### ISSUE TITLE
Can not find config data-source With versin 5.0.0-alpha 

### ISSUE THREAD

**Issue by SpinSi** [apache/shardingsphere#10009]
You are Chinase ,Why Engilish?

see  https://shardingsphere.apache.org/document/current/cn/overview/
Depend on  document 
ShardingSphere > 用户手册 > ShardingSphere-JDBC > 使用手册 > 数据分片
with spring namespace
and version 5.0.0-alpha
org.apache.shardingsphere
shardingsphere-jdbc-core-spring-namespace
5.0.0-alpha
we can not find this config
shardingsphere:data-source

**Comment by terrymanu** [comment]
Please show your error log

**Comment by terrymanu** [comment]
> You are Chinase ,Why Engilish?
> 

Because of Apache ShardingSphere is a global community and English is the global language of the world.

**Comment by terrymanu** [comment]
Closed because of no response anymore.

**Comment by SpinSi** [comment]
shardingsphere:data-source
配置标签是在哪定义的？
