### ISSUE TITLE
Can shdringahpere-proxy support sharding and replica query for the same t_order table at the same time?

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#10019]
Can shdringahpere-proxy support sharding and replica query for the same t_order table at the same time?

**Comment by terrymanu** [comment]
Yes, FYI:
shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/dbtbl_with_read_write_splitting/rules.yaml

**Comment by wl4g** [comment]
ok,   In addition, I would like to ask if there is a case of integration with https://github.com/openark/orchestrator or replication-manager   thanks!

**Comment by wl4g** [comment]
ok, In addition, I would like to ask if there is a case of integration with https://github.com/openark/orchestrator or replication-manager  thanks!

**Comment by wl4g** [comment]
Our department wants to encapsulate a complete new mysql ha solution, which can quickly deploy a proprietary cloud

**Comment by wl4g** [comment]
Our department wants to encapsulate a complete new mysql ha solution, which can quickly deploy a private cloud

**Comment by terrymanu** [comment]
No plan for orchestrator supporting, does anyone interest this issue?

**Comment by terrymanu** [comment]
I just close this issue because of no feedback for long time.
