### ISSUE TITLE
what's the sharding jdbc config "autoTables' mean?

### ISSUE THREAD

**Issue by CatYangWei** [apache/shardingsphere#10043]
where can i find the document or  the usage?

**Comment by tristaZero** [comment]
Hi @CatYangWei 
I have to say this feature is so great, and will be improved later.
FYI. https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/

**Comment by childewuque** [comment]
> Hi @CatYangWei
> I have to say this feature is so great, and will be improved later.
> FYI. https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/

What's difference between "tables" and "autoTables" in yaml, no more info about "autoTables"  by google&baidu. thanks.

**Comment by tristaZero** [comment]
autoTables` needs `ShardingAutoTableAlgorithm` to help users auto-sharding tables, [Config](https://github.com/apache/shardingsphere/blob/master/shardingsphere-jdbc/shardingsphere-jdbc-core/src/test/resources/config/config-sharding.yaml) is a exmpale.
@RaigorJiang are there other configs in our `examples`?

**Comment by RaigorJiang** [comment]
Hi @CatYangWei @childewuque 
`autoTable` is a feature to let users do not care about the specific distribution of the tables, just tell shardingsphere how many pieces to split the tables into.

There are currently no other documents and examples to illustrate `autoTable`, we will write an article to introduce this feature in the future.

Thanks for your attention.

**Comment by RaigorJiang** [comment]
Hello, we have published an article about `AutoTable`(in Chinese), hoping to answer all users’ doubts, please refer to:
https://mp.weixin.qq.com/s/fDYqW-yJIVpkcUDNT-gsuA

In addition, as the first user to raise `AutoTable-related` issues, the ShardingSphere community would like to express gratitude to you and prepared `a gift for you`. 
Please tell me your contact info (phone number, email or wechat ID) via email (raigor.jiang@gmail.com) , and we will contact you. 
Thank you!
