### ISSUE TITLE
Why do you use the default sub database rules and do not query according to the default configured rules

### ISSUE THREAD

**Issue by huangchenliang** [apache/shardingsphere#10076]
spring.shardingsphere.sharding.default-database-strategy.inline.sharding-column=market_id
spring.shardingsphere.sharding.default-database-strategy.inline.algorithm-expression=ds$->{"000".equals(market_id)? "2" : "1"}

**Comment by huangchenliang** [comment]
spring.shardingsphere.sharding.default-database-strategy.inline.sharding-column=market_id
spring.shardingsphere.sharding.default-database-strategy.inline.algorithm-expression=ds$->{"000".equals(market_id)? "2" : "1"}

**Comment by tristaZero** [comment]
So I did not catch you.
Which version is used? If there is no specific database strategy for that sharding table, default strategy will work.

**Comment by terrymanu** [comment]
No enough information, I just close the issue.
