### ISSUE TITLE
How sharding-jdbc config complex & hint sharding strategy together for same table

### ISSUE THREAD

**Issue by laravelshao** [apache/shardingsphere#10095]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
If has shardingColumn will use my custom complex sharding strategy, if has custom HintManager use hint sharding strategy.

### Actual behavior
But TableRuleConfiguration can only config for one sharding strategy. If config a table for hint sharding strategy, will always use hint sharding strategy. In version 3.0.0.M1 both sharding strategy can  work together.

**Comment by laravelshao** [comment]
@yu199195 Is sharding-jdbc support multi strategy for one table

**Comment by tristaZero** [comment]
Hi @laravelshao currently, sharding sphere does not support two different strategies for one single table.  But you can configure two sharding tables (Just different names) with two strategies.

**Comment by laravelshao** [comment]
@tristaZero How to configure two sharding tables for one single table, Can you give more information？
