### ISSUE TITLE
Implement SQLServerPrivilegeHandler and add unit test

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10102]
Hi, community,

This issue is to `override` the `create()`, `grantAll()`,  and `diff()` of `SQLServerPrivilegeHandler` and also add unit tests for them in `SQLServerPrivilegeHandlerTest`.

### Definitions
`create()`, means creating new users (from the signature) in the database.
`grantAll()` means granting super privileges to users (from the signature) in the database.
`diff()`, means getting the user list where the users do not exist in the database.

### Reference
#10075 and #10073 are for your references.

**Comment by RaigorJiang** [comment]
Hi @tristaZero , I want to do this.
