### ISSUE TITLE
Tool for transfer from ORACLE SQL rule to the rule in g4 file.

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#10104]
## Tool for transfer from Oracle SQL rule to the rule in g4 file.

 For example:
 This is Oracle rule
![image](https://user-images.githubusercontent.com/22066046/114962786-ef7e0680-9e9d-11eb-9f51-7121b8364993.png)
This is the rule in the g4 file
```
DROP TABLE tableName (CASCADE CONSTRAINTS)? (PURGE)?
```
Both rules are very like each other. Maybe we could try to build a tool for transferring automatically.

**Comment by wgy8283335** [comment]
The tool locates in the repository:
`https://github.com/wgy8283335/shardingsphere.git`
The tool locates in the directory:
`shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/tool`

**Comment by terrymanu** [comment]
It is out of range of ShardingSphere, I just close it.
