### ISSUE TITLE
Implement PostgreSQLPrivilegeHandler and add unit test

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10101]
Hi, community,

This issue is to `override` the `create()`, `grantAll()`,  and `diff()` of `PostregreSQLPrivilegeHandler` and also add unit tests for them in `PostgreSQLPrivilegeHandlerTest`.

### Definitions
`create()`, means creating new users (from the signature) in the database.
`grantAll()` means granting super privileges to users (from the signature) in the database.
`diff()`, means getting the user list where the users do not exist in the database.

### Reference
#10075 and #10073 are for your references.

**Comment by totalo** [comment]
Get it

**Comment by tristaZero** [comment]
This issue perfect fit you. :)
