### ISSUE TITLE
Implement OraclePrivilegeHandler and add unit test

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10100]
Hi, community,

This issue is to `override` the `create()`, `grantAll()`,  and `diff()` of `OraclePrivilegeHandler` and also add unit tests for them in `OraclePrivilegeHandlerTest`.

### Definitions
`create()`, means creating new users (from the signature) in the database.
`grantAll()` means granting super privileges to users (from the signature) in the database.
`diff()`, means getting the user list where the users do not exist in the database.

### Reference
#10075 and #10073 are for your references.

**Comment by Liangda-w** [comment]
Hi @tristaZero, may I try this issue:)
