### ISSUE TITLE
RangeShardingAlgorithm  Generic problem, specified as Date, actually a string

### ISSUE THREAD

**Issue by November22** [apache/shardingsphere#10119]
I specified the generic type as the time type, but in actual use it is indeed a string type, which makes me feel puzzled。
version: 4.1.1
Slice key: create_time
SQL：select * from t_trade where create_time >= '2021-07-12' order by create_time desc
RangeShardingAlgorithm：
![image](https://user-images.githubusercontent.com/26109828/115133653-7bc63000-a03c-11eb-8e43-2721ae1e4bcb.png)

Exception：
java.lang.ClassCastException: java.util.Date cannot be cast to java.lang.String

**Comment by RaigorJiang** [comment]
Hi @November22 ,  is this problem exists in version 5.0.0?   did you have a try?

**Comment by November22** [comment]
is there a release version of 5.0.0? I want to use version 4.1。
In fact, the generic type of StandardShardingAlgorithm does not convert or verify the actual value。I specify a BigInteger type as Date type, and no error will be reported。 I think this should be converted, and an exception is thrown if the conversion fails.
![image](https://user-images.githubusercontent.com/26109828/115192475-6ffe6a80-a11d-11eb-8d38-36ecc37aff8a.png)

**Comment by November22** [comment]
Sorry, ClassCastException is indeed thrown when doing actual value acquisition. 
Now I have a doubt. When actually inserting or querying, instead of creating SQL by replacing values, I use string values directly in SQL, such as create_time> '2021-04-19', then the incoming points The slice value type is a string, although it is a time type in the database.
version: 5.0.0-alpha 
![image](https://user-images.githubusercontent.com/26109828/115193844-43e3e900-a11f-11eb-992f-338915417b44.png)

**Comment by tristaZero** [comment]
Hi as @RaigorJiang said, we have fixed this one from 5.x release.

**Comment by November22** [comment]
OK, when is the release time of 5. X? ☺

**Comment by tristaZero** [comment]
Hi please try the release one, i.e., 5.0.0-alpha
