### ISSUE TITLE
why sharding-jdbc-spring-boot-starter still in 4.1.1 ?

### ISSUE THREAD

**Issue by zhangdc007** [apache/shardingsphere#10118]
In use sharding-jdbc-spring-boot-starter 4.1.1 and Spring boot 2.4.4
and find load metadata very slow,I see the bug is fix in 5.0.0-alpha in 10 Nov 2020,but sharding-jdbc-spring-boot-starter still in 4.1.1,and how can I update to 5.0.0-alpha in use of sharding-jdbc-spring-boot-starter

**Comment by RaigorJiang** [comment]
@zhangdc007   
see https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-sharding-spring-boot-starter

**Comment by tristaZero** [comment]
@RaigorJiang Nice.
