### ISSUE TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of alter session

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10111]
This issue is the subsequent one from [#9603](https://github.com/apache/shardingsphere/pull/9603#issuecomment-796600731).

Oracle Ref -> https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlqr/SQL-Statements.html#GUID-CE009C87-4AA6-45BF-9A0D-2B2C5FFB47B3

**Comment by tristaZero** [comment]
Hi @ThanoshanMV , this one is yours. :)
Could you comment here so that I can assign it to you?

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'll try this one.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, next, I'll try [ALTER SYSTEM](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-SYSTEM.html#GUID-2C638517-D73A-41CA-9D8E-A62D1A0B7ADB).

**Comment by tristaZero** [comment]
@ThanoshanMV Go ahead.
BTW, your GSoC 2021 application is approved now. Let us wait its timeline moving.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'll start work on [Oracle SELECT statement](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6) as it's hard and other DML statements depend on `SELECT` statement's rules.

**Comment by tristaZero** [comment]
@ThanoshanMV Yep, but you can proofread it by successive PRs.

**Comment by ThanoshanMV** [comment]
Okay @tristaZero, I'll proofread it by successive PRs.

**Comment by tristaZero** [comment]
Done.
