### ISSUE TITLE
field 'text'

### ISSUE THREAD

**Issue by 17602541404** [apache/shardingsphere#10128]
Is 'text' a keyword? The field name of a table is 'text', and an error occurs when SQL is executed.
If so, is there any other solution besides changing the field name? please!

**Comment by RaigorJiang** [comment]
@17602541404  Yes, 'TEXT' is a keyword.
please see https://dev.mysql.com/doc/refman/5.7/en/keywords.html

You can write the SQL with '`'   as '`text`'

**Comment by 17602541404** [comment]
> @17602541404 Yes, 'TEXT' is a keyword.
> please see https://dev.mysql.com/doc/refman/5.7/en/keywords.html
> 
> You can write the SQL with quote as `text`

It worked, thanks

**Comment by RaigorJiang** [comment]
You are welcome.   Is this issue can be closed?
