### ISSUE TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of ALTER SYNONYM

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10136]
This issue is the subsequent one from [#9603](https://github.com/apache/shardingsphere/pull/9603#issuecomment-796600731).

Oracle Ref -> https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlqr/SQL-Statements.html#GUID-CE009C87-4AA6-45BF-9A0D-2B2C5FFB47B3

**Comment by tristaZero** [comment]
@zhujunxxxxx will take it over.

**Comment by zhujunxxxxx** [comment]
@tristaZero I found `alter database` is not support, i will fix it.

**Comment by tristaZero** [comment]
Done.
