### ISSUE TITLE
Shardingscaling does not support mysql 5.5.38;

### ISSUE THREAD

**Issue by poxiao1266** [apache/shardingsphere#10134]
Shardingscaling does not support mysql 5.5.38;an error is reported when used; the error message is as follows: 

 org.apache.shardingsphere.scaling.core.exception.PrepareFailedException: Source data source check variables failed. at org.apache.shardingsphere.scaling.mysql.MySQLDataSourceChecker.checkVariable(MySQLDataSourceChecker.java:93) at org.apache.shardingsphere.scaling.mysql.MySQLDataSourceChecker.checkVariable(MySQLDataSourceChecker.java:83) at org.apache.shardingsphere.scaling.core.job.preparer.ShardingScalingJobPreparer.checkDataSources(ShardingScalingJobPreparer.java:93) at org.apache.shardingsphere.scaling.core.job.preparer.ShardingScalingJobPreparer.prepare(ShardingScalingJobPreparer.java:69) at org.apache.shardingsphere.scaling.core.ScalingJobController.start(ScalingJobController.java:54) at org.apache.shardingsphere.scaling.web.HttpServerHandler.startJob(HttpServerHandler.java:99) at org.apache.shardingsphere.scaling.web.HttpServerHandler.channelRead0(HttpServerHandler.java:73) at org.apache.shardingsphere.scaling.web.HttpServerHandler.channelRead0(HttpServerHandler.java:52) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLException: Illegal operation on empty result set. at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:790) at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5213) at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5136) at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java) at org.apache.shardingsphere.scaling.mysql.MySQLDataSourceChecker.checkVariable(MySQLDataSourceChecker.java:101) at org.apache.shardingsphere.scaling.mysql.MySQLDataSourceChecker.checkVariable(MySQLDataSourceChecker.java:90) ... 35 common frames omitted

**Comment by menghaoranss** [comment]
which version of ShardingSphere do you use, and have you tried other versions of mysql?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
