### ISSUE TITLE
ShardingSphere Agent is broken

### ISSUE THREAD

**Issue by dmsolr** [apache/shardingsphere#10141]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Reason analyze (If you can)

I notice that many PRs shardingsphere-agent checker run failure. Seem likes some API agent instrumented is out of date.

**Comment by menghaoranss** [comment]
@yu199195 could you please follow up on this issue?

**Comment by terrymanu** [comment]
Fixed now
