### ISSUE TITLE
Clear business logic with PostgreSQLBinaryStatementRegistry

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10184]
The PostgreSQLBinaryStatementRegistry is different with MySQLBinaryStatementRegistry.

The scope of MySQLBinaryStatementRegistry is for proxy instance, all connections share same MySQLBinaryStatement map, key of binaryStatements is `statementID`, value is `SQL, parameters and parameter types`.

But the scope of PostgreSQLBinaryStatementRegistry is for connection instance, per connection hold independent PostgreSQLBinaryStatement map, key is `connectionID`, value is `ConnectionScopeBinaryStatementRegistry`, and `ConnectionScopeBinaryStatementRegistry` hold another map, key is `statementID`, value is `SQL, parameters and parameter types`.

Obviously, PostgreSQLBinaryStatementRegistry has one more layer than MySQLBinaryStatementRegistry.

Please clear the PostgreSQLBinaryStatementRegistry data structure. It is better to use same data structure with MySQLBinaryStatementRegistry if possible.

The PR #10185 is use status to control connection inactive. If using MySQL impl style, the PR #10185 maybe revert.

**Comment by terrymanu** [comment]
The new PR #10186 used running task count instead of in use status, consider revert them together.

**Comment by TeslaCN** [comment]
I want to know is it possible to unify connection id and channel id.
