### ISSUE TITLE
Striongly suggest to add new config for setting whether all tables are default sharded or not, then simplifying this kind of configuration

### ISSUE THREAD

**Issue by zhonghuali** [apache/shardingsphere#10199]
Strongly suggest to add new config for setting whether all tables are default sharded or not, then simplifying this kind of configuration

_Originally posted by @zhonghuali in https://github.com/apache/shardingsphere/issues/7196#issuecomment-826602578_

**Comment by tristaZero** [comment]
So you think the `defaultDatabaseStrategy`  and `defaultTableStrategy` is not enough for your case?

**Comment by zhonghuali** [comment]
> So you think the `defaultDatabaseStrategy` and `defaultTableStrategy` is not enough for your case?
I think the `defaultDatabaseStrategy` and `defaultTableStrategy` does't provide correct/user-friendly behaviours. 
as you know, it require to configure a table name for those intending to use defaultDatabaseRulerule, but there are many tables ,and these table or data souce may be added  in some time, then we have to change the configuration every time.  As I gave the default database rule, these default rules should be defaultly applied to these tables without specific table rules.   if I  gave a default rule, then I have to give a table rule config which is default rule.  I think it doesn't make sense. 

In a word, if I give the `defaultDatabaseStrategy` and `defaultTableStrategy` ,and all of tables in my db would be sharded, then I expect to no more configuration for tables.

**Comment by tristaZero** [comment]
Hi we have to distinguish which part of the configuration is shared and which one is not.

`defaultDatabaseStrategy` and `defaultTableStrategy` are shared for each sharding table, but `actual datanodes` is different for them in most cases. Therefore that part has to be configured accordingly.
