### ISSUE TITLE
The following problems are found in the project transformation sharding-jdbc 4.1.1 scheme

### ISSUE THREAD

**Issue by 243006306** [apache/shardingsphere#10196]
The following problems are found in the project transformation sharding-jdbc 4.1.1 scheme

1. Why does hint still need to go through the parsing process? Because my SQL is relatively complex (subquery, Union). Now if I find that the problem can not be resolved, I will randomly select a data source and do not enter the hash function of the hint algorithm. This makes me puzzled. I feel that if I can't resolve it, I can throw out the exception, A data source should not be randomly selected, and the hint mode should be able to skip the parsing process and merging process.

2. When I only split the database, the default partition rule does not take effect. I need to configure actual data nodes. I have hundreds of tables in a database. I think this is unreasonable. I should use wildcards, or if it is not configured by default, it is the whole database, or add and exclude some tables to configure.

**Comment by 243006306** [comment]
Force routing does not work, do not enter 'HintShardingAlgorithm`

**Comment by RaigorJiang** [comment]
Hi @243006306 
Could you please provide a configuration and SQL, so we can reproduce it.

**Comment by 243006306** [comment]
SQL is like this `SELECT x.column_1,x.column_2  FROM( SELECT a.column_1,o.column_2 FROM A a INNER JOIN b b ON b.id = a.order_id  AND b.mof_id = 'xxxxxx'  WHERE  a.xxx='xxx' and b.xxx='xxx' UNION SELECT a.column_,o.column_1 FROM A a INNER JOIN b b ON b.id = a.order_id  AND b.mof_id = 'xxxxxx'  WHERE  a.xxx='xxx' and b.xxx='xxx') x order by column_1,column_2 `

**Comment by 243006306** [comment]
Configuration is like this ：
`spring.shardingsphere.sharding.binding-tables[0]=A,B
spring.shardingsphere.sharding.tables.A.actual-data-nodes=
spring.shardingsphere.sharding.tables.B.actual-data-nodes=
spring.shardingsphere.sharding.default-database-strategy.hint.algorithm-class-name=com.szjz.cloud.algorithm.IdHintAlgorithm
`

**Comment by 243006306** [comment]
My debug test found that the interpretation of SQL failed, so I chose the route of the random data source, just like the route of the Ping SQL test sent after starting the project without specifying the default data source. I want the 'hint' mode to go directly to my 'hintalgorithm' class without parsing, because I only need the sub database. I found that the 'select x.x from' with the outermost package removed, You can parse successfully and go to the custom 'hintalgorithm' slicing algorithm. I wonder why the parsing fails without reporting an error

**Comment by 243006306** [comment]
我DEBUG测试发现解释SQL失败，所以选择了随机数据源的路由，就像未指定默认数据源启动项目后发送的ping SQL测试所走的路由一样，我想`HINT`模式不经过解析，直接走向我的`HintAlgorithm`类，因为我只需要分库，我测试发现去除最外层包裹的`SELECT X.X FROM `，就可以解析成功并走向自定义的`HintAlgorithm`分片算法,我很疑惑，为什么解析失败不报错

**Comment by tristaZero** [comment]
Hi, have you ever check the log? Is there any exception info?

**Comment by 243006306** [comment]
@tristaZero My debug observation did not report an error, because there was a sub query in SQL that could not parse the table name, resulting in routing to the random data source

**Comment by tristaZero** [comment]
Hi, `sub query` is supported better from the 5.x  release, could you try the 5.0.0-alpha?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
