### ISSUE TITLE
读写分离配合分表，分表失效

### ISSUE THREAD

**Issue by Victoryli** [apache/shardingsphere#10198]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
读写分离配合分表
### Actual behavior
在分表生效的基础上，加入读写分离的配置，分表失效，只是读写分离生效
## Question
为什么分表失效
### Example codes for reproduce this issue (such as a github link).
application.yml 文件配置如下：

`spring:
  shardingsphere:
    datasource:
      names: shardingmaster,shardingslave # 最好不要有特殊字符
      shardingmaster:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://xxxxxxx:3306/shardingsphere1?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&connectTimeout=10000&socketTimeout=100000&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
      shardingslave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://xxxxxx:3306/xxxxx?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&connectTimeout=10000&socketTimeout=100000&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: 'ROUND_ROBIN'
      master-data-source-name: 'shardingmaster'
      name: datasource
      slave-data-source-names: 'shardingslave'

    sharding:
      tables:
        account_generate_mq_log: # 表名
          table-strategy:
            standard:
              sharding-column: account_time # 分片字段
              precise-algorithm-class-name: com.xxx.sharding.config.PreciseSharingTableAlgorithmOfAccountGenerateMqLog
              range-algorithm-class-name: com.xxxsharding.config.RangeShardingAlgorithmOfAccountGenerateMqLog
          actual-data-nodes: account_generate_mq_log_$->{[202104]}
    props:
      sql:
        show: true`

**Comment by menghaoranss** [comment]
For English only, other languages will not accept.
