### ISSUE TITLE
Throw exception message error

### ISSUE THREAD

**Issue by DreamSaddle** [apache/shardingsphere#10191]
Missing `String.format()` In file [JDBCLockEngine#checkTableLock](https://github.com/apache/shardingsphere/blob/master/shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/executor/JDBCLockEngine.java#L106) .

```java
private void checkTableLock(final ShardingSphereLock lock, final Collection<String> tableNames) throws SQLException {
      for (String tableName : tableNames) {
          if (lock.isLocked(LockNameUtil.getTableLockName(DefaultSchema.LOGIC_NAME, tableName))) {
              // Missing format
              throw new SQLException("Table %s is locked");
          }
      }
  }
```

**Comment by RaigorJiang** [comment]
@DreamSaddle  Thank you, would you like to make a PR?

**Comment by DreamSaddle** [comment]
Yes, it would be my pleasure

**Comment by DreamSaddle** [comment]
@RaigorJiang Yes, it would be my pleasure

**Comment by RaigorJiang** [comment]
Welcome :)
