### ISSUE TITLE
Reduce code complexity and improve readability for ShardingUnicastRoutingEngine

### ISSUE THREAD

**Issue by MingxingLAI** [apache/shardingsphere#10202]
When I read the source code of this project, The code readability of this [file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/unicast/ShardingUnicastRoutingEngine.java) is significantly lower than other files.

Optimization suggestion：

- Reduce the length of the  route function
- Reduce code nesting depth

**Comment by RaigorJiang** [comment]
Good idea 👍
