### ISSUE TITLE
Could you merge some useful code to 4.1.x

### ISSUE THREAD

**Issue by IcebergXTY** [apache/shardingsphere#10223]
## Question

As 5.0.0 is still alpha version, we just use 4.1.1 now. And we found some bug in this version like #5882 and #8574.

It seems like you are just maintain one version at a time now. But the new version takes too long that we can't wait it anymore...

So could you merge some code to 4.1.x to fix some serious bugs? Thanks 😃

**Comment by tristaZero** [comment]
Hi @IcebergXTY 
Sorry to say that 4.x will have no subsequent releases anymore. We suggest you try 5.0.0-alpha which has many bug-fixing and improvements.

**Comment by IcebergXTY** [comment]
> Hi @IcebergXTY
> Sorry to say that 4.x will have no subsequent releases anymore. We suggest you try 5.0.0-alpha which has many bug-fixing and improvements.

Well, thank you anyway for your quick reply
