### ISSUE TITLE
SQLFeatureNotSupportedException("setNString")

### ISSUE THREAD

**Issue by ly164608001** [apache/shardingsphere#10224]
database type is ORACLE，there is not allowed insert when table column type is NVARCHAR2，think about supported whether or not?

**Comment by avalon5666** [comment]
Pls provider the complete sql, and which shardingsphere version

**Comment by avalon5666** [comment]
Can you use varchar instead of nvarchar?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
