### ISSUE TITLE
Antlr ParseTree error when database field is "POINT"

### ISSUE THREAD

**Issue by leonbond** [apache/shardingsphere#10259]
```
import org.antlr.v4.runtime.tree.ParseTree;
import org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor;
import org.junit.Test;

import javax.xml.bind.SchemaOutputResolver;

public class T1 {
    @Test
    public void t1() {
        ParseTree parseTree = new SQLParserExecutor("MySQL", "insert into T_NAME (POINT) values (?)").execute().getRootNode();
    }
}
```
This code will report the following error:
```
line 1:20 no viable alternative at input '(POINT'
```
Only the word "POINT" doesn’t work. Why? Is it a keyword?
The shardingsphere version is 4.1.1

**Comment by Liangda-w** [comment]
Hi @leonbond are you trying with the latest version?

It works in my testing:

![image](https://user-images.githubusercontent.com/66914151/117368558-fb208400-aec3-11eb-906f-6f52b44a60e0.png)

**Comment by leonbond** [comment]
@Liangda-w This is my pom config. It's Java project. Can i have a look at your code?
<dependency>
                        <groupId>org.apache.shardingsphere</groupId>
                        <artifactId>sharding-jdbc-spring-namespace</artifactId>
                        <version>4.1.1</version>
                        <exclusions>
                                <exclusion>
                                        <artifactId>antlr4-runtime</artifactId>
                                        <groupId>org.antlr</groupId>
                                </exclusion>
                        </exclusions>
                </dependency>
                <dependency>
                        <artifactId>antlr4-runtime</artifactId>
                        <groupId>org.antlr</groupId>
                        <version>4.7.1</version>
                </dependency>

**Comment by Liangda-w** [comment]
Since this is an Antlr parsing exception, I just tested the rule with Antlr Preview.
The latest version is 5.0.0-alpha, so upgrade should help:)

**Comment by leonbond** [comment]
@Liangda-w Still thank you!

**Comment by leonbond** [comment]
@tristaZero I have tried several versions of antlr, including 4.7.2 4.7.1 and so on,  while the version of sharding-jdbc is 4.1.1, they all report errors

**Comment by leonbond** [comment]
> Since this is an Antlr parsing exception, I just tested the rule with Antlr Preview.
> The latest version is 5.0.0-alpha, so upgrade should help:)

5.0.0-alpha works, no more error.

**Comment by bkiers** [comment]
> ... From @bkiers 's comment, It looks it is a bug from Antlr. ...

No, that was not what I meant. The problem is with one of the `.g4` grammar files in this repository. This is **not** a bug in ANTLR 4.7.2 (or some other version). I see this bug a lot on stackoverflow. The issue is outlined in the related SO Q&A linked in this issue. 

More background information can be found if you Google on "keyword identifier issue antlr": https://www.google.com/search?channel=fs&client=ubuntu&q=keyword+identifier+issue+antlr

**Comment by jingshanglu** [comment]
> > ... From @bkiers 's comment, It looks it is a bug from Antlr. ...
> 
> No, that was not what I meant. The problem is with one of the `.g4` grammar files in this repository. This is **not** a bug in ANTLR 4.7.2 (or some other version). I see this issue a lot on stackoverflow. The issue is outlined in the related SO Q&A linked in this issue.
> 
> More background information can be found if you Google on "keyword identifier issue antlr": https://www.google.com/search?channel=fs&client=ubuntu&q=keyword+identifier+issue+antlr

@bkiers @tristaZero Yes, the problem is with `g4` file, now 5.0.0-alpha works.

**Comment by tristaZero** [comment]
Hi @bkiers ,

Thanks for your clarificaiton, l mistook your words. Also, thanks for your answer on `stack` page.

**Comment by leonbond** [comment]
@jingshanglu By the way, do you know when the official version of 5.x will be released?
