### ISSUE TITLE
route sql tables do not have any sharding table,should let pass,do not check sql.

### ISSUE THREAD

**Issue by DongJigong** [apache/shardingsphere#10257]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
           <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-core</artifactId>
                <version>4.1.1</version>
            </dependency>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
    ShardingSphere-JDBC
### Expected behavior
  should not check sql which does not contains sharding tables
### Actual behavior
  SELECT             COUNT(DISTINCT d.device_code) devSum,             SUM(d.qr_num) portNum,             SUM(CASE WHEN d.state = 0 THEN d.qr_num END) unUseQrNum,             SUM(CASE WHEN d.state = 1 THEN d.qr_num END) useQrNum,             d.`status` status         FROM             (SELECT             dev.device_code,             dev.`status`,             COUNT(ite.`qr_num`) qr_num,             ite.state,             dev.org_id             FROM charge_match_device dev             LEFT JOIN charge_match_device_items ite on dev.device_code = ite.device_code             GROUP BY dev.device_code,ite.state) d          WHERE   d.org_id = 1  OR d.org_id IN (SELECT c.org_id  FROM sys_org c  WHERE FIND_IN_SET(1, c.ancestors))          GROUP BY d.`status`
### Reason analyze (If you can)
Caused by: java.lang.IllegalStateException: Can not find owner from table.
	at org.apache.shardingsphere.sql.parser.binder.segment.select.projection.engine.ProjectionsContextEngine.find(ProjectionsContextEngine.java:197)

**Comment by avalon5666** [comment]
The subqery not support, or try the mater branch version.
Pls Reference the [documents](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/)

**Comment by DongJigong** [comment]
> The subqery not support, or try the mater branch version.
> Pls Reference the [documents](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/)

I think these sqls that don't contains sharding tables shall not check grammer and let pass.

**Comment by DongJigong** [comment]
> Try [Hint](https://shardingsphere.apache.org/document/current/en/features/sharding/concept/hint/)

HintManager won't help me. I am not sure if Hint can resole my problem. In my option, it only strongly use sharding rule,but my sql shall pass without sharding rule,because sql  desn't contains sharding table.

**Comment by strongduanmu** [comment]
@DongJigong Thank you very much for your feedback. At present, ShardingSphere is not perfect in handling temporary table aliases. I will try to fix this problem in the master branch.

**Comment by strongduanmu** [comment]
@DongJigong With 4.1.1 version, you can rewrite sql like this:
```sql
SELECT COUNT(DISTINCT device_code) AS devSum, SUM(qr_num) AS portNum
	, SUM(CASE
		WHEN state = 0 THEN qr_num
	END) AS unUseQrNum, SUM(CASE
		WHEN state = 1 THEN qr_num
	END) AS useQrNum
	, status AS status
FROM (
	SELECT dev.device_code, dev.status, COUNT(ite.qr_num) AS qr_num, ite.state
		, dev.org_id
	FROM charge_match_device dev
		LEFT JOIN charge_match_device_items ite ON dev.device_code = ite.device_code
	GROUP BY dev.device_code, ite.state
) d
WHERE org_id = 1
	OR org_id IN (
		SELECT c.org_id
		FROM sys_org c
		WHERE FIND_IN_SET(1, c.ancestors)
	)
GROUP BY status;
```

**Comment by DongJigong** [comment]
> @DongJigong With 4.1.1 version, you can rewrite sql like this:
> 
> ```sql
> SELECT COUNT(DISTINCT device_code) AS devSum, SUM(qr_num) AS portNum
> 	, SUM(CASE
> 		WHEN state = 0 THEN qr_num
> 	END) AS unUseQrNum, SUM(CASE
> 		WHEN state = 1 THEN qr_num
> 	END) AS useQrNum
> 	, status AS status
> FROM (
> 	SELECT dev.device_code, dev.status, COUNT(ite.qr_num) AS qr_num, ite.state
> 		, dev.org_id
> 	FROM charge_match_device dev
> 		LEFT JOIN charge_match_device_items ite ON dev.device_code = ite.device_code
> 	GROUP BY dev.device_code, ite.state
> ) d
> WHERE org_id = 1
> 	OR org_id IN (
> 		SELECT c.org_id
> 		FROM sys_org c
> 		WHERE FIND_IN_SET(1, c.ancestors)
> 	)
> GROUP BY status;
> ```

Thanks. I have rewrite my sql to solve this problem. I hope that problems like this can be solved quickly.
