### ISSUE TITLE
The primary  key is sharding column created the key  value by the  GeneratedKey config 。 is it okay？

### ISSUE THREAD

**Issue by XUZHOUWANG** [apache/shardingsphere#10274]
**table：**

@TableName("t_user")
@Data
public class User implements Serializable {

    @TableId(type = IdType.INPUT)
    private Long id;
    private String name;
    private Date gmtCreate;
    private Date gmtModified;
    private String phone;
    private Integer isDeleted;

}

**config**

 sharding:
      tables:
        t_user:
          actual-data-nodes: skshardingjdbc.t_user_$->{0..1}
          logicTable: t_user
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: t_user_$->{id % 2}
          keyGenerator:
            type: UUID
            column: id

**error** 

### Cause: java.lang.IllegalArgumentException: Sharding value must implements Comparable.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 37 more

**Comment by avalon5666** [comment]
Use "@TableId(type = IdType.AUTO)"

**Comment by avalon5666** [comment]
1. Use "@TableId(type = IdType.AUTO)"
2. id's type in class not match uuid

**Comment by XUZHOUWANG** [comment]
https://blog.csdn.net/qiaoqiyu6416/article/details/107044664/

**Comment by XUZHOUWANG** [comment]
> 1. Use "@TableId(type = IdType.AUTO)"
> 2. id's type in class not match uuid

no，I want to create the id by shardingsphere; the definition of  User is okay.

**Comment by avalon5666** [comment]
Follow step 1 ~ 2

**Comment by XUZHOUWANG** [comment]
> Follow step 1 ~ 2

it‘s okay. but i want to the value of the   primary key  created by the snowflake set by the sharding configuration. while step 1~2,the id is created by the mybatis-plus framework.

**Comment by avalon5666** [comment]
How to confirm the id is created by the mybatis-plus framework?

**Comment by avalon5666** [comment]
"IdType.AUTO" is created by the database，it will create by shardingsphere database middleware

**Comment by XUZHOUWANG** [comment]
> "IdType.AUTO" is created by the database，it will create by shardingsphere database middleware，mybatis-plus do nothing.

it's okay. I try it. it's fine. I know the "IdType.ASSIGN_ID" procedure. But I don't really try the "IdType.AUTO". thank you
