### ISSUE TITLE
PostgreSQL `SHOW xxx` syntax conflicting with DistSQL

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10271]
As you know, ShardingSphere defines [DistSQL](https://shardingsphere.apache.org/document/current/cn/features/dist-sql/) for distributed metadata queries. 

There is an issue that `SHOW xxx` DistSQL has conflicts with PostgreSQL standard SQL syntax.

### How to reproduce?
- Start Proxy using PostgreSQL
- Execute DistSQL `show REPLICA_QUERY rule from schem_name`

### Expected and actual results
**Expected** 
`ShardingSphereSQLParserEngine` return `ShowRuleStatement`.
**Actual**
`ShardingSphereSQLParserEngine` return `PostgreSQLShowStatement`.

### Some hints for solution
- Please check the definition of `show` in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql/DALStatement.g4` is aligned with PostgreSQL or not
- Consider working on its definition to avoid the visitor entering into `show colId` branch

**Note**
I am unsure these hints can help us fix this conflict, but it is worth more investigation since this method is the cheapest for pushing the development of the DistSQL feature. If you have any progress, please contact me.

**Comment by strongduanmu** [comment]
@tristaZero I tested PG `show statement` parsing, and found that antlr can match invalid content by default, which caused the `show statement` in distsql to fail to be executed. By specifying a explicit `EOF` lexical symbol, we can force to match all inputs, and invalid content will cause exceptions. 

Before adding `EOF`:
![image](https://user-images.githubusercontent.com/10829171/117523407-fefaf600-afea-11eb-8307-06cd83223cf0.png)

After adding `EOF`:
![image](https://user-images.githubusercontent.com/10829171/117523479-1c2fc480-afeb-11eb-8a7d-f9d69243ffc7.png)

**Comment by tristaZero** [comment]
@strongduanmu Bingo, elegant. :)
