### ISSUE TITLE
Can not load schema and tables from MySQL Workbench

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10275]
When using MySQL Workbench to connect proxy, the schema and tables can not show in schema view.
The exception is occur: `Error Code: 0 MySQL_ResultSet::getString: invalid value of 'columnIndex'`

Version of MySQL Workbench: 8.0.24
Version of MySQL Cli: 8.0.23

**Comment by RaigorJiang** [comment]
It is in progress, the update will be posted in https://github.com/apache/shardingsphere/issues/11994.
 I will close the current issue.
