### ISSUE TITLE
 shardingsphere-scaling transfer -1 to 255 for TINYINT when IN 'EXECUTE_INCREMENTAL_TASK'

### ISSUE THREAD

**Issue by huntkalio** [apache/shardingsphere#10314]
## Bug Report
1.I use the master version of  shardingsphere-scaling to test database scaling.I have a table which has a column like this:
`client_type` TINYINT(2) NULL DEFAULT '-1';

2.when running shardingsphere-scaling transfer '-1'  value to '255' value.Then the sql will transfer like this：
insert into test(id,client_type) values(1,255)......;

3.I found that MySQLTinyBinlogProtocolValue.java use MySQLPacketPayload   readInt1() to read the value，but MySQLPacketPayload use ‘readUnsignedByte()’  to read value.

4.MySQLShortBinlogProtocolValue and other may have the same problem.

**Comment by RaigorJiang** [comment]
ref to #5868
This issue may needs some discussion  @tristaZero

**Comment by tristaZero** [comment]
Hi @huntkalio ,
Thanks for your report and debug. So we mainly locate this issue is about `MySQL protocol, right?
@TeslaCN could you give this one a double-checking? 
@RaigorJiang Do you have any idea dealing with this one?

**Comment by RaigorJiang** [comment]
I have a question, why we changed it to unsigned in 5868?

**Comment by huntkalio** [comment]
@tristaZero ，I think we can't distinguish whether it is signed or unsigned only by MySQL binlog protocol，may need to use the table meta info.

**Comment by tristaZero** [comment]
Maybe, like [Table Metadata](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/schema/model/TableMetaData.java)?

@tristaZero

**Comment by huntkalio** [comment]
yes,may add something like this：

https://github.com/alibaba/canal/blob/master/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/TableMeta.java

**Comment by tristaZero** [comment]
@huntkalio Similar.

Actually, I have no idea how and why we fix #5868. Maybe the assignee of that issue can give us some hints. @tuohai666 

Besides, I still confused by @huntkalio described in this  issue, 
> I found that MySQLTinyBinlogProtocolValue.java use MySQLPacketPayload readInt1() to read the value，but MySQLPacketPayload use ‘readUnsignedByte()’ to read value.

Maybe we start by figuring this part out. @RaigorJiang  Like @huntkalio 's comment, it looks like `table metadata` is required.

@huntkalio This issue just impacts sharding-scaling, doesn't it? @avalon5666 If available, could you give it a look?

**Comment by avalon5666** [comment]
I will check this.

**Comment by huntkalio** [comment]
@tristaZero  I only test sharding-scaling and found this problem。
