### ISSUE TITLE
How can i change listening port 3307 to  3306 ?

### ISSUE THREAD

**Issue by darlinglele** [apache/shardingsphere#10315]
I have check the document, but did found the option for listening port

**Comment by RaigorJiang** [comment]
Hi @darlinglele 
Do you mean sharding-proxy?   
`ShardingSphere-Proxy uses 3307 port in default. Users can start the script parameter as the start port number, like bin/start.sh 3308.`
see https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/usage/startup/

**Comment by darlinglele** [comment]
Good, thank you very much!
