### ISSUE TITLE
The auto generated files from ANTLR may push to GitHub

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10311]
The auto generated files from ANTLR are located on `/gen` folder which may push to GitHub if committer careless.

The solutions to be resolved problems:

1. Make generated codes from `/gen` to `target/gen` (I prefer this way)
2. Or add `/gen` to .gitignore file

**Comment by TeslaCN** [comment]
Consider configuring your ANTLR output disectory.

![image](https://user-images.githubusercontent.com/20503072/117924574-88cafc00-b328-11eb-8e0c-b26500a78a80.png)
