### ISSUE TITLE
What a suitable prop value to max.connections.size.per.query 

### ISSUE THREAD

**Issue by shixinxin6** [apache/shardingsphere#10328]
## Question

Version ： 4.1.1
Sharding JDBC

Too slow start for default value

Start Locked for value is 50
![image](https://user-images.githubusercontent.com/43789167/118088107-255ccf00-b3f9-11eb-8f34-11f830184699.png)

**Comment by terrymanu** [comment]
Please read https://shardingsphere.apache.org/document/current/en/features/sharding/principle/execute/

**Comment by shixinxin6** [comment]
thank you
