### ISSUE TITLE
The project started very slowly

### ISSUE THREAD

**Issue by henjuese** [apache/shardingsphere#10333]
Loading 3 logic tables' meta data  
Loading 3369 tables' meta data
..........
Start up stuck for a long time
Loading metadata is very slow

**Comment by yllions** [comment]
you can config the `spring.sharding.props.max.connections.size.per.query` param greater. for example 16 or 32.

**Comment by SteNicholas** [comment]
@henjuese , have you tried to update the `spring.sharding.props.max.connections.size.per.query` configuration?

**Comment by henjuese** [comment]
max.connections.size.per.query: 50 is OK
