### ISSUE TITLE
Add more assertions of GovernanceFacadeTest.assertInit()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10345]
use reflection to assert attributes of GovernanceFacade.

Just search `// TODO` from class `GovernanceFacadeTest` to find hint

**Comment by JooKS-me** [comment]
@terrymanu Hi, can I try it?

**Comment by SteNicholas** [comment]
@JooKS-me , I have assigned this to you. Please go ahead to complete this.
