### ISSUE TITLE
Add test case for RegistryCenterRepositoryFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10346]

**Comment by totalo** [comment]
hello  can i try to do this ?

**Comment by SteNicholas** [comment]
@totalo , have you discussed with @terrymanu what need to do for this task? If you know what to do, I can assign this to you.

**Comment by totalo** [comment]
> @totalo , have you discussed with @terrymanu what need to do for this task? If you know what to do, I can assign this to you.

Thank you very much. For the test, I think I can try it first based on my understanding of the code. After the completion, I can trouble everyone to review and discuss.😁
