### ISSUE TITLE
data migration config

### ISSUE THREAD

**Issue by wavelet123** [apache/shardingsphere#10349]
Hi Team,
We need to migrate  one houndred millions records into 1000 sharding tables.
Could you please advise how to recognize the source table in sharding proxy?

what I want to do is
insert into account_friend_012(sharding table) select * from source.account_friend (source table)where id=1;

but with following configuration,I can only see the sharding table.please advise.

dataSources:
  ds_0:
    url: jdbc:mysql://1.1.1.1:3307/friends?serverTimezone=GMT%2B2&useSSL=false
    username: shardingadmin
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 180000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
shardingRule:
  tables:
    t_accountfriend:
      actualDataNodes:  ds_0.accountfriend_${0..999}
      tableStrategy:
        inline:
          shardingColumn: FFirstAccountID
          algorithmExpression: accountfriend_$->{FFirstAccountID % 1000}
  defaultTableStrategy:
dataSources:
  ds_0:
    url: jdbc:mysql://1.1.1.1:3307/friends?serverTimezone=GMT%2B2&useSSL=false
    username: shardingadmin
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 180000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
shardingRule:
  tables:
    t_accountfriend:
      actualDataNodes:  ds_0.accountfriend_${0..999}
      tableStrategy:
        inline:
          shardingColumn: FFirstAccountID
          algorithmExpression: accountfriend_$->{FFirstAccountID % 1000}
  defaultTableStrategy:
    none:
  defaultDataSourceName: ds_0

thanks

**Comment by wavelet123** [comment]
I mean how to config to check the other no-sharding tables in one datasource

**Comment by tristaZero** [comment]
Hi  @wavelet123 ,

`Check non-sharding` tables?  Does that mean to show  `non-sharding` tables in  Proxy?
If you use 5.0.0-alpha, all non-sharding tables will be present by executing `show tables` SQL, even though they do not show up in your yaml configuration.
