### ISSUE TITLE
Too many keys are generated

### ISSUE THREAD

**Issue by SeniorBoy** [apache/shardingsphere#10357]
## Bug Report

 private void prepare() {
        executionContext = prepareEngine.prepare(sql, getParameters());
        findGeneratedKey().ifPresent(generatedKey -> generatedValues.add(generatedKey.getGeneratedValues().getLast()));
    }

found `generatedValues` values size > 1

 Too many keys are generated. There are only 1 target objects
Version 4.1.1

**Comment by tristaZero** [comment]
Hey, could you try the 5.0.0-alpha?

**Comment by SeniorBoy** [comment]
5.0.0-alpha There are other bugs in this release as well
 Does not support ClassBasedShardingAlgorithm ，The sharding algorithm was not found in the dependency package

**Comment by SeniorBoy** [comment]
5.0.0-alpha There are other bugs in this release as well
 Does not support ClassBasedShardingAlgorithm ，The sharding algorithm was not found in the dependency package

**Comment by SeniorBoy** [comment]
> Hey, could you try the 5.0.0-alpha?
5.0.0-alpha There are other bugs in this release as well
Does not support ClassBasedShardingAlgorithm ，The sharding algorithm was not found in the dependency package

**Comment by tristaZero** [comment]
You mean  this user-defined sharding algorithm interface `StandardShardingAlgorithm`?

**Comment by SeniorBoy** [comment]
> You mean this user-defined sharding algorithm interface `StandardShardingAlgorithm`?

![image](https://user-images.githubusercontent.com/20497813/118472396-5f044180-b73b-11eb-9b85-67f4c4509e7a.png)

ClassBasedShardingAlgorithm interface

**Comment by RaigorJiang** [comment]
Hi @SeniorBoy 
ClassBasedShardingAlgorithm is not a interface, it's just a way to configure a custom sharding algorithm.
For example:
1. Define a custom sharding algorithm implements StandardShardingAlgorithm, named 'MyShardingAlgorithm'
2. Configure 'shardingAlgorithms' with 'MyShardingAlgorithm', like: 
>   shardingAlgorithms:
     &emsp;<sharding-algorithm-name\>:
     &emsp;&emsp;type: CLASS_BASED
     &emsp;&emsp;props:
     &emsp;&emsp;&emsp;strategy: standard
     &emsp;&emsp;&emsp;algorithmClassName: org.xxx.example.MyShardingAlgorithm
   
I hope this information is useful to you.

**Comment by SeniorBoy** [comment]
> props

No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `CLASS_BASED`.

**Comment by RaigorJiang** [comment]
@SeniorBoy  Have you tried the latest version?   5.0.0-RC1-SNAPSHOT

**Comment by terrymanu** [comment]
Closed because of no response anymore.
