### ISSUE TITLE
在日志中打印 SQL带有换行，不便于日志检索,  打印  SQL日志 如何打成一行 ?

### ISSUE THREAD

**Issue by liuyuqiang** [apache/shardingsphere#10350]
sql 日志带有换行，不便于日志检索, sql 日志 如何打成一行 ? 

`
INFO  ShardingSphere-SQL-Actual SQL: test-db::: INSERT INTO test_ 1 ( id,
type,
uid,
r,
a,
b,
c,
e,
f,
c,
create,
update )  VALUES  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ::: [0, 0, 1, 0, 0, 0, 0, 0, 0, , 2021-05-15 13:23:12.0, 2021-05-15 13:23:12.0] 
`

**Comment by menghaoranss** [comment]
@liuyuqiang For English only.
