### ISSUE TITLE
Clean code for authority API

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10375]
Hi,

Greeting!
This issue is to optimize coding, please look at #10310 comments (TODO-1, TODO-2) and fix them.

Look forward to your PR and comments. :)

**Comment by zhujunxxxxx** [comment]
please assgin to me

**Comment by strongduanmu** [comment]
> please assgin to me

@zhujunxxxxx Assigned and welcome.

**Comment by tristaZero** [comment]
@zhujunxxxxx So this issue was fixed, wasn't it?

**Comment by zhujunxxxxx** [comment]
@tristaZero It has not been completely repaired. I plan to repair it this weekend. Recently, I have been busy, sorry.

**Comment by tristaZero** [comment]
@zhujunxxxxx  Got it, I reopened it for your fix. Thanks.

**Comment by tristaZero** [comment]
@zhujunxxxxx If you are about to raise a PR, please mention and link this issue.

**Comment by tristaZero** [comment]
Done.
