### ISSUE TITLE
Clean code for Process report feature 

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10374]
Hey,

Welcome! This is a very simple task for newcomers, please collaborate in this community from this one.

#### How
Look at my comment of #10351 and fix it.

**Comment by SivaTharun** [comment]
@tristaZero can i work on this issue.

**Comment by tristaZero** [comment]
Hi @SivaTharun Assigned to you. If you like, #10375 is suitable for you. :)

**Comment by tristaZero** [comment]
@SivaTharun Hi

Here is [the detail](https://github.com/apache/shardingsphere/pull/10351/files#r634033162).

**Comment by SivaTharun** [comment]
@tristaZero Please review the [PR](https://github.com/apache/shardingsphere/pull/10676) that i have raised for this issue and let me know of any changes, that needs to be addressed.
