### ISSUE TITLE
Does sharding not support DB2？

### ISSUE THREAD

**Issue by wsj1028** [apache/shardingsphere#10394]
I use DB2 to query the database and report an error，The test code is as follows 
`    @Resource(name = "shardingDataSource")
    private DataSource dataSource;

        Connection connection = dataSource.getConnection();
        String sql = "select * from t_order";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()){
            System.out.println("order_id: "+resultSet.getLong("order_id")
                    +", user_id: "+ resultSet.getLong("user_id"));
        }
        resultSet.close();
        preparedStatement.close();
        connection.close();
`
The error is as follows，
`com.ibm.db2.jcc.am.SqlException: [jcc][t4][10120][10898][4.28.11] 操作无效：已关闭 result set。 ERRORCODE=-4470, SQLSTATE=null
`

**Comment by strongduanmu** [comment]
@wsj1028 I am very sorry to tell you that ShardingSphere does not support DB2, and currently supports MySQL, Oracle, SQLServer, and PostgreSQL.

**Comment by SteNicholas** [comment]
@wsj1028 , ShardingSphere doesn't support DB2 database, but welcome to contribute the DB2 integration.
