### ISSUE TITLE
how to config SPI sharding class  in springboot2.3?

### ISSUE THREAD

**Issue by childewuque** [apache/shardingsphere#10397]
shardingsphere jdbc 5.0.0-alpha

public class DBShardingAlgorithm implements StandardShardingAlgorithm<Long> 

resources/META-INF/spring.factories
org.apache.shardingsphere.sharding.api.sharding.standard.StandardShardingAlgorithm=com.test.DBShardingAlgorithm

  `database-class-based:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.test.DBShardingAlgorithm

error:

org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `CLASS_BASED`.
	at org.apache.shardingsphere.infra.spi.typed.TypedSPIRegistry.getRegisteredService(TypedSPIRegistry.java:50)`

So how to config spi ? thanks!

**Comment by childewuque** [comment]
org.apache.shardingsphere.sharding.spi.ShardingAlgorithm=com.test.DBShardingAlgorithm

org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `CLASS_BASED`

**Comment by strongduanmu** [comment]
@childewuque After this [PR](https://github.com/apache/shardingsphere/pull/8508) is merged, we use the `CLASS_BASED` sharding algorithm without additional configuration of SPI, just specify the `algorithmClassName` parameter. Therefore, you can try the latest code from the master branch.

**Comment by childewuque** [comment]
> @childewuque After this [PR](https://github.com/apache/shardingsphere/pull/8508) is merged, we use the `CLASS_BASED` sharding algorithm without additional configuration of SPI, just specify the `algorithmClassName` parameter. Therefore, you can try the latest code from the master branch.

Thank u，I'll try the master branch.
And looking forward to the next version
