### ISSUE TITLE
ERROR 2006 (HY000): MySQL server has gone away

### ISSUE THREAD

**Issue by fanchao916** [apache/shardingsphere#10400]
sharding-proxy 5.x Alpha，After connecting with the mysql client (mysql -uxx -pxx -hxx -Pxxx)，When I execute the show databases command, some databases  can be displaye。After executing use sharding_db  and  Execute show tables；Report an error

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    31
Current database: sharding_db

ERROR 2013 (HY000): Lost connection to MySQL server during query

Because i know what tables are inside, the error is the same as above after executing select * from sharding_db.t_order directly.

Use python, mysql workbench to connect to this proxy, i can execute commands such as show tables, and data query is normal.
 
When the above error is reported, there is no record in the log

**Comment by strongduanmu** [comment]
@fanchao916 Can you translate it to English?

**Comment by fanchao916** [comment]
> @fanchao916 Can you translate it to English?
sharding-proxy 5.x Alpha，After connecting with the mysql client (mysql -uxx -pxx -hxx -Pxxx)，When I execute the show databases command, some databases can be displaye。After executing use sharding_db and Execute show tables；Report an error

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id: 31
Current database: sharding_db

ERROR 2013 (HY000): Lost connection to MySQL server during query

Because i know what tables are inside, the error is the same as above after executing select * from sharding_db.t_order directly.

Use python, mysql workbench to connect to this proxy, i can execute commands such as show tables, and data query is normal.

When the above error is reported, there is no record in the log
