### ISSUE TITLE
Add parse & rewrite test case for postgresql start/end transaction

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10403]
After PR #10402 is merged, we need to add some test cases for postgresql `start/end transaction` statements, including parse result tests and rewrite tests. 

If you are a newbie, you can use the `SQLParserParameterizedTest` and `ShardingSQLRewriterParameterizedTest` classes as the entrance to understand the logic of parsing tests and rewriting tests.

If you are interested, please leave a comment below. BTW, If you need any help, please ping me.

**Comment by beverleyokogwu** [comment]
I'm interested

**Comment by sizzlecar** [comment]
Let me try

**Comment by strongduanmu** [comment]
@sizzlecar Welcome and assigned.
