### ISSUE TITLE
Optimize java doc in ShardingRule class

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10416]
As described in PR #10414, some java doc description in the `ShardingRule` class is inaccurate and needs to be optimized. You need to optimize the java doc according to the comment in PR #10414, and check whether other java doc has the same problem.

For example, the following javadoc description is inaccurate.

```java
    /**
     * Judge logic table is belong to sharding tables.
     *
     * @param logicTableName logic table name
     * @return logic table is belong to sharding tables or not
     */
    public boolean isShardingTable(final String logicTableName) {
        return tableRules.containsKey(logicTableName.toLowerCase());
    }
```

We can modify it to `Judge whether logic table is sharding table or not.` Then modify the comment of return to `whether logic table is sharding table or not`. The public method in ShardingRule has some similar problems, please find and optimize together.

If you are interested, please leave a comment below. BTW, If you need any help, please ping me.

**Comment by KSMASTERS** [comment]
I am interested, please let me do it

**Comment by strongduanmu** [comment]
@KSMASTERS Welcome to join ShardingSphere community! Assigned.

**Comment by Swastyy** [comment]
@strongduanmu Please assign this issue to me. Thanks.

**Comment by strongduanmu** [comment]
Hi @Swastyy, I have modified this issue, you can try again.
