### ISSUE TITLE
SQL server lost the value of the last field through top pagination

### ISSUE THREAD

**Issue by linchers** [apache/shardingsphere#10420]
### Which version of ShardingSphere did you use?
4.1.1  
sqlserver

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

select top 10 id, name, content from table 。。。
id = 1; name = 123; content= abc
result: 1, abc, null
**ID is used as an alias** 
shardingsphere-sql-parser-dialect\shardingsphere-sql-parser-sqlserver\src\main\antlr4\imports\sqlserver\DMLStatement.g4
`projections
    : (unqualifiedShorthand | projection) (COMMA_ projection)*
    ;

projection
    : (top | columnName | expr) (AS? alias)? | qualifiedShorthand
    ;

top
    : TOP LP_? topNum RP_? PERCENT? (WITH TIES)? (ROW_NUMBER LP_ RP_ OVER LP_ orderByClause RP_)?
    ;`

### Actual behavior

 After modification 
`
projections
    : (unqualifiedShorthand | projection | (top (projection)?)) (COMMA_ projection)*
    ;

projection
    : (columnName | expr) (AS? alias)? | qualifiedShorthand
    ;

top
    : TOP LP_? topNum RP_? PERCENT? (WITH TIES)? (ROW_NUMBER LP_ RP_ OVER LP_ orderByClause RP_)?
    ;`

org.apache.shardingsphere.sql.parser.sqlserver.visitor.impl.SQLServerDMLVisitor
Move code from visitProjection to visitProjections
` 
if (null != ctx.top()) {
            RowNumberValueSegment rowNumber = (RowNumberValueSegment) visit(ctx.top());
            projections.add(new TopProjectionSegment(ctx.top().getStart().getStartIndex(), ctx.top().getStop().getStopIndex(), rowNumber, null));
`
it well be ok !

**Comment by strongduanmu** [comment]
@linchers Hi, can you try the `5.0.0-alpha` version? I think this problem has been fixed.

**Comment by tuichenchuxin** [comment]
@linchers I have tested on master branch, it is supported now.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it. Thank you.
