### ISSUE TITLE
RDL process suspend 

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#10437]
proxy compiled by up to date master code.

following is the process to reproduce :

1.establish 2 MySQL by docker, init with schema `demo_ds` creation
2.start up proxy without any config yaml but server.yaml
3.connect to proxy by mysql client
4.create resource by RDL as following : 
```
ADD RESOURCE resource0 (
HOST=127.0.0.1,
PORT=13306,
DB=demo_ds,
USER=root,
PASSWORD=root
);
```

when try to drop or show this resource, will get an promotion `Empty set`
since the resource has been created, should be drop or show .

**Comment by menghaoranss** [comment]
Fixed by #10555
