### ISSUE TITLE
Binding table configuration not effective

### ISSUE THREAD

**Issue by yidazhi** [apache/shardingsphere#10439]
I made the following configuration in sharding proxy, but the binding table did not take effect

bindingTables:
    - wt_tran,wt_tran_detail      ##Effective
    - user_account,user_subaccount    ##Effective
    - wt_tran_detail,user_account   ##It didn't work,These two tables will also produce Cartesian product for join query.

version  :  apache-shardingsphere-incubating-4.0.0-sharding-proxy

How do I configure it to take effect？

**Comment by tristaZero** [comment]
Looks strange if the first two work well.
From your configuration, I suppose wt_tran_detail, user_account, user_subaccount and wt_tran share same sharding column and algorithm, don't they? If so, could you configure that in the way below?
```yaml
bindingTables:
- wt_tran, wt_tran_detail, user_account, user_subaccount 
```

**Comment by yidazhi** [comment]
> Looks strange if the first two work well.
> From your configuration, I suppose wt_tran_detail, user_account, user_subaccount and wt_tran share same sharding column and algorithm, don't they? If so, could you configure that in the way below?
> 
> ```yaml
> bindingTables:
> - wt_tran, wt_tran_detail, user_account, user_subaccount 
> ```

Yes, they share the same slicing and algorithm. Let me test it according to your suggestion

**Comment by yidazhi** [comment]
> Looks strange if the first two work well.
> From your configuration, I suppose wt_tran_detail, user_account, user_subaccount and wt_tran share same sharding column and algorithm, don't they? If so, could you configure that in the way below?
> 
> ```yaml
> bindingTables:
> - wt_tran, wt_tran_detail, user_account, user_subaccount 
> ```

According to your suggestion, it is effective and will not produce Cartesian product. Thank you
