### ISSUE TITLE
关闭进程 执行shutdownhook后，程序开始执行删除数据操作，底层报异常被拒绝。但是后续还有一次插入操作是ok可以执行得.  目前猜测像是操作数据得线程提前关闭了，但插入ok得，不清楚删除和插入是否存在区别.

### ISSUE THREAD

**Issue by xuyjava** [apache/shardingsphere#10436]
INFO 67472 --- [nfoReplicator-0] c.n.d.DiscoveryClient                    : DiscoveryClient_RANK-SERVICE/rank-service:ce34cecf0e7eb423927a9bd09702218b - registration status: 204
%xwEx2021-05-24 11:20:16.704 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : java.util.concurrent.RejectedExecutionException: Task com.google.common.util.concurrent.TrustedListenableFutureTask@6ebf0dfa[status=PENDING, info=[task=[running=[NOT STARTED YET], org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine$$Lambda$253/2054518048@24d95395]]] rejected from java.util.concurrent.ThreadPoolExecutor@222cedf3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
%xwEx2021-05-24 11:20:16.704 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
%xwEx2021-05-24 11:20:16.704 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:525)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.asyncExecute(ExecutorEngine.java:110)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.asyncExecute(ExecutorEngine.java:103)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.parallelExecute(ExecutorEngine.java:92)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeUpdate(PreparedStatementExecutor.java:123)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:133)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.data.jdbcactuator.ExecuteProcessor.executeUpdate(ExecuteProcessor.java:46)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.data.dao.ShardDao.deleteAllTable(ShardDao.java:225)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.data.dao.ShardDao$$FastClassBySpringCGLIB$$8dd5cb14.invoke(<generated>)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.data.dao.ShardDao$$EnhancerBySpringCGLIB$$e8a9b350.deleteAllTable(<generated>)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.data.database.helper.MysqlCacheHelper.deleteAllTable(MysqlCacheHelper.java:163)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.rank.rankImpl.RankServiceImpl.rankDump(RankServiceImpl.java:160)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.rank.rankImpl.RankServiceImpl.destroy(RankServiceImpl.java:148)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.application.NirvanaShutdownHandler.shutdown(NirvanaShutdownHandler.java:62)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.application.NirvanaShutdownHandler.onApplicationEvent(NirvanaShutdownHandler.java:31)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at com.wangyuan.game.nirvana.application.NirvanaShutdownHandler.onApplicationEvent(NirvanaShutdownHandler.java:22)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:992)
%xwEx2021-05-24 11:20:16.705 ERROR 67472 --- [      Thread-12] c.w.g.n.l.a.Log4jPrintStream             : 	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)

**Comment by xuyjava** [comment]
shardingsphere version: 4.1.1

**Comment by strongduanmu** [comment]
@xuyjava Can you translate it to English? And I can’t understand what you mean, can you submit it according to the issue template?
