### ISSUE TITLE
There is a problem with the distributed transaction springcloud shardingsphere4.1.1+seata1.3.0  

### ISSUE THREAD

**Issue by zhzwdzai** [apache/shardingsphere#10450]
If shardingsphere is used in downstream services, the global distributed transaction of Seata cannot be used
![image](https://user-images.githubusercontent.com/33139799/119438344-903fcb80-bd52-11eb-8ba3-28ca2c0d2d49.png)

![image](https://user-images.githubusercontent.com/33139799/119435994-e6f6d680-bd4d-11eb-93a7-01d62608a3df.png)
![image](https://user-images.githubusercontent.com/33139799/119436426-b82d3000-bd4e-11eb-9ad0-065c1d108b01.png)

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.
