### ISSUE TITLE
Refactor import classes for DistSQLVisitor

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#10457]
Just search code  like `final DistSQLStatementParser.` in `DistSQLVisitor ` and import the complete classes instead of import `DistSQLStatementParser `

**Comment by KSMASTERS** [comment]
I want  to do it!

**Comment by menghaoranss** [comment]
> I want to do it!

assigned, welcome.

**Comment by menghaoranss** [comment]
@KSMASTERS hi, how is it going now.

**Comment by wmouren** [comment]
Can I try?
