### ISSUE TITLE
Support sharding tables and broadcast tables to execute ALTER TABLE ... RENAME TO ... statement

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10476]
Currently, PR #10462 only implements the `ALTER TABLE ... RENAME TO ... statement` for the single table. The storage problem of the table rule has not been solved after sharding tables and the broadcast tables are renamed. Therefore, sharding tables and the broadcast tables are not supported `ALTER TABLE ... RENAME TO ... statement` now.

We need to discuss with @tristaZero @menghaoranss to determine the final implementation, and then support sharding tables and broadcast tables.

**Comment by kssumin** [comment]
Hi @strongduanmu 

  I would like to work on this issue. I've already implemented a solution for supporting
  `ALTER TABLE ... RENAME TO` and `RENAME TABLE` statements for sharding and broadcast
  tables.

  ### Implementation Summary:
  - Removed restrictions in `ShardingAlterTableSupportedChecker` and
  `ShardingRenameTableSupportedChecker`
  - Added validation to prevent table name conflicts
  - Updated metadata refreshers to handle rename operations
  - Added comprehensive unit tests (8 tests, all passing)

  The physical table renaming works for both single and sharding/broadcast tables. For
  sharding/broadcast tables, the rules can be updated manually via DistSQL (consistent with
   existing DROP/CREATE TABLE behavior).

  I'm preparing to submit a PR. Any feedback or guidance would be appreciated!

  Thanks!

**Comment by strongduanmu** [comment]
@kssumin This sounds great. I have a question: Does the `ALTER TABLE ... RENAME TO ...` statement only support Cluster mode and not Stanadlone? Because, we can't modify the YAML configuration in Stanadlone mode.

**Comment by kssumin** [comment]
Hi @strongduanmu,

Thanks for the question!  
From my understanding, this feature should work in both Standalone and Cluster modes,  
not only in Cluster mode — but please correct me if I’m misunderstanding.

### My understanding

- In Standalone mode, YAML is only used for initial bootstrap.
- Runtime changes via DistSQL are persisted to the configured repository (JDBC or in-memory), not to YAML.
- When using the default in-memory repository, changes are volatile and will be lost after restart.
- When using a JDBC repository, the changes are persisted and reloaded on restart.
- This follows the same behavior as other DDL operations (like DROP/CREATE TABLE),  
  where the physical operation succeeds and rules can be updated manually via DistSQL.

### Implementation approach

Based on that, I kept the behavior consistent:
- Physical tables are renamed automatically.
- Sharding/broadcast rules remain unchanged.
- Users can update those rules manually via DistSQL.
- Changes are persisted in the repository.

Could you please confirm if my understanding of how Standalone mode handles persistence is correct?  
If there are any details or edge cases I should handle differently, I’d really appreciate your guidance.

Thanks again!
