### ISSUE TITLE
There is a problem in  ShardingSphereConnection . It should TransactionHolder.setInTransaction() when setAutoCommit(false)

### ISSUE THREAD

**Issue by lyennon** [apache/shardingsphere#10507]
https://github.com/apache/shardingsphere/blob/41f1335023c8ca10ba289b8d02ae29967045429d/shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java#L237

 It should TransactionHolder.setInTransaction() when setAutoCommit(false); 
if(!autoCommit){
TransactionHolder.setInTransaction()
}

**Comment by yx9o** [comment]
@RaigorJiang Hi, I want to try to deal with this issue. I verified that this problem exists in the case of `TransactionType.LOCAL`.
![8915b10bebe0d60e930833a3b517430](https://user-images.githubusercontent.com/12792261/135125717-ce7f0203-7507-4f66-bf91-19a62f48dc15.png)
![daa53556fad52e91d72a3b4ee81f242](https://user-images.githubusercontent.com/12792261/135125731-d6acc35f-f93b-4311-802c-85c14303f332.png)

**Comment by RaigorJiang** [comment]
Thanks @yx9o .
