### ISSUE TITLE
Add more RQL parser tests in DistSQLStatementParserEngineTest

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#10505]
1. SHOW SHARDING TABLE RULES FROM schemaName
2. SHOW SHARDING TABLE RULE t_order
3. SHOW SHARDING TABLE RULE t_order FROM schemaName

**Comment by JooKS-me** [comment]
Hi, can I try it?

**Comment by menghaoranss** [comment]
> Hi, can I try it?

welcome.
