### ISSUE TITLE
Error when table name is organization

### ISSUE THREAD

**Issue by yuanjava1** [apache/shardingsphere#10500]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core-spring-boot-starter   5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
My environment is spring boot + spring data JPA. When the project starts, it will automatically create a table and prompt me：line 1:13 no vivable alternate at input'organization'

![1](https://user-images.githubusercontent.com/31638995/119781232-5b23ac80-befd-11eb-9e91-f4eaa7dcd341.png)
![2](https://user-images.githubusercontent.com/31638995/119781233-5b23ac80-befd-11eb-897b-6656e33b6f91.png)
![3](https://user-images.githubusercontent.com/31638995/119781234-5b23ac80-befd-11eb-8acb-9cd821c17e17.png)

**Comment by strongduanmu** [comment]
@yuanjava1 Thank you very much for your feedback, can you provide the SQL text?

**Comment by yuanjava1** [comment]
> @ yuanjava1非常感谢您的反馈，可以提供SQL文本吗？

Hello, the second picture is marked in red，My English is not very good, please forgive me
