### ISSUE TITLE
After Dependent ShardingSphere , MyBatis-Plus ResultMap Mapping Null

### ISSUE THREAD

**Issue by cz1422189551** [apache/shardingsphere#10515]
env:
dependency group: 'com.baomidou', name: 'mybatis-plus-boot-starter', version: "3.4.0"
dependency group: 'org.apache.shardingsphere', name: 'shardingsphere-jdbc-core-spring-boot-starter', version: "5.0.0-alpha"

issue:
select *  from pue;     resultMapping  ok 

select * , id as 'pid' from  pue;    resultMapping  only id  has value  

select xxx.* , yyy.*  from xxxx;   resultMapping null

**Comment by Scottle-Hu** [comment]
I met this problem, too. 
And I found that if do not use *, all work fine.

for example:
```select xxx.a, xxx.b , yyy.a, yyy.b from xxxx;```
instead of
```select xxx.* , yyy.* from t;```

**Comment by strongduanmu** [comment]
Hi @cz1422189551, can you provide more information? I need to reproduce this problem.

**Comment by terrymanu** [comment]
Sorry to reply late.
mybatis-plus is the ORM framework of JDBC.
Actually, , ShardingSphere community have no time to read source codes of other ORM framework, we are focusing on JDBC(or proxy) only.
So, please do some investigate, and then we can locate about SQL and JDBC interface.
