### ISSUE TITLE
[GSoC 2021] Proofread the Oracle DDL/TCL SQL Definitions

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#10513]
This issue is related to the Google Summer of Code (GSoC) 2021 project - [Proofread the Oracle DDL/TCL SQL Definitions](https://summerofcode.withgoogle.com/projects/#5167124928004096). 
Meanwhile, it is a sub-issue of #6480.

### Background

ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for MySQL, PostgreSQL, SQLServer, and Oracle, which means we have to understand different database dialects SQLs. 

This project is focused on proofreading all the **Oracle TCL** (Transaction Control Language) and **DDL** (Data Definition Language) SQL definitions except for ALTER, DROP, CREATE and TRUNCATE.

#### TCL
- [x] SET TRANSACTION
- [x] SET CONSTRAINT(S)

#### DDL
- [x] ANALYZE
- [x] ASSOCIATE STATISTICS
- [x] DISASSOCIATE STATISTICS
- [x] AUDIT (Unified Auditing)
- [x] NOAUDIT (Unified Auditing)
- [x] COMMENT
- [x] FLASHBACK DATABASE
- [x] FLASHBACK TABLE
- [x] PURGE
- [x] RENAME

Reference: Oracle [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SQL-Statements-ADMINISTER-KEY-MANAGEMENT-to-ALTER-JAVA.html#GUID-04D8EBB3-583D-4969-8344-E221000E9CD9) of SQL definitions

**Comment by Liangda-w** [comment]
Remaining improvements: see discussion in #11126 - parse the following segments and add corresponding tests.

- [ ] function
- [ ] package

**Comment by Liangda-w** [comment]
GSoC project completed:) Huge thanks to my mentors @wgy8283335 and @tristaZero

**Comment by wgy8283335** [comment]
> GSoC project completed:) Huge thanks to my mentors @wgy8283335 and @tristaZero

Congratulations! It's my pleasure. @Liangda-w

**Comment by tristaZero** [comment]
Hey, it's an enjoyable time to be your mentor during GSoC here. @Liangda-w Good luck!
