### ISSUE TITLE
Add test cases for RuleConfigurationChecker

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10536]
- [x] Add test case for RuleConfigurationCheckerFactory with RuleConfigurationChecker fixture
- [x] Add test case for ShardingRuleConfigurationChecker
- [x] Add test case for AlgorithmProvidedShardingRuleConfigurationChecker
- [x] Add test case for ReadwriteSplittingRuleConfigurationChecker
- [x] Add test case for AlgorithmProvidedReadwriteSplittingRuleConfigurationChecker
- [x] Add test case for EncryptRuleConfigurationChecker
- [x] Add test case for AlgorithmProvidedEncryptRuleConfigurationChecker
- [x] Add test case for DatabaseDiscoveryRuleConfigurationChecker
- [x] Add test case for ShadowRuleConfigurationChecker

**Comment by zhujunxxxxx** [comment]
@terrymanu Can I try?

**Comment by menghaoranss** [comment]
> @terrymanu Can I try?

welcome.

**Comment by zhujunxxxxx** [comment]
@terrymanu the fellow RuleConfigurationChecker has been merged.
- Add test case for ShardingRuleConfigurationChecker
- Add test case for AlgorithmProvidedShardingRuleConfigurationChecker
