### ISSUE TITLE
When using mybatisplus plus goupBy for paging query, the count parameter is not encrypted

### ISSUE THREAD

**Issue by xiongwu1** [apache/shardingsphere#10538]
When using mybatisplus plus goupBy for paging query, the count parameter is not encrypted, resulting in no data query
Before report a bug, make sure you have.

As shown below:
![image](https://user-images.githubusercontent.com/15642586/120001385-4ed74680-c006-11eb-9a25-a32534c35891.png)

**Comment by xiongwu1** [comment]
Encrypted field is not groupBy field

**Comment by terrymanu** [comment]
Sorry to reply late.
mybatis-plus is the ORM framework of JDBC.
Actually, , ShardingSphere community have no time to read source codes of other ORM framework, we are focusing on JDBC(or proxy) only.
So, please do some investigate, and then we can locate about SQL and JDBC interface.
