### ISSUE TITLE
Use RuleConfigurationFixture instead of ShardingRuleConfiguration for test case in governance module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10537]
For decouple features and governance module, it is better to use  RuleConfigurationFixture instead of ShardingRuleConfiguration for test cases. They are:

- [ ] RuleChangedListenerTest.assertCreateEventWithRule()
- [ ] SchemaRuleRegistryServiceTest.assertLoadWithExistedNode()
- [ ] RegistryCenterTest.createRuleConfigurations()

**Comment by totalo** [comment]
hi can i try to do this ?

**Comment by menghaoranss** [comment]
> hi can i try to do this ?

assigned
