### ISSUE TITLE
Support `CREATE TABLESPACE` of PostgreSQL

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10549]
### Desc
Currently, some of the communities are test PostgreSQL-Sharding-Proxy by benchmark SQL. However, they reported that unsupported SQL, i.e., `CREATE TABLESPACE` has become a blocker for their work. 

### Task
To figure out whether we can support this SQL in PostgreSQL-Sharding-Proxy effectively.

> create tablespace example3 relative location 'tablesapce2'; create table t1 TABLESPACE tablespace_name

Maybe we can consider routing this SQL to all the instances.

### Ref
- https://www.postgresql.org/docs/10/sql-createtablespace.html
- https://www.postgresql.org/docs/10/sql-createtable.html

**Comment by zhujunxxxxx** [comment]
I'd like to try it;

**Comment by strongduanmu** [comment]
@zhujunxxxxx Because this issue is urgent, I will fix the problem first. Issue #10368 will include other unsupported statements. Welcome to participate.

**Comment by zhujunxxxxx** [comment]
@strongduanmu OK.
