### ISSUE TITLE
shardingsphere-5.0.0-alpha NullPointException

### ISSUE THREAD

**Issue by heysJava** [apache/shardingsphere#10569]
Use the shardingsphere-5.0.0-alpha version to perform monthly sub-tables, such as detail_202101, detail_202102..., but I don’t want to create the detail table, and the result is a null pointer exception. How do I configure it?

**Comment by RaigorJiang** [comment]
@heysJava 
Sorry for keeping you waiting, has your problem been solved?

**Comment by terrymanu** [comment]
No response anymore, I just close the issue.
