### ISSUE TITLE
subquery in select not support

### ISSUE THREAD

**Issue by dbzzzzz** [apache/shardingsphere#10565]
### Which version of ShardingSphere did you use?
ShardingSphere 5
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
select (select max(USER_ID) from t_order) a,ORDER_ID,STATUS from t_order;
should return 3 columns.
### Actual behavior
return only 2 columns.
mysql> select (select max(USER_ID) from t_order) a,ORDER_ID,STATUS from t_order;
+------+----------+
| a    | ORDER_ID |
+------+----------+
|   11 |     1000 |
|   11 |     1001 |
|   11 |     1100 |
|   11 |     1101 |
+------+----------+
4 rows in set (0.07 sec)

**Comment by strongduanmu** [comment]
After PR #10658 is merged, the problem of missing columns in the subquery will be resolved, but there are still problems, and the subquery aggregated results are incorrect.

![image](https://user-images.githubusercontent.com/10829171/120791590-f99bb780-c566-11eb-9be7-4fc213a091ea.png)
