### ISSUE TITLE
support LOAD DATA

### ISSUE THREAD

**Issue by dbzzzzz** [apache/shardingsphere#10568]
### Is your feature request related to a problem?
No
### Describe the feature you would like.
In mysql, we usually use LOAD DATA command to load data into mysql, so I hope shardingsphere could support LOAD DATA command. such as:
LOAD DATA LOCAL INFILE '/tmp/t_order.txt' INTO TABLE t_order;

**Comment by terrymanu** [comment]
The data is in database, but ShardingSphere. So there is no plan to support `LOAD DATA`
