### ISSUE TITLE
union not support

### ISSUE THREAD

**Issue by dbzzzzz** [apache/shardingsphere#10566]
### Which version of ShardingSphere did you use?
ShardingSphere 5
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
select * from t_order 
union all 
select * from t_order;
should return correct result.
### Actual behavior
mysql> select * from t_order 
    -> union all 
    -> select * from t_order;
ERROR 1999 (C1999): Unknown exception: [union select is not supported yet.]
mysql> select * from t_order  union  select * from t_order;
ERROR 1999 (C1999): Unknown exception: [union select is not supported yet.]

**Comment by tuichenchuxin** [comment]
@dbzzzzz union/ union all had supported in master branch now, if the tables is not sharding_table or broadcast tables.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it.
