### ISSUE TITLE
Add more assertions  in MetaDataChangedListenerTest

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#10575]

**Comment by shashwatj07** [comment]
May I take this? Please let me know what kind of assertions are needed.

**Comment by huangdx0726** [comment]
Can i try it? But there is no such file,  Is it renamed?  @menghaoranss

**Comment by tristaZero** [comment]
Sure welcome, does anyone want to have a try? @huangdx0726 @shashwatj07

**Comment by menghaoranss** [comment]
The class has been renamed to `MetaDataChangedWatcherTest`, I will move this issue to `5.0.0-RC-1`, please reply this issue  if you want to try again. @shashwatj07 @huangdx0726

**Comment by huangdx0726** [comment]
Ok, I will try.

**Comment by tristaZero** [comment]
Hi @huangdx0726 assigned this one to U.
