### ISSUE TITLE
Use Parameterized + XML instead of static test with DistSQLStatementParserEngineTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10581]
The DistSQLStatementParserEngineTest is split to:

- DistSQLStatementParserEngineTest
- EncryptRuleStatementParserEngineTest
- DatabaseDiscoveryRuleStatementParserEngineTest
- ReadwriteSplittingRuleStatementParserEngineTest
- ShardingRuleStatementParserEngineTest

FYI: SQLParserParameterizedTest

**Comment by totalo** [comment]
hi can i try this?

**Comment by strongduanmu** [comment]
> hi can i try this?

@totalo Welcome, and assigned.

**Comment by zhujunxxxxx** [comment]
@totalo Do you have time? I see you have several issues. If you have no time, I will revise this.

**Comment by totalo** [comment]
> revise this.

thx ,I am working hard
