### ISSUE TITLE
executor.size is not working

### ISSUE THREAD

**Issue by zhkj0001** [apache/shardingsphere#10589]
dear teams:

I met a issue when I try to optimize my query through shardingsphere. Because we hava 30 sharding table. so we like to add more thread to perfume query. but It seems the property spring.shardingsphere.props.executor.size=4. but I noticed there were 2 threads is working because my cpus has 2 cores. 

Our  shardingsphere version is 4.0.0.RC1. There is no any error. So figer out how to configure the threads to work propertly.

Appreciate a lot.

**Comment by terrymanu** [comment]
The `executor.size` properties is removed from the newest version(5.0.0-RC1), it is better to use cpu * 2 -1 to instead customized.
