### ISSUE TITLE
Replace keyword with another in integrate tests

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10604]
Hi there,

This is a subsequent simple task of #10603. Welcom anyone who wants to have a try. :)

Just replace the keyword `Calcite` with `Federate` for all the SQLs, the names of variables and configuration file in `shardingsphere-jdbc/shardingsphere-jdbc-core/src/test`.

Please refer to [How to raise a PR](https://shardingsphere.apache.org/community/cn/contribute/contributor/)

**Comment by abhikarkamkar** [comment]
hi @tristaZero  can I take this ?

**Comment by tristaZero** [comment]
> hi @tristaZero can I take this ?

Sure, welcome.

**Comment by abhikarkamkar** [comment]
hi @tristaZero I have done changes related to replacement of keyword calcite to federate under ``` shardingsphere-jdbc/shardingsphere-jdbc-core/src/test ``` . Please let me know in case of any issues.
