### ISSUE TITLE
group by + having not support

### ISSUE THREAD

**Issue by dbzzzzz** [apache/shardingsphere#10618]
### Is your feature request related to a problem?

In shardingsphere 5 proxy，group by + having does not support, the error is as below:
mysql> select USER_ID,sum(ORDER_ID) from t_order group by USER_ID having sum(ORDER_ID)>1100;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'having sum(ORDER_ID)>1100' at line 1

**Comment by strongduanmu** [comment]
PR #10620 fixes the grammatical problem of the wrong order after adding the `order by` clause when the `select ... group by ... having ... statement` is rewritten, but `having` clause is not handled correctly.

![image](https://user-images.githubusercontent.com/10829171/120632545-aad51b80-c49b-11eb-8f92-378dfa3d8111.png)

We need to remove the `having` clause in the rewriting logic, and filter the having conditions after group merge.
