### ISSUE TITLE
multi row sql problem

### ISSUE THREAD

**Issue by Pinary** [apache/shardingsphere#10616]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.x  4.x  5.x

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Running 2 insert sql as one statement. e.g:
insert into system_log_operate (id,create_date) values (?, ?);
insert into test(id,create_date) values (?, ?);

we expected actual sql :
insert into system_log_operate_0 (id,create_date) values (?, ?);
insert into test(id,create_date) values (?, ?);

### Actual behavior
get error java.sql.SQLException: No value specified for parameter 3

**Comment by strongduanmu** [comment]
@Pinary ShardingSphere does not support multiple SQL, because it will bring more complexity and lower performance. You can split multiple SQL into multiple single SQL for execution.
