### ISSUE TITLE
addShutdownHook in ShardingExecutorService

### ISSUE THREAD

**Issue by whojes** [apache/shardingsphere#10641]
## Question

Hi there, i have a question. 

I'm currently using shardingsphere for a project with spring boot framework.
When i create sharding datasource, it registers a shutdown hook while creating its stuffs; ([code link](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/kernel/thread/ExecutorServiceManager.java#L47))

i'm using my sharding datasource in middle of business code, and i'm hoping that `ShardingExecutorService` would be destroyed after related beans stop working and has been released, according to spring's shutdown process. But the library registers shutdown hook which destroys a thread pool regardless of spring context.

i think `ExecutorServiceManager` should not register the shutdown hook, implement Closeable, and add destroy process in `close()` method. Is there a  reason for register the shutdown hook to Runtime?

**Comment by terrymanu** [comment]
Is anybody interest this issue?

**Comment by terrymanu** [comment]
Thanks for @cheese8 to fix this issue.
