### ISSUE TITLE
Create user should not need to execute use database first

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#10673]
```
mysql> create user test identified by '123456';
ERROR 1046 (3D000): No database selected
mysql>
```

**Comment by RaigorJiang** [comment]
I'm working on this issue, please assign it to me, thanks.

**Comment by ccMoriarty** [comment]
![image](https://user-images.githubusercontent.com/35559210/126616133-28d8201f-bdf4-4561-927f-3703b89aa791.png)
![image](https://user-images.githubusercontent.com/35559210/126616237-0ff0b5c3-8079-4318-8826-327228c84559.png)


I have a similar problem

when i use  'select * from db.tb',  it tell me No database selected; but it ok in MySQL

why must selecte  database  first

**Comment by RaigorJiang** [comment]
Hi @ccMoriarty 
Thanks for your feedback, but this is not a similar problem. 
- for Proxy, different schemas can have different feature configurations, which will affect the query results, so the schema must be used first.
- `create user` is not limited by the sharding function, so this needs to be solved.
