### ISSUE TITLE
Create `DropTableStatementFederateRefresher`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10697]
Hi community,

This issue needs more effort than good-first-issue. Hope you can enjoy it. :)

### Target 
- Create a class named `DropTableStatementFederateRefresher` which is to renew `FederateSchemaMetadata` when users execute `drop table xxx` SQL. (It is simple to figure out that once the table structure changes, the metadata needs to be refreshed accordingly)
- Add a unit test for your change

### How
- Create a class named `DropTableStatementFederateRefresher` implementing `FederateRefresher<DropTableStatement>`
Here are some tips,
1. Please refer to `CreateTableStatementFederateRefresher` and `DropTableStatementSchemaRefresher`
2. Add a `remove` function for `FederateSchemaMetadata` like `renew()` of it.
- Add this one to `MetadataRefresherFactory`
- Add a unit test similar to `DropTableStatementSchemaRefresherTest` and #10695

**Comment by xiaoshen11** [comment]
Please assign to me.

**Comment by kimmking** [comment]
@xiaoshen11 assigned

**Comment by yinyichao** [comment]
Please assign to me.

**Comment by xiaoshen11** [comment]
@tristaZero my pr checks fail，details as follows，I don't konw how to solve it，please help me 

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:33 min
[INFO] Finished at: 2021-06-14T02:57:45Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal on project shardingsphere-infra-optimize: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-infra-optimize:jar:5.0.0-RC1-SNAPSHOT: Failed to collect dependencies at org.apache.calcite:calcite-core:jar:1.26.0: Failed to read artifact descriptor for org.apache.calcite:calcite-core:jar:1.26.0: Could not transfer artifact org.apache.calcite:calcite-core:pom:1.26.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-core/1.26.0/calcite-core-1.26.0.pom: Connection reset -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :shardingsphere-infra-optimize
Error: Process completed with exit code 1.

**Comment by tristaZero** [comment]
Hi @xiaoshen11 
I just restart the CI task, let us wait for the result. Plus, some comments are expected to be dealt with.
