### ISSUE TITLE
default-database-strategy:hint  hint can't use

### ISSUE THREAD

**Issue by stelin** [apache/shardingsphere#10699]
ShardingSphere-JDBC 4.1.1 default-database-strategy:hint can't use

spring:
shardingsphere:
sharding:
default-data-source-name: demo-1
default-database-strategy:
hint:
algorithm-class-name: com.ai94.mysql.annotation.AnnotationHintShardingAlgorithm
datasource:
names: demo-1,demo-2
# datasource one
demo-1:
type: com.zaxxer.hikari.HikariDataSource
driverClassName: com.mysql.jdbc.Driver
jdbcUrl: jdbc:mysql://localhost:3306/db_A?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
username: root
password: root
# datasource two
demo-2:
type: com.zaxxer.hikari.HikariDataSource
driverClassName: com.mysql.jdbc.Driver
jdbcUrl: jdbc:mysql://localhost:3306/db_B?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
username: root
password: root

**Comment by stelin** [comment]
like https://github.com/apache/shardingsphere/issues/5970

**Comment by strongduanmu** [comment]
@stelin Can you submit this issue in English?

**Comment by stelin** [comment]
@strongduanmu 
Only configure default-database-strategy，This method does not seem to be supported!

**Comment by strongduanmu** [comment]
Hi @stelin, I used the version `4.1.1` of `Sharding-JDBC` to test the Hint feature, and there is no problems. The following is my test demo:

```java
public class HintTest {
    
    public static void main(String[] args) throws SQLException {
        DataSource dataSource = new HintTest().getShardingDataSource();
        Connection connection = dataSource.getConnection();
        PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM t_order");
        HintManager.getInstance().setDatabaseShardingValue(1);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()) {
            System.out.println(resultSet.getString("ORDER_ID") + " " + resultSet.getString("USER_ID"));
        }
        HintManager.getInstance().close();
        resultSet.close();
        preparedStatement.close();
        connection.close();
    }
    
    private DataSource getShardingDataSource() throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTableRuleConfigs().add(getOrderTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(getOrderItemTableRuleConfiguration());
        shardingRuleConfig.getBindingTableGroups().add("t_order, t_order_item");
        shardingRuleConfig.getBroadcastTables().add("t_config");
        shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new HintShardingStrategyConfiguration(new AnnotationHintShardingAlgorithm()));
        shardingRuleConfig.setDefaultTableShardingStrategyConfig(new InlineShardingStrategyConfiguration("order_id", "ds_${order_id % 2}"));
        Properties props = new Properties();
        props.setProperty("sql.show", "true");
        return ShardingDataSourceFactory.createDataSource(createDataSourceMap(), shardingRuleConfig, props);
    }
    
    private static KeyGeneratorConfiguration getKeyGeneratorConfiguration() {
        KeyGeneratorConfiguration result = new KeyGeneratorConfiguration("SNOWFLAKE", "order_id");
        return result;
    }
    
    TableRuleConfiguration getOrderTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration("t_order", "ds_${0..1}.t_order_${0..1}");
        result.setKeyGeneratorConfig(getKeyGeneratorConfiguration());
        return result;
    }
    
    TableRuleConfiguration getOrderItemTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration("t_order_item", "ds_${0..1}.t_order_item_${0..1}");
        return result;
    }
    
    Map<String, DataSource> createDataSourceMap() {
        Map<String, DataSource> result = new HashMap<>();
        result.put("ds_0", DataSourceUtil.createDataSource("demo_ds_0"));
        result.put("ds_1", DataSourceUtil.createDataSource("demo_ds_1"));
        return result;
    }
}
```

**Comment by strongduanmu** [comment]
When i set `HintManager.getInstance().setDatabaseShardingValue(1);`, the route result is:
```
[main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM t_order
[main] INFO ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@62b969c4, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@dcc6211), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@dcc6211, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=7, distinctRow=false, projections=[ShorthandProjection(owner=Optional.empty, actualColumns=[ColumnProjection(owner=null, name=order_id, alias=Optional.empty), ColumnProjection(owner=null, name=user_id, alias=Optional.empty), ColumnProjection(owner=null, name=status, alias=Optional.empty), ColumnProjection(owner=null, name=content, alias=Optional.empty), ColumnProjection(owner=null, name=content_new, alias=Optional.empty), ColumnProjection(owner=null, name=content_new_2, alias=Optional.empty), ColumnProjection(owner=null, name=order_name, alias=Optional.empty), ColumnProjection(owner=null, name=item_cd, alias=Optional.empty)])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@47ec7422, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@48535004, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@610df783, containsSubquery=false)
[main] INFO ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM t_order_0
[main] INFO ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM t_order_1
```

When i set `HintManager.getInstance().setDatabaseShardingValue(0);`, the route result is:
```
[main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM t_order
[main] INFO ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@4441d567, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@3e1624c7), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@3e1624c7, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=7, distinctRow=false, projections=[ShorthandProjection(owner=Optional.empty, actualColumns=[ColumnProjection(owner=null, name=order_id, alias=Optional.empty), ColumnProjection(owner=null, name=user_id, alias=Optional.empty), ColumnProjection(owner=null, name=status, alias=Optional.empty), ColumnProjection(owner=null, name=content, alias=Optional.empty), ColumnProjection(owner=null, name=content_new, alias=Optional.empty), ColumnProjection(owner=null, name=content_new_2, alias=Optional.empty), ColumnProjection(owner=null, name=order_name, alias=Optional.empty), ColumnProjection(owner=null, name=item_cd, alias=Optional.empty)])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@62b969c4, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@dcc6211, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@47ec7422, containsSubquery=false)
[main] INFO ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM t_order_0
[main] INFO ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM t_order_1
```

When i don't set `HintManager.getInstance().setDatabaseShardingValue(0);`, the route result is:
```
[main] INFO ShardingSphere-SQL - Logic SQL: SELECT * FROM t_order
[main] INFO ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@6e0cff20, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@359b650b), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@359b650b, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=7, distinctRow=false, projections=[ShorthandProjection(owner=Optional.empty, actualColumns=[ColumnProjection(owner=null, name=order_id, alias=Optional.empty), ColumnProjection(owner=null, name=user_id, alias=Optional.empty), ColumnProjection(owner=null, name=status, alias=Optional.empty), ColumnProjection(owner=null, name=content, alias=Optional.empty), ColumnProjection(owner=null, name=content_new, alias=Optional.empty), ColumnProjection(owner=null, name=content_new_2, alias=Optional.empty), ColumnProjection(owner=null, name=order_name, alias=Optional.empty), ColumnProjection(owner=null, name=item_cd, alias=Optional.empty)])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@6a9b0a6f, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@10667848, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@191a709b, containsSubquery=false)
[main] INFO ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM t_order_0
[main] INFO ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM t_order_1
[main] INFO ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM t_order_0
[main] INFO ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM t_order_1
```

So I want to know what is your configuration? What is the abnormal phenomenon?

**Comment by stelin** [comment]
I work will like your method. but I  do not configure `TableRuleConfiguration`,  becase only want to sharding for datasource.If must to configure table runles,It's very troublesome for many tables(200+)

**Comment by stelin** [comment]
Only one rule for database.Has not table rules.
![image](https://user-images.githubusercontent.com/1677543/121518045-9dcba580-ca22-11eb-8439-3abe921da83b.png)

**Comment by stelin** [comment]
If must to configure table rules like below.
![image](https://user-images.githubusercontent.com/1677543/121518217-d0759e00-ca22-11eb-851c-3d6d386f9c8b.png)

**Comment by stelin** [comment]
It's very troublesome, because every table must to be configured.

**Comment by stelin** [comment]
We only want to switch datasource(database), It has nothing to do with tables.

**Comment by strongduanmu** [comment]
@stelin Do you mean that your tables are all non-sharding tables, so `TableRuleConfiguration` is not configured? It should be noted that `DefaultDatabaseShardingStrategyConfig` is for the configuration of sharding tables, and it is inappropriate to use in this scenario.

**Comment by strongduanmu** [comment]
@stelin In version 4.x, you need to configure `shardingRuleConfig.setDefaultDataSourceName("ds_0");` to meet your needs. In version 5.x, we introduced the concept of [single table](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sql/#%E5%8D%95%E8%A1%A8), you can route these tables automatically without any configuration.

**Comment by stelin** [comment]
@strongduanmu 

Yes my tables are all non-sharding tables. Now in version 4.x is not supported! But version 5.x do not released. If  5.x can use?

**Comment by strongduanmu** [comment]
@stelin In version 4.x, you can configure `shardingRuleConfig.setDefaultDataSourceName("ds_0")`;

**Comment by stelin** [comment]
https://mvnrepository.com/artifact/org.apache.shardingsphere/sharding-jdbc-spring-boot-starter

![image](https://user-images.githubusercontent.com/1677543/121621336-8e8a3d80-ca9e-11eb-8f22-733b754f2393.png)

**Comment by stelin** [comment]
I configured shardingRuleConfig.setDefaultDataSourceName("ds_0"), But can not to switch datasource;

**Comment by stelin** [comment]
Want to switch datasource by application context(like http header)

**Comment by stelin** [comment]
hint:algorithm-class-name can not worker for this.

**Comment by stelin** [comment]
Single table can not solved.My scenario is one datasource has many tables. Olny sharding for database(datasource). Tables not to sharding

**Comment by strongduanmu** [comment]
> Single table can not solved.My scenario is one datasource has many tables. Olny sharding for database(datasource). Tables not to sharding

@stelin If you need sharding, then you need to configure sharding rules. You can either shard the database and the table at the same time, or you can only shard the database or only the table. Without configuration rules, the Hint sharding algorithm will definitely not take effect.

**Comment by stelin** [comment]
If only want to  sharding for database(datasource), then  with configuration table rules is very troublesome. If add one table ,must to add configuration

**Comment by strongduanmu** [comment]
@stelin If you have a better solution about sharding api, please submit an issue to the community for discussion.

**Comment by stelin** [comment]
Now can not use shardingjdbc to my scenario. You have solution？

**Comment by strongduanmu** [comment]
@stelin As I said before, configure sharding rules.

**Comment by stelin** [comment]
Understanded

**Comment by strongduanmu** [comment]
@stelin If this issue has been resolved, please close it. If you have a better idea, please submit an issue to discuss about sharding api.

**Comment by stelin** [comment]
A a better method to supported switch datasource without any   table sharding rules configuration.

**Comment by stelin** [comment]
But now is not supported.

**Comment by strongduanmu** [comment]
@stelin Your idea is to change the sharding api and the underlying implementation, which needs to be discussed by the community. 
The previous demo has given an example where the hint can be executed normally after configuring the sharding rules. So I think this issue can be closed. If you have configured sharding rules and encounter other problems, please submit a new issue and upload the corresponding demo.

**Comment by stelin** [comment]
Thanks

**Comment by stelin** [comment]
Can supported table match rules:

`
shardingRule:
  tables:
   order_*:
        actualDataNodes: demo_ds_${0..1}.t_order_${0..1}
        databaseStrategy:
          hint:
            algorithmClassName: io.shardingsphere.userAlgo.HintAlgorithm
        tableStrategy:
          hint:
            algorithmClassName: io.shardingsphere.userAlgo.HintAlgorithm
`

**Comment by wanlongz** [comment]
@stelin How did you solve it in the end? I have the same problem

**Comment by tuziaifendou** [comment]
> @stelin In version 4.x, you need to configure `shardingRuleConfig.setDefaultDataSourceName("ds_0");` to meet your needs. In version 5.x, we introduced the concept of [single table](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sql/#%E5%8D%95%E8%A1%A8), you can route these tables automatically without any configuration.

 In version 4.1.1，when i add spring.shardingsphere.sharding.default-data-source-name=ds0，then service starts very slowly.



> @stelin In version 4.x, you need to configure `shardingRuleConfig.setDefaultDataSourceName("ds_0");` to meet your needs. In version 5.x, we introduced the concept of [single table](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sql/#%E5%8D%95%E8%A1%A8), you can route these tables automatically without any configuration.

 In version 4.1.1，when i add spring.shardingsphere.sharding.default-data-source-name=ds0.when start service，meta data load cost about 204022 milliseconds,then service starts very slowly. how to solution？

**Comment by tuziaifendou** [comment]
> @stelin In version 4.x, you need to configure `shardingRuleConfig.setDefaultDataSourceName("ds_0");` to meet your needs. In version 5.x, we introduced the concept of [single table](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sql/#%E5%8D%95%E8%A1%A8), you can route these tables automatically without any configuration.

In version 4.1.1，when i add spring.shardingsphere.sharding.default-data-source-name=ds0.when start service，meta data load cost about 204022 milliseconds,then service starts very slowly. how to solution？

**Comment by tuziaifendou** [comment]
> @stelin How did you solve it in the end? I have the same problem

I have the same problem too

**Comment by strongduanmu** [comment]
> > @stelin How did you solve it in the end? I have the same problem
> 
> I have the same problem too

@tuziaifendou I think you can submit a new issue to describe your problem.

**Comment by tuziaifendou** [comment]
您好，我现在正在工作中，无法亲自回复您的邮件。我将在工作结束后，尽快给您回复。
