### ISSUE TITLE
Create `AlterTableStatementFederateRefresher`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10696]
Hi community,

This issue needs more effort than good-first-issue. Hope you can enjoy it. :)

### Target 
- Create a class named `AlterTableStatementFederateRefresher` which is to renew `FederateSchemaMetadata` when users execute `alter table xxx` SQL. (It is simple to figure out that once the table structure changes, the metadata needs to be refreshed accordingly)
- Add a unit test for your change

### How
- Create a class named `AlterTableStatementFederateRefresher` implementing `FederateRefresher<AlterTableStatement>`
Here are some tips,
1. Please refer to `CreateTableStatementFederateRefresher` and `AlterTableStatementSchemaRefresher`
2. The keypoint is to get the latest `TableMetaData` and call `FederateSchemaMetadata`.`renew()`. That way, `AlterTableStatementSchemaRefresher` will help you know how to create a `TableMetaData` 
- Add this one to `MetadataRefresherFactory`
- Add a unit test similar to `AlterTableStatementSchemaRefresherTest` and #10695

**Comment by MingxingLAI** [comment]
Can I take this issue and #10697 ?

**Comment by strongduanmu** [comment]
> Can I take this issue and #10697 ?

@MingxingLAI Assigned.

**Comment by yinyichao** [comment]
Please assign to me.
