### ISSUE TITLE
Distsql create sharding table rule based on readwrite_splitting rule error

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10692]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy & governance

### Expected behavior

create sharding table rule based on readwrite_splitting rule success

### Actual behavior

```sql
mysql> CREATE SHARDING TABLE RULE t_order (
    ->     RESOURCES(ms_group_0,ms_group_1),
    ->     SHARDING_COLUMN=order_id,
    ->     TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=4)),
    ->     GENERATED_KEY(COLUMN=another_id,TYPE(NAME=snowflake,PROPERTIES("worker-id"=123)))
    -> );
ERROR 1102 (C1102): Resources [ms_group_0, ms_group_1] do not exist in schema sharding_db.
```

**Comment by RaigorJiang** [comment]
I will do this, please assign to me, thanks!
