### ISSUE TITLE
Add unit test for CreateTableStatementFederateRefresher

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10695]
Hi, 

Thanks for your interest.
This issue is to add a unit test for CreateTableStatementFederateRefresher.
If you want to have an example, please refer to `CreateTableStatementSchemaRefresherTest`.

**Comment by yiwenlong** [comment]
Please assign to me.

**Comment by strongduanmu** [comment]
> Please assign to me.

@yiwenlong Assigned.

**Comment by yinyichao** [comment]
Please assign to me.

**Comment by liulong99** [comment]
Please assign to me.

**Comment by menghaoranss** [comment]
CreateTableStatementFederateRefresher has been merged into CreateTableStatementSchemaRefresher, I will close this issue,  @yinyichao you can refer to the another issue #14083
