### ISSUE TITLE
Is there any possibility to disable loadDefaultSchemaMetaData at project startup?

### ISSUE THREAD

**Issue by smcdl** [apache/shardingsphere#10694]
ShardingMetaDataLoader#loadDefaultSchemaMetaData takes so much time when project startup. I don't konw why It needs to load the schema of all tables？I try to repack the sharding-core-common.jar by disabling loadDefaultSchemaMetaData. It works very well. So anyone can tell me whether I am doing the wrong thing ?

**Comment by terrymanu** [comment]
Please try to version 5.x, the performance it better than before.
