### ISSUE TITLE
Duplicated code fragment in FederateRefresher

### ISSUE THREAD

**Issue by MingxingLAI** [apache/shardingsphere#10714]
![企业微信截图_a6ebbc14-7532-4418-bd6c-a9b0cb8ec64d](https://user-images.githubusercontent.com/80867129/121157415-20663080-c87c-11eb-920c-2944c313dccb.png)

`loadTableMetaData` function will be used in multiple different files. I suggest to promote a parent class, for example, `AbstractFederateRefresher`, which implement some common methods.

**Comment by terrymanu** [comment]
Closed because the pull request closed without reason explained.
