### ISSUE TITLE
The merge method of ShardingDQLResultMerger will throw exception when queryResults.size()==0

### ISSUE THREAD

**Issue by mlkui** [apache/shardingsphere#10724]
### Which version of ShardingSphere did you use?
Current master branch, commit id: gd4d1ca2522

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Show explicit error message.

### Actual behavior
Unchecked IndexOutOfBoundsException expection is thrown.

### Reason analyze (If you can)
The merge method of ShardingDQLResultMerger should not be invoked at all. 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. SELECT * FROM phycial_table_not_exist_in_the_phycial_database
2. You will get java.lang.IndexOutOfBoundsException: Index:0, Size:0

**Comment by strongduanmu** [comment]
I used `sharding` table and `single` table to test, and the exceptions you reported were not reproduced, but appropriate exceptions were thrown.

```
mysql> select * from t_order_item_test;
ERROR 1999 (C1999): Unknown exception: [`t_order_item_test` single table does not exist.]

mysql> select * from t_order_item;
ERROR 1146 (42S02): Table 'demo_ds_0.t_order_item_0' doesn't exist
```
