### ISSUE TITLE
How to support people's congress gold warehouse database [domestic database] Kingbase

### ISSUE THREAD

**Issue by hgx615** [apache/shardingsphere#10725]
## **Please increase the function of domestic database - DZJCANG KINGBASE database**

       Our system uses the middleware to complete the database library, table, read and write separation functions.However, now the company requires us to replace our database with a domestic database - Renda Jincang Kingbase database. Currently, our middleware does not support Renda Jincang Kingbase database, so we have to make a choice:
1. If this middleware can support DZJCANG Kingbase database, continue to use this middleware; otherwise, it is necessary to choose other middleware with this function.Since we have been using this middleware for some time and are familiar with its development, operation and maintenance, we hope to continue to use this middleware. However, we are not yet capable of expanding the development and support of DZJCang Kingbase database on the basis of this middleware. Please kindly confirm whether you can support the domestic database:The functions of DZJCANG KINGBASE database.
thank you

**Comment by terrymanu** [comment]
This database is not for open source, we can not get the environment of this database. I have no idea to support it.
