### ISSUE TITLE
Logical table names could NOT be replaced by physical table names for SQL contains JOIN condition 

### ISSUE THREAD

**Issue by mlkui** [apache/shardingsphere#10723]
### Which version of ShardingSphere did you use?
Current master branch, commit id: gd4d1ca2522

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Logical table names are replaced by their physical table names for SQL contains JOIN condition 

### Actual behavior
Logical table names could NOT been replaced by their physical table names for SQL contains JOIN condition 

### Reason analyze (If you can)
Calsite does not perform table name replacing procedure?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Assign physical table names T1 and T2 for two logic tables LT1 and LT2 using actual-data-nodes configuration;
2. SELECT * FROM LT1 will properly be rewritten to SELECT * FROM T1;
3. SELECT * FROM LT1 JOIN LT2 ON LT1.ID=LT2.ID will NOT be rewritten to SELECT * FROM T1 JOIN T2 ON T1.ID=T2.ID

**Comment by strongduanmu** [comment]
@mlkui When multiple unbinding sharding tables perform join related queries, calcite will be used for query optimization, and calcite will convert logical tables into physical tables internally.

We have optimized this scenario in the master branch. Welcome to use the latest code to test and feedback the results.
