### ISSUE TITLE
Custom Sharding Algortihm

### ISSUE THREAD

**Issue by No-Silver-J** [apache/shardingsphere#10761]
dear teams:

When I implemented a custom sub-table algorithm, I encountered a problem, as shown in the figure. The error is this exception, indicating that I did not implement the class according to the type I configured.
However, I have already configured the full package name of the implementation class in the META-INF.SERVICES directory. I don't know how to solve this problem
![image](https://user-images.githubusercontent.com/45869667/121654958-d2963600-cad0-11eb-9cbb-e0ef37a6ac29.png)

**Comment by RaigorJiang** [comment]
Hi @No-Silver-J 
It is a little complicated to implement SPI, so we provided a way to define custom algorithm called `class based sharding algorithm`,  please ref to

**Comment by Beyondeclipse** [comment]
Hi @No-Silver-J 
It is not that difficult to implement algorithm SPI . Please try to follow this example:
1. Create your class  implemented org.apache.shardingsphere.sharding.api.sharding.standard.StandardShardingAlgorithm.
2. Create file "org.apache.shardingsphere.sharding.spi.ShardingAlgorithm" in src/main/resources/META-INF/services.
3. Add your class with package in the file, like: "xxxx.xxx.xxxx.TableAlgorithm".
4. config setting like this:
`rules:
-
  tables:
    TABLE_SHARDING_DEMO:
      actualDataNodes: demo_00${0..1}.TABLE_SHARDING_DEMO
      databaseStrategy: &demo
        standard:
          shardingColumn: demo_name
          shardingAlgorithmName: mod_2

  shardingAlgorithms:
    mod_2:
      type: MOD_2  # returned value of method "getType()" in your implemented class
      props:`

**Comment by terrymanu** [comment]
No enough information, I just close the issue.
