### ISSUE TITLE
Add unit test for isAllTablesInSameDataSource method in shardingRule

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10764]
Hi,

This issue is to add a unit test for `isAllTablesInSameDataSource` method in `shardingRule`.

If you want to have an example, please refer to the test case for other method in `ShardingRuleTest`.

**Comment by sreeja97** [comment]
Can I work on this issue?

**Comment by strongduanmu** [comment]
@sreeja97 Welcome, i will assign this issue to you.

**Comment by zzs52** [comment]
Can i try?

**Comment by strongduanmu** [comment]
> Can i try?

@zzs52 Of course.

**Comment by strongduanmu** [comment]
Fixed by #14997.
