### ISSUE TITLE
[DISCUSS] New release 5.0.0-beta is coming!

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10787]
Hi community,

This issue is a starting signal for our next release, i.e., 5.0.0-beta.

As you know, we have been preparing for this release for over half of a year. But I assume it is worth waiting for this wonderful release. So please give a look at [1] to learn more about its release note. Hope the features you expect are on this list!

If you are still working on some issues which are supposed to catch this release, please contact me ASAP. What's more, we welcome any suggestions and feedback from you.

Warm regards,
Trista

[1] https://u01f1kqxrl.feishu.cn/sheets/shtcnA9X7ChUhpb2N4AASwgExKf

**Comment by tristaZero** [comment]
Here, thanks to everyone who helped boost this release coming. 👍 

@wgy8283335 
@ThanoshanMV 
@Liangda-w
@sandynz
@huanghao495430759 
@zhujunxxxxx 
@totalo 
@avalon5666
@MingxingLAI 
@RaigorJiang
@zjcnb

**Comment by terrymanu** [comment]
I'm looking forward to it

**Comment by tristaZero** [comment]
Hi,

5.0.0-beta is on the voting stage, please refer to [Vote Process](https://lists.apache.org/thread.html/rb2132469b082ed42ca2621c57af900c5ea0d4160283f0856da7e841e%40%3Cdev.shardingsphere.apache.org%3E) to cast your vote.

Best,
Trista

**Comment by fzyzcjy** [comment]
Hi, I wonder when can we use 5.0.0 in our *production environment*? Or, do you suggest that we should not use it, but should use 4.x? Thanks!

**Comment by tristaZero** [comment]
Hi my suggestion is to consider 5.0.0-alpha or beta. @fzyzcjy

**Comment by fzyzcjy** [comment]
@tristaZero Thanks for the reply. So when will we be able to use it in production?

**Comment by tristaZero** [comment]
Hi, I suppose it will be online next week.

**Comment by tristaZero** [comment]
Hi, [Mail list](https://lists.apache.org/thread.html/rb2132469b082ed42ca2621c57af900c5ea0d4160283f0856da7e841e%40%3Cdev.shardingsphere.apache.org%3E) will show you what is going on.

**Comment by tristaZero** [comment]
[The vote](https://lists.apache.org/thread.html/r2d33d7951061f3abbb3d91d2b69816acfc5da6d47ce4e57fafd0672a%40%3Cdev.shardingsphere.apache.org%3E) of this release passed, thanks for your review. I will publish it ASAP.

**Comment by tristaZero** [comment]
Hi all,

5.0.0-beta has released now, thanks for your attention.

You will find the announcement here.
https://lists.apache.org/thread.html/r3b91e470044c2f8151906b66c49f2d618c28f775085408a14d55aec7%40%3Cdev.shardingsphere.apache.org%3E
