### ISSUE TITLE
Add more test cases for shardingsphere-sql-parser-engine module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10796]
- [ ] Add test case for SQLParserEngine
- [ ] Add test case for DatabaseTypedSQLParserFacadeRegistry with DatabaseTypedSQLParserFacade fixture
- [x] Add test case for ParseASTNode

**Comment by LeeGuoPing** [comment]
I want to try it

**Comment by terrymanu** [comment]
@LeeGuoPing  Welcome, I just assigned to you.

**Comment by LeeGuoPing** [comment]
when I add test case named DatabaseTypedSQLParserFacadeRegistryTest,  I created a new package name fixture, it contains DatabaseLexer, DatabaseParser,DatabaseParserFacade. And use SPI to test it, my idea is right?

![image](https://user-images.githubusercontent.com/35389145/122164522-80c32680-cea9-11eb-854e-96caa8eefcdf.png)

**Comment by LeeGuoPing** [comment]
But now I don't understand how to add test case for SQLParserEngine,  Can you give me some advice, thank you @terrymanu

**Comment by terrymanu** [comment]
> when I add test case named DatabaseTypedSQLParserFacadeRegistryTest, I created a new package name fixture, it contains DatabaseLexer, DatabaseParser,DatabaseParserFacade. And use SPI to test it, my idea is right?
> 
> ![image](https://user-images.githubusercontent.com/35389145/122164522-80c32680-cea9-11eb-854e-96caa8eefcdf.png)

You are correct

**Comment by terrymanu** [comment]
> But now I don't understand how to add test case for SQLParserEngine, Can you give me some advice, thank you @terrymanu

It is better to mock sqlParserExecutor and parseTreeCache, then verify the call times of `parse`
