### ISSUE TITLE
Calcite always can not download when mvn install in windows env

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#10810]
Calcite lib always can not download when mvn install in windows env, please investigate the reason.

error log:

```
Error:  Failed to execute goal on project shardingsphere-infra-optimize: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-infra-optimize:jar:5.0.0-RC1-SNAPSHOT: Failed to collect dependencies at org.apache.calcite:calcite-core:jar:1.26.0: Failed to read artifact descriptor for org.apache.calcite:calcite-core:jar:1.26.0: Could not transfer artifact org.apache.calcite:calcite-core:pom:1.26.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/calcite/calcite-core/1.26.0/calcite-core-1.26.0.pom: Connection reset -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :shardingsphere-infra-optimize
Error: Process completed with exit code 1.
```

**Comment by Beyondeclipse** [comment]
I guest it may be the net enviroment problem. I just run "mvn install" successfully with the newest codes in wndows env through my nexus server.

**Comment by FujiwaraTakumi** [comment]
I build successfully as well with latest code via "mvn clean install -Prelease".

`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22:02 min
[INFO] Finished at: 2021-06-16T12:41:20+08:00
[INFO] ------------------------------------------------------------------------
`

**Comment by terrymanu** [comment]
What I mean is in GitHub Action, mvn install failure

**Comment by TeslaCN** [comment]
I found something here https://github.com/actions/virtual-environments/issues/1499
