### ISSUE TITLE
Hello, I have a problem now, but I don't know the cause of the problem

### ISSUE THREAD

**Issue by imOneDa** [apache/shardingsphere#10811]
When I try to use ShardingSphere-JDBC for my project, I get an error at project startup with the following message:

Failed to instantiate [org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource]: Constructor threw exception; nested exception is java.lang.AbstractMethodError: com.mysql.JDBC4Connection.getScheam()Ljava/lang/String;

(sorry,I can't copy any logs because we have strict security measures)
![20210610160712011](https://user-images.githubusercontent.com/85914520/121984143-0d47e900-cdc5-11eb-9dd1-fb5d5e2ad035.jpg)

This is part of my configuration file:
![20210610160825744](https://user-images.githubusercontent.com/85914520/121984179-1b960500-cdc5-11eb-9d31-40fedd3356ca.jpg)

I don't know how to solve this problem,help me please,thanks.

**Comment by TeslaCN** [comment]
What's the version of MySQL JDBC driver?

**Comment by imOneDa** [comment]
> What's the version of MySQL JDBC driver?

<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.5</version>
</dependency>

thanks.
