### ISSUE TITLE
HintShardingAlgorithm 不生效

### ISSUE THREAD

**Issue by Dave-he** [apache/shardingsphere#10823]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
这样配置了Hint策略但是没有生效
<img width="863" alt="image" src="https://user-images.githubusercontent.com/20518717/122059675-765c4a80-ce1f-11eb-94a2-8c684e2196a0.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/20518717/122059573-5dec3000-ce1f-11eb-9ede-37522a0e7123.png">

### Actual behavior
<img width="725" alt="image" src="https://user-images.githubusercontent.com/20518717/122059720-83793980-ce1f-11eb-80cb-fff66f5dbef0.png">

### Reason analyze (If you can)
Hint强制执行，在init阶段就没有生效

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
