### ISSUE TITLE
Can I use ShardingSphere fully reactive with R2DBC without proxy and sidecar?

### ISSUE THREAD

**Issue by sgc109** [apache/shardingsphere#10837]
Hi, I'm a newbie for this great library and I have a question!

I've googled and looked for documentations and Github issues, but there I couldn't find any mention of R2DBC in an environment that doesn't use proxy.

When I see documentation for ShardingSphere-JDBC, it only talks about JDBC.

I saw some discussions in this issue(https://github.com/apache/shardingsphere/issues/8073) and I wonder if I should use proxy to get it fully non-blocking with R2DBC.

Thank you!

**Comment by terrymanu** [comment]
Not sure, it for JDBC only for now.
It is better to try R2DBC

**Comment by terrymanu** [comment]
I just close this issue because of no feedback for long time.
