### ISSUE TITLE
Sharding-JDBC 4.1.0：ShardingSphereException: Cannot support Multiple-Table for org.apache.shardingsphere.sql.parser.sql.statement.dml.DeleteStatement

### ISSUE THREAD

**Issue by trycache0828** [apache/shardingsphere#10843]
## Question

The deletion operation encountered this problem：

org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Cannot support Multiple-Table for &apos;org.apache.shardingsphere.sql.parser.sql.statement.dml.DeleteStatement@2c20c02f&apos;.

![QQ截图20210617162736](https://user-images.githubusercontent.com/14318621/122361765-22ba4000-cf8a-11eb-8c0c-5a02ae95d974.png)

## Usage scenarios

Spring 3.x + Hibernate 4.x + Sharding-JDBC 4.1.0

## Table structure

![sharding-table](https://user-images.githubusercontent.com/14318621/122363927-ee478380-cf8b-11eb-85fa-96d6d3dc21b0.png)

## Sharding Configration

[com.zaxxer.hikari.HikariDataSource]HikariPool-1 - Starting...
[com.zaxxer.hikari.HikariDataSource]HikariPool-1 - Start completed.
[org.apache.shardingsphere.core.log.ConfigurationLogger]ShardingRuleConfiguration:
tables:
  s_tantic:
    actualDataNodes: master.s_tantic_${2019..2023}
    logicTable: s_tantic
    tableStrategy:
      standard:
        preciseAlgorithmClassName: org.st.core.extend.datasource.shardingjdbc.DatePreciseShardingAlgorithm
        rangeAlgorithmClassName: org.st.core.extend.datasource.shardingjdbc.DateRangeShardingAlgorithm
        shardingColumn: create_date

[org.apache.shardingsphere.core.log.ConfigurationLogger]Properties:
sql.show: 'true'
check.table.metadata.enabled: 'false'

## Dependency package

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.1.0</version>
        </dependency>

**Comment by strongduanmu** [comment]
@trycache0828 What is the type of two tables? BTW, can you the latest version?

**Comment by trycache0828** [comment]
Problem resolved, SQL statement alias setting problem in project.

So,the solution is to remove the alias in the query condition code!

Thank you for your attention!

## Original SQL

DELETE FROM s_tantic WHERE s_tantic.code = '0010'  AND ID = '8aa0b39f7960f4c801764b287c303856'

## New SQL

DELETE FROM s_tantic WHERE code = '0010'  AND ID = '8aa0b39f7960f4c801764b287c303856'

## Inspiration for problem solving

![sharding-4 1 1-delete-question](https://user-images.githubusercontent.com/14318621/122528290-b9e8cb80-d04e-11eb-94c3-edeee54dc432.png)

**Comment by trycache0828** [comment]
Sharding JDBC middleware version has been changed from 4.1.0 to 4.1.1. Tried to use sharding JDBC middleware version 5.0.0-alpha.I heard that the latest version is 5.0.0

**Comment by trycache0828** [comment]
> @trycache0828 What is the type of two tables? BTW, can you the latest version?

Sharding JDBC middleware version has been changed from 4.1.0 to 4.1.1. Tried to use sharding JDBC middleware version 5.0.0-alpha.I heard that the latest version is 5.0.0

**Comment by strongduanmu** [comment]
@trycache0828 The result of SQL rewriting of version 4.1 is wrong, you can try version 5.x to see if there are similar problems?

**Comment by trycache0828** [comment]
> @trycache0828 The result of SQL rewriting of version 4.1 is wrong, you can try version 5.x to see if there are similar problems?

Sharding JDBC middleware version 5.0.0 cannot be downloaded.

## Dependency package

    
    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
        <version>5.0.0</version>
    </dependency>

    
    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>sharding-jdbc-core</artifactId>
        <version>5.0.0</version>
    </dependency>

## question

Could not find artifact org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:pom:5.0.0 in central (https://repo.maven.apache.org/maven2)

**Comment by strongduanmu** [comment]
@trycache0828 Change maven groupId to `org.apache.shardingsphere`.

**Comment by trycache0828** [comment]
> @trycache0828 Change maven artifactId to `shardingsphere-jdbc-core`.

maven artifactId sharding-jdbc-spring-boot-starter Is it necessary?I've added shardingsphere-jdbc-core for 5.0.0-beta.What's the difference between the three.（sharding-jdbc-spring-boot-starter, sharding-jdbc-core and shardingsphere-jdbc-core）

**Comment by trycache0828** [comment]
> @trycache0828 Change maven artifactId to `shardingsphere-jdbc-core`.

maven artifactId sharding-jdbc-spring-boot-starter Is it necessary?I've added shardingsphere-jdbc-core for 5.0.0-beta.What's the difference between the three.（sharding-jdbc-spring-boot-starter, sharding-jdbc-core and shardingsphere-jdbc-core）

**Comment by trycache0828** [comment]
> @trycache0828 Change maven artifactId to `shardingsphere-jdbc-core`.

Can't find Class for org.apache.shardingsphere.api.sharding.standard.PreciseShardingAlgorithm and org.apache.shardingsphere.api.sharding.standard.RangeShardingAlgorithm etc.

Use middleware version 5.0.0-beta

## Dependency package

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-beta</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.0.0-beta</version>
        </dependency>

**Comment by strongduanmu** [comment]
@trycache0828 In version 5.0.0-beta, PreciseShardingAlgorithm has been integrated into StandardShardingAlgorithm, please refer to the official documentation for more information.
