### ISSUE TITLE
sharding-sate：The global timeout is not set

### ISSUE THREAD

**Issue by shihaozhangtong** [apache/shardingsphere#10841]
function：org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingTransactionManager#begin
image：
![image](https://user-images.githubusercontent.com/54934390/122349445-d87f9180-cf7e-11eb-8b8f-9e58153ac410.png)

**Comment by terrymanu** [comment]
Anyone interest to fix the issue?

**Comment by strongduanmu** [comment]
@99ashish Welcome.

**Comment by challengeof** [comment]
@strongduanmu Hi I submitted a PR fixed this issue please help review. #14214

**Comment by strongduanmu** [comment]
> @strongduanmu Hi I submitted a PR fixed this issue please help review. #14214

Hi @jingshanglu, can you help review this pr #14214.
