### ISSUE TITLE
Modify getSaneResult() implementation of Sharding JDBC

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10844]
Ref to #10138
We found that there is a problem with the implementation of `getSaneResult`, which will cause SQL execution exceptions to not be thrown normally.
Now we are going to change all the anonymous implementations of the `getSaneResult` method used in Sharding-JDBC to return `Optional.empty()` so that the code structure can be preserved and expanded when needed in the future.

Impacted classes：
```
BatchPreparedStatementExecutor.class
JDBCExecutorCallbackTest.class
ShardingSpherePreparedStatement.class
ShardingSphereStatement.class
```

**Comment by Mr-Zhe** [comment]
So many bugs
