### ISSUE TITLE
Why default-database-strategy is supported for different version?

### ISSUE THREAD

**Issue by stelin** [apache/shardingsphere#10857]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
- 4.0.0.rc2
- 4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
- ShardingSphere-JDBC

### Expected behavior
4.0.0.rc2 or 4.1.1 is supported.
### Actual behavior
Only 4.0.0.rc2 is supported, 4.1.1 is not supported.
### Example codes for reproduce this issue (such as a github link).
The configuration:

```
spring.shardingsphere.datasource.names=ds_test,ds_test-rw
spring.shardingsphere.datasource.ds_test.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds_test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds_test.url=xxx
spring.shardingsphere.datasource.ds_test.username=test
spring.shardingsphere.datasource.ds_test.password=123456
spring.shardingsphere.datasource.ds_test.initial-size=1
spring.shardingsphere.datasource.ds_test-rw.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds_test-rw.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds_test-rw.url=xxx
spring.shardingsphere.datasource.ds_test-rw.username=test
spring.shardingsphere.datasource.ds_test-rw.password=123456
spring.shardingsphere.datasource.ds_test-rw.initial-size=1
spring.shardingsphere.sharding.master-slave-rules.ds_20001.name=ds_20001
spring.shardingsphere.sharding.master-slave-rules.ds_20001.master-data-source-name=ds_test
spring.shardingsphere.sharding.master-slave-rules.ds_20001.slave-data-source-names[0]=ds_test-rw
spring.shardingsphere.sharding.default-data-source-name=ds_20001
spring.shardingsphere.sharding.default-database-strategy.hint.algorithm-class-name=xxx.xxx.MySharding
spring.shardingsphere.props.sql.show=true
```

The hintShardingAlgorithm:
```
public class MySharding implements HintShardingAlgorithm<String> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<String> shardingValue) {
        System.out.println(shardingValue);
        return availableTargetNames;
    }
}
```

The code:
```
HintManager.getInstance().setDatabaseShardingValue("ds_20001");
```

**Comment by stelin** [comment]
@strongduanmu

**Comment by stelin** [comment]
like https://github.com/apache/shardingsphere/issues/5970

![image](https://user-images.githubusercontent.com/1677543/122518438-c74c8880-d043-11eb-873b-63b1581fc7a6.png)

**Comment by strongduanmu** [comment]
@stelin Do you mean to use `default-database-strategy` in read-write separation scenarios? 

In issue #10699, I have explained that `default-database-strategy` is used in `sharding` scenarios. Read-write splitting will automatically determine whether to use the write database or the read database.

**Comment by stelin** [comment]
default-database-strategy use to swith datasource. 4.0.0.rc2 is supported for test.

**Comment by stelin** [comment]
Now must to use 4.0.0.rc2.

**Comment by stelin** [comment]
I think this is  a bug in 4.1.1.

**Comment by strongduanmu** [comment]
> I think this is a bug in 4.1.1.

@stelin No, it's not a bug. If you need to use `default-database-strategy` in `read-write splitting` scenarios, you can integrate `read-write splitting` and `sharding` together.

**Comment by stelin** [comment]
Must sharding together is very strange!

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
