### ISSUE TITLE
Some CSS code appeared in documents

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#10852]
## Bug Report

https://shardingsphere.apache.org/blog/cn/videos/

![image](https://user-images.githubusercontent.com/20503072/122502801-e9391180-d029-11eb-9cd9-d3f235ca4775.png)

**Comment by totalo** [comment]
hi @TeslaCN .I have a local test, as if writing like this is no problem, please take a look

**Comment by totalo** [comment]
![image](https://user-images.githubusercontent.com/29777558/122948006-25170280-d3ad-11eb-81dd-1435ad9623bb.png)
