### ISSUE TITLE
Inconsistent case check problem

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10863]
### Which version of ShardingSphere did you use?
4.1.1 & 5.0.0-RC1-SNAPSHOT

There is an inconsistency in case handling in class `TablesContext` and `ProjectionsContextEngine`, which needs to be corrected.

![image](https://user-images.githubusercontent.com/5668787/122533896-9a54a180-d054-11eb-8958-a19565c2d981.png)

**Comment by zoujianchao** [comment]
I'll do it

**Comment by yx9o** [comment]
could you assign this issue to me

**Comment by RaigorJiang** [comment]
Hi @zoujianchao  
Welcome~

**Comment by RaigorJiang** [comment]
@yx9o  Sorry, I do not hava permission to assign task, and @zoujianchao has take it,  please try another issue, thank you.
