### ISSUE TITLE
AESEncryptAlgorithm can Not use Properties to get the right AES_KEY Value

### ISSUE THREAD

**Issue by nanzheng** [apache/shardingsphere#10867]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### shardingsphere-encrypt-core Module

---exception code----

private byte[] createSecretKey() {
        Preconditions.checkArgument(props.containsKey(AES_KEY), String.format("%s can not be null.", AES_KEY));
        return Arrays.copyOf(DigestUtils.sha1(props.getProperty(AES_KEY)), 16);
    }

---settings----

spring.shardingsphere.rules.encrypt.encryptors.name_encryptor.type=AES
spring.shardingsphere.rules.encrypt.encryptors.name_encryptor.props.aes-key-value=123456
#spring.shardingsphere.encrypt.encryptors.pwd_encryptor.type=md5

spring.shardingsphere.rules.encrypt.tables.encrypt_user.columns.user_name.plain-column=user_name_plain
spring.shardingsphere.rules.encrypt.tables.encrypt_user.columns.user_name.cipher-column=user_name
spring.shardingsphere.rules.encrypt.tables.encrypt_user.columns.user_name.encryptor-name=name_encryptor
#spring.shardingsphere.encrypt.tables.encrypt_user.columns.pwd.cipherColumn=pwd
#spring.shardingsphere.encrypt.tables.encrypt_user.columns.pwd.encryptor=pwd_encryptor

### Expected behavior

 Preconditions.checkArgument(props.containsKey(AES_KEY), String.format("%s can not be null.", AES_KEY));
this step will pass and return the true

### Actual behavior

 Preconditions.checkArgument(props.containsKey(AES_KEY), String.format("%s can not be null.", AES_KEY));
this step props is empty and return the false

### Reason analyze (If you can)

in version 4.0.0

public abstract class TypeBasedSPIServiceLoader<T extends TypeBasedSPI> {
    private final Class<T> classType;

    public final T newService(String type, Properties props) {
        Collection<T> typeBasedServices = this.loadTypeBasedServices(type);
        if (typeBasedServices.isEmpty()) {
            throw new RuntimeException(String.format("Invalid `%s` SPI type `%s`.", this.classType.getName(), type));
        } else {
            T result = (TypeBasedSPI)typeBasedServices.iterator().next();
            result.setProperties(props);  //renew the Properties
            return result;
        }
    }
}

but where is setProperties step  in 5.0.0 ?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

insert into sql

**Comment by tristaZero** [comment]
Do you point [This one](https://github.com/apache/shardingsphere/blob/8ee0074d018ce56487bc0138d84acc097c28002b/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/spi/typed/TypedSPIRegistry.java#L100)?

**Comment by nanzheng** [comment]
> Do you point [This one](https://github.com/apache/shardingsphere/blob/8ee0074d018ce56487bc0138d84acc097c28002b/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/spi/typed/TypedSPIRegistry.java#L100)?

right, so this util class is not in the 5.0.0, which class pass the value to setProperties?

**Comment by RaigorJiang** [comment]
Hi @nanzheng 
I checked [encrype example ](https://github.com/apache/shardingsphere/tree/8ee0074d018ce56487bc0138d84acc097c28002b/examples/shardingsphere-jdbc-example/other-feature-example/encrypt-example/encrypt-spring-boot-example)
and the properties is as expected.

You may want to see the class `EncryptAlgorithmFactoryBean` to find the SPI load logic.

**Comment by nanzheng** [comment]
> Hi @nanzheng
> I checked [encrype example ](https://github.com/apache/shardingsphere/tree/8ee0074d018ce56487bc0138d84acc097c28002b/examples/shardingsphere-jdbc-example/other-feature-example/encrypt-example/encrypt-spring-boot-example)
> and the properties is as expected.
> 
> You may want to see the class `EncryptAlgorithmFactoryBean` to find the SPI load logic.

Thank for your reply. So EncryptAlgorithmFactoryBean will pass the propeties value into the algorithm? I will check it out.

**Comment by RaigorJiang** [comment]
Yes,  notice the super class `ShardingSphereAlgorithmFactoryBean`.

**Comment by Keanhua** [comment]
i found the same bug 
![image](https://user-images.githubusercontent.com/31396902/125750155-86ce12a4-7fd0-4756-bf7d-da2c5accf12b.png)
the algorithmConfiguration have no value

**Comment by Keanhua** [comment]
![image](https://user-images.githubusercontent.com/31396902/125750787-91be76b7-6654-49bc-942b-9230ed618683.png)
the follow is here get wrong

**Comment by Keanhua** [comment]
@tristaZero can you help fix the bug?

**Comment by tristaZero** [comment]
@Keanhua Hi which release do you test?

**Comment by Keanhua** [comment]
@tristaZero 5.0.0-beta,thank u

**Comment by RaigorJiang** [comment]
Hi @Keanhua 
Can you provide a demo project on github? So that we can reproduce your scene.  Thank you!

**Comment by Keanhua** [comment]
@RaigorJiang this project you can see the bug. https://github.com/Keanhua/sharding-bug-demo

**Comment by RaigorJiang** [comment]
> @RaigorJiang this project you can see the bug. https://github.com/Keanhua/sharding-bug-demo

OK, I'll check it.

**Comment by RaigorJiang** [comment]
Hi @Keanhua 
I checked and tested your demo project, there are some problems:
1. Reder to [example](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/other-feature-example/encrypt-example/encrypt-spring-boot-example/src/main/resources/application-encrypt-databases.properties), `columns.column.encryptor` should be `columns.column.encryptor-name` now;
2. `encryptor-name` should not has underline in YAML configuration.
3. You can just replace your config file with example file, it should work well, so it's a configuration issue.

**Comment by Keanhua** [comment]
@RaigorJiang, encryptor_aes is my define encryptor-name. for the version 4.0.1,it can works well. 
i check it and i replace encryptor_aes to encryptor-aes, it also occurs error.
can you provide me a corrent yml file ?

**Comment by RaigorJiang** [comment]
@Keanhua   OK, I wll upload tonight.

**Comment by RaigorJiang** [comment]
Hi @Keanhua,
Please see this [commit](https://github.com/RaigorJiang/sharding-bug-demo/commit/500522b6e12c4f2fd3f50ae10ee140050c30fc43).
Because your sql file just has one table, so I delete other table configuration in the yaml.   You can add them as the same format.

**Comment by Keanhua** [comment]
@RaigorJiang ok,thank you very much

**Comment by Keanhua** [comment]
@RaigorJiang, i tried it , it works well,,thank you very much
