### ISSUE TITLE
broadcast-tables 

### ISSUE THREAD

**Issue by bankly** [apache/shardingsphere#10883]
Bug Report

version：shardingsphere-jdbc 5.0.0-alph

Configuration Spring boot starter broadcast-tables is invalid , but spring namespace is valid

spring.shardingsphere.rules.sharding.broadcast-tables=area

**Comment by strongduanmu** [comment]
@bankly Can you show more infomation?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
