### ISSUE TITLE
Add unit test for DatabasePrivileges of database authority module

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10888]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `DatabasePrivileges` to test its public functions.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Example FYI
- `PrivilegeMergeTest`

**Comment by zhujunxxxxx** [comment]
I want to try this issue. [OSD2021]

**Comment by tristaZero** [comment]
@zhujunxxxxx Hey, this is designated for newcomer, I'd like to assign you some senior tasks.

**Comment by SivaTharun** [comment]
@tristaZero can i work on this issue?

**Comment by tristaZero** [comment]
If you're interested in such issues, I recommend #10902 for you. @SivaTharun

**Comment by tristaZero** [comment]
@zhujunxxxxx Do you want to have a try with #10904?

**Comment by AbnerHung** [comment]
can i try this issue?

**Comment by tristaZero** [comment]
Hey @AbnerHung Welcome, it's yours now.
