### ISSUE TITLE
booting error with oracle 11g

### ISSUE THREAD

**Issue by xueshiji** [apache/shardingsphere#10896]
**Which version of ShardingSphere did you use?**
5.0.0-beta
**Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?**
ShardingSphere-JDBC
**Expected behavior**
Correct booting
**Actual behavior**
ORA-00904: "IDENTITY_COLUMN": Invalid identifier
**Reason analyze**
Oracle-11g's ALL_TAB_COLUMNS table does not have IDENTITY_COLUMN field.
![source](https://user-images.githubusercontent.com/32958628/122768785-84eeaa00-d2d6-11eb-8855-dd2a84a66f35.png)

**Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.**
N/A

**Comment by strongduanmu** [comment]
@xueshiji Thank you very much for using the `5.0.0-beta` version and reporting the problem. Are you interested in submitting a PR to fix this problem?
