### ISSUE TITLE
Suggestions on the example project

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10891]
## Suggestions on the example project

When using the example project, I found that some startup classes with different functions have the same name (ExampleMain).

It is not friendly for developers who use the example project to understand the corresponding functions,In the UI display in the IDE is not very recognizable.

At the same time, the jdbc_url link parameter configuration in the unified configuration file of all sample projects.

#### 1. Start class name 

Basic format: 

function + project nature + [configuration type] + end of Example

For example in the governance-example project:

```java 
JavaConfigurationExampleMain --> GovernanceRawJavaConfigurationExample
YamlConfigurationExampleMain --> GovernanceRawYamlConfigurationExample
ExampleMain --> GovernanceSpringBootExample
ExampleMain --> GovernanceSpringNamespaceExample
``` 

#### 2. Configuration file changed

Parameter jdbc_url request parameters are unified:

```shell
?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
```

**Comment by taojintianxia** [comment]
what I believe, is that make the demo / example as"stupid" as it could be.
no lambda, no abstraction, no design pattern, no programming skill show off .

to make the people who has less than 1 year Java experience could easily understand is the best.

**Comment by tristaZero** [comment]
Hi @soulasuna ,

Thanks for your first issue here. It looks fine with me, please go ahead. Also, you can give some consideration on @taojintianxia 's suggestion.
