### ISSUE TITLE
Add Unit test for StoragePrivilegeBuilder

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10904]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `StoragePrivilegeBuilder` to test its public functions.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Tips
- You can consider H2 database for test if you like.

### Example FYI
- `StoragePrivilegeBuilder`

**Comment by zhujunxxxxx** [comment]
I wan to try.

**Comment by zhujunxxxxx** [comment]
@tristaZero please assign to me

**Comment by tristaZero** [comment]
Assigned. @zhujunxxxxx
