### ISSUE TITLE
Improve AllPrivilegesPermittedAuthorityProviderAlgorithm and add UT

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10902]
Hi community,

This issue is for #10887.

### Aim
- Define AllPrivilegesPermittedShardingSpherePrivileges as a `final` class
- Add unit test for `AllPrivilegesPermittedAuthorityProviderAlgorithm` to test its public functions.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Example FYI
- `PrivilegeMergeTest`

**Comment by SivaTharun** [comment]
@tristaZero can i work on this issue?

**Comment by tristaZero** [comment]
Assigned to U.

**Comment by SivaTharun** [comment]
@tristaZero please review this [PR](https://github.com/apache/shardingsphere/pull/11152) for this issue
