### ISSUE TITLE
Refactor SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ORDER_BY statement with shardingsphere-integration-test

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10917]
Hi community,

This issue is for #10887.

# Background

Currently `FederateStatementTest` and `FederatePrepareStatementTest` use JUNIT to test SQL statements. In order to improve test coverage and code elegance, we need to migrate the test scenarios of FederateStatementTest and FederatePrepareStatementTest to `shardingsphere-integration-test`. 

# Target

The goal of this issue is to migrate the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ORDER_BY` statement to the `shardingsphere-integration-test` module. 

You can search for the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ORDER_BY` keyword, and then you will find the test cases in `FederateStatementTest` and `FederatePrepareStatementTest`.

FederateStatementTest:

```java
    private static final String SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ORDER_BY =
            "select t_order_federate.* from t_order_federate, t_order_item_federate_sharding "
                    + "where t_order_federate.order_id = t_order_item_federate_sharding.item_id "
                    + "ORDER BY t_order_item_federate_sharding.user_id";

    @Test
    public void assertQueryWithFederateInSingleAndShardingTableOrderByByExecuteQuery() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableOrderBy(true);   
    }
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableOrderByByExecute() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableOrderBy(false);
    }
    
    private void assertQueryWithFederateInSingleAndShardingTableOrderBy(final boolean executeQuery) throws SQLException {
        ShardingSphereStatement statement = (ShardingSphereStatement) getShardingSphereDataSource().getConnection().createStatement();
        ResultSet resultSet = getResultSet(statement, SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ORDER_BY, executeQuery);
        assertNotNull(resultSet);
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1000));
        assertThat(resultSet.getInt(2), is(10));
        assertThat(resultSet.getString(3), is("init"));
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1001));
        assertThat(resultSet.getInt(2), is(11));
        assertThat(resultSet.getString(3), is("init"));
        assertFalse(resultSet.next());
    }
```

# How to
In order to finish this task, you need to understand the [documentation](https://shardingsphere.apache.org/document/current/en/features/test-engine/integration-test/) of the integration test first, and PR #10913 also provides an example, which you can refer to. BTW, if you have any questions, please leave a comment.

**Comment by LeeGuoPing** [comment]
@strongduanmu finished
