### ISSUE TITLE
RangeShardingAlgorithm throws: Factory method 'shardingDataSource' threw exception; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by kushalhalder** [apache/shardingsphere#10912]
Factory method 'shardingDataSource' threw exception; nested exception is java.lang.NullPointerException
If default database strategy has been defined with range algorithm, it throws the above error. 

If I include precise with range, then only precise is picked up. 

What is wrong here?
```
spring.shardingsphere.sharding.default-database-strategy.standard.sharding-column=keyspaceID
spring.shardingsphere.sharding.default-table-strategy.none=
spring.shardingsphere.sharding.default-database-strategy.standard.range-algorithm-class-name=group.shardingsphere.algorithm.RangeShardingDatabaseAlgorithm
spring.shardingsphere.sharding.default-database-strategy.standard.precise-algorithm-class-name=group.shardingsphere.algorithm.PreciseModuloShardingDatabaseAlgorithm
```
I do not need Precise, just Range would do.

**Comment by tristaZero** [comment]
Hey, which version?

**Comment by kushalhalder** [comment]
Hey, thanks for getting back. I could fix it, not an issue from shardingsphere. Thanks again.
