### ISSUE TITLE
[Doc] Add English documentation for DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10928]
Hi, ShardingSphere 5.0.0-beta will be released soon, and DistSQL is an important feature, but I found that the English documentation of DistSQL is still in **'TODO'** status and needs to be added urgently. (Can be translated from the corresponding Chinese page)
The following is a list of document tasks that need to be processed, if anyone wants to help, please claim one(or some) of them.
**(Please notice: this is a high priority task)**

- [DistSQL](https://shardingsphere.apache.org/document/current/en/features/dist-sql/) // Exists
  - [ ] [Syntax](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/)  (@yx9o)
    - [ ] [RDL Syntax](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/) (@RaigorJiang )
      - [ ] [Data Source](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/rdl-resource/)
      - [ ] [Sharding](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/rdl-sharding-rule/)
      - [ ] [Readwritie-Splitting](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/rdl-readwrite-splitting-rule/)
      - [ ] [Encrypt](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/rdl-encrypt-rule/)
      - [ ] [DB Discovery](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rdl/rdl-db-discovery-rule/)
    - [ ] [RQL Syntax](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/) (@soulasuna)
      - [ ] [Data Source](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/rql-resource/)
      - [ ] [Sharding](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/rql-sharding-rule/)
      - [ ] [Readwritie-Splitting](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/rql-readwrite-splitting-rule/)
      - [ ] [Encrypt](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/rql-encrypt-rule/)
      - [ ] [Discovery](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/rql-db-discovery-rule/)
    - [ ] [SCTL Syntax](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/sctl/) (@yx9o)
      - [SCTL](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/sctl/sctl/) // Exists
  - [ ] [Usage](https://shardingsphere.apache.org/document/current/en/features/dist-sql/usage/)  (@RaigorJiang )
    - [ ] [Sharding](https://shardingsphere.apache.org/document/current/en/features/dist-sql/usage/sharding-rule/)

**Comment by RaigorJiang** [comment]
I'll fix `RDL Syntax` first.

**Comment by soulasuna** [comment]
I want to get involved

**Comment by soulasuna** [comment]
I want to do RQL Syntax

**Comment by RaigorJiang** [comment]
@soulasuna  Thanks for joining

**Comment by yx9o** [comment]
I can handle “syntax” and “SCTL Syntax”

**Comment by RaigorJiang** [comment]
@yx9o  Thank you

**Comment by RaigorJiang** [comment]
Fixes by #10939, #10945, #10946
