### ISSUE TITLE
about init  metadata of tables 

### ISSUE THREAD

**Issue by childewuque** [apache/shardingsphere#10938]
shardingsphere jdbc 5
springboot2.3

I have a project it uses only one logic table，but there are 10000 other tables  in the same db for other projects
When my project starting，shardingsphere jdbc will init all tables' metadata,then the process seem like "sleep"

Can I exclude other tables in my sharding project? 
Thanks

**Comment by terrymanu** [comment]
What is the actual version, 5 is never released yet

**Comment by childewuque** [comment]
> What is the actual version? 5 is never released yet

Master，downloaded on May 20

I find the method in ShardingRule.java:
    private Collection<String> getExcludedTables() {
        Collection<String> result = new HashSet<>(getTables());
        result.addAll(getAllActualTables());
        result.addAll(broadcastTables);
        return result;
    }

So I add all tables at actual-data-nodes for excluding other tables.

sample code:
tables:
          sharding_product:
            actual-data-nodes: sdb_$->{1..4}.fads_product_$->{['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']}$->{['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']},sdb_$->{1..4}.shop_product_$->{['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']}$->{['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']}      
............
very long...

Do you have more better suggestions for the case:
Only one table to shard in my project but there are too many other tables in the same db. 
Thanks.

**Comment by terrymanu** [comment]
The version 5.0.0-beta has already resolve this problem.

**Comment by childewuque** [comment]
> The version 5.0.0-beta has already resolved this problem.
Thanks
I try the version.

**Comment by childewuque** [comment]
I test and debug  the project by configging one logic table at  actual-data-nodes now,the 5.0.0-beta version problem still exists.

FederateSchemaMetadata.java 
 private void initTables(ShardingSphereMetaData metaData) throws SQLException {
        Collection<DataNodeContainedRule> dataNodeRules = this.getDataNodeContainedRules(metaData);
        Map<String, Collection<DataNode>> tableDataNodes = this.getTableDataNodes(dataNodeRules);
        Map<String, Collection<String>> dataSourceRules = this.getDataSourceRules(metaData);
        Iterator var5 = tableDataNodes.entrySet().iterator();     // blocked here

more ideas?
And may Shardingsphere-jdbc only init logic tables and broadcast?

**Comment by childewuque** [comment]
Another project has same problem,it uses 20 db ,every db has about 5000 tables.
Only 1 logic tables (256*20 actual tables) are used in the project.
Sometimes the project can start in 5~10 minutes,sometimes it is blocked.
max-connections-size-per-query=1000 now

**Comment by qiancheng8866** [comment]
same question,up+1!

**Comment by tuichenchuxin** [comment]
@childewuque @qiancheng8866 I had improved the performance about loading table meta data on master branch. Welcome to try to test master branch.

**Comment by strongduanmu** [comment]
Performance optimization has been completed, welcome to use the master branch test.

**Comment by childewuque** [comment]
@tuichenchuxin @strongduanmu 
I now use v5.0.0, and I find that the range of excluded tables is smaller than v5.0.0-beta, v5.0.0 only excludes getAllActualTables
Therefore, 5.0.0 initialized more tables metadata and the project started more slowly
In a database with many tables, only one table is used for sharding, and the other tables are not used by shardingsphere at all. How can the project be started more quickly?

Thanks.

SingleTableRule class:
    private Collection<String> getExcludedTables(final Collection<ShardingSphereRule> rules) {
        return rules.stream().filter(each -> each instanceof DataNodeContainedRule).flatMap(each -> ((DataNodeContainedRule) each).getAllTables().stream()).collect(Collectors.toSet());
    }

**Comment by tuichenchuxin** [comment]
@childewuque Can you help to position the code which is slow?

**Comment by childewuque** [comment]
> @childewuque Can you help to position the code which is slow?

Thanks for the quick response!
1.There are  about 6000 tables in every DB. But only one logic table named prod_score is sharded in my project.
2.actualDataNodes: dataSource$->{1..4}.prod_score_$->{(Integer.toHexString(0)..Integer.toHexString(255)).collect{t ->t.padLeft(2,'0')}}
3.The slowest point is the line in SingleTableMetaDataBuilder.load() --line 51：
     Collection<TableMetaDataLoaderMaterial> tableMetaDataLoaderMaterials = TableMetaDataUtil.getTableMetaDataLoadMaterial(needLoadTables, materials, false);
   Because  there are about 24000 tables in  Collection<String> needLoadTables.

Now my solution is that all tables are configed at actualDataNodes for exclude ,but it is toooooo long.

Thanks.

**Comment by childewuque** [comment]
@tuichenchuxin  I don't know if it is possible to initialize only the sharding tables ...

**Comment by tuichenchuxin** [comment]
@childewuque 
> 3.The slowest point is the line in SingleTableMetaDataBuilder.load() --line 51：
Collection tableMetaDataLoaderMaterials = TableMetaDataUtil.getTableMetaDataLoadMaterial(needLoadTables, materials, false); 

This line is all memory operations, It shouldn't be so slow. I'll check it.
>Now my solution is that all tables are configed at actualDataNodes for exclude ,but it is toooooo long.

This way may not work. Is it worked?

>lazy load may be a good idea, we'll consider it, but for now, may not skip.

**Comment by childewuque** [comment]
> 
It seems there are some loops on  tableNames/singleTableDataNodes   , and tableNames or singleTableDataNodes has 24k elements,  so it's slow.
E.g :
org.apache.shardingsphere.infra.metadata.schema.builder.util.TableMetaDataUtil line 51  
org.apache.shardingsphere.infra.datanode.DataNodes  line  55 

I exclude all tables  at actualDataNodes  then the project starts normally and works fine.
I don't know why shardingsphere will exclude the tables at actualDataNodes, but my project only use one logic table,so all tabls of the db are configured at actualDataNodes, it seems no problem in theory.

**Comment by tuichenchuxin** [comment]
@childewuque Thank you for your feedback, I'll check it later. And are you willing to submit a pr to optimize this problem?

**Comment by childewuque** [comment]
Thanks! 
I want but I don't know the global purpose of all tables metadata.
So just for my case,if I can ,Maybe  I will add a  configuration item to decide initializing tables metadata.
haha

**Comment by tuichenchuxin** [comment]
@childewuque we have optimized multi tables load.
14000 singleTables load from 140s To 17s.
May be you can try again.
