### ISSUE TITLE
sharding-jdbc 4.1.1 设置hint强制路由策略 只分库不分表 为何还有sql 不支持

### ISSUE THREAD

**Issue by monkeymada** [apache/shardingsphere#10933]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
采用shardingjdbc hint 强制路由策略，不是可以跳过 解析和改写阶段吗
### Actual behavior
执行关联更新报 sql 不支持 

org.apache.shardingsphere.underlying.common.exception.ShardingSphereException: Cannot support Multiple-Table for 'org.apache.shardingsphere.sql.parser.sql.statement.dml.UpdateStatement@1addadb9'.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/67772051/123041587-1883c000-d428-11eb-9f5f-2504fb53fe0c.png)

**Comment by strongduanmu** [comment]
@monkeymada For english only, other language will not be accept.
