### ISSUE TITLE
sharding-jdbc 4.1.1 使用hint 强制路由策略时 发现仍有些 sql 报错不支持

### ISSUE THREAD

**Issue by monkeymada** [apache/shardingsphere#10931]
## Question
sharding-jdbc 4.1.1 使用hint 强制路由策略时 发现仍有些 sql 报错不支持，不是使用hint强制路由可以跳过 sql 解析和改写吗 为什么还会报一些sql 不支持（例如两个表的关联更新）

**Comment by strongduanmu** [comment]
@monkeymada For english only, other language will not be accept.
