### ISSUE TITLE
Sharding-JDBC 4.1.1 sets the hint cast policy. Why is there still some SQL that does not support the hint cast policy

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#10940]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
Sharding-JDBC 4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
With the ShardingJDBC hint policy, the official website description can skip parsing and overwriting, but some SQL still does not support, such as multi-table association updates
### Actual behavior
![image](https://user-images.githubusercontent.com/67772051/123067043-36125300-d443-11eb-971d-67774b206704.png)

### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/67772051/123067072-3dd1f780-d443-11eb-8a25-a3d8fd64fe43.png)

**Comment by strongduanmu** [comment]
@monkeymada Hint provides a way to specify the sharding value from outside, user does not need to specify the sharding value in SQL, except for this, it is no different from other routing algorithms. The logic of parsing, verification, and routing will be executed normally.

**Comment by Yule-Momoko** [comment]
Nested subqueries, such as:  select count(*) from (select * from t_order d) c
![image](https://user-images.githubusercontent.com/67772051/123358068-5b1ad900-d59d-11eb-8942-e1755ee965b0.png)

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
