### ISSUE TITLE
4.1.1 version ，Project upgrade SQL report error

### ISSUE THREAD

**Issue by shenyao2333** [apache/shardingsphere#10955]
When I want from an old project integrated Sharding, found that there are some SQL query is not supported, and errors in some strange, such as: 
- Java. Lang. ClassCastException:java.lang.String cannot be cast to java.lang.Integer
-  Error querying database.  Cause: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
- Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 0
and so on.....

Some of the SQL error is a temporary table, anyway, a lot of complex SQL problems, this aspect can now have other ways to solve it?For example, forcing the data source to be specified so as to skip the parsing of the SQL, since this is an old project, this SQL is a bit errorless, so it is difficult to modify the SQL.Is there any good solution to this BUG?

I put an incorrect SQL
```
SELECT
	game.strength,
	game.game_id,
	game.member_id,
	game.crated_time,
	m.nickname,
	m.headimg 
FROM
	( SELECT strength, game_id, member_id, crated_time FROM club_sugar_game GROUP BY member_id, game_id ORDER BY strength DESC ) game
	LEFT JOIN member m ON game.member_id = m.id 
GROUP BY
	game.member_id 
ORDER BY
	strength DESC,
	game_id ASC 
```
![image](https://user-images.githubusercontent.com/49504066/123197884-c94c9680-d4de-11eb-93d0-77ab829ae203.png)

**Comment by trycache0828** [comment]
Your SQL statement needs to be rewritten.All Subquery SQL statement  must carry fragment field.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
