### ISSUE TITLE
Add unit test for ComposeClassStaticMethodAroundAdvice and ComposeConstructorAdvice

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#10958]
Hi community,

This issue is for #10887.

# Aim

Add unit test for ComposeClassStaticMethodAroundAdvice and ComposeConstructorAdvice to test its public functions.

- [ ] ComposeClassStaticMethodAroundAdvice
- [ ] ComposeConstructorAdvice

# Basic Qualifications
- Java
- Maven
- Junit.Test

# Example FYI

  - `PrivilegeMergeTest `

**Comment by Swastyy** [comment]
@taojintianxia I think this is a part of #11156

**Comment by tristaZero** [comment]
Hi @Swastyy So do you want to take charge of this one?

**Comment by Swastyy** [comment]
> Hi @Swastyy So do you want to take charge of this one?

Yes I am working on it.

**Comment by tristaZero** [comment]
@Swastyy Hi I am cleaning stale issues, are you still interested in working on it?

**Comment by Swastyy** [comment]
> @Swastyy Hi I am cleaning stale issues, are you still interested in working on it?

Hey @tristaZero I need some time to resolve some errors, if you want to recreate this issue, we can do this.

**Comment by tristaZero** [comment]
@taojintianxia Hi, we still need to fix this issue, don't we?
