### ISSUE TITLE
Add unit test for shardingsphere-db-discovery

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10963]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-db-discovery project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [ ] DatabaseDiscoveryRuleLexer
- [ ] DatabaseDiscoveryRuleParser
- [ ] DatabaseDiscoveryRuleSQLStatementVisitor
- [ ] DatabaseDiscoveryRuleSQLStatementParserFacade
- [ ] MGRHeartbeatJob

## Examples FYI
- DatabaseDiscoveryRuleStatementParserEngineTest
- MGRDatabaseDiscoveryTypeTest

**Comment by Orliucase** [comment]
@i will solve it@

**Comment by Orliucase** [comment]
Could you assign me this issue?

**Comment by tristaZero** [comment]
Hey @soulasuna welcome.
[How to raise a PR](https://shardingsphere.apache.org/community/cn/contribute/contributor/) is for U.

**Comment by Orliucase** [comment]
sorry,the issue is a bit difficult for me at the moment, I can not do it

**Comment by tristaZero** [comment]
@Orliucase Alright, thanks. We'd like to welcome others.
