### ISSUE TITLE
Add unit test for shardingsphere-governance

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10969]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-governance project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [ ] GovernanceExecuteProcessReporter

## Examples FYI
- GovernanceTransactionContextsTest

**Comment by SriSatyaT** [comment]
Can I work on this issue?

**Comment by strongduanmu** [comment]
@SriSatyaT Welcome.

**Comment by SriSatyaT** [comment]
@strongduanmu Thank you.

**Comment by menghaoranss** [comment]
@SriSatyaT  this issue has been fixed [#12997](https://github.com/apache/shardingsphere/pull/12997) by other contributor, I will close this issue now, thanks for your feedback and look forward to seeing you here again.
