### ISSUE TITLE
Sharding-JDBC 5.0.0-alpha configuration error 

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#10962]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Refer to the official documentation configuration but always report an error:
Caused by: org.apache.shardingsphere.infra.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `CLASS_BASED`.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

#sharding-jdbc
#spring.shardingsphere.datasource.names=ds1,ds2
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.common.username=admin
spring.shardingsphere.datasource.common.password=123456

spring.shardingsphere.datasource.ds1.jdbc-url=jdbc:mysql://localhost:3306/my_sql?serverTimezone=UTC&useSSL=false
spring.shardingsphere.datasource.ds2.jdbc-url=jdbc:mysql://localhost:3306/my_sql?serverTimezone=UTC&useSSL=false

# 用于Hint 的分片策略
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds${1..2}.t_order

spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.hint.hint-test.sharding-algorithm-name=hint-test

spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.type=CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.strategy=HINT
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.algorithmClassName=com.shardingjdbc.test.DatabaseHintShardingKeyAlgorithm

**Comment by RaigorJiang** [comment]
Hi @monkeymada 
ShardingSphere 5.0.0-alpha was released at 2020-11-13, but class based sharding algorithm was merged at 2020-12-07
in https://github.com/apache/shardingsphere/pull/8508.
So please try the latest version 5.0.0-beta, thank you.
