### ISSUE TITLE
Add unit test for shardingsphere-encrypt

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10964]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-encrypt project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [ ] EncryptConditionEngine
- [ ] EncryptSQLRewriteContextDecorator
- [ ] EncryptAssignmentParameterRewriter
- [ ] EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter
- [ ] EncryptInsertValueParameterRewriter
- [ ] EncryptPredicateParameterRewriter
- [x] EncryptParameterRewriterBuilder
- [ ] AssistQueryAndPlainInsertColumnsTokenGenerator
- [x] EncryptAlterTableTokenGenerator
- [ ] EncryptAssignmentTokenGenerator
- [x] EncryptCreateTableTokenGenerator
- [ ] EncryptForUseDefaultInsertColumnsTokenGenerator
- [ ] EncryptInsertOnUpdateTokenGenerator
- [ ] EncryptInsertValuesTokenGenerator
- [ ] EncryptPredicateColumnTokenGenerator
- [ ] EncryptPredicateRightValueTokenGenerator
- [x] EncryptProjectionTokenGenerator
- [ ] InsertCipherNameTokenGenerator
- [x] EncryptTokenGenerateBuilder

## Examples FYI
- EncryptInConditionTest
- EncryptSQLRewriteContextDecorator

**Comment by jasaroya** [comment]
Hi, I'd like to take on this issue.

**Comment by tristaZero** [comment]
Hi @jasaroya How is it going? ;-)

**Comment by tristaZero** [comment]
@jasaroya Any issues there, please be free to let us know.

**Comment by clbigdata** [comment]
I want to solve this issue

**Comment by Franco-H** [comment]
Hi. Has this issue been resolved? or is it still in progress? I have completed the tests for this issue for my school project and would like to make a PR if it is okay.

**Comment by jasaroya** [comment]
@Franco-H It's in progress. This was my issue for Open Source Day, so I would like the chance to complete it.

**Comment by menghaoranss** [comment]
@jasaroya We can communicate the progress of the task here at any time

**Comment by susongyan** [comment]
may i take part of tasks ?  @jasaroya @tristaZero

**Comment by strongduanmu** [comment]
@susongyan Of course, you can declare subtasks that you want to accomplish.

**Comment by susongyan** [comment]
> @susongyan Of course, you can declare subtasks that you want to accomplish.

i'd like to try rewriters first, many thanks 

- [ ]  EncryptAssignmentParameterRewriter
- [ ]  EncryptInsertOnDuplicateKeyUpdateValueParameterRewriter
- [ ]  EncryptInsertValueParameterRewriter
- [ ]  EncryptPredicateParameterRewriter

**Comment by LingyaoLv** [comment]
Hi @jasaroya 
Would you still like to contribute and resolve this issue?
Please share a status update with the community, thank you.

**Comment by menghaoranss** [comment]
@jasaroya @susongyan @LingyaoLv hi guys, this issue has been here for a long time, and the OSD 2021 is over, I just close this issue now, and move the remaining tasks to other issues, thanks for your attention.
