### ISSUE TITLE
Add unit test for shardingsphere-db-protocol-postgresql

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10960]
Hi community,

This issue is for #10887.

## Aim
Add unit test for 
shardingsphere-db-protocol-postgresql
project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
- [ ] PostgreSQLComBindPacket

## Examples FYI
- PostgreSQLComBindPacketTest

**Comment by takuya1981** [comment]
Can I  try it?

**Comment by strongduanmu** [comment]
> Can I try it?

@takuya1981 Welcome.

**Comment by tristaZero** [comment]
Hi @takuya1981 [How to raise a PR](https://shardingsphere.apache.org/community/en/contribute/contributor/) FYI.

**Comment by takuya1981** [comment]
@strongduanmu , @tristaZero , Thanks.

**Comment by takuya1981** [comment]
I'd like to confirm something. Which class is needed to be tested in this ticket? I mean  PostgreSQLComBindPacket is already tested in PostgreSQLComBindPacketTest.

**Comment by tristaZero** [comment]
@takuya1981 Sorry for my late response.

**Comment by soulasuna** [comment]
@takuya1981 Thank you very much for your attention. PostgreSQLComBindPacket is already tested in PostgreSQLComBindPacketTest. You can see #10887. Pick a task that interests you.
