### ISSUE TITLE
Add unit test for shardingsphere-readwrite-splitting

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10965]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-readwrite-splitting project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [ ] ReadwriteSplittingRuleStatementConverter

## Examples FYI
- YamlRootRuleConfigurationsForYamlReadwriteSplittingRuleConfigurationTest

**Comment by sizzlecar** [comment]
Let me try

**Comment by strongduanmu** [comment]
@sizzlecar Welcome, you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.
