### ISSUE TITLE
[Doc] Optimize change history of ShardingSphere-JDBC Java API (English)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10976]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972 

### Aim

Optimize change history of ShardingSphere-JDBC Java API (English version). 

### How to

1. Migrate `Java API` change history from
   `4.1.2.Configuration Manual`->`Java API`->`Change History` to
   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Java API`;
2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.
3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Java API change history](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/java-api/change-history/)

**Comment by Swastyy** [comment]
@tristaZero assign me this issue.
