### ISSUE TITLE
Add unit test for shardingsphere-infra-authority

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10970]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-infra-authority project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes

Add unit test for classes to test its public functions.

- [x] AuthorityChecker
- [x] StoragePrivilegeBuilder
- [x] NativeAuthorityProviderAlgorithm
- [x] AuthorityRuleBuilder
- [x] DefaultAuthorityRuleConfigurationBuilder
- [ ] AuthorityRule
- [x] AuthorityRuleConfigurationYamlSwapper

## Examples FYI
- MySQLPrivilegeHandlerTest

**Comment by songyuequan** [comment]
please assign it to me

**Comment by strongduanmu** [comment]
@songyuequan Welcome.

**Comment by menghaoranss** [comment]
@songyuequan I will move this issue to the next version, you can still try to solve this issue later.

**Comment by songyuequan** [comment]
I will start soon

**Comment by Franco-H** [comment]
> I will start soon

Hi songyuequan. Just let you know I am also working on this issue for my school project. Im 99.9% done. Just need to fix some checkstyle issues.

**Comment by songyuequan** [comment]
> > I will start soon
> 
> Hi songyuequan. Just let you know I am also working on this issue for my school project. Im 99.9% done. Just need to fix some checkstyle issues.

Ok, thank you for your Help. And you can do it all.

**Comment by LingyaoLv** [comment]
Hi @songyuequan 
Would you still like to contribute and resolve this issue?
Please share a status update with the community, thank you.

**Comment by menghaoranss** [comment]
@LingyaoLv @songyuequan this issue has been here for a long time, most of them has been resolved, I will close this issue and move the left tasks to another issue. Thanks for your attention. If you want to continue contributing, you can follow the issue board.
