### ISSUE TITLE
Add unit test for shardingsphere-infra-datetime

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10978]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-infra-datetime project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] DatabaseDatetimeService
- [ ] TimeServiceFactory
- [ ] TimeServiceConfiguration

## Examples FYI
- TimeServiceConfigurationTest

**Comment by jackding79** [comment]
can assign to me?

**Comment by strongduanmu** [comment]
@jackding79 Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.

**Comment by SriSatyaT** [comment]
Can I work on this issue?
