### ISSUE TITLE
Optimize API  change history documentation

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10972]
### Background

At present, the API change history of ShardingSphere-JDBC is distributed in different chapters of the user manual, including:

- 4.1.2. `Configuration Manual`-> `Java API` ->`Change History`
- 4.1.2. `Configuration Manual` -> `YAML Configuration` -> `Change History`
- 4.1.2. `Configuration Manual` -> `Spring Boot Starter Configuration` -> `Change History`
- 4.1.2. `Configuration Manual` -> `Spring Namespace Configuration` -> `Change History`

Is is not convenient for users to find, and it is not conducive to unified maintenance.

### Aim

Migrate the above `change history` to another chapter and make the following adjustments:

1. Modify the `7.FAQ` in the document to `7.Others`, the original `FAQ` chapter is sunk to `7.1.FAQ`;
2. Add directory `7.2.API Change History`;
3. Migrate the API change history from the `4.User Manual` to the newly added `7.2.API Change History` directory, and check whether the content of the document is correct during the process;
4. Add configuration change history of the ShardingSphere-Proxy;
5. unify terminologies, such as `Replica query` and `Readwrite split`,  should be changed to `Readwrite splitting`.

The adjusted directory level is as follows:

```
├── 6.Downloads
└── 7.Others
    ├── 7.1.FAQ
    └── 7.2.API Change History
    	├── 7.2.1.ShardingSphere-JDBC
        │   ├── Java API
        │   ├── YAML Configuration
        │   ├── Spring Boot Starter Configuration
        │   └── Spring Namespace Configuration
        ├── 7.2.2.ShardingSphere-Proxy
        ...
```

**Notice: ShardingSphere documentation contains English and Chinese versions, which will be processed separately.**

Current issue is an overview of the requirement,  tasks will be published in the related issues.

**Comment by soumyac19** [comment]
Hi, I would like to work on this issue. 

> ### Background
> At present, the API change history of ShardingSphere-JDBC is distributed in different chapters of the user manual, including:
> 
> * 4.1.2. `Configuration Manual`-> `Java API` ->`Change History`
> * 4.1.2. `Configuration Manual` -> `YAML Configuration` -> `Change History`
> * 4.1.2. `Configuration Manual` -> `Spring Boot Starter Configuration` -> `Change History`
> * 4.1.2. `Configuration Manual` -> `Spring Namespace Configuration` -> `Change History`
> 
> Is is not convenient for users to find, and it is not conducive to unified maintenance.
> 
> ### Aim
> Migrate the above `change history` to another chapter and make the following adjustments:
> 
> 1. Modify the `7.FAQ` in the document to `7.Others`, the original `FAQ` chapter is sunk to `7.1.FAQ`;
> 2. Add directory `7.2.API Change History`;
> 3. Migrate the API change history from the `4.User Manual` to the newly added `7.2.API Change History` directory, and check whether the content of the document is correct during the process;
> 4. Add configuration change history of the ShardingSphere-Proxy;
> 5. unify terminologies, such as `Replica query` and `Readwrite split`,  should be changed to `Readwrite splitting`.
> 
> The adjusted directory level is as follows:
> 
> ```
> ├── 6.Downloads
> └── 7.Others
>     ├── 7.1.FAQ
>     └── 7.2.API Change History
>     	├── 7.2.1.ShardingSphere-JDBC
>         │   ├── Java API
>         │   ├── YAML Configuration
>         │   ├── Spring Boot Starter Configuration
>         │   └── Spring Namespace Configuration
>         ├── 7.2.2.ShardingSphere-Proxy
>         ...
> ```
> 
> **Notice: ShardingSphere documentation contains English and Chinese versions, which will be processed separately.**
> 
> Current issue is an overview of the requirement, tasks will be published in the related issues.

**Comment by strongduanmu** [comment]
@soumyac19 Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.

**Comment by RaigorJiang** [comment]
done.
