### ISSUE TITLE
[Doc] Adjust Others and FAQ chapters

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10974]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Add `Others` chapter and adjust the `FAQ` , `Change History` chapters.

### How to

1. Modify the `7.FAQ` in the document to `7.Others`, the original `FAQ` chapter is sunk to `7.1.FAQ`;

2. Add directory `7.2.API Change History`;

3. Add directory `7.2.1.ShardingSphere-JDBC`;

4. Create `_index.en.md` and `_index.cn.md`, write some descriptions for the directory;

   (If you are not familiar with Chinese, please mark `_index.cn.md` as `TODO`)

**Comment by strongduanmu** [comment]
@harshita19244 This issue is also assigned to you.

**Comment by RaigorJiang** [comment]
#TODO Chinese content needs to be supplemented by new PR.

**Comment by RaigorJiang** [comment]
Chinese content fixed by https://github.com/apache/shardingsphere/pull/11405.
