### ISSUE TITLE
Add unit test for shardingsphere-infra-common

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10973]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-infra-common project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [x] DataSourceNameAwareFactory
- [x] DataSourceValidator
- [x] LockNameUtil
- [x] CreateUserStatementEventMapper
- [x] GrantStatementEventMapper
- [x] SQLStatementEventMapperFactory
- [x] ShardingSphereUsers
- [x] TransactionHolder

## Examples FYI
- ShardingSphereRulesBuilderTest

**Comment by fwhdzh** [comment]
Hello, I want to try this issue.
