### ISSUE TITLE
simplify sql parse when only use read-write-splitting

### ISSUE THREAD

**Issue by lyennon** [apache/shardingsphere#10975]
when only use read-write-splitting, we don't need parse the whole syntax tree .it's enougth you know it's  reade or write operation. so that it can support more kind of sql.

**Comment by tristaZero** [comment]
If you just target at `read-write-splitting`, it indeed. But, we still have to consider other scenarios. I wonder the current solution has any major negative impact on your case?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
