### ISSUE TITLE
[Doc] Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration (English)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10985]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration. (English version). 

### How to

1. Migrate `Spring Namespace Configuration` change history from

   `4.1.2.Configuration Manual`->`Spring Namespace Configuration`->`Change History` to

   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Spring Namespace Configuration`;

2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.

3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Spring Namespace Configuration change history](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/spring-namespace/change-history/)

**Comment by harshita19244** [comment]
Could you assign me this issue?

**Comment by tristaZero** [comment]
Hi @harshita19244  welcome here.

If you have any questions, @RaigorJiang , community mentor, is glad to provide any help.

**Comment by harshita19244** [comment]
#10972 could you assign this too? To modify `7.FAQ` to `7.others`, I need to start there

**Comment by RaigorJiang** [comment]
> #10972 could you assign this too? To modify `7.FAQ` to `7.others`, I need to start there

Hi, it may be #10974, but not #10972  :)   
@tristaZero Please help to assign, thanks.

**Comment by strongduanmu** [comment]
> #10972 could you assign this too? To modify `7.FAQ` to `7.others`, I need to start there

@harshita19244 Can you comment on issue #10972.

**Comment by harshita19244** [comment]
@RaigorJiang when I modify the website docs and execute the build.sh, the latest build does not show up my changes. I do have Hugo installed locally

**Comment by Swastyy** [comment]
Hi @RaigorJiang Please assign this issue to me if not completed.

**Comment by RaigorJiang** [comment]
Thank you @Swastyy .
