### ISSUE TITLE
Add unit test for shardingsphere-sql-parser-statement

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10988]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-sql-parser-statement project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] ColumnExtractor
- [ ] ExpressionBuilder
- [ ] SubqueryExtractUtil
- [ ] WhereExtractUtil

## Examples FYI
- SQLUtilTest

**Comment by yinyanghuafa** [comment]
please let me try.

**Comment by iamkyu** [comment]
Let me work

**Comment by tristaZero** [comment]
@iamkyu Hey see you again here.
