### ISSUE TITLE
Add unit test for shardingsphere-infra-route

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10987]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-infra-route project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] AllSQLRouteExecutor

## Examples FYI
- SQLRouteEngineTest

**Comment by takuya1981** [comment]
Hello, Can I try this ticket?

**Comment by strongduanmu** [comment]
@takuya1981 Of course, and you refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribute.
