### ISSUE TITLE
[Doc] Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration (Chinese)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10986]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration. (Chinese version). 

### How to

1. Migrate `Spring Namespace Configuration` change history from

   `4.1.2.Configuration Manual`->`Spring Namespace Configuration`->`Change History` to

   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Spring Namespace Configuration`;

2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.

3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Spring Namespace Configuration change history](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-namespace/change-history/)

**Comment by sydgeek** [comment]
Please assign it to me.

**Comment by menghaoranss** [comment]
> Please assign it to me.

Welcome.

**Comment by sydgeek** [comment]
There has a problem in this document.

- The following 2 namespaces in the document are inaccessible:
    http://shardingsphere.apache.org/schema/shardingsphere/readwrite-splitting/readwrite-splitting-5.0.0.xsd
    http://shardingsphere.apache.org/schema/shardingsphere/governance/governance-5.0.0.xsd

It seems that the directory /governance and /read write-splitting does not exist in the index of /schema/shardingsphere,
needs additional repair.

**Comment by RaigorJiang** [comment]
@sydgeek  Thanks for your carefulness, are you interested in fixing these problems?

**Comment by sydgeek** [comment]
@RaigorJiang Certainly, I can find these config files from projects, but I don't know how to add online namespaces.
Could you help me?

**Comment by RaigorJiang** [comment]
> There has a problem in this document.
> 
> * The following 2 namespaces in the document are inaccessible:
>   http://shardingsphere.apache.org/schema/shardingsphere/readwrite-splitting/readwrite-splitting-5.0.0.xsd
>   http://shardingsphere.apache.org/schema/shardingsphere/governance/governance-5.0.0.xsd
> 
> It seems that the directory /governance and /read write-splitting does not exist in the index of /schema/shardingsphere,
> needs additional repair.

@sydgeek 
I found the cause of the problem, our file has been renamed, but the directory of the online schema has not changed its name:  
https://shardingsphere.apache.org/schema/shardingsphere/
@taojintianxia   Could you help?

**Comment by sydgeek** [comment]
@RaigorJiang Ok, got it.
