### ISSUE TITLE
Add unit test for shardingsphere-infra-optimize

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10984]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-infra-optimize project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] CreateTableStatementFederateRefresher

## Examples FYI
- DropTableStatementFederateRefresherTest

**Comment by PallaviRoy** [comment]
Hi, I want to work on this issue
