### ISSUE TITLE
[Doc] add configuration change history of ShardingSphere-Proxy. (English)

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#10990]
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

add  configuration change history of ShardingSphere-Proxy (English version). 

### How to

1. Add  `7.2.2.ShardingSphere-Proxy` in the `7.2.API Change History` directory;
2. create file `_index.en.md` and write the configuration change history of proxy's `server.yaml`.

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [ShardingSphere-Proxy Configuration Manual](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/configuration/)

**Comment by Swastyy** [comment]
@RaigorJiang I want to work on this. Please assign it to me.

**Comment by strongduanmu** [comment]
@Swastyy Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.

**Comment by Swastyy** [comment]
@strongduanmu please see #11383 to have others folder and getting started with this issue.

**Comment by RaigorJiang** [comment]
The PR https://github.com/apache/shardingsphere/pull/11383  is not for this issue, please reopen it (#10990), thanks!

**Comment by Swastyy** [comment]
> The PR #11383 is not for this issue, please reopen it (#10990), thanks!

Yeah, I will make a PR for this issue.
