### ISSUE TITLE
java.util.NoSuchElementException: No value bound

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#10999]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
hint configuration
### Reason analyze (If you can)
Confirm this configuration error：

spring.shardingsphere.rules.tables.t_order.actual-data-nodes=ds${1..2}.t_order
spring.shardingsphere.rules.tables.t_order.database-strategy.hint-test.sharding-algorithm-name=hint-test
spring.shardingsphere.rules.sharding-algorithms.hint-test.type=HINT-TEST

**Comment by RaigorJiang** [comment]
Hi @monkeymada  
Is this issue relted to #10962 ?

**Comment by monkeymada** [comment]
Not relevant, I'm following this example:
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/other-feature-example/hint-example

**Comment by RaigorJiang** [comment]
OK, the configuration and exception information you provided is too brief, can you provide more complete information?

**Comment by yuzhiping** [comment]
I also encountered the same problem，I'm following this example:
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example 

spring boot  version is 2.4.0

detail shardingsphere config as follow:

![image](https://user-images.githubusercontent.com/10362461/131218586-590e78f9-4167-41c4-9f10-b669ab18c9df.png)


when i  start my program,detail error as follow:

![image](https://user-images.githubusercontent.com/10362461/131218614-e4ecee93-7f23-4f1f-a14a-9e8baf5af3a7.png)

**Comment by yuzhiping** [comment]
@Yule-Momoko  I ran into the same problem last week，and  just upgrade version to  `5.0.0-beta`

**Comment by RaigorJiang** [comment]
Hi @yuzhiping 
The scene used by @Yule-Momoko is hint, and your configuration is sharding inline, they are different.
And I will use your configuration to investigate.

**Comment by RaigorJiang** [comment]
Since @yuzhiping  deleted the configuration, the problem cannot be reproduced.
This issue will be closed, if there are related issues, please submit a new one.
