### ISSUE TITLE
Add unit test for shardingsphere-transaction-2pc

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10995]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-transaction-2pc project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [x] #11021

## Examples FYI
- MySQLXAConnectionWrapperTest

**Comment by sizzlecar** [comment]
Let me try

**Comment by soulasuna** [comment]
@sizzlecar 

> Let me try

welcome !!

**Comment by sizzlecar** [comment]
> @sizzlecar
> 
> > Let me try
> 
> welcome !!

Please assign me

**Comment by TeslaCN** [comment]
> > @sizzlecar
> > > Let me try
> > 
> > 
> > welcome !!
> 
> Please assign me

Assigned.

**Comment by sizzlecar** [comment]
> > > @sizzlecar
> > > > Let me try
> > > 
> > > 
> > > welcome !!
> > 
> > 
> > Please assign me
> 
> Assigned.

Hello, OracleXAConnectionWrapperTest already exists, which class should I add unit tests for?

**Comment by sizzlecar** [comment]
@soulasuna @strongduanmu Hello, OracleXAConnectionWrapperTest already exists, which class should I add unit tests for?

**Comment by soulasuna** [comment]
@sizzlecar  You can look at #10887, pick a task that interests you.
