### ISSUE TITLE
Add unit test for shardingsphere-transaction-core

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10993]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-transaction-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] ResourceDataSource

## Examples FYI
- ResourceIDGeneratorTest

**Comment by namitad** [comment]
would like to work on this issue. could this be assigned to me?

**Comment by strongduanmu** [comment]
> would like to work on this issue. could this be assigned to me?

@namitad Welcome, and assigned.
