### ISSUE TITLE
Add unit test for shardingsphere-sql-parser-engine

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#10992]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-sql-parser-engine project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] SQLParserEngine
- [ ] SQLVisitorEngine
- [ ] SQLParserFactory

## Examples FYI
- SQLParserEngineTest

**Comment by zzq1314zll** [comment]
Hi!  @strongduanmu  I want this issue to be my "virgin commit"

**Comment by strongduanmu** [comment]
@zzq1314zll Welcome to join the SS community.

**Comment by tristaZero** [comment]
@zzq1314zll aha, welcome, [How to raise a PR](https://shardingsphere.apache.org/community/cn/contribute/contributor/) for your virgin PR.

**Comment by zzq1314zll** [comment]
@tristaZero I have some questions, can you help me

**Comment by zzq1314zll** [comment]
![image](https://user-images.githubusercontent.com/33930711/124281712-93617f00-db7c-11eb-91e2-2b94c15e2dd9.png)
