### ISSUE TITLE
INFO： no viable alternative at input 'RANGE'

### ISSUE THREAD

**Issue by shijinting0321** [apache/shardingsphere#11007]
### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Execute SQL：
```sql
CREATE TABLE `cec_device_param_value_p3051403033191` (
	`id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '自增',
	`param_code` VARCHAR ( 32 ) NOT NULL COMMENT '参数code',
	`device_code` VARCHAR ( 32 ) NOT NULL COMMENT '设备code',
	`value` VARCHAR ( 100 ) NOT NULL COMMENT '值',
	`acquisition_time` TIMESTAMP NOT NULL COMMENT '参数采集时间',
	`update_time` TIMESTAMP NOT NULL COMMENT '参数入库时间',
	PRIMARY KEY ( `id`, `acquisition_time` ) USING BTREE,
	KEY `acquisition_time` ( `acquisition_time` ) USING BTREE 
	) ENGINE = MyISAM AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8 
	PARTITION BY RANGE (UNIX_TIMESTAMP( acquisition_time )) (
	PARTITION `2021` VALUES LESS THAN ( UNIX_TIMESTAMP('2022-01-01 00:00:00')) ENGINE = MyISAM
	);
```
### Actual behavior
Failed to execute, output message：no viable alternative at input 'RANGE'

**Comment by strongduanmu** [comment]
@shijinting0321 Thanks for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment]
![image](https://user-images.githubusercontent.com/10829171/123386610-6d127100-d5c9-11eb-9289-84d904381733.png)

@shijinting0321 Is this a legal mysql statement?

**Comment by strongduanmu** [comment]
@shijinting0321 Hi, can you give a feedback?

**Comment by shijinting0321** [comment]
> @shijinting0321 Hi, can you give a feedback?
The SQL is correct in my code, but it was written wrong in issue,I have corrected it.

**Comment by shijinting0321** [comment]
> @shijinting0321 Hi, can you give a feedback?

This has been modified using Markdown

**Comment by strongduanmu** [comment]
> > @shijinting0321 Hi, can you give a feedback?
> 
> This has been modified using Markdown

@shijinting0321 I used the latest SQL you provided for testing, and found no exception when execute parsing.

![image](https://user-images.githubusercontent.com/10829171/123747464-92fb8680-d8e5-11eb-8915-62e9451f7512.png)

**Comment by shijinting0321** [comment]
> > > @shijinting0321 Hi, can you give a feedback?
> > 
> > 
> > This has been modified using Markdown
> 
> @shijinting0321 I used the latest SQL you provided for testing, and found no exception when execute parsing.
> 
> ![image](https://user-images.githubusercontent.com/10829171/123747464-92fb8680-d8e5-11eb-8915-62e9451f7512.png)

I will try to build a demo project to restore the problem

**Comment by strongduanmu** [comment]
@shijinting0321 Can you provide more infomation?

**Comment by strongduanmu** [comment]
Long time no response.
