### ISSUE TITLE
Proxy not support "explain performance" language on postgresql/opengauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11026]
### Is your feature request related to a problem?
no
### Describe the feature you would like.
in pg or opengauss, we support `explain performance $SQL` to analyze sql performance, but proxy not support , I wish proxy can support this feature;
![image](https://user-images.githubusercontent.com/12265143/123510182-b2f43580-d6ac-11eb-83bb-01305b76cc61.png)
see opengauss description: https://opengauss.org/en/docs/2.0.1/docs/Developerguide/overview-16.html

**Comment by tuichenchuxin** [comment]
@justbk2015 expalin performance is not supported by PG.
see https://www.postgresql.org/docs/13/sql-explain.html.
