### ISSUE TITLE
Wrong LIMIT [offset, row_count] rewrite SQL on openGuass

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11025]
### Which version of ShardingSphere did you use?
master / opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy
### Expected behavior
run `select * from tb_notdb_distable1 LIMIT 5,2;` can get actual result.
### Actual behavior
not query data return
### Reason analyze (If you can)
sql rewirte of limit not support from 5,2 to 7,0, the row_count at least is 1 on postgresql.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. config:
tables:
  tb_notdb_distable1:
     actualDataNodes: ds_1.tb_notdb_distable1_${0..2}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: tb_tb_notdb_distable_inline1
defaultDatabaseStrategy:
  none: null
defaultTableStrategy:
  none: null
shardingAlgorithms:
   tb_tb_notdb_distable_inline1:
     type: INLINE
     props:
       algorithm-expression: tb_notdb_distable1_${id % 3}
       allow-range-query-with-inline-sharding: true
--------
2. init table
create table tb_notdb_distable1(id int unique,name text,type int);
insert into tb_notdb_distable1 values(1,'test1',1),(2,'test2',1),(3,'test3',2),(4,'test4',2),(5,'test5',3),(6,'test6',3),(7,'test7',3),(8,'test8',3);
analyze tb_notdb_distable1 ;
--------
3. query/result
select * from tb_notdb_distable1 LIMIT 5;
select * from tb_notdb_distable1 LIMIT 5,2;--error result is empty, we except test4 and test1 record
![image](https://user-images.githubusercontent.com/12265143/123510058-f26e5200-d6ab-11eb-8fe7-6ec774bca330.png)
4. rewrite sql
![image](https://user-images.githubusercontent.com/12265143/123510102-2ba6c200-d6ac-11eb-8f1e-0c630cd01db2.png)

### Example codes for reproduce this issue (such as a github link).
see this descript: https://gitee.com/opengaussorg/dashboard?issue_id=I3XRVI

**Comment by strongduanmu** [comment]
@justbk2015 I refer to the official documentation of PG, this SQL seems to be illegal.

```
[ WITH [ RECURSIVE ] with_query [, ...] ]
SELECT [ ALL | DISTINCT [ ON ( expression [, ...] ) ] ]
    [ * | expression [ [ AS ] output_name ] [, ...] ]
    [ FROM from_item [, ...] ]
    [ WHERE condition ]
    [ GROUP BY grouping_element [, ...] ]
    [ HAVING condition ]
    [ WINDOW window_name AS ( window_definition ) [, ...] ]
    [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] select ]
    [ ORDER BY expression [ ASC | DESC | USING operator ] [ NULLS { FIRST | LAST } ] [, ...] ]
    [ LIMIT { count | ALL } ]
    [ OFFSET start [ ROW | ROWS ] ]
    [ FETCH { FIRST | NEXT } [ count ] { ROW | ROWS } ONLY ]
    [ FOR { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE } [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...] ]
```

The legal sql should be `select * from tb_notdb_distable1 LIMIT 5 OFFSET 2;`

**Comment by justbk2015** [comment]
@strongduanmu this sql language come from sharding-doc:
https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/sql/

SELECT select_expr [, select_expr ...] FROM table_reference [, table_reference ...]
[WHERE predicates]
[GROUP BY {col_name | position} [ASC | DESC], ...]
[ORDER BY {col_name | position} [ASC | DESC], ...]
[LIMIT {[offset,] row_count | row_count OFFSET offset}]
pg and og also support this sql on normal table, but error on sharding table!

**Comment by strongduanmu** [comment]
@justbk2015 The SQL in the official document is in MySQL dialect, please adjust the SQL according to the official PG document.

**Comment by justbk2015** [comment]
pg and og already support this dialect:

[ WITH [ RECURSIVE ] with_query [, ...] ]
SELECT [/*+ plan_hint */] [ ALL | DISTINCT [ ON ( expression [, ...] ) ] ]
{ * | {expression [ [ AS ] output_name ]} [, ...] }
[ FROM from_item [, ...] ]
[ WHERE condition ]
[ GROUP BY grouping_element [, ...] ]
[ HAVING condition [, ...] ]
[ WINDOW {window_name AS ( window_definition )} [, ...] ]
[ { UNION | INTERSECT | EXCEPT | MINUS } [ ALL | DISTINCT ] select ]
[ ORDER BY {expression [ [ ASC | DESC | USING operator ] | nlssort_expression_clause ] [ NULLS { FIRST | LAST } ]} [, ...] ]
[ LIMIT { [offset,] count | ALL } ]===========>look at here!
[ OFFSET start [ ROW | ROWS ] ]
[ FETCH { FIRST | NEXT } [ count ] { ROW | ROWS } ONLY ]
[ {FOR { UPDATE | SHARE } [ OF table_name [, ...] ] [ NOWAIT ]} [...] ];
-------------
my problem is our og support this dialect `limit 5,2` and result is right, but sharding-proxy is not correct implements this feature, may be this is a bug.

**Comment by strongduanmu** [comment]
@justbk2015 This is the dialect of openGuass, currently not supported, please adjust the SQL according to the standard PostgreSQL syntax
