### ISSUE TITLE
Add unit test for ExecuteProcessStrategyEvaluator

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#11031]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `ExecuteProcessStrategyEvaluator` to test its public functions.

### Basic Qualifications
* Java
* Maven
* Junit.Test

**Comment by PallaviRoy** [comment]
Hi, can I take this issue?

**Comment by strongduanmu** [comment]
@PallaviRoy Welcome.

**Comment by menghaoranss** [comment]
@PallaviRoy We can communicate the progress of the task here at any time.

**Comment by menghaoranss** [comment]
@PallaviRoy Thanks for your attention. OSD 2021 is over. I just close this issue now.
