### ISSUE TITLE
Add unit test for ProcessRegistrySubscriber

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#11033]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `ProcessRegistrySubscriber` to test its public functions.

### Basic Qualifications
* Java
* Maven
* Junit.Test

### Example FYI
* `RegistryCenterTest`

**Comment by tanu02** [comment]
Hi Team 
Can I assign this to myself?

**Comment by tristaZero** [comment]
Sure @tanu02 Welcome. ;-)

**Comment by tanu02** [comment]
Thank you @tristaZero 
Could you please review the PR: https://github.com/apache/shardingsphere/pull/11419

**Comment by tanu02** [comment]
There seems to be some issue with the license. Has this ever occurred before? 
https://travis-ci.org/github/apache/shardingsphere/builds/774675252

**Comment by sandynz** [comment]
Hi @tanu02 , seems CI is not enabled currently, you could run `./mvnw -T 1C clean install` on local for now, make sure it can be compiled and tested successfully.
For more details, see [Code of Conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/).

**Comment by tanu02** [comment]
Got it. Seems like I had to add licence declaration in the file.  
Thank you!

**Comment by tanu02** [comment]
It is getting built on my local succesfully.  
https://github.com/apache/shardingsphere/pull/11419
Please review the PR.
