### ISSUE TITLE
Add unit test for ExecuteProcessEngine

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#11030]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `ExecuteProcessEngine` to test its public functions:
- Verify `EXECUTE_ID` could be put and removed correctly
- Verify `ExecuteProcessReporter.report` is invoked

### Basic Qualifications
* Java
* Maven
* Junit.Test

**Comment by fwhdzh** [comment]
Hello, I want to try this issue.

**Comment by strongduanmu** [comment]
@fwhdzh Welcome to join SS community.
