### ISSUE TITLE
11g or lower of oracle use 5.0.0-beta error

### ISSUE THREAD

**Issue by yuanhuyulin** [apache/shardingsphere#11046]
the Class OracleTableMetaDataLoader of module shardingshere-infra-common :
        **    private static final String TABLE_META_DATA_SQL = "SELECT OWNER AS TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IDENTITY_COLUMN %s FROM ALL_TAB_COLUMNS WHERE OWNER = ?";**

database not exists column IDENTITY_COLUMN , Then on start my project that used 5.0.0-beta must be error for "IDENTITY_COLUMN" not exists; on the last it can also error like **org.apache.shardingsphere.infra.exception.ShardingSphereException: `DUAL` single table does not exist.**

**Comment by avalon5666** [comment]
Can you set sql.show=true, and provider the configuration and full exception log?

**Comment by xueshiji** [comment]
@yuanhuyulin @terrymanu  It has been fixed in https://github.com/apache/shardingsphere/pull/10956

**Comment by strongduanmu** [comment]
Fixed by #10956.
