### ISSUE TITLE
Add ShardingSphereOptimizerTest to assert ShardingSphereOptimizer

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#11048]
Hi,

This issue is to add `ShardingSphereOptimizerTest` to assert whether `ShardingSphereOptimizer` can return the best physical executed plan.

This class is a kernel process to do SQL optimization. #10889 and #11042 make the optimizer levering ShardingSphere parser, but we need this test to confirm its basic function.

### Target
Create `ShardingSphereOptimizerTest`  to test its `optimize()` function

###  Tips
Create `TableMetaData` for `ShardingSphereMetaData` and utilize `OptimizeContextFactory` to create `OptimizeContext` for `ShardingSphereOptimizer`.

**Comment by tristaZero** [comment]
@wgy8283335 do you want to work on this one since you showed your interest in this feature.

**Comment by wgy8283335** [comment]
> @wgy8283335 do you want to work on this one since you showed your interest in this feature.

Sure, I'd like to take care of this issue.
