### ISSUE TITLE
select * from t_user where(id in (select id from t_machine))  not support

### ISSUE THREAD

**Issue by wenjunlichao1231** [apache/shardingsphere#11043]
select * from t_user where(id in (select id from t_machine)) 

When select * encounters a subquery, the query field will include the field of the table in the subquery, resulting in the field of the query does not exist, because the word is read in the table of the subquery.

**Comment by avalon5666** [comment]
Can you set sql.show=true, and provider the configuration and full exception log?

**Comment by wenjunlichao1231** [comment]
> Can you set sql.show=true, and provider the configuration and full exception log?

Thank you very much for your reply, the actual sql query statement is not rewritten, but when the result set is obtained, because the select * field to be queried includes the field in the subquery table, the array is out of bounds.The getColumnCount function includes the sum of the fields of the query table and the subquery table, resulting in a query error
![16151624852541_ pic_hd](https://user-images.githubusercontent.com/8392641/123722559-2b304600-d8bb-11eb-8992-fb9a80da8d09.jpg)

**Comment by avalon5666** [comment]
Pls  the configuration and full exception log, I can't find out which sql execute by ShardingSphere-Command-1 thread.

**Comment by wenjunlichao1231** [comment]
> Pls the configuration and full exception log, I can't find out which sql execute by ShardingSphere-Command-1 thread.

This is the error log thanks for your help [error.txt](https://github.com/apache/shardingsphere/files/6730053/error.txt)

**Comment by avalon5666** [comment]
This file does not contain the above exception stack.

**Comment by wenjunlichao1231** [comment]
> This file does not contain the above exception stack.

Please help me take a look again, thank you very much ,
![1624938462244](https://user-images.githubusercontent.com/8392641/123734426-e95dca80-d8cf-11eb-8d55-2fbb3572e151.jpg)
![1624938484953](https://user-images.githubusercontent.com/8392641/123734429-ebc02480-d8cf-11eb-80f3-d5a3118d3a17.jpg)

[error1.txt](https://github.com/apache/shardingsphere/files/6730506/error1.txt)

**Comment by avalon5666** [comment]
Which version do you use?

**Comment by wenjunlichao1231** [comment]
> Which version do you use?
> And provider t_user & t_machine configurations

5.0.0-alpha

**Comment by wenjunlichao1231** [comment]
> Which version do you use?
> And provider t_user & t_machine configurations

Please help me see 
[sql.zip](https://github.com/apache/shardingsphere/files/6730923/sql.zip)

**Comment by avalon5666** [comment]
shardingsphere table rule configuration

**Comment by wenjunlichao1231** [comment]
> shardingsphere table rule configuration

You can try a strategy that is not worthy of sensitive, and it won’t work without a strategy.

**Comment by avalon5666** [comment]
Pls provider shardingsphere table rule configuration. java api or yaml file or spring namespace and so on.

**Comment by wenjunlichao1231** [comment]
> Pls provider shardingsphere table rule configuration. java api or yaml file or spring namespace and so on.

[rule.txt](https://github.com/apache/shardingsphere/files/6731123/rule.txt)

**Comment by wenjunlichao1231** [comment]
> Pls provider shardingsphere table rule configuration. java api or yaml file or spring namespace and so on.

Hello, have you reproduced it now? This statement has nothing to do with the rule. Even if there is no rule, an error will occur, because it will be wrong to get the query field. The obtained query field contains the field of the table in the subquery

**Comment by avalon5666** [comment]
Pls try 5.0.0-beta

**Comment by wenjunlichao1231** [comment]
> Pls try 5.0.0-beta, I test work fine in 5.0.0-beta

I found another problem, I submitted a new issuer, can you please help me to check it out, [https://github.com/apache/shardingsphere/issues/11057](url)

**Comment by avalon5666** [comment]
Has this problem been solved?

**Comment by wenjunlichao1231** [comment]
> Has this problem been solved?

Because it is not convenient for us to upgrade to the latest version, The way I solve it now is as shown in the screenshot, I am not sure if there will be other problems
![6](https://user-images.githubusercontent.com/8392641/123783896-740eeb80-d909-11eb-8f35-016cde849b9c.png)

**Comment by avalon5666** [comment]
Recommand to upgrade.
