### ISSUE TITLE
sharding-jdbc 4.1.1 Processing result set report error

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11055]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingjdbc 4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Reason analyze (If you can)
select '' as my_colum from t_table
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/67772051/123757709-d4456380-d8f0-11eb-822d-ca0b37f68971.png)

**Comment by avalon5666** [comment]
Pls try with 5.0.0-beta.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
