### ISSUE TITLE
the result of the subquery is used as an alias, and the alias cannot find the corresponding table

### ISSUE THREAD

**Issue by wenjunlichao1231** [apache/shardingsphere#11057]
![4](https://user-images.githubusercontent.com/8392641/123782046-7a03cd00-d907-11eb-8916-afdbaf757f37.png)
<img width="1509" alt="2" src="https://user-images.githubusercontent.com/8392641/123782096-82f49e80-d907-11eb-8490-292211f4d49f.png">
<img width="1204" alt="1" src="https://user-images.githubusercontent.com/8392641/123782119-89831600-d907-11eb-9071-b24bc32f8b63.png">

**Comment by avalon5666** [comment]
5.0.0-beta fix many bug and improve sql compatibility, 4.1.1 is a historical version and will not be maintained, recommand upgrade rather than fix it.

**Comment by terrymanu** [comment]
The version before 5.x is out of service, I just close the issue.
