### ISSUE TITLE
这算是一个巨型bug吗

### ISSUE THREAD

**Issue by wtjperi2003** [apache/shardingsphere#11059]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0.beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
抛出异常
### Actual behavior
没有任何异常
### Reason analyze (If you can)
没看源码
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
很简单，库里一张表某个字段设成非空，然后在insert一条数据，非空字段不传值，正常要报异常，但是在5.0.0beta版本上，没有异常抛出，正常返回，只不过返回值是-1，我退回到4.1.1版本会抛异常

**Comment by avalon5666** [comment]
I tested as expected.
Is your test environment consistent? As far as I know mysql disable strict mode allow insert null to not null column, but the return value must correct.

**Comment by avalon5666** [comment]
By the way create issue in english.

**Comment by avalon5666** [comment]
Fixed by #10845, You can build from master and test again.

**Comment by avalon5666** [comment]
Duplicate with #11063
