### ISSUE TITLE
Sharding-Proxy Whether you need to care about unsupported SQL?

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11052]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
 Sharding-JDBC 4.1.1 There are a lot of unsupported SQL,Very upset. Sharding-Proxy  Whether there are no such problems

**Comment by avalon5666** [comment]
shardingsphere jdbc and proxy share sql parsing module.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
