### ISSUE TITLE
Can sharding-jdbc 5.0.0-Beta be used in production environment?

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11058]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
Can sharding-jdbc 5.0.0-Beta be used in production environment?  When will the official version be released?

**Comment by avalon5666** [comment]
This version fixes a lot of problems and improve sql compatibility compared with the 4.x

**Comment by Yule-Momoko** [comment]
But the Maven library doesn't seem to have this version

**Comment by avalon5666** [comment]
Look again, it's synchronized.

**Comment by Yule-Momoko** [comment]
<dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
                <version>5.0.0-beta</version>
            </dependency>

**Comment by avalon5666** [comment]
Oh, I will check this.

**Comment by avalon5666** [comment]
ArtifactId renamed.
```
<dependency>
  <groupId>org.apache.shardingsphere</groupId>
  <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
  <version>5.0.0-beta</version>
</dependency>
```

**Comment by Yule-Momoko** [comment]
ok thank you
