### ISSUE TITLE
What are the specific functions of proxy cluster management and what to pay attention to？

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#11054]
For example, dynamic adjustment of the number of physical library connections after scaling. No similar feature list?

**Comment by ddsr-ops** [comment]
Such as actual db connection pool monitor, slow sql alert, proxy HA.

**Comment by sandynz** [comment]
Hi @git-chenhao , when scaling job get done successfully, ShardingSphere will switch metadata (include `dataSources` and `rules`), and connection pool will be refreshed.

You could referto [ScalingRegistrySubscriber.clusterSwitchConfiguration]( https://github.com/apache/shardingsphere/blob/73846fd843cf695285b7951560825786a72d70f2/shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/cluster/coordinator/registry/cache/subscriber/ScalingRegistrySubscriber.java#L109 ) and [ContextManager.alterDataSourceConfiguration]( https://github.com/apache/shardingsphere/blob/6b7aa50f27a0e3d10a91ef7f2c0d0ac532aee566/shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/manager/ContextManager.java#L212 ) for more details.

**Comment by terrymanu** [comment]
This issue is opened for long time any no feedback, I just close it.
