### ISSUE TITLE
Can't throw SQLIntegrityConstraintViolationException:Duplicate entry "ID45_ID045_ba" for key "foo_45.id_id0_value"

### ISSUE THREAD

**Issue by chenqin091017** [apache/shardingsphere#11063]
### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core 5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
table foo, column id、id0 and value is a index,these type is unique。
![sql](https://user-images.githubusercontent.com/17311435/123812182-7469af80-d926-11eb-9876-aa9384e05a40.png)

Logic SQL：`insert into foo(id,id0,value) values(?,?,?)`
Actual SQL：`insert into foo_45(id,id0,value) values(?,?,?)`
`ID45_ID045_bar` exist in my database, insert same data can throw SQLException.
I checked data uniqueness using this unique_index.
### Actual behavior
can not throw SQLException
### Reason analyze (If you can)
![exception](https://user-images.githubusercontent.com/17311435/123810743-3b7d0b00-d925-11eb-87b5-4546d7bbe2c4.png)

**Comment by avalon5666** [comment]
I will check this.

**Comment by avalon5666** [comment]
Fixed by #10845, You can build from master and test again.
