### ISSUE TITLE
the package is missing when running the unit test at the latest master branch

### ISSUE THREAD

**Issue by xdshent** [apache/shardingsphere#11073]
## Bug Report
Hi community,

There is no package of `org.apache.shardingsphere.distsql.parser.autogen
` when I debug `shardingsphere-encrypt-core`'s test case at the latest master branch, as follow graph:

* latest commit id: e2e085ca8b906baba500c4e74cfaac81170b8ec4

<img width="1499" alt="package-missing" src="https://user-images.githubusercontent.com/16759505/123916796-a164a380-d9b4-11eb-89fd-0c8cc88ae6c7.png">

**Comment by TeslaCN** [comment]
Refer to https://shardingsphere.apache.org/document/current/en/faq/

**Comment by longhw** [comment]
> Refer to https://shardingsphere.apache.org/document/current/en/faq/

but when I execute under command to generate code，I still get error，why？please help me，thank you！
![image](https://user-images.githubusercontent.com/22389149/217998200-7b27a6c3-d868-4c7c-95e3-9eb8383e6ca5.png)
![image](https://user-images.githubusercontent.com/22389149/217998245-963a6064-c838-44d6-b4a8-606442df4b5c.png)

**Comment by TeslaCN** [comment]
> > Refer to https://shardingsphere.apache.org/document/current/en/faq/
> 
> but when I execute under command to generate code，I still get error，why？please help me，thank you！ ![image](https://user-images.githubusercontent.com/22389149/217998200-7b27a6c3-d868-4c7c-95e3-9eb8383e6ca5.png) ![image](https://user-images.githubusercontent.com/22389149/217998245-963a6064-c838-44d6-b4a8-606442df4b5c.png)

Since antlr was upgraded to 4.10.1 days ago, you will need Java 11 to compile latest master.

**Comment by longhw** [comment]
> > > Refer to https://shardingsphere.apache.org/document/current/en/faq/
> > 
> > 
> > but when I execute under command to generate code，I still get error，why？please help me，thank you！ ![image](https://user-images.githubusercontent.com/22389149/217998200-7b27a6c3-d868-4c7c-95e3-9eb8383e6ca5.png) ![image](https://user-images.githubusercontent.com/22389149/217998245-963a6064-c838-44d6-b4a8-606442df4b5c.png)
> 
> Since antlr was upgraded to 4.10.1 days ago, you will need Java 11 to compile latest master.

wo ca，got
