### ISSUE TITLE
Sharding JDBC 5.0.0-beta configuration error

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11085]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
The following configuration:

#sharding-jdbc
spring.shardingsphere.datasource.names=ds1,ds2
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds1.driver‐class‐name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds1.url=jdbc:127.0.0.1:3306/my_db?serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
spring.shardingsphere.datasource.ds1.username=admin
spring.shardingsphere.datasource.ds1.password=123

spring.shardingsphere.datasource.ds2.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds2.driver‐class‐name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds2.url=jdbc:127.0.0.1:3306/my_db?serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
spring.shardingsphere.datasource.ds2.username=admin
spring.shardingsphere.datasource.ds2.password=123

spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.hint.hint-test.sharding-algorithm-name=hint-test

spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.type= CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.strategy=HINT
spring.shardingsphere.rules.sharding.sharding-algorithms.hint-test.props.algorithmClassName=com.my.shardingjdbc.DatabaseHintShardingKeyAlgorithm

spring.shardingsphere.props.sql.show = true

### Actual behavior
The following error:
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 72 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendDialectRemainTables(SchemaBuilder.java:120)
	... 90 common frames omitted
Caused by: java.lang.NullPointerException: null

**Comment by zjcnb** [comment]
hi, I think you need to change the jdbc:127.0.0.1:3306 first
suck as : jdbc:mysql://127.0.0.1:3306

Please try it

**Comment by Yule-Momoko** [comment]
The problem is:
spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.hint.hint-test.sharding-algorithm-name=hint-test

**Comment by tristaZero** [comment]
Hi @Yule-Momoko any progress? From the log, it seems it has something to do with `metadata loading`. Could you provide more log?

**Comment by Yule-Momoko** [comment]
Hi @tristaZero
![image](https://user-images.githubusercontent.com/67772051/124404792-05011f00-dd6f-11eb-9353-5aa59d7f63a4.png)

**Comment by strongduanmu** [comment]
@Yule-Momoko Yes, the description of `sharding-algorithm-name` is repeated. Are you interested in submitting a PR for optimization?

**Comment by Yule-Momoko** [comment]
I don't know how to operate it

**Comment by strongduanmu** [comment]
> I don't know how to operate it

@Yule-Momoko You can refer this [doc](https://shardingsphere.apache.org/community/cn/contribute/contributor/).

**Comment by yx9o** [comment]
I'll do it.

**Comment by RaigorJiang** [comment]
@yx9o  Thank you.
