### ISSUE TITLE
Please provide a sample hint configuration for ShardingJDBC5.0.0-beta version. Thank you!

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11088]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
Please provide a sample hint configuration for ShardingJDBC5.0.0-beta version. Thank you!

**Comment by avalon5666** [comment]
See [example](https://github.com/apache/shardingsphere/tree/5.0.0-beta/examples/shardingsphere-jdbc-example/other-feature-example/hint-example/hint-raw-jdbc-example).

**Comment by Yule-Momoko** [comment]
what ?   this is  ShardingJDBC5.0.0-alpha version,There is no help

**Comment by avalon5666** [comment]
Hi, this example work on 5.0.0-beta too, pls try it.
We had modify the example version in master.

**Comment by Yule-Momoko** [comment]
this example  Is configured in SPI mode ,I need BASE-CLASS mode

**Comment by avalon5666** [comment]
Take a look at the examples and documentation. I don't understand what is spi and what is class_based.
```
  defaultDatabaseStrategy:
    hint:
      shardingAlgorithmName: hint_test
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    hint_test:
      type: HINT_TEST
```
```
public final class ModuloHintShardingAlgorithm implements HintShardingAlgorithm<Long> {
    ...
    @Override
    public String getType() {
        return "HINT_TEST";
    }
}
```
