### ISSUE TITLE
ShardingUnconfiguredTablesRoutingEngine.java#findDataSourceName() cannot ignore the case of logicTables

### ISSUE THREAD

**Issue by yaomindong1996** [apache/shardingsphere#11093]
## Bug Report

ShardingUnconfiguredTablesRoutingEngine.java#findDataSourceName() cannot ignore the case of logicTables

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
want to ignore the case of logicTables

**Comment by terrymanu** [comment]
The version is out of service, please try new version
