### ISSUE TITLE
Consider about remove MetaDataAwareEventSubscriber

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11097]
After #11084 merged, the GovernanceAuthorityContext has been removed, and there is no implementation class of MetaDataAwareEventSubscriber.
Can we consider about remove MetaDataAwareEventSubscriber?

**Comment by lwclover** [comment]
OK，please walk to pull request [#11099](https://github.com/apache/shardingsphere/pull/11099)

**Comment by tristaZero** [comment]
Hi done.
