### ISSUE TITLE
SQL rewriting problems in encrypt scenarios

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11105]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Both

### Expected behavior
‘ALTER TABLE t_user_details DROP COLUMN number’ executed normally.

### Actual behavior
`[ERROR] 2021-07-02 05:18:01.665 [ShardingSphere-ScenarioExecutorPool-jdbc-encrypt-H2-0] o.a.s.t.i.junit.watcher.ITWatcher - Error case: assertExecuteUpdate[jdbc: encrypt -> H2 -> Literal -> ALTER TABLE t_user_details DROP COLUMN number], message: org.h2.jdbc.JdbcSQLException: Column "DROP" not found; SQL statement:
ALTER TABLE t_user_details DROP COLUMN number_cipher  , DROP COLUMN number_plain  [42122-196]`

### Reason analyze (If you can)
DROP is repeatedly written in EncryptAlterTableTokenGenerator.getDropColumnTokens：
![image](https://user-images.githubusercontent.com/76552510/124225202-9ab36900-db39-11eb-8a24-9b9bdfe723d7.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
You can reproduce the issue from the integration test of the DDL, the corresponding statements are marked.
![image](https://user-images.githubusercontent.com/76552510/124226019-fc280780-db3a-11eb-9ad2-8713b559a61d.png)

# By the way
I will try to fix this issue in the next PR if I can.

**Comment by zjcnb** [comment]
Assign it to me, please

**Comment by strongduanmu** [comment]
@zjcnb Assigned, if you have any questions, please ping me.

**Comment by zjcnb** [comment]
> @zjcnb Assigned, if you have any questions, please ping me.

ok

**Comment by zjcnb** [comment]
@JiekerTime  hi bro, The problem is that the SQL syntax h2 is not supported. You can look at this: https://www.h2database.com/html/commands.html#alter_table_drop_column And You can specify db-types="MySQL" in ddl-integration-test-cases.xml, and modify scenario-types="dbtbl_with_readwrite_splitting,readwrite_splitting". Can you submit a PR?

**Comment by JiekerTime** [comment]
> @JiekerTime hi bro, The problem is that the SQL syntax h2 is not supported. You can look at this: https://www.h2database.com/html/commands.html#alter_table_drop_column And You can specify db-types="MySQL" in ddl-integration-test-cases.xml, and modify scenario-types="dbtbl_with_readwrite_splitting,readwrite_splitting". Can you submit a PR?

Modified the main text: "The current problem does not occur in the H2 scenario", you can reproduce the problem by uncommenting it.

**Comment by arthasking123** [comment]
I'll try to fix it because I wrote the code :)

**Comment by strongduanmu** [comment]
@arthasking123 Welcome.

**Comment by JiekerTime** [comment]
problem fixed! so closed.
