### ISSUE TITLE
[Summer 2021] ShardingSphere-Agent Add OpenTelemetry plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/shardingsphere#11102]
According to the current Agent architecture, add the implementation of related APIs and SPI interfaces, and connect with OpenTelemetry.

refer [https://summer.iscas.ac.cn/#/org/prodetail/210090023](https://summer.iscas.ac.cn/#/org/prodetail/210090023)

Task List

- [x] add OpenTelemetry plugin
- [x] add test unit
- [x] add integration test for docker

**Comment by yu199195** [comment]
good job!

**Comment by tristaZero** [comment]
@JooKS-me Welcome.

@yu199195 As the mentor of ShardingSphere community, could you add labels and milestone for this issue?

**Comment by yu199195** [comment]
@tristaZero  Hi, Thank you for the reminder， I will add labels and milestone for this issue.

**Comment by JooKS-me** [comment]
This is a wonderful event and community, thank you for bringing me into the door of open source.

**Comment by tristaZero** [comment]
Hi @JooKS-me  @yu199195 Thanks for your effort here, and please enjoy it!
