### ISSUE TITLE
Wrong metadata in encrypt scenarios

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11103]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Both

### Expected behavior
When I execute ‘ALTER TABLE t_user_details CHANGE number number_new VARCHAR(50)’, it is able to finish the column name change.

### Actual behavior
`[ERROR] 2021-07-02 04:57:46.341 [ShardingSphere-ScenarioExecutorPool-jdbc-dbtbl_with_readwrite_splitting_and_encrypt-H2-0] o.a.s.t.i.junit.watcher.ITWatcher - Error case: assertExecuteUpdate[jdbc: dbtbl_with_readwrite_splitting_and_encrypt -> H2 -> Literal -> ALTER TABLE t_user_details CHANGE number number_new VARCHAR(50)], message: org.h2.jdbc.JdbcSQLException: Column "number" not found; SQL statement:
ALTER TABLE t_user_details_0 CHANGE number number_new VARCHAR(50) [42122-196]`

### Reason analyze (If you can)
EncryptAlterTableTokenGenerator.getModifyColumnTokens
![image](https://user-images.githubusercontent.com/76552510/124222997-6dfd5280-db35-11eb-8bcd-3e54981e5586.png)
As shown, it will look for encrypt rules by the modified column names, thus resulting in no matching encrypt  rules being found.
![image](https://user-images.githubusercontent.com/76552510/124223174-cdf3f900-db35-11eb-91e2-b5d39a272a0a.png)
![image](https://user-images.githubusercontent.com/76552510/124223214-e06e3280-db35-11eb-8621-75c58ddc6cd9.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
You can reproduce the issue from the integration test of the DDL, the corresponding statements are marked.
![image](https://user-images.githubusercontent.com/76552510/124223747-ea446580-db36-11eb-898c-32e0afe8b639.png)

# By the way
I will try to fix this issue in the next PR if I can.

**Comment by tristaZero** [comment]
@strongduanmu Hi could you have a look? Plus, if @zjcnb wants to like a try, welcome.
#11105 and This one.

**Comment by zjcnb** [comment]
> @strongduanmu Hi could you have a look? Plus, if @zjcnb wants to like a try, welcome.
> #11105 and This one.

yeah , I'm willing to give it a try

**Comment by strongduanmu** [comment]
> > @strongduanmu Hi could you have a look? Plus, if @zjcnb wants to like a try, welcome.
> > #11105 and This one.
> 
> yeah , I'm willing to give it a try

@zjcnb Welcome.

**Comment by JiekerTime** [comment]
> > @strongduanmu Hi could you have a look? Plus, if @zjcnb wants to like a try, welcome.
> > #11105 and This one.
> 
> yeah , I'm willing to give it a try

I will also participate in this issue, and you can contact me if you have any questions.

**Comment by zjcnb** [comment]
> > > @strongduanmu Hi could you have a look? Plus, if @zjcnb wants to like a try, welcome.
> > > #11105 and This one.
> > 
> > 
> > yeah , I'm willing to give it a try
> 
> I will also participate in this issue, and you can contact me if you have any questions.

Ok, that's good

**Comment by JiekerTime** [comment]
After confirming that the cause of this problem is not caused by the H2 dialect, the review is detailed in [PR](https://github.com/apache/shardingsphere/runs/3017749540)

**Comment by arthasking123** [comment]
I'll try to fix it because I wrote the code :)

**Comment by arthasking123** [comment]
Can you show me the expected running SQL of 'ALTER TABLE t_user_details CHANGE number number_new VARCHAR(50)' if we 
 use the encrypt configuration in the unit test? @JiekerTime

**Comment by JiekerTime** [comment]
> Can you show me the expected running SQL of 'ALTER TABLE t_user_details CHANGE number number_new VARCHAR(50)' if we
> use the encrypt configuration in the unit test? @JiekerTime

I think the statement  after it is rewritten should be `ALTER TABLE t_user_details CHANGE number_plain number_plain_new,  CHANGE 
 number_cipher number_cipher_new`

**Comment by arthasking123** [comment]
so we need to add column information of number_new like this?
![image](https://user-images.githubusercontent.com/16257131/126108060-a67d5cc3-4737-48c2-ae35-b2b831445347.png)

**Comment by JiekerTime** [comment]
> so we need to add column information of number_new like this?
> 
> ![image](https://user-images.githubusercontent.com/16257131/126108112-99db5727-6575-44ff-ad2b-faeb92cae0c0.png)

I don't think we should configure it, because our changes should be hot-deployed.

**Comment by arthasking123** [comment]
> > so we need to add column information of number_new like this?
> > ![image](https://user-images.githubusercontent.com/16257131/126108112-99db5727-6575-44ff-ad2b-faeb92cae0c0.png)
> 
> I don't think we should configure it, because our changes should be hot-deployed.

so how we determine the cipherColumn name and the plainColumn name of the new column?

**Comment by tristaZero** [comment]
@arthasking123 Appreciated your initiative here.

> how we determine the cipherColumn name and the plainColumn name of the new column?

That's the key point, my suggestion is to generate the names of `cipherColumn` and `plainColumn` by using `new_logic_column_name` + the keyword 'cipher' or `plain`, like 'new_logic_name_plain'.
Besides, you still need to check whether this table has the same columns as our generated column name. How? `FederateTableMetadata` contains all the actual column names.
But no worries, let firstly finish the first bug fix and then consider checking for it.

**Comment by arthasking123** [comment]
maybe we could use a real database to store these encrypt rules instead of using yaml files
