### ISSUE TITLE
PostgreSQL integrates Sharding Proxy and uses Timestamp as the conditional query. There is a problem in the fifth query.

### ISSUE THREAD

**Issue by kenl-lin** [apache/shardingsphere#11110]
In the process of my integration, the following error occurred, when querying through the timestamp type. The first few queries are no problem. It was found that the problem occurred for the fifth time, and finally through the to_timestamp() function query, there was no problem.

`### SQL: select * from order_tick where account_id = ? and trans_time < ?
### Cause: java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy153.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)`

There may also be some problems when responding to the timestamp type.

**Comment by RaigorJiang** [comment]
Sorry, the above PR is for issue 11100, not 11110, and the title has changed.

**Comment by kenl-lin** [comment]
Is this a bug?

**Comment by RaigorJiang** [comment]
Hi @kenl-lin 
I did a test to verify, and no similar exceptions were found.
```sql
sharding_db=# select * from t_order;
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        2 |       2 | ok     | 2021-09-28 11:51:03.0 
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(2 rows)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)
 
sharding_db=# select * from t_order where user_id = 1 and trans_time < '2021-09-28 00:00:00.0';
 order_id | user_id | status |      trans_time       
----------+---------+--------+-----------------------
        1 |       1 | ok     | 2021-09-01 11:51:59.0 
(1 row)

```


My version is 5.0.0-RC1 (master branch), welcome to try the new version.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, I will close it. 
If you still have related questions, please submit a new issue, thank you.
