### ISSUE TITLE
JoinType of JoinTableSegment is missing

### ISSUE THREAD

**Issue by guimingyue** [apache/shardingsphere#11115]
The `joinType` field of `JoinTableSegment` is null for inner join. I think the `ParseTreeVisitor` does not handle the join type property. For example, the testcase of [SelectStatementSqlNodeConverterTest#testConvertInnerJoin](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-optimize/src/test/java/org/apache/shardingsphere/infra/optimize/core/convert/SelectStatementSqlNodeConverterTest.java#LC147).
<img width="600" alt="Screen Shot 2021-07-02 at 23 09 31" src="https://user-images.githubusercontent.com/1716196/124295234-2ef9ec00-db8b-11eb-954b-fb40001b308b.png">

The following image is the method of `org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor#visitJoinedTable`. And nothing has been assigned to `JoinTableSegment` object.

<img width="999" alt="Screen Shot 2021-07-02 at 23 25 13" src="https://user-images.githubusercontent.com/1716196/124297109-4c2fba00-db8d-11eb-98d8-c081ac92a6fa.png">

**Comment by tuichenchuxin** [comment]
I'd like to try that

**Comment by tuichenchuxin** [comment]
@guimingyue 
Hi, i can assigned the joinType to 3 types
"INNER","LEFT","RIGHT" but not "FULL".
Because mysql only support this
joined_table: {
    table_reference {[INNER | CROSS] JOIN | STRAIGHT_JOIN} table_factor [join_specification]
  | table_reference {LEFT|RIGHT} [OUTER] JOIN table_reference join_specification
  | table_reference NATURAL [INNER | {LEFT|RIGHT} [OUTER]] JOIN table_factor
}
will this three type enough for you ?

**Comment by guimingyue** [comment]
> n

It's ok for MySQL for now.

**Comment by tuichenchuxin** [comment]
@guimingyue 
ok，i'll make 
[INNER | CROSS] JOIN | STRAIGHT_JOIN AS "INNER";
{LEFT|RIGHT} [OUTER] JOIN AS "LEFT"/"RIGHT";
NATURAL [INNER | {LEFT|RIGHT} [OUTER]] JOIN AS "INNER"/"LEFT"/"RIGHT";
Will this be ok?

**Comment by guimingyue** [comment]
> @guimingyue
> ok，i'll make
> [INNER | CROSS] JOIN | STRAIGHT_JOIN AS "INNER";
> {LEFT|RIGHT} [OUTER] JOIN AS "LEFT"/"RIGHT";
> NATURAL [INNER | {LEFT|RIGHT} [OUTER]] JOIN AS "INNER"/"LEFT"/"RIGHT";
> Will this be ok?

STRAIGHT_JOIN and INNER JOIN are not equal, so I think we should leave it to be unsupported.

**Comment by tuichenchuxin** [comment]
> > @guimingyue
> > ok，i'll make
> > [INNER | CROSS] JOIN | STRAIGHT_JOIN AS "INNER";
> > {LEFT|RIGHT} [OUTER] JOIN AS "LEFT"/"RIGHT";
> > NATURAL [INNER | {LEFT|RIGHT} [OUTER]] JOIN AS "INNER"/"LEFT"/"RIGHT";
> > Will this be ok?
> 
> STRAIGHT_JOIN and INNER JOIN are not equal, so I think we should leave it to be unsupported.

emm,you are right!

**Comment by tuichenchuxin** [comment]
@guimingyue 
I think NATURAL [INNER | {LEFT|RIGHT} [OUTER]] JOIN  is different either,
So,i think assign joinType as 'NATURAL' will be better.
