### ISSUE TITLE
Some subclass of `ExpressionSegment` have not been parsed

### ISSUE THREAD

**Issue by guimingyue** [apache/shardingsphere#11127]
The expression of `ExpressionOrderByItemSegment`  and `ExpressionProjectionSegment` contains only String type field, which cannot be converted to calcite SqlNode.

Then expression field should be ast object.

**Comment by tuichenchuxin** [comment]
I want fix it.

**Comment by tuichenchuxin** [comment]
@guimingyue I want to know what kind of object you need?

**Comment by guimingyue** [comment]
> @guimingyue I want to know what kind of object you need?

For example, the expression '10+30' in the select list of the following SQL should be parsed as a BinaryOperationExpression object, and the left and right fields should LiteralExpressionSegment objects.

```sql
select 10 + 30, o1.order_id + 10, o1.order_id, o1.user_id from t_order o1
```
