### ISSUE TITLE
5.0.0-beta insert data, failed to get autoincrement primary key

### ISSUE THREAD

**Issue by boycai** [apache/shardingsphere#11122]
### Which version of ShardingSphere did you use?
5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc-core

### Expected behavior
The use of "insert" to the table when inserting data, can be obtained from the entity class to ID (on the primary key). Because before using 4.0.1 versions are supported

### Actual behavior
I use Mybatis, primary keys on the table into the line, to generate the primary key ID should be automatically set to an instance of my class in the ID attribute, but now after insert object access ID is still empty.

### Reason analyze (If you can)
The debug tracking results：
`
Class: org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator

Statement stmt;
org.apache.shardingsphere.driver.jdbc.core.resultset.GeneratedKeysResultSet rs = stmt.getGeneratedKeys();
rs.isClosed() -> false
rs.next() -> false
`
**Should be a cursor has been moved to the end. If before used up, initiative to set the cursor to the starting position ( eg: ResultSet.beforeFirst() ), may be able to solve this problem.**

### Example codes for reproduce this issue (such as a github link).
My Codes:
`
MyBatis XML：
\<insert id="insert" parameterType="com.*.model.Article" keyProperty="id" keyColumn="id" useGeneratedKeys="true" >
    INSERT INTO article (type, title) VALUES (#{type}, #{title})
\</insert>

Java Codes：
if (article.getId() == null) {
    articleService.insert(article);
    System.out.println("id=" + article.getId());// id=null （Using version 5.0-beta after the output is null, 4.0.1 version is good）
}
`

**Comment by tristaZero** [comment]
@zjcnb Hi, could you have a look here? What you changed in our last PR is about this one?

**Comment by zjcnb** [comment]
> @zjcnb Hi, could you have a look here? What you changed in our last PR is about this one?

OK, let me see

**Comment by zjcnb** [comment]
@tristaZero @boycai  hello, I just checked that the related, code has not yet been merged into the beta branch. Can you try the 5.0.0-RC1-SNAPSHOT branch

**Comment by tristaZero** [comment]
So we have fixed this issue on our master branch, right? @zjcnb

**Comment by zjcnb** [comment]
> So we have fixed this issue on our master branch, right? @zjcnb

yes
