### ISSUE TITLE
ShardingSphere-Proxy 5.0beta版，在分片规则中未指定具体表的分库规则，不走默认分库规则

### ISSUE THREAD

**Issue by wjh0258** [apache/shardingsphere#11139]
ShardingSphere-Proxy 5.0beta版

在分片规则中未指定具体表的分库规则，不走默认分库规则，都默认插入到了配置中的最后一个数据源。

表比较多不想一个个表配置路由规则，能否未配置的走默认统一路由配置？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
