### ISSUE TITLE
Add unit test for shardingsphere-agent-core

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#11156]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-agent-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [x] ComposeClassStaticMethodAroundAdvice
- [x] ComposeConstructorAdvice

## Examples FYI
- ShardingSphereTransformerTest

**Comment by Swastyy** [comment]
@soulasuna Can I work on this issue?

P.S. It would be great if you can share some resources since I am new to open source in databases.

**Comment by Swastyy** [comment]
Hey @tristaZero when I am cloning the repo into my local machine its not cloning all the folders. 
![image](https://user-images.githubusercontent.com/64654203/125267965-e1b51180-e324-11eb-8cc3-5d46a6f70907.png)

**Comment by tristaZero** [comment]
Hi @Swastyy ,

Welcome, I guess we already have met yesterday, right?

**Comment by Swastyy** [comment]
> Hi @Swastyy ,
> 
> Welcome, I guess we already have met yesterday, right?

Yep, but I dont know why it is not working 😕

**Comment by tristaZero** [comment]
> when I am cloning the repo into my local machine its not cloning all the folders.

It looks a little wired. You ran `git clone your forked repo`, right?

**Comment by Swastyy** [comment]
Hmm yes

**Comment by Swastyy** [comment]
@tristaZero I think I found the problem. Sorry for disturbing

**Comment by menghaoranss** [comment]
@Swastyy I have removed unnecessary task list. This issue has been perfectly solved. Thanks for your contribution.
