### ISSUE TITLE
The CAST function is not supported

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11168]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
The CAST function is not supported
for example:
SELECT
	CAST( g_no AS SIGNED ) 
FROM t_order
### Actual behavior

com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)

**Comment by tuichenchuxin** [comment]
I want fix it.

**Comment by strongduanmu** [comment]
@Yule-Momoko Thank you for your feedback, @tuichenchuxin will track it.
