### ISSUE TITLE
sharding-jdbc-spring-boot-starter 4.1.1, throw IndexOutOfBoundsException excetion

### ISSUE THREAD

**Issue by qq279973895** [apache/shardingsphere#11162]
my mysql table ：
![图片](https://user-images.githubusercontent.com/14822832/124456926-d8c0bf00-ddbd-11eb-9930-6e3dbb9f23c2.png)

CREATE TABLE `t_testpaper_question` (
  `id` bigint(20) unsigned NOT NULL,
  `paperId` bigint(20) DEFAULT NULL,
  `questionId` bigint(20) NOT NULL,
  `innerOrder` int(11) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '0禁用，1启用',
  PRIMARY KEY (`id`),
  KEY `tq_paperId` (`paperId`),
  KEY `t_testpaper_question_questionId_index` (`questionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC

pom version:
![图片](https://user-images.githubusercontent.com/14822832/124457045-f7bf5100-ddbd-11eb-895e-5e7b8a912b4b.png)

When I use spring boot excute sql : "SELECT ttq.*,(@rowNum :=@rowNum + 1) AS num FROM t_testpaper_question ttq,(SELECT @rowNum := 0) temp WHERE paperId = 160 AND STATUS = 1 ORDER BY innerOrder"，my idea throw IndexOutOfBoundsException.

The following is idea console info：
2021-07-05 18:11:13.889 ERROR 15476 --- [  XNIO-1 task-1] c.q.p.qlib.exception.ExcptionAdvice      : occur unhandle exception: org.mybatis.spring.MyBatisSystemException, errorMsg: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IndexOutOfBoundsException: Index: 0

![图片](https://user-images.githubusercontent.com/14822832/124458210-4b7e6a00-ddbf-11eb-89ee-b7e3fea4cdf3.png)

**Comment by qq279973895** [comment]
TestPaperMapper.xml error sql ： 
<select id="getTestpaperQuestionByPaperId" resultType="com.qishiyun.poplar.qlib.dto.TestpaperQuestion">
        select ttq.*,(@rowNum :=@rowNum + 1) AS num from t_testpaper_question ttq,(SELECT @rowNum := 0) temp where paperId = #{paperId} and status = 1 order by innerOrder
</select>

**Comment by terrymanu** [comment]
Sorry to reply late.
mybatis-plus is the ORM framework of JDBC.
Actually, , ShardingSphere community have no time to read source codes of other ORM framework, we are focusing on JDBC(or proxy) only.
So, please do some investigate, and then we can locate about SQL and JDBC interface.
