### ISSUE TITLE
where does the  shariding-ui store the data 

### ISSUE THREAD

**Issue by GarfieldZhan** [apache/shardingsphere#11166]
what did I do:
I deploy sharding-proxy-4.1.1 and sharding-4.1.1-ui  in  my  machine ,And I registry config center and registry center using the ui , but when I create database with comment in Chinese  , the comments turn to '???'  
So I stop the  sharding-proxy-4.1.1 and sharding-proxy-4.1.1-ui  , then I deploy  sharding-5.0.0-beta and   sharding-5.0.0-ui-alpha in the SAME machine，when I login the  ui and  click the  registry center,I find some the error:  
![image](https://user-images.githubusercontent.com/39785377/124531598-698cae80-de41-11eb-99b5-552f27014707.png)
Notice this one :"namespace: orchestration" in the error information, "orchestration" is the default config in the sharding-proxy-4.1.1, the server.yml below:

orchestration:
  orchestration_ds:
    orchestrationType: registry_center,config_center,distributed_lock_manager
    instanceType: zookeeper
    serverLists: localhost:2181
    namespace: orchestration
    props:
      overwrite: false
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
#
authentication:
  users:
    root:
      password: PASSWORD
    sharding:
      password: sharding 
      authorizedSchemas: PASSWORD
#
props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  proxy.hint.enabled: false
  query.with.cipher.column: true
  sql.show: false
  allow.range.query.with.inline.sharding: false

so I think there's somethind wrong with the data the  sharding-ui store

**Comment by tristaZero** [comment]
Hi @GarfieldZhan The configuration is a bit different between 5.x and 4.x, please give a look at the doc and [example](https://github.com/apache/shardingsphere/tree/5.0.0-beta/examples).
