### ISSUE TITLE
select count(1)+1 from test_table not support

### ISSUE THREAD

**Issue by JoinWDT** [apache/shardingsphere#11174]
### Which version of ShardingSphere did you use?

5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

`1. select CONCAT(ROUND(SUM(1)/0.000131*100,3), '') from test_table`
`2. select count(1)+1 from test_table`
`3. select count(1)+sum(1) from test_table`

**Comment by strongduanmu** [comment]
@JoinWDT What is the exception information?

**Comment by tuichenchuxin** [comment]
@strongduanmu I had test this sql on master branch , it is supported.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it.
