### ISSUE TITLE
Add example to validate Parser SQLStatement for SQL92 Database.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11197]
Hi community,

This issue is for #10887.

## Aim
Add example to validate Parser SQLStatement for SQL92 Database.

## Examples FYI
- MySQLParserStatementExample

**Comment by zoujianchao** [comment]
I'll make it

**Comment by zoujianchao** [comment]
please assign it to me,dear zjcnb

**Comment by strongduanmu** [comment]
@zoujianchao Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.
