### ISSUE TITLE
Add examples to validate Parser SQLStatement for SqlServer DataBase.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11195]
Hi community,

This issue is for #10887.

## Aim
Add examples to validate Parser SQLStatement for SqlServer DataBase.

## Examples FYI
- MySQLParserStatementExample

**Comment by LeeGuoPing** [comment]
please assign it to me,dear zjcnb

**Comment by daipengfei183** [comment]
i want to do it！

**Comment by strongduanmu** [comment]
@LeeGuoPing  Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.

**Comment by strongduanmu** [comment]
@daipengfei183 Are you interested in other osd tasks? Like, this issue —— https://github.com/apache/shardingsphere/issues/10868.
