### ISSUE TITLE
Add examples to validate Parser SQLStatement for oracle.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11193]
Hi community,

This issue is for #10887.

## Aim
Add examples to validate Parser SQLStatement for Oracle Datebase.

## Examples FYI
- MySQLParserStatementExample

**Comment by LeeGuoPing** [comment]
please assign it to me

**Comment by strongduanmu** [comment]
> please assign it to me

@LeeGuoPing Welcome, i will assign this issue to you.
