### ISSUE TITLE
Add example to validate Parser SQLStatement for PostgreSQL Database.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11198]
Hi community,

This issue is for #10887.

## Aim
Add example to validate Parser SQLStatement for PostgreSQL Database.

## Examples FYI
- MySQLParserStatementExample

**Comment by TyrealBM** [comment]
please assign it to me,dear zjcnb

**Comment by strongduanmu** [comment]
@TyrealBM Welcome, and you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribution.

**Comment by Swastyy** [comment]
@strongduanmu Is it still open? Can I work on this?

**Comment by strongduanmu** [comment]
@Swastyy This issue has been assigned to @TyrealBM, you can claim other osd tasks, such as issue #10915.
