### ISSUE TITLE
5.0.0 oracle hibernate 子查询 语句解析有误

### ISSUE THREAD

**Issue by sharplaw** [apache/shardingsphere#11214]
执行语句：SELECT * FROM (SELECT adminuserd0_.ID AS id1_6_, adminuserd0_.AVATAR AS avatar2_6_, adminuserd0_.CREATED_AT AS created_at3_6_, adminuserd0_.DELETED_AT AS deleted_at4_6_, adminuserd0_.DISABLED AS disabled5_6_, adminuserd0_.PASSWORD AS password6_6_, adminuserd0_.PHONE AS phone7_6_, adminuserd0_.REAL_NAME AS real_name8_6_, adminuserd0_.SEX AS sex9_6_, adminuserd0_.UPDATED_AT AS updated_at10_6_, adminuserd0_.USERNAME AS username11_6_ FROM ADMIN_USER adminuserd0_ WHERE (adminuserd0_.deleted_at IS NULL) AND (adminuserd0_.USERNAME LIKE ?) ORDER BY adminuserd0_.ID DESC) WHERE rownum <= ?
控制台报错打印数据：子查询select * 替换有误
Sql = SELECT "adminuserd0_"."id", "adminuserd0_"."password", "adminuserd0_"."avatar", "adminuserd0_"."created_at", "adminuserd0_"."updated_at", "adminuserd0_"."deleted_at", "adminuserd0_"."disabled", "adminuserd0_"."wt_real_name_in", "adminuserd0_"."USERNAME" AS username, "adminuserd0_"."wt_username_in", "adminuserd0_"."PHONE" AS phone, "adminuserd0_"."real_name", "adminuserd0_"."sex" FROM (SELECT adminuserd0_.ID AS id1_6_, adminuserd0_.AVATAR AS avatar2_6_, adminuserd0_.CREATED_AT AS created_at3_6_, adminuserd0_.DELETED_AT AS deleted_at4_6_, adminuserd0_.DISABLED AS disabled5_6_, adminuserd0_.PASSWORD AS password6_6_, adminuserd0_.PHONE AS phone7_6_, adminuserd0_.REAL_NAME AS real_name8_6_, adminuserd0_.SEX AS sex9_6_, adminuserd0_.UPDATED_AT AS updated_at10_6_, adminuserd0_.USERNAME AS username11_6_ FROM ADMIN_USER adminuserd0_ WHERE (adminuserd0_.deleted_at IS NULL) AND (adminuserd0_.USERNAME LIKE :1 ) ORDER BY adminuserd0_.ID DESC) WHERE rownum <= :2 , 

OriginalSql = SELECT "adminuserd0_"."id", "adminuserd0_"."password", "adminuserd0_"."avatar", "adminuserd0_"."created_at", "adminuserd0_"."updated_at", "adminuserd0_"."deleted_at", "adminuserd0_"."disabled", "adminuserd0_"."wt_real_name_in", "adminuserd0_"."USERNAME" AS username, "adminuserd0_"."wt_username_in", "adminuserd0_"."PHONE" AS phone, "adminuserd0_"."real_name", "adminuserd0_"."sex" FROM (SELECT adminuserd0_.ID AS id1_6_, adminuserd0_.AVATAR AS avatar2_6_, adminuserd0_.CREATED_AT AS created_at3_6_, adminuserd0_.DELETED_AT AS deleted_at4_6_, adminuserd0_.DISABLED AS disabled5_6_, adminuserd0_.PASSWORD AS password6_6_, adminuserd0_.PHONE AS phone7_6_, adminuserd0_.REAL_NAME AS real_name8_6_, adminuserd0_.SEX AS sex9_6_, adminuserd0_.UPDATED_AT AS updated_at10_6_, adminuserd0_.USERNAME AS username11_6_ FROM ADMIN_USER adminuserd0_ WHERE (adminuserd0_.deleted_at IS NULL) AND (adminuserd0_.USERNAME LIKE ?) ORDER BY adminuserd0_.ID DESC) WHERE rownum <= ?, 
Error Msg = ORA-00904: "adminuserd0_"."sex": 标识符无效

**Comment by zjcnb** [comment]
hi,  ShardingSphere-Proxy currently does not support Oracle

**Comment by sharplaw** [comment]
I use&nbsp;ShardingSphere-JDBC ,not&nbsp;ShardingSphere-Proxy



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/shardingsphere] 5.0.0 oracle hibernate 子查询 语句解析有误 (#11214)





 
hi,  ShardingSphere-Proxy currently does not support Oracle

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
