### ISSUE TITLE
shardingproxy：readwrite-splitting does not work

### ISSUE THREAD

**Issue by half-pa** [apache/shardingsphere#11213]
version:5.0-beta
config-master-slave.xml
config:
`schemaName: master_slave_db

dataSources:
  master:
    url: jdbc:mysql://ocalhost:3306/put_up1?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&autoReconnect=true
    username: fowrite
    password: 717jL4H729apESWqeDsOnUX6P1iPvO+U2wt9rGI
    connectionTimeoutMilliseconds: 660000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 300000
    maxPoolSize: 3000
    minPoolSize: 10
    maintenanceIntervalMilliseconds: 30000
    keepaliveTime: 260000
  slave0:
    url: jdbc:mysql://localhost:3306/put_up2?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&autoReconnect=true
    username: forread
    password: (lZeDLLBr7EmHvgrVACiJjV3uoUGC4CuDzvIxv9tc
    connectionTimeoutMilliseconds: 660000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 300000
    maxPoolSize: 3000
    minPoolSize: 10
    maintenanceIntervalMilliseconds: 30000
    keepaliveTime: 260000

rules:
  - !READWRITE_SPLITTING
    dataSources:
      pr_ds:
        writeDataSourceName: master
        readDataSourceNames:
          - slave0
        loadBalancerName: roundRobin
    loadBalancers:
      roundRobin:
        type: ROUND_ROBIN`

when I excute1000 query sqls ,my master DB (DB for write) got the query request more than my slave DB

**Comment by strongduanmu** [comment]
@half-pa Do you mean to execute 1000 SQL at a time? This type of SQL is not currently supported, and multiple SQLs executed at a time may be of different types, which will lead to incorrect read-write routing.

**Comment by half-pa** [comment]
@strongduanmu I have1000 threads, one query per thread, but more queries received by the master DB。not 1000 query SQL at a time。

**Comment by terrymanu** [comment]
This is the basic feature, there are integrate tests running every commit.
So, it is better to check the configuration of your program.
