### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by damo120** [apache/shardingsphere#11211]
table1 use has_mod,sharding-count is 9;
table2 use has_mod,sharding-count is 19;
when select by 

'select * from table2 where exists(select * from table1 where table1.xx=table2.xx)'

runtime error 

using ShardingSphere-proxy 5.0.0-bate

**Comment by terrymanu** [comment]
Can you provide the exception stack trace?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
