### ISSUE TITLE
sql "start transaction read only" not support on pg/openGauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11238]
## Bug Report
if we set a transaction with read only level,  this will success insert on proxy, but fail on pg/openGauss, this is proxy's bug, please fix.

### Which version of ShardingSphere did you use?
opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
can't insert data when set read only level
### Actual behavior
insert success
### Reason analyze (If you can)
transaction not correct dispose
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
login in sharding_db, then do  this:
sharding_db=>start transaction read only;
sharding_db=>insert into t_order (user_id, order_id) values (1, 1);  ---this must throw exception from pg/opengauss 
sharding_db=> end;

**Comment by jingshanglu** [comment]
It maybe fixed by #14983.
