### ISSUE TITLE
result incorrect when DN not reachable in proxy on pg/opengauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11239]
## Bug Report
proxy with two node DN1, DN2 and start success. then I stop DN1, and DN2. when we use gsql connect to sharding_db,  we can get `select gs_password_notifytime()` and `select intervaltonum(gs_password_deadline())` return 1, this is incorrect , we expect throw exception

### Which version of ShardingSphere did you use?
opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy 
### Expected behavior
throw exception when run select func() when DN node is not reachable
### Actual behavior
get result  1 
### Reason analyze (If you can)
exception not diposed when connection if refuse
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
proxy with two node DN1, DN2 and start success. then I stop DN1, and DN2. when we use gsql connect to sharding_db,  we can get `select gs_password_notifytime()` and `select intervaltonum(gs_password_deadline())` return 1, this is incorrect , we expect throw exception
### Example codes for reproduce this issue (such as a github link).
see link and they discuss:
https://gitee.com/opengauss/openGauss-distributed-solutions/issues/I3YK9C?from=project-issue
https://gitee.com/opengauss/openGauss-distributed-solutions/issues/I3Z7CR?from=project-issue

**Comment by tristaZero** [comment]
@justbk2015 Hi, I saw many issues about OG SQLs.
Currently, we will firstly deal with PostgreSQL SQL. BTW, are the issues you raised all in PostgreSQL's SQL list?
If not, please comment something on that issue. Thanks.
