### ISSUE TITLE
create/alter/drop view not support on pg/openGauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11237]
## Feature Request
to support create/alter/drop view on pg/openGauss

### Is your feature request related to a problem?
I find pr: https://github.com/apache/shardingsphere/pull/7740 already support on mysql,so can your support pg/openGauss too?
### Describe the feature you would like.
sharding_db=> CREATE VIEW MyView AS select a.,b.item_con from t_order a,t_order_item b where a.order_id = b.order_id and a.user_id = b.user_id;
ERROR: relation "t_order" does not exist on master1 ===> we need this view sql language success execute and view truely created!

**Comment by SteNicholas** [comment]
@justbk2015 `CREATE/ALTER/DROP VIEW` is supported in MySQL, other like PG/OpenGauss doesn't support this. Do you have interest to contribute this support? @strongduanmu could help you to contribute.

**Comment by justbk2015** [comment]
> @justbk2015 `CREATE/ALTER/DROP VIEW` is supported in MySQL, other like PG/OpenGauss doesn't support this. Do you have interest to contribute this support? @strongduanmu could help you to contribute.

I will try it

**Comment by strongduanmu** [comment]
This issue has been supported by issue #17915, so I will close this issue.
