### ISSUE TITLE
drop tablespace have difference result in two DN nodes

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11235]
## Bug Report
if we create a single table on two DN nodes's tablespace, order is DN1,DN2。 then we try to drop tablespace,  not all ways get exception, if table create on DN2, even if tablespace can't delete, but result if success!
### Which version of ShardingSphere did you use?
opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
we need get exception  result  for drop tablespace! 
### Actual behavior
if table create on DN1 then get exception , otherwith table create on  DN2 then get delete success, but tablespace not delete!
### Reason analyze (If you can)
1. result merge behaive not right!
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. create tablespace tblspc;
2. create table tb_space(id int);
3. drop tablespace tblspc; ---- if tb_space create on DN1, then result with exception(this is our expect) ; if tb_space create on DN2, the result is success,(without expect)

### Example codes for reproduce this issue (such as a github link).
see: https://gitee.com/opengauss/openGauss-distributed-solutions/issues/I3XUXH?from=project-issue

**Comment by tuichenchuxin** [comment]
@justbk2015 
Which version do you use of sharding-proxy?
I tested what you said ,but can't reproduce you bug.
![image](https://user-images.githubusercontent.com/86938616/125879938-00b703eb-384e-4289-9b4d-80deb1b74a22.png)

**Comment by justbk2015** [comment]
> @justbk2015
> Which version do you use of sharding-proxy?
> I tested what you said ,but can't reproduce you bug.
> ![image](https://user-images.githubusercontent.com/86938616/125879938-00b703eb-384e-4289-9b4d-80deb1b74a22.png)

opengauss_adapt branch

**Comment by tuichenchuxin** [comment]
@justbk2015 Maybe you need to merge master into opengauss_adapt_branch, then test it again.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
