### ISSUE TITLE
grant not support on pg/openGauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11236]
## Bug Report
grant privileges to user_test; 
this language not support on sharding-proxy

### Which version of ShardingSphere did you use?
opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
execute success
### Actual behavior
with exception
### Reason analyze (If you can)
not support this language
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
use gsql to login sharding_db, then execute:
sharding_db=>grant all privileges to user_test; 
result is ERROR: You have an error in your SQL syntax
### Example codes for reproduce this issue (such as a github link).
see: https://gitee.com/opengauss/openGauss-distributed-solutions/issues/I3YPSM?from=project-issue

**Comment by SteNicholas** [comment]
@justbk2015 , `GRANT` syntax isn't supported in PG/OpenGauss. Do you have interest to contribute this adapter to PG/OpenGauss?

**Comment by justbk2015** [comment]
> @justbk2015 , `GRANT` syntax isn't supported in PG/OpenGauss. Do you have interest to contribute this adapter to PG/OpenGauss?

I'd like to try it

**Comment by tuichenchuxin** [comment]
@justbk2015 
I saw you have this sql:
grant privileges to user_test;
I don't konw if `privileges` is a role or a keyword.
if it is a role ,then sharding-proxy is supported.
if it is a keyword ,then the PG official document is not support.
see https://www.postgresql.org/docs/13/sql-grant.html

**Comment by justbk2015** [comment]
> @justbk2015
> I saw you have this sql:
> grant privileges to user_test;
> I don't konw if `privileges` is a role or a keyword.
> if it is a role ,then sharding-proxy is supported.
> if it is a keyword ,then the PG official document is not support.
> see https://www.postgresql.org/docs/13/sql-grant.html

I spell some error, please use `grant all privileges to user_role` instead.

**Comment by tuichenchuxin** [comment]
@justbk2015 
grant all privileges to user_role is not supported by pg official document,
may be 'grant all privileges on t_order to user_role'

**Comment by justbk2015** [comment]
> @justbk2015
> grant all privileges to user_role is not supported by pg official document,
> may be 'grant all privileges on t_order to user_role'

I will try and soon reponse you.

**Comment by sandynz** [comment]
@justbk2015 feedback it works. Closed.
