### ISSUE TITLE
rollback not completely support in pg/opengauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11243]
## Bug Report
if create table called in transaction  ,then rollback, the table is not created, but the table metadata was updated in proxy,  I can't recreate this table before restart proxy.

### Which version of ShardingSphere did you use?
opengauss_adapt
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
I can recreate table after transaction rollback
### Actual behavior
I can't create table
### Reason analyze (If you can)
table metadata was updated whatever this transaction is rollback or not.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sharding_db=> begin;
BEGIN
sharding_db=> create table test(id int);
0
sharding_db=> rollback;
ROLLBACK
sharding_db=> create table test(id int); -----there have error!
ERROR: Table 'test' already exists.
sharding_db=> drop table test;
ERROR: table "test" does not exist
### Example codes for reproduce this issue (such as a github link).
see link: https://gitee.com/opengauss/openGauss-distributed-solutions/issues/I3ZQNI?from=project-issue

**Comment by jingshanglu** [comment]
Now, DDL cannot be executed inside a transaction block, only outside a transaction block.
