### ISSUE TITLE
spring boot 2.x+ss 5.0.0-beta, discussion of using underscores in properties in configuration files

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#11242]
**description:**
Spring boot 2.x does not support underscores in attribute names. In the official documentation of ss, there are underscores in attribute names in the configuration of the fragmentation algorithm, such as:
```
# Configure sharding algorithm
spring.shardingsphere.rules.sharding.sharding-algorithms.database_inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database_inline.props.algorithm-expression=ds_${user_id% 2}
spring.shardingsphere.rules.sharding.sharding-algorithms.table_inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.table_inline.props.algorithm-expression=t_order_${order_id% 2}
```
I think database_inline and table_inline need to be adjusted and cannot contain underscores, because such a configuration will report an error when it starts. The error is as follows:
```
ss error: Preconditions.checkNotNull(expression, "Inline sharding algorithm expression cannot be null.");
springboot error: "Configuration property name'" + name + "'is not valid".
```
I think the error report of springboot is clearer, and the user can know which attribute in the configuration is wrong or invalid.

and so,
I expect to be able to output the springboot error in the catch of the PropertyUtil.containPropertyPrefix(final Environment environment, final String prefix) method. And adjust the underline in the document.

Welcome to leave a comment and discuss.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
