### ISSUE TITLE
Reason: Failed to bind properties under 'sharding.jdbc.datasource.db' to java.util.Map<?, ?>

### ISSUE THREAD

**Issue by abideZLQ** [apache/shardingsphere#11255]
一、envorment：

sharding jdbc5.0.0-meta + springboot2.0.0.M2 + mybatis plus 3

simple project address:  https://github.com/abideZLQ/sharding-jdbc-demo.git

二、sprintboot start-up error：

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target [Bindable@4f8d86e4 type = java.util.Map<?, ?>, value = 'none', annotations = array<Annotation>[[empty]]] failed:

    Reason: Failed to bind properties under 'sharding.jdbc.datasource.db' to java.util.Map<?, ?>

Action:

Update your application's configuration

Process finished with exit code 1

**Comment by zjcnb** [comment]
Hi bro, i use your config it can work. You can refer to this [https://github.com/zjcnb/ss-example.git](url)

**Comment by terrymanu** [comment]
Closed because of no response anymore.
