### ISSUE TITLE
Why is the exception of my SQL execution not thrown out

### ISSUE THREAD

**Issue by JonasGao** [apache/shardingsphere#11251]
## Question

When I migrated the legacy code, I did not pay attention to the table structure is not suitable for sharding. 
After completing the Sharding configuration. I test my code. It is an insert operation. I found that it did not report an error, but returned the number of affected rows "-1". I was confused at the time. After many attempts, I amended the table structure. Normally, SQLException will be thrown in this case. 
Afterwards, I briefly read the source code.
So, why does JDBCExecutorCallback not throw SQLException

Let's give a chestnut 🙋‍♂️

```sql
CREATE TABLE ht_supply_price_sku_adjust
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(100) NOT NULL
)
```

And use default key generate strategy. Default key is of type LONG. INT will fail. 
Now when you insert into some table like `ht_supply_price_sku_adjust_01`. it will return -1

The source code is there
```java
public abstract class JDBCExecutorCallback<T> implements ExecutorCallback<JDBCExecutionUnit, T> {
    private T execute(JDBCExecutionUnit jdbcExecutionUnit, boolean isTrunkThread, Map<String, Object> dataMap) throws SQLException {
       ...
        try {
            ...
        } catch (SQLException var8) {
            // Hi, there. Why not throw the var8 ?
            if (!isTrunkThread) {
                return null;
            } else {
                Optional<T> saneResult = this.getSaneResult(this.sqlStatement);
                if (saneResult.isPresent()) {
                    return saneResult.get();
                } else {
                    sqlExecutionHook.finishFailure(var8);
                    SQLExecutorExceptionHandler.handleException(var8);
                    return null;
                }
            }
        }
    }
}
```

**Comment by RaigorJiang** [comment]
Hi @JonasGao 
Please refer to #10844 , You can try the latest version by build master branch.

**Comment by tristaZero** [comment]
@JonasGao I stand @RaigorJiang . Plus, your 🙋‍♂️  ... looks cute.

**Comment by JonasGao** [comment]
@RaigorJiang Nice. I will try later.
