### ISSUE TITLE
sharding-proxy  XA transaction manager

### ISSUE THREAD

**Issue by ZhengSiyang** [apache/shardingsphere#11253]
Sharding-proxy cannot be integrated in the application as a data source, as a data source in a multi-data source distributed transaction manager

![微信截图_20210709173453](https://user-images.githubusercontent.com/26701055/125058375-c952b600-e0dc-11eb-8ab5-45c7345590ad.png)

![微信截图_20210709173716](https://user-images.githubusercontent.com/26701055/125058393-ce176a00-e0dc-11eb-85af-9d2e37b039a5.png)

Please help me, what causes this problem

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
