### ISSUE TITLE
Document Corrigendum：5.x Version FAQ

### ISSUE THREAD

**Issue by acmenlt** [apache/shardingsphere#11264]
## Problem description

Article 16 of FAQ in version 5.x of the official website is inconsistent with the actual situation

Shardingkeygenerator no longer exists in the latest version

## Repair opinion

Modify the Shardingkeygenerator to the correct Keygeneratealgorithm

Address：https://shardingsphere.apache.org/document/current/cn/faq/

**Comment by yx9o** [comment]
I'll do it

**Comment by strongduanmu** [comment]
@yx9o Welcome, assigned.

**Comment by yx9o** [comment]
fixed in #11292

**Comment by RaigorJiang** [comment]
Hi @longtai94, can this issue be closed now?
