### ISSUE TITLE
Can not route tables for [pg_database], please make sure the tables are in same schema

### ISSUE THREAD

**Issue by Yuesd** [apache/shardingsphere#11272]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by Yuesd** [comment]
Warning：Can not route tables for [pg_database], please make sure the tables are in same schema
using config-sharing.yml

**Comment by terrymanu** [comment]
Hi, can you provide more details?
