### ISSUE TITLE
Remove test only constructor of SelectStatementContext

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11270]
The first constructor of SelectStatementContext are used for test case only.

Please refactor the test cases to use the second constructor and remove the first one.

**Comment by LeeGuoPing** [comment]
May I do this one?

**Comment by terrymanu** [comment]
Go ahead please

**Comment by LeeGuoPing** [comment]
I met some troubles. one is the second constructor when the orderByContext has no elements but the groupByContext has some elements. it will add the groupByContext's elements as orderByContext's auto. In this case, I not found a solution to solve this problem. this method "assertBuildGroupByMemoryMergedResultWithMySQLLimit" has this prolems!
![image](https://user-images.githubusercontent.com/35389145/125615788-c4460846-2b04-4d56-9096-b1332c1b40c7.png)

**Comment by LeeGuoPing** [comment]
And, the other problem is when the test case is Oracle, in the "createPaginationContext" method called a method is

![image](https://user-images.githubusercontent.com/35389145/125617293-750ac4f8-f1bb-4e58-a2a8-3e669f36a1f1.png)

oracle is not support, to run the test case 'assertBuildIteratorStreamMergedResultWithOracleLimit' successfully. I write so long code, My idea is right? sorry, I have not read the whole code of this project

 @Test
    public void assertBuildIteratorStreamMergedResultWithOracleLimit() throws SQLException {
        ShardingDQLResultMerger resultMerger = new ShardingDQLResultMerger(DatabaseTypeRegistry.getActualDatabaseType("Oracle"));
        Map<String, ShardingSphereMetaData> metaDataMap = new HashMap<>();
        ShardingSphereMetaData metaData = mock(ShardingSphereMetaData.class);
        when(metaData.getSchema()).thenReturn(schema);
        metaDataMap.put(DefaultSchema.LOGIC_NAME, metaData);
        OracleSelectStatement selectStatement = (OracleSelectStatement) buildSelectStatement(new OracleSelectStatement());
        ProjectionsSegment projectionsSegment = mock(ProjectionsSegment.class);
        when(projectionsSegment.getStartIndex()).thenReturn(0);
        when(projectionsSegment.getStopIndex()).thenReturn(0);
        when(projectionsSegment.isDistinctRow()).thenReturn(false);
        when(projectionsSegment.getProjections()).thenReturn(Collections.emptyList());
        selectStatement.setProjections(projectionsSegment);

        LimitSegment limitSegment = mock(LimitSegment.class);
        when(limitSegment.getOffset()).thenReturn(Optional.of(new NumberLiteralRowNumberValueSegment(0, 0, 1, true)));
        when(limitSegment.getRowCount()).thenReturn(Optional.empty());
        WhereSegment whereSegment = mock(WhereSegment.class);

        BinaryOperationExpression binaryOperationExpression = mock(BinaryOperationExpression.class);
        when(binaryOperationExpression.getLeft()).thenReturn(new ColumnSegment(0, 0, new IdentifierValue("row_id")));
        when(binaryOperationExpression.getRight()).thenReturn(new LiteralExpressionSegment(0, 0, 1));
        when(binaryOperationExpression.getOperator()).thenReturn(">=");
        when(whereSegment.getExpr()).thenReturn(binaryOperationExpression);
        selectStatement.setWhere(whereSegment);

        SubqueryTableSegment subqueryTableSegment = mock(SubqueryTableSegment.class);
        SubquerySegment subquerySegment = mock(SubquerySegment.class);
        SelectStatement subSelectStatement = mock(SelectStatement.class);
        ProjectionsSegment subProjectionsSegment = mock(ProjectionsSegment.class);
        TopProjectionSegment topProjectionSegment = mock(TopProjectionSegment.class);
        when(topProjectionSegment.getAlias()).thenReturn("row_id");
        when(subProjectionsSegment.getProjections()).thenReturn(Collections.singletonList(topProjectionSegment));
        when(subSelectStatement.getProjections()).thenReturn(subProjectionsSegment);
        when(subquerySegment.getSelect()).thenReturn(subSelectStatement);
        when(subqueryTableSegment.getSubquery()).thenReturn(subquerySegment);
        selectStatement.setFrom(subqueryTableSegment);
        SelectStatementContext selectStatementContext1 = new SelectStatementContext(metaDataMap, Collections.emptyList(), selectStatement, DefaultSchema.LOGIC_NAME);

        MergedResult actual = resultMerger.merge(createQueryResults(), selectStatementContext1, buildSchema());
        assertThat(actual, instanceOf(RowNumberDecoratorMergedResult.class));
        assertThat(((RowNumberDecoratorMergedResult) actual).getMergedResult(), instanceOf(IteratorStreamMergedResult.class));
    }
