### ISSUE TITLE
Sharding-JDBC Poor performance, need to Improve.

### ISSUE THREAD

**Issue by nanzheng** [apache/shardingsphere#11281]
### Env
Version：shardingsphere 4.0.1
Test tool: jmeter 5.3
Test Case: shardingsphere benchmark 4.1.1
Database ：mysql
Threads: 10
Each thread loops: 1000000

### Test cases
Case A(JDBC): select * from a where a.aa= 'ciphertext' and a.bb='ciphertext';
Case B(Sharding-JDBC): select * from a where a.aa= 'plaintext' and a.bb='plaintext';

### Result diagram
JDBC base compare profiler output [Case A](https://github.com/nanzheng/ShardingSphere-Oracle-Test/blob/main/20210712-152815.svg)

sharding-jdbc base compare profiler output [Case B](https://github.com/nanzheng/ShardingSphere-Oracle-Test/blob/main/20210712-152322.svg)

### Summary
As you can see
 from these two diagram， there is about 35% performance loss where i use two encryption filed as query condition .

**Comment by terrymanu** [comment]
All improvements are finished.
