### ISSUE TITLE
Integrate the Hikari metrics to Prometheus

### ISSUE THREAD

**Issue by dachuan9e** [apache/shardingsphere#11304]
Integrate the Hikari metrics to Prometheus.

 We can get the runtime data of Hikari pool for analyzing the performance when queries happen.

**Comment by dachuan9e** [comment]
Here are different ways to integrate the metrics. These ways can be used by integrating any metrics other than HikariCP metrics.
1. Use the java agent way
2.Use the modular code way

**Comment by JooKS-me** [comment]
> Here are different ways to integrate the metrics. These ways can be used by integrating any metrics other than HikariCP metrics.
> 
> 1. Use the java agent way
>    2.Use the modular code way

Hi @dachuan9e , I think you'd better use the java agent way, which is a module specifically for observability.

**Comment by dachuan9e** [comment]
Right now we only do some metrics or statistics by java agent. It is temporary. We will support querying runtime data by  distSQL next. The plan is to do some necessary data collect in proxy. It will provides api to distSQL and agent to do better exports. It also will reduce the complexity of implement by agent.

**Comment by menghaoranss** [comment]
Completed.
