### ISSUE TITLE
Customize ShardingAlgorithm cannot get Bean from Spring

### ISSUE THREAD

**Issue by Ryan-Miao** [apache/shardingsphere#11318]
## Question

I use standard table strantegy to sharding. My class implements PreciseShardingAlgorithm, Cannot get anything from Spring context beacase of is not the same class loader?

中文：

我自定义了分片策略，在实现的PreciseShardingAlgorithm调用Spring Context，调用静态类的静态成员变量， 都是空。我想要分片策略可以查询redis等其他介质货主分片， 但sharding加载的自定义策略不能获取其他静态对象。

```

public class SkuDbPreciseShardingAlgorithm implements PreciseShardingAlgorithm<String> {

    private static final Logger LOGGER = LoggerFactory.getLogger(SkuDbPreciseShardingAlgorithm.class);

    /**
     * 分库分表
     *
     * @param dsNameList    可选db列表
     * @param shardingValue 货主编码
     * @return ds
     */
    @Override
    public String doSharding(Collection<String> dsNameList, PreciseShardingValue<String> shardingValue) {
        String companyCode = shardingValue.getValue();
  //  这里获取的是null,  静态方法返回值null。 但我实际上在springboot启动后插入了路由
        ShardingRoute route = SkuRouteRepository.getRouteMap(companyCode);
        if (route != null) {
            String dbName = route.getDbNo();
            if (StringUtils.isNoneBlank(dbName) && dsNameList.contains(dbName)) {
                return dbName;
            }
        }

        LOGGER.error("没有找到配置的分片：{}", companyCode);
        throw new UnsupportedOperationException();
    }
}

```

**Comment by strongduanmu** [comment]
@Ryan-Miao You can try to use the Hint for routing. For more information, please refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/hint/).

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
