### ISSUE TITLE
ShardingSphere-Proxy startup document has mistakes

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11317]
Hi,
     I found a documentation error. 
    Address url: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/usage/startup/
    ext-lib are right, lib-ext are not right.  it ’s  need correction.

**Comment by yx9o** [comment]
I'll do it

**Comment by strongduanmu** [comment]
@yx9o Welcome.

**Comment by yx9o** [comment]
fixed in #11335
