### ISSUE TITLE
Can complex queries be supported by using only the read-write separation function? Is read write separation also based on rewriting SQL?

### ISSUE THREAD

**Issue by ShenAoScript** [apache/shardingsphere#11325]
Can complex queries be supported by using only the read-write separation function? Is read write separation also based on rewriting SQL?

Old projects should support read-write separation. It contains a large number of complex queries. Can it be used in this scenario?

**Comment by strongduanmu** [comment]
@ShenAoScript Read-write splitting relies on SQL parsing, you can upgrade to version `5.0.0-beta`, SQL parsing has done a lot of optimization.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
