### ISSUE TITLE
ShardingSphere plans to cite Hint through special notation in SQL, When is this feature ready to start？ 

### ISSUE THREAD

**Issue by MingxingLAI** [apache/shardingsphere#11331]
## Question

* Apache ShardingSphere also plans to cite Hint through special notation in SQL, so that users can use that function in a more transparent way.
* Can you give me some hints, let me try to implement this function

**Comment by strongduanmu** [comment]
@MingxingLAI There is no official plan yet, and you are very welcome to implement this feature.

**Comment by tristaZero** [comment]
Hi could you give more explanation on this feature? What does HINT means?

**Comment by tristaZero** [comment]
It will be appreciated if you can give some examples.

**Comment by MingxingLAI** [comment]
Hi，tristaZero，I quote this question from your official documentation，see [here](https://shardingsphere.apache.org/document/current/en/features/sharding/concept/hint/)


I understand the hint syntax like [this](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html). for example:

```SQL
SELECT /*+ NO_RANGE_OPTIMIZATION(t3 PRIMARY, f2_idx) */ f1
  FROM t3 WHERE f1 > 30 AND f1 < 33;
SELECT /*+ BKA(t1) NO_BKA(t2) */ * FROM t1 INNER JOIN t2 WHERE ...;
SELECT /*+ NO_ICP(t1, t2) */ * FROM t1 INNER JOIN t2 WHERE ...;
SELECT /*+ SEMIJOIN(FIRSTMATCH, LOOSESCAN) */ * FROM t1 ...;
EXPLAIN SELECT /*+ NO_ICP(t1) */ * FROM t1 WHERE ...;
SELECT /*+ MERGE(dt) */ * FROM (SELECT * FROM t1) AS dt;
INSERT /*+ SET_VAR(foreign_key_checks=OFF) */ INTO t2 VALUES(2);
```

**Comment by tristaZero** [comment]
Hi @MingxingLAI ,

Thanks for your explanation. That will be a good feature. Actually, we have a plan to do such things. I'd welcome you to join!
@RaigorJiang Could you look at this one and get @MingxingLAI  involved?

**Comment by tristaZero** [comment]
@MingxingLAI BTW, are you interested in other issues currently? All the issues labeling with `OSD` are ready to be assigned. Have a good day.

**Comment by RaigorJiang** [comment]
This feature is great! But I think we still need more time to think and make plan.
@MingxingLAI  if you have good ideas, please feel free to put forward them, thank you!

**Comment by RaigorJiang** [comment]
Hi all, there is already a new issue to deal with sql hint, so I will close this one.
Please refer to #13771.
