### ISSUE TITLE
Can't find index exception occur when execute select statement with order by expression

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#11338]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

execute success

### Actual behavior

```sql
SELECT * FROM t_order ORDER BY id - 1;
ERROR 1999 (C1999): Unknown exception: [Can't find index: org.apache.shardingsphere.infra.binder.segment.select.orderby.OrderByItem@45bcc494]
```

**Comment by MingxingLAI** [comment]
Hi，I am studying ShardingSphere recently. I don’t quite understand this piece of logic, why this modification can fix this problem, can you explain it?

Does this modification solve similar problems？ like this:

```SQL
select * from t_order order by abs(user_id);
```

**Comment by strongduanmu** [comment]
> Hi，I am studying ShardingSphere recently. I don’t quite understand this piece of logic, why this modification can fix this problem, can you explain it?
> 
> Does this modification solve similar problems？ like this:
> 
> ```sql
> select * from t_order order by abs(user_id);
> ```

@MingxingLAI Because in a distributed scenario, we need to ensure that the results are in order, and we need to sort and merge the ordered results on different data nodes. At this time, we need to take out the field value of order by for sorting. However, query results may not contain the field value of the order by, so it needs to be added when rewriting. The query statement that contains shorthand is not correct when dealing with rewriting.
