### ISSUE TITLE
5.0.0-alpha，User defined table splitting algorithm can not work

### ISSUE THREAD

**Issue by Hmz3192** [apache/shardingsphere#11330]
## Version
5.0.0-alpha
## Question

The YML file and custom algorithm are shown in the figure. Why can't the configured custom algorithm take effect and still be full routing?
I have checked the user manual and other issues. I can't get help. Please check it for me. If my configuration is wrong, can you help me point out.Thank you

![yml1](https://user-images.githubusercontent.com/26765797/125601121-c47ca809-935b-4bf9-80c3-97db9587792e.jpg)
![yml](https://user-images.githubusercontent.com/26765797/125600127-649d4386-a44e-4b31-933e-c0e468333caf.jpg)
![algorithm](https://user-images.githubusercontent.com/26765797/125600118-fb75d3b0-6329-4704-97f4-8cd2f44091c5.jpg)
![result](https://user-images.githubusercontent.com/26765797/125600122-3fd43105-ea36-436a-afcd-4895f905684f.jpg)

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by tuichenchuxin** [comment]
@Hmz3192  Can you provide a demo example for me to try?

**Comment by Hmz3192** [comment]
> @Hmz3192 Can you provide a demo example for me to try?
Here is my demo link
https://github.com/Hmz3192/QuickStartOfShardingSphereJDBC-main

**Comment by strongduanmu** [comment]
@Hmz3192 Can you try version 5.0.0-beta? Maybe this issue has been fixed.

**Comment by tuichenchuxin** [comment]
@Hmz3192 
I found you use CLASS_BASED.
ShardingSphere 5.0.0-alpha was released at 2020-11-13, but class based sharding algorithm was merged at 2020-12-07
in #8508.
So please try the latest version 5.0.0-beta, thank you.

**Comment by Hmz3192** [comment]
Thank you,i fix it

**Comment by Superainbower** [comment]
Hi, Hmz
Could you share your demo,  Thanks a lot!
