### ISSUE TITLE
Config  actual-data-nodes

### ISSUE THREAD

**Issue by Superainbower** [apache/shardingsphere#11347]
## Question

**For English only**, other languages will not accept.
Hi, i have a question about how to config  actual-data-nodes ( table name is : order、order_0、order_1)
my config like this : actual-data-nodes=ds.order_${[0,1]} 
and implements StandardShardingAlgorithm and return "order",  but i got  "Route table order does not exist"
so any one could tell me how to config , or is it support now?

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
@Superainbower You can refer official [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/) for detailed information.

**Comment by RaigorJiang** [comment]
Hi @Superainbower 
You can also refer to the [example](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases-tables.yaml) .

**Comment by RaigorJiang** [comment]
`actual-data-nodes=ds.order_${[0,1]} `

change to 

`actual-data-nodes=ds.t_order_${0..1}`

**Comment by Superainbower** [comment]
Thanks, i find it

**Comment by RaigorJiang** [comment]
Hi @Superainbower 
If your problem is solved, can we close this issue?

**Comment by Superainbower** [comment]
HI,@RaigorJiang
The problem is solved, Thanks very much!
