### ISSUE TITLE
aliyun rds proxy error

### ISSUE THREAD

**Issue by ssxg** [apache/shardingsphere#11367]
我用sharingsphere proxy（版本为5.0.0beta）以encrypt方式代理一个阿里云的rds（mysql 5.7），proxy服务启动正常
[INFO ] 2021-07-16 17:00:24.523 [main] o.a.s.p.i.i.AbstractBootstrapInitializer - Database name is `MySQL`, version is `5.7.32-log`
[INFO ] 2021-07-16 17:00:34.710 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy start success.
但是通过DBeaver连接proxy时弹出错误
Unknown exception: [SQL checking failed. Error message: .]

**Comment by RaigorJiang** [comment]
Hi @ssxg 
What is your DBeaver's version?    
It is recommended that you use [MySQLWorkbench](https://www.mysql.com/products/workbench/) as the client.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
