### ISSUE TITLE
The init() method is not work when i implements standard sharding algorithm

### ISSUE THREAD

**Issue by Superainbower** [apache/shardingsphere#11361]
## Question

**For English only**, other languages will not accept.

Hi,  i define my sharding algorithm implements StandardShardingAlgorithm, and find init() method.
i do something in this method,but it doesn't work, some one could help me? 
Thanks a lot
eg:
![image](https://user-images.githubusercontent.com/35786966/125900814-ac10998a-deb8-42ca-8b65-c51448d2ccf5.png)

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
@Superainbower Which version do you use?

**Comment by Superainbower** [comment]
5.0.0-beta

**Comment by strongduanmu** [comment]
@Superainbower If you use the beta version, then you don’t need to implement the ClassBased algorithm yourself, because it’s already built in, you only need to configure it according to the documentation. You can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/built-in-algorithm/sharding/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%88%86%E7%89%87%E7%AE%97%E6%B3%95).

**Comment by Superainbower** [comment]
Because my table name like this: order、order2020、order2019, so i need to implement the ClassBased algorithm
i find in org.apache.shardingsphere.sharding.algorithm.sharding.classbased.ClassBasedShardingAlgorithm, it only create algorithm Instance, and don't called Instance.init(), this is reason why it doesn't work?
![image](https://user-images.githubusercontent.com/35786966/125931323-402b5c85-abb9-4728-b272-881a37d4a7fd.png)

**Comment by terrymanu** [comment]
@Superainbower Could you change the title for search friendly?

**Comment by Superainbower** [comment]
@terrymanu OK

**Comment by tuichenchuxin** [comment]
@Superainbower Cound you offer an example for me to reproduce?
I had tested 5.0.0-beta and did not find the problem you mentioned.

**Comment by Superainbower** [comment]
@tuichenchuxin 
Hi, Thanks for your reply！
I try your advise, add @Component at My sharding algorithm,  the init() will be called when start my project,
but my value still not right
![image](https://user-images.githubusercontent.com/35786966/126102449-565f7598-ad52-4266-a5d6-68a3f934d7b9.png)
Here is my demo link:
https://github.com/Superainbower/ShardingsphereDemo

**Comment by tuichenchuxin** [comment]
@Superainbower I have tested your demo, ```init()``` is not useful.
Actually,```@component``` should not add.
Adding this annotation will only make spring initialize the call in advance, but the subsequent shardingsphere will still initialize the class again, but shardingsphere does not call the init() method, so the init() method is indeed invalid.
Thank you for raising this question. We will consider this issue.
