### ISSUE TITLE
‘select @@character_set_results’ returns incorrect values

### ISSUE THREAD

**Issue by aiprog** [apache/shardingsphere#11369]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

4.4.1

mysql5.5

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

proxy

### Expected behavior

‘select @@character_set_results’ should return correct values.

### Actual behavior

Always returns null, even after executes  ‘set character_set_results=utf8’ successfully. But ‘show session variables like character_set_results’ returns utf8.

**Comment by tuichenchuxin** [comment]
This problem does exist, I will follow it up.

**Comment by tristaZero** [comment]
@aiprog Hi thanks for your feedback. Please watch this issue for the @tuichenchuxin 's PR here.

**Comment by menghaoranss** [comment]
@tuichenchuxin will leave the PR  which fixed this issue here

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin 
Any update here? Could we finish this in 5.1.1?

**Comment by RaigorJiang** [comment]
Fixed in master.

<img width="418" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/efaf52eb-0bbb-4b43-947c-fb5f750ab275">
