### ISSUE TITLE
Adding Contributors Section in Readme

### ISSUE THREAD

**Issue by achalesh27022003** [apache/shardingsphere#11371]
## Feature Request

I would suggest that there should be a token of appreciation for all the contributors out there to this repository. Therefore, we can add a contributor's section in the documentation i.e. readme below. 

If permits, I would like to take on this issue under Open Source Day'21.

**Comment by terrymanu** [comment]
Good suggestion, anybody want to do this issue?

**Comment by LeeGuoPing** [comment]
I want to do it.

**Comment by LeeGuoPing** [comment]
Should I add all contributors to readme.md?

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.
