### ISSUE TITLE
Multi data source problem

### ISSUE THREAD

**Issue by hsw409328** [apache/shardingsphere#11392]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

Multi data source problem

When the table name is repeated, the latter will override the former

For example:

X0 data source , table name: A1

X1 data source,  table name: A1

During automatic routing, X1 data source will be executed and cannot be specified as x0 data source

Looking for solutions?

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by hsw409328** [comment]
debug :

package org.apache.shardingsphere.infra.rule.single;

@Getter
public final class SingleTableRule implements FeatureRule, SchemaRule {
    
    private final Collection<String> dataSourceNames;
    
    private final Map<String, SingleTableDataNode> singleTableDataNodes;

...
}

singleTableDataNodes  for Map. The key will be covered

**Comment by tristaZero** [comment]
Hi @hsw409328 ,

Thanks for your debugging. I suppose you're right? Before we decide to fix it, could you let me know why you want to have all the single tables with the same table name?

**Comment by hsw409328** [comment]
@tristaZero When I use multiple databases under the same data source, each database has a user table. When I use it in sharding JDBC, I will not be able to switch correctly.

**Comment by strongduanmu** [comment]
@hsw409328 If every database contains this table and has the same data, you can set it as a broadcast table.

**Comment by hsw409328** [comment]
@strongduanmu The data content is different

**Comment by Beyondeclipse** [comment]
Hi @hsw409328, since the data is different for the uses, how to find the correct database? Is it possible to treate table A1 as sharding-table and use some field like 'user_id' as sharding-key ?

**Comment by hsw409328** [comment]
@Beyondeclipse

 It can't be set like this.

Because different business user tables correspond to different system services. The problem of coverage can't be solved simply by slicing.

Can you provide methods like @ qualifier or @ datasource for setting?

**Comment by Beyondeclipse** [comment]
> @Beyondeclipse
> 
> It can't be set like this.
> 
> Because different business user tables correspond to different system services. The problem of coverage can't be solved simply by slicing.
> 
> Can you provide methods like @ qualifier or @ datasource for setting?

It is likely that shardingsphere should have unique table name. And adding a new field as sharding-key may be a easy way to use it.

**Comment by strongduanmu** [comment]
@hsw409328 The latest master branch adds a duplicate check to the single table. This can ensure that you find duplicate single tables in time and avoid routing errors.
```java
    public static Map<String, SingleTableDataNode> load(final DatabaseType databaseType, final Map<String, DataSource> dataSourceMap, final Collection<String> excludedTables) {
        Map<String, SingleTableDataNode> result = new HashMap<>();
        for (Entry<String, DataSource> entry : dataSourceMap.entrySet()) {
            Map<String, SingleTableDataNode> singleTableDataNodes = load(databaseType, entry.getKey(), entry.getValue(), excludedTables);
            singleTableDataNodes.keySet().forEach(each -> Preconditions.checkState(!result.containsKey(each), "Single table conflict, there are multiple tables `%s` existed.", each));
            result.putAll(singleTableDataNodes);
        }
        return result;
    }
```

**Comment by hsw409328** [comment]
@strongduanmu 
This is just a check and does not solve the problem of duplicate tables of multiple data sources

**Comment by hsw409328** [comment]
Preconditions.checkState(!result.containsKey(each), "Single table conflict, there are multiple tables `%s` existed.", each)

**Comment by strongduanmu** [comment]
@hsw409328 A single table must be unique in the same logical data source. If your multiple single tables have no relationship and the data is different, why not consider splitting them into multiple logical data sources?

**Comment by ccMoriarty** [comment]
I has similar question in ss-proxy (5.0.0 beta)

my dataSource like  'db_YYYYMM',   table like 'tb_dd'

in mysql , there are  'db_202107.tb_01'  and  'db_202108.tb_01'

when i start ss-proxy it tells me   'Single table conflict, there are multiple tables `tb_01` existed'.   

i want to shard by time , just like "2021-07-01 15:47:32"  to  `db_202107`.`tb_01`,   "2021-08-01 15:47:32"  to  db_202107`.`tb_01`   

how should i set it ?

**Comment by ccMoriarty** [comment]
why not use  'db.tb'  as  singleTableName ?

**Comment by tristaZero** [comment]
Hi @ccMoriarty 

> i want to shard by time , just like "2021-07-01 15:47:32" to db_202107.tb_01, "2021-08-01 15:47:32" to db_202108.tb_01

That way, it's suggested to configure a sharding table for both actual tables sharing the same name.
