### ISSUE TITLE
route result is wrong

### ISSUE THREAD

**Issue by vince7839** [apache/shardingsphere#11397]
I execute a SQL like this : "select * from demo_db where num=1 or num=2 and count=3"，
I config 2 dataSources : ds_0 and ds_1
table strategy : tb_${num % 2}，
database strategy : ds_${count % 2}
but route result only contains ds_1，following is actual SQL:
Actual SQL: ds_1 ::: select * from tb_1 where num = 1 or num=2 and count =3
Actual SQL: ds_1 ::: select * from tb_0 where num = 1 or num=2 and count =3
Version : 4.1.0

**Comment by dongzl** [comment]
Hi @vince7839 , for English only.

**Comment by vince7839** [comment]
@dongzl ，Hi,I’ve updated

**Comment by tristaZero** [comment]
@vince7839 Thanks for your question.
It looks a little wired. Would you mind trying the beta release for this case? We suggest you using 5.0.0-bete for your new production evn.
