### ISSUE TITLE
shardingsphere version and zookeeper version question

### ISSUE THREAD

**Issue by zupermanOK** [apache/shardingsphere#11393]
my shardingsphere version is 4.1.1
and my zookeeper server version is 3.6.3，but when my application starting ,so many exception .search from google,all anwsers is i should change my jar version about curator,but i tried 3.x,4.x, nothing changed and still wrong.

so ,what  zookeeper version does it correspond to shardingsphere 4.1.1

hope replay,thanks

**Comment by menghaoranss** [comment]
The version of curator for 4.1.1 is 2.10.0，zookeeper of 3.6.x is not supported，if you still need to use zookeeper with 3.6.3, please upgrade ShardingSphere to 5.x

**Comment by menghaoranss** [comment]
closed because no response any more
