### ISSUE TITLE
when can I get latest version of sharding-core(5.0.0) ?

### ISSUE THREAD

**Issue by ruyin-zh** [apache/shardingsphere#11406]
The version I used is 4.1.1 and this version has a problem which cost much time at analyzing table column and index. I viewed source code of 5.x and found problem had been fixed above. So I hope latest version as soon as possible.

**Comment by menghaoranss** [comment]
Version 5.0.0-beta has been released, you can try to upgrade

**Comment by ruyin-zh** [comment]
yes, I see, I hope to obtain the required dependencies through the maven, it's not a good idea to package and upload jars by myself.

**Comment by menghaoranss** [comment]
Search with `ShardingSphere` prefix in Maven repository

**Comment by ruyin-zh** [comment]
ok,thx
