### ISSUE TITLE
The same datasource pool will be opened twice when proxy start

### ISSUE THREAD

**Issue by dachuan9e** [apache/shardingsphere#11416]
[INFO ] 2021-07-20 18:26:57.981 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Starting...
[INFO ] 2021-07-20 18:27:08.017 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Start completed.
[INFO ] 2021-07-20 18:27:08.017 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Starting...
[INFO ] 2021-07-20 18:27:18.050 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Start completed.
[INFO ] 2021-07-20 18:27:18.050 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Shutdown initiated...
[INFO ] 2021-07-20 18:27:18.051 [main] com.zaxxer.hikari.HikariDataSource - sharding_db/ds_1 - Shutdown completed.

**Comment by TeslaCN** [comment]
This may be related to `org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.decorator.HikariJDBCParameterDecorator`.

**Comment by dachuan9e** [comment]
Not this.  Here it create datasource using these codes.  I will fixed. And also here is another problem that the datasource hasn't specific pool name.

private static Map<String, DataSource> createDataSources(final String schemaName, final Map<String, DataSourceParameter> dataSourceParameters) {
        Map<String, DataSource> result = new LinkedHashMap<>(dataSourceParameters.size(), 1);
        for (Entry<String, DataSourceParameter> entry : dataSourceParameters.entrySet()) {
            DataSource dataSource = JDBCRawBackendDataSourceFactory.getInstance().build(schemaName + "/" + entry.getKey(), entry.getValue());
            if (null != dataSource) {
                result.put(entry.getKey(), dataSource);
            }
        }
        return result;
    }

    public DataSource build(final String dataSourceName, final DataSourceParameter dataSourceParameter) {
        HikariConfig config = new HikariConfig();
        .......
        DataSource result;
        try {
            result = new HikariDataSource(config);
