### ISSUE TITLE
mysql case when statement parse error

### ISSUE THREAD

**Issue by sinoryan** [apache/shardingsphere#11418]
shardingsphere version:4.1.1

mybatis sql  as follow:

SELECT id,
        (CASE
        WHEN LENGTH(TRIM(name_en))<![CDATA[>]]>0 THEN CONCAT(name_cn,'-',name_en)
        ELSE name_cn
        END) AS text,account_no FROM `user`
        WHERE status=1 xxxx

debug screenshot
![QQ图片20210720191809](https://user-images.githubusercontent.com/8133974/126315353-5cae0c08-6338-4d2e-b96f-c3a47b28b6c3.png)
![QQ图片20210720191816](https://user-images.githubusercontent.com/8133974/126315357-4ca4798f-63e3-4db5-bc3c-954b3ef6d86c.png)

exception:
line 3:25 no viable alternative at input '(CASEWHENLENGTH(TRIM(name_en'

**Comment by strongduanmu** [comment]
@sinoryan Can you try the latest `5.0.0-beta`?

**Comment by sinoryan** [comment]
@strongduanmu 

> @sinoryan Can you try the latest `5.0.0-beta`?
ok, i will try it in next time.

**Comment by tuichenchuxin** [comment]
@strongduanmu I had tried this sql on master branch , It's supported now.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it.
