### ISSUE TITLE
Add more usages for DistSQL

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#11410]
Refer to [The Usage of DistSQL for Sharding](https://shardingsphere.apache.org/document/current/en/features/dist-sql/usage/sharding-rule/)  to add more usages for DistSQL:

- [ ] Encrypt
- [ ] Readwrite Splitting
- [ ] Database Discovery

Notes:
- Base on version 5.0.0-beta
- Use MySQL Client with black background
- Keep the document style uniform

**Comment by yinyanghuafa** [comment]
please let me try.

**Comment by RaigorJiang** [comment]
@yinyanghuafa 
Sorry for the late reply, are you still willing to try?

**Comment by lanchengx** [comment]
@RaigorJiang please let me try.
