### ISSUE TITLE
When DataSourceChangedEvent happens, the old connection pool will be closed and then the new connection pool will be loaded

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#11424]
## Bug Report

**5.0.0-alpha ShardingSphere-Proxy**
### Expected behavior
**Replace the connection pool in the context with the new connection pool, and then close the old connection pool losslessly**
### Actual behavior
**The old connection pool was closed first, causing all SQL in the current library to fail before the new connection pool was ready**
![image](https://user-images.githubusercontent.com/20919316/126428722-b6102aab-f9db-4f9e-914a-135b9d1d1190.png)

**Comment by menghaoranss** [comment]
Refactor by #11642
