### ISSUE TITLE
It doesn't work, throws Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by zhangwangren** [apache/shardingsphere#11422]
## Question
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-beta</version>
        </dependency>

My custom Algorithm is work, and return success.  but the sql throw a Exception:Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0;   
sql: SELECT * FROM reservoir_water_rain_data WHERE 1=1 AND rwd.TM BETWEEN #{timeFrom} AND #{timeTo}
 
When I change to SELECT * FROM reservoir_water_rain_data_01 WHERE 1=1 AND rwd.TM BETWEEN #{timeFrom} AND #{timeTo}
 is work.
![image](https://user-images.githubusercontent.com/32890060/126415064-f9724151-4daa-4228-92b2-15ef3dfe5ddf.png)

Does anyone know why？pls tell me, thanks

**Comment by penuel-leo** [comment]
fixed?
