### ISSUE TITLE
PGSQL Join Query SQL Rewrite Exception

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11429]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
![image](https://user-images.githubusercontent.com/76552510/126452999-c0958165-7add-4d0b-b1ec-41b8fcaf0945.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/126453028-204bc990-f003-4826-bc2c-36e35f402bc7.png)

### Reason analyze (If you can)
Rewrite Exception

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Recreating the environment through [configuration files](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/docker/tbl/postgresql/proxy/conf/config-tbl.yaml) and [init.sql](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/tbl/init-sql/postgresql/init.sql)

Exectue `SELECT * FROM t_user u INNER JOIN t_user_item m ON u.user_id=m.user_id`

**Comment by tuichenchuxin** [comment]
@JiekerTime inner join in pgsql is not supported yet, it will be supported soon.

**Comment by JiekerTime** [comment]
> @JiekerTime inner join in pgsql is not supported yet, it will be supported soon.

OK, then I will close the PG-related tests for now

**Comment by tristaZero** [comment]
@tuichenchuxin @strongduanmu Do we have any plan to fix it?

**Comment by tuichenchuxin** [comment]
> @tuichenchuxin @strongduanmu Do we have any plan to fix it?

I'll try to support it next week.

**Comment by tuichenchuxin** [comment]
@JiekerTime I found that, this error is due to the alias word `u`.
Such as `select * from t_user u` can't be paser well.
Replace the word `u` to another word can be ok.

**Comment by tuichenchuxin** [comment]
![image](https://user-images.githubusercontent.com/86938616/127499038-110515f0-bbc5-462b-b1d8-b1c6a207fe5c.png)
baseRule.g4 has rule conflict.
We will fix this later.

**Comment by JiekerTime** [comment]
> @JiekerTime I found that, this error is due to the alias word `u`.
> Such as `select * from t_user u` can't be paser well.
> Replace the word `u` to another word can be ok.

Well, the parsing was correct when I was operating the native database, so I think it might be a bug and we'll fix it right?

**Comment by tuichenchuxin** [comment]
> Well, the parsing was correct when I was operating the native database, so I think it might be a bug and we'll fix it right?

@JiekerTime Yes, it's a bug, we'll fix it later.

**Comment by JiekerTime** [comment]
> > Well, the parsing was correct when I was operating the native database, so I think it might be a bug and we'll fix it right?
> 
> @JiekerTime Yes, it's a bug, we'll fix it later.

Okay, looking forward to your good news.

**Comment by JiekerTime** [comment]
problem solved ! so closed.
