### ISSUE TITLE
mvn compile failed!! master code

### ISSUE THREAD

**Issue by hsw409328** [apache/shardingsphere#11427]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

master 

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

jdbc

### Expected behavior

compile sucess and run sucess

### Actual behavior

![image](https://user-images.githubusercontent.com/11609045/126444978-b6e205d8-3675-4879-8820-d800a23a019f.png)

package org.apache.shardingsphere.sharding.distsql.parser.core;

/**
 * SQL statement visitor for sharding rule.
 */
public final class ShardingRuleSQLStatementVisitor extends ShardingRuleStatementBaseVisitor<ASTNode> implements SQLVisitor {
.....
    }

**Comment by TeslaCN** [comment]
@hsw409328 Please read the faq.
https://shardingsphere.apache.org/document/current/en/others/faq/
