### ISSUE TITLE
all password in proxy is plainttext config, there are some security problems in production environment

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#11434]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no
### Describe the feature you would like.
password can be encrypt config in proxy, and we can define encrypt algorithm myself.

**Comment by terrymanu** [comment]
Does anyone interest this issue?

**Comment by sandynz** [comment]
@justbk2015 feedback no more PR for now, it could be closed.
