### ISSUE TITLE
5.0.0-beat still start slowly; ColumnMetaDataLoader 

### ISSUE THREAD

**Issue by qbmiller** [apache/shardingsphere#11436]
5.0.0-beta
springboot start slow  still like 4.0
org.apache.shardingsphere.infra.metadata.schema.builder.loader.ColumnMetaDataLoader#load

scan every table multi every field;

**Comment by tuichenchuxin** [comment]
@qbmiller Thanks for the feedback, we will follow up to solve this problem.

**Comment by qbmiller** [comment]
this code block. sometimes run ; 
sometimes not run this code block;   haven't looked closely yet

**Comment by xueshiji** [comment]
@qbmiller @tuichenchuxin 9 tables but 10 minutes![QQ截图20210802180010.png](https://user-images.githubusercontent.com/32958628/127843991-3f7f73d9-4917-49ae-a98f-bf79299c078d.png)

**Comment by qbmiller** [comment]
> this code block. sometimes run ;
> sometimes not run this code block; haven't looked closely yet
> 
> rewrite ColumnMetaDataLoader#load add log.info(); can saw the problem; scan every table
> eg: we have 20tables for 1~1000 shared; will scan 20*1000=20000 times metadata
> 
> spring.shardingsphere.props.check-table-metadata-enabled=false default false; not work for that

our problem;  post module config all logic tables. but chat module only config one logic table , 
so chat module load other tables as normal tables for 1000 times

**Comment by tuichenchuxin** [comment]
@qbmiller 
Thanks for the feedback, you can try the latest code we have solved the problem of slow loading.

**Comment by tuichenchuxin** [comment]
Closed due to no reply for a long time.
