### ISSUE TITLE
One of datasources failed to build, but the proxy still start successfully

### ISSUE THREAD

**Issue by sccc803** [apache/shardingsphere#11438]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When one of datasources failed to build, the proxy should start failed.

### Actual behavior
![image](https://user-images.githubusercontent.com/43317745/126467045-7c7be3ef-a02c-4661-826d-62c95f8a36aa.png)
When the first (ordered in the configuration file) datasouce built successfully, proxy will start successfully whenever other datasouce built failed.

### Reason analyze (If you can)
In the method org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.factory.JDBCRawBackendDataSourceFactory#build
![image](https://user-images.githubusercontent.com/43317745/126470638-55e7110c-b3f1-4fac-ba46-9c49be5a7883.png)
When the excpiton occured, return null whithout throwing any exception.
![image](https://user-images.githubusercontent.com/43317745/126471052-f00badb3-0132-4bd0-9c4f-ad21240d6b60.png)
The datasource will not be put in dataSourceMap, and the process will continue whithout any excption.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Set wrong password to the second datasource in configuration file, eg. 
![image](https://user-images.githubusercontent.com/43317745/126471845-98bdcdab-47e8-4990-9e30-116b807df9cc.png)
Then start proxy.

**Comment by dachuan9e** [comment]
https://github.com/apache/shardingsphere/pull/11432

Please check if the latest code in master branch has fixed this issue. @

**Comment by sccc803** [comment]
> #11432
> 
> Please check if the latest code in master branch has fixed this issue. @

Yes, it has been fixed.
