### ISSUE TITLE
5.0.0_beta version start errror，Initialization of bean ShardingSphereAutoConfiguration failed，NullPointerException

### ISSUE THREAD

**Issue by Hmz3192** [apache/shardingsphere#11433]
## Which version of ShardingSphere did you use?
shardingsphere-jdbc-core 5.0.0-beta

## Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

## Expected behavior
springboot service can startup

## Actual behavior
springboot service can not startup

## Methods already referred
  1. json format column in the table [#11047] [#10900] [#11363],etc.
  2. Refer to the official example [#official example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example)
  3. set ```check-table-metadata-enabled: false```
## Pictures
My tables’ screenshot and error:
![image](https://user-images.githubusercontent.com/26765797/126461522-4556e72b-2f01-430f-918a-95a0fbf61332.png)
![image](https://user-images.githubusercontent.com/26765797/126461552-8bc9ebff-15d5-4db7-b7c6-2a821a6fc754.png)
![image](https://user-images.githubusercontent.com/26765797/126461603-1ecf8acd-68ee-4c74-a326-6daedc6f2ce2.png)

My demo link:
[#demo](https://github.com/Hmz3192/QuickStartOfShardingSphereJDBC-main)

Please help me point out my mistakes. Thank you very much！！！

**Comment by tuichenchuxin** [comment]
@Hmz3192 Thank you for feedback.We have noticed this problem and will resolve it later.

**Comment by xiefangzhenz** [comment]
I have same problem

**Comment by iCloudys** [comment]
I have same problem

**Comment by tuichenchuxin** [comment]
> I have same problem

This problem has been soloved in this [pr ](https://github.com/apache/shardingsphere/pull/11414)
on master branch.

**Comment by RaigorJiang** [comment]
Fixed in https://github.com/apache/shardingsphere/pull/11414.
