### ISSUE TITLE
java.sql.Timestamp cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by Superainbower** [apache/shardingsphere#11448]
## Bug Report**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
i got some error when use 5.0.0-RC1-SNAPSHOT although it's work well in  5.0.0-beta

### Actual behavior
SQL: select count(*) from (select car,count(*) as cnt from table group by car) a
![image](https://user-images.githubusercontent.com/35786966/126596688-9a1d784d-22c2-4263-82ab-714fb2d5542d.png)

**Comment by strongduanmu** [comment]
Duplicate with #10760.
