### ISSUE TITLE
Multiple-Table Delete report error

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11449]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
DELETE ta 
FROM
	FI_TableA ta
	JOIN FI_TableB tb ON tb.id = ta.id 
WHERE
	ta.CODE = '1'
### Actual behavior
Cause: org.apache.shardingsphere.infra.exception.ShardingSphereException: Cannot support Multiple-Table for '[FI_TableA,FI_TableB, ta]'.
### Reason analyze (If you can)
The alias was incorrectly resolved into a table

**Comment by Yule-Momoko** [comment]
DELETE ta
FROM
	FI_TableA ta
	JOIN FI_TableB tb ON tb.id= ta.id
WHERE
	ta.code = '1'

**Comment by terrymanu** [comment]
Hi, The exception thrown with `Cannot support Multiple-Table for '[FI_TableA,FI_TableB, ta]'.` is expected exception.
Delete multiple table is unnecessary in sharding databases, the priority is pretty low.
We have opened the issue before, but nobody collect it. 
So I just close the issue, if any idea want to contribute, please give the design doc and the pull requests.
Thank you.

**Comment by Yule-Momoko** [comment]
Why can't this be solved？This deletion is my normal operation, but not what I expected

**Comment by Yule-Momoko** [comment]
My routing policy is  Hint

**Comment by Yule-Momoko** [comment]
@terrymanu
