### ISSUE TITLE
Naming problem of data source in HikariCP metrics

### ISSUE THREAD

**Issue by dachuan9e** [apache/shardingsphere#11451]
# Background
If we use agent to monitor the hikariCP metrics and export to the prometheus.  There are many data sources exposed by the data. However it can be identified by the value of  key "pool" as following.  As the proxy running the postfix number will increated if any data source created.  It makes the exporting data in prometheus can not know the pool belongs to which schema.  It seems to name the data source pool for the monitor metrics.

prometheus data:
```java
hikaricp_active_connections{pool="HikariPool-1",} 0.0
hikaricp_active_connections{pool="HikariPool-2",} 0.0
```

# problems or influence

The data source in proxy will be closed and opened during the running time. It makes it difficult to identify if no name.
Otherwise the metrics tracer is also named by pool name. Naming a data source can solve the problem but also has some 
influence if we can share the data source among different schemas. However proxy doesn't share the data source it will create different data source for different schema even the same ds name. At the same time naming the connection pool increases the complexity of code. We have to be careful to avoid potential issues in future.

hikaricp code:

```java 
   public void setMetricsTrackerFactory(MetricsTrackerFactory metricsTrackerFactory)
   {
      if (metricsTrackerFactory != null) {
         this.metricsTracker = new MetricsTrackerDelegate(metricsTrackerFactory.create(config.getPoolName(), getPoolStats()));
      }
      else {
         this.metricsTracker = new NopMetricsTrackerDelegate();
      }
   }
```
# Question
At first, we need to confirm that it should provide named pool for prometheus for exporting data. If there is no this requirement we can avoid the complexity.

**Comment by RaigorJiang** [comment]
For the monitoring system, `poolName` is necessary, otherwise the operator will not be able to identify which data source the monitoring indicators come from.

And here is a question:
When the same data source is configured in different schemas, proxy will create two different connection pools for it, which is a little waste of resources.

**Comment by dachuan9e** [comment]
Right now users can provide property named 'poolName' in configuration file.  It will set the data source pool name as the property value. The following is the example:

# Example

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    poolName: sharding.ds_0

# Attention & Suggestion
If the poolName is the same shared by different data source it will cause the metrics data errors.
We recommended that it should keep the name provided by 'poolName' unique all the proxy.
