### ISSUE TITLE
select * from db.tb  need to  selecte database first

### ISSUE THREAD

**Issue by ccMoriarty** [apache/shardingsphere#11454]
### Which version of ShardingSphere did you use?

apache-shardingsphere-5.0.0-beta-shardingsphere-proxy

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Example codes for reproduce this issue (such as a github link).

![image](https://user-images.githubusercontent.com/35559210/126617098-1bda4355-5a00-4a4b-8523-738ee6476ec0.png)
![image](https://user-images.githubusercontent.com/35559210/126617112-a82253a8-2944-4d80-88f9-a9587ac093e4.png)

when i use 'select * from db.tb', it tell me No database selected; but it ok in MySQL

why must selecte database first

version: apache-shardingsphere-5.0.0-beta-shardingsphere-proxy

**Comment by RaigorJiang** [comment]
Refer to https://github.com/apache/shardingsphere/issues/10673, I think it's not a problem.

**Comment by strongduanmu** [comment]
@ccMoriarty You can try the master branch, sql with schema has already been supported.

**Comment by ccMoriarty** [comment]
@strongduanmu  thanks
