### ISSUE TITLE
 nested exception is org.apache.ibatis.executor.ExecutorException:

### ISSUE THREAD

**Issue by CTO-xk** [apache/shardingsphere#11455]

**Comment by zjcnb** [comment]
Hi, can you provide the ShardingSphere version and sql?

**Comment by CTO-xk** [comment]
版本是

><dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>
sql 是
SELECT
	res.id,
	res.parent_id,
	res.resource_name,
	res.resource_type,
	res.resource_code,
	res.resource_url,
	res.sort,
	rid
FROM
	t_resource res
LEFT JOIN (
	SELECT
		res.id,
		rr.roid rid
	FROM
		t_resource res
	LEFT JOIN t_role_resource rr ON res.id = rr.reid
	WHERE
		res.parent_id = 0
	AND res.resource_type = '1'
	AND rr.roid = 1379400291016765441
	AND res.state = '1'
	AND res.is_delete = '0'
	AND rr.is_delete = '0'
	ORDER BY
		res.sort
) t ON res.id = t.id
WHERE
	res.parent_id = 0
AND res.resource_type = '1'
AND res.state = '1'
AND res.is_delete = '0'
AND res.application_code = 'agent'
ORDER BY
	res.sort

**Comment by CTO-xk** [comment]
> 你好，能提供ShardingSphere的版本和sql吗？

我在下面提供了

**Comment by zjcnb** [comment]
@CTO-xk  Please modify Chinese to English

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
