### ISSUE TITLE
Having is not supported

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11467]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
  : Logic SQL: SELECT
	cd 
FROM
	F_TABLEA 
WHERE
	ID = 'e79119bb8cd04ae584cb3e04299da3be' 
GROUP BY
	cd 
HAVING
	count( 1 ) > 0;
### Actual behavior
Actual SQL: ds24 ::: SELECT
	cd 
FROM
	F_TABLEA 
WHERE
	ID = 'e79119bb8cd04ae584cb3e04299da3be' 
GROUP BY
	cd 
;

**Comment by strongduanmu** [comment]
@Yule-Momoko The having statement is already supported in the master branch, but not yet in the beta version.

**Comment by Yule-Momoko** [comment]
@strongduanmu When will the version be updated？

**Comment by strongduanmu** [comment]
@Yule-Momoko Because the beta version has just been released, the next version will take some time.

**Comment by CheerwayRen** [comment]
> @Yule-Momoko The having statement is already supported in the master branch, but not yet in the beta version.

There happens to be a problem here. Why are the table having queries that do not use sharding tables also intercepted and can not get the correct results

**Comment by CheerwayRen** [comment]
> @Yule-Momoko Because the beta version has just been released, the next version will take some time.

There happens to be a problem here. Why are the table having queries that do not use sharding tables also intercepted and can not get the correct results
