### ISSUE TITLE
insert into tableA（id,cd）（select id,cd from tableB）Does not support

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#11469]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-betad
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
insert into tableA（id,cd）（select id,cd from tableB）Does not support

**Comment by RaigorJiang** [comment]
Please refer to [Supported SQL](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/#supported-sql-1):
> The table inserted and the table selected must be the same or bind tables.

**Comment by Yule-Momoko** [comment]
is bind tables

**Comment by RaigorJiang** [comment]
How about 
```sql
insert into tableA（id,cd）select id,cd from tableB
```
Do not use parentheses in query statements, like the example?    

> Please refer to [Supported SQL](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/#supported-sql-1):
> 
> > The table inserted and the table selected must be the same or bind tables.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
