### ISSUE TITLE
problems after change data store as raw in oracle

### ISSUE THREAD

**Issue by wuguowei19880907** [apache/shardingsphere#11475]
oracle database+spring boot 1.5+hibernate+sharding 5.0.0

I change the **EncryptAlgorithm** encrypt and decrypt method return bytes to store the encrypted data with **oracle raw type**.
![image](https://user-images.githubusercontent.com/19338820/126764950-b4a8e4f8-c2bc-49c4-bce2-7f4710120446.png)

when i execute update for insert data ,the error logs:
![image](https://user-images.githubusercontent.com/19338820/126765028-d47261a4-2bdf-4e13-b02f-f76c29ce6be2.png)

I think it is because that the bytes data insert not success ,but how to change the data type as bytes or raw

**Comment by terrymanu** [comment]
No plan to improve with oracle, I just set it as good amateur issue, does anyone want to fix it?

**Comment by cheese8** [comment]
Could you provide a simplified demo, i would try it later. @wuguowei19880907

**Comment by wuguowei19880907** [comment]
> Could you provide a simplified demo, i would try it later. @wuguowei19880907

You can use any demo with sql **select top 10 xxx from tablename**,if there is no mistake with sharding5.1.0,please tell me.
Thanks

**Comment by terrymanu** [comment]
The version is out of service, please try new version
