### ISSUE TITLE
Discuss scope of governance module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11502]
The scope of current governance module include `multiple Proxy/JDBC instances coordinate`, `disable data sources` and `circuit break`.

But disable data sources and circuit break features is belong to management scope, which should not depend on governance module. The scope of governance module should simplify to multiple instances coordinate only.

So, how about split disable data sources to readwrite-splitting module and split circuit break to kernel module (for now, may create a new management module in future)?

The governance module may rename to `cluster`, `coordinator` or `notification`.

Any suggestions?

**Comment by taojintianxia** [comment]
nowadays, shardingsphere get more and more modules, if one module become complex, this module devided into several modules. just like cells, modules grow up and keep on dividing. and code compile/build/download/debug .... become more and more complex too.

maybe , maybe some day, shardingshere will divide into several independent  PROJECTs ?

**Comment by totalo** [comment]
I think disabling data sources may not only be suitable for readwrite-splitting related functions, some projects may have similar requirements for dynamic data sources. Can a management module be abstracted? Separate each ability independently.

**Comment by terrymanu** [comment]
> nowadays, shardingsphere get more and more modules, if one module become complex, this module devided into several modules. just like cells, modules grow up and keep on dividing. and code compile/build/download/debug .... become more and more complex too.
> 
> maybe , maybe some day, shardingshere will divide into several independent PROJECTs ?

I am not sure for now, it is another topic.

**Comment by terrymanu** [comment]
> I think disabling data sources may not only be suitable for readwrite-splitting related functions, some projects may have similar requirements for dynamic data sources. Can a management module be abstracted? Separate each ability independently.

Sure, I just list the example. Because of disable data source is for readwrite-splitting only for now.
