### ISSUE TITLE
Navicat show “No database selected” when connect to ShardingSphere Proxy

### ISSUE THREAD

**Issue by vince7839** [apache/shardingsphere#11512]
Version:5.0.0-beta
I config 2 dataSource like following and launch ShardingSphere-Proxy，but when I try to connect it by Navicat，it failed and show "No database selected". 
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://localhost:3306/db_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://localhost:3306/db_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

**Comment by menghaoranss** [comment]
duplicate with #7141, please provide more stack logs.

**Comment by taojintianxia** [comment]
@menghaoranss please take a look a the response I did in this issue 
https://github.com/apache/shardingsphere/issues/11712

**Comment by RaigorJiang** [comment]
Fixed in https://github.com/apache/shardingsphere/issues/11994.
