### ISSUE TITLE
MySQL limit paging query bug, use 'limit 20, 10' but return 20 （Left join query）

### ISSUE THREAD

**Issue by trycache0828** [apache/shardingsphere#11536]
## Bug Report

When use LIMIT 0, 10, the query result is normal and the number of query result records is 10.

When use LIMIT 10, 10, the query result is normal and the number of query result records is 10.

But when use LIMIT 20, 10, the query result is incorrect and the number of query result records is 20

The limit statement has been rewritten

SQL printed by hibernate：SELECT * FROM XXX WHER XXX ORDER BY  XXX LIMIT 10 , 20

ShardingSphere Logic SQL: SELECT * FROM XXX WHER XXX ORDER BY  XXX LIMIT 10 , 20

### Which version of ShardingSphere did you use?

    
    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>shardingsphere-jdbc-core</artifactId>
        <version>5.0.0-beta</version>
        <exclusions>
            <exclusion>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-client</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

 ShardingSphere-JDBC

### Expected behavior

when use LIMIT 20, 10, the query result is incorrect and the number of query result records is 20.

### Actual behavior

 use LIMIT 20, 10, the query result  is normal and the number of query result records is 10.

### Reason analyze (If you can)

SQL parsing query merge result set is not considerate

**Comment by trycache0828** [comment]
@strongduanmu Already using 5.0.0-beta,how to solve this problem？https://github.com/apache/shardingsphere/issues/2419

**Comment by strongduanmu** [comment]
@trycache0828 I can't reproduce this problem, and from the information you provided, logic sql is a wrong sql, please check whether hibernate generates wrong logic sql.
