### ISSUE TITLE
Maven's third-party dependent packages depend on different versions of guava packages, which are incompatible with each other.

### ISSUE THREAD

**Issue by trycache0905** [apache/shardingsphere#11537]
Maven's third-party dependent packages depend on different versions of guava packages, which are incompatible with each other.

## ERROR
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V

## Description

Class: com.google.common.base.Preconditions

Jar: guava-29.0-jre.jar

## Dependency package

    
    
    <dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>shardingsphere-jdbc-core</artifactId>
        <version>5.0.0-beta</version>
        <exclusions>
            <exclusion>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-client</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

**Comment by terrymanu** [comment]
Please shade the dependencies if conflict.

**Comment by trycache0905** [comment]
您好！    您的邮件已收到，我会尽快处理！谢谢！    顺祝：工作顺利！
