### ISSUE TITLE
SQL checking failed

### ISSUE THREAD

**Issue by bai1986** [apache/shardingsphere#11550]
when i excuted a sql ，like show databases,in apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-proxy-bin，Errors are reported as follows
ERROR 1999 (C1999): Unknown exception: [SQL checking failed. Error message: .]
root@127.0.0.1((none)) 12:17>exit
The proxy does not report any error

My configuration is as follows：
**config-sharding.yaml**
schemaName: ProductDB

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB00?serverTimezone=UTC&useSSL=false
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB01?serverTimezone=UTC&useSSL=false
    username: shardingsphere
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  

  rules:
  - !SHARDING
    tables:
      Products_Core:
        actualDataNodes: ds_${0..7}.Products_Core
        keyGenerateStrategy:
          column: product_id
          keyGeneratorName: snowflake
        databaseStrategy:
          standard:
            shardingColumn: product_id
            shardingAlgorithmName: Products_Core_database_inline
      products_ddshop_category:
        actualDataNodes: ds_${0..7}.products_ddshop_category
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: ddshop_database_inline

    bindingTables:
      - Products_Core,products_ddshop_category
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      product_core_database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${product_id % 7}
      ddshop_database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${id % 7}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

**Comment by menghaoranss** [comment]
This seems to be the problem of authority, please confirm the users which configured in `server.yaml` are created in the actual database.

**Comment by mazhai** [comment]
I found that when I connected to Alibaba RDS
class MySQLPrivilegeHandler 
```
    private void addToPrivilegeTypesIfPresent(final boolean hasPrivilege, final PrivilegeType privilegeType, final Collection<PrivilegeType> target) {
        if (hasPrivilege) {
            target.add(privilegeType);
        }
    }
```
hasPrivilege property is always false
becase `resultSet.getBoolean()` methods always false

But there is no such problem when using mysql

**Comment by menghaoranss** [comment]
> @menghaoranss
> I found that when I connected to Alibaba RDS
> class MySQLPrivilegeHandler
> 
> ```
>     private void addToPrivilegeTypesIfPresent(final boolean hasPrivilege, final PrivilegeType privilegeType, final Collection<PrivilegeType> target) {
>         if (hasPrivilege) {
>             target.add(privilegeType);
>         }
>     }
> ```
> 
> hasPrivilege property is always false
> becase `resultSet.getBoolean()` methods always false
> 
> But there is no such problem when using mysql

ShardingSphere load all privileges from actual database, so please check the user privileges in RDS.

**Comment by mazhai** [comment]
@menghaoranss 
Now the user has advanced permissions in RDS, but the program does not get them. In version 4, this was not an issue


![image](https://user-images.githubusercontent.com/5811436/128306514-e79fc410-a46c-44e5-8423-18dd7ef032b6.png)
![image](https://user-images.githubusercontent.com/5811436/128306582-128fd038-9f3a-4a8c-9f4e-c77e413cb77a.png)
![image](https://user-images.githubusercontent.com/5811436/128306829-166e6156-a9e6-4c2f-8ce6-68f9722988fa.png)
![image](https://user-images.githubusercontent.com/5811436/128306969-38d81ba6-0d71-4f6e-be27-6315554da83d.png)

**Comment by mazhai** [comment]
![image](https://user-images.githubusercontent.com/5811436/128309972-225d1274-ea92-4979-a0c4-d3de1bc5677a.png)

I see this method takes the user from server.yaml, shouldn't it use the user from config-sharding. Yaml? Yaml and config-sharding.yaml must have the same user name?

**Comment by PhantomMaa** [comment]
connect to Alibaba RDS, will find the two sql not work: show databases, show tables.
1. show databases
because rds not react  as a complete mysql，some details are different.  
for this case, SELECT * FROM mysql.user WHERE (user, host) in (("root", "%"));
return Show_db_priv is N
need update to Y
2.  show tables
edit the source code, shardingsphere-infra-authority-common AuthorityChecker
![image](https://user-images.githubusercontent.com/3435178/132612623-87d7e323-b03a-4c9f-b0a3-feb80b230286.png)

**Comment by terrymanu** [comment]
The authority module has refactored in 5.1.x, please retry it.
I just close this issue, if the problem still existed, please open a new issue, thank you.
