### ISSUE TITLE
UnrecognizedDatabaseURLException

### ISSUE THREAD

**Issue by yuefolk** [apache/shardingsphere#11568]
the bug like [https://github.com/apache/shardingsphere/issues/8736](url)
this is my jdbcUrl config:
jdbc:mysql://localhost:3306,localhost2:3306/databaseName?xxx

It will report an error
`Exception in thread "main" org.apache.shardingsphere.underlying.common.database.metadata.UnrecognizedDatabaseURLException: The URL: 'jdbc:mysql://localhost:3306/' is not recognized. Please refer to this pattern: 'jdbc:(mysql|mysqlx)(:loadbalance|:replication)?:(\w*:)?//([\w\-\.]+):?([0-9]*),?.*?/([\w\-]+);?\S*'.
	at org.apache.shardingsphere.underlying.common.database.metadata.dialect.MySQLDataSourceMetaData.<init>`

I checked the code and found the reason in MultipleDataSourcesRuntimeContext.class
`result.put(entry.getKey(), new DatabaseAccessConfiguration(metaData.getURL(), metaData.getUserName(), (String)null));`
the method `metaData.getURL()` only will return 'jdbc:mysql://localhost:3306/' so cause this exception.
how to fix it?
and if your config is 'jdbc:mysql://localhost:3306/databaseName?xxx' the method `metaData.getURL()` will return 'jdbc:mysql://localhost:3306/databaseName?xxx'

**Comment by sandynz** [comment]
It's #8736

**Comment by sandynz** [comment]
Hi @yuefolk , thanks for your feedback. Seems you've figured out the cause, would you like to push a PR to improve it?
