### ISSUE TITLE
Mysql inner join without bindingtable execute actual sql not like expected.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#11562]
## Bug Report
sql:
`select a.order_id from t_order a inner join t_order_item b on a.order_id
= b.order_id where a.user_id = 1 and a.order_id = 1 and b.user_id = 1 and b.order_id = 1;`
in console actual sql is 
`ds_0 ::: select a.order_id from t_order a inner join t_order_item b on a.order_id = b.order_id where a.user_id = 1 and a.order_id = 1 and b.user_id = 1 and b.order_id = 1`
`ds_1 ::: select a.order_id from t_order a inner join t_order_item b on a.order_id = b.order_id where a.user_id = 1 and a.order_id = 1 and b.user_id = 1 and b.order_id = 1`
but t_order and t_order_item is not exists. Actual sql is not actual.

Here is my config

schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123

### Which version of ShardingSphere did you use?
master branch
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-proxy
### Expected behavior
Should execute like this:
`ds1: select a.order_id from t_order_1 a inner join t_order_item_1 b on a.order_id
= b.order_id where a.user_id = 1 and a.order_id = 1 and b.user_id = 1 and b.order_id = 1;`

**Comment by tuichenchuxin** [comment]
This sql already supported by federate on master branch.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, so I close this issue.
