### ISSUE TITLE
Does Shardingsphere-5.x support default-data-source-name of Shardingsphere-4.x? It seems that the corresponding relationship between each table and the database should be clearly specified in Shardingsphere-5.x.

### ISSUE THREAD

**Issue by wangdandong** [apache/shardingsphere#11565]
Does Shardingsphere-5.x support `default-data-source-name` of Shardingsphere-4.x? It seems that the corresponding relationship between each table and the database should be clearly specified in Shardingsphere-5.x.

**Comment by menghaoranss** [comment]
refer to #7731
