### ISSUE TITLE
rsMeta.getColumnCount() returns "0", If I query the entire sharding table for GROUPING result.

### ISSUE THREAD

**Issue by gywndi** [apache/shardingsphere#11566]
## Bug Report

"user" is sharding table and sharding key is "userid". 
```sql
select * from (
  select name, count(*) from user where crc32(name) % 2 = 0 group by name
  union all
  select name, count(*) from user where crc32(name) % 2 = 1 group by name
) x
```

When executing the above kind of query, the rsMeta.getColumnCount() result is 0. I implemented a simple logic to drop the query result into JSON and tested it.

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? 
ShardingSphere-JDBC

### Expected behavior
```json
{"rowCount":3,"rows":[{"name":"abcde-name0","count(*)":"1"},{"name":"abcde-name1","count(*)":"1"},{"name":"abcde-name2","count(*)":"1"}]}%  
```

### Actual behavior
```json
{"rowCount":3,"rows":[{},{},{}]}%  
```

**Comment by terrymanu** [comment]
Can not support subquery in 4.x, please update to version 5.x and try again
