### ISSUE TITLE
Unable to connect to ali RDS

### ISSUE THREAD

**Issue by mazhai** [apache/shardingsphere#11560]
### Which version of ShardingSphere did you use?
5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

I've tried versions 4.0.0-4.1.1. Proxy can connect to ali RDS normally, and I can connect to sharding proxy using dbeverar

However, starting from 5.0.0, sharding proxy startup is normal. Dbevers cannot be connected. Does 5.0.0 not support ali RDS?

Tips
Unknown exception: [SQL checking failed. Error message: .]

**Comment by menghaoranss** [comment]
Same as #11550
