### ISSUE TITLE
shardingSphere-ui question

### ISSUE THREAD

**Issue by WuZhiMing2** [apache/shardingsphere#11572]
In windows ,cmd run code
mvn clean install -Prelease
 report errors 
![image](https://user-images.githubusercontent.com/37823425/127467643-fdddc400-2de1-4515-8c28-cc4f6fd49f05.png)

**Comment by TeslaCN** [comment]
Your network is not well for `npm install`.

**Comment by WuZhiMing2** [comment]
> Your network is not well for `npm install`.

Can you have image well in China

**Comment by TeslaCN** [comment]
@WuZhiMing2 Consider configure a HTTP proxy in Maven settings. The plugin will use the proxy automatically.

**Comment by WuZhiMing2** [comment]
> @WuZhiMing2 Consider configuring a HTTP proxy in Maven settings. The plugin will use the proxy automatically.

this?
`
        <mirror>
            <id>aliyunmaven</id>
            <mirrorOf>*</mirrorOf>
            <name>阿里云公共仓库</name>
            <url>https://maven.aliyun.com/repository/public</url>
        </mirror>
`

**Comment by TeslaCN** [comment]
HTTP proxy is like the following:
```
   <proxies>
      <proxy>
         <id>my-proxy</id>
         <active>true</active>
         <protocol>http</protocol>
         <host>192.168.10.117</host>
         <port>3267</port>
         <!--
         <username>shihuan</username>
         <password>123456</password>
         <nonProxyHosts>repository.mycom.com|*.google.com</nonProxyHosts>
         -->
      </proxy>
    </proxies>
```

**Comment by TeslaCN** [comment]
This issue may caused by network environment. Please submit a new issue if you have other questions.
