### ISSUE TITLE
why not upgrade build tool to gradle

### ISSUE THREAD

**Issue by hoorf** [apache/shardingsphere#11573]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
build slow 
### Describe the feature you would like.
swith to gradle or separate the project ,all in one just terrible

**Comment by TeslaCN** [comment]
Building slow is because of tests, using Gradle may not be helpful.
Try executing
```
mvn -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests clean install -T1C
```

**Comment by hoorf** [comment]
```
[INFO] 
[INFO] shardingsphere ..................................... SUCCESS [  3.973 s]
[INFO] shardingsphere-agent ............................... SUCCESS [  0.228 s]
[INFO] shardingsphere-agent-api ........................... SUCCESS [  2.999 s]
[INFO] shardingsphere-agent-core .......................... SUCCESS [  6.136 s]
[INFO] shardingsphere-agent-bootstrap ..................... SUCCESS [  3.332 s]
[INFO] shardingsphere-sql-parser .......................... SUCCESS [  0.183 s]
[INFO] shardingsphere-sql-parser-spi ...................... SUCCESS [  1.579 s]
[INFO] shardingsphere-sql-parser-statement ................ SUCCESS [ 10.944 s]
[INFO] shardingsphere-sql-parser-engine ................... SUCCESS [  3.704 s]
[INFO] shardingsphere-distsql-parser ...................... SUCCESS [  0.216 s]
[INFO] shardingsphere-distsql-parser-statement ............ SUCCESS [  1.686 s]
[INFO] shardingsphere-distsql-parser-engine ............... SUCCESS [  2.982 s]
[INFO] shardingsphere-infra ............................... SUCCESS [  0.192 s]
[INFO] shardingsphere-infra-parser ........................ SUCCESS [  2.749 s]
[INFO] shardingsphere-test ................................ SUCCESS [  0.177 s]
[INFO] shardingsphere-test-common ......................... SUCCESS [  1.526 s]
[INFO] shardingsphere-infra-common ........................ SUCCESS [ 10.962 s]
[INFO] shardingsphere-infra-binder ........................ SUCCESS [  5.985 s]
[INFO] shardingsphere-infra-route ......................... SUCCESS [  3.444 s]
[INFO] shardingsphere-agent-plugins ....................... SUCCESS [  0.408 s]
[INFO] shardingsphere-agent-plugin-metrics ................ SUCCESS [  0.191 s]
[INFO] shardingsphere-agent-metrics-api ................... SUCCESS [  3.268 s]
[INFO] shardingsphere-features ............................ SUCCESS [  0.173 s]
[INFO] shardingsphere-sharding ............................ SUCCESS [  0.160 s]
[INFO] shardingsphere-sharding-distsql .................... SUCCESS [  0.145 s]
[INFO] shardingsphere-sharding-distsql-statement .......... SUCCESS [  1.661 s]
[INFO] shardingsphere-sharding-distsql-parser ............. SUCCESS [  2.585 s]
[INFO] shardingsphere-readwrite-splitting ................. SUCCESS [  0.151 s]
[INFO] shardingsphere-readwrite-splitting-distsql ......... SUCCESS [  0.147 s]
[INFO] shardingsphere-readwrite-splitting-distsql-statement SUCCESS [  1.516 s]
[INFO] shardingsphere-readwrite-splitting-distsql-parser .. SUCCESS [  2.141 s]
[INFO] shardingsphere-db-discovery ........................ SUCCESS [  0.154 s]
[INFO] shardingsphere-db-discovery-distsql ................ SUCCESS [  0.145 s]
[INFO] shardingsphere-db-discovery-distsql-statement ...... SUCCESS [  1.543 s]
[INFO] shardingsphere-db-discovery-distsql-parser ......... SUCCESS [  2.023 s]
[INFO] shardingsphere-encrypt ............................. SUCCESS [  0.159 s]
[INFO] shardingsphere-encrypt-distsql ..................... SUCCESS [  0.141 s]
[INFO] shardingsphere-encrypt-distsql-statement ........... SUCCESS [  1.534 s]
[INFO] shardingsphere-encrypt-distsql-parser .............. SUCCESS [  2.283 s]
[INFO] shardingsphere-scaling ............................. SUCCESS [  0.159 s]
[INFO] shardingsphere-scaling-distsql ..................... SUCCESS [  0.154 s]
[INFO] shardingsphere-scaling-distsql-statement ........... SUCCESS [  1.482 s]
[INFO] shardingsphere-scaling-distsql-parser .............. SUCCESS [  1.766 s]
[INFO] shardingsphere-parser-test ......................... SUCCESS [ 11.546 s]
[INFO] shardingsphere-sql-parser-dialect .................. SUCCESS [  0.187 s]
[INFO] shardingsphere-sql-parser-sql92 .................... SUCCESS [  5.369 s]
[INFO] shardingsphere-sql-parser-mysql .................... SUCCESS [ 12.273 s]
[INFO] shardingsphere-sql-parser-postgresql ............... SUCCESS [ 12.145 s]
[INFO] shardingsphere-sql-parser-oracle ................... SUCCESS [ 12.118 s]
[INFO] shardingsphere-sql-parser-sqlserver ................ SUCCESS [  6.583 s]
[INFO] shardingsphere-db-protocol ......................... SUCCESS [  0.199 s]
[INFO] shardingsphere-db-protocol-core .................... SUCCESS [  2.721 s]
[INFO] shardingsphere-infra-rewrite ....................... SUCCESS [  4.611 s]
[INFO] shardingsphere-infra-optimize ...................... SUCCESS [  5.715 s]
[INFO] shardingsphere-infra-executor ...................... SUCCESS [  6.604 s]
[INFO] shardingsphere-infra-authority ..................... SUCCESS [  0.170 s]
[INFO] shardingsphere-infra-authority-api ................. SUCCESS [  1.569 s]
[INFO] shardingsphere-infra-context ....................... SUCCESS [  4.209 s]
[INFO] shardingsphere-governance .......................... SUCCESS [  0.165 s]
[INFO] shardingsphere-governance-repository ............... SUCCESS [  0.158 s]
[INFO] shardingsphere-governance-repository-api ........... SUCCESS [  1.534 s]
[INFO] shardingsphere-infra-authority-common .............. SUCCESS [  5.178 s]
[INFO] shardingsphere-governance-core ..................... SUCCESS [  6.923 s]
[INFO] shardingsphere-sharding-api ........................ SUCCESS [  1.853 s]
[INFO] shardingsphere-sharding-distsql-handler ............ SUCCESS [  4.305 s]
[INFO] shardingsphere-infra-merge ......................... SUCCESS [  4.110 s]
[INFO] shardingsphere-infra-datetime ...................... SUCCESS [  0.189 s]
[INFO] shardingsphere-infra-datetime-spi .................. SUCCESS [  1.782 s]
[INFO] shardingsphere-infra-datetime-type ................. SUCCESS [  0.140 s]
[INFO] shardingsphere-system-datetime ..................... SUCCESS [  2.450 s]
[INFO] shardingsphere-sharding-core ....................... SUCCESS [ 12.922 s]
[INFO] shardingsphere-readwrite-splitting-api ............. SUCCESS [  1.517 s]
[INFO] shardingsphere-readwrite-splitting-distsql-handler . SUCCESS [  3.095 s]
[INFO] shardingsphere-readwrite-splitting-core ............ SUCCESS [  4.728 s]
[INFO] shardingsphere-encrypt-api ......................... SUCCESS [  1.514 s]
[INFO] shardingsphere-encrypt-distsql-handler ............. SUCCESS [  3.038 s]
[INFO] shardingsphere-encrypt-core ........................ SUCCESS [  7.458 s]
[INFO] shardingsphere-db-discovery-api .................... SUCCESS [  1.498 s]
[INFO] shardingsphere-db-discovery-distsql-handler ........ SUCCESS [  3.062 s]
[INFO] shardingsphere-db-discovery-provider ............... SUCCESS [  0.151 s]
[INFO] shardingsphere-db-discovery-mgr .................... SUCCESS [  3.390 s]
[INFO] shardingsphere-db-discovery-core ................... SUCCESS [  6.028 s]
[INFO] shardingsphere-proxy ............................... SUCCESS [  0.154 s]
[INFO] shardingsphere-proxy-common ........................ SUCCESS [  5.003 s]
[INFO] shardingsphere-shadow .............................. SUCCESS [  0.180 s]
[INFO] shardingsphere-shadow-api .......................... SUCCESS [  1.442 s]
[INFO] shardingsphere-shadow-core ......................... SUCCESS [  6.129 s]
[INFO] shardingsphere-transaction ......................... SUCCESS [  0.562 s]
[INFO] shardingsphere-transaction-core .................... SUCCESS [  3.300 s]
[INFO] shardingsphere-transaction-2pc ..................... SUCCESS [  0.507 s]
[INFO] shardingsphere-transaction-xa ...................... SUCCESS [  0.509 s]
[INFO] shardingsphere-transaction-xa-spi .................. SUCCESS [  3.062 s]
[INFO] shardingsphere-transaction-xa-atomikos ............. SUCCESS [  3.614 s]
[INFO] shardingsphere-transaction-xa-core ................. SUCCESS [  4.879 s]
[INFO] shardingsphere-jdbc ................................ SUCCESS [  0.162 s]
[INFO] shardingsphere-jdbc-core ........................... SUCCESS [  8.435 s]
[INFO] shardingsphere-governance-repository-provider ...... SUCCESS [  0.150 s]
[INFO] shardingsphere-governance-repository-zookeeper-curator SUCCESS [  3.825 s]
[INFO] shardingsphere-scaling-core ........................ SUCCESS [  9.019 s]
[INFO] shardingsphere-scaling-distsql-handler ............. SUCCESS [  3.232 s]
[INFO] shardingsphere-db-protocol-mysql ................... SUCCESS [  6.458 s]
[INFO] shardingsphere-scaling-dialect ..................... SUCCESS [  0.163 s]
[INFO] shardingsphere-scaling-mysql ....................... SUCCESS [  7.804 s]
[INFO] shardingsphere-scaling-postgresql .................. SUCCESS [  5.370 s]
[INFO] shardingsphere-proxy-backend ....................... SUCCESS [ 11.768 s]
[INFO] shardingsphere-proxy-frontend ...................... SUCCESS [  0.146 s]
[INFO] shardingsphere-proxy-frontend-spi .................. SUCCESS [  3.071 s]
[INFO] shardingsphere-proxy-frontend-core ................. SUCCESS [  6.782 s]
[INFO] shardingsphere-agent-metrics-prometheus ............ SUCCESS [  4.976 s]
[INFO] shardingsphere-agent-plugin-tracing ................ SUCCESS [  1.105 s]
[INFO] shardingsphere-agent-tracing-test .................. SUCCESS [  5.455 s]
[INFO] shardingsphere-agent-tracing-jaeger ................ SUCCESS [  8.385 s]
[INFO] shardingsphere-agent-tracing-zipkin ................ SUCCESS [  6.838 s]
[INFO] shardingsphere-agent-tracing-opentracing ........... SUCCESS [  6.664 s]
[INFO] shardingsphere-agent-tracing-opentelemetry ......... SUCCESS [  7.438 s]
[INFO] shardingsphere-agent-plugin-logging ................ SUCCESS [  0.184 s]
[INFO] shardingsphere-agent-logging-base .................. SUCCESS [  1.677 s]
[INFO] shardingsphere-agent-distribution .................. SUCCESS [  1.680 s]
[INFO] shardingsphere-db-protocol-postgresql .............. SUCCESS [  4.985 s]
[INFO] shardingsphere-database-datetime ................... SUCCESS [  3.422 s]
[INFO] shardingsphere-governance-context .................. SUCCESS [  4.851 s]
[INFO] shardingsphere-jdbc-governance ..................... SUCCESS [  6.728 s]
[INFO] shardingsphere-jdbc-spring ......................... SUCCESS [  0.224 s]
[INFO] shardingsphere-jdbc-spring-infra ................... SUCCESS [  0.172 s]
[INFO] shardingsphere-jdbc-spring-boot-starter-infra ...... SUCCESS [ 38.782 s]
[INFO] shardingsphere-jdbc-spring-namespace-infra ......... SUCCESS [  4.285 s]
[INFO] shardingsphere-sharding-spring ..................... SUCCESS [  0.159 s]
[INFO] shardingsphere-sharding-spring-boot-starter ........ SUCCESS [  5.423 s]
[INFO] shardingsphere-shadow-spring ....................... SUCCESS [  0.150 s]
[INFO] shardingsphere-shadow-spring-boot-starter .......... SUCCESS [  4.135 s]
[INFO] shardingsphere-encrypt-spring ...................... SUCCESS [  0.160 s]
[INFO] shardingsphere-encrypt-spring-boot-starter ......... SUCCESS [  4.554 s]
[INFO] shardingsphere-readwrite-splitting-spring .......... SUCCESS [  0.142 s]
[INFO] shardingsphere-readwrite-splitting-spring-boot-starter SUCCESS [  4.316 s]
[INFO] shardingsphere-jdbc-transaction-spring ............. SUCCESS [  4.609 s]
[INFO] shardingsphere-jdbc-core-spring .................... SUCCESS [  1.227 s]
[INFO] shardingsphere-jdbc-core-spring-boot-starter ....... SUCCESS [  5.532 s]
[INFO] shardingsphere-sharding-spring-namespace ........... SUCCESS [  5.741 s]
[INFO] shardingsphere-readwrite-splitting-spring-namespace  SUCCESS [  4.178 s]
[INFO] shardingsphere-encrypt-spring-namespace ............ SUCCESS [  4.147 s]
[INFO] shardingsphere-shadow-spring-namespace ............. SUCCESS [  3.995 s]
[INFO] shardingsphere-jdbc-core-spring-namespace .......... SUCCESS [  4.418 s]
[INFO] shardingsphere-jdbc-governance-spring .............. SUCCESS [  1.480 s]
[INFO] shardingsphere-jdbc-governance-spring-boot-starter . SUCCESS [  6.159 s]
[INFO] shardingsphere-jdbc-governance-spring-namespace .... SUCCESS [  6.945 s]
[INFO] shardingsphere-proxy-frontend-mysql ................ SUCCESS [  8.832 s]
[INFO] shardingsphere-proxy-frontend-postgresql ........... SUCCESS [  8.051 s]
[INFO] shardingsphere-governance-repository-etcd .......... SUCCESS [  8.389 s]
[INFO] shardingsphere-proxy-bootstrap ..................... SUCCESS [  7.985 s]
[INFO] shardingsphere-db-discovery-spring ................. SUCCESS [  0.145 s]
[INFO] shardingsphere-db-discovery-spring-namespace ....... SUCCESS [  2.669 s]
[INFO] shardingsphere-db-discovery-spring-boot-starter .... SUCCESS [  4.376 s]
[INFO] shardingsphere-scaling-bootstrap ................... SUCCESS [  5.098 s]
[INFO] shardingsphere-transaction-xa-narayana ............. SUCCESS [  3.712 s]
[INFO] shardingsphere-transaction-xa-bitronix ............. SUCCESS [  3.614 s]
[INFO] shardingsphere-transaction-base .................... SUCCESS [  0.614 s]
[INFO] shardingsphere-transaction-base-seata-at ........... SUCCESS [  4.685 s]
[INFO] shardingsphere-integration-test .................... SUCCESS [  0.307 s]
[INFO] shardingsphere-integration-test-fixture ............ SUCCESS [  8.261 s]
[INFO] shardingsphere-integration-test-suite .............. SUCCESS [  9.764 s]
[INFO] shardingsphere-integration-agent-test .............. SUCCESS [  0.193 s]
[INFO] shardingsphere-integration-agent-test-plugins ...... SUCCESS [  0.151 s]
[INFO] shardingsphere-integration-agent-test-common ....... SUCCESS [  1.692 s]
[INFO] shardingsphere-integration-agent-test-metrics ...... SUCCESS [  5.017 s]
[INFO] shardingsphere-integration-agent-test-zipkin ....... SUCCESS [  4.775 s]
[INFO] shardingsphere-integration-agent-test-jaeger ....... SUCCESS [  4.818 s]
[INFO] shardingsphere-integration-agent-test-opentelemetry  SUCCESS [  4.986 s]
[INFO] shardingsphere-integration-scaling-test ............ SUCCESS [  0.194 s]
[INFO] shardingsphere-integration-scaling-test-mysql ...... SUCCESS [  3.827 s]
[INFO] shardingsphere-rewrite-test ........................ SUCCESS [  3.086 s]
[INFO] shardingsphere-distribution ........................ SUCCESS [  0.163 s]
[INFO] shardingsphere-src-distribution .................... SUCCESS [  0.144 s]
[INFO] shardingsphere-jdbc-distribution ................... SUCCESS [  4.157 s]
[INFO] shardingsphere-proxy-distribution .................. SUCCESS [  3.523 s]
[INFO] shardingsphere-scaling-distribution ................ SUCCESS [  1.461 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:37 min
[INFO] Finished at: 2021-07-30T09:15:53+08:00
[INFO] ------------------------------------------------------------------------
```
oook,10 min normal?

**Comment by TeslaCN** [comment]
> ```
> [INFO] 
> [INFO] shardingsphere ..................................... SUCCESS [  3.973 s]
> [INFO] shardingsphere-agent ............................... SUCCESS [  0.228 s]
> [INFO] shardingsphere-agent-api ........................... SUCCESS [  2.999 s]
> [INFO] shardingsphere-agent-core .......................... SUCCESS [  6.136 s]
> [INFO] shardingsphere-agent-bootstrap ..................... SUCCESS [  3.332 s]
> [INFO] shardingsphere-sql-parser .......................... SUCCESS [  0.183 s]
> [INFO] shardingsphere-sql-parser-spi ...................... SUCCESS [  1.579 s]
> [INFO] shardingsphere-sql-parser-statement ................ SUCCESS [ 10.944 s]
> [INFO] shardingsphere-sql-parser-engine ................... SUCCESS [  3.704 s]
> [INFO] shardingsphere-distsql-parser ...................... SUCCESS [  0.216 s]
> [INFO] shardingsphere-distsql-parser-statement ............ SUCCESS [  1.686 s]
> [INFO] shardingsphere-distsql-parser-engine ............... SUCCESS [  2.982 s]
> [INFO] shardingsphere-infra ............................... SUCCESS [  0.192 s]
> [INFO] shardingsphere-infra-parser ........................ SUCCESS [  2.749 s]
> [INFO] shardingsphere-test ................................ SUCCESS [  0.177 s]
> [INFO] shardingsphere-test-common ......................... SUCCESS [  1.526 s]
> [INFO] shardingsphere-infra-common ........................ SUCCESS [ 10.962 s]
> [INFO] shardingsphere-infra-binder ........................ SUCCESS [  5.985 s]
> [INFO] shardingsphere-infra-route ......................... SUCCESS [  3.444 s]
> [INFO] shardingsphere-agent-plugins ....................... SUCCESS [  0.408 s]
> [INFO] shardingsphere-agent-plugin-metrics ................ SUCCESS [  0.191 s]
> [INFO] shardingsphere-agent-metrics-api ................... SUCCESS [  3.268 s]
> [INFO] shardingsphere-features ............................ SUCCESS [  0.173 s]
> [INFO] shardingsphere-sharding ............................ SUCCESS [  0.160 s]
> [INFO] shardingsphere-sharding-distsql .................... SUCCESS [  0.145 s]
> [INFO] shardingsphere-sharding-distsql-statement .......... SUCCESS [  1.661 s]
> [INFO] shardingsphere-sharding-distsql-parser ............. SUCCESS [  2.585 s]
> [INFO] shardingsphere-readwrite-splitting ................. SUCCESS [  0.151 s]
> [INFO] shardingsphere-readwrite-splitting-distsql ......... SUCCESS [  0.147 s]
> [INFO] shardingsphere-readwrite-splitting-distsql-statement SUCCESS [  1.516 s]
> [INFO] shardingsphere-readwrite-splitting-distsql-parser .. SUCCESS [  2.141 s]
> [INFO] shardingsphere-db-discovery ........................ SUCCESS [  0.154 s]
> [INFO] shardingsphere-db-discovery-distsql ................ SUCCESS [  0.145 s]
> [INFO] shardingsphere-db-discovery-distsql-statement ...... SUCCESS [  1.543 s]
> [INFO] shardingsphere-db-discovery-distsql-parser ......... SUCCESS [  2.023 s]
> [INFO] shardingsphere-encrypt ............................. SUCCESS [  0.159 s]
> [INFO] shardingsphere-encrypt-distsql ..................... SUCCESS [  0.141 s]
> [INFO] shardingsphere-encrypt-distsql-statement ........... SUCCESS [  1.534 s]
> [INFO] shardingsphere-encrypt-distsql-parser .............. SUCCESS [  2.283 s]
> [INFO] shardingsphere-scaling ............................. SUCCESS [  0.159 s]
> [INFO] shardingsphere-scaling-distsql ..................... SUCCESS [  0.154 s]
> [INFO] shardingsphere-scaling-distsql-statement ........... SUCCESS [  1.482 s]
> [INFO] shardingsphere-scaling-distsql-parser .............. SUCCESS [  1.766 s]
> [INFO] shardingsphere-parser-test ......................... SUCCESS [ 11.546 s]
> [INFO] shardingsphere-sql-parser-dialect .................. SUCCESS [  0.187 s]
> [INFO] shardingsphere-sql-parser-sql92 .................... SUCCESS [  5.369 s]
> [INFO] shardingsphere-sql-parser-mysql .................... SUCCESS [ 12.273 s]
> [INFO] shardingsphere-sql-parser-postgresql ............... SUCCESS [ 12.145 s]
> [INFO] shardingsphere-sql-parser-oracle ................... SUCCESS [ 12.118 s]
> [INFO] shardingsphere-sql-parser-sqlserver ................ SUCCESS [  6.583 s]
> [INFO] shardingsphere-db-protocol ......................... SUCCESS [  0.199 s]
> [INFO] shardingsphere-db-protocol-core .................... SUCCESS [  2.721 s]
> [INFO] shardingsphere-infra-rewrite ....................... SUCCESS [  4.611 s]
> [INFO] shardingsphere-infra-optimize ...................... SUCCESS [  5.715 s]
> [INFO] shardingsphere-infra-executor ...................... SUCCESS [  6.604 s]
> [INFO] shardingsphere-infra-authority ..................... SUCCESS [  0.170 s]
> [INFO] shardingsphere-infra-authority-api ................. SUCCESS [  1.569 s]
> [INFO] shardingsphere-infra-context ....................... SUCCESS [  4.209 s]
> [INFO] shardingsphere-governance .......................... SUCCESS [  0.165 s]
> [INFO] shardingsphere-governance-repository ............... SUCCESS [  0.158 s]
> [INFO] shardingsphere-governance-repository-api ........... SUCCESS [  1.534 s]
> [INFO] shardingsphere-infra-authority-common .............. SUCCESS [  5.178 s]
> [INFO] shardingsphere-governance-core ..................... SUCCESS [  6.923 s]
> [INFO] shardingsphere-sharding-api ........................ SUCCESS [  1.853 s]
> [INFO] shardingsphere-sharding-distsql-handler ............ SUCCESS [  4.305 s]
> [INFO] shardingsphere-infra-merge ......................... SUCCESS [  4.110 s]
> [INFO] shardingsphere-infra-datetime ...................... SUCCESS [  0.189 s]
> [INFO] shardingsphere-infra-datetime-spi .................. SUCCESS [  1.782 s]
> [INFO] shardingsphere-infra-datetime-type ................. SUCCESS [  0.140 s]
> [INFO] shardingsphere-system-datetime ..................... SUCCESS [  2.450 s]
> [INFO] shardingsphere-sharding-core ....................... SUCCESS [ 12.922 s]
> [INFO] shardingsphere-readwrite-splitting-api ............. SUCCESS [  1.517 s]
> [INFO] shardingsphere-readwrite-splitting-distsql-handler . SUCCESS [  3.095 s]
> [INFO] shardingsphere-readwrite-splitting-core ............ SUCCESS [  4.728 s]
> [INFO] shardingsphere-encrypt-api ......................... SUCCESS [  1.514 s]
> [INFO] shardingsphere-encrypt-distsql-handler ............. SUCCESS [  3.038 s]
> [INFO] shardingsphere-encrypt-core ........................ SUCCESS [  7.458 s]
> [INFO] shardingsphere-db-discovery-api .................... SUCCESS [  1.498 s]
> [INFO] shardingsphere-db-discovery-distsql-handler ........ SUCCESS [  3.062 s]
> [INFO] shardingsphere-db-discovery-provider ............... SUCCESS [  0.151 s]
> [INFO] shardingsphere-db-discovery-mgr .................... SUCCESS [  3.390 s]
> [INFO] shardingsphere-db-discovery-core ................... SUCCESS [  6.028 s]
> [INFO] shardingsphere-proxy ............................... SUCCESS [  0.154 s]
> [INFO] shardingsphere-proxy-common ........................ SUCCESS [  5.003 s]
> [INFO] shardingsphere-shadow .............................. SUCCESS [  0.180 s]
> [INFO] shardingsphere-shadow-api .......................... SUCCESS [  1.442 s]
> [INFO] shardingsphere-shadow-core ......................... SUCCESS [  6.129 s]
> [INFO] shardingsphere-transaction ......................... SUCCESS [  0.562 s]
> [INFO] shardingsphere-transaction-core .................... SUCCESS [  3.300 s]
> [INFO] shardingsphere-transaction-2pc ..................... SUCCESS [  0.507 s]
> [INFO] shardingsphere-transaction-xa ...................... SUCCESS [  0.509 s]
> [INFO] shardingsphere-transaction-xa-spi .................. SUCCESS [  3.062 s]
> [INFO] shardingsphere-transaction-xa-atomikos ............. SUCCESS [  3.614 s]
> [INFO] shardingsphere-transaction-xa-core ................. SUCCESS [  4.879 s]
> [INFO] shardingsphere-jdbc ................................ SUCCESS [  0.162 s]
> [INFO] shardingsphere-jdbc-core ........................... SUCCESS [  8.435 s]
> [INFO] shardingsphere-governance-repository-provider ...... SUCCESS [  0.150 s]
> [INFO] shardingsphere-governance-repository-zookeeper-curator SUCCESS [  3.825 s]
> [INFO] shardingsphere-scaling-core ........................ SUCCESS [  9.019 s]
> [INFO] shardingsphere-scaling-distsql-handler ............. SUCCESS [  3.232 s]
> [INFO] shardingsphere-db-protocol-mysql ................... SUCCESS [  6.458 s]
> [INFO] shardingsphere-scaling-dialect ..................... SUCCESS [  0.163 s]
> [INFO] shardingsphere-scaling-mysql ....................... SUCCESS [  7.804 s]
> [INFO] shardingsphere-scaling-postgresql .................. SUCCESS [  5.370 s]
> [INFO] shardingsphere-proxy-backend ....................... SUCCESS [ 11.768 s]
> [INFO] shardingsphere-proxy-frontend ...................... SUCCESS [  0.146 s]
> [INFO] shardingsphere-proxy-frontend-spi .................. SUCCESS [  3.071 s]
> [INFO] shardingsphere-proxy-frontend-core ................. SUCCESS [  6.782 s]
> [INFO] shardingsphere-agent-metrics-prometheus ............ SUCCESS [  4.976 s]
> [INFO] shardingsphere-agent-plugin-tracing ................ SUCCESS [  1.105 s]
> [INFO] shardingsphere-agent-tracing-test .................. SUCCESS [  5.455 s]
> [INFO] shardingsphere-agent-tracing-jaeger ................ SUCCESS [  8.385 s]
> [INFO] shardingsphere-agent-tracing-zipkin ................ SUCCESS [  6.838 s]
> [INFO] shardingsphere-agent-tracing-opentracing ........... SUCCESS [  6.664 s]
> [INFO] shardingsphere-agent-tracing-opentelemetry ......... SUCCESS [  7.438 s]
> [INFO] shardingsphere-agent-plugin-logging ................ SUCCESS [  0.184 s]
> [INFO] shardingsphere-agent-logging-base .................. SUCCESS [  1.677 s]
> [INFO] shardingsphere-agent-distribution .................. SUCCESS [  1.680 s]
> [INFO] shardingsphere-db-protocol-postgresql .............. SUCCESS [  4.985 s]
> [INFO] shardingsphere-database-datetime ................... SUCCESS [  3.422 s]
> [INFO] shardingsphere-governance-context .................. SUCCESS [  4.851 s]
> [INFO] shardingsphere-jdbc-governance ..................... SUCCESS [  6.728 s]
> [INFO] shardingsphere-jdbc-spring ......................... SUCCESS [  0.224 s]
> [INFO] shardingsphere-jdbc-spring-infra ................... SUCCESS [  0.172 s]
> [INFO] shardingsphere-jdbc-spring-boot-starter-infra ...... SUCCESS [ 38.782 s]
> [INFO] shardingsphere-jdbc-spring-namespace-infra ......... SUCCESS [  4.285 s]
> [INFO] shardingsphere-sharding-spring ..................... SUCCESS [  0.159 s]
> [INFO] shardingsphere-sharding-spring-boot-starter ........ SUCCESS [  5.423 s]
> [INFO] shardingsphere-shadow-spring ....................... SUCCESS [  0.150 s]
> [INFO] shardingsphere-shadow-spring-boot-starter .......... SUCCESS [  4.135 s]
> [INFO] shardingsphere-encrypt-spring ...................... SUCCESS [  0.160 s]
> [INFO] shardingsphere-encrypt-spring-boot-starter ......... SUCCESS [  4.554 s]
> [INFO] shardingsphere-readwrite-splitting-spring .......... SUCCESS [  0.142 s]
> [INFO] shardingsphere-readwrite-splitting-spring-boot-starter SUCCESS [  4.316 s]
> [INFO] shardingsphere-jdbc-transaction-spring ............. SUCCESS [  4.609 s]
> [INFO] shardingsphere-jdbc-core-spring .................... SUCCESS [  1.227 s]
> [INFO] shardingsphere-jdbc-core-spring-boot-starter ....... SUCCESS [  5.532 s]
> [INFO] shardingsphere-sharding-spring-namespace ........... SUCCESS [  5.741 s]
> [INFO] shardingsphere-readwrite-splitting-spring-namespace  SUCCESS [  4.178 s]
> [INFO] shardingsphere-encrypt-spring-namespace ............ SUCCESS [  4.147 s]
> [INFO] shardingsphere-shadow-spring-namespace ............. SUCCESS [  3.995 s]
> [INFO] shardingsphere-jdbc-core-spring-namespace .......... SUCCESS [  4.418 s]
> [INFO] shardingsphere-jdbc-governance-spring .............. SUCCESS [  1.480 s]
> [INFO] shardingsphere-jdbc-governance-spring-boot-starter . SUCCESS [  6.159 s]
> [INFO] shardingsphere-jdbc-governance-spring-namespace .... SUCCESS [  6.945 s]
> [INFO] shardingsphere-proxy-frontend-mysql ................ SUCCESS [  8.832 s]
> [INFO] shardingsphere-proxy-frontend-postgresql ........... SUCCESS [  8.051 s]
> [INFO] shardingsphere-governance-repository-etcd .......... SUCCESS [  8.389 s]
> [INFO] shardingsphere-proxy-bootstrap ..................... SUCCESS [  7.985 s]
> [INFO] shardingsphere-db-discovery-spring ................. SUCCESS [  0.145 s]
> [INFO] shardingsphere-db-discovery-spring-namespace ....... SUCCESS [  2.669 s]
> [INFO] shardingsphere-db-discovery-spring-boot-starter .... SUCCESS [  4.376 s]
> [INFO] shardingsphere-scaling-bootstrap ................... SUCCESS [  5.098 s]
> [INFO] shardingsphere-transaction-xa-narayana ............. SUCCESS [  3.712 s]
> [INFO] shardingsphere-transaction-xa-bitronix ............. SUCCESS [  3.614 s]
> [INFO] shardingsphere-transaction-base .................... SUCCESS [  0.614 s]
> [INFO] shardingsphere-transaction-base-seata-at ........... SUCCESS [  4.685 s]
> [INFO] shardingsphere-integration-test .................... SUCCESS [  0.307 s]
> [INFO] shardingsphere-integration-test-fixture ............ SUCCESS [  8.261 s]
> [INFO] shardingsphere-integration-test-suite .............. SUCCESS [  9.764 s]
> [INFO] shardingsphere-integration-agent-test .............. SUCCESS [  0.193 s]
> [INFO] shardingsphere-integration-agent-test-plugins ...... SUCCESS [  0.151 s]
> [INFO] shardingsphere-integration-agent-test-common ....... SUCCESS [  1.692 s]
> [INFO] shardingsphere-integration-agent-test-metrics ...... SUCCESS [  5.017 s]
> [INFO] shardingsphere-integration-agent-test-zipkin ....... SUCCESS [  4.775 s]
> [INFO] shardingsphere-integration-agent-test-jaeger ....... SUCCESS [  4.818 s]
> [INFO] shardingsphere-integration-agent-test-opentelemetry  SUCCESS [  4.986 s]
> [INFO] shardingsphere-integration-scaling-test ............ SUCCESS [  0.194 s]
> [INFO] shardingsphere-integration-scaling-test-mysql ...... SUCCESS [  3.827 s]
> [INFO] shardingsphere-rewrite-test ........................ SUCCESS [  3.086 s]
> [INFO] shardingsphere-distribution ........................ SUCCESS [  0.163 s]
> [INFO] shardingsphere-src-distribution .................... SUCCESS [  0.144 s]
> [INFO] shardingsphere-jdbc-distribution ................... SUCCESS [  4.157 s]
> [INFO] shardingsphere-proxy-distribution .................. SUCCESS [  3.523 s]
> [INFO] shardingsphere-scaling-distribution ................ SUCCESS [  1.461 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  10:37 min
> [INFO] Finished at: 2021-07-30T09:15:53+08:00
> [INFO] ------------------------------------------------------------------------
> ```
> 
> 
>      
>   
> 
> oook,10 min normal?

What's your CPU？
My i7-8700 in Linux took about 6 minutes to install.
Apple M1 took about 7 minutes.

**Comment by hoorf** [comment]
i5-8400 also need 10 min,maven did  no cache build

**Comment by dachuan9e** [comment]
Please have a try build with '-T' like '-T4C'

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
