### ISSUE TITLE
数据分片后，如果优雅扩容

### ISSUE THREAD

**Issue by z7658329** [apache/shardingsphere#11579]
比如我现在按照用户ID分10个库，未来业务量激增，需要分128个库，如何优雅扩容？

**Comment by yx9o** [comment]
Hi @z7658329  , for English only, please modify the issue title and content. thanks

**Comment by menghaoranss** [comment]
@z7658329 Please refer to [ShardingSphere Scaling](https://shardingsphere.apache.org/document/current/en/features/scaling/) , For English only, look forward to your next feedback.
