### ISSUE TITLE
orchestration, updated zookeeper /state/datasources/schema.ds0_salve1 to SET a slave datasource DISABLED 

### ISSUE THREAD

**Issue by liuyibo123** [apache/shardingsphere#11578]
## Question
I want to use orchestration to  blowout a datasouce, updated zookeeper /state/datasources/schema.ds0_salve1 to SET a slave datasource DISABLED ,but the sql  still execute  to  this datasouce.

**Comment by menghaoranss** [comment]
@liuyibo123 which version did you use?

**Comment by liuyibo123** [comment]
> @liuyibo123 which version did you use?

4.1.1

**Comment by menghaoranss** [comment]
@liuyibo123 could you try with version `5.0.0-beta` again?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
