### ISSUE TITLE
Explanation about %SHARDINGSPHERE_PROXY_HOME% in Docs

### ISSUE THREAD

**Issue by sgc109** [apache/shardingsphere#11588]
In [documentation for shardingsphere proxy](https://shardingsphere.apache.org/document/current/en/quick-start/shardingsphere-proxy-quick-start/), it says as follows

> %SHARDINGSPHERE_PROXY_HOME% is the shardingsphere proxy extract path. for example: /Users/ss/shardingsphere-proxy-bin/

However, it is not clear for what **"shardingsphere proxy extract path"** means.
I just guessed that %SHARDINGSPHERE_PROXY_HOME% is `shardingsphere/shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources` because this is one of few(6 exactly) places that include start.sh in bin/ directory in it, and the only place related with shardingsphere proxy at the same time.

But, when I run start.sh in `shardingsphere/shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin`, then following error occurs.

> Error: Could not find or load main class org.apache.shardingsphere.proxy.Bootstrap

I think there need some correct explanations in documentation.

**Comment by menghaoranss** [comment]
`shardingsphere proxy extract path` is based on ShardingSphere's binary package，would you like to explain with a PR?

**Comment by sgc109** [comment]
How can I get ShardingSphere's binary package?

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
