### ISSUE TITLE
optimization Hard-coded string

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#11581]
Hi, I found the following database type values such as: `"H2", "MySQL", "PostgreSQL", "Oracle", "SQLServer", "SQL92"` There are hard-coded strings in a large number of classes (test Except for classes).

Although these values will not be changed or incorrectly written, I still think it is better to use enumerations to replace strings, which is easier to manage and maintain.

Welcome to leave a comment and discuss.

Code screenshot:

![image](https://user-images.githubusercontent.com/12792261/127594773-92de7bcb-5545-4dc9-9b14-96b260c8d4ef.png)
![image](https://user-images.githubusercontent.com/12792261/127594911-f7196635-58c5-4614-8645-8b6b6566726a.png)
![image](https://user-images.githubusercontent.com/12792261/127595154-2c4319d7-d97f-421f-bcbb-de44c3ffe17e.png)

**Comment by terrymanu** [comment]
No, enumerations are static only, the database types are "dynamic" which can be added via SPI
