### ISSUE TITLE
Unnecessary code coverage report production on GHA

### ISSUE THREAD

**Issue by kuantuna** [apache/shardingsphere#11580]
### What is the problem?
As stated in the [ci.yml](https://github.com/apache/shardingsphere/blob/master/.github/workflows/ci.yml) file, _**JaCoCo**_ and **_Cobertura_** code coverage reports are generated while the project is being built. However, since these generated reports are not saved anywhere, they are automatically deleted when the GHA instance finishes the run. This leads to unnecessary waste of time and electricity during CI builds.

### How is the problem manifested?
I forked the project and measured how much time was wasted due to these reports that were generated and not used.

1. It took a total of **6454 seconds** for the build 3 platforms where these reports were [generated](https://github.com/kuantuna/shardingsphere/actions/runs/1080696903), 
2. while it took a total of **3025 seconds** for the build 3 platforms where the reports were [not generated](https://github.com/kuantuna/shardingsphere/actions/runs/1080736069).

This shows that **_3429 seconds are wasted unnecessarily_**. And also means that it can be saved for the next builds.
(Note: Total time is calculated as: build time on windows + build time on linux + build time on macos)

### Possible solutions

1. Prevent the reports from being produced (e.g., by adding or configuring a Maven profile)
2. Allow the reports to be registered on some code coverage platform (e.g., codecov.io which is the platform used in [.travis.yml](https://github.com/apache/shardingsphere/blob/master/.travis.yml))

If one of these two options is suitable for you or if you have another suggestion, I would like to open a pull request on it.

**Comment by terrymanu** [comment]
Hi, could you provide a pull request to resolve the issue?
