### ISSUE TITLE
Sharding-proxy may have problems in local transaction scenarios

### ISSUE THREAD

**Issue by spilledyear** [apache/shardingsphere#11593]
Scene description:
1. Same DB and sub-table
2. Set the value of maxConnectionsSizePerQuery greater than 1
3. Assuming that a logical SQL will be split into two physical SQLs, in the scenario where maxConnectionsSizePerQuery is greater than 1, two database connections will be created at this time. Two physical SQLs will eventually be executed in two database connections
4. Assuming that there is a query statement next, it is possible that the latest data cannot be obtained because of the wrong connection.

The core code is as follows:
ResourceManagedExecuteGroupEngine#generateSQLExecuteGroups

this is a demo:
![image](https://user-images.githubusercontent.com/24663965/127762585-2a31fb11-49e9-4fcc-acba-9de8f49eeb99.png)

**Comment by terrymanu** [comment]
What is your version?

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
