### ISSUE TITLE
Atomikos may cause too many connections

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11611]
The problem occurred with integration testing, which could not be resolved due to limited capabilities.

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### behavior
![image](https://user-images.githubusercontent.com/76552510/127949473-af3c8087-b0f8-4811-a2be-bc80e14fc467.png)

### Reason analyze (If you can)
I guess it's caused by Atomikos's connection not being reclaimed or not being reused.
This problem is more severe in PG type databases.
![image](https://user-images.githubusercontent.com/76552510/127949775-1317aca2-059f-4c3e-a76e-4c2d0d820862.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
You can reproduce this problem by way of [#11781](https://github.com/apache/shardingsphere/issues/11781)

**Comment by hoorf** [comment]
improve the pgsql config `max_connections` may work in short time

**Comment by JiekerTime** [comment]
> improve the pgsql config `max_connections` may work at short time

This really can run through, but I don't think this approach can solve the problem at the root because the number of connections is growing exponentially.
