### ISSUE TITLE
can not support pageHelper with group by?

### ISSUE THREAD

**Issue by loseyourselfWell** [apache/shardingsphere#11616]
## Question

i use pageHelper count pageSize,my sql use group by at last.

exception :

### Cause: java.lang.IllegalStateException: Must have sharding column with subquery.

pom maven version  4.0.1

**Comment by terrymanu** [comment]
Must have sharding column with subquery.

**Comment by loseyourselfWell** [comment]
but it works in version 3.0，so why not support in 4.x？

**Comment by lizhuquan0769** [comment]
I have the same problem, is there a solution?
