### ISSUE TITLE
Incorrect distSQL prompt not friendly enough

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#11612]
Hi community,
When I execute an incorrect distSQL, 
such as: 
```mysql 
CREATE SHARDING TABLE RULE t_lancc (
      RESOURCES(resource_1)
);
```
 it is a friendlier way to prompt for `syntax errors` instead of `Unknown exception: [null]`

**Comment by RaigorJiang** [comment]
Please assign to me, thanks.
