### ISSUE TITLE
ShardingSphere-jdbc configuration add schema name

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11621]
Hi,

   ShardingSphere-jdbc configuration add schema name

## shardingsphere-jdbc-core

- [x] yml config add schemaName:
```
schemaName: logic_db
```

- [x] properties config add schemaName:  
```
spring.shardingsphere.schema.name: logic_db
```

- [x] namespace xml add schemaName   

```
<shardingsphere:data-source id="dataSource" data-source-names="ds_0_write" rule-refs="shardingRule" schema-name="logic_db"></shardingsphere:data-source>
```

## shardingsphere-jdbc-governance

- [x] yml config add schemaName:  
```
schemaName: logic_db
```

- [x] properties config add schemaName:  
```
spring.shardingsphere.schema.name: logic_db
```

- [x] namespace xml add schemaName:  
```
<governance:data-source id="shardingDatabasesTablesDataSource" data-source-names="demo_ds_0, demo_ds_1" reg-center-ref="regCenter" rule-refs="shardingRule" schema-name="logic_db"/>
```

## Remove getDefaultSchemaMetadata()  interface

- [x] remove getDefaultMetaData() interface
```
    /**
     * Get default mata data.
     *
     * @return default mata data
     */
    ShardingSphereMetaData getDefaultMetaData();
```

##  Use real schema name replace logic_db

- [x] use real schema name replace logic_db
```
    /**
     * Schema name.
     */
    public static final String LOGIC_NAME = "logic_db";
```

**Comment by zjcnb** [comment]
example for yml:

`schemaName: logic_db

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: jdbc_${0..1}.t_order_${0..1}
    t_order_item:
      actualDataNodes: jdbc_${0..1}.t_order_item_${0..1}
      keyGenerateStrategy:
        column: item_id
        keyGeneratorName: increment
    t_config:
      actualDataNodes: jdbc_${0..1}.t_config
    t_user:
      actualDataNodes: jdbc_0.t_user_${0..1}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: reset_increment
  autoTables:
    t_order_auto:
      actualDataSources: jdbc_0, jdbc_1
      shardingStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: mod
    t_order_item_auto:
      shardingStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: mod
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_config
    - t_sys
  defaultTableStrategy:
    standard:
      shardingColumn: order_id
      shardingAlgorithmName: standard_test
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: standard_test
  
  shardingAlgorithms:
    standard_test:
        type: STANDARD_TEST
    table_inline:
      type: INLINE
      props:
        algorithm-expression: t_user_${id % 2}
    mod:
      type: MOD
      props:
        sharding-count: 2
  
  keyGenerators:
    increment:
      type: INCREMENT
    reset_increment:
      type: RESET_INCREMENT`

**Comment by terrymanu** [comment]
The `schemaName` is important concept in proxy and JDBC. 
There is 1st line to config `schemaName` in proxy's YAML.
So how about adjust the new parameter `schemaName` to the 1st parameter of the new constructor?

**Comment by terrymanu** [comment]
Another suggestion, could we consider about merge the `schemaName` into MetaDataContexts in `ShardingSphereDataSource` and `GovernanceShardingSphereDataSource`?

The `schemaName` often uses in the kernel process in future.

**Comment by zjcnb** [comment]
> Another suggestion, could we consider about merge the `schemaName` into MetaDataContexts in `ShardingSphereDataSource` and `GovernanceShardingSphereDataSource`?
> 
> The `schemaName` often uses in the kernel process in future.

Yes, i think so!

**Comment by terrymanu** [comment]
It is better to rename the `schemaName` to `currentSchemaName`, because the method `MetaDataContexts.getAllSchemaNames()` if for all schema name.

In the other words, `MetaDataContexts.getAllSchemaNames()` just like SQL `show databases`, `MetaDataContexts.getCurrentSchemaNames()` just like SQL `select database()`,

**Comment by terrymanu** [comment]
Sorry, I think it carefully, the `schemaName` is for connection scope, but the class `MetaDataContexts` is for instance scope.
One instance can include multiple current schemas which hold user connections.
So, keep `schemaName` on DataSource scope with JDBC is fine for now, but in the future, it is better to move it to Connection.

**Comment by zjcnb** [comment]
> Sorry, I think it carefully, the `schemaName` is for connection scope, but the class `MetaDataContexts` is for instance scope.
> One instance can include multiple current schemas which hold user connections.
> So, keep `schemaName` on DataSource scope with JDBC is fine for now, but in the future, it is better to move it to Connection.

Yes i will continue to finish it.

**Comment by zjcnb** [comment]
Hi,

At present, according to the logic of singleTableRule, the DefaultSchema.LOGIC_NAME in A and B does not need to be adjusted for the time being.

DatabaseDiscoverySQLRouter.createRouteContext()
```
 @Override
    public RouteContext createRouteContext(final LogicSQL logicSQL, final ShardingSphereMetaData metaData, final DatabaseDiscoveryRule rule, final ConfigurationProperties props) {
        RouteContext result = new RouteContext();
        String dataSourceName = new DatabaseDiscoveryDataSourceRouter(rule.getSingleDataSourceRule()).route();
        result.getRouteUnits().add(new RouteUnit(new RouteMapper(DefaultSchema.LOGIC_NAME, dataSourceName), Collections.emptyList()));
        return result;
    }
```
ReadwriteSplittingSQLRouter.createRouteContext()

```
  @Override
    public RouteContext createRouteContext(final LogicSQL logicSQL, final ShardingSphereMetaData metaData, final ReadwriteSplittingRule rule, final ConfigurationProperties props) {
        RouteContext result = new RouteContext();
        String dataSourceName = new ReadwriteSplittingDataSourceRouter(rule.getSingleDataSourceRule()).route(logicSQL.getSqlStatementContext().getSqlStatement());
        result.getRouteUnits().add(new RouteUnit(new RouteMapper(DefaultSchema.LOGIC_NAME, dataSourceName), Collections.emptyList()));
        return result;
    }
```
