### ISSUE TITLE
use SQL “Selecct * From...” but result only has part field,not all

### ISSUE THREAD

**Issue by Lacxner** [apache/shardingsphere#11631]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
all field（id、store_id、goods_id、goods_name、goods_img...）
### Actual behavior
only query two field：id、store_id
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. SQL：
![1628046370(1)](https://user-images.githubusercontent.com/35280133/128115819-1d7b6a06-eaee-49f5-b0ef-9608d4e3dfef.png)
2. Mybatis Console SQL Log：
![1628046462](https://user-images.githubusercontent.com/35280133/128115942-a3afa862-68de-4b2b-86fc-80bbea30b765.png)
cant return other field and subquery result.
but if clearly write all field names, that the result is correct
![1628047262(1)](https://user-images.githubusercontent.com/35280133/128117011-f392ca59-4fab-4f11-a5af-5132a73dd2fd.png)

**Comment by strongduanmu** [comment]
@GeekerG2Y Thank you for your feedback, can you try the master branch? I think this bug has been fixed on the master branch.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
