### ISSUE TITLE
shardingsphere executing sql that included subQuery and “order by  alias.field” will throw a "IllegalStateException"

### ISSUE THREAD

**Issue by YollinChan** [apache/shardingsphere#11645]
for example，sql like: "SELECT  s.id from (select id from table_a where id >= 0  limit 0,1000) as s order by s.id desc;" will encounter a "IllegalStateException". 

but sql like "SELECT  s.id from (select id from table_a where id >= 0  limit 0,1000) as s order by id desc;" can execute normally

**Comment by YollinChan** [comment]
exception message is "Can not find owner from table."

**Comment by strongduanmu** [comment]
Duplicate with issue #10257. You can try `5.0.0-beta` version.
