### ISSUE TITLE
Load metadata,ShardingTableMetaDataBuilder#parallelLoadTables performance waste.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#11658]
### Is your feature request related to a problem?
not a problem, but a little performance waste about
### Describe the feature you would like.
sharding config, when i make `check-table-metadata-enabled: true`
then it'll go through `TableMetaDataBuilder#parallelLoadTables`
Then i found tableFutureMap will throw away some future, which is already load table.
If I want to check whether the tables of all data nodes are consistent, then I shouldn't just use the table name as the key.
If I just want to check all the tables on one node, then I shouldn't load all the nodes.
![image](https://user-images.githubusercontent.com/86938616/128312872-35580944-e1f7-4ca2-a475-eea97a40bf07.png)

**Comment by tuichenchuxin** [comment]
I found `MetaDataContextsBuilder#buildSchema` has useless line. 
![image](https://user-images.githubusercontent.com/86938616/128321202-eb1dfbdc-2f5d-46eb-bb9c-f13010c400f5.png)

**Comment by tristaZero** [comment]
? So is it fixed?

**Comment by tuichenchuxin** [comment]
@tristaZero Not yet. After the dialect loading rule tables and the single tables are completed, the parallel check logic will be refactored, and the dialect loading method will be introduced. This problem will be fixed at that time.
