### ISSUE TITLE
Chinese character garbled

### ISSUE THREAD

**Issue by bai1986** [apache/shardingsphere#11662]
The scenario is as follows：
    MySQL character set is configured as follows：
              character_set_server = gbk
    my tables character set is DEFAULT CHARSET=gbk
   The ss-proxy version is apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-proxy-bin
   

When PHP connects directly to MySQL, Chinese characters are displayed normally，However, when PHP connects to the ss-proxy and the proxy routes to the back end, the Chinese code displayed is garbled
For example：
Direct connection mysql，The page is shown below
   'product_name' => string '精选汉法词典‘

Connect proxy, and the page is shown as follows
   'product_name' => string '绮鹃€夋眽娉曡瘝鍏�'

Therefore, I suspect that some default character set settings of shardingsphere-proxy affect Chinese garbled code，please give some  guidance to solve this problem

My data source configuration is as follows
  config-sharding.yaml
   ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ProductDB01?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK

  I tried to configure GBK, utf8 has no effect on the page display results
   

Below is  some test code

<?php
   $cset="GB2312";
   header("Content-type:text/html;charset=$cset");

function f_db_connection($host, $username, $passwd, $dbname, $port, $charset ) /*数据库连接*/
{
    $connection = new mysqli($host, $username, $passwd, $dbname, $port );
    if ($connection->connect_errno) {
        printf("db_connection failed: %s \n host=%s ,username=%s, passwd=%s, dbname=%s \n", $connection->connect_error,$host,$username, $passwd, $dbname);
       // printf($port) ;
        exit();
    }
    mysqli_set_charset($connection, $charset);
    //mysqli_query($connection, "set names utf8");
    return $connection;
}

?>

**Comment by taojintianxia** [comment]
following is the key part of the test application, written in PHP

```php
$cset="GB2312";
//$cset="UTF-8";
header("Content-type:text/html;charset=$cset");




function f_db_connection($host, $username, $passwd, $dbname, $port, $charset ) /*数据库连接*/
{
    $connection = new mysqli($host, $username, $passwd, $dbname, $port );
    if ($connection->connect_errno) {
        printf("db_connection failed: %s \n host=%s ,username=%s, passwd=%s, dbname=%s \n", $connection->connect_error,$host,$username, $passwd, $dbname);
       // printf($port) ;
        exit();
    }
    mysqli_set_charset($connection, $charset);
    //mysqli_query($connection, "set names utf8");
    return $connection;
}
```

**Comment by RaigorJiang** [comment]
Hi @bai1986 
Can you config the property `sql-show` to `true`, and observe if there is a statement like `SET NAMES xxx COLLATE xxx` in proxy log?

**Comment by RaigorJiang** [comment]
On the other hand, you can try to configure more JDBC parameters, such as
`&character_set_server= gbk&connectionCollation=gbk_bin`

example:
```
url: jdbc:mysql://127.0.0.1:3306/ProductDB01?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin
```

**Comment by RaigorJiang** [comment]
Hi @bai1986 ,
Is there any progress?

**Comment by bai1986** [comment]
> Hi @bai1986 ,
> Is there any progress?
hi：
   According to your guidance, the configuration file has been modified, and the Chinese garbled code problem still exists. Later, we can adjust the page code to solve it. So let's ignore this problem for the time being and carry out the next test. If you have any suggestions, I'll test it further

jdbc:mysql://127.0.0.1:3306/ProductDB05?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=GBK&character_set_server= gbk&connectionCollation=gbk_bin

**Comment by RaigorJiang** [comment]
OK, Thanks for your feedback.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
