### ISSUE TITLE
Insert the execution prompt data too long for column, why not throw an exception

### ISSUE THREAD

**Issue by ezio7584** [apache/shardingsphere#11664]
Execute the statement exception in the database, but no exception is thrown in the program

language: java
shardingsphere-jdbc-core-spring-boot-starter: 5.0.0-beta
mysql:5.7

**Comment by RaigorJiang** [comment]
Hi @ezio7584 
Can you provide more information, such as exception log？  And there is a similar issue, you can refer to #10138.

**Comment by tristaZero** [comment]
@ezio7584 Hi? So if this one was fixed, could you close it?
