### ISSUE TITLE
Add unit test for shardingsphere-shadow-core

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#11687]
Hi community,

This issue is for #11661

## Aim
Add unit test for shardingsphere-shadow-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] ShadowDataSourceConfigurationYamlSwapper
- [ ] ShadowTableConfigurationYamlSwapper
- [ ] ShadowRuleAlgorithmProviderConfigurationYamlSwapper

## Examples FYI
- ShadowRuleConfigurationYamlSwapperTest
- YamlRootRuleConfigurationsForYamlShadowRuleConfigurationTest

**Comment by WtlKoma** [comment]
I want do this.

**Comment by strongduanmu** [comment]
@WtlKoma Welcome.

**Comment by hoorf** [comment]
may be unit test will change for `fixme` tags remove

**Comment by soulasuna** [comment]
> may be unit test will change for `fixme` tags remove

Thank you very much for reminding. But that is something to be done after all the refactoring is completed.
