### ISSUE TITLE
Optimize code readability about MetaDataContextsBuilder#build method.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#11683]
### Is your feature request related to a problem?
No, just optimize code readability.
### Describe the feature you would like.
In build method
```Map<TableMetaData, TableMetaData> tableMetaData = SchemaBuilder.build(new SchemaBuilderMaterials(databaseType, dataSourceMap, rules, props));```
SchemaBuilder build a map with same key and value. The value is decorated by the key under certain conditions.
Both keyset and valueset are used in different places in the build method.
I suggest disassembling tableMetaData. The SchemaBuilder.build method should return a Schema object.

**Comment by tristaZero** [comment]
So? any progress?

**Comment by tuichenchuxin** [comment]
@tristaZero This issue is related to this issue #11718 . After it is merged, I will start to do this.

**Comment by tuichenchuxin** [comment]
It has been optimized, so I closed it.
