### ISSUE TITLE
[enhancement]how about add context parameters on encrypt and decrypt method

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#11689]
## Feature Request

**For English only**, other languages will not accept.

### Describe the feature you would like.
We need different key on each table/column to encrypt and decrypt with, how about add content parameters as below code, for example: logicTable, logicColumn etc? 

`/**
 * Encryptor.
 */
public interface Encryptor extends TypeBasedSPI {
    
    /**
     * Initialize.
     */
    void init();
    
    /**
     * Encode.
     * 
     * @param plaintext plaintext
     * @param encryptContextMap encrypt context map(logicTable and logicColumn)
     * @return ciphertext
     */
    String encrypt(Object plaintext, **Map<String, Object> encryptContextMap**);
    
    /**
     * Decode.
     * 
     * @param ciphertext ciphertext
     * @param decryptContextMap decrypt context map(logicTable and logicColumn)
     * @return plaintext
     */
    Object decrypt(String ciphertext, **Map<String, Object> decryptContextMap**);
}`

**Comment by tristaZero** [comment]
Hi @cheese8 Sorry for my late response. I am interested in your issue. Could I know why you want to add new parameters to these interfaces?

**Comment by cheese8** [comment]
Hi @tristaZero , as enterprise requirements described what we should encrypt sensitive data by keys/hash sensitive data by salt, for example  1 business unit per 1 key or 1 database/schema/table/column per 1 key... and add those parameters into decrypt and decrypt context are compatible with now implements.

**Comment by cheese8** [comment]
Not compatible, I meant that If context parameters  added, we can use it as needed, and also ignore it while not needed.

**Comment by tristaZero** [comment]
That way , do you think properties of an encryption implement for this interface are enough? e.g., `AES_KEY = "aes-key-value"` of `AESEncryptAlgorithm`.
If I do not reply promptly, you can send your WeChat number to my email (panjuan@apache.org) as to discuss this interesting issue.

**Comment by cheese8** [comment]
I think it's not enough because the key/salt should be related to the databaseName/id, schema, table and plain column.

**Comment by cheese8** [comment]
Thank you for encouraging me @tristaZero , I'll pr it soon as I take the below steps done
1、migrate the implementation from shardingsphere 4.1.1 to 5.0.0-RC1-SNAPSHOT
(I see the version of 5.0.0-RC1-SNAPSHOT was refactoring some places from the version 4.1.1)
2、test it passed my 3 samples

**Comment by tristaZero** [comment]
Go ahead. ;-)
