### ISSUE TITLE
The implement of GovernanceMetaDataContexts.renew(SchemaAddedEvent) is not correct

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11698]
Because of thread safe and performance reason, 
the design of GovernanceMetaDataContexts is using `new StandardMetaDataContexts` to instead of original one.

The method `GovernanceMetaDataContexts.renew(SchemaAddedEvent)` is modify the  original StandardMetaDataContexts, which is not correct, please fix it.

**Comment by menghaoranss** [comment]
I'll follow up.
