### ISSUE TITLE
when I send the 'select * from XX for update' statement to the proxy, proxy still sends the statement to the read-only node

### ISSUE THREAD

**Issue by cqiwencom** [apache/shardingsphere#11711]
I used shardingsphere-proxy-5.0 to config-readwrite-splitting. When I use this component to separate the reading and writing of the database, the back-end MySQL server is Mgr cluster, with one master and multiple slaves. The problem is: when I send the 'select * from T1 for update' statement to the proxy, proxy still sends the statement to the read-only node, so I can't add the update lock to the T1 table. Is there any way to specify the 'select... For update' statement to only go to writable nodes?

I was told that hint can be used to force routing to writable nodes. But I haven't found the relevant implementation method of proxy. Can anyone provide it? Thank you!

**Comment by tristaZero** [comment]
Could you try the [sctl](https://shardingsphere.apache.org/document/current/cn/features/dist-sql/syntax/sctl/) feature?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
