### ISSUE TITLE
Integrate with mybatis-plus failed to obtain the SQL exception information.

### ISSUE THREAD

**Issue by Jenyow** [apache/shardingsphere#11728]
### Which version of ShardingSphere did you use?
* shardingsphere-jdbc-core-spring-boot-starter：5.0.0-beta
* mybatis-plus-boot-starter：3.4.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
only use ShardingSphere-JDBC

### Expected behavior
The SQL exception information can be obtained.

### Actual behavior
Failed to obtain the SQL exception information.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. The database field 'status' set to mandatory.
2. use mybatis-plus provide the save function to save the entity not set status value. 
3. can print insert log without exception，but don't success to save the data.

**Comment by RaigorJiang** [comment]
Hello, for English only, please translate the issue, thank you.

**Comment by Jenyow** [comment]
> Hello, for English only, please translate the issue, thank you.

**Comment by RaigorJiang** [comment]
Hi @Jenyow 
Thanks for you report,  but you did not provide an exception log, so we cannot determine the cause of the error. Maybe similar to #10138,  you can try the master branch to check it.

**Comment by tristaZero** [comment]
HI @Jenyow ?

**Comment by Jenyow** [comment]
I has write a demo : https://github.com/Jenyow/sharding-demo.git,  please read the project's  readme.md, thanks.

**Comment by cocodroid** [comment]
My god.why don't you provide a exception log

**Comment by Jenyow** [comment]
> My god.why don't you provide a exception log in your demo...

Sorry, now I had add the log file to the demo.

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang
> I has write a demo : https://github.com/Jenyow/sharding-demo.git, please read the project's readme.md, thanks.

@Jenyow  OK, I am going to have a test.

**Comment by RaigorJiang** [comment]
> Hi @Jenyow
> Thanks for you report, but you did not provide an exception log, so we cannot determine the cause of the error. Maybe similar to #10138, you can try the master branch to check it.

Hi @Jenyow 
I have checked your demo project, the problem is duplicate with issue 10138. 
Now it was fixed by #10845, You can build from master branch and try again.

**Comment by Jenyow** [comment]
> > Hi @Jenyow
> > Thanks for you report, but you did not provide an exception log, so we cannot determine the cause of the error. Maybe similar to #10138, you can try the master branch to check it.
> 
> Hi @Jenyow
> I have checked your demo project, the problem is duplicate with issue 10138.
> Now it was fixed by #10845, You can build from master branch and try again.

@RaigorJiang OK, thanks.

**Comment by Jenyow** [comment]
> > Hi @Jenyow
> > Thanks for you report, but you did not provide an exception log, so we cannot determine the cause of the error. Maybe similar to #10138, you can try the master branch to check it.
> 
> Hi @Jenyow
> I have checked your demo project, the problem is duplicate with issue 10138.
> Now it was fixed by #10845, You can build from master branch and try again.

@RaigorJiang OK, thanks.

**Comment by RaigorJiang** [comment]
@Jenyow 
If your problem is solved, please close this issue, thanks.

**Comment by Jenyow** [comment]
Wait for the next release.

**Comment by tristaZero** [comment]
@Jenyow It's coming soon!
