### ISSUE TITLE
Map<String, Integer> dataTypes = DataTypeLoader.load(connection.getMetaData())里面没有json类型

### ISSUE THREAD

**Issue by dyplus** [apache/shardingsphere#11732]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
@dyplus For English only, please translate the issue title to English first.

**Comment by menghaoranss** [comment]
For English only, other languages will not accept.
