### ISSUE TITLE
EncryptRule#findEncryptTable method match is case sensitive

### ISSUE THREAD

**Issue by xuzhouzhangtongtong** [apache/shardingsphere#11744]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

org.apache.shardingsphere.encrypt.rule.EncryptRule#findEncryptTable

     tables.get(logicTable)
     I want to be able to configure case insensitivity here.

**Comment by xuzhouzhangtongtong** [comment]
because mybatis xml sql ， Both upper and lower case of the table name exist

**Comment by tristaZero** [comment]
Hi which version are you using? Could you try the latest release, i.e, beta?

**Comment by sandynz** [comment]
> because mybatis xml sql ， Both upper and lower case of the table name exist

Hi @xuzhouzhangtongtong , just use real table name might be better.

**Comment by tristaZero** [comment]
If there is no feedback, we have to close it.

**Comment by terrymanu** [comment]
No response anymore, I just close the issue.
