### ISSUE TITLE
I can't understand the following GovernanceMetaDataContexts#renew() method. I've received ZK deletion event here. Why do I have to delete it manually?

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#11747]
Recently, I prepare adding read-write data source failover based on sharingsphere proxy (automatically detect the master-slave information of MySQL group replication and automatically update it to 'xx/metadata/userdb/rules' of zookeeper). I can't understand the following renew method. I've received ZK deletion event here. Why do I have to delete it manually?

https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-context/src/main/java/org/apache/shardingsphere/governance/context/metadata/GovernanceMetaDataContexts.java#L203

**Comment by wl4g** [comment]
Another question is, how do you use 'xx/states/primarynodes' and 'xx/states/datanodes'  ?  I want to use it when adding failover.

**Comment by menghaoranss** [comment]
> Recently, I prepare adding read-write data source failover based on sharingsphere proxy (automatically detect the master-slave information of MySQL group replication and automatically update it to 'xx/metadata/userdb/rules' of zookeeper). I can't understand the following renew method. I've received ZK deletion event here. Why do I have to delete it manually?
> 
> https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-context/src/main/java/org/apache/shardingsphere/governance/context/metadata/GovernanceMetaDataContexts.java#L203

@wl4g Thanks for your feedback，this issue has been fixed in the master branch.

**Comment by menghaoranss** [comment]
> Another question is, how do you use 'xx/states/primarynodes' and 'xx/states/datanodes' ? I want to use it when adding failover.
> Because I only searched here in all the codes, and the settings are empty, https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java#L111

I will follow up.

**Comment by menghaoranss** [comment]
> Another question is, how do you use 'xx/states/primarynodes' and 'xx/states/datanodes' ? I want to use it when adding failover.
> Because I only searched here in all the codes, and the settings are empty, https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java#L111

If data nodes changed, `db_discovery` will post event to `governance`, you can search the following code in `MGRDatabaseDiscoveryType.java`
```
ShardingSphereEventBus.getInstance().post(new DataSourceDisabledEvent(schemaName, entry.getKey(), true));
```

**Comment by wl4g** [comment]
> > Another question is, how do you use 'xx/states/primarynodes' and 'xx/states/datanodes' ? I want to use it when adding failover.
> > Because I only searched here in all the codes, and the settings are empty, https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java#L111
> 
> If data nodes changed, `db_discovery` will post event to `governance`, you can search the following code in `MGRDatabaseDiscoveryType.java`
> 
> ```
> ShardingSphereEventBus.getInstance().post(new DataSourceDisabledEvent(schemaName, entry.getKey(), true));
> ```
Thank you very much for your reminder. I almost made wheels again. How to configure this Mgr discovery? Are there any examples?

**Comment by menghaoranss** [comment]
> > > Another question is, how do you use 'xx/states/primarynodes' and 'xx/states/datanodes' ? I want to use it when adding failover.
> > > Because I only searched here in all the codes, and the settings are empty, https://github.com/apache/shardingsphere/blob/5.0.0-beta/shardingsphere-governance/shardingsphere-governance-core/src/main/java/org/apache/shardingsphere/governance/core/registry/RegistryCenter.java#L111
> > 
> > 
> > If data nodes changed, `db_discovery` will post event to `governance`, you can search the following code in `MGRDatabaseDiscoveryType.java`
> > ```
> > ShardingSphereEventBus.getInstance().post(new DataSourceDisabledEvent(schemaName, entry.getKey(), true));
> > ```
> 
> Thank you very much for your reminder. I almost made wheels again. How to configure this Mgr discovery? Are there any examples?

refter to: 
https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/config-database-discovery.yaml

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
