### ISSUE TITLE
Something wrong with the document of GOVERNANCE 

### ISSUE THREAD

**Issue by LeeGuoPing** [apache/shardingsphere#11764]
## Question

one. GovernanceConfiguration class has no param "name", and add param "overwrite"
two. RegistryCenterConfiguration class add param "namespace"

the document see: https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/java-api/governance/

**Comment by menghaoranss** [comment]
Governance is being refactored now,  could you commit a PR to fix it?

**Comment by LeeGuoPing** [comment]
ok @menghaoranss

**Comment by LeeGuoPing** [comment]
@menghaoranss  brother, I have update the documents, both English and Chinese.
