### ISSUE TITLE
is there some official performance report to prove the performance gap between 5.0 and 4.0,3.0?

### ISSUE THREAD

**Issue by jackjoesh** [apache/shardingsphere#11761]
is there some official performance report to prove the performance gap between 5.0 and 4.0, 3.0?
Because we want to upgrade from 3.1 to 5.0, we must prove the performance before staring project, thank you.

**Comment by menghaoranss** [comment]
@jackjoesh Which project did you use, ShardingSphere-JDBC or ShardingSphere-Proxy?

**Comment by jackjoesh** [comment]
> ShardingSphere-JDBC

ShardingSphere-JDBC

**Comment by tristaZero** [comment]
Hi @jackjoesh We suggest you update to 5.x which contains many bug-fix and new enhancements and will have future supports.
When it comes to the performance report, it shows like 3.1 is 14'000 TPS, while the master branch is 12'000 TPS (still under our tuning) from my local env of mac. Do not worry, performance tests and improvements are our aims this month. That means the next release will include performance improvenments.

**Comment by jackjoesh** [comment]
> tuning

Great!  As you said, we are very much looking forward to upgrading to the new version to reduce maintenance costs.
Because the tps of our system is one hundred thousand level, so the performance is very important, thank you for help

**Comment by tristaZero** [comment]
If this issue is fixed, could you close it? Thanks.

**Comment by jackjoesh** [comment]
> If this issue is fixed, could you close it? Thanks.

ok
