### ISSUE TITLE
front page grammar problem

### ISSUE THREAD

**Issue by Steven-78** [apache/shardingsphere#11773]
"Consist" shouldn't be used in passive voice.  It should be "consist of" instead of "consisted of".  

![image](https://user-images.githubusercontent.com/35221791/129120851-c8559f0d-6b98-4ef2-9c43-569f2bf62763.png)

**Comment by yy2so** [comment]
Hi Steven, good find. I'd just like to suggest that the correct format should be "consisting of" (add -ing)

By the way you're welcome to join our community on Slack: 
https://join.slack.com/t/apacheshardingsphere/shared_invite/zt-sbdde7ie-SjDqo9~I4rYcR18bq0SYTg

**Comment by menghaoranss** [comment]
> Hi @Steven-78, good find. I'd just like to suggest that the correct format should be "consisting of" (add -ing)
> 
> By the way you're welcome to join our community on Slack:
> https://join.slack.com/t/apacheshardingsphere/shared_invite/zt-sbdde7ie-SjDqo9~I4rYcR18bq0SYTg

@yy2so Thanks for your suggestion.  
@Steven-78 You are welcome to submit a PR to fix this issue.

**Comment by himanshu007-creator** [comment]
hi! is @Steven-78 allows, may I work on this issue?
Thanks

**Comment by menghaoranss** [comment]
> hi! is @Steven-78 allows, may I work on this issue?
> Thanks

@himanshu007-creator welcome, I will assign this issue to you, looking forward to your PR.
