### ISSUE TITLE
There was a feign call in the transaction and the data did not roll back properly

### ISSUE THREAD

**Issue by lovegames** [apache/shardingsphere#11788]
## Question
When using distributed transaction, the feign call threw an exception, but the transaction did not roll back properly. It is suspected that the code entered fallback, so the transaction could not be rolled back properly. Is there any good solution

`@ShardingTransactionType(value = TransactionType.XA)
    @Transactional(rollbackFor = Exception.class)
    @Override
    public Integer testTransactionXA(User user) {
        userMapper.insert(user);

        SysOrganizationDto dto = new SysOrganizationDto();
        dto.setName("测试事务");
        sysOrganizationFeign.insert(dto);
        userMapper.insert(user);

        return null;
    }

@Component
@Slf4j
public class SysOrganizationFallBackFactory implements FallbackFactory<SysOrganziationApi> {
    @Override
    public SysOrganziationApi create(Throwable throwable) {
        log.error("SysOrganizationFallBackFactory error: ", throwable);
        return new SysOrganziationApi() {

            @Override
            public Long insert(SysOrganizationDto dto) {
                return null;
            }

}
`

**Comment by terrymanu** [comment]
Could change the title for search friendly?

**Comment by tristaZero** [comment]
Hi @lovegames which version did you test?

**Comment by lovegames** [comment]
<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-transaction-spring-boot-starter</artifactId>
            <version>3.1.0</version>
        </dependency>

**Comment by tristaZero** [comment]
@lovegames Thanks, @cherrylzhao do you have time to have a look?

**Comment by lovegames** [comment]
Can it be solved? @tristaZero

**Comment by tristaZero** [comment]
Sorry, I suggest you try the 5.0.0-beta release, and the distributed transaction will be our target in the next release.
