### ISSUE TITLE
Insert too long data, no exception be thrown,no error log, no rollback. [it should throw exception]

### ISSUE THREAD

**Issue by qanson** [apache/shardingsphere#11795]
### Which version of ShardingSphere did you use?
5.0-Beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
The database field length is only 50, however when inserting test data , the length of data is more than 50. It should have thrown 
an exception. There should be  exception and rollback.
### Actual behavior
No exception ,the log runs well without err log and the program continue to run and no rollback happen. There should throw an exception
### Reason analyze (If you can)
I assume in the ShardingSphere-JDBC source code, there may try catch the sql exception ,so we can't rollback. 
 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
code:
![image](https://user-images.githubusercontent.com/16503640/129301894-6db29add-76bc-4813-b8b3-ec1ef6a4608b.png)

log:
![log](https://user-images.githubusercontent.com/16503640/129302556-74208340-27e6-4e49-8d5b-728567bc95ec.png)

### Example codes for reproduce this issue (such as a github link).
only the sharding-jdbc-tables example, and in java code , insert the status field more than 50 charcaters.

**Comment by zjcnb** [comment]
Hi， you can try it again in ShardingSphere 5.0.0-RC1-SNAPSHOT

**Comment by zjcnb** [comment]
Hi @qanson,  you can try it at 5.0.0-RC1-SNAPSHOT. It should be fixed.

**Comment by qanson** [comment]
> Hi @qanson, you can try it at 5.0.0-RC1-SNAPSHOT. It should be fixed.

Thanks a lot .

**Comment by tristaZero** [comment]
@qanson Hi if this issue is fixed, could you close it?

**Comment by RaigorJiang** [comment]
Duplicate with #10138.
