### ISSUE TITLE
Add test cases in FederateJDBCExecutorTest to assert federate query optimization.

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#11792]
## Add FederateJDBCExecutorTest to assert FederateJDBCExecutorTest

Below action should be taken:
- add JOIN SQL in the test cases.
- add subquery SQL in the test cases.
- mock catalog reader, to change the metadata of the table.
- add more test cases related to federated queries.

**Comment by sandynz** [comment]
Hi @wgy8283335 , are you working on this issue?

**Comment by wgy8283335** [comment]
> Hi @wgy8283335 , are you working on this issue?

Yes

**Comment by wgy8283335** [comment]
This issue could be closed, as the tasks have been moved into another issue: 'Tasks in the federate optimizer'
#12709
