### ISSUE TITLE
Whether to add restricted full routing

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#11801]
Hi all,

 I found that the current insert has increased the limit, please refer to ： 

```
 public void postValidate(final ShardingRule shardingRule, final SQLStatementContext<InsertStatement> sqlStatementContext,
                             final RouteContext routeContext, final ShardingSphereSchema schema) {
        if (needCheckDatabaseInstance) {
            Preconditions.checkState(routeContext.isSingleRouting(), "Sharding value must same with subquery.");
        }
        if (routeContext.isSingleRouting()) {
            return;
        }
        String tableName = sqlStatementContext.getSqlStatement().getTable().getTableName().getIdentifier().getValue();
        if (shardingRule.isBroadcastTable(tableName)) {
            return;
        }
        if (routeContext.getOriginalDataNodes().stream().anyMatch(dataNodes -> dataNodes.size() > 1)) {
            throw new ShardingSphereException("Insert statement does not support sharding table routing to multiple data nodes.");
        }
    }
```

Question : Is it also necessary to add such processing during update and delete?

**Comment by tristaZero** [comment]
@zjcnb Did you let @strongduanmu know about this issue?

**Comment by strongduanmu** [comment]
@zjcnb For update and delete statements, users may perform operations without the sharding column. Therefore, this judgments should not be added to update and delete statements.

**Comment by zjcnb** [comment]


> @zjcnb For update and delete statements, users may perform operations without the sharding column. Therefore, this judgments should not be added to update and delete statements.

Yes,  it 's have this actual situation, i will close this issue
