### ISSUE TITLE
java.lang.String cannot be cast to org.apache.shardingsphere.infra.yaml.config.YamlRuleConfiguration

### ISSUE THREAD

**Issue by lzq574947385** [apache/shardingsphere#11831]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC

### Expected behavior
Successfully started the project

### Actual behavior
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.shardingsphere.infra.yaml.config.YamlRuleConfiguration
### Example codes for reproduce this issue (such as a github link).
rules:
  #配置分片规则
  tables:
    #配置商户汇总表cc_restaurant_collect_data规则
    cc_restaurant_collect_data:
      actualDataNodes: ds0.cc_restaurant_collect_data$->{2020..2021}0$->{1..9},ds0.cc_restaurant_collect_data$->{2020..2021}1$->{0..2}
      #配置分表策略
      tableStrategy:
        complex:
          shardingColumns: id,collectDate
          shardingAlgorithmName: name11

  #分片算法配置
  shardingAlgorithms:
    #分片算法名称
    name11:
      #分片算法类型
      type: ComplexKeysShardingAlgorithm
      #分片算法属性配置
      props:
        algorithmClassName：: com.vortex.cloud.envcloud.cc.config.sharding.RestaurantCollectDataShardingAlgorithm

props: #属性配置
  sql-show: true #是否开启SQL显示，默认值: false

**Comment by lzq574947385** [comment]
![image](https://user-images.githubusercontent.com/61236603/129482288-227bd9d2-2b3e-4c9c-bab0-3bfe25c006db.png)

**Comment by lzq574947385** [comment]
![image](https://user-images.githubusercontent.com/61236603/129482311-2684b9bb-3d3e-4eb9-a24d-2b2993fc5f7e.png)

**Comment by vince7839** [comment]
@lzq574947385 Hi,I think your config is in incorrect,add "- !SHARDING" under "rules" and try again please.

**Comment by lzq574947385** [comment]
Thanks!
