### ISSUE TITLE
Please make ShardingSphere - JDBC work for write DB operation even when one or several shards were broken

### ISSUE THREAD

**Issue by yc-22** [apache/shardingsphere#11852]
### Is your feature request related to a problem?
I am using Spring Boot + ShardingSphere - JDBC. So far, it seems that when one shard is broken, other shards can't be used for write DB operation as well while the read DB operation still can work fine.

### Describe the feature you would like.
Can you please make it work for write DB operation even when one or several shards were broken? Thanks!

**Comment by terrymanu** [comment]
Duplicate with #11892
