### ISSUE TITLE
how statement to sql(string)?

### ISSUE THREAD

**Issue by hsw409328** [apache/shardingsphere#11862]
## Question

**For English only**, other languages will not accept.

use sql-parse-engine 

`public static SQLStatement statement(final String databaseType, final String sql, final Boolean useCache) {
        ParseTree tree = new SQLParserEngine(databaseType).parse(sql, useCache);
        SQLVisitorEngine sqlVisitorEngine = new SQLVisitorEngine(databaseType, "STATEMENT", new Properties());
        SQLStatement sqlStatement = sqlVisitorEngine.visit(tree);
        return sqlStatement;
    }`

How to convert an object to an executed SQL string？

**Comment by strongduanmu** [comment]
@hsw409328 The original SQL is String type. Why convert the parsed result into String?

**Comment by hsw409328** [comment]
> @hsw409328 The original SQL is String type. Why convert the parsed result into String?

I used the parsing engine alone to rewrite the where condition. I want to parse the changed object back to SQL string

**Comment by hsw409328** [comment]
unparse engine not found!

**Comment by tristaZero** [comment]
Hi @hsw409328 Sorry I can not catch you.
Do you want to convert an SQLStatement into a rewritten SQL? Could I get the necessity? ShardingSphere will generate the to-execute by router and rewriter, which is a little complex.

**Comment by hsw409328** [comment]
> Hi @hsw409328 Sorry I can not catch you.
> Do you want to convert an SQLStatement into a rewritten SQL? Could I get the necessity? ShardingSphere will generate the to-execute by router and rewriter, which is a little complex.

(sql-parse-engin) don't support SQLStatement to SQL ? Is that so?

**Comment by tristaZero** [comment]
Hi @hsw409328 
Supposing the public API, the answer is yes. Currently, we do not provide an independent API to revert an SQLStatement to a SQL, while we implement it internally.
Why do you want this feature?

**Comment by hsw409328** [comment]
> Hi @hsw409328
> Supposing the public API, the answer is yes. Currently, we do not provide an independent API to revert an SQLStatement to a SQL, while we implement it internally.
> Why do you want this feature?

When I make a MySQL query, I automatically add conditions in the where part. I need to parse the original SQL, assemble it with SQLStatement, and finally restore it to executable SQL
