### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#11865]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Expected behavior
Build should be successful
### Actual behavior
On running `mvn clean install`
![image (1)](https://user-images.githubusercontent.com/64654203/129733327-9c47f87a-5f25-4680-8e11-e99f6b255318.png)

On running maven with -X switch
![image (2)](https://user-images.githubusercontent.com/64654203/129733383-2c89d703-3d9b-4af5-b9cb-7ddfcc2d6443.png)
![image (3)](https://user-images.githubusercontent.com/64654203/129733389-9252ecd1-5620-4459-842c-4b109e2db8c5.png)

On running `mvn -Dmaven.javadoc.skip=true -Djacoco.skip=true -DskipITs -DskipTests clean install`
![image](https://user-images.githubusercontent.com/64654203/129733104-7f5be505-b3e2-42f0-832a-e3a7b29ee3b0.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run  `mvn clean install`
Run maven with -X switch
Run `mvn -Dmaven.javadoc.skip=true -Djacoco.skip=true -DskipITs -DskipTests clean install`

**Comment by TeslaCN** [comment]
I'm not sure if the path is too long in Windows environment, try moving your project directory to `C:/` or somewhere to shorten your path.

**Comment by dachuan9e** [comment]
The root cause is that the path has space. @Swastyy

**Comment by Swastyy** [comment]
Hi @TeslaCN and @dachuan9e, thanks for answering. Changing the project location to shorter path worked for me although while cloning I got the point that the file paths are very long but I didn't knew that it will cause problems in compilation/build. 
If this also happens incase of spaces then @dachuan9e thanks for solving it. Since my problem is solved now we can decide if this issue to close or not.
