### ISSUE TITLE
How to get the latest docker images of shardingsphere5.x-proxy?

### ISSUE THREAD

**Issue by hexingfu** [apache/shardingsphere#11877]
when I execute this docker command "docker pull apache/shardingsphere-proxy" from the offical document,why I can not get the image?

**Comment by TeslaCN** [comment]
Try
```bash
docker pull apache/sharding-proxy
```

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
