### ISSUE TITLE
Add skywalking-eyes for license header check.

### ISSUE THREAD

**Issue by wu-sheng** [apache/shardingsphere#11876]
## Feature Request

I am asking whether someone could add [skywalking-eyes](https://github.com/apache/skywalking-eyes) as a GHA in the SharingSphere repo(s). It provides a very easy way to check license header, and directly tag them on the PR.
Also, in the next 0.2.0 release, it would provide license resolution for dependency libs, we could make sure all dependencies' licenses are expected.

### Is your feature request related to a problem?

License check.

**Comment by totalo** [comment]
hi, Can I do this?

**Comment by wu-sheng** [comment]
Assigned to you, this should be not hard. And many repo(s) in SkyWalking, APISIX, Apollo, TiDB have been using this. You could choose which repo you want to take a reference.

**Comment by totalo** [comment]
> Assigned to you, this should be not hard. And many repo(s) in SkyWalking, APISIX, Apollo, TiDB have been using this. You could choose which repo you want to take a reference.

ok.thx

**Comment by tristaZero** [comment]
Hi what's the difference between Apache rat and this one? Is there any doc?
