### ISSUE TITLE
Please make ShardingSphere - JDBC work for write DB operation when one or several shards are broken

### ISSUE THREAD

**Issue by yc-22** [apache/shardingsphere#11892]
### Which version of ShardingSphere did you use?
ShardingSphere 5.0.0-beta 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Write DB operations can perform well when one or several shards are broken as read DB operations.
### Actual behavior
The write operations would cause errors and trigger the project's written retry mechanism when one DB shard was broken. (When the write operation is gonna write something to the remaining db shards instead of the broken one.)
The read operations can still perform well in that scenario. 
Error: Please see the attached error log.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
` spring.shardingsphere.rules.sharding.tables.LedgerEntry.actual-data-nodes: ledger$->{0..3}.LedgerEntry `
- Set `spring.datasource.continue-on-error: true`
- Drop one ledger DB. Then write operation can't perform for other DB shards.

### Example codes for reproduce this issue (such as a github link).

![errorLog1](https://user-images.githubusercontent.com/84406645/129979941-b7c4004e-d42f-4e48-9fb1-c422d7de9e1a.PNG)
![errorLog2](https://user-images.githubusercontent.com/84406645/129979944-3b5fa366-9c50-4250-9224-6eea3bde8e2c.PNG)

**Comment by tristaZero** [comment]
Hi @yc-22 I did not get you. Could you provide your configuration to let me which feature you want to use? Readwrite-splitting or sharding?

**Comment by yc-22** [comment]
> Hi @yc-22 I did not get you. Could you provide your configuration to let me which feature you want to use? Readwrite-splitting or sharding?

Sharding. I want to shard 4 data sources for both read and write operation. For now, if I drop one shard, the write db operation would completely fail. (Even if the data is supposed to be written into healthy shard) But the read operation can still perform well. So is there some setting I can configure to make write db operation still perform in this scenario or this is a bug?

**Comment by tristaZero** [comment]
Hi @yc-22 Sorry for my late reply.
Do you mean, when one DB is offline, an `UPDATE` SQL will fail but a `QUERY` SQL succeeds?
It's a little wired. Could you set `sql-show` = `true` to output more details in log?

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
