### ISSUE TITLE
missing pakage org.apache.shardingsphere.sql.parser.autogen

### ISSUE THREAD

**Issue by hexingfu** [apache/shardingsphere#11893]
When I cloned the whole project into my local development environment, I found that there was a missing package (org. Apache. Shardingsphere. SQL. Parser. Autogen). Where should I get this package?

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/others/faq/#2-why-do-some-compiling-errors-appear-why-did-not-the-idea-index-the-generated-codes
