### ISSUE TITLE
'HINT_INLINE' sharding algorithm cannot take effect.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#11918]
### Which version of ShardingSphere did you use?
 master branch

### Problem
 Use `HINT_INLINE` sharding algorithm, but `algorithm-expression` cannot  take effect.

### Reason analyze (If you can)
 Class `HintInlineShardingAlgorithm` implements `TypedSPI`, and the properties value is assigned via `setProps` method like in `InlineShardingAlgorithm`. 
 However, in class `HintInlineShardingAlgorithm`, the name of the field `properties` does not match the `props` required by the interface.

### How to fix it
1. change  field name `properties` to `props` in `HintInlineShardingAlgorithm`;
2. fix the `set` method name in `HintInlineShardingAlgorithmTest`;

For more process information, please refer to [Contributor Guide](https://shardingsphere.apache.org/community/en/contribute/contributor/) and [Code of Conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/).

**Comment by Superainbower** [comment]
i want to fix it

**Comment by strongduanmu** [comment]
@Superainbower Welcome.

**Comment by RaigorJiang** [comment]
@Superainbower 
Welcome to contribute, if you have any questions, you can ask here.
