### ISSUE TITLE
my project both use mysql and mssql；how to use shardingsphere。

### ISSUE THREAD

**Issue by soca2013** [apache/shardingsphere#11947]
my project both use mysql and mssql；how to use shardingsphere。
   can you  support  multi  schameName for shardingsphere?

**Comment by menghaoranss** [comment]
In the master branch, you can define  two different schemaNames for datasources.

**Comment by soca2013** [comment]
> In the master branch, you can define two different schemaNames for datasources.

Give an example，please，thank you。

**Comment by RaigorJiang** [comment]
@soca2013 
Please refer to [example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-proxy-example/shardingsphere-proxy-boot-mybatis-example/src/main/resources/conf), just put multi config files.
