### ISSUE TITLE
timestamp nanos Inaccurate

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#11953]
ShardingSphere-Proxy-5.0.0-beta

create table table_1
(
    id              int(11) unsigned auto_increment comment '自增id'
    **test_date**       datetime(3)                            null
)

mysql-connector-java-5.1.48 
jdbcUrlParam: useServerPrepStmts=true&cachePrepStmts=true

### Expected behavior

datetime(3) 2021-8-23 10:06:33.599

### Actual behavior

datetime(3) 2021-8-23 10:06:33.000

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/20919316/130420120-4ee74e40-e465-4fbf-a361-91883ed03103.png)

here, getNanos is always 6 digits int

**Comment by Swastyy** [comment]
@strongduanmu , @tristaZero I really want to work on this. Can you help me out for how to start.

**Comment by strongduanmu** [comment]
Hi @Swastyy , welcome back, to be honest, this issue is not simple and may require some skills in the MySQL protocol. I think @TeslaCN  can provide you with a good help.

**Comment by linghengqian** [comment]
Will this affect ShardingSphere JDBC 5.1.0? I'm not quite sure where this code is located.

**Comment by soulasuna** [comment]
I can try.

**Comment by linghengqian** [comment]
> Will this affect ShardingSphere JDBC 5.1.0? I'm not quite sure where this code is located.

- I have seen it in `org.apache.shardingsphere.db.protocol.mysql.packet.command.query.binary.execute.protocol.MySQLDateBinaryProtocolValue` in `5.1.0`. It means `result.setNanos(payload.readInt4() *1_000_000_000);`? Looks like it would cause `org.apache.shardingsphere.db.protocol.mysql.packet.command.query.binary.execute.protocol.MySQLDateBinaryProtocolValueTest#assertReadWithElevenBytes()` to fail.
- ![image](https://user-images.githubusercontent.com/20187731/156550137-76cc2c0e-ddd4-4c47-9a2f-352b2f671d7e.png)

**Comment by soulasuna** [comment]
Inconsistent accuracy of `TIMESTAMP` between `MySQL` and `JDBC` caused problems.

MySQL `TIMESTAMP` with up to microseconds (6 digits) precision.
Refer to MySQL official documentation:
https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html

JDBC `java.sql.Timestamp` with up to microseconds (9 digits) precision
![pr](https://user-images.githubusercontent.com/33794770/156715465-2aee30ee-84c2-42e1-97ed-1c2fe665e2a0.jpg)

I did a precision fit.
