### ISSUE TITLE
Summary of integration testing issues

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#11951]
## PG Data Source Related Testing

The most important issue: [#11611](https://github.com/apache/shardingsphere/issues/11611) 
The number of connections even increased to several thousand

### DQL
common issues:

[#11382](https://github.com/apache/shardingsphere/issues/11382)

PostgreSQL default order by collate:
![image](https://user-images.githubusercontent.com/76552510/130409938-014acbf8-1906-41e9-804c-1fa23f8723c8.png)

#### encrypt

[#11408](https://github.com/apache/shardingsphere/issues/11408)

#### encrypt
[#11465](https://github.com/apache/shardingsphere/issues/11465)

----
## Testing support for multiple database types

The remaining data types to be completed are as follows.：

- Oracle
- SqlServer

Since the tests are based on docker containers, but there are no officially provided containers for the above database types, we cannot continue to build the integration test framework.

Therefore new strategies need to be discussed, or custom containers need to be created.

----
## Governance module issues

There are still potential problems, but due to the anomalous number of connections mentioned above, it is not possible to continue the exploration.

**Comment by tristaZero** [comment]
@strongduanmu Hi could you look at these issues?

**Comment by strongduanmu** [comment]
> @strongduanmu Hi could you look at these issues?

@tristaZero I will check it.

**Comment by strongduanmu** [comment]
All the exception reported above have been fixed, and this issue can be closed.
