### ISSUE TITLE
Plan to support `information_schema`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#11994]
Hi community,

We are working on a plan for ShardingSphere-Proxy to support queries on `information_schema` to resolve some remaining issues. At the same time, this work can also solve the problem that some SQL clients cannot connect to the Proxy.

Since this is an important and complex feature, we need to implement it step by step.

> _Notice: Some tables or columns are not applicable in distributed scenarios and will not be fully supported._ 

First, we will start with `MySQL`.

If you have more related questions or suggestions, please comment in this issue.

#### Related issues:
- #6693
- #11992
- #3572

#### Sample SQLs:

- SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA
- SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'
- select * from information_schema.columns where table_schema = 'sharding_db';

#### Supported:
- information_schema.SCHEMATA #12011

**Comment by lanchengx** [comment]
🥷
