### ISSUE TITLE
shardingsphere-jdbc actual-data-nodes needs to be dynamically configured

### ISSUE THREAD

**Issue by chenzw93** [apache/shardingsphere#12003]
hi:
There is such a scenario: I want to use the sub-table function, whether the value of actual-data-nodes can be dynamically refreshed. That is to say how to dynamically expand the sub-table and refresh the configuration of the sub-table.

For example, I use time to divide tables. At first, actual-data-nodes configured t_call_record_${[202108]}, but later, new tables tbl_log_202109, tbl_log_202110..., how to give the newly created table shardingsphere management?
Note: The table structure of tbl_log_202108 and tbl_log_202109 are exactly the same

**Comment by chenzw93** [comment]
@Comven 
yeah, thank you
I saw the IntervalShardingAlgorithm algorithm class you were talking about, and there is another AutoIntervalShardingAlgorithm algorithm class, which only exists in the 5.0.0-beta version.

If it is version 4.1.1, the current method is to use reflection to refresh the properties in the TableRule object. It feels quite inelegant. Are there any other extension points?

**Comment by chenzw93** [comment]
@avalon5666 
hi, brother
Do you have a better solution?

**Comment by avalon5666** [comment]
@chenzw93 Sorry, I misunderstood before.
It seem you need dynamically reload sharding rule?

**Comment by chenzw93** [comment]
@avalon5666 yes,  any good extension points of version 4.1.1?

**Comment by avalon5666** [comment]
I'm not familiar with this part of code.
Recommand to try 5.x [governance](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/usage/governance/), because 4.x is no longer maintained.
