### ISSUE TITLE
5.0.0-beta The same error occurs :  Batch update returned unexpected row count from update [0]; actual row count: 24; expected: 1

### ISSUE THREAD

**Issue by luoyexiaoran** [apache/shardingsphere#12029]
version :    shardingsphere-jdbc-core  5.0.0-beta
project:   springboot+hibernate+ shardingsphere-jdbc-core 
Here is my configuration:

> #sharding-jdbc分表配置
rules:
- !SHARDING
  # 配置分片规则
  tables:
    # 配置商户汇总表cc_restaurant_collect_data规则
    cc_restaurant_collect_data:
      actualDataNodes: ds0.cc_restaurant_collect_data$->{2020..2021}0$->{1..9},ds0.cc_restaurant_collect_data$->{2020..2021}1$->{0..2}
      # 配置分表策略
      tableStrategy:
        complex:
          shardingColumns: collectDate
          shardingAlgorithmName: cc_restaurant_collect_data
    # 配置商户汇总表cc_sypoint_collect_data规则
    cc_sypoint_collect_data:
      actualDataNodes: ds0.cc_sypoint_collect_data$->{2020..2021}0$->{1..9},ds0.cc_sypoint_collect_data$->{2020..2021}1$->{0..2}
      # 配置分表策略
      tableStrategy:
        complex:
          shardingColumns: collectDate
          shardingAlgorithmName: cc_sypoint_collect_data
    # 配置商户汇总表cc_rfid规则
    cc_rfid:
      actualDataNodes: ds0.cc_rfid$->{2020..2021}0$->{1..9},ds0.cc_rfid$->{2020..2021}1$->{0..2}
      # 配置分表策略
      tableStrategy:
        complex:
          shardingColumns: time
          shardingAlgorithmName: cc_rfid
    # 配置商户汇总表cc_weighbridge规则
    cc_weighbridge:
      actualDataNodes: ds0.cc_weighbridge$->{2020..2021}0$->{1..9},ds0.cc_weighbridge$->{2020..2021}1$->{0..2}
      # 配置分表策略
      tableStrategy:
        complex:
          shardingColumns: grossDateTime
          shardingAlgorithmName: cc_weighbridge
  shardingAlgorithms:
    cc_restaurant_collect_data:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.RestaurantCollectDataShardingAlgorithm
    cc_sypoint_collect_data:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.SypointCollectDataShardingAlgorithm
    cc_rfid:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.RfidDataShardingAlgorithm
    cc_weighbridge:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.WeighbridgeShardingAlgorithm

  bindingTables:  #绑定表规则列表
    - cc_restaurant_collect_data
    - cc_sypoint_collect_data
    - cc_rfid
    - cc_weighbridge

props: #属性配置
  #是否开启SQL显示，默认值: false
  sql-show: true

![image](https://user-images.githubusercontent.com/48896854/130945492-c0e93775-cd5f-4b4c-a0ac-f6deb8e20f22.png)
it was there and it was fixed,But now it's back

**Comment by avalon5666** [comment]
Can you show me the logic sql.

**Comment by luoyexiaoran** [comment]
> Can you show me the logic sql.
> I think the logic sql also insert statement, pls check your sql.
![image](https://user-images.githubusercontent.com/48896854/131272310-bfb40712-4d39-47d8-8f36-55ac25bb759d.png)

this is my logic sql: insert into cc_weighbridge (createTime, lastChangeTime, status, beenDeleted, deletedTime, deleteManId, deleteManName, saveManId, saveManName, saveTime, updateManId, updateManName, updateTime, tenantCode, tenantId, areaId, areaInnerCode, areaName, beenAlarm, carCode, carId, code, collectWeight, dataOperateType, deviation, disposeUnitCode, driver, errorWeight, grossDateTime, grossWeight, handleUnit, handleUnitInnerCode, icCode, isRun, memo, netWeight, no, offset, productId, productName, productType, repairFlag, setDeviation, sourceUnit, syCompanyId, syCompanyName, tareDateTime, tareWeight, tenantName, transformArea, transformAreaId, transformCarNo, transportUnit, transportUnitInnerCode, unitPrice, url1, url2, urlType, weighMan, weightNo, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
yes!I do want to insert a record,But it has an error when Hibernate doflush!
I only inserted one piece of data, but it returned the number of affected rows is error, which I think is the actual number of tables for all the sub-tables

**Comment by avalon5666** [comment]
Is it a sharding table or broadcast table?

**Comment by luoyexiaoran** [comment]
> Is it a sharding table or broadcast table?
> Pls check your WeighbridgeShardingAlgorithm.
it is a sharding table not  broadcast table!
![image](https://user-images.githubusercontent.com/48896854/131274050-ecc82c33-3e1d-402d-bcc6-4c0ca6c66fe4.png)
It does not enter a breakpoint when saved!Is it because I getType() returns null?
![image](https://user-images.githubusercontent.com/48896854/131274063-8a6116dc-52c9-4d0d-9d1b-6c345832ea1e.png)

**Comment by avalon5666** [comment]
Can you debug the cc_weighbridge table stragegy is set correct?

**Comment by luoyexiaoran** [comment]
> Can you debug the cc_weighbridge table stragegy is set correct?

Can you correctly access my custom sharding logic?When I carry a shard column query, it normally enters the custom shard logic!But when a query does not carry a shard column condition or save. it cannot enter custom shard logic,I consider this normal when queries do not carry shard criteria.

![image](https://user-images.githubusercontent.com/48896854/131275911-1d2eb6dd-1a9f-437f-95b5-dc362b21ca3d.png)


![image](https://user-images.githubusercontent.com/48896854/131276240-2c509b21-d262-464b-9b0e-25cfef12e726.png)

the 1 can enter custom shard logic,but 2,3 is not enter!so i think cc_weighbridge table stragegy is correct!

**Comment by avalon5666** [comment]
Yes, ss use sharding column to routing, so the sql must cotain sharding column.

**Comment by luoyexiaoran** [comment]
> Yes, ss use sharding column to routing, so the sql must cotain sharding column.

so,,Why is the wrong number of affected rows returned when saving?4.0 doesn't have this problem....But I had to upgrade to 5.0 to solve the subquery problem...
Can you tell me the reason for this,thanks!!!!!

**Comment by avalon5666** [comment]
Contain the sharding colum can resolve this issue?

**Comment by luoyexiaoran** [comment]
> Contain the sharding colum can resolve this issue?
When I save, the shard column has value!!so,,I thought it was strange,I don't think the result set is being merged

**Comment by avalon5666** [comment]
If it is a date time sharding table and has sharding column value, it should be routing to one table, but it routing to 24 sub table, is that the problem?

**Comment by avalon5666** [comment]
The result set value is 24, i will check it too.
But I think we need to find out the routing is correct.

**Comment by luoyexiaoran** [comment]
> If it is a date time sharding table and has sharding column value, it should be routing to one table, but it routing to 24 sub table, is that the problem?

yes,, it routing to 24 sub table!!

**Comment by luoyexiaoran** [comment]
> The result set value is 24, i will check it too.
> But I think we need to find out the routing is correct.
I'm sure it's caused by sharding!!!Because I changed the set of shard tables to 12, the error result is 12!!

**Comment by avalon5666** [comment]
> > If it is a date time sharding table and has sharding column value, it should be routing to one table, but it routing to 24 sub table, is that the problem?
> 
> yes,, it routing to 24 sub table!!

so we need the find out why routing to 24 sub table first?

**Comment by luoyexiaoran** [comment]
> > > If it is a date time sharding table and has sharding column value, it should be routing to one table, but it routing to 24 sub table, is that the problem?
> > 
> > 
> > yes,, it routing to 24 sub table!!
> 
> so we need the find out why routing to 24 sub table first?
yes!I don't know why my shard logic doesn't come in when I save!!

**Comment by avalon5666** [comment]
> > Can you debug the cc_weighbridge table stragegy is set correct?
> 
> Can you correctly access my custom sharding logic?When I carry a shard column query, it normally enters the custom shard logic!But when a query does not carry a shard column condition or save. it cannot enter custom shard logic,I consider this normal when queries do not carry shard criteria.
> 
> ![image](https://user-images.githubusercontent.com/48896854/131275911-1d2eb6dd-1a9f-437f-95b5-dc362b21ca3d.png)
> 
> ![image](https://user-images.githubusercontent.com/48896854/131276240-2c509b21-d262-464b-9b0e-25cfef12e726.png)
> 
> the 1 can enter custom shard logic,but 2,3 is not enter!so i think cc_weighbridge table stragegy is correct!

I suppose your sql has sharding column value and can enter the custom shard logic, pls debug the WeighbridgeShardingAlgorithm#doSharding return result.

**Comment by luoyexiaoran** [comment]
> > > Can you debug the cc_weighbridge table stragegy is set correct?
> > 
> > 
> > Can you correctly access my custom sharding logic?When I carry a shard column query, it normally enters the custom shard logic!But when a query does not carry a shard column condition or save. it cannot enter custom shard logic,I consider this normal when queries do not carry shard criteria.
> > ![image](https://user-images.githubusercontent.com/48896854/131275911-1d2eb6dd-1a9f-437f-95b5-dc362b21ca3d.png)
> > ![image](https://user-images.githubusercontent.com/48896854/131276240-2c509b21-d262-464b-9b0e-25cfef12e726.png)
> > the 1 can enter custom shard logic,but 2,3 is not enter!so i think cc_weighbridge table stragegy is correct!
> 
> I suppose your sql has sharding column value and can enter the custom shard logic, pls debug the WeighbridgeShardingAlgorithm#doSharding return result.
Which? 2 or 3?

**Comment by avalon5666** [comment]
3

**Comment by luoyexiaoran** [comment]
> 3

no, save and update can not enter WeighbridgeShardingAlgorithm!!!
this update ,It has no errors :
![image](https://user-images.githubusercontent.com/48896854/131281139-2bcf11f9-e4aa-4363-9d8c-20dfccf1ba2e.png)

this is save:
![image](https://user-images.githubusercontent.com/48896854/131281363-d484721a-7b35-49c2-bcc6-b5c3dce03f74.png)

**Comment by avalon5666** [comment]
Can you provider the demo.

**Comment by luoyexiaoran** [comment]
![image](https://user-images.githubusercontent.com/48896854/131281995-b5771f75-a95f-4689-9012-dc33126f8010.png)

**Comment by luoyexiaoran** [comment]
> Can you provider the demo.

Can you provider the demo.I don't know What do you mean !!!remote or Record a video?

**Comment by avalon5666** [comment]
the code which i can debug.

**Comment by luoyexiaoran** [comment]
> the code which i can debug.

oh,,the project too large!!Can you remote my computer debug?

**Comment by avalon5666** [comment]
ok

**Comment by luoyexiaoran** [comment]
> ok

sunflower or  teamview?

**Comment by avalon5666** [comment]
tv

**Comment by luoyexiaoran** [comment]
> tv

327 590 892                         1qr3y4c4

**Comment by avalon5666** [comment]
sunflower, tv is limited

**Comment by luoyexiaoran** [comment]
> sunflower, tv is limited

624 160 036       6N57s9

**Comment by luoyexiaoran** [comment]
> sunflower, tv is limited

WX is error ,,so bad
