### ISSUE TITLE
 What should I do if I only do sub database？？？

### ISSUE THREAD

**Issue by jianyun** [apache/shardingsphere#12043]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

What should I do if I only do sub database？？？

**Comment by tristaZero** [comment]
@Comven Aha, bingo, right.
