### ISSUE TITLE
Error in Windows when running 'mvn install' with file path containing more than 256 characters

### ISSUE THREAD

**Issue by Beyondeclipse** [apache/shardingsphere#12054]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
run mvn install successfully

### Actual behavior
Error running 'shardingsphere-standalone-mode-repository-local [clean...]': Cannot run program "C:\Java\jdk8u292-b10\bin\java.exe" (in directory "xxx\sharding-sphere\shardingsphere-mode\shardingsphere-mode-type\shardingsphere-standalone-mode\shardingsphere-standalone-mode-repository\shardingsphere-standalone-mode-repository-provider\shardingsphere-standalone-mode-repository-local"): CreateProcess error=267, 目录名称无效。

### Reason analyze (If you can)
The file paths contain more than 256 characters.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
In Windows，run mvn install under the project 'shardingsphere-standalone-mode-repository-local'.

**Comment by tristaZero** [comment]
Hi @Beyondeclipse So?

**Comment by Beyondeclipse** [comment]
It OK now, thank you!

**Comment by zm52hz** [comment]
@RaigorJiang Hi RaigorJiang、FAQ url about this error is Not Found. 
could you give me a new url? thanks

**Comment by RaigorJiang** [comment]
@zm52hz https://shardingsphere.apache.org/document/current/cn/reference/faq/
