### ISSUE TITLE
Support mode on spring boot starter

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12057]
- [ ] Support mode on spring boot starter
- [ ] Merge shardingsphere-jdbc-governance-spring-boot-starter and shardingsphere-jdbc-core-spring-boot-starter
- [ ] Remove shardingsphere-jdbc-governance-spring-boot-starter module
- [ ] Remove shardingsphere-jdbc-governance-spring module

**Comment by zjcnb** [comment]
I want to do, please assign me!

**Comment by zjcnb** [comment]
boot start config：

spring.shardingsphere.model.type=Cluster
spring.shardingsphere.model.repository.type=ZooKeeper
spring.shardingsphere.model.repository.props.namespace=demo_boot_common
spring.shardingsphere.model.repository.props.serverLists=localhost:2181
spring.shardingsphere.model.overwrite=true

**Comment by zjcnb** [comment]
@terrymanu Hi, these tasks have been completed.
