### ISSUE TITLE
Consider about use single ContextManager to instead of mode based ContextManager

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12058]
- [x] Consider about move @Subscribe from ClusterContextManager to ClusterContextManagerBuilder
- [x] Consider about move disableDataSources() and persistMetaData() from ClusterContextManager to ClusterContextManagerBuilder
- [ ] Merge ClusterContextManager, StandaloneContextManager and MemoryContextManager into ContextManager

**Comment by zjcnb** [comment]
please assign me!
