### ISSUE TITLE
SingleTableRule is created in MetaDataContext when Rules and DataSources are both empty for JDBC with cluster mode

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#12060]
## Question

Test with spring-namespace:

```
<cluster:repository id="clusterRepository" type="TestRegistry" namespace="clusterPersistRepository" server-lists="localhost:3182">
        <props>
            <prop key="max-retries">3</prop>
            <prop key="operation-timeout-milliseconds">1000</prop>
        </props>
    </cluster:repository>
<shardingsphere:data-source id="emptyConfigurationDataSourceGovernance">
        <shardingsphere:mode type="Cluster" repository-ref="clusterRepository" />
    </shardingsphere:data-source>
```

There's nothing in the registry center, when create datasource with  the configuration above，will create a single table rule in MetaDataContext.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/60651792/131116033-e0223a29-0237-4362-801b-ba95fc3946ea.png">

**Comment by strongduanmu** [comment]
@menghaoranss `SingleTableRule` is a built-in Rule used to provide routing capabilities for `SingleTable`. It does not require configuration and will automatically create and load single tables in the data source.

**Comment by menghaoranss** [comment]
> @menghaoranss `SingleTableRule` is a built-in Rule used to provide routing capabilities for `SingleTable`. It does not require configuration and will automatically create and load single tables in the data source.

@strongduanmu Thanks for your reply, i can close this issue now.
