### ISSUE TITLE
Discuss how to refactor SQLUtil.getShowLikePattern()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12087]
There are 2 problems:

1. SQLUtil is for all SQL basic operation, `getShowLikePattern()` is more specific. They are not in the same abstract level, it is better to process for all `like`.
2. There still have question of `SQLUtil.getShowLikePattern()` itself. I don't know why replace `_` to `.{1}`, and replace `%` to `.*`. Is it for regular expression with callee? If yes, the codes of `SQLUtil.getShowLikePattern()` are difficult to understand. This method should describe itself at first.

**Comment by strongduanmu** [comment]
@terrymanu Thank you very much for your suggestions, I submitted a PR to optimize this issue, please review it.
