### ISSUE TITLE
Etcd watch listen not compatible support ADD event

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#12103]
### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

sharding-proxy

### Expected behavior

![image](https://user-images.githubusercontent.com/33742097/131317071-e4b4d872-c2d8-463a-ae2a-eb2dbe01d40b.png)

it can create database successful!

### Actual behavior

Failure

### Reason analyze (If you can)

Etcd watch listen not compatible support ADD event

**Comment by zjcnb** [comment]
assign me please.

**Comment by SteNicholas** [comment]
@zjcnb , I have assigned the issue to you. Please go ahead to fix the uncompatibility for the ADD event support.

**Comment by zjcnb** [comment]
> Please go ahead to fix the uncompatibility for the ADD event support

thx
