### ISSUE TITLE
Questions and suggestions for Metadata builder refactoring

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#12113]
### Fine
- `TableMetaDataLoaderEngine`

### To optimized
- `build`,  `load`  and `decorate`   of  `TableMetaDataBuilder` vs `buildLogicTableMetaDataMap`, `buildActualTableMetaDataMap` of `SchemaBuilder`
- The relationship of `RuleBasedTableMetaDataBuilder` and `TableContainedRule` in `decorate` of `TableMetaDataBuilder`
- `decorateWithCheckTableMetaData` and `decorateLogicTableName`  of `ShardingTableMetaDataBuilder` to get logic tables，rather than actual tables?
- Move `TableMetaDataLoaderEngine` and `TableMetaDataLoaderMaterial` to loader package
- Create `default` package for `loader` package to include all the default loaders

### Minor issue
- Rename `TableMetaDataUtil`?
- Rename `SchemaBuilder` referring to `ShardingSphereRulesBuilder`?

**Comment by tuichenchuxin** [comment]
I want to refactor metadata builder.
