### ISSUE TITLE
Whether cluster need to auto switch could be customized by conf and SPI when scaling task almost finished

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#12121]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Currently, there is hard-coded algorithm to check whether scaling task is almost finished. After some discussion with @tristaZero , in order to support more requirements, we decided to make it be customized by configuration and SPI.

TODO list:
- Define a sub-type of `ShardingSphereAlgorithm` for cluster auto switch
- Implement a default algorithm
- Define configuration structure of scaling in `server.yaml`
- Replace hard-coded algorithm

**Comment by tristaZero** [comment]
Looks fine. ;-)
