### ISSUE TITLE
PostgreSQL doesn't support `abort` (rollback)

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#12166]
## Feature Request

Using `psql` connect to PostgreSQL:
```
wuweijie=# begin;
BEGIN
wuweijie=*# abort;
ROLLBACK
```

Connect to Proxy:
```
bmsql=> begin;
BEGIN
bmsql=*> abort;
ERROR:  You have an error in your SQL syntax
```

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you take a look at this issue?

**Comment by tuichenchuxin** [comment]
> @tuichenchuxin Can you take a look at this issue?

ok, I'll have a look.
