### ISSUE TITLE
Unify the column name format in the DistSQL result set

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#12168]
Hi community,

I found that the column names of some response results from DIstSQL are not uniform, and some adjustments are needed, such as
#### Case:
`show databases`:  the column name `SCHEMA_NAME` is all uppercase. ❌
```sql
mysql> show databases; 
+-------------+
| SCHEMA_NAME |
+-------------+
| sharding_db |
+-------------+
```

`show variable transaction_type`: the column name `TRANSACTION_TYPE`  is all uppercase.  ❌
```sql
mysql> show variable transaction_type;
+------------------+
| TRANSACTION_TYPE |
+------------------+
| XA               |
+------------------+
```

`show sharding hint status`: the column names are all lowercase.  ✅
```sql
mysql> show sharding hint status;
+----------------+--------------------------+-----------------------+------------------+
| table_name     | database_sharding_values | table_sharding_values | sharding_type    |
+----------------+--------------------------+-----------------------+------------------+
| t_order_item_0 |                          |                       | databases_tables |
| t_order_item_1 |                          |                       | databases_tables |
+----------------+--------------------------+-----------------------+------------------+
```

#### Format:
`preview SQL`: the  column name `datasource_name` is not standardized, `data` and  `source` should be two words. ❌
```sql
mysql> preview select * from t_order;
+-----------------+-----------------------+
| datasource_name | sql                   |
+-----------------+-----------------------+
| ds_0            | select * from t_order |
| ds_1            | select * from t_order |
+-----------------+-----------------------+
```

Therefore, it is necessary to check the results of all [RQL](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/rql/) and [RAL](https://shardingsphere.apache.org/document/current/en/features/dist-sql/syntax/ral/ral/) statements, If anyone is interested, please comment in this issue, thank you.

**Comment by yx9o** [comment]
I want to try this issue.
