### ISSUE TITLE
Add unit test for FilterableExecutionContextGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#12171]
This issue is for adding unit tests for FilterableExecutionContextGenerator#generate.
If you are interested, please leave a message.

**Comment by meSunnySrivastava** [comment]
Hello @strongduanmu 
I would like to contribute in this issue.

**Comment by strongduanmu** [comment]
Hi @meSunnySrivastava , welcome to leave a comment. This issue is for PR #12177, after it is merged, you can start working.

**Comment by meSunnySrivastava** [comment]
Hello @strongduanmu 
PR is merged but
PR #12177 did't commit getTableColumns method in SelectStatementContext.
I checked in files changed.

**Comment by strongduanmu** [comment]
@meSunnySrivastava I'm very sorry, the logic has been adjusted after review, I will modify the content of this issue.

**Comment by strongduanmu** [comment]
Hi @meSunnySrivastava, does this issue have any progress?

**Comment by meSunnySrivastava** [comment]
Hello @strongduanmu Sorry I am unable to work due to health reasons. Could you please assign this to anyone else?
I apologize for this late information.

**Comment by strongduanmu** [comment]
@meSunnySrivastava It doesn't matter, take a good rest and stay healthy.

**Comment by clbigdata** [comment]
I would like to contribute in this issue.

**Comment by strongduanmu** [comment]
@clbigdata Welcome, I will assign this issue to you.

**Comment by yy2so** [comment]
Hi @clbigdata would you still like to contribute and resolve this issue?

Please share a status update with the community, thank you.

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by TeslaCN** [comment]
@shreya024 
Sorry for the delay. Assigned.

**Comment by shreya024** [comment]
> @shreya024 Sorry for the delay. Assigned.

Hey @TeslaCN sorry for not informing earlier.The OpenForce program has ended.

**Comment by TeslaCN** [comment]
This issue is outdated.
