### ISSUE TITLE
Add more unit test for ProjectionEngine

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#12170]
Since PR #12199 optimizes the logic of ShorthandProjection in ProjectionEngine, more test cases need to be added.

If you are interested, please leave a message.

**Comment by schrosolver** [comment]
Hello @strongduanmu
I would like to contribute in this issue.

I don't see this method in master branch.
Could you please let me know if I should look into some other branch?

**Comment by strongduanmu** [comment]
Hi @schrosolver, welcome to leave a comment. This issue is for PR #12177, after it is merged, you can start working.

**Comment by strongduanmu** [comment]
@schrosolver I'm very sorry, the logic has been adjusted after review, I will modify the content of this issue.

**Comment by schrosolver** [comment]
> @schrosolver I'm very sorry, the logic has been adjusted after review, I will modify the content of this issue.

Sure no problem at all, Will start working on this and create a PR

**Comment by menghaoranss** [comment]
@schrosolver I will move this issue to the next version, and you can still try to resolve it later.

**Comment by yy2so** [comment]
Hi @schrosolver would you still like to contribute and resolve this issue?

Please share a status update with the community, thank you.

**Comment by schrosolver** [comment]
Thanks for reaching out. Sorry for the delay.
With my current bandwidth and commitments I might not be able to work on this until sometime. Please reassign this task to someone else.

**Comment by yy2so** [comment]
> Thanks for reaching out. Sorry for the delay.
> 
> With my current bandwidth and commitments I might not be able to work on this until sometime. Please reassign this task to someone else, if they are interested.

Hi @schrosolver thanks for the update. Noted, wie'll reassign.

Hope to see you back in the ShardingSphere community soon.

**Comment by TeslaCN** [comment]
There are about 24% lines in `ProjectionEngine` are not covered by `ProjectionEngineTest.` This issue will remain open.

**Comment by DreamTexX** [comment]
Hello, would like to work on this. Is this still relevant? I see there are only a few untested lines. Just seems like a good small starting point to start contributing 😄.

**Comment by TeslaCN** [comment]
Hi @DreamTexX 
Would you like to finish this issue?

**Comment by DreamTexX** [comment]
Yes

**Comment by DreamTexX** [comment]
Sorry for answering so late, didn't got a notification

**Comment by TeslaCN** [comment]
Test cases are not in release scope. I'm removing the milestone for now.

**Comment by DreamTexX** [comment]
Hey, i added a test case and coverage for projection engine is now at 98% (one line untested). Can i nevertheless already submit a pr?
