### ISSUE TITLE
Hint Usage in Documents

### ISSUE THREAD

**Issue by CreatureOX** [apache/shardingsphere#12182]
## Question
I've found issues like #4281 #6458 mentioned `hintManager.setDatabaseShardingValue` will be used in route step instead of skipping parse and rewrite phase since 4.x. Is this part of documents out-of-date? 

I am glad to update this part in documents in 4.x and later version.

**Comment by tristaZero** [comment]
@CreatureOX More than welcome. ;-)
Hi @RaigorJiang could you give a check here?

**Comment by RaigorJiang** [comment]
Hi @tristaZero 
I checked the [document](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/usage/sharding/hint/) of current version, and the description does still exist:
> After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced.

Hi @CreatureOX 
Welcome to submit a PR to remove the description of the feature. Thank you!

**Comment by CreatureOX** [comment]
Assign me please.
