### ISSUE TITLE
Discuss, Do we need to refactor the ShardingSphereDataSource

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#12189]
Hi community,

   I found some code can be optimized, It 's about ```ShardingSphereDataSource```. For example:

```
ShardingSphereDataSource.createContextManager(final String schemaName, final ModeConfiguration modeConfig)

ShardingSphereDataSource.createContextManager(final String schemaName, final ModeConfiguration modeConfig, final Map<String, DataSource> dataSourceMap, final Collection<RuleConfiguration> ruleConfigs, final Properties props)
```

I think these two methods can be merge one method, We only need to make adjustments in the upper layer to be compatible.

Even, I think the two of them can be merged if we do not consider users to directly create ShardingSphereDataSource

```
ShardingSphereDataSource(final String schemaName, final ModeConfiguration modeConfig)

ShardingSphereDataSource(final String schemaName, final ModeConfiguration modeConfig, final Map<String, DataSource> dataSourceMap, final Collection<RuleConfiguration> ruleConfigs, final Properties props)
```

**Comment by menghaoranss** [comment]
I suggest keeping the 2 construction methods of `ShardingSphereDataSource`, and you can try to merge  `createContextManager`.

**Comment by zjcnb** [comment]
> I suggest keeping the 2 construction methods of `ShardingSphereDataSource`, and you can try to merge `createContextManager`.

Yeah, I will merge createContextManager
