### ISSUE TITLE
When there is only one `sharding table rule` on ZK,  `drop sharding table` rule will fail

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#12195]
Hi community,
There may be a problem about `ShardingRuleConfigurationChecker`

![image](https://user-images.githubusercontent.com/52209337/131971827-e5a19ad3-6a49-4f60-b70a-17d5e307954e.png)

![image](https://user-images.githubusercontent.com/52209337/131971894-2b6636ee-7ab6-425e-81be-68d7ff5a8631.png)

This method will be used when persistent configuration to zk.
So when only `rules.shardingAlgorithms` is configured in my configuration file, proxy startup will fail.
In addition, when the `schema` has only one `sharding table rule`, using DistSQL to delete the `sharding table rule` will also fail

![image](https://user-images.githubusercontent.com/52209337/131976086-18d7c569-1cc3-4a6e-bcbb-5e9e9caee7b8.png)

**Comment by zjcnb** [comment]
governance are remove from ShardingSphere， i think the error message should be change to
```
No available encrypt rule configuration in `%s` for register center.
```
