### ISSUE TITLE
When will version 5.0.0-RC1 be released

### ISSUE THREAD

**Issue by xueshiji** [apache/shardingsphere#12208]
## Question
I want to know when the 5.0.0-RC1 version will be released，Could you give an approximate time?

**Comment by tristaZero** [comment]
Hi @xueshiji Thanks for your question which is also many other folks' concern.
I presume it is supposed to launch next month.

**Comment by sandynz** [comment]
Hi @xueshiji , welcome to follow WeChat Official Account (公众号) `Sharding-Sphere` to get ShardingSphere Chinese news.
