### ISSUE TITLE
Add test case for GlobalRulesBuilder

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12206]

**Comment by Muhammadwasi** [comment]
Hi @terrymanu,

I would like to take up this issue. Please assign it to me.

Thanks.

**Comment by strongduanmu** [comment]
Welcome @Muhammadwasi, you can refer this [doc](https://shardingsphere.apache.org/community/en/contribute/contributor/) for your first contribute.

**Comment by menghaoranss** [comment]
@Muhammadwasi I will move this issue to the next version, and you can still try to resolve it later.

**Comment by menghaoranss** [comment]
@Muhammadwasi hi, any progress here?

**Comment by Muhammadwasi** [comment]
Hi @menghaoranss,

I will resolve this issue asap.

**Comment by yy2so** [comment]
Hi @Muhammadwasi would you still like to contribute and resolve this issue?

**Comment by acmenlt** [comment]
@strongduanmu Can I work on this issue

**Comment by strongduanmu** [comment]
> @strongduanmu Can I work on this issue

@acmenlt Of course, I will assign this issue to you.

**Comment by terrymanu** [comment]
The test cases are not enough, please add more test cases with global rule

**Comment by acmenlt** [comment]
> The test cases are not enough, please add more test cases with global rule

@terrymanu Received. More detailed test cases will be added in the next submission

**Comment by TeslaCN** [comment]
Hi @acmenlt 
Any update here? We are going to release 5.1.1.

**Comment by acmenlt** [comment]
> Hi @acmenlt Any update here? We are going to release 5.1.1.

@TeslaCN There is no update yet. Can we postpone it to the next version.

**Comment by TeslaCN** [comment]
Test cases are not in release scope. I'm removing the milestone for now.

**Comment by terrymanu** [comment]
@mabaiwan  Hi, any update?

**Comment by mabaiwan** [comment]
@terrymanu Sorry, I forgot, update later.
