### ISSUE TITLE
Date formatting issues

### ISSUE THREAD

**Issue by programmerhes** [apache/shardingsphere#12236]
When I try to use a string to receive the date，preciseShardingValue.getValue() return -1
sql:select * from order_main where createtime = '2021-04-01 00:00:00'
```
public class USerTablePreciseShardingAlgorithm implements PreciseShardingAlgorithm<String> {
    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<String> preciseShardingValue) {
        System.out.println(preciseShardingValue.getValue()); //Expected value is "2021-04-01 00:00:00" but -1
        System.out.println(preciseShardingValue.getLogicTableName());
        return "order_main_202104";
 }
```
version:3.1.0
Thanks for answering

**Comment by RaigorJiang** [comment]
Hi @programmerhes 
Version 3.1.0 is outdated，many issues related to the `date` format have been fixed after version 4.0.0. 
For example: https://github.com/apache/shardingsphere/issues/10207
So please try the updated version.

**Comment by RaigorJiang** [comment]
Hi @programmerhes
Is your problem solved?

**Comment by programmerhes** [comment]
yes.thank you
