### ISSUE TITLE
Eating InsertStatement Exceptions?

### ISSUE THREAD

**Issue by coolbeevip** [apache/shardingsphere#12246]
### Which version of ShardingSphere did you use?

5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

An exception should be thrown when the insert statement exception

### Actual behavior

ShardingSphere Eating InsertStatement Exceptions

### Example codes for reproduce this issue (such as a github link).

This issue is easy to reproduce

**Comment by coolbeevip** [comment]
It's already fixed in https://github.com/apache/shardingsphere/pull/10845 

I can't found snapshot version of the master in https://repository.apache.org/content/repositories/snapshots/

**Comment by RaigorJiang** [comment]
> It's already fixed in #10845
> 
> I can't download snapshot version of the master in https://repository.apache.org/content/repositories/snapshots/

Yes it was fixed. You can build from master branch, please refer to [README](https://github.com/apache/shardingsphere/blob/master/README.md).

**Comment by coolbeevip** [comment]
> README

Thank you
