### ISSUE TITLE
support proxy's "set names"

### ISSUE THREAD

**Issue by ccMoriarty** [apache/shardingsphere#12245]
### Describe the feature you would like.
now, "set names"  is actually a transparent transmission, to execute "set names" on the specific DB. it changes the character set of DB，not the ShardingSphere-proxy.

When a SQL is executed, it reaches the proxy first, and the proxy will convert it from byte stream to String. Now there is no specified character set.This may cause chinese garbled problems.

if i have a gbk table and a utf8 table in same proxy, it must cause chinese garbled.

so i think proxy's "set names" can be supported. in mysql, set names  changes the session-level character set. I hope the proxy has its own session-level character set. (When new String, the specified Session-level character set that can be displayed)

if it is completed, we can use multiple encoding formats in one proxy

**Comment by RaigorJiang** [comment]
Good idea.

**Comment by tristaZero** [comment]
So do we have any guides to help contributors raise a PR on this issue? @RaigorJiang 
@ccMoriarty Would you have to try to fix this issue with a hand from our committer?

**Comment by RaigorJiang** [comment]
Currently, we do not maintain the character set in the metadata. In particular, it is a greater challenge for the Proxy to want a session-level character set. 
Therefore, this work may have a relatively large impact and requires thinking and design first.
If @ccMoriarty is interested, please put forward some ideas.

**Comment by TeslaCN** [comment]
Hi @ccMoriarty 
The Proxy has supported session-level charset since #13332. Would you like to finish this issue?

**Comment by ccMoriarty** [comment]
@TeslaCN 
I’m glad to to solve this problem. But it’s almost the end of the year, I’m busy here. it may have to wait until January to develop

**Comment by TeslaCN** [comment]
Hi @ccMoriarty 
Any update here?

**Comment by TeslaCN** [comment]
This issue has been fixed in #15603, #15619, #15753, #15795.
