### ISSUE TITLE
Master branch, Insert on duplicate key update error!

### ISSUE THREAD

**Issue by CodingBingo** [apache/shardingsphere#12272]
### Which version of ShardingSphere did you use?
Current master branch.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
when i user shardingSephere-jdbc, this sql will occur error.
```
insert into social_count (image, video, feeds, organization,createTime,updateTime) values (  ?, ?, ?, ?, now(), now()) on duplicate key update image = image + ?,video = video + ?,feeds = feeds + ?,updateTime = now()
```
social_count is single table in single database.

error:
```
bad SQL grammar []; nested exception is java.sql.SQLException: No value specified for parameter 6
```

### Reason analyze (If you can)
In code of **org.apache.shardingsphere.infra.binder.segment.insert.values.OnDuplicateUpdateContext**, we have a function
```
     private int calculateParameterCount(final Collection<ExpressionSegment> assignments) {
        int result = 0;
        for (ExpressionSegment each : assignments) {
            if (each instanceof ParameterMarkerExpressionSegment) {
                result++;
            } 
        }
        return result;
    }
```
when i step into this function, each of element in assignments is an instanceof **BinaryOperationExpression**, not **ParameterMarkerExpressionSegment**, so it will course `parameterCount` always be 0.

### Example codes for reproduce this issue (such as a github link).
To fix this bug, i modified the code as below.
```
private int calculateParameterCount(final Collection<ExpressionSegment> assignments) {
        int result = 0;
        for (ExpressionSegment each : assignments) {
            if (each instanceof ParameterMarkerExpressionSegment) {
                result++;
            } else if (each instanceof BinaryOperationExpression) {
                if (((BinaryOperationExpression) each).getRight() instanceof ParameterMarkerExpressionSegment) {
                    result++;
                }
            }
        }
        return result;
    }
```

**Comment by RaigorJiang** [comment]
Hi @CodingBingo 
Thanks for your report, let's wait for @strongduanmu to have a look.

**Comment by tristaZero** [comment]
So @strongduanmu It's an existing bug, right？
Hi @CodingBingo thanks. If so, would you like to try to fix this one?

**Comment by strongduanmu** [comment]
@tristaZero Yes, it's an bug, and this issue is similar  to #7998.

**Comment by CodingBingo** [comment]
> So @strongduanmu It's an existing bug, right？
> Hi @CodingBingo thanks. If so, would you like to try to fix this one?

I will try to fix bug and make a pull request, thanks for your guys reply.

**Comment by strongduanmu** [comment]
@CodingBingo You are welcome to submit a PR.
