### ISSUE TITLE
How to use SNOWFLAKE key generator when use Docker

### ISSUE THREAD

**Issue by jiangqs3** [apache/shardingsphere#12287]
## Question

shardingSphere version:4.1.1
Using the Snowflake algorithm in docker environment may generate duplicate primary keys. What configuration is required to avoid this problem when use sharding-jdbc.

**Comment by RaigorJiang** [comment]
Hello @jiangqs3 
Why shardingsphere-jdbc may generate duplicate primary keys in docker environment?  
Did you configure the same props `worker-id`?  
Notice: Each container can be mounted with a different VOLUME, which can solve the problem.

**Comment by jiangqs3** [comment]
Thank you.

**Comment by tristaZero** [comment]
Solved, closed.
