### ISSUE TITLE
Check whether the rules are complete for ShardingSphere-JDBC

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#12289]
## Question

**For English only**, other languages will not accept.

refer to #12195 

In the class `SchemaRulePersistService`, the following method will check whether the rule configurations are complete before persisted.

For ShardingSphere-Proxy, it could run successfully without any rules,  so this is unnecessary logic for proxy. 

For ShardingSphere-JDBC, it should be checked before creating `ShardingSphereDataSource`

```
private Collection<YamlRuleConfiguration> createYamlRuleConfigurations(final String schemaName, final Collection<RuleConfiguration> ruleConfigs) {
        Collection<RuleConfiguration> configs = new LinkedList<>();
        for (RuleConfiguration each : ruleConfigs) {
            RuleConfigurationCheckerFactory.newInstance(each).ifPresent(checker -> checker.check(schemaName, each));
            configs.add(each);
        }
        return new YamlRuleConfigurationSwapperEngine().swapToYamlRuleConfigurations(configs);
    }
```

Task list:

- [x] Remove checker in `SchemaRulePersistService` to fix #12195 
- [ ] Add check in ShardingSphere-JDBC

**Comment by zjcnb** [comment]
Hi， i want try to Add check in ShardingSphere-JDBC task
