### ISSUE TITLE
Add unit tests for DefaultDataSourceCreator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#12305]
This issue is for adding unit tests for DefaultDataSourceCreator.
If you are interested, please leave a message.

**Comment by CodingBingo** [comment]
I am interested to provide unit tests for DefaultDataSourceCreator;
I will try to finish this task soon

**Comment by strongduanmu** [comment]
@CodingBingo Welcome.

**Comment by CodingBingo** [comment]
> @CodingBingo Welcome.

Hi, this issue can be closed now.

**Comment by strongduanmu** [comment]
> > @CodingBingo Welcome.
> 
> Hi, this issue can be closed now.

Hi @CodingBingo, next time you can use `Fixes #11589` format, after the PR is merged, the issue will be closed automatically.

**Comment by strongduanmu** [comment]
Fixed by #12367.
