### ISSUE TITLE
sometimes, while executing PreparedStatement,shardingshpere throw a null pointer exception

### ISSUE THREAD

**Issue by YollinChan** [apache/shardingsphere#12309]
sql like "SELECT id,order_no FROM table_a WHERE (order_no = ? AND is_del = ?)"

sometimes,shardingshpere will throw a null pointer exception in MySQLComStmtExecutePacket.java. error meessage is:

`message :   Exception occur: 
java.lang.NullPointerException: null
	at org.apache.shardingsphere.db.protocol.mysql.packet.command.query.binary.execute.MySQLComStmtExecutePacket.getParameters(MySQLComStmtExecutePacket.java:106)
	at org.apache.shardingsphere.db.protocol.mysql.packet.command.query.binary.execute.MySQLComStmtExecutePacket.(MySQLComStmtExecutePacket.java:84)
	at org.apache.shardingsphere.db.protocol.mysql.packet.command.MySQLCommandPacketFactory.newInstance(MySQLCommandPacketFactory.java:63)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandPacket(MySQLCommandExecuteEngine.java:46)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:79)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

source code is in line 106
![image](https://user-images.githubusercontent.com/37432978/132652673-1341c7e0-c7e8-4f04-9527-cbf773d1f885.png)

**Comment by YollinChan** [comment]
we add log and final see that
 [paramIndex] == 0;
binaryStatement.getParameterTypes().get(parameterIndex).getColumnType() == 6;
nullBitmap.isNullParameter(parameterIndex) == false;
MySQLBinaryProtocolValueFactory.getBinaryProtocolValue(binaryStatement.getParameterTypes().get(parameterIndex).getColumnType()) == null

**Comment by YollinChan** [comment]
【MySQLBinaryProtocolValueFactory.getBinaryProtocolValue(binaryStatement.getParameterTypes().get(parameterIndex).getColumnType()) == null 】cause null pointer exception in line 106.

**Comment by tristaZero** [comment]
Hi which version? @YollinChan 
@TeslaCN

**Comment by TeslaCN** [comment]
I found a way to reproduce this issue:

```java
package icu.wwj.hello.jdbc;

import lombok.SneakyThrows;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Types;
import java.util.concurrent.SynchronousQueue;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class MySQLRepeatedlyPrepareExecuteClose {
    
    public static void main(String[] args) {
        final int threads = 2;
        Runnable runnable = () -> {
            try (Connection connection = getConnection()) {
                for (; ; ) {
                    try (PreparedStatement preparedStatement = connection.prepareStatement("select * from sbtest1 where id = ?")) {
                        int result = ThreadLocalRandom.current().nextInt(200000);
                        if (result > 100000) {
                            preparedStatement.setNull(1, Types.INTEGER);
                        } else {
                            preparedStatement.setInt(1, result);
                        }
                        preparedStatement.executeQuery().close();
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        };
        ThreadPoolExecutor executor = new ThreadPoolExecutor(threads, threads, 0L, TimeUnit.SECONDS, new SynchronousQueue<>());
        for (int i = 0; i < threads; i++) {
            executor.execute(runnable);
        }
        executor.shutdown();
    }
    
    @SneakyThrows
    private static Connection getConnection() {
        return DriverManager.getConnection("jdbc:mysql://127.0.0.1:13306/sbtest_direct?useSSL=false&useServerPrepStmts=true&cachePrepStmts=false&prepStmtCacheSize=1", "root", "root");
    }
}
```

**Comment by TeslaCN** [comment]
Prepared statement is stateful and it is not shared between sessions.
Refer to https://dev.mysql.com/doc/refman/8.0/en/prepare.html 

The prepared statements are shared between connections in ShardingSphere MySQL Proxy.

https://github.com/apache/shardingsphere/blob/b8db81f51e533773a8992c4909cc4f623279a356/shardingsphere-db-protocol/shardingsphere-db-protocol-mysql/src/main/java/org/apache/shardingsphere/db/protocol/mysql/packet/command/query/binary/execute/MySQLComStmtExecutePacket.java#L81-L83

![image](https://user-images.githubusercontent.com/20503072/141978219-a9d44186-773a-4c20-bb38-4f7ac78b6d8a.png)

![image](https://user-images.githubusercontent.com/20503072/141978285-dc0ff989-c3e5-427d-9cb6-3f7bbd9af770.png)
