### ISSUE TITLE
A question about sharding-proxy cluster mode

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12326]
Does sharding-proxy support high-availability clusters? How many modes are there?

**Comment by RaigorJiang** [comment]
Hi @marker-wu 
`mode` supports `Memory`, `Cluster`, `Standalone`, etc. The documentation of mode is being updated. 
Please pay attention to the documentation update, thank you！

**Comment by RaigorJiang** [comment]
Hi @marker-wu 
Please refer to the document:  https://shardingsphere.apache.org/document/current/cn/features/mode/

**Comment by marker-wu** [comment]
How many types of sharing-proxy cluster mode are there? Does it support distributed clusters? Distributed cluster similar to redis

**Comment by tristaZero** [comment]
@marker-wu Sure, we are working on this feature, which includes the distributed mode.

**Comment by RaigorJiang** [comment]
I found that this issue has been discussed in #12593, can this issue be closed?
