### ISSUE TITLE
duplicate key update syntax not support in openGauss

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#12328]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes,  in scaling project, I have removed conflict operation in openGauss.
### Describe the feature you would like.
pg syntax is :  insert into t1 valeus (0,0) on conflict (xxx) do nothing
opengauss syntax is: insert into t1 valeus (0,0) on duplicate key update nothing

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin, can you check this sql?

**Comment by tuichenchuxin** [comment]
@strongduanmu in pg, it's supported.

**Comment by tuichenchuxin** [comment]
This issue can be closed. It's supported #13326

**Comment by strongduanmu** [comment]
Already fixed by #13326.
