### ISSUE TITLE
A minor issue :  Does not support  LocalDateTime & LocalDate 

### ISSUE THREAD

**Issue by zBo1997** [apache/shardingsphere#12335]
ERROR ===> 
Cause: java.sql.SQLFeatureNotSupportedException: getObject with type; getObject with type; nested exception is java.sql.SQLFeatureNotSupportedException: getObject with type.

"AbstractUnsupportedOperationResultSet" dont have implements  . how to use "LocalDateTime" or “LocalDate” in shardingJDBC Support? 
![image](https://user-images.githubusercontent.com/53822786/132808191-80b9a00b-11e4-44d5-bfcf-0c84c960f8ea.png)

**Comment by RaigorJiang** [comment]
@strongduanmu Please take a look, thank you！

**Comment by tristaZero** [comment]
Hi, @zBo1997 which version do you use? I presume the relevant issue was fixed already. Could you search these keywords in closed PRs? I guess you will get some hints.

**Comment by zBo1997** [comment]
Appreciate your immediate reply. i got some hints
