### ISSUE TITLE
Read write separation, MySQL master-slave delay

### ISSUE THREAD

**Issue by zhanghongzheng6** [apache/shardingsphere#12340]
When using shardingsphere read / write separation, if the master-slave synchronization is delayed, can the program automatically change the read operation to read the master library

**Comment by RaigorJiang** [comment]
Hello, for English only, please translate the title and content, thank you!

**Comment by RaigorJiang** [comment]
Yes, ShardingSphere-JDBC has this ability.
Please refer to the dockement: https://shardingsphere.apache.org/document/current/cn/features/readwrite-splitting/use-norms/
Set `queryConsistent ` to true to enable this feature.

example:
https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-readwrite-splitting.yaml

**Comment by zhanghongzheng6** [comment]
Thank you for your reply. The problem I encountered can not be completely solved.
My problem is: the database jitters. The master and slave are delayed for 10 seconds. A complete query request does not read the latest data. This leads to a serious problem.

Is there a function similar to heartbeat check that can automatically switch between master and slave when there is a certain delay?

**Comment by RaigorJiang** [comment]
No.
The master-slave synchronization is done independently by the databases, and ShardingSphere cannot perceive it.

**Comment by zhanghongzheng6** [comment]
Well, I see

**Comment by zhanghongzheng6** [comment]
Well, I see
