### ISSUE TITLE
Add unit test for shardingsphere-shadow-core

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#12344]
Hi community,

This issue is for #11661

## Aim
Add unit test for shardingsphere-shadow-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [x] NoteShadowAlgorithmDeterminer
- [ ] ShadowDetermineCondition

## Examples FYI

- ColumnShadowAlgorithmDeterminerTest

**Comment by LeeGuoPing** [comment]
i want to try it.

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.
