### ISSUE TITLE
Example improvement plan

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12366]
The current example is not good enough. It is difficult to understand, which users can not find their desired example codes quickly, the disadvantages are:

1. The categories of examples are not in same abstract level, they are not show the overview of ShardingSphere features and structure clearly;
2. The `example-core` module is too complicated which contains too many common and abstract codes, user do not need to understander them. It is better to use "flat" codes and make them independent each other;
3. Proxy and JDBC need to provide configurations for multiple dimensions, such as different modes, different kernel providers and different feature configs;
4. JDBC example can be split to different adaptors, such as `jdbc`, `spring boot starter & jdbc`, `spring boot starter & jpa`, `spring boot starter & mybatis`, `spring namespace & jdbc`, `spring namespace & jpa` and , `spring namespace & mybatis`;
5. Proxy do not need java connect example, config only is enough.

It is more clear if adjust example structure as:

```
shardingsphere-example
  ├- shardingsphere-jdbc-example
     ├- shardingsphere-jdbc-${mode}-example
        ├- shardingsphere-jdbc-${mode}-${transaction}-${feature}-example
           ├- shardingsphere-jdbc-${mode}-${transaction}-${feature}-${framework}-example
  ├- shardingsphere-proxy-example
     ├- shardingsphere-proxy-${mode}-example
        ├- shardingsphere-proxy-${mode}-${transaction}-${feature}-example
  ├- shardingsphere-parser-example
```

`${xxx}` are variables which can be replaced by:

- `${mode}`: memory, standalone-file, cluster-zookeeper, cluster-etcd
- `${transaction}`: local, xa-atomikos, xa-bitronix, xa-narayana, base-seata
- `${feature}`: sharding, readwrite-splitting, db-discovery, encrypt, shadow and all permutation of them
- `${framework}`: jdbc, springboot-starter-jdbc, springboot-starter-jpa, springboot-starter-mybatis, springnamespace-jdbc, springnamespace-jpa, spring-namespace-mybatis

The duplicated codes may consider about using code-generation engine.

![example-code-gen-engine drawio](https://user-images.githubusercontent.com/5516298/132954397-406a0dbe-f28f-4e5b-89b2-1d79595422b4.png)

**Comment by totalo** [comment]
hi, I want to finish this job. plz assgin to me. thanks.

**Comment by terrymanu** [comment]
Welcome, we can discuss more about it.

**Comment by totalo** [comment]
After discussion with @terrymanu , there are mainly the following two parts
1. The proxy uses the original yaml configuration, regardless of the way the template is generated.
2. The jdbc repeated code uses a template method, and the metadata of the data model comes from the yaml configuration file. Users only need to modify yaml to generate sample code with one click.

More suggestions?

**Comment by terrymanu** [comment]
LGTM

**Comment by menghaoranss** [comment]
@totalo I noticed that some of the new examples could not work well, I want to confirm whether you have tested them, or that the development is not completed now.

**Comment by totalo** [comment]
> @totalo I noticed that some of the new examples could not work well, I want to confirm whether you have tested them, or that the development is not completed now.

Hi, @menghaoranss, this work is still in progress, and there may be some problems with each example. When it is officially launched and used, I will confirm again. In this process, if I have problems with understanding a certain function, please also point it out, thanks~

**Comment by terrymanu** [comment]
@totalo Thank you for the great job!
The example enhancement is completed nearly.

There are still some tasks need to be done:

1. `product`, `mode` and `transaction` in config.yaml could be use multiple values, it is better to name them as `products`, `modes` and `transactions`.
2. I noticed that example of Proxy can not use mix rule configuration, maybe we can improve it to keep same as JDBC.
3. The data model is for config loading and template together, we can consider about split them, just add a config object to load config.yaml only. The config.yaml can generate lots of examples, so the config object can derive lots of data model objects. 
4. It is better to add verification for `config.yaml`, to reminder the config error to end users.

**Comment by totalo** [comment]
> @totalo Thank you for the great job! The example enhancement is completed nearly.
> 
> There are still some tasks need to be done:
> 
> 1. `product`, `mode` and `transaction` in config.yaml could be use multiple values, it is better to name them as `products`, `modes` and `transactions`.
> 2. I noticed that example of Proxy can not use mix rule configuration, maybe we can improve it to keep same as JDBC.
> 3. The data model is for config loading and template together, we can consider about split them, just add a config object to load config.yaml only. The config.yaml can generate lots of examples, so the config object can derive lots of data model objects.
> 4. It is better to add verification for `config.yaml`, to reminder the config error to end users.
> 5. We can remove or deprecated the original examples if our new examples are ready.

It's my pleasure, I will continue to push forward and continue to improve related functions.

**Comment by terrymanu** [comment]
And one more suggestion we can do:
It is better to split `ExampleMain.ftl` as each framework keep one.

**Comment by totalo** [comment]
> And one more suggestion we can do: It is better to split `ExampleMain.ftl` as each framework keep one.

ok, i will do it.

**Comment by terrymanu** [comment]
One more thing: we can consider about use template to generate test cases which can assert the data sources are connected and work fine.

**Comment by TeslaCN** [comment]
Hi @totalo 
Have we finished this issue?

**Comment by totalo** [comment]
> Hi @totalo Have we finished this issue?

Soon. I'm putting some finishing touches on it.
