### ISSUE TITLE
Is last_value a reserved words

### ISSUE THREAD

**Issue by 448700174** [apache/shardingsphere#12370]
SELECT COUNT(distinct elder_id)
    FROM elder_change 
    WHERE category IN ( 0, 1 ) and tenant_id = ?
	    	AND last_value not in   (  ? , ? , ? , ? , ? , ? , ? , ? ) 
             AND current_value in  (  ? , ? , ? , ? , ? , ? , ? , ? )

This simple SQL can not parse.The error message is:You have an error in your SQL syntax

**Comment by 448700174** [comment]
When I change the last_value to my_last_value it parse success.

**Comment by RaigorJiang** [comment]
MySQL has a function called `last_value`, which may conflict in parsing.

**Comment by tristaZero** [comment]
Hi @448700174 Thanks for your feedback. I am curious which release you tested? I suppose 5.0.0-beta supports it.

**Comment by 448700174** [comment]
It's  5.0.0-beta

**Comment by RaigorJiang** [comment]
> Hi @448700174 Thanks for your feedback. I am curious which release you tested? I suppose 5.0.0-beta supports it.


I tested with the parser of the mstaer branch, but it still doesn’t support.

> SELECT COUNT(distinct elder_id)
> FROM elder_change
> WHERE category IN ( 0, 1 ) and tenant_id = ?
> AND last_value not in ( ? , ? , ? , ? , ? , ? , ? , ? )
> AND current_value in ( ? , ? , ? , ? , ? , ? , ? , ? )
> 
> This simple SQL can not parse.The error message is:You have an error in your SQL syntax

**Comment by ThanoshanMV** [comment]
Hi @RaigorJiang, I'll try to fix it.

**Comment by strongduanmu** [comment]
Welcome @ThanoshanMV, i will assign this issue to you.

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang, I'll try to fix it.

Thank you @ThanoshanMV .

**Comment by tristaZero** [comment]
@ThanoshanMV Hey, Glad to see you after GSoC. ;-)
