### ISSUE TITLE
Document improvement plan

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12374]
The current document is not good enough, it is not show the feature and architecture with ShardingSphere 5.x.
It is better to redesign the index of new document:

```
Overview
Concepts
  ├-Adaptor
  ├-Mode
  ├-DistSQL
  ├-Pluggable
Features
  ├-Sharding
  ├-Readwrite Splitting
  ├-Database Discovery
  ├-Scaling
  ├-Encrypt
  ├-Shadow
  ├-Observability
    ├-Agent
    ├-Tracing
    ├-Metrics
User Manual
  ├-ShardingSphere-JDBC
    ├-Java Configuration
    ├-YAML Configuration
    ├-Spring-Boot-Starter
    ├-Spring Namespace
  ├-ShardingSphere-Proxy
    ├-YAML Configuration
    ├-DistSQL
Developer Manual
    ├-TODO
Downloads
Reference
  ├-Kernel
    ├-Metadata
    ├-Transaction
    ├-Query Optimizer
    ├-Authority
    ├-Single Table
    ├-Scheduler
  ├-Test Engine
  ├-Solution
    ├-Distributed Database
    ├-Data Security
    ├-Database Gateway
    ├-Online Stress Test
  ├-FAQ
```

**Comment by Swastyy** [comment]
I can try this one @RaigorJiang will there be subtasks for this or in one PR it should be completed? I want to work on this. Thanks.

**Comment by RaigorJiang** [comment]
> I can try this one @RaigorJiang will there be subtasks for this or in one PR it should be completed? I want to work on this. Thanks.

This is a big adjustment, and there will be many new additions. 
I think there should be some subtasks, but more detailed planning is needed.
