### ISSUE TITLE
Dependent version

### ISSUE THREAD

**Issue by xr2117** [apache/shardingsphere#12371]
What is 5.0.0-alpha springboot-starter  dependency

**Comment by terrymanu** [comment]
Maven can download dependencies automatically, what problem do you meet?

**Comment by RaigorJiang** [comment]
@xr2117 
Do you mean this one? 
> https://shardingsphere.apache.org/document/5.0.0-alpha/en/user-manual/shardingsphere-jdbc/usage/sharding/spring-boot-starter/

**Comment by linghengqian** [comment]
Maybe you mean the unupdated Chinese document? Please refer to the English document.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
