### ISSUE TITLE
The refactor of ShardingSphere-sharding-route  module is not appropriate

### ISSUE THREAD

**Issue by guimingyue** [apache/shardingsphere#12383]
## Feature Request
I found that the `ShardingSphere-infra-route` module was refactored, and classes related to `ShardingCondition` have 
 been moved to `ShardingSphere-sharding-core` module. This will lead to circular dependency of modules like `shardingsphere-infra-executor` and `shardingsphere-sharding-core`，if I want to compute the routing context in the `shardingsphere-infra-executor`.

In my forked [shardingsphere repository](https://github.com/guimingyue/shardingsphere/tree/optimizer), the federated join feature is now WIP, which should compute the routing context in the `shardingsphere-infra-executor` module. The route information is needed for the execution of the `TableScan` operator, in which the sharding table sql should be executed.

For more detail, please refer to [https://github.com/guimingyue/shardingsphere/blob/optimizer/shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/federate/schema/row/FederateRowExecutor.java#L91](https://github.com/guimingyue/shardingsphere/blob/optimizer/shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/federate/schema/row/FederateRowExecutor.java#L91)

**Comment by menghaoranss** [comment]
which version of source code did you use, there's no `shardingsphere-sharding-executor` in the master, and infra should not rely directly on `sharding`

**Comment by guimingyue** [comment]
> which version of source code did you use, there's no `shardingsphere-sharding-executor` in the master, and infra should not rely directly on `sharding`

Sorry, I typed the wrong module name.
I mean the route-related classes should not be moved to `sharding` package.

**Comment by menghaoranss** [comment]
> > which version of source code did you use, there's no `shardingsphere-sharding-executor` in the master, and infra should not rely directly on `sharding`
> 
> Sorry, I typed the wrong module name.
> I mean the route-related classes should not be moved to `sharding` package.

Route is the kernel feature of ShardingSphere, different features such as `Sharding`, `Readwrite Splitting` and `Encrypt` , etc. have their own routers. They all need to be loaded into infra through SPI without direct reference just like this.

```
public PartialSQLRouteExecutor(final Collection<ShardingSphereRule> rules, final ConfigurationProperties props) {
        this.props = props;
        routers = OrderedSPIRegistry.getRegisteredServices(SQLRouter.class, rules);
    }
```

**Comment by terrymanu** [comment]
The code has been refactored, I just close the issue for now, any question please create new issue, thank you.
