### ISSUE TITLE
compile 5.0.0-beta source error

### ISSUE THREAD

**Issue by tianmingxing** [apache/shardingsphere#12388]
![image](https://user-images.githubusercontent.com/5615719/133030429-fd1cf942-4c84-44e9-8af4-f3666deefda0.png)

**Comment by menghaoranss** [comment]
please try to execute `mvn install` first for `shardingsphere-sql-parser` module

**Comment by tianmingxing** [comment]
> please try to execute `mvn install` first for `shardingsphere-sql-parser` module

tks!!!
