### ISSUE TITLE
A little confusion about code design of `HintManager.getInstance()`

### ISSUE THREAD

**Issue by codeboyzhou** [apache/shardingsphere#12399]
## Question

Hi guys, does anybody can explain this confusion of mine?

When I was using shardingsphere, I met a exception as follows, and it's from the class `HintManager`, method is `getInstance()`.
`java.lang.NullPointerException: Hint has previous value, please clear first.`

I read the source code, more or less, feeling a little confused about the code design here.

According to my understanding, the reason why `HintManager.getInstance()` throw a `NullPointerException` is that wants to guarantee, or we can say it wants to tell its caller that ONLY ONE instance can be used here, during the whole period. But why not consider that design the code as a singleton pattern? I mean that there is no need to throw the NPE exception here, instead that the sharding framework should guarantee this (just only one instance of `HintManager`), but not external caller to guarantee that.

Looking forward to your reply, thank you so much.

**Comment by menghaoranss** [comment]
1. `HintManager` is `AutoCloseable`, When `HintManager` was released normally, `HINT_MANAGER_HOLDER` will be cleared
2. `Hintmanager` needs to support multi-threaded, so it cannot be designed as a singleton

**Comment by codeboyzhou** [comment]
@menghaoranss Thanks, appreciate that, your answer is simple and clearly, especially _the second one_ , I got you.
Feel free to close this topic, please.

**Comment by codeboyzhou** [comment]
@menghaoranss
Thanks, appreciate that, your answer is simple and clearly, especially _the second one_, I got you, feel free to close this topic, please.

**Comment by menghaoranss** [comment]
@codeboyzhou  thanks for your feedback.
