### ISSUE TITLE
An error about Sharding-UI 

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12391]
I got an error when I submitted。Can't recognize yaml format correctly
When I remove the line where "- !SHARDING" is located, I can submit
![image](https://user-images.githubusercontent.com/45256940/133039481-e05bd12c-722f-4a33-8dd4-11d08e627883.png)
![image](https://user-images.githubusercontent.com/45256940/133039503-d2df7b67-aaf4-4e58-88aa-6cb2a80c420c.png)

**Comment by menghaoranss** [comment]
@marker-wu You can use DistSQL to create or alter sharing rule in the latest version.

**Comment by marker-wu** [comment]
> @marker-wu You can use DistSQL to create or alter sharing rule in the latest version.
I configured it in accordance with the latest rules
[https://shardingsphere.apache.org/document/5.0.0-beta/cn/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/](url)
![image](https://user-images.githubusercontent.com/45256940/133207328-40b61879-a04c-4ba8-a544-70f6b89f4b4e.png)

**Comment by marker-wu** [comment]
Why is there no follow-up?

**Comment by strongduanmu** [comment]
Hi @marker-wu, you can try the distsql to create or alter sharding rule. `sharding-ui` will not continue to be upgraded in the future, if necessary, you can develop it yourself.

**Comment by RaigorJiang** [comment]
@marker-wu  
Welcome to ues DistSQL:
https://shardingsphere.apache.org/document/current/cn/features/dist-sql/

**Comment by RaigorJiang** [comment]
sharding-ui is no longer maintained, so close this issue.
