### ISSUE TITLE
How can I configure the ComplexKeysShardingAlgorithm in version 5.0.0-alpha，In the form of Java API

### ISSUE THREAD

**Issue by Lychengit** [apache/shardingsphere#12392]

**Comment by tuichenchuxin** [comment]
@Lychengit You can try like this.
```
        // 配置分库策略
        orderTableRuleConfig.setDatabaseShardingStrategy(new ComplexShardingStrategyConfiguration("user_id,order_id", "dbShardingAlgorithm"));
        // 配置分库算法
        Properties dbShardingAlgorithmrProps = new Properties();
        dbShardingAlgorithmrProps.setProperty("algorithm-expression", "ds${(user_id % 2) + (order_id % 3)}");
        shardingRuleConfig.getShardingAlgorithms().put("dbShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("COMPLEX_INLINE", dbShardingAlgorithmrProps));```

**Comment by Lychengit** [comment]
@tuichenchuxin In this version（5.0.0-alpha）. no such algorithm（“COMPLEX_INLINE”）. 
![image](https://user-images.githubusercontent.com/90435449/133075029-95dfd605-c133-4792-b836-7c3195861286.png)

**Comment by tuichenchuxin** [comment]
@Lychengit  In this version（5.0.0-alpha ) need to implement `ComplexKeysShardingAlgorithm` or  you can update version.

**Comment by Lychengit** [comment]
@tuichenchuxin I have a class MyComplexKeysShardingAlgorithm to implement ComplexKeysShardingAlgorithm. But I don't know how to configure it（MyComplexKeysShardingAlgorithm ）. Make it work.

**Comment by tuichenchuxin** [comment]
@Lychengit Configure `MyComplexKeysShardingAlgorithm` as spi. Or can you offer your example, let me check.

**Comment by Lychengit** [comment]
spi like this? yes, I succeeded in trying like this yesterday. But I think it's a little informal... ,So I want to ask if there is a better way.
![image](https://user-images.githubusercontent.com/90435449/133182726-c6e4ca4b-db2b-4d50-b623-9d238f3b150b.png)

**Comment by tuichenchuxin** [comment]
@Lychengit Yes. Spi is more flexible.

**Comment by Lychengit** [comment]
@tuichenchuxin ok! Thank you very much. I like the style of the version 5.0.0-beta very much. It's more flexible. But there are some problems with this version（5.0.0-beta）. So I'm trying version 5.0.0-alpha.

**1、** No error prompt for duplicate unique values. like this. The id field is the primary key. Insert ID 123 at the same time, No error.
![image](https://user-images.githubusercontent.com/90435449/133186469-6595303d-62ab-45f3-b176-8bb33343b18f.png)
![image](https://user-images.githubusercontent.com/90435449/133186552-e4ea30a8-a885-4c64-b037-cdbbd8b556a8.png)

**2、** This problem has been fixed（But it's still on the master branch）.
![image](https://user-images.githubusercontent.com/90435449/133187047-39fed112-c6ca-4421-b796-080046608c6b.png)

**3、** If the field is capitalized, it may cause all tables to be inserted. 
![image](https://user-images.githubusercontent.com/90435449/133188053-38e8545e-2d8a-4cee-be72-910bfe457409.png)
![image](https://user-images.githubusercontent.com/90435449/133188607-2b205137-5dcf-4883-987b-e276ccd84392.png)

**Comment by tuichenchuxin** [comment]
@Lychengit I understand that. We will release the latest version soon, and you are welcome to try it out at that time

**Comment by Lychengit** [comment]
@tuichenchuxin Thank you for your hard work. I will!
