### ISSUE TITLE
Can parse hint on SQL parser engine

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#1240]

**Comment by leehom** [comment]
I have some idea about hint sharding, what hint means is routing to db.table according business, and  business in som way deal with fields in sql,  parsing sql just found what fields business dealed with but not the business it self. I now use hint sharding, I found hint sharding like resource manage so much, that is to say，assigning which db.table to which user, I think developing a resource management can help more

**Comment by terrymanu** [comment]
Closed because no contributor interest with this feature
