### ISSUE TITLE
When using calcite to execute SQL containing Chinese, proxy will throw an exception.

### ISSUE THREAD

**Issue by chengh1** [apache/shardingsphere#12406]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When using calcite to execute SQL containing Chinese, it can be executed successfully。

### Actual behavior
When using calcite to execute SQL containing Chinese, it will throw exception "Caused by: org.apache.calcite.runtime.CalciteException: Failed to encode '已启用' in character set 'ISO-8859-1'"

### Reason analyze (If you can)
The default encoding of calcite is'ISO-8859-1', which is a single-byte encoding. Chinese characters will appear garbled and cause errors.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、Execute an join query sql which containing Chinese and tables are not  binding tables, and the proxy will use calcite to execute this sql. At this time, the proxy will throw an exception.
2、sql for example :

select t.*,o.item_id as item_id,(case when t.status = 'init' then '已启用' when t.status = 'failed' then '已停用' end) as stateName
    from t_order t left join t_order_item as o on o.order_id =t.order_id where t.order_id=1000 limit 1

this sql is from the file dql-integration-test-cases.xml which is in shardingsphere-integration-test module,  table t_order and t_order_item are not binding tables.

**Comment by chengh1** [comment]
we can resolve it by adding a calcite configuration file to specify charset as utf8 .
step:
1、create a calcite configuration file name as saffron.properties.
2、 add the config "calcite.default.charset = utf8" in the file.

**Comment by sandynz** [comment]
Hi @chengh1 , thanks for your feedback. Since it's resolved, I'll close it now.
