### ISSUE TITLE
How to configure the spring namespace?

### ISSUE THREAD

**Issue by xfyang1988** [apache/shardingsphere#12419]
If "xmlns:shardingsphere="http://shardingsphere.apache.org/schema/shardingsphere/sharding"" is configured, the following "shardingsphere:data-source" tag cannot be found, and vice versa.ShardingSphere version is 5.0.0-beta

![image](https://user-images.githubusercontent.com/19721648/133203648-e88d176c-5a14-473e-8ab4-1c6f4767741e.png)
![image](https://user-images.githubusercontent.com/19721648/133203672-0eb6ee18-09d0-499a-8638-e60ee2503523.png)

**Comment by menghaoranss** [comment]
please refer to the example of 5.0.0-beta:

https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-namespace-jpa-example/src/main/resources/META-INF/application-sharding-tables.xml

**Comment by xfyang1988** [comment]
Configured according to your example, but reported the following error?

Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 20 in XML document from class path resource [spring/local/springbeans-sharding-datasource.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 89; cvc-complex-type.3.2.2: 元素 'sharding:standard-strategy' 中不允许出现属性 'algorithm-ref'。

![image](https://user-images.githubusercontent.com/19721648/133211925-9b2865ec-a179-423c-a7e0-709aafc1722e.png)

**Comment by xfyang1988** [comment]
Configured according to your example, but reported the following error?

Offending resource: class path resource [spring/applicationContext.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 20 in XML document from class path resource [spring/local/springbeans-sharding-datasource.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 32; cvc-complex-type.2.4.c: 通配符的匹配很全面, 但无法找到元素 'sharding:sharding-algorithm' 的声明。

![image](https://user-images.githubusercontent.com/19721648/133218745-86e79ebb-ebc0-4801-bb70-b917d203ddab.png)

**Comment by zjcnb** [comment]
@xfyang1988 Hi, Can you provider demo project for us, i will check it.

**Comment by xfyang1988** [comment]
This is based on the project renovation, based on the company's confidentiality agreement, can not be opened, you can check it out

> @xfyang1988 Hi, Can you provider demo project for us, i will check it.
