### ISSUE TITLE
Cannot find strategy for generate keys

### ISSUE THREAD

**Issue by zjbxxx** [apache/shardingsphere#12424]
I am using sharding-proxy-5.0.0-beat. Now there is a problem. When I perform a single table insertion operation on a table that is not fragmented, the error is as follows: This version of shardingproxy doesn't yet support this SQL. 'cannot find strategy for generate keys. Tell me how to solve this problem? Thank you very much!

**Comment by tuichenchuxin** [comment]
@zjbxxx Can you show me the config?

**Comment by zjbxxx** [comment]
> @zjbxxx你能告诉我配置吗？

schemaName: heattingwork
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/heattingwork?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    
    
rules:
- !SHARDING
  tables:
    dtu_log:
      actualDataNodes: ds_0.dtu_log_$->{2021..2022}${(1..12).collect{t ->t.toString().padLeft(2,'0')}}
      tableStrategy:
        standard:
          shardingColumn: create_date
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake

  bindingTables:
    - dtu_log
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: dtu_log_$->{create_date.take(4) + create_date[5,6]}
        allow-range-query-with-inline-sharding: true

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123

**Comment by zjbxxx** [comment]
> @zjbxxx你能告诉我配置吗？

Sorry, I'm a novice. The configuration format just given may be a little messy

**Comment by AdelaHong** [comment]
I have encountered this problem. This problem does exist in the 5.0.0-bate version. The author of the master version has already repaired it. It is recommended to download the master branch by yourself.

**Comment by zjbxxx** [comment]
> I have encountered this problem. This problem does exist in the 5.0.0-bate version. The author of the master version has already repaired it. It is recommended to download the master branch by yourself.

Thank you very much for helping me solve the problem, thank you!

**Comment by zjbxxx** [comment]
> I have encountered this problem. This problem does exist in the 5.0.0-bate version. The author of the master version has already repaired it. It is recommended to download the master branch by yourself.
Hello, I'd like to ask, do I download the source code of the master branch and type it into a package in tar.gz format?

**Comment by AdelaHong** [comment]
After downloading the master version, use maven to make a jar package

**Comment by zjbxxx** [comment]
> After downloading the master version, use maven to make a jar package

Hello, I'm really sorry to bother you again. I downloaded the source code of master and made an error in the process of packaging with maven, as follows:

[ERROR] Failed to execute goal on project shardingsphere-proxy-common: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-proxy-common:jar:5.0.0-RC1-SNAPSHOT: The following artifacts could not be resolved: org.apache.shardingsphere:shardingsphere-infra-context:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-memory-mode-core:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-standalone-mode-core:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-standalone-mode-repository-file:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-cluster-mode-core:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-sharding-core:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-readwrite-splitting-core:jar:5.0.0-RC1-SNAPSHOT, org.apache.shardingsphere:shardingsphere-encrypt-core:jar:5.0.0-RC1-SNAPSHOT,

Do you know what caused this? Excuse me!

**Comment by AdelaHong** [comment]
Never encountered before, if you need, you can email the jar package to you

**Comment by zjbxxx** [comment]
> 没遇到过，需要的话可以把jar包email给你

I replaced the version with 5.0.0-alpha to avoid this problem. Although there are other problems now, I am solving them. Thank you again

**Comment by zjbxxx** [comment]
> 没遇到过，需要的话可以把jar包email给你

Hello, my email is zjb_ job@126.com , you can send the jar package to my mailbox when it is convenient for you, please

**Comment by Naiwei-stamina** [comment]
> Never encountered before, if you need, you can email the jar package to you

hello bro, i'm also encounting this problem now, can you please send this jar package to me when you are convenient ? my email address is 1261879381@qq.com, thank you

**Comment by sandynz** [comment]
Hi @zjbxxx , does it work now? Could we close it?

**Comment by zjbxxx** [comment]
> Hi @zjbxxx , does it work now? Could we close it?
Yes, I don't use this project anymore
