### ISSUE TITLE
version 4.1.1 ,  The database has a value, but the result returns null

### ISSUE THREAD

**Issue by zhw1992** [apache/shardingsphere#12425]
select aa,(select count(1) from xx) as bb from cc

The value of bb returns null,How to solve this situation?

**Comment by strongduanmu** [comment]
Hi @zhw1992, thank you for your feedback. The 4.x version does not support subqueries very well, you can try the latest 5.x version.

**Comment by terrymanu** [comment]
The `5.0.0-beta` version supports federation engine which can process subquery, please try it, thank you.
