### ISSUE TITLE
Memory leak with  ParameterMarkerExpressionSegment

### ISSUE THREAD

**Issue by fffscd** [apache/shardingsphere#12447]
## shardingsphere version 
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
 <version>4.0.0-RC2</version>
        </dependency>

## dump file
num   #instances   #bytes    #class name
----------------------------------------------
1: 416715 76135448 [C
2: 703904 28156160 com.mysql.cj.ClientPreparedQueryBindValue
3: 716219 24664480 [B
4: 999889 23997336 java.util.LinkedList$Node
5: 919298 22063152 org.apache.shardingsphere.core.parse.sql.segment.dml.expr.simple.ParameterMarkerExpressionSegment
6: 413983 9935592 java.lang.String
7: 90277 8666592 sun.util.calendar.Gregorian$Date
8: 45092 8629888 [Ljava.lang.Object;
9: 33902 2983376 java.lang.reflect.Method
10: 89915 2877280 java.sql.Timestamp

## gc times
S0 S1 E O M CCS YGC YGCT FGC FGCT GCT
0.00 10.00 0.00 40.10 97.33 95.64 109504 2288.480 323 298.115 2586.596
0.00 0.00 33.19 30.19 97.33 95.64 109504 2288.480 323 299.660 2588.140
46.43 0.00 3.94 30.19 97.33 95.64 109505 2288.504 323 299.660 2588.164
46.43 0.00 64.46 30.19 97.33 95.64 109505 2288.504 323 299.660 2588.164
0.00 31.42 44.28 30.26 97.33 95.64 109506 2288.516 323 299.660 2588.176

Too many ParameterMarkerExpressionSegment objects, and  this object cannot be GC

**Comment by menghaoranss** [comment]
@fffscd thanks for your feedback, have you tried with the latest version?

**Comment by fffscd** [comment]
I upgraded to see
