### ISSUE TITLE
【Interval Sharding Algorithm Type: INTERVAL Attributes: datetime-interval-amount】invalid

### ISSUE THREAD

**Issue by WangShaolin-GitHub** [apache/shardingsphere#12458]
Hello，shardingsphere version 5.0.0-alpha：spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-interval.props.datetime-interval-amount=2
How do I set it? To enter the RangeShardingValue
![image](https://user-images.githubusercontent.com/35981782/133426858-81691dcb-70ff-42c0-a7b1-c8a2944a591a.png)

**Comment by zjcnb** [comment]
@WangShaolin-GitHub Hi, You can try it . I think it's can work well. And i 'm looking forward to your feedback.

**Comment by WangShaolin-GitHub** [comment]
s per the above configuration, the creation time 2014-05-22 should be stored in t_ORDER_20140521, but in t_ORDER_20140522

**Comment by WangShaolin-GitHub** [comment]
@zjcnb As per the above configuration, the creation time 2014-05-22 should be stored in t_ORDER_20140521, but in t_ORDER_20140522

**Comment by zjcnb** [comment]
@WangShaolin-GitHub  I don't think!  Because, your creation time is 2014-05-22, it' s sharding value, so shardingsphere are calculated from 2014-05-22.

**Comment by zjcnb** [comment]
By the way, your datetime-lower is 2014-05-21 and datetime-upper is 2014-05-31, and your datetime-interval-amount is 2, your creation time is 2014-05-22.
 So, shardingsphere can calculation available table. such as: 20140522, 20140524, 20140526, 20140528, 20140530

**Comment by WangShaolin-GitHub** [comment]
I still don't understand. insert time 2014-05-23, error as follows:
![image](https://user-images.githubusercontent.com/35981782/133545216-b0203ff8-9237-43ba-bd8e-2cdf0a2fa790.png)
![image](https://user-images.githubusercontent.com/35981782/133545275-f305004c-86e5-45c4-bea1-cfde490be48c.png)

**Comment by WangShaolin-GitHub** [comment]
I have debugged the source code and found that it always goes to the method on line 123, not line 130. If I want to go to the method on line 130, how should I configure it?
![image](https://user-images.githubusercontent.com/35981782/133546094-3a1ecedb-feb7-4447-b66f-0afcbe4ade7b.png)
Method 1. String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Comparable<?>> shardingValue)
Method 2. Collection<String> doSharding(final Collection<String> availableTargetNames, final RangeShardingValue<Comparable<?>> shardingValue)

**Comment by zjcnb** [comment]
you should change your sql, such as: create_time >= '2014-05-22 00:00:00' and create_time <='2014-05-22 23:59:59'

**Comment by WangShaolin-GitHub** [comment]
Thank you for answering the second question, what about the first one?

**Comment by WangShaolin-GitHub** [comment]
After repeated tests, I found that the sharding table is only related to the sharding suffix-pattern attribute, and has nothing to do with datetime-interval-amount and datetime-interval-unit. the source code is as follows:
![image](https://user-images.githubusercontent.com/35981782/133558553-e264ff9a-facf-484e-b3ef-308e2734a08f.png)

**Comment by zjcnb** [comment]
The first one question, you set datetime-interval-amount is 2, 
available table : 20140522, 20140524, 20140526, 20140528, 20140530. you can set set datetime-interval-amount is 1

**Comment by WangShaolin-GitHub** [comment]
After repeated tests, I found that the sharding table is only related to the sharding suffix-pattern attribute, and has nothing to do with datetime-interval-amount and datetime-interval-unit. the source code is as follows:
![image](https://user-images.githubusercontent.com/35981782/133559486-15b6b1a8-bead-4b3b-bc93-dda95ddb79d5.png)

**Comment by zjcnb** [comment]
> After repeated tests, I found that the sharding table is only related to the sharding suffix-pattern attribute, and has nothing to do with datetime-interval-amount and datetime-interval-unit. the source code is as follows:
> ![image](https://user-images.githubusercontent.com/35981782/133559486-15b6b1a8-bead-4b3b-bc93-dda95ddb79d5.png)

yes， create_time is not an interval. datetime-interval-amount not be used

**Comment by tuichenchuxin** [comment]
@WangShaolin-GitHub After this [pr](https://github.com/apache/shardingsphere/pull/12625) 
is merged, this will be fixed on branch master.

**Comment by sandynz** [comment]
Hi @WangShaolin-GitHub , since it's already fixed, I'll close it now. If it still doesn't work, you could feedback here again, thanks.
