### ISSUE TITLE
support Administration Statements sql parse `ALTER RESOURCE GROUP`

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#12452]
Hi community,

This issue is for #10887.

## Aim
support parse mysql administration statements sql `ALTER RESOURCE GROUP`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
We have completed the rule in DALStatement.g4.
But have not yet implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`
To complete this issue, I think we should complete these steps:
- Create `MySQLAlterResoureGroupStatement` class 
- Add rule  in `shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java`
- Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`.
- Finally, add test for parse statement in `shardingsphere-test` module
## Example FYI
- Refer to this merged pr：https://github.com/apache/shardingsphere/pull/12979/files

**Comment by sanjanathomas** [comment]
Can I work on this issue?

**Comment by menghaoranss** [comment]
@sanjanathomas welcome, assigned.

**Comment by tuichenchuxin** [comment]
@sanjanathomas Hello, is there any progress about this issue?

**Comment by clbigdata** [comment]
I want to solve this problem
