### ISSUE TITLE
support Administration Statements sql parse CHECKSUM TABLE

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#12465]
Hi community,

This issue is for #10887.

## Aim
support parse mysql administration statements sql `CHECKSUM TABLE`

## Basic Qualifications
- java
- maven
- antlr4
- 
## Detail
We have completed the rule in DALStatement.g4.
But have not yet implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`
To complete this issue, I think we should complete these steps:
- Complete `MySQLChecksumTableStatement` class 
- Add rule for clone in `shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java`
- Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`.
- Finally, add test for parse clone statement in `shardingsphere-test` module
## Example FYI
- Refer to this merged pr：https://github.com/apache/shardingsphere/pull/12979/files

**Comment by sangeethapradeep** [comment]
Can I work on this issue?

**Comment by terrymanu** [comment]
Sure, I just assign it to you

**Comment by Liangda-w** [comment]
@strongduanmu yes, I'm interested in this issue and can take it over if @sangeethapradeep is no longer working on this:)

**Comment by strongduanmu** [comment]
Hi @Liangda-w I have assign this issue to you, and you can work on this now.

**Comment by clbigdata** [comment]
I want to solve this problem
