### ISSUE TITLE
support Administration Statements sql parse REPAIR TABLE

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#12467]
Hi community,

This issue is for #10887.

## Aim
support parse mysql administration statements sql `REPAIR TABLE`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
We have completed the repair rule in DALStatement.g4.
But have not yet implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`
To complete this issue, I think we should complete these steps:
- Complete `MySQLRepairTableStatement` class 
- Add rule for clone in `shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java`
- Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`.
- Finally, add test for parse clone statement in `shardingsphere-test` module
## Example FYI
- Refer to this merged pr：https://github.com/apache/shardingsphere/pull/12979/files

**Comment by LeeGuoPing** [comment]
I wanna to do it
