### ISSUE TITLE
the more useless config added , the lower performance proxy will get.

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#12473]
hi, there
  this situation is provided by a tester in another company , as his description, if we test a scheme `database-1` in config-xxxx.yaml, we also put some other configs for `database-2` ... `database-10`, even we do not use these config , the performance will slow down.

**Comment by menghaoranss** [comment]
Look forward to seeing some configuration case here, and the performance is refer to startup?

**Comment by taojintianxia** [comment]
> Look forward to seeing some configuration case here, and the performance is refer to startup?

performance means the ability under presure test.

**Comment by taojintianxia** [comment]
so I test it myself :
  - test environment
    - CPU : 32C , RAM : 64G , JVM : 2g
    - version : latest proxy

I test two case seperatly : 
  - only config-readwrite-splitting.yaml
  - from config-readwrite-splitting-1.yaml to config-readwrite-splitting-10.yaml

but I didn't see any performance get down when I start up proxy with 10 config files.

**Comment by taojintianxia** [comment]
problem solved , after they update the JVM, raise up the xmx, problem solved.
as my anaylize, they got a machine without a good CPU, so that jvm settings will solve their issue

close this issue
