### ISSUE TITLE
How to build ShardingProxy?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12472]
How to build the sharding-proxy source code into a binary package? like this:
![image](https://user-images.githubusercontent.com/45256940/133541185-53e4fb8b-1de9-4bac-9e06-9407061a4f2a.png)

**Comment by taojintianxia** [comment]
take a look on the README.md of shardingsphere project

![image](https://user-images.githubusercontent.com/4112856/133541296-02358168-9d50-40ea-906b-abc73b398eec.png)

**Comment by marker-wu** [comment]
I failed to build
my version is 5.0.0-beta
here are the error message:
![image](https://user-images.githubusercontent.com/45256940/133543794-9833de2d-bf57-4801-9c6d-3192986fecb7.png)
After executing the command, some source code in the target directory is deleted
![image](https://user-images.githubusercontent.com/45256940/133543898-f3ead31b-da38-409d-b4d7-ff2e49eb8037.png)

before executing:
![image](https://user-images.githubusercontent.com/45256940/133544245-991809b9-8eea-4bcc-8805-266e3f5fdaa8.png)

**Comment by TeslaCN** [comment]
Try the following command
```
./mvnw clean install -DskipTests -Prelease -B -Drat.skip=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -T1C
```

**Comment by marker-wu** [comment]
it worked!  But I didn't see the binary package after the build 
 
![image](https://user-images.githubusercontent.com/45256940/133568586-e82c3ade-fdeb-4a25-a2ad-84e1d3ab4b0c.png)

**Comment by marker-wu** [comment]
hello！Why there is no follow-up？

**Comment by TeslaCN** [comment]
Hi @marker-wu 
You can find the package under `shardingsphere-distribution/shardingsphere-proxy-distribution/target`

**Comment by marker-wu** [comment]
yeah  i find it !!!

**Comment by marker-wu** [comment]
> Hi @marker-wu
> You can find the package under `shardingsphere-distribution/shardingsphere-proxy-distribution/target`.

The binary package built with 5.0.0-beta reports an error when running，Please help me see what is causing the problem
![image](https://user-images.githubusercontent.com/45256940/133766171-dda477ac-3359-437e-b190-fe74973771c8.png)
I can run normally in the source code

**Comment by RaigorJiang** [comment]
Resolved.

**Comment by marker-wu** [comment]
> Try the following command
> 
> ```
> ./mvnw clean install -DskipTests -Prelease -B -Drat.skip=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -T1C
> ```
it build failed on the latest master branch，Can you help provide new build commands？thank you

**Comment by RaigorJiang** [comment]
![image](https://user-images.githubusercontent.com/5668787/140522940-69464de1-a06a-42fd-b9ab-c50f1b08a48d.png)

@marker-wu  I used this command to build successfully, maybe you can try again.

**Comment by marker-wu** [comment]
> ![image](https://user-images.githubusercontent.com/5668787/140522940-69464de1-a06a-42fd-b9ab-c50f1b08a48d.png)
> 
> @marker-wu I used this command to build successfully, maybe you can try again.

I succeeded after trying again
