### ISSUE TITLE
support Administration Statements sql parse SHOW CREATE TRIGGER

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#12470]
Hi community,

This issue is for #10887.

## Aim
support parse mysql administration statements sql `SHOW CREATE TRIGGER`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
SHOW CREATE TRIGGER Statement In mysql
need to be supported in shardingsphere-sql-parser.
```
SHOW CREATE TRIGGER trigger_name
```
https://dev.mysql.com/doc/refman/8.0/en/show-create-trigger.html

## Example FYI
- DCLStatement.g4

**Comment by LeeGuoPing** [comment]
I want to have a try

**Comment by tuichenchuxin** [comment]
@LeeGuoPing Ok, thank you for your support.

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.

**Comment by LeeGuoPing** [comment]
@tuichenchuxin hi, Which purpose of this issue? I have seen SHOW CREATE TRIGGER in file
![image](https://user-images.githubusercontent.com/35389145/134477338-c65f84dc-7d0a-4d51-9ff9-b3f7383e77c2.png)

**Comment by tuichenchuxin** [comment]
@LeeGuoPing I checked it again, sorry, there is a problem with the information I described. This statement can be parsed, but it will fail when visiting, it should be because the visit method is not implemented. Are you willing to do it?

**Comment by LeeGuoPing** [comment]
> @LeeGuoPing I checked it again, sorry, there is a problem with the information I described. This statement can be parsed, but it will fail when visiting, it should be because the visit method is not implemented. Are you willing to do it?

@tuichenchuxin of course.

**Comment by tuichenchuxin** [comment]
@LeeGuoPing Thanks, hope your pr.

**Comment by LeeGuoPing** [comment]
> @LeeGuoPing Thanks, hope your pr.

@tuichenchuxin  commited
