### ISSUE TITLE
support Administration Statements sql parse SHOW CREATE USER

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#12471]
Hi community,

This issue is for #10887.

## Aim
support parse mysql administration statements sql `SHOW CREATE USER`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
SHOW CREATE USER Statement In mysql
need to be supported in shardingsphere-sql-parser.
```
SHOW CREATE USER user
```
https://dev.mysql.com/doc/refman/8.0/en/show-create-user.html

## Example FYI
- DCLStatement.g4

**Comment by strawberry-crisis** [comment]
Can I have this one plz

**Comment by tuichenchuxin** [comment]
> Can I have this one plz

Welcome, ok.

**Comment by strawberry-crisis** [comment]
Hi there,
"SHOW CREATE USE" exists in "DALStatement.g4", I'm kinda confused about what should I do about this issue.

![image](https://user-images.githubusercontent.com/13709330/134645222-a1708526-2648-4dd4-a79b-c434a906b14a.png)

**Comment by tuichenchuxin** [comment]
@strawberry-crisis This sql can be parsed as a tree, but visit method is not implemented. So it's not completed in sql-parser.

**Comment by strawberry-crisis** [comment]
Got it, I'll try my best
