### ISSUE TITLE
Optimize the FAQ

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#12480]
### Background
Currently, the records in the [FAQ](https://shardingsphere.apache.org/document/current/en/others/faq/) are not classified, which is not conducive to search and maintenance.
### Aim
1. Add the corresponding category tag to the record in the FAQ.
2. Put the content of the same tags together.

The expected result after adjustment is like this
```
1. [Sharding] Why are the default distributed auto-augment key strategy provided by ShardingSphere not continuous and most of them end with even numbers?
2. [Sharding] How to solve Cloud not resolve placeholder … in string value … error?
3. [Encryption] How to solve that data encryption can’t work with JPA?
4. [Other] Why do some compiling errors appear? Why did not the IDEA index the generated codes?
```

We provide these tags
```
[JDBC] [Proxy] [Sharding] [Readwrite-splitting] [Scaling] [Shadow] [DistSQL] [Other]
```
Corresponding Chinese tags
```
[JDBC] [Proxy] [分片] [读写分离] [弹性伸缩] [影子库压测] [DistSQL] [其他]
```

**Notice: ShardingSphere documentation contains English and Chinese versions, which will be processed separately.**

**Comment by yx9o** [comment]
Please assign to me.

**Comment by strongduanmu** [comment]
@yx9o Welcome.
