### ISSUE TITLE
Add unit test for ShardingFederatedRoutingEngine

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#12488]
This issue is for adding unit tests for ShardingFederatedRoutingEngine.

After PR #12486 is merged, please cover the latest logic in the unit test.

If you are interested, please leave a message.

**Comment by yx9o** [comment]
I want to try this issue.

**Comment by strongduanmu** [comment]
Welcome @yx9o, I have assigned this issue to you.
