### ISSUE TITLE
Add ut for ShadowExtractor in shadow project

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#12498]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-shadow-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] ShadowExtractor

## Examples FYI

- ShadowValueJudgeUtilTest

**Comment by zzs52** [comment]
can I have a try?

**Comment by menghaoranss** [comment]
@zzs52 hi, any progress here?

**Comment by zzs52** [comment]
> 
Sorry, I was not very free before, I will finish it soon
