### ISSUE TITLE
Add ut for ShadowUpdateStatementRoutingEngine in shadow project

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#12495]
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-shadow-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [ ] ShadowUpdateStatementRoutingEngine

## Examples FYI

- ShadowInsertStatementRoutingEngineTest

**Comment by AbnerHung** [comment]
can i have a try ?

**Comment by sandynz** [comment]
Hi @AbnerHung , welcome, already assigned to you.

**Comment by AbnerHung** [comment]
Ok, sorry for the slow progress, I'll unassign myself.
