### ISSUE TITLE
Add unit test for SchemaMetaDataPersistService

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#12511]
Please add unit test for this method:

```
public void persist(final String schemaName) {
    repository.persist(SchemaMetadataNode.getSchemaNamePath(schemaName), "");
}
```

**Comment by pavluchenko** [comment]
Hi, I would like to look on this. Can you please assign to me this issue?

**Comment by zjcnb** [comment]
> Hi, I would like to look on this. Can you please assign to me this issue?

yes, welcome

**Comment by zjcnb** [comment]
This unit test has been added.
