### ISSUE TITLE
Some query failed get the column value

### ISSUE THREAD

**Issue by 448700174** [apache/shardingsphere#12517]
My sql execute sucess, but some column's value cannot map to entity.The failed column including account_type,status,is_accounted,creator_id,and all left join columns(category,category_type,category_title,goods_title,evidence).
The origin SQL is:
SELECT
cod.*,
cc.category,
cc.category_type,
cc.category_title,
cg.goods_title,
cg.evidence
FROM
care_order_detail cod
left join care_goods cg on cg.id = cod.goods_id
left join care_category cc on cc.id = cg.category_id
WHERE 1=1
AND cod.id = #{id}
and cod.tenant_id = #{tenantId}

The code is current master.

**Comment by menghaoranss** [comment]
Could you provide your configurations, print the logic sql and actual sql in the log?

**Comment by 448700174** [comment]
2021-09-18 15:36:20.564 [http-nio-8099-exec-4] INFO  ShardingSphere-SQL - Logic SQL: SELECT
    cod.*,
    cc.category,
    cc.category_type,
    cc.category_title,
    cg.goods_title,
    cg.evidence
    FROM
    care_order_detail cod
    left join care_goods cg on cg.id = cod.goods_id
    left join care_category cc on cc.id = cg.category_id
    WHERE 1=1
    AND cod.id = ?
    and cod.tenant_id = ?
2021-09-18 15:36:20.564 [http-nio-8099-exec-4] INFO  ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
2021-09-18 15:36:20.564 [http-nio-8099-exec-4] INFO  ShardingSphere-SQL - Actual SQL: ds ::: SELECT
    cod.*,
    cc.category,
    cc.category_type,
    cc.category_title,
    cg.goods_title,
    cg.evidence
    FROM
    care_order_detail_12 cod
    left join care_goods cg on cg.id = cod.goods_id
    left join care_category cc on cc.id = cg.category_id
    WHERE 1=1
    AND cod.id = ?
    and cod.tenant_id = ? ::: [2981, 12]

My config is:
         sharding:
            key-generators:
               snowflake:
                  type: SNOWFLAKE
                  props:
                     worker-id: 123
            sharding-algorithms:
               tenant-id-sharding:
                  type: CLASS_BASED
                  props:
                     strategy: STANDARD
                     algorithmClassName: com.youban.common.dao.TenantIdShardingAlgorithm
            binding-tables:
               - care_task,care_task_item,care_task_detail
               - care_patrol_task,care_patrol_subtask,care_patrol_item
            tables:
               care_task:
                  actual-data-nodes: ds.care_task_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding
               care_task_detail:
                  actual-data-nodes: ds.care_task_detail_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding
               care_task_item:
                  actual-data-nodes: ds.care_task_item_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding
               care_patrol_task:
                  actual-data-nodes: ds.care_patrol_task_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding
               care_patrol_item:
                  actual-data-nodes: ds.care_patrol_item_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding
               care_patrol_subtask:
                  actual-data-nodes: ds.care_patrol_subtask_$->{1..99}
                  table-strategy:
                     sharding-column: tenant_id
                     sharding-algorithm-name: tenant-id-sharding
               care_order_detail:
                  actual-data-nodes: ds.care_order_detail_$->{1..99}
                  table-strategy:
                     standard:
                        sharding-column: tenant_id
                        sharding-algorithm-name: tenant-id-sharding

**Comment by 448700174** [comment]
And I debug into mybatis code 
![image](https://user-images.githubusercontent.com/20518071/133881279-62a43e8a-eac2-4d56-8e3c-6b37eb765d30.png)

The account_type's value got in org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet, but failed to transfer into entity object.

**Comment by 448700174** [comment]
Any updates?

**Comment by terrymanu** [comment]
Could you provide the necessary information?
Maybe follow issue template as an example
