### ISSUE TITLE
How to change the default port of Sharding-Proxy

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12521]
How to change the default  port of Sharding-Proxy 3307?

**Comment by RaigorJiang** [comment]
Please refer to document:
https://shardingsphere.apache.org/document/current/cn/quick-start/shardingsphere-proxy-quick-start/

**Comment by RaigorJiang** [comment]
Or another doc:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/usage/startup/#notices

**Comment by RaigorJiang** [comment]
Hello @marker-wu , if this question has been resolved, can we close this issue?

**Comment by marker-wu** [comment]
> Hello @marker-wu , if this question has been resolved, can we close this issue?

sure

**Comment by RaigorJiang** [comment]
Thanks, please enjoy the community.
