### ISSUE TITLE
How to build a sharding-proxy cluster？

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12533]
How to build a sharding-proxy cluster？

**Comment by CrackerSuperior** [comment]
I was thinking about that, too. 
My simple solution is to make ZooKeeper the configuration center and registry. LVS perform load balancing. It works ok. But I don't know if it really meets the clustering requirements

**Comment by CrackerSuperior** [comment]
This is my picture
![sharding集群English@2x](https://user-images.githubusercontent.com/45088781/133868866-52a11f4f-42fb-46ac-8479-35e0fba53901.png)
：

**Comment by marker-wu** [comment]
> This is my picture:
> ![sharding集群English@2x](https://user-images.githubusercontent.com/45088781/133868866-52a11f4f-42fb-46ac-8479-35e0fba53901.png)

Haha, I have the same idea as you. I tried to use Nginx to proxy proxy last night, but it didn’t work. I don’t know if there is a problem with my configuration.
Have you tried successfully?

**Comment by CrackerSuperior** [comment]
> > This is my picture:
> > ![sharding集群English@2x](https://user-images.githubusercontent.com/45088781/133868866-52a11f4f-42fb-46ac-8479-35e0fba53901.png)
> 
> Haha, I have the same idea as you. I tried to use Nginx to proxy proxy last night, but it didn’t work. I don’t know if there is a problem with my configuration.
> Have you tried successfully?

My virtual IP does connect to all of my proxies, and it's polling

**Comment by marker-wu** [comment]
> > > This is my picture:
> > > ![sharding集群English@2x](https://user-images.githubusercontent.com/45088781/133868866-52a11f4f-42fb-46ac-8479-35e0fba53901.png)
> > 
> > 
> > Haha, I have the same idea as you. I tried to use Nginx to proxy proxy last night, but it didn’t work. I don’t know if there is a problem with my configuration.
> > Have you tried successfully?
> 
> My virtual IP does connect to all of my proxies, and it's polling

Can you share your Nginx configuration？

**Comment by CrackerSuperior** [comment]
> > > > This is my picture:
> > > > ![sharding集群English@2x](https://user-images.githubusercontent.com/45088781/133868866-52a11f4f-42fb-46ac-8479-35e0fba53901.png)
> > > 
> > > 
> > > Haha, I have the same idea as you. I tried to use Nginx to proxy proxy last night, but it didn’t work. I don’t know if there is a problem with my configuration.
> > > Have you tried successfully?
> > 
> > 
> > My virtual IP does connect to all of my proxies, and it's polling
> 
> Can you share your Nginx configuration？

Sorry, I'm using LVS.

**Comment by CrackerSuperior** [comment]
I can give you the steps of LVS if you want to use LVS too

**Comment by marker-wu** [comment]
> I can give you the steps of LVS if you want to use LVS too

OK, let me see

**Comment by CrackerSuperior** [comment]
> > 如果你也想用LVS我可以给你LVS的步骤
> 
> 好的，让我看看

LB Server Configuration:
``` shell
ifconfig network_card_name vip/mask up
ipvsadm -C
ipvsadm --set 30 5 60
ipvsadm -A -t vip:port -s rr -p 60
ipvsadm -a -t vip:port -r proxy_ip:port -g -w 1
#All proxy ip must be matched
ipvsadm -ln
ipvsadm -S > /etc/sysconfig/ipvsadm
systemctl restart ipvsadm
```

Web Server Configuration:
Disable ARP packet broadcasting:
```shell
cat >>/etc/sysctl.conf<<EOF 
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.lo.arp_ignore = 1
net.ipv4.conf.lo.arp_announce = 2 EOF
sysctl -p
```
Bind virtual IP addresses, add static routes, receive packets from the LB server, and forward the packets to the LO network adapter for processing:
``` shell
ip addr add vip/mask dev lo 
route add -host proxy_ip dev lo
```

**Comment by marker-wu** [comment]
> > > 如果你也想用LVS我可以给你LVS的步骤
> > 
> > 
> > 好的，让我看看
> 
> LB Server Configuration:
> 
> ```shell
> ifconfig network_card_name vip/mask up
> ipvsadm -C
> ipvsadm --set 30 5 60
> ipvsadm -A -t vip:port -s rr -p 60
> ipvsadm -a -t vip:port -r proxy_ip:port -g -w 1
> #All proxy ip must be matched
> ipvsadm -ln
> ipvsadm -S > /etc/sysconfig/ipvsadm
> systemctl restart ipvsadm
> ```
> 
> Web Server Configuration:
> Disable ARP packet broadcasting:
> 
> ```shell
> cat >>/etc/sysctl.conf<<EOF 
> net.ipv4.conf.all.arp_ignore = 1
> net.ipv4.conf.all.arp_announce = 2
> net.ipv4.conf.lo.arp_ignore = 1
> net.ipv4.conf.lo.arp_announce = 2 EOF
> sysctl -p
> ```
> 
> Bind virtual IP addresses, add static routes, receive packets from the LB server, and forward the packets to the LO network adapter for processing:
> 
> ```shell
> ip addr add vip/mask dev lo 
> route add -host proxy_ip dev lo
> ```

Haha, thank you, I built one with Haproxy and it worked！

**Comment by CrackerSuperior** [comment]
> > > > 如果你也想用LVS我可以给你LVS的步骤
> > > 
> > > 
> > > 好的，让我看看
> > 
> > 
> > LB Server Configuration:
> > ```shell
> > ifconfig network_card_name vip/mask up
> > ipvsadm -C
> > ipvsadm --set 30 5 60
> > ipvsadm -A -t vip:port -s rr -p 60
> > ipvsadm -a -t vip:port -r proxy_ip:port -g -w 1
> > #All proxy ip must be matched
> > ipvsadm -ln
> > ipvsadm -S > /etc/sysconfig/ipvsadm
> > systemctl restart ipvsadm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Web Server Configuration:
> > Disable ARP packet broadcasting:
> > ```shell
> > cat >>/etc/sysctl.conf<<EOF 
> > net.ipv4.conf.all.arp_ignore = 1
> > net.ipv4.conf.all.arp_announce = 2
> > net.ipv4.conf.lo.arp_ignore = 1
> > net.ipv4.conf.lo.arp_announce = 2 EOF
> > sysctl -p
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bind virtual IP addresses, add static routes, receive packets from the LB server, and forward the packets to the LO network adapter for processing:
> > ```shell
> > ip addr add vip/mask dev lo 
> > route add -host proxy_ip dev lo
> > ```
> 
> Haha, thank you, I built one with Haproxy and it worked！

congratulations

**Comment by tristaZero** [comment]
@marker-wu @CrackerSuperior Hi, everyone, thanks for your discussion, especially @CrackerSuperior 's diagram, looks nice.
I'd like to move this issue to the `discussion` section to make more people know about your talk. ;-)
