### ISSUE TITLE
JDBCExecutorCallbackError

### ISSUE THREAD

**Issue by cuixiaoxult** [apache/shardingsphere#12536]
![06657fc32527658bba8e514e421b4d6](https://user-images.githubusercontent.com/49865284/133870189-79e2a9bb-894a-4583-8bc0-9220e0897f39.png)
The exception information returned by mysql executing the insert method is caught by the method execute catch of JDBCExecutorCallback and the execution result is false, which causes the business code to fail to obtain the exception information

**Comment by menghaoranss** [comment]
@cuixiaoxult For English only, please translate the issue title to English .

**Comment by tristaZero** [comment]
@cuixiaoxult Hey thanks for your debug. Which version do you use?
@strongduanmu Could you check this one?

**Comment by strongduanmu** [comment]
Hi @cuixiaoxult, thank you for your feedback. This issue is duplicated with #11251, and it has been fixed in master branch. You can try the latest code in master branch.

**Comment by strongduanmu** [comment]
Duplicate with #11251.
