### ISSUE TITLE
Add unit test for scaling DataSourceWrapper

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#12540]
Hi community,

This issue is for #10887.

### Aim
Add unit test for `org.apache.shardingsphere.scaling.core.common.datasource.DataSourceWrapper` to test its public functions:
- Mock `DataSource` of `java.sql`, verify certain method is invoked.

### Basic Qualifications
* Java
* Maven
* Junit.Test

**Comment by alikaanbaci** [comment]
Hello, can i work on this issue?

**Comment by tristaZero** [comment]
Sure, @alikaanbaci are you still interested in this one? ;-)

**Comment by alikaanbaci** [comment]
@tristaZero yeap gladly :)

**Comment by alikaanbaci** [comment]
Hello, @tristaZero , @sandynz, I opened the pull request for the issue
