### ISSUE TITLE
Use `docker pull apache/shardingsphere-proxy` cannot pull the image.

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#12542]
## Bug Report
Hi, community,
        I encountered the following problems when pulling the official shardingsphere-proxy Docker image:
```
1. The "docker pull apache/shardingsphere-proxy" in the document cannot pull the image.
2. The pull command searched by dockerhub is "docker pull apache/sharding-proxy:5.0.0-beta".
3. The configuration in pom.xml is "<repository>apache/shardingsphere-proxy</repository>".
```

As above: 
several documents are inconsistent, the image name in dockerhub is incorrect, and the image in the document cannot be pulled.

Related screenshots:
![image](https://user-images.githubusercontent.com/12792261/133873696-62c303ca-6cc1-43fa-8dd3-f3a984a852b7.png)
![image](https://user-images.githubusercontent.com/12792261/133873704-23127721-8eab-4b33-a464-b0f0cb0119dd.png)
![image](https://user-images.githubusercontent.com/12792261/133873712-a6b4f8af-3e81-46db-8a19-8931087005e9.png)
![image](https://user-images.githubusercontent.com/12792261/133873717-5d347516-2c00-4c65-a0bd-6a7f24c47d5a.png)
![image](https://user-images.githubusercontent.com/12792261/133877564-3e539149-9755-4069-a02d-55eb64e12c4a.png)
![image](https://user-images.githubusercontent.com/12792261/133877570-5c8f108a-f53d-4575-8a6a-49f0c5a68426.png)

### Which version of ShardingSphere did you use?
5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Use `docker pull apache/shardingsphere-proxy` can pull the image.

### Actual behavior
Use `docker pull apache/shardingsphere-proxy` cannot pull the image.
Use `docker pull apache/sharding-proxy` can pull the image.

### Reason analyze (If you can)
The image name in dockerhub needs to be adjusted to `apache/shardingsphere-proxy`.

**Comment by tristaZero** [comment]
It looks like we have a bug on our doc? @yx9o

**Comment by tristaZero** [comment]
@zjcnb could you double-check here?

**Comment by strongduanmu** [comment]
> @zjcnb could you double-check here?

@yx9o @tristaZero This is a problem with the beta release. We released the image as `sharding-proxy` incorrectly. I have modified the release process document before——pr #11521, and the issue will be resolved in the next version.

**Comment by yx9o** [comment]
@strongduanmu @tristaZero ok, there are two areas that need to be dealt with:
1. The documents are all modified to `apache/shardingsphere-proxy`.
2. Modified dockerhub to `docker pull apache/shardingsphere-proxy`.

**Comment by tristaZero** [comment]
Therefore let's fix them! @yx9o  @strongduanmu

**Comment by yx9o** [comment]
@strongduanmu @tristaZero How to maintain the official Docker image.
![image](https://user-images.githubusercontent.com/12792261/134497230-f1c9c6f1-e34b-4502-a76b-bbc4d3b875a8.png)

**Comment by tristaZero** [comment]
@taojintianxia Hi look at here.

**Comment by terrymanu** [comment]
We just create the new repo on DockerHub for shardingsphere.
We can close this issue.
