### ISSUE TITLE
[Examples] Move and delete some modules and directories.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#12569]
Hi community,

This issue is for #10887.

### Background

Refor to #12557.

### Aim
1. Move `shardingsphere-parser-example` to `other-example` .
2. Delete directory `docker/shardingsphere-jdbc`.

### How to
1. Create new module  `other-example` in `examples` project.
2. Move module `shardingsphere-parser-example` into `other-example` .
3. Delete directory `docker/shardingsphere-jdbc`.

**Comment by PuneetDabral** [comment]
sir i am new in open source can you please help me to contribute here !!.....sir

**Comment by RaigorJiang** [comment]
Hi @PuneetDabral 
Welcome to ShardingSphere, I am honored to be able to help you.
As a first step, you can refer to these documents:
- [How to Set Up Your DEV Environment](https://shardingsphere.apache.org/community/en/contribute/establish-project/)
- [Contributor Guide](https://shardingsphere.apache.org/community/en/contribute/contributor/)

**Comment by PuneetDabral** [comment]
thanku sir ..

**Comment by RaigorJiang** [comment]
You are welcome.

**Comment by PuneetDabral** [comment]
ok sir after that what i can do ...!! i know that thing ...but i dont know java very well...so please help me

**Comment by RaigorJiang** [comment]
This task does not require java coding, but you need a java development environment and some knowledge of [maven](https://maven.apache.org/).
This is a brief process:
1. Clone the ShardingSphere project
2. Import shardingsphere/examples into your IDE as a maven project
3. Adjust the modules according to the task description
4. Submit a PR

**Comment by PuneetDabral** [comment]
ok sir i will try and send a pr request please check and correct this .. thanku sir

**Comment by RaigorJiang** [comment]
> ok sir i will try and send a pr request please check and correct this .. thanku sir

OK, hope to see you later.

**Comment by PuneetDabral** [comment]
ok sir...

**Comment by PuneetDabral** [comment]
check my pr

**Comment by RaigorJiang** [comment]
Hi @PuneetDabral 
Any progress? Or is there any difficulty?

**Comment by PuneetDabral** [comment]
sir i am totally puzzle about that thing...

**Comment by RaigorJiang** [comment]
It doesn't matter, you can take some time to learn. If it really can't be done, we can let someone else do it.
No matter what, thank you very much!

**Comment by Swastyy** [comment]
Hi @RaigorJiang Can I create a PR to fix this?

**Comment by RaigorJiang** [comment]
@Swastyy  Thank you for reaching out!
