### ISSUE TITLE
[Examples] Create `mixed-feature-example` for `shardingsphere-jdbc-example`. 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#12566]
Hi community,

This issue is for #10887.

### Background

Refor to #12557.

### Aim
1. Create module `mixed-feature-example` for `shardingsphere-jdbc-example`, and create `sharding-readwrite-splitting-example`  in `mixed-feature-example`.

2. Extract sharding & readwrite-splitting mixed examples from `sharding-example` and become an independent example module.

### How to
1. Create new module `mixed-feature-example` in `shardingsphere-jdbc-example`.

2. Create new module `sharding-readwrite-splitting-example` in `mixed-feature-example`.

3. Create the following examples in the `sharding-readwrite-splitting-example` module:
   - sharding-readwrite-splitting-raw-jdbc-example
   - sharding-readwrite-splitting-spring-boot-jpa-example
   - sharding- readwrite-splitting-spring-boot-mybatis-example
   - sharding-readwrite-splitting-spring-namespace-jpa-example
   - sharding-readwrite-splitting-spring-namespace-mybatis-example
   
4. All required files can be extracted from `sharding-example`, such as YAML configuration file: 
   - https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-readwrite-splitting.yaml
   - https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-readwrite-splitting-range.yaml

5. The configuration and code of `sharding-readwrite-splitting` are no longer retained in `sharding-example`.

### Notice: 
Please pay attention to distinguish between `readwrite-splitting` and `sharding-readwrite-splitting`, this issue is for `sharding-readwrite-splitting`.

**Comment by Swastyy** [comment]
@RaigorJiang Please assign this to me.

**Comment by RaigorJiang** [comment]
Hi @Swastyy  ,
Nice to see you again, welcome!

**Comment by Swastyy** [comment]
Hey @RaigorJiang In the point 3 we need to move the mentioned examples to `sharding-readwrite-splitting-example` module or I have to create newer?
