### ISSUE TITLE
[Examples] Create `single-feature-example` for `shardingsphere-jdbc-example`.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#12563]
Hi community,

This issue is for #10887.

### Background
Refor to #12557.

### Aim
Create module `single-feature-example` for `shardingsphere-jdbc-example`, and move the existed example modules into the new module.

### How to
1. Create new module `single-feature-example` in `shardingsphere-jdbc-example`.
2. Move the following modules into `single-feature-example`:
   - cluster-mode-example
   - encrypt-example
   - extension-example
   - future-shadow-example
   - shadow-example
   - sharding-example
   - transaction-example
3. `hint-example` does not need to be moved, it will be processed in another task.

**Comment by Swastyy** [comment]
Hi @RaigorJiang Please assign this to me.
