### ISSUE TITLE
Table name tends to be case sensitive when Single Table Routing

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#12576]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

When I execute an SQL which contains the **Single Table** (the table is in the database while the table name is not in any rule files) via ShardingSphere-Proxy, the table name tends to be case sensitive.
Suppose the table **test** is the Single Table.
What I expect are

```
mysql> select * from test;
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
| fid  | fint | ffloat | ftext | fdate | fdatetime | ftimestamp          | ftime | fblob |
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
| 1    |    1 |      1 | 1     | NULL  | NULL      | 2019-12-25 06:20:43 | NULL  | NULL  |
| NULL | NULL |   NULL | NULL  | NULL  | NULL      | 2020-09-07 07:26:27 | NULL  | 4V   |
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
```

and

```
mysql> select * from TEST;
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
| fid  | fint | ffloat | ftext | fdate | fdatetime | ftimestamp          | ftime | fblob |
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
| 1    |    1 |      1 | 1     | NULL  | NULL      | 2019-12-25 06:20:43 | NULL  | NULL  |
| NULL | NULL |   NULL | NULL  | NULL  | NULL      | 2020-09-07 07:26:27 | NULL  | 4V   |
+------+------+--------+-------+-------+-----------+---------------------+-------+-------+
```

### Actual behavior

```
mysql> select * from TEST limit 1;
ERROR 1146 (42S02): Table 'demo_ds_0.TEST' doesn't exist
```

### Reason analyze (If you can)

This problem is not caused by MySQL server parameter configurations and can be easily reproduced.

**Comment by strongduanmu** [comment]
@tuohai666 Thank you for your feedback, I will check it.
