### ISSUE TITLE
SqlNodeConvertEngine.convert() parse SQL with subquery correctly.

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#12581]
### Describe the feature you would like.

SqlNodeConvertEngine.convert() can not parse SQL with subquery correctly. So, we should add some logic when processing the subquery.

SqlNodeConverter in 'org.apache.shardingsphere.infra.optimize.core.convert.converter' could not parse subquery.
For example:

SELECT_SQL_SUBQUERY_WHERE_EXISTS =
            "SELECT t_order_federate.order_id, t_order_federate.user_id "
                    + "FROM t_order_federate "
                    + "WHERE EXISTS (SELECT * FROM t_user_info WHERE t_order_federate.user_id = t_user_info.user_id)";
                   
SELECT_SQL_SUBQUERY_FROM =
            "SELECT t_order_federate.order_id, t_order_federate.user_id, u.user_id "
                    + "FROM t_order_federate, (SELECT * FROM t_user_info) as u "
                    + "WHERE t_order_federate.user_id = u.user_id ";

**Comment by strongduanmu** [comment]
@wgy8283335 Thank you for your feedback, I will optimize this problem.
