### ISSUE TITLE
Compile error after pr #12562 and #12564 merged

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12583]
I just comment 4 classes, there are:

- ShadowRuleQueryResultSet
- ShadowAlgorithmQueryResultSetTest
- ShadowRuleQueryResultSetTest
- ShadowTableRuleQueryResultSetTest

Please search "// TODO fixme with issue #12583" to fix this issue

**Comment by zhfeng** [comment]
It seems that these commits were pushed to the ```master`` branch without the CI testing. I think it could be better to avoid pushing to the ```master``` branch directly.
