### ISSUE TITLE
Some failure tests when building with JDK 11

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#12587]
Following #12578

**Comment by tristaZero** [comment]
Hi, would you like to fix this issue? I saw your activities many times, welcome!
What does make you have attention here?

**Comment by zhfeng** [comment]
Oh, I'm thinking about introduce the sharding-sphere extension in Quarkus ecosystem. So it could be better to support build with JDK 11 since Quarkus has dropped the JDK 8 support in 2.x

What do you think the JDK support in sharding-sphere ? Do we need to support such LTS JDK versions, e.g. (8, 11, 17)

**Comment by tristaZero** [comment]
You are working in upgrading JDK 11, right？ Is it enough for the next step of the plan?
