### ISSUE TITLE
[EXAMPLE] Add README.md in each example and describe in details

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#12590]
## Feature Request
I'd like to suggest to add README.md in each example

- The basic idea of the example, just like "This example shows how to do some features in sharding-sphere"
- How to build the example
- How to run the example, especailly with the command lines
- What is the expected outcome
-

**Comment by tristaZero** [comment]
Hey, that's what we plan to do next step. could you like to join and speed it up?

**Comment by zhfeng** [comment]
yeah sure, I'm very happy to join in. And it looks like better to host a seperate example repository, such as https://github.com/apache/shardingshpere-examples.

**Comment by tristaZero** [comment]
@zhfeng Cool welcome. ;-) @RaigorJiang could you update our refactoring plan on example and involve @zhfeng in?

Actually, we created a separate repo for examples, but many people feedbacked that it's indirect to visit them comparing to the place in the master branch. Hence, we merge them into this repo for convenience.

**Comment by RaigorJiang** [comment]
Hi @zhfeng 
I created an issue to adjust the structure of examples, the purpose is also to make examples easier to understand:
https://github.com/apache/shardingsphere/issues/12557

If possible, please submit a PR as an example, and then we will open the task for more people to participate. 
Do you think it is ok?

**Comment by zhfeng** [comment]
Thanks @RaigorJiang and I will take a look.

**Comment by RaigorJiang** [comment]
Now we have a new plan for `examples`, please refer to #12366, I just close this issue.
