### ISSUE TITLE
Support Quarkus extension

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#12591]
## Feature Request

I just want to add sharding sphere in [Quarkus](https://quarkus.io/) ecosystem and support as an extension

### Describe the feature you would like.

- create a quarkus extension just like ```quarkus-sharding-sphere```
- It should leverage on [Quarkus Datasource](https://quarkus.io/guides/datasource)
- It needs to produce  ```ShardingSphereDataSource``` beans with the ```application.properties``` or the yaml configuration. 
- It nees to support in JVM and Native mode

Any feedback is welcome !

**Comment by tristaZero** [comment]
Hey @zhfeng ,

Your idea looks nice! You want to add `quarkus.datasource.db-kind=shardingsphere`? Could I know why you want to add `shardingsphere-db-kind` for `Quarkus`?

I am curious which scenario people would like to choose `Quarkus-dataSource`?
