### ISSUE TITLE
Some DistSQL parsers report errors

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#12616]
Some DistSQL parsers report errors, but do not affect execution.

The following will show the statements I encountered and is not meant to represent the entire statement：

`show variable *` like ：show variable cached_connections

![image](https://user-images.githubusercontent.com/76552510/134294627-66ddfff2-9043-4539-894a-0c2eca202b6f.png)

`preview *`：

![image](https://user-images.githubusercontent.com/76552510/134294840-08394d8c-3eb3-4b3d-b73a-5f6e86481b13.png)

**Comment by RaigorJiang** [comment]
Hi @JiekerTime 
Thank you for your feedback.
Because the parsing process of DistSQL uses exception to control the flow, we see these outputs are ‘normal’, this is not a ‘BUG’. 
We will try to block these information, thank you.

**Comment by JiekerTime** [comment]
> Hi @JiekerTime
> Thank you for your feedback.
> Because the parsing process of DistSQL uses exception to control the flow, we see these outputs are ‘normal’, this is not a ‘BUG’.
> We will try to block these information, thank you.

Ok, I'll close this issue after this information is blocked!

**Comment by RaigorJiang** [comment]
Fixed in #12867.
