### ISSUE TITLE
Throw an exception when parsing sql

### ISSUE THREAD

**Issue by daodefengshang** [apache/shardingsphere#12624]
### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
send the sql to mysql
### Actual behavior
Throw an exception
Cause: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.simple.ParameterMarkerExpressionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.simple.LiteralExpressionSegment
### Reason analyze (If you can)
ShardingSphere-JDBC cannot correctly identify the parameters in the select statement
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
select ? as id

**Comment by strongduanmu** [comment]
Hi @daodefengshang, can you try the latest version? It has a better support for sql parse.

**Comment by tuichenchuxin** [comment]
@daodefengshang I had checked it on master branch, it's already supported.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it.
