### ISSUE TITLE
class DistSQLVisitor  lost package "autogen"

### ISSUE THREAD

**Issue by jingminy** [apache/shardingsphere#12631]
![image](https://user-images.githubusercontent.com/15995728/134365958-e5d34a03-32d2-4e76-b8ba-0677b8e5bc0c.png)

please fix it, thanks!

**Comment by yx9o** [comment]
@jingminy Hi, did you execute `install`? The files in the `autogen` package are generated after executing `install`.

**Comment by RaigorJiang** [comment]
Hi @jingminy 
If your problem is solved, can you close this issue?
