### ISSUE TITLE
Where to configure AutoTables' library sub-database strategy in version 5.0.0-beta？

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12641]
here is my config-sharding.yaml
![image](https://user-images.githubusercontent.com/45256940/134451647-034e5476-9bb9-44ea-85bb-817786133a13.png)
![image](https://user-images.githubusercontent.com/45256940/134451721-555e48e4-2e67-40ec-bbbe-1a6a9d5d7007.png)
I configured a default database strategy, but it is invalid for AutoTables
![image](https://user-images.githubusercontent.com/45256940/134451905-cbdb24d4-679b-429c-b5b2-65644e447912.png)
According to my configuration, this piece of data is expected to go to ds_1, but it is routed to ds_0

**Comment by RaigorJiang** [comment]
Hi @marker-wu 
If you want to control the sharding strategy yourself, you should use the `tables` configuration instead of `autoTables`.
Here is an [example](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-proxy-example/shardingsphere-proxy-memory-example/shardingsphere-proxy-memory-local-sharding-example/src/main/resources/conf/config-sharding.yaml) showing the different configurations of tables and autoTables.
For more information about `autoTable`, you can refer to this article:
https://mp.weixin.qq.com/s/fDYqW-yJIVpkcUDNT-gsuA

**Comment by RaigorJiang** [comment]
@marker-wu 
Has your problem been solved?

**Comment by marker-wu** [comment]
> @marker-wu
> Has your problem been solved?
I used the way of tables from the beginning, and it worked very well. But later I saw the Autotables method and tried to use it, and found this problem

**Comment by RaigorJiang** [comment]
> I used the way of tables from the beginning, and it worked very well. But later I saw the Autotables method and tried to use it, and found this problem

This is not a problem, they are different configuration ways, and you can't mix them arbitrarily.

**Comment by marker-wu** [comment]
> > I used the way of tables from the beginning, and it worked very well. But later I saw the Autotables method and tried to use it, and found this problem
> 
> This is not a problem, they are different configuration ways, and you can't mix them arbitrarily.

In Autotables mode, the sub-database strategy cannot be specified. Isn't this a problem?

**Comment by RaigorJiang** [comment]
> In Autotables mode, the sub-database strategy cannot be specified. Isn't this a problem?

Yes, because autoTable does not need to configure databaseStrategy.
I suggest you read the article I provided. Thank you.

**Comment by marker-wu** [comment]
> > In Autotables mode, the sub-database strategy cannot be specified. Isn't this a problem?
> 
> Yes, because autoTable does not need to configure databaseStrategy.
> I suggest you read the article I provided. Thank you.

Since it is an automatic sharding, why do you need to specify a table sharding strategy? Do not specify a database sharding strategy?
Is this semi-automatic？

**Comment by RaigorJiang** [comment]
@marker-wu 
Sorry, you made a mistake. AutoTable does not need to configure `databaseStrategy`, nor does it have `tableStrategy`, it uses `shardingStrategy`.
Please refer to the documentation.   
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/

**Comment by RaigorJiang** [comment]
Hi @marker-wu 
If your question is solved, we will close this issue.
