### ISSUE TITLE
When the FLUSH PRIVILEGES command is executed, an error is reported

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12649]
When the FLUSH PRIVILEGES command is executed, an error is reported：
![image](https://user-images.githubusercontent.com/45256940/134468457-4109880e-a269-4d02-8319-a16078508077.png)

**Comment by strongduanmu** [comment]
Hi @marker-wu, thank you for your feedback. @tuichenchuxin Can you check this problem.

**Comment by tuichenchuxin** [comment]
@strongduanmu @marker-wu ok, I'll investigate this issue.
