### ISSUE TITLE
How to verify that sharding-proxy supports XA distributed transactions？

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12652]
How to verify that sharding-proxy supports XA distributed transactions？

**Comment by strongduanmu** [comment]
@marker-wu For more detailed transaction information, you can refer [official doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/usage/transaction/).

**Comment by marker-wu** [comment]
> @marker-wu For more detailed transaction information, you can refer [official doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/usage/transaction/).

I read this article, he has no specific verification steps, I use the default transaction manager Atomikos, can you provide specific and feasible verification solutions？

**Comment by marker-wu** [comment]
When my transaction type is XA, I use the demo program to connect to the proxy to insert data into the database, and an error is reported:
![image](https://user-images.githubusercontent.com/45256940/134630140-1341b4fe-bb65-4c30-af9a-54746d8d83a3.png)
![image](https://user-images.githubusercontent.com/45256940/134630248-a6b56855-cf43-403d-b730-e84c2238925e.png)

When the transaction type is LOCAL, normal operation

**Comment by strongduanmu** [comment]
@marker-wu Can you provide your demo application and shardingsphere-proxy config? I need this information to reproduce exception.

**Comment by marker-wu** [comment]
> @marker-wu Can you provide your demo application and shardingsphere-proxy config? I need this information to reproduce exception.
my demo config:
![image](https://user-images.githubusercontent.com/45256940/134634228-71c6538c-a56c-4916-bd32-8d1479394da6.png)

my proxy config:
server.yaml:
![image](https://user-images.githubusercontent.com/45256940/134634375-fa753b47-c1b7-40f9-9291-099cbdf4a1f2.png)

**Comment by marker-wu** [comment]
> @marker-wu Can you provide your demo application and shardingsphere-proxy config? I need this information to reproduce exception.
Is there any progress?

**Comment by marker-wu** [comment]
hello ，Why there is no follow-up？

**Comment by jingshanglu** [comment]
@marker-wu，Do you mean run `xa start/end/commit/rollback` on shardingsphere-proxy?

**Comment by jingshanglu** [comment]
@marker-wu I see you use TiDB for store,  can you show the sql? I see the root exception is `you have an error in your SQL syntax`.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
