### ISSUE TITLE
Can sharding-proxy support creating a user with an empty password?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12650]
Can sharding-proxy support creating a user with an empty password?
![image](https://user-images.githubusercontent.com/45256940/134469452-1e171d79-8125-47e5-be68-bbb1a7772126.png)

**Comment by strongduanmu** [comment]
@marker-wu In the current implementation, a password is required.

**Comment by RaigorJiang** [comment]
Closed because there is no follow-up response.
