### ISSUE TITLE
Travis ci automatic cancellation causes a lot of x.

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#12665]
Hi community：

In the current travis-ci, when the last build has not been completed, and a new pr is merged into the master, the last build will be automatically cancelled. How about the way to convert the current travis-ci to github actions?

The following is an example of the reason for cancellation of CI:
```
This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#24066) for branch master came in while this job was waiting to be processed.
```

**Comment by strongduanmu** [comment]
@totalo Thank you for your feedback, @TeslaCN will track this issue.

**Comment by TeslaCN** [comment]
I've disabled `Auto cancel branch builds` in travis-ci.
![image](https://user-images.githubusercontent.com/20503072/134609730-e5863baa-c4d9-44a4-9edb-c978043f798c.png)
