### ISSUE TITLE
Question about the transaction of sharding-proxy in 5.0.0-beta

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12677]
When I use the demo program to connect to the sharding-proxy, my transaction type is LOCAL. My demo program inserted two pieces of data into the database and was routed to a different database. Finally, I rolled back the transaction and found that the data in the two databases were both Rolled back, why can the local transaction roll back the data of the two databases?
Isn't this in the category of distributed transactions?
![image](https://user-images.githubusercontent.com/45256940/134631539-cf71f4c0-3b1c-4604-b7c0-539c705a0794.png)

**Comment by TeslaCN** [comment]
The LOCAL transaction will commit or rollback all connections used in a transaction.

**Comment by marker-wu** [comment]
> The LOCAL transaction will commit or rollback all connections used in a transaction. Data may be inconsistent if any connections commit or rollback failed.

Do you mean that LOCAL transactions are also one of the supported distributed transactions?

**Comment by TeslaCN** [comment]
> Do you mean that LOCAL transaction is also one of the supported distributed transactions?

The LOCAL will try committing or rolling back all connections, it just acts on multiple data sources, I don't think it is distributed.

**Comment by marker-wu** [comment]
> > Do you mean that LOCAL transaction is also one of the supported distributed transactions?
> 
> The LOCAL will try committing or rolling back all connections, it just acts on multiple data sources, I don't think it is distributed.

The sub-database sub-table I understand is also a scenario in distributed transactions. LOCAL controls the commit or rollback of all connections in the entire transaction, but it cannot guarantee final consistency

According to what you mean, what is the application scenario of XA and BASE in sharding-proxy?

**Comment by strongduanmu** [comment]
@marker-wu Whether to use Local transaction is determined by your scenario. If you only perform table sharding or you can ensure that the tables of related businesses are in the same database, then using Local transactions can work. 

If these conditions cannot be guaranteed, then you need consider XA or BASE.

**Comment by marker-wu** [comment]
> @marker-wu Whether to use Local transaction is determined by your scenario. If you only perform table sharding or you can ensure that the tables of related businesses are in the same database, then using Local transactions can work.
> 
> If these conditions cannot be guaranteed, then you need consider XA or BASE.

OK

**Comment by strongduanmu** [comment]
@marker-wu Can you close this issue?
