### ISSUE TITLE
Does it support distributed transactions across multiple sharding-proxy?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12680]
Does it support distributed transactions across multiple sharding-proxy?

**Comment by strongduanmu** [comment]
@marker-wu Why do you need transaction that across multiple proxy? Proxy can manage multiple real databases based on the logical databases.

**Comment by marker-wu** [comment]
> @marker-wu Why do you need transaction that across multiple proxy? Proxy can manage multiple real databases based on the logical databases.
Our architecture is micro-service-oriented, each micro-service corresponds to a database, and then each database is divided into databases and tables. If all the information is allocated in a sharding-proxy, I am afraid that there will be a single point of failure.

**Comment by terrymanu** [comment]
If across multiple shardingsphere-proxy, the shardingsphere-proxy is act as RM. So, it depends on your application distributed transaction solution.
