### ISSUE TITLE
Delete redundant ShardingGeneratedKeyInsertValueParameterRewriterTest

### ISSUE THREAD

**Issue by fwhdzh** [apache/shardingsphere#12699]
I found ShardingGeneratedKeyInsertValueParameterRewriterTest exists both in "shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite/parameter" and "shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite".

This is because of my carelessness and I want to delete the one in "shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/rewrite" in the issue.

**Comment by strongduanmu** [comment]
Fixed by #12700.
