### ISSUE TITLE
master branch native table privilege check exception

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#12717]
### Which version of ShardingSphere did you use?
master/5.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
native table privilege check should work without any exception 

### Actual behavior
got exception java.sql.SQLException: Column 'user' not found.

### Reason analyze (If you can)
TABLE_PRIVILEGE_SQL should be "SELECT Db, Table_name, Table_priv, user, host FROM mysql.tables_priv WHERE (user, host) in (%s)", i.e. user and host must be included in selected column.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
grant any table privilege on user in server.yaml will trigger this bug

### Example codes for reproduce this issue (such as a github link).
none

**Comment by RaigorJiang** [comment]
Hi @roodkcab 
Could you show some exception log?

**Comment by RaigorJiang** [comment]
@roodkcab 
Thank you for your feedback. I ran some tests and the results are as follows:
```sql
mysql> grant select, insert, update, delete on sharding_db.t_order to user12717@%;
ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'

mysql> grant select, insert, update, delete on sharding_db.t_order to user12717;
ERROR 1146 (42S02): Table 'sharding_db.t_order' doesn't exist

mysql> grant select, insert, update, delete on t_order to user12717;
Query OK, 0 rows affected (0.04 sec)
```

There are indeed problems that need to be improved.

**Comment by lanchengx** [comment]
@RaigorJiang I can try to investigate.

**Comment by RaigorJiang** [comment]
> @RaigorJiang I can try to investigate.

@lanchengx Thank you.

**Comment by RaigorJiang** [comment]
For #12752 and #13911, 
`Native` authority provider will be removed later, I just close this issue.
Thank you all!
