### ISSUE TITLE
The default authority type in the configuration file and the code is inconsistent

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#12725]
In `DefaultAuthorityRuleConfigurationBuilder`, `ALL_PRIVILEGES_PERMITTED` has been used as the default type, but the configuration file and document are still `NATIVE`

![image](https://user-images.githubusercontent.com/52209337/134796365-70d03de0-dddc-473f-ad8d-7617f759f730.png)
![image](https://user-images.githubusercontent.com/52209337/134796378-22b0ac1f-a250-4b6e-9fdd-89572cb2e1ab.png)
![image](https://user-images.githubusercontent.com/52209337/134796458-9c58cf2e-5176-4688-bece-7bacc5f80e96.png)

**Comment by RaigorJiang** [comment]
Hi @tristaZero 
Please have a look, I also think that the default type should be consistent with the type of `DefaultAuthorityRuleConfigurationBuilder`, using `ALL_PRIVILEGES_PERMITTED`, can we change it like this?
