### ISSUE TITLE
parse sql error

### ISSUE THREAD

**Issue by 5661954** [apache/shardingsphere#12728]
## Bug Report

the  version of ShardingSphere 4.1.1
ShardingSphere-JDBC
parse sql error,  run sql in mysql console is right ,but use mybatis, there throw exception like next:
'''
### Error querying database.  Cause: java.lang.ClassCastException: class 
org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment cannot be cast to class org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment (org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment and org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment are in unnamed module of loader 'app')
### SQL: select           id, asset_ins_id, product_ins_id,  create_time, update_time         from relation            where (product_ins_id,asset_ins_id) in        (  (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) , (?,?) )
'''

**Comment by terrymanu** [comment]
The version is pretty old, cloud you test `master` branch again?

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this sql parse on master branch?

**Comment by tuichenchuxin** [comment]
@strongduanmu  ok, I'll check later.

**Comment by tuichenchuxin** [comment]
@5661954 I checked this sql in master, it is supported now.

**Comment by strongduanmu** [comment]
This sql has been supported in master branch, you can try the latest version `5.0.0-beta`.

**Comment by liangxianjin** [comment]
> @5661954 I checked this sql in master, it is supported now.

Hi, Are you using 5.0.0? I'm using 4.1.1. I have the same problem. I think I can get it to 4.1.1

**Comment by strongduanmu** [comment]
> > @5661954 I checked this sql in master, it is supported now.
> 
> Hi, Are you using 5.0.0? I'm using 4.1.1. I have the same problem. I think I can get it to 4.1.1

Now you can try 5.5.1 version, if this sql still parse error, you can submit a new issue.

**Comment by liangxianjin** [comment]
> beta

Hello, excuse me, we are currently using SHARDINGJDBC 4.1.1, the business must implement select * from table WHERE (object, ATTR) IN (? , ?) , (? , ?)
However, sharding JDBC is not currently supported in 4.1.1. Currently have not seen the high version 5.0.0 source implementation, production 4.1.1 may not be able to upgrade the high version, I can high version of the existing extensions, to move it to 4.1.1 use

**Comment by liangxianjin** [comment]
> > > @5661954 I checked this sql in master, it is supported now.
> > 
> > 
> > Hi, Are you using 5.0.0? I'm using 4.1.1. I have the same problem. I think I can get it to 4.1.1
> 
> Now you can try 5.5.1 version, if this sql still parse error, you can submit a new issue.

Convenient to say the next 5.0.0 source code, that commit commit to solve this problem, I carefully study the following, well, I will strongly support our open source project⭐

**Comment by liangxianjin** [comment]
> You can find 5.0.0 source code here - https://github.com/apache/shardingsphere/tags

Thank you very much！

**Comment by liangxianjin** [comment]
> You can find 5.0.0 source code here - https://github.com/apache/shardingsphere/tags
I moved code 5.0.0 to 4.1.1 to try the problem has been solved, thanks again!
