### ISSUE TITLE
Redesign the project structure in `readme` file inside `shardingsphere/examples` directory

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#12743]
## Feature Request

According to PR(#12736 ) the module location of `shardingsphere-parser-example` has been changed.
Hence it should be updated in the project structure.
Link to readme file - https://github.com/apache/shardingsphere/blob/master/examples/README.md

Please answer these questions before submitting your issue. Thanks!

**Comment by yx9o** [comment]
I'll do it.

**Comment by RaigorJiang** [comment]
@yx9o Welcome.
