### ISSUE TITLE
shardingsphere-proxy-5.0.0-beta  实现数据库迁移，只能使用默认的 ds_0, ds_1，而且密码还只能是123456？可以自己配置这些吗？我配置了没生效

### ISSUE THREAD

**Issue by thombgithub** [apache/shardingsphere#12745]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
For english only, other language will not accept.
