### ISSUE TITLE
Getting the table structure information when the shardingsphere starts causes the program to get stuck

### ISSUE THREAD

**Issue by Comven** [apache/shardingsphere#12742]
shardingsphere-jdbc-core-spring-boot-starter-5.0.0-beta

The historical database contains tens of thousands of tables，Because the order table is divided by day，When the program starts, the component of shardingsphere auto executes the following SQL like
```
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CLOLUMN_KEY, EXTRA, COLLATION_NAME FROM information_schema.columns WHERE TABLE_SCHEMA='hist_db' AND TABLE_NAME NOT IN('order_20210101','order_20210102',......
```
and SQL
```
SELECT FULL TABLES FROM 'hist_db' LIKE 'xxxx_yyy_20190610'
```
It takes a lot of time to execute these SQL to initialize the components of shardingsphere after the program starts. The greater the number of sub tables, the longer the time it takes to get stuck.

Is there any way to skip this step or speed it up ?

**Comment by Comven** [comment]
Has this problem been optimized？

**Comment by RaigorJiang** [comment]
Hi @Comven 
For a sharding table, only one of the nodes will be scanned when loading metadata.
At the same time, in the last few versions, the performance of metadata loading has also been improved, it is recommended that you try the latest version.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
