### ISSUE TITLE
[DistSQL] Password recognition error when adding resources. 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#12758]
### Which version of ShardingSphere did you use?
ShardingSphere-Proxy : master branch

### Actual behavior
My password for mysql user is `admin@2021`, so I input SQL:
```sql
ADD RESOURCE resource_0 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=db0,
    USER=root,
    PASSWORD=admin@2021
);
```
But the password received by Proxy is just `admin`, this cause validate failed.

### Reason analyze (If you can)
ANTLR definition is flawed.

**Comment by lanchengx** [comment]
@RaigorJiang please assign to me
