### ISSUE TITLE
Consider renaming ConfigurationPropertyKey#EXECUTOR_SIZE

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#12770]
## Discussion

The `executor-size` is too simple to understand in `server.yaml`, consider renaming it.

https://github.com/apache/shardingsphere/blob/64cfdc01e964e45b1711ddca57c06ea2979b7e0a/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml#L60

**Comment by TeslaCN** [comment]
Since this property is used in `org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine` and referenced by the following classes:
* `org.apache.shardingsphere.mode.metadata.MetaDataContextsBuilder`
* `org.apache.shardingsphere.proxy.backend.context.BackendExecutorContext`

I've come out with some names: 
* `kernel-executor-size`
* `infra-executor-size`
* `executor-engine-thread-pool-size`
* `sql-executor-size`

**Comment by tristaZero** [comment]
+1 for `kernel-executor-size`
