### ISSUE TITLE
how to use xa transaction in shardingsphere-proxy

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#12771]
## Question

I tried to use xa transaction on shardingsphere-proxy but got something wrong.

the first problem is mysql does not support xa (start|begin) 'xxxxx' (join|resume), I made a little change here
![image](https://user-images.githubusercontent.com/1700820/134866170-1b82ca54-2d77-4ae7-b283-4962601c4ac0.png)

then I set autocommit = 0 before use xa start 'xxxxx', but according to code here, it seems shardingsphere is trying to execute xa start on every schema using a broadcastdatabasebackendhandler 
![image](https://user-images.githubusercontent.com/1700820/134866387-6e144726-8014-4561-87d7-8d637461c497.png)
which lead to 
![image](https://user-images.githubusercontent.com/1700820/134866989-09bae555-dba1-4ec8-8074-6db709bfa5c4.png)

the test sql is quite simple

```
set autocommit = 0;
xa start '1298390128390218903182903801923890218390';
xa end '1298390128390218903182903801923890218390';
xa prepare '1298390128390218903182903801923890218390';
xa commit '1298390128390218903182903801923890218390';
```

it seems I have to configure a xa datasource, but I can't find any document or examples for such configuration, please help, THX!

**Comment by roodkcab** [comment]
I think we have to handle xa stmt just like normal tcl stmt, so that we could use shardingSphereTransactionManager to handle such command.
![image](https://user-images.githubusercontent.com/1700820/134870307-091508e0-813f-41b5-b99a-4ab454d298e8.png)

**Comment by RaigorJiang** [comment]
Can these examples help you?  
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-sample/shardingsphere-proxy-sample/shardingsphere-proxy-memory-example

**Comment by RaigorJiang** [comment]
SQL statement does not need to declare XA

**Comment by zhfeng** [comment]
@roodkcab it needs to use a mysql XA DataSource class such as ```com.mysql.cj.jdbc.MysqlXADataSource```. All of the transaction operations should be handled by mysql driver. So in your application, you just need to
```java
TransactionManager tm;

tm.begin();
try {
    do_some_insert_sql();
    other_process(); // just like send a message to AMQ
    tm.commit();
} catch (Exception e) {
    tm.rollback();
}
```

Or if you use some framework, such as Spring, Spring-Boot or Wildfly, the container will manage the tarnsaction process. You just need to 
```java
@Transactional
void process() {
    do_some_insert_sql();
    other_process();
}
```

In term of the sharding-proxy, @RaigorJiang I belive that it should bypass the xa related commands and route to the backend servers ? Is there any test for this XA scenario ?

**Comment by RaigorJiang** [comment]
Shardingsphere integrates [TransactionManager](https://shardingsphere.apache.org/document/current/cn/dev-manual/transaction/), which can be used by both JDBC and Proxy. Users only need to configure the transaction manager type, and then submit ordinary SQL statements.

**Comment by zhfeng** [comment]
Well, I understand that this TansactionManager is used by Shardingsphere internal to commit to the backend database servers especially in the case of splitting a origin insert sql statment into two or more statments and routing to the different databases, which should be running with XA or SEAT transaction mode to make the data consistency. @RaigorJiang , is it right ?

In @roodkcab scenario, it seems that he wants to use a XA transaction in the application and connect to the shardingsphere-proxy. So @roodkcab can you describe your question in more detail ? e.g. what is your application want to do in XA transaction ?

**Comment by RaigorJiang** [comment]
> Well, I understand that this TansactionManager is used by Shardingsphere internal to commit to the backend database servers especially in the case of splitting a origin insert sql statment into two or more statments and routing to the different databases, which should be running with XA or SEAT transaction mode to make the data consistency. @RaigorJiang , is it right ?
> 
> In @roodkcab scenario, it seems that he wants to use a XA transaction in the application and connect to the shardingsphere-proxy. So @roodkcab can you describe your question in more detail ? e.g. what is your application want to do in XA transaction ?

Yes, it is.

**Comment by roodkcab** [comment]
> Well, I understand that this TansactionManager is used by Shardingsphere internal to commit to the backend database servers especially in the case of splitting a origin insert sql statment into two or more statments and routing to the different databases, which should be running with XA or SEAT transaction mode to make the data consistency. @RaigorJiang , is it right ?
> 
> In @roodkcab scenario, it seems that he wants to use a XA transaction in the application and connect to the shardingsphere-proxy. So @roodkcab can you describe your question in more detail ? e.g. what is your application want to do in XA transaction ?

right, I have to use XA statements without jdbc. It's actually some PHP scripts connect to shardingsphere-proxy with PDO extension, using XA statements to get distribution transaction done.

I've solved this problem by using a SchemaAssignedDatabaseHandler in TransactionBackendHandlerFactory when tclStatement is  an instance of MySQLXAStatement.

![image](https://user-images.githubusercontent.com/1700820/135231739-fd5e3f65-7268-4fe4-97d6-a8636ad9be6c.png)

**Comment by zhfeng** [comment]
It's nice to hear that you resolved this issue. And did you make these changes in shardingsphere-proxy ? and do you mind contributing them back to the upstream community ? I'm looking forward your contribution.

**Comment by roodkcab** [comment]
I think I have to make more test before making a pull request. I've found some different behavior between using proxy and raw mysql server.

**Comment by roodkcab** [comment]
I've successfully run full xa transaction in proxy, and here's what I've done

1、add XA statement support，including
'''
xa start/begin 'xxxx';
xa end 'xxxx';
xa prepare 'xxxx';
xa commit 'xxxx';
xa rollback 'xxxx';
''' 

2、 get  distribution transaction  done by using shardingsphere transaction manager, the default one is Atomikos. 
when sending '''xa start''' statement to proxy, we call begin function in JTA.
shardingsphere will trigger a '''xa start''' on backend database on any other SQL got received. 
for '''xa end''' and '''xa prepare''' statement, both of them could be simply ignored.
for '''xa commit''' and '''xa rollback''' we call commit and rollback respectively in JTA,

**Comment by roodkcab** [comment]
> > Well, I understand that this TansactionManager is used by Shardingsphere internal to commit to the backend database servers especially in the case of splitting a origin insert sql statment into two or more statments and routing to the different databases, which should be running with XA or SEAT transaction mode to make the data consistency. @RaigorJiang , is it right ?
> > In @roodkcab scenario, it seems that he wants to use a XA transaction in the application and connect to the shardingsphere-proxy. So @roodkcab can you describe your question in more detail ? e.g. what is your application want to do in XA transaction ?
> 
> right, I have to use XA statements without jdbc. It's actually some PHP scripts connect to shardingsphere-proxy with PDO extension, using XA statements to get distribution transaction done.
> 
> I've solved this problem by using a SchemaAssignedDatabaseHandler in TransactionBackendHandlerFactory when tclStatement is an instance of MySQLXAStatement.
> 
> ![image](https://user-images.githubusercontent.com/1700820/135231739-fd5e3f65-7268-4fe4-97d6-a8636ad9be6c.png)

this is a wrong implementation, and there's no transaction at all on backend database.

**Comment by zhfeng** [comment]
@roodkcab it's great and can you describe your xa transaction scenario in details ?

Is there any problem if sharding-proxy will rewrite the SQL into different backend databses (sharding database) after ```xa_start``` ?

Why ```xa_end``` and ```xa_prepare``` could be ignored ? I think it is important for 2pc protocol.

**Comment by zhfeng** [comment]
OK, I'm looking forward to your contribution on xa support ! Feel free to open a discuss on github.

**Comment by roodkcab** [comment]
related issue #12652 #9611

**Comment by zhfeng** [comment]
Well, there is a long disscusion with this issue and two related PR #13187 and #13362 . I'd like to say

- It is a lack of documents to understand the sharding sphere transaction desgin, does anybody point out if I miss it ?
- There is a confusion between ```TransactionType.XA``` and using XA scenario with ```sharding-proxy```.
- It seem that we change the semantics of some transaction statments, such as ```set autoCommit```.

And  I think it is very important of the transactional functions of sharding sphere especially in production system which is concerned about the data consistency.

It should have a good chance to talk about this issue in the meetup but unfortunately we missed it due to COVID-19. Anyway, I think it could be helpful to have this disscusion face to face and it might be much clearer understand. Although this issue could be a very hard and tough, I believe that we can resolve it finally because **WE ARE GREAT TEAM**.

Feel free to schedul a online meeting for disscussion if you think this is necessary. @roodkcab @RaigorJiang @TeslaCN @tristaZero @jingshanglu

**Comment by RaigorJiang** [comment]
Good advice, looking forward to your voice.

**Comment by jingshanglu** [comment]
> Well, there is a long disscusion with this issue and two related PR #13187 and #13362 . I'd like to say
> 
> * It is a lack of documents to understand the sharding sphere transaction desgin, does anybody point out if I miss it ?
> * There is a confusion between `TransactionType.XA` and using XA scenario with `sharding-proxy`.
> * It seem that we change the semantics of some transaction statments, such as `set autoCommit`.
> 
> And I think it is very important of the transactional functions of sharding sphere especially in production system which is concerned about the data consistency.
> 
> It should have a good chance to talk about this issue in the meetup but unfortunately we missed it due to COVID-19. Anyway, I think it could be helpful to have this disscusion face to face and it might be much clearer understand. Although this issue could be a very hard and tough, I believe that we can resolve it finally because **WE ARE GREAT TEAM**.
> 
> Feel free to schedul a online meeting for disscussion if you think this is necessary. @roodkcab @RaigorJiang @TeslaCN @tristaZero @jingshanglu

good idea，we can also disscussion on https://community.sphere-ex.com/t/topic/367, We can temporarily specify a time, how about this weekend？

**Comment by zhfeng** [comment]
@jingshanglu sure, please send me the invitation (maybe a wechat meeting) and I prefer to the time at night :) 

I think we should share the link of the meeting on public if possible and hope the other people  who are concern with this topic could  join the disscusion.

**Comment by roodkcab** [comment]
anytime is ok for me

**Comment by jingshanglu** [comment]
> > Well, there is a long disscusion with this issue and two related PR #13187 and #13362 . I'd like to say
> > 
> > * It is a lack of documents to understand the sharding sphere transaction desgin, does anybody point out if I miss it ?
> > * There is a confusion between `TransactionType.XA` and using XA scenario with `sharding-proxy`.
> > * It seem that we change the semantics of some transaction statments, such as `set autoCommit`.
> > 
> > And I think it is very important of the transactional functions of sharding sphere especially in production system which is concerned about the data consistency.
> > It should have a good chance to talk about this issue in the meetup but unfortunately we missed it due to COVID-19. Anyway, I think it could be helpful to have this disscusion face to face and it might be much clearer understand. Although this issue could be a very hard and tough, I believe that we can resolve it finally because **WE ARE GREAT TEAM**.
> > Feel free to schedul a online meeting for disscussion if you think this is necessary. @roodkcab @RaigorJiang @TeslaCN @tristaZero @jingshanglu
> 
> good idea，we can also disscussion on https://community.sphere-ex.com/t/topic/367, We can temporarily specify a time, how about this weekend？
Maybe we should define several topics and then determine the online meeting time. what topics shall we discuss?

**Comment by zhfeng** [comment]
yeah, I'd like to propasal the following

- With XA scenario in sharding-proxy, what should we support ? sharding-proxy needs to be the same behavior as a single XA resource ?
- Make sure about the difference between ```TransactionType.XA``` and ```XA Support```
- Review the current implementation of transation support in sharding-proxy
- How to test the XA scenarioes

feel free to share the ideas and maybe have a chinese version if you like.

**Comment by roodkcab** [comment]
>With XA scenario in sharding-proxy, what should we support ? sharding-proxy needs to be the same behavior as a single XA resource ?

@zhfeng do you mean we can support different type of backend connection in a XA transaction? for example, we can start a XA transaction in MySQL, together with another one in Postgres or Oracle and even a connection on MQ?

>Review the current implementation of transation support in sharding-proxy

definitely we should

>How to test the XA scenarioes

this is also a proposal I'd like to discuss. I don't think mock is a good choice for such scenario.

**Comment by jingshanglu** [comment]
On November 27th, I booked a tencentmeeting. We can prepare the agenda and then have some discussion.
url:https://meeting.tencent.com/dm/eYpab4935SQr

**Comment by zhfeng** [comment]
Thanks @jingshanglu and please share this link of meeting in public places. e.g. shardingsphere mailing-list, sphere-ex forum. I'm looking forward to meet with all of you. @roodkcab can you share with your usecase in php for XA ?

**Comment by roodkcab** [comment]
no problem, I'll create a gist for u later

**Comment by zhfeng** [comment]
@jingshanglu can you update with our discussion on the last meeting ? Thanks !

**Comment by jingshanglu** [comment]
After online discussion, the conclusion is as follows：

1. Does ShardingSphere provide branch transactions, eg: xa start/end/prepare/commit/recover
2. If we want to implement a complete solution,  we maybe need to manage the transaction log
3. Documents on transaction need to be perfected
4. Is there a LTS version plan

**Comment by zhfeng** [comment]
Thanks @jingshanglu and as the related action, the first step I proposal to **VOTE** on the sharding-sphere mailing list to make sure if we want to support ```XA``` transaction with sharding-proxy.

So @jingshanglu can you help to raise a **VOTE** on mailing list ?

**Comment by zhfeng** [comment]
Hi @jingshanglu https://github.com/apache/shardingsphere/issues/13656 maybe resolve this issue partly ?

**Comment by jingshanglu** [comment]
> Hi @jingshanglu #13656 maybe resolve this issue partly ?

Yeah, #13656 can partly resolve this issue.Now we can focus on `one datasource` and `encrypt`,proposal:
1. Create `XAhandler` to only hand `XA request`  
2. Add check for env, when use `encrypt` and have only one datasource, support for `XA` will effect.

Based on this proposal, @roodkcab is dealing with this issue.

**Comment by zhfeng** [comment]
Thanks a lot @jingshanglu and FYI, I create https://github.com/apache/shardingsphere/pull/14075 to fix some issues about Mysql XA parser, please review it and I think it could be helpful to ```XAHandler``` implementation.

And @roodkcab feel free to ping me if you get this proposal out of door and I'd like to work with you.

**Comment by roodkcab** [comment]
here's a [proposal](https://wonderfull.feishu.cn/docs/doccn4a1x4Rmx4pEADYbtkAeLGc) for this issue. as @zhfeng has pointed out: XA statements should be passed to backend database instead of wrapping it into JTA. Having discussion with @jingshanglu a litter bit more, we both agree to firstly focus on supporting XA statements on a single database, and throw error when multiple instance configured.

and I think @zhfeng 's pr https://github.com/apache/shardingsphere/pull/13362 has get most of job done, I think we only need to have more discussion on inXA and transactionType.MANUAL.

@zhfeng I've invite u to join shardingsphere slack channel, so that we can have a conversation online, or we can use any other im tools u like.

**Comment by zhfeng** [comment]
@roodkcab Great work - I reply you on the slack [channel](https://apacheshardingsphere.slack.com/archives/C026MLH7F34/p1639467945006300)

**Comment by roodkcab** [comment]
for anyone interested in this topic, we setup a shardingsphere slack channel #transaction and here's some discussion on [transactionStatus ](https://apacheshardingsphere.slack.com/archives/C02QMEQRKT8/p1639568920010200)
