### ISSUE TITLE
How to configure sharding rules for multiple schemas in sharding-proxy？

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12775]
How to configure sharding rules for multiple schemas in sharding-proxy？

**Comment by RaigorJiang** [comment]
@marker-wu 
Just put multiple config files in Proxy, like the [example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-proxy-example/shardingsphere-proxy-hint-example/src/main/resources).

**Comment by RaigorJiang** [comment]
@marker-wu
 If your question is solved, can you close the issue?

**Comment by RaigorJiang** [comment]
> Does sharding-proxy load all yaml files in the conf directory? There is no restriction on file name, right?

Yes, there is no limit. A normal file name is fine.

**Comment by RaigorJiang** [comment]
I think this question has been answered clearly, so close the issue.
