### ISSUE TITLE
SpringBoot2.1.3 + ShardingJDBC5.0 health check error.

### ISSUE THREAD

**Issue by wangwangwangBoy** [apache/shardingsphere#12774]
As the title ,SpringBoot 2.1.3 + ShardingJDBC5.0 can't register service with Eureka

I used SpringBoot2.1.3+ShardingJDBC4.0 before, and it runs normally. But when I changed to 5.0. I need to modify the version of guava, after modifying 29.0-jre. It was found that the registration service failed, but a single service can provide services to the outside world normally.

shch as :
![image](https://user-images.githubusercontent.com/46279672/134871172-7ff82957-e2de-4a68-b55b-4f1840f6bcca.png)

**Comment by RaigorJiang** [comment]
Sorry, ShardingSphere only has operations related to the data source. You need to investigate this issue based on the exception information.

**Comment by wangwangwangBoy** [comment]
> Sorry, ShardingSphere only has operations related to the data source. You need to investigate this issue based on the exception information.

Thanks, I will check my other configuration

**Comment by wangwangwangBoy** [comment]
> Sorry, ShardingSphere only has operations related to the data source. You need to investigate this issue based on the exception information.

Can you reopen this question again? I found something about the data source. When I use Sharding, the SpringCloud data source health check will fail.

**Comment by RaigorJiang** [comment]
@wangwangwangBoy Please provide some error logs.

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy Please provide some error logs.


This looks like it uses Sharding DataSource, but during the health check, the cachedDatabaseMetaData object is null
![image](https://user-images.githubusercontent.com/46279672/134898555-f4ddb553-4dc0-466d-a812-4ee1d308ec7c.png)
use sharding is null
![image](https://user-images.githubusercontent.com/46279672/134898601-2cb8cbe6-956f-490c-87d4-0c395c3df316.png)

**Comment by wangwangwangBoy** [comment]
Error logs
![image](https://user-images.githubusercontent.com/46279672/134901499-0f6537e7-91a9-4dff-8422-006d5a88d8d7.png)

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy Thank you.
> @strongduanmu Could you have a look?

I'd found some different things , when it's  JDBCDataBaseMetaData，it can be woekrd, but when ShardingSphereDataBaseMetaData , it will be wrong.
![image](https://user-images.githubusercontent.com/46279672/134910755-fcc87c8a-ad04-42f6-91ec-c6d4f4e139d2.png)

**Comment by strongduanmu** [comment]
@wangwangwangBoy Can you provide a demo application? I need to reproduce this exception.

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy Can you provide a demo application? I need to reproduce this exception.

That's our project code. It may take a while to make a demo. I will upload a demo later. I avoided this problem by canceling the security check, but found a new problem. When inserting data into a data table that is not configured with a table-sharing strategy, this error 'Cannot find strategy for generate keys.' occurred. After debugging, I found that the key generation strategy only has two tables I configured. How can I solve it?
![image](https://user-images.githubusercontent.com/46279672/135007370-21bc5a98-989c-4a84-81b5-8bfc3f603d81.png)

**Comment by wangwangwangBoy** [comment]
> > configured
> 
> @wangwangwangBoy `Cannot find strategy for generate keys.` is a known bug and has been fixed in the master branch. You can test it.

Haha, can you give me a compressed package of master's pom jar? The latest Sharding version used by our company is 4.1, and there is no master jar, just like the picture
![image](https://user-images.githubusercontent.com/46279672/135009901-a8bb611f-a46b-46c0-839a-4d61a6a96188.png)

**Comment by RaigorJiang** [comment]
The complete compressed package is large, and the version will be updated continuously. 
It is recommended that users build by themselves so that the latest version can be obtained at any time.
Here is a build guide:
https://github.com/apache/shardingsphere/blob/master/README_ZH.md

**Comment by wangwangwangBoy** [comment]
Thank you. Let me try.

**Comment by wangwangwangBoy** [comment]
> The complete compressed package is large, and the version will be updated continuously.
> It is recommended that users build by themselves so that the latest version can be obtained at any time.
> Here is a build guide:
> https://github.com/apache/shardingsphere/blob/master/README_ZH.md

**Comment by wangwangwangBoy** [comment]
> The complete compressed package is large, and the version will be updated continuously.
> It is recommended that users build by themselves so that the latest version can be obtained at any time.
> Here is a build guide:
> https://github.com/apache/shardingsphere/blob/master/README_ZH.md

I tried it and found that there are some exceptions. The READ_ME may not run on windows. It may be "mvn clean install -Prelease", and then an error occurs. Can I skip this step?
![image](https://user-images.githubusercontent.com/46279672/135032373-990956ea-5d2a-4768-ad3e-1abed3d91b54.png)

![image](https://user-images.githubusercontent.com/46279672/135032265-f37e3ae6-e9bd-4e08-8ddd-721ccc0cf516.png)

**Comment by RaigorJiang** [comment]
@wangwangwangBoy 
The CI includes a windows building, and I have a windows machine(win 10), they all work well. 
Maybe check the cause again, or try another machine?

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy
> The CI includes a windows building, and I have a windows machine(win 10), they all work well.
> Maybe check the cause again, or try another machine?T

Thank you, my machine is also win10, I'll try later

**Comment by strongduanmu** [comment]
@wangwangwangBoy It seems that some jar package is missing. Please check whether the dependent jar package is missing.

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy It seems that some jar package is missing. Please check whether the dependent jar package is missing.
There seems to be a lack of methods. I wonder if someone did not submit the complete code
![image](https://user-images.githubusercontent.com/46279672/135073380-d20fcf0e-9ee6-4bef-ab7e-6f812fd4e42c.png)

**Comment by strongduanmu** [comment]
@wangwangwangBoy Is this jar package packaged from the latest master branch? The latest code seems to have been different.

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy Is this jar package packaged from the latest master branch? The latest code seems to have been different.

I am extracting code 9.24. Found that there is indeed a problem. The two packages do not match. I really cannot compile this package. Unable to get the new version

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy Is this jar package packaged from the latest master branch? The latest code seems to have been different.

Do you have other channels to get the package?

**Comment by strongduanmu** [comment]
You can provide your demo application, and I will check this exception.

**Comment by wangwangwangBoy** [comment]
> You can provide your demo application, and I will check this exception.

Sorry, I can’t, that’s our company code

**Comment by wangwangwangBoy** [comment]
> You can provide your demo application, and I will check this exception.
[sharding-jdbc.zip](https://github.com/apache/shardingsphere/files/7248264/sharding-jdbc.zip)

**Comment by strongduanmu** [comment]
Thank you, I will check it.

**Comment by strongduanmu** [comment]
@wangwangwangBoy I ran the test program on my machine, and there were no exceptions except for the absence of the table.

![image](https://user-images.githubusercontent.com/10829171/135192501-a195e303-2eaf-41f8-9f40-8f26c35cfa37.png)

In addition, I also started `ShardingJdbcApplication`, but no health check error occurred.

![image](https://user-images.githubusercontent.com/10829171/135192641-bce8c2a0-8490-40d6-ad3a-3ab31c4a435e.png)

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy I ran the test program on my machine, and there were no exceptions except for the absence of the table.
> 
> ![image](https://user-images.githubusercontent.com/10829171/135192501-a195e303-2eaf-41f8-9f40-8f26c35cfa37.png)
> 
> In addition, I also started `ShardingJdbcApplication`, but no health check error occurred.
> 
> ![image](https://user-images.githubusercontent.com/10829171/135192641-bce8c2a0-8490-40d6-ad3a-3ab31c4a435e.png)

yead. It means that there is a problem with my jar package. Can you provide a package compiled by maven that is available locally? I can't compile branch master.

**Comment by strongduanmu** [comment]
You can try this jar. [apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz](https://github.com/apache/shardingsphere/files/7248481/apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz)

**Comment by wangwangwangBoy** [comment]
> You can try this jar. [apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz](https://github.com/apache/shardingsphere/files/7248481/apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz)

I'll try it ,thank you

**Comment by wangwangwangBoy** [comment]
> You can try this jar. [apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz](https://github.com/apache/shardingsphere/files/7248481/apache-shardingsphere-5.0.0-RC1-SNAPSHOT-shardingsphere-jdbc-bin.tar.gz)

After replacing the Jar, my problem was solved, thank you

**Comment by strongduanmu** [comment]
@wangwangwangBoy Can this issue be closed?

**Comment by wangwangwangBoy** [comment]
sure, than you again

**Comment by strongduanmu** [comment]
You are welcome.
