### ISSUE TITLE
The sharding-proxy of the latest master branch cannot be found in the RuntimeStatus of sharding-ui

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12778]
The sharding-proxy of the latest master branch cannot be found in the RuntimeStatus of sharding-ui
![image](https://user-images.githubusercontent.com/45256940/134887065-47d3afd3-8fcf-4b5d-a47b-88e9ebc9c421.png)

The sharding-proxy 5.0.0-beta version in sharding-ui can be found

**Comment by menghaoranss** [comment]
refer to #12391
