### ISSUE TITLE
Does "sharding-proxy" support the "load data infile" syntax of "mysql"?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12789]
Version:5.0.0-RC1

``` sql
mysql> load data low_priority infile "/root/a.sql" into table t_frag;
ERROR 1999 (C1999): Unknown exception: [Can not find visitor rule: `LoadStatementContext`]
```

**Comment by tristaZero** [comment]
Sorry, currently, it doesn't work. Hi I saw your questions on github many times. Do you want to use this project on your production env？

**Comment by CrackerSuperior** [comment]
> Sorry, currently, it doesn't work. Hi I saw your questions on github many times. Do you want to use this project on your production env？

We are verifying the availability of "sharding-proxy", and if it is suitable for our business, we will consider using it. Or make a slight modification to meet our business needs

**Comment by RaigorJiang** [comment]
Proxy can now support the `source` command, can it meet the needs?

**Comment by CrackerSuperior** [comment]
> Proxy can now support the `source` command, can it meet the needs?

Yes, I just tested whether it is compatible with the developer volume

**Comment by CrackerSuperior** [comment]
> Proxy can now support the `source` command, can it meet the needs?

Well, we are testing and hope it meets the demand.

**Comment by RaigorJiang** [comment]
Hi @CrackerSuperior 
Can we close this issue?
