### ISSUE TITLE
[Sharding-jdbc master]No response when querying using Sharding-jdbc.

### ISSUE THREAD

**Issue by wangwangwangBoy** [apache/shardingsphere#12819]
[Sharding-jdbc + Druid] Sharding-jdbc is used in the project to split the table. When querying a logical table with 20 sub-tables, there is no response.
I don't know what's wrong, can someone help me?
Attached is my jstack information.
[1222.txt](https://github.com/apache/shardingsphere/files/7250572/1222.txt)

![image](https://user-images.githubusercontent.com/46279672/135240609-ab33767c-52ab-4b1e-bb90-02b911408b50.png)

**Comment by strongduanmu** [comment]
@wangwangwangBoy What version are you using?

**Comment by wangwangwangBoy** [comment]
attachment is our  config:



> @wangwangwangBoy What version are you using?

The latest branch of'master'. The code pulled last night

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy What version are you using?

![image](https://user-images.githubusercontent.com/46279672/135242501-d5370046-cf07-4b02-8134-fc0ca96e297b.png)
This is also the case for those without sub-tables, version 4.0 is good

**Comment by strongduanmu** [comment]
@wangwangwangBoy How can I reproduce this problem?

**Comment by wangwangwangBoy** [comment]
> How can I reproduce this problem?

I have no idea, i'm tired, Can't see the problem with jstack?  or you may remote my machine?

**Comment by strongduanmu** [comment]
@wangwangwangBoy It seems to be related to the connection. Check if there are enough connection resources?

**Comment by wangwangwangBoy** [comment]
> @wangwangwangBoy It seems to be related to the connection. Check if there are enough connection resources?



> @wangwangwangBoy It seems to be related to the connection. Check if there are enough connection resources?
I know the problem. I configured a property and it became like this
![image](https://user-images.githubusercontent.com/46279672/135251021-de7c289b-a87e-49fd-80bf-c7aaf4a7dad3.png)

**Comment by strongduanmu** [comment]
This issue is closed because the problem has been solved.
