### ISSUE TITLE
Support not nest subquery on encrypt rewrite

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#12825]
@tristaZero  @strongduanmu 
Support subquery(not nested) on encrypt rewrite, the following sqls was tested (on mysql) ok,  more sqls are welcome to leave a message.

subquery on projection:

logicSQL:
SELECT u.mobile, u.username, u.id_no, (select o.card_no from `order` o where o.card_no=u.id_no) card_no FROM `user` u, `bankcard` c where u.id_no =c.card_no and u.mobile=? and u.id=1

actualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no, (select o.card_no_cipher from `order` o where o.card_no_hash=u.id_no_hash) card_no FROM `user` u, `bankcard` c where u.id_no_hash =c.card_no and u.mobile_hash=? and u.id=1

subquery on tablesegment:

LogicSQL:
SELECT u.mobile, u.username, u.id_no, o.card_no FROM (select card_no from `order`) o, user `u`, bankcard c where o.card_no=u.id_no and o.card_no=c.card_no and u.mobile=? and o.card_no=? and u.id=1

ActualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no, o.card_no_cipher AS card_no FROM (select card_no_cipher, card_no_hash from `order`) o, user `u`, bankcard c where o.card_no_hash=u.id_no_hash and o.card_no_hash=c.card_no and u.mobile_hash=? and o.card_no_hash=? and u.id=1

subquery on expression:

LogicSQL:
SELECT u.mobile, u.username, u.id_no FROM user `u`, bankcard c where u.id_no=(select card_no from `order` where card_no=?) and u.mobile=? and u.id=1

ActualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no FROM user `u`, bankcard c where u.id_no_hash=(select card_no_hash from `order` where card_no_hash=?) and u.mobile_hash=? and u.id=1

LogicSQL:
SELECT u.mobile, u.username, u.id_no FROM user `u`, bankcard c where u.id_no in (select card_no from `order` where card_no=?) and u.mobile=? and u.id=1

ActualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no FROM user `u`, bankcard c where u.id_no_hash in (select card_no_hash from `order` where card_no_hash=?) and u.mobile_hash=? and u.id=1

LogicSQL:
SELECT u.mobile, u.username, u.id_no FROM user `u`, bankcard c where (select card_no from `order` where card_no=?)=u.id_no and u.mobile=? and u.id=1

ActualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no FROM user `u`, bankcard c where (select card_no_hash from `order` where card_no_hash=?)=u.id_no_hash and u.mobile_hash=? and u.id=1

LogicSQL:
SELECT u.mobile, u.username, u.id_no FROM user `u`, bankcard c where (select card_no from `order` where card_no=?)=(select id_no from `user` where id_no=?) and u.mobile=? and u.id=1

ActualSQL:
SELECT u.mobile_cipher AS mobile, u.username, u.id_no_cipher AS id_no FROM user `u`, bankcard c where (select card_no_hash from `order` where card_no_hash=?)=(select id_no_hash from `user` where id_no_hash=?) and u.mobile_hash=? and u.id=1

**Comment by cheese8** [comment]
I would try to fix and pr it, please assign it to me, thanks. @strongduanmu

**Comment by strongduanmu** [comment]
@cheese8 Thank you for your feedback, I have assigned this issue to you.

**Comment by cheese8** [comment]
Plans to split into below sub-PRs to submit:
- [ ] Support not nested subquery (from Projections, TableSegment and Expression) on SelectStatement
- [ ] Support not nested subquery (from Projections, TableSegment and Expression) on UpdateStatement
- [ ] Support not nested subquery (from Projections, TableSegment and Expression) on DeleteStatement
