### ISSUE TITLE
Unify sql-case-id name pattern in SQL parser test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12830]
Currently, `sql-case-ids` are specified in both camel case and snake case.

It is better to use snake-case. Please unify the sql-case-id in xml test cases.

**Comment by ThanoshanMV** [comment]
I'll try to do it.

**Comment by terrymanu** [comment]
@ThanoshanMV Welcome, I just assign it to you.

**Comment by ThanoshanMV** [comment]
Distributed SQL case ids are in spinal-case. Should we need to change them into snake-case or spinal-case is the recommended one?
