### ISSUE TITLE
Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]

### ISSUE THREAD

**Issue by WswSummer15** [apache/shardingsphere#12869]
(MacOS IDEA)Program startup error：
Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthContributorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributorRegistry]: Factory method 'healthContributorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthContributorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Data sources cannot be empty.

springboot + shardingsphere + HikariDataSource 
<java.version>1.8</java.version>
<mysql.version>8.0.18</mysql.version>
<spring.boot.version>2.2.2.RELEASE</spring.boot.version>
<sharding-jdbc.version>4.0.0-RC1</sharding-jdbc.version>

config.yaml here:
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: 
        username: 
        password: 
        hikari:
          minimum-idle: 5
          max-lifetime: 1800000
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 30000
          pool-name: DatebookHikariCP
          connection-timeout: 30000
    sharding:
      tables:
        task:
          actual-data-nodes: ds0.task_$->{2020..2021}
          table-strategy:
            standard:
              sharding-column: create_date
              precise-algorithm-class-name: 
              range-algorithm-class-name:
          key-generator:
            column: task_id
            type: SNOWFLAKE
      defaultDataSourceName: ds0
    props:
      sql:
        show: true

![image](https://user-images.githubusercontent.com/34562805/135600632-394c4dd0-f1f0-4bc5-ac0b-95ea66e4e899.png)

**Comment by terrymanu** [comment]
Please read the matched document first

**Comment by taojintianxia** [comment]
you use sharding-jdbc 4.0.0 RC1 ?

**Comment by WswSummer15** [comment]
> you use sharding-jdbc 4.0.0 RC1 ?

yes

**Comment by WswSummer15** [comment]
> you use sharding-jdbc 4.0.0 RC1 ?

Same configuration file, Windows good, MAC error

**Comment by WswSummer15** [comment]
> Please read the matched document first

Without reading the official document, I will ask here？

**Comment by agoodcoolman** [comment]
the same question,
use sharding-jdbc-5.0.0  

this is my ymal config

`schemaName: sharding_db
mode:
  type: memory
dataSources:
  ds0:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: 
    jdbc-url: 
    username: 
    password: 
  ds1:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: 
    username: 
    password: 
rules:
  tables:
    data_door_info_all:
      actual-data-nodes: ds${[0,1]}.data_door_info_all_$->{[0,1,2,3]}
      databaseStrategy:
        standard:
          sharding-column: id
          shardingAlgorithmName: hash_mode
      table-strategy:
        standard:
          sharding-column: idcard
          sharding-algorithm-name: hash_mode
  defaultTableStrategy:
    none:
  sharding-algorithms:
    hash_mod:
      type: MOD
      props:
        sharding-count: 3

keyGenerators:
  snowflake:
    type: SNOWFLAKE
    props:
      worker-id: 123`

**Comment by terrymanu** [comment]
The version 4.x is out of service. For version 5.x, it is better to create a new issue, we just separate between 4.x and 5.x.
