### ISSUE TITLE
Add test cases for ShardingSphereDataSourceFactory and YamlShardingSphereDataSourceFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#12872]
- [ ] Add test cases for ShardingSphereDataSourceFactory
- [ ] Add test cases for YamlShardingSphereDataSourceFactory

**Comment by zhujunxxxxx** [comment]
I'd like do it.

**Comment by menghaoranss** [comment]
@tulikavijay I just assign this issue to you, look forward to your pull request.

**Comment by terrymanu** [comment]
There are no progress for long time, I just cancel assign to you and make the issue open to pick up.
