### ISSUE TITLE
Checksum can be generated automatically

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#12902]
### Describe the feature you would like.

Introduce `checksum-maven-plugin` can save the following step.

![image](https://user-images.githubusercontent.com/20503072/135871541-defb8113-b475-4f11-a06b-750439564548.png)

**Comment by tristaZero** [comment]
@TeslaCN Nice idea, do you want to have a try? Or welcome other volunteers?

**Comment by TeslaCN** [comment]
Hi @tristaZero 
I tried the checksum plugin in ElasticJob and I will finish this issue in passing.

**Comment by tristaZero** [comment]
Sound nice, look forward to it.
