### ISSUE TITLE
How to support hintshardingalgorithm and precisesharingalgorithm to make multiple sharding algorithms effective for the same table?

### ISSUE THREAD

**Issue by sika-code-cloud** [apache/shardingsphere#12946]
## Question
How to support hintshardingalgorithm and precisesharingalgorithm to make multiple sharding algorithms effective for the same table?
For example, generally, you can partition according to the specified partition key, but sometimes you need to specify forced partition. How can this be supported?

**Comment by strongduanmu** [comment]
Hi @dq-open-cloud, you can meet these needs by customizing algorithms. ShardingSphere only provides general algorithms.

**Comment by RaigorJiang** [comment]
I think @strongduanmu 's answer is very clear, and this issue will be closed.
