### ISSUE TITLE
读写分离对数据库版本有限制吗？目前使用postgresql-9.2版本，在访问次数过多情况下会出现数据库连接释放不掉的情况

### ISSUE THREAD

**Issue by itxiaohouzi** [apache/shardingsphere#12958]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
@itxiaohouzi Can you translate this issue to english? And provide more information according to issue template.
