### ISSUE TITLE
Using SQLHint to support encrypt rewrite besides

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#12957]
## Feature Request

Using SQLHint to support encrypt rewrite besides, for example:

`update table set plain_column = xxx where plain_column=xxx`
 might be rewrited as below
`update table set cipher_column = cipher_xxx, assist_column=assist_xxx, plain_column=xxx where assist_column=assist_xxx`

if SQLHint used as
`/* no encrypt rewrite */ update table set plain_column = xxx where plain_column=xxx`
 it would not be rewrited, but the same as below
`/* no encrypt rewrite */ update table set plain_column = xxx where plain_column=xxx`

Additional scenarios:

In data encryption scenarios, there are 3 kinds of refresh data:
1、Refresh for the old data, we call it initial refresh.
2、Clear Plain refresh, after encryption finished, we need to clear the plain.
3、Change key refresh, we should change the key regularly, after change the key, we should refresh the data.

For the 2, we should not rewrite the sql, while SS now support to set plain column null, and we need set blank way.

**Comment by cheese8** [comment]
@strongduanmu Are we thinking the same idea? please assign it to me, thanks.

**Comment by strongduanmu** [comment]
Fixed by #15965.
