### ISSUE TITLE
how can i use  normal table(have no use sharding) join broadcast table?

### ISSUE THREAD

**Issue by zhangwangren** [apache/shardingsphere#12967]
## Question
how can i use  normal table(have no use sharding) left join broadcast table? 

for example:
#broadcast table
spring.shardingsphere.sharding.broadcast-tables=t_config
#normal table 
t_order
when i try  SELECT * FROM t_order LEFT JOIN t_config ON XXX  
it throws Exception : Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Expression 'rwd.TM' is not being grouped 
pls help!!!

**Comment by strongduanmu** [comment]
@zhangwangren What version are you using?

**Comment by zhangwangren** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-beta</version>
        </dependency>

**Comment by strongduanmu** [comment]
@zhangwangren This seems to be a bug in beta version, can you try the master branch?

**Comment by zhangwangren** [comment]
i can not find

**Comment by zhangwangren** [comment]
im sorry!  This seems to bring a new bug, when i use the master code, nomarl table can join broadcast table, but the sharding table
doesn't  work.
------------------------------------
# this is my config
spring.shardingsphere.sharding.broadcast-tables[0]=dict_station_belong_reservoir
spring.shardingsphere.sharding.tables.dict_station_belong_reservoir.actual-data-nodes=ds$->{0}.dict_station_belong_reservoir
