### ISSUE TITLE
ExecutionException: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by yidazhi** [apache/shardingsphere#12988]
Hi team,
I executed a query, and the result set was about 2.81 million rows. During the execution process, proxysql hung. Check the log. There are a lot of following information in the log

I see some questioners say that adding Xmx can solve this problem. What command can I use to add Xmx ？

This is my current startup information:
java -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -server -Xmx2g -Xms2g -Xmn1g -Xss256k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -classpath .:/gamepind/apache-shardingsphere-incubating-4.0.0-sharding-proxy-bin/conf:/gamepind/apache-shardingsphere-incubating-4.0.0-sharding-proxy-bin/lib/* org.apache.shardingsphere.shardingproxy.Bootstrap

Please help me

for example:
[WARN ] 14:10:43.061 [HikariPool-4 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-4 - Thread starvation or clock leap detected (housekeeper delta=1m33s264ms8
99µs882ns).
[WARN ] 14:10:43.061 [HikariPool-8 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-8 - Thread starvation or clock leap detected (housekeeper delta=1m21s399ms1
07µs797ns).
[WARN ] 14:10:43.061 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=1m21s399ms8
µs655ns).
[WARN ] 14:10:43.062 [HikariPool-3 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Thread starvation or clock leap detected (housekeeper delta=1m26s718ms8
45µs724ns).
[WARN ] 14:10:36.527 [HikariPool-7 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-7 - Thread starvation or clock leap detected (housekeeper delta=2m40s194ms7
04µs652ns).
[WARN ] 14:10:43.389 [HikariPool-9 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-9 - Thread starvation or clock leap detected (housekeeper delta=45s555ms103
µs290ns).
Exception in thread "ShardingSphere-Command-3" java.lang.OutOfMemoryError: Java heap space
[WARN ] 14:12:56.959 [HikariPool-6 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-6 - Thread starvation or clock leap detected (housekeeper delta=56s577ms732
µs173ns).
[WARN ] 14:13:13.663 [HikariPool-9 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-9 - Thread starvation or clock leap detected (housekeeper delta=54s104ms876
µs824ns).
[WARN ] 14:13:16.947 [HikariPool-5 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=1m736ms940µ
s715ns).
[WARN ] 14:13:16.947 [HikariPool-8 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-8 - Thread starvation or clock leap detected (housekeeper delta=1m737ms171µ
s331ns).
[WARN ] 14:13:22.319 [HikariPool-12 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-12 - Thread starvation or clock leap detected (housekeeper delta=1m6s109ms
92µs864ns).
[WARN ] 14:13:24.449 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m4s890ms35
6µs36ns).
[WARN ] 14:13:26.959 [HikariPool-7 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-7 - Thread starvation or clock leap detected (housekeeper delta=1m11s72ms85
0µs44ns).
[WARN ] 14:13:27.286 [HikariPool-6 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-6 - Thread starvation or clock leap detected (housekeeper delta=45s316ms893
µs387ns).

**Comment by taojintianxia** [comment]
hi , @yidazhi

there is a start.sh in shardingsphere proxy/bin . try to modify that shell file.
`JAVA_MEM_OPTS=" -server -Xmx2g -Xms2g -Xmn1g -Xss1m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 "
`

just modify the config here and then save the startup.sh ( if you in windows , it's start.bat)

**Comment by taojintianxia** [comment]
> @taojintianxia thanks

you are more than welcome
