### ISSUE TITLE
Migrate the sharding-readwrite-splitting example

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#12986]
There is a `application-sharding-readwrite-splitting` in [spring-boot-jpa sharding example](https://github.com/Swastyy/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources)

It should be migrated to `mixed-feature-example`

For reference #12969

**Comment by RaigorJiang** [comment]
@yx9o Assigned.

**Comment by yx9o** [comment]
@menghaoranss @RaigorJiang Sorry, these two days have been too busy, I will submit the last module tonight and it will be completed.
