### ISSUE TITLE
when use ShardingSphere encrypt, The database returned no natively generated identity value after save

### ISSUE THREAD

**Issue by wuwu20048** [apache/shardingsphere#12994]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
before I use  ShardingSphere encrypt , the Id can return after save the entity.
### Actual behavior
I  am using  ShardingSphere encrypt feature;
when I use hibernate ,after save the entity,the primary id that is auto increment no returned, but the record was inserted in mysql database。 the hibernate throw the exception below:

org.hibernate.HibernateException: The database returned no natively generated identity value

```java
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = IDENTITY)
    public Integer getId() {
        return id;
    }
```

the table was not configured in encrypt:rule

**Comment by wuwu20048** [comment]
@strongduanmu it run well with the version 4.1.1,you can try

**Comment by strongduanmu** [comment]
@wuwu20048 I'm very sorry, the 4.1.1 version is a historical version, and it is no longer maintained. Welcome to the latest 5.0.0-beta version.

**Comment by strongduanmu** [comment]
@wuwu20048 Thank you for the information, I will check this issue.

**Comment by strongduanmu** [comment]
@wuwu20048 This problem is a bug and has been fixed in the master branch. Welcome to use the master branch to test. The upcoming RC1 version will contain a fix for this problem.
