### ISSUE TITLE
What are spring.provides for? and why the spring.provides content not same with package

### ISSUE THREAD

**Issue by LeeGuoPing** [apache/shardingsphere#12992]
## Question

![image](https://user-images.githubusercontent.com/35389145/136791475-eb10ab79-6a24-4e77-a1e8-4a79b97c6dbb.png)

**Comment by RaigorJiang** [comment]
> @RaigorJiang it seems to be used only for STS IDE, at the end of the following issue, some starter delete spring.provides files [spring-projects/spring-boot#12435](https://github.com/spring-projects/spring-boot/issues/12435)

It seems yes, can you help to investigate it?

**Comment by sandynz** [comment]
Hi @LeeGuoPing , looks `spring.provides` is removed from Spring Boot `2.1`, see [Spring Boot 2.1 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#removal-of-springprovides-files).
Currently, ShardingSphere depend on `<spring-boot.version>[1.5.20.RELEASE,2.0.0.M1)</spring-boot.version>`.
We'd better keep `spring.provides` for now.

**Comment by LeeGuoPing** [comment]
@RaigorJiang Thank you for your reply
![image](https://user-images.githubusercontent.com/35389145/136878621-6eb9af03-df78-416c-b759-41be4f94ada9.png)

**Comment by RaigorJiang** [comment]
I got some information through google search, you can also refer to:
https://www.google.com/search?q=spring.provides&btnK=Google+%E6%90%9C%E7%B4%A2&source=hp&ei=6vJkYZrXDLK1mAWFrajoAw&iflsig=ALs-wAMAAAAAYWUA-qqGZtjjV0SvDnCjoE2OKeAnuePT
