### ISSUE TITLE
Support all the jdbc urls for H2 databases

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#13007]
### Is your feature request related to a problem?
Currently the [H2DataSourceMetaData](https://github.com/apache/shardingsphere/blob/master/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/database/metadata/dialect/H2DataSourceMetaData.java#L43) only supports the memory jdbc url like ```jdbc:h2:mem```. While I'm workong with [quarkus-shardingsphere-jdbc](https://github.com/quarkiverse/quarkus-shardingsphere-jdbc), it needs to support all the [H2 jdbc urls ](https://quarkus.io/guides/datasource#h2)

```
jdbc:h2:{ {.|mem:}[name] | [file:]fileName | {tcp|ssl}:[//]server[:port][,server2[:port]]/name }[;key=value…​]
```
### Describe the feature you would like.

It could be great to support all of these urls.

**Comment by sandynz** [comment]
Hi @zhfeng , thanks for you feedback, you've found the cause, would you like to raise a PR to get it done?

**Comment by sandynz** [comment]
There might be a little refactoring to do, I'll check it later.

**Comment by sandynz** [comment]
@lichengxin813 Thank you for your PRs. Welcome to go ahead further.

@zhfeng it's done, you could verify it on master branch or later release.

**Comment by zhfeng** [comment]
@lichengxin813 Well done ! I will check it.
