### ISSUE TITLE
not support encrypt in sharding scene

### ISSUE THREAD

**Issue by yixianluo** [apache/shardingsphere#13011]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-5.0.0-beta and 5.0.0-master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
if rule is -!SHARDING and -!ENCRYPT, encrypt column can be rewrited right

config
rule:
- !SHARDING
    tables:
       tb_student:
          actualDataNodes: db.tb_student${0..1}
          tableStrategy:
               standard:
                    shardingColumn: sid
                    shardingAlgorithmName: student_inline
     shardingAlgorithms:
           student_inline:
               type: inline
               props:
                    xxxexpression: tb_student${sid%2}
                   
- !ENCRYPT
  encryptor:
      aes_en
          type: ace
          props:
              aes-key-value:xxxxx
   tables:
       tb_student:  
          column:
              phone:
                   plainColumn: phone
                   cipherColumn: enc_phone
                   encryptorName:  aes_en

sql:
select b.cid, b.name, count(a.sid) from tb_student a right join tb_course b on a.sid=b.sid group by b.cid having b.cid>5 order by b.cid desc

### Actual behavior
encrypt column not be rewrited
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
yaml file config -!SHARDING and -!ENCRYPT

**Comment by strongduanmu** [comment]
Thank you very much for your feedback. Can you provide a complete configuration and SQL which occurs exception?

**Comment by yixianluo** [comment]
has commit more info

**Comment by terrymanu** [comment]
No response
