### ISSUE TITLE
ShardingSphere-Proxy how to connect to jaeger-agent?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13019]
ShardingSphere-Proxy how to connect to jaeger-agent? how to reference jaeger-agent port?

![image](https://user-images.githubusercontent.com/13001038/137100049-d29d6d86-586f-4b3e-95ed-45d1932546e1.png)

**Comment by sandynz** [comment]
Hi @penghuazhou , for proxy `5.0.0-beta` or master branch, you could follow [Agent Integration](https://shardingsphere.apache.org/document/5.0.0-beta/cn/features/governance/observability/agnet/) to test.
