### ISSUE TITLE
did the cipher_column not suppot the null query?

### ISSUE THREAD

**Issue by wuwu20048** [apache/shardingsphere#13017]
## Question

did the cipher_column not suppot the null query?
eg:
String hql="from User where mobile=:mobile and idcard is not null" ;

the mobile and the idcard fileid has cipher column.

expect sql:
select * from user where mobile_cipher='XXX' and idcard_cipher is not null;

Actual SQL:
select * from user where mobile_cipher='XXX' and  (idcard is not null) 

but the plain_column idcard was deleted  and not existed。
so what is the problem and Is there a solution?

**Comment by terrymanu** [comment]
I just close the issue because of no feedback for long time.
