### ISSUE TITLE
springboot + mybatis + shardingsphere agent. After starting springbStarting from the sixth query, only the total number of records can be queried, but the record content cannot be queried. 

### ISSUE THREAD

**Issue by 791837060** [apache/shardingsphere#13022]
springboot + mybatis + shardingsphere proxy. After starting springboot, it can be queried normally for 5 times. Starting from the sixth query, only the total number of records can be queried, but the record content cannot be queried. 0 rows of records are returned, and the query statement field includes the timestamp type. You need to restart springboot to queried again 5 times. what is the reason?

**Comment by sandynz** [comment]
Hi @ulwfcyvi , could you submit issue with template? Much information is needed for us

**Comment by sandynz** [comment]
@ulwfcyvi , you could fill in information with this template:

```
## Bug Report

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).
```
