### ISSUE TITLE
"apache-shardingsphere-4.1.1-src-release" can not support etcd?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13039]
"apache-shardingsphere-4.1.1-src-release" can not support etcd?

Exception in thread "main" java.lang.RuntimeException: Invalid `org.apache.shard
ingsphere.orchestration.center.RegistryCenterRepository` SPI type `etcd`.
        at org.apache.shardingsphere.spi.TypeBasedSPIServiceLoader.newService(Ty
peBasedSPIServiceLoader.java:46)
        at org.apache.shardingsphere.orchestration.core.registrycenter.RegistryC
enterRepositoryServiceLoader.load(RegistryCenterRepositoryServiceLoader.java:49)
        at org.apache.shardingsphere.orchestration.core.facade.ShardingOrchestra
tionFacade.<init>(ShardingOrchestrationFacade.java:69)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.startWithRegistryCe
nter(Bootstrap.java:131)
        at org.apache.shardingsphere.shardingproxy.Bootstrap.main(Bootstrap.java
:87)
(END)

**Comment by sandynz** [comment]
It should be supported in `4.1.1`, from docs and source code.

I verified in `EtcdCenterRepositoryTest`, modified some code:
```
    static {
        NewInstanceServiceLoader.register(RegistryCenterRepository.class);
    }
    
    @Before
    public void setUp() {
        Collection<RegistryCenterRepository> repositories = NewInstanceServiceLoader.newServiceInstances(RegistryCenterRepository.class);
        setClient();
        setProperties();
    }
```
`repositories` has `EtcdCenterRepository` instance.

@penghuazhou have you included maven dependency of `sharding-orchestration-center-etcd`?

**Comment by penghuazhou** [comment]
thanks
