### ISSUE TITLE
select information_schema didn't release connection cause connection pool exhausted 

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#13033]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
execute such sql multiple times should be ok
```
select `column_name` as `column_name`, `column_comment` as `column_comment`, `column_default` as `column_default`, `data_type` as `data_type` from information_schema.columns limit 1;
```

### Actual behavior
after ```maxPoolSize``` times, SQL will be hang until connection timeout.

### Reason analyze (If you can)
getSourceData of AbstractSelectInformationExecutor.java didn't close connection.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
execute such sql for ```maxPoolSize``` times 
```
select `column_name` as `column_name`, `column_comment` as `column_comment`, `column_default` as `column_default`, `data_type` as `data_type` from information_schema.columns limit 1;
```

**Comment by RaigorJiang** [comment]
Thank you @roodkcab @lanchengx .
