### ISSUE TITLE
im sorry!  This seems to bring a new bug, when i use the master code, nomarl table can join broadcast table, but the sharding table doesn't  work.

### ISSUE THREAD

**Issue by zhangwangren** [apache/shardingsphere#13053]
im sorry!  This seems to bring a new bug, when i use the master code, nomarl table can join broadcast table, but the sharding table doesn't  work.  
------------------------------------
# this is my config
spring.shardingsphere.sharding.broadcast-tables[0]=dict_station_belong_reservoir
spring.shardingsphere.sharding.tables.dict_station_belong_reservoir.actual-data-nodes=ds$->{0}.dict_station_belong_reservoir

_Originally posted by @zhangwangren in https://github.com/apache/shardingsphere/issues/12967#issuecomment-943112300_

**Comment by sandynz** [comment]
Hi @zhangwangren , could submit issue with template? As detailed as possible, it's necessary for us to understand your problem.
