### ISSUE TITLE
MGR High Avaliable Discovery config auto task not found current primary

### ISSUE THREAD

**Issue by llzx373** [apache/shardingsphere#13066]
### Which version of ShardingSphere did you use?

last 5.0 RC version

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

MGR High Avaliable Discovery config auto task primaryDatasource parameter change with current real primary，do not send primary change event every check，should only in the time primary change。

### Actual behavior

primaryDatasource parameter not change with current real primary， send primary change event every check

### Reason analyze (If you can)

primaryDatasource init when task init，but not change when metachange in metadata（Zookeeper）。

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

configure HA using Discovery ，with debug mode，seen the primary change events 。

**Comment by sandynz** [comment]
Hi @llzx373 , thanks for your feedback. Could you supply detailed configuration, and some screenshots to `Reason analyze`?

**Comment by zjcnb** [comment]
@llzx373 Hi，I think this problem are fixed in master branch, Can you try it again?

**Comment by terrymanu** [comment]
No response
