### ISSUE TITLE
If the encrypted field is not set or set to null when inserted, the value stored in the database will still be encrypted into a null string

### ISSUE THREAD

**Issue by chengyequn** [apache/shardingsphere#13061]
If the encrypted field is not set or set to null when inserted, the value stored in the database will still be encrypted into a null string,
my shardingsphere's version is 4.0.1. How can solve it?

**Comment by cheese8** [comment]
so what the problem is? or you can check the field null in your encrypt algorithm.

**Comment by chengyequn** [comment]
> so what the problem is? or you can check the field null in your encrypt algorithm.

Thanks for your reply, I use the default AES encryption，can you tell me how to not encrypt the null value？

**Comment by chengyequn** [comment]
> For example, You could copy the default AES encryption then customize it as 'AES1' in your project, then check the field null.

Thank you for your reply！I will try it
