### ISSUE TITLE
ShardingSphere-UI cannot start with JDK 11

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#13071]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-UI
### Expected behavior
Normal start.My environment is Eclipse Adoptium builds of OpenJDK 11.0.12.
### Actual behavior
Can't start normally.
```shell
Starting the ShardingSphere-UI ...
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
![image](https://user-images.githubusercontent.com/20187731/137590031-adf6611b-f223-4c12-901b-48c7bce54f5c.png)

**Comment by linghengqian** [comment]
> Hi @linghengqian , `UseFastAccessorMethods` was removed in JDK 9. https://github.com/apache/shardingsphere/issues/12578 supported JDK 11 build, we could try to make start script to support JDk 11 then.

I noticed that shardingSphere-UI was last released on Nov 22ed, 2020. Why isn't it updated with this year's ShardingSphere 5.0.0-beta?

**Comment by tristaZero** [comment]
Hi @linghengqian We're sorry, the UI project hasn't been updated along with the 5.0.0-beta release. The reason is that we have no more time and effort on it. But we welcome other guys to activate UI project.

**Comment by tristaZero** [comment]
Hi, I will help you close this one.
