### ISSUE TITLE
Do not support sql parameter?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13089]
Do not support sql parameter?

version:shardingshpere-proxy, the master git 

It be ok if use Where("app_id = 1"), It not be of when use Where("app_id = ?", 1)
![image](https://user-images.githubusercontent.com/13001038/137687783-6358a6ef-b39a-473b-89fc-88d5677f8498.png)

**Comment by lanchengx** [comment]
@penghuazhou thanks, 
could you show what the actual SQL sent by the ORM to the proxy is?
It will be printed in the Proxy log if you enable `sql-show`

**Comment by lanchengx** [comment]
thanks, could you find the SQL sent to the proxy when using `?` as a placeholder, for example through debug.

**Comment by lanchengx** [comment]
Yes, modified in https://github.com/apache/shardingsphere/pull/13095

**Comment by penghuazhou** [comment]
@lanchengx 

[DEBUG] 2021-10-18 17:35:02.843 [nioEventLoopGroup-3-2] o.a.s.db.protocol.codec.PacketCodec - Read from client 69c087fd : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 00 00 00 5a 6c 72 75 70 73 63 5f 31 5f 31 00 |P...Zlrupsc_1_1.|
|00000010| 53 45 4c 45 43 54 20 2a 20 46 52 4f 4d 20 22 71 |SELECT * FROM "q|
|00000020| 75 61 6c 69 74 79 5f 72 65 63 6f 72 64 5f 72 65 |uality_record_re|
|00000030| 73 75 6c 74 22 20 57 48 45 52 45 20 61 70 70 5f |sult" WHERE app_|
|00000040| 69 64 20 3d 20 24 31 20 4f 52 44 45 52 20 42 59 |id = $1 ORDER BY|
|00000050| 20 69 64 20 64 65 73 63 00 00 00 44 00 00 00 10 | id desc...D....|
|00000060| 53 6c 72 75 70 73 63 5f 31 5f 31 00 53 00 00 00 |Slrupsc_1_1.S...|
|00000070| 04                                              |.               |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-10-18 17:35:02.961 [Connection-2-ThreadExecutor] o.a.s.p.f.p.c.PostgreSQLCommandExecutorFactory - Execute packet type: PARSE_COMMAND, value: org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.parse.PostgreSQLComParsePacket@212e6d94
[DEBUG] 2021-10-18 17:35:03.356 [Connection-2-ThreadExecutor] o.a.s.p.f.p.c.PostgreSQLCommandExecutorFactory - Execute packet type: DESCRIBE_COMMAND, value: org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.describe.PostgreSQLComDescribePacket@44a59c8c
[DEBUG] 2021-10-18 17:35:03.359 [Connection-2-ThreadExecutor] o.a.s.p.f.p.c.PostgreSQLCommandExecutorFactory - Execute packet type: SYNC_COMMAND, value: org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.binary.sync.PostgreSQLComSyncPacket@294a8fe2
[DEBUG] 2021-10-18 17:35:03.361 [nioEventLoopGroup-3-2] o.a.s.db.protocol.codec.PacketCodec - Write to client 69c087fd : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 31 00 00 00 04                                  |1....           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-10-18 17:35:03.362 [nioEventLoopGroup-3-2] o.a.s.db.protocol.codec.PacketCodec - Write to client 69c087fd : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 5a 00 00 00 05 49                               |Z....I          |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-10-18 17:35:05.170 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.170 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.174 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.174 [HikariPool-1 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.310 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.310 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Before cleanup stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.311 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)
[DEBUG] 2021-10-18 17:35:05.311 [HikariPool-2 housekeeper] com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - After cleanup  stats (total=1, active=0, idle=1, waiting=0)


<img width="1397" alt="企业微信截图_4b812127-756a-42a3-9de7-1aabfbb54bbb" src="https://user-images.githubusercontent.com/13001038/137706773-1951d7c7-47f1-4346-ae32-46cdaeac6534.png">

**Comment by lanchengx** [comment]
@penghuazhou Sorry, some omissions cause compilation exceptions, please update the code and make sure that the compilation is passed and try again

**Comment by TeslaCN** [comment]
@penghuazhou 
Could you provide example codes in text format? I might try the Golang client after #10814 fixed.

**Comment by penghuazhou** [comment]
thanks
