### ISSUE TITLE
DistSQL function enhancement, add more DistSQL syntax

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13087]
Related Issue : https://github.com/apache/shardingsphere/issues/12735

Add DistSQL syntax to improve the support for the rules in the configuration file

- [x] Add `CREATE SHARDING ALGORIHTM` syntax
- [x] Add `CREATE DEFAULT SHARDING [DATABASE | TABLE] STRATEGY` syntax
- [x] `CREATE SHARDING TABLE RULE` syntax enhancement

Add distSQL syntax to show more information

- [x] Add `SHOW SINGLE TABLE RULES` syntax
- [x] Add `SHOW INSTANCE LIST` syntax
- [x] Add `SHOW READWRITE_SPLITTING READ RESOURCES` syntax

**Comment by menghaoranss** [comment]
@lanchengx  If all tasks are completed, please close this issue.
