### ISSUE TITLE
Migrate PR from Gitee to GitHub

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#13083]
### Background
Previously, our contributor submitted PR from Gitee, but unfortunately, these codes cannot be automatically synchronized to the Github repository.

### Aim
Use the code on Gitee to resubmit a PR on GitHub.
Gitee PR link:
https://gitee.com/Sharding-Sphere/sharding-sphere/pulls/3

**Comment by totalo** [comment]
hi @RaigorJiang , Does a certain volunteer move all the prs, or do you expect contributors on gitee to be responsible for their own prs?

**Comment by Swastyy** [comment]
Hi @RaigorJiang , Is this issue not fixed yet? If so, I want to try.

**Comment by RaigorJiang** [comment]
@Swastyy 
Sorry, it was fixed by https://github.com/apache/shardingsphere/pull/13318.  I will close this issue.

**Comment by haoqi123** [comment]
我是gitee上的原贡献者，没有及时看到消息，心理难受没有帮上忙，很抱歉

**Comment by RaigorJiang** [comment]
@haoqi123 
Sorry for that, and only English can be used here, please translate and edit the comment, thank you
