### ISSUE TITLE
header of information_schema is always ColumnName instead of ColumnLabel

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#13090]
### Which version of ShardingSphere did you use?
5.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
header of information_schema should be column label

### Actual behavior
header of information_schema is column name, for example 
```
select `COLUMN_NAME` as `cn`  from information_schema.columns where table_schema = 'test' and table_name = 'tbl'
```
should return cn, where actually return COLUMN_NAME now.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
select `COLUMN_NAME` as `cn`  from information_schema.columns where table_schema = 'test' and table_name = 'tbl'
```

**Comment by lanchengx** [comment]
Hi@roodkcab, thanks for your feedback, do you want to try to solve it?
