### ISSUE TITLE
how to use EncryptRuleConfiguration and ShardingRuleConfiguration together in shardingsphere-jdbc with version 4.0.0 

### ISSUE THREAD

**Issue by lebron374** [apache/shardingsphere#13105]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

in our project，we need to both use  EncryptRuleConfiguration and ShardingRuleConfiguration together?any example to show this

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
