### ISSUE TITLE
support parsing SHOW REPLICA STATUS for mysql

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13138]
Hi community,

This issue can be a good first try.

## Aim
support parse mysql administration statements sql `SHOW REPLICA STATUS`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
Add antlr rule in DALStatement.g4. refer to https://dev.mysql.com/doc/refman/8.0/en/show-replica-status.html
Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`
To complete this issue, I think we should complete these steps:
- Create anltr rule in DALStatement.g4
- Create `MySQLShowReplicaStatusStatement` class in this package `org.apache.shardingsphere.sql.parser.sql.dialect.statement.mysql.dal`
- Add rule in `shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java`
- Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`. 
- Finally, add test for parse clone statement in `shardingsphere-test` module
## Example FYI
- Refer to this merged pr：https://github.com/apache/shardingsphere/pull/12979/files

**Comment by flycash** [comment]
Only support `SHOW REPLICA STATUS`?
MySQL 5.7 has no `SHOW REPLICA STATUS` but have `SHOW SLAVE STATUS`

**Comment by tuichenchuxin** [comment]
@flycash I saw this in document 
https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html
I think we should support both.

**Comment by flycash** [comment]
ok
