### ISSUE TITLE
support parsing SHOW PROCEDURE STATUS for mysql

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13131]
Hi community,

This issue can be a good first try.

## Aim
support parse mysql administration statements sql `SHOW PROCEDURE STATUS`

## Basic Qualifications
- java
- maven
- antlr4

## Detail
We have completed the clone rule in DALStatement.g4.
But have not yet implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`
To complete this issue, I think we should complete these steps:
- Create `MySQLShowProcedureStatusStatement` class in this package `org.apache.shardingsphere.sql.parser.sql.dialect.statement.mysql.dal`
- Add rule  in `shardingsphere-sql-parser/shardingsphere-sql-parser-engine/src/main/java/org/apache/shardingsphere/sql/parser/core/database/visitor/SQLVisitorRule.java`
- Implement the visit method in `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/impl/MySQLDALStatementSQLVisitor.java`. 
- Finally, add test for parse clone statement in `shardingsphere-test` module
## Example FYI
- Refer to this merged pr：https://github.com/apache/shardingsphere/pull/12979/files

**Comment by tuichenchuxin** [comment]
@ThanoshanMV You can use this code to test it.
https://github.com/apache/shardingsphere/blob/837b14ff0657cd59673de25f31cb48c02a9e1088/examples/other-example/shardingsphere-parser-example/src/main/java/org/apache/shardingsphere/example/parser/mysql/statement/MySQLParserStatementExample.java

**Comment by flycash** [comment]
I found that there was already `MySQLShowProcedureStatusStatement`, so it was addressed, right?

**Comment by tuichenchuxin** [comment]
@flycash yes,it has been completed, I'll close it, thank you.
