### ISSUE TITLE
where is the proxy ip message in zookeeper?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13171]
version:/Users/zego/IdeaProjects/apache-shardingsphere-5.0.0-beta-src-release

<img width="621" alt="企业微信截图_7c544eb1-1d35-491a-aec3-636b43bb0364" src="https://user-images.githubusercontent.com/13001038/138059649-b48b9446-e883-4199-aea4-6ba205ebaca4.png">

**Comment by zjcnb** [comment]
@penghuazhou Hi, you can look this.
![image](https://user-images.githubusercontent.com/33742097/138063589-2f96c583-1982-4bf6-b98d-74b6dadc863f.png)
