### ISSUE TITLE
4.0 Do you support from_ Unixtime function？

### ISSUE THREAD

**Issue by xfzhaoGit** [apache/shardingsphere#13184]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

4.0.1  support mysql from_unixtime main？

**Comment by xfzhaoGit** [comment]
In the shardingsphere+mybatis-plus SQL statement, create_ date is used as the partition key, and the input parameter long type uses from_ The unixtime function is converted to date, resulting in no user-defined policy. You can directly pass in the date type. Do you support from_ Unixtime function

**Comment by lanchengx** [comment]
@xfzhaoGit Sorry,  we hope the title is also in English, could you adjust it?

**Comment by xfzhaoGit** [comment]
4.0.0-RC2

**Comment by xfzhaoGit** [comment]
OK， thanks
