### ISSUE TITLE
Query Emoji's questions

### ISSUE THREAD

**Issue by duansy123** [apache/shardingsphere#13198]
The data obtained by querying the fields with emoji expressions becomes "?"
But not every time it’s "?" It is occasionally possible to successfully display emoji
The character sets of all libraries and tables are unified utf8mb4
The character set of the linked database is also set &character_set_server=utf8mb4&connectionCollation=utf8mb4_bin
Please help to solve this problem

**Comment by RaigorJiang** [comment]
> Version is 5.0.0

`5.0.0` is not existed, can you give the full version?

**Comment by RaigorJiang** [comment]
Hi @duansy123  Is it effective?

**Comment by duansy123** [comment]
> Hi @duansy123 Is it effective?

I am trying but the new version configuration is a bit different, I need time to start it

**Comment by RaigorJiang** [comment]
> I am trying but the new version configuration is a bit different, I need time to start it

Yes, there are some differences.
