### ISSUE TITLE
When the data source configuration information is incorrect, the wrong DB host is displayed in sharding-proxy

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#13203]
![image](https://user-images.githubusercontent.com/45256940/138250380-1ec86cac-8174-4cfe-a386-4925a4c15c6d.png)
The configured data source ip is not this

**Comment by RaigorJiang** [comment]
> > ![image](https://user-images.githubusercontent.com/45256940/138251277-a7f37919-12a4-4d14-96f2-29edd83194a5.png)


@marker-wu  That is not the data source host, it is the client address.

**Comment by RaigorJiang** [comment]
![image](https://user-images.githubusercontent.com/5668787/138382077-1ad0c0f9-85ee-42b0-9717-d8a6cc0e1bc0.png)

This is the common prompt style of the database, not a problem of ShardingSphere.
