### ISSUE TITLE
Many mistakes

### ISSUE THREAD

**Issue by asura2019** [apache/shardingsphere#13201]
<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>

1，Cross library joins are not supported
2，Count (1) is not supported
3，Not supported (min (ID) - 1)
4，Cross database query is not supported

Speechless, brothers！

**Comment by lanchengx** [comment]
Hi @winer77444 , thanks for you feedback, could you try the latest version?

![image](https://user-images.githubusercontent.com/52209337/138250604-1a660ce6-574d-4175-9c14-930cda1788d3.png)

**Comment by asura2019** [comment]
Can you give me a press create_ time between ? and ? Configuration? I've been working on it for a few days, and your configuration is not detailed

**Comment by TeslaCN** [comment]
Close due to no response.
