### ISSUE TITLE
Doesn't it support active/standby switching similar to Mycat? What should I do if the master is down?

### ISSUE THREAD

**Issue by SugarPPig** [apache/shardingsphere#13210]
A master m1 is used to process all write requests, and its slave s1, another master m2 and its slave s2 are responsible for all read requests. When master m1 goes down, master m2 is responsible for writing requests, and m1 and m2 are each other's standbys.

**Comment by lanchengx** [comment]
Hi @SugarPPig , only support English ask questions, could you adjust this issue?

**Comment by SugarPPig** [comment]
> Hi @SugarPPig , only support English ask questions, could you adjust this issue?

Ok , It has been modified.
