### ISSUE TITLE
In terms of date ranges, there are some problems with actual-data-nodes

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#13240]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

After the project was upgraded to `5.0.0-alpha`, I thought, `INTERVAL`, if `datetime-interval-unit` chooses `DAYS` and `datetime-interval-amount` chooses `1`, in this case, how should `actual-data-nodes` be written?

Is it difficult to avoid the issue of different days in February in leap years and peace years?

By analogy, if `INTERVAL` chooses `DAYS` for `datetime-interval-unit` and `7` for `datetime-interval-amount`, in this case, `actual-data-nodes` is also difficult to write in line expressions? Can someone provide an idea?

The best way to deal with dates I have seen is to map dates to natural numbers of 1, 2,...N as shown by `AUTO_INTERVAL`. There is no such problem in `actual-data-nodes`. But this and `INTERVAL` are completely two ideas.

After all, `AUTO_INTERVAL` does not have the attribute configuration of a logical table. When I want to extend `AUTO_INTERVAL`, I can only use `CLASS_BASED`.

The content of this issue comes from the discussions I created ( https://github.com/apache/shardingsphere/discussions/13230 ), but after looking through it, I realized that this is not a question that has a clear answer, so I take part of it to issue, and would like someone to give some ideas in the source code example.

2021.10.27update: 
I'm sorry I thought that `auto-tables` has no logical tables...this is my practice accident.

### Discussed in https://github.com/apache/shardingsphere/discussions/13230

<div type='discussions-op-text'>

<sup>Originally posted by **linghengqian** October 22, 2021</sup>
After the project was upgraded to `5.0.0-alpha`, I thought, `INTERVAL`, if `datetime-interval-unit` chooses `DAYS` and `datetime-interval-amount` chooses `1`, in this case, how should `actual-data-nodes` be written?

Is it difficult to avoid the issue of different days in February in leap years and peace years?

By analogy, if `INTERVAL` chooses `DAYS` for `datetime-interval-unit` and `7` for `datetime-interval-amount`, in this case, `actual-data-nodes` is also difficult to write in line expressions? Can someone provide an idea?

The best way to deal with dates I have seen is to map dates to natural numbers of 1, 2,...N as shown by `AUTO_INTERVAL`. There is no such problem in `actual-data-nodes`. But this and `INTERVAL` are completely two ideas.

After all, `AUTO_INTERVAL` does not have the attribute configuration of a logical table. When I want to extend `AUTO_INTERVAL`, I can only use `CLASS_BASED`.</div>

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue? I remember that we have fixed this problem in the master branch.

**Comment by linghengqian** [comment]
> @tuichenchuxin Can you help check this issue? I remember that we have fixed this problem in the master branch.

Sorry, I want to ask what fix is? Now doesn't INTERVAL need to define actual-data-Nodes?

**Comment by linghengqian** [comment]
I feel that it is better for me to put the unresolved issues in the newly opened `Open SphereEx Community`. I will close this issue.
