### ISSUE TITLE
To support IPv6

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#13260]
It's better to remove the property **java.net.preferIPv4Stack** in the start script of proxy and scaling to enable the IPv6 network.

```
java.net.preferIPv4Stack (default: false)
If IPv6 is available on the operating system the underlying native socket will be, by default, an IPv6 socket which lets 
applications connect to, and accept connections from, both IPv4 and IPv6 hosts. However, in the case an application would 
rather use IPv4 only sockets, then this property can be set to true. The implication is that it will not be possible for the 
application to communicate with IPv6 only hosts.
```

Please refer to:
https://docs.oracle.com/javase/8/docs/api/index.html

**Comment by sandynz** [comment]
I started proxy on OSX local by `org.apache.shardingsphere.proxy.Bootstrap` without `-Djava.net.preferIPv4Stack=true` option, connect and test with native MySQL client, it works with `-h127.0.0.1` and `-h0:0:0:0:0:0:0:1`.
