### ISSUE TITLE
support optimize table route

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13279]
### Which version of ShardingSphere did you use?
 master branch
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
I have configed two mysql instance, but when i execute this sql
```
OPTIMIZE TABLE t_order;
```
It should be 
```
ds-0 OPTIMIZE TABLE t_order_0;
ds-0 OPTIMIZE TABLE t_order_1;
ds-1 OPTIMIZE TABLE t_order_0;
ds-1 OPTIMIZE TABLE t_order_1;
```
but actual is
```
ds-1 ::: OPTIMIZE TABLE t_order;
```

**Comment by LiujunjieALiling** [comment]
I also find this bug,The bad thing is that we are now batch, and there are a lot of Library tables 。 Which  version  will  be supported   on  this  optimize  ?

we are  in  version 4.1

**Comment by tuichenchuxin** [comment]
@LiujunjieALiling This optimize will supported on version 5.0.1
