### ISSUE TITLE
Charset in ShardingSphere Proxy is determined by environment

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#13317]
## Feature Request

Charset of ShardingSphere Proxy is determined by
1. locale of environment
2. The property `file.encoding`

### Is your feature request related to a problem?
If the charset was unset in environment, any non-ASCII characters will always be malformed.

### Describe the feature you would like.

* [x] Parse Charset provides by client in protocol and store in connection scope. #13332 
* [x] Intercept SQL like `set names utf8` or `set client_encoding to 'UTF8'` and set the charset to current channel attribute. Duplicated with #12245

**Comment by soulasuna** [comment]
I will try second task

**Comment by TeslaCN** [comment]
Setting charset is available.
