### ISSUE TITLE
Support openGuass dialect SQL parse and execute

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13326]
### Is your feature request related to a problem?

#11026 #11025

### Describe the feature you would like.

At present, the master branch already supports the `openGuass` database. Most of the syntax of `openGuass` is the same as `PostgreSQL`. We can use the `PostgreSQL` parser directly, but there are some dialects of `openGuass` that are still not supported. 

Therefore, in order to improve the support of `openGuass` dialect, we need to enhance the existing `openGuass` parser so that it can easily expand the unique statement parsing on the basis of inheriting the PostgreSQL parser, and support these statements execute.

**Comment by tuichenchuxin** [comment]
@strongduanmu I want to try it.

**Comment by tuichenchuxin** [comment]
## Background
Recently, We plan to fully support the openGauss database .  Currently protocol is already supported, so we only need to add openGauss's antlr grammar.
## Design
1. add antlr g4 for openGauss.
2. add test case.

![openGauss_parse](https://user-images.githubusercontent.com/86938616/140030133-2fe02be6-7882-4777-99a4-2a3694a9d399.png)
## Task
- [ ] add antlr g4 for openGauss.
- [ ] support openGauss parse.

**Comment by strongduanmu** [comment]
Already support.
