### ISSUE TITLE
sharding-proxy version 4.0.1  load data infile is not supported?

### ISSUE THREAD

**Issue by we1s3** [apache/shardingsphere#13328]
Using sharding proxy version 4.0.1 TCP client centos7 to execute “load data infile”, an error occurred:
ERROR 10002 (C1000): 2Unknown exception: [Unsupported SQL of `load data infile '

**Comment by terrymanu** [comment]
We have no plan to support `load data infile` now, anybody interest the issue?

**Comment by terrymanu** [comment]
Expired requirement, I just close this issue.
