### ISSUE TITLE
Discussion on the `shardingsphere-sharding-distsql` module

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13333]
The `shardingsphere-distsql-parser` module and `shardingsphere-sharding-distsql` in `shardingsphere-features` both define DistSQL syntax and implement related functions, but the directory structure is inconsistent, which increases the difficulty of understanding.

Refer to `shardingsphere-sharding-distsql` structure
```
├── shardingsphere-sharding-distsql
│    ├── shardingsphere-sharding-distsql-statement
│    ├── shardingsphere-sharding-distsql-parser
│    ├── shardingsphere-sharding-distsql-handler
```

It is recommended that the previous `shardingsphere-distsql-parser` structure
```
├── shardingsphere-distsql-parser
│    ├── shardingsphere-distsql-parser-statement
│    ├── shardingsphere-distsql-parser-engine
```
change into
```
├── shardingsphere-distsql
│    ├── shardingsphere-distsql-engine
│    ├── shardingsphere-distsql-parser
│    ├── shardingsphere-distsql-statement
```

Just to set the ball rolling, looking forward to a better idea

**Comment by terrymanu** [comment]
How about use structure blow: 

```
├── shardingsphere-distsql
│    ├── shardingsphere-distsql-parser
│    ├── shardingsphere-distsql-statement
│    ├── shardingsphere-distsql-handler
```

Move spi, engine, g4 and generated code to shardingsphere-distsql-parser together?

**Comment by RaigorJiang** [comment]
> How about use structure blow:
> 
> ```
> ├── shardingsphere-distsql
> │    ├── shardingsphere-distsql-parser
> │    ├── shardingsphere-distsql-statement
> │    ├── shardingsphere-distsql-handler
> ```
> 
> Move spi, engine, g4 and generated code to `shardingsphere-distsql-parser` together, and add `shardingsphere-distsql-handler` for keep consist with rule's distsql?

Yes it looks better.

**Comment by lanchengx** [comment]
Hi, @terrymanu 
The `shardingsphere-distsql-handler` module may not be added
I found that some handler classes that will be moved have a lot of dependencies on other modules, such as `shardingsphere-sql-parser-statement`, `shardingsphere-infra-common`, etc., which will complicate the dependency of `shardingsphere-distsql` .

**Comment by lanchengx** [comment]
Has been completed
