### ISSUE TITLE
How to make the broadcastTables query fall into a fixed data source

### ISSUE THREAD

**Issue by ziliangzeng** [apache/shardingsphere#13348]
## Question

- version
   5.0.0-beta
- question
   hello，i would like to konw How to make the broadcastTables query fall into a fixed data source？
   I think my reading ability is limited and I can’t find the answer on the official website, hahaha.

**Comment by ziliangzeng** [comment]
@RaigorJiang hi, Thanks for your answer.
In fact, it is because I have some monolithic tables that need to be broadcasted as global tables, but there are problems when querying. I finally solved the problem by setting the monolithic table as a shard table, but specifying the data source. Hahaha

**Comment by RaigorJiang** [comment]
OK, thanks for your feedback.
