### ISSUE TITLE
Execute 'preview' in DataGrip and return parsing failure.

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#13366]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Execute `preview select * from t_order;` in DataGrip to return the result.

### Actual behavior
Failed to parse sql.
![2e4fdc7c7fae0be60873e6a4d6c3700](https://user-images.githubusercontent.com/12792261/139524858-848b6100-b65e-4d44-afd8-f6f2ec83c96d.png)

### Reason analyze (If you can)
DistSQL does not parse comments and needs to be removed.

If possible, I hope to fix it.

**Comment by RaigorJiang** [comment]
Hi @yx9o  ,
This is a very important issue, thank you for your feedback.
And looking forward to your PR!
