### ISSUE TITLE
Mybaties Plus Insert did not return to the primary key?

### ISSUE THREAD

**Issue by XiaoHongMao94** [apache/shardingsphere#13388]
I use ShardingSphere data encryption module
When I use mybaties plus insert a data object of a primary key has not been assigned
The table is not in the configuration file ==> rules.encrypt.tables
In the form in the configuration file is normal

## configuration 
spring:
  shardingsphere:
    rules:
      encrypt:
        encryptors:
          encryptor_aes:
            type: sm4
        tables:
          test_table:
            columns:
              fname:
                plainColumn: fname
                cipherColumn: fname_enc
                encryptorName: encryptor_aes

## code

TestTable test = new TestTable();
testService.saveOrUpdate(test); // **test bean primary key is null**

public interface TestServiceextends IService<TestTable> {
}

**Comment by menghaoranss** [comment]
which version did you use? please provide logic sql, actual sql and other more log info.

**Comment by terrymanu** [comment]
Hi, ORM integrate is not the scope which we served.
Please start discuss after dig to JDBC layer.
