### ISSUE TITLE
PostgreSQL delete statement parses the schema and table incorrectly

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13389]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC or ShardingSphere-Proxy

### Expected behavior

execute EncryptSQLRewriterParameterizedTest successfully

### Actual behavior

![image](https://user-images.githubusercontent.com/10829171/139651249-c6a23580-72e9-4267-aac0-040bf6fa3c99.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Modify `scenario/sharding/case/delete.xml:18` file, and remove `db-types` in `delete_without_sharding_value_for_parameters` or `delete_without_sharding_value_for_literals` test case, then run `EncryptSQLRewriterParameterizedTest`, you will get the wrong result.

**Comment by tuichenchuxin** [comment]
I want to check this issue.

**Comment by strongduanmu** [comment]
@tuichenchuxin Great, I will assign this issue to you.
