### ISSUE TITLE
It would be better to modify one of method of ShardingSpherePrivileges interface's return comments 

### ISSUE THREAD

**Issue by LeeGuoPing** [apache/shardingsphere#13410]
## Question

![image](https://user-images.githubusercontent.com/35389145/139830530-dea5905e-fc44-42f6-a550-e36faebc09b0.png)
It would be better to modify method `boolean hasPrivileges(String schema);` ' return comments  from `has or not` to `has privileges or not`

Do you think so?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
@LeeGuoPing you can fix it with a PR.
