### ISSUE TITLE
create_ Date is used as the partition key according to create_ Date range query only supports between and?

### ISSUE THREAD

**Issue by xfzhaoGit** [apache/shardingsphere#13414]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**. 

create_ Date is the partition key, and press create_ date range lookup between and follows the custom fragmentation strategy, but > and < follow all table queries.

![003CF7EE-7576-47D5-A351-F86C2BEA62E3](https://user-images.githubusercontent.com/50861620/139847227-56b9166c-c46b-4d55-aafe-8fbe8164df59.jpeg)

![5ECC461E-E279-4791-B440-C68D60BE9615](https://user-images.githubusercontent.com/50861620/139847188-6e3e0069-7b3f-453a-8d05-6f61844d9251.jpeg)

**Comment by terrymanu** [comment]
No necessary information, maybe you can follow the template to provide such as version, config file etc.
