### ISSUE TITLE
 Insert and update SQL does not report errors when the field is too long

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#13423]
**The shardingsphere version is 5.0.0.beta,database is mysql.**

**shardingsphere does not report errors：**
2021-11-03 10:45:38.836|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Logic SQL: insert into `t_pipeline_info` (`PIPELINE_ID`, `PROJECT_ID`, `PIPELINE_NAME`, `PIPELINE_DESC`) values (?, ?, ?, ?) on duplicate key update `t_pipeline_info`.`PIPELINE_DESC` = ?
2021-11-03 10:45:38.837|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] SQLStatement: MySQLInsertStatement(setAssignment=Optional.empty, onDuplicateKeyColumns=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.OnDuplicateKeyColumnsSegment@7b11b60e])
2021-11-03 10:45:38.838|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Actual SQL: ds_0 ::: insert into `t_pipeline_info` (`PIPELINE_ID`, `PROJECT_ID`, `PIPELINE_NAME`, `PIPELINE_DESC`) values (?, ?, ?, ?) on duplicate key update `t_pipeline_info`.`PIPELINE_DESC` = ? ::: [p-17bd8ac584be4d228c9ad2d15e9d169117bd8ac584be4d228c9ad2d15e9d169117bd8ac584be4d228c9ad2d15e9d1691, devops-test, bnmvvv1234, dfdf89089808, dfdf89089808]

**Native SQL directly inserts an error**
![企业微信截图_16359070273966](https://user-images.githubusercontent.com/5268164/140003658-61fa2dc9-9484-46b7-a9f0-d060cfff0b39.png)

My configuration is as follows：

    private fun dataSourceMap(config: DataSourceProperties): Map<String, DataSource> {
        val dataSourceMap: MutableMap<String, DataSource> = mutableMapOf()
        val dataSourceConfigs = config.dataSourceConfigs
        dataSourceConfigs.forEachIndexed { index, dataSourceConfig ->
            val dataSourceName = "$DATA_SOURCE_NAME_PREFIX$index"
            dataSourceMap[dataSourceName] = createHikariDataSource(
                datasourcePoolName = dataSourceName,
                datasourceUrl = dataSourceConfig.url,
                datasourceUsername = dataSourceConfig.username,
                datasourcePassword = dataSourceConfig.password,
                datasourceInitSql = dataSourceConfig.initSql,
                datasouceLeakDetectionThreshold = dataSourceConfig.leakDetectionThreshold
            )
        }
        return dataSourceMap
    }

    private fun createHikariDataSource(
        datasourcePoolName: String,
        datasourceUrl: String,
        datasourceUsername: String,
        datasourcePassword: String,
        datasourceInitSql: String?,
        datasouceLeakDetectionThreshold: Long
    ): HikariDataSource {
        return HikariDataSource().apply {
            poolName = datasourcePoolName
            jdbcUrl = datasourceUrl
            username = datasourceUsername
            password = datasourcePassword
            driverClassName = Driver::class.java.name
            minimumIdle = 10
            maximumPoolSize = 50
            idleTimeout = 60000
            connectionInitSql = datasourceInitSql
            leakDetectionThreshold = datasouceLeakDetectionThreshold
        }
    }

    @Bean
    fun shardingDataSource(config: DataSourceProperties): DataSource {
        val shardingRuleConfig = ShardingRuleConfiguration()
        // 设置表的路由规则
        val tableRuleConfigs = shardingRuleConfig.tables
        val dataSourceSize = config.dataSourceConfigs.size
        tableRuleConfigs.add(getTableRuleConfiguration("t_pipeline_info", dataSourceSize))
        tableRuleConfigs.add(getTableRuleConfiguration("t_pipeline_user", dataSourceSize))
        val dbShardingAlgorithmrProps = Properties()
        dbShardingAlgorithmrProps.setProperty("strategy", "STANDARD")
        dbShardingAlgorithmrProps.setProperty("algorithmClassName",
            "com.xxx.devops.sharding.configuration.BkDatabaseShardingAlgorithm")
        shardingRuleConfig.shardingAlgorithms["bkDatabaseShardingAlgorithm"] =
            ShardingSphereAlgorithmConfiguration("CLASS_BASED", dbShardingAlgorithmrProps)

        shardingRuleConfig.defaultTableShardingStrategy = NoneShardingStrategyConfiguration()
        shardingRuleConfig.defaultDatabaseShardingStrategy =
            StandardShardingStrategyConfiguration(PROJECT_ID_FIELD, "bkProcessDatabaseShardingAlgorithm")
        val properties = Properties()
        // 是否打印SQL解析和改写日志
        properties.setProperty("sql-show", "true")
        return ShardingSphereDataSourceFactory.createDataSource(
            dataSourceMap(config),
            listOf(shardingRuleConfig),
            properties
        )
    }

    fun getTableRuleConfiguration(
        tableName: String,
        dataSourceSize: Int,
        specifyDataSourceName: String? = null
    ): ShardingTableRuleConfiguration? {
        // 生成实际节点规则
        val actualDataNodes = if (specifyDataSourceName != null) {
            "$specifyDataSourceName.$tableName"
        } else {
            val lastIndex = dataSourceSize - 1
            "$DATA_SOURCE_NAME_PREFIX\${0..$lastIndex}.$tableName"
        }
        val tableRuleConfig = ShardingTableRuleConfiguration(tableName, actualDataNodes)
        tableRuleConfig.tableShardingStrategy = NoneShardingStrategyConfiguration()
        tableRuleConfig.databaseShardingStrategy =
            StandardShardingStrategyConfiguration(PROJECT_ID_FIELD, "bkDatabaseShardingAlgorithm")
        return tableRuleConfig
    }

**My table structure is as follows：**

CREATE TABLE `t_pipeline_info` (
  `PIPELINE_ID` varchar(34) NOT NULL DEFAULT,
  `PROJECT_ID` varchar(64) NOT NULL COMMENT,
  `PIPELINE_NAME` varchar(255) NOT NULL,
  `PIPELINE_DESC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PIPELINE_ID`),
  UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`),
  KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by carlyin0801** [comment]
@strongduanmu Please help me look at this problem.

**Comment by strongduanmu** [comment]
@carlyin0801 Thank you for your feedback, I will check it later.

**Comment by carlyin0801** [comment]
@strongduanmu Thank you, this problem is very important. If it is confirmed that the problem can be solved in the latest official version, we plan to use shardingsphere in the production environment

**Comment by strongduanmu** [comment]
@carlyin0801 Can you try the master branch? I think this bug has been fixed. You can refer #12936 for more detailed info.

**Comment by carlyin0801** [comment]
@strongduanmu Thank you, How can I use the package of the master branch?

**Comment by strongduanmu** [comment]
@carlyin0801 You can download here——http://117.48.121.24:8080/.

**Comment by carlyin0801** [comment]
@strongduanmu thanks,I imported all these packages into the project and executed the logic to report errors.

![企业微信截图_16360178047046](https://user-images.githubusercontent.com/5268164/140291259-795c1570-2a0b-4ade-9a9d-5d125bfb11c8.png)
![企业微信截图_1636017819629](https://user-images.githubusercontent.com/5268164/140291276-a3c6a771-e78b-405f-8e3b-d8ce12e3492a.png)

**Comment by strongduanmu** [comment]
@carlyin0801 Thank you for your test, The 5.0.0 GA version is currently being released and will be released after the vote is passed.

**Comment by strongduanmu** [comment]
I will close this issue first. If there are other issues using the 5.0.0 GA version later, please submit your issue feedback, thank you.

**Comment by CheerwayRen** [comment]
> **The shardingsphere version is 5.0.0.beta,database is mysql.**
> 
> **shardingsphere does not report errors：** 2021-11-03 10:45:38.836|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Logic SQL: insert into `t_pipeline_info` (`PIPELINE_ID`, `PROJECT_ID`, `PIPELINE_NAME`, `PIPELINE_DESC`) values (?, ?, ?, ?) on duplicate key update `t_pipeline_info`.`PIPELINE_DESC` = ? 2021-11-03 10:45:38.837|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] SQLStatement: MySQLInsertStatement(setAssignment=Optional.empty, onDuplicateKeyColumns=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.OnDuplicateKeyColumnsSegment@7b11b60e]) 2021-11-03 10:45:38.838|biz-e3424a198605469bb31139f9767fe21b||SQLLogger.java|74|INFO||||||[XNIO-1 task-1] Actual SQL: ds_0 ::: insert into `t_pipeline_info` (`PIPELINE_ID`, `PROJECT_ID`, `PIPELINE_NAME`, `PIPELINE_DESC`) values (?, ?, ?, ?) on duplicate key update `t_pipeline_info`.`PIPELINE_DESC` = ? ::: [p-17bd8ac584be4d228c9ad2d15e9d169117bd8ac584be4d228c9ad2d15e9d169117bd8ac584be4d228c9ad2d15e9d1691, devops-test, bnmvvv1234, dfdf89089808, dfdf89089808]
> 
> **Native SQL directly inserts an error** ![企业微信截图_16359070273966](https://user-images.githubusercontent.com/5268164/140003658-61fa2dc9-9484-46b7-a9f0-d060cfff0b39.png)
> 
> My configuration is as follows：
> 
> ```
> private fun dataSourceMap(config: DataSourceProperties): Map<String, DataSource> {
>     val dataSourceMap: MutableMap<String, DataSource> = mutableMapOf()
>     val dataSourceConfigs = config.dataSourceConfigs
>     dataSourceConfigs.forEachIndexed { index, dataSourceConfig ->
>         val dataSourceName = "$DATA_SOURCE_NAME_PREFIX$index"
>         dataSourceMap[dataSourceName] = createHikariDataSource(
>             datasourcePoolName = dataSourceName,
>             datasourceUrl = dataSourceConfig.url,
>             datasourceUsername = dataSourceConfig.username,
>             datasourcePassword = dataSourceConfig.password,
>             datasourceInitSql = dataSourceConfig.initSql,
>             datasouceLeakDetectionThreshold = dataSourceConfig.leakDetectionThreshold
>         )
>     }
>     return dataSourceMap
> }
> 
> private fun createHikariDataSource(
>     datasourcePoolName: String,
>     datasourceUrl: String,
>     datasourceUsername: String,
>     datasourcePassword: String,
>     datasourceInitSql: String?,
>     datasouceLeakDetectionThreshold: Long
> ): HikariDataSource {
>     return HikariDataSource().apply {
>         poolName = datasourcePoolName
>         jdbcUrl = datasourceUrl
>         username = datasourceUsername
>         password = datasourcePassword
>         driverClassName = Driver::class.java.name
>         minimumIdle = 10
>         maximumPoolSize = 50
>         idleTimeout = 60000
>         connectionInitSql = datasourceInitSql
>         leakDetectionThreshold = datasouceLeakDetectionThreshold
>     }
> }
> 
> @Bean
> fun shardingDataSource(config: DataSourceProperties): DataSource {
>     val shardingRuleConfig = ShardingRuleConfiguration()
>     // 设置表的路由规则
>     val tableRuleConfigs = shardingRuleConfig.tables
>     val dataSourceSize = config.dataSourceConfigs.size
>     tableRuleConfigs.add(getTableRuleConfiguration("t_pipeline_info", dataSourceSize))
>     tableRuleConfigs.add(getTableRuleConfiguration("t_pipeline_user", dataSourceSize))
>     val dbShardingAlgorithmrProps = Properties()
>     dbShardingAlgorithmrProps.setProperty("strategy", "STANDARD")
>     dbShardingAlgorithmrProps.setProperty("algorithmClassName",
>         "com.xxx.devops.sharding.configuration.BkDatabaseShardingAlgorithm")
>     shardingRuleConfig.shardingAlgorithms["bkDatabaseShardingAlgorithm"] =
>         ShardingSphereAlgorithmConfiguration("CLASS_BASED", dbShardingAlgorithmrProps)
> 
>     shardingRuleConfig.defaultTableShardingStrategy = NoneShardingStrategyConfiguration()
>     shardingRuleConfig.defaultDatabaseShardingStrategy =
>         StandardShardingStrategyConfiguration(PROJECT_ID_FIELD, "bkProcessDatabaseShardingAlgorithm")
>     val properties = Properties()
>     // 是否打印SQL解析和改写日志
>     properties.setProperty("sql-show", "true")
>     return ShardingSphereDataSourceFactory.createDataSource(
>         dataSourceMap(config),
>         listOf(shardingRuleConfig),
>         properties
>     )
> }
> 
> fun getTableRuleConfiguration(
>     tableName: String,
>     dataSourceSize: Int,
>     specifyDataSourceName: String? = null
> ): ShardingTableRuleConfiguration? {
>     // 生成实际节点规则
>     val actualDataNodes = if (specifyDataSourceName != null) {
>         "$specifyDataSourceName.$tableName"
>     } else {
>         val lastIndex = dataSourceSize - 1
>         "$DATA_SOURCE_NAME_PREFIX\${0..$lastIndex}.$tableName"
>     }
>     val tableRuleConfig = ShardingTableRuleConfiguration(tableName, actualDataNodes)
>     tableRuleConfig.tableShardingStrategy = NoneShardingStrategyConfiguration()
>     tableRuleConfig.databaseShardingStrategy =
>         StandardShardingStrategyConfiguration(PROJECT_ID_FIELD, "bkDatabaseShardingAlgorithm")
>     return tableRuleConfig
> }
> ```
> 
> **My table structure is as follows：**
> 
> CREATE TABLE `t_pipeline_info` ( `PIPELINE_ID` varchar(34) NOT NULL DEFAULT, `PROJECT_ID` varchar(64) NOT NULL COMMENT, `PIPELINE_NAME` varchar(255) NOT NULL, `PIPELINE_DESC` varchar(255) DEFAULT NULL, PRIMARY KEY (`PIPELINE_ID`), UNIQUE KEY `T_PIPELINE_INFO_NAME_uindex` (`PROJECT_ID`,`PIPELINE_NAME`), KEY `PROJECT_ID` (`PROJECT_ID`,`PIPELINE_ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

How do you configure and display the actual SQL，I configured sql-show, but it didn't work
