### ISSUE TITLE
How to get 5.0.0 release package

### ISSUE THREAD

**Issue by syz521** [apache/shardingsphere#13438]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
@syz521 The 5.0.0  is in the community voting stage and can be downloaded on the official website after it is released.

**Comment by Jenyow** [comment]
> @syz521 The 5.0.0 is in the community voting stage and can be downloaded on the official website after it is released.

When does it end?

**Comment by summer9989** [comment]
same question

**Comment by syz521** [comment]
> 
> 
> same question

https://www.oschina.net/news/167991

**Comment by TeslaCN** [comment]
Hi @syz521 @Jenyow @summer9989 
You may download the latest ShardingSphere from https://shardingsphere.apache.org/document/current/en/downloads/ or Maven Central repository.
