### ISSUE TITLE
batch Update statement use case statement get shardingvalue error

### ISSUE THREAD

**Issue by 5661954** [apache/shardingsphere#13430]
### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

when i use  the batch update sql like next:
update test
     set a =case when id=? then ?
                        when id=? then ? end,
         b =case when id=? then ?
                         when id=? then ? end,
         c =case when id=? then ?
                      when id=? then ? end 
    where shard_id = ? AND id in (?, ?)

the parameters: 123832998204264448, ddab501493484145b23f1fefb5aadce0, 123824723966533632, d21eee1fa36a45a88b75c7ddce899918, 123832998204264448, 123832999030517760, 123824723966533632, 123824724314648576, 123832998204264448, BP320276354, 123824723966533632, BP320276352, 79ffca0e081a43f899486ef67148db77, 123832998204264448, 123824723966533632

the sharding column shard_id=79ffca0e081a43f899486ef67148db77 but actualy the sharding column value
is 123832998204264448

### Reason analyze (If you can)
the index of shard column pos should be 12,but the parse engine get the error index is 0

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
@strongduanmu OK, I'll check it.

**Comment by tuichenchuxin** [comment]
@5661954 I have tested this issue on master branch, It's ok now.
Can you try 5.x version, we have optimized a lot.

**Comment by tuichenchuxin** [comment]
Closed due to long time no reply.
