### ISSUE TITLE
Why the equal RouteMapper is duplicated in one execution context?

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#13437]
https://github.com/apache/shardingsphere/blob/1ea6d35c6a2deacb6e148158c6ac4adc6c60ef38/shardingsphere-infra/shardingsphere-infra-executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/context/ExecutionContextBuilder.java#L73-L78

![image](https://user-images.githubusercontent.com/20503072/140038642-acffc9de-73b9-4733-b65b-a901c2734c05.png)

They are equal but not the same instances. Could we reuse the instances?

**Comment by terrymanu** [comment]
The proposal of spilt ExecutionContext and RouteContext is decouple these 2 modules, keep one module has independent context.

I am not sure merge or not, the class ExecutionContext and RouteContext contains same fields, but still contains different fields, it can not reuse the whole class.

**Comment by TeslaCN** [comment]
> The proposal of spilt ExecutionContext and RouteContext is decouple these 2 modules, keep one module has independent context.
> 
> I am not sure merge or not, the class ExecutionContext and RouteContext contains same fields, but still contains different fields, it can not reuse the whole class.

Thanks for your answer!
