### ISSUE TITLE
Will sharding-proxy delete the schema node affect the use of the function?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#13448]
![image](https://user-images.githubusercontent.com/45256940/140250239-0e742547-d596-416e-92e2-5116a83e8cf9.png)

**Comment by terrymanu** [comment]
I can get your point, could you describe you expectation?

**Comment by marker-wu** [comment]
> I can get your point, could you describe you expectation?

There are more than 800 tables in a database, and the number of rows in yaml is more than 100,000. Because of the operation of the schema, the ZK operation is timed out.

**Comment by menghaoranss** [comment]
> > I can get your point, could you describe you expectation?
> 
> There are more than 800 tables in a database, and the number of rows in yaml is more than 100,000. Because of the operation of the schema, the ZK operation is timed out.

@marker-wu The schema has been split into multiple nodes by table in the upcoming 5.1.0 version, you can try again with master branch now.

**Comment by menghaoranss** [comment]
Look forward to your next feedback.
