### ISSUE TITLE
When will this project start to support jdbc4.2？

### ISSUE THREAD

**Issue by pandatop** [apache/shardingsphere#13453]
When will the project support jdbc4.2?
The mybatis vrsion I use is 3.5.7, and the sharding-jdbc version is 4.1.1. The enumeration and LocalDateTime type fields in the entity class have to write their own processors. And sharding-jdbc5.0.0-beta still does not support jdbc4.2

**Comment by linghengqian** [comment]
Uh, what are the features of `JDBC4.2` for `LocalDateTime` in JAVA? In `ShardingSphere-JDBC` and `ShardingSphere-Proxy` to `5.0.0-beta`, `LocalDateTime` is properly recognized by `CLASS_BASE` to custom sharding algorithms.

**Comment by pandatop** [comment]
> Uh, what are the features of `JDBC4.2` for `LocalDateTime` in JAVA? In `ShardingSphere-JDBC` and `ShardingSphere-Proxy` to `5.0.0-beta`, `LocalDateTime` is properly recognized by `CLASS_BASE` to custom sharding algorithms.

![image](https://user-images.githubusercontent.com/86768666/140266047-b9483ba8-bc36-41ec-bb32-1d339fa9fdff.png)
![image](https://user-images.githubusercontent.com/86768666/140266117-e12e4e56-aec0-4c09-b997-28f16c1925f2.png)
![image](https://user-images.githubusercontent.com/86768666/140266253-458561f1-b49e-4596-a7d1-90ae23bbc9d6.png)

Because in mybatis 3.5.7 corresponding to the result of LocalDateTime or LocalDate type, the API of JDBC4.1 is called, but it is not supported in sharding-jdbc, and the method is final modified. Currently, only the processing of mybatis can be rewritten kind

**Comment by TeslaCN** [comment]
The version `4.1.1` is no longer maintained. Could you try the latest version?

**Comment by pandatop** [comment]
> The version `4.1.1` is no longer maintained. Could you try the latest version?

Yes, I read the code of 5.0.0-beta, it still doesn't support it

**Comment by pandatop** [comment]
> The version `4.1.1` is no longer maintained. Could you try the latest version?
At present, I have quoted the latest version, the problem has been solved, thank you for your reminder
