### ISSUE TITLE
When JSON appears， SQL parse has error

### ISSUE THREAD

**Issue by gooddr** [apache/shardingsphere#13465]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
tenant_id = 100001
### Actual behavior
tenant_id = 1
### Reason analyze (If you can)
json_extract(user.extend_field,'$.sk0') parse error 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
select user.id as user_id from tenant_user as user where  json_extract(user.extend_field,'$.sk0')=? and user.tenant_id=? and user.is_del=?    ::: [1, 100001, 0]
shardingColumn = tenant_id
### Example codes for reproduce this issue (such as a github link).
------1
shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new StandardShardingStrategyConfiguration("tenant_id",new DBPreciseShardingAlgorithm()));
------2
public class DatabasePreciseShardingAlgorithm implements PreciseShardingAlgorithm<Long> {
    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Long> shardingValue) {
        log.warn("tenant_id = {}", shardingValue);            
        return dataSource; 
    }

}

**Comment by strongduanmu** [comment]
Hi @gooddr, thank you for your feedback, can you try the latest version?

**Comment by gooddr** [comment]
> Hi @gooddr, thank you for your feedback, can you try the latest version?

ok.i will try. thanks.

**Comment by tuichenchuxin** [comment]
@strongduanmu I have tried this issue.It's supported now on 5.X
