### ISSUE TITLE
lower verion atomikos refreshXAConnect occurs connection leaks

### ISSUE THREAD

**Issue by wangeDear** [apache/shardingsphere#13471]
### Which version of ShardingSphere did you use?
5.0.0-RC

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Actual behavior
connection leaks

### Reason analyze (If you can)
lower verion atomikos bug

atomikos issues：
https://github.com/atomikos/transactions-essentials/issues/152

**Comment by sandynz** [comment]
Thanks for your feedback. Since you've mentioned it in #13434, we could discuss it there.
