### ISSUE TITLE
Consider merge two FunctionSegements with the same name

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13483]
## Feature Request

Currently, there are two FunctionSegments with the same name in the parsing module. We need to investigate whether they have the same meaning. If possible, I suggest combining them into one FunctionSegment. If they have different meanings, we should consider using different names.

![image](https://user-images.githubusercontent.com/10829171/140603041-59086c74-fea9-49cc-8890-64c68d57329e.png)

### Is your feature request related to a problem?

No

**Comment by tuichenchuxin** [comment]
I want to check it.
