### ISSUE TITLE
getting data from resultset occur index out of bounds 

### ISSUE THREAD

**Issue by yixianluo** [apache/shardingsphere#13480]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-snapshot

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
sql: select avg(id) from (select id from tb_student where sid%2=0 limit 10) a
tb_student has two table

rule is sharding and encrypt

this sql will cause exception: indexOutOfBoundsException in class EncryptAlgorithmMetaData.findEncryptor()

### Reason analyze (If you can)

ShardingSphereMetaData function hasSelectExpandProjections() return false as sql has subqury

**Comment by strongduanmu** [comment]
@yixianluo Thank you for your feedback, I will check it.
