### ISSUE TITLE
DistSQL error message is wrong.

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#13494]
### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Actual behavior

![image](https://user-images.githubusercontent.com/12792261/140701509-8e146875-10c3-40b1-ad0a-a21a8160ac44.png)

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/12792261/140701046-06289d38-72af-480c-97e7-dc56e08b462f.png)

I want to fix it.

**Comment by RaigorJiang** [comment]
@yx9o 
Thanks a lot.

**Comment by yx9o** [comment]
Fixed in #13507 .
