### ISSUE TITLE
sharding-proxy pool performance

### ISSUE THREAD

**Issue by syz521** [apache/shardingsphere#13497]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by syz521** [comment]
Is there an official performance test for sharding-proxy 5.0. I use the beta version to test the performance. The read-write separation is configured. The read performance is only 1 / 5 of that of the direct database

**Comment by TeslaCN** [comment]
Hi @syz521 
How do you test the performance?

**Comment by TeslaCN** [comment]
I found this issue is duplicated, could you continue discussing in #10626?

**Comment by syz521** [comment]
> 
> 
> I found this issue is duplicated, could you continue discussing in #10626?
Yes

**Comment by syz521** [comment]
duplicate
