### ISSUE TITLE
When executing SQL, the fields do not match the database, and no exception is thrown

### ISSUE THREAD

**Issue by yxiaozhou** [apache/shardingsphere#13498]
After checking the document, it is found that there is no description of the problem;

Using mybatis and MySQL

For example, the fields in the database are ID and phone_ Number, area, the SQL actually inserted is:
insert into personal_phone_2
( phone_number,
area1 , id)
values (?, ?, ?) ::: [123, 111, 1457646753489616897]；
Obviously, the fields do not match, but the code does not throw an exception

The code screenshot is as follows:
![image](https://user-images.githubusercontent.com/33828903/140722326-045e8493-6028-403d-9b65-5a1e34413a86.png)
The database fields are as follows:
![image](https://user-images.githubusercontent.com/33828903/140722358-152a1ee2-2dd5-4af8-9b19-e3a0b2a68ccb.png)

**Comment by yxiaozhou** [comment]
After checking the document, it is found that there is no description of the problem;

Using mybatis and MySQL

For example, the fields in the database are ID and phone_ Number, area, the SQL actually inserted is:
insert into personal_phone_2
( phone_number,
area1 , id)
values (?, ?, ?) ::: [123, 111, 1457646753489616897]；
Obviously, the fields do not match, but the code does not throw an exception

The code screenshot is as follows:
![image](https://user-images.githubusercontent.com/33828903/140722953-d655b824-6069-4351-8a32-dd9a1f79e145.png)

The database fields are as follows:

![image](https://user-images.githubusercontent.com/33828903/140722984-364a23f1-3af4-46a5-9aae-a6445c00240f.png)

**Comment by tuichenchuxin** [comment]
@yxiaozhou which version have you used? can you offer an demo for me to have a check?

**Comment by yxiaozhou** [comment]
> @yxiaozhou which version have you used? can you offer an demo for me to have a check?

5.0.0-beta

**Comment by yxiaozhou** [comment]
> @yxiaozhou which version have you used? can you offer an demo for me to have a check?
https://github.com/yxiaozhou/demo-orm-mybatis

↑ This is my demo for this question;
Run the test method addPhone in SpringBootDemoOrmMybatisApplicationTests.java

**Comment by yxiaozhou** [comment]
> > @yxiaozhou which version have you used? can you offer an demo for me to have a check?
> > https://github.com/yxiaozhou/demo-orm-mybatis
> 
> ↑ This is my demo for this question; Run the test method addPhone in SpringBootDemoOrmMybatisApplicationTests.java
@tuichenchuxin

**Comment by RaigorJiang** [comment]
Hi @yxiaozhou 
This issue has been fixed in master branch, please refer to #10138, #10844.

**Comment by yxiaozhou** [comment]
> Hi @yxiaozhou This issue has been fixed in master branch, please refer to #10138, #10844.

@RaigorJiang    which version i can use now?  i saw shardingsphere-jdbc-core:5.0.5  released at 2 nov

**Comment by RaigorJiang** [comment]
@yxiaozhou 
5.0.0-GA will release soon.

**Comment by yxiaozhou** [comment]
> @yxiaozhou 5.0.0-GA will release soon. https://mp.weixin.qq.com/s/nPs5iJRf1i2azS6dk2q-ag

Nice！
