### ISSUE TITLE
The data source refresh did not close the link of the old data source and threw an exception. How can we deal with this problem? If there is a good scheme, please give me some advice ，thanks

### ISSUE THREAD

**Issue by liangxianjin** [apache/shardingsphere#13501]
There are 30 connections, two instances in total
Problem Description:
Multiple instances refresh the data source, reload the data source, and create a link. Before this process, first check the old data source and new data source, including fragment configuration; CLose new  and old data sources have interactive data source links ，Use new data source list
Before refresh
There are 60 connections

After refresh
There are 90 connections 
org.apache.shardingsphere.shardingjdbc.jdbc.adapter.AbstractDataSourceAdapter#close(java.util.Collection<java.lang.String>)
![image](https://user-images.githubusercontent.com/45254883/140731860-4bbe328c-3456-489a-9950-e2c47b2e8a36.png)
Database link exception after closing

**Comment by tuichenchuxin** [comment]
@liangxianjin which version have you used?

**Comment by liangxianjin** [comment]
> @liangxianjin which version have you used?

   Maven coordinate:  <sharding-sphere.version>4.1.1</sharding-sphere.version>
To refresh a multi instance data source, you need to close the connection between the duplicate data source lists in the old data source list and the new data source list

![Uploading image.png…]()

**Comment by liangxianjin** [comment]
> @liangxianjin which version have you used?

   Maven coordinate:  <sharding-sphere.version>4.1.1</sharding-sphere.version>
To refresh a multi instance data source, you need to close the connection between the duplicate data source lists in the old data source list and the new data source list

![image](https://user-images.githubusercontent.com/45254883/140849676-d0dfbbd3-612e-4d63-8181-5d1c2a2359b2.png)

**Comment by tuichenchuxin** [comment]
@liangxianjin Thank you for your feedback. Can you help to check if this problem is exist in 5.0.0 ? Because 4.1.1 is a long time ago version.

**Comment by liangxianjin** [comment]
> @liangxianjin Thank you for your feedback. Can you help to check if this problem is exist in 5.0.0 ? Because 4.1.1 is a long time ago version. We'll prefer to fix bugs in 5.0.0 preferentially.
Well, OK.
thank

**Comment by liangxianjin** [comment]
Now, does 5.0.0 support case... When statements? Write your own preprocessing and splice SQL
