### ISSUE TITLE
[Discussion] Consider merge QueryAssistedEncryptAlgorithm and EncryptAlgorithm into one

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#13508]
## Feature Request

For now:
1、We see that there are two interfaces QueryAssistedEncryptAlgorithm and EncryptAlgorithm, QueryAssistedEncryptAlgorithm inherit from EncryptAlgorithm and provider method queryAssistedEncrypt for QueryAssist.
2、We see 5 fields in EncryptColumnRuleConfiguration but only one encryptorName can be configed with both QueryAssistedEncryptAlgorithm and EncryptAlgorithm, QueryAssistedEncryptAlgorithm was configed usually.
3、We see findEncryptor in EncryptRule.getEncryptValues and EncryptRule.getEncryptAssistedQueryValues, the methods in QueryAssistedEncryptAlgorithm only invoked during encrypt/queryAssistedEncrypt and decrypt, thinking of the above 2.

That's a bad smell, so I consider merge QueryAssistedEncryptAlgorithm and EncryptAlgorithm into one called EncryptAlgorithm with 3 methods: encrypt, queryAssistedEncrypt and decrypt. Would you please suggest on this? @strongduanmu

**Comment by cheese8** [comment]
The first solution is:
merge QueryAssistedEncryptAlgorithm and EncryptAlgorithm into one called EncryptAlgorithm with 3 methods: encrypt, queryAssistedEncrypt and decrypt.

The second solution is:
cut off the inherit relationship on QueryAssistedEncryptAlgorithm and EncryptAlgorithm, and add the 6th field named queryAssistedEncryptorName in EncryptColumnRuleConfiguration.

Which one do you prefer? @strongduanmu

**Comment by strongduanmu** [comment]
@cheese8 Considering that the 5.0.0 GA version has just been released, it is not suitable to make changes to the API at this time, I think this suggestion can be put into the future 6.x version.

**Comment by cheese8** [comment]
Please assign it to me, thanks.
