### ISSUE TITLE
Redis ShardingKey Generator and  ShardingDataSource  error

### ISSUE THREAD

**Issue by liangxianjin** [apache/shardingsphere#13515]
![image](https://user-images.githubusercontent.com/45254883/140889590-13020f3c-0d60-40e3-b9a6-0f6409542ddc.png)
![image](https://user-images.githubusercontent.com/45254883/140889610-c90a80bf-8996-45a6-92b5-bafdacce1efb.png)

maven 4.1.1 change 5.0.0   error

**Comment by tuichenchuxin** [comment]
Thank you for trying to use 5.0.0. 5.0.0 have some api change, now it has been become pluggable architecture. Future version api changes will be small.

**Comment by liangxianjin** [comment]
> Thank you for trying to use 5.0.0. 5.0.0 have some api change, now it has been become pluggable architecture. Future version api changes will be small.
#13501  
you are welcome

 Do we have a good solution to this problem

**Comment by tuichenchuxin** [comment]
Currently it can be configured through distSql to reduce configuration changes, but currently only proxy is supported. The insensitivity upgrade is currently still advancing.

**Comment by liangxianjin** [comment]
well. The key is that the production environment is also in use. We are want to switch data sources and hot refresh

**Comment by liangxianjin** [comment]
> Currently it can be configured through distSql to reduce configuration changes, but currently only proxy is supported. The insensitivity upgrade is currently still advancing.

well. The key is that the production environment is also in use. We are want to switch data sources and hot refresh

**Comment by tuichenchuxin** [comment]
;)
