### ISSUE TITLE
Introduce Maven Flatten Plugin for project examples

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#13512]
### Is your feature request related to a problem?
There are too many modules in examples and we have to update example versions in every example `pom.xml` during project release, which is tedious to maintain.

### Describe the feature you would like.

Using `maven-flatten-plugin` in examples and replace version with variable in `pom.xml`.

**Comment by Swastyy** [comment]
Hi @TeslaCN Please assign this to me.

**Comment by TeslaCN** [comment]
> Hi @TeslaCN Please assign this to me.

@Swastyy Welcome!
