### ISSUE TITLE
About batch insert operation in sharding-jdbc

### ISSUE THREAD

**Issue by fwnan** [apache/shardingsphere#13529]
Currently, there are a lot of SQL batch inserts in our business code, but the new version of ABC does not support batch keywords, such as union all, so there are two problems:
1. Will batch operations of mysql, Oracle or other databases be supported in the future?
2. In the current 5.x version, it is possible to operate SQL without using sharding-JDBC agent.
Looking forward to replyIn the future, will you consider a syntax that supports bulk inserts?

**Comment by tuichenchuxin** [comment]
@fwnan What's the meaning of batch sql?
`union` or ```insert into ...;insert into ...;```
We'll support completely support `union`, `Batch insert` may be cost a bit longer time, have not a plan yet.
And What is the scenario where you don't need sharding-jdbc? Why not directly jdbc.

**Comment by terrymanu** [comment]
No response

**Comment by terrymanu** [comment]
I just close the issue because of no feedback for long time.
