### ISSUE TITLE
NullPointerException when using shardingjdbc5.0.0 and flyway

### ISSUE THREAD

**Issue by makexiao113** [apache/shardingsphere#13526]
my yaml is this：

···

spring:
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/membership
        username: membership
        password: membership
    mode:
      type: Memory
    schema:
      name: membership

···

when i run my project，flyway  throw NullPointerException when init itemself and get cachedDatabaseMetaData in ShardingSphereDatabaseMetaData，i debug and found shardingjdbc  constructor org\apache\shardingsphere\driver\jdbc\core\datasource\metadata\ShardingSphereDatabaseMetaData  super class AdaptedDatabaseMetaData.cachedDatabaseMetaData   is null，what can i do to make  cachedDatabaseMetaData  has something？

thanks

**Comment by tuichenchuxin** [comment]
@m350058411 Maybe there is some config error? Can you offer me a demo?

**Comment by m350058411** [comment]
> @m350058411 Maybe there is some config error? Can you offer me a demo?
[spring.zip](https://github.com/apache/shardingsphere/files/7509552/spring.zip)
sure,thank you,waitting for your good news

**Comment by m350058411** [comment]
> @m350058411 Maybe there is some config error? Can you offer me a demo?

install parent before running membership

**Comment by makexiao113** [comment]
> @m350058411 Maybe there is some config error? Can you offer me a demo?

@tuichenchuxin   Have you received the demo?  I have uploaded demo in comments, thanks

**Comment by zjcnb** [comment]
@makexiao113 Hi bro, you must be set rule for your config.  you can set rule and try it again.

**Comment by FuckDoctors** [comment]
same here, but with liquibase

**Comment by makexiao113** [comment]
> @makexiao113 Hi bro, you must be set rule for your config. you can set rule and try it again.
> 
> By the way, i had download your demo

thanks，I'll try
