### ISSUE TITLE
Physical library plus table plus field

### ISSUE THREAD

**Issue by duansy123** [apache/shardingsphere#13527]
How to add tables and fields to the physical library to take effect directly without restarting sharding？

**Comment by tuichenchuxin** [comment]
I can’t understand your needs accurately, can you describe the scenario you need in detail?

**Comment by duansy123** [comment]
> I can’t understand your needs accurately, can you describe the scenario you need in detail?

So we are using version 5.0.0-alpha
Then we found that sharding always reports an error every time a table or field is added to mysql
The error message is as follows

![image](https://user-images.githubusercontent.com/38459049/141045826-5b110ed7-33aa-423c-9105-02526bb130b5.png)



But when I restarted sharding and then query or insert again, there is no problem.
I hope to be able to add fields or tables to mysql without restarting sharding

**Comment by tuichenchuxin** [comment]
@duansy123 Do you add tables through sharding or directly through mysql? If you add table directlty through mysql then sharding will not get these tables meta data.

**Comment by duansy123** [comment]
> @duansy123 Do you add tables through sharding or directly through mysql? If you add table directlty through mysql then sharding will not get these tables meta data.

I am adding fields and tables directly through mysql. Do you mean that only tables and field shading added through sharding can take effect directly without restarting? I have seen from the Internet that if the zookeeper is connected, the metadata can be modified dynamically, but the data in the table cannot be modified.

**Comment by menghaoranss** [comment]
> directly

@duansy123 if you change the metadata of tables through mysql, ShardingSphere and zookeeper couldn't  get its change now, unless restart ShardingSphere  or change them through ShardingSphere.

**Comment by duansy123** [comment]
> > directly
> 
> @duansy123 if you change the metadata of tables through mysql, ShardingSphere and zookeeper couldn't get its change now, unless restart ShardingSphere or change them through ShardingSphere.

Ok hope this can be optimized

**Comment by duansy123** [comment]
Ok hope this can be optimized

**Comment by terrymanu** [comment]
What is physical library?
