### ISSUE TITLE
MGRDatabaseDiscoveryType some methods need add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13534]
Hi community,

I found `shardingsphere-db-discovery-mgr` module need to add unit test. it 's task list :

- [ ] MGRDatabaseDiscoveryType.startPeriodicalUpdate()
- [ ] MGRDatabaseDiscoveryType.updateProperties()

**Comment by ShiFengCui** [comment]
assign me please

**Comment by strongduanmu** [comment]
@ShiFengCui Assigned.
