### ISSUE TITLE
Unable to build a new release version

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13549]
version：
  5.0.0-release

error：
![image](https://user-images.githubusercontent.com/45088781/141234037-072cf8a7-7729-436b-a04f-c1f9fd8274aa.png)
![image](https://user-images.githubusercontent.com/45088781/141234079-bde43b32-328c-4158-883c-6b16432a7d60.png)

**Comment by syz521** [comment]
same question. need a doc to help debug and build

**Comment by yx9o** [comment]
@CrackerSuperior Hi, you need to `install` first.
