### ISSUE TITLE
Is `ShardingSphere agent` built-in in `Proxy`?

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#13553]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

One question, does the ShardingSphere agent already exist in the ShardingSphere proxy, and how to disable it?

If the binary distribution package of `ShardingSphere-Proxy` does not include this component, I think the `APM INTEGRATION` part of the document can be changed to avoid ambiguity.

![image](https://user-images.githubusercontent.com/20187731/141273105-81bea5e0-5047-4b86-81c9-ef1bd7c5eb67.png)

**Comment by dachuan9e** [comment]
@linghengqian Yes, you'r right. Here it means the opentracing plugin in shardingsphere agent and skywalking agent cannot be used at same time.  Welcome you to do some contribution if you'd like.

**Comment by linghengqian** [comment]
> @linghengqian Yes, you'r right. Here it means the opentracing plugin in shardingsphere agent and skywalking agent cannot be used at same time. Welcome you to do some contribution if you'd like.

I'm sorry that my time schedule is not convenient for me to deal with it. Can you assign another Contributor to do this?

**Comment by penghuazhou** [comment]
Can I use open observability function?

![image](https://user-images.githubusercontent.com/13001038/141718857-07180e09-20c3-46af-81f3-d731aa294fc5.png)

**Comment by linghengqian** [comment]
@penghuazhou 
Hi, I am sorry that I have no experience in using `ShardingSphere Agent`. As far as I know, `skywalking` automatic probe, `OpenTracing` protocol and `OpenTelemetry` protocol are three unrelated APM implementations, and before `5.0. 0-beta`There is no issue that cannot use the APM function.
Because the documentation of the `master` branch is different from the documentation of the `5.0.0` branch, if you are a Chinese developer, I think you can go to https://shardingsphere.apache.org/document/5.0.0/cn/features/governance/observability/ Go find the answer.
Mention issues unrelated to the subject under unrelated issues, I think it is inconvenient for later searchers to retrieve. I think you can create an issue with `question` with `type`, attach the steps to reproduce the issue, and use The `markdown` syntax covers code blocks. I believe friends in the community who are familiar with `shardingsphere agent` will help you.

**Comment by penghuazhou** [comment]
thanks
