### ISSUE TITLE
shardinsphere-jdbc5.0.0 can't work with seataserver1.4.1

### ISSUE THREAD

**Issue by jmbkeyes** [apache/shardingsphere#13550]
## Bug Report

**For English only**, other languages will not accept.
Since 5.0.0 is released, I upgrade the shardingshphere-jdbc to 5.0.0 for my demo project(https://github.com/jmbkeyes/shardingsphere-jdbc-seata-demo.git), and then test the api with global seata transaction.
It seems that seata transaction doesn't triggered.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
Seata transaction should work as expected.
### Actual behavior
Seata transaction doesn't work
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. download the demo project.
2.  create database bocai_checkin2018, bocai_checkin2019,bocai_checkin2020, and then run the sql scripts in db folder.
3. start the project, you will see RM, TM register successfully in the console log.
4. call the api http://{ip}:9090/api/test/2 or http://{ip}:9090/api/test/tci,   there'll be no log like " i.seata.tm.api.DefaultGlobalTransaction : Begin new global transaction [172.19.176.1:8091:184011852433330176]"

### Example codes for reproduce this issue (such as a github link).
https://github.com/jmbkeyes/shardingsphere-jdbc-seata-demo.git

**Comment by zjcnb** [comment]
@jmbkeyes Thank you for your feedback, I will check this issue. @strongduanmu please assign me thx.

**Comment by strongduanmu** [comment]
@zjcnb Assigned.

**Comment by jmbkeyes** [comment]
not fix in 5.1.0
