### ISSUE TITLE
Add unit test for H2DataSourceMetaData.isInSameDatabaseInstance and DataSourceMetaData.isInSameDatabaseInstance

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#13558]
Hi community,

`H2DataSourceMetaData.isInSameDatabaseInstance` and `DataSourceMetaData.isInSameDatabaseInstance` was added recently, it need to add some unit tests for these methods, and verify the implementation of `isInSameDatabaseInstance`.

**Comment by ReyYang** [comment]
Can i take this ?. Thanks

**Comment by sandynz** [comment]
@ReyYang Welcome, I just assigned it to you.
