### ISSUE TITLE
By shardingsphere querying character_set_client sometimes for utf8mb4 and sometimes for latin1, our underlying MySQL table encoding is utf8mb4

### ISSUE THREAD

**Issue by metayx** [apache/shardingsphere#13563]
![image](https://user-images.githubusercontent.com/16127829/141406445-4161a8b1-858f-4416-9f8a-8f622e18f136.png)

**Comment by RaigorJiang** [comment]
Hi @metayx 
Are you using ShardingSphere-Proxy?
Here is a similar issue for your reference https://github.com/apache/shardingsphere/issues/13023.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
