### ISSUE TITLE
I get an error when I execute select * from table in proxy 5.0

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#13577]
I get an error when I execute select * from table in proxy 5.0
![image](https://user-images.githubusercontent.com/45256940/141448879-1455a255-3287-4334-a7c0-8df6d1b8f35b.png)

**Comment by menghaoranss** [comment]
How could it be reproduced?

**Comment by TeslaCN** [comment]
What is your mysql client version?

**Comment by marker-wu** [comment]
> What is your mysql client version?
mysql8

**Comment by TeslaCN** [comment]
Hi @marker-wu 
Could you provide some information to help us reproduce this issue? We cannot reproduce it these days.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
