### ISSUE TITLE
How to user local transaction in shardingsphere-proxy 5.0.0?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13575]
Can I user Local transaction like this in shardingshpere-proxy 5.0.0?

![image](https://user-images.githubusercontent.com/13001038/141447710-b63a5db5-2f16-4fa7-877b-7d312c4a9ab1.png)

**Comment by zjcnb** [comment]
@penghuazhou Hi, you needn't set Local. Because Local are ShardingSphere default transaction type.

**Comment by RaigorJiang** [comment]
You can change the type to LOCAL, or comment out the `!TRANSACTION` rule configuration, because LOCAL will be used by default.

**Comment by penghuazhou** [comment]
thanks

**Comment by penghuazhou** [comment]
@RaigorJiang, Why there have Atomikos logs when i config like below? Does shardingshpere-proxy use Atomikos to manage Local TRANSACTION?

![image](https://user-images.githubusercontent.com/13001038/141931901-a93ceddb-bf7b-4e12-87e7-a65422a3a541.png)


Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 2021-11-15 19:44:40.995 [main] o.a.s.p.i.i.AbstractBootstrapInitializer - Database name is PostgreSQL, version is 9.2.24
[INFO ] 2021-11-15 19:44:41.227 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy start success.
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 2021-11-15 19:48:02.450 [main] o.a.s.p.i.i.AbstractBootstrapInitializer - Database name is PostgreSQL, version is 9.2.24

**Comment by RaigorJiang** [comment]
Hi @penghuazhou 
Please check your `mode` configuration. If the registry is enabled and `overwrite` is false, then the registry configuration will be used to start the proxy instead of your local configuration file.

**Comment by penghuazhou** [comment]
@RaigorJiang, It alse have Atomikos logs, when I disabled registry.

![image](https://user-images.githubusercontent.com/13001038/141937452-bc250b54-2383-497b-aa10-17602e871ebd.png)

[WARN ] 2021-11-16 15:12:40.022 [main] c.a.icatch.provider.imp.AssemblerImp - Th
anks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactio
ns for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this
 message and receive FREE tips & advice
[WARN ] 2021-11-16 15:12:40.022 [main] c.a.icatch.provider.imp.AssemblerImp - Th
anks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactio
ns for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this
 message and receive FREE tips & advice
Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransact
ions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this
 message and receive FREE tips & advice

**Comment by RaigorJiang** [comment]
> @RaigorJiang, It alse have Atomikos logs, when I disabled registry.

OK, I will check it.

**Comment by RaigorJiang** [comment]
Hi @penghuazhou ,
Indeed, as you reported, the proxy loads Atomikos, but the actual transaction type used is not affected by this. 
You can execute the following statement to query the currently used transaction type:
```sql
mysql> show variable transaction_type;
+------------------+
| transaction_type |
+------------------+
| LOCAL |
+------------------+
1 row in set (0.01 sec)
```

**Comment by penghuazhou** [comment]
thanks very mush
