### ISSUE TITLE
Is sharding-jdbc support multi strategy for one table?

### ISSUE THREAD

**Issue by gaozhuo** [apache/shardingsphere#13572]
Is sharding-jdbc support multi sharding algorithm for one table?
eg：PreciseShardingAlgorithm for userId，HintShardingAlgorithm for orderId
I already sharding table by userId (PreciseShardingAlgorithm)，but i want to query by orderId (use HintManager)

**Comment by strongduanmu** [comment]
Hi @gaozhuo, ShardingSphere provides some general algorithms, and you can implement custom sharding algorithms according to your needs.

**Comment by RaigorJiang** [comment]
Hi @gaozhuo 
You can try to query the same actual table with different logical table names, so that you can configure different strategies for different logical tables.

**Comment by terrymanu** [comment]
I just close the issue because of no response anymore.
