### ISSUE TITLE
Creating hyperlinks

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#13581]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
See the image below for reference
![image](https://user-images.githubusercontent.com/64654203/141467017-cea220a0-fd21-4106-85a6-a22273f5ee27.png)

### Describe the feature you would like.
I want to add hyperlinks for documentation and readme. This look more better like we already have other hyperlinks the mailing list, github issues etc.

**Comment by Swastyy** [comment]
@RaigorJiang @tristaZero @strongduanmu If everyone feels it correct, then I'll do this. Thanks.

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Sorry, I didn't understand, which part of the content is to be hyperlinked? From the picture, the document already has a link.

**Comment by Swastyy** [comment]
> Hi @Swastyy Sorry, I didn't understand, which part of the content is to be hyperlinked? From the picture, the document already has a link.

First is after `For full documentation & more details, visit: ` 
and second is in Contribution section after `For guides on how to get started and setup your environment, contributor & committer guides, visit:`

**Comment by RaigorJiang** [comment]
@Swastyy 
Thank you, you are really careful 👍

**Comment by Swastyy** [comment]
> @Swastyy Thank you, you are really careful 👍

Thank you @RaigorJiang 😃
