### ISSUE TITLE
Support to validate whether the sharding rules of the binding tables are consistent

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13596]
## Feature Request

When user configures many sharding rules, and the sharding rules are inconsistent, it is easy to cause logical exceptions due to incorrect binding table settings. 

Therefore, we should consider adding a validate logic to verify the binding tables in the same group. The sharding rules of each table must be consistent, otherwise an exception will be thrown to remind the user to modify the configuration.

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

When the application is started, add logic to check the binding table rules. If the sharding rules in the same group are inconsistent, a clear exception message will be thrown to remind the user.

This issue is open to the community, if you are interested, please leave a message. If you have any questions, you can also contact me for help.

**Comment by cheese8** [comment]
assign me, thanks.

**Comment by strongduanmu** [comment]
@cheese8 Welcome, I just assign this issue to you.

**Comment by cheese8** [comment]
Any examples or related issues to show what is the incorrect binding table settings? @strongduanmu

**Comment by tuichenchuxin** [comment]
Fixed.
