### ISSUE TITLE
How can I get instance ip from etcd?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13604]
How can I get instance ip from etcd in shardingsphere-proxy? I want the etcd key name that I can exec "etcdctl get" to get.

**Comment by menghaoranss** [comment]
Get instance ip in shardingsphere-proxy?  Do you develop based on shardingsphere-proxy?

**Comment by penghuazhou** [comment]
> Get instance ip in shardingsphere-proxy? Do you develop based on shardingsphere-proxy?

I want to know which shardingsphere-proxy is work in shardingsphere-proxy cluster. Client will not use the shardingsphere-proxy when it crashdown.

**Comment by menghaoranss** [comment]
please refer to https://shardingsphere.apache.org/document/current/cn/reference/management/ , proxy nodes will be persisted to /status/compute_nodes/online

**Comment by penghuazhou** [comment]
@menghaoranss, But I can not get it, when i use ectd? I know how to get it when I use zookeeper.

![image](https://user-images.githubusercontent.com/13001038/141753276-b37af9be-3f0a-42a7-9a43-c17e243e25a6.png)

**Comment by menghaoranss** [comment]
@penghuazhou try to get all nodes prefixed with `/status/compute_nodes/online`

**Comment by penghuazhou** [comment]
@menghaoranss, I also can not get it.

![image](https://user-images.githubusercontent.com/13001038/141761821-1acf1c78-7756-489e-8314-127fa13d99a7.png)


![image](https://user-images.githubusercontent.com/13001038/141761321-2c2dbdbc-e039-4b7a-85a4-1138b6acad57.png)

**Comment by menghaoranss** [comment]
`etcdctl get --prefix governance_ds/status/compute_nodes/online` , `governance_ds ` is the namespace

**Comment by penghuazhou** [comment]
thanks
