### ISSUE TITLE
Include xsd of Spring namespace into release progress

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#13607]
xsd of Spring namespace is not in current release progress, release manager maybe forget copy them into official website.

It is better to enhance to create new version for each release, for example: rename `http://shardingsphere.apache.org/schema/shardingsphere/datasource/datasource.xsd` to `http://shardingsphere.apache.org/schema/shardingsphere/datasource/datasource-5.0.0.xsd`

And replace the newest xsd to `http://shardingsphere.apache.org/schema/shardingsphere/datasource/datasource.xsd`

**Comment by menghaoranss** [comment]
I will follow up.
