### ISSUE TITLE
can't compatible spring boot 2.x

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#13602]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Actual behavior

upgrade spring boot to 2.x, org.apache.shardingsphere.spring.boot.SpringBootStarterTest#assertRules can't run
![image](https://user-images.githubusercontent.com/16568907/141711909-59c3e053-dee4-468f-8153-26f9af7366c5.png)

### Reason analyze (If you can)

org.apache.shardingsphere.spring.boot.util.PropertyUtil#v2 can't worker well

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.  only need to upgrade the spring boot in shardingsphere to 2.0.0.RELEASE 
2. org.apache.shardingsphere.spring.boot.SpringBootStarterTest#assertRules

**Comment by strongduanmu** [comment]
@SirMin Thank you for your feedback, can you see if the underscore is causing the configuration load exception? #11242

**Comment by SirMin** [comment]
Similar problems.
spring boot 2.x properties key only contain alpha&numberic&'-'
checker is  `org.springframework.boot.context.properties.source.ConfigurationPropertyName`
![image](https://user-images.githubusercontent.com/16568907/141733487-7339aaaa-0c58-46a2-a52b-ed272c1eb1e8.png)

**Comment by terrymanu** [comment]
Any suggestion to resolve the problem?

**Comment by SirMin** [comment]
I think has two treatment methods
1. Camel case is not supported. But must tip message instead of NPE
2. In the springboot 2.x version, the Camel Case converted to - separated

**Comment by SirMin** [comment]
![image](https://user-images.githubusercontent.com/16568907/146745509-c87fb444-dc1d-49db-b052-8dd0a7f826f5.png)
org.springframework.boot.context.properties.bind.BeanPropertyName#toDashedForm(java.lang.String, int)
The way handles case in springboot 2.0.0.RELEASE.

**Comment by SirMin** [comment]
@terrymanu I will try to submit a pr
