### ISSUE TITLE
ShardingSphere 4.1.1版本GroupUp时，sql解析错误

### ISSUE THREAD

**Issue by geiyelui** [apache/shardingsphere#13606]
## Question

原sql，已模糊掉部分字段
select
a.id, a.createDate, a.remark, a.ackSn, a.alarmSource, a.alarmTime, a.alarmType, a.descr,
(case when a.attachmentCount = 0 then count(m.mediaitemid) else a.attachmentCount end) as
attachmentCount
from gpsalarm a
LEFT JOIN mediaitem m on a.plateNo = m.plateNo and a.alarmTime = m.sendTime
order by a.createDate desc
其中testA 为分表，正常状态下可以走sharding的sql解析，但是加上 Group By a.createDate 之后就报错

控制台显示报错信息
[https://images.gitee.com/uploads/images/2021/1115/115840_9375c7fc_5101220.png](url)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
