### ISSUE TITLE
How should I perform cross-database queries?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13612]
Version：
  master

![image](https://user-images.githubusercontent.com/45088781/141744268-6e6ee8c9-925c-44c3-8700-6770978ad23c.png)
As the documentation shows, do I need to configure something to use this feature or use "shardingSphere" as usual？

**Comment by strongduanmu** [comment]
@CrackerSuperior Considering that this feature is experimental, it is disabled by default. You can enable federation query by configuring `sql-federation-enabled = true`. 

For more information, you can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/props/).

**Comment by CrackerSuperior** [comment]
> @CrackerSuperior Considering that this feature is experimental, it is disabled by default. You can enable federation query by configuring `sql-federation-enabled = true`.
> 
> For more information, you can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/props/).

ok,thanks
