### ISSUE TITLE
Use the embedded H2 DB to implement the standalone mode

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#13618]
In the [standalone mode](https://shardingsphere.apache.org/document/current/en/concepts/mode/), it is not a good choice to use local files to persist metadata, because local files are not encrypted and can be modified at any time. Therefore, we consider using embedded h2 DB to support standalone mode.

The following steps are required:

1. Add new module `shardingsphere-standalone-mode-repository-h2` under `shardingsphere-standalone-mode-repository-provider`
2. Add class `H2Repository.java` to implement all the interfaces of `StandalonePersistRepository` 
3. Add necessary unit tests

**Comment by EAHITechnology** [comment]
Let me try.But I need some time to get acquainted~

**Comment by menghaoranss** [comment]
> Let me try.But I need some time to get acquainted~

welcome

**Comment by LeeGuoPing** [comment]
Could I have a try, brothers

**Comment by menghaoranss** [comment]
@EAHITechnology hi ,  any progress here?

**Comment by menghaoranss** [comment]
@EAHITechnology @LeeGuoPing thanks for your attention, and this task has passed for too long. I will suspend this issue now.
