### ISSUE TITLE
After inserting data, saveBatch is split into one insert instead of batch insert

### ISSUE THREAD

**Issue by xr2117** [apache/shardingsphere#13615]
shardingJDBC 5.0.0-alpha 

mybatis 3.1.1

The execution of the savebatch method is split into one save instead of a batch insert

**Comment by menghaoranss** [comment]
could you try with the 5.0.0 GA version , and provide your configurations and logic sql, actual sql printed in the log

**Comment by xr2117** [comment]
Mybatis savebatch method used



Print SQL

INSERT INTO internal_questions (
	pick_count,
	parent_id,
	is_choice,
	questions_type_id,
	questions_type_name,
	questions_type_detail_id,
	questions_type_detail_name,
	content,
	answer,
	line_number,
	option_a,
	option_b,
	difficulty_id,
	difficulty_name,
	is_charged,
	is_group_question,
	origin,
	upload_batch,
	examine_status,
	is_down,
	is_check,
	create_time,
	create_by,
	update_time,
	update_by,
	is_deleted 
)
VALUES
	(
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
	? 
	)

config:

spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
      names: ds1
      ds1:
        password: xxx
        url: xxx
        username: xxx
    rules:
      sharding:
        key-generators:
          snowflake:
            props:
              max-vibration-offset: 2048
              worker-id: 1
            type: SNOWFLAKE
        sharding-algorithms:
          tbstrategy:
            props:
              algorithm-expression: questions_$->{id % 2 + 1}
            type: INLINE
        tables:
          questions: 
            actual-data-nodes: ds1.questions_$->{1..2}
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
            table-strategy:
              standard:
                sharding-algorithm-name: tbstrategy
                sharding-column: id

**Comment by userkdg** [comment]
+1 
shardingshpere-proxy had batch CRUD Bug , too!

**Comment by terrymanu** [comment]
Please try to version 5.0.0.
