### ISSUE TITLE
sharding close old datasource has Exception

### ISSUE THREAD

**Issue by liangxianjin** [apache/shardingsphere#13631]
https://github.com/brettwooldridge/HikariCP/issues/1873#issue-1054349928

![image](https://user-images.githubusercontent.com/45254883/141882607-5dea256b-fc5d-4822-b361-592bdab65f35.png)

**Comment by menghaoranss** [comment]
@liangxianjin which version did you use, and how could it be reproduced？

**Comment by liangxianjin** [comment]
4.1.1version; 5.0.0 Relevant API changes， can't be changed after trying

**Comment by menghaoranss** [comment]
@liangxianjin I couldn't get your point, and there's no more exception info you provide, could you describe what help you want in only one issue?

**Comment by liangxianjin** [comment]
Sry. The data source refresh did not close the link of the old data source and threw an exception. How can we deal with this problem? If there is a good scheme, please give me some advice .

**Comment by liangxianjin** [comment]
> @liangxianjin I couldn't get your point, and there's no more exception info you provide, could you describe what help you want in only one issue?

Sry. The data source refresh did not close the link of the old data source and threw an exception. How can we deal with this problem? If there is a good scheme, please give me some advice .

**Comment by liangxianjin** [comment]
> @liangxianjin I couldn't get your point, and there's no more exception info you provide, could you describe what help you want in only one issue?

Sry. The data source refresh  close the link of the old data source and threw an exception. How can we deal with this problem? If there is a good scheme, please give me some advice . thanks

**Comment by terrymanu** [comment]
Sorry, I still cannot get your point, can you provide an example to reproduce it?

**Comment by terrymanu** [comment]
Closed because of no response
