### ISSUE TITLE
How to increase the speed of batch insert with sharding-jdbc？

### ISSUE THREAD

**Issue by walkmiss** [apache/shardingsphere#13648]
I usually use the batchUpdate method of the jdbcTemplate to speed up bulk data writes ，it does pretty good. But after my service import shardingjdbc to sharding，the batchUpdate method of jdbcTemplate becomes very slow, I realize that may be shardingjdbc divede the bulk sql, what can i do to increase the speed of batch insert with sharding-jdbc?

**Comment by tuichenchuxin** [comment]
@walkmiss which version have you used?

**Comment by terrymanu** [comment]
I just close the issue because of no response anymore.
