### ISSUE TITLE
sharding,sql in(xx,xx,xx,xx,xx,xx) query bug 

### ISSUE THREAD

**Issue by zymapp** [apache/shardingsphere#13646]
Found that the sharding on the in query support is not very friendly, will be half more queries, such as my user_id 1 is divided by the rules in library A table, user_id is divided by rules in the library On Table 2 of B, if you query with user_id in (1, 2), the shelling will perform select on table 1, 2, and table 1 and 2 of Library B, and perform select four times. According to the theory should only need to be executed once on the 1 table of library A and then on library B to perform a select on it, interrupt point discovery sub-library rule only once, sub-table rule will enter twice, in fact, sub-library rule also need to enter two breakpoints to be right

**Comment by strongduanmu** [comment]
@zymapp Can you describe this issue according to the bug issue template?

**Comment by terrymanu** [comment]
because of no response anymore, I just close this issue.
