### ISSUE TITLE
Refactor the MySQL DAL  showXXX statement‘s showLike & showWhereClause segment.

### ISSUE THREAD

**Issue by dongzl** [apache/shardingsphere#13650]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

Hi, shardingsphere community:

Now, some of MySQL DAL  showXXX statement have the same filter segment, for example:

- [x] SHOW FUNCTION STATUS
- [x] SHOW CHARACTER SET
- [x] SHOW COLLATION
- [x] SHOW COLUMNS
- [x] SHOW DATABASES
- [x] SHOW EVENTS
- [x] SHOW OPEN TABLES
- [x] SHOW PROCEDURE STATUS
- [x] SHOW STATUS
- [x] SHOW TABLE STATUS
- [x] SHOW TABLES
- [x] SHOW TRIGGERS
- [x] SHOW VARIABLES

```
SHOW PROCEDURE STATUS
    [LIKE 'pattern' | WHERE expr]
```
```
SHOW FUNCTION STATUS
    [LIKE 'pattern' | WHERE expr]
```

They have the same filter segment. But in the code , have the duplicate code, for example:

```
/**
 * MySQL show procedure status statement.
 */
@Setter
@ToString
public final class MySQLShowProcedureStatusStatement extends AbstractSQLStatement implements DALStatement, MySQLStatement {
    
    private ShowLikeSegment like;
    
    private WhereSegment where;
    
    /**
     * Get like segment.
     *
     * @return like segment
     */
    public Optional<ShowLikeSegment> getLike() {
        return Optional.ofNullable(like);
    }
    
    /**
     * Get where segment.
     *
     * @return where segment
     */
    public Optional<WhereSegment> getWhere() {
        return Optional.ofNullable(where);
    }
}
```

```
@Setter
@ToString
public final class MySQLShowFunctionStatusStatement extends AbstractSQLStatement implements DALStatement, MySQLStatement {
    
    private ShowLikeSegment like;
    
    private WhereSegment where;
    
    /**
     * Get like segment.
     *
     * @return like segment
     */
    public Optional<ShowLikeSegment> getLike() {
        return Optional.ofNullable(like);
    }
    
    /**
     * Get where segment.
     *
     * @return where segment
     */
    public Optional<WhereSegment> getWhere() {
        return Optional.ofNullable(where);
    }
}
```

I want to define a `ShowFilterSegment` class, and compose the `ShowLikeSegment` and `WhereSegment` into `ShowFilterSegment`，like this:

```
public class ShowFilterSegment implements SQLSegment {
    
    private final int startIndex;
    
    private final int stopIndex;
    
    private ShowLikeSegment like;
    
    private WhereSegment where;
}
```

```
@Setter
@ToString
public final class MySQLShowFunctionStatusStatement extends AbstractSQLStatement implements DALStatement, MySQLStatement {
    
    private ShowFilterSegment filter;
    
    /**
     * Get filter segment.
     *
     * @return filter segment
     */
    public Optional<ShowFilterSegment> getFilter() {
        return Optional.ofNullable(filter);
    }
}
```

Do you think this is a good idea? please give me some advices.

**Comment by strongduanmu** [comment]
@dongzl I think this solution is ok, it can effectively reduce duplication of code.

**Comment by dongzl** [comment]
> @dongzl I think this solution is ok, it can effectively reduce duplication of code.

@strongduanmu , Thank you for your replay, I will list the statement and refactor them.
