### ISSUE TITLE
Why is the actual executed SQL displayed in the "shardingShpere" log different from the actual SQL executed by MySQL itself?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13653]
version：
  master

shardingSphere log：
  ``` sql
[INFO ] 2021-11-17 10:55:12.901 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3
[INFO ] 2021-11-17 10:55:12.901 [Connection-4-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
[INFO ] 2021-11-17 10:55:12.902 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3
[INFO ] 2021-11-17 10:55:12.902 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3

```

MySQL log:

``` sql
 event_time: 2021-11-17 10:55:12.938037
   user_host: pcloud[pcloud] @ localhost [127.0.0.1]
   thread_id: 443
   server_id: 1
command_type: Query
    argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert5`
*************************** 9. row ***************************
  event_time: 2021-11-17 10:55:12.938037
   user_host: pcloud[pcloud] @ localhost [127.0.0.1]
   thread_id: 444
   server_id: 1
command_type: Query
    argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert5`
*************************** 10. row ***************************
  event_time: 2021-11-17 10:55:12.948604
   user_host: pcloud[pcloud] @ localhost [127.0.0.1]
   thread_id: 440
   server_id: 1
command_type: Query
    argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert4`
*************************** 11. row ***************************
  event_time: 2021-11-17 10:55:12.948604
   user_host: pcloud[pcloud] @ localhost [127.0.0.1]
   thread_id: 439
   server_id: 1
command_type: Query
    argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert4`
```

Why is the actual executed SQL displayed in the "shardingShpere" log different from the actual SQL executed by MySQL itself?

**Comment by CrackerSuperior** [comment]
> version： master
> 
> shardingSphere log：
> 
> ```sql
> [INFO ] 2021-11-17 10:55:12.901 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3
> [INFO ] 2021-11-17 10:55:12.901 [Connection-4-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
> [INFO ] 2021-11-17 10:55:12.902 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3
> [INFO ] 2021-11-17 10:55:12.902 [Connection-4-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_1 ::: SELECT * FROM insert4 o INNER JOIN insert5 i ON o.id = i.id WHERE i.id > 3
> ```
> 
> MySQL log:
> 
> ```sql
>  event_time: 2021-11-17 10:55:12.938037
>    user_host: pcloud[pcloud] @ localhost [127.0.0.1]
>    thread_id: 443
>    server_id: 1
> command_type: Query
>     argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert5`
> *************************** 9. row ***************************
>   event_time: 2021-11-17 10:55:12.938037
>    user_host: pcloud[pcloud] @ localhost [127.0.0.1]
>    thread_id: 444
>    server_id: 1
> command_type: Query
>     argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert5`
> *************************** 10. row ***************************
>   event_time: 2021-11-17 10:55:12.948604
>    user_host: pcloud[pcloud] @ localhost [127.0.0.1]
>    thread_id: 440
>    server_id: 1
> command_type: Query
>     argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert4`
> *************************** 11. row ***************************
>   event_time: 2021-11-17 10:55:12.948604
>    user_host: pcloud[pcloud] @ localhost [127.0.0.1]
>    thread_id: 439
>    server_id: 1
> command_type: Query
>     argument: SELECT `id`, `sharding`, `sex`, `name`, `text`, `longtexts`, `time`, `money` FROM `insert4`
> ```
> 
> Why is the actual executed SQL displayed in the "shardingShpere" log different from the actual SQL executed by MySQL itself?

And I opened the "Federation" engine, which is a cross-database related query.

**Comment by strongduanmu** [comment]
@CrackerSuperior Yes, the logs currently printed are indeed not actually executed SQL. The federation execution engine processes and executes the user's logical SQL internally. We will optimize log printing and output the sql executed inside the federation execution engine.

**Comment by CrackerSuperior** [comment]
> @CrackerSuperior Yes, the logs currently printed are indeed not actually executed SQL. The federation execution engine processes and executes the user's logical SQL internally. We will optimize log printing and output the sql executed inside the federation execution engine.

ok
