### ISSUE TITLE
5.0.0-mode fuse

### ISSUE THREAD

**Issue by fenghuarugu** [apache/shardingsphere#13662]
When I use the orchestration management function of shardingsphere-5.0.0, which word can I write to fuse the database instance? I know that 5.0.0-alpha is written to disable, but I see that the source code of 5.0.0 is written to circuit_ Breaker did not fuse.

**Comment by menghaoranss** [comment]
Use DistSQL `[enable / disable] instance IP=xxx, PORT=xxx` to disable or enable the instance.

**Comment by fenghuarugu** [comment]
I tried it yesterday. When I use the following method: use distsql [disable] instance IP = XXX, port = XXX to disable the instance, I can still write data successfully. My version is the latest 5.0.0

**Comment by menghaoranss** [comment]
Any exception occurred where you execute `disable instance IP=xxx,port=xxx`?

**Comment by fenghuarugu** [comment]
There is no exception. When I used 5.0.0-alpha to write disable, the data could not be inserted into the database normally. However, when I used 5.0.0-alpha to write disable, the instance node was ZK deleted, but the data could still be written into the database normally. So is the function of the disable operation in 5.0.0 changed? In the past, the data source was closed, and then the system could not write to the database. Now, the control center cannot control this instance?

**Comment by fenghuarugu** [comment]
There is no exception. When I write disable with 5.0.0-alpha, the data cannot be inserted into the database normally, but when I write disable with 5.0.0, the data can still be written into the database normally.

**Comment by menghaoranss** [comment]
JDBC or Proxy? Please describe the steps to reproduce

**Comment by fenghuarugu** [comment]
It's JDBC. It's not easy to edit here. I wrote the problem back in the following blog post.
https://github.com/apache/shardingsphere/issues

**Comment by menghaoranss** [comment]
For JDBC, the `port` is PID, execute `show instance list;` in proxy to get all instance list.

**Comment by fenghuarugu** [comment]
What happens if you write disabled? What can this function do? If I write disabled when I use the 5.0.0-beta version,. Then the database of this instance will achieve the effect of fusing, that is, I can't perform crud operation. I think this is the correct use scenario. However, after I write disabled in version 5.0.0, I can still perform database crud operation. I have written the problem description and operation steps in my post. Can you demonstrate and reproduce the problems I said, Can you give me a solution or explanation? No thanks left.

**Comment by fenghuarugu** [comment]
https://blog.csdn.net/yanchi92/article/details/121399075

**Comment by menghaoranss** [comment]
> What happens if you write disabled? What can this function do? If I write disabled when I use the 5.0.0-beta version,. Then the database of this instance will achieve the effect of fusing, that is, I can't perform crud operation. I think this is the correct use scenario. However, after I write disabled in version 5.0.0, I can still perform database crud operation. I have written the problem description and operation steps in my post. Can you demonstrate and reproduce the problems I said, Can you give me a solution or explanation? No thanks left.

please refer : https://shardingsphere.apache.org/document/current/cn/reference/management/

The structure of registry center has been changed in 5.0.0 GA

if you don't use DistSQL, add the instanceId under /status/compute_nodes/circuit_breaker

**Comment by fenghuarugu** [comment]
OK, I probably understand. Thank you. Will shardingsphere UI have version 5.0.0ga?, I haven't seen it yet

**Comment by menghaoranss** [comment]
ShardingSphere-UI won't be updated, because `DistSQL` provides more capabilities, including everything the UI can do before.

**Comment by fenghuarugu** [comment]
Thank you

**Comment by menghaoranss** [comment]
@fenghuarugu welcome, would you mind closing  this issue?

**Comment by fenghuarugu** [comment]
I'm sorry, I forgot to close the operation
