### ISSUE TITLE
got dependency error when compile the project

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#13674]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
MacOS 5.0.1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC and ShardingSphere-Proxy
### Expected behavior
compile success
### Actual behavior
compile failed
### Reason analyze (If you can)
dependency issue
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. clone the up to date code from shardingsphere github : https://github.com/apache/shardingsphere.git
2. compile the project by following command : 
```shell
./mvnw clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -T1C -Prelease
```
3. got following compile error :

```log
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:30 min (Wall Clock)
[INFO] Finished at: 2021-11-18T11:09:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shardingsphere-integration-agent-test-jaeger: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-integration-agent-test-jaeger:jar:5.0.1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-integration-agent-test-common:jar:tests:5.0.1-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
[ERROR] Failed to execute goal on project shardingsphere-integration-agent-test-metrics: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-integration-agent-test-metrics:jar:5.0.1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-integration-agent-test-common:jar:tests:5.0.1-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
[ERROR] Failed to execute goal on project shardingsphere-integration-agent-test-zipkin: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-integration-agent-test-zipkin:jar:5.0.1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-integration-agent-test-common:jar:tests:5.0.1-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
[ERROR] Failed to execute goal on project shardingsphere-integration-agent-test-opentelemetry: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-integration-agent-test-opentelemetry:jar:5.0.1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-integration-agent-test-common:jar:tests:5.0.1-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]

```

test related dependencies block the compile process even the command already skip test.

**Comment by menghaoranss** [comment]
I will try to reproduce.
