### ISSUE TITLE
After the table splitting policy is configured, it does not take effect, nor does it report an error, and no table splitting processing is performed

### ISSUE THREAD

**Issue by Zhai6319** [apache/shardingsphere#13675]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphereJDBC
### Expected behavior
It is hoped that table splitting can be performed normally
### Actual behavior
Mybatis plus is integrated into the project. After the table splitting strategy is configured, no table splitting processing is performed and no error is reported
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sharding:
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
        sharding-algorithms:
          user-table-strategy-inline:
            type: INLINE
            props:
              algorithm-expression: user_info_$->{user_id % 2}
        tables:
          user_info:
            actual-data-nodes: example.user_info_$->{0..1}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: user-table-strategy-inline
### Example codes for reproduce this issue (such as a github link).
No,

**Comment by zjcnb** [comment]
@Zhai6319 Hi, I think your configuration are right. Can you support a demo project?  Because, my demo can be sharding normally

**Comment by Zhai6319** [comment]
version 5.0.0
![image](https://user-images.githubusercontent.com/29478697/142403886-7c36105d-5af7-4ca9-a321-68ac483360d5.png)
Database specific table
![image](https://user-images.githubusercontent.com/29478697/142403606-c0d9cdaf-c034-4db8-8505-05d82996f960.png)
Specific configuration
![c0eec8078eb36317f8a03918bbbc027](https://user-images.githubusercontent.com/29478697/142403654-b0a16ebc-a8d7-4492-949d-69e69941ea91.png)

![5ab2382fd777abfa94475a25163afde](https://user-images.githubusercontent.com/29478697/142403699-dd818314-ca74-452f-8bcb-053657317650.png)
Start successful
![fe98dd8bd7edb349dcb1e1a729be3f9](https://user-images.githubusercontent.com/29478697/142403754-13671c41-b3ae-4156-a8a6-916c15057358.png)

![3e5011eb4f33aad9c5bb66bf49422e3](https://user-images.githubusercontent.com/29478697/142403775-ed15b681-82b0-4aca-8def-bdd3946f620f.png)
![3d5a420634ac0377ca1b1775886c1a5](https://user-images.githubusercontent.com/29478697/142403800-c111ba4c-9e35-4bfd-a234-f07e8d91a365.png)

**Comment by strongduanmu** [comment]
Hi @Zhai6319, can you provide sql-show log?

**Comment by Zhai6319** [comment]
![image](https://user-images.githubusercontent.com/29478697/142561824-455a533f-1e6a-40f1-97a9-698aa9578976.png)

**Comment by Zhai6319** [comment]
I configured SQL output, but it didn't work. I can only output the SQL of mybatis plus
![image](https://user-images.githubusercontent.com/29478697/142565362-b18b91b2-ef09-41fd-8dc2-2371b0ea1a0b.png)

The following is the SQL output of mybatis plus. I wonder if the shardingsphere is compatible with mybatis plus or other dependencies


![image](https://user-images.githubusercontent.com/29478697/142566388-172985b9-2003-417c-be5e-220c96521ffa.png)

**Comment by Zhai6319** [comment]
I introduce the configuration in the way below the startup class
![image](https://user-images.githubusercontent.com/29478697/142566512-96ef3fd3-9d2d-4439-9dca-c7598204b766.png)

**Comment by strongduanmu** [comment]
@Zhai6319 I am not familiar with MyBatis Plus. Can you debug to see if ShardingSphereDataSource is successfully injected into your project? Or try to remove MyBatis Plus temporarily?

**Comment by Zhai6319** [comment]
@strongduanmu I have provided a demonstration project to @ sphereex in the community wechat group

**Comment by strongduanmu** [comment]
> @strongduanmu I have provided a demonstration project to @ sphereex in the community wechat group

@Zhai6319 Thank you, I will check this demo.

**Comment by Zhai6319** [comment]
Thank you

**Comment by Zhai6319** [comment]
I think I've found the problem

**Comment by Zhai6319** [comment]
I don't understand the configuration of this mode
![41dfef1be1e45f8f3ff933e6de49e0c](https://user-images.githubusercontent.com/29478697/142709085-e2a98db1-6a97-403f-af2f-1ee3ce1b2624.png)

**Comment by strongduanmu** [comment]
@Zhai6319 You can close this issue, and submit new issue about mode.
