### ISSUE TITLE
`show instance list` is not correct

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#13677]
```
mysql> show instance list;
+---------------+-------+--------+
| ip            | port  | status |
+---------------+-------+--------+
| 192.168.5.200 | 3307  | enable |
| 192.168.5.200 | 30191 | enable |
+---------------+-------+--------+
2 rows in set (0.00 sec)
```

For `ShardingSphere-JDBC` instance, `30191` is PID, not `port`, the result may need to be optimized.

**Comment by RaigorJiang** [comment]
Hi @lanchengx , could you check it?  Thank you!

**Comment by lanchengx** [comment]
@RaigorJiang @menghaoranss  please assign to me .

**Comment by lanchengx** [comment]
@me
The value of port comes from the node `/status/compute_nodes/online` on zk, could you see the value on `zk`
