### ISSUE TITLE
Execute insert sql, and the sql primary key is negative, the error is: "outside valid range for the datatype BIGINT"

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#13670]
### Expected behavior
execution succeed

### Actual behavior
'18446744073709548257' in column '1' is outside valid range for the datatype BIGINT.

### Reason analyze:
The primary key type is: bigint
When the sql insert primary key is positive, the execution is correct, if it is negative, the execution is wrong, but no matter whether it is positive or negative, the data has actually entered the database

 ###SQL to execute:
INSERT INTO db0.tb0 ( id, start_active_date, enable_flag, type_code, segment_value )
VALUES(-33454,'2021-05-26','Y','DEPT','TEST1001')
![image](https://user-images.githubusercontent.com/41990755/142230662-6686467f-7632-429d-92e7-857c003607b7.png)
![image](https://user-images.githubusercontent.com/41990755/142230059-107a66c9-d084-4a1d-9479-d4f15cf0e8a6.png)
![image](https://user-images.githubusercontent.com/41990755/142230152-296829aa-eaa4-436f-9945-13ecdc3ee328.png)

**Comment by jingshanglu** [comment]
@ThisOnly can you show more info? like `db type` and `db version` (mysql5.7 or others)

**Comment by tuichenchuxin** [comment]
I have tried to insert negative id into table with proxy. It's ok. Can you check again?

**Comment by ThisOnly** [comment]
> I have tried to insert negative id into table with proxy. It's ok. Can you check again?
![image](https://user-images.githubusercontent.com/41990755/142401270-027eddd0-f271-4079-9e4b-e30bff2488c9.png)
I still have this problem

**Comment by tuichenchuxin** [comment]
Could you show me your config?

**Comment by ThisOnly** [comment]
I found the reason: MySQL has enabled the primary key auto-increment situation, and the inserted ID is a negative number, it will cause this problem。

When using primary key auto-increment, the ProxyJDBCExecutorCallback.getGeneratedKeyIfInteger(final Statement statement) method will call resultSet.getLong, which causes this problem；

![image](https://user-images.githubusercontent.com/41990755/142555740-02be8e0a-2784-4f82-98a5-beb508ae87f2.png)

**Comment by tuichenchuxin** [comment]
> I found the reason: MySQL has enabled the primary key auto-increment situation, and the inserted ID is a negative number, it will cause this problem。
> 
> When using primary key auto-increment, the ProxyJDBCExecutorCallback.getGeneratedKeyIfInteger(final Statement statement) method will call resultSet.getLong, which causes this problem；
> 
> ![image](https://user-images.githubusercontent.com/41990755/142555740-02be8e0a-2784-4f82-98a5-beb508ae87f2.png)

Is a config problem or a bug?

**Comment by ThisOnly** [comment]
a bug

**Comment by ThisOnly** [comment]
When the primary key has a value, sharding should not call the method of primary key auto-increment

**Comment by tuichenchuxin** [comment]
@ThisOnly I think we should not add negtive value on column with auto-increment. But it has really inserted, return error is not correct.

`There can be only one AUTO_INCREMENT column per table, it must be indexed, and it cannot have a DEFAULT value. An AUTO_INCREMENT column works properly only if it contains only positive values. Inserting a negative number is regarded as inserting a very large positive number. This is done to avoid precision problems when numbers “wrap” over from positive to negative and also to ensure that you do not accidentally get an AUTO_INCREMENT column that contains 0.`
https://dev.mysql.com/doc/refman/8.0/en/create-table.html
