### ISSUE TITLE
Sharding Tables  join does not behave as expected

### ISSUE THREAD

**Issue by yiyayamaya** [apache/shardingsphere#13679]
Hi!

### Which version of ShardingSphere did you use?
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-namespace</artifactId>
			<version>4.1.1</version>
		</dependency>

### Expected behavior

There are two actual tables(atc_task_logs_20211117 and atc_task_logs_20211118) splited from one logic table (atc_task_logs).
I use created_time as the split column and it works well.

I want join atc_task_logs_20211117 and atc_task_logs_20211118 on a column they both have. 

I expect the  actual sql be something like 

```
        select 
        *
        FROM 
        atc_task_logs_20211117 firstDay JOIN atc_task_logs_20211118 secondDay
        ON firstDay.hash_key = secondDay.hash_key

```

I wrote it like 

```
        select
            *
        FROM
            atc_task_logs   firstDay JOIN atc_task_logs  secondDay  ON firstDay.hash_key = secondDay.hash_key
        WHERE
         <![CDATA[ firstDay.created_time >= '2021-11-17 00:00:00'  ]]>
         and
         <![CDATA[  firstDay.created_time <= '2021-11-17 23:59:59'   ]]>
         and
        <![CDATA[ secondDay.created_time >= '2021-11-18 00:00:00'  ]]>
         and
         <![CDATA[  secondDay.created_time <= '2021-11-18 23:59:59'  ]]>

```

### Actual behavior
![image](https://user-images.githubusercontent.com/45009320/142374478-c2447ad2-4205-4d0e-80cb-6e9bce97a695.png)

### Reason analyze (If you can)

It may because I join two actual tables from the same logic table?
or the split column from two tables are the same?

Thank you.

**Comment by strongduanmu** [comment]
@yiyayamaya Thank you for your feedback, 4.x version does not support non-binding sharding table join query, because there may be cross-database situations.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
