### ISSUE TITLE
sql alias is case sensitive

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#13683]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy?

### Expected behavior
sql can be executed normally，Hope: sql is not case sensitive

### Actual behavior
Runtime exception: [null]

### Reason analyze (If you can)
The executed sql is：SELECT DISTINCT HPPS.REC_FLAG FROM  PARTY_SITES HPPS
 WHERE hpps.PARTY_SITE_NUMBER = 'H020101' AND hpps.tenant_id = 41;
Alias in uppercase: "HPPS", The WHERE condition is written "hpps";Cause an error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/41990755/142380150-079a32e2-b8ff-4b8a-b27b-c03d91819959.png)
![image](https://user-images.githubusercontent.com/41990755/142380177-25549c5f-b9bd-4c10-932c-7c0fef7cdcc1.png)

**Comment by tuichenchuxin** [comment]
This sql cannot be executed correctly, so sharding-proxy will not support it either

**Comment by ThisOnly** [comment]
![image](https://user-images.githubusercontent.com/41990755/142403091-1f27e960-cbfb-4933-a4c0-39a0df299d97.png)
mysql is executable

**Comment by tuichenchuxin** [comment]
may be is because navicat has optimized.
![image](https://user-images.githubusercontent.com/86938616/142549852-c2f80091-8135-4e91-bc11-a44f5412e9de.png)

**Comment by ThisOnly** [comment]
![image](https://user-images.githubusercontent.com/41990755/142817369-de137f82-f055-4cb7-93b0-03c73c062896.png)
mysql can execute this sql；
mysql version: 5.7.10

**Comment by tuichenchuxin** [comment]
@ThisOnly I found this document, better use same case.
 https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
![image](https://user-images.githubusercontent.com/86938616/142820794-b57d24f1-af0e-4c57-897c-27963f7141f7.png)

**Comment by ThisOnly** [comment]
OK, thanks
