### ISSUE TITLE
Add DistSQL to trigger table metadata refresh.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#13702]
Hi community,

We have collected some user requirements. 

>We hope that when using Proxy, we can execute DDL on the physical database (for example, add a column to a table), and then refresh the metadata in the Proxy, so that ShardingSphere can recognize the newly added column.

Such as this issue:
- https://github.com/apache/shardingsphere/issues/11755

\
Now, I plan to add a syntax for refreshing table metadata in DistSQL, so that users can control when to trigger the refresh.
The syntax is as follows:
1. Refresh metadata of all tables:
```sql
refresh table metadata;
```
2. Refresh metadata of the specified table:
```sql
# from a random resource
refresh table metadata t_order;
# From the specified resource
refresh table metadata t_order from resource ds_0;
```

At the same time, `ContextManager` needs to add a new API to really refresh the metadata. @menghaoranss  can you help design the ContextManager interface?

**Comment by RaigorJiang** [comment]
Hi @lanchengx ,
Thanks for your great work, please leave a comment and I will assign this issue to you.

**Comment by lanchengx** [comment]
> Hi @lanchengx , Thanks for your great work, please leave a comment and I will assign this issue to you.

🥷

**Comment by RaigorJiang** [comment]
Done.
