### ISSUE TITLE
【shardingsphere-proxy】Do you have any suggestions on where to bury to get the client  IP and schema that want connected to  proxy

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#13704]
## Question

**For English only**, other languages will not accept.

**Do you have any suggestions on where to bury the IP of the client connected to proxy，i want to record the client ip and schema which client wants to connect   in  log**

```java

# Class Name ： MySQLAuthenticationHandler

# method 

    public Optional<MySQLServerErrorCode> login(final String username, final String hostname, final byte[] authenticationResponse, final String databaseName) {

    # My idea is to be here ，record the client ip and schema 

        Grantee grantee = new Grantee(username, hostname);
        if (!SQLCheckEngine.check(grantee, (a, b) -> isPasswordRight((ShardingSphereUser) a, (byte[]) b), authenticationResponse, getRules(databaseName))) {
            return Optional.of(MySQLServerErrorCode.ER_ACCESS_DENIED_ERROR);
        }
        return null == databaseName || SQLCheckEngine.check(databaseName, getRules(databaseName), grantee)
                ? Optional.empty() : Optional.of(MySQLServerErrorCode.ER_DBACCESS_DENIED_ERROR);
    }
```

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by TeslaCN** [comment]
Hi @xue2lang 
I think the location in your idea is fine.
