### ISSUE TITLE
I don't quite understand the mode concept of spring.shardingsphere.mode configuration. 

### ISSUE THREAD

**Issue by Zhai6319** [apache/shardingsphere#13710]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

I don't quite understand the mode concept of spring.shardingsphere.mode configuration. If the online is distributed, must this be configured as cluster? If not configured, what will be the impact? In our project, only split tables and data desensitization are used. If it must be configured, can Nacos be used as the warehouse type?

**Comment by zjcnb** [comment]
@Zhai6319 Hi, you can look this. https://shardingsphere.apache.org/document/5.0.0/en/concepts/mode/

**Comment by roodkcab** [comment]
>If the online is distributed, must this be configured as cluster? 
yes it must be.

>If not configured, what will be the impact? 
table metadata, i.e. structure/index is stored in etcd or anyother repositories configured in server.xml when mode is cluster. when add / drop column of a table, metadata should be refreshed, or you will get wrong metadata when execute PrepareStatement.

>can Nacos be used as the warehouse type?
Nacos is supported by shardingsphere

**Comment by Zhai6319** [comment]
@roodkcab Thank you for your answer, but there is no detailed configuration explanation about Nacos on the official website

**Comment by TeslaCN** [comment]
> @roodkcab Thank you for your answer, but there is no detailed configuration explanation about Nacos on the official website

Hi @Zhai6319 
The Nacos is supported in ShardingSphere 4.x and is no longer supported since 5.0.
