### ISSUE TITLE
ShardingSphere-jdbc 5.0 连接oracle时，insert into语句 SQL解析会报错

### ISSUE THREAD

**Issue by fengaixue** [apache/shardingsphere#13728]
5.0.0 oracle 普通的insert into 语句为什么不能解析通过??

[https://gitee.com/Sharding-Sphere/sharding-sphere/issues/I4IPJQ](url)

**Comment by strongduanmu** [comment]
@fengaixue Can you translate this issue to english? And provide more information?

**Comment by fengaixue** [comment]
Executor SQL: insert into t_order(id,user_id) values(1,1)

SQLParsingException : You hava an error in your SQL syntax

**Comment by fengaixue** [comment]
Debug info: OracleStatementParser.insertSingleTable()

switch case not match !!!  throw  NoviableAltException...

**Comment by fengaixue** [comment]
Debug info: OracleStatementParser.insertSingleTable()

switch case not match !!!  throw  NoviableAltException...

**Comment by fengaixue** [comment]
Already&nbsp;provided,&nbsp;&nbsp;I think it's enough !!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] ShardingSphere-jdbc 5.0 连接oracle时，insert into语句 SQL解析会报错 (Issue #13728)





 
@fengaixue Can you translate this issue to english? And provide more information?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuichenchuxin** [comment]
I use the same sql, it can parsed. Can you show me a demo to try?

**Comment by fengaixue** [comment]
Don't use unit tests！Combining with the druid-spring-boot-starter(1.2.6)、ojdbc8(12.2.0.1) and mybatis-spring-boot-starter(1.3.2)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] ShardingSphere-jdbc 5.0 连接oracle时，insert into语句 SQL解析会报错 (Issue #13728)





 
I use the same sql, it can parsed. Can you show me a demo to try?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuichenchuxin** [comment]
Parser is an independent model. If it's a parse error, may the actual sql is not that simple.

**Comment by fengaixue** [comment]
4.1.1&nbsp;it can parsed，5.0.0&nbsp;can`t&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 上午10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/shardingsphere] ShardingSphere-jdbc 5.0 连接oracle时，insert into语句 SQL解析会报错 (Issue #13728)





 
Parser is an independent model. If it's a parse error, may the actual sql is not that simple.
 
—

**Comment by terrymanu** [comment]
For English only
