### ISSUE TITLE
Consider about add parser rule in kernel layer

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#13725]
refer #13722.

In the process of reading the code, I found that some parsing rule configurations are still hard-coded in the code, and there are enough parsing-related configurations so that we can extract them and assemble them into a parse rule.
such as `sql-comment-parse-enabled`, sqlStatementCache option and parse tree cache option, and more about parse.

after extract:
```
- !SQL_PARSER
  sqlCommentParseEnabled: true
  sqlCacheInitialCapacity: 2000
  ......
```
todo list:

- [x] Support the configuration of rules
- [x] DistSQL RDL
- [x] DistSQL RQL
- [ ] add docs

Do you think this is a good idea? please give me some advices.

**Comment by tuichenchuxin** [comment]
+1

**Comment by totalo** [comment]
好的，我会推进这项工作

**Comment by tuichenchuxin** [comment]
@totalo Hi, I want to know how can I use sqlCommentParseEnabled in sharding-jdbc for springboot. :)

**Comment by totalo** [comment]
> @totalo Hi, I want to know how can I use sqlCommentParseEnabled in sharding-jdbc for springboot. :)

hi @tuichenchuxin. Sorry, it may not be supported yet. I am considering how to add it. I will submit a pr support tonight.

**Comment by tuichenchuxin** [comment]
@totalo :) Not in a hurry
