### ISSUE TITLE
When will 5.0.1 publish?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#13738]
When will 5.0.1 publish?

**Comment by menghaoranss** [comment]
Do you have any problems with version 5.0.0?

**Comment by penghuazhou** [comment]
I want use 5.0.1 in product environment because 5.0.1 have fixed some bugs.

**Comment by menghaoranss** [comment]
@penghuazhou Thanks for your attention. We will plan to release 5.0.1 in about a month.

**Comment by penghuazhou** [comment]
thanks
