### ISSUE TITLE
Error named Chinese after as in sql statement

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#13734]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy

### Expected behavior
Execution error

### Actual behavior
Executed correctly

### Reason analyze (If you can)
Sharding does not support naming Chinese after as，but mysql support 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
The executed sql is:
![image](https://user-images.githubusercontent.com/41990755/142816686-272aff73-d42d-49ba-9f93-1e3fbb8fdbfb.png)

**Comment by strongduanmu** [comment]
Hi @ThisOnly, thank you for your feedback, can you provide more exception info?

**Comment by ThisOnly** [comment]
![image](https://user-images.githubusercontent.com/41990755/142846426-3ac5ca17-304d-4695-81bd-e2c48cb7ebc1.png)

**Comment by supkingx** [comment]
@strongduanmu I want to try and fix it

**Comment by strongduanmu** [comment]
> @strongduanmu I want to try and fix it

@ThisOnly Great, I will assign this issue to you.

**Comment by supkingx** [comment]
@ThisOnly Put quotes around 合同分类
For example, H.document_type as "合同分类"
