### ISSUE TITLE
SQL parse error when execute sql with mysql keyword

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13759]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

select statement parse successfully

```sql
SELECT t1.id, track_id, title, intro, rank, h5_query_link, status, created_at, updated_at, operator, is_delete from tb_discovery_weibo_news_track t1 WHERE  is_delete = 0 and status in ( 0 , 10 , 11 )
```

### Actual behavior

![image](https://user-images.githubusercontent.com/10829171/143030879-984ca62a-2433-44ce-bb29-1630d22002ca.png)

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/10829171/143031027-25768324-dd80-40ab-b074-b58921a0ad90.png)

`rank` is a new keyword added in mysql 8.x version, which caused this sql parsing error. @tuichenchuxin Should we consider a comprehensive investigation of the parsing anomalies caused by keywords?

**Comment by tuichenchuxin** [comment]
Ok, I'll investigate these keywords.

**Comment by tuichenchuxin** [comment]
```
select rank from t;
```
If i execute this sql directly connected to mysql server. It can't be executed.
mysql version is `8.0.25`.
So, I think we don't need to support this.

**Comment by shenyiheyi** [comment]
`select rank from t;`
If i execute this sql directly connected to mysql server. It can be executed.
mysql version is 5.7.28.
So, I think  you need to support this.

**Comment by tuichenchuxin** [comment]
Rank is not supported in mysql 8.0 but can be supported in mysql 5.7.
this is related to #13759
I think we should avoid using this keywork as a column name.

**Comment by TeslaCN** [comment]
Hi @strongduanmu @tuichenchuxin 
Any update here? Could we finish this in 5.1.1?

**Comment by strongduanmu** [comment]
> Hi @strongduanmu @tuichenchuxin Any update here? Could we finish this in 5.1.1?

@TeslaCN I will move this issue to 5.1.2.

**Comment by tuichenchuxin** [comment]
rank can't be used in mysql 8 directly, but can used in mysql 5. And we can use it by `rank` this way. So I think we do not need to support this.  I'll close this issue.
