### ISSUE TITLE
Add more unit tests for ContextManager

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#13758]
- [ ] addSchema
- [ ] deleteSchema
- [ ] addResource
- [ ] alterResource
- [ ] dropResource
- [ ] alterRuleConfiguration
- [ ] alterDataSourceConfiguration
- [ ] alterSchema
- [ ] alterGlobalRuleConfiguration
- [ ] alterProps
- [ ] reloadMetaData

**Comment by shankeerthan-kasilingam** [comment]
Would like to pick up this ticket.

**Comment by shankeerthan-kasilingam** [comment]
Would like to pick up this ticket.

**Comment by strongduanmu** [comment]
@shankeerthan-kasilingam Welcome, I have assign this issue to you.

**Comment by menghaoranss** [comment]
> Would like to pick up this ticket.

@shankeerthan-kasilingam welcome

**Comment by shankeerthan-kasilingam** [comment]
Hey,
I have finished writing test cases. Apologies for the delay. I'll send a PR after a self review.

**Comment by shankeerthan-kasilingam** [comment]
Hi @menghaoranss and @strongduanmu,
I have sent a draft PR. https://github.com/apache/shardingsphere/pull/14363
Could you please check it?.

TIA
