### ISSUE TITLE
When executing the SQL created by obtaining the table, the value cannot be obtained. The SQL is show create table sys_log

### ISSUE THREAD

**Issue by jasper520** [apache/shardingsphere#13769]
show create table sys_log cannot get the value of the query

**Comment by strongduanmu** [comment]
Hi @jasper520, Can you submit an issue according to the bug template?

**Comment by jasper520** [comment]
```
<!--sharding jdbc-->
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.1.1</version>
		</dependency>
```

![image](https://user-images.githubusercontent.com/37660035/143205786-8a3371dd-6230-45d1-8b9a-24e7f2b94976.png)


sql：@SqlParser(filter = true)
	@Select("show create table sys_log")
	Map selectTableCreateSql2(@Param("tableName") String tableName);

I want to obtain the creation SQL of the table through this SQL, which can be obtained directly when using mybatis plus, but not when using sharding

**Comment by terrymanu** [comment]
Sorry, the information is not enough.
By the way, we have no time to investigate the issue related with other framework, it is better to use JDBC reproduce it.

**Comment by jasper520** [comment]
你好，来信收到，谢谢

**Comment by LeibNici** [comment]
Yes, I also encountered the same problem, how did you solve it?

**Comment by jasper520** [comment]
你好，来信收到，谢谢

**Comment by LeibNici** [comment]
For example: show create table user will be automatically converted to show create table user_202201, my purpose is to get dynamically created table sql
