### ISSUE TITLE
multi-table union query, do I need to specify all table strategy

### ISSUE THREAD

**Issue by oulexue** [apache/shardingsphere#13762]
### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
when i use the hint strategy  in a JOIN sql，the routing is incorrect。 Here's the code：

            hintManager.addDatabaseShardingValue("voucher","0");
            hintManager.addDatabaseShardingValue("account","1");

My question is multi-table union query, do I need to specify all table policies？

### Actual behavior
it only route to the repository specified by the voucher, regardless of the order

### Reason analyze (If you can)
I traced the code and found the following problem，
![image](https://user-images.githubusercontent.com/26663469/143159280-aba07b35-dae1-4bda-9fe0-a39f899a1e4d.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT u.* FROM account u  left join voucher l  on u.sob_id=l.sob_id WHERE u.city=#{city,jdbcType=VARCHAR}

**Comment by strongduanmu** [comment]
@oulexue Can you provide the sharding configuration and sql-show log?

**Comment by oulexue** [comment]
![image](https://user-images.githubusercontent.com/26663469/143169836-74b31495-0ab2-4884-80b7-79f68d8eec3a.png)
![image](https://user-images.githubusercontent.com/26663469/143169989-eb7a492e-5baf-42ab-9c65-08fa4c5ebdb8.png)

this is the configuration and actual SQL

**Comment by oulexue** [comment]
Only the repository where the voucher resides is routed

**Comment by oulexue** [comment]
hintManager.addTableShardingValue("account","1");
            hintManager.addTableShardingValue("voucher","0_2022");

            hintManager.addDatabaseShardingValue("voucher","0");
            hintManager.addDatabaseShardingValue("account","1");

**Comment by oulexue** [comment]
Actually, they're supposed to be in a same database. I kept them separate

**Comment by strongduanmu** [comment]
@oulexue Since you configured `account` and `voucher` as binding tables, when routing, a table is randomly selected for routing. But judging from your configuration, their sharding rules are different, so they cannot be configured as a binding table.

**Comment by oulexue** [comment]
thanks ，i get it
