### ISSUE TITLE
shardingsphere-test-common

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#13774]
shardingsphere-test-common version 5.0.0
not found from maven;
src package error:
[ERROR] Failed to execute goal on project shardingsphere-jdbc-core: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-jdbc-core:jar:5.0.0: Failure to find org.apache.shardingsphere:shardingsphere-test-common:jar:5.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by menghaoranss** [comment]
how could it be reproduced?

**Comment by TeslaCN** [comment]
The `shardingsphere-test-common` was not deployed to central repository, you may need to execute `mvn install` to install the modules to your local repository.
