### ISSUE TITLE
config query-with-cipher-column="false" rewrite sql is not correct

### ISSUE THREAD

**Issue by princess-yanyan** [apache/shardingsphere#13793]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

When I used 4.0.1 version,config <prop key="query.with.cipher.column">false</prop>, use plain column to query is correct,like you see "1" and "2" are plain column
![image](https://user-images.githubusercontent.com/25997093/143406933-06f2ecfd-18e4-48b8-9081-37fa645fa9f5.png)
![image](https://user-images.githubusercontent.com/25997093/143406952-1669cd8a-5803-48f3-8e16-591a91413b59.png)

but when I used 5.0.0 version，config query-with-cipher-column="false"，use plain column to query is not correct
![image](https://user-images.githubusercontent.com/25997093/143407038-2ba135a3-d432-4704-84fb-2fb06ea09c0b.png)
![image](https://user-images.githubusercontent.com/25997093/143407065-e3aee62d-e395-4771-bf47-27cdd4ac1d88.png)

so i want to say ,can 5.0.0 version the rewrite sql  same as 4.0.1?

**Comment by princess-yanyan** [comment]
I mean when query-with-cipher-column="false", 1 and 3 all should card_no (plain column)

**Comment by strongduanmu** [comment]
@princess-yanyan Thank you for your feedback. I see you are using the table-level `query.with.cipher.column` parameter, which is great. And I will investigate this issue.

**Comment by wuguanyu** [comment]
<xsd:schema xmlns="http://shardingsphere.apache.org/schema/shardingsphere/encrypt"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:beans="http://www.springframework.org/schema/beans"
            targetNamespace="http://shardingsphere.apache.org/schema/shardingsphere/encrypt"
            elementFormDefault="qualified">
    <xsd:import namespace="http://www.springframework.org/schema/beans" schemaLocation="http://www.springframework.org/schema/beans/spring-beans.xsd" />
    
    <xsd:element name="rule">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="table" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required" />
            <xsd:attribute name="query-with-cipher-column" type="xsd:boolean" default="true" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="table">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required" />
            <xsd:attribute name="query-with-cipher-column" type="xsd:boolean" />
        </xsd:complexType>
    </xsd:element>
     <xsd:element name="column">
        <xsd:complexType>
            <xsd:attribute name="logic-column" type="xsd:string" use="required" />
            <xsd:attribute name="cipher-column" type="xsd:string" use="required" />
            <xsd:attribute name="assisted-query-column" type="xsd:string" />
            <xsd:attribute name="plain-column" type="xsd:string" />
            <xsd:attribute name="encrypt-algorithm-ref" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="encrypt-algorithm">
        <xsd:complexType>
            <xsd:all>
                <xsd:element ref="beans:props" minOccurs="0" />
            </xsd:all>
            <xsd:attribute name="id" type="xsd:string" use="required" />
            <xsd:attribute name="type" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

**Comment by wuguanyu** [comment]
@princess-yanyan Can you try rule level ？

**Comment by strongduanmu** [comment]
> @princess-yanyan Can you try rule level ？

As @wuguanyu said, you can use the rule-level `query.with.cipher.column` parameter. The `query.with.cipher.column` parameter at the table level is a new feature. I just tested it and there are indeed some rewriting problems. I will fix this as soon as possible.

**Comment by wuguanyu** [comment]
@strongduanmu ruleLevel or tableLevel  query.with.cipher.column ,Does it have priority？

**Comment by strongduanmu** [comment]
> @strongduanmu ruleLevel or tableLevel query.with.cipher.column ,Does it have priority？

@wuguanyu If the queryWithCipherColumn at the table level is configured, it has a higher priority.

**Comment by wuguanyu** [comment]
> > @princess-yanyan Can you try rule level ？
> 
> As @wuguanyu said, you can use the rule-level `query.with.cipher.column` parameter. The `query.with.cipher.column` parameter at the table level is a new feature. I just tested it and there are indeed some rewriting problems. I will fix this as soon as possible.

You tested it In UnitTest ？

**Comment by wuguanyu** [comment]
> @princess-yanyan Thank you for your feedback. I see you are using the table-level `query.with.cipher.column` parameter, which is great. And I will investigate this issue.

You tested it In UnitTest ？

**Comment by strongduanmu** [comment]
> > @princess-yanyan Thank you for your feedback. I see you are using the table-level `query.with.cipher.column` parameter, which is great. And I will investigate this issue.
> 
> You tested it In UnitTest ？

@wuguanyu Test with proxy.

**Comment by wuguanyu** [comment]
![image](https://user-images.githubusercontent.com/24486917/143516641-2b38efac-d845-46d3-97f6-ad8c90d17226.png)

**Comment by strongduanmu** [comment]
Hi @princess-yanyan @wuguanyu, can you help test this issue on master branch?

**Comment by wuguanyu** [comment]
@strongduanmu I see source code ,we set query.with.cipher.column in rule-level, It worked.

**Comment by wuguanyu** [comment]
@princess-yanyan install code in local and test issue?

**Comment by strongduanmu** [comment]
> @princess-yanyan install code in local and test issue?

@wuguanyu Yes, test this problem with table level query.with.cipher.column param.

**Comment by princess-yanyan** [comment]
@strongduanmu @wuguanyu sorry，The internet in the company is not good,i can't download the source code,when i go home i will try，thank you for your reply

**Comment by princess-yanyan** [comment]
I install code in local  with 5.0.1-SNAPSHOT  and test this problem with table level query.with.cipher.column param,then it worked, table level has a higher priority.
