### ISSUE TITLE
Consider providing a dependency management POM

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#13795]
### Is your feature request related to a problem?
Managing project's dependencies is a tedious work.

### Describe the feature you would like.

Consider providing a pom `shardingsphere-dependencies` like the following one.
```xml
<dependencyManagement>
     <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>2.6.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by Swastyy** [comment]
Hi @TeslaCN Can I try solving this?

**Comment by TeslaCN** [comment]
Maybe we don't need this. About modules: 
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/optional-plugins/
