### ISSUE TITLE
Add unsupported sql for shardingsphere

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13792]
Hi, community.
We want to improve the support of sql parse.
It's a good first issue to contribute to shardingsphere.
## How to contribute
- Just found sql not supported and Then add to this [file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml)
## Skills
- None
## How to find sql not supported
- I found test case in postgresql resource code refer to #13383
- you can use [this example program ](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test)or write yourself code to test if there are some not supported sql.
- If you find some error sql, add to this [file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml)

- run this [file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java)

## After commit remeber to complete the task in #13383

**Comment by meSunnySrivastava** [comment]
Hello @menghaoranss, 
I would like to contribute to this.

**Comment by strongduanmu** [comment]
@meSunnySrivastava Welcome, I will assign this issue to you.

**Comment by meSunnySrivastava** [comment]
@tuichenchuxin 

**Could you please confirm my understanding about the steps I have to follow?**

_1. Get All SQL files: We have SQL files at the following location
https://github.com/postgres/postgres/tree/master/src/test/regress/sql


2. Run SQLParserEngine: For each SQL files I have to run SQLParserEngine and see for which SQL I am getting an exception
For running SQLParserEngine I can refer to https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test

3.Add to Unsupported: If I find any sql which is causing the exception I have to add it to unsupported.xml
https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml

4. Confirmation Step: To confirm this I have to run UnsupportedSQLParserParameterizedTest.java test. 
Test should pass and SQLParsingException should be thrown for the SQL which I added in step 3._ 

Please correct the step where I have wrong understanding if any. 

**Question: Once I am done processing one sql file do I need to mark that as checked in the following issue as well?** 
https://github.com/apache/shardingsphere/issues/13383
**or Do I need to mention anywhere which files are done?**

**Comment by tuichenchuxin** [comment]
@meSunnySrivastava Yes, your step is right. Just submit an pr mention #13383 or comment is enough, I'll mark the subtask as checked.

**Comment by tuichenchuxin** [comment]
I have update my[ example demo](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test)
Now, it can get all unsupported sql from postgreSql and mySql.
And I get two unsupported file. So this issue can be closed.
