### ISSUE TITLE
Add more unit test for EncryptAlgorithmMetaData, EncryptRule and EncryptTable

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13807]
Hi, community:

This issue is to add more unit tests for the `EncryptAlgorithmMetaData`, `EncryptRule` and `EncryptTable` classes. Welcome to claim them.

The specific subtasks are as follows:

- [x] Add unit test for EncryptAlgorithmMetaData#isQueryWithCipherColumn
- [x] Add unit test for EncryptRule#isQueryWithCipherColumn
- [x] Add unit test for EncryptTable#getQueryWithCipherColumn

Through this issue, you can understand the process of participating in Apache ShardingSphere, and be familiar with Encrypt-related APIs.

**Comment by lovestaryouth** [comment]
新人报道，请多关照

**Comment by strongduanmu** [comment]
Hi @lovestaryouth welcome here, can you translate your comment to english?

**Comment by lovestaryouth** [comment]
I come back with regret for my foolish early

**Comment by zzs52** [comment]
Can I try?

**Comment by strongduanmu** [comment]
> Can I try?

@zzs52 Of course.

**Comment by strongduanmu** [comment]
Fixed by #14630.
