### ISSUE TITLE
shardinshere4.x and 5.x support Microservices transaction?

### ISSUE THREAD

**Issue by HCTzz** [apache/shardingsphere#13801]
I want to confirm something，shardinshere support Microservices transaction?  thanks!

**Comment by TeslaCN** [comment]
About transaction, you may refer to https://shardingsphere.apache.org/document/current/en/features/transaction/

**Comment by HCTzz** [comment]
@TeslaCN 我看seata以及shardingSphere整合demo里，接口调用入口都是使用shardingsphere的服务。反过来调用就会报错。 #13783

**Comment by jingshanglu** [comment]
> I want to confirm something，shardinshere support Microservices transaction? thanks!

@HCTzz Not support yet, Here is a discussion about this [discussion](https://github.com/apache/shardingsphere/issues/12771)

**Comment by HCTzz** [comment]
@jingshanglu but only using Seata, the reason for Seata fetch scheme error(get table meta error ,table xxx not exist) is that the real table name cannot be obtained. Can you give me some advice? thank you!

**Comment by jingshanglu** [comment]
> @jingshanglu but only using Seata, the reason for Seata fetch scheme error(get table meta error ,table xxx not exist) is that the real table name cannot be obtained. Can you give me some advice? thank you!
@HCTzz Can you show the sql send to shardingsphere from Seata?

**Comment by jingshanglu** [comment]
the same with #14550
