### ISSUE TITLE
Configuration: sharding-algorithms.xxx.props.algorithm-expression init failure in 5.0.0

### ISSUE THREAD

**Issue by ZWMdarker** [apache/shardingsphere#13817]
Configuration is as follows:
spring:
  shardingsphere：
    .......
    rules:
      sharding:
        binding-tables: t_file
        tables:
          t_file:
            database-strategy:
              standard:
                sharding-column: c_wjdx
                sharding-algorithm-name: database_inline
            table-strategy:
              standard:
                sharding-column: c_bh
                sharding-algorithm-name: table_inline
        sharding-algorithms:
          database_inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{c_wjdx % 2}
          table_inline:
            type: INLINE
            props:
              algorithm-expression: t_file$->{c_bh % 3}
When I started the project, it always gave me this error: java.lang.NullPointerException: Inline sharding algorithm expression cannot be null.
But I've configured this property

**Comment by ZWMdarker** [comment]
and I debugged the source code, I found in the class AbstractAlgorithmProvidedBeanRegistry  ,this method registerBean.
boolean existProps = PropertyUtil.containPropertyPrefix(environment, propsPrefix) always return false; and i try to use this method   environment.getProperty("spring.shardingsphere.rules.sharding.sharding-algorithms.database_inline.props.algorithm-expression") , i can get the result

**Comment by zjcnb** [comment]
refer to: #13554 

@ZWMdarker Hi, you can change `database_inline` to `database-inline` and `table_inline `to `table-inline`

**Comment by ZWMdarker** [comment]
@zjcnb thx, When I modified this parameter（<sharding-algorithm-name>）, the problem was solved. but, I got the above configuration from the official website
from : https://shardingsphere.apache.org/document/5.0.0/en/user-manual/shardingsphere-jdbc/usage/sharding/spring-boot-starter/
Real is too embarrassing~~~

**Comment by zjcnb** [comment]
I think you can fixed it. Welcome to join ShardingSphere!

**Comment by terrymanu** [comment]
Fixed
