### ISSUE TITLE
sharding-jdbc is support custome db or table name

### ISSUE THREAD

**Issue by bpzhang** [apache/shardingsphere#13812]
sharding-jdbc is support db instance name or table name:
I want to custom a name for table or db instance, like:
db_order_0001,db_order_0002 
and prefix is start '000' or another prefix

**Comment by strongduanmu** [comment]
@bpzhang You can refer this [document](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/inline-expression/).

**Comment by bpzhang** [comment]
> @bpzhang You can refer this [document](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/inline-expression/).

yes,This is what I wanted,Thanks
