### ISSUE TITLE
How do I configure a custom sharding algorithm in version 5.x?

### ISSUE THREAD

**Issue by Sfaecp** [apache/shardingsphere#13815]
To customize the sharding algorithm configuration, I only found the configuration before 5.x, but did not find the configuration before 5.x.
My configuration is as follows:
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=table-inline

spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.table-inline.props.algorithmClassName=com.lbx.dividedbtable.algorithm.PowerfulGreateTableAlgorithm

**Comment by strongduanmu** [comment]
Hi @Sfaecp, you can use `class_based` algorithm. For more detailed information, you can refer https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%88%86%E7%89%87%E7%AE%97%E6%B3%95

**Comment by Sfaecp** [comment]
Think you!
