### ISSUE TITLE
required a bean of type 'javax.sql.DataSource' that could not be found.

### ISSUE THREAD

**Issue by DreamPWJ** [apache/shardingsphere#13816]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0      spring boot 2.5.6    mysql 8.0.12
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
Start-up success
### Actual behavior
![image](https://user-images.githubusercontent.com/16730031/143544812-1dd83b29-f7c5-4d7f-b371-847320f02d5b.png)

### Reason analyze (If you can)
Unable to find data source
### Example codes for reproduce this issue (such as a github link).
@Bean
    public static SqlSessionFactory sqlSessionFactoryBean(
            @Qualifier("dataSource") DataSource dataSource) 
{}

**Comment by DreamPWJ** [comment]
Caused by: java.sql.SQLSyntaxErrorException: Table 'property_sales_dev.user_login_log' doesn't exist      ，
User_login_log is a logical table
But there are user_login_log_1 , user_login_log_2。
![image](https://user-images.githubusercontent.com/16730031/143555703-ac75f033-1ebe-47f1-8373-7efd4bdfe47d.png)

**Comment by zjcnb** [comment]
@DreamPWJ Hi, you can refer to this : https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases-tables.yaml

**Comment by DreamPWJ** [comment]
Perhaps the JAR is not in effect
