### ISSUE TITLE
Shardingwhere5 custom configuration document support？

### ISSUE THREAD

**Issue by fyname** [apache/shardingsphere#13827]
hi

Are there any documents about shardingwhere 5 custom routing and SQL rewriting YML?

**Comment by RaigorJiang** [comment]
Hi @fyname 
The feature of custom rewriting is not provided, and custom routing can be implemented by customizing the sharding algorithm.

document:
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/

example:
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example
