### ISSUE TITLE
Restore sysbench documents

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#13825]
## Documents

The `sysbench` testing references were deleted in https://github.com/apache/shardingsphere/pull/13005. 
And the `performance-test` was accidentally renamed to `sysbench-test` in https://github.com/apache/shardingsphere/pull/13182. 

Consider restoring the `sysbench` documents and update the configurations to the latest.

**Comment by Swastyy** [comment]
Can I try this?

**Comment by TeslaCN** [comment]
> Can I try this?

@Swastyy Welcome! My idea is restoring the documents deleted in #13005. Before restoring, you may need to check if there is anything outdated in documents, if so, update them to latest. And rename the current `sysbench-test` to `performance-test` againi.
