### ISSUE TITLE
Question：Shardingsphere proxy ，how does it support splitting only databases, but not tables

### ISSUE THREAD

**Issue by 90yangkang** [apache/shardingsphere#13820]
Shardingsphere proxy ，how does it support splitting only databases, but not tables？

**Comment by zjcnb** [comment]
@90yangkang  Hi, you can look this : https://community.sphere-ex.com/t/topic/419

**Comment by zjcnb** [comment]
@90yangkang  Hi, you can refer to this :
https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases.yaml
and
https://community.sphere-ex.com/t/topic/419/12

**Comment by terrymanu** [comment]
I just close it because no response for long time.
