### ISSUE TITLE
Add more unit test for ShardingConditions

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13821]
Hi, community:

This issue is to add more unit tests for the ShardingConditions class. Welcome to claim them.

The specific subtasks are as follows:

- [ ]  Add unit test for ShardingConditions#isAlwaysFalse
- [ ]  Add unit test for ShardingConditions#merge
- [ ]  Add unit test for ShardingConditions#isNeedMerge
- [ ]  Add unit test for ShardingConditions#isSameShardingCondition

Through this issue, you can understand the process of participating in Apache ShardingSphere, and be familiar with sharding.

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by strongduanmu** [comment]
@mohitsaxenaknoldus Welcome, I will assign this issue to you.

**Comment by mohitsaxenaknoldus** [comment]
@strongduanmu Need some help with this: https://github.com/apache/shardingsphere/pull/13836
Can't seem to figure out why the CI is failing.

**Comment by clbigdata** [comment]
I want solve this

**Comment by strongduanmu** [comment]
> I want solve this

@clbigdata Welcome, I will assign this issue to you.

**Comment by farmer-liuz1024** [comment]
Please assign this issue to me.thx

**Comment by strongduanmu** [comment]
@farmer-liuz1024 Welcome, I just assign this issue to you.
