### ISSUE TITLE
Hello, when I insert a picture stream blob, the data will change

### ISSUE THREAD

**Issue by shenmadouyaowen** [apache/shardingsphere#13847]
Software version ：shardingsphere  5.0
System version ：Ubuntu 20.04.3 LTS x86_64
php version ：7.4
mysql version  ：8.0
PHP framework：Laravel Framework 8.73.2

Hello, read the picture stream data and write it to MySQL.  it was found that the picture could not be displayed. It can display the image data not inserted through the shardingsphere. After testing, the data will change when I write it.

**Comment by zjcnb** [comment]
@shenmadouyaowen Hi, What is the format of the picture? And Can you provider your table structure.

**Comment by shenmadouyaowen** [comment]
> @shenmadouyaowen Hi, What is the format of the picture? And Can you provider your table structure.

Hello, thank you for your reply. The image format includes JPG, PNG and tiff. The following is my MySQL table structure.
![image](https://user-images.githubusercontent.com/12426724/144156035-88f71ea9-2b27-4f8c-9314-46576bfc0051.png)

**Comment by zjcnb** [comment]
@shenmadouyaowen Ok ,  I will check it.

**Comment by zjcnb** [comment]
Hi, I try test it. but i not found problem. this is my demo projec
[ss-example.zip](https://github.com/apache/shardingsphere/files/7639380/ss-example.zip)
t.

**Comment by shenmadouyaowen** [comment]
> Hi, I try test it. but i not found problem. this is my demo project. [ss-example.zip](https://github.com/apache/shardingsphere/files/7639380/ss-example.zip)
> 
> Run JdbcPictureDemo.class
> 
> change
> 
> ```
> 	<dependency>
> 			<groupId>org.apache.shardingsphere</groupId>
> 			<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
> 			<version>5.0.1-SNAPSHOT</version>
> 		</dependency>
> ```
> 
> to
> 
> ```
> 	<dependency>
> 			<groupId>org.apache.shardingsphere</groupId>
> 			<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
> 			<version>5.0.0</version>
> 		</dependency>
> ```

Thank you very much. I'll try again
