### ISSUE TITLE
Bug when specifying data table

### ISSUE THREAD

**Issue by qiuweilu** [apache/shardingsphere#13846]
## Bug Report
version
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0</version>
        </dependency>

question
  example
        SELECT user_share.*, act_stats.*, user_info.info_nickname, user_info.info_photo, user_info.info_gender
        FROM user_share
        INNER JOIN act_stats_${tabIndex} act_stats ON user_share.share_id = act_stats.bind_fkid
        INNER JOIN user_info ON user_info.user_id = user_share.user_id
        WHERE user_share.user_id = #{userId,jdbcType=BIGINT} AND share_del = 0
        ORDER BY share_id DESC
  describe
      In 4.1.1, I can use “act_stats_${tabIndex}” assign table index，and it works ok. Now, it can't work, i print sql is right, but act_stats's data can't return.

**Comment by zjcnb** [comment]
@qiuweilu  Can you provider a demo project? We will check it.

**Comment by qiuweilu** [comment]
describe
act_stats,act_stats_0,act_stats_1 ...  act_stats_10，the foreign key of the sub table is is fk_id，but sometimes I want assign a fixed table, when I do this and it can't work.

**Comment by terrymanu** [comment]
There are no enough information, I just close the issue.
