### ISSUE TITLE
date cast error

### ISSUE THREAD

**Issue by qiuweilu** [apache/shardingsphere#13849]
version
shardingsphere-jdbc-core-5.0.0.jar:5.0.0

question
property：private Date cmntCtime;

class java.time.LocalDateTime cannot be cast to class java.sql.Timestamp

org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet.getTimestamp(ShardingSphereResultSet.java:249) ~[shardingsphere-jdbc-core-5.0.0.jar:5.0.0]

**Comment by strongduanmu** [comment]
@qiuweilu Thank you for your feedback, can you submit issue according the template?
