### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by xiongchengqq** [apache/shardingsphere#13855]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Sharding 5.0.0 is used and configuration problems occur
### Actual behavior
mapping values are not allowed here
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Configuration is as follows:
 spring:
    shardingsphere:
       dataSources: fudabd-common-plat-db
           fudabd-common-plat-db:
               type: com.zaxxer.hikari.HikariDataSource
               driverClassName: com.mysql.cj.jdbc.Driver

### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/80461901/143976864-408295ee-7465-4af4-8e20-49d40310439e.png)

**Comment by zjcnb** [comment]
@xiongchengqq I think your configuration hava a mistake, you can change `dataSources: fundabd-common-plat-db` to `dataSources`. remove fundabd-common-plat-db. And try it again.

**Comment by xiongchengqq** [comment]
![image](https://user-images.githubusercontent.com/80461901/143979158-0214b2dc-5d49-4943-9c54-47183c653f41.png)
 I am showing that the database driver is not found

**Comment by zjcnb** [comment]
You can check your mysql server version. Is mysql 8.x ?

**Comment by xiongchengqq** [comment]
是的,我的服务器是8.x的

**Comment by zjcnb** [comment]
> 是的,我的服务器是8.x的

translate english please.

**Comment by xiongchengqq** [comment]
Yes, my server is 8.x

**Comment by xiongchengqq** [comment]
spring:
  shardingsphere:
    dataSources:
      fudabd-common-plat-db:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:13306/fudabd_common_plat_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&skip-host-cache=true
        username: root
        password: 123456

**Comment by xiongchengqq** [comment]
My configuration

**Comment by zjcnb** [comment]
It 's no problem when i used your configuration.

![image](https://user-images.githubusercontent.com/33742097/143980572-5558d2fb-b436-4785-bf3f-04d60e207499.png)

Can you provider a demo project ?

**Comment by xiongchengqq** [comment]
Import dependency issues
