### ISSUE TITLE
If I want to learn the source code of "shardingShere", is there any good way to recommend it?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13854]
version：
  master

If I want to learn the source code of "shardingShere", is there any good way to recommend it?

**Comment by lanchengx** [comment]
Hi @CrackerSuperior , [Sig](https://community.sphere-ex.com/c/22-category/22) in the Chinese community is a good choice, 
and recently [Meetup](https://mp.weixin.qq.com/s/4BHVxbJxEe2o_FvpH6rTUQ) is also worth paying attention to.

**Comment by CrackerSuperior** [comment]
> Hi @CrackerSuperior , [Sig](https://community.sphere-ex.com/c/22-category/22) in the Chinese community is a good choice, and recently [Meetup](https://mp.weixin.qq.com/s/4BHVxbJxEe2o_FvpH6rTUQ) is also worth paying attention to.

ok，thanks
