### ISSUE TITLE
Does ShardingComplexRoutingEngine have all the functions of ShardingFederatedRoutingEngine?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#13869]
Does ShardingComplexRoutingEngine have all the functions of ShardingFederatedRoutingEngine?

**Comment by strongduanmu** [comment]
@marker-wu No, they are different. ShardingComplexRoutingEngine cannot handle cross-database queries.

**Comment by marker-wu** [comment]
> handle cross-database queries.

![image](https://user-images.githubusercontent.com/45256940/144157623-3a96757b-ff44-45e0-b1ad-f155febbf99c.png)
Doesn't this support cross-database query?

**Comment by marker-wu** [comment]
Why is there no follow-up?

**Comment by strongduanmu** [comment]
> Why is there no follow-up?

@marker-wu Sorry for late reply. ShardingComplexRoutingEngine cannot handle cross-database queries, it can only query the data in the same database according to the Cartesian product.

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
