### ISSUE TITLE
CONNECTION_STRICTLY  must be memory merge？why merge is GroupByStreamMergedResult？ 

### ISSUE THREAD

**Issue by SpriderMan** [apache/shardingsphere#13863]
excute sql：SELECT o.user_id FROM t_order_0 o JOIN t_order_item_0 i ON o.order_id=i.order_id and o.user_id IN
         (  ? ,   ?,  ? ,  ?,  ?) group by o.user_id ORDER BY user_id ASC 

![image](https://user-images.githubusercontent.com/18304842/144004463-451d17b7-9a72-487c-95ad-c8af59f38b0e.png)
![image](https://user-images.githubusercontent.com/18304842/144004496-9752ab05-e930-4f6a-b8a1-0b61237d035d.png)

![image](https://user-images.githubusercontent.com/18304842/144004691-6d8bee6c-a782-456b-b47b-2fcda90cbff3.png)

**Comment by terrymanu** [comment]
Close because of staled.
