### ISSUE TITLE
'show instance list' doesn't provide port running in standalone mode

### ISSUE THREAD

**Issue by dachuan9e** [apache/shardingsphere#13876]
'show instance list' doesn't provide port when proxy run in standalone mode.  The result is like 'xxx.xx.xx.xx@'.  

The result has port like 'xxx.xx.xx.xx@3307' when proxy run in cluster mode

**Comment by RaigorJiang** [comment]
This is because the port is not saved in metadata, which can only be obtained in the registry.
@menghaoranss  please help to see if this value can be added to metadata?

**Comment by dachuan9e** [comment]
The port is necessary for some case. Please consider it.

**Comment by lanchengx** [comment]
Fixed in https://github.com/apache/shardingsphere/pull/14930
