### ISSUE TITLE
关于ShardingSphereXA分布式事务

### ISSUE THREAD

**Issue by yeruilong** [apache/shardingsphere#13871]
WARN  com.atomikos.datasource.xa.XAResourceTransaction - XA resource 'resource-1-master': suspend for XID '3139322E3136382E35362E312E746D313633383237323939323830323030303031:3139322E3136382E35362E312E746D31' raised -5: invalid arguments were given for the XA operation
com.mysql.cj.jdbc.MysqlXAException: XAER_INVAL: Invalid arguments (or unsupported command)

访问接口报了个错，没找到解决方案

**Comment by menghaoranss** [comment]
@yeruilong For English only, please translate to English first.

**Comment by yeruilong** [comment]
about ShardingSphereXA Distributed transaction：

  @ShardingTransactionType(TransactionType.XA)
  @Transactional(propagation = Propagation.REQUIRED,rollbackFor = Exception.class)
  public Boolean A() {
    mapperA.updateById();
    B();
}

  @Transactional(propagation = Propagation.REQUIRES_NEW,rollbackFor = Exception.class)
  public Boolean b() {
       mapperB.updateById();
 }
WARN com.atomikos.datasource.xa.XAResourceTransaction - XA resource 'resource-1-master': suspend for XID '3139322E3136382E35362E312E746D313633383237323939323830323030303031:3139322E3136382E35362E312E746D31' raised -5: invalid arguments were given for the XA operation
com.mysql.cj.jdbc.MysqlXAException: XAER_INVAL: Invalid arguments (or unsupported command)

when I call interface reported an error, but no solution was found

**Comment by yeruilong** [comment]
why close this issue?and not give me solution


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 晚上11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] 关于ShardingSphereXA分布式事务 (Issue #13871)





 
Closed #13871.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
