### ISSUE TITLE
Whether SQL parsing can be skipped？

### ISSUE THREAD

**Issue by DreamPWJ** [apache/shardingsphere#13879]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.  yes
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues). yes
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview). yes

Now I just divide table part library, we have hundreds of tables, only need a few tables to do table processing, there is a lot of complex SQL, integration

Shardingsphere will directly cause a lot of SQL to fail to run in the future, and the modification is tedious. We only need to parse a few tables specified, not all tables. Is this configuration available?

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by DreamPWJ** [comment]
For projects running for several years, it is a huge test cost to retrofit incompatible SQL, and we only want shardingSphere

To process and parse the tables that we want to fragment

**Comment by strongduanmu** [comment]
Hi @DreamPWJ, thank you for your feedback. The parsing engine is the foundation of Apache ShardingSphere, and all functions depend on the results of the parsing, so parsing cannot be skipped.

If you have requirements, you can manage sharding tables and other tables in the business layer by configuring multiple data sources.

**Comment by DreamPWJ** [comment]
@strongduanmu 
Configuring multiple data sources adds to our transformation and maintenance costs, and we now only have two tables to shard, which can be specified and then parsed if possible

**Comment by DreamPWJ** [comment]
When most people use Shardingsphere, it means that the project is already very large, rather than a new project, and the transformation cost is very large. Hopefully

Shardingsphere can reduce the transformation cost and better access to the project. Is there any plan for this in the future?

**Comment by strongduanmu** [comment]
How to distinguish between sharding and non-sharding tables? Do you still need sql parsing, and then know whether to include a sharding table based on the parsing result?

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/144349928-2798d1ab-1a54-4c7b-9312-07ade64cc108.png)
Add a switch that tells the developer whether to parse all tables or to parse specified tables

**Comment by DreamPWJ** [comment]
Is there anything new? @strongduanmu

**Comment by terrymanu** [comment]
No, SQL parser is the required module of ShardingSphere to understand SQL, it cannot be skipped with any reason.
