### ISSUE TITLE
The library sharding-jdbc-spring-boot-starter And shardingsphere-sharding-spring-boot-starter 

### ISSUE THREAD

**Issue by isfong** [apache/shardingsphere#13880]
What's the difference ? thanks~

**Comment by warriorsliuz** [comment]
`
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0</version>
        </dependency>
`

**Comment by isfong** [comment]
> ```
> <dependency>
>      <groupId>org.apache.shardingsphere</groupId>
>      <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
>      <version>5.0.0</version>
> </dependency>
> ```
Are you saying that `shardingsphere-jdbc-core` can replace `sharding-jdbc` ?

**Comment by terrymanu** [comment]
They are the different version
