### ISSUE TITLE
Elastic expansion

### ISSUE THREAD

**Issue by JWJ32** [apache/shardingsphere#13881]
When migrating 40w data using sharding-proxy(4.1.1) and ahrding-scaling(4.1.1), the CPU reaches its peak and proxy automatically stops,How do I fix thi
![1](https://user-images.githubusercontent.com/67968000/144185889-d9f44f0e-b69f-4384-a7aa-da17b230d81d.jpg)
s?

**Comment by strongduanmu** [comment]
Hi @JWJ32, can you try the latest 5.0.0 version? We have made a lot of optimizations.

**Comment by sandynz** [comment]
Hi @JWJ32 , `5.1.0` will be released soon, we've added rate limiter and read batch size to protect system load.

**Comment by sandynz** [comment]
Closed since no response for a long time.
