### ISSUE TITLE
How to set the default data source in version 5

### ISSUE THREAD

**Issue by Hachiko-JQ** [apache/shardingsphere#13896]
## Question
spring.shardingsphere.sharding.default-data-source-name=

This cannot be set in version 5

**Comment by strongduanmu** [comment]
Hi @Hachiko-JQ, you can try the new feature sql hint in master branch.

**Comment by lanchengx** [comment]
Hi @Hachiko-JQ, In Proxy `CREATE DEFAULT SINGLE TABLE RULE`  statement is an alternative to `default-data-source-name`, please refer to this [link](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/)

**Comment by RaigorJiang** [comment]
This issue seems to be resolved, I will close it. 
If you still have problems, please reopen it or submit a new one.
