### ISSUE TITLE
Proofread the Oracle DDL SQL Definitions

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#13909]
As a follow-up issue on #10513, there are still some Oracle DDL SQLs (ALTER, CREATE and DROP) not been proofread yet. 

### Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for MySQL, PostgreSQL, SQLServer, and Oracle, which means we have to understand different database dialects SQLs.

**Comment by tristaZero** [comment]
Hi @strongduanmu Do we have a to-do list of the SQL proofreading project?  That will be helpful to steer @Liangda-w to a certain goal.

**Comment by strongduanmu** [comment]
@tristaZero I'm very sorry, for the oracle dialect, there is currently no checklist, we will list this checklist as soon as possible @tuichenchuxin .

**Comment by tuichenchuxin** [comment]
@strongduanmu sure, I'll add the checklist.

**Comment by tuichenchuxin** [comment]
@Liangda-w Hi, I have cloned oracle sql grammer from [offical doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/index.html) to make a task list in #6480.  And I'll complete the task when you complete some grammer. It will be easier for other communities to see what else they can do.

**Comment by Liangda-w** [comment]
Hi @tuichenchuxin @tristaZero @strongduanmu, thank you so much! I'll start with DDL - CREATE SQLs:) 

Besides, I notice some of them (e.g. CREATE FUNCTION) are [PL/SQL](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/sql-statements-for-stored-plsql-units.html#GUID-C918310F-F1BB-41D7-9466-B558B70DDFFE), is there anything special that we need to take care of for those SQLs?

**Comment by tuichenchuxin** [comment]
@Liangda-w I think SQL and PL/SQL in oracle is defined same. So, there is nothing special.
`PL/SQL is Oracle's procedural language extension to SQL. PL/SQL allows you to mix SQL statements with procedural constructs. PL/SQL provides the capability to define and execute PL/SQL program units such as procedures, functions, and packages. PL/SQL program units generally are categorized as anonymous blocks and stored procedures.`

**Comment by strongduanmu** [comment]
This issue has not been finished, so I will reopen it.
