### ISSUE TITLE
  shardingproxy execute select * from allTables limit 0;

### ISSUE THREAD

**Issue by hgbit** [apache/shardingsphere#13914]
version: shardingsphere 4.0.1

I use shardingProxy, mysql client is navicat
execute "select * from logicTable where shardingColum = xxx;"
shardingproxy execute select * from allTables limit 0;
how to config letting shardingproxy not execute it?
log:
[INFO ] 15:26:22.752 [ShardingSphere-Command-13] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * from lc_vocabulary_book_word_141 a WHERE vocabularyId = 626852710238396416
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Logic SQL: SELECT * FROM `lexicon_dev`.`lc_vocabulary_book_word` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - SQLStatement: SelectSQLStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@2d2dea4e, tablesContext=TablesContext(tables=[Table(name=lc_vocabulary_book_word, alias=Optional.absent())], schema=Optional.of(lexicon_dev))), projectionsContext=ProjectionsContext(startIndex=7, stopIndex=7, distinctRow=false, projections=[ShorthandProjection(owner=Optional.absent())], columnLabels=[id, vocabularyid, wordvalue, lanid, createtime, updatetime]), groupByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.groupby.GroupByContext@1c043a5b, orderByContext=org.apache.shardingsphere.sql.parser.relation.segment.select.orderby.OrderByContext@493c1908, paginationContext=org.apache.shardingsphere.sql.parser.relation.segment.select.pagination.PaginationContext@6bdecb6d, containsSubquery=false)
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_0` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_1` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_2` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_3` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_4` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_5` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_6` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_7` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_8` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_9` LIMIT 0
[INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_10` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_11` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_12` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_13` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_14` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_15` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_16` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_17` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_18` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_19` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_20` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_21` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_22` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_23` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_24` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_25` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_26` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_27` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_28` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_29` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_30` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_31` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_32` LIMIT 0
[INFO ] 15:26:22.831 [ShardingSphere-Command-15] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT * FROM `lc_vocabulary_book_word_33` LIMIT 0

**Comment by RaigorJiang** [comment]
> [INFO ] 15:26:22.830 [ShardingSphere-Command-15] ShardingSphere-SQL - Logic SQL: SELECT * FROM lexicon_dev.lc_vocabulary_book_word LIMIT 0

The logic SQL is `LIMIT 0`, so please check your input SQL.
It may also be a problem caused by Navicat, you can try to verify the problem with the MySQL command line.

**Comment by RaigorJiang** [comment]
No response.
