### ISSUE TITLE
Authority issue about select from information_schema.SCHEMATA

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#13913]
Refer to #13912.

When use Navicat to connect with ShardingSphere-Proxy, Navicat will query schemas to show, and Proxy does not check user's privileges.

![image](https://user-images.githubusercontent.com/5668787/144557731-61ab16f7-d7fb-453e-b9af-8ab4aeb7483d.png)

**Comment by lanchengx** [comment]
@RaigorJiang plz assign to me.
