### ISSUE TITLE
Insert sql and use function to cause parameter loss problem

### ISSUE THREAD

**Issue by cherubimLV** [apache/shardingsphere#13929]
### Expected behavior：

Use sql with mysql function to insert data, for example：

```
insert into user (id,name,phone,create_time,create_id)
value
(#{id},#{name},#{phone},FROM_UNIXTIME(#{createTime}/1000,'%Y-%m-%d %H:%i:%S'),#{createId})
```

The parameters passed in strictly in accordance with normal conditions should be able to execute successfully.

But the actual situation is that the parameter ``#{createTime}`` will be lost, causing an exception to be thrown:

Error updating database.  Cause: java.sql.SQLException: No value specified for parameter 5。

After searching for the reason, it was found in the method:

``org.apache.shardingsphere.sql.parser.sql.common.util.ExpressionExtractUtil#getParameterMarkerExpressions``

```java
public static List<ParameterMarkerExpressionSegment> getParameterMarkerExpressions(final Collection<ExpressionSegment> expressions) {
        List<ParameterMarkerExpressionSegment> result = new ArrayList<>();
        for (ExpressionSegment each : expressions) {
            //There is no support for ExpressionProjectionSegment
            if (each instanceof ParameterMarkerExpressionSegment) {
                result.add((ParameterMarkerExpressionSegment) each);
            }
            // TODO support more expression type if necessary 
            if (each instanceof BinaryOperationExpression) {
                result.addAll(getParameterMarkerExpressions(Collections.singletonList(((BinaryOperationExpression) each).getLeft())));
                result.addAll(getParameterMarkerExpressions(Collections.singletonList(((BinaryOperationExpression) each).getRight())));
            }
        }
        return result;
    }
```

After inspection, it was found that the method:

``org.apache.shardingsphere.sql.parser.mysql.visitor.statement.impl.MySQLStatementSQLVisitor#visitFunctionCall``

The parameter objects generated under the method are all ``ExpressionProjectionSegment``, which leads to the fact that the parameters used in the function call when inserting are not added to ``List<ParameterMarkerExpressionSegment>``.

When the object ``org.apache.shardingsphere.infra.rewrite.context.SQLRewriteContext#SQLRewriteContext`` is created later, as long as it is ``instanceof InsertStatementContext``, it will execute ``new GroupedParameterBuilder(
         ((InsertStatementContext) sqlStatementContext).getGroupedParameters(), ((InsertStatementContext) sqlStatementContext).getOnDuplicateKeyUpdateParameters())``For parameter construction, the number of parameters inserted into the function will be lost at the beginning
```java
public SQLRewriteContext(final ShardingSphereSchema schema, final SQLStatementContext<?> sqlStatementContext, final String sql, final List<Object> parameters) {
        this.schema = schema;
        this.sqlStatementContext = sqlStatementContext;
        this.sql = sql;
        this.parameters = parameters;
        addSQLTokenGenerators(new DefaultTokenGeneratorBuilder().getSQLTokenGenerators());
        parameterBuilder = ((sqlStatementContext instanceof InsertStatementContext) && (null == ((InsertStatementContext) sqlStatementContext).getInsertSelectContext()))
                ? new GroupedParameterBuilder(
                        ((InsertStatementContext) sqlStatementContext).getGroupedParameters(), ((InsertStatementContext) sqlStatementContext).getOnDuplicateKeyUpdateParameters())
                : new StandardParameterBuilder(parameters);
    }
```

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin, can you help check this issue on master branch? I think it has been supported in master branch.

**Comment by tuichenchuxin** [comment]
Ok, I’ll check it later&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Zhengqiang Duan ***@***.***&gt;
Date: Sat,Dec 4,2021 2:41 PM
To: apache/shardingsphere ***@***.***&gt;
Cc: tuichenchuxin ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/shardingsphere] Insert sql and use function to cause parameter loss problem (Issue #13929)





 
Hi @tuichenchuxin, can you help check this issue on master branch? I think it has been supported in master branch.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuichenchuxin** [comment]
@cherubimLV I have checked your sql in master branch. It can be supported now.

**Comment by zhangwangren** [comment]
> Hi @tuichenchuxin, can you help check this issue on master branch? I think it has been supported in master branch.
Excuse me!  I want to know if the master branch can be used SUBSTRING() in the INSERT INTO VALUES? Like this 
INSERT INTO tb_user(user_no, user_name) VALUES (#{userNo}, SUBSTRING(#{userName}, 1, 2));
