### ISSUE TITLE
Compile error when creating new file

### ISSUE THREAD

**Issue by cherubimLV** [apache/shardingsphere#13932]
I created a new file to compile, prompting a compilation error

error 

information:
.......
[INFO] shardingsphere-readwrite-splitting-core ............ FAILURE [ 23.090 s]
.......
[INFO] shardingsphere-proxy-distribution .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:06 min (Wall Clock)
[INFO] Finished at: 2021-12-04T17:15:57+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project shardingsphere-readwrite-splitting-core: Too many files with unapproved license: 1 See RAT report in: E:\IDEAword\shardingsphere\shardingsphere-features\shardingsphere-readwrit
e-splitting\shardingsphere-readwrite-splitting-core\target\rat.txt -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shardingsphere-readwrite-splitting-core

[rat.txt](https://github.com/apache/shardingsphere/files/7653683/rat.txt)

**Comment by totalo** [comment]
because the license check failed, you can add `-Drat.skip=true` to skip the check.

**Comment by cherubimLV** [comment]
Thank you
