### ISSUE TITLE
Can simplify the dependency slightly in the next version?

### ISSUE THREAD

**Issue by Comven** [apache/shardingsphere#13946]
version: shardingsphere-jdbc-core-spring-boot-starter-5.0.0 and 5.1.0

Upgrade from version 4.x to 5.x, The dependency of version 5. X is almost 20M more than that of version 4. X . shardingsphere-jdbc-core-spring-boot-starter even introduces a large number of 'elasticjob' component packages. I hope the next version can be slightly streamlined and optimized. 

Thanks !

**Comment by strongduanmu** [comment]
@Comven Yes, we have also noticed this problem, and we will optimize it in later versions to implement on-demand loading of features.

**Comment by Comven** [comment]
> @Comven Yes, we have also noticed this problem, and we will optimize it in later versions to implement on-demand loading of features.

When is an optimized version for this problem expected to be released?

**Comment by Comven** [comment]
5.1.0 still contains a large number of elastic job jar packages.

![image](https://user-images.githubusercontent.com/8464801/154453319-d94b2729-e556-4d0d-b3a8-acd7814c27fd.png)

**Comment by linghengqian** [comment]
- The `shardingsphere-jdbc-core-spring-boot-starter` jar related to this issue has been removed at https://github.com/apache/shardingsphere/issues/22469, this issue does not seem suitable for further discussion. 
- I assume this issue should change the target?

**Comment by linghengqian** [comment]
- The related spring boot starter has been deleted and there is no point in opening the current issue.
