### ISSUE TITLE
How does "shardingsphere" connect a group of mysql with a master-slave relationship?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13963]
Version：
  master，shardingshpere-proxy

Question：
  Now I have two mysqls, one master and one backup. I want to use "fragments" to link them. When the master is damaged, it is hoped that the "sharding" can automatically switch to the slave library.

**Comment by zjcnb** [comment]
@CrackerSuperior Hi, You can use db-discovery module. it's support mysql mgr.

**Comment by CrackerSuperior** [comment]
> 

Is there a simple example or configuration document description? The official document does not seem to have this configuration description?

**Comment by CrackerSuperior** [comment]
> @CrackerSuperior嗨，您可以使用 db-discovery 模块。它支持 mysql mgr。

Is there a simple example or configuration document description? The official document does not seem to have this configuration description?

**Comment by zjcnb** [comment]
Because, it 's adjusting api now, new api refer to : #13902

**Comment by zjcnb** [comment]
If you use 5.0.0 GA version, you can refer to : https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/config-database-discovery.yaml

**Comment by CrackerSuperior** [comment]
> If you use 5.0.0 GA version, you can refer to : https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/config-database-discovery.yaml

![image](https://user-images.githubusercontent.com/45088781/144961835-2b9b5e76-6260-48a1-b310-4e2187ce2d46.png)
What should be filled in this "keepAliveCron"?

**Comment by zjcnb** [comment]
cron expression, '0/5 * * * * ?' means to execute every 5 seconds

**Comment by CrackerSuperior** [comment]
> cron expression, '0/5 * * * * ?' means to execute every 5 seconds

ok, also, under this function, is the master-slave replication of mysql built manually or sharding helps me build it?

**Comment by zjcnb** [comment]
> > cron expression, '0/5 * * * * ?' means to execute every 5 seconds
> 
> ok, also, under this function, is the master-slave replication of mysql built manually or sharding helps me build it?

You need build it by yourself.

**Comment by CrackerSuperior** [comment]
> > > cron expression, '0/5 * * * * ?' means to execute every 5 seconds
> > 
> > 
> > ok, also, under this function, is the master-slave replication of mysql built manually or sharding helps me build it?
> 
> You need build it by yourself.

ok,thank you very much！

**Comment by wl4g** [comment]
Currently I am also testing this database discovery function. I wrote it myself before. You can refer to my docker-based mgr deployments: [11](https://blogs.wl4g.com/archives/2477)

**Comment by wl4g** [comment]
Currently I am also testing this database discovery function. I wrote it myself before. You can refer to my docker-based mgr deployments: [https://blogs.wl4g.com/archives/2477](https://blogs.wl4g.com/archives/2477)
