### ISSUE TITLE
Add document of SM3 and SM4 of encryptor

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#13986]
The encryptor SM3 and SM4 have completed in #13894, please add document on https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/builtin-algorithm/encrypt/ and https://shardingsphere.apache.org/document/current/cn/dev-manual/encryption/

**Comment by cheese8** [comment]
ok, please assign it to me, thanks. @terrymanu

**Comment by strongduanmu** [comment]
@cheese8 I just assign this issue to you.

**Comment by terrymanu** [comment]
Welcome

**Comment by cheese8** [comment]
Does the en documents should be also added? @terrymanu

**Comment by terrymanu** [comment]
> Does the en documents should be also added? @terrymanu

Sure. I saw you have already finish English document too.
