### ISSUE TITLE
Add syntax for `DROP SHARDING KEY GENERATOR`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13999]
For details, please refer to https://github.com/apache/shardingsphere/issues/13994

The ANTLR definition syntax is as follows:

```sql
DROP SHARDING KEY GENERATOR keyGeneratorName (COMMA keyGeneratorName)*;
```

Examples are as follows:

```sql
DROP SHARDING KEY GENERATOR uuid_key_generator;
```

**Comment by Liangda-w** [comment]
Hi, I'd like to try this:)

**Comment by lanchengx** [comment]
Thanks for your contribution, @RaigorJiang will assign it to you 😀
We will review your pr and give you feedback
