### ISSUE TITLE
shardingsphere-jdbc not support openGauss batchInsert protocol

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#13996]
## Feature Request
shardingsphere-jdbc support openGauss batchInsert protocol.

### Is your feature request related to a problem?
Yes, this causes build tpcc warehouses too slow.
### Describe the feature you would like.
support openGauss batchInsert protocol, improve build warehouses of tpcc's speed.

**Comment by TeslaCN** [comment]
I did some research. The `ShardingSpherePreparedStatement` has already used the `addBatch` method. The openGauss JDBC Driver will use the `BatchBind` protocol to communicate with openGauss server.

https://github.com/apache/shardingsphere/blob/15880ece98257a2019847c0ff0cd9dde3d8f721c/shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java#L578-L586
