### ISSUE TITLE
is encrypt not support MyBatis useGeneratedKeys ？

### ISSUE THREAD

**Issue by Un-use** [apache/shardingsphere#13992]
### when i use config，like this
    encryptors:
      encryptor_custom:
        type: custom
    tables:
      table1:
        columns:
          column1:
            plainColumn: column1
            cipherColumn: column1Cipher
            encryptorName: encryptor_custom
### SQL like this,  I can get generate Key, `id`
    INSERT INTO table1 (column1) VALUES (#{column1});
###  remove `plainColumn`, it doesn't work, can't get generate key 
    encryptors:
      encryptor_custom:
        type: custom
    tables:
      table1:
        columns:
          column1:
            cipherColumn: column1Cipher
            encryptorName: encryptor_custom

### it can be support？

**Comment by strongduanmu** [comment]
Hi @Un-use, thank you for your feedback. Can you try 5.0.0 GA version? I think this bug has been fixed in this version.

**Comment by Un-use** [comment]
您好：    您发的邮件已收到，我会尽快给您回复。    祝好！                                             --Unuse

**Comment by Un-use** [comment]
### finally i find the error, throw an exception, but it be caught....
### how to fix this? need throw the exception
![image](https://user-images.githubusercontent.com/13214561/145320912-a6b8d13f-dd21-4900-904f-6567caad07b2.png)

**Comment by strongduanmu** [comment]
@Un-use The problem that the exception was not thrown is also fixed in the 5.0.0 GA version. Welcome to upgrade.

**Comment by Un-use** [comment]
upgraded, thank you.
