### ISSUE TITLE
DistSQL plans to support `CREATE SHARDING KEY GENERATOR`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13994]
`KeyGenerator`  is used to generate [Distributed Primary Key](https://shardingsphere.apache.org/document/current/en/features/sharding/concept/key-generator/) in ShardingSphere, and is configured as follows in the Sharding feature:

![image](https://user-images.githubusercontent.com/52209337/145165511-428b4f7b-6a46-4743-893c-27d99a6e01b2.png)

At present, in the Sharding feature, DistSQL's support for `KeyGenerator` is not complete. It is only limited to creating `KeyGenerator` when creating `ShardingTableRule`. This method is not friendly enough for `KeyGenerator` reuse and property adjustment.

Therefore, in the Sharding feature, DistSQL plans to provide more complete support for the `KeyGenerator` property.

The ANTLR definition syntax is as follows:

```sql
CREATE SHARDING KEY GENERATOR keyGeneratorDefination (COMMA keyGeneratorDefination)*

keyGeneratorDefination: keyGeneratorName LP algorithmDefinition RP;
keyGeneratorName: IDENTIFIER;
algorithmDefinition: TYPE LP NAME EQ algorithmName (COMMA PROPERTIES LP algorithmProperties? RP)? RP;
```

Examples are as follows:

```sql
CREATE SHARDING KEY GENERATOR uuid_key_generator(TYPE(NAME=uuid,PROPERTIES("worker-id"=123)));
```

For the specific details of the implementation, please refer to [`CREATE SHARDING ALGORITHM`](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/#sharding-table-rule)

The files that may need to be adjusted during the implementation process are as follows:

- Revise:

  - `src/main/antlr4/imports/sharding/RDLStatement.g4`  is used for [RDL]
  -  `src/main/antlr4/imports/sharding/RQLStatement.g4`  is used for [RQL]
  - `src/main/antlr4/imports/sharding/Keyword.g4`
  - `ShardingDistSQLStatement.g4`
  - `ShardingDistSQLStatementVisitor.java`
  - `org.apache.shardingsphere.infra.distsql.update.RuleDefinitionUpdater` is used for [RDL](https://shardingsphere.apache.org/document/current/en/concepts/distsql/) statements
  - `org.apache.shardingsphere.infra.distsql.query.DistSQLResultSet` is used for [RQL](https://shardingsphere.apache.org/document/current/en/concepts/distsql/) statements
  - `src/main/resources/sql/supported/` add test statement to the corresponding file
  - `src/main/resources/case/` adds a test case to the corresponding file
  - Add the corresponding `TestCase` in `SQLParserTestCases`

- Add

  - The syntax corresponding to `DistSQLStatement.java`
  - The RDL syntax corresponding to `RuleDefinitionUpdater.java`
  - The RQL syntax corresponding to `DistSQLResultSet.java`
  - `Updater` corresponding unit test
  - `TestCase` class
  - The `Assert` class for verifying test results
  - Documents `sharding.cn.md` and `sharding.en.md`

**Comment by yx9o** [comment]
I want to try this.

**Comment by lanchengx** [comment]
@yx9o  Welcome, @RaigorJiang will assign it to you 😀
