### ISSUE TITLE
Add syntax for `ALTER SHARDING KEY GENERATOR`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#13997]
For details, please refer to https://github.com/apache/shardingsphere/issues/13994

The ANTLR definition syntax is as follows:

```sql
ALTER SHARDING KEY GENERATOR keyGeneratorDefination (COMMA keyGeneratorDefination)*

keyGeneratorDefination: keyGeneratorName LP algorithmDefinition RP;
keyGeneratorName:IDENTIFIER;
algorithmDefinition: TYPE LP NAME EQ algorithmName (COMMA PROPERTIES LP algorithmProperties? RP)? RP;
```

Examples are as follows:

```sql
ALTER SHARDING KEY GENERATOR uuid_key_generator(TYPE(NAME=uuid,PROPERTIES("worker-id"=123)));
```

This syntax overlaps with `CREATE SHARDING KEY GENERATOR` statement, need to complete the `CREATE SHARDING KEY GENERATOR` statement first.

**Comment by dongzl** [comment]
@lanchengx    I want to try it.

**Comment by dongzl** [comment]
> @dongzl Welcome, @RaigorJiang will assign it to you 😀

Thanks.
