### ISSUE TITLE
failed backup database with postgis extension enabled  when using pg_dump  

### ISSUE THREAD

**Issue by oneslideicywater** [apache/shardingsphere#14008]
It's very nice that I successfully build an image `apache/shardingsphere-proxy:5.0.1-SNAPSHOT` [refer to this issue](https://github.com/apache/shardingsphere/issues/13978), the previous problem solved!. 

but there's another question occurs:

dump the logical database `sharding_db` (with postgis extension enabled using `CREATE EXTENSION postgis;`) 
 failed when using pg_dump  
:

```bash
root@a15d5aac4a11:/var/lib/postgresql/data# pg_dump -U postgres -d sharding_db -h 192.168.10.53 -p 13308 > test.sql
Password: 
pg_dump: [archiver (db)] query failed: ERROR:  You have an error in your SQL syntax
pg_dump: [archiver (db)] query was: LOCK TABLE public.spatial_ref_sys IN ACCESS SHARE MODE
```

but dump the physical database( not proxyed by sharding-proxy) is ok :

```bash
pg_dump -U postgres -d geo -h 192.168.10.53 -p 5432 > test.sql
```

**Comment by terrymanu** [comment]
No plan to support pg_dump now, anybody interesting this issue?

**Comment by terrymanu** [comment]
Nobody interested the issue for long time, I just close it.
