### ISSUE TITLE
When executing range query with multiple tables and merging the query result , shardingsphere throws the NullPointerExpection？

### ISSUE THREAD

**Issue by Lacxner** [apache/shardingsphere#14016]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere-JDBC 5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Spring Boot、MyBtatisPlus、ShardingSphere-JDBC
### Expected behavior
return two tables merged query result.
### Actual behavior
when merging the query result, throws an NullPointerException in ShardingSphere
### Reason analyze (If you can)

Here throws the NullPointerException!
![1639038212](https://user-images.githubusercontent.com/35280133/145362643-0fa8e6be-5e58-4b4b-902a-fdab013eacc5.png)
I find ShardingSphere exclude the table which is in config.
![1639038466](https://user-images.githubusercontent.com/35280133/145362789-4542c9e0-2c6c-45ad-b4b4-8cc5060bb734.png)
![1639038664(1)](https://user-images.githubusercontent.com/35280133/145362804-ac05e18c-0447-4017-bfdc-8adc32c665bf.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.config class

        ShardingRuleConfiguration shardingRuleConfiguration = new ShardingRuleConfiguration();
        Properties algorithmProperties = new Properties();
        algorithmProperties.setProperty("strategy", "STANDARD");
        algorithmProperties.setProperty("algorithmClassName", "com.diantoushi.duoduo.config.MonthShardingAlgorithm");
        ShardingSphereAlgorithmConfiguration shardingSphereAlgorithmConfiguration = new ShardingSphereAlgorithmConfiguration("CLASS_BASED", algorithmProperties);
        Map<String, ShardingSphereAlgorithmConfiguration> shardingSphereAlgorithmConfigurationMap = new HashMap<>();
        shardingSphereAlgorithmConfigurationMap.put("monthShardingAlgorithm", shardingSphereAlgorithmConfiguration);
        shardingRuleConfiguration.setShardingAlgorithms(shardingSphereAlgorithmConfigurationMap);

        ShardingTableRuleConfiguration shardingTableRuleConfiguration = new ShardingTableRuleConfiguration("pdd_keyword_goods", "ds0.pdd_keyword_goods_20$->{(21..25)}$->{(1..12).collect{t -> t.toString().padLeft(2, \"0\")}}");
        ShardingStrategyConfiguration shardingStrategyConfiguration = new StandardShardingStrategyConfiguration("record_date", "monthShardingAlgorithm");
        shardingTableRuleConfiguration.setTableShardingStrategy(shardingStrategyConfiguration);
        KeyGenerateStrategyConfiguration keyGenerateStrategyConfiguration = new KeyGenerateStrategyConfiguration("id", "SNOWFLAKE");
        shardingTableRuleConfiguration.setKeyGenerateStrategy(keyGenerateStrategyConfiguration);
        shardingRuleConfiguration.setTables(Collections.singletonList(shardingTableRuleConfiguration));

        shardingRuleConfiguration.setBindingTableGroups(Collections.singletonList("pdd_keyword_goods"));

        Properties properties = new Properties();
        properties.setProperty("sql-show", "true");
        DataSource dataSource = null;
        try {
            dataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singletonList(shardingRuleConfiguration), properties);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return dataSource;

2.exception

Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitive(OrderByValue.java:64)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.<init>(OrderByValue.java:58)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:85)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:63)
	at org.apache.shardingsphere.infra.merge.MergeEngine.executeMerge(MergeEngine.java:90)
	at org.apache.shardingsphere.infra.merge.MergeEngine.merge(MergeEngine.java:80)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.mergeQuery(ShardingSpherePreparedStatement.java:393)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.getResultSet(ShardingSpherePreparedStatement.java:339)

**Comment by strongduanmu** [comment]
@Lacxner Thank you for your feedback. `singleTableDataNodes` is used to maintain the distribution info of a single table, and is used for automatic routing of a single table, so there is no need to load the sharding table here.

Your exception is similar to #13544, please check whether the metadata is loaded abnormally caused by the wrong configuration.

**Comment by Lacxner** [comment]
@strongduanmu I have seen the source code, I found that in default config the ShardingSphere will only load the first actual data node. If table is not existed, there will be none of the logic table.

**Comment by strongduanmu** [comment]
> 

@Lacxner Yes, so please ensure that the real table exists. In addition, can this issue be closed?

**Comment by Lacxner** [comment]
@strongduanmu Ok, I have closed the issue. I have some problem. It seems that if setting the property "check-table-metadata-enabled" to "true" then it will load all actual data nodes(It works well). So I can use this property when the first table is non-existent?

**Comment by strongduanmu** [comment]
Hi @Lacxner, the `check-table-metadata-enabled` attribute is used to verify the metadata of the sharding table. If it is enabled, the metadata of all actual tables will be loaded at startup, which will slow down the startup speed.
