### ISSUE TITLE
[Example] Add a new configuration example for load balance algorithm.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14013]
Hi community,

@cherubimLV submitted a new load balance algorithm of replica databases: `WeightReplicaLoadBalanceAlgorithm`, refer to #13943.
Now we need a new configuration example in the examples project. May be added in https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-raw-jdbc-example

If you want to help, please leave a comment 😀.

**Comment by cherubimLV** [comment]
Okay, I will add it and submit it

**Comment by RaigorJiang** [comment]
Haha, thank you!

**Comment by RaigorJiang** [comment]
Merged, thanks!
