### ISSUE TITLE
encrypt rewrite sql bug

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14010]
### Which version of ShardingSphere did you use?
the lastest master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
(no) subquery order by or group by、 alterTable 

``` sql
preview select a.address from ec_oms_order a group by a.address desc;
> select a.address_cipher as address from ec_oms_order a group by a.address_cipher desc;

preview select a.address from ec_oms_order a order by a.address desc;
> select a.address_cipher as address from ec_oms_order a order by a.address_cipher desc;

preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a group by a.address_cipher desc ) as tmp;

preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a order by a.address_cipher desc ) as tmp;

preview alter table ec_oms_order add column ab text after address;
> alter table ec_oms_order add column ab text after address_cipher;

preview alter table ec_oms_order add column ab text after address;
> alter table ec_oms_order add column ab text after address_cipher;

preview alter table ec_oms_order modify column ab text after address;
> alter table ec_oms_order modify column ab text after address_cipher;

preview alter table ec_oms_order change column ab ab text after address;
> alter table ec_oms_order change column ab ab text after address_cipher;

```

To remak : order by / group by can`t use xx_cipher as xx , so only rewrite to xx_cipher 

### Actual behavior

(no) subquery order by or group by

``` sql
preview select a.address from ec_oms_order a group by a.address desc;
> select a.address_cipher as address from ec_oms_order a group by a.address desc;

preview select a.address from ec_oms_order a order by a.address desc;
> select a.address_cipher as address from ec_oms_order a order by a.address desc;

preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a group by a.address desc ) as tmp;

preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a order by a.address desc ) as tmp;

preview alter table ec_oms_order add column ab text after address;
> alter table ec_oms_order add column ab text after address ;

preview alter table ec_oms_order add column ab text after address;
> alter table ec_oms_order add column ab text after address ;

preview alter table ec_oms_order modify column ab text after address;
> alter table ec_oms_order modify column ab text after address ;

preview alter table ec_oms_order change column ab ab text after address;
> alter table ec_oms_order change column ab ab text after address ;

```

### Reason analyze (If you can)

no implement rewrite order/group by encrypt columns .
no implement rewrite alter table xx after encrypt column .

### REMAK
can`t push this issue to 5.0.1-GA Milestone ？i think This is the basis for ensuring that encryption is available

**Comment by userkdg** [comment]
@cheese8 the issue samilar to [#13972 ], maybe repair all

**Comment by strongduanmu** [comment]
@userkdg Thank you for your feedback, We will support this case later.

**Comment by userkdg** [comment]
你好，很高兴收到您的邮件，谢谢。

**Comment by cheese8** [comment]
it's not the same, please assign it to me, thanks. @strongduanmu

**Comment by cheese8** [comment]
it seems that AfterColumnDefinitionSegment was not supported in AlterDefinitionSegment yet. @tuichenchuxin @strongduanmu

**Comment by userkdg** [comment]
> ### Which version of ShardingSphere did you use?
> the lastest master
> 
> ### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
> ShardingSphere-Proxy
> 
> ### Expected behavior
> (no) subquery order by or group by、 alterTable
> 
> ```sql
> preview select a.address from ec_oms_order a group by a.address desc;
> > select a.address_cipher as address from ec_oms_order a group by a.address_cipher desc;
> 
> preview select a.address from ec_oms_order a order by a.address desc;
> > select a.address_cipher as address from ec_oms_order a order by a.address_cipher desc;
> 
> preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> > select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a group by a.address_cipher desc ) as tmp;
> 
> preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> > select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a order by a.address_cipher desc ) as tmp;
> 
> preview alter table ec_oms_order add column ab text after address;
> > alter table ec_oms_order add column ab text after address_cipher;
> 
> preview alter table ec_oms_order add column ab text after address;
> > alter table ec_oms_order add column ab text after address_cipher;
> 
> preview alter table ec_oms_order modify column ab text after address;
> > alter table ec_oms_order modify column ab text after address_cipher;
> 
> preview alter table ec_oms_order change column ab ab text after address;
> > alter table ec_oms_order change column ab ab text after address_cipher;
> ```
> 
> To remak : order by / group by can`t use xx_cipher as xx , so only rewrite to xx_cipher
> 
> ### Actual behavior
> (no) subquery order by or group by
> 
> ```sql
> preview select a.address from ec_oms_order a group by a.address desc;
> > select a.address_cipher as address from ec_oms_order a group by a.address desc;
> 
> preview select a.address from ec_oms_order a order by a.address desc;
> > select a.address_cipher as address from ec_oms_order a order by a.address desc;
> 
> preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> > select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a group by a.address desc ) as tmp;
> 
> preview select count(1) as cnt from (select a.address from ec_oms_order a order by a.address desc ) as tmp;
> > select count(1) as cnt from (select a.address_cipher as address from ec_oms_order a order by a.address desc ) as tmp;
> 
> preview alter table ec_oms_order add column ab text after address;
> > alter table ec_oms_order add column ab text after address ;
> 
> preview alter table ec_oms_order add column ab text after address;
> > alter table ec_oms_order add column ab text after address ;
> 
> preview alter table ec_oms_order modify column ab text after address;
> > alter table ec_oms_order modify column ab text after address ;
> 
> preview alter table ec_oms_order change column ab ab text after address;
> > alter table ec_oms_order change column ab ab text after address ;
> ```
> 
> ### Reason analyze (If you can)
> no implement rewrite order/group by encrypt columns . no implement rewrite alter table xx after encrypt column .
> 
> ### REMAK
> can`t push this issue to 5.0.1-GA Milestone ？i think This is the basis for ensuring that encryption is available

**Comment by userkdg** [comment]
other sql rewrite bug 
1. ddl sql (not) exists 
``` sql
preview select address from ec_oms_order where exists(select b.address from ec_oms_order b where b.address=ec_oms_order.address);
> select address_cipher AS address from ec_oms_order where exists(select b.address from ec_oms_order b where b.address=ec_oms_order.address)

```
