### ISSUE TITLE
Support unsupported sql in parser.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#14015]
Hi community,
There are some unsupported sql in [this file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml)
You can help to support if you
>Be familiar with g4 file of Antlr (The grammars are RegularExpression-like)
Be familiar with java 

## Background
How is a SQL parsed?
`SQL definition file`
->(Parse to)
`AST`
->(Visit it)
`SQLStatment`

## Process
- Pick an unsupported sql and try to get why it's not supported.(antlr4 grammer? or not implement visit method. You can use [antlr4 plugins](https://plugins.jetbrains.com/plugin/7358-antlr-v4) to help analysis.You may need to visit offical doc to check the grammer.)
- After you fixing it, remember to add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case)
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) to make sure no exceptions.
## Notice
1.Left recursion can not work well in Antlr4,
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```
[Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.

## Sub Task

- [ ] assert_select_into_SQL
- [ ] assert_select_with_collate_with_marker
- [ ] assert_select_with_json_extract_sign_with_parameter_marker
- [ ] assert_select_with_json_unquote_extract_sign_with_parameter_marker
- [ ] assert_insert_with_first
- [ ] assert_dist_SQL_show_rule_parse_conflict
- [ ] create_bit_xor_table
- [ ] select_with_comment1
- [ ] select_with_comment2
- [ ] select_with_comment5
- [ ] select_with_comment6
- [ ] select_with_comment7
- [ ] select_with_comment8
- [ ] select_with_comment9
- [ ] select_with_comment10
- [x] alter_table_convert
- [x] alter_table_convert_collate
- [x] delimiter
- [ ] with_select
- [ ] with_select_comment
- [ ] select_cast
- [x] copy_table_from_stdin
- [x] create_type
- [ ] create_aggregate
- [ ] create_table_as_select
- [ ] create_schema
- [ ] alter_aggregate
- [x] create_conversion
- [x] alter_conversion
- [ ] create_foreign_data_wrapper
- [ ] create_server
- [ ] alter_foreign_data_wrapper
- [x] create_language
- [x] alter_language
- [ ] create_operator
- [ ] alter_operator
- [ ] create_statistics
- [ ] alter_statistics
- [x] create_text_search_dictionary
- [x] alter_text_search_dictionary
- [x] create_text_search_template
- [x] alter_text_search_template
- [x] create_tex_search_parser
- [x] alter_text_search_parser
- [ ] drop_foreign_data_wrapper
- [x] drop_language
- [ ] drop_schema
- [ ] drop_operator
- [ ] comment_on_table
- [ ] alter_view_rename
- [ ] create_table_no_valid
- [x] create_rule
- [ ] drop_rule
- [ ] create_as_select
- [ ] create_domain
- [x] drop_domain
- [ ] create_temp_table
- [ ] select_case_when
- [ ] select_like
- [ ] select_keyword
- [ ] drop_type
- [ ] alter_table_set
- [ ] alter_view_set
- [ ] create_publication

**Comment by tuichenchuxin** [comment]
This is related to #13792

**Comment by LeeGuoPing** [comment]
I want to  do ` drop_domain`

**Comment by dongzl** [comment]
I will do:

- `create_language`
- `alter_language`
- `drop_language`

**Comment by LeeGuoPing** [comment]
I want to do 

1. create_schema

1. drop_schema

**Comment by tuichenchuxin** [comment]
I have tested sql case from [mysql case ](https://github.com/mysql/mysql-server/tree/8.0/mysql-test/t)and [postgresql case](https://github.com/postgres/postgres/tree/master/src/test/regress/sql)
By using this [program](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test)
And then I get two unsupported sql files.
[mysql unsupported sql](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test/blob/main/src/main/resources/result/mySql.txt)
[postgresql unsupported sql](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test/blob/main/src/main/resources/result/postgreSql.txt)

**Comment by dongzl** [comment]
`create_conversion`
`alter_conversion `

**Comment by LeeGuoPing** [comment]
`create_type`

**Comment by LeeGuoPing** [comment]
- `create_text_search_dictionary`
- ` alter_text_search_dictionary`
- ` create_text_search_template`
- ` alter_text_search_template`

**Comment by tuichenchuxin** [comment]
Recently we extracted some unsupported sql from the official test set of mysql and postgresql to[ this file](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/unsupported/unsupported.xml)
If these unsupported sql can be resolved, then our parsing support (MySQL/PostgreSql) will reach 100%.

**Comment by strongduanmu** [comment]
> I have tested sql case from [mysql case ](https://github.com/mysql/mysql-server/tree/8.0/mysql-test/t)and [postgresql case](https://github.com/postgres/postgres/tree/master/src/test/regress/sql)
By using this [program](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test)
And then I get two unsupported sql files.
[mysql unsupported sql](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test/blob/main/src/main/resources/result/mySql.txt)
[postgresql unsupported sql](https://github.com/tuichenchuxin/extract-sql-for-shardingsphere-parser-test/blob/main/src/main/resources/result/postgreSql.txt) 

Hi @everly-gif, @Trydamere, are you willing to take part in this task? You can claim subtasks in `unsupported.xml` and complete the optimization of SQL Parser, which will be helpful for GSOC tasks.

**Comment by Trydamere** [comment]
Sure. I will read the issue and claim the subtasks.

**Comment by everly-gif** [comment]
Thanks @strongduanmu . I'll also look into this issue and start claiming subtasks

**Comment by Trydamere** [comment]
I will do ` drop_type`

**Comment by everly-gif** [comment]
I want to do `drop_rule`

**Comment by strongduanmu** [comment]
> I will do `drop_rule` [ Part of subtasks mentioned in this issue]
> 
> I also want to do `drop_statistics` `drop_trigger` [Mentioned in `unsupported.xml`] May I?

@everly-gif Of course.

**Comment by Trydamere** [comment]
- `drop_operator`
- `drop_access`
- `drop_server`

**Comment by everly-gif** [comment]
Since I'm done with my previous claimed tasks, here are some more I'm claiming to work on,
`drop_publication`
`drop_subscription`

**Comment by Trydamere** [comment]
- `ALTER OPERATOR`
- `ALTER OPERATOR CLASS`
- `ALTER OPERATOR FAMILY`
- `ALTER POLICY`
- `ALTER PUBLICATION`
- `ALTER ROUTINE`

**Comment by everly-gif** [comment]
> * `ALTER OPERATOR`
> * `ALTER OPERATOR CLASS`
> * `ALTER OPERATOR FAMILY`
> * `ALTER POLICY`
> * `ALTER PUBLICATION`
> * `ALTER ROUTINE`

@strongduanmu aren't these statements part of the GSOC project ? Hence, it should be worked on only during the coding period right?

**Comment by Trydamere** [comment]
Sorry. I forgot it. Withdrew.

**Comment by strongduanmu** [comment]
> 

@everly-gif @Trydamere Yes, these tasks need to be done during GSOC, so please skip these subtasks for now.

**Comment by FlyingZC** [comment]
I will do:
`create_by_mysql_source_test_case328`

`create_by_mysql_source_test_case329`

`create_by_mysql_source_test_case330`

`create_by_mysql_source_test_case331`

`create_by_mysql_source_test_case332`
