### ISSUE TITLE
readme doc bug

### ISSUE THREAD

**Issue by nikerxu** [apache/shardingsphere#14028]
the Contribution Guidelines page is not found
![a9bdb5f698a33b81aa29f80c91e5373](https://user-images.githubusercontent.com/19975759/145531702-ba857997-55df-49d0-bd21-f828e2756758.png)
![ab5d44dcdef4c8b87c8e207af0f198b](https://user-images.githubusercontent.com/19975759/145531707-8079c5a2-a028-42b6-8c6c-fc013bc0ac86.png)

**Comment by tuichenchuxin** [comment]
@nikerxu May be there is some Internet problem. I can visit this page.

**Comment by menghaoranss** [comment]
@nikerxu thanks for your feedback, fixed now.
