### ISSUE TITLE
ShardingSphere Parser supports Lineage? 

### ISSUE THREAD

**Issue by melin** [apache/shardingsphere#14021]
ShardingSphere Parser supports Lineage? Table to table, column to column

**Comment by terrymanu** [comment]
What is Lineage, could provide the introduce and GitHub repo?

**Comment by melin** [comment]
https://sqlflow.gudusoft.com/#/
https://github.com/maropu/spark-sql-flow-plugin

Liang Zhang ***@***.***> 于2021年12月9日周四 23:34写道：

**Comment by terrymanu** [comment]
Maybe need to add Lineage SQL dialect support

**Comment by melin** [comment]
There are a lot of data Catalog products, one of the important functions is data blood, looking forward to joining the program

**Comment by terrymanu** [comment]
No plan for support Lineage  now, anybody interesting this issue?
