### ISSUE TITLE
Add test cases for DataSourceDestroyer

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#14039]
The test cases are:

- [ ] DataSourceDestroyerFactory
- [ ] DefaultDataSourceDestroyer
- [ ] HikariDataSourceDestroyer

**Comment by takuya1981** [comment]
Can I try this??

**Comment by strongduanmu** [comment]
@takuya1981 Welcome, I will assign this issue to you.

**Comment by TeslaCN** [comment]
Finished in #14561.
