### ISSUE TITLE
4.1.0 version No entry doSharding method

### ISSUE THREAD

**Issue by qq494905015** [apache/shardingsphere#14036]
Bug Report
For English only, other languages will not accept.

Which version of ShardingSphere did you use?
4.1.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
entry doSharding method , Insert into the correct database source

Actual behavior
No entry doSharding method ,

Reason analyze (If you can)
Steps to reproduce the behavior, such as: 
already set rule configuration and hint algorithm.
sql to execute, and HintManager add correct dataSource rule. but no entry doSharding method.
i try to replace 4.0.0-RC2, it can entry doSharding method.    Is it a version problem.

![image](https://user-images.githubusercontent.com/14796790/145552425-51601f63-3e4f-4b11-8039-6efa9c64dd71.png)
![image](https://user-images.githubusercontent.com/14796790/145552439-42ec77e1-2c7d-44af-a1cf-a6aded3e2ae2.png)

**Comment by zjcnb** [comment]
@qq494905015 Hi, you can try it with 5.0.0 version.

**Comment by terrymanu** [comment]
What is your SQL, could you make sure your SQL contains sharding key?

**Comment by terrymanu** [comment]
Closed because of no response
