### ISSUE TITLE
`com.mchange.v1.db.sql.UnsupportedTypeException` needs adjustment

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#14032]
Replace `com.mchange.v1.db.sql.UnsupportedTypeException` with `java.lang.UnsupportedOperationException`

For example:
before modification:
![image](https://user-images.githubusercontent.com/52209337/145548169-8ad2ae2e-2a69-49ba-8be1-df0abc001ed3.png)

after modification:
![image](https://user-images.githubusercontent.com/52209337/145548363-21981b86-84de-4f6e-96f9-ab4673c0b9ee.png)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by RaigorJiang** [comment]
Welcome @himanshu007-creator .

**Comment by himanshu007-creator** [comment]
I am unable to clone repo in my computer, errors occur because of long file names

**Comment by lanchengx** [comment]
please  refer [FAQ](https://shardingsphere.apache.org/document/current/en/reference/faq/#other-in-windows-environmentwhen-cloning-shardingsphere-source-code-through-git-why-prompt-filename-too-long-and-how-to-solve-it)
