### ISSUE TITLE
How can I slove the database health check always fail   

### ISSUE THREAD

**Issue by Orange-apples** [apache/shardingsphere#14037]
![1639130534(1)](https://user-images.githubusercontent.com/63826095/145555850-20fe247b-51d2-4fd8-9139-84f2c0dbb80c.jpg)

**Comment by Orange-apples** [comment]
![1639130641(1)](https://user-images.githubusercontent.com/63826095/145556009-9a424d3e-dd9d-48bd-81c8-9779511fc51d.jpg)

**Comment by tuichenchuxin** [comment]
Can you offer me a demo to try it?

**Comment by terrymanu** [comment]
Because of no response anymore, I just close this issue.
