### ISSUE TITLE
I want to know how the high availability of the "cluster" mode in the "mode" is reflected?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#14030]
Version：
 sharding-proxy-master

I want to know how the high availability of the "cluster" mode in the "mode" is reflected?
In the official document, how does the high availability mentioned in the description of the role of the "cluster" setting of the "mode" reflect?

**Comment by CrackerSuperior** [comment]
It seems that there is no master and backup like MySQL？

**Comment by zjcnb** [comment]
ShardingSphere are only dicovery master and slave relation. The zookeeper are storage disabled node. It guarantees ShardingSphere can be used normally.
