### ISSUE TITLE
In the Proxy, `select current_user` does not query the configured user

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#14035]
The query result of `select current_user()` is users in `server.yaml`.

![image](https://user-images.githubusercontent.com/52209337/145551010-767a61cc-ae36-4fe5-a83a-0169a095a287.png)

But `select current_user` is routed to the database to query the user in the database;

We expect that the result of the select current_user query should also be the users configured by `server.yaml`

**Comment by yx9o** [comment]
I want to try this issue.

**Comment by RaigorJiang** [comment]
Thanks @yx9o
