### ISSUE TITLE
Why the DistSQL resource group statement assert at "org.apache.shardingsphere.test.sql.parser.parameterized.asserts.statement.dal.impl" package

### ISSUE THREAD

**Issue by dongzl** [apache/shardingsphere#14078]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

why the DistSQL resource group statement assert call at "org.apache.shardingsphere.test.sql.parser.parameterized.asserts.statement.dal.impl" package

e.g:
These class are DistSQL test case assert class:
- `MySQLCreateResourceGroupStatementAssert`
- `MySQLDropResourceGroupStatementAssert`
- `MySQLSetResourceGroupStatementAssert`
- `MySQLAlterResourceGroupStatementAssert`

But they are at the package of `org.apache.shardingsphere.test.sql.parser.parameterized.asserts.statement.dal.impl`,

I think they should be at the package of `org.apache.shardingsphere.test.sql.parser.parameterized.asserts.statement.distsql.rdl`.

why?

**Comment by RaigorJiang** [comment]
Hi @dongzl 
Resource Group is a feature of MySQL, not for DistSQL.
Ref to https://dev.mysql.com/doc/refman/8.0/en/resource-groups.html

**Comment by dongzl** [comment]
OK, I'm sorry, I have a misunderstand for g4 file, Thank you for your reply.
