### ISSUE TITLE
The case sensitivity of `single table` and `sharding table` are inconsistent

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14090]
### Which version of ShardingSphere did you use?
5.0.1-SNAPSHOT, master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
single table can be the same as sharding table, case insensitive

### Actual behavior
single table is case sensitive
sharding table is case insensitive

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Prepare tables
- `t_order` is a sharding table
- `t_single` is a single table:
```sql
mysql> show tables;
+-----------------------+------------+
| Tables_in_sharding_db | Table_type |
+-----------------------+------------+
| t_order               | BASE TABLE |
| t_single              | BASE TABLE |
+-----------------------+------------+
2 rows in set (0.01 sec)
```
2. Query with uppercase table name
```sql
mysql> select * from T_ORDER;
Empty set (0.01 sec)

mysql> select * from T_SINGLE;
ERROR 1997 (C1997): Runtime exception: [`T_SINGLE` single table does not exist.]
mysql>
```

**Comment by strongduanmu** [comment]
@RaigorJiang Thank you for your feedback, I will optimize this issue.

**Comment by strongduanmu** [comment]
After the PR merge, the latest results are as follows, which can support uppercase and lowercase queries.

```sql
mysql> create table t_single(id int, content varchar(100));
Query OK, 0 rows affected (0.16 sec)

mysql> SHOW TABLES;
+-----------------------+------------+
| Tables_in_sharding_db | Table_type |
+-----------------------+------------+
| t_single              | BASE TABLE |
+-----------------------+------------+
1 row in set (0.04 sec)

mysql> SELECT * FROM T_SINGLE;
Empty set (0.03 sec)
```

**Comment by RaigorJiang** [comment]
Thank you @strongduanmu
