### ISSUE TITLE
Verify scaling PostgreSQL updated record migration on incremental stage if update is ignored then improve it

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14091]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Updated record should be migrated to target database.

### Reason analyze (If you can)
In `PostgreSQLScalingSQLBuilder.buildConflictSQL`, `ON CONFLICT` it `DO NOTHING`
```
    private String buildConflictSQL(final DataRecord dataRecord) {
        StringBuilder result = new StringBuilder(" ON CONFLICT (");
        for (Column each : RecordUtil.extractPrimaryColumns(dataRecord)) {
            result.append(each.getName()).append(",");
        }
        result.setLength(result.length() - 1);
        result.append(") DO NOTHING");
        return result.toString();
    }
```
It seems cause issue, verification is needed for now.

`MySQLScalingSQLBuilder.buildDuplicateUpdateSQL` works.

**Comment by ReyYang** [comment]
Can i take this ? Thanks

**Comment by ReyYang** [comment]
Hello, after my actual inspection, I found that no problems were found in the incremental update of the current situation. I look forward to your reply.

**Comment by sandynz** [comment]
@ReyYang That's ok. Thanks
