### ISSUE TITLE
sharding-proxy doesn't support create table in transaction 

### ISSUE THREAD

**Issue by oneslideicywater** [apache/shardingsphere#14114]
using client tools such navicat connect to sharding-proxy. create a table in transaction failed:

### client log

```bash
 ERROR:  org.apache.shardingsphere.proxy.backend.exception.TableModifyInTransactionException
```
### sharding-proxy log

```bash
ooh, no log
```

so I wonder why sharding-proxy doesn't support create/drop table in transaction.

**Comment by menghaoranss** [comment]
@oneslideicywater could you please provide more information, the proxy version, your configurations, and steps to reproduce, this will help us solve your problem faster.

**Comment by terrymanu** [comment]
Closed because of no response
