### ISSUE TITLE
shardingsphere-jdbc-core has some useless dependency

### ISSUE THREAD

**Issue by lyennon** [apache/shardingsphere#14118]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

https://github.com/apache/shardingsphere/blob/6dd0369c80f3631146c8e8a0aada40013360487c/shardingsphere-jdbc/shardingsphere-jdbc-core/pom.xml#L35-L54

it has some sql parser dependency, but we may only need one , such as mysql parser . so it will be better that set optional = true
```
 <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-sql-parser-sql92</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
</dependency>
```

**Comment by TeslaCN** [comment]
@lyennon Could you exclude them for the moment?

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
