### ISSUE TITLE
When crossing database query, it throws SchemaNotExistedException.

### ISSUE THREAD

**Issue by Lacxner** [apache/shardingsphere#14116]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Querying in Version 4.1.1 and MySQL is work well.
### Actual behavior
![20211216161039](https://user-images.githubusercontent.com/35280133/146345368-0dffddae-8070-4bf2-b161-4ab88adc455b.png)
SQL：SELECT mobile FROM zhishu.user WHERE id = 1.
But "zhishu" is really exist.
### Reason analyze (If you can)
none
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
none
### Example codes for reproduce this issue (such as a github link).
none

**Comment by strongduanmu** [comment]
Hi @Lacxner, thank you for your feedback. ShardingSphere only supports querying of logic database. 
If you want to use a function similar to sql transparent transmission, you can use the sql hint developed by the master branch——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E8%B7%AF%E7%94%B1%E8%87%B3%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93.
