### ISSUE TITLE
query is not case sensitive when i use shardingColumn.

### ISSUE THREAD

**Issue by EarthXuan** [apache/shardingsphere#14128]
## Which version of ShardingSphere did you use?
5.0.1
## Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
## Expected behavior
query is not case sensitive
## Actual behavior
it is case sensitive when i use shardingColumn.
for example,i query error by guid , when my shardingColumn is Guid.
![企业微信截图_16397080512731](https://user-images.githubusercontent.com/19358477/146481957-a4eadf5a-95f2-44db-932b-89f068800df6.png)
![企业微信截图_16397080713025](https://user-images.githubusercontent.com/19358477/146481971-07792e5d-9a48-4794-9b79-0d34a70a8e4d.png)
![企业微信截图_16397080239537](https://user-images.githubusercontent.com/19358477/146481981-3ed7cdc9-da22-4763-b44f-4b597ee07bf1.png)
![企业微信截图_16397080128760](https://user-images.githubusercontent.com/19358477/146481993-6ad88206-3351-44b1-8ca9-9dba2bd5719c.png)

**Comment by tuichenchuxin** [comment]
When shardingSphere doSharding will use `groovy.lang.Closure`. Actually, the config ShardingColumn is not case sensitive. But the `closure` and the sharding value in your sql must be same.
For example 
if closure is `t_order_$->{Guid % 2} `
then your sql must be `Guid`

**Comment by EarthXuan** [comment]
Can you support it？
actually，developer maybe use guid/GUID/guid in sql.

**Comment by strongduanmu** [comment]
> 

@EarthXuan Thank you, we will optimize this issue.

**Comment by EarthXuan** [comment]
> > 
> 
> @EarthXuan Thank you, we will optimize this issue.

Thanks~
