### ISSUE TITLE
sharding proxy add heartbeat for different port (not 3307)

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#14136]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

**we use LVS for sharding proxy load ，but it need a different port  for heartbeat，have any suggest ？**

but i donot want to add another ServerBootstrap instance

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
use another port to start proxy, `sh %SHARDINGSPHERE_PROXY_HOME%/bin/start.sh ${proxy_port}`

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
