### ISSUE TITLE
last_insert_id not returned when using update

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#14144]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior
update id_gen set max_id = last_insert_id(max_id + 1) where type = 1;
the last_insert_id should be returned back to user

### Actual behavior
can't get last_insert_id like insert statement

### Reason analyze (If you can)
isReturnGeneratedKeys is only true on insert statement

**Comment by roodkcab** [comment]
`update id_gen set max_id = last_insert_id(max_id + 1) where type = 1` and then use `select last_insert_id()` is recommended in MySQL [manual](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_last-insert-id)

![image](https://user-images.githubusercontent.com/1700820/146628056-a3b2430f-97dd-4824-ad0f-1830145f95f0.png)

for shardingsphere, there's a problem that we use a connection pool, `select last_insert_id` may send to a connection other then the one used for `update` without transaction, which leading to wrong last_insert_id.

**Comment by roodkcab** [comment]
> The master branch always change, could you provide the commit id?

didn't get it, do u looking for 06cfe39459a7ebc9552a6e92cd214d347817ddb6 ?

**Comment by terrymanu** [comment]
Does the issue resolve?

**Comment by roodkcab** [comment]
not yet
