### ISSUE TITLE
JDBC  not Sharding Key query,the null field in the database will become 0

### ISSUE THREAD

**Issue by yanyuyaol** [apache/shardingsphere#14156]
Why is it designed like this？e.g. Long、Integer

**Comment by zjcnb** [comment]
Can you provider your configuration?

**Comment by yanyuyaol** [comment]
yml：  
shardingsphere:
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        hikari:
          minimumIdle: 2
          maximumPoolSize: 300
          idleTimeout: 120000
          connectionTimeout: 300000
          leakDetectionThreshold: 300000
    sharding:
      tables:
        con_video_inject:
          # 分表配置
          actual-data-nodes: ds0.con_video_inject_${0..2}
          table-strategy:
            inline:
              #分片列名称
              sharding-column: video_id
              #分片算法
              algorithm-expression: con_video_inject_${video_id % 3}
pom:
       <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-core-common</artifactId>
            <version>4.1.1</version>
        </dependency>
      <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <version>2.0.8.RELEASE</version>
        </dependency>

**Comment by yanyuyaol** [comment]
> Can you provider your configuration?

yml:
![image](https://user-images.githubusercontent.com/96333264/147327043-fca7d41c-ccbd-4ab3-b5fd-5a192e219da5.png)
pom：
![image](https://user-images.githubusercontent.com/96333264/147327186-bcc513bd-e977-43c0-9cc7-040e37001c39.png)

**Comment by terrymanu** [comment]
The version 4.x is out of service, please try version 5.x
