### ISSUE TITLE
Cannt connect to proxy with Data Grip

### ISSUE THREAD

**Issue by caohuanglin** [apache/shardingsphere#14169]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Connet to client
### Actual behavior
When I try to connect to proxy with Data Grip,it didn`t work.Data grip shown error message '[3D000][1046] No database selected.'
But Navicat is available;
![image](https://user-images.githubusercontent.com/22470050/146719282-e3bb2256-ea7f-4478-96e9-2f19f7b3709d.png)
![image](https://user-images.githubusercontent.com/22470050/146719386-a1d38d4e-7446-4fae-a362-c41d12baca5a.png)
![image](https://user-images.githubusercontent.com/22470050/146719360-f45a29a1-7e7e-43cf-a9d0-dc95eae45e5c.png)

**Comment by lanchengx** [comment]
Hi @caohuanglin, The support for DataGrip has yet to be improved. Suggested reference [FAQ](https://shardingsphere.apache.org/document/current/cn/reference/faq/#proxy-%E5%9C%A8%E4%BD%BF%E7%94%A8-shardingsphere-proxy%E6%97%B6%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%90%88%E9%80%82%E7%9A%84%E5%B7%A5%E5%85%B7%E8%BF%9E%E6%8E%A5%E5%88%B0-shardingsphere-proxy)

**Comment by caohuanglin** [comment]
> Hi @caohuanglin, The support for DataGrip has yet to be improved. Suggested reference [FAQ](https://shardingsphere.apache.org/document/current/cn/reference/faq/#proxy-%E5%9C%A8%E4%BD%BF%E7%94%A8-shardingsphere-proxy%E6%97%B6%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%90%88%E9%80%82%E7%9A%84%E5%B7%A5%E5%85%B7%E8%BF%9E%E6%8E%A5%E5%88%B0-shardingsphere-proxy)

I got it. Thanks.

**Comment by caohuanglin** [comment]
It works in data grip 2020.1 with following steps.
1. declare database
![image](https://user-images.githubusercontent.com/22470050/146730530-66281ec9-674e-4500-822f-539d13397908.png)
2. select the option
![image](https://user-images.githubusercontent.com/22470050/146730929-12773534-428c-4667-8c10-0e9cc7cd3d87.png)
3. change schemas
![image](https://user-images.githubusercontent.com/22470050/146731157-58775038-50a7-4022-a23a-c116fd376a26.png)
After these steps,I connect to proxy successfully
![image](https://user-images.githubusercontent.com/22470050/146731546-7ffe7b81-6703-498c-a7d4-f36f95cb0efd.png)
