### ISSUE TITLE
sharding+group by+mysql8.x+execute()  ClassCastException

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#14175]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
exeucte success
### Actual behavior
Exception in thread "main" java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.sql.Timestamp
### Reason analyze (If you can)
org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute() use inner class
![image](https://user-images.githubusercontent.com/16568907/146749895-b9128af4-c0e9-472c-a217-b079039c1459.png)
![image](https://user-images.githubusercontent.com/16568907/146749935-f5098ef6-c75f-4e8c-a836-b53a08963ff7.png)
but org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#executeQuery0 use PreparedStatementExecuteQueryCallback
![image](https://user-images.githubusercontent.com/16568907/146750062-7837d901-dedd-4b19-8f35-4eceb4bfaa77.png)
if need merge PreparedStatementExecuteQueryCallback handle type use db type
inner class use getObject, in mysql driver 8.x DateTime return LocalDateTime
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Preparation phase
* mysql connector driver 8.x
* sql has group by
* table sharding or db sharding
2. Execute phase
* call org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute()
* call org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSet#getTimestamp(java.lang.String)
### Example codes for reproduce this issue (such as a github link).
https://github.com/SirMin/shardingsphere5.x-demo

**Comment by strongduanmu** [comment]
@SirMin Thank you for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment]
Hi @SirMin I used the demo that you provided for testing, but there was no exception.

```
09:46:50.302 [main] INFO ShardingSphere-SQL - Logic SQL: select id, name, sharding_key, create_time from t_user group by name
09:46:50.302 [main] INFO ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
09:46:50.302 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 ::: select id, name, sharding_key, create_time from t_user0 group by name ORDER BY name ASC 
09:46:50.302 [main] INFO ShardingSphere-SQL - Actual SQL: ds0 ::: select id, name, sharding_key, create_time from t_user1 group by name ORDER BY name ASC 
09:46:50.302 [main] INFO ShardingSphere-SQL - Actual SQL: ds1 ::: select id, name, sharding_key, create_time from t_user0 group by name ORDER BY name ASC 
09:46:50.302 [main] INFO ShardingSphere-SQL - Actual SQL: ds1 ::: select id, name, sharding_key, create_time from t_user1 group by name ORDER BY name ASC 
2021-12-14 17:37:55.0
```

**Comment by SirMin** [comment]
I provided success and exception case
![image](https://user-images.githubusercontent.com/16568907/147065109-0515f7cd-0c1d-4b71-9e60-1fea80d48a4d.png)
You need to open the comment

**Comment by strongduanmu** [comment]
@SirMin Thank you, I will check it again.

**Comment by SirMin** [comment]
@strongduanmu 
this way only case by case.
jdbc type convert is very complex. I think you need to refer to the JDBC implementation, I'm found other problem,
I'm reproduced the problem. The value of the same attribute is different for the same record
**step:**
reexecute ddl and dml 
execute App.java
https://github.com/SirMin/shardingsphere5.x-demo

**Comment by strongduanmu** [comment]
> @strongduanmu this way only case by case. jdbc type convert is very complex. I think you need to refer to the JDBC implementation, I'm found other problem, I'm reproduced the problem. The value of the same attribute is different for the same record **step:** reexecute ddl and dml execute App.java https://github.com/SirMin/shardingsphere5.x-demo

@SirMin Thank you for your feedback, I will check it again.

**Comment by SirMin** [comment]
@strongduanmu 
This conversion can be problematic if the application and database are not in the same time zone.

**Comment by strongduanmu** [comment]
> This conversion can be problematic if the application and database are not in the same time zone.

How can I get time zone info from application?

**Comment by SirMin** [comment]
@strongduanmu 
The mysql JDBC Driver 8.x getTimestamp method converts the time using the url's serverTimeZone

**Comment by strongduanmu** [comment]
> serverTimeZone

@SirMin It can be seen that you have done a lot of research on JDBC implementation. Are you interested in submitting a PR to support different types of processing?

**Comment by SirMin** [comment]
@strongduanmu 
I'm looking at the implementation of mysql, and I'm worried that different implementation types are handled differently.
Let me try to implement that

**Comment by challengeof** [comment]
@strongduanmu 
I fixed this bug please help review. 
Test please refer to the case https://github.com/SirMin/shardingsphere5.x-demo provided by the issue authors. 
The time zone problem  please add serverTimezone=UTC to jdbcUrl to view the results.

**Comment by strongduanmu** [comment]
> @strongduanmu I fixed this bug please help review. Test please refer to the case https://github.com/SirMin/shardingsphere5.x-demo provided by the issue authors. The time zone problem please add serverTimezone=UTC to jdbcUrl to view the results.

@challengeof Thank you, I will review this pr later.

**Comment by SirMin** [comment]
@strongduanmu this pr only resolve the mysql's problem

![image](https://user-images.githubusercontent.com/16568907/147638617-013a0462-4e8f-4529-a375-b92e0913459a.png)
the mysql 8.x's code in com.mysql.cj.result.BooleanValueFactory
![image](https://user-images.githubusercontent.com/16568907/147638729-ee7ab878-b9f9-4bef-934c-1a69948d86d8.png)
postgresql's code in org.postgresql.jdbc.BooleanTypeUtil
![image](https://user-images.githubusercontent.com/16568907/147638828-de505a75-0c68-4fc9-923d-7cab09db1872.png)
I think the merge engin get value need refactor

**Comment by SirMin** [comment]
I don't think ShardingSphere should support too many type conversions, but you need to prompt the corresponding information.

**Comment by strongduanmu** [comment]
Hi @SirMin, can you submit a new issue to talk about this discussion?

**Comment by SirMin** [comment]
@strongduanmu ok
