### ISSUE TITLE
DatabaseMetaData metaData = con.getMetaData();  metaData.getPrimaryKeys(）is failed

### ISSUE THREAD

**Issue by qianxuwanyu** [apache/shardingsphere#14177]
shardingproxy  Table 'XXX.XXX' doesn't exist

**Comment by menghaoranss** [comment]
could you provide more information, such as version,  log, your configuration and steps to reproduce

**Comment by qianxuwanyu** [comment]
> could you provide more information, such as version, log, your configuration and steps to reproduce

![Uploading image.png…]()

**Comment by qianxuwanyu** [comment]
-   //注册驱动程序 mysql 5+ or 8+
      DriverManager.registerDriver(new com.mysql.jdbc.Driver());
      //获得连接
      String url = "jdbc:mysql://localhost:3307/fintax_tax_proxy?useSSL=false";
      Connection con = DriverManager.getConnection(url, "root", "root");
      //检索元数据对象
      DatabaseMetaData metaData = con.getMetaData();

      //it's ok
      ResultSet columnData = metaData.getColumns("fintax_tax_proxy", "fintax_tax_proxy", "config_area", null);

      //failed
      ResultSet primaryKeys = metaData.getPrimaryKeys("fintax_tax_proxy", "fintax_tax_proxy", "config_area");

Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'fintax_tax_proxy.config_area' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by qianxuwanyu** [comment]
import org.apache.ddlutils.model.Column;
import org.apache.ddlutils.model.Table;
import org.apache.ddlutils.platform.DatabaseMetaDataWrapper; //导入方法依赖的package包/类
import org.apache.ddlutils.platform.MetaDataColumnDescriptor;
import org.springframework.jdbc.support.JdbcUtils;

I don't know how to comment

**Comment by qianxuwanyu** [comment]
> could you provide more information, such as version, log, your configuration and steps to reproduce

You can see my reply code

**Comment by menghaoranss** [comment]
which  version of proxy did you use, could you provide the proxy yaml configuration?

**Comment by qianxuwanyu** [comment]
> could you provide more information, such as version, log, your configuration and steps to reproduce



> which version of proxy did you use, could you provide the proxy yaml configuration?
apache-shardingsphere-5.0.0-alpha-shardingsphere-proxy-bin  or 4.x all

**Comment by qianxuwanyu** [comment]
> which version of proxy did you use, could you provide the proxy yaml configuration?

apache-shardingsphere-5.0.0-alpha-shardingsphere-proxy-bin or 4.x  all cant not be success

**Comment by qianxuwanyu** [comment]
```
# 对外数据库名称
schemaName: fintax_tax_proxy
# 数据库链接公共参数
dataSourceCommon:
 username: root
 password: root123456
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 50
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000
# 数据库地址，这里配置了两个库
dataSources:
 ds_0:
   url: jdbc:mysql://localhost:5688/fintax_tax_0?serverTimezone=UTC&useSSL=false
 ds_1:
   url: jdbc:mysql://localhost:5688/fintax_tax_1?serverTimezone=UTC&useSSL=false
# 分片规则
rules:
- !SHARDING
 tables:
   # 虚拟表名称，最后登陆 proxy之后，sharding_db库下只有一张表 test（我这里只分了一个表，用于测试）
   data_qy:
     # ds_${0..1} 分库规则，库索引从0到1，一共两个，前缀为：ds_， test，分成3张表，索引从0到2，前缀为：test_
     actualDataNodes: ds_${0..1}.data_qy_${0..7}
     databaseStrategy:
       standard:
         shardingColumn: qy_id
         shardingAlgorithmName: database_inline
     tableStrategy:
       standard:
         # 分片键
         shardingColumn: qy_id
         shardingAlgorithmName: test_inline
     keyGenerateStrategy:
       column: id
       keyGeneratorName: snowflake  #主键生成策略 -- 雪花算法
   data_tax_report:
     # ds_${0..1} 分库规则，库索引从0到1，一共两个，前缀为：ds_， test，分成3张表，索引从0到2，前缀为：test_
     actualDataNodes: ds_${0..1}.data_tax_report_${0..7}
     databaseStrategy:
       standard:
         shardingColumn: qy_id
         shardingAlgorithmName: user_database_inline
     tableStrategy:
       standard:
         # 分片键
         shardingColumn: qy_id
         shardingAlgorithmName: user_inline
     keyGenerateStrategy:
       column: id
       keyGeneratorName: snowflake  #主键生成策略 -- 雪花算法    
# 默认数据库分片规则

**Comment by sandynz** [comment]
Hi @qianxuwanyu , could you try `metaData.getPrimaryKeys(connection.getCatalog(), connection.getSchema(), tableName)`?

It should work, I've used it on similar scenario. You could refer to [PipelineTableMetaDataLoader.java]( https://github.com/apache/shardingsphere/blob/master/shardingsphere-kernel/shardingsphere-data-pipeline/shardingsphere-data-pipeline-core/src/main/java/org/apache/shardingsphere/data/pipeline/core/metadata/loader/PipelineTableMetaDataLoader.java )

**Comment by terrymanu** [comment]
Closed because of no response
