### ISSUE TITLE
un support sql 

### ISSUE THREAD

**Issue by HardyDou** [apache/shardingsphere#14173]
### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
All 
### Actual behavior
![企业微信截图_16399904333675](https://user-images.githubusercontent.com/18573210/146740827-bb5aed64-334e-45b9-8db2-719a67cf9709.png)
### Reason analyze (If you can)
none

**Comment by terrymanu** [comment]
Closed because of no response
