### ISSUE TITLE
sharding-proxy when execute connection.setReadOnly(true)  all datasource in proxy will execute "set session transaction read only"

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#14187]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

**sharding-proxy when execute connection.setReadOnly(true) ,all datasource in proxy will execute "set session transaction read only"**

when one connection （for datasource a）execute connection.setReadOnly(true)，other datasource b c d will change to read only，have any idea to change code ???

**now ,i ignore this sql "set session transaction read only"
but other set command will all execute ，set transaction_isolation will change all datasource ,so How to solve it fundamentally ,now i change code like this ：** 

**BroadcastDatabaseBackendHandler**
![image](https://user-images.githubusercontent.com/30221773/146939418-7a96c6e9-54f5-48a4-833b-a1ec6fbbc779.png)

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
 5.0.0-beat
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
only one datasource change to read only
### Actual behavior
all datasource change to read only
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/30221773/146874736-ba25e997-8c9d-4343-99ec-376784a6ee9f.png)

![image](https://user-images.githubusercontent.com/30221773/146874115-b0058ff4-706c-4cf6-8b38-03f45cfe5155.png)

this ShardingDatabaseBroadcastRoutingEngine route all datasources
### Example codes for reproduce this issue (such as a github link).
```java

// I have more than one logic schema ,eg：schema_a(a_db_0,a_db_1)，schema_b(b_db_0,b_db_1）


    /**
     * 单表：仅设置当前逻辑库只读 ( use shema_a)
     */
    @Test
    public void singleTableForReadOnlyTest() {
        String sql = "INSERT IGNORE INTO user_role (user_id, role_id, remark) VALUES (20092, 20090, null);";
        try (Connection connection = getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);) {
            connection.setReadOnly(true);
            preparedStatement.execute();
            ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
            while (generatedKeys.next()) {
                System.out.println(generatedKeys.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally {

            sql = "delete from user_role where user_id=20092 and role_id=20090;";
            try (Connection connection = getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql);) {
                preparedStatement.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }
```

**other example **
```java
    /**
     * 单表：事务隔离级别
     */
    @Test
    public void singleTableForIsolationTest() {
        String sql = "INSERT IGNORE INTO user_role (user_id, role_id, remark) VALUES (20092, 20090, null);";
        try (Connection connection = getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);) {
            connection.setTransactionIsolation(2);
            preparedStatement.execute();
            ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
            while (generatedKeys.next()) {
                System.out.println(generatedKeys.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally {

            sql = "delete from user_role where user_id=20092 and role_id=20090;";
            try (Connection connection = getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql);) {
                preparedStatement.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```
![image](https://user-images.githubusercontent.com/30221773/146914869-939e0937-a298-484b-9ffd-e37ccde06a4b.png)

**Comment by xue2lang** [comment]
@menghaoranss have any suggest

**Comment by jingshanglu** [comment]
@xue2lang Is it unreasonable that all datasources are set to `session transaction read only`? What is your use case?

**Comment by xue2lang** [comment]
@jingshanglu   your can see  test code

**Comment by xue2lang** [comment]
my question is，why one dal command will effect all schema，i think one tcp session will only effect its schema

**Comment by jingshanglu** [comment]
@xue2lang Maybe it is a bug.

**Comment by jingshanglu** [comment]
@xue2lang Are you interested in fixing this problem？we can fully discuss it first, and then fix it

**Comment by userkdg** [comment]
What's wrong with this problem？
i met it

**Comment by chengh1** [comment]
The sql like `session transaction read only` will execute on all schema, When routing later, it will also route to all datasourcec under the current schema.

**Comment by jingshanglu** [comment]
@xue2lang Very in-depth analysis. For this situation, it may be necessary to design database metadata management to be compatible with MySQL behavior. We should sort out the states that need to be managed, and then manage them through zk.
