### ISSUE TITLE
implement COM_STATISTICS & COM_SLEEP 

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#14192]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Proxy

### Expected behavior

COM_STATISTICS COM_SLEEP not implement

### Actual behavior

implement both of them just like COM_QUIT

### Reason analyze (If you can)

not implement

**Comment by terrymanu** [comment]
This issue is pretty long time, and the pull request has already closed, I just close this issue.
