### ISSUE TITLE
The antlr4 grammar file does not recognize the variables in the mysql create function statement

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#14211]
## Bug Report
mysql syntax file may be wrong. I found that it may be caused by the declareStatement grammar rules(line 682) in the DDLStatement.g4, The "variable" grammar rules  it refers to must start with '@' .

example:  
```sql
create
        function myfunTest(idx int)
        returns int
        comment 'test'
    begin
        declare res int;
        declare num1, num2 int  default 27;
        declare data1, data2 int;
        set num2 = 23, res = num1 + num2;
        set data1 = 1, data2 = 1;
        select id, id into  data1, data2 from sss where id = idx;
        set res :=  res * (data1 + data2);
        return (res);
    end;
```
![img](https://tttz.gitee.io/pic/ast/mysqlfun.png)

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
@strongduanmu Ok, I'll check it.

**Comment by jiangtao69039** [comment]
the same problem with "select into" statement ;
example:  

```sql
SELECT name, url
INTO WebsitesBackup2016
FROM Websites;

```

**Comment by jiangtao69039** [comment]
hi, Does this issue have any results? or it's not a bug?

**Comment by tuichenchuxin** [comment]
@jiangtao69039 It's a bug, I'll solve this issue, recently.
