### ISSUE TITLE
Cannot use mod() on this number type: java.math.BigDecimal, it's should be fixed.

### ISSUE THREAD

**Issue by GreekPanda** [apache/shardingsphere#14242]
I've reviewed the issue #13857 , but I don't know your guys what to fix it or not, it's a big issue to my history code if not supported with BigInteger, I can't change all code from BigInteger to Long, it's impossible. 

MySQL: mysql  Ver 8.0.25 for Linux on x86_64 (MySQL Community Server - GPL)
JDBC: mysql-connector-java 8.0.11
HikariCP: 2.7.8

**Comment by RaigorJiang** [comment]
Hi @GreekPanda 
BigInteger cannot use the mod function, and you use a modular sharding algorithm, which is the cause of the exception.
ShardingSphere provides a general solution, but also provides the ability to expand. If you have a special scenario, you can choose to implement your own sharding algorithm and use the BigInteger type in the algorithm.

Here is an example of a custom algorithm:
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
