### ISSUE TITLE
Fix test case MySQLDataSourcePreparerTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#14246]
Some changes in #14243 and broken the test case MySQLDataSourcePreparerTest, please mock and fix it.

**Comment by shankeerthan-kasilingam** [comment]
I would like to work on this issue.

**Comment by strongduanmu** [comment]
@shankeerthan-kasilingam Welcome, I will assign this issue to you.

**Comment by shankeerthan-kasilingam** [comment]
@strongduanmu Could you please check the [PR](https://github.com/apache/shardingsphere/pull/15203) and let me know if any improvements or changes to be done?
