### ISSUE TITLE
There is an error in the official document

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#14257]
## There is an error in the official document
- https://shardingsphere.apache.org/document/current/cn/quick-start/shardingsphere-proxy-quick-start/
   - https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/configuration/

![image](https://user-images.githubusercontent.com/86462784/147192873-8c3063ef-77b6-4e9f-b272-87409dd37c66.png)
![image](https://user-images.githubusercontent.com/86462784/147192917-1792043f-d70f-4e93-98d6-9919c3dc8e1f.png)

**Comment by RaigorJiang** [comment]
Hi @wsm12138 
Thanks for your feedback, do you want to fix it?

**Comment by wsm12138** [comment]
@RaigorJiang NO,thanks ⁽⁽ଘ( ˙꒳˙ )ଓ⁾⁾

**Comment by RaigorJiang** [comment]
> @RaigorJiang NO,thanks ⁽⁽ଘ( ˙꒳˙ )ଓ⁾⁾

Haha, alright, thank you.
