### ISSUE TITLE
Does it support consistent hash fragmentation strategy? To solve the problem of sharding scaling? I am reluctant to use scaling to re-migrate data because it is too troublesome

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#14251]
If it supports consistent hash fragmentation, where is there an example to configure it?

**Comment by wl4g** [comment]
If it supports consistent hash fragmentation, where is there an example to configure it?

**Comment by sandynz** [comment]
Hi @wl4g , from [Sharding Algorithm](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/ ), there's no consistent hash fragmentation strategy for now.

In fact, there're friendly strategies for scaling, e.g. `BOUNDARY_RANGE`. But scale on original database cluster is not implemented for now, it's planned and might be done at next year.

**Comment by sandynz** [comment]
Just an idea, `BOUNDARY_RANGE` plus distributed random id generation, it's similar as consistent hash and could be no any data need to be migrated.

**Comment by terrymanu** [comment]
I just close this issue because no response for long time.
