### ISSUE TITLE
xa recover return nothing when using server side prepare

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#14263]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior
`xa recover` should return xid for transaction not commited.

### Actual behavior
nothing returned

**Comment by zhfeng** [comment]
what is you mean ```server side prepare``` ?

**Comment by roodkcab** [comment]
> what is you mean `server side prepare` ?

it means prepare sql in mysql server. some mysql clients like PDO can emulate sql prepare themselves.

**Comment by zhfeng** [comment]
So you use https://www.php.net/manual/en/pdo.prepare.php ? and this method is called after ```xa.begin()``` ?

**Comment by roodkcab** [comment]
> So you use https://www.php.net/manual/en/pdo.prepare.php ? 
yes

> and this method is called after `xa.begin()` ?
the call stack is like below
```
xa start $xid;
xa end $xid;
disconnect with mysql
xa recover;
//get nothing here.
```

**Comment by zhfeng** [comment]
well, I think ```PDO::prepare``` does not relate to any xa transaction context. And  it will not change the xa state in the server. So ```xa recover``` returns nothing is expected. Maybe I misunderstand the php prepare ? But I cannot find some hints in php manual which implictly makes the xa transaction into prepare state after this invoking.
