### ISSUE TITLE
shardingsphere 5.0.0 seata 1.4.2 deal transaction fail

### ISSUE THREAD

**Issue by linjikun** [apache/shardingsphere#14261]
when I upgrate  shardingsphere 5.0.0-alpha to 5.0.0
seata XID is null

![微信图片_20211223154317](https://user-images.githubusercontent.com/33478843/147206020-09990d18-84c4-4316-ab9b-b6eef611ae64.png)

**Comment by zjcnb** [comment]
@linjikun Hi, I think this problem are fixed at master branch, you can try.

**Comment by linjikun** [comment]
> 

@zjcnb ,thank you for your answer,I will try it later

**Comment by zjcnb** [comment]
> > 
> 
> @zjcnb ,thank you for your answer,I will try it later

Hi, is this problem solved?

**Comment by linjikun** [comment]
@zjcnb I have change to 5.0.0-alpha,this problem is solved
