### ISSUE TITLE
No use database, execute select now() no response.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#14285]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

![image](https://user-images.githubusercontent.com/33742097/147311229-73ec16e5-050c-4619-b395-41a0051afb3a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/33742097/147311254-aed42acc-6aef-4bb5-9a29-da220c40ee4b.png)

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by zjcnb** [comment]
@LeeGuoPing Hi, I think proxy must be use database. So, i will close it.
