### ISSUE TITLE
app-proxy occasionally takes a long time to obtain a connection

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#14299]
ShardingSphere-Proxy 5.0.0-Alpha

HikariCP 4.0.4-SNAPSHOT

### Expected behavior
Application -> Proxy
HikariCP HikariDataSource.getConnection() Less than 1s
metrics hikaricp_connections_acquire_seconds_max < 1s

Proxy-DB 
metrics hikaricp_connections_acquire_seconds_max < 1s

### Actual behavior
Application -> Proxy
many times hikaricp_connections_acquire_seconds_max 3s around
![image](https://user-images.githubusercontent.com/20919316/147340452-856d1474-8ed0-4f7c-8fbe-c9991d1ea909.png)

Proxy-DB hikaricp_connections_acquire_seconds_max < 1s

### Supplement

Application HikariCP config
```
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.leak-detection-threshold=30000
spring.datasource.hikari.minimum-idle=32
spring.datasource.hikari.maximum-pool-size=64
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 'x'
```

Application -> Proxy  Network  is normal

**Comment by roodkcab** [comment]
@git-chenhao hi the problem may occurred after restart shardingsphere, it depends on how to use it. which mode do you use, cluster/standalone/memory ?

**Comment by git-chenhao** [comment]
> @git-chenhao hi the problem may occurred after restart shardingsphere, it depends on how to use it. which mode do you use, cluster/standalone/memory ?

@roodkcab cluster mode,  During the occurrence, shardingsphere did not restart

**Comment by roodkcab** [comment]
check the number of active connections, if all thread is occupied doing transaction, new coming connection will be hung until transaction finished.

**Comment by roodkcab** [comment]
and can you upgrade shardingsphere-proxy to the latest version ? if you use information_schema, a bug of not release connection is fixed after alpha

**Comment by git-chenhao** [comment]
Monitor the number of active connections seen above. The water level is very low, and there are a large number of idle connections.

**Comment by git-chenhao** [comment]
Do you think it is convenient to communicate with WeChat?
my wechat 15618790097

**Comment by git-chenhao** [comment]
@roodkcab

**Comment by TeslaCN** [comment]
This issue is inactive for a while. I'm closing this for now.
