### ISSUE TITLE
Oracle pagination and sorting doesn' t work properly

### ISSUE THREAD

**Issue by HarrySheep** [apache/shardingsphere#14334]
## Question

What happens?
I'm using sharding-jdbc springboot, trying to perform pagination (with PageHelper) with 2 sharding tables (in Oracle).
The result sets seem like containing all the result I need, but they have not been sorted.
So I wonder if i configure it wrong or what?
I have searched for it for a long time, but I never found a proper solution.

Here's some configuration and the test code:
**Maven Dependency:**
![image](https://user-images.githubusercontent.com/26380795/147433185-aadbb926-5486-4476-b644-42a1f22cf7b0.png)

**Configuration:**
![image](https://user-images.githubusercontent.com/26380795/147434065-e98d6e6f-cc0b-45bc-992b-e2a6d099a1e8.png)

**Sharding Algorithm:**
Plz ignore it for now. It seems to have nothing to do with this issue.

**Test Code:**
![image](https://user-images.githubusercontent.com/26380795/147434346-7913331f-1b38-4d45-9754-8421e48d1dcf.png)

![image](https://user-images.githubusercontent.com/26380795/147432959-85cb18e5-6731-417c-a92d-94144587c05a.png)

**Mybatis Mapper:**
![image](https://user-images.githubusercontent.com/26380795/147432983-db9155de-123f-4727-ab08-2bf0861859d5.png)

**Here's the result sets:**
![image](https://user-images.githubusercontent.com/26380795/147434695-1b9ecf6e-fb36-497c-a67b-7f045a3b03d9.png)

**The SQL Log:**
![image](https://user-images.githubusercontent.com/26380795/147434138-3356b5d9-2f4f-476b-b696-b778917e2fb7.png)

What it appears?
And above all, we can see that it scanned through 2 tables, nfs_push_sent_message and nfs_push_sent_message_2021, and the sql did have the "order by STATUS_TIME desc" phase clearly. But still, the "order column" in **result sets were not ordered**.

If you need any further information, please contact me at any time. Thank for for taking a look at the question.

**Comment by tuichenchuxin** [comment]
From the actual sql, it seems have order clause. Can you try to offer a demo?

**Comment by xszhe** [comment]
我也出现同样的问题，是因为
D:/maven_bd/org/apache/shardingsphere/shardingsphere-jdbc-core/5.0.0/shardingsphere-jdbc-core-5.0.0.jar!/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.class:121


this.sqlStatement = sqlParserEngine.parse(sql, true);
这个语句对无法解析分页组件组合的SQL，对分页内子查询的order by 无法正常解析，导致无法识别
![Snipaste_2022-01-28_09-29-51](https://user-images.githubusercontent.com/49973087/151471374-3dfc8763-e82c-46b7-901d-295c7f8c66d5.jpg)
我通过对分页组件 com.github.pagehelper:pagehelper:5.3.0 的源码修改覆盖，将order by 的子查询提取到外部，让 sharding 能正常解析。

com.github.pagehelper.dialect.helper.OracleDialect

`

    /**
     * 
     */
    public String getPageSql(String sql, Page page, CacheKey pageKey) {
        StringBuilder sqlBuilder = new StringBuilder(sql.length() + 120);
        sqlBuilder.append("SELECT * FROM ( ");
        sqlBuilder.append(" SELECT TMP_PAGE.*, ROWNUM PAGEHELPER_ROW_ID FROM ( \n");
        sqlBuilder.append(sql);
        sqlBuilder.append("\n ) TMP_PAGE) TMP_PAGE_2");
        sqlBuilder.append(" WHERE TMP_PAGE_2.PAGEHELPER_ROW_ID <= ? AND TMP_PAGE_2.PAGEHELPER_ROW_ID > ?");
        addOrderBy(sql, sqlBuilder);
        return sqlBuilder.toString();
    }

    /**
     * add order by 
     *
     * @param sql
     * @param sqlBuilder
     */
    private void addOrderBy(String sql, StringBuilder sqlBuilder) {
        CCJSqlParserManager parserManager = new CCJSqlParserManager();
        try {
            Statement statement = parserManager.parse(new StringReader(sql));
            if (statement instanceof Select) {
                Select select = (Select) statement;
                PlainSelect plain = (PlainSelect) select.getSelectBody();
                List<OrderByElement> orderByElements = plain.getOrderByElements();
                int index = 0;
                if (null != orderByElements && !orderByElements.isEmpty()) {
                    for (OrderByElement orderByElement : orderByElements) {
                        if (null != orderByElement) {
                            if (0 == index) {
                                sqlBuilder.append(" ORDER BY ");
                            } else {
                                sqlBuilder.append(" ,");
                            }
                            sqlBuilder.append(orderByElement);
                            index++;
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
`

![image](https://user-images.githubusercontent.com/49973087/151471309-82f961aa-c001-4a2c-a3ab-c12a8292eb33.png)

执行的sql是
SELECT * FROM (  SELECT TMP_PAGE.*, ROWNUM PAGEHELPER_ROW_ID FROM ( 
SELECT * FROM SYS_LOG_12  WHERE (       (  log_type = ? ) ) order by log_date Desc
 ) TMP_PAGE) TMP_PAGE_2 WHERE TMP_PAGE_2.PAGEHELPER_ROW_ID <= ? AND TMP_PAGE_2.PAGEHELPER_ROW_ID > ? ORDER BY log_date DESC

测试可分页及正常排序。

**Comment by xiajifei** [comment]
I have a same question;sql can't exe in Sharding;
"SELECT * FROM ( SELECT TMP_PAGE.*, ROWNUM PAGEHELPER_ROW_ID FROM ( select sys_user.id, sys_user.user_code, sys_user.user_name, sys_user.password, sys_user.phone_number,sys_user.email, sys_user.avatar, sys_user.is_manager, sys_user.open_id, sys_user.app_code, sys_user.remark, sys_user.create_time, sys_user.modify_time, sys_user.create_user_id,sys_user.modify_user_id, sys_user.is_delete,sys_user.card_no,sys_user.contacts , sys_user_app_rel.app_id as userAppRelAppId, sys_user_app_rel.user_type as userAppRelUserType, IFNULL(?,null) as appId from sys_user left join sys_user_app_rel on sys_user.id=sys_user_app_rel.user_id left join sys_user_corp_rel on sys_user.id=sys_user_corp_rel.user_id where 1=1 and sys_user.is_manager = 1 and sys_user.is_delete=0 and sys_user_app_rel.is_delete=0 /*and upper(sys_user.user_code) != 'ADMIN'*/ and sys_user_app_rel.app_id=? group by sys_user.user_code order by sys_user.create_time desc ) TMP_PAGE) WHERE PAGEHELPER_ROW_ID <= ? AND PAGEHELPER_ROW_ID > ?"

**Comment by terrymanu** [comment]
No plan to improve with oracle, I just set it as good amateur issue, does anyone want to fix it?

**Comment by xinglijun1973** [comment]
Can you post your Sharding Algorithm and PushSentMessage::getStatusTime? I'll  try to repeat it.

**Comment by xinglijun1973** [comment]
> No plan to improve with oracle, I just set it as good amateur issue, does anyone want to fix it?
@terrymanu I'm almost done with it, please assign it to me.
