### ISSUE TITLE
When there is a multiplication operation in the sql query field, the field after the operation will not be parsed

### ISSUE THREAD

**Issue by zhougaole** [apache/shardingsphere#14342]
For example：
SELECT 
    A.VOUCHERLISTID, 
    A.VOUCHERID, 
    A.MATERIALCODE, 
    A.UNITCODE, 
    A.UNITNAME, 
    A.MATERIALNAME, 
    A.EXTTXT, 
    A.NUM, 
    A.PRICE,
    A.PROVIDERID, 
    A.PROVIDERNAME, 
    A.REMARK, 
    A.BIZID, 
    A.BIZLISTID, 
    (A.PRICE*A.NUM) MONEY , 
    A.STOCKID,
    a.seriescodeid, 
    a.sheetlistid, 
    a.degree, 
    a.mssserialno, 
    a.brandname, 
    a.model, 
    a.terminal, 
    a.terminallist,
    A.SCMRETURNSTATUS, 
    a.prdha, 
    a.prdhaname, 
    a.storehouseid, 
    a.storehousename, 
    a.houseareaname, 
    a.houseareaid,
    a.itemid, 
    a.supplierid, 
    a.suppliername, 
    a.itemname,
    a.storelocalid, 
    a.storelocalname, 
    a.stocklistid,
    a.bktype, 
    a.zddlsh, 
    a.listRelationid, 
    a.outwarehouseid, 
    a.ACCOUNTTYPE, 
    a.OWNERTYPE
FROM 
    test A

Only the (A.PRICE*A.NUM) MONEY field can be parsed, and the following fields will not be parsed

**Comment by tuichenchuxin** [comment]
which version have you used?

**Comment by zhougaole** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        shardingsphere-jdbc  5.0.0
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 1/5/2022 ***@***.***> wrote： 



which version have you used?

**Comment by zhougaole** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            SQL can be parsed, but the value of the following field is found to be null, in fact there is a value
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 1/5/2022 ***@***.***> wrote： 



what is the mean can't be parsed? I use this sql , It can be parsed.

**Comment by terrymanu** [comment]
@zhougaole Hi, your comment include lots of css info, can you remove it?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
