### ISSUE TITLE
About information_schema schema

### ISSUE THREAD

**Issue by hhxsy** [apache/shardingsphere#14347]
## Question

I can't execute sql 'select * from information_schema.processlist' by using compute node at shardingsphere-proxy.
How can I search processlist information?

**Comment by RaigorJiang** [comment]
information_schema cannot describe the state of a distributed database. 
ShardingSphere provides the following syntax:
- show processlist;

**Comment by hhxsy** [comment]
So,How can I notice the dead lock happen and locate this lock without information_schema?

**Comment by hhxsy** [comment]
> information_schema cannot describe the state of a distributed database. ShardingSphere provides the following syntax:
> 
> * show processlist;

So,How can I notice the dead lock happen and locate this lock without information_schema?

**Comment by RaigorJiang** [comment]
It cannot be done at present, and the support for information_schema will be improved in the future.

**Comment by hhxsy** [comment]
I used the command 'show processlist' then got a empty result.
Then I followed the walking and find that zookeeper request parameter plus the string  'execution_nodes' , zookeeper threw an exception that the node could not be connected.
Is this currect？
![1640682487(1)](https://user-images.githubusercontent.com/18184721/147550257-c1d48b21-5148-42fe-9da7-d43fa1cbc83a.png)

**Comment by RaigorJiang** [comment]
Hi @menghaoranss , 
Please help us.

**Comment by terrymanu** [comment]
Fixed
