### ISSUE TITLE
[DistSQL] Optimize query results of `SHOW AUTHORITY RULE`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14346]
After PR #14260, we can query authority rule through DistSQL:

![image](https://user-images.githubusercontent.com/5668787/147455967-661bd375-850c-496e-b809-fbdc0775f9aa.png)

But now anyone can see the passwords of other users, which needs to be improved.

I suggest that when users execute `SHOW AUTHORITY RULE`, only query the user name, not the secret.

**Comment by RaigorJiang** [comment]
Hi @CrackerSuperior Could you help finish it?

**Comment by CrackerSuperior** [comment]
> Hi @CrackerSuperior Could you help finish it?

ok, no problem
