### ISSUE TITLE
[DistSQL] Optimize the syntax of `CREATE SHARDING TABLE RULE`.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14340]
Hi community,

According to the existing [RDL syntax](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/), if the user wants to use the inline expression to specify shariding table nodes, before `CREATE SHARDING TABLE RULE,` he must first execute the `CREATE SHARDING ALGORITHM` to create the necessary algorithm.
For example:
```sql
CREATE SHARDING ALGORITHM 
database_inline (TYPE(NAME=inline,PROPERTIES("algorithm-expression"="resource_${user_id % 2}"))),
table_inline (TYPE(NAME=inline,PROPERTIES("algorithm-expression"="t_order_item_${order_id % 2}")));

CREATE SHARDING TABLE RULE t_order_item (
DATANODES("resource_${0..1}.t_order_item_${0..1}"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=user_id,SHARDING_ALGORITHM=database_inline),
TABLE_STRATEGY(TYPE=standard,SHARDING_COLUMN=order_id,SHARDING_ALGORITHM=table_inline)
);
```

If users can directly declare inline expressions in the `CREATE SHARDING TABLE RULE` statement, it will simplify the process of creating rules.
For example:
```sql
CREATE SHARDING TABLE RULE t_order_item (
DATANODES("resource_${0..1}.t_order_item_${0..1}"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=user_id,SHARDING_ALGORITHM(TYPE(NAME=inline,PROPERTIES("algorithm-expression"="resource_${user_id% 2}")))),
TABLE_STRATEGY(TYPE=standard,SHARDING_COLUMN=order_id,SHARDING_ALGORITHM(TYPE(NAME=inline,PROPERTIES("algorithm-expression"="t_order_item_${order_id % 2}"))))
);

```

So, I suggest optimizing the syntax of `CREATE SHARDING TABLE RULE` and `ALTER SHARDING TABLE RULE`, allowing users to use any of the above ways to define rules.

**Comment by CrackerSuperior** [comment]
If so, where should the name of the algorithm be specified?

**Comment by tristaZero** [comment]
@CrackerSuperior There is not necessary to have the algorithm name in the second case, right?

**Comment by CrackerSuperior** [comment]
> @CrackerSuperior There is not necessary to have the algorithm name in the second case, right?

In other words, is it a disposable item?

**Comment by RaigorJiang** [comment]
> > @CrackerSuperior There is not necessary to have the algorithm name in the second case, right?
> 
> In other words, is it a disposable item?

No, it's actually similar to the syntax of autoTable. An algorithm is automatically created, and the name is automatically generated.

**Comment by CrackerSuperior** [comment]
> > > @CrackerSuperior There is not necessary to have the algorithm name in the second case, right?
> > 
> > 
> > In other words, is it a disposable item?
> 
> No, it's actually similar to the syntax of autoTable. An algorithm is automatically created, and the name is automatically generated.

I want to try this, but it may take a long time for me to do it. Is this grammar urgent?

**Comment by RaigorJiang** [comment]
> I want to try this, but it may take a long time for me to do it. Is this grammar urgent?

It's a bit urgent, can I give you another issue?

**Comment by CrackerSuperior** [comment]
> > I want to try this, but it may take a long time for me to do it. Is this grammar urgent?
> 
> It's a bit urgent, can I give you another issue?

Haha, it's okay

**Comment by CrackerSuperior** [comment]
> > I want to try this, but it may take a long time for me to do it. Is this grammar urgent?
> 
> It's a bit urgent, can I give you another issue?

Mainly because there is not much free time suitable for development every day. Helplessly.  
:)
