### ISSUE TITLE
on sql parser, how to parser multi sql string 

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14368]
Q:
![image](https://user-images.githubusercontent.com/21057449/147518507-02fb6b13-09d8-4dc3-86a8-801fc03bdd30.png)

in shardingsphere-proxy, mysql packet#readStringEOF get the multi sql statement, then ``` org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory#newInstance ``` only parser the first sql statement, will ingore other sql .  

sql:
```
SHOW VARIABLES LIKE 'lower_case_%'; SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster' 
```

use client:
![image](https://user-images.githubusercontent.com/21057449/147518986-30c81f46-42a9-4ffe-b38b-f35a5a129892.png)

issues:
-  why mysql ``` public MySQLComQueryPacket(final MySQLPacketPayload payload) {
        super(MySQLCommandPacketType.COM_QUERY);
        sql = payload.readStringEOF();
    } ```  return multi sql statement ,  
-  how to fix parser multi sql.

**Comment by strongduanmu** [comment]
Hi @userkdg, thank you for your feedback. Now shardingsphere doesn't support multi sql string parse.
