### ISSUE TITLE
About Data Backup Support

### ISSUE THREAD

**Issue by hhxsy** [apache/shardingsphere#14370]
## Question

I notice that it was been failed When I try to backup my data by using mysqlbinlog or mydumper tools. 
And It will be cast a Error :

`Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.FILES.EXTRA' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by' when trying to dump tablespaces`

So, Is there any tools I can use to backup my data?

**Comment by terrymanu** [comment]
No plan for database operation scope
