### ISSUE TITLE
Failed to connect Shardingshpere-proxy 5.0.1 but successful to connect  Shardingshpere-proxy 5.0.0 with Navicat Premius 15.0.9

### ISSUE THREAD

**Issue by GreekPanda** [apache/shardingsphere#14387]
### Which version of ShardingSphere did you use?
5.0.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Can connect to ShardingSphere-Proxy with Navicat premium 15.0.9

### Actual behavior
Failt to connect 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. Use Navicat premium 15.0.9 to connect ShardingSphere-Proxy 5.0.0 is ok
2. Faild to Navicat premium 15.0.9 to connect ShardingSphere-Proxy 5.0.1 show error : 1064-You have an error in your SQL syntax; check the manual that corresponds to you MySQL server version for the right syntax to use near 'SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS suppport_ndb FROM information_' at line 1
3.  Use MySQL command like "mysql -uroot -h 127.0.0.1 -p -P3307"  is OK.

**Comment by CrackerSuperior** [comment]
Can you try to update NaviCat.
15.0.26 No problem temporarily
