### ISSUE TITLE
Try to fix that using function(like to_date()) in INSERT sql will cause parameter loss problem

### ISSUE THREAD

**Issue by liuziyi16** [apache/shardingsphere#14409]
### Executing the following sql in mapper will cause parameter loss problem
```
<insert id="insert" parameterType="com.sharding.entity.Student">
        insert into student (id,name,sex,birthday)
        values
        ( #{id}, #{name}, #{sex}, STR_TO_DATE(#{birthday},"%Y-%m-%d"))
</insert>
```
## My Solution
I find the problem happens in class **InsertValueContext** function **calculateParametersCount**
```
    private int calculateParametersCount(final Collection<ExpressionSegment> assignments) {
        int result = 0;
        for (ExpressionSegment each : assignments) {
            if (each instanceof ParameterMarkerExpressionSegment ) {
                result++;
            }
        }
        return result;
    }
```
### I fix the code as below
```
    private int calculateParametersCount(final Collection<ExpressionSegment> assignments) {
        int result = 0;
        for (ExpressionSegment each : assignments) {
            if (each instanceof ParameterMarkerExpressionSegment || each instanceof ExpressionProjectionSegment) {
                result++;
            }
        }
        return result;
    }
```

**Comment by zjcnb** [comment]
@liuziyi16  Hi, thanks for your feedback. And the 4.0.1 version is too old, can you try the latest 5.0.0 version?

**Comment by liuziyi16** [comment]
@zjcnb We used the 4.0.1 version at the beginning, and we were worried that if it was safe to upgrade it to 5.0.0. So I try to fix the problem in 4.0.1 version or 4.1.1 version so that I can use the version 4.0.1 normally.

**Comment by zjcnb** [comment]
> @zjcnb We used the 4.0.1 version at the beginning, and we were worried that if it was safe to upgrade it to 5.0.0. So I try to fix the problem in 4.0.1 version or 4.1.1 version so that I can use the version 4.0.1 normally.

It's cool, you can try fix it in 4.x version, By the way, 5.1.0-release version are coming. It 's analyze the biggest improvement on sql.

**Comment by liuziyi16** [comment]
> It's cool, you can try fix it in 4.x version, By the way, 5.1.0-release version are coming. The sql parse are improved a lot.

Thanks for your help. I'm very looking forward to the 5.1.0-release version. I've learnt a lot from 5.0.0.

**Comment by terrymanu** [comment]
The version 4.x is out of service, I just close this issue.
