### ISSUE TITLE
What are the limitations of shardingsphere type conversion, and the unsupported type conversion should prompt an error message

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#14430]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
yes, like https://github.com/apache/shardingsphere/issues/14175
### Describe the feature you would like.
Shardingsphere type handling is too general, many conversions are database dependent, and the Merge Engine handles single routing differently.
I don't think ShardingSphere should support too many type conversions, but you need to prompt the corresponding information.

**Comment by SirMin** [comment]
Boolean type conversion differences between mysql 8.x driver and PostgreSQL
the mysql 8.x's code in com.mysql.cj.result.BooleanValueFactory
![image](https://user-images.githubusercontent.com/16568907/147638729-ee7ab878-b9f9-4bef-934c-1a69948d86d8.png)
postgresql's code in org.postgresql.jdbc.BooleanTypeUtil
![image](https://user-images.githubusercontent.com/16568907/147638828-de505a75-0c68-4fc9-923d-7cab09db1872.png)
I think the merge engin get value need refactor.
I'm comparing mysql with Postgresql.

**Comment by tuichenchuxin** [comment]
@SirMin Could you try to submit a pr?

**Comment by SirMin** [comment]
@tuichenchuxin The changes here are a bit big. I will prepared a document for the implemented logic and posted it in the issue. Take a look. If you think there is no problem, I will submit a pr

**Comment by tuichenchuxin** [comment]
@SirMin Sure, Thanks a lot.

**Comment by SirMin** [comment]
@tuichenchuxin  Can I send email to you, I has some question about this issue.

**Comment by tuichenchuxin** [comment]
@SirMin Sure.

**Comment by SirMin** [comment]
@tuichenchuxin  I'm sorry, I can't find your email, if you don't want publish email, I already publish my email.
