### ISSUE TITLE
When there is "-" in shcemaname, an error is reported when select with database name

### ISSUE THREAD

**Issue by zhouyouwei-0127** [apache/shardingsphere#14441]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Problem description
config:
![image](https://user-images.githubusercontent.com/64695476/147738802-ed197a61-f2d8-45a2-8f0a-89bbb9b9b9b7.png)

table:
![1640856750(1)](https://user-images.githubusercontent.com/64695476/147739373-0494877f-5403-4615-b3b4-612adc608a87.jpg)

sql and execution results:
![image](https://user-images.githubusercontent.com/64695476/147739820-430b81df-51c9-4d4d-b3fa-d6107303b2e2.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
All in the problem description
### Example codes for reproduce this issue (such as a github link).
All in the problem description

**Comment by zjcnb** [comment]
@zhouyouwei-0127 Hi, you can use `select * from "a-proxy".t_user;` and try it again.

**Comment by strongduanmu** [comment]
It seems that the native mysql does not support the `-` in the schemaName.

![image](https://user-images.githubusercontent.com/10829171/147747732-54761ede-a68b-4ace-9e38-cd20549f5a00.png)

**Comment by zhouyouwei-0127** [comment]
> 
Tank you for your advice，select * from "a-proxy".t_user is OK
@zjcnb

**Comment by zhouyouwei-0127** [comment]
> It seems that the native mysql does not support the `-` in the schemaName.
> 
> ![image](https://user-images.githubusercontent.com/10829171/147747732-54761ede-a68b-4ace-9e38-cd20549f5a00.png)

OK. I see, Thank you
