### ISSUE TITLE
Why does starting the shardingsphere-proxy after configuration mode (zk) disable all data sources by default? And there is no mechanism to resume enabled it??

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#14450]
Use version 5.0 0. Why do I start shardingsphere proxy debugging code after configuring mode (zk) found in: `org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.afterBuildContextManager()` disables all data sources by default, although it finds the processing method of subscription status change `org.apache.shardingsphere.mode.manager.cluster.coordinator.ClusterContextManagerCoordinator.renew(DisabledStateChangedEvent event)`, but I don't know where is the original mechanism to trigger enable dataSources? This affects my use of Mgr discovery. For example, when I start, I must report an error `org.apache.shardingsphere.dbdiscovery.mgr.MGRDatabaseDiscoveryType.updateMemberState()`

**Comment by wl4g** [comment]
So I was forced to increase my judgment:

```java
    @Override
    public void updateMemberState(final String schemaName, final Map<String, DataSource> dataSourceMap,
            final Collection<String> disabledDataSourceNames) {
        Map<String, DataSource> activeDataSourceMap = new HashMap<>(dataSourceMap);
        if (!disabledDataSourceNames.isEmpty()) {
            activeDataSourceMap.entrySet().removeIf(each -> disabledDataSourceNames.contains(each.getKey()));
        }

        //
        // [BUGFIX for ADD check no active dataSources]
        //
        /**
         * Refer sources code:
         * {@link org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder#afterBuildContextManager}
         * {@link org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder#disableDataSources}
         * {@link org.apache.shardingsphere.dbdiscovery.rule.DatabaseDiscoveryRule#updateStatus(DataSourceStatusChangedEvent)}
         */
        if (isEmpty(activeDataSourceMap)) {
            log.warn("Cannot update member state, because any are no active dataSources.");
            return;
        }

        List<String> memberDataSourceURLs = findMemberDataSourceURLs(activeDataSourceMap);
        if (memberDataSourceURLs.isEmpty()) {
            return;
        }
        Map<String, String> dataSourceURLs = new HashMap<>(16, 1);
        determineDisabledDataSource(schemaName, activeDataSourceMap, memberDataSourceURLs, dataSourceURLs);
        determineEnabledDataSource(dataSourceMap, schemaName, memberDataSourceURLs, dataSourceURLs);
    }
```

**Comment by zjcnb** [comment]
@wl4g Hi, i think build discovery rule and find master-slaven relation frist, and then call disableDataSources() method. So i think it 's no problem. But disableDataSources() method are useless.

**Comment by wl4g** [comment]
No, I see what you mean. What you must pay attention to is that although you execute `org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.beforeBuildContextManager` will eventually call `org.apache.shardingsphere.dbdiscovery.spi.MGRDatabaseDiscoveryType.startPeriodicalUpdate`, and then execute `org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.afterBuildContextManager()` that is, the MGR discovery scan job is timed and can only be in a few seconds (the official example is 5sec)

**Comment by wl4g** [comment]
The core is that asynchronous causes problems!!!

**Comment by wl4g** [comment]
```yaml
rules:
# Ignore other configuration ...
 - !DB_DISCOVERY
   dataSources:
# Ignore other configuration ...
   discoveryTypes:
     cn_south1_a1_mgr_g0_0:
       type: MGR
       props:
         groupName: 5db40c3c-180c-11e9-afbf-005056ac6820
         zkServerLists: 'localhost:2181'
         keepAliveCron: '0/5 * * * * ?'
```

**Comment by wl4g** [comment]
This field:  `keepAliveCron`

**Comment by wl4g** [comment]
Let's put aside this problem for the time being. I can fix this asynchronous problem myself, but another important question is, is there any mechanism to trigger the execution of `enabledDataSources()` ?  Do you want me to delete ZK's node `/shardingproxy manually_ 0/status/storage_ nodes/disable` ???

**Comment by wl4g** [comment]
@zjcnb

**Comment by wl4g** [comment]
@terrymanu

**Comment by wl4g** [comment]
I guess, does the designer consider consistently enabling the data source after the cluster multi node startup is completed? But I didn't find the enabling code?

**Comment by zjcnb** [comment]
> Let's put aside this problem for the time being. I can fix this asynchronous problem myself, but another important question is, is there any mechanism to trigger the execution of `enabledDataSources()` ? Do you want me to manually delete ZK's node `/shardingproxy_0/status/storage_nodes/disable/xxx` ???

I think you can use ShardingSphere DistSQL to delete it If you use ShardingSphere-Proxy.

**Comment by zjcnb** [comment]
By the way, ShardingSphere database discovery can automatically correct enabled and disabled states. i think you need't to manually delete it.

**Comment by zjcnb** [comment]
> This field: `keepAliveCron`, It will may delay execution for 5 sec first

it 's not right, you can see DatabaseDiscoveryRule class:

```
    private DatabaseDiscoveryRule(final String schemaName, final Map<String, DataSource> dataSourceMap, final Collection<DatabaseDiscoveryDataSourceRuleConfiguration> dataSourceRuleConfigs,
                                  final Map<String, DatabaseDiscoveryHeartBeatConfiguration> heartBeatConfig, final Map<String, DatabaseDiscoveryType> discoveryTypes) {
        this.discoveryTypes = discoveryTypes;
        dataSourceRules = getDataSourceRules(dataSourceRuleConfigs, heartBeatConfig);
        findMasterSlaveRelation(schemaName, dataSourceMap);
        initAware();
        initHeartBeatJobs(schemaName, dataSourceMap);
    }
```

**Comment by wl4g** [comment]
I fully understand and understand what you mean now, but there are bugs here. I also see that the two methods' `determineDisabledDataSource` and `determineEnabledDataSource` are used to automatically maintain the disabled state, but what you don't notice is, When the `updateMemberState` and `updatePrimaryDataSource` were first executed, all data sources were filtered by the `disabledDataSourceNames` parameter. This is the key point, which led to the failure of all the automatic maintenance states you said...

**Comment by wl4g** [comment]
Namely: activeDataSourceMap.isEmpty is true, do you understand now?

**Comment by wl4g** [comment]
![image](https://user-images.githubusercontent.com/29530154/147807670-eef9f430-1a85-4dd5-9767-62af3ba0e232.png)

**Comment by wl4g** [comment]
I added the above judgment myself

**Comment by wl4g** [comment]
Now let's go back to your ideas. I think all your ideas are OK, but invoke `org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.disableDataSources()` at startup is wrong.

**Comment by zjcnb** [comment]
> Now let's go back to your ideas. I think all your ideas are OK, but invoke `org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.disableDataSources()` at startup is wrong.

Yes, i think you can submit a pull reqeust to remove it.

**Comment by zjcnb** [comment]
> Namely: activeDataSourceMap.isEmpty is true, do you understand now?

I understand your mean, activeDataSourceMap may be empty if master-slave node are disable.

**Comment by wl4g** [comment]
@zjcnb

**Comment by zjcnb** [comment]
> Hello, last time I found that the version was different, I used 5.0.0 and you used 5.1.0, I have solved it by modifying the source code, but now I found a new problem, see: [#14724](https://github.com/apache/shardingsphere/issues/14724), and I also found that tag/5.1.0 was deleted by the author? ? ?

Ok, let us see.

**Comment by terrymanu** [comment]
The version is out of service, please try new version
