### ISSUE TITLE
route sql to write datasource based on username or listen address.

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#14472]
### Describe the feature you would like.
read write split datasource can be routed through hint. but it'll be more convenient to use username or connection host to set hint automatically.

example:
when user name is `db_writeonly`, session could set writeonly hint automatically;

or we can add a new property `writeOnlyHost` to read write split configuration, if user connect to database use `writeOnlyHost` then set writeonly hint automatically on that session. (it may difficult to get connection host, since host is always converted to IP address before connect to database. however, if user connect to database use lo network, we can distinguish different host ip, like 127.0.0.1, 127.0.0.2, and etc)

**Comment by tuichenchuxin** [comment]
@roodkcab Does it means config a userName, if it is same with the name used. Then using the writeOnly?

**Comment by roodkcab** [comment]
> @roodkcab Does it means config a userName, if it is same with the name used. Then using the writeOnly?

yes, it is.

**Comment by strongduanmu** [comment]
Hi @roodkcab, we have provide [sql hint](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E8%B7%AF%E7%94%B1%E8%87%B3%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93) in the master branch. I think you can try it.

**Comment by roodkcab** [comment]
> Hi @roodkcab, we have provide [sql hint](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E8%B7%AF%E7%94%B1%E8%87%B3%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93) in the master branch, I think you can try it. SQL hint can implement primary dataSource routing through comments in sql.
> 
> ```sql
> /* ShardingSphere hint: writeRouteOnly=true */
> SELECT * FROM t_order;
> ```

yes, I know. and we have distsql to change session based hint too. the need is to use hint by dsn, i.e. use host, port or username to set hint automatically.

**Comment by terrymanu** [comment]
What is the status of this issue? Can I close it?

**Comment by TeslaCN** [comment]
This issue has been inactive for a while, I'm closing it for now.
