### ISSUE TITLE
document config error

### ISSUE THREAD

**Issue by fangg2021** [apache/shardingsphere#14479]
ShardingSphere > User Manual > ShardingSphere-JDBC > Configuration Manual > Spring Boot Starter Configuration > Mixed Rules

***
# Sharding algorithm configuration
spring.shardingsphere.rules.sharding.sharding-algorithms.default-database-strategy-inline.type=INLINE
# The enumeration value of `ds_$->{user_id % 2}` is the name of the logical data source configured with readwrite-splitting
spring.shardingsphere.rules.sharding.sharding-algorithms.default-database-strategy-inline.algorithm-expression=ds$->{user_id % 2}
spring.shardingsphere.rules.sharding.sharding-algorithms.user-table-strategy-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user-table-strategy-inline.algorithm-expression=t_user_$->{user_id % 2}

***

that "user-table-strategy-inline.algorithm-expression" should be "user-table-strategy-inline.**props**.algorithm-expression"

**Comment by zjcnb** [comment]
@fangg2021 Hi, thanks for your feedback, it's really have a mistake. Can you submit a pull request to fix it.

**Comment by Swastyy** [comment]
@zjcnb I have corrected it. If the original person wants to do this you can close it.
