### ISSUE TITLE
Make ShardingSphere-Proxy acts like how database does when rejecting connections which exceeded proxy-frontend-max-connections

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#14497]
### Is your feature request related to a problem?

When connections to ShardingSphere-Proxy exceeded `proxy-frontend-max-connections`, the way of rejecting connections to ShardingSphere-Proxy is different with how actual database does. This is not friendly to client which wants to connect to ShardingSphere-Proxy.

https://github.com/apache/shardingsphere/blob/21b2802b888ae20264d5a6c338e114b3193ce5bb/shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelLimitationInboundHandler.java#L33-L54

### Describe the feature you would like.

Make ShardingSphere-Proxy acts like how actual database does when rejecting connections which exceeded `proxy-frontend-max-connections`.

**Comment by soulasuna** [comment]
I will do.

**Comment by TeslaCN** [comment]
@soulasuna Welcome. Assigned.
