### ISSUE TITLE
on encrypt, subquery projections token error, cause sql executor throw sqlexception

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14506]
### Which version of ShardingSphere did you use?
5.1.0-GA

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior
``` sql
SELECT b.address, b.normal_field 
FROM (SELECT a.address_cipher as address, a.normal_field FROM ec_oms_order a WHERE a.order_code = 1373) b;
```
and ``` b.address ``` projection can ``` findEncryptor() ``` =true to decrypt column data.

### Actual behavior
``` sql
SELECT b.address_cipher as address, b.normal_field 
FROM (SELECT a.address_cipher as address, a.normal_field FROM ec_oms_order a WHERE a.order_code = 1373) b;
```
exception: 
Unknown column 'b.address_cipher' in 'field list',  due to suquery without address_cipher.

### Reason analyze (If you can)
 subquery & resultset  projections has sql rewrite bug, when query & subquery both had encrypt column .

In resultset . ``` b.address_cipher as address  ``` projection, name  must to ```address_cipher``` , can ``` findEncryptor()`` to  decrypt column data ,  but subquery , ``` a.address_cipher as address ```  result unkown ``` b.address_cipher``` .

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
rule: 
tables: 
 ec_oms_order: 
  address:
    columnPlain: address
    columnCipher: address_cipher
    encrypter: encrypt-aes
 queryWithCipherColumn: true

**Comment by strongduanmu** [comment]
@userkdg Thank you for your feedback, I will investigate this issue.

**Comment by cheese8** [comment]
I will check on it laster. please assign it to me.

**Comment by strongduanmu** [comment]
> I will check on it laster. please assign it to me.

@cheese8 Welcome.

**Comment by cheese8** [comment]
Hi @userkdg What is your logicSQL? I checked this as below on master，not very good but at it's ok:

LogicSQL:

SELECT b.certificate_number, b.amount FROM (SELECT a.certificate_number as certificate_number, a.amount FROM t_account a WHERE a.amount = 1373) b

ActualSQL:

SELECT b.cipher_certificate_number AS certificate_number, b.cipher_amount AS amount FROM (SELECT a.cipher_certificate_number, a.assisted_query_certificate_number, a.cipher_amount FROM t_account a WHERE a.cipher_amount = 1373) b

**Comment by userkdg** [comment]
> Hi @userkdg What is your logicSQL? I checked this as below on master，not very good but it's ok:
> 
> LogicSQL:
> 
> `SELECT b.certificate_number, b.amount FROM (SELECT a.certificate_number as certificate_number, a.amount FROM t_account a WHERE a.amount = 1373) b`
> 
> ActualSQL:
> 
> `SELECT b.cipher_certificate_number AS certificate_number, b.cipher_amount AS amount FROM (SELECT a.cipher_certificate_number, a.assisted_query_certificate_number, a.cipher_amount FROM t_account a WHERE a.cipher_amount = 1373) b`

very thinks.
yes. this is ok. it must to analyze out projections & (mutil ) subquery projections, and then
i met two case
- column projections
 like your example

- shorthand projections case
``` 
select b.* from (select a.address, a.address as addr2, … from ec_oms_order a) b 
```

**Comment by cheese8** [comment]
ok,  get it, @userkdg  there is a problem in shorthand case. i will fix it soon.

**Comment by TeslaCN** [comment]
Hi @strongduanmu @cheese8 
Any update here?

**Comment by tuichenchuxin** [comment]
Fixed.
