### ISSUE TITLE
springboot + shardingSphere5.0 + Dubbo2.7.x实现分库分表的情况下，集成 + seata1.4.2后，报出以下异常： Could not found any index in the table: xxx 

### ISSUE THREAD

**Issue by jlovej** [apache/shardingsphere#14518]
各位大神好，我在springboot + seata1.4.2 + Dubbo2.7.x实现分库分表(3个库，t_order分4张表)的情况下，集成 + shardingSphere5.0 后，报出以下异常：
Could not found any index in the table: xxx，查看了下源码，在seata1.4.2中的io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache#resultSetMetaToSchema方法调用org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData#getIndexInfo时无法获取到MetaData的主键与索引信息，最终导致seata中的(tm.getAllIndexes().isEmpty()】这行条件成立就会抛出异常，请问是什么原因，谢谢。

**Comment by strongduanmu** [comment]
Hi @jlovej, can you translate this issue to english?

**Comment by jlovej** [comment]
> 各位大神好，我在springboot + seata1.4.2 + Dubbo2.7.x实现分库分表(3个库，t_order分4张表)的情况下，集成 + shardingSphere5.0 后，报出以下异常： Could not found any index in the table: xxx，查看了下源码，在seata1.4.2中的io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache#resultSetMetaToSchema方法调用org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData#getIndexInfo时无法获取到MetaData的主键与索引信息，最终导致seata中的(tm.getAllIndexes().isEmpty()】这行条件成立就会抛出异常，请问是什么原因，谢谢。

To english：
Springboot + Seata1.4.2 + Dubbo2.7.x + shardingSphere5.0

Could not found any index in the table: XXX, looked at the source code, IO in seata1.4.2. Seata. Rm. The datasource. SQL. Struct. Cache. MysqlTableMetaCache# resultSetMetaToSchema method call org. Apache. Shardingsph Ere. Driver. JDBC. Core. The datasource. Metadata. ShardingSphereDatabaseMetaData# getIndexInfo when unable to get the primary key and index to the metadata information, If (tm.getallIndexes ().isEmpty()) is valid, an exception will be thrown.

**Comment by jingshanglu** [comment]
@jlovej Can you give the stack info? what is your `config-sharding.yaml`?  and give the reproduce step.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by jlovej** [comment]
看不懂中文吗？是中国人吗

**Comment by strongduanmu** [comment]
Hi @jlovej ShardingSphere is an international project. Using English can facilitate communication between people of different language backgrounds. If you want to submit a question in Chinese, please use the [OpenSEC](https://community.sphere-ex.com/).

**Comment by ZhangLong-19991216** [comment]
May I ask, how did you solve, I also met the same problem
