### ISSUE TITLE
ShardingSphere-Proxy配置

### ISSUE THREAD

**Issue by xcmonline** [apache/shardingsphere#14529]
看官网中只是要求对conf目录下的yaml配置文件进行配置，不知道其中具体的配置说明有没有比较详细的文档或案例。

**Comment by linghengqian** [comment]
Examples in the source file provide detailed examples of various modules.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by xcmonline** [comment]
> **仅适用于英语**，不接受其他语言。

有条款一定使用英文吗？为什么歧视中文？

**Comment by linghengqian** [comment]
@xcmonline 
I don't know why you have a problem with discriminating against Chinese. When you create an issue, the issue template is limited to English for others to read. Of course, Shardingsphere corresponds to a community of domestic users, https://community.sphere-ex.com/
```
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

```
