### ISSUE TITLE
on proxy, in release application, do update, delete, add transaction  sql operation will throw read only  Exception.

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14541]
### Which version of ShardingSphere did you use?
5.1.0-GA

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior
update, delete, add sql will throw read only Exception.

### Actual behavior
from application log: 
![image](https://user-images.githubusercontent.com/21057449/148184941-732e7d80-6679-474d-b753-c197b7f4ee00.png)

from proxy log:
<img width="705" alt="1641374110(1)" src="https://user-images.githubusercontent.com/21057449/148192129-bc93cd66-5f3d-4e87-baf5-b597d2535e3a.png">

remark:  two case are transaction issues.

### Reason analyze (If you can)
In the application connection agent, if transaction operations are performed, such as (batch) new addition, (batch) modification, (batch) deletion, exceptions will occur
feature:
- Occasionally
- Prone to happen under multithreading
- Transactional

remark: Personal level is limited, unable to locate specific code issues for transaction issues, But this is more important for application . 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
single transaction sql
application env:
- druid pool (default transaction config)
- spring transaction 
proxy env:
 ``` - !TRANSACTION
  defaultType: XA | LOCAL
  providerType: Atomikos | null ```

**Comment by userkdg** [comment]
Important, currently the application cannot be accessed (+﹏+) ~~~

**Comment by jingshanglu** [comment]
@userkdg Can you give the sql from you app to proxy? now, from the stack info, maybe your app start a transaction with `read only` and then run a `insert` statement, then the exception exported is expected.

**Comment by userkdg** [comment]
> 
yes, i give a app logic sql now. 
as: 
step1: scheduler job 
<img width="586" alt="1641438128(1)" src="https://user-images.githubusercontent.com/21057449/148321532-0a8b2ae4-be2a-4cbf-83bf-a7c86df024c7.png">
step2:  service no set transaction 
<img width="260" alt="1641438282(1)" src="https://user-images.githubusercontent.com/21057449/148321760-7d19e78e-b3d7-443f-9429-301e6fe40e4f.png">
step3: update
<img width="573" alt="1641438354(1)" src="https://user-images.githubusercontent.com/21057449/148321865-c4725edf-c485-415a-b480-f1ab6dc576dc.png">
step4: update sql using tk-mybatis 
<img width="645" alt="1641438386(1)" src="https://user-images.githubusercontent.com/21057449/148321914-af7693d1-85b8-4506-b44e-60c65fa6d4c7.png">

remark: this is one case in app

**Comment by jingshanglu** [comment]
@userkdg Are the above feature and features used `@Transactional(readOnly = true)`  in different schemas? Is it same as #14187 ？

**Comment by userkdg** [comment]
@jingshanglu Make sure only one schema is used.  
- under ``` @Transactional(readOnly = true) ``` , the app feature can work normally when the app is not connected to the proxy 
- sporadic, Not all transaction operations will report errors, and some errors will occur after a period of time

this is doubt.

**Comment by jingshanglu** [comment]
@userkdg Ok, these two feature use one connection to proxy, it maybe why you meet the exception.
Did these two features use the same connection to proxy before?

**Comment by userkdg** [comment]
@jingshanglu maybe use the same connection on app,  normal app used connection pool, and then reuse connection, This is similar to the problem of reuse connection on proxy , but the  features can work normally when the app is not connected to the proxy.

**Comment by jingshanglu** [comment]
@userkdg Normally, it also come when app connect to MySQL using connection pool. You open a connection by MySQL-Client to MySQL, run `set transaction read only` and some sql, then you reuse the conn, and run a `insert`, it also  appear. In proxy,  only in a connection from app to proxy, proxy will reuse connection  to DB.
