### ISSUE TITLE
An error is reported when creating a view using the broadcast table：Can not support sharding table

### ISSUE THREAD

**Issue by Huletian** [apache/shardingsphere#14544]
# An error is reported when creating a view using the broadcast table：Can not support sharding table

## Create view statement
CREATE   VIEW `v_subject_type` AS
SELECT DISTINCT
`dw_subject`.`subject_type_code` AS `subject_type_code`,
`dw_subject`.`subject_type` AS `subject_type` 
FROM
	`dw_subject`

## config-sharding.yml configuration information
  broadcastTables:
    - dw_subject

**Comment by strongduanmu** [comment]
Hi @Huletian, thank you for your feedback, I will track this issue.
