### ISSUE TITLE
[DistSQL] NPE occurs when preview SQL by `schema.table`. 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14558]
### Which version of ShardingSphere did you use?
5.0.1-SNAPSHOT master branch
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Preview SQL execute success.
### Steps to reproduce the behavior
1. config sharding rule in YAML.
2. connect Proxy with MySQL Cli.
3. show databases, display `sharding_db`;
4. execute: `select * from sharding_db.t_order;`   SUCCESS
5. execute: `preview select * from sharding_db.t_order;` NPE

**Comment by yx9o** [comment]
I want to try.

**Comment by RaigorJiang** [comment]
@yx9o Thank you

**Comment by yx9o** [comment]
@RaigorJiang The reasons for positioning the NPE are as follows:
![image](https://user-images.githubusercontent.com/12792261/148342486-14c9b18f-0112-4240-a768-7cf6ff19a23a.png)
