### ISSUE TITLE
how can i find version 5.0`s config

### ISSUE THREAD

**Issue by yuanjinzhong** [apache/shardingsphere#14553]
such as below 

      1. spring.shardingsphere.rules : 规则配置
　　2. spring.shardingsphere.rules.sharding.sharding-algorithms : 分库分表规则配置
　　3. spring.shardingsphere.rules.sharding.tables : 分库分表对象配置
　　4. spring.shardingsphere.rules.sharding.key-generators : 分布式序列配置
　　5. spring.shardingsphere.rules.replica-query : 读写分离配置
　　6. spring.shardingsphere.rules.encrypt : 数据脱敏配置

**Comment by linghengqian** [comment]
Maybe I don't understand what you're trying to say. I think you should use all English.

**Comment by yuanjinzhong** [comment]
> Maybe I don't understand what you're trying to say. I think you should use all English.

你好，我在学习使用sharding-jdbc 5.0。然后我上网搜索教程的时候，发现教程上说5.0和v4版本配置有差异。

网上教程显示v5版本的配置是：

spring.shardingsphere.**rules**. sharding.XXX 

官网上的配置是：

spring.shardingsphere.sharding.XXX

然后我就困惑了，应该使用什么配置。哪里可以查询到配置？

希望有同学给我解答一下，比心♥️

**Comment by strongduanmu** [comment]
> 

Hi @yuanjinzhong, can you translate this answer to english? If you want to use Chinese, you can submit questions at [OpenSEC](https://community.sphere-ex.com/).

**Comment by yuanjinzhong** [comment]
> > 
> 
> Hi @yuanjinzhong, can you translate this answer to english? If you want to use Chinese, you can submit questions at [OpenSEC](https://community.sphere-ex.com/).

Hi, I am learning to use Sharding-JDBC 5.0. Then I searched the tutorial online and it said there was a configuration difference between version 5.0 and VERSION V4.

The online tutorial shows that the v5 configuration is:

spring.shardingsphere.rules. sharding.XXX

The configuration on the official website is:

spring.shardingsphere.sharding.XXX

Then I was confused about what configuration to use. Where can I query the configuration?

Hope to have a classmate to answer me, than the heart ♥️

**Comment by strongduanmu** [comment]
You can refer to official example —— https://github.com/apache/shardingsphere/tree/master/examples.

**Comment by yuanjinzhong** [comment]
> You can refer to official example —— https://github.com/apache/shardingsphere/tree/master/examples.

thanks

**Comment by yuanjinzhong** [comment]
> > 
> 
> Hi @yuanjinzhong, can you translate this answer to english? If you want to use Chinese, you can submit questions at [OpenSEC](https://community.sphere-ex.com/).

[OpenSEC](https://community.sphere-ex.com/) is very good.  i found a new world

**Comment by WENZIZZHENG** [comment]
我个人做了个demo，你可以参考一下：https://github.com/WENZIZZHENG/spring-boot-demo/tree/master/spring-boot-sharding-jdbc

**Comment by yuanjinzhong** [comment]
> 我个人做了个demo，你可以参考一下：https://github.com/WENZIZZHENG/spring-boot-demo/tree/master/spring-boot-sharding-jdbc

很棒，3Q

**Comment by terrymanu** [comment]
This issue is opened for long time any no feedback, I just close it.
