### ISSUE TITLE
Request to support SkyWalking v6 backend

### ISSUE THREAD

**Issue by wu-sheng** [apache/shardingsphere#1460]
I have known SkyWalking always has sharding-sphere project supported. Since we have begun the release process of SkyWalking 6.0.0-alpha, I hope we could build a more stable and convenience solution by using sharding-sphere as SkyWalking storage implementor.

In v6, I intend to support JDBC, TiDB and sharding-sphere with MySQL style. I think they could be compatible with each other. But consider sharding-sphere needs some sharding rules, let's talk about that, and make sure which is best for the product env.

**Comment by wu-sheng** [comment]
No time line for this, but I will do some implement for MySQL and TiDB from next week, welcome to join

**Comment by terrymanu** [comment]
The previous version of sharding-jdbc's backend for SkyWalking is sharding by datetime.
Could we use  previous sharding rule to do it for SkyWalking v6?

**Comment by wu-sheng** [comment]
We could. But at real product env, I have some doubts. This wouldn't help on performance, just save more data.

**Comment by terrymanu** [comment]
Any idea on that, maybe hash with spanId?

**Comment by wu-sheng** [comment]
Many tables, not just trace.

**Comment by kimmking** [comment]
@yu199195 has been finish it.
