### ISSUE TITLE
数据脱敏存在一些SQL支持问题

### ISSUE THREAD

**Issue by ha543624703** [apache/shardingsphere#14603]
Data Masking does not support batch update of case when writing method，like:
UPDATE `city` 
SET NAME =
CASE
		WHEN id = 1 THEN 'nj' 
		WHEN id = 2 THEN 'wh' 
	END,
	address =
CASE
		WHEN id = 1 THEN 'abc' 
		WHEN id = 2 THEN 'def' 
	END 
	WHERE
		id IN (1,2);

**Comment by strongduanmu** [comment]
Hi @ha543624703, can you translate this issue to english? And show your encrypt config?
