### ISSUE TITLE
[DistSQL] Add a syntax `SHOW UNUSED SHARDING  KEY GENERATORS`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14610]
Hi community,

### Background
Similar to [SHOW UNUSED SHARDING ALGORITHMS](https://github.com/apache/shardingsphere/issues/14609), we need a syntax to query unused key generators.

### Aim
The syntax is as follows:
```sql
SHOW UNUSED SHARDING KEY GENERATORS [FROM schemaName]
```

**Comment by yx9o** [comment]
I want.
