### ISSUE TITLE
on encrypt ，add check function 

### ISSUE THREAD

**Issue by cicscpmi** [apache/shardingsphere#14622]
## Feature Request
The encrypted field cannot support calculation operation. Can you add a check function to check whether the field operated by the current function contains the field to be decrypted?

**Comment by strongduanmu** [comment]
Hi @cicscpmi, can you provide more information to describe your feature request?

**Comment by cicscpmi** [comment]
in  EncryptMergedResult,for example:
    if  the column that  the findColumnProjection finds  is not a columnProject, such as  expressionProject ,findColumnProjection returns  Optional.empty() ;
   Can you provide a function to find  any column when the column findColumnProjection finds is  an expressionProject ,and the column expression include any encrypt column.
  For example:
    in table t_users include id,name,pwd column,the pwd is a encrypt column.
  when sql is select id ,name ,CONCAT(name,pwd) as val from t_user;
 getValue(val) find this column(val) is not a columnProject . and the express is "CONCAT(name,pwd)" include pwd is a encrypt. Can you provide a function to check this ?

**Comment by tuichenchuxin** [comment]
@cicscpmi Are you willing to submit a pr?

**Comment by cheese8** [comment]
Assign it to me, I will try to enhance it. @strongduanmu @tuichenchuxin

**Comment by strongduanmu** [comment]
> in EncryptMergedResult,for example: if the column that the findColumnProjection finds is not a columnProject, such as expressionProject ,findColumnProjection returns Optional.empty() ; Can you provide a function to find any column when the column findColumnProjection finds is an expressionProject ,and the column expression include any encrypt column. For example: in table t_users include id,name,pwd column,the pwd is a encrypt column. when sql is select id ,name ,CONCAT(name,pwd) as val from t_user; getValue(val) find this column(val) is not a columnProject . and the express is "CONCAT(name,pwd)" include pwd is a encrypt. Can you provide a function to check this ?

@cicscpmi Sorry for later reply. Even we add this check logic for expression which contains encrypt column, but the result is still not correct, because we can't distinguish encrypt value from expression value.

**Comment by cheese8** [comment]
I strongly recommended that do not write logic in sql,  writing the logic using java code.
