### ISSUE TITLE
shardingsphere sql parser support multi statements 

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14636]
### Is your feature request related to a problem?
app/client had some one request with mult sql , such as ,the mybatis xml 
``` xml 

<update>
    <foreach collection="bos" item="item" split=";">
        update xx set name= #{item.name} where  id = #{item.id}
    </foreach>
</update>
```

### Describe the feature you would like.
on sharding-proxy,  accept one packet with multi sql, can foreach every sql packet to submitted.

**Comment by TeslaCN** [comment]
Could you provide more information about this issue?

**Comment by userkdg** [comment]
need support :
![Uploading image.png…]()

**Comment by TeslaCN** [comment]
> @TeslaCN one packet had mult sql from app, then proxy will throw exception ,such as :
> 
> ```java
> Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `ec_oms_config_order_hang_sub` (`hand_code`, `order_type`, `province' at line 1
> ```
> 
> ![image](https://user-images.githubusercontent.com/21057449/149514220-0c39677d-1a1a-4af6-b1fe-a7374167815e.png)

@userkdg I seems this exception was thrown by JDBC Driver instead of Proxy.

**Comment by userkdg** [comment]
> > @TeslaCN one packet had mult sql from app, then proxy will throw exception ,such as :
> > ```java
> > Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `ec_oms_config_order_hang_sub` (`hand_code`, `order_type`, `province' at line 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/21057449/149514220-0c39677d-1a1a-4af6-b1fe-a7374167815e.png)
> 
> @userkdg It seems this exception was thrown by JDBC Driver instead of Proxy.

This issue has been fixed locally, reason is :
mybatis foreach insert/update... sql parser error and sharding-encrypt sql rewrite unsupport

**Comment by TeslaCN** [comment]
@userkdg You may consider doing batched inserts by multi values instead of multi statements.

**Comment by userkdg** [comment]
@TeslaCN It is not friendly to mature business systems. In addition, shouldn't we solve this problem from the framework?

**Comment by TeslaCN** [comment]
It is not because of unsupported feature, insert with values may faster than multi statements.

**Comment by terrymanu** [comment]
ShardingSphere does not support multiple SQL in one query.
Does anyone want to do this issue?
