### ISSUE TITLE
"show scaling status jobId" might respond "Malformed packet"

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14641]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy, scaling

### Expected behavior
No error message return

### Actual behavior
Sometimes it respond "Malformed packet":
```
mysql> show scaling status 1757889056821006;
ERROR 2027 (HY000): Malformed packet
```

**Comment by sandynz** [comment]
Hi @ReyYang , Could you investigate this issue?

**Comment by ReyYang** [comment]
ok, i'll take a look
