### ISSUE TITLE
[Sharding5.0.0] Use @ShardingSphereTransactionType(TransactionType. XA) is set to the XA transaction type is not effective 

### ISSUE THREAD

**Issue by kangshiwei** [apache/shardingsphere#14654]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
Hi @kangshiwei  
why you say it doesn't work, please provide more info

**Comment by kangshiwei** [comment]
When XA transactions are used in version 4.1.0, ENABLING DEBUG logging results in XA-related logs.   But in the use of 5.0.0 version, in the add @ ShardingSphereTransactionType (TransactionType.   XA), no log information related to XA was found when debug logs were opened.  Local transactions were found after breakpoint debugging.

**Comment by RaigorJiang** [comment]
Hi @jingshanglu , please help take a look at this question.

**Comment by jingshanglu** [comment]
@kangshiwei Can you show a demo？

**Comment by kangshiwei** [comment]
![Uploading 企业微信截图_16421304638149.png…]()
![Uploading 企业微信截图_16421306201693.png…]()

**Comment by kangshiwei** [comment]
<img width="818" alt="企业微信截图_16421304638149" src="https://user-images.githubusercontent.com/25686458/149446512-e21a97cb-3d84-476d-885e-40743c2440bf.png">
<img width="1034" alt="企业微信截图_16421306201693" src="https://user-images.githubusercontent.com/25686458/149446545-96d33c19-ccdf-49fd-a67c-3ffc3385ed9b.png">
[Sharding-Jdbc-Simple-5.0.zip](https://github.com/apache/shardingsphere/files/7867626/Sharding-Jdbc-Simple-5.0.zip)

**Comment by jingshanglu** [comment]
What log in the picture above?  the following picture is just the log of shardingsphere,  you can check it through debug tracking.

**Comment by kangshiwei** [comment]
The log in the first image is a debug log printed using the XA transaction type in ShardingSphere-4.1.0
The log in the second image is a debug log printed using the XA transaction type in ShardingSphere-5.0.0

**Comment by zjcnb** [comment]
I think this problem are fixed in master branch. you can try. @kangshiwei

**Comment by ainydexiaohai** [comment]
同样的问题，楼主解决了吗？

**Comment by ainydexiaohai** [comment]
5.0.1-SNAPSHOT中已经解决，下载源码打包安装到本地仓库，pom文件中切换成5.0.1-SNAPSHOT版本即可。

**Comment by kangshiwei** [comment]
Ok! Thank you for your help. I'll try a new version next.
