### ISSUE TITLE
sharding-proxy proxy concurrency problem!!

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14650]
In the proxy, in the concurrent import data, the expected number of imported records is 10, but the actual number of imported records is less than or equal to 10. It is a sporadic problem, and the current positioning is a concurrency problem! Which concurrency caused it to not be located, here, please help you guys

**Comment by userkdg** [comment]
The access proxy is a stable system, and the function is normal before it is connected

**Comment by userkdg** [comment]
> In the proxy, in the concurrent import data, the expected number of imported records is 10, but the actual number of imported records is less than or equal to 10. It is a sporadic problem, and the current positioning is a concurrency problem! Which concurrency caused it to not be located, here, please help.

**Comment by TeslaCN** [comment]
Hi @userkdg 
I'm afraid that we can hardly help you unless you provide some information to help us reproduce this issue, such as DB, versions, configurations and so on.

**Comment by TeslaCN** [comment]
Hi @userkdg 
Any update here?

**Comment by terrymanu** [comment]
Closed because of no response.
