### ISSUE TITLE
Does sharding jdbc support mysql type longblob ?

### ISSUE THREAD

**Issue by ziliangzeng** [apache/shardingsphere#14666]
## Question
hi.
Does sharding JDBC support MySQL type longblob ? 
example: i have 4 database .  the broadcasttable was in 4 database.
when I try to insert into broadcastTable with longblob. it inserts success. 
but interesting thing is that It segmentation 4 parts. each database have 1/4 longblob.
in my mind . each data should have complete longblob .
that was confuse.

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because of it closed by author without any reason.
