### ISSUE TITLE
Add more unit test for SelectStatementContext

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14672]
Hi, community:

This issue is to add more unit tests for the SelectStatementContext class. Welcome to claim them.

The specific subtasks are as follows:

- [ ]  Add unit test for SelectStatementContext#isContainsDollarParameterMarker
- [ ]  Add unit test for SelectStatementContext#isContainsPartialDistinctAggregation

Through this issue, you can understand the process of participating in Apache ShardingSphere, and be familiar with sharding.

**Comment by Swastyy** [comment]
Hi @strongduanmu Can I please try this once? If I could not I'll inform you. Thanks.

**Comment by strongduanmu** [comment]
@Swastyy Welcome, I just assign this issue to you.

**Comment by strongduanmu** [comment]
Hi @Swastyy, does this issue has any progress?

**Comment by Swastyy** [comment]
Hi @strongduanmu , the test cases will be created in a separate file for both of them or inside the SelectStatementContextText.java?

**Comment by strongduanmu** [comment]
@Swastyy Inside the SelectStatementContextText.java may be better.

**Comment by Swastyy** [comment]
> @Swastyy Inside the SelectStatementContextText.java may be better.

Ok, thanks @strongduanmu .

**Comment by terrymanu** [comment]
Hi @Swastyy There are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by strongduanmu** [comment]
@Bpazy Welcome.
