### ISSUE TITLE
sql use 'binary' sharding is not support??

### ISSUE THREAD

**Issue by lafaso** [apache/shardingsphere#14694]
## Bug Report

Hello,Teachers，

this is my mysql table, and user_id is the sharding field.
![image](https://user-images.githubusercontent.com/16465114/148962086-0a4e1502-5703-4171-abdd-91bc5b7f827e.png)

when I execute the following SQL statement, it does not work!  just special for the ‘**binary** ’，it doesn't support '**binary**'?

`SELECT * FROM t_order WHERE order_id = #{orderId,jdbcType=INTEGER} AND user_id= binary #{userId,jdbcType=VARCHAR}`

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
it will sharding by user_id

### Actual behavior
no sharding

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL：
![IGri0ZDmi3](https://user-images.githubusercontent.com/16465114/148964250-18c3edf7-9020-4d32-ba31-17cfa4231c2b.png)

debug the method,return a empty map;
private Map<Column, Collection<RouteValue>> createRouteValueMap(SQLStatementContext sqlStatementContext, AndPredicate andPredicate, List<Object> parameters) 
1、
![image](https://user-images.githubusercontent.com/16465114/148964225-4f098406-ddec-4c9c-a2e9-5f50f87c71a4.png)
2、
![image](https://user-images.githubusercontent.com/16465114/148964706-392e6bdb-5797-418d-9023-dda8951fb504.png)
3、
![image](https://user-images.githubusercontent.com/16465114/148965112-db370664-88bf-4851-815d-aec3f9c46bc5.png)
4、
![image](https://user-images.githubusercontent.com/16465114/148965903-2048f856-2bfc-457b-82de-07a19ee7197c.png)

**Comment by strongduanmu** [comment]
@lafaso Thank you for your feedback, I will investigate this problem.
