### ISSUE TITLE
About using readwrite splitting hint function

### ISSUE THREAD

**Issue by lwclover** [apache/shardingsphere#14699]
## Using SQL Hint function a little complex and having a risk. 
code like:
```
Connection conn = null;
Statement stat = null;
try {
	conn = ds.getConnection(); 
	stat = conn.createStatement();
	stat.execute("set readwrite_splitting hint source=write");
	String sql = "select * from test";
	ResultSet rs = stat.executeQuery(sql);
	if(rs.next()){
		System.out.println("data");
	}else{
		System.out.println("no data");
	}
} catch (Exception e) {
	e.printStackTrace();
} finally {
	if(stat != null){
		try {
			stat.execute("clear readwrite_splitting hint;");
		} catch (Exception e) {
			e.printStackTrace();
		}
		try {
			stat.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	if(conn != null){
		try {
			conn.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```
The whole process is not atomic, there is a risk the hint tag never remove from ThreadLocal in proxy.
How about merging into one SQL?
For example: /\* set readwrite_splitting hint source=write \*/select * from test/\* clear readwrite_splitting hint \*/.
How about remove clear readwrite_splitting hint?
I think 'clear readwrite_splitting hint' is unnecessary, auto remove hint tag after executing sql.

**Comment by strongduanmu** [comment]
Hi @lwclover, thank you for your suggestion. We have already provide sql hint feature in master branch. You can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E5%BC%BA%E5%88%B6%E4%B8%BB%E5%BA%93%E8%B7%AF%E7%94%B1) for more detailed information. 

```sql
/* ShardingSphere hint: writeRouteOnly=true */
SELECT * FROM t_order;
```

**Comment by lwclover** [comment]
> Hi @lwclover, thank you for your suggestion. We have already provide sql hint feature in master branch. You can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E5%BC%BA%E5%88%B6%E4%B8%BB%E5%BA%93%E8%B7%AF%E7%94%B1) for more detailed information.
> 
> ```sql
> /* ShardingSphere hint: writeRouteOnly=true */
> SELECT * FROM t_order;
> ```

I am using shardingsphere proxy,not  shardingsphere jdbc.

**Comment by strongduanmu** [comment]
@lwclover Proxy can also support this feature.

**Comment by lwclover** [comment]
> @lwclover Proxy can also support this feature.
proxy props config below:
sql-show: true
proxy-hint-enabled: true
sql-comment-parse-enabled: true

executing sql '/* ShardingSphere hint: writeRouteOnly=true */ select * from test', there is no effect. 
Where did I configure it wrong?

**Comment by strongduanmu** [comment]
> 

@lwclover Which version are you using? Is it possible to provide the log information printed by sql-show?

**Comment by lwclover** [comment]
> > 
> 
> @lwclover Which version are you using? Is it possible to provide the log information printed by sql-show?

proxy 5.0.0.
TextProtocolBackendHandlerFactory.newInstance() method first line:
`
String trimSQL = SQLUtil.trimComment(sql);
`

**Comment by strongduanmu** [comment]
@lwclover Please try the latest master branch, because this is a new feature.

**Comment by lwclover** [comment]
> @lwclover Please try the latest master branch, because this is a new feature.

the latest branch has the feature, thank you

**Comment by lwclover** [comment]
> @lwclover Please try the latest master branch, because this is a new feature.

And how

**Comment by lwclover** [comment]
The whole process is not atomic, there is a risk the hint tag never remove from ThreadLocal in proxy.

**Comment by tuichenchuxin** [comment]
@lwclover If you use SQL hint like `/* ShardingSphere hint: writeRouteOnly=true */ select * from test`,
This way we didn't use HintManager at all. So, there is no risk about threadLocal.

**Comment by lwclover** [comment]
> @lwclover If you use SQL hint like `/* ShardingSphere hint: writeRouteOnly=true */ select * from test`, This way we didn't use HintManager at all. So, there is no risk about threadLocal.

You are right.

By the way, I am using proxy 5.0.0, If I want to use comment hint feature, Which commits do I need to merge?

**Comment by tuichenchuxin** [comment]
@lwclover You can refer to [this](https://github.com/apache/shardingsphere/issues/13771)
5.1 will be released soon.

**Comment by lwclover** [comment]
> @lwclover You can refer to [this](https://github.com/apache/shardingsphere/issues/13771) 5.1 will be released soon.

thanks
