### ISSUE TITLE
For example, I have an activity table that stores the activities of each period, so the content of each period of my activities should correspond to an activity detail table. I hope to achieve this, but now I'm stuck here and I need help.

### ISSUE THREAD

**Issue by dragonorant** [apache/shardingsphere#14705]
I want to do sharding on another table according to the primary key of a table. What should I do?

```xml
            <!-- https://mvnrepository.com/artifact/org.apache.shardingsphere/sharding-jdbc-spring-boot-starter -->
            <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
                <version>5.0.0</version>
            </dependency>
```

For example, I have an activity table that stores the activities of each period, so the content of each period of my activities should correspond to an activity detail table. I hope to achieve this, but now I'm stuck here and I need help.

**Comment by tuichenchuxin** [comment]
Maybe `bindTables` can help.
https://shardingsphere.apache.org/document/current/en/features/sharding/concept/table/#binding-table

**Comment by terrymanu** [comment]
Closed because of no response for long time.
