### ISSUE TITLE
There are 1000+ tables in my sub-database and sub-tables, do you support it? I use jdbc mode

### ISSUE THREAD

**Issue by goudai** [apache/shardingsphere#14702]
### There are 1000+ tables in my sub-database and sub-tables, do you support it? I use jdbc mode

**Comment by RaigorJiang** [comment]
Hi @goudai 
You can have a try.
Too many tables may cause the startup time to be longer, and there is no problem in running.

**Comment by linghengqian** [comment]
I tried hosting 1800+ tables and at least the data sharding function was fine.

**Comment by terrymanu** [comment]
Closed because of no response for long time.
