### ISSUE TITLE
Show error message when altering sharding configuration if scaling is not enabled

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14719]
## Feature Request
Currently, if scaling is not enabled, alter sharding configuration will take effect immediately, e.g. `ALTER SHARDING ALGORITHM`, `ALTER SHARDING TABLE RULE`. Though sharding configuration is altered immediately, but the underlying data is not scaled, in fact it cause issue. So we'll improve it.

### Is your feature request related to a problem?
Yes

### Describe the feature you would like.
If scaling is not enabled, show error message to user when altering sharding configuration.

**Comment by sandynz** [comment]
Refer to following java classes methods for more details:
- RuleDefinitionBackendHandler.execute
- RuleAlteredJobWorker.isOnRuleAlteredActionEnabled

Refer to [Sharding Rule Definition DistSQL]( https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/ ) for more details.

**Comment by ReyYang** [comment]
can i take it?,Thanks

**Comment by sandynz** [comment]
> can i take it?,Thanks

Welcome. Assigned to you.
