### ISSUE TITLE
Add more unit test for MetaDataRefresher

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14727]
Hi, community:

This issue is to add more unit tests for the MetaDataRefresher class. Welcome to claim them.

The specific subtasks are as follows:

- [ ]  Add unit test for AlterIndexStatementSchemaRefresher#refresh
- [ ]  Add unit test for AlterTableStatementSchemaRefresher#refresh
- [ ]  Add unit test for CreateIndexStatementSchemaRefresher#refresh
- [ ]  Add unit test for CreateTableStatementSchemaRefresher#refresh
- [ ]  Add unit test for CreateViewStatementSchemaRefresher#refresh
- [ ]  Add unit test for DropIndexStatementSchemaRefresher#refresh
- [ ]  Add unit test for DropTableStatementSchemaRefresher#refresh
- [ ]  Add unit test for DropViewStatementSchemaRefresher#refresh
- [ ]  Add unit test for RenameTableStatementSchemaRefresher#refresh

Through this issue, you can understand the process of participating in Apache ShardingSphere, and be familiar with sharding meta data.

**Comment by menghaoranss** [comment]
duplicate with #14083

**Comment by strongduanmu** [comment]
@menghaoranss Thank you.
