### ISSUE TITLE
Every scaling job should only run on one proxy node in proxy cluster

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14720]
### Is your feature request related to a problem?
Yes

### Describe the feature you would like.
Currently, if we start scaling job in proxy cluster, then it might cause issue. Since scaling job is in register center, and it will notify every proxy node in cluster and every proxy node will start scaling job.

I found exception before. It's necessary to test it more and fix it if necessary.

**Comment by ReyYang** [comment]
can i handle it? thanks

**Comment by sandynz** [comment]
It's already completed when another feature is implemented, so it's not necessary to do it any more.
