### ISSUE TITLE
Only one scaling job could be executed at the same time for one schema

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14722]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
In case of there're several scaling jobs are created that belong to the same schema, they will run concurrently, it might cause issue. So it's better to add some limitation:
1. Make sure there's only one scaling job is running if there're seveval scaling jobs that belong to the same schema.
2. Validate metadata, if target metadata is old than current enabled one, then it should not be executed. (It will be done after metadata multi-version is completed, not in this feature request.)

**Comment by ReyYang** [comment]
can i take it?,Thanks
