### ISSUE TITLE
Support broadcast table in scaling job

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#14721]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
From scaling code, looks broadcast table is not handled.

**Comment by ReyYang** [comment]
can i take it? thanks

**Comment by TeslaCN** [comment]
Hi @sandynz @ReyYang 
Any update here? Could we finish this in 5.1.1?

**Comment by sandynz** [comment]
> Hi @sandynz @ReyYang Any update here? Could we finish this in 5.1.1?

It depends on  #15532, I'll move it to 5.1.2 for now.
