### ISSUE TITLE
Add more unit test for ShardingRenameTableStatementValidator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14726]
Hi, community:

This issue is to add more unit tests for the ShardingRenameTableStatementValidator class. Welcome to claim them.

The specific subtasks are as follows:

- [ ]  Add unit test for ShardingRenameTableStatementValidator#preValidate
- [ ]  Add unit test for ShardingRenameTableStatementValidator#postValidate

Through this issue, you can understand the process of participating in Apache ShardingSphere, and be familiar with sharding validate.

**Comment by homeway88** [comment]
I am going to do these tasks, can you assign it to me ? @strongduanmu

**Comment by strongduanmu** [comment]
@homeway88 Welcome, I will assign this issue to you.
