### ISSUE TITLE
Hello, why can't version 5.0.0 support SQL batch insert or update?

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#14731]
Hello, why can't version 5.0.0 support SQL batch insert or update?

**Comment by strongduanmu** [comment]
@carlyin0801 Can you explain this issue in detail?

**Comment by carlyin0801** [comment]
such as:
INSERT INTO table ( "clo1", "col2", "col3", "col4", "col5" )
VALUES
( 1, 10, NULL, '2021-12-19 13:38:35', 'xxx'),
( 2, 11, NULL, '2021-12-19 15:05:13', 'xxx'),
( 3, 12, NULL, '2021-12-19 15:05:13', 'xxx'),
( 4, 13, NULL, '2021-12-19 15:05:13', 'xxx');

**Comment by strongduanmu** [comment]
@carlyin0801 If you have any problem, you can submit a issue according to the bug template.

**Comment by hipopular** [comment]
Insert statement does not support sharding table routing to multiple data nodes.\n### The error may exist
The error occur
red while setting parameters\n### SQL: insert into `mer_batch_321566` ( UID, CINEMA_UID, CINEMA_NAME, MER_UID, SKU_UID, SKU_CODE, UNIT_UID, UNIT_NAME, LEVEL, DEL_FLAG, CREATE_TIME, TENANT_ID ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '32
1566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '
321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
 '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?,
 ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?
, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?,
 ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?
, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?,
 ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?,
?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' ) , ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '321566' )

**Comment by terrymanu** [comment]
Closed because of no response for long time.
