### ISSUE TITLE
proxy兼容 IDEA DataGrid 数据库编辑器

### ISSUE THREAD

**Issue by hywr** [apache/shardingsphere#14734]
目前的版本(5.0.0)，MySql采用idea的数据库编辑器时会有以下两个问题：

1. 不选数据库的情况下无法列出数据库，并报错：[3D000][1046] No database selected.
2. 已选数据库的情况下无法列出表，并报错：[C1997][1997] Runtime exception: [unsupported table: `tables`]
辛苦大佬们改进一波

图:
![alt 未选图片时](https://pic.aaxp.cn/zxs-ks/unselected.png)
![alt 已选图片时](https://pic.aaxp.cn/zxs-ks/selected.png)

**Comment by menghaoranss** [comment]
@hywr For English only.

**Comment by hywr** [comment]
Ok,I see.View this Issue #14740 please
