### ISSUE TITLE
'Proxy project' uses 'READWRITE_SPLITTING' plug-in. The master database shouldn't be used under read-only transactions

### ISSUE THREAD

**Issue by hywr** [apache/shardingsphere#14741]
My version is:Sharding Sphere Proxy 5.0.0

Proxy project uses 'READWRITE_SPLITTING' plug-in. Under read-only transactions, the slave database should be used instead of the master database.

**Comment by TeslaCN** [comment]
The ShardingSphere-Proxy doesn't support read only transaction yet.

**Comment by jingshanglu** [comment]
@hywr when use read-only transaction, why route to master database?

**Comment by jingshanglu** [comment]
@hywr Maybe it has been fixed by #14983 .

**Comment by TeslaCN** [comment]
Set transaction read only has supported in later version. Please upgrade to latest version.
