### ISSUE TITLE
It is recommended to improve the configuration item document

### ISSUE THREAD

**Issue by hesixian123** [apache/shardingsphere#14755]
In the process of using, I found that many configuration items are not explained in detailed documents, especially between versions. Configuration items vary greatly, and there are no detailed configuration documents, which is very inconvenient to use. I hope the developer team can improve the document. This is a good project. Thank you.

**Comment by CrackerSuperior** [comment]
Can you be more specific? For example, the configuration you most want to know now.

**Comment by terrymanu** [comment]
No response for long time, I just close it
