### ISSUE TITLE
An error is reported when PostgreSQL money type queries large numbers

### ISSUE THREAD

**Issue by ReyYang** [apache/shardingsphere#14769]
### Which version of ShardingSphere did you use?
master branch
PostgreSQL 14
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
return correct result
### Actual behavior
return error
### Reason analyze (If you can)
The money field in PostgreSQL is detected with ’ , ‘
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、create table
``` sql
create table table_mix
(
    id       bigint primary key ,
    shard_id bigint not null,
    t_money  money  null
);
```
2、insert datas
```sql
insert into table_mix (id, shard_id, t_money)
values (1, 2, 9999999);
```
3、error
```shell
sharding_db=> select * from table_mix;
ERROR:  不良的类型值 double : 9,999,999.00
```

**Comment by ReyYang** [comment]
Using psql query returns normal
```shell
demo_ds_0=# select * from table_mix;
 id | shard_id |    t_money
----+----------+---------------
  6 |        6 | $9,999,999.00
(1 row)
```

**Comment by tuichenchuxin** [comment]
I want to investigate this issue.

**Comment by tuichenchuxin** [comment]
@ReyYang I found this issue is because of postgresql jdbc bug.
Avoid to use money type. And postgresql jdbc seems no plan to fix this.
refer to [this](https://github.com/pgjdbc/pgjdbc/issues/1835)
