### ISSUE TITLE
subquery as column Bug

### ISSUE THREAD

**Issue by LittlePluumLYY** [apache/shardingsphere#14773]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Example Sql:
    select a.col,(select b.col from b where b.aid=a.bid) from a;
Expect above sql execute correctly in same database
### Actual behavior
sqlParser recognized the 'a' in 'a.bid' in subquery as logical table when above sql been parsed, produced a SimpleTableSegment 'a' not exists.
when some place like GroupByMemoryMergedResult.getValueCaseSensitiveFromTables lookup the SelectStatementContext.getAllTables, maybe produce NullPointerException.
### Reason analyze (If you can)
sqlParse do not linked the table or table alias between subquery and outer query.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![lQLPDhsN94kTOEHNAe_NA8uwhqkzCPRQkpgB545-sgB3AA_971_495](https://user-images.githubusercontent.com/13850854/149488234-cc94756c-a347-4c50-8998-f5206ee6f262.png)

**Comment by tuichenchuxin** [comment]
I want to investigate this issue.

**Comment by tuichenchuxin** [comment]
Can you show me a demo to try or give me your config.
I can't reproduce it.

**Comment by tuichenchuxin** [comment]
Closed due to no reply for a long time.

**Comment by zhaozhentao** [comment]
i have the same problem
