### ISSUE TITLE
Add test case for ShowAuthorityRuleExecutor

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14805]
### Background
ShowAuthorityRuleExecutor is the executor for DistSQL `SHOW AUTHORITY RULE`.
Document: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/

### How to
Refer to the test case for `ShowTransactionRuleExecutor `: [ShowTransactionRuleExecutorTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/common/show/ShowTransactionRuleExecutorTest.java).

**Comment by LeeGuoPing** [comment]
I want to do it

**Comment by RaigorJiang** [comment]
@LeeGuoPing  Welcome!
