### ISSUE TITLE
Add test case for ShowSQLParserRuleExecutor 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14806]
### Background
ShowAuthorityRuleExecutor is the executor for DistSQL `SHOW SQL_PARSER RULE`.
Document: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/

### How to
Refer to the test case for `ShowTransactionRuleExecutor` : [ShowTransactionRuleExecutorTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/text/distsql/ral/common/show/ShowTransactionRuleExecutorTest.java).

**Comment by Liangda-w** [comment]
Hi, I would like to take this issue:)

**Comment by RaigorJiang** [comment]
Hi @Liangda-w , welcome!
