### ISSUE TITLE
Add new DistSQL to export schema configuration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14807]
Hi community,

starting from version 5.0.0, DistSQL provides many syntaxes to help users query resources and rule configuration, such as

- SHOW SCHEMA RESOURCES
- SHOW SHARDING TABLE RULES
- SHOW SHARDING ALGORITHMS
- SHOW READWRITE_SPLITTING RULES
- ...

However, if a user wants to obtain the complete configuration of a schema through DistSQL, it will be more difficult.

On the other hand, there are users who want to define rules via DistSQL and export them as YAML. On the contrary, there are also users who want to convert the existing YAML files into DistSQL statements, so as to completely get rid of the constraints of configuration files.

Therefore, I propose to design a series of new DistSQL syntax to help users achieve the above functions.

Among them, the configuration export is a little easier, and we can start with this.

### Proposal

For reference, I considered the following syntax:

```sql
EXPORT SCHEMA (CONFIGURATION|CONFIG) [FROM schemaName] [, FILE="filePath"]
````

When the user inputs `EXPORT SCHEMA CONIFG`, print out all the resources and rule configurations in the schema (organized in YAML text format);

When the user inputs `EXPORT SCHEMA CONIFG, file="/Users/foo/config-sharding.yaml"`, write the resources and rule configurations in the schema to the target YAML file. (The permission of Proxy to write files needs to be guaranteed by the user, otherwise an exception will be thrown)
\
\
The above is just a preliminary idea, any suggestions are welcome.

**Comment by totalo** [comment]
Maybe add a type? For example, sharding, readwrite-splitting...

**Comment by yx9o** [comment]
I want to try.

**Comment by RaigorJiang** [comment]
> Maybe add a type? For example, sharding, readwrite-splitting...

Hi @totalo , Thanks for your suggestion, what is the effect?  Export only one rule's configuration?

**Comment by RaigorJiang** [comment]
> I want to try.

Hi @yx9o ,
Thanks for your attention, this issue may need more discussion, but you can do research first.

**Comment by totalo** [comment]
> > Maybe add a type? For example, sharding, readwrite-splitting...
> 
> Hi @totalo , Thanks for your suggestion, what is the effect? Export only one rule's configuration?

Yes. I think it might be possible to make an optional? If I configure too many rules, I just want to check one of my rule configuration.

**Comment by RaigorJiang** [comment]
> Yes. I think it might be possible to make an optional? If I configure too many rules, I just want to check one of my rule configuration.

It can be considered, but the syntax and keywords will not be easy to define. （configuration includes resources and rules）.

**Comment by totalo** [comment]
> > Yes. I think it might be possible to make an optional? If I configure too many rules, I just want to check one of my rule configuration.
> 
> It can be considered, but the syntax and keywords will not be easy to define. （configuration includes resources and rules）.

How about `EXPORT SCHEMA typeOption? CONIFG`, we can use `ctx.typeOption.getText()` to get the type.

**Comment by RaigorJiang** [comment]
If it's just sharding, then `RULE` is more suitable than `CONFIG`.
But again this would be very similar to `SHOW SHARDING TABLE RULE`.

I think `SCHEMA CONFIG` must includes all RESOURCES and RULES,
If you want to expand optionals, then `EXPORT SHARDING TABLE RULE` would be more accurate.

**Comment by yx9o** [comment]
`EXPORT SCHEMA CONIFG, file="/Users/foo/config-sharding.yaml"` Does this case include printing.

**Comment by RaigorJiang** [comment]
I don't think it's needed, just return the operation success?

**Comment by totalo** [comment]
> If it's just sharding, then `RULE` is more suitable than `CONFIG`. But again this would be very similar to `SHOW SHARDING TABLE RULE`.
> 
> I think `SCHEMA CONFIG` must includes all RESOURCES and RULES, If you want to expand optionals, then `EXPORT SHARDING TABLE RULE` would be more accurate.

All right!

**Comment by RaigorJiang** [comment]
Hi @yx9o 
Let's think about how to implement the `import` syntax. Users can input YAML content through SQL or provide a file path.

**Comment by yx9o** [comment]
> Hi @yx9o Let's think about how to implement the `import` syntax. Users can input YAML content through SQL or provide a file path.

I think the file import way is used more.

**Comment by RaigorJiang** [comment]
> I think the file import way is used more.

Yes, I think so.

**Comment by RaigorJiang** [comment]
Hi  @isHuangXin ,
this issue has been completed, we will create a new issue for the GSoC project and look forward to your participation.

**Comment by isHuangXin** [comment]
> Hi @isHuangXin , this issue has been completed, we will create a new issue for the GSoC project and look forward to your participation.

OK. I will try my best to finish the GSoC project.

**Comment by isHuangXin** [comment]
> OK. I will try my best to finish the GSoC project.
Hi, @RaigorJiang.
I'm very confused. Is it me to create an issue about the GSoC project?
Or you create an issue about GSoC and I complete the solution idea.

**Comment by RaigorJiang** [comment]
> I'm very confused. Is it me to create an issue about the GSoC project?
> Or you create an issue about GSoC and I complete the solution idea.

@isHuangXin 
The new issue can of course be created by you if you wish.
