### ISSUE TITLE
the documents of the XA Narayana transaction type, including compilation, packaging, and usage, are not covered.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#14816]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
the documents of the XA Narayana transaction type, including compilation, packaging, and usage, are covered.
### Actual behavior
the documents of the XA Narayana transaction type, including compilation, packaging, and usage, are not covered.

**Comment by userkdg** [comment]
shardingsphere using spi classloader, you need copy ```Narayana|Bitronix``` jars to proxy ``` ext-lib/ ```

**Comment by terrymanu** [comment]
Closed because of no response for long time.
