### ISSUE TITLE
app using xa [atomikos] transaction, throw Occasional error

### ISSUE THREAD

**Issue by userkdg** [apache/shardingsphere#14826]
### Which version of ShardingSphere did you use?
5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior
no Occasional error

how to choose xa manager , which is release ? Atomikos 、Bitronix 、Narayana

### Actual behavior
Occasional on app
eg:
- error1: atomikos occasional eslint error.
![image](https://user-images.githubusercontent.com/21057449/149726660-ac2576e1-ca9e-4973-9eae-1e863ca50571.png)

- error2: xa set global transaction
<img width="1112" alt="d9d061ea-e1c8-471b-8d63-d8f37e9abaf6" src="https://user-images.githubusercontent.com/21057449/149726696-8e0cae5d-35a9-498c-baa9-90bc6ae9f1c1.png">

### Reason analyze (If you can)
no.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
props:
``` 
- !TRANSACTION
  defaultType: XA
  providerType: Atomikos

```
- simple sql: SELECT count(0) FROM ec_oms_retention_product_strategy WHERE del_flag = 0

**Comment by RaigorJiang** [comment]
Hi @userkdg 
Is your problem still there? Can it be reproduced?

**Comment by terrymanu** [comment]
Closed because of no response for long time.
