### ISSUE TITLE
how to set complex algorithm

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#14838]
shardingsphere version 5.0.0
how to set complex algorithm for shardingtable in yaml?

**Comment by RaigorJiang** [comment]
@xsong123
Please refer to:
https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/resources/yaml/sharding-rule.yaml

**Comment by terrymanu** [comment]
Closed because of no response for long time.
