### ISSUE TITLE
why MetaDataContexts.getLock() always return Optional.empty() ?

### ISSUE THREAD

**Issue by agzou** [apache/shardingsphere#14844]
why MetaDataContexts.getLock() always return Optional.empty() ?
> source code
https://github.com/apache/shardingsphere/blob/5.0.0/shardingsphere-mode/shardingsphere-mode-core/src/main/java/org/apache/shardingsphere/mode/metadata/MetaDataContexts.java

**Comment by RaigorJiang** [comment]
This method is not currently used, it should be a reserved interface.

**Comment by terrymanu** [comment]
Closed because of no response for long time.
