### ISSUE TITLE
read-write-splitting with spring boot and jpa never reach to read-datasource

### ISSUE THREAD

**Issue by tuyendev** [apache/shardingsphere#14858]
### Which version of ShardingSphere did you use? 

- **5.0.0**

### Which project did you use? 

- **ShardingSphere-JDBC**

### Expected behavior
- Read behavior never swith to slave datasources even ROUND_ROBIN or RANDOM
### Actual behavior
- Read behavior CAN NOT reach to read datasources (slave)
`SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty, window=Optional.empty)`
`Actual SQL: write-ds ::: select user0_.id as id1_0_, user0_.email as email2_0_ from users user0_`
### Reason analyze (If you can)
- Not yet
### Steps to reproduce the behavior
- I was following **the official example of shardingshere**. I was confused a bit when I turn off write datasource (master), the read process is dead and can never recover back. I do turn on sql-show optional and I can see that the reader only read the master datasource

### Example codes for reproduce this issue (such as a github link).
[SRC](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-namespace-jpa-example/src/main/java/org/apache/shardingsphere/example/readwrite/splitting/spring/namespace)

#### UPDATE 1

I found a weird behaviour ( not sure about that  ) in **ReadwriteSplittingDataSourceRouter.java**

`    private boolean isPrimaryRoute(final SQLStatement sqlStatement) {
        return containsLockSegment(sqlStatement) || !(sqlStatement instanceof SelectStatement) || HintManager.isWriteRouteOnly() || TransactionHolder.isTransaction();
    }`

The **TransactionHolder.isTransaction()** was **true**, i even don't set any transaction configuration.  
It worked in previous version (4.1.1). I only cause problem with this version (5.0.0)

#### UPDATE 2

In class **ShardingSphereConnection.java**

```
    private void processLocalTransaction() throws SQLException {
        connectionManager.setAutoCommit(autoCommit);
        if (!autoCommit) {
            TransactionHolder.setInTransaction();
        }
    }
    
```

I think this line is the root cause. I tried to **select** function, this should not set in the transaction. I guess

**Comment by zjcnb** [comment]
@tuyendev Thanks for your feedback. I will adjust readwrite-splitting configuration and check your question.

**Comment by tuyendev** [comment]
@zjcnb I don't think your configuration is wrong.
I found a weird behaviour ( not sure about that  ) in **ReadwriteSplittingDataSourceRouter.java**

`    private boolean isPrimaryRoute(final SQLStatement sqlStatement) {
        return containsLockSegment(sqlStatement) || !(sqlStatement instanceof SelectStatement) || HintManager.isWriteRouteOnly() || TransactionHolder.isTransaction();
    }`

The **TransactionHolder.isTransaction()** was **true**, i even don't set any transaction configuration.  
It worked in previous version (4.1.1). I only cause problem with this version

**Comment by tuyendev** [comment]
@zjcnb I don't think your configuration is wrong.

Please check my update

**Comment by zjcnb** [comment]
> @zjcnb I don't think your configuration is wrong.
> 
> Please check my update

OK, I will check.

**Comment by zjcnb** [comment]
@tuyendev Hi, this reason is `processSuccess()` method add @Transactional annotation. the autoCommit set as false.  Maybe this readwrite-splitting example are some problem, the insert and query should be separated and not in a transaction.

**Comment by tuyendev** [comment]
Agreed @zjcnb . Should I report this issue as bug or waiting for the your example.

**Comment by zjcnb** [comment]
I will tell you if this issue are fixed，If you interest of this，you can resolve it too.



发自我的iPhone


------------------ Original ------------------
From: Tea ***@***.***&gt;
Date: Tue,Jan 18,2022 7:06 PM
To: apache/shardingsphere ***@***.***&gt;
Cc: zhaojinchao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/shardingsphere] read-write-splitting with spring boot andjpa never reach to read-datasource (Issue #14858)

**Comment by tuyendev** [comment]
@zjcnb thank you. I will try to fix the issue

**Comment by zjcnb** [comment]
> @zjcnb thank you. I will try to fix the issue

I will create a new issue and then you claim it.

**Comment by lsoimpe** [comment]
The same problem!!!

**Comment by sunzhen086** [comment]
me too

**Comment by lsoimpe** [comment]
一个bug既然4个月不能修复？

**Comment by zjcnb** [comment]
The readwrite example have `@Transactional` annotation. If you read data from slave replica data source in transaction, you can remove `@Transactional` annotation or set loadBalancers type are `FIXED_REPLICA_ROUND_ROBIN`, i will close this issue. If you have any questions, please submit a new issue
