### ISSUE TITLE
[ Example ] Readwrite-splitting example not route read data source.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#14868]
Hi community,

refer to: #14858 

```
    @Override
    @Transactional
    public void processSuccess() throws SQLException {
        System.out.println("-------------- Process Success Begin ---------------");
        List<Long> orderIds = insertData();
        printData();
        deleteData(orderIds);
        printData();
        System.out.println("-------------- Process Success Finish --------------");
    }
```

Insert and query should split when use readwrite-splitting feature. Because insert and query in a transaction, lead to read always request write data source.

**Comment by zjcnb** [comment]
@tuyendev Can you solve it?

**Comment by tuyendev** [comment]
Now it worked with the latest version. Could you close the issue ?

**Comment by 13612687938** [comment]
with the latest version 5.1.0 (5.0.0 is also), my method just contain query without any insert(or update 、 delete) but always request write data source.

**Comment by tuyendev** [comment]
My bad! I checked, still buggy

**Comment by zjcnb** [comment]
> My bad! I checked, still buggy

Yeah, The example project are refactoring, I will tell you when it finished.
,

**Comment by zjcnb** [comment]
The example are in transaction. If you route slave node, you can set TRANSACTION_RANDOM for load balance algorithm. So, i close this issue.
