### ISSUE TITLE
What are the hard advantages of shardingsphere vs tidb ? Why choose `shardingsphere` if I can use `tidb`

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#14888]
What are the hard advantages of `shardingsphere` vs [tidb](https://docs.pingcap.com/zh/tidb/v4.0/) ? Why choose `shardingsphere` if I can use [tidb](https://docs.pingcap.com/zh/tidb/v4.0/)

**Comment by terrymanu** [comment]
ShardingSphere is for database plus, not a database. It focus on enhancement of original databases.

**Comment by wl4g** [comment]
Uh huh, I want to ask why I choose shardingsphere to solve the problem of massive OLTP data storage and query? Tidb is also compatible with MySQL protocol and has no complex slicing logic, I have been actively using shardingsphere, but my reason tells me that tidb will be better?

**Comment by wl4g** [comment]
@terrymanu

**Comment by terrymanu** [comment]
If you use ShardingSphere as a database, there are lots of dimension need to be consider, for example: stable, latency, TPS of TPCC etc. You may try to test them if you are interested.
But I still have to say ShardingSphere is different with database, it is database plus. There are lots of features in ShardingSphere, for example: PostgreSQL supported, encrypt, etc...

**Comment by wl4g** [comment]
OK, thanks for your patience answer. Like many people, I am confused about the problem: how to solve automatic scaling elegantly and simply? I think since many other shard-nothing databases are auto-scaling, how can shardingsphere be done automatically? or must manually exec?

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/features/scaling/
