### ISSUE TITLE
sharing-proxy 中文问号

### ISSUE THREAD

**Issue by wyxabd** [apache/shardingsphere#14894]
当数据库内容为中文时 或者sql中带有中文时显示问号

**Comment by CrackerSuperior** [comment]
Can you show me your config-*.yaml configuration?

**Comment by wyxabd** [comment]
At 2022-01-19 15:23:59, "CrackerSuperior" ***@***.***> wrote:

Can you show me your config-*.yaml configuration?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
