### ISSUE TITLE
Add more unit test for EncryptSQLRewriteContextDecorator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14908]
Hi, community:

This issue is to add more unit tests for the EncryptSQLRewriteContextDecorator class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for EncryptSQLRewriteContextDecorator#decorate
- [ ] Add unit test for EncryptSQLRewriteContextDecorator#getOrder
- [ ] Add unit test for EncryptSQLRewriteContextDecorator#getTypeClass

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by strongduanmu** [comment]
Welcome @LeeGuoPing, I just assign this issue to you.
