### ISSUE TITLE
Add more unit test for EncryptParameterRewriterBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14909]
Hi, community:

This issue is to add more unit tests for the EncryptParameterRewriterBuilder class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for EncryptParameterRewriterBuilder#getParameterRewriters

**Comment by zzs52** [comment]
Can i try?

**Comment by strongduanmu** [comment]
@zzs52 Welcome, I will assign this issue to you.
