### ISSUE TITLE
Add more unit test for ShardingTokenGenerateBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14911]
Hi, community:

This issue is to add more unit tests for the ShardingTokenGenerateBuilder class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for ShardingTokenGenerateBuilder#getSQLTokenGenerators

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.
