### ISSUE TITLE
Add more unit test for DefaultTokenGeneratorBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14913]
Hi, community:

This issue is to add more unit tests for the DefaultTokenGeneratorBuilder class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for DefaultTokenGeneratorBuilder#getSQLTokenGenerators

**Comment by NOLouser** [comment]
Maybe I can try.

**Comment by strongduanmu** [comment]
@NOLouser Welcome, I will assign this issue to you.
