### ISSUE TITLE
Add more unit test for SQLTokenGenerators

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14912]
Hi, community:

This issue is to add more unit tests for the SQLTokenGenerators class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for SQLTokenGenerators#addAll
- [ ] Add unit test for SQLTokenGenerators#generateSQLTokens

**Comment by jiangtao69039** [comment]
Is there a deadline?

**Comment by strongduanmu** [comment]
No, you can try this issue according to your time.

**Comment by jiangtao69039** [comment]
ok
