### ISSUE TITLE
Add more unit test for EncryptTokenGenerateBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14910]
Hi, community:

This issue is to add more unit tests for the EncryptTokenGenerateBuilder class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for EncryptTokenGenerateBuilder#getSQLTokenGenerators

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by yx9o** [comment]
@LeeGuoPing Welcome.
