### ISSUE TITLE
Adjust sample module names

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#14925]
The current sample module have deep hierarchy and the name is not make sense.

It is better to move them as flat hierarchy and rename follow by:

```
shardingsphere-${product-name}-sample
  ${feature}--${framework}?--${mode}--${transaction-type}`
```

for example: 

```
shardingsphere-jdbc-sample
  db-discovery--spring-boot-starter-jpa--cluster-zookeeper--xa-atomikos`
```

**Comment by totalo** [comment]
Please assign me and I will follow up.

**Comment by Swastyy** [comment]
Hi @terrymanu , in the PR #14940 how you changed so many files? Have you done it one by one
