### ISSUE TITLE
Official documentation webpage contains some error links

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#14935]
## Bug Report

the documentation page contains error link, it will rediect to 404 page when click.  [Here is error page](https://shardingsphere.apache.org/document/5.1.0/cn/user-manual/shardingsphere-jdbc/yaml-config/)
  
If the click on the left nav bar is correct.

![sss22](https://user-images.githubusercontent.com/20572131/150270295-6ba5f1a1-fa51-4635-8ab0-1f15614474b2.png)

**Comment by menghaoranss** [comment]
@jiangtao69039 thanks for you feedback, I will fix ASAP.
