### ISSUE TITLE
proxy can not run where java11 configed. please adapt it!

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#14941]
## Feature Request

**For English only**, other languages will not accept.
 java8 run ss-proxy is OK, but java11 raise Exception:

_OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a futu release.
**Unrecognized VM option 'UseFastAccessorMethods'**
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit
### Is your feature request related to a problem?
Yes, java11 can not directly run, I need delete the report java_vm args._

### Describe the feature you would like.
I want run ss-proxy in multi java version for perfermance test.so I want start.sh auto check java version for it's java_vm args.

**Comment by terrymanu** [comment]
@justbk2015 You have already analyze the reason, cloud you consider about submit a pull request to fix the issue?

**Comment by justbk2015** [comment]
> @justbk2015 You have already analyze the reason, cloud you consider about submit a pull request to fix the issue?

I will try it.

**Comment by linghengqian** [comment]
Thank you for your handling. I noticed that you only changed `start.sh`. Is it possible to change `start.bat` in another PR? This is related to https://community.sphere-ex.com/t/topic/313 .
