### ISSUE TITLE
Cound one disable some SQL in Sharding proxy for safety?

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#14964]
Cound one disable some SQL in Sharding proxy for safety?

**Comment by wl4g** [comment]
@WillemJiang @rfscholte @ke4qqq

**Comment by wl4g** [comment]
Can server.yaml authorization be configured?  If not, where do I start with my own development?

**Comment by RaigorJiang** [comment]
There is no such feature yet, do you want to disable a specific few SQLs or a certain type of SQL, such as DDL statements?

**Comment by wl4g** [comment]
Well, I have implements of: [https://github.com/wl4g/xcloud-shardingproxy/blob/1ab823b8bb78c33608dd2a94680b1727039249d2/xcloud-shardingproxy-starter/src/main/resources/example/server.yaml#L51](https://github.com/wl4g/xcloud-shardingproxy/blob/1ab823b8bb78c33608dd2a94680b1727039249d2/xcloud-shardingproxy-starter/src/main/resources/example/server.yaml#L51)

**Comment by wl4g** [comment]
Can you help me see any suggestions?

**Comment by RaigorJiang** [comment]
It's interesting to see your design from the configuration, but due to limited information, I can't give a valuable comment, as long as it can satisfy your business, it's good!

**Comment by terrymanu** [comment]
@wl4g Hi, any update?
