### ISSUE TITLE
when use ShardingSphere-JDBC readwrite-splitting,occur `java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@32660719 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.`

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#14975]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.1 Snapshot 
commit e963a135f887a1d3c05e1fac7c861f5536261d7e
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
work normally 
### Actual behavior
![image](https://user-images.githubusercontent.com/86462784/150481633-d219ca10-c5cc-40be-ab06-bf08bbce0ec5.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
 shardingsphere-rw.yaml
```
dataSources:
  write_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://IP:Prot/DB
    username: root
    password: 
    maximumPoolSize: 1024
    minimumIdle: 1024

props:

rules:
- !READWRITE_SPLITTING
  dataSources:
    ds_0:
      type: Static
      props:
        write-data-source-name: write_ds_0
        read-data-source-names: write_ds_0
### Example codes for reproduce this issue (such as a github link).

**Comment by strongduanmu** [comment]
@wsm12138 Thank you for your feedback, I will investigate this issue.
