### ISSUE TITLE
how to use stream query 

### ISSUE THREAD

**Issue by xsong123** [apache/shardingsphere#15000]
shardingsphere version 5.0.0
mysql version 5.7

how to set settings for stream query ?
now add setFetchSize for jdbc, but stream query don't work.

**Comment by yx9o** [comment]
Hi, can you provide more error information? Maybe you can try the master version, please refer to: https://github.com/apache/shardingsphere/issues/14827

**Comment by strongduanmu** [comment]
@xsong123 Can you provide your configuration? Or give an example?

**Comment by strongduanmu** [comment]
> Hi, can you provide more error information? Maybe you can try the master version, please refer to: #14827

Thank you for @yx9o, but the pr of this issue has been reverted because it caused an unexpected streaming query exception.

**Comment by strongduanmu** [comment]
If you use mysql database, you can try `preparedStatement.setFetchSize(Integer.MIN_VALUE);` to open stream query.

**Comment by xsong123** [comment]
> If you use mysql database, you can try `preparedStatement.setFetchSize(Integer.MIN_VALUE);` to open stream query.

i have used `preparedStatement.setFetchSize(Integer.MIN_VALUE);` , but don't work.
trace source, then found:
ConnectionMode connectionMode = maxConnectionsSizePerQuery < sqlUnits.size() ? ConnectionMode.CONNECTION_STRICTLY : ConnectionMode.MEMORY_STRICTLY;

`maxConnectionsSizePerQuery` and `sqlUnits.size()`  affect connectionMode .
![image](https://user-images.githubusercontent.com/19642484/150661940-884fc42c-bb07-4e97-9629-d1d15015fb8d.png)

**Comment by strongduanmu** [comment]
@xsong123 Yes, we can't use stream query when connection mode is `connection_strictly`.

**Comment by terrymanu** [comment]
Closed because of no response for long time.
