### ISSUE TITLE
proxy 5.0 not support row_number function  

### ISSUE THREAD

**Issue by asp1111** [apache/shardingsphere#15014]
mysql : 8.x
shardingsphere proxy : 5.0.0
i customize my shardingAlggorithm,it olny route to one datasource,but still not support row_number function  ,is that a bug ? or just not support? or i do anything wrong ?
![image](https://user-images.githubusercontent.com/13173179/150717142-aadb56bc-da84-4860-a03a-d12ac3f5f126.png)

**Comment by strongduanmu** [comment]
@asp1111 Can you provide your sharding configuration and exception info?

**Comment by asp1111** [comment]
![image](https://user-images.githubusercontent.com/13173179/150718467-5c5c45dc-f126-46da-87c1-03b43f86dffc.png)
![image](https://user-images.githubusercontent.com/13173179/150718486-c2e3aea1-4f01-41b7-b3af-0fdf5d36937b.png)
@strongduanmu

**Comment by strongduanmu** [comment]
@asp1111 What is the exception message? Also, what should I do to reproduce this problem.

**Comment by asp1111** [comment]
### here is exception message
![image](https://user-images.githubusercontent.com/13173179/150731377-6f1b9626-4f3d-42d1-b388-1ed149acf198.png)
### reproduce this problem
set up two database , create user table  

    CREATE TABLE `aiot_t_user` (
      `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
      `tenantId` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL ,
      `departmentId` bigint DEFAULT NULL ,
      `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL ,
      PRIMARY KEY (`id`) USING BTREE,
    ) ENGINE=InnoDB AUTO_INCREMENT=399 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

customize  shardingAlggorithm and run sql

    SELECT
	    id,
	    ROW_NUMBER() OVER ( PARTITION BY departmentId ORDER BY createTime DESC ) 
    FROM
	    aiot_t_user 
    WHERE
	    tenantId = "1004200"

**Comment by strongduanmu** [comment]
@asp1111 Thank you for your feedback, I will check this issue.

**Comment by strongduanmu** [comment]
@asp1111 Where is the createTime column in create table statement?

**Comment by asp1111** [comment]
i edit it : )

**Comment by strongduanmu** [comment]
Hi @asp1111, I have tested master branch, this exception has been fixed.

**Comment by asp1111** [comment]
that is great,thanks

**Comment by strongduanmu** [comment]
Fixed in master branch.
