### ISSUE TITLE
example is not standard in ShardingRawJavaConfigurationExample

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#15021]
## Bug Report

One example is not standardized.  It prints sql in console by default, but others will not.

I can submit a PR if need to modify here

### Which version of ShardingSphere did you use?

branch: master 
class Name: ShardingRawJavaConfigurationExample

### Expected behavior

![notprint](https://user-images.githubusercontent.com/20572131/150749347-d93f4c44-86a7-4461-9389-d7c7836efd31.png)

### Actual behavior

![print](https://user-images.githubusercontent.com/20572131/150749365-9d81ffb6-e579-4d67-8b98-1622acf68e11.png)

**Comment by jiangtao69039** [comment]
I can submit a PR if need to modify here.

**Comment by zjcnb** [comment]
Hi, this are test Stanalone mode. Did you modify the `sharding-databases.yaml` file?

**Comment by jiangtao69039** [comment]
No,I didn't change any files.

**Comment by zjcnb** [comment]
> No,I didn't change any files.

OK, i will check it. Hold on please.

**Comment by zjcnb** [comment]
![image](https://user-images.githubusercontent.com/33742097/150760454-f6f00522-ca2d-4556-9cb0-d716c1ee2e9f.png)

@jiangtao69039 I can't reproduce it. Can you delete .shardingsphere file? And run this method again.
![image](https://user-images.githubusercontent.com/33742097/150760955-5a5104b0-a8e8-4fb0-9718-b90c51191b40.png)

**Comment by jiangtao69039** [comment]
Sorry,is my problem.Thank you very much!
