### ISSUE TITLE
What does it mean that the 'err' percentage is 100% of 4.1.1 version in benchmark?

### ISSUE THREAD

**Issue by climy007** [apache/shardingsphere#15052]
Dear developer, 
I found that the err rate of sharding-jdbc in selecting option is always 100% rather than single route or full route. Does it mean that all selecting results got by sharding-jdbc are wrong?
The image shows that the benchmark of sharding-jdbc posted on official website
![image](https://user-images.githubusercontent.com/45785480/150933582-900b3572-d33f-44ba-99dc-a030672471e8.png)

**Comment by menghaoranss** [comment]
@climy007 hi, what's the link of this report ?

**Comment by taojintianxia** [comment]
@climy007  would you post the link here ?

**Comment by climy007** [comment]
> you
Okay. The link is here. It's an official benchmark.
https://shardingsphere.apache.org/benchmark/#/overview_detail/3

**Comment by climy007** [comment]
> menghaoranss
Okay. The link is here. It's an official benchmark.
https://shardingsphere.apache.org/benchmark/#/overview_detail/3

**Comment by climy007** [comment]
> @climy007 hi, what's the link of this report ?

> you
Okay. The link is here. It's an official benchmark.
https://shardingsphere.apache.org/benchmark/#/overview_detail/3

**Comment by climy007** [comment]
> @climy007 would you post the link here ?

Okay. The link is here. It's an official benchmark.
https://shardingsphere.apache.org/benchmark/#/overview_detail/3

**Comment by terrymanu** [comment]
The version 4.x is out of service, welcome to try version 5.x
