### ISSUE TITLE
Add unit test for InstanceContext

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#15051]

**Comment by csonezp** [comment]
I would like to contribute in this issue, please assign it to me

**Comment by menghaoranss** [comment]
> I would like to contribute in this issue, please assign it to me

@csonezp welcome on board

**Comment by csonezp** [comment]
@menghaoranss 

Hi，i have some doubts after reading the code.

InstanceContext#switchInstanceState:

`    private void switchInstanceState(final Collection<String> status) {
        state.switchState(StateType.CIRCUIT_BREAK, null != status && status.contains(StateType.CIRCUIT_BREAK.name()));
    }`

The effect of these codes is to put CIRCUIT_BREAK into StateContext#currentState when the `status` is contain CIRCUIT_BREAK, or run currentState.pop() when `status` not contain CIRCUIT_BREAK.

Does InstanceContext only pay attention to the state of CIRCUIT_BREAK ?  

When will method switchInstanceState be called ?

Thanks !

**Comment by menghaoranss** [comment]
@csonezp there are only `OK` and `CIRCUIT_BREAK` status for ShardingSphere now, when execute DistSQL `enable / disable instance ip=xxx,port=xxx` , the method switchInstanceState will be called. please refer to [DistSQL RAL](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/ral/)
