### ISSUE TITLE
Refactor YamlProxyConfigurationSwapperTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15061]
The test case YamlProxyConfigurationSwapperTest use lots of mock to build test data, it is too difficult to understand.

It is better to use yaml file to provide test data, just load yaml file in test case and assert swap.

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.
