### ISSUE TITLE
Hello, may I ask how shardingsphere ensures the data consistency in each partition database when inserting data into the broadcast table?

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#15071]
Hello, may I ask how shardingsphere ensures the data consistency in each partition database when inserting data into the broadcast table? Is it guaranteed by distributed transactions?

**Comment by RaigorJiang** [comment]
Hi @carlyin0801 
ShardingSphere support distributed transaction, and the default transaction type is `LOCAL`, you can refer to the document:
https://shardingsphere.apache.org/document/current/en/features/transaction/

**Comment by carlyin0801** [comment]
@RaigorJiang Thank you for your answer, you mean that if I do not actively configure to support distributed transactions, the data consistency of the broadcast table of each partition database cannot be guaranteed？

**Comment by RaigorJiang** [comment]
Yes, as the documentation describes, local transactions are not capable enough in high consistency and eventual consistency.

**Comment by terrymanu** [comment]
Closed because of no response for long time.
