### ISSUE TITLE
关于只分库部分表

### ISSUE THREAD

**Issue by sunny800629** [apache/shardingsphere#15073]
1、能否支持根据数据源名称获取连接并进行数据操作么？现在有一种使用场景是为：有几个数据库，每个数据库对应一个用户，需要根据用户获取数据源并进建表等操作，无需在每个数据库中都创建相同的表。
2、能够支持在统一数据库中，针对不同的用户创建以用户名称为前缀的表，并进行操作么？

**Comment by RaigorJiang** [comment]
Hi @sunny800629 
For ENGLISH only, please translate the issue.
