### ISSUE TITLE
Query about "like"

### ISSUE THREAD

**Issue by princess-yanyan** [apache/shardingsphere#15079]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

I known encryption not support 'like', but i want to ask for advice,if the encrypt column need to query with ‘like’ what shuld i do？if you have some advice

**Comment by strongduanmu** [comment]
@princess-yanyan There is a way to use substring encryption now, and then use the same way to split and encrypt the query field to support like queries.
