### ISSUE TITLE
biginteger = character varying ?

### ISSUE THREAD

**Issue by dissdic** [apache/shardingsphere#15084]
a table with id column which is primary key of this table.and the type of the primary key is bigInteger.
we use spring-jdbc as the frame for data interaction with PostgreSql.
when executing a sql in the form of "select ... from table where id  = ?" with the statement paramters present as "id ="123456""
then the executor of the shardingsphere PreparedStatement will throw the error:biginteger = character varying...
through i get what this mean,after changing the type of id column to varchar ,execution passed . but still can't figure out how to deal with it without changing the type of id column.
so what should i do with this error?

**Comment by terrymanu** [comment]
I just set it as `invalid` because of closed by author without any reason.
