### ISSUE TITLE
Micro-Refactoring Integration Testing.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#15089]
After a lot of efforts, the integration test now has a small success.

However, there are still some potential problems in integration testing, such as confusing file structure, code redundancy, lack of design mode, memory leaks, connection leaks, poor performance, and so on.

Therefore I consider I want to do some micro-refactoring of integration tests while finishing #9104.

Of course, my ability and time are limited, so I hope more people can help me to improve the integration test part.

I roughly sort out the list of tasks：
- [x] Completely replace docker-compose with testContainer startup.
- [x] More abstract testContainer and integrate test-related interfaces to make it more flexible.
- [x] Retail the lifecycle of container startup, check various leaks and repair the leak.
- [x] Sort out the residual problems of the governance module and pgsql module.
- [x] Continue to extend the functionality.

**Comment by menghaoranss** [comment]
@JiekerTime glad to see you again here, could you provide detailed plan or a task list to describe what you will do next.

**Comment by menghaoranss** [comment]
> @JiekerTime glad to see you again here, could you provide detailed plan or a task list to describe what you will do next.

or continue #9104 ?

**Comment by TeslaCN** [comment]
@soulasuna Could you please follow this issue.

**Comment by JiekerTime** [comment]
> @JiekerTime glad to see you again here, could you provide detailed plan or a task list to describe what you will do next.

I roughly sorted out the problem and will update the detailed issue according to the continuing task.
