### ISSUE TITLE
why cached the configuration file at folder "C:\Users\Administrator\.shardingsphere\metadata\logic_db"

### ISSUE THREAD

**Issue by patience00** [apache/shardingsphere#15132]
## Bug Report

I used Druid connection pool for the first time,and there is some error make the project can't start,
so I have modified the configuration file and changed connection pool to Hikari,
but shardingsphere-jdbc-core-spring-boot-starter still used the  cached configuration file

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0</version>
        </dependency>
### Expected behavior
use the  latest application.yml
### Actual behavior
project is still started with a cached configuration file 
### Reason analyze (If you can)
I don't think caching is necessary
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
as described above

**Comment by menghaoranss** [comment]
Please provide your yml configuration, the local file cache takes effect if you configure `Standalone` mode

**Comment by patience00** [comment]
> Please provide your yml configuration, the local file cache takes effect if you configure `Standalone` mode
yes,it is Standalone
thanks!
