### ISSUE TITLE
Add more unit test for EncryptContextBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15140]
Hi, community:

This issue is to add more unit tests for the EncryptContextBuilder class. Welcome to claim them.
After pr #15133 was merged, you can start this work.

The specific subtasks are as follows:

- [ ] Add unit test for EncryptContextBuilder#build

**Comment by zzs52** [comment]
Can i try?

**Comment by yx9o** [comment]
@zzs52 Welcome.

**Comment by strongduanmu** [comment]
Fixed by #15189.
