### ISSUE TITLE
Schema 'root' doesn't exist in ShardingSphere-Proxy 5.0

### ISSUE THREAD

**Issue by wyxabd** [apache/shardingsphere#15145]
use PostgreSQL
For example:：select * from “root”.pagemanage
ERROR:  Schema 'root' doesn't exist.

**Comment by RaigorJiang** [comment]
Hi @wyxabd 
ShardingSphere manages distributed databases and coordinates data through logical schemas. If you do not create a `root` schema in ShardingSphere, it does not exist.

**Comment by wyxabd** [comment]
root schema is existed,but show ERROR

**Comment by RaigorJiang** [comment]
Please provide your schema configuration.

**Comment by wyxabd** [comment]
schemaName: jdt

dataSources:
  primary_ds:
    url: jdbc:postgresql://10.25.108.163:5432/jdt
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  replica_ds_0:
    url: jdbc:postgresql://10.25.108.161:5432/jdt
    username: postgres
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
#  replica_ds_1:
#    url: jdbc:postgresql://127.0.0.1:5432/demo_replica_ds_1
#    username: postgres
#    password: postgres
#    connectionTimeoutMilliseconds: 30000
#    idleTimeoutMilliseconds: 60000
#    maxLifetimeMilliseconds: 1800000
#    maxPoolSize: 50
#    minPoolSize: 1
#
rules:
  - !READWRITE_SPLITTING
    dataSources:
      pr_ds:
        writeDataSourceName: primary_ds
        readDataSourceNames:
          - replica_ds_0
#        - replica_ds_1

**Comment by RaigorJiang** [comment]
> schemaName: jdt
> 
> dataSources: primary_ds: url: jdbc:postgresql://10.25.108.163:5432/jdt username: postgres password: 123456 

Hi @wyxabd 
From your configuration, the logic schema name is `jdt`, not root.
In ShardingSphere, users can not use pg schema in SQL, it shoud be logic schema.

**Comment by wyxabd** [comment]
use PostgreSQL 
jdt is DatabaseName
root is SchemaName

**Comment by RaigorJiang** [comment]
@wyxabd 
I understand what you mean, in PostgreSQL, database and schema have different meanings, but in ShardingSphere, database and schema both refer to logical database (or logic schema), which is somewhat different from using Postgres directly.

**Comment by RaigorJiang** [comment]
There is a related issue: https://github.com/apache/shardingsphere/issues/14004

**Comment by ZengYu1** [comment]
Hi, So how to access the schema of "root"

**Comment by ZengYu1** [comment]
@RaigorJiang Hi, So how to access the schema of "root"

**Comment by RaigorJiang** [comment]
@ZengYu1 Can't do it now, can only use public schema

**Comment by ZengYu1** [comment]
你好，已收到你的来信，谢谢

**Comment by ZengYu1** [comment]
你好，已收到你的来信，谢谢

**Comment by TeslaCN** [comment]
Schema supporting is improved in later version.

**Comment by ZengYu1** [comment]
你好，已收到你的来信，谢谢
