### ISSUE TITLE
No value specified for parameter

### ISSUE THREAD

**Issue by anonymous-lj** [apache/shardingsphere#15152]
<dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
      <version>5.0.0</version>
  </dependency>
ShardingSphere JDBC  pressure test abnormal 

sql：select * from api_wallet  where id = ?  for update

Caused by: java.sql.SQLException: No value specified for parameter 1
2022/1/28 下午2:47:40         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2022/1/28 下午2:47:40         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2022/1/28 下午2:47:40         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2022/1/28 下午2:47:40         at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:396)
2022/1/28 下午2:47:40         at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:322)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement$2.executeSQL(ShardingSpherePreparedStatement.java:318)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.parallelExecute(ExecutorEngine.java:97)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:82)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:49)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.executor.JDBCLockEngine.doExecute(JDBCLockEngine.java:116)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.executor.JDBCLockEngine.execute(JDBCLockEngine.java:93)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.executor.DriverJDBCExecutor.execute(DriverJDBCExecutor.java:127)
2022/1/28 下午2:47:40         at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:298)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.PreparedStatementProxy.lambda$execute$0(PreparedStatementProxy.java:55)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.exec.SelectForUpdateExecutor.doExecute(SelectForUpdateExecutor.java:91)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50)
2022/1/28 下午2:47:40         at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55)
2022/1/28 下午2:47:40         at jdk.internal.reflect.GeneratedMethodAccessor418.invoke(Unknown Source)
2022/1/28 下午2:47:40         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022/1/28 下午2:47:40         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2022/1/28 下午2:47:40         at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
2022/1/28 下午2:47:40         at com.sun.proxy.$Proxy361.execute(Unknown Source)
2022/1/28 下午2:47:40         at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
2022/1/28 下午2:47:40         at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
2022/1/28 下午2:47:40         at jdk.internal.reflect.GeneratedMethodAccessor413.invoke(Unknown Source)
2022/1/28 下午2:47:40         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022/1/28 下午2:47:40         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2022/1/28 下午2:47:40         at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
2022/1/28 下午2:47:40         at com.sun.proxy.$Proxy359.query(Unknown Source)
2022/1/28 下午2:47:40         at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
2022/1/28 下午2:47:40         at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
2022/1/28 下午2:47:40         at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
2022/1/28 下午2:47:40         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163)
2022/1/28 下午2:47:40         at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90)
2022/1/28 下午2:47:40         at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
2022/1/28 下午2:47:40         at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
2022/1/28 下午2:47:40         at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
2022/1/28 下午2:47:40         at jdk.internal.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
2022/1/28 下午2:47:40         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022/1/28 下午2:47:40         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2022/1/28 下午2:47:40         at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)

**Comment by strongduanmu** [comment]
@anonymous-lj Thank you for your feedback, we will investigate this issue.

**Comment by anonymous-lj** [comment]
spring:
  application: 
    name: micro-fund
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: fund
      fund:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://***:3306/***?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B0
        username: ***
        password: ***
    rules:
      sharding:
        tables:
          api_flow:
            actual-data-nodes: fund.api_flow
            table-strategy:
              standard:
                sharding-column: uuid
                sharding-algorithm-name: custom-sharding
        sharding-algorithms:
          custom-sharding:
            type: CLASS_BASED
            props: 
              strategy: STANDARD
              algorithmClassName: ***.CustomSharding

**Comment by anonymous-lj** [comment]
`spring:
  application: 
    name: micro-fund
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: fund
      fund:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://***:3306/***?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B0
        username: ***
        password: ***
    rules:
      sharding:
        tables:
          api_flow:
            actual-data-nodes: fund.api_flow
            table-strategy:
              standard:
                sharding-column: uuid
                sharding-algorithm-name: custom-sharding
        sharding-algorithms:
          custom-sharding:
            type: CLASS_BASED
            props: 
              strategy: STANDARD
              algorithmClassName: ***.CustomSharding`

**Comment by anonymous-lj** [comment]
spring:
  application: 
    name: micro-fund
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: fund
      fund:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://***:3306/***?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B0
        username: ***
        password: ***
    rules:
      sharding:
        tables:
          api_flow:
            actual-data-nodes: fund.api_flow
            table-strategy:
              standard:
                sharding-column: uuid
                sharding-algorithm-name: custom-sharding
        sharding-algorithms:
          custom-sharding:
            type: CLASS_BASED
            props: 
              strategy: STANDARD
              algorithmClassName: ***.CustomSharding

**Comment by zjcnb** [comment]
> spring: application: name: micro-fund shardingsphere: props: sql-show: true mode: type: Memory datasource: names: fund fund: type: com.alibaba.druid.pool.DruidDataSource driver-class-name: com.mysql.cj.jdbc.Driver url: jdbc:mysql://_**:3306/**_?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B0 username: *** password: *** rules: sharding: tables: api_flow: actual-data-nodes: fund.api_flow table-strategy: standard: sharding-column: uuid sharding-algorithm-name: custom-sharding sharding-algorithms: custom-sharding: type: CLASS_BASED props: strategy: STANDARD algorithmClassName: ***.CustomSharding

Thanks. I will check it.

**Comment by zjcnb** [comment]
@anonymous-lj Hi, Can you provider your CustomSharding class?

**Comment by anonymous-lj** [comment]
`public class CustomSharding implements StandardShardingAlgorithm<Comparable<?>> {

    @Override
    public void init() {
    }

    @Override
    public String getType() {
        return "custom-sharding";
    }

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Comparable<?>> shardingValue) {
        return "api_flow";
    }

    @Override
    public Collection<String> doSharding(Collection collection, RangeShardingValue rangeShardingValue) {
        return null;
    }
}`

**Comment by luodadaRyan** [comment]
Hi, is there a temporary solution? I also have such a problem.

**Comment by zjcnb** [comment]
> Hi, is there a temporary solution? I also have such a problem.

I 'm checking

**Comment by zjcnb** [comment]
@anonymous-lj Hello, i think your configuration has mistakes, your sql is `select * from api_wallet where id = ? for update`. But your configuration `logic table ` is `api_flow`.

**Comment by anonymous-lj** [comment]
I didn't api_wallet table configure as sharing，that should have no impact，Why do you report an error

**Comment by zjcnb** [comment]
> I didn't api_wallet table configure as sharing，that should have no impact，Why do you report an error

Yes, you are right. But i can't recurrent it. 

### My configuation
```
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.shardingsphere.sharding.db.table

server:
  port: 8890
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      ds0:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test0
        type: com.zaxxer.hikari.HikariDataSource
      names: ds0
    rules:
      sharding:
        sharding-algorithms:
          # 分表算法
          custom-sharding:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.shardingsphere.sharding.db.table.entity.CustomSharding

        tables:
          order:
            actual-data-nodes: ds0.order
            # 分表策略
            table-strategy:
              standard:
                sharding-column: uuid
                sharding-algorithm-name: custom-sharding
```

### My sql 

```
    <select id = "select" parameterType="com.shardingsphere.sharding.db.table.entity.User" resultMap="userMap">
        select * from t_user0 where id = #{id} for update
    </select>
```

### CustomSharding class

```
public class CustomSharding implements StandardShardingAlgorithm<Comparable<?>> {
    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Comparable<?>> shardingValue) {
        return "order";
    }
    
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Comparable<?>> shardingValue) {
        return null;
    }
    
    @Override
    public void init() {
    
    }
    
    @Override
    public String getType() {
        return "custom-sharding";
    }
}
```

<img width="1808" alt="image" src="https://user-images.githubusercontent.com/33742097/154210458-7a376ee0-8bba-45ac-8f39-d8fd58fc7c69.png">

Maybe your can provider a demo project?

**Comment by anonymous-lj** [comment]
This anomaly can only be detected during pressure test，Moreover, I involve multiple service calls, and the simple pressure test has no impact

**Comment by zjcnb** [comment]
> This anomaly can only be detected during pressure test，Moreover, I involve multiple service calls, and the simple pressure test has no impact

Okay, i will keep following

**Comment by zjcnb** [comment]
@anonymous-lj Hi, Can you use 5.1.2 release try again?

**Comment by TeslaCN** [comment]
Please upgrade to latest version. I'm closing this unless we could reproduce it.
