### ISSUE TITLE
[DistSQL] Add a syntax `SHOW SHARDING TABLE RULES USED KEY GENERATOR`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15169]
Hi community,
this issue is similar to [SHOW SHARDING TABLE RULES USED ALGORITHM](https://github.com/apache/shardingsphere/issues/15168)

### Aim
The syntax is as follows:
```sql
SHOW SHARDING TABLE RULES USED KEY GENERATOR keyGenerator [FROM schemaName]
```

### Reference
- #14610
- #15167

**Comment by LeeGuoPing** [comment]
Hi, I want to do it.

**Comment by RaigorJiang** [comment]
Welcome @LeeGuoPing

**Comment by LeeGuoPing** [comment]
@RaigorJiang Is it belong to RAL or RQL, I see both them has show ***

**Comment by RaigorJiang** [comment]
@LeeGuoPing 
The query of schema rules should in RQL.
Queries in RAL are global rules and global configurations.
