### ISSUE TITLE
[DistSQL] Add a syntax `SHOW SHARDING TABLE RULES USED ALGORITHM`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15168]
Hi community,
this issue is similar to [SHOW RULES USED RESOURCE](https://github.com/apache/shardingsphere/issues/15167)

### Aim
The syntax is as follows:
```sql
SHOW SHARDING TABLE RULES USED ALGORITHM algorithmName [FROM schemaName]
```

### Reference
- #14609
- #15167

**Comment by art-yang** [comment]
May I have a try？

**Comment by art-yang** [comment]
Hi, I want to do it.

**Comment by yx9o** [comment]
@art-yang Welcome.

**Comment by RaigorJiang** [comment]
Hi @leedongyang 
any update? Did you encounter difficulties?

**Comment by leedongyang** [comment]
@RaigorJiang I am too busy these days. I plan to deal with this issue this weekend.

**Comment by RaigorJiang** [comment]
@leedongyang 
Well, no hurry, you can enjoy the process.
