### ISSUE TITLE
`ClusterContextManagerCoordinator` need to add some unit test.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15185]
Hi community,

`ClusterContextManagerCoordinator.class` need to add some unit test.

- [ ] renew(final PrimaryStateChangedEvent event)
- [ ] renew(final StateEvent event)
- [ ] renew(final WorkerIdEvent event)
- [ ] renew(final LabelsEvent event)

**Comment by shankeerthan-kasilingam** [comment]
Hi @zjcnb,
I'd like to pickup this issue.

**Comment by strongduanmu** [comment]
@shankeerthan-kasilingam Welcome, I just assign this issue to you.
