### ISSUE TITLE
Add test case for MetaDataPersistService.getEffectiveDataSources()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15217]

**Comment by csonezp** [comment]
I would like to contribute in this issue, please assign it to me

**Comment by strongduanmu** [comment]
@csonezp Welcome.

**Comment by csonezp** [comment]
@terrymanu 
sorry,I've been so busy lately that I don't have time to deal with this

**Comment by acmenlt** [comment]
You can give it to me, thank you.
