### ISSUE TITLE
[DistSQL] Add a syntax `COUNT INSTANCE RULES`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#15275]
Hi community,
this issue is for a new DistSQL syntax.

**Background**
> Currently, there is already a `count schema rules` syntax for querying the number of rules in a schema, but it is still troublesome to get the number of rules in an instance when there are multiple schemas.

So we intend to provide a syntax for querying all rules in an instance.

**Aim**

| feature  |type  | count
| ----     | ---- |---- |
| single_table |table |  2  |
| sharding     |sharding_table |  2  |
| sharding |binding_table |  1  |
| sharding |broadcast_table |  0  |
| readwrite_splitting |datasource |  1  |
| db_discovery |datasource |  0  |
| encrypt  | table |0  |
| shadow  | datasource |0  |

The syntax is as follows:

```mysql
COUNT INSTANCE RULES;
```

_Tip: You can refer to the `count schema rules` syntax  https://github.com/apache/shardingsphere/pull/14736_

**Comment by TaoTaos068** [comment]
I would like to contribute in this issue, please assign it to me

**Comment by strongduanmu** [comment]
@TaoTaos068 Welcome.
