### ISSUE TITLE
Do data consistency check on only one proxy node in proxy cluster for every scaling job

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15291]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Currently, `FinishedCheckJob` which is used to check scaling jobs completion and continue next process, `FinishedCheckJob` will be started in every proxy node, it's not necessary to do it, it's better to do some improvement:
1. Do data consistency check on only one proxy node in proxy cluster (should be done).
2. Start `FinishedCheckJob` on only one proxy node in proxy cluster, or refactor the process (optional).

**Comment by ReyYang** [comment]
can i take this? thanks
