### ISSUE TITLE
Support ShardingSphereDataSource initialization with XA disabled

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15290]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Currently, when creating a new `ShardingSphereDataSource`, XA is enabled by default, XA feature will be initialized. Scaling will create new `ShardingSphereDataSource`, but XA is not necessary for scaling, it's better to disable XA for scaling for better performance and avoid possible XA connection leak (e.g. #13479).

TODO:
1. Refactor `ShardingSphereDataSource`, make it possible to configure XA enabled or not when initializing `ShardingSphereDataSource`.
2. Initialize `ShardingSphereDataSource` with XA disabled.

**Comment by ReyYang** [comment]
can i take this? thx

**Comment by sandynz** [comment]
Currently, XA won't be initialized when it's configured as LOCAL (default value).
