### ISSUE TITLE
When will the version 5.1.0 be pushed to the maven central repository？

### ISSUE THREAD

**Issue by Glowdable** [apache/shardingsphere#15349]
When will the version 5.1.0 be pushed to the maven central repository？

**Comment by menghaoranss** [comment]
The version 5.1.0 is voting. You can follow the [mailing-list](https://lists.apache.org/thread/34pyky29qw4p8knh2wzh02xhp3d7bcro) to get the latest progress

**Comment by RaigorJiang** [comment]
5.1.0 has been released:
Download Links: 
https://shardingsphere.apache.org/document/current/en/downloads/
Release Notes: 
https://github.com/apache/shardingsphere/blob/master/RELEASE-NOTES.md
