### ISSUE TITLE
Mysql parse SQL exception

### ISSUE THREAD

**Issue by AngeLoidYun** [apache/shardingsphere#15355]
I got an error when i execute sql bellow:
```SELECT a.maxvalue from example a where a.id = '2'```

error message:
```
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
```

I try to wrap maxvalue with '\`'  it works .
```SELECT a.`maxvalue` from example a where a.id = '2'```

but the first sql execute success in all other sql executors. i think this is a bug.

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Reason analyze (If you can)
maxvalue is a keyword of mysql

**Comment by TeslaCN** [comment]
Hi @AngeLoidYun 
`a=.id` or `a.id`?

**Comment by AngeLoidYun** [comment]
@TeslaCN sorry , ```a.id```

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin Could you help us check this issue?

**Comment by tuichenchuxin** [comment]
@TeslaCN Ok, I'll fix this.

**Comment by Bpazy** [comment]
May I try this? Seems to be a problem of parsing

**Comment by strongduanmu** [comment]
> parsing

@Bpazy Welcome, I just assign this issue to you.
