### ISSUE TITLE
How to execute DML queries on sharded table

### ISSUE THREAD

**Issue by vivek579** [apache/shardingsphere#15356]
## How to execute DML queries on sharded table

Executing DML queries with flyway is supported ?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by vivek579** [comment]
Using

**Comment by RaigorJiang** [comment]
ShardingSphere-JDBC is based on JDBC for logical processing, and theoretically supports any ORM and JDBC-based SQL client.
As for your question about flyway, the description is too simplistic, can you provide more information? How would you like to use it? What kind of SQL is executed? Any concerns?

**Comment by terrymanu** [comment]
Closed because no response
