### ISSUE TITLE
ShardingSphere-Proxy Occasionally discard commit&rollback operations

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#15388]
### Which version of ShardingSphere did you use?
5.0.0-Alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
transaction normal commit&rollback

### Actual behavior
app-ssproxy execute commit&rollback but ssproxy not execute commit&rollback to db （Happens ocasionally）

### Reason analyze (If you can)
sorry ~

**Comment by TeslaCN** [comment]
@git-chenhao 
The ShardingSphere has a lot of enhancements about transaction after 5.0.0-alpha. It's hard to confirm the issue of a legacy version if we don't know how to reproduce it.

**Comment by TeslaCN** [comment]
Close due to no response.
