### ISSUE TITLE
Enhancements to proxy integration narayana

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#15405]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Background
When using the proxy with narayana, we need to configure the `xaRecoveryNodes` attribute for the proxy (the instanceid of the current proxy is used by default), and this attribute can be modified through distsql. The `xaRecoveryNodes` attribute is instance-level and needs to be bound to the instance

### Describe the feature you would like.

- [x] Store `xaRecoveryNodes` at the instance level  @menghaoranss 
- [x] add Event when `xaRecoveryId` changed @menghaoranss 
- [x] use distsql to show all instanceid @RaigorJiang 
- [x] use distsql to modify `xaRecoveryId` @RaigorJiang 
- [x] Ensure that `TM` is properly reinitialized after `xaRecoveryId` is modified @jingshanglu 
- [x] suppprt default jdbc recovery store for cluster mod. @jingshanglu

**Comment by RaigorJiang** [comment]
Well, for task 2, `SHOW INSTANCE LIST` can display all instance ids, can it meet the requirements?

**Comment by jingshanglu** [comment]
> 

The result of `SHOW INSTANCE LIST` is used to provide the user with the modified value.

**Comment by menghaoranss** [comment]
@jingshanglu  the DistSQL to show all instanced is already exists : `SHOW INSTANCE LIST`

**Comment by RaigorJiang** [comment]
Hi @jingshanglu 
I found the `xa_recovery_id` in the `ComputeNode`, so I plan to make the following adjustments:
- Added display of `XA_RECOVERY_ID` in `SHOW INSTANCE LIST`
- Added a DistSQL syntax to modify it:
`ALTER INSTANCE 10.x.x.xxx@3307 SET XA_RECOVERY_ID xxx`

**Comment by soulasuna** [comment]
@menghaoranss I can try `add Event when xaRecoveryId changed`, please  assign to me.

**Comment by jingshanglu** [comment]
@RaigorJiang Maybe we should support this sql
`ALTER INSTANCE 127.0.0.1@3310 SET XA_RECOVERY_ID = 127.0.0.1@3308,127.0.0.1@3310;` 
`127.0.0.1@3308` is not alive proxy instance.

**Comment by RaigorJiang** [comment]
> ALTER INSTANCE 127.0.0.1@3310 SET XA_RECOVERY_ID = 127.0.0.1@3308,127.0.0.1@3310;
127.0.0.1@3308 is not alive proxy instance.

Hi @jingshanglu , can we change the key to `XA_RECOVERY_NODES` :
```sql
ALTER INSTANCE 127.0.0.1@3310 SET XA_RECOVERY_NODES = 127.0.0.1@3308,127.0.0.1@3310;
```

**Comment by jingshanglu** [comment]
> > ALTER INSTANCE 127.0.0.1@3310 SET XA_RECOVERY_ID = 127.0.0.1@3308,127.0.0.1@3310;
> > 127.0.0.1@3308 is not alive proxy instance.
> 
> Hi @jingshanglu , can we change the key to `XA_RECOVERY_NODES` :
> 
> ```sql
> ALTER INSTANCE 127.0.0.1@3310 SET XA_RECOVERY_NODES = 127.0.0.1@3308,127.0.0.1@3310;
> ```

OK，i agree with this idea.

**Comment by TeslaCN** [comment]
Hi @jingshanglu @lanchengx 
Any update here? Could we finish this in 5.1.1?

**Comment by lanchengx** [comment]
@TeslaCN done

**Comment by TeslaCN** [comment]
> @TeslaCN done
