### ISSUE TITLE
合并m个长度为n的已排序数组的时间复杂度为O(mn(log m))

### ISSUE THREAD

**Issue by carteruu** [apache/shardingsphere#15413]
合并m个长度为n的已排序数组的时间复杂度为O(mn(log m))，按照原文举的例子，分片数量m为2时，时间复杂度为O(n)，原文并没有问题，只是表述有歧义。
而且一般分片数量都不会很大，基本可以认为是O(n)。

_Originally posted by @[CoderFengZi](https://github.com/CoderFengZi) in https://github.com/apache/shardingsphere/issues/9745#issuecomment-1039961458_

**Comment by carteruu** [comment]
1

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
