### ISSUE TITLE
App hanging when working with DruidDataSource

### ISSUE THREAD

**Issue by lite-up** [apache/shardingsphere#15420]
### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core-spring-boot-starter 5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
I'm currently using `DruidDataSource`, everything works fine. 

### Actual behavior
However, if these below conditions being met: 
1. `sharding-jdbc.max-connections-size-per-query > druid.maxActive`, 
2. `Actual SQLs number > druid.maxActive`
and then the application will be hanging forever for waiting for the next idle `Connection`;

### Reason analyze (If you can)
1. `sharding-jdbc.max-connections-size-per-query > druid.maxActive`, 
2. `Actual SQLs number > druid.maxActive`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. set `sharding-jdbc.max-connections-size-per-query > druid.maxActive`;
2. and then simply do some `xxxMapper.selectList(null)` to make a ALL-SHARDING-TABLES-Scanning.

**Comment by terrymanu** [comment]
Does anyone want to investigate it?

**Comment by TeslaCN** [comment]
I think this is expected. `max-connections-size-per-query` should not greater than available in connection pool.
