### ISSUE TITLE
[DistSQL]CREATE SHARDING TABLE RULE report syntax

### ISSUE THREAD

**Issue by wjf870128** [apache/shardingsphere#15442]
shardingsphere-proxy : 5.1.0
DistSQL step:
1）CREATE SHARDING KEY GENERATOR snowflake_key_generator (TYPE(NAME=SNOWFLAKE));
2）CREATE SHARDING ALGORITHM database_inline (
TYPE(NAME=inline,PROPERTIES("algorithm-expression"="ts_${user_id % 4}"))
);
3）CREATE SHARDING ALGORITHM table_inline (
TYPE(NAME=inline,PROPERTIES("algorithm-expression"="t_order_${order_id % 4}"))
);
4）CREATE SHARDING TABLE RULE t_order (
DATANODES("ts_${0..3}.t_order_${0..3}"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=user_id,SHARDING_ALGORITHM=database_inline),
TABLE_STRATEGY(TYPE=standard,SHARDING_COLUMN=order_id,SHARDING_ALGORITHM=table_inline),
GENERATED_KEY(COLUMN=id,GENERATED_KEY_ALGORITHM=snowflake_key_generator)
);
then report the error：ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'。
If I change the 4 step to the following referenced the document:
CREATE SHARDING TABLE RULE t_order (
DATANODES("ts_${0..3}.t_order_${0..3}"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=user_id,SHARDING_ALGORITHM(TYPE(NAME=inline,PROPERTIES("algorithm-expression"="ts_${user_id % 4}")))),
TABLE_STRATEGY(TYPE=standard,SHARDING_COLUMN=order_id,SHARDING_ALGORITHM=table_inline),
GENERATED_KEY(COLUMN=id,GENERATED_KEY_ALGORITHM=snowflake_key_generator)
);
The error is also occured.

**Comment by lanchengx** [comment]
@wjf870128 Thanks your feedback, 5.1.0 The syntax has been adjusted, `GENERATED_KEY` has been replaced with `KEY_GENERATE_STRATEGY`, please refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl /rule-definition/sharding/

**Comment by wjf870128** [comment]
> @wjf870128 Thanks your feedback, 5.1.0 The syntax has been adjusted, `GENERATED_KEY` has been replaced with `KEY_GENERATE_STRATEGY`, please refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/

Thanks,that's ok!

CREATE SHARDING TABLE RULE t_order (
DATANODES("ts_${0..3}.t_order_${0..3}"),
DATABASE_STRATEGY(TYPE=standard,SHARDING_COLUMN=user_id,SHARDING_ALGORITHM=database_inline),
TABLE_STRATEGY(TYPE=standard,SHARDING_COLUMN=order_id,SHARDING_ALGORITHM=table_inline),
KEY_GENERATE_STRATEGY(COLUMN=id,KEY_GENERATOR=snowflake_key_generator)
);
