### ISSUE TITLE
Upgrade 5.1.0 to start reporting NullPointException 

### ISSUE THREAD

**Issue by pandatop** [apache/shardingsphere#15447]
version:5.1.0
sharding-jdbc
problem description: 
I upgraded from 5.0.0 to 5.1.0. After the project is started, a NullPointException occurs when checking the read-write configuration, but I don't know what the type of the read-write configuration is. There is no relevant example on the official documentation.

![image](https://user-images.githubusercontent.com/86768666/154245835-195f192e-9b7a-499a-b475-ae5083d1bd3f.png)
![image](https://user-images.githubusercontent.com/86768666/154246451-502899ea-4bc8-4511-9504-a775e165b43d.png)
![image](https://user-images.githubusercontent.com/86768666/154246571-72b50675-3696-46b3-8be2-0f2135b6e8d8.png)

**Comment by terrymanu** [comment]
I just set it as `invalid` because of closed by author without any reason.
