### ISSUE TITLE
shardingsphere-jdbc with jdbcTemplate.update()  throw null exception

### ISSUE THREAD

**Issue by ionauq** [apache/shardingsphere#15451]
## Question

when i use `shardingsphere-jdbc-core` `5.0.0` with  `JdbcTemplate.update()` in readwrite-splitting mode, the  `keyHolder` return null.

example:

```
  GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();
        int row = jdbcTemplate.update((conn) -> {
            PreparedStatement ps = conn.prepareStatement("insert into tags (app_id, name) value(?, ?)", Statement.RETURN_GENERATED_KEYS);
            ps.setLong(1, 1L);
            ps.setString(2, "test");
            return ps;
        }, keyHolder);

        long id = keyHolder.getKey().longValue();
```

![image](https://user-images.githubusercontent.com/4327765/154261641-b06ba707-8860-4c1f-8552-c27b643de862.png)

![image](https://user-images.githubusercontent.com/4327765/154264243-e8c149ec-5062-4f62-b75d-aeb356f9ae2e.png)

The program runs to `new GeneratedKeysResultSet`,  if the column is not null, the program is normal.

Do I need to configure specific information? 

thanks

**Comment by strongduanmu** [comment]
Hi @ionauq, thank you for your feedback. It looks like a bug, I will investigate this issue.

**Comment by strongduanmu** [comment]
Hi @ionauq, I have tested with PreparedStatement and generatedKeys are fetched normally. I'm not very familiar with JdbcTemplate, does it depend on the columnName field? If you can provide a demo, I believe the problem will be solved quickly.

**Comment by ionauq** [comment]
> Hi @ionauq, I have tested with PreparedStatement and generatedKeys are fetched normally. I'm not very familiar with JdbcTemplate, does it depend on the columnName field? If you can provide a demo, I believe the problem will be solved quickly.

thanks.  I write a simple demo. 

 [shardingJdbcDemo](https://github.com/ionauq/shardingJdbcDemo)

**Comment by strongduanmu** [comment]
@ionauq Thank you, I will check it again.

**Comment by strongduanmu** [comment]
Hi @ionauq, can you help test this problem with master branch? You can execute `mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C` on your machine.

**Comment by ionauq** [comment]
> Hi @ionauq, can you help test this problem with master branch? You can execute `mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C` on your machine.

It's so efficient!  The test passed under my use case. Thanks!!!
When will the next stable version be released?

**Comment by strongduanmu** [comment]
@ionauq I'm very sorry, as 5.1.0 has just been released, the next version may take some time. If you rely on this bug fix, consider packaging it yourself.

**Comment by ionauq** [comment]
> @ionauq I'm very sorry, as 5.1.0 has just been released, the next version may take some time. If you rely on this bug fix, consider packaging it yourself.

ok, thanks!
