### ISSUE TITLE
sql by nested queries and group by  ,Prompt table does not exist , Table splitting failed

### ISSUE THREAD

**Issue by secondchilde** [apache/shardingsphere#15460]
## sql by nested queries and group by  ,Prompt table does not exist , Table splitting failed
sharding version : 4.1.1
Slice table : t_scan_task_number
Slice key : store_id

when i exectuor this sql :

select count(1) from (
        SELECT
        store_id,DATE_FORMAT(scan_time,"%Y%m"),distributor_id
        FROM。t_scan_task_number 
        WHERE 1=1
    and scan_time >= DATE_FORMAT('2022-02-01 00:00:00', '%Y-%m-%d %H:%i:%s' )
        and scan_time <= DATE_FORMAT('2022-02-28 23:59:59', '%Y-%m-%d %H:%i:%s' )
        and store_id in (12057,1123)
     
        group by store_id,distributor_id,DATE_FORMAT(scan_time,"%Y%m") order by store_id
        asc,DATE_FORMAT(scan_time,"%Y%m") desc ) temp

Prompt: 
1146 - Table 'db_puxian_promotion.t_scan_task_number' doesn't exist, Time: 0.013000s

When I add a serial number in the back, it will be executed successfully。 t_scan_task_number_01

wait for reply,thanks

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
Hi @secondchilde, thank you for your feedback. But version 4.1.1 does not support subqueries, if you want to use subqueries, please upgrade to version 5.1.0.

**Comment by secondchilde** [comment]
I tried. Version 5.1.0 is really OK. Thank you

**Comment by strongduanmu** [comment]
@secondchilde Thank you for testing. Can we close this issue now?

**Comment by strongduanmu** [comment]
Already fixed by version 5.1.0.

**Comment by secondchilde** [comment]
sry. I couldn't open GitHub some time ago , The problem has been solved , thank you .
