### ISSUE TITLE
分表配置分片规则表名遇到$如何处理？

### ISSUE THREAD

**Issue by pqgj19930708** [apache/shardingsphere#15478]
最开始是这样配置的
spring.shardingsphere.sharding.tables.coin_$crdnusdt.actual-data-nodes=exchange.coin_$crdnusdt
报找不到crdnusdt这个脚本
之后增加转义$
spring.shardingsphere.sharding.tables.ex_trade_$crdnusdt.actual-data-nodes=exchange.ex_trade_\$crdnusdt
还是报找不到crdnusdt这个脚本
再增加\\$转义后
spring.shardingsphere.sharding.tables.ex_trade_$crdnusdt.actual-data-nodes=exchange.ex_trade_\\$crdnusdt
不报错了。但是
启动日志是下面这样
masterSlaveRules:
    tables:
           ex_trade_crdnusdt:
                actualDataNodes: exchange.ex_trade_\$crdnusdt
                logicTable: ex_trade_crdnusdt

有没有办法解决一下

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
