### ISSUE TITLE
shardingsphere 5.0.0 version  yml configuration is not supported  YamlTransactionRuleConfiguration

### ISSUE THREAD

**Issue by ruoyang-pin** [apache/shardingsphere#15488]
![image](https://user-images.githubusercontent.com/82640419/154618140-baf5437d-cd66-4757-9d83-e66a99b356f9.png)

**Comment by RaigorJiang** [comment]
Hi @ruoyang-pin 
Why do you say that, is there any more information?

**Comment by zjcnb** [comment]
@ruoyang-pin Hi, are you referring to configuration in springboot project's application.yml file?

**Comment by ruoyang-pin** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 19:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] shardingsphere 5.0.0 version  yml configuration is not supported  YamlTransactionRuleConfiguration (Issue #15488)




 
@ruoyang-pin Hi, are you referring to configuration in springboot project's application.yml file?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjcnb** [comment]
Got it! Maybe support it next release.

**Comment by ruoyang-pin** [comment]
thank you



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 21, 2022 19:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] shardingsphere 5.0.0 version  yml configuration is not supported  YamlTransactionRuleConfiguration (Issue #15488)




 
Got it! Maybe support it next release.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjcnb** [comment]
This issue need confirm. I think we can discuss whether it is necessary.

**Comment by zhaojinchao95** [comment]
This issue need to be reconsidered.  i close it.
