### ISSUE TITLE
NPE with flywaydb 

### ISSUE THREAD

**Issue by ynfeng** [apache/shardingsphere#15497]
version: 5.1.0

Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.driver.jdbc.adapter.AdaptedDatabaseMetaData.getDatabaseProductName(AdaptedDatabaseMetaData.java:46)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.getDatabaseProductName(JdbcUtils.java:169)
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromJdbcConnection(DatabaseType.java:68)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:82)
	at org.flywaydb.core.Flyway.execute(Flyway.java:456)
	at org.flywaydb.core.Flyway.repair(Flyway.java:369)

**Comment by ynfeng** [comment]
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    schemas: demo
    validate-on-migrate: false
  shardingsphere:
    rules:
      readwrite-splitting:
        data-sources:
          readwrite-ds:
            type: Static
            props:
              write-data-source-name: main-ds
              read-data-source-names: readonly-ds
    datasource:
      names:
        - main-ds
        - readonly-ds
    main-ds:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/demo?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: 123456
    readonly-ds:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/demo?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: 123456

**Comment by strongduanmu** [comment]
Hi @ynfeng, thank you for your feedback. I'm not familiar with flywaydb, can you dig into the code to see what caused the exception?

**Comment by ynfeng** [comment]
In class org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData line 57, the dataSourcesMetaData was null.
![20220218170208](https://user-images.githubusercontent.com/7802558/154651598-74755e45-dd61-4ab4-93d8-dc69c5c3d8ba.jpg)

**Comment by ynfeng** [comment]
Oh, I found the problem. The config in yaml dosen't support this format.
![1](https://user-images.githubusercontent.com/7802558/154655829-83a862a2-4bb9-4be7-9cb9-277aa4419dd5.jpg)
and this is ok.
![2](https://user-images.githubusercontent.com/7802558/154655877-f89ebbae-56cd-4d01-ba73-c9ce8f5a9cf9.jpg)

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by strongduanmu** [comment]
@LeeGuoPing Welcome.

**Comment by LeeGuoPing** [comment]
sorry, I use the config but never reproduce the problem.

The config:
![config](https://user-images.githubusercontent.com/35389145/155493339-673b1fb9-45cc-4998-91ec-598f019ba9b6.png)

The result:
![image](https://user-images.githubusercontent.com/35389145/155493527-3babb4db-9959-4944-8133-8c715aa5b571.png)

**Comment by terrymanu** [comment]
I close the issue because of no response anymore.
