### ISSUE TITLE
Could you please replace static version with {revision} variable?

### ISSUE THREAD

**Issue by bjo2008cnx** [apache/shardingsphere#15531]
when the version needs to be updated, we need to modify every pom.xml and then commit TOO MANY files.
Could you please replace version with {revision} variable so that only **ONE** file is required to be modified? 

FYI: http://maven.apache.org/maven-ci-friendly.html 

Thanks very much.

**Comment by bjo2008cnx** [comment]
FYI: https://github.com/apache/dubbo/blob/3.0/pom.xml
steps: 
1. add plugin into <build><plugins>...<plugins></build>
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.1.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

2. define revision property in parent pom.xml: 
   for example:
    <properties>
        <revision>5.0.1</revision>       
    </properties>

3. replace version in each pom.xml with ${revision}

**Comment by Swastyy** [comment]
Hi @bjo2008cnx , We have already implemented those in PR #13823

**Comment by TeslaCN** [comment]
@bjo2008cnx We use the maven-release-plugin when releasing.

**Comment by bjo2008cnx** [comment]
get it.  many thanks.

**Comment by TeslaCN** [comment]
I'm closing this. Please file a new issue if you have any other questions.
