### ISSUE TITLE
Cannot subclass final class org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource

### ISSUE THREAD

**Issue by lw613315** [apache/shardingsphere#15533]
## Question

Error creating bean with name 'dataSource'

Could not generate CGLIB subclass of class org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource: 
Cannot subclass final class org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource

**Comment by zjcnb** [comment]
@lw613315  Hi, Can you provide a demo? This problem same to #15086 . I want to know how to reproduce it.

**Comment by lw613315** [comment]
The problem has been solved. Due to configuration error.

**Comment by zjcnb** [comment]
> The problem has been solved. Due to configuration error.

Please close this issue, thx.

**Comment by roy-500** [comment]
> The problem has been solved. Due to configuration error.

How can I solve this problem? I have the same problem

**Comment by githust66** [comment]
> How can I solve this problem? I have the same problem

How can I solve this problem? I have the same problem

**Comment by githust66** [comment]
> The problem has been solved. Due to configuration error.

How can I solve this problem? I have the same problem

**Comment by YLongGe** [comment]
> The problem has been solved. Due to configuration error.
Could you tell me the solution？thanks
