### ISSUE TITLE
sharding-jdbc starts too slowly

### ISSUE THREAD

**Issue by Qumans** [apache/shardingsphere#15535]
### Reason analyze (If you can)：
possible code locations：
DatabaseType databaseType = DatabaseTypeRecognizer.getDatabaseType(dataSources.get(each).values());
Local test environment 600 tables took 13 seconds
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.sub-table only
2.two identical data sources
3.More than 10,000 tables
4.Only configure table splitting rules for one of the tables

**Comment by tuichenchuxin** [comment]
Can you try 5.1 version？
We have optimized it.

**Comment by terrymanu** [comment]
I close the issue because of no response anymore.

**Comment by sunxuejian** [comment]
help me, for the same issue, i used latest version 5.1.0,  still slow.    

tables: 8000+ 

Loading table metadata takes 15 minutes

**Comment by tuichenchuxin** [comment]
How many datasource? 8000+ is all single table?
Can you help to analysis which code is slow?
