### ISSUE TITLE
FinishCheckJob cannot do a completion check if the scaling job is incorrect

### ISSUE THREAD

**Issue by ReyYang** [apache/shardingsphere#15541]
### Is your feature request related to a problem?
yes
### Describe the feature you would like.
In the current case, FinishCheckJob is a separate program running, so it will still check the scaling state when the Scaling job fails, and we want to skip the completion check when the Scaling job fails

**Comment by sandynz** [comment]
It affect test case, if previous scaling job is successful and target data is not cleaned, then when new scaling job of the same schema is created, it'll be failed since target table is not empty, but FinishCheckJob will pass data consistency check.
