### ISSUE TITLE
Sharding-JDBC 5.1.0 startup time is too long

### ISSUE THREAD

**Issue by Qumans** [apache/shardingsphere#15543]
### Which version of ShardingSphere did you use?

5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Does not take up too much startup time

### Actual behavior

Loading metadata consumes a lot of time

### Reason analyze (If you can)

The amount of metadata is too large, there are about 400,000 pieces, and it is increasing every day，v5.1.0 can only solve the immediate problem, there will still be problems in the future

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

    datasource:
      ds-0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: 
        username: 
        password: 
        maxWait: 60000
        maxActive: 1000
        maxIdle: 20
        initialSize: 20
        removeAbandoned: true
        validationQuery: SELECT 1
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
      names: ds-0
    rules:
      sharding:
        tables:
          prod_gray_cloth_inventory:
            actualDataNodes: ds-0.table_$->{0..31}
            keyGenerateStrategy:
              column: id
              props:
                worker:
                  id: 100
              keyGeneratorName: SNOWFLAKE
            tableStrategy:
              standard:
                shardingAlgorithmName: inventoryalg
                shardingColumn: 
        sharding-algorithms:
          inventoryalg:
            type: 
            props:
              strategy: STANDARD
              algorithmClassName:

**Comment by strongduanmu** [comment]
> The amount of metadata is too large, there are about 400,000 pieces

@Qumans Thank you for your feedback. How to understand this sentence? 400,000 tables exist?

**Comment by linxiaofan** [comment]
> > The amount of metadata is too large, there are about 400,000 pieces
> 
> @Qumans Thank you for your feedback. How to understand this sentence? 400,000 tables exist?

麻烦看下我上面的回复哈

**Comment by strongduanmu** [comment]
@linxiaofan First of all, thank you very much for your feedback. Since this is an international project, please translate the message into English so that more people can participate. In addition, we will optimize the scenario you provide, and we will update the issue on the latest optimization progress.

**Comment by linxiaofan** [comment]
> 



> @linxiaofan First of all, thank you very much for your feedback. Since this is an international project, please translate the message into English so that more people can participate. In addition, we will optimize the scenario you provide, and we will update the issue on the latest optimization progress.

OK..I look forward to your optimization，thanks.

**Comment by tuyendev** [comment]
Beside your data is large, I also encountered this problems compare with version 4.1.1. It seems 2x lower

**Comment by systemview2018** [comment]
any update on this issue?

**Comment by strongduanmu** [comment]
@systemview2018 Can you try the latest version?

**Comment by smoothbasterd** [comment]
I use the 5.4.0,start up time takes ten minutes long.Is my meta data too large?Which meta data too large may take this situation.

**Comment by jonaskahn** [comment]
This issue should be considered due performance enhancing.

**Comment by strongduanmu** [comment]
Please try the latest 5.4.1, this problem has been optimized.
