### ISSUE TITLE
`ClusterContextManagerCoordinator.renew(final SchemaVersionChangedEvent event)` Add unit test.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15564]

**Comment by zjcnb** [comment]
`1`

**Comment by zjcnb** [comment]
`1`

**Comment by baolieshougu** [comment]
Can I try it?

**Comment by strongduanmu** [comment]
@baolieshougu Welcome, I just assign this issue to you.

**Comment by yangsen00** [comment]
hello,I have a question. Where I circled out.
![image](https://user-images.githubusercontent.com/73088519/155329557-c4f51f7e-c472-47fc-b100-538c456ac34e.png)
When I use 
`        mock(MockedDataSource.class)
`
It will cause a NullPoint, It same like that. MockedDataSource.class don't have value of url,username and password.
And I use a constructor as this picture show,  it worked.
How can I fix if?

**Comment by yx9o** [comment]
@yangsen00 Hi, you can try to create a data source through a method and specify the parameter information you need.
example:
```java
private MockedDataSource createDataSource() {
        MockedDataSource result = new MockedDataSource();
        result.setUrl("jdbc:mysql://localhost/demo_ds");
        result.setUsername("username");
        result.setPassword("password");
        return result;
    }
```
