### ISSUE TITLE
spring JdbcTemplate insert cann't support return key

### ISSUE THREAD

**Issue by larrychen8276** [apache/shardingsphere#15578]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
```
14:47:43.803 [http-nio-70-exec-4] INFO  ShardingSphere-SQL:74- Actual SQL: dataSourceMysqlMaster ::: insert into c_z_role(name,remark) values (?,?) ::: [eee, eee]
2月 23, 2022 2:47:43 下午 org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [springMvc] in context with path [/core] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "key" is null] with root cause
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "key" is null
	at org.springframework.util.LinkedCaseInsensitiveMap.convertKey(LinkedCaseInsensitiveMap.java:332)
	at org.springframework.util.LinkedCaseInsensitiveMap.putIfAbsent(LinkedCaseInsensitiveMap.java:212)
	at org.springframework.util.LinkedCaseInsensitiveMap.putIfAbsent(LinkedCaseInsensitiveMap.java:49)
	at org.springframework.jdbc.core.ColumnMapRowMapper.mapRow(ColumnMapRowMapper.java:55)
	at org.springframework.jdbc.core.ColumnMapRowMapper.mapRow(ColumnMapRowMapper.java:46)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$3(JdbcTemplate.java:1000)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:991)
```

### Example codes for reproduce this issue (such as a github link).
```
public Integer insertPrimaryKey(final SysRole entity) {
		KeyHolder keyHolder = new GeneratedKeyHolder();

		getJdbcTemplate().update(new PreparedStatementCreator() {
			public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
				PreparedStatement ps = connection.prepareStatement("insert into c_z_role (name, remark) values (?, ?)", Statement.RETURN_GENERATED_KEYS);
				ps.setString(1, entity.getName());
				ps.setString(2, entity.getRemark());
				return ps;
			}
		}, keyHolder);
               // keyHolder.getKey() is null
		return keyHolder.getKey().intValue();
	}
```

**Comment by strongduanmu** [comment]
@larrychen8276 Can you provide your configuration? Besides, you can look at this issue #15451, maybe they are same problems.

**Comment by larrychen8276** [comment]
> @larrychen8276 Can you provide your configuration? Besides, you can look at this issue #15451, maybe they are same problems.
[spring-mysql-readwrite-splitting.txt](https://github.com/apache/shardingsphere/files/8122477/spring-mysql-readwrite-splitting.txt)

**Comment by strongduanmu** [comment]
@larrychen8276 I think this issue is same with #15451, you can try the latest master branch.

**Comment by larrychen8276** [comment]
> @larrychen8276 I think this issue is same with #15451, you can try the latest master branch.

thanks!

**Comment by strongduanmu** [comment]
> 

You are welcome, looking forward to your test result.

**Comment by strongduanmu** [comment]
Hi @larrychen8276, can you try the latest master branch?
