### ISSUE TITLE
support multiple schema on same instance

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#15579]
### Is your feature request related to a problem?
```
Preconditions.checkState(schemaNames.size() <= 1, "Can not support multiple different schema.");
```
currently TablesContext will check schema number of select statement and throw exception on multiple schema detected.

### Describe the feature you would like.
can we support multiple schema on same instance? for example, sql like below
```
select t1.*, t2.* from test1.test t1, test2.test t2;
```

if I comment this check, I can get a "partial correct" result in client side prepare, i.e. using text protocol. but error on server side prepare, due to wrong field schema.

**Comment by roodkcab** [comment]
since shardingsphere treat each schema as a separate instance, i.e. test1 and test2 are running on different physic instances, I didn't figure out an easy way to support this feature. any idea?

**Comment by terrymanu** [comment]
Fixed
