### ISSUE TITLE
Fix IT error for `SELECT t_order_item_federate_sharding`

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15592]
The IT result is different with load data from database.

Case name: 

1. select t_order_federate.*, t_order_item_federate_sharding.* from t_order_federate, t_order_item_federate_sharding where t_order_federate.order_id = t_order_item_federate_sharding.item_id AND t_order_item_federate_sharding.remarks = 't_order_item_federate_sharding' 

2. select o.*, i.* from t_order_federate o, t_order_item_federate_sharding i where o.order_id = i.item_id 

Expected: is "1000"
but: was "10000"

Please see `dql-integration-test-cases.xml` and search `FIXME #15592`

**Comment by strongduanmu** [comment]
@terrymanu Thank you for your feedback, I will investigate this issue.

**Comment by LeeGuoPing** [comment]
I will investigate it.
