### ISSUE TITLE
Fix IT error for `SELECT COUNT(DISTINCT order_id), SUM(DISTINCT order_id) FROM t_order WHERE order_id &lt; 1100`

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15591]
The IT result is different with load data from database.

Case name: SELECT COUNT(DISTINCT order_id), SUM(DISTINCT order_id) FROM t_order WHERE order_id &lt; 1100
Expected: is "count(distinct order_id)"
but: was "aggregation_distinct_derived_0"

Please see `dql-integration-test-cases.xml` and search `FIXME #15591`

**Comment by tuichenchuxin** [comment]
Thank you for your feedback, I'll investigate it.
