### ISSUE TITLE
Fix IT error for select projection names

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15594]
The IT result is different with load data from database.

Please see: 
1. `BaseDQLIT` and search `// FIXME #15594 Expected: is "order_id", but: was "order_id0`, please remove the try catch to reproduce the issue
2. `BaseDQLIT` and search `// FIXME #15594 Expected: is "sum(order_id_sharding)0", but: was "expr$1"`, please remove the try catch to reproduce the issue

**Comment by strongduanmu** [comment]
@terrymanu Thank you for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment]
I have confirmed the issue, it's a bug of calcite jdbc driver, I will try to fix this bug and upgrade calcite version.

**Comment by strongduanmu** [comment]
Fixed by #20872
