### ISSUE TITLE
Fix IT error for `SELECT * FROM t_order o LEFT JOIN t_order_item m ON o.order_id = m.order_id AND o.user_id = m.user_id`

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15590]
The IT result is different with load data from database.

Case name: SELECT * FROM t_order o LEFT JOIN t_order_item m ON o.order_id = m.order_id AND o.user_id = m.user_id
Expected: is "1100"
but: was "2000"

Please see `dql-integration-test-cases.xml` and search `FIXME #15590`

**Comment by tuichenchuxin** [comment]
Thank you for your feedback , I'll invetigate it.
