### ISSUE TITLE
Fix IT error for accurate of AVG 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#15593]
The IT result is different with load data from database.

Case name: SELECT AVG(user_id) AS user_id_avg FROM t_order
Expected: is "19"
but: was "19.5000"

Please see: 
1. `dql-integration-test-cases.xml` and search `FIXME #15593`
2. `BaseDQLIT` and search `// FIXME #15593 verify accurate data types`, please remove the try catch to reproduce the issue

**Comment by strongduanmu** [comment]
@terrymanu Thank you for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment]
I have investigated the current processing logic of ShardingSphere MergeEngine for AVG functions, and they all use the precision of 4 decimal places. This logic needs to be investigated and kept consistent with the database.

```java
/**
 * Average aggregation unit.
 */
@RequiredArgsConstructor
public final class AverageAggregationUnit implements AggregationUnit {
    
    private BigDecimal count;
    
    private BigDecimal sum;
    
    @Override
    public void merge(final List<Comparable<?>> values) {
        if (null == values || null == values.get(0) || null == values.get(1)) {
            return;
        }
        if (null == count) {
            count = new BigDecimal("0");
        }
        if (null == sum) {
            sum = new BigDecimal("0");
        }
        count = count.add(new BigDecimal(values.get(0).toString()));
        sum = sum.add(new BigDecimal(values.get(1).toString()));
    }
    
    @Override
    public Comparable<?> getResult() {
        if (null == count || BigDecimal.ZERO.equals(count)) {
            return count;
        }
        // TODO use metadata to fetch float number precise for database field
        return sum.divide(count, 4, RoundingMode.HALF_UP);
    }
}
```
