### ISSUE TITLE
有没有地方，可以查看到各版本的变更记录

### ISSUE THREAD

**Issue by wangfan9002** [apache/shardingsphere#15610]
有没有地方，可以查看到各版本的变更记录； 例如，修复了什么BUG, 新增了什么特性

**Comment by strongduanmu** [comment]
Hi @wangfan9002, can you translate this issue to english first?

**Comment by menghaoranss** [comment]
@wangfan9002 refer to https://github.com/apache/shardingsphere/releases , and for English only here.
