### ISSUE TITLE
The first SQL is executed slowly after the application is started.

### ISSUE THREAD

**Issue by hachikozjq** [apache/shardingsphere#15628]
Version 5.0.0
An SQL query within 10ms will be executed for the first time after each restart, which will be hyperbolized to 4 or 5s at first. Later, according to the online method, "Select X" will be executed once after the container is started, which is effective, but the first execution needs about 2s. Later, it will be changed to a specific table query, and then reduced to within 500ms. But it still did not achieve the normal effect within 10ms.
```
        String databaseType = "MySQL";
        String sql = "select id from xxx limit 1";
        // 方法1
        DatabaseTypedSQLParserFacade sqlParserFacade = DatabaseTypedSQLParserFacadeRegistry.getFacade(databaseType);
        SQLParser sqlParser = SQLParserFactory.newInstance(sql, sqlParserFacade.getLexerClass(),
                sqlParserFacade.getParserClass(), true);
        ParseASTNode execute = (ParseASTNode) sqlParser.parse();
        ParseTree parseTree = execute.getRootNode();
        SQLVisitorFactory.newInstance(databaseType, "STATEMENT", SQLVisitorRule.valueOf(
                parseTree.getClass()), null);
```

**Comment by yx9o** [comment]
Hi @hachikozjq , for English only, please modify the issue title and content, thank you.

**Comment by Lyzxii** [comment]
Hi, I have this question too, did you figure it out?

**Comment by terrymanu** [comment]
Duplicated with #18369
