### ISSUE TITLE
sharding-jdbc insert clob type field into oracle db error

### ISSUE THREAD

**Issue by zhangzhaoyu** [apache/shardingsphere#15633]
## Bug Report

3.1.0 v

use sharding-jdbc to insert data into oracle db with clob filed exception:
SQL state 99999 error code 17004 无效的列类型。

orace.jdbc.driver.OraclePreparedStatement.setObject() not support StringReader.class type.

mybatis ClobTypeHandler convert java string to StringReader type for CLOB type.

how can I fix it ? Thanks.

**Comment by strongduanmu** [comment]
Hi @zhangzhaoyu, can you try 5.1.0? 3.1.0 is too old.

**Comment by terrymanu** [comment]
The version 3.x is out of service, welcome to try version 5.x
