### ISSUE TITLE
sharding jdbc 5.0.0(5.1.0) how to set a default datasource?

### ISSUE THREAD

**Issue by 13612687938** [apache/shardingsphere#15631]
## Question

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.0</version>
        </dependency>

when I have some datasource, how to set which is the default datasource?

**Comment by zjcnb** [comment]
@13612687938 Hi, I think the default data source are removed at 5.1.0

**Comment by 13612687938** [comment]
@zjcnb In the actual development, not all tables need sub-database and sub-table, there is always a single table, how to solve it?

**Comment by zjcnb** [comment]
> @zjcnb In the actual development, not all tables need sub-database and sub-table, there is always a single table, how to solve it?

`ShardingSphere` can according your table to find datasource if you a single table in one data source. But if you have same table in two  data source, the `ShardingSphere` can pick any one data source

**Comment by 13612687938** [comment]
Perfect, I tried three data sources, first put the table to data source 3 and then request, successful, and then move the table to data source 2 and then request, successful.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/shardingsphere] sharding jdbc 5.0.0(5.1.0) how to set a default datasource? (Issue #15631)





  
@zjcnb In the actual development, not all tables need sub-database and sub-table, there is always a single table, how to solve it?
  
ShardingSphere can according your table to find datasource if you a single table in one data source. But if you have same table in two  data source, the ShardingSphere can pick any one data source
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjcnb** [comment]
@13612687938 Yeah.
