### ISSUE TITLE
[OpenForce 2022] Integrating the embedded H2 Database to implement the standalone mode

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#15665]
This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

## Background

In the [standalone mode](https://shardingsphere.apache.org/document/current/en/concepts/mode/), it is not a good choice to use local files to persist metadata, because local files are not encrypted and can be modified at any time. Therefore, we consider using embedded H2 Database to support standalone mode. We need to persist the meta data in YAML format into H2 Database,  just like the registry center. All the meta data structure of the registry center please refer to [Management](https://shardingsphere.apache.org/document/current/cn/reference/management/).

## Task list
The following steps are required:

- [ ] Open `H2Repository.java` to implement all of the empty methods.
- [ ] Add necessary unit tests

**Comment by acmenlt** [comment]
You can assign it to me. Thank you @menghaoranss

**Comment by zjcnb** [comment]
> You can assign it to me. Thank you @menghaoranss

Welcome.
