### ISSUE TITLE
MySQL function from_unixtime not supported 

### ISSUE THREAD

**Issue by yuwentao** [apache/shardingsphere#15666]
query statement "FROM_UNIXTIME(created_time,'%Y-%m-%d') " not supported in shardingsphere 5.1.0 version

**Comment by strongduanmu** [comment]
Hi @yuwentao, can you show more information about this sql? Such as exception stack.

**Comment by wsg96321** [comment]
It seems to be ok to this function when I use version 5.1.0 version too.
![image](https://user-images.githubusercontent.com/8844009/156095487-445d93f4-4876-4e0e-9c9f-789467fe863f.png)

**Comment by yuwentao** [comment]
--  not supported and not any error information response
SELECT DAYOFMONTH(FROM_UNIXTIME(created_time, '%Y-%m-%d')) as riqi FROM `s_user` where created_time > 0  limit 1；
--  supported  ,response the right result
select DAYOFMONTH(NOW())；

**Comment by wsg96321** [comment]
Maybe your data or condition has something wrong in `s_user` ?  eg. therer is no record where created_time>0 。 

![image](https://user-images.githubusercontent.com/8844009/156101222-68d5824d-a42c-4da3-9096-9253609e55ba.png)

PS: The type of `createtime` in my table `hero` is datetime, so it has to cast it to unix timestamp when the function `FROM_UNIXTIME`'s first params type must be timestamp. 
this is mysql desc : `FROM_UNIXTIME(unix_timestamp,format)`

**Comment by RaigorJiang** [comment]
I tested on the current master and it works fine.

### In Proxy
<img width="990" alt="image" src="https://user-images.githubusercontent.com/5668787/215313127-bc650b86-5d98-4ce5-acc8-c193b2269a64.png">

### In MySQL
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/5668787/215313136-1525233c-7b2f-4ea1-a070-10acb84cdca7.png">
