### ISSUE TITLE
Enhance startup script for ShardingSphere-Proxy

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#15663]
### Is your feature request related to a problem?

Sometimes we try to start a new Proxy process before stopping the previous. In this situation, the new Proxy will fail to startup and we won't know it until we check the log.

### Describe the feature you would like.

- Support using `$JAVA_HOME`.
- (Optional) Check if the address and port which we attempt to use in new Proxy process is already used by another Proxy.
- Consider how to join the script until the Proxy startup succeeded or failed.
- (Docker) Make container down if ShardingSphere-Proxy startup failed.

**Comment by sunkai-cai** [comment]
please assignees to me
