### ISSUE TITLE
配合pagehelper使用，分页查询失效

### ISSUE THREAD

**Issue by afeiluo** [apache/shardingsphere#15661]
依赖:
```shell
<dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
      <version>4.1.1</version>
  </dependency>
 <exclusion>
      <groupId>com.github.pagehelper</groupId>
      <artifactId>pagehelper</artifactId>
      <version>5.3.0</version>
  </exclusion>
```
`PageHelper.startPage(1, 10)..doSelectPage(() -> mybatisMapperSelectMethod()); //查询的表没有分片` 
正常情况下pagerhelper 会查总数，然后再limit, 但是用了shardingjdbc提供的数据源之后，仅仅查询了mapper里面定义的sql语句，导致分页失效。

**Comment by yx9o** [comment]
Hi @afeiluo , for English only, please modify the issue title and content, thank you.
