### ISSUE TITLE
Encrypt feature performance optimize

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15686]
## Feature Request

At present, the encrypt feature of the master branch has a large performance loss, and it is necessary to investigate the performance bottleneck in it and improve the encrypt performance.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/10829171/156120284-d4e59af3-575d-4f1b-b7bd-d1df85e72d2d.png">

**Comment by TeslaCN** [comment]
Hi @strongduanmu 
Any update here?

**Comment by strongduanmu** [comment]
@TeslaCN Thank you for your remind, this issue can be closed now.
