### ISSUE TITLE
Add unit test for PipelineDataSourceCreatorFactory and PipelineDataSourceFactory

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15693]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `PipelineDataSourceCreatorFactory` and `PipelineDataSourceFactory` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by selectbook** [comment]
Hello, I would like to contribute in this issue.

**Comment by sandynz** [comment]
> Hello, I would like to contribute in this issue.

Welcome! Assigned to you.

**Comment by selectbook** [comment]
I'll get it done this week

**Comment by sandynz** [comment]
@selectbook , that's OK, thanks.

**Comment by terrymanu** [comment]
@selectbook Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by Swastyy** [comment]
Hi, I think this issue is completed

**Comment by sandynz** [comment]
> Hi, I think this issue is completed

Thanks. I'll close it now
