### ISSUE TITLE
[OpenForce 2022] Add unit test for PipelineTableMetaData

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15698]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `PipelineTableMetaData` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Example FYI
- `TableMetaDataTest`

**Comment by pk-218** [comment]
I am participating in OpenForce 2022 and would like to work on this issue.
@sandynz  could you assign this issue to me?

**Comment by sandynz** [comment]
@pk-218 Welcome!

**Comment by pk-218** [comment]
@sandynz I had a query
In the `PipelineTableMetaData` class, there is a method `getColumnMetaData` which is overloaded; the following are the method signatures:
```java
public PipelineColumnMetaData getColumnMetaData(final int columnIndex)
public PipelineColumnMetaData getColumnMetaData(final String columnName)
```
Should I test both these methods in the same JUnit test method and name it `assertGetColumnMetaData` or create separate test methods like `assertGetColumnMetaDataGivenColumnIndex` and `assertGetColumnMetaDataGivenColumnName`?
