### ISSUE TITLE
[OpenForce 2022] Add unit test for RecordUtil

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15699]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `RecordUtil` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by BashCache** [comment]
Hi,
I would like to work on this issue. Can you assign this to me

**Comment by BashCache** [comment]
Hi,
I have added the unit tests and raised a PR for the same. Please let me know if there are any changes to be made :)

**Comment by TeslaCN** [comment]
Finished in #15980.
