### ISSUE TITLE
[OpenForce 2022] Add unit test for `JobProgressYamlSwapper`

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15696]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `JobProgressYamlSwapper` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by BashCache** [comment]
Hi,
I would like to work on this issue. Could you please assign this to me.

**Comment by sandynz** [comment]
Hi @BashCache , welcome! Assigned.

**Comment by BashCache** [comment]
Hi,
I have made a PR for the same. Please let me know for any changes :)
