### ISSUE TITLE
[OpenForce 2022] Add unit test for PipelineSimpleLock

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15697]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `PipelineSimpleLock` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by strongduanmu** [comment]
Welcome @sandynz, I will assign this issue to you.

**Comment by sandynz** [comment]
Hi @shreya024 , welcome!
