### ISSUE TITLE
[OpenForce 2022] Add unit test for ShardingSpherePipelineDataSourceConfiguration

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15709]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `ShardingSpherePipelineDataSourceConfiguration` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by rithikarajk** [comment]
Hi, I am an Openforce 2022 participant. I would like to work on this issue.

**Comment by sandynz** [comment]
Hi @rithikarajk , welcome!

**Comment by rithikarajk** [comment]
@sandynz Thank you.

**Comment by TeslaCN** [comment]
Hi @rithikarajk 
Any update here?

**Comment by sandynz** [comment]
Hi @rithikarajk , feel free to leave comment here if you have any question.

**Comment by rithikarajk** [comment]
Sorry Sir for the delay. I am working on the issue. I lost the track due to
unexpected series exams. I couldn't focus on solving the issue. I assure to
close the issue as soon as possible.

**Comment by sandynz** [comment]
@rithikarajk , that's OK, thanks.

**Comment by sandynz** [comment]
Closed since it's already implemented
