### ISSUE TITLE
[OpenForce 2022] Add unit test for CRC32MatchMySQLSingleTableDataCalculator

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15705]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `CRC32MatchMySQLSingleTableDataCalculator` in `shardingsphere-data-pipeline-mysql` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by pparthenhs** [comment]
Dear @sandynz , 

I start working on this ticket.

I will let you know when I am finished.

Best regards, 
Panagiotis Parthenis

**Comment by yx9o** [comment]
@pparthenhs Welcome.

**Comment by sandynz** [comment]
Welcome!

**Comment by pparthenhs** [comment]
Hello @yx9o  and @sandynz , 

Thank you for the welcome, I am happy to contribute. 

I just open the PR regarding the adding unit test for CRC32MatchMySQLSingleTableDataCalculator.

I remain at your disposal for any code review comments and any further support.

Best regards, 
Panagiotis Parthenis
