### ISSUE TITLE
Add unit test for PositionInitializerFactory, MemoryPipelineChannelFactory and PipelineSQLBuilderFactory

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15702]
Hi community,

### Aim
Add unit test for `PositionInitializerFactory`, `MemoryPipelineChannelFactory` and `PipelineSQLBuilderFactory` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by varsha089** [comment]
Hi, I am Varsha, a contributor to OpenForce 2022. I would like to work on this issue. Please guide me on how to proceed in this issue, I know basic Java and SQL.

**Comment by sandynz** [comment]
Hi @varsha089 , welcome!

Knowing basic Java and SQL is enough to contribute on this issue. You could have a look at [Contributor Guide]( https://shardingsphere.apache.org/community/en/contribute/contributor/ ) and [Set Up Env]( https://shardingsphere.apache.org/community/en/contribute/establish-project/ ) firstly.

**Comment by varsha089** [comment]
Thank you so much

**Comment by sandynz** [comment]
Hi @varsha089 , is there any updates on this issue? Feel free to leave comment here if you have any question.

**Comment by sandynz** [comment]
@varsha089 , that's OK.
Maybe there're too much classes need to add unit test, I could separate it as several issues.
Which one are you doing? I'll keept it here.

**Comment by terrymanu** [comment]
@varsha089 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by TeslaCN** [comment]
Close via #19286.
