### ISSUE TITLE
Add unit test for InsertCipherNameTokenGenerator

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#15700]
Hi community,

### Aim
Add unit test for `InsertCipherNameTokenGenerator`.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Example FYI
- `EncryptProjectionTokenGeneratorTest`

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by varsha089** [comment]
Hi, I am Varsha, a contributor to OpenForce 2022. I would like to work on this issue. Please guide me on how to proceed on this issue I am familiar with basic java and SQL.

**Comment by menghaoranss** [comment]
@varsha089 welcome

**Comment by terrymanu** [comment]
@varsha089 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by sgunadhya** [comment]
Hi I am Sushant; I would like to work on this issue.
