### ISSUE TITLE
[OpenForce 2022] Add unit test for MySQLInventoryDumper

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15707]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `MySQLInventoryDumper` in `shardingsphere-data-pipeline-mysql` module, doesn't include parent class methods.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by pparthenhs** [comment]
Dear @sandynz, 

I would like to collaborate on this issue. After some investigation, found that the class MySQLInventoryDumper is coved from unit tests.

![image](https://user-images.githubusercontent.com/9752042/159447676-bfa78f34-975c-4d46-bcbc-695753a12a4f.png)

So I think you could close the current issue.

Thank you in advance for your time, and contribution. I remain always at your disposal.

Best regards, 
Panagiotis Parthenis

**Comment by tain198127** [comment]
assign me
