### ISSUE TITLE
[OpenForce 2022] Add unit test for EncryptAssignmentTokenGenerator

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#15701]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `EncryptAssignmentTokenGenerator`.

### Basic Qualifications
- Java
- Maven
- Junit.Test

### Example FYI
- `EncryptProjectionTokenGeneratorTest`

**Comment by pparthenhs** [comment]
Hello @menghaoranss, I can work on this issue.

**Comment by yx9o** [comment]
@pparthenhs Welcome.

**Comment by pparthenhs** [comment]
Hello @yx9o, the issue is ready. Please let me know of any code review comments.

Best regards, 
Panagiotis Parthenis
