### ISSUE TITLE
[OpenForce 2022]  Add `spi-based-sharding-spring-boot-mybatis-example` for `spi-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15719]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

[spi-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and configure it using  [SPI (Service Provider Interface)](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html).

### Aim

Add `spi-based-sharding-spring-boot-mybatis-example` for `spi-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-boot-mybatis-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-mybatis-example)

**Comment by susongyan** [comment]
may i take this task?

**Comment by strongduanmu** [comment]
@susongyan Welcome, I will assign this issue to you.
