### ISSUE TITLE
Add raw java example to `class-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15712]
Hi community,

### Background

[class-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and declare the configuration using `CLASS_BASED` (avoid using SPI extensions)

### Aim

Add raw java example to `class-based-sharding-algorithm-example` (in sub-module `class-based-sharding-raw-jdbc-example`)

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-raw-jdbc-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example)

**Comment by Swastyy** [comment]
Hi @RaigorJiang , I want to do this one under OpenForce 😃 . Thanks.

**Comment by yx9o** [comment]
@Swastyy Hi, nice to see you again.
assigned to you.

**Comment by Swastyy** [comment]
Hi @RaigorJiang @yx9o , in this I have to create a module `class-based-sharding-algorithm-example` inside `class-based-sharding-raw-jdbc-example` ([here](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example/class-based-sharding-raw-jdbc-example))
Correct me if I am wrong.

**Comment by Swastyy** [comment]
Hey @RaigorJiang , I cannot comment on the PR, I have understood it, and used `ShardingRawJavaConfigurationExample.java` for reference. Let me know if the configuration is not correctly used. Thanks.

**Comment by Swastyy** [comment]
Hey @RaigorJiang , can you provide an example when the sharding algorithm in datasource is configured as custom algorithm?

**Comment by RaigorJiang** [comment]
> Hey @RaigorJiang , can you provide an example when the sharding algorithm in datasource is configured as custom algorithm?

OK, I will update later.

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Here are some instructions and sample snippets:
1. Startup class
   Reference to: `org.apache.shardingsphere.example.sharding.raw.jdbc.ShardingRawJavaConfigurationExample`
2. DataSourceFactory
   Reference to: `org.apache.shardingsphere.example.sharding.raw.jdbc.factory.DataSourceFactory`
3. DataSourceConfiguration
   Reference to: `org.apache.shardingsphere.example.sharding.raw.jdbc.config.ShardingDatabasesConfigurationPrecise`

Application:
- In ShardingDatabasesConfigurationPrecise:
```java
private ShardingRuleConfiguration createShardingRuleConfiguration() {
        ShardingRuleConfiguration result = new ShardingRuleConfiguration();
        ...
        result.setDefaultDatabaseShardingStrategy(new StandardShardingStrategyConfiguration("user_id", "inline"));
        Properties props = new Properties();
        props.setProperty("algorithm-expression", "demo_ds_${user_id % 2}");
        result.getShardingAlgorithms().put("inline", new ShardingSphereAlgorithmConfiguration("INLINE", props));
        ...
        return result;
    }
```
The `new ShardingSphereAlgorithmConfiguration` specifies the use of the `INLINE` algorithm, and passes in a property containing "algorithm-expression" as a parameter. In the algorithm map, the key is also `inline`.
At the same time, a `StandardShardingStrategyConfiguration` is created in `defaultDatabaseShardingStrategy`, and `inline` (here is the key of map) is applied.


- Custom Algorithm:

Take `org.apache.shardingsphere.example.extension.classbased.sharding.raw.jdbc.fixture.ClassBasedStandardShardingAlgorithmFixture` as an example, it accepts a parameter "sharding-count" to calculate sharding count:
```java
@Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Integer> shardingValue) {
        for (String each : availableTargetNames) {
            if (each.endsWith(String.valueOf(shardingValue.getValue() % shardingCount))) {
                return each;
            }
        }
        return null;
    }
```

In the new `ShardingDatabasesConfigurationPrecise`, we can define:
````java
private ShardingRuleConfiguration createShardingRuleConfiguration() {
        ShardingRuleConfiguration result = new ShardingRuleConfiguration();
        ...
        result.setDefaultDatabaseShardingStrategy(new StandardShardingStrategyConfiguration("user_id", "custom"));
        Properties props = new Properties();
        props.setProperty("strategy", "standard");
        props.setProperty("algorithmClassName", "org.apache.shardingsphere.example.extension.classbased.sharding.raw.jdbc.fixture.ClassBasedStandardShardingAlgorithmFixture");
        props.setProperty("sharding-count", "4");
        result.getShardingAlgorithms().put("custom", new ShardingSphereAlgorithmConfiguration("CLASS_BASED", props));
        ...
        return result;
    }

````

illustrate:
- Because `ClassBasedStandardShardingAlgorithmFixture` implements `StandardShardingAlgorithm`, the strategy in props is `standard`;
- `algorithmClassName` is used to specify the custom algorithm to use;
- `sharding-count` is a parameter required by the algorithm.

The other parts are basically the same as the `sharding-raw-jdbc-example`.

**Comment by terrymanu** [comment]
@Swastyy Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by lushaorong** [comment]
I want to try this work
