### ISSUE TITLE
Optimize configuration for privilege provider `DATABASE_PERMITTED`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15711]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441).

### Background

[SCHEMA_PRIVILEGES_PERMITTED](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/yaml-config/authentication/#schema_privileges_permitted) is a privilege provider provided by ShardingSphere, which allows administrators to grant access rights to different schemas for different users. But:

- If a user has authorization for multiple schemas, the enumeration configuration is verbose
- If a user has access to all schemas, also need to enumerate each one

### Aim

- [ ] Optimize the configuration of `SCHEMA_PRIVILEGES_PERMITTED` to improve the experience of configuring multiple schemas for one user

- [ ] All schemas can be granted to a user in the form of `*`

- [ ] Update `SchemaPrivilegesPermittedAuthorityProviderAlgorithmTest`

### Basic Qualifications

- Java
- Maven
- Junit.Test

**Comment by utkershrajvenshi** [comment]
Hi @RaigorJiang 
I wish to contribute to this issue under OpenForce 2022 and want to clarify some doubts for this ticket...

**Comment by RaigorJiang** [comment]
Hi @utkershrajvenshi 
Welcome to Apache ShardingSphere, which part do you have questions about?

**Comment by utkershrajvenshi** [comment]
I need to know if I need to optimize SchemaPrivilegesPermittedAuthorityProviderAlgorithm.java file here( shardingsphere-kernel/shardingsphere-authority/shardingsphere-authority-core/src/main/java/org/apache/shardingsphere/authority/provider/schema/SchemaPrivilegesPermittedAuthorityProviderAlgorithm.java )

Or I need to optimize the configuration in the docs' authentication.en.md here( docs/document/content/user-manual/shardingsphere-proxy/yaml-config/authentication.en.md )

**Comment by RaigorJiang** [comment]
Hi @utkershrajvenshi 
The files you pointed out are absolutely correct, including the java files and documentation.
In fact, there are three other files that need to be adjusted accordingly:
- `SchemaPrivilegeBuilder.java`
It builds userPrivilegeMap based on configuration in props
- `SchemaPrivilegesPermittedShardingSpherePrivileges.java`
Its methods are used to determine whether the user has the corresponding privileges.
- `SchemaPrivilegesPermittedAuthorityProviderAlgorithmTest.java`
Test cases for `SchemaPrivilegesPermittedAuthorityProviderAlgorithm`.

**Comment by utkershrajvenshi** [comment]
Great! Thanks for clearing it up @RaigorJiang 
I wish to work on this issue so could you please assign it to me?

**Comment by utkershrajvenshi** [comment]
Also, could you please share your Slack id so I can ping you there for possibly further questions on this ticket...

**Comment by RaigorJiang** [comment]
Okey,  I am in the channel `openforce2022` of Apache ShardingSphere, you can search `Raigor Jiang` to find me there. 😁

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by runqi-zhao** [comment]
@RaigorJiang 你好，Hi, I didn't find SchemaPrivilegesPermittedAuthorityProviderAlgorithm and related configuration in this version, can you tell me where it was moved to?

**Comment by RaigorJiang** [comment]
Hi @runqi-zhao 
It is named `DATABASE_PERMITTED` for now, please refer to:
https://shardingsphere.apache.org/document/current/en/dev-manual/proxy/
