### ISSUE TITLE
Add `class-based-sharding-spring-namespace-jpa-example` for `class-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15715]
Hi community,

### Background

[class-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and declare the configuration using `CLASS_BASED` (avoid using SPI extensions)

### Aim

Add `class-based-sharding-spring-namespace-jpa-example` for `class-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-namespace-jpa-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-namespace-jpa-example)

**Comment by neoneww** [comment]
may i take this?

**Comment by aniketh-varma** [comment]
Hi, I am a contributor to OpenForce 2022. I would like to work on this issue.

**Comment by strongduanmu** [comment]
> may i take this?

@neoneww Welcome, I will assign this issue to you.

**Comment by strongduanmu** [comment]
> Hi, I am a contributor to OpenForce 2022. I would like to work on this issue.

Hi @aniketh-varma, since @neoneww claimed this issue first, you are welcome to claim other OpenForce issues.

**Comment by RaigorJiang** [comment]
Hi @neoneww , any update?

**Comment by terrymanu** [comment]
@neoneww Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by RaigorJiang** [comment]
Hi @Rohitpandey357 
Welcome to ShardingSphere community.

For this issue, there are already some completed modules, you can refer to:
- [class based](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example)
- [spi based](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example)
