### ISSUE TITLE
[OpenForce 2022]  Add `class-based-sharding-spring-namespace-mybatis-example` for `class-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15716]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

[class-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and declare the configuration using `CLASS_BASED` (avoid using SPI extensions)

### Aim

Add `class-based-sharding-spring-namespace-mybatis-example` for `class-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-namespace-mybatis-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-namespace-mybatis-example)

**Comment by susongyan** [comment]
may i take this?

**Comment by RaigorJiang** [comment]
@susongyan Welcome.
