### ISSUE TITLE
[OpenForce 2022]  Add `spi-based-sharding-spring-boot-jpa-example` for `spi-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15718]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

[spi-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and configure it using  [SPI (Service Provider Interface)](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html).

### Aim

Add `spi-based-sharding-spring-boot-jpa-example` for `spi-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-boot-jpa-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-jpa-example)

**Comment by yx9o** [comment]
@RakeshPotnuru Welcome, assigned to you.

**Comment by RakeshPotnuru** [comment]
Hi @RaigorJiang, @yx9o 
Can you guide me a little on this issue?

**Comment by RaigorJiang** [comment]
@RakeshPotnuru 
Sure, which part do you have questions about?

**Comment by RakeshPotnuru** [comment]
@RaigorJiang 
Can you give more details about this issue? I am first time contributing to this project.

**Comment by RaigorJiang** [comment]
@RakeshPotnuru 
Did you clone the project? 
Open the example project with the IDE and find the example module given in the description.
You will find that there is only one java-raw access example under `spi-based-sharding-algorithm-example`. 
In fact, ShardingSphere supports multiple access ways. For more infor, you can refer to the module module `sharding-spring-boot-jpa-example`.

**Comment by RaigorJiang** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/5668787/156889498-5b708aea-a63f-4366-9a22-1a197ed09981.png">
