### ISSUE TITLE
Add raw java example for `spi-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15717]
Hi community,

### Background

[spi-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and configure it using  [SPI (Service Provider Interface)](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html).

### Aim

Add raw java example for `spi-based-sharding-algorithm-example` (in sub-module `spi-based-sharding-raw-jdbc-example`)

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-raw-jdbc-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example)

**Comment by afreenabegum** [comment]
Hi @RaigorJiang .
I would like to work on this issue. Can you assign it to me !!

Thank you.

**Comment by yx9o** [comment]
@afreenabegum Welcome, assigned to you.

**Comment by Kamalesh3112** [comment]
Hi @RaigorJiang 
With your kind permission , I could be great to work on this issue .
Can you assign this issue to me ?

**Comment by RaigorJiang** [comment]
Hi @Kamalesh3112 
Thanks for your attention, but this issue has been assigned to @afreenabegum, let's give him more time to fix it.
Maybe you can take a look at other issues, and I will also add more issues for example project.

**Comment by Kamalesh3112** [comment]
That's fine @RaigorJiang . No issues , let the person can solve . Sure that's great

**Comment by aaryan078** [comment]
Hi, I am aaryan, a contributor to OpenForce 2022. I would like to work on this issue

**Comment by RaigorJiang** [comment]
OK! @aaryan078 
Because @afreenabegum removed the assignment before,  you can take it now.

**Comment by terrymanu** [comment]
@aaryan078 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by lushaorong** [comment]
I would like to work on this issue. Can you assign it to me !!

**Comment by RaigorJiang** [comment]
@lushaorong Welcome!

**Comment by lushaorong** [comment]
I'm a little confused. There are already a class `SPIBasedShardingRawYamlConfigurationExample`  in sub-module `spi-based-sharding-raw-jdbc-example` and a user-defined sharding algorithm and configure it using SPI. So what can I do?

**Comment by lushaorong** [comment]
> @lushaorong Welcome!

I'm a little confused. There are already a class SPIBasedShardingRawYamlConfigurationExample in sub-module spi-based-sharding-raw-jdbc-example and a user-defined sharding algorithm and configure it using SPI. So what can I do?

**Comment by RaigorJiang** [comment]
Hi @lushaorong 
For `spi-based-sharding-algorithm-example`, there is just a `RawYamlConfigurationExample`  ([link](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example/spi-based-sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/extension/spibased/sharding/raw/jdbc))

We need another `RawJavaConfigurationExample`, you can refer to [here](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/sharding/raw/jdbc).

**Comment by lushaorong** [comment]
Hi @RaigorJiang 
Maybe I can also refer to [ShardingSphere-JDBC > Java API](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/java-api/) . Am I right?

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang Maybe I can also refer to [ShardingSphere-JDBC > Java API](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/java-api/) . Am I right?

Of course, the documentation can help you understand what the configuration item means.
