### ISSUE TITLE
Add `class-based-sharding-spring-boot-jpa-example` to `class-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15713]
Hi community,

### Background

[class-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/class-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and declare the configuration using `CLASS_BASED` (avoid using SPI extensions)

### Aim

Add `class-based-sharding-spring-boot-jpa-example` for `class-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-boot-jpa-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-jpa-example)

**Comment by ankitadam** [comment]
Hii, I am a beginner. I know only basics of Java. Will I be able to work on this?

**Comment by RaigorJiang** [comment]
Hi @ankitadam 
Thank you for your attention.
This issue only requires basic java programming skills (because a lot of code can be copied), in fact, just add a maven submodule, and copy some code and configuration with reference to the example

**Comment by ankitadam** [comment]
> Hi @ankitadam Thank you for your attention. This issue only requires basic java programming skills (because a lot of code can be copied), in fact, just add a maven submodule, and copy some code and configuration with reference to the example

Ok got it, I would like to work on it. Please assign it to me.

**Comment by RaigorJiang** [comment]
Hi @ankitadam , any update?

**Comment by terrymanu** [comment]
@ankitadam Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.
