### ISSUE TITLE
[OpenForce 2022] Add unit test for StandardPipelineDataSourceConfiguration

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#15710]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim
Add unit test for `StandardPipelineDataSourceConfiguration` in `shardingsphere-pipeline-test` module.

### Basic Qualifications
- Java
- Maven
- Junit.Test

**Comment by yx9o** [comment]
@pparthenhs Welcome, assigned to you.

**Comment by sandynz** [comment]
Welcome!
