### ISSUE TITLE
Add `spi-based-sharding-spring-namespace-mybatis-example` for `spi-based-sharding-algorithm-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15721]
Hi community,

### Background

[spi-based-sharding-algorithm-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example/spi-based-sharding-algorithm-example) is an example of a custom algorithm that demonstrates how to integrate a user-defined sharding algorithm and configure it using  [SPI (Service Provider Interface)](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html).

### Aim

Add `spi-based-sharding-spring-namespace-mybatis-example` for `spi-based-sharding-algorithm-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [sharding-spring-namespace-mybatis-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-namespace-mybatis-example)

**Comment by aniketh-varma** [comment]
Hi, I am a part of OpenForce 2022. I would like to work on this issue.

**Comment by strongduanmu** [comment]
@aniketh-varma Welcome, I will assign this issue to you.

**Comment by Swastyy** [comment]
Hi @aniketh-varma Are you still working on this? If not, I will do it. Let me know, thanks.

**Comment by aniketh-varma** [comment]
Hi @Swastyy, Yes I am working on the issue and will make a PR in the coming week. Sorry for the delay. Thanks!

**Comment by terrymanu** [comment]
@aniketh-varma Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try
