### ISSUE TITLE
can't connection database

### ISSUE THREAD

**Issue by Xasperfect** [apache/shardingsphere#15724]
our project use  mycat for Split database. then wo use sharding-jdbc connection mycat ,and prompt error.
error message：
          caused by: java.SQLException:ResultSet is from update.No Data

but our database has lots of data.

I can't upload photoes for company's projects ，I‘m sorry. I hope get your help.

I will provide more information tomorrow

**Comment by TeslaCN** [comment]
ShardingSphere-JDBC connects database via official MySQL JDBC connector. Could you make sure whether the MyCAT implemented MySQL protocol correctly?

**Comment by terrymanu** [comment]
I close the issue because of no response anymore.
