### ISSUE TITLE
[OpenForce 2022]  Add SQL parser test case for `ShowScalingStatusStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15728]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

`SHOW SCALING STATUS jobId` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `ShowScalingStatusStatement`. Now we need to add a test case for this parsing process to assert that its parsing is correct.

### Aim

Add SQL parser test case for `ShowScalingStatusStatement`.

- Affected files:

  - `SQLParserTestCases` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/query.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/query.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/scaling/ShowScalingStatusStatementTestCase.java` (create )

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/scaling/query/ShowScalingStatusStatementAssert.java` (create )

  - `QueryableScalingRALStatementAssert` (modify)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- `CheckScalingStatement`
- `CheckScalingStatementTestCase`
- `CheckScalingStatementAssert`
- search for "check-scaling"

**Comment by pparthenhs** [comment]
Dear @RaigorJiang, 

I could work on this ! ... I will let you know when it is ready !!

Best regards, 
Panagiotis Parthenis
