### ISSUE TITLE
[OpenForce 2022]  Add SQL parser test case for `DropScalingStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15731]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

`DROP SCALING jobId` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `DropScalingStatement`. Now we need to add a test case for this parsing process to assert that its parsing is correct.

### Aim

Add SQL parser test case for `DropScalingStatement`.

- Affected files:

  - `SQLParserTestCases` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/update.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/update.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/scaling/DropScalingStatementTestCase.java` (create )

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/scaling/update/DropScalingStatementAssert.java` (create )

  - `UpdatableScalingRALStatementAssert` (modify)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- `ApplyScalingStatement`
- `ApplyScalingStatementTestCase`
- `ApplyScalingStatementAssert`
- search for "apply-scaling"

**Comment by pparthenhs** [comment]
Dear @RaigorJiang , 

I start working on this issue. 

I will let you know when I am finished.

Best regards, 
Panagiotis Parthenis
