### ISSUE TITLE
Please support database dameng and kingbase

### ISSUE THREAD

**Issue by chrvip** [apache/shardingsphere#15738]
### Is your feature request related to a problem?
Dameng and kingbase is more and more popular in China. Our clients asked us to use these databases that they had bought.
Dameng: https://www.dameng.com/
Kingbase: https://www.kingbase.com.cn/

### Describe the feature you would like.
Support most of features as for  MySQL.

**Comment by RaigorJiang** [comment]
Hi @chrvip 
They are compatible with the MySQL protocol, so you can perform some tests and submit specific issues if there is any incompatibility.

**Comment by terrymanu** [comment]
No plan to support not open sourced database
