### ISSUE TITLE
[OpenForce 2022]  Add SQL parser test case for `ResetScalingStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15733]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

`RESET SCALING jobId` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `ResetScalingStatement`. Now we need to add a test case for this parsing process to assert that its parsing is correct.

### Aim

Add SQL parser test case for `ResetScalingStatement`.

- Affected files:

  - `SQLParserTestCases` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/update.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/update.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/scaling/ResetScalingStatementTestCase.java` (create)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/scaling/update/ResetScalingStatementAssert.java` (create)

  - `UpdatableScalingRALStatementAssert` (modify)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- `ApplyScalingStatement`
- `ApplyScalingStatementTestCase`
- `ApplyScalingStatementAssert`
- search for "apply-scaling"

**Comment by pparthenhs** [comment]
Dear @Raigor, 

My name is Panagiotis Parthenis and I am a software engineer. I would like to put my knowledge to good use and contribute to an open-source project. 

This is my first try !!! 

I will try my best to offer something valuable to the community. 

I remain always at your disposal.

Best regards, 
Panagiotis Parthenis

**Comment by RaigorJiang** [comment]
Hi @pparthenhs 
Thank you for your interest in ShardingSpherer, do you want to participate in this issue?
I will try my best to help if needed.
