### ISSUE TITLE
`CREATE SHARDING TABLE RULE`  syntax parsing inline expression exception, missing inner single quotes

### ISSUE THREAD

**Issue by Huletian** [apache/shardingsphere#15759]
## Bug Report
When using distsql to create standard table rules, parsing errors will occur when the inline expression in distsql enumerates the resources of character types .
The following is distsql I used when I created it:

create sharding table rule ed_school (
datanodes("ds_${['bnds','bndsly']}.ed_school"),
database_strategy(
	type=standard,
	sharding_column=school_code,
	sharding_algorithm(TYPE(NAME=inline,PROPERTIES("algorithm-expression"="ds_${school_code}")))
)
);

**Comment by lanchengx** [comment]
@Huletian Thanks your feedback ,  I will check
