### ISSUE TITLE
whether to support nested queries or sub queries for split tables? Version 5.1.0

### ISSUE THREAD

**Issue by xfzhaoGit** [apache/shardingsphere#15764]
SELECT
    IFNULL(a.signOneInTime, ''),
    IFNULL(b.signOneOutTime, '')
FROM
    (
        SELECT
            sum(sign_time) AS signOneInTime,
            date_str
        FROM
            original_sign_record  <!— no Slice table-->
        WHERE
            emp_id = ?
        AND sign_time < ?
        AND sign_time > ?
    ) a
LEFT JOIN (
    SELECT
        sum(sign_time) AS signOneOutTime,
        date_str
    FROM
        original_sign_record <!— Slice table —>
    WHERE
        emp_id = ?
    AND sign_time < ?
    AND sign_time > ?
) b ON a.date_str = b.date_str

original_sign_record，sum(sign_time)=1000
original_sign_record2022 sum(sign_time)=500
same conditions：sign_time，scan all tables

expect：
signOneOutTime=1500

actual：
occasionally signOneOutTime=1000，Occasional appearance  signOneOutTime=500

**Comment by xfzhaoGit** [comment]
sharding-jdbc 5.1.0

**Comment by terrymanu** [comment]
What is your configuration?

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
