### ISSUE TITLE
HashModShardingAlgorithm getShardingCount() throw a NumberFormatException

### ISSUE THREAD

**Issue by qiaoheng110** [apache/shardingsphere#15769]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
HashModShardingAlgorithm can correct parsing of the sharding-count property
### Actual behavior
throw a java.lang.NumberFormatException: null
### Reason analyze (If you can)
JDK1.8 Properties.getProperty(String key) only return value of type string, otherwise return null 

HashModShardingAlgorithm
<img width="850" alt="image" src="https://user-images.githubusercontent.com/20252910/156500592-c30af024-d2a5-4504-a2af-2deda872f72a.png">
Properties
<img width="650" alt="image" src="https://user-images.githubusercontent.com/20252910/156500627-969ecec5-e644-4aa3-bc61-e2ebc9091597.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/20252910/156500689-b2c954a2-b336-48e7-8b1c-351d353640cd.png">

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/20252910/156500723-8904649d-913c-43e5-b770-0ff551f83082.png">

### Example codes for reproduce this issue (such as a github link).
if i config like this, it can work correctly

<img width="283" alt="image" src="https://user-images.githubusercontent.com/20252910/156500840-57f9217e-f7c7-4ddb-9107-758467c53f1f.png">

**Comment by strongduanmu** [comment]
@qiaoheng110 Thank you for your feedback, I will check this issue.
