### ISSUE TITLE
Grammar error in a documentation

### ISSUE THREAD

**Issue by hizem** [apache/shardingsphere#15774]
While I was reading the documentation on the official website I noticed a grammar mistake in the **Concepts - Adaptor - ShardingSphere-Proxy** part, I'am willing to contribute to the project thus I created this issue hoping that will be assigned to me as a good first issue.
To correct the mistake you just need to replace **compatible of** with **compatible with** that's all.
The image attached demonstrates the mistake : 
<img width="1242" alt="Screen Shot 2022-03-03 at 10 17 34 AM" src="https://user-images.githubusercontent.com/32454249/156536315-b692038f-39d4-41e8-ad80-095d0a20952a.png">

**Comment by nitishsaini706** [comment]
@hizem Are you still working on this ?

**Comment by hizem** [comment]
> @hizem Are you still working on this ?

@nitishsaini706  yes I'm working on it

**Comment by yx9o** [comment]
Fixed by #15788 .
