### ISSUE TITLE
There is LOCATION,PARENT etc in Oracle SQL, then prompt You have an error in your SQL syntax.

### ISSUE THREAD

**Issue by XuHaijwill** [apache/shardingsphere#15781]
My contains the fields LOCATION,PARENT, and the program reported an error.

My Eventment is
shardingsphere 5.1.0(spring-boot-start)
mybaits
Oracle 19c
Java 1.8

sql is:**select location,parent from organization**

**Comment by XuHaijwill** [comment]
Hi team,Why can't location and pareant be queried as field names in Oracle?

**Comment by terrymanu** [comment]
It seems like oracle parse problem, does anyone want to fix it?

**Comment by tianhao960** [comment]
I would like to take this.

**Comment by strongduanmu** [comment]
@tianhao960 Welcome.
