### ISSUE TITLE
Federation cannot cast tinyint

### ISSUE THREAD

**Issue by weiboboCN** [apache/shardingsphere#15782]
version:5.1.0 release shardingsphere.
 other  framework :mybatis.

sql:
select c.id as companyId ,p.id as projectId ,c.name as companyName,p.name as projectName from company c,project p where c.project_id = p.id and c.state=0;

c.state is defined as tinyint.
project is defined as  **single table**

exception:
java.sql.SQLException: Internal error: exception while executing query: class java.lang.Integer cannot be cast to class java.lang.Byte (java.lang.Integer and java.lang.Byte are in module java.base of loader 'bootstrap')

**Comment by RaigorJiang** [comment]
Fixed by #21954.
