### ISSUE TITLE
OracleStatement can't parse alise with 'T'

### ISSUE THREAD

**Issue by YoungHu** [apache/shardingsphere#15789]
## Bug Report

when test oracle sql parse got error. sql text `SELECT NULLIF(T.USER_NO, 'NULL') FROM T_RATION_INFO T`. 
if change to low cause character `select nullif(t.user_no, 'null') from t_ration_info t`, parse ok.  
what's the problem?

### Which version of ShardingSphere did you use?
5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
parse without exception

### Actual behavior
throw parse exception

### Reason analyze (If you can)
no idea

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
`new SQLVisitorEngine(databaseType, "STATEMENT", new Properties()).visit(new SQLParserEngine("Oracle", new CacheOption(128,1024L,4), true).parse('SELECT NULLIF(T.USER_NO, 'NULL') FROM T_RATION_INFO T', false));`

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?
