### ISSUE TITLE
Cross database query ,prompt: not support schme

### ISSUE THREAD

**Issue by secondchilde** [apache/shardingsphere#15791]
## Question

When I execute a cross database query . Cross database query tables are two tables of different databases without sub tables

DataBase:  db_puxian_promotion
slice : t_scan_task_number
query: t_activity_limit
DataBase: db_pixiu_order
no slice;
query:t_trade_order、t_trade_order_item

sql:
`
  SELECT
	  COUNT( 1 ) 
  FROM
	  db_pixiu_order.t_trade_order tto
	  LEFT JOIN db_pixiu_order.t_trade_order_item toi ON toi.order_id = tto.id
	  LEFT JOIN db_puxian_promotion.t_activity_limit tal ON tal.activity_id = toi.activity_id 
  WHERE
	  limit_param = 'end_date' 
  AND limit_value < now()
`

Prompt: not support schme ...

I can't remember the question clearly. It's best if I can answer it. Thank you
**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by judykula** [comment]
mark

**Comment by terrymanu** [comment]
What is your version?

**Comment by terrymanu** [comment]
Closed because of no feedback anymore
