### ISSUE TITLE
sharding5.0 memory take up too much

### ISSUE THREAD

**Issue by zhao190775705** [apache/shardingsphere#15792]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc
### Actual behavior
Before the project memory 3GB now 6G
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/43293476/156718909-d4878dbe-cad8-408d-afdb-a6b170d6cefd.png)
![image](https://user-images.githubusercontent.com/43293476/156719026-ac766cec-26e2-4546-91be-7217cdddf5a1.png)

sharding some components memory take up too much

prod question very urgent
Looking forward to your reply

**Comment by TeslaCN** [comment]
It seems the instances are quite a log but the shallow size is not very large. Could you show us the retained size and provides some configurations?

**Comment by zhao190775705** [comment]
What configuration do I need？
sharding?
Only when business is busy memory take up too much
I can't reproduce the problem locally
Memory snapshots can be provided
Does it work for you ？

You' ve had a long day.

**Comment by zhao190775705** [comment]
![image](https://user-images.githubusercontent.com/43293476/156910753-1c308b5b-93b6-4d4b-91d7-9591a7e82985.png)
I'm trying to change this file
Would it be all right?

**Comment by TeslaCN** [comment]
SQL parser cache can be configured since 5.1.0.
https://shardingsphere.apache.org/document/5.1.0/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-parser/

**Comment by TeslaCN** [comment]
> What configuration do I need？ sharding? Only when business is busy memory take up too much I can't reproduce the problem locally Memory snapshots can be provided Does it work for you ？
> 
> You' ve had a long day.

It would be helpful if you can provide the heap dump file.

**Comment by zhao190775705** [comment]
I know this is not a good method of transmission.......bother you
send  wuweijie@apache.org, please check it email

**Comment by zhao190775705** [comment]
I want to know “ParameterMarkerExpressionSegment” this class to do with？
I wonder if it is possible that the parsing SQL failed？
I'm not good enough to test some hypothesis

**Comment by TeslaCN** [comment]
Hi @zhao190775705 
I've checked your heap dump and found that the caches of SQL parser retained hundreds of megabytes memory, especially some SQLs are very large.

![image](https://user-images.githubusercontent.com/20503072/157172417-80310aeb-17ed-4938-a8a2-7fa81db104ee.png)

![image](https://user-images.githubusercontent.com/20503072/157172527-095b6a90-38df-4141-a17c-acd4fa33db77.png)

Fortunately, the ShardingSphere 5.1.0 supports configuring SQL parse caches in rules. Please refer to:
https://shardingsphere.apache.org/document/5.1.0/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-parser/

**Comment by zhao190775705** [comment]
![image](https://user-images.githubusercontent.com/43293476/157186769-4974e141-a57f-43c9-b748-1ba1a85fd81d.png)
I'm trying to build the source code to change the size here？
but it didn't work out that way。
I need your help

**Comment by zhao190775705** [comment]
The problem is only on the line。
We were afraid of other problems after the upgrade？ 
Let's see if there's another solution
thank you

**Comment by TeslaCN** [comment]
> ![image](https://user-images.githubusercontent.com/43293476/157186769-4974e141-a57f-43c9-b748-1ba1a85fd81d.png) I'm trying to build the source code to change the size here？ but it didn't work out that way。 I need your help

How long is your SQL? If the SQL string took about 3MB, each cache entry which contains key and value will take about 10MB.

**Comment by zhao190775705** [comment]
We set the cache capacity to a smaller value？
What are some of the consequences。
Does it have a significant performance impact？

**Comment by TeslaCN** [comment]
> We set the cache capacity to a smaller value？ What are some of the consequences。 Does it have a significant performance impact？

It may take more time on parsing SQL if you reduce the max size.

**Comment by zhao190775705** [comment]
ok I know，We try to change sql tomorrow See if it works。
We found that the SQL was probably too long

**Comment by zhao190775705** [comment]
my advice key not use string ，the algorithm is used to convert to int？
Could this be a better option？

**Comment by TeslaCN** [comment]
The key is the SQL. What if different SQL have same result?

> cache key not use string ，the algorithm is used to convert to int？ Could this be a better option？

**Comment by zhao190775705** [comment]
If the result is the same, does the cache store a copy

**Comment by zhao190775705** [comment]
It's stable now，batch insert？
Does the cache store multiple copies of a different number of inserts in a batch？

**Comment by TeslaCN** [comment]
> It's stable now
> batch insert ， different number of inserts，cache how to store

It depends on how you do the batched inserts. If the SQLs are different, all SQLs will be cached.

**Comment by zhao190775705** [comment]
insert sql don't cache, yes or no？
The only problem now is that there are too many batch insert cache SQL

**Comment by TeslaCN** [comment]
> insert sql don't cache, yes or no？ The only problem now is that there are too many batch insert cache SQL

The SQL will be cached if you use the PreparedStatement.

**Comment by TeslaCN** [comment]
Close due to no response.
