### ISSUE TITLE
query result bug

### ISSUE THREAD

**Issue by xfzhaoGit** [apache/shardingsphere#15798]
## Bug Report

**For English only**, other languages will not accept.
.org/document/current/en/overview).

SELECT
b.id,
a.name,
IFNULL(b.signTime, ''),
date_str dateStr
FROM
user a
LEFT JOIN (
SELECT
sum(sign_time) AS signTime,
date_str,
user_id,
FROM
user_sign_record <!— Slice table —>
WHERE
user_id = ?
GROUP BY date_str
) b ON a.id = b.user_id
ORDER BY a.name

user:
id | name
---|---
1 | zhangsan
2 | lisi

user_sign_record
id | user_id | sign_time| date_str
---|---|---|---
1 | 1 | 1000|2022-03-04
2 | 2 | 1000|2022-03-04

user_sign_record2022
id | user_id | sign_time| date_str
---|---|---|---
1 | 1 | 500|2022-03-04
2 | 2 | 500|2022-03-04

`create_date`  is sharding key,  this sql is all tables scans.

expectd：
id | name |dateStr| signTime
---|---|---|---
1 | zhangsan|2022-03-04 | 1500
2 | lisi |2022-03-04| 1500

actual：
id | name | dateStr| signTime
---|---|---|---
1 | zhangsan|2022-03-04 | 1000
2 | lisi|2022-03-04 | 1000

or

id | name | dateStr| signTime
---|---|---|---
1 | zhangsan|2022-03-04 | 500
2 | lisi|2022-03-04 | 500

### Which version of ShardingSphere did you use?
5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

**Comment by strongduanmu** [comment]
Hi @xfzhaoGit, thank you for your feedback, can you open `sql-federation` for this query?

**Comment by xfzhaoGit** [comment]
Yes, sql-show is true and Confirm to scan all tables. 

Is it because this SQL is not supported？

And my configuration is on the intranet and I can't upload the value GitHub，sorry。

**Comment by xfzhaoGit** [comment]
open fedreation sql is error！

My configuration is on the intranet, and GitHub is not easy to upload. Can I add wechat group?

**Comment by strongduanmu** [comment]
> open fedreation sql is error！
> 
> My configuration is on the intranet, and GitHub is not easy to upload. Can I add wechat group?

@yang-7777 Yes, you can send wechat number to my email——[duanzhengqiang@apache.org](mailto:duanzhengqiang@apache.org)

**Comment by xfzhaoGit** [comment]
Wechat has been sent to your email. Please pull me into SS discussion group. Thank you

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
