### ISSUE TITLE
When sysbench prepare is used，java.lang.NullPointerException：null

### ISSUE THREAD

**Issue by zhaoliansheng2022** [apache/shardingsphere#15799]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

When sysbench prepare is used，java.lang.NullPointerException：null

![bJYtamOwKl](https://user-images.githubusercontent.com/98297067/156775281-5f5b61c9-2246-44b6-9aa6-d8a7c2229924.png)

config-readwrite-splitting.yaml

schemaName: sbtest

dataSources:
  write_ds:
    url: jdbc:mysql://[127.0.0.1:3306/write_ds?serverTimezone=UTC&useSSL=false](http://127.0.0.1:3306/write_ds?serverTimezone=UTC&useSSL=false)
    username: test
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 2000
    minPoolSize: 1

rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      type: Static
      props:
        write-data-source-name: write_ds
        read-data-source-names: write_ds

**Comment by strongduanmu** [comment]
@zhaoliansheng2022 Thank you for your feedback, I will investigate this issue.
