### ISSUE TITLE
The `ReadwriteSplittingDataSourceRule.getWriteDataSource()` need add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15801]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

ReadwriteSplittingDataSourceRule.getWriteDataSource() need add unit test. I think should be consider `DynamicReadwriteSplittingType` and `StaticReadwriteSplittingType`.

**Comment by Girlwithasmile** [comment]
I am a contributer at openforce 2022 and would like to contribute to this

**Comment by acmenlt** [comment]
You can give it to me, thank you.

**Comment by zjcnb** [comment]
> You can give it to me, thank you.

Welcome, i assigned you @acmenlt.
