### ISSUE TITLE
The `ReadwriteSplittingDataSourceRuleConfiguration` need add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15800]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

`ReadwriteSplittingDataSourceRuleConfiguration` need add some unit test.

- [ ] `ReadwriteSplittingDataSourceRuleConfiguration.getAutoAwareDataSourceName()`
- [ ] `ReadwriteSplittingDataSourceRuleConfiguration.getWriteDataSourceName()`
- [ ] `ReadwriteSplittingDataSourceRuleConfiguration.getReadDataSourceNames()`

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by strongduanmu** [comment]
@shreya024 Welcome, I will assign this issue to you.

**Comment by menghaoranss** [comment]
@shreya024 please refer to `ReadwriteSplittingRuleTest` as an example, just create an object through `new ReadwriteSplittingDataSourceRuleConfiguration`, and then assert whether the value obtained by the above method is the same as you expect
