### ISSUE TITLE
[OpenForce 2022]  Add `shadow-spring-namespace-jpa-example` for `shadow-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15812]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background
What is feature `Shadow`?
https://shardingsphere.apache.org/document/current/en/features/shadow/

[shadow-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/shadow-example) is used to demonstrate how to integrate ShardingSphere-JDBC and enable `shadow`.

Now, it has three sub-modules:

```
<module>shadow-raw-jdbc-example</module>
<module>shadow-spring-boot-mybatis-example</module>
<module>shadow-spring-namespace-mybatis-example</module>
```

### Aim

Add `shadow-spring-namespace-jpa-example` for `shadow-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [Configuration Item Explanation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-namespace/rules/shadow/) 

- [sharding-spring-namespace-jpa-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-namespace-jpa-example)

### Notice
- You need to clone the ShardingSphere project from [here](https://github.com/apache/shardingsphere) first
- In the ShardingSphere directory, `examples` is a separate maven project, you should open `examples` instead of `ShardingSphere` in the IDE.
- Contributor Guide: https://shardingsphere.apache.org/community/en/contribute/contributor/
- Code of Conduct: https://shardingsphere.apache.org/community/en/contribute/code-conduct/

**Comment by soma2000-lang** [comment]
@RaigorJiang  I am working on this issue I am a participant of

**Comment by RaigorJiang** [comment]
Hi @soma2000-lang 
Welcome to Apache ShardingSphere, I will assign it to you.

**Comment by acmenlt** [comment]
@RaigorJiang Can I work on this since No PR had made till now?

**Comment by RaigorJiang** [comment]
> @RaigorJiang Can I work on this since No PR had made till now?

Hi @soma2000-lang , do we need to assign it to @acmenlt ?

**Comment by soma2000-lang** [comment]
Sorry due to some other work I am unable to give a pr .you can assign it to him

**Comment by RaigorJiang** [comment]
Still thank you! @soma2000-lang
