### ISSUE TITLE
Add unit test for TablesContext#findTableNamesByColumnProjection

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15815]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add unit test for TablesContext#findTableNamesByColumnProjection.

- TablesContext#findTableNamesByColumnProjection

**Comment by abhijeetjejurkar** [comment]
Hey,
 Can I try for this issue?

**Comment by strongduanmu** [comment]
@abhijeetjejurkar Welcome, for the first contribution, you can read [code conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) first, it may be helpful to you.

**Comment by abhijeetjejurkar** [comment]
Sure..Thankyou!
