### ISSUE TITLE
Add unit test for EncryptAssignmentTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15818]
Hi community,

We need to add some unit test for EncryptAssignmentTokenGenerator.

- EncryptAssignmentTokenGenerator#isGenerateSQLToken
- EncryptAssignmentTokenGenerator#generateSQLTokens

**Comment by Bhawna-Ad** [comment]
Hey! I am a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by manisha-27** [comment]
Hey @strongduanmu Can I work on this issue under OpenForce'22 ?

**Comment by Ash-KODES** [comment]
Hey,I want work on this issue since no PR had made yet!
#OPENFORCE 2022

**Comment by strongduanmu** [comment]
@manisha-27 @Ash-KODES Welcome, I will assign this issue to you.

**Comment by terrymanu** [comment]
@manisha-27 @Ash-KODES Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by sunkai-cai** [comment]
I am working it

**Comment by strongduanmu** [comment]
Fixed by #15917.
