### ISSUE TITLE
[OpenForce 2022]  Add `encrypt-spring-namespace-jpa-example` for `encrypt-example`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#15811]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

[encrypt-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/encrypt-example) is used to demonstrate how to integrate ShardingSphere-JDBC and [encrypt data](https://shardingsphere.apache.org/document/current/en/features/encrypt/).

Now, it has three sub-modules:

```
<module>encrypt-raw-jdbc-example</module>
<module>encrypt-spring-boot-mybatis-example</module>
<module>encrypt-spring-namespace-mybatis-example</module>
```

### Aim

Add `encrypt-spring-namespace-jpa-example` for `encrypt-example`

### Basic Qualifications

- Java
- Maven

### Example FYI

- [Configuration Item Explanation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-namespace/rules/encrypt/) 
- [sharding-spring-namespace-jpa-example](https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-namespace-jpa-example)

### Notice
- You need to clone the ShardingSphere project from [here](https://github.com/apache/shardingsphere) first
- In the ShardingSphere directory, `examples` is a separate maven project, you should open `examples` instead of `ShardingSphere` in the IDE.
- Contributor Guide: https://shardingsphere.apache.org/community/en/contribute/contributor/
- Code of Conduct: https://shardingsphere.apache.org/community/en/contribute/code-conduct/

**Comment by acmenlt** [comment]
@RaigorJiang Is this question over

**Comment by Akshit42-hue** [comment]
Can I work on this issue @RaigorJiang

**Comment by RaigorJiang** [comment]
Since the PR for this issue has been inactive for more than 10 days, I will assign it to someone else

**Comment by RaigorJiang** [comment]
Hi @Akshit42-hue , @acmenlt requests this issue first, so I just assign it to him, thank you.
