### ISSUE TITLE
Add unit test for ColumnSegment#getExpression

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15816]
Hi community,

We need to add unit test for ColumnSegment#getExpression.

- ColumnSegment#getExpression

**Comment by manisha-27** [comment]
Hey @strongduanmu, Can I work on this issue under OpenForce'22?

**Comment by strongduanmu** [comment]
@manisha-27 Of course, I will assign this issue to you.

**Comment by terrymanu** [comment]
@manisha-27 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.
