### ISSUE TITLE
Add unit test for EncryptForUseDefaultInsertColumnsTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15819]
Hi community,

We need to add unit test for EncryptForUseDefaultInsertColumnsTokenGenerator.

- EncryptForUseDefaultInsertColumnsTokenGenerator#isGenerateSQLToken
- EncryptForUseDefaultInsertColumnsTokenGenerator#generateSQLToken

**Comment by Vaishnavi1411** [comment]
Hi, I am Vaishnavi , a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by manisha-27** [comment]
Hey @strongduanmu Can I work on this issue under OpenForce'22?

**Comment by abhijeetjejurkar** [comment]
Hey, can I work on this? I have already worked on similar issue, https://github.com/apache/shardingsphere/issues/15815

**Comment by strongduanmu** [comment]
Of course @abhijeetjejurkar If @Vaishnavi1411 @manisha-27 haven't started this task.

**Comment by abhijeetjejurkar** [comment]
@Vaishnavi1411 @manisha-27 are you working on this?

**Comment by terrymanu** [comment]
@manisha-27 @abhijeetjejurkar Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by terrymanu** [comment]
The coverage of test cases are not enough, we need to add more test cases.

**Comment by TeslaCN** [comment]
Close via #19394.
