### ISSUE TITLE
Add some unit test for AssistQueryAndPlainInsertColumnsTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15817]
Hi community,

We need to add some unit test for AssistQueryAndPlainInsertColumnsTokenGenerator.

- AssistQueryAndPlainInsertColumnsTokenGenerator#isGenerateSQLToken
- AssistQueryAndPlainInsertColumnsTokenGenerator#generateSQLTokens

**Comment by manisha-27** [comment]
Hey @strongduanmu Can I work on this issue under OpenForce'22?

**Comment by strongduanmu** [comment]
@manisha-27 Of course, assigned.

**Comment by manisha-27** [comment]
Thankyou @strongduanmu
Also I'm a begginer can you guide me how to proceed with the issue.

**Comment by strongduanmu** [comment]
> Thankyou @strongduanmu Also can you guide me how to proceed with the issue.

Hi @manisha-27, you can refer to EncryptAlterTableTokenGeneratorTest, it is a good example.

**Comment by terrymanu** [comment]
@manisha-27 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by quicksandznzn** [comment]
i will finish it.
