### ISSUE TITLE
Add unit test for EncryptInsertOnUpdateTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15820]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add some unit test for EncryptInsertOnUpdateTokenGenerator.

- EncryptInsertOnUpdateTokenGenerator#isGenerateSQLToken
- EncryptInsertOnUpdateTokenGenerator#generateSQLTokens

**Comment by aaryan078** [comment]
Hi, I am aaryan, a contributor to OpenForce 2022. I would like to work on this issue.

**Comment by manisha-27** [comment]
Hey @strongduanmu Can I work on this issue under OpenForce'22 ?

**Comment by abhijeetjejurkar** [comment]
Hey, can I work on this? I have already worked on similar issue, https://github.com/apache/shardingsphere/issues/15815

**Comment by strongduanmu** [comment]
@abhijeetjejurkar Welcome, I will assign this issue to you.

**Comment by iisheng** [comment]
Hello, I would like to have a try

**Comment by strongduanmu** [comment]
@iisheng Welcome.

**Comment by zjcnb** [comment]
It has finished
