### ISSUE TITLE
Add unit test for InsertCipherNameTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15825]
Hi community,

We need to add some unit test for InsertCipherNameTokenGenerator.

- InsertCipherNameTokenGenerator#isGenerateSQLToken
- InsertCipherNameTokenGenerator#generateSQLTokens

**Comment by alceil** [comment]
Hi, I am  Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by strongduanmu** [comment]
> Hey @strongduanmu , I am Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

Welcome @alceil, I will assign this issue to you. For first contribution, you can read [code conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) first, it may be helpful to you.

**Comment by alceil** [comment]
Thanks @strongduanmu

**Comment by alceil** [comment]
Hey @strongduanmu is there any similar test I can refer too to get an idea to solve this issue?

**Comment by strongduanmu** [comment]
Hi @alceil, you can refer EncryptAlterTableTokenGeneratorTest.

**Comment by alceil** [comment]
Where should I place the Test file. Like which folder @strongduanmu

**Comment by strongduanmu** [comment]
@alceil Does this issue has any progress?

**Comment by alceil** [comment]
I will raise a pr soon as possible I was busy this week due to my college work.

**Comment by terrymanu** [comment]
@alceil Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by sgunadhya** [comment]
There is overlap between this issue and issue #15700

**Comment by TeslaCN** [comment]
Duplicate with #15700.
