### ISSUE TITLE
Add unit test for EncryptOrderByItemTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15822]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add some unit test for EncryptOrderByItemTokenGenerator.

- EncryptOrderByItemTokenGenerator#isGenerateSQLToken
- EncryptOrderByItemTokenGenerator#generateSQLTokens

**Comment by huangyilong2000** [comment]
Hello, Is this issue still open? I want to work on this issue. 
I am familiar with Java. This is my first contribution. I will appreciate if you can give me guide woring on this issue.

**Comment by MrNobody09** [comment]
Hi, I am Nalin, a contributor to OpenForce 2022. I would like to work on this issue. Can you assign it to me?

**Comment by manisha-27** [comment]
Hey @strongduanmu Can I work on this issue under OpenForce'22 ?

**Comment by menghaoranss** [comment]
> Hey @strongduanmu Can I work on this issue under OpenForce'22 ?

@manisha-27 here is the issue list of OpenForce'22, feel free to pick one: https://github.com/apache/shardingsphere/issues?q=is%3Aopen+is%3Aissue+label%3A%22project%3A+OpenForce+2022%22+no%3Aassignee
