### ISSUE TITLE
Add unit test for EncryptPredicateColumnTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15823]
Hi community,

We need to add some unit test for EncryptPredicateColumnTokenGenerator.

- EncryptPredicateColumnTokenGenerator#isGenerateSQLToken
- EncryptPredicateColumnTokenGenerator#generateSQLTokens

**Comment by vasantisuthar** [comment]
Hi, I am Vasanti Suthar, a contributor to OpenForce 2022. I would like to work on this issue. At the time I am not familiar with the unit test but I do know Java and Databases, can you guide me to work on this issue. Thank you.

**Comment by strongduanmu** [comment]
Welcome @vasantisuthar, for first contribution, you can read [code conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) first, it may be helpful to you. 

Then you can refer to EncryptParameterRewriterBuilderTest, which is a typical JUNIT unit test. First, you need to mock the object that the unit test depends on through the mock method, then call the public method that needs to be tested, and finally use assertThat to assert the result.

**Comment by terrymanu** [comment]
@vasantisuthar Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by strongduanmu** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/19502.

**Comment by sunkai-cai** [comment]
Thanks @strongduanmu review code of #19502 , this issue has been completed.
