### ISSUE TITLE
Add unit test for EncryptInsertValuesTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15821]
Hi community,

We need to add some unit test for EncryptInsertValuesTokenGenerator.

- EncryptInsertValuesTokenGenerator#isGenerateSQLToken
- EncryptInsertValuesTokenGenerator#generateSQLTokens

**Comment by Pdahiya5033** [comment]
Hi @strongduanmu 
I would like to contribute to this issue being a participant in openforce 22

**Comment by strongduanmu** [comment]
> 

Welcome @Pdahiya5033, For first contribution, you can read [code conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) first, it may be helpful to you.

**Comment by terrymanu** [comment]
@Pdahiya5033 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by Pdahiya5033** [comment]
I am sorry for that .
Yeah you can state this issue as open
