### ISSUE TITLE
Add unit test for EncryptPredicateRightValueTokenGenerator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15824]
Hi community,

We need to add some unit test for EncryptPredicateRightValueTokenGenerator.

- EncryptPredicateRightValueTokenGenerator#isGenerateSQLToken
- EncryptPredicateRightValueTokenGenerator#generateSQLTokens

**Comment by Ardent10** [comment]
Hello there,

**Comment by Ardent10** [comment]
I wanted to contribute but I don't know Java at the moment, I get to understand that this project is related to  Databases, I do understand MongoDB and SQL. I don't know if it would be helpful or not.
Can you please guide me how can get started in this prroject?

**Comment by strongduanmu** [comment]
Hi @Ardent10, this project is developed in java, so java is a must-have skill. If you want to participate in this issue, my suggestion is to learn the use of java first and understand how to use juint for unit testing.

**Comment by menghaoranss** [comment]
> Hello there,
> I wanted to contribute but I don't know Java at the moment, I get to understand that this project is related to Databases, I do understand MongoDB and SQL. I don't know if it would be helpful or not.
> Can you please guide me how can get started in this project?

@Ardent10 Here is a document optimized issue #15836 , would you like to try it?

**Comment by seraph14** [comment]
I know java and the basics of unit testing with JUnit. Can I work on this issue?

**Comment by menghaoranss** [comment]
> I know java and the basics of unit testing with JUnit. Can I work on this issue?

@seraph14 sure, look forward to your contribution.

**Comment by terrymanu** [comment]
@seraph14 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by strongduanmu** [comment]
Fixed by #19502.

**Comment by sunkai-cai** [comment]
Thanks @strongduanmu review code of #19502 , this issue has been completed.
