### ISSUE TITLE
SQL parse error when execute postgresql select statement

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#15835]
### Which version of ShardingSphere did you use?

[b3e90fc](https://github.com/apache/shardingsphere/commit/b3e90fc9f8df3057b75ae3c7630a6c02b930d0d7)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute `SELECT * FROM cypher('sharding_test_1', $$ CREATE (n) $$) as (a agtype)` successfully.

### Actual behavior

```
test=> SELECT * FROM cypher('sharding_test_1', $$ CREATE (n) $$) as (a agtype);
ERROR:  You have an error in your SQL syntax
test=> SELECT * FROM cypher('sharding_test_2', $$ CREATE (n) $$) as (a agtype);
ERROR:  You have an error in your SQL syntax
```

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this sql?

**Comment by tuichenchuxin** [comment]
sure, I'll check it.
