### ISSUE TITLE
What are the limitations of sharding JDBC on SQL?

### ISSUE THREAD

**Issue by LiangZai8** [apache/shardingsphere#15840]
Dear developer 👍 
I have a problem, for example:
![image](https://user-images.githubusercontent.com/77952342/156962561-08d78626-490b-4e76-890c-2935ae4f4cc8.png)

I can't know which SQL keywords can't be used, We have a lot of items. I need to know what can't be used. It's easier to change it
 Thanks;

**Comment by strongduanmu** [comment]
Hi @LiangZai8, can you provide more information? version and sharding configuration?

**Comment by terrymanu** [comment]
I close the issue because of no response anymore.
