### ISSUE TITLE
type convert

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#15874]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no

### Describe the feature you would like.
Now many type conversions will throw Exceptions, In stream and memory modes, there will also be inconsistent behavior.
I will build type convert system enumerates all Types of java.sql.Types, Unify the behavior of stream and memory modes and Make prompts more friendly

#14430
#15457
- [ ]  infrastructure 
- [ ] java.sql.Types.BIT
- [ ] java.sql.Types.TINYINT
- [ ] java.sql.Types.SMALLINT
- [ ] java.sql.Types.INTEGER
- [ ] java.sql.Types.BIGINT
- [ ] java.sql.Types.FLOAT
- [ ] java.sql.Types.REAL
- [ ] java.sql.Types.DOUBLE
- [ ] java.sql.Types.NUMERIC
- [ ] java.sql.Types.DECIMAL
- [ ] java.sql.Types.CHAR
- [ ] java.sql.Types.VARCHAR
- [ ] java.sql.Types.LONGVARCHAR
- [ ] java.sql.Types.DATE
- [ ] java.sql.Types.TIME
- [ ] java.sql.Types.TIMESTAMP
- [ ] java.sql.Types.BINARY
- [ ] java.sql.Types.VARBINARY
- [ ] java.sql.Types.LONGVARBINARY
- [ ] java.sql.Types.NULL
- [ ] java.sql.Types.OTHER
- [ ] java.sql.Types.JAVA_OBJECT
- [ ] java.sql.Types.DISTINCT
- [ ] java.sql.Types.STRUCT
- [ ] java.sql.Types.ARRAY
- [ ] java.sql.Types.BLOB
- [ ] java.sql.Types.CLOB
- [ ] java.sql.Types. REF
- [ ] java.sql.Types.DATALINK
- [ ] java.sql.Types.BOOLEAN
- [ ] java.sql.Types.ROWID
- [ ] java.sql.Types.NCHAR
- [ ] java.sql.Types.NVARCHAR
- [ ] java.sql.Types.LONGNVARCHAR
- [ ] java.sql.Types.NCLOB
- [ ] java.sql.Types.SQLXML
- [ ] java.sql.Types.REF_CURSOR
- [ ] java.sql.Types.TIME_WITH_TIMEZONE
- [ ] java.sql.Types.TIMESTAMP_WITH_TIMEZONE

**Comment by SirMin** [comment]
![class](https://user-images.githubusercontent.com/16568907/157196593-732c31fc-f227-4eb2-940d-a1b824df892c.png)
![load all TypeHandler](https://user-images.githubusercontent.com/16568907/157196705-e0e8d22b-325f-48e4-836c-b0043d9a5294.png)
![get target type value with memory](https://user-images.githubusercontent.com/16568907/157196616-8d1a6f5e-ba0a-44de-899d-333bf60185e4.png)
![get target type value with stream](https://user-images.githubusercontent.com/16568907/157196676-3e0bb473-53ed-4b0f-a891-a20a69a940da.png)
![JDBCMemoryQueryResult load value](https://user-images.githubusercontent.com/16568907/157196693-2c13987b-55c0-4fa9-b4ad-9241c747a1a1.png)

**Comment by TeslaCN** [comment]
Hi @SirMin @tuichenchuxin 
Any update here?

**Comment by tuichenchuxin** [comment]
@TeslaCN Not complete yet. We'll discuss about it. @SirMin

**Comment by terrymanu** [comment]
@SirMin Thanks for excellent details of the issue, could change the title for search friendly?
