### ISSUE TITLE
multiple  data source aggregation 

### ISSUE THREAD

**Issue by galaxylqx** [apache/shardingsphere#15876]
Problem Description：multiple  data source ，use the same database instance. for example, The host is 127.0.0.1 and port is 3306，Need to create multiple connection pools，If it is 100 databases，You need to create 100 connection pools 

```schemaName: sharding_db
dataSources:
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/db_1?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
 ds_2:
    url: jdbc:mysql://127.0.0.1:3306/db_2?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```

Therefore, whether the same database instance will share the connection pool for aggregation，Increase the parameter identification whether to enable aggregation.
server.yaml
```
props:
   data-source-aggregation-enabled: true
```

**Comment by TeslaCN** [comment]
Some databases like PostgreSQL may not support connect to different databases through one connection. What's the problem of creating 100 connection pools?

**Comment by sandynz** [comment]
Hi @galaxylqx , What's the advantages if we do data source aggregation? Save opened connections?
It's true in some cases, but we could consider the most connections we need for peak throughput, the connections counts are similar in this case, no matter we do data source aggregation or not. And we could do some optimization on data source configuration to take similar effect.

**Comment by galaxylqx** [comment]
Hi @sandynz, Have you considered the problem of 10000 databases in the same physical database instance, which means that 10000 database connection pools need to be created. It does exist in our online environment. The current way of binding data sources to physical databases is unreasonable when the same database instance is used for many databases. I think database connections should not be bound to databases, but should correspond to database instances, A database instance can create one or more connection pools, which can be determined by the configuration.

**Comment by sandynz** [comment]
Hi @galaxylqx , I did the similar thing for thread pool before, it seems more flexible for shared pool than dedicated pools, they're different ways.
If every database need to limit maximum connections count, and the minimum connections count is `0`, then it's resource isolation problem, the 2 ways above have similar effect, though one of them need much more configuration.
For example: [Hystrix Execution Isolation Strategy]( https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy ).

In ShardingSphere, there's `schema` which is the database concept in ShardingSphere, and the underlying RDBMS database is the abstraction level and created by users for now.
For ShardingSphere cloud product, the resource abstraction level might be machine instance or database instance, and underlying databases are created by ShardingSphere, then users just need few configuration. This might be the feature you want.

**Comment by WJME** [comment]
@galaxylqx  这个问题大佬你是怎样解决的呢

**Comment by linghengqian** [comment]
@WJME The discussion related to this issue has ended at https://github.com/apache/shardingsphere/pull/16511, if there is a problem, you should open a new issue instead of staying in this issue.
