### ISSUE TITLE
Github pages shows  its active but its not . 404 error pops up

### ISSUE THREAD

**Issue by aasim-syed** [apache/shardingsphere#15896]
### Actual behavior

![image](https://user-images.githubusercontent.com/70385414/157351286-ab15501e-86b7-486e-ac73-548ce1cf01b6.png)

**Comment by linghengqian** [comment]
What's this? There is no prompt in the documentation pointing to this link.

**Comment by RaigorJiang** [comment]
@aasim-syed  The URL you visited does not belong to the Apache organization.

**Comment by aasim-syed** [comment]
> @aasim-syed The URL you visited does not belong to the Apache organization.
THEN WHAT DOES THIS LEAD TO. ONLY THING INVALID IS THIS LABEL ON THE ISSUE.
![image](https://user-images.githubusercontent.com/70385414/157451593-3fe1ea55-141a-47cb-a663-d0a9ce03be20.png)

**Comment by RaigorJiang** [comment]
Oh, I find it!  Thank you @aasim-syed .

**Comment by RaigorJiang** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/5668787/157461645-700ae39e-b46a-420c-9c40-d074ce9d0160.png">

**Comment by RaigorJiang** [comment]
Hi @taojintianxia 
Could you have a look?

**Comment by taojintianxia** [comment]
> Hi @taojintianxia Could you have a look?

let me ask the infra team about this . I saw this kind of issue on some other Apache project, let me try to fix it

**Comment by linghengqian** [comment]
- Isn't this issue already resolved?

**Comment by RaigorJiang** [comment]
Resolved.
