### ISSUE TITLE
TypedSPIRegistry's methods finregisteredService and GeregisteredService feel misleading

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#15927]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

findRegisteredService and getRegisteredService feels like getting one that already exists, but actual new.

**Comment by RaigorJiang** [comment]
Hi @SirMin 
Actually, `findXxx` and `getXxx` here means to get registered SPI types, not SPI instances.
Do you have any other suggestions?

**Comment by SirMin** [comment]
@RaigorJiang 
In TypedSPIRegistry , is SPI instance. modified to newXxx?  Below is an example of usage, it like get already exists, but is new.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/16568907/159146678-c3270c4c-463b-4279-9fd8-0480151402da.png">

**Comment by SirMin** [comment]
in SingletonSPIRegistry, getSingletonInstancesMap will register SPI, but TypedSPIRegistry not. Manual registration is required when using TypedSPIRegistry, but not when using SingletonSPIRegistry. unify behavior?

**Comment by sandynz** [comment]
> in SingletonSPIRegistry, getSingletonInstancesMap will register SPI, but TypedSPIRegistry not. Manual registration is required when using TypedSPIRegistry, but not when using SingletonSPIRegistry. unify behavior?

Hi @SirMin , `SingletonSPI` and `SingletonSPIRegistry` were added after `TypedSPIRegistry` to simplify singleton SPI  usage and improve performance. And `getSingletonInstancesMap` method should be called once for one `singletonSPIClass`, so it's equavalent as before.

But methods in `TypedSPIRegistry` will be called repeatedly for one `typedSPIClass`, if we add `ShardingSphereServiceLoader.register(...)` in `TypedSPIRegistry` methods, it'll be called too much times, so it's not added for now.

In fact, only `ShardingSphereServiceLoader.getSingletonServiceInstances` were replaced as `SingletonSPIRegistry`, there might be more cases could be improved later.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
