### ISSUE TITLE
Mysql Jdbc setBlob() cannot be replaced with setObject(), causing data inconsistencies   ,Shardingjdbc4.1.1

### ISSUE THREAD

**Issue by huyu-tom** [apache/shardingsphere#15948]
![image](https://user-images.githubusercontent.com/54206202/157466065-36ac3138-aeb5-424f-94d9-e916063e2168.png)
![b3ba7997fcb0b09897f36158f6fa704](https://user-images.githubusercontent.com/54206202/157468063-5a171bd6-4dc6-4902-bbc4-71fd2b296ff3.png)
![c1a9fd4d34c67739798d3e8df31ba2d](https://user-images.githubusercontent.com/54206202/157468095-56aab8ca-6685-495a-bc24-3032e97f0728.png)

**Comment by sandynz** [comment]
Hi @huyu-tom , thanks for your feedback. Could you get a workaround for now?

**Comment by terrymanu** [comment]
The version 4.x is out of service, please try version 5.x
