### ISSUE TITLE
[OpenForce 2022] Add Oracle SQL `DROP DATABASE LINK`

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#15954]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support parsing Oracle SQL `DROP DATABASE LINK`. You can learn more details about this SQL [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DROP-DATABASE-LINK.html#GUID-89856C55-29FB-4B52-84A9-E53B8D115864).
- Remember to add new corresponding SQL cases in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed results in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case).
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) and [UnsupportedSQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java) to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

## Targets files
You can take this PR as a reference #14048 (Add Oracle SQL - CREATE DATABASE LINK)

**Comment by everly-gif** [comment]
Hi, I'm willing to give this a try as a part of openforce. Please assign this issue to me

**Comment by Liangda-w** [comment]
@everly-gif sure, welcome!
