### ISSUE TITLE
How to customized my specific Sharding Strategy

### ISSUE THREAD

**Issue by breezeLoganGithub** [apache/shardingsphere#15950]
I check the user 's manual said it support user customized Sharding Strategy。
How to do it,can you provide an example , 3ks:)

**Comment by zjcnb** [comment]
Please refer to : https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/extension-example/custom-sharding-algortihm-example

**Comment by breezeLoganGithub** [comment]
can you give some detial for ClassBasedOrderItemStandardShardingAlgorithmFixture ,I have no idea for the functions.3ks

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I'm closing it now.
If this problem persists, please reopen it or submit a new one.
