### ISSUE TITLE
[OpenForce 2022] Add Oracle SQL `ALTER DATABASE LINK`

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#15955]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support parsing Oracle SQL `ALTER DATABASE LINK`. You can learn more details about this SQL [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-DATABASE-LINK.html#GUID-0259D771-9D04-4D86-A94D-61B621A3918A).
- Remember to add new corresponding SQL cases in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed results in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case).
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) and [UnsupportedSQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java) to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

## Targets files
You can take a look at this PRs as a reference
*  #14048 
* #16024

**Comment by AnushkaSingh1** [comment]
Hi, I am Anushka, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Comment by utkershrajvenshi** [comment]
Hi @Liangda-w 
I'd like to explore this issue. Could you please point me to resources for learning about ANTLR G4 files.
I would like to contribute under OpenForce 2022. Could you please assign this ticket to me..

**Comment by Liangda-w** [comment]
Hi @AnushkaSingh1, welcome! Assigned to you:)

**Comment by Liangda-w** [comment]
> Hi @Liangda-w I'd like to explore this issue. Could you please point me to resources for learning about ANTLR G4 files. I would like to contribute under OpenForce 2022. Could you please assign this ticket to me..

Hi @utkershrajvenshi, thanks for your interest! However as @AnushkaSingh1 comes first, I just assigned this issue to her. 
If you would like to work on similar issues, you can find more [here](https://github.com/apache/shardingsphere/issues?q=is%3Aissue+is%3Aopen+label%3A%22project%3A+OpenForce+2022%22+++label%3A%22in%3A+SQL+parse%22+no%3Aassignee+) about PostgreSQL, which haven't been assigned yet. Let me know if you're interested in Oracle specific SQLs, I can open another issue for you:) 

You can learn more about ANTLR in their official doc [here](https://github.com/antlr/antlr4/blob/master/doc/index.md) and see some already implemented grammar [here](https://github.com/apache/shardingsphere/tree/c27bfea1a989d36055fe81c4da5fd37a0e40d526/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle) as examples.

**Comment by everly-gif** [comment]
Hi @Liangda-w  Can I take this issue up? I would like to work on this.

**Comment by Liangda-w** [comment]
> Hi @Liangda-w Can I take this issue up? I would like to work on this.

Sure feel free to take it up:) 

@AnushkaSingh1 what's the status now, are you still working on this issue?

**Comment by AnushkaSingh1** [comment]
Yes I am working, am sorry I was busy with my college exams!

**Comment by everly-gif** [comment]
@Liangda-w in that case, could you create some new issues for me? I would love to work on some :)

**Comment by Liangda-w** [comment]
> @Liangda-w in that case, could you create some new issues for me? I would love to work on some :)

Sure, I just created #16621 and #16620, feel free to claim:)

**Comment by everly-gif** [comment]
This issue can be closed , PR is already merged #16980 .

**Comment by Liangda-w** [comment]
> This issue can be closed , PR is already merged #16980 .

Great, thank you! 👍
