### ISSUE TITLE
Which version of org.apache.curator should I use in shardingsphere 5.1.0

### ISSUE THREAD

**Issue by qiaoheng110** [apache/shardingsphere#15963]
## Question
Which version of org.apache.curator should I use in shardingsphere 5.1.0
cluster mod
<img width="873" alt="image" src="https://user-images.githubusercontent.com/20252910/157603534-140a6620-5c9a-4229-88eb-2981475b9690.png">

**Comment by zjcnb** [comment]
@qiaoheng110 Hi, you can dependency it if you use cluster mode : 

```
 <dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-cluster-mode-repository-zookeeper-curator</artifactId>
    <version>5.1.0</version>
 </dependency>
```

**Comment by qiaoheng110** [comment]
> @qiaoheng110 Hi, you can dependency it if you use cluster mode :
> 
> ```
>  <dependency>
>     <groupId>org.apache.shardingsphere</groupId>
>     <artifactId>shardingsphere-cluster-mode-repository-zookeeper-curator</artifactId>
>     <version>5.1.0</version>
>  </dependency>
> ```

<img width="829" alt="image" src="https://user-images.githubusercontent.com/20252910/157610730-7f2b3874-4cae-458a-931f-7cef267f6ae6.png">
@zjcnb another problem occurred
