### ISSUE TITLE
org.apache.shardingsphere.sql.parser.autogen not exists

### ISSUE THREAD

**Issue by lxb1742** [apache/shardingsphere#15964]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
![parse](https://user-images.githubusercontent.com/101316197/157607081-de4487dc-12db-4a89-b8fd-f2fed53c76b1.png)

**Comment by cheese8** [comment]
mvn install first

**Comment by TeslaCN** [comment]
Please refer to FAQ.
https://shardingsphere.apache.org/document/current/en/reference/faq/

**Comment by bpzhang** [comment]
https://shardingsphere.apache.org/document/current/en/faq/
