### ISSUE TITLE
sharding connection problem

### ISSUE THREAD

**Issue by wangzb105** [apache/shardingsphere#15983]
## Bug Report
15/5000 
Use the program to create a Pymysql connection and use the connection to execute it
execute twice create database if not exists seer_dev default charset utf8mb4 collate utf8mb4_unicode_ci;
err: pymysql.err.ProgrammingError: (1007, "Can't create database 'seer_dev'; database exists")
execute use seer_dev;
err: pymysql.err.OperationalError: (1997, 'Runtime exception: [Failed to switch schema, please terminate current transaction.]')
use apache/shardingsphere-proxy-5.1.0 version

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by RaigorJiang** [comment]
@wangzb105 
Thanks for your report, I'll check it.

**Comment by RaigorJiang** [comment]
Hi @wangzb105 
The problem was fixed in #16056, you can try the master branch now.

**Comment by wangzb105** [comment]
5/5000 
Another question，execute use seer_dev;
err: pymysql.err.OperationalError: (1997, 'Runtime exception: [Failed to switch schema, please terminate current transaction.]') ？？？

**Comment by RaigorJiang** [comment]
Please check the SQL log to see if statements such as `begin` have been sent, resulting in a transaction.
