### ISSUE TITLE
Cluster Mode ClassNotFoundException: org.apache.curator.connection.StandardConnectionHandlingPolicy

### ISSUE THREAD

**Issue by qiaoheng110** [apache/shardingsphere#15998]
when i use Cluster Mode
<img width="271" alt="image" src="https://user-images.githubusercontent.com/20252910/157838059-6ef39a6a-f843-4073-ae6f-c4325a7efc90.png">
5.1.0
<img width="650" alt="image" src="https://user-images.githubusercontent.com/20252910/157838143-27f2ff79-70e7-4b7b-b4db-e4cb42391ef3.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/20252910/157838202-95ad796b-69c2-466d-a219-99429b4ac0de.png">

A startup error occurred

<img width="821" alt="image" src="https://user-images.githubusercontent.com/20252910/157838348-2287612e-aab5-4a58-ab9b-f1c36a4ca7eb.png">

**Comment by zjcnb** [comment]
@qiaoheng110 I guess your maven dependency conflict, Can you show your `pom.xml`?
