### ISSUE TITLE
Redesign RDL integrate test engine and cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#16005]
The current RDL integrate test engine and cases are in-corrected.

I just removed the cases on #16004.

The problem of current RDL cases:

1. The SQL of case should be RDL, not RQL;
2. Should not change current rules, which are used to RAL and RQL, it is better to CREATE/ALTER/DROP new rule for assertion.

Please Redesign the RDL test engine and rewrite the related test cases.

**Comment by nikhilmaurya26** [comment]
Hi @terrymanu , I am Nikhil, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Comment by terrymanu** [comment]
Hi, Nikhil. Welcome to pick up this issue, any question please contact me freely.

**Comment by Jacob953** [comment]
Hi, @terrymanu! plz assign this to me, too. ;)

**Comment by terrymanu** [comment]
@Jacob953 Please go ahead

**Comment by terrymanu** [comment]
@Jacob953 @nikhilmaurya26 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by sunkai-cai** [comment]
I am working it.
