### ISSUE TITLE
91/5000  When a table using the standard subdivision strategy, if use hintManager. SetDatabaseShardingValue addTableShardingValue, cannot be routed to the corresponding database and table

### ISSUE THREAD

**Issue by csdeng84** [apache/shardingsphere#16008]
91/5000 
When a table using the standard subdivision strategy, if use hintManager. SetDatabaseShardingValue addTableShardingValue, cannot be routed to the corresponding database and table。

because in  ShardingStandardRoutingEngine.java (line 78)
only   use HintShardingStrategy can enter into the function  isRoutingByHint 
--------------------------------------------------------------------------------------------------------
    private Collection<DataNode> getDataNodes(final ShardingRule shardingRule, final TableRule tableRule) {
        ShardingStrategy databaseShardingStrategy = createShardingStrategy(shardingRule.getDatabaseShardingStrategyConfiguration(tableRule),
                shardingRule.getShardingAlgorithms(), shardingRule.getDefaultShardingColumn());
        ShardingStrategy tableShardingStrategy = createShardingStrategy(shardingRule.getTableShardingStrategyConfiguration(tableRule),
                shardingRule.getShardingAlgorithms(), shardingRule.getDefaultShardingColumn());
        if (isRoutingByHint(shardingRule, tableRule)) {
            return routeByHint(tableRule, databaseShardingStrategy, tableShardingStrategy);
        }
        if (isRoutingByShardingConditions(shardingRule, tableRule)) {
            return routeByShardingConditions(shardingRule, tableRule, databaseShardingStrategy, tableShardingStrategy);
        }
        return routeByMixedConditions(shardingRule, tableRule, databaseShardingStrategy, tableShardingStrategy);
    }
---------------------------------------------------------------------------------------------------------------
This is recommended 

   private boolean isRoutingByHint(final ShardingRule shardingRule, final TableRule tableRule) {
        //return  (shardingRule.getDatabaseShardingStrategyConfiguration(tableRule) instanceof HintShardingStrategyConfiguration
         //       && shardingRule.getTableShardingStrategyConfiguration(tableRule) instanceof HintShardingStrategyConfiguration);

        boolean isByHitManager = getDatabaseShardingValuesFromHint().size() > 0 && getTableShardingValuesFromHint().size() > 0;
        boolean isByHitStrategy = shardingRule.getDatabaseShardingStrategyConfiguration(tableRule) instanceof HintShardingStrategyConfiguration
                && shardingRule.getTableShardingStrategyConfiguration(tableRule) instanceof HintShardingStrategyConfiguration;
        return isByHitManager || isByHitStrategy;
    }

**Comment by RaigorJiang** [comment]
Hi @csdeng84 
The hint algorithm is indeed prepared for the hint strategy.

**Comment by csdeng84** [comment]
> Hi @csdeng84 The hint algorithm is indeed prepared for the hint strategy.

@RaigorJiang  ,Thankyou!     because the table has already use standard-strategy , I want to use hintManager for batch-processing.

**Comment by RaigorJiang** [comment]
I will close this issue as it doesn't match the design of ShardingSphere.
In a sharding scenario, if users need to route to a specific data source or table, they should use the sharding key to control it, not through another strategy (like hint).
