### ISSUE TITLE
distributed transaction, two data source

### ISSUE THREAD

**Issue by luoye1989hzx** [apache/shardingsphere#16022]
There are two data sources in a method, one sharding, one not. 
How to guarantee transaction?
Is there a reasonable solution?

**Comment by RaigorJiang** [comment]
Hi @luoye1989hzx 
Are both data sources in ShardingSphere's logical schema? Please provide more information.

**Comment by luoye1989hzx** [comment]
> Hi @luoye1989hzx Are both data sources in ShardingSphere's logical schema? Please provide more information.

One is， one not

**Comment by RaigorJiang** [comment]
> One is， one not

In this case, the transaction needs to be actively guaranteed by yourself, such as sending commits and rollbacks. 
In fact, with or without sharding, your data sources can be handed over to ShardingSphere for consolidation so that XA transactions can be used.
