### ISSUE TITLE
Travis CI failure caused by jacoco:prepare-agent failed

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#16059]
## CI

https://app.travis-ci.com/github/apache/shardingsphere/builds/247807532

**Comment by Trydamere** [comment]
hi, @TeslaCN I want to contribute to this issue.
I am familiar with Java, but I have not used travis CI before. Could you give me instruction how to begin this issue?

**Comment by TeslaCN** [comment]
Hi @Trydamere 
Actually I don't know what happened to Travis CI. I'm going to clear the caches. If the problem still occur, we may need to investigate why the jacoco:prepare-agent failed.

**Comment by TeslaCN** [comment]
I've restarted this after caches cleared. https://app.travis-ci.com/github/apache/shardingsphere/builds/247884763

**Comment by TeslaCN** [comment]
Problem solved after clearing the caches.
