### ISSUE TITLE
generate docker images for every commit

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#16068]
## Feature
For everytime the version release, this is only one proxy docker image for that corresponding version. this is not convenient for testing.

so add some github actions to generate the docker images for every commit to test.

please assign this task to me.

**Comment by RaigorJiang** [comment]
Fixed by #16070.

**Comment by taojintianxia** [comment]
https://github.com/apache/shardingsphere/pkgs/container/shardingsphere-proxy

**Comment by TeslaCN** [comment]
`SW_OAP` is SkyWalking OAP.
https://github.com/apache/shardingsphere/blob/f99a508cd432b3806255a91826e91f9a3374bb17/.github/workflows/docker-per-commit.yaml#L62
