### ISSUE TITLE
Modifying the database lob column will report errors and steam cannot be read repeatedly

### ISSUE THREAD

**Issue by iwhalecloud-platform** [apache/shardingsphere#16080]
### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
When using sharding to connect to Oracle database, if the database field is CLOB or blob, the following error will be reported:

Error updating database. Cause: java. sql. SQLException: Invalid column type
The error may involve defaultParameterMap
The error occurred while setting parameters
 SQL: UPDATE BC_ CARD_ PROFILE_ RULE SET OBJ_ PROLONG_ RULE = ? WHERE CARD_ PROFILE_ RULE_ ID = ?
Cause: java. sql. SQLException: Invalid column type
; uncategorized SQLException; SQL state [99999]; error code [17004]; Invalid column type; nested exception is java. sql. SQLException: Invalid column type
### Reason analyze (If you can)
In addition, when the table is a sharding table or broadcast table, if the CLOB field is updated on multiple tables, only one table can read the updated value, because the CLOB will be set with stringreader type in the code. After reading the first time, the index reaches the end of the stream, and the value cannot be read repeatedly
### Solution
Convert stream to reference data type

**Comment by terrymanu** [comment]
The version is out of service, I just close it
