### ISSUE TITLE
Add unit test for ShardingRemoveTokenGenerator

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16093]
Hi community,

We need to add some unit test for ShardingRemoveTokenGenerator.

- [X] ShardingRemoveTokenGenerator#isGenerateSQLToken
- [x] ShardingRemoveTokenGenerator#generateSQLTokens

**Comment by BashCache** [comment]
Hi,
I would like to work on this issue under OpenForce 2022. Can you assign this to me

**Comment by terrymanu** [comment]
@BashCache Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by Rohitpandey357** [comment]
Hi, I would like to work on this issue. Please, assign this to me.

**Comment by strongduanmu** [comment]
@Rohitpandey357 Welcome, I just assign this issue to you.
