### ISSUE TITLE
`MetaDataPersistService.persistTransactionRule(final Properties props, final boolean isOverwrit)` need add unit test.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16091]

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by sandynz** [comment]
@shreya024 Welcome!

**Comment by yangsen00** [comment]
Hello，dose this issues need someone to solve? maybe I can.

**Comment by sandynz** [comment]
@yangsen00 , Welcome!

**Comment by yangsen00** [comment]
> > Hello，dose this issues need someone to solve? maybe I can.
> 
> @yangsen00 Hi, how is this mission going?
I'm busy for my work.I'll finish it this week

**Comment by zjcnb** [comment]
> > > Hello，dose this issues need someone to solve? maybe I can.
> > 
> > 
> > @yangsen00 Hi, how is this mission going?
> > I'm busy for my work.I'll finish it this week

OK, i 'm looking forward.

**Comment by yangsen00** [comment]
hello,could this close?

**Comment by terrymanu** [comment]
@yangsen00 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by yangsen00** [comment]
> @yangsen00 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

I have created a PR，and code have merged into master，maybe it should closed

**Comment by zjcnb** [comment]
> > @yangsen00 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.
> 
> I have created a PR，and code have merged into master，maybe it should closed

Yeah, it 's finished, i close it
