### ISSUE TITLE
Add unit test for IndexToken#toString

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16098]

**Comment by SarveshLimaye** [comment]
Hi, I am Sarvesh Limaye, a contributor to OpenForce 2022. I would like to work on this issue. Thank you!

**Comment by tuichenchuxin** [comment]
@SarveshLimaye Ok.

**Comment by terrymanu** [comment]
@SarveshLimaye Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by TeslaCN** [comment]
Close via #19325.
