### ISSUE TITLE
Add unit test for ShardingInsertValuesToken#toString

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16100]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by strongduanmu** [comment]
Welcome @shreya024, glad see you again.

**Comment by shreya024** [comment]
> Welcome @shreya024, glad see you again.

Thank you,I am working on the issue.Kindly guide me how to access/modify the result located inside toString method from test class.

**Comment by strongduanmu** [comment]
> > Welcome @shreya024, glad see you again.
> 
> Thank you,I am working on the issue.Kindly guide me how to access/modify the result located inside toString method from test class.

@shreya024 Of course, You could create a ShardingInsertValuesToken instance first, and then add some insertValues by `getInsertValues().add(insertValueToken)` method. 

After complete these tasks, you can test `toString` method. It should be noted that this method needs to pass in a RouteUnit, which is result returned by ShardingSphere routing engine, which records the relationship between logical data source and real data source, as well as logical table and real table.

**Comment by shreya024** [comment]
> > > Welcome @shreya024, glad see you again.
> > 
> > 
> > Thank you,I am working on the issue.Kindly guide me how to access/modify the result located inside toString method from test class.
> 
> @shreya024 Of course, You could create a ShardingInsertValuesToken instance first, and then add some insertValues by `getInsertValues().add(insertValueToken)` method.
> 
> After complete these tasks, you can test `toString` method. It should be noted that this method needs to pass in a RouteUnit, which is result returned by ShardingSphere routing engine, which records the relationship between logical data source and real data source, as well as logical table and real table.

Thank you.Yes,I have done these but I'm getting a java.lang.StringIndexOutOfBoundsException: start -2, end 0, length 0 probably because StringBuilder result is always empty.
