### ISSUE TITLE
Add unit test for WhereClauseShardingConditionEngine#createShardingConditions

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16103]

**Comment by deathmukh** [comment]
hi, can I work on this?

**Comment by strongduanmu** [comment]
@deathmukh Welcome, I will assign this issue to you.

**Comment by terrymanu** [comment]
@deathmukh Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by lushaorong** [comment]
I want to try this work

**Comment by strongduanmu** [comment]
@lushaorong Welcome.

**Comment by asasas234** [comment]
I want to try this work

**Comment by lhyundeadsoul** [comment]
> I want to try this work

Sorry, @asasas234  I am already working on this, and I will submit PR soon. I am glad to invite you to give me a review. Thx.
