### ISSUE TITLE
Add unit test for InsertClauseShardingConditionEngine#createShardingConditions

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16102]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

**Comment by pparthenhs** [comment]
Hello there, I could start working on this. I will let you know when I finish.

**Comment by tuichenchuxin** [comment]
@pparthenhs OK. Glad to see you.

**Comment by pparthenhs** [comment]
MR is ready!! :rocket:  :rocket:

**Comment by terrymanu** [comment]
The #16212 is not cover all codes of InsertClauseShardingConditionEngine#createShardingConditions, please continue to do it
