### ISSUE TITLE
Add unit test for ConditionValueGeneratorFactory#generate

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16105]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

**Comment by shreya024** [comment]
Hi, I am Shreya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by strongduanmu** [comment]
@shreya024 Glad see you here, I will assign this issue to you.
