### ISSUE TITLE
Add unit test for TableToken#toString

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#16101]

**Comment by Naresh-chandanbatve** [comment]
Hello @tuichenchuxin, 
I am openforce 2022 contributor,
I want to work on this issue can you assign this to me.

**Comment by strongduanmu** [comment]
@Naresh-chandanbatve Welcome, I will assign this issue to you.

**Comment by terrymanu** [comment]
@Naresh-chandanbatve Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by zrsaber** [comment]
please assign it to me, i will have a try

**Comment by misselvexu** [comment]
I will finish this ut.
