### ISSUE TITLE
use spring boot 2.6.4 , transaction do not roll back

### ISSUE THREAD

**Issue by shangwq** [apache/shardingsphere#16117]
use the lastest version spring boot 2.6.4  and shardingsphere 5.1.0
transaction do not roll back

ps. use spring boot 2.5.x and 2.6.x  has this same problem，spring boot 2.4.x is ok

**Comment by zjcnb** [comment]
@shangwq Hello, Can you provide a demo project?

**Comment by shangwq** [comment]
it's a simple project

the main dependencies is
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.6.4</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.1.0</version>
</dependency>
```

application.properties
```properties
mybatis.mapper-locations = classpath*:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case = true

spring.shardingsphere.props.sql-show = true
spring.shardingsphere.datasource.names = master,slave

spring.shardingsphere.datasource.master.type = com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.master.driver-class-name = com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.master.jdbc-url = jdbc:mysql://xxx:3306/xxx?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowMultiQueries=true
spring.shardingsphere.datasource.master.username = xxx
spring.shardingsphere.datasource.master.password = xxx

spring.shardingsphere.datasource.slave.type = com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.slave.driver-class-name = com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.slave.jdbc-url = jdbc:mysql://xxx:3306/xxx?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowMultiQueries=true
spring.shardingsphere.datasource.slave.username = xxx
spring.shardingsphere.datasource.slave.password = xxx
```

Unit Test
```java
@SpringBootApplication
@MapperScan(basePackages = {"com.example.demo"})
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}


@Transactional(rollbackFor = Exception.class)
@SpringBootTest(classes = {DemoApplication.class})
class DemoApplicationTests {

    @Resource
    private AddressMapper addressMapper;

    @Test
    void test() {
        AddressModel address = new AddressModel();
        address.setAddressId(111L);
        address.setContactMobile("18888888888");
        address.setContactName("Tom");
        addressMapper.insertSelective(address);
    }

}
```

normally when the unit test completed, the transaction will be roll back.
but actually the data `Tom` was still in database, do not roll back.

when i change spring boot version to 2.4.13, the transaction can roll back successfully

**Comment by jingshanglu** [comment]
Maybe it is problem of spring boot, when exception reported, spring not send a `rollback`.

**Comment by user20161119** [comment]
shardingsphere 5.1.0 and spring boot 2.6.3 has the same issue
according transaction log,spring transaction management roll back transaction,but the data saved into db.
![1650537934(1)](https://user-images.githubusercontent.com/123967/164442157-835bfa40-817c-4829-b7a6-062603de0784.png)

**Comment by shangwq** [comment]
@user20161119 downgrade spring boot to 2.6.2 can fix it temporarily.

**Comment by user20161119** [comment]
> @user20161119 downgrade spring boot to 2.6.2 can fix it temporarily.

It's work,thanks

**Comment by user20161119** [comment]
> @user20161119 downgrade spring boot to 2.6.2 can fix it temporarily.

Could you explain the issue and what's the plan for the issue to fix?

thanks

**Comment by user20161119** [comment]
> @shangwq Hello, Can you provide a demo project?

@zjcnb There is a plan to fix the issue?

**Comment by zjcnb** [comment]
@user20161119 @shangwq @jingshanglu Hi, I think this problem not belong `ShardingSphere`. Because, when we use `@Transaction` in unit test. the `isDefaultRollback(TestContext testContext)` method has problem.

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/33742097/164602973-2e69426e-6de1-45c9-b017-9a87f3b36fec.png">

**Comment by user20161119** [comment]
@zjcnb I tested with spring boot 2.6.3 with jdbc,transaction worked as excepted,the data did not save to db

![image](https://user-images.githubusercontent.com/123967/164699298-d24c0316-2643-44c2-9d88-c84d8c7196fb.png)


![image](https://user-images.githubusercontent.com/123967/164699407-a5918e8f-ea76-4588-a1ad-81eb882bef84.png)

**Comment by zjcnb** [comment]
[shardingsphere-jdbc-pools-test.zip](https://github.com/apache/shardingsphere/files/8540243/shardingsphere-jdbc-pools-test.zip)

Refer to this example.

**Comment by user20161119** [comment]
> @user20161119 @shangwq @jingshanglu Hi, I think this problem not belong `ShardingSphere`. Because, when we use `@Transaction` in unit test. the `isDefaultRollback(TestContext testContext)` method has problem.
> 
> <img alt="image" width="1692" src="https://user-images.githubusercontent.com/33742097/164602973-2e69426e-6de1-45c9-b017-9a87f3b36fec.png">

You said the issues is not belong Sharding-jdbc，i tested with jdbc,the transaction work as excepted, the issue is belong to sharding-jdbc?

**Comment by zjcnb** [comment]
> > @user20161119 @shangwq @jingshanglu Hi, I think this problem not belong `ShardingSphere`. Because, when we use `@Transaction` in unit test. the `isDefaultRollback(TestContext testContext)` method has problem.
> > <img alt="image" width="1692" src="https://user-images.githubusercontent.com/33742097/164602973-2e69426e-6de1-45c9-b017-9a87f3b36fec.png">
> 
> You said the issues is not belong Sharding-jdbc，i tested with jdbc,the transaction work as excepted, the issue is belong to sharding-jdbc?

Support your project demo please.

**Comment by user20161119** [comment]
[springtrx.zip](https://github.com/apache/shardingsphere/files/8540408/springtrx.zip)

run junit test `com.example.demo.DBServiceTest.testAdd()`

**Comment by zjcnb** [comment]
\

> [springtrx.zip](https://github.com/apache/shardingsphere/files/8540408/springtrx.zip)
> 
> run junit test `com.example.demo.DBServiceTest.testAdd()`

Did you use shardingsphere for this project???

**Comment by user20161119** [comment]
> @zjcnb I tested with spring boot 2.6.3 with jdbc,transaction worked as excepted,the data did not save to db
> 
> ![image](https://user-images.githubusercontent.com/123967/164699298-d24c0316-2643-44c2-9d88-c84d8c7196fb.png)
> 
> ![image](https://user-images.githubusercontent.com/123967/164699407-a5918e8f-ea76-4588-a1ad-81eb882bef84.png)

This project do not depends on shardingSphere,I just want to verify my above question it's spring boot transaction issue or ShardingSpere issue.

**Comment by shangwq** [comment]
> [shardingsphere-jdbc-pools-test.zip](https://github.com/apache/shardingsphere/files/8540243/shardingsphere-jdbc-pools-test.zip)
> 
> 
> 
> Refer to this example.

upgrade spring boot version to 2.6.4  or above, will be reproduction.

**Comment by yanghao888** [comment]
#18008 Is it the same as this issue?
