### ISSUE TITLE
can not find the correct table name  when column names start with a number

### ISSUE THREAD

**Issue by 1172015211** [apache/shardingsphere#16132]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by 1172015211** [comment]
sql is:"select tbl_jh_form_business_lbe3hyu0.`2520ca0ec87f4395af880b47a50431da` from tbl_jh_form_business_lbe3hyu0_select tbl_jh_form_business_lbe3hyu0 "
SQLStatement tables is null.

sharding-jdbc version is 3.1

**Comment by strongduanmu** [comment]
Hi @1172015211, thank you for your feedback. Can you try latest 5.1.0 version? sharding-jdbc version is 3.1 is too old.

**Comment by 1172015211** [comment]
> Hi @1172015211, thank you for your feedback. Can you try latest 5.1.0 version? sharding-jdbc version is 3.1 is too old.

Thanks for your reply.Since the project framework is relatively old, the version of Sharding-JDBC is 3.1. Can I confirm that this problem will not exist in the higher version of Sharding-JDBC? Can I fix this by tweaking the source code?

**Comment by terrymanu** [comment]
Could try by yourself to confirm it?

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
