### ISSUE TITLE
add github action to generate the nightly build Artifacts

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#16133]
as we know, some users are not convenient to compile the distribution package by up to date code.

so we will add github action to compile the code and upload the artifacts to apache nightly build project to share.

**Comment by taojintianxia** [comment]
anyone see this issue, please assign to me.

**Comment by taojintianxia** [comment]
@sandynz hi there, please assign to me again. just click the wrong button.

**Comment by taojintianxia** [comment]
thank you, @strongduanmu

**Comment by TeslaCN** [comment]
This issue may not in release scope.

**Comment by taojintianxia** [comment]
depends on Apache infra team to assign permission

https://issues.apache.org/jira/browse/INFRA-22987
