### ISSUE TITLE
two update after 3ms interval confilct

### ISSUE THREAD

**Issue by maketubo** [apache/shardingsphere#16146]
### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
1. execute A update ： update table0 set status = "Running" where id = 1;
2. after 3ms
3. execute B update ： update table0 set status = "Success" where id = 1;
4. query table0 where id = 1; we expect that the status of query result is Success

### Actual behavior
but actually the status of query result is Running;
我们做了个实验，在100多次A & B调用中，会有10-30个的结果是Running；
不使用ShardingSphere-JDBC时，这100多次调用都不会出现这样的情况。
请问如何避免这个问题呢，谢谢🙏

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because of the author close it without any reason.
