### ISSUE TITLE
Consider holding all parameter marker segments in SQLStatement

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#16144]
### Is your feature request related to a problem?

Related to #16129. We need to know all the indices of parameter markers to rewrite the SQL to JDBC style.

### Describe the feature you would like.

Could we consider holding all parameter marker segments in `AbstractSQLStatement` like the `comments`?
https://github.com/apache/shardingsphere/blob/bf7a90f2c86cc1fdb97956a123e39b066185b5b6/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/statement/AbstractSQLStatement.java#L32-L37

**Comment by tuichenchuxin** [comment]
I'll solve this issue.
