### ISSUE TITLE
The sample for shardingsphere & seata with XA mode

### ISSUE THREAD

**Issue by LGAKing** [apache/shardingsphere#16156]
## Question

Could someone share me a XA mode sample?

Thanks in advance.

**Comment by zjcnb** [comment]
@LGAKing  Please refer to : https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/transaction-example

**Comment by LGAKing** [comment]
> @LGAKing Please refer to : https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/transaction-example

Thanks! But what I want is an example of XA mode based on shardingsphere and seata

**Comment by lxx-sample** [comment]
+1

**Comment by zhanglaig** [comment]
shardingsphere and seata xa +1

**Comment by FlyingZC** [comment]
Shardingsphere currently does not support the seata xa mode, are you interested in supporting it. @LGAKing You can choose the XA implement based on Narayana and Atomikos.

**Comment by RaigorJiang** [comment]
Without such a plan, I will close this issue.
