### ISSUE TITLE
The sharding-column of database-strategy and table-strategy is the same field , get error。

### ISSUE THREAD

**Issue by GravityMatrix** [apache/shardingsphere#16158]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

version 4.1.1

**Comment by terrymanu** [comment]
Duplicated with #16159
