### ISSUE TITLE
[OpenForce 2022] Optimize official documents

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#16163]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim

Check the source file below, search `确定该issue不是通过简单的检索即可以解决的问题`、`对该issue分配合适的标签 `, `请在选择您要修改的issue` and then  keep a space between Chinese and English words.

Source file:
https://github.com/apache/shardingsphere/blob/master/docs/community/content/contribute/contributor.cn.md

Official document link:
https://shardingsphere.apache.org/community/cn/contribute/contributor/

**Comment by Swastyy** [comment]
Just for OpenForce, I will fix this one, please assign @zjcnb .
