### ISSUE TITLE
File path is incorrect

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#16168]
After the structure of examples module is changed, the path for file `class-based-sharding-algorithm-example` is not updated in this [file](https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/Oct_12_4_Updates_and_FAQ_Your_1_Minute_Quick_Start_Guide_to_ShardingSphere.en.md)

**Comment by RaigorJiang** [comment]
@Swastyy You are so attentive, but the blog of the historical version cannot be modified. So I just close this issue.
