### ISSUE TITLE
[OpenForce 2022] Optimize official documents

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#16175]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441

Aim
Corrected the url field of the data shardingsphere data source configuration.

Tips:

 `spring.shardingsphere.datasource.<actual-data-source-name>.jdbc-url` is right, We need to check that the field in the document is `url` and fix it to `jdbc-url`.

such as :
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/mix/
<img width="872" alt="image" src="https://user-images.githubusercontent.com/29777558/158947106-55c87ba2-bac6-4d00-89e9-0ee755c19144.png">

**Comment by Amulya-coder** [comment]
Hi, I would like to work on this issue, I am a contributor to openforce2022, please assign it to me. Thank you.

**Comment by totalo** [comment]
> Hi, I would like to work on this issue, I am a contributor to openforce2022, please assign it to me. Thank you.

welcome.

**Comment by Amulya-coder** [comment]
Hi, I have created the PR for this issue: https://github.com/apache/shardingsphere/pull/16196

Kindly review it and if there are any modification required, please let me know.
