### ISSUE TITLE
升级到sharding-jdbc-spring-namespace,由3.0.0.M4 至至4.0.1版本和集成的apollo冲突，导致启动失败

### ISSUE THREAD

**Issue by xiaofeixia** [apache/shardingsphere#16182]
升级到sharding-jdbc-spring-namespace，由3.0.0.M4 至4.0.1版本   和集成的apollo冲突，导致启动失败
pom.xml:

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.1</version>
         </dependency>
       <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>1.5.1.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-core</artifactId>
            <version>1.5.1.1-SNAPSHOT</version>
        </dependency>
======================================================================
启动时，报这个错误：
message:Error creating bean with name 'com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor]: Constructor threw exception; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.util.ConfigUtil!,org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor]: Constructor threw exception; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.util.ConfigUtil!

有没有什么好的建议，如何解决？

**Comment by menghaoranss** [comment]
@xiaofeixia for English only, please translate to English first.
