### ISSUE TITLE
batch inserts performance problem

### ISSUE THREAD

**Issue by SanXun99** [apache/shardingsphere#16197]
#### Self-Diagnosis
- [x] I have reviewed the documentation.
- [x] I have reviewed the Wiki.
- [x] I have tried to use the latest version.
- [x] I have searched the issues for an answer to my question. 
- [x] I have searched the web for an answer to my question.

#### Environment
- [x] Operating System: win10
- [x] Plugin version: 5.1
Using the JDBC batch function, insert tens of thousands of data, when you do not use ShardingJDBC, it is less than 1s, and the total consumption of 5s after introducing ShardingJDBC

**Comment by linghengqian** [comment]
I have to say, this issue template doesn't seem to come from ShardingSphere. 👀

**Comment by CrackerSuperior** [comment]
Sharding does have the problem of slow execution efficiency of batch SQL, which is probably caused by using Antlr4. Antlr4 will parse this batch SQL into a syntax tree. It takes a lot of time to traverse the syntax tree, but this is unavoidable.

**Comment by strongduanmu** [comment]
@linghengqian Thank you for your feedback, we are considering optimizing batch performance, see #15995 for details.

**Comment by TeslaCN** [comment]
Duplicate with #15995.
