### ISSUE TITLE
[New Feature] Support system database and schema query statements for MySQL and PostgreSQL

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16234]
## Feature Request

According to the feedback from the community, ShardingSphere currently does not support MySQL and PostgreSQL system databases and schema query statements. When the user executes the following statement, an exception will occur.

```sql
select count(*) from information_schema.TABLES where table_name = #{tableName}
# org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'information_schema' doesn't exist.
```

### Is your feature request related to a problem?

#15327 #11994 #14728 #14347 #13586 #11167

### Describe the feature you would like.

In order to provide support for the MySQL and PostgreSQL system database/schema, we need to adjust the structure of the metadata first, so that the metadata can support the three-tier structure of `database -> schema -> table`.

- [x] adjust the structure of metadata in zookeeper
- [x] adjust metadata initialization logic and kernel usage metadata logic
- [x] initialize calcite metadata with new metadata

New metadata structure:

```
|----metadata
    |----sharding_db
        |----active_version: 0
        |----versions
            |----0
                |----dataSources
                |----rules
        |----schemas
            |----information_schema
                |----tables
                    |----views
            |----pg_catalog
            |----public
                |----tables
                    |----t_order
```

New ShardingSphereMetaData java class:

```java
/**
 * ShardingSphere meta data.
 */
@RequiredArgsConstructor
@Getter
public final class ShardingSphereMetaData {
    
    private final String name;
    
    private final ShardingSphereResource resource;
    
    private final ShardingSphereRuleMetaData ruleMetaData;
    
    private final Map<String, ShardingSphereSchema> schemas;
}
```

After completing the metadata structure adjustment, we need to optimize metadata initialization logic and manually build system databases and schemas for different database dialects. The overall process of initialization is as follows:

![image](https://user-images.githubusercontent.com/10829171/159218342-3633222a-1cfb-42f0-acd7-d242328a451e.png)

Then adjust the execution process, when the query statement contains system databases/tables, we use federation execution engine to execute. 

![image](https://user-images.githubusercontent.com/10829171/159218388-74f08372-a311-4b5e-9fdb-7798b8cfd39f.png)

It is worth noting that we will first return an empty system database/table result set, and then consider using elastic-job to regularly maintain system database/table information to zookeeper after all these tasks are completed.

- [x] optimize metadata initialization logic
- [x] manually build system databases and schemas for different database dialects
- [x] adjust the execution process for system databases/tables query statements

**Comment by strongduanmu** [comment]
All task has been finished, so I will close this issue.

**Comment by shanrenxj** [comment]
Does shardingsphere-jdbc 5.1.2 also support this feature?

**Comment by DoccYi** [comment]
> Does shardingsphere-jdbc 5.1.2 also support this feature?

It seems that the code is not merged into 5.1.2 
[https://github.com/apache/shardingsphere/blob/5.1.1/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java](url)
[https://github.com/apache/shardingsphere/blob/5.1.2/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/ShardingSphereMetaData.java](url)

**Comment by study-renjie** [comment]
Hello, may I know which version supports the schema feature? Currently, I am using version 5.4.0, which does not support this feature yet.

**Comment by strongduanmu** [comment]
> ```sql
> table_name
> ```

Hi, you can submit a bug issue for schema feature.

**Comment by study-renjie** [comment]
> > ```sql
> > table_name
> > ```
> 
> Hi, you can submit a bug issue for schema feature.

i have submit a new issue,Can you tell me how to solve this problem in version 5.4.0？
my new issue is in here.
https://github.com/apache/shardingsphere/issues/28601

**Comment by Dr-wgy** [comment]
ShardingSphere Query Discrepancy
When executing the query SELECT COUNT(1) FROM information_schema.schemata WHERE schema_name='?' LIMIT 1 on ShardingSphere version 5.5.2, I'm encountering an unexpected result.

Specifically:

Direct Query on Target Sharding DB: When this query is run directly on the underlying sharding database, the expected result of 1 is returned.

Query Executed via ShardingSphere: However, when the exact same query is executed through ShardingSphere, the result returned is 0.

This indicates a discrepancy in how ShardingSphere is processing or routing this particular information_schema query, leading to an incorrect count.

There are significant compatibility issues between Flyway and ShardingSphere.
There are significant compatibility issues between hibernate and ShardingSphere. 
  jpa:
    hibernate:
      ddl-auto: update 

Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.apache.shardingsphere.infra.exception.dialect.exception.syntax.table.TableExistsException

@strongduanmu
