### ISSUE TITLE
Upgrade sharding-jdbc-spring-namespace from 3.0.0.M4 to 4.0.1 conflicts with the integrated Apollo, resulting in startup failure

### ISSUE THREAD

**Issue by xiaofeixia** [apache/shardingsphere#16239]
Upgrade sharding-jdbc-spring-namespace from 3.0.0.M4 to 4.0.1 conflicts with the integrated Apollo, resulting in startup failure

pom.xml:
           <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-spring-namespace</artifactId>
                <version>4.0.1</version>
             </dependency>
           <dependency>
                <groupId>com.ctrip.framework.apollo</groupId>
                <artifactId>apollo-client</artifactId>
                <version>1.5.1.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.ctrip.framework.apollo</groupId>
                <artifactId>apollo-core</artifactId>
                <version>1.5.1.1-SNAPSHOT</version>
            </dependency>

======================================================================
This error is reported when starting：
message:Error creating bean with name 'com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor]: Constructor threw exception; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.util.ConfigUtil!,org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ctrip.framework.apollo.spring.property.SpringValueDefinitionProcessor]: Constructor threw exception; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.util.ConfigUtil!

Are there any good suggestions and how to solve this？

**Comment by zjcnb** [comment]
@xiaofeixia The `4.0.1` is too old, can you try it again with `5.1.0` ?

**Comment by TeslaCN** [comment]
Apollo is no longer supported.
