### ISSUE TITLE
Flexible acquisition of encryption module key

### ISSUE THREAD

**Issue by mageeric** [apache/shardingsphere#16251]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Yes

### Describe the feature you would like.

The encryption key is fixed in the configuration file.

I hope I can define the interface and obtain it flexibly, because the key may be in another service.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If you want to continue this topic, please reopen it or submit a new one.
