### ISSUE TITLE
Consider move `StorageRole`and `StorageStatus` to `mode-core` module.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16256]
The `StorageNodeDataSource`, `StorageNodeRole` and `StorageNodeStatus` in `shardingsphere-infra-common`, it doesn't seem to suitable, they are only used by `readwrite-splitting ` and `db-discovery ` feature. I think it better way moved to `mode-core` module. And `mode-core` module as basic module, it can be referenced by `readwrite-splitting ` and `db-discovery`. So i will adjust it.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/33742097/159410606-617c86f5-c950-4f1d-a505-d5792e0aa5a4.png">

**Comment by TeslaCN** [comment]
Hi @zjcnb 
Any update here? Could we finish this in 5.1.1?

**Comment by zjcnb** [comment]
> Hi @zjcnb Any update here? Could we finish this in 5.1.1?

@TeslaCN Hi, i 'm not confirm. i will do it after version 5.1.1.
