### ISSUE TITLE
Proxy support schema lock for stop write in cluster mode

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#16269]
## Feature Request

Proxy support global schema lock in cluster mode

### Describe the feature you would like.

Proxy support schema level stop write lock in cluster mode

**Comment by TeslaCN** [comment]
Hi @soulasuna 
Any update here? Could we finish this in 5.1.1?

**Comment by soulasuna** [comment]
Hi @TeslaCN
There will also be an update on intercepting DistSQL.
Others need to be supplemented by @sandynz.

**Comment by sandynz** [comment]
Hi @TeslaCN , @soulasuna , scaling integration with schema lock is done, this part will be released in 5.1.1

**Comment by soulasuna** [comment]
The basic function of the non-reentrant global distributed lock is completed.
Implemented:
1. Schema-level distributed lock based on zookeeper.
2. Lock and unlock can be performed in different `Proxy` nodes for the same Schema.
3. In the locked state, newly joined cluster `Proxy` nodes can lock the schema synchronously.
