### ISSUE TITLE
Add more unit test for ClassBasedShardingAlgorithmFactory

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16284]
Hi community,

We need to add more unit test for ClassBasedShardingAlgorithmFactory.

- [ ] ClassBasedShardingAlgorithmFactory#newInstance

**Comment by akhil9281** [comment]
Hi @strongduanmu I would like to work on this issue under OpenForce2022, Thank You!

**Comment by strongduanmu** [comment]
@akhil9281 Welcome, I will assign this issue to you.

**Comment by akhil9281** [comment]
Thank you @strongduanmu ,, could you please guide me on how can I add more unit test for ClassBasedShardingAlgorithmFactory ?

**Comment by strongduanmu** [comment]
Hi @akhil9281, `ClassBasedShardingAlgorithmFactory` is a factory class for building `StandardShardingAlgorithm`, `ComplexKeysShardingAlgorithm` and `HintShardingAlgorithm`, so we need to test the instantiation of these three algorithms. Also, in addition to the `newInstance` method, there are `setProperties` and `init` logic that need to be overridden in unit tests.

**Comment by akhil9281** [comment]
okay @strongduanmu,, let me study it and I'll get back to you!

**Comment by strongduanmu** [comment]
Hi  @akhil9281 , `ClassBasedShardingAlgorithmFactory` is a factory class used to create `ClassBasedShardingAlgorithm`. You only need to mock some input parameters, and then judge the result through assertion.

If you don't know where to start, you can refer to `DatabaseBackendHandlerFactoryTest`, which is a typical factory class unit test.

**Comment by terrymanu** [comment]
@akhil9281 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by lushaorong** [comment]
I want to try this work
