### ISSUE TITLE
Add more unit test for TableRule

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16289]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for TableRule.

- [x] TableRule#getDataNodeGroups
- [x] TableRule(final Collection<String> dataSourceNames, final String logicTableName)

**Comment by yangsen00** [comment]
hello, I would like to have a try

**Comment by strongduanmu** [comment]
@yangsen00 Welcome.

**Comment by yangsen00** [comment]
hello,could this close?
