### ISSUE TITLE
Need Fix `cluster-mode-spring-namespace-mybatis-example` module

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16282]
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/33742097/159611953-db6d3624-a129-47eb-a4cc-ea936171b2d2.png">

**Comment by soumya-dash3** [comment]
Hello @zjcnb. I'm a contributor at Open-Force. Can this issue be assigned to me? Thanks

**Comment by yx9o** [comment]
@soumya-dash3 Welcome.

**Comment by zjcnb** [comment]
@soumya-dash3  Hi, are you still watching this mission?

**Comment by soumya-dash3** [comment]
Actually got it assigned being a part of open-force. So...

**Comment by mabaiwan** [comment]
Can I try this issue?

**Comment by strongduanmu** [comment]
@mabaiwan Welcome.
