### ISSUE TITLE
Add more unit test for ShardingRule

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16288]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for ShardingRule.

- [ ] ShardingRule#getDatabaseShardingStrategyConfiguration
- [ ] ShardingRule#getTableShardingStrategyConfiguration
- [ ] ShardingRule#isGenerateKeyColumn
- [ ] ShardingRule#getShardingRuleTableNames
- [ ] ShardingRule#getLogicAndActualTablesFromBindingTable
- [ ] ShardingRule#getAllDataNodes
- [ ] ShardingRule#findFirstActualTable
- [ ] ShardingRule#isNeedAccumulate
- [ ] ShardingRule#findActualTableByCatalog

Since this issue contains many sub-tasks, you can choose one or more of them to participate.

**Comment by strongduanmu** [comment]
Since this issue contains many sub-tasks, you can choose one or more of them to participate.

**Comment by ntsompa** [comment]
Hello, i am interested in 'tackling' some of this issues. Could you please give me some guidance?

**Comment by acmenlt** [comment]
@strongduanmu Hi, I can do all these tasks, or I can be randomly assigned to some of them.

**Comment by strongduanmu** [comment]
@ntsompa @acmenlt Welcome. You can do any tasks on this list, as long as you declare it in this issue.

**Comment by acmenlt** [comment]
@ntsompa If there's no problem, I'll finish the first half

- [ ]  ShardingRule#getDatabaseShardingStrategyConfiguration
- [ ]  ShardingRule#getTableShardingStrategyConfiguration
 - [ ] ShardingRule#isGenerateKeyColumn
 - [ ] ShardingRule#getShardingRuleTableNames
 - [ ] ShardingRule#getLogicAndActualTablesFromBindingTable

**Comment by ntsompa** [comment]
@acmenlt No problem at all, if you want you can also do the rest. No worries.

**Comment by longtai-cn** [comment]
@ntsompa Hello, do you have time to finish the remaining tasks.

**Comment by ntsompa** [comment]
@longtai-cn Hello, you could take them if you want, i don't have much time lately.

**Comment by longtai-cn** [comment]
> @longtai-cn Hello, you could take them if you want, i don't have much time lately.

@ntsompa nYes, thank you
