### ISSUE TITLE
Add more unit test for InlineExpressionParser

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16283]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for InlineExpressionParser.

- [ ] InlineExpressionParser#isInlineExpression
- [ ] InlineExpressionParser#handlePlaceHolder
- [ ] InlineExpressionParser#evaluateClosure

**Comment by ismailalammar** [comment]
Hi , i would like contribute under OpenForce 2022 , could you please assign this issue to me ?

**Comment by strongduanmu** [comment]
@ismailalammar Welcome, I will assign this issue to you.

**Comment by ismailalammar** [comment]
Thanks @strongduanmu , could you please guid me on the testing mechanism for `InlineExpressionParser#evaluateClosure` ?

**Comment by ismailalammar** [comment]
Hi @strongduanmu , i've submitted a PR for this issue. Thanks!

**Comment by strongduanmu** [comment]
> Hi @strongduanmu , i've submitted a PR for this issue. Thanks!

Good job, I will review this pr.
