### ISSUE TITLE
Add more unit test for DatabaseTypeFactory

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16293]
Hi community,

We need to add more unit test for DatabaseTypeFactory.

- [ ] DatabaseTypeFactory#getDatabaseType

**Comment by jenil2401** [comment]
Hi I would like to work on this issue under OpenForce 2022. Can you please assign this issue to me? And also if possible suggestion on how to get started with this issue?

**Comment by totalo** [comment]
> Hi I would like to work on this issue under OpenForce 2022. Can you please assign this issue to me? And also if possible suggestion on how to get started with this issue?

hi @jenil2401 , welcome, You can search for the DatabaseTypeFactory class and add unit tests for the getDatabaseType method of this class.

**Comment by terrymanu** [comment]
@jenil2401 Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by zrsaber** [comment]
please assign it to me, i will have a try

**Comment by strongduanmu** [comment]
@zrsaber Welcome aboard.
