### ISSUE TITLE
Optimization DistSQL RAL `show readwrite_splitting read resources` result

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16298]
I think not need to show `delay_time (ms)` column when use `MGR` database discovery type.

```
mysql> show readwrite_splitting read resources;
+----------+---------+-----------------+
| resource | status  | delay_time (ms) |
+----------+---------+-----------------+
| ds_1     | enabled |                 |
| ds_2     | enabled |                 |
+----------+---------+-----------------+
```

**Comment by RaigorJiang** [comment]
If this `delay_time` is not displayed only in MGR mode, it will cause the result set of this DistSQL to be unstable, I think this is not a good idea.

**Comment by zjcnb** [comment]
> If this `delay_time` is not displayed only in MGR mode, it will cause the result set of this DistSQL to be unstable (means the same input, will get different columns), I think this is not a good idea.

Yeah, let's keep the this result style.  I close this issue.
