### ISSUE TITLE
Add more unit test for ShardingRuleConfigurationConverter 

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16291]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for ShardingRuleConfigurationConverter.

- [ ] ShardingRuleConfigurationConverter#findAndConvertShardingRuleConfiguration

**Comment by ntsompa** [comment]
Hello, i am interested in this one. Could you please help me with some guidelines on how to work with it? Thank you.

**Comment by strongduanmu** [comment]
@ntsompa Welcome, you can refer ShardingRuleConfigurationYamlSwapperTest class.

**Comment by acmenlt** [comment]
@strongduanmu Please assign it to me.

**Comment by strongduanmu** [comment]
@acmenlt Welcome.
