### ISSUE TITLE
Add more unit test for ShardingRuleAlgorithmProviderConfigurationYamlSwapper

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16290]
Hi community,

We need to add more unit test for ShardingRuleAlgorithmProviderConfigurationYamlSwapper.

- [x] ShardingRuleAlgorithmProviderConfigurationYamlSwapper#swapToYamlConfiguration
- [x] ShardingRuleAlgorithmProviderConfigurationYamlSwapper#swapToObject

**Comment by ntsompa** [comment]
Hello, i am interested in working with this issue. Could you please assist me with it? Maybe an existing example. Thank you in advance.

**Comment by itsAfnanAlam** [comment]
Hi @strongduanmu,
I would like to work on this issue. Can you assign this to me?

**Comment by strongduanmu** [comment]
@itsAfnanAlam Welcome, I will assign this issue to you.

**Comment by itsAfnanAlam** [comment]
Thank you @strongduanmu,  could you please guide me on how can I add more unit tests for ShardingRuleAlgorithmProviderConfigurationYamlSwapper?

**Comment by strongduanmu** [comment]
@itsAfnanAlam You can refer to EncryptRuleAlgorithmProviderConfigurationYamlSwapperTest.

**Comment by terrymanu** [comment]
@itsAfnanAlam Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by lushaorong** [comment]
I want to try this work

**Comment by terrymanu** [comment]
> * ShardingRuleAlgorithmProviderConfigurationYamlSwapper

Get getRuleTagName, getOrder and getTypeClass are static impl, do not need add test cases, I just remove them

**Comment by terrymanu** [comment]
The test coverage does not reach 100% for `setYamlStrategies` `swapToObject` and `setStrategies`.
We need to add more test cases for this class.

**Comment by terrymanu** [comment]
This issue contains lots message, I just close this one and create a new one to continue.
