### ISSUE TITLE
Test case `ClusterContextManagerCoordinatorTest#assertDisableStateChanged` has no assertion

### ISSUE THREAD

**Issue by devfat** [apache/shardingsphere#16295]
Test case `ClusterContextManagerCoordinatorTest#assertDisableStateChanged` has no assertion. 
```
    @Test
    public void assertDisableStateChanged() {
        DisabledStateChangedEvent event = new DisabledStateChangedEvent(new QualifiedSchema("schema.readwrite_ds.ds_0"), true);
        coordinator.renew(event);
    }
```

It doesn't meet [code of conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/):
> Every test case need precised assertion.

**Comment by zjcnb** [comment]
@devfat Can you fix it?

**Comment by devfat** [comment]
> @devfat Can you fix it?

Okey, I will try to fix it.

**Comment by zjcnb** [comment]
> > @devfat Can you fix it?
> 
> Okey, I will try to fix it.

Okay.
