### ISSUE TITLE
Add more unit test for TrafficStrategyConfigurationYamlSwapper

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16292]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for TrafficStrategyConfigurationYamlSwapper.

- [ ] TrafficStrategyConfigurationYamlSwapper#swapToYamlConfiguration
- [ ] TrafficStrategyConfigurationYamlSwapper#swapToObject

**Comment by weihubeats** [comment]
hey, can I try this issue?

**Comment by strongduanmu** [comment]
@weihubeats Of course, I will assign this issue to you.
