### ISSUE TITLE
[OpenForce 2022]  Remove useless `worker-id` props  for sharding key generator

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#16302]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background
Previously, we needed to specify the `worker-id` when creating a `snowflake` key generator object.
But now that `worker-id` has been changed to a process-level configuration, there is no need to specify this parameter for each key generator.

### Aim
Remove useless `worker-id` props as in #15608.

for example:
- in `ShowShardingTableRulesUsedAlgorithmQueryResultSetTest.java`
```java
private ShardingSphereAlgorithmConfiguration createKeyGeneratorConfiguration() {
        Properties props = new Properties();
        props.put("worker-id", "123");
        return new ShardingSphereAlgorithmConfiguration("SNOWFLAKE", props);
    }
```

change it to 
```java
private ShardingSphereAlgorithmConfiguration createKeyGeneratorConfiguration() {
        return new ShardingSphereAlgorithmConfiguration("SNOWFLAKE", new Properties());
    }
```

You can find similar code in:
- `ShardingKeyGeneratorsQueryResultSetTest.java`
- `UnusedShardingKeyGeneratorsQueryResultSetTest.java`
also please change them.

### Basic Qualifications

- Java
- Maven

**Comment by abhijeetjejurkar** [comment]
hey, can I try this issue?

**Comment by RaigorJiang** [comment]
Sure, I'll assign it to you @abhijeetjejurkar .
