### ISSUE TITLE
Show error message: Route table null does not exist, available actual table

### ISSUE THREAD

**Issue by dawson-ao** [apache/shardingsphere#16343]
### Which version of ShardingSphere did you use?

5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

 ShardingSphere-JDBC 

### Expected behavior

insert data to databases and success.

### Actual behavior

show message:

Route table null does not exist, available actual table

### SQL: INSERT INTO user   ( id,  `name`,  age )  VALUES   ( ?,  ?,  ? )
@Service
public class UserServiceImpl extends ServiceImpl<UserDao, User> implements UserService {
//	@Autowired
//	private UserMapper userMapper;

	@Override
	public int saveUser(User user) {
		user.setId(System.currentTimeMillis());
		insert(user);
		return 1;
	}

**Comment by zjcnb** [comment]
@dawson-ao Hi, Please provide your configuration.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
