### ISSUE TITLE
Incorrect locale and charset cause exception "ERROR 2027 (HY000): Malformed packet" when using sharding-proxy

### ISSUE THREAD

**Issue by caohuanglin** [apache/shardingsphere#16348]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Actual behavior
mysql is utf-8.
Centos which is deployed sharding-proxy is "POSIX".
When i try to connect the sharding-proxy which is deploy on Centos with locale is "POSIX" as shown on the left of the picture,i find clients including mysql command,navicat,data-grip and java-app using mybatis couldnt get query result and throw exception `"ERROR 2027 (HY000): Malformed packet"`.But Only when some Chinese data in the table,it didnt work.If there are no Chinese in the table, it still could query right result.
![image](https://user-images.githubusercontent.com/22470050/159961167-09c85e07-52b8-4096-a677-4e622ca6cfe7.png)

### Reason analyze (If you can)
I think it caused by locale and mysql charset. Because of only throwing exception when tables contain Chinese.When i change the locale to the UTF-8 as shown on the right of the picture,It works normally now.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Change the sharding-proxys server locale to which cant support data in your table, like Chinese.

![image](https://user-images.githubusercontent.com/22470050/159953573-136538c5-1bed-4681-a18d-8272d0685084.png)

After all,I think it is nessasary for reminding people to check locale on the sharding-proxy server, especially for Non English developers.Can anyone add some tips into the quick start or deploy guides?

**Comment by TeslaCN** [comment]
Hi @caohuanglin 
Could you try the master branch? We have did some enhancements about charset in master branch. You may find the daily build in https://github.com/apache/shardingsphere/pkgs/container/shardingsphere-proxy.

**Comment by terrymanu** [comment]
No feedback, closed
