### ISSUE TITLE
[OpenForce 2022] Add more unit test for `AlterInstanceHandler`

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16359]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441

We need to add more unit tests for AlterInstanceHandler to cover the thrown exception

- [ ] AlterInstanceHandler

Example FYI
- AlterTrafficRuleHandlerTest

**Comment by ismailalammar** [comment]
Hi @lanchengx  i would like to work on this issue , could you please assign this issue to me? And also if possible suggestion on how to get started with this issue. Thanks

**Comment by strongduanmu** [comment]
@ismailalammar Welcome, you can refer AlterTrafficRuleHandlerTest, it give an good example.

**Comment by ismailalammar** [comment]
Hi @strongduanmu i've submitted a PR regarding this issue , kindly let me know if there is any issue.

Thanks
