### ISSUE TITLE
[OpenForce 2022]  Add logback configuration instructions for Proxy.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#16356]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background
ShardingSphere-Proxy uses `logback` to output logs, and we provide a new feature to support custom log splitting. 
Please refer to #16333 and #16336.

### Aim
Added new documentation pages to describe default logging configurations (like levels, which are in logback.xml) and provide examples of several customization scenarios.
The new documentation page will be shown [here](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/).

### How to
1. Add a new directory under [user manual of Proxy](https://github.com/apache/shardingsphere/tree/master/docs/document/content/user-manual/shardingsphere-proxy), named `logging`. 
2. Create a new markdown file in the directory `logging`, the file name will be `_index.en.md`.
3. Add some descriptions to `_index.en.md` according to your understanding of [logback.xml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/logback.xml).
4. To understand the content of [#16333](https://github.com/apache/shardingsphere/issues/16333) and [#16336](https://github.com/apache/shardingsphere/pull/16336), add some custom examples in `_index.en.md`.
5. Don't worry about `_index.cn.md`, let the contributors who are familiar with Chinese to handle it

### Basic Qualifications
- Markdown
- XML
- Logback

**Comment by Swastyy** [comment]
Hi @RaigorJiang , I will do this and other assigned to me tasks for openforce in some time. Please assign to me for english version. Thanks.

**Comment by RaigorJiang** [comment]
OK @Swastyy , glad to see you!

**Comment by acmenlt** [comment]
@RaigorJiang `_index.cn.md` Can I claim this task

**Comment by RaigorJiang** [comment]
Hi @acmenlt, nice to see you here!  
Sure, you can take it, thanks for your help!

**Comment by acmenlt** [comment]
@RaigorJiang Hi, now the weight of logging and startup is 1. Which one has the highest priority.

![image](https://user-images.githubusercontent.com/77398366/161409846-9be05235-ec55-4cea-842a-e5a20de6da64.png)
![image](https://user-images.githubusercontent.com/77398366/161409851-541c78b8-21be-4457-831c-1a1e1cc3f2c3.png)

**Comment by acmenlt** [comment]
@RaigorJiang I think startup should have a higher priority.

**Comment by RaigorJiang** [comment]
> logging module for proxy explained #16541

@acmenlt  Yes, I agree with you. 👍
