### ISSUE TITLE
Does shardingsphere-jdbc support different type datasources at the same time in one project？

### ISSUE THREAD

**Issue by yanweimiao** [apache/shardingsphere#16355]
Does shardingsphere-jdbc support different type datasources such as mysql and oracle at the same time in one project？

**Comment by strongduanmu** [comment]
Hi @yanweimiao, shardingsphere-jdbc does not support different type datasources now, but we will support this feature in the future.

**Comment by yanweimiao** [comment]
What is the expected release date for this function？

**Comment by TeslaCN** [comment]
It has been supported since 5.3.0.
