### ISSUE TITLE
[OpenForce 2022] Add SQL parser test case for `ALTER INSTANCE instanceId SET XA_RECOVERY_NODES = value1,value2`.

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16357]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441

### Background
`ALTER INSTANCE instanceId SET XA_RECOVERY_NODES  = value` is a syntax in DistSQL RAL, when ShardingSphereSQLParserEngine receives this SQL text, it parses it as AlterInstanceStatement. 

Currently we have enhanced the syntax from `ALTER INSTANCE instanceId SET XA_RECOVERY_NODES = value` to `ALTER INSTANCE instanceId SET XA_RECOVERY_NODES = value1,value2`. Therefore, it is necessary to **add a parsing test that supports multiple values**.

### Aim
Add SQL parser test case for  `ALTER INSTANCE instanceId SET XA_RECOVERY_NODES = value1,value2`.

- Affected files:
   - shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/common.xml(modify)
   - shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/common.xml(modify)

After all, execute DistSQLParserParameterizedTest#assertDistSQL() for validation

### Basic Qualifications
Java
Maven
### Example FYI
 - shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/common.xml:104 `(alter-instance sql-case-id="alter-instance-xa-recovery-nodes")`
 - shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/common.xml:55 `(distsql-case id="alter-instance-xa-recovery-nodes)`

search for "alter-instance-xa-recovery-nodes"

**Comment by Amulya-coder** [comment]
Hi, @lanchengx I would like to work on this issue under OpenForce2022. Thanks.

**Comment by lanchengx** [comment]
@Amulya-coder  welcome
