### ISSUE TITLE
Update SQL parse engine api usage in document

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16364]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

Due to changes in the API of the SQL parse engine, we need to update the usage examples in the official documentation.

You can find target in this link, https://shardingsphere.apache.org/document/current/cn/reference/sharding/parse/.

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/10829171/160071498-adfa974b-89ed-4b84-8119-60606ae7a1fe.png">

- [ ] Update SQLParserEngine usage examples
- [ ] Update SQLVisitorEngine usage examples

Since the document contains both Chinese and English versions, please modify them at the same time.

**Comment by Amulya-coder** [comment]
Hi @strongduanmu I would like to work on this issue under OpenForce2022, Thanks.

**Comment by strongduanmu** [comment]
@Amulya-coder Welcome.

**Comment by Amulya-coder** [comment]
@strongduanmu could you please guide me on how can I update the usage examples

**Comment by strongduanmu** [comment]
@Amulya-coder Have you read the content of the issue carefully? You can complete this issue by following the previous steps.
