### ISSUE TITLE
I want use sharding-jdbc directly in benchmark tools, but sharding-jdbc not support.

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#16367]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
jmeter and benchmarksql tools can't direct run with sharding-jdbc.
### Describe the feature you would like.
I thinks sharding-jdbc can implements java.sql.Driver standard(declare SPI).
And use unique jdbc prefix like: jdbc:shardingjdbc://sharding_yaml=/opt/config&&database_typ=openGauss&&otherparam .....
So user can only change the config and add sharding-jdbc jar to classpath, this may be work.

**Comment by TeslaCN** [comment]
Close via https://github.com/apache/shardingsphere/pull/17602
