### ISSUE TITLE
SchemaMetaDataNode.getFullMetaDataPath(final String schemaName, final String node) add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16385]

**Comment by ntsompa** [comment]
Hello i am interested in this one. Could you please help me with where the unit tests are supposed to be written for each part? Thank you in advance.

**Comment by zjcnb** [comment]
Please add unit tests in class `SchemaMetaDataNodeTest`

**Comment by ntsompa** [comment]
Hello, i notice that the SchemaMetaDataNode.getFullMetaDataPath() is a private method, so how am i supposed to call it from the test class? Also, which values should i use as its parameters in order to test it? Thank you in advance.

**Comment by zjcnb** [comment]
> Hello, i notice that the SchemaMetaDataNode.getFullMetaDataPath() is a private method, so how am i supposed to call it from the test class? Should I create a public method to call it for testing? Also, should i use specific values as its parameters in order to test it? Thank you in advance.

Sorry, this is private method, it needn't add unit test. Close it.
