### ISSUE TITLE
SchemaMetaDataNode.getDatabaseNamePath(final String databaseName) add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16384]

**Comment by ntsompa** [comment]
Hello i am interested into this one. Thank you.

**Comment by zjcnb** [comment]
> Hello i am interested into this one. Thank you.

Please completed it first https://github.com/apache/shardingsphere/issues/16385 .

**Comment by ntsompa** [comment]
Hello, i think i solved this one, may i open a pull request? Thank you.

**Comment by ismailalammar** [comment]
Hi @zjcnb , would like to contribute to solve this issue ,  if it is still open and not assigned to anyone
