### ISSUE TITLE
Example improvement plan ||

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#16404]
Now the brand new example module has been initially completed, and the shardingshere-jdbc example is ready to use, but there are many areas that can be optimized.

Task:
- [x] Add verification of `config.yaml` configuration to provide user-friendly prompts
- [ ] Supports the combined generation of transaction, product, and operational modes

relate #12366

**Comment by ShiFengCui** [comment]
assign me please

**Comment by strongduanmu** [comment]
@ShiFengCui Welcome.

**Comment by TeslaCN** [comment]
Examples are not in release scope. I will remove the milestone for now.
