### ISSUE TITLE
如何实现不带分片键使用Hint，带分片键时使用分片算法？

### ISSUE THREAD

**Issue by udrnrso** [apache/shardingsphere#16442]
假设分片字段是user_id
在不带user_id条件时，如下面sql，希望能强制指定分片号
// 强制指定使用分片00
select * from tableA limit 500
在带user_id条件时，使用分片算法
select * from tableA where user_id = 'testuser' 

看了文档好像只能hint/standard 二选 一，是否支持混合使用呢？

**Comment by RaigorJiang** [comment]
Hello @udrnrso,  for English only, please translate, thank you.
