### ISSUE TITLE
Fail to execute RDL in DBeaver, error message is: This version of ShardingSphere-Proxy doesn't yet support this SQL

### ISSUE THREAD

**Issue by NJCrazyRen** [apache/shardingsphere#16448]
I used ShardingSphere-proxy 5.1.0 for decrypt data purpose.

I tried to set the rule with RDL sql below:
`CREATE ENCRYPT RULE spcm_pc_partner (
COLUMNS(
(NAME=tel_num,CIPHER=tel_num,TYPE(NAME=SRM_DATA_AES)),
(NAME=bank_account_num, CIPHER=bank_account_num,TYPE(NAME=SRM_DATA_AES))
)`
My db table's name is 'spcm_pc_partner' and custom encryptor named 'SRM_DATA_AES'. I'm sure this custom encryptor is available
because another rule using the encryptor defined in config-xx.yaml works well.

But I got an error:
`SQL error [1235] [42000]: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'`

Is there some syntax wrong in the RDL sql?

**Comment by lanchengx** [comment]
@NJCrazyRen Hi，I find that your statement seems to be missing a `)`

```
CREATE ENCRYPT RULE spcm_pc_partner ( 
   COLUMNS( 
      (NAME=tel_num,CIPHER=tel_num,TYPE(NAME=SRM_DATA_AES)), 
      (NAME=bank_account_num, CIPHER=bank_account_num,TYPE(NAME=SRM_DATA_AES)) 
   )
```

**Comment by NJCrazyRen** [comment]
> @NJCrazyRen Hi，I find that your statement seems to be missing a `)`
> 
> ```
> CREATE ENCRYPT RULE spcm_pc_partner ( 
>    COLUMNS( 
>       (NAME=tel_num,CIPHER=tel_num,TYPE(NAME=SRM_DATA_AES)), 
>       (NAME=bank_account_num, CIPHER=bank_account_num,TYPE(NAME=SRM_DATA_AES)) 
>    )
> ```

Oh, it's my mistake. I'm careless. I have corrected the sql and test. It works as expected. Thanks.

**Comment by lanchengx** [comment]
ok, i will close this issue
