### ISSUE TITLE
[OpenForce 2022] Modify capitalization of keywords in RAL grammar documents

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16455]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441

### Background
DistSQL（Distributed SQL）is Apache ShardingSphere specific SQL. 

In documentation we usually use all uppercase words for grammar keywords and camel case for grammar variables. 
For example, in the syntax `ADD RESOURCE dataSource`,  `ADD` and `RESOURCE` are syntax keywords,  `dataSource` is variable

### Aim
Modify grammar keywords in documents to uppercase.

The following files need to be modified
-  docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/_index.en.md
- docs/document/content/user-manual/shardingsphere-proxy/distsql/syntax/ral/_index.cn.md
### How to

1. Open the grammar document that needs to be modified
2. Find the column that needs to be modified. The `Statement` column and `Example` in the table are the columns that need to be modified
3. Identify syntax keywords.
    - Determined by the grammar definition file.

The grammar definition file is as follows

- shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/imports/RALStatement.g4
- shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-parser/src/main/antlr4/imports/readwrite-splitting/RALStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/sharding/RALStatement.g4
- shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4/imports/scaling/RALStatement.g4

### Example

Take modifying `set readwrite_splitting hint source = [auto/write]` as an example.

Search `set readwrite_splitting hint source` to determine the file where the grammar is located is `shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-distsql/shardingsphere-readwrite-splitting-distsql-parser/src/main/antlr4/imports/ readwrite-splitting/RALStatement.g4`.

The syntax is defined as `SET READWRITE_SPLITTING HINT SOURCE EQ sourceValue` .

So `set readwrite_splitting hint source = [auto/write]` should be changed to `SET READWRITE_SPLITTING HINT SOURCE = [auto/write]`

### Example FYI
[RAL::Global Rule](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/#global-rule)

**Comment by ritikBhandari** [comment]
Hi,
Can I work on this?

**Comment by lanchengx** [comment]
@ritikBhandari Welcome

**Comment by KALYAN393** [comment]
Hi, as this is my first contribution so i think that this issue is good to start, kindly allow me to work on this issue if possible.

**Comment by lanchengx** [comment]
@KALYAN393 Sorry, already assigned to @ritikBhandari .

**Comment by ritikBhandari** [comment]
`_index.cn.md` is also to be modified?

**Comment by ritikBhandari** [comment]
I guess `cn` means Chinese. Right?

**Comment by lanchengx** [comment]
> `_index.cn.md` is also to be modified?

Yeah, it needs to be modified.

**Comment by ritikBhandari** [comment]
But most of the content is in Chinese ig. Is there any catch to modify it or manual translation?

**Comment by lanchengx** [comment]
Like `_index.en.md`, only need to adjust the `语句` and `示例 ` columns, the Chinese part does not need to be modified

**Comment by lanchengx** [comment]
If you find it difficult, you can also just adjust `_index.en.md`

**Comment by ritikBhandari** [comment]
> If you find it difficult, you can also just adjust `_index.en.md`

No if its just those columns in `_index.cn.md` which need to be modified, I'll do it.
Thanks!

**Comment by ritikBhandari** [comment]
Plz review the PR I've opened for the issue. If this one is correct, I'll do the same for `_index.cn.md` file

**Comment by ritikBhandari** [comment]
@terrymanu I have resolved the issue for _index.cn.md as well. You can consider it if you want.

**Comment by ritikBhandari** [comment]
> @ritikBhandari it is wanted. I will merge your other PR soon

Thank you:)
