### ISSUE TITLE
The problem of association between two sub-tables

### ISSUE THREAD

**Issue by zm52hz** [apache/shardingsphere#16469]
## Question
version : ShardingSphere-JDBC 5.1.0

According to the logic of ShardingSphere, the query condition has no sharding field and the routing engine will use the Cartesian product for it.
Now we have the following SQL:
   SQL1: select a.id ,a.time,b.id from photo a left join alarm_photo b on a.alarm_id = b.id 
Logic Table photo has two actual tables:  photo_202201,photo_202203 ,  two months has one actual table;
Logic Table alarm_photo has three actual tables: alarm_photo_202201,alarm_photo_202202,alarm_photo_202203, one months has one acutal table;
Logic table photo has one data :[ id：1、date:'20220201'  ]、and the data is in actual table photo_202201
Logic alarm_photo has no data.
Now I execute the above SQL1(left join ! not right join)、and get the three results: 
[id:1,time:'20220201', id null],[id:1,time:'20220201', id null],[id:1,time:'20220201', id null]

This is not what I expected, I think there should be only one data. 
Why is this, I know it's caused by the Cartesian product, but why doesn't ShardingSphere solve this problem?
Can you give me an answer ？thanks.

**Comment by RaigorJiang** [comment]
This problem is not easy to solve.
Hi @strongduanmu  Can you provide some suggestions?

**Comment by strongduanmu** [comment]
@zm52hz Thank you for your feedback, this maybe a bug, I will investigate this problem.

**Comment by strongduanmu** [comment]
Duplicate with #14418.
