### ISSUE TITLE
About user customize sql with force index

### ISSUE THREAD

**Issue by yaofeng8888** [apache/shardingsphere#16481]
## Question
sharding-jdbc-core ：version 3.1.0
sharding-jdbc-spring-namespace : version 3.1.0
desc:
 when i was use force index,the program error 。
 java.sql.SQLSyntaxErrorException: Key 'idx_createdon_WT_WRONG_0' doesn't exist in table 'WT_WRONG_0'
 but "idx_createdon" is my index, "WT_WRONG" is table name
the sql operation result is ：select * from WT_WRONG force index(idx_createdon)
 
thanks

**Comment by RaigorJiang** [comment]
Hi @yaofeng8888 
version 3.1.0 is no longer maintained, it is recommended that you try the new version.

**Comment by yaofeng8888** [comment]
Hi RaigorJiang
thank for your replay
My program was online 。i can not upgrade the version。i konw the sharding-jdbc use ‘’index+table name‘’ and rename to used as index name, 
the 3.1.0 version was not support to user force index? 
Or with some configuration to solve this error

**Comment by RaigorJiang** [comment]
@yaofeng8888 
Sorry for the late reply. 
In the sharding scenario, the actual table name has been rewritten according to the algorithm, and the index name will also be rewritten. It is difficult for users to specify a clear index through SQL.
Therefore, this method is not feasible.
