### ISSUE TITLE
version 5.1.0 shardingsphere-jdbc-spring-boot-starter package can not find interface  PreciseShardingAlgorithm

### ISSUE THREAD

**Issue by superme-ray** [apache/shardingsphere#16480]
its bug？？

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.0</version>
        </dependency>

implement interface PreciseShardingAlgorithm，not found！！！！

**Comment by linghengqian** [comment]
PreciseShardingAlgorithm was cancelled after 5.0.0-alpha. You should use the new API.

**Comment by superme-ray** [comment]
please update document！！！

**Comment by beareverse** [comment]
真服了官方了
