### ISSUE TITLE
Does Shardingsphere support add datasource dynamically?

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#16509]
Now we have a scenario where the data of different users are placed in different databases (i.e. data sources).
But now I write all databases in the configuration file. Every time a new user is added to our system, I need to add a new data source to the configuration file and restart the shardingsphere proxy.
Is there a way for me to dynamically load these data sources? And allocate these databases according to the rules I make.

Thank  you!

**Comment by strongduanmu** [comment]
@VeejaLiu Yes, you can use distsql to add datasource dynamically. For more details about distsql, you can refer this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/).

**Comment by VeejaLiu** [comment]
@strongduanmu Thank you very much!!! Sincerely wish shardingsphere better and better!!!

**Comment by strongduanmu** [comment]
@VeejaLiu If you encounter any problems in the process of using distsql, welcome to communicate in the community.

**Comment by VeejaLiu** [comment]
@strongduanmu Okay!!! Thank you!!!
