### ISSUE TITLE
new ShardingSphereDataSource() is too slowly

### ISSUE THREAD

**Issue by irwinai** [apache/shardingsphere#16515]
I got 20 database strategy and 1 read-write spliting 
so total I have 40 db datasource.
such as :
ds$->{1..40}.trade

finally , I found that the new ShardingSphereDataSource using 1mintute to start.
so
can you tell me how can i make this fast?

**Comment by irwinai** [comment]
It looks like the SchemaRulesBuilder -> buildRules -> DatabaseTypeRecognizer.getDatabaseType
is too slow

**Comment by tuichenchuxin** [comment]
What's your version? JDBC or Proxy?

**Comment by irwinai** [comment]
5.0.0 JDBC

**Comment by irwinai** [comment]
I found that getConnenction is too slowly.
```
private static DatabaseType getDatabaseType(final DataSource dataSource) {
        log.info("getConnection starting ...");
        long start = System.currentTimeMillis();
        Connection connection = null;
        try {
            connection = dataSource.getConnection();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        log.info("getConnection using {}", (System.currentTimeMillis() - start));
        try {
            return DatabaseTypeRegistry.getDatabaseTypeByURL(connection.getMetaData().getURL());
        } catch (final SQLException ex) {
            throw new IllegalArgumentException("An error occurred when open datasource connection!", ex);
        }
    }
```
the log show : getConnection using 253
so if I have 40 datasource connection
the time using is 10 sec
with more getConnection option
the createDatasource option can use 1minute

**Comment by tuichenchuxin** [comment]
@irwinai You can try the latest version, we have improved the performance.

**Comment by irwinai** [comment]
I have tried 5.1.0 new version , and the create ShardingSphereDataSource is slowly also

**Comment by tuichenchuxin** [comment]
> It looks like the SchemaRulesBuilder -> buildRules -> DatabaseTypeRecognizer.getDatabaseType is too slow

I see, seems, we check different database by loop.
Maybe load by mutli thread is better.

**Comment by irwinai** [comment]
@tuichenchuxin year,the time cost almost is the getConnection()

**Comment by tuichenchuxin** [comment]
@irwinai Can you try to submit a pr?

**Comment by terrymanu** [comment]
Duplicate with #18369
