### ISSUE TITLE
Could I connect MySQL other version(both 5.7.22 and 8.0.22) as DS to ShardingSphere-proxy?

### ISSUE THREAD

**Issue by SimYeJu** [apache/shardingsphere#16516]
## Enviroment
ShardingSphere
 - proxy 5.0.0
   - mysql-connector/J 5.1.47

DBMS
 - MySQL 5.7.22
 - MySQL 8.0.22

Application
- Spring Boot 2.5.5

Could I connect MySQL other version(both 5.7.22 and 8.0.22) as DS to ShardingSphere-proxy 5.0.0?

I run that enviroment but returned under error message.

> WARN [com.zaxxer.hikari.pool.PoolBase:checkDefaultIsolation:491] PORT:6481 [main] HikariPool-4 - Default transaction isolation level detection failed (Could not map transaction isolation '1' to a valid JDBC level.).
ERROR [com.zaxxer.hikari.pool.HikariPool:createPoolEntry:498] PORT:6481 [main] HikariPool-4 - Error thrown while acquiring connection from data source
java.sql.SQLException: Could not map transaction isolation '1' to a valid JDBC level.

So, I query 'SELECT @@SESSION.tx_isolation' at MySQL client with ShardingSphere-proxy 5.0.0, and I receive result 1.
<img width="324" alt="image" src="https://user-images.githubusercontent.com/55989240/160995334-e7d4a943-6efe-4aa1-b87a-e2468565933f.png">

I know tx_isolation is deprecated at MySQL 8 version.

though... How Can I use other MySQL version with ShardingSphere-proxy?

**Comment by tuichenchuxin** [comment]
I tried to use mysql 5.7 and mysql 8.0 in proxy. It's ok.

**Comment by SimYeJu** [comment]
Then, I change my question.

ShardingSphere Proxy 5.0.0 connect to DS1 (MySQL 5.7.17) and to DS2 (MySQL 8.0.25).

I wonder why result is '1' when query 'SELECT @@SESSION.tx_isolation' to ShardingSphere Proxy.
![image](https://user-images.githubusercontent.com/55989240/161877025-eb896a1f-df34-4f1c-9afb-38cdabc77fd1.png)


tx_isolation's valid value is 'READ-UNCOMMITTED', 'READ-COMMITTED', 'REPEATABLE-READ'. 'SERIALIZABLE'.
https://docs.oracle.com/cd/E17952_01/mysql-5.7-en/server-system-variables.html#sysvar_tx_isolation

**Comment by tuichenchuxin** [comment]
@SimYeJu Ok. I'll check later.

**Comment by TeslaCN** [comment]
You may upgrade to ShardingSphere-Proxy 5.1.2 and configure `proxy-mysql-default-version` in `server.yaml`.
