### ISSUE TITLE
postgresql's COPY FROM and INSERT INTO SELECT statements 

### ISSUE THREAD

**Issue by Eunjung87** [apache/shardingsphere#16525]
**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
when I insert data as follows, I get the following error. 

sharding_db=> insert into person select * from person2;
**ERROR:  java.lang.NullPointerException**
sharding_db=> \copy person from '/home/agens/person_0_0.csv' delimiter '|' csv header ;
**ERROR:  COPY from stdin failed: COPY commands are only supported using the CopyManager API.**
CONTEXT:  COPY person, line 1

Doesn't it support postgresql's COPY FROM and INSERT INTO SELECT statements or pg_dump now?
Then, when using shardingsphere for the first time in postgresql, if data needs to be migrated, how should it be migrated?

If so, are there any plans to support that feature?

### Describe the feature you would like.
I want to use the COPY and INSERT INTO SELECT statements of postgresql Database in sharding-proxy and sharding-jdbc.

**Comment by tuichenchuxin** [comment]
Seems like a parsing error. I'll check it.

**Comment by strongduanmu** [comment]
@Eunjung87 Can you provide your sharding configuration?

**Comment by strongduanmu** [comment]
Hi @Eunjung87, I have optimized the copy statement and insert select statement in PostgreSQL. However, considering the difference between distributed SQL and stand-alone SQL, currently copy statements and insert select statements cannot support sharding tables, but only support single tables.
