### ISSUE TITLE
How to support efficient BETWEEN and with Snowflake algorithm ID

### ISSUE THREAD

**Issue by mousycoder** [apache/shardingsphere#16537]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/6722977/161204127-0368e96c-4556-4415-9fed-9f94e45770f7.png">
It's going to loop a lot, and it's not going to work

**Comment by strongduanmu** [comment]
@mousycoder Thank you for your feedback, this is indeed a problem. Maybe we can reduce the number of loops by checking if the number of availableTargetNames and result are equal.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
