### ISSUE TITLE
[Question] How to write sharding rule with prefix and sharding-column

### ISSUE THREAD

**Issue by Jun10ng** [apache/shardingsphere#16534]
## Question

Hi team,
I hava a question about how to write sharding rule with **prefix** and **sharding-column**

My current prop file map sharding job_lob_tab from `job_lob_0` to `job_lob_100`, and I want to modify it, to 
**sharding job_lob_tab from `job_lob_00000000` to `job_lob_00000100` (for sharding table,padding 8 digits with 0)**

```
spring.shardingsphere.rules.sharding.tables.gs_job_log.actual-data-nodes=job_log_$->{0..100}

spring.shardingsphere.rules.sharding.sharding-algorithms.job-log-table-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.job-log-table-inline.props.algorithm-expression=gs_job_log_$->{job_group % 100}

```
How should I modify it？

I read the [docs](https://shardingsphere.apache.org/document/current/en/features/sharding/concept/inline-expression/), I only found an example with a prefix.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/46768176/161199167-400791fe-97c0-4e3c-94be-c8672ab9564f.png">

But I dont know how to embed my sharding-column `job_group` into it
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
Hi @Jun10ng 
1. You could specify the sharding column by :
```
spring.shardingsphere.rules.sharding.tables.gs_job_log.table-strategy.standard.sharding-column=job_group
```
2. For your  `actual-data-nodes`,  do you want `db.job_log_0000000$->{0..9}, db.job_log_000000$->{10..99}, db.job_log_00000100`?

**Comment by RaigorJiang** [comment]
Refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/sharding/

**Comment by Jun10ng** [comment]
> Hi @Jun10ng
> 
> 1. You could specify the sharding column by :
> 
> ```
> spring.shardingsphere.rules.sharding.tables.gs_job_log.table-strategy.standard.sharding-column=job_group
> ```
> 
> 2. For your  `actual-data-nodes`,  do you want `db.job_log_0000000$->{0..9}, db.job_log_000000$->{10..99}, db.job_log_00000100`?

Thanks for your reply, but my actually route field is `job_group%100`. Could I write as the follow？
> spring.shardingsphere.rules.sharding.tables.gs_job_log.table-strategy.standard.sharding-column=job_group%100


感谢你的回复。 实际上我的字段是 job_group的后三位，也就是 `job_group%100`。
所以我可以这样写吗？
> spring.shardingsphere.rules.sharding.tables.gs_job_log.table-strategy.standard.sharding-column=job_group%100

**Comment by RaigorJiang** [comment]
I think it should be `job_group%1000`,   so you can get the last three digits.

**Comment by Jun10ng** [comment]
okay 
so `sharding-column ` prop can be assigned an expression？

**Comment by RaigorJiang** [comment]
Sorry, I don't understand what you mean, please give an example.
