### ISSUE TITLE
SchemaMetaDataNode.getMetaDataDataSourcePath(final String schemaName, final String version) add unit test.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16542]

**Comment by ismailalammar** [comment]
Hi , i would like to work on this , please assign it to me

**Comment by strongduanmu** [comment]
@ismailalammar Of course, I just assign this issue to you.

**Comment by ismailalammar** [comment]
HI @strongduanmu , i've submitted a PR regarding this issue , thanks!
