### ISSUE TITLE
the comment statement can't work in ShardingSphere-Proxy

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#16548]
### Which version of ShardingSphere did you use?

master e6c69508baa0b8ae6c4a73644744bbf46a8a04b7

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

after create table by  ShardingSphere-Proxy, then i want to add the comment on t_order; it's execute ok on DataGrip or Navicat

```sql
##  i replace the actual table name  to logic table name
COMMENT ON TABLE "t_order_0" IS 'Test table comment';
```
<img width="767" alt="image" src="https://user-images.githubusercontent.com/101622833/161228933-35043c1f-35c0-4a58-92f2-f46f65b80f04.png">

same problem with the sql
```sql
## same problem 
COMMENT ON COLUMN "t_order_0"."user_id" IS 'id of user';
```

### Actual behavior

execute this sql  in ShardingSphere-Proxy 

```
sharding_db=> COMMENT ON TABLE "t_order" IS 'Test table comment';
ERROR:  You have an error in your SQL syntax
sharding_db=>
```

### Reason analyze (If you can)

i find the problem is at `PostgreSQLParser.parse()` 

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/101622833/161229940-968dfd4a-3d1a-43df-a43a-d9cc74ed54e1.png">

final the exception is happened  at  `PostgreSQLStatementParser` 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Prepare operation:
1. config yaml （use postgreSQL)
```xml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/ds_0
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
  ds_1:
    url: jdbc:postgresql://127.0.0.1:5432/ds_1
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```

2. create table by ShardingSphere-Proxy

```sql
CREATE TABLE t_order (
  order_id bigint NOT NULL,
  user_id int NOT NULL,
  status varchar(50) DEFAULT NULL,
  PRIMARY KEY (order_id)
) ;
```

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
Sure, I'll check it.

**Comment by azexcy** [comment]
i test at master 534c6791fa570449271313573c0346aca096ae3d
but the response is error.

```
sharding_db=> COMMENT ON COLUMN t_order.order_id IS '主键注释';
ERROR:  relation "t_order" does not exist

sharding_db=> COMMENT ON TABLE "t_order" IS 'Test table comment';
ERROR:  relation "t_order" does not exist
```
