### ISSUE TITLE
[OpenForce 2022] Move the class into the correct package

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16553]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441

### Background
`AlterDefaultSingleTableRuleStatement` is an object of the DistSQL syntax `ALTER DEFAULT SINGLE TABLE RULE`. It is a subclass of the `AlterRuleStatement` class in the `org.apache.shardingsphere.distsql.parser.statement.rdl.create `package.

### Aim
`AlterDefaultSingleTableRuleStatement` and `AlterRuleStatement` should be under the same package

Moved `AlterDefaultSingleTableRuleStatement` into `org.apache.shardingsphere.distsql.parser.statement.rdl.alter`

**Comment by Swastyy** [comment]
Hi @lanchengx , I have created a PR for this one just now.

**Comment by lanchengx** [comment]
@Swastyy Thanks
