### ISSUE TITLE
Refactoring Global Lock.

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#16564]
### Is your feature request related to a problem?

Refactoring `GlobalLock`.

### Describe the feature you would like.

`ShardingSphereDistributeGlobalLock` to merge with the original  `ShardingSphereDistributeLock`

**Comment by TeslaCN** [comment]
Hi @soulasuna 
Are we done?

**Comment by soulasuna** [comment]
Hi @TeslaCN Must be done today

**Comment by soulasuna** [comment]
@TeslaCN Is done.
