### ISSUE TITLE
load data infile is not run

### ISSUE THREAD

**Issue by liuxingping138** [apache/shardingsphere#16567]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by liuxingping138** [comment]
load data infile is not run,have a error :ERROR 1997 (C1997): Runtime exception: [Can not find visitor rule: `LoadStatementContext`]

**Comment by strongduanmu** [comment]
@liuxingping138 Thank you for your feedback, can you provide your configuration and sql?

**Comment by liuxingping138** [comment]
sql:  load data infile '/var/lib/mysql-files/test_lxp.txt' into table lxp_test(prov_name,city_name,county_name)

my configuration :ds_0: initializationFailTimeout: 1 validationTimeout: 5000 connectionTimeoutMilliseconds: 30000 readOnly: false idleTimeoutMilliseconds: 60000 isolateInternalQueries: false url: jdbc:mysql://192.168.1.6:3306/test_proxy_0?serverTimezone=UTC&useSSL=false leakDetectionThreshold: 0 password: ******&f minPoolSize: 1 allowPoolSuspension: false dataSourceProperties: cacheServerConfiguration: 'true' elideSetAutoCommits: 'true' useServerPrepStmts: 'true' cachePrepStmts: 'true' rewriteBatchedStatements: 'true' cacheResultSetMetadata: 'false' useLocalSessionState: 'true' maintainTimeStats: 'false' prepStmtCacheSize: '200000' tinyInt1isBit: 'false' prepStmtCacheSqlLimit: '2048' netTimeoutForStreamingResults: '0' maxLifetimeMilliseconds: 1800000 dataSourceClassName: com.zaxxer.hikari.HikariDataSource autoCommit: true maxPoolSize: 50 username: root ds_1: initializationFailTimeout: 1 validationTimeout: 5000 connectionTimeoutMilliseconds: 30000 readOnly: false idleTimeoutMilliseconds: 60000 isolateInternalQueries: false url: jdbc:mysql://192.168.1.7:3306/test_proxy_1?serverTimezone=UTC&useSSL=false leakDetectionThreshold: 0 password: ****&4y minPoolSize: 1 allowPoolSuspension: false dataSourceProperties: cacheServerConfiguration: 'true' elideSetAutoCommits: 'true' useServerPrepStmts: 'true' cachePrepStmts: 'true' rewriteBatchedStatements: 'true' cacheResultSetMetadata: 'false' useLocalSessionState: 'true' maintainTimeStats: 'false' prepStmtCacheSize: '200000' tinyInt1isBit: 'false' prepStmtCacheSqlLimit: '2048' netTimeoutForStreamingResults: '0' maxLifetimeMilliseconds: 1800000 dataSourceClassName: com.zaxxer.hikari.HikariDataSource autoCommit: true maxPoolSize: 50 username: root ds_2: initializationFailTimeout: 1 validationTimeout: 5000 connectionTimeoutMilliseconds: 30000 readOnly: false idleTimeoutMilliseconds: 60000 isolateInternalQueries: false url: jdbc:mysql://192.168.1.8:3306/test_proxy_2?serverTimezone=UTC&useSSL=false leakDetectionThreshold: 0 password: ****& minPoolSize: 1 allowPoolSuspensi

**Comment by liuxingping138** [comment]
my version 5.1.0

**Comment by terrymanu** [comment]
The load data infile feature is not implemented yet, we need to discuss how to implement it first.

**Comment by liuxingping138** [comment]
Ok，Thank You！
