### ISSUE TITLE
How to use schema in sharding resolve?

### ISSUE THREAD

**Issue by nexen505** [apache/shardingsphere#16586]
### Discussed in https://github.com/apache/shardingsphere/discussions/16585

<div type='discussions-op-text'>

<sup>Originally posted by **nexen505** April  4, 2022</sup>
Hi! Question for version 5.1.1.

Let's assume that we have the following sharding scheme. 
We have one database instance with each shard mapped to the different database schema. Shards should be delegated to the single DataSource for this database because we should have one connection pool for all the schemas. So we need generated SQL-queries of every shard to be schema-specific.

Is this configuration possible? How to configure datasources and their aliases as schema-specific for the correctly generated SQL-queries?</div>

**Comment by strongduanmu** [comment]
Hi @nexen505, let's talking about this topic in discussion. I will close this issue here.
