### ISSUE TITLE
How to use Hint without shard key, and use shard algorithm with shard key?

### ISSUE THREAD

**Issue by udrnrso** [apache/shardingsphere#16613]
Suppose the shard field is user_id
Without the user_id condition, such as the following sql, I hope to force the shard number to be specified
// Force the use of shard 00
select * from tableA limit 500
With the user_id condition, use the sharding algorithm
select * from tableA where user_id = 'testuser'

After reading the document, it seems that we can only choose between hint/standard. Does it support mixed use?

**Comment by strongduanmu** [comment]
@udrnrso Mixed use is not supported now. The hint sharding algorithm is to support scenarios where the sharding column does not exist in the table. If your table has this field, it is best to use the standard algorithm.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
