### ISSUE TITLE
Add more unit test for ShardingCopyStatementValidator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16617]
Hi community,

We need to add more unit test for ShardingCopyStatementValidator.

- [ ] ShardingCopyStatementValidator#preValidate

**Comment by Liangda-w** [comment]
@Devamparikh welcome:) assigned to you

**Comment by Devamparikh** [comment]
Hey @Liangda-w is there any channel where we can discuss this issue with other team members?

**Comment by Liangda-w** [comment]
> Hey @Liangda-w this ShardingCopyStatementValidatorTest file would be easy to create if I can have some example or anything.

The examples [here](https://github.com/apache/shardingsphere/tree/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/route/engine/validator/dml) might be helpful for you:) and here is the [slack channel](https://join.slack.com/t/apacheshardingsphere/shared_invite/zt-sbdde7ie-SjDqo9~I4rYcR18bq0SYTg) if you want to discuss issues

**Comment by terrymanu** [comment]
@Devamparikh Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by zrsaber** [comment]
please assign it to me, i will have a try

**Comment by strongduanmu** [comment]
@zrsaber Welcome, I'm glad to see you again.
