### ISSUE TITLE
[HY000][1815] Internal error: Error while preparing statement [/* ApplicationName=DataGrip 2021.3.4 */ for Date_format

### ISSUE THREAD

**Issue by wayinit** [apache/shardingsphere#16622]
When I used this sql
SELECT
        tmp.id,
        tmk.tb_mem_no mem_no,
        tmk.tb_kyc_flag kyc_flag
        FROM
        tb_mem_personal tmp,
        tb_mem_kyc tmk,
        tb_country tc
        WHERE
        tmk.id = tmp.tb_kyc_id
        AND tc.tb_country_code = tmk.tb_credentials_city
        AND DATE_FORMAT(tmp.kyc_submit_time,'%Y%m%d') = date_format(now(),'%Y%m%d')
It show me error  [HY000][1815] Internal error: Error while preparing statement [/* ApplicationName=DataGrip 2021.3.4 */ .
<img width="1074" alt="origin_img_v2_949c758c-fded-45ff-b6dc-97f84f76ef6g" src="https://user-images.githubusercontent.com/16432884/162106912-72bf5e8f-35f4-4587-90fa-78abdc985824.png">

**Comment by strongduanmu** [comment]
@wayinit Can you provide more information according to issue template?

**Comment by wayinit** [comment]
### Which version of ShardingSphere did you use?
ShardingSphere proxy 5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
获的正确的结果
### Actual behavior
报错了，如上面提到的
### Reason analyze (If you can)
我在实验中发现，单表使用函数不会报错，可是表关联查询的时候无论是where还是查询字段中加入了函数都会报错。
我的环境是分了两个库
错误信息来看像是关联查询就无法处理函数了。
函数不能使用包括 Date_format concat substr now()
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT
tmp.id,
tmk.tb_mem_no mem_no,
tmk.tb_kyc_flag kyc_flag
FROM
tb_mem_personal tmp,
tb_mem_kyc tmk,
tb_country tc
WHERE
tmk.id = tmp.tb_kyc_id
AND tc.tb_country_code = tmk.tb_credentials_city
AND DATE_FORMAT(tmp.kyc_submit_time,'%Y%m%d') = date_format(now(),'%Y%m%d')

**Comment by wayinit** [comment]
@strongduanmu 有消息了吗

**Comment by terrymanu** [comment]
For english only
