### ISSUE TITLE
Case display results are different

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#16624]
## Case display results are different
- Shardingsphere proxy version is 5.1.0
- SQL：
``` sql
mysql> SHOW FULL TABLES FROM `test` LIKE 'act_id_property';
+-----------------+------------+
| Tables_in_test  | Table_type |
+-----------------+------------+
| act_id_property | BASE TABLE |
+-----------------+------------+
1 row in set (0.00 sec)

mysql> SHOW FULL TABLES FROM `test` LIKE 'ACT_ID_PROPERTY';
Empty set (0.00 sec)

mysql> select * from ACT_ID_PROPERTY;
+----------------+---------+------+
| NAME_          | VALUE_  | REV_ |
+----------------+---------+------+
| schema.version | 6.5.0.6 |    1 |
+----------------+---------+------+
1 row in set (0.01 sec)
```

MySQL is set to be case insensitive. The execution results of the two SQL statements are different. You can query the results in lowercase, but there is no result in uppercase.

Incompatible with such queries?

**Comment by strongduanmu** [comment]
@novice-gamer Thank you for your feedback. Are you interested in submitting a PR to solve this issue?

**Comment by novice-gamer** [comment]
Sorry, I'm not a developer. Are you sure this is a bug in shardingsphere proxy?
