### ISSUE TITLE
[OpenForce 2022] Add Oracle SQL `DROP DIRECTORY`

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#16621]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support parsing Oracle SQL `DROP DIRECTORY`. You can learn more details about this SQL [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DROP-DIRECTORY.html#GUID-3719950A-7B6A-4284-8467-B3455ECF8516).
- Remember to add new corresponding SQL cases in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed results in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case).
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) and [UnsupportedSQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java) to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

## Targets files
You can take a look at this PRs as a reference
*  #14048 
* #16024

**Comment by Devamparikh** [comment]
Hey there! 
I was in search for issues like this to work on.
Can I take this issue?

**Comment by everly-gif** [comment]
Hi, I would like to work on this issue !

**Comment by Liangda-w** [comment]
Hey @Devamparikh, thanks for your interest! But since you have #16620 already, I would assign this to @everly-gif, who asked for such issues before :)
