### ISSUE TITLE
[OpenForce 2022] Add Oracle SQL `CREATE DIRECTORY`

### ISSUE THREAD

**Issue by Liangda-w** [apache/shardingsphere#16620]
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support parsing Oracle SQL `CREATE DIRECTORY`. You can learn more details about this SQL [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-DIRECTORY.html#GUID-8E9C569A-1B06-42C4-9586-0EF83437001A).
- Remember to add new corresponding SQL cases in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed results in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case).
- Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) and [UnsupportedSQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/UnsupportedSQLParserParameterizedTest.java) to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

## Targets files
You can take a look at this PRs as a reference
*  #14048 
* #16024

**Comment by Devamparikh** [comment]
Hey, Can I work on this please?

**Comment by yx9o** [comment]
@Devamparikh Welcome, assigned to you.

**Comment by everly-gif** [comment]
Hi @Devamparikh what's the update with this issue? Are you working on it still? I will like to take over if you aren't working on it.

**Comment by everly-gif** [comment]
Will be making an PR soon as there as has been no progress or response.
