### ISSUE TITLE
the data is not written to the database in time

### ISSUE THREAD

**Issue by newchendb** [apache/shardingsphere#16631]
shardingsphere-proxy version is 5.1.0。

Under what circumstances will the program submit data and return success, but the data is not written to the database in time, sometimes delaying for several seconds.

**Comment by newchendb** [comment]
There is no such problem with direct database connection. There will be such a problem with shardingsphere-proxy

**Comment by jingshanglu** [comment]
Can you show proxy config? can you show a demo?

**Comment by jingshanglu** [comment]
Can you show the SQL demo?

**Comment by newchendb** [comment]
![image](https://user-images.githubusercontent.com/29219642/162349200-3a9d0cf6-b250-43a3-9453-a1c27a7802b0.png)

@jingshanglu  Very simple SQL. The data is inserted in the above SQL, but sometimes the corresponding data is not found in the following query

**Comment by jingshanglu** [comment]
> ![image](https://user-images.githubusercontent.com/29219642/162349200-3a9d0cf6-b250-43a3-9453-a1c27a7802b0.png)
> 
> @jingshanglu Very simple SQL. The data is inserted in the above SQL, but sometimes the corresponding data is not found in the following query

This scenario should not lead to write delay. The possible scenario is to write to the master DB and read from the slave DB.

**Comment by jingshanglu** [comment]
The scene in the screenshot is read and written on the same DB.

**Comment by newchendb** [comment]
@jingshanglu Yes, before that, I thought it was caused by MySQL master-slave synchronization delay, so I changed it to this, but the problem still exists.

**Comment by jingshanglu** [comment]
I see your just insert to one table and select from two table,  does the other table have master-slave synchronization delay?

**Comment by newchendb** [comment]
@jingshanglu No, the associated table is a sub table. This operation does not involve sub tables.

**Comment by newchendb** [comment]
This is accidental

**Comment by jingshanglu** [comment]
OK, If it appears again, you can simplify the demo and post it.

**Comment by newchendb** [comment]
![image](https://user-images.githubusercontent.com/29219642/162378253-5e0ef134-a2a2-4927-bb74-a32cfd647ebd.png)
The above is my test code. Query the list after adding

![image](https://user-images.githubusercontent.com/29219642/162378513-a8589bc7-3b2e-4c8f-a16f-fe6bd20144f6.png)
The above is the log of my code. There is no newly added data in the list query

![image](https://user-images.githubusercontent.com/29219642/162378773-a4f42f9d-7c13-430f-9b13-30b177e12e27.png)
The above is the SQL log。

 but it is not always the case.
@jingshanglu

**Comment by jingshanglu** [comment]
Can you try this on mysql client?

**Comment by newchendb** [comment]
I have abandoned sharding proxy and used shardingjdbc instead
