### ISSUE TITLE
Potential performance issue in cluster mode caused by DistributeLockContext

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#16633]
### Which version of ShardingSphere did you use?

master after 10fdd38cbfd1b98be5009dfad89933dd572bcd88

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy in cluster mode

### Monitor Blocked

Some threads were blocked about 800 ms.

![image](https://user-images.githubusercontent.com/20503072/162146873-a8884909-7716-49fa-92a9-58d641ef514f.png)

**Comment by soulasuna** [comment]
I will follow up.

**Comment by TeslaCN** [comment]
Close this in #16636 and #16658.
