### ISSUE TITLE
如果只有部分数据库分库分表，shardingSphere5.0版本如何配置默认数据源？

### ISSUE THREAD

**Issue by xxmlovezw** [apache/shardingsphere#16638]
根据[Apache ShardingSphere 5.0.0-beta 官方中文文档](https://www.bookstack.cn/books/shardingsphere-5.0.0-beta)官方文档
在application.yaml中配置spring.shardingsphere.rules.sharding.default-data-source-name=stash1
结果并没有实现功能

**Comment by taojintianxia** [comment]
please use English to describe your question.
