### ISSUE TITLE
If only some databases are divided into databases and tables, how does shardingSphere 5.0 configure the default data source? 

### ISSUE THREAD

**Issue by xxmlovezw** [apache/shardingsphere#16649]
According to the Apache ShardingSphere 5.0.0-beta official Chinese documentation official documentation
Configure spring.shardingsphere.rules.sharding.default-data-source-name=stash1 in application.yaml
As a result, it does not work

**Comment by strongduanmu** [comment]
@xxmlovezw From 5.x version, users do not need to configure the default dataSource, ShardingSphere will automatically load and manage single tables.

**Comment by xxmlovezw** [comment]
@strongduanmu If I want to put a table that is not sharded into a specified database, how do I configure it? Now I find that tables that do not shard the tables are randomly assigned to the two databases I configured.

**Comment by strongduanmu** [comment]
> @strongduanmu If I want to put a table that is not sharded into a specified database, how do I configure it? Now I find that tables that do not shard the tables are randomly assigned to the two databases I configured.

@xxmlovezw You can use distsql to set default resource——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/.

**Comment by xxmlovezw** [comment]
@strongduanmu If I only use shardingSphere-jdbc ,Is there a way to implement a table configuration that does not shard into a table to the specified database?
