### ISSUE TITLE
DistributeLockContext.renew(final LockReleasedEvent event) need add unit test

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16646]

**Comment by Devamparikh** [comment]
Assign this to me I will work on this.

**Comment by zjcnb** [comment]
> Assign this to me I will work on this.

Done.

**Comment by zjcnb** [comment]
@Devamparikh Hi, how is this mission?

**Comment by Devamparikh** [comment]
Sorry I didn't get time and then forgot about this.
I will work on it once I get time.
