### ISSUE TITLE
SQL does not print parameters after the Read-Write Split are configured

### ISSUE THREAD

**Issue by lixaviers** [apache/shardingsphere#16640]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

SQL print parameters before the Read-Write Split are not configured,SQL does not print parameters after the Read-Write Split are configured.

before
 ShardingSphere-SQL - Actual SQL: master ::: SELECT  xxxxxxxxxxxx    oc_order 
 WHERE  is_deleted=0
AND (order_status = ? AND pay_close_time <= ?) ::: [1, 2022-04-07 18:35:30]

-----------------------------------------------------------------------------------------------------------------------------

after
ShardingSphere-SQL - Actual SQL: slave0 ::: SELECT   xxxxxxxxxxxx   FROM oc_order 
 WHERE  is_deleted=0

AND (order_status = ? AND pay_close_time <= ?)

`
spring:
  shardingsphere:
    props:
      sql:
        show: true`

**Comment by zjcnb** [comment]
@lixaviers Hello, 4.1.1 version are too old. Can you try it with 5.1.0 version?

**Comment by lixaviers** [comment]
Hello, I tried to upgrade to version 5 and tested it. Found that the main library, every time I try to debug and see `ReadwriteSplittingDataSourceRouter`  class, `TransactionHolder.IsTransaction().` All the Transactional operations I've read before used @Transactional(readOnly = true). Now that means getting rid of all @Transactional(readOnly = true) is too expensive
