### ISSUE TITLE
union all not correct in multi table associated queries, but correct in onetable queries.

### ISSUE THREAD

**Issue by wayinit** [apache/shardingsphere#16652]
### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-proxy
### Expected behavior
get the result
### Actual behavior
no result, empty
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
like the SQL, when I use multi table associated queries, the result is empty, but the tables has data.
SELECT tu.use_id,
       tu.tb_mobile,
       ta.class_no
FROM tb_user tu,
     tb_apply ta
where tu.use_id = ta.use_id
  and tu.tb_cert_s = 'Y'
  and ta.tb_status = 2
union all
SELECT tu.use_id,
       tu.tb_mobile,
       ta.class_no
FROM tb_a_user tu,
     tb_apply ta
where tu.mem_no = ta.use_id
  and tu.cert_s = 'Y'
  and ta.tb_status = 2
but only union all the tb_user and tb_a_user, I can get the result. 
for this sutuation, there is just tb_a_user has data.

**Comment by strongduanmu** [comment]
Hi @wayinit, Did you turn on the `sql-federation` config? `union all` statement is currently only supported through the experimental sql-federation feature.

**Comment by wayinit** [comment]
<img width="614" alt="origin_img_v2_f325fe05-13e6-4d0c-a31a-3d9a14d9e3bg" src="https://user-images.githubusercontent.com/16432884/162405792-6647aeec-477f-49be-9f99-8e2a4bfa3200.png">

**Comment by wayinit** [comment]
@strongduanmu 
<img width="614" alt="origin_img_v2_f325fe05-13e6-4d0c-a31a-3d9a14d9e3bg" src="https://user-images.githubusercontent.com/16432884/162405839-a59c9efc-f662-4415-83e0-ffd0cc962816.png">
