### ISSUE TITLE
Support batch update

### ISSUE THREAD

**Issue by ycy1991** [apache/shardingsphere#16660]
## Question
For batch update of mybatis, SQL only parses the table before the first semicolon, and subsequent statements are not parsed into actual SQL,eg:
![image](https://user-images.githubusercontent.com/16506338/162395059-25e437e0-ac08-44b2-89e8-cd900e56d15e.png)

![image](https://user-images.githubusercontent.com/16506338/162395148-45ad7405-fda8-4563-9aed-b6ef266c2de5.png)
Will subsequent versions support

**Comment by strongduanmu** [comment]
@ycy1991 Thank you for your feedback, multi statements parse is not supported yet. May I ask what feature are you using? Using multiple sql statements in a sharding scenario will cause some execution problems.

**Comment by ycy1991** [comment]
Updating a table in batch，eg
![image](https://user-images.githubusercontent.com/16506338/162490291-fd203930-ddd9-46f8-b0f6-395cab4955fc.png)

**Comment by ycy1991** [comment]
If the SQL is written directly, can some SQL not be parsed?
like this
update xxl_job_log_01 set  trigger_code=xx where  `id`= xx and  `job_id`=xx and  `trigger_time`= xx
update xxl_job_log_01 set  trigger_code=xx where  `id`= xx and  `job_id`=xx and  `trigger_time`= xx
Directly skip routing and parsing operations

**Comment by strongduanmu** [comment]
@ycy1991 Skipping parsing is not a good idea, currently all ShardingSphere features relies on SQL parsing. We will consider supporting parsing of multiple SQL statements in the future.

**Comment by strongduanmu** [comment]
If you really need the passthrough feature, you can refer to this doc——
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#%E4%BD%BF%E7%94%A8-hint-%E8%B7%AF%E7%94%B1%E8%87%B3%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93.

**Comment by ycy1991** [comment]
I use the following scheme to deal with it. I think it should be possible，Write mybatis SQL into the code and traverse it
![image](https://user-images.githubusercontent.com/16506338/162688010-b92cfd1f-77b7-4306-bffc-400d0f798287.png)

Put the code into a transaction
@Transactional(rollbackFor = Exception.class, timeout=1000)
  public void batchUpdate(List<XxlJobLog> batchUpdateLogs) {
        // 通过同一个事务，整体提交解决sharingjdbc无法解析批量batch sql
        for (XxlJobLog logVo : batchUpdateLogs) {
            logVo.setActualTableName(targetTable);
            xxlJobLogDao.batchUpdateHandleInfo(logVo);
        }
}
Do you think it's risky

**Comment by strongduanmu** [comment]
@ycy1991 Call the native JDBC interface directly by splicing SQL?

**Comment by ycy1991** [comment]
Yes, I don't need to calculate the routing table through shardingjdbc. I can calculate the actual routing table in advance
