### ISSUE TITLE
how to support enum class

### ISSUE THREAD

**Issue by sinolan** [apache/shardingsphere#16664]
java enum not support?
the sql field a.sex is enum type, mysql database's type is int(2) , but not support?

### Which version of ShardingSphere did you use?
shardingsphere5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC

### Expected behavior
SELECT a.id,a.create_time,a.login_name,a.name,a.sex,a.disabled FROM sys_user a
![16494116035302](https://user-images.githubusercontent.com/8133974/162413827-7685af2b-0bf4-4bf2-8277-dc89d380ca86.png)

![6494118109476](https://user-images.githubusercontent.com/8133974/162413801-90ed4a77-dabf-4522-bcdc-9d045ae3a802.png)

![6494118848157](https://user-images.githubusercontent.com/8133974/162413854-4857ce30-b66a-4a34-b225-2500d92fd19b.png)

**Comment by terrymanu** [comment]
Enum cannot support is not critical issue, I just as the issue as `good pro issue`, welcome interested contributor handle this one.

**Comment by susongyan** [comment]
i'd like to try it

**Comment by Bpazy** [comment]
Seems fixed in https://github.com/apache/shardingsphere/pull/15487.
