### ISSUE TITLE
Refactor `ALTER RESOURCE` syntax doc

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16679]
This issue is a subtask of refactoring DistSQL documentation. Please refer to https://github.com/apache/shardingsphere/issues/16666

The content of the `ALTER RESOURCE` syntax document is the same as the content of the `CREATE RESOURCE` syntax document. Just change the `CREATE` keyword to the `ALTER` keyword. 

Please refer to [add-resource.cn.md](https://github.com/apache/shardingsphere/pull/16659/files#diff-12f2c55d2cfc539bc821e65c34192e3695d22348d53df90fd8c1b8960c16a5c9)

For syntax definition files, please refer to `shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/imports/RDLStatement.g4:26`

**Comment by Swastyy** [comment]
Hi @lanchengx , can you give the link of `CREATE RESOURCE` syntax document, I am not able to find it.

**Comment by lanchengx** [comment]
> Hi @lanchengx , can you give the link of `CREATE RESOURCE` syntax document, I am not able to find it.

please refer https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/resource-definition/add-resource/
