### ISSUE TITLE
Add more unit test for IndexMetaDataUtil

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16670]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for IndexMetaDataUtil.

- [ ] IndexMetaDataUtil#getGeneratedLogicIndexName
- [ ] IndexMetaDataUtil#getTableNamesFromMetaData

**Comment by weihubeats** [comment]
Hey, Can I work on this please?

**Comment by strongduanmu** [comment]
@weihubeats Welcome.
