### ISSUE TITLE
Refactor `SHOW UNUSED RESOURCE` syntax doc

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#16681]
This issue is a subtask of refactoring DistSQL documentation. Please refer to https://github.com/apache/shardingsphere/issues/16666

The content of the `SHOW UNUSED RESOURCE` syntax document is roughly the same as the content of the `SHOW RESOURCE` document. Need to add `UNUSED` keyword.

The difference between the two can refer to the syntax definition file `shardingsphere-distsql/shardingsphere-distsql-parser/src/main/antlr4/imports/RQLStatement.g4:26`

`SHOW RESOURCE` document. Please refer to [show-resource.cn.md](https://github.com/apache/shardingsphere/pull/16663/files9)

**Comment by Swastyy** [comment]
Hi @lanchengx , please assign it to me.

**Comment by strongduanmu** [comment]
@Swastyy Assigned.
