### ISSUE TITLE
sharding doesn't work

### ISSUE THREAD

**Issue by mylixiangxiang** [apache/shardingsphere#16689]
1、A service
![Capto_Capture 2022-04-09_11-27-23_上午](https://user-images.githubusercontent.com/101060605/162554641-d4735280-abf9-4222-afb8-f76983734c45.png)
2、B dubbo service
![Capto_Capture 2022-04-09_11-35-59_上午](https://user-images.githubusercontent.com/101060605/162554856-bc44c5f7-ee45-45c6-a506-e484b1c42e80.png)
3、B dubbo service sharding log info
why SELECT * FROM capital_record WHERE (capital_id) in ( 2 ) not sharding route？
<img width="735" alt="WeChatb1913a36daf25226128ffda50b9e10c7" src="https://user-images.githubusercontent.com/101060605/162555198-c1849761-a8ad-4aa0-823b-539bdeea144c.png">

4、Sharding config
![Capto_Capture 2022-04-09_11-52-24_上午](https://user-images.githubusercontent.com/101060605/162555289-007d0c84-9905-44b9-8780-7aace6bffb35.png)

5、Mysql table info
![Capto_Capture 2022-04-09_11-54-39_上午](https://user-images.githubusercontent.com/101060605/162555341-8c6b028a-a44a-4790-bb94-9ca0d800c605.png)

My question is：why SELECT * FROM capital_record WHERE (capital_id) in ( 2 ) not sharding route？thanks

**Comment by RaigorJiang** [comment]
Hi @mylixiangxiang , 
1. what's your version of ShardingSphere? 
2. why the column after `where` in brackets?  can you try ` where capital_id in (value)`

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
