### ISSUE TITLE
Exception "Column index out of range" happend when querying ShardingSphere-proxy

### ISSUE THREAD

**Issue by NJCrazyRen** [apache/shardingsphere#16709]
ShardingSphere-proxy 5.1.0

I use ShardingSphere-proxy only for data-decrypt, so there is just only one data source which is a MySQL database. In the mysql database there is a table named "ssrc_rfx_quotation_line" with 276 columns. When I trying to execute query like 'select * from ssrc_rfx_quotation_line', the exception happend.

That table is a plain table without any encrypt column, so there are no encrypt rules related to it.

**Comment by NJCrazyRen** [comment]
The table in database is may less than 276 columns at beginning and ShardingSphere-proxy started.
Then someone added column(s) but ShardingSphere-proxy didn't restart.

**Comment by zjcnb** [comment]
@NJCrazyRen Hello, Maybe you can refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/ 

Execute `REFRESH TABLE METADATA` to refresh your metadata for `ShardingSphere-Proxy`

**Comment by NJCrazyRen** [comment]
> @NJCrazyRen Hello, Maybe you can refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/
> 
> Execute `REFRESH TABLE METADATA` to refresh your metadata for `ShardingSphere-Proxy`

It's very helpful. Thank you.
