### ISSUE TITLE
visual tool

### ISSUE THREAD

**Issue by chenrunkun** [apache/shardingsphere#16723]
## Question
1.shardingsphere-proxy Have a good visualization tool
2.shardingsphere-proxy 5.1 Which version of Navicat Premium is compatible

**Comment by lanchengx** [comment]
Hi @chenrunkun,  please refer [FAQ](https://shardingsphere.apache.org/document/5.1.0/cn/reference/faq/#proxy-%E5%9C%A8%E4%BD%BF%E7%94%A8-shardingsphere-proxy%E6%97%B6%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%90%88%E9%80%82%E7%9A%84%E5%B7%A5%E5%85%B7%E8%BF%9E%E6%8E%A5%E5%88%B0-shardingsphere-proxy)
