### ISSUE TITLE
how to config actual-data-nodes while my actual-data-nodes tables is dynamic。

### ISSUE THREAD

**Issue by wlklnn** [apache/shardingsphere#16725]
My shard-table will be created everyday。 It can't be configured by  
 <sharding:table-rule logic-table="t_mt" table-strategy-ref="self_hint_shard"  actual-data-nodes="——"/>
my maven dependency is         
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-namespace</artifactId>
            <version>5.1.0</version>
        </dependency>

**Comment by wlklnn** [comment]
if the actual-data-nodes was set as not exists table,there is a NPE.
![image](https://user-images.githubusercontent.com/29269426/162686444-edacb773-0ebd-4442-aa93-50ea0cbcfd5a.png)

**Comment by linghengqian** [comment]
- This answer in Apache ShardingSphere 5.1.0, the best answer is obviously to rely on Zookeeper/Etcd, in Apache ShardingSphere Proxy to dynamically change through DistSQL.

- Of course, you can do some things via CI/CD without using a Proxy, because ActualDatanode is actually a Groovy expression that can call static variables and methods of Java classes. If you know Gitlab Runner, I'm sure you know what I'm talking about, there are many applications for this.

- Second, ShardingSphere seems to have an agenda to create tables that don't exist at startup. It is pointless to configure a table that does not exist in the ShardingSphere, which will cause metadata checking to fail.

**Comment by wlklnn** [comment]
The actualDatanode  is dynamic ,for example, today's  ActualDatanode is [table_name_20220401..table_name_20220411], and  become [table_name_20220402..table_name_20220412] tomorrow,should i use a Scheduling to set ActualDatanode everyday ? but i can't find how to do this.

**Comment by wlklnn** [comment]
@linghengqian 
Thanks very much. 
I just use ShardingSphere's jdbc ,not proxy ,so there is no DistSQL, and the most hard for me is :how to refresh actualdatanodes without restart my application.  how to get the [actualdatanodes ] bean object and reset it's value is still  unknown to me.
thanks agin for your reply.

**Comment by linghengqian** [comment]
There is also some experiment in ShardingSphere 4.x to implement `SPI` in the registry to dynamically modify `actualDatanodes`, this process becomes more complex in `5.x` as the data distribution changes and the `ShardingRule` is rebuilt, I wonder if anyone's willing to do that. If you dispense with `ShardingSphere` data sources altogether, you can use its algorithm classes to encapsulate util yourself, bypassing the problems `actualDatanodes` needs to find.

**Comment by wlklnn** [comment]
I try to refresh it by ContextManager.alterRuleConfiguration(final String schemaName, final Collection<RuleConfiguration> ruleConfigs),It seems to be working properly. 
[InitActualDataNodesExample.txt](https://github.com/apache/shardingsphere/files/8480180/InitActualDataNodesExample.txt)

**Comment by linghengqian** [comment]
@wlklnn 
- Your sharing looks very cool! It's the first time I see such an application.

@strongduanmu 
- Is it possible to provide a `Util` class within `ShardingSphere JDBC` that wraps the method `updateShardRuleActualDataNodes()` for updating `actual-data-nodes` mentioned by @wlklnn  ? I believe many people are looking for how to update it dynamically, and it is convenient to simplify the process.
```java
package com.lingh.ao;

import org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource;
import org.apache.shardingsphere.infra.config.RuleConfiguration;
import org.apache.shardingsphere.sharding.algorithm.config.AlgorithmProvidedShardingRuleConfiguration;
import org.apache.shardingsphere.sharding.api.config.rule.ShardingTableRuleConfiguration;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.Collection;
import java.util.LinkedList;

@Component
public class InitActualDataNodesAO {
    @Resource
    private ShardingSphereDataSource shardingSphereDataSource;
    private final String logicTableNameForTOrder = "t_order";
    private final String schemaNameForTOrder = "sharding_db";

    public void testSharding() {
        // generate actualDataNodes
        String actualDataNodes = "ds-0.t_order_$->{[1..8]}";

        this.updateShardRuleActualDataNodes(shardingSphereDataSource, schemaNameForTOrder, logicTableNameForTOrder, actualDataNodes);
    }

    private void updateShardRuleActualDataNodes(ShardingSphereDataSource dataSource, String schemaName, String logicTableName, String newActualDataNodes) {
        // Context manager.
        org.apache.shardingsphere.mode.manager.ContextManager contextManager = dataSource.getContextManager();

        // Rule configuration.
        Collection<RuleConfiguration> newRuleConfigList = new LinkedList<>();
        Collection<RuleConfiguration> oldRuleConfigList = dataSource.getContextManager()
                .getMetaDataContexts()
                .getMetaData(schemaName)
                .getRuleMetaData()
                .getConfigurations();

        for (RuleConfiguration oldRuleConfig : oldRuleConfigList) {
            if (oldRuleConfig instanceof AlgorithmProvidedShardingRuleConfiguration) {

                // Algorithm provided sharding rule configuration
                AlgorithmProvidedShardingRuleConfiguration oldAlgorithmConfig = (AlgorithmProvidedShardingRuleConfiguration) oldRuleConfig;
                AlgorithmProvidedShardingRuleConfiguration newAlgorithmConfig = new AlgorithmProvidedShardingRuleConfiguration();

                // Sharding table rule configuration Collection
                Collection<ShardingTableRuleConfiguration> newTableRuleConfigList = new LinkedList<>();
                Collection<ShardingTableRuleConfiguration> oldTableRuleConfigList = oldAlgorithmConfig.getTables();

                oldTableRuleConfigList.forEach(oldTableRuleConfig -> {
                    if (logicTableName.equals(oldTableRuleConfig.getLogicTable())) {
                        ShardingTableRuleConfiguration newTableRuleConfig = new ShardingTableRuleConfiguration(oldTableRuleConfig.getLogicTable(), newActualDataNodes);
                        newTableRuleConfig.setTableShardingStrategy(oldTableRuleConfig.getTableShardingStrategy());
                        newTableRuleConfig.setDatabaseShardingStrategy(oldTableRuleConfig.getDatabaseShardingStrategy());
                        newTableRuleConfig.setKeyGenerateStrategy(oldTableRuleConfig.getKeyGenerateStrategy());

                        newTableRuleConfigList.add(newTableRuleConfig);
                    } else {
                        newTableRuleConfigList.add(oldTableRuleConfig);
                    }
                });

                newAlgorithmConfig.setTables(newTableRuleConfigList);
                newAlgorithmConfig.setAutoTables(oldAlgorithmConfig.getAutoTables());
                newAlgorithmConfig.setBindingTableGroups(oldAlgorithmConfig.getBindingTableGroups());
                newAlgorithmConfig.setBroadcastTables(oldAlgorithmConfig.getBroadcastTables());
                newAlgorithmConfig.setDefaultDatabaseShardingStrategy(oldAlgorithmConfig.getDefaultDatabaseShardingStrategy());
                newAlgorithmConfig.setDefaultTableShardingStrategy(oldAlgorithmConfig.getDefaultTableShardingStrategy());
                newAlgorithmConfig.setDefaultKeyGenerateStrategy(oldAlgorithmConfig.getDefaultKeyGenerateStrategy());
                newAlgorithmConfig.setDefaultShardingColumn(oldAlgorithmConfig.getDefaultShardingColumn());
                newAlgorithmConfig.setShardingAlgorithms(oldAlgorithmConfig.getShardingAlgorithms());
                newAlgorithmConfig.setKeyGenerators(oldAlgorithmConfig.getKeyGenerators());

                newRuleConfigList.add(newAlgorithmConfig);
            }
        }

        // update context
        contextManager.alterRuleConfiguration(schemaName, newRuleConfigList);
    }
}
```

**Comment by strongduanmu** [comment]
> Is it possible to provide a Util class within ShardingSphere JDBC that wraps the method updateShardRuleActualDataNodes() for updating actual-data-nodes mentioned by @wlklnn ? I believe many people are looking for how to update it dynamically, and it is convenient to simplify the process.

@linghengqian Thank you for your remind, I will take a look at this way.

**Comment by linghengqian** [comment]
@xieyongchao2 Replying to the closed issue is an inexplicable thing for the owner of this issue. I think it would be better if you open a new issue and provide a minimal replica demo, and then point out the association with this issue.

**Comment by caol64** [comment]
> @wlklnn
> 
> * Your sharing looks very cool! It's the first time I see such an application.
> 
> @strongduanmu
> 
> * Is it possible to provide a `Util` class within `ShardingSphere JDBC` that wraps the method `updateShardRuleActualDataNodes()` for updating `actual-data-nodes` mentioned by @wlklnn  ? I believe many people are looking for how to update it dynamically, and it is convenient to simplify the process.
> 
> ```java
> package com.lingh.ao;
> 
> import org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource;
> import org.apache.shardingsphere.infra.config.RuleConfiguration;
> import org.apache.shardingsphere.sharding.algorithm.config.AlgorithmProvidedShardingRuleConfiguration;
> import org.apache.shardingsphere.sharding.api.config.rule.ShardingTableRuleConfiguration;
> import org.springframework.scheduling.annotation.EnableScheduling;
> import org.springframework.scheduling.annotation.Scheduled;
> import org.springframework.stereotype.Component;
> 
> import javax.annotation.Resource;
> import java.util.Collection;
> import java.util.LinkedList;
> 
> @Component
> public class InitActualDataNodesAO {
>     @Resource
>     private ShardingSphereDataSource shardingSphereDataSource;
>     private final String logicTableNameForTOrder = "t_order";
>     private final String schemaNameForTOrder = "sharding_db";
> 
>     public void testSharding() {
>         // generate actualDataNodes
>         String actualDataNodes = "ds-0.t_order_$->{[1..8]}";
> 
>         this.updateShardRuleActualDataNodes(shardingSphereDataSource, schemaNameForTOrder, logicTableNameForTOrder, actualDataNodes);
>     }
> 
>     private void updateShardRuleActualDataNodes(ShardingSphereDataSource dataSource, String schemaName, String logicTableName, String newActualDataNodes) {
>         // Context manager.
>         org.apache.shardingsphere.mode.manager.ContextManager contextManager = dataSource.getContextManager();
> 
>         // Rule configuration.
>         Collection<RuleConfiguration> newRuleConfigList = new LinkedList<>();
>         Collection<RuleConfiguration> oldRuleConfigList = dataSource.getContextManager()
>                 .getMetaDataContexts()
>                 .getMetaData(schemaName)
>                 .getRuleMetaData()
>                 .getConfigurations();
> 
>         for (RuleConfiguration oldRuleConfig : oldRuleConfigList) {
>             if (oldRuleConfig instanceof AlgorithmProvidedShardingRuleConfiguration) {
> 
>                 // Algorithm provided sharding rule configuration
>                 AlgorithmProvidedShardingRuleConfiguration oldAlgorithmConfig = (AlgorithmProvidedShardingRuleConfiguration) oldRuleConfig;
>                 AlgorithmProvidedShardingRuleConfiguration newAlgorithmConfig = new AlgorithmProvidedShardingRuleConfiguration();
> 
>                 // Sharding table rule configuration Collection
>                 Collection<ShardingTableRuleConfiguration> newTableRuleConfigList = new LinkedList<>();
>                 Collection<ShardingTableRuleConfiguration> oldTableRuleConfigList = oldAlgorithmConfig.getTables();
> 
>                 oldTableRuleConfigList.forEach(oldTableRuleConfig -> {
>                     if (logicTableName.equals(oldTableRuleConfig.getLogicTable())) {
>                         ShardingTableRuleConfiguration newTableRuleConfig = new ShardingTableRuleConfiguration(oldTableRuleConfig.getLogicTable(), newActualDataNodes);
>                         newTableRuleConfig.setTableShardingStrategy(oldTableRuleConfig.getTableShardingStrategy());
>                         newTableRuleConfig.setDatabaseShardingStrategy(oldTableRuleConfig.getDatabaseShardingStrategy());
>                         newTableRuleConfig.setKeyGenerateStrategy(oldTableRuleConfig.getKeyGenerateStrategy());
> 
>                         newTableRuleConfigList.add(newTableRuleConfig);
>                     } else {
>                         newTableRuleConfigList.add(oldTableRuleConfig);
>                     }
>                 });
> 
>                 newAlgorithmConfig.setTables(newTableRuleConfigList);
>                 newAlgorithmConfig.setAutoTables(oldAlgorithmConfig.getAutoTables());
>                 newAlgorithmConfig.setBindingTableGroups(oldAlgorithmConfig.getBindingTableGroups());
>                 newAlgorithmConfig.setBroadcastTables(oldAlgorithmConfig.getBroadcastTables());
>                 newAlgorithmConfig.setDefaultDatabaseShardingStrategy(oldAlgorithmConfig.getDefaultDatabaseShardingStrategy());
>                 newAlgorithmConfig.setDefaultTableShardingStrategy(oldAlgorithmConfig.getDefaultTableShardingStrategy());
>                 newAlgorithmConfig.setDefaultKeyGenerateStrategy(oldAlgorithmConfig.getDefaultKeyGenerateStrategy());
>                 newAlgorithmConfig.setDefaultShardingColumn(oldAlgorithmConfig.getDefaultShardingColumn());
>                 newAlgorithmConfig.setShardingAlgorithms(oldAlgorithmConfig.getShardingAlgorithms());
>                 newAlgorithmConfig.setKeyGenerators(oldAlgorithmConfig.getKeyGenerators());
> 
>                 newRuleConfigList.add(newAlgorithmConfig);
>             }
>         }
> 
>         // update context
>         contextManager.alterRuleConfiguration(schemaName, newRuleConfigList);
>     }
> }
> ```

@linghengqian In 5.1.2 version, ShardingSphereDataSource doesn't have getContextManager method. Is this solution needs to update?

**Comment by linghengqian** [comment]
@caol64 

- Hi, if you feel the need, you should open a new issue instead of staying in this one.  

- According to https://github.com/apache/shardingsphere/issues/18494, the metadata module is undergoing a massive adjustment, which means that every version uses this method differently.  I don't really recommend doing this, DistSQL is currently my solution.

**Comment by caol64** [comment]
@linghengqian Understood, thanks.

**Comment by SDSmalin** [comment]
I found a simpler code

``` yaml
actual-data-nodes: ds0.$->{com.lingh.LocalShardingDatabasesAndTablesUtil.getActualDataNodes()}
```

``` JAVA
public class LocalShardingDatabasesAndTablesUtil { 
     public static List<String> getActualDataNodes() { 
         LocalDate startTime = LocalDate.now().minusDays(10); 
         LocalDate endTime = LocalDate.now(); 
         return LongStream.range(0, ChronoUnit.DAYS.between(startTime, endTime)) 
                 .mapToObj(startTime::plusDays) 
                 .map(localDate -> "table_name_" + localDate.format(DateTimeFormatter.ofPattern("yyyyMMdd"))) 
                 .collect(Collectors.toList()); 
     }
}
```
``` JAVA
public class InitActualDataNodesAO {
    @Resource
    private ShardingSphereDataSource shardingSphereDataSource;
    private final String schemaNameForTOrder = "sharding_db";

    public void testSharding() {
        this.reloadShardRuleActualDataNodes(shardingSphereDataSource, schemaNameForTOrder);
    }

    private void reloadShardRuleActualDataNodes(ShardingSphereDataSource dataSource, String schemaName) {
        // Context manager.
        org.apache.shardingsphere.mode.manager.ContextManager contextManager = dataSource.getContextManager();

        // Rule configuration.
        Collection<RuleConfiguration> ruleConfigList = dataSource.getContextManager()
                .getMetaDataContexts()
                .getMetaData(schemaName)
                .getRuleMetaData()
                .getConfigurations();
        // update context
        contextManager.alterRuleConfiguration(schemaName, ruleConfigList);
    }
}
```
It's just need to execute `contextManager.alterRuleConfiguration()` to reload `actual-data-nodes`

**Comment by StarHuzy** [comment]
> There is also some experiment in ShardingSphere 4.x to implement `SPI` in the registry to dynamically modify `actualDatanodes`, this process becomes more complex in `5.x` as the data distribution changes and the `ShardingRule` is rebuilt, I wonder if anyone's willing to do that. If you dispense with `ShardingSphere` data sources altogether, you can use its algorithm classes to encapsulate util yourself, bypassing the problems `actualDatanodes` needs to find.

hello  , i Use custom table splitting strategy ，Successfully dynamically adding nodes
There will be no issues in the SQL execution of a single tables，But if there are node configuration issues in cascading queries with `join query`

![image](https://github.com/apache/shardingsphere/assets/42610282/49a8b4b3-006a-49fc-950f-d9677252a6dc)


```
@Component
@Slf4j
public class DataShardingAlgorithm implements StandardShardingAlgorithm<Long> {


    @Override
    public Collection<String> doSharding(Collection<String> collection, RangeShardingValue<Long> rangeShardingValue) {
        System.out.println("demo = " + collection);
        return collection;
    }

    @Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<Long> preciseShardingValue) {
        StringBuilder resultTableName = new StringBuilder();
        String logicTableName = preciseShardingValue.getLogicTableName();
        // 拼接的tenantId，格式为 表名_{tenant_id}
        resultTableName.append(logicTableName).append("_").append(preciseShardingValue.getValue());
        String newTableName = resultTableName.toString().toLowerCase();
        if (!collection.contains(newTableName)) {
            // 动态新增节点
            ShardingAlgorithmTool.copyTable(logicTableName,newTableName);
            collection.add(newTableName);
        }
        System.out.println("collection = " + collection);
        return newTableName;
    }
    @Override
    public String getType() {
        return null;
    }
    @Override
    public void init(Properties properties) {

    }

}
```

**Comment by linghengqian** [comment]
- @StarHuzy Hi, since this issue has long been closed, the content discussed above is no longer of any currency as a large number of API changes have been made.  Please open a new issue for discussion.

**Comment by StarHuzy** [comment]
> * @StarHuzy Hi, since this issue has long been closed, the content discussed above is no longer of any currency as a large number of API changes have been made.  Please open a new issue for discussion.
Sorry for the slow response，I tried to explain him in simple and detailed terms.
This is my problem #28704  It was written in great detail and included the code ，Thank you very much for taking the time to answer， I think this is a significant discovery

**Comment by StarHuzy** [comment]
> * @StarHuzy Hi, since this issue has long been closed, the content discussed above is no longer of any currency as a large number of API changes have been made.  Please open a new issue for discussion.
@linghengqian 
Sorry for the slow response，I tried to explain him in simple and detailed terms.
This is my problem https://github.com/apache/shardingsphere/issues/28704 It was written in great detail and included the code ，Thank you very much for taking the time to answer， I think this is a significant discovery

**Comment by linghengqian** [comment]
- To make a long story short, modifying actualDataNodes via the Java API is still not very human-friendly. I've opened https://github.com/apache/shardingsphere/pull/37778 . The branch where the PR is located supports this syntax.

```java
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
public class ExampleUtils {
    void test() throws SQLException {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:shardingsphere:classpath:demo.yaml");
        config.setDriverClassName("org.apache.shardingsphere.driver.ShardingSphereDriver");
        try (HikariDataSource dataSource = new HikariDataSource(config);
             Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    create default sharding database strategy if not exists (
                        type = 'standard',
                        sharding_column = user_id,
                        sharding_algorithm(
                            type(
                                name = class_based,
                                properties(
                                    'strategy' = 'STANDARD',
                                    'algorithmClassName' = 'org.apache.shardingsphere.test.natived.commons.algorithm.ClassBasedInlineShardingAlgorithmFixture'
                                )
                            )
                        )
                    )
                    """);
            statement.execute("""
                    create sharding table rule if not exists t_order (
                        datanodes(
                            '<LITERAL>ds_0.t_order, ds_1.t_order, ds_2.t_order'
                        ),
                        key_generate_strategy(column = order_id, type(name = 'SNOWFLAKE'))
                    )
                    """);
            statement.execute("SELECT * FROM t_order");
            statement.execute("""
                    alter sharding table rule t_order (
                        datanodes(
                            '<LITERAL>ds_0.t_order, ds_1.t_order, ds_2.t_order, ds_3.t_order'
                        ),
                        key_generate_strategy(column = order_id, type(name = 'SNOWFLAKE'))
                    )
                    """);
            statement.execute("SELECT * FROM t_order");
        }
    }
}
```
- Feel free to submit reviews for https://github.com/apache/shardingsphere/pull/37778 .
