### ISSUE TITLE
I chose the sharding strategy is preciseShardingAlgorithm, but I want to use HintManager

### ISSUE THREAD

**Issue by Gordonman** [apache/shardingsphere#16720]
## Question

shardingshere version: 4.0.0-RC2

I chose the sharding strategy is preciseShardingAlgorithm, and the precise algorithm class was specified. 

When there is no sharding key in SQL, I want to use HintManager to manually specify the sharding key, but it does not take effect.

I checked the source code and found that only one sharding rule can be configured.

Is there any way to solve my problem？

thanks.

**Comment by RaigorJiang** [comment]
Hi @Gordonman , Please see if sql hint can solve your problem？

**Comment by RaigorJiang** [comment]
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#route-to-the-specified-database-with-hint

**Comment by Gordonman** [comment]
> https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#route-to-the-specified-database-with-hint

Thank you  @RaigorJiang. 
I've tried before , but it can't solve my problem.   Because I have specified the table strategy is standard. 
Use hintManager.addTableShardingValue to add sharding key value of table. it does not take effect.

**Comment by RaigorJiang** [comment]
@Gordonman 
I am referring to specifying sharding routing through `SQL comments`, which does not require hint algorithm and is designed for sharding algorithm.
But this requires you to upgrade to version 5.x.

- example
```sql
/* ShardingSphere hint: dataSourceName=ds_0 */
SELECT * FROM t_order;
```

**Comment by Gordonman** [comment]
@RaigorJiang  
Ok, I see, thanks. Version upgrade is a difficult thing. 
I have another question, Dose SQL comments support specifying sharding table? I checked the doc and found that it seems to only support data source routing

**Comment by RaigorJiang** [comment]
> @RaigorJiang Ok, I see, thanks. Version upgrade is a difficult thing. I have another question, Dose SQL comments support specifying sharding table? I checked the doc and found that it seems to only support data source routing

Yes, just support hint to data source for now.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
