### ISSUE TITLE
How to dynamically add data sources and specify cuts

### ISSUE THREAD

**Issue by wqzcoder** [apache/shardingsphere#16739]
I would like to ask, I control the data source myself, and then what annotations are dynamically cut to the data source I dynamically add

**Comment by wqzcoder** [comment]
Help me

**Comment by strongduanmu** [comment]
You can try distsql, it allows users to add resources(datasources) dynamically. For more information, you can refer this doc——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/.

**Comment by wqzcoder** [comment]
> You can try distsql, it allows users to add resources(datasources) dynamically. For more information, you can refer this doc——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/.

I use shardingJdbc.For example, now I configured 2 data sources, and at runtime, I added 3 more data sources, so now there are 5 data sources, so how do I specify one of the libraries  
![image](https://user-images.githubusercontent.com/67619412/163088520-ffd8e75f-73aa-4ae3-ba39-7236a043c109.png)

**Comment by strongduanmu** [comment]
@wqzcoder It is not possible to dynamically add data sources using ShardingSphere-JDBC alone. You can mix and deploy ShardingSphere-JDBC and ShardingSphere-Proxy in Cluster mode, allowing you to dynamically add data sources through DistSQL.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
