### ISSUE TITLE
Select Order by SQL EPE

### ISSUE THREAD

**Issue by ycy1991** [apache/shardingsphere#16734]
## Question
config
![image](https://user-images.githubusercontent.com/16506338/162715280-19526b66-9821-4df1-85ae-2e3efa311803.png)
router
![image](https://user-images.githubusercontent.com/16506338/162715080-14a40de0-99fd-452c-859b-e6376f677172.png)

sql
![image](https://user-images.githubusercontent.com/16506338/162715503-fe90d29d-6e40-43a9-992e-ee475b91c816.png)

NPE
![image](https://user-images.githubusercontent.com/16506338/162715568-8a815685-55ba-4e4f-91e7-06893d229a04.png)

![image](https://user-images.githubusercontent.com/16506338/162715196-c791bc01-01a7-4ead-b11c-368a87a328d5.png)

**Comment by tuichenchuxin** [comment]
Seems your `xxl_job_log_0_1` is not exists.

**Comment by ycy1991** [comment]
Must this table be created? xxl_job_log_0_1 ，Can I assign values manually?

**Comment by ycy1991** [comment]
It's a little strange. I think as long as any physical table corresponding to the logical table is created, it should be able to match?
