### ISSUE TITLE
Shadingjdbc datasource initialization is too slowly

### ISSUE THREAD

**Issue by Even-sun** [apache/shardingsphere#16753]
shadingjdbc version: 5.1.0

same issue:  #10938

in my database it used one logic table . when initializing the datasource, read the metadata of all my tables.  8000+ tables takes 15 minutes.  how can i resolved it.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/21055134/162872868-55ff1018-c1bd-4b3d-bb6f-a205b0b40dba.png">

**Comment by zjcnb** [comment]
@Even-sun  Hi, The metadata multi-threaded loading is only for data sources, and table-level multi-threaded loading not support now. Are you interested in enhancement to it?

**Comment by Even-sun** [comment]
> Hi, The metadata multi-threaded loading is only for data sources, and table-level multi-threaded loading not support now. Are you interested in enhancement to it?

i hope not to load all tables metadata, just process ShardingRule contained tables,  SingleTableRule load all table it is too slowly.

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
@strongduanmu sure.
@Even-sun Can you help to position the slow code?
And 8000+ are all single tables one datasource?

**Comment by Even-sun** [comment]
> @strongduanmu sure. @Even-sun Can you help to position the slow code? And 8000+ are all single tables one datasource?

Yes, these tables are in the one datasource. but i only have one logic table need sharding,

**Comment by echenchou** [comment]
<img width="723" alt="image" src="https://github.com/apache/shardingsphere/assets/16699508/259b6c9b-12d8-48c2-bfd4-7d3d61285d1b">
@xjsunup 排除这个，直接起飞，开发者不愿意搞配置，那就不用它也应该没啥影响。

**Comment by xjsunup** [comment]
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/16699508/274188228-259b6c9b-12d8-48c2-bfd4-7d3d61285d1b.png"> @xjsunup 排除这个，直接起飞，开发者不愿意搞配置，那就不用它也应该没啥影响。

当时也是覆盖了源码的部分实现。总之解决就好了😄

**Comment by echenchou** [comment]
您的邮件已收到！我会尽快查阅的！谢谢~
