### ISSUE TITLE
Add more unit test for DatabaseAdminQueryBackendHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16759]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for DatabaseAdminQueryBackendHandler.

- [ ] DatabaseAdminQueryBackendHandler#execute
- [ ] DatabaseAdminQueryBackendHandler#next
- [ ] DatabaseAdminQueryBackendHandler#getRowData

To finish this task, you can refer `BroadcastDatabaseBackendHandlerTest`, this class give a good example.

**Comment by longtai-cn** [comment]
@strongduanmu hi, can you assign it to me

**Comment by strongduanmu** [comment]
@longtai-cn Welcome.
