### ISSUE TITLE
HASH_MOD sharding-count configuration question

### ISSUE THREAD

**Issue by luckleemon** [apache/shardingsphere#16751]
i want use the hash_mod sharding-algorithm, and have configure the sharding-count , but when i start the project
it throw the exception as the below, why?

[org/apache/shardingsphere/sharding/spring/boot/ShardingRuleSpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.infra.config.RuleConfiguration]: Factory method 'shardingRuleConfiguration' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hash_mod_user': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Sharding count cannot be null.

and my config like this:

sharding-algorithms:
          hash_mod_user:
            type: HASH_MOD
            props:
              sharding-count: '2'

**Comment by RaigorJiang** [comment]
Hi @luckleemon 
What is the version of ShardingSphere?  
Please provide some more information, like sharding table rule.  I suspect this problem is caused by not using auto table.

**Comment by luckleemon** [comment]
i have solved the problem， 'hash_mod_user' do not works ，because  it must replace the '_' to '-',  as  'hash-mod-user'
