### ISSUE TITLE
Add more unit test for AlterViewStatementHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#16772]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for AlterViewStatementHandler.

- [ ] AlterViewStatementHandler#getRenameView

To finish this task, you can refer AlterViewStatementHandlerTest, it has already provide an example.

**Comment by ThanoshanMV** [comment]
Hi, can I try this

**Comment by strongduanmu** [comment]
@ThanoshanMV Of course, but we need to wait pr #16771 merged.
