### ISSUE TITLE
Dynamic create table add unuse tag

### ISSUE THREAD

**Issue by muchengyang** [apache/shardingsphere#16793]
## Question

**For English only**, other languages will not accept.
Using mybatis to create a table, SQL rewrites the index field and adds the table name. This is a very bad rewriting SQL. After looking at the source code, I can't find a solution. Can I configure it to prevent it from rewriting SQL in this way, or customize the function of rewriting SQL

![image](https://user-images.githubusercontent.com/16506338/163154508-776d5482-0711-4fbb-857e-94fd085a40e7.png)

![image](https://user-images.githubusercontent.com/16506338/163154645-81e6010d-0b4a-4d5b-9428-3ca62bec8fd4.png)

**Comment by ycy1991** [comment]
Thinks,I understand, but I think this location should have different database types and pluggable rewrites, otherwise it's a little unfriendly to use

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
