### ISSUE TITLE
shardingsphere-jdbc 5.1.0 Cluster mode ClassNotFoundException

### ISSUE THREAD

**Issue by qiaoheng110** [apache/shardingsphere#16792]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/20252910/163135058-4c671a37-8e23-49c9-b967-1809455c0655.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/20252910/163135225-d24ca3df-994e-4111-a7bb-56a3cad40ce2.png">
when i add the below dependency missing another class，I think it conflicts with the dubbo version. Most projects will use dubbo. What version of curator should I use?
<img width="687" alt="image" src="https://user-images.githubusercontent.com/20252910/163135453-0cc96a4b-2f27-46e6-89b0-e16cbc6597de.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/20252910/163135692-fca1f2aa-94ac-4a27-a931-55bf3473f879.png">

**Comment by TeslaCN** [comment]
Could you check the actual version of Curator? The ShardingSphere require Curator 5.x.

**Comment by qiaoheng110** [comment]
> Could you check the actual version of Curator? The ShardingSphere require Curator 5.x.
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/20252910/163166497-37d6beb8-f411-470e-b33e-f00690f69350.png">

**Comment by qiaoheng110** [comment]
> Could you check the actual version of Curator? The ShardingSphere require Curator 5.x.

i think shardingsphere-cluster-mode-repository-zookeeper-curator    the version of Curator depends on is wrong

**Comment by TeslaCN** [comment]
> > Could you check the actual version of Curator? The ShardingSphere require Curator 5.x.
> 
> i think shardingsphere-cluster-mode-repository-zookeeper-curator the version of Curator depends on is wrong

The version of Curator may be changed by your other dependencies.
