### ISSUE TITLE
Cannot get result in Association query with single table

### ISSUE THREAD

**Issue by wayinit** [apache/shardingsphere#16807]
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy master
### Expected behavior
got the count
### Actual behavior
got an error
[C1997][1997] Runtime exception: [All tables must be in the same datasource.]
### Reason analyze (If you can)
I have no idea.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT count(0)
FROM tb_im_current_chat ticc
         LEFT JOIN tb_mem_personal tmp ON tmp.tb_mem_no = ticc.tb_user_id
tb_im_current_chat is single table
tb_mem_personal  is sharding table

**Comment by terrymanu** [comment]
Closed because of no feedback for long time
