### ISSUE TITLE
Slack channel is invalid

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#16814]
I can't open the channel provided by the official website. Is it not maintained now?

**Comment by zjcnb** [comment]
@VeejaLiu Hi, Can your provider official website url? I can visit it in my here.

**Comment by VeejaLiu** [comment]
https://apacheshardingsphere.slack.com/?redir=%2Fmessages%2FC026MLH7F34

**Comment by VeejaLiu** [comment]
<img width="2026" alt="image" src="https://user-images.githubusercontent.com/22064617/163335678-e921e827-ba70-424c-9945-a49fd674a9d4.png">

**Comment by VeejaLiu** [comment]
I am in hiretual.slack.com

**Comment by VeejaLiu** [comment]
I have entered slack through the invitation connection. Thank you, but please check this problem.
