### ISSUE TITLE
When managing data sources in the UI, no configuration is loaded

### ISSUE THREAD

**Issue by weijialiu-hiretual** [apache/shardingsphere#16825]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/82020360/163358902-defed321-25c9-43d0-921b-6d6741e93c07.png">
No Data:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/82020360/163358959-4d7885dd-0ad3-49a7-8625-ade429926d76.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/82020360/163359044-5e298c1c-311b-4919-9a57-9a5a1f3ef458.png">
But in zookeeper, There are shardingsphere related configurations.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/82020360/163359252-1ed997a7-41d5-4970-83ec-c115bbc4c476.png">

**Comment by strongduanmu** [comment]
Hi @weijialiu-hiretual thank you for your feedback, ShardingSphere-UI is not maintained, you can modify the source code by yourself.

**Comment by weijialiu-hiretual** [comment]
OK I see
Thank you
