### ISSUE TITLE
Documentation lacks description of custom properties for CLASS_BASE

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#16834]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Yes, refer to https://github.com/apache/shardingsphere/pull/14784 .

### Describe the feature you would like.

- Seen in https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/ , the documentation lacks description of custom properties for CLASS_BASE. But according to 5.1.0 PR, this feature has been implemented.

- ![image](https://user-images.githubusercontent.com/20187731/163387435-f08e8f1f-eaeb-4101-a5ea-5bbc592d89be.png)

**Comment by zjcnb** [comment]
@linghengqian Hi, Can you submit a pull request?

**Comment by linghengqian** [comment]
> @linghengqian Hi, Can you submit a pull request?

The layout of this piece makes me not sure how to add the explanation. I hope other friends can submit the PR.
