### ISSUE TITLE
The shardingsphere-sql-parser-oracle's Source code[autogen]  does not exist

### ISSUE THREAD

**Issue by wrs1226** [apache/shardingsphere#16845]
The shardingsphere-sql-parser-oracle's Source code does not exist：
shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/java/org/apache/shardingsphere/sql/parser/autogen

![image](https://user-images.githubusercontent.com/11829959/163514157-cc568d7a-8810-430b-8e15-0c8f11dc6d9c.png)

**Comment by strongduanmu** [comment]
@wrs1226 You can use `mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C -Dcheckstyle.skip=true` to generate these code.

**Comment by wrs1226** [comment]
The shardingsphere-sql-parser-oracle's Source code[autogen] will download from the maven&nbsp;repository? shardingsphere-sql-parser-oracle-5.1.0-sources.jar?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] The shardingsphere-sql-parser-oracle's Source code[autogen]  does not exist (Issue #16845)





 
@wrs1226 You can use mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C -Dcheckstyle.skip=true to generate these code.

**Comment by wrs1226** [comment]
The shardingsphere-sql-parser-oracle's Source code[autogen] will download from the maven repository? shardingsphere-sql-parser-oracle-5.1.0-sources.jar?






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] The shardingsphere-sql-parser-oracle's Source code[autogen]  does not exist (Issue #16845)





 
@wrs1226 You can use mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C -Dcheckstyle.skip=true to generate these code.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

QQ录屏20220415151442.mp4 (28.96M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=75363332cdf706c6a967d362426304175e0f0b005201050b1507070a574e025c0a041e0a075705150055500b055354010b005150647b366969f48ff4a551060a0a060703515203090c02011c0913023805&t=exs_ftn_download&code=8632dc68
