### ISSUE TITLE
Parser engine‘s compatible issues with oracle

### ISSUE THREAD

**Issue by wrs1226** [apache/shardingsphere#16841]
Problem details：
1、	SQL generated by hibernate‘s Session.get(cls,id)：
select sysuser0_.id as id1_63_1_, sysuser0_.create_datetime as create_d2_63_1_, sysuser0_.creator as creator3_63_1_, sysuser0_.deleted as deleted4_63_1_, sysuser0_.remark as remark5_63_1_, sysuser0_.serial_number as serial_n6_63_1_, sysuser0_.update_datetime as update_d7_63_1_, sysuser0_.updater as updater8_63_1_, sysuser0_.AREA as AREA9_63_1_, sysuser0_.DEGREES as DEGREES10_63_1_, sysuser0_.department_id as departm11_63_1_, sysuser0_.ENDVALIDDATE as ENDVALI12_63_1_, sysuser0_.ESOP_ACCOUNT as ESOP_AC13_63_1_, sysuser0_.is_enabled as is_enab14_63_1_, sysuser0_.is_locked as is_lock15_63_1_, sysuser0_.MAIL as MAIL16_63_1_, sysuser0_.MOBILE as MOBILE17_63_1_, sysuser0_.POSITION as POSITIO18_63_1_, sysuser0_.SAVE_LEVEL as SAVE_LE19_63_1_, sysuser0_.SEC_LEVEL as SEC_LEV20_63_1_, sysuser0_.STVALIDDATE as STVALID21_63_1_, sysuser0_.userDetail_id as userDet30_63_1_, sysuser0_.TOTAL_SPACE as TOTAL_S22_63_1_, sysuser0_.TYPE as TYPE23_63_1_, sysuser0_.UNITID as UNITID24_63_1_, sysuser0_.user_account as user_ac25_63_1_, sysuser0_.user_name as user_na26_63_1_, sysuser0_.user_password as user_pa27_63_1_, sysuser0_.USERTYPE as USERTYP28_63_1_, sysuser0_.WORKLIFES as WORKLIF29_63_1_, sysuserdet1_.id as id1_65_0_, sysuserdet1_.create_datetime as create_d2_65_0_, sysuserdet1_.creator as creator3_65_0_, sysuserdet1_.deleted as deleted4_65_0_, sysuserdet1_.remark as remark5_65_0_, sysuserdet1_.serial_number as serial_n6_65_0_, sysuserdet1_.update_datetime as update_d7_65_0_, sysuserdet1_.updater as updater8_65_0_, sysuserdet1_.address as address9_65_0_, sysuserdet1_.birthday as birthda10_65_0_, sysuserdet1_.department as departm11_65_0_, sysuserdet1_.email as email12_65_0_, sysuserdet1_.mobilePhone as mobileP13_65_0_, sysuserdet1_.telephone as telepho14_65_0_, sysuserdet1_.university as univers15_65_0_ from sys_user sysuser0_ left outer join sys_userdetail sysuserdet1_ on sysuser0_.userDetail_id=sysuserdet1_.id where sysuser0_.id=?

2、 In oracle‘s parser , parser engine‘‘s parser throw exception , It was  parser for the second time
![image](https://user-images.githubusercontent.com/11829959/163507353-130d19b9-7263-4a1e-a3c3-a1c7d9d8a442.png)

On line 10 of the OracleStatementParser’s selectSubquery()  code：getInterpreter().adaptivePredict(_input,54,_ctx) It cannot get an explicit type
![image](https://user-images.githubusercontent.com/11829959/163507436-bf9cb0d8-b9de-4350-bd06-e8ea0130f00d.png)

3、	On line 393 of the  ParserATNSimulator's adaptivePredict(_input,54,_ctx) code：int alt = execATN(dfa, s0, input, index, outerContext);  It cannot get an explicit type and throw NoViableAltException e = noViableAlt(input, outerContext, previousD.configs, startIndex);
![image](https://user-images.githubusercontent.com/11829959/163507527-b1b5e45e-1380-4710-86fe-7a44bf8a97f8.png)

![image](https://user-images.githubusercontent.com/11829959/163507551-01b0fc2b-1e6e-498e-b039-56682c1ff997.png)

4、The last of program's problem：
![image](https://user-images.githubusercontent.com/11829959/163507610-c1e0f8fd-b108-4ba5-8c8b-3bf98b49114b.png)

**Comment by strongduanmu** [comment]
Hi @wrs1226, thank you for your feedback, and can you translate this issue to english?

**Comment by wrs1226** [comment]
> Hi @wrs1226, thank you for your feedback, and can you translate this issue to english?
不好意思，英语不好

**Comment by strongduanmu** [comment]
@wrs1226 You can try to translate this issue with some util, such as google translate.

**Comment by wrs1226** [comment]
> @wrs1226 You can try to translate this issue with some util, such as google translate.

嗯嗯 翻译了一下

**Comment by tuichenchuxin** [comment]
I'll check it.

**Comment by tuichenchuxin** [comment]
It's because of the word `POSITION`.
You can use "POSITION" instead.
@wrs1226

**Comment by tuichenchuxin** [comment]
Is there anyone interested to solve this issue?

**Comment by sgunadhya** [comment]
I am interested in solving this issue. I need guidance on how to solve it.

**Comment by AllyKaz** [comment]
Having looked at this, I don't think there's an issue to solve. The double parsing is the consequence of an optimisation that first attempts to parse with a faster, but less powerful algorithm (SLL), that either returns a correct parse tree or throws an error which may, or may not, indicated that there's a actual syntax error or it requires the more powerful LL algorithm. 

Consequently, given the use of POSITION is a syntax error, the double parsing is a necessary and unavoidable part of the optimisation. Maybe the optimisation could be improved on, but I don't see this behaviour as necessitating that, and that's probably a bit much for good first issue.

[https://tomassetti.me/improving-the-performance-of-an-antlr-parser/](url)
