### ISSUE TITLE
[shardingsphere-encrypt] The encrypted data is not automatically decrypted during query.

### ISSUE THREAD

**Issue by mingyifei** [apache/shardingsphere#16850]
## Bug Report

The encrypted data is not automatically decrypted during query.

Scenario: Shadow and encryption and decryption test. When the client configures javaagent, decryption fails.
javaAgent: https://github.com/SphereEx/cyborg-flow

version: master 

server.yaml
[server.md](https://github.com/apache/shardingsphere/files/8495515/server.md)

config-shadow.yaml
[config-shadow.md](https://github.com/apache/shardingsphere/files/8495519/config-shadow.md)

client package：
shardingsphere-examples ：shardingsphere-proxy-example ：shardingsphere-proxy-boot-mybatis-example

**Comment by strongduanmu** [comment]
Hi @mingyifei, I have try your configuration, but I can't reproduce this result. Can you give a step to help reproduce this problem?

**Comment by mingyifei** [comment]
> Hi @mingyifei, I have try your configuration, but I can't reproduce this result. Can you give a step to help reproduce this problem?

My client uses javaagent, javaAgent: https://github.com/SphereEx/cyborg-flow

**Comment by tuichenchuxin** [comment]
I want to check this issue.

**Comment by soulasuna** [comment]
@mingyifei  Please provide the configuration file `config-shadow.yaml` in `cyborg-database-shadow`

**Comment by mingyifei** [comment]
> @mingyifei Please provide the configuration file `config-shadow.yaml` in `cyborg-database-shadow`
[config-shadow.md](https://github.com/apache/shardingsphere/files/8509163/config-shadow.md)

**Comment by mingyifei** [comment]
> @mingyifei Please provide the configuration file `config-shadow.yaml` in `cyborg-database-shadow`

I didn't start cyborg-database-shadow. I used the master branch code to start proxy. I only used cyborg-agent

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
