### ISSUE TITLE
How to configure the default connection pool configuration for all data sources? Only config once.

### ISSUE THREAD

**Issue by skyjilygao** [apache/shardingsphere#16865]
## Question
How to configure the default connection pool configuration for all data sources? Only config once.

**Comment by strongduanmu** [comment]
@skyjilygao Thank you for your feedback. Currently ShardingSphere does not support configuration of default data source properties, you need to configure properties for each data source separately. In addition, you can also simplify the configuration of yaml files through DistSQL.
