### ISSUE TITLE
the select was routed to write-ds, why?

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#16875]
## Question

1、this is my config：
![image](https://user-images.githubusercontent.com/28882195/163668189-58a48fe6-929e-4d3b-976c-543341539d8e.png)

2、the execution result：
![image](https://user-images.githubusercontent.com/28882195/163668270-c918002f-25b8-45f0-a3aa-183eeb7db6b8.png)

**Comment by strongduanmu** [comment]
Hi @doveylovey, can you execute insert statement and select statement in a transaction?

**Comment by zjcnb** [comment]
The same to #14868

**Comment by doveylovey** [comment]
> The same to #14868

Has this problem been solved now？Please tell me what I should do?

**Comment by doveylovey** [comment]
@zjcnb Has this problem been solved now？Please tell me what I should do.

**Comment by doveylovey** [comment]
> Hi @doveylovey, can you execute insert statement and select statement in a transaction?

This is an example in the project, I just changed the configuration, can you tell me how to change it?

**Comment by zjcnb** [comment]
> @zjcnb Has this problem been solved now？Please tell me what I should do.

@doveylovey Hi, you can find `OrderServiceImpl.class` in `example-spring-mybatis` module. Remove `@Transactional ` annotation in `processFailure()` method and `processSuccess()` method.

**Comment by doveylovey** [comment]
> Hi @doveylovey, can you execute insert statement and select statement in a transaction?

@strongduanmu I can't understand what you said, can you speed up how to modify?

**Comment by strongduanmu** [comment]
@doveylovey Sorry, I made a typo. What I want to confirm is, are you executing the insert and select statements in transaction? The statements in the transaction will be executed by the primary datasource.

**Comment by doveylovey** [comment]
> > @zjcnb Has this problem been solved now？Please tell me what I should do.
> 
> @doveylovey Hi, you can find `OrderServiceImpl.class` in `example-spring-mybatis` module. Remove `@Transactional ` annotation in `processFailure()` method and `processSuccess()` method.

Your solution only works for `example-spring-mybatis` module, What about other modules?

**Comment by doveylovey** [comment]
@zjcnb Your solution only works for example-spring-mybatis module, What about other modules?

**Comment by doveylovey** [comment]
> @doveylovey Sorry, I made a typo. What I want to confirm is, are you executing the insert and select statements in transaction? The statements in the transaction will be executed by the primary datasource.

@strongduanmu yes, i executing the insert and select statements in transaction. But, if I don't do that, how do you guarantee transactions?

**Comment by doveylovey** [comment]
> > @zjcnb Has this problem been solved now？Please tell me what I should do.
> 
> @doveylovey Hi, you can find `OrderServiceImpl.class` in `example-spring-mybatis` module. Remove `@Transactional ` annotation in `processFailure()` method and `processSuccess()` method.

@zjcnb Your solution only works for example-spring-mybatis module, What about other modules?

**Comment by strongduanmu** [comment]
> > @doveylovey Sorry, I made a typo. What I want to confirm is, are you executing the insert and select statements in transaction? The statements in the transaction will be executed by the primary datasource.
> 
> @strongduanmu yes, i executing the insert and select statements in transaction. But, if I don't do that, how do you guarantee transactions?

If you start a transaction, I think the route result is right. For more detail, please refer to this doc——https://shardingsphere.apache.org/document/current/cn/features/readwrite-splitting/use-norms.

**Comment by doveylovey** [comment]
> > > @doveylovey Sorry, I made a typo. What I want to confirm is, are you executing the insert and select statements in transaction? The statements in the transaction will be executed by the primary datasource.
> > 
> > 
> > @strongduanmu yes, i executing the insert and select statements in transaction. But, if I don't do that, how do you guarantee transactions?
> 
> If you start a transaction, I think the route result is right. For more detail, please refer to this doc——https://shardingsphere.apache.org/document/current/cn/features/readwrite-splitting/use-norms.

@strongduanmu Ok, thank you very much
