### ISSUE TITLE
conflict key generated: shardingsphere/sharding-jdbc-core/src/main/java/com/dangdang/ddframe/rdb/sharding/keygen/DefaultKeyGenerator.java

### ISSUE THREAD

**Issue by weekndyyy** [apache/shardingsphere#16895]
I am using sharding-jdbc-core 4.1.1 and defined a custom key generator which is based on **shardingsphere/sharding-jdbc-core/src/main/java/com/dangdang/ddframe/rdb/sharding/keygen/DefaultKeyGenerator.java**, the only difference is changing WORKER_ID_BITS and SEQUENCE_BITS to 6 bits:

`private static final long SEQUENCE_BITS = 6L;`
`private static final long WORKER_ID_BITS = 6L;`

My concurrency is not large, but sometimes a key conflict occurs, two threads generated the same key:
![snowflake](https://user-images.githubusercontent.com/48077356/163783910-13f11aad-a342-4fee-8833-099f0e9c6411.PNG)

How can I fix this problem?

**Comment by zjcnb** [comment]
@weekndyyy  Hello, Can you try it again with 5.1.1 version? I think you used version are too old.

**Comment by weekndyyy** [comment]
> @weekndyyy Hello, Can you try it again with 5.1.1 version? I think you used version are too old.

Is this problem caused by the low version?

**Comment by pzpupu** [comment]
我使用5.1.1版本，在并发高的时候使用snowflake id, 仍会出现重复的情况
---------------
I use version 5.1.1 and use snowflake id when the concurrency is high, and there will still be duplicates

**Comment by Qiudenghui** [comment]
你好，请问下这个最后怎么处理了，现在我也遇到这个情况，workerId  也配置了，仍然主键重复
