### ISSUE TITLE
Add unit test for ComputeNode.getProcessTriggerInstanceIdNodePath(final String instanceId, final InstanceType instanceType, final String showProcessListId)

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16926]

**Comment by csonezp** [comment]
please assign it to me ,i want have a try

**Comment by zjcnb** [comment]
> please assign it to me ,i want have a try

Done.

**Comment by zjcnb** [comment]
@csonezp Hi, are you still watching this mission?

**Comment by csonezp** [comment]
> @csonezp Hi, are you still watching this mission?

yeah,I will finish it this weekend.
