### ISSUE TITLE
force index PRIMARY cause SQL syntax

### ISSUE THREAD

**Issue by udrnrso** [apache/shardingsphere#16934]
### Which version of ShardingSphere did you use?

5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior
update sql with force index  as following should be ok
update t_test_table force index (PRIMARY)
set test_column='value'

### Actual behavior
throw SQL syntax error

### Reason analyze (If you can)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.identifier
_input.LA(1)  get   PRIMARY 521
but PRIMARY  is treat as exception

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
update t_test_table force index (PRIMARY)
set test_column='value'

**Comment by strongduanmu** [comment]
@udrnrso Thank you for your feedback, I will investigate this issue.
