### ISSUE TITLE
About the slow start of ShardingSphere

### ISSUE THREAD

**Issue by zxtprivate** [apache/shardingsphere#16942]
In my team, some databases were divided into databases by month, resulting in the increase of databases. When myCAT was replaced with Sharding, I noticed that the startup was slow due to too many database links.
Through debugging positioning code found in org. Apache. Shardingsphere. Infra. Database. The type of getDatabaseType (final Collection < DataSource > dataSources) The method is a little slow
![截屏2022-04-20 11 01 03](https://user-images.githubusercontent.com/50144235/164141988-4081016c-1545-4035-97e2-77e7e6d0e376.png)
I'm going to change it a little bit here
![截屏2022-04-20 11 08 02](https://user-images.githubusercontent.com/50144235/164142458-f88ccf91-35c4-473c-a20c-ee6366b40919.png)
Before the change, my project started waiting about 3 minutes and 30 seconds for a database queue link, and after the change, only 40 seconds.
I'm just going to do a demo here, hoping that the authorities can optimize this code so that when the number of database links is high, the long startup always causes people to wait
Thread pool example.
![截屏2022-04-20 11 08 35](https://user-images.githubusercontent.com/50144235/164143284-ad6f8fa1-17b4-4897-99b7-512fbbe40009.png)

**Comment by TeslaCN** [comment]
Hi @zxtprivate 
Are you interested in submitting a PR to fix this?

**Comment by zxtprivate** [comment]
> Hi @zxtprivate Are you interested in submitting a PR to fix this?

I'm sorry, what is PR? I'm just a rookie. I'm not familiar with it

**Comment by TeslaCN** [comment]
> > Hi @zxtprivate Are you interested in submitting a PR to fix this?
> 
> I'm sorry, what is PR? I'm just a rookie. I'm not familiar with it

It means that contributing your codes to Apache ShardingSphere. You may refer to https://shardingsphere.apache.org/community/en/contribute/contributor/. Please let us know if you are interested.

**Comment by zxtprivate** [comment]
> 

I'll try

**Comment by zxtprivate** [comment]
> > > 你好@zxtprivate你有兴趣提交 PR 来解决这个问题吗？
> > 
> > 
> > 对不起，什么是公关？我只是一只菜鸟。
> 
> 这意味着将您的代码贡献给 Apache ShardingSphere。您可以https://shardingsphere.apache.org/community/en/contribute/contributor/。如果您有兴趣，请告诉我们。

I'll try

**Comment by TeslaCN** [comment]
> I'll try

Welcome.
