### ISSUE TITLE
In Windows, the ShardingSphere-Proxy startup fails if the directory name contains a space

### ISSUE THREAD

**Issue by lvzbOne** [apache/shardingsphere#16953]
## I failed to start `ShardingSphere-Proxy 5.0.0-alpha` in Windows system because there are Spaces in a directory

**Space was converted to %20F causing an exception**
**It would be nice if it could parse correctly**
![在这里插入图片描述](https://img-blog.csdnimg.cn/d0bfeb3d56a24910a1b719513705dade.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBATHZRaUZlbg==,size_20,color_FFFFFF,t_70,g_se,x_16)

**Comment by TeslaCN** [comment]
Hi @lvzbOne 
Could you try the 5.1.1? This issue has been solved since 5.1.0. Duplicated with https://github.com/apache/shardingsphere/issues/13833
