### ISSUE TITLE
[Missing source file] SQLServerStatementParser,PostgreSQLStatementLexer

### ISSUE THREAD

**Issue by star10k** [apache/shardingsphere#16971]
Project:   shardingsphere-sql-parser  
Missing source file:  SQLServerStatementParser,PostgreSQLStatementLexer
Version:  4.0.1

**Comment by strongduanmu** [comment]
Hi @star10k, you can run `mvn clean install -Prelease -T 1C` to generate SQLServerStatementParser and PostgreSQLStatementLexer.

**Comment by star10k** [comment]
ok. thank you for your help!
