### ISSUE TITLE
Can I get the table name of the logical table name in the doSharding() method?

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#16999]
Can I get the table name of the logical table in the doSharding() method?
In this way, I can apply a set of rules to different tables.

**Comment by terrymanu** [comment]
Can you provide more details?

**Comment by VeejaLiu** [comment]
@terrymanu 
In shardingsphere, the set of sub tables corresponds to a logical table. 

For example, the actual tables are `use_a`, `user_b`, and `user_c`. But in fact, their logical table name is `user`. I mean, can I get the current logical table name in the dosharding() method? I guess it's not very difficult.

If my description is not very clear, I can try to describe it again.

Thank you for your hard work.

**Comment by terrymanu** [comment]
What is the proposal to get logic table name? I want the user API as easy as possible

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
