### ISSUE TITLE
Add test coverage report in GitHub action and remove travis in CI

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17014]
Hi, the travis CI is slower than GitHub action, it is better to remove it and use GitHub action only.
But the test coverage report is generated by travis now, please move it into GitHub action and and remove travis as well.

**Comment by Jacob953** [comment]
Hi, @terrymanu, I'd like to try. Could you assign me, please?

**Comment by terrymanu** [comment]
Great, please go ahead

**Comment by terrymanu** [comment]
Great Job!
