### ISSUE TITLE
[SQLException]Savepoint can only be used in transaction blocks

### ISSUE THREAD

**Issue by wuguanyu** [apache/shardingsphere#17029]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
 no exception 

### Actual behavior

Savepoint can only be used in transaction blocks

**Comment by wuguanyu** [comment]
org.apache.shardingsphere.transaction. ConnectionTransaction
```
private final ShardingSphereTransactionManager transactionManager;
    
/**
     * Whether in transaction.
     * 
     * @return in transaction or not
     */
    public boolean isInTransaction() {
        return null != transactionManager && transactionManager.isInTransaction();
    }
```
if i use localTransaction , the ShardingSphereTransactionManager is always null.

**Comment by zjcnb** [comment]
@wuguanyu  Thank you for your feedback, I 'll check it.

**Comment by wuguanyu** [comment]
@zjcnb 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/24486917/164889768-19f172b5-c72b-47d6-90a1-20c7046b2170.png">

what codeStyle Our team use ?

**Comment by zjcnb** [comment]
@wuguanyu Can you provider your demo project?

**Comment by zjcnb** [comment]
> @zjcnb <img alt="image" width="842" src="https://user-images.githubusercontent.com/24486917/164889768-19f172b5-c72b-47d6-90a1-20c7046b2170.png">
> 
> what codestyle do our team use ?

Default style for idea. What's the problem?

**Comment by wuguanyu** [comment]
> @wuguanyu Can you provider your demo project?

I use my company business project. It hard to make demo project, I need try

**Comment by wuguanyu** [comment]
> > @zjcnb <img alt="image" width="842" src="https://user-images.githubusercontent.com/24486917/164889768-19f172b5-c72b-47d6-90a1-20c7046b2170.png">
> > what codestyle do our team use ?
> 
> Default style for idea. What's the problem?

I wanted to fixed, encounter some checkStyle issue

**Comment by wuguanyu** [comment]
> @wuguanyu Can you provider your demo project?

https://github.com/wuguanyu/shardingsphere/commits/2022-04-24-fix-bug
I try to fix by myself, It resolve my issue, but I can't confirm my code is correct or not

**Comment by jingshanglu** [comment]
> > @wuguanyu Can you provider your demo project?
> 
> https://github.com/wuguanyu/shardingsphere/commits/2022-04-24-fix-bug I try to fix by myself, It resolve my issue, but I can't confirm my code is correct or not

Maybe it's better to change check isInTransaction from `ConnectionManager` to `ShardingSphereConnection` use `isHoldTransaction` .

**Comment by wuguanyu** [comment]
> > > @wuguanyu Can you provider your demo project?
> > 
> > 
> > https://github.com/wuguanyu/shardingsphere/commits/2022-04-24-fix-bug I try to fix by myself, It resolve my issue, but I can't confirm my code is correct or not
> 
> Maybe it's better to change check isInTransaction from `ConnectionManager` to `ShardingSphereConnection` use `isHoldTransaction` .

it seem like my code is not good way to fix.  I only wanted fixed new SQLException("Savepoint can only be used in transaction blocks.") to make our company program to run on line

**Comment by wuguanyu** [comment]
> > @wuguanyu Can you provider your demo project?
> 
> https://github.com/wuguanyu/shardingsphere/commits/2022-04-24-fix-bug I try to fix by myself, It resolve my issue, but I can't confirm my code is correct or not

**Comment by princess-yanyan** [comment]
I also encounter this problem ，
maybe it's a bug，when i use local transaction with nested transactions，will cause “Savepoint can only be used in transaction blocks”
