### ISSUE TITLE
Add test cases for HighlyAvailableStatus's impl

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17023]
- [ ] Add test cases for MGRHighlyAvailableStatus
- [ ] Add test cases for ShowSlaveStatusHighlyAvailableStatus

**Comment by chakkk309** [comment]
Hi, I would like to work on this issue, please assign it to me.

**Comment by strongduanmu** [comment]
@chakkk309 Welcome.

**Comment by sunkai-cai** [comment]
HighlyAvailableStatus has been Replace。maybe we can close it。 https://github.com/apache/shardingsphere/pull/17078/files

**Comment by chakkk309** [comment]
> HighlyAvailableStatus has been Replace。maybe we can close it。 https://github.com/apache/shardingsphere/pull/17078/files

Yes, this module has been refactored.
