### ISSUE TITLE
Rename db-discovery type

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17025]
Hi, the current db-discovery type is `MGR`, `MASTER_SLAVE` and `openGauss` which are not in same abstract level and the case .

`MGR` and `MASTER_SLAVE` is for MySQL only, and `openGauss` is other db-discovery type of database, not HA method.

It is better to rename and standardize the db-discovery type. I prefer rename like the way below:

`MGR` -> `MySQL.MGR`
`MASTER_SLAVE` -> `MySQL.NORMAL_REPLICATION`
`openGauss` -> `openGauss.NORMAL_REPLICATION`

**Comment by zjcnb** [comment]
I agree, that 's a good idea.

**Comment by terrymanu** [comment]
I will change it soon
