### ISSUE TITLE
Use multiple threads to improve performance for DatabaseDiscoveryEngine.checkHighlyAvailableStatus()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17021]
Please search `// TODO query with multiple threads` in class `DatabaseDiscoveryEngine` to find the modify point.

Use multiple threads to improve performance when loading data from databases.
Please reuse `ExecutorEngine` for concurrency execute.

**Comment by weihubeats** [comment]
can i try this

**Comment by zjcnb** [comment]
> can i try this

Welcome, I assign you
