### ISSUE TITLE
Metadata in ProxyContext take effect ahead of time when altering sharding table rule and emitting scaling job

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17045]
## Bug Report

Related to issue #16924

### Which version of ShardingSphere did you use?
master branch, commit e826b154fe1846bb7227032386d6ea3c2d4b33d8

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
sharding table rule won't be changed immediately in `ShardingSphereRuleMetaData` before scaling job is successful.

### Actual behavior
Just after `ALTER SHARDING TABLE RULE t_order` with sharding-count chagned, `SHOW SHARDING TABLE RULE t_order` return unactive metadata rule.

Refer to https://github.com/apache/shardingsphere/issues/16924#issuecomment-1107684546 for more details.

### Reason analyze (If you can)
I set break point in `ContextManager.init` and `RuleAlteredJob.execute`. Got some screenshots.

When starting proxy:
<img width="1398" alt="WX20220424-110153@2x" src="https://user-images.githubusercontent.com/42492540/164956918-74b3beaf-db3e-4abe-8955-c97c25bee85b.png">

After `ALTER SHARDING TABLE RULE t_order` and `SHOW SHARDING TABLE RULE t_order`:
<img width="1397" alt="WX20220424-111105@2x" src="https://user-images.githubusercontent.com/42492540/164956952-87f87a1c-be9f-43dc-9438-5ce5cc4722f7.png">

`ShardingSphereRuleMetaData` object is not replaced, but `ShardingSphereRuleMetaData.configurations` is changed.
(Verified via `ProxyContext.getInstance().getMetaData("scaling_db2")`)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Refer to https://github.com/apache/shardingsphere/issues/16924#issuecomment-1107684546 for more details.

**Comment by sandynz** [comment]
Hi @zjcnb , could you help to have a look at this issue?

**Comment by zjcnb** [comment]
> Hi @zjcnb , could you help to have a look at this issue?

OK, i will check it.
