### ISSUE TITLE
The id generated by the built-in snowflake id generator of shardingsphere is duplicated, and the length is not 64 bits.

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#17055]
Hello, The shardingsphere version I am using is 5.0.0，the following is my code and result data, please look at the reason：
**Test code:**
object SnowFlakeUtils {
    fun  getId(workerId: String): Long {
        val keyGenerator = SnowflakeKeyGenerateAlgorithm()
        val properties = Properties()
        properties.setProperty("worker-id", workerId)
        keyGenerator.props = properties
        keyGenerator.init()
        return keyGenerator.generateKey().toString().toLong()
    }
}
        for (i in 1..100) {
            println(SnowFlakeUtils.getId("1"))
        }

**The resulting data is:**
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630224842752
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630229037056
725026630233231360

**Comment by carlyin0801** [comment]
Hi @zjcnb , could you help to have a look at this issue?

**Comment by zjcnb** [comment]
> Hi @zjcnb , could you help to have a look at this issue?

Sure, i will check.

**Comment by zjcnb** [comment]
> Hi @zjcnb , could you help to have a look at this issue?

Sure, i will check.

**Comment by TeslaCN** [comment]
Hi @carlyin0801 
I noticed that your code creates instance of `SnowflakeKeyGenerateAlgorithm` every time in loop. Consider using the same instance of `SnowflakeKeyGenerateAlgorithm`.

**Comment by carlyin0801** [comment]
ok，thanks
