### ISSUE TITLE
Cannot persist to Zookeeper when there is no table under PostgreSQL schema

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17061]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/0f0ddf8ffcc1fa9b85f7065d6bf4c72ab13c90fe

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Can persist schema to Zookeeper when there is no table under this schema

### Actual behavior

Create two new schemas, but can not persist to Zookeeper.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/10829171/164973066-c02c9595-f721-46fd-abc2-0a606390bec7.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/10829171/164973094-1eaffa26-6d3c-47ef-8e52-474eea86b260.png">

**Comment by strongduanmu** [comment]
Hi @zjcnb, can you help check this bug?

**Comment by zjcnb** [comment]
> Hi @zjcnb, can you help check this bug?

Yeah, i will fix it.
