### ISSUE TITLE
Querying with the 'select *' syntax reports an error

### ISSUE THREAD

**Issue by wangwangwangBoy** [apache/shardingsphere#17060]
###  ShardingSphere-JDBC

After updating the latest master branch. Using select * reported an error, the master in October last year can be executed normally

![image](https://user-images.githubusercontent.com/46279672/164971487-02671fc1-986d-4f38-b94a-dd432098a6a2.png)

After replacing select *, it can run normally
![image](https://user-images.githubusercontent.com/46279672/164971599-25dc3cd5-9680-423f-b544-e1222c4700a1.png)

**Comment by strongduanmu** [comment]
Hi @wangwangwangBoy, thank you for your feedback. Can you provide the original sql string?

**Comment by wangwangwangBoy** [comment]
select * from (
        select
        distinct
        di.device_id AS deviceId,
        b.id AS projectId,
        bai.project_status,
        ifnull(ds.status,0) AS deviceStatus,
        di.device_name deviceName,b.name projectName,
        date_format(ds.update_time,'%Y-%m-%d %H:%i:%S') updateTime,
        CONCAT(left(e.district_name_path,3),'-',d.name,'-',c.name) parkName
        from
        device_info di left join device_status ds on (di.device_id = ds.device_id  
        and di.project_id = ds.project_id and di.tenant_id = ds.tenant_id and DATE_FORMAT( ds.update_time, '%Y-%m-%d' )
        = CURDATE())
        left join bid_area b on di.project_id = b.id and di.tenant_id = b.tenant_id
        left join bid_area_info bai ON bai.bid_area_id = b.id and bai.tenant_id = b.tenant_id
        left join park c on c.id = b.park_id and c.tenant_id = b.tenant_id
        left join sys_org d on d.id = c.sys_org_id and d.tenant_id = c.tenant_id
        LEFT JOIN sys_tenant e ON e.id = di.tenant_id
        WHERE
        b.is_enable =1
        ORDER BY c.name,b.name ) tmp where (tmp.project_status != 7 OR tmp.project_status IS NULL)

**Comment by wangwangwangBoy** [comment]
> Hi @wangwangwangBoy, thank you for your feedback. Can you provide the original sql string?

thank you for your feedback. The last reply is our original sql

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, and ShardingSphere has released several new versions, so I will close it.
Please try the latest version, and if the problem reproduces, please reopen it or submit a new one.
