### ISSUE TITLE
big andPredicates collections where parse sql

### ISSUE THREAD

**Issue by fbin87** [apache/shardingsphere#17068]
when use sql with more where conditions in shardingsphere 4.1.1

I found big collections in PredicateBuilder.mergePredicate()
![image](https://user-images.githubusercontent.com/42720240/164981853-875b5a48-229b-4f20-bbcc-6fbda622f22f.png)

then SelectStatementContext.getAllTablesFromWhere() will take a lot of time to traverse AndPredicate object

the sql is:
static String SQL1 = "select * from model where id = 'a' and (name = 'a' or name ='b' or name ='b' or name ='b' or name ='b' or name ='b' or name ='b' or name ='b' or name ='b' or name ='b') and (age in (4,5,6,7,8) or height = '2' and (weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2)) and (age in (4,5,6,7,8) or height = '2' and (weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2)) and (age in (4,5,6,7,8) or height = '2' and (weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2 or weight = 2))";

**Comment by fbin87** [comment]
SelectStatementContext.getAllTablesFromWhere()  traverse big AndPredicate object collections
![image](https://user-images.githubusercontent.com/42720240/164982052-bd8697b8-93b1-403e-97fc-f4243821929c.png)

**Comment by strongduanmu** [comment]
Hi @fbin87, thank you for your feedback. Can you try the latest 5.1.1 version? Version 4.1.1 is too old.

**Comment by RaigorJiang** [comment]
@fbin87 
`andPredicates` has been removed in https://github.com/apache/shardingsphere/pull/7353.

**Comment by tangyiming** [comment]
it's still too big to accept.
<img width="1379" alt="image" src="https://github.com/apache/shardingsphere/assets/18328731/50b68078-0cb0-445a-bf3d-39c1c12d4c8a">

**Comment by strongduanmu** [comment]
Hi @tangyiming, Thank you for your latest feedback. Could you please submit a new issue? I will follow up on this issue.

**Comment by strongduanmu** [comment]
And you can test the latest 5.4.1 version.
