### ISSUE TITLE
During scaling, the index in the statement generating the table exceeds the length limit.

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#17073]
## Bug Report
<img width="2551" alt="image" src="https://user-images.githubusercontent.com/22064617/164973772-8089c928-3147-4b54-a0d4-5d2ff5571151.png">

**Comment by sandynz** [comment]
The create table SQL is generated and rewritten by kernel.

**Comment by VeejaLiu** [comment]
@sandynz I think we should deal with such corner cases, I think this is a bug.

**Comment by sandynz** [comment]
Hi @strongduanmu , could you help to have a look at this issue?

**Comment by strongduanmu** [comment]
@sandynz Thank you for your remind. @VeejaLiu This is not a bug, the logical index will add the actual table suffix in ShardingSphere. I think you should adjust the length of the logic logical index to avoid the actual index being too long.

**Comment by VeejaLiu** [comment]
@strongduanmu 
Thank you for your reply.
But I don't agree with you. In the production environment, it's normal to have a long table name or index name.
Even because of some historical factors, this bad design may already exist in the user's system. But we can't blame our users for this. I think as middleware developers, we should achieve maximum compatibility and non-invasive. We should predict this situation in advance and take corresponding actions, rather than let users modify their design (even bad design).
Finally, thank you for your reply.

**Comment by strongduanmu** [comment]
@VeejaLiu Of course, I agree that ShardingSphere should be as compatible with native databases as possible, but ShardingSphere needs to consider different databases, and indexes with the same name are not allowed in PostgreSQL databases, which is the reason for index rewriting. 

If you are interested, you can try to sort out the index requirements of different databases, and then optimize the logic of existing index rewriting.

**Comment by VeejaLiu** [comment]
@strongduanmu 
Thank you!
It explains the matter
I've only used MySQL and haven't thought about other databases.
This is really a thorny problem.
Thank you for your reply.

**Comment by terrymanu** [comment]
Is the problem resolved?

**Comment by ayundi123** [comment]
最终这个问题不解决了吗？

**Comment by VeejaLiu** [comment]
hhhh, still in status: volunteer wanted

**Comment by ayundi123** [comment]
![image](https://github.com/apache/shardingsphere/assets/138763913/ccdad93b-fb7a-479b-8b63-d8edfb4ad02e)
![1708591760943](https://github.com/apache/shardingsphere/assets/138763913/2109fc25-e93f-4a8d-bc95-b680bdcc6392)
mysql索引超长的问题可以通过修改这行代码解决。
