### ISSUE TITLE
Can I read the file in the init() method of the custom algorithm class?

### ISSUE THREAD

**Issue by VeejaLiu** [apache/shardingsphere#17087]
## Question
I'm using Proxy.
Can I read the file in the init() method of the custom algorithm class?
Where should I put the file in the proxy?
How should I read it? Could you give me an example?

**Comment by TeslaCN** [comment]
If you are doing your custom algorithm, you may do anything you want in the `init()` including reading a file. There are many ways to do that, such as packing the file into your custom algorithm jar and read it by `YourClass.class.getResource()`.

**Comment by VeejaLiu** [comment]
@TeslaCN Thank you, mate.
This is exciting news. This will help me solve many problems.
