### ISSUE TITLE
There is a problem parsing union SQL for same table

### ISSUE THREAD

**Issue by Gordonman** [apache/shardingsphere#17117]
**ShardingSphere version:**  4.0.0-RC2

**project:**  ShardingSphere-JDBC

**Test case:**
tableName:  coupon_detail
sharding-column:  mer_code
precise-algorithm:   Modulo Operation for mer_code.   ex:  mer_code=123456  , actual-data-node= 123456 % 10 = 6  

Origin sql: 
```
SELECT *  FROM coupon_detail  WHERE  mer_code = '123456' AND user_card ='AAA' 
UNION
SELECT *  FROM coupon_detail  WHERE mer_code = '123456' AND user_id =12345678
```

Expected behavior:
```
SELECT *  FROM coupon_detail_6  WHERE  mer_code = '123456' AND user_card ='AAA' 
UNION
SELECT *  FROM coupon_detail_6  WHERE mer_code = '123456' AND user_id =12345678
```

Actual behavior
```
SELECT *  FROM coupon_detail_6  WHERE  mer_code = '123456' AND user_card ='AAA' 
UNION
SELECT *  FROM coupon_detail  WHERE mer_code = '123456' AND user_id =12345678
```

**The second table name is not rewrite.**

 
**Reason analyze:**
I tracked the source code and found SQLParseEngine only parse first table segment , So  SQLRewriteEngine only rewrite first table name.

**Comment by strongduanmu** [comment]
Hi @Gordonman, can you try the latest version? 4.0.0 is too old.

**Comment by Gordonman** [comment]
> 

Which version supports this feature？

**Comment by strongduanmu** [comment]
> > 
> 
> Hi @strongduanmu Which version supports this feature？

You can try 5.1.1, for more detailed info, refer to this doc——https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/sql/#sql-%E7%A4%BA%E4%BE%8B.
