### ISSUE TITLE
Distributed transaction cannot be rolled back normally

### ISSUE THREAD

**Issue by newchendb** [apache/shardingsphere#17139]
Shardingsphere-JDBC version is 5.1.1 
Seata version is 1.4.2 
Here is a simple demo. Can you help me see why distributed transactions are invalid? Is the configuration missing or wrong?

https://github.com/newchendb/shardingjdbc-seata-test

The order application requests the commodity application. When the order application actively reports an error, the commodity application does not trigger transaction rollback or report any error.

**Comment by jingshanglu** [comment]
`@ShardingSphereTransactionType(TransactionType.BASE)` only guarantees the transaction semantics of the connection obtained
 through `shardingsphere`. If you want to realize cross service transaction semantics, you may need to understand the usage of `@Globaltransaction`
