### ISSUE TITLE
There was a problem upgrading the version 4.1.1 ~5.x

### ISSUE THREAD

**Issue by asdxiaoqex** [apache/shardingsphere#17146]
![image](https://user-images.githubusercontent.com/50010140/165469522-bc0129e1-028a-494b-87f8-bcf181ac099b.png)

In the old version 4.x, I got the split table rule through datasource, and then modified it with reflection to achieve dynamic capacity expansion.

In the new version5.x, I can't find a place to get the sharingrule. I hope you can prompt where you can reference.
![image](https://user-images.githubusercontent.com/50010140/165470119-a830ad55-71b0-4ef3-bad2-bbadb1b9c293.png)

Or there are other APIs that can provide better dynamic capacity expansion table rules. Please give me some guidance.

**Comment by TeslaCN** [comment]
Hi @asdxiaoqex 
You may try `getRuleMetaData().findRule(ShardingRule.class)`.

https://github.com/apache/shardingsphere/blob/dab914a6edac43f82a60be00280aa6597d5bda74/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/rule/ShardingSphereRuleMetaData.java#L94-L97

**Comment by asdxiaoqex** [comment]
> Hi @asdxiaoqex You may try `getRuleMetaData().findRule(ShardingRule.class)`.
> 
> https://github.com/apache/shardingsphere/blob/dab914a6edac43f82a60be00280aa6597d5bda74/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/metadata/rule/ShardingSphereRuleMetaData.java#L94-L97

is empty

**Comment by asdxiaoqex** [comment]
我是想获取到 表路由的配置 然后修改他

**Comment by asdxiaoqex** [comment]
因为我现在是把一些由日期动态创建的路由 也加载进去 因为每天都会 新增新的路由表 旧版本可以通过上面那个shardingRule反射去改，新版 没找到

**Comment by RaigorJiang** [comment]
@asdxiaoqex  I think you can refer to #16725, and a better way is to execute DistSQL through Proxy for maintenance.
