### ISSUE TITLE
[Discussion] Refactoring EncryptColumnRuleConfiguration and related to set encryptorName by column

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#17152]
Now 1 logicColumn 1 encryptorName, only one encryptorName could be specified, but there are cipherColumn and assistedQueryColumn and maybe other desensitization column would be added by requirements.

I supposed to refactor as below, and what's your suggestion?  related: #13508

![image](https://user-images.githubusercontent.com/25882819/165507029-bb4b1162-db67-43a5-9908-733e0e2effbf.png)

**Comment by terrymanu** [comment]
I just set it as invalid because of the author close the issue without any reason.
