### ISSUE TITLE
About shadow db routing extension support richer ways

### ISSUE THREAD

**Issue by bushuaigege** [apache/shardingsphere#17168]
ok
It has been confirmed that the answer cannot be obtained through google search and github issue;

Requirement: switch the shadow route after obtaining the tag through the request header, and the master-slave db is currently used

for example: all sql operations entered through the A URL are executed in the shadow db;

At present, the implementation method is considered: implement ShadowAlgorithm, whether there is already a similar case

**Comment by soulasuna** [comment]
@bushuaigege 
There is currently no relevant implementation case.
Is it convenient to describe the usage scenarios and specific implementation requirements?

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
