### ISSUE TITLE
Create database xxx not effict when using Proxy

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#17173]
## Bug Report

master 16d9ef687c2fb4c0669a4af9ce62f14395bae7e9

ShardingSphere-Proxy

when i using direct connection to database, 

```
public class BootTest {
    
    public static void main(String[] args) throws SQLException {
        val connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "postgres");
        connection.createStatement().execute("create database test_db3");
    }
}
```
the result is success
<img width="442" alt="image" src="https://user-images.githubusercontent.com/101622833/165694680-1f7f550a-5a82-4986-88fa-c32ef2bd9add.png">

but using ss-proxy, when i execute the following code

```
public class BootTest {
    
    public static void main(String[] args) throws SQLException {
        val connection = DriverManager.getConnection("jdbc:postgresql://localhost:3307/postgres", "root", "root");
        connection.createStatement().execute("create database proxy_db");
    }
}
```

the console output is 
```
[INFO ] 2022-04-28 14:58:20.678 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: create database proxy_db
[INFO ] 2022-04-28 14:58:20.680 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: PostgreSQLCreateDatabaseStatement()
```

but the zk data seems not create database succeed;

<img width="630" alt="image" src="https://user-images.githubusercontent.com/101622833/165695501-604027a6-2f1e-4769-aa26-fc1672a4ae4a.png">

I can repeatedly execute the above steps, no exception will be reported. This should be throw similar exception just like `database xxx already exists` 

I find the diffent handle at CommandExecutorTask

when i execute using  jdbc connection 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/101622833/165698677-6dc5b951-ac73-4a88-a6cb-507413d6726e.png">

if i using psql console, create database succced, 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/101622833/165699353-5cce12e0-70de-4f9e-8426-1c056f033f22.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/101622833/165700477-57a6dac5-6c59-4011-bfc3-4f5979895af2.png">

but the type is  `SIMPLE_QUERY` 
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/101622833/165699269-ac6ab1e5-f1d6-45db-bc4e-11fc3df04593.png">

**Comment by sandynz** [comment]
Hi @TeslaCN , could you help to have a look at this issue?

**Comment by TeslaCN** [comment]
I will check this.
You may add `preferQueryMode=extendedForPrepared` to JDBC url as a temporary solution.
