### ISSUE TITLE
encrypt config  queryWithCipherColumn is  support column levels？

### ISSUE THREAD

**Issue by zhaoguhong** [apache/shardingsphere#17196]
## current

```bash
# glable level
spring.shardingsphere.rules.encrypt.queryWithCipherColumn=true
# table level
spring.shardingsphere.rules.encrypt.tables.t_encrypt.queryWithCipherColumn=true
```
## expect

```bash
# glable level
spring.shardingsphere.rules.encrypt.queryWithCipherColumn=true
# table level
spring.shardingsphere.rules.encrypt.tables.t_encrypt.queryWithCipherColumn=true
# column level
spring.shardingsphere.rules.encrypt.tables.t_encrypt.columns.phone.queryWithCipherColumn=true
```

**Comment by cheese8** [comment]
What kind of scene the column level `queryWithCipherColumn`  is needed？It feels just too fine-grained on column level.

**Comment by strongduanmu** [comment]
Hi @zhaoguhong what is your business scenario, and you need to switch between encryption and decryption at the column level?

**Comment by cheese8** [comment]
Your `address` column need to be encrypted too , do it need to be queryed in `where condition`？@zhaoguhong

**Comment by cheese8** [comment]
OK, I got it. I think it should be supported, what do you think? @strongduanmu

**Comment by strongduanmu** [comment]
From this scenario, it is indeed necessary, but this solution will make the encrypt rewrite logic more complicated, and we need to evaluate all possible problems in detail, such as performance and code maintainability.

**Comment by cheese8** [comment]
Assign me please , I am following it.

**Comment by cheese8** [comment]
> > Hi @zhaoguhong what is your business scenario, and you need to switch between encryption and decryption at the column level?
> 
> My table, contains historical data
> 
> ```sql
> create table t_encrypt
> (
>     id           bigint unsigned auto_increment primary key,
>     phone        varchar(100) null,
>     address       varchar(100) null
> );
> ```
> 
> After encryption the phone column
> 
> now `queryWithCipherColumn` is true
> 
> but my boss say address also need to encrypt，What should I do?

As now `queryWithCipherColumn `  effected on global and table level, maybe you can rollback the `phone` column, when the whole table finished encryption, then commit the whole table. @zhaoguhong

**Comment by zhaoguhong** [comment]
> > > Hi @zhaoguhong what is your business scenario, and you need to switch between encryption and decryption at the column level?
> > 
> > 
> > My table, contains historical data
> > ```sql
> > create table t_encrypt
> > (
> >     id           bigint unsigned auto_increment primary key,
> >     phone        varchar(100) null,
> >     address       varchar(100) null
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After encryption the phone column
> > now `queryWithCipherColumn` is true
> > but my boss say address also need to encrypt，What should I do?
> 
> As now `queryWithCipherColumn ` effected on global and table level, maybe you can rollback the `phone` column, when the whole table finished encryption, then commit the whole table. @zhaoguhong

ok，I see
