### ISSUE TITLE
Preparing failure in scaling because getting primary key failed

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#17191]
### Which version of ShardingSphere did you use?
5.1.1 #5b117204
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Scaling task started successfully.

### Actual behavior
The scaling task failed to start because the primary key of the table could not be found, but the table actually has a primary key.

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5668787/165874660-f218a1d9-5d1e-4f9e-86ee-47f5094bab78.png">

### Reason analyze (If you can)
```java
private static final String FETCH_PRIMARY_KEY_TEMPLATE = "SELECT constraint_name,column_name FROM information_schema"
            + ".key_column_usage WHERE table_name = '%s' AND table_schema='public'";
```
Because we only get the table information from the public schema, but the user is currently using another schema.

**Comment by sandynz** [comment]
Customized schema of getting create table for PostgreSQL and openGauss has been supportted in #17379.

**Comment by RaigorJiang** [comment]
Thank you! @sandynz
