### ISSUE TITLE
`UPDATE statement` parsing failed in PostgreSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#17190]
### Which version of ShardingSphere did you use?
5.1.1 release
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
SQL can be parsed correctly for update statement in PG.

### Actual behavior
SQL parsing failed:
```sql
update t_order t set t.name = 'x', t.age = 10 where t.id = 5;
```
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/5668787/165874209-969702bb-456e-44f8-80f1-aa5e5bc35865.png">

**Comment by tuichenchuxin** [comment]
I'll check it.

**Comment by tuichenchuxin** [comment]
This seems not supported for pg.
https://www.postgresql.org/docs/current/sql-update.html
use this to replace
```
update t_order t set name = 'x', age = 10 where t.id = 5;
```

**Comment by RaigorJiang** [comment]
@tuichenchuxin 
OK, thank you, so I can close it now.
