### ISSUE TITLE
MySQL create database succeed, but can't use it at JDBC

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#17203]
### Which version of ShardingSphere did you use?

master 3d08a8d176d494239c575b84535d30408cc6b456

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

If create database succeed, can be used right now.

### Actual behavior

I was using ShardingSphere-Proxy with MySQL, only use server.yaml, not use config-sharding.yaml

Firstly, I create database sharding_db;
```
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3307/?serverTimezone=UTC&useLocalSessionState=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false&useServerPrepStmts=true"), "root", "root")) {
            connection.createStatement().execute("CREATE DATABASE sharding_db");
        }
```

Then I want to create new Connection and use `sharding_db` just created just now, but the exception will thrown.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/101622833/165897838-2e985c9c-af9b-4a8b-8329-123f431dcb66.png">

Only MySQL has the problem, PostgreSQL I tested, it's ok. And after i execute `ADD RESOURCE xxx`, the problem will not appear.

**Comment by RaigorJiang** [comment]
Hi @azexcy 
Thanks for your feedback.
@lanchengx  could you help investigate?

**Comment by lanchengx** [comment]
@azexcy @RaigorJiang Thanks, I will check

**Comment by lanchengx** [comment]
Hi @azexcy, you can try to use the latest code from master, it works.
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/52209337/167583507-816b0f3c-cd25-4511-a3aa-a11a323b6b1b.png">

**Comment by azexcy** [comment]
Ok, I will try later, Thanks
