### ISSUE TITLE
官网中关于ShardingSphere-JDBC配置项说明文档的错误

### ISSUE THREAD

**Issue by suncl001** [apache/shardingsphere#17260]
版本：5.1.1
问题文档地址：https://shardingsphere.apache.org/document/5.1.1/cn/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/sharding/
说明：
在spring-boot-starter配置规则“数据分片”的配置文档中，关于"用于单分片键的标准分片场景"的配置项文档说明为：
`spring.shardingsphere.rules.sharding.tables.<table-name>.database-strategy.standard.sharding-column=`
实际应该为：
`spring.shardingsphere.rules.sharding.tables.<table-name>.table-strategy.standard.sharding-column=`
其他关于分片的配置项说明可能也存在此问题。
以下为截图：
![b47006efcc2f49c6de1b7342108a52d](https://user-images.githubusercontent.com/52554846/166159785-bb261e32-e00a-41c2-a764-4944da2c46cc.png)

**Comment by strongduanmu** [comment]
Hi @suncl001, thank you for your feedback. Can you translate this issue to english? In addition, ShardingSphere supports both database-strategy and table-strategy configurations, which represent sharding and table sharding strategies, respectively.
