### ISSUE TITLE
Why the second variable of Actual SQL(simple) is not the actual tabel name?

### ISSUE THREAD

**Issue by ryanxci** [apache/shardingsphere#17285]
Why the second variable of Actual SQL(simple) is not the actual tabel name?

log("Actual SQL(simple): {} ::: {}", dataSourceNames, executionUnits.size());

Is tableRouteMapper.getActualName() more appropriate here?

**Comment by RaigorJiang** [comment]
Hi @ryanxci 
Thanks for your feedback.
According to your suggestion, I checked the `SQLLogger`:
When the `SELECT` routing results of multiple tables are on the same data source, `Actual SQL` is a UNION ALL statement containing multiple tables, but at this time `tableRouteMappers` only contains one object, and its `actualName` does not reflect the actual query table name.
So I recommend keeping it as it is.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
