### ISSUE TITLE
spring-data-jdbc error is supported for version 5.1.1

### ISSUE THREAD

**Issue by deploymentadmin** [apache/shardingsphere#17296]
a bean of type 'org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations' that could not be found.
but 4.0.0 version  is ok

**Comment by linghengqian** [comment]
Try updating your `org.springframework.boot:spring-boot-starter-parent` version to 2.6.7. This class belongs to the Spring Framework and still exists in the Master branch. See https://github.com/spring-projects/ spring-framework/blob/4fc359f75ec58ed9477ace0cbc6129ce752f1c63/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterJdbcOperations.java .

**Comment by deploymentadmin** [comment]
![image](https://user-images.githubusercontent.com/97282143/166850411-b1089acd-5470-46f9-a452-8f955834693d.png)
that is Spring cannot initialize the data source， spring.datasource config is ok.   Is there an example for spring-data-JDBC？

**Comment by linghengqian** [comment]
@deploymentadmin Normally not, because as far as I know Spring Data JDBC is usually used to integrate into the Mapper layer of Mybatis, I don't see any problems in this area. I think you can provide a minimal example of a recurring problem. (Looks like you did some extra configuration on Spring.)
