### ISSUE TITLE
WeightReplicaLoadBalanceAlgorithm can not be used by multiple load balance rules

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17313]
The static field `WEIGHT_MAP` is class level which effected each other for different load balance rules.

Please use object level attribute on this algorithm.

**Comment by terrymanu** [comment]
Hi, @cherubimLV 

This feature comes from #13933, could you fix it?

**Comment by cherubimLV** [comment]
ok.give it to me

**Comment by TeslaCN** [comment]
Hi @cherubimLV 
Any update here?

**Comment by TeslaCN** [comment]
I'm moving this to next milestone.
