### ISSUE TITLE
Timed out after starting project for Sharding

### ISSUE THREAD

**Issue by q3056917665** [apache/shardingsphere#17335]
### Which version of ShardingSphere did you use?
sharding-jdbc V4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
The project is successfully started.

### Actual behavior
On 5.7.36 of the MySQL version and the number of tables is 2133 the timeout. but not on 5.6.51 of the MySQL version,The same quantity.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sharding rule configuration

### Example codes for reproduce this issue (such as a github link).
It has nothing to do with code

**Comment by TeslaCN** [comment]
Hi @q3056917665 
The ShardingSphere-JDBC 4.x is no longer maintained. Could you try the 5.1.1? We have done many enhancements about loading metadata.

**Comment by q3056917665** [comment]
> Hi @q3056917665 The ShardingSphere-JDBC 4.x is no longer maintained. Could you try the 5.1.1? We have done many enhancements about loading metadata.

ok, let's try it

**Comment by terrymanu** [comment]
@q3056917665 Hi, any update?

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
