### ISSUE TITLE
Whether shardingsphere JDBC supports dynamic SQL under the same database instance and different schemas

### ISSUE THREAD

**Issue by deploymentadmin** [apache/shardingsphere#17332]
Whether shardingsphere JDBC supports dynamic SQL under the same database instance and different schemas, for example: "insert into ds_0. user (city, name) values ('a ',' b ')";
that error org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'ds_0' doesn't exist.

I use shardingsphere JDBC for sharding database，shardingsphere.datasource is config  database instance,i hope that sql to support  databasename.tablename  .
 thanks

**Comment by RaigorJiang** [comment]
Hi @deploymentadmin 
ShardingSphere supports the format of `database.table`,  like:
```sql
DELETE FROM sharding_db.t_account WHERE status = 'OK'
```
But the database should be the logic database in ShardingSphere, not a resource.
