### ISSUE TITLE
应该如何知道配置的分布式事务-XA事务已经生效了？

### ISSUE THREAD

**Issue by luojianjianjun** [apache/shardingsphere#17355]
## 如何知道配置的分布式事务-XA事务已经生效了？

采用的版本是 5.0.0
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-transaction-xa-core</artifactId>
            <version>5.0.0</version>
        </dependency>

在方法上使用了注解
    @Override
    @Transactional
    @ShardingSphereTransactionType(TransactionType.XA)
    public int insertSelectiveXA() {
        for(int i = 0;i<5;i++){
            Order order = new Order();
            String subName = UUID.randomUUID().toString();
            order.setOrderName(subName);
            orderMapper.insertSelective(order);
        }
        return 0;
    }
但是我无法确保分布式事务-XA事务生效了，因为我没有在日志中找到XA事务的相关信息，比如说开启XA事务的输出提示，但是我在项目路径下的/logs/找到了两个文件，xa_tx.lck 和xa_tx24.log，请问我如何才能知道XA事务开启且生效了？

**Comment by Crackersssss** [comment]
Or try with XA transaction statement.

**Comment by RaigorJiang** [comment]
Hi @luojianjianjun 
For English only, please translate this issue, thank you.
