### ISSUE TITLE
[WeOpen-Star] Add more unit test for FederationDatabaseMetaData

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17375]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

We need to add more unit test for FederationDatabaseMetaData.

- [ ] FederationDatabaseMetaData#putSchemaMetadata
- [ ] FederationDatabaseMetaData#putTableMetadata
- [ ] FederationDatabaseMetaData#removeSchemaMetadata
- [ ] FederationDatabaseMetaData#removeTableMetadata
- [ ] FederationDatabaseMetaData#getSchemaMetadata

**Comment by aoyvx** [comment]
Assign me, please.

**Comment by aoyvx** [comment]
@strongduanmu hi,I was testing the getSchemaMetadata method when I raised a `NullPointerException`.Do you think you should use `Optional.ofNullable()` as the return value

**Comment by aoyvx** [comment]
@strongduanmu Hello, what should I do.

**Comment by strongduanmu** [comment]
> getSchemaMetadata

@aoyvx Can you show your test code?

**Comment by aoyvx** [comment]
> @aoyvx Can you show your test code?

@strongduanmu The following test case can pass, but I'm not sure if it meets the expectations. Complete code in https://github.com/apache/shardingsphere/compare/master...aoyvx:features/FederationDatabaseMetaDataTest.
```
    @Test(expected = NullPointerException.class)
    public void assertGetSchemaMetadataByNonexistentKey() {
        final ShardingSphereSchema sphereSchema = mock(ShardingSphereSchema.class);
        final Map<String, ShardingSphereSchema> map = Maps.of("foo_db", sphereSchema);
        final FederationDatabaseMetaData federationDatabaseMetaData = new FederationDatabaseMetaData("foo", map);
        federationDatabaseMetaData.getSchemaMetadata("foo_db_2");
    }
```

**Comment by terrymanu** [comment]
What is the stack trace？
