### ISSUE TITLE
A simple select error about sharding-proxy  

### ISSUE THREAD

**Issue by jiangce111** [apache/shardingsphere#17373]
### This table has no sharding,table structure:
```
CREATE TABLE `rpt_tplusecfg_test` (
  `id` int(11) NOT NULL ,
  `tplusecfgid` int(11) NOT NULL ,
  `userid` char(32) NOT NULL ,
  `attr` char(40) NOT NULL ,
  `attrname` varchar(256) NOT NULL ,
  `rank` int(11) NOT NULL DEFAULT '10' ,
  `formulaflag` tinyint(1) NOT NULL DEFAULT '0',
  `formula` text ,
  `unit` char(40) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3205 DEFAULT CHARSET=utf8;
```

 When I run a select statement, the following error occurs:
 ```
mysql> select id, tplusecfgid, userid, attr, attrname, rank, formulaflag, unit from rpt_tplusecfg_test  where  tplusecfgid=52;
ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
 ```
 When you use SELECT * or select another column, the results will work ,After several tests, the query results are normal after removing the TANK column 
 
 ```
mysql> select id, tplusecfgid, userid, attr, attrname,  formulaflag, unit from rpt_tplusecfg_test  where  tplusecfgid=52;
Empty set (0.01 sec)

 ```

The version I used before was 5.1.0, and the result was still abnormal after I updated it to 5.1.1

**Comment by strongduanmu** [comment]
Hi @jiangce111, thank you for your feedback. Can you use quotes around rank? Just like 'rank'. According to issue #14224, the rank keyword is no longer supported in MySQL 8.0, so it is better not to name the field rank.

**Comment by jiangce111** [comment]
Sorry for not finding relevant errors before, thank you for your answers, THE MySQL version I use is 5.7.33, and the connector version is mysql-connector-Java-5.1.49  ,when i use  quotes around rank the result is normal.
