### ISSUE TITLE
gsql could not login to Proxy with default postgres database

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17409]
### Which version of ShardingSphere did you use?
master branch, commit d7a8079e5141474e47e4aaa42221feda32047964

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior
gsql could login to Proxy with postgres.

### Actual behavior
Client log:
```
omm@b74ff82d07b4:~$ gsql --host=host.docker.internal --port=3307 postgres root
Password for user root:
Failed to get the server's version. resStatus=7
ERROR: ERROR:  org.apache.shardingsphere.proxy.backend.exception.RuleNotExistedException
```
No log in Proxy.

### Reason analyze (If you can)
`postgres` exists in registry center `/metadata/postgres/`, though content is empty.

The error occur when executing `SELECT VERSION()`.
<img width="1377" alt="图片" src="https://user-images.githubusercontent.com/42492540/167236466-614d25dd-7d87-4f09-bad1-59c58bc53831.png">

Similar situation works on PostgreSQL backend.
```
% psql --host=localhost --port=3307 postgres root
Password for user root:
psql (13.4, server 12.3-ShardingSphere-Proxy 5.1.2-SNAPSHOT-371f15e)
Type "help" for help.
```
Seems after authentication, there's no more query SQL with psql.

No sure what's wrong with gsql.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1, Install MogDB v2.1, refer to  https://docs.mogdb.io/zh/mogdb/v2.1/docker-installation . Or try openGauss

2, Update `server.yaml`:
Add
```
  proxy-frontend-database-protocol-type: openGauss
```
in `props`.

3, Start Proxy.

4, Login with gsql
```
docker exec -it mogdb bash

su - omm

gsql --host=host.docker.internal --port=3307 postgres root
```

**Comment by sandynz** [comment]
Hi @TeslaCN , could you help to have a look at this issue?

**Comment by TeslaCN** [comment]
`gsql` would query `pg_settings` when establishing connection.
![image](https://user-images.githubusercontent.com/20503072/167239981-a61728c7-4712-43bc-933c-a5f1ef7945fe.png)
![image](https://user-images.githubusercontent.com/20503072/167240004-72cf4ca4-3cb2-4bfb-922e-5e8b17119a88.png)
![image](https://user-images.githubusercontent.com/20503072/167240009-a266081a-76ab-4481-8682-ff3fea42d6cf.png)
![image](https://user-images.githubusercontent.com/20503072/167240015-b2b0a5eb-a9d9-4523-9350-eebd0328333a.png)

**Comment by TeslaCN** [comment]
Temporary solution is adding a logic database to ShardingSphere-Proxy.

**Comment by jingshanglu** [comment]
@TeslaCN this sql will be execute too, and have error
```
SELECT intervaltonum(gs_password_deadline()) 
```

**Comment by TeslaCN** [comment]
The following SQL is sent by gsql 2.1.0:
```sql
SELECT gs_password_notifytime()
```
