### ISSUE TITLE
Does it support mysql batch update?

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#17418]
Does it support mysql batch update? use mybatis

**Comment by TeslaCN** [comment]
You may use the method `addBatch()` of `PreparedStatement`.

**Comment by marker-wu** [comment]
> You may use the method `addBatch()` of `PreparedStatement`.
![image](https://user-images.githubusercontent.com/45256940/167368537-3c3c0462-bbac-4d1c-b3b1-d5072f1ea432.png)
use this way ,it worked！
