### ISSUE TITLE
error  Insert statement does not support sharding table routing to multiple data nodes.

### ISSUE THREAD

**Issue by deploymentadmin** [apache/shardingsphere#17415]
![image](https://user-images.githubusercontent.com/97282143/167244006-2d5c7c8a-c6fa-46f3-adff-7a5ec6f5d243.png)

execute  sql ="insert into user(city,name,code) values('a','b',1)";  error  Insert statement does not support sharding table routing to multiple data nodes.   version for 5.1.1
try again,it‘s key-generate not work ,  why key generate is not work?

**Comment by terrymanu** [comment]
I just set it as invalid because of the author close the issue without any reason.
