### ISSUE TITLE
Page failure occurs when PageHelper pages are used and there is a Group by in SQSL statements

### ISSUE THREAD

**Issue by MfkOTT** [apache/shardingsphere#17410]
## Bug Report
version:4.1.1
Page failure occurs when PageHelper pages are used and there is a Group by in SQSL statements

   SELECT
           SUM(xx) 
        FROM
            xx
        WHERE
        and statistics_time <![CDATA[ <= ]]> #{endTime} and statistics_time <![CDATA[ >= ]]> #{startTime}
        GROUP BY
        xx
when i delete "GROUP BY" then sharding can work ,or i didn't use pagehelper but "limit", the sharding can work too.
so i guess it was because of pagehepler

**Comment by TeslaCN** [comment]
The version 4.1.1 is no longer maintained. Could you try the ShardingSphere 5.1.1?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
