### ISSUE TITLE
Plan to refactor DistSQL's RAL syntax

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#17423]
**Aim**
Move the grammar related to global rules in the RAL grammar to the corresponding global rules module.

Reference feature module

<img width="376" alt="image" src="https://user-images.githubusercontent.com/52209337/167248009-e0ca2d2b-d1c7-4141-aa47-18ba9cf4d739.png">

**Comment by TeslaCN** [comment]
Hi @lanchengx 
Any update here?

**Comment by yx9o** [comment]
@RaigorJiang Hi, I would like to be involved in this work.

**Comment by RaigorJiang** [comment]
@yx9o 
Thank you, let me explain, this task needs to add the corresponding distsql module under global rule, you may need to add new SPI, like `EncryptDistSQLStatementParserFacade`

**Comment by yx9o** [comment]
Ok, I will refer to the feature module above.

**Comment by RaigorJiang** [comment]
@yx9o Completed, thank you!
