### ISSUE TITLE
Add more unit test for SingleTableSQLRouter

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17448]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for SingleTableSQLRouter.

- [ ] SingleTableSQLRouter#decorateRouteContext

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by strongduanmu** [comment]
@runqi-zhao Welcome.
