### ISSUE TITLE
The settle value are not changed with SetVariableExecutorTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17444]
Please find `// FIXME should be 1024, but is 128` comment in class SetVariableExecutorTest.
The settle values does not effective.

**Comment by lanchengx** [comment]
In cluster mode, props will be refreshed through notifications, but in stand-alone mode or in-memory mode, there may be inconsistencies between cache and props data. Fix in https://github.com/apache/shardingsphere/pull/17465
