### ISSUE TITLE
Add unit test for SingleTableRouteEngineFactory

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17447]
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

We need to add more unit test for SingleTableRouteEngineFactory.

- [ ] SingleTableRouteEngineFactory#newInstance

**Comment by misselvexu** [comment]
Please assign this issue to me , thanks ~

**Comment by strongduanmu** [comment]
@misselvexu Welcome.
