### ISSUE TITLE
How to use skywalking monitor sharding-jdbc 5.0?

### ISSUE THREAD

**Issue by yuzhiping95** [apache/shardingsphere#17443]
Question:
I dont know how to use skywalking monitor sharding-jdbc 5.0. 
Can sharding-Jdbc achieve this goal? 
If the middleware supports this feature, could you give me some advice? I cant find any solution of sharding-jdbc.  
Thanks for your support！

**Comment by linghengqian** [comment]
- In fact, ShardingSphere JDBC itself has a corresponding plug-in in Skywalking Java Agent. As long as your application can access its own SkyWalking OAP Server through JavaAgent, you can naturally trace the traces of ShardingSphere through the link. 
- Issues related to Skywalking have little to do with ShardingSphere.
- ![trace-list](https://user-images.githubusercontent.com/20187731/167295170-f0acb7da-9802-45eb-85d1-5f22caa73fc0.png)
- ![image](https://user-images.githubusercontent.com/20187731/167295141-5453c6ca-ad3a-44bf-823c-28061170a5ad.png)
