### ISSUE TITLE
select union subquery NullPointerException

### ISSUE THREAD

**Issue by anonymous-lj** [apache/shardingsphere#17466]
### Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
</dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
`Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.infra.binder.segment.select.subquery.engine.SubqueryTableContextEngine.createSubqueryTableContexts(SubqueryTableContextEngine.java:43)
	at org.apache.shardingsphere.infra.binder.segment.table.TablesContext.createSubqueryTables(TablesContext.java:99)
	at org.apache.shardingsphere.infra.binder.segment.table.TablesContext.<init>(TablesContext.java:86)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementContext.<init>(SelectStatementContext.java:110)
	at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.getDMLStatementContext(SQLStatementContextFactory.java:146)
	at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.newInstance(SQLStatementContextFactory.java:129)
	at org.apache.shardingsphere.infra.binder.SQLStatementContextFactory.newInstance(SQLStatementContextFactory.java:114)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:181)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:149)
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:80)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)`

### Reason analyze (If you can)
Suspected to have something to do with the 5.1.0 update _Support select union/union all ... statements by federation engine_
5.0.0 no problem

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
`SELECT
              af.id,
              af.appid,
              af.uuid,
              af.wallet_id,
              af.currency,
              af.existing_balance,
              af.original_balance,
              af.balance_change,
              af.create_time,
              af.micro_time,
              af.operation_type,
              af.operation_mode
          FROM
              api_flow af
          WHERE
              af.create_time &gt;= #{startTime}
              AND af.create_time &lt; #{endTime}
          UNION
          SELECT
              af.id,
              af.appid,
              af.uuid,
              af.wallet_id,
              af.currency,
              af.existing_balance,
              af.original_balance,
              af.balance_change,
              af.create_time,
              af.micro_time,
              af.operation_type,
              af.operation_mode
          FROM
              ( SELECT DISTINCT wallet_id FROM api_flow WHERE create_time >= #{startTime} AND create_time &lt; #{endTime} ) t
              INNER JOIN api_fund_check_end cf ON t.wallet_id = cf.wallet_id
              INNER JOIN api_flow af ON ( cf.wallet_id = af.wallet_id AND cf.micro_time = af.micro_time)`

**Comment by strongduanmu** [comment]
Hi @anonymous-lj, thank you for your feedback, Can you provide your sharding configuration and create table statement?

**Comment by anonymous-lj** [comment]
@strongduanmu 
config
`spring:
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: fund
      fund:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    rules:
      sharding:
        tables:
          api_flow:
            actual-data-nodes: fund.api_flow_${0..19}
            table-strategy:
              standard:
                sharding-column: uuid
                sharding-algorithm-name: custom-sharding
        sharding-algorithms:
          custom-sharding:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: xxx.CustomSharding`

`public class CustomSharding implements StandardShardingAlgorithm<Comparable<?>> {

    private final static SortedMap<Long, String> sortedMap = new TreeMap<>();

    private static long getFNVHash(String str) {
        final long p = 16777619;
        long hash = 2166136261L;
        long fnvSize = 4294967296L;
        for (int i = 0; i < str.length(); i++) {
            hash = ((hash ^ str.charAt(i)) * p) % fnvSize;
        }
        return hash;
    }

    static {
        String tableName = "api_flow_";
        for (int i = 0; i < 20; i++) {
            String each = tableName + i;
            sortedMap.put(getFNVHash(each), each);
            for (int j = 0; j < 100; j++) {
                sortedMap.put(getFNVHash(each + "_VN_" + j), each);
            }
        }
    }

    @Override
    public void init() {
    }

    @Override
    public String getType() {
        return "custom-sharding";
    }

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Comparable<?>> shardingValue) {
        long abs = getFNVHash(shardingValue.getValue().toString());
        SortedMap<Long, String> subMap = sortedMap.tailMap(abs);
        if (subMap.isEmpty()) {
            long i = sortedMap.firstKey();
            return sortedMap.get(i);
        } else {
            long i = subMap.firstKey();
            return subMap.get(i);
        }
    }

    @Override
    public Collection<String> doSharding(Collection collection, RangeShardingValue rangeShardingValue) {
        return null;
    }
}
`
create table DDL
`CREATE TABLE `api_flow_x` (
  `id` varchar(120) COLLATE utf8_bin NOT NULL,
  `appid` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `uuid` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `operation_type` enum('deposit','withdrawal','rebate','transfer') COLLATE utf8_bin DEFAULT NULL,
  `operation_mode` enum('telegraphic_withdrawal','system_withdrawal') COLLATE utf8_bin DEFAULT NULL,
  `capital_flow` enum('outside_to_wallet','system_to_wallet','wallet_to_outside','mt4_to_wallet','mt4_to_mt4','wallet_to_wallet','wallet_to_mt4') COLLATE utf8_bin DEFAULT NULL,
  `currency` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `original_balance` decimal(20,6) DEFAULT '0.000000',
  `service_charge` decimal(20,6) DEFAULT '0.000000',
  `original_service_charge` decimal(20,6) DEFAULT '0.000000',
  `balance_change` decimal(20,6) DEFAULT '0.000000',
  `existing_balance` decimal(20,6) DEFAULT '0.000000',
  `order_serial` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `remark` text COLLATE utf8_bin,
  `wallet_id` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `wallet_type` enum('commission','transaction') COLLATE utf8_bin DEFAULT 'transaction',
  `create_time` datetime DEFAULT NULL,
  `utype` varchar(120) COLLATE utf8_bin DEFAULT 'client',
  `is_deleted` tinyint(1) DEFAULT '0',
  `sync` tinyint(1) DEFAULT '0',
  `micro_time` bigint(50) DEFAULT NULL,
  `agents` text COLLATE utf8_bin,
  `sales` text COLLATE utf8_bin,
  `channel_code` varchar(120) COLLATE utf8_bin DEFAULT NULL,
  `audit_rate` decimal(25,15) DEFAULT '0.000000000000000',
  `usd_service_charge` decimal(20,6) DEFAULT '0.000000',
  `usd_balance_change` decimal(20,6) DEFAULT '0.000000',
  PRIMARY KEY (`id`),
  KEY `index_operation_type` (`operation_type`) USING BTREE,
  KEY `index_operation_mode` (`operation_mode`) USING BTREE,
  KEY `index_capital_flow` (`capital_flow`) USING BTREE,
  KEY `index_uuid` (`uuid`) USING BTREE,
  KEY `index_appid` (`appid`) USING BTREE,
  KEY `sync` (`sync`) USING BTREE,
  KEY `agent` (`agents`(255)) USING BTREE,
  KEY `sales` (`sales`(255)) USING BTREE,
  KEY `currency` (`currency`) USING BTREE,
  KEY `create_time_index` (`create_time`) USING BTREE,
  KEY `wallet_id_uuid_index` (`wallet_id`,`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `api_fund_check_end` (
  `wallet_id` varchar(120) NOT NULL,
  `micro_time` bigint(11) NOT NULL,
  `is_deleted` tinyint(1) NOT NULL,
  `id` int(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;`

**Comment by strongduanmu** [comment]
Format sql:

```sql
SELECT af.id, af.appid, af.uuid, af.wallet_id, af.currency
	, af.existing_balance, af.original_balance, af.balance_change, af.create_time, af.micro_time
	, af.operation_type, af.operation_mode
FROM api_flow af
WHERE af.create_time >= ""
	AND af.create_time < ""
UNION
SELECT af.id, af.appid, af.uuid, af.wallet_id, af.currency
	, af.existing_balance, af.original_balance, af.balance_change, af.create_time, af.micro_time
	, af.operation_type, af.operation_mode
FROM (
	SELECT DISTINCT wallet_id
	FROM api_flow
	WHERE create_time >= ""
		AND create_time < ""
) t
	INNER JOIN api_fund_check_end cf ON t.wallet_id = cf.wallet_id
	INNER JOIN api_flow af
	ON cf.wallet_id = af.wallet_id
		AND cf.micro_time = af.micro_time
```
