### ISSUE TITLE
Sharding converts the uppercase letters of mysql fields to lowercase letters

### ISSUE THREAD

**Issue by MfkOTT** [apache/shardingsphere#17478]
**version:4.1.1**
![image](https://user-images.githubusercontent.com/14286747/167372515-6c997671-ff0c-4363-9dff-6dbeedb0af27.png)

![image](https://user-images.githubusercontent.com/14286747/167372580-ca73c4e0-8520-4c3c-b3eb-81cef5e9ece6.png)

**Can conversion be disabled**

**Comment by TeslaCN** [comment]
Hi @MfkOTT
Could you try the ShardingSphere 5.1.1? The 4.1.1 is no longer maintained.

**Comment by MfkOTT** [comment]
According to the actual situation of the current project, there are too many compatibility problems after the upgrade, so I can't upgrade the version easily

**Comment by MfkOTT** [comment]
> Hi @MfkOTT Could you try the ShardingSphere 5.1.1? The 4.1.1 is no longer maintained.

According to the actual situation of the current project, there are too many compatibility problems after the upgrade, so I can't upgrade the version easily

**Comment by terrymanu** [comment]
Sorry, the version 4.x is out of service
