### ISSUE TITLE
Does Sharding-jdbc support PostgreSQL “with recursive”

### ISSUE THREAD

**Issue by LuwendiWuyi** [apache/shardingsphere#17507]
When I use PostgreSQL‘s  “with recursive” to implement  recurrence method， the ShardingAlgorithm does not work. So I want to konw 
does Sharding-jdbc support PostgreSQL “with recursive”

**Comment by strongduanmu** [comment]
Hi @LuwendiWuyi, ShardingSphere does not suppot with recursive statement with sharding feature now.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I'm closing it now.
If this problem persists, please reopen it or submit a new one.
