### ISSUE TITLE
[WeOpen-Star] Add unit test for ClusterContextManagerCoordinator.renew(final SchemaDeletedEvent event)

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17519]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

Add unit test for ClusterContextManagerCoordinator.renew(final SchemaDeletedEvent event).

**Comment by lushaorong** [comment]
Assign me, please.

**Comment by terrymanu** [comment]
@lushaorong Hi, there are no progress for long time, I just cancel assign to you and make the issue open to pick up.
