### ISSUE TITLE
[WeOpen-Star] Add unit test for ClusterContextManagerCoordinator.renew(final SchemaAddedEvent event)

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17517]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

Add unit test for ClusterContextManagerCoordinator.renew(final SchemaAddedEvent event).

**Comment by strongduanmu** [comment]
@lushaorong Welcome, assigned.
