### ISSUE TITLE
Start scaling job might fail since tryLock failure after stopping scaling job

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17518]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy, scaling enabled

### Expected behavior
stop scaling and start scaling could be executed repeated, without tryLock failure.

### Actual behavior
Start scaling failed:
```
[INFO ] 2022-05-10 17:02:22.637 [Connection-2-ThreadExecutor] o.a.s.d.p.c.a.i.AbstractPipelineJobAPIImpl - Start disabled pipeline job 0130317c30317c3054317c7363616c696e675f6462
[INFO ] 2022-05-10 17:02:22.647 [Curator-SafeNotifyService-0] o.a.s.d.p.c.e.PipelineJobExecutor - UPDATED job config: /scaling/0130317c30317c3054317c7363616c696e675f6462/config
[INFO ] 2022-05-10 17:02:22.665 [Curator-SafeNotifyService-0] o.a.s.d.p.c.lock.PipelineSimpleLock - tryLock, lockName=scaling_db, timeoutMills=1000, result=false
[INFO ] 2022-05-10 17:02:22.665 [Curator-SafeNotifyService-0] o.a.s.d.p.c.e.PipelineJobExecutor - tryLock failed, databaseName=scaling_db
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Stop scaling {jobId};
2. Start scaling {jobId};

**Comment by sandynz** [comment]
Hi @soulasuna , could you help to have a look at this issue?

**Comment by soulasuna** [comment]
@sandynz Assigne to me
