### ISSUE TITLE
Add test case for SQLRewriteContextDecoratorFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17580]
This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

The steps of add test case  of SPI factories:

1. Create or reuse a SPI fixture, name as `XXXFixture` in test folder and do not forget put them into META-INF/services;
2. Add test case for XXXFactory's `newInstance`, `findInstance`, `getInstance`, `getInstances`, `getAllInstances` and so on;
3.Please reference `ClusterPersistRepositoryFactoryTest` or `ScalingEntryFactoryTest` as samples.

**Comment by misselvexu** [comment]
Please assign this issue to me , thanks ~
