### ISSUE TITLE
Does sharding proxy support SSL? If so, how to configure it?

### ISSUE THREAD

**Issue by xxbcoder** [apache/shardingsphere#17596]
Does sharding proxy support SSL? If so, how to configure it?

**Comment by xxbcoder** [comment]
If MySQL enables SSL, I use sharding proxy. What should be configured on sharding proxy to connect?

**Comment by TeslaCN** [comment]
ShardingSphere-Proxy doesn't support SSL for now. But Proxy connects to MySQL via MySQL JDBC Connector, which means Proxy can use SSL communicate with MySQL Server.

**Comment by xxbcoder** [comment]
Mycat does not support ssl either. It has a setting called "dbDriver", which supports "navicat" or "jdbc". Only "dbDriver=jdbc" supports ssl; but selecting "jdbc" will cause a series of other problems. , It seems that the function of jdbc is not fully realized. So if I want to use ShardingSphere-Proxy to connect to mysql with ssl turned on, is there any configuration like dbDriver that needs to be modified, or directly use useSSL=false in jdbcUrl? Now we want to choose ShardingSphere-Proxy as the database middleware, but we are worried about encountering the same problem.

**Comment by xxbcoder** [comment]
> ShardingSphere-Proxy doesn't support SSL for now. But Proxy connects to MySQL via MySQL JDBC Connector, which means Proxy can use SSL communicate with MySQL Server.

Mycat does not support ssl either. It has a setting called "dbDriver", which supports "navicat" or "jdbc". Only "dbDriver=jdbc" supports ssl; but selecting "jdbc" will cause a series of other problems. , It seems that the function of jdbc is not fully realized. So if I want to use ShardingSphere-Proxy to connect to mysql with ssl turned on, is there any configuration like dbDriver that needs to be modified, or directly use useSSL=false in jdbcUrl? Now we want to choose ShardingSphere-Proxy as the database middleware, but we are worried about encountering the same problem.

**Comment by TeslaCN** [comment]
> Mycat does not support ssl either. It has a setting called "dbDriver", which supports "navicat" or "jdbc". Only "dbDriver=jdbc" supports ssl; but selecting "jdbc" will cause a series of other problems. , It seems that the function of jdbc is not fully realized. So if I want to use ShardingSphere-Proxy to connect to mysql with ssl turned on, is there any configuration like dbDriver that needs to be modified, or directly use useSSL=false in jdbcUrl? Now we want to choose ShardingSphere-Proxy as the database middleware, but we are worried about encountering the same problem.

```
     Client
        |
        | SSL not supported
        V
ShardingSphere-Proxy
        |
        | SSL supported by configuring `useSSL=true` and other options in JDBC URL
        V
      MySQL
```

**Comment by xxbcoder** [comment]
tks

**Comment by vikiuvb** [comment]
@TeslaCN What does it take to support SSL for the frontend channel communications? I'm new to the ShardingSphere project. If you can share some file references, I can try taking a stab at it.

**Comment by TeslaCN** [comment]
> @TeslaCN What does it take to support SSL for the frontend channel communications? I'm new to the ShardingSphere project. If you can share some file references, I can try taking a stab at it.

Here is something about MySQL SSL handshake protocol.
https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html#sect_protocol_connection_phase_initial_handshake_ssl_handshake

Here is the frontend of ShardingSphere-Proxy.

https://github.com/apache/shardingsphere/blob/8f898cc6501afb985dc157b7d9bbe414bdfae247/shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/main/java/org/apache/shardingsphere/proxy/frontend/ShardingSphereProxy.java#L107-L119
