### ISSUE TITLE
worker id of snowflake not work 

### ISSUE THREAD

**Issue by lcxywfe** [apache/shardingsphere#17600]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
snowflake:
  props:
    worker-id: 123

### Actual behavior
worker id not work

**Comment by zjcnb** [comment]
@lcxywfe Hi, The `work-id` are removed in `5.1.1 `version. When you use `ShardingSphere cluster mode`, the `work-id` are automatic generated.

**Comment by lcxywfe** [comment]
@zjcnb Hi, If I have more than 1024 workers, and each worker has local shardingproxy service, Is there any solution to solve the key generator problem?

**Comment by zjcnb** [comment]
> @zjcnb Hi, If I have more than 1024 workers, and each worker has local shardingproxy service, Is there any solution to solve the key generator problem?

Dose you use shardingsphere cluster?

**Comment by TeslaCN** [comment]
> @zjcnb Hi, If I have more than 1024 workers, and each worker has local shardingproxy service, Is there any solution to solve the key generator problem?

You may implement your own key generator and use it by SPI.

**Comment by lcxywfe** [comment]
@zjcnb Not cluster now, so the cluster mode could resolve this problem? Is there any tutorial?

**Comment by zjcnb** [comment]
> @zjcnb Not cluster now, so the cluster mode could resolve this problem? Is there any tutorial?

Yes, `cluster mode` are surpport now.  `memory mode` and `standalone mode` not support now. You also refer to @TeslaCN said. implement `KeyGenerateAlgorithm` interface.

**Comment by lwclover** [comment]
> > @zjcnb Hi, If I have more than 1024 workers, and each worker has local shardingproxy service, Is there any solution to solve the key generator problem?
> 
> You may implement your own key generator and use it by SPI.

Wouldn't it be nice if I could set the length of the workId?

**Comment by lwclover** [comment]
If you don't mind using strings as ids, you can use nanoid.
