### ISSUE TITLE
Add SQL dialect translator module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17619]
The one usage of ShardingSphere is database gateway.
The current ShardingSphere-Proxy can support MySQL protocol to visit PostgreSQL by PostgreSQL dialect, vice versa.
It is time to support SQL translator module to translate the SQL dialect and make the database gateway more powerful. 
Let's make MySQL protocol to visit PostgreSQL by MySQL dialect possible!

The tasks are:

- [x] Add shardingsphere-sql-translator in kernel module
- [x] Support SQL translate interface after SQL rewrite
- [x] Provide SPI to make develop native SQL translator way available
- [x] Use JOOQ as one type of SQL translate engine
- [ ] Provide 2nd level SPI to rewrite SQL dialects by original SQL for native SQL translator

**Comment by Zhoutzzz** [comment]
That sounds interesting, I think the translator module in kernel very challenging about me and I wanna to join implementation it!

**Comment by terrymanu** [comment]
@Zhoutzzz, Welcome, the structure of this module will setup soon, we can talk about the translation details first.

**Comment by arthasking123** [comment]
I would like to participate this issue

**Comment by lyw1129** [comment]
I would like to participate this issue.We are currently experiencing SQL conversion problems with heterogeneous databases.We are currently experiencing SQL conversion problems with heterogeneous databases.

**Comment by lyw1129** [comment]
In some cases, there is no need to modify SQL. How to determine whether to modify SQL before rewriting SQL

**Comment by terrymanu** [comment]
Welcome, @arthasking123 @lyw1129 
The main framework is nearly finished. 
The input param is SQL and parsed SQL statement, any idea to translate them to other dialect? Some option we can consider:

1. Use SQL statement to regenerate the SQL
2. Use SQL token in rewrite module to rewrite the SQL

Which way is better?

**Comment by terrymanu** [comment]
When I add jooq into rewrite module, the exception occur in https://github.com/apache/shardingsphere/runs/6434791822?check_suite_focus=true

But there nothing change by spring and transaction. I want focus the next job of the SQL translation kernel logic, anyone want to investigate it?

You can use this PR (https://github.com/apache/shardingsphere/pull/17656) to reproduce the exception.

```log
ava.lang.NoClassDefFoundError: org/springframework/transaction/PlatformTransactionManager
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:612)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:523)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:509)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:569)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:695)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1496)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1190)
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:773)
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:715)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:118)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at 
```

**Comment by terrymanu** [comment]
@Zhoutzzz @lyw1129 @arthasking123 
NativeSQLTranslator is the basic interface of NativeSQLTranslator. Please have a look and decide the way to translate:

1. Use SQL statement to regenerate the SQL
2. Use SQL token in rewrite module to rewrite the SQL

**Comment by iisheng** [comment]
> When I add JOOQ into rewrite module, the exception thrown in https://github.com/apache/shardingsphere/runs/6434791822?check_suite_focus=true
> 
> There is nothing changed about spring and transaction related. I want focus the next job on the SQL translation kernel logic, does anyone want to investigate it?
> 
> You can reproduce the exception by PR #17656.
> 
> ```
> ava.lang.NoClassDefFoundError: org/springframework/transaction/PlatformTransactionManager
> 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
> 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
> 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:612)
> 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:523)
> 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:509)
> 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:569)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:695)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1496)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:395)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:508)
> 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1190)
> 	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:785)
> 	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:773)
> 	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:760)
> 	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:715)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
> 	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:118)
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
> 	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
> 	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
> 	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
> 	at 
> ```

Hi, I want to have a try, and this is my pull request. 

https://github.com/apache/shardingsphere/pull/17659

**Comment by complone** [comment]
The dialect conversion currently implemented supports built-in jooq,

The principle of jooq to realize dialect conversion is based on DSL context, the request for a database is based on anltr4 rule standard, and the implementation of dialect switching is transferred to L




If we want to realize the native dialect now

Now my thinking is

1. Dialect of PostgreSQL based on anltr4 https://github.com/tshprecher/antlr_psql For example, the parsing logic here



2. The logic of conversion refers to jooq's abstractquery#getsql method



Complete the native SQL translation from Mysql to Postgres in this way

I wonder if this is feasible?

**Comment by terrymanu** [comment]
> The dialect conversion currently implemented supports built-in jooq,
> 
> The principle of jooq to realize dialect conversion is to transfer the request for one database to another database based on anltr4 rules and standards based on DSL context
> 
> If we want to realize the native dialect now
> 
> I have an idea
> 
> 1. Dialect of PostgreSQL based on anltr4 https://github.com/tshprecher/antlr_psql For example, the parsing logic here
> 2. The logic of conversion refers to jooq's abstractquery#getsql method
> 
> Complete the native SQL translation from Mysql to Postgres in this way
> 
> I wonder if this is feasible?

For current situation, use SQL token in rewrite module to rewrite the SQL is better.
For long term roadmap, I prefer use SQL token in rewrite module to rewrite the SQL, but it need to change the whole logic of rewrite module.

**Comment by complone** [comment]
> > 目前实现的方言转换支持内置jooq，
> > jooq实现方言转换的原理是根据基于DSL上下文的anltr4规则和标准，将对一个数据库的请求转移到另一个数据库
> > 如果我们现在想实现本地方言
> > 我有个主意
> > 
> > 1. 基于anltr4的PostgreSQL方言https://github.com/tshprecher/antlr_psql例如这里的解析逻辑
> > 2. 转换的逻辑参考jooq的abstractquery#getsql方法
> > 
> > 这样完成从Mysql到Postgres的原生SQL翻译
> > 我想知道这是否可行？
> 
> 对于目前的情况，使用重写模块中的 SQL 令牌来重写 SQL 更好。 对于长期路线图，我更喜欢在重写模块中使用 SQL 令牌来重写 SQL，但它需要改变重写模块的整个逻辑。

@terrymanu I think we should provide abstract methods about ```ASTBudiler``` in ```AbstractSQLBudiler``` so that subclasses can rewrite the logic of AST traversal. I plan to refer to the grammar parsing layer of presto to construct and traverse [AST ](https://github.com/ prestodb/presto/blob/master/presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java)

**Comment by complone** [comment]
> > @terrymanu I think we should provide abstract methods about `ASTBudiler` in `AbstractSQLBudiler` so that subclasses can rewrite the logic of AST traversal, and build `ASTBuilder` in `RouteSQLBuilder`. I plan to refer to the grammar parsing layer of presto to construct and traverse [AST](https://github.com/prestodb/presto/blob/master/presto-parser/src/main/java/com/facebook/presto/sql/parser/AstBuilder.java)
> 
> It is better to reuse ShardingSphere's ASTNode or SQLStatement

Yes, I submitted a part of the code to the local warehouse, please take a look
https://github.com/complone/shardingsphere/commit/2633a433be362a0cdbef88da7a1df0c7bbfb87e4

**Comment by TeslaCN** [comment]
I'm moving this to next milestone.

**Comment by complone** [comment]
> Hi @complone @terrymanu Could we finish this in 5.1.2?

This version is still familiar with SQL lexical, currently need to complete [issue-17635]*https://github.com/apache/shardingsphere/issues/17635) familiar with SQL syntax parsing and testing process

**Comment by strongduanmu** [comment]
Hi @terrymanu @complone , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
Since the last subtask will take a long time to implement, I will temporarily remove milestone.
