### ISSUE TITLE
sharding_proxy，using the group_concat function, two values are returned

### ISSUE THREAD

**Issue by ArchangelLiang** [apache/shardingsphere#17627]
### sql：
```
SELECT
	group_concat( industry_name) 
FROM
	hunt_industry;
```
### result:
![image](https://user-images.githubusercontent.com/51203465/168220930-f954d670-df6b-429e-84ae-cd0063dd0a76.png)

**Comment by terrymanu** [comment]
Closed because of no feedback for long time
