### ISSUE TITLE
Use Sharding-jdbc to query data by "limit A offset B",  the Tomcat gives a OOM error

### ISSUE THREAD

**Issue by LuwendiWuyi** [apache/shardingsphere#17628]
When I use Sharding-jdbc to query table A's data with 'limit num1 offset num2', the tomcat gives a OOM error.
1.The original sql is:
select ELC_NO, ELC_ID,...,ORG_NO from eqelcmst where ORG_NO in (?,?,?,?,?,?) order by ELC_NO desc limit 9 OFFSET 76323501 
2.The two actual sqls are:
select ELC_NO, ELC_ID,...,ORG_NO from eqelcmst1 where ORG_NO in (?,?,?,?,?,?) order by ELC_NO desc limit 76323510 OFFSET 0
select ELC_NO, ELC_ID,...,ORG_NO from eqelcmst3 where ORG_NO in (?,?,?,?,?,?) order by ELC_NO desc limit 76323510 OFFSET 0
It seems that Sharding query the whole table's data and the OOM happens.
I want to get help to solve this question, Thanks!

**Comment by TeslaCN** [comment]
Hi @LuwendiWuyi Could you consider refactoring your pagination? Doing large offset is not a good practice in sharding scenario. You may refer to https://shardingsphere.apache.org/document/current/en/reference/sharding/rewrite/#pagination-revision

**Comment by terrymanu** [comment]
Can you provide the full stack trace?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time
