### ISSUE TITLE
[WeOpen-Star] Add more unit test for ExpressionExtractUtil

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17678]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

We need to add more unit test for ExpressionExtractUtil.

- [ ] ExpressionExtractUtil#findNotContainsNullLiteralsExpression

**Comment by clbigdata** [comment]
hello ,please sign it for me

**Comment by strongduanmu** [comment]
@clbigdata Welcome.

**Comment by strongduanmu** [comment]
Because we have refactor findNotContainsNullLiteralsExpression method to private method, so I will close this issue.
