### ISSUE TITLE
[WeOpen-Star]  Article Translation 

### ISSUE THREAD

**Issue by QUBOHAO1998** [apache/shardingsphere#17686]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)

We need to translate [DistSQL cluster governance capabilities](https://mp.weixin.qq.com/s/QVT3jRjqO8FaJVYhSDVc5g) to English

**Comment by vishalkumarmahato** [comment]
I wanna contribute to this but need guidance , I'm a  new Comer you guidance will be mean a lot to me .

**Comment by Jacob953** [comment]
Hi, I'd like to try. Please assign this to me, too. ;)

**Comment by Jacob953** [comment]
Hey, @zjcnb @QUBOHAO1998! PTAL
I've done. ;)

**Comment by Jacob953** [comment]
Hey, @zjcnb @QUBOHAO1998! PTAL
I've done. ;)
