### ISSUE TITLE
shadow-raw-jdbc-example org.apache.shardingsphere.example.shadow.raw.jdbc.config.ShadowDefaultAlgorithmConfiguration  defaultShadowAlgorithmName spell mistake

### ISSUE THREAD

**Issue by grapeqin** [apache/shardingsphere#17697]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

when I run org.apache.shardingsphere.example.shadow.raw.jdbc.ShadowRawJavaConfigurationExample example，choose 
`private static ShardingType shardingType = ShardingType.SHADOW_DEFAULT_ALGORITHM;`

### Actual behavior
it shows：
![image](https://user-images.githubusercontent.com/6265178/168533863-d1e82bf8-411a-4c5b-9e2f-065360d4658b.png)

### Reason analyze (If you can)

I found when we set defaultShadowAlgorithmName `simple-note-algorithm` in method of `createShadowRuleConfiguration` (from line #51 in `org.apache.shardingsphere.example.shadow.raw.jdbc.config.ShadowDefaultAlgorithmConfiguration` ) 

but in method of `createShadowAlgorithmConfigurations` we put `simple-hint-algorithm`,so I think who spell mistake.

I try to modify set defaultShadowAlgorithmName `simple-hit-algorithm` in method of `createShadowRuleConfiguration`,then it  works.

**Comment by soulasuna** [comment]
I will fix it. 
Please assign to me.
