### ISSUE TITLE
Helm Chart is 404

### ISSUE THREAD

**Issue by wangyun1517** [apache/shardingsphere#17698]
## Bug Report

When I install the shardingsphere-proxy by helm charts, it get the 404 error.

![Screen Shot 2022-05-16 at 3 01 04 PM](https://user-images.githubusercontent.com/9639483/168536855-90152bf0-8497-4202-a74d-05ec7e5e7076.png)

how can I fix this error?

**Comment by windghoul** [comment]
At this stage, Helm on the master branch has not been officially released, so it cannot be installed in the form of the charts repository.If you want to try helm installation, please deploy in the form of a local helm repository. For details, see https://helm.sh/docs/helm/helm_install , an unpacked chart directory installation.The official version will be released with version 5.1.2, and the api may be changed at this stage @wangyun1517
