### ISSUE TITLE
Unit test DataSourcePoolDestroyerTest.assertAsyncDestroyHikariDataSource failed occasionally

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#17727]
### Which version of ShardingSphere did you use?

master - 436b495b680e666283b7f517e979c0c01bfd58fa

### Expected behavior

Unit test passed stably.

### Actual behavior

Test case `DataSourcePoolDestroyerTest.assertAsyncDestroyHikariDataSource` failed occasionally.

Refer to https://github.com/apache/shardingsphere/runs/6465279647?check_suite_focus=true

**Comment by LeeGuoPing** [comment]
I saw this problem is caused by timeout, should I adjust the time-out value of this mehtod.
![image](https://user-images.githubusercontent.com/35389145/172775896-6a90cb05-73f2-4d11-b95f-7d5a15401a84.png)

**Comment by TeslaCN** [comment]
Maybe fixed by #18257.
