### ISSUE TITLE
ComplexKeysShardingAlgorithm implemention return tableNameCollection  right but did not route to the table

### ISSUE THREAD

**Issue by linilq** [apache/shardingsphere#17748]
ComplexKeysShardingAlgorithm implemention return tableNameCollection right but did not route to the target table and cause SQLSyntaxErrorException：
### Cause: java.sql.SQLSyntaxErrorException: Table 'linilq.device_user' doesn't exist

for the log has print the actrual sql:

2022-05-17 19:56:53 INFO [main] SQLLogger.java:74 Actual SQL: ds0 ::: INSERT INTO device_user  ( id,
create_user_id,
user_id,
device_no,
device_type,
bind_role,
bind_time,
bind_status )  VALUES  (?, ?, ?, ?, ?, ?, ?, ?) ::: [1526531732107350017, 19911017, 108956421, 20111bacv, 2, 2, 2022-05-17 19:55:00.166, 1]

cannot find anything wrong within the code.wish some help with it .thks a lot

![image](https://user-images.githubusercontent.com/7315931/168806623-384e659c-d143-494b-bc81-24cb425d411b.png)

![image](https://user-images.githubusercontent.com/7315931/168805262-d07df962-6fa4-4763-bd2c-972505d78f94.png)

**Comment by terrymanu** [comment]
I just set it as invalid because of the author close the issue without any reason.
