### ISSUE TITLE
for this condition , which datasource will be selected?

### ISSUE THREAD

**Issue by LikeElephantintheforest** [apache/shardingsphere#17763]
my config like this : 

    datasource:
      trade:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
        jdbcUrl: **jdbc:port/trade**
        username: ${TRADE_DB_USER}
        password: ${TRADE_DB_PASSWD}
      payment:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
        jdbcUrl: **jdbc:port/payment**
        username: ${DB_USER}
        password: ${DB_PASSWD}

      payment-readonly:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
        jdbcUrl:  **jdbc:port/payment**
        username: ${READONLY_PAYMENT_DB_USER}
        password: ${READONLY_PAYMENT_DB_PASSWD}

      trade-readonly:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
        jdbcUrl: **jdbc:port/trade**
        username: ${READONLY_TRADE_DB_USER}
        password: ${READONLY_TRADE_DB_PASSWD}

mysql user trade-readonly  ,  payment-readonly just have read permission;
mysql user trade , payment  have write permission;

they have same jdbcURL , same databases name  and same table schema ,difference is just mysql account;
we want to used difference mysql account to do read or write  (we cant't use master-slave to solve it);

sorry,  i don't  find   ss how to do databases sharding ...   

could happen write request 2 readonly databases  like my config ?

 

project based on springBoot  2.2.5.RELEASE.  + ss 4.1.0 ;

**Comment by LikeElephantintheforest** [comment]
and i. append  "readOnly: true"  to config   , it's necessary ?

**Comment by terrymanu** [comment]
The version 4.x is out of service, please try 5.x
