### ISSUE TITLE
sharding jdbc cross-table sorting paging query

### ISSUE THREAD

**Issue by yuanyuanbb521** [apache/shardingsphere#17800]
## Question

**sharding jdbc cross-table sorting paging query returns incorrect result set, sorting error

**Comment by yuanyuanbb521** [comment]
sharding jdbc cross-table sorting paging query returns the wrong result set, sorting error, for example, by time by month table, a month of data is a table, when I query two months of data, paging query by time descending order, each page query 10, the return result set of 10 data contains two months of data

**Comment by terrymanu** [comment]
I cannot get your point from the title, can you change it?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time
