### ISSUE TITLE
Error when using sharding query

### ISSUE THREAD

**Issue by q3056917665** [apache/shardingsphere#17804]
sharding version: 5.1.1

error:
```
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:177)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:149)
```
The reason for the error: I have no problem using idea to start the query , but using jar start to error.This is the reason why I found the error, but I don't know why it happened
![image](https://user-images.githubusercontent.com/49391495/169250201-ba4cb463-55dd-4dc9-9d1e-e2a74c097869.png)
![image](https://user-images.githubusercontent.com/49391495/169250645-50ba80c6-6ebf-40f0-b8b9-0476b64aeefc.png)

**Comment by TeslaCN** [comment]
Please show us how you packed the Jar.

**Comment by q3056917665** [comment]
@TeslaCN 
Pack command: mvn clean package -Dmaven.test.skip=true
jar start command: java -jar demo.jar 127.0.0.1:2181

**Comment by TeslaCN** [comment]
If you are packing fat jar, you may need to handle SPI in maven-shade-plugin. Refer to https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

**Comment by q3056917665** [comment]
> 如果你正在包装胖罐，你可能需要在maven-shade-plugin中处理SPI。请参阅 https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

@TeslaCN 
Solved, thank you

**Comment by TeslaCN** [comment]
You are welcome.
