### ISSUE TITLE
Refactor EncryptColumnRuleConfiguration to decouple cipher encryptor and assist encryptor

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#17803]
## Feature Request

How about refactor `EncryptColumnRuleConfiguration` as below:  @strongduanmu 

- [x] add assistEncryptorName
- [x] make assistEncryptorName work
- [ ] refactor QueryAssistedEncryptAlgorithm and deprecate it (the only difference of  the algorithm one is **symmetric** and other is **asymmetric**)
- [ ] validate the availabilities on cipherColumn & cipherEncryptorName pair, assistColumn & assistEncryptorName pair

![image](https://user-images.githubusercontent.com/25882819/169700196-4efe8170-4da9-4260-b58f-55e0836c0ebb.png)

**Comment by tuichenchuxin** [comment]
@cheese8 Why need to decouple cipher encryptor and assist encryptor?

**Comment by cheese8** [comment]
> @cheese8 Why need to decouple cipher encryptor and assist encryptor?

One for cipherColumn and one for assistColumn, that's more simple.
