### ISSUE TITLE
Change `readwrite_splitting` to `Readwrite_splitting` for `Official Documentation`

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#17811]
Change `readwrite_splitting` to `Readwrite_splitting`

Address : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/readwirte-splitting-rule/

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/33742097/169289432-9a8b3e12-2dab-4435-b187-9b0e0db28f97.png">

**Comment by Swastyy** [comment]
Hi @zjcnb , I want to complete this task. Thanks.
