### ISSUE TITLE
bug on creating MySQLComStmtExecutePacket

### ISSUE THREAD

**Issue by ruanyg** [apache/shardingsphere#17827]
version： 5.0.0
project: shardingsphere-proxy
cluster mode
use mysql prepareStatement

the parameter is type of MYSQL_TYPE_BLOB(252), packet of mysql shown below
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/19629642/169453557-74f59f4c-d376-4ed9-b8e1-678574a4b81a.png">

At this time, MySQLStringLenencBinaryProtocolValue is used to get parameter value from mysql packet and index out of bound occur.
![image](https://user-images.githubusercontent.com/19629642/169453657-20f2ac7f-0f19-41e5-9ecf-9895456c6021.png)

![image](https://user-images.githubusercontent.com/19629642/169454066-60676fcb-c85f-4282-8e5f-eac6342f2043.png)

**Comment by TeslaCN** [comment]
This issue is caused by ShardingSphere-Proxy cannot handle `COM_STMT_SEND_LONG_DATA`.
