### ISSUE TITLE
[ GSoC 2022 ] Solve unsupported Postgres sql about alter statement for ShardingSphere Parser

### ISSUE THREAD

**Issue by everly-gif** [apache/shardingsphere#17848]
This issue is created to better track my PRs for GSoC 2022.
You can view more about my project [here](https://summerofcode.withgoogle.com/programs/2022/projects/ajDT1hjj)

## Background

Apache ShardingSphere is positioned as a Database Plus, and aims at building a standard layer and
ecosystem above heterogeneous databases. It focuses on how to reuse existing databases and their
respective upper layer, rather than creating a new database. The goal is to minimize or eliminate the
challenges caused by underlying database fragmentation.  

ShardingSphere parser engine is the core of ShardingSphere, It helps users parse a SQL to get the AST
(Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser
engine can handle SQLs for MySQL, PostgreSQL, SQLServer, openGauss and Oracle. However, there are
still many statements that are not supported yet.  

More details:  
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/  

Therefore this project proposes to Solve unsupported Postgres sql about alter statements for
ShardingSphere Parser and also proofread and optimize the grammar wherever needed referring the official postgres [docs](https://www.postgresql.org/docs/current/sql-commands.html).

## Tasks

- [x] ALTER OPERATOR
- [x] ALTER POLICY
- [x] ALTER PUBLICATION
- [x] ALTER ROUTINE
- [x] ALTER RULE
- [x] ALTER SCHEMA
- [x] ALTER SEQUENCE
- [x]  ALTER SERVER
- [x] ALTER STATISTICS
- [x] ALTER SUBSCRIPTION
- [x] ALTER TABLE
- [x] ALTER TEXT SEARCH
- [x]  ALTER TRIGGER
- [x] ALTER TYPE
- [x] ALTER VIEW

**Comment by everly-gif** [comment]
Hi @strongduanmu , please assign this issue to me

**Comment by strongduanmu** [comment]
@everly-gif Assigned.

**Comment by everly-gif** [comment]
This issue has been completed 🎉. 
Thank you for the great mentorship !
Looking forward to staying in touch with the community 😊.

Talking GSoC , @strongduanmu what is the usual work product URL that is preferred by the Org? GitHub Gists, Blogs, Web pages etc?? I will start drafting mine soon after your suggestion.

Thanks.

**Comment by strongduanmu** [comment]
Congratulations @everly-gif , you have done these tasks very well. 👍

> Talking GSoC , @strongduanmu what is the usual work product URL that is preferred by the Org? GitHub Gists, Blogs, Web pages etc?? I will start drafting mine soon after your suggestion.

For this question, I think you can choose a tool you are familiar with to write gsoc summaries.

**Comment by everly-gif** [comment]
> For this question, I think you can choose a tool you are familiar with to write gsoc summaries.
  

Thank you ! I decided to go with GitHub Gists.
Here's the link : https://gist.github.com/everly-gif/b2df9b5b2133afc671c38c43c08f2569
What do you think?
