### ISSUE TITLE
Metadata lost when execute `refresh table metadata` statement

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17887]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/0162b7ef9fd740f2d371336c487ac471aea20a91

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Metadata load correctly when execute `refresh table metadata` statement

### Actual behavior

Metadata lost. The actual public schema contains more than 80 tables, and when I finish `refresh table metadata`, there are only two tables.

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/10829171/169936713-65b28ea3-fe35-44dd-8bd0-6c947ee10b4f.png">

### Reason analyze (If you can)

Wrong schemaName value, causing metadata to be overwritten.

```java
    /**
     * Reload meta data.
     *
     * @param databaseName database name to be reloaded
     * @param schemaName schema name to be reloaded
     */
    public void reloadMetaData(final String databaseName, final String schemaName) {
        try {
            Map<String, ShardingSphereSchema> schemas = loadActualSchema(databaseName, schemaName);
            alterSchemas(databaseName, schemas);
            for (ShardingSphereSchema each : schemas.values()) {
                metaDataContexts.getPersistService().ifPresent(optional -> optional.getSchemaMetaDataService().persistTables(databaseName, schemaName, each));
            }
        } catch (final SQLException ex) {
            log.error("Reload database:{} meta data of schema:{} failed", databaseName, schemaName, ex);
        }
    }
```

In addition, refreshing a single table created in native PostgreSQL through the `refresh table metadata` statement will also fail to load.

**Comment by zjcnb** [comment]
Thx, i will chekc it.
