### ISSUE TITLE
[GSOC 2022] Develop an external tool to convert YAML configuration DistSQL script

### ISSUE THREAD

**Issue by isHuangXin** [apache/shardingsphere#17939]
This issue is created to better track my PRs for GSoC 2022.
You can find more details about my project [here](https://summerofcode.withgoogle.com/programs/2022/projects/4PnSweAf)

## Background
Apache ShardingSphere is positioned as a Database Plus, and aims at building a standard layer and ecosystem above heterogeneous databases. It focuses on how to reuse existing databases and their respective upper layer, rather than creating a new database. The goal is to minimize or eliminate the challenges caused by underlying databases fragmentation.

Below is my completion plan 

step 1: Parsing YAML files.
Step2: Figure out what we need to complete the output DistSQL RDL  is 'ADD' and 'CREATE' syntax from parsing YAML files.
Step3: Wrap a command line tool to complete the conversion of YAML to DistSQL without starting a proxy.

- [x] ADD RESOURCE dataSource
- [x] CREATE SHARDING TABLE RULE 
- [x] Sharding Binding Table Rule
- [x] Sharding Broadcast Table Rule
- [x] Sharding Scaling Rule
- [x] CREATE READWRITE_SPLITTING RULE
- [x] CREATE DB_DISCOVERY RULE
- [x] CREATE ENCRYPT RULE
- [x] CREATE SHADOW RULE

**Comment by RaigorJiang** [comment]
Hi @isHuangXin ,
Nice to see you here!  But the link you provided cannot be accessed (access denied).

**Comment by isHuangXin** [comment]
> Hi @isHuangXin , Nice to see you here! But the link you provided cannot be accessed (access denied).

Sry for late reply. The link has been updated, is it accessible now?

**Comment by RaigorJiang** [comment]
> Sry for late reply. The link has been updated, is it accessible now?

Yes, the new link is accessible.

**Comment by TeslaCN** [comment]
This issue is not finished yet.

**Comment by isHuangXin** [comment]
Hi, @RaigorJiang 
This issue about GSoC 2022 has been completed 🎉.
Thank you for the great guidance, which has made me learn a lot. 

I will continue to contribute code to ShardingSphere, here is my GSoC 2022 final report link: https://github.com/isHuangXin/GSoC-2022-DistSQL-Convert-Tool

**Comment by RaigorJiang** [comment]
@isHuangXin 
Sorry, this CI failure has not been completed
https://github.com/apache/shardingsphere/pull/20843

**Comment by RaigorJiang** [comment]
Not completed
