### ISSUE TITLE
CONNECTION_ID() do not support alias

### ISSUE THREAD

**Issue by lcxywfe** [apache/shardingsphere#17949]
### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
select CONNECTION_ID() as cid;
get:
cid: 1

### Actual behavior
connection_id():  1

**Comment by terrymanu** [comment]
Does anyone want to fix it?

**Comment by csonezp** [comment]
I want to try it
