### ISSUE TITLE
Improve of IntervalShardingAlgorithm

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#17957]
- [ ] Extract 3 private methods in `doSharding` method for `doShardingInLocalDate`, `doShardingInLocalTime` amd `doShardingInLocalDateTime`
- [ ] The instanceOf judgment is too complicated in method `getDateTimeText`, it is better to use instanceOf TemporalAccessor to judge it and move the instanceOf Instant in front of  TemporalAccessor judgment
- [ ] The variable name `viewAsLocalDate` and `viewAsLocalTime` in method `getMatchedTables` are difficult to understand. How about rename them as `localDate` and `localTime`?

**Comment by ICannerxy** [comment]
Please assign it to me

**Comment by strongduanmu** [comment]
@ICannerxy Assigned.
