### ISSUE TITLE
how to deploy to maven Nexus

### ISSUE THREAD

**Issue by 18291486619** [apache/shardingsphere#18028]
i has install success

but deploy to  maven Nexus fail

my maven setting has  set maven Nexus  user and password

mvn  deploy -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -DrepositoryId=snapshots -T1C

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.706 s (Wall Clock)
[INFO] Finished at: 2022-05-28T17:25:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project shardingsphere: Failed to deploy artifacts: Could not transfer artifact org.apache.shardingsphere:shardingsphere:pom:5.1.1-20220528.092536-1 from/to apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots): authentication failed for https://repository.apache.org/content/repositories/snapshots/org/apache/shardingsphere/shardingsphere/5.1.1-SNAPSHOT/shardingsphere-5.1.1-20220528.092536-1.pom, status: 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

 
<parent>
        <groupId>org.apache</groupId>
        <artifactId>apache</artifactId>
        <version>21</version>
    </parent>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere</artifactId>
    <version>5.1.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>

**Comment by terrymanu** [comment]
This is general maven issues, I just close it.
