### ISSUE TITLE
Proxy not support ALTER TABLE xxx RENAME statement of sharding tables

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#18021]
## Bug Report

Proxy not support`ALTER TABLE xxx RENAME`  statement of MySQL.
will support it in the future?

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Proxy

### Expected behavior

rename all sharding tables name

### Actual behavior

```
mysql> CREATE TABLE t_order (order_id bigint NOT NULL, user_id int NOT NULL, status varchar(50) DEFAULT NULL, t_numeric numeric(10,2) DEFAULT NULL, PRIMARY KEY (order_id));
Query OK, 0 rows affected (0.21 sec)

mysql> ALTER TABLE t_order RENAME TO t_order_temp;
ERROR 1997 (C1997): Runtime exception: [ALTER TABLE ... RENAME TO ... statement can not support sharding tables and broadcast tables.]
```

### Reason analyze (If you can)

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/101622833/170805676-92ddcdf3-1391-467e-b44b-8831fb58c71f.png">

**Comment by terrymanu** [comment]
No plan to support it
