### ISSUE TITLE
deploy到私服

### ISSUE THREAD

**Issue by 18291486619** [apache/shardingsphere#18025]
mvn  deploy -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -DrepositoryId=snapshots -T1C

使用master分支

setting已经配置私服地址和账号

528.070633-1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.462 s (Wall Clock)
[INFO] Finished at: 2022-05-28T15:06:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project shardingsphere-jdbc-core-spring-boot-starter: Failed to deploy artifacts: Could not transfer artifact org.apache.shardingsphere:shardingsphere-jdbc-core-spring-boot-starter:jar:5.1.1-20220528.070633-1 from/to apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots): authentication failed for https://repository.apache.org/content/repositories/snapshots/org/apache/shardingsphere/shardingsphere-jdbc-core-spring-boot-starter/5.1.1-SNAPSHOT/shardingsphere-jdbc-core-spring-boot-starter-5.1.1-20220528.070633-1.jar, status: 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
