### ISSUE TITLE
This version of ShardingSphere-Proxy doesn't yet support this SQL

### ISSUE THREAD

**Issue by jokeyuHhhh** [apache/shardingsphere#18039]
springboot+xa+shardingproxy5.1.1
mysql-connector-java version 8.0.11
xa commit sql to proxy :XA START 0x31302e382e302e362e746d313635333739393036353235313030303038,0x31302e382e302e362e746d3134,0x41544f4d 
![image](https://user-images.githubusercontent.com/106460562/170852546-c5d42dcc-d0fe-411c-940a-1b29c4851b23.png)
![image](https://user-images.githubusercontent.com/106460562/170852575-d5715a3a-a6e3-40c9-836b-7b7ae8c1abb6.png)
![image](https://user-images.githubusercontent.com/106460562/170852591-b6e4eb59-662d-459e-8b1c-81a31a02a7cb.png)
![image](https://user-images.githubusercontent.com/106460562/170852613-10032418-fb9b-4f88-b97b-dd6eaf03b5e5.png)

**Comment by terrymanu** [comment]
I just set it as invalid because of the author close the issue without any reason.
