### ISSUE TITLE
shardingsphere-proxy throw XA Exception When integration with spring boot and atomikos

### ISSUE THREAD

**Issue by jokeyuHhhh** [apache/shardingsphere#18056]
## Bug Report
An exception is reported when using XA to commit transactions to sharding-proxy
![image](https://user-images.githubusercontent.com/106460562/170911593-202cdd7f-3ba3-447c-a26a-e5d66b119878.png)
![image](https://user-images.githubusercontent.com/106460562/170911645-c1dc21fc-7fae-4149-a2cd-3ac378974e1f.png)

The use of springboot  + jta+sharding-proxy

The springboot dataSource configuration is as follows
![image](https://user-images.githubusercontent.com/106460562/170911971-59371b47-7a3c-489e-a91e-bc4f8bc4cf88.png)
![image](https://user-images.githubusercontent.com/106460562/170912041-49f7e892-d3ef-4ecc-a7a8-e2221c6b561e.png)

The springboot transaction configuration is as follows
![image](https://user-images.githubusercontent.com/106460562/170912280-8a548af0-b81e-4099-8263-a0e049f8bf1f.png)
![image](https://user-images.githubusercontent.com/106460562/170912303-be6c8cd4-9daf-471b-a6ef-f85fedea38f1.png)
jta configuration is as follows
![image](https://user-images.githubusercontent.com/106460562/170912316-6f708709-2214-433f-8772-37111ac3b2dc.png)
![image](https://user-images.githubusercontent.com/106460562/170912325-ad76e824-a6ff-4245-8011-f6d48137d91f.png)

sharding-proxy turns on the default XA transaction configuration
![170852591-b6e4eb59-662d-459e-8b1c-81a31a02a7cb](https://user-images.githubusercontent.com/106460562/170912625-75e5beb9-9d31-45fe-9530-6e6b05530dc6.png)
Check out some configurations of jta.properties    
![170852613-10032418-fb9b-4f88-b97b-dd6eaf03b5e5](https://user-images.githubusercontent.com/106460562/170912790-ee6fa909-0b6b-4af9-a2cf-6f3b36087aed.png)

### Which version of ShardingSphere did you use?
ShardingSphere 5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy

### Expected behavior
Committing the XA transaction statement succeeded
### Actual behavior
SQLSyntaxErrorException: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
### Reason analyze (If you can)
The Sharding-proxy configuration is faulty or has a bug  
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Failed to execute the XA statement in the proxy database
The sql is :XA START 0x31302e382e302e362e746d313635333739393036353235313030303038,0x31302e382e302e362e746d3134,0x41544f4d

**Comment by jokeyuHhhh** [comment]
The mysql-connector cersion 8.0.11 
The Atomikos version 4.0.6

**Comment by jingshanglu** [comment]
@jokeyuHhhh  The proxy uses the `xa` protocol internally to ensure the transaction semantics of the ds managed by ShardingSphere-proxy, but does not provide the `xa` interface to the outside.
