### ISSUE TITLE
The 5.1.1 document is not ture about sharding rules

### ISSUE THREAD

**Issue by 726411951** [apache/shardingsphere#18055]
### Which version of ShardingSphere did you use?
5.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
configure sharding-jdbc properties
### Reason analyze (If you can)
the document is not update 
### Example codes for reproduce this issue (such as a github link).

![image](https://user-images.githubusercontent.com/32379580/170907416-48462e4e-bc87-409b-9859-13da8e73e42a.png)

I use this document configuration,but it is not work.
So I check the source code from example and find it likes 
![image](https://user-images.githubusercontent.com/32379580/170908604-e0c14544-325d-456d-900a-c63cf72f424a.png)

Is the document need to be update?
the source code link [application-sharding-databases.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-sharding-databases.properties)

**Comment by zjcnb** [comment]
@726411951 Hi, thank you for your feedback, i think it's no problem. Because, it may be `standard` or `complex` or `hint`.

**Comment by 726411951** [comment]
> @726411951 Hi, thank you for your feedback, i think it's no problem. Because, it may be `standard` or `complex` or `hint`.
@zjcnb But the key differences between `spring.shardingsphere.sharding.database-strategy` and `spring.shardingsphere.rules.sharding.database-strategy` is `.rules`  and I think it's necessary to run with 5.1.1 version 
the document is missing `.rules`

**Comment by zjcnb** [comment]
> @zjcnb But the key differences between `spring.shardingsphere.sharding.database-strategy` and `spring.shardingsphere.rules.sharding.database-strategy` is `.rules` and I think it's necessary to run with 5.1.1 version the document is missing `.rules`

Yeah, you are right. Can you submit a pull request to fix it?

**Comment by 726411951** [comment]
@zjcnb fine，I will do it

**Comment by RaigorJiang** [comment]
Hi @726411951  any update?

**Comment by 726411951** [comment]
@RaigorJiang  Hi，I think the repository of the website is [shardingsphere-doc](https://github.com/apache/shardingsphere-doc)  ,so should I commit in this repository and close this issue?

**Comment by RaigorJiang** [comment]
@726411951 
We just need to update the markdown file in https://github.com/apache/shardingsphere/tree/master/docs and `shardingsphere-doc` will automatically build the new content.

**Comment by 726411951** [comment]
@RaigorJiang  Fine，I will update it soon.
