### ISSUE TITLE
ont the navicat , different window exec  SHOW SCHEMA RESOURCES ,result different also 。

### ISSUE THREAD

**Issue by connor1024** [apache/shardingsphere#18070]
version info ： shardingsphere proxy 5.1.0 
mode type : cluster,
repository type : ZooKeeper

my question that : 
On the  Navicat window exec [SHOW SCHEMA RESOURCES] 
result:
![image](https://user-images.githubusercontent.com/105640567/170962540-d9f7e044-7bd8-429a-b421-e92819b0a4d8.png)

but on other navicat window  exec [SHOW SCHEMA RESOURCES] 
![image](https://user-images.githubusercontent.com/105640567/170962596-cbb561ea-32a6-43da-9a5c-8090d58d7698.png)

first window less a datasource:wey_test

in the ZooKeeper UI , hava this datasource wey_test: 
![image](https://user-images.githubusercontent.com/105640567/170963403-837400e7-bf5f-4a0e-8fb5-9b58518b1509.png)

**Comment by connor1024** [comment]
How did I find this problem ？An exception occurred in the log of my service：[Hint datasource: xxxx is not exist!]。

**Comment by zjcnb** [comment]
@connor1024 Hi, How to add resource `wey_test`? Is it by `DistSQL`?

**Comment by connor1024** [comment]
> 

yes,  DistSQL :
-- 新增数据库资源
ADD RESOURCE wey_test (
    URL="",
    USER=root,
    PASSWORD=root,
PROPERTIES("connectionTimeoutMilliseconds"=30000,"idleTimeoutMilliseconds"=60000,"maxLifetimeMilliseconds"=1800000,"maxPoolSize"=50,"minPoolSize"=1)
);

**Comment by connor1024** [comment]
> @connor1024 Hi, How to add resource `wey_test`? Is it by `DistSQL`?

yes, DistSQL :
-- 新增数据库资源
ADD RESOURCE wey_test (
URL="",
USER=root,
PASSWORD=root,
PROPERTIES("connectionTimeoutMilliseconds"=30000,"idleTimeoutMilliseconds"=60000,"maxLifetimeMilliseconds"=1800000,"maxPoolSize"=50,"minPoolSize"=1)
);

**Comment by connor1024** [comment]
> @connor1024 Hi, How to add resource `wey_test`? Is it by `DistSQL`?

yes, DistSQL :
ADD RESOURCE wey_test (
URL="",
USER=root,
PASSWORD=root,
PROPERTIES("connectionTimeoutMilliseconds"=30000,"idleTimeoutMilliseconds"=60000,"maxLifetimeMilliseconds"=1800000,"maxPoolSize"=50,"minPoolSize"=1)
);

**Comment by terrymanu** [comment]
@connor1024 What is your configuration?

**Comment by TeslaCN** [comment]
This may be fixed in latest version. Please open a new issue if the problem still exists.
