### ISSUE TITLE
Can the documentation get any worse?

### ISSUE THREAD

**Issue by qianYzz** [apache/shardingsphere#18102]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by qianYzz** [comment]
小白看文档 根本配不起来

**Comment by qianYzz** [comment]
我要疯了

**Comment by TeslaCN** [comment]
Hi @qianYzz 
You may refer to examples here. https://github.com/apache/shardingsphere/tree/master/examples
If you have any suggestion, welcome to submit Pull Requests.

**Comment by terrymanu** [comment]
Constructive feedback accepted only, I am sorry to close this issue.
