### ISSUE TITLE
Support password encrypt

### ISSUE THREAD

**Issue by galaxylqx** [apache/shardingsphere#18107]
The current passwords in server.yaml and config.yaml are stored in plain text, and I hope to support encryption of passwords
server.yaml

server.yaml
props:
   proxy-password-encrypt-enabled: true # Proxy password encrypt, default false.
   proxy-password-encrypt-salt: '' # Proxy password encrypt salt

**Comment by RaigorJiang** [comment]
Hi @galaxylqx 
This idea is very interesting, there was a similar issue before, but it was not completed in the end, hope you can take a look at this PR: #11440

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If you want to continue this topic, please reopen it or submit a new one.
