### ISSUE TITLE
ShardingSphereException: Route table xxx_journal_202205 does not exist, available actual table: [xxx_journal_]

### ISSUE THREAD

**Issue by liuyuqiang** [apache/shardingsphere#18111]
### Error querying database.  Cause: org.apache.shardingsphere.infra.exception.ShardingSphereException: Route table xxxx_journal_202205 does not exist, available actual table: [xxx_journal_]

<img width="922" alt="image" src="https://user-images.githubusercontent.com/3795195/171253385-c8b9aa04-7e33-431c-b579-dfba7a8a9c2b.png">

<img width="918" alt="image" src="https://user-images.githubusercontent.com/3795195/171253561-102f9a22-6950-46cb-888f-11dbd1cc08fb.png">

这种错误是什么引起的？

**Comment by strongduanmu** [comment]
Please submit issue according to bug template.

**Comment by terrymanu** [comment]
Closed because of no feedback for long time
