### ISSUE TITLE
bug:In the case of sub-tables, if the sql contains on group by select, it will cause an error in the actually generated sql

### ISSUE THREAD

**Issue by carlyin0801** [apache/shardingsphere#18122]
**Bug Report**
Which version of ShardingSphere did you use?
5.1.1

**Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?**
ShardingSphere-JDBC

**configuration:**
"ds_{0..1}.T_ATOM_FAIL_SUMMARY_DATA_{0..1}"

**table init sql:**
CREATE TABLE `T_ATOM_FAIL_SUMMARY_DATA_0` (
  `ID` bigint(32) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `PIPELINE_NAME` varchar(255) NOT NULL,
  `ATOM_CODE` varchar(64) NOT NULL,
  `ATOM_NAME` varchar(64) NOT NULL,
  `CLASSIFY_CODE` varchar(32) NOT NULL,
  `CLASSIFY_NAME` varchar(32) NOT NULL,
  `ERROR_TYPE` int(11) DEFAULT NULL,
  `ERROR_COUNT` int(11) DEFAULT NULL,
  `STATISTICS_TIME` datetime(3) NOT NULL,
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`ID`),
  KEY `INX_TAFSD_PROJECT_TIME_PIPELINE_TYPE` (`PROJECT_ID`,`STATISTICS_TIME`,`PIPELINE_ID`,`ERROR_TYPE`),
  KEY `INX_TAFSD_PROJECT_TIME_TYPE` (`PROJECT_ID`,`STATISTICS_TIME`,`ERROR_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `T_ATOM_FAIL_SUMMARY_DATA_1` (
  `ID` bigint(32) NOT NULL,
  `PROJECT_ID` varchar(64) NOT NULL,
  `PIPELINE_ID` varchar(34) NOT NULL,
  `PIPELINE_NAME` varchar(255) NOT NULL,
  `ATOM_CODE` varchar(64) NOT NULL,
  `ATOM_NAME` varchar(64) NOT NULL,
  `CLASSIFY_CODE` varchar(32) NOT NULL,
  `CLASSIFY_NAME` varchar(32) NOT NULL,
  `ERROR_TYPE` int(11) DEFAULT NULL,
  `ERROR_COUNT` int(11) DEFAULT NULL,
  `STATISTICS_TIME` datetime(3) NOT NULL,
  `CREATOR` varchar(50) NOT NULL DEFAULT 'system',
  `MODIFIER` varchar(50) NOT NULL DEFAULT 'system',
  `UPDATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CREATE_TIME` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`ID`),
  KEY `INX_TAFSD_PROJECT_TIME_PIPELINE_TYPE` (`PROJECT_ID`,`STATISTICS_TIME`,`PIPELINE_ID`,`ERROR_TYPE`),
  KEY `INX_TAFSD_PROJECT_TIME_TYPE` (`PROJECT_ID`,`STATISTICS_TIME`,`ERROR_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

**Expected behavior**
select `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE` as `atomCode`, `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` as `errorType`, sum(ERROR_COUNT) as `ErrorCountSum`, `T_ERROR_TYPE_DICT`.`NAME` as `errorName` from `T_ATOM_FAIL_SUMMARY_DATA` join `T_ERROR_TYPE_DICT` on `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` = `T_ERROR_TYPE_DICT`.`ERROR_TYPE` where `T_ATOM_FAIL_SUMMARY_DATA`.`STATISTICS_TIME` between ? and ? group by `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE`, `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE`
**can be converted into**
select `T_ATOM_FAIL_SUMMARY_DATA_1`.`ATOM_CODE` as `atomCode`, `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` as `errorType`, sum(ERROR_COUNT) as `ErrorCountSum`, `T_ERROR_TYPE_DICT`.`NAME` as `errorName` from `T_ATOM_FAIL_SUMMARY_DATA_1` join `T_ERROR_TYPE_DICT` on `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` = `T_ERROR_TYPE_DICT`.`ERROR_TYPE` where `T_ATOM_FAIL_SUMMARY_DATA_1`.`STATISTICS_TIME` between ? and ? group by `T_ATOM_FAIL_SUMMARY_DATA_1`.`ATOM_CODE`, `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` 

**Actual behavior**
select `T_ATOM_FAIL_SUMMARY_DATA_1`.`ATOM_CODE` as `atomCode`, `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` as `errorType`, sum(ERROR_COUNT) as `ErrorCountSum`, `T_ERROR_TYPE_DICT`.`NAME` as `errorName` from `T_ATOM_FAIL_SUMMARY_DATA_1` join `T_ERROR_TYPE_DICT` on `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` = `T_ERROR_TYPE_DICT`.`ERROR_TYPE` where `T_ATOM_FAIL_SUMMARY_DATA_1`.`STATISTICS_TIME` between ? and ? group by `T_ATOM_FAIL_SUMMARY_DATA_1`.`ATOM_CODE`, `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` **ORDER BY `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE` ASC,`T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` ASC**

The error message is as follows:
2022.06.01 14:46:01,733|20892487-66f2-459a-8c30-609ebc87f48d| [NIO-2 task-2] ERROR c.t.d.c.w.handler.RuntimeExceptionMapper 47 Failed with runtime exceptionrorCountSum`, `T_ERROR_TYPE_DICT`.`NAME` as `errorName` from `T_ATOM_FAIL_SUMMARY_DATA_1` join `T_ERROR_TYPE_DICT` on `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` = `T_ERROR_TYPE_DICT`.`ERROR_TYPE` where `T_ATOM_FAIL_SUMMARY_DATA_1`.`STATISTICS_TIME` between ? and ? group by `T_ATOM_FAIL_SUMMARY_DATA_1`.`ATOM_CODE`, `T_ATOM_FAIL_SUMMARY_DATA_1`.`ERROR_TYPE` ORDER BY `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE` ASC,`T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` ASCorg.jooq.exception.DataAccessException: SQL [select `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE` as `atomCode`, `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` as `errorType`, sum(ERROR_COUNT) as `ErrorCountSum`, `T_ERROR_TYPE_DICT`.`NAME` as `errorName` from `T_ATOM_FAIL_SUMMARY_DATA` join `T_ERROR_TYPE_DICT` on `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE` = `T_ERROR_TYPE_DICT`.`ERROR_TYPE` where `T_ATOM_FAIL_SUMMARY_DATA`.`STATISTICS_TIME` between ? and ? group by `T_ATOM_FAIL_SUMMARY_DATA`.`ATOM_CODE`, `T_ATOM_FAIL_SUMMARY_DATA`.`ERROR_TYPE`]; Unknown column 'T_ATOM_FAIL_SUMMARY_DATA.ATOM_CODE' in 'order clause'        at org.jooq_3.14.15.MYSQL.debug(Unknown Source)        at org.jooq.impl.Tools.translate(Tools.java:2903)        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:337)        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2880)

**Comment by cheese8** [comment]
I can not reproduce this case with latest master, can you describe it in short and provide the demo to reproduce it?

**Comment by carlyin0801** [comment]
Expected behavior
select T_ATOM_FAIL_SUMMARY_DATA.ATOM_CODE as atomCode, T_ATOM_FAIL_SUMMARY_DATA.ERROR_TYPE as errorType, sum(ERROR_COUNT) as ErrorCountSum, T_ERROR_TYPE_DICT.NAME as errorName from T_ATOM_FAIL_SUMMARY_DATA join T_ERROR_TYPE_DICT on T_ATOM_FAIL_SUMMARY_DATA.ERROR_TYPE = T_ERROR_TYPE_DICT.ERROR_TYPE where T_ATOM_FAIL_SUMMARY_DATA.STATISTICS_TIME between ? and ? group by T_ATOM_FAIL_SUMMARY_DATA.ATOM_CODE, T_ATOM_FAIL_SUMMARY_DATA.ERROR_TYPE
can be converted into
select T_ATOM_FAIL_SUMMARY_DATA_1.ATOM_CODE as atomCode, T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE as errorType, sum(ERROR_COUNT) as ErrorCountSum, T_ERROR_TYPE_DICT.NAME as errorName from T_ATOM_FAIL_SUMMARY_DATA_1 join T_ERROR_TYPE_DICT on T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE = T_ERROR_TYPE_DICT.ERROR_TYPE where T_ATOM_FAIL_SUMMARY_DATA_1.STATISTICS_TIME between ? and ? group by T_ATOM_FAIL_SUMMARY_DATA_1.ATOM_CODE, T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE

Actual behavior
select T_ATOM_FAIL_SUMMARY_DATA_1.ATOM_CODE as atomCode, T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE as errorType, sum(ERROR_COUNT) as ErrorCountSum, T_ERROR_TYPE_DICT.NAME as errorName from T_ATOM_FAIL_SUMMARY_DATA_1 join T_ERROR_TYPE_DICT on T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE = T_ERROR_TYPE_DICT.ERROR_TYPE where T_ATOM_FAIL_SUMMARY_DATA_1.STATISTICS_TIME between ? and ? group by T_ATOM_FAIL_SUMMARY_DATA_1.ATOM_CODE, T_ATOM_FAIL_SUMMARY_DATA_1.ERROR_TYPE **ORDER BY T_ATOM_FAIL_SUMMARY_DATA.ATOM_CODE ASC,T_ATOM_FAIL_SUMMARY_DATA.ERROR_TYPE ASC**

@cheese8 The highlighted content above is redundant

**Comment by terrymanu** [comment]
What is your configuration of ShardingSphere?

**Comment by TeslaCN** [comment]
Close due to no response.
