### ISSUE TITLE
Route table logicTable_xxx does not exist, available actual table: [logicTable]

### ISSUE THREAD

**Issue by Linda-Tan** [apache/shardingsphere#18123]
Version:5.1.1
An error occurred:
Route table ea_document_1 does not exist, available actual table: [ea_document]
Problem Description,: I can't find my custom sharded table in availableTargetNames, what should I do. 4.1.1 It's okay to write like this
Error address:org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:79)
configuration:
![image](https://user-images.githubusercontent.com/19643764/171352127-992bc0ea-f8b0-44fa-b90d-f938096a8713.png)
![image](https://user-images.githubusercontent.com/19643764/171352218-ec80ea81-8049-43d7-8ee8-06360913c02e.png)

**Comment by strongduanmu** [comment]
Hi @Linda-Tan, please translate this issue to English first. Besides, can you check your actual table `logicTable_xxx` exists in actualDataNodes?

**Comment by Linda-Tan** [comment]
DataNodes It will actually increase dynamically, can you bypass the verification of this item?

**Comment by Linda-Tan** [comment]
Tables are dynamically created via triggers
