### ISSUE TITLE
Add unit test for JdbcQueryPropertiesExtensionFactory

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#18151]
`JdbcQueryPropertiesExtensionFactoryTest.java` could be added in `shardingsphere-test/shardingsphere-pipeline-test` module. Since `JdbcQueryPropertiesExtension` SPI implementations are in dialect modules.

Currently, `JdbcQueryPropertiesExtension` has 3 implementations: MySQL, PostgreSQL, openGauss.
We could add `assertExtendQueryPropertiesForMySQL` etc unit test methods, get real implementation, verify implementation class and also verify part of the query properties if it exists.

**Comment by natehuangting** [comment]
I want to complete this issue, is it possible?

**Comment by yx9o** [comment]
@natehuangting Welcome.

**Comment by natehuangting** [comment]
Thank you!
