### ISSUE TITLE
Association query sub table data cannot be exported

### ISSUE THREAD

**Issue by imjcoder** [apache/shardingsphere#18170]
**### Thank you da lao **
According to order_ ID to query, order_ When the ID is an odd number, only the odd t can be found_ order_ Data in item, otherwise even data can only be queried

It didn't work out until 5:00 am. Can you provide more examples on the official website?

I have uploaded the code to Baidu cloud, but it can't be uploaded to GitHub....

baidu [wangpan：](https://pan.baidu.com/s/1DCXW14UtLdby6lI5ELLqzw?pwd=btch)
password: btch 

The third example, the test code in, according to order_ During ID query and paging query, the data in the sub table is inaccurate..

The table structure is as follows：

`
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for t_order0
-- ----------------------------
DROP TABLE IF EXISTS `t_order0`;
CREATE TABLE `t_order0` (
  `order_id` bigint NOT NULL COMMENT '主键ID',
  `add_time` date DEFAULT NULL COMMENT '入库时间',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(100) DEFAULT NULL COMMENT '订单编号',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';

-- ----------------------------
-- Table structure for t_order1
-- ----------------------------
DROP TABLE IF EXISTS `t_order1`;
CREATE TABLE `t_order1` (
  `order_id` bigint NOT NULL COMMENT '主键ID',
  `add_time` date DEFAULT NULL COMMENT '入库时间',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(100) DEFAULT NULL COMMENT '订单编号',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';

-- ----------------------------
-- Table structure for t_order2
-- ----------------------------
DROP TABLE IF EXISTS `t_order2`;
CREATE TABLE `t_order2` (
  `order_id` bigint NOT NULL COMMENT '主键ID',
  `add_time` date DEFAULT NULL COMMENT '入库时间',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(100) DEFAULT NULL COMMENT '订单编号',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';

-- ----------------------------
-- Table structure for t_order3
-- ----------------------------
DROP TABLE IF EXISTS `t_order3`;
CREATE TABLE `t_order3` (
  `order_id` bigint NOT NULL COMMENT '主键ID',
  `add_time` date DEFAULT NULL COMMENT '入库时间',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(100) DEFAULT NULL COMMENT '订单编号',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';`

**Comment by xinglijun1973** [comment]
what's your expected and actual ?

**Comment by terrymanu** [comment]
Closed because of no feedback
