### ISSUE TITLE
Shardingsphere-jdbc single db , how to config local transaction with spring

### ISSUE THREAD

**Issue by AzeWZ** [apache/shardingsphere#18178]
## Question
prepare: 
1. single db, only use partition table function
2. with spring boot 
3. don't use xa or seata. i only have one db.
q:
transaction don't rollback.  however config 
"     data-source-properties:
          useLocalSessionState: false"  can rollback.
how to config transaction with spring boot.

**Comment by RaigorJiang** [comment]
Hi @jingshanglu , can you take a look at this question?

**Comment by phdbutbachelor** [comment]
you can inject a ShardingSphereDataSource bean into a LocalSesstionFactoryBean, then a PlatformTransactionManager:
-----------------------------------------------------------------------------------------------------------------------------------
@Bean
public DataSource mainShardingSphereDataSource() throws IOException, SQLException {
    File _yaml = ResourceUtils.getFile("classpath:shardingsphere.yml");
    return YamlShardingSphereDataSourceFactory.createDataSource(_yaml);
}

@Bean
public LocalSessionFactoryBean mainShardingSphereSessionFactory(@Value(value = "${spring.datasource.main.dialect}") String dialect, @Qualifier(value = "mainShardingSphereDataSource") DataSource dataSource) {
    LocalSessionFactoryBean _localSessionFactoryBean = new LocalSessionFactoryBean();
    _localSessionFactoryBean.setDataSource(dataSource);
    _localSessionFactoryBean.setPackagesToScan("gmcc.sparrow.model.set");

    Properties _properties = new Properties();
    _properties.setProperty("hibernate.dialect", dialect); // 设置方言
    _localSessionFactoryBean.setHibernateProperties(_properties);
    return _localSessionFactoryBean;
}

@Bean
public PlatformTransactionManager mainShardingSphereTransactionManager(@Qualifier(value = "mainShardingSphereSessionFactory") EntityManagerFactory entityManagerFactory) {
    return new JpaTransactionManager(entityManagerFactory);
}
-----------------------------------------------------------------------------------------------------------------------------------
