### ISSUE TITLE
RC4EncryptAlgorithm key lost bug

### ISSUE THREAD

**Issue by BasZhang** [apache/shardingsphere#18194]
### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc-core-spring-boot-starter

### Expected behavior
 Input data with different keys produce different output.

### Actual behavior
Outputs are no different.
### Reason analyze (If you can)
org.apache.shardingsphere.encrypt.algorithm.RC4EncryptAlgorithm resets the key after encrypt or decrypt.

**Comment by terrymanu** [comment]
Could you change the title for search friendly?

**Comment by cheese8** [comment]
I will check this.
