### ISSUE TITLE
An incorrect SQL statement was generated when the SQL statement contained "count ditinct(id1,id2)" 

### ISSUE THREAD

**Issue by devin-wanghuixiong** [apache/shardingsphere#18210]
Logic SQL: select distinct count(distinct checkdetai0_.id, checkdetai0_.tenant_id) as col_0_0_ from check_detail_sale checkdetai0_ left outer join check_detail_sale_item items1_ on checkdetai0_.id=items1_.master_id and checkdetai0_.tenant_id=items1_.tenant_id and ( items1_.deleted=0) where ( checkdetai0_.deleted=0) and checkdetai0_.tenant_id=100 and checkdetai0_.id>=45660871065600000 and checkdetai0_.id<57257282764800000

Actual SQL: check_0 ::: select distinct DISTINCT checkdetai0_.id,checkdetai0_.tenant_id as col_0_0_ from check_detail_sale_2022_05 checkdetai0_ left outer join check_detail_sale_item_2022_05 items1_ on checkdetai0_.id=items1_.master_id and checkdetai0_.tenant_id=items1_.tenant_id and ( items1_.deleted=0) where ( checkdetai0_.deleted=0) and checkdetai0_.tenant_id=100 and checkdetai0_.id>=45660871065600000 and checkdetai0_.id<57257282764800000

version v5.1.1

What should I do now

**Comment by cheese8** [comment]
I did not reproduce it, can you provide a demo?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
