### ISSUE TITLE
Support inline constraint in Oracle CREATE TABLE statement

### ISSUE THREAD

**Issue by zhiyoucai** [apache/shardingsphere#18230]
## English Description
When I input such a sql statement to create a table:

```sql
create table test1
(
  id int not null
);
```

I support that "not null" will be in the SqlStatement object.

## Chinese Description

当我解析这样一段SQL的时候：

```sql
create table test1
(
  id int not null
);
```

我希望在解析后“not null”，可以出现在SqlStatement的实现类中。

**Comment by zhiyoucai** [comment]
我正在开发这个功能

**Comment by terrymanu** [comment]
Could you translate to English?
