### ISSUE TITLE
[ShardingProxy] sessionVariables in jdbc url will cause 'not a valid entry' exception when using dsql to add/alter resource

### ISSUE THREAD

**Issue by pencilcap123** [apache/shardingsphere#18331]
## Bug Report

session variables set in jdbc url is not supported when using dsql to add/alter resource to shardingproxy.

```bash
jdbc:mysql://127.0.0.1:3306/aa?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&sessionVariables=ob_query_timeout=30000000,ob_read_consistency='weak'
```

Shardigproxy will throw not a valid entry exception when parsing jdbc url containing sessionVariables params.

![image](https://user-images.githubusercontent.com/41630875/173322715-4c2c0496-2985-4d15-bdcf-eec3834889f0.png)

### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Adding resource using dsql with sessionVariables params is suppored because sessionVariables is a widely-used jdbc url param for mysql

### Actual behavior
Shardigproxy will throw not a valid entry exception when parsing jdbc url containing sessionVariables params.

![image](https://user-images.githubusercontent.com/41630875/173322715-4c2c0496-2985-4d15-bdcf-eec3834889f0.png)

### Reason analyze (If you can)
the '=' character must not be used as the separator directly. 
![image](https://user-images.githubusercontent.com/41630875/173323125-633e7115-b148-46e5-b445-181756e1ec14.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
jdbc:mysql://127.0.0.1:3306/aa?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&sessionVariables=ob_query_timeout=30000000,ob_read_consistency='weak'

adding resource using jdbcurl above will reproduce the bug.

### Example codes for reproduce this issue (such as a github link).
none

**Comment by zjcnb** [comment]
@pencilcap123 Hi, thank you for your feedback, Can you submit a pull reqeust to fixed it?

**Comment by zjcnb** [comment]
> jdbc:mysql://127.0.0.1:3306/aa?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&sessionVariables=ob_query_timeout=30000000,ob_read_consistency='weak'

Yeah, you are right. But it 's right if you not use `DistSQL`.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/33742097/174610437-4997f5bf-b988-4d9f-8b4d-6716e283cbcc.png">


Use `DistSQL` : 

```
ADD RESOURCE ds0 (
    URL="jdbc:mysql://127.0.0.1:3306/ds0?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&sessionVariables=ob_query_timeout=30000000,ob_read_consistency='weak'",
    USER=root,
    PASSWORD=123456
);
```

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/33742097/174610113-745878bf-d35f-4f10-a4c8-77c88395c6ba.png">

So, i think `DistSQL` ignores `''`, if you are interested, you can try to modify `DistSQL` Parse.
