### ISSUE TITLE
After the program starts, the first execution of sql is very slow

### ISSUE THREAD

**Issue by SmallBeautifulPig** [apache/shardingsphere#18369]
when use sharding-jdbc 5.1.1 

After the program starts, the first execution of sql is very slow， it takes about 5-6 seconds.

I can't find a reasonable configuration from the official website to solve this problem

**Comment by wszpwsren** [comment]
same

**Comment by jsgjj111** [comment]
me too...

**Comment by terrymanu** [comment]
What is the SQL details, can you use APM tools to locate the SQL parse and execute spend?

**Comment by terrymanu** [comment]
The SQL need to be parsed to AST for 1st received and will put into cache.
SQL warm up feature can let user indicated SQLs before the application start-up.
If anyone want to do it, we can discuss the desgin.

**Comment by csonezp** [comment]
I want to try it

**Comment by mintheon** [comment]
me too!
