### ISSUE TITLE
DatabaseDiscovery needs to support memory and standby mode

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18381]
### Describe the feature you would like.
Currently DatabaseDiscovery can only take effect in cluster mode, I hope it can also take effect in memory and standalone mode.

**Comment by zjcnb** [comment]
Yeah, that a good idea. i think it should be provide `SPI` interface in `db-discovery` module, and users can use different JOBs according to their own needs. 

I will do it.
