### ISSUE TITLE
Failed to execute goal on project shardingsphere-integration-test-suite

### ISSUE THREAD

**Issue by cheese8** [apache/shardingsphere#18417]
## Bug Report

`mvn clean compile package install -Dmaven.javadoc.skip=true -Drat.skip=true -Dmaven.test.skip=true -U`

[ERROR] Failed to execute goal on project shardingsphere-integration-test-suite: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-integration-test-suite:jar:5.1.3-SNAPSHOT: The following artifacts could not be resolved: org.apache.shardingsphere:shardingsphere-integration-test-fixture:jar:tests:5.1.3-SNAPSHOT, org.apache.shardingsphere:shardingsphere-integration-test-env:jar:tests:5.1.3-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-integration-test-fixture:jar:tests:5.1.3-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.3-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
The whole project

**Comment by terrymanu** [comment]
But the CI is success.

**Comment by cheese8** [comment]
> But the CI is success.

Yeah, I will reproduce it and investigate the reasons.
