### ISSUE TITLE
ExportDatabaseConfigurationHandler need to be improved

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18437]
The export data in ExportDatabaseConfigurationHandler is in file: `shardingsphere-proxy/shardingsphere-proxy-backend/src/test/resources/expected/export-database-configuration.yaml`. The content of the export data is not good engough.

1. `!!set` should to be removed in line 33 
2. `?` should to be removed in line 34
3. `''` value of none should be removed in line 40
4. `null` value of default_scaling should be removed in line 45
5. : `null` should be removed in line 59

**Comment by mabaiwan** [comment]
Can I work on this issue?

**Comment by zjcnb** [comment]
> Can I work on this issue?

Welcome.
