### ISSUE TITLE
Add assertion for CreateTrafficRuleHandlerTest and AlterTrafficRuleHandlerTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18449]
- [x] Add created rule assertion for `CreateTrafficRuleHandlerTestassertExecute()`
- [x] Add altered rule assertion for `AlterTrafficRuleHandlerTest.assertExecute()`

**Comment by MichaelDeSteven** [comment]
Can I try this task？

**Comment by terrymanu** [comment]
@MichaelDeSteven  Sure, go ahead please
