### ISSUE TITLE
Spring Data JPA occure Exception with Blob value

### ISSUE THREAD

**Issue by LGAKing** [apache/shardingsphere#18452]
I am using Spring Data JPA, and have declared Entity. Among them, some fields use the Object (specific type, eg. ItemDTO) type declaration in Entity, and use Blob storage in the database. When Sharding is not integrated, CRUD can be performed normally. After integrating Sharding, an exception "unsupported data type" will appear when inserting Blob data. I don't know if this problem will be fixed, or if the Entity field type needs to be changed to Clob or byte[].

Sharding Vesion: 5.1.1

DB Version:  Oracle 19c

thks~

**Comment by terrymanu** [comment]
Can you provide the full stack trace?

**Comment by LGAKing** [comment]
> Can you provide the full stack trace?

thks ur reply!

**Comment by terrymanu** [comment]
Can you format your log, remove the `\r\n\t`? It is not easy to read
