### ISSUE TITLE
The introduction to databaseName and other properties of SpringBoot Starter is missing from the documentation

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#18499]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- I noticed that in https://github.com/apache/shardingsphere/pull/16790,  `spring.shardingsphere.schame.name` has been replaced by `spring.shardingsphere.database.name`. The documentation was also updated in https://github.com/apache/shardingsphere/pull/17760 . 

- But I noticed that only the `Spring namespace` in the documentation embodies this change. 

- Compared to https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/spring-namespace/ , https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/spring-boot-starter/ does not describe the related properties.
- 
![image](https://user-images.githubusercontent.com/20187731/174930003-a5d0c42b-403c-4ab3-a145-445759fc87ac.png)
- 
![image](https://user-images.githubusercontent.com/20187731/174930053-0f18a8e0-51a2-4ff6-b481-bfa037d846cf.png)

- Also, in https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/, schemaName is still used.

- 
![image](https://user-images.githubusercontent.com/20187731/174929493-4208e9e0-51b2-47b5-8296-39d5149ef385.png)

- Is this a deliberate downsizing of the concept？

**Comment by zjcnb** [comment]
ShardingSphere compatible `database name` and `schema name`.  You can refer to #14004 for the reason of adjustment

**Comment by linghengqian** [comment]
@zjcnb Should the documentation be consistent in usage or indicate the existence and meaning of both properties? I don't think it will be the norm to include property descriptions for only one of them, or not to specify them in the documentation.

**Comment by strongduanmu** [comment]
Hi @linghengqian, thank you for your feedback. I think these documents should adjust schemaName to databaseName. At present, ShardingSphere maintains the configuration of schemaName for compatibility, and will only support databaseName in the future, so the document should be updated to databaseName. Can you submit a pr to correct the document?

**Comment by linghengqian** [comment]
> Hi @linghengqian, thank you for your feedback. I think these documents should adjust schemaName to databaseName. At present, ShardingSphere maintains the configuration of schemaName for compatibility, and will only support databaseName in the future, so the document should be updated to databaseName. Can you submit a pr to correct the document?

I've been busy in recent weeks and it's hard to find time to revise the documentation. It would be great if a friend could submit a PR associated with this Issue.
