### ISSUE TITLE
Confusion about changes to ShardingSphereDataSource and ContextManager

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#18494]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- I'm confused about some changes to `ShardingSphereDataSource` and `ContextManager` in `ShardingSphere 5.1.2`. In https://github.com/apache/shardingsphere/pull/17860 , removed `org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource` 's get method of the properties makes it impossible to get `org.apache.shardingsphere.mode.manager.ContextManager` directly through `ShardingSphereDataSource#getContextManager`, but must be obtained through the following method reflection.

```java
@SneakyThrows(ReflectiveOperationException.class)
public static ContextManager getContextManager(final ShardingSphereDataSource dataSource) {
    Field field = ShardingSphereDataSource.class.getDeclaredField("contextManager");
    field.setAccessible(true);
    return (ContextManager) field.get(dataSource);
}
```

- What's the point of this change? I'd be grateful if someone could help answer this question.

- For `org.apache.shardingsphere.mode.manager.ContextManager`, its changes are not reflected much in the Realease Note. 
    - In https://github.com/apache/shardingsphere/pull/16919, `getMetaData(final String schemaName)` was changed to `getMetaData(final String databaseName)`, the signature changed. 
    - Then in https://github.com/apache/shardingsphere/pull/17792 , the function signature was changed from `public ShardingSphereMetaData getMetaData(final String databaseName) )` is changed to `public ShardingSphereDatabaseMetaData getDatabaseMetaData(final String databaseName)`, and the method name is changed. 
    - In https://github.com/apache/shardingsphere/pull/17817 , `public ShardingSphereDatabaseMetaData getDatabaseMetaData(final String databaseName)` becomes `public ShardingSphereDatabase getDatabaseMetaData(final String databaseName)`, the return body changes. 
    - In https://github.com/apache/shardingsphere/pull/17958 , `public ShardingSphereDatabase getDatabaseMetaData(final String databaseName)` becomes `public ShardingSphereDatabase getDatabase (final String databaseName)`, the method name changed again. 
    - I noticed that this parameterized constructor `getDatabase(final String databaseName)` ended up in https://github.com/apache/shardingsphere/pull/17983 has been removed. 

- This finally changes in ShardingSphere 5.1.2, getting `Collection<org.apache.shardingsphere.infra.config.RuleConfiguration>` which is hard to see in the Release Note. From
```java
Collection<RuleConfiguration> testRuleConfigList = shardingSphereDataSource.getContextManager()
        .getMetaDataContexts()
        .getMetaData(schemaName)
        .getRuleMetaData()
        .getConfigurations();
```
- to (Now `getContextManager()` needs to be obtained by reflection of custom function.)

```java
Collection<RuleConfiguration> testRuleConfigList = getContextManager(shardingSphereDataSource)
                .getMetaDataContexts()
                .getMetaData()
                .getDatabases()
                .get(databaseName)
                .getRuleMetaData()
                .getConfigurations();
```
  
- Given that the changes to `ContextManager` are so complex, is it possible to add a description of the API changes somewhere in the public article or documentation?

- A derived question is why `org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSourceTest#getContextManager(final ShardingSphereDataSource dataSource)`, throws `java.lang.ReflectiveOperationException` instead of `java.lang.NoSuchFieldException` ? Throws a wider range of exceptions It seems that the exception message is not intuitive, am I understanding it right?

**Comment by terrymanu** [comment]
Metadata module is still being adjusted.

**Comment by linghengqian** [comment]
Wow, I'm looking forward to what the metadata module will look like in the end.

**Comment by rujiaxiao** [comment]
I have the same confuse  when i upgrade sharding version from 5.1.1 to 5.2.1，i can‘t start my application because of  a lot of can‘t find class or function，since like`ShardingSphereDataSource.getContextManager()`.
Thanks for @linghengqian provide some advice function：`getContextManager(final ShardingSphereDataSource dataSource)`，it
 work now.
I hope the version upgrade could friendly to the lower version,thanks a lot.

**Comment by linghengqian** [comment]
> I have the same confuse when i upgrade sharding version from 5.1.1 to 5.2.1，i can‘t start my application because of a lot of can‘t find class or function，since like`ShardingSphereDataSource.getContextManager()`. Thanks for [@linghengqian](https://github.com/linghengqian) provide some advice function：`getContextManager(final ShardingSphereDataSource dataSource)`，it work now. I hope the version upgrade could friendly to the lower version,thanks a lot.

I'm not currently handling any follow-up issues to this one because these Java APIs appear to be still dynamically changing. Making DistSQL available on ShardingSphere JDBC would be a better follow-up to this issue. DistSQL itself seems quite stable. However, I'm not handling related issues or drafts.
