### ISSUE TITLE
Insert statement does not support sharding table routing to multiple data nodes.

### ISSUE THREAD

**Issue by emmataobao** [apache/shardingsphere#18513]
![1655884625423](https://user-images.githubusercontent.com/46233536/174975626-0ad407ee-f100-4129-9bbd-33406d3133b1.png)
![1655884691419](https://user-images.githubusercontent.com/46233536/174975884-f8ddb71e-bb89-4836-a11b-f3bad8757b49.png)

**Comment by terrymanu** [comment]
I just set it as invalid because of the author close the issue without any reason.
