### ISSUE TITLE
Is mariadb galera cluster supported?

### ISSUE THREAD

**Issue by nagae-memooff** [apache/shardingsphere#18543]
Can I use  a mariadb galera cluster(multi master mode) as a dataresource node? 
The document only mentioned that Mysql Group Replication(multi master mode) is not supported.

**Comment by zjcnb** [comment]
@nagae-memooff Do you use the `db-discovery` feature?

**Comment by nagae-memooff** [comment]
> @nagae-memooff Do you use the `db-discovery` feature?

I don't use it.

**Comment by terrymanu** [comment]
Not yet, but can do the mariadb galera cluster  implementation by yourself. `MGRMySQLDatabaseDiscoveryProviderAlgorithm` is the best example.

**Comment by terrymanu** [comment]
I just open it as `good amateur issue`

**Comment by terrymanu** [comment]
The database discovery feature has been remove form ShardingSphere, please ref #24486
