### ISSUE TITLE
ShardingSphere-Proxy listen on specified addresses

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#18554]
### Is your feature request related to a problem?

For security.

### Describe the feature you would like.

Support listening on specific addresses like the MySQL or PostgreSQL.

Netty bind: https://stackoverflow.com/questions/30957207/netty-listen-on-several-addresses-ports-with-a-single-serverbootstrap

**Comment by TeslaCN** [comment]
The API of binding addresses could be:

```bash
bin/start.sh -h 127.0.0.1,192.168.1.1 -p 13306 -c /path/to/conf
```

```
-h  Bind addresses, can be IPv4, IPv6, hostname. In
    case more than one address is specified in a
    comma-separated list. The default value is '0.0.0.0'.
-p  Bind port, default is '3307', which could be changed in server.yaml
-c  Path to config directory of ShardingSphere-Proxy, default it 'conf'
```

**Comment by csonezp** [comment]
I'd like to try that.

**Comment by TeslaCN** [comment]
@csonezp Welcome!

**Comment by csonezp** [comment]
@TeslaCN Hi，the options [-h addresses] is already used for print_usage, should it be replaced by "-addr" ?

**Comment by csonezp** [comment]
> @TeslaCN Hi，the options [-h addresses] is already used for print_usage, should it be replaced by "-addr" ?

or "-host" ?

**Comment by TeslaCN** [comment]
How about naming it -a?

**Comment by csonezp** [comment]
> How about naming it -a?

ok, that's a good solution
