### ISSUE TITLE
sqlserver select top 10 xxx from table_ where xxx

### ISSUE THREAD

**Issue by wuguowei19880907** [apache/shardingsphere#18561]
java8  sharding 5.1.0
database:sqlserver 2012
spring boot +jpa

I use spring boot +sqlserver + sharding5.1.0 , the sql is
```
SELECT TOP 20 configdo0_.id AS id1_9_, configdo0_.category AS category2_9_, configdo0_.name AS name3_9_, configdo0_.note AS note4_9_, configdo0_.updated_at AS updated_5_9_, configdo0_.value AS value6_9_ FROM config configdo0_ WHERE configdo0_.category = ? ORDER BY configdo0_.id ASC
```
the **name** field is encrypt,but sharding cannot recongnize it.
When I debug the error,I found that the **selectstatment** cannot be parsed correct!
![微信图片_20220624134228](https://user-images.githubusercontent.com/19338820/175470161-b2fed234-128b-4e71-9be8-c43b7b52d708.png)

**Comment by terrymanu** [comment]
What is your configuration?

**Comment by wuguowei19880907** [comment]
if i change the encrypt rules ,it work well.

**Comment by terrymanu** [comment]
Your configuration please

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
