### ISSUE TITLE
SQL route can optimize

### ISSUE THREAD

**Issue by wt-better** [apache/shardingsphere#18584]
### Describe the feature you would like.

Eg：`select * from tbl_order where order_id in (1,2)`

`tbl_order` is sharding  table, two database: database01, database02; two tables: tbl_order_01, tbl_order_02 .

**shardingKey** is `order_id`，database and table sharding rule all `order_id%2` .

The current  will produce four `shardingsphere.RouteUnit`, respectively: <databse01:tbl_order_01>, <databse01:tbl_order_02>, <databse02:tbl_order_01>, <databse02:tbl_order_02> .

I think two routeUnit `shardingsphere.RouteUnit`：<databse01:tbl_order_01> 、<databse02:tbl_order_02>  ok,this optimize can reduce sql execute count and result merge cost.

version: shardingsphere 5.1.1, The following code:

`org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine#route0`

Further, the binding algorithm is proposed，when datbase and table sharing rule and value consistent，we can reduce once route 
calculate cost。

**Comment by terrymanu** [comment]
Yes, it is a good idea, could you provide the pseudo code or draw a diagram to make your idea more clear?

**Comment by cheese8** [comment]
I am try to improve this.

**Comment by wt-better** [comment]
Thanks a lot, expect !

**Comment by cheese8** [comment]
> Yes, it is a good idea, could you provide the pseudo code or draw a diagram to make your idea more clear?

Please review the InlineShardingAlgorithm proposal. @terrymanu

**Comment by terrymanu** [comment]
It better to design first

**Comment by cheese8** [comment]
![image](https://user-images.githubusercontent.com/25882819/177003372-1711f468-a6df-40a0-accb-4dca116e9296.png)

**Comment by wt-better** [comment]
please attent sharding values, not only sharding strategy.



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/02/2022 21:41 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [apache/shardingsphere] SQL route can optimize (Issue #18584) |

**Comment by cheese8** [comment]
Can you describe your scene in detail to show us why database and table sharding rule are the same, for example all order_id%2. 
@wt-better

**Comment by wt-better** [comment]
database and table rule in same is very common on my company.

---- Replied Message ----
***@***.***>Date07/02/2022 ***@***.******@***.******@***.***>SubjectRe: [apache/shardingsphere] SQL route can optimize (Issue #18584)
Can you describe your scene in detail to show us why database and table sharding rule are the same, for example all order_id%2.
@wt-better

**Comment by cheese8** [comment]
> database and table rule in same is very common on my company.
> […](#)
> ---- Replied Message ---- ***@***.***>Date07/02/2022 ***@***.******@***.******@***.***>SubjectRe: [apache/shardingsphere] SQL route can optimize (Issue #18584) Can you describe your scene in detail to show us why database and table sharding rule are the same, for example all order_id%2. @wt-better — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Can you describe in detail the scene in your company how to shard the database and table? We need to estimate whether these scenarios are general or customized requirements.

**Comment by cheese8** [comment]
No further response closed.
