### ISSUE TITLE
Remove deprecated CountInstanceRulesHandler and CountInstanceRulesStatement

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18583]
CountInstanceRulesHandler breaks the pluggable design, nobody need to know all dynamic plugins. 
We should split the count logic push down to each concrete rule.

The handler should be:

- [ ] CountSingleTableRuleHandler
- [ ] CountShardingRuleHandler
- [ ] CountReadwriteSplittingRuleHandler
- [ ] CountDatabaseDiscoveryRuleHandler
- [ ] CountEncryptRuleHandler
- [ ] CountShadowRuleHandler

and others...

The DistSQL and related SQL statement `CountInstanceRulesStatement` need to be removed too.

The SQL and SQL statement should be:

- [ ] `COUNT SINGLE_TABLE RULE (FROM databaseName)?` and CountSingleTableRuleResourceStatement
- [ ] `COUNT SHARDING RULE (FROM databaseName)?` and CountShardingRuleResourceStatement
- [ ] `COUNT READWRITE_SPLITTING RULE (FROM databaseName)?` and CountReadwriteSplittingRuleResourceStatement
- [ ] `COUNT DATABASE_DISCOVERY RULE (FROM databaseName)?` and CountDatabaseDiscoveryRuleResourceStatement
- [ ] `COUNT ENCRYPT RULE (FROM databaseName)?` and CountEncryptRuleResourceStatement
- [ ] `COUNT SHADOW RULE (FROM databaseName)?` and CountShadowRuleResourceStatement

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by terrymanu** [comment]
Great

**Comment by LeeGuoPing** [comment]
@terrymanu count instance belong to RAL, the  concrete rules belong to RAL or RQL? I think it belong to RQL

**Comment by RaigorJiang** [comment]
I think RQL is better.

**Comment by RaigorJiang** [comment]
Hi @LeeGuoPing,
This issue lists some tasks, are they all completed? Or can you mark the completed parts?

**Comment by LeeGuoPing** [comment]
@RaigorJiang completed all

**Comment by RaigorJiang** [comment]
> @RaigorJiang completed all

Well, thank you!
