### ISSUE TITLE
Optimize sneakyaml export DatabaseConfiguration

### ISSUE THREAD

**Issue by mabaiwan** [apache/shardingsphere#18596]
The yaml exported by the database configuration contains `:null` and `?`

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/77398366/175783569-8d83bd85-681a-4329-a2a7-5adb10b30077.png">

Now, the problem is solved by string replacement. We hope that it can be eliminated by snakyaml.

unit testing: `ExportDatabaseConfigurationHandlerTest#assertExecute`

**Comment by terrymanu** [comment]
Welcome who familiar for YAML to pick up the issue.
