### ISSUE TITLE
Add test cases of InstanceMetaData

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18591]

**Comment by kvaithin** [comment]
Hi could I pick this up pls.

**Comment by kvaithin** [comment]
Hi, did not reset the counter as suggested. As it comes into play only in one of the tests and not affecting others. 
Avoided it as would have had to use meddle with reflection to reset it considering the `ATOMIC_LONG` value is private.

Please do advice if the counter reset is a must. And if so if we are open to making `ATOMIC_LONG` package private in that case to ease the reset. Thanks.

**Comment by terrymanu** [comment]
Hi, the class is renamed to InstanceMetaData which is an interface, and the test cases are completed. So I just close the issue.
