### ISSUE TITLE
Single table must check duplicate tables

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18604]
There is `check-duplicate-table-enabled` in global properties which for single table loading check, I think this is incorrect.

The logic table names can not same in same logic database.schema in ShardingSphere.

It should `THROW EXCEPTION` if the same single table name in same database.schema when ShardingSphere startup.

This is the basic rule in database system with `database.schema.table` should be unique. ShardingSphere should not break it.

**Comment by strongduanmu** [comment]
Yes, I agree with you, ShardingSphere should guarantee the uniqueness of the table in same schema.
