### ISSUE TITLE
shardingsphere 5.1.1 insert into  select    select logic table name  can't to convert actual table name error  ora-00942

### ISSUE THREAD

**Issue by yunfei-yimao** [apache/shardingsphere#18632]
inset into ta_trade_request(...) select ... from tr_collect_trade_request

**Comment by yunfei-yimao** [comment]
![微信图片_20220627172644](https://user-images.githubusercontent.com/108256627/175908493-a9b647ca-2d42-4dc7-9da1-a165c7644fe7.jpg)

**Comment by linghengqian** [comment]
Why are you presenting the configuration in this way? If you are in a corporate intranet environment, do not send out the map of the intranet to harm people.

**Comment by yunfei-yimao** [comment]
other  query  ， aggregate function  can support,  but  insert  into logic table  select  logic table   ,error, ora-00942 表不存在，please  help!

**Comment by linghengqian** [comment]
You provided very little information. The information you need to add should at least cover all of what is needed for the question template. A unit test that can reproduce will obviously explain what you are expressing.

**Comment by yunfei-yimao** [comment]
![微信图片_20220704141557](https://user-images.githubusercontent.com/108256627/177092895-a2f865a4-1965-4ed0-bae3-cf3290146c96.png)
![微信图片_20220704141615](https://user-images.githubusercontent.com/108256627/177092901-01f63c24-61bd-442c-9fc3-d9828aadcf71.png)

**Comment by linghengqian** [comment]
The information you provide is not enough to be understood, because you are not showing log and more information, nor are you providing a replicable demo. Use h2database to provide examples that make people more understand what your issue wants to express.

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
