### ISSUE TITLE
Delete support for branch transaction on proxy.

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#18636]
Reason for deletion：
1.  `MANUALXA` in TransactionType does not conform to ShardingSphere's design specification
2. `TransactionXAHandler` does not conform to ShardingSphere's design specification.

**Comment by terrymanu** [comment]
Please see my comment in #14130.
I do not agree to add transaction type `MANUALXA` too, I don't think this is a good design enough.

**Comment by zhfeng** [comment]
I just wonder that what is the `ShardingSphere's design specification` and how `TransactionXAHandler` breaks it?

**Comment by zhfeng** [comment]
I think we need more discusstion and feel free to setup a meeting if you like.

**Comment by terrymanu** [comment]
The goal of ShardingSphere's transaction module is in official document[1] for long time .

The MANUALXA does not design for resolve the same problem, It just support XA protocol in the frontend of ShardingSphere which is database protocol side, not storage side.

So I don't think it is a good design enough. It is very confused for mix protocol side and storage side.

LOCAL, XA and BASE are types of transaction, I don't think MANUALXA is the same abstract level with them.

[1] https://shardingsphere.apache.org/document/current/en/features/transaction/

**Comment by zhfeng** [comment]
I agree that `MANUALXA` is not a good name. But I still think it makes sense that `sharding-proxy` supports the XA statments in case which users want to contronl the transactions by themselves, e.g. involving in an external JTA transaction.

**Comment by terrymanu** [comment]
it is another task for supporting XA protocol in ShardingSphere.
TransactionType only focus on transactional storage.

**Comment by zhfeng** [comment]
Thanks @terrymanu and it should be great to support XA protocol. There are still some challenges in the recovery scenarioes. I'd like to be involved in this task and do you raise any issue for it?

**Comment by zhfeng** [comment]
Yeah, I understand and `XA protocol in SQL layer` was introudced by https://github.com/apache/shardingsphere/pull/14075. But I think we still need to handle `XAStatement` in `sharding-proxy` especially in the case of crash recovery happening in the multi backend databases. I think we don't have any test case for this scenario currently.

Anyway my +1 for improving the implementation of `TransactionXAHandler` but no just deleting it.

**Comment by terrymanu** [comment]
Yes, TransactionXAHandler could keep, and we need more improve on it.

**Comment by roodkcab** [comment]
no doubt that XA is stands for distribution transaction.
