### ISSUE TITLE
hint route cache invalidation

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#18631]
## Question
hint route：
/* ShardingSphere hint: dataSourceName= test */SELECT COUNT(*) AS total FROM account AS a
The result varies after multiple executions.
Found in the project.

**Comment by zhenglu8** [comment]
### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

**Comment by Bingai077** [comment]
ShardingSphere-Proxy

**Comment by Bingai077** [comment]
ShardingSphere-Proxy 5.1.0

**Comment by Bingai077** [comment]
Online environment (Docker environment publishing) application connection proxy will open multiple threads, resulting in inconsistent query data. Please tell me how to solve it

**Comment by Bingai077** [comment]
>ShardingSphere-Proxy 5.1.0   
 Online environment (Docker environment publishing) application connection proxy will open multiple threads, resulting in inconsistent query data. Please tell me how to solve it

**Comment by terrymanu** [comment]
This design break the ShardingSphere concept. User should not acre about the actual data source in DistSQL.
We will remove /* ShardingSphere hint: dataSourceName= XXX */ before 5.1.3 release.

**Comment by terrymanu** [comment]
Please see #18620
