### ISSUE TITLE
table name suffix duplicated in index name after scaling tables

### ISSUE THREAD

**Issue by nagae-memooff** [apache/shardingsphere#18661]
I'm using ShardingSphere-Proxy 5.1.1.

When I create a table with index, I found there is a table name suffix appended to the original index name.
It's OK, I know it is not a bug but a feature as HERE said: https://github.com/apache/shardingsphere/issues/17073.

But when I scale my data to new database instances, I found that the same table name suffix was appended again and exceed the 64 bytes index name limit.

For example:
my original create table sql:

```
CREATE TABLE `message_threads` (
...
  PRIMARY KEY (`id`),
  KEY `index_message_threads_on_id` (`id`),
  KEY `index_message_threads_on_starter_id` (`starter_id`)
)
```
and if I execute show create table on databases, it will be that:

```
Create Table: CREATE TABLE `message_threads` (
...
  PRIMARY KEY (`id`),
  KEY `index_message_threads_on_id_message_threads` (`id`),
  KEY `index_message_threads_on_starter_id_message_threads` (`starter_id`)
)
```

and If I try to scale the db to new database instances, It' ll raise a failure with this Error: 
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Identifier name 'index_message_threads_on_starter_id_message_threads_message_threads' is too long
```
![image](https://user-images.githubusercontent.com/4215831/176155730-4b795344-82a8-4987-a5dc-1fa378693fc6.png)

**Comment by RaigorJiang** [comment]
Duplecated with #17073.
