### ISSUE TITLE
Single table conflict occurred when i add master-slave resource by `DistSQL`

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#18664]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior

`Add resource` successful.

### Actual behavior

`ERROR 1104 (C1104): Can not process invalid resources, error messages are: [Single table conflict, there are multiple tables `admin` existed.].`

`ADD MASTER RESOURCE : `

```
ADD RESOURCE ds0 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=lsj,
    USER=root,
    PASSWORD=123456
);
```

`ADD SLAVE RESOURCE : `

```
ADD RESOURCE ds1 (
    HOST=127.0.0.1,
    PORT=3307,
    DB=lsj,
    USER=root,
    PASSWORD=123456
);
```

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/33742097/176172502-390062d1-1c7a-4554-b253-3f7ccb8b23a2.png">

**Comment by strongduanmu** [comment]
@zjcnb Thank you for your feedback. After discussion, we decided to delete the duplicate verification of the single table, and let the user ensure the uniqueness of single tables.
