### ISSUE TITLE
Other databases will not be displayed after distsql is executed

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#18676]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.3
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
When you change rules using distsql, other databases are not affected.
### Actual behavior
After using distsql to change rules, only the databases modified by the rules will be preserved after "show databases" is executed, and the rest will disappear.Only after restart will it return to normal。
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
When there are multiple databases, problems may occur after one of them executes distsql to configure fragmentation rules or data source rules.

**Comment by terrymanu** [comment]
What is your configuraton?
