### ISSUE TITLE
Add test case for OptimizerContext.addSchema()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18682]

**Comment by xuup** [comment]
hi, please assign this issue to me , i will finish it.

**Comment by xuup** [comment]
OptimizerContext has been refactor, maybe this issue should be modify?

**Comment by abhinav-koppula** [comment]
@terrymanu - OptimizerContext is now a pojo. Which class are we talking about here?

**Comment by strongduanmu** [comment]
> @terrymanu - OptimizerContext is now a pojo. Which class are we talking about here?

This class is currently being refactored, so I will close this issue and welcome to claim other issues from the community.
