### ISSUE TITLE
[DistSQL] READWRITE_SPLITTING RULES need to show `write_data_source_query_enabled` query results 

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#18687]
Hi community,

We recently refactor `readwrite-splitting` feature `API`, you can refer to #18587, #18629.

Currently showing results when you use `dynamic strategy` :

```
mysql> show readwrite_splitting rules from readwrite_splitting_db;
+--------------+-----------------------------+------------------------+------------------------+--------------------+---------------------+
| name         | auto_aware_data_source_name | write_data_source_name | read_data_source_names | load_balancer_type | load_balancer_props |
+--------------+-----------------------------+------------------------+------------------------+--------------------+---------------------+
| readwrite_ds | ms_group_0                  |     ds_0               |      ds_1,ds_2         |                    |                     |
+-------+------------------------------------+------------------------+------------------------+--------------------+---------------------+
```

It's missing the `write_data_source_query_enabled` parameter.

Task list :

- [ ] Modify `ReadwriteSplittingRuleQueryResultSet.class` to add `write_data_source_query_enabled` parameter.
- [ ] Fix `ReadwriteSplittingRuleQueryResultSetTest.class` unit test.
- [ ] Fix `shardingsphere-integration-test` module.

1. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rdl/dataset/empty_rules/alter_readwrite_splitting_rules.xml`
2. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rdl/dataset/empty_rules/create_readwrite_splitting_rules.xml`
3. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rdl/dataset/empty_rules/drop_readwrite_splitting_rules.xml`
4. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting/show_readwrite_splitting_rules.xml`
5. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/dbtbl_with_readwrite_splitting_and_encrypt/show_readwrite_splitting_rules.xml`
6. `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/dataset/readwrite_splitting/show_readwrite_splitting_rules.xml`

- [ ] Modify document

1. Refer to : https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/readwrite-splitting/

**Comment by chakkk309** [comment]
Hi, I want to have a try.

**Comment by chakkk309** [comment]
> > Hi, I want to have a try.
> 
> We need to finish it in 5.1.3 milestone, so we need to hurry.

OK, I'll sync the progress to finish on time.

**Comment by zhaojinchao95** [comment]
Ref : #18587
