### ISSUE TITLE
JDBCBackendConnection：proxy-db connection no rollback when application-proxy connection  is closed

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#18684]
### Which version of ShardingSphere did you use?
 5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
transaction rollback(proxy-db) when connection ( application-proxy) is closed
 
### Actual behavior
transaction no rollback(proxy-db) when connection ( application-proxy) is closed

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/20919316/176368125-9b7c3595-f0f1-4534-bdcb-ff44acbcc4de.png)

When the above figure is executed to step 4-6, the disconnection of the upstream connection triggers the channelInactive method of Netty. At this time, the resources in the JDBCBackendConnection are still empty. Because step 7 has not been started, the subsequent step 7 is executed after the resources are cleaned up, and the subsequent connection will remain there.

JDBCBackendConnection Whether to add a new status to control the addition of connections？

**Comment by TeslaCN** [comment]
Is it duplicated with https://github.com/apache/shardingsphere/issues/18634？
Step 7 is finished after channel inactive.

**Comment by git-chenhao** [comment]
> Is it duplicated with [https://github.com/apache/shardingsphere/issues/18634？](https://github.com/apache/shardingsphere/issues/18634%EF%BC%9F) Step 7 is finished after channel inactive, which may cause this issue.

thanks，same question~
