### ISSUE TITLE
SHARDINGSPHERE-JDBC 5.1.2 usage about jooq

### ISSUE THREAD

**Issue by xllove-moon** [apache/shardingsphere#18691]
## Question
A few days ago, we upgraded to the latest version 5.1.2 of shardingsphere-jdbc. 
In version 5.1.1, jooq is not included in Maven dependency, but we found some problems about the compatibility between jooq and springboot (our version is 2.3.12). 
After excluding jooq dependency, the service can now run normally in the test environment. our service uses readwrite-splitting and sharing-table function

The first problem is that when jooq is used with springboot AOP, it will cause a very slow startup bug. After testing, this problem can still be repeated in our service https://github.com/jOOQ/jOOQ/issues/5902
The second problem is that stackoverflowerror occurs at startup. We have to increase -Xss to solve it  https://github.com/jOOQ/jOOQ/issues/7994

** These problems seem to have nothing to do with shardingsphere JDBC. I wonder whether excluding jooq from Maven will affect the stable operation of shardingsphere JDBC？**

**Comment by terrymanu** [comment]
If using yaml, please config like this way to switch off jooq translator

```yaml
!SQL_TRANSLATOR
  type: NATIVE
```

**Comment by terrymanu** [comment]
I just update the doc to config SQL translator:

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/java-api/rules/sql-translator/
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-translator/
