### ISSUE TITLE
Does shardingsphere5.1.0 support "insert into... On duplicate key update..."?

### ISSUE THREAD

**Issue by beitengda** [apache/shardingsphere#18696]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by sandynz** [comment]
Hi @beitengda , it should be already supported. Could you help to supply how you reproduce this issue, you could use the issue template to submit.

**Comment by terrymanu** [comment]
No feedback, I just close it.
