### ISSUE TITLE
[DistSQL] Need to add `writeDataSourceQueryEnabled` paramter about RDL READWRITE_SPLITTING RULE

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#18695]
Hi community, 

We recently refactor `readwrite-splitting` feature `API`, you can refer to #18587, #18629.

So, we need to modify `RDL` about `READWRITE_SPLITTING RULE`. 

Now CREATE or ALTER Dynamic `READWRITE_SPLITTING RULE` DistSQL are : 

// Dynamic
```
CREATE READWRITE_SPLITTING RULE ms_group_1 (
AUTO_AWARE_RESOURCE=group_0
);
```

```
ALTER READWRITE_SPLITTING RULE ms_group_1 (
AUTO_AWARE_RESOURCE=group_1
);
```

Hope to adjust to : 

// Dynamic
```
CREATE READWRITE_SPLITTING RULE ms_group_1 (
AUTO_AWARE_RESOURCE=group_0,
WRITE_DATA_SOURCE_QUERY_ENABLED='true'
);
```

```
ALTER READWRITE_SPLITTING RULE ms_group_1 (
AUTO_AWARE_RESOURCE=group_1,
WRITE_DATA_SOURCE_QUERY_ENABLED='false'
);
```

- [ ] Adjust `shardingsphere-readwrite-splitting-distsql-handler` RDLStatement.g4 file.
- [ ] Modify `CreateReadwriteSplittingRuleStatementUpdater.class` and `AlterReadwriteSplittingRuleStatementUpdater.class`.
- [ ] Modify document

1. https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/

- [ ] Fix shardingsphere-integration-test module.

**Comment by yx9o** [comment]
I want to try.

**Comment by zjcnb** [comment]
> I want to try.

Nice, assigned

**Comment by yx9o** [comment]
@zjcnb Hi, in dynamic syntax, is WRITE_DATA_SOURCE_QUERY_ENABLED required or optional?

**Comment by zjcnb** [comment]
> @zjcnb Hi, in dynamic syntax, is WRITE_DATA_SOURCE_QUERY_ENABLED required or optional?

It 's optional

**Comment by zhaojinchao95** [comment]
Ref : https://github.com/apache/shardingsphere/issues/18587
