### ISSUE TITLE
When the first table of the sharding table does not exist,there is no tips

### ISSUE THREAD

**Issue by GodKerwin** [apache/shardingsphere#18707]
![图片](https://user-images.githubusercontent.com/32355479/176436280-f8c62c8e-2599-4247-a3ba-cb4f4ba063dc.png)
![图片](https://user-images.githubusercontent.com/32355479/176436464-a032ed1e-713b-4c34-9cff-a2658bbd2e72.png)

**Comment by strongduanmu** [comment]
Why does the sharding table not exist?

**Comment by GodKerwin** [comment]
> The business only needs half a year of data, and the DBA will regularly clean up the data over half a year

**Comment by strongduanmu** [comment]
If you delete some sharding tables, then you need to modify the sharding rules at the same time to make them consistent.

**Comment by GodKerwin** [comment]
> 
OK, Got it! I suggest outputting some logs when the schema cannot be queried, because it is too hidden.
