### ISSUE TITLE
分片算法问题

### ISSUE THREAD

**Issue by zzl14273119** [apache/shardingsphere#18726]
自动分片算法中的基于分片容量的范围分片算法
场景：3个分片，lower=3，upper=8，volume=5
问题：当upper-lower=vloume的值的时候，插入100条数据，为什么前2个分片按照分片数据量volume的值，剩下多出来的数据都会被插入到最后一个分片中，即分片一有3条数据，分片二有5条数据，剩下的全部在分片三中？

**Comment by strongduanmu** [comment]
@zzl14273119 Please translate this issue to English.
