### ISSUE TITLE
Partition algorithm problem

### ISSUE THREAD

**Issue by zzl14273119** [apache/shardingsphere#18737]
Range partition algorithm based on partition capacity in automatic partition algorithm

Scenario: 3 slices, lower=3, upper=8, volume=5

Question: when 100 pieces of data are inserted, when the upper value minus the lower value equals the vloume value, why are the remaining data in the first two slices inserted into the last slice according to the volume value of the slice data volume, that is, slice 1 has 3 pieces of data, slice 2 has 5 pieces of data, and all the rest is in slice 3?

**Comment by RaigorJiang** [comment]
Hi @zzl14273119 
Your description is a bit abstract, can you use the issue template to provide detailed information?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
