### ISSUE TITLE
JDBCBackendConnection：proxy-db connection auto commit when application-proxy connection break

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#18734]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
transaction rollback(proxy-db) when connection ( application-proxy) break

### Actual behavior
transaction auto commit(proxy-db) when connection ( application-proxy) break，This will result in inconsistent data

![image](https://user-images.githubusercontent.com/20919316/176640984-ac5d13be-2ce2-4a37-92ec-787359306770.png)

### Reason analyze (If you can)
When the above figure is executed to step 4-6, the disconnection of the upstream connection triggers the channelInactive method of Netty. At this time, JDBCBackendConnection will clear connectionPostProcessors
<img width="809" alt="image" src="https://user-images.githubusercontent.com/20919316/176641343-ad682ac5-c4a6-4ae8-864b-d92fd7501ad4.png">
So, step 2 the stored a will be deleted.
This causes the transaction to be automatically committed after step 10 is completed，Not as expected rollback！

**Comment by git-chenhao** [comment]
I can solve this problem. I will send PR later

**Comment by TeslaCN** [comment]
> I can solve this problem. I will send PR later

Welcome! Assigned.

**Comment by TeslaCN** [comment]
Close via #18750.
