### ISSUE TITLE
哪里能看版本的更新日志呀

### ISSUE THREAD

**Issue by yunmengmeng** [apache/shardingsphere#18739]
英文不好，就不写英文了
现在最新都5.1.2版本了，官网上也没有说明当前是哪个版本的文档，主要是我看官网上写不支持savePoint，可是5.1.1开始就已经支持了，如果能说明版本，以及有一个版本更新日志文档岂不是更好

**Comment by strongduanmu** [comment]
You can refer release notes——https://github.com/apache/shardingsphere/releases.
