### ISSUE TITLE
Handling SET statement in ShardingSphere-Proxy

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#18738]
### Which version of ShardingSphere did you use?

5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Consider removing BroadcastDatabaseBackendHandler

If we execute SQL (SET statement) like the following, `BroadcastDatabaseBackendHandler` will execute SQL in all data sources of all logic databases (schemas).
```sql
set sql_mode = ''
```

Why shouldn't Proxy broadcast SQL to all logic data sources?
- It is expensive if there are too many data sources.
- PostgreSQL's connection is created with fixed database, which cannot be changed on the fly.
- If the SET statement worked in session scope, the connections used to execute the SQL will be returned to data sources, which pollutes connections in data sources. This issue cannot cure this problem, but may reduce the impact of pollution. 

### After removed

Define a SPI interface to check whether the Proxy should passthrough variables in SET statement to data sources (a whitelist written in codes).

1. Except for the statements that need to be specially processed (autocommit, etc.), the Proxy does not do any actual operations for parameters that are not in the whitelist;
2. (For MySQL) SET GLOBAL / PERSIST / PERSIST_ONLY in the whitelist is fully routed in the current logic database. If the current logic database is null, no actual operation is performed; (the `BroadcastDatabaseBackendHandler` can be removed)
3. The SET SESSION parameter in the whitelist:
  - Putting the SET statement into the playback collection, just like how the Proxy handles the `begin`;
  - Neither acquire any new connections, nor release existing connections if in a transaction;
  - When executing a SET statement in a transaction, the existing connection needs to traverse and execute the SET statement;
  - All connections are not directly returned to the connection pool after use (client disconnection, transaction end, etc.) and need to be destroyed.
4. (For MySQL) SET @user-defined variable handling refers to 3;
5. When the SET operation target value is default, clear the SET SESSION in the playback set;
6. (For PostgreSQL) RESET operation refers to 5;
7. (For PostgreSQL) SET LOCAL transaction-level scope is not currently supported.

How to evict the connection?
- HikariCP provides method `com.zaxxer.hikari.HikariDataSource#evictConnection`
Or we could execute `RESET` instead of evicting when closing connections for less network overhead.

**Comment by wuwen5** [comment]
@TeslaCN `5.1.3` It is not released. Is it released in `5.2.0`?

**Comment by strongduanmu** [comment]
@wuwen5 Yes, the latest version is `5.2.0`. Currently, there is a bug in github, we cannot update 5.1.3 to 5.2.0, we will try to update milestone again after this bug is fixed.
