### ISSUE TITLE
Refactor `ImportDatabaseConfigurationHandler` to only allow imports when database is empty

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#18746]
Hi community,

We have a pair of statements in DistSQL for export and import configuration, they are:
- EXPORT DATABASE CONFIGURATION
- IMPORT DATABASE CONFIGURATION
> https://github.com/apache/shardingsphere/pull/15069
https://github.com/apache/shardingsphere/pull/16162

Among them, there may be some problems in the processing of `IMPORT`:
1. When the data sources already exist in the metadata, the current practice is to merge the imported ones, but the removed resources are not well closed, which may lead to connection leakage;
2. When a configuration already exists, it is difficult to tell whether the user wants to merge or replace completely;
3. Refer to some other databases, hope the target is clean when importing, such API is easier to understand.

Therefore, I recommend adjusting the implementation of `ImportDatabaseConfigurationHandler` to only allow imports if the current database's configuration is empty.

If anyone wants to try it, please leave a comment on this issue.

**Comment by yx9o** [comment]
Let me try.

**Comment by RaigorJiang** [comment]
@yx9o Thank you!
