### ISSUE TITLE
The original data source may not be closed after alter resource

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#18747]
ContextManager.alterResource :

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/60651792/176719267-d4de3ff8-a153-4dfa-89c6-b4e3bacd8aaf.png">

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/60651792/176719570-72a3687b-65d6-4363-b1a6-e9466f10159d.png">

**Comment by strongduanmu** [comment]
Hi @menghaoranss , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by zhaojinchao95** [comment]
The problem are fixed in `master` branch, so i will close it.
