### ISSUE TITLE
In one config, can config two - !SHARDING bug

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18755]
### Which version of ShardingSphere did you use?

ShardingSphere-Proxy?

I add two '! Sharding', proxy can start. I think this situation should not allow startup.
<img width="729" alt="企业微信截图_19b36e3f-39c9-4ecf-9313-a8dc9b5170a7" src="https://user-images.githubusercontent.com/26433395/176826767-57dee3ae-97db-43a4-9a2e-2aece515a49f.png">

![image](https://user-images.githubusercontent.com/26433395/176826815-04c57943-5278-40e9-95bd-f9425315b636.png)

**Comment by zhenglu8** [comment]
To reproduce this issue, could you please provide:

### Which version of ShardingSphere did you use?

**Comment by natehuangting** [comment]
@zhenglu8 ShardingSphere Proxy 5.1.3

**Comment by terrymanu** [comment]
Yes, we need to check unique for each rule.
It can be prevent by configuration, so I just set the issue as `good amateur issue`.

**Comment by LeeGuoPing** [comment]
May I have a try

**Comment by natehuangting** [comment]
> May I have a try

@LeeGuoPing Yeah. If you can, handle it.
