### ISSUE TITLE
shardingsphere 5.11 sharding-jdbc- orchestration  Maven JAR package dependencies

### ISSUE THREAD

**Issue by xiaojiaoshou** [apache/shardingsphere#18769]
I want to upgrade version, use Sharing-JDBC version 5.11, use ZooKeeper as configuration center and service Orchestration integration. The JAR package dependencies that need to be integrated are not found in the documentation for version 5.11 or in the demo. Where are the instructions?

**Comment by terrymanu** [comment]
Document is here: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/

**Comment by xiaojiaoshou** [comment]
Another question.does shardingsphere 5.0 and later versions support shardingshardingsphere UI? I don't see a version supported by shardingshardingsphere UI after shardingsphere 5.0 and 5.0?or shardingsphere-ui(5.0.0-alpha)  support ?
