### ISSUE TITLE
sharding-jdbc-spring-boot-starter 4.1.1 is latest in Maven Central

### ISSUE THREAD

**Issue by jason-lindholm** [apache/shardingsphere#18790]
https://mvnrepository.com/artifact/org.apache.shardingsphere/sharding-jdbc-spring-boot-starter

Curious if this is an oversight? 

I'd like to try the latest spring-boot-starter from maven central if possible.

**Comment by terrymanu** [comment]
The name of sharding-jdbc is changed to shardingsphere-jdbc.
Please find here[1] for version 5.x

[1] https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core-spring-boot-starter/5.1.2

**Comment by jason-lindholm** [comment]
thank you!
