### ISSUE TITLE
Missing document of ShardingSphere JDBC only can load single logic database

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18794]
The reason of ShardingSphere JDBC only can load single logic database is do not want load all customized algorithm which maybe in different servers with different business unit.

We need to add description here[1].

[1] https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/

**Comment by menghaoranss** [comment]
Add unsupported items for do not support configuring multiple logic databases https://github.com/apache/shardingsphere/pull/34030
