### ISSUE TITLE
Add more test cases for DatabaseTypeEngine.getProtocolType

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18823]
To make sure the test coverage is 100%

**Comment by huangdx0726** [comment]
I will try

**Comment by terrymanu** [comment]
@huangdx0726 Welcome onboard!

**Comment by huangdx0726** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
