### ISSUE TITLE
Add test case for OptimizerContext.alterDatabase

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18877]

**Comment by huangdx0726** [comment]
I will try

**Comment by terrymanu** [comment]
Great, I just assign to you

**Comment by huangdx0726** [comment]
Can i add test case for all remaining  public methords in this class？

**Comment by terrymanu** [comment]
The alterDatabase is refactored and removed for now. I just close this issue.

**Comment by terrymanu** [comment]
> Can i add test case for all remaining public methords in this class？

Sure, welcome!
