### ISSUE TITLE
Spring Boot Starter needs to add documentation and auto-suggestions for the SQL TRANSLATOR module

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#18889]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Yes, refer to https://github.com/apache/shardingsphere/issues/18653 and https://github.com/apache/shardingsphere/issues/18691 .

### Describe the feature you would like.

- Currently at https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sql-translator/ , YAML configuration provides configuration for `SQL_TRANSLATOR`. But for Spring Boot Starter, which has no documentation on the `SQL_TRANSLATOR` module, refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/ . 
- 
![image](https://user-images.githubusercontent.com/20187731/177486019-8cc23143-41bb-4de1-9b52-6ea1f0b9d268.png)

- 
![image](https://user-images.githubusercontent.com/20187731/177485989-ba3f0265-e628-442c-b6b1-029f7e737a70.png)

- In the `additional-spring-configuration-metadata.json`, there is no similar field involving automatic prompts. Refer to https://github.com/apache/shardingsphere/blob/master/shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json .

- A reasonable, conceivable configuration would be something like adding `spring.shardingsphere.rules.sql-translator.type` and `spring.shardingsphere.rules.sql-translator.useOriginalSQLWhenTranslatingFailed` in an additional `additional-spring-configuration-metadata.json` .

**Comment by zjcnb** [comment]
I think it's better to add automatic prompts to  https://github.com/apache/shardingsphere/blob/master/shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json .

**Comment by mabaiwan** [comment]
@zjcnb Can I try this issue?
