### ISSUE TITLE
ShardingSphere-Proxy opens prometheus monitoring and fails to start

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#18906]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy and Agent
### Expected behavior
Turn on prometheus monitoring and start successfully
### Actual behavior
Unable to start

![1657113946623](https://user-images.githubusercontent.com/16010265/177560998-a6d208c2-630f-4663-a8cd-34c98e810d0c.jpg)

**Comment by RaigorJiang** [comment]
Thank you @jiangML .

**Comment by likeitchen** [comment]
@jiangML 你好 请问你的proxy 和 agent 是什么版本呀

**Comment by likeitchen** [comment]
@jiangML Hello ML, what are the versions of agent and proxy in the current instance

I use proxy and agent during testing 5.2.1 No error reporting 5.1.0 No error reporting

However, 5.1.2 is consistent with the above error

9090 port fails to collect indicator data
