### ISSUE TITLE
I try to use custom sharding

### ISSUE THREAD

**Issue by poo0054** [apache/shardingsphere#18927]
### Which version of ShardingSphere did you use?
ShardingSphere-JDBC 5.1.0 + spring boot 2.3.10

  
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
        </dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC

### Expected behavior
Slicing rules execute my own

### Actual behavior
Not initialized

### Reason analyze (If you can)
ClassBasedShardingAlgorithm not  initialized,
The init() method of ClassBasedShardingAlgorithm was not executed

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

>  This is my configuration
```properties
spring.shardingsphere.enabled=true
spring.shardingsphere.datasource.names=oms
spring.shardingsphere.datasource.oms.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.oms.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.oms.url=jdbc:mysql://192.168.0.128:3306/yidian_oms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.oms.username=root
spring.shardingsphere.datasource.oms.password=root

spring.shardingsphere.rules.sharding.tables.oms_master_order.actual-data-nodes=oms.oms_master_order_$->{0..1}
spring.shardingsphere.rules.sharding.tables.oms_master_order.table-strategy.standard.sharding-column=id
spring.shardingsphere.rules.sharding.tables.oms_master_order.table-strategy.standard.sharding-algorithm-name=master-order-inline
spring.shardingsphere.rules.sharding.sharding-algorithms.master-order-inline.type=CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.master-order-inline.props=strategy
spring.shardingsphere.rules.sharding.sharding-algorithms.master-order-inline.props.algorithmClassName=cn.dian1.oms.core.sharding.TableShardingAlgorithm

```
>   This is my Algorithm
```java
public class TableShardingAlgorithm implements StandardShardingAlgorithm<Integer> {

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Integer> shardingValue) {
        System.out.println(availableTargetNames + "----------------" + availableTargetNames);
        return null;
    }

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Long> shardingValue) {
        System.out.println(availableTargetNames + "----------------" + availableTargetNames);
        return null;
    }

    @Override
    public void init() {
        System.out.println("------------------------------自定义分片启动----------------------------");
    }

    @Override
    public String getType() {
        return "";
    }

}
```

When executing classbasedshardingalgorithm. The attribute props in it has value, but standardshardingalgorithm is empty,
I looked at the classbasedshardingalgorithm and did not execute its init () method after startup.

The initialization of my customized method has not been executed

I found that all implementation classes of standardshardingalgorithm did not execute the init () method.
My environment is in springboot

**Comment by poo0054** [comment]
I found that all implementation classes of standardshardingalgorithm did not execute the init () method.
My environment is in springboot

**Comment by linghengqian** [comment]
- I think your custom `CLASS_BASE` class is written incorrectly, you don't need to `@Component`, you actually just need to mark the `final` class. Unless you have registered SPI, you don't need to override `getType` to a value other than `null`. You can refer to it  https://github.com/apache/shardingsphere/blob/5.1.0/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/java/org/apache/shardingsphere/sharding/fixture/ClassBasedStandardShardingAlgorithmFixture.java . 

- Incidentally, I can't reproduce your question in ShardingSphere 5.1.2. I think you should update the dependencies first.

**Comment by poo0054** [comment]
@linghengqian Hello, I tried not to add @component. I have also tried the generic type of string. But not at all  。
In springboot environment

I found that all the init () methods of standardshardingalgorithm were not executed.
As a result, every standardshardingalgorithm is not fully initialized. This problem is particularly obvious when you just try hashmodshardingalgorithm. The shardingcount attribute inside is a 0. It uses an int type. If you hit a breakpoint, you won't enter

**Comment by linghengqian** [comment]
@poo0054 

- I'm having a bit of a hard time understanding the meaning of this `all`....because I tried to debug the `org.apache.shardingsphere.sharding.algorithm.sharding.datetime.IntervalShardingAlgorithm` which implements `org.apache.shardingsphere.sharding.api.sharding.standard.StandardShardingAlgorithm` , the `init()` method is executed normally. 
- If you want to know where to start calling `init()`, see https://github.com/apache/shardingsphere/pull/11931 .
- If you can provide a reproduced example, it will obviously help us understand what is happening.
- ![image](https://user-images.githubusercontent.com/20187731/177753808-3a374d73-b0f4-4105-8bc7-889aee076450.png)

**Comment by linghengqian** [comment]
Obviously no PR will reach the master branch, as the problem cannot be reproduced in the master branch.

**Comment by poo0054** [comment]
I now switch to version 5.1.2,  
The classbasedshardingalgorithm object is @5925，All properties in it have been loaded successfully，The init () method also executes smoothly.
TableShardingAlgorithm@5944.
![image](https://user-images.githubusercontent.com/85894494/177927691-af1e52d2-5aa4-4891-b411-7ebf2d5479f0.png)

Then I try to understand where this class is injected

![image](https://user-images.githubusercontent.com/85894494/177928992-8c76e6de-0d87-4de4-b53e-a829a54fa559.png)

After successful startup. I try to partition with custom partition。
Found in partialsqlouteexecutor#routes

![image](https://user-images.githubusercontent.com/85894494/177930019-8284abd4-0617-487a-9f3a-cf7164ec9b68.png)

Finally, when the standardshardingstrategy is initialized, there is a classbasedshardingalgorithm object in it. But not the same one,

Above is classbasedshardingalgorithm @5925

Now it's classbasedshardingalgorithm @20441

![image](https://user-images.githubusercontent.com/85894494/177930367-06bbbf11-8543-40e1-ab92-da9003828992.png)

Finally, in classbasedshardingalgorithm#dosharding  java.lang.NullPointerException: null

![image](https://user-images.githubusercontent.com/85894494/177930773-787c0f15-ed4e-4537-9654-5df6a947f5c0.png)

**Comment by poo0054** [comment]
I found that you replaced the Preparedstatement with your shardingspherepreparedstatement. The classbasedshardingalgorithm in it is stored in the shardingspherepreparedstatement. However, after the initialization of classbasedshardingalgorithm, it is stored in the bean of spring, and beandefinitionbuilder \genericbeandefinition is used to create beandefinitionbuilder. Then register
I found that you replaced the Preparedstatement with your shardingspherepreparedstatement. The classbasedshardingalgorithm in it is stored in the shardingspherepreparedstatement. However, after the initialization of classbasedshardingalgorithm, it is stored in the bean of spring, and beandefinitionbuilder \genericbeandefinition is used to create beandefinitionbuilder. Then register. I'm a little curious about why we need to register here. Why don't we get the data source directly from beanfactory and put classbasedshardingalgorithm into it

**Comment by linghengqian** [comment]
I tested CLASS_BASE locally and still can't reproduce the NPE you took. I realize that you have a problem with the custom algorithm class, and I think that providing a reproducible unit test will help illustrate your problem.

**Comment by linghengqian** [comment]
> I found that you replaced the Preparedstatement with your shardingspherepreparedstatement. The classbasedshardingalgorithm in it is stored in the shardingspherepreparedstatement. However, after the initialization of classbasedshardingalgorithm, it is stored in the bean of spring, and beandefinitionbuilder \genericbeandefinition is used to create beandefinitionbuilder. Then register. I'm a little curious about why we need to register here. Why don't we get the data source directly from beanfactory and put classbasedshardingalgorithm into it 

- Are you referring to custom algorithm classes registered into the Spring container? This has nothing to do with ShardingSphere's design, which clearly shouldn't intersect with Spring when its data source itself is in a Spring container. And you have to take into account that Quarkus users don't walk Spring containers.

**Comment by poo0054** [comment]
Thank you very much for your answer. I'm also confused now



But I found that this is the case when the shardingspherealgorithmfactory#createalgorithm method creates a classbasedshardingalgorithm

![image](https://user-images.githubusercontent.com/85894494/177933905-8561a497-185e-4cc8-9a9c-021228257312.png)

Then in classbasedshardingalgorithm#dosharding, the standardshardingalgorithm in it is a null value

**Comment by poo0054** [comment]
Suddenly I found that it was my local environment problem. I recreated this code into a project, and then it could be passed in another place. Nothing has changed. Thank you very much for your answer

**Comment by dinghu** [comment]
> Suddenly I found that it was my local environment problem. I recreated this code into a project, and then it could be passed in another place. Nothing has changed. Thank you very much for your answer

no  i also get this bug like you, it is a bug!!!

**Comment by dinghu** [comment]
> Suddenly I found that it was my local environment problem. I recreated this code into a project, and then it could be passed in another place. Nothing has changed. Thank you very much for your answer

no  i also get this bug like you, it is a bug!!!

**Comment by linghengqian** [comment]
@dinghu It's not a bug, since no one has provided a minimal reproducible example.

**Comment by poo0054** [comment]
@dinghu  hi,Is your new environment.If Alibaba sentinel is introduced into your environment, you can consider taking a look
#18966 . You can check whether the spring bean was created before the post processors

**Comment by dinghu** [comment]
> 

thank you very much，i use shiro in my project . shiro realm contains some XXservice XX dao but sharding configs is not be loaded at this time !  finnaly i solve it like this:
![1660290818884](https://user-images.githubusercontent.com/8045842/184310176-f475c83f-511d-438c-96b0-6e9c40950dc2.png)

**Comment by poo0054** [comment]
@dinghu I'm glad I can help you
