### ISSUE TITLE
5.1.2,“create table “  Not full route

### ISSUE THREAD

**Issue by a207005** [apache/shardingsphere#18934]
ShardingSphere-JDBC 5.1.2
in my project,i need to create table based on business.
in version 4.1.1 ,i can create table in all my databasenodes.but in version 5.1.2 only 1 node created the table.
![image](https://user-images.githubusercontent.com/17873578/177736942-a0c21107-dc16-4441-8f84-77ac4574b06d.png)

then id config a target table rule in shard-jdbc shard rules.start my project,use my project create the target table ,all databasenodes created the table.
![image](https://user-images.githubusercontent.com/17873578/177735781-ef58d986-bccb-4877-9875-e4f90323e324.png)
![image](https://user-images.githubusercontent.com/17873578/177735672-fda79cc7-030e-49ae-9a64-491b80b26022.png)

no rule,no full route create base.
has rule,full ruoute create base.

how i can create table and create rules without proxy

**Comment by terrymanu** [comment]
What is your configuration?

**Comment by terrymanu** [comment]
Closed because of no feedback for long time.
