### ISSUE TITLE
No implementation class load from SPI `org.apache.shardingsphere.sharding.spi.ShardingAlgorithm` with type `T_ORDER_SPI_BASED`.

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#18932]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
work correctly

### Actual behavior
in the spi-based-sharding-spring-boot-jpa-example project:
![image](https://user-images.githubusercontent.com/28882195/177727072-4111ff32-9968-4f7f-9240-26f4fbad6e99.png)
the error log:
![image](https://user-images.githubusercontent.com/28882195/177727186-7ce83b4f-bd44-444e-ab26-71fe8f96ba98.png)

### Reason analyze (If you can)
the custom algorithm is not implemented and configured correctly

**Comment by poo0054** [comment]
I also have this problem,What is your version,Is it an official example of use

 I found that all the init () methods of standardshardingalgorithm were not executed.

**Comment by terrymanu** [comment]
> I also have this problem I found that all the init () methods of standardshardingalgorithm were not executed. As a result, every standardshardingalgorithm is not fully initialized. This problem is particularly obvious when you just try hashmodshardingalgorithm. The shardingcount attribute inside is a 0. It uses an int type. If you hit a breakpoint, you won't enter

They are maybe different problems. One is for loading not existed SPI, your issue is codes can find SPI, but not call init method.

**Comment by terrymanu** [comment]
@doveylovey For your issue, I think that the `T_ORDER_SPI_BASED` is your own sharding algorithm type.
Please try to understand the example, and run the original example to make sure the example is fine.

**Comment by poo0054** [comment]
Hi, I found this problem. This problem does exist in sentinel. The address is this. You can have a look
https://github.com/alibaba/spring-cloud-alibaba/issues/2651
