### ISSUE TITLE
Support get detail error info for parse

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#18948]
### Is your feature request related to a problem?
 No
### Describe the feature you would like.
 parse error should have detail info.
like this sql 
```
CREATE TABLE public.files (id BIGINT NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE, created_by BIGINT, updated_by BIGINT, name VARCHAR(255), path VARCHAR(255), CONSTRAINT files_pkey PRIMARY KEY (id))
```
We can only get this error info
```
You have an error in your SQL syntax
```
Actually we can get detail info like this 
```
line 1:184 no viable alternative at input 'path'
```
### How to do
I found if I remove this error listener line. Then, I can get error info . So it's may be a way to get detail info.
```java
    @SneakyThrows(ReflectiveOperationException.class)
    private static SQLParser createSQLParser(final TokenStream tokenStream, final Class<? extends SQLParser> parserClass) {
        SQLParser result = parserClass.getConstructor(TokenStream.class).newInstance(tokenStream);
        ((Parser) result).setErrorHandler(new BailErrorStrategy());
        // ((Parser) result).removeErrorListener(ConsoleErrorListener.INSTANCE);
        return result;
    }
```

**Comment by chakkk309** [comment]
Hi, can I try this?

**Comment by tuichenchuxin** [comment]
sure

**Comment by tuichenchuxin** [comment]
@chakkk309 hi, is there any progress for this issue?

**Comment by chakkk309** [comment]
> @chakkk309 hi, is there any progress for this issue?

Hi, this issue is still in progress, if there is any progress I will keep you updated.

**Comment by strongduanmu** [comment]
You can do some test, I think it has been support by other contributor.

**Comment by strongduanmu** [comment]
@hailin0 Thank you for your feedback. Since this issue has been fixed, I will close it.
