### ISSUE TITLE
count with subquery is error

### ISSUE THREAD

**Issue by luoyexiaoran** [apache/shardingsphere#18949]
error sql:

select count(1) from ( select r.name, r.rubbishType,left(cd.collectDate,4) as collectDate,sum(cd.collectVolumeOfToday) as dailyOutput,  sum(cd.collectTrashSumNum) as collectTrashSumNum,sum(cd.collectTimes) as collectTimes,cd.districtName,sum(cd.alarmNums) as alarmNum,r.classesName  from cc_restaurant_collect_data cd LEFT JOIN cc_restaurant r on cd.restaurantId = r.id  where cd.beenDeleted = 0  and r.beenDeleted = 0  and left(cd.collectDate,4)>=?  and left(cd.collectDate,4)<=?  group by cd.districtId,cd.restaurantId,left(cd.collectDate,4) ) a 

![image](https://user-images.githubusercontent.com/48896854/177904466-2810ffbe-1667-46d1-ae43-0b81506acd3d.png)

every actual sql result is correct! but  the aggregate result simply adds up all the results!

**Comment by terrymanu** [comment]
What is your version?

**Comment by luoyexiaoran** [comment]
> What is your version?

5.0.0-RC1-SNAPSHOT,,I'm trying to switch to 5.1.3,,But it is still wrong

**Comment by terrymanu** [comment]
What is your configuration?

**Comment by luoyexiaoran** [comment]
> What is your configuration?
![image](https://user-images.githubusercontent.com/48896854/178386516-92bb11cf-057a-4fed-b4cb-711cc5eec987.png)
![image](https://user-images.githubusercontent.com/48896854/178386538-c3d4d12a-7686-408e-99f1-57007598eb0b.png)
![image](https://user-images.githubusercontent.com/48896854/178386563-816f7533-8af6-47d3-86c4-6a8d1b547377.png)

I sharding it by the month,this sql select group one year data

**Comment by terrymanu** [comment]
Please use text with markdown syntax to provide your configuration, snapshot is difficult to search and copy

**Comment by luoyexiaoran** [comment]
`rules:
  - !SHARDING
    # 配置分片规则
    tables:
      # 配置商户汇总表cc_restaurant_collect_data规则
      cc_restaurant_collect_data:
        actualDataNodes: ds0.cc_restaurant_collect_data$->{2020..2022}0$->{1..9},ds0.cc_restaurant_collect_data$->{2020..2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: collectDate
            shardingAlgorithmName: cc_restaurant_collect_data
      # 商户汇总表（修正收运量）
      cc_restaurant_collect_data_correct_weight:
        actualDataNodes: ds0.cc_restaurant_collect_data_correct_weight$->{2020..2022}0$->{1..9},ds0.cc_restaurant_collect_data_correct_weight$->{2020..2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: collectDaterestaurantCollectDataCorrectWeightController
            shardingAlgorithmName: cc_restaurant_collect_data_correct_weight
      # 配置商户汇总表cc_sypoint_collect_data规则
      cc_sypoint_collect_data:
        actualDataNodes: ds0.cc_sypoint_collect_data$->{2020..2022}0$->{1..9},ds0.cc_sypoint_collect_data$->{2020..2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: collectDate
            shardingAlgorithmName: cc_sypoint_collect_data
      # 配置商户汇总表cc_rfid规则
      cc_rfid:
        actualDataNodes: ds0.cc_rfid$->{2020..2022}0$->{1..9},ds0.cc_rfid$->{2020..2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: time
            shardingAlgorithmName: cc_rfid
      # 配置商户汇总表cc_weighbridge规则
      cc_weighbridge:
        actualDataNodes: ds0.cc_weighbridge$->{2020..2022}0$->{1..9},ds0.cc_weighbridge$->{2020..2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: grossDateTime
            shardingAlgorithmName: cc_weighbridge
      # 配置商户汇总表cc_sypoint_collect_data规则
      cc_car_alarm_event:
        actualDataNodes: ds0.cc_car_alarm_event$->{2022}0$->{1..9},ds0.cc_car_alarm_event$->{2022}1$->{0..2}
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: alarmTime
            shardingAlgorithmName: cc_car_alarm_event
    shardingAlgorithms:
      cc_restaurant_collect_data:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.RestaurantCollectDataShardingAlgorithm
      cc_restaurant_collect_data_correct_weight:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.RestaurantCollectDataCorrectWeightShardingAlgorithm
      cc_sypoint_collect_data:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.SypointCollectDataShardingAlgorithm
      cc_rfid:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.RfidDataShardingAlgorithm
      cc_weighbridge:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.WeighbridgeShardingAlgorithm
      cc_car_alarm_event:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.vortex.cloud.envcloud.cc.config.sharding.CarAlarmEventShardingAlgorithm
#属性配置
props:
  sql-show: true`

` @Override
    public String doSharding(Collection availableTargetNames, PreciseShardingValue shardingValue) {
        String collectDate = (String) shardingValue.getValue();
        LinkedList<String> tableNames = CollectionUtil.newLinkedList();
        tableNames.addAll(availableTargetNames);
        //获取所有表名，确定范围
        for (String tableName : tableNames) {
            String month = tableName.substring(tableName.length() - 6);
            if (month.equals(collectDate.substring(0, 7).replaceAll("-", ""))) {
                return tableName;
            }
        }
        throw new VortexException("未找到分表路由");
    }

    @Override
    public Collection<String> doSharding(Collection availableTargetNames, RangeShardingValue shardingValue) {
        List<String> result = CollectionUtil.newLinkedList();
        Range<String> ranges = shardingValue.getValueRange();
        result.addAll(availableTargetNames);
        if (ranges.hasLowerBound()) {
            String startDate = ranges.lowerEndpoint();
            DateTime beginOfMonth = DateUtil.beginOfMonth(DateUtil.parse(startDate.substring(0, 7), "yyyy-MM"));
            result = result.stream().filter(tableName -> {
                String month = tableName.substring(tableName.length() - 6);
                DateTime endOfMonth = DateUtil.endOfMonth(DateUtil.parse(month, "yyyyMM"));
                return beginOfMonth.getTime() <= endOfMonth.getTime();
            }).collect(Collectors.toList());
        }
        if (ranges.hasUpperBound()) {
            String endDate = ranges.upperEndpoint();
            DateTime endOfMonth = DateUtil.endOfMonth(DateUtil.parse(endDate.substring(0, 7), "yyyy-MM"));
            result = result.stream().filter(tableName -> {
                String month = tableName.substring(tableName.length() - 6);
                DateTime beginOfMonth = DateUtil.beginOfMonth(DateUtil.parse(month, "yyyyMM"));
                return beginOfMonth.getTime() <= endOfMonth.getTime();
            }).collect(Collectors.toList());
        }
        return result;
    }`

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, and ShardingSphere has released several new versions, so I will close it.
Please try the latest version, and if the problem reproduces, please reopen it or submit a new one.
