### ISSUE TITLE
It seems that DistSQL has a problem parsing the "from" statement.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#18964]
### Which version of ShardingSphere did you use?
5.1.3-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
 SHOW DATABASE RESOURCES FROM db execute succes.

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/177965817-93d120a9-c293-4d5b-8797-5611fd2ae572.png)

### Reason analyze (If you can)
db is a keyword

### Example codes for reproduce this issue (such as a github link).

shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/rql/rql-integration-test-cases.xml

**Comment by RaigorJiang** [comment]
Hi @JiekerTime ,
Thanks for your report.

In the `Resource RDL` scenario, `DB` is indeed a keyword.
I'm already sorting out the specifications for DistSQL keywords and variable types, and will add detailed plans in another issue: #18811

**Comment by RaigorJiang** [comment]
Updated in #18811.
