### ISSUE TITLE
When using JPA, and without transaction management, the select is routed to the write-ds, why not the read-ds?

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#18963]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
v5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
When shardingSphere is used with JPA, and without transaction management, the select are routed to read-ds.

### Actual behavior
the select are not routed to read-ds:
![image](https://user-images.githubusercontent.com/28882195/178170406-ecf34207-c7fa-49f9-8148-789d29c64c8b.png)

**Comment by doveylovey** [comment]
@[terrymanu](https://github.com/terrymanu) Hello, can you take a look at this problem? I need some help, thank you

**Comment by terrymanu** [comment]
Your application framework is too complicated, can you provide the code to reproduce it?

**Comment by doveylovey** [comment]
> Your application framework is too complicated, can you provide the code to reproduce it?

This is an example given in the project, located at:

https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/java/org/apache/shardingsphere/example/readwrite/splitting/spring/boot/jpa/ReadwriteSplittingSpringBootJpaExample.java

https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-namespace-jpa-example/src/main/java/org/apache/shardingsphere/example/readwrite/splitting/spring/namespace/jpa/ReadwriteSplittingSpringNamespaceJpaExample.java

**Comment by RaigorJiang** [comment]
This is because of a feature at the time:
There are write operations on the same connection, and subsequent reads are also routed to write ds for consistency.
