### ISSUE TITLE
5.1.1 not support mysql subquery ?

### ISSUE THREAD

**Issue by williamXinCC** [apache/shardingsphere#18973]
SELECT person_id,
        open_id
        FROM sf_person
        WHERE tenant_id = #{tenantId} and person_id IN
        (SELECT person_id
        FROM sf_person_unit
        WHERE tenant_id = #{tenantId} and
        unit_id IN
        (SELECT unit_id
        FROM sf_unit
        <where>
            <if test="buildingList != null and buildingList.size() > 0">
                and building_id IN
                <foreach collection="buildingList" item="item" index="index" open="(" close=")" separator=",">
                    #{item}
                </foreach>
            </if>
            and tenant_id = #{tenantId}
        </where>
        )and type !=4 and status = 1 and exclusive_state =1
        )

**Comment by TeslaCN** [comment]
Hi @williamXinCC 
Please provide us your configurations, DDL, actual SQL and errors.

**Comment by williamXinCC** [comment]
![image](https://user-images.githubusercontent.com/34149036/178094011-68b02c51-f463-4784-a815-28a2cfede7c2.png)
![image](https://user-images.githubusercontent.com/34149036/178094031-a78893e3-3aa8-408b-82f1-fcff37e961bf.png)
![image](https://user-images.githubusercontent.com/34149036/178094077-ad794ba1-df29-4070-be8b-1dda6a46b5e7.png)
![image](https://user-images.githubusercontent.com/34149036/178094088-bf6b4a8d-bbcb-4839-a7e0-1e2307c30e5b.png)

**Comment by williamXinCC** [comment]
Is also never use  my custom StandardShardingAlgorithm

**Comment by williamXinCC** [comment]
The other question, after 4.1.1 upgrade to 5.1.2,the project startup very very slow, so i change to 5.1.1 return to normal

**Comment by linghengqian** [comment]
> The other question, after 4.1.1 upgrade to 5.1.2,the project startup very very slow, so i change to 5.1.1 return to normal

Resolved in https://github.com/apache/shardingsphere/issues/18691 .

**Comment by TeslaCN** [comment]
Could you paste the SQL and codes in text format? Screenshots doesn't help us to reproduce this issue.

**Comment by linghengqian** [comment]
Hi, a critical calcite issue has been resolved, refer to https://issues.apache.org/jira/plugins/servlet/mobile#issue/CALCITE-35.  I think we have good reason to upgrade to calcite 1.31.0 now.  👨‍🔧

**Comment by RaigorJiang** [comment]
Hi @williamXinCC @linghengqian 
Has this issue been resolved after the calcite upgrade?

**Comment by linghengqian** [comment]
- My local test looks normal, and the issue does not give a reproducible example to test.  For more issues with Calcite, I think we can move to https://github.com/apache/shardingsphere/issues/20982 .

**Comment by RaigorJiang** [comment]
> * My local test looks normal, and the issue does not give a reproducible example to test.  For more issues with Calcite, I think we can move to [When I execute integration test using `ADVANCED` type, I am getting exception as below. #20982](https://github.com/apache/shardingsphere/issues/20982) .

OK, thank you @linghengqian , so I just close this issue now.
