### ISSUE TITLE
To be optimized hints of ContextManager

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18972]
1. Reload schema/table method can handle alter only, it should handle add and drop too;
1. persistMetaData() and dataSourceService.append() method occur together in addResource(), it is better to aggregate the accessor of reg center;
1. Missing ResourceHeldRule.addResource() in alterRuleConfiguration and alterDataSourceConfiguration.

**Comment by zjcnb** [comment]
Thx, I will follow it.

**Comment by strongduanmu** [comment]
Hi @zjcnb , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
Hi, could we finish this issue in 5.2.1?

**Comment by strongduanmu** [comment]
Since this task is not complete, I will move it to 5.2.2.

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could it be done on 5.3.1?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , could it be done on 5.3.1?

I think this issue are finished. so i close it
