### ISSUE TITLE
Try to remove LockContext.isLocked()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18991]
LockContext.tryLock() is good practice of database lock.
For each lock progress, it is better to call tryLock first until timeout.

I am not sure what is the useful of `isLocked` method, can it be instead of tryLock?

The logic of `if isLocked is true, then throw exception` is not suitable out of control of LockContext.

**Comment by soulasuna** [comment]
The `isLocked` can not remove in cluster mode.
