### ISSUE TITLE
RALStatement extension structures are not clear

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18995]
The current structures are:

```
RALStatement
  -- QueryableRALStatement
  -- UpdatableRALStatement
  -- QueryableScalingRALStatement
  -- UpdatableScalingRALStatement
  -- CommonRALStatement
  -- AdvancedDistSQLStatement
```

`QueryableRALStatement` and `UpdatableRALStatement` are suitable basic categories.
`QueryableScalingRALStatement` and `UpdatableScalingRALStatement` are not in same abstract level with previous.
`CommonRALStatement` is for hint only, which is not suitable too for same abstract level. Question: Any other new DistSQL will be handled?
`AdvancedDistSQLStatement` is not used for now, maybe remove soon.

I suggest to adjust the class  extension structure. How about below?

```
RALStatement
  -- QueryableRALStatement
  -- UpdatableRALStatement
  -- ScalingRALStatement
    ---- QueryableScalingRALStatement
    ---- UpdatableScalingRALStatement
  -- HintRALStatement
```

**Comment by RaigorJiang** [comment]
Yes, it's a good suggestion.

**Comment by RaigorJiang** [comment]
Hi @terrymanu 

I sorted out the relationship between the current DistSQLStatement and its subclasses:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/5668787/178217962-3a44682f-490d-49c0-9eb1-8b038706370c.png">

There are indeed some problems:
1. `AdvancedDistSQLStatement` is not used;
2. `CommonRALStatement` only contains Hint-related statements;
3. Inappropriate levels of `QueryableScalingRALStatement` and `UpdatableScalingRALStatement`;
4. `PreviewStatement` and `ParseStatement` are not strictly `QUERY`, and may need to add a new type, which is different from `RDL`, `RAL`, and `RQL`.

I plan to make the following adjustments:
1. Remove `AdvancedDistSQLStatement`;
2. Remove `CommonRALStatement`, `HintDistSQLStatement` directly inherits `RALStatement`;
3. Added `ScalingRALStatement` as you said;
4. Added `SAL (SQL Analysis Language)`, including `Preview`, `Parse`, `Format` and other statements for analyzing SQL statements.
The new structure is as follows:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/5668787/178218232-af9e321b-a90b-454e-951b-f44c3f27802a.png">

At the same time, the naming of DistSQLStatementParserEngine should also be
To update:
- `CommonDistSQLStatementParserEngine` renamed to `KennelDistSQLStatementParserEngine`;
- `AdvancedDistSQLStatementParserEngine` renamed to `SALStatementParserEngine`
#### Before
<img width="840" alt="image" src="https://user-images.githubusercontent.com/5668787/178219307-1e4b320d-1696-4321-946d-7bcadf23ec53.png">

#### After
<img width="830" alt="image" src="https://user-images.githubusercontent.com/5668787/178219178-f9d0ed39-a681-4af9-8afe-22f0768cc9d8.png">
