### ISSUE TITLE
LockNameDefinition maybe not good name

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#18998]
The class of LockNameDefinition is defined for lock mode and level, not name.
It is better to change the name more make sense.

**Comment by strongduanmu** [comment]
Hi @soulasuna  , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by soulasuna** [comment]
@strongduanmu I am sorry, this has been done, I just forgot to close it
