### ISSUE TITLE
Merge memory and standalone mode

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19001]
Memory and standalone mode is too similar, and we can add memory storage for standalone.
I want to discuss how about merge memory and standalone mode, any suggestion?

**Comment by zjcnb** [comment]
Great! I think it only reserve `standalone` mode, and the default type is `h2`.

**Comment by terrymanu** [comment]
Yes, h2 is the default storage for standalone mode, and we can use h2's mem jdbc url for current memory mode.

**Comment by terrymanu** [comment]
`StandalonePersistRepository` uses `FileRepository` as default StandalonePersistRepository. 
I plan to change like this way:

1. Use `H2Repository` as default impl;
2. Remove `FileRepository`, `H2Repository` is enough;
3. Use `jdbc:h2:mem` as default url

**Comment by wuwen5** [comment]
This update breaks the compatibility,the version upgrade brings a lot of trouble. In our application scenario, it is very simple. We only need the default memory mode. We do not want to use the h2 memory database in production.  
And in our build configuration the maven dependency scope of h2 is test.

It seems that the file storage implementation has also been deleted in this update. I suggest restoring the file implementation as an option.
