### ISSUE TITLE
Split ShowVariableStatement to ShowVariableStatement and ShowAllVariablesStatement

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19014]
The ShowVariableStatement include show single variable and show all variables, it is better to split it to 2 classes: ShowVariableStatement and ShowAllVariablesStatement. The tasks include:

- [ ] Add ShowAllVariablesStatement
- [ ] Implement visitor of ShowAllVariablesStatement
- [ ] Make ShowVariableStatement's constructor as @RequiredArgsConstructor
- [ ] Add ShowAllVariablesHandler
- [ ] Register ShowAllVariablesHandler in RALBackendHandlerFactory
- [ ] Add related test cases

**Comment by LeeGuoPing** [comment]
I want to do it
