### ISSUE TITLE
We hope to support the fuzzy query of encrypted fields

### ISSUE THREAD

**Issue by liming0** [apache/shardingsphere#19026]
## We hope to support the fuzzy query of encrypted fields

Now it is to report exceptions directly, and the algorithm can be implemented by itself

### Is your feature request related to a problem?
no

**Comment by terrymanu** [comment]
Do you mean `LIKE`?

**Comment by liming0** [comment]
> Do you mean `LIKE`?
yes

**Comment by liming0** [comment]
> > Do you mean `LIKE`?
> > yes
The current situation is that 'like' will result in an error

**Comment by terrymanu** [comment]
I have no idea for how to support `LIKE`, any suggestions?

**Comment by cheese8** [comment]
In practice, it is often implemented by another column which is desensitized and met your `LIKE` requirement.

**Comment by liming0** [comment]
> I have no idea for how to support `LIKE`, any suggestions?
I think we only need to allow the like keyword to filter the encrypted column. The specific implementation of encryption and query can be realized by users themselves

**Comment by liming0** [comment]
> I have no idea for how to support `LIKE`, any suggestions?



> I have no idea for how to support `LIKE`, any suggestions?


我现在的想法是将内容拆分成x个字符一组，然后将每组分别加密，再拼接起来存储，在查询时重复分组加密的步骤，再进行查询即可；这种方式目前有两个点需要控制：一是加密后的字符会比较长，这种方式属于用存储空间来实现这个需求；二是需要控制变量x的大小，不能太短，太长了也会影响搜索体验
My idea now is to divide the content into groups of X characters, then encrypt each group separately, and then splice them together for storage. When querying, repeat the steps of grouping encryption, and then query; At present, there are two points to be controlled in this method: first, the encrypted characters will be relatively long. This method uses storage space to realize this requirement; Second, we need to control the size of variable x, which should not be too short. Too long will also affect the search experience

**Comment by liming0** [comment]
> I have no idea for how to support `LIKE`, any suggestions?
My idea now is to divide the content into groups of X characters, then encrypt each group separately, and then splice them together for storage. When querying, repeat the steps of grouping encryption, and then query; At present, there are two points to be controlled in this method: first, the encrypted characters will be relatively long. This method uses storage space to realize this requirement; Second, we need to control the size of variable x, which should not be too short. Too long will also affect the search experience

**Comment by terrymanu** [comment]
How about the performance and the storage capacity?

**Comment by strongduanmu** [comment]
Duplicated with #20435
