### ISSUE TITLE
SHOW SHARDING AUDITORS Not support.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#19020]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
![image](https://user-images.githubusercontent.com/76552510/178210402-905cca52-2e38-4fb8-8c6a-bd130def5255.png)
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/sharding/
![image](https://user-images.githubusercontent.com/76552510/178210468-9e1247ca-7132-4786-a131-e6b5e7da6d4f.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/178210458-c62365b1-118a-4aa8-8e41-06916c66a1cf.png)

### Reason analyze (If you can)
Not support.

**Comment by csonezp** [comment]
Which version are you using?
I didn't find this problem in the latest version.

**Comment by csonezp** [comment]
Which version are you using?
I didn't find this problem in the latest version

**Comment by natehuangting** [comment]
@JiekerTime Can you provide your sharding configuration file, I have no problem with my own verification.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/26433395/178385225-a26dcfa0-0edf-4e52-85e0-554217c1f950.png">

**Comment by JiekerTime** [comment]
This is my problem, the mirror is not being updated.
