### ISSUE TITLE
Shardingsphere-proxy Can not support multiple different database error

### ISSUE THREAD

**Issue by hehua2018** [apache/shardingsphere#19035]
##### mysql databases: product;finance
```
 select tso.store_id,dept.pk_org,dept.code,dept.name,dept.shortname, dept.parent_pk_dept,dept.pk_org,dept.pk_dept from product.t_store_options tso inner join finance.nc_dept dept on tso.nc_pk_org = dept.pk_org where tso.store_id = ? and parent_pk_dept = '~'
```
#### The error is shown below
![image](https://user-images.githubusercontent.com/36179722/178256563-f51fd8f4-8b24-4d5a-bb1a-ffb2dc41b853.png)

**Comment by terrymanu** [comment]
Can you use markdown syntax to format your issue content to make it easy to read?

**Comment by hehua2018** [comment]
> Can you use markdown syntax to format your issue content to make it easy to read?

ok, the above problem has been solved using markdown document, please help to see how to solve it, thank you

**Comment by inotgaoshou** [comment]
mark,I have the same problem.

**Comment by terrymanu** [comment]
> > Can you use markdown syntax to format your issue content to make it easy to read?
> 
> ok, the above problem has been solved using markdown document, please help to see how to solve it, thank you

The picture is hard to copy and search, could you change it to text with markdown syntax?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.

**Comment by Y-sir** [comment]
@inotgaoshou @hehua2018 Is this issue resolved now?
