### ISSUE TITLE
[Jager agent]trace cannot be passed across threads

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#19043]
### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
trace can be passed across threads(Jager agent)

### Actual behavior
trace cannot be passed across threads(Jager agent)

### Reason analyze (If you can)
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/20919316/178398318-5d2fffcb-0898-4240-9cc9-a7b75042ac32.png">
Scopemanager is not set as cross thread storage here

**Comment by RaigorJiang** [comment]
Hi @git-chenhao 
Would you like to submit a PR to improve it?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
