### ISSUE TITLE
when to support MGR multi-primary-mode

### ISSUE THREAD

**Issue by AllKai** [apache/shardingsphere#19056]
MGR multi-primary-mode very important

**Comment by zjcnb** [comment]
> MGR multi-primary-mode very important

@AllKai A Hi, `ShardingSphere` should support multiple writes first.

**Comment by AllKai** [comment]
> > MGR multi-primary-mode very important
> 
> @AllKai A Hi, `ShardingSphere` should support multiple writes first.

yes, 我们现在使用MySQL-Router路由MGR, It would be better if routing control could be done at the application layer

**Comment by AllKai** [comment]
> > MGR multi-primary-mode very important
> 
> @AllKai A Hi, `ShardingSphere` should support multiple writes first.

We now use MySQL-Router to control MGR and it would be better if routing control could be done at the application layer.

**Comment by RaigorJiang** [comment]
Without such a plan, I will close this issue
