### ISSUE TITLE
Refer to each other in class "ConnectionSession" and "BackendConnection" 

### ISSUE THREAD

**Issue by xuup** [apache/shardingsphere#19051]
## Question
Hi, I found a place refer to each other  in ShardingSphere master branch.

##### org/apache/shardingsphere/proxy/backend/session/ConnectionSession.java

BackendConnection is  one of ConnectionSession‘s properties.

```java
public final class ConnectionSession {
   
    private final BackendConnection backendConnection;

}    
```

However, in BackendConnection's implements , like JDBCBackendConnection, ConnectionSession as one of its properties.

##### org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/JDBCBackendConnection.java
```java
public final class JDBCBackendConnection implements BackendConnection<Void>, ExecutorJDBCConnectionManager {
    
    private final ConnectionSession connectionSession;

}
```

I think this is not good for java programming, Could you please explain the reason for this design？ Thx .

**Comment by TeslaCN** [comment]
In earlier version, there is a `BackendConnection` which includes all fields in `ConnectionSession` and `JDBCBackendConnection`. We want to decouple `BackendConnection` from JDBC, so we separated it into two classes.
`ConnectionSession` and `BackendConnection` is bound for a client of Proxy, so we make it refers each other.

Actually, this is similar to `HikariPool` and `HikariDataSource`, which refers each other.

**Comment by TeslaCN** [comment]
I'm closing this question for now.
