### ISSUE TITLE
Maybe we can verify dataSource in ReadWrite-splitting rules，before create  ReadWrite-splitting rules.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#19102]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
NO
#### First of all, we can use DistSQL create two READWRITE_SPLITTING RULE in one logic schema.
eg:
```
CREATE READWRITE_SPLITTING RULE ms_group_0 (
WRITE_RESOURCE=write_ds,
READ_RESOURCES(read_ds_0,read_ds_1),
TYPE(NAME=random)
);
CREATE READWRITE_SPLITTING RULE ms_group_1(
WRITE_RESOURCE=write_ds,
READ_RESOURCES(read_ds_0,read_ds_1),
TYPE(NAME=random)
);

```
<img width="665" alt="image" src="https://user-images.githubusercontent.com/86462784/178705641-fbc56d1e-07e9-48a6-af7a-8e8328cda378.png">

#### But when we use select in this logic schema,we can't figure out how to route,because of we have same table in two rules.
And it is not legal, because we cant't have two same table in one schema.

**Comment by peilinqian** [comment]
```
split_db=> CREATE READWRITE_SPLITTING RULE ms_group_0 (
split_db(> WRITE_RESOURCE=write_0,
split_db(> READ_RESOURCES(read1_0),
split_db(> TYPE(NAME="random")
split_db(> );
ERROR:  Can not config duplicate write data source `write_0` in database `split_db`.
split_db=> CREATE READWRITE_SPLITTING RULE ms_group_1(
split_db(> WRITE_RESOURCE=write_0,
split_db(> READ_RESOURCES(read1_0),
split_db(> TYPE(NAME="random")
split_db(> );
ERROR:  Can not config duplicate write data source `write_0` in database `split_db`.
split_db=>
split_db=> SHOW READWRITE_SPLITTING RULES;
    name    | auto_aware_data_source_name | write_data_source_query_enabled | write_data_source_name | read_data_source_names |   load_balancer_type    | load_balancer_props
------------+-----------------------------+---------------------------------+------------------------+------------------------+-------------------------+---------------------
 ds_0       |                             |                                 | write_0                | read0_0                | TRANSACTION_ROUND_ROBIN |
 ds_1       |                             |                                 | write_1                | read1_0                | TRANSACTION_ROUND_ROBIN |
 ms_group_0 |                             |                                 | write_0                | read1_0                | random                  |
 ms_group_1 |                             |                                 | write_0                | read1_0                | random                  |
(4 rows)

```

**Comment by wsm12138** [comment]
@zhaojinchao95  @RaigorJiang  
plz help have a look

**Comment by zhaojinchao95** [comment]
This problem cause are `DistSQL` update memory metadata first, and then, call `governance api` to persist configuration. compute node listen zk event to rebuild readwrite rule throws error, this work flow are asynchronous.

**Comment by wsm12138** [comment]
@peilinqian 
I found this issue fixed by https://github.com/apache/shardingsphere/pull/21093.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/86462784/191426413-6ce9dfd5-5803-4f97-96a0-02cbfd8b33d9.png">


<img width="1070" alt="image" src="https://user-images.githubusercontent.com/86462784/191426482-c6657a7a-d887-4880-ba62-6bdc4be04c3e.png">

**Comment by RaigorJiang** [comment]
Yes, by design, read resource and write resource may be the same.
