### ISSUE TITLE
Integration tests support cluster mode

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#19103]
## Feature Request
Integration tests support cluster mode

### Describe the feature you would like.
Integration tests in cluster mode cover all scenarios：
- [x] empty_rules
- [x] db
- [x] tbl
- [x] encrypt
- [x] shadow
- [x] readwrite_splitting
- [x] dbtbl_with_readwrite_splitting
- [x] dbtbl_with_readwrite_splitting_and_encrypt

**Comment by TeslaCN** [comment]
single rule cluster (docker, proxy, PostgreSQL, db) occasionally failed.
https://github.com/apache/shardingsphere/runs/7441972808?check_suite_focus=true

**Comment by TeslaCN** [comment]
https://github.com/apache/shardingsphere/runs/7442050177?check_suite_focus=true

**Comment by TeslaCN** [comment]
https://github.com/apache/shardingsphere/runs/7442413184?check_suite_focus=true

**Comment by soulasuna** [comment]
Is completed
