### ISSUE TITLE
How to encrypt shard configuration metadata before persistence

### ISSUE THREAD

**Issue by KevinZhanyang** [apache/shardingsphere#19117]
How do I encrypt persistent metadata?

**Comment by terrymanu** [comment]
Can you change the title to more make sense?

**Comment by KevinZhanyang** [comment]
> Can you change the title to more make sense?

ok

**Comment by terrymanu** [comment]
why need to encrypt the metadata?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
