### ISSUE TITLE
Error using select statement to obtain data volume

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#19133]
The version is shardingsphere-5.1.3-snapshot

This table is only a single table, and there is no sub table
error message：
`mysql> select prov_id from csys_company_buffer_info;
+---------+
| prov_id |
+---------+
| 63      |
。。。。
| 63      |
| 63      |
| 63      |
+---------+
563275 rows in set (0.88 sec)

mysql> select prov_id from csys_company_buffer_info;
+---------+
| prov_id |
+---------+
| 63      |
。。。
| 63      |
| 63      |
| 63      |
| 63      |
+---------+
501 rows in set (0.00 sec)

mysql> select count(*) from csys_company_buffer_info;
+----------+
| count(*) |
+----------+
|   563275 |
+----------+
1 row in set (0.25 sec)`

log:
"
[INFO ] 2022-07-14 14:36:07.631 [ShardingSphere-Command-20] ShardingSphere-SQL - Logic SQL: select prov_id from csys_company_buffer_info
[INFO ] 2022-07-14 14:36:07.631 [ShardingSphere-Command-20] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(table=Optional.empty, limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
[INFO ] 2022-07-14 14:36:07.631 [ShardingSphere-Command-20] ShardingSphere-SQL - Actual SQL: ds_2 ::: select prov_id from csys_company_buffer_info
"

**Comment by terrymanu** [comment]
What is the error message?

**Comment by novice-gamer** [comment]
There is no error message, which is a strange phenomenon when querying; The version used was pulled by the master a month ago

**Comment by strongduanmu** [comment]
Hi @novice-gamer, thank you for your feedback. What is the actual count of csys_company_buffer_info table?

**Comment by novice-gamer** [comment]
The actual quantity is 563275 lines
