### ISSUE TITLE
Does JDBC support auto table building

### ISSUE THREAD

**Issue by wklong** [apache/shardingsphere#19140]
Dear Community, 
# environment
spring boot: 2.6.9
shardingsphere: 5.1.1

#configuratio
`
spring.shardingsphere.datasource.names=shardingsphere_study,shardingsphere_study_1

spring.shardingsphere.datasource.shardingsphere_study.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.shardingsphere_study.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.shardingsphere_study.jdbc-url=jdbc:mysql://localhost:3306/shardingsphere_study
spring.shardingsphere.datasource.shardingsphere_study.username=xxx
spring.shardingsphere.datasource.shardingsphere_study.password=

spring.shardingsphere.datasource.shardingsphere_study_1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.shardingsphere_study_1.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.shardingsphere_study_1.jdbc-url=jdbc:mysql://localhost:3306/shardingsphere_study_1
spring.shardingsphere.datasource.shardingsphere_study_1.username=root
spring.shardingsphere.datasource.shardingsphere_study_1.password=

spring.shardingsphere.rules.sharding.binding-tables[0]=t_order,t_order_item
spring.shardingsphere.rules.sharding.broadcast-tables=t_address

spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=shardingsphere_study.t_order_$->{0..11}
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=code
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=t-order-inline
spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.column=order_code
spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.tables.t_order_item.actual-data-nodes=shardingsphere_study.t_order_item_$->{0..11}
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-column=order_code
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-algorithm-name=t-order-item-inline
spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.props.algorithm-expression=t_order_$->{code % 11}
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.props.algorithm-expression=t_order_item_$->{order_code % 11}
spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
`

**Comment by tuichenchuxin** [comment]
not support yet.
Please translate to english.

**Comment by wklong** [comment]
> not support yet. Please translate to english.

ths
