### ISSUE TITLE
mysql max min function with select table.* use the  subquery will lost some column

### ISSUE THREAD

**Issue by zt9788** [apache/shardingsphere#19144]
### Which version of ShardingSphere did you use?
version=5.1.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
```
#this sql will error
select k.* from (
select a,b,min(a_b) as startTime max(a_c) as endTime ,d,e,f,g (8 column)
 from table_number where ...... group by ...) k where ... 
```
**## Edit begin**
mybatis read just have a,b,d... ,but startTime,endTime will lost when **select k.*** 
I try to use 
```
select k.a,k.startTime....... from (...) k .... //it is right
```
<img width="522" alt="image" src="https://user-images.githubusercontent.com/15647179/178942035-41db6574-7965-47a1-9568-43711b2246ea.png">
The sharding use hasSelectExpandProjections will return 5 columns
when the else was 8 columns
<img width="845" alt="image" src="https://user-images.githubusercontent.com/15647179/178942697-c46007c8-0e8a-4fd5-be77-939221058756.png">

**Original question**
> How can i set `ShardingSphereResultSet`.`hasSelectExpandProjections` false or make it right?

**New**
It is a bug  or i have to chang all the * to cloumn name?

**Comment by RaigorJiang** [comment]
We generally use select * from table.

This issue has been inactive for a long time, and ShardingSphere has released several new versions, so I will close it.
Please try the latest version, and if the problem reproduces, please reopen it or submit a new one.
