### ISSUE TITLE
Replace change history by configuration migration tool 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19158]
The change history page [1] is too difficult to maintenance and understand.
I plan to remove the pages and provide the configuration migration tool fro old version to new version.
Any suggestions?

[1] https://shardingsphere.apache.org/document/current/en/reference/api-change-history/

**Comment by strongduanmu** [comment]
That's great, if there are different versions of the migration tool, users can quickly upgrade without caring about API changes.

**Comment by terrymanu** [comment]
I just remove change history now
