### ISSUE TITLE
A 404 appears inside the page link of readwrite-splitting by spring boot

### ISSUE THREAD

**Issue by wklong** [apache/shardingsphere#19172]
1. Enter the page ( https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/readwrite-splitting/ )
2. In this section (Dynamic Readwrite-Splitting)
<img width="831" alt="image" src="https://user-images.githubusercontent.com/11863572/179131658-58602f58-2d58-4feb-828c-616b8a3e36a8.png">
3. Click the red box in the image above,The error link address is  https://shardingsphere.apache.org/document/current/cn/features/readwrite-splitting/use-norms

**Comment by zjcnb** [comment]
@wklong It seems a problem, Can you submit a pull request to fix it?

**Comment by wklong** [comment]
I tried, but found that the reason for link 404 was the absence of use-norms directory rather than the incorrect link address, and I couldn't complete the writing of the file. Pls look at the following figure:

![image](https://user-images.githubusercontent.com/11863572/179137065-52359260-fe31-4832-93a6-7c85d06765e8.png)
