### ISSUE TITLE
Consider to add @ToString annotation for SQLStatement and SQLSegment

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#19189]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

According to the code conduct, each `SQLStatement` and `SQLSegment` implementation class must add the lombok `@ToString` annotation. If the implementation class inherits a parent class, you need to add the `callSuper = true` parameter.

At present, there are many SQLStatements and SQLSegments in the SQL Parser module without the `@ToString` annotation, which leads to the fact that when `sql-show` printing is enabled, only the address of the object can be printed, not the content of the object.

Therefore, we need to add `@ToString` annotations to SQLStatement and SQLSegment of different databases according to the specification——https://shardingsphere.apache.org/community/cn/contribute/code-conduct/.

- [x] Add `@ToString` annotation for common SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for MySQL SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for PostgreSQL SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for openGauss SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for SQLServer SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for Oracle SQLStatement and SQLSegment
- [x] Add `@ToString` annotation for SQL92 SQLStatement and SQLSegment

**Comment by chakkk309** [comment]
Hi, I want to try it.

**Comment by strongduanmu** [comment]
@chakkk309 Welcome, you can refer #19191 to finish other tasks.

**Comment by strongduanmu** [comment]
@Trydamere Of course, You can communicate with @chakkk309  about issue assignment.

**Comment by chakkk309** [comment]
Hi @Trydamere, I'm working on PostgreSQL, openGauss and SQLServer SQLStatement.

**Comment by Trydamere** [comment]
Hi @chakkk309, I will work on Oracle and SQL92 SQLStatement.

**Comment by strongduanmu** [comment]
@chakkk309 @Trydamere Thank you for your contribution. Since all subtasks has been finished, I will close this issue.
