### ISSUE TITLE
master have a compiler error

### ISSUE THREAD

**Issue by wklong** [apache/shardingsphere#19202]
Dear Community:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/11863572/179163363-fe80543c-727e-4aaa-b579-9fec04ea93ad.png">

See above, I went to the master code, refer to the https://shardingsphere.apache.org/community/cn/contribute/contributor/, but there is still a compiler error.
Global search, AdvancedDistSQLStatementLexer class was not found

**Comment by TeslaCN** [comment]
Please try the command in wiki 
https://github.com/apache/shardingsphere/wiki

**Comment by TeslaCN** [comment]
Close due to no response.
