### ISSUE TITLE
 Label related distsql syntax is not supported

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#19215]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_282
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: 7c67365b394d2e3ac562329b550c135c31ea764d
Commit Message: Avoid overhead of invoking method in Optional.orElse (#18921)
Branch: 7c67365b394d2e3ac562329b550c135c31ea764d
Build time: 2022-07-08T19:24:17+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Label related distsql syntax is not supported
### Actual behavior
Label related distsql syntax is supported
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
LABEL INSTANCE xxxx with olap,group_by;
UNLABEL INSTANCE xxxx ;
UNLABEL INSTANCE xxxx with group_by;
LABEL INSTANCE xxxx  with new_label;
RELABEL INSTANCE xxxx  with label_0, label_1;

**Comment by wsm12138** [comment]
https://github.com/apache/shardingsphere/pull/19152

**Comment by RaigorJiang** [comment]
Fixed by #19152.
