### ISSUE TITLE
为什么4.1.1版本 default-database-strategy.hint.algorithm-class-name不生效

### ISSUE THREAD

**Issue by kevin-jjc** [apache/shardingsphere#19231]
在4.1.1 版本中为什么不配置表分片的情况下单独配置default-database-strategy.hint.algorithm-class-name不生效？
我看了源码是不支持，之前如4.0.0都是支持的，是基于什么原因考虑呢？

**Comment by strongduanmu** [comment]
Please translate this issue to English, and submit issue according to template.
