### ISSUE TITLE
Complete dev-manual documents

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19241]
The contents of dev-manual is not clear enough, I just provide the template of the contents:

For each SPI: 

```
## SPI Class Name 

### Fully-qualified class name

[`org.apache.shardingsphere.xxx.XXX`](https://github.com/apache/shardingsphere/blob/master/xxx/xxx/XXX.java)

### Definition

[Definition descriptions]

### Implementation classes

| *Configuration Type* | *Description*         | *Fully-qualified class name* |
| --------------------- | ------------------ | ---------------------------- |
| XXX | description details | [`org.apache.shardingsphere.xxx.xxx.XXX`](https://github.com/apache/shardingsphere/blob/master/xxx/xxx/XXX.java) |
```

The English examples please reference [agent.en.md](https://github.com/apache/shardingsphere/blob/master/docs/document/content/dev-manual/agent.en.md) and [configuration.en.md](https://github.com/apache/shardingsphere/blob/master/docs/document/content/dev-manual/configuration.en.md)

The Chinese examples please reference [agent.cn.md](https://github.com/apache/shardingsphere/blob/master/docs/document/content/dev-manual/agent.cn.md) and [configuration.cn.md](https://github.com/apache/shardingsphere/blob/master/docs/document/content/dev-manual/configuration.cn.md)

The documents need to be updated are:

- [x] mode.en.md
- [x] mode.cn.md
- [x] kernel.en.md
- [ ] kernel.cn.md
- [x] data-source.en.md
- [ ] data-source.cn.md
- [ ] sql-parser.en.md, SQLVisitorFacade part is not completed yet
- [ ] sql-parser.cn.md
- [x] proxy.en.md
- [x] proxy.cn.md
- [x] sharding.en.md
- [ ] sharding.cn.md
- [x] readwrite-splitting.en.md
- [ ] readwrite-splitting.cn.md
- [x] ha.en.md
- [x] ha.cn.md
- [x] transaction.en.md
- [x] transaction.cn.md
- [x] sql-check.en.md
- [ ] sql-check.cn.md
- [x] encrypt.en.md
- [ ] encrypt.cn.md
- [x] shadow.en.md
- [ ] shadow.cn.md

**Comment by strongduanmu** [comment]
@Swastyy Welcome, I just assign this issue to you.
