### ISSUE TITLE
Split ShardingSphereDataSourceFactoryTest.assertCreateDataSourceWithDatabaseName() to more test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19252]
ShardingSphereDataSourceFactoryTest.assertCreateDataSourceWithDatabaseName() contains multiple calls of `ShardingSphereDataSourceFactory.createDataSource()`.

It is better to split them into different test cases. Please make one test case just assert one scenario.

The method should be split to:

- [ ] assertCreateDataSourceWithModeConfiguration
- [ ] assertCreateDataSourceWithDatabaseNameAndModeConfiguration
- [ ] assertCreateDataSourceWithAllParametersForMultipleDataSourcesWithDefaultDatabaseName
- [ ] assertCreateDataSourceWithAllParametersForMultipleDataSources
- [ ] assertCreateDataSourceWithAllParametersForSingleDataSourceWithDefaultDatabaseName
- [ ] assertCreateDataSourceWithAllParametersForSingleDataSource
- [ ] assertCreateDataSourceWithDefaultModeConfigurationForMultipleDataSources
- [ ] assertCreateDataSourceWithDatabaseNameAndDefaultModeConfigurationForMultipleDataSources
- [ ] assertCreateDataSourceWithDefaultModeConfigurationForSingleDataSource
- [ ] assertCreateDataSourceWithDatabaseNameAndDefaultModeConfigurationForSingleDataSource

**Comment by SalvadorRomo** [comment]
Hi!! Can I work on this, I'm a Software Engineer and I'm pretty interested in tis project. Regards!!

**Comment by yx9o** [comment]
@SalvadorRomo Welcome, assigned to you.

**Comment by SalvadorRomo** [comment]
thks!!
