### ISSUE TITLE
Add test case for MetaDataContextsFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19262]

**Comment by mayank-aggarwal28** [comment]
Can I try this issue?

**Comment by strongduanmu** [comment]
Hi @mayank-aggarwal28  , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by abhinav-koppula** [comment]
Hi @terrymanu  
Since the issue hasn't been worked upon since quite some time, I have taken a stab at it.
I have created PR - https://github.com/apache/shardingsphere/pull/20676. Can you please review it?

**Comment by terrymanu** [comment]
The issue has not finished, we need to assert the created meta data too.
I have already add todo during #20773

**Comment by abhinav-koppula** [comment]
> The issue has not finished, we need to assert the created meta data too. I have already add todo during #20773

@terrymanu - I have created a new PR - https://github.com/apache/shardingsphere/pull/20778. I have mocked the static methods `GlobalRulesBuilder.buildRules`, `ShardingSphereDatabasesFactory.create` and have added assertions for the metadata.
