### ISSUE TITLE
Sharding-jdbc Can't findById after insert the data

### ISSUE THREAD

**Issue by lyf200581105** [apache/shardingsphere#19278]
Using sharding-jdbc-core 4.1.1， only sharding tables
DB : AWS Aurora
Both read and write operations are using master endpoint
<dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-core</artifactId>
                <version>4.1.1</version>
</dependency>

Using Jmeter to do some performance test
step 1: call create API to  insert data to DB and return id
step 2: call get API with ID returned by step1 to query the data by Id, about 70% results showed data not found

But if pause about 30ms between step1 and step2, then all queries of step2 return successfully

And I did a similar test for no sharding tables, and all works fine.

I saw there is a statement for LOCAL Transaction as below
"There is no loss in performance, but strong consistency and final consistency cannot be guaranteed."

So is the insert delay I met caused by the strong consistency issue of local transaction? or did someone encounter a similar issue before?

**Comment by terrymanu** [comment]
The version 4.x is out of service, please try to version 5.x

**Comment by lyf200581105** [comment]
hi @terrymanu 
I had update to version 5.1.1., issue still exist
<dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core</artifactId>
                <version>5.1.1</version>
            </dependency>

below is part of the log:

![image](https://user-images.githubusercontent.com/49605984/179480940-e43dfd18-54e0-4eff-874b-378e17d85742.png)
