### ISSUE TITLE
Split SHOW INSTANCE MODE to SHOW MODE and SHOW INSTANCE

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19279]
`SHOW INSTANCE MODE` include mode and instance information, which are different domain.
Please split the DistSQL to `SHOW MODE` and `SHOW INSTANCE`.

**Comment by RaigorJiang** [comment]
`SHOW MODE` or `SHOW INSTANCE` will conflict with the PostgreSQL's syntax, new DistSQLs need to be designed.

**Comment by terrymanu** [comment]
> `SHOW MODE` or `SHOW INSTANCE` will conflict with the PostgreSQL's syntax, new DistSQLs need to be designed.

Which one conflicts with PostgreSQL?

**Comment by RaigorJiang** [comment]
Both will, since show statement of PostgreSQL conforms to this format.
Maybe consider `SHOW MODE INFO` & `SHOW INSTANCE INFO`

**Comment by terrymanu** [comment]
> Both will, since show statement of PostgreSQL conforms to this format.
> 
> > https://www.postgresql.org/docs/14/sql-show.html
> 
> Maybe consider `SHOW MODE INFO` & `SHOW INSTANCE INFO`

Yes SHOW XXX INFO is good

**Comment by yx9o** [comment]
let me do it.

**Comment by RaigorJiang** [comment]
Thank you  @yx9o
