### ISSUE TITLE
java not used @transactional annotation ,data cannot be updated

### ISSUE THREAD

**Issue by liushangqing9803** [apache/shardingsphere#19319]
Configured a local transaction, found that only @transactional can be added to the method to take effect, resulting in some single update operation in the project plus @transactional annotation, it feels very troublesome. I don't know if I haven't configured it myself, or does the local transaction of shardingsphere have to add @transactional annotation to the method to take effect?

version: ShardingSphere-Proxy 5.1.1

**Comment by liushangqing9803** [comment]
When the next transaction is executed, the update statement that does not open the transaction will commit the transaction together

**Comment by terrymanu** [comment]
Can you provide the demo to reproduce the problem?

**Comment by liushangqing9803** [comment]
```
@Service
public class StatusServiceImpl implements StatusService {
   //not used @Transactional , When this method is executed, the updated stusdent data cannot be seen
    @Override
    public Long update(Status status) {
        return studentsMapper.update(status);
    }

  //used @Transactional , normal execution
   @Override
    @Transactional
    public Long updateT(Status status) {
        return studentsMapper.update(status);
    }
}
```

**Comment by FlyingZC** [comment]
Can you give me a simple runnable demo to investigate this issue,thank you. @liushangqing9803

**Comment by TeslaCN** [comment]
Close due to no response.
