### ISSUE TITLE
IT single rule cluster (docker, proxy, MySQL, readwrite_splitting) occasionally failed

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19328]
### Expected behavior

Integration tests passed.

### Actual behavior

https://github.com/apache/shardingsphere/runs/7387546450?check_suite_focus=true

**Comment by TeslaCN** [comment]
https://github.com/apache/shardingsphere/runs/7382591576?check_suite_focus=true

**Comment by soulasuna** [comment]
Related #19103.
Close it first, then open it when it's fixed
