### ISSUE TITLE
Question about sharding-jdbc routing engine

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#19323]
I customized a sharding algorithm modulo the consistent hash of company_id. All tables in the database have the same sub-database sub-table algorithm, but the number of sub-tables is inconsistent. How does sharding-jdbc execute only one SQL query when doing a multi-table join query without configuring the binding table?

The execution log shows that sql is executed many times, and the way to execute sql is Cartesian product

**Comment by RaigorJiang** [comment]
The binding table needs to be configured, otherwise Cartesian product will appear in multi-table join.
