### ISSUE TITLE
How to configure administrator account and application connection account in server.yaml file

### ISSUE THREAD

**Issue by zhangchuangcheng0807** [apache/shardingsphere#19375]
Problem Description: 
    1.Hope the proxy account can access all databases in the shardingsphere-proxy middleware;
    2.I hope the app_001 account can only access the app_db_001 database in the shardingsphere-proxy middleware;
    3.I hope the app_002 account can only access the app_db_002 database in the shardingsphere-proxy middleware;
    4.The following configuration can only be used by app_001 and app_002 accounts, and proxy accounts cannot be used. It should be that the users and provider labels below cover the users and provider labels above.
    5.Is there any other way to achieve coexistence of administrator account and application account?

[root@localhost conf]# pwd
 /opt/shardingsphere-proxy-bin-5.1.2/conf
[root@localhost conf]# vim server.yaml
rules:
  - !AUTHORITY
    users:
       - proxy@%:passwd
    provider:
      type: ALL_PERMITTED

    users:
      - app_001@%:passwd01
      - app_002@%:passwd02
    provider:
      type: DATABASE_PERMITTED
      props:
        user-database-mappings: app_001@%=app_db_001, app_002@%=app_db_002

**Comment by terrymanu** [comment]
What is your version

**Comment by zhangchuangcheng0807** [comment]
> shardingsphere-proxy-bin-5.1.2

**Comment by RaigorJiang** [comment]
Hi @zhangchuangcheng0807 
I think your question is similar to #15711, we plan to grant privileges to admins via `*` so it will be easier.

**Comment by zhangchuangcheng0807** [comment]
> Hi @zhangchuangcheng0807 I think your question is similar to #15711, we plan to grant privileges to admins via `*` so it will be easier.
thanks, I will continue to pay attention to this function and look forward to the new version to provide a better solution.

**Comment by RaigorJiang** [comment]
Fixed in #19399.

**Comment by RaigorJiang** [comment]
Hi @zhangchuangcheng0807 
After this PR #19399 is merged, you can configure it like this:
```yaml
user-database-mappings: app_001@%=app_db_001, app_002@%=app_db_002, proxy@%=*, 
```
which means user `proxy@%` can access all databases.

**Comment by zhangchuangcheng0807** [comment]
> Hi @zhangchuangcheng0807 After this PR #19399 is merged, you can configure it like this:
> 
> ```yaml
> user-database-mappings: app_001@%=app_db_001, app_002@%=app_db_002, proxy@%=*, 
> ```
> 
> which means user `proxy@%` can access all databases.

thanks, I will test the new version as soon as it is released.
