### ISSUE TITLE
Move legacy version documents from homepage menu to new page

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19382]
There are lots of legacy document links in the homepage menu. It is better move them to a new page.
The home page only keep newest version and legacy versions.

The tasks are:

- [x] Create new page, move all legacy version documents here;
- [x] Change the top menu in homepage, remove all legacy versions and add the link for new page;
- [x] Change the bottom menu in homepage, remove all legacy versions and add the link for new page.

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by strongduanmu** [comment]
Welcome @runqi-zhao, I just assign this issue to you.

**Comment by runqi-zhao** [comment]
Hi @terrymanu @strongduanmu, When I try to run the doc's community through hugo in windows, I always get the following errors.
<.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState
Linux also has these errors, and after searching, it seems that I need to configure something to run it
Do I need to configure anything extra before running?

**Comment by terrymanu** [comment]
Do you use the same Hugo version?

**Comment by runqi-zhao** [comment]
@terrymanu I didn't find instructions about the version, using the latest version, which version I need to use?

**Comment by Jacob953** [comment]
> @terrymanu I didn't find instructions about the version, using the latest version, which version I need to use?

Hi, you need to degrade to 0.092 or lower to fix that. I could help you with this issue. )

**Comment by Jacob953** [comment]
In my opinion, there is no need to use Hugo for resolving this issue. I recommend checking config.toml first. )
