### ISSUE TITLE
Move FAQ from document to wiki page

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19383]
FAQ page always changes, but the document is pretty static.
It is better to split FAQ and document, just remove FAQ and move the content into GitHub Wiki.

The tasks are:

- [x] Add FAQ page in GitHub Wiki;
- [x] Move FAQ content into WIKi;
- [x] Add FAQ link into homepage's top menu (in document section);
- [ ] Add FAQ link into homepage's bottom menu (in document section).

**Comment by Swastyy** [comment]
Hi @terrymanu , I want to contribute on this.

**Comment by terrymanu** [comment]
Thank you, I just assign to you

**Comment by Swastyy** [comment]
But I don't see the option of `New Page` in the github wiki of the repository, then is there any other option for that?

**Comment by terrymanu** [comment]
@Swastyy I just add the initial page[1]

[1] https://github.com/apache/shardingsphere/wiki/FAQ

**Comment by Swastyy** [comment]
even the `edit` option is not there, I have added the screenshot here:
![image](https://user-images.githubusercontent.com/64654203/180777856-5901dc21-233a-409a-8200-3fb8b17d0de3.png)

**Comment by Swastyy** [comment]
Hi @terrymanu , I think only the collaboraters have access to do it, which can also be changed acc to [this](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis#:~:text=Only%20repository%20collaborators%20can%20edit,com%20to%20edit%20your%20wiki.)

**Comment by terrymanu** [comment]
@Swastyy Hi, our new committer. You have the permission now!

**Comment by Swastyy** [comment]
> @Swastyy Hi, our new committer. You have the permission now!

Thanks @terrymanu , I will surely complete it. 😄

**Comment by Swastyy** [comment]
Hi @terrymanu , do we need to remove the FAQ page from the documents as we are providing the links for the github wiki everywhere?

**Comment by TejaSaii** [comment]
I would like to contribute to this, can anyone explain me where is this homepage's top and bottom menu?
