### ISSUE TITLE
How to add data sources and related configurations without downtime in the production environment, and make it take effect?

### ISSUE THREAD

**Issue by Green524** [apache/shardingsphere#19390]
## Question
How to add data sources and related configurations without downtime in the production environment, and make it take effect?

**Comment by Green524** [comment]
> You can `add/alter/drop` datasource or `create/alter/drop` configuration by `DistSQL`, and i suggest you to use `ShardingSphere cluster` mode
thank you for your reply.
Is there any other way?

**Comment by Green524** [comment]
> You can `add/alter/drop` datasource or `create/alter/drop` configuration by `DistSQL`, and i suggest you to use `ShardingSphere cluster` mode

Thank you for your reply.
Is there any other way?

**Comment by RaigorJiang** [comment]
DistSQL is the only recommended way:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/
