### ISSUE TITLE
delete sql question

### ISSUE THREAD

**Issue by oulexue** [apache/shardingsphere#19409]
### Which version of ShardingSphere did you use?
sharding jdbc 5.1.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
when execute delete sql with
An error occurred during the delete SQL execution
 
### Actual behavior
 Cannot support Multiple-Table for '[tb_finance_auxiliary_type, tb_finance_voucher_auxiliary]'.### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
 DELETE FROM tb_finance_voucher_auxiliary where auxiliary_type in (SELECT id from tb_finance_auxiliary_type where sob_id=#{id});

**Comment by terrymanu** [comment]
Please split the SQL to 2 SQLs for each to be delete table.
