### ISSUE TITLE
How to associate updates

### ISSUE THREAD

**Issue by 1048933788** [apache/shardingsphere#19417]
## Question

**How to associate updates**
**version** 4.1.1
**for example：**
UPDATE table1 t1,
table2 t2 
SET t1.source_ext_a = t2.source_ext_a,
t1.source_ext_b = t2.source_ext_b,
t1.scene_code = t2.scene_code,
t1.source = t2.source,
t2.member_clean_status = 1 
WHERE
	t1.id = t2.id 
	AND t1.channel = t2.channel 
	AND t2.id >= 1 
	AND t2.id <= 1000000
	LIMIT 1

**exception** :  Cannot support Multiple-Table for '%s'.

最好能用中文回我哈哈，多谢啦

**Comment by TeslaCN** [comment]
ShardingSphere 4.1.1 is no longer maintained, please try the latest version.
