### ISSUE TITLE
Refactor scaling for better code reuse on new types of jobs

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19421]
Part of #13875.

Hi community,

After discussion with @tristaZero , we'll start to do it recently, it should be done on next release 5.1.3.

It could be easier to extend a new type of job after refactoring.

There will be some new issues linked here on next weeks, and refactoring detail wil be commented in new issues.

Refactoring overview will be put here later.

**Comment by strongduanmu** [comment]
Hi @sandynz , could we finish this issue in `5.1.3`?

**Comment by sandynz** [comment]
There might be few new PR, I'll close it now.
