### ISSUE TITLE
how can i set sql-mode through a conf file

### ISSUE THREAD

**Issue by panqizhen** [apache/shardingsphere#19424]
## Question
I am using shardingsphere-proxy with php and I need to set mysql sql-mode. now i can only set sql-mode after start shardingsphere-proxy, but it will be invalid after restart. I did not find any method in the docs and i can not understand the source code. How can i set sql-mode durable
![image](https://user-images.githubusercontent.com/22044790/180164741-fe4fd892-ced3-4a4b-b0c6-bcc6b640ec2d.png)

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Just set it in your database

**Comment by panqizhen** [comment]
> Just set it in your database

But i can not remove STRICT_TRANS_TABLES

**Comment by panqizhen** [comment]
> Just set it in your database

![image](https://user-images.githubusercontent.com/22044790/183861125-a552dc70-eafe-4ba1-9991-370b9d0d8af3.png)

hwo can i change this sql_mode and remove "STRICT_TRANS_TABLES"

**Comment by TeslaCN** [comment]
Try setting `jdbcCompliantTruncation=false` in JDBC URL.

Such as
```
jdbc:mysql://127.0.0.1:3306/ds?jdbcCompliantTruncation=false
```

**Comment by panqizhen** [comment]
> Try setting `jdbcCompliantTruncation=false` in JDBC URL.
> 
> Such as
> 
> ```
> jdbc:mysql://127.0.0.1:3306/ds?jdbcCompliantTruncation=false
> ```

Thank you very much! It works
