### ISSUE TITLE
A bug in the binding table at version 5.1.1

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#19423]
A bug in the binding table, the table is divided according to order_id and user_id, and an exception is displayed
![image](https://user-images.githubusercontent.com/45256940/180164441-a434424b-d690-404f-ab05-f7049099f5d6.png)

![image](https://user-images.githubusercontent.com/45256940/180164179-ab82b571-4586-43c3-bcf3-2bc1e70c3b7b.png)

**Comment by strongduanmu** [comment]
@marker-wu Which version do you use?

**Comment by marker-wu** [comment]
> @marker-wu Which version do you use?

5.1.1

**Comment by strongduanmu** [comment]
Ok, I will check this bug.

**Comment by inotgaoshou** [comment]
I don't quite understand the configuration or meaning of the binding table. My problem now is that the table users in the associated table cannot be recognized, because the users table is in another database。
add java code like this?
```
  shardingRuleConfig.getBroadcastTables().add("users");
```

**Comment by strongduanmu** [comment]
@marker-wu Can you try the latest version? I can not reproduce this exception with master branch.

**Comment by marker-wu** [comment]
> @marker-wu Can you try the latest version? I can not reproduce this exception with master branch.
I tried the latest version and it still doesn't work
The problem seems to be in the assignment of tableDataNode.prefix, the correct value should be t_order
![image](https://user-images.githubusercontent.com/45256940/182016574-fe7dcc12-cbb8-43d9-863d-edfe5f5c8cd8.png)

here are my physical table，Did you test with the same scene as I did?
![image](https://user-images.githubusercontent.com/45256940/182016927-3ff2733c-35a0-4eb7-a719-b3fb46705089.png)

**Comment by strongduanmu** [comment]
Why not use `t_order_00`, `t_order_01`?

**Comment by marker-wu** [comment]
> Why not use `t_order_00`, `t_order_01`?
I divided the table according to multiple fields
![image](https://user-images.githubusercontent.com/45256940/182017372-d51e5d79-a548-4355-94f5-14a6b52e0876.png)

**Comment by marker-wu** [comment]
It should be a problem with this regex，can I fork it and fix it?
![image](https://user-images.githubusercontent.com/45256940/182017651-9290fe1c-17f6-4213-9f46-7fa27b4eea7d.png)

**Comment by strongduanmu** [comment]
@marker-wu How can the prefix be accurately identified?

**Comment by marker-wu** [comment]
> @marker-wu How can the prefix be accurately identified?

enhanced on the basis of the original regular, the real table contains a set of rules: numbers and -or_ (can exist multiple times), and finally ends with number
original:      Pattern.compile("\\d+$");
modify to :  Pattern.compile("(\\d+[\\-_]){0,}(\\d+$)");

**Comment by strongduanmu** [comment]
@marker-wu Can you give some test case to show the result.

**Comment by marker-wu** [comment]
> @marker-wu Can you give some test case to show the result.

here are my test result：
![image](https://user-images.githubusercontent.com/45256940/182112493-0a0ab7ba-93af-424b-9903-3adc546d9bcd.png)

**Comment by strongduanmu** [comment]
@marker-wu Looks great, you can raise a pr to fix this bug.

**Comment by marker-wu** [comment]
> Looks great, you can raise a pr to fix this bug.

OK，I'll do it after get off work

**Comment by TW-haiyuan** [comment]
@strongduanmu  hi, i am using shardingsphere jdbc 5.1.1 and also meet this problem. But the type of binding tables' sharding key i used is string, now the shardingsphere use "\\d+$" to get actualDataNodes' suffix. I want to know why choose to use numbers as the rule, will other types (like string) be added in the future?

**Comment by strongduanmu** [comment]
@TW-haiyuan Adding a numeric suffix may be a hidden specification. I don't think we should pay too much attention to the suffix, after all users don't need to pay attention to the actual table, what do you think?

**Comment by marker-wu** [comment]
> @strongduanmu hi, i am using shardingsphere jdbc 5.1.1 and also meet this problem. But the type of binding tables' sharding key i used is string, now the shardingsphere use "\d+$" to get actualDataNodes' suffix. I want to know why choose to use numbers as the rule, will other types (like string) be added in the future?

Usually, the suffixes of the partition table are all numbers, and the binding table requires the same partition rules. Numbers are more friendly than letters during verification, and it is difficult to specify verification rules with letters. In addition, the purpose of our sub-table is for better routing later. Common sharding algorithms such as: hash modulo, time, range, etc. These suffixes are all numbers. If you want to divide the table according to letters, you can convert it to numbers by hash algorithm. this is my understanding

**Comment by tuichenchuxin** [comment]
I found if we use logic table like `t_order0226_1` and will get this logic prefix `t_order`.
This result is confusing. I think we should just support stripping the number endings.
