### ISSUE TITLE
Using a registry can cause unexpected things to happen

### ISSUE THREAD

**Issue by pengdafu** [apache/shardingsphere#19422]
### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy

### Expected behavior
Nodes A and B use ETCD as the registry。Show the timeline:
1. A run `create table t1 (id int);`
2. B run `show tables like `'t1'` to get the result
3. A run `drop table t1`, and then run `show tables like `'t1'` the result shows that t1 does not exist
4. B run `show tables like `'t1'` the result show that t1 exist，but run `select * from t1` show that t1 doesn't exist。Even weirder is if I create table t1 show that t1 already exist
5. reboot A and B，all appear normal。

expect B to behave normally when A drop table t1.

### Actual behavior

When A drop table t1, B behaves strangely

### Reason analyze (If you can)

Node B does not watch registry changes. As a result, memory remains after schema is deleted

**Comment by zjcnb** [comment]
@pengdafu Can you try it again with `5.1.2` version?

**Comment by pengdafu** [comment]
> 

I'll try it when I upgrade

**Comment by pengdafu** [comment]
After the upgrade, reports of the two node creation tables exist, but query reports do not exist

**Comment by zjcnb** [comment]
> After the upgrade, reports of the two node creation tables exist, but query reports do not exist

Can you show reproduce step to us?

**Comment by pengdafu** [comment]
![image](https://user-images.githubusercontent.com/28956520/180185778-06fd80c7-db14-4116-94a4-d994d323a0d3.png)

**Comment by pengdafu** [comment]
Using ZK is OK, only ETCD as registry is a problem, you said that supporting ETCD as registry is not quite correct.
