### ISSUE TITLE
Clean unused code in AbstractDataSourcePreparer

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19430]
After DataSourcePreparer implementations use PipelineDDLGenerator, some utility methods are not used any more, they could be removed.

List:
- getTableDefinitionSQLType
- replaceActualTableNameToLogicTableName

Double check list:
- addIfNotExistsForCreateTableSQL, looks it's still referenced in MySQLDataSourcePreparer, is it necessary?

**Comment by azexcy** [comment]
I will follow this issue

**Comment by azexcy** [comment]
MySQLDataSourcePreparer still need addIfNotExistsForCreateTableSQL, because PipelineDDLGenerator generate MySQL  create table script, use `show create table`, it will not append `if not exists` after `create table`.

**Comment by azexcy** [comment]
I will improve openGauss create table sql generate method too
