### ISSUE TITLE
Decouple TaskConfiguration from PrepareTargetSchemasParameter and PrepareTargetTablesParameter

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19440]
Part of  #19421.

Purpose:
- Decouple it for DataSourcePreparer common usage

### Current code snippets

TaskConfiguration contains dedicated jobConfig:
```
public final class TaskConfiguration {
    
    private final RuleAlteredJobConfiguration jobConfig;
```

TaskConfiguration is part of PrepareTargetSchemasParameter and PrepareTargetTablesParameter:
```
public final class PrepareTargetTablesParameter {
    
    private final TaskConfiguration taskConfig;
```

```
public final class PrepareTargetSchemasParameter {
    
    private final TaskConfiguration taskConfig;
```

`taskConfig` is referenced in `AbstractDataSourcePreparer` etc.

### Possible changes

Remove TaskConfiguration reference from PrepareTargetSchemasParameter and PrepareTargetTablesParameter.
Add needed fields in Parameter classes.

**Comment by huangdx0726** [comment]
Can i try?

**Comment by sandynz** [comment]
> Can i try?

Hi @huangdx0726 , welcome!

But it's an urgent task, do you plan to solve it on next days?

**Comment by huangdx0726** [comment]
ok

**Comment by sandynz** [comment]
> ok

Thanks, just assigned to you.
