### ISSUE TITLE
Add more unit test for AlgorithmProvidedShardingRuleConfigurationChecker and ShardingRuleConfigurationChecker

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#19463]
After pr #19462 was merged, we need to add more unit tests for `AlgorithmProvidedShardingRuleConfigurationChecker` and `ShardingRuleConfigurationChecker`. Unit tests need to be able to cover various normal and abnormal scenarios in AbstractShardingRuleConfigurationChecker.

The target method for unit testing is as follows:

- [ ] AlgorithmProvidedShardingRuleConfigurationChecker#check
- [ ] ShardingRuleConfigurationChecker#check

**Comment by xuup** [comment]
Hi, could you please assign that to me?

**Comment by yx9o** [comment]
@xuup Thank you.
