### ISSUE TITLE
ShardingShpere-proxy default driver

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#19466]
version:sharesphere-proxy-5.1.1
When I start sharesphere proxy without config config-sharding.yml,beause I want to push zookeeper by myself.And there's no log like DataBase name is 'PostgreSQL' ,version is `9.6.22`,then I push zookeeper by myself.It cann't connection,unless I restart proxy and have the log DataBase name is 'PostgreSQL'.So,the default driver looks doesn't work unless pre config the database source.

**Comment by RaigorJiang** [comment]
Hi @koala775 
The default database type of Proxy is MySQL.
If you want it to start with the PostgreSQL protocol, configure it in `server.yaml`
```yaml
props:
   proxy-frontend-database-protocol-type: PostgreSQL
```
Also you can refer to this issue: #18578

Of course, if there is already a data source at startup, this configuration is not required.

**Comment by koala775** [comment]
Thank you for replaying,it's work.By the way,where to look full server.yaml configure.

**Comment by RaigorJiang** [comment]
> Thank you for replaying,it's work.By the way,where to look full server.yaml configure .

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/yaml-config/props/

It may not be complete enough and requires us to keep updating it.

**Comment by RaigorJiang** [comment]
Hi @koala775 , Please close this issue if your problem is solved, thank you!

**Comment by koala775** [comment]
Thank you,have resolved.
