### ISSUE TITLE
Consider merge RuleAlteredJobSchedulerCenter into RuleAlteredJob and RuleAlteredJobCenter

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19460]
Part of  #19421.

Since there's RuleAlteredJobCenter to manage all jobs, and job shards (RuleAlteredJobScheduler) could be managed by RuleAlteredJob itself.

Then remove RuleAlteredJobSchedulerCenter.

It could be done after PR 19457 completed.

**Comment by sandynz** [comment]
@azexcy Could you help to follow it?

**Comment by azexcy** [comment]
OK, I will follow it.
