### ISSUE TITLE
Clean unused classes for data source preparer

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19464]
After DataSourcePreparer implementations use PipelineDDLGenerator, some classes are not used any more, they could be removed.

List:
- ActualTableDefinition
- TableDefinitionSQLType

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by yx9o** [comment]
@runqi-zhao Thank you.
