### ISSUE TITLE
the username for resource cannot have '-', or it will return ERROR

### ISSUE THREAD

**Issue by crazyboy988** [apache/shardingsphere#19475]
## Feature Request

**For English only**, other languages will not accept.

`ADD RESOURCE test0_proxy_test_write_ds (
    URL="jdbc:mysql://test0-mysql-master.test0:3306/proxy-test?serverTimezone=UTC&useSSL=false",
    USER=proxy-test-user,
    PASSWORD=proxy-test-password
);`

it returns：ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'

but user and password is correct!!! DistSQL proxy can not surport '-'.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by RaigorJiang** [comment]
Hi @crazyboy988 
Thanks for your feedback.

Currently username does not support any special characters, and passwords can already support special characters by adding double quotes.

Also, a format definition for DistSQL parameters is in the works (#18811), and will soon support arbitrary legal strings as well.

**Comment by RaigorJiang** [comment]
Updated in https://github.com/apache/shardingsphere/issues/18811.
