### ISSUE TITLE
keywords in proxy which can't be used as column name within a mysql select sql

### ISSUE THREAD

**Issue by ruanyg** [apache/shardingsphere#19478]
### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Behavior
these keywords shown below can't be used as column name within a mysql select sql
```
GROUPS
RANK
CUBE
NTH_VALUE
SYSTEM
MYSQL_MAIN
ROW_NUMBER
OVER
PERCENT_RANK
BIT_XOR
LAG
UTC_DATE
UTC_TIME
ROW
GROUPING
OF
ROWS
EMPTY
FIRST_VALUE
FUNCTION
DENSE_RANK
CUME_DIST
WINDOW
JSON_TABLE
LEAD
RECURSIVE
NTILE
LATERAL
EXCEPT
UTC_TIMESTAMP
```

### Reason analyze (If you can)
in grammatical level they aren't regarded as _identifier_
<img width="829" alt="image" src="https://user-images.githubusercontent.com/19629642/180442823-d10b1799-0ea9-48dc-a949-0587cd65ed5b.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Just execute a select sql having one or more keywords described before as column name, for example
`select rank from student;`
and then error occurs
```
mysql> select rank from student;
ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
```

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by csonezp** [comment]
These sql contain reserved words, and return error is expected.
Do you mean the error information is wrong?
@ruanyg

**Comment by mingyifei** [comment]
> 

If the MySQL client can query, it should be consistent with it.

**Comment by ruanyg** [comment]
> These sql contain reserved words, and return error is expected. Do you mean the error information is wrong? @ruanyg

They can execute correctly when connect to mysql directly without proxy, the behaviors between mysql and proxy are inconsistent.

**Comment by liujia13142324** [comment]
I also meed the same problem in ShardingSphere-JDBC, because the column name such as rank is defined in the table. If I remove the rank column from the query, ShardingSphere-JDBC can work normally.
(在ShardingSphere-JDBC中我也碰到了同样的问题，因为表中定义了rank这样的列名。如果我在查询中去掉rank列，ShardingSphere-JDBC能正常查询)
@csonezp

**Comment by liujia13142324** [comment]
ShardingSphere-JDBC version: 5.1.2

**Comment by mingyifei** [comment]
Let me add:  ORDER

**Comment by tuichenchuxin** [comment]
I'll check this. Thanks.

**Comment by tuichenchuxin** [comment]
I tried mysql 8 and this keyword can be supported with mysql but not supported by shardingsphere.
`MYSQL_MAIN` `UTC_DATE` `UTC_TIME` `UTC_TIMESTAMP`.
Others can't be supported for mysql 8.
