### ISSUE TITLE
Sharding-jdbc Can't findById after insert the data

### ISSUE THREAD

**Issue by lyf200581105** [apache/shardingsphere#19503]
Using shardingsphere-jdbc-core 5.1.2 + spring jpa， only sharding tables, using LOCAL Transaction only.
DB: AWS Aurora
Both read and write operations are using the master endpoint

Using Jmeter to do some performance test
step 1: call create API to insert data to DB and return id
step 2: call get API with ID returned by step1 to query the data by Id, about 70% of results showed data not found(please refer to attached log)
![image](https://user-images.githubusercontent.com/49605984/180646918-56598000-47bb-4ee8-b811-2a2f93cfafe5.png)

But if pause about 30ms between step1 and step2,  or or add **@Transactional** with getting method(like below ), then all queries of step2 return successfully 
   @Transactional
    @Override
    public TestModel getById(Long id) {
        Optional<TestModel> optional = repository.findById(id);
        if(!optional.isPresent()) {
            throw new RuntimeException("TestModel [" + id + "] not found");
        }
        return optional.get();
    }

I saw there is a statement for LOCAL Transaction as below
"There is no loss in performance, but strong consistency and final consistency cannot be guaranteed."

Is this behavior correct? Need to use @transactional  for query operation to guarantee consistency?

**Comment by strongduanmu** [comment]
Hi @lyf200581105, thank you for your feedback.  Can you show the original sql which send to ShardingSphere?

**Comment by lyf200581105** [comment]
> Hi @lyf200581105, thank you for your feedback. Can you show the original sql which send to ShardingSphere?

Thanks for your reply.
I'm using jpa API： repository.findById(id), the original search sql is like below:

Hibernate: select testmodel0_.id as id1_0_0_, testmodel0_.create_time as create_t2_0_0_, testmodel0_.last_update_time as last_upd3_0_0_, testmodel0_.model_name as model_na4_0_0_, testmodel0_.module_res_id as module_r5_0_0_ from db_test testmodel0_ where testmodel0_.id=?

2022-07-19T08:57:54.998 INFO [http-apr-0.0.0.0-8080-exec-9] org.apache.shardingsphere.infra.executor.sql.log.SQLLogger.log-74 | Logic SQL: select testmodel0_.id as id1_0_0_, testmodel0_.create_time as create_t2_0_0_, testmodel0_.last_update_time as last_upd3_0_0_, testmodel0_.model_name as model_na4_0_0_, testmodel0_.module_res_id as module_r5_0_0_ from db_test testmodel0_ where testmodel0_.id=?

**Comment by lyf200581105** [comment]
hello
Any update for this?

**Comment by TeslaCN** [comment]
From your logs, it seems that insert and select were executed in different threads, so probably 2 threads were using different db connections. If the transaction isolation is not `READ UNCOMMITTED`, how could you make sure the select operation is performed after transaction committed?

**Comment by lyf200581105** [comment]
@TeslaCN  Actually the select thread begins after the insert thread is executed, and it uses the insert result to search (id is generated by insert operation), which means when the select thread starts, the insert transaction is already committed.

**Comment by TeslaCN** [comment]
Could you show us your configuration?
Consider enabling logs by `sql-show: true` and check actual SQL execution.

**Comment by RaigorJiang** [comment]
Closed due to no response.
