### ISSUE TITLE
The io.takari:maven plugin should probably be removed

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#19510]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- A long-unupdated Maven plugin is used in the `pom.xml` of the current master branch.
```
                <plugin> 
                     <groupId>io.takari</groupId> 
                     <artifactId>maven</artifactId> 
                     <version>${takari-maven-plugin.version}</version> 
                 </plugin>
```

- According to the information provided at https://mvnrepository.com/artifact/io.takari/maven/0.7.7 , this plugin actually serves `io.takari:maven-wrapper:0.5.6` which has been discontinued for maintenance.

- The Maven Wrapper has been replaced with the version under Apache Org at https://github.com/apache/shardingsphere/pull/14258 , so this plugin seems moot and removing it is expected behavior.

- https://github.com/apache/shardingsphere/pull/14258 doesn't remove `.mvn/wrapper/MavenWrapperDownloader.java` , which doesn't seem like a reasonable choice.  Since `./mvnw` will automatically download the Maven Wrapper JAR via `wget` or `curl` if `MavenWrapperDownloader.java` does not exist, this class is not needed in my understanding.

- Switching the Maven Wrapper from 3.8.4 to 3.8.5 is also an expected behavior, and a consistent Maven version with `maven-mvnd:0.8.0` will help mvnd users to speed up local builds. Refer to https://github.com/apache/maven-mvnd/releases/tag/0.8.0 .

**Comment by terrymanu** [comment]
Awesome, could you try to remove it and upgrade the version of mvnw as a pull request?

**Comment by linghengqian** [comment]
Yes, I am working on this issue.
