### ISSUE TITLE
How does DistSQL simplify logical table configuration

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#19521]
Which version of ShardingSphere did you use?
5.1.2 （helm cluster）

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Expected behavior
DistSQL has a simple logical table configuration.

Actual behavior
For the case where only the database is shard.
Configuration is as
 
```
create database ds;
use ds;

ADD RESOURCE ds_abc (
    HOST=192.168.0.1,
    PORT=3306,
    DB=ds_abc,
    USER=root,
    PASSWORD=123456
);

ADD RESOURCE ds_bcd (
    HOST=192.168.0.1,
    PORT=3306,
    DB=ds_bcd,
    USER=root,
    PASSWORD=123456
);

CREATE SHARDING ALGORITHM database_inline (
	TYPE(NAME=inline,PROPERTIES("algorithm-expression"="ds_${tenant_code}"))
);
CREATE DEFAULT SHARDING DATABASE STRATEGY (
	TYPE = standard,SHARDING_COLUMN=tenant_code,SHARDING_ALGORITHM=database_inline
);

CREATE SHARDING TABLE RULE order_test (
	datanodes("ds_${['abc','bcd']}.order_test")
)
CREATE SHARDING TABLE RULE user_test (
	datanodes("ds_${['abc','bcd']}.user_test")
)
```

How do I use DistSQL if I have many databases and tables that need to be dynamically sharded?

**Comment by terrymanu** [comment]
Why need to simply DistSQL only?
DistSQL is same with standard SQL, do you consider about use SQL to simply create table dynamically?

**Comment by Bingai077** [comment]
We need to use DistSQL to dynamically modify the database sharding rules.

**Comment by terrymanu** [comment]
It is better to use code dynamic DistSQL, but DistSQL should be statically.

**Comment by Bingai077** [comment]
It mainly involves the configuration of logical table routes

**Comment by terrymanu** [comment]
> It mainly involves the configuration of logical table routes

So, how about `It is better to generate DistSQL from programing dynamically, but DistSQL should be statically.`

**Comment by Bingai077** [comment]
In this case, I find the table rule configuration too tedious. The default value cannot be set null.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
