### ISSUE TITLE
Two problems with proxy

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#19529]
1、In cluster mode, the configuration file under conf has been modified, but the proxy configuration is not modified through DistSQL query. Why?
2、The distributed primary key generation strategy is configured as snowflake algorithm, Do you still need to specify the value of primary key in insert statement, please give an INSERT SQL, thank you.

**Comment by terrymanu** [comment]
For search friendly reason, could split them to 2 issues and give them a better title?

**Comment by PeiMouRen** [comment]
split
