### ISSUE TITLE
Project can not build

### ISSUE THREAD

**Issue by pengpengno** [apache/shardingsphere#19527]
## Question
branch： master
version: 5.1.3-SNAPSHOT
jdk:1.8_131
maven:3.6.3
mavenrepository:https://maven.aliyun.com/repository/public
when i try to build shardingsphere project in idea, it happens lots of mistakes
such as below
![image](https://user-images.githubusercontent.com/48426117/180761795-70ac9a86-2daa-45e2-9c6c-40185436ab97.png)
 the main question is  how to build the project normal,
this problem is cause in my env?
hope the develops help

**Comment by linghengqian** [comment]
If you are using Windows, you will need to use Maven to build the project first, as suggested by the Github Wiki.  An obvious quick command is 

```
./mvnw -B clean install -D"maven.javadoc.skip"=true -D"rat.skip"=true -D"jacoco.skip"=true -D"spotless.apply.  skip"=true
```

**Comment by terrymanu** [comment]
Please execute mvn install to generate the generated antlr class first.
Just see https://shardingsphere.apache.org/document/current/en/reference/faq/
