### ISSUE TITLE
gitpod integration

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#19536]
## Question
Somedays ago around 5 to 10, I saw a PR which included the project integration to gitpod, unfortunately I cannot find it now. My thought is if we have merged it then there should be a detailed explanation of how to use it should be there in contributors guide.

**Comment by linghengqian** [comment]
- Gitpod is indeed the de facto standard for browser-side IDEs to some extent.  

- But https://github.com/apache/shardingsphere/pull/19360 looks to change the useless part in `README.md`.  I must point out that even without creating `.gitpod.yml`, users can open the specified branch of Apache ShardingSphere directly in the browser.

**Comment by Swastyy** [comment]
Hi @linghengqian , I have opened my fork in gitpod but there happens to have issues of dependencies so I thought after integration it gets resolved, but maybe not because this PR does nothing I see.

**Comment by linghengqian** [comment]
- According to https://www.gitpod.io/docs/languages/java, configuring a `.gitpod.yml` with JDK does seem inevitable.  Refer to https://www.gitpod.io/docs/languages/java.  

- But the previous PR set JDK to 17, I think it should be consistent with `pom.xml`, use JDK8.  

- Also, is it really a requirement to use Gitpod?  It is widely used in Gitlab, but it does not reflect the integration for easy getting started in Github.

**Comment by TeslaCN** [comment]
Does gitpod have any advantage over the GitHub Codespaces?

**Comment by Siddhant-K-code** [comment]
👋 from Gitpod

> Does gitpod have any advantage over the GitHub Codespaces? I used to submit simple codes by Codespaces and I think it is enough. For more complicate scenario, I think the WEB IDE is incapable for now.

Yeah, It's an Open Source Product, with Support of multiple IDEs like IntelliJ & faster prebuilds with much lesser pricing

Read More: [Gitpod vs Codespaces](https://www.gitpod.io/vs/github-codespaces)

---

@Swastyy @linghengqian You Can Test out the Gitpod Configuration Setup on our fork: https://gitpod.io/#https://github.com/gitpod-forks/apache-shardingsphere

**Comment by linghengqian** [comment]
- Unless GitHub's support for Gitpod reaches the same level as GitLab, at least it can be accessed directly from the project homepage. I think it is too early to discuss this.
- ![image](https://user-images.githubusercontent.com/20187731/182296071-9f0fea73-1cee-4f4c-9d27-22b9ab505f9c.png)
- ![image](https://user-images.githubusercontent.com/20187731/182296122-edd337c6-1688-4e9a-b62e-e172f4829a03.png)

**Comment by Swastyy** [comment]
Hello everyone, I agree with @linghengqian and @TeslaCN as the gitpod's support is not very effective and useful for now. Lets see if it helps in future to do development.
Also @Siddhant-K-code , few months back I used gitpod for a document development it worked fine but now why it shows every file as changed which contains an image? and how to fix it?

**Comment by linghengqian** [comment]
I prefer to put discussions of changes to the Gitpod integration experience in their own discussion forum on github.com.  This issue can be closed.
