### ISSUE TITLE
Cannot bench ShardingSphere-Proxy PostgreSQL by pgbench

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19566]
### Which version of ShardingSphere did you use?

master - ed2025c84518de8a39dd015a55a1119e79828373

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

pgbench worked.

### Actual behavior

```
pgbench -i -h 127.0.0.1 -p55432 -Upostgres postgres
```

```
dropping old tables...
creating tables...
generating data (client-side)...
pgbench: fatal: query failed: ERROR:  org.apache.shardingsphere.proxy.backend.exception.TableModifyInTransactionException
pgbench: query was: truncate table pgbench_accounts, pgbench_branches, pgbench_history, pgbench_tellers
```

About pgbench https://www.postgresql.org/docs/current/pgbench.html

**Comment by FlyingZC** [comment]
I want to investigate the issue,how can I reproduce this problem,execute the command `pgbench` directly on the proxy?

**Comment by TeslaCN** [comment]
@FlyingZC Welcome. This issue is related to https://github.com/apache/shardingsphere/pull/11545

**Comment by FlyingZC** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/19788130/181679529-d1601685-6161-4b74-8c22-746105143d62.png">
I have reproduced this problem locally.

**Comment by FlyingZC** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/19788130/181694193-b095eef1-7ca7-477d-9797-897b80ee12fb.png">

**Comment by FlyingZC** [comment]
1.When I use local transaction,the `begin; truncate...;` cannot be executed successfully,The method of `isExecuteDDLInPostgreSQLOpenGaussTransaction` reported an error;
2.When I use XA transaction,the `begin; truncate...;` cannot be executed successfully, The method of `isExecuteDDLInXATransaction` reported an error;
3.I think ss does not support DDL operations in XA transactions or pgsql/opengauss transactions now.

**Comment by TeslaCN** [comment]
Throwing TableModifyInTransactionException is because PostgreSQL can rollback DDL like the following:
```sql
begin;
drop table t;
rollback;
```
But ShardingSphere's meta data cannot be rollback.
If `truncate` won't change the meta data, may be we could allow it could be executed in transaction.

**Comment by FlyingZC** [comment]
> Throwing TableModifyInTransactionException is because PostgreSQL can rollback DDL like the following:
> 
> ```sql
> begin;
> drop table t;
> rollback;
> ```
> 
> But ShardingSphere's meta data cannot be rollback. If `truncate` won't change the meta data, may be we could allow it could be executed in transaction.

I will try.

**Comment by FlyingZC** [comment]
Supported `truncate` sql in https://github.com/apache/shardingsphere/pull/19746
