### ISSUE TITLE
Consider adapting the SQL Federation feature for openGauss databases

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#19580]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Currently, ShardingSphere uses Calcite JDBC to implement the SQL federation feature, and provides basic support for MySQL and PostgreSQL database. Due to the importance of the openGauss database, we decided to adapt the SQL federation feature to the openGuass database. In order to adapt to the openGauss database, we need to complete the following subtasks.

- [x] Complete the remaining tasks in issue #13091 to make query optimization and ShardingSphere work well together;
- [x] Optimize openGuass select statement parsing——https://opengauss.org/zh/docs/latest/docs/Developerguide/SELECT.html;
- [x] Convert openGuass statement syntax tree to calcite syntax tree
- [x] SQL Federation feature adapts to openGauss data type
- [x] SQL Federation feature supports distributed transaction management
- [x] SQL Federation feature supports cross-database views

**Comment by boyjoy1127** [comment]
Mark this.

**Comment by strongduanmu** [comment]
Hi @boyjoy1127, welcome to join this task. 😀

**Comment by strongduanmu** [comment]
@FlyingZC I will assign this issue to you.

**Comment by strongduanmu** [comment]
All tasks has been finished, so I will close this issue.
