### ISSUE TITLE
Remove spring dependency in shardingsphere-integration-test-scaling

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19612]
There is JDBCTemplate class using in shardingsphere-integration-test-scaling which is unnecessary. 
Please use raw JDBC to access database and keep the module's dependency more simple.

**Comment by taojintianxia** [comment]
please assign to me

**Comment by taojintianxia** [comment]
this may taking a lot of time, let's lower the priority and focus on env refactor.

**Comment by strongduanmu** [comment]
Hi @taojintianxia , could we finish this issue in `5.1.3`?

**Comment by TeslaCN** [comment]
Tests are not in release scope. We could remove the milestone.

**Comment by TeslaCN** [comment]
Close via #22890.
