### ISSUE TITLE
Merge all atomic container into shardingsphere-integration-test-env module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19615]

**Comment by taojintianxia** [comment]
please assign to me

**Comment by taojintianxia** [comment]
this is a huge issue. splitt into 4 sub issues :

use env to manage the properties in scaling IT:
https://github.com/apache/shardingsphere/issues/19958

use env to manage the container in scaling IT:
https://github.com/apache/shardingsphere/issues/19956

**Comment by strongduanmu** [comment]
Hi @taojintianxia , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by taojintianxia** [comment]
this could be closed. related issue has  been finished.
