### ISSUE TITLE
Merge storage container's config file to shardingsphere-integration-test-env module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19626]
The config file (for example: my.cnf, postgresql.conf) is in multiple modules, please merge them into shardingsphere-integration-test-env module

**Comment by taojintianxia** [comment]
please assign to me

**Comment by strongduanmu** [comment]
Hi @taojintianxia , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by taojintianxia** [comment]
the original design has been changed. this should be closed.
