### ISSUE TITLE
5.x版本的【default datasource name】配置变更

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#19635]
我有一些不需要分片的表，看FAQ说是这些表不用在rules里指定，但是查看日志，sql没有路由到正确的datasource中，4.x版本是有一个[default-datasource-name]配置来解决这个问题，5.x版本怎么解决呢？
![image](https://user-images.githubusercontent.com/46043280/181442024-e61b4584-3bcb-49d1-b655-d3291727a5e3.png)

**Comment by PeiMouRen** [comment]
![image](https://user-images.githubusercontent.com/46043280/181442557-e243a75b-ce03-4eb7-98a8-75e2d10be64b.png)

**Comment by strongduanmu** [comment]
Please translate this issue to English.
