### ISSUE TITLE
PHP connection proxy found that can not correctly query data

### ISSUE THREAD

**Issue by mini1798** [apache/shardingsphere#19633]
## Question

When I use PHP version 5.7, the query data found not correct query.Returns the result list is empty！

sql -> select * from order where order_id in (12) and status>0 order by id desc;

Have bosses know how to solve

**Comment by RaigorJiang** [comment]
Hi @mini1798 
Thank you for your feedback, but please use the issue template to ask questions.
Including providing information such as the `version` and `configuration` you used, and also the table structure, preferably including a way to reproduce the issue, so that you can get better help.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
