### ISSUE TITLE
[Proxy 5.1.2]Non-sharded tables are not automatically recognized

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#19645]
I have three data sources:ds0、ds1、ds2，there are also non-sharded tables(like t_test) in ds2, but when i select t_test, shardingsphere-proxy routed to the ds0 or ds1, It's not routed to ds2, why is that?
Proxy:5.1.2 
mode:cluster with zookeeper
Is already contained t_test in the metadata.

**Comment by RaigorJiang** [comment]
Thanks for your feedback.
No one else has encountered this problem. It may be caused by a certain configuration. Can you provide your configuration for analysis?

**Comment by PeiMouRen** [comment]
The problem has been solved，because I'm using the PG database，so I need to specify the schema in SQL, otherwise,the default public schema will be used.
eg:
```sql
# pg
select * from myschema.t_order;
```

**Comment by RaigorJiang** [comment]
> ```sql
> # pg
> select * from myschema.t_order;
> ```

ok, your feedback is important, thank you!
