### ISSUE TITLE
Complete unit test for MySQLAdminExecutorCreator

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19667]
## Unit tests

Related to https://github.com/apache/shardingsphere/pull/19638.

Complete the unit test https://github.com/apache/shardingsphere/blob/b6fa71fc0b202be70f347b164e0c5bc22bec7c0a/shardingsphere-proxy/shardingsphere-proxy-backend/src/test/java/org/apache/shardingsphere/proxy/backend/handler/admin/mysql/MySQLAdminExecutorCreatorTest.java to make it cover all lines in `MySQLAdminExecutorCreator`.

**Comment by huangdx0726** [comment]
I will work on it
