### ISSUE TITLE
Whether you plan to support to  remove outage DB node automatically?

### ISSUE THREAD

**Issue by broccolik** [apache/shardingsphere#19676]
our test,
we have two DB nodes, a master and a slave, when one of them was broken,The application is not working properly.
so,Whether you plan to support to  remove outage DB node automatically,and work properly with the left one?

**Comment by TeslaCN** [comment]
Have you tried the HA of ShardingSphere?
https://shardingsphere.apache.org/document/current/en/features/ha/

**Comment by broccolik** [comment]
> Have you tried the HA of ShardingSphere? https://shardingsphere.apache.org/document/current/en/features/ha/

no
