### ISSUE TITLE
Enhancement test for kernel

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#19691]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No

### Describe the feature you would like.
Enhancement test for kernel in integretion test.

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin , could we finish this issue in `5.1.3`?

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin 
Is this still opening?

**Comment by tuichenchuxin** [comment]
> Hi @tuichenchuxin Is this still opening?

Yes

**Comment by strongduanmu** [comment]
Since this issue is too big, we will split it into new issues, so I will close it.
