### ISSUE TITLE
Add more assertions for ConfigurationPropertiesTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19734]
Add missing assertions with `assertGetValue` and `assertGetDefaultValue` methods:

- [ ] PROXY_BACKEND_QUERY_FETCH_SIZE
- [ ] PROXY_FRONTEND_EXECUTOR_SIZE
- [ ] PROXY_BACKEND_EXECUTOR_SUITABLE
- [ ] PROXY_FRONTEND_MAX_CONNECTIONS
- [ ] PROXY_BACKEND_DRIVER_TYPE
- [ ] PROXY_MYSQL_DEFAULT_VERSION
- [ ] PROXY_DEFAULT_PORT
- [ ] PROXY_NETTY_BACKLOG

**Comment by huangdx0726** [comment]
I will work on it

**Comment by luctech111** [comment]
@terrymanu Can i try this issue as my first issue, thanks.

**Comment by newboy2004** [comment]
i will try this issue please assign it to me?
