### ISSUE TITLE
Remove jobConfig from TaskConfiguration for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19742]
Part of #19421.

Current code:
```
public final class TaskConfiguration {
    
    private final RuleAlteredJobConfiguration jobConfig;
    
    private final DumperConfiguration dumperConfig;
    
    private final ImporterConfiguration importerConfig;
}
```

And `jobConfig` is used in 2 places, in RuleAlteredJobPreparer:
```
        IncrementalTask incrementalTask = new IncrementalTask(taskConfig.getJobConfig().getConcurrency(),
                taskConfig.getDumperConfig(), taskConfig.getImporterConfig(), pipelineChannelCreator, dataSourceManager, sourceMetaDataLoader, incrementalDumperExecuteEngine, persistCallback);

...

        String databaseType = taskConfig.getJobConfig().getSourceDatabaseType();
        DataSource dataSource = dataSourceManager.getDataSource(taskConfig.getDumperConfig().getDataSourceConfig());
        return PositionInitializerFactory.getInstance(databaseType).init(dataSource);
```
`int concurrency` and `sourceDatabaseType`.

`TaskConfiguration` is planned to be common class used for some types of jobs, but `jobConfig` is not common, there're 2 possible solutions:
1. Change `jobConfig` type to PipelineJobConfiguration, and add some common methods in PipelineJobConfiguration.
2. Extract fields into `dumperConfig` or `importerConfig` and remove `jobConfig` from `TaskConfiguration`.

Solution 2 is preferred.

Possible changes:
- Add `concurrency` in `ImporterConfiguration`
- Use `taskConfig.getDumperConfig().getDataSourceConfig().getDatabaseType()` to replace `taskConfig.getJobConfig().getSourceDatabaseType()`
- Remove `jobConfig` from `TaskConfiguration`

**Comment by sandynz** [comment]
Hi @huangdx0726 , would you like to follow it? You've submitted another PR that's related to TaskConfiguration.

**Comment by huangdx0726** [comment]
OK，assigned  to me

**Comment by sandynz** [comment]
> OK，assigned to me

Thanks. Just assigned to you.
