### ISSUE TITLE
Sql Syntax Error

### ISSUE THREAD

**Issue by huangxinjian** [apache/shardingsphere#19766]
## Feature Request

I think the class `H2Repository` can change internal sql
```sql
CREATE TABLE repository(id varchar(36) PRIMARY KEY, key TEXT, value TEXT, parent TEXT);
``` 
to
```sql
CREATE TABLE repository(id_ varchar(36) PRIMARY KEY, key_ TEXT, value_ TEXT, parent_ TEXT)
```

because `key` is key word on mysql / mariadb that can't execute successful. 

Why I use H2Repository with mysql, because the class has args `props`, So I can access mysql like this and found the problem.

```sql
 return new ModeConfiguration("Standalone", new StandalonePersistRepositoryConfiguration("H2", new Properties(){{
            put(JDBCRepositoryPropertyKey.JDBC_URL.getKey(), "your mysql jdbc url");
            put(JDBCRepositoryPropertyKey.USER.getKey(), "your jdbc name");
            put(JDBCRepositoryPropertyKey.PASSWORD.getKey(), "your jdbc password");
        }}), true);
```

**Comment by terrymanu** [comment]
If you want use MySQL, please add `MySQLRepository` implemented by SPI

**Comment by huangxinjian** [comment]
Aha ! Actually I want and I think many developer use mysql in their computer on China. I will try to commit a PR later. Is there any specification for submitting PR?

**Comment by huangxinjian** [comment]
BUT the sql problem can't solve despite add `MySQLRepository`. Because class `JDBCRespository` hava hard code for get value
```sql
try (ResultSet resultSet = preparedStatement.executeQuery()) {
                List<String> resultChildren = new LinkedList<>();
                while (resultSet.next()) {
                    String childrenKey = resultSet.getString("key");  // hard code
                    if (Strings.isNullOrEmpty(childrenKey)) {
                        continue;
                    }
                    int lastIndexOf = childrenKey.lastIndexOf(SEPARATOR);
                    resultChildren.add(childrenKey.substring(lastIndexOf + 1));
                }
                return new ArrayList<>(resultChildren);
            }
```

**Comment by linghengqian** [comment]
> BUT the sql problem can't solve despite add `MySQLRepository`. Because class `JDBCRespository` hava hard code for get value
> ```sql
> try (ResultSet resultSet = preparedStatement.executeQuery()) {
>                 List<String> resultChildren = new LinkedList<>();
>                 while (resultSet.next()) {
>                     String childrenKey = resultSet.getString("key");  // hard code
>                     if (Strings.isNullOrEmpty(childrenKey)) {
>                         continue;
>                     }
>                     int lastIndexOf = childrenKey.lastIndexOf(SEPARATOR);
>                     resultChildren.add(childrenKey.substring(lastIndexOf + 1));
>                 }
>                 return new ArrayList<>(resultChildren);
>             }
> ```

Does some work need to go to https://github.com/apache/shardingsphere/issues/19655?

**Comment by huangxinjian** [comment]
> > BUT the sql problem can't solve despite add `MySQLRepository`. Because class `JDBCRespository` hava hard code for get value
> > ```sql
> > try (ResultSet resultSet = preparedStatement.executeQuery()) {
> >                 List<String> resultChildren = new LinkedList<>();
> >                 while (resultSet.next()) {
> >                     String childrenKey = resultSet.getString("key");  // hard code
> >                     if (Strings.isNullOrEmpty(childrenKey)) {
> >                         continue;
> >                     }
> >                     int lastIndexOf = childrenKey.lastIndexOf(SEPARATOR);
> >                     resultChildren.add(childrenKey.substring(lastIndexOf + 1));
> >                 }
> >                 return new ArrayList<>(resultChildren);
> >             }
> > ```
> 
> Does some work need to go to #19655?

yep.It seems to be what #19655 describes

**Comment by terrymanu** [comment]
Here is the issue #19655

**Comment by linghengqian** [comment]
Just a synchronous comment: key is also a keyword in H2Database 2.x, I think this needs to be avoided, otherwise the ShardingSphere Standalone mode cannot be used under H2Database 2.x. Also affects https://github.com/apache /shardingsphere/issues/15327.

**Comment by linghengqian** [comment]
@huangxinjian It looks like JDBCRespository already allows for SPI extensions.

**Comment by linghengqian** [comment]
- I'm working on this issue. It appears that only a MySQL implementation of `org.apache.shardingsphere.mode.repository.standalone.StandalonePersistRepository` is required.

**Comment by linghengqian** [comment]
- This seems to be a problem with the GPL V2 LICENSE of the mysql driver. But it’s not a big problem. I can use Apache V2’s `org.mariadb:r2dbc-mariadb:1.1.3` to ensure that the final product can connect to MySQL through the R2DBC Driver without violating the ASF policy.
