### ISSUE TITLE
There is a problem with the English paragraph format on the official website

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/shardingsphere#19796]
## There is a problem with the English paragraph format on the official website

**example**
![image](https://user-images.githubusercontent.com/40255310/182328882-6921f094-fb3b-4bd6-8730-4825696ef800.png)

There are more problems like this

**Comment by strongduanmu** [comment]
Can you submit a pr to fix this problem?

**Comment by shining-stars-lk** [comment]
I can fix it.
