### ISSUE TITLE
PostgreSQL/openGauss RESET statement cannot be parsed caused by #15309

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19810]
## Bug Report

Related to #18738.

### Which version of ShardingSphere did you use?

master - 73674d5ef5de2adce8a4a881e79baf4c401c352c

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

SQL parser.

### Expected behavior

PostgreSQL / openGauss RESET statement could be parsed correctly.

### Actual behavior

```
bmsql_sharding=> reset all;
ERROR:  You have an error in your SQL syntax
```

### Reason analyze (If you can)

#15309 add an `EOF` which broke the rule of RESET statement.

**Comment by runqi-zhao** [comment]
please assign it to me, I will have a try

**Comment by TeslaCN** [comment]
@RaigorJiang If we removed the EOF, does Scaling DistSQL `RESET` still work in PostgreSQL?

**Comment by RaigorJiang** [comment]
> @RaigorJiang If we removed the EOF, does Scaling DistSQL `RESET` still work in PostgreSQL?

No, removing EOF will cause `RESET SCALING jobId` not to work

**Comment by RaigorJiang** [comment]
### UPDATE
I found that `EOF` has been added to `PostgreSQLStatementParser.g4` (by #16818), so that one in `resetParameter` can now be removed.
