### ISSUE TITLE
How can I use the MOD algorithm type of shardingsphere 5.1.2 version?

### ISSUE THREAD

**Issue by xiaotong2019** [apache/shardingsphere#19817]
## Question

How can I use the MOD algorithm type of shardingsphere 5.1.2 version?

The part of doc and my config such as:

![image](https://user-images.githubusercontent.com/110440830/182506977-23e92727-7c43-4cc6-8b99-47c173ca89ec.png)
![image](https://user-images.githubusercontent.com/110440830/182507084-3aa84bca-be31-4041-a53c-156fa8d1e434.png)
![image](https://user-images.githubusercontent.com/110440830/182507467-46b2e798-75a4-4ea4-b80d-c1ac4edcf822.png)

Help and Thanks!

**Comment by strongduanmu** [comment]
Please refer this example——https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-auto-tables.properties.

**Comment by xiaotong2019** [comment]
Ok, Thank you.
