### ISSUE TITLE
There is about 5% ~ 10% performance loss of standalone mode impacted by #19618

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19827]
### Which version of ShardingSphere did you use?

master - 19265081c966cb0a839267b060593b258b0883b4

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy Standalone

### Actual behavior

The #19618 added `ProcessRegistrySubscriber` to `StandaloneContextManagerBuilder`, which impacted the performance of ShardingSphere-Proxy.

The red parts are increased overhead in main logic of ShardingSphere-Proxy.
![image](https://user-images.githubusercontent.com/20503072/182533024-52700802-e9eb-4813-8ecf-201370d29110.png)

**Comment by tuichenchuxin** [comment]
I'll invesigate this issue.
