### ISSUE TITLE
使用create语句创建的表，在使用sql语句创建索引后，CreateIndexStatementSchemaRefresher无法获取到这个表，应用重启后就能获取到了

### ISSUE THREAD

**Issue by lfc8912** [apache/shardingsphere#19835]
![QQ截图20220803161519](https://user-images.githubusercontent.com/55868476/182559601-59dd5272-ff16-4e74-8cbf-7907d47a43b6.png)

**Comment by TeslaCN** [comment]
Hi @lfc8912 
For English only.

**Comment by terrymanu** [comment]
For English only.

**Comment by lfc8912** [comment]
I can not say english
