### ISSUE TITLE
Could not create connection to database server. Attempted reconnect 10 times. Giving up.

### ISSUE THREAD

**Issue by bojiw** [apache/shardingsphere#19830]
The application uses mysql-connector-java-5.1.38 HikariCP-2.4.2.jar to connect to sharding-proxy.5.1.1 and reports an error Direct connection to mysql is normal

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/22230991/182538889-f77f0f8d-b0b7-48db-81c9-047f7f1265a6.png">

**Comment by TeslaCN** [comment]
Hi @bojiw 
Could you provide more information such as configurations and demo codes to help us reproduce this issue?

**Comment by bojiw** [comment]
It has been solved because the directly connected mysql and the mysql configured by sharding-proxy are not the same and the versions on both sides are different
