### ISSUE TITLE
Is this a bug  in 5.1.2  ?

### ISSUE THREAD

**Issue by lfc8912** [apache/shardingsphere#19848]
![image](https://user-images.githubusercontent.com/55868476/182750205-19380bb4-b7c6-4662-b154-9eb8301d7e81.png)
![image](https://user-images.githubusercontent.com/55868476/182750674-257fcbaa-564b-426b-b395-e7c6debb4a8d.png)

**Comment by strongduanmu** [comment]
@lfc8912 Yes, this bug has been fixed in master branch, you can test it.

**Comment by strongduanmu** [comment]
I just close this issue, If you have any question when you test master branch, you can submit a new issue.
