### ISSUE TITLE
Does shardingsphere-proxy hava some config ignore upper and lower case

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#19846]
version：5.1.1
opt：
Java code sql is upper case，postgresSQL table name and column is upper case ,but it throw a exception:no exist the table.When I change the postgresSQL table name and column to lower case,it's work.Is there some config to ignore upper and lower case.

**Comment by zjcnb** [comment]
> Hi @zjcnb could you help answer this question?

Sure, of course.

**Comment by zjcnb** [comment]
@koala775 Hi, ShardingSphere are ignore case, it default to lower case. You can use `master` branch to check your problem.

**Comment by koala775** [comment]
Thank you for replaying.Have resolved.
