### ISSUE TITLE
can log more info? 

### ISSUE THREAD

**Issue by Sarali2022** [apache/shardingsphere#19854]
For example. I can't have more info to know the problem. can debug more info?
can I configure don't load datasource meta because always   load meta fail（for example view，oracle）？
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/104294827/182757805-57892779-8818-4783-a66b-040b3a0447a0.png">

**Comment by terrymanu** [comment]
What is your configuration and how to reproduce the exception?

**Comment by Sarali2022** [comment]
I use code to config  datasource， but I don't know witch datascource has such exception。 maybe  use alibaba adb datasource has such exception。

**Comment by RaigorJiang** [comment]
Hi @Sarali2022 
Has this issue been resolved?

**Comment by RaigorJiang** [comment]
Closed due to no response.

**Comment by RaigorJiang** [comment]
@Sarali2022 
By the way, the database needs to provide high-performance services, and generally does not provide too many logs. It seems that you are using ShardingSphere-JDBC, you can troubleshoot this problem by debugging.
