### ISSUE TITLE
Database-driven dependencies of the EXAMPLES module

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/shardingsphere#19851]
## Question
- In the Standalone mode, the default database driver is H2, but in the configuration file in the Example module, the database driver is mysql. 
- So now the H2 database driver is loaded when the Examples module is started. What's the reason for this design. 

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Which version of ShardingSphere did you use?
master

**Comment by shining-stars-lk** [comment]
In this case, the example module will launch with an error that the driver of H2 cannot be found, because H2 has a dependency range of test and will not be relied on

**Comment by linghengqian** [comment]
- Refer to https://github.com/apache/shardingsphere/pull/19806#pullrequestreview-1060303787.  The main reason for using h2database in Example is that it is just a replacement for MySQL.  

- For well-known reasons, there is no global lifecycle listener on Junit4, so we cannot use Junit Platform integration for testcontainer.  

- I think it is unreasonable for Example to use h2database of test scope.

**Comment by terrymanu** [comment]
@mabaiwan Hi, please have a look
