### ISSUE TITLE
Consider researching and supporting column visible metadata for different databases

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#19862]
### Is your feature request related to a problem?

#19824.
#19859.

### Describe the feature you would like.

After PR #19859 was merged, we added visible field to `ShardingSphereColumn` to support MySQL invisiable column feature. Since ShardingSphere is a database incremental engine, it can support various types of databases, so we need to investigate the support of various databases for column visible.

```java
/**
 * ShardingSphere column.
 */
@RequiredArgsConstructor
@Getter
@EqualsAndHashCode
@ToString
public final class ShardingSphereColumn {
    
    private final String name;
    
    private final int dataType;
    
    private final boolean primaryKey;
    
    private final boolean generated;
    
    private final boolean caseSensitive;
    
    private final boolean visible;
}
```

- [x] MySQL invisiable column(supported since MySQL 8.0.23——https://dev.mysql.com/doc/refman/8.0/en/invisible-columns.html)
- [x] PostgreSQL invisiable column (not support)
- [x] openGauss invisiable column (not support)
- [x] Oracle invisiable column  (https://oracle-base.com/articles/12c/invisible-columns-12cr1)
- [x] SQLServer invisiable column (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15)
- [x] H2 invisiable column  (https://www.h2database.com/html/grammar.html#column_definition)

**Comment by dongzl** [comment]
Hi @strongduanmu , I will try to fix it.

**Comment by strongduanmu** [comment]
@dongzl Welcome.

**Comment by dongzl** [comment]
good ref:  https://www.postgresql.org/message-id/be81d947-f4fe-c062-f107-0f05f8f87ca8@migops.com

**Comment by strongduanmu** [comment]
Thank you @dongzl for your great job. I will close this issue since all tasks has been finished.
