### ISSUE TITLE
Refactor GovernanceRepositoryAPI for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19887]
Part of #19421.

There's dedicated code in GovernanceRepositoryAPI:
```
void persistJobProgress(RuleAlteredJobContext jobContext);

JobProgress getJobProgress(String jobId, int shardingItem);
```

GovernanceRepositoryAPI's responsibility is encapsulate registry center repository operations, and keep it simple.

Possible changes:
1, In `GovernanceRepositoryAPI`:
```
void persistJobProgress(String jobId, int shardingItem, String progressValue);

String getJobProgress(String jobId, int shardingItem);
```

2, Add high level methods in `RuleAlteredJobAPI`

**Comment by sandynz** [comment]
@azexcy , could you help to follow it?

**Comment by azexcy** [comment]
I will follow this issue.
