### ISSUE TITLE
Decouple RuleAlteredJobScheduler and RuleAlteredJobContext for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19899]
Part of #19421.

Possible changes:

1, In `RuleAlteredJobScheduler`, replace `RuleAlteredJobContext` to `PipelineJobContext`;

2, Add InventoryTasks / IncrementalTasks / PipelineProcessContext in `RuleAlteredJobScheduler`;

**Comment by huangdx0726** [comment]
I will try

**Comment by sandynz** [comment]
> I will try

Thanks. Just assigned it to you.

**Comment by huangdx0726** [comment]
PipelineProcessContext  is nothing now？whaht's responsibilities？

**Comment by huangdx0726** [comment]
```java
public interface PipelineProcessContext {

    ExecuteEngine getInventoryDumperExecuteEngine();

    ExecuteEngine getIncrementalDumperExecuteEngine();

    ExecuteEngine getImporterExecuteEngine();
}
```
and `AbstractPipelineProcessContext` `implements` ` PipelineProcessContext` right?

**Comment by sandynz** [comment]
> PipelineProcessContext is nothing now？whaht's responsibilities？

Yes, you could add common methods in PipelineProcessContext. It has sub-class: AbstractPipelineProcessContext and RuleAlteredContext.

**Comment by sandynz** [comment]
> ```java
> public interface PipelineProcessContext {
> 
>     ExecuteEngine getInventoryDumperExecuteEngine();
> 
>     ExecuteEngine getIncrementalDumperExecuteEngine();
> 
>     ExecuteEngine getImporterExecuteEngine();
> }
> ```
> 
> and `AbstractPipelineProcessContext` `implements` ` PipelineProcessContext` right?

Yes, `implements PipelineProcessContext` is missed before, I've submitted a PR and it's merged today. You could merge from upstream master branch.

**Comment by sandynz** [comment]
And you could ignore preparation part (e.g. `jobContext.getJobPreparer().prepare(jobContext);`) for now, or you could do it after #19897 is done
