### ISSUE TITLE
Add AbstractPipelineJob for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19897]
Part of #19421.

Possible changes:

1, Add `AbstractPipelineJob`, extract common code of `RuleAlteredJob` into it.

2, Move `new Thread(runnable).start();` from `RuleAlteredJobScheduler` to `AbstractPipelineJob.runInBackground` method.

3, Move preparation code from `RuleAlteredJobScheduler` to `RuleAlteredJob`.

**Comment by azexcy** [comment]
I will follow it, please assign to me

**Comment by sandynz** [comment]
@azexcy , could you help to follow it?
