### ISSUE TITLE
Add test cases for JDBCRepository

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#19912]
- [ ] Add fixture: JDBCRepositoryFixture implements JDBCRepository
- [ ] Add test case with mock

**Comment by shining-stars-lk** [comment]
I can do this task

**Comment by mabaiwan** [comment]
@shining-stars-lk Welcome

**Comment by strongduanmu** [comment]
Hi @shining-stars-lk , could we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by abhinav-koppula** [comment]
Hi @terrymanu 
Since there was no update on this issue since quite some time, I have taken a stab at it.
I have created a PR https://github.com/apache/shardingsphere/pull/20699. Can you please review?

**Comment by agentart** [comment]
@abhinav-koppula Please wait to run CI

**Comment by abhinav-koppula** [comment]
@agentart - Can you please assign the issue to me since the PR has been merged?
