### ISSUE TITLE
Refactor AbstractImporter.getSchemaName

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19936]
Currently, AbstractImporter.getSchemaName is an abstract method, and it's implemented in MySQLImporter / PostgreSQLImporter / OpenGaussImporter.

In fact, it could be implemented in AbstractImporter, to simplify AbstractImporter sub-classes, and ImporterFactory / ScalingEntry later.

Possible changes:
- Refactor ImporterConfiguration.getSchemaName, check schema available or not by `DatabaseTypeFactory.getInstance(databaseType).isSchemaAvailable();`, return null if schema is not available
- Remove `abstract` on AbstractImporter.getSchemaName; Change `protected` to `private`
- Remove implementations of AbstractImporter.getSchemaName

Following classes and methods could be referenced, they could be used to implement getSchemaName in AbstractImporter:
- AbstractImporter.getImporterConfig()
- ImporterConfiguration.getDataSourceConfig()
- PipelineDataSourceConfiguration.getDatabaseType()
- DatabaseType.isSchemaAvailable()

**Comment by sandynz** [comment]
Hi @huangdx0726 , are you intersting to solve it?

**Comment by huangdx0726** [comment]
ok ，assigned to me

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.
