### ISSUE TITLE
Optimize Federation-Query

### ISSUE THREAD

**Issue by boyjoy1127** [apache/shardingsphere#19937]
## Feature Request

Federation Query should be optimized.

### Is your feature request related to a problem?
No

### Describe the feature you would like.
- [X] Add TranslateTable to support projection and filter push down to the table rel-node.
- [X] Add optimization rules to support projection and filter push down to the table rel-node.
- [x] Optimize rules to support projection and filter push down well.
- [ ] Add cache for SQL and query plan.
- [ ] Add calcite statistics-related API in the future infra-meta module.
- [ ] Optimize rules to support the join well. Collect calcite statistics of the schema and table, to support optimization well.
- [ ] Optimize rules to support the sub-query well. Collect calcite statistics of the schema and table, to support optimization well.
- [ ] Optimize the procedure of the execution to accelerate the query.

**Comment by strongduanmu** [comment]
Hi @boyjoy1127, Could we finish this issue in 5.1.3?

**Comment by strongduanmu** [comment]
Since the design of sql federation is not consistent with this issue now, I will close this issue. If there is a new solution, please discuss it in the community first.
