### ISSUE TITLE
Remove AbstractImporter sub-classes and simplify ImporterFactory

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19938]
It could be done after #19936.

Since there's no more abstract method to implement for AbstractImporter sub-classes, and there's no more abstract method in near future, so we could remove these sub-classes to simplify related code.

Possible changes:
- Rename AbstractImporter to DefaultImporter; Remove `abstract` and add `final`;
- Remove ScalingEntry.getImporterClass() method and related sub-class method impl
- Remove AbstractImporter sub-classes
- Simplify ImporterFactory.createImporter, remove Importer reflection construction, just new DefaultImporter
- ~~Move ImporterFactory to the same module and package as Importer interface~~

**Comment by piyushg1** [comment]
Hi, could you assign this to me?
I'm a complete begineer and want to give it a shot.
Thanks.

**Comment by sandynz** [comment]
> Hi, could you assign this to me? I'm a complete begineer and want to give it a shot. Thanks.

Hi @piyushg1 , welcome! Assigned to you.

You could refer to [Contribution Guide]( https://shardingsphere.apache.org/community/en/contribute/ ), it might be helpful.

**Comment by sandynz** [comment]
Hi @huangdx0726 , are you intersting to solve it? You've just resolved the prepositive issue.

**Comment by huangdx0726** [comment]
ok Assigned  to me

**Comment by huangdx0726** [comment]
@sandynz   hi, the `Importer` interface is defined in `shardingsphere-data-pipeline-api` module , i try to move `ImporterFactory` to the module, but the `DefaultImporter` and `PipelineDataSourceManager` in `shardingsphere-data-pipeline-core` module,  Is `Pipelinedatasourcemanager` also moved to this module ？

**Comment by sandynz** [comment]
@huangdx0726 , I missed the details. You could keep ImporterFactory in original module and package.

**Comment by huangdx0726** [comment]
ok
