### ISSUE TITLE
The keyGenerateAlgorithm is invalid when the insert statement is executed

### ISSUE THREAD

**Issue by dym254661025** [apache/shardingsphere#19961]
### Cause: java.sql.SQLException: Field 'id' doesn't have a default value
; Field 'id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'id' doesn't have a default value

**Comment by strongduanmu** [comment]
Hi @dym254661025, can you provide more information to help reproduce this exception?

**Comment by dym254661025** [comment]
shardingsphere 5.1.1

properties
`spring:
  shardingsphere:
    enabled: true
    props:
      sql:
        show: true

    rules:
      sharding:
        key-generators:
          log-key:
            type: AUTOKEY 

        sharding-algorithms:
          history-month: 
            type: MONTH 
            props:
              strategy: standard
              algorithmClassName: com.demo.test.framework.config.sharding.MonthStandardShardingAlgorithm
        tables:
          test_record:
            actual-data-nodes: ds-history.test_record_$->{2022..2030}$->{(1..12).collect(i->i.toString().padLeft(2,'0'))}
            table-strategy: 
              standard: 
                sharding-column: time 
                sharding-algorithm-name: history-month 
            key-generate-strategy:
              column: id
              key-generator-name: log-key
          test_info:
            actual-data-nodes: ds-history.test_info_2022$->{(2..12).collect(i->i.toString().padLeft(2,'0'))}
            table-strategy: 
              standard: 
                sharding-column: time 
                sharding-algorithm-name: history-month 
            key-generate-strategy:
              column: id
              key-generator-name: log-key
    datasource:
      names: ds-history
      ds-history:
        type: ${spring.datasource.type}
        driver-class-name: ${spring.datasource.driverClassName}
        url: ${spring.datasource.druid.history.url}
        username: ${spring.datasource.druid.history.username}
        password: ${spring.datasource.druid.history.password}`

**Comment by dym254661025** [comment]
DDL
CREATE TABLE `test_record_202205` (
  `id` bigint(20) NOT NULL,
  `point_id` bigint(20) NOT NULL,
  `str` varchar(255) DEFAULT NULL,
  `time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `point_id` (`point_id`,`str`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by dym254661025** [comment]
@Insert("insert into test_record(point_id,str,`time`)values(#{pointId},#{str},#{time}) on duplicate key update str = value(str)")
    int add(TestRecord testRecord);

**Comment by strongduanmu** [comment]
Can you provide a demo? The information you provided seems to integrate with the framework and also has a private sharding algorithm.

**Comment by dym254661025** [comment]
When executing the insert statement, the breakpoints  in the keygenerator algorithm do not stop

**Comment by dym254661025** [comment]
> 
[test.zip](https://github.com/apache/shardingsphere/files/9279611/test.zip)

**Comment by dym254661025** [comment]
> 
[test.zip](https://github.com/apache/shardingsphere/files/9279611/test.zip)

**Comment by dym254661025** [comment]
> 
[test.zip](https://github.com/apache/shardingsphere/files/9279611/test.zip)

**Comment by dym254661025** [comment]
> Can you provide a demo? The information you provided seems to integrate with the framework and also has a private sharding algorithm.

 [test.zip](https://github.com/apache/shardingsphere/files/9279611/test.zip)

**Comment by dym254661025** [comment]
> > Can you provide a demo? The information you provided seems to integrate with the framework and also has a private sharding algorithm.
> 
> [test.zip](https://github.com/apache/shardingsphere/files/9279611/test.zip)

The test_info object can successfully execute the insert statement, but the test_record object executes the insert statement with an error
Field 'id' doesn't have a default value

**Comment by dym254661025** [comment]
The real table in my database is incomplete, and I only created the middle part of the actual-data-nodes, so that the test_ record table could not be found in the schemas of logic_db.
![image](https://user-images.githubusercontent.com/67610946/184311590-a63a955f-694b-4a7b-8f87-8a213daf4008.png)
When I create the first table in the actual-data-nodes, I can find test_record in tables
![image](https://user-images.githubusercontent.com/67610946/184311389-ecf8be48-38fc-45f6-93cf-4d89fd047b7b.png)
