### ISSUE TITLE
Refactor InventoryTaskSplitter for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19976]
Part of #19421.

Currently, there's hard-coded RuleAlteredJobContext and RuleAlteredJobConfiguration in InventoryTaskSplitter.

Possible changes:
- Replace RuleAlteredJobContext to PipelineJobContext
- Remove RuleAlteredJobConfiguration
- Add necessary fields

**Comment by sandynz** [comment]
@azexcy , could you help to follow it?

**Comment by azexcy** [comment]
I will follow it, please assign to me
