### ISSUE TITLE
When thread pool related properties are not configured, sub-table query will cause system downtime

### ISSUE THREAD

**Issue by smallblack-xh** [apache/shardingsphere#19978]
Hello, I recently encountered a problem. I used shardingsphere in the project, but some configurations of the data source were missed due to negligence. When I started the system normally and submitted a query without a table field, the system stayed on the Actual SQL log. In response, all other functions are also shut down. I searched for a long time, still can't figure out why it is like this. Can you help me analyze？

Version of Shardingsphere:4.1.1

Size of table: 50
Existing configuration：
spring.shardingsphere.props.max.connections.size.per.query = 10
ignored configuration：
spring.shardingsphere.datasource.master.initialSize = 30
spring.shardingsphere.datasource.master.maxActive = 50
spring.shardingsphere.datasource.master.minIdle = 20
spring.shardingsphere.datasource.master.maxWait = 5000

**Comment by linghengqian** [comment]
I'm assuming a similar problem is solved in an issue, since no one wants to look at older versions of git source.  4.1.1 is very old.

**Comment by TeslaCN** [comment]
Please upgrade to latest version. 4.1.1 is no longer maintained for years.
