### ISSUE TITLE
Update antlr4 to 4.10+

### ISSUE THREAD

**Issue by shanrenxj** [apache/shardingsphere#19990]
Hibernate 6.0.1+ was ues antlr4: 4.10+
when I force to use  antlr4: 4.10+，I got error：
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **4** (expected 3).
then when I force to use  antlr4: 4.9.x，I got error
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **3** (expected 4).

**Comment by shanrenxj** [comment]
> 你要提交PR吗？这将有助于更快地解决这个问题。

I have submitted PR for this issue, but I do not have permission

**Comment by linghengqian** [comment]
I suggest you open a new issue to discuss the point in time to migrate the base JDK version of ShardingSphere to JDK11. This issue will be blocked before the new issue is resolved, so I suggest closing this issue.
