### ISSUE TITLE
Extract PipelineJobPreparerUtils from RuleAlteredJobPreparer for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20007]
Part of #19421.

Currently, InventoryTaskSplitter is an dividual class that's used by RuleAlteredJobPreparer, but other code snippets are hard-coded in RuleAlteredJobPreparer. We'll try to extract some common methods from RuleAlteredJobPreparer into PipelineJobPreparerUtils and refactor it, then it could be used in different types of job preparer.

Possible changes (need to investigate it, it's not required to do):
- Add PipelineJobPreparerUtils class
- Extract schema & table preparer into PipelineJobPreparerUtils
- Extract position initialization and destroying into PipelineJobPreparerUtils
- Refactor position destroying (in cleanup method currently), not only support ShardingSpherePipelineDataSourceConfiguration, but also support StandardPipelineDataSourceConfiguration
- Other methods that could be reused

**Comment by sandynz** [comment]
@azexcy , could you help to follow it?

**Comment by azexcy** [comment]
Please assign to me.
