### ISSUE TITLE
sharding proxy time_zone can not change

### ISSUE THREAD

**Issue by wsg96321** [apache/shardingsphere#20004]
version: sharding proxy v5.1.0

for example : `1659070419` is the timestamp of `2022-07-29 12:53:39` for time_zone "UTC+8"
but when I set time_zone in my sharding proxy, it seems does't effect. It keeps the `time_zone` for `SYSTEM`, and I can't not change it in one connect session (it doesn't have matter when I login the remote mysql to `set time_zone`, so it troubleshoot remote mysql problems)
![image](https://user-images.githubusercontent.com/8844009/183547473-1f3b4651-949e-44cc-a38d-ad562c9ecf95.png)
![image](https://user-images.githubusercontent.com/8844009/183548199-b32007b3-b9b0-4154-b777-fa3c38a895be.png)

in the same instance but not the same database,  It works for sharding proxy by `set time_zone` when I doesn't have use INLINE expressions for my sharding table, like belows:
![image](https://user-images.githubusercontent.com/8844009/183548366-a5e7a6ba-5f9e-4c81-a78a-a372d8027b7c.png)

**Comment by TeslaCN** [comment]
SET statement is not properly handled in previous versions. Please consider setting global timezone.

**Comment by wsg96321** [comment]
it is the same behavior when I use set global time_zone , and besides , when it is only just one database in a sharding proxy instance , it seems work right.
( also I have try this in v5.1.1 version , it is the same as v5.1.0 )

**Comment by TeslaCN** [comment]
We did some changes to SET statement in https://github.com/apache/shardingsphere/issues/18738, which would be available in next release.

**Comment by wsg96321** [comment]
OK , thanks a lot , then we will have a try in next release .
