### ISSUE TITLE
shardingsphere-proxy with HAProxy

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#20016]
version:5.1.1
opt:
I use HAProxy to implement load balancing，the HAProxy roll polling algorithm set roundrobin，the weight is 1:1.But the phenomenon is a period of vistis a， a period of vistis b.It's not at a time vist a,at a time vistis b.It have a relationship with shardingsphere-proxy?

**Comment by TeslaCN** [comment]
Hi @koala775 
Database connection is stateful. If you are executing SQL in one session, all request would be executed in one connection.

**Comment by koala775** [comment]
Thank you for replaying.I requet a controller every time,it belongs to a session?

**Comment by TeslaCN** [comment]
> Thank you for replaying.I request a controller every time,it belongs to a session?

That depends on whether you are using pooled connection.

**Comment by koala775** [comment]
Yes,I use.

**Comment by TeslaCN** [comment]
> Yes,I use.

Connection pool reuses actual database connections. So pooled connection in different request may corresponding to same actual connection.

**Comment by koala775** [comment]
Shardingsphere-proxy also hava session concept？

**Comment by TeslaCN** [comment]
Connection to ShardingSphere-Proxy is also stateful.

**Comment by koala775** [comment]
Ok，thanks.
