### ISSUE TITLE
When sharding proxy and SQL hint are used for database splitting, does the read-write separation configuration not take effect？

### ISSUE THREAD

**Issue by ykjxx** [apache/shardingsphere#20019]
problem：When sharding proxy and SQL hint are used for database splitting, does the read-write separation configuration not take effect？
environment：shardingproxy-5.1.2,mysql5.7
What should I do if I want to use hint and read / write split config at the same time?

**Comment by RaigorJiang** [comment]
Hi @ykjxx 
Please describe your configuration and operation, what is the expectation and what is the actual performance?
So that someone can help you analyze the cause of the problem.

It is best to use the issue template to ask questions.

**Comment by ykjxx** [comment]
Hi @RaigorJiang 
my config:
![image](https://user-images.githubusercontent.com/52477571/183792838-0b7e3988-986f-4579-96f8-1cc94593294e.png)
[db1, replica1] and [DB2, replica2] are two groups of master-slave Databases. I hope to route these two groups of Databases through Hin SQL and realize read-write separation
excute-sql: /* ShardingSphere hint: dataSourceName=db_2 */ select * from sm_project_img;
expect： It is expected that the above SQL execute on the slave dabatase(replica_2)
actual:  this sql execute on the master database(db_2)

**Comment by RaigorJiang** [comment]
Two risks:
1. Your readwrite-splitting group names and the original resource names are duplicated, which may lead to deviation
2. The way of SQL HINT to dataSourceName has been removed from the master, so it is best not to use it, otherwise the subsequent upgrade will not be possible.

**Comment by RaigorJiang** [comment]
Closed due to no reply for a long time.
