### ISSUE TITLE
create tablespace does not support specifying the maxsize limit

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#20026]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_282
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5
Commit Message: Implements openGauss version function by calcite (#19327)
Branch: 9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5
Build time: 2022-08-04T19:57:18+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
alter table does support modifying the tablespace of the table
### Actual behavior
alter table does not support modifying the tablespace of the table

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
create tablespace does not support specifying the maxsize limit
It is recommended to support according to the create tablespace syntax
```
order_db=> create tablespace tbspc_test location '/openGauss/tbspc_test' maxsize '10M';
ERROR:  You have an error in your SQL syntax
```

**Comment by RaigorJiang** [comment]
Yes, `maxsize` is not supported by the current syntax definition, are you interested in improving it?

refer to https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-opengauss/src/main/antlr4/imports/opengauss/DDLStatement.g4

**Comment by lhyundeadsoul** [comment]
I am trying to add max_size option to createtablespace in openGause syntax. But I am not very familiar with antlr4.
So this PR is still WIP.
Is there any quick tutorial on antlr4 development in shardingsphere? @strongduanmu @RaigorJiang

**Comment by lhyundeadsoul** [comment]
> I am trying to add max_size option to createtablespace in openGause syntax. But I am not very familiar with antlr4. So [this PR](https://github.com/apache/shardingsphere/pull/20641) is still WIP. Is there any quick tutorial on antlr4 development in shardingsphere? @strongduanmu @RaigorJiang Thx!

Here it is
https://shardingsphere.apache.org/document/current/cn/test-manual/module-test/parser-test/

**Comment by strongduanmu** [comment]
@peilinqian Can you help test this sql again?
