### ISSUE TITLE
Refactor parameter definition of DistSQL for feature `sharding`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20028]
Hi community,

This issue is for #18811, to refactor parameter definition in module **`shardingsphere-sharding-distsql-parser`**

### Aim

- [ ] Redefine identifier and literals in g4 grammar (Literals.g4, Keyword.g4)
- [ ] Change parameter type definitions in g4 of `RDLStatement`, `RQLStatement` and `RALStatement`
- [ ] Update `ShardingDistSQLStatementVisitor` & `ScalingSQLStatementVisitor` to fit parameter type adjustment
- [ ] Update parser test cases in module `shardingsphere-parser-test`
- [ ] Update other affected test cases (Maybe in `shardingsphere-integration-test`)
- [ ] Update the syntax and usage documentation
> Hopefully you can also rename `ScalingSQLStatementVisitor` to `ScalingDistSQLStatementVisitor`

### Basic Qualifications

- Java
- ANTLR
- Markdown

### Links
- Syntax: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/
- Usage: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/sharding-rule/

### Example FYI

#19722

**Comment by yx9o** [comment]
let me try.

**Comment by RaigorJiang** [comment]
Completed, thank you! @yx9o

**Comment by sunkai-cai** [comment]
please assigness to me.
