### ISSUE TITLE
Refactor parameter definition of DistSQL for feature `readwrite-splitting`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20031]
Hi community,

This issue is for #18811, to refactor parameter definition in module **`shardingsphere-readwrite-splitting-distsql-parser`**

### Aim

- [ ] Redefine identifier and literals in g4 grammar (Literals.g4, Keyword.g4)
- [ ] Change parameter type definitions in g4 of `RDLStatement`, `RQLStatement` and `RALStatement`
- [ ] Update `ReadwriteSplittingDistSQLStatementVisitor` to fit parameter type adjustment
- [ ] Update parser test cases in module `shardingsphere-parser-test`
- [ ] Update other affected test cases (Maybe in `shardingsphere-integration-test`)
- [ ] Update the syntax and usage documentation

### Basic Qualifications

- Java
- ANTLR
- Markdown

### Links
- Syntax: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/
- Usage: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/readwirte-splitting-rule/

### Example FYI

#19722

**Comment by runqi-zhao** [comment]
Please assign this task to me

**Comment by RaigorJiang** [comment]
Hi @runqi-zhao , Welcome!

**Comment by RaigorJiang** [comment]
Hi @runqi-zhao 
Any progress? Or have any questions?

**Comment by runqi-zhao** [comment]
@RaigorJiang Sorry, because of other busy things recently, it hasn't started yet. It will be dealt with tomorrow

**Comment by RaigorJiang** [comment]
> @RaigorJiang Sorry, because of other busy things recently, it hasn't started yet. It will be dealt with tomorrow

OK, thank you!

**Comment by sunkai-cai** [comment]
please assigness to me.

**Comment by RaigorJiang** [comment]
@runqi-zhao 
Sorry, the time for this issue is a bit long, I will assign it to @sunkai-cai now, and you are welcome to participate in other issues next time. Thank you!
