### ISSUE TITLE
Redesign exception hierarchy of ShardingSphere

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20036]
The current Exception is not very clear. It is better to redesign the exception hierarchy of ShardingSphere.

1. The exception should split to ShardingSphereException which can throw to SDK layer for operation error by user, and ShardingSphereInsideException for internal catch;
1. The ShardingSphereException should include error categories and error codes, user can query like dictionary by the error categories;
1. ShardingSphereInsideException should catch by ShardingSphere and never throw to SDK directly, it can be thrown by error packet or re-throw by ShardingSphereException with error category and error code;
1. Re-throw other exceptions such as: IllegalArgumentException to ShardingSphereException.

----

The value of ShardingSphere's Kernel vendor codes should be:

`1%d`(Category)`%d%d%d`(Sequence)

Categories of Kernel:
  - metadata(0)
  - data(1)
  - syntax(2)
  - connection(3)
  - transaction(4)
  - lock(5)
  - audit(6)
  - cluster(7)
  - pipeline(8)

----

The value of ShardingSphere's Feature vendor codes should be:

`2%d%d`(Feature)`%d`(Category)`%d`(Sequence)

Feature Codes:
  - Sharding(0)
  - Readwrite-splitting(2)
  - Database-discovery(3)
  - SQL translator(4)
  - Traffic(5)
  - Encryption(7)
  - Shadow(8)

Categories of Feature:
  - metadata(0,1)
  - data(2,3)
  - syntax(4,5)
  - connection(6,7)
  - algorithm(8)
  - customized-algorithm(9)

----

The value of ShardingSphere's Generic vendor codes should be:

`3%d%d%d%d`(Sequence)

**Comment by strongduanmu** [comment]
Hi @terrymanu , can we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by terrymanu** [comment]
Ok, please move it to next milestone

**Comment by strongduanmu** [comment]
Since this is a long-term task, I will temporarily remove milestones.
