### ISSUE TITLE
Refactor parameter definition of DistSQL for feature `db-discovery`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20032]
Hi community,

This issue is for #18811, to refactor parameter definition in module **`shardingsphere-db-discovery-distsql-parser`**

### Aim

- [ ] Redefine identifier and literals in g4 grammar (Literals.g4, Keyword.g4)
- [ ] Change parameter type definitions in g4 of `RDLStatement`, `RQLStatement` and `RALStatement`
- [ ] Update `DatabaseDiscoveryDistSQLStatementVisitor` to fit parameter type adjustment
- [ ] Update parser test cases in module `shardingsphere-parser-test`
- [ ] Update other affected test cases (Maybe in `shardingsphere-integration-test`)
- [ ] Update the syntax and usage documentation

### Basic Qualifications

- Java
- ANTLR
- Markdown

### Links
- Syntax: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/db-discovery/
- Usage: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/db-discovery/

### Example FYI

#19722

**Comment by sunkai-cai** [comment]
Please assign this task to me

**Comment by sunkai-cai** [comment]
# Question

refer to this case #20145 ，Redefine identifier and literals like this：

* Before

```
CREATE DB_DISCOVERY RULE ha_group_0 (RESOURCES(resource0,resource1), TYPE(NAME=mgr,PROPERTIES(groupName='92504d5b-6dec')),HEARTBEAT(PROPERTIES('keepAliveCron'='0/5 * * * * ?')));

discoveryTypeName
    : IDENTIFIER
    ;
```

* After

```
CREATE DB_DISCOVERY RULE ha_group_0 (RESOURCES(resource0,resource1), TYPE(NAME="mgr",PROPERTIES(groupName='92504d5b-6dec')),HEARTBEAT(PROPERTIES('keepAliveCron'='0/5 * * * * ?')));

discoveryTypeName
    : STRING
    ;
```

But, if `discoveryTypeName` is `STRING`, then:

* Before

```
DROP DB_DISCOVERY TYPE db_discovery_group_0_mgr;
```

* After

```
DROP DB_DISCOVERY TYPE `db_discovery_group_0_mgr`;
```

So,  how can i redefine ？

**Comment by RaigorJiang** [comment]
> discoveryTypeName

I understand what you mean, the `discoveryTypeName` is reused here, but it is actually `discoveryTypeName` (like "MySQL.MGR") and `discoveryAlgorithmName` (like db_discovery_group_0_mgr)

Thus, it can be distinguished
