### ISSUE TITLE
Refactor parameter definition of DistSQL for feature `encrypt`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20030]
Hi community,

This issue is for #18811, to refactor parameter definition in module **`shardingsphere-encrypt-distsql-parser`**

### Aim

- [ ] Redefine identifier and literals in g4 grammar (Literals.g4, Keyword.g4)
- [ ] Change parameter type definitions in g4 of `RDLStatement`, `RQLStatement` and `RALStatement`
- [ ] Update `EncryptDistSQLStatementVisitor` to fit parameter type adjustment
- [ ] Update parser test cases in module `shardingsphere-parser-test`
- [ ] Update other affected test cases (Maybe in `shardingsphere-integration-test`)
- [ ] Update the syntax and usage documentation

### Basic Qualifications

- Java
- ANTLR
- Markdown

### Links
- Syntax: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/
- Usage: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/encrypt-rule/

### Example FYI

#19722

**Comment by Crackersssss** [comment]
Can i try it?

**Comment by sunkai-cai** [comment]
let me try.
