### ISSUE TITLE
Maybe we should export  something about TRANSACTION?

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#20046]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no
##### I found when use ShardingSphere ，we can't get enough information about TRANSACTION.
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/86462784/183611874-97b22222-20e9-4217-a968-60d56ff31b47.png">

##### When we view zk ,there is only graph information about the transaction.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/86462784/183798930-f233cae2-d088-4de5-94bf-f49e9cbe32d9.png">

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/86462784/183798863-076bbf36-fed0-4ba6-b90d-d17c80b60c14.png">

##### When we config `logback.xml` (    name="com.atomikos" level="all") ,there is only graph information about the transaction.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/86462784/183799532-d75bdb22-405c-4263-bcfe-31e5f9d057c8.png">

**Comment by FlyingZC** [comment]
You can configure atomikos' log file like this:
```xml
    <logger name="com.atomikos" level="DEBUG">
        <appender-ref ref="console" />
    </logger>
```

**Comment by FlyingZC** [comment]
You can configure narayana log file like this:
```xml
<!-- narayana -->
<logger category="com.arjuna" level="DEBUG">
    <appender-ref ref="console" />
</logger>
```

**Comment by FlyingZC** [comment]
Now DistSQL displays the rule information. The rule information comes from user configuration. At present, there is not much configuration information on the transaction side,so very little information is shown.
