### ISSUE TITLE
hi，which version supports batch insert（sharding-jdbc）？

### ISSUE THREAD

**Issue by Lychengit** [apache/shardingsphere#20042]
scene：The data inserted in batch are all in the same table（No distributed transactions）.

like this:

INSERT INTO t_table (xx, xx) VALUES
(xx,xx),
(xx,xx),
(xx,xx);

**Comment by strongduanmu** [comment]
Hi @Lychengit, batch insert is the basic feature, you can try any version.

**Comment by Lychengit** [comment]
> 你好@Lychengit，批量插入是基本功能，你可以尝试任何版本。

ok. I'll try again，Please do not close this issue.
