### ISSUE TITLE
opengauss manual scaling, “CHECK SCALING” syntax not supported

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#20063]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_282
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5
Commit Message: Implements openGauss version function by calcite (#19327)
Branch: 9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5
Build time: 2022-08-04T19:57:18+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
opengauss manual scaling, “CHECK SCALING” syntax supported
### Actual behavior
opengauss manual scaling, “CHECK SCALING” syntax not supported
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
order_db=> show scaling status 0130317c30317c3054317c6f726465725f6462;
 item | data_source |          status          | active | inventory_finished_percentage | incremental_idle_seconds
------+-------------+--------------------------+--------+-------------------------------+--------------------------
 0    | ds_0        | EXECUTE_INCREMENTAL_TASK | true   | 100                           | 145
 1    | ds_1        | EXECUTE_INCREMENTAL_TASK | true   | 100                           | 147
(2 rows)

order_db=> STOP SCALING SOURCE WRITING  0130317c30317c3054317c6f726465725f6462;
SUCCESS
order_db=> CHECK SCALING 0130317c30317c3054317c6f726465725f6462 BY TYPE (NAME=CRC32_MATCH);
ERROR:  Database type openGauss is not supported in [MySQL]
order_db=> APPLY SCALING 0130317c30317c3054317c6f726465725f6462;
ERROR:  Data consistency check is not finished or failed.
order_db=>
```

**Comment by sandynz** [comment]
Hi @peilinqian , the error of
```
order_db=> CHECK SCALING 0130317c30317c3054317c6f726465725f6462 BY TYPE (NAME=CRC32_MATCH);
ERROR:  Database type openGauss is not supported in [MySQL]
```
means `CRC32_MATCH` just support `MySQL` for now, openGauss is not suportted.

You could use `DATA_MATCH` algorothem, e.g.
```
CHECK SCALING 0130317c30317c3054317c6f726465725f6462 BY TYPE (NAME=DATA_MATCH);
```
