### ISSUE TITLE
There are a lot of schemas on a database instance and all of them must be used. How to proxy all of them? Can I only proxy ports directly with the mysql-proxy mode instead of configuring schemas one by one?

### ISSUE THREAD

**Issue by WJME** [apache/shardingsphere#20079]
I have a big trouble or question, please help me
I have one mysql master database and one slave database, I only need to use the read-write separation function. But there are 100+ schemas in my main database. Is it difficult for me to configure all 300+ schemas to the yaml configuration file one by one?
  Is there a simple configuration pattern that directly transparently transmits all schemas? As far as I know, mycat also needs to be configured one by one, but Qihoo 360's atlas and mysql's official mysql-proxy can be directly configured into a mode similar to all transparent use.

**Comment by WJME** [comment]
@rfscholte @WillemJiang @ke4qqq @gmcdonald

**Comment by WJME** [comment]
Their schema update is a tcp port forwarding that supports interception handling

**Comment by WJME** [comment]
Their mode is more like a tcp port forwarding that supports interception processing

**Comment by WJME** [comment]
Their schema is more like a tcp port forwarding that supports interception processing, so even creating a new schema in a running database is immediately available to jdbc on the proxy side without reconfiguring or restarting. Can't deny that I do I've seen some SAAS projects do it like this

**Comment by WJME** [comment]
Their mode is more like a tcp port forwarding that supports interception processing, so even creating a new schema in a running database can be immediately available to jdbc on the proxy side without reconfiguring or restarting. Can't deny that I do I've seen some SAAS projects do it like this

**Comment by WJME** [comment]
@sandynz

**Comment by sandynz** [comment]
Hi @WJME , I'm not sure what's the feature request means, could you submit a thread on forum community?
