### ISSUE TITLE
Discovery invalid when primary switchover to the first primary node of the proxy start

### ISSUE THREAD

**Issue by xueyilong** [apache/shardingsphere#20090]
### ENV
ShardingSphere-Proxy version :  5.1.2
Database Version : MogDB 3.0.0 （1 primay 2 standby）

### Expected behavior
Discovery the right database role whatever i execute the switchover on the any standby node

### Actual behavior
<img width="977" alt="image" src="https://user-images.githubusercontent.com/20434574/184165694-2114c03c-5ec3-42a3-8a07-36abcf024813.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/20434574/184165721-71aebc46-18c1-4e7d-b65a-505fa7b9bc84.png">

The first time(22:29) i start  proxy , the db primay is ds_0 and the readwrite_splitting rule is right
The second time(22:30) i execute switover on ds_1 , the db primary is ds_1 and the readwrite_splitting rule is right
The third time(22:31) i execute switover on ds_0 again,  the db primary is ds_0 , the readwrite_splitting rule is wrong and have three records in readwrite_splitting read resources;

**Comment by terrymanu** [comment]
The database discovery feature has been remove form ShardingSphere, please ref #24486
