### ISSUE TITLE
ShardingSphere still hava Deadlock exception

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#20097]
version:5.1.1
opt:
I use Sysbench to execute the performance test,then throw the error:Deadlock found when trying to get lock;try restarting transtraction,have an impact on？

**Comment by TeslaCN** [comment]
This may be related to your sharding configuration.

**Comment by koala775** [comment]
The proxy is default config.Sharding rule is one databese with ten tables，use standard tableStrategy with id%10.

**Comment by TeslaCN** [comment]
The sysbench may modify different ids in a transaction. Sharding tables may cause deadlock in sysbench read write test.

**Comment by koala775** [comment]
Ok，thank you for replaying，I exactly execute the read write test.
