### ISSUE TITLE
Route table null does not exist, available actual table

### ISSUE THREAD

**Issue by dinghu** [apache/shardingsphere#20101]
Route table null does not exist, available actual table

InlineShardingAlgorithm init ok but when doshading ->createClosure（this.algorithmExpression） this.algorithmExpression is null

this is my config:
          dyc_post-inline:
            type: INLINE
            props:
              algorithm-expression: dyc_post_$->{id % 2}

**Comment by dinghu** [comment]
i use shiro in my project . shiro realm contains some XXservice XX dao but sharding configs is not be loaded at this time ! finnaly i solve it like this
![image](https://user-images.githubusercontent.com/8045842/184317129-cc7b3b3d-9112-4927-8b35-f405ce322b9b.png)

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
