### ISSUE TITLE
Add InventoryDumperCreator SPI to decouple InventoryDumper and ScalingEntry

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20128]
Purpose
- Separate InventoryDumper from ScalingEntry for better reuse

Possible changes:
- Add InventoryDumperCreator interface, extends TypedSPI, marked as @SingletonSPI; Put in the same module and package of AbstractInventoryDumper;
- Add MySQL & PostgreSQL & Fixture implementations of InventoryDumperCreator; Register them in resources/WEB-INF.services
- Add InventoryDumperCreatorFactory; Put in the same module and package of AbstractInventoryDumper;
- Add InventoryDumperCreatorFactoryTest in shardingsphere-pipeline-test module, assert get instance of InventoryDumperCreator by type "MySQL" / "PostgreSQL" / "Fixture";
- Remove ScalingEntry.getInventoryDumperClass() method
- Remove DumperFactory.createInventoryDumper method and update related code
- Update related unit test

Example:
- ImporterCreator, ImporterCreatorFactory

**Comment by sandynz** [comment]
Hi @huangdx0726 , are you interesting to resolve it?

**Comment by huangdx0726** [comment]
yes, please assign to me

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.

**Comment by huangdx0726** [comment]
yes， please assign to me



---Original---
From: "Hongsheng ***@***.***&gt;
Date: Sat, Aug 13, 2022 17:29 PM
To: ***@***.***&gt;;
Cc: "Da Xiang ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] Add InventoryDumperCreator SPI todecouple InventoryDumper and ScalingEntry (Issue #20128)




 
Hi @huangdx0726 , are you interesting to resolve it?
