### ISSUE TITLE
Refactor RuleAlteredContextManagerLifecycleListener for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20127]
Part of #19421.

Currently, RuleAlteredContextManagerLifecycleListener is hard-coded for one scenario, we could refactor it for common usage.

Possible changes:
- Rename RuleAlteredContextManagerLifecycleListener to PipelineContextManagerLifecycleListener
- Move PipelineContextManagerLifecycleListener to `org.apache.shardingsphere.data.pipeline.core.listener` package
- Add PipelineJobWorker class
- Move `initWorkerIfNecessary` method from RuleAlteredJobWorker to PipelineJobWorker

**Comment by huangdx0726** [comment]
I'll  work on it

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.
