### ISSUE TITLE
Add more test cases for StandardSQLErrorCode

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20131]
Some enum is not being tested yet, please add them too.

- [ ] SCALING_JOB_NOT_EXIST
- [ ] UNSUPPORTED_SQL

**Comment by huangdx0726** [comment]
please assign to me

**Comment by strongduanmu** [comment]
@huangdx0726 Welcome.

**Comment by huangdx0726** [comment]
`SCALING_OPERATE_FAILED` and `TOO_MANY_CONNECTIONS` are not EXIST in ShardingSphereVendorError

**Comment by terrymanu** [comment]
Some enum has removed after refactor, I just update the tasks.

**Comment by terrymanu** [comment]
Sorry, the StandardSQLErrorCode should be removed after exception refactor. I just close the issue
