### ISSUE TITLE
How do I create multiple ShardingSphereDatasource?

### ISSUE THREAD

**Issue by huahuo840** [apache/shardingsphere#20147]
I'm using DynamicDataSource, DynamicDataSource
Contains a ShardingSphereDatasource and a dbc2DataSource. 

When I try to create a ShardingSphereDatasource for more than one dbc2DataSource, I fail. 

The reason for this failure is that the multiple ShardingSphereDatasource created are actually the same, and I found that the ShardingSphereDatasource was init only once. Re-creation will point to the same address

![image](https://user-images.githubusercontent.com/86599014/184478459-b4528c82-ebec-44fb-bef7-7b3415d41ee7.png)

**Comment by RaigorJiang** [comment]
This is not a ShardingSphere issue, I will close it.
