### ISSUE TITLE
Decouple PipelineDDLGenerator with ContextManager for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20141]
Part of #19421.

Currently, PipelineDDLGenerator depends on ContextManager, ShardingSphereDatabase and Map<String,DataSource> will be got from ContextManager.
When importing data from unmanaged resource (database), we could not get DataSource from ContextManager.

Possible changes:
- Update parameters of generateLogicDDLSQL method to: databaseType, dataSource, schemaName, actualTableName, logicTableName, ShardingSphereSQLParserEngine
- Remove dependency of ContextManager from PipelineDDLGenerator

**Comment by huangdx0726** [comment]
assign to me

**Comment by sandynz** [comment]
> assign to me

Thanks. It's an urgent issue, would you still like to have a try?

**Comment by huangdx0726** [comment]
Is databaseName not required?

**Comment by sandynz** [comment]
> Is databaseName not required?

Looks it's used in `SQLStatementContextFactory.newInstance`, you could add it. And also other parameters if necessary.

**Comment by huangdx0726** [comment]
get it
