### ISSUE TITLE
This version of ShardingSphere-Proxy doesn't yet support this SQL.

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#20188]
Which version of ShardingSphere did you use?
ghcr.io/apache/shardingsphere-proxy:c9cc117c8f4b42c220f89c92851bf945c40c71b0 （helm cluster）

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Expected behavior
This version of ShardingSphere-Proxy support this SQL.

Actual behavior
This version of ShardingSphere-Proxy doesn't yet support this SQL.

![7a61c16d8d53d47d251746b1c15eed5](https://user-images.githubusercontent.com/51192624/184597036-31ed36ec-aea7-4392-9c42-3c3b498b5666.jpg)

Can you support some JSON functions for MySQL 8？

**Comment by strongduanmu** [comment]
Hi @Bingai077, can you provide the original sql?

**Comment by Bingai077** [comment]
```
SELECT
	COUNT(*) 
FROM
	production_basic_data_craft_define define 
WHERE
	JSON_CONTAINS( define.line_msg -> '$[*].code', '"CX07"', '$' ) 
	AND define.tenant_code = '6kr9mxk3'
```

**Comment by strongduanmu** [comment]
Welcome @tianhao960, I just assign this issue to you.

**Comment by strongduanmu** [comment]
Hi @Bingai077, can you help test this issue with master branch?
