### ISSUE TITLE
Missing documentation related to load balancing

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#20212]
Please refer to the documentation：
[READWRITE-SPLITTING EN](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/)

[READWRITE-SPLITTING CN](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/)

lack link about: [负载均衡算法](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/builtin-algorithm/load-balance/) and [Load Balance Algorithm](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/builtin-algorithm/load-balance/)

**Comment by TeslaCN** [comment]
This could be found in dev manual.
https://shardingsphere.apache.org/document/current/en/dev-manual/readwrite-splitting/

This issue has been inactive for a while, I'm closing it for now.
