### ISSUE TITLE
How to set the Time Zone for ShardingSphere-Proxy？

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#20217]
Which version of ShardingSphere did you use?
ghcr.io/apache/shardingsphere-proxy:c9cc117c8f4b42c220f89c92851bf945c40c71b0 （helm cluster）

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Expected behavior
After ShardingSphere-Proxy proxy, the time zone is Asia/Shanghai，same as a direct connection.

Actual behavior
After ShardingSphere-Proxy proxy, the time zone is eight hours apart.
My shard dataSources url configuration parameter is
 `jdbc:mysql://192.168.1.1:3306/test_db1?useUnicode=true&serverTimezone=Asia/Shanghai`

**Comment by RaigorJiang** [comment]
Hi @Bingai077 
When your client connects to the Proxy, you also need to set the time zone through the client URL.

**Comment by Bingai077** [comment]
@RaigorJiang When my client connects to the Proxy, I've set the time zone, too.But it's not in effect.
![image](https://user-images.githubusercontent.com/51192624/185021826-f076e7b2-8538-4bc6-87e8-7dab7b77d8b3.png)

**Comment by RaigorJiang** [comment]
Hi @TeslaCN , do you have some suggestions?

**Comment by Bingai077** [comment]
@RaigorJiang  It has been resolved. The specific reason is that the container is in the wrong time zone.

**Comment by RaigorJiang** [comment]
> @RaigorJiang It has been resolved. The specific reason is that the container is in the wrong time zone.

OK, thanks for your feedback.
