### ISSUE TITLE
auto-tables  There is no real sub-table sub-library  and  an error（Table 'sharding-jdbc-test2.t_order_4' doesn't exist） is reported 

### ISSUE THREAD

**Issue by kutouziUk** [apache/shardingsphere#20228]
# question 1： There is no real sub-table sub-library
- version: 5.1.2 
- mysql schema:
![image](https://user-images.githubusercontent.com/54654629/185032569-f8ebf61e-8942-4c94-98bf-11cbece4bd3c.png)
- yaml: 
![image](https://user-images.githubusercontent.com/54654629/185032973-07744c6d-4a0a-4db0-8f7c-7cfb1f0d2c76.png)
- result:  There are data in the sharding-jdbc-test.t_order_0 and sharding-jdbc-test2.t_order_1 tables. There is no data in the sharding-jdbc-test.t_order_1 and  sharding-jdbc-test2.t_order_0 tables.Personally, I think all tables should have data in them. Is it because of my understanding of auto-tables?

# question 2： Table 'sharding-jdbc-test2.t_order_4' doesn't exist
- version: 5.1.2 
- mysql schema：
![image](https://user-images.githubusercontent.com/54654629/185033705-074d76cc-92f9-45ff-b825-c68e827e2df6.png)
- yaml:
![image](https://user-images.githubusercontent.com/54654629/185034595-e929095e-7a7b-4d79-9199-87c6b02df34a.png)
![image](https://user-images.githubusercontent.com/54654629/185034666-dfe4fb90-12b7-49f5-bfbe-f43925b9bede.png)
- result: Table 'sharding-jdbc-test2.t_order_4' doesn't exist. But if a database sharding-jdbc-test4 is added, configure actual-data-sources: test$->{0..3}, sharding-count: 8  No error will be reported after starting and running

**Comment by strongduanmu** [comment]
Hi @kutouziUk thank you for your feedback. Sharding auto tables is suitable for scenarios where the maintenance of sharding tables is completely handed over to ShardingSphere. Users do not need to create actual tables by themselves, but only need to execute the `CREATE TABLE` statement through ShardingSphere, and ShardingSphere will automatically create actual tables.

**Comment by kutouziUk** [comment]
@strongduanmu 谢谢。 像我这种自建表的情况，auto-tables就不能适用吗？就不能使用auto-tables吗？

**Comment by strongduanmu** [comment]
> @strongduanmu 谢谢。 像我这种自建表的情况，auto-tables就不能适用吗？就不能使用auto-tables吗？

Please translate this message to English.

**Comment by kutouziUk** [comment]
@ strongduanmu thank you. Wouldn't auto-tables work in my case?

**Comment by strongduanmu** [comment]
@kutouziUk If you want to create actual tables by yourself, you can use tables configuration in ShardingRule, it supports config actualDataNodes. Just like:

```yaml
rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
```

**Comment by kutouziUk** [comment]
@strongduanmu Thank you for your answer，i know。 you say "but only need to execute the CREATE TABLE statement through ShardingSphere"  but I don't know much about DisSQL at present, let me look at the document first

**Comment by kutouziUk** [comment]
I'm sorry to trouble you again. you replied “but only need to execute the CREATE TABLE statement through ShardingSphere”
 How is the create table statement executed, directly in the client tool or through the Sharding-JDBC API?

**Comment by strongduanmu** [comment]
You can execute sql through ShardingSphere Proxy or JDBC.

**Comment by kutouziUk** [comment]
I'm just using Sharding-JDBC。
1、configure auto-tables first
2、run create table SQL by JDBC API
 ```mysql
    CREATE TABLE `t_order_0` (
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `price` decimal(10,2) NOT NULL COMMENT '订单价格',
  `user_id` bigint(20) NOT NULL COMMENT '下单用户id',
  `status` varchar(50) NOT NULL COMMENT '订单状态',
  PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `t_order_1` (
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `price` decimal(10,2) NOT NULL COMMENT '订单价格',
  `user_id` bigint(20) NOT NULL COMMENT '下单用户id',
  `status` varchar(50) NOT NULL COMMENT '订单状态',
  PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```
3、 all insert, select, update... statements
Is that how it works?

**Comment by kutouziUk** [comment]
I'm just using Sharding-JDBC。
1、configure auto-tables first
2、run create table SQL by JDBC API
 ```mysql
    CREATE TABLE `t_order_0` (
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `price` decimal(10,2) NOT NULL COMMENT '订单价格',
  `user_id` bigint(20) NOT NULL COMMENT '下单用户id',
  `status` varchar(50) NOT NULL COMMENT '订单状态',
  PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `t_order_1` (
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `price` decimal(10,2) NOT NULL COMMENT '订单价格',
  `user_id` bigint(20) NOT NULL COMMENT '下单用户id',
  `status` varchar(50) NOT NULL COMMENT '订单状态',
  PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```
3、 all insert, select, update... statements
Is that how it works?

**Comment by strongduanmu** [comment]
You should execute logic SQL, just like:

```sql
CREATE TABLE `t_order` (
 `order_id` bigint(20) NOT NULL COMMENT '订单id',
 `price` decimal(10,2) NOT NULL COMMENT '订单价格',
 `user_id` bigint(20) NOT NULL COMMENT '下单用户id',
 `status` varchar(50) NOT NULL COMMENT '订单状态',
 PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```

**Comment by kutouziUk** [comment]
ok, thank you

**Comment by kutouziUk** [comment]
thank you. I have successfully configured and executed

**Comment by strongduanmu** [comment]
That's great. If this problem has been solved, please close this issue.

**Comment by kutouziUk** [comment]
ok thank you
