### ISSUE TITLE
xa does not guarantee transactionality

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#20234]
## Bug Report
When the xa switch is turned on, two pieces of data are inserted into two datasources when inserting, but transactionality cannot be guaranteed.

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

![image](https://user-images.githubusercontent.com/26433395/185055919-1a920cb1-b51f-4b79-990b-59eaae6b27ab.png).

**Comment by FlyingZC** [comment]
I want to investigate the issue @strongduanmu .

**Comment by FlyingZC** [comment]
You can start a XA transaction such as using `SET AUTOCOMMIT=0` or `BEGIN`,in other cases, the XA transaction will not be opened.

**Comment by natehuangting** [comment]
> You can start a XA transaction such as using `SET AUTOCOMMIT=0` or `BEGIN`,in other cases, the XA transaction will not be opened.

@FlyingZC I think this can automatically open a transaction inside the Proxy, and submit.
