### ISSUE TITLE
An error occurred after executing the test case

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/shardingsphere#20237]
### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Execute successfully
### Actual behavior
Fail
### Example codes for reproduce this issue (such as a github link).
![微信图片_20220817153800](https://user-images.githubusercontent.com/40255310/185062051-deb44eb9-0b96-4e1b-b6cb-a155fab81f66.png).
As shown in the screenshot.
```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --add-opens
```

**Comment by strongduanmu** [comment]
@shining-stars-lk Can you check whether the local java environment is normal first?

**Comment by shining-stars-lk** [comment]
The local environment should be fine.
Executing the Example module is successful.

**Comment by shining-stars-lk** [comment]
It is okay.
It's my configuration.
thanks.

**Comment by TeslaCN** [comment]
This is caused by configuration of IDEA. You may reload Maven projects.
![image](https://user-images.githubusercontent.com/20503072/209623311-2efdffe3-bcc3-46ab-8ba8-0e8e44f099f3.png)
