### ISSUE TITLE
Shardingsphere-proxy don't automatically generate table schema

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#20256]
version：5.1.2
opt:
I push datasource to zk by myself ,the table schema don't generate automatically.But the 5.1.1 can generate automatically.The 5.1.2 does not support?

**Comment by TeslaCN** [comment]
Operating ZooKeeper directly is not recommended. Please consider adding DataSource by DistSQL.

**Comment by koala775** [comment]
Yes，but I need create difference database in a namespace.I have a try, to create database,it's fail.So I push database to zk by myself,and use distsql to add resource,it throw exception:Datasource or shardingsphere rule does not exist.

**Comment by koala775** [comment]
Thank you for replaying.I think I have resolved.I find use db tool does not support well,I use DBeaver to create database.
