### ISSUE TITLE
How does version 3.1 support ipv6 format？

### ISSUE THREAD

**Issue by xiaowoonly** [apache/shardingsphere#20264]
## How does version 3.1 support ipv6 format？

![4601e47fc888d000111048815370ff6](https://user-images.githubusercontent.com/26780965/185312902-479470f9-6b78-4143-9b00-d59aac227eb5.png)
It is precisely because of this regular check that the ipv6 format is not supported.
What should I do?

**Comment by linghengqian** [comment]
You should provide a reproducible unit test using the master branch.  No PR will go back to the old version.

**Comment by terrymanu** [comment]
The version is out of service
