### ISSUE TITLE
Syntax error when execute `ADD RESOURCE`

### ISSUE THREAD

**Issue by kutouziUk** [apache/shardingsphere#20285]
# SQL 
ADD RESOURCE resource_0 (HOST=192.168.60.100,PORT=3316,DB=sharding-proxy-test,USER=root,PASSWORD=root);
![image](https://user-images.githubusercontent.com/54654629/185522907-909f43b4-b359-4170-93ac-f8f3ec6d7829.png)
# sharding-proxy version
![image](https://user-images.githubusercontent.com/54654629/185522985-e6b47322-bc25-4418-af6c-c791abfc91db.png)
# server.yaml
![image](https://user-images.githubusercontent.com/54654629/185523151-67db50f1-55d4-4c0d-a6f2-88ee00f43948.png)

**Comment by RaigorJiang** [comment]
Hi @kutouziUk  ,
If you are using the master branch, please note that DistSQL syntax has some adjustments (parameters have been standardized), please refer to the latest documentation:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/resource-definition/

**Comment by kutouziUk** [comment]
@RaigorJiang ![image](https://user-images.githubusercontent.com/54654629/185543403-67677baf-0076-4f35-8a59-11b5a52d598a.png)
The database name cannot contain -？

**Comment by kutouziUk** [comment]
# example of official documentation
![image](https://user-images.githubusercontent.com/54654629/185547966-29c6b648-4d70-4bbf-89d3-52402e6f4ebb.png)
# Here is my configuration
![image](https://user-images.githubusercontent.com/54654629/185547821-b09e51ed-585f-48a9-8228-f819dc2a684d.png)
Does a string need not be included with ""?

**Comment by kutouziUk** [comment]
# example of official documentation
![image](https://user-images.githubusercontent.com/54654629/185550057-36cefb24-7d38-46c8-b0ac-e45514d97c77.png)
# here is my configuration
![image](https://user-images.githubusercontent.com/54654629/185550190-25e7102f-5a79-4e5f-b8b6-a0b824aebdc2.png)

# where can I see the error log? the console does not output syntax errors, I do not understand the specific reason why
![image](https://user-images.githubusercontent.com/54654629/185551098-7eecf56b-890e-460a-9943-4f9efa55b2e8.png)

**Comment by RaigorJiang** [comment]
@kutouziUk 
In versions 5.1.1 and 5.1.2, `HOST`, `DB`, `USER`, `PASSWORD` do not require quotes, but do not support special characters such as '`- @ . `' .
In order to better standardize DistSQL parameters, the master branch has required strings to be quoted, so that they can contain some special characters.

Therefore, if you use 5.1.1, the DB name has special characters, you cannot `ADD RESOURCE` in this way, you can refer to the URL method:
https://shardingsphere.apache.org/document/5.1.1/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/resource-definition/

eg.
```sql
ADD RESOURCE ds_0 (
    URL="jdbc:mysql://127.0.0.1:3306/db0?serverTimezone=UTC&useSSL=false",
    USER=root,
    PASSWORD=root
);
```

**Comment by kutouziUk** [comment]
@RaigorJiang 
Thank you for your answer. The execution succeeded, and I understood the difference in the version of the document I was looking at.

**Comment by RaigorJiang** [comment]
> @RaigorJiang Thank you for your answer. The execution succeeded, and I understood the difference in the version of the document I was looking at.

OK, so I can close this issue now.
