### ISSUE TITLE
Extract list() method to PipelineJobPublicAPI and AbstractPipelineJobAPIImpl for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20298]
Part of #19421.

Possible changes:
- Add abstract class PipelineJobInfo; Add sub-class MigrationJobInfo
- Add list() method in PipelineJobPublicAPI
- Extract list() impl from MigrationJobAPIImpl to AbstractPipelineJobAPIImpl

**Comment by huangdx0726** [comment]
assign to me

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.

**Comment by huangdx0726** [comment]
`PipelineJobInfo` 's structure  like `JobInfo`  or replace it？

**Comment by sandynz** [comment]
> `PipelineJobInfo` 's structure like `JobInfo` or replace it？

Like JobInfo.
You could extract some common fields into it. Looks most of them are common, except `tables`.
