### ISSUE TITLE
Why are  prepareStatement(final String sql, final int[] columnIndexes) and prepareStatement(final String sql, final String[] columnNames) in the ShardingSphereConnection the same

### ISSUE THREAD

**Issue by O-king** [apache/shardingsphere#20297]
## Question
why are they in the ShardingSphereConnection the same?
    
    @Override
    public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, Statement.RETURN_GENERATED_KEYS);
    }
    
    @Override
    public PreparedStatement prepareStatement(final String sql, final String[] columnNames) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, Statement.RETURN_GENERATED_KEYS);
    }

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
