### ISSUE TITLE
support KILL <processID> to cancel running SQL

### ISSUE THREAD

**Issue by ICannerxy** [apache/shardingsphere#20299]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

`SHOW PROCESSLIST` will list current running SQL, but not support `KILL processID` command to cancel running SQL.

**Comment by strongduanmu** [comment]
This feature is exciting, waiting for your good news.

**Comment by strongduanmu** [comment]
Ref #20311.
