### ISSUE TITLE
shardingsphere-proxy postgresql navicat design table error

### ISSUE THREAD

**Issue by wangkun001** [apache/shardingsphere#20304]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
 <version>5.1.2</version>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
navicat design table normal when use shardingsphere-proxy postgresql 
### Actual behavior
navicat design table error when use shardingsphere-proxy postgresql 

### Reason analyze (If you can)
antlr parse sql  syntax error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
select distinct routine_schema, routine_name, params.parameter from information_schema.routines left join ( select specific_schema, specific_name, group_concat(concat(data_type, ' ', parameter_name) order by ordinal_position separator ', ') parameter, routine_type from information_schema.parameters group by specific_schema, specific_name, routine_type ) params on routines.routine_schema = params.specific_schema and routines.routine_name = params.specific_name and routines.routine_type = params.routine_type where routine_schema = 'db' order by routine_schema

**Comment by strongduanmu** [comment]
Thank you for your feedback, ShardingSphere doesn't support PostgreSQL information_schema and pg_catalog now.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I'm closing it now.
If this problem persists, please reopen it or submit a new one.
