### ISSUE TITLE
Configuring the database of oracle

### ISSUE THREAD

**Issue by 13145512239** [apache/shardingsphere#20303]
Can you support this configuration for 4.0.0-RC1 ?
jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.12)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.22)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = rac)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))

**Comment by strongduanmu** [comment]
4.0.0-RC1 is too old. Can you try latest 5.1.2?

**Comment by linghengqian** [comment]
Duplicate with https://github.com/apache/shardingsphere/issues/20291.

**Comment by 13145512239** [comment]
> 4.0.0-RC1 is too old. Can you try latest 5.1.2?

Hi，I try 5.1.2, and OracleDataSourceMetaData can not pass this url, but 5.0.0 is ok ? can you fix this bug ?
