### ISSUE TITLE
Lack of documentation on properties of built-in algorithms related to cosid

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20328]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Yes, related to https://github.com/apache/shardingsphere/issues/14047.

### Describe the feature you would like.

- In https://shardingsphere.apache.org/document/current/en/dev-manual/sharding/, the following built-in algorithm classes are introduced.
    - org.apache.shardingsphere.sharding.cosid.algorithm.sharding.mod.CosIdModShardingAlgorithm
    - org.apache.shardingsphere.sharding.cosid.algorithm.sharding.interval.CosIdIntervalShardingAlgorithm 
    - org.apache.shardingsphere.sharding.cosid.algorithm.sharding.interval.CosIdSnowflakeIntervalShardingAlgorithm

- But in https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/sharding/, the above algorithm class lacks the introduction of properties. This part of the documentation should be supplemented.

**Comment by linghengqian** [comment]
@Ahoo-Wang  I noticed that `org.apache.shardingsphere.sharding.cosid.algorithm.sharding.interval.CosIdIntervalShardingAlgorithm` does not support common JSR-310 classes like `org.apache.shardingsphere.sharding.algorithm.sharding.datetime.IntervalShardingAlgorithm`, this is intentional Is it? Because the documentation doesn't say so.

**Comment by terrymanu** [comment]
Revert by #20603

**Comment by linghengqian** [comment]
https://github.com/apache/shardingsphere/pull/20605 has been merged, I will add the documentation later.  I am working on this issue.

**Comment by strongduanmu** [comment]
Hi @linghengqian, can we finish this issue in `5.1.3`?

**Comment by linghengqian** [comment]
> Hi @linghengqian, can we finish this issue in `5.1.3`?

I don't have time to deal with it these few days and can move out of the 5.1.3 milestone.

**Comment by strongduanmu** [comment]
Thank you for your feedback, I will move this issue to `5.2.1`.
