### ISSUE TITLE
Add IncrementalDumperCreator SPI to decouple IncrementalDumper and ScalingEntry

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20334]
Purpose
- Separate IncrementalDumper from ScalingEntry for better reuse

Possible changes:
- Add IncrementalDumperCreator interface, extends TypedSPI, marked as @SingletonSPI; Put in the same module and package of AbstractIncrementalDumper;
- Add MySQL & PostgreSQL & openGauss & Fixture implementations of IncrementalDumperCreator; Register them in resources/WEB-INF.services
- Add IncrementalDumperCreatorFactory; Put in the same module and package of AbstractIncrementalDumper;
- Add IncrementalDumperCreatorFactoryTest in shardingsphere-pipeline-test module, assert get instance of IncrementalDumperCreator by type "MySQL" / "PostgreSQL" / "openGauss" / "Fixture";
- Remove ScalingEntry.getIncrementalDumperClass() method
- Remove DumperFactory.createIncrementalDumper method and update related code
- Update related unit test
- Keep ScalingEntry and related classes & configs for now

Example:
- InventoryDumperCreator, InventoryDumperCreatorFactory

**Comment by huangdx0726** [comment]
assign to me

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.

**Comment by strongduanmu** [comment]
Hi @huangdx0726 , could we finish this issue in `5.1.3`?

**Comment by huangdx0726** [comment]
Ok， I'll fix tonight.
