### ISSUE TITLE
The database name cannot be properly obtained

### ISSUE THREAD

**Issue by coder616** [apache/shardingsphere#20338]
ShardingSphere version 5.1.2?

The database name cannot be properly obtained when using ShardingSphere-JDBC to connect to a mysql instance proxied by ShardingSphere-proxy.

org.apache.shardingsphere.infra.metadata.database.schema.loader.dialect.MySQLSchemaMetaDataLoader:

`private Map<String, Collection<ColumnMetaData>> loadColumnMetaDataMap(final DataSource dataSource, final Collection<String> tables) throws SQLException {
        Map<String, Collection<ColumnMetaData>> result = new HashMap<>();
        try (
                Connection connection = dataSource.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(getTableMetaDataSQL(tables))) {
            Map<String, Integer> dataTypes = DataTypeLoaderFactory.getInstance(DatabaseTypeFactory.getInstance("MySQL")).load(connection.getMetaData());
            String databaseName = "".equals(connection.getCatalog()) ? GlobalDataSourceRegistry.getInstance().getCachedDatabaseTables().get(tables.iterator().next()) : connection.getCatalog();
            preparedStatement.setString(1, databaseName);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    String tableName = resultSet.getString("TABLE_NAME");
                    ColumnMetaData columnMetaData = loadColumnMetaData(dataTypes, resultSet);
                    if (!result.containsKey(tableName)) {
                        result.put(tableName, new LinkedList<>());
                    }
                    result.get(tableName).add(columnMetaData);
                }
            }
        }
        return result;
    }`  

connection.getCatalog() returned is not real database name.

**Comment by strongduanmu** [comment]
Hi @coder616, ShardingSphere uses the logical database name, which can be configured in `config-xxx.xml` file.

**Comment by coder616** [comment]
I know that ShardingSphere Proxy uses the logical database name, but in practice, the logical database name is usually composed of prefix or suffix with business significance and the actual database name. So when I use the ShardingSphere - JBDC to a database table through the agent as the decryption MySQLSchemaMetaDataLoader cannot correct to get the actual metadata, leading to a join operation of the query results cannot be normal.

org.apache.shardingsphere.encrypt.merge.dql.EncryptMergedResult#getValue：
`public Object getValue(final int columnIndex, final Class<?> type) throws SQLException {
        Optional<EncryptContext> encryptContext = metaData.findEncryptContext(columnIndex);
        if (!encryptContext.isPresent() || !metaData.isQueryWithCipherColumn(encryptContext.get().getTableName(), encryptContext.get().getColumnName())) {
            return mergedResult.getValue(columnIndex, type);
        }
        Optional<EncryptAlgorithm> encryptAlgorithm = metaData.findEncryptor(encryptContext.get().getTableName(), encryptContext.get().getColumnName());
        if (!encryptAlgorithm.isPresent()) {
            return mergedResult.getValue(columnIndex, type);
        }
        Object cipherValue = mergedResult.getValue(columnIndex, Object.class);
        return null == cipherValue ? null : encryptAlgorithm.get().decrypt(cipherValue, encryptContext.get());
    }`

`/**
     * Find encrypt context.
     * 
     * @param columnIndex column index
     * @return encrypt context
     */
    public Optional<EncryptContext> findEncryptContext(final int columnIndex) {
        Optional<ColumnProjection> columnProjection = findColumnProjection(columnIndex);
        if (!columnProjection.isPresent()) {
            return Optional.empty();
        }
        TablesContext tablesContext = selectStatementContext.getTablesContext();
        String schemaName = tablesContext.getSchemaName().orElseGet(() -> DatabaseTypeEngine.getDefaultSchemaName(selectStatementContext.getDatabaseType(), database.getName()));
        Map<String, String> expressionTableNames = tablesContext.findTableNamesByColumnProjection(
                Collections.singletonList(columnProjection.get()), database.getSchema(schemaName));
        Optional<String> tableName = findTableName(columnProjection.get(), expressionTableNames);
        return tableName.map(optional -> EncryptContextBuilder.build(database.getName(), schemaName, optional, columnProjection.get().getName()));
    }`

**Comment by RaigorJiang** [comment]
When using ShardingSphere, the physical schema name cannot be used in the join statement.

This issue has been inactive for a long time, so I'm closing it now.
If this problem persists, please reopen it or submit a new one.
