### ISSUE TITLE
Add more unit tests in the class of `TransactionRuleTest` for transactions

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20347]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests in the class of `org.apache.shardingsphere.transaction.rule.TransactionRuleTest`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
You can add more unit tests for the methods of `addResource`,`closeStaleResource`,`closeStaleResource` in the class.
E.g. when you call `addResource`,it will recreate the `ShardingSphereTransactionManagerEngine` and the `databases` will contain the database you added.

**Comment by huangdx0726** [comment]
assign to me

**Comment by huangdx0726** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by FlyingZC** [comment]
Fixed by #22165.

**Comment by huangdx0726** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
