### ISSUE TITLE
Add more unit tests in the class of `TransactionTypeHolderTest` for transactions

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20346]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests in the class of `org.apache.shardingsphere.transaction.core.TransactionTypeHolderTest`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
You can add `LOCAL` and `BASE` unit tests in this class.

**Comment by huangdx0726** [comment]
assign to me

**Comment by strongduanmu** [comment]
@huangdx0726 Welcome, I just assign this issue to you.
