### ISSUE TITLE
merge will return empty list

### ISSUE THREAD

**Issue by mumutu66** [apache/shardingsphere#20352]
https://github.com/apache/shardingsphere/blob/f347765d0dfa05fe4d3a31c69813b34f66fe275a/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/main/java/org/apache/shardingsphere/sharding/merge/dql/pagination/TopAndRowNumberDecoratorMergedResult.java#L62

`pagination` is offset and limit  and canbe same value 。so why  skipOffset will change the rownumber to the offset value while compare to the actual row number which return false every time offset equals limit。

**Comment by strongduanmu** [comment]
Can you provide a demo to describe your problem?

**Comment by mumutu66** [comment]
。it's an issue report with `TopAndRowNumberDecoratorMergedResult` when use sqlserver will hit this logic.

first I use my own way to fixed (issue)[https://github.com/apache/shardingsphere/issues/17973]  then the case is a simple hello world example : one logic table with  two sharding table  table_0 , table_1

 I query a table with OFFSET 200 FETCH NEXT 200 the actualsql will be query every sharding table OFFSET 0 FETCH NEXT 400 , then come to the merge phase the origin logic in  ` `TopAndRowNumberDecoratorMergedResult` return empty list even both QueryResult has a 400 result, cuz the `pagination.getActualRowCount() ` is 200 and the rowNumber is set to 201 during the `skipOffset()`
Maybe there has two case the pagination ActualRowCount is 400 but something got error it return 200 or the rowNumber canbe 0.。。 currently I change the rowNumber = 0 and everything works well

**Comment by 2671884528** [comment]
I am using version 5.2.1 to connect to SQL server. This problem also occurs when using paging. How to solve it?

**Comment by 2671884528** [comment]
> 。it's an issue report with `TopAndRowNumberDecoratorMergedResult` when use sqlserver will hit this logic.
> 
> first I use my own way to fixed [issue](https://github.com/apache/shardingsphere/issues/17973) then the case is a simple hello world example : one logic table with two sharding table table_0 , table_1
> 
> I query a table with OFFSET 200 FETCH NEXT 200 the actualsql will be query every sharding table OFFSET 0 FETCH NEXT 400 , then come to the merge phase the origin logic in `TopAndRowNumberDecoratorMergedResult` return empty list even both `QueryResult` has a 400 result, cuz the `pagination.getActualRowCount() ` is 200 and the rowNumber is set to 201 during the `skipOffset()` Maybe there has two case one is the pagination ActualRowCount is 400 but something got error it return 200 and another is rowNumber should be 0.。。 currently I change the rowNumber = 0 and everything works well

Brother, how to solve this problem?
