### ISSUE TITLE
Add more unit test for SQLUtil

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20362]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `SQLUtil` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/SQLUtil.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by nnomier** [comment]
Hello ! Can I work on this issue?

**Comment by TeslaCN** [comment]
@nnomier Welcome!
