### ISSUE TITLE
Add more unit tests for the class of `AutoCommitUtils` 

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20360]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests for the class of `org.apache.shardingsphere.transaction.utils.AutoCommitUtils`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
Maybe you can mock the sqlStatement like `new MySQLSelectStatement()`,`new MySQLAlterTableStatement()`... and assert the result of `needOpenTransaction` method.

**Comment by FlyingZC** [comment]
You can check the test coverage on this page: https://app.codecov.io/gh/apache/shardingsphere
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/19788130/185869583-9413aa1e-99eb-4932-9f5c-6f128402d8e3.png">

**Comment by abhinav-koppula** [comment]
@strongduanmu - I have created a PR - https://github.com/apache/shardingsphere/pull/21332.
Can you please review?

**Comment by strongduanmu** [comment]
@abhinav-koppula Thank you for your remind, I will review this pr.
