### ISSUE TITLE
Add more unit test for DeleteStatementHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20364]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `DeleteStatementHandler` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/DeleteStatementHandler.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by abhinav-koppula** [comment]
@strongduanmu - I have created a PR - https://github.com/apache/shardingsphere/pull/20875.
Please review.
