### ISSUE TITLE
Add more unit test for ColumnExtractor

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20361]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `ColumnExtractor` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/util/ColumnExtractor.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by klurpicolo** [comment]
Hi, I'd like to work on this. Thanks.

**Comment by strongduanmu** [comment]
Welcome @klurpicolo, I will assign this issue to you.
