### ISSUE TITLE
Add more unit test for UpdateStatementHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20368]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `UpdateStatementHandler` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/dml/UpdateStatementHandler.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by abhinav-koppula** [comment]
@strongduanmu - Have created a PR - https://github.com/apache/shardingsphere/pull/20831. 
Please review.

**Comment by strongduanmu** [comment]
Hi @abhinav-koppula, thank you for your contributions in these days. Do you want to get involved in more advanced tasks such as enhancing SQL Parser?

**Comment by abhinav-koppula** [comment]
> Hi @abhinav-koppula, thank you for your contributions in these days. Do you want to get involved in more advanced tasks such as enhancing SQL Parser?

Yes, please. That was my intention as well. I wanted to get started with easy tasks and move towards bit advanced tasks.

**Comment by strongduanmu** [comment]
@abhinav-koppula Great plan, looking forward to your more contributions in the ShardingSphere community. If you have any questions, you can contact us via github or slack.

**Comment by abhinav-koppula** [comment]
> @abhinav-koppula Great plan, looking forward to your more contributions in the ShardingSphere community. If you have any questions, you can contact us via github or slack.

Thanks a lot for the encouragement and quick reviews.
