### ISSUE TITLE
Add more unit tests for the class of `OracleXAConnectionWrapper`

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20369]
Hi community,
This issue is for #28487

# Aim
Add more unit tests for the class of `org.apache.shardingsphere.transaction.xa.jta.connection.dialect.OracleXAConnectionWrapper`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
.You can refer to this class `org.apache.shardingsphere.transaction.xa.jta.connection.dialect.MySQLXAConnectionWrapperTest` to write unit tests.

**Comment by FlyingZC** [comment]
You can check the test coverage on this page: https://app.codecov.io/gh/apache/shardingsphere
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/19788130/185871961-893bd3f4-b157-458d-a4ae-1da836656dc3.png">

**Comment by cunhazera** [comment]
Can you assign?

**Comment by KaroK365** [comment]
Can I work on it ? 
Also a bit of guidance on how to approach, I am new to this.

**Comment by KaroK365** [comment]
I started working on it and taking reference to org.apache.shardingsphere.transaction.xa.jta.connection.dialect.MySQLXAConnectionWrapperTest


but still I am facing some issues

![image](https://github.com/user-attachments/assets/6e70e8e1-444b-4de7-801a-b5097143cae7)

Idk why intellij is showing red marks on them i have imported them too

![image](https://github.com/user-attachments/assets/44bbed5a-0604-4619-97f0-7f28f11b0b70)


also I have added Oracle dependency in POM - (shardingsphere - transaction - xa - core)
![image](https://github.com/user-attachments/assets/23a83114-d6b4-4da2-a3ac-09cc1f7c5637)
