### ISSUE TITLE
Enhanced algorithm checking for `CREATE SHARDING TABLE RULE`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20378]
Hi community,

Currently, users can configure sharding table rules in two different ways: `tables` and `autoTables`
([ref](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/))
Likewise, both configurations can be created via DistSQL: the difference is that one uses `DATANODES` to define storage nodes, while the other uses `RESOURCES`. ([ref](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/))

Note that when using the `autoTables` configuration, it should be used with the `Auto Sharding Algorithm`, but not others. ([ref](https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/sharding/))
If a non auto algorithm is provided to an auto table, the rule may not work.

Therefore, we should check when `CREATE SHARDING TABLE RULE` to help users find configuration errors early.

The processing logic is in `CreateShardingTableRuleStatementUpdater`, of course, `AlterShardingTableRuleStatementUpdater` should also do similar checks.

**Comment by sunkai-cai** [comment]
please assigness to me.
