### ISSUE TITLE
Add more unit test for CommentStatementHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20373]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `CommentStatementHandler` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/CommentStatementHandler.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by moukthika777** [comment]
Hi @strongduanmu , can I contribute to this issue?

**Comment by strongduanmu** [comment]
@moukthika777 Of course, I will assign this issue to you.
