### ISSUE TITLE
Add more unit test for ClusterStatementHandler

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20372]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `ClusterStatementHandler` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-sql-parser/shardingsphere-sql-parser-statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/handler/ddl/ClusterStatementHandler.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by strongduanmu** [comment]
@moukthika777 Can you comment on this issue? I will assign it to you.

**Comment by moukthika777** [comment]
@strongduanmu Can you assign this to me
