### ISSUE TITLE
Add more unit test for `BitronixRecoveryResource`

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20381]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests for the class of `org.apache.shardingsphere.transaction.xa.bitronix.manager.BitronixRecoveryResource`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
Add more unit tests for `org.apache.shardingsphere.transaction.xa.bitronix.manager.BitronixRecoveryResource` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/19788130/185874917-02abf61b-a3d1-4706-96bb-4e33cc7ba2c7.png">

**Comment by abhinav-koppula** [comment]
@FlyingZC - I have created a PR - https://github.com/apache/shardingsphere/pull/21313.
Can you please review?
