### ISSUE TITLE
Add more unit test for `SingleXAResourceHolder`

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20382]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests for the class of `SingleXAResourceHolder`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
Add more unit tests for `org.apache.shardingsphere.transaction.xa.bitronix.manager.SingleXAResourceHolder` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/19788130/185875275-102f4844-9b0d-499a-900f-fa50f7abf615.png">

**Comment by abhinav-koppula** [comment]
@FlyingZC - I have created a PR - https://github.com/apache/shardingsphere/pull/21315.
Can you please review?
