### ISSUE TITLE
Add more unit test for `AtomikosTransactionManagerProviderTest`

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20380]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests for the class of `org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProviderTest`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
Add more unit tests for `org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProviderTest` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19788130/185874229-07df5f79-c47a-4d67-a505-fe13d07117c4.png">

**Comment by abhinav-koppula** [comment]
@FlyingZC - I have created a PR - https://github.com/apache/shardingsphere/pull/21334.
Can you please review?
