### ISSUE TITLE
Add more unit test for `DefaultTransactionRuleConfigurationBuilder`

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#20387]
Hi community,
This issue is for [#20305](https://github.com/apache/shardingsphere/issues/20305)

# Aim
Add more unit tests for the class of `DefaultTransactionRuleConfigurationBuilder`.

# Basic Qualifications
- Java
- Maven
- Transaction

# Detail
Add more unit tests for `org.apache.shardingsphere.transaction.rule.builder.DefaultTransactionRuleConfigurationBuilder` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/19788130/185877321-69c1f4b0-13d3-4d87-8040-78d00b0171d1.png">

**Comment by abhinav-koppula** [comment]
@FlyingZC - I have created a PR - https://github.com/apache/shardingsphere/pull/21305 for this.
Can you please review?
