### ISSUE TITLE
Add more unit test for DefaultSQLParserRuleConfigurationBuilder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20396]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `DefaultSQLParserRuleConfigurationBuilder` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/main/java/org/apache/shardingsphere/parser/rule/builder/DefaultSQLParserRuleConfigurationBuilder.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by Swastyy** [comment]
Hi @strongduanmu , the links for unit test coverage in these relevant issues are not working for me. Can you check once if they work for you?

**Comment by strongduanmu** [comment]
> https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/main/java/org/apache/shardingsphere/parser/rule/builder/DefaultSQLParserRuleConfigurationBuilder.java

Yes, I can't open the page right now, I'll investigate why.

**Comment by strongduanmu** [comment]
@Swastyy You can try to access it from this page. https://app.codecov.io/gh/apache/shardingsphere
