### ISSUE TITLE
support parse ALTER PROCEDURE

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#20393]
Hi community,

This issue is for #20305.
ref to #6480

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support more sql parse. 

- [x] ALTER PROCEDURE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-PROCEDURE.html#GUID-24A5796F-7D97-49D4-8448-7E541CB73AC6)

## Process
1. Compare SQL definitions in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-language-elements.html#GUID-285DFAEE-1A34-4248-BA4B-2591476A0C3C) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle).
2. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc.
3. Run `mvn install the current_file_module`.
4. Check whether there are any exceptions. If indeed, please fix them. (`Especially xxxVisitor.class`).
5. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML.
6. Run SQLParserParameterizedTest to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

**Comment by tianhao960** [comment]
hi, @tuichenchuxin , I've just post a pr of alter procedure. 
ref: https://github.com/apache/shardingsphere/pull/20463

**Comment by strongduanmu** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/20463.
