### ISSUE TITLE
Add more unit test for SQLParserRule

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20392]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `SQLParserRule` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/main/java/org/apache/shardingsphere/parser/rule/SQLParserRule.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by abhinav-koppula** [comment]
@strongduanmu - Can you please review this PR - https://github.com/apache/shardingsphere/pull/21293
