### ISSUE TITLE
support parse EXPLAIN PLAN SQL 

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#20390]
Hi community,

This issue is for #28487.
ref to #6480

## Background
ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). At present, this parser engine can handle SQLs for `MySQL`, `PostgreSQL`, `SQLServer`, `openGauss` and `Oracle`, which means we have to understand different database dialect SQLs.
More details: 
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Task
This issue is to support more sql parse. 

- [ ] EXPLAIN PLAN [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/EXPLAIN-PLAN.html#GUID-FD540872-4ED3-4936-96A2-362539931BA0)

## Process
1. Compare SQL definitions in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-language-elements.html#GUID-285DFAEE-1A34-4248-BA4B-2591476A0C3C) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle).
2. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc.
3. Run `mvn install the current_file_module`.
4. Check whether there are any exceptions. If indeed, please fix them. (`Especially xxxVisitor.class`).
5. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML.
6. Run SQLParserParameterizedTest to make sure no exceptions.

## Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Oracle SQLs

**Comment by anamendes23** [comment]
I will work on this issue.
Would someone please assign it to me?

**Comment by TeslaCN** [comment]
Hi @anamendes23 Welcome!

**Comment by strongduanmu** [comment]
This issue has not been finished, so I will reopen it.

**Comment by anamendes23** [comment]
I have written the ANTLR grammar, but the visitors are not autogenerating when I rebuild the project.

**Comment by strongduanmu** [comment]
Hi @anamendes23, you can execute `mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true -Prelease -T 1C` on your local machine.

**Comment by AbnerHuang2** [comment]
@strongduanmu  this issue has fixed in this pr(#27228), can be marked as completed.

**Comment by strongduanmu** [comment]
@AbnerHuang2 Thank you for your feedback, I will close this issue.
