### ISSUE TITLE
Add more unit test for YamlSQLParserCacheOptionConfigurationSwapper

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20401]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

## Aim

Add more unit tests for `YamlSQLParserCacheOptionConfigurationSwapper` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere/blobs/master/shardingsphere-kernel/shardingsphere-parser/shardingsphere-parser-core/src/main/java/org/apache/shardingsphere/parser/yaml/swapper/YamlSQLParserCacheOptionConfigurationSwapper.java

## Basic Qualifications

- Java
- Maven
- Junit

**Comment by abhinav-koppula** [comment]
@strongduanmu - I have created a PR - https://github.com/apache/shardingsphere/pull/20768.
Can you please review?

**Comment by strongduanmu** [comment]
@abhinav-koppula Thank you for your remind, I will review this pr.
