### ISSUE TITLE
Limit metadata loading to specific configured Single Tables only

### ISSUE THREAD

**Issue by silversteak** [apache/shardingsphere#20431]
In GenericSchemaBuilder, I see that apart from the sharding tables all other tables meta data is getting loaded. Is it possible to limit that to specific configured Single Tables only. As my micro services needs only few tables out of 420 tables to get loaded. This will drastically boast the loading time of the service. 

![image](https://user-images.githubusercontent.com/25997886/186075652-b714cc2d-aa5d-4df0-9a44-bd1f4ef55867.png)

![image](https://user-images.githubusercontent.com/25997886/186000360-17d3b274-cdf1-4ab4-93b7-82c270f00d71.png)

**Comment by mouaifulao** [comment]
There are more than 1000 tables in our test environment, they belong to one Oracle schema.
The application took 30 minutes to start, and most of the time was spent on loading schemedata for single tables.
We just have 22 sharding tables, and most signle tables are not associated with these sharded tables.
Is there any way to load table metadatas  just for the sharded tables and the associated siginle tables?

**Comment by Calabor-Hoc** [comment]
I have the same concern. 
Loading all table metadata also brings another problem to me:
Oracle UROWID cannot be parsed by shardingsphere, which leads to NPE during boot.

**Comment by silversteak** [comment]
@terrymanu @TeslaCN can you please have a look into it ?

**Comment by strongduanmu** [comment]
@silversteak Thank you for your feedback, we are designing a new single table loading logic. By default, no single table is loaded. Users can specify which single tables to load through YAML or DistSQL.
