### ISSUE TITLE
Move directory `shardingsphere-charts` to sub-project repo `shardingsphere-on-cloud`

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere#20445]
Since there is a new sub-project [shardingsphere-on-cloud](https://github.com/apache/shardingsphere-on-cloud) mainly collects the cloud solutions for ShardingSphere, the `shardingsphere-charts` directory gets its chance to be moved to the shardingsphere-on-cloud repo.

**Comment by mlycore** [comment]
This is related to issue [Consider moving Helm Charts of ShardingSphere to this repo.](https://github.com/apache/shardingsphere-on-cloud/issues/29)

**Comment by TeslaCN** [comment]
Since the shardingsphere-charts has been moved to https://github.com/apache/shardingsphere-on-cloud.
PR: https://github.com/apache/shardingsphere-on-cloud/pull/41
I'm going to update the release guide of ShardingSphere and remove the shardingsphere-charts in this repository.
