### ISSUE TITLE
shrdingsphere-sacling data Migration Issues

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#20449]
Now our project is changing from single table to sub-database and sub-table, I would like to know if shardingsphere-scaling supports data migration from single table to sub-database and sub-table, is there any demo for reference, thank you.

**Comment by TeslaCN** [comment]
What you mentioned in issue is just a very basic function of ShardingSphere-Scaling. You may refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/scaling/

**Comment by huangconghe** [comment]
thanks
