### ISSUE TITLE
short-circuit query

### ISSUE THREAD

**Issue by ZZemptypoint** [apache/shardingsphere#20461]
## Feature Request

Assuming that our sharding-clomn type is a time-type, when we use the "limit" statement in the SQL, generally means we want it to short-circuit evaluation, Instead of routing it all the way.
For example:
``` sql
select * from table where time <'xxxx-xx-xx' limit 2
```
We want to find the first two pieces of data available before this time, they may be in different tables, but obviously there is no need to route all the tables. Now we make it table by table in business logic code, it's not cool.

### Is your feature request related to a problem?
NO, new feature request.

**Comment by RaigorJiang** [comment]
Hi @ZZemptypoint 
You can achieve this by configuring sharding rules and implementing sharding algorithms.

Considering this issue has been inactive for a long time, I'm closing it now.
If you still have the same problem, please reopen it or submit a new one.
