### ISSUE TITLE
subquery error,when result  contains *

### ISSUE THREAD

**Issue by xiaoxu9401** [apache/shardingsphere#20464]
when the query result set contains a.*, and contains  join sub query ,  the resultset is wrong。 final result fields has sub selected field。

such as  
 select
            a.*
        from litigation_lawyer a inner join (
            select lawyer_id, max(version) as version from litigation_lawyer_blacklist group by lawyer_id
        ) b on a.lawyer_id = b.lawyer_id and a.version = b.version

result:    a.* ,  lawyer_id

**Comment by xiaoxu9401** [comment]
error msg :
### Cause: java.sql.SQLException: Column index out of range.
; Column index out of range.; nested exception is java.sql.SQLException: Column index out of range.



 protected Field **getField**(int columnIndex) throws SQLException {
        if ((columnIndex < 1) || (columnIndex > this.fields.length)) {
            throw SQLError.createSQLException(Messages.getString("ResultSetMetaData.46"), SQLError.SQL_STATE_INVALID_COLUMN_NUMBER, this.exceptionInterceptor);
        }

        return this.fields[columnIndex - 1];
    }

**Comment by fourierxue** [comment]
I had the same problem

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, and ShardingSphere has released several new versions, can you try the latest version 5.3.1?
