### ISSUE TITLE
Remove `COUNT DATABASE RULES`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#20478]
Related to  #18583

`COUNT INSTANCE RULE` has been split into 
- `COUNT SINGLE_TABLE RULE`, 
- `COUNT SHARDING RULE` and many more

Then `COUNT DATABASE RULES` should also be removed.
The related classes are `CountDatabaseRulesStatement`, `DatabaseRulesCountResultSet` and corresponding `g4` and `visitor`.

**Comment by sunkai-cai** [comment]
please assign to me

**Comment by yx9o** [comment]
@sunkai-cai Hi, is this work in progress?

**Comment by sunkai-cai** [comment]
> @sunkai-cai Hi, is this work in progress?

sorry，i was late.
