### ISSUE TITLE
how to execute raw mybatis xml sql statement without sharding rout

### ISSUE THREAD

**Issue by pengfeis** [apache/shardingsphere#20499]
I faced an tricky error  "java.sql.SQLException: Statement parameter 1 not set " when execute an mapper sql statement like
```
-- table A, B only single table, no sharding rules
insert into A (x, y,z) select b1, b2, b3 from B where b1=#{b1} and b2 = #{b2}
```
After some debug and research I found the paramters missing after sharding.
My question is how execute raw mybatis xml sql statement without sharding rout, Any idea for shardig jdbc config ban the sharding route?

**Comment by strongduanmu** [comment]
@pengfeis Please modify this issue according to bug template.

**Comment by TeslaCN** [comment]
Close due to no response.
