### ISSUE TITLE
support  postgresl merge operation ("insert into on conflict update")

### ISSUE THREAD

**Issue by xiongdamao** [apache/shardingsphere#20506]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
 excute merge opertion sql  `INSERT INTO tb_user (id,name) VALUES (#{id},#{name}) ON CONFLICT (id) DO UPDATE SET name=#{name} witch parameters **id00(String), test_name(String), test_name(String)**` in postgres db
it should be no error occurs.

### Actual behavior
we got following errors:
2022-08-25 13:08:50.145 DEBUG 20200 --- [nio-8080-exec-1] test.UserMapper.merger                   : ==>  Preparing: INSERT INTO tb_user (id,name) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET name=?
2022-08-25 13:08:51.108 DEBUG 20200 --- [nio-8080-exec-1] test.UserMapper.merger                   : ==> Parameters: **id00(String), test_name(String), test_name(String)**
2022-08-25 13:08:51.153  INFO 20200 --- [nio-8080-exec-1] ShardingSphere-SQL                       : Logic SQL: INSERT INTO tb_user (id,name) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET name=?
2022-08-25 13:08:51.153  INFO 20200 --- [nio-8080-exec-1] ShardingSphere-SQL                       : SQLStatement: PostgreSQLInsertStatement(withSegment=Optional.empty)
2022-08-25 13:08:51.153  INFO 20200 --- [nio-8080-exec-1] ShardingSphere-SQL                       : Actual SQL: ds0 ::: INSERT INTO tb_user (id,name) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET name=? ::: **[id00, test_name]**
2022-08-25 13:08:51.196  INFO 20200 --- [nio-8080-exec-1] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2022-08-25 13:08:51.245  INFO 20200 --- [nio-8080-exec-1] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2022-08-25 13:08:51.256 ERROR 20200 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: 
 Error updating database.  Cause: org.postgresql.util.PSQLException: 未设定参数值 3 的内容。{( No value specified for parameter 3)}
The error may exist in test/UserMapper.java (best guess)
The error may involve test.UserMapper.merger-Inline
 The error occurred while setting parameters
 SQL: INSERT INTO tb_user (id,name) VALUES (?,?) ON CONFLICT (id) DO UPDATE SET name=?
 Cause: org.postgresql.util.PSQLException: 未设定参数值 3 的内容。{( No value specified for parameter 3)}
; SQL []; 未设定参数值 3 的内容。{( No value specified for parameter 3)}; nested exception is org.postgresql.util.PSQLException: 未设定参数值 3 的内容。] with root cause

 
### Reason analyze (If you can)
maybe version 5.1.2 of shardingsphere not support postgresql merge operation ("insert into on conflict update")

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. create a table in postgresql 
CREATE TABLE tb_user
(
    id character varying(10),
    name character varying(10) ,
    CONSTRAINT user_id PRIMARY KEY (id)
)
2. ceate spring boot project with mybatis and sharding-jdbc
3. create UserMapper
   @Update({"INSERT INTO tb_user (id,name) VALUES (#{id},#{name}) " +
            "ON CONFLICT (id) DO UPDATE SET name=#{name}"})
    int merge(User user);
4. create UserService
 public int merge(User user) {
        return this.baseMapper.merge(user);
    }
5. create  UserController
 @GetMapping("/merge")
    public int merge() {
        return service.merge(User.builder().id("id00").age(12).name("test_name").email("test@test.com").build());
    }
6.  add sharding rule in application.yml
   rules:
      sharding:
        tables:
          tb_user:
            actual-data-nodes: ds0.tb_user
            databaseStrategy:
              none:
6. enter url:  http://localhost:8080/user/merge in browser

### Example codes for reproduce this issue (such as a github link).
https://github.com/xiongdamao/test-sharding

**Comment by strongduanmu** [comment]
Hi @xiongdamao, thank you for your feedback. Can you modify this issue according to bug template.

**Comment by xiongdamao** [comment]
Hi @strongduanmu , I changed the template of issue from "Feature Request" to "Bug Report"

**Comment by strongduanmu** [comment]
@xiongdamao Thank you, can you provide the configuration of tb_user?

**Comment by strongduanmu** [comment]
@xiongdamao Thank you, can you provide the configuration of tb_user?

**Comment by xiongdamao** [comment]
@strongduanmu add the configuration of tb_user to https://github.com/xiongdamao/test-sharding/tree/master/src/main/resources

**Comment by strongduanmu** [comment]
> nfiguration of t

@xiongdamao Thank you for your detailed information.

**Comment by tianhao960** [comment]
hi, @strongduanmu  I‘d like to try

**Comment by strongduanmu** [comment]
@tianhao960 Welcome, I will assign this issue to you.

**Comment by strongduanmu** [comment]
@tianhao960 At present, we only solved the parsing problem, and we need to confirm whether it can be executed in the sharding scenario.

**Comment by tianhao960** [comment]
@strongduanmu try the sharding scenario with following config:
`spring:
  shardingsphere:
    # 是否开启
    datasource:
      # 数据源（逻辑名字）
      names: m1
      # 配置数据源
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name:  org.postgresql.Driver
        jdbc-url: jdbc:postgresql://192.168.64.2:5432/test
        username: root
        password: 123456
    # 分片的配置
    rules:
      sharding:
        # 表的分片策略
        tables:
          # 逻辑表的名称
          tb_user:
            # 数据节点配置，采用Groovy表达式
            actual-data-nodes: m1.tb_user${0..1}
            # 配置策略
            table-strategy:
              # 用于单分片键的标准分片场景
              standard:
                sharding-column: id
                # 分片算法名字
                sharding-algorithm-name: user_inline
            key-generate-strategy: # 主键生成策略
              column: id  # 主键列
              key-generator-name: snowflake  # 策略算法名称(推荐使用雪花算法)
        key-generators:
          snowflake:
            type: SNOWFLAKE
        sharding-algorithms:
          user_inline:
            type: inline
            props:
              algorithm-expression: tb_user$->{id % 2}
    props:
      # 日志显示具体的SQL
      sql-show: true`

and insert success.

**Comment by tianhao960** [comment]
@strongduanmu try the sharding scenario with following config:
![1662555486287](https://user-images.githubusercontent.com/1155952/188883940-c0a27bee-cc4e-4246-822a-77cd3086f66d.jpg)

**Comment by strongduanmu** [comment]
@tianhao960 Good  job, can you test insert update statement when update sharding column? 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10829171/189002981-9b5da05f-580b-4815-96d7-cda896a6e493.png">

**Comment by tianhao960** [comment]
hi, @strongduanmu , have test the scenario that sharding key and update column are the same; and could insert success when do not cause sharding change and throw exception when cause sharding changes, that is the expect behavior of current version of shardingSphere.  thanks.

**Comment by strongduanmu** [comment]
Thank you for your feedback, I will close this issue.
