### ISSUE TITLE
Cannot add resources after discovery rules created

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#20513]
### Which version of ShardingSphere did you use?
master 6cf1f1e8352d7be5c501a5626ef44e708a5b0d2b
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
 ADD RESOURCE success.
### Actual behavior
Got an exception and ADD RESOURCE failed.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Add resources `ds_0`, `ds_1`, `ds_2`.
```
add resource 
ds_0(url="jdbc:mysql://xxx.xx.xx.xx:33306/primary_demo_ds?serverTimezone=UTC&useSSL=false", user="root",password="xxxxxx"), 
ds_1(url="jdbc:mysql://xxx.xx.xx.xx:33307/primary_demo_ds?serverTimezone=UTC&useSSL=false", user="root",password="xxxxxx"),
ds_2(url="jdbc:mysql://xxx.xx.xx.xx:33308/primary_demo_ds?serverTimezone=UTC&useSSL=false", user="root",password="xxxxxx");
```
2. Create database discover rule `group0`.
```
CREATE DB_DISCOVERY RULE group_0 ( RESOURCES(ds_0, ds_1, ds_2), TYPE(NAME='MySQL.MGR',PROPERTIES('group-name'='558edd3c-02ec-11ea-9bb3-080027e39bd2')), HEARTBEAT(PROPERTIES('keep-alive-cron'='0/5 * * * * ?')) );
```
3. Add resource `resource_0`.
```
ADD RESOURCE resource_0 (
    HOST="127.0.0.1",
    PORT=3306,
    DB="db0",
    USER="root",
    PASSWORD="123456"
);
```

### Log
```
ERROR 1999 (42000): Unknown exception: java.lang.NullPointerException
```

**Comment by strongduanmu** [comment]
Hi @Qianyi951015 @RaigorJiang , can we finish this issue in `5.1.3`?

**Comment by strongduanmu** [comment]
I will move this issue to `5.2.1`.

**Comment by RaigorJiang** [comment]
> I will move this issue to `5.2.1`.

OK, thank you @strongduanmu

**Comment by strongduanmu** [comment]
Hi @RaigorJiang , could we finish this issue in 5.2.1?

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang , could we finish this issue in 5.2.1?

Let me check it.

**Comment by RaigorJiang** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/5668787/195303442-5818af01-72df-4885-bd80-003c7e7bdede.png">

Hi @Qianyi951015  I can't reproduce the problem, can you reproduce it?

**Comment by Qianyi951015** [comment]
I also can not reproduce it now. Maybe already been solved by someone.
