### ISSUE TITLE
Remove ScalingEntry and related classes

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20525]
We've decoupled all of classes in ScalingEntry as SPI, so we could remove ScalingEntry and related classes now.

Possible changes:
- Remove ScalingEntry, ScalingEntry SPI impl and SPI registration in WEB-INF.services
- Remove ScalingEntryFactory
- Remove related unit test

**Comment by huangdx0726** [comment]
assign to me

**Comment by sandynz** [comment]
Thanks. Just assigned it to you.
