### ISSUE TITLE
About TNS in OracleDataSourceMetaData Class

### ISSUE THREAD

**Issue by powerbear1994** [apache/shardingsphere#20529]
private final Pattern connectDescriptorUrlPattern = Pattern.compile("jdbc:oracle:(thin|oci|kprb):@[(\\w\\s=)]+HOST\\s*=\\s*([\\w\\-\\.]+).*PORT\\s**=\\s(\\d+).*SERVICE_NAME\\s**=\\s*(\\w+)\\)");

i think it should be 

private final Pattern connectDescriptorUrlPattern = Pattern.compile("jdbc:oracle:(thin|oci|kprb):@[(\\w\\s=)]+HOST\\s*=\\s*([\\w\\-\\.]+).*PORT\\s**=\\s*(\\d+).*SERVICE_NAME\\s**=\\s*(\\w+)\\)");

forget a * after "PORT\\s*=\\s"

**Comment by TeslaCN** [comment]
Hi @powerbear1994 
Are you interested in fixing this issue?

**Comment by abhinav-koppula** [comment]
@TeslaCN - I have created a PR https://github.com/apache/shardingsphere/pull/20701.
Does it fix the issue?
