### ISSUE TITLE
ExecuteProcessEngine increases about 7% unnecessary CPU overhead for ShardingSphere-JDBC

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#20531]
### Which version of ShardingSphere did you use?

master - 6e603add90c02a81726375be49ddf5f5e1760e31

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC standalone

### Expected behavior

Light overhead.

### Actual behavior

The total overhead of ExecuteProcessEngine is about 7%. But this overhead is useless for standalone ShardingSphere-JDBC.

![image](https://user-images.githubusercontent.com/20503072/186793962-0c0c4b7c-c900-4f39-9269-dacc02532fc9.png)

**Comment by strongduanmu** [comment]
Hi @TeslaCN, can we close this issue now?

**Comment by TeslaCN** [comment]
I tested the ShardingSphere-JDBC + openGauss, the overhead was eliminated.
