### ISSUE TITLE
Error Msg: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'

### ISSUE THREAD

**Issue by bojiw** [apache/shardingsphere#20559]
execute sql DELETE FROM groups WHERE `id` = 1368 error
message：Error Msg: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'; Sql: DELETE FROM groups WHERE `id` = 1368

sql is executable in mysql

using sharding-proxy 5.1.2

**Comment by tianhao960** [comment]
I would like to try this.

**Comment by strongduanmu** [comment]
@tianhao960 Welcome, I just assign this issue to you.

**Comment by tianhao960** [comment]
hello, @bojiw , which version of mysql did you use? I've try the sql it can not run at mysql 8.0 . and the word "groups" is a reserved keyword of mysql from version 8.0; and ShardingSphere is treated "groups" as a reserved keyword like mysql 8.0, so can not use groups as a table name. 

and the temp work around is add ` around  groups
`DELETE FROM `groups` WHERE id = 1368;`

**Comment by strongduanmu** [comment]
This issue has not been finished, so I will reopen it.
