### ISSUE TITLE
Routing problem in the new transcation(propagation = Propagation.REQUIRES_NEW) 

### ISSUE THREAD

**Issue by mmcLine** [apache/shardingsphere#20614]
### Which version of ShardingSphere did you use?

4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Read the data immediately after writing, expecting to query from the master database
### Actual behavior

query from the slave database

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

service query by slave database：

![image](https://user-images.githubusercontent.com/37876129/187062373-bfef1ce9-72f8-4d6f-befc-ca03a271c19a.png)

### Example codes for reproduce this issue (such as a github link).

```
@Service
public class CityService {

    @Autowired
    private CityRepository cityRepository;

    @Autowired
    private CityService2 cityService2;

    @Transactional(rollbackFor = Exception.class)
    public void test(){
        City city=new City();
        city.setName("眉山");
        city.setProvince("四川");
        cityRepository.save(city);

        cityService2.test();

        List<City> all = cityRepository.findAll();
        all.forEach(x->{
            System.out.println("cityService:"+((x.getProvince().equals("四川"))?"主库":"从库")+":"+x);
        });
    }
}
```

```
public class CityService2 {

    @Autowired
    private CityRepository cityRepository;

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void test(){
        List<City> all = cityRepository.findAll();
        all.forEach(x->{
            System.err.println("cityService2:"+((x.getProvince().equals("四川"))?"主库":"从库")+":"+x);
        });
    }
}

```

**Comment by strongduanmu** [comment]
Hi @mmcLine 4.1.0 is too old, can you try the latest 5.1.2?

**Comment by mmcLine** [comment]
> Hi @mmcLine 4.1.0 is too old, can you try the latest 5.1.2?

I tried the latest version, but it's still wrong

**Comment by FlyingZC** [comment]
This bug has been fixed by https://github.com/apache/shardingsphere/pull/20814 .See the reply below this issue #20789.

**Comment by RaigorJiang** [comment]
Fixed.
