### ISSUE TITLE
support MD5 authentication for proxy frontend.

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#20619]
## Feature Request

**For English only**, other languages will not accept.
I want use pg driver to connect ss-proxy, but in backend database type is openGauss.

### Is your feature request related to a problem?
No.

### Describe the feature you would like.
the reason is pg driver default authentication is  MD5, but when backend database type is openGauss, only support SHA256.
I want configure ss-proxy support both MD5 and SHA256 authentication。

**Comment by RaigorJiang** [comment]
I want to complete this feature 😀
