### ISSUE TITLE
Does sharding JDBC support insert into select

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#20632]
Does sharding JDBC support insert into select？
Not through my custom sharding-Algorithm, such as actual-data-nodes: ds0.order_$->{['tr','fs']}_$->{0..9},
Actual stored table is order_tr_0,do not throw exception.

**Comment by strongduanmu** [comment]
Now, ShardingSphere can support insert into select for binding tables and single tables, you can try the latest version.

**Comment by taku-hua** [comment]
actually  it don't support,  i use 4.1.1 。  
the sql is like below  
```sql
insert  into tabel1 (id, name) select id,'#{name}' from tableB
```
and it throw a nullpointerException from tree.visit(this) in 

```java
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser
@Override
		public <T> T accept(ParseTreeVisitor<? extends T> visitor) {
			if ( visitor instanceof MySQLStatementVisitor ) return ((MySQLStatementVisitor<? extends T>)visitor).visitInsert(this);
			else return visitor.visitChildren(this);
		}

```
