### ISSUE TITLE
Can we provide a DistSQL like `REFRESH GlOBAL TABLE METADATA;` to make refresh table metadata easier ?

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#20630]
### Is your feature request related to a problem?
No
### Describe the feature you would like.

Now `DistSQL` only support refresh table metadata in some logic database.
When user create table in actual DB,we must execute `refresh table metadata *` in every logic database.
It's really difficult,when i have thousands of logic database need to refresh.
If we can provide a DistSQL like `REFRESH GlOBAL TABLE METADATA;`,then we will bring a better experience.

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/86462784/187155243-3615d501-8a68-4d6d-9e35-600106338b50.png">

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/

**Comment by TeslaCN** [comment]
Hi @RaigorJiang 
Please help checking this.

**Comment by RaigorJiang** [comment]
Hi @wsm12138 
`Table metadata` belongs to a certain logic database, and `GlOBAL TABLE METADATA` is a concept that is not easy to understand.
Why do you have thousands of logic databases? What kind of scene is it?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
