### ISSUE TITLE
 ARJUNA016111: The node identifier cannot be null

### ISSUE THREAD

**Issue by Xiao-A-Zhai** [apache/shardingsphere#20649]
![image](https://user-images.githubusercontent.com/84503834/187378635-4cec41c9-2e3d-4877-8960-42ae9492821c.png)
![image](https://user-images.githubusercontent.com/84503834/187378716-b76c6c6c-5d74-46fd-9267-3c930afe993c.png)

I according to your document at https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/transact  An exception was reported in the process of configuration.   Was there a problem with the example I found?   Then I tried to manually set the first screenshot to solve the problem, and the code thrown by the exception was in the second screenshot

**Comment by Xiao-A-Zhai** [comment]
![image](https://user-images.githubusercontent.com/84503834/187358961-47854854-82f2-4bf2-ac58-2657433b0254.png)
我在代码里也没有找到相关项的配置。。。

**Comment by TeslaCN** [comment]
Hi @FlyingZC 
Please help checking this.

**Comment by FlyingZC** [comment]
@Xiao-A-Zhai Hi, The `NarayanaConfigurationFileGenerator` has been removed now.And could you please describe the problem more clearly?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
