### ISSUE TITLE
how to config multi databaseName

### ISSUE THREAD

**Issue by lirulei** [apache/shardingsphere#20653]

**Comment by tangjunhu007** [comment]
in proxy mode?

**Comment by TeslaCN** [comment]
Just configure multiple config-*.yaml files like the following

```
conf
├── config-bmsql-sharding-mod.yaml
├── config-sharding-mysql.yaml
├── config-sysbench-single.yaml
├── config-sysbench.yaml
└── server.yaml
```

You may refer to:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/startup/bin/
