### ISSUE TITLE
Consider loading view metadata to ShardingSphereSchema

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#20681]
Hi, community

We are plan to load database view meta data to support #19580 

- [x] Loading MySQL view metadata.
- [x] Loading PostgreSQL view metadata.
- [x] Loading openGauss view metadata.
- [x] Loading SQLServer view metadata. @dongzl 
- [ ] Loading Oracle view metadata. @chakkk309 
- [ ] Loading H2 view metadata. @agentart 

```
public final class ShardingSphereSchema {
    
    private final Map<String, ShardingSphereTable> tables;
    
    private final Map<String, ShardingSphereView> views;
}
```

**Comment by agentart** [comment]
@zjcnb Hi, I claim the implementation of h2

**Comment by zjcnb** [comment]
> @zjcnb Hi, I claim the implementation of h2

Cool.

**Comment by dongzl** [comment]
SQLServer

**Comment by zjcnb** [comment]
> SQLServer

Welcome

**Comment by chakkk309** [comment]
Hi, I would like to implement the Oracle part.

**Comment by zjcnb** [comment]
> Hi, I would like to implement the Oracle part.

Welcome

**Comment by zhaojinchao95** [comment]
Hi everyone, this issue has some problem. I will rearrange, So i close it.
