### ISSUE TITLE
when READWRITE_SPLITTING rule exist, alter resource or add new resource occur error

### ISSUE THREAD

**Issue by wzhj2326** [apache/shardingsphere#20727]
### Which version of ShardingSphere did you use?
5.1.3-SNAPSHOT   5.2.0  tag

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
premise:
      when create two resouces (ds_01、ds_02) and create two READWRITE_SPLITTING rules ,READWRITE_SPLITTING rules use these resources

action:
     i alter resource ds_01 , then return  ERROR 1102 (C1102): Resources [ds_02] do not exist in database sharding_demo.

    add new resource also report that

**Comment by zjcnb** [comment]
@wzhj2326 Thank you for your feedback, this is a bug. Let me fixed it.

**Comment by strongduanmu** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/20747.
