### ISSUE TITLE
[5.1.0] <sharding:table-rule /> without 'actual-data-sources' property?

### ISSUE THREAD

**Issue by djmirv** [apache/shardingsphere#20728]
1, 'sharding:table-rule'  has property 'actual-data-sources':
https://shardingsphere.apache.org/document/5.1.0/en/user-manual/shardingsphere-jdbc/spring-namespace/rules/sharding/

2,  but practically not found :
    <xsd:element name="table-rule">
http://shardingsphere.apache.org/schema/shardingsphere/sharding/sharding-5.1.0.xsd)

**Comment by linghengqian** [comment]
- I believe this is an older version of the documentation bug. Since it is not possible to submit PRs to archived tags, you can update to 5.1.2 to verify.

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
