### ISSUE TITLE
[5.1.0] readwrite-splitting:data-source-rule without 'data-source-rule' property?

### ISSUE THREAD

**Issue by djmirv** [apache/shardingsphere#20722]
1，property showed in doc.
https://shardingsphere.apache.org/document/5.1.0/cn/user-manual/shardingsphere-jdbc/spring-namespace/rules/readwrite-splitting/

2，but not showed in '.xsd' file
http://shardingsphere.apache.org/schema/shardingsphere/readwrite-splitting/readwrite-splitting-5.1.0.xsd

**Comment by linghengqian** [comment]
- I believe this is an older version of the documentation bug.  Since it is not possible to submit PRs to archived tags, you can update to 5.1.2 to verify.
