### ISSUE TITLE
Extract pipeline meta data node change listener SPI for common usage

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20735]
Part of #19421.

Currently, on wathcing `/pipeline`, event key will be matched by different hard-coded regex, it's not easy to add new node change logic. So it's better to extract pipeline meta data node change listener SPI for common usage.

Related code:
- PipelineJobExecutor.doStart method

We might need to handle process configuration change for migration job and other types of jobs in the future. And new type job might need to handle other nodes change.

Possible changes:
- Add pipeline meta data node change listener SPI
- Add SPI factory
- Add SPI impl
- Refactor PipelineJobExecutor as singleton
- Add method in PipelineJobExecutor to register listener
- Unit test, etc

**Comment by sandynz** [comment]
@azexcy , could you help to follow it?

**Comment by azexcy** [comment]
I will follow it.
