### ISSUE TITLE
Consider refactoring SQLParserParameterizedTest and UnsupportedSQLParserParameterizedTest using ThreadPool for efficient execution

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#20742]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

At present, when we execute `mvn clean install -Prelease -T 1C` in the `shardingsphere-sql-parser` module, we can find that the execution time is very long, so we need to consider using a thread pool to execute unit tests concurrently to improve the execution of sql parser unit tests efficiency.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/10829171/188155528-5d3326bf-6863-4243-94b5-89498c435374.png">

How to reproduce this problem?

```bash
cd shardingsphere-sql-parser
mvn clean install -Prelease -T 1C
```

**Comment by tianhao960** [comment]
hi, @strongduanmu , I'd like to try this

**Comment by strongduanmu** [comment]
@tianhao960 Welcome, I will assign this issue to you.
