### ISSUE TITLE
Add test case for ShardingSpherePreconditions

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20749]

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by abhinav-koppula** [comment]
Hi @terrymanu 
I have created a PR for the same - https://github.com/apache/shardingsphere/pull/20765
Can you please take a look?

**Comment by terrymanu** [comment]
> Hi @terrymanu I have created a PR for the same - #20765 Can you please take a look?

Good implementation, I had merged it.

**Comment by terrymanu** [comment]
> I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

Thank you for pay attention, this PR is be merged, please pick up more other issues next time.
