### ISSUE TITLE
Springboot 集成 MybaitsPlus+ShardingShere报错 

### ISSUE THREAD

**Issue by strongyc** [apache/shardingsphere#20763]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\javaProject\ShardingShereDemo4\target\classes\com\yc\modular\user\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/ShardingSphereAutoConfiguration.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.shardingsphere.infra.config.mode.ModeConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by linghengqian** [comment]
- No one knows how to solve your issue. You have neither formatted the log information in markdown, nor provided a minimal reproducible example, nor did you provide reproducible steps, and it does not conform to the issue template.

- This issue can be closed and marked as invalid.

**Comment by agentart** [comment]
@strongyc Please modify it according to the issue template.

**Comment by strongyc** [comment]
> @strongyc Please modify it according to the issue template.

[ShardingShereDemo4.zip](https://github.com/apache/shardingsphere/files/9484640/ShardingShereDemo4.zip)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
