### ISSUE TITLE
Official website CSS style confused.

### ISSUE THREAD

**Issue by dongzl** [apache/shardingsphere#20772]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

<img width="859" alt="image" src="https://user-images.githubusercontent.com/5917359/188314955-4d20861d-78e7-4138-b156-acb931e96a91.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/5917359/188314965-59f96b7e-de14-41c1-8252-5ac91ae3a846.png">

**Comment by strongduanmu** [comment]
Hi @dongzl, You can try to force refresh the website.

**Comment by dongzl** [comment]
> Hi @dongzl, You can try to force refresh the website.

Thanks, It's OK.
