### ISSUE TITLE
Add unit test for ClusterContextManagerCoordinator.killProcessListId(final KillProcessListIdEvent event)

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#20802]

**Comment by theshashankpal** [comment]
Hi @zhaojinchao95 ,
I am a student who needs to contribute to an OpenSource project in my coursework, so I was wondering if you can assign this to me.
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can someone please assign this to me?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , I am a student who needs to contribute to an OpenSource project in my coursework, so I was wondering if you can assign this to me. This issue seems to be a good initiation of my journey towards contribution to FOSS projects. Can someone please assign this to me?

Ok, i will assign you
