### ISSUE TITLE
use recursion to setNextException with chain in classes JDBCBackendTransactionManager and LocalTransactionManager

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20810]
Please use recursion to setNextException with chain, not overlap in classes JDBCBackendTransactionManager and LocalTransactionManager.

Just search `// TODO` to find the codes.

**Comment by null-sys** [comment]
Hey @terrymanu , I am interested in resolving this issue. This will be my first contribution here, let me know if this needs to be assigned to me or I can raise a PR for this.

**Comment by TeslaCN** [comment]
Hi @null-sys 
Assigned.

**Comment by strongduanmu** [comment]
Hi @null-sys , could we finish this issue in 5.2.1?

**Comment by null-sys** [comment]
Hey @strongduanmu development was done and it was approved. I just resolved conflicts. You can check this 
[PR](https://github.com/apache/shardingsphere/pull/21076) . @terrymanu please have a look and merge

**Comment by strongduanmu** [comment]
Since this task is not complete, I will move it to 5.2.2.
