### ISSUE TITLE
mybatisPlus selectCount RenException

### ISSUE THREAD

**Issue by Mrljt497** [apache/shardingsphere#20833]
For English only, other languages will not accept.

Before report a bug, make sure you have:

Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will close it.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
5.1.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
the SQL listed below should be parsed correctly

Actual behavior
Got SQLFeatureNotSupportedException

Reason analyze (If you can)
sql Incorrect format  mybatisPlus.selectCount  sql：select（ * ） There is a blank in the middle

Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
run the following SQL:
SELECT COUNT(  *  ) 
FROM CCM_COUPON_DEFINE

Got error
![mybatisPlus](https://user-images.githubusercontent.com/74707593/188622617-92434228-f2fa-4aca-9181-6a2af33b5f44.jpg)
:

**Comment by strongduanmu** [comment]
@Mrljt497 Can you submit issue according to bug template?

**Comment by Mrljt497** [comment]
OK, I have changed the content

**Comment by RaigorJiang** [comment]
Hi @Mrljt497 
Has this issue been resolved?
In addition, from the exception stack you provided, there is no information related to ShardingSphere

**Comment by RaigorJiang** [comment]
Closed due to no response.
