### ISSUE TITLE
Multi-threaded execute `JDBCRepository.init`method at the same time, may cause deadlock

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#20876]
## Bug Report

I use jdbc mode to create Sharding ShardingSphereDataSource, finally the `H2JDBCRepositoryProvider` will be used.
If multiple threads at about the same time execute `JDBCRepository.init`

related code
```
    @Override
    public void init(final Properties props) {
        JDBCRepositoryProperties jdbcRepositoryProps = new JDBCRepositoryProperties(props);
        hikariDataSource = new HikariDataSource();
        hikariDataSource.setJdbcUrl(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.JDBC_URL));
        hikariDataSource.setUsername(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.USERNAME));
        hikariDataSource.setPassword(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.PASSWORD));
        try (
                Connection connection = hikariDataSource.getConnection();
                Statement statement = connection.createStatement()) {
            provider = JDBCRepositoryProviderFactory.getInstance(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.PROVIDER));
            statement.execute(provider.dropTableSQL());
            statement.execute(provider.createTableSQL());
        }
    }
```

the `provider.dropTableSQL()` may cause deadlock exception, and failed to get data source

```
Caused by: org.h2.jdbc.JdbcSQLTransactionRollbackException: Deadlock detected. The current transaction was rolled back. Details: "\000aSession #2 (user: SA, RUNNING) on thread Thread-9 is waiting to lock PUBLIC.repository (exclusive) while locking PUBLIC.SYS (exclusive).\000aSession #3 (user: SA, RUNNING) on thread Thread-10 is waiting to lock PUBLIC.SYS (exclusive) while locking PUBLIC.repository (exclusive)."; SQL statement: DROP TABLE IF EXISTS `repository` [40001-214]
```

relation ci link:
> https://github.com/apache/shardingsphere/runs/8242175967?check_suite_focus=true
https://github.com/apache/shardingsphere/runs/8226074983?check_suite_focus=true

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Succeed to get data source

### Actual behavior

Exception thrown and failed to get data source

### Reason analyze (If you can)

http://www.h2database.com/html/advanced.html

drop table may get exclusive lock,  add jdbc param or add lock?
> I'm not sure, maybe there is a better way

**Comment by strongduanmu** [comment]
Hi @itmachen , could we finish this issue in 5.2.1?

**Comment by itmachen** [comment]
@strongduanmu recently completed

**Comment by itmachen** [comment]
@azexcy What scenario will be multi-threaded execution.

**Comment by azexcy** [comment]
> @azexcy What scenario will be multi-threaded execution.

relation class `ShardingSpherePipelineDataSourceCreator`
if  multiple  pipeline jobs are running at the same time, multiple threads will create the data source at the same time

**Comment by itmachen** [comment]
@azexcy I have optimized a version before, can you please accept it

**Comment by itmachen** [comment]
@azexcy Not sure it can be solved, so can you give me a reproduction process

**Comment by azexcy** [comment]
OK, i will check it later, thanks.

**Comment by strongduanmu** [comment]
Since this task is not complete, I will move it to 5.2.2.

**Comment by azexcy** [comment]
Since it has not undergone complete testing, I will move it to 5.3.1.

**Comment by azexcy** [comment]
I ran the case  several times locally, there are no deadlock occur at the moment

**Comment by azexcy** [comment]
I close it because it couldn't be reproduced
