### ISSUE TITLE
Failed to add database and table, dynamically refresh data source, instantiate scheme    <sharding-sphere.version>4.1.1</sharding-sphere.version>

### ISSUE THREAD

**Issue by liangxianjin** [apache/shardingsphere#20874]
## Question
The old connection cannot be closed when refreshing the data source, which will lead to the continuous increase of database connections
Because we have partially extended the current framework, the cost of version upgrade is relatively high. Let's see if dynamic addition and hot refresh of libraries and tables can be realized on the basis of the original version 4.1.1

**Comment by TeslaCN** [comment]
The version 4.1.1 has no longer maintained. You may have to do this on your own if you insist on using 4.1.1
