### ISSUE TITLE
Rename and move PipelineJobExecutor

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20885]
Part of #19421

The responsibility of PipelineJobExecutor is watching pipeline meta data in registry center, and then dispatch events to handlers.

Possible changes:
- Rename PipelineJobExecutor to PipelineMetaDataNodeWatcher; Update class and method javadoc;
- Move PipelineMetaDataNodeWatcher to package `org.apache.shardingsphere.data.pipeline.core.metadata.node`, the same as `PipelineMetaDataNode`

**Comment by sandynz** [comment]
Hi @huangdx0726 , are you interesting to resolve it?

**Comment by huangdx0726** [comment]
yes, assign to me

**Comment by sandynz** [comment]
> yes, assign to me

Thanks, just assigned it to you.
