### ISSUE TITLE
show processlist shows sleep connections

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#20896]
## Feature Request

SS currently show processlist can only display the connection in execution, but not the connection in the sleep. I hope to be able to display all the same as MySQL, if I need to filter the sleep, can use the following command.

```
pager grep -v sleep;show processlist;
```

**Comment by strongduanmu** [comment]
@natehuangting Good suggestion, but the current process of show processlist cannot support this feature. Are you willing to design a solution?
