### ISSUE TITLE
Column index out of range

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#20903]
## Question
sharding-jdbc version 5.1.2
sql:select * from (select name,age from  order)

exception:
Column index out of range.; nested exception is java.sql.SQLException: Column index out of range.

**Comment by linghengqian** [comment]
It is better that you modify the issue description as the issue template.  No one else can guess the specific information you are deliberately withholding.

**Comment by chenws1012** [comment]
I see that 5.0.0 has been fixed, why is there a similar exception in 5.2.1
<img width="933" alt="image" src="https://user-images.githubusercontent.com/17613152/207261745-5b17d429-92e5-41ec-add9-aa1ab0b1afd4.png">

**Comment by linghengqian** [comment]
@chenws1012 Since these are essentially two issues, you can bring a minimal reproducible example and open a new issue. The problem with subqueries involved a module that didn't exist at 5.0.0.
