### ISSUE TITLE
Confusion about the positioning of ShardingRuleConfiguration

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20912]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**

- I took a look at https://shardingsphere.apache.org/document/5.2.0/en/dev-manual/configuration/ and got some confusion.

- `AlgorithmShardingRuleConfiguration` is `Used to convert algorithm-based sharding user configuration into sharding rule objects`, `ShardingRuleConfiguration` is `Used to convert sharding user configuration into sharding rule objects`, is there any difference in semantics?  

- I am a little surprised that the two classes are not in a parent-subclass relationship.  Because I noticed that from ShardingSphere `5.1.2` to `5.2.0`, most of `AlgorithmShardingRuleConfiguration` was replaced by `ShardingRuleConfiguration`, which is reflected in the design of `org.apache.shardingsphere.mode.manager.ContextManager`.

**Comment by strongduanmu** [comment]
Hi @linghengqian, `AlgorithmShardingRuleConfiguration` should refer to `AlgorithmProvidedShardingRuleConfiguration`, the documentation should be wrong. It is mainly suitable for Spring scenarios, Spring will help us complete the initialization of algorithm objects, and `ShardingRuleConfiguration` is suitable for non-Spring environments.

I also find it confusing to have two similar classes, are you interested in trying to merge them?

**Comment by linghengqian** [comment]
@strongduanmu 
- I'm stumped because some of my local attempts are affected by the strange behavior of `org.apache.shardingsphere.mode.manager.ContextManager#alterRuleConfiguration`. The strange behavior I'm referring to ends up being something like https://github.com/apache/shardingsphere/issues/20952. 

- I'd like to have other friends to try the work of merge the two classes.

**Comment by strongduanmu** [comment]
> * I'm stumped because some of my local attempts are affected by the strange behavior of `org.apache.shardingsphere.mode.manager.ContextManager#alterRuleConfiguration`. The strange behavior I'm referring to ends up being something like [NPE " Cannot invoke "org.apache.shardingsphere.infra.metadata.database.schema.decorator.model.ShardingSphereSchema.getVisibleColumnNames(String)" because the return value of "java.util.Map.get(Object)" is null" #20952](https://github.com/apache/shardingsphere/issues/20952).

@linghengqian This exception may be caused by wrong metadata, we will investigate it later.

**Comment by linghengqian** [comment]
- I will try to verify after https://github.com/apache/shardingsphere/pull/21037 is merged.
