### ISSUE TITLE
Confusion about using DistSQL in databases other than MySQL/PostgreSQL

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20914]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**

- I noticed that in ShardingSphere `5.2.0`, the database dialect support for databases such as `SQL Server` and `Oracle` has been relatively complete.  But for ShardingSphere Proxy, its documentation still uses the statement that it only supports `MySQL/PostgreSQL`, refer to https://shardingsphere.apache.org/document/5.2.0/en/overview/deployment/ .

- Considering that DistSQL only works with ShardingSphere Proxy, I assume the following scenario.  There is already a ShardingSphere Proxy instance without any logical database configuration, add a SQL Server instance through DistSQL, and then use an Java applications with `ShardingSphere JDBC and SQL Server` to synchronize the Zookeeper configuration in another place.  

- Does this process require the SQL Server JDBC driver to exist in the `ext-lib` folder of the `ShardingSphere Proxy` instance?  Or is DistSQL also affected by the limitations of `MySQL/PostgreSQL`?

- I'm not quite sure how many limitations would be involved in a process like https://medium.com/codex/how-to-develop-your-distributed-sql-statement-in-apache-shardingsphere-2939eb689c61 just by simply executing DistSQL.

**Comment by RaigorJiang** [comment]
In fact, the execution of DistSQL is not limited by the backend DB type.
DistSQL is mainly used to manage the config & metadata of ShardingSphere, including resources and rules in the logic database.

If Proxy supports more database types in the future, it will have little effect on DistSQL.

**Comment by linghengqian** [comment]
> In fact, the execution of DistSQL is not limited by the backend DB type. DistSQL is mainly used to manage the config & metadata of ShardingSphere, including resources and rules in the logic database.
> 
> If Proxy supports more database types in the future, it will have little effect on DistSQL.

Thanks for your answer.
