### ISSUE TITLE
sql-federation-type lacks more specific documentation

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20913]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- I noticed that at https://shardingsphere.apache.org/document/current/en/user-manual/common-config/props/ , for the master branch, `sql-federation-enabled` was refactored to `sql-federation-type`, which allows `NONE`, `ORIGINAL`, `ADVANCED` three values.  

- But I didn't see the introduction of the difference between `NONE`, `ORIGINAL`, `ADVANCED`, is this lack of corresponding documentation?  Or am I overlooking something?

**Comment by strongduanmu** [comment]
SQL Federation is still under development, and the documentation will be supplemented after the feature is basically completed. `sql-federation-type` is also a temporary configuration. It will be enabled in ADVANCED mode by default when the feature is finished in the future.

**Comment by linghengqian** [comment]
Thanks for your answer.
