### ISSUE TITLE
Question about persist metadata node when use ShardingSphere-JDBC cluster mode

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20915]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- I noticed issues like https://github.com/apache/shardingsphere/issues/19713 and related PRs mentioned that some configurations do not persist metadata node when use ShardingSphere-JDBC cluster mode.  

- This actually brings me some confusion, is it only the `sql-parser` module that will not persist metadata node when use ShardingSphere-JDBC cluster mode?  Considering the properties mentioned in https://shardingsphere.apache.org/document/current/en/user-manual/common-config/props/ , will properties like `sql-federation-type` persist metadata node when  use ShardingSphere-JDBC cluster mode?  

- I noticed that the documentation doesn't specifically say what properties do not save metadata to zookeeper/etcd in a hybrid deployment.

**Comment by zhaojinchao95** [comment]
Hi, `sql-parser` are global rule, it not belong to `/metadata/db/verisons/0/rules`

**Comment by linghengqian** [comment]
wow I misunderstood the information of that issue.
