### ISSUE TITLE
Discuss the time to increase the minimum JDK compilation version of the ShardingSphere project to 11

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#20935]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Yes, refer to https://github.com/apache/shardingsphere/pull/20008 and https://github.com/apache/shardingsphere/pull/20119 .

### Describe the feature you would like.

- Starting from Antlr `4.10`, it requires users to have a minimum JDK version of 11. Refer to https://github.com/antlr/antlr4/releases/tag/4.10.1 .
- And for Hibernate which relies on Antlr, it uses Antlr `4.10` from Hibernate `6.0.1`, Hibernate `6.1.x` works on SpringBoot OSS `3.0.0-M4`, for ShardingSphere JDBC `5.2.0` which uses Antlr `4.9.2`, this breaks ShardingSphere JDBC Use of hybrid deployment form with zookeeper/etcd.

- I think it's time to consider the point in time when the minimum compiled version of ShardingSphere is raised to JDK11. I think this event should appear later than November 2022, when SpringBoot OSS `3.0.0` releases the first Release version. For the master branch of ShardingSphere, in which version should it raise the minimum build version? Is it ShardingSphere `5.3.0` or ShardingSphere `6.0.0`?

- Refer to https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M4-Release-Notes#hibernate-61 .

**Comment by linghengqian** [comment]
- I'm reopening this issue because no one has responded to the time point, and I'll submit a PR directly if it's ok.

**Comment by TeslaCN** [comment]
> * I'm reopening this issue because no one has responded to the time point, and I'll submit a PR directly if it's ok.

This may impact a lot of users. It's better to discuss breaking changes in mailing list.

**Comment by linghengqian** [comment]
- Considering the process at https://github.com/apache/shardingsphere/issues/1157, maybe it would be better for PMC to start a new email thread?  👀

**Comment by zhfeng** [comment]
Vote on github issue? Is it an official process? I think it should happen on the mailing list although it seems few peope take care of it.

**Comment by linghengqian** [comment]
- @zhfeng The official voting procedure should be transferred to the maillist, this issue should not be responsible for any related voting from the process, and I am not a Committer. 

- The reason I didn't turn on the maillist was simply because it wasn't my need, which was @shanrenxj's need in the first place.

**Comment by zhfeng** [comment]
@linghengqian I'm not a Committer either. But it is free to ask a voting on the community, the PMC has a binding `+1` and anyone can show  his/her opinion.

**Comment by zhfeng** [comment]
Hi @terrymanu @linghengqian @TeslaCN @taojintianxia @shanrenxj,

I raise a thread [Plan to drop JDK 8](https://lists.apache.org/thread/kgtfx5vnw73o61lkvdshyfvjfvvzk3js) on the mailing list, and please review and discuss there. I'm open to any idea.

Thanks!

**Comment by shanrenxj** [comment]
It's time to give those programmers who refuse to embrace new things a head start. Let them stay in the old shardingsphere.

**Comment by zhfeng** [comment]
Hi @shanrenxj,

We are not pushing people but trying to figure it out. Currently I'm working with @linghengqian to resolve the `antlr4` upgrading issue by not breaking the `JDK 8` support.

The most thing is like

- We need to change to build `shardingsphere ` with JDK > 11 only.
- But it is still compatitable with JDK 1.8 which the people should be good at runtime.

**Comment by linghengqian** [comment]
- I'm afraid I haven't had the energy to explore the corresponding PR for https://github.com/antlr/antlr4/issues/2448 . The release cycle of Antlr4 seems to be extremely long, and I'm not sure how to deal with something like `antlr.skip` in the end. I've recently been exploring Runtime Reflection issues surrounding GraalVM with byte-buddy.

**Comment by zhfeng** [comment]
No, it should be OK without this skip propery with antlr4. I'm trying to prepare a PR to `force build shardingsphere with JDK 11`. @linghengqian please go head with your current works on GraalVM. I'm looking forward the `shardingsphere-native-proxy` which will be awsome.

**Comment by zhfeng** [comment]
Please review https://github.com/apache/shardingsphere/pull/23550

**Comment by linghengqian** [comment]
- Resolved by https://github.com/apache/shardingsphere/pull/23550. Antlr4 has nothing to do with this issue.
