### ISSUE TITLE
ProxyClusterContainerConfigurationFactory not get cluster server.yaml configuration

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#20932]
I found not persist metadata to governance center when i run integration test case with cluster mode. And i see `ProxyClusterContainerConfigurationFactory.class` get `server.yaml` configuration are not right. when i adjustment path to `/env/common/cluster/proxy/conf/`, there are many integration test case are run failed.  

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/33742097/189538651-3adf3f66-7c46-4aca-b2e5-545aa97b08c2.png">

Relate pull request #20103

### Which version of ShardingSphere did you use?

`master` https://github.com/apache/shardingsphere/commit/f7e511be1b976124e327a3a0f93315552b08d895

### Which project did you use? 

`shardingsphere-test`

### Expected behavior

`shardingsphere-integration-test-suite` test case can run really in cluster mode.

### Actual behavior

<img width="737" alt="image" src="https://user-images.githubusercontent.com/33742097/189538222-daaf3be1-b1fc-4da9-b6a5-dbaa47630e72.png">

### Reason analyze (If you can)

```
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class ProxyClusterContainerConfigurationFactory {
    
    /**
     * Create instance of adaptor container configuration.
     * 
     * @param scenario scenario
     * @param databaseType database type
     * @return created instance
     */
    public static AdaptorContainerConfiguration newInstance(final String scenario, final DatabaseType databaseType) {
        return new AdaptorContainerConfiguration(scenario, getMountedResources(scenario, databaseType));
    }
    
    private static Map<String, String> getMountedResources(final String scenario, final DatabaseType databaseType) {
        Map<String, String> result = new HashMap<>(2, 1);
        String pathInContainer = "/opt/shardingsphere-proxy/conf";
        result.put("/env/common/standalone/proxy/conf/", pathInContainer);
        result.put("/env/scenario/" + scenario + "/proxy/conf/" + databaseType.getType().toLowerCase(), pathInContainer);
        return result;
    }
}
```

`/env/common/standalone/proxy/conf/` should be change to `/env/common/cluster/proxy/conf/`

**Comment by zhaojinchao95** [comment]
The `ddl-integration-test-cases.xml` still has two error case, Can you look this? @soulasuna . Please search `<!-- TODO Fix me -->`

**Comment by strongduanmu** [comment]
Hi @zhaojinchao95 @soulasuna , could we finish this issue in 5.2.1?
