### ISSUE TITLE
about Read write separation

### ISSUE THREAD

**Issue by strongyc** [apache/shardingsphere#20950]
## Question
If fragmentation key and read-write separation are configured, can the slave library be used for query? 
**For English only**, other languages will not accept.
```
spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes=ds1.user_${0..3}
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-algorithm-name=user_inline
spring.shardingsphere.rules.sharding.tables.user.table-strategy.standard.sharding-column=id
#spring.shardingsphere.rules.sharding.sharding-algorithms.user_inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user_inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user_inline.props.algorithm-expression=user_$->{id % 4}
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.user.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE

spring.shardingsphere.rules.readwrite-splitting.data-sources.read_write_db.type=Static 
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.static-strategy.write-data-source-name=ds1
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.static-strategy.read-data-source-names= ds2
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.load-balancer-name= rids
spring.shardingsphere.rules.readwrite-splitting.load-balancers.rids.type=ROUND_ROBIN
````
DS1 is still used for query
Before asking a question, make sure you have:

**Comment by strongyc** [comment]
How to configure read-write separation for fragmentation key？

**Comment by zhaojinchao95** [comment]
@strongyc Hi, you can refer to this : https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/mixed-feature-example/sharding-readwrite-splitting-example/sharding-readwrite-splitting-spring-boot-mybatis-example/src/main/resources/application-sharding-readwrite-splitting.properties

**Comment by strongyc** [comment]
> @strongyc Hi, you can refer to this : https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/mixed-feature-example/sharding-readwrite-splitting-example/sharding-readwrite-splitting-spring-boot-mybatis-example/src/main/resources/application-sharding-readwrite-splitting.properties

get,thinks
