### ISSUE TITLE
How to implement sharding algorithm in version 5.2.0

### ISSUE THREAD

**Issue by 726411951** [apache/shardingsphere#20951]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

For our business, I implement sharding algorithm by using Java code,and the version is 5.1.1,the class is 
![image](https://user-images.githubusercontent.com/32379580/189801857-7fab8872-0be8-47b4-a5c0-ffea596a1a66.png)

But when I update version to 5.2.0, This project can not run and the error is `[org/apache/shardingsphere/spring/boot/ShardingSphereAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingSphereDataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Type is required.`

I dont konw how to work it by changing my code , or may be can use this property [Class Based Sharding Algorithm
](https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/sharding/#class-based-sharding-algorithm) instands of the code. I'm not sure, thanks for your answer

**Comment by strongduanmu** [comment]
@726411951 Thank you for your feedback. Can you provide your sharding configuration?

**Comment by 726411951** [comment]
@strongduanmu  almost like 
```
spring.shardingsphere.datasource.names=ds0,ds1

spring.shardingsphere.datasource.ds0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.jdbc-url=jdbc:mysql://192.168.0.1:3306/oms_base0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds0.username=root
spring.shardingsphere.datasource.ds0.password=xxx

spring.shardingsphere.datasource.ds1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds1.jdbc-url=jdbc:mysql://192.168.0.1:3306/oms_base1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds1.username=root
spring.shardingsphere.datasource.ds1.password=xxx

spring.shardingsphere.rules.sharding.tables.oms_biz_order.database-strategy.standard.sharding-column=merchant_id
spring.shardingsphere.rules.sharding.tables.oms_biz_order.database-strategy.standard.sharding-algorithm-name=shardingAlgorithmConfig

spring.shardingsphere.rules.sharding.tables.oms_detail.database-strategy.standard.sharding-column=merchant_id
spring.shardingsphere.rules.sharding.tables.oms_detail.database-strategy.standard.sharding-algorithm-name=shardingAlgorithmConfig
```

**Comment by Ryoui** [comment]
@726411951 请问解决了吗

**Comment by 726411951** [comment]
@Ryoui not yet

**Comment by linghengqian** [comment]
- Can you make a minimal reproducible example using h2database?  The configuration you gave is not complete, I tried to verify it locally and it was successful.

**Comment by 726411951** [comment]
@linghengqian Hi, this is the demo and run successfully on version 5.1.1
[demo](https://github.com/726411951/sharding-database-demo)

**Comment by linghengqian** [comment]
@726411951 
- I found out that this is nothing but your configuration issue. Your configuration is very confusing. 🤷‍♂️
- Refer to https://github.com/linghengqian/sharding-database-demo/commit/ae37f388bda6a282623f1b3aedc19d8b7446ed1c.

**Comment by 726411951** [comment]
@linghengqian So cooooool ! It's very helpful to me :satisfied: I
