### ISSUE TITLE
Completing RDL-Sharding-related documentation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#20969]
We are currently refactoring the documentation related to DistSQL, and we need the community's help to improve the following statements together.
- [ ] `ALTER SHARDING TABLE RULE`
- [ ] `DROP SHARDING TABLE RULE `
- [ ] `ALTER DEFAULT SHARDING STRATEGY`
- [ ] `DROP DEFAULT SHARDING STRATEGY`
- [ ]  `ALTER SHARDING ALGORITHM`
- [ ]  `DROP SHARDING ALGORITHM`
- [ ]  `ALTER SHARDING KEY GENERATOR`
- [ ]  `DROP SHARDING KEY GENERATOR`

You can refer to the syntax from the [existing documentation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/).

You need to add documentation to the [sharding directory](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/sharding/).

You can also refer to the relevant Issue：#16666  #19898

**Comment by RaigorJiang** [comment]
It has been completed, the latest document address:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/alter-sharding-table-rule/
