### ISSUE TITLE
Unable to use distributed transactions in the scenario of data encryption

### ISSUE THREAD

**Issue by hf185** [apache/shardingsphere#20971]
## Bug Report

The distributed transaction fails when only the data encryption scheme is used,

I found ` ShardingTransactionManagerEngine` only in `shardingDataSource()`  is executed will be created, under the scheme of data encryption, and implemented the function is `encryptDataSource()` 

![c714febcce2ea8b288803cbf31adb054](https://user-images.githubusercontent.com/43991218/190102838-886ae778-fbfc-4a64-b668-ea9ae04fac29.png)
![2](https://user-images.githubusercontent.com/43991218/190103609-741f9beb-2f95-4de9-92a2-fba8c712d610.png)
![3](https://user-images.githubusercontent.com/43991218/190103608-1c20d6ca-13ac-47b0-9842-3cea0b6240ef.png)
![4](https://user-images.githubusercontent.com/43991218/190103627-fe365397-37e1-4c7d-bab8-db80f2c764c9.png)

### Which version of ShardingSphere did you use?

4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### ShardingSphere configuration

![9b523c44f522434e23d4fff4072251fd](https://user-images.githubusercontent.com/43991218/190102598-c0324a0a-5dac-414e-9748-73a065d69506.png)

> Only encryption is used

### expected outcome

Use distributed transactions normally

**Comment by FlyingZC** [comment]
Hi,can you try the latest version, 4.x version is no longer maintained.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
