### ISSUE TITLE
Completing RDL-SingleTable-related documentation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#20989]
We are currently refactoring the documentation related to DistSQL, and we need the community's help to improve the following statements together.
- [x] `ALTER DEFAULT SINGLE TABLE RULE`
- [x] `DROP DEFAULT SINGLE TABLE RULE`

You can refer to the syntax from the [existing documentation](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/single-table/).

You need to add documentation to the [singleTable directory](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/).

You can also refer to the relevant Issue：#16666  #19898

**Comment by tianhao960** [comment]
hi, @JiekerTime , I'd like to try this.
