### ISSUE TITLE
mybatisPlus selectCount RenException

### ISSUE THREAD

**Issue by Mrljt497** [apache/shardingsphere#20999]
For English only, other languages will not accept.

Before report a bug, make sure you have:

Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will close it.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
5.1.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
the SQL listed below should be parsed correctly

Actual behavior
Got SQLFeatureNotSupportedException

Reason analyze (If you can)
sql Incorrect format mybatisPlus.selectCount sql：select（ * ） There is a blank in the middle

Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
run the following SQL:
SELECT COUNT( * )
FROM CCM_COUPON_DEFINE

Got error
mybatisPlus
![mybatis](https://user-images.githubusercontent.com/74707593/190345244-c932dcf6-4239-4a45-9acc-5f1e9a01b87f.jpg)

**Comment by linghengqian** [comment]
- You need to give a minimal reproducible example.  I have not tested such a problem locally.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
