### ISSUE TITLE
When using ShardingSphere-Proxy, after replacing the config-sharding.yaml configuration file with DistSQL, some SQL statements report an error

### ISSUE THREAD

**Issue by Gangplank0** [apache/shardingsphere#21017]
Add Resource and create sharding rules with DistSQL, but no sharding table was created, because the sharding table was already created when using the config-sharding.yaml configuration file.
When using SELECT COUNT(*), an error is reported.
**"Unknown exception: Cannot invoke "org.apache.shardingsphere.infra.metadata.database.schema.decorator.model.ShardingSphereTable.getColumns()" because "table" is null".**
Before using source code installation of ShardingSphere-Proxy, now using Helm installation of ShardingSphere-Proxy.
How to solve this problem please?

**Comment by zhaojinchao95** [comment]
@Gangplank0 Hi, which proxy version?

**Comment by Gangplank0** [comment]
5.2.0

**Comment by zhaojinchao95** [comment]
Execute Refresh table metadata after when you create &nbsp;sharding table rule. Please try it again

------------------ Original ------------------
From: Socialist ***@***.***&gt;
Date: Sat,Sep 17,2022 9:30 AM
To: apache/shardingsphere ***@***.***&gt;
Cc: zhaojinchao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [apache/shardingsphere] When using ShardingSphere-Proxy, afterreplacing the config-sharding.yaml configuration file with DistSQL, some SQLstatements report an error (Issue #21017)





 
5.2.0

**Comment by Gangplank0** [comment]
it works.Thank you very much!

**Comment by zhaojinchao95** [comment]
Ok! Actually, `Refresh table metadata` command is redundant and will not need to be executed in the next version

**Comment by Gangplank0** [comment]
Ok! looking forward to the new release
