### ISSUE TITLE
Add more unit test for BootstrapArguments

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#21016]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

### Aim
Add more unit tests for `BootstrapArguments` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

### Basic Qualifications
Java
Maven
Junit

**Comment by abhinav-koppula** [comment]
@FlyingZC - I have created a PR - https://github.com/apache/shardingsphere/pull/21308. 
Can you please review?
