### ISSUE TITLE
Add more unit test for DataSourceStateManager

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#21014]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/28487.

### Aim
Add more unit tests for DataSourceStateManager to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

### Basic Qualifications
Java
Maven
Junit

**Comment by li3317** [comment]
Hello! May I try this issue?

**Comment by terrymanu** [comment]
Sure, I just assign to you

**Comment by Manas-33** [comment]
Hey, I would like to work on this
