### ISSUE TITLE
Wiki updation

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#21011]
Some of the links in Wiki are not working - for example [Get Involved resource](https://shardingsphere.apache.org/community/en/contribute/), and etc.

PS: Found this through an OSD'22 participant. Link to [thread](https://gracehopperosd.slack.com/archives/C03U8UB2N03/p1663303308306069?thread_ts=1663298222.183499&cid=C03U8UB2N03)

**Comment by ayushis380** [comment]
Hi @Swastyy, I think the above link in Wiki is working now. [Get Involved resource](https://shardingsphere.apache.org/community/en/involved/contribute/). I tried opening it, and it doesn't give any errors.

**Comment by Swastyy** [comment]
yeah @ayushis380 just checked now. Thanks to @RaigorJiang for fixing them.

**Comment by Swastyy** [comment]
reopening for other pages links like https://github.com/apache/shardingsphere/wiki/How-to-Set-Up-Your-Dev-Environment

**Comment by TeslaCN** [comment]
> reopening for other pages links like https://github.com/apache/shardingsphere/wiki/How-to-Set-Up-Your-Dev-Environment

Thanks. I've fix the links in https://github.com/apache/shardingsphere/wiki/How-to-Set-Up-Your-Dev-Environment
