### ISSUE TITLE
Unknown exception occurred when drop index 

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21010]
### Which version of ShardingSphere did you use?

`5.2.0`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/33742097/190550331-36598518-af60-4ff9-8be3-a96a4eef8d69.png">

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin , could we finish this issue in 5.2.1?

**Comment by strongduanmu** [comment]
Besides, I think we should provide more information according to bug template. @zhaojinchao95

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin @zhaojinchao95 
Please confirm the milestone of this issue.

**Comment by zhaojinchao95** [comment]
Move to 5.3.1 milestone.

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , does it still not work on latest version?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , does it still not work on latest version?

Next version, thx

**Comment by zhaojinchao95** [comment]
The problem is not reproduced, i close it
