### ISSUE TITLE
About start.sh, I can't start Proxy designated port with pleasure ？

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#21018]
### Which version of ShardingSphere did you use?
91d2d46cf9ea4d139478c2c9c6de8734ade7d4a1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
start proxy with port 4444 and ignore unavailable DataSource
### Actual behavior
start failed
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/86462784/190602955-5a070b61-97ba-4fc1-8132-e02ee3f65b89.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
start.sh 4444 -f or start.sh -f 4444

**Comment by FlyingZC** [comment]
I want to investigate the issue. @strongduanmu

**Comment by FlyingZC** [comment]
Maybe mixing the -xxx parameter with and without the -xxx parameter was not supported before.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/19788130/190940367-68093f8f-b405-4e00-997a-911fb2573fc5.png">
