### ISSUE TITLE
Add more unit test for YamlSQLParserRuleConfigurationSwapper

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#21020]
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

### Aim
Add more unit tests for `YamlSQLParserRuleConfigurationSwapper` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

### Basic Qualifications
Java
Maven
Junit

**Comment by abhinav-koppula** [comment]
@strongduanmu / @FlyingZC - Is this issue duplicate of #20400 ?

**Comment by strongduanmu** [comment]
Yes, this issue is duplicated with #20400, I will close this issue.
