### ISSUE TITLE
Remove invalid proxy props from documentation.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21024]
Hi community,

This issue is for #20305.

### Background

In ShardingSphere-Proxy, the following  props have been removed, now we need to remove these instructions from the [documentation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/yaml-config/props/).

- proxy-opentracing-enabled

- check-duplicate-table-enabled

### Aim

Remove `proxy-opentracing-enabled` and `check-duplicate-table-enabled` from documentation.

They are in the following files:

- docs/document/content/user-manual/shardingsphere-proxy/yaml-config/props.cn.md
- docs/document/content/user-manual/shardingsphere-proxy/yaml-config/props.en.md

### How to

1. Remove the lines where `proxy-opentracing-enabled` and `check-duplicate-table-enabled` are, from the above files.
2. Submit a PR (pull request) and wait for review.
3. Documentation will be automatically updated after the PR is merged.

### Basic Qualifications

- Git

### Guide
Please follow this guide to set up your environment: https://shardingsphere.apache.org/community/en/involved/contribute/dev-env/

And then, start the contribute flow: 
https://shardingsphere.apache.org/community/en/involved/contribute/contributor/

**Comment by aishwaryasharmaccoew** [comment]
Hello, I think this would be a good issue for me to start contributing.
Could you please assign it to me

**Comment by ayushis380** [comment]
Hi Community,
I want to pick this issue. I am doing this for the first time and want to start with an easy one.

**Comment by RaigorJiang** [comment]
Hi @ayushis380 
Sorry, I just assigned the issue to @aishwaryasharmaccoew  because she made the request first, thank you!

**Comment by Swastyy** [comment]
And @ayushis380 , you can comment on other good first issues.
