### ISSUE TITLE
shardingsphere5.2 cannot use druid with Password encryption

### ISSUE THREAD

**Issue by linruzhou** [apache/shardingsphere#21032]
The following configuration can be used in shardingsphere5.1.1, but it is error to use in shardingsphere5.2

spring:
  shardingsphere:
    datasource:
      names: testss
      testss:
        type: com.alibaba.druid.pool.DruidDataSource
        name: testss
        username: testdb
        password: WJFBeNnNARnNnN0QHlaysEkRuoZrT2H+4bWuOyH7VHkXsdZkg5JgIdjonoNk2UaL7zleLKEkUv8HUbV280tAlw==
        url: jdbc:mysql://xxxx/testdb?characterEncoding=UTF-8
        driverClassName: com.mysql.cj.jdbc.Driver
        filter:
          config:
            enable: true
        filters: config
        connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI5W+KCEDSKlEZye8ZTAcg20gsFnV4qvTc4E8tvtUmTx3XhiAijlPrt2GFtXgPmHLGpyULPrbwD2rCjeuDjqvOcCAwEAAQ==
        initialSize: 20
        maxActive: 30
        minIdle: 10
        maxWait: 1000
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: -1
        validationQuery: select 1
        testOnBorrow: true
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000

exception:

Caused by: java.lang.IllegalArgumentException: Class is not accepted: com.alibaba.druid.filter.config.ConfigFilter
	at org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor.getClassForName(ShardingSphereYamlConstructor.java:55)
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:662)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:322)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)

note: When I use the password directly , that is, when the config filter is not configured, it can be used normally.

**Comment by linghengqian** [comment]
- I suggest you use double **```** to format the markdown part of your issue, your description is too difficult to understand.
- This is obviously because `org.apache.shardingsphere.infra.util.yaml.constructor.ShardingSphereYamlConstructor` did not take into account the unique use case of `Alibaba Druid`, which uses Class to save configuration, and the unit test currently only includes `HikariCP`, `DBCP`, `C3P0`. 
- Would it be convenient for you to submit a PR to try to be compatible with this treatment?

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
