### ISSUE TITLE
Update snakeyaml to 1.31 or 1.32 to fix unit tests

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#21043]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Yes, refer to https://github.com/apache/shardingsphere/pull/15260 .

### Describe the feature you would like.

- At https://github.com/apache/shardingsphere/pull/15260, the yaml 1.1 deserialization bug introduced since snakeyaml 1.19 was discovered for the first time.  This issue was reported at https://bitbucket.org/snakeyaml/snakeyaml/issues/387/support-for-generic-types-when-serializing and fixed in Snakeyaml 1.31.  Although the corresponding unit tests have been changed directly, raising to a higher version will still help explain some unreasonable yaml deserialization errors.

**Comment by linghengqian** [comment]
I am working on this issue.

**Comment by pjfanning** [comment]
1.32 has security fixes (as does 1.31) - so it is good to upgrade anyway.
* https://github.com/advisories/GHSA-9w3m-gqgf-c4p9
* https://github.com/advisories/GHSA-c4r9-r8fh-9vj2
