### ISSUE TITLE
No error exception when drop all sharding broadcast table rules with no sharding broadcast table rule in database

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#21058]
### Which version of ShardingSphere did you use?
master 9c83948cdb49af429851eb2eca9ce10da9dfb7a7
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Error exception by sharding broadcast table rules unexist
### Actual behavior
Drop sharding broadcast table rules successfully 
### Screenshot
![171663567311_ pic](https://user-images.githubusercontent.com/57847965/190957704-61b96d6f-eb97-4505-8c36-2e1444b6eb72.jpg)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. show show sharding broadcast table rules to make sure no sharding broadcast table rule exist 
```
SHOW SHARDING BROADCAST TABLE RULES;
```
2. drop all sharding broadcast table rules
```
DROP SHARDING BROADCAST TABLE RULES;
```

**Comment by RaigorJiang** [comment]
@rahulbiswas876 Welcome!

**Comment by RaigorJiang** [comment]
`DROP SHARDING BROADCAST TABLE RULES;` has been removed, so I close this issue.
