### ISSUE TITLE
Cause: java.lang.IllegalStateException: All tables must be in the same datasource

### ISSUE THREAD

**Issue by Mrljt497** [apache/shardingsphere#21062]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Run SQL normally and return the results

### Actual behavior
Runtime exception

### Reason analyze (If you can)
Cause: java.lang.IllegalStateException: All tables must be in the same datasource.
Read/write separation, primary table reads primary database, and associated table reads secondary database

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sql：
SELECT
	ORM.* 
FROM
	PSO_ORDER_MST ORM
	LEFT JOIN CAM_ACCOUNT_CARD_DTL ACD ON ORM.CARD_UUID = ACD.UUID

config：
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            type: STATIC
            props:
              auto-aware-data-source-name: write
              load-balancer-name: RANDOM
              write-data-source-name: db0
              read-data-source-names: db1
      sharding:
        sharding-algorithms:
          order-date-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: cn.com.beautyfarm.sharding.TableDateShardingAlgorithm
        tables:
          PSO_ORDER_MST:
            actual-data-nodes: db0.PSO_ORDER_MST,db0.PSO_ORDER_MST_$->{2015..2022}
            table-strategy:
              standard:
                sharding-column: CREATE_DATE
                sharding-algorithm-name: order-date-inline

**Comment by terrymanu** [comment]
The feature  is improved, could test the latest version?
