### ISSUE TITLE
No error exception when Alter unexist sharding binding table rule

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#21061]
### Which version of ShardingSphere did you use?
master 9c83948cdb49af429851eb2eca9ce10da9dfb7a7
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
error exception by sharding binding table rule do not exist.
### Actual behavior
Alter sharding binding table rule successful and create a sharding binding table rule

### Screenshot
![181663570696_ pic](https://user-images.githubusercontent.com/57847965/190964507-1cae1c08-b58e-424a-98be-8b11ce15b950.jpg)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Create sharding table rules : t_order, t_order_item, t_1, t_2.

2. Show sharding binding table rules to make sure no sharding binding table rules exist .
```
SHOW SHARDING BINDING TABLE RULES;
```
3. Alter sharding binding table rule. 
```
ALTER SHARDING BINDING TABLE RULES (t_order,t_order_item),(t_1,t_2);
```
4. Show sharding binding table rules to verify sharding binding table rule had been created.
```
SHOW SHARDING BINDING TABLE RULES;
```

**Comment by RaigorJiang** [comment]
Hi @Qianyi951015,Thanks for your feedback!

**Comment by yx9o** [comment]
I want to investigate.

**Comment by yx9o** [comment]
@Qianyi951015 Can you provide the statement for creating a sharding rule? thanks

**Comment by Qianyi951015** [comment]
@yx9o  Hi here is an example for creating a sharding table rule
```
CREATE SHARDING TABLE RULE t_order_item (
DATANODES("resource_${0..1}.t_order_item_${0..1}"),
DATABASE_STRATEGY(TYPE="standard",SHARDING_COLUMN=user_id,SHARDING_ALGORITHM(TYPE(NAME="inline",PROPERTIES("algorithm-expression"="resource_${user_id % 2}")))),
TABLE_STRATEGY(TYPE="standard",SHARDING_COLUMN=order_id,SHARDING_ALGORITHM=table_inline),
KEY_GENERATE_STRATEGY(COLUMN=another_id,KEY_GENERATOR=snowflake_key_generator)
);
```

**Comment by Qianyi951015** [comment]
@yx9o May be you also need key generator for creating the sharding table rule
```
CREATE SHARDING KEY GENERATOR snowflake_key_generator(TYPE(NAME="SNOWFLAKE"));
```
