### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by longfangwei** [apache/shardingsphere#21074]
shardingsphere5.1.1,druid 1.2.8  

If rules key is added, the project startup will report Caused by: java. lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required. If rules key is not added, the user-defined table splitting policy will not be followed

**Comment by linghengqian** [comment]
- You must provide a minimal reproducible example and provide reproducible steps based on the issue template. ShardingSphere does not use `sqlSessionFactory` or `sqlSessionTemplate`.

**Comment by longfangwei** [comment]
ok

**Comment by fakerme** [comment]
这个配置要加上 我是原来用的dynamic 改为shardingsphere 然后报错，加上这个就没毛病了
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
version 改为你自己的 mysql version

**Comment by longfangwei** [comment]
这个不是mysql驱动吗？
![image](https://user-images.githubusercontent.com/52698019/192674061-dfa42b7f-cf35-4ce8-874a-a36548bdc7b5.png)
我这里也是有的，现在觉得是多数据源与shardingsphere兼容的问题

**Comment by linghengqian** [comment]
@fakerme 

- If you plan to discuss, you should open a new issue with enough information.  I don't know what `多数据源` you are referring to.
