### ISSUE TITLE
shardingsphere5.1.1 因为rules启动导致Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by longfangwei** [apache/shardingsphere#21081]
### Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
</dependency>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Database sub database and table sub database and table sub database and table sub table succeeded through user-defined algorithm strategy
### Actual behavior
![image](https://user-images.githubusercontent.com/52698019/191152245-aa1fcd4a-8c37-4085-b93e-744babafa642.png)
If the shardingsphere rules are used, the property 'sqlSessionFactory' or 'sqlSessionTemplate' are required exception will result. If the shardingsphere rules are not used, that is, if the rules are removed, the project can be started normally, but the user-defined table splitting policy will not be followed.
### Reason analyze (If you can)
It may be a jar package problem, because our separate spring boot demo is OK, but it can't be integrated into the project. The project references multiple data sources, but it doesn't seem to have much impact.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I will give you the demo project code to help you look at it. Thank you

**Comment by zhaojinchao95** [comment]
@longfangwei Hi, can you translate title to english and describe your problem in the provided template?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
