### ISSUE TITLE
Use an existing algorithm to create a shadow rule.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21088]
### Is your feature request related to a problem?
No.

### Describe the feature you would like.
In DistSQL, we can create shadow algorithms alone, but we lack a way to specify algorithms when creating rules.
Reference: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/shadow/

We should improve the syntax of `CREATE SHADOW RULE` and `ALTER SHADOW RULE` to support specifiy an existing algorithm, please refer to `SHARDING TABLE RULE`:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/

**Comment by yx9o** [comment]
I want to try.

**Comment by RaigorJiang** [comment]
Closed for #21659.
