### ISSUE TITLE
Enhanced standalone mode and make it persist metadata

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21092]
Hi community,

  Now, ShardingSphere `Standalone` mode default use `h2` database memory mode. It 's not enough, Because some metadata are need to persist, such as : `view`. So i think we need to  enhance it and make it persistent.

**Comment by zhaojinchao95** [comment]
@itmachen Hi, can you look this?

**Comment by itmachen** [comment]
ok
