### ISSUE TITLE
The detailed description of the transaction manager is missing in user manual

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#21108]
### description
In the description of the RAL Global rule "Alter transaction rule"(https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/#global-rule) shows that support Atomikos, Narayana and Bitronix. But actually, to use the Narayana or Bitronix, you need to load class of Narayana or Bitronix from SPI by yourself. This is not stated in the documentation. This is not stated in the documentation, and it is also not stated how to manually load these transaction managers.

### screenshot of documentation

![191663739661_ pic](https://user-images.githubusercontent.com/57847965/191425229-267f5f4d-02c1-42eb-9687-a0febd7ad93a.jpg)

![201663739700_ pic](https://user-images.githubusercontent.com/57847965/191425267-eab4e815-a788-40ed-b127-624cac8f68f9.jpg)

### screenshot of execute statements

![211663739882_ pic](https://user-images.githubusercontent.com/57847965/191426199-fb2e61d4-ee64-4b11-ab7b-0ff0f05ff328.jpg)

**Comment by FlyingZC** [comment]
You can see how to configure transaction provider in these docs.
- https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/transaction/ 
- https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/transaction/bitronix/
- https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/special-api/transaction/narayana/

**Comment by FlyingZC** [comment]
Are you interested in trying to supplement this document.

**Comment by Qianyi951015** [comment]
Sure

**Comment by Qianyi951015** [comment]
@FlyingZC The document you provide are actually for JDBC, is that same for proxy?

**Comment by FlyingZC** [comment]
> @FlyingZC The document you provide are actually for JDBC, is that same for proxy?

Yes.
