### ISSUE TITLE
Does this component support encryption and decryption for big data, Hive, hbase and other components? 

### ISSUE THREAD

**Issue by 2013650523** [apache/shardingsphere#21101]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by linghengqian** [comment]
- HBase should be allowed to use only SQL92, but such unit tests have never existed, nor have antlr4 files that deal with Hbase's proprietary syntax.  

- I think this issue is blocked by https://github.com/apache/shardingsphere/issues/14061 . If you're happy to submit some PRs to push for better unit tests, it may be resolved sooner.

**Comment by 2013650523** [comment]
I do not understand the principle of ShardingSphere. May I ask whether using ShardingSphere can achieve seamless interception of agents directly from the bottom layer, or do I need to change the service configuration or code to access the agent layer?

**Comment by linghengqian** [comment]
- For a general RDBMS, ShardingSphere Proxy will virtualize a data source, and whether it uses the MySQL dialect or the PostgreSQL dialect depends on your choice.  ShardingSphere JDBC does the same, but the dialect used depends on the connected database.  

- For HBase, I have the impression that the master branch never existed unit tests. For Apache Phoenix unit tests, everything with NoSQL is a bit unknown.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
Please pay attention to #14061 for future updates.
