### ISSUE TITLE
Cannot use a separately created shadow algorithm to create a shadow rule (lack of syntax)

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#21103]
### Is your feature request related to a problem?
No
### Describe the feature you would like.
There is a syntax for creating a shadow algorithm separately in Distsql, but cannot use a separately created shadow algorithm to create a shadow rule(I'v already check the Antler file). This makes it moot to create the shadow algorithm alone.
Please complete the syntax of using shadow algorithm to create shadow rule.

**Comment by RaigorJiang** [comment]
Duplicate with #21088.
