### ISSUE TITLE
Caused by: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Mrljt497** [apache/shardingsphere#21102]
For English only, other languages will not accept.

Before report a bug, make sure you have:

Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will close it.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
5.1.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
Normal startup of the project

Actual behavior
Project startup error

Reason analyze (If you can)
Caused by: java.lang.NullPointerException: null
Error will be reported when the service is started after the tab
le splitting policy is configured.
The startup is normal after removing the sub table strategy.
<img width="1690" alt="企业微信截图_16637254802022" src="https://user-images.githubusercontent.com/74707593/191397220-af5208e9-300f-4db5-9941-1af1f9c9b49d.png">

**Comment by zhaojinchao95** [comment]
@Mrljt497 Hi, according to your error message, I don't see error log about `ShardingSphere`.

**Comment by TeslaCN** [comment]
Please use the new way to integrate ShardingSphere with Spring Boot.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/
