### ISSUE TITLE
1114 - Invalid sharding algorithms [INTERVAL].

### ISSUE THREAD

**Issue by ling185831070** [apache/shardingsphere#21106]
CREATE SHARDING TABLE RULE sn_log (
RESOURCES ( ds_2, ds_3, ds_4 ),
SHARDING_COLUMN = created,
TYPE (
NAME = "INTERVAL",
PROPERTIES ( "datetime-pattern"="yyyy-MM-dd HH:mm:ss","datetime-lower"= "2016-01-01 00:00:00", "datetime-upper"= "2021-12-31 00:00:00", "sharding-suffix-pattern"="yyyyMM","datetime-interval-amount"="1", "datetime-interval-unit"="Months") 
),
KEY_GENERATE_STRATEGY ( COLUMN = id, TYPE ( NAME = "snowflake" ) ) 
);

**Comment by ling185831070** [comment]
apache-shardingsphere-5.2.0-shardingsphere-proxy-bin.tar

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
