### ISSUE TITLE
Simplify module folders name

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#21129]
There are lots problem for long module folders, just ref #20041

It is better to reduce the length of module folder.

I plan to remove the prefix of modules, **but keep artifactId unchanged**.

For example: 

1. `shardingsphere-mode` should change to `mode`
2. `shardingsphere-cluster-mode-core` should change to `core`
3. `shardingsphere-cluster-mode-repository-zookeeper-curator` should change to `zookeeper-curator`

**Comment by Swastyy** [comment]
Hi, I want to help on this.

**Comment by terrymanu** [comment]
> Hi, I want to help on this.

Thank you for pay attention. 
This issue needs lots changes, it is better to choose a day which nobody submit codes, for example: holiday.
And it is better to merge all big PR.

We need to find the good time. I plan to do it on this Sunday if possible.
