### ISSUE TITLE
XA getConnection null

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#21133]
## Bug Report

My logical library name is db, but I use Db and open XA transactions, which will result in no connection.

### Which version of ShardingSphere did you use?

ShardingSphere-Proxy master

<img width="1512" alt="企业微信截图_89bebbe9-71aa-458b-8b28-97f886a55367" src="https://user-images.githubusercontent.com/26433395/191684223-078214ba-3dd0-4c5b-a1eb-353c2872d6e3.png">

**Comment by FlyingZC** [comment]
@zhaojinchao95 I want to investigate the issue, please assign me.

**Comment by natehuangting** [comment]
@FlyingZC 
I have already checked out the problem, please help to review

**Comment by FlyingZC** [comment]
> @FlyingZC I have already checked out the problem, please help to review

OK.
