### ISSUE TITLE
Completing RDL-readwriteSplitting-related documentation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#21146]
We are currently refactoring the documentation related to DistSQL, and we need the community's help to improve the following statements together.
- [ ] `ALTER READWRITE_SPLITTING RULE`
- [ ] `DROP READWRITE_SPLITTING RULE`

You can refer to the syntax from the [existing documentation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/).

You need to add documentation to the [readwrite-splitting directory](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/readwrite-splitting/).

You can also refer to the relevant Issue：#16666  #19898

**Comment by etcZYP** [comment]
i wanna have a try, plz assign to me, thx

**Comment by strongduanmu** [comment]
@etcZYP Welcome, I just assign this issue to you.

**Comment by etcZYP** [comment]
> @etcZYP Welcome, I just assign this issue to you.

i just clicked the unassign me button by accident, how can i cancel this operation？

**Comment by RaigorJiang** [comment]
Completed, thank you!

- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/alter-readwrite-splitting-rule/
- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/readwrite-splitting/drop-readwrite-splitting-rule/
