### ISSUE TITLE
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingSphereDataSource' defined in class path resource [org/apache/shardingsphere/spring/boot/ShardingSphereAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingSphereDataSource' threw exception; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by liuxuejava** [apache/shardingsphere#21153]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by zhaojinchao95** [comment]
@liuxuejava What is your configuration and ShardingSphere version? Can you submit your problem by refer to the issue template?

**Comment by zhaojinchao95** [comment]
@liuxuejava What is your configuration and ShardingSphere version? Can you desc your problem by refer to the issue template?

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192177234-13071290-f340-4e43-a60c-8e24f70c1567.png)

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192177798-518be3de-8f38-47f2-99a2-59ca15f203e5.png)

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192178074-113a8d83-f981-4021-a8ac-e2761ff81ded.png)
配置文件截图

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192178171-6e3a3c7c-f7f4-419c-8518-d110f8ad30a8.png)

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192178211-9577caf6-ac10-4a3d-9c3c-389d9fbb1c19.png)

**Comment by liuxuejava** [comment]
![image](https://user-images.githubusercontent.com/19323303/192178380-9881c309-8ff6-4704-a89c-4e806d8c9dd7.png)

**Comment by liuxuejava** [comment]
> @liuxuejava What is your configuration and ShardingSphere version? Can you desc your problem by refer to the issue template?

Configuration and version I have submitted

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by TeslaCN** [comment]
Your logs were incomplete, root cause was missed in your screenshots. And there is a new way to use Spring Boot since ShardingSphere 5.3.0. Please try it.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/
