### ISSUE TITLE
The XaDataSource-established Connection of the transaction manager was not properly closed.

### ISSUE THREAD

**Issue by codeleep** [apache/shardingsphere#21156]
### Which version of ShardingSphere did you use?
- The version is 5.0.0-beta, but our company has made some changes to it. But the part where the problem occurs does not have any code intrusion
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Q：
I found the close method in org.apache.shardingsphere.transaction.xa.XAShardingTransactionManager.
```java
  @Override
    public void close() throws Exception {
        for (XATransactionDataSource each : cachedDataSources.values()) {
            each.close(); // remove sequentially Configuration.removeResource(res.getName());
        }
        cachedDataSources.clear();
        xaTransactionManager.close();  // he will call userTransactionService.shutdown(true);
    }
```
However, call userTransactionService.shutdown(true); Is to shut down all resources in the Configuration. Isn't this unnecessary?

I also don't quite understand why the transaction manager didn't expose the way to shut down a resource alone. In the method exposed by the userTransactionService, he only removed it from the resourceList_ and resources_, but did not call its close method, which resulted in the need to wait for jvm to collect system garbage. This resource will only be recycled.

The problem that follows is that if I want to dynamically offline a logical library and its corresponding transaction manager on the proxy side, I cannot disconnect the proxy from mysql in time.

**Comment by FlyingZC** [comment]
I want to investigate this issue,please assign to me. @zhaojinchao95

**Comment by strongduanmu** [comment]
@local-li Can you try the latest release version? Such as 5.2.0.

**Comment by local-li** [comment]
> 



> @local-li Can you try the latest release version? Such as 5.2.0.

Yes, I found the difference in 5.2.0, but only the following changes were made.

1. Change the name to xaTransactionManagerProvider;
2. Added an overloaded method public void begin(final int timeout)
3. Judgment of legitimacy before xaTransactionManagerProvider.close()

But such a change did not meet my expectations. What I want is that, in terms of the logical library dimension, the connection in the transaction manager of a logical library can be closed individually. Instead of XATransactionDataSource.close() just remove the resource from Configuration.removeResource(res.getName());.

Of course, this part is not the source code of the framework itself. But there is such a need

**Comment by FlyingZC** [comment]
@local-li I think you are right,atomikos will remove the resources and close the xa connections when we call the `close` method.If ss closes the connection by itself, atomikos will not execute the close logic.

**Comment by local-li** [comment]
> @local-li I think you are right,atomikos will remove the resources and close the xa connections when we call the `close` method.If ss closes the connection by itself, atomikos will not execute the close logic.
Can I only call Configuration.removeResource(res.getName()) myself to get the resource to close

**Comment by FlyingZC** [comment]
The `Configuration.removeResource(resName)` method only removes the resource and does not close the resource,maybe you can refer to the logic of this method
`com.atomikos.icatch.config.Configuration#removeAndCloseResources`
1.remove the resouce by resource name and return the resource object you want,`Configuration.removeResource ( res.getName () )`;
2.close the resource
```java
private static void removeAndCloseResources(boolean force) {
  Collection<RecoverableResource> resources = Configuration.getResources();
  for (RecoverableResource res : resources) {
		  Configuration.removeResource ( res.getName () );
          try {
              res.close ();
          } catch ( ResourceException re ) {
           // ...
          }
      }
}
```

**Comment by local-li** [comment]
> The `Configuration.removeResource(resName)` method only removes the resource and does not close the resource,maybe you can refer to the logic of this method `com.atomikos.icatch.config.Configuration#removeAndCloseResources` 1.remove the resouce by resource name and return the resource object you want,`Configuration.removeResource ( res.getName () )`; 2.close the resource
> 
> ```java
> private static void removeAndCloseResources(boolean force) {
>   Collection<RecoverableResource> resources = Configuration.getResources();
>   for (RecoverableResource res : resources) {
> 		  Configuration.removeResource ( res.getName () );
>           try {
>               res.close ();
>           } catch ( ResourceException re ) {
>            // ...
>           }
>       }
> }
> ```



Yes, I also noticed this method, but Configuration static classes are proxied by UserTransactionService.

If I choose to cross it directly, is this a step-up in code design?

At present, my solution is to manually call System.gc() after the program itself is removed. But I will do a stricter check before calling System.gc(). Do you think there will be other hidden problems in this way?

**Comment by FlyingZC** [comment]
Execute `System.gc()` is the bad way I think.Both `Configuration.removeResource(resName)` and `com.atomikos.icatch.config.Configuration#removeAndCloseResources` methods are not in the JTA specification.I think just remove the logic in the `org.apache.shardingsphere.transaction.xa.atomikos.manager.AtomikosTransactionManagerProvider#removeRecoveryResource` and then let atomikos execute its own close logic.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
