### ISSUE TITLE
Add test case for PluginConfiguration.validate()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#21175]

**Comment by ishu-thakur** [comment]
@terrymanu can you provide brief description for this issue?

**Comment by captainbkarthick** [comment]
Hi I would like to work on this. Could you please assign this to me?

**Comment by captainbkarthick** [comment]
Please note that I have raised an Issue in the file. [https://github.com/apache/shardingsphere/issues/21573](https://github.com/apache/shardingsphere/issues/21573)

I wish to fix the Issue and Tests for the file.

**Comment by captainbkarthick** [comment]
@terrymanu

**Comment by captainbkarthick** [comment]
@terrymanu / @strongduanmu ,
Requesting to check this
