### ISSUE TITLE
Completing RDL-encrypt-related documentation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#21190]
We are currently refactoring the documentation related to DistSQL, and we need the community's help to improve the following statements together.
- [ ] `ALTER ENCRYPT RULE`
- [ ] `DROP ENCRYPT RULE`

You can refer to the syntax from the [existing documentation](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/).

You need to add documentation to the [encrypt directory](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/encrypt/).

You can also refer to the relevant Issue：#16666  #19898

**Comment by shining-stars-lk** [comment]
Can i have a try and assign to me?

**Comment by kavyabhat02** [comment]
Hi, can I take up this issue?
