### ISSUE TITLE
In Shardinging-JDBC-spring-boot-starter :4.1.1, the hint database policy in ShardingSphere is invalid

### ISSUE THREAD

**Issue by keliubo** [apache/shardingsphere#21205]
In ShardingStandardRoutingEngine class, GetDatabaseShardingValuesFromHint methods' HintManager. GetDatabaseShardingValues (logicTableName) 'depots strategy according to the table name for the database, lead to get less than, all the queries in the library

**Comment by RaigorJiang** [comment]
Hi @keliubo ,
Version v4.1.1 has been archived, have you tried the new version v5.2.0? Does the problem still exist?

**Comment by keliubo** [comment]
ok,i will try today in the evening

**Comment by RaigorJiang** [comment]
> ok,i will try today in the evening
OK, thank you!

**Comment by keliubo** [comment]
Equally, when users use hint depots strategy will be to call getDatabaseShardingValuesFromHint method。
private List<ShardingConditionValue> getDatabaseShardingValuesFromHint() {
        return getShardingConditions(HintManager.isDatabaseShardingOnly() ? HintManager.getDatabaseShardingValues() : HintManager.getDatabaseShardingValues(logicTableName));
    } 
LogicTableName is always the table name resulting in an empty return result

**Comment by RaigorJiang** [comment]
So, please provide sharding rules and hint operation procedures to analyze the cause of the problem

**Comment by keliubo** [comment]
rules:
      sharding:
        tables:
          #逻辑表
          course:
            #m1表示数据源 course表示表名
            actual-data-nodes: m$->{1..2}.course_$->{1..2}
            #库的分片策略
            database-strategy:
              hint:
                sharding-algorithm-name: t-db-hint
                  # com.example.shardingspheredemo.algorithm.db.hint.MyHintDbShardingAlgorithm
            #表分片策略
            table-strategy:
              hint:
                sharding-algorithm-name: t-table-hint
                #com.example.shardingspheredemo.algorithm.table.hint.MyHintTableShardingAlgorithm
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1
        sharding-algorithms:
          t-db-hint:
            type: HINT_DB_TEST
          t-table-hint:
            type: HINT_TABLE_TEST

@Getter
public class MyHintDbShardingAlgorithm implements HintShardingAlgorithm<Long> {

    private Properties props;

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, HintShardingValue<Long> shardingValue) {
        String key = shardingValue.getLogicTableName() + shardingValue.getValues().toArray()[0];
        if(availableTargetNames.contains(key)){
            return Arrays.asList(key);
        }
        throw new UnsupportedOperationException("this key " + key + " not support");
    }

    @Override
    public Properties getProps() {
        return null;
    }

    @Override
    public void init(Properties properties) {
        this.props = props;
    }

    @Override
    public String getType() {
        return "HINT_DB_TEST";
    }
}


@Test
    public void queryCourseByHint(){
        HintManager hintManager = HintManager.getInstance();
        hintManager.addDatabaseShardingValue("m","1");
        hintManager.addTableShardingValue("course","1");
        List<Course> courses = courseMapper.selectList(null);
        System.out.println(courses);
    }
**The result is to go back and look in both M1 and M2**
