### ISSUE TITLE
support `show processlist` show jdbc sleep connection

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#21215]
## Feature Request
`show processlist` has been able to display proxy sleep connections since #21000
So, jdbc is able to show sleep connection.
We could be able to get the sleep logic connection -- `ShardingSphereConnection`.
After implement this, when we use `show processlist` in proxy, we can get all logic connection's status.

**Comment by Jacob953** [comment]
@tuichenchuxin  Hi, I'd like to try. But I may need some instructions.

**Comment by tuichenchuxin** [comment]
> @tuichenchuxin Hi, I'd like to try. But I may need some instructions.

sure :)

**Comment by strongduanmu** [comment]
This feature is already supported in version 5.5.0, so I will close this issue.
