### ISSUE TITLE
How sharding tables with standard and hint at the same time

### ISSUE THREAD

**Issue by littlecold-Github** [apache/shardingsphere#21213]
version ： 5.1.1， springboot version：2.5.4
  hi， i have some confusion about how to sharding  tables with standard and hint at the same time。
  when i assign the sharding column, i hope it sharding table with the standard sharding algorithm, and when i use the HintManager, i hope it will go with the algorithm that i implement the interface `org.apache.shardingsphere.sharding.api.sharding.hint.HintShardingAlgorithm`.
so ,the question is ,how to achieve this purpose with springboot-starter？
thanks.

**Comment by RaigorJiang** [comment]
Hi @littlecold-Github 
Currently, the standard and hint strategies are mutually exclusive, and only one can be used.
Hope to have a solution to meet this scenario in the future.

**Comment by RaigorJiang** [comment]
Closed due to no response.

**Comment by lly-ke** [comment]
Can't it be supported now? Is it supported in lower versions? Do I have any way to support both

**Comment by RaigorJiang** [comment]
> Can't it be supported now? Is it supported in lower versions? Do I have any way to support both

You can use hint manager or SQL-hint for sharding tables.
- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/
- https://shardingsphere.apache.org/document/current/en/user-manual/common-config/sql-hint/#sharding
