### ISSUE TITLE
Optional long parameter 'id' is present but cannot be translated into a null value

### ISSUE THREAD

**Issue by 0xddy** [apache/shardingsphere#21227]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

**org.apache.shardingsphere:shardingsphere-jdbc-core-spring-boot-starter:5.2.0**

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

**ShardingSphere-JDBC**

### Expected behavior

Query results，Version shardingsphere-jdbc-core:5.1.2 can be used normally, but an exception occurs after upgrading

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Simple SELECT SQL

### Example codes for reproduce this issue (such as a github link).

![image](https://user-images.githubusercontent.com/10867124/192555504-edb49471-5926-461f-a2d2-806e28859784.png)

No anywhere nullable 'id'，but error print  **Caused by: java.lang.IllegalStateException: Optional long parameter 'id' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type**

**Comment by terrymanu** [comment]
I just set the issue as `invalid` because the author close it without any reason.
