### ISSUE TITLE
After adding or reducing fields to the database table, an exception will be thrown if there are similar (select * from t_table ) execution statements in the running service。

### ISSUE THREAD

**Issue by marsal1212** [apache/shardingsphere#21247]
## Question
version:  shardingsphere-jdbc:5.2.0
env: mysql8.0.17

After adding or reducing fields to the database table, an exception will be thrown if there are similar (select * from t_table ) execution statements in the running service。This situation will disappear after the service is restarted。
exception:
      adding fields ：      java.lang.ArrayIndexOutOfBoundsException: Index 64 out of bounds for length 64 ...
      reducing  fields ：   java.sql.SQLException: Column index out of range. ; Column index out of range....

Is there any solution ？

**Comment by chenws1012** [comment]
sharding-jdbc load all table metaData when start ，modifying the table structure after startup requires a restart
