### ISSUE TITLE
使用shardingsphere-jdbc-core-spring-boot-starter maven 包依赖太多，依赖不合理

### ISSUE THREAD

**Issue by jeffyok** [apache/shardingsphere#21253]
使用shardingsphere-jdbc-core-spring-boot-starter maven 包依赖太多，依赖不合理，依赖了 上百个包，光用你们这个框架就占用了60多M的包的大小，有没有方法只依赖部分的包，比如我 只要数据库读写分离，就不需要依赖其他没有用到的包了

**Comment by TeslaCN** [comment]
**For English only.**
You can exclude dependencies as you need.
