### ISSUE TITLE
data-source-aggregation-enabled lacks documentation

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#21254]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Yes, related to https://github.com/apache/shardingsphere/issues/15876. 

### Describe the feature you would like.

- In https://github.com/apache/shardingsphere/pull/16511, a general configuration item is introduced as `data-source-aggregation-enabled`, the default value is `false`.  But the documentation lacks an introduction to this configuration. Refer to https://shardingsphere.apache.org/document/5.2.0/en/user-manual/common-config/props/ .

- I think it's reasonable to patch its documentation.

**Comment by TeslaCN** [comment]
This is removed by https://github.com/apache/shardingsphere/pull/17034

**Comment by linghengqian** [comment]
- wow i didn't notice, i will close this issue.
