### ISSUE TITLE
Add test cases for agent yaml package

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#21270]
- [ ] YamlEngine
- [ ] YamlAgentConfigurationSwapper

**Comment by null-sys** [comment]
Can you assign this to me? I would like to work on this.

**Comment by terrymanu** [comment]
Sure, welcome @null-sys

**Comment by xiaobaisdz** [comment]
Can you assign this task to me？

**Comment by zhaojinchao95** [comment]
> Can you assign this task to me？

Welcome

**Comment by xiaobaisdz** [comment]
I would like to ask you some questions:
1. YamlEngineTest class already exists in project shardingsphere-infra-util, and all functions have been tested
2. I didn't find YamlAgentConfigurationSwapper this class

**Comment by terrymanu** [comment]
The class has been refactored
