### ISSUE TITLE
The link in the documents is wrong (404)

### ISSUE THREAD

**Issue by Programmer-ZX** [apache/shardingsphere#21280]
# The link Inline Expression in the documents is wrong

In the following document，in Chapter Inline Sharding Algorithm 、 Hint Inline Sharding Algorithm and Complex Inline Sharding Algorithm
[Inline Expression](https://github.com/apache/shardingsphere/blob/master/en/features/sharding/concept/inline-expression) link cannot be opened (404)

## Document link
- https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/common-config/builtin-algorithm/sharding.en.md
- https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/common-config/builtin-algorithm/sharding.cn.md

## link 404
![截屏2022-09-30 下午2 11 25](https://user-images.githubusercontent.com/23043552/193202351-c1ee15f1-13b8-4973-b149-c690814cba59.png)

#### en-01
![截屏2022-09-30 下午2 06 17](https://user-images.githubusercontent.com/23043552/193201905-1b16bc68-7b9a-4096-b910-cb6a95aff638.png)
#### en-02
![截屏2022-09-30 下午2 07 18](https://user-images.githubusercontent.com/23043552/193201904-481ba04d-466b-45dc-bb0f-a78423779008.png)
#### cn-03
![截屏2022-09-30 下午2 07 40](https://user-images.githubusercontent.com/23043552/193201906-0d394d86-5c7d-4af0-a2ed-3c58dd7e67cb.png)
#### cn-04
![截屏2022-09-30 下午2 07 54](https://user-images.githubusercontent.com/23043552/193201911-7d95eaa7-714e-43c5-b1d3-58537c04bb09.png)

##

**Comment by strongduanmu** [comment]
@Programmer-ZX Thank you for your feedback. Can you try to fix it?

**Comment by Swastyy** [comment]
Else I can ;).

**Comment by strongduanmu** [comment]
Welcome @Swastyy, you can assign to yourself next time.
