### ISSUE TITLE
Fix typo in XA Transanction section

### ISSUE THREAD

**Issue by KnothHe** [apache/shardingsphere#21296]
Hi, there is a typo in [ShardingSphere > Features > Distributed Transaction > XA Transanction] section.

> XA transaction adopts the concepts including AP(application program), YM(transaction manager) and RM(resource manager) to ensure the strong consistency of distributed transactions.

should be
> XA transaction adopts the concepts including AP(application program), TM(transaction manager) and RM(resource manager) to ensure the strong consistency of distributed transactions.

The change is `YM` -> `TM`.

**Comment by KnothHe** [comment]
Meanwhile `Transanction` is also typo.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/25814839/193396048-1d520f40-35af-4a1a-b6cb-8f7ceec8cd89.png">

**Comment by KnothHe** [comment]
Hi, @strongduanmu  I have submitted a pr, can you help me review and merge it?

**Comment by KnothHe** [comment]
Meanwhile, I don't seem to have permission to add label to this issue.

> Please choose the issue to be edited. If it is a new issue discovered or a new function enhancement to offer, please create an issue and set the right label for it.

**Comment by strongduanmu** [comment]
Hi @KnothHe, thank you for your contribution. I have merge your pr.

**Comment by KnothHe** [comment]
@strongduanmu thank you.
