### ISSUE TITLE
Import failed via IDEA 2021.1

### ISSUE THREAD

**Issue by Jacob953** [apache/shardingsphere#21371]
## Bug Report
Import failed via IDEA 2021.1. SS could be built successfully via maven, but loading failed under the submodule.
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/64075563/194587189-7f43c737-1716-4c6c-a375-3f0988afccf2.png">
I've tried importing about ten times (including rebooting and restoring other configurations). And this worked one week ago (before reconstructing).
### Which version of ShardingSphere did you use?
Latest.
### Expected behavior
Update to IDEA 2022.2
### Actual behavior
Update to IDEA 2022.2
### Reason analyze (If you can)
I'm not sure exactly why. But the project imported successfully after I updated IDEA to 2022.2.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/64075563/194588208-22570ae7-30f6-46a5-9829-560aeef51ec5.png">
### Steps to reproduce the behavior, such as SQL to execute, sharding rule configuration, when exceptions occur, etc.
Env: 
- os Apple M1 Big Sur 11.6
- ide IDEA 2021.1

Step:
- Get from VCS

**Comment by terrymanu** [comment]
What is the result for execute `mvn install`?

**Comment by Jacob953** [comment]
> What is the result for execute `mvn install`?

Build Success.

**Comment by TeslaCN** [comment]
This is related to your environment. You have solved this issue. I'm closing this.
