### ISSUE TITLE
Add more cases for ConstructHPA unit test 

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere#21377]
Hi community,

This issue is for https://github.com/apache/shardingsphere-on-cloud/issues/78

Aim
---
Add more cases for ConstructHPA to improve unit test coverage.

The function is https://github.com/apache/shardingsphere-on-cloud/blob/2f348ea1208b3396ddbe873a60f32369578f8697/shardingsphere-operator/pkg/reconcile/resource.go#L258. 

The cases should be added to https://github.com/apache/shardingsphere-on-cloud/blob/main/shardingsphere-operator/pkg/reconcile/reconcile_test.go.

Basic Qualifications
---

- [Golang Unit Test](golang.org)
- [stretchr/testify/assert](github.com/stretchr/testify/assert)
- [Kubernetes Deployment](kubernetes.io)

**Comment by KiranPatil30** [comment]
Hello Sir , Can You Assign This Issue to Me?
Please

**Comment by mlycore** [comment]
Hi. any updates on this ? @KiranPatil30

**Comment by KiranPatil30** [comment]
No

**Comment by strongduanmu** [comment]
Ref #28487.
