### ISSUE TITLE
5.1.2 group by function bug 

### ISSUE THREAD

**Issue by ZhiYu2018** [apache/shardingsphere#21407]
## Bug Report
  when use 5.1.2 to execute sql like this:
     select cc,
        sum(a) as a,
        sum(b) as b,
        sum(c) as c
        from xxxx
        where xxxx = 0
        and ec ='xxx'
        and cc in('U','B','E', 'u')
        group by cc
 then the result U has not been aggregated. the result like this:
 B,***,***,***,
 E,***,***,***.
U,***,***,***.
u,***,***,***.
U,***,***,***.
the U returned two rows when we had two shards.

**Comment by TeslaCN** [comment]
Please try the ShardingSphere 5.3.0.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
