### ISSUE TITLE
Add unit test for CuratorZookeeperRepository.getRegistryCenterTime(final String key)

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21435]

**Comment by DivvSaxena** [comment]
will work on it

**Comment by DivvSaxena** [comment]
assign

**Comment by zhaojinchao95** [comment]
> assign

Done

**Comment by DivvSaxena** [comment]
can you give me the location of the file

**Comment by DivvSaxena** [comment]
and do we have to basically add unit test or do we have to document it or add some description about it please guide

**Comment by zhaojinchao95** [comment]
> and do we have to basically add unit test or do we have to document it or add some description about it please guide

Only add unit test

**Comment by zhaojinchao95** [comment]
> can you give me the location of the file

https://github.com/apache/shardingsphere/blob/master/mode/type/cluster/repository/provider/zookeeper-curator/src/test/java/org/apache/shardingsphere/mode/repository/cluster/zookeeper/CuratorZookeeperRepositoryTest.java

**Comment by DivvSaxena** [comment]
#21452 made the PR

**Comment by DivvSaxena** [comment]
can u tell me how to fix that issue
#21452

**Comment by zhaojinchao95** [comment]
> can u tell me how to fix that issue #21452

You can see error message : https://github.com/apache/shardingsphere/actions/runs/3218169698/jobs/5275132672

**Comment by zhaojinchao95** [comment]
The method are removed, so i will close it
