### ISSUE TITLE
Add unit test for CuratorZookeeperRepository.getNumChildren(final String key)

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21434]

**Comment by iofit** [comment]
I'll start working on this, if someone can assign it it'd be great!

**Comment by strongduanmu** [comment]
@iofit Assigned.

**Comment by iofit** [comment]
I've added a PR https://github.com/apache/shardingsphere/pull/21537 please take a look whenever you can, thanks!
