### ISSUE TITLE
Possibly make `proxy-hint-enabled: true` use threads replaced from platform threads to virtual threads?

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#21454]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- No.

### Describe the feature you would like.

- As mentioned in https://shardingsphere.apache.org/document/5.2.0/en/user-manual/shardingsphere-proxy/yaml-config/props/ , if `proxy-hint-enabled` is set to `true` , Proxy's threading model will change from IO multiplexing to an independent thread for each request.
- ![image](https://user-images.githubusercontent.com/20187731/194837078-06d994e2-8a48-474f-bd71-81fbe6eb6e37.png)
- In JDK 19, there is a concept of virtual threads that is different from platform threads. Is it possible for us to change the use of platform threads in specific components to virtual threads to eliminate the problem of reducing the throughput of ShardingSphere Proxy? This may mean that the minimum compiled JDK version of some Proxy-related components has been upgraded to JDK19.

**Comment by TeslaCN** [comment]
I've tested Virtual thread multiple times in x64 and aarch64, the performance is worse.

**Comment by linghengqian** [comment]
- It seems premature to discuss this question, I will close this issue.
