### ISSUE TITLE
[DistSQL] Add SQL parser test case for `ShowShardingHintStatusStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21464]
### Background

`SHOW SHARDING HINT STATUS` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `ShowShardingHintStatusStatement`. Now we need to add a test case for this parsing process to assert that the parsing is correct.

### Aim

Add SQL parser test case for `ShowShardingHintStatusStatement`.

- Affected files:

  - SQLParserTestCases (**modify**)

  - test/parser/src/main/resources/case/ral/updatable.xml (**modify**)

  - test/parser/src/main/resources/sql/supported/ral/updatable.xml (**modify**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/queryable/ShowShardingHintStatusStatementTestCase.java (**create**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/queryable/ShowShardingHintStatusStatementAssert.java (**create**)

  - QueryableRALStatementAssert (**modify**)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- ShowAllVariablesStatement
- ShowAllVariablesStatementTestCase
- ShowAllVariablesStatementAssert
- SQLParserTestCases
- search for "show-all-variables"

**Comment by isHuangXin** [comment]
[WeOpen Star] Hi, Jiang. I want to try this issue. Plz assign it to me~

**Comment by isHuangXin** [comment]
Close this issue due to pr being merged.
