### ISSUE TITLE
[DistSQL] Add SQL parser test case for `AddShardingHintTableValueStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21468]
### Background

`ADD SHARDING HINT TABLE_VALUE xx = yy` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `AddShardingHintTableValueStatement`. Now we need to add a test case for this parsing process to assert that the parsing is correct.

### Aim

Add SQL parser test case for `AddShardingHintTableValueStatement`.

- Affected files:

  - SQLParserTestCases (**modify**)

  - test/parser/src/main/resources/case/ral/updatable.xml (**modify**)

  - test/parser/src/main/resources/sql/supported/ral/updatable.xml (**modify**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/updatable/AddShardingHintTableValueStatementTestCase.java (**create**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/updatable/AddShardingHintTableValueStatementAssert.java (**create**)

  - UpdatableRALStatementAssert (**modify**)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- ImportDatabaseConfigurationStatement
- ImportDatabaseConfigurationStatementTestCase
- ImportDatabaseConfigurationStatementAssert
- SQLParserTestCases
- search for "import-database-config"

**Comment by ankit-dub** [comment]
HintRALStatementAssert can be created for all Hint SQL parsing test cases, RAL statement are extended by Update, Query and Hint.
UpdatableRALStatementAssert assertIs function is not compatible with Hint statement

**Comment by RaigorJiang** [comment]
Hi @ankit-dub 
Thanks for your feedback, would you like to participate in this task?

**Comment by ankit-dub** [comment]
Yeah I will take up this task @RaigorJiang

**Comment by RaigorJiang** [comment]
@ankit-dub Welcome~

**Comment by ankit-dub** [comment]
@RaigorJiang get access denied while pushing the changes

fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by RaigorJiang** [comment]
@ankit-dub  Please refer to https://shardingsphere.apache.org/community/en/involved/contribute/contributor/

**Comment by RaigorJiang** [comment]
Fixed by #21873.

**Comment by RaigorJiang** [comment]
> @RaigorJiang created the PR with changes. Can you review and approve workflow?

Merged, thank you!
