### ISSUE TITLE
[DistSQL] Add SQL parser test case for `SetShardingHintDatabaseValueStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21465]
### Background

`SET SHARDING HINT DATABASE_VALUE = xx` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `SetShardingHintDatabaseValueStatement`. Now we need to add a test case for this parsing process to assert that the parsing is correct.

### Aim

Add SQL parser test case for `SetShardingHintDatabaseValueStatement`.

- Affected files:

  - SQLParserTestCases (**modify**)

  - test/parser/src/main/resources/case/ral/updatable.xml (**modify**)

  - test/parser/src/main/resources/sql/supported/ral/updatable.xml (**modify**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/updatable/SetShardingHintDatabaseValueStatementTestCase.java (**create**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/updatable/SetShardingHintDatabaseValueStatementAssert.java (**create**)

  - UpdatableRALStatementAssert (**modify**)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- ImportDatabaseConfigurationStatement
- ImportDatabaseConfigurationStatementTestCase
- ImportDatabaseConfigurationStatementAssert
- SQLParserTestCases
- search for "import-database-config"

**Comment by isHuangXin** [comment]
[WeOpen Star] Hi, Jiang. I want to try this issue. Plz assign this issue to me~

**Comment by RaigorJiang** [comment]
Fixed.
