### ISSUE TITLE
[DistSQL] Add SQL parser test case for `ClearShardingHintStatement`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21469]
### Background

`CLEAR SHARDING HINT` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `ClearShardingHintStatement`. Now we need to add a test case for this parsing process to assert that the parsing is correct.

### Aim

Add SQL parser test case for `ClearShardingHintStatement`.

- Affected files:

  - SQLParserTestCases (**modify**)

  - test/parser/src/main/resources/case/ral/updatable.xml (**modify**)

  - test/parser/src/main/resources/sql/supported/ral/updatable.xml (**modify**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/updatable/ClearShardingHintStatementTestCase.java (**create**)

  - test/parser/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/updatable/ClearShardingHintStatementAssert.java (**create**)

  - UpdatableRALStatementAssert (**modify**)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- ShowAllVariablesStatement
- ShowAllVariablesStatementTestCase
- ShowAllVariablesStatementAssert
- SQLParserTestCases
- search for "show-all-variables"

**Comment by vinayakghatul** [comment]
Hi team,Can I pick this?

**Comment by RaigorJiang** [comment]
Hi @vinayakghatul ,
Sure, welcome to Apache ShardingSphere, I just assign it to you.

**Comment by Qianyi951015** [comment]
please assign to me, i will finish asap
