### ISSUE TITLE
Some hyperlinks in documents are outdated after project structure refactored

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#21477]
## Fix 404 in documents

Related to https://github.com/apache/shardingsphere/pull/21339

There are many 404 links in https://github.com/apache/shardingsphere/tree/master/docs/document/content/dev-manual

For example: https://github.com/apache/shardingsphere/pull/21478

**Comment by Swastyy** [comment]
I will do some.

**Comment by Swastyy** [comment]
I think this issue is solved by all tha above PRs.

**Comment by TeslaCN** [comment]
> I think this issue is solved by all tha above PRs.

Thank you @Swastyy. I'm closing this.
