### ISSUE TITLE
Words being broken within the text-box in almost all pages

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#21474]
In the documentation, in many pages the words in every line are broken.
for example, in the image below: designed is as 'desig' and 'ned'; testing as 'te' and 'sting'
![image](https://user-images.githubusercontent.com/64654203/194933707-b83e1d0e-60a2-4c1d-8df0-051bb8e4f8a8.png)

A solution to above I can see in a discussion is [here](https://answers.microsoft.com/en-us/msoffice/forum/all/words-being-broken-within-textbox/f24f0d9b-919f-4849-bd58-1e356f0fc4e7)

**Comment by BryanYin** [comment]
I guess this should be a one-line change, please see #21903.

**Comment by terrymanu** [comment]
Fixed by 6a83538a45c72026def41b4c54082210bc271c72
