### ISSUE TITLE
Supporting data source level heterogeneous database gateway

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#21481]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Currently, in issue #17619, we have implemented basic heterogeneous database gateway feature. Users can use the MySQL protocol to access the backend PostgreSQL database. But it will require that the databases in the same logic database must be of the same type, otherwise an exception will be thrown. 

In a real heterogeneous database scenario, the backend storage in the same logical database may be a mix of databases such as MySQL and PostgreSQL. Therefore, we need to implement heterogeneous support at the data source level, allowing users to mix different databases for storage.

In order to achieve this goal, we first need to adjust the metadata to support the database type judgment at the data source level.

```java
/**
 * ShardingSphere resource meta data.
 */
public final class ShardingSphereResourceMetaData {
    
    private final Map<String, ShardingSphereResource> resources;
    ...
}

public final class ShardingSphereResource {

    private final DataSource dataSource;

    // 每一个 DataSource 对应一个 databaseType
    private final DatabaseType databaseType;
    
    @Getter(AccessLevel.NONE)
    private final DataSourceMetaData dataSourceMetaData;
}
```

With the modification of the ShardingSphereResource object, we need to modify the following modules to ensure that the databaseType at the data source level can take effect. 

- [x] #22558
- [x] modify metadata load logic
- [x] modify kernel merge engine logic which related with databaseType
- [x] modify sql translate logic to support dataSource level sql translate
- [x] modify proxy and jdbc adaptor logic which related with databaseType
- [x] modify TransactionRule to support dataSource level databaseType

**Comment by TeslaCN** [comment]
Hi @strongduanmu 
Have we finished this?

**Comment by strongduanmu** [comment]
Basically completed, except for the first subtask, I will adjust the first subtask as a separate issue and complete it in the next version.

**Comment by strongduanmu** [comment]
All task has been finished, so I will close this issue.
