### ISSUE TITLE
Unify metadata naming

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21485]
I found some metadata related classes with camel case `MetaData` in their names like
```java
/**
  * Meta data contexts.
  */
@RequiredArgsConstructor
@Getter
public final class MetaDataContexts
```
But there are also some that do not use camel case, such as
```java
/**
  * SPI metadata aware.
  */
public interface SPIMetadataAware {
```

In fact, `Metadata` is a proper noun, it does not need to be split.
I propose a uniform adjustment to the related names, including related comments.

Ref: https://en.wikipedia.org/wiki/Metadata

**Comment by Swastyy** [comment]
I want to work on it :)

**Comment by RaigorJiang** [comment]
@Swastyy  Welcome :)

**Comment by DivvSaxena** [comment]
@RaigorJiang  If no one is working on it , can u assign it to me

**Comment by RaigorJiang** [comment]
Hi @Swastyy, 
Can we assign the issue to @DivvSaxena  ?

**Comment by Swastyy** [comment]
Alright @RaigorJiang , I am little busy this week too, we can assign it to him.

**Comment by RaigorJiang** [comment]
> Alright @RaigorJiang , I am little busy this week too, we can assign it to him.

Well, thank you! @Swastyy @DivvSaxena

**Comment by DivvSaxena** [comment]
@RaigorJiang Check my PR #22066

**Comment by RaigorJiang** [comment]
> @RaigorJiang Check my PR #22066

Please hava a look: https://github.com/apache/shardingsphere/pull/22066#pullrequestreview-1177431946

**Comment by DivvSaxena** [comment]
@RaigorJiang  I understood that Metadata is a proper noun and it should not be written like "Meta data" or "meta data" , Thus i have updated please check my PR #22130

**Comment by RaigorJiang** [comment]
@DivvSaxena 
In fact, there are many such files that need to be modified, which is the purpose of this issue.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5668787/201503778-e9466887-6286-44d7-b8bd-c0b073133986.png">

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/5668787/201503812-ee4470ae-205b-4fa3-82e0-c83307b857b6.png">

**Comment by DivvSaxena** [comment]
@RaigorJiang Ok i will submit PRs for ech module separately.

**Comment by DivvSaxena** [comment]
Hey @RaigorJiang !
I made PRs and checked all the files and modified it  PRs-  #22155 #22130
Lets connect on slack and Linkedln please drop your id

**Comment by RaigorJiang** [comment]
@DivvSaxena 
Sorry, CI is still failing.

**Comment by terrymanu** [comment]
It is better to keep consists with the JDBC interface.
for example: java.sql.ResultSetMetaData

I prefer to use MetaData

**Comment by terrymanu** [comment]
I just revert the changes of #22704

**Comment by RaigorJiang** [comment]
> It is better to keep consists with the JDBC interface. for example: java.sql.ResultSetMetaData
> 
> I prefer to use MetaData

OK.
