### ISSUE TITLE
max-connections-size-per-query not work

### ISSUE THREAD

**Issue by wangjiihao** [apache/shardingsphere#21482]
配置 max-connections-size-per-query 结果没有效果，shardingsphere运行时 还是使用的默认值1
![a34b62fb27d6f21790487cf432f8315](https://user-images.githubusercontent.com/49392645/195010184-d20666bd-9a4a-467e-9a17-6719551d0a92.jpg)

**Comment by wangjiihao** [comment]
![image](https://user-images.githubusercontent.com/49392645/195010569-e5f06e71-eb62-4d60-97d3-357accbd24d1.png)

**Comment by TeslaCN** [comment]
Please paste your rules and SQL.

**Comment by wangjiihao** [comment]
# 分片的配置
    rules:
      sharding:
        # 表的分片策略
        tables:
          # 逻辑表的名称
          asset_terminal_basic_seq:
            # 数据节点配置，采用Groovy表达式
            actual-data-nodes: master.asset_terminal_basic_seq$->{0..4}
            #分表策略
            table-strategy:
              standard:
                # 分片列名称
                sharding-column: id
                sharding-algorithm-name: alg-hash-mod
        #分片算法配置
        sharding-algorithms:
          # 哈希取模分片算法
          alg-hash-mod:
            # 分片算法类型
            type: HASH_MOD
            # 分片算法属性配置
            props:
              sharding-count: '5'

**Comment by wangjiihao** [comment]
sql就是一些最简单的select查询没什么特别的东西

**Comment by wangjiihao** [comment]
用的是springbootstarter的shardingsphere5.1.1版本

**Comment by wangjiihao** [comment]
@TeslaCN 您好,就是配置max-connections-size-per-query: 100的时候没生效,局部配置如下:
props:
      #sql打印
      sql-show: true
      max-connections-size-per-query: 100

**Comment by TeslaCN** [comment]
For English only.

**Comment by wangjiihao** [comment]
Hello, the max-connections-size-per-query does not take effect. The local configuration is as follows:

props:

#Sql printing

sql-show: true

max-connections-size-per-query: 100

**Comment by wangjiihao** [comment]
The dependencies used are as follows:
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
        </dependency>

**Comment by wangjiihao** [comment]
At present, the efficiency of some simple queries is relatively low. After tracing the source code, we can see that the union all is automatically spliced, resulting in the low efficiency of some simple queries and queries using paging plug-ins when the data volume is large

**Comment by wangjiihao** [comment]
@TeslaCN It is suggested that the user can configure the part of adding union all .In addition, I configure this parameter in the yml file, max connections size per query, which has never been recognized

**Comment by TeslaCN** [comment]
Hi @wangjiihao 
Please try the latest ShardingSphere 5.3.1. The ShardingSphere Spring Boot Starter has been deprecated and removed since 5.3.0.
About the `union all`, please file a new issue.
