### ISSUE TITLE
Add a new DistSQL `REFRESH DATABASE METADATA`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21483]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Now we have a DistSQL to refresh the table's metadata:
````
REFRESH TABLE METADATA
````
Ref https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/

In some specific scenarios (such as event exceptions), there will also be inconsistent rule metadata and configuration. 
I want to add a DistSQL to refresh the metadata of the entire logic database, including rules and tables. 

The syntax may be
````
REFRESH DATABASE METADATA
````

**Comment by strongduanmu** [comment]
Hi @RaigorJiang , could we finish this issue in 5.2.1?

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang , could we finish this issue in 5.2.1?

Yes, it will be finished soon.
