### ISSUE TITLE
Cluster mode questions 

### ISSUE THREAD

**Issue by Liam987-yu** [apache/shardingsphere#21497]
Hi
I have three questions 
1. If i just use write/read splitting feature , Should i use the cluster mode (zookeeper) 
2. What is the impact if I don't configure the mode？
3.  My project already have imported the  nacos ,Can i use nacos to be  the registery center  

Looking forward  to your reply

**Comment by TeslaCN** [comment]
Nacos support was supported in ShardingSphere 5.3.0. Cluster mode will share metadata between processes and restarting is no required after metadata changed. If you are using standalone mode, restarting processes is required after executed DDL.
