### ISSUE TITLE
NPE occurred when execute `SHOW STATUS` in Proxy.

### ISSUE THREAD

**Issue by Dangshuangyin** [apache/shardingsphere#21521]
![image](https://user-images.githubusercontent.com/89122494/195273832-8e8e62a1-e7a1-4dad-a889-8d74a3914a60.png)

 ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[ERROR] 2022-10-12 14:06:53.546 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.infra.federation.executor.original.OriginalFederationExecutor.createConnection(OriginalFederationExecutor.java:92)
        at org.apache.shardingsphere.infra.federation.executor.original.OriginalFederationExecutor.executeQuery(OriginalFederationExecutor.java:83)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.doExecuteFederation(JDBCDatabaseCommunicationEngine.java:165)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:123)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:94)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:110)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by RaigorJiang** [comment]
Hi @Dangshuangyin 
Thanks for your feedback, what is your version of Proxy?

**Comment by Dangshuangyin** [comment]
> Hi @Dangshuangyin Thanks for your feedback, what is your version of Proxy?

5.2.0

**Comment by RaigorJiang** [comment]
Hi @Dangshuangyin 
I verified with 5.2.0 and found no similar issues.
Can you provide the rule configuration in order to reproduce the problem?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/5668787/195637391-728fad07-a4f2-4e70-8442-5b99cf7678af.png">

**Comment by Dangshuangyin** [comment]
> [status: need more info ](/apache/shardingsphere/labels/status%3A%20need%20more%20info) l

![image](https://user-images.githubusercontent.com/89122494/195742139-102e9905-3012-4e41-b870-15950224729d.png)

CREATE TABLE `t_order` (
  `id` bigint(20) NOT NULL COMMENT '主键id',
  `order_id` int(20) NOT NULL DEFAULT 0 COMMENT '订单ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

![image](https://user-images.githubusercontent.com/89122494/195742229-cc0ac432-e318-4b83-8da1-1e7b16a95ef7.png)

![image](https://user-images.githubusercontent.com/89122494/195742262-adb98427-0fb3-4082-a7ab-5a68a3b5a308.png)

**Comment by RaigorJiang** [comment]
@Dangshuangyin 
Sorry, I tested again with your configuration and everything works fine.
Moreover, such a configuration will not use the `federation` engine. 
Do you have other configurations for your proxy?


<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5668787/196104867-04982df8-fe49-424c-9ec8-25d6c3dc6916.png">

**Comment by koala775** [comment]
I also have this proplem,version:shardingsphere-proxy-5.2.1.I use DBeaver to connect then throw this exception.

**Comment by RaigorJiang** [comment]
> I also have this proplem,version:shardingsphere-proxy-5.2.1.I use DBeaver to connect then throw this exception.

@koala775 Please enable `sql_show` and provide the SQL and log when exception occurs, thank you!

**Comment by koala775** [comment]
I haven't execute any sql,I just use DBeaver  to connect proxy.

**Comment by RaigorJiang** [comment]
> I haven't execute any sql,I just use DBeaver to connect proxy.

Yes, DBeaver will send SQL statement to query some data.

**Comment by koala775** [comment]
Yes.I have saw some sql like,SELECT @@session.automoit.Then next line it's the exception.

**Comment by RaigorJiang** [comment]
@koala775 
After my test, I found that the exception is not caused by the printed Actual SQL, we need to enable the Proxy's debug log and view the received packets.
- Find logback.xml
```xml
<logger name="org.apache.shardingsphere" level="info" additivity="false">
      <appender-ref ref="console" />
</logger>
```
- Change it to debug:
```xml
<logger name="org.apache.shardingsphere" level="debug" additivity="false">
      <appender-ref ref="console" />
</logger>
```
And then restart Proxy and connect with client.

**Comment by RaigorJiang** [comment]
In my environment, it was the following SQL that caused the NPE, which was not the same as what @Dangshuangyin  provided:
```sql
/* ApplicationName=DBeaver 22.2.3 - Main */ SELECT * FROM information_schema.TABLES t
WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS';
```

**Comment by RaigorJiang** [comment]
However, in distributed scenarios, `information_schema` is not easy to implement, and this work will still take a long time.

**Comment by koala775** [comment]
So,it's have a effect with the use?

**Comment by koala775** [comment]
The log is like:
![lQLPJxbWourZoWrNATHNBH-wCqLMBiBPbcMDYLoAm4DOAA_1151_305](https://user-images.githubusercontent.com/35438579/199668803-ae9a56b7-3d6b-404b-bc32-19f75f7ef908.png)

**Comment by RaigorJiang** [comment]
> So,it's have a effect with the use?

Since there are too many differences between third-party clients, it is recommended to use the mysql command client to connect to the Proxy.

**Comment by RaigorJiang** [comment]
duplicated with #18955.
