### ISSUE TITLE
Improve Properties definition in DistSQL to support more types

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21543]
Ref to #18811, 

I found that the behavior of property value in DistSQL has some conflicts with the specification, e.g.
````
ADD RESOURCE resource_0 (
     HOST='127.0.0.1', # string
     PORT=3306, # int
     DB='db0', # string
     USER='root', # string
     PASSWORD="root", # string
     PROPERTIES("maximumPoolSize"="10") # string
)
````
The key of a property is a string ("maximumPoolSize"), but the value can be an integer or a boolean.

Therefore, I am going to adjust the definition of the `PROPERTIES` in DistSQL so that the types supported by value conform to the overall specification.

**Comment by TeslaCN** [comment]
Hi @RaigorJiang 
Any progress here?

**Comment by RaigorJiang** [comment]
Completed.
