### ISSUE TITLE
sharding jdbc: how to import existing data to sharding tables

### ISSUE THREAD

**Issue by huang714669** [apache/shardingsphere#21549]
I am using sharding-jdbc 5.1.2, for existing or historical data(these data are updated incrementally in real-time), does shardingsphere, is there any way or best practice to import these data to sharding tables:

I can figure out one way, to create a consumer to consume the  historical data periodically， but this solution is an intrusion into the business code, so this is not the best way for us

**Comment by huang714669** [comment]
I have see the document about sharding-proxy data migration https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/migration/,

I have another question before I try this, does this migration solution support different table schemas between the source table and the target table?

**Comment by sandynz** [comment]
> I have see the document about sharding-proxy data migration https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/migration/,
> 
> I have another question before I try this, does this migration solution support different table schemas between the source table and the target table?

Hi @huang714669 , the target table could have different table name as source table, but the table structure should be the same.
If you want to ADD/DROP/MODIFY table columns, you could try to do it before migration on source table for now.
And could you describe how you plan to change your table schema?

**Comment by huang714669** [comment]
got it ! We have to figure out the data compatible way out of shardingsphere
