### ISSUE TITLE
Pagination failure---urgent

### ISSUE THREAD

**Issue by HeiKeJi6** [apache/shardingsphere#21556]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.1.1</version>
        </dependency>

PageHelper. startPage(1, 10)..doSelectPage(() -> mybatisMapperSelectMethod()); // The queried table has no partitions

Normally, pagerhelper checks the total number and then limits it. However, after using the data source provided by shardingjdbc, only the sql statements defined in the mapper are queried, resulting in page invalidation.

**Comment by TeslaCN** [comment]
The version 4.x is EOL. Please upgrade to latest version.
