### ISSUE TITLE
Custom sharding algorithm range query not executed

### ISSUE THREAD

**Issue by sun2430987** [apache/shardingsphere#21554]
version:
sharding-jdbc 5.2.0

config:
![image](https://user-images.githubusercontent.com/26375092/195774878-d9f69310-2276-47b6-93fb-c7789d8e77eb.png)

LogTablesShardingAlgorithm:
![image](https://user-images.githubusercontent.com/26375092/195774988-e19bb2c4-5ac4-4ff3-a548-282b9ce130e2.png)

- init(Properties properties) ok
- doSharding(Collection<String> collection, PreciseShardingValue<Date> preciseShardingValue) ok
- doSharding(Collection<String> collection, RangeShardingValue<Date> rangeShardingValue) not executed

**Comment by haiy1026** [comment]
algorithmClassName -> algorithm-class-name

**Comment by TeslaCN** [comment]
It is expected behaviour if your SQL has specified precise value for sharding key.
If you have other question, please open a new issue according to the template.
