### ISSUE TITLE
consider the compatibility of the API

### ISSUE THREAD

**Issue by linking12** [apache/shardingsphere#21566]
Please consider the compatibility of the API. From 5.1.1 to 5.2.0, the entire API has undergone earth-shaking changes. Don't you consider the complexity of application upgrading?

As a top-level project of apache, there is still a company supporting it, and such a mistake should not be made

**Comment by strongduanmu** [comment]
Hi @linking12, thank you for your feedback. I'm so sorry to say that with the rapid development of ShardingSphere, sometimes we have to make adjustments to the API. Currently, the version of ShardingSphere follows the A.B.C format, when the API remains compatible, we will upgrade the C version, such as: 5.1.0, 5.1.1 and 5.1.2. When API incompatibilities arise, we upgrade B versions, such as 5.1.0 and 5.2.0. If the entire ShardingSphere architecture changes drastically, we will upgrade the A version, such as 4.0.0 and 5.0.0.
