### ISSUE TITLE
Start data migration occur NPE

### ISSUE THREAD

**Issue by wzhj2326** [apache/shardingsphere#21561]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Data Migration
Remise:
  logical database in proxy contains capital letters e.g(testDB)
Action:
     Start data migration e.g( MIGRATE TABLE ds_0.Task INTO testDB.task;) then occur NPE

![screenshot-20221014-163938](https://user-images.githubusercontent.com/15643447/195802699-0d700910-40ce-4ba5-b36f-21606b08762e.png)

**Comment by sandynz** [comment]
Hi @wzhj2326 , thanks for your feedback. We'll fix it, you could try `testdb` for now.
