### ISSUE TITLE
Add test case for ShardingAutoTableAlgorithmUtil

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#21569]

**Comment by captainbkarthick** [comment]
I would like to work on this issue.

**Comment by strongduanmu** [comment]
Welcome @captainbkarthick, I will assign this issue to you.

**Comment by captainbkarthick** [comment]
@terrymanu / @strongduanmu 
Raised PR for this change.
Requesting to check and Merge.

**Comment by captainbkarthick** [comment]
@terrymanu ,
I have fixed the checkstyle errors.
Requesting to check.

**Comment by captainbkarthick** [comment]
Hi @terrymanu / @strongduanmu ,
Requesting to check this PR.

Thanks
