### ISSUE TITLE
There is a NullPointerException when I execute select * from schema.table in postgresql

### ISSUE THREAD

**Issue by zhouyouwei-0127** [apache/shardingsphere#21596]
### Which version of ShardingSphere did you use?
5.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
![image](https://user-images.githubusercontent.com/64695476/196029760-e74cf874-fca0-484f-8baf-eef1a5dc4638.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/64695476/196029801-e1f3ae07-dcb4-4eb2-a95a-0b0dda07fe58.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL: select * from public.t_user;
configuration: 
![image](https://user-images.githubusercontent.com/64695476/196029982-0bd66567-76e4-478e-846c-48cdae89cf05.png)

when I execute select * from public.t_user, exception occur

**Comment by TeslaCN** [comment]
Please try the ShardingSphere 5.3.0. We are keep improving the schema support. Please open another issue if you have new question.
