### ISSUE TITLE
can support guass db now？

### ISSUE THREAD

**Issue by csz5667757** [apache/shardingsphere#21612]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by linghengqian** [comment]
- The master branch doesn't have its unit tests, but if it's just executing SQL92-related functions through the JDBC driver, this shouldn't be a problem.
