### ISSUE TITLE
Can Keep core/main API stable in a big version like 5.x.x？

### ISSUE THREAD

**Issue by Glowdable** [apache/shardingsphere#21614]
## Question

I upgraded our company's shardingjdbc twice.One is from 5.1.0 to 5.1.1,  the other is from 5.1.1 to 5.2.0.I am confused that many core/main APIs changed.For example,  DialectSchemaMetaDataLoader class,  YamlEngine package path, StandardShardingAlgorithm interface, ShardingSphereAlgorithmFactory.createAlgorithm and 
sharding config like StaticStrategy.
Can Keep core/main API stable in a big version like 5.x.x?
Or  do we have API change rules?

**Comment by RaigorJiang** [comment]
Hi @Glowdable ,
Thank you for your feedback. I'm sorry to say that with the rapid development of ShardingSphere, sometimes we have to make adjustments to the API. 
Currently, the version of ShardingSphere follows the `A.B.C` format.
- When the API remains compatible, we will upgrade the C version, such as: 5.1.0, 5.1.1 and 5.1.2. 
- When API incompatibilities arise, we upgrade B versions, such as 5.1.0 and 5.2.0.
- If the entire architecture changes drastically, we will upgrade the A version, such as 4.0.0 and 5.0.0.
