### ISSUE TITLE
tools to generate railroad diagrams for sql statment

### ISSUE THREAD

**Issue by tianhao960** [apache/shardingsphere#21616]
### Is your feature request related to a problem?
no

### Describe the feature you would like.
 railroad diagrams could show the possible options for a SQL statement as below. 
Compared to text representation, the visual diagrams give users an intuitive way to explore the grammar and discover features.

and we can develop a tool to generate the diagram and put it to the docs, that's will helpful.

![image](https://user-images.githubusercontent.com/1155952/196162406-9113666d-2010-4412-877d-c9f5da252156.png)

**Comment by strongduanmu** [comment]
Looks cool, let's start it.

**Comment by TeslaCN** [comment]
Do we really need MySQL syntax in our documents? I think users will not learn usage of MySQL from ShardingSphere.

**Comment by RaigorJiang** [comment]
I agree with @TeslaCN , ShardingSphere does not need to provide syntax descriptions for the multiple supported dialects.
ShardingSphere has its own DistSQL, and we also added a railroad diagram for the DistSQL syntax, please refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/storage-unit-definition/register-storage-unit/

**Comment by mlycore** [comment]
Agree with @TeslaCN and @RaigorJiang . IMO, since there is already provided railway diagrams for DistSQL, we should make it clear that if there are some differences with this enhancement.

**Comment by strongduanmu** [comment]
I think this work is meaningful. A mature distributed database should be able to describe the range of syntax it supports. For example, cockroachdb and tidb are compatible with postgresql and mysql, but they also provide sql syntax railway diagrams.

PostgreSQL sql grammar - https://www.cockroachlabs.com/docs/stable/sql-grammar.html.
TiDB sql grammar - https://docs.pingcap.com/zh/tidb/stable/sql-statement-add-column.
