### ISSUE TITLE
when cluster has two proxy nodes drop resource has problem

### ISSUE THREAD

**Issue by wzhj2326** [apache/shardingsphere#21626]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
start two proxy nodes (e.g proxy-01 、proxy-02) in cluster.
in proxy-01:
   add resource ds_0
   drop resource ds_0 ignore single tables;
but in proxy-02  ds_0 also exist

**Comment by zhaojinchao95** [comment]
@wzhj2326  Which your `ShardingSphere-Proxy` version?

**Comment by wzhj2326** [comment]
> 

5.2.1

**Comment by wzhj2326** [comment]
> 

5.2.1

**Comment by wzhj2326** [comment]
> @wzhj2326 Which your `ShardingSphere-Proxy` version?

@zhaojinchao95 5.2.1

**Comment by zhaojinchao95** [comment]
Thank you, i will check it.
