### ISSUE TITLE
org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment

### ISSUE THREAD

**Issue by hanlaotie666** [apache/shardingsphere#21638]
### Which version of ShardingSphere did you use?
4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
sql: select name from I_FIXEDNETWORKLTP where lower(name) in ('xx')
SQL query successfully

### Actual behavior
query error
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment

**Comment by TeslaCN** [comment]
4.1 is no longer maintained. Please upgrade to latest version.
