### ISSUE TITLE
Introduce `flatten-maven-plugin` for ShardingSphere

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21639]
Hi community,

Now the subproject `examples` has used the `flatten-maven-plugin` to reduce duplicate version declarations (since https://github.com/apache/shardingsphere/issues/13512). 
It is valuable, otherwise we still have to change a lot of version numbers during release (like this https://github.com/apache/shardingsphere/pull/21625)

Therefore, I am going to use `${revision}` to define the version number in the same way for ShardingSphere, to facilitate maintenance.

**Comment by TeslaCN** [comment]
If we did this, should we changing usage of `maven-release-plugin`?

**Comment by TeslaCN** [comment]
https://github.com/apache/shardingsphere/issues/15531

**Comment by RaigorJiang** [comment]
Hi @TeslaCN 
Thanks for your reminder, `maven-release-plugin` can help reduce the trouble in the release process, but in daily development, if I add a new module, I still have to add a displayed version number, which still has the risk of error.

I will investigate the possibility of using `flatten-maven-plugin` and `maven-release-plugin` together.

**Comment by TeslaCN** [comment]
Hi @RaigorJiang 
Please confirm the milestone of this issue.

**Comment by RaigorJiang** [comment]
> Hi @RaigorJiang Please confirm the milestone of this issue.

Hi @TeslaCN , It can't be finished soon, I just remove the milestone.

**Comment by RaigorJiang** [comment]
I think this issue is no longer necessary, I will close it.
