### ISSUE TITLE
ComplexKeysShardingAlgorithm not support '>='  '<=' '>' '<' 

### ISSUE THREAD

**Issue by xia10802481** [apache/shardingsphere#21645]
### Which version of ShardingSphere did you use?
4.0.0-RC2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
when complex shard column contains '>=' in sql,ComplexKeysShardingAlgorithm impl can accept this column in doSharding method ,complexKeysShardingValue params
### Actual behavior
can not accept this column
### Reason analyze (If you can)
i dont know
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL:
select * from people where age > 18 and sex =0 "
SpringBootConfig:
pring.shardingsphere.sharding.tables.xxtable-strategy.complex.sharding-columns = age,sex
spring.shardingsphere.sharding.tables.xx.table-strategy.complex.algorithm-class-name= com.demo.DateShardingAlgorithm
DateShardingAlgorithm:
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/13432288/196598058-7a332636-c3aa-429d-9b07-95ee6d0c9f96.png">
result:
![image](https://user-images.githubusercontent.com/13432288/196599750-715c90c5-e378-4b31-9874-ced82ab12e83.png)

cant receiver age params

**Comment by strongduanmu** [comment]
The version 4.x is too old, please try the latest 5.2.1 version.

**Comment by TeslaCN** [comment]
Close due to no response.
