### ISSUE TITLE
Can provide golang version of sharding-jdbc ？

### ISSUE THREAD

**Issue by DearWhite** [apache/shardingsphere#21656]
### Is your feature request related to a problem?
no
### Describe the feature you would like.
Can provide golang version of sharding-jdbc ？

**Comment by TeslaCN** [comment]
You may use the ShardingSphere-Proxy. Proxy could be used like a database.

**Comment by linghengqian** [comment]
- Do you mean to bind the Java API of ShardingSphere JDBC to the C API through `Project Panama`, and then call the C API to Golang? Could it be too early? But if you are already using JDK 19, I think you can give it a try.
- You just need to generate bindings with jextract first, load the library in the second, and call in the third. Ideally there isn't much C Language that needs to be written.

**Comment by DearWhite** [comment]
> * Do you mean to bind the Java API of ShardingSphere JDBC to the C API through `Project Panama`, and then call the C API to Golang? Could it be too early? But if you are already using JDK 19, I think you can give it a try.
> * You just need to generate bindings with jextract first, load the library in the second, and call in the third. Ideally there isn't much C Language that needs to be written.

I want to use it（go lib of ShardingSphere JDBC ） directly in the go service

**Comment by linghengqian** [comment]
- This is completely impossible if the GoLang community has no intention of dealing with it. Not all dependencies can find a replacement Golang lib, the typical ones are Groovy Shell and Calcite, how can we imagine that something like Groovy Shell exists in Golang Lib? Golang has never had such a powerful SQL parser as Calcite, LOL. 🤣

**Comment by DearWhite** [comment]
> You may use the ShardingSphere-Proxy. Proxy could be used like a database.
https://shardingsphere.apache.org/document/5.2.1/en/overview/
The overview document says  ShardingSphere-Proxy：" Relatively High loss", can you explain it?

**Comment by DearWhite** [comment]
> * This is completely impossible if the GoLang community has no intention of dealing with it. Not all dependencies can find a replacement Golang lib, the typical ones are Groovy Shell and Calcite, how can we imagine that something like Groovy Shell exists in Golang Lib? Golang has never had such a powerful SQL parser as Calcite, LOL. 🤣

LOL. 🤣

**Comment by linghengqian** [comment]
@DearWhite 
- FYI, under the governance of the truffle framework, within the same GraalVM Native Image, I can directly call some APIs of Apache ShardingSphere JDBC through Python, JavaScript, R, Ruby and Rust( LLVM ).  Here is part of the implementation of the peripheral issue of https://github.com/apache/shardingsphere/issues/21347 . 

- If you want to implement Golang with Truffle, you should submit some PR to https://github.com/oracle/graal/issues/381 .  

- Obviously, there are very few people using Golang, far less than the Truffle .Net proposal.
