### ISSUE TITLE
Encrypt 洗数状态优化

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#21651]
### Which version of ShardingSphere did you use?
b0741a7733a89f10f62c6844406c36eb029ad1f5
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy
### Expected behavior
洗数完成的最终状态均为 finished
### Actual behavior
![WmbqsWp57n](https://user-images.githubusercontent.com/86462784/196838972-002816d0-3001-4cd9-81bb-7015026a875d.jpg)

**Comment by RaigorJiang** [comment]
For English only.
