### ISSUE TITLE
miss java file ShardingSphereDataSourceFactory.java

### ISSUE THREAD

**Issue by showlist** [apache/shardingsphere#21663]
versoin 5.2.1 shardingsphere-jdbc-core-spring-boot-starter

will miss ShardingSphereDataSourceFactory

**Comment by linghengqian** [comment]
- What is the context of what you are expressing?  Why would you need ShardingSphereDataSourceFactory ?

**Comment by TeslaCN** [comment]
Here is what you are looking for.
https://github.com/apache/shardingsphere/blob/5.2.1/jdbc/core/src/main/java/org/apache/shardingsphere/driver/api/ShardingSphereDataSourceFactory.java
