### ISSUE TITLE
encrypt  insert field cannot be null!

### ISSUE THREAD

**Issue by zzzwjZhang** [apache/shardingsphere#21668]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/46548177/197112144-b34e9ea6-3f09-469d-bcd8-df85ede22c82.png">
in this method ,field value cannot be null or throw NullPointException,but null value could be handle in EncryptAlgorithm!

**Comment by TeslaCN** [comment]
Hi @zzzwjZhang 
Are you interested in investigating this issue?
