### ISSUE TITLE
[DistSQL] Change `SINGLE TABLE RULE` related syntax 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21672]
Hi community,

This issue is for #21659.

### Background
By default, when a user creates a single table, it is randomly routed to a storage unit, but we can route the user-created single table to the same unit through `CREATE DEFAULT SINGLE TABLE RULE`.

But before that, if the CREATE statement is not executed, the result of `SHOW SINGLE TABLE RULES` is an empty string, which does not match the actual situation of "RANDOM".

### Aim
Change `SINGLE TABLE RULE` related syntax , e.g.
- `CREATE DEFAULT SINGLE TABLE RULE RESOURCE = xx` -> `SET DEFAULT SINGLE TABLE STORAGE UNIT = xx`
- `ALTER DEFAULT SINGLE TABLE RULE RESOURCE` ->  REMOVE IT
- `DROP DEFAULT SINGLE TABLE RULE` -> `SET DEFAULT SINGLE TABLE STORAGE UNIT = RANDOM` (RANDOM is keyword)
- `SHOW SINGLE TABLE RULES` -> `SHOW DEFAULT SINGLE TABLE STORAGE UNIT`

**Comment by jiangML** [comment]
I'll try to do it

**Comment by RaigorJiang** [comment]
@jiangML Completed, thank you!
