### ISSUE TITLE
[DistSQL] Change keyword `RESOURCE` to `STORAGE UNIT`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21671]
Hi community,

This issue is for #21659.

### Background
Because the conceptual scope of `RESOURCE` is relatively large, here it actually just represents the unit used to store data, so the naming is adjusted.

At the same time, `ADD RESOURCE` does not `ADD` a new db, but register the physical db in the logical database for use, so `ADD` is also adjusted to `REGISTER`.

### Aim
Change keywords, e.g.
```
ADD RESOURCE -> REGISTER STORAGE UNIT
ALTER RESOURCE -> ALTER STORAGE UNIT 
DROP RESOURCE -> UNREGISTER STORAGE UNIT
SHOW DATABASE RESOURCES -> SHOW STORAGE UNITS
SHOW UNUSED RESOURCES -> SHOW STORAGE UNITS WHERE usage_count = 0
```

**Comment by jiangML** [comment]
I'll try to do it

**Comment by RaigorJiang** [comment]
@jiangML Completed, thank you!
