### ISSUE TITLE
[DistSQL] Optimize `DB_DISCOVERY` related syntax

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21697]
Hi community,

This issue is for #21659.

### Aim
Optimize `DB_DISCOVERY` related syntax.

#### Remove
- CREATE DB_DISCOVERY TYPE
- CREATE DB_DISCOVERY HEARTBEAT
- ALTER DB_DISCOVERY TYPE
- ALTER DB_DISCOVERY HEARTBEAT

#### Optimize
- CREATE DB_DISCOVERY RULE
- ALTER DB_DISCOVERY RULE
> After optimization, only supports synchronous creation of TYPE and HEARTBEAT

**Comment by Pace2Car** [comment]
I will work on it

**Comment by RaigorJiang** [comment]
@Pace2Car Thank you!

**Comment by RaigorJiang** [comment]
@Pace2Car Completed, thank you!
