### ISSUE TITLE
How tp implement batch encryption in ShardingSphere-JDBC_Encryption

### ISSUE THREAD

**Issue by tianshuainan** [apache/shardingsphere#21709]
How to customize the encryption algorithm to achieve batch encryption in ‘EncryptAlgorithm’ and  ‘QueryAssistedEncryptAlgorithm’ class

**Comment by gxxiong** [comment]
Your problem is that you won't extend the encryption algorithm?

**Comment by tianshuainan** [comment]
> 
i want to implement batch encrypt,but the provided interface can't resolve it

**Comment by gxxiong** [comment]
Encryption is performed one by one according to your SQL parameters. Why do you need batch encryption?
