### ISSUE TITLE
I always report an error when upgrading from 5.1.2 File mode to 5.2.1 JDBC mode

### ISSUE THREAD

**Issue by Zhai6319** [apache/shardingsphere#21703]
## Bug Report

mybatis plus 3.5.1 + shardingsphere 5.2.1 + druid 1.2.8

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/29478697/197388894-a9e64cf2-dbea-467b-a355-f6a92e4d10a5.png">

demo example：[[demo example](https://github.com/Zhai6319/sbx-system)](https://github.com/Zhai6319/sbx-system)

Please use the maven settings file under the maven directory of the project
<img width="626" alt="image" src="https://user-images.githubusercontent.com/29478697/197389162-29b01c02-f88a-45e2-9b51-e21a30bf7d57.png">

**Comment by Zhai6319** [comment]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/29478697/197389285-3c9c0b1c-b9ba-4dce-ae2c-c218a331b2b9.png">
I don't know if there is a problem with my configuration

**Comment by linghengqian** [comment]
- This issue is a duplicate of https://github.com/apache/shardingsphere/issues/21476 and should be marked as invalid and closed.  

- If you are using `SpringBoot OSS < 3.0.0-M5`, you need to specify the SnakeYAML version manually.

**Comment by Zhai6319** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/29478697/197392135-0e76f629-0a3e-4b34-a457-dc4ba6424a94.png">
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/29478697/197392151-51df21fc-cf70-4cd5-870e-c36a350af868.png">
I report this error after specifying the version

**Comment by linghengqian** [comment]
- ShardingSphere 5.2.0 slightly refactored the configuration of read-write separation on the client side.  A typical example of changes to upgrade from 5.1.2 to 5.2.0 should look something like https://github.com/dynamic-datasource/dynamic-datasource-samples/commit/dd7c1e99f75ec66d249af186661c57335bea03c1 .

- Without further ado, the link I quoted doesn't have much to do with ShardingSphere.  You should refer to the official documentation.

**Comment by Zhai6319** [comment]
Thank you for your help
