### ISSUE TITLE
[DistSQL] Optimize `SHARDING TABLE RULE` related syntax

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#21717]
Hi community,

This issue is for #21659.

#### Remove
- CREATE SHARDING ALGORITHM
- ALTER SHARDING ALGORITHM
- CREATE SHARDING KEY GENERATOR
- ALTER SHARDING KEY GENERATOR

#### Simplify
Simplify the following syntax, only supports synchronous creation algorithms.
- CREATE SHARDING TABLE RULE
- ALTER SHARDING TABLE RULE

#### Update
- SHARDING BINDING TABLE RULES -> SHARDING TABLE REFERENCE RULE

**Comment by Pace2Car** [comment]
I will work on it.

**Comment by RaigorJiang** [comment]
@Pace2Car  Completed, thank you !
