### ISSUE TITLE
Add unit test for ReflectiveUtil

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#21746]
This issue is to add unit tests for the ReflectiveUtil class and includes the following subtasks:

- [ ] ReflectiveUtil#getFieldValue
- [ ] ReflectiveUtil#setField
- [ ] ReflectiveUtil#setStaticField

**Comment by ishu-thakur** [comment]
Hi @strongduanmu I would like to contribute on this issue can you assign that to me :)?

**Comment by strongduanmu** [comment]
Welcome @ishu-thakur, I will assign this issue to you.

**Comment by pandaapo** [comment]
?

**Comment by pandaapo** [comment]
? Does it mean that my PR before this assignment will be ignored directly?

**Comment by ishu-thakur** [comment]
@strongduanmu @sandynz Please review the PR #21778 that i have raised as per the issue #21746 :) and if any changes required i will be doing that .

**Comment by strongduanmu** [comment]
Hi @pandaapo, thank you very much for your contribution, but the habit of the ShardingSphere community is to claim the issue first, and then submit the PR. We have many other unclaimed issues and contributions are welcome.

**Comment by strongduanmu** [comment]
@pandaapo Do you want to fix issue #21775?
