### ISSUE TITLE
How can I refresh the sharding-rules

### ISSUE THREAD

**Issue by wangyu3619** [apache/shardingsphere#21740]
## Question

How can I refresh the sharding-rules when I need a dynamicsharding-tables rule.For example, I need tables for the last seven days, one table for each day.
shardingsphere-jdbc-core-spring-boot-starter 5.2.0

**Comment by RaigorJiang** [comment]
Hello @wangyu3619 , 
It is recommended to use `DistSQL` for dynamic management rules. If the application uses `JDBC` access, it needs to be deployed with `Proxy` for hybrid architecture.

- [DistSQL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/)
- [Hybrid Architecture](https://shardingsphere.apache.org/document/current/en/overview/#hybrid-architecture)
