### ISSUE TITLE
[SQLLogger] SQLStatement log

### ISSUE THREAD

**Issue by smartbetter** [apache/shardingsphere#21764]
## Feature Request

Hi，I don't need a SQLStatement, SQLStatement prints too much.

Can you add a switch to the SQLStatement of SQLLogger to control whether to print?

**Comment by strongduanmu** [comment]
You can use `sql-show: false` to close sql print.

**Comment by smartbetter** [comment]
> You can use `sql-show: false` to close sql print.

No, I need print Logic SQL and Actual SQL.

**Comment by RaigorJiang** [comment]
How about change the level of `SQLStatement` to debug?

**Comment by smartbetter** [comment]
> How about change the level of `SQLStatement` to debug?

I think so.

**Comment by RaigorJiang** [comment]
@smartbetter Are you interested in submitting this change？

**Comment by smartbetter** [comment]
> @smartbetter Are you interested in submitting this change？

@RaigorJiang Yes, But I think add a switch to the SQLStatement of SQLLogger to control whether to print, That's better

**Comment by smartbetter** [comment]
> @smartbetter Are you interested in submitting this change？

submitting pull request？

**Comment by RaigorJiang** [comment]
> > @smartbetter Are you interested in submitting this change？
> 
> submitting pull request？

Yes, Pull Request.

**Comment by smartbetter** [comment]
To new issues: https://github.com/apache/shardingsphere/issues/22453

**Comment by RaigorJiang** [comment]
Removed in #22453.
