### ISSUE TITLE
How to set default system database

### ISSUE THREAD

**Issue by miaoyinjun** [apache/shardingsphere#21767]
shardingsphere.version: 5.2.1
How to set ShardingSphere default system database to support global metadata management?

**Comment by RaigorJiang** [comment]
@miaoyinjun  There is currently no such function.
ShardingSphere will provide logical system databases like `information_schema`, this feature is under development

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I'm closing it now.
