### ISSUE TITLE
Are you cheating? What the hell are you doing?

### ISSUE THREAD

**Issue by judykula** [apache/shardingsphere#21784]
![image](https://user-images.githubusercontent.com/3365786/198185844-2564fb35-eac9-494c-8c15-7b753db7ff24.png)
![image](https://user-images.githubusercontent.com/3365786/198185882-4619f107-7914-46ef-9842-f5d430e1bc59.png)
![image](https://user-images.githubusercontent.com/3365786/198185921-bc0fce9a-7850-44d6-b9ce-ab9839cb0ac1.png)
![image](https://user-images.githubusercontent.com/3365786/198186861-e7489b5f-da84-4826-a612-4e5825294c66.png)
![image](https://user-images.githubusercontent.com/3365786/198186913-f46218c9-2fe4-4340-b1e1-620cee9ac18a.png)

Can you be more responsible?

**Comment by strongduanmu** [comment]
@judykula First of all, please pay attention to your words and deeds, we welcome good advice, not accusation.

**Comment by strongduanmu** [comment]
Second, before asking questions, please read ShardingSphere's documentation and existing issues carefully. To use the Consul registry, you need to add dependencies yourself. For specific reference: https://shardingsphere.apache.org/document/5.2.1/cn/user-manual/shardingsphere-proxy/optional-plugins/

**Comment by strongduanmu** [comment]
Third, currently only the Zookeeper registry is the main task. ShardingSphere will ensure that its functions are complete. Other implementations need to be led by the community itself. As you have shown, some of the unimplemented methods of the Consul registry need to be continuously improved by the community.

**Comment by strongduanmu** [comment]
Since you are not participating in accordance with the ShardingSphere community's specifications, I will set this issue as invalid. Welcome to submit a new issue to discuss how to improve the Consule registry.

**Comment by judykula** [comment]
@strongduanmu 没有完成的功能请明确在版本特征里进行提示。做到任何一个环节都要严谨，才能给选用Shardingsphere作为数据库底层proxy的技术负责人以信心，而不是满足自洽性就可以，这更像是满足老板的要求，而不是用户。

选择刚开始的Shardingsphere 5作为proxy是因为信任，但是现在Shardingsphere已经快把我的脸给打肿了，我取消了对Shardingsphere的点赞，抱歉。
