### ISSUE TITLE
mybatis-plus3.5.2、shardingsphere5.1.1（Using encrypt）、oracle，When querying by page,rewirte sql is error, regards the ROWNUM as a real field, but it is not

### ISSUE THREAD

**Issue by zhang-zhipeng** [apache/shardingsphere#21799]
### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
mybatis-plus3.5.2、shardingsphere5.1.1、oracle.
When querying by page, the sql of the queried field name has no concatenated quotation marks.
I found that the latest version of OracleDataType also uses QuoteCharacter.QUOTE, which still causes the rewritten sql to be quoted.
### Actual behavior
When querying by page, the sql of the queried field name is spliced with quotation marks, resulting in an error in the query. ORA-00904: "update_time": the ID is invalid

**Comment by zhang-zhipeng** [comment]
Encrypt function is used

**Comment by zhang-zhipeng** [comment]
Logic SQL: 
SELECT * FROM (SELECT TMP.*, ROWNUM ROW_ID FROM (SELECT ID, NAME, PWD, MOBILE, CUSTOMER_ID, CREATE_TIME, UPDATe_TIME, FROM T_CIPHER_OLD WHERE (ID = ?) ) TMP WHERE ROWNUM <= ?) WHERE ROW_ID > ?

ACTUAL SQL：
SELECT "ID", "NAME", "PWD_CIPHER" AS "PWD", "MOBILE", "CUSTOMER_ID", "CREATE_TIME", "UPDATE_TIME", "ROWNUM" AS "ROW_ID" FROM ( SELECT "ID", "NAME", "PWD_CIPHER", "MOBILE", "CUSTOMER_ID", "CREATE_TIME", "UPDATE_TIME", ROWNUM AS ROW_ID FROM (SELECT SELECT ID, NAME, PWD, MOBILE, CUSTOMER_ID, CREATE_TIME, UPDATe_TIME, FROM T_CIPHER_OLD WHERE (ID = ?) ) TMP WHERE ROWNUM <= ?) WHERE ROW_ID > ?

The "ROWNUM" AS "ROW_ID" in ACTUAL SQL regards the ROWNUM as a real field, but it is not

**Comment by zhang-zhipeng** [comment]
If all field queries do not splice quotation marks, or ROWNUM does not splice quotation marks, SQL is correct

**Comment by strongduanmu** [comment]
Hi @zhang-zhipeng, thank you for your feedback. Can you show your encrpt configuration and table init sql?

**Comment by zhang-zhipeng** [comment]
encrypt config：
rules:
      encrypt:
        encryptors:
          pwd-encryptor:
            type: AES
            props:
              aes-key-value: 123456abc
        tables:
          T_CIPHER_OLD:
            columns:
              PWD:
                cipher-column: PWD_CIPHER
                encryptor-name: pwd-encryptor

create table sql:
CREATE TABLE "T_CIPHER_OLD"
(
	"ID" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(255),
	"CREATE_TIME" TIMESTAMP(6),
	"UPDATE_TIME" TIMESTAMP(6),
	"MOBILE" VARCHAR2(100),
	"PWD_CIPHER" VARCHAR2(100),
	"CUSTOMER_ID" VARCHAR2(100),
	PRIMARY KEY("ID")
)

**Comment by zhang-zhipeng** [comment]
Entity：
@Data
@TableName(value = "T_CIPHER_OLD")
public class CipherOld implements Serializable {
    @TableId(value = "ID")
    private Long id;
    @TableId(value = "NAME")
    private String name;
    @TableId(value = "PWD")
    private String pwd;
    @TableId(value = "MOBILE")
    private String mobile;
    @TableId(value = "CUSTOMER_ID")
    private Long customerId;
    @TableId(value = "CREATE_TIME")
    private Date createTime;
    @TableId(value = "UPDATE_TIME")
    private Date updateTime;
}

**Comment by zhang-zhipeng** [comment]
@strongduanmu  Will it be fixed in the latest version？

**Comment by strongduanmu** [comment]
> function

@zhang-zhipeng Thank you for your remind, I will check this issue today.

**Comment by strongduanmu** [comment]
Hi @zhang-zhipeng, shardingsphere can not support shorthand expand when subuqery contains encrypt column, you can try to modify shorthand to columns. 

For more details, you can refer - https://shardingsphere.apache.org/document/current/en/features/encrypt/appendix/
