### ISSUE TITLE
JDBC连接OceanBase数据库选择连接模式的问题

### ISSUE THREAD

**Issue by Zx07** [apache/shardingsphere#21802]
使用sharing-jdbc连接OceanBase数据库时，jdbc自动生成了mysql的SQL去查表的索引。但是我的OceanBase租户是oracle模式的，这必然会报错。
       然后我把pom里所有有mysql关键字的依赖都给去掉，包括sharing-jdbc里的也去掉了。但是还是会自动拼出mysql的SQL去查索引，请问这个有什么办法可以指定jdbc拼的SQL为oracle模式吗？

**Comment by zhaojinchao95** [comment]
@Zx07  **For English only**, other languages will not accept.
