### ISSUE TITLE
Error occur when batch inserting rows into proxy !

### ISSUE THREAD

**Issue by MaricoHan** [apache/shardingsphere#21818]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Hi, when I batch insert  data into  the table through ShardingSphere-proxy-v5.2.1，I will be prompted with the following exception. However ,it is normal to directly insert into the table without the proxy.** 
---
Did I configure something wrong ?  HELP ~

**Note: I have tried to increase the value of sqlStatementCache in server.yaml**

```java
2022/10/28 04:00:46 - ERROR (version 9.3.0.0-428, build 9.3.0.0-428 from 2022-04-12 04.56.25 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2022/10/28 04:00:46 -  Error batch inserting rows into table [t_accounts].
2022/10/28 04:00:46 - Errors encountered (first 10):
2022/10/28 04:00:46 - 
2022/10/28 04:00:46 - 
2022/10/28 04:00:46 - Error updating batch
2022/10/28 04:00:46 - Parameter index out of bounds. 60177 is not between valid values of 1 and 60176
2022/10/28 04:00:46 - 
2022/10/28 04:00:46 -
2022/10/28 04:00:46 -         at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:348)
2022/10/28 04:00:46 -         at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow(TableOutput.java:125)
2022/10/28 04:00:46 -         at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2022/10/28 04:00:46 -         at java.lang.Thread.run(Thread.java:750)
2022/10/28 04:00:46 - Caused by: org.pentaho.di.core.exception.KettleDatabaseBatchException: 
2022/10/28 04:00:46 - Error updating batch

```

**Comment by RaigorJiang** [comment]
@MaricoHan 
Please provide your configuration and executed SQL statement that can help reproduce the issue

**Comment by TeslaCN** [comment]
Duplicate with #17166.
