### ISSUE TITLE
Does the shard key support like

### ISSUE THREAD

**Issue by wangjiihao** [apache/shardingsphere#21810]
Does the partition key support querying in the like mode and How to use it if it supports

**Comment by wangjiihao** [comment]
@TeslaCN

**Comment by wangjiihao** [comment]
example:
     select * from user where name like '王%'
name is the shard key

**Comment by wangjiihao** [comment]
version: shardingsphere-jdbc-core-spring-boot-starter 5.0.0

**Comment by RaigorJiang** [comment]
@wangjiihao 
Sharding key just supports `=` or range (`>`, `>=`, `<`, `<=`, `between`)

**Comment by wangjiihao** [comment]
@RaigorJiang  
Can I customize a like routing rule? By implementation or inheritance

**Comment by wangjiihao** [comment]
When querying shard fields, I need to use the like method, because there is a parent-child relationship between data similar to the codes of provinces and cities, and provinces and cities have a unified prefix

**Comment by RaigorJiang** [comment]
Unfortunately, in the sharding scenario, there is currently no interface to implement `LIKE`.
