### ISSUE TITLE
Unknown prepared statement handler (4) given to mysqld_stmt_reset

### ISSUE THREAD

**Issue by codeducker** [apache/shardingsphere#21821]
execute sql return Unknown prepared statement handler (4) given to mysqld_stmt_reset

**Comment by codeducker** [comment]
using spring boot 2.6 + mybatis-plus 3.5.2 + sharingsphere-jdbc 5.2.1

**Comment by RaigorJiang** [comment]
Hi @codeducker,
Thanks for your feedback, please provide your logic SQL and configuration, what is the best way to reproduce this problem.

**Comment by codeducker** [comment]
I have change the version of shardingsphere and the default datasource ,then i fixed the problem above
