### ISSUE TITLE
Sharing-JDBC does not support the Oracle tenant of OceanBase database

### ISSUE THREAD

**Issue by Zx07** [apache/shardingsphere#21835]
When sharing jdbc is used to connect to OceanBase database, jdbc automatically generates MySQL SQL to query the table index. However, my OceanBase tenant is in Oracle mode, which will inevitably report an error.
Then I removed all dependencies on MySQL dependency in the pom, including those in sharing jdbc. However, MySQL SQL will be automatically spelled out to query the index. Is there any way to specify the SQL spelled by jdbc as oracle mode?

**Comment by strongduanmu** [comment]
Hi @Zx07, can you provide a demo to help demonstrate the problem?

**Comment by Zx07** [comment]
@strongduanmu my demo:

**Comment by Zx07** [comment]
@strongduanmu my demo:
![image](https://user-images.githubusercontent.com/51987374/199034032-6ef5c829-a319-4d74-925f-98d98ed9445a.png)

**Comment by Zx07** [comment]
This is my config
![image](https://user-images.githubusercontent.com/51987374/199035133-aed05511-e7bc-484f-9869-423e2aaf8581.png)

**Comment by Zx07** [comment]
![image](https://user-images.githubusercontent.com/51987374/199035267-48b52109-78a3-43da-a496-d1c76fecb7b1.png)

**Comment by TeslaCN** [comment]
It seems that your configuration is not ShardingSphere 5.x. The legacy version is no longer maintained. Please upgrade to latest version.
