### ISSUE TITLE
Does sharding proxy support sharding+readwrite at the same time?

### ISSUE THREAD

**Issue by hza2022x** [apache/shardingsphere#21856]
We plan to use 8 mysql instances, 4 databases in each instance and 16 tables in each database. total tables is: 8 * 4 * 16 = 512
At the same time, each mysql instance has a backup and  a slave. When the master is down, the backup will take over it.
So total mysql instances is: 8 *3 = 24.
Does sharding proxy support sharding+readwrite at the same time?

**Comment by strongduanmu** [comment]
Of course, the features provided by ShardingSphere can be used together. You can refer https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/mix/.

**Comment by hza2022x** [comment]
Great !
Which version support this feature? Does 5.0.0 support it?

**Comment by strongduanmu** [comment]
> Great ! Which version support this feature? Does 5.0.0 support it?

You can try the latest 5.2.1 version.

**Comment by hza2022x** [comment]
Ok. Many thanks

**Comment by RaigorJiang** [comment]
Close because it has been resolved.

**Comment by djmirv** [comment]
> Close because it has been resolved.

In which version solved?

**Comment by djmirv** [comment]
> Close because it has been resolved.

Cuz i tried the 5.1.0. And it doesn't work.
