### ISSUE TITLE
Unregister multiple migration source storage units, when one unexist exception all storage units mentioned in the statement unexist.

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#21867]
### Which version of ShardingSphere did you use?
85abe604471c44867a50a3fc3c825f61fbe99826
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy
### Expected behavior
Unregister multiple migration source storage units, when one unexist exception the unexist one unexist.
### Actual behavior
Unregister multiple migration source storage units, when one unexist exception all storage units mentioned in the statement unexist.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Register migration source storage unit
```sql
REGISTER MIGRATION SOURCE STORAGE UNIT su_0 (
    URL="jdbc:mysql://127.0.0.1:3306/migration_ds_0?serverTimezone=UTC&useSSL=false",
    USER="root",
    PASSWORD="123456",
    PROPERTIES("minPoolSize"="1","maxPoolSize"="20","idleTimeout"="60000")
);
```
2. Unregister multiple migration source storage unit
```sql
UNREGISTER MIGRATION SOURCE STORAGE UNIT su_0, su_1;
```
### Screen shot
<img width="643" alt="image" src="https://user-images.githubusercontent.com/57847965/198995483-5c1b5463-635f-44f8-81a8-48bbe883bb84.png">

**Comment by RaigorJiang** [comment]
Hi @Qianyi951015 ,
Thanks for your feedback, do you want to fix it?

**Comment by Qianyi951015** [comment]
> Hi @Qianyi951015 , Thanks for your feedback, do you want to fix it?

Sure
