### ISSUE TITLE
The index appends the current table name problem when the DDL statement is executed

### ISSUE THREAD

**Issue by bravelionet** [apache/shardingsphere#21886]
Community hello
When a new table is created by executing ddl using the data source, the current table name is appended to the index. Ensure that no table name is appended to the index in the current DDL. Debugging found no problems

mysql-connector-java -> 8.0.25

dynamic-datasource-spring-boot-starter  -> 3.5.1 

shardingsphere-jdbc-core-spring-boot-starter -> 5.1.2

The following DDL simplification
The order base 202212 is appended to the index

`CREATE TABLE if not exists order_base_202212 (
  `pu_id` bigint(20) NOT NULL COMMENT 'id',
  `order_no` varchar(36) NOT NULL COMMENT ''
  PRIMARY KEY (`pu_id`) USING BTREE,
  UNIQUE KEY `order_no` (`order_no`) USING BTREE,
  KEY `biz_order_appId_bizCode_system_code` (`biz_order_no`,`biz_app_id`,`biz_code`) USING BTREE,
  KEY `original_appId_bizcode` (`original_order_no`,`biz_app_id`,`biz_code`) USING BTREE,
  KEY `transaction_type` (`type`,`trade_type`,`trade_type_tag`),
  KEY `work_flow_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='' 

CREATE TABLE `order_base_202212` (
  `pu_id` bigint(20) NOT NULL COMMENT 'id',
  `order_no` varchar(36) NOT NULL COMMENT '订单号码'
  PRIMARY KEY (`pu_id`) USING BTREE,
  UNIQUE KEY `order_no_order_base_202212` (`order_no`) USING BTREE,
  KEY `biz_order_appId_bizCode_system_code_order_base_202212` (`biz_order_no`,`biz_app_id`,`biz_code`) USING BTREE,
  KEY `original_appId_bizcode_order_base_202212` (`original_order_no`,`biz_app_id`,`biz_code`) USING BTREE,
  KEY `transaction_type_order_base_202212` (`type`,`trade_type`,`trade_type_tag`),
  KEY `work_flow_state_order_base_202212` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';`

**Comment by RaigorJiang** [comment]
@bravelionet 
This is the design, because there may be multiple tables in a data source in sharding scenario, and the index names cannot be repeated.
