### ISSUE TITLE
Get the sql executed on the current connection of sharding-proxy

### ISSUE THREAD

**Issue by bojiw** [apache/shardingsphere#21885]
Currently want to get the sql executed before the current connection in the rewrite module

**Comment by RaigorJiang** [comment]
Hi @bojiw 
It's not clear what your intention is from your description, please provide a valid message through the issue template.

**Comment by bojiw** [comment]
There is currently a function that requires secondary development of sharding-proxy
Demand content：
After receiving the select last_insert_id() sql, need to rewrite the sql with the name of the table to be queried

At present, it is considered to save the table name as the current connection id when executing insert, and then obtain the table name saved by insert through the current connection id when executing select last_insert_id().

I want to determine whether the current sharding-proxy is using the same connection when the business executes insert and then executes select last_insert_id. If so, where is it appropriate to implement the operation just now?

**Comment by bojiw** [comment]
Hi @RaigorJiang

**Comment by RaigorJiang** [comment]
Hi @bojiw 
I'm not very clear, maybe this issue can help you #17942
