### ISSUE TITLE
shardingjdbc读写分离和分库分表是否也可同时配置？

### ISSUE THREAD

**Issue by Andrew-Yang999** [apache/shardingsphere#21897]
版本：3.0.0.M3
疑惑点：io.shardingsphere.jdbc.spring.boot.SpringBootConfiguration#dataSource 
![image](https://user-images.githubusercontent.com/44202153/199245601-7326e44f-8f84-41b9-bff9-86bb1d0f83ee.png)
SpringBootConfiguration创建bean的时候，发现masterSlaveProperties与shardingProperties的配置是互斥的。
那么项目里面有部分表是需要分表的，其他表需要读写分离在shardingjdbc有使用方式吗？

**Comment by djmirv** [comment]
同样有疑惑
