### ISSUE TITLE
Use break-word rather than break-all in English

### ISSUE THREAD

**Issue by BryanYin** [apache/shardingsphere#21903]
Could you please check if `word-break:break-word` is better than `break-all` in below line for providing better readability?

https://github.com/apache/shardingsphere/blob/aec92754f9519e573a8eb4415fcd3122e4a604e1/docs/document/static/css/theme-white.css#L339

Current:
![image](https://user-images.githubusercontent.com/25950822/199391568-03e39ad9-a6de-412c-a928-f101fe648841.png)

After change:
![image](https://user-images.githubusercontent.com/25950822/199391635-c64f82c9-29cd-4e4e-a85e-e54fafef8d98.png)

**Comment by Swastyy** [comment]
This issue is already there as #21474

**Comment by BryanYin** [comment]
close as duplicate.
