### ISSUE TITLE
Can metadata be loaded only when used? If read/write separation is used alone, metadata does not need to be loaded

### ISSUE THREAD

**Issue by 794086163** [apache/shardingsphere#21914]
## Question

Can metadata be loaded only when used? If read/write separation is used alone, metadata does not need to be loaded

I have thousands of tables, but only use read and write separation, loaded useless metadata, resulting in a waste of space, can you add a switch configuration, control whether to load metadata, or automatically according to whether the use of the function involves metadata to load

**Comment by terrymanu** [comment]
No, metadata is the kernel of ShardingSphere, it will be used everywhere.
