### ISSUE TITLE
Refactor github action to make it more efficient

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#21934]
- [ ] merge reusable workflow
- [x] reduce the duplicated actions or move the low preority test to nightly build 
- [x] add mannually trigger to workflow
- [x] build docker image through commit it, not pending nightly build

**Comment by TeslaCN** [comment]
Is there any detail about this issue? I wonder how?

**Comment by TeslaCN** [comment]
GitHub Action is not included in release. I'm removing milestone.
