### ISSUE TITLE
Nightly IT Example Generator workflow could be improved

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#21943]
Currently, Nightly IT Example Generator workflow has some problems:

1, Job has no timeout, there's [job]( https://github.com/apache/shardingsphere/actions/runs/3388544928/jobs/5630665471 ) cost more than 4 hours and it's still running:
<img width="1039" alt="图片" src="https://user-images.githubusercontent.com/42492540/199869152-c44ce51d-ab59-4e50-9929-2363dae4a23b.png">

2, There're much failed jobs

3, There're `104` [jobs]( https://github.com/apache/shardingsphere/actions/runs/3388544928 ), every job might cost several minutes on `Build with Maven` (e.g. 5/7/8 minutes).

**Comment by sandynz** [comment]
Hi @totalo , could you help to have a look at it when you have time?

**Comment by totalo** [comment]
> Hi @totalo , could you help to have a look at it when you have time?

Ok，I‘ll follow up.
