### ISSUE TITLE
Insert statement does not support sharding table routing to multiple data nodes.

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#21953]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1 (5.2.2-SNAPSHOT has the same problem)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
1. Why do we have ds_1 here?
![image](https://user-images.githubusercontent.com/28882195/199908654-5f21cf85-fc9e-4caa-9251-1acbc212aaef.png)

2. Why do we have ds_0 here?
![image](https://user-images.githubusercontent.com/28882195/199908739-d76b472b-cedf-4b1e-842e-9c41600ead19.png)

3. An insert error occurred
![image](https://user-images.githubusercontent.com/28882195/199908829-3e9c83ef-d32c-4716-8f27-0b9feacd777c.png)

### Example codes for reproduce this issue (such as a github link).
https://github.com/apache/shardingsphere/blob/5.2.1/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/sharding/raw/jdbc/ShardingSQLCommentHintRawExample.java

**Comment by strongduanmu** [comment]
@doveylovey Please refer this issue #18620.

**Comment by linghengqian** [comment]
- It seems that for the keyGenerators of the primary key of the table is the example of SNOWFLAKE, the capabilities provided by https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/ cannot handle it. 
- So, what should be the direction of change for this example?

**Comment by RaigorJiang** [comment]
This is because the comment API of hint sql have been adjusted, resulting in the hint not taking effect.
Now #23189 restores this ability, please try the latest version.
