### ISSUE TITLE
No implementation class load from SPI `org.apache.shardingsphere.mode.repository.standalone.StandalonePersistRepository` with type `H2`.

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#21955]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1 (5.2.2-SNAPSHOT has the same problem)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Actual behavior
![image](https://user-images.githubusercontent.com/28882195/199919801-08781ab8-8d25-4b1e-b1a5-6514a3f41825.png)

### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/28882195/199919716-e02a8bc5-35e8-4721-ad11-abc6bed22b37.png)

### Example codes for reproduce this issue (such as a github link).
https://github.com/apache/shardingsphere/blob/5.2.1/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/java/org/apache/shardingsphere/example/sharding/raw/jdbc/ShardingRawJavaConfigurationExample.java

**Comment by magegoofy** [comment]
@doveylovey Are you interested in solving this problem?

**Comment by doveylovey** [comment]
> @doveylovey Are you interested in solving this problem?
Of course

**Comment by magegoofy** [comment]
@doveylovey welcome

**Comment by RaigorJiang** [comment]
The example module has been adjusted, and now the generator generates sample code, so this issue no longer needs to be dealt with.
Thank you all!

**Comment by RaigorJiang** [comment]
Ref: https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-example-generator
