### ISSUE TITLE
Consider researching and supporting column unsigned metadata for different databases

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#21954]
### Is your feature request related to a problem?

#21894
#15782

### Describe the feature you would like.

At present, the dateType of the field is stored in the ShardingSphere metadata. When SQL Federation is initialized, the Java type of the field will be initialized according to the dateType. In the JDBC specification, the mapping relationship between JDBC Type and Java Type is declared, but there will be differences in database implementation. For example, MySQL supports UNSIGNED, which will cause the Java Type and specification of JDBC Type mapping to be different.

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/10829171/199914090-e7723333-1fbb-43be-84dd-7c6093fdd5a2.png">

```java
/**
 * ShardingSphere column.
 */
@RequiredArgsConstructor
@Getter
@EqualsAndHashCode
@ToString
public final class ShardingSphereColumn {
    
    private final String name;
    
    private final int dataType;
    
    private final boolean primaryKey;
    
    private final boolean generated;
    
    private final boolean caseSensitive;
    
    private final boolean visible;
    
    private final boolean unsigned;
}
```

- [x] MySQL unsigned column(support——https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html)
- [x] PostgreSQL unsigned column (not support https://www.postgresql.org/docs/current/datatype.html https://stackoverflow.com/questions/20810134/why-unsigned-integer-is-not-available-in-postgresql )
- [x] openGauss unsigned column (not support https://docs.opengauss.org/zh/docs/3.1.0/docs/Developerguide/%E6%95%B0%E5%80%BC%E7%B1%BB%E5%9E%8B.html )
- [x] Oracle unsigned column  (not support https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements001.htm#i45441 https://stackoverflow.com/questions/16338044/oracle-sql-unsigned-integer )
- [x] SQLServer unsigned column (not support https://sql-bits.com/creating-unsigned-columns-in-sql-server/ https://learn.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-ver16 )
- [x] H2 unsigned column  (not support https://www.h2database.com/html/datatypes.html  https://github.com/h2database/h2database/issues/739 )

**Comment by strongduanmu** [comment]
Ref https://github.com/apache/shardingsphere/issues/19580.

**Comment by MaricoHan** [comment]
Hi @strongduanmu ,It is not only caused by unsigned, but also by signed tinyint: https://github.com/apache/shardingsphere/issues/15782

**Comment by strongduanmu** [comment]
> Hi @strongduanmu ,It is not only caused by unsigned, but also by signed tinyint: #15782

Yes, I know, unsigned types can cause similar problems. So we need to add such a field.

**Comment by dongzl** [comment]
Hi @strongduanmu, I want to try it.

**Comment by strongduanmu** [comment]
Thank you very much for your research, I will close this issue.
