### ISSUE TITLE
Deadlock issue in CONNECTION_STRICTLY mode

### ISSUE THREAD

**Issue by xiamenmin** [apache/shardingsphere#21964]
## Question
When I use the cCONNECTION_STRICTLY mode, I have the problem of getting database connections and waiting for each other in a concurrent scenario.

###  Business scene
- The current data is divided into 10 tables, and when I configure maxConnectionSizePerQuery = 5, and the instantaneous concurrency is > 8, the following problems will occur

### Configuration
- MaxActive = 15
- MaxWait = 60_000
- max.connections.size.per.query = 5
- DruidDataSource
- Version: apache-shardingsphere-jdbc-4.1.1

I add comments to the source code
``` java
package org.apache.shardingsphere.shardingjdbc.jdbc.adapter;

public abstract class AbstractConnectionAdapter extends AbstractUnsupportedOperationConnection {
 private List<Connection> createConnections(final String dataSourceName, final DataSource dataSource, final int connectionSize) throws SQLException {
        List<Connection> result = new ArrayList<>(connectionSize);
        for (int i = 0; i < connectionSize; i++) {
            try {
                System.out.println("Connections name:" + Thread.currentThread().getName() + "dataSourceName:" + dataSourceName + " progress:" + result.size() + "/" + connectionSize);
               ....
        }
        return result;
    }
}
```

### Running result log
... key log
Connections name:ForkJoinPool.commonPool-worker-13 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-9 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-8 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-15 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-11 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-10 dataSourceName:cmc progress:1/5
Connections name:ForkJoinPool.commonPool-worker-6 dataSourceName:cmc progress:4/5

### Problems
- Wait for each other to get the connection  from pool
- maxWait timeout

### Error Log
... key log
Could't get 5 connections one time, partition succeed connection(1) have released!
 Could't get 5 connections one time, partition succeed connection(4) have released!

**Comment by sandynz** [comment]
Hi @xiamenmin , looks you're running version 4.1.1, could you try version 5.3.0?

**Comment by zhaojinchao95** [comment]
> Hi @xiamenmin , looks you're running version 4.1.1, could you try version 5.3.0?

Next version, thx

**Comment by xiamenmin** [comment]
Ok, let me try

**Comment by sandynz** [comment]
@xiamenmin thanks for your demo. Suggest to create a new repository to write the demo, but not in ShardingSphere repository, it might take long time to download it.

**Comment by xiamenmin** [comment]
ok i have updated
