### ISSUE TITLE
Filter out cases that are expected to fail for dynamic load SQL parser test cases

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#22034]
## Feature Request

Now, we have dynamic load SQL parser test. 
https://github.com/apache/shardingsphere/blob/master/test/integration-test/sql-parser/src/test/java/org/apache/shardingsphere/sql/parser/base/DynamicLoadingSQLParserParameterizedTest.java

This can get test cases from mysql/postgres/openGauss.
But some case is expected to parse failed. These test cases should be filtered.
For example this.
![image](https://user-images.githubusercontent.com/86938616/200785241-8f1be864-1762-4010-ba30-e255f45b8052.png)

**Comment by Jacob953** [comment]
Fixed on https://github.com/apache/shardingsphere/pull/22100/files#diff-cb0bb54ec24509f2bcc14b1b7dee80e496568d055fd1160eeaf617c32787cd9f
