### ISSUE TITLE
when encrypt data is null ,queryAssistedEncrypt method of QueryAssistedEncryptor  not execute cause error

### ISSUE THREAD

**Issue by tianshuainan** [apache/shardingsphere#22049]
In ShardingSphere-JDBC 4.1.1, I implemented SPI QueryAssistedEncryptor. If multiple parameters contain null values, queryAssistedEncrypt() method is not executed, causing internal error.
configuration as below:
`spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.plainColumn=requester_email
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.cipherColumn=requester_email_cipher
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.assistedQueryColumn=requester_email_assisted
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_email.encryptor=queryassistedencryptor

spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.plainColumn=requester_name
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.cipherColumn=requester_name_cipher
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.assistedQueryColumn=requester_name_assisted
spring.shardingsphere.encrypt.tables.dsr_request.columns.requester_name.encryptor=queryassistedencryptor
`
when requestName is null, it will report bug,and queryAssistedEncrypt() method not execute  , and cause error
`{
"requesterEmail": "550736273@qq.com"
}`

**Comment by strongduanmu** [comment]
Hi @tianshuainan, thank you for your feedback. We have fixed this bug in master branch, can you try to test it?

**Comment by tianshuainan** [comment]
非常感谢！可以提供更多细节吗？在哪个包、类下面？有具体的例子吗？再次感谢，这对我帮忙很大，也非常重要

**Comment by tianshuainan** [comment]
Thank you very much! Can you provide more details? Under which package, class? Are there any specific examples? Thank you again. This has been very helpful and important

**Comment by strongduanmu** [comment]
Fixed by #21864.
