### ISSUE TITLE
sql retry

### ISSUE THREAD

**Issue by wangyf1024** [apache/shardingsphere#22056]
i use shardingsphere 5.1.2.
![image](https://user-images.githubusercontent.com/31696437/201023889-2365bdd2-ffa8-4b31-9dfa-317147781d55.png)
![image](https://user-images.githubusercontent.com/31696437/201024554-fa70a755-2ce7-4920-9acd-9c6997635e6c.png)
![image](https://user-images.githubusercontent.com/31696437/201024668-5524b9e4-adf5-41ba-8571-3701c3fc14c2.png)
sql execute two

**Comment by TeslaCN** [comment]
Could you provide your configuration and more logs? We can hardly figure out problem by these pictures.

**Comment by wangyf1024** [comment]
> o

mysql 8.0.28 Transaction cannot be rolled back，seata retry due

**Comment by RaigorJiang** [comment]
Hi @wangyf1024 
Has this issue been resolved?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
