### ISSUE TITLE
How ShardingSphere-Proxy adds a new year's sub-table

### ISSUE THREAD

**Issue by saeipi** [apache/shardingsphere#22068]
How ShardingSphere-Proxy adds a new year's sub-table

I have split the table by month. For example, 202201 - 202212. I now want to append the data for 2023. I would like to add 202301~202312 forms. Please how can I achieve this.

> **For English only**, other languages will not accept.

**Comment by RaigorJiang** [comment]
Hi @saeipi 
You can update sharding table rule by [DistSQL](https://shardingsphere.apache.org/document/5.2.1/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/) `ALTER SHARDING TABLE RULE`,
and then execute `CREATE TABLE IF NOT EXIST xxx`
