### ISSUE TITLE
Route table null does not exist, available actual table

### ISSUE THREAD

**Issue by sonwyday** [apache/shardingsphere#22072]
## Version
5.1.2
## Question
algorithmExpression disappeared
![image](https://user-images.githubusercontent.com/16163595/201268049-25960305-ccba-4df7-924e-d0697ce9116d.png)
![image](https://user-images.githubusercontent.com/16163595/201268506-24b13ad8-6d54-4dd4-9d07-179a03448a2f.png)
![image](https://user-images.githubusercontent.com/16163595/201267749-865a4329-b8c9-4082-b435-e07109843af7.png)

![微信截图_20221111130646](https://user-images.githubusercontent.com/16163595/201267557-b2bea3e9-7e6c-42bc-972c-90a3e09f3b20.png)
![image](https://user-images.githubusercontent.com/16163595/201268998-a905c242-21dd-400b-b5f0-406b9baefdd9.png)

**Comment by sandynz** [comment]
Hi @sonwyday , could you fill information with template?
And it's better to post detailed configuration and steps to reproduce.

**Comment by TeslaCN** [comment]
Close due to no response.
Spring modules have been deprecated and removed since 5.3.0. Please use the new way to integrate ShardingSphere with Spring Boot.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/
