### ISSUE TITLE
大佬们，请教一下shardingProxy怎么解决创建的物理表和逻辑表的中文乱码的问题

### ISSUE THREAD

**Issue by pandong8** [apache/shardingsphere#22083]
大佬们，请教一下shardingProxy怎么解决创建的物理表和逻辑表的中文乱码的问题？感谢

**Comment by RaigorJiang** [comment]
Hi @pandong8 
Welcome to Apache ShardingSphere community, but only **English** is accepted here.
I will close this issue, please submit a new one.
Thank you!
