### ISSUE TITLE
shadring jdbc  HA And  readwrite-splitting  not effectuate

### ISSUE THREAD

**Issue by Fanzhshuai** [apache/shardingsphere#22090]
shardingsphere-jdbc-core-spring-boot-starter： 5.2.1
type : sharding- jdbc
mysql cluster : one master two slave

HA And  readwrite-splitting rules config：

   rules:
        readwrite-splitting:
          data-sources: 
            replica_ds:
              dynamic-strategy:
                auto-aware-data-source-name: readwrite_ds
                write-data-source-query-enabled: true
        database-discovery:
          data-sources:
            readwrite_ds:
              data-source-names: ds1,ds2,ds3
              discovery-heartbeat-name: mgr-heartbeat
              discovery-type-name: mgr
          discovery-heartbeats:
            mgr-heartbeat:
              props: 
                keep-alive-cron: '0/5 * * * * ?'
          discovery-types:
            mgr:
              type: MySQL.NORMAL_REPLICATION
              props: 
                delay-milliseconds-threshold: 1000

Problem 1: When a salve  MySQL server stops service from the database, the read request traffic cannot be switched to another available salve MySQL server

Problem 2: Both MySQL slave databases stop service, and the read request traffic cannot be switched to the available MySQL master server

I hope everybody can help me with this. Thank you

**Comment by sandynz** [comment]
Hi @Fanzhshuai , thanks for you feedback. Suggest to use code block to paste configuration.

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could you help to have a look at this issue?

**Comment by RaigorJiang** [comment]
This issue has been inactive for too long, and ShardingSphere has released several new versions, so I will close it.
Users are advised to try the latest version, and if the problem reproduces, please reopen it or submit a new one.
