### ISSUE TITLE
postgresql order by cause NullPointerException

### ISSUE THREAD

**Issue by qunqunzq** [apache/shardingsphere#22108]
version 5.2.1

When you have Orby, I find that you load Schema = public by default. But my table is in object_modeling, resulting in a NullPointerException.

![](https://user-images.githubusercontent.com/8464801/143830561-6c22c583-ce81-493a-b2e4-8a7539e471f5.png)

Now in order to execute properly, I have to create the table again under public. Is this a bug? Or can you specify which tables to scan?

**Comment by qunqunzq** [comment]
My jdbc link = jdbc:postgresql://127.0.0.1:5432/event_driven?currentSchema=object_modeling

**Comment by sandynz** [comment]
Hi @qunqunzq , JDBC mode or proxy mode are you running? Which SQL or method did you execute that trigger this error?

Looks like it's a search path issue, search path is fully supported currently, could you try to add schema in SQL as a workaround for now?

**Comment by strongduanmu** [comment]
Sorry, the search path feature is not supported at present. The default schema is `public`. If you need to query table in other schemas, please use `select * from schema.table`.
