### ISSUE TITLE
Consider adding a version switch button in the upper right corner of the document page

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#22126]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

It is very inconvenient to switch versions at present. Is it possible to consider adding a version switching button in the upper right corner of the document page?

![image](https://user-images.githubusercontent.com/10829171/201480954-afa028a2-f81b-4d16-bec8-762c77ecde53.png)

**Comment by Jacob953** [comment]
Done.

**Comment by strongduanmu** [comment]
@Jacob953 Good job.
