### ISSUE TITLE
Optimize algorithmDefinition naming in encryptColumnDefinition

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22135]
In the `CREATE ENCRYPT RULE` syntax, there is such a definition as follows:

```sql
encryptColumnDefinition
     : LP columnDefinition (COMMA plainColumnDefinition)? COMMA cipherColumnDefinition (COMMA assistedQueryColumnDefinition)? (COMMA likeQueryColumnDefinition)? COMMA algorithmDefinition (COMMA algorithmDefinition)? (COMMA algorithmDefinition)? RP
     ;
```
Ref: https://github.com/apache/shardingsphere/blob/master/features/encrypt/distsql/parser/src/main/antlr4/imports/encrypt/RDLStatement.g4

It can be found that there are three `algorithmDefinitions` in this definition, but they actually represent different meanings.
According to the semantics, these three `algorithmDefinition` represent `encrypt algorithm`, `assisted query algorithm` and `like query algorithm` respectively.

We should add variables to distinguish these names and improve readability.

**Comment by isHuangXin** [comment]
[WeOpen Star] Hi, Jiang. I want to try this issue. Plz assign it to me~

**Comment by RaigorJiang** [comment]
Welcome back！ @isHuangXin

**Comment by isHuangXin** [comment]
I probably understand the meaning of this issue. 

There are three algorithmDefinitions in `COMMA algorithmDefinition (COMMA algorithmDefinition)? (COMMA algorithmDefinition)?`, which represent `encrypt algorithm`, `assisted query algorithm` , and  `like query algorithm` respectively. 

The task I need to finish is to alias these three algorithms separately for better readability.

**Comment by RaigorJiang** [comment]
> I probably understand the meaning of this issue.
> 
> There are three algorithmDefinitions in `COMMA algorithmDefinition (COMMA algorithmDefinition)? (COMMA algorithmDefinition)?`, which represent `encrypt algorithm`, `assisted query algorithm` , and `like query algorithm` respectively.
> 
> The task I need to finish is to alias these three algorithms separately for better readability.

Yes, you are right!
