### ISSUE TITLE
how to create table using    ShardingSphereDataSource ds

### ISSUE THREAD

**Issue by jianzh5** [apache/shardingsphere#22152]
I want auto create tables by days , i using ShardingSphereDataSource like this

```java
 private void createTable(DataSource dataSource, String logicTable) {
        String sql = "Create table if not exists `T_EVENT_20221113` like `T_EVENT_20221110`";
        try(Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()){
            statement.execute(sql);
        }catch (SQLException e){
            throw new RuntimeException("");
        }
    }
```

i have two datasource on application.yml，ds0 and ds1，this procedure only takes effect on ds0。

![image](https://user-images.githubusercontent.com/5998464/201525357-75e13781-0b7e-49da-b939-f8f8a7f96cdd.png)

How to get the program to work in both ds0 and ds1?

**Comment by fang1025** [comment]
you should get ShardingSphereMetaData first. 
then you can get all databases and excute you function 'createTable' for each database.

**Comment by sandynz** [comment]
Hi @jianzh5 , if your `dataSource` is ` ShardingSphereDataSource` (which includes ds0 and ds1), then it'll be routed to ds0 and ds1 automatically.

Is there already existing table? Does CRUD work?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
