### ISSUE TITLE
ShardingSphere-Encrypt: I query encrypted field with AssistedColumn，and it can't support predicate form

### ISSUE THREAD

**Issue by tianshuainan** [apache/shardingsphere#22194]
I  queryed encrypted field(such as :email) with Assisted query column and I used the method provided by JPA (findByEmail ()) to find the correct results. But using the following Predicate method fails. How to  solve this?I  will appreciate it very much and look forward to your reply.
` public ResponseEntity<?> getPaginatedRequestsByDsl(int page, int size, Predicate predicate) {

        Pageable paging = PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createTime"));
        final Page<DsrRequest> pagedResult = dsrRequestRepositoryDao.findAll(predicate, paging);

        final DsrRequestInPaginatedResponse dsrRequestInPaginatedResponse = new DsrRequestInPaginatedResponse();
        if (pagedResult.hasContent()) {
            List<DsrRequestDto> listOfDsrRequests = pagedResult.stream()
                    .map(DsrRequestMapper.INSTANCE::entityToDto).collect(Collectors.toList());

            dsrRequestInPaginatedResponse.setRequests(listOfDsrRequests);
        } else {
            dsrRequestInPaginatedResponse.setRequests(Collections.emptyList());
        }`

**Comment by tuichenchuxin** [comment]
Please investigate in detail the SQL used by the specific query and offer related configuration.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
