### ISSUE TITLE
OrderedServicesCache#softCache may be memory leak

### ISSUE THREAD

**Issue by ICannerxy** [apache/shardingsphere#22204]
### Which version of ShardingSphere did you use? 
> 5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
> ShardingSphere-Proxy

### Expected behavior
> Full GC is expected to recycle useless objects in the cache, When a table is created or deleted, the objects in the soft reference are always growing.

### Actual behavior
> Full gc objects in the old age cannot be recycled, resulting in frequent full gc.

### Reason analyze (If you can)
> May be the object in softCache is strong reference, so can`t recycled when full gc.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Frequently create tables and delete tables, and use DistSQL to add sharding table rules .

### Example codes for reproduce this issue (such as a github link).

![image](https://user-images.githubusercontent.com/40480377/202127621-37a8a1f3-6436-4b92-b80e-3839402162c7.png)

![image](https://user-images.githubusercontent.com/40480377/202127660-a4f638b9-ebdf-4a7c-b10f-e818a0258a93.png)

**Comment by strongduanmu** [comment]
Hi @ICannerxy, can you try batch updating hundreds of rules in one distsql? This reduces the creation of many rule objects.

**Comment by TeslaCN** [comment]
Could you provide heap dump?

**Comment by TeslaCN** [comment]
It seems that the classloader had the largest retained size. The heap dump couldn't prove this issue.

![image](https://user-images.githubusercontent.com/20503072/202398265-eec23b46-94c5-4eaa-ad4d-bb9d953e7fa4.png)


![image](https://user-images.githubusercontent.com/20503072/202398150-1385e6e4-9142-40bc-a5a4-c740491ef4f2.png)

**Comment by ICannerxy** [comment]
The verified impact is that after running for a period of time, the shardingSphere's full gc is very frequent, but the full gc can't recover the old object in cache, Because the recovery time of SoftReference occurs before OOM, full gc will not recover.
