### ISSUE TITLE
Nacos Repository throws 'Wait value availability timeout exceeded' Exception

### ISSUE THREAD

**Issue by twosoy** [apache/shardingsphere#22214]
## shardingsphere  version：5.2.1 and spring-boot version：2.7.3

    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-cluster-mode-repository-nacos</artifactId>
      <version>5.2.1</version>
    </dependency>

    <dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-cluster-mode-repository-nacos</artifactId>
      <version>5.2.1</version>
    </dependency>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.3</version>
        <relativePath/>
      </parent>

## application.properties
`
logging.level.org.apache.shardingsphere=DEBUG
spring.shardingsphere.props.sql-show=true
spring.shardingsphere.mode.type=Cluster
spring.shardingsphere.mode.repository.type=Nacos
spring.shardingsphere.mode.repository.props.server-lists=localhost:8848
spring.shardingsphere.mode.repository.props.namespace=01413141-9cfb-477a-9dc3-da0cd2e522ed
spring.shardingsphere.datasource.names=ds1
spring.shardingsphere.datasource.ds1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds1.jdbc-url=jdbc:mysql://localhost:55000/sharding
spring.shardingsphere.datasource.ds1.username=xxxx
spring.shardingsphere.datasource.ds1.password=xxxx
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds1.t_order_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=type
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=t-order-inline
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.props.algorithm-expression=t_order_$->{type % 2}

`

## Exception
<img width="1229" height="300" alt="Snipaste_2022-11-16_20-40-00" src="https://user-images.githubusercontent.com/26370775/202187230-a2fbf21d-5ac4-468c-a13d-79edae7a626a.png">

## Question
1、Is this a bug ，how to fix？
2、Whether there is an Example of repository-nacos？

Thank You！！！！！！！！！

**Comment by zhaojinchao95** [comment]
@caqhy Hi, can you look this?

**Comment by caqhy** [comment]
@twosoy Hi, try the following configuration.

```yaml
mode:
  type: Cluster
  repository:
    type: Nacos
    props:
      namespace: governance_ds
      server-lists: localhost:8848
      retryIntervalMilliseconds: 1000
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
```

If Nacos Repository still throws 'Wait value availability timeout exceeded' Exception, please try increasing value of retryIntervalMilliseconds, maxRetries.

**Comment by twosoy** [comment]
@caqhy 
Nacos Repository still throws 'Wait value availability timeout exceeded' Exception！！！！！
``` yaml
retryIntervalMilliseconds：2000
maxRetries：5
```

> There are three steps to persist '/metadata/logic_db/active_version'
s1: persist /metadata                 
s2: /metadata/logic_db             
s3: /metadata/logic_db/active_version

But，After persist，only ‘/metadata/logic_db/active_version’ in service。
The subsequent persistence operation overwrites the previous value。

The service meta of 'PERSISTENT' is 
``` 
+08:00=1668726902989
/metadata/logic_db/active_version=0
``` 
<img width="1324" height = "159" alt="image" src="https://user-images.githubusercontent.com/26370775/202583836-59865d1f-062a-4758-b7dc-6938192f6334.png">



waitValue method throws 'NacosException',because of There are three pieces of data for generation persistence, but actually there is only one piece。


*NacosRepository.java*
``` java
@SneakyThrows(InterruptedException.class)
    private void waitValue(final Collection<KeyValue> keyValues) throws NacosException {
        if (!isAvailable(keyValues)) {
            long retryIntervalMilliseconds = nacosProps.getValue(NacosPropertyKey.RETRY_INTERVAL_MILLISECONDS);
            int maxRetries = nacosProps.getValue(NacosPropertyKey.MAX_RETRIES);
            for (int retry = 0; retry < maxRetries; retry++) {
                Thread.sleep(getSleepTimeMs(retry, retryIntervalMilliseconds));
                if (isAvailable(keyValues)) {
                    return;
                }
            }
            throw new NacosException(NacosException.RESOURCE_NOT_FOUND, "Wait value availability timeout exceeded");
        }
    }
    
    private boolean isAvailable(final Collection<KeyValue> keyValues) throws NacosException {
        Map<Boolean, List<KeyValue>> keyValueMap = keyValues.stream().collect(Collectors.groupingBy(KeyValue::isEphemeral));
        for (Entry<Boolean, List<KeyValue>> entry : keyValueMap.entrySet()) {
            ServiceMetadata service = serviceController.getService(entry.getKey());
            Map<String, List<Instance>> instanceMap = client.getAllInstances(service.getServiceName(), false).stream().collect(Collectors.groupingBy(NacosMetaDataUtil::getKey));
            keyValues.removeIf(keyValue -> {
                Collection<Instance> instances = instanceMap.get(keyValue.getKey());
                String value = keyValue.getValue();
                return CollectionUtils.isNotEmpty(instances) ? instances.stream().anyMatch(instance -> StringUtils.equals(NacosMetaDataUtil.getValue(instance), value)) : Objects.isNull(value);
            });
        }
        return keyValues.isEmpty();
    }
```

**Comment by sandynz** [comment]
Hi @twosoy , is it resolved?

Did you try nacos client or telnet to connect Nacos server, how much time it cost?
If it's fast enough, then could you debug `NacosRepository's` `waitValue` and `isAvailable` to find out which step is slow?

**Comment by twosoy** [comment]
It's fast enough，but actually there is only one piece！！！！

**Comment by twosoy** [comment]
The problem has been solved.

The component versions I use are as follows:
shardingsphere-jdbc-core ： 5.3.0  
shardingsphere-cluster-mode-repository-nacos version ： 5.3.0  
Nacos Version ： 2.1.2 

Thank you very much for your help.

**Comment by sandynz** [comment]
@twosoy , could you share how you resolve it? It could be valuable for other people.

**Comment by removeif** [comment]
@twosoy  hi , my  nacos have username & password ,how need I do support it? shardingsphere version 5.2.1
![image](https://user-images.githubusercontent.com/10427139/211259115-4e040a11-8c7c-44e1-990a-7e3943c1bc2a.png)

**Comment by byteboycn** [comment]
@twosoy I have same problem, colud you tell me how to resolve it ?

**Comment by byteboycn** [comment]
resolved,   
just using nacos-server 2.0 or later
