### ISSUE TITLE
如何配置方言转换

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [apache/shardingsphere#22227]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
关于方言转换的功能， 没有找到配置说明或者使用手册

**Comment by strongduanmu** [comment]
For English only, other language will not accept.

**Comment by Jean-Jacques-Nuoan** [comment]
can you speak chinese ?

**Comment by strongduanmu** [comment]
Apache is an international community, and communication in English is the norm at Apache, which helps people with different language backgrounds to communicate technically. If you want to communicate in Chinese, please join the official chinese WeChat group.
