### ISSUE TITLE
如何配置方言转换

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [apache/shardingsphere#22238]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
如何配置方言转换功能，有没有配置说明或者配置手册

**Comment by tuichenchuxin** [comment]
Please use english for issue.
