### ISSUE TITLE
Is ContextManager#alterRuleConfiguration thread-safe method?

### ISSUE THREAD

**Issue by fbin87** [apache/shardingsphere#22237]
## Question

the method such as org.apache.shardingsphere.mode.manager.ContextManager#alterRuleConfiguration, alterSchemas and so on, Are they thread-safe ?

I want to update the rule or database with ContextManager.alterRuleConfiguration(...), while the old shardingSphere data source is being used

**Comment by zhaojinchao95** [comment]
@fbin87 They are thread-safe for a single ShardingSphere-Proxy.

**Comment by fbin87** [comment]
> @fbin87 They are thread-safe for a single ShardingSphere-Proxy.

Under the situation of java api standalone mode, when I call ContextManager.alterRuleConfiguration(...) to refresh the current ShardingSphereDatasource (it is used by another thread), how about ?

**Comment by zhaojinchao95** [comment]
> > @fbin87 They are thread-safe for a single ShardingSphere-Proxy.
> 
> @zhaojinchao95 Hello, Under the situation of java api standalone mode, when I call ContextManager.alterRuleConfiguration(...) to refresh the current ShardingSphereDatasource (it is used by another thread), how about ?

I think we can verify it. you have some suggest?

**Comment by fbin87** [comment]
> > > @fbin87 They are thread-safe for a single ShardingSphere-Proxy.
> > 
> > 
> > @zhaojinchao95 Hello, Under the situation of java api standalone mode, when I call ContextManager.alterRuleConfiguration(...) to refresh the current ShardingSphereDatasource (it is used by another thread), how about ?
> 
> I think we can verify it. you have some suggest?

thank you, No additional suggestions
