### ISSUE TITLE
Remove the exclamation mark in the proxy's global rule configuration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22329]
Hi community,

Before, we have removed the exclamation in the Authority configuration in #21611.
Well, this way does make the configuration more concise.

Now, I propose to remove the exclamation mark in other global rule configurations, including:
- !TRANSACTION
- !SQL_PARSER
- !SQL_TRANSLATOR

Please Refer to:
- https://github.com/apache/shardingsphere/blob/master/proxy/bootstrap/src/main/resources/conf/server.yaml
- https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/yaml-config/rules/

**Comment by jiangML** [comment]
I want to do it.

**Comment by RaigorJiang** [comment]
Hi @jiangML, thank you!

**Comment by RaigorJiang** [comment]
Completed.
