### ISSUE TITLE
Can we unify the use of underscore and minus in YAML?

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22321]
Hi community,

In YAML configuration, we can use underscore (`_`) or minus (`-`), but it is very strange to mix them irregularly in a same file, as shown in the following figure:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/5668787/203093931-82f366fe-33ad-490f-a0ab-0f97c00e0211.png">

The above picture is from the sharding configuration document, and there are similar cases in examples, underscore (_) or minus (-) are used.

While both symbols are legal, I think we should recommend one usage in our projects, maybe like table names, using underscores is just fine.

**Comment by RaigorJiang** [comment]
After discussing with @terrymanu , we believe that the YAML configuration style in the project should be unified for the following reasons:
- Avoid user confusion and reduce the cost of understanding
- Facilitates interaction with DistSQL, since in DistSQL only underscore is allowed in identifier

Therefore, we plan to update all YAML file separators in the example and documentation to underscore.
Anyone wanna try it?

**Comment by Qianyi951015** [comment]
Please assign to me
