### ISSUE TITLE
When I Use Encrypt, How can I solve blank String correctly？

### ISSUE THREAD

**Issue by Keanhua** [apache/shardingsphere#22349]
## Question

**For English only**, other languages will not accept.

I config 'A' column need encrypt.  When i insert one data ，the 'A' column will be encrypted.
but i config  'A' column  default ''. When i insert one data without 'A' column，the 'A' column will be ''.
then  when i query with 'A' column,  the condition is where 'A'='', i can not query those records with default '' value.

how can i solve it？thanks. i only think i can config default value with the blank encrypted value.

**Comment by tuichenchuxin** [comment]
You can try to change to default null

**Comment by Keanhua** [comment]
> You can try to change to default null

if i change to default null, the column can not create index correctly。

**Comment by tuichenchuxin** [comment]
There is currently no way to skip the encryption of empty strings.

**Comment by cheese8** [comment]
change default '' into default encrypt('') or make column A in sql explicitly
