### ISSUE TITLE
ShardingProxy uses database and return the result `show tables` without inputted SQL

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#2234]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
1. login
2. input `select * from t_order;`
3. get error information that `ERROR 1046 (3D000): No database selected`
4. input `show tables;`
***5. get error information that `ERROR 1046 (3D000): No database selected`***
### Actual behavior
1. login
2. input `select * from t_order;`
3. get error information that `ERROR 1046 (3D000): No database selected`
4. input `show tables;`
***5. get information that `Empty set (0.06 sec)`***
### Reason analyze (If you can)
When i input `show tables;`, shardingProxy `setLogicSchema()` in`UnicastBackendHandler`.

Here is the problem in `UnicastBackendHandler`:
```
LogicSchema logicSchema = backendConnection.getLogicSchema();
        if (null == logicSchema) {
            logicSchema = LogicSchemas.getInstance().getLogicSchemas().values().iterator().next();
            backendConnection.setCurrentSchema(logicSchema.getName());
        }
```

**Comment by cherrylzhao** [comment]
we will fix this after parser engine complete refactor.

**Comment by cherrylzhao** [comment]
SQL parse engine have completed DAL refactor, the hard code for proxy handler could be removed

**Comment by tristaZero** [comment]
Hi @xbkaishui 
Do you think this issue actually was fixed?

**Comment by xbkaishui** [comment]
Yes.  It works as expect in master branch

**Comment by tristaZero** [comment]
Thanks for your reminder @xbkaishui , therefore I will close this one.
