### ISSUE TITLE
Integration test General DQLIT has failed. And the error is different everytime.

### ISSUE THREAD

**Issue by boyjoy1127** [apache/shardingsphere#22352]
## Integration test General DQLIT has failed. And the error is different everytime.
Run "org.apache.shardingsphere.test.integration.engine.dql.GeneralDQLIT"
With the content of "it-env.properties“
```
#it.run.modes=Standalone,Cluster
it.run.modes=Standalone
it.run.additional.cases=false

#it.scenarios=db,tbl,readwrite_splitting,encrypt,shadow,dbtbl_with_readwrite_splitting,dbtbl_with_readwrite_splitting_and_encrypt,rdl_empty_rules,empty_rules,sharding_and_encrypt,encrypt_and_readwrite_splitting,encrypt_shadow,readwrite_splitting_and_shadow,sharding_and_shadow,sharding_encrypt_shadow
it.scenarios=db

# it.cluster.env.type=DOCKER,NATIVE
it.cluster.env.type=NATIVE

# it.cluster.adapters=jdbc,proxy
it.cluster.adapters=proxy

# it.cluster.databases=MySQL,PostgreSQL,openGauss
it.cluster.databases=MySQL

```

<img width="1369" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/101028753/203474636-88dde446-d0bb-413b-8a13-98d766393af2.png">
<img width="1372" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/101028753/203474655-910e796c-3e26-44f6-ac5b-0edac9ebb1e4.png">
<img width="1378" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/101028753/203474671-be7b8c51-0d7d-4bd3-8d9f-8750a8c536e8.png">
<img width="1371" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/101028753/203474687-73d99144-6386-4604-8424-fce80bb6c5e4.png">
<img width="1377" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/101028753/203474712-7a609632-d4dd-4414-bddf-c4be541b0c49.png">
<img width="1368" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/101028753/203474735-e1badb85-c837-4fbe-96aa-a8e2bd763e4a.png">
<img width="1406" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/101028753/203474753-c9a7b43a-125c-427e-b764-af4008fa7f08.png">
<img width="1370" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/101028753/203474761-a5353d4a-ea47-4692-9eae-c9c1185333c9.png">

**Comment by zhaojinchao95** [comment]
Thank you for your feedback, We need to check it.

**Comment by terrymanu** [comment]
The DQL test engine has been refactored
