### ISSUE TITLE
ConsulRepositoryTest.assertWatchUpdate unit test are failed on JDK17 with windows

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#22354]
Refer to : https://github.com/apache/shardingsphere/actions/runs/3504574219/jobs/5870340032#step:6:51477

`master` https://github.com/apache/shardingsphere/commit/74ec5dfa35c98d7436a353456a6d5be99320a570

```
Error:  Failures: 
Error:    ConsulRepositoryTest.assertWatchUpdate:159 
Wanted but not invoked:
client.getKVValues(
    <any java.lang.String>,
    <any com.ecwid.consul.v1.QueryParams>
);
-> at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:529)

However, there were exactly 2 interactions with this mock:
client.setKVValue(
    "sharding/key/key1",
    "value1"
);
-> at org.apache.shardingsphere.mode.repository.cluster.consul.ConsulRepositoryTest.assertWatchUpdate(ConsulRepositoryTest.java:148)

client.setKVValue(
    "sharding/key/key1",
    "value1-1"
);
-> at org.apache.shardingsphere.mode.repository.cluster.consul.ConsulRepositoryTest.assertWatchUpdate(ConsulRepositoryTest.java:155)


[INFO] 
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by clbigdata** [comment]
I want try it.

**Comment by linghengqian** [comment]
- How is this problem currently ignored in ShardingSphere CI? I have the impression that Junit4 does not have anything like Junit Jupiter's `org.junit.jupiter.api.condition.DisabledOnOs` annotation.

**Comment by linghengqian** [comment]
- As a reminder, CI went back to normal two days ago. Reference https://github.com/apache/shardingsphere/actions/runs/4008661065 .
- ![image](https://user-images.githubusercontent.com/20187731/215278650-2d94af46-a2d7-487a-82fb-ccf044bd4b5c.png)

**Comment by linghengqian** [comment]
- Fixed in https://github.com/apache/shardingsphere/actions/runs/7265750918 .

**Comment by linghengqian** [comment]
- Confirmed at https://github.com/apache/shardingsphere/actions/runs/7920316847 that it has been fixed.
