### ISSUE TITLE
[DistSQL] Improve DROP .* RULE & DROP .* STRATEGY

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#22358]
Hi community,

After DistSQL has restructured the grammar of creating rules, it no longer supports referencing existing algorithms to create rules, so when removing a rule, the associated algorithms should be removed at the same time.

**Aim**

Improve the following DistSQL:

- DROP DB_DISCOVERY RULE
- DROP ENCRYPT RULE
- DROP READWRITE_SPLITTING RULE
- DROP SHADOW RULE
- DROP SHARDING TABLE RULE
- DROP SHARDING TABLE REFERENCE RULE
- DROP BROADCAST TABLE RULE
- DROP TRAFFIC RULE
- DROP DEFAULT SHARDING DATABASE STRATEGY
- DROP DEFAULT SHARDING TABLE STRATEGY

**Comment by RaigorJiang** [comment]
Related to #21659.

**Comment by Pace2Car** [comment]
I will work on this issue.
