### ISSUE TITLE
ERROR:  Routed target `ds_-1` does not exist, available targets are `[ds_0, ds_1]`.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#22357]
### Which version of ShardingSphere did you use?
792829660d2bf7b2dbc7890d8431242a47541333
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy 
### Expected behavior
<img width="805" alt="image" src="https://user-images.githubusercontent.com/86462784/203498727-341f9bee-82ab-42ee-a3af-8ed33ff84305.png">

like DB，we can insert negative 
### Actual behavior
<img width="811" alt="image" src="https://user-images.githubusercontent.com/86462784/203498698-1e065c74-cff1-474c-a2c4-fb12a5fbb225.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
https://github.com/apache/shardingsphere/issues/22170
```
 insert into t_ssdb_tb values (1,1,99,'test'),(-1,2,99,'Test12'),(0,2,99,'test12');
```

**Comment by strongduanmu** [comment]
@wsm12138 Please try to add abs function for sharding algrithom.

**Comment by wsm12138** [comment]
algorithm-expression: t_order_big_${(order_id % 2).abs()}
          thanks for your reply
