### ISSUE TITLE
Whether to support all tables of the data to follow the default sub-database strategy

### ISSUE THREAD

**Issue by flywenCWW** [apache/shardingsphere#22389]
Configure the table to be divided in the spring.shardingsphere.sharding.tables configuration item, and the strategy of dividing the database can be implemented correctly
But there is no configured table, and the strategy of sub-database cannot be used

Is there a way to let all the tables in the database use the sub-database strategy by default, instead of the tables configured in spring.shardingsphere.sharding.tables to be sub-database, because there are a lot of tables, it is more troublesome to configure

**Comment by strongduanmu** [comment]
You can try to set defaultDatabaseStrategy, it can simplify sharding configuration.
