### ISSUE TITLE
a question about set shardingsphere mode

### ISSUE THREAD

**Issue by griptide** [apache/shardingsphere#22382]
em~ so is a bug ?

![image](https://user-images.githubusercontent.com/32671195/203725121-53ade7c9-f51e-4b9b-a78f-82fab42fbf42.png)

![image](https://user-images.githubusercontent.com/32671195/203725146-28270e03-c50f-403e-8299-4d7b216b338d.png)

**Comment by strongduanmu** [comment]
Thank you for your feedback. @zhaojinchao95  Can you help check this issue?

**Comment by zhaojinchao95** [comment]
> Thank you for your feedback. @zhaojinchao95 Can you help check this issue?

Sure.

**Comment by zhaojinchao95** [comment]
@griptide Hi, The `memory` mode needn't to configuration. ShardingSphere default mode are `memory` in your `ShardingSphere version`. you can refer to : https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/cluster-mode-example/cluster-mode-spring-namespace-mybatis-example/src/main/resources/META-INF/zookeeper
