### ISSUE TITLE
rewrite sql to lose the schema

### ISSUE THREAD

**Issue by dbin0123** [apache/shardingsphere#22387]
database: dm8
sharding version: 5.2.1
org.apache.shardingsphere.infra.rewrite.sql.impl.AbstractSQLBuilder.toSQL()

![image](https://user-images.githubusercontent.com/18297300/203758724-3b255b1b-e4c6-4721-aca6-df2b98de54e8.png)

**Comment by strongduanmu** [comment]
@dbin0123 Can you provide your configuration to help reproduce this exception?

**Comment by dbin0123** [comment]
The example configuration obtains the data source'getDataSource()'. There is a problem with the data source name, please adjust it to`healthcloud_platform_support`. Thank you

**Comment by dbin0123** [comment]
The example configuration obtains the data source'getDataSource()'. There is a problem with the data source name, please adjust it to`healthcloud_platform_support`. Thank you

**Comment by RaigorJiang** [comment]
Hi @dbin0123 
Has this issue been resolved?
In addition, the ShardingSphere community does not have a test environment for the DM database and cannot verify your scenario.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
