### ISSUE TITLE
Agent supports projects that use JDBC, such as Spring Boot

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#22409]
### Background
Currently `Agent` only supports integration with `Proxy`, there will be problems when integrating with `JDBC`. 
For example, when integrating with a spring boot project, the current `Agent` does not support this scenario due to the existence of a custom classloader in Spring Boot.
```
java -javaagent:/xx/shardingsphere-agent.jar -jar spring-boot-xxx.jar
```

### Problem
1. Agent will share `slf4` and `logback` dependencies with the application. When integrating with Spring Boot applications, the Agent cannot find the corresponding dependencies because Spring Boot uses a custom classloader to load dependencies
2. The enhanced implementation classes in the plug-in jar will be loaded using AppClassloader, but the Spring Boot application will be started using a custom classloader, resulting in enhanced classes and applications in different classloaders.

### Task
1. Bootstrap agent dependencies need to be isolated from application dependencies
2. The classloader of the enhanced class needs to be associated with the application classloader
3. Bootstrap agent needs to wrap log output (to prevent the Proxy's logback.xml configuration file from being obtained when integrating with Proxy, resulting in a mismatch between the classes in the configuration file and the shaded classes)

**Comment by RaigorJiang** [comment]
Completed.
