### ISSUE TITLE
shardingsphere uses snowflake algorithm to generate primary key. Why can it only generate the value of 1 or 2 after modulo 16?

### ISSUE THREAD

**Issue by chenyongyin** [apache/shardingsphere#22424]
version：5.0.0-alpha
question：
shardingsphere uses snowflake algorithm to generate primary key. Why can it only generate the value of 1 or 2 after modulo 16?

**Comment by zhaojinchao95** [comment]
@chenyongyin Can you use `ShardingSphere`` 5.2.1`  and try it?

**Comment by sandynz** [comment]
Hi @chenyongyin , I checked `SnowflakeKeyGenerateAlgorithm.generateKey()`, `sequence` will increase `1` in every call.

What's the system TPS? Maybe it's too small. Since snowflake algorithm generated id will be changed in every millisecond.

**Comment by TeslaCN** [comment]
Close due to no response.
