### ISSUE TITLE
Uniform term `DistSQL`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22449]
Hi community,

In Apache ShardingSphere, [DistSQL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/) is a proper noun, which means Distributed SQL.
However, we cannot use `dist SQL` to represent `DistSQL` because `dist` is not a complete word.

There are the following examples:
- correct
```java
/**
  * DistSQL backend handler factory.
  */
```

- incorrect
```java
/**
  * Dist SQL Statement.
  */
```

```java
/**
  * SQL parser for kernel dist SQL.
  */
```

We need to unify these terms, anyone want to try?

**Comment by Qianyi951015** [comment]
please assign to me

**Comment by RaigorJiang** [comment]
Thank you! @Qianyi951015
