### ISSUE TITLE
Questions about reloading metadata

### ISSUE THREAD

**Issue by 55959411** [apache/shardingsphere#22531]
### Which version of ShardingSphere did you use?
Shardingsphere 5.2.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
ORACLE
Zookeeper Cluster Mode

Problems occurred in the org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory class reloadDatabases method.

see below:
![issue](https://user-images.githubusercontent.com/46920849/204748066-d542758b-391f-427e-b3ad-7991578e554e.png)
As shown in the figure above, the schema information in zookeeper is not updated unless the zookeeper cache is deleted

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could you help to have a look at this issue?

**Comment by zhaojinchao95** [comment]
@55959411 ShardingSphere are believe governance center, ShardingSphere start up use db information when governance center not tables, if governance center has some tables, the ShardingSphere can use governance center's tables.

**Comment by RaigorJiang** [comment]
This is the design and will not change for the time being, thanks for the feedback.
