### ISSUE TITLE
Update EncryptRuleQueryResultSet for more algorithms.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22547]
Ref to #22135.
`encryptAlgorithm`, `assistedQueryAlgorithm` and `likeQueryAlgorithm` can be created in Encrypt RDL now, but there is still only `encryptAlgorithm` in RQL, we now need to upgrade `EncryptRuleQueryResultSet`.

See also: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/encrypt/

**Comment by jiangML** [comment]
Hi, I want to try this issue. please assign it to me.

**Comment by RaigorJiang** [comment]
Hi @jiangML, welcome~

**Comment by RaigorJiang** [comment]
Completed.
