### ISSUE TITLE
Rename `show_resources.xml` to `show_storage_units.xml`

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#22589]
Hi community,

The DistSQL `SHOW DATABASE RESOURCES` syntax adjusted to `SHOW STORAGE UNITS`, please refer to : #21671 .

So i think we should rename `show_resources.xml` to `show_storage_units.xml` in `test-suite` module.

**Comment by RishiKumarRay** [comment]
can i go for this? @zhaojinchao95

**Comment by Swastyy** [comment]
Welcome @RishiKumarRay

**Comment by RishiKumarRay** [comment]
@Swastyy please help to review
