### ISSUE TITLE
Encrypt queryWithCipherColumn not support Dynamic configuration In spring xml

### ISSUE THREAD

**Issue by zhaoguhong** [apache/shardingsphere#22591]
Encrypt queryWithCipherColumn not support Dynamic configuration In spring xml

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/28058794/205242684-da96d25b-4576-4ffd-afcf-c5144d9c604c.png">
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/28058794/205253333-9a508012-993a-4b25-ab2d-20a45b10d73c.png">

Because type is boolean in schema

<img width="983" alt="image" src="https://user-images.githubusercontent.com/28058794/205253450-4dced892-9df3-4f0f-8406-baab0f8e43fd.png">

The type can change to String?

**Comment by strongduanmu** [comment]
@zhaoguhong Thank you for your feedback. Starting from 5.3.0, we will use the ShardingSphere Driver to replace the Spring NameSpace, you can follow this version and test it.

**Comment by zhaoguhong** [comment]
> 

Ok
