### ISSUE TITLE
would Parameterized class combine together 

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#22590]
## Question

the class `ShardingSphereIntegrationTestParameterized` seems got something in common with `ParallelParameterized` : both of these are used for controlling the parallel of test case.

so, I'm curious 
1. is it possible to conbine to one class
2. why it needs to skip docker type

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/4112856/205249040-1b17eb14-a5c5-4807-8748-fea0f2a17727.png">

**Comment by terrymanu** [comment]
I just merge them in #22611
