### ISSUE TITLE
CREATE DB_DISCOVERY RULE error

### ISSUE THREAD

**Issue by wayuki** [apache/shardingsphere#22650]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

mysql: Server version:		5.6.51-log MySQL Community Server (GPL)
ds_a is master,others are slaves

### Expected behavior
ds_a:

mysql> SHOW SLAVE HOSTS;
+-----------+------+------+-----------+--------------------------------------+
| Server_id | Host | Port | Master_id | Slave_UUID                           |
+-----------+------+------+-----------+--------------------------------------+
|    168178 |      | 3306 |      9728 | 6b637151-72ba-11ed-a450-02001715f769 |
|      8764 |      | 3306 |      9728 | 6e903de2-72ba-11ed-a450-02001714e0dd |
+-----------+------+------+-----------+--------------------------------------+
2 rows in set (0.00 sec)

mysql> SHOW VARIABLES LIKE 'read_only';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| read_only     | OFF   |
+---------------+-------+
1 row in set (0.00 sec)

ds_b and ds_c:
mysql> SHOW SLAVE HOSTS;
Empty set (0.00 sec)

mysql> SHOW VARIABLES LIKE 'read_only';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| read_only     | ON    |
+---------------+-------+
1 row in set (0.00 sec)

mysql> CREATE DB_DISCOVERY RULE db_discovery_group_0 (
    -> RESOURCES(ds_a, ds_b, ds_c),
    -> TYPE(NAME='MySQL.NORMAL_REPLICATION'),
    -> HEARTBEAT(PROPERTIES('keep-alive-cron'='0/5 * * * * ?'))
    -> );
ERROR 30000 (HY000): Unknown exception: Cannot parse null string

### Actual behavior
ERROR 30000 (HY000): Unknown exception: Cannot parse null string

**Comment by RaigorJiang** [comment]
Hi @wayuki , thanks for your feedback, I will check it.

**Comment by Pace2Car** [comment]
Hi @wayuki, Can you try this statement in the 5.3.1 version, this issue seems to be resolved
```sql
CREATE DB_DISCOVERY RULE db_discovery_group_0 (
STORAGE_UNITS(ds_a, ds_b, ds_c),
TYPE(NAME='MySQL.NORMAL_REPLICATION'),
HEARTBEAT(PROPERTIES('keep-alive-cron'='0/5 * * * * ?'))
);
```

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
