### ISSUE TITLE
Sharding-JDBC When to support Mysql MGR Multi-primary mode

### ISSUE THREAD

**Issue by Fanzhshuai** [apache/shardingsphere#22679]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could you help to have a look at this issue?

**Comment by zhaojinchao95** [comment]
We are no plan to support it at the moment, what is your usage scenario? @Fanzhshuai

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , could you help to have a look at this issue?

Sure.

**Comment by Fanzhshuai** [comment]
> We are no plan to support it at the moment, what is your usage scenario? @Fanzhshuai

Readwrite-splitting Ha scenario.

**Comment by Fanzhshuai** [comment]
> > > We are no plan to support it at the moment, what is your usage scenario? @Fanzhshuai
> > 
> > 
> > Readwrite-splitting Ha scenario.
> 
> ShardingSphere not support dual write, so maybe you should use `sharding+readwirte-splitting+ha` ?

I know, but I don't want maintain sharding proxy。  

Finally, thank you for your reply
