### ISSUE TITLE
Make `SHOW SINGLE TABLES` support like clause

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22729]
Hi community,

This is a request for Improve DistSQL.

### Background
Now we have a DistSQL syntax:
```sql
SHOW SINGLE TABLES
```
Ref to: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/single-table/

### Aim
When there are many single tables, it is more difficult to look up some ones. 
We should support the like clause, just like `SHOW FULL TABLE LIKE 'xx%'`, we can support `SHOW SINGLE TABLES LIKE 'xxx'`.

Ref: https://dev.mysql.com/doc/refman/8.0/en/show-tables.html

**Comment by Qianyi951015** [comment]
please assign to 么

**Comment by RaigorJiang** [comment]
Hi @Qianyi951015 , welcome!
