### ISSUE TITLE
WorkerId

### ISSUE THREAD

**Issue by 1210958801** [apache/shardingsphere#22746]
Please tell me how to use workerId when using snowflake algorithm for distributed primary key ID in 5.1.1

**Comment by sandynz** [comment]
Hi @1210958801 , I checked https://github.com/apache/shardingsphere/releases , looks worker id is not well supported in version 5.1.1, since there's bug fix in newer version.

Could you try latest version?

**Comment by 1210958801** [comment]
Sorry, we are a production environment, is there any alternative plan now @sandynz

**Comment by sandynz** [comment]
@1210958801 , how you use worker id now? Is it used in proxy cluster?

Workaround: Generate distributed id by your system and set id into your SQL.

**Comment by youngMvcBrother** [comment]
> Sorry, we are a production environment, is there any alternative plan now @sandynz

@1210958801 

**My Solution;Can I help you?**

add configure
```yaml
    defaultKeyGenerateStrategy:
      column: user_id
      keyGeneratorName: snowflake
```


**issues source:**
_org.apache.shardingsphere.sharding.rule.ShardingRule_ instantiation; generate DefaultKeyGenerateStrategy overrides SnowflakeKeyGenerateAlgorithm;
**when generating DefaultKeyGenerateStrategy , prop is null;**
**If DefaultKeyGenerateStrategy  is set, it will not be overwritten.**

![image](https://user-images.githubusercontent.com/13623260/207279184-512204be-7139-46d6-8f9c-f43fb2982473.png)
