### ISSUE TITLE
I wonder if I could manually set the distributed private key

### ISSUE THREAD

**Issue by StupidManYI** [apache/shardingsphere#22744]
sometimes, I need to use the entity primary key for other fields. To avoid secondary query,I wonder if I could manually set the distributed private key.  (for the Same primary key generation strategy and IdGenerator)

this is my IdGenerator ( implements ShardingKeyGenerator)

<img width="631" alt="image" src="https://user-images.githubusercontent.com/50037510/206374256-7cecc507-6dcf-4905-a2d0-7db90b75ff78.png">

my example 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/50037510/206374981-43485bf0-887a-42ce-87df-83342751cfa5.png">

**Comment by sandynz** [comment]
Hi @StupidManYI , you could set primary key manually.

**Comment by StupidManYI** [comment]
ok,thank you so much @sandynz

**Comment by StupidManYI** [comment]
succeed in setting primary key manually.

 This primary key is manually generated and is not overwritten by automatic generation
<img width="765" alt="image" src="https://user-images.githubusercontent.com/50037510/206378471-624b05ae-0086-431d-8c43-514a7e3af536.png">
