### ISSUE TITLE
Discuss rename artifactId from shardingsphere-jdbc-core to shardingsphere-jdbc

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#22752]
After adding `ShardingSphereDriver`, spring namespace and spring boot starter of ShardingSphere-JDBC are no longer important. 
After removed them, the sub-module of `shardingsphere-jdbc` contains `shardingsphere-jdbc-core` only.

I know that API changes always annoy users. However, I still believe it is a good idea to rename the `shardingsphere-jdbc-core` of the root artifact ID to `shardingsphere-jdbc`.

Before changes, import ShardingSphere-JDBC from maven is:

```xml
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
```

I think it's better to change it to:

```xml
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc</artifactId>
```

Any suggestion?

**Comment by RaigorJiang** [comment]
As a dependency entry, `shardingsphere-jdbc` is better than `shardingsphere-jdbc-core`.

**Comment by strongduanmu** [comment]
This is a good idea to prevent users from incorrectly using `shardingsphere-jdbc` and `shardingsphere-jdbc-core` dependencies.
