### ISSUE TITLE
Cluster mode metadata repository implementation modules are not fully dependent in proxy-bootstrap module

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#22819]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Currently, [Metadata Repository]( https://shardingsphere.apache.org/document/5.3.0/en/user-manual/common-config/builtin-algorithm/metadata-repository/ ) has 4 implementations for Cluster mode: ZooKeeper, Etcd, Nacos and Consul.

Implementation modules are: `shardingsphere-cluster-mode-repository-zookeeper`, `shardingsphere-cluster-mode-repository-etcd`, `shardingsphere-cluster-mode-repository-nacos` and `shardingsphere-cluster-mode-repository-consul`.

They're equavalent, but only part of the implementation modules are dependent in `shardingsphere-proxy-boostrap` and `shardingsphere-jdbc-distribution` modules.
It's better to depend all of them or none of them in a module.

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could you help to have a look at this issue when you have time?

**Comment by zhaojinchao95** [comment]
@sandynz Thank you for your feedback, I think `ZooKeeper` and `Etcd` are the prefer register center for `ShardingSphere` cluster mode, So it's better to make it directly depend on. Other register center is better not to integrate by default, or it will make it bloated.

**Comment by zhaojinchao95** [comment]
I think `shardingsphere-jdbc-distribution` module are remove etcd dependency. `shardingsphere-proxy-boostrap ` continue to be reserved

**Comment by sandynz** [comment]
> I think `shardingsphere-jdbc-distribution` module are remove etcd dependency. `shardingsphere-proxy-boostrap ` continue to be reserved

That's OK
