### ISSUE TITLE
Add metadata repository impl dependency for JDBC Cluster mode in metadata repository document

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#22821]
### Is your feature request related to a problem?
No

### Describe the feature you would like.
Currently, [Metadata Repository]( https://shardingsphere.apache.org/document/5.3.0/en/user-manual/common-config/builtin-algorithm/metadata-repository/ ) has 4 implementations for Cluster mode: ZooKeeper, Etcd, Nacos and Consul. And they're not depended in `shardingsphere-jdbc-core` module.
If user want to use Cluster mode, they need to add related module in dependencies, but it's not documented for now. It's better to add it for easier integration.

Implementation modules are: `shardingsphere-cluster-mode-repository-zookeeper`, `shardingsphere-cluster-mode-repository-etcd`, `shardingsphere-cluster-mode-repository-nacos` and `shardingsphere-cluster-mode-repository-consul`.

e.g.
```
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-cluster-mode-repository-zookeeper</artifactId>
            <version>${shardingsphere.version}</version>
        </dependency>
```

**Comment by sandynz** [comment]
Hi @zhaojinchao95 , could you help to have a look at this issue when you have time?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , could you help to have a look at this issue when you have time?

Thx, i see

**Comment by linghengqian** [comment]
- I marked the GAV information of these dependencies in https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/optional-plugins/ before, do I need to move the page?
- ![image](https://user-images.githubusercontent.com/20187731/207005772-30cfe375-c5d7-4f17-a103-b3e2ff6e0b3a.png)

**Comment by sandynz** [comment]
Hi @linghengqian , looks it's different as Maven dependency and it's just for Proxy mode but not JDBC mode, I suggest to keep this page.

**Comment by zhaojinchao95** [comment]
@linghengqian Are you interested in following this?

**Comment by linghengqian** [comment]
@zhaojinchao95 To be honest I'm not sure what the requirements are for the new page. I have no intention of working on this issue. 👀

**Comment by linghengqian** [comment]
- It looks like https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/optional-plugins/ is the result of the current issue?

**Comment by sandynz** [comment]
That's OK.
