### ISSUE TITLE
SQL Dialect

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [apache/shardingsphere#22828]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

can i user mysql driver to connect to sharding-jdbc ,then use sharding-jdbc connect to postgreSql

**Comment by azexcy** [comment]
@Jean-Jacques-Nuoan Hi , Maybe this is what you want to know https://shardingsphere.apache.org/document/current/en/features/db-gateway/limitations/

**Comment by Jean-Jacques-Nuoan** [comment]
@azexcy  but it does not give a Description about how to use it,I tried it failed

**Comment by azexcy** [comment]
@Jean-Jacques-Nuoan For now, this is still an experimental feature, so stay tuned for it.
