### ISSUE TITLE
Wrong value of option for the selection element with id='select-version'

### ISSUE THREAD

**Issue by Jacob953** [apache/shardingsphere#22827]
## Bug Report

The value value of option for the selection element with id='select-version' is wrong. Obviously here.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/64075563/207013447-ae1008ff-d209-4a19-925a-20a29ebae5bd.png">

### Which version of ShardingSphere did you use?

latest.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

None.

### Expected behavior

For example, it should be `https://shardingsphere.apache.org/document/5.2.1/en/overview/` rather than `https://shardingsphere.apache.org/document/5.2.1.3.0/en/overview/`.

### Actual behavior

Turn to a nonexistent page.

### Reason analyze (If you can)

Wrong RE expression for Hugo.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. correct the expression at the language.html -> `replaceRE "document/[\\w|-]*" (printf "document/%s" $version) $permalink`
2. generate 5.3.0 to replace the existing document version in shardingsphere-doc.

### Example codes for reproduce this issue (such as a github link).

1. downgrade hugo to 0.93 and render pages? (a lot of related problems may raise.

**Comment by azexcy** [comment]
Hi @Jacob953 , thanks for your feedback.
Would you be interested in submitting a PR to fix it?

**Comment by Jacob953** [comment]
Yep. I'm working on this. )
