### ISSUE TITLE
Shardingsphere proxy 的distsql语句提示错误问题

### ISSUE THREAD

**Issue by zhangjianleittntty** [apache/shardingsphere#22850]
Shardingsphere proxy服务已经启动，通过mysql做了连接。
执行：> ADD RESOURCE resource_1 (........)
           > SHOW SCHEMA RESOURCES;
           > REGISTER STORAGE UNIT ds_2(.......)
等语句都提示，语法错误。都是在示例或文档中拷的语句，始终不清楚为什么会是语法错误。
如下面提示：
(1)
`You have an error in your SQL syntax: ADD RESOURCE resource_1 (
URL=jdbc:mysql://127.0.0.1:3310/orderweek_0?serverTimezone=UTC&useSSL=false,
USER=root,
PASSWORD=12345678,
PROPERTIES(maximumPoolSize=10,idleTimeout=30000)), no viable alternative at input 'ADD' at line 1, position 0, near [@0,0:2='ADD',<78>,1:0]`
(2)
`ERROR 12000 (42000): You have an error in your SQL syntax: SHOW SCHEMA RESOURCES, no viable alternative at input 'SHOWSCHEMA' at line 1, position 5, near [@1,5:10='SCHEMA',<607>,1:5]`

**Comment by azexcy** [comment]
@zhangjianleittntty 
Welcome to Apache ShardingSphere community, but only English is accepted here.
I will close this issue, please submit a new one.
Thank you!
