### ISSUE TITLE
connection disable

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#22903]
version:ShardingSphere-Proxy-5.2.1
option:When execute sql,it's happened,throw the error:connection disable.Some reason cause this?

**Comment by azexcy** [comment]
Hi @koala775 , Problems can occur for a variety of reasons,  we can't get valid information from the description, maybe you could provide more information?

**Comment by koala775** [comment]
Yes,We perform the performance test with the api，and open the XA Atomikos transtraction.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
