### ISSUE TITLE
Optimize `ShardingStatisticsTableCollector` for database postgres and openGauss

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#22902]
### Describe the feature you would like.
- Optimize `ShardingStatisticsTableCollector` for database postgres and openGauss
 ref to #21268 #22052
 We had added `sharding_table_statistics` table into `shardingsphere` database. And `ShardingStatisticsTableCollector` has supported MySQL and partial information of postgres/openGauss. This task is to complete the collect of pg/og's information.
 We can use this sql to get the data you collected.
 `select * from shardingsphere.sharding_table_statistics`

**Comment by lushaorong** [comment]
I want to try ```complete the collect of pg's information``` first

**Comment by strongduanmu** [comment]
@lushaorong Welcome, I will assign this issue to you.

**Comment by tuichenchuxin** [comment]
@lushaorong hi, is there any progress of this issue?

**Comment by lushaorong** [comment]
> @lushaorong hi, is there any progress of this issue?

Not yet. I will submit PR tomorrow
