### ISSUE TITLE
Apache CouchDB with JDBC Support

### ISSUE THREAD

**Issue by TheRook** [apache/shardingsphere#22961]
## Feature Request

CouchDB supports JDBC and has SQL-Like features and supports advanced sharding and elastic resizing.  But it doesn't look like Apache ShardingSphere supports Apache CouchDB.

This is a really good pairing and will allow the support for much larger CouchDB apps.

**Comment by FlyingZC** [comment]
Hello @TheRook, this is a great feature, but we have no plans to support it at the moment, would you want to try it.

**Comment by TheRook** [comment]
If you could support other JDBC databases in the Apache ecosystem like
CouchDB that would be greatly appreciated!

Other DBMSes have other features to offer, it is not that one database is
better in all cases, but rather use the best database for the job.  CouchDB
is unique in that it supports dynamic databases and being disconnected
entirely.

**Comment by RaigorJiang** [comment]
Closed due to no response.
By the way, the ShardingSphere community has no such plan for now, if anyone is interested, please submit a PR to add this support.

**Comment by RaigorJiang** [comment]
> @TheRook I am curious, is there anything that needs to be done on the ShardingSphere side? I don't even understand what unsupported refers to. I assume you are the Committer of CouchDB.

I think he means that CouchDB supports the JDBC protocol. If someone want to integrate with ShardingSphere, it need to at least support protocol identification, such as `DatabaseType`.
