### ISSUE TITLE
QUERY_WITH_CIPHER_COLUMN supports column-level settings

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#22964]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
When using `DistSQL` to operate `ENCRYPT` rules, it is hoped that `QUERY_WITH_CIPHER_COLUMN` can be set on the column
### Describe the feature you would like.
For example, set `user_id` and `order_id` separately.
```sql
CREATE ENCRYPT RULE t_encrypt (
COLUMNS(
    (NAME=user_id, CIPHER =user_plain, ENCRYPT_ALGORITHM(TYPE(NAME='MD5')), QUERY_WITH_CIPHER_COLUMN=TRUE),
    (NAME=order_id, CIPHER =order_cipher, ENCRYPT_ALGORITHM(TYPE(NAME='MD5')), QUERY_WITH_CIPHER_COLUMN=FALSE)
)
);
```

**Comment by RaigorJiang** [comment]
It is related to #17196.
