### ISSUE TITLE
In Legacy, document content does not match version

### ISSUE THREAD

**Issue by zhuxiaoyu118** [apache/shardingsphere#22988]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

ShardingSphere Document

ShardingSphere-5.x

![image](https://user-images.githubusercontent.com/35491513/208618111-e7307b1d-1315-4858-b60f-196de67a984b.png)

![image](https://user-images.githubusercontent.com/35491513/208617041-72ff15fd-7bb6-4e38-849f-97a563991d2d.png)

Click view in Legacy. Document content does not match version

**Comment by FlyingZC** [comment]
Hi, @zhuxiaoyu118.Thanks for your feedback, would you like to fix this issue.

**Comment by TeslaCN** [comment]
The badge shows the latest version in Maven Central. It doesn't links to a specified version.
