### ISSUE TITLE
Readwrite_splitting DistSQL document havent been update

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#22984]
Hi guys,
     I found that the DistSQL document of the `create/alter static readwrite_splitting rule` syntax and example haven't been updated. 

#### screenshot of the document
![image](https://user-images.githubusercontent.com/57847965/208609831-334ac8a2-fa11-4e7a-97b1-6c19f952314b.png)

#### the syntax now should be:
```
CREATE READWRITE_SPLITTING RULE ms_group_0 (
    WRITE_STORAGE_UNIT=write_ds,
    READ_STORAGE_UNITS(read_ds_0,read_ds_1),
    TYPE(NAME="random")
);
```

**Comment by FlyingZC** [comment]
Thanks for your feedback.
