### ISSUE TITLE
sharding-algorithms.xxx.props cannot read values from yaml normally

### ISSUE THREAD

**Issue by duanqiaoyanyu** [apache/shardingsphere#22989]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
props can set values from yaml normally

### Actual behavior
sharding-algorithms.algorithm-name.props cannot inject values when algorithm-name is begin with a Upper alphabet

### Reason analyze (If you can)
some logic cannot allow Upper alphabet begins algorithms

**Comment by FlyingZC** [comment]
@duanqiaoyanyu thanks for your feedback,can you provide an example of the problem.

**Comment by RaigorJiang** [comment]
Closed due to no response.
