### ISSUE TITLE
The latest version 5.3.0 cannot be found in the legacy

### ISSUE THREAD

**Issue by zhuxiaoyu118** [apache/shardingsphere#22987]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).

ShardingSphere Document

ShardingSphere-5.3.0

![image](https://user-images.githubusercontent.com/35491513/208614650-6e65b027-4d6e-4694-95f9-952b4cf6082a.png)

The latest version 5.3.0 cannot be found at https://shardingsphere.apache.org/legacy.html

**Comment by FlyingZC** [comment]
You can find the 5.3.0 document in latest release. https://shardingsphere.apache.org/document/5.3.0/en/overview/
<img width="401" alt="image" src="https://user-images.githubusercontent.com/19788130/208623478-e78aacf4-06b2-4855-af82-29c0be8abe43.png">
