### ISSUE TITLE
ShardingSphere-Proxy5.1.2 MySQL查询报错

### ISSUE THREAD

**Issue by li463619361** [apache/shardingsphere#23017]
![4b0856ef525eb85319e3510a39087c3](https://user-images.githubusercontent.com/34559980/208876071-9bfc1bcf-279a-42b4-9af1-80b2b4cd6686.png)
![4e20225969c4d3d47e6cb62ab8bee2f](https://user-images.githubusercontent.com/34559980/208876078-a950f255-cb6a-4538-b5d9-1cf12b39bb18.png)
![19eb8dbd02c3d52ec3428f3ec28f0b1](https://user-images.githubusercontent.com/34559980/208876083-bf9b183c-fa7c-48bd-aade-38ad3507e839.png)
![137e7f77c6a17684eba7fd2fe5e9553](https://user-images.githubusercontent.com/34559980/208876085-5d21d7e0-5a9a-4206-9031-f0624ad65494.png)
![516b9114d1b9ce8f24fc0f7f9ee1477](https://user-images.githubusercontent.com/34559980/208876088-504b1d38-6720-495e-a8e8-e91875c9e34d.png)
![cb775d0e21d2eedf9e2e2d176bef9aa](https://user-images.githubusercontent.com/34559980/208876095-b82981e8-8b73-43cd-9dba-78ba73323e10.png)
![f91c497f2a472ceff7ef86feb838c61](https://user-images.githubusercontent.com/34559980/208876100-7a67b974-0718-43e1-b610-b1db5c321dea.png)
项目中引入这个好多增查报错 大牛有什么好的一劳永逸解决方案

**Comment by FlyingZC** [comment]
Please describe your issue in English according to the issue template, other languages will be closed directly.
