### ISSUE TITLE
Like query algorithm support '_' match

### ISSUE THREAD

**Issue by gxxiong** [apache/shardingsphere#23029]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
The like query algorithm does not support '_' match
### Describe the feature you would like.
Like query algorithm support '_' match

**Comment by strongduanmu** [comment]
Thank you @gxxiong, that's a really good suggestion.
