### ISSUE TITLE
Remove data types from `SHOW ENCRYPT RULES`.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23023]
Hi community,

There are some data types in result set of `SHOW ENCRYPT RULES`,  like logic_data_type, cipher_data_type. 
But actually there is no data type in `EncryptColumnRuleConfiguration`, we can not get any result about type.
So we need to remove data type from `SHOW ENCRYPT RULES`.

Ref: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rql/rule-query/encrypt/

### Tasks
- [ ] remove data type from `SHOW ENCRYPT RULES`;
- [ ] Update test cases
- [ ] Update document

**Comment by Qianyi951015** [comment]
please assign to me thx
