### ISSUE TITLE
Authority  rule support distsql

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#23024]
just like create user distsql on running.

**Comment by FlyingZC** [comment]
@McClone Hi, would you want to design this feature. @RaigorJiang hi,please have a look.

**Comment by McClone** [comment]
> @McClone Hi, would you want to design this feature. @RaigorJiang hi,please have a look.

There's nothing I can do

**Comment by RaigorJiang** [comment]
Hi @McClone @FlyingZC ,
I think doing this currently will bring a security issue as we can't identify which users are able to do `create user` or `drop user`.

**Comment by McClone** [comment]
> Hi @McClone @FlyingZC , I think doing this currently will bring a security issue as we can't identify which users are able to do `create user` or `drop user`.

It is possible to have a default user root like MySQL

**Comment by RaigorJiang** [comment]
No plan, and there are still security issues, so close this issue for now.
