### ISSUE TITLE
Can supoort other database procotol,like oracle、sql server?

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#23038]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
no
### Describe the feature you would like.
Can supoort other database procotol,like oracle、sql server?

**Comment by FlyingZC** [comment]
@McClone hi,we have no plans to support these now, would you want to have a try.

**Comment by McClone** [comment]
> @McClone hi,we have no plans to support these now, would you want to have a try.

I'd love to, but I don't know how to do that, can I be guided

**Comment by terrymanu** [comment]
Please read the SQLServer protocol https://learn.microsoft.com/en-us/openspecs/sql_server_protocols/ms-sqlprotlp/f16558b2-4561-45be-89c9-6f9114514c97, and reference shardingsphere-mysql-protocol module to get some idea
