### ISSUE TITLE
Use way of AgentServiceLoader to simplify ShardingSphereServiceLoader

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#23035]
AgentServiceLoader is the better way to initialize SPI classes. 
It creates a new AgentServiceLoader singleton for each SPI class.

The advantages are: 

1. Never register SPI manually again;
1. All SPI factories can be removed;
1. Unit tests can be simplified too.

**Comment by strongduanmu** [comment]
I like this new way, it can reduce a lot of coding work.
