### ISSUE TITLE
Route table question

### ISSUE THREAD

**Issue by wangjiihao** [apache/shardingsphere#23048]
When routing table names, the administrator needs to be able to query all tables during operation. How should I operate in the algorithm? Should I return null? When the administrator logs in, the partition key value is "1"

**Comment by wangjiihao** [comment]
public static String routeTable(String value, String logictable) {
        String resultTab = "";
        if ("1".equals(value)){
            return null;
        }else if (value.startsWith(HEBEI.getCode())){
            resultTab = logictable +"1";
        }else if (value.startsWith(SHANXI.getCode())){
            resultTab = logictable +"2";
        }else if (value.startsWith(NEIMENGGU.getCode())){
            resultTab = logictable +"3";
        }else if (value.startsWith(LIAONING.getCode())){
            resultTab = logictable +"4";
        }else if (value.startsWith(JILIN.getCode())){
            resultTab = logictable +"5";
        }else if (value.startsWith(HEILONGJIANG.getCode())){
            resultTab = logictable +"6";
        }else if (value.startsWith(JIANGSU.getCode())){
            resultTab = logictable +"7";
        }else if (value.startsWith(ZHEJIANG.getCode())){
            resultTab = logictable +"8";
        }else if (value.startsWith(ANHUI.getCode())){
            resultTab = logictable +"9";
        }else if (value.startsWith(FUJIAN.getCode())){
            resultTab = logictable +"10";
        }else if (value.startsWith(JIANGXI.getCode())){
            resultTab = logictable +"11";
        }else if (value.startsWith(SHANDONG.getCode())){
            resultTab = logictable +"12";
        }else if (value.startsWith(HENAN.getCode())){
            resultTab = logictable +"13";
        }else if (value.startsWith(HUBEI.getCode())){
            resultTab = logictable +"14";
        }else if (value.startsWith(HUNAN.getCode())){
            resultTab = logictable +"15";
        }else if (value.startsWith(GUANGDONG.getCode())){
            resultTab = logictable +"16";
        }else if (value.startsWith(GUANGXI.getCode())){
            resultTab = logictable +"17";
        }else if (value.startsWith(HAINAN.getCode())){
            resultTab = logictable +"18";
        }else if (value.startsWith(SICHUAN.getCode())){
            resultTab = logictable +"19";
        }else if (value.startsWith(GUIZHOU.getCode())){
            resultTab = logictable +"20";
        }else if (value.startsWith(YUNNAN.getCode())){
            resultTab = logictable +"21";
        }else if (value.startsWith(XIZANG.getCode())){
            resultTab = logictable +"22";
        }else if (value.startsWith(SHANXI1.getCode())){
            resultTab = logictable +"23";
        }else if (value.startsWith(GANSU.getCode())){
            resultTab = logictable +"24";
        }else if (value.startsWith(QINGHAI.getCode())){
            resultTab = logictable +"25";
        }else if (value.startsWith(NINGXIA.getCode())){
            resultTab = logictable +"26";
        }else if (value.startsWith(XINJIANG.getCode())){
            resultTab = logictable +"27";
        }else if (value.startsWith(BEIJING.getCode())){
            resultTab = logictable +"28";
        }else if (value.startsWith(CHONGQING.getCode())){
            resultTab = logictable +"29";
        }else if (value.startsWith(TIANJIN.getCode())){
            resultTab = logictable +"30";
        }else if (value.startsWith(SHANGHAI.getCode())) {
            resultTab = logictable + "31";
        }else {
            resultTab = logictable +"0";
        }
        return resultTab;
    }

**Comment by strongduanmu** [comment]
Hi @wangjiihao, can you submit issue according to issue template?

**Comment by RaigorJiang** [comment]
Closed due to no response.
