### ISSUE TITLE
Possible nioEventLoop leakage in MySQL data pipeline

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#23055]
### Which version of ShardingSphere did you use?

master - 04f521f79edadcc3c427133c40089c5823e3e221

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

No leakage.

### Actual behavior

![image](https://user-images.githubusercontent.com/20503072/209281186-282e2b48-d5c0-40f5-ae8c-64ed5be7be3e.png)

![image](https://user-images.githubusercontent.com/20503072/209281149-3b5ed080-21a6-4899-813b-0fe3f798b04e.png)

![image](https://user-images.githubusercontent.com/20503072/209282918-0b7f0209-6830-4ea7-b92b-d7b71ff3e914.png)

### Reason analyze (If you can)

Epoll is available. But event loop groups are nio. So the event loop may belong to MySQLClient.
EventLoopGroup was not shutdown in MySQLClient.

**Comment by azexcy** [comment]
I will follow this.
