### ISSUE TITLE
Add more test cases for ReflectionUtil

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#23078]
Add test cases for:

- [ ] getFieldValue
- [ ] invokeMethod

**Comment by aryan19926** [comment]
hello
My name is aryan.
I would to love to help in this project.
Could you please help me to get started?

**Comment by sandynz** [comment]
Hi @aryan19926 , welcome!
You could have a look at [Get Involved]( https://shardingsphere.apache.org/community/en/involved/ ), specially Contribute Guide and Contribute Conduct.

**Comment by aryan19926** [comment]
Hello
I'm a beginner and really want to help.
I've read the GET INVOLVED section .
Could to please guide to me a bit more ? as I am unable to find the necessary files to make changes .
Thanks.

**Comment by sandynz** [comment]
Hi @aryan19926 , have you setted up [DEV Environment]( https://shardingsphere.apache.org/community/en/involved/contribute/dev-env/ ) for Java development?

You could learn how to do Java unit test before starting it, e.g. [example]( https://www.baeldung.com/java-unit-testing-best-practices ), and then have a look at [Unit Test of Conduct]( https://shardingsphere.apache.org/community/en/involved/conduct/code/#contributor-covenant-unit-test-of-conduct ).

Then search `ReflectionUtil` and `ReflectionUtilTest` in IDE. There're already some unit tests in `ReflectionUtilTest`, you could add more unit tests in it.

**Comment by aryan19926** [comment]
Yes I have setted up DEV Environment .
Okay 
Thanks  for replying.

**Comment by aryan19926** [comment]
Just to update you.
I have studied Java Unit Testing.
Now studying java reflection.
Will try adding more test cases in a day or two.
Thanks

**Comment by sandynz** [comment]
@aryan19926 Nice. Keep going forward

**Comment by ShivaReddyVanja** [comment]
hey iam shiva, i am a complete beginner, i am trying to get into open source , i dont know where to start or what to learn,please help me to get started

**Comment by sandynz** [comment]
> hey iam shiva, i am a complete beginner, i am trying to get into open source , i dont know where to start or what to learn,please help me to get started

Hi @ShivaReddyVanja , welcome!

You could have a look at:
- Java Programming Language, and related tools (e.g. Maven)
- Java Unit Test
- [Get Involved](https://shardingsphere.apache.org/community/en/involved/), specially Contribute Guide and Contribute Conduct.

Then try to pick a [good first issue]( https://github.com/apache/shardingsphere/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 ) to start contribution of Apache ShardingSphere.

And also you could have a look at [hackertoberfest completed PRs]( https://github.com/apache/shardingsphere/pulls?q=is%3Apr+label%3Ahacktoberfest+is%3Aclosed ) as examples.
