### ISSUE TITLE
【binding-tables】Why does my idea report this error "Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.binding-tables[0]' "

### ISSUE THREAD

**Issue by ricklin97** [apache/shardingsphere#23094]
when I use 
"`spring.shardingsphere.rules.sharding.binding-tables[0]=t_order,t_order_item`",
 idea report this error"**Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.binding-tables[0]'** ".
and code cannot be executed

thanks~

**Comment by TeslaCN** [comment]
Spring modules have been deprecated and removed since 5.3.0. Please use the ShardingSphere-JDBC in Driver way. https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/
