### ISSUE TITLE
Performing unsupported query

### ISSUE THREAD

**Issue by theodoretsai** [apache/shardingsphere#23110]
## Question

I need to manually control locks in PostgreSQL, but running them with a sharded connection will produce org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL, is there a way to manually route such queries avoiding the parsing engine and work around the problem?

SQLs I need to run are like:
```
NOWAIT_SQL = lock table %1$s in access share mode nowait;
```

```
PreparedStatement lockSm = connectionCache.prepareStatement(
                        String.format(NOWAIT_SQL, table),
                        ResultSet.TYPE_FORWARD_ONLY,
                        ResultSet.CONCUR_READ_ONLY);
PreparedStatement sm = connectionCache.prepareStatement(
                        "select * from " + table + ";",
                        ResultSet.TYPE_FORWARD_ONLY,
                        ResultSet.CONCUR_READ_ONLY);
connection.setAutoCommit(false);
lockSm.execute();
rs = sm.executeQuery();
...
connectionCache.commit();
connectionCache.setAutoCommit(true);
```

**Comment by TeslaCN** [comment]
I can't execute this SQL in PostgreSQL 14. Could you clarify?

![image](https://user-images.githubusercontent.com/20503072/209772436-8fb6f57b-f338-4a8a-a364-d96cbfa23a09.png)

**Comment by theodoretsai** [comment]
I should have used ? as placeholder for tablename, sorry.
That was the prototype code for testing, so I was just using String format to inject parameters into the sql, %1$s should be replaced by a table name you intend to lock.

**Comment by TeslaCN** [comment]
Could you try the ShardingSphere 5.3.0?
I tried executing SQL in ShardingSphere-Proxy PostgreSQL. The SQL could be parsed and executed.
![image](https://user-images.githubusercontent.com/20503072/209773144-59998b91-c2b4-4a33-831b-0422c0471cd7.png)

**Comment by TeslaCN** [comment]
It seems that the SQL is supported by ShardingSphere's Parser.
![image](https://user-images.githubusercontent.com/20503072/209773406-1bb51f45-8961-4e43-b4be-0dff1539c3f7.png)

**Comment by theodoretsai** [comment]
Thanks, I was using version 4.0.1, will try 5.3.0. But in a more generic case I suppose there is no way to bypass the parser if needed?

**Comment by TeslaCN** [comment]
> Thanks, I was using version 4.0.1, will try 5.3.0. But in a more generic case I suppose there is no way to bypass the parser if needed?

There is no such way for now.
