### ISSUE TITLE
Add more test cases for ClusterModeContextManager

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#23123]

**Comment by jeffuofa93** [comment]
I can take a stab at this. First time contributing. Let me know if theirs any other details needed to get started.

**Comment by jeffuofa93** [comment]
Can have this done by 12/29 if I don't hit any major roadblocks

**Comment by TeslaCN** [comment]
Welcome @jeffuofa93 
Assigned to you.
@zhaojinchao95 Please clarify the issue or provide some help if necessary.

**Comment by tristaZero** [comment]
Welcome @jeffuofa93 !

**Comment by zhaojinchao95** [comment]
> 

Nice, you can communicate at any time if you has problems

**Comment by zhaojinchao95** [comment]
> I can take a stab at this. First time contributing. Let me know if theirs any other details needed to get started.

You need to understand Mock, you can refer to `DatabaseMetaDataPersistServiceTest.class`

**Comment by tristaZero** [comment]
@jeffuofa93 The steps FYI,
1. Create a test class named `ClusterModeContextManagerTest` in general in its test dir.
2. Create `assertXXX` functions to do tests for these important functions of `ClusterModeContextManager`
3.  Refer to `DatabaseMetaDataPersistServiceTest.class` to write this new one.

**Comment by jeffuofa93** [comment]
On it! Will reach out if I have any questions thank you for the help!

**Comment by jeffuofa93** [comment]
Hi @zhaojinchao95, 

Been working on the testing and just wanted to touch base to check if I'm headed down the right path on this issue. Here is a link to a gist of my code so far [current implementation](https://gist.github.com/jeffuofa93/91db92d1ca7dedb5dbe55e4f86229735) and the current branch [forked repo branch 231123](https://github.com/jeffuofa93/shardingsphere/tree/231123). I'm a little unsure of where at what level I should be using the verify calls on. I've tried to copy the structure of the provided example as best as best as possible but the classes are constructed slightly different. 

No rush to take a look I will continue to work on my implementation and let you know if I have other questions. Thanks!

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95,
> 
> Been working on the testing and just wanted to touch base to check if I'm headed down the right path on this issue. Here is a link to a gist of my code so far [current implementation](https://gist.github.com/jeffuofa93/91db92d1ca7dedb5dbe55e4f86229735) and the current branch [forked repo branch 231123](https://github.com/jeffuofa93/shardingsphere/tree/231123). I'm a little unsure of what level I should be using the verify calls on. I've tried to copy the structure of the provided example as best as best as possible but the classes are constructed slightly different.
> 
> No rush to take a look I will continue to work on my implementation and let you know if I have other questions. Thanks!

Cool, i think you idea are right. you can keep doing it.

**Comment by kanha-gupta** [comment]
Hey, I've seen the codebase, would submit a PR soon :)
