### ISSUE TITLE
Refactor DataSourceContainedRule#getDataSourceMapper return type for easy use

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#23133]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Currently, the DataSourceContainedRule#getDataSourceMapper interface is declared as follows. The result is a `Map<String, Collection<String>>` structure, which is not easy to use. For example: I want to get the primary data source from this Map.

```java
/**
 * ShardingSphere rule which contains data source.
 */
public interface DataSourceContainedRule extends ShardingSphereRule {
    
    /**
     * Get data source mapper.
     *
     * @return data source mapper
     */
    Map<String, Collection<String>> getDataSourceMapper();
}
```

**Comment by FlyingZC** [comment]
Fixed by #25388
