### ISSUE TITLE
postgresql sql parse

### ISSUE THREAD

**Issue by gx-march** [apache/shardingsphere#23141]
### Which version of ShardingSphere did you use?
5.2.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
![image](https://user-images.githubusercontent.com/87351847/209797171-40ac0ad5-1fce-4a3a-9ae9-f8ca2a627c99.png)

sql keyword cannot be resolved. I'm trying to add a keyword ``,But to no avail.

**Comment by gx-march** [comment]
![image](https://user-images.githubusercontent.com/87351847/209797480-de89dae5-5678-44c1-9fac-e534ea808a1a.png)

**Comment by TeslaCN** [comment]
Hi @gx-march 
Please try using double quote, such as `"date"`.

**Comment by gx-march** [comment]
> 你好@gx-march 请尝试使用双引号，例如`"date"`.

thanks, Your suggestion is valid
