### ISSUE TITLE
Add e2e test for SQL HINT.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#23184]
# BackGround
Through this #20736, we support SQL HINT. 
There are currently two ways, one is to enable the comment parsing switch `sqlCommentParseEnabled: true`, then the information of SQL HINT will be extracted through antlr parser. 
The other is to turn off the comment parsing switch `sqlCommentParseEnabled: false`, which allows the same SQL but different comment information to use the same cache, thereby improving performance.
# Task

- [ ] Add e2e test for SQL HINT with `sqlCommentParseEnabled: true`
- [ ] Add e2e test for SQL HINT with `sqlCommentParseEnabled: false`

I have added one test for example.
https://github.com/apache/shardingsphere/pull/22727

**Comment by dongzl** [comment]
Hi @tuichenchuxin , I will try it.

**Comment by tuichenchuxin** [comment]
@dongzl hi, how has this issue progressed lately?

**Comment by strongduanmu** [comment]
This task is obsolete since the latest version has removed sqlCommentParseEnabled.
