### ISSUE TITLE
JDBCRepository#delete should avoid using String#format when printing Log

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#23218]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- No.

### Describe the feature you would like.

- For https://github.com/apache/shardingsphere/blob/master/mode/type/standalone/repository/provider/jdbc/core/src/main/java/org/apache/shardingsphere/mode/repository/standalone/jdbc/JDBCRepository.java , its #getDirectly, #getChildrenKeys, #persist, #persist are all processed with consistent Log.
```java
log.error("Get {} data by key: {} failed", getType(), key, ex);
log.error("Get children {} data by key: {} failed", getType(), key, ex);
log.error("Persist {} data to key: {} failed", getType(), key, ex);
log.error("Update {} data to key: {} failed", getType(), key, ex);
```
- except for #delete . I think JDBCRepository#delete should avoid String#format .
```java
log.error(String.format("Delete %s data by key: {} failed", getType()), key, ex);
```

**Comment by zhaojinchao95** [comment]
Yes, you are right. Can you fix it?

**Comment by linghengqian** [comment]
- I'm working on this issue.
