### ISSUE TITLE
WeightReplicaLoadBalanceAlgorithm props init fail

### ISSUE THREAD

**Issue by maziqiang12138** [apache/shardingsphere#23237]
project start error log 
Caused by: java.lang.IllegalStateException: Readwrite-splitting data source weight config are required in database `logic_db`.

yaml:
`    rules:
      readwrite-splitting:
        data-sources:
          test:
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave1,slave2
            load-balancer-name: customWeight
        load-balancers:
          customWeight:
            type: WEIGHT
            props:
              slave1: 7
              slave2: 3`
same yaml my test demo can start success

**Comment by jiangML** [comment]
As described in the exception, can you try to configure the `data-sources` as logic_db?

**Comment by RaigorJiang** [comment]
Hi @maziqiang12138 , please provide your ShardingSphere version and rule configuration, thank you!

**Comment by RaigorJiang** [comment]
Closed due to no response.
