### ISSUE TITLE
WeightReadQueryLoadBalanceAlgorithm props null

### ISSUE THREAD

**Issue by maziqiang12138** [apache/shardingsphere#23246]
The prop is normal when initializing the WeightReadQueryLoadBalanceAlgorithm, but the props of the WeightReadQueryLoadBalanceAlgorithm are null when creating the druid data source
springboot 2.2.5
druid 1.1.22
mybatis 1.3.2
shardingjdbc 5.1.2

**Comment by maziqiang12138** [comment]
The reason cannot be found. The same configuration can be obtained after creating a demo project. Is there any other conflict? There is no clue

**Comment by maziqiang12138** [comment]
初始化
<img width="926" alt="image" src="https://user-images.githubusercontent.com/39107589/210165927-802ee053-f41a-43ca-9c60-ff8f9d5a0995.png">
创建数据源
<img width="969" alt="image" src="https://user-images.githubusercontent.com/39107589/210165975-553057e2-dd25-4852-aa1a-1c113ad1b9bb.png">

**Comment by zhaojinchao95** [comment]
Show your configuration please and by the way, you can use `ShardingSphere-5.3.0` try it again.

**Comment by maziqiang12138** [comment]
> 
Thank you for your reply. I can run with version 5.1.1. It should be a version compatibility problem
