### ISSUE TITLE
Remove the spring settings in maven which is out of date

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#23273]
there are some spring settings in maven like followings :

```
./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
```

and now it's exclude from ss core, should be removed.

**Comment by sandynz** [comment]
spring namespace and spring boot starter modules were removed, and also spring version range in pom.xml, so versions:resolve-ranges in CI is not necessary any more.

I just remember to remove it and find it's done. Thanks
