### ISSUE TITLE
Add unit test for MaskAlgorithmUtil

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#23292]
This issue is to add unit tests for the MaskAlgorithmUtil class and includes the following subtasks:

- [ ] MaskAlgorithmUtil#checkSingleCharConfig
- [ ] MaskAlgorithmUtil#checkAtLeastOneCharConfig
- [ ] MaskAlgorithmUtil#checkIntegerTypeConfig

**Comment by gxxiong** [comment]
I'll try

**Comment by strongduanmu** [comment]
@gxxiong Welcome, I will assign this issue to you.

**Comment by akhil9281** [comment]
Hello, I would like to work on this issue.

**Comment by strongduanmu** [comment]
Hi @akhil9281, do you want to try other issues? Such as - https://github.com/apache/shardingsphere/issues/16841.

**Comment by akhil9281** [comment]
I took a look at #16841 and I'm not really interested in that. But I'll keep an eye out for new issues. Thank you
