### ISSUE TITLE
Resolved [org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction]

### ISSUE THREAD

**Issue by YashRaj011** [apache/shardingsphere#23304]
**I'm getting this error I don't know why can anyone help me?**

![Screenshot_20230103_171047](https://user-images.githubusercontent.com/88896207/210350542-7639cba0-3a93-4e6b-ae6e-2e5f1a631594.png)

**My user class is :**

![Screenshot_20230103_171504](https://user-images.githubusercontent.com/88896207/210351127-e976ceef-9f7f-4be5-ab0b-00175a74f1f1.png)
![image](https://user-images.githubusercontent.com/88896207/210351238-3031ff73-d630-4f0a-921f-9cc0872820f7.png)

**Service class for registration**

![Screenshot_20230103_171713](https://user-images.githubusercontent.com/88896207/210351471-1e707e91-ec48-4929-a2fa-a095c889cdc6.png)

**Repository**

![Screenshot_20230103_171826](https://user-images.githubusercontent.com/88896207/210351589-bcb69271-73e9-4355-8d8a-d8c527cb3c3e.png)

**Database table desc**

![Screenshot_20230103_171916](https://user-images.githubusercontent.com/88896207/210351703-5ca60d4b-7672-4ab8-8b5d-ab0e00755584.png)

Please help me find the solution!

**Comment by jiangML** [comment]
Hi @YashRaj011 please provide your ShardingSphere version and rule configuration, thank you!

**Comment by YashRaj011** [comment]
Hey @jiangML sorry to tell you but, I am new to spring boot can you please tell me what is shardingsphere and its rule config

**Comment by YashRaj011** [comment]
I am stuck at this part for past 2 days and have no idea what to do

**Comment by YashRaj011** [comment]
Here what i have encountered now is when i comment the cnfrmPassword field in the User.java(user class) and commenting the fieldValueMatch annotation it is working fine. But when i mention it as done above i am getting the same error (org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction)

**Comment by linghengqian** [comment]
> Hey @jiangML sorry to tell you but, I am new to spring boot can you please tell me what is shardingsphere and its rule config

- If you don't know what ShardingSphere is, and your picture has nothing to do with ShardingSphere, why don't you ask Spring Boot?

**Comment by RaigorJiang** [comment]
Sorry, this issue is not related to ShardingSphere, I will close it.

**Comment by YashRaj011** [comment]
Ohhk my bad sorry guyss


And thank you.
