### ISSUE TITLE
where can I see unsupported sql(mysql)?

### ISSUE THREAD

**Issue by Ryoui** [apache/shardingsphere#23349]
where can I see the unsupported sql and functions and their relationship to the version?
i didn't find that description in the official documentation.

**Comment by jiangML** [comment]
Hi @Ryoui 
You can view the latest daily results in `Nightly - SQL parser loading from external cases` Actions.
https://github.com/apache/shardingsphere/actions/workflows/nightly-sql-parser.yml

![image](https://user-images.githubusercontent.com/16010265/210758119-4b707482-cf21-4c52-a589-92870280ed52.png)
