### ISSUE TITLE
Significant performance degradation when executing DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23344]
Hi community,

Since the 5.3.1 release is approaching (#23328), I conducted a performance test on DistSQL and found some phenomena:
1. Every time DistSQL RDL is executed, the `DatabaseMetaDataPersistService#loadSchemas` method will be triggered, which includes the operation of loading table metadata;
2. When the number of tables reaches tens or hundreds, loadSchemas may take several seconds or tens of seconds;

Here is a test script that executes these SQLs sequentially (or in batches with programs), and you can find a significant increase in time-consuming.
[distsql.sql.zip](https://github.com/apache/shardingsphere/files/10350307/distsql.sql.zip)

The following is the profiling result obtained after executing these SQLs:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/5668787/210727831-9e64f980-c658-4863-9739-80b5682f64b0.png">

**Comment by zhaojinchao95** [comment]
I will follow it.
