### ISSUE TITLE
Copyright format is still not unified

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23385]
Ref #21643

There are still some files with inconsistent copyright format:
- cursor-command.xml
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/5668787/211055027-3db19893-2ae4-4b5e-bc06-5ddb97e67312.png">

- test/e2e/agent/plugins/jaeger/pom.xml
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/5668787/211055374-b4bb12c4-7466-435e-9857-8256b36279bf.png">

- maven-wrapper.properties
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/5668787/211056447-5e180341-b06d-449d-8430-3bd3793ccd21.png">

- .licenserc.yaml
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/5668787/211057280-85cff3c7-4362-46f3-bcb8-16f586a3c19e.png">

- mvnw
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/5668787/211058724-225e53bb-a295-4a3d-a8bf-16cd1756c98f.png">

- file.conf & registry.ftl etc.
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/5668787/211059087-6b08c42c-fb8f-41d7-80a0-4eb915b5b8aa.png">

**Comment by Qianyi951015** [comment]
please assign to me thx
