### ISSUE TITLE
Welcome to leave your company's information

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#234]
Welcome to register by `company` + `homepage` + `use case(optional)`, your support is important to us.
We will sync to [official website](https://shardingsphere.apache.org/community/en/powered-by/) periodically.

**Comment by mi2004** [comment]
广东优茶大数据 www.utea20.com

**Comment by git-chenhao** [comment]
上海定菱网络科技有限公司+http://www.qbaolive.com/

**Comment by fengjianquan9527** [comment]
上海九脉信息技术有限公司(东方车联)+http://www.dongfang789.com

**Comment by terrymanu** [comment]
山东佰昌信息科技有限公司 http://www.sdbaichang.com

**Comment by dzxiang** [comment]
北京真信认知科技有限公司  http://www.zhenxinsafe.com/

**Comment by terrymanu** [comment]
北京家视天下科技有限公司 http://www.hiveview.com/

**Comment by zhaoming-mike** [comment]
sharding 拼写错了哦！

**Comment by terrymanu** [comment]
已修正，多谢指出

**Comment by wu191287278** [comment]
视觉中国 https://500px.me

**Comment by xuminwlt** [comment]
足记 http://www.fotoplace.cc

**Comment by terrymanu** [comment]
转转公司 http://www.zhuanzhuan.com

**Comment by kingcodeyu** [comment]
深圳小牛在线https://www.xiaoniu88.com/

**Comment by wangda** [comment]
特微智能 http://www.trawe.cn

**Comment by duerlatter** [comment]
中策车空间 http://www.zcckj.com

**Comment by terrymanu** [comment]
唯品会 http://www.vip.com

**Comment by zhikaichen123** [comment]
TCL http://yq.tclo2o.cn

**Comment by zackwrj** [comment]
食蚁兽网络 http://www.41soo.com

**Comment by chinacode** [comment]
深圳男衣库科技有限公司 https://www.nanyiku.com/

**Comment by yiwugou** [comment]
义乌购 http://www.yiwugou.com

**Comment by terrymanu** [comment]
凤凰汽车 http://auto.ifeng.com/

**Comment by terrymanu** [comment]
搜狐资讯 http://ss.sohu.com/

**Comment by tietang** [comment]
客如云 http://www.keruyun.com

**Comment by FlorentinoWen** [comment]
广西壮族自治区国土资源信息中心 + z.gxdlr.gov.cn

**Comment by gfreezy** [comment]
下厨房 http://www.xiachufang.com

**Comment by Mailerm** [comment]
深圳市神州路路通网络科技有限公司 https://660pp.com

**Comment by komawei** [comment]
深圳市赢家服饰有限公司 http://www.eeka.cn/

**Comment by hubigsea** [comment]
中通快递股份有限公司  http://www.zto.com/

**Comment by terrymanu** [comment]
赛特斯CertusNet http://www.certusnet.com.cn/

**Comment by Breggor** [comment]
别吃胖 http://www.biechipang.net/index.html

**Comment by yekairush** [comment]
华夏信财https://www.huaxiafinance.com/

**Comment by lihbing** [comment]
你我金融https://www.niiwoo.com/

**Comment by 15827071127** [comment]
微视听http://www.91vst.com/

**Comment by 15827071127** [comment]
CIBN微视听（原全聚合）http://www.91vst.com/

**Comment by baidan** [comment]
五谷图像 http://www.5grain.com/

**Comment by aloxc** [comment]
天涯社区 http://www.tianya.cn

**Comment by xiaoliqiang** [comment]
oppo  http://www.oppo.com

**Comment by bingzhilanmo** [comment]
货车帮 http://www.huochebang.com/

**Comment by slatonwu** [comment]
首汽约车   http://www.01zhuanche.com/

**Comment by aseaday** [comment]
上海南潮信息科技有限公司 https://ruff.io

**Comment by terrymanu** [comment]
浙江育体科技有限公司 http://www.tvlongmaop.com

**Comment by zjqwll** [comment]
浙江育体科技有限公司 http://www.tvlongmao.com

**Comment by jklliang** [comment]
海尔金融控股集团-海尔消费金融 www.haiercash.com  870558761求进qq群

**Comment by TaXueWWL** [comment]
高阳捷迅信息技术有限公司  http://www.19pay.com.cn/

**Comment by xiaofuhao** [comment]
我爱卡  www.51credit.com

**Comment by lianzhichao** [comment]
丽人丽妆 http://www.lrlz.com/

**Comment by huisongyang** [comment]
中通快递 www.zto.com

**Comment by firebata** [comment]
黑胡子游戏  [www.bbgameonline.com](www.bbgameonline.com)

**Comment by loysen** [comment]
浙江众匠信息技术有限公司+http://www.youx.mobi/

**Comment by linminqin** [comment]
随手记 www.sui.com

**Comment by xunzhaotianhe** [comment]
美丽金融 https://www.mljr.com/

**Comment by sunnykaka** [comment]
团贷网 https://www.tuandai.com

**Comment by ofdata** [comment]
京东商城海外站 https://www.jd.ru https://www.joybuy.com

**Comment by sixizi** [comment]
京东金融+http://jr.jd.com

**Comment by xunzhaotianhe** [comment]
美利金融这几个字我上次写错了，写成了“美丽金融”，现在sj官网-社区-采用公司 这里显示的是“美丽金融”，可以修改成“美利金融”吗，谢谢

**Comment by terrymanu** [comment]
@xunzhaotianhe 已修正

**Comment by tristaZero** [comment]
@liunianmoshi 感谢支持，已加入使用公司列表~

**Comment by tristaZero** [comment]
@weilp 感谢支持，已加入~[使用公司列表](http://shardingjdbc.io/community/cn/03-company/)

**Comment by zichuangyang** [comment]
北京云庐科技有限公司 www.cloudansys.com

**Comment by tristaZero** [comment]
@zichuangyang 欢迎加入~
已加入 [使用公司列表](http://shardingsphere.io/community/cn/03-company/)

**Comment by bai020** [comment]
哔哩哔哩弹幕网，https://www.bilibili.com/
哔哩哔哩(゜-゜)つロ干杯~-bilibili

**Comment by tristaZero** [comment]
欢迎使用~已经入使用公司列表！ @bai020

**Comment by waterless** [comment]
掌趣

**Comment by eaglewa** [comment]
百姓网+http://www.baixing.com/

**Comment by JiXiaodong** [comment]
每日优鲜便利购 www.imrfresh.com

**Comment by tristaZero** [comment]
Welcome and thanks for joining us. @JiXiaodong 
Your company now is in [End users' List](http://shardingjdbc.io/community/cn/03-company/)

**Comment by markflyfly** [comment]
兔展，快速制作H5平台  [www.rabbitpre.com](www.rabbitpre.com)

**Comment by tristaZero** [comment]
Welcome and thanks for joining us. @markflyfly 
Your company now is in [End users' List](http://shardingsphere.io/community/cn/company/)

**Comment by markflyfly** [comment]
@tristaZero thanks too!

**Comment by jack-zdl** [comment]
策赢平台 https://www.cypfintech.com/[https://www.cypfintech.com/](url)

**Comment by jack-zdl** [comment]
策赢平台 https://www.cypfintech.com/

**Comment by cxdhefei** [comment]
科大讯飞 http://www.iflytek.com/

**Comment by windawaken** [comment]
小航狗有限公司

**Comment by anjingxz** [comment]
京东大数据与智能供应链事业部

**Comment by lferic** [comment]
好未来培优研发部+培优业务系统

**Comment by joey168** [comment]
东莞市大易产业链服务有限公司 https://www.dayi35.com

**Comment by junejs** [comment]
慧影科技（北京）有限公司 + http://www.huiyihuiying.com/ + AI医疗

**Comment by haroldjiang** [comment]
大家用sharding-jdbc多还是sharing-proxy多啊

**Comment by haroldjiang** [comment]
有没有在生产环境用sharing-proxy的

**Comment by starcwang** [comment]
一点资讯 https://www.yidianzixun.com/

**Comment by linkgo8391** [comment]
杭州开课啦教育http://www.kaike.la/

**Comment by wyzssw** [comment]
滴滴小桔车服

**Comment by life300131** [comment]
京东金融-职能研发部-财务研发组

**Comment by tianbin1001** [comment]
京东金融-企业金融研发部-企业融资研发组

**Comment by lfg777** [comment]
拍拍贷-https://www.ppdai.com

**Comment by tristaZero** [comment]
@lfg777 @tianbin1001 @life300131 @wyzssw @linkgo8391 @starcwang 
Welcome here. Your company is now in our [user list](http://shardingsphere.io/community/cn/company/).

**Comment by pinebud** [comment]
火币资讯

**Comment by pinebud** [comment]
火币资讯-https://www.huobiinfo.com

**Comment by fy401** [comment]
瓜子二手车-https://www.guazi.com

**Comment by terrymanu** [comment]
@pinebud @fy401 Welcome our 2 new friends.  Your company is now in our [user list](http://shardingsphere.io/community/cn/company/).

**Comment by clin2y** [comment]
蜂网供应链-https://www.newbeescm.com/ 智慧零售

**Comment by liweifengwf** [comment]
大搜车- https://www.souche.com/zh/

**Comment by tristaZero** [comment]
> 大搜车- https://www.souche.com/zh/
@liweifengwf 
Welcome~

**Comment by tristaZero** [comment]
@clin2y Hi, welcome~
Your company is now in our user list.

**Comment by fg0711** [comment]
海典软件  http://www.hydee.cn

**Comment by zhuchao941** [comment]
点我达 https://www.dianwoda.com/

**Comment by tristaZero** [comment]
@fg0711 @zhuchao941 welcome~

**Comment by paco277853071** [comment]
速珂智能-http://www.supersoco.com/

**Comment by chenshun131** [comment]
武汉金康高科技有限公司-http://www.kingcome.cn/

**Comment by org-hejianhui** [comment]
江苏中辰软件科技有限公司-http://jszcrj.com/

**Comment by zjcnb** [comment]
小红唇科技网络有限公司-https://www.xiaohongchun.com/

**Comment by Mkeeper6** [comment]
斗鱼 https://www.douyu.com/

**Comment by llliusong** [comment]
杭州康帕斯科技有限公司-http://www.compasshz.com/

**Comment by Myshiner** [comment]
sharding-proxy中可以设置控制规则吗？
比如：丢弃查询中没有where条件的语句
3.x的文档中没有这些配置

**Comment by Myshiner** [comment]
点石经纬-https://www.okayzhihui.com/ -智慧教育

**Comment by bukeneng2011** [comment]
京东云-https://www.jdcloud.com/cn/ -云计算

**Comment by tristaZero** [comment]
@bukeneng2011  @Myshiner @llliusong Welcome :-D, your companies is now in [Company List](https://shardingsphere.apache.org/community/cn/company/).

**Comment by stevenlii** [comment]
58

**Comment by 125964590** [comment]
好未来

**Comment by tristaZero** [comment]
@stevenlii @125964590 Welcome, your companies are now in [Company List](https://shardingsphere.apache.org/community/cn/company/).

**Comment by Corezuo** [comment]
智创工场  http://www.izxcs.com/

**Comment by changguofeng1** [comment]
楚楚街 http://www.chuchujie.com/  社交电商

**Comment by pcalpha** [comment]
杭州海康威视数字技术有限公司  http://www.hikvision.com

**Comment by jackzhangyk** [comment]
马蜂窝 [马蜂窝](http://www.mafengwo.com) 旅游服务

**Comment by daizf** [comment]
vivo www.vivo.com 商城订单服务

**Comment by HanWang945** [comment]
百果园   http://www.pagoda.com.cn/    水果零售企业

**Comment by ManderLS** [comment]
东奥教育集团 edu.dongao.com  题库系统

**Comment by ManderLS** [comment]
东奥教育集团 http://edu.dongao.com 题库系统

**Comment by manheiba** [comment]
玖富数科 [https://www.9fgroup.com](url)

**Comment by williambrv** [comment]
杭州光云科技有限公司  http://www.raycloud.com/  企业服务

**Comment by chandler-han** [comment]
奇艺世纪科技有限公司 https://www.iqiyi.com/ 娱乐

**Comment by tristaZero** [comment]
@chandler-han
@williambrv
@manheiba
@ManderLS 
@HanWang945 
@daizf
@jackzhangyk 
@changguofeng1
@ZuoFuhong
@pcalpha

Welcome, your companies are now in [Company List](https://shardingsphere.apache.org/community/cn/company/).

**Comment by zhouliwei555** [comment]
每日优鲜  https://www.missfresh.cn/    电商

**Comment by michaeljinxq** [comment]
汽车之家 https://www.autohome.com.cn 汽车互联网平台

**Comment by keji94** [comment]
微脉 [http://www.myweimai.com/](http://www.myweimai.com/)

**Comment by liuweizhenhaoa** [comment]
杭州金通科技集团股份有限公司   http://www.jtkjbike.com/  互联网出行

**Comment by yazong** [comment]
> 杭州金通科技集团股份有限公司 http://www.jtkjbike.com/ 互联网出行

哦了哦了大佬

**Comment by 747510350** [comment]
重庆啄木鸟网络科技有限公司 http://www.xiujiadian.com/ 家庭维修

**Comment by wangjinzhao** [comment]
高济医疗

**Comment by shenmimoon** [comment]
https://github.com/apache/incubator-shardingsphere/issues/59
u can just take questions **For English only**,but companies in Chinese ? @apache

**Comment by pitthuang** [comment]
均瑶集团 www.juneyao.com

**Comment by wangzhengxi** [comment]
云路供应链http://www.yl-scm.com/

**Comment by finnlee87** [comment]
秒卖房 https://www.maifang.com

**Comment by TonySourcing** [comment]
TonySourcing https://TonySourcing.com

**Comment by hunter7727** [comment]
北京新脉远望科技有限公司 http://www.cyberplus.com.cn/

**Comment by yjmyzz** [comment]
携程旅行网 , https://www.ctrip.com,  在线旅游

**Comment by csgirl562857639** [comment]
魔力耳朵 https://magicears.com.cn/

**Comment by Myshiner** [comment]
OKAY智慧教育 https://www.okayzhihui.com/

**Comment by xiaoya0991** [comment]
马蜂窝 https://www.mafengwo.cn/   
![image](https://user-images.githubusercontent.com/30378811/67620565-e5e08900-f83a-11e9-8be5-a4b85f6fcd02.png)

**Comment by beckhampu** [comment]
Orange Finance  甜橙金融(翼支付) https://www.bestpay.com.cn/

**Comment by partys88** [comment]
三只松鼠 
![图片](https://user-images.githubusercontent.com/13522975/69606552-1431ce00-105e-11ea-8bf2-2652389a1b64.png)

**Comment by wenweibin** [comment]
中国民生银行股份有限公司 http://www.cmbc.com.cn/

**Comment by lirengui** [comment]
> Welcome to register by `company` + `homepage` + `use case(optional)`, your support is important to us.
> We will sync to [official website](https://shardingsphere.apache.org/community/en/poweredby/) periodically.
> 
> 欢迎采用了ShardingSphere的公司在此登记，您的支持是我们最大的动力。
> 请按`公司名` + `首页` + `应用案例（可选）`的格式登记。
> 我们会定期同步至[使用公司列表页面](https://shardingsphere.apache.org/community/cn/poweredby/)。

广州理德物联网科技有限公司  http://www.iotlead.com

**Comment by lyzhb9014** [comment]
途家民宿 https://www.tujia.com/

**Comment by ganjx** [comment]
快捷通支付服务有限公司  https://www.kjtpay.com

**Comment by mayee** [comment]
北京千丁互联科技有限公司 http://caas.com.cn/

**Comment by Keanhua** [comment]
上海社宝信息科技有限公司  https://www.shebaotong.com/

**Comment by tcmtang** [comment]
广州码码高信息科技有限公司 [http://www.mamagao.cn/](url)

**Comment by minghu-zhang** [comment]
天威诚信 https://www.itrus.cn

**Comment by RaigorJiang** [comment]
开通金融 https://www.ktjr.com/

**Comment by jackiesteed** [comment]
亚朵 www.yaduo.com

**Comment by Suancaiyu0707** [comment]
哈啰出行 https://www.helloglobal.com/

**Comment by q1waq1wa** [comment]
信也科技 https://www.ppdai.com/

**Comment by xiyelife** [comment]
马上金融  https://www.msxf.com/
![image](https://user-images.githubusercontent.com/8772975/71565181-0fda5400-2ae7-11ea-912e-0eec9c7d47ad.png)

**Comment by suhuaguo** [comment]
上海 soul app 
https://www.soulapp.cn/

**Comment by zhaozengbin** [comment]
对啊网 https://www.duia.com

**Comment by caoweiyu** [comment]
佰裕行科技（深圳）有限公司 https://innoways.com

**Comment by strongduanmu** [comment]
南京爱福路汽车科技 http://www.f6car.com/

**Comment by limingwei** [comment]
淘金云客服 ( 四川淘金你我信息技术有限公司 ) http://www.itaojin.cn ( http://t.itaojin.cn )

**Comment by freezingWu** [comment]
广州锐森科技 https://www.elelive.net/

**Comment by langtutengbywang** [comment]
智云健康 https://www.zyhealth.com/

**Comment by kevingarnetttwo** [comment]
得物app [https://poizon.com/](url)

**Comment by orangeyts** [comment]
谛达诺科技 http://www.didano.com/

**Comment by guanxiaochen** [comment]
会通教育科技 https://willclass.com

**Comment by sunyinhui** [comment]
聚励云机械 https://www.cloudm.com

**Comment by stamhe** [comment]
连尚文学 http://read.zhulang.com/

**Comment by jiangxiewei** [comment]
公交云 http://www.dtchuxing.com/index.html

**Comment by loquitowen** [comment]
采用公司第41位 广西壮族自治区国土资源信息中心 http://z.gxdlr.gov.cn/
现已更名 广西壮族自治区自然资源信息中心  http://dnr.gxzf.gov.cn 
谢谢开源组的作品

**Comment by terrymanu** [comment]
> 采用公司第41位 广西壮族自治区国土资源信息中心 http://z.gxdlr.gov.cn/
> 现已更名 广西壮族自治区自然资源信息中心 http://dnr.gxzf.gov.cn
> 谢谢开源组的作品

Got it, I will update user list soon

**Comment by zengzhihong** [comment]
泰古信息 http://tigosoft.com

**Comment by brzone** [comment]
广州餐道信息科技有限公司 https://www.can-dao.com/

**Comment by odyssey1816** [comment]
欢聚时代 https://www.yy.com/

**Comment by tianbin1001** [comment]
叮当快药 http://www.ddky.com/

**Comment by flyerik** [comment]
中移动金融科技

**Comment by yazong** [comment]
北京登云美业网络科技有限公司 https://www.idengyun.com/  调研中

**Comment by yazong** [comment]
> 北京登云美业网络科技有限公司 https://www.idengyun.com/ 调研中

liliya@idengyun.com

**Comment by nemofusion** [comment]
杭州涂鸦智能  www.tuya.com

**Comment by huntunshule** [comment]
北京航天智控 [http://www.aicmonitor.com/](http://www.aicmonitor.com/)

**Comment by psh882003** [comment]
天阳宏业科技有限公司+http://www.tansun.com/

**Comment by klboke** [comment]
凯京科技 + https://www.keking.com

**Comment by shooray** [comment]
税鸽飞腾信息科技有限公司 http://www.dzzd.com

**Comment by zowie9966** [comment]
台州市卓唯眼镜有限公司https://zowiesunglasses.com/

**Comment by zowie9966** [comment]
台州市卓唯眼镜有限公司+https://zowiesunglasses.com/

**Comment by novayoung** [comment]
海典软件+http://www.hydee.cn

**Comment by huangzhCHN** [comment]
南京中卫信+http://www.chiscdc.com/

**Comment by xbww** [comment]
北京源赞科技有限公司+https://gitqa.com

**Comment by terrymanu** [comment]
> 北京源赞科技有限公司

@xbww  Hi, your web site have some problems need to be clarify

1. The website is not for security for https, can you change the url?
1. The website is look like use a open source project named as `禅道`, is the project belong to your company?

**Comment by xbww** [comment]
the gitqa.com website will be available after 3 month





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：Liang Zhang<notifications@github.com>
日　期：2020年06月17日 12:29:18
收件人：apache/shardingsphere<shardingsphere@noreply.github.com>
抄　送：Darke<darke@gitqa.com>; Mention<mention@noreply.github.com>
主　题：Re: [apache/shardingsphere] Welcome to leave your company's info(欢迎使用ShardingSphere的公司在此登记) (#234)


北京源赞科技有限公司 
@xbww Hi, your web site have some problems need to be clarify 
The website is not for security for https, can you change the url?
The website is look like use a open source project named as 禅道, is the project belong to your company?

**Comment by kimmking** [comment]
@xbww 

域名gitqa.com的信息以下信息更新时间：2020-06-12 09:17:53立即更新获取API
主办单位名称涿州智软联胜网络科技有限公司
主办单位性质企业
网站备案/许可证号冀ICP备18036290号-1查看截图

**Comment by andyhewenhui** [comment]
KaDa故事  https://kada.hhdd.com/

**Comment by taojintianxia** [comment]
> Welcome to register by `company` + `homepage` + `use case(optional)`, your support is important to us.
> We will sync to [official website](https://shardingsphere.apache.org/community/en/users/) periodically.
> 
> 欢迎采用了ShardingSphere的公司在此登记，您的支持是我们最大的动力。
> 请按`公司名` + `首页` + `应用案例（可选）`的格式登记。
> 我们会定期同步至[使用公司列表页面](https://shardingsphere.apache.org/community/cn/users/)。

the compoy list who used shardingsphere should be changed 
使用公司列表页面的 link 应该改成 (https://shardingsphere.apache.org/community/cn/powered-by/)，当前是个 404

**Comment by terrymanu** [comment]
> > Welcome to register by `company` + `homepage` + `use case(optional)`, your support is important to us.
> > We will sync to [official website](https://shardingsphere.apache.org/community/en/users/) periodically.
> > 欢迎采用了ShardingSphere的公司在此登记，您的支持是我们最大的动力。
> > 请按`公司名` + `首页` + `应用案例（可选）`的格式登记。
> > 我们会定期同步至[使用公司列表页面](https://shardingsphere.apache.org/community/cn/users/)。
> 
> the compoy list who used shardingsphere should be changed
> 使用公司列表页面的 link 应该改成 ([https://shardingsphere.apache.org/community/cn/powered-by/)，当前是个](https://shardingsphere.apache.org/community/cn/powered-by/)%EF%BC%8C%E5%BD%93%E5%89%8D%E6%98%AF%E4%B8%AA) 404

Fixed

**Comment by xbkaishui** [comment]
杭州诺景网络 https://credigo.io/

**Comment by Jasun0925** [comment]
武汉万江龙 http://www.shangquanquan.com/

**Comment by syhasia** [comment]
广联达科技股份有限公司 https://www.glodon.com/

**Comment by 4455159211** [comment]
重庆信达软件工作室  http://xindadev.com/

**Comment by zuowenmou** [comment]
闪送 http://www.ishansong.com/

**Comment by tristaZero** [comment]
@xbkaishui @Jasun0925 
@syhasia @4455159211 @zuowenmou

Hi everyone, Thanks for your attention and feedback! Besides, if you like, welcome to join this community and become one of the important contributor team. :-)

Hope you enjoy yourselves here.

Best,
Trista

**Comment by leechaoqiang** [comment]
韵达科技  http://www.yundaex.com/cn/index.php

**Comment by duanzonglong** [comment]
上海弘人网络科技有限公司 http://www.c-wms.net/

**Comment by tristaZero** [comment]
@leechaoqiang @duanzonglong 
Hi Thanks for your feedback. Glad to see your company in the user list of `ShardingSphere community`.

Cheers,
Trista

**Comment by palosky** [comment]
山东华链医疗科技有限公司 http://www.huxleymedical.tech/

**Comment by terrymanu** [comment]
> 山东华链医疗科技有限公司 http://www.huxleymedical.tech/

@palosky Hello, your URL is 404 Not Found

**Comment by diwayou** [comment]
大商天狗电子商务有限责任公司 https://m.51tiangou.com/

**Comment by ccitt** [comment]
途家民宿+http://www.tujia.com/

**Comment by nicochow** [comment]
Keep https://www.keep.com/

**Comment by yapee123456** [comment]
baidu  https://www.baidu.com/

**Comment by yang-7777** [comment]
> baidu https://www.baidu.com/

Hi Thank you for your reply, please contact me via email or wechat ss_assistant_1, much appreciate.

**Comment by tristaZero** [comment]
@diwayou @ccitt @nicochow @yapee123456 Thanks for everyone's comment. :-)
Welcome!

@yang-7777 Please list them on our user list page.

**Comment by yang-7777** [comment]
丁香园 http://www.dxy.cn/

**Comment by yang-7777** [comment]
神州商龙科技股份有限公司 tcslwxwl.cn.b2b168.com/

**Comment by yang-7777** [comment]
神州商龙科技股份有限公司 http://tcslwxwl.cn.b2b168.com/

**Comment by carl-zhao** [comment]
茄子快传 http://www.ushareit.com/

**Comment by paascloud** [comment]
每日优鲜 https://www.missfresh.cn/

**Comment by yang-7777** [comment]
360数科 https://www.360jinrong.net/

**Comment by terrymanu** [comment]
> baidu https://www.baidu.com/

@yapee123456 Hello, thank you for register, Baidu is a great and big company, could you tell us more details of which applications use Apache ShardingSphere?

**Comment by WildWolfBang** [comment]
360数科 https://www.360jinrong.net/

**Comment by tristaZero** [comment]
Hi @WildWolfBang welcome. :-)

@yang-7777 Please add our new users to the user page, thanks.

**Comment by neverdizzy** [comment]
浙江大东鞋业有限公司 + [http://www.dusto.cn/](url)

**Comment by liangbaolatiao** [comment]
京东物流 + https://www.jdl.cn/

**Comment by tristaZero** [comment]
Hi @neverdizzy @liangbaolatiao 
Welcome your joining!

**Comment by TestManAndCode** [comment]
广东喜百年供应链科技有限公司 + http://www.xbnwl.com/

**Comment by aladinw** [comment]
北京加菲猫科技有限公司 https://www.garfiel-tech.com/  未来信封

**Comment by domineerLong** [comment]
上海云砺信息科技有限公司  https://www.xforceplus.com/

**Comment by c918330** [comment]
杭州每天健康科技有限公司 https://www.mytijian.com

**Comment by copyshop** [comment]
hello， Shardingshere is use in meicloud （美云智数 http://www.meicloud.com/）

**Comment by terrymanu** [comment]
> hello， Shardingshere is use in meicloud （美云智数 [http://www.meicloud.com/）](http://www.meicloud.com/%EF%BC%89)

Hi, your website is broken.

**Comment by ghostxixi** [comment]
baidu 爱番番 https://aifanfan.baidu.com/     Use ShardingSphere for database sharing & table sharing

**Comment by gfsamudra** [comment]
travelingpin https://travelingpin.com

**Comment by tristaZero** [comment]
Hi welcome @ghostxixi  😉

**Comment by tristaZero** [comment]
> travelingpin https://travelingpin.com

Hi @gfsamudra Thanks and welcome. : )
Just out of my curiosity, which product do you use? ShardingJDBC or ShardingProxy?

**Comment by gfsamudra** [comment]
> > travelingpin https://travelingpin.com
> 
> Hi @gfsamudra Thanks and welcome. : )
> Just out of my curiosity, which product do you use? ShardingJDBC or ShardingProxy?

use ShardingJDBC with standard database: MySQL and SQLServer 🥇

**Comment by tristaZero** [comment]
> use ShardingJDBC with standard database: MySQL and SQLServer 🥇
Aha, I guess so. Thanks, 😃

**Comment by yinyanghuafa** [comment]
建信金融科技 https://www.ccbft.com/

**Comment by copyshop** [comment]
> > hello， Shardingshere is use in meicloud （美云智数 [http://www.meicloud.com/）](http://www.meicloud.com/%EF%BC%89)
> 
> Hi, your website is broken.

http://www.meicloud.com     it's not http://www.meicloud.com/%EF%BC%89, I've just tested that there's no problem with this website. Do you input extra characters,

**Comment by terrymanu** [comment]
> > > hello， Shardingshere is use in meicloud （美云智数 [http://www.meicloud.com/）](http://www.meicloud.com/%EF%BC%89)
> > 
> > 
> > Hi, your website is broken.
> 
> http://www.meicloud.com it's not http://www.meicloud.com/%EF%BC%89, I've just tested that there's no problem with this website. Do you input extra characters,

Got it, welcome to use Apache ShardingSphere

**Comment by terrymanu** [comment]
> 建信金融科技 https://www.ccbft.com/

Published into official website, thank you and welcome to use Apache ShardingSphere

**Comment by dafanzhi** [comment]
无远信息技术 https://wuyuan.io 无远开发平台

**Comment by lunarzzz** [comment]
腾讯音乐娱乐科技有限公司 https://y.tencentmusic.com

**Comment by gfsamudra** [comment]
@terrymanu how Published into official website? we to use Apache ShardingSphere

**Comment by ywendy** [comment]
中税网 www.taxchina.com  
数据脱敏

**Comment by tristaZero** [comment]
Hi @lunarzzz @ywendy Thanks for your comments and have my best wishes. :)

**Comment by terrymanu** [comment]
> @terrymanu how Published into official website? we to use Apache ShardingSphere

Just register in this issue, I will publish it on official website

**Comment by dafanzhi** [comment]
无远开发平台 https://wuyuan.io

**Comment by tristaZero** [comment]
@dafanzhi Hi welcome.

**Comment by github-ganyu** [comment]
商越科技 https://www.sunyur.com/

**Comment by tristaZero** [comment]
@github-ganyu Thanks for your attention.

**Comment by junejs** [comment]
微医云（杭州）控股有限公司，https://cloud.guahao.cn/

**Comment by tristaZero** [comment]
@junejs Nice to see you here.

**Comment by MrXionGe** [comment]
北京立思辰云悦科技有限公司，https://www.yunyuecloud.com/，业务系统读写分离

**Comment by wangshihuyue** [comment]
武汉快特信息技术有限公司 www.qvodte.com
零售ERP库存核心业务

**Comment by gfsamudra** [comment]
i already submit https://travelingpin.com but still not published official @terrymanu

**Comment by terrymanu** [comment]
@gfsamudra Great, waiting for the good news. 
Any questions please contact us.

**Comment by terrymanu** [comment]
> 武汉快特信息技术有限公司 www.qvodte.com
> 零售ERP库存核心业务

@wangshihuyue Helllo, the website is broken, do you need to fix it?

**Comment by terrymanu** [comment]
> 楚楚街 http://www.chuchujie.com/ 社交电商

`Hi, the website is broken, I just remove it from the powered  by page, please contact me if the website fixed.` by @terrymanu

**Comment by GeniusQ** [comment]
广东达信智慧云科技有限公司 http://www.gddxit.com/
昆明市自来水客户营销平台

**Comment by tristaZero** [comment]
> 广东达信智慧云科技有限公司 http://www.gddxit.com/
> 昆明市自来水客户营销平台

Welcome. : )

**Comment by sqldance** [comment]
理想汽车 https://www.lixiang.com

**Comment by tristaZero** [comment]
Hi @sqldance
Welcome here.

**Comment by junejs** [comment]
this is a test

**Comment by wl4g** [comment]
商物云  https://sunwuu.com

**Comment by tristaZero** [comment]
@wl4g Then you are the part of this community. :)

**Comment by hzhangse** [comment]
公牛智能产业中心-物联网云平台 https://www.gongniu.cn/

**Comment by tristaZero** [comment]
@hzhangse Please have my welcome.

**Comment by SinPingWu** [comment]
普适导航科技股份有限公司 http://ubinavi.com.cn/

**Comment by strongduanmu** [comment]
@SinPingWu Welcome to join the community.

**Comment by mghio** [comment]
未来医生 https://www.xingren.com

**Comment by tristaZero** [comment]
@mghio Thanks for your feedback. ;-)

**Comment by acmenlt** [comment]
Medbanks（思派网络） + https://www.medbanks.cn/

**Comment by tristaZero** [comment]
@acmenlt Hi welcome come here.

**Comment by haroldyong** [comment]
正元智慧 http://www.hzsun.com  软件开发及服务

**Comment by shadowsmao** [comment]
SourcingArts    https://www.sourcingarts.com/ 电子商务

**Comment by tristaZero** [comment]
@shadowsmao Hey, welcome. ;-)
