### ISSUE TITLE
When is node of '/nodes/storage_nodes' created

### ISSUE THREAD

**Issue by pengbiaobeyond** [apache/shardingsphere#23411]
I only see the query and application of this node，but I can not find the creating of  '/nodes/storage_nodes'

**Comment by zhaojinchao95** [comment]
@pengbiaobeyond Hi, `/nodes/storage_nodes ` created when you disable or enable data source. Refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/circuit-breaker/alter-readwrite-splitting-rule-enable-disable/. And If you use db-discovery and readwrite-splitting rule, the  `/nodes/storage_nodes ` is auto created.
