### ISSUE TITLE
Add test case for PluginContext

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#23419]

**Comment by Hzg030** [comment]
Hello,  i am a complete beginner, I have set up my development environment according to the contribution guide and learned how to write unit tests; I think I can try this task, please assign to me, thanks.

**Comment by zhaojinchao95** [comment]
> Hello, i am a complete beginner, I have set up my development environment according to the contribution guide and learned how to write unit tests; I think I can try this task, please assign to me, thanks.

Welcome
