### ISSUE TITLE
shardingsphere removed “MASTER_VISITED” in 5.x version？How can I use this feature instead？

### ISSUE THREAD

**Issue by Enternal-ZERO** [apache/shardingsphere#23421]
This is 4.1.0 code
 public String route(final SQLStatement sqlStatement) {
        if (isMasterRoute(sqlStatement)) {
            MasterVisitedManager.setMasterVisited();
            return masterSlaveRule.getMasterDataSourceName();
        }
...

and in 5.3.0
 public String route(final SQLStatementContext<?> sqlStatementContext) {
        if (isPrimaryRoute(sqlStatementContext)) {
            return rule.getWriteDataSource();
        }
....

why remove this feature in 5.x？
it means user should maintain a threadlocal status？and release by usercode？

**Comment by Pace2Car** [comment]
Hi @Enternal-ZERO, if you use for `readwrite-splitting`, please refer to: https://github.com/apache/shardingsphere/pull/13375

**Comment by Enternal-ZERO** [comment]
> Hi @Enternal-ZERO, if you use for `readwrite-splitting`, please refer to: #13375

Okay，I have seen the commit，but what's the reason， this feature was mentioned in 4.x as a core feature
"If there is write operation in the same thread and database connection, all the following read operations are from the master database to ensure data consistency."

and it works in the past version well

Are there any example to explain “Keep data consistent in same thread is not make sense enough”

**Comment by RaigorJiang** [comment]
Hi @Enternal-ZERO 
I remember a scene related to #13375,  pseudocode:
```java
public String fooQuery {
# insert a request log
statement.executeUpdate("xxx");

# do some business query
statement.executeQuery("xxx");
...
return result;
}
```
As above, if I have such a business scenario (record request log), then all request threads are `MASTER_VISITED`, and no request will be routed to the read data source. This violates the original intention of readwrite splitting.

**Comment by Enternal-ZERO** [comment]
> Hi @Enternal-ZERO I remember a scene related to #13375, pseudocode:
> 
> ```java
> public String fooQuery {
> # insert a request log
> statement.executeUpdate("xxx");
> 
> # do some business query
> statement.executeQuery("xxx");
> ...
> return result;
> }
> ```
> 
> As above, if I have such a business scenario (record request log), then all request threads are `MASTER_VISITED`, and no request will be routed to the read data source. This violates the original intention of readwrite splitting.


this sounds some troubles really .

but remove this feature will cause data consistency , if user update version in product env. it is terrible..and it not mentioned in doc(5.x) 

at least, i think it must be Highlight  in 5.x docs.

in another way, can this feature be controlled by user self (use config)
or give an entrance to manage a thread local status  by user code?
because in sharding framework，the code using “ try catch + autocloseable ”，thread local object will remove automatically
i think this is nice. 
but if use hintmanage to finish this feature ,user code should find a way to setMasterOnly, and find a way to release thread local object。
in most time， these code “ set and release ”  is being separate.  and diff project ，such as WEB、JOB、 RPC , release code maybe different.

**Comment by RaigorJiang** [comment]
`Transactional` can be declared in methods with write operations,
then the read and write statement in the transaction will be routed to the write data source.

**Comment by Enternal-ZERO** [comment]
> `Transactional` can be declared in methods with write operations, then the read and write statement in the transaction will be routed to the write data source.
@RaigorJiang 
there are so many methods, and so many projects... use @Transactional is a terrible work.

**Comment by RaigorJiang** [comment]
> > there are so many methods, and so many projects... use @transactional is a terrible work.

How helpful is `MASTER_VISITED` in your use case? Is there any negative impact?

**Comment by Enternal-ZERO** [comment]
> > > there are so many methods, and so many projects... use @transactional is a terrible work.
> 
> How helpful is `MASTER_VISITED` in your use case? Is there any negative impact?
In the past versions, sharding framework  using “ try catch +  autocloseable ”，thread local object will remove automatically.
and in our project , there are huge code  read the new data after write.
and in 5.x  if I need keep this feature, I need use hintmanage to maintain the status , and need clear myself.

**Comment by Pace2Car** [comment]
I understand your scenario now, but this does not seem to be a problem that most users will encounter. If you have a good suggestion or implementation about this, you can submit a PR, thank you!

**Comment by RaigorJiang** [comment]
Hi @Enternal-ZERO 
This scenario is indeed possible, you can start a community discussion (via mailing list or discussion issue), or submit a PR after design, this is a good opportunity to participate in the community.  :)
