### ISSUE TITLE
Remove unused annotation ShardingSphereTransactionType

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#23457]
Please remove unused annotation ShardingSphereTransactionType and the empty package.

**Comment by Pace2Car** [comment]
For #22469 .

**Comment by asundiary** [comment]
I will work on it.

**Comment by newboy2004** [comment]
i will try it.

**Comment by CoderMayhem** [comment]
I'd like to take this up if work is stalled on this.
