### ISSUE TITLE
How to set data source

### ISSUE THREAD

**Issue by szzxl** [apache/shardingsphere#23464]
shardingsphere-jdbc-core-spring-boot-starter:5.1.1
druid-spring-boot-starter:1.2.14
mysql-connector-java: 8.0.31
spring-boot-dependencies：2.7.3

shardingsphere:
    mode:
      type: Cluster
      repository:
        type: ZooKeeper
        props:
          namespace: ns
          server-lists: localhost:2181
          retryIntervalMilliseconds: 500
          maxRetries: 3
          timeToLiveSeconds: 60
          operationTimeoutMilliseconds: 500
    rules:
      readwrite-splitting:
        data-sources:
           ds:
             type: Static
             load-balancer-name: my
             props:
                 write-data-source-name: master
                 read-data-source-names: salve1,salve2
        load-balancers:
          my:
            type: ROUND_ROBIN
    datasource:
      names: master,salve1,salve2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc: 
        username: 
        password: 
      salve1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url:
        username: 
        password: 
      salve2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: 
        username: 
        password: 

According to the official website, report errors
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1204) [druid-1.2.14.jar:na]

**Comment by Pace2Car** [comment]
Please refer to: https://shardingsphere.apache.org/document/5.2.1/en/faq/ question 1
And also, it is recommended to upgrade to version 5.3.x and use the JDBC Driver to access ShardingSphere-JDBC.
For more information, see https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/
