### ISSUE TITLE
In the case of inconsistent table DDL in the sharding, execute the select * error column index out of range

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#23475]
## Bug Report

select * from table_a

logic_table: table_a
actual_table: table_a_0~table_9

table_a_0 - table_5 has 10 column
table_a_6 - table_9 has 9 column

### Which version of ShardingSphere did you use?
5.3.1-release

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
execute success

### Actual behavior
error，Column index out of range

### Reason analyze (If you can)
ss metadata: has 10 column
table_a_6~table_9 has 9 column

ss metadata info Inconsistent with the table structure in data source

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/20919316/211516219-9dffa88a-c385-4e79-a6fc-b45179e55044.png">

**Comment by zhaojinchao95** [comment]
Execute [REFRESH DATABASE METADATA FROM GOVERNANCE CENTER](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-database-metadata/) afrer execute DDL SQL, might fix this.

**Comment by git-chenhao** [comment]
@zhaojinchao95 When there is a lot of data in the physical database, table splitting may be half successful and half failed。Do you have any good suggestions? We can change the code

**Comment by git-chenhao** [comment]
@zhaojinchao95 Can you help me？😭
