### ISSUE TITLE
why  not support set Hikari poolName ?

### ISSUE THREAD

**Issue by fuwenbo2013** [apache/shardingsphere#23490]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by fuwenbo2013** [comment]
![image](https://user-images.githubusercontent.com/44946487/211723035-df63beb1-5431-4ccd-99a4-e1b988469170.png)

**Comment by fuwenbo2013** [comment]
the  poolName was added  in latest version

**Comment by zhaojinchao95** [comment]
Hi, the poolName are suddenly, I think we needn't care it. May I ask what you need to do with it?

**Comment by RaigorJiang** [comment]
ShardingSphere has some scenarios for refreshing metadata, and the connection pool will also be rebuilt.
By default, different poolNames will be generated at this time, but if the user specifies a poolName, two pools before and after may have the same name, which may confuse monitoring indicators.

**Comment by fuwenbo2013** [comment]
> ShardingSphere has some scenarios for refreshing metadata, and the connection pool will also be rebuilt. By default, different poolNames will be generated at this time, but if the user specifies a poolName, two pools before and after may have the same name, which may confuse monitoring indicators.

If use  the  custome poolName as the prefix, can it be solved?

**Comment by RaigorJiang** [comment]
> If use the custome poolName as the prefix, can it be solved?

So how to do with that, do you hava any idea?

**Comment by jdxia** [comment]
> ShardingSphere has some scenarios for refreshing metadata, and the connection pool will also be rebuilt. By default, different poolNames will be generated at this time, but if the user specifies a poolName, two pools before and after may have the same name, which may confuse monitoring indicators.

If the user specifies duplicates, it is the user's problem
Not currently supported. Let's take a look at the monitoring. How can we match the name of the connection pool with the specific data source?
