### ISSUE TITLE
the slave node is repeatedly updated

### ISSUE THREAD

**Issue by pengbiaobeyond** [apache/shardingsphere#23498]
I see that in the source code, the slave node is repeatedly updated again and again in the scheduled task.

**Comment by pengbiaobeyond** [comment]
<img width="825" alt="1673421153(1)" src="https://user-images.githubusercontent.com/46187883/211741025-8fde71a2-e8c3-476f-95bc-b762355c5c2e.png">

**Comment by RaigorJiang** [comment]
Hi @zhaojinchao95, Maybe you can help take a look at this question~

**Comment by terrymanu** [comment]
What is your version?
