### ISSUE TITLE
When postgresql node use db-discovery, choose which discoveryType?

### ISSUE THREAD

**Issue by LanceJerry** [apache/shardingsphere#23501]
## Question

**postgresql db use shardingsphere-porxy**, we plan to choose db-discovery and RW splitting to complete dynamic RW splitting.

there are three discovery types:

- MySQL.MGR,
- MySQL.NORMAL_REPLICATION
- openGauss.NORMAL_REPLICATION

**which discoveryType could used by postgresql?** we tried openGauss.NORMAL_REPLICATION and get a error result,, it seems not be suitable to postgresql. there are errors:

- o.a.s.d.a.DatabaseDiscoveryEngine - Load data source replica status error: 
org.postgresql.util.PSQLException: ERROR: function pg_stat_get_stream_replications() does not exist
建议：No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by Pace2Car** [comment]
Sorry, PostgreSQL db-discovery is not currently supported, if you have a good implementation, welcome to submit a PR.

**Comment by LanceJerry** [comment]
> Sorry, PostgreSQL db-discovery is not currently supported, if you have a good implementation, welcome to submit a PR.

Thanks for your reply, we will try to resolve it.

**Comment by RaigorJiang** [comment]
Hi @LanceJerry , Do you want to submit a PR?

**Comment by terrymanu** [comment]
The database discovery feature has been remove form ShardingSphere, please ref #24486
