### ISSUE TITLE
Slow sql occurred several times when using shardingsphere-proxy5.1.2

### ISSUE THREAD

**Issue by TianShaoJie-alt** [apache/shardingsphere#23524]
### Which version of ShardingSphere did you use? 
shardingsphere5.1.2 
### Which project did you use?       ShardingSphere-JDBC or ShardingSphere-Proxy? 
ShardingSphere-Proxy 
### Expected behavior 
normal use
### Actual behavior 
Slow sql occurs about 10 times over several thousand transactions, around 1000 milliseconds
### Reason analyze (If you can) 
It could be configuration-related
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc. 
Execute SQL
### Example codes for reproduce this issue (such as a github link).

**Comment by TeslaCN** [comment]
Could you check the GC stat? You may use `jstat -gc $PID 1000`.

**Comment by TianShaoJie-alt** [comment]
Online project, shall not arbitrarily improve the right... Can you improve on the server.xml configuration

**Comment by TeslaCN** [comment]
There are many possibilities of performance issue. You may need to provide more details about your issue. Such as how could you make sure the slow SQL was not caused by improper JVM options or other configurations.

**Comment by TianShaoJie-alt** [comment]
![825b086ddb4f6b605aaa14e596b317d](https://user-images.githubusercontent.com/56820226/212005389-1ff958f7-dbd8-450d-a659-5f7e9ba3488e.png)

**Comment by TianShaoJie-alt** [comment]
Check the above gc situation

**Comment by TeslaCN** [comment]
You may need to check the GC stat in busy time. And how much is your system TPS? How do you find out the slow SQL from thousands of transactions?
