### ISSUE TITLE
Support loading `01-initdb` according to database version in e2e mode.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#23528]
## Feature Request

I want add `GRANT XA_RECOVER_ADMIN ON *.* TO 'username'@'%';`;
but this can only used in mysql8.0+

So I think we need spilt `01-initdb` by version.

**Comment by AbnerHuang2** [comment]
@strongduanmu  this issue fixed by pr(#25549), can be closed.

**Comment by strongduanmu** [comment]
@AbnerHuang2 Thank you for your feedback, I will close this issue.
