### ISSUE TITLE
Remove useless Enum `GrantLevelTypeEnum`

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#23534]
Hi guys,
             I found that there is a useless Enum `GrantLevelTypeEnum` that needs to be removed, anyone wanna try it? 
path: /shardingsphere/sql-parser/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/common/segment/generic/GrantLevelTypeEnum

![image](https://user-images.githubusercontent.com/57847965/212127003-db236d7b-cdad-43a0-a198-9ecdd62017e3.png)

**Comment by strongduanmu** [comment]
Hi @xuup, can you comment on this issue? I will assign it to you.
