### ISSUE TITLE
shardingSphere5.2.1 + Oracle  join query with different result ? 

### ISSUE THREAD

**Issue by woshiluoshao** [apache/shardingsphere#23538]
## Question

my oracle data has gbp、zhsq、cms_app base;

select count(1)
		from ${dbuser.gbp}.t_Basic_Risk t1
		 inner join T_NOTICE_TOOLS t2
		 on t1.BASIC_ID = t2.NOTICE_ID
the SQL can execute success,

but 
select count(1)
       from T_NOTICE_TOOLS T
			inner join ${dbuser.cms_app}.app_zone_user_area_bind B
       on T.notice_uuid = B.ORG_CODE

SQL execute fail 
error message:
### Cause: java.sql.SQLSyntaxErrorException: ORA-00905: 缺失关键字

i donot konw why，

please help me thanks 

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by Pace2Car** [comment]
Duplicated with #23511.
