### ISSUE TITLE
addShutdownHook in ShardingExecutorService  Problem In 4.1.1

### ISSUE THREAD

**Issue by Cenck** [apache/shardingsphere#23545]
![image](https://user-images.githubusercontent.com/21187499/212290468-c5c61510-6721-46cd-8ab1-5081a199c3eb.png)

Please merge it into Version 4.1.1，Our team encounter  the same problem with Issue 10641.

thank you

**Comment by Pace2Car** [comment]
Are you willing to consider upgrading the version of ShardingSphere, this issue seems to have been resolved.

**Comment by RaigorJiang** [comment]
All fixes will only be in the new version, please consider upgrading the ShardingSphere version.
