### ISSUE TITLE
Snyk vulnerability scanning

### ISSUE THREAD

**Issue by vikiuvb** [apache/shardingsphere#23558]
ShardingSphere has a lot of dependencies, but the snyk scan just scans only the top level dependencies. It is not scanning all POM files in the multi-module project. 

![image](https://user-images.githubusercontent.com/13797616/212490395-3463fa87-d513-4835-9e5b-f34dd9671e9c.png)

**Comment by RaigorJiang** [comment]
Hi @vikiuvb 
Do you have some ideas about how to solve this problem?

**Comment by linghengqian** [comment]
- To be honest, I don't know why it points to https://snyk.io/test/github/apache/shardingsphere?targetFile=pom.xml . I can get all the CVE information by importing Apache ShardingSphere normally.
- ![image](https://user-images.githubusercontent.com/20187731/214611340-a5529064-4ca9-4051-8924-c2dcf24805ef.png)
- ![image](https://user-images.githubusercontent.com/20187731/214610471-32eb8fe7-81bd-4010-b78c-af8beefccf2d.png)

- @RaigorJiang I noticed that generating reports requires a paid Snyk account. I wonder if this function will involve applying for permission from ASF?
- ![image](https://user-images.githubusercontent.com/20187731/214608930-ab70895d-d4cb-4608-88f7-44317dbf95e5.png)

**Comment by vikiuvb** [comment]
@strongduanmu @RaigorJiang @linghengqian I don't think the Snyk badge will work for multi-module projects. We need to use Github integration to monitor the project for vulnerabilities. When Synk detects a vulnerability, it can raise a PR.

**Reference:** https://docs.snyk.io/integrations/git-repository-scm-integrations/github-integration#github-integration-features

The last Snyk scan by @linghengqian indicates some high-severity issues. Without proper integration, we will be running blind.

**Comment by linghengqian** [comment]
- @vikiuvb Since Synk has been replaced by SonarCloud in https://github.com/apache/shardingsphere/pull/25524, I think this issue has no meaning to continue to open.

**Comment by vikiuvb** [comment]
@linghengqian Yes. It can be closed.

**Comment by vikiuvb** [comment]
@linghengqian Yes. It can be closed.
