### ISSUE TITLE
Does Shardingsphere-proxy support password encryption？

### ISSUE THREAD

**Issue by LanceJerry** [apache/shardingsphere#23573]
## Question

**storage units**
If Shardingsphere-proxy support password encryption when create a distsql rule like a storge unit?
**Given Example**：
REGISTER STORAGE UNIT ds_0 (
    HOST="127.0.0.1",
    PORT=3306,
    DB="db_0",
    USER="root",
    PASSWORD="root"
);
**Expected rule**：
REGISTER STORAGE UNIT ds_0 (
    HOST="127.0.0.1",
    PORT=3306,
    DB="db_0",
    USER="root",
    PASSWORD="EAD234ASDFASD" # encryption algorithm，transfer “root” to “EAD234ASDFASD”。
);
If Shardingsphere-proxy  do not support password encryption， it will be insecurity to use.

**Comment by RaigorJiang** [comment]
If the proxy has such an encryption algorithm, how does the user know how to enter the password when using DistSQL?

**Comment by LanceJerry** [comment]
> If the proxy has such an encryption algorithm, how does the user know how to enter the password when using DistSQL?

If proxy could support input origin password, and encrypt it, and when show to users, it could trans to origin password, it is more suitable to show and save paasword? In a word, saving origin password as metedata in zookeeper or server.yaml(such as 

authority:
  users:
    - user: root@%
      password: root) may be not safe.

**Comment by LanceJerry** [comment]
Of course, it's just a my question and want to get the answer.

**Comment by RaigorJiang** [comment]
This requirement is reasonable, but currently there seems to be no good solution
