### ISSUE TITLE
driverClassName配置似乎并未生效

### ISSUE THREAD

**Issue by afei199002** [apache/shardingsphere#23596]
## Question

配置
dataSources:
  db_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.xxx.Driver

driverClassName配置似乎并未生效，debug看代码，
public final class DataSourceReflection {
    
    static {
        GENERAL_CLASS_TYPES = new HashSet<>(
                Arrays.asList(boolean.class, Boolean.class, int.class, Integer.class, long.class, Long.class, String.class, Collection.class, List.class, Properties.class));
        SKIPPED_PROPERTY_KEYS = new HashSet<>(Arrays.asList("loginTimeout", "driverClassName"));
    }
不知道是不是这个类这个设置的原因

**Comment by RaigorJiang** [comment]
**For English only**, other languages will not accept.

**Comment by wcarcher** [comment]
这个问题这么重要，为啥不回复解决

**Comment by strongduanmu** [comment]
Hi @wcarcher, can you submit a new issue according to bug template?
