### ISSUE TITLE
sharding-jdbc    How to synchronize the structure of single table library and sub-table library ？

### ISSUE THREAD

**Issue by leafcold** [apache/shardingsphere#23609]
I am a novice,

In the development environment, our table looks like this:
CREATE TABLE `user`  (
  `only_id` bigint(23) NOT NULL,
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

In the production environment, our table looks like this
CREATE TABLE `user_00`  (
  `only_id` bigint(23) NOT NULL,
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `user_01`  (
  `only_id` bigint(23) NOT NULL,
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

Now we have modified the table of the development environment like this:
CREATE TABLE `user`  (
  `only_id` bigint(23) NOT NULL,
  `uid` int(11) NOT NULL,
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

How to synchronize the table structure of the production environment and the development environment

**Comment by RaigorJiang** [comment]
Hello @leafcold , 
what is the relationship between the information you describe and ShardingSphere?

**Comment by RaigorJiang** [comment]
If you use ShardingSphere-Proxy, you can execute DDL through Proxy. (assuming no impact on data)
If you are using ShardingSphere-JDBC, you need to handle it yourself, or deploy a Proxy for maintenance operations.
