### ISSUE TITLE
sharding-proxy 5.3.1:The logical configuration that does not go through sub-database and sub-table does not work

### ISSUE THREAD

**Issue by duansy123** [apache/shardingsphere#23610]
## Bug Report
The configuration is as follows
![image](https://user-images.githubusercontent.com/38459049/212844888-490c628d-c841-4cab-8d46-941246caed59.png)
The configuration of version 5.0.0 is easy to use. Now after upgrading 5.3.1, an error will be reported
![image](https://user-images.githubusercontent.com/38459049/212845195-1fcc1341-f42b-454e-a8bc-c07a83344c09.png)
Excuse me, is there a grammar upgrade？
Please take a look Thank you

**Comment by RaigorJiang** [comment]
Hi @duansy123  
The format of the sharding configuration remains unchanged:
1. If the cluster mode is used, please check whether the configuration in governance is correct
2. If it is in standalone mode, please provide a complete configuration to reproduce the problem

**Comment by duansy123** [comment]
yes,it is in standalone mode,The following is the complete configuration


`databaseName: cxm_tenant_db

dataSources:
  cxm_public:
    url: jdbc:mysql://xxxxxxxxx:3306/cxm_public?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds0:
    url: jdbc:mysql://xxxxxxxxx:3306/cxm_agroup_0000?useUnicode=true&allowMultiQueries=true&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds1:
    url: jdbc:mysql://xxxxxxxx:3306/cxm_agroup_0001?useUnicode=true&allowMultiQueries=true&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds2:
    url: jdbc:mysql://xxxxxxxx3306/cxm_agroup_0002?useUnicode=true&allowMultiQueries=true&character_set_server=utf8mb4&connectionCollation=utf8mb4_bin&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1            
  # ds_1:
  #   url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
  #   username: root
  #   password:
  #   connectionTimeoutMilliseconds: 30000
  #   idleTimeoutMilliseconds: 60000
  #   maxLifetimeMilliseconds: 1800000
  #   maxPoolSize: 50
  #   minPoolSize: 1

rules:
- !SHARDING
  tables:
    research_info:
      actualDataNodes: ds${0..2}.research_info
      keyGenerateStrategy:
        column: research_id
        keyGeneratorName: snowflake
      databaseStrategy:
        standard:
          shardingColumn: aid
          shardingAlgorithmName: database_inline
    company_info:
      actualDataNodes: cxm_public.company_info
      keyGenerateStrategy:
        column: company_id
        keyGeneratorName: snowflake
      databaseStrategy:
        none:


  bindingTables:
    none:
  broadcastTables:
    none:
  #  - t_order,t_order_item

  defaultDatabaseStrategy:
    standard:
      shardingColumn: aid
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
  # defaultAuditStrategy:
  #  auditorNames:
  #    - sharding_key_required_auditor
  #  allowHintDisable: true

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds${aid % 3}
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
          worker-id: ${worker-id}
          max-vibration-offset: 16
#  auditors:
#    sharding_key_required_auditor:
#      type: DML_SHARDING_CONDITIONS

`
After I adjusted the default sharding strategy to none, it is now normal

![image](https://user-images.githubusercontent.com/38459049/212880541-86334719-e606-4568-b544-0f8795caef19.png)
So when the default sharding rule and the specified table do not participate in the sharding configuration exist at the same time, it does not work in version 5.3.1

**Comment by terrymanu** [comment]
Hello, it's inevitable that there will be compatibility issues with the various versions of ShardingSphere. Due to the vast number of combinations, it's impossible to address each one individually. To better face the future, the community would like to focus on resolving issues with the current version. For issues related to upgrades, please read the documentation for the respective version. If you encounter a bug in the new version (not a configuration issue), please submit a separate issue.
