### ISSUE TITLE
Consider splitting test cases in E2E into multiple different files

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#23645]
### Is your feature request related to a problem?

No

### Describe the feature you would like.

Currently, the cases in the E2E test are written in different XML files according to the statement type, for example, the `dql-integration-test-cases.xml` file contains all select-related cases. With the increase in the number of E2E test cases, it is now difficult to identify which select statements have added cases and which have not. Therefore, we need to split e2e case files, such as splitting according to different types of select statements, `simple select`, `select union`, `select subquery`, etc., which will make the understanding of test cases easier much easier.

https://github.com/apache/shardingsphere/blob/master/test/e2e/suite/src/test/resources/cases/dql/dql-integration-test-cases.xml

Besides, as a remind, `https://github.com/apache/shardingsphere/blob/master/test/it/parser/src/main/resources/case/dml/select-aggregate.xml` provides a nice split example.

Following are tasks:

- [x] splitting `dal-integration-test-cases.xml` file
- [x] splitting `dcl-integration-test-cases.xml` file
- [x] splitting `ddl-integration-test-cases.xml` file
- [x] splitting `dml-integration-test-cases.xml` file
- [x] splitting `dql-integration-test-cases.xml` file
- [x] splitting `ral-integration-test-cases.xml` file
- [x] splitting `rdl-integration-test-cases.xml` file
- [x] splitting `rql-integration-test-cases.xml` file
- [x] splitting `tcl-integration-test-cases.xml` file

**Comment by gxxiong** [comment]
I'll fix it

**Comment by strongduanmu** [comment]
@gxxiong Welcome, I will assign this issue to you.

**Comment by strongduanmu** [comment]
All tasks have been completed.
