### ISSUE TITLE
chinese databases DM dameng

### ISSUE THREAD

**Issue by Radom7** [apache/shardingsphere#23640]
chinese databases DM dameng is supported by shardingsphere?

**Comment by strongduanmu** [comment]
Hi @Radom7, ShardingSphere currently does not adapt to the DM database. If you need it, you can expand it based on the pluggable architecture.

**Comment by q82184828** [comment]
is there some configuration for add schema to rewirite sql? For example： select * from t1.test

**Comment by linghengqian** [comment]
- IMHO, after checking https://en.dameng.com/view/16.html , DM8 looks more closed than Oracle Database Express Edition (`gvenzl/oracle-free` and `gvenzl/oracle-xe` in Docker Hub). DM8 does not provide a developer-usable Docker Image to Docker Hub. This often means a closed source implementation is required.

**Comment by terrymanu** [comment]
Sorry, this feature is not considered within the currently supported scope.
