### ISSUE TITLE
Use MergedResult to implement RQL functions, remove DistSQLResultSet

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23772]
Now `DistSQLResultSet` is used to implement RQL functionality, and its implementations contain business logic, which is not good, `ResultSet` should just be an object to collect results.

Refer to #23735, #23737 and #23766, we are using `MergedResult` for RQL and removing `DistSQLResultSet` to make the logic clearer.

There are many classes to be refactored, if you want, please participate together.

### Tasks
- [x] CountShardingRuleResultSet
- [x] UnusedShardingAlgorithmsResultSet
- [x] ShardingTableRulesUsedAlgorithmResultSet
- [x] CountMaskRuleResultSet
- [x] ShardingTableRulesUsedKeyGeneratorResultSet
- [x] RulesUsedStorageUnitResultSet
- [x] ShardingTableReferenceRuleResultSet
- [x] DefaultShardingStrategyResultSet
- [x] CountSingleTableResultSet
- [x] CountShadowRuleResultSet
- [x] CountReadwriteSplittingRuleResultSet
- [x] ShadowRuleResultSet
- [x] LogicalTableResultSet
- [x] DatabaseDiscoveryRuleResultSet
- [x] ShadowTableRuleResultSet
- [x] CountDatabaseDiscoveryRuleResultSet
- [x] ShardingTableRulesUsedAuditorResultSet
- [x] DefaultShadowAlgorithmResultSet
- [x] MaskRuleResultSet
- [x] UnusedShardingAuditorsResultSet
- [x] BroadcastTableRuleResultSet
- [x] CountEncryptRuleResultSet
- [x] ShardingAuditorsResultSet
- [x] ShardingKeyGeneratorResultSet
- [x] ShardingTableNodesResultSet
- [x] UnusedShardingKeyGeneratorResultSet
- [x] ShadowAlgorithmResultSet
- [x] ShardingTableRuleResultSet
- [x] DatabaseDiscoveryTypeResultSet
- [x] DatabaseDiscoveryHeartbeatResultSet
- [x] EncryptRuleResultSet
- [x] ShardingAlgorithmResultSet
- [x] ReadwriteSplittingRuleResultSet

**Comment by Qianyi951015** [comment]
please assign to me thx

**Comment by RaigorJiang** [comment]
@Qianyi951015 
Great work, thanks!
