### ISSUE TITLE
How to restart sharding proxy gracefully?

### ISSUE THREAD

**Issue by hza2022x** [apache/shardingsphere#23853]
How to restart sharding proxy gracefully? many thanks.

when restart happens, we want to tell the client: we are restarting, new request don't come in any more.

At the same time, we want the on-fly requests can be handled before sharding-proxy is shutdown.

background:

Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Any one could give some suggestions? many thanks.

**Comment by hza2022x** [comment]
when restart happens, we want to tell the client: we are restarting, new request don't come in. 

At the same time, we want the on-fly requests can be handled before sharding-proxy is shutdown.

Any one could give some suggestions? many thanks.

**Comment by hza2022x** [comment]
background:

Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

**Comment by TeslaCN** [comment]
There is no graceful shutdown for now. This could be an enhancement.

**Comment by hza2022x** [comment]
looking forward......

**Comment by laijianquan1234** [comment]
why ? can fix ?

**Comment by laijianquan1234** [comment]
> why ?? can fix it quickly

**Comment by TeslaCN** [comment]
> > why ?? can fix it quickly

Before doing this enhancement, we may need to discuss how.

**Comment by susongyan** [comment]
mark

**Comment by terrymanu** [comment]
The version is out of service, please try new version.
