### ISSUE TITLE
how to distinguish  request source is from mysql client or program  in sharding proxy? thanks

### ISSUE THREAD

**Issue by hza2022x** [apache/shardingsphere#23858]
background:

Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

For example:
select * from sale_order;

if the table sale_order has millions of records, it may use great memory. 

if the request is from mysql client, and the sql has no 'limit' in where condition, we want to check it. 

Then how to distinguish  request source is from mysql client or program in sharding proxy? thanks

**Comment by hza2022x** [comment]
background:

Which version of ShardingSphere did you use?
5.0.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

**Comment by RaigorJiang** [comment]
Both the MySQL client and the JDBC application are essentially connected to the Proxy through the database protocol, and there is no mark to distinguish them.
Proxy supports parsing of SQL comments, would you like to do some work on this?

**Comment by TeslaCN** [comment]
You may try implementing your own SQLAuditor to forbid executing SQL without limit.

https://github.com/apache/shardingsphere/blob/master/infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/audit/SQLAuditor.java

**Comment by hza2022x** [comment]
get it.  many thanks

**Comment by RaigorJiang** [comment]
@hza2022x  You are welcome.
