### ISSUE TITLE
parameters in the function are not recognized

### ISSUE THREAD

**Issue by WANMAX** [apache/shardingsphere#23875]
### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
"select ar.content -> '$.hi' "hi" from activity_record ar where json_contains(ar.content, ?, '$.hi') limit ?, ?"
There should be three parameters, but the parameters in the function are not recognized
<img width="542" alt="image" src="https://user-images.githubusercontent.com/9609623/215735751-7b662828-0ba5-416d-8ab3-83acff1f3f62.png">

### Actual behavior
The limitSegment gets the wrong parameter because of wrong index.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/9609623/215736018-3cfd1d48-1347-4d48-a3af-07f050834864.png">

**Comment by WANMAX** [comment]
Index of offset parameter should be 1 and index of rowCount parameter should be 2.

**Comment by strongduanmu** [comment]
Hi @WANMAX, thank you for your feedback, can you show your configuration?

**Comment by WANMAX** [comment]
props:
  sql-show: true
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: 
    username: 
    password: 
  slave1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: 
    username: 
    password: 
rules:
  - !READWRITE_SPLITTING
    dataSources:
      ms:
        staticStrategy:
          writeDataSourceName: master
          readDataSourceNames:
            - slave1
        loadBalancerName: roundRobin
    loadBalancers:
      roundRobin:
        type: ROUND_ROBIN

**Comment by strongduanmu** [comment]
Thank you, We will investigate this problem.

**Comment by FlyingZC** [comment]
I want to investigate it. @strongduanmu

**Comment by strongduanmu** [comment]
@FlyingZC Assigned.

**Comment by WANMAX** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/9609623/215929614-d5b62145-56e9-4a14-8cca-55353e692a1f.png">
In fact, the parameter context has been recognized here, which is not handled

**Comment by FlyingZC** [comment]
Just visit the parameters in the JsonFunction to make the index correct, I will fix it.

**Comment by WANMAX** [comment]
In version 5.3.2?
