### ISSUE TITLE
postgresql protocol cannot proxy multiple databases

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#23899]
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
postgresql can proxy multiple databases
### Actual behavior
postgresql Cannot proxy multiple databases

**Comment by TeslaCN** [comment]
I cannot get your point. Could you clarify your question? Did you mean multiple logic databases?

**Comment by McClone** [comment]
After the first addition is successful, add other databases for the second time. The tables in the database are the same as those in the previous one。

**Comment by McClone** [comment]
> I cannot get your point. Could you clarify your question? Did you mean multiple logic databases?

After the first addition is successful, add other databases for the second time. The tables in the database are the same as those in the previous one

**Comment by TeslaCN** [comment]
Could you help us reproduce this?

**Comment by McClone** [comment]
create database test1; 
REGISTER STORAGE UNIT test1(
    HOST="127.0.0.1",
    PORT=3306,
    DB="test1",
    USER="root",
    PASSWORD="root"
);

create database test2; 
REGISTER STORAGE UNIT test2(
    HOST="127.0.0.1",
    PORT=3306,
    DB="test2",
    USER="root",
    PASSWORD="root"
);


The result is that the two databases are same, which is wrong.

**Comment by McClone** [comment]
> create database test1; REGISTER STORAGE UNIT test1( HOST="127.0.0.1", PORT=3306, DB="test1", USER="root", PASSWORD="root" );
> 
> create database test2; REGISTER STORAGE UNIT test2( HOST="127.0.0.1", PORT=3306, DB="test2", USER="root", PASSWORD="root" );
> 
> The result is that the two databases are same, which is wrong.

it is different from mysql

**Comment by McClone** [comment]
select * from pg_tables,  result are same.  but two database has different table.

**Comment by McClone** [comment]
？？？

**Comment by TeslaCN** [comment]
Query `pg_catalog` is not well supported for now. It does not affect CRUD.
