### ISSUE TITLE
can not use navicat to connect opengauss proxy

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#23891]
### Expected behavior
can use navicat to connect opengauss proxy
### Actual behavior
Notice "none of the server's SASL authentication mechanisms are supported"

**Comment by TeslaCN** [comment]
ShardingSphere-Proxy openGauss using openGauss SCRAM SHA256 authenticator, which is incompatible with PostgreSQL.

**Comment by RaigorJiang** [comment]
Supported by #24313.
