### ISSUE TITLE
refactor log output in agent core

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#23904]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

#### Expected
The logs in the Agent are output to `agent/log/stdout.log` file.

#### Notice
Since the logs in `agent.jar` use `slf4j` and `logback` for output, in order to avoid conflicts with the corresponding dependencies of the application, `slf4j` and `logback` must be shaded. Similarly, `agent.jar` cannot contain `logback.xml`, need to use `Logback SPI` for log configuration.

#### Task
+ Agent core uses `slf4j`, `logback` for log output.
+ Remove `log-api`, `log-to-slf4j`
+ Relocation `slf4j`, `logback`
+ Remove `agent/log-lib` directory
+ Remove AgentLoggerClassLoader

**Comment by Dawoodeveloper** [comment]
can i solve this issue??

**Comment by jiangML** [comment]
Hi @Dawoodeveloper  Thanks, this issue has been resolved, you can try other issues.

**Comment by Dawoodeveloper** [comment]
Ok
