### ISSUE TITLE
Query in information_schema not working

### ISSUE THREAD

**Issue by jyotisharma7** [apache/shardingsphere#23922]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere Proxy-5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere Proxy
### Expected behavior
Connection to ShardingSphere should give an output for `"select * from information_schema.sequences;"`
### Actual behavior
`ERROR:  At line 0, column 0: Object 'sequences' not found within 'information_schema'`
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
sh start.sh
psql -U root -h 127.0.0.1 -p 3307 dbname=hint_db
select * from information_schema.sequences;
select * from information_schema.tables;
```

**Comment by RaigorJiang** [comment]
Refer to #16234, ShardingSphere provides aggregated information_schema, and currently does not support sequences operations.
