### ISSUE TITLE
Failed to run Docker mode according to the integration test document

### ISSUE THREAD

**Issue by lushaorong** [apache/shardingsphere#23946]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
![image](https://user-images.githubusercontent.com/16489768/216361518-ba0b918c-4770-4ea9-a9d9-7ed96369d260.png)

Execute commands correctly

### Actual behavior
![image](https://user-images.githubusercontent.com/16489768/216361222-f2a57d97-8bed-4965-a8c1-f602875ef622.png)

### Reason analyze (If you can)
pom.xml path error in document .The correct command is
```
./mvnw -B clean install -f test/e2e/pom.xml -Pit.env.docker -Dit.cluster.adapters=proxy,jdbc -Dit.scenarios=${scenario_name_1,scenario_name_2,scenario_name_n} -Dit.cluster.databases=MySQL
```
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Run integration test with docker mode

**Comment by RaigorJiang** [comment]
Hi @lushaorong ,
Do you want to submit a PR to fix it?

**Comment by lushaorong** [comment]
> Hi @lushaorong ,
> Do you want to submit a PR to fix it?

Ok
