### ISSUE TITLE
Remove Hint DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23953]
Hi community,

Since [SQL Hint](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/#use-special-sql-comments) is more convenient and compatible with Proxy, I think it is time to consider removing [Hint DistSQL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/hint/).

#### Using DistSQL to implement Hint has the following problems:
1. To execute a query, the user needs to send `Hint DistSQL` and `DML SQL` separately, which is not friendly to use;
2. After using `Hint DistSQL`, the user needs to send an additional `CLEAR` statement;
3. When Hint is enabled, Proxy needs to make a special judgment on the connected thread, which increases the complexity; ([link](https://github.com/apache/shardingsphere/blob/efe9ee21266d6507dee4639eb0c19a6d98992325/proxy/frontend/core/src/main/java/org/apache/shardingsphere/proxy/frontend/state/impl/OKProxyState.java#L61))

Now, SQL Hint can perfectly solve the above problems, so I suggest to start the work of removing Hint DistSQL, with the following tasks:

- [x] Remove `HintRALStatementExecutor` and implementation
- [x] Remove `HintRALBackendHandler`
- [x] Remove `HintRALStatement` and subclasses
- [x] Remove Hint DistSQL documentation
- [ ] Remove the judgment related to Hint in `OKProxyState`
- [ ] Remove the configuration item: `proxy-hint-enabled`
- [x] Remove related test cases
- [x] Remove HintManagerHolder

**Comment by anmui** [comment]
hi!i want to try,can i do this?

**Comment by RaigorJiang** [comment]
Hi @anmui ,
Welcome here!  This task affects many files and may not be suitable for beginners, but you can try to submit PRs.

**Comment by yx9o** [comment]
Hi @RaigorJiang , i want to join.

**Comment by anmui** [comment]
hi,I have completed 1,2,3,5,8….Can I still submit it？🥹

**Comment by yx9o** [comment]
@anmui Ok, welcome, you submit pr.

**Comment by RaigorJiang** [comment]
According to the discussion in #24227, `proxy-hint-enabled` has not been removed, this needs to be investigated further.

**Comment by TeslaCN** [comment]
Please try removing `proxy-hint-enabled` again. Proxy has introduced flow control in frontend #25081.

**Comment by anmui** [comment]
> Please try removing `proxy-hint-enabled` again. Proxy has introduced flow control in frontend #25081.

ok
