### ISSUE TITLE
Remove useless symbol in readwrite-splitting documents

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23951]
As shown in the picture:

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/5668787/216505593-9181b601-c0bf-4173-9c6c-278f16ab36a6.png">

Ref: https://shardingsphere.apache.org/document/current/en/features/readwrite-splitting/

**Comment by mehboobali98** [comment]
Hi @RaigorJiang  , I want to contribute on this.

**Comment by RaigorJiang** [comment]
@mehboobali98 Welcome!

**Comment by RaigorJiang** [comment]
Hi @mehboobali98 , 
@piyush280599 has fixed this issue, thank you!
