### ISSUE TITLE
Optimize the inheritance structure of RALStatement 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23955]
Now, the inheritance structure of RALStatement is a bit less clear compared to RDLStatement and RQLStatement.

### RDLStatement
<img width="567" alt="image" src="https://user-images.githubusercontent.com/5668787/216525569-bad545fd-2ac1-4b69-962f-07acae62f745.png">

### RALStatement
<img width="584" alt="image" src="https://user-images.githubusercontent.com/5668787/216525679-b25b0a60-0d24-4365-8dbc-3e6a5ee363f4.png">

As shown in the figure, `QueryableRALStatement`, `UpdatableRALStatement` and `ScalingRALStatement`, they should not be classified at the same level.
And `HintRALStatement` is also special (will be removed in #23953).

I plan to classify `RALStatement` as follows to optimize their inheritance relationship:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/5668787/216527523-032c3010-1d54-4566-ae07-c71968455b5e.png">

Please let me know if you have any suggestions.

**Comment by yx9o** [comment]
Hi @RaigorJiang , can i join.

**Comment by RaigorJiang** [comment]
@yx9o Yes, you are welcome, feel free to submit a PR!
