### ISSUE TITLE
[discuss] Create an sharding index for the shardingsphere

### ISSUE THREAD

**Issue by sunkai-cai** [apache/shardingsphere#23956]
## Question

Question：After we use sharding, if the condition in the query SQL does not have a shard key, then [full database route](https://shardingsphere.apache.org/document/current/en/reference/sharding/route/#full-database-route) will be triggered.
问题：我们在使用分片后，如果查询SQL中的条件没有分片键，那么将触发[全库表路由](https://shardingsphere.apache.org/document/current/cn/reference/sharding/route/#全库表路由)。

Suggestion: If we can add a sharding index function to `shardingsphere`, it will reduce the routing requests of the full database route in some cases.
建议：如果我们可以给`shardingsphere` 增加一个分片索引功能，那将可以减少某些情况下的全库表路由请求，从而有效提高性能。

Case:  I am doing DB performance optimization for a traditional business system that has been running for more than 5 years,Use `shardingsphere-proxy` to separate hot or warm data. We use horizontal sharding database,   the `order_time` field of key sharding. Most query SQL will bring the time range condition of `order_time` field. Part of the query SQL just have the `order_id` condition, then `full database route` will be triggered.

案例：我在为一个运行超过5年的传统业务系统做DB性能优化，通过 `shardingsphere-proxy` 给数据做冷热分离。我们对订单表进行分片，将 `order_time` 字段作为分片键。大部分的查询SQL，会带上 `order_time` 字段的时间范围条件。一部分的查询SQL，是以 `order_id` 条件，将触发`全库表路由`。

```
SELECT * FROM order WHERE order_id = 10001;
```

```
SELECT * FROM order_2019 WHERE order_id = 10001;
SELECT * FROM order_2020 WHERE order_id = 10001;
SELECT * FROM order_2021 WHERE order_id = 10001;
SELECT * FROM order_2022 WHERE order_id = 10001;
SELECT * FROM order_2023 WHERE order_id = 10001;
```

If we can make an index table for order_id, then we can pass the index, query the physical tables by order_id, thereby avoiding the occurrence of `full database route`
如果我们可以给 order_id 做个索引表，那么可以通过索引，查询到 order_id 指向的分片表，进而避免`全库表路由`的发生。

**Comment by strongduanmu** [comment]
@sunkai-cai Yes, global secondary indexes can significantly improve query performance. Are you interested in designing solutions and then contributing to this feature?

**Comment by sunkai-cai** [comment]
> @sunkai-cai Yes, global secondary indexes can significantly improve query performance. Are you interested in designing solutions and then contributing to this feature?

I'm happy to do this feature.

**Comment by sunkai-cai** [comment]
issue move to #24315 .  close this.
