### ISSUE TITLE
The assembly configuration of ShardingSphere Proxy contains `logback.xml` which does not exist

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#24005]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

- When I was working on https://github.com/apache/shardingsphere/pull/23957 , I noticed that the assembly configuration of ShardingSphere Proxy contains `logback.xml` which does not exist. Refer to https://github.com/apache/shardingsphere/blob/19377e060f43daa63fb34ec4a169ab50ebce0093/distribution/proxy/src/main/assembly/shardingsphere-proxy-binary-distribution.xml .
```xml
<fileSet>
    <directory>../../proxy/bootstrap/src/main/resources</directory>
    <includes>
        <include>logback.xml</include>
    </includes>
    <outputDirectory>conf</outputDirectory>
    <fileMode>0644</fileMode>
</fileSet>
```
- I checked https://github.com/apache/shardingsphere/tree/19377e060f43daa63fb34ec4a169ab50ebce0093/proxy/bootstrap/src/main/resources and this file does not exist. Even if I compile locally, this file does not exist. So why pack a file that doesn't exist?
- ![image](https://user-images.githubusercontent.com/20187731/216774371-601c1782-7aea-4b4e-9c3f-cfe2235fe83b.png)

**Comment by RaigorJiang** [comment]
Yes, logback.xml does not exist anymore, we should update the assembly file.

**Comment by linghengqian** [comment]
- I'm working on this issue.
