### ISSUE TITLE
sqlserver paging sql mergeResultSet.getValue has a error 

### ISSUE THREAD

**Issue by kittywu66** [apache/shardingsphere#24037]
## Bug Report we using shardingsphere-jdbc-core 5.1.2
Our sqlserver paging sql execution results are as follows
![image](https://user-images.githubusercontent.com/23444920/217134727-98eae9f7-6a3a-473b-b71e-d9f97e4dcc83.png)
getIndexFromColumnLabelAndIndexMap("quoteMode") = 3，javaType of column quoteMode is Int,but javaType of column orderNo is String,
(int) The mergeResultSet. getValue method called in the ResultSetUtil. convertValue (mergeResultSet. getValue (columnIndex, int. class), int. class) statement returns the value of orderNo, resulting in an error when converting to int

![image](https://user-images.githubusercontent.com/23444920/217135343-5fe01234-0e4f-41b4-bb6f-b9c719a1b97e.png)

**Comment by zhaojinchao95** [comment]
@kittywu66 Can you try ShardingSphere` 5.3.1` version?
