### ISSUE TITLE
PostgreSQLStatementParser类静态持有DFA引用，大量解析SQL会导致OOM

### ISSUE THREAD

**Issue by kaituozhesh** [apache/shardingsphere#24031]
ATNConfig持有实例不会被回收，执行SQL解析的次数越多持有的越多。

目前我们的处理方案：定时清除引用
ParserATNSimulator interpreter = new PostgreSQLStatementParser(null).getInterpreter();
for (int i = 0; i < PostgreSQLStatementParser._ATN.getNumberOfDecisions(); ++i) {
     interpreter.decisionToDFA[i] = new DFA(PostgreSQLStatementParser._ATN.getDecisionState(i), i);
 }

**Comment by zhaojinchao95** [comment]
@kaituozhesh Hi, only support english issue, I will close it first, you can resubmit one
