### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_UUID' 

### ISSUE THREAD

**Issue by jyotisharma7** [apache/shardingsphere#24043]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere Proxy 5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Support POSTGRESQL_TYPE_UUID column type.
### Actual behavior
`java.lang.IllegalArgumentException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_UUID' in column type when process binary protocol value`
### Reason analyze (If you can)
```
java.lang.IllegalArgumentException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_UUID' in column type when process binary protocol value
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.extended.bind.protocol.PostgreSQLBinaryProtocolValueFactory.getBinaryProtocolValue(PostgreSQLBinaryProtocolValueFactory.java:145)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.extended.bind.PostgreSQLComBindPacket.getBinaryParameters(PostgreSQLComBindPacket.java:143)
	at org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.extended.bind.PostgreSQLComBindPacket.readParameters(PostgreSQLComBindPacket.java:82)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.bind.PostgreSQLComBindExecutor.execute(PostgreSQLComBindExecutor.java:51)
	at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.PostgreSQLAggregatedCommandExecutor.execute(PostgreSQLAggregatedCommandExecutor.java:41)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by jyotisharma7** [comment]
@TeslaCN Can you please let me know where the code changes have to be made so that I can give it a try?
I was referring to [this](https://github.com/apache/shardingsphere/issues/9000) issue.
Do we need to make same type of code changes?

**Comment by TeslaCN** [comment]
> @TeslaCN Can you please let me know where the code changes have to be made so that I can give it a try?
> I was referring to [this](https://github.com/apache/shardingsphere/issues/9000) issue.
> Do we need to make same type of code changes?

Hi @jyotisharma7 I have fixed a similar issue recently. https://github.com/apache/shardingsphere/pull/23786/files
The way to fix is similar.

**Comment by jyotisharma7** [comment]
Hi @TeslaCN I am trying to fix this issue to give it a try.
But I am facing the below issue after I tried making similar changes.
```
org.postgresql.util.PSQLException: ERROR: Unsupported SQL operation: Unsupported PostgreSQL format code `63762`
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468) ~[postgresql-42.2.6.jar:42.2.6]
```

This issue is occuring from PostgreSQLValueFormat.java class. For UUID data type do we have to pass 0 or 1?

**Comment by TeslaCN** [comment]
> Hi @TeslaCN I am trying to fix this issue to give it a try. But I am facing the below issue after I tried making similar changes.
> 
> ```
> org.postgresql.util.PSQLException: ERROR: Unsupported SQL operation: Unsupported PostgreSQL format code `63762`
> at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468) ~[postgresql-42.2.6.jar:42.2.6]
> ```
> 
> This issue is occuring from PostgreSQLValueFormat.java class. For UUID data type do we have to pass 0 or 1?
> 
> It is failing at **result.add(PostgreSQLValueFormat.valueOf(payload.readInt2()));** of PostgreSQLComBindPacket.java because payload.readInt2() returns value greater than 0 or 1.
> 
> ```
>  public List<PostgreSQLValueFormat> readResultFormats() {
>         int resultFormatsLength = payload.readInt2();
>         if (0 == resultFormatsLength) {
>             return Collections.emptyList();
>         }
>         if (1 == resultFormatsLength) {
>             return Collections.singletonList(PostgreSQLValueFormat.valueOf(payload.readInt2()));
>         }
>         List<PostgreSQLValueFormat> result = new ArrayList<>(resultFormatsLength);
>         for (int i = 0; i < resultFormatsLength; i++) {
>             result.add(PostgreSQLValueFormat.valueOf(payload.readInt2()));
>         }
>         return result;
>     }
> ```

The result format in protocol must be 0 or 1. 

If the result was not 0 or 1, it may be affected by decoding previous fields such as value of parameter.

https://www.postgresql.org/docs/current/protocol-message-formats.html
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/20503072/217686524-fd87a22f-7663-4601-a805-7e721d974b38.png">

**Comment by jyotisharma7** [comment]
@TeslaCN Do we need to write e2e suite test cases also?

**Comment by jyotisharma7** [comment]
@TeslaCN I have raised this PR. Can you please have a look into it?

**Comment by TeslaCN** [comment]
> @TeslaCN Do we need to write e2e suite test cases also?

Yes, if you could.

**Comment by TeslaCN** [comment]
> @TeslaCN @tristaZero I have raised this PR. Can you please have a look into it?

I've left some comments in the PR.
