### ISSUE TITLE
writeRouteOnly hint comment does not work? ( comment is not in mysql packet payload)?thanks

### ISSUE THREAD

**Issue by hza2022x** [apache/shardingsphere#24057]
i execute the following sql via mysql client: 
/* ShardingSphere hint: writeRouteOnly=true */ select  * from sku where id =5916249356177

but the sql value in the following breakpoint doesn't contain the comment 'ShardingSphere hint';

    public MySQLComQueryPacket(final MySQLPacketPayload payload) {
        super(MySQLCommandPacketType.COM_QUERY);
        sql = payload.readStringEOF(); // here :sql = select  * from sku where id =5916249356177
    }

shardingsphere version:   5.0.0

could any one explain why this happened? many thanks.

**Comment by hza2022x** [comment]
it workds after add -c to the connect String.  thanks

**Comment by zhaojinchao95** [comment]
> it works after add -c to the connect String. thanks

@hza2022x So, this problem are solved?

**Comment by hza2022x** [comment]
yes solved. thanks.
