### ISSUE TITLE
no viable alternative at input 'INSERT'

### ISSUE THREAD

**Issue by zhoubin7** [apache/shardingsphere#24053]
## Question

sharding-sphere 5.3.0

select *,INSERT ( receiver_phone, 4, 4, '****' ) AS 'receiverPhone' from table

'insert' in select query fields is not supported

**Comment by RaigorJiang** [comment]
Hi @zhoubin7 
What database protocol are you using?

**Comment by zhoubin7** [comment]
Hi @RaigorJiang 
mysql 8.0

**Comment by zhoubin7** [comment]
> 你好@zhoubin7 你使用什么数据库协议？

mysql

**Comment by RaigorJiang** [comment]
Even if I copy your SQL statement to the native mysql 8, it cannot be executed. Can you provide detailed information?

**Comment by zhoubin7** [comment]
> _INSERT (receiver_phone, 4, 4, '_ ***' ) AS 'receiverPhone'

![image](https://user-images.githubusercontent.com/38552814/221343351-406a27c2-4c6c-4521-b3c8-1cc3818fd6a0.png)

**Comment by RaigorJiang** [comment]
Ok, there is an extra comma in your original description, so it will not work when copying.


> select _,INSERT ( receiver_phone, 4, 4, '_***' ) AS 'receiverPhone' from table
> 
> 'insert' in select query fields is not supported

**Comment by RaigorJiang** [comment]
Hi @zhoubin7 
I couldn't find the usage of SELECT INSERT in the [syntax docs](https://dev.mysql.com/doc/refman/8.0/en/select.html), only some [test cases](https://github.com/mysql/mysql-server/search?q=SELECT+INSERT) found by searching.
Do you have relevant information to provide?

**Comment by RaigorJiang** [comment]
Hi @zhoubin7 
This issue has been fixed and you can verify it on the master branch.
Thank you!
