### ISSUE TITLE
separate database does not separate table

### ISSUE THREAD

**Issue by zhoubin7** [apache/shardingsphere#24067]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

shardingsphere 5.3.0

Whether to support, separate database does not separate table
provide some examples

**Comment by Pace2Car** [comment]
Hi @zhoubin7, ShardingSphere has the examples module, please take a look
As for data sharding configuration, you can refer to: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/
