### ISSUE TITLE
Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#24073]
### Which version of ShardingSphere did you use?
5.3.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Actual behavior
backend on mysql 5.7  and  throw a exception:
Unknown system variable 'transaction_isolation'

**Comment by McClone** [comment]
mysql-connector-java-5.1.47.jar  and mysql-connector-java-8.0.11.jar  are try.but is still wrong.

**Comment by McClone** [comment]
I use huawei cloud mysql 5.7

**Comment by zhaojinchao95** [comment]
@McClone  `proxy-mysql-default-version: 5.7.22` Add this properties configuration and try it again.
