### ISSUE TITLE
Consider making ShardingSphere-Proxy support Unix Domain Socket

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#24095]
### Describe the feature you would like.

The ShardingSphere-Proxy support TCP/IP only for now.
If ShardingSphere-Proxy supported UDS:
- Improve local access network performance.
- Client could connect to Proxy without password.

**Comment by sunkai-cai** [comment]
let me try.

**Comment by TeslaCN** [comment]
Welcome. @sunkai-cai 
We need to discuss about how to configure the UDS path in Proxy.

**Comment by sunkai-cai** [comment]
@TeslaCN 

我们可以先在 start.sh 上加 一个选项，例如 ”-s /var/rum/shardingshpere.sock“ 或者 ”--socket  /var/rum/shardingshpere.sock“

We can add an option to start.sh at first, such as "-s /var/rum/shardingshpere.sock" or " --socket /var/rum/shardingshpere.sock"

**Comment by TeslaCN** [comment]
> @TeslaCN
> 
> 我们可以先在 start.sh 上加 一个选项，例如 ”-s /var/rum/shardingshpere.sock“ 或者 ”--socket /var/rum/shardingshpere.sock“
> 
> We can add an option to start.sh at first, such as "-s /var/rum/shardingshpere.sock" or " --socket /var/rum/shardingshpere.sock"

About the option naming, we could refer to the options of the database.

**Comment by sunkai-cai** [comment]
mysqld use --socket ,  but  the option naming of start.sh for shardingshpere-proxy  use "-a -p -c ".

**Comment by sunkai-cai** [comment]
@TeslaCN  Proxy need to use Unix Domain Socket and TCP/IP at the same time？

**Comment by TeslaCN** [comment]
> @TeslaCN Proxy need to use Unix Domain Socket and TCP/IP at the same time？

I think it is necessary.
