### ISSUE TITLE
Can sharding-proxy support batch insert

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#24133]
version:Shardingsphere-Proxy.5.2.1
code:
```
connection:jdbc://mysql://ip:port/db?rewriteBatchedStaments=true
Statement stmt=conn.createStatement();
for(int int i=0;i<num;i++){
stmt.addBatch("insert into tabel(name) values("‘name"+i+"’)");
}
stmt.executeBatch();
```
when num<=4,it's ok.But when num>4,it throw a exception:bad SQL grammar[INSERT INTO table.....], You have an error in your SOLyntax; check the manual that corresponds to your Mysql server version for the right syntax to use near "INSERT INTO

**Comment by TeslaCN** [comment]
Could you try using `PreparedStatement`?

**Comment by koala775** [comment]
Yes,It's ok.But have some other problem.Use PreparedStatement ,  special character escape ,for example the ' turn ‘’，but we need \‘,so we change the way.

**Comment by TeslaCN** [comment]
Parsing multi statements is unsupported in ShardingSphere for now.

**Comment by koala775** [comment]
But，PreparedStatement is ok.Is any difference between them.

**Comment by koala775** [comment]
Have reference document?

**Comment by TeslaCN** [comment]
Using `PreparedStatement` with `rewriteBatchedStaments=true`. Insert statement `insert into tbl (col) values (?)` would be rewrote to multi values like the following:
```sql
insert into tbl (col) values (1), (2), (3)...
```

**Comment by koala775** [comment]
Thanks.So using Statement with rewriteBatchedStaments=true is not support?

**Comment by TeslaCN** [comment]
> Thanks.So using Statement with rewriteBatchedStaments=true is not support?

I think so.

**Comment by jinliangXX** [comment]
> Parsing multi statements is unsupported in ShardingSphere for now.

When is this feature expected to be supported?

**Comment by terrymanu** [comment]
No plan, does anyone want to finish the issue?
