### ISSUE TITLE
I reported an error using mysql cli  `use database`

### ISSUE THREAD

**Issue by ckall** [apache/shardingsphere#24157]
Version: 5.3.0
Error Message: 
we find java version: java17, full_version=17.0.2, full_path=/usr/local/openjdk-17/bin/java
The port is 3308
The classpath is /opt/shardingsphere-proxy/conf:.:/opt/shardingsphere-proxy/lib/*:/opt/shardingsphere-proxy/ext-lib/*
main class org.apache.shardingsphere.proxy.Bootstrap 3308 /opt/shardingsphere-proxy/conf 0.0.0.0 false
Thanks for using Atomikos! This installation is not registered yet. 
REGISTER FOR FREE at http://www.atomikos.com/Main/RegisterYourDownload and receive:
- tips & advice 
- working demos 
- access to the full documentation 
- special exclusive bonus offers not available to others 
- everything you need to get the most out of using Atomikos!
[INFO ] 2023-02-14 09:02:11.041 [main] o.a.s.p.v.ShardingSphereProxyVersion - Database name is `MySQL`, version is `8.0.28`, database name is `order`
[INFO ] 2023-02-14 09:02:11.596 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy Standalone mode started successfully
[ERROR] 2023-02-14 09:02:29.940 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.lang.NullPointerException: Cannot invoke "org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.close()" because "this.databaseCommunicationEngine" is null
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.fieldlist.MySQLComFieldListPacketExecutor.close(MySQLComFieldListPacketExecutor.java:92)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:124)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ckall** [comment]
`

schemaName: order

dataSources:
  test_write_order_0:
    url: jdbc:mysql://xxxx:32770/test_order_0?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_write_order_1:
    url: jdbc:mysql://xxxx:32770/test_order_1?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_write_order_2:
    url: jdbc:mysql://xxxx:32770/test_order_2?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_write_order_3:
    url: jdbc:mysql://xxxx:32770/test_order_3?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_write_order_4:
    url: jdbc:mysql://xxxx:32770/test_order_4?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_write_order_5:
    url: jdbc:mysql://xxxx:32770/test_order_5?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

  test_read_order_0:
    url: jdbc:mysql://xxxx:32771/test_order_0?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_read_order_1:
    url: jdbc:mysql://xxxx:32771/test_order_1?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_read_order_2:
    url: jdbc:mysql://xxxx:32771/test_order_2?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_read_order_3:
    url: jdbc:mysql://xxxx:32771/test_order_3?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_read_order_4:
    url: jdbc:mysql://xxxx:32771/test_order_4?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  test_read_order_5:
    url: jdbc:mysql://xxxx:32771/test_order_5?charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

rules:
  - !READWRITE_SPLITTING
    dataSources:
      test_order_0:
        staticStrategy:
          writeDataSourceName: test_write_order_0
          readDataSourceNames:
            - test_read_order_0
        loadBalancerName: random
      test_order_1:
        staticStrategy:
          writeDataSourceName: test_write_order_1
          readDataSourceNames:
            - test_read_order_1
        loadBalancerName: random
      test_order_2:
        staticStrategy:
          writeDataSourceName: test_write_order_2
          readDataSourceNames:
            - test_read_order_2
        loadBalancerName: random
      test_order_3:
        staticStrategy:
          writeDataSourceName: test_write_order_3
          readDataSourceNames:
            - test_read_order_3
        loadBalancerName: random
      test_order_4:
        staticStrategy:
          writeDataSourceName: test_write_order_4
          readDataSourceNames:
            - test_read_order_4
        loadBalancerName: random
      test_order_5:
        staticStrategy:
          writeDataSourceName: test_write_order_5
          readDataSourceNames:
            - test_read_order_5
        loadBalancerName: random
    loadBalancers:
      random:
        type: ROUND_ROBIN
  - !SHARDING
    tables:
      test_order:
        actualDataNodes: test_order_${0..5}.order_${0..4}
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: order_inline
        databaseStrategy:
          standard:
            shardingColumn: agent_id
            shardingAlgorithmName: database_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    defaultShardingColumn: agent_id
    defaultDatabaseStrategy:
      standard:
        shardingColumn: agent_id
        shardingAlgorithmName: database_inline
    defaultTableStrategy:
      standard:
        shardingColumn: user_id
        shardingAlgorithmName: order_inline
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: test_order_${agent_id % 6}
      order_inline:
        type: INLINE
        props:
          algorithm-expression: order_${user_id % 5}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
`

**Comment by RaigorJiang** [comment]
@ckall 
Thank you for your feedback. 
In addition, your markdown markup may be incorrect, and the format does not take effect.

**Comment by ckall** [comment]
Hello, have you solved it?

**Comment by RaigorJiang** [comment]
@ckall  In my test, this problem cannot be reproduced, can you reproduce it stably?
