### ISSUE TITLE
likeQueryColumnName in PostgreSQL does not take effect

### ISSUE THREAD

**Issue by McClone** [apache/shardingsphere#24173]
### Expected behavior
select * from xx  where a like '%a%' has result;
### Actual behavior
select * from xx  where a like '%a%' has no  result;

**Comment by RaigorJiang** [comment]
Hi @McClone 
Please provide encrypt rule configuration and table structure.

**Comment by McClone** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3762822829519345228 skey=@crypt_a483e9a3_ea8e947805d191749b3d3654adf9fdec mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/20875807/219347000-dafc92b4-9f18-4c26-85bd-db739f2baa61.jpg)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=6708885929683913169 skey=@crypt_a483e9a3_ea8e947805d191749b3d3654adf9fdec mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/20875807/219347019-45b9d1bf-c5ef-4708-b858-57832f9464f3.jpg)

**Comment by McClone** [comment]
when use distsql on postgresql can not work, but same distsql on mysql can work.

**Comment by gxxiong** [comment]
Try the keyword like in uppercase

**Comment by McClone** [comment]
> Try the keyword like in uppercase

Is it reasonable to capitalize, or is it a bug?

**Comment by tuichenchuxin** [comment]
e2e test already had this situation.
https://github.com/apache/shardingsphere/blob/8bfd61e0f881cfe3e934b0d4790b8a0472fcb6fe/test/e2e/suite/src/test/resources/cases/dql/dql-integration-select.xml#L171-L174
Maybe you can check logs to get more details.

**Comment by McClone** [comment]
> e2e test already had this situation.
> 
> https://github.com/apache/shardingsphere/blob/8bfd61e0f881cfe3e934b0d4790b8a0472fcb6fe/test/e2e/suite/src/test/resources/cases/dql/dql-integration-select.xml#L171-L174
> 
> 
> Maybe you can check logs to get more details.

logs show sql is wrong. like query value is not CHAR DIGEST value,just like encrypted value

**Comment by McClone** [comment]
This will not happen through configuration file configuration, but distsql will.I think is a bug on distsql.

**Comment by tuichenchuxin** [comment]
Is there any error logs?

**Comment by tuichenchuxin** [comment]
Or after crete rule. execute `show encrypt rules` to check the rule is created.

**Comment by McClone** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=5137752149934886846 skey=@crypt_a483e9a3_4a5602b69e1f20f5f9b6b7e1c3ea2de3 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/20875807/219593659-9cc1da7e-e50c-4998-966a-8561e2268e25.jpg)

**Comment by McClone** [comment]
The number in like is calculated incorrectly.
This value   963eddd18... is wrong.

**Comment by McClone** [comment]
> Or after crete rule. execute `show encrypt rules` to check the rule is created.

it is have rules.

**Comment by gxxiong** [comment]
@tuichenchuxin 
2023-02-17 16:42:18 [INFO ] 2023-02-17 08:42:18.846 [Connection-2-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM t_encrypt WHERE user_name like '熊%'
2023-02-17 16:42:18 [INFO ] 2023-02-17 08:42:18.846 [Connection-2-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT "t_encrypt"."id", "t_encrypt"."user_name" AS "user_name" FROM t_encrypt WHERE user_name_like like 'rvRclQPExJDkhss3DQsRkQ=='
2023-02-17 16:42:32 [INFO ] 2023-02-17 08:42:32.417 [Connection-2-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SELECT * FROM t_encrypt WHERE user_name LIKE '熊%'
2023-02-17 16:42:32 [INFO ] 2023-02-17 08:42:32.418 [Connection-2-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT "t_encrypt"."id", "t_encrypt"."user_name" AS "user_name" FROM t_encrypt WHERE user_name_like LIKE '佹%'

table	logic_column	cipher_column	plain_column	assisted_query_column	like_query_column	encryptor_type	encryptor_props	assisted_query_type	assisted_query_props	like_query_type	like_query_props	query_with_cipher_column
t_encrypt	user_name	user_name			user_name_like	AES	aes-key-value=123456abc			CHAR_DIGEST_LIKE		true

**Comment by tuichenchuxin** [comment]
Can you provide complete steps to do it? I can try to reproduce this problem.
And sql please use \``` select... \```

**Comment by McClone** [comment]
> Can you provide complete steps to do it? I can try to reproduce this problem. And sql please use ``` select... ```

1.start postgresql proxy server
2.create database,create storge unit
3.create encrypt rule distsql
4.select * from xxx_table where xxx_field like '%xxx%'


Just the fuzzy query uses lowercase like on postgresql，nothing special about the others.

**Comment by tuichenchuxin** [comment]
OK，I'll figure it out.

**Comment by tuichenchuxin** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/23771/

**Comment by mainidear** [comment]
Can you provide the sample code of "Like query column"? @McClone
