### ISSUE TITLE
Do I have to introduce the H2 database to replace the original Memory mode?

### ISSUE THREAD

**Issue by kzxuan** [apache/shardingsphere#24189]
SpringBoot 2.7.2, ShardingSphere-JDBC 5.3.1

The latest version seems to only provide two optional modes: Standalone (default) and Cluster.
When I use Standalone, I need to provide a JDBC url, which can be MySQL or H2.
However, our production env does not allow the execution of MySQL commands like 'drop table' or 'create table'.
So do I have to import the H2 database instead of the Memory mode?

**Comment by tuichenchuxin** [comment]
@zhaojinchao95 hello, can you help to check it?

**Comment by zhaojinchao95** [comment]
@kzxuan Yes, ShardingSphere default mode is Standalone, it's use h2 database.
