### ISSUE TITLE
use Spring Transactional change isolation  not work

### ISSUE THREAD

**Issue by MrDustZero** [apache/shardingsphere#24188]
**shardingsphere-jdbc  5.0.0**

mysql default isolation : REPEATABLE-READ
spring use :  @Transactional(rollbackFor = Exception.class,isolation = Isolation.READ_UNCOMMITTED)

spring change  isolation  code in  org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction:
`               // Apply specific isolation level, if any.
		Integer previousIsolationLevel = null;
		if (definition != null && definition.getIsolationLevel() != TransactionDefinition.ISOLATION_DEFAULT) {
			if (debugEnabled) {
				logger.debug("Changing isolation level of JDBC Connection [" + con + "] to " +
						definition.getIsolationLevel());
			}
			int currentIsolation = con.getTransactionIsolation();
			if (currentIsolation != definition.getIsolationLevel()) {
				previousIsolationLevel = currentIsolation;
				con.setTransactionIsolation(definition.getIsolationLevel());
			}
		}
`

if (currentIsolation != definition.getIsolationLevel())   is false  no changes made
ShardingSphereConnection    default isolation  TRANSACTION_READ_UNCOMMITTED
`
private int transactionIsolation = TRANSACTION_READ_UNCOMMITTED;
`

but sql session isolation still REPEATABLE-READ

How to solve it?

**Comment by tuichenchuxin** [comment]
@FlyingZC hi, can you help to check it?

**Comment by MrDustZero** [comment]
已解决  配置文件加入 spring.shardingsphere.datasource.defaultTransactionIsolation=4 (4 代表 REPEATABLE-READ)， 这样连接池在创建连接的时候，会把这个值赋给 ShardingSphereConnection
