### ISSUE TITLE
Why do I have to configure the table rule when I use the hint algorithm?

### ISSUE THREAD

**Issue by dasonXu** [apache/shardingsphere#24197]
Why do I have to configure the table rule when I use the hint algorithm?

the version of sharding-jdbc: 5.2.1

the config:

`spring.shardingsphere.rules.sharding.default-database-strategy.hint.sharding-algorithm-name=myHint
spring.shardingsphere.rules.sharding.default-table-strategy.none
spring.shardingsphere.rules.sharding.sharding-algorithms.myHint.type=CLASS_BASED
spring.shardingsphere.rules.sharding.sharding-algorithms.myHint.props.strategy=HINT
spring.shardingsphere.rules.sharding.sharding-algorithms.myHint.props.algorithmClassName=xxxxx`

**i only want to sharding database without sharding tables, but the configure is not works, it must config the table what u want to sharding**

because of the source code, it will new ShardingIgnoreRoutingEngine ?

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/34209278/219324122-c7c6de1c-8a1d-483d-b371-c4019b584334.png">

so when i want to sharding database without sharding tables. also need me add all tables config to the file?

**Comment by Qianyi951015** [comment]
i think u should config at least 1 sharding table rule to make the default strategy effective

**Comment by dasonXu** [comment]
> i think u should config at least 1 sharding table rule to make the default strategy effective

so, when i config a fake table, then all table will use my default-database-strategy?

**Comment by dasonXu** [comment]
> i think u should config at least 1 sharding table rule to make the default strategy effective

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/34209278/219353349-4f46acd2-3989-466a-8819-260c506614cc.png">

it will compare sql tables and config tables, if u have not config, the sql will not rote to the database.

**Comment by Qianyi951015** [comment]
> > i think u should config at least 1 sharding table rule to make the default strategy effective
> 
> so, when i config a fake table, then all table will use my default-database-strategy?

no, I don't think ShardingSphere currently support sharding the whole database

**Comment by RaigorJiang** [comment]
ShardingSphere needs to explicitly declare which tables need to be sharded and how the tables are distributed.
Otherwise, if user do not specify a hint value when execute query, how does ShardingSphere choose a route?

**Comment by dasonXu** [comment]
> ShardingSphere needs to explicitly declare which tables need to be sharded and how the tables are distributed. Otherwise, if user do not specify a hint value when execute query, how does ShardingSphere choose a route?

sure i have specified a hint value(a tenantId in the code),  now i only want to sharding database with all tables.

**Comment by RaigorJiang** [comment]
@dasonXu  OK, we can use `defaultDatabaseStrategy` to simplify some configurations, but still need to declare the name and `dataNodes` of each sharding table in the sharding rule.

ShardingSphere needs to adapt to the usage scenarios of most users. If your needs are not met, are you willing to submit a PR to realize it?
