### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: can't get index from columnLabel[xxxxxxxxx]

### ISSUE THREAD

**Issue by dabingRyan** [apache/shardingsphere#24207]
## Bug Report
java.sql.SQLFeatureNotSupportedException: can't get index from columnLabel[xxxxxxxxx].

### Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.0</version>
        </dependency>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc Read/Write Splitting

### Expected behavior

java:
private Collection<ColumnProjection> getColumnProjections(final Collection<Projection> projections) {
        Collection<ColumnProjection> result = new LinkedList<>();
        for (Projection each : projections) {
            if (each instanceof ColumnProjection) {
                result.add((ColumnProjection) each);
            }
            if (each instanceof ShorthandProjection) {
                result.addAll(((ShorthandProjection) each).getActualColumns().values());
            }
        }
        return result;
    }

in this projections ,there has some ExpressionProjection, but not add to result.   
sql:
select ifnull(sell_price,0) productPrice from product where id=1;    

ifnull(sell_price) productPrice is a ExpressionProjection

**Comment by dabingRyan** [comment]
my  SQL statements is:
`
select *
from (select a.CLIENT                      client,
             a.PRO_SITE                    storeId,
             f.STO_NAME                    stoName,
             a.PRO_SELF_CODE               proCode,
             a.PRO_DEPICT                  proDepict,
             a.PRO_PYM                     proPym,
             IFNULL(SUM(b.GSSB_QTY), 0) AS inventoryQty
      from GAIA_PRODUCT_BUSINESS a
               LEFT JOIN GAIA_SD_STOCK_BATCH b on a.PRODUCT_ID = b.PRODUCT_ID
      WHERE a.CLIENT = 'ABCD') aa;
`
there is an exception 
`Can not get index from column label `inventoryQty`.; nested exception is java.sql.SQLFeatureNotSupportedException: Can not get index from column label `inventoryQty`.>
org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'inventoryQty' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: Can not get index from column label `inventoryQty`.
; Can not get index from column label `inventoryQty`.; nested exception is java.sql.SQLFeatureNotSupportedException: Can not get index from column label `inventoryQty`.
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:96)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at com.sun.proxy.$Proxy110.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy174.findListForHisClinicZhongXiPage(Unknown Source)
	at com.gov.external.modules.product.service.impl.ProductServiceImpl.searchClinicPage(ProductServiceImpl.java:338)
	at com.gov.external.modules.product.service.impl.ProductServiceImpl$$FastClassBySpringCGLIB$$8fc4ea9f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)`

But when I delete the outermost alias aa, it's ok!
like this :
`select a.CLIENT                      client,
             a.PRO_SITE                    storeId,
             f.STO_NAME                    stoName,
             a.PRO_SELF_CODE               proCode,
             a.PRO_DEPICT                  proDepict,
             a.PRO_PYM                     proPym,
             IFNULL(SUM(b.GSSB_QTY), 0) AS inventoryQty
      from GAIA_PRODUCT_BUSINESS a
               LEFT JOIN GAIA_SD_STOCK_BATCH b on a.PRODUCT_ID = b.PRODUCT_ID
      WHERE a.CLIENT = 'ABCD'`

**Comment by fangs95** [comment]
This problem is due to the use of expressions in the select clause. It should be because this is a framework for data shard that the expressions in select are disabled.
org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionEngine#getColumnProjections
```java
    private Collection<ColumnProjection> getColumnProjections(final Collection<Projection> projections) {
        Collection<ColumnProjection> result = new LinkedList<>();
        for (Projection each : projections) {
            if (each instanceof ColumnProjection) {
                result.add((ColumnProjection) each);
            }
            if (each instanceof ShorthandProjection) {
                result.addAll(((ShorthandProjection) each).getActualColumns().values());
            }
        }
        return result;
    }
```
This code will filter out the ExpressionProjection.

Because I only use read-write separation, I override this method in my own project.
```java
    private Collection<ColumnProjection> getColumnProjections(final Collection<Projection> projections) {
        Collection<ColumnProjection> result = new LinkedList<>();
        int mockSeq = 0;
        for (Projection each : projections) {
            if (each instanceof ColumnProjection) {
                result.add((ColumnProjection) each);
            }
            if (each instanceof ExpressionProjection) {
                ExpressionProjection expressionProjection = (ExpressionProjection) each;
                ColumnProjection projection = new ColumnProjection(null, "mock" + mockSeq++, expressionProjection.getAlias().get());
                result.add(projection);
            }
            if (each instanceof ShorthandProjection) {
                result.addAll(((ShorthandProjection) each).getActualColumns().values());
            }
        }
        return result;
    }
```
I just don't know if changing this will cause other problems

**Comment by flower-you** [comment]
but ProjectionEngine is final,can't override. How did you do it?

**Comment by strongduanmu** [comment]
Duplicate with #24207

**Comment by zxk1111** [comment]
i has the same error,like select t.*  from (select s.field_1,if(s.field_2 is null,1,2) as field_2 from sub s)t  will display this error because of t.*,
if like select t.field_1,t.field_2 will success,

error msg:
java.sql.SQLFeatureNotSupportedException: can't get index from columnLabel[field_2]

related version:
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
</dependency>
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.2.20</version>
</dependency>
