### ISSUE TITLE
what is the grade of maturity of  XA transaction? any one validated it on production env?

### ISSUE THREAD

**Issue by hza2022x** [apache/shardingsphere#24216]
what is the grade of maturity of  XA transaction? 
Is there any one that validated it on production env? if so, which provider is  used, atomikos, bitronix, or narayana?
Many thanks

ps: I'm using sharding proxy 5.0.0.

**Comment by FlyingZC** [comment]
Recommended to use narayana in production.

**Comment by frankwang314** [comment]
Bug exists for narayana + proxy(5.2.1),  refer to the issue: #24215

**Comment by strongduanmu** [comment]
@frankwang314 Thank you for your feedback. @FlyingZC Can you take a look at this problem?

**Comment by FlyingZC** [comment]
I will investigate this issue, please assign it to me. @strongduanmu

**Comment by hza2022x** [comment]
> 


> production

Thanks for your recommendation.

I'm using sharding proxy 5.0.0.   i found the followings TX features are released in 5.1.1:
Distributed Transaction: Add savepoint support for ShardingSphere proxy
Distributed Transaction: Support auto rollback when report exception in transaction block for PostgreSQL and openGauss
Distributed Transaction: Make it is easy to use with Narayana
Distributed Transaction: Add savepoint support for ShardingSphere-JDBC

Is there any probability to use  narayana with xa in version 5.0.0? and if it's possible, how is the performance of narayana?

thanks.

**Comment by FlyingZC** [comment]
@hza2022x Reply under this issue #24215

**Comment by FlyingZC** [comment]
Closed due to no reply.
