### ISSUE TITLE
shardingsphere-jdbc-core-spring-boot-starter,When will version 5.3.0 be released?

### ISSUE THREAD

**Issue by mainidear** [apache/shardingsphere#24258]
## Question
shardingsphere-jdbc-core-spring-boot-starter,When will version 5.3.0 be released?

https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core-spring-boot-starter

**Comment by strongduanmu** [comment]
Hi @mainidear, `shardingsphere-jdbc-core-spring-boot-starter` has been removed. You can try ShardingSphere Driver. For details, please refer to the official document - https://shardingsphere.apache.org/document/5.3.0/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/

**Comment by Comven** [comment]
The configuration of each release changes a lot, resulting in worse usability and almost difficult to upgrade smoothly

**Comment by strongduanmu** [comment]
Yes, this did lead to incompatibility, so we chose to make API adjustments in version 5.3.0. In the long run, removing `shardingsphere-jdbc-core-spring-boot-starter` and using native `ShardingSphereDriver` can reduce the difficulty for users.

**Comment by strongduanmu** [comment]
@mainidear @Comven @Scarange In addition, compatibility is a challenging task. If you are interested in participating in the ShardingSphere community, we can also consider maintaining minor versions for a long time, such as: 5.2.0, 5.2.1, 5.2.2, and maintain API compatibility through these versions . This requires everyone to work together. At present, we don't have enough people to complete this work.
