### ISSUE TITLE
 Where can I find the use example of "Like query column" in the project？？

### ISSUE THREAD

**Issue by mainidear** [apache/shardingsphere#24268]
## Question

 Where can I find the use example of "Like query column" in the project？？
![image](https://user-images.githubusercontent.com/5800685/220223979-dd523dfd-dc62-47ea-9cdb-008885197a73.png)
![image](https://user-images.githubusercontent.com/5800685/220224229-846405f0-6b37-49e9-be2e-c215ffee4a1f.png)

**Comment by strongduanmu** [comment]
Duplicate with #24269
