### ISSUE TITLE
I'm currently looking for this example "Like query column" and haven't found it yet? Help please！

### ISSUE THREAD

**Issue by mainidear** [apache/shardingsphere#24269]
![1676944327246](https://user-images.githubusercontent.com/5800685/220227986-2fc31ce7-4363-46c3-a109-849ecbb737b1.jpg)
Where can I find the encryption example mentioned in the above picture on github, and there is no gitee code example at present, please post the latest example code path, thank you!

I'm currently looking for this example "Like query column" and haven't found it yet? Help please！

**Comment by strongduanmu** [comment]
@mainidear Yes, there is no example of encrypt LIKE feature in the example so far. Would you like to help add this example?

**Comment by strongduanmu** [comment]
In addition, you can read this document to see how encrypt like is used. https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/encrypt/

**Comment by mainidear** [comment]
> 

OK

**Comment by mainidear** [comment]
> @mainidear Yes, there is no example of encrypt LIKE feature in the example so far. Would you like to help add this example?

OK

**Comment by totalo** [comment]
hi ,@mainidear  Now that there are no concrete examples, you can write sample code using the modules generated by the latest examples[1], combined with documentation references[2]. You can also contribute encrypted queries of type like to the example generation module.

[1]  https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-example-generator
[2]  https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/java-api/rules/encrypt/

**Comment by strongduanmu** [comment]
Close due to long time no response.
