### ISSUE TITLE
Add more unit test for ImportDatabaseConfigurationUpdater

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#24279]
Hi community,

Now, `ImportDatabaseConfigurationUpdater` has `sharding`、`readwrite-splitting`、`discovery` rule unit test. But, i think we need to add unit test for `encrypt`、`shadow`、`mask` rule.

- [ ] encrypt rule
- [ ] shadow rule
- [ ] mask rule

**Comment by Qianyi951015** [comment]
please assign to me

**Comment by zhaojinchao95** [comment]
> please assign to me

OK
