### ISSUE TITLE
return generatedKeys when use ShardingSpherePreparedStatement.executeBatch

### ISSUE THREAD

**Issue by baijun44** [apache/shardingsphere#24294]
### Is your feature request related to a problem?
yes
### Describe the feature you would like.
Now I use readwriteSplitting feature and execute BatchInsert, can't get generatedKeys.
In this situation, I use only one database (write db) ,I hope get more datasource features when sql is routed only one database.just like using druid.

**Comment by RaigorJiang** [comment]
Hi @baijun44 
Are you using an auto-increment primary key?

**Comment by baijun44** [comment]
> Hi @baijun44 Are you using an auto-increment primary key?

yes, if I execute single insert, it works.
I try to modify executeBatch method and cache java.sql.Statement object just like execute method does. it can run. So, I hope get official support.

**Comment by RaigorJiang** [comment]
Hi @baijun44 
Would you like to submit a PR?

**Comment by baijun44** [comment]
> Hi @baijun44 Would you like to submit a PR?

Yes,Let me try.

**Comment by baijun44** [comment]
@RaigorJiang hello,could you help me review the code? I passed all tests on my pc.

**Comment by RaigorJiang** [comment]
@baijun44 Thanks for your contribution, @strongduanmu will help us review.

**Comment by strongduanmu** [comment]
Fixed by #24405
