### ISSUE TITLE
How do I listen to the Sharding-proxy if it is in effect?

### ISSUE THREAD

**Issue by qiujm1996** [apache/shardingsphere#24297]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

version:Sharding-proxy 5.2.0
when I change sharding-proxy configuration parameters in zookeeper,sharding-proxy will take effect with a delay.
As a monitoring system, how can I know when the configuration changed  take effect?

**Comment by RaigorJiang** [comment]
What about query rules with DistSQL?

**Comment by qiujm1996** [comment]
> 

niubillity
