### ISSUE TITLE
How can I do Equivalent query with cipher column?

### ISSUE THREAD

**Issue by wsc20190102** [apache/shardingsphere#24300]
## Question

How can I do Equivalent query with cipher column ?

shardingSphere version is 5.1.0
framework is spring data jpa, use feature projection query

part of sql is :  AND if( :email != '', u.email = :email, 1=1 )
email is the cipher column and my yaml config is ineffective

tables:
          sys_user:
            columns:
              email:
                cipher-column: email
                assisted-query-column: email
                encryptor-name: mysharding-encryptor
              mobile:
                cipher-column: mobile
                encryptor-name: mysharding-encryptor
            query-with-cipher-column: true

**Comment by strongduanmu** [comment]
@tuichenchuxin Can you help check this issue?

**Comment by tuichenchuxin** [comment]
Sure. @wsc20190102 I can't see the sql clearly. Can you optimize the infomation for me to reproduce.

**Comment by wsc20190102** [comment]
i use spring data jpa projection query with the sql, the cipher column email is invalid,  i give right email value,but i get nothing with the result

SELECT
	* 
FROM
	sys_user AS u
	LEFT JOIN sys_ent ON u.id = ent.user_id 
	AND ent.is_deleted = 0 
WHERE
	email = " "

**Comment by wsc20190102** [comment]
@tuichenchuxin

**Comment by tuichenchuxin** [comment]
try this? And open `sql-show` property to show the actual sql.
```sql
SELECT
*
FROM
sys_user AS u
LEFT JOIN sys_ent ON u.id = ent.user_id
AND ent.is_deleted = 0
WHERE
u.email = " "
```

**Comment by wsc20190102** [comment]
sorry，column email is the condition column and cipher column, i just want to query result which equal the email value like "467542@qq.com"
 my config as blow
`rules:
      encrypt: # 加密规则配置
        encryptors:
          mysharding-encryptor:
            type: MYAES # 声明加密处理器的类型
            props:
              aes-key-value: ${teleinfo.snms.file-encrypt-key}
        tables:
          sys_user:
            columns:
              email:
                cipher-column: email
                assisted-query-column: email
                encryptor-name: mysharding-encryptor
              mobile:
                cipher-column: mobile
                encryptor-name: mysharding-encryptor
            query-with-cipher-column: true  # 设置查询是否使用密文列`

**Comment by wsc20190102** [comment]
whether shardingSphere 5.1.0 version can support cipher column query?  thanks  @tuichenchuxin

**Comment by tuichenchuxin** [comment]
> 

I saw cipher-column and assisted-query-column is same : email.
May be you just need cipher-column?
this doc may offer some help.
https://shardingsphere.apache.org/document/5.1.0/cn/user-manual/shardingsphere-jdbc/java-api/rules/encrypt/

**Comment by strongduanmu** [comment]
Long time no response.
