### ISSUE TITLE
Shardingsphere-jdbc configuration mode is zookeeper, metadata is not update

### ISSUE THREAD

**Issue by Python-IBM** [apache/shardingsphere#24317]
## Question

Operation steps:
1. In the spring boot, the mode is configured as ZooKeeper. ZooKeeper generates metadata.
2. Modify the value of sharding-column in the spring configuration to the new value, and restart the spring boot.

Problems encountered:
Zookeeper's metadata/logic_ db/versions/0/rules is still the old value and has not changed to the new value.

**Comment by Pace2Car** [comment]
Hi @Python-IBM , which version of ShardingSphere are you using? If it is a version before 5.2.1, you can overwrite it through the configuration property `overwrite: true`.

After 5.2.1 released, ShardingSphere removed `overwrite` property and set it to `false` by default, it means that already persisted configuration will not be overwritten.

You can use DistSQL to modify the configuration, if it is a test environment, you can manually clear the configuration data  in the governance center.

**Comment by RaigorJiang** [comment]
If you are using ShardingSphere-JDBC, then [mixed deployment](https://shardingsphere.apache.org/document/current/en/overview/#hybrid-architecture) with Proxy is the way recommended by the community. Because in this way, the technical team has mastered the dynamic configuration initiative.

**Comment by Python-IBM** [comment]
> Hi @Python-IBM , which version of ShardingSphere are you using? If it is a version before 5.2.1, you can overwrite it through the configuration property `overwrite: true`.
> 
> After 5.2.1 released, ShardingSphere removed `overwrite` property and set it to `false` by default, it means that already persisted configuration will not be overwritten.
> 
> You can use DistSQL to modify the configuration, if it is a test environment, you can manually clear the configuration data in the governance center.

I use version 5.2.1, and set the attribute "overwrite: true" of mode in the spring configuration, but the zookeeper has not updated the metadata, which is still old. I want to update metadata after the spring boot is restarted, and I don't want to use DistSQL to update.

**Comment by Python-IBM** [comment]
> If you are using ShardingSphere-JDBC, then [mixed deployment](https://shardingsphere.apache.org/document/current/en/overview/#hybrid-architecture) with Proxy is the way recommended by the community. Because in this way, the technical team has mastered the dynamic configuration initiative.

The project is not intended to adopt mixed deployment. shardingsphere-jdbc is suitable for our current oracle database.

**Comment by Pace2Car** [comment]
> I use version 5.2.1, and set the attribute "overwrite: true" of mode in the spring configuration, but the zookeeper has not updated the metadata, which is still old. I want to update metadata after the spring boot is restarted, and I don't want to use DistSQL to update.

So as mentioned before, ShardingSphere 5.2.1 has removed the `overwrite` property, and the metadata does not support overwriting.

**Comment by Python-IBM** [comment]
> > I use version 5.2.1, and set the attribute "overwrite: true" of mode in the spring configuration, but the zookeeper has not updated the metadata, which is still old. I want to update metadata after the spring boot is restarted, and I don't want to use DistSQL to update.
> 
> So as mentioned before, ShardingSphere 5.2.1 has removed the `overwrite` property, and the metadata does not support overwriting.

Ok, Thank you! It is hoped that the later version can also support the coverage of registry metadata through spring attribute configuration.

**Comment by Python-IBM** [comment]
> > I use version 5.2.1, and set the attribute "overwrite: true" of mode in the spring configuration, but the zookeeper has not updated the metadata, which is still old. I want to update metadata after the spring boot is restarted, and I don't want to use DistSQL to update.
> 
> So as mentioned before, ShardingSphere 5.2.1 has removed the `overwrite` property, and the metadata does not support overwriting.

I set "overwrite: true", the metadata updated the rules, but did not update the logical table under the "metadata/logic_db/schemas/logic_db/tables/" directory. I deleted the physical table, restarted the service, and the logical table still exists. What is the reason?

**Comment by Pace2Car** [comment]
> How to solve the above two problems?

Hi @Python-IBM, If you are using ShardingSphere-JDBC with cluster mode, the only way to refresh the db metadata is clear the configuration data in the current governance center, and then restart the service.
> I recommend deploying a `ShardingShere-Proxy` instance to maintain your configuration and metadata.

If the startup is slow due to loading tables, you can try to upgrade the version, which is continuously being optimized.

**Comment by Python-IBM** [comment]
> 

Our project only intends to consider using shardingsphere-jdbc to rely on the jar package. We will not consider the shardingsphere-proxy scheme for the time being. If we need to delete metadata every time, it will be too inconvenient. The "overwrite: true" in the spring configuration will have little effect. Also, upgrade to the latest version. Versions above 5.2.0 do not support "overwrite: true", but these problems still need to be optimized.

**Comment by Pace2Car** [comment]
This does not seem to be a universal scenario. The hybrid architecture is suitable for most users. If you have a good design, you can submit a PR and the community will consider it.

**Comment by Python-IBM** [comment]
OK, I understand. thank you
