### ISSUE TITLE
show tables &&show table status,What is the difference between the two SQL execution processes?

### ISSUE THREAD

**Issue by Hale-CHIOU** [apache/shardingsphere#24314]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

version:sharding-proxy 5.2.0
when I execute "show tables",Sharing-proxy shows me the table I have configured in schemas.
when I execute "show table status",Sharing-proxy shows me the table of all data sources.

So I would like to ask how they differ in the execution process of implementation

**Comment by FlyingZC** [comment]
`show tables` query shardingsphere's own metadata, `show table status` query the first storage node and merge result.
