### ISSUE TITLE
4.1.1 Upgrade to 5.1.1 A large number of union all cause memory problems

### ISSUE THREAD

**Issue by tanpeng2018** [apache/shardingsphere#24335]
The project upgraded the component from 4.1.1 to 5.1.1. The sub-table configuration was correct and the service was started normally. However, a large number of union all table queries occurred during the execution of sql, resulting in sql execution failure. The specific information is as follows:

<img width="1346" alt="WechatIMG2285" src="https://user-images.githubusercontent.com/39759481/221091661-7291cf5b-ffd2-4254-bc30-7fa0f259e11d.png">
As shown in the figure, the original sql is very simple and can also find the unique table according to the table splitting conditions, but the above error is reported. The following is a screenshot of some sql:

<img width="1439" alt="WechatIMG2292" src="https://user-images.githubusercontent.com/39759481/221091678-00fe3577-ee8e-48d8-a2a0-d35c8557a651.png">

**Comment by strongduanmu** [comment]
Can you provide more information? Such as sharding cofiguration and table init sql.

**Comment by tanpeng2018** [comment]
> Can you provide more information? Such as sharding cofiguration and table init sql.

this is some config:

spring.shardingsphere.rules.sharding.tables.order_index.actual-data-nodes=ds0.order_index_$->{0..1023}_20$->{20..40}
spring.shardingsphere.rules.sharding.tables.order_index.table-strategy.complex.sharding-algorithm-name=orderIndexShard
spring.shardingsphere.rules.sharding.tables.order_index.table-strategy.complex.sharding-columns=shard_id,order_id,out_order_id
spring.shardingsphere.rules.sharding.sharding-algorithms.orderindex.type=orderIndexShard
spring.shardingsphere.props.sql-show=false
spring.shardingsphere.props.kernel-executor-size=32
spring.shardingsphere.props.max.max-connections-size-per-query=50

**Comment by tanpeng2018** [comment]
config error
