### ISSUE TITLE
Cipher column didn't consider backslash as an  escape character;

### ISSUE THREAD

**Issue by liyimingcust** [apache/shardingsphere#24333]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Considering sql_mode without  NO_BACKSLASH_ESCAPES,cipher column should escape the backslash before encrypt and store;
### Actual behavior
Cipher column  encrypt the value with backslash;
### Reason analyze (If you can)
Mysql could properly handle backslash as an escape character,SS considers it as plaintext instead;
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
You guys could try sqls like this(make sure that SS's address_json has a cipher column address_json_cipher )
  A : insert into table_a set `address_json` = '{\"full_address\":\"\"}';
  B : insert into table_a set `address_json` = '{"full_address":""}';
if the service side was origin Mysql, address_json should be the same.
But if the service side was SS, address_json are same,address_json_cipher are different;
Comment text escaped the backslash,soI put a pic below
![image](https://user-images.githubusercontent.com/28863292/221494677-be8a8394-dbc5-4323-8158-3a264eb54a2f.png)

**Comment by FlyingZC** [comment]
@liyimingcust hi, can you provide your ShardingSphere config, @tuichenchuxin hi, please have a look.

**Comment by liyimingcust** [comment]
@
schemaName: ***
dataSources:
  ds0:
    url: jdbc:mysql://***:3307/***?serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: erp_qa
    password: ***
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 10
    minPoolSize: 1
rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: ***
  tables:
    applying_consignee:
      columns:
        mobile:
          plainColumn: mobile
          cipherColumn: mobile_cipher
          encryptorName: aes_encryptor
        address_json:
          plainColumn: address_json
          cipherColumn: address_json_cipher
          encryptorName: aes_encryptor
        name:
          plainColumn: name
          cipherColumn: name_cipher
          encryptorName: aes_encryptor
        idcard_num:
          plainColumn: idcard_num
          cipherColumn: idcard_num_cipher
          encryptorName: aes_encryptor

**Comment by terrymanu** [comment]
The version is out of service, please try new version.
