### ISSUE TITLE
4.1.1升级到5.1.1出现大量union all 造成内存问题

### ISSUE THREAD

**Issue by tanpeng2018** [apache/shardingsphere#24334]
The project upgraded the component from 4.1.1 to 5.1.1. The sub-table configuration was correct and the service was started normally. However, a large number of union all table queries occurred during the execution of sql, resulting in sql execution failure. The specific information is as follows:
<img width="1346" alt="WechatIMG2285" src="https://user-images.githubusercontent.com/39759481/221091661-7291cf5b-ffd2-4254-bc30-7fa0f259e11d.png">
As shown in the figure, the original sql is very simple and can also find the unique table according to the table splitting conditions, but the above error is reported. The following is a screenshot of some sql:
<img width="1439" alt="WechatIMG2292" src="https://user-images.githubusercontent.com/39759481/221091678-00fe3577-ee8e-48d8-a2a0-d35c8557a651.png">

**Comment by strongduanmu** [comment]
For English only, other language will not accept.
