### ISSUE TITLE
5.3.1 集成seata全局事务时，如果外围同样存在全局事务时，commit()方法报空异常

### ISSUE THREAD

**Issue by ulwx** [apache/shardingsphere#24331]
```
GlobalTransaction globalTransaction = GlobalTransactionContext.getCurrentOrCreate();
globalTransaction.begin(timeout * 1000);     
TransactionTypeHolder.set(TransactionType.BASE);
try{
    doInsert();
}finally {
    TransactionTypeHolder.clear();
}
globalTransaction.commit();
```
上述代码运行时，doInsert()会抛出null异常，是doInsert()里的commit()方法抛出的，原因是shardingjdbc代理commit()方法时，由于SeataATShardingSphereTransactionManager#begin()方法因为外围存在GlobalTransaction而一直没有执行，导致TransactionTypeHolder#set()没有执行，一直为空，从而在shardingjdbc代理commit()方法执行时通过TransactionTypeHolder#get()查询为空，报null指针异常

**Comment by FlyingZC** [comment]
Please use English and submit an issue according to the template.

**Comment by zhaojinchao95** [comment]
Please translate your issue and create a new issue.
