### ISSUE TITLE
5.3.1 When integrating seata global transactions, if there are also global transactions on the periphery, the commit () method reports a null exception

### ISSUE THREAD

**Issue by ulwx** [apache/shardingsphere#24332]
```
GlobalTransaction globalTransaction = GlobalTransactionContext.getCurrentOrCreate();
globalTransaction.begin(timeout * 1000);     
TransactionTypeHolder.set(TransactionType.BASE);
try{
    doInsert();
}finally {
    TransactionTypeHolder.clear();
}
globalTransaction.commit();
```
When the above code is running, doInsert() will throw a null exception, which is thrown by the commit() method in doInsert(). The reason is that when the shardingjdbc proxy commit() method is used, because the SeataATShardingSphereTransactionManager # begin() method has not been executed because of the existence of GlobalTransaction on the periphery, the TransactionTypeHolder # set() method has not been executed and is always empty, Thus, when the shardingjdbc agent commit() method is executed, the query is null through TransactionTypeHolder # get(), and a null pointer exception is reported！

**Comment by FlyingZC** [comment]
Not support starting the SEATA AT transaction from the outside.ShardingSphere starts the SEATA AT transaction by itself.
