### ISSUE TITLE
a confused problem about default connect pool

### ISSUE THREAD

**Issue by lmx1989219** [apache/shardingsphere#24348]
Standalone mode default run with hikari pool,but i replace with druid even it works fine.
i found the follow code,
`JDBCRepository.java`
````
public void init(final Properties props) {
        JDBCRepositoryProperties jdbcRepositoryProps = new JDBCRepositoryProperties(props);
        hikariDataSource = new HikariDataSource();
        String jdbcUrl = jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.JDBC_URL);
        hikariDataSource.setJdbcUrl(jdbcUrl);
        hikariDataSource.setUsername(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.USERNAME));
        hikariDataSource.setPassword(jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.PASSWORD));
        try (
                Connection connection = hikariDataSource.getConnection();
                Statement statement = connection.createStatement()) {
            provider = TypedSPILoader.getService(JDBCRepositoryProvider.class, jdbcRepositoryProps.getValue(JDBCRepositoryPropertyKey.PROVIDER));
            if (!jdbcUrl.contains(H2_FILE_MODE_KEY)) {
                statement.execute(provider.dropTableSQL());
            }
            statement.execute(provider.createTableSQL());
        }
    }
````

whatever i do the hikari pool both running.
so a problem is coming,my app has two datasource,even though the primary is druid,but i want exclude hikari ,how do i can resolve this sense
thanks!

**Comment by zhaojinchao95** [comment]
@lmx1989219 Hello, your means are according to the configured connection pool, to initialize the data source of standalone mode?

**Comment by lmx1989219** [comment]
> @lmx1989219 Hello, your means are according to the configured connection pool, to initialize the data source of standalone mode?

yes, i only have a confused with standalone mode,of course the cluster mode has no problem.

**Comment by zhaojinchao95** [comment]
> > @lmx1989219 Hello, your means are according to the configured connection pool, to initialize the data source of standalone mode?
> 
> yes, i only have a confused with standalone mode,of course the cluster mode has no problem.

I think it can be optimize here. Are you interested in doing it?

**Comment by lmx1989219** [comment]
> e cluster mode has no problem

okay

**Comment by liming0** [comment]
@zhaojinchao95 I have also noticed this issue. Will this issue be optimized in the new version? Is there a plan already in place？

**Comment by XiFYuW** [comment]
Is there a solution?

**Comment by liming0** [comment]
> it's a implemention mechanism，not a problem，can ignore it
Is this not a problem? At least it can be considered an optimizable point.Isn't that to say that using standalone mode can only use the default hikari, even if other connection pools are configured, they won't be used
