### ISSUE TITLE
Upgrade test framework from JUnit 4 to JUnit 5

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#24350]
I want to upgrade the test framework from JUnit 4 to JUnit 5.

The main changes include:

1. Renaming the imported `Assertions` class.
1. Refactoring `assertXXX(message, xxx)` to `assertXXX(xxx, message)`.
1. Refactoring `@Test(expected = xxx)` to `assertThrows`.
1. Refactoring `@Ignore` to `@Disabled`.
1. Refactoring `@Before`, `@BeforeClass`, `@After`, `@AfterClass` to `@BeforeEach`, `@BeforeAll`, `@AfterEach`, `@AfterEach`.
1. Refactoring `@Parameters` to `@ParameterizedTest` and `@ArgumentsSource`.
1. Refactoring `@ClassRule` and `BlockJUnit4ClassRunner` to `BeforeAllCallback` and `AfterAllCallback`.
1. Refactoring `@RunWith` to `@ExtendWith`.

Since the changes are significant, I plan to upgrade the test cases one by one. Until all the upgrades are completed, JUnit 4.x and JUnit 5.x can coexist.

**Comment by taojintianxia** [comment]
@terrymanu besides `@ArgumentsSource` , there are `@CsvFileSource`、 `@MethodSource`、`@EnumSource` are also useful, please consider that.
