### ISSUE TITLE
[example] Cluster repository missing nacos support.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/shardingsphere#24375]
## Question

Cluster repository missing nacos support in example generator module.

**Comment by FlyingZC** [comment]
@GOODBOY008 Hi, would you want to add the example.@zhaojinchao95 Please have a look.

**Comment by zhaojinchao95** [comment]
@GOODBOY008 Are you interested in add it?

**Comment by zhaojinchao95** [comment]
> @GOODBOY008 Hi, would you want to add the example.@zhaojinchao95 Please have a look.

Sure.

**Comment by GOODBOY008** [comment]
> ## Question
> Cluster repository missing nacos support in example generator module.

I'm willing to take this issue , Please assign to me. Thank you :)

**Comment by GOODBOY008** [comment]
> > @GOODBOY008 Hi, would you want to add the example.@zhaojinchao95 Please have a look.
> 
> Sure.

@zhaojinchao95 I'm willing to take this issue , Please assign to me. Thank you :)

**Comment by zhaojinchao95** [comment]
> 

Welcome
