### ISSUE TITLE
error time_zone while use Instant type to query

### ISSUE THREAD

**Issue by Ikki-Dai** [apache/shardingsphere#24374]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.2 ~ 5.3.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
while use Instant type, it have different value type from mysql sql log

when trans value like '2023-02-10T00:00:00Z' use Instant Type
- use jdbc **without** shardingsphere, print log in mybatis is '2023-02-10 00:00:00.0 (Timestamp)' and actual value '2023-02-10 00:00:00' in mysql (mysql.general_log)

### Actual behavior

- use jdbc **with** shardingsphere, pring log in mybatis and shardingsphere is '2023-02-10 00:00:00.0 (Timestamp' and actual value '2023-02-09 16:00:00' in mysql(mysql.general_log)

### Example codes for reproduce this issue (such as a github link).
- no other parameters effect, i did't set jdbc url parameter, mysql time_zone set, just change `spring.shardingsphere.enebled` to test the same sql

**Comment by FlyingZC** [comment]
Shardingsphere will not modify the date time, can you provide a reproducible demo.

**Comment by Ikki-Dai** [comment]
@FlyingZC 
pls refer https://github.com/Ikki-Dai/shardsphere24374.git for demo

**Comment by FlyingZC** [comment]
[OK]

**Comment by Ikki-Dai** [comment]
`Date` type have same issue

**Comment by FlyingZC** [comment]
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/19788130/223589766-c486bb50-4a2d-407c-ac09-9aad26dcef1a.png">
I tried it, and found that the time displayed in the Mybatis log seems to be wrong, and the code has not yet entered the ShardingSphere.

**Comment by Ikki-Dai** [comment]
have u checked `mysql.general_log`, it have different actual value and result set while use shardingsphere and not
