### ISSUE TITLE
Mybatis does not take effect on batch update of data by table

### ISSUE THREAD

**Issue by Python-IBM** [apache/shardingsphere#24394]
1. Application version
shardingsphere-jdbc：5.2.0
mysql：5.7
mybatis-plus: 3.4.1
Spring Boot: 2.3.12

2. Mybatis xml
![image](https://user-images.githubusercontent.com/33851767/222029064-9dd5bf1c-e6c4-4e91-8def-cca2ee9ddc5b.png)
(1) After the batch update of the foreach loop using the mybatis tag.
(2) Sub-table reg_ bill_ trans_ 01 Data updated successfully. It is divided into table reg_ bill_ trans_ 02 The data was not updated successfully. It is still the old value.

**Comment by RaigorJiang** [comment]
Hi @Python-IBM 
ShardingSphere works according to SQL and rules, and does not care about specific operations in ORM.
Please provide your sharidng rule configuration, Logic SQL and Actual SQL to investigate the issue.

Tip: enable `sql-show` to print out Logic SQL and Actual SQL in the log.

**Comment by Python-IBM** [comment]
> Hi @Python-IBM ShardingSphere works according to SQL and rules, and does not care about specific operations in ORM. Please provide your sharidng rule configuration, Logic SQL and Actual SQL to investigate the issue.
> 
> Tip: enable `sql-show` to print out Logic SQL and Actual SQL in the log.

Ok, I understand. I'll check it again

**Comment by wj0530** [comment]
I also have the same problem, how did you ultimately solve it
