### ISSUE TITLE
Support parsing more functions SQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#24398]
In the process of investigating #24053, I found that there are still many functions that are not supported by the parser engine, and I think we can improve it gradually.

Here are some references:
#### MySQL
- Document: https://dev.mysql.com/doc/refman/8.0/en/functions.html
- PR: #24396

####
- [x] REPEAT https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_repeat
- [x] EXTRACT https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_extract
- [ ] CAST https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
- [ ] Optimize MySQLStatementSQLVisitor#visitCastFunction

**Comment by yx9o** [comment]
I want to try.

**Comment by RaigorJiang** [comment]
> I want to try.

Welcome here!

**Comment by kanha-gupta** [comment]
@RaigorJiang Hey, I have made a PR for Repeat function, I have seen that Extract function & Cast function are present as Special function "select_extract" & "select_cast_function" in the codebase & in the ANTLR4 grammar file as special function as well.
I believe if i add support for it, it might cause duplication so can you please specify ?

**Comment by RaigorJiang** [comment]
@kanha-gupta 
You can find them in `mysql/BaseRule.g4`:
```
extractFunction
     : EXTRACT LP_ identifier FROM expr RP_
     ;
```

```
castFunction
     : CAST LP_ expr AS dataType RP_
     ;
```

**Comment by RaigorJiang** [comment]
Hi @kanha-gupta , thanks for your investigation, for your reference:

- MySQLKeyword.g4
<img width="933" alt="image" src="https://user-images.githubusercontent.com/5668787/224551080-afa85cc9-0b0e-45fa-9e5c-198d4712c450.png">

- BaseRule.g4
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/5668787/224551177-aea512c6-3c97-4d2b-8514-fa56526ea241.png">

```
castFunction
    : CAST LP_ expr AS dataType RP_
    | CAST LP_ expr AT TIME ZONE expr AS DATETIME typeDatetimePrecision? RP_
    ;
```


- Result
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5668787/224551215-147502bb-3125-4e2b-ab5d-11d12d2125e6.png">

**Comment by kanha-gupta** [comment]
@RaigorJiang @strongduanmu Hello, Thanks a lot for guidance. I've completed all 4 tasks.
I request you to assign me other issues of SQL parsing for SELECT statement queries if available.

**Comment by RaigorJiang** [comment]
> @RaigorJiang @strongduanmu Hello, Thanks a lot for guidance. I've completed all 4 tasks. I request you to assign me other issues of SQL parsing for SELECT statement queries if available.

Hi @kanha-gupta 
Are you interested in this issue https://github.com/apache/shardingsphere/issues/21209
