### ISSUE TITLE
sharding-jdbc sql parse mysql json type search grammar ”member of“ casue NoViableAltException

### ISSUE THREAD

**Issue by JLVWJ** [apache/shardingsphere#24424]
0.sharding-jdbc version:5.2.1
1.mysql sql:
 where lc.app_id = #{param.appId}
      and lc.is_deleted = -1
      and lc.status = -1
      and #{param.platformId} member of(lc.match_json -> '$') 
      and json_contains(lc.match_json -> '$', CAST(#{param.deliveryType} AS JSON))
      and lc.direction = #{param.direction}
      and fti.country_code = #{param.countryCode}
      and (fti.charge_method = 1 or JSON_OVERLAPS(ftig.group_item -> '$', CAST(#{param.groupItem} AS JSON)));

![image](https://user-images.githubusercontent.com/25194557/222400909-d05509ab-1609-499b-98cc-3e8687a5f806.png)
![ea1094c1-71f8-45f5-a737-1ffe3cfe6909](https://user-images.githubusercontent.com/25194557/222401003-76903604-c487-49b7-b613-f70a43928683.jpeg)

**Comment by avalon5666** [comment]
let me try
