### ISSUE TITLE
I am integrating opentelemetry, would like to ask how to achieve observability in shardingsphere 5 JDBC

### ISSUE THREAD

**Issue by freshchen** [apache/shardingsphere#24438]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by FlyingZC** [comment]
@RaigorJiang Hi,please have a look.

**Comment by RaigorJiang** [comment]
Hi @freshchen @FlyingZC 
I think @jiangML can help us, please wait for his comment.

**Comment by freshchen** [comment]
Thanks for the quick feedback, I am trying to add a real SQL span to tracking system, i find old sharding jdbc based on eventbus + opentracing, but I can’t find it in shardingsphere jdbc 5

**Comment by freshchen** [comment]
I find a extension point SPISQLExecutionHook, whether this SPI can cover all scenarios

**Comment by jiangML** [comment]
@freshchen Hi, training under `ShardingSphere-JDBC` is not yet supported
