### ISSUE TITLE
A BUG about shardingsphere-proxy5.3.1

### ISSUE THREAD

**Issue by ICALLYOU** [apache/shardingsphere#24435]
When using navicat for query, the old version navvicat data display incomplete, the new version navicats connection error
the old version navicat:
![图片](https://user-images.githubusercontent.com/48971995/222626401-8c732998-57a0-4fc0-a734-8c3af5037148.png)
the new version navicat:
![图片](https://user-images.githubusercontent.com/48971995/222626813-7ece7ce4-a164-457d-8325-b3ca8ba50a46.png)
![图片](https://user-images.githubusercontent.com/48971995/222626772-0825e757-84f4-46b0-8b1b-a0a73345664c.png)
![图片](https://user-images.githubusercontent.com/48971995/222626895-ec70888f-aaad-4f7e-9d09-d89a8c91e053.png)

**Comment by RaigorJiang** [comment]
It is recommended to use DBeaver, Navicat is not an open source software.

**Comment by RaigorJiang** [comment]
After changing the client, you will find that the data is correct, so this is not a problem with ShardingSphere.
