### ISSUE TITLE
sharding order by npe

### ISSUE THREAD

**Issue by wanghongzhou2626** [apache/shardingsphere#24432]
Question
Using sharding to split tables across months using order by resulted in npe
version：5.2.1
<img width="871" alt="截屏2023-03-03 01 14 52" src="https://user-images.githubusercontent.com/38241680/222503556-61acfb00-0a51-4247-abd3-43993bde459b.png">

EachSimpleTableSegment does not contain the sub-table month I want, which leads to the failure of sorting according to order by after merging，The field of order by is create_time
please help me

**Comment by strongduanmu** [comment]
@wanghongzhou2626 Can you provide your sharding configuration and sql?

**Comment by wanghongzhou2626** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/38241680/222623845-159825d4-1ab0-4131-acfe-5e1b75bfe585.png">
      check-table-metadata-enabled: false

**Comment by wanghongzhou2626** [comment]
<img width="891" alt="截屏2023-03-03 12 57 59" src="https://user-images.githubusercontent.com/38241680/222635213-2a51345c-9fc8-4896-addb-5a5523eb7520.png">
check-table-metadata-enabled: false will not add logical tables when the project is started. For example, the current total number of tables is 600, and the method through the picture will reduce a few logical tables, which will lead to subsequent order by merge engine table lookup The table corresponding to the name generates npe

**Comment by FlyingZC** [comment]
Are you operating on a logical table, this place is to load the metadata of the table, and the metadata of each table of the sharded table should be the same.

**Comment by wanghongzhou2626** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/38241680/223017091-a463ef19-e7eb-4d13-b7cc-552bd18b28a7.png">
I have found the cause of the problem
The above is the configuration of my sub-table
When starting a project to obtain metadata, first find out if there is a logical table for the month of 202201, and if so, add it to the table collection. So the npe that results in the subsequent query
If I turn on the configuration check-table-metadata-enabled:true, I don’t need to consider this issue. How does this consume performance? Or how should my goovc expression be written? For example, I started in 2022 but I don't know the end year.

**Comment by FlyingZC** [comment]
Please provide your config,`check-table-metadata-enabled:true` will load all the will load the table structure of all actual tables for verification when starting ShardingSphere and updating the table structure,.You can configure the end time until 2050.

**Comment by wanghongzhou2626** [comment]
> 请提供您的配置，`check-table-metadata-enabled:true`将加载所有将加载所有实际表的表结构以在启动ShardingSphere 和更新表结构时进行验证，您可以配置结束时间到2050 年。

<img width="1091" alt="截屏2023-03-06 12 03 56" src="https://user-images.githubusercontent.com/38241680/223300665-5d5535f9-d0ef-4572-8a38-e554cbbdb2dd.png">
If the launch date of a certain project is 202203 and the end date is unknown, how should I configure it? Will the end date 2050 you mentioned consume performance?

**Comment by wanghongzhou2626** [comment]
Can I dynamically control the sub-table by month

**Comment by RaigorJiang** [comment]
> Can I dynamically control the sub-table by month

DistSQL can help user to alter sharding table rules.
