### ISSUE TITLE
[doc] Add springboot integrate with shardingsphere jdbc migration doc from 5.2.0 and older version to lastest version.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/shardingsphere#24449]
## Question

Because of big change in 5.3.0 when springboot integrate with shardingsphere, I think a migration guide document will be very helpful for developers.

**Comment by GOODBOY008** [comment]
@terrymanu Please have a look.

**Comment by FlyingZC** [comment]
ShardingSphere documentation has configuration documents for each version, and ShardingSphere will provide upgrade tools in the future.

**Comment by FlyingZC** [comment]
ShardingSphere documentation has configuration documents for each version, and ShardingSphere will provide upgrade tools in the future.

**Comment by zhaojinchao95** [comment]
By the way,` springboot-starter` module are removed. use `ShardingSphereDriver` later.
