### ISSUE TITLE
Can you provide a complete and enabled demo, each demo corresponds to its own version

### ISSUE THREAD

**Issue by jdAction** [apache/shardingsphere#24458]
Can you provide a complete and enabled demo, each demo corresponds to its own version
The example given by the official documentation has been wrong. Since you want to release a new version, integrate the springboot demo by the way.

**Comment by zhaojinchao95** [comment]
> Can you provide a complete and enabled demo, each demo corresponds to its own version The example given by the official documentation has been wrong. Since you want to release a new version, integrate the springboot demo by the way.

Hi, `springboot-starter` module are removed. You can use `ShardingSphereDriver`.

**Comment by RaigorJiang** [comment]
Please refer to the example module, there are always examples of spring boot.
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-example-generator

**Comment by RaigorJiang** [comment]
> Can you provide a complete and enabled demo, each demo corresponds to its own version The example given by the official documentation has been wrong. Since you want to release a new version, integrate the springboot demo by the way.

Can you point out which part of the documentation is wrong?
