### ISSUE TITLE
The for loop under batch update only modifies the table name of the first statement

### ISSUE THREAD

**Issue by guoxk2** [apache/shardingsphere#24473]
Which version of ShardingSphere did you use?
5.1.2

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
replace all table names

Actual behavior
Only the table name of the first cycle is replaced

![image](https://user-images.githubusercontent.com/40156524/223065410-ea06d5c2-fa8e-4bd4-8c9c-1cb0558fad25.png)

running results：
![image](https://user-images.githubusercontent.com/40156524/223066443-0d979f43-33bb-4e9d-b82b-3d16c1faf543.png)

How to replace all table names in the loop?

**Comment by azexcy** [comment]
Thanks for feedback, the `5.1.2` version is outdated, can you try the latest version?

**Comment by guoxk2** [comment]
> Thanks for feedback, the `5.1.2` version is outdated, can you try the latest version?

After changing to version `5.3.1`, the problem no longer appears, thank you

**Comment by twitchob** [comment]
If possible, could you please close this issue?

**Comment by RaigorJiang** [comment]
> After changing to version `5.3.1`, the problem no longer appears, thank you

Great!  thanks for your feedback.

**Comment by gufeng710** [comment]
Hello, I'm having the same problem.  with using org.apache.shardingsphere:shardingsphere-jdbc-core:5.3.1, The problem still exists. Can you help me

**Comment by 6westboy9** [comment]
Hello, I'm having the same problem. with using org.apache.shardingsphere:shardingsphere-jdbc-core:5.4.1, The problem still exists. Can you help me

**Comment by strongduanmu** [comment]
Hi @6westboy9, ShardingSphere doesn't support multi statement execute.
