### ISSUE TITLE
Mbatis-plus Page 

### ISSUE THREAD

**Issue by bitbxj** [apache/shardingsphere#24475]
Hello！
My application use Springboot and mybatis-plus. ShardingSphere be import  for sharding table，The original page interface does not work properly . it report  "Not supported token 'WITH'" in console. I look up many website,but not find about the question,how can i solve it? thank for your support!

**Comment by azexcy** [comment]
It is difficult to understand the cause from the above description, maybe it's not ShardingSphere problem

**Comment by bitbxj** [comment]
> It is difficult to understand the cause from the above description, maybe it's not ShardingSphere problem

thanks for your reply ! my application's sql cause ,such as：“WITH selectTemp AS (SELECT TOP 100 PERCENT  ROW_NUMBER() OVER (ORDER BY vs.id DESC) as __row_number__,  vs.* .......) SELECT * FROM selectTemp WHERE __row_number__ BETWEEN 1 AND 10 ORDER BY __row_number__", application can  run nomally without inporting shardingsphere.   The sql is create automatically by mybatis-plus . if  want to application run nomally without to modify sql,coulde you provide any way to solve it!?

**Comment by azexcy** [comment]
Maybe you can debug it and try, I used to do something similar and they could work together or you can upgrade `ShardingSphere-JDBC` version and try again.

**Comment by bitbxj** [comment]
I want to sharding the table with the table's field value, such as has a table include project field,which's type is string, when row data is inserted into the table,  which‘s name is Automatically added "_&{code}"！

**Comment by HarleyCheng2023** [comment]
> Maybe you can debug it and try, I used to do something similar and they could work together or you can upgrade `ShardingSphere-JDBC` version and try again.

what is your shardingSphere-jdbc version?
