### ISSUE TITLE
The shardingsphere-jdbc 3.* URL does not support multiple IP addresses.

### ISSUE THREAD

**Issue by itudo** [apache/shardingsphere#24481]
Background:

springboot version: 2.7.2
orm: mybatis-plus 3.5.1
ShardingSphere-JDBC：3.*

error message:
`exception is io.shardingsphere.core.exception.ShardingException: The URL of JDBC is not supported.  please refer to this pattern: jdbc:postgresql://([\w\-\.]+):?([0-9*])/([\w\-]+)`

We hope that the single IP address restriction can be removed.

**Comment by strongduanmu** [comment]
`ShardingSphere-JDBC：3.*` is too old, please upgrade to the latest version.

**Comment by wangzhijun1124** [comment]
> `ShardingSphere-JDBC：3.*` is too old, please upgrade to the latest version.

**Comment by wangzhijun1124** [comment]
But shardingsphere 5 is not backward compatible, is it? If the application is upgraded from 3 to 5, a lot of reconstruction and verification will be required.

**Comment by sandynz** [comment]
Hi @wangzhijun1124 , you could try to update version 3 source code by yourself, and upload packaged jar to own Maven repository.
