### ISSUE TITLE
FOR shardingsphere5.3 dynamic config suggestion

### ISSUE THREAD

**Issue by hyz1994121** [apache/shardingsphere#24498]
In my project i try upgrade shardingsphere from 5.1.1 to 5.3
i use shardingshpere jdbc by spring-namespace
after read this, https://community.sphere-ex.com/t/topic/1284 finished my upgrade
then i found some problem, in sharding.yaml i must use the real jdbcurl for datasource config 
before, in my project ,we use ${jdbc.url} by apollo config to distinguish different environment，ex qa, ol

i found to build spring bean org.springframework.jdbc.datasource.SimpleDriverDataSource , i could set username, password by apollo config, but the url must use jdbc:shardingsphere:classpath:sharding.yaml like this,
to use prefix jdbc:shardingsphere:

though i could not use the dynamic config to distinguish the different enviroment.
in different env i must make 2 yaml file, it's very uncomfortable.

**Comment by hyz1994121** [comment]
is anyone can help me?

**Comment by zhaojinchao95** [comment]
@hyz1994121 You can look this : https://github.com/apache/shardingsphere/issues/23388

**Comment by liming0** [comment]
I also encountered this issue when using nacos. sharding.yaml cannot reference the values of the configuration files in nacos

**Comment by 794086163** [comment]
> 置

+1

**Comment by hyz1994121** [comment]
> I also encountered this issue when using nacos. sharding.yaml cannot reference the values of the configuration files in nacos

sharding现在感觉越做越脱离用户了感觉，搞的新东西完全摒弃原有的，并不兼容，低版本的bug也不修复fix，到高版本直接跨越式的升级，搞的我们在低版本和高版本之间还得手动在应用中重写来修复bug，有点蛋疼

**Comment by liming0** [comment]
> > I also encountered this issue when using nacos. sharding.yaml cannot reference the values of the configuration files in nacos
> 
> sharding现在感觉越做越脱离用户了感觉，搞的新东西完全摒弃原有的，并不兼容，低版本的bug也不修复fix，到高版本直接跨越式的升级，搞的我们在低版本和高版本之间还得手动在应用中重写来修复bug，有点蛋疼

Yes, the main issue is that there is still no smooth transition plan, but fortunately, SPI was provided. I implemented the configuration loading of NACOS myself and also replaced the values referenced by Spring's ${}

**Comment by strongduanmu** [comment]
@liming0 Can you contribute your implement to upstream to help more users?

**Comment by strongduanmu** [comment]
The Nacos implementation comes from some community contributors, so it is not perfect now, and we hope that more developers will improve it so that it has a chance to become more stable.

**Comment by liming0** [comment]
> @liming0 Can you contribute your implement to upstream to help more users?

Yes, I have removed the part about spring from my code. How can I contribute the code next

**Comment by strongduanmu** [comment]
Hi @liming0, you can submit a new issue to describe your modify, and then we could discuss in this issue.

**Comment by liming0** [comment]
> Hi @liming0, you can submit a new issue to describe your modify, and then we could discuss in this issue.

[Sharding-jdbc supports nacos configuration](https://github.com/apache/shardingsphere/issues/25445)
@strongduanmu

**Comment by linghengqian** [comment]
- Now at https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/ , there are at least 4 SPI implementation to dynamically define YAML attribute values.
- Refer to 
  - #29909
  - #29907
  - #29995
  - https://github.com/apache/shardingsphere-plugin?tab=readme-ov-file#jdbc-driver-config-plugin
