### ISSUE TITLE
MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm is not work

### ISSUE THREAD

**Issue by yangyu4143** [apache/shardingsphere#24507]
shardingshere-jdbc-5.1.2
mysql-version:8.0.27
database:salve_0,salve_1 CHANGE MASTER TO MASTER_DELAY = 60
Query 3 times,then 2 times is failed and 1 time is succeed after I inert one sql.
I found the breakpoint of MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm.loadReplicaStatus is not step into.

![微信图片_20230308224133](https://user-images.githubusercontent.com/127313227/223754605-1dfdd23f-1935-424d-afe1-523b5f7cf2d0.jpg)

![微信图片_20230308230414](https://user-images.githubusercontent.com/127313227/223754701-d6d7ec01-b834-4cfd-b3d2-e408bff82034.png)

**Comment by azexcy** [comment]
The `5.1.2` version is outdated, please try the latest version firstly?

**Comment by zhaojinchao95** [comment]
@yangyu4143 Hi, `5.1.2` version not support delay disabled replica data source function. you can upgrade your `ShardingSphere` version and try it again.
