### ISSUE TITLE
Slow execution of DistSQL RDL

### ISSUE THREAD

**Issue by Huletian** [apache/shardingsphere#24511]
## 	DistSQL is slow

version:5.1.1 

I will be very slow when executing sql .The sql is as follows 
`

add resource ds_xuexiao1 (
	host=localhost,
	port=3306,
	db=xuexiao1,
	user=root,
	password=123456
);

	ALTER sharding TABLE rule ed_school (
	datanodes ( "ds_${['xuexiao1','xuexiao2', 'xuexiao3']}.ed_school" ),
	database_strategy (
		type = standard,
		sharding_column = school_code,
		sharding_algorithm (
			TYPE (
				NAME = inline,
			PROPERTIES ( "algorithm-expression" = "ds_${school_code}" )))) 
);
`

**Comment by RaigorJiang** [comment]
@Huletian 
Thanks for your feedback.
Executing DistSQL will cause metadata refresh. If you have a large number of rules or tables, it will consume much time.
Are there many rules in your logic database?

**Comment by Huletian** [comment]
> @Huletian Thanks for your feedback. Executing DistSQL will cause metadata refresh. If you have a large number of rules or tables, it will consume much time. Are there many rules in your logic database?

Well, I do have a lot of rules and tables

**Comment by RaigorJiang** [comment]
@Huletian 
Ok, I heard that some contributors are designing solutions to optimize metadata refresh, looking forward to starting soon.

**Comment by RaigorJiang** [comment]
This problem will be improved in the future, there are already many similar issues, so I close this one.
