### ISSUE TITLE
How to disable seata?

### ISSUE THREAD

**Issue by longkaimao** [apache/shardingsphere#24569]
## Question

How do I disable seata using configuration?
The following is my configuration：
`sharding {
  transaction.seata.at.enable = false
}`

But,when i call the transaction method,it report the following error：
Caused by: java.lang.IllegalStateException: sharding seata-at transaction has been disabled.

thanks!

**Comment by FlyingZC** [comment]
Change your transaction configuration to xa or local, and please submit an issue according to the template.
