### ISSUE TITLE
how to change the final execute sql like content

### ISSUE THREAD

**Issue by mandone** [apache/shardingsphere#24572]
## Question

this is my sql before route

```sql
select day_value as id_date, avg(success_count) as success, avg(failed_count) as fail
from t_sdk_stat_count_xxx_sdk_202301 
where sdk_code = 'xxx_sdk'
  and day_value >= '20221201'
  and day_value <= '20230301'
  and month_value >= '202212'
  and month_value <= '202303'
group by day_value;
```

sdk_code and month_value column is my sharding rule columns like under config

```sql
<sharding:complex-strategy id="complexStrategy" sharding-columns="sdk_code,month_value" algorithm-ref="complexShardingAlgorithm"/>
```

due to my shard table with month_value  and sdk_code,the final sql needn't  sdk_code = 'xxx_sdk' and  and month_value >= '202212' and month_value <= '202303';
so I want to remve these two conditions。
I read the source code, didn't find any hook meet this demand

**Comment by sandynz** [comment]
Hi @mandone , sorry, what's your expected result?

**Comment by mandone** [comment]
this is my sql before route

```sql
select day_value as id_date, avg(success_count) as success, avg(failed_count) as fail
from t_sdk_stat_count_xxxt_sdk_202301
where sdk_code = 'xxx_sdk'
  and day_value >= '20221201'
  and day_value <= '20230301'
  and month_value >= '202212'
  and month_value <= '202303'
group by day_value;
```

I want change my finally execute sql to 

```sql
select day_value as id_date, avg(success_count) as success, avg(failed_count) as fail
from t_sdk_stat_count_xxx_sdk_202301 
where day_value >= '20221201'
  and day_value <= '20230301'
group by day_value;
```
maybe execute faster

**Comment by sandynz** [comment]
1, Since `sharding-columns="sdk_code,month_value"` is configured, it's better to put sharding columns `sdk_code` and `month_value` in SQL condition, else it'll be routed to all database shard, it might lead to worse performance.

2, What about just update the original SQL condition? (It's not recommended to remove sharding columns, but you could try to test it)

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
