### ISSUE TITLE
Get a simplest dependency for sharding feature

### ISSUE THREAD

**Issue by liuxianqiang** [apache/shardingsphere#24590]
## Feature Request
I just want to add sharding feature in my application. so i add following "shardingsphere-jdbc-core" dependency in pom.xml
But i find shardingsphere-jdbc-core has too many transitive dependency.
how can i get a simplest dependency ? 
i tried "shardingsphere-sharding-core", but it not work.

`<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
    <version>5.3.1</version>
</dependency>
`

### Is your feature request related to a problem?
NO

### Describe the feature you would like.
simplest dependency to get sharding feature.
modular design, simpliest dependency

**Comment by sandynz** [comment]
Hi @liuxianqiang , if you're running ShardingSphere-JDBC, then `shardingsphere-jdbc-core` is required. And you could try [ShardingSphere-Proxy]( https://shardingsphere.apache.org/document/5.3.1/en/quick-start/shardingsphere-proxy-quick-start/ )
