### ISSUE TITLE
Avoid GitHub Actions stuck too long in step actions/cache

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#24604]
## GitHub Actions

Some cache restore actions stuck for 10 minutes, which caused jobs failure.

Introduce `SEGMENT_DOWNLOAD_TIMEOUT_MINS` ENV and set timeout to 1 min.

https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cache-segment-restore-timeout

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/20503072/225185810-680b0e91-3aa8-41f5-9cb9-eec5dbc23fd6.png">

**Comment by sudip-unb** [comment]
I am interested to work on this issue.

**Comment by TeslaCN** [comment]
@sudip-unb Welcome

**Comment by sudip-unb** [comment]
Hi @TeslaCN I checked the link you have provided and I think it is a settings update and it needs admin access. Following I found here - https://docs.github.com/en/actions/learn-github-actions/variables
`To create secrets or variables for a personal account repository, you must be the repository owner. To create secrets or variables for an organization repository, you must have admin access.`

**Comment by TeslaCN** [comment]
Hi @sudip-unb 
Have you met any problem?

**Comment by sudip-unb** [comment]
Hi @TeslaCN 
I was busy with my midterm. I will raise the PR soon.

**Comment by TeslaCN** [comment]
Hi @sudip-unb 
Any update here?
