### ISSUE TITLE
Why do you traverse fields multiple times when finding the partition key

### ISSUE THREAD

**Issue by 374639131** [apache/shardingsphere#24613]
version：
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
    <version>5.3.0</version>
</dependency>

![lhc](https://user-images.githubusercontent.com/52057252/225210121-16b709a2-873a-4e88-9e7b-d89db3f7f45a.png)
![lhc2](https://user-images.githubusercontent.com/52057252/225210145-770b2ccb-840a-41fe-9088-849c044f841e.png)

my sql is "insert into xxx  values (),(),(),()"

As shown in the figure, Why do you need to traverse the column multiple times instead of just once? Get the index in the column set, and then value the value of the set according to the index

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated and removed in 5.3.0, please try new version and use ShardingSphere Driver.
