### ISSUE TITLE
sql rewrite issue

### ISSUE THREAD

**Issue by chinaxlt** [apache/shardingsphere#24618]
origin sql ->
select distinct id from (select distinct id from table_a where id = 1 union all select distinct id from table_b where id = 1) as tem

rewrite sql ->
select distinct id from (select distinct id from table_a_01 where id = 1 union all select distinct id from table_b_01 ORDER BY id ASC  where id = 1) as tem
 
ORDER BY id ASC cause an error in the rewrite SQL

**Comment by strongduanmu** [comment]
Hi @chinaxlt, thank you for your feedback. Currently, the ShardingSphere does not support subqueries, so you need to make some changes to the logical SQL.
