### ISSUE TITLE
About Seata transaction

### ISSUE THREAD

**Issue by longkaimao** [apache/shardingsphere#24649]
## Question
ShardingSphere version：5.3.1

I am using the transaction of base,I configure the annotation '@ShardingSphereTransactionType(value = TransactionType.BASE)' at my global transaction code.
I want to know whether it is required to add the annotation '@ShardingSphereTransactionType(value = TransactionType.BASE)' at other branch transactions code.

Thanks!

**Comment by sandynz** [comment]
Hi @FlyingZC , could you help to have a look at it?

**Comment by longkaimao** [comment]
I found  ‘@ShardingSphereTransactionType’ is no longer used in version 5.3.1,and there is a global configure which is ‘  - !TRANSACTION defaultType: LOCAL providerType: Seata’, if I need to specify it in the business, I have to write code: TransactionTypeHolder.  Set (TransactionType.  Base);

Do I have to add this code to every branch transaction?

**Comment by FlyingZC** [comment]
If you use base transaction, you can configure it in yaml:
```yaml
  - !TRANSACTION
    defaultType: BASE
    providerType: Seata
```

**Comment by FlyingZC** [comment]
Closed due to no reply.
