### ISSUE TITLE
The generated sql contains ShardingInsertValuesToken

### ISSUE THREAD

**Issue by Cyoking** [apache/shardingsphere#24659]
## Question
The shardingSphere I use is version 5.1.1

The following is my mybatis sql
```xml
<insert id="test">
        INSERT INTO test
        (v_uuid, company_id, hash_id, store_id, msku, stock_90_list)
        VALUES
        <foreach collection="tList" item="item" index="index" separator=",">
            (
                #{item.vUuid},
                #{item.companyId},
                #{item.hashId},
                #{item.storeId},
                #{item.msku},
                #{item.stock90List}
            )
        </foreach>
        ON DUPLICATE KEY UPDATE
        company_id  = values(company_id),
        stock_90_list=values(stock_90_list)
</insert>
```
Below is the value of parsing sql in ParseInfo
![image](https://user-images.githubusercontent.com/41101749/225798897-521a4fdd-8f7a-42f6-acb5-cb7cfb818bcf.png)

This will result in an error：
Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: -52

**Comment by darren-wang** [comment]
has this problem been solved? I met this problem too.

**Comment by strongduanmu** [comment]
@darren-wang Can you sumbit new issue to report this exception?
