### ISSUE TITLE
ERROR org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask - Exception occur:   。How do I deal with this?

### ISSUE THREAD

**Issue by saeipi** [apache/shardingsphere#24663]
lark-shardingsphere-proxy-01  | +--------+-------------------------------------------------+----------------+
lark-shardingsphere-proxy-01  | |00000000| 63 00 00 00 03 53 45 4c 45 43 54 20 51 55 45 52 |c....SELECT QUER|
lark-shardingsphere-proxy-01  | |00000010| 59 5f 49 44 2c 20 53 55 4d 28 44 55 52 41 54 49 |Y_ID, SUM(DURATI|
lark-shardingsphere-proxy-01  | |00000020| 4f 4e 29 20 41 53 20 53 55 4d 5f 44 55 52 41 54 |ON) AS SUM_DURAT|
lark-shardingsphere-proxy-01  | |00000030| 49 4f 4e 20 46 52 4f 4d 20 49 4e 46 4f 52 4d 41 |ION FROM INFORMA|
lark-shardingsphere-proxy-01  | |00000040| 54 49 4f 4e 5f 53 43 48 45 4d 41 2e 50 52 4f 46 |TION_SCHEMA.PROF|
lark-shardingsphere-proxy-01  | |00000050| 49 4c 49 4e 47 20 47 52 4f 55 50 20 42 59 20 51 |ILING GROUP BY Q|
lark-shardingsphere-proxy-01  | |00000060| 55 45 52 59 5f 49 44                            |UERY_ID         |
lark-shardingsphere-proxy-01  | +--------+-------------------------------------------------+----------------+
lark-shardingsphere-proxy-01  | 05:40:12.735 [Connection-1-ThreadExecutor] DEBUG org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID)
lark-shardingsphere-proxy-01  | 05:40:12.739 [Connection-1-ThreadExecutor] ERROR org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask - Exception occur: 
lark-shardingsphere-proxy-01  | java.lang.NullPointerException: Cannot invoke "org.apache.shardingsphere.sqlfederation.optimizer.context.parser.OptimizerParserContext.getDialectProps()" because "parserContext" is null
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.sqlfederation.advanced.AdvancedSQLFederationExecutor.execute(AdvancedSQLFederationExecutor.java:140)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.sqlfederation.advanced.AdvancedSQLFederationExecutor.executeQuery(AdvancedSQLFederationExecutor.java:115)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.doExecuteFederation(JDBCDatabaseCommunicationEngine.java:163)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:121)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:94)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
lark-shardingsphere-proxy-01  |         at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
lark-shardingsphere-proxy-01  |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
lark-shardingsphere-proxy-01  |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
lark-shardingsphere-proxy-01  |         at java.base/java.lang.Thread.run(Thread.java:833)
lark-shardingsphere-proxy-01  | 05:40:12.740 [epollEventLoopGroup-3-1] DEBUG org.apache.shardingsphere.db.protocol.codec.PacketCodec - Write to client 6d7fe1db :
lark-shardingsphere-proxy-01  |          +-------------------------------------------------+
lark-shardingsphere-proxy-01  |          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
lark-shardingsphere-proxy-01  | +--------+-------------------------------------------------+----------------+
lark-shardingsphere-proxy-01  | |00000000| b5 00 00 01 ff 30 75 23 48 59 30 30 30 55 6e 6b |.....0u#HY000Unk|
lark-shardingsphere-proxy-01  | |00000010| 6e 6f 77 6e 20 65 78 63 65 70 74 69 6f 6e 3a 20 |nown exception: |
lark-shardingsphere-proxy-01  | |00000020| 43 61 6e 6e 6f 74 20 69 6e 76 6f 6b 65 20 22 6f |Cannot invoke "o|
lark-shardingsphere-proxy-01  | |00000030| 72 67 2e 61 70 61 63 68 65 2e 73 68 61 72 64 69 |rg.apache.shardi|
lark-shardingsphere-proxy-01  | |00000040| 6e 67 73 70 68 65 72 65 2e 73 71 6c 66 65 64 65 |ngsphere.sqlfede|
lark-shardingsphere-proxy-01  | |00000050| 72 61 74 69 6f 6e 2e 6f 70 74 69 6d 69 7a 65 72 |ration.optimizer|
lark-shardingsphere-proxy-01  | |00000060| 2e 63 6f 6e 74 65 78 74 2e 70 61 72 73 65 72 2e |.context.parser.|
lark-shardingsphere-proxy-01  | |00000070| 4f 70 74 69 6d 69 7a 65 72 50 61 72 73 65 72 43 |OptimizerParserC|
lark-shardingsphere-proxy-01  | |00000080| 6f 6e 74 65 78 74 2e 67 65 74 44 69 61 6c 65 63 |ontext.getDialec|
lark-shardingsphere-proxy-01  | |00000090| 74 50 72 6f 70 73 28 29 22 20 62 65 63 61 75 73 |tProps()" becaus|
lark-shardingsphere-proxy-01  | |000000a0| 65 20 22 70 61 72 73 65 72 43 6f 6e 74 65 78 74 |e "parserContext|
lark-shardingsphere-proxy-01  | |000000b0| 22 20 69 73 20 6e 75 6c 6c                      |" is null       |
lark-shardingsphere-proxy-01  | +--------+-------------------------------------------------+----------------+

**Comment by sandynz** [comment]
Hi @saeipi , `INFORMATION_SCHEMA.PROFILING` is not ready completely.

#24662 is the roadmap to improve INFORMATION_SCHEMA
