### ISSUE TITLE
Stuck when querying data

### ISSUE THREAD

**Issue by 294794668** [apache/shardingsphere#24664]
when i use mysql:mysql-connector-java:8.0.32,I can't get data from database and keep waiting.
until I changed to another version mysql:mysql-connector-java:8.0.28.
the shardingsphere version is org.apache.shardingsphere:shardingsphere-jdbc-core:5.3.1

**Comment by 294794668** [comment]
when I only use HikariDataSource without sharding-jdbc and the mysql version is mysql:mysql-connector-java:8.0.32.
it is okay.

**Comment by sandynz** [comment]
Hi @294794668 , could you try to get related Java threads stack? I don't know what is thread waiting on.

And it's better to submit issue with defined template. If you could supply a demo to reproduce it, it's appreciated.
