### ISSUE TITLE
no viable alternative at input 'REGISTER'

### ISSUE THREAD

**Issue by FjcD** [apache/shardingsphere#24680]
### Which version of ShardingSphere did you use?
apache-shardingsphere-5.3.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
REGISTER STORAGE UNIT
### Actual behavior
 no viable alternative at input 'REGISTER' at line 1
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
REGISTER STORAGE UNIT ds_0 (
    URL="jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false"
    USER="root",
    PASSWORD="root"
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="30000")
),ds_1 (
    URL="jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false"
    USER="root",
    PASSWORD="root"
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="30000")
);

**Comment by FjcD** [comment]
😿

**Comment by FjcD** [comment]
🆘

**Comment by RaigorJiang** [comment]
@FjcD 
Your URL and PASSWORD lines are missing commas.

**Comment by FjcD** [comment]
Thank you very much
