### ISSUE TITLE
Refactor YamlLoggingRuleConfigurationSwapper to add getDefaultLoggingRuleConfiguration 

### ISSUE THREAD

**Issue by zhfeng** [apache/shardingsphere#24728]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
It is simiar with #24727 and related to logback. I need to re-write `DefaultLoggingRuleConfiguration` in native building.

### Describe the feature you would like.
Add `getDefaultLoggingRuleConfiguration` in `YamlLoggingRuleConfigurationSwapper` like
```java
private LoggingRuleConfiguration getDefaultLoggingRuleConfiguration() {
    return new DefaultLoggingRuleConfigurationBuilder().build();
}
```
and change https://github.com/apache/shardingsphere/blob/dd16be872a0f24d24e147c58041f7f92a34879d9/kernel/logging/core/src/main/java/org/apache/shardingsphere/logging/yaml/swapper/YamlLoggingRuleConfigurationSwapper.java#L45-L47 with

```java
if (null == result.getLoggers()) { 
    result = getDefaultLoggingRuleConfiguration();
}
```

**Comment by RaigorJiang** [comment]
Hi @zhfeng 
It seems that it just extracts a call into an independent method. 
What is the difference between these two ways for native building?

**Comment by zhfeng** [comment]
@RaigorJiang yeah, I can use `@Substitute` in GraalVM and it could re-write these codes during the native building. Because I need to exclude `ch.qos.logback`, there are some issue with `DefaultLoggingRuleConfigurationBuilder` during the static analysis.

```java
@TargetClass(YamlLoggingRuleConfigurationSwapper.class)
final class YamlLoggingRuleConfigurationSwapperSubstitution {
    @Substitute
    private LoggingRuleConfiguration getDefaultLoggingRuleConfiguration() {
        return new JBossLoggingRuleConfigurationBuilder().build();
    }
}
```
Then it only impacts the native image.

**Comment by RaigorJiang** [comment]
@zhfeng OK, thanks for your answer.
