### ISSUE TITLE
Create JDBC Connection failed

### ISSUE THREAD

**Issue by Hale-CHIOU** [apache/shardingsphere#24737]
### Which version of ShardingSphere did you use?
5.2.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
create JDBC Connection
### Actual behavior
After a period of use with sharding-proxy,a part of JAVA application can not create JDBC connection,but another part of the JAVA application is the ability to create connections.After restarting sharding-proxy, all connections can be created normally.What directions can I take to troubleshoot this problem?

**Comment by TeslaCN** [comment]
Hi @Hale-CHIOU 
Is there any error occurred?

**Comment by Hale-CHIOU** [comment]
> Hi @Hale-CHIOU Is there any error occurred?

Sharing-proxy log file found no error.There is also enough space left on the sharding-proxy's disk.I can connect to sharding-proxy in local java service/SQL console, stdout.log can also output actual sql; only a few services in prod environment will not connect to sharding-proxy service. When I restarted these services/sharding-proxy, the problem disappeared

**Comment by TeslaCN** [comment]
We can hardly help you with this situation. 😂
