### ISSUE TITLE
Improve properties verification of DataConsistencyCalculateAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24748]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] ~~CRC32MatchDataConsistencyCalculateAlgorithm~~
- [ ] DataMatchDataConsistencyCalculateAlgorithm

**Comment by tobehardest** [comment]
Hello, I want to try to make this, can you assign it to me?

**Comment by Pace2Car** [comment]
@tobehardest Welcome!

**Comment by Pace2Car** [comment]
Hi @tobehardest, a period of time has passed, do you need help with any difficulties?

**Comment by Pace2Car** [comment]
Since it hasn't been updated in a long time, I will continue to complete it.
