### ISSUE TITLE
When the application is first started, a small number of requests for RT are very high, and the basic time consuming is in the parse phase

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#24744]
### Which version of ShardingSphere did you use?
ShardingSphere-5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
sql parse always keep at millisecond level

### Actual behavior
some request sql parse time consuming 5s+

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/20919316/226855867-bd9e3629-96e4-4eb0-b871-658a3fb7ce00.png">

for example sql:/*SS: primary=true :SS*/select {30+ Column Name} from table_a WHERE (  no_a = ? and no_b = ? )

before application ready we warm up some sql execute parse、route、rewrite，but the effect is not obvious

```
// connection is ShardingSphereConnection
Connection connection = dataSource.getConnection();

PreparedStatement preparedStatement = connection.prepareStatement(checkSql);

preparedStatement.execute();
```

Flame diagram of the just started process：

<img width="791" alt="image" src="https://user-images.githubusercontent.com/20919316/226862793-6aae60bb-b9f3-45a5-b410-bea497fd983a.png">

**Comment by TeslaCN** [comment]
Hi @git-chenhao 
Could you provide your flamegraph and the SQL which took 5s to parse?

**Comment by git-chenhao** [comment]
test code, local env need 2s+

```
 String sql ="/* mysql-connector-java-5.1.48 ( Revision: 29734982609c32d3ab7e5cac2e6acee69ff6b4aa ) */SELECT @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout";

        long start = System.currentTimeMillis();
        ShardingSphereSQLParserEngine parseEngine = new ShardingSphereSQLParserEngine(DatabaseTypeRegistry.getTrunkDatabaseTypeName(new MySQLDatabaseType()));
        long start2 = System.currentTimeMillis();
        System.out.println((start2 -start) + "ms");
        SQLStatement sqlStatement = parseEngine.parse(sql, true);

        System.out.println(sqlStatement);
        System.out.println((System.currentTimeMillis() -start) + "ms");
```

**Comment by TeslaCN** [comment]
Hi @git-chenhao 
I've tested your code in ShardingSphere 5.3.2. It seems that the results are not bad.

Each case repeat 10 times.

Enable parse cache:
![image](https://user-images.githubusercontent.com/20503072/227095166-6c43732a-c7a4-419b-a22d-50d86a13ae3b.png)

Disable parse cache:
![image](https://user-images.githubusercontent.com/20503072/227094897-cf6e65cc-c119-4045-aa62-7d8121d4645e.png)

**Comment by git-chenhao** [comment]
> Hi @git-chenhao I've tested your code in ShardingSphere 5.3.2. It seems that the results are not bad.
> 
> Each case repeat 10 times.
> 
> Enable parse cache: ![image](https://user-images.githubusercontent.com/20503072/227095166-6c43732a-c7a4-419b-a22d-50d86a13ae3b.png)
> 
> Disable parse cache: ![image](https://user-images.githubusercontent.com/20503072/227094897-cf6e65cc-c119-4045-aa62-7d8121d4645e.png)

@TeslaCN ShardingSphere 5.3.2 contrast ShardingSphere 5.0.0，Have you done a lot of optimization at the parsing level

？

**Comment by TeslaCN** [comment]
> > Hi @git-chenhao I've tested your code in ShardingSphere 5.3.2. It seems that the results are not bad.
> > Each case repeat 10 times.
> > Enable parse cache: ![image](https://user-images.githubusercontent.com/20503072/227095166-6c43732a-c7a4-419b-a22d-50d86a13ae3b.png)
> > Disable parse cache: ![image](https://user-images.githubusercontent.com/20503072/227094897-cf6e65cc-c119-4045-aa62-7d8121d4645e.png)
> 
> @TeslaCN ShardingSphere 5.3.2 contrast ShardingSphere 5.0.0，Have you done a lot of optimization at the parsing level
> 
> ？

I'm not familiar with optimization for parser. You may search the Pull Requests.

**Comment by git-chenhao** [comment]
```
 public static void testParse() {
        String sql = "/* mysql-connector-java-5.1.48 ( Revision: 29734982609c32d3ab7e5cac2e6acee69ff6b4aa ) */SELECT %s,@@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout";
        long start = System.currentTimeMillis();
        ShardingSphereSQLParserEngine parseEngine = new ShardingSphereSQLParserEngine(DatabaseTypeRegistry.getTrunkDatabaseTypeName(new MySQLDatabaseType()));
        parseEngine.parse(String.format(sql, 10), true);
        System.out.println("parse:" + (System.currentTimeMillis() - start) + "ms");
        ExecutorService executorService = Executors.newFixedThreadPool(100);
        for (int i = 0; i < 1000; i++) {
            int finalI = i;
            executorService.submit(() -> {
                long subStart = System.currentTimeMillis();
                parseEngine.parse(String.format(sql, finalI % 80), true);
                System.out.println("parse:" + (System.currentTimeMillis() - subStart) + "ms");
            });
        }
    }
```
@TeslaCN

**Comment by TeslaCN** [comment]
Could you provide us some SQLs of your scenarios? We cannot find out the root cause without issue details.

**Comment by git-chenhao** [comment]
After testing and warming up, I found that each thread was slow to execute the first time, but quickly thereafter. Is there any caching mechanism based on Threadlocal for antlr4？

**Comment by terrymanu** [comment]
The version is out of service, please try new version.
