### ISSUE TITLE
Improve properties verification of EncryptAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24747]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] MD5EncryptAlgorithm
- [ ] RC4EncryptAlgorithm
- [ ] AESEncryptAlgorithm
- [ ] SM4EncryptAlgorithm
- [ ] SM3EncryptAlgorithm
- [ ] CharDigestLikeEncryptAlgorithm

**Comment by strawberry-crisis** [comment]
Can I help with this issue? Thanks.
