### ISSUE TITLE
Improve properties verification of ShadowAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24749]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] ColumnRegexMatchedShadowAlgorithm
- [ ] ColumnValueMatchedShadowAlgorithm
- [ ] ~~SQLHintShadowAlgorithm~~

**Comment by ZJJ087** [comment]
Hello, I'm a newcomer for shardingsphere, can you assign this issue to me? thanks!

**Comment by ZJJ087** [comment]
是value和column有需要验证的地方吗？我看option type已经做了校验了

**Comment by Pace2Car** [comment]
Related test cases are still incomplete, such as `column` is null, etc.

**Comment by RaigorJiang** [comment]
> > @ZJJ087 Welcome!
> 
> 是value和column有需要验证的地方吗？我看option type已经做了校验了

Hi @ZJJ087 , only **English** is accepted here, please translate your comment, thank you!
