### ISSUE TITLE
Improve properties verification of ShardingAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24756]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [x] ClassBasedShardingAlgorithm
- [x] ComplexInlineShardingAlgorithm
- [x] HintInlineShardingAlgorithm
- [x] IntervalShardingAlgorithm
- [x] InlineShardingAlgorithm
- [x] CosIdSnowflakeIntervalShardingAlgorithm
- [x] CosIdIntervalShardingAlgorithm
- [x] CosIdModShardingAlgorithm

**Comment by liuxiaocs7** [comment]
Hi, @RaigorJiang I am a newcomer for shardingsphere, I want to try this issue, please assign to me, thanks! BTW, `ClassBasedSharingAlgorithm` appears twice on the first and third lines.

CC @Pace2Car

**Comment by RaigorJiang** [comment]
@liuxiaocs7 OK, thank you!

**Comment by liuxiaocs7** [comment]
Hi, @Pace2Car, thanks for your reminder, I've been a little busy recently so I'm a little behind schedule. At present, the implementation of `ClassBasedShardingAlgorithm` has been completed, could you help me to have a look at it in your free time?

I am not sure whether this modification meets the requirements. My understanding is to enhance the verification rules for the attribute values ​​input in the configuration, and modify the test program accordingly. Does `AlgorithmClassName` need to be further verified by reflection in the `getAlgorithmClassName` method? I see the current logic is in `ClassBasedShardingAlgorithmFactory`.

There are also some other questions. There are many `sharding expressions` and `time format` judgments about the sharding algorithm. Is there any tool class for this part in the project before to check whether it is a valid sharding expression or time format.

I will modify it according to your comments as soon as possible and continue to complete other verifications, thanks!

**Comment by Pace2Car** [comment]
Since it haven't progressed for too long, I will continue to work on it.
