### ISSUE TITLE
Improve properties verification of  JobRateLimitAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24753]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] QPSJobRateLimitAlgorithm
- [ ] TPSJobRateLimitAlgorithm

**Comment by insist777** [comment]
Hi, does this pr content meet the requirements and specifications? Hope to have some suggestions.

**Comment by Pace2Car** [comment]
@insist777 Thanks for your contribution and welcome to the community！
