### ISSUE TITLE
Improve properties verification of TrafficAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24754]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] ~~FirstSQLTrafficAlgorithm~~
- [ ] ~~JDBCTrafficAlgorithm~~
- [ ] ~~ProxyTrafficAlgorithm~~
- [ ] SQLMatchTrafficAlgorithm
- [ ] SQLRegexTrafficAlgorithm

**Comment by Ntmac** [comment]
Hi, I'm a newcomer for shardingsphere, can you assign this issue to me? thanks!

**Comment by Pace2Car** [comment]
@Ntmac Welcome!

**Comment by Netter99** [comment]
Hello, @Pace2Car , I am confused about what I should do about the code, can you make a simple discribtion about the problem?
What I need to impove about the properties verification? Is this what you want?
![image](https://user-images.githubusercontent.com/47752565/229690967-008c1859-7914-4d2c-b8a6-4574d085d618.png)

**Comment by Pace2Car** [comment]
Yes, you provided a correct demo, but the code style needs to be consistent with other files
refer to: https://github.com/apache/shardingsphere/pull/24742/files

After improve the verification, please add the related unit tests.

**Comment by Netter99** [comment]
Hello, @Pace2Car , I am not sure whether have I sucessfully pushed the code to the respository.
![image](https://user-images.githubusercontent.com/47752565/229987265-eaeaac03-26f4-4a2a-ab4c-3395dd9596ce.png)
![image](https://user-images.githubusercontent.com/47752565/229987365-4b9f99c6-dab6-4dc4-9d46-3fe3f9b1a07f.png)

**Comment by Netter99** [comment]
Hello, @Pace2Car , I have a question about how to deal with the throw exception.The details are as follow.
run `mvnw -T1C -B -ntp clean install`: the error is the same
![image](https://user-images.githubusercontent.com/47752565/230363937-9843bcf1-c4a7-4a93-9bce-ca2107ca55cc.png)

**Comment by Pace2Car** [comment]
> Hello, @Pace2Car , I have a question about how to deal with the throw exception.The details are as follow. run `mvnw -T1C -B -ntp clean install`: the error is the same ![image](https://user-images.githubusercontent.com/47752565/230363937-9843bcf1-c4a7-4a93-9bce-ca2107ca55cc.png)

If the thrown exception is what you expect, use `assertThrows()` to assert that.
