### ISSUE TITLE
Improve properties verification of KeyGenerateAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24750]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] SnowflakeKeyGenerateAlgorithm
- [ ] ~~UUIDKeyGenerateAlgorithm~~
- [ ] CosIdSnowflakeKeyGenerateAlgorithm
- [ ] CosIdKeyGenerateAlgorithm
- [ ] ~~NanoIdKeyGenerateAlgorithm~~

**Comment by shengdoupi** [comment]
Hi, I'm a newcomer for shardingsphere, can you assign this issue to me? thanks!

**Comment by Pace2Car** [comment]
@shengdoupi Welcome!
