### ISSUE TITLE
Improve properties verification of ReadQueryLoadBalanceAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24752]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] ~~RandomReadQueryLoadBalanceAlgorithm~~
- [ ] ~~RoundRobinReadQueryLoadBalanceAlgorithm~~
- [ ] WeightReadQueryLoadBalanceAlgorithm

**Comment by QiangYuan0828** [comment]
Hi, I would like to work on this issue.

**Comment by RaigorJiang** [comment]
Hi @QiangYuan0828, welcome!

**Comment by QiangYuan0828** [comment]
Hi, does my pull request satisfy the demand? hopes have some suggestions.

**Comment by Pace2Car** [comment]
> Hi, does my pull request satisfy the demand? hopes have some suggestions.

Hi @QiangYuan0828, Thanks for your PR, but it seems that these checks are unnecessary in your PR, The target described in the main issue(#24746) is to improve the properties verification in the `init` method.

For example, in `WeightReadQueryLoadBalanceAlgorithm.init()`, the data sources must not be empty, and the weight of data source must be configured

BTW: use `ShardingSpherePreconditions.checkState` like other checks do.

**Comment by QiangYuan0828** [comment]
@Pace2Car Got it, thanks for your clarification. I will correct it and resubmit again.
