### ISSUE TITLE
Improve properties verification of MaskAlgorithm

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#24755]
Hi community,

This issue is one of the tasks of #24746.

If not sure what to do, please refer to the example: #24742

## Aim
- [ ] MaskBeforeSpecialCharsAlgorithm
- [ ] MaskFirstNLastMMaskAlgorithm
- [ ] KeepFirstNLastMMaskAlgorithm
- [ ] MaskAfterSpecialCharsAlgorithm
- [ ] MaskFromXToYMaskAlgorithm
- [ ] KeepFromXToYMaskAlgorithm
- [ ] MilitaryIdentityNumberRandomReplaceAlgorithm
- [ ] UnifiedCreditCodeRandomReplaceAlgorithm
- [ ] LandlineNumberRandomAlgorithm
- [ ] PersonalIdentityNumberRandomReplaceAlgorithm
- [ ] TelephoneRandomReplaceAlgorithm
- [ ] GenericTableRandomReplaceAlgorithm
- [ ] ~~MD5MaskAlgorithm~~

**Comment by kyooosukedn** [comment]
Hi, would love to contribute :)

**Comment by Pace2Car** [comment]
@kyooosukedn Welcome!

**Comment by Pace2Car** [comment]
Hi @kyooosukedn, thank you very much for your contribution, this task has been completed.
