### ISSUE TITLE
About Issues#24741,I want to say

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#24776]
1： I think I described it very very very clearly. Why do you always answer irrelevant questions?

2： My question is  " vertical sharding table  Is it supported to insert logical tables， the data scattered among the three real tables?"
       if support  How to write,  I do not know how to write (Because it is not found in official documents and official examples.)
       if not support  you can tell me "no"

**Comment by TeslaCN** [comment]
Hi @liruhui 
1. There is no need to open multiple issues for same question.
2. ShardingSphere does support vertical sharding. Please try understanding design of sharding rule. Community **does not provide hand-by-hand teaching service**. You may ask company for commercial service.
