### ISSUE TITLE
Create default sharding strategy failed when there is no sharding rules in database.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#24770]
### Which version of ShardingSphere did you use?
master 7304be07

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Create default sharding strategy successfully

### Actual behavior
Create default sharding strategy failed when no sharding rules are configured in the database
<img width="1086" alt="Snipaste_2023-03-23_10-38-23" src="https://user-images.githubusercontent.com/5668787/227093774-54ed69ea-7a69-4223-9865-038cb828e1d9.png">

### Reason analyze (If you can)
Because the check of current rule config
```java
private void checkCurrentRuleConfiguration(final String databaseName, final ShardingRuleConfiguration currentRuleConfig) {
        ShardingSpherePreconditions.checkNotNull(currentRuleConfig, () -> new MissingRequiredRuleException("Sharding", databaseName));
    }
```

**Comment by Pace2Car** [comment]
I will try it.
