### ISSUE TITLE
enhance NewInstanceServiceLoader.

### ISSUE THREAD

**Issue by cherrylzhao** [apache/shardingsphere#2477]
currently we leverage the JDK `ServiceLoader` to load the SPI implement class, `ServiceLoader` could not cache found classes, it will  search class every time using ClassLoader. it is not convenient when we need to acquire instance more than one time. so we consider about extending capability of raw ServiceLoader.

- [x] Establish ShardingSphereServiceLoader
- [ ] Only cache class instead of instance while registry
- [ ] Provide loading instance by type
- [ ] Provide loading instance by args
- [x] Refactor TypeBasedSPI.
- [x] Refactor other customizer service loader

**Comment by liujuntao** [comment]
When i tracing the code, i found lots of NewInstanceServiceLoader exist all the project .

**Comment by cherrylzhao** [comment]
ShardingSphereServiceLoader is based on multi-instances, so we do not plan to provide singleton feature as below
- Only cache class instead of instance while registry
-  Provide loading instance by type
- Provide loading instance by args
