### ISSUE TITLE
MasterSlave Mode Datasource, why do  shardingtable config rule is only effect on master datasource?

### ISSUE THREAD

**Issue by bitbxj** [apache/shardingsphere#24786]
is there error in config ,or it is normal!

**Comment by zhaojinchao95** [comment]
Please provide your configuration.

**Comment by bitbxj** [comment]
sorry！
above src codes there is error to correct. actually second parameter is “shardingRuleConfig”
"return ShardingDataSourceFactory.createDataSource( getDataSourceMap( dataSourceMaster, dataSourceSlave ), shardingRuleConfig, properties );"
