### ISSUE TITLE
Use SPI to handle initialization of different Opentracing implements

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#2478]
Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
Some of the Opentracing implements use constructor to initialize like SkyWalking, while some of them use builder to initialize like Zipkin. To support all of the implements, the SPI mechanism is required.

**Comment by betterjava** [comment]
I would like try to do this in a few days.

**Comment by betterjava** [comment]
should I add SkywalkingTracer as default implement?

**Comment by tuohai666** [comment]
> @tuohai666 should I add SkywalkingTracer as default implement?

It's not necessary.

Have you tested for various Opentracing implements? If so, please provide some tracing pictures, at least include SkyWalking and Zipkin.

**Comment by betterjava** [comment]
Not yet.
I just have tested success for unit tests. I will test that later.

**Comment by betterjava** [comment]
@tuohai666 I tested it for SkyWalking with sharding-jdbc and sharding-proxy.
But the Zipkin client Brave does not have default implements for Opentracing. I have try my hard to convert brave to Opentracing, but still have some methods can not convert success.I have change nothing in using Opentracing,just provide a SPI for getting a Opentracing Tracer. Do you have any suggestions for me?

**Comment by tuohai666** [comment]
OK. I heard someone have tested with the version of io.zipkin.brave 5.1.1/io.opentracing.brave 0.31.0.
You can try with that version.

**Comment by betterjava** [comment]
There is no 'ActiveSpan' in io.opentracing:0.31.0. The shardingsphere where throw an Exception because we use that with  io.opentracing:0.30.0 in our dev version. Like below:

`java.lang.NoClassDefFoundError: io/opentracing/ActiveSpan`

**Comment by tuohai666** [comment]
So, we should try to find way to support both of the implements.

**Comment by betterjava** [comment]
OK. I understand what you said. 
The current situation is :

- The highest Openstracing version supported by Skywalking is 0.30.0
- The lowest  Openstracing version supported by jaeger is 0.31.0
- There is no directy support from Zipkin,but I seems like 0.31.0 will by supported by Changing  some code from Brave.

**Comment by tuohai666** [comment]
Thanks for your effort. You really make big progress.

**Comment by tuohai666** [comment]
It's hard to combine Opentracing 0.30.0 and 0.31.0. Maybe it's no necessary to do this.
