### ISSUE TITLE
Can't set search_path in postgresql

### ISSUE THREAD

**Issue by gongdaowei** [apache/shardingsphere#24795]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior
 
Can't execute ```set search_path = 'xxx';``` in proxy.

```
server 12.1-ShardingSphere-Proxy 5.3.0

encrypt_db=> set search_path = 'abc';
SET
encrypt_db=> show search_path;
 search_path
-------------

(1 row)
```

### Actual behavior

Can execute set search_path = 'xxx' ; success in proxy and take effect.

### Reason analyze (If you can)

```PostgreSQLDDLStatementSQLVisitor```  is not parsing this sql.

**Comment by SeanDragon** [comment]
I also have the same problem, hope to solve it as soon as possible, thanks.
