### ISSUE TITLE
Running "mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e" failed.

### ISSUE THREAD

**Issue by twitchob** [apache/shardingsphere#24806]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Hi,community
I was able to succeed by executing the following build command according to the documentation:`mvn clean install -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -Prelease`
![a1c2921581f15a4ede4a5b7f60c15cf](https://user-images.githubusercontent.com/34822229/227486223-b7192a2e-2cb6-47eb-a9af-9d0c8bf667ba.png)

This command did not succeed:`mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e` or `mvn clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`
![image](https://user-images.githubusercontent.com/34822229/227486966-666908cd-1862-462b-9c5f-f45e3cd27d1c.png)

I have reverted all the code, but the problem still persists. If possible, could you help me solve this problem?

**Comment by TeslaCN** [comment]
Maybe some unit tests failed on Windows environment.

**Comment by TeslaCN** [comment]
Is it the same as #24697?

**Comment by gxxiong** [comment]
Try moving the project to the root directory, such as D:

**Comment by twitchob** [comment]
> Is it the same as #24697?

YES.I have added the environment variable, but it doesn't seem to work.

> Try moving the project to the root directory, such as D:

OK,I will have try.I am still actively looking for a solution, but testing will take some time, I will continue to track the problem until it is solved

**Comment by twitchob** [comment]
I confirmed that adding environment variables  `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` would solve this problem, but now other issues have arisen that I am working on gradually
