### ISSUE TITLE
how to config actualDataNodes to express  db1.tb1,  db2.tb2 ,db3.tb3, db4.tb4 db5.tb5 db6.tb6

### ISSUE THREAD

**Issue by zhouyao1994** [apache/shardingsphere#24814]
## Question
i want config  a list wiht     [db0.db0    db1.tb1,  db2.tb2] but when i set  actualDataNodes to 
`db${0,2}.tb${0,2}`
it genarate a list with
[    "db0.tb0", "db0.tb1", "db0.tb2",    "db1.tb0", "db1.tb1", "db1.tb2",    "db2.tb0", "db2.tb1", "db2.tb2"]

how can i genarate to db1.tb1,  db2.tb2 ,db3.tb3, db4.tb4 db5.tb5 db6.tb6?

**Comment by RaigorJiang** [comment]
I think this needs to be enumerated, or you can check the syntax documentation of groovy
(Expressions are parsed by groovy)

Ref: https://shardingsphere.apache.org/document/current/en/features/sharding/concept/#row-value-expressions

**Comment by zhouyao1994** [comment]
> I think this needs to be enumerated, or you can check the syntax documentation of groovy (Expressions are parsed by groovy)
> 
> Ref: https://shardingsphere.apache.org/document/current/en/features/sharding/concept/#row-value-expressions

i searched the groovy documentation，but not get more elegent expression

**Comment by RaigorJiang** [comment]
That's true, if you don't want to enumerate, can you use the same table name in each data source?
`db${0..6}.tb`

**Comment by zhouyao1994** [comment]
> That's true, if you don't want to enumerate, can you use the same table name in each data source? `db${0..6}.tb`

actually ，In some scenarios, I would like the programmers to explicitly specify the table name to avoid any mistakes in writing the database.

**Comment by RaigorJiang** [comment]
I understand, but it's a pity that there is no better way at present.

**Comment by zhouyao1994** [comment]
> 

ok,thx~
