### ISSUE TITLE
Add test cases for ReadwriteSplittingDataSourceRouter

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#24811]

**Comment by kvaithin** [comment]
Hi could this be assigned to me pls.

**Comment by yx9o** [comment]
@kvaithin Welcome.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by terrymanu** [comment]
Duplicated with #24935
