### ISSUE TITLE
E2EContainerComposer closed not as expected.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#24845]
## Bug Report
https://github.com/apache/shardingsphere/blob/7a7b9118535348835001404176b197899f632571/test/e2e/sql/src/test/java/org/apache/shardingsphere/test/e2e/engine/composer/E2EContainerComposer.java#L102-L106
 
 TOTAL_STATUS_COUNT seems not correct.
 
 This may cause container not closed as expected.

**Comment by terrymanu** [comment]
The code has been refactored.
