### ISSUE TITLE
How to monitor hikaricp

### ISSUE THREAD

**Issue by huang714669** [apache/shardingsphere#24863]
## Question

- version: sharding-jdbc 5.1.2, springboot 2.6
- question: how to exposure hikaricp metrics to springboot actuator endpoint?
I can not see any hikari related metrics in http://localhost:8080/actuator/metrics
my configuration like this:
`spring.shardingsphere.datasource.names=ds_0
spring.shardingsphere.datasource.ds0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.jdbc-url=xxx
spring.shardingsphere.datasource.ds0.username=root
spring.shardingsphere.datasource.ds0.password=xxx
spring.shardingsphere.datasource.ds0.maximum-pool-size=50`

and also tried to set MetricsTrackerFactory properties but failed with argument type mismath error:
spring.shardingsphere.datasource.ds0.metrics-tracker-factory=com.zaxxer.hikari.metrics.prometheus.PrometheusMetricsTrackerFactory

**Comment by terrymanu** [comment]
Please try to use ShardingSphere-agent to monitor apm and metrics

**Comment by HallenW** [comment]
> 有人请回答这个问题吗？我已经在这里屏蔽了好几天了，尝试了很多方法好几天了？由于ShardingSphereDatasource没有提供任何公共方法来设置hikari MetricsTrackerFactory

I have also encountered this problem recently. Do you have a solution?

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
