### ISSUE TITLE
test proxy through mysql test framework

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#24873]
the [mysql test framework](https://dev.mysql.com/doc/dev/mysql-server/latest/PAGE_MYSQL_TEST_RUN.html) is the test suite provided by mysql. this test suite contains a lot of test script for mysql server and client.

to test the compatibility of shardingsphere, we could test by mysql test framework suite :
1. luanch up proxy
2. luanch mysql test framework and the target is that proxy
3. record the compability results

**Comment by totalo** [comment]
hi, I can follow up on this issue, please assign it to me.

**Comment by totalo** [comment]
hi, I can follow up on this issue, please assign it to me.
