### ISSUE TITLE
不带查询条件的怎么分表？

### ISSUE THREAD

**Issue by zkpgds** [apache/shardingsphere#24884]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by zhaojinchao95** [comment]
Please translate your titile to english for this issue.

**Comment by RaigorJiang** [comment]
**For English only**, other languages will not accept.
