### ISSUE TITLE
when alter storage unit, old connections did not closed

### ISSUE THREAD

**Issue by wzhj2326** [apache/shardingsphere#24882]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

when alter storage unit, old connections did not closed

**Comment by zhaojinchao95** [comment]
Can you show your `DistSQL`?

**Comment by wzhj2326** [comment]
> Can you show your `DistSQL`?
REGISTER STORAGE UNIT ds_01 (URL="jdbc:mysql://172.22.3.237:3306/sharding_write_0",USER="root",PASSWORD="123456");

ALTER STORAGE UNIT ds_01 (URL="jdbc:mysql://172.22.3.237:3306/sharding_write_0",USER="root",PASSWORD="123456");


![image](https://user-images.githubusercontent.com/15643447/228411107-e13c6bcd-0c17-43b9-9d45-b950eada6021.png)

![image](https://user-images.githubusercontent.com/15643447/228411246-2b6fd855-e336-4de3-8c81-4fc5f51aad4a.png)

**Comment by zhaojinchao95** [comment]
There is no change in your storage unit configuration, and then go to modify it?

**Comment by zhaojinchao95** [comment]
@RaigorJiang Maybe we can intercept at distsql.

**Comment by wzhj2326** [comment]
> There is no change in your storage unit configuration, and then go to modify it?

@zhaojinchao95 
Yes ,but when  i register storage unit,it create 4 connections ,
then unregister it , remaining 2 connections，only 2 connection is closed

![image](https://user-images.githubusercontent.com/15643447/228442831-61bd5097-cda1-44d6-bd5b-27372e3de1ed.png)

![image](https://user-images.githubusercontent.com/15643447/228443183-a30c977b-7399-439e-9be6-f099cda7ec10.png)

**Comment by zhaojinchao95** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/33742097/228450584-8585a17a-a0fe-4d5d-9255-bb8c70354d29.png">

**Comment by wzhj2326** [comment]
I think it is caused by line 88 in the following class，it got one connection but it did not closed the connection.

https://github.com/apache/shardingsphere/blob/296d2913d05fbe88eb82ea460ac932ec97164825/infra/common/src/main/java/org/apache/shardingsphere/infra/datasource/props/DataSourcePropertiesValidator.java#L71-L90

**Comment by zhaojinchao95** [comment]
> > <img alt="image" width="727" src="https://user-images.githubusercontent.com/33742097/228450584-8585a17a-a0fe-4d5d-9255-bb8c70354d29.png">
> > Can you try it with master branch? I can't reproduce it.
> 
> @zhaojinchao95
> 
> I try it with master branch,it also has the problem. Are you execute `show processlist` on the actual database ？

I 'm not  execute `show processlist` on the actual database, i will try again

**Comment by wzhj2326** [comment]
Hi @zhaojinchao95 have you tried again?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 have you tried again?

Yeah, it looks has some problem, would you like submit a pull request to fix it?

**Comment by RaigorJiang** [comment]
@wzhj2326   Indeed it is, thanks for pointing that out.
