### ISSUE TITLE
Why does sharding-jdbc-spring-boot-starter 4.1 perform better than shardingsphere-jdbc-core5.3

### ISSUE THREAD

**Issue by Misakami** [apache/shardingsphere#24881]
I compare the performance of the two versions on the test server to determine whether to update to the new version. The results are as follows
4 database  8 tables
ration_trigger_trade_flow Number of single table records: 3058,654

sharding-jdbc-spring-boot-starter 4.1
![image](https://user-images.githubusercontent.com/22981008/228208406-c99d6791-172f-4fec-9ece-05071f2c8016.png)
shardingsphere-jdbc-core 5.3
![image](https://user-images.githubusercontent.com/22981008/228208652-06cddb79-c601-48ab-b3a7-84cb537b495a.png)

**Comment by terrymanu** [comment]
It's difficult to determine exactly why sharding-jdbc-spring-boot-starter 4.1 performs better than shardingsphere-jdbc-core 5.3 without further information about your specific use case and performance metrics. However, here are some general reasons why one may perform better than the other.

It's important to note that performance can be affected by a variety of factors, including the hardware and software environment, the size and complexity of the dataset, and the specific use case. Therefore, it's recommended to perform your own benchmarks and tests to determine which library performs better for your specific use case.
