### ISSUE TITLE
The fact that the \d&&\d tableName syntax is not yet supported.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#24899]
The following issues are from single table scenarios, other types have not been tested.

My resources config and query sql is as follows:
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/76552510/228719224-5382ae2e-7d1a-47bb-a7cc-afa4be79ba72.png">
Got result like follows:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/76552510/228719407-facff2fd-a518-4017-ac36-e0f842b90ffa.png">
![image](https://user-images.githubusercontent.com/76552510/228720202-25933625-341a-4ec1-abfb-ce6dd43a85c4.png)
acutally, data like follows:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/76552510/228719535-8583ecab-a25b-47a6-9c41-dc3827abdde0.png">

When I debug , Found that schema have no data, even 10min passed.
![image](https://user-images.githubusercontent.com/76552510/228723837-214c2cde-e261-44c4-a841-3b13d4e1118c.png)

I will try to fix it, if someone wanna do me a favour,  that would be great.

**Comment by RaigorJiang** [comment]
Hi @JiekerTime , currently cluster mode can support `\d` , excluding `\d tableName`

**Comment by JiekerTime** [comment]
> Hi @JiekerTime , currently cluster mode can support `\d` , excluding `\d tableName`

singleton couldn't support yet?

**Comment by strongduanmu** [comment]
You can take a look at sys_data, the actual data is stored in sys_data znode.

**Comment by strongduanmu** [comment]
> All the data should come from ShardingSphereDatabase.schemas.

ShardingSphereDatabase.schemas only contains table metadata, the actual data of pg_class and pg_namespace are stored in sys_data znode. These data were collected from native postgresql via a timed task, performed every 30s.

**Comment by strongduanmu** [comment]
Moreover, this feature is only supported on the Proxy adaptor and requires cluster mode.

**Comment by JiekerTime** [comment]
The context is understood, I will try to support \d tableName and try to support singleton mode.
