### ISSUE TITLE
[Question] How to use DistSQL in native ShardingSphere-Proxy

### ISSUE THREAD

**Issue by liuxiaocs7** [apache/shardingsphere#24919]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

---

Hi, community,  i start `org.apache.shardingsphere.proxy.Bootstrap` by IDEA (set argument `3307` as port)

using `server.yaml` as conf:

```yaml
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500

authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED
```

ShardingProxy starts successfully as follows:

```
[INFO ] 2023-04-01 00:10:50.850 [main] o.a.c.f.imps.CuratorFrameworkImpl - Default schema
[INFO ] 2023-04-01 00:10:50.859 [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x10000f2303c000e, negotiated timeout = 40000
[INFO ] 2023-04-01 00:10:50.886 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
[INFO ] 2023-04-01 00:10:52.950 [main] o.apache.curator.utils.Compatibility - Using org.apache.zookeeper.server.quorum.MultipleAddresses
[INFO ] 2023-04-01 00:10:53.515 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy Cluster mode started successfully
```

But when I try to connect to the proxy using the mysql client in windows, it seems to be stuck and i can't login.

![client](https://user-images.githubusercontent.com/42756849/229174588-3d835716-2184-4978-83c0-8d9169105ba9.gif)

logs in IDEA's console has **no change**.

when i stop `BootStrap`, i got

```
PS C:\Users\liuxiaocs> mysql -h 127.0.0.1 -P3307 -uroot -p
Enter password: ****
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 2
```

~~So how to use DistSQL in native ShardingSphere-Proxy or only support configuration by yaml now  in local mode~~?

---

- Env: Win10
- JDK 1.8
- Commit id: a32f720cc3d1a0ab52b2b7562cfbeeef732e4149

**Comment by RaigorJiang** [comment]
Proxy is indeed used as such, both in binary and in IDEs.
Did you get any exception messages?

**Comment by liuxiaocs7** [comment]
> Proxy is indeed used as such, both in binary and in IDEs. Did you get any exception messages?

Hi, @RaigorJiang, I added some notes to make the problem description clearer, and there is no exception message in IDEA's console.

**Comment by liuxiaocs7** [comment]
Hi, @RaigorJiang, Sorry for late.

1.  when I use standalone mode, mysql client can connect to the Proxy normally.
2.  I deleted default zookeeper namespace (governance_ds) and tried, but failed too.
3. `proxy-frontend-database-protocol-type` is not included in props, `server.yaml` as conf as shown above, no other configuration

---

I found that it may be a problem with the JDK version. After switching to JDK17, I can log in successfully.

Before:
<img width="483" alt="Snipaste_2023-04-20_02-54-13" src="https://user-images.githubusercontent.com/42756849/233173485-eed5f1eb-6c95-426d-b8f1-10e06d055123.png">
After:
<img width="455" alt="Snipaste_2023-04-20_02-56-45" src="https://user-images.githubusercontent.com/42756849/233173511-c592749b-03e8-4658-97f8-5e6f16995097.png">

Result:
![image](https://user-images.githubusercontent.com/42756849/233173627-431921c7-f411-42c5-8194-7c144841ff09.png)

Thanks!

**Comment by RaigorJiang** [comment]
OK, thanks for the feedback.

Now the ShardingSphere source code needs to be compiled with JDK 11 or above, but the binary file supports running on JDK 8.

This issue you found is very interesting. Anyway, congratulations on solving the problem.

**Comment by RaigorJiang** [comment]
My JDK version:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/5668787/233243701-c2ad3330-5042-40a2-af3f-bea8c6f3d3de.png">
