### ISSUE TITLE
Add test case for ReadwriteSplittingDataSourceRouter

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#24935]

**Comment by ShockleysxX** [comment]
Hello, I want to try to make this, can you assign it to me?

**Comment by AdrianAcostaPR** [comment]
Hello, if this is still available I'd like to give it a try.  Can it be assigned to me?

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?
