### ISSUE TITLE
Add test cases for readwrite-splitting router

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#24940]
Add test cases for:

- [x] QualifiedReadwriteSplittingPrimaryDataSourceRouter
- [x] QualifiedReadwriteSplittingTransactionalDataSourceRouter
- [x] StandardReadwriteSplittingDataSourceRouter

**Comment by ZJJ087** [comment]
I want to do it

**Comment by wuxihao01** [comment]
Hello, I want to try to make this, can you assign it to me?@terrymanu

**Comment by wuxihao01** [comment]
@terrymanu Hello, I want to try to make this, can you assign it to me?

**Comment by Sakuragi27** [comment]
Hello, I want to try, can you give me?

**Comment by strongduanmu** [comment]
@Sakuragi27 Welcome, I will assign this issue to you.

**Comment by Sakuragi27** [comment]
@strongduanmu thanks!

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?
