### ISSUE TITLE
oracle batchInsert

### ISSUE THREAD

**Issue by ly164608001** [apache/shardingsphere#24986]
### Which version of ShardingSphere did you use?
**5.3.1**

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
oracle batchinsert successful

### Actual behavior
org.apache.shardingsphere.infra.binder.statement.dml.InsertStatementContext.<init> throws NullPointerException

### Reason analyze (If you can)
Possible syntax parsing exception

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
execute SQL：INSERT ALL INTO t_bill (id, billing_date) VALUES ( ?, ? ) INTO t_bill (id, billing_date) VALUES ( ?, ? ) SELECT 1 FROM DUAL 
sharding rule ：
mode:
  type: Standalone
  repository:
    type: JDBC
    props:
      path: demo

dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@ip:port/orcl
    username: xxx
    password: xxx
    maxPoolSize: 10

rules:
- !SHARDING
    tables:
      t_bill:
        actualDataNodes: ds_$->{0}.t_bill_$->{202304}
        tableStrategy:
          standard:
            shardingColumn: billing_date
            shardingAlgorithmName: date_interval
    shardingAlgorithms:
      date_interval:
        type: INTERVAL 
        props:
          datetime-pattern: yyyy-MM-dd HH:mm:ss
          datetime-lower: '2021-01-01 00:00:00'
          datetime-upper: '2025-01-01 00:00:00'
          sharding-suffix-pattern: yyyyMM
          datetime-interval-amount: 1
          datetime-interval-unit: MONTHS      
exception occur：
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.infra.binder.statement.dml.InsertStatementContext.<init>

**Comment by RaigorJiang** [comment]
Hi @ly164608001 
Can you provide the table structure? It is convenient for volunteers to reproduce the problem.

**Comment by ly164608001** [comment]
> Hi @ly164608001 Can you provide the table structure? It is convenient for volunteers to reproduce the problem.
 the table structure in oracle is：
create table t_bill_202304 (id int ,billing_date date)；
