### ISSUE TITLE
When I used Flyway, I also configured the snowflake ID, but on the first startup, the saved data ID was null

### ISSUE THREAD

**Issue by Johnnie-YH** [apache/shardingsphere#24998]
ShardingJdbc 5.3.1  flyway 7.12.0

When I used Flyway, I also configured the snowflake ID, but on the first startup, the saved data ID was null

<img width="1174" alt="图片" src="https://user-images.githubusercontent.com/45616388/229660222-af098774-d5d5-4732-aaca-16dd4ce77043.png">

Because the fly script is executed only after loading the datasource, the tables in the schema are empty, and therefore the snowflake id will not be generated

<img width="1487" alt="图片" src="https://user-images.githubusercontent.com/45616388/229661055-1ce23974-fe2e-4bd9-8fe0-17fc60ffbee2.png">

**Comment by RaigorJiang** [comment]
Hi @Johnnie-YH 
Are you willing to optimize this problem?
