### ISSUE TITLE
how to read config from nacos config center 

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#25027]
# Detailed steps
## step1: start nacos 
![image](https://user-images.githubusercontent.com/24687986/230313930-5f2bfeb2-98b3-499b-83b3-233699015e0b.png)

## step2: create config in nacos 
![image](https://user-images.githubusercontent.com/24687986/230313712-308889eb-dc86-421b-ae98-f6075cd16127.png)

## step3:  my questions 
```properties 
 java Project  how to read config from nacos  and  what  dependency is needed
 ```
![QQ图片20230407102710](https://user-images.githubusercontent.com/24687986/230528409-2c632f39-837f-42c5-8956-bcadb452e6b3.png)

**Comment by zhaojinchao95** [comment]
Maybe https://nacos.io/zh-cn/docs/system-configurations.html this document can help you.

**Comment by liruhui** [comment]
@zhaojinchao95  

I not fount any useful configuration  in  https://nacos.io/zh-cn/docs/system-configurations.html 

java project  start three times(the project has three instances) ，so  three instances get the same shadingconfig  from nacos is  needed. but not got it   because  I dont know where to write  "dataId", is it not supported?
