### ISSUE TITLE
Merge shardingsphere-standalone-mode-repository-jdbc module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25057]
Modify the module `shardingsphere-standalone-mode-repository-jdbc-core` by changing the current H2 and MySQL SPI to an XML configuration file that is directly load by the core module.

The XML attribute should contain all SQL statements of `JDBCRepositoryProvider` and the JDBC driver class name, which be parsed JAXB.

After the modification, `shardingsphere-standalone-mode-repository-jdbc-h2` and `shardingsphere-standalone-mode-repository-jdbc-mysql` can be deleted, and `shardingsphere-standalone-mode-repository-jdbc-core` should be renamed to "shardingsphere-standalone-mode-repository-jdbc" and moved up to the parent module.

The xml should be:

```xml
<sql type="H2" driver-class-name="xxx.xxx.xxx">
    <create-table> xxx</create-table>
    <select-by-key> xxx</select-by-key>
    <select-by-parent> xxx</select-by-parent>
    <insert> xxx</insert>
    <update> xxx</update>
    <delete> xxx</delete>
</sql>
```

**Comment by iamhucong** [comment]
@terrymanu Would it be possible to assign it to me? I believe I could try to accomplish it.

**Comment by magestacks** [comment]
@iamhucong Welcome.

**Comment by iamhucong** [comment]
@terrymanu @magestacks Hi, I have already submitted the pull request. Could you please review it when you have time and provide any suggestions you may have?

**Comment by terrymanu** [comment]
> @terrymanu @magestacks Hi, I have already submitted the pull request. Could you please review it when you have time and provide any suggestions you may have?

Thank you, I just comment on pull request.

**Comment by shiliang-star** [comment]
Please see this [issue](https://github.com/apache/shardingsphere/issues/28227)
