### ISSUE TITLE
Add 'SortMergeJoin' in Federation to support large table join.

### ISSUE THREAD

**Issue by boyjoy1127** [apache/shardingsphere#25064]
Refs #19937
## Add 'SortMergeJoin' in Federation to support large table join
![image](https://user-images.githubusercontent.com/101028753/230697075-208eea55-e4cd-4f0b-a608-2ba453ab276a.png)

```
sort t1, sort t2
R1 = t1.next()
R2 = t2.next()
while (R1 != null && R2 != null) {
   if R1 joins with R2  
      output (R1, R2)
   else if R1 < R2  
      R1 = t1.next()
   else
      R2 = t2.next()
}
```

**Comment by strongduanmu** [comment]
Since the design of sql federation is not consistent with this issue now, I will close this issue. If there is a new solution, please discuss it in the community first.
