### ISSUE TITLE
ShardingSphereResultSetUtil.createColumnLabelAndIndexMap  There are more mapped fields than the actual SQL query results, resulting in reading out of bounds

### ISSUE THREAD

**Issue by gzwz** [apache/shardingsphere#25063]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

ShardingSphereResultSetUtil.createColumnLabelAndIndexMap  There are more mapped fields than the actual SQL query results, resulting in reading out of bounds
![图片](https://user-images.githubusercontent.com/15667193/230666015-8298fc55-22bd-45ab-ad74-af3b95c185ef.png)

**Comment by strongduanmu** [comment]
Hi @gzwz, which version do you use? Besides, can you provide the step to reproduce this exception?

**Comment by gzwz** [comment]
org.apache.shardingsphere:shardingsphere-jdbc-core:5.3.2  

this is  mys sql  
---------------------------------------------------------------------------
SELECT 
    DISTINCT RES.* 
FROM 
    (   SELECT 
            PROCDEF.* , 
            INSTANCE.INSTANCE_COUNT_ , 
            INC.INCIDENT_TYPE_ , 
            INC.INCIDENT_COUNT_ 
        FROM 
            ACT_RE_PROCDEF PROCDEF 
        LEFT OUTER JOIN 
            (   SELECT 
                    E.PROC_DEF_ID_ , 
                    COUNT(E.PROC_INST_ID_) AS INSTANCE_COUNT_ 
                FROM 
                    ACT_RU_EXECUTION E 
                WHERE 
                    E.PARENT_ID_ IS NULL 
                GROUP BY 
                    E.PROC_DEF_ID_ ) INSTANCE 
        ON 
            PROCDEF.ID_ = INSTANCE.PROC_DEF_ID_ 
        LEFT OUTER JOIN 
            (   SELECT 
                    I.PROC_DEF_ID_ , 
                    I.INCIDENT_TYPE_ , 
                    COUNT(I.ID_) AS INCIDENT_COUNT_ 
                FROM 
                    ACT_RU_INCIDENT I 
                WHERE 
                    I.ID_ = I.ROOT_CAUSE_INCIDENT_ID_ 
                GROUP BY 
                    I.PROC_DEF_ID_, 
                    I.INCIDENT_TYPE_ ) INC 
        ON 
            PROCDEF.ID_ = INC.PROC_DEF_ID_ ) RES 
ORDER BY 
    RES.ID_ ASC 
------------------------------------------------------------------------
the query  result of the query is 18 columns

![图片](https://user-images.githubusercontent.com/15667193/230763802-289b3dc9-ab9d-48bd-a320-3cc925c37fce.png)

and 

![图片](https://user-images.githubusercontent.com/15667193/230764102-380d9853-d6bf-46f6-9c88-bd782f035730.png)


The original results found in the above figure are still correct, but at this point, errors begin to occur

![图片](https://user-images.githubusercontent.com/15667193/230764493-85e329f9-d245-4fde-b48a-21801dc1858e.png)

After taking column 19 here, it will cause the boundary to be crossed later on
![图片](https://user-images.githubusercontent.com/15667193/230764587-a0cec7eb-d7fb-47ef-b9a3-e2b14ac4fd88.png)

**Comment by gzwz** [comment]
The reason for this error is that an additional subquery field was retrieved
![图片](https://user-images.githubusercontent.com/15667193/230764859-fb58832a-03a3-46ab-b77a-ea190c876d2d.png)

**Comment by gzwz** [comment]
This is the MySQL database address, username, and password. It's okay. If you use it, please let me know and I will delete it

120.77.38.34   13306  smlh_sit  testuser  123456789

**Comment by gzwz** [comment]
and  
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.1</version>
  </dependency>

I tried again using this version
He will also search out the sub query fields
As shown in the following figure

![图片](https://user-images.githubusercontent.com/15667193/230817934-260d7754-9581-4a28-971c-a0f6cef24e39.png)

**Comment by strongduanmu** [comment]
@gzwz Did you config sharding rule?

**Comment by gzwz** [comment]
I have used 5.3.2 and still have similar issues

**Comment by strongduanmu** [comment]
Hi @peachyy @gzwz, can you try the latest 5.4.1? We added SQL Binder to analyze table and column meta-information, and I think this problem should have been solved.

**Comment by strongduanmu** [comment]
If you still have problems using 5.4.1, please help provide a demo program so that we can quickly fix the problem. Thank you very much.
