### ISSUE TITLE
When using liquibase, JdbcConnection connot get the database catalog correctly

### ISSUE THREAD

**Issue by yuyee-qi** [apache/shardingsphere#25073]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by yuyee-qi** [comment]
I use the latest version 5.3.2 of ShardingSphere-JDBC.

Before using it, I can start my SpringBoot project repeatedly, but now, I just can do once. When I start my project for the second time, it will fail because of repeated creation of liquibase's tables.

From the debug call stack, there is only a difference when using it before and after. The JdbcConnection cannot obtain catalog after using it. 

So I think there is something wrong with this code in calss **org.apache.shardingsphere.driver.jdbc.adapter.AbstractConnectionAdapter**, it doesnot store and return the catalog correctly.

    @Override
    public final String getCatalog() {
        return null;
    }
    @Override
    public final void setCatalog(final String catalog) {
    }

I wonder why it returns null directly instead of saving is as a field in the abstract class.

**Comment by RaigorJiang** [comment]
@yuyee-qi 
It seems that you need to get the catalog from ShardingSphereConnection, can you provide a demo that reproduces the problem?

**Comment by yuyee-qi** [comment]
I reproduce this exception, the demo in my demo project **https://github.com/yuyee-qi/shardingsphere-liquibase-demo**

**Comment by wanghongzhou** [comment]
这个BUG [22876](https://github.com/apache/shardingsphere/issues/22876) 也是因为这个原因导致的，当hibernate的ddl-auto设置为update时，每次启动时会去维护表，因为catalong为空导致检测不到表，于是去创建表，出现表存在的异常

**Comment by terrymanu** [comment]
Can not support liquibase, does anyone want to finish the issue?
