### ISSUE TITLE
The SQL_HINT algorithm cannot be set: Invalid shadow algorithm

### ISSUE THREAD

**Issue by Administrator-Xorex** [apache/shardingsphere#25099]
## Bug Report
ShardingSphere-Proxy 5.3.2

source: product.user
shadow: product_shadow.user

I have set sql_comment_parse_enable=true
![image](https://user-images.githubusercontent.com/26794746/231083593-8c4e3c7f-889d-42cb-b178-d7671103138b.png)

---

I follow the document DistSQL to set a shadow rule:
![image](https://user-images.githubusercontent.com/26794746/231083818-49cbd012-0019-4cb3-9406-99c4d6ccc37a.png)

This is my DistSQL order and responsed an ERROR 19150 (44000): Invalid shadow algorithm:
![image](https://user-images.githubusercontent.com/26794746/231083868-a3991c5a-681b-4671-ad59-a59186e1839b.png)

**Comment by RaigorJiang** [comment]
Hi @Administrator-Xorex 
Thanks for the feedback, I reproduced your problem.

The execution fails here because the verification finds that the algorithm lacks Properties, but `SQLHintShadowAlgorithm` does not need to initialize properties.

Are you interested in fixing this issue?

**Comment by RaigorJiang** [comment]
OK, I'd like to fix it, thank you!
