### ISSUE TITLE
Incorrect `HINT_INLINE` algorithm expression in RDL tests

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25131]
Hint inline sharding algorithm only accepts property named `value`, but `user_id` is used in test statement, which is incorrect.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/5668787/231345087-69d48e26-c0da-4b4a-8758-056aee377d3d.png">

```sql
'algorithm-expression'='t_order_${user_id % 2}')
```

https://github.com/apache/shardingsphere/blob/2c1bdd26cf3d163ef5fdc2615590325bc67ec867/test/it/parser/src/main/resources/sql/supported/rdl/alter.xml#L46

It should be noted that this is the case in both CREATE and ALTER statements.

**Comment by ZJJ087** [comment]
Hi @RaigorJiang , pls assign to me

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?
