### ISSUE TITLE
Heap memory increase due to sql dynamic comment 

### ISSUE THREAD

**Issue by Harif-Rahman** [apache/shardingsphere#25136]
## Bug Report

**For English only**, other languages will not accept.

Spring boot version : 2.1.5.RELEASE
JDK : amazoncorretto:8u332
ShardingSphere version : 5.2.0

We have introduced a change to pass the request id for every outgoing sql for tracing purpose.
After this change we have observed increase in jvm heap memory
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/48013254/231359262-43e71c98-61ea-46df-b52f-0ffd7528d88d.png">

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/48013254/231359312-2e6d36e7-20e7-4d53-885d-51e4f9a06fa4.png">

Statement inspector class :
public class SqlStatementInspector implements StatementInspector {
private static final int REQUEST_PATH_MAX_LENGTH = 50;
@OverRide
public String inspect(String sql) {
// add request id in sql as comment eg : select * from table t1 /* R:123 P: /api/v1 */ 

return sql + /* R: getrequestid() P: getrequestPath() */
}
}
Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by RaigorJiang** [comment]
Hi @Harif-Rahman 
Was there a similar increase in memory before adding the comment?

**Comment by tuichenchuxin** [comment]
I agree with your suspect. The cache can't be used cause of different comments. Consider changing the configuration of the SQL parser rule to reduce the cache size.
In addition, I have another idea, if `sqlCommentParseEnabled: false`, you can remove the comment information from the cached SQL of sqlPaserEngine, so that you can use the same cache even if you comment different SQL.

**Comment by Harif-Rahman** [comment]
@tuichenchuxin 
i used sqlCommentParseEnabled as false and this is my configuration for that

    CacheOption parseTreeCacheOption = new CacheOption(128, 1024L);
    CacheOption sqlStatementCacheOption = new CacheOption(2000, 65535L);
    Collection<RuleConfiguration> ruleConfigurations = new ArrayList<>();
    ruleConfigurations.add(shardingRuleConfig);
    ruleConfigurations.add(new SQLParserRuleConfiguration(false, parseTreeCacheOption, sqlStatementCacheOption));


But the sql query going to mysql is going without comments itself but ideally we need to ignore only on parse and we need to pass the actual sql with comments to mysql right ?

**Comment by tuichenchuxin** [comment]
If it is false, then shardingsphere will not care about the content of comments other than /*SHARDINGSPHERE_HINT*/. You can check whether the SQL entered into the shardingsphere has comment information. If you use mysql-client, you need to add `-c` parameter to pass comments

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
