### ISSUE TITLE
logSlowQuery should print sql instead of statement.toString()

### ISSUE THREAD

**Issue by always-busy** [apache/shardingsphere#25154]
### Which version of ShardingSphere did you use?
shardingsphere5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Actually，logSlowQuery method should print sql 

### Actual behavior
SlowQuery: 19621 milliseconds. SQL: 'org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement@714ccc92'

**Comment by Pace2Car** [comment]
Please provide more information to troubleshoot.
