### ISSUE TITLE
Compiled shardingsphere proxy startup error

### ISSUE THREAD

**Issue by zljaaa** [apache/shardingsphere#25155]
bin/start.sh -v
we find java version: java8, full_version=1.8.0_341, full_path=/home/merce/app/jdk1.8.0_341/bin/java
ShardingSphere-5.3.2-SNAPSHOT
Commit ID: dirty-d6c42214da3af888af040e4b758795e0c4c7cd11
Commit Message: Migrate openjdk to eclipse-temurin (#23487)
Branch: master
Build time: 2023-02-24T17:15:51+0800

![image](https://user-images.githubusercontent.com/20503072/231737745-9b418221-b329-4801-993f-b30793e85d82.png)

**Comment by zljaaa** [comment]
add a module in features，The code can be started successfully, but not compiled

**Comment by TeslaCN** [comment]
Could you try using official 5.3.2 release?

**Comment by TeslaCN** [comment]
Close due to no response.
