### ISSUE TITLE
Unify the format of `jdbc:opengauss`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25162]
There are now `jdbc:openGauss` and `jdbc:opengauss` in the project, they are functionally equivalent, but this will confuse the reader.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/5668787/231936191-9d2e026b-82f8-4e20-a30d-197085d6ad8d.png">

We should unify the style and use lowercase, refer to `jdbc:postgresql`

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5668787/231936154-3160b582-f220-4ee4-a354-f9d9d304ae4b.png">

**Comment by LeeGuoPing** [comment]
Can you assign it to me

**Comment by zhaojinchao95** [comment]
> Can you assign it to me

Good job!
