### ISSUE TITLE
在使用5.12版本进行 left join 联表查询时，路由失败

### ISSUE THREAD

**Issue by lmandy** [apache/shardingsphere#25167]
SQL语句如下，其中2个表是绑定关系：
SELECT
	pd.id,
	pde.ewallet_order_id
FROM
	payment_dynamicaccountinfo pd
LEFT JOIN payment_dynamicaccountinfo_extra pde ON pd.id = pde.payment_dynamicaccountinfo_id
WHERE
	1 = 1
AND pd.dynamic_date >= '2023-01-01 00:00:00'
当前使用版本是5.12，我查看了当前最新的版本也是这个问题
通过查看源码得到原因是因为TablesContext这个类中tableNames属性是一个HashSet类型，导致表的顺序发生了变化
![image](https://user-images.githubusercontent.com/16572623/231988663-eef55ddc-5c0f-40eb-819f-ae56fbebfbb3.png)

之前使用的版本是4.1.1，而在4.1.1这个版本已经解决了的
![image](https://user-images.githubusercontent.com/16572623/231989145-bb8fa619-d500-4562-b070-01614826631c.png)

我找到了之前的lssues   https://github.com/apache/shardingsphere/issues/866

那这个问题是已经解决了，还是我的配置问题

**Comment by zhaojinchao95** [comment]
@lmandy Hi, please translate your question to english and submit a new issue, i close it first.

**Comment by lmandy** [comment]
OK
