### ISSUE TITLE
XA transaction does support MySQL8.x version

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#25186]
version: ShardingSphere-proxy-5.2.1
question: ShardingSphere-proxy XA Atomikos transaction does support MySQL8.x version?

**Comment by FlyingZC** [comment]
@koala775 Hi, XA transactions support MySQL 8.x version, please provide detailed information.

**Comment by koala775** [comment]
We prepare to deploy product.The test env use the MySQL5.x.The app with XA transtraction is work well.But ,the product env is use MySQL8.x, we worry is not work well. Beacuse we find MySQL8.x some xa variables have no.Such as ,
the MySQL5.x have this,but MySQL8.x hava no.
![image](https://user-images.githubusercontent.com/35438579/232370450-71ae59b2-369f-48c2-a324-5410ea6cea76.png)

**Comment by koala775** [comment]
@FlyingZC Support MySQL8.x, Do we need config something?

**Comment by FlyingZC** [comment]
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/19788130/232773440-29d1dcf9-320f-48a9-9081-d76eef3337b1.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/19788130/232774521-f5528344-7db1-454d-bb5b-9f280f915797.png">
https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_support_xa
https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html
@koala775 The `innodb_support_xa` variable has been removed in mysql8.

**Comment by FlyingZC** [comment]
Closed due to no reply.
