### ISSUE TITLE
Re-design for ShardingSphere groovy expr

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25184]
1. Add the `shardingsphere-infra-expr` module for put all groovy related logics here.
2. Add the `shardingsphere-infra-expr-spi` sub-module, which contains the `JVMInlineExpressionParser` interface that can be used by each sub-module.
3. Add the `shardingsphere-infra-expr-core` sub-module, which contains the `InlineExpressionParser` and the logic for copying bytecode in the POM file.
4. Add the `shardingsphere-infra-expr-hotsopt` and `shardingsphere-infra-expr-espresso` sub-modules, where the latter can depend on the former.
5. Consider using ByteBuddy to simplify the implementation of jar copy and reflection. (Optional)

**Comment by linghengqian** [comment]
- I work on this issue.

**Comment by terrymanu** [comment]
Great
