### ISSUE TITLE
Build failed with error Could not find resource 'src/resources/spotless/java.xml' if working dir is not root of ShardingSphere

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#25190]
### Which version of ShardingSphere did you use?

master - e4d0557d5039dc1dce2c8d8c8fe9eb06b85aa1ac

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Failed:
```bash
% pwd
/home/wuweijie/projects/shardingsphere/sql-parser/dialect/mysql

% mvn clean install -q -DskipTests
```

This worked:
```bash
% pwd
/home/wuweijie/projects/shardingsphere

% mvn clean install -f sql-parser/dialect/mysql/pom.xml -q -DskipTests
```

### Expected behavior

Build specific modules successfully.

### Actual behavior

```
% pwd
/home/wuweijie/projects/shardingsphere/sql-parser/dialect/mysql
% mvn clean install -q -DskipTests
Running `/home/wuweijie/projects/shardingsphere/mvnw`...
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply (default) on project shardingsphere-sql-parser-mysql: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply failed: Unable to locate file with path: src/resources/spotless/java.xml: Could not find resource 'src/resources/spotless/java.xml'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

**Comment by wuxihao01** [comment]
Hi @TeslaCN ，pls assign to me

**Comment by TeslaCN** [comment]
> Hi @TeslaCN ，pls assign to me

Welcome.

**Comment by wuxihao01** [comment]
Hi @TeslaCN ,I'm a newcomer for shardingsphere, and I'm interested in this problem.  How can I start about this problem?

**Comment by wuxihao01** [comment]
Thanks for your advice, I am trying to fix it now

**Comment by wuxihao01** [comment]
Hi, @TeslaCN , I try to fix the bug, now i am not receive error message when running the `mvn clean install -q -DskipTests`  in the  `/shardingsphere/sql-parser/dialect/mysql`.  Does this mean that the problem has been fixed

**Comment by wuxihao01** [comment]
Hi, @TeslaCN , I try to fix `pom.xml,` now i am not receive error message when running the mvn clean install -q -DskipTests in the /shardingsphere/sql-parser/dialect/mysql. Does this mean that the problem has been fixed

**Comment by wuxihao01** [comment]
Hi, @TeslaCN , I try to fix `pom.xml`, now i am not receive error message when running the `mvn clean install -q -DskipTests` in the `/shardingsphere/sql-parser/dialect/mysql.` Does this mean that the problem has been fixed
<img width="510" alt="c00d5d36e882be5fe45adc0743ec4c2" src="https://user-images.githubusercontent.com/43370512/233775568-ce76acfa-2d94-4a13-8738-e30959eff7c6.png">

**Comment by TeslaCN** [comment]
> Hi, @TeslaCN , I try to fix `pom.xml`, now i am not receive error message when running the `mvn clean install -q -DskipTests` in the `/shardingsphere/sql-parser/dialect/mysql.` Does this mean that the problem has been fixed
> <img width="510" alt="c00d5d36e882be5fe45adc0743ec4c2" src="https://user-images.githubusercontent.com/43370512/233775568-ce76acfa-2d94-4a13-8738-e30959eff7c6.png">
> 

Yes. Please submit a PR.

**Comment by wuxihao01** [comment]
> > Hi, @TeslaCN , I try to fix `pom.xml`, now i am not receive error message when running the `mvn clean install -q -DskipTests` in the `/shardingsphere/sql-parser/dialect/mysql.` Does this mean that the problem has been fixed
> > <img alt="c00d5d36e882be5fe45adc0743ec4c2" width="510" src="https://user-images.githubusercontent.com/43370512/233775568-ce76acfa-2d94-4a13-8738-e30959eff7c6.png">
> 
> Yes. Please submit a PR.

Thank for your help, i have submit the PR.
