### ISSUE TITLE
navicat无法连接Sharding-Proxy

### ISSUE THREAD

**Issue by zhonghuafy** [apache/shardingsphere#25211]
Sharding-Proxy版本：Version: 5.3.2
jdk版本：Java HotSpot(TM) 64-Bit Server VM 18.9
系统：Windows 10 专业版
mysql版本：8.0.26
navicat版本：15.0.9 - Premium

使用命令行可以正常连接Sharding-Proxy：
![commond line connect proxy](https://user-images.githubusercontent.com/3118819/232740718-693cf879-d649-4d11-aaac-9b390ef40170.PNG)

使用navicat可以测试连接成功：
![navicat connect proxy](https://user-images.githubusercontent.com/3118819/232740907-11a9d7c3-6af1-460e-b516-f576b2b83d93.PNG)

但是打开连接报错：
![navicat open connect proxy](https://user-images.githubusercontent.com/3118819/232741911-9cfd4ef1-685f-4cdf-80d6-168d0f804886.PNG)

控制台日志：
![navicat open connect proxy error](https://user-images.githubusercontent.com/3118819/232743377-8e41d48e-a1d2-4364-8dbe-1ec53915edfc.PNG)

server.yaml唯一的配置：
```authority:
  users:
    - user: sharding@%
      password: sharding
  privilege:
    type: DATABASE_PERMITTED
    props:
      user-database-mappings: sharding@%=sharding_proxy
```

config-sharding.yaml的全部配置：
```databaseName: sharding_proxy
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/dn1?serverTimezone=UTC&useSSL=false
    username: risk
    password: riskpassword
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/dn2?serverTimezone=UTC&useSSL=false
    username: risk
    password: riskpassword
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/dn4?serverTimezone=UTC&useSSL=false
    username: risk
    password: riskpassword
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_com:
    url: jdbc:mysql://127.0.0.1:3306/comm?serverTimezone=UTC&useSSL=false
    username: risk
    password: riskpassword
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    auto_main_order:
      actualDataNodes: ds_${0..2}.auto_main_order
      databaseStrategy:
        standard:
          shardingColumn: partner_id
          shardingAlgorithmName: boundary-range
      tableStrategy:
        none: 

  shardingAlgorithms:
    boundary-range:
      type: BOUNDARY_RANGE
      props:
        sharding-ranges: 10, 30, 
```

相似问题：[windows部署shardingsphere-proxy,启动成功，使用navicat连接报错](https://community.sphere-ex.com/t/topic/1175)
相似问题：[navicat连接ShardingSphere分表分库插件的坑](https://blog.csdn.net/W07028057/article/details/122074138)

**Comment by RaigorJiang** [comment]
Hi @zhonghuafy 
Welcome to Apache ShardingSphere community, but only **English** is accepted here.
I will close this issue, please submit a new one.
Thank you!
