### ISSUE TITLE
Add unit test for ShardingLoadDataStatementValidator and ShardingLoadXMLStatementValidator

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#25232]
This issue is to add unit tests for the ShardingLoadDataStatementValidator and  ShardingLoadXMLStatementValidator, it includes the following subtasks:

- [ ] ShardingLoadDataStatementValidator#preValidate
- [ ] ShardingLoadXMLStatementValidator#preValidate

**Comment by liuxiaocs7** [comment]
Hi, @strongduanmu, i want to have a try, plz assign to me, thanks!

**Comment by strongduanmu** [comment]
@liuxiaocs7 Welcome.

**Comment by liuxiaocs7** [comment]
Hi, @strongduanmu, thanks for your revise(#25248), the code looks more clear and concise, I would like to ask why the extra space/Tab is needed

![image](https://user-images.githubusercontent.com/42756849/233240799-9e296613-9935-468d-81cb-d28a7da74981.png)

BTW, could you tell me where can I continue to learn the code norms of the community?

**Comment by strongduanmu** [comment]
Hi @liuxiaocs7, can you read ShardingSphere code conduct first - https://shardingsphere.apache.org/community/en/involved/conduct/code/. Besides, you can execute `mvn spotless:apply` to format code.

**Comment by liuxiaocs7** [comment]
> Hi @liuxiaocs7, can you read ShardingSphere code conduct first - https://shardingsphere.apache.org/community/en/involved/conduct/code/. Besides, you can execute `mvn spotless:apply` to format code.

Got it, thanks!
