### ISSUE TITLE
when i login to proxy server and execute 'use database' ,always 'SHOW COLUMNS FROM table' 

### ISSUE THREAD

**Issue by young138120** [apache/shardingsphere#25247]
I deploy the proxy server with 5.3.2 version and I defind  database with many of datasource
start the proxy server successful

but，when i login proxy server by mysql client  and execute comand 'use database'
it will log like this：
`
[INFO ] 2023-04-20 08:56:55.693 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SHOW COLUMNS FROM sy_fanwei FROM jn_proxy_db
[INFO ] 2023-04-20 08:56:55.693 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_now ::: SHOW COLUMNS FROM sy_fanwei 
[INFO ] 2023-04-20 08:56:55.744 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SHOW COLUMNS FROM or_rescue_order_201909 FROM jn_proxy_db
[INFO ] 2023-04-20 08:56:55.744 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_now ::: SHOW COLUMNS FROM or_rescue_order_201909 
[INFO ] 2023-04-20 08:57:02.670 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SHOW COLUMNS FROM sy_user_info FROM jn_proxy_db
[INFO ] 2023-04-20 08:57:02.670 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_now ::: SHOW COLUMNS FROM sy_user_info 
[INFO ] 2023-04-20 08:57:02.762 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Logic SQL: SHOW COLUMNS FROM or_pay_record FROM jn_proxy_db
[INFO ] 2023-04-20 08:57:02.762 [Connection-5-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_now ::: SHOW COLUMNS FROM or_pay_record 
`
show columns all of  table in the database，why is it do that？

**Comment by strongduanmu** [comment]
This sql is sent by mysql client, you can use ` mysql -u root -h 127.0.0.1 -P 3307 -proot -c -A` to login Proxy.

**Comment by tuichenchuxin** [comment]
I think these statements are sent by the client.

**Comment by TeslaCN** [comment]
Try using `mysql` with `-A` option.

**Comment by young138120** [comment]
3Q for everybody 
it is work for me，close the issue
by the way ，shardingsphere has any weixin chat group to communicate ？
i have some of question about how to correct use the shardingsphere proxy，such as ，how to design sharding，and how to config the default  datasource ， why is it not work that sharding datasource table join single table and so on。。
