### ISSUE TITLE
Can Sharding support this SQL?

### ISSUE THREAD

**Issue by Crackersssss** [apache/shardingsphere#25294]
### Is your feature request related to a problem?
yes
### Describe the feature you would like.
sql that supports mysql；
The meaning of the SQL is: the SQL query query from the table t_select_base_test_1 whether the pk (primary key) is between 1 and integer_test, sort in ascending order according to the value of integer_test, and finally return the first 10 records. The LIMIT clause limits the number of rows in the result set to 10 rows.

### version
master

### sql
``` mysql
SELECT pk BETWEEN 1 AND integer_test
FROM t_select_base_test_1
ORDER BY integer_test
LIMIT 10
```
### error 
![image](https://user-images.githubusercontent.com/45088781/233885861-63d5c3fc-8b22-431c-b88b-5bbb1020a526.png)

**Comment by strongduanmu** [comment]
Hi @Crackersssss, can you provide information according to issue template?

**Comment by Crackersssss** [comment]
> Hi @Crackersssss, can you provide information according to issue template?

sry,Do you need any other information?:)

**Comment by strongduanmu** [comment]
Yes, such as ShardingSphere version, MySQL version.

**Comment by Crackersssss** [comment]
> Yes, such as ShardingSphere version, MySQL version.

ShardingSphere version: follow the master branch
MySQL version: 5.7.38

**Comment by Crackersssss** [comment]
It might be a problem with the syntax engine. The grammar engine only builds the syntax tree of between, and does not process between in the visitor.:)

**Comment by strongduanmu** [comment]
Yes, we will optimize it.

**Comment by strongduanmu** [comment]
@iamhucong Of course, you can try to solve it.

**Comment by strongduanmu** [comment]
Hi @Crackersssss, @iamhucong help fix this bug, can you test it with master branch?

**Comment by Crackersssss** [comment]
> Hi @Crackersssss, @iamhucong help fix this bug, can you test it with master branch? Besides, can you modify issue name for search friendly?
ok i changed the question name
