### ISSUE TITLE
mybatis cross-database joint query java.sql.SQLException: exception while executing query: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by China-Uncle** [apache/shardingsphere#25320]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core</artifactId>
                <version>5.3.2</version>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Actual behavior

![Snipaste_2023-04-25_15-59-52](https://user-images.githubusercontent.com/39592981/234213271-a20e1b9a-c48b-4572-b0b8-f2b4c23ccaa7.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
`database1:
CREATE TABLE member (
id tinyint(11) unsigned NOT NULL,
custom_id tinyint(11) unsigned NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

database2:
CREATE TABLE info (
id int(11) unsigned NOT NULL AUTO_INCREMENT,
custom_id int(11) unsigned NOT NULL,
`update_time` datetime 
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

Use mybatis parameterized query
public class MemberQuery{
 private Integer id;
 private String update_time;
}
sql:
select * from member inner join info on member.custom_id=info.custom_id where  member.id =#{id}   and info.update_time &gt #{update_time}   
No exception if you don't use parameterized query`
sql:
select * from member inner join info on member.custom_id=info.custom_id where  member.id =${id}   and info.update_time &gt ${update_time}

**Comment by linghengqian** [comment]
- I'm not sure if this is an unprocessed case of ResultSet. Can you provide a minimum reproducible example through Git?

- Displaying a log with images is difficult to read. Can you format this part of the log using Github's markdown syntax? Reference resources https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code .

**Comment by China-Uncle** [comment]
> * I'm not sure if this is an unprocessed case of ResultSet. Can you provide a minimum reproducible example through Git?
> * Displaying a log with images is difficult to read. Can you format this part of the log using Github's markdown syntax? Reference resources https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code .

Hello, the demo is at https://github.com/China-Uncle/sharding-demo.git
The sql statement is in README.md

**Comment by linghengqian** [comment]
- I will verify this issue later.

**Comment by linghengqian** [comment]
- @China-Uncle Late reply, I just completed the minified verification at https://github.com/linghengqian/sharding-demo/commit/c1ada5bc00ecc527c580fa1bb70a3cd32476e0cc a while ago.
- @strongduanmu For the case where `sql-federation-type` is `ORIGINAL` or `ADVANCED`, I noticed that when the PreparedStatement does not carry parameters, the unit test executes normally. When PreparedStatement carries parameters, unit test execution fails. I was wondering if there is a known issue tracking this problem?
- The minimal unit testing and verification process is located at https://github.com/linghengqian/sharding-demo .

**Comment by linghengqian** [comment]
- I updated this Example to Apache ShardingSphere 5.4.0 in https://github.com/linghengqian/sharding-demo/commit/0a56737eb0628aaa8f334fa3c04fa18bcdba37ee and https://github.com/linghengqian/sharding-demo , both unit tests now fail, which exhibits new inconsistent behavior with 5.3.2. I will reopen my investigation into this issue.

- Some `sqlFederation`-related material is located in https://github.com/apache/shardingsphere/issues/26011.

**Comment by linghengqian** [comment]
- I found the problem in https://github.com/apache/shardingsphere/pull/28279 and https://github.com/linghengqian/sharding-demo/commit/e0927a4a30a62de1f7baee8c8000c770cd953076. Apache Calcite 1.32 does not support the `TIMESTAMP_TRUNC` function, which was added in Calcite 1.33.
