### ISSUE TITLE
getGeneratedKeys()  Oracle ROWID not supported ->Comparable<?> resultSet.getObject(1) 

### ISSUE THREAD

**Issue by yuzx88** [apache/shardingsphere#25347]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
insert data
### Actual behavior
Error getting generated key or setting result to parameter object. Cause: java.lang.ClassCastException: oracle.sql.ROWID cannot be cast to java.lang.Comparable
### Reason analyze (If you can)
getGeneratedKeys not support oracle.sql.ROWID
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/40666803/234767227-4edfe93e-284e-48ff-9562-4d2a1d84306d.png)
The data can be inserted successfully, but an exception will be thrown. Please tell me how to handle this exception thanks!

**Comment by sandynz** [comment]
@yuzx88 thanks for your feedback.

@strongduanmu Could you help to verify whether it works or not

**Comment by wangbaiwang123** [comment]
问题解决了吗

**Comment by wangbaiwang123** [comment]
问题解决了，是因为Oracle使用了mybatis plus自动生成主键导致的，表里面也没有主键。加了主键，改成雪花算法生成id手动set后就正常了，
![image](https://github.com/apache/shardingsphere/assets/43299969/1d70b2f7-93bb-47be-9328-2cae3cd391a8)
