### ISSUE TITLE
Add test cases for YamlReadwriteSplittingRuleConfigurationSwapper

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25353]
Please reference `YamlEncryptRuleConfigurationSwapperTest`

**Comment by tobehardest** [comment]
I will do this.

**Comment by strongduanmu** [comment]
@tobehardest Welcome.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by tobehardest** [comment]
> Will this issue be completed before June 15 which is the final date of version 5.4.0?

Sorry, there are too many things before, I will finish him today.
