### ISSUE TITLE
Add test cases for YamlShadowRuleConfigurationSwapper and YamlShadowTableConfigurationSwapper

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25354]
Please reference `YamlEncryptRuleConfigurationSwapperTest`

**Comment by Sakuragi27** [comment]
Hello, I want to try, can you give me?

**Comment by tristaZero** [comment]
@Aryex82 Welcome! I assigned it to you.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by Aryex82** [comment]
@boyjoy1127 Thank you for the follow up. Since this is my first task in this project I would like some more time for this task. Is it possible to move it to next release?

**Comment by wgy8283335** [comment]
> @boyjoy1127 Thank you for the follow up. Since this is my first task in this project I would like some more time for this task. Is it possible to move it to next release?

OK
