### ISSUE TITLE
Add test cases for YamlShardingRuleConfigurationSwapper and other classes in same package

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25356]
Add test cases for:

- [ ] YamlShardingRuleConfigurationSwapper
- [ ] ShardingRuleConfigurationConverter
- [x] YamlKeyGenerateStrategyConfigurationSwapper
- [ ] YamlShardingAuditStrategyConfigurationSwapper
- [ ] YamlShardingStrategyConfigurationSwapper
- [x] YamlShardingAutoTableRuleConfigurationSwapper
- [ ] YamlShardingTableReferenceRuleConfigurationConverter
- [ ] YamlShardingTableRuleConfigurationSwapper

Please reference `YamlEncryptRuleConfigurationSwapperTest`

**Comment by itsAfnanAlam** [comment]
Hello! I'm interested in contributing and I noticed that issue #25356 is still open. Is it okay if I work on this issue?

**Comment by strongduanmu** [comment]
@itsAfnanAlam Of course, I just assign this issue to you.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by shubham-j-sde** [comment]
Hi, Can I take this Up?

**Comment by shubham-j-sde** [comment]
Hello, can you please help with review of tests so far. will be helpful to avoid possible mistakes in remaining cases.

**Comment by shubham-j-sde** [comment]
can you plz review them now. I have kept different PR's for reqd. 8 tests to keep commit flow clean.
Thank you!

**Comment by terrymanu** [comment]
@shubham-j-sde Thank you for doing a great job. Your code is elegant and the writing style is completely unified, which is a real pleasure to read. Welcome to contribute more!

**Comment by shubham-j-sde** [comment]
Thank you! I'd love that
