### ISSUE TITLE
Increment task failed when using table without unique keys of migration

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#25362]
## Bug Report

When migration table without primary key,  increment task failed because of delete records parse failed

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/101622833/234808310-160aa751-9a9a-458a-82fc-dadad8739682.png">

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/101622833/234809715-1d69fe32-a4a8-4146-8172-35c5f47d6637.png">

### Which version of ShardingSphere did you use?

master 

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

**Comment by sandynz** [comment]
Fixed by #25345
