### ISSUE TITLE
Add unit tests for ShardingSphereTable

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#25361]
This issue is to add unit tests for the ShardingSphereTable class, it includes the following subtasks:

- [ ] ShardingSphereTable#containsColumn
- [ ] ShardingSphereTable#containsIndex
- [ ] ShardingSphereTable#getColumn
- [ ] ShardingSphereTable#getColumns
- [ ] ShardingSphereTable#getConstraints
- [ ] ShardingSphereTable#getIndex
- [ ] ShardingSphereTable#getIndexes
- [ ] ShardingSphereTable#putColumn
- [ ] ShardingSphereTable#putIndex
- [ ] ShardingSphereTable#removeIndex

**Comment by 100paperkite** [comment]
Can I work on this? :)

**Comment by strongduanmu** [comment]
@100paperkite Of course, I will assign this issue to you.
