### ISSUE TITLE
When run in Tomcat and use default Mode,has No suitable driver Excepeion

### ISSUE THREAD

**Issue by speedhao** [apache/shardingsphere#25401]
## Bug Report

Why ModeConfiguration not support config 'driverClassName'?
When I Use default Mode(it's Standalone and H2 database), and run my applicatin in Tomcat
It will throws 'No suitable driver' Exception

### Which version of ShardingSphere did you use?
5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
no Exception

### Actual behavior
has a Exception

### Reason analyze (If you can)
'HikariDataSource' will get driver by 'DriverManager',although DriverManager has 'org.h2.Driver',but it's ClassLoader is 'java.net.URLClassLoader'
and current ClassLoader is 'ParallelWebappClassLoader',so it can't get the driver
I see the 'JDBCRepositoryPropertyKey' don't has 'driverClassName' key, and JDBCRepository.init() are no settings either.
I think this is a BUG.

**Comment by RaigorJiang** [comment]
Duplicated with #https://github.com/apache/shardingsphere/issues/23768#issuecomment-1426919566
