### ISSUE TITLE
Please resolve maven jar version conflicts

### ISSUE THREAD

**Issue by dictionaryshi** [apache/shardingsphere#25460]
Version conflicts are potentially dangerous 
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-transaction-xa-core</artifactId>
            <version>5.3.2</version>
        </dependency>

<img width="620" alt="image" src="https://user-images.githubusercontent.com/33995567/236373597-bdf52816-9b06-46e9-8132-83b645e21440.png">

**Comment by zhaojinchao95** [comment]
@dictionaryshi Are you interested in optimizing it?

**Comment by dictionaryshi** [comment]
@zhaojinchao95  Very interested, but the work is very busy and I don't have much time.

**Comment by taojintianxia** [comment]
the following action will detect the dependency conflicts and there will be someone solve it
https://github.com/apache/shardingsphere/actions/runs/9997923474/job/27635659055
