### ISSUE TITLE
Merge sql-parser and distsql-parser into the same module

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25484]
Hi community,

Currently we have a standalone `sql-parser` module, but there is also a `distsql-parser` under the `distsql` module.
Since `distsql-parser` modules depend on `sql-parser`, and they both require `antlr` components.

I suggest merging `sql-parser` and `distsql-parser` into one `parser` module.

#### Before

```
.
├── ...
├── distsql
│   ├── handler
│   ├── parser
│   └── statement
├── ...
├── sql-parser
│   ├── dialect
│   ├── engine
│   ├── spi
│   └── statement
├── ...

```

#### After

- Split `distsql-parser` into `parser-distsql-core` and `parser-distsql-engine` (`distsql-parser` has two packages called `core` and `engine` )
- Move `parser-distsql` and `parser-sql` into the `parser` module

```
.
├── ...
├── distsql
│   └── handler
├── ...
├── parser
│   ├── distsql
│   │   ├── engine
│   │   └── statement
│   └── sql
│   │   ├── dialect
│   │   ├── engine
│   │   ├── spi
│   │   └── statement
├── ...
```

In this way, we can move the definition of `antlr4-runtime` from the root pom to the new `parser` module.

The above is my idea, welcome any suggestions, thank you!

**Comment by RaigorJiang** [comment]
Currently, the `shardingsphere-parser` module already exists under the `kernel`, but it actually serves the global rule `SQL_PARSER`.
Therefore, the `shardingsphere-parser` module should be named `shardingsphere-sql-parser` to keep the same style as `shardingsphere-authority`, `shardingsphere-sql-translator`, etc.


<img width="416" alt="image" src="https://user-images.githubusercontent.com/5668787/236730173-ef69ba00-5f8e-4da9-a8ca-38b95b198856.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5668787/236730227-b9ed7d55-c491-4464-a60a-9b28c5ce5f60.png">

In the first step, I will swap the names of `shardingsphere-parser` and `shardingsphere-sql-parser`.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?
