### ISSUE TITLE
Consider adjusting the metadata structure to enable the refresh of metadata more graceful in ShardingSphere.

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#25485]
Hi community,

   We are considering adjust the metadata structure. Beacause, the ShardingSphere metadata refresh are so heavy now. Such as it 's refresh builder all global rule configuration when i changed `sqlParser` configuration. The database configuration and datasource configuration also have the same problem, so we plan to split the metadata structure to enable more fine-grained metadata refresh.

Metadata new structure:

`/namespace/rules node` : 

```
namespace
   ├──rules
       ├──authority
            ├──active_version
            ├──versions
                  ├──0
                  ├──...
       ├──transaction
            ├──active_version
            ├──versions
                  ├──0
                  ├──...
       ├──sql_parse
            |──active_version
            ├──versions
                  ├──0
                  ├──... 
```

`/namespace/props node` : 

```
namespace
   ├──props
        |──active_version
         ├──versions
               ├──0
               ├──...
```

`/namespace/metadata node` : 

```
   ├──metadata
        |──#{databaseName}
               |──data_sources
                     |──${dataSourceName}
                           |──active_version
                           ├──versions
                                ├──0
                                ├──...
               |──rules
                    |──sharding
                         |──tables
                              |──${tableName}
                                     ├──active_version
                                     ├──versions
                                          ├──0
                                          ├──...
                         |──binding_tables
                              |──${bindingTableName}
                                     |──active_version
                                     ├──versions
                                          ├──0
                                          ├──...
               |──schemas
                    |──${schema_name}
                           |──tables
                                |──${tableName}
                                     |──columns
                                          |──${columnName}
                                                |──active_version
                                                ├──versions
                                                     ├──0
                                                     ├──...
                           |──views
               |──props
                     |──active_version
                     ──versions
                         ├──0
                         ├──...
```

**Comment by Pace2Car** [comment]
I want to help with this.

**Comment by zhaojinchao95** [comment]
> I want to help with this.

Thx

**Comment by RaigorJiang** [comment]
@zhaojinchao95 @Pace2Car 
Great, metadata refresh can be more accurate after splitting, thus greatly improving refresh performance, thank you for your idea.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by Pace2Car** [comment]
No, this will be completed in the next release.

**Comment by zhaojinchao95** [comment]
> Will this issue be completed before June 15 which is the final date of version 5.4.0?

Yeah, we are working on it.

**Comment by vikiuvb** [comment]
@zhaojinchao95 Is this handled https://github.com/apache/shardingsphere/issues/24236 as part of this change? If not, I would love to contribute.

**Comment by vikiuvb** [comment]
> @zhaojinchao95 Is this handled #24236 as part of this change? If not, I would love to contribute.

@Pace2Car @RaigorJiang Can someone confirm?

**Comment by Pace2Car** [comment]
@vikiuvb Welcome! 
The metadata structure refactor is almost complete, there are still a lot of unit testing and IT needs to be supplemented, welcome to claim contributions.

Please refer : https://github.com/apache/shardingsphere/issues/26599 https://github.com/apache/shardingsphere/issues/26598

And we will continue to release related tasks, the community looks forward to your contributions.

**Comment by Pace2Car** [comment]
> @zhaojinchao95 Is this handled #24236 as part of this change? If not, I would love to contribute.

#24236 will be resolved when this is done.
