### ISSUE TITLE
One table and two routing rules are specified through code？

### ISSUE THREAD

**Issue by sxz1314** [apache/shardingsphere#25500]
I have customized a multi field sharding rule for a table, and I would like to know how to configure a MyBATIS batch SQL using mandatory routing, as not using mandatory routing will result in multiple multi field sharding rules being used. Very slow

**Comment by zhaojinchao95** [comment]
I'm not sure if this [doc](https://shardingsphere.apache.org/document/current/cn/user-manual/common-config/sql-hint/) can help you

**Comment by sxz1314** [comment]
> 我不确定这个[文档](https://shardingsphere.apache.org/document/current/cn/user-manual/common-config/sql-hint/)是否可以帮助你

I configured composite sharding through the configuration file, but I want to use mandatory routing in my program. What should I do

**Comment by FlyingZC** [comment]
You can use `/* SHARDINGSPHERE_HINT: DATA_SOURCE_NAME=ds_0 */ SELECT * FROM t_order;` to specify data source.

**Comment by sxz1314** [comment]
https://gitee.com/sxz1314/shanrdingjdbc-dynamics-rule
I wrote a demo to implement dynamic routin
