### ISSUE TITLE
metadata repository

### ISSUE THREAD

**Issue by 13145512239** [apache/shardingsphere#25512]
## Question
**Hi, we use shardingJDBC 5.3.0 version, what data is persisted by metadata? and if i don't want to use, how can i to close it ?** 
![5a3a641b3913243e2addf88074ba550](https://user-images.githubusercontent.com/109202417/236726934-055d3ff9-0110-46fe-bfcd-d85f5a80f955.png)

**Comment by Pace2Car** [comment]
Hi @13145512239, metadata refers to all necessary configurations and information when ShardingSphere runs, so it cannot be closed.

This configuration is to set how to persist metadata, which is especially important in cluster mode.

**Comment by 13145512239** [comment]
> Hi @13145512239, metadata refers to all necessary configurations and information when ShardingSphere runs, so it cannot be closed.
> 
> This configuration is to set how to persist metadata, which is especially important in cluster mode.

**Comment by 13145512239** [comment]
> Hi @13145512239, metadata refers to all necessary configurations and information when ShardingSphere runs, so it cannot be closed.
> 
> This configuration is to set how to persist metadata, which is especially important in cluster mode.

can i close it ? It doesn't seem particularly important

**Comment by Pace2Car** [comment]
> can i close it ? It doesn't seem particularly important

If you are using standalone mode, just ignore the `mode` configuration

**Comment by 13145512239** [comment]
> > can i close it ? It doesn't seem particularly important
> 
> If you are using standalone mode, just ignore the `mode` configuration

Yes,but i meet a error, it's like this https://github.com/apache/shardingsphere/issues/25405,

**Comment by Pace2Car** [comment]
This should have been resolved in #25482.

**Comment by 13145512239** [comment]
> This should have been resolved in #25482.



> This should have been resolved in #25482.

thank you, so do i need to wait for version 5.4.0 to come online ?

**Comment by Pace2Car** [comment]
> thank you, so do i need to wait for version 5.4.0 to come online ?

No, only need to introduce the dependency of h2.

**Comment by 13145512239** [comment]
> > thank you, so do i need to wait for version 5.4.0 to come online ?
> 
> No, only need to introduce the dependency of h2.

I  do this , but still error, Is it because I'm using shardingJDBC, https://github.com/apache/shardingsphere/pull/25482 used shardingProxy

**Comment by Pace2Car** [comment]
Please provide more information to help us reproduce this issue, your configuration file (please desensitize), dependency description file

**Comment by freenet-233** [comment]
> Please provide more information to help us reproduce this issue, your configuration file (please desensitize), dependency description file

Have you solved this issue?

**Comment by terrymanu** [comment]
Metadata is the kernel of ShardingSphere, cannot close or remove it.
