### ISSUE TITLE
shardingsphere proxy Database and table partitioning+read write separation+MGR highly available yaml configuration

### ISSUE THREAD

**Issue by Silecne666** [apache/shardingsphere#25530]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Could you please provide the shardingsphere proxy version 5.3.2 with database and table partitioning, read write separation, and MGR high availability yaml configuration, including dataSources configuration.According to the official document, it cannot start normally

**Comment by FlyingZC** [comment]
@Silecne666 Hi, HA has been removed because it is unstable, you can configure sharding and readwrite-splitting together.

**Comment by KevinZurant** [comment]
@Silecne666 你好,你现在已经通过shardingsphere proxy实现MGR一主多从模式下 动态切换主从数据库了吗

**Comment by limoliyas** [comment]
Has the MGR self discovery function been removed?

**Comment by terrymanu** [comment]
Sorry, Database discovery feature is not considered within the currently supported scope.
