### ISSUE TITLE
[pg]node typeorm got  feature_not_supported

### ISSUE THREAD

**Issue by susongyan** [apache/shardingsphere#25536]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

proxy

### Expected behavior
using node typeorm  execute sql  success 

### Actual behavior
got  feature_not_supported error

### Reason analyze (If you can)
pg  when using node typeorm  ,  it'll  send  flush_command(H..S)  before execute sql;   but  proxy PostgreSQLCommandExecutorFactory not support this command

```java
private static CommandExecutor getCommandExecutor(final PostgreSQLCommandPacketType commandPacketType, final PostgreSQLCommandPacket commandPacket, final ConnectionSession connectionSession,
                                                      final PortalContext portalContext) throws SQLException {
        switch (commandPacketType) {
            case SIMPLE_QUERY:
                return new PostgreSQLComQueryExecutor(portalContext, (PostgreSQLComQueryPacket) commandPacket, connectionSession);
            case PARSE_COMMAND:
                return new PostgreSQLComParseExecutor((PostgreSQLComParsePacket) commandPacket, connectionSession);
            case BIND_COMMAND:
                return new PostgreSQLComBindExecutor(portalContext, (PostgreSQLComBindPacket) commandPacket, connectionSession);
            case DESCRIBE_COMMAND:
                return new PostgreSQLComDescribeExecutor(portalContext, (PostgreSQLComDescribePacket) commandPacket, connectionSession);
            case EXECUTE_COMMAND:
                return new PostgreSQLComExecuteExecutor(portalContext, (PostgreSQLComExecutePacket) commandPacket);
            case SYNC_COMMAND:
                return new PostgreSQLComSyncExecutor(connectionSession);
            case CLOSE_COMMAND:
                return new PostgreSQLComCloseExecutor(portalContext, (PostgreSQLComClosePacket) commandPacket, connectionSession);
            case TERMINATE:
                return new PostgreSQLComTerminationExecutor();
            default:
                return new PostgreSQLUnsupportedCommandExecutor();
        }
    }
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

use node typeorm to execute pg sql

**Comment by susongyan** [comment]
i tried to add flush command executor,   it works fine for me

**Comment by FlyingZC** [comment]
@TeslaCN Hi, please have a look.

**Comment by TeslaCN** [comment]
> i tried to add flush command executor, it works fine for me

Could you submit a PR to fix this?

**Comment by susongyan** [comment]
> > i tried to add flush command executor, it works fine for me
> 
> Could you submit a PR to fix this?

ok , assign to me

**Comment by susongyan** [comment]
@FlyingZC  plz  have a look  

i don't know why  pr failed 'analyaze to sonarcloud'

**Comment by susongyan** [comment]
@TeslaCN plz have a look

i don't know why pr failed 'analyaze to sonarcloud'
