### ISSUE TITLE
Curator usage has event blocking risk.

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#25576]
Hi community,

 Currently, ShardingSphere' s curator usage has event blocking risk. because [ZooKeeper watches are single threaded](https://cwiki.apache.org/confluence/display/CURATOR/TN1), So we can't use curator thread to do something. For example, load database metadata or persist data to governance center. 

Reproduce Steps:

```
1. CREATE DATABASE sharding_db;
2. USE sharding_db;
3. REGISTER STORAGE UNIT ds_0 (
    URL="jdbc:mysql://127.0.0.1:3306/yy?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=8192&prepStmtCacheSqlLimit=8000",
    USER="root",
    PASSWORD="root",
    PROPERTIES("maximumPoolSize"=20,"minimumIdle"=1,"idleTimeout"="30000")
);
The ds_0 data source has 1k+ tables.

4. SET DIST VARIABLE sql_show = true; // sql_show is always false and need to a long time to update.
5. SHOW DIST VARIABLES;
```

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by zhaojinchao95** [comment]
This problem need to re-investigate, i will create a new issue when i figure it out.
