### ISSUE TITLE
Add an example for create encrypt rule with `ASSISTED_QUERY` and `LIKE_QUERY` in DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25587]
Ref: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule/

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by RaigorJiang** [comment]
@boyjoy1127 I removed the milestone 5.4.0, thank you!
