### ISSUE TITLE
Proxy：How to handle views that use sharding tables

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#25596]
# How to handle views that use sharding tables

for example, now there is a `t_order` table requires sharding(like `ds_${0..1}.t_order`), but there is another view that uses the sharding table `t_order`，like
```sql
CREATE 
	OR REPLACE VIEW v_order_detail ( orderId, orderDate, orderItemId, orderItemName ) AS SELECT
	t1.ID,
	t1.DATE,
	t2.ID,
	t2.NAME 
FROM
	t_order t1
	JOIN t_order_item t2 ON t1.ID = t2.orderId
```
what should I do with this view in this scenario? create this view in all dbs, or only create in one of the dbs? Is there has other way to handle it?

**Comment by FlyingZC** [comment]
You can enalbe `sql-federation-type: ADVANCED` to support cross-shard view, sql-federation is currently an experimental function.

**Comment by PeiMouRen** [comment]
@FlyingZC 
Thank you for your answer, May I ask where there are explaination and examples about the `sql-federation-type`attriubte.

**Comment by FlyingZC** [comment]
Since it is an experimental function, there is no corresponding document, you can configure `sql-federation-type: ADVANCED` to try. https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/yaml-config/props/
