### ISSUE TITLE
Add test case for JDBCContext

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#25631]

**Comment by salmansharifov** [comment]
Hi @terrymanu . Can I take that issue? What type of test is required?

**Comment by Aryex82** [comment]
Hi @terrymanu, I would like to take up this task.

**Comment by sandynz** [comment]
> Hi @terrymanu . Can I take that issue? What type of test is required?

Welcome. It's unit test. Assigned to you.

**Comment by sandynz** [comment]
Hi @Aryex82 , welcome. Could you try other good first issues, e.g.  #24662, it includes much sub-tasks.
