### ISSUE TITLE
RROR 12000 (42000): You have an error in your SQL syntax: REFRESH TABLE METADATA delivery FROM actualDataNodes  ds_0 SCHEMA jd, no viable alternative at input 'REFRESH' at line 1, position 0, near [@0,0:6='REFRESH',<809>,1:0]

### ISSUE THREAD

**Issue by yinhongke** [apache/shardingsphere#25693]
run   "REFRESH TABLE METADATA delivery FROM actualDataNodes 'delivery_20230506' ds_0 SCHEMA jdw" error

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Please provide the necessary information following the issue template.

**Comment by yinhongke** [comment]
above is my config.yml.   I don't know how to reflash actualDataNodes by distsql

**Comment by yinhongke** [comment]
"REFRESH TABLE METADATA delivery FROM actualDataNodes 'delivery_20230506' ds_0 SCHEMA test"  is my  distsql script。

**Comment by yinhongke** [comment]
I can run  “REFRESH TABLE METADATA delivery  actualDataNodes 'delivery_20230506' ds_0 SCHEMA test”  no error，but not effective

**Comment by terrymanu** [comment]
what is actualDataNodes? The SQL pattern is: `  'REFRESH' 'TABLE' 'METADATA' (tableName | tableName 'FROM' 'STORAGE' 'UNIT' storageUnitName ('SCHEMA' schemaName)?)?`

FYI: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata/
