### ISSUE TITLE
ERROR 30000 (HY000): Unknown exception: Cannot invoke "org.apache.shardingsphere.readwritesplitting.api.transaction.TransactionalReadQueryStrategy.name()"

### ISSUE THREAD

**Issue by alei78910** [apache/shardingsphere#25744]
Upgrade from shardingsphere-proxy:5.3.2 self-compiled master branch to apache-shardingsphere-5.3.3-SNAPSHOT, execute 
```
CREATE READWRITE_SPLITTING RULE group_messagecenter (
WRITE_STORAGE_UNIT=ds_write_messagecenter,
READ_STORAGE_UNITS(ds_read_messagecenter),
TYPE(NAME="random")
);
```
 error message is as follows:
```
ERROR 30000 (HY000): Unknown exception: Cannot invoke "org.apache.shardingsphere.readwritesplitting.api.transaction.TransactionalReadQueryStrategy.name()" because the return value of "org.apache.shardingsphere.
readwritesplitting.api.rule.ReadwriteSplittingDataSourceRuleConfiguration.getTransactionalReadQueryStrategy()" is null
```
Corresponding to the 62 lines in the features\readwrite-splitting\core\src\main\java\org\apache\shardingsphere\readwritesplitting\yaml\swapper\YamlReadwriteSplittingRuleConfigurationSwapper.java file result.setTransactionalReadQueryStrategy(dataSourceRuleConfig.getTransactionalReadQueryStrategy ().name());

**Comment by zhaojinchao95** [comment]
@alei78910 Thank you for your feedback, we will check it.

**Comment by alei78910** [comment]
How do I set transactionalReadQueryStrategy to PRIMARY when executing 
```
CREATE READWRITE_SPLITTING RULE group_messagecenter (
WRITE_STORAGE_UNIT=ds_write_messagecenter,
READ_STORAGE_UNITS(ds_read_messagecenter),
TYPE(NAME="random")
);
```

**Comment by zhaojinchao95** [comment]
@Pace2Car @RaigorJiang Hi, is there a way?

**Comment by RaigorJiang** [comment]
Hi  @alei78910 @zhaojinchao95 
I found that the attribute `transactionalReadQueryStrategy` was recently added and cannot be configured in the DistSQL now.

We need to update DistSQL syntax.

**Comment by RaigorJiang** [comment]
Hi @alei78910 
After #25871, now we can set transactionalReadQueryStrategy  in readwrite-splitting RDL.
