### ISSUE TITLE
hintManager.setDatabaseShardingValue(0); If “shardingRuleConfig.getTables().addAll” is not configured, the “DefaultDatabaseShardingStrategy” logic is not used and the default database is used

### ISSUE THREAD

**Issue by DMzmwh** [apache/shardingsphere#25751]
version:5.2.0

   
    private ShardingRuleConfiguration createShardingRuleConfiguration() {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        HashMap<String, AlgorithmConfiguration> algorithms = new HashMap<>();

        Properties hint = new Properties();
        hint.setProperty("strategy", "HINT");
        hint.setProperty("algorithmClassName", DBHintAlgorithm.class.getName());
        AlgorithmConfiguration algorithmConfiguration = new AlgorithmConfiguration("CLASS_BASED", hint);

        Properties tableHint = new Properties();
        tableHint.setProperty("strategy", "HINT");
        tableHint.setProperty("algorithmClassName", TableHintAlgorithm.class.getName());
        AlgorithmConfiguration tableHintAC = new AlgorithmConfiguration("CLASS_BASED", tableHint);

        algorithms.put("my-hint", algorithmConfiguration);
        algorithms.put("my-table-hint", tableHintAC);

        shardingRuleConfig.setShardingAlgorithms(algorithms);
        shardingRuleConfig.getTables().addAll(this.getTableRuleConfiguration());

        shardingRuleConfig.setDefaultDatabaseShardingStrategy(new HintShardingStrategyConfiguration("my-hint"));
        shardingRuleConfig.setDefaultTableShardingStrategy(new HintShardingStrategyConfiguration("my-table-hint"));
        return shardingRuleConfig;
    }

try (HintManager hintManager = HintManager.getInstance()) {
            hintManager.setDatabaseShardingValue(0);
            waybillLogMapper.qryWaybillNos111(1,1L);
            System.out.printf("");
}

Actual SQL: dp_log_1 ::: SELECT * FROM waybill_log_log

**Comment by DMzmwh** [comment]
**version** : Previously, using 4.0.0-RC1 was fine for the business

**Comment by DMzmwh** [comment]
I want to just switch the database and manipulate the table using the actual table name without configuring “shardingRuleConfig.getTables()”

**Comment by sandynz** [comment]
Hi @DMzmwh , could you try latest version? Currently, it's [5.3.2]( https://shardingsphere.apache.org/document/5.3.2/en/user-manual/shardingsphere-jdbc/special-api/sharding/hint/ ).

**Comment by DMzmwh** [comment]
That's still the case；

**Comment by sandynz** [comment]
Hi @tuichenchuxin , could you help to have a look at it?

**Comment by tuichenchuxin** [comment]
@DMzmwh I don't quite understand what your question is? What are the expectations?

**Comment by DMzmwh** [comment]
The expectation is not to configure “shardingRuleConfig.getTables().addAll(this.getTableRuleConfiguration())”, to switch databases by “hintManager.setDatabaseShardingValue(0)”

**Comment by DMzmwh** [comment]
No logical table is configured, the actual table name is used, and only the database is switched
