### ISSUE TITLE
When shardjdbc and mybatis query mysql keywords, an Error preparing statement exception is displayed

### ISSUE THREAD

**Issue by EmiyaXzero** [apache/shardingsphere#25763]
ShardingSphere version:
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.2.1</version>
</dependency>

My mybatis mapper looks like this,The mysql keyword system was used when the table was designed for historical reasons.
When I use system in my where statement, the preparing statement exception will be reported. I can only replace system with 'system'. I know that this problem is caused by sql non-standard. However, without using shardingjdbc this problem will not occur. Will this situation be compatible in the future?

 select <include refid="Base_Column_List"></include>
        from system_project
        <where>
            state in (1,2) and system = 'oldsystem'
            <if test="projectName!=null and projectName!=''">
                and project_name like concat('%', #{projectName}, '%')
            </if>
            <if test="projectType!=null and projectType!=''">
                and project_type = #{projectType}
            </if>
            <if test="sysId!=null">
                and system_id = #{sysId}
            </if>
        </where>
        order by CREATE_TIME desc

**Comment by azexcy** [comment]
@EmiyaXzero  We all know that using keywords is not a very good way, maybe we can use escape symbols?

**Comment by sandynz** [comment]
Hi @EmiyaXzero , we've resolved some similar problems before. But i'm not sure, could you supply the full error message and stack trace? We'll verify it.

**Comment by EmiyaXzero** [comment]
> @EmiyaXzero We all know that using keywords is not a very good way, maybe we can use escape symbols?

Thanks to your suggestion, I also tried to user ` modify the mapper .xml in the project to solve this problem, but I found that if you use example to splice SQL, this problem will still occur, and it will take a long time to completely solve it.

**Comment by sandynz** [comment]
Hi @tuichenchuxin , could you help to verify the SQL parse with `system` keyword? I doesn't work on my local machine too.

**Comment by tuichenchuxin** [comment]
Sure. `system` can be supported by modify .g4 rule. I have added volunteer wanted label.
this pr should be a good example https://github.com/apache/shardingsphere/pull/19011

**Comment by tuichenchuxin** [comment]
> Hi, @EmiyaXzero , I'm a newcomer for shardingsphere, and I'm interested in this problem. Can I have a try?

sure, welcome.

**Comment by cardigan1008** [comment]
Hi @tuichenchuxin ,

I hope this message finds you well. I have been trying to modify the BaseRule.g4 file in /parser/sql/dialect/mysql/src/main/antlr4/imports/mysql to add the "SYSTEM" keyword to the identifierKeywordsUnambiguous list. However, despite adding it to the list, the test still fails. Interestingly, when I replaced "SYSTEM" with "STATUS", which is also a keyword in MySQL, the test passed.

Could you please give me some advice on this? Thank you for your time and consideration.

Here is my test:
```xml
<sql-case id="select_with_keyword_system" value="SELECT * FROM vtx_project WHERE system = ?" />

<select sql-case-id="select_with_keyword_system" parameters="0">
    <from>
        <simple-table name="vtx_project" start-index="14" stop-index="24" />
    </from>
    <projections start-index="7" stop-index="7">
        <shorthand-projection start-index="7" stop-index="7" />
    </projections>
    <where start-index="26" stop-index="41">
        <expr>
            <binary-operation-expression start-index="32" stop-index="41">
                <left>
                    <column name="system" start-index="32" stop-index="37"/>
                </left>
                <operator>=</operator>
                <right>
                    <literal-expression value="0" start-index="41" stop-index="41"/>
                    <parameter-marker-expression parameter-index="0" start-index="41" stop-index="41"/>
                </right>
            </binary-operation-expression>
        </expr>
    </where>
</select>
```
The error:
org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: SELECT * FROM vtx_project WHERE system = 0, no viable alternative at input 'SELECT*FROMvtx_projectWHEREsystem' at line 1, position 32, near [@5,32:37='system',<689>,1:32]

**Comment by tuichenchuxin** [comment]
@cardigan1008 I think add `System` to BaseRule.g4. identifierKeywordsUnambiguous will be work.

**Comment by cardigan1008** [comment]
@tuichenchuxin Thanks. But that’s exactly how I modified BaseRule.g4. But the test failed🥲 When I replaced "SYSTEM" with "STATUS", which is also a keyword in MySQL, the test passed. That confuses me.
