### ISSUE TITLE
Spring Boot(Fat jar) fails to start in stand-alone mode when using JDBC

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#25784]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

JDBC
### Expected behavior

success
### Actual behavior

![image](https://github.com/apache/shardingsphere/assets/16010265/d515d23e-bc9b-4212-bd69-ea8a49f8261c)

### Reason analyze (If you can)

Unable to read the `H2.xml` file
Related PR: https://github.com/apache/shardingsphere/pull/25161

**Comment by zhaojinchao95** [comment]
@jiangML Hi, are you interested fix it?
