### ISSUE TITLE
proxy update pg json field failed 

### ISSUE THREAD

**Issue by susongyan** [apache/shardingsphere#25838]
### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy 

### Expected behavior
update json field success 

### Actual behavior
org.postgresql.util.PSQLException: ERROR: column "xx" is of type json but expression is of type character varying

proxy seems to treat json as text in backend

### Reason analyze (If you can)
in "bind" phase,  actual  parameter is not parsed correctly 

 PostgreSQLComBindPacket#getTextParameters doesn't  deal  with PostgreSQLColumnType.POSTGRESQL_TYPE_JSON
<img width="1364" alt="image" src="https://github.com/apache/shardingsphere/assets/17156143/16a17fd6-bb38-4a20-9b2c-d3cd08a63621">

expected parameter object(i tried to fix myself):      update success 
<img width="1396" alt="image" src="https://github.com/apache/shardingsphere/assets/17156143/9cd95229-ba80-4cda-b615-8db804feb1da">

**Comment by sandynz** [comment]
Hi @susongyan , thanks for your feedback.

Some questions:

1, How you set parameter for PreparedStatement when exception occur, is there example code

2, What's the workaround that make it work

**Comment by susongyan** [comment]
code: 

using jdbc to update    json field 'alert_persons'

String sql = "UPDATE t_alert_rule SET alert_persons = ?, update_time = CURRENT_TIMESTAMP WHERE id IN (?) RETURNING update_time";
        try (Connection conn = dataSource.getConnection()) {
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            PGobject jsonObject = new PGobject();
            jsonObject.setType("json");
            jsonObject.setValue(JSON.toJSONString(Collections.singletonList("test)")));
            preparedStatement.setObject(1, jsonObject);
            preparedStatement.setLong(2, 130);
            preparedStatement.execute();
        }

**Comment by susongyan** [comment]
what i do to  fix this case is 

add case  json in  org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.extended.bind.PostgreSQLComBindPacket#getTextParameters(java.lang.String, org.apache.shardingsphere.db.protocol.postgresql.packet.command.query.extended.PostgreSQLColumnType)
 
```java
  case POSTGRESQL_TYPE_JSON:
                return PostgreSQLTextJsonUtils.parse(textValue);
            default:
```
PostgreSQLTextJsonUtils.parse returns PGobject type=json

**Comment by sandynz** [comment]
@susongyan Nice. Could you submit a PR to improve it?

And a possible workaround:
- Add `&stringtype=unspecified` in JDBC url parameter

**Comment by susongyan** [comment]
> 

ok ,i'll submit a pr;     assign it to me plz

**Comment by susongyan** [comment]
ok ,i'll submit a pr; assign it to me plz
@sandynz

**Comment by sandynz** [comment]
> ok ,i'll submit a pr; assign it to me plz @sandynz

Well, done
