### ISSUE TITLE
MySQL 8.0 ALTER TABLE RENAME COLUMN is not parsed into AlterTableStatement

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#25852]
### Which version of ShardingSphere did you use?

master - d9b4780b4010f1554a1b094972b60181bebf046b

### Expected behavior

```sql
alter table f rename column new_col to renamed_col
```

### Actual behavior

There is nothing about rename column in AlterTableStatement.

![image](https://github.com/apache/shardingsphere/assets/20503072/5190ac1d-e6d6-4c11-85b9-022e889f11c4)

**Comment by zihaoAK47** [comment]
@TeslaCN Hi, I would like to try to solve this problem

**Comment by TeslaCN** [comment]
Welcome @zihaoAK47

**Comment by TeslaCN** [comment]
Hi @zihaoAK47 
Here is a similar issue. Would you like to fix this? https://github.com/apache/shardingsphere/issues/25862
