### ISSUE TITLE
[DistSQL] Use SPI to refactor RULBackendHandler

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25868]
Refer to https://github.com/apache/shardingsphere/issues/23854

Use SPI to refactor RULBackendHandler, and remove the static map.

<img width="638" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/4303ae7d-cf61-408a-867b-630f657083ca">

**Comment by yx9o** [comment]
Hi @RaigorJiang , I want to join.

**Comment by RaigorJiang** [comment]
Thank you @yx9o 👍

**Comment by RaigorJiang** [comment]
Completed, thank you! @yx9o
