### ISSUE TITLE
Hexadecimal data cannot be encrypted？

### ISSUE THREAD

**Issue by BeCareOfZm** [apache/shardingsphere#25877]
After SQL statement execution，the record is not encrypted
example：

```
insert into `testdb`.`m_user` (`id_card_no`,`name`,`mobile`,`id`) values(x'323230363035313934373039333038313730', x'6C70', x'3138323336343833383537', 1)
```
result：
<img width="630" alt="image" src="https://github.com/apache/shardingsphere/assets/19266113/91e77ed3-fb88-48e8-ba7d-77b02a4cf768">

**Comment by sandynz** [comment]
Hi @BeCareOfZm , could you edit the issue with [template]( https://raw.githubusercontent.com/apache/shardingsphere/master/.github/ISSUE_TEMPLATE/bug-report.md )? More information is needed, e.g. version, configuration, etc

**Comment by BeCareOfZm** [comment]
> Hi @BeCareOfZm , could you edit the issue with [template](https://raw.githubusercontent.com/apache/shardingsphere/master/.github/ISSUE_TEMPLATE/bug-report.md)? More information is needed, e.g. version, configuration, etc

**tar package**:  apache-shardingsphere-5.3.2-shardingsphere-proxy-bin.tar
**version**: 5.3.2
**rule**: ```
CREATE ENCRYPT RULE t_user (
  COLUMNS(
    (
      NAME = id_card_no,
      CIPHER = id_card_no,
      ENCRYPT_ALGORITHM(
        TYPE(
          NAME = 'AES',
          PROPERTIES('aes-key-value' = '123456abc')
        )
      )
    ),
    (
      NAME = mobile,
      CIPHER = mobile,
      ENCRYPT_ALGORITHM(
        TYPE(
          NAME = 'AES',
          PROPERTIES('aes-key-value' = '123456abc')
        )
      )
    )
  ),
  QUERY_WITH_CIPHER_COLUMN = true
);
```
**create table sql**: 
`CREATE TABLE t_user (
    id INT(8) primary key, 
    mobile VARCHAR(50), 
    id_card_no VARCHAR(50)
);`

**Comment by sandynz** [comment]
Hi @tuichenchuxin , could you help to verify it?

**Comment by tuichenchuxin** [comment]
not support yet.
