### ISSUE TITLE
MySQL CREATE TABLE LIKE syntax is not parsed

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#25926]
### Which version of ShardingSphere did you use?

5.3.2

### Expected behavior

```sql
CREATE TABLE bmsql_item_new LIKE bmsql_item;
```

### Actual behavior

Found nothing about `LIKE` syntax in parse result.

![image](https://github.com/apache/shardingsphere/assets/20503072/5c8e924f-4e18-4f67-bffc-9b3ecb07ad4b)

**Comment by zihaoAK47** [comment]
@TeslaCN Hi mentor, please assign this problem to me. I will solve it after finishing the #25862 issue.   ʅ(‾◡◝)ʃ

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by TeslaCN** [comment]
Closed by #25993.
