### ISSUE TITLE
line 5:34 no viable alternative at input 'TRIM(LEADING'00'FROMdealer_scm_code'

### ISSUE THREAD

**Issue by www-haifeng** [apache/shardingsphere#25938]
**sql**
 SELECT
    reward_type AS reward_item,

    SUM(unrecharge_amount) AS unrecharge_amount,
    TRIM(LEADING '00' FROM dealer_scm_code) AS dealer_scm_code
    FROM
    rebate_account_report
    WHERE
    month_date = #{month_date} AND mcht_id = #{mcht_id} AND data_state = 1
    GROUP BY
    reward_type, dealer_scm_code

**springboot**
 //https://mvnrepository.com/artifact/org.apache.shardingsphere/sharding-jdbc-spring-boot-starter
    implementation group: 'org.apache.shardingsphere', name: 'sharding-jdbc-spring-boot-starter', version: '4.1.1'
// https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.3'
why？why？why？

**Comment by TeslaCN** [comment]
Hi @www-haifeng 
You are using a legacy version. Please upgrade to ShardingSphere 5.3.2.

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
