### ISSUE TITLE
The meaning of broadcast table.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#25957]
I learned a lot of sub-table rules, among which the meaning of broadcast table makes me puzzled.

What is the meaning of its existence, is it a function of historical legacy？

----

I guessed some of its benefits, such as disaster tolerance, fast routing, and solving spanning query problems.

- about disaster tolerance:

When a database or a table goes down, this can lead to data inconsistency or even unavailability of the entire cluster. So this advantage is excluded.

- about fast routing

Is it really better than single table routing speed?

- about solving spanning query problems

Most associative queries are merged into the Proxy's memory, and by streaming merge, etc., I don't think this improves performance much, and is a waste of physical storage space.

---

I am really troubled and need help to clear the confusion

**Comment by RaigorJiang** [comment]
Refer to https://shardingsphere.apache.org/document/current/en/features/sharding/concept/#broadcast-data-frame

The significance of the broadcast table is to facilitate join queries with big tables.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
