### ISSUE TITLE
 Seata+shardingsphere+dynamic  >>zpp

### ISSUE THREAD

**Issue by zhangpp2023** [apache/shardingsphere#26015]
## Bug Report   Using Seata+shardingsphere+dynamic  >>zpp

**For English only**, other languages will not accept.

我把shardingsphere数据源交给了dynamic数据源管理，所以我可以通告DS来切换库使用分表规则了，但是我使用了seata1.4.2版本，全局事务无法回滚我，我加了seata代理sharing数据源，可以回滚了，但是回滚的时候，把所有的分区表都查询删除了一遍，我用年月分的，按道理应该查询删除对应的分区表才是啊，请求支持；

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).
![TIM图片20230602163904](https://github.com/apache/shardingsphere/assets/134915429/78ee1fa5-73c0-4b6e-b1c3-38e48f3c8abd)

![TIM图片20230602163904](https://github.com/apache/shardingsphere/assets/134915429/fb69725a-95a5-4e17-a309-501feb6a277f)

**Comment by zhaojinchao95** [comment]
@zhangpp2023 Hi, please translate into english.

**Comment by linghengqian** [comment]
> 我加了seata代理sharing数据源

- Please provide more description of this operation. I'm afraid this violates the current design of ShardingSphere. Refer to https://github.com/apache/shardingsphere/pull/30146 .
