### ISSUE TITLE
Inconsistent order of fields in SQLParserRule, SQLParserRuleConfiguration and YamlSQLParserRuleConfiguration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#26026]
<img width="1030" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/366c5542-45b4-4054-b6f0-45ebbefadddf">

### Related classes
- SQLParserRule

- SQLParserRuleConfiguration

- YamlSQLParserRuleConfiguration

**Comment by AsfarHorani** [comment]
@RaigorJiang  Hi I am willing to contribute, can we get connect to or give me any further information regarding the issue?

**Comment by yx9o** [comment]
@AsfarHorani Hello, unify the order of the same attributes in the two classes.

**Comment by RaigorJiang** [comment]
Hi @AsfarHorani 
In fact, I listed 3 classes in the issue, 2 of them have the same order of fields, you only need to adjust the one that is different.

**Comment by AsfarHorani** [comment]
@RaigorJiang  @yx9o assign it to me

**Comment by yx9o** [comment]
@AsfarHorani Welcome
