### ISSUE TITLE
Is doSharding's collection not thread safe?

### ISSUE THREAD

**Issue by zt9788** [apache/shardingsphere#26064]
### Which version of ShardingSphere did you use?
ShardingShpere 5.3.2 JDK17

I make a custom ComplexKeysShardingAlgorithm 
in `doSharding(Collection<String> collection,
                                         ComplexKeysShardingValue<String> complexKeysShardingValue)`

I use the `collection.toArray()[0]` sometimes will throw ` Index X out of bounds for length X` when programe starting.

```
at java.util.LinkedHashMap.keysToArray(LinkedHashMap.java:545)
at java.util.HashSet.toArray(HashSet.java:368)
at ...CustomhardingAlgorithm.doSharding(CustomhardingAlgorithm.java:64)
....
```

There are very few abnormal situations that have occurred, and I have not been able to reproduce them local.

**Comment by RaigorJiang** [comment]
@zt9788 
Is it possible that your collection is empty?

**Comment by zt9788** [comment]
@RaigorJiang 
No, the Exception is ` Index 2 out of bounds for length  2` (index >0 )
and I make sure the collection is not empty (when toArray hashset will make a array length = collection.size() but if the set changed that may throw the exception

**Comment by RaigorJiang** [comment]
Did you modify the input collection in the `CustomhardingAlgorithm#doSharding` method?

**Comment by zt9788** [comment]
Code is:

I haven't do anything yet, just get index0  of them after toArray

```

    @Override
    public Collection<String> doSharding(Collection<String> collection,
                                         ComplexKeysShardingValue<String> complexKeysShardingValue) {
        if(App.getApplicationContext() == null) {
            return collection;
        }
        Set<String> shardingSuffix = new HashSet<>();
        var tablename =  collection.toArray()[0]; // here throw the Exception
...
```

**Comment by RaigorJiang** [comment]
That's really strange, there is no logic to modify this collection in ShardingSphere.
Would it be convenient for you to add logging and an `isEmpty` check before collection.toArray() ? to analyze the problem.

**Comment by zt9788** [comment]
@RaigorJiang 

I carefully checked and found that in doSharding with multiple threads, I may indeed perform an add operation on the collection (normally only for the first time), which may be the problem

Thank you very much. I will close the issue first and carefully investigate it. If it is confirmed to be a shardingshpere issue, I will open it 

It is indeed a bit strange because even modifications are still add, and I don't know why there is an out of bounds exception

Thank you again for your reply
