### ISSUE TITLE
If I use an Order-Revealing Encryption algorithm, does the Encryption feature support comparison operators?

### ISSUE THREAD

**Issue by x2zh** [apache/shardingsphere#26067]
## Question

If I use an Order-Revealing Encryption algorithm, does the Encryption feature support comparison operators for encrypted fields？such as GREATER THAN, LESS THAN, ORDER BY, BETWEEN

## reference
> [Order-Revealing Encryption](https://crypto.stanford.edu/ore/)

**Comment by strongduanmu** [comment]
If there is a suitable encryption algorithm, I think it can be supported in future.
