### ISSUE TITLE
shardingsphere-jdbc-core-spring-boot-starter5.3.1 Programming transactions causing fragmentation rules to become invalid

### ISSUE THREAD

**Issue by Daibhid666** [apache/shardingsphere#26070]
## Bug Report

The spi mechanism injects custom sharding algorithms, and the sharding rules are invalidated using spring programed transactions

### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

shardingsphere-jdbc-core-spring-boot-starter5.3.1

### Expected behavior

for example  :  insert into t_order(id,order_id,create_time) values(1,2,'2023-06-07 00:00:00')    The expected data is inserted into t_order_202306
### Actual behavior 

for example  :  insert into t_order(id,order_id,create_time) values(1,2,'2023-06-07 00:00:00')    The expected data is inserted into t_order
### Reason analyze (If you can)
Using spring@Transactional declarative transactions invalidates custom sharding rules  

The specific behavior is as described above

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![lQLPJx6aPFQHflbNARrNBiOwi7ujNq08DsAEdnsJngAwAA_1571_282](https://github.com/apache/shardingsphere/assets/10000521/d14697cb-0299-4187-b0e7-2c5a6984f604)

![lQLPJwgdIk_AxNbNAYnNA66wdLKvn0FaDN0EdnpWrkC7AA_942_393](https://github.com/apache/shardingsphere/assets/10000521/66e8901f-d40b-4c07-ba04-4b6357cebd61)

**Comment by RaigorJiang** [comment]
Hi @Daibhid666 
Please provide enough information according to the issue template, thank you!

**Comment by Daibhid666** [comment]
> **[RaigorJiang](/RaigorJiang) ** c

@RaigorJiang  The problem has been redescribed, please check

**Comment by RaigorJiang** [comment]
@Daibhid666 
According to your algorithm fragment, when an exception occurs in the `doSharding` method, it will be routed to the `t_order` table, please check if there is an error log?

**Comment by Daibhid666** [comment]
The sharding algorithm failed, the data was inserted into the t_order table, not the t_order_202306 table, and there was no error log

**Comment by RaigorJiang** [comment]
So maybe your log didn't take effect? 
From the analysis of known information, the high probability is the routing result caused by this algorithm.

**Comment by Daibhid666** [comment]
@RaigorJiang The problem is that with declarative transactions or annotated transactions, the sharding algorithm will not be called, and it will not be routed to the specified shard

**Comment by RaigorJiang** [comment]
That's weird, @Daibhid666  can you provide a demo project to investigate the issue?

**Comment by Daibhid666** [comment]
@RaigorJiang There is no possibility that the sharding rules are invalid due to dynamic data sources
 
![image](https://github.com/apache/shardingsphere/assets/10000521/c3ce0614-b394-4eef-a870-4ee9819d479c)

**Comment by RaigorJiang** [comment]
> @RaigorJiang There is no possibility that the sharding rules are invalid due to dynamic data sources

If so, you need to confirm whether the INSERT SQL uses sharding data source, maybe the transaction affects the logic of the dynamic data source.

**Comment by Daibhid666** [comment]
![image](https://github.com/apache/shardingsphere/assets/10000521/d65f405f-7a4b-42b6-80bc-53066b9ca03c)
![image](https://github.com/apache/shardingsphere/assets/10000521/f3c23089-e3be-43d9-b45b-3a38533dbd40)
![image](https://github.com/apache/shardingsphere/assets/10000521/6b1249d0-f32c-4c3d-a0b0-dabb87ae7a71)


A shardingsphere transaction manager was configured, the @Transactional annotation specified transactions, and the code switched sharding data sources, but the sharding rules still failed

**Comment by Daibhid666** [comment]
@RaigorJiang There is no api to manually call the following sharding rules to parse the sql route

**Comment by RaigorJiang** [comment]
We first need to determine whether the SQL is routed to ShardingSphereDataSource, can you provide a demo?

**Comment by Daibhid666** [comment]
@RaigorJiang Is it convenient to add a contact information for remote? demo is not available

**Comment by Daibhid666** [comment]
@RaigorJiang  Thanks for the Pointers! The problem has been located because the dynamic multi-data source configuration master data source is consistent with the shardingsphere data source and the sharding rules are invalid due to transactions

**Comment by RaigorJiang** [comment]
@Daibhid666 
Well, good news! Do you mean that when add transaction, the SQL is not routed into ShardingSphereDataSource?

**Comment by Daibhid666** [comment]
![image](https://github.com/apache/shardingsphere/assets/10000521/4fea733a-b8d8-4307-85f8-ae6eaa25f92c)
![image](https://github.com/apache/shardingsphere/assets/10000521/0ded0bd4-bad0-4ec8-b9d9-ab84870d9ce3)
![image](https://github.com/apache/shardingsphere/assets/10000521/6921720c-f903-4c09-9139-65d955603536)
@RaigorJiang The above image shows that the shardingsphere data source is first loaded, and then the shardingsphere data source is handed over to dynamic data source management. The shardingsphere data source is injected back into the spring transaction manager. Transaction not in effect

**Comment by Daibhid666** [comment]
@RaigorJiang shardingsphere-jdbc-core-spring-boot-starter5.2.1 does not support DataSourceTransactionManager transaction manager?

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated and removed in 5.3.0, please try new version and use ShardingSphere Driver.
