### ISSUE TITLE
shardingsphere-proxy5.3.2 Startup error

### ISSUE THREAD

**Issue by Daibhid666** [apache/shardingsphere#26075]
## Question

org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x10d45e323100042, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[INFO ] 2023-06-06 16:01:11.145 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
[INFO ] 2023-06-06 16:01:12.678 [main-SendThread(172.19.138.135:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server Prod-RDS/172.19.138.135:2181.
[INFO ] 2023-06-06 16:01:12.679 [main-SendThread(172.19.138.135:2181)] org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
[INFO ] 2023-06-06 16:01:12.679 [main-SendThread(172.19.138.135:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.19.138.135:58960, server: Prod-RDS/172.19.138.135:2181
[INFO ] 2023-06-06 16:01:12.680 [main-SendThread(172.19.138.135:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server Prod-RDS/172.19.138.135:2181, session id = 0x10d45e323100042, negotiated timeout = 40000
[INFO ] 2023-06-06 16:01:12.680 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
[WARN ] 2023-06-06 16:01:12.681 [main-SendThread(172.19.138.135:2181)] org.apache.zookeeper.ClientCnxn - Session 0x10d45e323100042 for server Prod-RDS/172.19.138.135:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x10d45e323100042, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[INFO ] 2023-06-06 16:01:12.782 [main-EventThread] o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED

**Comment by RaigorJiang** [comment]
It seems that the zookeeper cannot be accessed, can you try to use `zkClient` to connect to the zookeeper server to check?

**Comment by Daibhid666** [comment]
If shardingsphere-proxy is used in other versions, versions 5.3.1 to 5.3.2 can be linked properly

**Comment by RaigorJiang** [comment]
@Daibhid666 
I googled and I think there are two possibilities:
1. The client and server versions are incompatible
2. Is zookeeper clustered? The above exception may also occur when more than half of the servers in the cluster are unavailable.

**Comment by Daibhid666** [comment]
2、zookeepr  Stand-alone version
