### ISSUE TITLE
把dataSourceClassName换成了druid连接池，为什么启动还会有com.zaxxer.hikari.HikariDataSource.getConnection？

### ISSUE THREAD

**Issue by 943305417** [apache/shardingsphere#26078]
把dataSourceClassName换成了druid连接池，为什么启动还会有com.zaxxer.hikari.HikariDataSource.getConnection？
尝试过彻底移除hikari，看看日志还有没有hikari，但是排除hikari后启动就报错

**Comment by 943305417** [comment]
org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepository
调试到这个类里面，发现有hikariDataSource的属性

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, but only **English** is accepted here.
I will close this issue, please submit a new one.
Thank you!
