### ISSUE TITLE
Sharding proxy-5.1.2 SQL error reported when executing cross schema queries. Is this not supported

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#26088]
## Bug Report
problem：Executing cross schema SQL error reporting
![image](https://github.com/apache/shardingsphere/assets/41990755/0db3cb9a-ff0d-48ce-9347-8cfe182a3d84)

![image](https://github.com/apache/shardingsphere/assets/41990755/b6ae7ecc-b704-4cb2-913a-fdab3c9824a8)

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding-proxy-5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Can be executed

### Actual behavior
error

**Comment by RaigorJiang** [comment]
Hi @ThisOnly 
Are `iscs_hsbm` and `hscs_hspm` your two logic databases?
If so, you can try to enable federation query in the latest version 5.3.2, this feature is not supported in 5.1.2.

**Comment by ThisOnly** [comment]
ok,thank

**Comment by RaigorJiang** [comment]
You are welcome!
Now I will close this issue, if you still have question, please reopen it or submit a new one.
