### ISSUE TITLE
Change dataSourceClassName to druid Connection pool. Why does the startup log still have com.zaxxer.hikari.HikariDataSource.getConnection?

### ISSUE THREAD

**Issue by 943305417** [apache/shardingsphere#26084]

**Comment by 943305417** [comment]
I have tried to completely remove hikari in Maven and check if there is still hikari in the logs. However, after excluding the dependency packages of hikari, the program will report an error when starting

**Comment by zhaojinchao95** [comment]
Hi, are you using `standalone` mode?

**Comment by 943305417** [comment]
> Hi, are you using `standalone` mode?

At first, I didn't set any mode, but later I set it to Memory mode, and the startup program still appears:

'com.zaxxer.hikari.HikariDataSource.getConnection - 110 ==== HikariPool-1 - Starting...' 
and
 'com.zaxxer.hikari.HikariDataSource.getConnection - 123 ==== HikariPool-1 - Start completed.'

**Comment by 943305417** [comment]
> Hi, are you using `standalone` mode?

,here are my settings：

mode:
  type: Memory

> Hi, are you using `standalone` mode?

I am using shardingsphere version 5.3.2 and have introduced dynamic datasource spring boot starter. I am not sure if this has any impact?

**Comment by zhaojinchao95** [comment]
`5.3.2` version already removed Memory mode. you can refer to #24348

**Comment by 943305417** [comment]
> `5.3.2` version already removed Memory mode. you can refer to #24348

This problem has been resolved. After switching to cluster mode, there were no Hikari logs
