### ISSUE TITLE
Why is the parameter marking index obtained not the value of the specified shard column

### ISSUE THREAD

**Issue by java-lbb** [apache/shardingsphere#26117]
![image](https://github.com/apache/shardingsphere/assets/111548695/08670115-ef1a-4cc5-b4d8-d39999264220)

**I want to get the value of 8 indexes in the parameter list —"72023050511451639719"，but always get the value of the 0th index。**

this my configuration
![image](https://github.com/apache/shardingsphere/assets/111548695/14908fd5-bd3f-4564-829a-ebfb65c9ad7f)

this my ShardingShardingAlgorithm
`@Component("FansDetailShardingAlgorithm")
public class FansDetailShardingAlgorithm implements StandardShardingAlgorithm<String> {

    @DubboReference
    OrderDubboService orderDubboService;

    private final ConcurrentMap<String, String> map = new ConcurrentHashMap<>();
    
    @Override
    public String doSharding(Collection<String> tableNames, PreciseShardingValue<String> preciseShardingValue) {
        if (CollectionUtil.isNotEmpty(map.keySet())) {
            for (String orderId : map.keySet()) {
                String uuid = map.get(orderId);
                if (ObjectUtil.isNotNull(uuid)) {
                    return preciseShardingValue.getLogicTableName() + "_" + Math.abs(uuid.hashCode() % 50);
                } else {
                    Order order = orderDubboService.getOrder(preciseShardingValue.getValue());
                    map.put(order.getOrderId(), order.getUuid());
                    return preciseShardingValue.getLogicTableName() + "_" + Math.abs(order.getUuid().hashCode() % 50);
                }
            }
        }
        Order order = orderDubboService.getOrder(preciseShardingValue.getValue());
        map.put(order.getOrderId(), order.getUuid());
        return preciseShardingValue.getLogicTableName() + "_" + Math.abs(order.getUuid().hashCode() % 50);
    }

    @Override
    public Collection<String> doSharding(Collection<String> tableNames, RangeShardingValue<String> rangeShardingValue) {
        return tableNames;
    }

    @Override
    public void init() {

    }

    @Override
    public String getType() {
        return "CLASS_BASED";
    }
}`
![image](https://github.com/apache/shardingsphere/assets/111548695/f61bfaeb-55cf-43a1-99d9-1f4fc3c89efa)

**Comment by terrymanu** [comment]
Please refer to the issue template to provide more details for your question. for example: version

**Comment by java-lbb** [comment]
1
