### ISSUE TITLE
[New Feature] Support PostgreSQL pg_catalog.pg_aggregate table empty query

### ISSUE THREAD

**Issue by wbcfwbe** [apache/shardingsphere#26143]
# Background
This task is a subtask of issue #24662.

Hi community.
ShardingSphere is committed to providing a multi-source heterogeneous, enhanced database platform and further building an ecosystem around the upper layer of the platform.
So ShardingSphere needs to be compatible with the inquiries of the system database of various types of databases, such as MySQL, PostgreSQL, and OpenGauss.

So we want to mock all system database tables and views query, return to the empty result.

# Tasks
In this issue, we will implement the empty query of the following system tables/views:
- [ ] pg_aggregate
- [ ] pg_am
- [ ] pg_amop
- [ ] pg_amproc
- [ ] pg_attrdef

# Refer PR
You can refer to the following similar PR to complete the task.
MySQL: #25076, #25256, PostgreSQL: #25752

**Comment by Wang-qing-yang** [comment]
please assign this to me @wbcfwbe

**Comment by wbcfwbe** [comment]
> please assign this to me @wbcfwbe

Hiii, If you're hoping to learn or share, don’t hesitate to add our WeChat account: Jialin953 with the remark: Split issues.
If you have any questions, you're welcome to ask the community anything!

**Comment by FlyingZC** [comment]
The current task has been completed, please refer to the parent task #24662, I will close this issue.
