### ISSUE TITLE
Add new metadata structure for global rule

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#26165]
Hi community,

  We are refactoring metadata structure and need your participation. Refer to issue : #25485, pr : #26163 

Task list : 

- [x] Add NewYamlTransactionRuleConfigurationSwapper @LeeGuoPing 
- [x] Add NewYamlTrafficRuleConfigurationSwapper
- [x] Add NewYamlSQLTranslatorRuleConfigurationSwapper
- [x] Add NewYamlSQLParserRuleConfigurationSwapper
- [x] Add NewYamlSQLFederationRuleConfigurationSwapper
- [x] Add NewYamlSingleRuleConfigurationSwapper
- [x] Add NewYamlLoggingRuleConfigurationSwapper
- [x] Add NewYamlGlobalClockRuleConfigurationSwapper

**Comment by susongyan** [comment]
i'd like to try it

**Comment by susongyan** [comment]
how to take this issue?  directly submit pr?
