### ISSUE TITLE
Add unit test for TableNamesMapper public method

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26217]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim

This issue is to add unit tests for the TableNamesMapper class, it includes the following subtasks:

- [ ]  TableNamesMapper#contains
- [ ]  TableNamesMapper#getTableNames
- [ ]  TableNamesMapper#put
- [ ]  TableNamesMapper#remove

You can refer this pr - https://github.com/apache/shardingsphere/pull/25386 to add unit test.

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by mehboobali98** [comment]
Hi @strongduanmu, can I work on this? TIA

**Comment by strongduanmu** [comment]
@mehboobali98 Welcome. I just assign this issue to you.

**Comment by strongduanmu** [comment]
Hi @mehboobali98, any progress now?

**Comment by KonarzewskiP** [comment]
Hi @strongduanmu,
I would like to work on this issue. Please assign it to me.

**Comment by strongduanmu** [comment]
@KonarzewskiP Assigned.
