### ISSUE TITLE
DatabaseConnector call ShardingRule.getAllTables cause performance degradation

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26210]
## Background

![image](https://github.com/apache/shardingsphere/assets/10829171/17c8c109-ff23-4aa1-a9f8-080c5faeef17)

When we are on the master branch performance testing, found the following problems, DatabaseConnector ShardingRule. A lot of call getAllTables method, the method USES the TreeSet and build subdivision table every time, and broadcast table and truth table, This results in a significant drop in performance.

**Comment by boyjoy1127** [comment]
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by strongduanmu** [comment]
Yes, I will finish this task today.

**Comment by strongduanmu** [comment]
Besides, I found getParameterCount can be optimized.

![image](https://github.com/apache/shardingsphere/assets/10829171/52450617-731a-4359-9d2c-3a7a1c901554)
