### ISSUE TITLE
ShardingSphere-JDBC will support openGauss and PostgresSQL  for subdatabase？

### ISSUE THREAD

**Issue by zc2003** [apache/shardingsphere#26314]
## Question
Which version of ShardingSphere did you use?
ShardingSphere-JDBC  5.1.1 and 5.2.1

When we use two differnt database for subdatabase,  openGauss and PostgresSQL, the software run error.

ShardingSphere-JDBC will support this kind of scenario?

**Comment by RaigorJiang** [comment]
As far as I know, there is no such plan, have you tried to connect openGauss with pg driver, is it ok?
