### ISSUE TITLE
Proxy MySQL syntax error (SELECT * FROM t1) EXCEPT (SELECT * FROM t2)

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#26321]
### Which version of ShardingSphere did you use?

382c598c834310da9b692ce9cb38eba60c42d39c

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy MySQL

### Expected behavior

Query succeeded.

### Actual behavior

```
mysql> (SELECT * FROM t1) EXCEPT (SELECT * FROM t2);
ERROR 12000 (42000): You have an error in your SQL syntax: (SELECT * FROM t1) EXCEPT (SELECT * FROM t2), no viable alternative at input 'EXCEPT' at line 1, position 19, near [@6,19:24='EXCEPT',<242>,1:19]
```

https://dev.mysql.com/doc/refman/8.0/en/except.html

**Comment by zihaoAK47** [comment]
@TeslaCN Hi mentor, please assign this problem to me. I will do my best to solve it.

**Comment by TeslaCN** [comment]
@zihaoAK47  Welcome!
