### ISSUE TITLE
Question about SPISQLExecutionHook

### ISSUE THREAD

**Issue by theodoretsai** [apache/shardingsphere#26323]
## Question

```
package org.apache.shardingsphere.infra.executor.sql.hook;

import org.apache.shardingsphere.infra.database.metadata.DataSourceMetaData;
import org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader;

import java.util.Collection;
import java.util.List;

/**
 * SQL Execution hook for SPI.
 */
public final class SPISQLExecutionHook implements SQLExecutionHook {
    
    private final Collection<SQLExecutionHook> SPISQLExecutionHook = ShardingSphereServiceLoader.getServiceInstances(SQLExecutionHook.class);
    
    @Override
    public void start(final String dataSourceName, final String sql, final List<Object> params, final DataSourceMetaData dataSourceMetaData, final boolean isTrunkThread) {
        for (SQLExecutionHook each : sqlExecutionHooks) {
            each.start(dataSourceName, sql, params, dataSourceMetaData, isTrunkThread);
        }
    }
    
    @Override
    public void finishSuccess() {
        for (SQLExecutionHook each : sqlExecutionHooks) {
            each.finishSuccess();
        }
    }
    
    @Override
    public void finishFailure(final Exception cause) {
        for (SQLExecutionHook each : sqlExecutionHooks) {
            each.finishFailure(cause);
        }
    }
}

```

In the class SPISQLExecutionHook there's a sqlExecutionHooks field which loads all providers from the SPI upon instatntiation, but there isn't a declared provider in the manifest except one from the test folder (so it's always an empty collection). I'd like to ask what's the purpose of this field and the purpose of looping through them in the start(), finishSuccess() and finishFailure() methods, and wouldn't there be a StackOverFlowError if any were any providers declared in a manifest and the sqlExecutionHooks field wasn't an empty list?

Thanks.

**Comment by jiangML** [comment]
@theodoretsai SeataTransactionalSQLExecutionHook also implements SQLExecutionHook, which will not cause StackOverFlowError

**Comment by theodoretsai** [comment]
@jiangML I guess that my ClassPath did not contain SeataTransactionalSQLExecutionHook since I only had shardingsphere-jdbc-core dependency, that solves the question, Thank you very much.
