### ISSUE TITLE
Invalid tag: !GLOBAL_CLOCK

### ISSUE THREAD

**Issue by zhong2312** [apache/shardingsphere#26341]
I am using the example of version 5.3.2
![image](https://github.com/apache/shardingsphere/assets/4153607/b481e9f7-89d8-41ee-ab47-23d462163a2c)

Sharing Configuration between ShardingJDBC and ShardingSphere-Proxy
![image](https://github.com/apache/shardingsphere/assets/4153607/715c28d2-e18b-4aa4-b75d-89b92259a4c8)
![01b470ff87c636e5c8802b10ad63d0c0](https://github.com/apache/shardingsphere/assets/4153607/4fc50b3f-23cd-4038-a695-3dc5d4c7aeaa)

The error occurred after startup.
![image](https://github.com/apache/shardingsphere/assets/4153607/a41f658b-315c-41bf-a384-aff8740cb530)

If the global-clock jar package is add, the application runs successfully.
![image](https://github.com/apache/shardingsphere/assets/4153607/0df0bcbe-6935-43fd-89d3-9c114878c642)
![image](https://github.com/apache/shardingsphere/assets/4153607/ce8722ca-b245-4f66-88c1-6cc6d5b7d6e8)

**Comment by FlyingZC** [comment]
@zhong2312 Hi,do you want to fix this issue.
