### ISSUE TITLE
Can't get COMMENT

### ISSUE THREAD

**Issue by manxihuanchi** [apache/shardingsphere#26346]
### Which version of ShardingSphere did you use?
shardingsphere-sql-parser-mysql  5.3.2
shardingsphere-sql-parser-sql92   5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-sql-parser-sql92 5.3.2
### Expected behavior
Can get COMMENT
### Actual behavior
Can get COMMENT
### Reason analyze (If you can)
package org.apache.shardingsphere.sql.parser.core;
/**
 * Parse AST node.
 */
@RequiredArgsConstructor
public final class ParseASTNode implements ASTNode {
    
    private final ParseTree parseTree;
    
    private final CommonTokenStream tokenStream;
    
    /**
     * Get root node.
     * 
     * @return root node
     */
    public ParseTree getRootNode() {
        return parseTree.getChild(0);
    }
    
    /**
     * Get hidden tokens.
     * 
     * @return hidden tokens
     */
    public Collection<Token> getHiddenTokens() {
        Collection<Token> result = new LinkedList<>();
        for (Token each : tokenStream.getTokens()) {
            if (Token.HIDDEN_CHANNEL == each.getChannel()) {
// each.getChannel()    Always 0
                result.add(each);
            }
        }
        return result;
    }
}

### Example codes for reproduce this issue (such as a github link).
String oneSql = " CREATE TABLE `t_device`  (
  `device_number` varchar(255)  COMMENT '设备编号',
  `name` varchar(255)  COMMENT '设备名称',
  `specifications_models` varchar(255)  COMMENT '规格型号',
  `manufacturing_date` datetime(0)  COMMENT '制造日期',
  `manufacturers` varchar(255)  COMMENT '制造厂家',
  `start_use_date` varchar(255) COMMENT '启用日期',
  `installation_site` varchar(255)  COMMENT '安装地点',
  `brand` varchar(255)  COMMENT '品牌',
  `device_price` decimal(10, 2)  COMMENT '设备价格',
  `power` varchar(255)  COMMENT '功率'
);";
String databaseType = "MYSQL";
                CacheOption cacheOption = new CacheOption(128, 1024L);
		SQLParserEngine parserEngine = new SQLParserEngine(databaseType, cacheOption);
		ParseASTNode parseASTNode = parserEngine.parse(oneSql, false);
		SQLVisitorEngine visitorEngine = new SQLVisitorEngine(sqlType, "STATEMENT", true, new Properties());
		SQLStatement sqlStatement = visitorEngine.visit(parseASTNode);
		TableSchema tableSchema = null;
		if (sqlStatement instanceof CreateTableStatement) {
			CreateTableStatement statement = (CreateTableStatement) sqlStatement;
			Collection<CommentSegment> commentSegments = statement.getCommentSegments();
			// commentSegments  is null
             }

**Comment by manxihuanchi** [comment]
Actual behavior
Can't get COMMENT

**Comment by zihaoAK47** [comment]
@manxihuanchi The Comment attribute currently does not seem to have parsing support.

**Comment by manxihuanchi** [comment]
Can you tell me how to parse it? I want to make changes directly on the source code, which is very important to me

**Comment by zihaoAK47** [comment]
@manxihuanchi  Of course :smile: 

1.You can use the Antlr4 plugin to check if the createTable rule correctly parses the above SQL statement rules, as specified in the {HOME}/shardingsphere/parser/sql/dialect/mysql/src/main/antlr4/imports/mysql/DDLStatement.g4

2.If parsing is incorrect, you need to modify the correct parsing rule to enable Antlr4 to parse the SQL statement correctly.

3.The visitCreateTable method of the {HOME}/apache/shardingsphere/parser/sql/dialect/mysql/src/main/java/org/apache/shardingsphere/sql/parser/mysql/visitor/statement/type/MySQLDDLStatementVisitor. java class is used to handle the syntax rules corresponding to the create table

4.You can process and parse the code here to support the COMMENT attribute, which is stored in {HOME}/shardingsphere/parser/sql/statement/src/main/java/org/apache/shardingsphere/sql/parser/sql/dialect/statement/mysql/ddl/MySQLCreateTableStatement.java

You can refer to the previous pr #25993

**Comment by terrymanu** [comment]
ShardingSphere is a product, not a development framework or SDK, and its current scope does not include providing development APIs beyond product features.
