### ISSUE TITLE
What is the entry point class for ShardingSphere-JDBC startup?

### ISSUE THREAD

**Issue by zhong2312** [apache/shardingsphere#26366]
I would like to see the initialization process of ShardingSphere-JDBC 5.3.2, but I have been debugging for a long time and cannot find the startup class.  I also couldn't find any classes similar to xxxAutoConfiguration (such as ShardingSphereAutoConfiguration) by searching through the source code.  Could you please let me know which class serves as the entry point?

Because I need to connect to different ShardingSphere logical databases within the same service, it means I need to configure two database names. So, I would like to see the initialization process of ShardingSphere-JDBC in order to find a solution."
![image](https://github.com/apache/shardingsphere/assets/4153607/065152a6-0788-4dd7-951f-6dcc472c340d)

**Comment by jiangML** [comment]
@zhong2312 Hi the entry class is `org.apache.shardingsphere.driver.ShardingSphereDriver`

**Comment by zhong2312** [comment]
![image](https://github.com/apache/shardingsphere/assets/4153607/475c3be8-0b30-44f5-82e7-046c27534972)

This approach is great, as it only requires changing the URL in spring.datasource.url to read different configuration files and create different data sources.
