### ISSUE TITLE
Please support environment variables in sharding.yml

### ISSUE THREAD

**Issue by cbcbbcbc** [apache/shardingsphere#26395]
(1) We need to override the variable definitions in sharding.yml according to the spring boot environment variables loading rules (same variable name in config/service-name.yml or config/application.yml), such as dataSources.x.jdbcUrl, dataSources.x.username;
(2) We need to refer the ourside variables from sharding.ymml, for example: dataSources.x.jdbcUrl: ${someVar}

**Comment by RaigorJiang** [comment]
@cbcbbcbc 
ShardingSphere does not have such a plan, do you have a feasible proposal?

**Comment by cbcbbcbc** [comment]
If you use Shardingsphere in a Spring Boot application, you will be aware of this requirement. Usually we use a configuration server such as Consul or Spring Cloud Config Server to save the production environment variables (DB username/password. etc.) those will override the ones in application.yml, the yml is packaged into a jar so we cannot replace it in production environment, this feature is the only one we can depend on.

**Comment by RaigorJiang** [comment]
@cbcbbcbc 
There is an issue about Apollo, which may help you.
https://github.com/apache/shardingsphere/issues/23388

**Comment by 401error** [comment]
@cbcbbcbc Have you solved it yet

**Comment by cbcbbcbc** [comment]
> @cbcbbcbc Have you solved it yet

I wrote my own driver class to replace the placeholders in yaml then call the default driver class.
