### ISSUE TITLE
No available readwrite-splitting rule configuration in database `logic_db`

### ISSUE THREAD

**Issue by yyyyyyyysssss** [apache/shardingsphere#26401]
shardingsphere:
    enabled: true
    datasource:
      names: master,slave0,slave1
      master:
        initial-size: 5   #连接池初始化连接数
        min-idle: 5       #连接池最小连接数
        max-active: 10   #连接池最大连接数
        max-wait: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        validationQuery: select 1
        testWhileIdle: true
        keepAlive: true
      slave0:
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        validationQuery: select 1
        testWhileIdle: true
        keepAlive: true
      slave1:
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        validationQuery: select 1
        testWhileIdle: true
        keepAlive: true
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            type: Static
            load-balancer-name: roundRobin
            props:
              auto-aware-data-source-name: master
              write-data-source-name: master
              read-data-source-names: slave0,slave1
        load-balancers:
          roundRobin:
            type: ROUND_ROBIN
    sharding:
      default-table-strategy: none
    props:
      sql:
        show: true

**Comment by RaigorJiang** [comment]
Please follow the issue template to ask questions and format your configuration text, thank you!
