### ISSUE TITLE
shardingsphere5.1.0 It supports springboot3.0.2 ？

### ISSUE THREAD

**Issue by yyyyyyyysssss** [apache/shardingsphere#26400]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by yyyyyyyysssss** [comment]
读写分离该如何配置呢？

**Comment by jiangML** [comment]
@yyyyyyyysssss Hi，you can look at the official website, https://shardingsphere.apache.org/document/current/en/overview/

**Comment by RaigorJiang** [comment]
Please refer to the documentation for version `5.1.0`
https://shardingsphere.apache.org/document/5.1.0/en/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/readwrite-splitting/
