### ISSUE TITLE
The cluster mode is Nacos, can it support authentication?

### ISSUE THREAD

**Issue by novayoung** [apache/shardingsphere#26437]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

In module shardingsphere-cluster-mode-repository-nacos, the method org.apache.shardingsphere.mode.repository.cluster.nacos.NacosRepository.createClient(final ClusterPersistRepositoryConfiguration config) create NamingService instance，but no parameters for username and password, If Nacos needs to log in, an error will be reported.

**Comment by zhaojinchao95** [comment]
@novayoung Hi, it's look not support, and are you interested in contributing to this great capability?

**Comment by zihaoAK47** [comment]
@zhaojinchao95 May I take a look at this problem? I will work hard to solve it.

**Comment by novayoung** [comment]
> @novayoung Hi, it's look not support, and are you interested in contributing to this great capability?

sure~

**Comment by zhaojinchao95** [comment]
@zhaojinchao95 @zihaoAK47 Hi, did you continue to complete it?
