### ISSUE TITLE
When shardingsphere proxy rewrites SQL, native characters similar to toString that have not been rewritten appear in the SQL body

### ISSUE THREAD

**Issue by StackRui** [apache/shardingsphere#26464]
## Question
When I executed a batch insert statement in shardingsphere proxy 5.1.2, the Actual SQL was rewritten as
 ` Insert INTO life_ cycle_tag_static (tag_id, tag_key, tenant_id, tag_value, 'add', loss, total, base_time) VALUES org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@5d853edc ON DUPLICATE KEY UPDATE ` total `=values (` total `)` 
please note the `org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@5d853edc`
Why is this happening? Such SQL will definitely report an error. But after restarting shardingsphere-proxy, the abnormality disappeared and everything was normal. I don't know how to reproduce this problem because I don't even know how it happened?. I am looking forward to any possible feedback on the reasons.

Here are some logs:
`[INFO ] 2023-06-19 15:01:38.631 [ShardingSphere-Command-46829] ShardingSphere-SQL - Logic SQL: INSERT INTO life_cycle_tag_statistic(tag_id, tag_key, tenant_id, tag_value, `add`, loss, total, base_time)  VALUES (0, 'tag_0', 1, 'tag_0', 0, 0, 0, 1687158098487)  ,(1, 'tag_1', 1, 'tag_1', 1, 1, 1, 1687158098487)  ,(2, 'tag_2', 1, 'tag_2', 2, 2, 2, 1687158098487)   ON DUPLICATE KEY UPDATE  `total`= values(`total`)                       
[INFO ] 2023-06-19 15:01:38.631 [ShardingSphere-Command-46829] ShardingSphere-SQL - SQLStatement: MySQLInsertStatement(setAssignment=Optional.empty, onDuplicateKeyColumns=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.OnDuplicateKeyColumnsSegment@63b26b46])                                                                                   
[INFO ] 2023-06-19 15:01:38.631 [ShardingSphere-Command-46829] ShardingSphere-SQL - Actual SQL: ds ::: INSERT INTO life_cycle_tag_statistic(tag_id, tag_key, tenant_id, tag_value, `add`, loss, total, base_time)  VALUES org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@5d853edc   ON DUPLICATE KEY UPDATE  `total`= values(`total`)`

**Comment by StackRui** [comment]
![image](https://github.com/apache/shardingsphere/assets/48947279/f1b09adb-7f8c-4797-bddc-202cca5635fc)
I reproduced the problem, but felt that it was impossible, but it did happen, and I was very confused

**Comment by TeslaCN** [comment]
Duplicate with https://github.com/apache/shardingsphere/issues/18456
