### ISSUE TITLE
how to config multiple same structure tables for using same encrypt rule ?

### ISSUE THREAD

**Issue by netyjq** [apache/shardingsphere#26502]
I have a table here that automatically generates a new table per day by date, I now want to configure the same encryption rules for these tables, I tested using the wildcard *, but it doesn't work。

tables for example sms_record_20230601, sms_record_20230602,sms_record_20230603,...sms_record_20230630,

i have try this: 

```java
EncryptColumnRuleConfiguration columnConfig2 = new EncryptColumnRuleConfiguration("dest_number", "dest_number_cipher", "", "aes");
            EncryptColumnRuleConfiguration columnConfig3 = new EncryptColumnRuleConfiguration("content", "content_cipher", "", "aes");

            Map<String, EncryptColumnRuleConfiguration> columnConfigMaps = new HashMap<>();
            columnConfigMaps.put("dest_number", columnConfig2);
            columnConfigMaps.put("content", columnConfig3);
            EncryptTableRuleConfiguration tableConfig = new EncryptTableRuleConfiguration(columnConfigMaps);
            encryptRuleConfig.getTables().put("sms_record*", tableConfig);
```

I've read the documentation and searched Google, but I still don't have an answer, need help , thanks!

**Comment by RaigorJiang** [comment]
@netyjq 
Are these sharding tables? If yes, just create encrypt rule for logical table in sharding.

**Comment by netyjq** [comment]
> @netyjq Are these sharding tables? If yes, just create encrypt rule for logical table in sharding.

No,  sharding features are not used yet.   for now, I can only write configuration table rules in the for loop in my code, right?

**Comment by RaigorJiang** [comment]
> > @netyjq Are these sharding tables? If yes, just create encrypt rule for logical table in sharding.
> 
> No, sharding features are not used yet. for now, I can only write configuration table rules in the for loop in my code, right?

@netyjq , You are right, we should add config for each table.
