### ISSUE TITLE
Add stargazers worldmap in ShardingSphere README page 

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#26521]
as we could see there are some stargazers analysis in the README page like followings

<img width="1157" alt="image" src="https://github.com/apache/shardingsphere/assets/4112856/f971b279-c133-46c5-89c2-2b83fe9d24e1">

please try to add the worldmap in the README page to make the analysis more detail 
some worldmap looks like :
![image](https://github.com/apache/shardingsphere/assets/4112856/5fd3863b-96ec-4300-bc9e-70ea3fc1eec4)
or
![image](https://github.com/apache/shardingsphere/assets/4112856/ba0b2e08-6d92-4567-8274-d5918e81598d)

**Comment by Swastyy** [comment]
I will try this :)

**Comment by taojintianxia** [comment]
> I will try this :)

hi, @Swastyy any idea on this ?

**Comment by Swastyy** [comment]
Hey, I have found this [link](https://dev.to/dyatko/worldstar-generate-world-map-of-your-github-stargazers-2cab) useful. I will create a PR with implementation of it.

**Comment by Zhenye-Na** [comment]
I have observed that this issue is not picked up by anyone, and I would like to work on this.

Before I made any changes, I noticed that there are some existing resources/tools that could help achieve this:

https://github.com/tunaitis/contributor-map#usage is one of the tools I came across.

Please feel free to let me know if you folks are ok with the approach I proposed:

1. Integrate with `contributor-map`
2. Create a new Github Actions to automatically update the generated SVG based on Cronjob


If everything looks fine then probably I could work on this.

Thanks

**Comment by Zhenye-Na** [comment]
It seems like the nightly-build workflow failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo

```
[Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
```

**Comment by taojintianxia** [comment]
> Hi @taojintianxia
> 
> It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> 
> ```
> [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> ```

yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file.
let's test it in forked repository and then commit the PR.

**Comment by Zhenye-Na** [comment]
> > Hi @taojintianxia
> > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > ```
> > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > ```
> 
> yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.

However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow

I am wondering is there a way to allowlist this github action somewhere I need to configure ?

**Comment by taojintianxia** [comment]
> > > Hi @taojintianxia
> > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > ```
> > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > ```
> > 
> > 
> > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> 
> However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> 
> I am wondering is there a way to allowlist this github action somewhere I need to configure ?
I have seen that error before, and did not handle that issue successfully. >_<

**Comment by Zhenye-Na** [comment]
> > > > Hi @taojintianxia
> > > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > > ```
> > > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > > ```
> > > 
> > > 
> > > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> > 
> > 
> > However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> > I am wondering is there a way to allowlist this github action somewhere I need to configure ?
> > I have seen that error before, and did not handle that issue successfully. >_<

Ack, no worry, let me create a quick PR revert that commit. Also, I will try to see if I could find something around it. Not familiar with Github Actions as well as this repo belongs to apache org.

Will send out the reverting commit PR shortly and let you know here.

Thanks!

**Comment by taojintianxia** [comment]
> > > > > Hi @taojintianxia
> > > > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > > > ```
> > > > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > > > ```
> > > > 
> > > > 
> > > > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> > > 
> > > 
> > > However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> > > I am wondering is there a way to allowlist this github action somewhere I need to configure ?
> > > I have seen that error before, and did not handle that issue successfully. >_<
> 
> Ack, no worry, let me create a quick PR revert that commit. Also, I will try to see if I could find something around it. Not familiar with Github Actions as well as this repo belongs to apache org.
> 
> Will send out the reverting commit PR shortly and let you know here.
> 
> Thanks!

I have revert the commit because there is a nightly check workflow, on of the workflow job is  called deadlink-check, that action detect there is a deadlink(that world map link) is 404, so I fixed that.

**Comment by Swastyy** [comment]
is this issue solved? There seems no map in readme

**Comment by taojintianxia** [comment]
> > > > > Hi @taojintianxia
> > > > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > > > ```
> > > > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > > > ```
> > > > 
> > > > 
> > > > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> > > 
> > > 
> > > However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> > > I am wondering is there a way to allowlist this github action somewhere I need to configure ?
> > > I have seen that error before, and did not handle that issue successfully. >_<
> 
> Ack, no worry, let me create a quick PR revert that commit. Also, I will try to see if I could find something around it. Not familiar with Github Actions as well as this repo belongs to apache org.
> 
> Will send out the reverting commit PR shortly and let you know here.
> 
> Thanks!

is it possible to upload the map picture to a space and then copy the link the map url to shardingsphere ?

**Comment by Zhenye-Na** [comment]
I could enable the github action workflow in my own fork, and update the apache mainline repo to reference the generated image.

However, I am not sure if

1. This is allowed or recommended to use a image link from another repo
2. If I happened to delete the branch or repo from my own account, the repoin apache mainline wont have the access to the image anymore

I am more interested to see if

1. Apache organization has a place to modify the allowed github actions
2. If there is a fork under shardingsphere org / commiter / TC members, maybe we could utilize that.

**Comment by Zhenye-Na** [comment]
> > > > > > Hi @taojintianxia
> > > > > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > > > > ```
> > > > > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > > > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > > > > ```
> > > > > 
> > > > > 
> > > > > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> > > > 
> > > > 
> > > > However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> > > > I am wondering is there a way to allowlist this github action somewhere I need to configure ?
> > > > I have seen that error before, and did not handle that issue successfully. >_<
> > 
> > 
> > Ack, no worry, let me create a quick PR revert that commit. Also, I will try to see if I could find something around it. Not familiar with Github Actions as well as this repo belongs to apache org.
> > Will send out the reverting commit PR shortly and let you know here.
> > Thanks!
> 
> is it possible to upload the map picture to a space and then copy the link the map url to shardingsphere ?

I could enable the github action workflow in my own fork, and update the apache mainline repo to reference the generated image.

However, I am not sure if

1. This is allowed or recommended to use a image link from another repo
2. If I happened to delete the branch or repo from my own account, the repoin apache mainline wont have the access to the image anymore

I am more interested to see if

1. Apache organization has a place to modify the allowed github actions
2. If there is a fork under shardingsphere org / commiter / TC members, maybe we could utilize that.

**Comment by taojintianxia** [comment]
> > > > > > > Hi @taojintianxia
> > > > > > > It seems like the nightly-build workflow last execution ([link](https://github.com/apache/shardingsphere/actions/runs/6448611936)) failed because of the github action `tunaitis/contributor-map@v1` is not allowed to be used in this repo
> > > > > > > ```
> > > > > > > [Error: .github#L1](https://github.com/apache/shardingsphere/commit/1e2fe35851f21809c34027e4fba2d5772a7fb006#annotation_14737341013)
> > > > > > > tunaitis/contributor-map@v1 is not allowed to be used in apache/shardingsphere. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link-check...
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > yes, it's not working in this repository. let's revert the change, remove the action and svg link from markdown file. let's test it in forked repository and then commit the PR.
> > > > > 
> > > > > 
> > > > > However, I am able to test this in my own fork, here is the [link ](https://github.com/Zhenye-Na/shardingsphere/actions/runs/6368471123/job/17287850146)to the execution hisotry via a github workflow
> > > > > I am wondering is there a way to allowlist this github action somewhere I need to configure ?
> > > > > I have seen that error before, and did not handle that issue successfully. >_<
> > > 
> > > 
> > > Ack, no worry, let me create a quick PR revert that commit. Also, I will try to see if I could find something around it. Not familiar with Github Actions as well as this repo belongs to apache org.
> > > Will send out the reverting commit PR shortly and let you know here.
> > > Thanks!
> > 
> > 
> > is it possible to upload the map picture to a space and then copy the link the map url to shardingsphere ?
> 
> I could enable the github action workflow in my own fork, and update the apache mainline repo to reference the generated image.
> 
> However, I am not sure if
> 
> 1. This is allowed or recommended to use a image link from another repo
> 2. If I happened to delete the branch or repo from my own account, the repoin apache mainline wont have the access to the image anymore
> 
> I am more interested to see if
> 
> 1. Apache organization has a place to modify the allowed github actions
> 2. If there is a fork under shardingsphere org / commiter / TC members, maybe we could utilize that.

upload to repo is not a good idea, could you please investigate if there is a free space for API upload files in Apache or some org like  that ?

**Comment by linghengqian** [comment]
- **I think the closure of this issue is illogical because the PR is not ready at all and the current README does not show the real geographical location information.** 
- ![image](https://github.com/user-attachments/assets/cc4ae631-297d-4c05-9f65-97de99454e39)
- I observed another solution from https://github.com/apache/superset . PingCAP provides a better solution.
- I want to replace these two graphs with 3 separate graphs: 
    - https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=stars&repo_id=49876476
    - https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=pull-request-creators&repo_id=49876476
    - https://next.ossinsight.io/widgets/official/analyze-repo-stars-map?activity=issue-creators&repo_id=49876476
    - ![image](https://github.com/user-attachments/assets/b55b2ca8-3a6d-4138-a945-24a047e095af)
    - ![image](https://github.com/user-attachments/assets/50943eab-6247-4ad7-aa23-9908e377c7e5)
    - ![image](https://github.com/user-attachments/assets/24ed0286-544e-4852-80c9-0b661551fd36)
- @taojintianxia @Zhenye-Na @Swastyy What do you think? This does not require any Github Actions at all, it is just referencing the image from the PingCAP side.
