### ISSUE TITLE
[Discussion] Consider moving the algorithms in sharding and encrypt plugins to a separate shardingsphere-plugin repository

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26590]
Hi community,

Due to the rapid development of ShardingSphere, plugin submodules are currently extracted from both sharding and encrypt modules to store some special algorithms contributed by the community, such as `cosId`, `nanoid` sharding algorithm, and `sm3` and `sm4` encryption algorithms. These plugins enrich the applicable scenarios of ShardingSphere, but also make ShardingSphere bloated and complicated. 

```
.
├── encrypt
│             ├── api
│             ├── core
│             ├── distsql
│             └── plugin
└──  sharding
              ├── api
              ├── core
              ├── distsql
              └── plugin
```

In order to reduce the dependence on some special jar packages, such as: `cosid`, `bcprov-jdk15on`, we can move the code in the plugin to an independent `shardingsphere-plugin` repository, and community contributors can contribute more algorithm implementations in this repository.

When users want to use the algorithm in `shardingsphere-plugin` repository, they only need to package the algorithm and add the jar to ShardingSphere.

Considering that this task will take some time to apply for a new repository, I suggest implementing it in two stages as follows:

- [x] first, remove plugin document in ShardingSphere
- [ ] second, move plugin code and document to `shardingsphere-plugin` repository

Everyone is welcome to participate in the discussion and express their views. Thank you.

**Comment by Swastyy** [comment]
Hi all and @strongduanmu , I will be contributing to some sub-tasks of this. Waiting for the `shardingsphere-plugin` repo to build and contribute to it. Have a great day!!

**Comment by strongduanmu** [comment]
Welcome @Swastyy, this task will keep ShardingSphere simple, and at the same time provide more opportunities for the community to customize algorithms, and everyone can use their ingenuity in the `shardingsphere-plugin` repository.

**Comment by strongduanmu** [comment]
After discussion - https://lists.apache.org/thread/f7xkjlvzfkkk9lcbgrv33zcmlhwcm2xs, we will promote this work:

- First of all, I will delete documents related to the Plugin algorithm;
- Then, I will apply for a new ShardingSphere-Plugin warehouse and move the code in Plugin to the new warehouse.
