### ISSUE TITLE
【distSQL】CREATE ENCRYPT RULE，when i add LIKE_QUERY，it's always wrong

### ISSUE THREAD

**Issue by static0807** [apache/shardingsphere#26622]
## Question

my shardingsphere's version is 5.3.2

when i execute this SQL, it is OK

CREATE ENCRYPT RULE t_encrypt_2 (COLUMNS((NAME=user_id,PLAIN=user_plain,CIPHER=user_cipher,ENCRYPT_ALGORITHM(TYPE(NAME='AES',PROPERTIES('aes-key-value'='123456abc'))))), QUERY_WITH_CIPHER_COLUMN=FALSE);

but, i want use like query, so i added like query sql, it is :

CREATE ENCRYPT RULE t_encrypt_2 (COLUMNS((NAME=user_id,PLAIN=user_plain,CIPHER=user_cipher,LIKE_QUERY=user_like,ENCRYPT_ALGORITHM(TYPE(NAME='AES',PROPERTIES('aes-key-value'='123456abc'))),LIKE_QUERY_ALGORITHM(TYPE(NAME='CRC16',PROPERTIES('cps-key-id'='123456abc'))))));

this one is always wrong

I have checked many times and I believe the grammar is correct，Please help me identify the problem，thanks

**Comment by Pace2Car** [comment]
@static0807 Please give specific error performance for troubleshooting.

**Comment by static0807** [comment]
> @static0807 Is the execution result incorrect or an error is reported? please give specific error performance for troubleshooting.

sorry，i forgot it
this is the execution result : 
![image](https://github.com/apache/shardingsphere/assets/72844024/15ff7a49-bda3-426d-a64c-b265572e719f)

thanks

**Comment by static0807** [comment]
> @static0807 Is the execution result incorrect or an error is reported? please give specific error performance for troubleshooting.

I just resolved this issue because there is an error in the official PDF document

in the PDF doc, create encrypt rule use ' LIKE_QUERY = likeQueryColumnName'

![image](https://github.com/apache/shardingsphere/assets/72844024/5dd42059-47d5-4ed8-9ae8-21f454eecea8)

this is wrong, but in online doc, it's 'LIKE_QUERY_COLUMN' , this is correct

![image](https://github.com/apache/shardingsphere/assets/72844024/6ff7667d-0691-4dd1-825e-c376512b938a)

in addition,the ASSISTED_QUERY_COLUMEN is also like this

please fix the pdf doc, thanks

**Comment by Pace2Car** [comment]
It looks like your PDF download is the master version, this syntax has been refactored in an upcoming release.
