### ISSUE TITLE
Missing org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser

### ISSUE THREAD

**Issue by lindadev77** [apache/shardingsphere#26671]
master分支 shardingsphere-parser-distsql-engine模块下的org.apache.shardingsphere.distsql.parser.core.kernel.KernelDistSQLParser 缺失基类org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser

![image](https://github.com/apache/shardingsphere/assets/9762702/6f7193e8-bdbf-4b3d-b2c5-d5c7a3f2a90d)

**Comment by Pace2Car** [comment]
Please refer to: https://shardingsphere.apache.org/community/en/involved/contribute/contributor/

Build and install all modules to solve this.

**Comment by Pace2Car** [comment]
BTW: The community should communicate in English.
