### ISSUE TITLE
sql parsing does not support <RLIKE | NOT RLIKE> in MySQL

### ISSUE THREAD

**Issue by FakeKotaro** [apache/shardingsphere#26687]
### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Behavior
When I run the following SQL：
```sql
SELECT * FROM user where name RLIKE 'devin'
```
It throws the following exception：
```java
Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax: SELECT * FROM user where name RLIKE '123', no viable alternative at input 'RLIKE' at line 1, position 30, near [@6,30:34='RLIKE',<593>,1:30]
```
But this SQL is actually executable in MySQL

### Reason analyze (If you can)
The handling of RLIKE is not defined in the antlr4 syntax file
```
predicate
    : bitExpr NOT? IN subquery
    | bitExpr NOT? IN LP_ expr (COMMA_ expr)* RP_
    | bitExpr NOT? BETWEEN bitExpr AND predicate
    | bitExpr SOUNDS LIKE bitExpr
    | bitExpr NOT? LIKE simpleExpr (ESCAPE simpleExpr)?
    | bitExpr NOT? REGEXP bitExpr
    | bitExpr
    ;
```

**Comment by FakeKotaro** [comment]
I'd like to know if this defect is already being followed up on, and if not,  I would like to make a PR

**Comment by FakeKotaro** [comment]
@strongduanmu

**Comment by zihaoAK47** [comment]
@FakeKotaro Hi, the above statement is indeed executable. The issue with RLIKE parsing also appears in this #25535 and is currently being followed up. It would be great if you could submit a PR to fix this issue. Thank you very much

**Comment by FakeKotaro** [comment]
@zihaoAK47 Sure, I'd like to submit a PR, please assign it to me

**Comment by zihaoAK47** [comment]
> @zihaoAK47 Sure, I'd like to submit a PR, please assign it to me

You can choose a mentor to assign the task to

**Comment by strongduanmu** [comment]
Fixed by https://github.com/apache/shardingsphere/pull/26731.
