### ISSUE TITLE
How to support cross-database queries?

### ISSUE THREAD

**Issue by cbcbbcbc** [apache/shardingsphere#26696]
If a query cross two databases, it'll fail. For example:
select * from my_db.T1 a, T2 b where b.id=? and b.id=a.id
Caused by: org.apache.shardingsphere.dialect.exception.syntax.database.UnknownDatabaseException: null

**Comment by terrymanu** [comment]
The `SQL federation` is an experimental feature, you can try it if you are interested.

**Comment by strongduanmu** [comment]
Since this issue has long time no response, I will close it.
