### ISSUE TITLE
Why not support closeOnCompletion API on java.sql.Statement

### ISSUE THREAD

**Issue by nswdn** [apache/shardingsphere#26700]
## ENV
JDK version: 8
Mybatis version: 3.5.6
Sharding-JDBC version: 3.0

## Code
```java
@Mapper
public interface Mapper {
  Cursor<User> findHugeUsers();
}
```

## Quesion
When I call findHugeUsers(), it throws a exception.
``` java
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.sql.SQLFeatureNotSupportedException: closeOnCompletion
```

I traced code and find that
```java
io.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationStatement#closeOnCompletion() {
  throws new SQLFeatureNotSupportedException("closeOnCompletion");
}
```
Then I read many versions of Sharding-JDBC's doc find that they seem to all not support closeOnCompletion method.

Is there's some same ways like Mybatis's Cursor to query huge data by Sharding-JDBC?

**Comment by rencoco** [comment]
I want to know if this question has been resolved, ths.

**Comment by nswdn** [comment]
> **version** : v5.3.0 I want to know if this question has been resolved, ths.

I do not sure about this, sorry. I use native connection pool (In my project is hikari.) to avoidance this issue.
