### ISSUE TITLE
Add unit test for RuleNodePathProvider 's implements.

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#26709]
- [ ] BroadcastRuleNodePathProvider
- [ ] CompatibleEncryptRuleNodePathProvider
- [ ] EncryptRuleNodePathProvider
- [ ] MaskRuleNodePathProvider
- [ ] ReadwriteSplittingRuleNodePathProvider
- [ ] ShadowRuleNodePathProvider
- [ ] ShardingRuleNodePathProvider
- [ ] SingleRuleNodePathProvider

**Comment by SwapnilPatil07** [comment]
I can work on this issue. Please assign it to me.
