### ISSUE TITLE
Add unit test for BroadcastRuleChangedEventCreator

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#26702]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for BroadcastRuleChangedEventCreator to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by KonarzewskiP** [comment]
Hi @zhaojinchao95.
There is no class **BroadcastRuleChangedEventCreator** in the project.

**Comment by terrymanu** [comment]
The class has been refactored, I just close the issue.
