### ISSUE TITLE
Using Savepoints in LocalTransaction mode causes memory leak

### ISSUE THREAD

**Issue by kfirst** [apache/shardingsphere#26726]
## Bug Report

When we use Savepoints in LocalTransaction mode on postgresql database, we get memory leak problem. The savepoints we ever created will be holded in ConnectionSavepointManager, and there's no mechanism to clean it up, even if the connection committed.

### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Holded Savepoints should be removed after connection committed.

### Actual behavior
Holded Savepoints do not be removed.

### Reason analyze (If you can)
In ConnectionManager#setSavepoint method, we call "ConnectionSavepointManager.getInstance().setSavepoint" method to hold the savepoint in ConnectionSavepointManager, but in ConnectionManager#commit method, we do not call "ConnectionSavepointManager.getInstance().transactionFinished" to remove the holded savepoints. This causes memory leak.

**Comment by kfirst** [comment]
When we use Savepoint in LocalTransaction mode on postgresql database, we get memory leak problem. The savepoints we ever created will be holded in ConnectionSavepointManager, and there's no mechanism to clean it up.

**Comment by TeslaCN** [comment]
Hi @kfirst 
Would you like to fix this issue?
We may need to cleanup savepoint in:
* `org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager#commit()`
* `org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager#rollback()`
