### ISSUE TITLE
When executing SQL with sub database and sub table keys, the actual executed SQL will be executed additionally to other libraries

### ISSUE THREAD

**Issue by ThisOnly** [apache/shardingsphere#26724]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The following is my configuration and executed SQL

![image](https://github.com/apache/shardingsphere/assets/41990755/06b43e14-0a1e-495a-93ed-f5eed3507d69)

![image](https://github.com/apache/shardingsphere/assets/41990755/b67f350f-184c-4a07-9ce3-5e6ec6557543)

The executed SQL carries sub database and sub table fields， partion_value is 1, theoretically speaking, SQL will only be used in ds_ 1 library execution, but in reality ds_ 0 has also been executed

The actual executed SQL is as follows
![1688184467641](https://github.com/apache/shardingsphere/assets/41990755/6abd1d72-cf3e-493b-9da3-609bea12f16c)

### Actual behavior
This SQL should not be in ds_0 Execute 

### Reason analyze (If you can)
This SQL carries a table partitioning key，and the sub database key is in the sub query

**Comment by terrymanu** [comment]
What's mean of `other libraries`?

**Comment by ThisOnly** [comment]
![image](https://github.com/apache/shardingsphere/assets/41990755/5e32b367-801a-4521-8b39-46510d146851)
This SQL statement was supposed to only be executed in ds_1, but it was actually executed in ds_0

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
