### ISSUE TITLE
Discussion on providing SPI to implement Yaml Configuration conversion DistSQL script

### ISSUE THREAD

**Issue by yx9o** [apache/shardingsphere#26732]
Hi Community:
I noticed the method in ConvertYamlConfigurationExecutor to generate DsitSQL for each feature, and I want to provide an SPI to replace them.

for example:
```java
@SingletonSPI
public interface ConvertYamlRuleConfigurationProvider extends TypedSPI {

     String generateDistSQL(final YamlRuleConfiguration yamlRuleConfig);
}
```
Is this okay?

**Comment by yx9o** [comment]
Hi @RaigorJiang , please help to see if this is ok?

**Comment by RaigorJiang** [comment]
@yx9o Good idea, can the method name be called `convert`?

**Comment by yx9o** [comment]
> @yx9o Good idea, can the method name be called `convert`?

Ok, then I'll try this direction first.

**Comment by RaigorJiang** [comment]
@yx9o Completed, great work, thank you!
