### ISSUE TITLE
when version 5.4.0 will be released

### ISSUE THREAD

**Issue by yflytom** [apache/shardingsphere#26746]
## Question

May I ask when version 5.4.0 will be released? The `shardingsphere-jdbc-core-spring-boot-starter` version in the maven warehouse is only `5.2.1`, while the `shardingsphere-jdbc-core` version is `5.3.2`. The two versions are also inconsistent
请问 5.4.0版本什么时候发布，maven仓库中的`shardingsphere-jdbc-core-spring-boot-starter`版本才`5.2.1`，而`shardingsphere-jdbc-core`版本是`5.3.2`，这两个版本也不一致!

**Comment by RaigorJiang** [comment]
Hi @yflytom 
Starting from 5.3.0, ShardingSphere no longer provides a spring boot starter, you can refer to the 5.3.2 document to use ShardingSphereDriver in the spring boot project.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/

**Comment by strongduanmu** [comment]
Since 5.4.0 is released, I will close this issue.
