### ISSUE TITLE
User defined variable keyword parsing failed

### ISSUE THREAD

**Issue by zihaoAK47** [apache/shardingsphere#26748]
## Question

**shardingsphere version: 5.3.3-SNAPSHOT**
**Problem type: SQL parse**

The following SQL example:
select @select
kill @empty
SET @drop = IF(@have_ndb = 0, @drop_cmd, 'SET @dummy = 0')
KILL QUERY @drop

If the variable name referenced by the user has the same name as the lexical rule in **MySQLKeyword.g4**, it will cause SQL parsing to fail. The lexical rule in **MySQLKeyword.g4** has higher priority.
Even if the correct **userVariable** syntax rules are defined in the **BaseRule.g4** file, parsing will fail

I would like to add a new rule in BaseRule.g4 that includes lexical information from MySQLKeyword.g4. After that, I want to modify the userVariable rule to be similar to the following:

userVariable
    : AT_ textOrIdentifier
    | textOrIdentifier
    | AT_ keyWords
    | keyWords
    ;

keyWords
    : DROP
    ;

Do you think this is the correct solution to avoid being affected by the lexical priority defined in the MySQLKeyword.g4 file?

**Comment by zihaoAK47** [comment]
@strongduanmu Hi, mentor please take a look at this question. Thank you

**Comment by terrymanu** [comment]
Please refer to the issue template to provide more details for your question. for example: version

**Comment by zihaoAK47** [comment]
> Please refer to the issue template to provide more details for your question. for example: version

Hi mentor, thank you for your reply. I have revised the description of the problem
