### ISSUE TITLE
Docker image build failed on aarch64 chip

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#26775]
Hi community,

`spotify:dockerfile-maven-plugin`(https://github.com/spotify/dockerfile-maven) has been out of maintenance for many years, need to upgrade its dependency to a version that supports aarch64.

### backtrace
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (shardingsphere-proxy-bin) on project shardingsphere-test-e2e-fixture: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider com.spotify.docker.client.shaded.jnr.ffi.provider.jffi.Provider: ExceptionInInitializerError: Can't overwrite cause with java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /private/var/folders/hw/rk2827v92hj2g7fq1p_v8jp40000gn/T/jffi591738434175491320.dylib: dlopen(/private/var/folders/hw/rk2827v92hj2g7fq1p_v8jp40000gn/T/jffi591738434175491320.dylib, 0x0001): tried: '/private/var/folders/hw/rk2827v92hj2g7fq1p_v8jp40000gn/T/jffi591738434175491320.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/hw/rk2827v92hj2g7fq1p_v8jp40000gn/T/jffi591738434175491320.dylib' (no such file), '/private/var/folders/hw/rk2827v92hj2g7fq1p_v8jp40000gn/T/jffi591738434175491320.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))

```

The dependencies that need to be added are defined as:
```xml
<plugin>
    <groupId>com.spotify</groupId>
    <artifactId>dockerfile-maven-plugin</artifactId>
    <version>${dockerfile-maven.version}</version>
    <dependencies>
        <dependency>
            <groupId>com.github.jnr</groupId>
            <artifactId>jnr-unixsocket</artifactId>
            <version>0.38.20</version>
        </dependency>
        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>docker-client</artifactId>
            <classifier>shaded</classifier>
            <version>8.14.5</version>
        </dependency>
    </dependencies>
</plugin>
```
After this, the current problem can be resolved.However, if the version of docker-client drops to 8.14.5, it will face some known issues:
- https://github.com/spotify/dockerfile-maven/issues/191

In the long run, we should try some other docker plugins, there are currently two popular plugins that can be taken into consideration:
- fabric8:docker-maven-plugin(https://github.com/fabric8io/docker-maven-plugin)
- mojohaus:exec-maven-plugin(https://github.com/mojohaus/exec-maven-plugin)

However, the replacement will involve a lot of configuration modification, which needs to be evaluated.

**Comment by Pace2Car** [comment]
Refer to: https://github.com/spotify/dockerfile-maven/issues/394

**Comment by Pace2Car** [comment]
Refer to: https://github.com/apache/airavata-custos/issues/374

**Comment by TeslaCN** [comment]
There is a temporary solution https://blog.csdn.net/wu_weijie/article/details/120630608

**Comment by Pace2Car** [comment]
> There is a temporary solution https://blog.csdn.net/wu_weijie/article/details/120630608

Thanks, this solved the problem I'm currently having
