### ISSUE TITLE
mysql database has a abnormal table，sharding-jdbc start failed

### ISSUE THREAD

**Issue by zdd1998** [apache/shardingsphere#26788]
my project use sharding-jdbc，4.1.1 version，and meet a problem!

**Error creating bean with name 'shardingDataSource' defined in class path resource [org/apache/shardingsphere/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.sql.SQLException: Can't find file: 'data_10' (errno: 2 - No such file or directory)**

I debuged and found that sharding jdbc perform both loadShardingSchemeMetaData and loadDefaultSchemeMetaData in the ShardingMetaDataLoader class.

I don't know why loadDefaultSchemeMetaData method need be invoked, and it seems there is no parameter can prevent it。
this property check.table.metadata.enabled set false as default and it just work on loadShardingSchemeMetaData method,
What is the actual meaning of this parameter？
Did anyone meet the same problem，please give me some help！
Thx!

**Comment by zhaojinchao95** [comment]
Hi, `4.1.1` are too old, you can use latest version and try it.

**Comment by zdd1998** [comment]
now i use sharding-jdbc-spring-boot-starter, the latest version is 4.1.1 in https://mvnrepository.com/search?q=sharding-jdbc.
you mean to use shardingsphere-jdbc-core-spring-boot-starter?

**Comment by zhaojinchao95** [comment]
> now i use sharding-jdbc-spring-boot-starter, the latest version is 4.1.1 in https://mvnrepository.com/search?q=sharding-jdbc. you mean to use shardingsphere-jdbc-core-spring-boot-starter?

The shardingsphere-jdbc-core-spring-boot-starter are removed at latest version, you can use https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core/5.3.2

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
