### ISSUE TITLE
sharding-shpere Handling null value

### ISSUE THREAD

**Issue by MuAnswer** [apache/shardingsphere#26787]
I encountered a problem when using sharding shpere 4.1.1. If the column value in the database library is null, the corresponding Java code Long will be processed as 0

**Comment by MuAnswer** [comment]
The source code is designed like this. Do you have any solutions?

**Comment by zhaojinchao95** [comment]
Hi, you can use latest version and try it.

**Comment by terrymanu** [comment]
The version is out of service, please try new version

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
