### ISSUE TITLE
add healthy check in master slave route mode

### ISSUE THREAD

**Issue by stanstanwang** [apache/shardingsphere#26785]
## Feature Request

when i using master slave mode, i configure one master and two slave,  but when one slave crash down, 
which will resulting the http requset with two more database read failded , becase one database read will route to the crashing slave，
can add some healthy check for master slave mode, like the kong or Hystrix ?

### Is your feature request related to a problem?
no

### Describe the feature you would like.

add healthy check in master slave route mode

**Comment by zhaojinchao95** [comment]
What you describe is similar to the previous database discovery function, it is not suitable for ss, you can refer to : https://github.com/apache/shardingsphere/issues/24486
