### ISSUE TITLE
when i use shardingsphere proxy with postgresql , how to switch database in jdbc

### ISSUE THREAD

**Issue by static0807** [apache/shardingsphere#26815]
## Question

my shardingsphere version is 5.3.2

because i want to dynamically refresh the encrypt rule by settings. so i try to use the distsql refresh the rules in my program.

I use jdbc to connect to postgreSQL through proxy，

first，i create logic database, so i execute "create database xxx"，

second, i want to register storage unit , i want switch to the new database, so i execute "USE XXX", but an error occurred.

Exception in thread "main" org.postgresql.util.PSQLException: ERROR: You have an error in your SQL syntax: USE test_pg, no viable alternative at input 'USE' at line 1, position 0, near [@0,0:2='USE',<589>,1:0]

i change to execute "\c xxx", but it also error.

Exception in thread "main" org.postgresql.util.PSQLException: ERROR: You have an error in your SQL syntax: \c test_pg, no viable alternative at input '\' at line 1, position 0, near [@0,0:0='\',<17>,1:0]

so, when i use jdbc  connect shardingsphere proxy, how i switch to other database on postgresql

**Comment by RaigorJiang** [comment]
Hi @static0807 ,
According to the PostgreSQL protocol, you need to re-create the data source connection using the new database(with new jdbc url) after creating it.

**Comment by static0807** [comment]
hi，@Raigorjiang

I tried it . 

First, i create a logic database. and then,i want to register a storage unit. so i must switch  the new logic database.

And i tried to connect to the new logic database without a storage unit, but it failed.

so i must switch to the new logic database first. 

What should I do with jdbc

**Comment by RaigorJiang** [comment]
@static0807 In addition, what is the reason for `re-create the data source connection using the new database, this is impossible without a storage unit .` you described?
