### ISSUE TITLE
When alter rule, all versions are kept in the governance center

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#26831]
### Which version of ShardingSphere did you use?
master 655c75431b0a5f906216f03b7fe0324e40d8dd0b

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When alter rule, only the latest version is kept in the governance center

### Actual behavior
When alter rule, all versions are kept in the governance center

<img width="359" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/348e6901-d2cc-4487-800b-e690cb7fab13">

### Steps to reproduce
1. create a single table t_single by CREATE TABLE statement;
2. drop table t_single;
3. create single table t_single  again.

**Comment by RaigorJiang** [comment]
Hi @zhaojinchao95 , could you help to check?

**Comment by zhaojinchao95** [comment]
> Hi @zhaojinchao95 , could you help to check?

Thx, i will check.
