### ISSUE TITLE
about scaling lost data

### ISSUE THREAD

**Issue by lukylegend** [apache/shardingsphere#26909]
## Question
When migrating single table data to sub-table with sharding-scaling, if the scaling machine is down, then restart and re-submit the task, the incremental data including updating and deleting during the downtime cannot be synchronized to the sub-table, can it be solved? scaling and proxy for version 4.1.1

**Comment by RaigorJiang** [comment]
Hi @lukylegend , 4.1.1 is to old, can you try the latest version 5.4.0?

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
