### ISSUE TITLE
Sharding-proxy connect to new type database

### ISSUE THREAD

**Issue by cxp108** [apache/shardingsphere#26919]
I need  sharding-proxy(version:5.3.2) connect to a new type database(have jdbc driver).  Where should I start?  Is there any tutorial for that?

**Comment by RaigorJiang** [comment]
Proxy currently provides MySQL, PG, and openGauss protocols. 
Adding a new database type means adding front-end and back-end protocol adaptation, SQL parsing, metadata management, transaction management, etc., which is a complex task.
If it is an open source database, we can discuss further.

**Comment by RaigorJiang** [comment]
Closed due to no response.
