### ISSUE TITLE
SPI issue

### ISSUE THREAD

**Issue by corgy-w** [apache/shardingsphere#26918]
## SPI issues

As a beginner, I would like to ask why sharding uses the traditional java util spi loading mechanism as the spi mode, instead of implementing a set of dubbo or spring-like spi mechanism to improve the loading speed.

I hope to see the big brother to give some guidance, this is just a personal humble opinion, may be I do not read enough comprehensive, I hope to get a reply!

Thank you very much!

**Comment by RaigorJiang** [comment]
@corgy-w 
Thanks for your feedback, this topic is interesting, can you provide more information? About how to improve loading speed.
