### ISSUE TITLE
Table 'XX' doesn't exist, when updated 5.4.0 from 5.3.2, with SHARDING rule using CLASS_BASED Algorithms

### ISSUE THREAD

**Issue by SingKS8** [apache/shardingsphere#26924]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior

shardingAlgorithms should work

### Actual behavior

got an exception: 

```log
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement
	at xyz.opcal.demo.service.ShardingLogServiceTest.save(ShardingLogServiceTest.java:45)
Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
	at xyz.opcal.demo.service.ShardingLogServiceTest.save(ShardingLogServiceTest.java:45)
Caused by: java.sql.SQLException: Table 'sharding_log' doesn't exist
	at xyz.opcal.demo.service.ShardingLogServiceTest.save(ShardingLogServiceTest.java:45)
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

I have a demo about table sharding with 'CLASS_BASED' algorithms, using "org.apache.shardingsphere.driver.ShardingSphereDriver" way.

Project structure:
Java: 8
Spring boot: 2.7.13

When I use 5.3.2 version, everything works, after updating 5.4.0, I got an exception above.
At first, I thought does 5.4.0 change some that need to create a table with logic table name "sharding_log", before that I only have sharding tables from "sharding_log_202301" to "sharding_log_202312".
But after creating a table with logic table name, exception is still here

### Example codes for reproduce this issue (such as a github link).

https://github.com/SingKS8/sharding-log-demo.git
(change db config)

**Comment by RaigorJiang** [comment]
Thanks for your feedback, I will investigate this issue

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
