### ISSUE TITLE
CHAR_DIGEST_LIKE  issue

### ISSUE THREAD

**Issue by yuyinw** [apache/shardingsphere#26932]
### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
CHAR_DIGEST_LIKE,  search result  is right
### Actual behavior
1. my test table has two record:

   id       name     phone                 email                         salary
   1        lihu       13877777777       243433@qq.com       15000
   2        liming    13888888888      243232@qq.com       15002

2.  my config:
like encryptor:
     type: CHAR DIGEST LIKE
md5 encryptor:
      type:MD5
tables:
       tbl_info:
       columns:
           salary:
                  cipherColumn: salary
                   encryptorName: aes encryptor
                   assistedQueryColumn:  salary 
                    assistassistedQueryEncryptorName: md5_encryptor
                   likeQueryColumn: salary_like
                    likeQueryEncryptorName: like_encryptor

4. when i search salary like %2, the result is wrong

SELECT *FROM "tbl_info" WHERE (salary like '%2')
[2 rows affected or returned ]
success5
[{1 lihu 138****7777 ******@qq.com 15000} {2 liming 138****8888 ******@qq.com 15002}]
    
### Reason analyze (If you can)
15000 and 15002 using CHAR_ DIGEST_ LIKE fuzzy query algorithm, all results are 04111
so it can not search right result

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?
