### ISSUE TITLE
ORACLE- getIndexInfo is slow，because analyze table compute statistics，can i  send the “true” param to getIndexInfo method？

### ISSUE THREAD

**Issue by linqr** [apache/shardingsphere#26931]
Which version of ShardingSphere did you use?
5.1.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
Start my app as soon as possible，can i send the “true” param to getIndexInfo，close the analyze；

Actual behavior
Load meta data for schema logic_db finished, cost 30 minutter

Reason analyze (If you can)
the method getIndexInfo() in jdbc has 5 param，the 5th param approximate, 
when true, result is allowed to reflect approximate or out of data values; 
when false, results are requested to be accurate，in the oracle jdbc implment, 
if approximate is false, it will analyze table compute statistics, the table records over 10 million，table compute statistics cost too much time, DBAs have their own plans to analyze table compute statistics, so, the param approximate can configure in the rule configuration file?

public static Collection load(final Connection connection, final String table) throws SQLException {
Collection result = new HashSet<>();
try (ResultSet resultSet = connection.getMetaData().getIndexInfo(connection.getCatalog(), connection.getSchema(), table, false, false)) {
while (resultSet.next()) {
String indexName = resultSet.getString(INDEX_NAME);
if (null != indexName) {
result.add(new PhysicalIndexMetaData(indexName));
}
}
}
return result;
}

**Comment by terrymanu** [comment]
The metadata is improved in each version, can you test the latest version?
