### ISSUE TITLE
Support parsing Oracle ALTER SEQUENCE sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#26973]
# Background
Hi community,
This issue is for #26878.

ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Oracle SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more oracle sql parse, as follows:
```sql
ALTER SEQUENCE
CREATE SEQUENCE
DROP SEQUENCE
```

```sql
ALTER DISKGROUP DATA ADD USER 'oracle1';
```

```sql
ALTER DATABASE FLASHBACK OFF;
```

```sql
ALTER ROLE
CREATE ROLE
DROP ROLE
SET ROLE
```

```sql
ALTER SESSION CLOSE DATABASE LINK <name>
```

# Process
1. First confirm that this is a correct oracle sql syntax, if not please ignore;
2. Compare SQL definitions in Oficial SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with Oracle SQLs

**Comment by zihaoAK47** [comment]
Hi, please assign it to me and I will solve it. Thank you

**Comment by zihaoAK47** [comment]
Error sql

SQL> ALTER SEQUENCE;
ALTER SEQUENCE
             *
ERROR at line 1:
ORA-02277: invalid sequence name

SQL> CREATE SEQUENCE;
CREATE SEQUENCE
              *
ERROR at line 1:
ORA-02277: invalid sequence name

SQL> DROP SEQUENCE;
DROP SEQUENCE
            *
ERROR at line 1:
ORA-02277: invalid sequence name

SQL> ALTER ROLE;
ALTER ROLE
         *
ERROR at line 1:
ORA-01935: missing user or role name

SQL> CREATE ROLE;
CREATE ROLE
          *
ERROR at line 1:
ORA-01937: missing or invalid role name

SQL> DROP ROLE;
DROP ROLE
        *
ERROR at line 1:
ORA-01935: missing user or role name

SQL> SET ROLE;
SET ROLE
       *
ERROR at line 1:
ORA-01937: missing or invalid role name

SQL> ALTER SESSION CLOSE DATABASE LINK `<name>`;
ALTER SESSION CLOSE DATABASE LINK `<name>`
                                  *
ERROR at line 1:
ORA-01729: database link name expected

**Comment by strongduanmu** [comment]
Thank you @zihaoAK47, I just assign this issue to you.
