### ISSUE TITLE
Support parsing Oracle ALTER SESSION sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#26974]
# Background
Hi community,
This issue is for #26878.

ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Oracle SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more oracle sql parse, as follows:
```sql
ALTER SESSION FORCE PARALLEL DML PARALLEL degree-of-parallelism;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL degree-of-parallelism;
```

```sql
ALTER SESSION SET CURRENT_SCHEMA = <schema name>
```

```sql
ALTER SESSION SET EVENTS '19119 TRACE NAME CONTEXT FOREVER, LEVEL 0x8';
```

```sql
ALTER SESSION SET <nls_parameter> = <value>
```

```sql
ALTER SESSION SET recyclebin = ON;

ALTER SYSTEM SET recyclebin = ON SCOPE = SPFILE;
```

# Process
1. First confirm that this is a correct oracle sql syntax, if not please ignore;
2. Compare SQL definitions in Oficial SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with Oracle SQLs

**Comment by zihaoAK47** [comment]
Hi, please assign it to me and I will solve it. Thank you

**Comment by zihaoAK47** [comment]
error sql

SQL> ALTER SESSION FORCE PARALLEL DML PARALLEL degree-of-parallelism;
ALTER SESSION FORCE PARALLEL DML PARALLEL degree-of-parallelism
                                          *
ERROR at line 1:
ORA-00933: SQL command not properly ended

SQL> ALTER SESSION FORCE PARALLEL QUERY PARALLEL degree-of-parallelism;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL degree-of-parallelism
                                            *
ERROR at line 1:
ORA-00933: SQL command not properly ended

SQL> ALTER SESSION SET CURRENT_SCHEMA = <schema name>;
ALTER SESSION SET CURRENT_SCHEMA = <schema name>
                                   *
ERROR at line 1:
ORA-02421: missing or invalid schema authorization identifier

SQL> ALTER SESSION SET <nls_parameter> = <value>;
ALTER SESSION SET <nls_parameter> = <value>
                  *
ERROR at line 1:
ORA-00922: missing or invalid option

**Comment by strongduanmu** [comment]
Good job, assigned. @zihaoAK47
