### ISSUE TITLE
Support parsing Oracle SWITCH DATABASE sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#27168]
# Background
Hi community,
This issue is for #26878.

ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Oracle SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more oracle sql parse, as follows:
```sql
SWITCH DATABASE TO COPY;
```

```sql
UPDATE SP PARTITION 
   (DATAOBJ_TO_PARTITION(
      base_table_name, :tab_physical_partid)) 
   VALUES(鈥) SET val = :newval WHERE rowid + :rowid;
```

```sql
UPDATE employees
   salary = salary*1.1
  WHERE employee_id = 100;
```

```sql
UPDATE employees
  SET job_id ='SA_MAN', salary = salary + 1000, department_id = 140
  WHERE last_name = 'Jones'
  RETURNING salary*0.25, last_name, department_id
    INTO :bnd1, :bnd2, :bnd3;
```

```sql
UPDATE employees
   SET salary = salary * 1.1
   WHERE department_id = 100
   RETURNING SUM(salary) INTO :bnd1;
```

# Process
1. First confirm that this is a correct oracle sql syntax, if not please ignore;
2. Compare SQL definitions in Oficial SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with Oracle SQLs

**Comment by chakkk309** [comment]
Hi, I wanna support this SQL statement, plz assign it to me, Thanks!

**Comment by strongduanmu** [comment]
@chakkk309 Welcome back. I just assign this issue to you.
