### ISSUE TITLE
Why is spring boot starter removed from the 5.3.0 documentation?

### ISSUE THREAD

**Issue by whiteS18** [apache/shardingsphere#27174]
When I first learned about this project, when I looked at the documentation, there were only shardingsphere-jdbc-core related dependencies, but the blog was full of ShardingSphere-JDBc-core-spring-boot-starter content. It's not friendly : (

**Comment by linghengqian** [comment]
- Hi, you can see related material in https://github.com/apache/shardingsphere/issues/22469 , this is particularly affected by the committer energy shortage.

**Comment by whiteS18** [comment]
> * Hi, you can see related material in [Removing Spring configuration from ShardingSphere #22469](https://github.com/apache/shardingsphere/issues/22469) , this is particularly affected by the committer energy shortage.

thks.
