### ISSUE TITLE
Does HintShardingAlgorithm support multiple master and multiple slave routes?

### ISSUE THREAD

**Issue by houxiaodong5** [apache/shardingsphere#27173]
When using HintShardingAlgorithm for forced routing, is it possible to support multiple masters and slaves? During the use of custom forced routing rules to switch between masters and slaves, inconsistencies were found in the data between the two.

**Comment by RaigorJiang** [comment]
Hi @houxiaodong5 
Are there multiple masters in your environment? Is there a sharding rule?
Please follow the issue template to ask questions and provide sample configurations so that we can communicate more accurately.

**Comment by RaigorJiang** [comment]
Closed due to no response.
