### ISSUE TITLE
I have already build project success but can not find ShardingSphereVersion.VERSION

### ISSUE THREAD

**Issue by whiteS18** [apache/shardingsphere#27176]
I have already build project success. But when I debug ExampleGeneratorMain::main, there are two error:  in ExampleGenerator::buildDataModel:
1.getType() return a Object but result require String
2.Cannot resolve symbol 'ShardingSphereVersion'

![image](https://github.com/apache/shardingsphere/assets/31566522/008acc2b-3610-4503-ab91-3f73fb69aee2)
![image](https://github.com/apache/shardingsphere/assets/31566522/75d19061-4fc4-47a2-8499-275d99ef002f)
![image](https://github.com/apache/shardingsphere/assets/31566522/a68396ae-c748-4732-a0ce-6dac0ae8c4d5)

**Comment by whiteS18** [comment]
ps.  my jdk version was adoptium jdk 17

**Comment by RaigorJiang** [comment]
@whiteS18 
Thanks for the feedback, did you find any problems after debugging?

**Comment by whiteS18** [comment]
> @whiteS18 Thanks for the feedback, did you find any problems after debugging?

No, I usually use debug XXX instead of Run XXX,
But when I run ExampleGeneratorMain: : the main, ExampleGenerator: : buildDataModel will have the idea of the tests. I see TypedSPI: : getType implementation classes or inheritance in the interface returns the type of the String and the DataBaseType, but in ExampleGenerator: : buildDataMode, receives the Map types as HashMap, And ExampleScenarioFactory: : use in judging frameworkScenario and transactionScenario getJavaClassTemplateMap is String: : the contains (FrameworkE Inherited TypedSPI xampleScenario, TransactionExampleScenario interface, so both the getType return value is the Object of the interface type, result in an error). About other ExampleGenerator: : buildDataModel on tip always resolve a symbol 'ShardingSphereVersion temporarily also don't know how to solve.

**Comment by RaigorJiang** [comment]
PR #27307 may solve the problem you encountered.
