### ISSUE TITLE
In a springboot project, how do I get a data source through annotations

### ISSUE THREAD

**Issue by doveylovey** [apache/shardingsphere#27198]
In a springboot project, how do I get a data source through @Autowired

![image](https://github.com/apache/shardingsphere/assets/28882195/4fd00cec-8bc2-443a-acb9-929e3df89ff9)

No value can be obtained in this way。

**Comment by RaigorJiang** [comment]
It looks like there is already a HikariDataSource object, what do you want to get? @doveylovey

**Comment by doveylovey** [comment]
> It looks like there is already a HikariDataSource object, what do you want to get? @doveylovey

No, I didn't get it. It's empty.
I want to get the shardingsphere datasource manually and then use it.

**Comment by RaigorJiang** [comment]
@doveylovey 
In your application, `ShardingSphereDataSource` is not registered as a bean, so it cannot be obtained through annotations.
You can define a method to register the bean yourself

**Comment by StarHuzy** [comment]
> @doveylovey In your application, `ShardingSphereDataSource` is not registered as a bean, so it cannot be obtained through annotations. You can define a method to register the bean yourself

hello, I also want to obtain this `ShardingSphereDataSource` for shardingsphere- jdbc-5.3.2   Refresh  `actualDataNodes` ，
But it is always null ，Do I have any other ways to obtain it？
