### ISSUE TITLE
Refactor PipelineImportSQLBuilder.sqlCacheMap

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#27235]
Currently, related code is:
```
    private final ConcurrentMap<String, String> sqlCacheMap;
```
1, We could use `Caffeine` to replace `ConcurrentMap`. Refer to `ShardingRouteCache` Caffeine usage as an example.

2, `sqlCacheMap` could be renamed to `sqlCache`.

**Comment by pandalee99** [comment]
I want to try to solve this issue. Please assign it to me.thanks！

**Comment by sandynz** [comment]
Hi @pandalee99 , welcome!
