### ISSUE TITLE
Why there are multiple HikariPools

### ISSUE THREAD

**Issue by silence1005** [apache/shardingsphere#27310]
I would like to ask, is there any problem with my configuration? After the project starts, there are 3 HikariPools. When operating the database, pool -1 is always used, but the default maximum number of connections of pool -1 is only 10. In the case of multi-threading, pool - 1 will report an error, indicating that the connection cannot be obtained. The connection pool of pool -3 is sufficient, and its number of connections is equal to what I configured, but pool - 3 has not been accessed much. Please tell me the data related to the connection pool. I am in pool -1 Do I have to configure it again? Supplement: 1. My project only uses sub-tables, there is no sub-library, so there is only one ds. 2. I have 40 tasks that need to use database connections. The core thread pool is 15. In debug mode, I found that: 15 threads are opened at one time, all of which get connections from pool -1, and then get connections occasionally. Get it from pool-3. 3. Now report an error message: pool -1 cannot obtain a connection. It calls the borrow method in hikari, the number of shareList is 10, it cannot get the link, enters the wait, and then times out and reports an error. 4. The size of shardList in pool-3 is equal to my configuration: 60

![image](https://github.com/apache/shardingsphere/assets/33715026/b76db418-df19-4859-88ee-2cd45c64ad39)

![f82fd92e0249619339311a032996990](https://github.com/apache/shardingsphere/assets/33715026/d19e885e-4bfd-4070-bc42-93b437ac199f)
![2c7fcf1a4cd8903e59cff22e0f5da18](https://github.com/apache/shardingsphere/assets/33715026/48b3e3fc-615e-493d-b297-5a4f119648b6)
![image](https://github.com/apache/shardingsphere/assets/33715026/dd2de657-598c-4081-806b-bc608e2f43ea)
![image](https://github.com/apache/shardingsphere/assets/33715026/bab88e7c-c7ae-4b54-93cb-97d1df8263e0)

**Comment by RaigorJiang** [comment]
Hi @silence1005 , **For English only**, other languages will not accept.

When using springboot, pool-1 is the connection obtained by your application from `ShardingSphereDataSource`, and pool-3 is the connection obtained by `ShardingSphereDataSource` from mysql.
(pool-2 should be used for test connection and has been closed)

In `sharding-dev.yaml`, the `maxPoolSize` you configure only affects the number of connections `ShardingSphereDataSource` obtains from mysql, and pool-1 uses the default configuration of hikari `maximumPoolSize` 10 because there is no configuration. (Ref https://github.com/brettwooldridge/HikariCP `maximumPoolSize`)


You can specify the size of pool-1 by `spring.datasource.hikari.maximum-pool-size`=xx

**Comment by silence1005** [comment]
Thank you for your answer! In fact, I solved my error problem by configuring the POOL -1 connection pool parameter yesterday. But what I am tangled is that as long as it involves the related configuration of the connection pool, I have to repeat the configuration on the POOL -1 when I configure it in POOL -3? And why most of the database requests are implemented by POOL -1 instead of POOL -3?

**Comment by RaigorJiang** [comment]
Pool-1 is your application getting connections from ShardingSphereDataSource, pool-3 is ShardingSphereDataSource getting connections from mysql, and their scopes are different.
Maybe you can enable hikari logging to find out more information.

**Comment by RaigorJiang** [comment]
> > 
> 
> Since the configuration of our data source will take effect in pool3, if I configure the druid used by the data source, will pool-3 also use the druid?

ShardingSphere can support any connection pool, but some special attributes of druid may not work well, such as filter.
