### ISSUE TITLE
Add unit test for ProjectionUtils public method

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#27317]
This issue is to add unit tests for the ProjectionUtils class, it includes the following subtasks:

- [ ]  ProjectionUtils#getColumnLabelFromAlias
- [ ]  ProjectionUtils#getColumnNameFromFunction

You can refer this pr - https://github.com/apache/shardingsphere/pull/25386 to add unit test.

**Comment by pandalee99** [comment]
I want to try to solve this issue.  Please assign it to me.thanks！

**Comment by strongduanmu** [comment]
Welcome @pandalee99, I just assign this issue to you.
