### ISSUE TITLE
Optimize algorithm name in all yaml configuration

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#27330]
Reason #27329.
 
Global search shardingAlgorithms configuration for `*.yaml`, change algoritm name `-` separator to `_` separator, And modify the referenced this algoritm name place.
 
Such as:

<img width="1345" alt="image" src="https://github.com/apache/shardingsphere/assets/33742097/2ea7bc11-49d4-4205-aac2-2e0f452085f9">

**Comment by zihaoAK47** [comment]
Hi, can I take a look at this question
