### ISSUE TITLE
认证授权配置后启动sharding proxy，再次修改认证授权配置不生效

### ISSUE THREAD

**Issue by gefufeng** [apache/shardingsphere#27332]

**Comment by Pace2Car** [comment]
The community uses English for communication, please translate.

And please follow the template to supplement the issue.

**Comment by gefufeng** [comment]
After authentication and authorization are configured, the sharding proxy is started，Modifying the authentication and authorization configurations again does not take effect

**Comment by gefufeng** [comment]
![image](https://github.com/apache/shardingsphere/assets/9637787/381e6042-fc8b-48f1-81e0-416ad423b351)
Dynamic changes do not take effect

**Comment by Pace2Car** [comment]
Cluster mode does not support overriding configuration now, clear the namespace or use a new one.

Refer to: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/

**Comment by zhaojinchao95** [comment]
@gefufeng It 's only support questions in English, i close it, you can create a new issue with English.
