### ISSUE TITLE
about alias (.SQLFeatureNotSupportedException: Can not get index from column label)

### ISSUE THREAD

**Issue by 041tjpu** [apache/shardingsphere#27346]
I found that if the fields before the alias are the same, an error will be reported as follows，But in the actual process, I will encounter this situation. The version is ShardingSphere-jdbc 5.3.2

SELECT '1' flag1,'1' flag2 from  test ,

thanks!!

**Comment by zhaojinchao95** [comment]
Can you try it with `5.4.0`?

**Comment by 041tjpu** [comment]
5.3.2  ：
SELECT '1' flag1,'2' flag2 from test , this is ok
now,I try 5.4.0
thanks

**Comment by 041tjpu** [comment]
> Can you try it with `5.4.0`?

I have just upgraded from version 5.3.2 to 5.4.0, and the previous problem has been solved. There is a new problem, the table without sharding Settings cannot be found. (door_record is my sharding table, and notice is the table without setting. The error is "Table 'notice' doesn't exist") My configuration is:

mode:
type: Standalone
repository:
type: JDBC
dataSources:
ds_0:
connectionProperties: druid.stat.mergeSql=true; druid.stat.slowSqlMillis=5000
minIdle: 5
validationQuery: SELECT 1 FROM sys_user
initialSize: 5
maxWait: 60000
#    filters: stat,wall,log4j
poolPreparedStatements: true
dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
maxPoolPreparedStatementPerConnectionSize: 20
testOnBorrow: true
testWhileIdle: true
minEvictableIdleTimeMillis: 300000
timeBetweenEvictionRunsMillis: 60000
testOnReturn: false
maxActive: 20
driverClassName: com.mysql.jdbc.Driver
username: root
Url: JDBC: mysql: / / 127.0.0.1:3306 / screen111? useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
password: root
rules:
-! SHARDING
tables:
door_record:
actualDataNodes: ds_0.door_record_$->{202305.. 202307}
tableStrategy:
standard:
shardingColumn: addtime
shardingAlgorithmName: door_interval
keyGenerateStrategy:
column: guid
keyGeneratorName: snowflake
bindingTables:
- door_record
defaultTableStrategy:
none:
shardingAlgorithms:
door_interval:
type: INTERVAL
props:
datetime-pattern: 'yyyy-MM-dd HH:mm:ss'
datetime-lower: '2023-05-01 00:00:00'
datetime-upper: '2023-08-01 00:00:00'
sharding-suffix-pattern: 'yyyyMM'
datetime-interval-amount: 1
datetime-interval-unit: 'MONTHS'
keyGenerators:
snowflake:
type: SNOWFLAKE
props:
sql-show: false @

**Comment by 041tjpu** [comment]
add config :
  - !SINGLE
    tables:
      # MySQL 风格
      - ds_0.* # 加载指定数据源中的全部单表
#      - "*.*" # 加载全部单表
    defaultDataSource: ds_0
