### ISSUE TITLE
How to configure the default data source in 5.4.0

### ISSUE THREAD

**Issue by bpzhang** [apache/shardingsphere#27342]
The defaultDataSourceName configuration was removed in the 5.x version, how do I configure this now.
For example, I have four data sources, 4 sub-libraries and sub-tables and 1 single library and single table, now I am going to configure the single library and single table's as the default data source, how do I configure this?

**Comment by zhaojinchao95** [comment]
I think you needn't to consider `defaultDataSourceName`. Because `ShardingSphere` can automatic identification of single table.

**Comment by bpzhang** [comment]
> I think you needn't to consider `defaultDataSourceName`. Because `ShardingSphere` can automatic identification of single table.

No, I need to, because the SS doesn't point to the data source of a single database table by default.

**Comment by bpzhang** [comment]
> 

In other words, how do I specify a specific data source as the default data source

**Comment by magicodex** [comment]
> > 
> 
> In other words, how do I specify a specific data source as the default data source

Same question [https://github.com/apache/shardingsphere/issues/9524#issuecomment-1684903475](https://github.com/apache/shardingsphere/issues/9524#issuecomment-1684903475)

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
