### ISSUE TITLE
Add unit test for MaskRuleConfigurationChecker

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#27417]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for MaskRuleConfigurationChecker to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by strongduanmu** [comment]
Welcome @kyooosukedn .

**Comment by kyooosukedn** [comment]
Hi @strongduanmu ,Unfortunately I still got an error on this: import org.apache.shardingsphere.test.fixture.jdbc.MockedDataSource;
I'm not sure why the package "jdbc" doesn't exist, my build is still failing because of this class.
