### ISSUE TITLE
In sharing-jdbc 5.4.0, insert stament all columnNames to lowerCase

### ISSUE THREAD

**Issue by bpzhang** [apache/shardingsphere#27424]
## Bug Report
Version: 5.4.0

I'm using sharding-jdbc, in the insert statement has a case-sensitive field, there will be more than one sharding condition, I debug the source code to find out, because, the source code in the insert statement to get the field, all converted to lowercase, This results in fields that exist being judged as non-existent, for example, accountNo and accountno, which will be judged as accountNo being a non-existent field, and then there will be a field that has two slice conditions, one normal and one with the value null, and then when the value is assigned, the null value overwrites the normal value
<img width="847" alt="image" src="https://github.com/apache/shardingsphere/assets/1734396/b905d899-c0e7-4053-abc3-f9f7df27054a">

**Comment by RaigorJiang** [comment]
ShardingSphere adopts a case-insensitive strategy, which is matched in lowercase

**Comment by RaigorJiang** [comment]
Yes, the same column names (different capitalization) should not appear in one table.
@bpzhang  Can you raise a PR if you think this should be optimized?

**Comment by bpzhang** [comment]
> Yes, the same column names (different capitalization) should not appear in one table. @bpzhang Can you raise a PR if you think this should be optimized?

OK！I will raise a PR.
