### ISSUE TITLE
The api for the broadcast table is gone

### ISSUE THREAD

**Issue by zhoubin7** [apache/shardingsphere#27423]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior
ShardingRuleConfiguration.broadcastTables
why delete the api?

### Actual behavior
I use the Java Api to configure,Tell me how to configure the broadcast table

**Comment by zhaojinchao95** [comment]
Please refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/broadcast/
