### ISSUE TITLE
Does the current version 5.4.0 still not support multiple SQL statements

### ISSUE THREAD

**Issue by 041tjpu** [apache/shardingsphere#27422]
Does the current version 5.4.0 still not support multiple SQL statements, such as:

<update id="saveOther" parameterType="Object">

Insert into school (name) values (# {name});

Insert into sys_ User (name) values (# {name});

</update>

The two tables above are not the ones I need to shard. Currently, I am doing sharding on the same database,

Do I have to split the above statement into two methods? There are many cases in my project, or is there any other way，Thanks!

**Comment by 041tjpu** [comment]
《update id="saveOther" parameterType="Object"》
        insert into school (name) values (#{name});
        insert into sys_user (guid,name)
        values (uuid(),#{name});
    《/update》

**Comment by 041tjpu** [comment]
《update id="saveOther" parameterType="Object"》
        insert into school (name) values (#{name});
        insert into sys_user (name) values (#{name});
    《/update》

**Comment by azexcy** [comment]
@tuichenchuxin Could you help answer whether it is currently supported?

**Comment by tuichenchuxin** [comment]
May not support now if you use sharding.
But you can try first.

**Comment by xiaomizhou2** [comment]
Multi-sql throws an exception when any function is used
