### ISSUE TITLE
When Proxy metadata info and backend jdbc connecntion metadata info has diff, execute sql throws "Column index out of range" 

### ISSUE THREAD

**Issue by git-chenhao** [apache/shardingsphere#27479]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Normal execution

### Actual behavior
 execute sql throws "Column index out of range" 

When Proxy metadata info and backend jdbc connecntion metadata info has diff
eg ：
```
logic_table: table_a
actual_table: table_a_0~table_a_9
route rule:  table_a_${id%10}

logic sql：select * from table_a where id =8
actual sql：select * from table_a_9 where id =8

where sql execute 
table_a_0 - table_5 has 10 column
table_a_6 - table_9 has 9 column

Proxy metadata: has 10 column
backend jdbc connection metadata: has 9 column
```
execute sql throws "Column index out of range" 

### Reason analyze (If you can)

https://github.com/apache/shardingsphere/blob/master/proxy/backend/core/src/main/java/org/apache/shardingsphere/proxy/backend/connector/DatabaseConnector.java#L315
<img width="1134" alt="image" src="https://github.com/apache/shardingsphere/assets/20919316/f6d07357-bbbc-4633-9911-16d77dcdb032">

getColumnCount from proxy metadata, is 10, but backend jdbc connection metadata only have 9 column

https://github.com/apache/shardingsphere/blob/master/proxy/backend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/backend/mysql/response/header/query/MySQLQueryHeaderBuilder.java#L40
<img width="1088" alt="image" src="https://github.com/apache/shardingsphere/assets/20919316/0960d54f-f43f-405e-9e40-ba01b17b7551">
this line throws "Column index out of range" 

why  getColumnCount from proxy metadata info ? Mainly to solve what problem

**Comment by git-chenhao** [comment]
@zhaojinchao95 Can you help me？😭

**Comment by git-chenhao** [comment]
@strongduanmu Can you help me？😭

**Comment by RaigorJiang** [comment]
Hi @git-chenhao 
Why the metadata has difference?  JDBC & Proxy are not in a cluster?

**Comment by git-chenhao** [comment]
> Hi @git-chenhao Why the metadata has difference? JDBC & Proxy are not in a cluster?

@RaigorJiang The DDL execution is not in the proxy, and it cannot be guaranteed that the DDL is consistent when the proxy refreshes the metadata. Is there any way to make compatibility at the code level？

**Comment by RaigorJiang** [comment]
@git-chenhao 
Sorry for the late reply, there is a DistSQL that can trigger Proxy to refresh metadata:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata/

**Comment by RaigorJiang** [comment]
Since the issue has been inactive for a long time, I will close it first. If you still have questions, please reopen it or submit a new one
