### ISSUE TITLE
SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.transaction.xa.jta.connection.XAConnectionWrapper` with type `SQLServer`.

### ISSUE THREAD

**Issue by huangconghe** [apache/shardingsphere#27476]
springboot + sqlserver + shariding-jdbc 5.1.2
user @ShardingSphereTransactionType(TransactionType.XA) 
insert data to sqlserver db 
cause exception 

 SPI-00001: No implementation class load from SPI `org.apache.shardingsphere.transaction.xa.jta.connection.XAConnectionWrapper` with type `SQLServer`.

**Comment by strongduanmu** [comment]
@huangconghe Yes, ShardingSphere does not yet implement XA functionality for SQLServer, are you interested in doing this?
