### ISSUE TITLE
Error querying database.  Cause: java.sql.SQLException: Table 'user_order' doesn't exist

### ISSUE THREAD

**Issue by qiuweilu** [apache/shardingsphere#27494]
<dependency>
        <groupId>org.apache.shardingsphere</groupId>
        <artifactId>shardingsphere-jdbc-core</artifactId>
        <version>5.4.0</version>
    </dependency>

application.properties
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yaml

**springboot 2.7
    @Scheduled(cron = "0 */2 * * * ?", zone = "Asia/Shanghai")
    protected void pay() {
......
         return userOrderMapper.selectByExample(example);
......
    }

Error querying database. Cause: java.sql.SQLException: Table 'user_order' doesn't exist
user_ order is a single table without sharding**

sharding.yaml
#spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
#spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yaml

mode:
  type: Standalone
  repository:
    type: JDBC

dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/foxwish?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

rules:
  - !SHARDING
    tables:
      user_media:
        actualDataNodes: ds_0.user_media_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_media_inline
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline
      part_vote:
        actualDataNodes: ds_0.part_vote_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_vote_inline

    shardingAlgorithms:
      t_media_inline:
        type: INLINE
        props:
          algorithm-expression: user_media_${part_fkid % 10}
      t_cmnt_inline:
        type: INLINE
        props:
          algorithm-expression: part_cmnt_${part_fkid % 10}
      t_vote_inline:
        type: INLINE
        props:
          algorithm-expression: part_vote_${part_fkid % 10}

props:
  sql-show: true

**Comment by qiuweilu** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.4.0</version>
        </dependency>

**springboot 2.7
@Scheduled(cron = "0 */2 * * * ?", zone = "Asia/Shanghai")

Error querying database.  Cause: java.sql.SQLException: Table 'user_order' doesn't exist
user_ order is a single table without sharding**




mode:
  type: Standalone
  repository:
    type: JDBC


dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/foxwish?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


rules:
  - !SHARDING
    tables:
      user_media:
        actualDataNodes: ds_0.user_media_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_media_inline
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline
      part_vote:
        actualDataNodes: ds_0.part_vote_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_vote_inline
      part_apply:
        actualDataNodes: ds_0.part_apply_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_apply_inline
      act_stats:
        actualDataNodes: ds_0.act_stats_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_stats_inline
      user_earn:
        actualDataNodes: ds_0.user_earn_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_earn_inline


    shardingAlgorithms:
      t_media_inline:
        type: INLINE
        props:
          algorithm-expression: user_media_${part_fkid % 10}
      t_cmnt_inline:
        type: INLINE
        props:
          algorithm-expression: part_cmnt_${part_fkid % 10}
      t_vote_inline:
        type: INLINE
        props:
          algorithm-expression: part_vote_${part_fkid % 10}
      t_apply_inline:
        type: INLINE
        props:
          algorithm-expression: part_apply_${part_fkid % 10}
      t_stats_inline:
        type: INLINE
        props:
          algorithm-expression: act_stats_${part_fkid % 10}
      t_earn_inline:
        type: INLINE
        props:
          algorithm-expression: user_earn_${part_fkid % 10}


props:
  sql-show: true

**Comment by kimmking** [comment]
where is the user_order table config?

**Comment by strongduanmu** [comment]
Hi @qiuweilu , you can add following config if you want to load all single tables.

```
- !SINGLE
  tables:
    - "*.*"
```

**Comment by qiuweilu** [comment]
> user_order

user_order  is a single table

**Comment by qiuweilu** [comment]
> Hi @qiuweilu , you can add following config if you want to load all single tables.
> 
> ```
> - !SINGLE
>   tables:
>     - "*.*"
> ```

Thank you. After reading the official document, I didn't write it clearly

**Comment by freenet-233** [comment]
How to solve it via JAVA API ?

**Comment by sunlife95** [comment]
> How to solve it via JAVA API ?

i solved with this code

     /**
     * 初始化单表规则
     */
    private SingleRuleConfiguration getSingleRuleConfiguration() {

        List<String> singleTableList = Lists.newArrayList();

        singleTableList.add("*.*");

        return new SingleRuleConfiguration(singleTableList, "ds_0");
    }

when i init datasource 

        // 单表配置
       SingleRuleConfiguration singleRuleConfiguration = getSingleRuleConfiguration();

       ShardingSphereDataSourceFactory.createDataSource("ds_0", new ModeConfiguration("Standalone", null), createDataSourceMap(), Lists.newArrayList(shardingRuleConfiguration, readwriteSplittingRuleConfiguration), props);

it's not standard code ~ but it worked in my project
