### ISSUE TITLE
Two questions about agent

### ISSUE THREAD

**Issue by corgy-w** [apache/shardingsphere#27578]
Q: sharding agent monitoring just support proxy mode can be observed, the jdbc can be?
Q:Is there a corresponding agnet case? I can't find any.

**Comment by RaigorJiang** [comment]
Hi @corgy-w 
Now agent can support ShardingSphere-JDBC, please refer the document:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/observability/

And there is an article on how to use it with ShardingSphere-JDBC
https://mp.weixin.qq.com/s/DzZjNvkF5_Cjm9gom1tbfQ

**Comment by corgy-w** [comment]
> Hi @corgy-w Now agent can support ShardingSphere-JDBC, please refer the document: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/observability/
> 
> And there is an article on how to use it with ShardingSphere-JDBC https://mp.weixin.qq.com/s/DzZjNvkF5_Cjm9gom1tbfQ

@RaigorJiang 
The agent support for sharding is from 5.3.2, I would like to retrofit it to support 5.2.1, the company's second development is based on 5.2.1, is the possibility there? I haven't started looking at the relevant code yet, just want to politely ask you about the feasibility for my next research, thanks!

**Comment by RaigorJiang** [comment]
@corgy-w 
I think it's very difficult, on the contrary, it's easier to upgrade the SS version, and there are other tons of improvements.

**Comment by corgy-w** [comment]
@RaigorJiang thanks!
