### ISSUE TITLE
why is it converted to lower case when getting table names and column names

### ISSUE THREAD

**Issue by bpzhang** [apache/shardingsphere#27571]
A design question, why is it converted to lower case when getting table names and column names?
<img width="899" alt="image" src="https://github.com/apache/shardingsphere/assets/1734396/ed664259-204e-4991-acf5-ff8c5812a81c">

**Comment by RaigorJiang** [comment]
@bpzhang 
At present, the information saved in the metadata is all lowercase, which is convenient for query.
