### ISSUE TITLE
oracle  count npe

### ISSUE THREAD

**Issue by dantqf** [apache/shardingsphere#27586]
oracle
shardingsphere 5.2.1
mybatis-plus 3.5.3.1
![图片](https://github.com/apache/shardingsphere/assets/11937350/cac297b5-df8a-4691-8ca4-86f10862f10e)
执行 SELECT COUNT( * ) AS total FROM t_order 报错
![图片](https://github.com/apache/shardingsphere/assets/11937350/90cfbfd0-f37d-4b0e-acfa-7cbfea41c265)

**Comment by azexcy** [comment]
@dantqf Thank you for your feedback, can you use the latest version to test (5.4.0) whether this problem can still be reproduced?

**Comment by strongduanmu** [comment]
Can you check that the actual table is consistent with the table in Oracle, including capitalization?

**Comment by dantqf** [comment]
Changing the table name to uppercase in the configuration file will solve the problem,Thank you very much!
