### ISSUE TITLE
Is ShardingSphere 4.1.1 version compatible with Spring Boot 3.0.5 version?

### ISSUE THREAD

**Issue by wangliguokaka** [apache/shardingsphere#27597]
when I hava upgrade springboot version from 2.x to 3.x， ShardingSphere config doesn‘t work。
Is ShardingSphere 4.1.1 version compatible with Spring Boot 3.0.5 version?
Does the YML file need to be modified?

**Comment by RaigorJiang** [comment]
4.1.1 is too old, you can try version latest 5.4.0

**Comment by wangliguokaka** [comment]
the last version of sharding-jdbc-spring-boot-starter is 4.1.1，
the last version of shardingsphere-jdbc-core  is 5.4.0
do I only need to upgrade the shardingsphere-jdbc-core jar package？

**Comment by RaigorJiang** [comment]
@wangliguokaka 
Yes, starting from 5.3.0, ShardingSphere no longer provides spring-boot-starter (there are configuration differences between different versions of spring boot, which consume a lot of maintenance time)
With the new ShardingSphereDriver, any spring boot version can be adapted.

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

#### Article for reference
https://mp.weixin.qq.com/s/wb5fgYzI8k5UQ_-NodpjVA

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
