### ISSUE TITLE
Cannot parse BYTEA on PostgreSQL and OpenGauss

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#27593]
## Bug Report
**typeName** syntax  does not support BYTEA
![image](https://github.com/apache/shardingsphere/assets/20572131/85193e7e-d8e9-49bd-a37d-e6fb7dac0a33)

statement:
```sql
select encode(test_datetype_col::bytea,'escape') from public.test_bytea
```

![image](https://github.com/apache/shardingsphere/assets/20572131/c90cd958-8986-4aa5-966c-f739525fc512)

This is a correct statement in PostgreSQL/OpenGauss:
![image](https://github.com/apache/shardingsphere/assets/20572131/554d152e-1bed-4040-aa9e-9b854af6bf26)

**Comment by strongduanmu** [comment]
HI @jiangtao69039 thank you for your feedback. Can you try to solve this exception?

**Comment by jiangtao69039** [comment]
please assign to me.

**Comment by jiangtao69039** [comment]
Who can review this pr? (#27602)
