### ISSUE TITLE
shardingsphere 5.4.0+mybaties;  when getGeneratedKeys it return empty ResultSet when after executeBatch

### ISSUE THREAD

**Issue by archlevel** [apache/shardingsphere#27600]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
I want to use sharedsphere+mybaties to perform batch database processing operations; when I use the following code to operate, I can't get the key returned by inserting;
eg:
connection = sqlSession. getConnection();
preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
... //set params
preparedStatement. addBatch();
...
preparedStatement. executeBatch();
...
resultSet = preparedStatement. getGeneratedKeys();
while(resultSet.next()){//Always return false; can you tell me why? Am I using it wrong?
     //Can't enter here, resulting in cannot getting the key returned by the database operation
}
### Actual behavior
it always get empty resultSet;
### Reason analyze (If you can)
When I call getGeneratedKeys, the batchPreparedStatementExecutor has been cleared by the finally module of executeBatch calling clearBatch() 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL:
insert into targets_system (subject,`code`, `name`, `count`, hierarchy,create_by,update_by)
        values (#{subject},#{code},#{name},#{count},#{hierarchy},#{createBy},#{updateBy})
Config:

rules:
- !SINGLE
  tables:
    - "*.*"
- !SHARDING
  tables:
    quiz_question_reply:
      actualDataNodes: ds_1.quiz_question_reply_202307
      tableStrategy:
        standard:
          shardingColumn: create_on #任务创建时间 mybaties的xml-sql语句配置必须含有create_on字段
          shardingAlgorithmName: quiz_question_reply_create_on
    quiz_member:
      actualDataNodes: ds_1.quiz_member_202307
      tableStrategy:
        standard:
          shardingColumn: create_on #任务创建时间 mybaties的xml-sql语句配置必须含有create_on字段
          shardingAlgorithmName: quiz_member_create_on
    quiz_student_report:
      actualDataNodes: ds_1.quiz_student_report_${0..49}
      tableStrategy:
        standard:
          shardingColumn: student_id
          shardingAlgorithmName: quiz_student_report_inline
  shardingAlgorithms:
    quiz_question_reply_create_on:
      type: CLASS_BASED
      props:
        sufixFormat: yyyyMM
        strategy: STANDARD
        algorithmClassName: com.yeker.sdk.sharding.algorithm.DateShardingAlgorithm
    quiz_member_create_on:
      type: CLASS_BASED
      props:
        sufixFormat: yyyyMM
        strategy: STANDARD
        algorithmClassName: com.yeker.sdk.sharding.algorithm.DateShardingAlgorithm
    quiz_student_report_inline:
      type: INLINE
      props:
        algorithm-expression: quiz_student_report_${student_id % 50}

props:
  sql-show: true

Result:
just get empty ResultSet when call preparedStatement. getGeneratedKeys();

### Example codes for reproduce this issue (such as a github link).

public static <E> int[] executeBatch(SqlSessionFactory sessionFactory, Logger log, String sql, Integer batchSize,Integer fetchSize, Collection<E> list, BiConsumer<PreparedStatement, E> consumer) {
        Assert.isFalse(batchSize < 1, BATCH_SIZE_MSG);
        Assert.isFalse(CollectionUtils.isEmpty(list), DATA_EMPTY_MSG);
        ResultSet resultSet = null;
        int size = list.size();
        int i = 1;
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        List<Integer> efts = new ArrayList<>();

        SqlSessionHolder sqlSessionHolder = (SqlSessionHolder) TransactionSynchronizationManager.getResource(sessionFactory);
        boolean transaction = TransactionSynchronizationManager.isSynchronizationActive();
        if (sqlSessionHolder != null) {
            SqlSession sqlSession = sqlSessionHolder.getSqlSession();
            sqlSession.commit(!transaction);
        }
        SqlSession sqlSession = sessionFactory.openSession(ExecutorType.BATCH);
        if (!transaction) {
            log.warn("SqlSession [" + sqlSession + "] was not registered for synchronization because DataSource is not transactional");
        }
        long start = System.currentTimeMillis();
        try {
            connection = sqlSession.getConnection();
            boolean insert = false;
            if (insert = (sql.toLowerCase().contains("insert"))) {
                preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            } else {
                preparedStatement = connection.prepareStatement(sql);
            }
            if(fetchSize!=null){
                preparedStatement.setFetchSize(fetchSize);
            }

            List<E> batchs = new ArrayList<>();
            for (E element : list) {
                consumer.accept(preparedStatement, element);
                batchs.add(element);
                preparedStatement.addBatch();
                if(insert){
                    efts.add(1);
                }
                if ((i % batchSize == 0) || i == size) {
                    int[] batchEftArrays = preparedStatement.executeBatch();
                    if(!insert){
                        List<Integer> eftList = Arrays.stream(batchEftArrays).boxed().collect(Collectors.toList());
                        efts.addAll(eftList);
                    }
                    if(!transaction){
                        sqlSession.commit(!transaction);
                        log.info(String.format("executeBatch manual =%s timeused %s",transaction, (System.currentTimeMillis()-start)));
                    }
                    else{
                        log.info(String.format("executeBatch transaction =%s timeused %s",transaction, (System.currentTimeMillis()-start)));
                    }
                }
                i++;
            }

            if (insert) {

                resultSet = preparedStatement.getGeneratedKeys();
                if(fetchSize!=null) {
                    resultSet.setFetchSize(fetchSize);
                }
                int idx = 0;
                while (resultSet.next()) {
                    E temp = batchs.get(idx);

                    Field field = temp.getClass().getDeclaredField("id");
                    Object id = resultSet.getObject("id");
                    MyBeanUtil.callSetterMethod(temp, "setId", field, id);
                    idx++;
                }
            }
            preparedStatement.clearBatch();
            return efts.stream().mapToInt(Integer::valueOf).toArray();
        } catch (Exception e) {
            sqlSession.rollback();
            throw new RuntimeException(e);
        } finally {
            if(ObjectUtil.isNotEmpty(resultSet)){
                try {
                    resultSet.close();
                } catch (SQLException e) {
                }
            }
            if (ObjectUtil.isNotEmpty(preparedStatement)) {
                try {
                    if (preparedStatement != null) {
                        preparedStatement.close();
                    }
                } catch (SQLException throwables) {
                    //
                }
            }
            sqlSession.close();
        }
    }

**Comment by azexcy** [comment]
I find the official doc, 

Limited supported SQL:

- When using `getGeneratedKeys` interface of JDBC specification to return auto-increment key, it is necessary to use a distributed key generator that supports auto-increment, and does not support other types of distributed key generators

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.
