### ISSUE TITLE
agent support

### ISSUE THREAD

**Issue by corgy-w** [apache/shardingsphere#27625]
Since no one replied to the last replyissues reply, I was forced to open another one to ask about it.  I apologize for the inconvenience.

The agent support for sharding is from 5.3.2, I would like to retrofit it to support 5.2.1, the company's second development is based on 5.2.1, is the possibility there? I haven't started looking at the relevant code yet, just want to politely ask you about the feasibility for my next research, thanks!

**Comment by RaigorJiang** [comment]
Duplicated with #27578.
