### ISSUE TITLE
How to implement shadow table based on Sharding-JDBC

### ISSUE THREAD

**Issue by wrail** [apache/shardingsphere#27634]
## Question

How to implement shadow table based on Sharding-JDBC

I want to use another table in the same database as a shadow table，and to use Sharding-JDBC to complete the shadow table route, but I only found the support of the shadow library

what should I do？

**Comment by RaigorJiang** [comment]
Hi @wrail 
Shadow is currently a routing feature at the `data source` level, which really does not meet the scenario you describe.
