### ISSUE TITLE
[proxy] not treat "?" operator correctly in postgresql

### ISSUE THREAD

**Issue by susongyan** [apache/shardingsphere#27892]
### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy 

### Expected behavior
pgsql  execute success 

 SELECT  * from table  WHERE receiver ?& $1 OR creater = $2;    
 parameter   1, test@gmail.com     2, susongyan

### Actual behavior
org.postgresql.util.PSQLException: No value specified for parameter 3.

### Reason analyze (If you can)
PostgreSQLComParseExecutor #convertSQLToJDBCStyle

after proxy parse this sql and convert it to jdbc paramter style 
the actual sql to execute in jdbc is    "SELECT  * from table  WHERE receiver ?& ? OR creater = ?;"

jdbc style, treat "?" as parameter marker, then  this sql  need three parameters in mistake (actually only two)

**Comment by azexcy** [comment]
@susongyan Thanks for the feedback!
Can you help confirm that this is still an issue on the master branch?

**Comment by susongyan** [comment]
> 

i checkout master code,  it  doesn't  escape this  operator yet,

**Comment by susongyan** [comment]
@azexcy i simply convert  ?  to ??   escaped in  pg jdbc driver's  style

**Comment by susongyan** [comment]
@RaigorJiang  help have a look ?

**Comment by sandynz** [comment]
Hi @susongyan , could you supply some PostgreSQL document of
> SELECT * from table WHERE receiver ?& $1 OR creater = $2;
parameter 1, [test@gmail.com](mailto:test@gmail.com) 2, susongyan

**Comment by susongyan** [comment]
> Hi @susongyan , could you supply some PostgreSQL document of
> 
> > SELECT * from table WHERE receiver ?& $1 OR creater = $2;
> > parameter 1, [test@gmail.com](mailto:test@gmail.com) 2, susongyan

https://www.postgresql.org/message-id/CADK3HH+Fbr4+TBrpmK7pSbVkBei7pHmB99ANU_Km1HnjCEmO6w@mail.gmail.com

**Comment by susongyan** [comment]
process in pg driver   @sandynz 
org.postgresql.core.Parser#parseJdbcSql
```java

        case '?':
          nativeSql.append(aChars, fragmentStart, i - fragmentStart);
          if (i + 1 < aChars.length && aChars[i + 1] == '?') /* replace ?? with ? */ {
            nativeSql.append('?');
            i++; // make sure the coming ? is not treated as a bind
          }

```

**Comment by susongyan** [comment]
@sandynz 

https://www.postgresql.org/docs/9.4/functions-json.html   this is jsonb function doc

**Comment by sandynz** [comment]
> process in pg driver @sandynz org.postgresql.core.Parser#parseJdbcSql
> 
> ```java
>         case '?':
>           nativeSql.append(aChars, fragmentStart, i - fragmentStart);
>           if (i + 1 < aChars.length && aChars[i + 1] == '?') /* replace ?? with ? */ {
>             nativeSql.append('?');
>             i++; // make sure the coming ? is not treated as a bind
>           }
> ```

1, Is `?` escape character in PostgreSQL? Is there any document about it?

2,
<img width="672" alt="图片" src="https://github.com/apache/shardingsphere/assets/42492540/4d04d7d5-7686-4a70-a65a-82ccbe20a519">
I found `Parser.parseJdbcSql` is referenced by 2 places, maybe not for every type of SQL. I'm not sure whether the SQL type is equivalent with `PostgreSQLComParseExecutor` handled or not.

**Comment by susongyan** [comment]
to question 1: 

proxy is also a jdbc client , i think  pg server doesn't case about escaped  ??

PostgreSQLComParseExecutor is transfer   pg origin packet to  jdbc style , then  pass it to pg driver to recover to  pg origin  packet  style ;   it's  pg driver's jdbc escape int client side 

origin pg packet from  node: 
SELECT * from table WHERE receiver ?& $1 OR creater = $2;

proxy convert it to :
SELECT * from table WHERE receiver ??& ? OR creater = ?;

pg driver recover it and send to  pg server:
SELECT * from table WHERE receiver ?& $1 OR creater = $2;

to question2 : 
Parser.parseJdbcSql used in   SetupQueryRunner( set variables ) and CachedQueryCreateAction( lrucache, common sql)
