### ISSUE TITLE
Oracle g4 specialDataType conflict with aggregateClause

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#27920]
### Which version of ShardingSphere did you use?

master - 7be997e66d0cbf557ad83946c7740a07255ef111

### Expected behavior

No syntax error.

```sql
CREATE OR REPLACE EDITIONABLE FUNCTION MY_FUNC (P1 VARCHAR2)
RETURN VARCHAR2 AGGREGATE USING MY_AGG_FUNC;
```

### Actual behavior

```
line 2:26 mismatched input 'USING' expecting {AS, IS, DEFAULT, SHARING, RESULT_CACHE, DETERMINISTIC, PIPELINED, PARALLEL_ENABLE, ACCESSIBLE, AUTHID, AGGREGATE, SQL_MARCO}
```

![image](https://github.com/apache/shardingsphere/assets/20503072/3c613145-b05b-4053-9e41-03160d9abaed)

**Comment by ilyasahsan123** [comment]
hi @TeslaCN , Could you please assign this issue to me?

**Comment by strongduanmu** [comment]
@ilyasahsan123 Assigned.

**Comment by ilyasahsan123** [comment]
Hi Team,

I've sent the pull request, Could someone please take a look?

- https://github.com/apache/shardingsphere/pull/29589

my reference for the implementation: [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpls/CREATE-FUNCTION-statement.html#GUID-B71BC5BD-B87C-4054-AAA5-213E856651F2)

<img width="300" height="300" alt="image" src="https://github.com/apache/shardingsphere/assets/14249648/6d2666e9-60ea-4e1b-a9f1-865c80bc0f92">

cc-ing @strongduanmu @zihaoAK47
