### ISSUE TITLE
Does shardingJdbc support Kingbase database?

### ISSUE THREAD

**Issue by Jack-huang-chen** [apache/shardingsphere#27967]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
Does Kingbase support connection with MySQL or PG protocol?
ShardingSphere can connect to any database, but some adaptation work may be required.

**Comment by RaigorJiang** [comment]
This issue has been inactive for a long time, so I will close it.
If this problem persists, please reopen it or submit a new one.
