### ISSUE TITLE
ZonedDateTime 

### ISSUE THREAD

**Issue by yarodai** [apache/shardingsphere#27968]
### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core-spring-boot-starter 5.2.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://github.com/apache/shardingsphere/assets/12030364/a3cadc22-5eed-4b9f-a785-a21294912116)

**Comment by zhaojinchao95** [comment]
@yarodai Can you try it with `5.4.0` version?

**Comment by yarodai** [comment]
> @yarodai Can you try it with `5.4.0` version?

I tried it, but it still doesn't work

**Comment by linghengqian** [comment]
- Unit tests related to this always exist, refer to https://github.com/apache/shardingsphere/blob/9a7e1403dd7327b53b8ee11c1d51517278d34af8/features/sharding/core/src/test/java/org/apache/shardingsphere/sharding/algorithm/sharding/datetime/IntervalShardingAlgorithmTest.java#L207 .

- You need to provide unit tests.

**Comment by linghengqian** [comment]
- Closing this issue because it cannot be reproduced.
