### ISSUE TITLE
SQL with 'with nolock' is not supported

### ISSUE THREAD

**Issue by RedThreeStone** [apache/shardingsphere#28009]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
SQL can be routed correctly
### Actual behavior
In the SQL server database, SQL with 'with (nolock)‘  cannot be routed
### Reason analyze (If you can)
org.apache.shardingsphere.sql.parser.SQLParserEngine#parse0  return an error SQLStatement,  The value of the attribute 'where' in it is null
### Example codes for reproduce this issue (such as a github link).
  @PostMapping("withNoLockTest2")
    public void withNoLockTest2(){
        FulfillOrder fulfillOrder = fulfillOrderMapper.selectByUserId2("123456");
        System.out.println(JSON.toJSONString(fulfillOrder));
    }

  <select id="selectByUserId2" resultMap="BaseResultMap">
        select user_id from fulfill_order with(nolock) where user_id=#{userId}
    </select>

**Comment by sandynz** [comment]
Looks `nolock` is not supported for SQLServer on master branch too.

Is `nolock` required?

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
