### ISSUE TITLE
v5.2.1, If a druid datasource has some filters, then create a ShardingSphereDataSource will occur exception 

### ISSUE THREAD

**Issue by study-renjie** [apache/shardingsphere#28013]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Shardingsphere-jdbc-core

### Expected behavior
work well

### Actual behavior
does not work

### Reason analyze (If you can)
![image](https://github.com/apache/shardingsphere/assets/43563096/4b26197e-fecb-44ad-afc3-40da9cf1dcad)
In this case, Druid datasource was added some filters (eg: StatFilter). When entered this method, the rootClass is a map and the className is a druid filter, validated failed.

**Comment by study-renjie** [comment]
i see the similar problem, but that problem is still open, not be solved,so i create a new problem

**Comment by sandynz** [comment]
Hi @study-renjie , possible workaround:
- https://github.com/apache/shardingsphere/issues/23526#issuecomment-1381224012
- https://github.com/apache/shardingsphere/issues/21211#issuecomment-1263344953

**Comment by study-renjie** [comment]
Although someone has raised the same question before, the problem has not been resolved so far

**Comment by sandynz** [comment]
> Although someone has raised the same question before, the problem has not been resolved so far

Hi, did you try their solution to make it work for now?

Currently, ShardingSphere supports Hikari data source pool, and other pools supporting is on the way, refer to #27608 for more details.

**Comment by freenet-233** [comment]
Cannot solve druid filter issue currently, at least v5.3.2. I solved it via Java API.

**Comment by nikbobo** [comment]
> Cannot solve druid filter issue currently, at least v5.3.2. I solved it via Java API.

How to slove it?

**Comment by linghengqian** [comment]
- Verify that this issue has been resolved at https://github.com/apache/shardingsphere/issues/21211#issuecomment-1932123528 . 
- Since there are no relevant unit tests for the current issue for a long time, I will close this issue.
