### ISSUE TITLE
Parsing SQL errors when using Oracle

### ISSUE THREAD

**Issue by humingzhang** [apache/shardingsphere#28068]
### Which version of ShardingSphere did you use?
5.2.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Success to execute query 
### Actual behavior
Invalid identification error
### Reason analyze (If you can)
column alias parsing error where use encrypt field
#### 3、execute sql
SELECT
			c.employee_code,
			c.employee_position,
			c.employee_email,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid AS userUuid,
			a.account_type,
			a.username,
			a.avatar,
			a.display_name,
			a.phone,
			a.email,
			a.state AS status,
			a.auth_type,
			a.auth_result,
			a.id
FROM
			uc_account a
JOIN uc_dept_user_relation d ON
			(a.uuid = d.user_uuid)
LEFT JOIN uc_company_user c ON
			(a.uuid = c.user_uuid
		AND d.company_uuid = c.company_uuid)
WHERE
			a.deleted = 0
	AND (c.deleted = 0
		OR c.deleted IS NULL)
	AND d.deleted = 0
	AND c.join_state IN (?)
	AND d.company_uuid = ?
GROUP BY
			c.employee_code,
			c.employee_position,
			c.employee_email,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid,
			a.account_type,
			a.username,
			a.avatar,
			a.display_name,
			a.phone,
			a.email,
			a.state,
			a.auth_type,
			a.auth_result,
			a.id
ORDER BY
			a.id DESC	
#### 4、mybatis-plus sql
SELECT
	*
FROM
	(
	SELECT
		TMP.*,
		ROWNUM ROW_ID
	FROM
		(
		SELECT
			c.employee_code,
			c.employee_position,
			c.employee_email,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid AS userUuid,
			a.account_type,
			a.username,
			a.avatar,
			a.display_name,
			a.phone,
			a.email,
			a.state AS status,
			a.auth_type,
			a.auth_result,
			a.id
		FROM
			uc_account a
		JOIN uc_dept_user_relation d ON
			(a.uuid = d.user_uuid)
		LEFT JOIN uc_company_user c ON
			(a.uuid = c.user_uuid
				AND d.company_uuid = c.company_uuid)
		WHERE
			a.deleted = 0
			AND (c.deleted = 0
				OR c.deleted IS NULL)
			AND d.deleted = 0
			AND c.join_state IN (?)
			AND d.company_uuid = ?
		GROUP BY
			c.employee_code,
			c.employee_position,
			c.employee_email,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid,
			a.account_type,
			a.username,
			a.avatar,
			a.display_name,
			a.phone,
			a.email,
			a.state,
			a.auth_type,
			a.auth_result,
			a.id
		ORDER BY
			a.id DESC ) TMP
	WHERE
		ROWNUM <=?)
WHERE
	ROW_ID > ?
#### 5、sharding sql
SELECT
	"c"."employee_code",
	"c"."employee_position",
	"c"."EMPLOYEE_EMAIL" AS "employee_email",
	"c"."create_time",
	"c"."join_state",
	"a"."nick_name",
	"a"."uuid" AS "userUuid",
	"a"."account_type",
	"a"."username",
	"a"."avatar",
	"a"."DISPLAY_NAME" AS "display_name",
	"a"."PHONE" AS "phone",
	"a"."EMAIL" AS "email",
	"a"."state" AS "status",
	"a"."auth_type",
	"a"."auth_result",
	"a"."id",
	"ROWNUM" AS "ROW_ID"
FROM
	(
	SELECT
		"c"."employee_code",
		"c"."employee_position",
		"c"."EMPLOYEE_EMAIL",
		"c"."create_time",
		"c"."join_state",
		"a"."nick_name",
		"a"."uuid" AS "userUuid",
		"a"."account_type",
		"a"."username",
		"a"."avatar",
		"a"."DISPLAY_NAME",
		"a"."PHONE",
		"a"."EMAIL",
		"a"."state" AS "status",
		"a"."auth_type",
		"a"."auth_result",
		"a"."id",
		ROWNUM ROW_ID
	FROM
		(
		SELECT
			c.employee_code,
			c.employee_position,
			c.EMPLOYEE_EMAIL,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid AS userUuid,
			a.account_type,
			a.username,
			a.avatar,
			a.DISPLAY_NAME,
			a.PHONE,
			a.EMAIL,
			a.state AS status,
			a.auth_type,
			a.auth_result,
			a.id
		FROM
			uc_account a
		JOIN uc_dept_user_relation d ON
			(a.uuid = d.user_uuid)
		LEFT JOIN uc_company_user c ON
			(a.uuid = c.user_uuid
				AND d.company_uuid = c.company_uuid)
		WHERE
			a.deleted = 0
			AND (c.deleted = 0
				OR c.deleted IS NULL)
			AND d.deleted = 0
			AND c.join_state IN
             (?)
			AND d.company_uuid = ?
		GROUP BY
			c.employee_code,
			c.employee_position,
			c.EMPLOYEE_EMAIL,
			c.create_time,
			c.join_state,
			a.nick_name,
			a.uuid,
			a.account_type,
			a.username,
			a.avatar,
			a.DISPLAY_NAME,
			a.PHONE,
			a.EMAIL,
			a.state,
			a.auth_type,
			a.auth_result,
			a.id
		ORDER BY
			a.id DESC ) TMP
	WHERE
		ROWNUM <=?)
WHERE
	ROW_ID > ?

**Comment by humingzhang** [comment]
version 5.1.1 does not have this issue

**Comment by RaigorJiang** [comment]
Hi @humingzhang 
The latest version has improved compatibility with `Oracle`, can you try 5.4.0?
In addition, the community has submitted many issues to improve `Oracle` parsing, you can also participate, thank you!

**Comment by humingzhang** [comment]
> Hi @humingzhang The latest version has improved compatibility with `Oracle`, can you try 5.4.0? In addition, the community has submitted many issues to improve `Oracle` parsing, you can also participate, thank you!



> Hi @humingzhang The latest version has improved compatibility with `Oracle`, can you try 5.4.0? In addition, the community has submitted many issues to improve `Oracle` parsing, you can also participate, thank you!

**Comment by humingzhang** [comment]
@RaigorJiang HI, I have tested the following versions and there are related issues
5.0
5.1
5.2
5.3
5.4
There was a previous version that did not have this issue: 4.0.0-RC4

**Comment by zhangfengcdt** [comment]
I tested these three SQLs using the Oracle SQL dialect on the master branch:
https://github.com/apache/shardingsphere/commit/b11bbfb12859f425f6afce14bd2e5ab58b82f565

None of them failed to be parsed.

**Comment by strongduanmu** [comment]
@zhangfengcdt Thank you for your feedback. @humingzhang Can you test with master branch?
