### ISSUE TITLE
Please support snakeyaml 2.0.

### ISSUE THREAD

**Issue by Pinkman-oss** [apache/shardingsphere#28067]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
When snakeyaml 2.0 is used in a project, an error is reported and the project cannot be started.

### Describe the feature you would like.
Please support snakeyaml 2.0.

**Comment by RaigorJiang** [comment]
Hi @Pinkman-oss 
ShardingSphere currently uses snakeyaml version 1.3.3, can you provide a work list for upgrading to 2.0?
Like what improvements does it bring, and are there any api changes?

**Comment by think-gem** [comment]
> Hi @Pinkman-oss ShardingSphere currently uses snakeyaml version 1.3.3, can you provide a work list for upgrading to 2.0? Like what improvements does it bring, and are there any api changes?

Because spring boot requires version 2.0, otherwise it conflicts with the new version spring boot

**Comment by SingKS8** [comment]
The most common conflict issues with snakeyaml 2.0 are that the default constructor of `org.yaml.snakeyaml.representer.Representer` is deprecated in 1.33 and remove in 2.0, in my opinion, even if snakeyaml team keep development about 1.x version series, shardingsphere team should have a plan about updating api which has deprecated.

I feel a little disappointed in this issuse is that your guy a contributor of this project under apache foundation, let a common community member who is not in development to provide a work list? I think keeping api updates and  avoiding vulnerabilities, should be responsibility of the core team.
