### ISSUE TITLE
GC count abnormal when service have too many calls

### ISSUE THREAD

**Issue by sunlife95** [apache/shardingsphere#28069]
## GC count abnormal when service have too many calls

version:5.4.0

descripetion:
when i deploy my service in prod,after a period of time,heap used up to 90% and fullGC can't release heap space.

recurrence: 
i set 14 thread and 1000000 times called to call the service, after a period of time, service restart.

![image](https://github.com/apache/shardingsphere/assets/18573716/483627f8-8125-49a0-a5fd-0ed6ad3cc767)
![image](https://github.com/apache/shardingsphere/assets/18573716/54b47e4e-0b6b-4465-a6ff-bb7a1b3a4c65)

**Comment by TeslaCN** [comment]
Are you using ShardingSphere-JDBC?

**Comment by sunlife95** [comment]
> Are you using ShardingSphere-JDBC?

yes, and i config with java 

`
    /**
     * 初始化分表规则
     */
    private ShardingRuleConfiguration getShardingRuleConfiguration() {
        ShardingRuleConfiguration ruleConfiguration = new ShardingRuleConfiguration();

        // 分库策略：不分库只分表
        ruleConfiguration.setDefaultDatabaseShardingStrategy(new NoneShardingStrategyConfiguration());
        // 分表策略：默认不分表
        ruleConfiguration.setDefaultTableShardingStrategy(new NoneShardingStrategyConfiguration());

        // 默认自增列值生成器
        ruleConfiguration.getKeyGenerators().putIfAbsent("myKeyGenerator", new AlgorithmConfiguration("myKeyGenerator", new Properties()));
        ruleConfiguration.setDefaultKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("shard_column", "myKeyGenerator");

        // 分表规则
        ruleConfiguration.getShardingAlgorithms().putIfAbsent(ShardingAlgorithmConsts.HASH_MODULO_ALGORITHM, new AlgorithmConfiguration(ShardingAlgorithmConsts.HASH_MODULO_ALGORITHM, new Properties()));

        // 分片规则
        ShardingTableRuleConfiguration result = new ShardingTableRuleConfiguration("shard_table", "ds_0.shard_table_${0..7}");
        result.setKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("shard_column", "myKeyGenerator"));
        result.setTableShardingStrategy(new StandardShardingStrategyConfiguration("shard_column", "myShardAlgorithm"));
        ruleConfiguration.getTables().add(result);

        return ruleConfiguration;
    }

    /**
     * 初始化单表规则
     */
    private SingleRuleConfiguration getSingleRuleConfiguration() {

        List<String> singleTableList = Lists.newArrayList();

        singleTableList.add("*.*");

        return new SingleRuleConfiguration(singleTableList, "ds_0");
    }
     /**
     * 主从分离配置
     * @return
     * @throws SQLException
     */
    private ReadwriteSplittingRuleConfiguration getReadWriteSplittingRuleConfiguration() {
        ReadwriteSplittingDataSourceRuleConfiguration dataSourceConfiguration = new ReadwriteSplittingDataSourceRuleConfiguration("ds_0", MASTER_NAME, SLAVE_NAMES, "roundRobin");

        //负载均衡算法
        Map<String, AlgorithmConfiguration> loadBalanceMaps = new HashMap<>(1);
        loadBalanceMaps.put("roundRobin", new AlgorithmConfiguration("ROUND_ROBIN", new Properties()));

        return new ReadwriteSplittingRuleConfiguration(Lists.newArrayList(dataSourceConfiguration), loadBalanceMaps);
    }


    /**
     * 初始化sharding 数据源
     * @return
     * @throws SQLException
     */
    @Bean
    public DataSource shardingDataSource() throws SQLException {

        // 分表规则配置
        ShardingRuleConfiguration shardingRuleConfiguration = getShardingRuleConfiguration();

        // 读写分离配置
        ReadwriteSplittingRuleConfiguration readwriteSplittingRuleConfiguration = getReadWriteSplittingRuleConfiguration();

        // 单表配置
        SingleRuleConfiguration singleRuleConfiguration = getSingleRuleConfiguration();

        // sharding sql显示配置
        Properties props = new Properties();
        props.put(ConfigurationPropertyKey.SQL_SHOW.getKey(), showSql);

        return ShardingSphereDataSourceFactory.createDataSource("ds_0", new ModeConfiguration("Standalone", null), createDataSourceMap(), Lists.newArrayList(shardingRuleConfiguration, readwriteSplittingRuleConfiguration, singleRuleConfiguration), props);
    }

`

**Comment by TeslaCN** [comment]
Thanks for your feedback. I've confirmed the memory leak in ShardingSphere-JDBC.

Running test with `-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError`
```java
    @Test
    void select1() throws SQLException {
        for (int i = 0; i < 10000000; i++) {
            try (Connection connection = getShardingSphereDataSource().getConnection(); Statement statement = connection.createStatement()) {
                statement.execute("select 1");
            }
        }
    }
```

```
diff --git a/test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingStatementTest.java b/test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingStatementTest.java
index cd8db1a672c..abf7869d37c 100644
--- a/test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingStatementTest.java
+++ b/test/e2e/driver/src/test/java/org/apache/shardingsphere/test/e2e/driver/statement/ShardingStatementTest.java
@@ -35,6 +35,15 @@ import static org.junit.jupiter.api.Assertions.assertTrue;
 
 class ShardingStatementTest extends AbstractShardingDriverTest {
     
+    @Test
+    void select1() throws SQLException {
+        for (int i = 0; i < 10000000; i++) {
+            try (Connection connection = getShardingSphereDataSource().getConnection(); Statement statement = connection.createStatement()) {
+                statement.execute("select 1");
+            }
+        }
+    }
+    
     @Test
     void assertGetGeneratedKeys() throws SQLException {
         String sql = "INSERT INTO t_order_item(order_id, user_id, status) VALUES (%d, %d, '%s')";

```

**Comment by strongduanmu** [comment]
Thank you for your feedback, I will try to fix the memory leak.

**Comment by strongduanmu** [comment]
> Thanks for your feedback. I've confirmed the memory leak in ShardingSphere-JDBC.
> 
> Running test with `-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError`
> 
> ```java
>     @Test
>     void select1() throws SQLException {
>         for (int i = 0; i < 10000000; i++) {
>             try (Connection connection = getShardingSphereDataSource().getConnection(); Statement statement = connection.createStatement()) {
>                 statement.execute("select 1");
>             }
>         }
>     }
> ```

I do some test according to this unit test, now the latest master has solved MySQL JDBC memory leak. @sunlife95 Can you help test again?

**Comment by sunlife95** [comment]
> > Thanks for your feedback. I've confirmed the memory leak in ShardingSphere-JDBC.
> > Running test with `-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError`
> > ```java
> >     @Test
> >     void select1() throws SQLException {
> >         for (int i = 0; i < 10000000; i++) {
> >             try (Connection connection = getShardingSphereDataSource().getConnection(); Statement statement = connection.createStatement()) {
> >                 statement.execute("select 1");
> >             }
> >         }
> >     }
> > ```
> 
> I do some test according to this unit test, now the latest master has solved MySQL JDBC memory leak. @sunlife95 Can you help test again?

i will test later
