### ISSUE TITLE
group by having didn't take effect

### ISSUE THREAD

**Issue by 54uso** [apache/shardingsphere#28070]
## having didn't take effect

* java8
* ShardingSphere-JDBC 5.2.0

### code
``` java
ResultSet resultSet = dataSource.getConnection().createStatement().executeQuery("SELECT trade_status, count(1) as cnt FROM loan_order_info group by trade_status");
while (resultSet.next()) {
    System.out.printf("resultSet group by: %d %d\n", resultSet.getInt(1), resultSet.getInt(2));
}
ResultSet resultSet1 = dataSource.getConnection().createStatement().executeQuery("SELECT trade_status, count(1) as cnt, max(id) as mid FROM loan_order_info where trade_status>0 and id>0 group by trade_status having cnt < 30000");
while (resultSet1.next()) {
    System.out.printf("resultSet1 group by having: %d %d\n", resultSet1.getInt(1), resultSet1.getInt(2));
}
```
### output
> resultSet group by: 1 35045
> resultSet group by: 2 37838
> resultSet group by: 3 22314
> resultSet1 group by having: 1 35045
> resultSet1 group by having: 2 37838
> resultSet1 group by having: 3 22314

**Comment by prajwalbandak** [comment]
hey @54uso , Can you assign to me and please explain what are the thing to do?

**Comment by strongduanmu** [comment]
@prajwalbandak Good job, I will assign this issue to you.

**Comment by strongduanmu** [comment]
HI @54uso, can you provide more information, just like config and your table init sql to help @prajwalbandak reproduce this exception.

**Comment by prajwalbandak** [comment]
Thank you, @strongduanmu and @54uso As a beginner in open source, it can be quite challenging to grasp the concept. Your explanation is greatly appreciated.

**Comment by 54uso** [comment]
@strongduanmu @prajwalbandak  Thanks for your reply, here are some of my configuration information
### config

``` properties
spring.shardingsphere.datasource.names = ds0,ds1

spring.shardingsphere.datasource.ds0.driverClassName = com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds0.url = jdbc:mysql://127.0.0.1:3306/loan_order_center_0?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&sessionVariables=SQL_SAFE_UPDATES=1
spring.shardingsphere.datasource.ds0.password = 
spring.shardingsphere.datasource.ds0.username = 
spring.shardingsphere.datasource.ds0.maxActive = 

spring.shardingsphere.datasource.ds1.driverClassName = com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds1.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds1.url = jdbc:mysql://127.0.0.1:3306/loan_order_center_1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&sessionVariables=SQL_SAFE_UPDATES=1
spring.shardingsphere.datasource.ds1.password = 
spring.shardingsphere.datasource.ds1.username = 
spring.shardingsphere.datasource.ds1.maxActive = 



spring.shardingsphere.rules.sharding.sharding-algorithms.loan-order-database-inline.type = INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.loan-order-database-inline.props.algorithm-expression = ds$->{((user_id >> 31) % 4) >> 1}

spring.shardingsphere.rules.sharding.sharding-algorithms.loan-order-info-tables-inline.type = INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.loan-order-info-tables-inline.props.algorithm-expression = loan_order_info_$->{((user_id >> 31) % 4) % 2}
```

###  table init sql
``` sql
CREATE TABLE `loan_order_info` (
  `id` bigint unsigned NOT NULL COMMENT '主键',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `instruction_id` bigint unsigned NOT NULL COMMENT '流水号',
  `trade_status` tinyint unsigned NOT NULL COMMENT '交易状态(1:交易成功,2:交易失败,3:处理中)',
  `inside_error_code` int DEFAULT NULL COMMENT '内部错误码',
  `inside_error_msg` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '内部错误信息',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_instruction_id` (`instruction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='订单状态表'
```

**Comment by prajwalbandak** [comment]
Hey @54uso ,In your second query, you're trying to filter the groups using the condition HAVING cnt < 30000. However, this condition is not applied correctly. The HAVING clause filters the results of the GROUP BY operation, and it works on the result of the aggregate functions (like COUNT, MAX, etc.) applied to the groups.
Can you try this code:
 `ResultSet resultSet1 = dataSource.getConnection().createStatement().executeQuery(
    "SELECT trade_status, count(1) as cnt, max(id) as mid " +
    "FROM loan_order_info " +
    "WHERE trade_status > 0 AND id > 0 " +
    "GROUP BY trade_status " +
    "HAVING cnt < 30000"
);

while (resultSet1.next()) {
    System.out.printf("resultSet1 group by having: %d %d\n", resultSet1.getInt("trade_status"), resultSet1.getInt("cnt"));
}
` 
let me know if this works or not. 
Thanks.

**Comment by prajwalbandak** [comment]
`ResultSet resultSet1 = dataSource.getConnection().createStatement().executeQuery(
    "SELECT trade_status, count(1) as cnt, max(id) as mid " +
    "FROM loan_order_info " +
    "WHERE trade_status > 0 AND id > 0 " +
    "GROUP BY trade_status " +
    "HAVING cnt < 30000"
);

while (resultSet1.next()) {
    System.out.printf("resultSet1 group by having: %d %d\n", resultSet1.getInt("trade_status"), resultSet1.getInt("cnt"));
}
`
