### ISSUE TITLE
whether shardingsphere support DM8 database or not？

### ISSUE THREAD

**Issue by 0Freesky0** [apache/shardingsphere#28095]
whether shardingsphere support DM8 database or not？
 
Only encryption features are used in our project；recently ，we wiil use DM8 to replace mysql，Is there a way to be compatible？

**Comment by RaigorJiang** [comment]
Hi @0Freesky0 
Apache ShardingSphere only supports internationalized database products, and there is no support plan for DM.
For specific databases, [SphereEx]( https://www.sphere-ex.com/) can provide consultation.

**Comment by strongduanmu** [comment]
Since this issue has already been answered, I will close it.
