### ISSUE TITLE
Supports encryption in the original column without the need to expand the column

### ISSUE THREAD

**Issue by NickCodeJourney** [apache/shardingsphere#28134]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by strongduanmu** [comment]
Hi @NickYoungPeng, can you describe your feature request in detail.
