### ISSUE TITLE
tables end with numbers have errors where configuring binding tables

### ISSUE THREAD

**Issue by liulangynfx** [apache/shardingsphere#28140]
The table like t_inventory_20210709, t_inventory_copy1 has errors when configuring the binding tables.
<img width="1168" alt="image" src="https://github.com/apache/shardingsphere/assets/13901073/2ad3c726-fa7d-4548-929c-60e6d35209cf">

 I debug the code，and then find that the table end with numbers may have problems when build dataNode on application started.This would cause the prefix is t_inventory_ or t_inventory_copy, and this cause loading binding table return false
<img width="981" alt="image" src="https://github.com/apache/shardingsphere/assets/13901073/2aa8de68-46fd-49a4-8869-dfd3e7d26fb3">
<img width="1229" alt="image" src="https://github.com/apache/shardingsphere/assets/13901073/a1429f76-a631-48fa-9519-b2fc91a980a6">

version: shardingsphere-jdbc-core-spring-boot-starter  5.1.2

this is my configuration:
spring.shardingsphere.datasource.names = ds_0,ds_1,ds_2,ds_3
spring.shardingsphere.datasource.ds_0.type = com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds_0.driver-class-name = com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds_0.jdbc-url = ...
spring.shardingsphere.datasource.ds_0.username = ...
spring.shardingsphere.datasource.ds_0.password = ...
spring.shardingsphere.datasource.ds_0.max-active = ...

...

spring.shardingsphere.rules.sharding.tables.t_inventory_20210709.actual-data-nodes = ds_${0..3}.t_inventory_20210709
spring.shardingsphere.rules.sharding.tables.t_inventory_20210709.database-strategy.standard.sharding-column = STATION
spring.shardingsphere.rules.sharding.tables.t_inventory_20210709.database-strategy.standard.sharding-algorithm-name = ds-sharding

**Comment by RaigorJiang** [comment]
Hi @liulangynfx 
Thanks for your feeback, can you try the latest version 5.4.0?
