### ISSUE TITLE
All tables must be in the same datasource

### ISSUE THREAD

**Issue by wuwei0727** [apache/shardingsphere#28144]
## Question
I use ShardingJDBC5.1.1, springboot2.3.12.RELEASE。
Now I have a problem:All tables must be in the same datasource
Below is my exception information picture：
![Snipaste_2023-08-17_17-22-18](https://github.com/apache/shardingsphere/assets/100761249/6031a303-19c4-4db5-8e39-17335059cd1f)

Below is a picture of my properties configuration file：
![Snipaste_2023-08-17_17-25-44](https://github.com/apache/shardingsphere/assets/100761249/4a21d353-80eb-41a5-bf4e-c665b230f333)

Here is my test code：
![Snipaste_2023-08-17_17-28-44](https://github.com/apache/shardingsphere/assets/100761249/8159737b-0e86-4a86-9fd0-08a61f7e5494)

![Snipaste_2023-08-17_17-30-32](https://github.com/apache/shardingsphere/assets/100761249/a56e52ae-cbf1-4585-bd8b-575dac73e2cb)

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
@wuwei0727 
Your table `p_findcar` is a sharding table, but the join table `map_2d` is a single table, right?
Since their distributions are different, the join cannot be performed.

**Comment by wuwei0727** [comment]
> @wuwei0727 你的表`p_findcar`是分片表，但是join表`map_2d`是单表，对吧？ 由于它们的分配不同，因此无法执行连接。
Excuse me, how do I join the single table with the fragmented table? Must the map_2d table be fragmented?

**Comment by RaigorJiang** [comment]
@wuwei0727 
If a table like `map_2d` does not have a lot of data, but you need to perform a join query with a sharding table, you can set `map_2d` as a broadcast table.
