### ISSUE TITLE
Shardingsphere 5.3.2 the first query very slow.

### ISSUE THREAD

**Issue by hypercube1024** [apache/shardingsphere#28151]
![first-query-slow](https://github.com/apache/shardingsphere/assets/854268/5401533d-3118-4534-ad6e-9ab26f96453a)
The antlr parser takes more than 2 seconds for the first query. It's very slow for high concurrency service.

**Comment by zhaojinchao95** [comment]
@hypercube1024 The first query cannot hit the cache.

**Comment by hypercube1024** [comment]
> @hypercube1024 The first query cannot hit the cache.

The first query over 2 seconds in high concurrency backend service tiggers the fuse protector and alarm when the service restarts. I thinks the shardingsphere JDBC needs optimize the antlr parser performance and persists the parsed sql into DB. Loads one row data from db only 2ms but parsed one sql needs 2 seconds.
