### ISSUE TITLE
Keep getting ERROR 2014 (HY000) at line 1: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by xqianwang** [apache/shardingsphere#28172]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
When I run command below, it should work
`mysql -h shardingsphere-proxy-apache-shardingsphere-proxy.shardingsphere.svc.cluster.local -P 3308 -u xxxx -p'xxxxx' -e "SHOW DATABASES;"`
### Actual behavior
it gives me error :
ERROR 2014 (HY000) at line 1: Commands out of sync; you can't run this command now

**Comment by zhaojinchao95** [comment]
Can you try it with your ip address?

**Comment by xqianwang** [comment]
Hi @zhaojinchao95 , you mean my client ip address? It doesn't explain that sometimes it works and sometimes it does not work.

**Comment by nikhilerigila09** [comment]
Hi @xqianwang, I am facing the same issue in shardingsphere 5.4.0, while using the k8 service name to connect to it. 
But it works fine if I port-forward the service and use localhost to connect to the proxy. 
It also works fine with shardingsphere-proxy 5.4.1.

**Comment by 4RSENALZ** [comment]
I also have this issue with shardingsphere5.2.1, does anyone know how to solve it ?

**Comment by 4RSENALZ** [comment]
> 我在 shardingsphere5.2.1 上也有这个问题，有谁知道如何解决它？

I trie it again with ShardingSphere 5.4.1 version and MySQL 8.0.31 version driver and solved it.

**Comment by terrymanu** [comment]
Any exception occur in ShardingSphere backend log?
