### ISSUE TITLE
Where's the the implementation of LEFT JOIN in the project code?

### ISSUE THREAD

**Issue by Cindyxin228** [apache/shardingsphere#28183]
## Where's the the implementation of LEFT JOIN in the project code?
Sorry to interrupt, I'm a little confused while reading the code. I want to know where the the implementation of LEFT JOIN is in the project code. Thanks very much.

**Comment by Cindyxin228** [comment]
> Hi @Cindyxin228 Do you want to know the routing strategy of Join? Its logic in sharding, binding tables, broadcasting and other scenarios is different. You'd better be able to ask a specific question. Than you!

Yeah, I want to know the routing strategy of Left Join in  sharding, binding tables. And I wand to know the process of the example "SELECT DISTINCT t1.id FROM website t1 LEFT JOIN ntable t2 ON t1.id = t2.id ORDER BY id;" when using sharding rule. 
Maybe telling me this is complex. Then please tell me some general locations(which folder or files， etc.)
Thanks very much.


Moreover, I'm learning the logic of the tool. When I reading the document https://shardingsphere.apache.org/document/5.1.2/cn/shardingsphere_docs_cn.pdf , I'm still confused with the whole construction and design. Is there more specific intorduction about the design of the code? Thanks very much.

**Comment by RaigorJiang** [comment]
@Cindyxin228 
ShardingSphere provides technical reference documents, which are general:
https://shardingsphere.apache.org/document/current/en/reference/
In the code, you can view the usage logic of `JoinTableSegment`
