### ISSUE TITLE
table.column like 'xxx' sql convert exception

### ISSUE THREAD

**Issue by zhanglinsong** [apache/shardingsphere#28203]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Logic SQL: SELECT count(0) FROM ilp_insurance WHERE ilp_insurance.order_sk > ? AND ilp_insurance.order_sk < ?  AND ilp_insurance.sales_order_no LIKE concat('%', ?, '%')
### Actual behavior
Actual SQL: ssm202302 ::: SELECT count(0) FROM ilp_insurance_202305 WHERE ilp_insurance_202305.order_sk > ? AND ilp_insurance_202305.order_sk < ?  AND ilp_insurance.sales_order_no LIKE concat('%', ?, '%') ::: [1684660071188, 1692608871220, YHTUS2023082000000]

### Reason analyze (If you can)
"ilp_insurance.sales_order_no LIKE concat('%', ?, '%')" the tablename in this sql is not replaced with the actual tablename

**Comment by RaigorJiang** [comment]
4.1.1 is too old, please try newer version, the laster one is 5.4.0.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
