### ISSUE TITLE
maven run but error？

### ISSUE THREAD

**Issue by lizongbo** [apache/shardingsphere#28211]
## Question

follow "Contributor Covenant Submitting of Conduct" from:

https://shardingsphere.apache.org/community/en/involved/conduct/code/

I had git clone the code,and run :
mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e

but I get error :

```
[WARNING] The requested profile "nexus" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project shardingsphere-parser-distsql-engine: Compilation failure: Compilation failure:
[ERROR] /D:/githubProjects/shardingsphere/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLParser.java:[22,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/githubProjects/shardingsphere/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLParser.java:[30,48] 找不到符号
[ERROR]   符号: 类 KernelDistSQLStatementParser
[ERROR] /D:/githubProjects/shardingsphere/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLLexer.java:[21,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/githubProjects/shardingsphere/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLLexer.java:[27,48] 找不到符号
[ERROR]   符号: 类 UtilityDistSQLStatementLexer
```

![image](https://github.com/apache/shardingsphere/assets/1670666/506b9c6b-9072-4455-8607-1dff5aa2f19d)

how to gen java source for  org.apache.shardingsphere.distsql.parser.autogen?

**Comment by linghengqian** [comment]
- The project is currently built on JDK11+ and unit tests are run on JDK 8+. Are you using JDK11+? Refer to https://github.com/apache/shardingsphere/wiki#how-to-setup-your-dev-environment

**Comment by lizongbo** [comment]
I use jdk8u382-b05 and got error.
then I use jdk-11.0.20+8 and run success.

but if I run command:
mvnw clean install -Prelease -T1C
then the process not continue run：

![image](https://github.com/apache/shardingsphere/assets/1670666/96b2b080-d254-4bca-ac03-bdd283c781df)


version info is:

```
D:\githubProjects\shardingsphere>mvnw -version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: C:\Users\8613\.m2\wrapper\dists\apache-maven-3.8.7-bin\678cc9d4\apache-maven-3.8.7
Java version: 11.0.20, vendor: Eclipse Adoptium, runtime: D:\Java\jdk-11.0.20+8
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

```

**Comment by lizongbo** [comment]
It run vary slow：

![image](https://github.com/apache/shardingsphere/assets/1670666/a6416b2d-0692-4ab6-b2c5-18969f16ceea)

**Comment by linghengqian** [comment]
- Usually, `./mvnw clean install -Release -T1C` does take more than 20 minutes on a device with 6 cores and 16GB memory.  But for validation PR, `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e` mentioned in PR template can utilize more system resources.  

- I don't have a Windows development environment, I'm assuming the unit tests are failing because you didn't turn on the directory length limit in Windows 11?

**Comment by linghengqian** [comment]
- If no one replies, it will be deemed resolved.
