### ISSUE TITLE
Springboot+Mybatis+HikariCP+shardingjdbc:5.4.0+Oracle ojdbc8:12.2.0.1. start up very slow

### ISSUE THREAD

**Issue by smoothbasterd** [apache/shardingsphere#28222]
My Spring Boot application, which uses MyBatis, HikariCP, Sharding-JDBC, and Oracle, runs perfectly fine when started locally. Although there's a slight pause during the loading of the fourth data source, the overall experience is smooth. However, when I deploy the application to the production environment, the program stalls for about ten minutes after loading the fourth data source. I suspect this delay is due to reading database metadata. If my understanding is correct, please guide me on how to resolve this issue. If my interpretation is incorrect, could you please help identify where the problem might lie?
![img_v2_a65d0196-647e-4c41-bbc5-8eb5e477f11g](https://github.com/apache/shardingsphere/assets/81557932/032e88b9-d5c9-431e-87be-39e7d7f30f3b)
![img_v2_1934827c-4241-4582-ba05-d0e28f8c835g](https://github.com/apache/shardingsphere/assets/81557932/e192a300-e000-4ae4-88b2-e8e4f9ef9be3)
![img_v2_bb635fe7-13d5-4728-89fb-a2d2037799eg](https://github.com/apache/shardingsphere/assets/81557932/a33e268a-3508-43bb-bd05-955c8baed310)
![img_v2_3545c2a2-2fb7-46ed-9c34-c113caabde3g](https://github.com/apache/shardingsphere/assets/81557932/99ff5714-d04f-46bd-a062-e907bd0ccbda)
![img_v2_b1cae127-0819-4e07-8d88-16930537bf0g](https://github.com/apache/shardingsphere/assets/81557932/2e74816f-00c4-4da9-9c1b-e5f8d9ff692d)

The program gets stuck at the following log for about ten minutes:
![image](https://github.com/apache/shardingsphere/assets/81557932/ae0a77c9-52c3-41d3-9fc5-4a03f7728283)

**Comment by RaigorJiang** [comment]
@smoothbasterd 
From the log, 'Invalid column name' is thrown by oracle jdbc driver, can you solve this problem first?

According to the sharding rule, there is only one sharding table, so the startup should be very fast.

**Comment by smoothbasterd** [comment]
> 从日志中，oracle jdbc驱动程序抛出“无效的列名”，你能先解决这个问题吗？
> 
> 根据分片规则，只有一个分片表，所以启动应该非常快。

Use the 5.4.1 snap shot. resolved this problem.Hope new release
