### ISSUE TITLE
关于5.4.0与spring boot 3.1.2集成依赖问题

### ISSUE THREAD

**Issue by IHEL** [apache/shardingsphere#28223]
为什么spring boot 3.1.2集成shardingsphere-jdbc-core  5.4.0需要指定如下依赖才能启动，否则会报错？

![image](https://github.com/apache/shardingsphere/assets/17951700/7366d902-c728-486d-80ad-d38c79198d50)

**Comment by lizongbo** [comment]
因为 javax.*包名的类，全部都换了新包名，需要用jakarta.*

参考：https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
