### ISSUE TITLE
Best practices for the "no sharding database, only part of tables sharding" scenario

### ISSUE THREAD

**Issue by Lijian500** [apache/shardingsphere#28238]
Best practices for the "no sharding database, only part of tables sharding" scenario

In a single database, some tables are divided into tables, and some tables are not divided. The best practice is whether to use multiple data sources or to use sharding-jdbc data source management?

thanks.

**Comment by YaoFly** [comment]
It is recommended to use sharding-jdbc data sources, as multiple data sources will bring complexity such as data source switching
