### ISSUE TITLE
Multi-table binding error, version 5.4/5.3.2

### ISSUE THREAD

**Issue by devin-wanghuixiong** [apache/shardingsphere#28249]
## Bug Report
规则：
```sql
CREATE SHARDING TABLE RULE t_order(
DATANODES("ds_0.t_order_${2023..2025}_0${1..9},ds_0.t_order_${2023..2025}_${10..12}"),
AUDIT_STRATEGY (TYPE(NAME='DML_SHARDING_CONDITIONS'),ALLOW_HINT_DISABLE=TRUE));

CREATE SHARDING TABLE RULE t_item (
DATANODES("ds_0.t_item_${2023..2025}_0${1..9},ds_0.t_item_${2023..2025}_${10..12}"),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME="snowflake")),
AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=TRUE)
);
```

绑定：
CREATE SHARDING TABLE REFERENCE RULE ref_order(t_item,t_order);
错误
Invalid `sharding table` rules `[ref_order]`, error messages are: [invalid sharding table reference.]

分析：
如果将 t_order 和 t_item 的 DATANODES 都修改为 "ds_0.t_order_${2023..2025}_0${1..9},ds_0.t_order_${2023..2025}_${10..12}" 则可以绑定

官方文档如下说明：
1、关联的分片表应分布在相同的存储单元，并且分片个数相同。例如 ds_${0..1}.t_order_${0..1} 与 ds_${0..1}.t_order_item_${0..1}；
2、关联的分片表应使用一致的分片算法。例如 t_order_${order_id % 2} 与 t_order_item_${order_item_id % 2}；

希望：
相同分表规则应该可以绑定表

**Comment by TeslaCN** [comment]
Does it matter?
![20230824-185310](https://github.com/apache/shardingsphere/assets/20503072/0cdc062b-afe8-479a-8146-adf83818b707)

**Comment by devin-wanghuixiong** [comment]
感谢你的回复，此问题已困扰数天
多次测试导致语句拷贝错误，但正确的规则语句依然无法绑定表

CREATE SHARDING TABLE RULE t_order(
DATANODES("ds_0.t_order_${2023..2025}_0${1..9},ds_0.t_order_${2023..2025}_${10..12}"),
AUDIT_STRATEGY (TYPE(NAME='DML_SHARDING_CONDITIONS'),ALLOW_HINT_DISABLE=TRUE));

CREATE SHARDING TABLE RULE t_item (
DATANODES("ds_0.t_item_${2023..2025}_0${1..9},ds_0.t_item_${2023..2025}_${10..12}"),
AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=TRUE)

生成的规则如下
![image](https://github.com/apache/shardingsphere/assets/43465381/277dafae-c553-4b7d-bd2e-f616a49352bd)

**Comment by devin-wanghuixiong** [comment]
> 感谢你的回复，此问题已困扰数天 
> 由于代码使用了普通文本编辑，导致github显示时缺少了一个下划线，但正确的创建规则依然无法多表绑定 
>
```sql
 CREATE SHARDING TABLE RULE t_order( DATANODES("ds_0.t_order_${2023..2025}_0${1..9},ds_0.t_order_${2023..2025}_${10..12}"), AUDIT_STRATEGY (TYPE(NAME='DML_SHARDING_CONDITIONS'),ALLOW_HINT_DISABLE=TRUE));
 
 CREATE SHARDING TABLE RULE t_item ( DATANODES("ds_0.t_item_${2023..2025}_0${1..9},ds_0.t_item_${2023..2025}_${10..12}"), AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=TRUE)
```
 
> 生成的规则如下 ![image](https://user-images.githubusercontent.com/43465381/263035524-277dafae-c553-4b7d-bd2e-f616a49352bd.png)

**Comment by strongduanmu** [comment]
Hi @devin-wanghuixiong, can you translate this issue to English? Besides, what are the sharding policies and algorithms you have configured?
