### ISSUE TITLE
agent load advisor not work on windows

### ISSUE THREAD

**Issue by bravehorse** [apache/shardingsphere#28252]
### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
agent work
### Actual behavior
agent cann't load advisor configration, log: No configuration of advisor for type ''
### Reason analyze (If you can)
JarEntry name separator is '/' , independent platform path separator
File.separator is '\' on windows, can't match entry name;

change suggestions: 
org.apache.shardingsphere.agent.core.advisor.config.AdvisorConfigurationLoader:65
before
`return pluginClassLoader.getResourceAsStream(String.join(File.separator, "META-INF", "conf", getFileName(pluginType)));`
after
`return pluginClassLoader.getResourceAsStream(String.join("/", "META-INF", "conf", getFileName(pluginType)));`

**Comment by jiangML** [comment]
@bravehorse Hi，can you modify it if you are interested?
