### ISSUE TITLE
Ability to define behaviour when sharding column is not present in the SQL

### ISSUE THREAD

**Issue by rimal** [apache/shardingsphere#2826]
### Is your feature request related to a problem?
https://github.com/apache/incubator-shardingsphere/issues/2815

### Describe the feature you would like.
There needs to be a way to define what to be done (which target names to be chosen) when sharding column is not in the SQL. Currently, as per `StandardRoutingEngine`, all available target names are returned. 

As a suggestion, we can also think of 

- moving this logic to the sharding algorithm itself. That means, let the sharding algorithm decide which target names to select in case there is no sharding column in the SQL 

- and may be have a default behaviour, in case the sharding algorithm also does not return any target name.

**Comment by terrymanu** [comment]
hi, @rimal 
This is a good suggestion, but consider about ShardingSphere as a database, we maybe should not expose such complicated feature to end users.

We want discuss that maybe we have some new way to do this better.

We plan do SQL examine and verify feature in future, which can permit end user config verification rule to determine which SQL can be executed. `Sharding without sharding-cloumn` should one of rule for verification rule.

How do you think?

**Comment by rimal** [comment]
@terrymanu Thanks for your reply.

Honestly, I see Sharding JDBC as a layer over my datasource. I believe that since Sharding JDBC is actually a part of the application and not something in between the application and the database (like ProxySQL), Sharding JDBC is much more powerful as it can let me shard via an application logic as well and not only on basis of the SQL.

Also, I ll try to shed some light on my use case:

- I have a multi-tenant application and we are sharding by tenant identifier. 
- Almost all requests served by the application are within the scope of the tenant.
- Not all queries have the sharding column  (in my case, the tenant identifier). 
- If the query has sharding column, i will want to decide the target name as per that.
- Otherwise, I will fetch tenant information from the current request being served the application, and then decide target name from that 

I have a patch in my mind which should resolve this use case. If it will be ok, i can submit that as a pull request.

**Comment by terrymanu** [comment]
Beside Sharding-JDBC, ShardingSphere also include Sharding-Proxy, we want make same behavior with those 2 products except different access layer (JDBC or database protocol).

**Comment by terrymanu** [comment]
I prefer support multi-tenants to high level of Sharding-JDBC, which can make ShardingSphere as a infrastructure of data-sharding.

How about add a new module to handle multi-tenants upper of basic sharding feature?

**Comment by rimal** [comment]
> Beside Sharding-JDBC, ShardingSphere also include Sharding-Proxy, we want make same behavior with those 2 products except different access layer (JDBC or database protocol).

That is a fair point. 

What if we let the `ShardingStrategy` decide what to do if `shardingValues` is empty or not. Currently, `StandardRoutingEngine` does not even call the `ShardingStrategy` is `shardingValues` are empty. 

I have submitted a pull request with the above implementation. Will it be possible for you to check it once and see if it makes sense ?

**Comment by rimal** [comment]
@terrymanu @KomachiSion I have gone through the feedback on the attached PR. From what I understand, letting `ShardingStrategy` decide what to do if `shardingValues` is empty or not contradicts the design of ShardingSphere.

Referring back to the sql examine feature, can you please explain a bit more in detail on what are you guys planning in that feature. Would want to understand if that helps my use case or not. 

Mentioning my use case again, I need some way to override the behaviour of full-routing when no sharding column is there in the SQL.

**Comment by KomachiSion** [comment]
Hi @rimal, sorry for late reply. `SQL examine`  is a function to be done in the future. At this stage, ShardingSphere has no plan to implement. 

If you want to override the behaviour of full-routing when no sharding column, you can have a try `Sharding Hint`, doc: https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/hint/.

**Comment by rimal** [comment]
From my understanding, with use of `Sharding Hint`, the SQL will no longer be passed. I will always have to set the hint, even if the SQL had a sharding column.

Please correct me if my understanding is wrong.

This is my order of preference while deciding the shard
- If SQL has sharding column, I need to respect that
- If SQL does not have sharding column, I have some other logic to decide the shard.

**Comment by KomachiSion** [comment]
Yes, with use of `Sharding Hint`, the sharding value need to be added by set hint.

So for your case, may be you can fork a branch and implement like your PR to solve your problem first. 
But as we said before, that implementation we can't merge to main branch, we plan to use `SQL examine` to provide solution in the future.

**Comment by Tanzhimin** [comment]
I have the same request.I modified the source code.
remove  "null != HINT_MANAGER_HOLDER.get()"  in HintManagerHolder.
Specify sharding fields based on table configuration at system startup。I have about 800 tables.
Don't know if there's a better way?

**Comment by KomachiSion** [comment]
> I have the same request.I modified the source code.
> remove "null != HINT_MANAGER_HOLDER.get()" in HintManagerHolder.
> Specify sharding fields based on table configuration at system startup。I have about 800 tables.
> Don't know if there's a better way?

I don't know your business logic and situation, so I have no suggest for you.
And you said you have 800 tables, is it means you have 800 tables to shard? I don't think it is necessary for all tables to do sharding.

For most of users, they want to shard tables by one or a bit of columns, and query by this sharding columns so that application and database can scan less rows.
If you have many situation to query without sharding column, maybe it means you should to update your application structure rather than ShardingSphere.

**Comment by Tanzhimin** [comment]
@KomachiSion 
Thanks.
I have 800 tables,only 20 tables need to shard
20 tables add Rules Can shard and Routing to different databases.
In addition, tables that do not need shard can’t Routing to different databases.
I wrote a MyHintShardingAlgorithm. but if It doesn't work. 
Without shard field it‘s can't into MyHintShardingAlgorithm.doSharding();

**Comment by KomachiSion** [comment]
> @KomachiSion
> Thanks.
> I have 800 tables,only 20 tables need to shard
> 20 tables add Rules Can shard and Routing to different databases.
> In addition, tables that do not need shard can’t Routing to different databases.
> I wrote a MyHintShardingAlgorithm. but if It doesn't work.
> Without shard field it‘s can't into MyHintShardingAlgorithm.doSharding();

Try to use default-data-source instead of hint.
It should be used when tables is not sharding table.

**Comment by rimal** [comment]
> Yes, with use of `Sharding Hint`, the sharding value need to be added by set hint.
> 
> So for your case, may be you can fork a branch and implement like your PR to solve your problem first.
> But as we said before, that implementation we can't merge to main branch, we plan to use `SQL examine` to provide solution in the future.

Ok. Thanks

**Comment by KomachiSion** [comment]
This discussion has no response more than 7 days. We will close this issue.

**Comment by vikiuvb** [comment]
@strongduanmu I'm working on this. Please assign it to me.

**Comment by strongduanmu** [comment]
@vikiuvb Assigned.

**Comment by strongduanmu** [comment]
Fixed by #22857.
