### ISSUE TITLE
Fix algorithm type in ENCRYPT DDL document

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28288]
Now `EncryptAlgorithm` is divided into three categories: 
- StandardEncryptAlgorithm
- AssistedEncryptAlgorithm
-  LikeEncryptAlgorithm

of which only `StandardEncryptAlgorithm` can be configured in `ENCRYPT_ALGORITHM`.

<img width="702" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/67db8149-9878-4ed0-ada0-b3bc4c8e5226">

---

But the `ENCRYPT_ALGORITHM` in the DistSQL example still uses `MD5`, which needs to be corrected.

<img width="845" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/ce3acf12-5294-4bf0-9455-9cb0a1f26a27">

Ref: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule/

**Comment by yx9o** [comment]
Hi @RaigorJiang , can I.

**Comment by RaigorJiang** [comment]
@yx9o Thank you~
