### ISSUE TITLE
mutile databaseName in config-readwrite-splitting.yaml

### ISSUE THREAD

**Issue by kurosakisora** [apache/shardingsphere#28316]
there is just one databaseName in config-readwrite-splitting.yaml, so I can just associate one database in shardingsphere-proxy and one database in backend db，how to make more？

**Comment by RaigorJiang** [comment]
`databaseName` refers to the name of the logical database in ShardingSphere, and multiple backend DBs can be configured in dataSources.
Please refer to:
https://github.com/apache/shardingsphere/blob/master/proxy/bootstrap/src/main/resources/conf/config-readwrite-splitting.yaml
