### ISSUE TITLE
How to make the broadcast table forward only to the writing library?

### ISSUE THREAD

**Issue by nb333999** [apache/shardingsphere#28318]
ShardingProxy version number: 5.4.0
This is my configuration file (read-write separation, multi-master and multi-slave):

databaseName: na2069
dataSources:
  master_0:
    url: jdbc:mysql://172.30.10.26:3306/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  slave00:
    url: jdbc:mysql://172.30.10.26:33061/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  slave01:
    url: jdbc:mysql://172.30.10.26:33062/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

  master_1:
    url: jdbc:mysql://172.30.10.26:3316/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  slave10:
    url: jdbc:mysql://172.30.10.26:33161/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  slave11:
    url: jdbc:mysql://172.30.10.26:33162/na2060?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SINGLE
  tables:
    - "*.*"

- !BROADCAST
  tables:
    - merchant

- !SHARDING
  tables:
    admin:
      actualDataNodes: rw_ds_${0..1}.admin
  bindingTables:
    - admin
  defaultDatabaseStrategy:
    standard:
      shardingColumn: mid
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: rw_ds_${mid % 2}
        allow-range-query-with-inline-sharding: true
  defaultShardingColumn: mid

- !READWRITE_SPLITTING
  dataSources:
    rw_ds_0:
      writeDataSourceName: master_0
      readDataSourceNames:
        - slave00
        - slave01
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: round_robin
    rw_ds_1:
      writeDataSourceName: master_1
      readDataSourceNames:
        - slave10
        - slave11
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: round_robin
  loadBalancers:
    round_robin:
      type: ROUND_ROBIN

Table admin can read and write normally, and the sub-database is also normal.
However, when reading and writing the broadcast table merchant, it will be executed in all libraries such as master_0, slave00, master_1, slave11, etc.
![image](https://github.com/apache/shardingsphere/assets/110665193/32aa0824-6e86-4336-baff-1bf75601f1df)
![image](https://github.com/apache/shardingsphere/assets/110665193/71fd127d-34a7-4c65-890e-6b8747abb809)
But the effect I want for the broadcast table is:
  When reading, read from the read library that separates reading and writing.
  When writing, write to the write library that reads and writes separately.

For example 
  when reading:
    SELECT * FROM merchant WHERE `mid` = 132 LIMIT 0, 1000
    This SQL should poll read from slave00 and slave01
  when modifying:
    UPDATE merchant SET quota = quota - 10 WHERE `mid` = 132
    This SQL should be written to master_0

How should I configure it?

**Comment by RaigorJiang** [comment]
There may be a problem with broadcast routing. 
Hi @jiangML, Can you take a look?

**Comment by nb333999** [comment]
> There may be a problem with broadcast routing. Hi @jiangML, Can you take a look?

This question has been bugging me for a few days now, please help me solve this problem.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
