### ISSUE TITLE
Put the ShardingSphere configuration into spring boot application.yaml and manage it by nacos.

### ISSUE THREAD

**Issue by ztgoto** [apache/shardingsphere#28367]
Why doesn't ShardingSphere no longer provide a spring-boot-starter? So how do you put the configuration into application.yaml now? And our application.yaml is managed by the nacos configuration center, which means that we want the configuration of ShardingSphere to be managed by nacos as well.

**Comment by linghengqian** [comment]
- You can find more information at https://github.com/apache/shardingsphere/issues/22469 . Maintaining 4 sets of API writing in the same project is a heavy burden for the committer. I assume someone will want to do something like https://github.com/quarkiverse/quarkus-shardingsphere-jdbc , maintaining Spring Boot Starter might be more appropriate to handle downstream.  

- When you try to use cluster mode, you can register and synchronize configuration directly to nacos metadata.  Reference https://shardingsphere.apache.org/document/5.4.0/en/user-manual/common-config/builtin-algorithm/metadata-repository/ .

**Comment by xsg22** [comment]
This article may solve your problem. Connection: https://blog.csdn.net/xsgnzb/article/details/133642928

**Comment by wnose** [comment]
Why is nacos supported in 5.4.0 and nacos support removed in 5.4.1

**Comment by linghengqian** [comment]
> Why is nacos supported in 5.4.0 and nacos support removed in 5.4.1

- nacos has not been removed, the relevant implementation is now located at https://github.com/apache/shardingsphere-plugin.  

- However, because of https://github.com/apache/shardingsphere-plugin/issues/21, the maven artifacts of nacos need to be built locally and have not yet entered the maven central repo.

- You can try to contact other committers to discuss further issues about https://github.com/apache/shardingsphere-plugin . Currently, git only releases source code and binary files, but does not release them into the maven central repo.

**Comment by wnose** [comment]
> > Why is nacos supported in 5.4.0 and nacos support removed in 5.4.1
> 
> * nacos has not been removed, the relevant implementation is now located at https://github.com/apache/shardingsphere-plugin.
> * However, because of [The artifacts haven't published to the central maven repo shardingsphere-plugin#21](https://github.com/apache/shardingsphere-plugin/issues/21), the maven artifacts of nacos need to be built locally and have not yet entered the maven central repo.
> * You can try to contact other committers to discuss further issues about https://github.com/apache/shardingsphere-plugin . Currently, git only releases source code and binary files, but does not release them into the maven central repo.

Thx I will try it

**Comment by linghengqian** [comment]
- There is no response from the creator of the issue, so I think there is no point in continuing to open this issue.
