### ISSUE TITLE
有没有人知道怎么关闭shardingsphere在插入数据的时候自动设置默认值，比如create_date，在插入的时候手动设置成A，shardingsphere会根据数据库字段的属性 “NOT NULL DEFAULT CURRENT_TIMESTAMP” 成当前时间 B，怎么关掉这个功能？

### ISSUE THREAD

**Issue by CKReliancd** [apache/shardingsphere#28380]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
