### ISSUE TITLE
Change structure error

### ISSUE THREAD

**Issue by DMzmwh** [apache/shardingsphere#28399]
shardingJDBC 5.2.0, sql query is select *, the addition of fields should not affect the online program running, I now as long as the table structure will report an error, the database corresponding entity has no parameter construction method
Add field report:   org.springframework.dao.DataIntegrityViolationException: Error attempting to get column
Delete field message:  java.sql.SQLException: Column index out of range.
Restart the project to take effect

**Comment by terrymanu** [comment]
The information you provided does not fully understand the issue. Please refer to the issue template to fill the necessary information, which will help us catch the problem clearly.

**Comment by wpinchine** [comment]
在 shardingsphere-jdbc:5.5.1 上遇到了相同的问题 ，select * 处理返回值的时候使用了进程启动时加载的表结构缓存，增删表结构之后，字段数量与类型无法对齐。通过数组下标获取缓存的表结构字段时候：在表结构中间添加字段时，表结构字段次序发生变更，可能会产生类型转换异常；在删除字段的时候，会产生数组越界异常。
