### ISSUE TITLE
[DISCUSS] Release Plan of ShardingSphere 5.4.1

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#28411]
## Release 5.4.1

Hi community,

After last release, we have received a lot of feedback from users and developers. Now we plan to release the ShardingSphere 5.4.1 version these days, which has made a lot of optimization and improvement for these feedback.

Please refer to this release notes to confirm whether it contains the features you expect. If I missed anything, please remind me ASAP. If there are any suggestions, please feel free to tell us.

### Bug Fix
1. Scaling: Fix get inventory position not correctly on breakpoint resuming when table names are similar
2. Scaling: Fix CDC importer not start on breakpoint resuming when first inventory task is finished
3. Single Table: Fix not switched active version when CREATE/DROP table modifies the Single rule configuration
4. JDBC: Fix JDBC memory leak with MySQL in the 5.4.0 version

### Enhancement
1. Mode: Improve Standalone mode JDBC type impl reset data on initialization
2. Scaling: Isolate ShardingSphereDataSource Standalone repository in pipeline
3. Scaling: Disable system-schema-metadata-enabled in pipeline
4. JDBC: Move jdbc core META-INF/services/java.sql.Driver from test to main
5. Scaling: Add algorithm columns in SHOW MIGRATION CHECK ALGORITHMS DistSQL result
6. Scaling: Add type_aliaes column in SHOW MIGRATION CHECK ALGORITHMS DistSQL result
7. Encrypt: Add duplicate name check for derived columns and logical columns
8. Encrypt: Deny DDL for cipher columns in Proxy
9. Encrypt: Add the default type for derived columns to `varchar(4000)`

### New Feature
1. Proxy: Supports dbcp and c3p0 connection pools
2. Metadata: Standalone mode adapts to metadata new structure
3. Governance: Governance supports register  instance level data source

**Comment by linghengqian** [comment]
- Hi, although the PR related to SnakeYAML 2.0 ( #24636 ) is no longer possible to enter the 5.4.1 milestone, can we include a related documentation statement PR into the 5.4.1 milestone? The related documentation PR is located at #28303 .
- It seems that some issues ask for an explanation of the Error seen in Spring Boot OSS 3. Like 
    - #28067 
    - #27370 
    - #28233 
    - #26041 
    - #25291

**Comment by taojintianxia** [comment]
> * Hi, although the PR related to SnakeYAML 2.0 ( [Upgrade snakeyaml to 2.0 #24636](https://github.com/apache/shardingsphere/pull/24636) ) is no longer possible to enter the 5.4.1 milestone, can we include a related documentation statement PR into the 5.4.1 milestone? The related documentation PR is located at [Add a description of the Jakarta EE namespace in the documentation for Spring Boot #28303](https://github.com/apache/shardingsphere/pull/28303) .
> * It seems that some issues ask for an explanation of the Error seen in Spring Boot OSS 3. Like
>   
>   * [Please support snakeyaml 2.0. #28067](https://github.com/apache/shardingsphere/issues/28067)
>   * [The service starts the error when upgrade snakeyaml to version 2.0 #27370](https://github.com/apache/shardingsphere/issues/27370)
>   * [Snakeyml 2.1 compatibility issue with shardingsphere-jdbc-core-spring-boot-starter 5.2.1 #28233](https://github.com/apache/shardingsphere/issues/28233)
>   * [Transition from Java EE to Jakarta EE #26041](https://github.com/apache/shardingsphere/issues/26041)
>   * [Sharding startup failed after upgrading the snake yml component to version 2.0 #25291](https://github.com/apache/shardingsphere/issues/25291)

seems it's already approved by community .

**Comment by qiuweilu** [comment]
https://github.com/apache/shardingsphere/issues/28397

**Comment by Yule-Momoko** [comment]
Is it possible to support pulling sharding.yaml configuration from nacos?

**Comment by linghengqian** [comment]
- This issue is resolved by https://github.com/apache/shardingsphere/releases/tag/5.4.1 .

**Comment by linghengqian** [comment]
- @Yule-Momoko Welcome to open a new issue.  

- @qiuweilu For https://github.com/apache/shardingsphere/issues/28397 , it looks like it lacks a minimal reproducible unit test, you can write a git using testcontainers.
