### ISSUE TITLE
Check algorithm type in encrypt DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28416]
Hi, this is for #28288.

When user executes `CREATE ENCRYPT RULE / ALTER ENCRYPT RULE`, we also need to check the algorithm type. 
For example, the type of `AssistedEncryptAlgorithm` cannot be used in `ENCRYPT_ALGORITHM`.

Ref: https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/encrypt/create-encrypt-rule/

**Comment by yx9o** [comment]
Hi @RaigorJiang , can I.

**Comment by RaigorJiang** [comment]
@yx9o Sure, thanks for your help!
