### ISSUE TITLE
Replace `new Date().getTime()` with `System.currentTimeMillis()`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28426]
Currently, the agent uses `new Date().getTime()` to obtain millisecond time, which should be replaced with `System.currentTimeMillis()`

<img width="1387" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/e73d9c26-2b4a-42fd-988b-c7bf1a4731b7">

**Comment by 134130** [comment]
I think these codes are not in `master` branch; Any classes appeared on your screenshot is not exists.
Let me know if these codes are not merged in `master` branch yet.
