### ISSUE TITLE
Check duplicate column name usage in encrypt DistSQL

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#28440]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master(be717e1733d2f9ef99c6348b069be099a6904c8f)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior
I create a encrypt rule with DistSQL
```SQL
CREATE ENCRYPT RULE t_order (COLUMNS((NAME=`user`,CIPHER=`user`,LIKE_QUERY=`user`, ENCRYPT_ALGORITHM(TYPE(NAME='AES',PROPERTIES('aes-key-value'='833FA067','digest-algorithm-name'='SHA-512'))),LIKE_QUERY_ALGORITHM(TYPE(NAME=CHAR_DIGEST_LIKE)))));
```
Both the plain column and the cipher column are configured as `user_id`

So this is an incorrect configuration and should report an error.
### Actual behavior
Create successed.

### Reason analyze (If you can)
Missing validation, same issue exists with ALTER ENCRYPT RULE

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Prepare a regular data source, configure it to Proxy and start

Create a logic database and excute:
```SQL
CREATE ENCRYPT RULE t_order (COLUMNS((NAME=`user`,CIPHER=`user`,LIKE_QUERY=`user`, ENCRYPT_ALGORITHM(TYPE(NAME='AES',PROPERTIES('aes-key-value'='833FA067','digest-algorithm-name'='SHA-512'))),LIKE_QUERY_ALGORITHM(TYPE(NAME=CHAR_DIGEST_LIKE)))));
```

**Comment by daleyzou** [comment]
I will try to resolve it.

**Comment by Pace2Car** [comment]
@daleyzou Thank you!
