### ISSUE TITLE
generateKey() would called twice in an insert method of mybatis

### ISSUE THREAD

**Issue by LinYuanq** [apache/shardingsphere#28456]
## Question

org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#createExecutionContext(org.apache.shardingsphere.infra.binder.QueryContext)
in this method,  SQLCheckEngine.check() & kernelProcessor.generateExecutionContext() would both call generateKey() method, which would make the Key to be discontinuous and always even

**Comment by terrymanu** [comment]
The information you provided does not fully understand the issue. Please refer to the issue template to fill the necessary information, which will help us catch the problem clearly.
