### ISSUE TITLE
Problems executing multiple sql

### ISSUE THREAD

**Issue by xiaomizhou2** [apache/shardingsphere#28461]
### Which version of ShardingSphere did you use?
v5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

My Database connection jdbc-url is open 'allowMultiQueries=true'

### MyBatis Xml Examples: 
```xml
<insert id="insert">
   INSERT INTO t_user (username,password) VALUES(#{username}, #{password});
   INSERT INTO t_user_role(user_id,role_id) VALUES(#{userId}, #{roleId});
</insert>
```

### Actual behavior

Cause: java.sql.SQLException: No value specified for parameter 18
; bad SQL grammar []; nested exception is java.sql.SQLException: No value specified for parameter 18

**Comment by terrymanu** [comment]
Can not support this feature
