### ISSUE TITLE
The query could not be successfully routed WITH RECURSIVE

### ISSUE THREAD

**Issue by sunday1105** [apache/shardingsphere#28474]
## Question
Which version supports recursive queries?

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.1.0</version>
</dependency>

Logic SQL: WITH RECURSIVE DirectoryCTE as (
        select *
        from table1
        where id = ?
        and project_id = ?
        union all
        select *   
        from table1 t
        INNER JOIN DirectoryCTE cte ON t.project_id = cte.project_id and t.parent_id = cte.id
        )
        select
        *  
        from DirectoryCTE
        order by `level`

---------------

Actual SQL: ds-master ::: WITH RECURSIVE DirectoryCTE as (
        select *
        from table1
        where id = ?
        and project_id = ?
        union all
        select *
        from project_file_catalog t
        INNER JOIN DirectoryCTE cte ON t.project_id = cte.project_id and t.parent_id = cte.id
        )
        select *
        from DirectoryCTE
        order by `level`

**Comment by strongduanmu** [comment]
Hi @sunday1105, CTE is not supported with sharding table now.

**Comment by zihaoAK47** [comment]
Hi, I would like to try to solve this problem. Please assign it to me. Thank you

**Comment by strongduanmu** [comment]
@zihaoAK47 Welcome.

**Comment by linghengqian** [comment]
- In this week's release of Calcite 1.36, https://issues.apache.org/jira/browse/CALCITE-129 has been resolved. This means that to support `recursive with`, ShardingSphere needs to change the Calcite version first.

**Comment by linghengqian** [comment]
- @zihaoAK47 Do you have time to verify? According to the unit test at https://github.com/apache/calcite/pull/3480 , the relevant statements should execute perfectly under Apache Calcite 1.36.0.  The originator of this issue did not provide git for verification.

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated and removed in 5.3.0, please try new version and use ShardingSphere Driver.

**Comment by phoema** [comment]
which version support  MYSQL8 WITH RECURSIVE

**Comment by linghengqian** [comment]
> which version support  MYSQL8 WITH RECURSIVE

The current issue is clearly closed not because of a PR, but because no one is using 5.5.3-SNAPSHOT to provide a Git repository with unit tests for verification.
