### ISSUE TITLE
REGISTER STORAGE UNIT and  create sharding table rule ERROR 30000 (HY000) 

### ISSUE THREAD

**Issue by jiahuiss** [apache/shardingsphere#28478]
DISTSQL：

REGISTER STORAGE UNIT ds_XXXX  or  ALTER SHARDING TABLE RULE  rule_name Report an error:
mysql> REGISTER STORAGE UNIT ds_xxxx_dev (
    -> URL="jdbc:mysql://127.0.0.1:3306/database0?serverTimezone=UTC&useSSL=false&useServerPrepStmts=false&prepStmtCacheSize=512&prepStmtCacheSqlLimit=256&useUnicode=true&characterEncoding=utf8&character_set_server=utf8mb4&connectionCollation=utf8mb4_unicode_ci",
    -> USER="",
    -> PASSWORD="",
    -> PROPERTIES("maximumPoolSize"=100,"idleTimeout"="30000")
    -> );
ERROR 30000 (HY000): Unknown exception: Max length of resource name exceeded: should be less than 45

log output:
![image](https://github.com/apache/shardingsphere/assets/142789122/700976b0-6443-4ba5-9800-5f49c3673eaf)

**Comment by zhaojinchao95** [comment]
Ref #22772
