### ISSUE TITLE
How to implement the node heartbeat check for Shardingsphere-proxy node

### ISSUE THREAD

**Issue by sweat-xsl** [apache/shardingsphere#28484]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by zhaojinchao95** [comment]
Maybe you can use HAproxy or keepalived tools

**Comment by sweat-xsl** [comment]
Are there any ideas that are in line with sharding's ecology, such as perhaps using distsql to explore each proxy node if health

**Comment by sweat-xsl** [comment]
> Maybe you can use HAproxy or keepalived tools

Are there any ideas that are in line with sharding's ecology, such as perhaps using distsql to explore each proxy node if health
