### ISSUE TITLE
Add more unit test for ShardingSphereStatistics

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28489]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ShardingSphereStatistics to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by KonarzewskiP** [comment]
Hi @zhaojinchao95,
I would like to work on this issue. Please assign it to me.
