### ISSUE TITLE
Add unit test for ClusterStatusSubscriber

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28488]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ClusterStatusSubscriber to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by ayusheshan** [comment]
Hi, I have raised a PR for this issue here: https://github.com/apache/shardingsphere/pull/28749
