### ISSUE TITLE
怎样实现对Shardingsphere-proxy节点实现节点探活功能

### ISSUE THREAD

**Issue by sweat-xsl** [apache/shardingsphere#28481]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by zhaojinchao95** [comment]
Please transalte your issue title to english.
