### ISSUE TITLE
Add unit test for NewDatabaseMetaDataNode#getDataSourceNodeWithVersion

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28495]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for NewDatabaseMetaDataNode to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by JessikaFujimura** [comment]
Hi, How are you doing?

I'd like to do this task. 

Thank you!

**Comment by terrymanu** [comment]
The method has been refactored, I just close the issue
