### ISSUE TITLE
Add more unit test for ShardingSphereSchemaData

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28490]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ShardingSphereSchemaData to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by archits581** [comment]
Hi, I am interested in working on this issue. Can I have a try at it?

**Comment by archits581** [comment]
Hi @zhaojinchao95, I have created a pull request to add more unit tests. Can you review the pull request and provide me with any feedback?
