### ISSUE TITLE
Add more unit test for NewDatabaseMetaDataNode#getDataSourceNodeVersionsNode

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28496]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for NewDatabaseMetaDataNode to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by rajeshwarrao055** [comment]
Hi @zhaojinchao95 ,

Can i pick this ?
