### ISSUE TITLE
Add more unit tests for NotExpressionBinder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28504]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for NotExpressionBinder to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by Sakshi-75** [comment]
Hi @strongduanmu , can I work on this?

**Comment by strongduanmu** [comment]
Of course. I just assign it to you.
