### ISSUE TITLE
Add more unit tests for SubqueryExpressionSegmentBinder

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28506]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for SubqueryExpressionSegmentBinder to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by strongduanmu** [comment]
@Sakshi-75 Welcome, I will assign this issue to you.

**Comment by Sakshi-75** [comment]
Hi @strongduanmu , I've raised a PR for this. Please review. Thanks!
