### ISSUE TITLE
Add more unit tests for SingleIndexReviser

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28518]
Hi community,

This issue is for #28487.

Aim
Add more unit tests for SingleIndexReviser to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by anogueiraFlywire** [comment]
Hi, @zhaojinchao95 , @iamhucong 
I'd like to work on this

**Comment by anogueiraFlywire** [comment]
Hi @iamhucong 
Is this ready to be merged?
