### ISSUE TITLE
Add more unit tests for SingleTableLoadUtils

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28519]
Hi community,

This issue is for #28487.

Aim
Add more unit tests for SingleTableLoadUtils to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by LaylaSilbernberg** [comment]
Hello! I am a junior looking to expand my testing skills and this looks very interesting. Could I contribute to this project?

**Comment by jbizzi** [comment]
Hi! Can I be assigned to solve this issue?

**Comment by terrymanu** [comment]
@jbizzi Welcome
