### ISSUE TITLE
Add more unit tests for NewInternalMetaDataFactory

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28514]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

Aim
Add more unit tests for NewInternalMetaDataFactory to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by terrymanu** [comment]
NewInternalMetaDataFactory has been removed
