### ISSUE TITLE
Add unit test for AESEncryptAlgorithm

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#28517]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for AESEncryptAlgorithm to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by Sakshi-75** [comment]
Hi @zhaojinchao95 , can I work on this?

**Comment by KonarzewskiP** [comment]
Hi @zhaojinchao95 
I would like to work on this issue, could you please assign it to me. Thanks!

**Comment by KonarzewskiP** [comment]
Hi @zhaojinchao95 
It looks like this task is already completed.  https://github.com/apache/shardingsphere/blob/master/features/encrypt/core/src/test/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithmTest.java
