### ISSUE TITLE
Add more unit tests for ReadwriteSplittingDataSourceRouter

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28527]
Hi community,

This issue is for #28487.

Aim
Add more unit tests for ReadwriteSplittingDataSourceRouter to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by Gowrishankar04** [comment]
Hi @iamhucong,

Can you please assign this to me?

**Comment by terrymanu** [comment]
Fixed by #32854
