### ISSUE TITLE
Add more unit tests for ShardingSchemaTableAggregationReviser

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28525]
Hi community,

This issue is for #28487.

Aim
Add more unit tests for ShardingSchemaTableAggregationReviser to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by terrymanu** [comment]
Fixed by #33669
