### ISSUE TITLE
Add more unit tests for BroadcastSQLRouter

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28521]
Hi community,

This issue is for #28487.

Aim
Add more unit tests for BroadcastSQLRouter to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

Basic Qualifications
Java
Maven
Junit

**Comment by TherChenYang** [comment]
can you assign this task to me？

**Comment by strongduanmu** [comment]
@TherChenYang Welcome to join ShardingSphere community, please enjoy it.

**Comment by TherChenYang** [comment]
> @TherChenYang Welcome to join ShardingSphere community, please enjoy it.

Hi @strongduanmu , please review and let me know if any changes are required in this PR. Thanks!
