### ISSUE TITLE
Add more unit tests for SingleMetaDataReviseEntry

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28533]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for SingleMetaDataReviseEntry to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by Sakshi-75** [comment]
Hi @tuichenchuxin , can I work on this?

**Comment by Sakshi-75** [comment]
Hi @tuichenchuxin , I've raised a PR for this. Please review. Thanks!
