### ISSUE TITLE
Add more unit tests for ShardingMetaDataReviseEntry

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28532]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ShardingMetaDataReviseEntry to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by harshithasudhakar** [comment]
Hi @tuichenchuxin, I'd like to take this up :)

**Comment by traitsisgiorgos** [comment]
hi, is the issue still open?

**Comment by shubham-j-sde** [comment]
Hi, I would like to take this issue, if it's still open
