### ISSUE TITLE
Add more unit tests for CDCResponseUtils

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#28530]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for CDCResponseUtils to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by KonarzewskiP** [comment]
Hi @azexcy 
I would like to work on this issue, please assign it to me.

**Comment by azexcy** [comment]
> Hi @azexcy I would like to work on this issue, please assign it to me.

OK, thanks
