### ISSUE TITLE
Add more unit tests for CDCImporterManager

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#28539]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for CDCImporterManager to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by isdrchagas** [comment]
hey, can I work on this?

**Comment by strongduanmu** [comment]
Welcome @isdrchagas, I just assign this issue to you.

**Comment by isdrchagas** [comment]
Hey guys, I hope this message finds you well. I wanted to inform you that I've already submitted my pull request, you can find it here https://github.com/apache/shardingsphere/pull/28666
