### ISSUE TITLE
Add more unit tests for IndexReviseEngine

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28536]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for IndexReviseEngine to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by JessikaFujimura** [comment]
Hi, I’d like to do this issue.

Thank you!

**Comment by JessikaFujimura** [comment]
Hi,
I open a PR https://github.com/apache/shardingsphere/pull/28834.
Let me know if any adjustment is necessary. 

Thank you very much!
