### ISSUE TITLE
Add more unit tests for ConstraintReviseEngine

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28537]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ConstraintReviseEngine to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by anogueiraFlywire** [comment]
Hi, @tuichenchuxin 
I'd like to work on this, can you please assign it to me?

**Comment by anogueiraFlywire** [comment]
Hi @tuichenchuxin,
Can you please review my PR?

**Comment by traitsisgiorgos** [comment]
hi, is the issue open?

**Comment by anogueiraFlywire** [comment]
Yes, I've asked for reviews several times, never got an approval + merge
