### ISSUE TITLE
Add more unit tests for EncryptMetaDataReviseEntry

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28531]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for EncryptMetaDataReviseEntry to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by saikiranpatil** [comment]
@tuichenchuxin can u assign this to me?

**Comment by KonarzewskiP** [comment]
Hi @tuichenchuxin 
I would like to work on this issue, could you please assign it to me.

**Comment by shubham-j-sde** [comment]
Hi,
can someone plz help with review.
Thanks
