### ISSUE TITLE
Add more unit tests for ExpressionSegmentBinder

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28538]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for ExpressionSegmentBinder to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by Gowrishankar04** [comment]
Hi @tuichenchuxin,

I would like to work on this. can you please assign this to me?

Thanks

**Comment by strongduanmu** [comment]
@Gowrishankar04 Welcome, I just assign it to you.

**Comment by KonarzewskiP** [comment]
Hi @tuichenchuxin 
I would like to work on this issue. Please assign it to me.

**Comment by Divyansh200102** [comment]
Hi, @strongduanmu I tried working on this issue but I am facing this error during the building 

![image](https://github.com/apache/shardingsphere/assets/146909065/4f127fe4-6f75-4d4d-99aa-c2e8c9571d2d)

**Comment by strongduanmu** [comment]
@Divyansh200102 You can try `./mvnw clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true -Dmaven.test.skip=true` first. Since we need Antlr generates code for SQL parsing.

**Comment by Divyansh200102** [comment]
> ./mvnw clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true -Dmaven.test.skip=true

I ran the command and build failure is coming

![image](https://github.com/apache/shardingsphere/assets/146909065/0717f549-f64a-443a-a4d3-122b132aa054)

**Comment by Divyansh200102** [comment]
> ./mvnw clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true -Dmaven.test.skip=true

I ran this command @strongduanmu but build failure is coming
![image](https://github.com/apache/shardingsphere/assets/146909065/d8fac87d-081a-4918-9e67-ce8b90dd9053)

**Comment by strongduanmu** [comment]
Can you remove `-Dmaven.javadoc.skip=true`?

**Comment by Divyansh200102** [comment]
> ./mvnw clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true -Dmaven.test.skip=true

@strongduanmu the build failure is still coming...

**Comment by SankarshanMishra** [comment]
hello Sir, 
I would like to work on this issue Kindly assign me this issue also it is going to be my first opensource contribution so kindly guide me a little.
Thank You.

**Comment by strongduanmu** [comment]
@Gowrishankar04 Welcome, I just assign this issue to you.

**Comment by SankarshanMishra** [comment]
This is my first time contributing to open source. I'm familiar with JUnit5
and creating fake repositories, as well as using data structures for test
cases(Mockito).However, I'm unsure how to apply these skills in this
specific context. Kindly provide me some guidance?

**Comment by SankarshanMishra** [comment]
![Screenshot (575)](https://github.com/apache/shardingsphere/assets/124585946/fdceec58-be15-4637-ac99-6815fe8b2755)
I dont know why I am unable to find the java file when claerly the location of the file is this Kindly help me out here a little shardingsphere\infra\binder\src\main\java\org\apache\shardingsphere\infra\binder\segment\expression\ExpressionSegmentBinder.java
Thank You

**Comment by AbnerHuang2** [comment]
@strongduanmu Pls assign to me.
