### ISSUE TITLE
Add more unit tests for SchemaMetaDataReviseEngine

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28534]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for SchemaMetaDataReviseEngine to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by mariacavalc** [comment]
Hey, can i take this one?

**Comment by HarshSawarkar** [comment]
hi @tuichenchuxin I would like to work on this issue.I have this one query regarding private revise() method.Do I need to write tests for this method also?Please see the attachment below.  
![image](https://github.com/apache/shardingsphere/assets/96522794/48c8f3dd-f4e9-4df1-b14a-b4bf6e95f900)

**Comment by tuichenchuxin** [comment]
@HarshSawarkar No need to write test for private method

**Comment by HarshSawarkar** [comment]
hey @tuichenchuxin  i have raised a PR for this issue.Can you please review it . Here's the link  https://github.com/apache/shardingsphere/pull/29240
