### ISSUE TITLE
Add more unit tests for TableMetaDataReviseEngine

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28535]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for TableMetaDataReviseEngine to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by gagan-gv** [comment]
Can I take this up?

**Comment by strongduanmu** [comment]
Of course, I will assign this issue to you.

**Comment by gagan-gv** [comment]
Hey, I've added the test cases and have raised a PR: https://github.com/apache/shardingsphere/pull/28626

**Comment by gagan-gv** [comment]
Hey, just forgot to add the licence before the code, so, raising a new PR.

**Comment by gagan-gv** [comment]
Please find the PR link below:
https://github.com/apache/shardingsphere/pull/28627

**Comment by gagan-gv** [comment]
Hi, I've run all the pre-build checks and have updated the PR.

**Comment by gagan-gv** [comment]
Hey, @strongduanmu can you please review the PR.
Thank you!

**Comment by gagan-gv** [comment]
Hi, I've made changes to PR as per the previous comments. Requesting someone to review the PR.

Thank you!

**Comment by gagan-gv** [comment]
Hey, @strongduanmu can you please review the PR.
Thank you!

**Comment by gagan-gv** [comment]
Hey, @strongduanmu I have made the changes to the PR, can you please review it.

Thank you!
