### ISSUE TITLE
Add unit test for PipelineJobProgressDetector

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28541]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `PipelineJobProgressDetector` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by ashutosh-roy** [comment]
Please assign this to me.

**Comment by sandynz** [comment]
@ashutosh-roy welcome

**Comment by KonarzewskiP** [comment]
Hi @sandynz 
I would like to work on this issue. Please assign it to me.

**Comment by sandynz** [comment]
@KonarzewskiP welcome! Assigned to you.
