### ISSUE TITLE
Add unit test for PipelineJobCenter

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28542]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `PipelineJobCenter` to test its public functions to improve unit test coverage. Methods: addJob, isJobExisting, getJob, getJobItemContext, getShardingItems.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by MihirKohli** [comment]
Willing to volunteer but i have no experience in unit testing? How to get started?

**Comment by sandynz** [comment]
Hi @MihirKohli , welcome! You could have a look at some JUnit 5 tutorials and reference unit tests in `kernel/data-pipeline/core/src/test/java/`.

**Comment by pavanbaloju** [comment]
Hi @sandynz I can work on this. Can you assign this to me?

**Comment by AbhineshJha** [comment]
hey  ! can i  work on this issue ? can u assign me ?

**Comment by 20t3r** [comment]
@sandynz Hi, can I please work on this issue? I’m a uni student who’s new to open source projects, but I will try my best for the pull request.

**Comment by ShamithaReddy** [comment]
hey, anyone working on this issue?

**Comment by sandynz** [comment]
> hey @MihirKohli ! can i work on this issue ? can u assign me ?

Welcome. You could work on it. There's no response more than 2 weeks.

**Comment by MihirKohli** [comment]
> > hey @MihirKohli ! can i work on this issue ? can u assign me ?
> 
> Welcome. You could work on it. There's no response more than 2 weeks.

Currently i am facing some issues meanwhile you can assign it to someone else

**Comment by sandynz** [comment]
OK, thanks. Welcome back

**Comment by HarshSawarkar** [comment]
hey @sandynz Can i pick this issue?

**Comment by HarshSawarkar** [comment]
I have raised a PR for the issue #28879.Here's the link
https://github.com/apache/shardingsphere/pull/28879

**Comment by sandynz** [comment]
Thanks all friends! Welcome to pick other issues.
