### ISSUE TITLE
Add unit test for GovernanceRepositoryAPIImpl persistJobOffsetInfo, getJobOffsetInfo

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28544]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `GovernanceRepositoryAPIImpl` to test its `persistJobOffsetInfo` and `getJobOffsetInfo` functions to improve unit test coverage. Unit test could be added in existing `GovernanceRepositoryAPIImplTest`.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by pavanbaloju** [comment]
Hi @sandynz, I can work on this. Can you please assign this to me?
