### ISSUE TITLE
Add unit test for GovernanceRepositoryAPIImpl.isExisted

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28543]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `GovernanceRepositoryAPIImpl` to test its `isExisted` function to improve unit test coverage. Unit test could be added in existing `GovernanceRepositoryAPIImplTest`.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by anogueiraFlywire** [comment]
Hi @sandynz,
I'd like to work on this issue as my first contribution ever to an OpenSource project
Can I get it assigned to me?

Thank you!

**Comment by sandynz** [comment]
@anogueiraFlywire Thanks for your contribution.
