### ISSUE TITLE
Add more unit tests for EncryptColumnNameReviser

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28549]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for EncryptColumnNameReviser to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by ivalkshfoeif** [comment]
Hi @tuichenchuxin, I heard from one of the OSD mentors that the Sharding Sphere is no longer in OSD2023 any more. I'm still interested in those issues and wondering if they are up for grabs.

**Comment by nikunjgupta609** [comment]
Please assign me with this issue.

**Comment by strongduanmu** [comment]
@nikunjgupta609 Assigned, good luck for you.

**Comment by HarshSawarkar** [comment]
Can I pick this Issue if no one else is working on it?

**Comment by HarshSawarkar** [comment]
Hi @tuichenchuxin I have created the pull request for this issue.Here's the link to my pull request https://github.com/HarshSawarkar/shardingsphere/pull/1

**Comment by tuichenchuxin** [comment]
> Hi @tuichenchuxin I have created the pull request for this issue.Here's the link to my pull request [HarshSawarkar#1](https://github.com/HarshSawarkar/shardingsphere/pull/1) Please can you review.

@HarshSawarkar I have checked, please submit your pr to shardingsphere

**Comment by HarshSawarkar** [comment]
Hi @tuichenchuxin I have submitted PR to shardingsphere.Can you please check.
