### ISSUE TITLE
Add unit test for YamlTableDataConsistencyCheckResultSwapper

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28540]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `YamlTableDataConsistencyCheckResultSwapper` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by pavanbaloju** [comment]
Hi @sandynz, I am interested to work on this. Can you please assign this to me?

**Comment by sandynz** [comment]
Hi @pavanbaloju , welcome!
