### ISSUE TITLE
Add unit test for GovernanceRepositoryAPIImpl persistLatestCheckJobId, getLatestCheckJobId, deleteLatestCheckJobId

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#28545]
Hi community,

This issue is for https://github.com/apache/shardingsphere/discussions/28487.

## Aim
Add more unit tests for `GovernanceRepositoryAPIImpl` to test its `persistLatestCheckJobId`, `getLatestCheckJobId` and `deleteLatestCheckJobId` functions to improve unit test coverage. Unit test could be added in existing `GovernanceRepositoryAPIImplTest`.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

## Basic Qualifications
- Java
- Maven
- Junit

**Comment by ManaMatrix** [comment]
Hello, I'd like to work on this, could you please assign this issue to me?

**Comment by sandynz** [comment]
Hi @ManaMatrix , welcome! Assigned to you.
