### ISSUE TITLE
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.ExpressionSegment

### ISSUE THREAD

**Issue by huanglf714** [apache/shardingsphere#28551]
## sql is 
    <update id="setPointCommodityDefaultSort">
        update
            itg_point_commodity_ext_t
        set sort = id
        where sort is null
    </update>

## expection
org.apache.ibatis.exceptions.PersistenceException:

**Comment by strongduanmu** [comment]
Hi @huanglf714, the 4.1.1 version is too old and is not currently maintained. Welcome to test with the latest version.

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
