### ISSUE TITLE
mysql-connector-java 8.0.x版本分片不生效

### ISSUE THREAD

**Issue by wpd-static** [apache/shardingsphere#28578]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
Hi @wpd-static, can you submit issue according to issue template?

**Comment by wpd-static** [comment]
In a java test project,springboot project,the pom file is imported,` <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.32</version>
            <scope>runtime</scope>
        </dependency>`,`<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.0</version>
        </dependency>`,` <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.3</version>
        <relativePath/>
    </parent>`.
The test code is,       
        ` ObString obString = new ObString();
        obString.setId(MyIdUtil.getSnowflakeNextId());
        obString.setRefId(1704678770319065096L);
        obString.setName("测试");
        obString.setValue("测试");
        String sql = "INSERT INTO ob_string (id,name, value, ref_id) VALUES (?, ?, ?, ?)";
        jdbcTemplate.update(sql, obString.getId(), obString.getName(), obString.getValue(), obString.getRefId());`
in JdbcTemplate execute 427 row, `ps = psc.createPreparedStatement(con);`No execution **ShardingSpherePreparedStatement**,i'm sorry to trouble you

**Comment by wpd-static** [comment]
table<ob_string> no fragment, error message :the table<ob_string> does not exist,When I replace ` <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            **<version>5.1.49</version>**
            <scope>runtime</scope>
        </dependency>`, Correct code execution,  Actual SQL: db0 ::: INSERT INTO ob_string_8 (id,name, value, ref_id) VALUES (?, ?, ?, ?) ::: [1706296697183092748, 测试, 测试, 1704678770319065096]

**Comment by zhaojinchao95** [comment]
Only support english to ask question, i will close it, you can create a new issue with english.
