### ISSUE TITLE
Fuzzy Query of Encrypted Fields

### ISSUE THREAD

**Issue by chengxunhuang** [apache/shardingsphere#28587]
## Bug Report
When performing fuzzy queries on encrypted fields, use distsql to create rules, as follows:
CREATE ENCRYPT RULE test (
	COLUMNS ((
			NAME = col1,
			likeQueryColumn = col1,
			likeQueryEncryptorName =like_encryptor,
			CIPHER = col1,
			ENCRYPT_ALGORITHM (
				TYPE (
					NAME = 'MySm4',
				PROPERTIES ( 'sm4-key' = 'a4311fa82f52d513f43a79a281c86ec1', 'sm4-mode' = 'ECB', 'sm4-padding' = 'PKCS5Padding' ))))));
Using this statement will display grammar errors。
If the fuzzy query column is removed, it can be successfully added，
CREATE ENCRYPT RULE test (
	COLUMNS ((
			NAME = col1,
			CIPHER = col1,
			ENCRYPT_ALGORITHM (
				TYPE (
					NAME = 'MySm4',
				PROPERTIES ( 'sm4-key' = 'a4311fa82f52d513f43a79a281c86ec1', 'sm4-mode' = 'ECB', 'sm4-padding' = 'PKCS5Padding' ))))));

So how to write distsql with likeQueryColumn and likeQueryEncryptorName

### Which version of ShardingSphere did you use?
5.3.1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

**Comment by strongduanmu** [comment]
@chengxunhuang Can you format your distsql? It's hard to read.
