### ISSUE TITLE
Fuzzy Query SQL Rewriting Problem for Cryptographic Columns

### ISSUE THREAD

**Issue by chengxunhuang** [apache/shardingsphere#28590]
### Which version of ShardingSphere did you use?
5.3.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
When performing a fuzzy query on ciphertext columns, I printed the SQL from sharding and found that the SQL was not the original value of the fuzzy query after being rewritten
### Actual behavior
![Snipaste_2023-09-26_14-44-07](https://github.com/apache/shardingsphere/assets/56817751/29599a72-eb9d-4c21-a3f6-03252884c800)

**Comment by strongduanmu** [comment]
Can you privode more information? I can't get your point from your issue.

**Comment by chengxunhuang** [comment]
good，The configuration is as follows：
![Snipaste_2023-09-26_14-44-07](https://github.com/apache/shardingsphere/assets/56817751/8231ccde-ed67-4a11-a4b0-4601404beb66)

The query statement is as follows：
navicat Connect proxy Execute SQL   SELECT * FROM  test where col1 like '2%' ;
In proxy, the SQL is rewritten as ： [INFO ] 2023-09-26 15:45:57.763 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: 5e869ce2cf334acc8687bf21dfb51d34 ::: SELECT `test`.`id`, `test`.`col1` AS `col1`, `test`.`col2` FROM  test where col1 like '1%'

**Comment by chengxunhuang** [comment]
@strongduanmu

**Comment by strongduanmu** [comment]
This is an expected result. The like encryption algorithm will digest the value of the like fuzzy query. For details, please refer to: https://mp.weixin.qq.com/s/Y4AYAaHnWhdxwmgV-6RZqA

**Comment by chengxunhuang** [comment]
That is to say, currently, the fuzzy query of ciphertext fields is biased, and it may not be able to be found。

**Comment by chengxunhuang** [comment]
I have another thing to ask you, how should the distSQL for the two fields likeQueryColumn and likeQueryEncryptorName be written。`CREATE ENCRYPT RULE test (
	COLUMNS ((
			NAME = col1,
			likeQueryColumn = col1,
			likeQueryEncryptorName =like_encryptor,
			CIPHER = col1,
			ENCRYPT_ALGORITHM (
				TYPE (
					NAME = 'MySm4',
				PROPERTIES ( 'sm4-key' = 'a4311fa82f52d513f43a79a281c86ec1', 'sm4-mode' = 'ECB', 'sm4-padding' = 'PKCS5Padding' ))))));`This has syntax errors, but after removing the likeQueryColumn and likeQueryEncryptorName, it can be added. Currently, does the version of likeQueryColumn and likeQueryEncryptorName not support distSQL。

**Comment by chengxunhuang** [comment]
@strongduanmu

**Comment by strongduanmu** [comment]
> That is to say, currently, the fuzzy query of ciphertext fields is biased, and it may not be able to be found。

All can be found, but for security reasons, the query results may be more than the actual value.

**Comment by chengxunhuang** [comment]
> > That is to say, currently, the fuzzy query of ciphertext fields is biased, and it may not be able to be found。
> 
> All can be found, but for security reasons, the query results may be more than the actual value.
> 
> In addition, as a reminder, in order to support like queries, data needs to be written through ShardingSphere to ensure that the same encryption method is used for reading and writing.

The current phenomenon is that the proxy configuration is as follows:
![配置](https://github.com/apache/shardingsphere/assets/56817751/060da70b-9dca-4366-bb18-5e8fb2baceb4)

> Unencrypted data from the original MySQL 5.7 database：

![原数据](https://github.com/apache/shardingsphere/assets/56817751/1de2f25f-4643-4911-88c1-b710801faf3d)

> After encryption, the original database becomes ciphertext data
![原库加密](https://github.com/apache/shardingsphere/assets/56817751/3ddb06da-af23-4d76-822d-00e604184d06)

> View decrypted data in proxy
![代理库解密](https://github.com/apache/shardingsphere/assets/56817751/6aec8778-78e7-4cf0-99ba-c7be0dfe65d7)

> Executing a fuzzy query in proxy without finding any results
![模糊查询](https://github.com/apache/shardingsphere/assets/56817751/db355abd-2bcd-4701-9a90-699ec8fbea82)

**Comment by chengxunhuang** [comment]
@strongduanmu Could you please answer that? Thank you

**Comment by strongduanmu** [comment]
Your cipherColumn and likeQueryColumn are configured with the same col1, which is an wrong. They need to use different column storage.
