### ISSUE TITLE
Hopefully, sharding.yaml can be read from nacos

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28592]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Hopefully, sharding.yaml can be read from nacos
### Actual behavior
It's extremely inconvenient to have to pack it in the project
### Reason analyze (If you can)
no
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
no
### Example codes for reproduce this issue (such as a github link).
no

**Comment by zhaojinchao95** [comment]
@Yule-Momoko Hi, are you interested in completing it?

**Comment by Yule-Momoko** [comment]
> @Yule-Momoko您好，您有兴趣完成吗？

yes

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
