### ISSUE TITLE
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=rules for JavaBean=org.apache.shardingsphere.driver.api.yaml.YamlJDBCConfiguration@1a69eb09

### ISSUE THREAD

**Issue by Zelexshow** [apache/shardingsphere#28618]
jdk17
springboot 3.1.4

yaml config file like this below:
///////////////////////////////////////////////
schemaName: test

dataSources:
  db_trans_single:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/db_trans_single?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

rules:
  keyGenerators:
    snowflake:
      type: SNOWFLAKE

props:
  sql-show: true
////////////////////////////////////////////////////////////////
maven details:
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
           <version>5.4.0/version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.33</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.8</version>
        </dependency>

ERROR:
![image](https://github.com/apache/shardingsphere/assets/52685431/51de5fe9-6592-44d5-b921-7ad4b545b0ab)

**Comment by linghengqian** [comment]
> schemaName: test

- The ShardingSphere does not have a top-level Tag for `schemaName`.
- I assume that what you need to configure is the database name of the logical database. The property name is `databaseName` and the default value is `logic_db`.
- Refer to https://shardingsphere.apache.org/document/5.4.0/en/user-manual/shardingsphere-jdbc/yaml-config/ .

**Comment by Zelexshow** [comment]
'databaseName' seems to be duplicated with the property ’dataSources‘， what should I fill this property?

**Comment by linghengqian** [comment]
> 'databaseName' seems to be duplicated with the property ’dataSources‘， what should I fill this property?

- This brings up another question, why do you need to configure schemaName?

**Comment by linghengqian** [comment]
- There is no response from the creator of the issue, so I think there is no point in continuing to open this issue.
