### ISSUE TITLE
Upgrade shardingsphere-jdbc-core-spring-boot-starter to higher version on the maven

### ISSUE THREAD

**Issue by JokaZhao** [apache/shardingsphere#28675]
## Question

My project use `shardingsphere-jdbc-core-spring-boot-starter` and now I will upgrade to `5.3.0`

Search for maven mvnrepository, the boot-starter highest version is `5.2.1`.

Do you need to deploy latest version to maven?

**Comment by zhaojinchao95** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` are removed in `5.3.0`, you can use  ShardingSphereDriver to complete project upgrade.
