### ISSUE TITLE
Compilation source code org. apache. shardingsphere. distsql. parser. autogen does not exist

### ISSUE THREAD

**Issue by chengxunhuang** [apache/shardingsphere#28671]
### Which version of ShardingSphere did you use?
5.4.1-relese
### Actual behavior
Currently, according to the document, Maven 3.8.6 and JDK17 are used, and the root directory is executed: mvn - DSkipITs - DSkipTests install - T1C, with an error reported
`[INFO] shardingsphere-proxy-distribution .................. SKIPPED
[INFO] shardingsphere-proxy-native-distribution ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  44.005 s (Wall Clock)
[INFO] Finished at: 2023-10-08T11:31:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project shardingsphere-parser-distsql-engine: Compilation failure: Compilation failure:
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[20,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[21,86] 程序包org.apache.shardingsphere.distsql.parser.autogen.UtilityDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[22,86] 程序包org.apache.shardingsphere.distsql.parser.autogen.UtilityDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[23,86] 程序包org.apache.shardingsphere.distsql.parser.autogen.UtilityDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[33,59] 找不到符号
[ERROR]   符号: 类 UtilityDistSQLStatementBaseVisitor
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[36,42] 找不到符号
[ERROR]   符号:   类 PreviewSQLContext
[ERROR]   位置: 类 org.apache.shardingsphere.distsql.parser.core.utility.UtilityDistSQLStatementVisitor
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[41,40] 找不到符号
[ERROR]   符号:   类 ParseSQLContext
[ERROR]   位置: 类 org.apache.shardingsphere.distsql.parser.core.utility.UtilityDistSQLStatementVisitor
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLStatementVisitor.java:[46,41] 找不到符号
[ERROR]   符号:   类 FormatSQLContext
[ERROR]   位置: 类 org.apache.shardingsphere.distsql.parser.core.utility.UtilityDistSQLStatementVisitor
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLLexer.java:[21,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLLexer.java:[27,47] 找不到符号
[ERROR]   符号: 类 KernelDistSQLStatementLexer
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLParser.java:[22,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLParser.java:[30,49] 找不到符号
[ERROR]   符号: 类 UtilityDistSQLStatementParser
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLParser.java:[22,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLParser.java:[30,48] 找不到符号
[ERROR]   符号: 类 KernelDistSQLStatementParser
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLLexer.java:[21,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/utility/UtilityDistSQLLexer.java:[27,48] 找不到符号
[ERROR]   符号: 类 UtilityDistSQLStatementLexer
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[21,56] 程序包org.apache.shardingsphere.distsql.parser.autogen不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[22,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[23,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[24,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[25,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[26,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[27,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[28,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[29,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[30,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[31,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[32,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[33,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[34,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[35,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[36,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[37,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[38,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[39,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[40,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在
[ERROR] /D:/code/data/shardingsphere-5.4.1-release/parser/distsql/engine/src/main/java/org/apache/shardingsphere/distsql/parser/core/kernel/KernelDistSQLStatementVisitor.java:[41,85] 程序包org.apache.shardingsphere.distsql.parser.autogen.KernelDistSQLStatementParser不存在`

**Comment by linghengqian** [comment]
- Please give the output of `java --version`.  This doesn't look like the output of JDK11-JDK21.

**Comment by Hvision** [comment]
the same problem that i use jdk1.8 and  mvn 3.9.4 .
![image](https://github.com/apache/shardingsphere/assets/24364787/f804d8fc-9e68-43aa-97f5-2f3cc861c228)

**Comment by Hvision** [comment]
@linghengqian  what should i do? There is no corresponding file automatically generated in the autogen folder.

**Comment by Hvision** [comment]
@chengxunhuang Have you solved this problem?

**Comment by linghengqian** [comment]
> @linghengqian  what should i do? There is no corresponding file automatically generated in the autogen folder.

- You need to use jdk11-jdk21 to compile the project, and set the language level of the project to JDK8 in the IDE.  For example you can switch to `21.0.1-graalce` via `sdkman!`.  

- On the CI side of shardingsphere, we compile shardingsphere products through JDK11 and execute unit tests under jdk8.

**Comment by Hvision** [comment]
it work, thanks.

> > @linghengqian  what should i do? There is no corresponding file automatically generated in the autogen folder.
> 
> * You need to use jdk11-jdk21 to compile the project, and set the language level of the project to JDK8 in the IDE.  For example you can switch to `21.0.1-graalce` via `sdkman!`.
> * On the CI side of shardingsphere, we compile shardingsphere binary through JDK11 and execute unit tests under jdk8.

it work, thanks.

**Comment by strongduanmu** [comment]
Since this question has been answered, I will close the issue.

**Comment by miaobainian36** [comment]
it work for me using jdk17.04 and lang level 8!
