### ISSUE TITLE
Add test cases for RuleMetaData.getInUsedStorageUnitNameAndRulesMap()

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#28681]

**Comment by Sakshi-75** [comment]
Hi @terrymanu , can I work on this?

**Comment by strongduanmu** [comment]
@Sakshi-75 Welcome, I will assign this issue to you.

**Comment by Sakshi-75** [comment]
Hi @terrymanu @strongduanmu ,
I've added some unit tests for the method and raised a PR so you can review the changes once and provide your feedbacks if any. 
Thanks!

**Comment by traitsisgiorgos** [comment]
is the issue still open?

**Comment by strongduanmu** [comment]
@traitsisgiorgos The code coverage is 34% now, you can continue to submit PR to improve the unit test.

**Comment by traitsisgiorgos** [comment]
I found another issue to work on so you are free to assign it to someone else. thank you!

**Comment by strongduanmu** [comment]
Hi @Sakshi-75, do you want to finish this issue?
