### ISSUE TITLE
How to get the DataSource   in  ShardingSphere-jdbc 5.3.2?

### ISSUE THREAD

**Issue by StarHuzy** [apache/shardingsphere#28705]
How to obtain the DataSource object when adjusting the configuration reading of the Driver to the SPI interface in ShardingSphere-jdbc 5.3.2 ？
I want to refresh the table rule `actualDataNodes`  by obtaining the dataSource ！

![image](https://github.com/apache/shardingsphere/assets/42610282/efd7881f-cd51-42ff-8a81-e8ad54acc6ec)

**Comment by RaigorJiang** [comment]
@StarHuzy 
This is because the life cycle of your custom algorithm is not managed by spring, and beans cannot be injected into it.

You can try to actively obtain the bean through other methods, such as `ApplicationContext `

**Comment by fanzhiyi0601** [comment]
After the version 5.3.0, shardingSphereDataSource has been removed. So you need to use YamlShardingSphereDataSourceFactory to create data source.

**Comment by RaigorJiang** [comment]
> After the version 5.3.0, shardingSphereDataSource has been removed. So you need to use YamlShardingSphereDataSourceFactory to create data source.

In fact, `ShardingSphereDataSource` still exists, `YamlShardingSphereDataSourceFactory` is just a factory class for building `ShardingSphereDataSource`
