### ISSUE TITLE
How to manage multiple sharding instances

### ISSUE THREAD

**Issue by zy1263188600** [apache/shardingsphere#28714]
I currently have a user db and a busi db
They have completely different database rules
What should I do？
Currently, I am using shardingsphere-jdbc-core-spring-boot-starter as the user db
busi db directly read the yml file for initialization (YamlShardingSphereDataSourceFactory.createDataSource())
But this configuration management is not convenient

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated, please try new version and use ShardingSphere Driver.
