### ISSUE TITLE
Snakeyaml has a high version conflict, and now relies on version 1.33 to have vulnerabilities.

### ISSUE THREAD

**Issue by tuwh** [apache/shardingsphere#28717]
### Which version of ShardingSphere did you use?

5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
The dependent plug-in snakeyaml version is 1.33, which is vulnerable. The component version in my project is 2.0. However, the startup will fail due to class conflicts. Will the dependent snakeyaml components be considered for upgrade?

### Actual behavior

this is the exception stack

Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42) ~[shardingsphere-infra-util-5.4.0.jar:5.4.0]

### Reason analyze (If you can)

The latest version of snakeyaml removes the no-argument constructor of the org.yaml.snakeyaml.representer.Representer class

**Comment by RaigorJiang** [comment]
Duplicated with #28233, #24636, #28067
