### ISSUE TITLE
when I want to insert sql use expression such as "#{giveTime} + unix_timestamp()", it makr the sql does not work.

### ISSUE THREAD

**Issue by dongfangding** [apache/shardingsphere#28710]
### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
I have the following SQL, I'm sure the parameters is normal, but it does not work properly
```xml
<insert id="givingUserBeautifulId">
    insert into user_beautiful_id(uid, beautiful_id, ctime, expire_time)
    values (#{uid}, #{beautifulId}, unix_timestamp(), #{giveTime} + unix_timestamp())
</insert>
```
in java 
```java
    int givingUserBeautifulId(@Param("uid") Long uid, @Param("beautifulId") Long beautifulId,
            @Param("giveTime") Long giveTime);
```

### Actual behavior
I will receive this error: 
No value specified for parameter 3
### Reason analyze (If you can)
This is the data I have collected as a reference
https://github.com/dongfangding/my-pic/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20231010230218.png

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
