### ISSUE TITLE
Why does the latest version not have the Orchestration module? I remember that 4.0.1 has it.

### ISSUE THREAD

**Issue by chenws1012** [apache/shardingsphere#28715]
## Database Orchestration
Dynamic Configuration
Orchestration & Governance
Data Encryption
Tracing & Observability
Elastic scaling out (Planing)

**Comment by strongduanmu** [comment]
Currently, the Orchestration module is refactor to mode module. For more details, please refer to the documentation: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/
