### ISSUE TITLE
Shardingsphere-proxy + seate update database exception Cause: java.sql.SQLException: Internal error: io.seata.core.exception.RmTransactionException: branch register failed

### ISSUE THREAD

**Issue by asdf112255** [apache/shardingsphere#28721]
## Question
i use shading-proxy +seate  with springboot app,
query data is right,
when i update database (insert/update/delete) i got exception below:
### Error updating database. Cause: java.sql.SQLException: Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454713603026944, errMsg: TransactionException[branch register request failed. xid=172.28.201.95:30095:455454713603026944, msg=Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454714349613056, errMsg: TransactionException[Could not found global transaction xid = 172.28.201.95:30095:455454714349613056, may be has finished.] ] ### The error may exist in jnpf/engine/mapper/FlowTaskMapper.java (best guess) ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: DELETE FROM flow_task WHERE (F_ID IN (?)) ### Cause: java.sql.SQLException: Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454713603026944, errMsg: TransactionException[branch register request failed. xid=172.28.201.95:30095:455454713603026944, msg=Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454714349613056, errMsg: TransactionException[Could not found global transaction xid = 172.28.201.95:30095:455454714349613056, may be has finished.] ] ; uncategorized SQLException; SQL state [HY000]; error code [1815]; Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454713603026944, errMsg: TransactionException[branch register request failed. xid=172.28.201.95:30095:455454713603026944, msg=Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454714349613056, errMsg: TransactionException[Could not found global transaction xid = 172.28.201.95:30095:455454714349613056, may be has finished.] ] ; nested exception is java.sql.SQLException: Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454713603026944, errMsg: TransactionException[branch register request failed. xid=172.28.201.95:30095:455454713603026944, msg=Internal error: io.seata.core.exception.RmTransactionException: branch register failed, xid: 172.28.201.95:30095:455454714349613056, errMsg: TransactionException[Could not found global transaction xid = 172.28.201.95:30095:455454714349613056, may be has finished.] ]

do i need any another configuration?
shardingsphere   server.conf:
transaction:
  defaultType: BASE
  providerType: Seata
seata.conf:
client {
    application.id = risk
    transaction.service.group = my_test_tx_group
}
any suggestion is appreciate!:)

**Comment by linghengqian** [comment]
> i use shading-proxy +seate with springboot app,
- Are you using `io.seata.spring.annotation.GlobalTransactional`? I suspect this has been declared in #30146 . If you are using `io.seata:seata-spring-boot-starter`, please turn off its automatic proxy data source function through the Spring Boot configuration file.

**Comment by linghengqian** [comment]
- Closing this issue because it cannot be reproduced.
