### ISSUE TITLE
document is so bad

### ISSUE THREAD

**Issue by metropolis-long** [apache/shardingsphere#28751]
I need a complete configuration file, not a partial one，
example：
mode (?): # 不配置则默认单机模式
  type: # 运行模式类型。可选配置：Standalone、Cluster
  repository (?): # 持久化仓库配置

What is the prefix for this configuration？？？？？

**Comment by strongduanmu** [comment]
Can you read the document carefully? - https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/#sample

**Comment by strongduanmu** [comment]
Since this question is meaningless, I will close it.
