### ISSUE TITLE
Whether jndi is supported in version 5.4.0?

### ISSUE THREAD

**Issue by mylife1984** [apache/shardingsphere#28769]
## Question
Whether jndi is supported in version 5.4.0?

How do I use jndi to connect to a database in springboot 2.7?

**Comment by zhaojinchao95** [comment]
I think it supported in version 5.4.0, you can try it. You can refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

**Comment by mylife1984** [comment]
> I think it supported in version 5.4.0, you can try it. You can refer to https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

Yes, that's what I did, but when configuring the data source, there was an exception entering jndi-name

**Comment by zhaojinchao95** [comment]
Your configuration file is too vague. Please format it and provide all the information.

**Comment by mylife1984** [comment]
> Your configuration file is too vague. Please format it and provide all the information.🔄  ❓

**Comment by mylife1984** [comment]
> > Your configuration file is too vague. Please format it and provide all the information.🔄  ❓
> 
> ## application-dev.yml
> ```
> server:
>   servlet:
>     context-path: /demo
> spring:
>   datasource:
>     driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
>     url: jdbc:shardingsphere:classpath:config-sharding.yml
> ```
> 
> ## config-sharding.yml
> ```
> mode:
>   type: Standalone
>   repository:
>     type: JDBC
> dataSources:
>   master:
>     jndi-name: jdbc/kims
>   log:
>     jndi-name: jdbc/kimslog
> rules:
>   - !SHARDING
>     tables:
>       t_kims:
>         actualDataNodes: master.t_user_$->{0..1}
>         tableStrategy:
>           standard:
>             shardingColumn: user_id
>             shardingAlgorithmName: user_table_inline
>     shardingAlgorithms:
>           user_table_inline:
>             type: INLINE
>             props:
>               algorithm-expression: t_user_$->{user_id % 2}
> props:
>   sql-show: true
> ```

**Comment by linghengqian** [comment]
- @mylife1984 What is `dataSources.master.jndi-name`? This configuration item never existed for ShardingSphere.

- @zhaojinchao95 I don't think the master branch of ShardingSphere now supports JNDI because there are no function calls `javax.naming.Context#lookup` at all.

**Comment by mylife1984** [comment]
> * @mylife1984 What is `dataSources.master.jndi-name`? This configuration item never existed for ShardingSphere.
> * @zhaojinchao95 I don't think the master branch of ShardingSphere now supports JNDI because there are no function calls `javax.naming.Context#lookup` at all.

In version 5.2.1, you can see the configuration of jndi-name, after that you can't see it, so I want to know how to configure it

https://shardingsphere.apache.org/document/5.2.1/cn/user-manual/shardingsphere-jdbc/spring-boot-starter/data-source/#%E4%BD%BF%E7%94%A8-jndi-%E6%95%B0%E6%8D%AE%E6%BA%90-2

**Comment by linghengqian** [comment]
@mylife1984 

- Hi, this is because this is not what ShardingSphere JDBC Core does.  ShardingSphere's Spring Boot Starter can use JNDI because it uses Spring's `org.springframework.jndi.JndiObjectFactoryBean`, refer to https://github.com/apache/shardingsphere/pull/2308 .

- With ShardingSphere removing the Spring Boot Starter now, using JNDI is currently not possible and requires writing a new PR.

**Comment by mylife1984** [comment]
> @mylife1984
> 
> * Hi, this is because this is not what ShardingSphere JDBC Core does.  ShardingSphere's Spring Boot Starter can use JNDI because it uses Spring's `org.springframework.jndi.JndiObjectFactoryBean`, refer to [Try to support JNDI Datasource for sharding-jdbc-spring-boot-starter #2308](https://github.com/apache/shardingsphere/pull/2308) .嗨，这是因为这不是ShardingSphere JDBC Core所做的。ShardingSphere 的 Spring Boot Starter 可以使用 JNDI，因为它使用的是 Spring 的 `org.springframework.jndi.JndiObjectFactoryBean` ，请参阅 尝试支持 JNDI 数据源的 sharding-jdbc-spring-boot-starter #2308 。
> * With ShardingSphere removing the Spring Boot Starter now, using JNDI is currently not possible and requires writing a new PR.随着 ShardingSphere 现在删除了 Spring Boot Starter，目前无法使用 JNDI，需要编写新的 PR。

Thank you!
