### ISSUE TITLE
Caused by: org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `MY_TABLE` does not exist.

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28848]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Can query normally
### Actual behavior
The prompt table does not exist, but I confirm that the table does exist and can be executed in 5.4.0

Caused by: org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `MY_TABLE` does not exist.

### Reason analyze (If you can)
Only read and write separation is configured：
dataSources:
write-ds-1:
dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
driverClassName: com.mysql.cj.jdbc.Driver
url: 'jdbc:mysql://writexxxx:3306/test?serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true'
username: xxx
password: xxx
write-ds-1-read:
dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
driverClassName: com.mysql.cj.jdbc.Driver
url: 'jdbc:mysql://readxxx:3306/test?serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true'
username: xxx
password: xxx

rules:

!READWRITE_SPLITTING
dataSources:
ds1:
writeDataSourceName: write-ds-1
readDataSourceNames:
- write-ds-1-read
transactionalReadQueryStrategy: PRIMARY
loadBalancerName: round_robin

loadBalancers:
round_robin:
type: ROUND_ROBIN
props:
sql-show: true

**Comment by Keanhua** [comment]
i occured the same exception

**Comment by zhaojinchao95** [comment]
Please add single table configuration, refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

**Comment by Yule-Momoko** [comment]
> Please add single table configuration, refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

ok

**Comment by fanzhiyi0601** [comment]
> Please add single table configuration, refer to : https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

It doesn't work well in Oracle.
