### ISSUE TITLE
When I used paging query, the "java.lang.String cannot be cast to java.lang.Integer" exception occurred.

### ISSUE THREAD

**Issue by yukunqi** [apache/shardingsphere#28856]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

Paginated SQL statements can be executed normally

### Actual behavior
exception java.lang.String cannot be cast to java.lang.Integer

### Reason analyze (If you can)
1. This is the end point where the exception occurs
https://github.com/apache/shardingsphere/blob/024c4d33b5098a644346c079104247ce614e5078/infra/binder/src/main/java/org/apache/shardingsphere/infra/binder/segment/select/pagination/PaginationContext.java#L57
2. The ParameterIndex is parsed from the ShardingSphereSQLParserEngine class in the constructor of ShardingSpherePreparedStatement.
https://github.com/apache/shardingsphere/blob/024c4d33b5098a644346c079104247ce614e5078/jdbc/core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/statement/ShardingSpherePreparedStatement.java#L200C34-L201

3.However, ShardingSphereSQLParserEngine did not correctly parse sqlStatment, which ultimately led to the aforementioned exception.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

You only need to execute the unit test for this SQL and perform SQL parsing to see the results of the parsing.

SQL:
```
SELECT *
FROM T1
WHERE column_1 = ?
	AND column_time BETWEEN ? AND ?
	AND column_2 <> '4'
	AND column_3 = ?
	AND column_4 IN (
		WITH RECURSIVE cte_connect_by AS (
				SELECT t2.*
				FROM T2 t2
				WHERE column_5 = ?
				UNION ALL
				SELECT t2.*
				FROM cte_connect_by r
				INNER JOIN T2 t2 
				ON t2.column_6 = r.column_7
			)
		SELECT 
		column_8
		FROM cte_connect_by
	)
ORDER BY column_9 DESC
LIMIT ?, ?
```

### Example codes for reproduce this issue (such as a github link).

```
@Test
    public void testParseLimitSegment() {
        String sql = "SELECT *\n" +
                "FROM T1\n" +
                "WHERE column_1 = ?\n" +
                "\tAND column_time BETWEEN ? AND ?\n" +
                "\tAND column_2 <> '4'\n" +
                "\tAND column_3 = ?\n" +
                "\tAND column_4 IN (\n" +
                "\t\tWITH RECURSIVE cte_connect_by AS (\n" +
                "\t\t\t\tSELECT t2.*\n" +
                "\t\t\t\tFROM T2 t2\n" +
                "\t\t\t\tWHERE column_5 = ?\n" +
                "\t\t\t\tUNION ALL\n" +
                "\t\t\t\tSELECT t2.*\n" +
                "\t\t\t\tFROM cte_connect_by r\n" +
                "\t\t\t\tINNER JOIN T2 t2 \n" +
                "\t\t\t\tON t2.column_6 = r.column_7\n" +
                "\t\t\t)\n" +
                "\t\tSELECT \n" +
                "\t\tcolumn_8\n" +
                "\t\tFROM cte_connect_by\n" +
                "\t)\n" +
                "ORDER BY column_9 DESC\n" +
                "LIMIT ?, ?";
        // Add your test code here
        CacheOption sqlStatementCacheOption = new CacheOption(10,10);
        CacheOption parseTreeCacheOption = new CacheOption(10,10);
        ShardingSphereSQLParserEngine parser = new ShardingSphereSQLParserEngine("MySQL",sqlStatementCacheOption,sqlStatementCacheOption,true);
        MySQLSelectStatement mySQLSelectStatement = (MySQLSelectStatement) parser.parse(sql, false);
        LimitSegment limitSegment = mySQLSelectStatement.getLimit().orElseThrow(RuntimeException::new);
        ParameterMarkerLimitValueSegment parameterMarkerLimitValueSegment = (ParameterMarkerLimitValueSegment) limitSegment.getOffset().orElseThrow(RuntimeException::new);
        int parameterIndex = parameterMarkerLimitValueSegment.getParameterIndex();
        Assert.equals(5,parameterIndex);
    }
```

<img width="1316" alt="截屏2023-10-28 23 59 53" src="https://github.com/apache/shardingsphere/assets/21964102/85712361-d63b-4cae-8c52-ecc7dc4af085">

**Comment by zihaoAK47** [comment]
Hi, it is recommended to provide the executed SQL statements or try using a new version.

**Comment by yukunqi** [comment]
Yes, I have this intention. I used SQL on the intranet and will add relevant information as soon as possible.

**Comment by yukunqi** [comment]
@zihaoAK47 hi i updated the comment above and add relevant executed SQL and also write a unit test to reproduce this exception

**Comment by zihaoAK47** [comment]
@yukunqi Hi, thank you for providing detailed information. The section containing CTE SQL statements does not support parsing in version 5.3.1.
This issue is the same as #28474, and the current master branch has resolved the parsing of MySQL cte SQL.

**Comment by yukunqi** [comment]
thanks @zihaoAK47 Looking forward to the release of new versions

**Comment by WilliamHWM** [comment]
There are same question in using union all sql and mybatis plus paging ,how to fix it?
