### ISSUE TITLE
How to use encryption desensitization function alone

### ISSUE THREAD

**Issue by zoulejiu** [apache/shardingsphere#28861]
There are hundreds of tables in my database, and I only need to encrypt the fields of a few tables. I find that it keeps prompting me that Table or view `xx` does not exist. This is a problem only if the tables are not configured for encryption.
Do I need to configure each of my other tables that do not need to be encrypted?
I saw the website mentioned the default data source, but the 5.4.1 version I am using no longer has this option.

**Comment by strongduanmu** [comment]
You need to use following config:

```yaml
- !SINGLE
  tables:
    - "*.*"
```
The default data source can only be used in the sharding feature.

**Comment by zoulejiu** [comment]
Thanks, it worked
