### ISSUE TITLE
Oracle COUNT OVER was not properly parsed

### ISSUE THREAD

**Issue by yanjisc** [apache/shardingsphere#28871]
### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC

### Expected behavior
Condition of COUNT OVER should be properly parsed.

### Actual behavior

![image](https://github.com/apache/shardingsphere/assets/8338732/4597eede-a7b7-40f2-a711-c0c45016b0d8)

**Comment by yanjisc** [comment]
![image](https://github.com/apache/shardingsphere/assets/8338732/073b24de-dd97-40cc-b8fb-beaac5fbcd3c)

**Comment by strongduanmu** [comment]
Hi @yanjisc, thank you for your feedback. Can you help fix this bug?

**Comment by yanjisc** [comment]
> Hi @yanjisc, thank you for your feedback. Can you help fix this bug?

ANTLR is used here and I can't fix it.

**Comment by yanjisc** [comment]
@strongduanmu 
ANTLR is used here and I can't fix it.

**Comment by yanjisc** [comment]
TO_CHAR(WM_CONCAT(DISTINCTJZG.XM)OVER' at line 1, position 474, near [@143,474:477='OVER',<774>,1:474]

**Comment by strongduanmu** [comment]
> @strongduanmu ANTLR is used here and I can't fix it.

Let's see if anyone in the community is interested in this issue

**Comment by zihaoAK47** [comment]
Hi please assign it to me thank you.

**Comment by strongduanmu** [comment]
@zihaoAK47 Welcome.

**Comment by strongduanmu** [comment]
Hi @yanjisc, can you help test this case with master branch? @zihaoAK47 submitted a PR that already supports this sql.
