### ISSUE TITLE
Hacktoberfest'23

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#28875]
Hi community, this year's hacktoberfest is currently running but in the readme of the repository I have seen that it is not updated after last year's fest. The line denotes there Hacktoberfest'22 also in the issues link connected to it, there is no open and labelled issue. Attaching the screenshot for reference. 
![image](https://github.com/apache/shardingsphere/assets/64654203/56487157-bb31-4134-8100-6cb95a4d4dd0)

**Comment by RaigorJiang** [comment]
@Swastyy 
Yes, maybe we should update the `README` and remove outdated information.
