### ISSUE TITLE
Can not support DML operation with multiple tables

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28873]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
supported
### Actual behavior
Version 5.4.0 is supported, but version 5.4.1 is not，Why is it getting weaker as you upgrade
### Reason analyze (If you can)
no
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
no
### Example codes for reproduce this issue (such as a github link).
no

**Comment by RaigorJiang** [comment]
Hi @Yule-Momoko ,
What are the configuration, SQL statements and actual behavior? Is there any error message?
