### ISSUE TITLE
A large number of 'org.apache.shardingsphere.infra.executor.sql.process.ProcessRegistry#processes' causing memory leaks

### ISSUE THREAD

**Issue by youn9yon9** [apache/shardingsphere#28884]
Which version of ShardingSphere did you use?

5.4.0

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

Expected behavior

When the query is finished, 'org.apache.shardingsphere.infra.executor.sql.process.ProcessRegistry#processes' should be removed.

Actual behavior

My system processes 10 million order callbacks every day, and when executing queries, a large number of 'processes' are stored, leading to frequent full garbage collections.

System monitoring：
<img width="562" alt="image" src="https://github.com/apache/shardingsphere/assets/59075697/a3ebf722-77e5-44d3-8e40-f41eefb7c902">

<img width="554" alt="image" src="https://github.com/apache/shardingsphere/assets/59075697/23195412-bf18-4a8b-a995-7769e2f03787">

heap dump：

![企业微信截图_3e95de44-c14b-4cba-a545-9a8a93639400](https://github.com/apache/shardingsphere/assets/59075697/c5b591d4-2b4e-4046-9f7c-e86868c41c0b)

**Comment by strongduanmu** [comment]
Hi @youn9yon9, this bug has been fixed in 5.4.1, can you try this version?

**Comment by youn9yon9** [comment]
OK
