### ISSUE TITLE
Shardingsphere ProcessRegistry Memory leak in Eclipse mat

### ISSUE THREAD

**Issue by sadtrain** [apache/shardingsphere#28897]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
no memory leak
### Actual behavior
![image](https://github.com/apache/shardingsphere/assets/38108737/6d38ae82-b48f-493a-9265-c60f5fd335c7)

### Reason analyze (If you can)
We run sql insert in a loop,which can make 100 results inserted into mysql per second.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
20 minutes after the application started,we can see many instances of org.apache.shardingsphere.infra.executor.sql.process.Process.
![image](https://github.com/apache/shardingsphere/assets/38108737/b24c75ba-adff-4fba-b590-b2fb1dc5d61c)

**Comment by strongduanmu** [comment]
This bug has been fixed in 5.4.1.
