### ISSUE TITLE
IntervalShardingAlgorithm unsupport gorm framework

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#28909]
I use IntervalShardingAlgorithm and the datetime-pattern is ''yyyy-MM-dd HH:mm:ss''.

If the time passed when the user requests the Proxy is "2023-01-01 12:00:00", there will be no problem. If the time passed is "2023-01-01", a "String index out of range: 19" exception will occur.

Why "2023-01-01" is passed instead of "2023-01-01 00:00:00" is because the gorm framework will remove the time and only keep the date when it finds that the time is "00:00:00". I think this is reasonable, and I hope Proxy can also support it, because MySQL also supports such delivery.

<img width="1305" alt="企业微信截图_b3ac7dc1-7c43-45d3-be06-4701bf2b0085" src="https://github.com/apache/shardingsphere/assets/26433395/7de53ed3-343c-4686-a567-aebcabf18cd3">

My solution is as follows, I don’t know if it is reasonable?
` 
private LocalDateTime parseLocalDateTime(final Comparable<?> endpoint) {
        try {
            return LocalDateTime.parse(getDateTimeText(endpoint), dateTimeFormatter);
        } catch (final DateTimeParseException ex) {
            LocalDate date = LocalDate.parse(getDateTimeText(endpoint), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            return LocalDateTime.of(date, LocalTime.MIDNIGHT);
        }
    }
`

**Comment by RaigorJiang** [comment]
Hi @natehuangting , thanks for your advice.
ShardingSphere is not only used in MySQL scenarios. If you want to promote this improvement, please also investigate the compatibility of common databases such as PostgreSQL and Oracle.

**Comment by linghengqian** [comment]
- The initial logic for this function came from shardingsphere 5.0.0-beta and has since evolved simply to align with the original design. The unit tests I first covered in #29967 locked this behavior, which I considered a bug.

**Comment by linghengqian** [comment]
> My solution is as follows, I don’t know if it is reasonable? 

- @natehuangting Hardly defining `DateTimeFormatter.ofPattern("yyyy-MM-dd")` is an unreasonable thing. If the incoming string is `20240204` like `yyyyMMdd`, it will lead to further confusion. I prefer using substrings of `datetime-pattern` in #29975.

**Comment by natehuangting** [comment]
你可以自定义算法的，这个看官方觉得通用不通用愿不愿意接受，我现在已经不写java，这是之前公司遗留的问题。发自我的 iPhone在 2024年2月4日，01:04，Ling Hengqian ***@***.***> 写道：﻿

My solution is as follows, I don’t know if it is reasonable?


@natehuangting Hardly defining DateTimeFormatter.ofPattern("yyyy-MM-dd") is an unreasonable thing. If the incoming string is 20240204 like yyyyMMdd, it will lead to further confusion. I prefer using substrings of datetime-pattern in #29975.
