### ISSUE TITLE
sharding-jdbc 5.4.1 spring boot is complete before the data source is initialized. How do I initialize the data source with spring boot

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28905]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
sharding-jdbc 5.4.1 spring boot is complete before the data source is initialized. How do I initialize the data source with spring boot

**Comment by linghengqian** [comment]
> spring boot is complete before the data source is initialized

- Please give further explanation. What is `complete`?

**Comment by Yule-Momoko** [comment]
> > spring boot在数据源初始化之前就完成了
> 
> * 请进一步解释。什么是`complete`？

spring boot starts the data source before initializing it

**Comment by Yule-Momoko** [comment]
> > spring boot在数据源初始化之前就完成了
> 
> * 请进一步解释。什么是`complete`？

That is, the data source is initialized last instead of starting with springboot

**Comment by linghengqian** [comment]
- Can you put a git that contains minimal reproducible unit tests?  You can use h2database or testcontainers as data source.  This appears to be a configuration issue, as the ShardingSphere DataSource only lets the downstream decide when to initialize.

**Comment by Yule-Momoko** [comment]
> * Can you put a git that contains minimal reproducible unit tests?  You can use h2database or testcontainers as data source.  This appears to be a configuration issue, as the ShardingSphere DataSource only lets the downstream decide when to initialize.

Can you give me a 5.4.1 configuration demo

**Comment by linghengqian** [comment]
- You can experiment with ShardingSphere's example module based on the content at https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example-generator/README.md .  

- Or refer to the closed issue with example git.  

- If there are any questions, please reply.

**Comment by Yule-Momoko** [comment]
Why is druid always initialized last

**Comment by linghengqian** [comment]
> Why is druid always initialized last

- The information you provided is still incomplete. What does `last` mean? The instantiation of the database connection pool is reproducible with a stack.

**Comment by linghengqian** [comment]
- Since no one responded, there is no point in continuing to open this issue.
