### ISSUE TITLE
Data source initialization time problem

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#28903]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Why is the data source initialized after the spring-boot boot is complete

**Comment by linghengqian** [comment]
> Why is the data source initialized after the spring-boot boot is complete.

- Please give further explanation. What is `the spring-boot boot is complete`?

**Comment by Yule-Momoko** [comment]
> > 为什么spring-boot启动完成后才初始化数据源。
> 
> * 请进一步解释。什么是`the spring-boot boot is complete`？

That is, the data source is initialized last instead of starting with springboot

**Comment by linghengqian** [comment]
- Can you put a git that contains minimal reproducible unit tests?  You can use h2database or testcontainers as data source.  This appears to be a configuration issue, as the ShardingSphere DataSource only lets the downstream decide when to initialize.

**Comment by linghengqian** [comment]
- There is no response from the creator of the issue, so I think there is no point in continuing to open this issue.
