### ISSUE TITLE
NPE occurs when execute DML without use database

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28918]
### Which version of ShardingSphere did you use?
master dd44eb00aba6f63efdba6feb8ddb5845fcc5152a

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
prompt `no database selected`

### Actual behavior
```sql
mysql> INSERT INTO t_order (order_id, user_id, status) VALUES 
    -> (1,1,'OK213521631237232');
ERROR 30000 (HY000): Unknown exception: Cannot invoke "String.toLowerCase()" because "databaseName" is null
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Start proxy without any configuration file
2. Execute any DML statement

**Comment by YaoFly** [comment]
I've already fixed it and submitted PR , PTAL

**Comment by RaigorJiang** [comment]
> I've already fixed it and submitted PR , PTAL

@YaoFly Merged, thank you!
