### ISSUE TITLE
支持TiDB吗

### ISSUE THREAD

**Issue by runningyz** [apache/shardingsphere#28929]
sharding sphere支持TiDB了吗？ 
使用场景：一个table数为百级别，库里数据总行数为几十亿行的mysql库，想迁移到TiDB。在迁移过程中，想保证数据强一致性，通过双写来实现，希望使用sharding sphere的XA事务功能，同时管理源库mysql和目标库TiDB

**Comment by strongduanmu** [comment]
Hi @runningyz, can you translate this issue to English?

**Comment by strongduanmu** [comment]
Currently, ShardingSphere does not support this feature. In the commercial version of SphereEx enhancements, heterogeneous database dual write and XA guarantees are available, so feel free to contact me if you are interested.
