### ISSUE TITLE
客户端连接sharding-proxy 5.4.0,执行联表更新操作，出现：[44000][20709] Can not find encrypt table: `intermediary_product_pass`.

### ISSUE THREAD

**Issue by yuyongxing** [apache/shardingsphere#28956]
执行的sql语句：
update intermediary_product_pass ipp,intermediary_product a2
set ipp.on_shelf_bool=0
where ipp.flag = 0
  and a2.flag = 0
  and ipp.product_id = a2.id；

**Comment by yuyongxing** [comment]
两张表的区别是：intermediary_product_pass未使用字段加密，intermediary_product 表中存在一个字段使用SM4加密，就出现这个错误。请问下是否有解决方案。

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
