### ISSUE TITLE
Executing 'drop streaming jobId' returned success, but the actual physical datasource replication slot was not deleted.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#28960]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.1-SNAPSHOT
Commit ID: dirty-e406a153c595a315fcf9cd0950a7eb1e206eaa7c
Commit Message: Support load unique key for H2 #28035 (#28154)
Branch: hw-cdc
Build time: 2022-12-12T03:18:10+0800
```
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy

### Expected behavior
Executing 'drop streaming jobId' returned success, and the actual physical datasource replication slot was deleted.
### Actual behavior
Executing 'drop streaming jobId' returned success, but the actual physical datasource replication slot was not deleted.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
drop streaming jobId;

![PKB}`9B)1 6A8G27M6SGE1T](https://github.com/apache/shardingsphere/assets/97432411/39fa76e9-d8fd-4169-9554-8855bcfa6dcc)
![H WF@$A(I8Z(T_BB383C77H](https://github.com/apache/shardingsphere/assets/97432411/3cb345f1-e9cd-443b-be46-3d4237653323)

**Comment by azexcy** [comment]
It's already fixed at #28890. Thank you for your feedback.
