### ISSUE TITLE
Add a new DistSQL to show implementations of SPI.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28984]
### Is your feature request related to a problem?
No.

### Describe the feature you would like.
When users use DistSQL to create sharding table rules, they should know in advance which algorithms are currently available (the algorithm type needs to be specified in [RDL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule/)), and we should provide a syntax to show what optional SPI implementations are available.

Task:
1. Design DistSQL syntax, which may belong to Queryable RAL
2. Implement the syntax, show the SPI name, type, and class path of the implementation class

**Comment by dongzl** [comment]
Hi @RaigorJiang ,  If this task is not urgent, I would like to try it.

**Comment by RaigorJiang** [comment]
Hi @dongzl , Thanks for your interest!
I hope this DistSQL will be available in the next version, maybe we have 30~40 days, is that okay?

**Comment by dongzl** [comment]
> Hi @dongzl , Thanks for your interest! I hope this DistSQL will be available in the next version, maybe we have 30~40 days, is that okay?

It's OK.

**Comment by dongzl** [comment]
@RaigorJiang , I design the `DistSQL`, The effect is as follow, It's OK?

```
mysql> mysql> SHOW SHARDING ALGORITHM INFO;
+-------------------------------------+----------------+-------------------------------------------------------------------------------------------------+
| name                                | type           | class_path                                                                                      |
+-------------------------------------+----------------+-------------------------------------------------------------------------------------------------+
| ModShardingAlgorithm                | MOD            | org.apache.shardingsphere.sharding.algorithm.sharding.mod.ModShardingAlgorithm                  |
| HashModShardingAlgorithm            | HASH_MOD       | org.apache.shardingsphere.sharding.algorithm.sharding.mod.HashModShardingAlgorithm              |
| VolumeBasedRangeShardingAlgorithm   | VOLUME_RANGE   | org.apache.shardingsphere.sharding.algorithm.sharding.range.VolumeBasedRangeShardingAlgorithm   |
| BoundaryBasedRangeShardingAlgorithm | BOUNDARY_RANGE | org.apache.shardingsphere.sharding.algorithm.sharding.range.BoundaryBasedRangeShardingAlgorithm |
| AutoIntervalShardingAlgorithm       | AUTO_INTERVAL  | org.apache.shardingsphere.sharding.algorithm.sharding.datetime.AutoIntervalShardingAlgorithm    |
| IntervalShardingAlgorithm           | INTERVAL       | org.apache.shardingsphere.sharding.algorithm.sharding.datetime.IntervalShardingAlgorithm        |
| ClassBasedShardingAlgorithm         | CLASS_BASED    | org.apache.shardingsphere.sharding.algorithm.sharding.classbased.ClassBasedShardingAlgorithm    |
| InlineShardingAlgorithm             | INLINE         | org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm            |
| ComplexInlineShardingAlgorithm      | COMPLEX_INLINE | org.apache.shardingsphere.sharding.algorithm.sharding.inline.ComplexInlineShardingAlgorithm     |
| HintInlineShardingAlgorithm         | HINT_INLINE    | org.apache.shardingsphere.sharding.algorithm.sharding.hint.HintInlineShardingAlgorithm          |
+-------------------------------------+----------------+-------------------------------------------------------------------------------------------------+
10 rows in set (0.01 sec)
```

**Comment by RaigorJiang** [comment]
Hi @dongzl ,
The output you showed works very well, but such input means that we need to provide a syntax for each SPI, which will be a lot of work.

For example, we also have `KeyGenerateAlgorithm`, `XATransactionManagerProvider`, `ReadQueryLoadBalanceAlgorithm` and many other SPIs.

Personally, can we first provide a basic syntax that can be applied to all SPIs, which means that the input needs to contain the full class path of the SPI, like:
```
show implementations of 'org.apache.shardingsphere.transaction.xa.spi.XATransactionManagerProvider'
```

On this basis, we provide syntactic sugar for some commonly used algorithms, as you showed, like
```
SHOW SHARDING ALGORITHM IMPLEMENTATIONS;
```

Is this feasible?

**Comment by dongzl** [comment]
> Hi @dongzl , The output you showed works very well, but such input means that we need to provide a syntax for each SPI, which will be a lot of work.
> 
> For example, we also have `KeyGenerateAlgorithm`, `XATransactionManagerProvider`, `ReadQueryLoadBalanceAlgorithm` and many other SPIs.
> 
> Personally, can we first provide a basic syntax that can be applied to all SPIs, which means that the input needs to contain the full class path of the SPI, like:
> 
> ```
> show implementations of 'org.apache.shardingsphere.transaction.xa.spi.XATransactionManagerProvider'
> ```
> 
> On this basis, we provide syntactic sugar for some commonly used algorithms, as you showed, like
> 
> ```
> SHOW SHARDING ALGORITHM IMPLEMENTATIONS;
> ```
> 
> Is this feasible?

Hi @RaigorJiang , Thanks for your reply, I think it's very good, The basic syntax provide all the SPI, and syntactic sugar for some commonly algorithms, I think this is a good idea.

**Comment by RaigorJiang** [comment]
@dongzl 
Thank you also for your idea. 
Please allow me to state that the syntax I provided is just an example and any suggestions are welcome.
