### ISSUE TITLE
insert failed with foreign key greater than 10158238

### ISSUE THREAD

**Issue by Bingo20** [apache/shardingsphere#28987]
## Bug Report

I am using sharding-sphere proxy docker image to insert data to mysql. I have two sharding tables: data & data_gt_version, where data_gt_version has a field dataId references data on column id.  I found a wierd situation: when dataId >= 10158238, insertion fails without error output.
Example insert sql: 

> INSERT IGNORE INTO `welabel-shard2`.data_gt_version (id, created_at, updated_at, deleted_at, value, gt_version, dataId, extUserId) VALUES (
4658625, DEFAULT, DEFAULT, DEFAULT, 'xxx', '-1', 10158238, 3);

my sharding config:

>databaseName: welabel-shard2
>
>dataSources:
> welabel:
>   url: jdbc:mysql://xxx
>   username: 111
>   password: 222
>   connectionTimeoutMilliseconds: 30000
>   idleTimeoutMilliseconds: 60000
>   maxLifetimeMilliseconds: 1800000
>   maxPoolSize: 50
>   minPoolSize: 1
>#
>rules:
>- !SHARDING
>  tables:
>    data:
>      actualDataNodes: welabel.data_${0..9}
>      tableStrategy:
>        standard:
>          shardingColumn: id
>          shardingAlgorithmName: data_inline
>      keyGenerateStrategy:
>        column: id
>        keyGeneratorName: snowflake
>    data_gt_version:
>      actualDataNodes: welabel.data_gt_version_${0..9}
>      tableStrategy:
>        standard:
>          shardingColumn: id
>          shardingAlgorithmName: data_gtv_inline
>      keyGenerateStrategy:
>        column: id
>        keyGeneratorName: snowflake
>  bindingTables:
>    - data
>    - data_gt_version
>  defaultTableStrategy:
>    none:
>  shardingAlgorithms:
>    data_inline:
>      type: INLINE
>      props:
>        algorithm-expression: data_${id % 10}
>        allow-range-query-with-inline-sharding: true
>    data_gtv_inline:
>      type: INLINE
>      props:
>        algorithm-expression: data_gt_version_${id % 10}
>  keyGenerators:
>    snowflake:
>      type: SNOWFLAKE

**Comment by Bingo20** [comment]
dataId <= 10158237 can be insert to table data_gt_version:
![image](https://github.com/apache/shardingsphere/assets/59853573/f0337eb0-c267-432f-a9dc-22c660e98689)

**Comment by terrymanu** [comment]
Based on your description of the issue, I do not believe it is caused by ShardingSphere.
