### ISSUE TITLE
The CDCClient doesn't implement dropstreaming function.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#28980]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-152f56c1195f324d310e794c443bec2b3be7190d
Commit Message: Improve CDCImporter finished flag
Branch: fix
Build time: 2022-12-12T03:18:10+0800
```
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The CDCClient implements dropstreaming function.

### Actual behavior
The CDCClient doesn't implement dropstreaming function.

**Comment by azexcy** [comment]
It's fixed at #28890, thanks for feedback.
