### ISSUE TITLE
Caused by: java.sql.SQLException: Unknown exception: Cannot invoke method div() on null object

### ISSUE THREAD

**Issue by superhahastart** [apache/shardingsphere#29029]
maven config :
 <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.4.1</version>
 </dependency>

yaml config：

rules:
  - !SHARDING
    tables:
      pay_order:
        #给出一张存在的物理表,算法表达式会自动替换掉10000
        actualDataNodes: ds_${0..1}.pay_order_10000_${0..32}
        tableStrategy:
          complex:
            shardingColumns: owner_code,id
            shardingAlgorithmName: pay_order_complex
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    defaultDatabaseStrategy:
      standard:
        shardingColumn: id
        shardingAlgorithmName: database_inline
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_$->{id % 2}
      pay_order_complex:
        type: COMPLEX_INLINE
        props:
          sharding-columns: owner_code,id
          algorithm-expression: pay_order_${owner_code/1}_${id % 33}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE

sql xml:

<img width="667" alt="屏幕截图 2023-11-13 223216" src="https://github.com/apache/shardingsphere/assets/78898670/29a3f209-abc8-4d8c-9d12-bcd62470fd0f">

When a batch write is executed, the following error message is occasionally displayed:

<img width="957" alt="屏幕截图 2023-11-13 222954" src="https://github.com/apache/shardingsphere/assets/78898670/34658edb-0df9-4672-b5f9-8ecd278cc574">
<img width="1029" alt="屏幕截图 2023-11-13 225351" src="https://github.com/apache/shardingsphere/assets/78898670/a6d8d04b-bc19-4926-800f-de59778383d2">

**Comment by strongduanmu** [comment]
@superhahastart Please check the fields in groovy inline expression for null?
