### ISSUE TITLE
Consider formatting algorithm props output to JSON

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#29039]
Query rules through RQL or RAL, and the format of algorithm props in the results obtained is as follows:
```sql
+-------------------------------------------------------+
| encryptor_props                                       |
+-------------------------------------------------------+
| aes-key-value=BA,FF=AB3,digest-algorithm-name=SHA-512 |
+-------------------------------------------------------+
```
The problem is that if the parameter value contains characters such as "=", "," etc., it may cause misunderstanding.

Using JSON format eliminates misunderstandings
```sql
+-----------------------------------------------------------------+
| encryptor_props                                                 |
+-----------------------------------------------------------------+
| {"aes-key-value"="BA,FF=AB3","digest-algorithm-name"="SHA-512"} |
+-----------------------------------------------------------------+
```
I'm going to replace the output of algorithm props into JSON format, which will involve the following RQL and RAL implementation changes

TASK LIST:
- [x] Refactor PropertiesConverter
- [x] Unit tests
- [x] E2E
- [ ] Documention

**Comment by RaigorJiang** [comment]
Good idea 👍
