### ISSUE TITLE
CREATE SHARDING TABLE RULE will delete the previous sharding configuration

### ISSUE THREAD

**Issue by lemon-xxy** [apache/shardingsphere#29031]
### Which version of ShardingSphere did you use?
docker:apache/shardingsphere-proxy:5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Add sharding rules
### Actual behavior
Delete the previous sharding rule and add a new sharding rule
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
before
<img width="1303" alt="image" src="https://github.com/apache/shardingsphere/assets/19415409/a9a2a8b1-3637-45b8-bf37-177116081169">
after
<img width="1187" alt="image" src="https://github.com/apache/shardingsphere/assets/19415409/77d2bb53-f71a-4c6c-ba0d-a7325844e186">

**Comment by RaigorJiang** [comment]
Hi @lemon-xxy 
I tested with version 5.4.1 and it didn’t reproduce.  [Proxy 5.4.1](https://www.apache.org/dyn/closer.lua/shardingsphere/5.4.1/apache-shardingsphere-5.4.1-shardingsphere-proxy-bin.tar.gz)

<img width="1148" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/950b6765-abb4-4baa-bd6f-67ce5106eea7">


PS. I used cluster mode (ZK),  and what is your mode configuration? @lemon-xxy

**Comment by lemon-xxy** [comment]
I tested the same configuration using 5.4.0 and it's normal

**Comment by nikhilerigila09** [comment]
Hi @lemon-xxy, I faced the same issue using 5.4.1 in Standalone mode, in both the Binary Distribution of shardingsphere-proxy and using Helm chart deployment. 
The issue seems to be only with adding table rules, there is no issue in adding storage units. 

For a workaround i've used Compatible_Standalone mode instead, and it works fine with this mode.

**Comment by RaigorJiang** [comment]
> Hi @lemon-xxy, I faced the same issue using 5.4.1 in Standalone mode, in both the Binary Distribution of shardingsphere-proxy and using Helm chart deployment. The issue seems to be only with adding table rules, there is no issue in adding storage units.
> 
> For a workaround i've used Compatible_Standalone mode instead, and it works fine with this mode.

Well, thanks for your feedback~
