### ISSUE TITLE
spring boot uses oracle data source and integrates ShardingSphere to scan metadata of database and table. A large number of non-public tables appear

### ISSUE THREAD

**Issue by NoSayDie** [apache/shardingsphere#29049]
The version of ShardingSphere used:     
   <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.1.1</version>
        </dependency>
springboot configuration information：
![image](https://github.com/apache/shardingsphere/assets/48913897/ab14ac3c-28a6-42b1-800c-ff516796a5f1)
Expected behavior：
Startup items Scan only the public tables of the oracle user, but not the system tables
Actual behavior：
The startup project is configured with multiple data sources, defaults to the primary data source, and scans system tables other than the expected public tables when it starts.
![微信截图_20231116100821](https://github.com/apache/shardingsphere/assets/48913897/a4b2e887-38fc-46de-ae07-5e219988e36f)
![微信图片_20231116100834](https://github.com/apache/shardingsphere/assets/48913897/3e05aead-5d37-4e7b-8020-ef8e951ed600)

**Comment by zhaojinchao95** [comment]
Your version is too old, please try upgrading `ShardingSphere` version.

**Comment by CYBWithFlourish** [comment]
Your version is too old, please try upgrading ShardingSphere version.
@zhaojinchao95 is right

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
