### ISSUE TITLE
Is it normal to have duplicate values in the key field in the repository table of sharding proxy?

### ISSUE THREAD

**Issue by yuyongxing** [apache/shardingsphere#29040]
## there is data
![image](https://github.com/apache/shardingsphere/assets/16145667/12a0e6e9-7329-4d0c-96f3-686084eb2eb5)

**Comment by terrymanu** [comment]
If it has affected your use, please raise specific questions. If you wish to discuss the source code, you may consider leaving a message in the discussions.
