### ISSUE TITLE
Support batch SQL for insert (xxx) values (111);insert (xxx) values (222);insert (xxx) values (333)；

### ISSUE THREAD

**Issue by gdefenser** [apache/shardingsphere#29050]
We using the ShardingProxy 5.4.0
For our apps, the insert&delete SQL will be generated under this format
```
insert (xxx) values (111);insert (xxx) values (222);insert (xxx) values (333)
```
Based on my understanding, this version was support batch SQL for this format only #25314
```
insert (xxx) values ((111),(222),(333))
```
We hope the further version can support the format as provided
Thanks

**Comment by gdefenser** [comment]
otherwise，dose ShardingProxy5.4.0 has any setting can route my original SQL without proxy?
@strongduanmu

**Comment by strongduanmu** [comment]
@gdefenser Can you try addBatch and executeBatch method? And then config rewriteBatchedStatements = true, it will rewrite multi insert sql to `insert into t (…) values (…) , (…), (…)`

**Comment by gdefenser** [comment]
ok，i try to add this config，thx
