### ISSUE TITLE
spring boot uses oracle data source and integrates ShardingSphere to scan metadata of database and table. A large number of non-public tables appear

### ISSUE THREAD

**Issue by NoSayDie** [apache/shardingsphere#29063]
The version of ShardingSphere used:

org.apache.shardingsphere
sharding-jdbc-core
4.1.1

springboot configuration information：
image
Expected behavior：
Startup items Scan only the public tables of the oracle user, but not the system tables
Actual behavior：
The startup project is configured with multiple data sources, defaults to the primary data source, and scans system tables other than the expected public tables when it starts.
微信截图_20231116100821
微信图片_20231116100834

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
