### ISSUE TITLE
questions about open gauss grammar parsing

### ISSUE THREAD

**Issue by Hvision** [apache/shardingsphere#29069]
When parsing the data type of open gaussd as character varying(16), why should it be parsed as name=charactervarying(16) instead of name=charactervarying, p=16.

**Comment by Hvision** [comment]
i think it is right that parsing character varying(16) to  name=charactervarying, p=16.

**Comment by strongduanmu** [comment]
@Hvision Yes, it looks like a parser bug, do you want to fix it?

**Comment by Hvision** [comment]
@strongduanmu I think we just need to change the g4 parsing rule file.
