### ISSUE TITLE
version:5.4.1,Unable to find routing shard

### ISSUE THREAD

**Issue by shig-cn** [apache/shardingsphere#29121]
sharding-proxy
version:5.4.1

It seems you're encountering routing shard errors in Sharding-Proxy 5.4.1 during concurrent write tests. This issue might be related to the configuration or the specifics of your testing scenario. Check your sharding configuration, and ensure proper setup for concurrent writes. If the problem persists, consult Sharding-Proxy documentation or community support for further assistance.

Error 20081: Routed target `device_8` does not exist, available targets are `[ds_0, ds_1]`.

**Comment by terrymanu** [comment]
I don't consider this a description of an issue, and I currently cannot understand the purpose of this issue, so please allow me to close this issue.
