### ISSUE TITLE
Failed to deserialize data of longblob type stored

### ISSUE THREAD

**Issue by charlesChou321** [apache/shardingsphere#29130]
Using the latest version of shardingproxyy, the database is using mysql.Using proxy to insert longBlob type data into the table, the storage is a serialized HashSet object.  After querying the data, deserialization failed with an error.  Have you encountered this problem again?The java version used in the project is java8.
org.flowable.common.engine.api.FlowableException: Couldn't deserialize object in variable 'sid-826BAC32-6E14-4A5B-B4EA-AF438B257AD4_assignees'

**Comment by terrymanu** [comment]
If the exception is `org.flowable.common.engine.api.FlowableException`, I don't think it is an issue related with ShardingSphere
