### ISSUE TITLE
Support parsing SQL Server SELECT <First sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29153]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT <First line>
FROM <Second line>
WHERE <Third line>
```
[link](https://learn.microsoft.com/zh-cn/sql/tools/sqlcmd/sqlcmd-use-utility?view=sql-server-ver16)

```sql
SELECT reason, score,
      script = JSON_VALUE(details, '$.implementationDetails.script'),
      planForceDetails.*,
      estimated_gain = (regressedPlanExecutionCount + recommendedPlanExecutionCount)
                  * (regressedPlanCpuTimeAverage - recommendedPlanCpuTimeAverage)/1000000,
      error_prone = IIF(regressedPlanErrorCount > recommendedPlanErrorCount, 'YES','NO')
FROM sys.dm_db_tuning_recommendations
CROSS APPLY OPENJSON (Details, '$.planForceDetails')
    WITH (  [query_id] int '$.queryId',
            regressedPlanId int '$.regressedPlanId',
            recommendedPlanId int '$.recommendedPlanId',
            regressedPlanErrorCount int,
            recommendedPlanErrorCount int,
            regressedPlanExecutionCount int,
            regressedPlanCpuTimeAverage float,
            recommendedPlanExecutionCount int,
            recommendedPlanCpuTimeAverage float
          ) AS planForceDetails
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/automatic-tuning/automatic-tuning?view=sql-server-ver16)

```sql
INSERT @table1 (c2, is_transient) VALUES (N'sample durable', 0)
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver16)

```sql
INSERT @table1 (c2, is_transient) VALUES (N'sample non-durable', 1)
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver16)

```sql
SELECT product_id   
FROM products   
WHERE CONTAINS(product_description, '"Snap Happy 100EZ" OR FORMSOF(THESAURUS,"Snap Happy") OR "100EZ"')
AND product_cost < 200
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/search/full-text-search?view=sql-server-ver16)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by strongduanmu** [comment]
@TherChenYang Assigned. 👍🏻
