### ISSUE TITLE
Support parsing SQL Server SELECT TRIM( sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29162]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT TRIM( '.,! ' FROM '     #     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(LEADING '.,! ' FROM  '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(TRAILING '.,! ' FROM '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(BOTH '123' FROM '123abc123') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
INSERT INTO [HR].[Employees]
        ([SSN]
        ,[FirstName]
        ,[LastName]
        ,[Salary])
    VALUES
        ('795-73-9838'
        , N'Catherine'
        , N'Abel'
        , $31692)
```
[link](https://learn.microsoft.com/zh-cn/azure/azure-sql/database/always-encrypted-enclaves-getting-started-vbs?view=azuresql)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by venkatdatta0** [comment]
Hi @FlyingZC 
I am new to the community and trying to add the support for TRIM function.

Please review: https://github.com/apache/shardingsphere/pull/29542

**Comment by strongduanmu** [comment]
Hi @venkatdatta0, I'm so sorry for late repley. I will review this pr.

**Comment by zzzk1** [comment]
Hi, @strongduanmu can you assigned this to me ? i want to try

**Comment by zhuruixuan** [comment]
@strongduanmu
 Hello, Can you assign me this task? I'll try to solve it.

**Comment by strongduanmu** [comment]
I assigned the task to @zzzk1 according to first come, first served basis. @zhuruixuan Are you interested in other SQL parsing tasks? There are many more tasks on our issue list.
