### ISSUE TITLE
Support parsing SQL Server SELECT COUNT(*) sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29170]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT COUNT(*) AS [Number of rows] FROM #Test
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16)

```sql
SELECT obj1.name AS [XEvent-name],
    col2.name AS [XEvent-column],
    obj1.description AS [Descr-name],
    col2.description AS [Descr-column]
FROM sys.dm_xe_objects AS obj1
INNER JOIN sys.dm_xe_object_columns AS col2
    ON col2.object_name = obj1.name
ORDER BY obj1.name,
    col2.name
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/extended-events/extended-events?view=sql-server-ver16)

```sql
INSERT INTO TestSchema.Employees (Name, Location) VALUES
  (N'Jared',  N'Australia'),
  (N'Nikita', N'India'),
  (N'Tom',    N'Germany')
```
[link](https://learn.microsoft.com/zh-cn/azure/azure-sql/database/connect-query-go?view=azuresql)

```sql
INSERT INTO dbo.Customers
```
[link](https://learn.microsoft.com/zh-cn/azure-data-studio/tutorial-sql-editor)

```sql
SELECT query = a.text, start_time, percent_complete,
    eta = dateadd(second,estimated_completion_time/1000, getdate())
FROM sys.dm_exec_requests r
    CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) a
WHERE r.command = 'RESTORE DATABASE'
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/restore-statements-transact-sql?view=sql-server-ver16)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by strongduanmu** [comment]
@TherChenYang Assigned, and good luck for you.
