### ISSUE TITLE
Support parsing SQL Server SELECT pglogical.replication_set_add_all_tables('myreplicationset', sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29175]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT pglogical.replication_set_add_all_tables('myreplicationset', '{public}'::text[])
```
[link](https://learn.microsoft.com/zh-cn/azure/postgresql/flexible-server/concepts-logical)

```sql
SELECT pglogical.replication_set_add_all_tables('default', ARRAY['testUser'])
```
[link](https://learn.microsoft.com/zh-cn/azure/postgresql/flexible-server/concepts-logical)

```sql
SELECT session_id as SPID, command, a.text AS Query, start_time, percent_complete
   , dateadd(second,estimated_completion_time/1000, getdate()) as estimated_completion_time
FROM sys.dm_exec_requests r
CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) a
WHERE r.command in ('BACKUP DATABASE','RESTORE DATABASE')
```
[link](https://learn.microsoft.com/zh-cn/azure/azure-sql/managed-instance/restore-sample-database-quickstart?view=azuresql)

```sql
SELECT * FROM (
SELECT col1, ROW_NUMBER () OVER (PARTITION by col1 ORDER BY col1) rn
FROM tab1 WHERE col1='XYZ'
) WHERE rn = 1
```
[link](https://learn.microsoft.com/zh-cn/azure/synapse-analytics/migration-guides/teradata/1-design-performance-migration)

```sql
SELECT count(*)
FROM input 
GROUP BY  clusterid, tumblingwindow (minutes, 5)
```
[link](https://learn.microsoft.com/zh-cn/azure/stream-analytics/stream-analytics-streaming-unit-consumption)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by yydeng626** [comment]
Please assign to me

**Comment by strongduanmu** [comment]
@yydeng626 Assigned.
