### ISSUE TITLE
Support parsing SQL Server SELECT Person1.name sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29189]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT
    Person1.name AS PersonName,
    STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends
FROM
    Person AS Person1,
    friendOf FOR PATH AS fo,
    Person FOR PATH  AS Person2
WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2)+))
AND Person1.name = 'Jacob'
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)

```sql
SELECT PersonName, Friends, levels
FROM (
    SELECT
        Person1.name AS PersonName,
        STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends,
        LAST_VALUE(Person2.name) WITHIN GROUP (GRAPH PATH) AS LastNode,
        COUNT(Person2.name) WITHIN GROUP (GRAPH PATH) AS levels
    FROM
        Person AS Person1,
        friendOf FOR PATH AS fo,
        Person FOR PATH  AS Person2
    WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2)+))
    AND Person1.name = 'Jacob'
) AS Q
WHERE Q.LastNode = 'Alice'
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)

```sql
SELECT
    Person1.name AS PersonName,
    STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends
FROM
    Person AS Person1,
    friendOf FOR PATH AS fo,
    Person FOR PATH  AS Person2
WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2){1,3}))
AND Person1.name = 'Jacob'
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)

```sql
SELECT PersonName, Friends
FROM (
    SELECT
        Person1.name AS PersonName,
        STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends,
        COUNT(Person2.name) WITHIN GROUP (GRAPH PATH) AS levels
    FROM
        Person AS Person1,
        friendOf FOR PATH AS fo,
        Person FOR PATH  AS Person2
    WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2){1,3}))
    AND Person1.name = 'Jacob'
) Q
WHERE Q.levels = 2
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)

```sql
SELECT
    Person1.name AS PersonName,
    STRING_AGG(Person2.name, '->') WITHIN GROUP (GRAPH PATH) AS Friends,
    Restaurant.name
FROM
    Person AS Person1,
    friendOf FOR PATH AS fo,
    Person FOR PATH  AS Person2,
    likes,
    Restaurant
WHERE MATCH(SHORTEST_PATH(Person1(-(fo)->Person2){1,3}) AND LAST_NODE(Person2)-(likes)->Restaurant )
AND Person1.name = 'Jacob'
AND Restaurant.name = 'Ginger and Spice'
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver16)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by shengdoupi** [comment]
@FlyingZC Hi community, I will have a try. Please assign me.

**Comment by strongduanmu** [comment]
@shengdoupi Welcome, I just assign this issue to you.

**Comment by shengdoupi** [comment]
> @FlyingZC Please assign this issue to me.

@TherChenYang  Hi, I'm working on it now, and I will try to finish it as soon as possible.

**Comment by shengdoupi** [comment]
> @FlyingZC Please assign this issue to me.

@TherChenYang Hi, I'm working on this issue now. It takes me a long time since graph related syntax is quite complex for me. Anyway, I believe it can be finished in a week, thank you!

**Comment by strongduanmu** [comment]
Ok, looking forward to your good news @shengdoupi

**Comment by shengdoupi** [comment]
@strongduanmu Hi, when I try to submit a PR for this issue, I find the function has been supported in #30288 , I think you can close this issue now.

**Comment by strongduanmu** [comment]
@shengdoupi Thank you for your test work, I will close this issue.
