### ISSUE TITLE
Support parsing SQL Server SELECT page_count, sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29191]
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT page_count,
    compressed_page_count,
    forwarded_record_count,
    *
FROM sys.dm_db_index_physical_stats(db_id(), object_id('t3'), NULL, NULL, 'SAMPLED')
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/system-dynamic-management-views/sys-dm-db-index-physical-stats-transact-sql?view=sql-server-ver16)

```sql
SELECT page_count,
    compressed_page_count,
    forwarded_record_count,
    *
FROM sys.dm_db_index_physical_stats(db_id(), object_id('t3'), NULL, NULL, 'DETAILED')
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/system-dynamic-management-views/sys-dm-db-index-physical-stats-transact-sql?view=sql-server-ver16)

```sql
SELECT backup_size/compressed_backup_size FROM msdb..backupset
```
[link](https://learn.microsoft.com/zh-cn/sql/relational-databases/backup-restore/backup-compression-sql-server?view=sql-server-ver16)

```sql
INSERT INTO sales VALUES (N'Canada', N'Alberta', 100)
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver16)

```sql
INSERT INTO sales VALUES (N'Canada', N'British Columbia', 200)
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver16)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by Ken01412** [comment]
Hi @FlyingZC  I want to give this a try , please assign it to me

**Comment by strongduanmu** [comment]
@Ken01412 Assgined.

**Comment by strongduanmu** [comment]
@TherChenYang Assigned.
