### ISSUE TITLE
shardingsphere-jdbc-core 升级到 5.4.1 版本，服务启动非常慢

### ISSUE THREAD

**Issue by tiandihai** [apache/shardingsphere#29216]
数据库里面2000多张表。。shardingsphere-jdbc-core 5.4.0版本，服务启动大概3--5分钟左右。 升级到 5.4.1 版本后服务启动大概需要20来分钟，特别非常慢。不知道是什么原因。看日志一直刷这个。

![微信截图_20231127165143](https://github.com/apache/shardingsphere/assets/6039066/2e4bca49-2a50-423b-afc7-a352235cc11f)

**Comment by tiandihai** [comment]
我这边是4个库，每个库里面2000张表，总共8000张。。。我把表删除了部分后，启动速度会快一点。是因为启动的时候会扫描表结构吗？有没有能够加快扫描速度的方式？

**Comment by tiandihai** [comment]
![image](https://github.com/apache/shardingsphere/assets/6039066/0c307e41-ef98-4aee-a203-bb9d8dd701c7)

**Comment by tiandihai** [comment]
![Uploading 微信截图_20231127165143.png…]()

**Comment by tiandihai** [comment]
![微信截图_20231127165143](https://github.com/apache/shardingsphere/assets/6039066/d8b598bd-9d50-4c74-9b5b-2c1b132700ed)

**Comment by tiandihai** [comment]
没有报错，就是启动慢，启动起来服务也正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月27日(周一) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/shardingsphere] shardingsphere-jdbc-core 升级到 5.4.1 版本，服务启动非常慢 (Issue #29216)




 
有报错吗

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
