### ISSUE TITLE
[5.4.1 PG] Protocol TLSv1.3 is not supported.

### ISSUE THREAD

**Issue by Jxxxx435046451** [apache/shardingsphere#29214]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by Jxxxx435046451** [comment]
![Uploading 1701049702295.jpg…]()

**Comment by Jxxxx435046451** [comment]
![1701049702295](https://github.com/apache/shardingsphere/assets/50289828/13e9351d-8335-4036-8e62-95680af53e87)

**Comment by RaigorJiang** [comment]
Hi @Jxxxx435046451, please describe the issue according to template, including how to reproduce the problem.
