### ISSUE TITLE
Enhance create DatabaseRule must have data source check

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#29233]
DatabaseRules need to be created when the data source exists, otherwise it will be meaningless, and when the node is restarted, existing rules will not be reloaded into the context.

The current situation is that some RuleDefinitionCreateUpdater implementations have already checked the data source in the checkSQLStatement method. such as：

CreateEncryptRuleStatementUpdater
```java
    @Override
    public void checkSQLStatement(final ShardingSphereDatabase database, final CreateEncryptRuleStatement sqlStatement, final EncryptRuleConfiguration currentRuleConfig) {
        if (!sqlStatement.isIfNotExists()) {
            checkDuplicateRuleNames(database.getName(), sqlStatement, currentRuleConfig);
        }
        checkColumnNames(sqlStatement);
        checkAlgorithmTypes(sqlStatement);
        checkToBeCreatedEncryptors(sqlStatement);
        checkDataSources(database);
    }

    private void checkDataSources(final ShardingSphereDatabase database) {
        ShardingSpherePreconditions.checkState(!database.getResourceMetaData().getStorageUnits().isEmpty(), () -> new EmptyStorageUnitException(database.getName()));
    }
```

I am going to extract this check into the RuleDefinitionBackendHandler as a public check for all statements that create rules.

Task List:

- [ ] RuleDefinitionBackendHandler
- [ ] NewRuleDefinitionBackendHandler
- [ ] related unit tests
- [ ] E2E

**Comment by HarshSawarkar** [comment]
Hey @Pace2Car, I would like to work on this issue if no one is working on it currently. Also I had this doubt in  

> CreateEncryptRuleStatementUpdater
> 
> ```java
>     @Override
>     public void checkSQLStatement(final ShardingSphereDatabase database, final CreateEncryptRuleStatement sqlStatement, final EncryptRuleConfiguration currentRuleConfig) {
>         if (!sqlStatement.isIfNotExists()) {
>             checkDuplicateRuleNames(database.getName(), sqlStatement, currentRuleConfig);
>         }
>         checkColumnNames(sqlStatement);
>         checkAlgorithmTypes(sqlStatement);
>         checkToBeCreatedEncryptors(sqlStatement);
>         checkDataSources(database);
>     }
> 
>     private void checkDataSources(final ShardingSphereDatabase database) {
>         ShardingSpherePreconditions.checkState(!database.getResourceMetaData().getStorageUnits().isEmpty(), () -> new EmptyStorageUnitException(database.getName()));
>     }
> ```
> 
> I am going to extract this check into the RuleDefinitionBackendHandler as a public check for all statements that create rules.

by checks do you mean only the Datasource check or all the listed checks in the method and also some of the statements that create rules like **_CreateMaskRuleExecutor_** dosn't check for **_DataSource_**. So, should this statements be checked for DataSource? Furthermore, the  **_RuleDefinitionBackendHandler_** class is from **_Proxy_** package, so to be able to checkDataSource() implemented in the  **_RuleDefinitionBackendHandler_**, this module has to be added in the corresponding _create rule class_. Will this implementation be correct?

**Comment by Pace2Car** [comment]
> Hey @Pace2Car, I would like to work on this issue if no one is working on it currently. Also I had this doubt in
> 
> > CreateEncryptRuleStatementUpdater
> > ```java
> >     @Override
> >     public void checkSQLStatement(final ShardingSphereDatabase database, final CreateEncryptRuleStatement sqlStatement, final EncryptRuleConfiguration currentRuleConfig) {
> >         if (!sqlStatement.isIfNotExists()) {
> >             checkDuplicateRuleNames(database.getName(), sqlStatement, currentRuleConfig);
> >         }
> >         checkColumnNames(sqlStatement);
> >         checkAlgorithmTypes(sqlStatement);
> >         checkToBeCreatedEncryptors(sqlStatement);
> >         checkDataSources(database);
> >     }
> > 
> >     private void checkDataSources(final ShardingSphereDatabase database) {
> >         ShardingSpherePreconditions.checkState(!database.getResourceMetaData().getStorageUnits().isEmpty(), () -> new EmptyStorageUnitException(database.getName()));
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am going to extract this check into the RuleDefinitionBackendHandler as a public check for all statements that create rules.
> 
> by checks do you mean only the Datasource check or all the listed checks in the method and also some of the statements that create rules like **_CreateMaskRuleExecutor_** dosn't check for **_DataSource_**. So, should this statements be checked for DataSource? Furthermore, the **_RuleDefinitionBackendHandler_** class is from **_Proxy_** package, so to be able to checkDataSource() implemented in the **_RuleDefinitionBackendHandler_**, this module has to be added in the corresponding _create rule class_. Will this implementation be correct?

Welcome, it should check that the DataSource exists before creating any DatabaseRule. In addition, pay attention to the possible occurrence of circular dependencies when implementing.

**Comment by HarshSawarkar** [comment]
Hi @Pace2Car I implemented the checkDataSource() method inside the RuleDefinationExecuteEngine() to avoid circular dependency.Can you please review?

**Comment by HarshSawarkar** [comment]
Hi @Pace2Car I  created this new branch from **_master_**branch. Also previously I did "git merge origin/master "  into my development branch. I got the same conflicts both the times. Can you  please tell how to resolve this issues?

**Comment by Pace2Car** [comment]
Close as completed.
