### ISSUE TITLE
What is the significance of the ShardingSphere-JDBC clustering pattern?

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#29232]
ShardingSphere-JDBC 5+; There's a pattern configuration. Not sure what this means, but configuring cluster mode is a hassle. It is recommended that the production environment use the cluster mode, but I use ShardingSphere-JDBC is the routing of the database and table of the single machine, even if I am a microservice, I do not need ShardingSphere-JDBC cluster. What's the point of this. There is also no complete yaml configuration sample, including read and write separation and sub-library sub-table. Why not make one?

**Comment by RaigorJiang** [comment]
Using cluster mode, users can dynamically change data sources and rules in JDBC through Proxy.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/

There are examples of mixed use of sharding and readwrite-splitting in the test module, for example:
https://github.com/apache/shardingsphere/blob/master/test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/rules.yaml

**Comment by 65725738** [comment]
> Using cluster mode, users can dynamically change data sources and rules in JDBC through Proxy. https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/mode/
> 
> There are examples of mixed use of sharding and readwrite-splitting in the test module, for example: https://github.com/apache/shardingsphere/blob/master/test/e2e/sql/src/test/resources/env/scenario/dbtbl_with_readwrite_splitting/rules.yaml

I mean this mode configuration is generally not useless. I will set the memory mode, I use sharding-jdbc normal table and library function has no impact?

**Comment by RaigorJiang** [comment]
> I mean this mode configuration is generally not useless. I will set the memory mode, I use sharding-jdbc normal table and library function has no impact?

Mode only affects the persistence method and whether it can be dynamically updated, but does not affect the use of features.
