### ISSUE TITLE
When the CDC streaming job is active , stop_time should be empty.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29249]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (#29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When the CDC streaming list is active , stop_time should be empty.

### Actual behavior
When the CDC streaming list is active , stop_time is not empty.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.  cdc client job is active
2.  show streaming list
![image](https://github.com/apache/shardingsphere/assets/97432411/3e14f4d8-6e23-4ea6-9d92-50a4a7a9c795)

**Comment by azexcy** [comment]
Fixed at https://github.com/apache/shardingsphere/pull/29277
