### ISSUE TITLE
How to detect the CDC streaming job status after the cdc server's exception needs to be considered.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29259]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (#29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800

```
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
CDC server exception, such as after kill-9 ss proxy, and then start ss-proxy the CDC task status is not active

### Actual behavior
CDC server exception, such as after kill-9 ss proxy, and then start ss-proxy the CDC task status is still active 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. start cdc job
2. kill ss-proxy
3. start ss-proxy and check cdc streaming job status

**Comment by azexcy** [comment]
`kill -9 pid` Unable to terminate the CDC task properly, so i will add `force stop streaming ` DistSQL later

**Comment by azexcy** [comment]
Allow delete active cdc jobs via DistSQL
