### ISSUE TITLE
Use JavaAgent introducing Sharding-JDBC

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#2927]
For now, there's code invading when using Sharding-JDBC. We try to find way that using JavaAgent to prevent changing code before introduce the Sharding-JDBC.

The main idea is replace DataSource via Javaassist, as well as any other bytecode engineering library. 

Please feel free to discuss if you have better way or better practise.

**Comment by xiaoya0991** [comment]
JavaAgent How the performance？

**Comment by tuohai666** [comment]
We'll test the performance as soon as the demo is complete. Do you have any experience in JavaAgent? Any suggestions?

**Comment by cherrylzhao** [comment]
[byte-buddy](https://github.com/raphw/byte-buddy/tree/master) have a convenient API to use java-agent and modify byte code at runtime, we can delegate the DataSource to ShardingDataSource using their `Changing existing classes` feature.

**Comment by tuohai666** [comment]
@cherrylzhao Thanks for your suggestion, yes, byte-buddy is better.

**Comment by tuohai666** [comment]
I'd like to share some details about how to redefine the DataSource.

1. Use SkyWalking [apm-agent-core](https://github.com/apache/skywalking/tree/master/apm-sniffer/apm-agent-core) instead of byte-buddy to hack JDBC code. apm-agent-core has significantly enhanced byte-buddy.

2. When an original DataSource is hacked for example to a ShardingDataSource. How to decide the behavior when the method of this DataSource is called? 
If the user call ds.getConnection(), we want the DataSource behaves like a ShardingDataSource. While if the Sharding-JDBC call ds.getConnection(), we want the DataSource behaves like an original DataSource.
It's convenient that we can find out who currently call getConnection() via Thread.currentThread().getStackTrace(). When the stack trace is from Sharding-JDBC, we treat the DataSource as the original one. 

3. How to support so many DataSources from various connection pools?
We have to redefine DataSources for some popular connection pools one by one. At first we only need to hack HikariDataSource and add it to a support list. After that users can add others they want.

**Comment by tuohai666** [comment]
DataSource should be intercepted in premain and be redefined to a new DataSource. The procedure can be illustrated as follow:

![image](https://user-images.githubusercontent.com/24643893/64142923-9edca580-ce40-11e9-8e02-72164dcfa4b4.png)

**Comment by sunbufu** [comment]
Sorry, Why should we replace the DataSource in connection pool? Can you give me some examples?

**Comment by tuohai666** [comment]
We don't have to replace the DataSource if you have better idea. There's no demo yet.

**Comment by yanickxia** [comment]
@yanyzy  this seem you good at javaAgent..

**Comment by terrymanu** [comment]
Expired
