### ISSUE TITLE
Unsupported SQL of `/*FORCE_IMCI_NODES*/ explain select /*+ SET_VAR(cost_threshold_for_imci=0) */ * from my_table`

### ISSUE THREAD

**Issue by GavinGuan24** [apache/shardingsphere#29311]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

No, I didn't retrieve it

### Describe the feature you would like.

Some databases have specific functions. I'm using a database which support **hint** by specific annotations.

```sql
/*FORCE_IMCI_NODES*/
explain select
/*+ SET_VAR(cost_threshold_for_imci=0) */ 
* 
from my_table
```

I executed the above SQL and got an exception.

```
### Cause: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: Unsupported SQL of `/*FORCE_IMCI_NODES*/ explain select /*+ SET_VAR(cost_threshold_for_imci=0) */
*
from my_table t
```

<img width="1220" alt="image" src="https://github.com/apache/shardingsphere/assets/33683337/90b272db-d288-4cf1-85d6-68c27194c0c5">

I hope I don't see this exception in future releases.

Thank your guys. 😁

**Comment by zihaoAK47** [comment]
Hi, can you provide more detailed information, such as the current version information and database related information?

**Comment by GavinGuan24** [comment]
```xml
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-core</artifactId>
    <version>4.1.1</version>
</dependency>

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
    <version>4.1.1</version>
</dependency>
```

My project is using MAVEN.
The version of `sharding-jdbc` is as above.
The database is `PolarDB 8.0.1`  (Aliyun PolarDB is compatible with MySQL).
This is the database that supports hint.

[PolarDB 8.0.1  FQA](https://help.aliyun.com/zh/polardb/polardb-for-mysql/user-guide/faq-8?spm=a2c4g.11186623.0.0.384a5614ZLijzi#section-37s-5vy-j75) You can use Chrome to translate entire web pages to view.

**Comment by zihaoAK47** [comment]
> ```
> <dependency>
>     <groupId>org.apache.shardingsphere</groupId>
>     <artifactId>sharding-jdbc-core</artifactId>
>     <version>4.1.1</version>
> </dependency>
> 
> <dependency>
>     <groupId>org.apache.shardingsphere</groupId>
>     <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
>     <version>4.1.1</version>
> </dependency>
> ```
> 
> My project is using MAVEN. The version of `sharding-jdbc` is as above. The database is `PolarDB 8.0.1` (Aliyun PolarDB is compatible with MySQL). This is the database that supports hint.
> 
> [PolarDB 8.0.1 FQA](https://help.aliyun.com/zh/polardb/polardb-for-mysql/user-guide/faq-8?spm=a2c4g.11186623.0.0.384a5614ZLijzi#section-37s-5vy-j75) You can use Chrome to translate entire web pages to view.

This issue also exists on the current master branch, and I will investigate it. Thank you very much for your feedback.

**Comment by GavinGuan24** [comment]
anyway, I wanna repeat it. I observed two phenomena.

this snippet will work fine.
```
/*FORCE_IMCI_NODES*/
select
/*+ SET_VAR(cost_threshold_for_imci=0) */ 
* 
from my_table
```


and this snippet will throw the exception.
```
/*FORCE_IMCI_NODES*/ explain select /*+ SET_VAR(cost_threshold_for_imci=0) */
* 
from my_table
```

**Comment by zihaoAK47** [comment]
@GavinGuan24 Hello, this issue has been resolved. Can you use the code on the master branch to test it?

**Comment by GavinGuan24** [comment]
@zihaoAK47  @strongduanmu    
You guys is awesome.  it's working.  shardingsphere is better now!!! 
Thank you all.

**Comment by strongduanmu** [comment]
> @zihaoAK47 @strongduanmu You guys is awesome. it's working. shardingsphere is better now!!! Thank you all.

@GavinGuan24 Thank you for your test work. Let's make shardingsphere better!

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
