### ISSUE TITLE
Updated ShardingSphere-Proxy  from  5.0.0 to 5.4.1,no tables display when show tables.

### ISSUE THREAD

**Issue by dengxiaolin23** [apache/shardingsphere#29310]
ds and shadow_ds has been created. we have created same tables in ds and shadow_ds。
1. Updated ShardingSphere-Proxy  from  5.0.0 to 5.4.1.
2. changed config-shadow.yaml as bellow
[config-shadow.txt](https://github.com/apache/shardingsphere/files/13593499/config-shadow.txt)
3.changed server.yaml as bellow.
[server.txt](https://github.com/apache/shardingsphere/files/13593508/server.txt)
4. Connect DB by port 3307 and execute show tables；but no tables display.

we cat't reproduce this issue on 5.0.0.How to How to configure shadow db on 5.4.1?

**Comment by jiangML** [comment]
You can try to execute `LOAD SINGLE TABLE *.*;`
Ref: https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/load-single-table/

**Comment by dengxiaolin23** [comment]
> You can try to execute `LOAD SINGLE TABLE *.*;` Ref: https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/load-single-table/

Thanks for your reply,but I can't fix this problem by you way.
![1](https://github.com/apache/shardingsphere/assets/149980880/f64d8c94-2547-44ab-947d-074f37407f63)

If you have successfully configured it, can you send me your configuration?
