### ISSUE TITLE
ShardingSphere cannot support table connection queries of different shcemal tables in the same PG database.

### ISSUE THREAD

**Issue by fmz200** [apache/shardingsphere#29322]
For example: Table A belongs to the PG database account library schemalA. When executing sql select *from A, an error message appears. Table A does not exist; the table can only be found by adding the shcemal name in front of it, such as: select * from schemalA.A
For example: table A belongs to the PG database account library schemalA, table B belongs to table A and belongs to the PG database account library schemalB, select * from schemalA.A a,schemalB.B b where a.id=b.id will be org.apache.shardingsphere. infra.exception.postgresql.exception.PostgrsSQLException;
I hope that a configuration similar to mycat's checkSQLschemal can be optimized.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.
