### ISSUE TITLE
How can non-data desensitized tables be accessed

### ISSUE THREAD

**Issue by zpinsg** [apache/shardingsphere#29359]
I am using the data desensitization function of ShardingSphere-Proxy. I have created the database, storage unit and data desensitization rules through DistSQL as follows:

CREATE database hlego_platform_proxy_db;

use hlego_platform_proxy_db;

REGISTER STORAGE UNIT hlego_platform (

HOST="xx.x.xx.xxx",

PORT=3315,

DB="hlego_platform",

USER="xxxx",

PASSWORD="xxxx"

);

CREATE MASK RULE code_snippet_revision (

COLUMNS(

(NAME=`name`,TYPE(NAME='AES', PROPERTIES('aes-key'='123456abc'))),

(NAME=`author`,TYPE(NAME='AES', PROPERTIES('aes-key'='123456abc')))

));

Through testing, the code_snippet_revision table is expected to return data for desensitized columns and other columns, but the other tables in the hlego_platform library do not have access.

My problem now is, if there are hundreds of tables in the library, only a few tables have data desensitization requirements, and the others have no requirements, how should I easily configure the tables with desensitization rules and other tables without desensitization requirements through ShardingSphere-Proxy?

**Comment by zhaojinchao95** [comment]
There is currently no more efficient configuration way. Do you have any ideas?

**Comment by RaigorJiang** [comment]
@zpinsg I think you need to load single tables, please refer to DistSQL:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/single-table/load-single-table/

**Comment by zpinsg** [comment]
@RaigorJiang load single table can really meet the needs, thank you very much!
