### ISSUE TITLE
Can the permission rule configuration, i.e. authority.users information, be maintained through DistSQL？

### ISSUE THREAD

**Issue by zpinsg** [apache/shardingsphere#29360]
I am using ShardingSphere-Proxy. How can the authentication and authorization information be changed dynamically? For example, when I need to add a new user, can I only modify the configuration file server.yaml and then restart the service to take effect?
I have checked the usage documentation, DistSQL only has sql to view, there is no new/modified/deleted sql, what should I do to dynamically change permissions?

**Comment by zhaojinchao95** [comment]
It seems not support.

**Comment by RaigorJiang** [comment]
For security reasons, providing the ability to dynamically manage users and permissions requires a fine-grained permission engine to support it. (Otherwise, anyone can create users and authorize them.) 
Currently, this part of the capability has not been open sourced.

**Comment by zpinsg** [comment]
@RaigorJiang Thank you for your reply！
