### ISSUE TITLE
no like_encryptor exists in 5.4.1

### ISSUE THREAD

**Issue by hhw3KevinHou** [apache/shardingsphere#29377]
## Bug Report
where is like_encryptor?  
Can not be found in source code. And there is no release notes about the change of like_encryptor after 5.3. 
It is just disappear.
ITEncryptLikeAlgorithmFixture.java is in test package. Why the ‘like’ search ability is removed and no documentation。
Now only AES and MD5 can be found in https://shardingsphere.apache.org/document/current/cn/dev-manual/encrypt/. 

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
like query can be used.

### Actual behavior
no like query for encrypted column.

**Comment by strongduanmu** [comment]
Hi @hhw3KevinHou, you can get like encrypt algothrim in plugin repository - https://github.com/apache/shardingsphere-plugin/blob/main/features/encrypt/like/src/main/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithm.java

**Comment by hhw3KevinHou** [comment]
It should be mentioned in release notes. It is a big change, and no info in user‘s manual. Thanks.
![image](https://github.com/apache/shardingsphere/assets/14155363/08e981ee-ab00-4496-861c-2e10036100e1)

**Comment by strongduanmu** [comment]
@hhw3KevinHou I think the release manager may have missed this change. However, you can get this information from the ShardingSphere dev mailing list, which we discussed with the community.

**Comment by strongduanmu** [comment]
You can obtain optional plug-ins for ShardingSphere from this document, which are not built into ShardingSphere. - https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/optional-plugins/

**Comment by strongduanmu** [comment]
Since this issue has been resolved, I will close this issue.
