### ISSUE TITLE
sql：do $$ BEGIN IF (select count(*) from information_schema.tables where table_name = 'casbin_rule') = 0 THEN CREATE SEQUENCE IF NOT EXISTS CASBIN_SEQUENCE START 1; END IF; END; $$;

### ISSUE THREAD

**Issue by superhahastart** [apache/shardingsphere#29370]
## Bug Report
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
    <version>5.4.1</version>
</dependency>
<dependency>
    <groupId>org.casbin</groupId>
    <artifactId>casbin-spring-boot-starter</artifactId>
    <version>1.2.0</version>
</dependency>
sql:
do $$ BEGIN IF (select count(*) from information_schema.tables where table_name = 'casbin_rule') = 0 THEN CREATE SEQUENCE IF NOT EXISTS CASBIN_SEQUENCE START 1; END IF; END; $$;
The SQL parsing engine reports an error:
<img width="1639" alt="屏幕截图 2023-12-12 020258" src="https://github.com/apache/shardingsphere/assets/78898670/8fd8586a-3eed-49cb-9a78-fa6272651223">

**Comment by strongduanmu** [comment]
Hi @superhahastart, can you modify this issue according to bug template?
