### ISSUE TITLE
i need new version with snakeyaml 2.2

### ISSUE THREAD

**Issue by onixred** [apache/shardingsphere#29389]
maybe publish a snapshot version  5.4.2-SNAPSHOT.

**Comment by linghengqian** [comment]
- Unfortunately, the project currently does not use the SNAPSHOT Repo under Apache Infra team. This is currently impossible. You may have to seek PMC support in the shardingsphere slack group to do this. 

- So for now, you have to compile the project manually.

- Shardingsphere's use of snakeyaml is unlikely to be affected by the snakeyaml CVE.

**Comment by onixred** [comment]
I can't compile the project manually, i need maven official repository

**Comment by linghengqian** [comment]
> I can't compile the project manually, i need maven official repository

- Uploading SNAPSHOT versions to the maven official repository is strange behavior for ASF.  I plan to raise a documentation PR for the current issue indicating how to use the SNAPSHOT version of shardingsphere-jdbc-core on jitpack.

**Comment by linghengqian** [comment]
- I checked https://jitpack.io/com/github/apache/shardingsphere/5.4.1/build.log. Under normal circumstances, you can only use jitpack's private library to build Shardingsphere's SNAPSHOT, which is not something the community can do.
```shell
Git error:
Repo too big: 609MB
https://github.com/apache/shardingsphere.git
```

**Comment by onixred** [comment]
thanks you for the advice

**Comment by linghengqian** [comment]
- Re-examining this issue, this is not really something that can be solved at the github issue level. You should start a new discussion thread on the mailing list.
