### ISSUE TITLE
Does ShardingSphere query information_schema.KEYWORDS when use MySQL connector-8.0.33?

### ISSUE THREAD

**Issue by sylar8023baby** [apache/shardingsphere#29388]
## Question

My shardingSphere version is 4.1.1.  It throws an error： Constructor threw exception:nested exceptions is
 java.sqlSQLSyntaxErrorException: Table "information_schema.KEYWORDS" does not exist after I upgraded jdbc version from v5.1.49 to v8.0.33. And the backend database is TiDB v6.5.5.

I did not  find some useful information and hope you can give me some help, Thank You.

![WechatIMG25](https://github.com/apache/shardingsphere/assets/25808299/e2888188-8286-411c-8e3f-a945dbc687ed)

**Comment by comecny** [comment]
In TiDB, when querying INFORMATION_SCHEMA, it is necessary to add the prefix tidb or mysql.

**Comment by linghengqian** [comment]
- The ss jdbc version you are using is too old. shardingsphere jdbc simulates the behavior of MySQL's information_schema through https://github.com/apache/shardingsphere/tree/master/infra/common/src/main/resources/schema/mysql/information_schema . 

- `information_schema.KEYWORDS` is currently not simulated.

- I'm assuming a friend is happy to submit a PR?

**Comment by comecny** [comment]
> * The ss jdbc version you are using is too old. shardingsphere jdbc simulates the behavior of MySQL's information_schema through https://github.com/apache/shardingsphere/tree/master/infra/common/src/main/resources/schema/mysql/information_schema .
> * `information_schema.KEYWORDS` is currently not simulated.
> * I'm assuming a friend is happy to submit a PR? Refer to [Add more information_schema tables #25076](https://github.com/apache/shardingsphere/pull/25076) .


I have checked the code, and indeed, there is no information_schema.KEYWORDS. I am more than willing to submit a PR.

**Comment by linghengqian** [comment]
- @comecny Do you plan to deal with this issue in the near future? If you don't have time, I will start organizing PR before the 5.5.0 release.

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
