### ISSUE TITLE
shardignJdbc 5.4.1 use HikariDataSource  or  DruidDataSource

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#29399]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
shardignJdbc 5.4.1 use HikariDataSource  or  DruidDataSource？
### Actual behavior

![image](https://github.com/apache/shardingsphere/assets/67772051/a45a7c97-8d6a-4340-8758-53634a7c5550)
this why？

**Comment by ReyYang** [comment]
I'm having the same issue, here's my configuration

sharding-jdbc.yaml:
<img width="945" alt="image" src="https://github.com/apache/shardingsphere/assets/29473272/3a5d02f2-033a-4a87-b3de-d036bedc8895">

<img width="708" alt="image" src="https://github.com/apache/shardingsphere/assets/29473272/c5b73d28-e478-4bd8-9f2f-c5f1aaad576a">


application.properties:
```properties
# 配置 DataSource Driver
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
# 指定 YAML 配置文件
spring.datasource.url=jdbc:shardingsphere:classpath:sharding-jdbc.yaml
```

When querying, I found that I did not use the data source I configured to query, but instead used HikariPool to query

**Comment by zhaojinchao95** [comment]
Ref #24348

**Comment by ReyYang** [comment]
I've noticed this issue hasn't been solved; are there any other solutions to this now?

**Comment by Yule-Momoko** [comment]
Does it have to be cluster mode？

**Comment by zhaojinchao95** [comment]
Sorry, not yet

**Comment by zhaojinchao95** [comment]
> I've noticed this issue hasn't been solved; are there any other solutions to this now?


Sorry, not yet

**Comment by ReyYang** [comment]
> > I've noticed this issue hasn't been solved; are there any other solutions to this now?
> 
> Sorry, not yet

Are there other versions that can avoid this problem?

**Comment by Yule-Momoko** [comment]
> > I've noticed this issue hasn't been solved; are there any other solutions to this now?
> 
> Sorry, not yet

Does the druid connection count configuration still work if Hikari is actually used

**Comment by zhaojinchao95** [comment]
> > > I've noticed this issue hasn't been solved; are there any other solutions to this now?
> > 
> > 
> > Sorry, not yet
> 
> Are there other versions that can avoid this problem?

I think not, Maybe you can consider submit a pull request to optimization it

**Comment by zhaojinchao95** [comment]
> > > I've noticed this issue hasn't been solved; are there any other solutions to this now?
> > 
> > 
> > Sorry, not yet
> 
> Does the druid connection count configuration still work if Hikari is actually used

I don't know, you can try it

**Comment by ReyYang** [comment]
OK, I'll consider submitting my own PR later, but I need to run the project properly for now

**Comment by zhaojinchao95** [comment]
> OK, I'll consider submitting my own PR later, but I need to run the project properly for now
.
Sorry, your PR can only be used in the next release.

**Comment by liming0** [comment]
@zhaojinchao95 @ReyYang Will this problem still be solved?
