### ISSUE TITLE
How to read the master data rather than slave in one Transaction?

### ISSUE THREAD

**Issue by qichanglong** [apache/shardingsphere#29400]
## Bug Report

**For English only**, other languages will not accept.

### Which version of ShardingSphere did you use?

5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingSphere-jdbc 

### Expected behavior

In one Transaction, before the insert data is commit in master db, the following read is also from **master**

### Actual behavior
In one Transaction, before the insert data is commit in master db, the following read is from **salve**, which lead to an empty result.

### Reason analyze (If you can)
the @Transactional annotation works, becase when an Exception occurs, the uncommit insert data is rollback。
but it turns out that the shardingSphere still read from the slave in one transaction.

### Example codes for reproduce this issue (such as a github link).

The code is as following:

1. introduce the shardingSphere-jdbc 5.4.0
```
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-jdbc-core</artifactId>
			<version>${shardingsphere.version}</version>
		</dependency>
```
2. produce **shardingJdbcDatasource** bean in the way of java api

```
    @Bean
    public DataSource shardingSphereDataSource() throws SQLException {
        ReadwriteSplittingDataSourceRuleConfiguration dataSourceConfig =
                new ReadwriteSplittingDataSourceRuleConfiguration(
                SHARDING_DS_NAME, SHARDING_JDBC_MASTER, Arrays.asList(SHARDING_JDBC_SLAVE),
                SHARDING_LOAD_BALANCE_NAME);

        Properties algorithmProps = new Properties();
        algorithmProps.setProperty(SHARDING_JDBC_SLAVE, "1");
        Map<String, AlgorithmConfiguration> algorithmConfigMap = new HashMap<>(1);
        algorithmConfigMap.put(SHARDING_LOAD_BALANCE_NAME, new AlgorithmConfiguration(SHARDING_LOAD_BALANCE_TYPE,
                algorithmProps));

        ReadwriteSplittingRuleConfiguration ruleConfig =
                new ReadwriteSplittingRuleConfiguration(Collections.singleton(dataSourceConfig), algorithmConfigMap);

        Properties props = new Properties();
        props.setProperty("sql-show", showSql);
        return ShardingSphereDataSourceFactory.createDataSource(createDataSourceMap(),
                Collections.singleton(ruleConfig), props);

    }
```

3. config sqlSessionFactory and transactionManager in spring-context.xml

	
```
	<bean id="transactionManager"
		class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource" ref="shardingSphereDataSource" />
	</bean>
```
```
	<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="shardingSphereDataSource" />
		<property name="typeAliasesPackage" value="com.thinkgem.jeesite,com.saj.commons,com.saj.appapi" />
		<property name="typeAliasesSuperType"
			value="com.thinkgem.jeesite.common.persistence.BaseEntity" />
		<property name="mapperLocations" value="classpath:/mappings/**/*.xml" />
		<property name="configLocation" value="classpath:/mybatis-config.xml"></property>
	</bean>
```

4. Service code:
```
	@Transactional(readOnly = false,rollbackFor = Exception.class)
	public User savePersonRegisterCN(PersonRegisterForm form,HttpServletRequest request) throws Exception{

		User user=new User();
		user.setId("123456987");
		userDao.insert(user);

		User user1 = userDao.get("123456987");
		return user;
	}
```

The insert log is as follow:
![image](https://github.com/apache/shardingsphere/assets/69241243/9d78884a-33ed-4a4b-a9c4-3094b3c1d621)

The read log points that shardingSphere read data from slave though it is in one transaction with the above insert operation.
![image](https://github.com/apache/shardingsphere/assets/69241243/f2d6082a-5e9b-4314-8543-60b1e794623b)

**Comment by niaucz** [comment]
[transactionalReadQueryStrategy ](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting/)

**Comment by qichanglong** [comment]
> [transactionalReadQueryStrategy ](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting/)

thank you, problem solved!
