### ISSUE TITLE
CDC:Exception during basic data synchronization of multiple tables, with some sub tables not synchronized.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29416]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-eb4dc319b97aba2133073446fa310763c4f0a9fb
Commit Message: Move migration.distsql package (#29320)
Branch: master
Build time: 2022-12-12T03:18:10+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Basic data synchronization of multiple tables is normal, and all sub table data synchronization is successful.

### Actual behavior
Exception during basic data synchronization of multiple tables, with some sub tables not synchronized.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://github.com/apache/shardingsphere/assets/97432411/ff408886-cd70-419f-8588-fa2b6aab8500)

![image](https://github.com/apache/shardingsphere/assets/97432411/e80d41cd-4b7d-4608-a1f9-debb3a2da4c7)

**Comment by azexcy** [comment]
I can't reproduce it locally, is it a problem with the environment?
