### ISSUE TITLE
The synchronization table and configuration are the same, but the generated CDC jobIDs are different.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29420]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-eb4dc319b97aba2133073446fa310763c4f0a9fb
Commit Message: Move migration.distsql package (https://github.com/apache/shardingsphere/pull/29320)
Branch: master
Build time: 2022-12-12T03:18:10+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The synchronization table and configuration are the same, but the generated jobIDs are the same.

### Actual behavior
The synchronization table and configuration are the same, but the generated jobIDs are different.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

![b147e3cc79a99941767d9944b723c61](https://github.com/apache/shardingsphere/assets/97432411/fed1b723-fd01-4d0c-9575-7cd2cd17e2e1)
![29731ac545134b18f21f6da75229a91](https://github.com/apache/shardingsphere/assets/97432411/5da2ffc8-2ccf-4f9d-b547-0f741abb16de)

**Comment by sandynz** [comment]
Already fixed by #29418
