### ISSUE TITLE
Metadata rule can not be added

### ISSUE THREAD

**Issue by hhw3KevinHou** [apache/shardingsphere#29431]
## Bug Report
SHOW ENCRYPT RULES FROM encrypt_db;
Got：
![image](https://github.com/apache/shardingsphere/assets/14155363/0c1db779-3882-4832-bb4b-a27bd4b78d07)
Add a rule:
![image](https://github.com/apache/shardingsphere/assets/14155363/f3080250-e0d0-4925-a831-5b8ad05cd28a)

Again SHOW ENCRYPT RULES FROM encrypt_db;   
![image](https://github.com/apache/shardingsphere/assets/14155363/d87b1130-14a5-48f7-9542-a224c0fbb3ad)

where is my test1 rule? 
### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior

2 rules

### Actual behavior
Only 1 new rule.  Missing old rule.

**Comment by hhw3KevinHou** [comment]
If I DROP ENCRYPT RULE test;
Then create ENCRYPT RULE test,  'Duplicate' error will show up.   Why? I dropped it.  Can not understand coder's mind.

**Comment by zhaojinchao95** [comment]
@hhw3KevinHou Hi, this problem are fixed in master branch. you can try it

**Comment by hhw3KevinHou** [comment]
> @hhw3KevinHou Hi, this problem are fixed in master branch. you can try it

U did not test it.   Delete a rule -> add a rule -> 2 rules in mem -> restart -> the added one is missing

**Comment by RaigorJiang** [comment]
@hhw3KevinHou Hi, are you test with standalone mode?

**Comment by hhw3KevinHou** [comment]
> @hhw3KevinHou Hi, are you test with standalone mode?

yes.  I found the code is too complicated and dirty.  It would be easy if you use  cache and persist structure.  All data store in database and use cache to make it fast.   You can delete lots of code to make it neat.  Too may codes use to maintain config file and database synchronize and so many bugs in code.
