### ISSUE TITLE
Did the author forget to submit this package?

### ISSUE THREAD

**Issue by cactuer** [apache/shardingsphere#29436]
## Question

![image](https://github.com/apache/shardingsphere/assets/52022187/ed9fa22d-04c9-4e29-a5d2-1363826dc104)

This directory is missing in the code：org.apache.shardingsphere.sql.parser.autogen

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
Hi @cactuer, you can execute `mvn clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true` to generate these codes.

**Comment by cactuer** [comment]
Thanks to the author for the reply, the problem has been solved. Although an error was reported when executing this command in the end, the relevant code has been generated.
This is really amazing, this is my first time to generate code in this way, let me see how this is implemented, it is so interesting.
Finally, I hope the author can write this command in the document to help interested developers join the project faster.

**Comment by strongduanmu** [comment]
> Finally, I hope the author can write this command in the document to help interested developers join the project faster.

You can get this command in this doc - https://shardingsphere.apache.org/community/en/involved/contribute/contributor/.

**Comment by cactuer** [comment]
thanksThank you, I didn’t read the documentation carefully.
