### ISSUE TITLE
Add some keywords in the "CREATE TABLE" in ORACLE.

### ISSUE THREAD

**Issue by ilyasahsan123** [apache/shardingsphere#29489]
## Feature Request

Add some keywords in the "CREATE TABLE".
The keywords are below: 
- CREATE TABLE t_log(id int PRIMARY KEY, status varchar(10)) NO MEMOPTIMIZE FOR READ
- CREATE TABLE t_log(id int PRIMARY KEY, status varchar(10)) NO MEMOPTIMIZE FOR WRITE

Changes proposed in this pull request:
- support for SQL “creating table” with keywords: NO MEMOPTIMIZE.

**Comment by strongduanmu** [comment]
Hi @ilyasahsan123, thank you very much for your contribution. Welcome to the ShardingSphere community as a contributor and look forward to getting more involved in SQL parsing tasks.
