### ISSUE TITLE
sharding-Jdbc  Standalone mode druid does not take effect but hikari

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#29496]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
sharding-Jdbc  Standalone mode druid does not take effect but hikari
### Actual behavior
Standalone mode druid

**Comment by linghengqian** [comment]
- Verified at https://github.com/apache/shardingsphere/issues/21211#issuecomment-1932123528 and I don't think there is an issue. 
- Please use shardingsphere 5.4.2-SNAPSHOT to provide unit tests.

**Comment by linghengqian** [comment]
- Due to lack of reproducible unit tests, I'm closing this issue.
