### ISSUE TITLE
The number of physical tables which sync is greater than CDC's WORK_ THREAD , waiting time too long.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29506]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (#29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy /CDC server

### Expected behavior
The number of physical tables which sync is greater than CDC's WORK_ THREAD , waiting time is normal.

### Actual behavior
The number of physical tables which sync is greater than CDC's WORK_ THREAD , waiting time too long.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![2b3f3f4ae94ff7fb308be47cd561e36](https://github.com/apache/shardingsphere/assets/97432411/c23af27f-f138-4cf3-83a5-8e525eed19ad)

**Comment by azexcy** [comment]
It's improved at https://github.com/apache/shardingsphere/pull/29453
