### ISSUE TITLE
nacos cluster mode report an error

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#29502]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Actual behavior
Console output only：
com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Starting...

Do you need any more configuration?

application.properties:
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yaml

sharding.yaml:
mode:
type: Cluster
repository:
type: nacos
props:
namespace: xxxx
server-lists: xxxx:8848
username: xxx
password: xxx
retryIntervalMilliseconds: 500
timeToLiveSeconds: 60

**Comment by terrymanu** [comment]
Cannot support nacos
