### ISSUE TITLE
When the CDC is incrementally synchronized，If xa transactions are large and the read time exceeds 300ms, it will cause transaction truncation.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#29508]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
/usr/bin/java
we find java version: java8, full_version=1.8.0_242, full_path=/usr/bin/java
ShardingSphere-5.4.2-SNAPSHOT
Commit ID: dirty-dc9d8bef0e5696e38b9dec665fb4a39cd29c1062
Commit Message: Improve stop_time display at show streaming list of CDC (https://github.com/apache/shardingsphere/pull/29090)
Branch: master
Build time: 2022-12-12T03:18:10+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy /CDC server

### Expected behavior
When the CDC is incrementally synchronized，If xa transactions are large and the read time exceeds 300ms, it will not
cause transaction truncation.

### Actual behavior
When the CDC is incrementally synchronized，If xa transactions are large and the read time exceeds 300ms, it will cause transaction truncation.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
6000 records in one transaction

![image](https://github.com/apache/shardingsphere/assets/97432411/fc12ef8d-1f5b-4945-bf04-d55bf66ecc83)

**Comment by azexcy** [comment]
CDC server couldn't wait too long, If there is more than a certain delay in reading data from the slot, XA transactions maybe truncated
