### ISSUE TITLE
Syntax parsing tree Outer join syntax parsing error

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#29504]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy     Oracle syntax parsing issues
### Expected behavior
Normal parsing
### Actual behavior
When select does not add a table alias, left join / right join will be parsed into inner join, but adding an alias will not cause parsing errors.
Without adding table alias
![0362e7d286df7b0d6745631ff7bb171](https://github.com/apache/shardingsphere/assets/62044303/b6b941c6-b3b3-4eaf-8609-cfad22057132)
When adding a table alias
![669889b90672a670ef34daa1f5488de](https://github.com/apache/shardingsphere/assets/62044303/220d2ff7-12af-4076-91f3-dbef517c6de7)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL without table alias
SELECT *
FROM table1
LEFT JOIN table2 ON table1.id = table2.id

SQL with table alias
SELECT *
FROM table1 t1
LEFT JOIN table2 t2 ON t1.id = t2.id

**Comment by zihaoAK47** [comment]
@TherChenYang Assigned

**Comment by Y-sir** [comment]
@TherChenYang  is also a full join bug

**Comment by Y-sir** [comment]
@TherChenYang There is also a full join bug

**Comment by Y-sir** [comment]
@TherChenYang SELECT
    select_list
FROM
    T1
FULL JOIN T2 ON join_condition;

**Comment by Y-sir** [comment]
@TherChenYang Would you like me to submit another issue

**Comment by Y-sir** [comment]
@TherChenYang Got it. Thank you.
