### ISSUE TITLE
DistSQL about ENCRYPT RULE can not work, need recode

### ISSUE THREAD

**Issue by hhw3KevinHou** [apache/shardingsphere#29510]
## Bug Report
 CREATE/alter/drop/show   ENCRYPT RULE   are all wrong output.   Some result wrong, Some persist wrong.   Author need recode DistSQL.

### Which version of ShardingSphere did you use?
5.4.1 with Mysql repository.
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Like SQL insert ,update ,delete behavior.
### Actual behavior
CREATE/alter/drop/show   ENCRYPT RULE      are all wrong.   Some result error, Some persist error.   Author need recode DistSQL.
 
Metadata in memory and Mysql are not consist.

I have cost a whole week to confirm this.

**Comment by zhaojinchao95** [comment]
Can you describe your detail operation?

**Comment by hhw3KevinHou** [comment]
Create  ENCRYPT RULE bug see #29431. 
Alter bug: alter a encrypte rule->restart->alter no effect.
Drop bug: drop a rule -> show  ENCRYPT RULE -> other rules are all dropped  (reason is rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass()));)

**Comment by hhw3KevinHou** [comment]
> Create ENCRYPT RULE bug see #29431.
> Alter bug: alter a encrypte rule->restart->alter no effect.
> Drop bug: drop a rule -> show ENCRYPT RULE -> other rules are all dropped (reason is rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass()));)

Create ENCRYPT RULE bug see https://github.com/apache/shardingsphere/issues/29431.
Alter bug: alter a encrypte rule->restart->alter no effect.
Drop bug: drop a rule -> show ENCRYPT RULE -> other rules are all dropped (reason is rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass()));)

**Comment by hhw3KevinHou** [comment]
> Can you describe your detail operation?

Create ENCRYPT RULE bug see https://github.com/apache/shardingsphere/issues/29431.
Alter bug: alter a encrypte rule->restart->alter no effect.
Drop bug: drop a rule -> show ENCRYPT RULE -> other rules are all dropped (reason is rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass()));)

**Comment by RaigorJiang** [comment]
@hhw3KevinHou Hi, are you test with standalone mode, and the persist repository is MySQL?
