### ISSUE TITLE
Remove Redundancy in Some Specifications Parser in Oracle

### ISSUE THREAD

**Issue by ilyasahsan123** [apache/shardingsphere#29559]
## Feature Request
Remove Redundancy in Some Specifications Parser in Oracle

### Is your feature request related to a problem?
N/A

### Describe the feature you would like.
Remove redundancy usage of Usable and Invalidation specifications.

**Comment by ilyasahsan123** [comment]
hi, @strongduanmu, another minors nitpick before holiday, can you please take another look?

**Comment by strongduanmu** [comment]
> hi, @strongduanmu, another minors nitpick before holiday, can you please take another look?

Of course, and thank you for your work.
