### ISSUE TITLE
ShardingShper 5.4.1 Why did I only configure 4 data sources, but hikari created 6 connection pools

### ISSUE THREAD

**Issue by 1ancElot** [apache/shardingsphere#29576]
The remaining two connection pools use default configurations, and my application requests through the default configured connection pools

**Comment by 1ancElot** [comment]
dataSources:
  db0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/db0?useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 28000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 500
    minPoolSize: 100
  db1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/db1?useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 28000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 500
    minPoolSize: 100
  db2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/db2?useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 28000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 500
    minPoolSize: 100
  db3:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/db3?useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 28000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 500
    minPoolSize: 100
props:
  sql-show: false
  max-connections-size-per-query: 4

**Comment by RaigorJiang** [comment]
@1ancElot 
Is your application a springboot project?
In this case, the application accesses `ShardingSphereDataSource` through the connection pool, and there will be additional connection pool objects.
