### ISSUE TITLE
Add test cases for authenticators & defaultAuthenticator

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#29581]
Now there is no test cases for authenticators and defaultAuthenticator, please add test cases.

- [ ] swapper test case (in `YamlAuthorityRuleConfigurationSwapperTest` and `NewYamlAuthorityRuleConfigurationSwapperTest`)
- [ ] build test case (in `DefaultAuthorityRuleConfigurationBuilderTest`)
- [ ] may be some other cases (refer to #24313)

**Comment by yx9o** [comment]
Hi @RaigorJiang  I can.

**Comment by RaigorJiang** [comment]
@yx9o Thank you~
