### ISSUE TITLE
Oracle insert into values ​​(), (), (); Syntax parsing bug of multiple values

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#29591]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy and Oracle DataBase
### Expected behavior
Normal parsing insert into values ​​​​(), (), (); Syntax;
like mysql; The analysis is as follows;
![image](https://github.com/apache/shardingsphere/assets/62044303/befaa489-2d23-41fd-ab98-0be6dda38329)

### Actual behavior
The analysis of oracle is as follows;

![image](https://github.com/apache/shardingsphere/assets/62044303/280b527a-6c1b-4ed3-bf8d-7876c95fe3da)

You can see that oracle only generated one assignmentValues ​​branch
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
INSERT INTO employees (employee_id, employee_name, salary) VALUES
(1, 'John Doe', 50000),
(2, 'Jane Smith', 60000),
(3, 'Bob Johnson', 55000);

**Comment by strongduanmu** [comment]
Hi @Y-sir, can you test this sql with original oracle database? Besides, Proxy does not support Oracle database now.

**Comment by Y-sir** [comment]
@strongduanmu Are you saying that I use shardingproxy to connect to Oracle and send this SQL for testing?

**Comment by Y-sir** [comment]
@TherChenYang Take a look at this parsing problem

**Comment by strongduanmu** [comment]
> @strongduanmu Are you saying that I use shardingproxy to connect to Oracle and send this SQL for testing?

I mean you need to make sure this is a correct oracle statement.

**Comment by Y-sir** [comment]
> > @strongduanmu Are you saying that I use shardingproxy to connect to Oracle and send this SQL for testing?
> 
> I mean you need to make sure this is a correct oracle statement.

Hello, Oracle supports this syntax format.

**Comment by strongduanmu** [comment]
You can show the orginal oracle doc about this sytax. In my impression, Oracle does not support this statement.

**Comment by Y-sir** [comment]
> @Y-sir You can refer to here, Oracle does not support batch insertion like MySQL. [link](https://docs.oracle.com/database/121/SQLRF/statements_9015.htm)
> 
> ```
> INSERT ALL 
> INTO my_table(field_1,field_2) VALUES (value_1,value_2) 
> INTO my_table(field_1,field_2) VALUES (value_3,value_4) 
> INTO my_table(field_1,field_2) VALUES (value_5,value_6)
> SELECT 1 FROM DUAL;
> ```

Okay, thank you. Does the current Oracle grammar analysis book support the grammar you posted?

**Comment by strongduanmu** [comment]
Since oracle does not support `insert into values ​​(), (), ();` sytax, I will close this issue.
