### ISSUE TITLE
why metadata persistence is requried? its not make sense for standalone mode

### ISSUE THREAD

**Issue by reidzhou** [apache/shardingsphere#29614]
actually, standalone mode is often used in demo or dev env, metadata persistence is not unnecessary, or maybe shardingsphere can provide a memory implentment. 
<img width="1095" alt="image" src="https://github.com/apache/shardingsphere/assets/34478469/9e6aadc1-3f99-4f38-8a96-a47010a643d2">

**Comment by RaigorJiang** [comment]
The default mode is use H2 to persist metadata in memory and just connect to H2 through JDBC

**Comment by hhw3KevinHou** [comment]
I found big bug of metadata persist function, lots of garbage. Mysql metadata is useful to test metadata function.

**Comment by RaigorJiang** [comment]
> I found big bug of metadata persist function, lots of garbage. Mysql metadata is useful to test metadata function.

@hhw3KevinHou Can you describe the detail?
