### ISSUE TITLE
Proxy startup exception with cluster mode

### ISSUE THREAD

**Issue by peixingzhe** [apache/shardingsphere#29624]
### Which version of ShardingSphere did you use?
5.3.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior
The following exception occurs when the proxy startup:
<img width="777" alt="f86a8f23e594fbf64ae49ff92e2a0cb" src="https://github.com/apache/shardingsphere/assets/46043280/24322834-1330-4abb-9c2c-a4b456d5b79b">

### Reason analyze (If you can)
Maybe zookeeper is listening to too many znodes?

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
About 200 tables are configured, of which 100 are sharding table, there are 32 databases, like `ds_${0..31}.t_test`.

**Comment by peixingzhe** [comment]
see:
https://github.com/apache/curator/commit/51483adb1d1dd3e43812b5d0ec7c03b6d1d05c7c
https://issues.apache.org/jira/browse/CURATOR-690

**Comment by peixingzhe** [comment]
Resolution: Replace the default with a new version(5.5.1 or higher) of curator.

**Comment by linghengqian** [comment]
- Fixed by #29795 .
