### ISSUE TITLE
Why does HikariCP default to reading the jdbc of slave MySQL?

### ISSUE THREAD

**Issue by Python-IBM** [apache/shardingsphere#29661]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 

### Expected behavior
I expect HikariCP to obtain the jdbcurl of the main MySQL

### Actual behavior
HikariCP default to reading the jdbc of slave MySQL

### Reason analyze (If you can)
**Hikari generates 3 connection pools：**
pool-1:  **spring.datasource.url: jdbc:shardingsphere:apollo:account-jdbc**
pool-2:  **dataSources.ds0.jdbcUrl: jdbc:mysql://192.168.1.101:3306/db_account**
pool-3:  **dataSources.ds1.jdbcUrl: jdbc:mysql://192.168.1.101:3306/db_account_slave**

**HikariDataSource always reads the jdbcurl of pool-3 as the final result.**

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
(1) **sharding rule configuration**
![image](https://github.com/apache/shardingsphere/assets/33851767/387f6891-bf9e-4b93-9353-a28ccdbae113)

(2)**Causing the registration of RM resources in seata to always be the jdbcUrl of slave mysql**
![image](https://github.com/apache/shardingsphere/assets/33851767/2cd6d246-3df2-4a31-89d7-22ecea903cdd)

**Comment by RaigorJiang** [comment]
@Python-IBM 
In a readwrite splitting scenario, the read query is routed to the read data source by default. 
If you want to query from the write data source, you can start a transaction.

**Comment by Python-IBM** [comment]
> In a readwrite splitting scenario, the read query is routed to the read data source by default.
> If you want to query from the write data source, you can start a transaction.

What should I do to support it? Is it configured in the shardingsphere jdbc configuration file?

**Comment by RaigorJiang** [comment]
This is the application scenario of the readwrite-splitting. 
If you only want to read the primary data source, why you config the readwrite-splitting rule?

https://shardingsphere.apache.org/document/5.4.1/en/features/readwrite-splitting/

#### How to start transaction in readwrite-splitting?
Just use Java standard ways, such as `setAutoCommit = false`, or use the annotation `@Transactional`
