### ISSUE TITLE
Add DistSQLSegment

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#29665]
There are many DistSQL-related segment classes now, and they directly inherit interface `ASTNode`, which is inappropriate.

<img width="527" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/6e557de6-967d-4776-b476-80b963ca09e2">

We should add `DistSQLSegment`, which is the same level as `SQLSegment`, and let DistSQL-related segment classes inherit `DistSQLSegment`.

#### Difference
`DistSQLSegment` does not need to provide `getStartIndex()` and `getStopIndex()` methods.

**Comment by yx9o** [comment]
Hi @RaigorJiang  I can.
