### ISSUE TITLE
About postgresql row data message return problem

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#29683]
![image](https://github.com/apache/shardingsphere/assets/62044303/63b0da1b-46f9-4429-9338-d4f496fcdb2b)

My table has a total of 1,000 rows of data. How does shardingproxy operate to split data packets of the same size and return them?

Where is the specific code?

**Comment by terrymanu** [comment]
I apologize, but your description is too brief for me to understand your intent. Could you please clarify your issue and purpose more clearly?
