### ISSUE TITLE
how to springboot3 integration with shardingsphere 5

### ISSUE THREAD

**Issue by xuqife** [apache/shardingsphere#29687]
Our company recently upgraded to jdk17 and shardingsphere 5, but your official website did not provide a springboot start for 5.0, and also, shardingsphere 5.0 did not integrate with nacos, so we hope you can provide an official solution

**Comment by zhaojinchao95** [comment]
You can use ShardingSphereDriver, it's not affected by the springboot version.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
