### ISSUE TITLE
Table or view does not exist

### ISSUE THREAD

**Issue by About-Gleaning** [apache/shardingsphere#29695]
## Question
my config
```
@Bean(name = "shardingDataSource")
public DataSource shardingDataSource(@Qualifier("dataSource") DataSource dataSource)throws Exception {
        // 配置真实数据源
        Map<String, DataSource> dataSourceMap = new HashMap<>(2);
        dataSourceMap.put("ds0", dataSource);
        DataSource shardingDataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Arrays.asList(), new Properties());
        return shardingDataSource;
}
```
 run application error info :
 Table or view *** does not exist.

add code: 
`SingleRuleConfiguration ruleConfig = new SingleRuleConfiguration(Lists.newArrayList("ds0.supplier_channel"), "ds0");`

its work

why?

**Comment by About-Gleaning** [comment]
throw error code: SimpleTableSegmentBinder.checkTableExists function
```
ShardingSpherePreconditions.checkState(statementBinderContext.getMetaData().containsDatabase(databaseName)
                && statementBinderContext.getMetaData().getDatabase(databaseName).containsSchema(schemaName)
                && statementBinderContext.getMetaData().getDatabase(databaseName).getSchema(schemaName).containsTable(tableName),
                () -> new TableNotExistsException(tableName));
```
metadata.databse.logic_db have not simple table name
![截屏2024-01-11 11 51 06](https://github.com/apache/shardingsphere/assets/26588825/2473fbb8-e550-483d-bf6e-67bffecbe566)

**Comment by RaigorJiang** [comment]
@About-Gleaning 
If a table does not have any rules, ShardingSphere will not load it into metadata.
The purpose of this is to solve the problem of slow loading when there are too many irrelevant tables in the DB.

If all single tables need to be loaded, you can use `*.*`
https://shardingsphere.apache.org/document/current/en/features/sharding/concept/#single-table
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/

**Comment by Holmesus** [comment]
发现有多个类似的issue，未分片的表的sql可以不做任何处理吗？现在不load未分片的表，运行时却报错，这个优化等于没优化呀
