### ISSUE TITLE
java.lang.IllegalArgumentException: Type is required.

### ISSUE THREAD

**Issue by yanghtGithub** [apache/shardingsphere#29699]
![image](https://github.com/apache/shardingsphere/assets/72773874/1d6820d6-2894-452f-91a8-5731aada6321)
![image](https://github.com/apache/shardingsphere/assets/72773874/d0d426da-bda5-4c7e-bd44-1c264d2934cb)

![image](https://github.com/apache/shardingsphere/assets/72773874/9d5c0a0a-80ca-47c7-862f-85fa4ff8b874)

**Comment by yanghtGithub** [comment]
i dont know how to resolve it

Which one configuration is wrong

**Comment by RaigorJiang** [comment]
Hi @yanghtGithub 
The log shows that `type`  is missing in the algorithm configuration. Please provide the complete rule configuration

**Comment by ferylork** [comment]
这个问题为什么没有解决就关闭了？
同版本5.2.1，把sharding移动到和datasource同一级就不会报错了
按要求（和提示）是在rules下，但是放rules下就报这个错

**Comment by linghengqian** [comment]
> 这个问题为什么没有解决就关闭了？

@ferylork 

- **The first reason is that the issue author has not responded.** Lack of communication will not solve anything. A GitHub actions job is always monitoring such issues with missing responses and adding issue tags.

- Secondly, the issue lacks a reproducible unit test, and the screenshot lacks more specific information. And the spring boot starter has been removed in a series of refactorings. 

> 同版本5.2.1，把sharding移动到和datasource同一级就不会报错了
> 按要求（和提示）是在rules下，但是放rules下就报这个错

- If you encounter such problems, you should bring unit tests that use h2database or testcontainers-java to write the original data source, and open a new issue.

**Comment by ferylork** [comment]
I just checked the source code and it's not related to shardingjdbc. It's a problem with Spring parsing the configuration file
The field name (key) of yml does not support underline_
The name of the sharding algorithm contains an underline

```
shardingAlgorithms:
  online_task_image_defect_inline:   //contains underline, illegal, so the type field cannot be obtained, returning null
  type: INLINE
```
