### ISSUE TITLE
Does shardingproxy have plans to support the domestic Dameng database protocol?

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#29727]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
shardingproxy   protocol
### Describe the feature you would like.
Does shardingproxy have plans to support the domestic Dameng database protocol? 
Recently, the company needs to connect to the domestic Dameng database. If you are studying a database protocol that is not open source, do you have any suggestions, such as how to study it, how to adapt the protocol, etc.? I hope anyone with relevant experience can give me some advice, thank you.

**Comment by RaigorJiang** [comment]
Unfortunately, ShardingSphere-Proxy cannot implement closed-source database protocols, and doing so would bring legal risks.
