### ISSUE TITLE
shardingsphere在mybatis中解析子查询中的表失败

### ISSUE THREAD

**Issue by Sumuxi9797926** [apache/shardingsphere#29788]
SELECT
	* 
FROM
	order_info_202401 main 
WHERE
	EXISTS (
	SELECT
		1 
	FROM
		order_item sub -- 应该为order_item_202401
	WHERE
		sub.order_no = main.order_no 
		AND (
			sub.sku_code LIKE concat( '%', '酒精', '%' ) 
		OR sub.product_name LIKE concat( '%', '酒精', '%' ))) 
	AND main.del_flag = 0 
	AND main.wid = 200 
	AND main.create_date BETWEEN '2024-01-05 00:00:00' 
	AND '2024-01-17 23:59:59';这个sql中order_item解析不出来，order_info和order_item都是根据时间分的表，有大佬知道如何解答么？

**Comment by Sumuxi9797926** [comment]
<select id="queryMallOrderInfoByPage" parameterType="com.frxs.fh.shopping.logistics.vo.req.MallOrderReq" resultMap="BaseResultMap">
        SELECT
            <include refid="Base_Column_List"/>
        FROM
            order_info main
        <where>
            <if test="mallOrderReq.skuOrProductName != null and mallOrderReq.skuOrProductName != ''">
                EXISTS ( SELECT 1 FROM order_item sub WHERE sub.order_no = main.order_no AND ( sub.sku_code LIKE concat('%', #{mallOrderReq.skuOrProductName}, '%') OR sub.product_name LIKE concat('%', #{mallOrderReq.skuOrProductName}, '%') ) ) AND
            </if>
                main.del_flag = 0 AND main.wid = #{mallOrderReq.wid}
            <if test="mallOrderReq.orderNo != null and mallOrderReq.orderNo != ''">
                    AND main.order_no = #{mallOrderReq.orderNo}
            </if>
            <if test="mallOrderReq.receiveAddr != null and mallOrderReq.receiveAddr != ''">
                    AND main.receive_addr LIKE concat('%', #{mallOrderReq.receiveAddr}, '%')
            </if>
            <if test="mallOrderReq.orderStatus != null and mallOrderReq.orderStatus != ''">
                    AND main.order_status = #{mallOrderReq.orderStatus}
            </if>
            <if test="mallOrderReq.orderStatusList != null and mallOrderReq.orderStatusList.size() > 0">
                AND main.order_status IN
                <foreach collection="mallOrderReq.orderStatusList" separator="," open="(" close=")" item="item">
                    #{item}
                </foreach>
            </if>
            <if test="mallOrderReq.userNameOrMobile != null and mallOrderReq.userNameOrMobile != ''">
                    AND ( main.receive_name LIKE concat('%', #{mallOrderReq.userNameOrMobile}, '%') OR main.receive_phone LIKE concat('%', #{mallOrderReq.userNameOrMobile}, '%') )
            </if>
            <choose>
                <when test="mallOrderReq.startTime != null and mallOrderReq.startTime != '' and mallOrderReq.endTime != null and mallOrderReq.endTime != ''">
                    AND main.create_date BETWEEN #{mallOrderReq.startTime} AND #{mallOrderReq.endTime}
                </when>
                <otherwise>
                    <if test="mallOrderReq.startTime != null and mallOrderReq.startTime != ''">
                        AND main.create_date > #{mallOrderReq.startTime}
                    </if>
                    <if test="mallOrderReq.endTime != null and mallOrderReq.endTime != ''">
                        AND main.create_date &lt; #{mallOrderReq.endTime}
                    </if>
                </otherwise>
            </choose>
        </where>
        ORDER BY main.create_date DESC
    </select>这是xml标签

**Comment by RaigorJiang** [comment]
@Sumuxi9797926 
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
please translate the title and comment, thank you!
