### ISSUE TITLE
Select insert parsing in mysql and sqlServer

### ISSUE THREAD

**Issue by TherChenYang** [apache/shardingsphere#29823]
## Question

In the process of writing the SQL Server parse select into statement，the required parsing syntax is as follows
<img width="705" alt="image" src="https://github.com/apache/shardingsphere/assets/124348939/90405f7d-23d3-4d04-8fcf-ab6764b09836">
I found that there is no corresponding intoSegment in SelectStatement.Then I looked at the parsing of Mysql, and I found that mysql skipped this part of the parsing work,You can see that selectIntoExpression was skipped during the visit,I am very confused about this.I wonder if this part of the content does not need to be analyzed?
![image](https://github.com/apache/shardingsphere/assets/124348939/e927d8d3-399b-47b0-91a6-7efe41f0a0f8)
![image](https://github.com/apache/shardingsphere/assets/124348939/4a4657f7-7e6c-4362-98fb-aa95caf0b129)

**Comment by strongduanmu** [comment]
@TherChenYang Thank you very much for your suggestion. I also found this problem recently. My suggestion is to add the parsing of `INTO TABLE`. At present, ShardingSphere is mainly used to enhance the processing of database, table, column, index and other objects, which need to be correctly parsed out before we can continuously improve these features.

**Comment by strongduanmu** [comment]
@TherChenYang Good job, the survey is so detailed that I think we can parse the into table into the Select Statement subclasses corresponding to each dialect.
