### ISSUE TITLE
sharding-proxy date query issue

### ISSUE THREAD

**Issue by tangzhihong** [apache/shardingsphere#29826]
I inserted a data entry into the MYSQL database using an SQL statement, where one of the fields is of type datatime with a value of 1991-04-14 02:00:00. However, the query reported an Unknown exception: HOUR_ OF_ Day: 2->3, at which point the URL of the proxy is set to: jdbc: mysql://192.168.10.4:3306/db_test?useSSL=false

When I added serverTimezone=GMT% 2B8 to the URL of the proxy, but found that it was 1991-04-14 03:00:00 from the sharing proxy

But the results I found from the physical database are all 1991-04-14 02:00:00

May I ask how to solve this problem

**Comment by LiberteKoder** [comment]
This is a time zone problem, I've encountered similar ones before, and the solution is to use this function to convert the time zone 
` convert_tz`
