### ISSUE TITLE
Add more details for SchemaMetaDataReviseEngineTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#29856]
The test coverage are not enough. Please add fixture for MetaDataReviseEntry

**Comment by KonarzewskiP** [comment]
Hi @terrymanu 

I would like to take this task, please assign it to me.

**Comment by dr-divago** [comment]
Hi @terrymanu is this issue still open? @KonarzewskiP are you still working on it?

**Comment by KonarzewskiP** [comment]
@dr-divago No, I am not working on it at the moment. Please go for it if you want.

**Comment by dr-divago** [comment]
@terrymanu  can you assign to me? I would like to work on it

**Comment by dr-divago** [comment]
Hi @terrymanu , I made a draft for increasing the coverage. I am not sure if the correct approach, please have a look

**Comment by traitsisgiorgos** [comment]
hi, is the issue still running?

**Comment by dr-divago** [comment]
@traitsisgiorgos there is a PR already waiting for review
