### ISSUE TITLE
When both BROADCAST and READWRITE_SPLITTING are used, ddl and insert is routed to all datasource

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#29867]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.2 
5.4.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Both ShardingSphere-JDBC and ShardingSphere-Proxy
### Expected behavior
ddl and insert is routed to write DataSource

### Actual behavior
ddl and insert is routed to all datasource
<img width="1764" alt="image" src="https://github.com/apache/shardingsphere/assets/16568907/c33acab5-bed7-44a3-aa5b-d0c55ad749ac">
<img width="1522" alt="image" src="https://github.com/apache/shardingsphere/assets/16568907/b6bb484b-f880-477c-8671-761cc17c36d8">
### Reason analyze (If you can)
BROADCAST rule getAvailableDataSourceNames by dataSourcesMap
Unable to handle raw data source name in READWRITE_SPLITTING

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
distsql:
create database demo;
use demo;
REGISTER STORAGE UNIT master (
    HOST="",  //mysql host
    PORT=, //mysql port
    DB="", //mysql db
    USER="", //mysql user
    PASSWORD="" //mysql password
);

REGISTER STORAGE UNIT slave1 (
    HOST="",  //mysql host
    PORT=, //mysql port
    DB="", //mysql db
    USER="", //mysql user
    PASSWORD="" //mysql password
);

REGISTER STORAGE UNIT slave2 (
    HOST="",  //mysql host
    PORT=, //mysql port
    DB="", //mysql db
    USER="", //mysql user
    PASSWORD="" //mysql password
);

CREATE BROADCAST TABLE RULE IF NOT EXISTS t_province;

CREATE READWRITE_SPLITTING RULE IF NOT EXISTS ms_group_0 (
    WRITE_STORAGE_UNIT=master,
    READ_STORAGE_UNITS(slave1, slave2),
    TYPE(NAME="random")
);

create table t_province(id bigint primary key auto_increment, name varchar(100) not null, code varchar(50) not null);
insert into t_province(name, code) value ('test', 'test')

**Comment by strongduanmu** [comment]
@SirMin Thank you for your feedback, I will investigate this problem.

**Comment by strongduanmu** [comment]
This bug has been fixed in #29025, you can wait for the next version.
