### ISSUE TITLE
Does ShardingSphere-proxy support oceanbase?

### ISSUE THREAD

**Issue by cbzgit** [apache/shardingsphere#29862]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by RaigorJiang** [comment]
OceanBase seems to have a MySQL compatibility mode. If you use the MySQL compatibility mode and connect through the MySQL protocol, it is OK.

**Comment by cbzgit** [comment]
Good,Thanks!
