### ISSUE TITLE
Proxy  because "this.xaTransactionManagerProvider" is null'

### ISSUE THREAD

**Issue by cookiejoo** [apache/shardingsphere#29904]
## Bug Report

proxy 5.4

use python conn proxy database error

################################################

import pymysql

conn = pymysql.connect(host='localhost', port=80, user='qoa_sharding', password='xxxx', database='xxx_sharding')
cursor = conn.cursor()

try:
    sql = "SELECT * FROM  test_ss  WHERE  cust_no = 'xxxx'"
    cursor.execute(sql)

    results = cursor.fetchall()

    for row in results:
        print(row)

except Exception as e:
    print("Error:", str(e))
finally:
    cursor.close()
    conn.close()

############################################################

Error: (30000, 'Unknown exception: Cannot invoke "org.apache.shardingsphere.transaction.xa.spi.XATransactionManagerProvider.getTransactionManager()" because "this.xaTransactionManagerProvider" is null')

#############################################################
but use java jbdc conn this database is success。

**Comment by zhaojinchao95** [comment]
Try open transaction configuration.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
