### ISSUE TITLE
Why is cluster mode recommended when using shardingsphere jdbc?

### ISSUE THREAD

**Issue by tarkgong** [apache/shardingsphere#29943]
Hello. 

We are trying to use shardingsphere-jdbc with springboot. Looking at the guide, cluster mode is recommended.
but from the guide document, there is no clear advantage of using cluster mode in shardingsphere-jdbc.
cluster mode only looks good in shardingsphere-porxy.

Please explain why cluster mode is recommended.

**Comment by zhaojinchao95** [comment]
Maybe you can know about the hybrid deployment model. https://shardingsphere.apache.org/document/current/cn/overview/
