### ISSUE TITLE
Some oracle parse test case failed when I add EOF in OracleStatement.g4

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#29988]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/pull/29985/files

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

All oracle parse test case execute successfully.

### Actual behavior

Some oracle parse test case failed when I add EOF in OracleStatement.g4

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Remove `IGNORE_TEST_CASES ` in [InternalSQLParserIT.java](https://github.com/apache/shardingsphere/pull/29985/files#diff-36708f24dea46e977dc7061f107a0a4d6ec85fe67d95b0dd064bc9210fb64639), and then execute InternalSQLParserIT.

**Comment by yydeng626** [comment]
please assign to me

**Comment by strongduanmu** [comment]
@yydeng626 Welcome, I will assign it to you.

**Comment by zhaojinchao95** [comment]
@yydeng626 Hi, the `5.5.0` version will be released next week. Can it be completed during this period?

**Comment by yydeng626** [comment]
@zhaojinchao95 Sure I can

**Comment by strongduanmu** [comment]
Since this issue contains many subtasks, I will move it to the next version - 5.5.1.
