### ISSUE TITLE
Refactor `show SPI implementations` DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30004]
Now we have some syntax for querying SPI implementations (https://github.com/apache/shardingsphere/issues/28984)

However, their implementation can be simplified. It is hoped that like `CountRuleStatement` and `RuleCountExecutor`, only a group of `statement` and `executor` can be used to implement functions, instead of adding many different `statements` and `executors`.

In addition, the `type` in result coulmns is useful to users (will be defined in the rules), while `name` and `class_path` are things that users do not need to care about, and we can remove them.

Maybe we can reuse `AlgorithmMetaDataQueryResultRows`, and refer to the output format of `SHOW MIGRATION CHECK ALGORITHMS`.

<img width="971" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/6ded33a9-e06e-4fa9-a3e3-165ec3120a66">

### task list
- [ ] refactor g4 and visitor
- [ ] refactor statement and executor
- [ ] update docs

**Comment by yx9o** [comment]
@RaigorJiang , I want to try.

**Comment by zhaojinchao95** [comment]
@yx9o Hi, the `5.5.0` version will be released next week. Can it be completed during this period?
