### ISSUE TITLE
SQL connection table query capitalization problem

### ISSUE THREAD

**Issue by yflytom** [apache/shardingsphere#30005]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingjdbc 5.4.1
### Expected behavior
When querying connected tables, the size is ignored and the custom algorithm can be entered normally.
连表查询时大小忽略可以正常进入自定义算法中

### Actual behavior
Capital letters cannot enter the custom sharding algorithm when querying connected tables.
连表查询时大写无法进入自定义分片算法中
### Reason analyze (If you can)
When querying a single table, uppercase letters can enter the custom sharding algorithm, but not after joining the tables. Is the case problem not ignored after joining the tables? My ability is limited and I haven’t checked the source code yet. Sorry.

单表查询时大写可以进入自定义分片算法，但是连表后就不行，是否连表后未忽略大小写问题，能力有限对源码还未查看，见谅
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![fcf66713d24e6bb5da516fc25f97a4e](https://github.com/apache/shardingsphere/assets/32268317/ac128e43-50a8-4f7a-a7dc-edf85847c6b7)

![e5d1e84c27909b1258f3d23cb046e9e](https://github.com/apache/shardingsphere/assets/32268317/76ff6713-b9ab-4b79-930f-88f77ecb7cfb)

### Example codes for reproduce this issue (such as a github link).
https://github.com/yflytom/sharding-bug-demo-master.git

**Comment by strongduanmu** [comment]
@yflytom Thank you for your feedback, I will investigate this issue.

**Comment by xiohuchi** [comment]
> ## Bug Report
> **For English only**, other languages will not accept.
> 
> Before report a bug, make sure you have:
> 
> * Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
> * Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
> 
> Please pay attention on issues you submitted, because we maybe need more details. If no response anymore and we cannot reproduce it on current information, we will **close it**.
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### Which version of ShardingSphere did you use?
> ### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
> shardingjdbc 5.4.1
> 
> ### Expected behavior
> When querying connected tables, the size is ignored and the custom algorithm can be entered normally. 连表查询时大小忽略可以正常进入自定义算法中
> 
> ### Actual behavior
> Capital letters cannot enter the custom sharding algorithm when querying connected tables. 连表查询时大写无法进入自定义分片算法中
> 
> ### Reason analyze (If you can)
> When querying a single table, uppercase letters can enter the custom sharding algorithm, but not after joining the tables. Is the case problem not ignored after joining the tables? My ability is limited and I haven’t checked the source code yet. Sorry.
> 
> 单表查询时大写可以进入自定义分片算法，但是连表后就不行，是否连表后未忽略大小写问题，能力有限对源码还未查看，见谅
> 
> ### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
> ![fcf66713d24e6bb5da516fc25f97a4e](https://private-user-images.githubusercontent.com/32268317/302241641-ac128e43-50a8-4f7a-a7dc-edf85847c6b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzcyOTcsIm5iZiI6MTcwODIzNjk5NywicGF0aCI6Ii8zMjI2ODMxNy8zMDIyNDE2NDEtYWMxMjhlNDMtNTBhOC00ZjdhLWE3ZGMtZWRmODU4NDdjNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NmZmOTZmZWIzODRmZWE3NmM5YWVkZmU4NjUxODMxODcwM2UwZDYzOTI2NzI4YTQxNjcyZmJiNmQ2MDdlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezAkpHp0nbb17TR421dcUCYZ_r687aG1xiRbAexKByU)
> 
> ![e5d1e84c27909b1258f3d23cb046e9e](https://private-user-images.githubusercontent.com/32268317/302241666-76ff6713-b9ab-4b79-930f-88f77ecb7cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzcyOTcsIm5iZiI6MTcwODIzNjk5NywicGF0aCI6Ii8zMjI2ODMxNy8zMDIyNDE2NjYtNzZmZjY3MTMtYjlhYi00Yjc5LTkzMGYtODhmNzdlY2I3Y2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjkyOTQ1NGIzYzNmYzA2YWZmMmVlYTdhY2I0MWNhMWFiM2ZmODkxZmJjZDUwMDY5Y2I3MTMzOWI4MGMwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jN2fnMk0VE3yOXCYsK2f7H2E_urXa6A2KUdGpb7Dc4g)
> 
> ### Example codes for reproduce this issue (such as a github link).
> https://github.com/yflytom/sharding-bug-demo-master.git

同问

**Comment by xiohuchi** [comment]
> ## Bug Report
> **For English only**, other languages will not accept.
> 
> Before report a bug, make sure you have:
> 
> * Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
> * Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
> 
> Please pay attention on issues you submitted, because we maybe need more details. If no response anymore and we cannot reproduce it on current information, we will **close it**.
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### Which version of ShardingSphere did you use?
> ### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
> shardingjdbc 5.4.1
> 
> ### Expected behavior
> When querying connected tables, the size is ignored and the custom algorithm can be entered normally. 连表查询时大小忽略可以正常进入自定义算法中
> 
> ### Actual behavior
> Capital letters cannot enter the custom sharding algorithm when querying connected tables. 连表查询时大写无法进入自定义分片算法中
> 
> ### Reason analyze (If you can)
> When querying a single table, uppercase letters can enter the custom sharding algorithm, but not after joining the tables. Is the case problem not ignored after joining the tables? My ability is limited and I haven’t checked the source code yet. Sorry.
> 
> 单表查询时大写可以进入自定义分片算法，但是连表后就不行，是否连表后未忽略大小写问题，能力有限对源码还未查看，见谅
> 
> ### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
> ![fcf66713d24e6bb5da516fc25f97a4e](https://private-user-images.githubusercontent.com/32268317/302241641-ac128e43-50a8-4f7a-a7dc-edf85847c6b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzcyOTcsIm5iZiI6MTcwODIzNjk5NywicGF0aCI6Ii8zMjI2ODMxNy8zMDIyNDE2NDEtYWMxMjhlNDMtNTBhOC00ZjdhLWE3ZGMtZWRmODU4NDdjNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NmZmOTZmZWIzODRmZWE3NmM5YWVkZmU4NjUxODMxODcwM2UwZDYzOTI2NzI4YTQxNjcyZmJiNmQ2MDdlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezAkpHp0nbb17TR421dcUCYZ_r687aG1xiRbAexKByU)
> 
> ![e5d1e84c27909b1258f3d23cb046e9e](https://private-user-images.githubusercontent.com/32268317/302241666-76ff6713-b9ab-4b79-930f-88f77ecb7cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzcyOTcsIm5iZiI6MTcwODIzNjk5NywicGF0aCI6Ii8zMjI2ODMxNy8zMDIyNDE2NjYtNzZmZjY3MTMtYjlhYi00Yjc5LTkzMGYtODhmNzdlY2I3Y2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYjkyOTQ1NGIzYzNmYzA2YWZmMmVlYTdhY2I0MWNhMWFiM2ZmODkxZmJjZDUwMDY5Y2I3MTMzOWI4MGMwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jN2fnMk0VE3yOXCYsK2f7H2E_urXa6A2KUdGpb7Dc4g)
> 
> ### Example codes for reproduce this issue (such as a github link).
> https://github.com/yflytom/sharding-bug-demo-master.git

同问
