### ISSUE TITLE
sqlfederation query error，java.lang.IllegalStateException: null

### ISSUE THREAD

**Issue by xljqq** [apache/shardingsphere#30012]
## Question
version：sharding-proxy-5.4.1
when i using sqlfederation query ，my sql is 
preview SELECT
	sku.sku_inst_id,
	oo.order_id,
	oo.order_no,
	oo.channel_id,
	oo.order_amount,
	oo.pay_amount,
	oo.target_object_id,
	oo.order_type,
	oo.oper_type,
	oo.STATUS,
	oo.status_date,
	oo.cust_id,
	oo.version,
	oo.accept_date,
	oo.create_date,
	oo.update_date,
	oo.complete_date,
	oo.remark,
	oo.out_order_id,
	oo.out_order_no 
FROM
	sku_inst sku
	LEFT JOIN order_item oi ON oi.order_item_id = sku.last_order_item_id
	LEFT JOIN online_order oo ON oo.order_id = oi.order_id 
WHERE
	sku.sku_inst_id=123456789111111111

it will throw Unkonw exception
![image](https://github.com/apache/shardingsphere/assets/5230461/88433aa5-d343-4423-b12b-387629fcc0d2)
but when i using  
preview SELECT
	sku.sku_inst_id,
	oo.order_id,
	oo.order_no,
	oo.channel_id,
	oo.order_amount,
	oo.pay_amount,
	oo.target_object_id,
	oo.order_type,
	oo.oper_type,
	oo.STATUS,
	oo.status_date,
	oo.cust_id,
	oo.version,
	oo.accept_date,
	oo.create_date,
	oo.update_date,
	oo.complete_date,
	oo.remark,
	oo.out_order_id,
	oo.out_order_no 
FROM
	sku_inst sku
	LEFT JOIN order_item oi ON oi.order_item_id = sku.last_order_item_id
	LEFT JOIN online_order oo ON oo.order_id = oi.order_id 
WHERE
	sku.sku_inst_id=‘123456789111111111’
it  can be execute。

my table  “sku_inst”  field  “sku_inst_id”   is  bigint。

**Comment by strongduanmu** [comment]
Hi @xljqq, thank you for your feedback. Can you provide more information to help us reproduce this exception?

**Comment by xljqq** [comment]
> Hi @xljqq, thank you for your feedback. Can you provide more information to help us reproduce this exception?

mysql table is  ：
sku_inst
![image](https://github.com/apache/shardingsphere/assets/5230461/7490a7ab-3c7f-4ccd-9738-31708b2bff58)
order_item
![image](https://github.com/apache/shardingsphere/assets/5230461/abd034b7-2bab-4d8f-b6b2-c5b279725f75)
online_order
![image](https://github.com/apache/shardingsphere/assets/5230461/aa65892d-0dfa-4888-b106-43f2881b6997)

my  sharding rule is:

#分库分表配置
rules:
- !SHARDING
  tables:
    online_order:
      actualDataNodes: online_write_ds_0.online_order_${0..11}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: online_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    customer:
      actualDataNodes: online_write_ds_0.customer_${0..11}
      tableStrategy:
        standard:
          shardingColumn: customer_id
          shardingAlgorithmName: customer_inline
      keyGenerateStrategy:
        column: customer_id
        keyGeneratorName: snowflake
    order_2_service:
      actualDataNodes: online_write_ds_0.order_2_service_${0..11}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: order_2_service_inline
      keyGenerateStrategy:
        column: o2s_id
        keyGeneratorName: snowflake
    order_item:
      actualDataNodes: online_write_ds_0.order_item_${0..11}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  bindingTables:
    - online_order,order_2_service,order_item
    - re_order_info,re_order_info_call_back
    - bsp_order_info
    - customer
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    online_order_inline:
      type: INLINE
      props:
        algorithm-expression: online_order_${order_id % 12}
    customer_inline:
      type: INLINE
      props:
        algorithm-expression: customer_${customer_id % 12}
    order_2_service_inline:
      type: INLINE
      props:
        algorithm-expression: order_2_service_${order_id % 12}
    order_item_inline:
      type: INLINE
      props:
        algorithm-expression: order_item_${order_id % 12}
#
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
    uuid:
      type: UUID         


#单表配置
- !SINGLE
  tables:
    - "*.*" # 加载全部单表
  defaultDataSource: online_write_ds_0 # 默认数据源，仅在执行 CREATE TABLE 创建单表时有效。缺失值为空，表示随机单播路由。
  
#读写分离配置
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      writeDataSourceName: online_write_ds_0
      readDataSourceNames:
        - online_read_ds_0
      loadBalancerName: random
      transactionalReadQueryStrategy: PRIMARY
  loadBalancers:
    random:
      type: RANDOM
