### ISSUE TITLE
Refactor DistSQLExecutor's test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#30083]
At present, we use the raw executor to perform assertion on test cases.
This approach is not accurate, as it requires manual injection of required dependencies such as database and rule.
I hope to use `DistSQLQueryExecuteEngine` and `DistSQLUpdateExecuteEngine`, which can create the executor through SPI, and automatically inject dependencies.

The sample please refer to `ShowAuthorityRuleExecutorTest`.

At present, a large number of `DistSQLExecutor` test cases need to be updated, and we sincerely seek the help of the community.

The test cases are:

- [x] ShowGlobalClockRuleExecutorTest
- [x] AlterGlobalClockRuleExecutorTest
- [x] ShowSingleTablesExecutorTest
- [x] ShowDefaultSingleTableStorageUnitExecutorTest
- [x] LoadSingleTableExecutorTest
- [x] SetDefaultSingleTableStorageUnitExecutorTest
- [x] ShowSQLFederationRuleExecutorTest
- [x] AlterSQLFederationRuleExecutorTest
- [x] ShowSQLParserRuleExecutorTest
- [x] AlterSQLParserRuleExecutorTest
- [x] ShowSQLTranslatorRuleExecutorTest
- [x] AlterSQLTranslatorRuleExecutorTest
- [x] ShowTransactionRuleExecutorTest
- [x] AlterTransactionRuleExecutorTest
- [x] ShowBroadcastTableRuleExecutorTest
- [x] CreateBroadcastTableRuleExecutorTest
- [x] DropBroadcastTableRuleExecutorTest
- [x] ShowEncryptRuleExecutorTest
- [x] AlterEncryptRuleExecutorTest
- [x] CreateEncryptRuleExecutorTest
- [x] DropEncryptRuleExecutorTest
- [x] ShowMaskRuleExecutorTest
- [x] AlterMaskRuleExecutorTest
- [x] CreateMaskRuleExecutorTest
- [x] DropMaskRuleExecutorTest
- [x] ShowReadwriteSplittingRuleExecutorTest
- [x] ShowStatusFromReadwriteSplittingRulesExecutorTest
- [x] ShowDefaultShadowAlgorithmExecutorTest
- [x] ShowShadowAlgorithmsExecutorTest
- [x] ShowShadowRuleExecutorTest
- [x] ShowShadowTableRulesExecutorTest
- [x] ShowDefaultShardingStrategyExecutorTest
- [x] ShowShardingAlgorithmExecutorTest
- [x] ShowShardingAuditorsExecutorTest
- [x] ShowShardingKeyGeneratorExecutorTest
- [x] ShowShardingTableNodesExecutorTest
- [x] ShowShardingTableReferenceRuleExecutorTest
- [x] ShowShardingTableRuleExecutorTest
- [x] ShowShardingTableRulesUsedAlgorithmExecutorTest
- [x] ShowShardingTableRulesUsedAuditorExecutorTest
- [x] ShowShardingTableRulesUsedKeyGeneratorExecutorTest
- [x] ShowUnusedShardingAlgorithmsExecutorTest
- [x] ShowUnusedShardingAuditorsExecutorTest
- [x] ShowUnusedShardingKeyGeneratorExecutorTest

**Comment by zzzk1** [comment]
hi, @terrymanu, I would like to get involved in the open source community starting with this issue

**Comment by terrymanu** [comment]
> hi, @terrymanu, I would like to get involved in the open source community starting with this issue

@zzzk1  Welcome onboard!

**Comment by VishalMCF** [comment]
@terrymanu How are we going to refactor AlterGlobalClockRuleExecutoreTest? I am asking this because in current test case we are using the method of buildToBeAlteredRuleConfiguration(sqlStatement). But the class DistSQLQueryExecuteEngine does not have any equivalent method. 
Also, I cannot use the execute query because the call to TypedSPI method fails. I know I am not able to put things correctly but it is because I am very much new to the project.

**Comment by zzzk1** [comment]
> DistSQLUpdateExecuteEngine

@VishalMCF pls look ```DistSQLUpdateExecuteEngine```

**Comment by VishalMCF** [comment]
@zzzk1 Thank you so much. Are you still working on the issue? If yes can I just create a PR for AlterGlobalClockRuleExecutoreTest test?

**Comment by zzzk1** [comment]
> @zzzk1 Thank you so much. Are you still working on the issue? If yes can I just create a PR for AlterGlobalClockRuleExecutoreTest test?

sure, just go ahead!

**Comment by VishalMCF** [comment]
@zzzk1 you can go ahead.It is still very confusing actually.

**Comment by Mykiiii** [comment]
Hi @terrymanu , I would like take this issue, if it's not done

**Comment by terrymanu** [comment]
> Hi @terrymanu , I would like take this issue, if it's not done

Sorry to reply late, please go ahead

**Comment by ilyasahsan123** [comment]
hi @terrymanu, Are we intentionally closing this issue? I noticed there are incomplete tasks remaining in this issue. Thanks

**Comment by terrymanu** [comment]
> hi @terrymanu, Are we intentionally closing this issue? I noticed there are incomplete tasks remaining in this issue. Thanks
> 
> (_edited_) It looks like the issue was closed because I flagged the latest pull request as **Fixes** instead of **Ref**

The issue was closed automatically due to the pull request association. However, this issue has not been fully resolved, and the unchecked checkboxes still require further modifications.
