### ISSUE TITLE
Why SQLExecutePrepareTemplate use different connections to execute actual sqls even in serial mode?

### ISSUE THREAD

**Issue by Sy9876** [apache/shardingsphere#3015]
## Question
I am using sharding-jdbc-core-4.0.0-RC1.

Table T sharding with 4 actual tables **T_0, T_1, T_2, T_3**.

I configured maxConnectionsSizePerQuery to 4.

```
spring.shardingsphere.props.max.connections.size.per.query=4
```

When I execute sql "select * from T" in a transactional method, I found sharding-jdbc **used 4 connections** to execute these sql in **serially**.

```
@Transactional(readOnly = true)
public void test() {
  jdbcTemplate.queryForList("select * from T");
}
```

I understand that we need use different connections to execute sql in paralle.
but why it use different connections even in serially?

----
Actually, in my application, following exception happened.
"Cause: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction"

My application is delete and insert records to a sharding table. sample code is:
```
@Transactional
public void x() {
  // 1  delete * from T;
  // 2  insert records
  for(Record record : records) {
    // insert into T values(...)
  }
}
```

I debugged and found there are 4 connections(transactions) after delete in mysql
conn1(trx1) -- delete T_0
conn2(trx2) -- delete T_1
conn3(trx3) -- delete T_2
conn4(trx4) -- delete T_3

and when do insert one by one, it only use conn1.
Then, when use conn1 to do "insert into T_1 ...", it waits trx2 to release the locks, until Lock wait timeout happened.

**Comment by cherrylzhao** [comment]
sorry for late response, we'd like to investigate later

**Comment by cherrylzhao** [comment]
it is very hard to handle this bug, we should
- make spring.shardingsphere.props.max.connections.size.per.query=1 when start a transaction.
- or add a table dimension within cachedConnections of ShardingConnection

**Comment by Sy9876** [comment]
Thank you for reply.

Config maxConnectionsSizePerQuery larger than 1 is dangers because it is application scope property.
On other hand, if keep it to 1, queries are execute in serial mode. So the more shards, the worse performance .

Expect to be resolved in future releases.

**Comment by cherrylzhao** [comment]
There are 2 transaction exception when  `max.connections.size.per.query > 1`

1. `write-write` transaction exception (#3015)
If write-operation-1 hold 4 connections of database1, then write-operation-2 may use a cached connection which lack of privilege to access the record  and then dead lock exception happed.

2. `write-query` transaction exception (#3732)
If write-operation-1 only hold 1 connection of database1, but query-operation-2 may get another connections from datasources which lack of privilege to access the write-operation-1 record, and then uncommitted records will not be visible.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
