### ISSUE TITLE
Add test case for ShardingSphereURLLoadEngine

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#30153]
Please add a new fixture of ShardingSphereURLLoader to finish the test case

**Comment by clbigdata** [comment]
I want try this

**Comment by zhaojinchao95** [comment]
> I want try this

Welcome!

**Comment by zhaojinchao95** [comment]
@clbigdata Hi, the `5.5.0` version will be released next week. Can it be completed during this period?
