### ISSUE TITLE
SHOW SHARDING ALGORITHM IMPLEMENTATIONS; ERROR

### ISSUE THREAD

**Issue by GPF199541** [apache/shardingsphere#30202]
version 5.4.1
 SHOW SHARDING ALGORITHM IMPLEMENTATIONS;

ERROR 12000 (42000): You have an error in your SQL syntax: SHOW SHARDING ALGORITHM IMPLEMENTATIONS, no viable alternative at input 'SHOWSHARDING' at line 1, position 5, near [@1,5:12='SHARDING',<862>,1:5]

**Comment by RaigorJiang** [comment]
Hi @GPF199541 
The DistSQL syntax you mentioned is new to the master branch and has not been released yet. It does not exist in version 5.4.1.
