### ISSUE TITLE
数据源用SQLserver时，分页有问题

### ISSUE THREAD

**Issue by 2671884528** [apache/shardingsphere#30218]
以下是可以正确拿到数据的
SELECT * FROM trade_order ORDER BY create_time OFFSET 0 ROW FETCH NEXT 10 ROWS ONLY;
以下是拿不到数据的（OFFSET不同而已）
SELECT * FROM trade_order ORDER BY create_time OFFSET 10 ROW FETCH NEXT 10 ROWS ONLY;

分析原因
这个判断有问题，导致无法获取数据。这里的逻辑不正确
![image](https://github.com/apache/shardingsphere/assets/39427887/5ac5a63e-98fc-49da-be07-c4e51600e42e)

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
