### ISSUE TITLE
SQLserver paging

### ISSUE THREAD

**Issue by 2671884528** [apache/shardingsphere#30222]
The following is the correct way to obtain the data
SELECT * FROM trade_order ORDER BY create_time OFFSET 0 ROW FETCH NEXT 10 ROWS ONLY;
The following data cannot be obtained (OFFSET is different)
SELECT * FROM trade_order ORDER BY create_time OFFSET 10 ROW FETCH NEXT 10 ROWS ONLY;

Analyze the reasons
There is a problem with this judgment and the data cannot be obtained. The logic here is incorrect
For this SQL OFFSET 10 ROW FETCH NEXT 10 ROWS ONLY, rowNumber++ <= pagination.getActualRowCount().get() is always false
![image](https://github.com/apache/shardingsphere/assets/39427887/c75caebd-c4af-4a3c-ae49-24e0a1868d0e)

**Comment by strongduanmu** [comment]
Hi @2671884528, thank you for feedback. Can you modify this issue according to issue template?

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
