### ISSUE TITLE
Custom sharding algorithm is not executed

### ISSUE THREAD

**Issue by stqf** [apache/shardingsphere#30229]
Runtime info:
JDK 17.0.6
SpringBoot: 3.0.6
shardingsphere-jdbc: 5.2.1
Dependency Info: 
![image](https://github.com/apache/shardingsphere/assets/33819174/fce94e9c-2a3b-4d62-bb05-ad7dbba14124)
Config file:
![image](https://github.com/apache/shardingsphere/assets/33819174/b98e35e9-2d11-4595-ba4f-7143cc02a658)
Custom algorithm:
![image](https://github.com/apache/shardingsphere/assets/33819174/1f2a968c-c800-4844-aac0-b40afb7077b6)
Error Info:
![image](https://github.com/apache/shardingsphere/assets/33819174/046567b2-12e2-4c74-bf27-3108466b32ff)
![image](https://github.com/apache/shardingsphere/assets/33819174/168ed3bc-d3dc-4f2d-8675-aefb28419e27)
Expected results:
1. Ability to enter custom sharding algorithms, dynamically create physical tables based on time, and return corresponding information
2. When is springboot starter 5.4.1 planned to be released?

**Comment by stqf** [comment]
After debugging, the standard sharding strategy is correct, 
![image](https://github.com/apache/shardingsphere/assets/33819174/cb4182c4-3fde-4569-9c2b-f2a07801f799)
but quotation marks need to be added to the column. The Hint allocation strategy still does not take effect.
![image](https://github.com/apache/shardingsphere/assets/33819174/a3721d5e-8e04-43c4-bce0-6db05428c164)
![image](https://github.com/apache/shardingsphere/assets/33819174/8d4811b6-d7f8-40b4-aa0a-13218fae8018)

**Comment by lorchr** [comment]
i meet the same error, custom defined hint sharding strategy not work.  with 5.4.1

**Comment by terrymanu** [comment]
The issue involves many thrid-party dependencies, but we are focusing only on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, could you please debug the program to show the specific issue with the JDBC calls, or provide a demo on GitHub for easy reproduction of the problem?
