### ISSUE TITLE
Fix checkstyle reported warning in many files

### ISSUE THREAD

**Issue by Pinti0001** [apache/shardingsphere#30236]
## WARNING:

File name : AlterDefaultShadowAlgorithmStatementAssert.java

- Utility classes should not have a public or default constructor. (35:1) [HideUtilityClassConstructor]

File name : AlterIndexStatementAssert.java

- Utility classes should not have a public or default constructor. (39:1) [HideUtilityClassConstructor]

 
And many more 

 **It's generally a good practice to follow the advice provided by Checkstyle and other static analysis tools, as they help enforce best practices and maintain code quality**.

**Comment by linghengqian** [comment]
- Closing issue due to lack of responses.
