### ISSUE TITLE
Improve shardingsphere.infra.url test cases

### ISSUE THREAD

**Issue by zzzk1** [apache/shardingsphere#30234]
## Feature Request

Windows11 Maven build process failed with
``` shell
./mvnw clean install -B -T1C -Pcheck
```
Operating System Information
![QQ截图20240221201629](https://github.com/apache/shardingsphere/assets/36791902/4d04a563-35a8-4a80-94d9-d68eed2b70a4)

Failed Test Cases
![QQ截图20240221201509](https://github.com/apache/shardingsphere/assets/36791902/644c220a-bea9-4a35-9d5e-5bf7a2439a10)

![QQ截图20240221201556](https://github.com/apache/shardingsphere/assets/36791902/b637b4b1-e399-4377-a00a-9a7748424cf6)

**Comment by linghengqian** [comment]
- Considering that I personally don't have a Windows Native development environment, I would suggest you open a PR. It's not difficult, just change the value of the assertion.
