### ISSUE TITLE
proxy-4.0.0-RC2 process blob data error

### ISSUE THREAD

**Issue by xriqyu** [apache/shardingsphere#3024]
writedata:
byte[] oriArray = new byte[]{
                1,0,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,113,117,101,115,-12,49,48,46,48,46,52,46,49,-75,75,74,65,104,115,100,97,107,100,104,97,115,107,-28,115,101,116,68,97,116,-31,1,1,91,76,106,97,118,97,46,108,97,110,103,46,79,98,106,101,99,116,-69,6,9,-64,-39,-86,20,3,115,100,104,98,115,97,104,100,98,115,-31,1,2,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,115,112,111,110,115,-27,0,0,0,3,115,107,104,100,98,115,107,100,117,104,97,108,100,115,106,102,100,107,106,97,102,110,97,100,102,-22,10,66,61,-8,-5,108,25,0,0,3,2,0,3,0,0
        };

but read data is
99,111,109,46,109,121,115,113,108,46,106,100,98,99,46,66,108,111,98,64,52,48,102,101,53,50,53,54

equals is false

table sql:
CREATE TABLE `data_record` (
  `uuid` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `byteData` blob,
  `type` int(11) NOT NULL,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

Simple Test code:
git@github.com:xriqyu/TestProxyTest.git

TestApplicationTests,java

thanks

**Comment by terrymanu** [comment]
Is it same issue with #3017?

**Comment by xriqyu** [comment]
different . not has exception，only process data error .
use mysql ok, use proxy error.

code:
 byte[] oriArray = new byte[]{          1,0,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,113,117,101,115,-12,49,48,46,48,46,52,46,49,-75,75,74,65,104,115,100,97,107,100,104,97,115,107,-28,115,101,116,68,97,116,-31,1,1,91,76,106,97,118,97,46,108,97,110,103,46,79,98,106,101,99,116,-69,6,9,-64,-39,-86,20,3,115,100,104,98,115,97,104,100,98,115,-31,1,2,99,111,109,46,108,115,46,114,112,99,46,115,101,114,118,101,114,46,82,112,99,82,101,115,112,111,110,115,-27,0,0,0,3,115,107,104,100,98,115,107,100,117,104,97,108,100,115,106,102,100,107,106,97,102,110,97,100,102,-22,10,66,61,-8,-5,108,25,0,0,3,2,0,3,0,0
        };
        record.setByteData(oriArray);
        mapper.insert(record);
        record = mapper.selectByPrimaryKey(record.getUuid());
        mapper.delete(record.getUuid());
        byte[] dbReadArray     = record.getByteData();
        System.out.println("\n");
        System.out.println("equals result : " + Arrays.equals(oriArray,dbReadArray));
        System.out.println("\n");

run result:
equals result : false

thanks.

**Comment by yanickxia** [comment]
@xriqyu  i try 4 different way to reappear it , but without success. 

RAW - JDBC Direct to Mysql
RAW - JDBC By Proxy to Mysql

Mybatis Direct to Mysql
Mybatis By Proxy to Mysql

this is my mybatis xml

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.shardingdemo.mapper.DataMapper">

    <resultMap id="baseResultMap" type="com.example.shardingdemo.entity.DataRecord">
        <result column="uuid" property="uuid" jdbcType="VARCHAR"/>
        <result column="type" property="type" jdbcType="INTEGER"/>
        <result column="byteData" property="byteData" jdbcType="BLOB" />
    </resultMap>

    <insert id="insert" useGeneratedKeys="true" keyProperty="uuid">
        INSERT INTO data_record (uuid, `type`, byteData) VALUES (#{uuid,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{byteData, jdbcType=BLOB});
    </insert>

    <select id="select" resultMap="baseResultMap">
        SELECT * FROM data_record where uuid = #{uuid};
    </select>
</mapper>
```

can you see any different? or give me your demo project. thanks

**Comment by KomachiSion** [comment]
@xriqyu Can you provide more detail information? Such as your sharding-proxy configuration?

**Comment by KomachiSion** [comment]
ShardingProxy decodes MySQL Query request package, and transform sql to String, which will be used to parse. 
But due to the charset, the Blob(binary) type can't transform to String. So some of special byte will be changed while the decode step.

I also add `useServerPrepStmts=true` and `cachePrepStmts=true` to jdbc url, but it will cause new exception: `Cause: java.sql.SQLException: 1Unsupported command: [COM_STMT_SEND_LONG_DATA]`

So, I think the problem need more investigation and discuss for the solutions.

Does any body have idea how mysql deal with the binary type protocol?

**Comment by xriqyu** [comment]
I have given up using the proxy process blob Data,but I hope that you can solve this problem.
now I am using base64.
object -serialization ->byte[] data -base64 encode-> String - write -> DB 
DB -read ->  String -base64 decode -> byte[] data -deserialization -> object

**Comment by xriqyu** [comment]
Testproject
git@github.com:xriqyu/TestProxyTest.git

sharding-proxy configuration:
--- start -------
schemaName: worldDB

dataSources:
 world_0:
   url: jdbc:mysql://127.0.0.1:3306/world_db_0?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 500
   minPoolSize: 1
 world_1:
   url: jdbc:mysql://127.0.0.1:3306/world_db_1?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 500
   minPoolSize: 1
 world_2:
   url: jdbc:mysql://127.0.0.1:3306/world_db_2?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 500
   minPoolSize: 1
 world_3:
   url: jdbc:mysql://127.0.0.1:3306/world_db_3?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 500
   minPoolSize: 1
 ds_default:
   url: jdbc:mysql://127.0.0.1:3306/demo_default_db?serverTimezone=UTC&useSSL=false
   username: root
   password: admin123
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 500
   minPoolSize: 1

shardingRule:
 tables:
   worldpoint:
     actualDataNodes: world_${0..3}.worldpoint
     databaseStrategy:
        inline:
          shardingColumn: serverId
          algorithmExpression: world_${serverId % 4}
     tableStrategy:
       inline:
         shardingColumn: serverId
         algorithmExpression: worldpoint
   world_march:
     actualDataNodes: world_${0..3}.world_march
     databaseStrategy:
        inline:
          shardingColumn: serverId
          algorithmExpression: world_${serverId % 4}
     tableStrategy:
       inline:
         shardingColumn: serverId
         algorithmExpression: world_march
   world_res_dead:
     actualDataNodes: world_${0..3}.world_res_dead
     databaseStrategy:
        inline:
          shardingColumn: serverId
          algorithmExpression: world_${serverId % 4}
     tableStrategy:
       inline:
         shardingColumn: serverId
         algorithmExpression: world_res_dead
   user_world_info:
     actualDataNodes: world_${0..3}.user_world_info
     databaseStrategy:
        inline:
          shardingColumn: uid
          algorithmExpression: world_${uid.hashCode() % 4}
     tableStrategy:
       inline:
         shardingColumn: uid
         algorithmExpression: user_world_info      
 bindingTables:
   - worldpoint,world_march,world_res_dead,user_world_info
 defaultDataSourceName: ds_default
 defaultDatabaseStrategy:
   none:
 defaultTableStrategy:
   none:

---end ---
Thanks every one.

**Comment by KomachiSion** [comment]
> ShardingProxy decodes MySQL Query request package, and transform sql to String, which will be used to parse.
> But due to the charset, the Blob(binary) type can't transform to String. So some of special byte will be changed while the decode step.
> 
> I also add `useServerPrepStmts=true` and `cachePrepStmts=true` to jdbc url, but it will cause new exception: `Cause: java.sql.SQLException: 1Unsupported command: [COM_STMT_SEND_LONG_DATA]`
> 
> So, I think the problem need more investigation and discuss for the solutions.
> 
> Does any body have idea how mysql deal with the binary type protocol?

pending reason: No find enough good solution.

**Comment by sandynz** [comment]
It'll be verified again after unified session charset is completed.

**Comment by terrymanu** [comment]
Version 4.x is out of service, welcome to try 5.x
