### ISSUE TITLE
Discrepancies in official websites in different languages

### ISSUE THREAD

**Issue by zzzk1** [apache/shardingsphere#30275]
## Feature Request

<img width="1919" alt="屏幕截图 2024-02-24 190107" src="https://github.com/apache/shardingsphere/assets/36791902/9454e97c-bb33-4587-abcc-19b31342a86f">
<img width="1910" alt="屏幕截图 2024-02-24 190315" src="https://github.com/apache/shardingsphere/assets/36791902/b00d8d23-5f3b-4923-a528-aadcd999dd0e">

### Describe the feature you would like.
**Remove `?`  in Chinese websites**

**Comment by linghengqian** [comment]
- @zzzk1 It looks like the original author of the PR in question has left Github. Would you be interested in submitting a PR to fix the `<h2>` tag at https://github.com/apache/shardingsphere-doc for this?

**Comment by zzzk1** [comment]
> - @zzzk1 It looks like the original author of the PR in issue has left Github. Would you be interested in submitting a PR to fix the `<h2>` tag at https://github.com/apache/shardingsphere-doc for this?

sure, i can do that

**Comment by Swastyy** [comment]
Hi @linghengqian , since the issue was getting stale by github, I already created a PR, you can review it. Thanks in advance.

**Comment by linghengqian** [comment]
> Hi @linghengqian , since the issue was getting stale by github, I already created a PR, you can review it. Thanks in advance. Link to PR - [apache/shardingsphere-doc#742](https://github.com/apache/shardingsphere-doc/pull/742)

- LGTM!
