### ISSUE TITLE
How to obtain the latest version of shardingsphere jdbc

### ISSUE THREAD

**Issue by robben009** [apache/shardingsphere#30293]
I followed the advice on your official website, want to get
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc</artifactId>
    <version>${latest.release.version}</version>
</dependency>  
but in https://mvnrepository.com/  can not find any version？just have  https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core

**Comment by strongduanmu** [comment]
Hi @robben009, you can search `shardingsphere-jdbc-core`. From the upcoming 5.5.0 release, shardingsphere-jdbc-core will be renamed to shardingsphere-jdbc.

**Comment by strongduanmu** [comment]
You can find the previous version of the guide by looking at the different versions of the documentation, in these documents, you will find the `shardingsphere-jdbc-core` description.

**Comment by robben009** [comment]
ok，i get

**Comment by strongduanmu** [comment]
Since this question has been answered, I will close this issue now.
