### ISSUE TITLE
Can not find module shardingsphere-sql-parser-test

### ISSUE THREAD

**Issue by sxl-vay** [apache/shardingsphere#30312]
![微信图片_20240227134502](https://github.com/apache/shardingsphere/assets/69157262/fba7168a-4fca-4869-ac78-246ee66d6612)

Can not find the module described in doc.

**Comment by strongduanmu** [comment]
Hi @sxl-vay, can you translate this issue to English?

**Comment by sxl-vay** [comment]
> Hi @sxl-vay, can you translate this issue to English?

I want to test whether Sharding-JDBC can parse some complex SQL.The documentation mentions the existence of this testing project, but I couldn't find it in the source code.

**Comment by sxl-vay** [comment]
> > > Hi @sxl-vay, can you translate this issue to English?
> > 
> > 
> > I want to test whether Sharding-JDBC can parse some complex SQL.The documentation mentions the existence of this testing project, but I couldn't find it in the source code.
> 
> In the current master branch, the shardingsphere-sql-parser-test module does not exist. The corresponding code logic has been moved to the shardingsphere-test-it-parser module, with package logic identical to that in the documentation. I will submit a pull request later to update the content of the document.

thanks,I'm waiting for you
