### ISSUE TITLE
When querying multiple tables, the custom database and table sharding algorithm fails, but it takes effect when querying a single table.

### ISSUE THREAD

**Issue by vwater** [apache/shardingsphere#30320]
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.4.1</version>
        </dependency>

  <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3.4</version>

    </dependency>
  
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>snakeyaml</artifactId>
                    <groupId>org.yaml</groupId>
                </exclusion>
            </exclusions>
        </dependency>

![image](https://github.com/apache/shardingsphere/assets/41112571/fa06b544-8b6c-4dec-80da-fb0d2dd4d80b)
![image](https://github.com/apache/shardingsphere/assets/41112571/a1db3453-10c8-4ef4-9880-a99b32996fa0)
![image](https://github.com/apache/shardingsphere/assets/41112571/cfcfed10-319e-40bb-b804-c424e70ba266)
![image](https://github.com/apache/shardingsphere/assets/41112571/3ea9759e-e6b6-4d3f-bd62-30812c5c38dd)
![image](https://github.com/apache/shardingsphere/assets/41112571/63ca9ed7-eaf3-446a-a3e7-397994db6049)

**Comment by terrymanu** [comment]
`shardingsphere-jdbc-core-spring-boot-starter` is deprecated and removed in 5.3.0, please try new version and use ShardingSphere Driver.
