### ISSUE TITLE
Why ShardingSphere-JDBC take over all SQL although the tables not in spring.shardingsphere.sharding.tables config?

### ISSUE THREAD

**Issue by equator8848** [apache/shardingsphere#30353]
## Why ShardingSphere-JDBC take over all SQL although the tables not in spring.shardingsphere.sharding.tables config?

Hi, My ShardingSphere-JDBC version is 4.1.1.

I use ShardingSphere-JDBC on my 5 logic tables, and I have many table that not need to be shard.

Why ShardingSphere-JDBC analyze and exec the SQL that referred tables not in `spring.shardingsphere.sharding.xxx` tables config, finally ShardingSphere-JDBC handle result. I think it's not ShardingSphere-JDBC business.

When I use the special jdbc driver, ShardingSphere-JDBC can not handle sql with asterisk wildcard such as `SELECT RES.*  from ACT_HI_ACTINST RES WHERE RES.PROC_INST_ID_ = '68543cb2-5c3f-11ee-a3c1-0242ac130003' and RES.TENANT_ID_ = 330000000000001`.

**Comment by equator8848** [comment]
![img_v3_028h_10bdf0d1-c7d6-4a6a-b177-b244de18066g](https://github.com/apache/shardingsphere/assets/38284623/8167acd6-94dc-4a71-9471-4971c5ab21eb)

![img_v3_028h_3063430d-5e18-4cb9-8b14-bb10ec2f0acg](https://github.com/apache/shardingsphere/assets/38284623/dfddc43b-0c5c-4242-b939-aebc2db91921)

**Comment by shardcn** [comment]
you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
