### ISSUE TITLE
postgresql does not support other schema name,just can be public

### ISSUE THREAD

**Issue by zhangzhaoyu** [apache/shardingsphere#30413]
## Bug Report
when I use postgresql with other shcema name ,not 'public' . class PostgreSQLMetaDataLoader can not load tables not in 'public' schema success.

postgresql dababase will use PostgreSQLDatabaseMetaData class to get default schema, it can be only 'public'.

I saw oracle use OracleDatabaseMetaData to get default schema below:

```java
connection.getMeataData().getUserName()
```

How can I use other schema name in postgresql?

**Comment by terrymanu** [comment]
What is your version?

**Comment by linchuyao** [comment]
5.4.1  I had the same problem

**Comment by linchuyao** [comment]
Table or view `%s` does not exist. 
Because only public schema is loaded by default, the verification fails because my project schema is not public

**Comment by strongduanmu** [comment]
You can try use `SELECT  FROM test.table`. ShardingSphere supports different schemas, but you need to specify the schema when using it.

If you want to get the same experience as native PostgreSQL, you can consider participating in this task: https://github.com/apache/shardingsphere/issues/17204

**Comment by strongduanmu** [comment]
This issue is duplicate with #17204, we will consider support PostgreSQL SEARCH PATH in future.
