### ISSUE TITLE
though setted keyGenerators SNOWFLAKE,but id is not setted

### ISSUE THREAD

**Issue by dongoewang** [apache/shardingsphere#30429]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
value of key is setted by SnowflakeKeyGenerateAlgorithm 
### Actual behavior
value of key is setted to null
### Example codes for reproduce this issue (such as a github link).
config file:

mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: sharding-data-source
      server-lists: ${zookeeper.ip}:2181

dataSources:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: ${store.datasource.ip}:3306/${store.datasource.oa}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${store.datasource.username}
    password: ${store.datasource.password}
    driverClassName: com.mysql.cj.jdbc.Driver
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual

rules:
- !SINGLE
    tables:
      - "*.*"
- !SHARDING
    tables:
      kq_attendance_daily:
        actualDataNodes: datasource.kq_attendance_daily_${202401..208801}
        tableStrategy:
          standard:
            shardingColumn: attendance_date
            shardingAlgorithmName: clockRecordAutoCustom
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake_generator

      kq_attendance_daily_clock:
        actualDataNodes: datasource.kq_attendance_daily_clock_${202401..208801}
        tableStrategy:
          standard:
            shardingColumn: attendance_date
            shardingAlgorithmName: clockRecordAutoCustom
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake_generator

    bindingTables:
      - kq_attendance_daily, kq_attendance_daily_clock

    shardingAlgorithms:
      clockRecordAutoCustom:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.younike.oa.shardingAlgorithm.ClockRecordAutoShardingAlgorithm

    keyGenerators:
      snowflake_generator:
        type: SNOWFLAKE

props:
  sql-show: true

java config
    @Bean(name = "shardingDataSource")
    public DataSource shardingDataSource() {
        DriverDataSourceCache dataSourceCache = new DriverDataSourceCache();
        DataSource dataSource = dataSourceCache.get("jdbc:shardingsphere:classpath:sharding-config.yaml");
        return dataSource;
    }

table:kq_attendance_daily（kq_attendance_daily_clock is similar with kq_attendance_daily）
CREATE TABLE `kq_attendance_daily`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `organ_id` bigint NULL DEFAULT NULL COMMENT '项目id',
  `employee_id` bigint NOT NULL COMMENT '员工ID',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '部门id',
  `post_id` bigint NULL DEFAULT NULL COMMENT '职位id',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1553387 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci COMMENT = '员工考勤日报' ROW_FORMAT = DYNAMIC;

**Comment by dongoewang** [comment]
where should i start from？

**Comment by RaigorJiang** [comment]
Hi, could you please provide your insert sql?

**Comment by dongoewang** [comment]
> Hi, could you please provide your insert sql?
thanks for replying。

i have been using saveBatch ofmybatis plus to insert data，such as 【clockRecordService.saveBatch(records)】。printed sql is following：
Logic SQL : INSERT INTO kq_employee_clock_record (
	id,
	employee_id,
	clock_time,
	clock_day,
	clock_day_time,
	longitude,
	latitude,
	address,
	source,
	os,
	browser,
	create_dt,
	create_user,
	update_dt,
	update_user 
)
VALUES
	( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) 
	2024-03-08 13 : 23 : 28 [ INFO ] [ XNIO - 1 task - 1 ] ShardingSphere - SQL : < 0.1 >< ziti918130105703170048 > Actual SQL : datasource ::: INSERT INTO kq_employee_clock_record_202402 (
		id,
		employee_id,
		clock_time,
		clock_day,
		clock_day_time,
		longitude,
		latitude,
		address,
		source,
		os,
		browser,
		create_dt,
		create_user,
		update_dt,
		update_user 
	)
VALUES
	(?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
	?) ::: [ NULL,
	65256,
	2024-02-01 00 : 00 : 00.0,
	2024-02-01,
	00 : 00 : 00,
	118.787651,
	32.035561,
	中国建设银行江苏省分行秦淮洪武路 188号,
	2,
	win11,
	Chrome Mobile,
	2024-03-08 13 : 22 : 46.416,
	NULL,
	NULL,
	NULL ]

testting sample is following
 public void testGenerator() throws Exception {
        List<EmployeeClockRecord> records = new ArrayList<>(3);
        EmployeeClockRecord clockRecord1 = new EmployeeClockRecord();
        clockRecord1.setEmployeeId(65256L);
        clockRecord1.setLongitude(new Double("118.787651"));
        clockRecord1.setLatitude(new Double("32.035561"));
        Date date = DateUtils.formatStringByStyleToDate("2024-01-31 15:08:40", "yyyy-MM-dd");
        clockRecord1.setClockTime(date);
        clockRecord1.setClockDay(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), YYYY_MM_DD));
        clockRecord1.setClockDayTime(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), HH_MM_SS));
        clockRecord1.setSource(2);
        clockRecord1.setOs("win11");
        clockRecord1.setBrowser("Chrome Mobile");
        clockRecord1.setAddress("中国建设银行江苏省分行秦淮洪武路188号");

        EmployeeClockRecord clockRecord2 = new EmployeeClockRecord();
        clockRecord2.setEmployeeId(65256L);
        clockRecord2.setLongitude(new Double("118.787651"));
        clockRecord2.setLatitude(new Double("32.035561"));
        Date date2 = DateUtils.formatStringByStyleToDate("2024-02-01 15:08:40", "yyyy-MM-dd");
//        Date date2 = Date.from(localDate2.atStartOfDay(ZoneOffset.ofHours(8)).toInstant());
        clockRecord2.setClockTime(date2);
        clockRecord2.setClockDay(DateUtils.formatDateByStyle(clockRecord2.getClockTime(), YYYY_MM_DD));
        clockRecord2.setClockDayTime(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), HH_MM_SS));
        clockRecord2.setSource(2);
        clockRecord2.setOs("win11");
        clockRecord2.setBrowser("Chrome Mobile");
        clockRecord2.setAddress("中国建设银行江苏省分行秦淮洪武路188号");


        records.add(clockRecord1);
        records.add(clockRecord2);
        String shardingDataSource ="shardingDataSource";
        DynamicDataSourceContextHolder.setDataSourceType(shardingDataSource);
        clockRecordService.saveBatch(records);
    }

**Comment by dongoewang** [comment]
> Hi, could you please provide your insert sql?
thanks for replying。

i have been using saveBatch ofmybatis plus to insert data，such as 【clockRecordService.saveBatch(records)】。printed sql is following：
Logic SQL : INSERT INTO kq_employee_clock_record (
	id,
	employee_id,
	clock_time,
	clock_day,
	clock_day_time,
	longitude,
	latitude,
	address,
	source,
	os,
	browser,
	create_dt,
	create_user,
	update_dt,
	update_user 
)
VALUES
	( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) 
	2024-03-08 13 : 23 : 28 [ INFO ] [ XNIO - 1 task - 1 ] ShardingSphere - SQL : < 0.1 >< ziti918130105703170048 > Actual SQL : datasource ::: INSERT INTO kq_employee_clock_record_202402 (
		id,
		employee_id,
		clock_time,
		clock_day,
		clock_day_time,
		longitude,
		latitude,
		address,
		source,
		os,
		browser,
		create_dt,
		create_user,
		update_dt,
		update_user 
	)
VALUES
	(?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
		?,
	?) ::: [ NULL,
	65256,
	2024-02-01 00 : 00 : 00.0,
	2024-02-01,
	00 : 00 : 00,
	118.787651,
	32.035561,
	中国建设银行江苏省分行秦淮洪武路 188号,
	2,
	win11,
	Chrome Mobile,
	2024-03-08 13 : 22 : 46.416,
	NULL,
	NULL,
	NULL ]

testting sample is following
 public void testGenerator() throws Exception {
        List<EmployeeClockRecord> records = new ArrayList<>(3);
        EmployeeClockRecord clockRecord1 = new EmployeeClockRecord();
        clockRecord1.setEmployeeId(65256L);
        clockRecord1.setLongitude(new Double("118.787651"));
        clockRecord1.setLatitude(new Double("32.035561"));
        Date date = DateUtils.formatStringByStyleToDate("2024-01-31 15:08:40", "yyyy-MM-dd");
        clockRecord1.setClockTime(date);
        clockRecord1.setClockDay(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), YYYY_MM_DD));
        clockRecord1.setClockDayTime(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), HH_MM_SS));
        clockRecord1.setSource(2);
        clockRecord1.setOs("win11");
        clockRecord1.setBrowser("Chrome Mobile");
        clockRecord1.setAddress("中国建设银行江苏省分行秦淮洪武路188号");

        EmployeeClockRecord clockRecord2 = new EmployeeClockRecord();
        clockRecord2.setEmployeeId(65256L);
        clockRecord2.setLongitude(new Double("118.787651"));
        clockRecord2.setLatitude(new Double("32.035561"));
        Date date2 = DateUtils.formatStringByStyleToDate("2024-02-01 15:08:40", "yyyy-MM-dd");
//        Date date2 = Date.from(localDate2.atStartOfDay(ZoneOffset.ofHours(8)).toInstant());
        clockRecord2.setClockTime(date2);
        clockRecord2.setClockDay(DateUtils.formatDateByStyle(clockRecord2.getClockTime(), YYYY_MM_DD));
        clockRecord2.setClockDayTime(DateUtils.formatDateByStyle(clockRecord1.getClockTime(), HH_MM_SS));
        clockRecord2.setSource(2);
        clockRecord2.setOs("win11");
        clockRecord2.setBrowser("Chrome Mobile");
        clockRecord2.setAddress("中国建设银行江苏省分行秦淮洪武路188号");


        records.add(clockRecord1);
        records.add(clockRecord2);
        String shardingDataSource ="shardingDataSource";
        DynamicDataSourceContextHolder.setDataSourceType(shardingDataSource);
        clockRecordService.saveBatch(records);
    }

**Comment by RaigorJiang** [comment]
OK, I noticed that your insert SQL already contains the id column, so it will not be automatically generated and rewritten.

You can try not to include the id column in the insert statement, then ShardingSphere will generate the value for you and rewrite the insert SQL.

**Comment by dongoewang** [comment]
thanks。 I  will  try



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/08/2024 18:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [apache/shardingsphere] though setted keyGenerators SNOWFLAKE,but id is not setted (Issue #30429) |

OK, I noticed that your insert SQL already contains the id column, so it will not be automatically generated and rewritten.

You can try not to include the id column in the insert statement, then ShardingSphere will generate the value for you and rewrite the insert SQL.

**Comment by dongoewang** [comment]
thanks,According to explanation,sovled the problem

**Comment by RaigorJiang** [comment]
Great, happy for you!
