### ISSUE TITLE
There is not  table【kq_attendance_clock】in shardingSphereSchema? 

### ISSUE THREAD

**Issue by dongoewang** [apache/shardingsphere#30464]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
There  is   table【kq_attendance_clock】in shardingSphereSchema
### Actual behavior
There is not  table【kq_attendance_clock】in shardingSphereSchema
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
though there are four sharing table，only table【kq_employee_clock_record】 information is in zk，there are not
other three tables information in zk。but there are all of sharding information in zk 。
1:config file ：Refer to the attachment【1.txt】
[1.txt](https://github.com/apache/shardingsphere/files/14567313/1.txt)

2：table：Refer to the attachment【2.png】
![2](https://github.com/apache/shardingsphere/assets/9483828/e0a99013-753a-4893-ad2a-20948bf90087)

3：zk‘s information：Refer to the attachment【3.txt】
[3.txt](https://github.com/apache/shardingsphere/files/14567314/3.txt)

4：error information：refer to the attachment【4.txt】
[4.txt](https://github.com/apache/shardingsphere/files/14567315/4.txt)
5：error occured place：
![5](https://github.com/apache/shardingsphere/assets/9483828/9875bb9c-3296-49ef-b915-f2ad1756ac33)

**Comment by dongoewang** [comment]
> Hi @dongoewang, can you refer faq - https://shardingsphere.apache.org/document/current/cn/faq/#%E5%8D%95%E8%A1%A8 to solve this exception?

thanks for reply。though i refered，don‘t solve that exception

**Comment by strongduanmu** [comment]
> > Hi @dongoewang, can you refer faq - https://shardingsphere.apache.org/document/current/cn/faq/#%E5%8D%95%E8%A1%A8 to solve this exception?
> 
> thanks for reply。though i refered，don‘t solve that exception

According to the information you provided, the sharding table is not loaded into the metadata. Please check whether the actual tables defined in the sharding rule exists.

**Comment by dongoewang** [comment]
> > > Hi @dongoewang, can you refer faq - https://shardingsphere.apache.org/document/current/cn/faq/#%E5%8D%95%E8%A1%A8 to solve this exception?
> > 
> > 
> > thanks for reply。though i refered，don‘t solve that exception
> 
> According to the information you provided, the sharding table is not loaded into the metadata. Please check whether the actual tables defined in the sharding rule exists.
thanks for suggestion。
first ，i have solved the program,but I want to ask a question.(in other word,i don't hnow thata Problem solving method is right or not)
step of problem solving method 
1:for code can automatically creat table in db，i overwrit class 【InlineExpressionParser】to append Processing with red lines framed such like following pitcture.
![处理1](https://github.com/apache/shardingsphere/assets/9483828/0724a782-894f-4769-8d2f-b11821f63910)
2:after code created table，i update ActualDataNodes such like following picture
![处理2](https://github.com/apache/shardingsphere/assets/9483828/db28e62f-b778-4939-aa0d-c05062a8fe96)

quesitn：
1：Is there a potential issue with this method
2：is there better method ？

**Comment by strongduanmu** [comment]
@dongoewang This approach seems to work, as we need to update nodes in actualDataNodes as we remove or add nodes. A better approach is to use cluster mode and update actualDataNodes through DistSQL.

**Comment by dongoewang** [comment]
> @dongoewang This approach seems to work, as we need to update nodes in actualDataNodes as we remove or add nodes. A better approach is to use cluster mode and update actualDataNodes through DistSQL.

Although i heve been using cluster mode，i have been using sharding sphere-jdbc。it seems sharding-shpere-jdbc dosn‘t use distsql

**Comment by strongduanmu** [comment]
We are currently planning this feature, please stay tuned for future versions.

**Comment by dongoewang** [comment]
> We are currently planning this feature, please stay tuned for future versions.

Looking forward to it
