### ISSUE TITLE
Does oracle's syntax parsing support this syntax?

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#30481]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Does oracle's syntax parsing support this syntax?
The sql is as follows:

> UPDATE t_logs t INNER JOIN t_user u ON t.oper_user = u.user_id
> SET t.oper_user = u.user_id, t.oper_user_name = u.user_name;

**Comment by strongduanmu** [comment]
Hi @Y-sir, ShardingSphere Proxy only support MySQL, PostgreSQL and openGauss, you can execuete Oracle sql through JDBC adapter.

**Comment by Y-sir** [comment]
> Hi @Y-sir, ShardingSphere Proxy only support MySQL, PostgreSQL and openGauss, you can execuete Oracle sql through JDBC adapter.

Hello, I am referring to the syntax of shardingsphere/parser oracle


![Uploading image.png…]()
