### ISSUE TITLE
The keyGenerateStrategy in version 5.2.0 is not functional, but it works in version 5.4.0.

### ISSUE THREAD

**Issue by JinZhang-96** [apache/shardingsphere#30484]
### Which version of ShardingSphere did you use?
5.2.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
keyGenerateStrategy is able use
### Actual behavior
keyGenerateStrategy is unable use
### Reason analyze (If you can)
upgrad 5.4.0
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
INSERT INTO TM_ELEMENT_1 (ELE_CODE, ELE_NAME, MAX_LEVEL, ELE_TYPE, GET_TYPE, SERVER_URL, DATA_SOURCE, TABLE_NAME, STATUS, LAST_VERSION)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ::: [code1, name1, 5, 1, 2, http://example.com, example_db, example_table, 1, 0]
### Example codes for reproduce this issue (such as a github link).
rules:
  - !SHARDING
    tables:
      TM_ELEMENT:
        actualDataNodes: element.TM_ELEMENT_${0..2}
        tableStrategy:
          standard:
            shardingColumn: ID
            shardingAlgorithmName: TM_ELEMENT_INLINE
        keyGenerateStrategy:
          column: ID
          keyGeneratorName: snowflake
    shardingAlgorithms:
      TM_ELEMENT_INLINE:
        type: INLINE
        props:
          algorithm-expression: TM_ELEMENT_${Math.abs(ID.hashCode()) % 3}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE

**Comment by terrymanu** [comment]
Then please upgrade the version to 5.4.0 please
