### ISSUE TITLE
Does oracle's syntax parsing support this syntax?

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#30482]
Bug Report
For English only, other languages will not accept.

Before report a bug, make sure you have:

Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will close it.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
5.4.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
Does oracle's syntax parsing support this syntax?
The sql is as follows:

UPDATE t_logs t INNER JOIN t_user u ON t.oper_user = u.user_id
SET t.oper_user = u.user_id, t.oper_user_name = u.user_name;

Actual behavior
Reason analyze (If you can)
Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Example codes for reproduce this issue (such as a github link).

![image](https://github.com/apache/shardingsphere/assets/62044303/17a6eaa3-acce-4059-b478-3dda79caa936)

![image](https://github.com/apache/shardingsphere/assets/62044303/20274baa-0ae3-4122-a180-0e21e2e2b050)

**Comment by RaigorJiang** [comment]
Looks like it's not supported
https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/UPDATE.html#GUID-027A462D-379D-4E35-8611-410F3AC8FDA5

**Comment by Y-sir** [comment]
@TherChenYang Hello, can you help me adapt it?

**Comment by TherChenYang** [comment]
@Y-sir Okay, I'll look into this problem.

**Comment by Y-sir** [comment]
> @Y-sir Okay, I'll look into this problem.

Thanks

**Comment by TherChenYang** [comment]
@Y-sir That syntax isn't valid in Oracle. You can do this:
```sql
update "t_logs" set "t_logs"."oper_user_name" = 
( select "t_user"."user_name"
from "t_user"
where "t_logs"."oper_user" = "t_user"."user_id")	
```

**Comment by Y-sir** [comment]
> @Y-sir That syntax isn't valid in Oracle. You can do this:
> 
> ```sql
> update "t_logs" set "t_logs"."oper_user_name" = 
> ( select "t_user"."user_name"
> from "t_user"
> where "t_logs"."oper_user" = "t_user"."user_id")	
> ```

@TherChenYang Hello, we are using Oracle modified by Magic. Can you help me adapt to this SQL?

**Comment by TherChenYang** [comment]
ShardingSphere currently has no plans to support customized databases. You can refer to the grammar of ANTLR to complete the corresponding support.

**Comment by RaigorJiang** [comment]
Closed due to no such plan.
