### ISSUE TITLE
How to config hikari for each dataSource,  like minimum-idle

### ISSUE THREAD

**Issue by xiangshaonumber1** [apache/shardingsphere#30480]
## Example use shardingSphere
LOG@2024-03-14 10:03:03.451 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: BaseHikariCP - Starting...
LOG@2024-03-14 10:03:03.627 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: HikariPool-1 - Starting...
LOG@2024-03-14 10:03:03.749 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: HikariPool-1 - Start completed.
LOG@2024-03-14 10:03:03.806 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: HikariPool-2 - Starting...
LOG@2024-03-14 10:03:03.933 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: HikariPool-2 - Start completed.
LOG@2024-03-14 10:03:03.933 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: HikariPool-3 - Starting...
LOG@2024-03-14 10:03:03.936 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: HikariPool-3 - Start completed.
LOG@2024-03-14 10:03:03.936 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: HikariPool-4 - Starting...
LOG@2024-03-14 10:03:03.939 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: HikariPool-4 - Start completed.
LOG@2024-03-14 10:03:06.600 [BT-2]  INFO-> com.zaxxer.hikari.pool.PoolBase.getAndSetNetworkTimeout[541]: BaseHikariCP - Driver does not support get/set network timeout for connections. (getNetworkTimeout)
LOG@2024-03-14 10:03:06.602 [BT-2]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: BaseHikariCP - Start completed.

complete used 3s. why? 

## Example do not use shardingSphere
LOG@2024-03-14 10:06:23.735 [BT-1]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[110]: HikariPool-1 - Starting...
LOG@2024-03-14 10:06:23.861 [BT-1]  INFO-> com.zaxxer.hikari.pool.HikariPool.checkFailFast[565]: HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6bea8488
LOG@2024-03-14 10:06:23.863 [BT-1]  INFO-> com.zaxxer.hikari.HikariDataSource.getConnection[123]: HikariPool-1 - Start completed.

like this, only used 130ms

## my config example (springboot2 + jdk21)
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-@custom.profile.name@.yaml
    hikari:
     # this like do not work 
      minimum-idle: 2
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 60000
      pool-name: BaseHikariCP
      max-lifetime: 180000
      validation-timeout: 1000
      connection-timeout: 3000
      keepalive-time: 30000

## config of sharding.yaml
mode:
  type: Standalone
  repository:
    type: JDBC
dataSources:
  write_ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.101.35:3307/testdb?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: 
    password: 
  read_ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.101.35:3307/testdb?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: 
    password: 
  read_ds2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.101.35:3307/testdb?useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: 
    password:

**Comment by RaigorJiang** [comment]
Hi @xiangshaonumber1 
You can set minPoolSize/maxPoolSize for  hikari pool, example:
```yaml
dataSources:
  ds_0:
      dataSourceClassName: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: xxx
      password: xxx
      maxPoolSize: 10
      minPoolSize: 10
```

**Comment by RaigorJiang** [comment]
Refer to https://github.com/apache/shardingsphere/blob/master/infra/data-source-pool/core/src/main/java/org/apache/shardingsphere/infra/datasource/pool/config/PoolConfiguration.java

**Comment by xiangshaonumber1** [comment]
> Hi @xiangshaonumber1 You can set minPoolSize/maxPoolSize for hikari pool, example:
> 
> ```yaml
> dataSources:
>   ds_0:
>       dataSourceClassName: com.zaxxer.hikari.HikariDataSource
>       driverClassName: com.mysql.cj.jdbc.Driver
>       jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
>       username: xxx
>       password: xxx
>       maxPoolSize: 10
>       minPoolSize: 10
> ```

@RaigorJiang thanks, but the property like poolName, the configuration is not work , can custom config it ?

**Comment by RaigorJiang** [comment]
@xiangshaonumber1 
Here is a related issue for your reference #17646

**Comment by xiangshaonumber1** [comment]
> @xiangshaonumber1 Here is a related issue for your reference #17646

i do like this link,  but it not work,  I use shardingsphere 5.4.1， poolName already rollback?  Consider open it up in the future？

**Comment by RaigorJiang** [comment]
@xiangshaonumber1 
I did some research and found that in ShardingSphere, connection pool objects are not fixed, they are rebuilt as configuration changes, so the same pool-name may be applied to different pool objects, which may cause potential problems ( such as the matching of monitoring indicators, etc.), so this is actually not a simple problem.
