### ISSUE TITLE
Missing convert rule configuration provider for broadcast and single rule

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30496]
<img width="477" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/f8907b96-066e-49ba-9f96-402fbfb6aae5">

**Comment by dongzl** [comment]
Hi @RaigorJiang, I want to try it.

**Comment by RaigorJiang** [comment]
Hi @dongzl , thanks for your help
