### ISSUE TITLE
What does supportEquivalentFilter mean?

### ISSUE THREAD

**Issue by zzyReal666** [apache/shardingsphere#30528]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

### Class ： EncryptAlgorithmMetaData

I am doing someting in encrypt algorithm,this is my question.

What does supportEquivalentFilter mean?When is this property `true`?
![image](https://github.com/apache/shardingsphere/assets/34822229/10e7f21a-6231-40aa-8228-90453563a020)

**Comment by pmupkin** [comment]
The supportEquivalentFilter  indicates whether the encryption algorithm supports equivalent filtering. In encrypted scenarios, traditional exact match queries may not be directly applicable due to the data being encrypted. If this property is set to true, it signifies that  equivalent filtering technique can be utilized to query encrypted data; if set to false, it indicates that equivalent filtering is not supported.

**Comment by zzyReal666** [comment]
Could you  pls  give me an example of an algorithm where this property is true?

**Comment by zzyReal666** [comment]
> Could you pls give me an example of an algorithm where this property is true?



> The supportEquivalentFilter indicates whether the encryption algorithm supports equivalent filtering. In encrypted scenarios, traditional exact match queries may not be directly applicable due to the data being encrypted. If this property is set to true, it signifies that equivalent filtering technique can be utilized to query encrypted data; if set to false, it indicates that equivalent filtering is not supported.

Could you pls give me an example of an algorithm where this property is true?

**Comment by strongduanmu** [comment]
> Could you pls give me an example of an algorithm where this property is true?
@zzyReal666 Currently, ShardingSphere does not provide a similar algorithm. You can implement it yourself, such as adding an additional timestamp to the encrypt key.

**Comment by zzyReal666** [comment]
> > Could you pls give me an example of an algorithm where this property is true?
> 
> @zzyReal666 Currently, ShardingSphere does not provide a similar algorithm. You can implement it yourself, such as adding an additional timestamp to the encrypt key.

If I'm not sure about this property（supportEquivalentFilter）, can I set this property to false?

**Comment by strongduanmu** [comment]
Sorry, this is my mistake. Usually this attribute of encryption algorithm is true and supports equal value filtering. Only for special algorithms, such as when the encrypt key is timestamp added, the property needs to be set to false.
