### ISSUE TITLE
Add more unit test for them

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#30524]
- [ ] DataSourceUnitPersistService
- [ ] DataSourceNodePersistService
- [ ] DatabaseRulePersistService
- [ ] TableMetaDataPersistService
- [ ] ViewMetaDataPersistService
- [ ] PropertiesPersistService
- [ ] GlobalRulePersistService
- [ ] DatabaseMetaDataPersistService
- [ ] MetaDataVersionPersistService
- [ ] StandaloneContextManagerBuilder
- [ ] ResourceMetaDataChangedSubscriber
- [ ]  PropertiesChangedWatcher
- [ ]  GlobalRuleChangedWatcher
- [ ]  ConfigurationChangedSubscriber
- [ ]  ClusterModeContextManager
- [ ]  MetaDataChangedWatcher

**Comment by sroopsai** [comment]
I would like to contribute for this issue. I am new to this project, so I need little guidance on how to proceed.

**Comment by zhaojinchao95** [comment]
> I would like to contribute for this issue. I am new to this project, so I need little guidance on how to proceed.

Hi, you can refer to : https://shardingsphere.apache.org/community/en/involved/contribute/contributor/

**Comment by Aias00** [comment]
i wanna do some help, and i just make a pr.

**Comment by mistymisti** [comment]
Hi, Am new to this project, I am trying to install this product and facing an issue when product installation, can anyone help ?
![Uploading Screenshot (24).png…]()

**Comment by zhaojinchao95** [comment]
This class are removed in `master` branch. So, i will close it.
