### ISSUE TITLE
sharding table uses a large number of union all, Actual SQL table name problem

### ISSUE THREAD

**Issue by wting1123** [apache/shardingsphere#30530]
### version
shardingsphere-jdbc-core-spring-boot-starter 5.2.1

### config
![image](https://github.com/apache/shardingsphere/assets/54521069/83727e3f-d584-4d6f-91a0-873b62b33f8f)

### Logic SQL
select count(0)
from (
select * from device_alarm where alarm_time <= ? AND mac_sn = 001
union all
select * from device_alarm where alarm_time >= ? AND alarm_time <= ? AND mac_sn = 002
union all
select * from device_alarm where alarm_time >= ? AND alarm_time <= ? AND mac_sn = 003
union all
select * from device_alarm where alarm_time >= ? AND alarm_time <= ? AND mac_sn = 004
union all
select * from device_alarm where alarm_time >= ? AND alarm_time <= ? AND mac_sn = 005
union all
select * from device_alarm where alarm_time >= ? AND mac_sn = 006
) table_count

![image](https://github.com/apache/shardingsphere/assets/54521069/f37f027b-ed57-404c-b90a-fbe99f56077d)

### Actual SQL
![image](https://github.com/apache/shardingsphere/assets/54521069/b72a162b-8803-4daf-aa7d-c22bdd21197c)

**Comment by wting1123** [comment]
![image](https://github.com/apache/shardingsphere/assets/54521069/39cd27d8-cd21-47ad-98d5-7cf9269ab596)

**Comment by RaigorJiang** [comment]
Hi @wting1123 
Thanks for your feedback, can you try the latest version 5.4.1?

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
