### ISSUE TITLE
When `check-table-metadata-enabled` is enabled, having different index names for sharded tables will result in an error.

### ISSUE THREAD

**Issue by JinZhang-96** [apache/shardingsphere#30547]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Metadata can pass the check.
### Actual behavior
The error is caused by the different index names in different sharded tables.
### Reason analyze (If you can)
the different index names in different sharded tables.

**Comment by RaigorJiang** [comment]
Different indexes actually mean inconsistent metadata, which is in line with the design purpose.
