### ISSUE TITLE
How do I change a data source to Druid in Shardingsphere JDBC5.4.1

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere#30554]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
use druid

### Actual behavior
use hikari

**Comment by zhuruixuan** [comment]
Please describe the title in English, please change it back to English, thank you

**Comment by RaigorJiang** [comment]
You may use `dataSourceClassName`

**Comment by zzyReal666** [comment]
step 1 ： Add dependencies.  `  <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.2.9</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-autoconfigure</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`
step 2 ：change your config.xml.   Pay attention to this `url`,not `jdbcUrl`
![image](https://github.com/apache/shardingsphere/assets/34822229/643ab9b2-cb0f-454b-a4d7-0108a96e2af3)

**Comment by RaigorJiang** [comment]
@zzyReal666 Thanks for sharing, it's a good reference

**Comment by RaigorJiang** [comment]
Closed due to no response.
If you still have questions, please reopen it or submit a new one.
