### ISSUE TITLE
Add test cases for implementations of RuleConfigurationToDistSQLConverter

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30628]
FYI: BroadcastRuleConfigurationToDistSQLConverterTest

### Tasks
- [ ] EncryptRuleConfigurationToDistSQLConverter
- [ ] MaskRuleConfigurationToDistSQLConverter
- [ ] ReadwriteSplittingRuleConfigurationToDistSQLConverter
- [ ] ShadowRuleConfigurationToDistSQLConverter
- [ ] ShardingRuleConfigurationToDistSQLConverter
- [ ] SingleRuleConfigurationToDistSQLConverter

**Comment by sroopsai** [comment]
Hi @RaigorJiang can you assign me for this issue.

**Comment by RaigorJiang** [comment]
Welcome @sroopsai

**Comment by sroopsai** [comment]
@RaigorJiang can you review my PR 🙂.
