### ISSUE TITLE
Modify sql-show not work

### ISSUE THREAD

**Issue by yuge1805** [apache/shardingsphere#30657]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

I want to print SQL. Follow the documentation to change the yaml configuration from false to true, but not working.
`props:
  sql-show: true`

### Actual behavior

SQL log is not printed

### Reason analyze (If you can)

![image](https://github.com/apache/shardingsphere/assets/45219837/0e97b23b-4fe1-4b3a-b6d0-8f1a09e48e33)

The configuration in zookeeper is used first, and the modification of the local yaml file not working.
I'm not sure if this is a BUG, I'm new to shardingsphere. After debugging, the problem of SQL logs not being printed was solved, which took a while.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

on first startup，sql-show: false；
Modify sql-show: true and restart the service；
SQL is not printed.

**Comment by linghengqian** [comment]
- I believe this behavior is documented at https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/ , ShardingSphere metadata will always be overwritten by the Metadata Repository's metadata.

> After parsing and loading the YAML file into ShardingSphere’s metadata, the next behavior will be determined again through the relevant configuration of Mode Configuration. Discuss two situations,
> ShardingSphere’s metadata does not exist in the Metadata Repository, and local metadata will be stored in the Metadata Repository.
> The metadata of ShardingSphere already exists in the Metadata Repository. Regardless of whether it is the same as the local metadata, the local metadata will be overwritten by the metadata of the Metadata Repository.

**Comment by zzyReal666** [comment]
config use a new zookeeper namespace or delete old zookeeper node.

**Comment by yuge1805** [comment]
Thanks for your reply, I know that now

**Comment by yuge1805** [comment]
> config use a new zookeeper namespace or delete old zookeeper node.

initialize zookeeper node  or delete old zookeeper node cost a lot of time ,  are you also that?

**Comment by zzyReal666** [comment]
> > config use a new zookeeper namespace or delete old zookeeper node.
> 
> initialize zookeeper node or delete old zookeeper node cost a lot of time , are you also that?

yeah，it cost a lot of time.But if it work,that means zookeeper config override your local config.you should update your zookeeper config ,local config is invalid.
