### ISSUE TITLE
How to dynamically add data sources based on Nacos in Shardingsphere 5.2.1 without restarting the service?

### ISSUE THREAD

**Issue by James-Zou** [apache/shardingsphere#30667]
**### sharing-jdbc 5.2.1 + Spring Boot + Nacos, I want to achieve dynamic governance of sharing-jdbc data sources. In the scenario where the service is not stopped, I want to be able to add or modify data source configurations in the Nacos configuration file, and have the service be able to update the new data source strategy in real-time without the need for a restart.******

**Comment by zzyReal666** [comment]
Now shardingphere not support Nacos.Maybe you should implement a new cluster for Nacos.
refer : `shardingsphere-cluster-mode-repository-provider`

**Comment by James-Zou** [comment]
> Now shardingphere not support Nacos.Maybe you should implement a new cluster for Nacos. refer : `shardingsphere-cluster-mode-repository-provider`
I see that there is an implementation of Nacos in the source code
<img width="867" alt="image" src="https://github.com/apache/shardingsphere/assets/16623321/6ce91bc3-c9e5-448f-8ce5-d5cc7775d122">

**Comment by zzyReal666** [comment]
> > Now shardingphere not support Nacos.Maybe you should implement a new cluster for Nacos. refer : `shardingsphere-cluster-mode-repository-provider`
> > I see that there is an implementation of Nacos in the source code
> 
> <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/16623321/317574114-6ce91bc3-c9e5-448f-8ce5-d5cc7775d122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTQ1MzgsIm5iZiI6MTcxMTU5NDIzOCwicGF0aCI6Ii8xNjYyMzMyMS8zMTc1NzQxMTQtNmNlOTFiYzMtYzllNS00NDhmLThjZTUtZDVjYzc3NzVkMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyNTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzc1OWExMzU0N2ExN2Q3ZDY4NjIxZTIwZjQzMzBkODY4OWY1YTJlZDExOGQ0ZWEyYWZkN2I1ODMyZGJjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.utcDCR031RQB-IUsLEZnmpLtSSzFdMFCxHDBiiA_Vzw">

sorry,it is my mistake. I dont find nacos info in doc.

**Comment by zzyReal666** [comment]
The latest version of nacos is available as a plug-in.

**Comment by James-Zou** [comment]
> The latest version of nacos is available as a plug-in.
 Thank you for your prompt. I only found this module, but I don't know how to use it. Do I need SPI injection? Are there any similar use cases, such as the tutorial on using Zookeeper, that I can refer to

**Comment by James-Zou** [comment]
I injected org. apache. shardingsphere. mode. repository. cluster. nacos in the form of spi NacosRepository found that it can only listen to changes in the configuration file and did not perform subsequent operations such as re instantiation of the data source.
