### ISSUE TITLE
Rename `sharding` to `shardingsphere` in seata.conf to keep consistent with shardingsphere

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#30672]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Currently, SeataATShardingSphereTransactionManager still uses the outdated sharding prefix when loading the seata.conf configuration file. Sharding is the past name of shardingsphere. In order to ensure consistency with the concept of shardingsphere, we need to adjust these attribute prefixes and rename sharding to shardingsphere.

```java
public SeataATShardingSphereTransactionManager() {
    FileConfiguration config = new FileConfiguration("seata.conf");
    enableSeataAT = config.getBoolean("sharding.transaction.seata.at.enable", true);
    applicationId = config.getConfig("client.application.id");
    transactionServiceGroup = config.getConfig("client.transaction.service.group", "default");
    globalTXTimeout = config.getInt("sharding.transaction.seata.tx.timeout", 60);
}
```

**Comment by TherChenYang** [comment]
@strongduanmu This issue can be assigned to me. I previously created an issue identical to this one and will close the corresponding issue.#30671

**Comment by strongduanmu** [comment]
@TherChenYang Assigned. Thank you for your continued contributions.
