### ISSUE TITLE
ShardingSphereResultSet 解析的columnLabelAndIndexMap 少于sql中对应的字段？

### ISSUE THREAD

**Issue by xjjva520** [apache/shardingsphere#30684]
ShardingSphereResultSet 解析的columnLabelAndIndexMap 少于sql中对应的字段？

对应版本
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.2</version>

sql中对应的字段有23，但是解析到columnLabelAndIndexMap  只有18了，带sum函数的全部没解析出来
![1711631304492](https://github.com/apache/shardingsphere/assets/24364311/4618abc8-0abd-4ea3-ac6b-ec3a2c5702ed)
<img width="926" alt="1711631397618" src="https://github.com/apache/shardingsphere/assets/24364311/800fd84c-0882-43ca-8947-76fc058aab01">
异常信息
<img width="813" alt="1711631487517" src="https://github.com/apache/shardingsphere/assets/24364311/5c89f75e-15f8-4574-9e66-c0f205edbedf">

**Comment by strongduanmu** [comment]
Can you translate this issue to English?

**Comment by xjjva520** [comment]
shardingsphere-jdbc-core-spring-boot-starter version is 5.1.2
issue: columnLabelAndIndexMap will give up AggregationProjection, Resulting in some fields in t. * not being mapped。
The problem lies in the following picture
<img width="705" alt="162c5078fa6705f3f6a1ee228330f08" src="https://github.com/apache/shardingsphere/assets/24364311/95d4f9a9-976d-4643-b63b-00545ed7a42a">

**Comment by strongduanmu** [comment]
For English only, other language will not accept.
