### ISSUE TITLE
BatchPreparedStatementExecutor ArrayIndexOutOfBoundsException!

### ISSUE THREAD

**Issue by CodingJabber** [apache/shardingsphere#30696]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
execute success

### Actual behavior
throw java.lang.ArrayIndexOutOfBoundsException: 0
at org.apache.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.accumulate(BatchPreparedStatementExecutor.java:192)

### Reason analyze (If you can)
this is same object, but not equals, I do not know why?It resulted in no SQL being executed, subsequently causing an exception when attempting to retrieve the affected count.
![image](https://github.com/apache/shardingsphere/assets/6846212/973420cd-5b2d-4ea1-b873-9433feedaf17)

I think these two have the same problem:
#1419 #8577

**Comment by strongduanmu** [comment]
Hi @CodingJabber, can you try the latest 5.4.1? 4.0.0 is too old.

**Comment by RaigorJiang** [comment]
Closed due to no response.
If this problem persists, please reopen it or submit a new one.
