### ISSUE TITLE
shardingsphere-transaction-core Transaction not enabled

### ISSUE THREAD

**Issue by Bob6474** [apache/shardingsphere#30721]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Inherit the XID of the upstream service and enable the seata transaction

### Actual behavior
not init transaction

### Reason analyze (If you can)
<img width="885" alt="image" src="https://github.com/apache/shardingsphere/assets/165616340/032fce71-c0d6-47db-a8ca-e667979304c3">
<img width="740" alt="image" src="https://github.com/apache/shardingsphere/assets/165616340/9c3612da-1776-4afe-b68b-e9c799260e79">
<img width="291" alt="image" src="https://github.com/apache/shardingsphere/assets/165616340/19516038-2786-438b-8e71-436705a3881d">

**Comment by linghengqian** [comment]
- I opened https://github.com/apache/shardingsphere/pull/32095 to fix this issue. Friends who follow the current issue can review it.
