### ISSUE TITLE
ShardingShpere proxy, how to execute create database command to backend db server ?

### ISSUE THREAD

**Issue by Gii16** [apache/shardingsphere#30744]
I execute create database xxx in mysql client, the request is not actually forward to backend db server. The code is run into CreateDatabaseBackendHandler, and just update the local context.
Is there any way that i could forward the request to the backend db server?

**Comment by Gii16** [comment]
以及想知道为什么TextProtocolBackendHandlerFactory中把DCLStatement封禁了？

**Comment by strongduanmu** [comment]
Can you translate this issue to English?

**Comment by Gii16** [comment]
> Can you translate this issue to English?

all right

**Comment by strongduanmu** [comment]
ShardingSphere only supports the creation of logical database; physical database need to be created on MySQL.

**Comment by Gii16** [comment]
> ShardingSphere only supports the creation of logical database; physical database need to be created on MySQL.

Thanks a lot for your answer.
