### ISSUE TITLE
MySQL max() in nested subquery fails

### ISSUE THREAD

**Issue by malachany** [apache/shardingsphere#30764]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

Tested in v5.41 and v5.4.2-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Expected to return a list of recent chat_messages 
### Actual behavior

In 5.41: `General error: 30000 Unknown exception: Cannot convert 2022-09-14T18:25:06 to long`
In 5.4.2-SNAPSHOT: `SQL federation doesn't support SQL`

### Reason analyze (If you can)

It looks like the MAX(created_at) isn't working correctly, and instead of showing the max DATETIME, it's trying to convert it to LONG.

One thing to note is that if I run the subquery by itself, it works fine.. it's only with it in the subquery that seems to be a problem:

```
SELECT
    ->     MAX(id) max_id,
    ->     chat_id,
    ->     MAX(created_at) created_at
    ->   FROM chats_messages
    ->   GROUP BY chat_id;
+--------+---------+---------------------+
| max_id | chat_id | created_at          |
+--------+---------+---------------------+
|      1 |       1 | 2022-09-14 18:25:06 |
|      2 |       2 | 2022-09-15 21:37:17 |
|     32 |       3 | 2022-10-26 09:06:24 |
|     34 |       4 | 2022-10-26 14:41:22 |
|      9 |       5 | 2022-09-16 19:18:45 |
|     11 |       6 | 2022-09-26 09:11:29 |
|     12 |       7 | 2022-09-30 19:05:20 |
|     13 |       8 | 2022-10-07 16:40:07 |
```

this works fine

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

This is the query:
```
SELECT
  members.chat_id,
  mess_max.created_at message_sent
FROM chats_members members 
JOIN (
  SELECT
    MAX(id) max_id,
    chat_id,
    MAX(created_at) created_at
  FROM chats_messages
  GROUP BY chat_id
) mess_max on mess_max.chat_id = members.chat_id
LEFT JOIN chats_messages_read_by_recipient is_read
  ON mess_max.max_id = is_read.chat_message_id AND is_read.created_by = 5094
WHERE (members.user_id = 5094 OR members.group_id IN('13'))
  AND is_read.id IS NULL;
```

**Comment by strongduanmu** [comment]
Hi @malachany, thank you for your feedback. Are you using SQL Federation? Can you provide your YAML configuration and table initialization SQL? I want to try to reproduce this exception.

**Comment by malachany** [comment]
@strongduanmu , thank you for the fast reply. I'll create an example project with the same settings to replicate it. Will get that to you later today. 🙏🏻

**Comment by strongduanmu** [comment]
@malachany Thank you for your help, I will try to reproduce and fix the problem.

**Comment by malachany** [comment]
Sounds good, thank you

**Comment by malachany** [comment]
Hey @strongduanmu. Checking in to see if there's any update in regards to reproducing the problem. Thanks

**Comment by malachany** [comment]
Hey @strongduanmu , checking in on this. Hope you had a good weekend

**Comment by strongduanmu** [comment]
@malachany Sorry, I'm very busy recently, I will take some time this week to investigate this issue.

**Comment by malachany** [comment]
No worries. Thanks for the update

**Comment by zihaoAK47** [comment]
@malachany Hello, we have investigated the issue and currently you can resolve it using any of the following methods:

Change the data type of your table field from `datetime` to another date type.
Try downgrading your MySQL driver, or use `mysql-connector-java` as the MySQL driver. The version I tested with is 8.0.13. 
Ref: https://mvnrepository.com/artifact/mysql/mysql-connector-java

![test](https://github.com/apache/shardingsphere/assets/106047330/f536686a-f886-4d52-9f27-c99fcf90f802)

**Comment by malachany** [comment]
thanks @strongduanmu  and @zihaoAK47 for looking into this

**Comment by strongduanmu** [comment]
@malachany You are welcome to help us test sql federation. This feature is very important to ShardingSphere and can greatly improve the usage scenarios of ShardingSphere.

**Comment by malachany** [comment]
@strongduanmu I'll be pulling latest and testing this out soon and will update you :)
