### ISSUE TITLE
What's the differences between data masking and data encrpytion?

### ISSUE THREAD

**Issue by Gii16** [apache/shardingsphere#30803]
https://shardingsphere.apache.org/document/current/en/features/encrypt/
https://shardingsphere.apache.org/document/current/en/features/mask/
look like the same

**Comment by strongduanmu** [comment]
Hi @Gii16, the encrypt feature will encrypt the data before storing it in the DB and decrypt it when querying. The mask feature will not perform any processing on the data in the DB. It will only modify the displayed content based on the mask algorithm after querying.

**Comment by Gii16** [comment]
> Hi @Gii16, the encrypt feature will encrypt the data before storing it in the DB and decrypt it when querying. The mask feature will not perform any processing on the data in the DB. It will only modify the displayed content based on the mask algorithm after querying.

Thank you!
