### ISSUE TITLE
 spring-boot-starter-parent 3.2.4 use shardingsphere-jdbc-core 5.4.1 throw NoSuchMethodError

### ISSUE THREAD

**Issue by diqiulikai** [apache/shardingsphere#30816]
<img width="1345" alt="image" src="https://github.com/apache/shardingsphere/assets/32244751/32fbf2c0-ad05-4129-9a21-da34b732d23b">

 spring-boot-starter-parent 3.2.4 dependency  org.yaml.snakeyaml 2.2,
        There is no default constructor available in 'org.yaml.snakeyaml.representer.Representer' 
Can the org. yaml. snakeyaml used by shardingsphere jdbc core also be upgraded to 2.2

**Comment by linghengqian** [comment]
- Fixed in #28805.

**Comment by linghengqian** [comment]
- Closed due to no reply.
