### ISSUE TITLE
Version 5.4.1 of ShardingSphere references SnakeYAML version 1.33, which has a security vulnerability. How to upgrade it?

### ISSUE THREAD

**Issue by James-Zou** [apache/shardingsphere#30856]
Version 5.4.1 of ShardingSphere references SnakeYAML version 1.33, which has a security vulnerability. How to upgrade it?

**Comment by James-Zou** [comment]
<img width="872" alt="image" src="https://github.com/apache/shardingsphere/assets/16623321/31635c0a-5d06-4448-8de8-ee029540f0c7">

**Comment by linghengqian** [comment]
- This obviously only requires manually compiling the master branch to migrate to 5.4.2-SNAPSHOT. Refer to https://github.com/apache/shardingsphere/issues/30318#issuecomment-2002341706 .

**Comment by linghengqian** [comment]
Closed due to no response.
