### ISSUE TITLE
TableNotExistsException: Table or view *** does not exist

### ISSUE THREAD

**Issue by shijie-328931589** [apache/shardingsphere#30860]
### Which version of ShardingSphere did you use?
5.4.1 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
When loading postgresql database schema，SchemaMetaDataLoader should load TABLE、VIEW、SYSTEM TABLE、SYSTEM TABLE、SYSTEM VIEW  and PARTITION TABLE
### Actual behavior
SchemaMetaDataLoader not load PARTITION TABLE，when do query from pg PARTITION TABLE, will appear org.apache.shardingsphere.infra.exception.TableNotExistsException 
### Reason analyze (If you can)
when load database tables, SchemaMetaDataLoader should add PARTITION TABLE.

**Comment by strongduanmu** [comment]
Can you give an example to describe the problem about partition table? I'm sorry, I'm not familiar with PostgreSQL partitioned tables and would like to learn more information.
