### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by Swastyy** [apache/shardingsphere#30877]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!
### Actual behavior
![image](https://github.com/apache/shardingsphere/assets/64654203/672eee42-cfcd-4424-a7a6-9a772c5cd4ac)
![image](https://github.com/apache/shardingsphere/assets/64654203/83d06065-6cbc-4121-be81-6e861c6b94a2)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
After clicking on the image icon on the Readme, it shows the error( see second screenshot)

**Comment by TherChenYang** [comment]
@Swastyy Thank you very much for your feedback, I will handle it.
