### ISSUE TITLE
gbase 8s Compatibility issues

### ISSUE THREAD

**Issue by leihj123** [apache/shardingsphere#30888]
Hello，
In our project，we use the gbase 8s database, sharding-JDBC for 5.1.0 , the project can't start correctly. The attachment is the error.
[long_text_2024-04-15-09-29-45.txt](https://github.com/apache/shardingsphere/files/14973384/long_text_2024-04-15-09-29-45.txt)

How could I solve this problem?

**Comment by strongduanmu** [comment]
Hi @leihj123, thank you for your feedback. Currently, ShardingSphere has no plans to support commercial databases.

**Comment by strongduanmu** [comment]
There is no plan to support commercial databases.
