### ISSUE TITLE
Provides Standalone Mode implementations of hsqldb and apache/derby

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#30926]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Yes. The current issue is a wrap-up of #30656.

### Describe the feature you would like.

- Provides Standalone Mode implementations of hsqldb and apache/derby. Just like `com.h2database:h2`. This involves testing three JDBC Drivers in `org.apache.shardingsphere:shardingsphere-standalone-mode-repository-jdbc`.
    - [x] `org.apache.derby.jdbc.EmbeddedDriver`/`org.apache.derby:derby`
    - [x] In order to use apache/derby in client/server mode, we may need to additionally implement the relevant xml of `org.apache.derby.jdbc.ClientDriver`. This requires `org.apache.derby:derbyclient`.
    - [x] `org.hsqldb.jdbc.JDBCDriver`/`org.hsqldb:hsqldb`

- This actually alleviates somewhat the argument in #30835 that the so-called h2database driver class name may become obsolete in the future. And the so-called avoidance of the need to use h2database on shardingsphere jdbc without introducing third-party database middleware.

**Comment by linghengqian** [comment]
- There is a very awkward problem. `org.apache.derby:derby:10.17.1.0` limits itself to run only on JDK 19-JDK 22, which surprised me. Of course, it may also run on unreleased JDK23-JDK24.

**Comment by terrymanu** [comment]
How about add derby for now only?

**Comment by linghengqian** [comment]
- `org.apache.shardingsphere.mode.repository.standalone.jdbc.JDBCRepositoryTest` also surprised me when mocking the in-memory database h2database. 
- At the same time, Embedded Derby also creates a lot of local files. I'm considering delaying providing unit tests for Derby due to the immutability of the relevant directory paths. PR is still in preparation.
```bash
java.lang.UnsupportedClassVersionError: org/apache/derby/jdbc/EmbeddedDriver has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.zaxxer.hikari.HikariConfig.attemptFromContextLoader(HikariConfig.java:973)
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:483)
	at com.lingh.DatabaseTest.test(DatabaseTest.java:16)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by terrymanu** [comment]
However, h2 or derby is not important, is it?

It is for memory, user do not need aware the memory db.

**Comment by linghengqian** [comment]
> However, h2 or derby is not important, is it?
> 
> It is for memory, user do not need aware the memory db. Maybe one db adapt is enough.

- Yes, but the source of the current issue is #30656, and related issues require solutions other than H2 Database. This is a CVE reported issue specific to Synk.

**Comment by terrymanu** [comment]
If Derby is used to completely replace H2, can it keep the same functionality while solving security issues?

I‘d like to think that using an unique memory database, as it can effectively reduce the complexity of ShardingSphere.

**Comment by linghengqian** [comment]
> If Derby is used to completely replace H2, can it keep the same functionality while solving security issues?
> 
> I‘d like to think that using an unique memory database, as it can effectively reduce the complexity of ShardingSphere.

I don't think I have an answer for this to a large extent. I have never compared the performance of H2Database, Derby, and HyperSQL Database when used as embedded databases.

**Comment by terrymanu** [comment]
Standalone mode for H2 is pretty easy, just find a database can be persist into memory.
Follow JDBC and SQL92 is enough.

**Comment by linghengqian** [comment]
> Standalone mode for H2 is pretty easy, just find a database can be persist into memory.
> Follow JDBC and SQL92 is enough.

In my local environment, embedded Derby does not work with JDK18 and below. I haven't had time to open an issue on the Derby side. It's hard to say whether this is a generally available replacement for the shardingsphere.

**Comment by terrymanu** [comment]
How about hsqldb, is there any CVE on it?

**Comment by linghengqian** [comment]
> How about hsqldb, is there any CVE issues on it?

- I updated https://github.com/apache/shardingsphere/pull/32192 to include the four usage paths of hsqldb. hsqldb works fine when executing the relevant SQL under jdk8, but I did not do further testing.
- The reason the PR is still in draft is that the issue involved on the derby side has not been opened yet.

**Comment by terrymanu** [comment]
I suggest removing the support for Derby and H2, and only keep HSQLDB.
After all, memory databases do not need to be aware by users, and there is not much need to support more than one memory database.

**Comment by linghengqian** [comment]
> I suggest removing the support for Derby and H2, and only keep HSQLDB.
> After all, memory databases do not need to be aware by users, and there is not much need to support more than one memory database.

- Even so, we can't completely eliminate the use of h2database in shardingsphere. Because the master branch uses h2database's mysql mode to simulate the use of mysql, and there is also dialect parsing of h2database's mysql mode. From my point of view, it is unlikely to choose a complete replacement instead of providing an alternative. Of course, hsqldb also provides a mysql compatibility mode, namely https://hsqldb.org/doc/2.0/guide/compatibility-chapt.html . But I would say that this still looks like a lot of work.
