### ISSUE TITLE
Currently not supported by activiti7. Is there a plan to support it

### ISSUE THREAD

**Issue by sawyerli135** [apache/shardingsphere#30980]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by sawyerli135** [comment]
ShardingSphere JDBC is not compatible with activiti7 process engine SQL syntax

**Comment by linghengqian** [comment]
- I still don't understand under what circumstances this bug occurs. Can you use testcontains-java to write a unit test that contains expected errors? Just attach it to a git.

**Comment by sawyerli135** [comment]
Error updating database. Cause: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
The error may exist in org/activiti/db/mapping/entity/Comment.xml
The error may involve org.activiti.engine.impl.persistence.entity.CommentEntity.insertComment-Inline
The error occurred while setting parameters
SQL: insert into ACT_HI_COMMENT (ID_, TYPE_, TIME_, USER_ID_, TASK_ID_, PROC_INST_ID_, ACTION_, MESSAGE_, FULL_MSG_) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
Cause: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)

**Comment by linghengqian** [comment]
- This Log can't actually explain anything, because the shardingsphere stack is not involved at all. You need to provide reproduction steps or unit tests.

**Comment by linghengqian** [comment]
Closed due to no response.
