### ISSUE TITLE
The order by subquery was not parsed successfully

### ISSUE THREAD

**Issue by jiangzj2024** [apache/shardingsphere#31039]
Query A:
select * from user_info001
union all 
select * from user_info002
order by id;

Query B:
select * from (
select * from user_info001
union all 
select * from user_info002) a
order by id;

Query A Global sorting of multiple horizontal sub-database；
Query B Individual sub-database are sorted independently，The order by subquery was not parsed successfully

**Comment by TherChenYang** [comment]
@jiangzj2024 Thank you very much for your feedback, Can you provide a test demo? This can help me locate the problem faster.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
