### ISSUE TITLE
Chinese encoding problem of fuzzy query in federated query

### ISSUE THREAD

**Issue by umll** [apache/shardingsphere#31044]
### Which version of ShardingSphere did you use?
SharingSphere-proxy5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Execute the following sql and successfully search the data
`SELECT ti.account_id, ai.account_email FROM topicset_info ti, account_info ai WHERE ti.account_id=ai.account_id AND ti.topicset_name LIKE CONCAT('%', '测试', '%')`
### Actual behavior
No data was retrieved after execution
### Reason analyze (If you can)
According to the log information, it may be that the Chinese encoding in the sql is incorrect during the federated query, resulting in no data being retrieved.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I only configured distributed and federated queries.
This is the log information:
`[INFO ] 2024-04-28 10:50:20.444 [ShardingSphere-Command-2] ShardingSphere-SQL - Logic SQL: SELECT `account_id` FROM `oj_new`.`topicset_info` WHERE `topicset_name` LIKE CONCAT('%', '\u6d4b\8bd5', '%')
[INFO ] 2024-04-28 10:50:20.444 [ShardingSphere-Command-2] ShardingSphere-SQL - Actual SQL: oj_topic ::: SELECT `account_id` FROM `topicset_info` WHERE `topicset_name` LIKE CONCAT('%', '\u6d4b\8bd5', '%')
[INFO ] 2024-04-28 10:50:20.457 [ShardingSphere-Command-2] ShardingSphere-SQL - Logic SQL: SELECT `account_id`, `account_email` FROM `oj_new`.`account_info`
[INFO ] 2024-04-28 10:50:20.457 [ShardingSphere-Command-2] ShardingSphere-SQL - Actual SQL: oj_user ::: SELECT `account_id`, `account_email` FROM `account_info`
`

**Comment by strongduanmu** [comment]
Hi @umll, can you try master branch? This issue is duplicated with #30918

**Comment by strongduanmu** [comment]
Since this issue has been fixed in master branch, I will close it.
