### ISSUE TITLE
SpringBoot project return format is not json

### ISSUE THREAD

**Issue by RealHeart** [apache/shardingsphere#31067]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.5.1-SNAPSHOT(d48a6c88da6e7eda41e0e0e85123247fa5aeb405)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
return json
### Actual behavior
return xml
### Reason analyze (If you can)
shardingsphere-jdbc > shardingsphere-standalone-mode-repository-provider > jackson-dataformat-xml

Because jackson-dataformat-xml exists

**Comment by linghengqian** [comment]
- Why is the Expected behavior "return json"? You need to provide unit tests.

**Comment by RealHeart** [comment]
> * Why is the Expected behavior "return json"? You need to provide unit tests.

Under normal circumstances, my API returns JSON, after introducing shardingsphere, because it contains jackson-dataformat-XML, Springboot will support returning XML-type content, the browser's accept content-type XML is higher than JSON, and the, this results in a preference for XML output, with the expectation of JSON, and my current solution is to change the default MediaType and skip the accept content-type detection to return the JSON format by default

**Comment by linghengqian** [comment]
- This is essentially one of the automatic configurations that spring boot does, and I recommend that you look for ways to define spring beans in the github issue area of spring boot to change the default configuration. The ShardingSphere uses jackson to parse xml for historical reasons, involving both spring boot and graalvm native image. Reference #29384 .

**Comment by linghengqian** [comment]
- By the way, the current issue appears to be a copy of both https://github.com/spring-projects/spring-boot/issues/32494 and https://github.com/spring-projects/spring-boot/issues/32647 , and neither of them has provided unit tests.
