### ISSUE TITLE
There seems to be a bug regarding the documentation

### ISSUE THREAD

**Issue by AntonyCheng** [apache/shardingsphere#31150]
# Version：shardingsphere-jdbc:5.5.0 + SpringBoot 2.7.18 &SpringBoot 3.2.5

# The Documentation:

![image](https://github.com/apache/shardingsphere/assets/88792183/d883a2a1-09d9-42e2-a9b2-deb1a5ed300c)

# My Question:

The YamlReadwriteSplittingRuleConfiguration.class has a prop:

``` java
@Getter
@Setter
public final class YamlReadwriteSplittingRuleConfiguration implements YamlRuleConfiguration {
    
    private Map<String, YamlReadwriteSplittingDataSourceRuleConfiguration> dataSources = new LinkedHashMap<>();
    
    private Map<String, YamlAlgorithmConfiguration> loadBalancers = new LinkedHashMap<>();
    
    @Override
    public Class<ReadwriteSplittingRuleConfiguration> getRuleConfigurationType() {
        return ReadwriteSplittingRuleConfiguration.class;
    }
}
```

So it should not be `dataSourceGroups` but `dataSources` here. Will this property be updated?

**Comment by linghengqian** [comment]
- You are looking at the 5.5.1-SNAPSHOT documentation, and the class changes are in #31017. 

- For documents corresponding to 5.5.0, the quick entry should be displayed via #31149. Actual at https://shardingsphere.apache.org/document/5.5.0/en/overview/ .

**Comment by AntonyCheng** [comment]
Thank you. I have seen the corresponding update on the official website. I would like to ask when the official version of 5.5.1 will be released.

**Comment by linghengqian** [comment]
- If you expect a faster release, you should leave a message in a new mail thread at https://lists.apache.org/list.html?dev@shardingsphere.apache.org . 

- As a committer, I personally only have non-binding release voting right. In any case, according to ASF regulations, the release process must be completed on the mailing list, which has nothing to do with github.com.

**Comment by AntonyCheng** [comment]
I have learned about it, thank you!
