### ISSUE TITLE
Support for Extending New Data Types based on Trunk Database Type

### ISSUE THREAD

**Issue by wuwen5** [apache/shardingsphere#31151]
## Feature Request

Currently, the Trunk database type feature in our system allows for convenient expansion of new database implementations based on a certain database. However, there is a limitation in that it does not support the extension of new data types on this basis.
﻿
To address this limitation, we need to enhance the Trunk database type feature to support the extension of new data types. This enhancement will provide users with greater flexibility in defining and utilizing custom data types within the framework.

### Describe the feature you would like.
We can implement extended data types based on a specific DB without copying an implementation class （`DialectMetaDataLoader`）, the modifier for implementing a class is usually final, so it has to be copied.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
