### ISSUE TITLE
How to perform dynamic desensitization?

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#31175]
How to perform dynamic desensitization based on permission roles? For example, when the admin user logs in, he or she will see the plain text, but when the test user logs in, he or she will see the desensitized cipher text?

**Comment by freeman983** [comment]
@strongduanmu   sqldev.info

**Comment by strongduanmu** [comment]
Hi @Y-sir @freeman983, thank you for your feedback. Currently, due to the lack of user permission system in ShardingSphere, this function cannot be realized for the time being.

**Comment by terrymanu** [comment]
Sorry, this feature is not considered within the currently supported scope.
