### ISSUE TITLE
java.lang.NoSuchMethodError: '....PreciseShardingValue.getValue()'

### ISSUE THREAD

**Issue by kanling123** [apache/shardingsphere#31225]
help
use sharding-proxy5.5  Algorithm
Class Based Sharding Algorithm
![屏幕截图 2024-05-14 145440](https://github.com/apache/shardingsphere/assets/135492593/ea96543e-27d0-4a19-97f6-d02fe65d284e)
![屏幕截图 2024-05-14 145510](https://github.com/apache/shardingsphere/assets/135492593/67bde68b-7bdf-49e1-a29c-811a42131fb1)
![屏幕截图 2024-05-14 145743](https://github.com/apache/shardingsphere/assets/135492593/dfaf821e-bf0e-4da3-a135-c28fc7b25812)
 Algorithm

**Comment by zzyReal666** [comment]
It seems that the algorithm you implemented does not match the configuration file. Are you trying to get an unconfigured parameter in the algorithm?You need to provide more information or a repository.

**Comment by linghengqian** [comment]
Issue closed due to failure to reproduce.
