### ISSUE TITLE
SHA1 and AES/ECB still in used

### ISSUE THREAD

**Issue by Gax-c** [apache/shardingsphere#31223]
Hello, when I was browsing the code I found [SHA1](https://github.com/apache/shardingsphere/blob/master/features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java#L57) and [AES/ECB](https://github.com/apache/shardingsphere/blob/master/features/encrypt/core/src/main/java/org/apache/shardingsphere/encrypt/algorithm/standard/AESEncryptAlgorithm.java#L95) are still in use. Both of these two algorithms are insecure. 

SHA1 is used as the default digest algorithm, and it's clear that SHA1 is no longer secure, so I recommend switch to be better algorithm like SHA256. 

`Cipher.getInstance(getType())` will be `Cipher.getInstance("AES")`, and `Cipher.getInstance("AES")` will use AES/ECB in default, which is insecure. I suggest specify the mode and padding rather than using the default one.

**Comment by zzyReal666** [comment]
shardingsphere is a database enhancement project, and I don't think it should or should be responsible for the security of the algorithm, because it provides the SPI mechanism to implement the algorithm you need.
