### ISSUE TITLE
shardingsphere-jdbc-core framework no longer being updated and maintained? The latest version is only 5.4.1

### ISSUE THREAD

**Issue by xiohuchi** [apache/shardingsphere#31235]
## Question
shardingsphere-jdbc-core framework no longer being updated and maintained? 
shardingsphere-jdbc-core framework no longer being updated and maintained? 
shardingsphere-jdbc-core framework no longer being updated and maintained? 

maven shardingsphere-jdbc-core  ， The latest version is only 5.4.1：
[https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core](https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core)

**Comment by xiohuchi** [comment]
I don’t want to use ‘shardingsphere-sharding-core’, I want to use ‘shardingsphere-jdbc-core ’，
the shardingsphere-sharding-core is not have ShardingSphereURLProvider。

not this :
[https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-sharding-core](https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-sharding-core)

maven shardingsphere-jdbc-core ， The latest version is only 5.4.1：
[https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core](https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core)

**Comment by linghengqian** [comment]
- This is a fix from #30182, where `org.apache.shardingsphere:shardingsphere-jdbc-core` was renamed to `org.apache.shardingsphere:shardingsphere-jdbc` to resolve issue #22752 from 2 years ago. There is no logical difference between them.

**Comment by dnjat** [comment]
为什么老是改来改去的. 如果改了,是不是有替代方案? 大家拿你的库集成到框架内,发行一个版本,改变一下功能,大家都跟着你来更新,这次移除ShardingSphereURLProvider,让大家怎么更. 就连配置文件,都是改来改去.真是服了(从5-5.41, 这次还没测,缺少类.没法更了)

**Comment by dnjat** [comment]
为什么老是改来改去的. 如果改了,是不是有替代方案? 大家拿你的库集成到框架内,发行一个版本,改变一下功能,大家都跟着你来更新,这次移除ShardingSphereURLProvider,让大家怎么更. 就连配置文件,都是改来改去.真是服了(从5-5.41, 这次还没测,缺少类.没法更了)

**Comment by strongduanmu** [comment]
Since this question has been answered, I will close this issue.
