### ISSUE TITLE
Change the 16 shards of the original table to 32 shards

### ISSUE THREAD

**Issue by ttfont** [apache/shardingsphere#31242]
## Question

May I ask a question, now I want to change the 16 shards of the original table to 32 shards, will the original data be automatically balanced? How to operate?

**Comment by TherChenYang** [comment]
@ttfont For this scenario, the first thing you need to do is data migration and rebalance the data. You can use the built-in migration feature of ShardingSphere or tools like dataX to complete the data migration, and then change the corresponding sharding configuration after migration.

**Comment by ttfont** [comment]
I understand that the task is to migrate data from 16 shards to a new cluster with 32 shards.  @TherChenYang 

> @ttfont For this scenario, the first thing you need to do is data migration and rebalance the data. You can use the built-in migration feature of ShardingSphere or tools like dataX to complete the data migration, and then change the corresponding sharding configuration after migration.

**Comment by TherChenYang** [comment]
@ttfont The first thing you need to do is to migrate the data, and modify the ShardingSphere configuration after migration.
Maybe I didn't quite understand the automatically balanced part above, I understand that this isn't handled on the shardingSphere side.

**Comment by ttfont** [comment]
> @ttfont The first thing you need to do is to migrate the data, and modify the ShardingSphere configuration after migration. Maybe I didn't quite understand the automatically balanced part above, I understand that this isn't handled on the shardingSphere side.

After migrating the data, adjust the number of shards in ShardingSphere, and then migrate the data to ShardingSphere. Is that correct

**Comment by TherChenYang** [comment]
@ttfont Are you using the ShardingSphere-JDBC or ShardingSphere-Proxy? If it is the JDBC module, ShardingSphere is not responsible for data migration. You need to use a data migration tool to complete the migration of your 16 shards to 32 shards. During the migration process, for both old and new clusters, you need to perform dual write operations by reading data from the old cluster (16 shards). Once the overall migration process is completed, change ShardingSphere's configuration so that both read and write operations are routed to the new cluster.

**Comment by ttfont** [comment]
> Are you using the ShardingSphere-JDBC or ShardingSphere-Proxy? If it is the JDBC module, ShardingSphere is not responsible for data migration. You need to use a data migration tool to complete the migration of your 16 shards to 32 shards. During the migration process, for both old and new clusters, you need to perform dual write operations by reading data from the old cluster (16 shards). Once the overall migration process is completed, change ShardingSphere's configuration so that both read and write operations are routed to the new cluster.

@TherChenYang 3Q
