### ISSUE TITLE
MySQL statement, using join query, other libraries, causing the library name to be replaced

### ISSUE THREAD

**Issue by hmkelntuh085** [apache/shardingsphere#31311]
For example：
When I set up read-write separation, write uses the a library and read uses the b library.
SQL:
select * from  b.in_order_dt orderd
inner join c.erp_tm_sku sku
on orderd.sku_id = sku.id

The last executed SQL is：
select * from  b.in_order_dt orderd
inner join b.erp_tm_sku sku
on orderd.sku_id = sku.id

How should I configure it so that my library name is not replaced?

THANKS

**Comment by terrymanu** [comment]
What is libraries and library name?

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
