### ISSUE TITLE
File to compile error: org. Apache. Shardingsphere. Infra. Autogen. Version. ShardingSphereVersion couldn't find the problem.

### ISSUE THREAD

**Issue by DIDA-lJ** [apache/shardingsphere#31355]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use? 

5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy? 

ShardingSphere-JDBC

### Expected behavior

In InstanceMetaDataFactoryTest class, assertCreateJDBCInstanceMetaDataWithInstanceId and assertCreateProxyInstanceMetaDataWithInstanceId normally execution, an error will not occur.

### Actual behavior

The results are shown below:

![image-20240523004827697](https://github.com/apache/shardingsphere/assets/97254796/16a9239e-158b-4f50-ada2-bcbcad7a8a44)

### Reason analyze (If you can)

Infra/common/SRC/main/templates/org/apache/shardingsphere/infra/autogen/version/ShardingSphereVersion. Java has not been found.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Just need in IDEA run directly in the infra/common/SRC/test/Java/org/apache/shardingsphere/infra/instance/metadata/InstanceMetaDataFactoryTest Java，the corresponding method can be repeated.

### Example codes for reproduce this issue (such as a github link).

https://github.com/apache/shardingsphere/tree/bae03f1b8a800efa10f30ae937d02f2668f3a204

**Comment by TherChenYang** [comment]
@DIDA-lJ please execute the command and try again


```
./mvnw -DskipITs -DskipTests install -T1C
```

**Comment by DIDA-lJ** [comment]
OK，thanking you for your help

LotusMoon ***@***.***> 于2024年5月23日周四 11:18写道：
