### ISSUE TITLE
which is the last release version that can be compiled with jdk8?

### ISSUE THREAD

**Issue by darren-wang** [apache/shardingsphere#31379]
I read https://shardingsphere.apache.org/community/cn/involved/contribute/dev-env/ to know that JDK11+ is needed to set up dev environment, the PR https://github.com/apache/shardingsphere/pull/23550   also said that JDK11+ is forced.

However, there is only jdk8 in my organization and when I cloned the source code, I found `jdk8` profile in IDEA's maven view.  

So here comes my questions:

1. What is the meaning of 'jdk8' profile in the source code, does it mean that I can still compile the source code with jdk8 using this profile?
2. If I can NOT compile the latest release with jdk8, which is the last release whose source code can be compiled with jdk8? 
3. Could the latest release 5.5.0 be used with jre8, NOT compiling its source but only to use it with spring boot and jre8?

**Comment by zhaojinchao95** [comment]
1. Can't compile using `jdk8`
2. `5.3.1`
3. `ShardingSphere` can be used in the `jdk8` environment

**Comment by darren-wang** [comment]
> 1. Can't compile using `jdk8`
> 2. `5.3.1`
> 3. `ShardingSphere` can be used in the `jdk8` environment

@zhaojinchao95 Great thanks !!! And if we can NOT compile shardingsphere 5.5.0 on jdk1.8 even with profile `jdk8` , then what is the usage of maven profile `jdk8` in source code? Are there any docs on it?

**Comment by terrymanu** [comment]
Please see `https://github.com/apache/shardingsphere/blob/abaf4067f3f1df4e8e7c36fad0816c257a923287/.github/workflows/ci.yml` and search content `CI - Compile by JDK 11 and Run on JDK 8` to find the hint.
