### ISSUE TITLE
YamlReadwriteSplittingRuleConfiguration jar and soruce is diff

### ISSUE THREAD

**Issue by 402363967** [apache/shardingsphere#31387]
YamlReadwriteSplittingRuleConfiguration类
在shardingsphere-readwrite-splitting-core-5.5.0.jar 变量叫：dataSources
在github的源码中叫dataSourceGroups；按照官方的文档无法使用
---
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=dataSourceGroups for JavaBean=org.apache.shardingsphere.readwritesplitting.yaml.config.YamlReadwriteSplittingRuleConfiguration@5b1420f9
 in 'reader', line 34, column 5:
      - !READWRITE_SPLITTING
        ^
Unable to find property 'dataSourceGroups' on class: org.apache.shardingsphere.readwritesplitting.yaml.config.YamlReadwriteSplittingRuleConfiguration

**Comment by zhaojinchao95** [comment]
You should refer to[ 5.5.0](https://shardingsphere.apache.org/document/5.5.0/en/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting/) when you use` 5.5.0 ` version.
