### ISSUE TITLE
5.4.1 delete plainColumn,  how to save plain value  in encrypt rule?

### ISSUE THREAD

**Issue by xigongxiaoche** [apache/shardingsphere#31416]
## 5.4.1 delete plainColumn,  how to save plain value  in encrypt rule?

Previously, I used version 5.3.2, which supported querying with plaintext. After upgrading to 5.4.1, the plainColumn feature was removed. Can anyone tell me how to save plaintext in encryption rules and use it for queries?

**Comment by xigongxiaoche** [comment]
Thank you very much

**Comment by xigongxiaoche** [comment]
@terrymanu Distsql delete queryWithCipherColumn and plainColumn is not support in encryptColumn. Can you give me some suggestion of how to use plainColumn in encryptColumn? Or show me why 5.4.0 delete plainColumn

**Comment by strongduanmu** [comment]
Duplicate with #31429
