### ISSUE TITLE
can not get value on use ShardingSpherePreparedStament.getResultSet()

### ISSUE THREAD

**Issue by shijie-328931589** [apache/shardingsphere#31427]
### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
database: PostgreSQL
sql: update test_table set resume_number=resume_number+1 where id=#{id} returning resume_number
api: ShardingSphereConnection.prepareStatement(sql).getResultSet();
expected get resume_number
### Actual behavior
the resultSet is null
### Reason analyze (If you can)
the sql is not match condition "executionContext.getSqlStatementContext() instanceof SelectStatementContext || executionContext.getSqlStatementContext().getSqlStatement() instanceof DALStatement"

**Comment by terrymanu** [comment]
What is your configuration?
