### ISSUE TITLE
NPE occurs when import metadata

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#31425]
### Which version of ShardingSphere did you use?
5.5.0-release

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
`EXPORT METADATA` and `IMPORT METADATA` can be executed successfully.

### Actual behavior
`IMPORT METADATA` failed
<img width="1026" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/414407b3-d925-4926-a0b9-0bcb0640655b">

### Reason analyze (If you can)
After investigation, it was found that there was a null value in the exported props, causing NPE to occur during import.

<img width="447" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/e8458f58-c24c-4f42-a146-87917f5911d0">

**Comment by yx9o** [comment]
Let me see.
