### ISSUE TITLE
shrdingsphere-proxy desensitization is not effective

### ISSUE THREAD

**Issue by haha8541168** [apache/shardingsphere#31441]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
apache-shardingsphere-5.4.1-shardingsphere-proxy

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Data on desensitization

### Actual behavior
encrypted data

### Reason analyze (If you can)
1.**Queries with simple sql like:'select data_encript from my_table' can correctly access decrypted data**;
2.**When sqls with 'group by' and Queries with pagination then comes the encrypted data,the following is my sql and my cipher_column is 'description'** 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
When sqls with 'group by' and Queries with pagination then comes the encrypted data,the following is my sql and my cipher_column is 'description
select
	handle,
	descriptionfrom
    (
	select
		max(handle) as handle,
		max(description) as description
	from
		(
		select
			a.handle,
			b.description
		from
			box_url a
		left join box_url_t b on
			a.handle = b.box_url_bo
		where
			a.is_deleted = 0
	) t
	group by
		handle ) h

**Comment by terrymanu** [comment]
What is your configuration?
