### ISSUE TITLE
Oracle  Insert   Return  Into  sql , throw NoViableAltException

### ISSUE THREAD

**Issue by zhuzhiyang** [apache/shardingsphere#31456]
## Bug Report

oracle sql parse failed

```
insert into SYS_ACTION_LOG(ACTION_KEY, ACTION_NAME, ACTION_TIME, ACTION_USER_NAME, ID, IP, PARAMS, REMARK) values(? , ? , ? , ? , ? , ? , ? , ? ) RETURNING ID INTO ?

```
## Version

shardingsphere version: 5.4.1
oracle verion: oracle 11g

## Stacktrace

![image](https://github.com/apache/shardingsphere/assets/20536244/8e643944-b689-4398-95b3-d849f3abb054)

**Comment by terrymanu** [comment]
SQL parsing has seen compatibility improvements with each version. Could you please try the latest version?
