### ISSUE TITLE
It is hoped that ShardingSphere can add support for redis and produce a useful redis cluster proxy

### ISSUE THREAD

**Issue by wwtao1024** [apache/shardingsphere#31516]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by strongduanmu** [comment]
Hi @wwt164888, since ShardingSphere is an international community, can you translate this issue into English?
