### ISSUE TITLE
springboot2.2.0 relase + sharding jdbc 5.5.0  sql executed  very slow

### ISSUE THREAD

**Issue by xu-huadong** [apache/shardingsphere#31581]
When the sql is executed for the first time, the system will take 5 seconds to initialize three HikariDataSources, and the execution speed is very slow. The second time the same sql is executed, it is very fast. Why? Is it possible to initialize HikariDataSource when the system starts?
![1717486695525](https://github.com/apache/shardingsphere/assets/24771599/1eec3b28-72d1-4982-be5b-54991e5168eb)

**Comment by xu-huadong** [comment]
dataSources:
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl : jdbc:**********
    username: user
    password: 123456
    connectionTimeoutMilliseconds: 28000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 500
    minPoolSize: 100
rules:
  - !SHARDING
    tables:
      T_ORDER:
        actualDataNodes: ds1.T_ORDER_$->{0..2}
        tableStrategy:
          standard:
            shardingColumn: ORDER_ID
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: ORDER_ID
          keyGeneratorName: snowflake
        auditStrategy:
          auditorNames:
            - sharding_key_required_auditor
          allowHintDisable: true

    shardingAlgorithms:
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: T_ORDER_${ORDER_ID% 3}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
    auditors:
      sharding_key_required_auditor:
        type: DML_SHARDING_CONDITIONS

props:
  sql-show: true

**Comment by TherChenYang** [comment]
@xu-huadong I think this is not an issue with ShardingSpehere. When you start springboot, HikariCP completes the initialization work of related thread pools, including but not limited to starting several internal thread pools according to the configuration, creating initial connections according to the configuration, and validating connections based on initSql in the configuration. These are necessary processes during startup. After initializing the connection pool, you can then obtain corresponding connections from the connection pool to execute SQL statements.

**Comment by xu-huadong** [comment]
thank you ！
