### ISSUE TITLE
encryption sql rewrite miss quote

### ISSUE THREAD

**Issue by litianzhong** [apache/shardingsphere#31584]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
   SQL is run successful
p.NAME         AS      'patient.name',
### Actual behavior
p.NAME           AS patient.name,
Mysql throw syntax error

### Reason analyze (If you can)
Sql rewrite miss the single quote.

**Comment by TherChenYang** [comment]
@litianzhong Hello, may I ask if you can provide the complete configuration along with the corresponding full SQL to execute, or any relevant error message? With just the above information, we are unable to determine the problem.

**Comment by terrymanu** [comment]
Due to no feedback from the author for an long period, I am closing this issue for now.
