### ISSUE TITLE
why my yaml properties datasource contain _ will report error??

### ISSUE THREAD

**Issue by wonderfulxin** [apache/shardingsphere#31614]
here is my datasource config
shardingsphere:
datasource:
ds_test:
driver-class-name: com.mysql.cj.jdbc.Driver
jdbc-url: jdbc:mysql://192.168.137.10:3306/ds_test
password: mysql123
type: com.zaxxer.hikari.HikariDataSource
username: root
names: ds_test
props:
sql:
show: true

and here is the error

Configuration property name 'spring.shardingsphere.datasource.ds_test' is not valid:

    Invalid characters: '_'
    Bean: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'spring.shardingsphere.datasource.ds_test' so that it conforms to the canonical names requirements.

**Comment by wonderfulxin** [comment]
here is my datasource config
    shardingsphere:
        datasource:
            ds_test:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://192.168.137.10:3306/ds_test
                password: mysql123
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            names: ds_test
        props:
            sql:
                show: true


and  here is the  error

Configuration property name 'spring.shardingsphere.datasource.ds_test' is not valid:

    Invalid characters: '_'
    Bean: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'spring.shardingsphere.datasource.ds_test' so that it conforms to the canonical names requirements.

**Comment by wonderfulxin** [comment]
Do you have any compatibility solutions??

**Comment by zzyReal666** [comment]
The following is my configuration, which is OK in version 5.5.1:
![image](https://github.com/apache/shardingsphere/assets/34822229/239daa9a-6ff1-4a83-a6f8-2d27b06d3459)

**Comment by wonderfulxin** [comment]
> The following is my configuration, which is OK in version 5.5.1: ![image](https://private-user-images.githubusercontent.com/34822229/337555272-239daa9a-6ff1-4a83-a6f8-2d27b06d3459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDM0MDgsIm5iZiI6MTcxNzc0MzEwOCwicGF0aCI6Ii8zNDgyMjIyOS8zMzc1NTUyNzItMjM5ZGFhOWEtNmZmMS00YTgzLWE2ZjgtMmQyN2IwNmQzNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2NTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MGY5MTdiNTk3NGExNjhjOWE1MWZmMmRjODQwODljNTBiOGNmMDE0MTZhOTNkNzUzYjYwMDExYWYyMTE3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8Bzsjf9qYnJ_wvLI3R_TgTn8onAupTaUdzgbRADB80)

what is you shardingjdbc version?

**Comment by zzyReal666** [comment]
> > The following is my configuration, which is OK in version 5.5.1: ![image](https://private-user-images.githubusercontent.com/34822229/337555272-239daa9a-6ff1-4a83-a6f8-2d27b06d3459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDM0MDgsIm5iZiI6MTcxNzc0MzEwOCwicGF0aCI6Ii8zNDgyMjIyOS8zMzc1NTUyNzItMjM5ZGFhOWEtNmZmMS00YTgzLWE2ZjgtMmQyN2IwNmQzNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2NTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MGY5MTdiNTk3NGExNjhjOWE1MWZmMmRjODQwODljNTBiOGNmMDE0MTZhOTNkNzUzYjYwMDExYWYyMTE3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8Bzsjf9qYnJ_wvLI3R_TgTn8onAupTaUdzgbRADB80)
> 
> what is you shardingjdbc version?

As mentioned above, my ssp-jdbc is version 5.5.1

**Comment by wonderfulxin** [comment]
> > > The following is my configuration, which is OK in version 5.5.1: ![image](https://private-user-images.githubusercontent.com/34822229/337555272-239daa9a-6ff1-4a83-a6f8-2d27b06d3459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDM0MDgsIm5iZiI6MTcxNzc0MzEwOCwicGF0aCI6Ii8zNDgyMjIyOS8zMzc1NTUyNzItMjM5ZGFhOWEtNmZmMS00YTgzLWE2ZjgtMmQyN2IwNmQzNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2NTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MGY5MTdiNTk3NGExNjhjOWE1MWZmMmRjODQwODljNTBiOGNmMDE0MTZhOTNkNzUzYjYwMDExYWYyMTE3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8Bzsjf9qYnJ_wvLI3R_TgTn8onAupTaUdzgbRADB80)
> > 
> > 
> > what is you shardingjdbc version?
> 
> As mentioned above, my ssp-jdbc is version 5.5.1

ok   thanks !  mine is 4.0.0-RC1 .  i will try  you version

**Comment by terrymanu** [comment]
The version 4.x is out of service, please try version 5.5.x
