### ISSUE TITLE
Add RepositoryTupleSwapperEngineIT's impl cases into mvn install and Github action CI

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#31634]

**Comment by taojintianxia** [comment]
Intentionally modifying the assert of ShardingConfigurationRepositoryTupleSwapperEngineIT to failed, the screen shot shows that test cases with an IT suffix will also run.

<img width="1844" alt="image" src="https://github.com/apache/shardingsphere/assets/4112856/3a2e5648-dbb2-4f95-a7b3-5fb17982de4a">

**Comment by taojintianxia** [comment]
Intentionally modifying the assert of ShardingConstraintReviserTest to failed, the screen shot shows that test cases with an Test suffix will run.

<img width="1786" alt="image" src="https://github.com/apache/shardingsphere/assets/4112856/3a2a670a-2365-45ea-b12b-5708821961c5">
