### ISSUE TITLE
How to define sharding rules for a given schema?

### ISSUE THREAD

**Issue by JamesRTaylor** [apache/shardingsphere#31659]
## Question

I've seen your documentation [here](https://shardingsphere.apache.org/document/legacy/3.x/document/en/manual/sharding-proxy/configuration/) on how to define sharding rules for a schema, but I can't seem to find any example in your project that does this. What yaml file is `schemaName` allowed to be defined in? Is there a unit test or example that you can point me toward? I'm using 5.5.1-SNAPSHOT. Is the functionality described in your documentation still supported?

Thanks for the help!

**Comment by strongduanmu** [comment]
Hi @JamesRTaylor, the `schemaName` configuration has been adjusted to `databaseName` in version 5.x. If you want to use the PostgreSQL schema, you can directly use the CREATE SCHEMA statement and specify the schema prefix in SQL, for example: `SELECT * FROM schema.t_order`. In addition, please note that ShardingSphere currently does not support the `SET SEARCH_PATH` statement and can only be switched by specifying the schema in SQL.
