### ISSUE TITLE
Join condition not considered for query rewrite

### ISSUE THREAD

**Issue by JamesRTaylor** [apache/shardingsphere#31658]
### Which version of ShardingSphere did you use?
5.5.1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Testing through unit tests

### Expected behavior
The join condition should help determine how the logical query is rewritten.

### Actual behavior
Only the name of the column referenced seems to have an impact on how the logical query is rewritten. The join condition doesn't impact it at all. For example, if an inequality join condition is used, the join would need to be run across all shards, while with an equality join, you'd be able to run it against a single shard.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Add the following to select.xml and run ShardingSQLRewriterIT:

    <rewrite-assertion id="select_with_inequality_join">
        <input sql="SELECT * FROM t_account o, t_account_detail i WHERE o.account_id>i.account_id AND o.account_id = ?" parameters="100" />
        <output sql="SELECT * FROM t_account_0 o, t_account_detail_0 i WHERE o.account_id > i.account_id AND o.account_id = ?" parameters="100" />
        <output sql="SELECT * FROM t_account_0 o, t_account_detail_1 i WHERE o.account_id>i.account_id AND o.account_id = ?" parameters="100" />
    </rewrite-assertion>

ShardingSphere only produces the first output query, which is correct if the join condition is an equality join, but not if it's an inequality join. Note that if there's no correlation between the two tables being joined, ShardingSphere produces the expected output queries. For example, this is correct:

    <rewrite-assertion id="select_with_unconstrained_user">
        <input sql="SELECT * FROM t_account o, t_user u WHERE o.account_id=u.id AND o.account_id = ?" parameters="100" />
        <output sql="SELECT * FROM t_account_0 o, t_user_0 u WHERE o.account_id=u.id AND o.account_id = ?" parameters="100" />
        <output sql="SELECT * FROM t_account_0 o, t_user_1 u WHERE o.account_id=u.id AND o.account_id = ?" parameters="100" />
    </rewrite-assertion>

**Comment by yydeng626** [comment]
It is not a bug . t_account and t_account_detail have the same sharding rules ,  see the sharding-rule.yaml configuration
```
  bindingTables:
    - t_account, t_account_detail, t_account_view
    - t_order, t_order_new, t_order_item
    - t_user, t_user_extend
    - t_role, t_role_admin
```
Refer [https://shardingsphere.apache.org/document/5.1.0/en/features/sharding/concept/table/#binding-table](url) @JamesRTaylor @strongduanmu

**Comment by strongduanmu** [comment]
@yydeng626 Thank you for your feedback, I will close this issue.
