### ISSUE TITLE
I don't config db,but sharding always init by h2 db.

### ISSUE THREAD

**Issue by 806072719** [apache/shardingsphere#31684]
![image](https://github.com/apache/shardingsphere/assets/50563366/c7032a9c-2844-4656-95a2-f3d4208296d1)
this is my configuration
![image](https://github.com/apache/shardingsphere/assets/50563366/821b8f7a-762d-4a99-be22-093432d4f2bf)
my version is 
`   <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.2.1</version>
        </dependency>
`
I want to know how 2 config the datasource in my yml

**Comment by TherChenYang** [comment]
@806072719 After loading metadata, ShardingSphere defaults to storing it in the h2 database, so you will see that each connection pool loads h2.
