### ISSUE TITLE
SKIP_SQL_REWRITE=true, invalid

### ISSUE THREAD

**Issue by 13302516724** [apache/shardingsphere#31709]
The number of shards in the table is 4, using USER-ID as the shard key

Logic SQL: 
/* SHARDINGSPHERE_HINT: DISABLE_AUDIT_NAMES=sharding_key_required_auditor, SKIP_SQL_REWRITE=true */ 
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}

Actual SQL：
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}
UNION ALL
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}
UNION ALL
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}
UNION ALL
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}

**How to effectively skip rewriting**

**expect**
SELECT * FROM T_ACCOUNT WHERE USERNAME=#{username} AND APP_ID = #{appId}

**Comment by terrymanu** [comment]
I apologize, but your description is too brief for me to understand your intent. Could you please clarify your issue and purpose more clearly?
