### ISSUE TITLE
MySQL parsing defect

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#31710]
Using getText here results in the retrieved string value not containing the spaces from the original value.

![image](https://github.com/apache/shardingsphere/assets/20572131/bf94e954-ed7c-4ad6-bfc2-cf90b6bfae58)

Code location: org. apache. shardingsphere. sql. parser. mysql. visitor. statement. MySQLStatementVisitor.visitJsonTableFunction

Test case id: **select_from_join_with_json_table**

**Comment by strongduanmu** [comment]
Hi @jiangtao69039, can you sumbit a pr to improve this problem? I think we can use getOrginialTest to improve it.
