### ISSUE TITLE
 About using dbeaver to link shardingproxy proxy problem

### ISSUE THREAD

**Issue by zhaoxiaoyi** [apache/shardingsphere#31775]
Using the postgres (old version) link shardingproxy in dbeaver can connect, but double-clicking "table" reports the following error。And can use sql to query data normally on the query page.

**Comment by linghengqian** [comment]
- First, you shouldn't expose internal data on github, you need to create a separate postgresql unit through docker or testcontainers-java to show what happens.
- You didn't specify the postgresql version, nor the shardingsphere proxy version. The `pg_catalog` schema related to the virtual data source is actually simulated at https://github.com/apache/shardingsphere/tree/5.5.0/infra/database/type/postgresql/src/main/resources/schema/postgresql/pg_catalog .
