### ISSUE TITLE
Can not get 36 connections one time, partition succeed connection(10) have released

### ISSUE THREAD

**Issue by wmfxly** [apache/shardingsphere#31821]
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy 5.5.0

### Expected behavior
I want to migrate data from the original database to the target library for table operation, 
according to the creation time create_time table, 3 tables per month.

MIGRATION tabel data success.

### Actual behavior
Caused by: java.sql.SQLException: Can not get 36 connections one time, partition succeed connection(10) have released. Please consider increasing the 'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' in properties.
More details: HikariPool-5 - Connection is not available, request timed out after 30009ms.
	at org.apache.shardingsphere.infra.exception.core.external.sql.ShardingSphereSQLException.toSQLException(ShardingSphereSQLException.java:76)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:409)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.createConnections(DriverDatabaseConnectionManager.java:393)
	at org.apache.shardingsphere.driver.jdbc.core.connection.DriverDatabaseConnectionManager.getConnections(

### Reason analyze (If you can)
'maxPoolSize' of the data sources or decreasing the 'max-connections-size-per-query' config invalidate
max-connections-size-per-query default value 1

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

-- MIGRATION SOURCE STORAGE
REGISTER MIGRATION SOURCE STORAGE UNIT yss_source_common_db (
    URL="jdbc:mysql://ip:3306/xxx_common?serverTimezone=UTC&useSSL=false",
    USER="user",
    PASSWORD="user",
    PROPERTIES("minPoolSize"="5","maxPoolSize"="50","idleTimeout"="60000")
);

-- add STORAGE UNIT
REGISTER STORAGE UNIT ds_0 (
    URL="jdbc:mysql://ip:3306/proxy_demo_ds_0?useSSL=false",
    USER="root",
    PASSWORD="mysql",
    PROPERTIES("maxPoolSize"=200,"idleTimeout"="30000","minPoolSize"=10,"maxLifetime"="1800000","connectionTimeout"="30000")
);
-- add sharding rule
CREATE SHARDING TABLE RULE app_notice_ind (
  DATANODES(ds_0.app_notice_ind_$->{202401..202412}$->{0..2}),
  TABLE_STRATEGY(TYPE="STANDARD",SHARDING_COLUMN=`create_time`,
  SHARDING_ALGORITHM(TYPE(NAME="DATEYYYYMM_THREE_MOD",
  PROPERTIES("algorithmClassName"="com.xxxxx.extend.proxy.algorithm.xxxxxxPreciseAlgorithm",
  "algorithm-expression"="app_notice_ind_$->{202401..202412}$->{0..2}")))),
  AUDIT_STRATEGY (TYPE(NAME="DML_SHARDING_CONDITIONS"),ALLOW_HINT_DISABLE=true)
);

MIGRATE TABLE xxx.app_notice_ind INTO app_notice_ind;

Any help would be greatly appreciated.Thanks .

**Comment by terrymanu** [comment]
I don't think `target library` is correct concept on ShardingSphere, please revise content first.

**Comment by terrymanu** [comment]
I don't think "library" is a concept related to ShardingSphere. Due to the high cost of understanding, please allow me to close this issue.

**Comment by RaigorJiang** [comment]
@wmfxly Please check the max connections allowed in MySQL and how many connections can be new created for migration.

```sql
show variables like'%max_connections%';
show status like 'Threads_connected';
```
