### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: can't get index from columnLabel[field_2]

### ISSUE THREAD

**Issue by zxk1111** [apache/shardingsphere#31824]
i has the same error,like select t.*  from (select s.field_1,if(s.field_2 is null,1,2) as field_2 from sub s)t  will display this error because of t.*,
if like select t.field_1,t.field_2 will success,

error msg:
java.sql.SQLFeatureNotSupportedException: can't get index from columnLabel[field_2]

related version:
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.1</version>
</dependency>
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.2.20</version>
</dependency>

_Originally posted by @zxk1111 in https://github.com/apache/shardingsphere/issues/24207#issuecomment-2185428616_

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by zxk1111** [comment]
1
