### ISSUE TITLE
it throw Exception "Must have one sharding with subquery" ,  the logic might be have problem 

### ISSUE THREAD

**Issue by wyt1128** [apache/shardingsphere#3187]
it throw exception "Must have one sharding with subquery" ,

![image](https://user-images.githubusercontent.com/22985532/66419477-c83bb300-ea36-11e9-8c3b-d1ff962e2045.png)
routingResult.getRoutingUnits().size() could be   greater than 1

### Which version of Sharding-JDBC  did you use?
4.0.0-RC3-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

**Comment by terrymanu** [comment]
It is a little complicated issue, I just assign to @tuohai666

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
