### ISSUE TITLE
[code conduct] There are a lot of indents in the g4 files that shouldn't be there

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#31892]
According to [Parser Conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/#contributor-covenant-g4-of-conduct), blank line should have no indents
https://shardingsphere.apache.org/community/en/involved/conduct/code/#contributor-covenant-g4-of-conduct

### shardingsphere-parser-sql-mysql
<img width="1062" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/6ea23dfb-5048-46c6-9ce6-7653327cd2d7">

### shardingsphere-parser-sql-hive
<img width="1058" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/b4a28fd9-174e-4040-9529-49f40211fee8">

**Comment by elysium-w** [comment]
@RaigorJiang I will finish it.

**Comment by RaigorJiang** [comment]
Assigned, thank you @elysium-w

**Comment by elysium-w** [comment]
> Assigned, thank you @elysium-w

which branch should  I submit this work to?

**Comment by RaigorJiang** [comment]
@elysium-w Please submit a PR for master, thank you!
https://shardingsphere.apache.org/community/en/involved/contribute/contributor/
