### ISSUE TITLE
自带的SnowflakeKeyGenerateAlgorithm id雪花生成器，批量多次调用 第一个一次调用永远是偶数的问题

### ISSUE THREAD

**Issue by l810102251** [apache/shardingsphere#31901]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Actual behavior
在官方的代码样例中，有个t_order 和t_order_item 表，数据写入逻辑是 先写t_order 然后 写t_order_item 表。写到数据中的order_id 都是偶数，item_id 都是基数，导致用order_id做shardingkey的分片配置，出现了数据分片一边倒的情况。

### Reason analyze (If you can)
，表的主键都是用snowflake_generator 算法生成，由于两次调用时间相隔很短，都在一个毫秒时间中。导致当前毫秒的正好调调用两次，第一次调用是偶数，第二次调用是基数，第一次都是order_id,第二次都是item_id 。所以到了分片一边倒的问题。

**Comment by RaigorJiang** [comment]
Welcome to Apache ShardingSphere community, please note only **English** is accepted here.
I will close this issue, please submit a new one if needed.
Thank you!
