### ISSUE TITLE
 ERROR o.s.j.d.DataSourceTransactionManager-Commit exception overridden by rollback exception

### ISSUE THREAD

**Issue by JsonLYH** [apache/shardingsphere#31923]
![1](https://github.com/apache/shardingsphere/assets/64977775/3f9b63bb-79a1-46ba-a3ca-2d764e6870ba)
![2](https://github.com/apache/shardingsphere/assets/64977775/8fdcdb07-6c82-441a-ba76-ad1bbeb57c0a)
![3](https://github.com/apache/shardingsphere/assets/64977775/acb55a73-2bb6-47ab-9aea-23000354cee7)

**Comment by terrymanu** [comment]
The issue contains only images, which is not conducive to search or code copying by contributors. Could you please recreate an new issue and describe it again using text and code?
