### ISSUE TITLE
[Jacoco codeCov] Scan and create aggregation Jacoco report for ShardingSphere

### ISSUE THREAD

**Issue by AkaLrz** [apache/shardingsphere#31940]
Feature Summary: 

By using Jacoco to create aggregation report about ShardingSphere. Fixed Bug caused by upgrade Junit from 4 to 5.  Created Shell script automaticly merge report without creating a new module. Ensure sustainable reporting after adding modules in the future. Created Jacoco Github Action.  Successfully configured Jacoco to adapt Junit5.

Added File:
jacoco.yml
unit-test-coverage-merge
jacoco plug-in on pom

File Structure:
<img width="448" alt="image" src="https://github.com/apache/shardingsphere/assets/98505130/6f240797-4dd7-45a1-9699-5752c554f4c6">

Note:
In code-coverage-merge.sh, if unit-test-coverage-merge module changed position, should update latest root directory for file directory and output directory.
<img width="1337" alt="image" src="https://github.com/apache/shardingsphere/assets/98505130/d98ca22e-def4-4261-8019-84f9f2fd369a">

**Comment by AkaLrz** [comment]
This pr also can solve following Issue:
Issue Name: Add code coverage in codecov #26526
Issue URL: https://github.com/apache/shardingsphere/issues/26526

**Comment by taojintianxia** [comment]
the codecov action need a upload token.
