### ISSUE TITLE
insert with cast i joind date type

### ISSUE THREAD

**Issue by yvladimirov** [apache/shardingsphere#31946]
### Which version of ShardingSphere did you use?
5.4.1-5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Jooq+ShardingSphere-JDBC +Postgresql
`insert into orders (id,cancel_expired_at, multi_order_id) values (?, cast(? as timestamp(6)), cast(? as uuid))`

worked

### Actual behavior

ERROR: syntax error at or near "astimestamp"

### Reason analyze (If you can)
ShardingSphere  have problem with parsing function **cast**  in **insert** case. Antlr join as and date type.

maybe a similar problem
https://github.com/apache/shardingsphere/pull/31744

**Comment by terrymanu** [comment]
Could you please pull to this commit and test it?

**Comment by terrymanu** [comment]
The title of this issue is not well enough, could you please update to a more understandable title by summarizing the content?
