### ISSUE TITLE
version 5.4X Sharding algorithm `HASH_MOD` initialization failed, reason is: `tb_xxx` tables sharding configuration can not use auto sharding algorithm

### ISSUE THREAD

**Issue by houqijun** [apache/shardingsphere#31964]
rules:
- !SHARDING
  tables:
    tb_alarm_data:
      actualDataNodes: ds$->{0..1}.tb_xxx
      databaseStrategy:
        standard:
          shardingColumn: station_id
          shardingAlgorithmName: database_hash_mod
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    database_hash_mod:
      type: HASH_MOD
      props:
        sharding-count: 2

**Comment by terrymanu** [comment]
The information you provided does not fully understand the issue. Please refer to the issue template to fill the necessary information, which will help us catch the problem clearly.

**Comment by FN20200222** [comment]
我也出现了这个问题
