### ISSUE TITLE
Different behaviors between proxy and mysql when using datetime

### ISSUE THREAD

**Issue by xiaoyuge** [apache/shardingsphere#32042]
## Question

I have a very strange problem. 

When my application directly connects to the MySQL database and inserts 1720418341000 into a datetime field, it correctly stores '2024-07-08 13:59:01'. 

However, when my application connects to MySQL through the ShardingSphere-Proxy and inserts 1720418341000 into a datetime field, it stores '0001-01-01 00:00:00' instead. 

What could be the reason for this, and how can I solve it?

Mysql version is 5.7.37
ShardingSphere-Proxy version is 5.3.2

**Comment by terrymanu** [comment]
Is it same with #32035?
