### ISSUE TITLE
Why does the running mode no longer support nacos since version 5.4.1?

### ISSUE THREAD

**Issue by liming0** [apache/shardingsphere#32072]
## Question
Why does the running mode no longer support nacos since version 5.4.1?
Version 5.4.1 still exists. There are still quite a lot of nacos users, and I hope they can be added back.

**Comment by terrymanu** [comment]
It is best to have one stable registry center, as there are many registry centers available, and they are not the main feature of ShardingSphere.
We do not have the time to test various combinations. 
Our focus is on the functionality of ShardingSphere itself.
