### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by liangjiajie-hub** [apache/shardingsphere#32099]
version：5.3.2
![1720947317748](https://github.com/user-attachments/assets/aa1f3b44-bb82-47bd-a91a-f9061389ed96)

"import org.apache.shardingsphere.distsql.parser.autogen"

**Comment by linghengqian** [comment]
- Feel free to check out https://github.com/apache/shardingsphere/wiki . You just need to switch to any JDK11+ version and compile Antlr4 products in advance. Similar to the following operations.
```bash
sdk install java 22.0.1-graalce
sdk use java 22.0.1-graalce

git clone git@github.com:apache/shardingsphere.git
cd ./shardingsphere/
./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true
```

**Comment by liangjiajie-hub** [comment]
Thank you very much!
