### ISSUE TITLE
can not query information_schema.COLUMNS  return empty

### ISSUE THREAD

**Issue by yinjinxiong** [apache/shardingsphere#32116]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
  execute  select * from information_schema.COLUMNS where TABLE_SCHEMA = :db_name and TABLE_NAME = :table_name   ， should return column information

"TABLE_CATALOG" -> "def"
"TABLE_SCHEMA" -> "activitys"
"TABLE_NAME" -> "activity"
"COLUMN_NAME" -> "start_time"
"ORDINAL_POSITION" -> {BigInteger@19670} "2"
"COLUMN_DEFAULT" -> null
"IS_NULLABLE" -> "NO"
"DATA_TYPE" -> "datetime"
"CHARACTER_MAXIMUM_LENGTH" -> null
"CHARACTER_OCTET_LENGTH" -> null
"NUMERIC_PRECISION" -> null
"NUMERIC_SCALE" -> null
"DATETIME_PRECISION" -> {BigInteger@19681} "0"
"CHARACTER_SET_NAME" -> null
"COLLATION_NAME" -> null
"COLUMN_TYPE" -> "datetime"
"COLUMN_KEY" -> ""
"EXTRA" -> ""
"PRIVILEGES" -> "select,insert,update,references"
"COLUMN_COMMENT" -> "开始时间 @query.between"
"GENERATION_EXPRESSION" -> ""

### Actual behavior
return empty 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

dataSources:
  novel:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8066/novel?useUnicode=true
    username: XXX
    password: XXX

shardingRule:
  tables:
    book_chapter:
      actualDataNodes: novel.book_chapter_${0..9}
      tableStrategy:
        inline:
          shardingColumn: book_id
          algorithmExpression: book_chapter_${(int)(book_id / 10) % 10}
props:
  sql.show: true

sql: select * from information_schema.COLUMNS where TABLE_SCHEMA = 'novel' and TABLE_NAME = 'book_chapter'

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
> ## Bug Report
> **For English only**, other languages will not accept.
> 
> Before report a bug, make sure you have:
> 
> * Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
> * Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).
> 
> Please pay attention on issues you submitted, because we maybe need more details. If no response anymore and we cannot reproduce it on current information, we will **close it**.
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### Which version of ShardingSphere did you use?
> 4.1.1
> 
> ### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
> ShardingSphere-JDBC
> 
> ### Expected behavior
> execute select * from information_schema.COLUMNS where TABLE_SCHEMA = :db_name and TABLE_NAME = :table_name ， should return column information
> 
> "TABLE_CATALOG" -> "def" "TABLE_SCHEMA" -> "activitys" "TABLE_NAME" -> "activity" "COLUMN_NAME" -> "start_time" "ORDINAL_POSITION" -> {BigInteger@19670} "2" "COLUMN_DEFAULT" -> null "IS_NULLABLE" -> "NO" "DATA_TYPE" -> "datetime" "CHARACTER_MAXIMUM_LENGTH" -> null "CHARACTER_OCTET_LENGTH" -> null "NUMERIC_PRECISION" -> null "NUMERIC_SCALE" -> null "DATETIME_PRECISION" -> {BigInteger@19681} "0" "CHARACTER_SET_NAME" -> null "COLLATION_NAME" -> null "COLUMN_TYPE" -> "datetime" "COLUMN_KEY" -> "" "EXTRA" -> "" "PRIVILEGES" -> "select,insert,update,references" "COLUMN_COMMENT" -> "开始时间 @query.between" "GENERATION_EXPRESSION" -> ""
> 
> ### Actual behavior
> return empty
> 
> ### Reason analyze (If you can)
> ### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
> dataSources: novel: driverClassName: com.mysql.jdbc.Driver url: jdbc:mysql://127.0.0.1:8066/novel?useUnicode=true username: XXX password: XXX
> 
> shardingRule: tables: book_chapter: actualDataNodes: novel.book_chapter_${0..9} tableStrategy: inline: shardingColumn: book_id algorithmExpression: book_chapter_${(int)(book_id / 10) % 10} props: sql.show: true
> 
> sql: select * from information_schema.COLUMNS where TABLE_SCHEMA = 'novel' and TABLE_NAME = 'book_chapter'
> 
> ### Example codes for reproduce this issue (such as a github link).

you may write issues of version 4.1.1 here :https://gitee.com/shardcn/shardingsphere_4.1.1
