### ISSUE TITLE
I can’t find 5.5.0 version jar on https://mvnrepository.com/

### ISSUE THREAD

**Issue by duyafeng** [apache/shardingsphere#32161]
I can’t find 5.5.0 version jar on https://mvnrepository.com/

**Comment by terrymanu** [comment]
https://mvnrepository.com/artifact/org.apache.shardingsphere

**Comment by duyafeng** [comment]
<img width="981" alt="image" src="https://github.com/user-attachments/assets/c31ef81a-b7f9-4851-b8b4-c20497c8ad34">
I‘m trying to download the  version 5.5.0, but on the website it only updates to  version 5.4.1.

**Comment by terrymanu** [comment]
https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc
