### ISSUE TITLE
Merge duplicated test container classes

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#32210]
There are duplicated test container classes in shardingsphere-test-e2e-agent-plugins-common and shardingsphere-test-e2e-transaction and other modules.

It should be merge into shardingsphere-test-e2e-env module.

Please search `// TODO Merge test container:` to find to be merged classes.

**Comment by DHRUV6029** [comment]
Hi, Can I work on this , Can you please assign it to me

**Comment by iamhucong** [comment]
@DHRUV6029 Hi, i’m already working on it. 😂
