### ISSUE TITLE
Can the view be decrypted and queried? After shardingproxy encrypts the table, this table has a view. Querying the view does not support decryption, right?

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#32228]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.3.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior

Views can decrypt queries

### Actual behavior

Query the view and find the ciphertext

**Comment by zhaojinchao95** [comment]
@Y-sir Hi, you can create encrypt rule for your view.

**Comment by Y-sir** [comment]
@zhaojinchao95 Hello, could you please give me some advice on how to create encryption rules?
