### ISSUE TITLE
[shardingsphere-5.1.1] When sharding table left join other non-sharding tables, merge query result throws NullPointerExpection

### ISSUE THREAD

**Issue by x782544391** [apache/shardingsphere#32237]
## Question

similar to [#14016](https://github.com/apache/shardingsphere/issues/14016)

version: 5.1.1

SQL ：SELECT  {som_column}
        FROM  table_a a
        LEFT JOIN  table_b  b  ON   {some_condition}
        LEFT JOIN  table_c   c  ON   {some_condition}
        LEFT JOIN  table_d  d  ON   {some_condition}
        LEFT JOIN  table_e  e  ON    {some_condition}
(only table_a is sharding table)

Question: 
       When query result is from more than one sharding table, shardingsphere throws the NullPointerExpection. I debug source code, found that ShardingSphereSchema doesn't contains non-sharding tables  in this SQL, so TableMetaData is null, this cause NPE.

The source code is in org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue#getOrderValuesCaseSensitiveFromTables，
line 74 cause NPE.

Looking forward to your reply. Thanks!

**Comment by terrymanu** [comment]
What is your configuration, database schema and actual SQL?

**Comment by x782544391** [comment]
ShardingSphereDataSource configuration:
`@Bean("shardingSphereDatasource")
    public DataSource shardingSphereDatasource(@Qualifier("druidDatasource") DataSource druidDatasource) {
        DynamicDataSource dynamicDataSource = (DynamicDataSource) druidDatasource;
        DruidDataSource druidDataSource = (DruidDataSource) dynamicDataSource.determineTargetDataSource();
        druidDataSource.setProxyFilters(Collections.singletonList(new ShardingSphereDruidFilter()));
        try {
            Properties props = new Properties();
            props.put(ConfigurationPropertyKey.SQL_SHOW.getKey(), false);
            props.put(ConfigurationPropertyKey.KERNEL_EXECUTOR_SIZE.getKey(), 10);
            Map<String, DataSource> result = new HashMap<>();
            result.put("test_sharding", druidDatasource);

            ShardingRuleConfiguration ruleConfiguration = new ShardingRuleConfiguration();
            Properties systemLogProps = new Properties();
            systemLogProps.setProperty("strategy", "complex");
            systemLogProps.setProperty("algorithmClassName", TableShardingAlgorithm.class.getName());
            ruleConfiguration.getShardingAlgorithms().put(TABLE_A_SHARDING_ALGORITHM_NAME, new ShardingSphereAlgorithmConfiguration("CLASS_BASED", systemLogProps));
            ShardingTableRuleConfiguration tableRuleConfiguration = new ShardingTableRuleConfiguration("table_a", DATA_SOURCE_NAME + ".table_a_" + MONTH_EXPRESSION_SUFFIX);
            tableRuleConfiguration.setTableShardingStrategy(new ComplexShardingStrategyConfiguration("CREATE_TIME_UTC, ID", SYSTEM_LOG_SHARDING_ALGORITHM_NAME));
            ruleConfiguration.getTables().add(tableRuleConfiguration);

            return ShardingSphereDataSourceFactory.createDataSource("sharding_db", result, Collections.singletonList(ruleConfiguration), props);
        } catch (Exception e) {
            logger.error("ShardingSphere datasource create error,Please check the database", e);
        }
        return druidDatasource;
    }`


actual SQL, it has two statement: 
1. SELECT {some_column}
FROM table_a_20240724 a
LEFT JOIN table_b b ON {some_condition}
LEFT JOIN table_c c ON {some_condition}
LEFT JOIN table_d d ON {some_condition}
LEFT JOIN table_e e ON {some_condition}
WHERE a.CREATE_TIME_UTC BETWEEN ? AND ? ORDER BY a.CREATE_TIME_UTC
1. SELECT {some_column}
FROM table_a_20240723 a
LEFT JOIN table_b b ON {some_condition}
LEFT JOIN table_c c ON {some_condition}
LEFT JOIN table_d d ON {some_condition}
LEFT JOIN table_e e ON {some_condition}
WHERE a.CREATE_TIME_UTC BETWEEN ? AND ? ORDER BY a.CREATE_TIME_UTC

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by x782544391** [comment]
I have format the configuration code.

**Comment by terrymanu** [comment]
What is class `DynamicDataSource`in your code?

**Comment by x782544391** [comment]
`DynamicDataSource` is a subclass of org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource. In my question,  it is actually a DruidDataSource.

I just wonder it cause NPE when query that sharding table joining non-sharding table and query-result from more than one sharding table in shardingsphere-5.1.1, but not throws Exception in sharding-jdbc-3.1.0. 

Must all tables be sharding-tables for one query SQL in 5.1.1?

**Comment by terrymanu** [comment]
Can you simplify your configuration and just for reproduce the issue?
