### ISSUE TITLE
In postgresql, use other schemaName, Login to the database using a different username, and view the tables in the specified mode.

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#32258]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy   postgresql 14.2
### Expected behavior
1、Create a new ceshi user   
`CREATE USER ceshi WITH PASSWORD '123ABCdef*';`
![image](https://github.com/user-attachments/assets/1ddbe2d0-b02f-4495-8ed2-9600e889f3fa)
2、Create a new ceshi mode
![image](https://github.com/user-attachments/assets/c292a7fd-8b01-4316-9c47-93f2741eb5f2)
And assign the ceshi mode to the ceshi user
3、In ceshi mode, create a new stu table
`CREATE TABLE "ceshi"."stu" (
  "id" int4 NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "stu_pkey" PRIMARY KEY ("id")
)
;`
![image](https://github.com/user-attachments/assets/c6c8bc7d-14aa-4eb8-8b85-aeabfaf1e195)
4、Use shardingproxy to proxy ceshi user and ceshi mode, start the proxy
![image](https://github.com/user-attachments/assets/273c721e-37fd-47f0-8d8b-a3f1313fcf79)
5、Use navicat to connect to the shardingproxy proxy
![image](https://github.com/user-attachments/assets/064907e0-6b14-473b-8e5c-d48d46f9f191)

### Actual behavior
6、View the table in ceshi mode, but cannot find it
![image](https://github.com/user-attachments/assets/e4f14487-46f0-4045-9e65-4baead428d0d)
7、At this time, check the source library. This stu table exists under the ceshi mode.
![image](https://github.com/user-attachments/assets/2ab05554-e58a-4da4-9d5e-cb4023f2bd87)

**Comment by terrymanu** [comment]
`log in` or `login`?
Please revise it.

**Comment by Y-sir** [comment]
> log in

 Hello, what do you mean by logging in? @terrymanu

**Comment by Y-sir** [comment]
Can anyone help me take a look?

**Comment by terrymanu** [comment]
What is mode?

**Comment by Y-sir** [comment]
> What is mode, Is it a database concept?

@terrymanu Modes other than public

**Comment by Y-sir** [comment]
In the postgresql database, there is public under postgres. If you don't use public, what about something else? @terrymanu

**Comment by terrymanu** [comment]
Do you mean schema?

**Comment by Y-sir** [comment]
> Do you mean schema?

@terrymanu yes

**Comment by terrymanu** [comment]
Can you revise your issue to make sure title and content are all correct?

**Comment by Y-sir** [comment]
> Can you revise your issue to make sure title and content are all correct?

ok

**Comment by strongduanmu** [comment]
This issue is duplicate with https://github.com/apache/shardingsphere/issues/17204, we will consider support PostgreSQL SEARCH PATH in future.
