### ISSUE TITLE
Is it possible that shardingsphere can automatically use a different keyword configuration based on the MySQL version?

### ISSUE THREAD

**Issue by MoonLord-LM** [apache/shardingsphere#32275]
For example, I'm using MySQL 5.7, and "system" is not a keyword, but it's validated like MYSQL 8.0 keywords?
Similar：https://github.com/apache/shardingsphere/issues/25763

Refer to the official documentation of MySQL. The keywords may be different for each minor version.
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-removed-in-current-series
![image](https://github.com/user-attachments/assets/4ec31e72-ca87-43cd-87be-2bfa7c393df1)

Why does it do keyword validation?
Maybe we do not need it?

**Comment by terrymanu** [comment]
You may use escape characters to process keyword
