### ISSUE TITLE
When setting read-write-splitting and sharding are set,read-write-splitting does not work

### ISSUE THREAD

**Issue by huhusu** [apache/shardingsphere#32319]
### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

Description:

I use JAVA API to write programs

have 4 datasource,two write ds and two read ds

read-write-splitting config like this:
write-data-source: ds0A0
read-data-source: ds1A0
write-data-source: ds0A1
read-data-source: ds1A1

sharding config like this:
ds0A0、ds0A1 sharding type is hash-mod

When setting read-write-splitting and sharding are set,read-write-splitting does not work.
If both independent configurations can work ok.

### Expected behavior
When setting read-write-splitting and sharding are set,both of them are work ok.

### Actual behavior
When setting read-write-splitting and sharding are set,read-write-splitting does not work.

**Comment by terrymanu** [comment]
Can you provide the configuration codes?

**Comment by huhusu** [comment]
The code logic is too complex, just paste the ShardingSphereDataSoureFactory.createDataSource method parameter directly.
parameter include shardingDsMap、allRules、shardingProperties
![1](https://github.com/user-attachments/assets/d8ed743d-99b8-4dbc-9176-68c44e91c495)
ShardingTableRuleConfiguration:
![2](https://github.com/user-attachments/assets/30ecf6b0-f429-4167-a18d-f0241f44f77a)
ReadwriteSplittingDatasourceRuleConfiguration:
![3](https://github.com/user-attachments/assets/d6bb4487-2904-44ef-a7b9-355f9dedc2f6)

**Comment by terrymanu** [comment]
The issue contains only images, which is not conducive to search or code copying by contributors. Could you please recreate an new issue and describe it again using text and code?
