### ISSUE TITLE
 Using version 5.5.0 of ShardingSphere. it requires snakeyaml version 2.2.However dependency through Maven, the version being used is 1.3

### ISSUE THREAD

**Issue by AzeWZ** [apache/shardingsphere#32325]
I am currently using version 5.5.0 of ShardingSphere. According to the pom.xml dependencies, it requires snakeyaml version 2.2. However, after adding the dependency through Maven, the version being used is 1.3, which is causing compatibility issues.

The snakeyaml version should be 2.2 as specified in the pom.x
![BEC185AE-637D-4164-836A-577A0239BC6B](https://github.com/user-attachments/assets/069970ea-8e7f-4f77-b9e5-0709f5b130ef)
ml of ShardingSphere 5.5.0.

**Comment by linghengqian** [comment]
- So I assume you want to raise a PR to shade the SnakeYaml package?
- SnakeYAML made a lot of API changes in the 2.0 milestone, which are obviously not compatible with SnakeYAML 1.33.

**Comment by AzeWZ** [comment]
i found it
 manually specifying version 2.2 for SnakeYAML.
 
https://github.com/apache/shardingsphere/blob/887b37285f553092f353d44053065c8fec43f1b8/docs/document/content/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/_index.cn.md?plain=1#L61
