### ISSUE TITLE
Sharding is adapted to the Dameng database and uses the OracleParse.class parser. When my query SQL contains an escape, it will report an error

### ISSUE THREAD

**Issue by wang866** [apache/shardingsphere#32357]
Sharding 5.5.0 version, compatible with Dameng database, uses Oracle Parser parser. When there is an escape in the query, it will report an error SQL statement

sql：
select * from table where name like ? escape '\';

Error message:
org.apache.shardingsphere.infra.exception.dialect.exception.syntax.sql.DialectSQLParsingException: You have an error in your SQL syntax:select * from table where name like ? escape '\' , null

How should this be resolved? Debugging shows that there was an error when parsing antlr4

**Comment by terrymanu** [comment]
No plan for now
