### ISSUE TITLE
In the newly added tables in the source database, zk does not synchronize the information.

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#32406]
In the newly added tables in the source database, zk does not synchronize the information.

mysql8.0.27    shardingproxy 

In the source database, add a table, stu1_copy1; 
![image](https://github.com/user-attachments/assets/9b59c119-ce9e-4809-a489-a99915b472c6)

Then query the table structure in zk；
![image](https://github.com/user-attachments/assets/ee99d734-877e-401c-a097-6e41db267284)

How to synchronize the information of the table added in the source database to zk

**Comment by terrymanu** [comment]
What is source database？

**Comment by Y-sir** [comment]
@terrymanu Database proxied by shardingproxy

**Comment by terrymanu** [comment]
https://shardingsphere.apache.org/document/5.5.0/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata/ may help you.

**Comment by Y-sir** [comment]
@terrymanu  Thanks
