### ISSUE TITLE
请问我用shardingsphere-jdbc-core-spring-boot-starter-5.1.2遇见一个奇怪的问题，有些mysql select 语句在mybatis 的xml传入的入参偶尔会莫名奇妙自动多出一个入参，导致比实际参数值多，导致参数越界的报错，下图这个10对应limit后面的？，5这个值是多出的，请问这个问题怎么解决

### ISSUE THREAD

**Issue by huidu0927** [apache/shardingsphere#32401]
用shardingsphere-jdbc-core-spring-boot-starter-5.1.2遇见一个奇怪的问题，有些mysql select 语句在mybatis 的xml传入的入参偶尔会莫名奇妙自动多出一个入参，导致比实际参数值多，导致参数越界的报错，下图这个10对应limit后面的？，5这个值是多出的
报错信息：
![shardingsphere-jdbc-core-spring-boot-starter-5 1 2-问题](https://github.com/user-attachments/assets/b9b386c6-b8b7-4081-95da-be61b2cf1fd1)
Cause: java.sql.SQLException: Parameter index out of bounds. 11 is not between valid values of 1 and 9

**Comment by linghengqian** [comment]
I tend to think that this is a problem with the parsing of antlr4 in the old version of shardingsphere. You need to try it with shardingsphere 5.5.0.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
