### ISSUE TITLE
shardingsphere-jdbc-core integration druid error

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/shardingsphere#32419]
## Question

An error occurred after the shardingsphere-jdbc-core integration druid was started

The error is

**nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required**

I processed it according to the instructions in the document without referring to starer

Document address: [https://www.bookstack.cn/read/shardingsphere-5.1.0-zh/4bbabb9801ce9847.md](https://www.bookstack.cn/read/shardingsphere-5.1.0-zh/4bbabb9801ce9847.md)

It still didn't work out.

### springboot version
spring-boot-2.3.12.RELEASE

#### other versions
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>1.1.10</version>
</dependency>

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
    <version>5.3.2</version>
    <exclusions>
        <exclusion>
            <artifactId>logback-classic</artifactId>
            <groupId>ch.qos.logback</groupId>
        </exclusion>
        <exclusion>
            <artifactId>HikariCP</artifactId>
            <groupId>com.zaxxer</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by linghengqian** [comment]
- You need to provide git with minimal unit tests, and the database can be created using h2database or testcontainers-java. This is not a real error log, it's just that some spring bean initialization failed, you need to provide more information.

**Comment by linghengqian** [comment]
- I also noticed that you are browsing documentation provided by third-party sites outside of apache.org. **These docs are not managed by ASF members or contributors, and they intentionally do not provide documentation in English.**
