### ISSUE TITLE
Is there any way to get whether the executed statement is insert or select in a custom algorithm?

### ISSUE THREAD

**Issue by hf185** [apache/shardingsphere#32500]
Sharding proxy: 5.2.1

CustomShardingAlgorithm implements ComplexKeysShardingAlgorithm

**Comment by terrymanu** [comment]
Is it ShardingSphere's feature?

**Comment by RaigorJiang** [comment]
The interface method of ShardingAlgorithm does not include Statement, so the Statement type cannot be determined in CustomShardingAlgorithm.

**Comment by perzpy** [comment]
> Sharding proxy: 5.2.1
> 
> CustomShardingAlgorithm implements ComplexKeysShardingAlgorithm

hi, do you find any way to get ?

**Comment by hf185** [comment]
> > Sharding proxy: 5.2.1
> > CustomShardingAlgorithm implements ComplexKeysShardingAlgorithm
> 
> @hf185 hi, do you find any way to get ?

Haven't found any good solutions

**Comment by perzpy** [comment]
@hf185 
我打算借用HintManager中的ThreadLocal来实现，插入时把其中某个值（比如setWriteRouteOnly设为true），然后在doSharding时判断这个值来判断是插入还是查询

**Comment by hf185** [comment]
> @hf185 我打算借用HintManager中的ThreadLocal来实现，插入时把其中某个值（比如setWriteRouteOnly设为true），然后在doSharding时根据这个值来判断是插入还是查询

可以交流一下

**Comment by hf185** [comment]
@perzpy 你好，请问你解决这个问题了吗？
