### ISSUE TITLE
amazon redshift not support

### ISSUE THREAD

**Issue by jojocodeX** [apache/shardingsphere#32588]
Currently Shardingsphere does not support the redshift protocol. Is there any consideration to add it in the future to meet more usage scenarios?

**Comment by linghengqian** [comment]
- Although https://github.com/aws/amazon-redshift-jdbc-driver is Apache V2 LICENSE, but it didn't seem to provide any available for developers to use Docker Image to deploy. This often means that you need to do closed-source SPI implementation and unit testing in a private project. 

- From my perspective, Amazon Redshift is just a downstream distribution of PostgreSQL, which I would say is probably not too difficult for a closed-source project.

**Comment by jojocodeX** [comment]
> * PostgreSQL

If you implement it yourself, can you use postgreSQL PostgreSQLStatementParser to adapt it? Because redshift does not provide syntax parsing, it is difficult to completely re-analyze the lexical structure.

**Comment by linghengqian** [comment]
I'm not an AWS employee, and I don't know if you're an AWS employee. This problem is really an AWS problem, and they are deliberately designed to make it difficult for external testing.

**Comment by jojocodeX** [comment]
> * I'm not an AWS employee, and I don't know if you're an AWS employee. This problem is really an AWS problem, and they are deliberately designed to make it difficult for external testing.
> * Another humorous point is that I can't even verify your claims. AWS blocks individual developer registration in China.

thank you
