### ISSUE TITLE
How to uniformly configure the database sharding strategy for all tables in the entire database

### ISSUE THREAD

**Issue by daaao** [apache/shardingsphere#32631]
Hello, my requirement is that all tables in the database (there are probably thousands of tables) need to be configured with the same sharding strategy, and this sharding strategy will not be modified, so I don't want to configure each table in the configuration file, which is very troublesome. How should I configure it?

Or is there a wildcard configuration method in logic-table, which means that all tables use the same database and table sharding strategy?

Or is there an SPI that can support expansion to achieve this requirement?

This means that there are hundreds of tables in a database, and more will be added later. I don’t want to configure the same rule for each table.

**Comment by terrymanu** [comment]
You may use DistSQL to config your rules, it can be generated by codes.
