### ISSUE TITLE
 Multi-table query left join lookup table

### ISSUE THREAD

**Issue by wangjianxin323** [apache/shardingsphere#32648]
this is my config:
dataSources:
  ds0:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/sdbilling2?useSSL=true&allowPublicKeyRetrieval=true&socketTimeout=60000&connectTimeout=60000&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: '123123FFFfff'
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    connectionTimeout: 60000
props:
  sql-show: show
rules:
  - !SHARDING
    shardingAlgorithms:
      table-5:
        type: HASH_MOD
        props:
          sharding-count: 5
      table-10:
        type: HASH_MOD
        props:
          sharding-count: 10
      table-20:
        type: HASH_MOD
        props:
          sharding-count: 20
    defaultTableStrategy:
      none:
    autoTables:
      iotcard_proxy_card:
        actualDataSources: ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: user_id
      iotcard_user_rate:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: user_id
      iotcard_user_order:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: user_id
      iotcard_customer_consume:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: member_id
      iotcard_card_balance_log:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: card_id
      iotcard_flow_order_log:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: order_id
      iotcard_fund_change:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: agent_id
      iotcard_card_relation_user:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-10
            shardingColumn: present_user_id
      iotcard_card_flow:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-20
            shardingColumn: card_id
      iotcard_day_flow:
        actualDataSources : ds0
        shardingStrategy:
          standard:
            shardingAlgorithmName: table-20
            shardingColumn: card_id

and this is my sql:
SELECT COUNT(*) AS total FROM iotcard_user_rate a JOIN iotcard_package b ON a.package_id = b.id JOIN iotcard_package_group c ON b.pack_group_id = c.id WHERE 1 = 1 AND a.user_id = ? AND c.id = ? AND a.up_user_id = ?

Among them iotcard_user_rate I set the sharding，iotcard_package is a single table.

the error is
 Cause: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'iotcard_package' does not exist.
But this table exists in my database.

Can you help me find out what's causing it?
My version is 5.5.0

**Comment by terrymanu** [comment]
Is `iotcard_package`  a single table?
