### ISSUE TITLE
shardingsphere-proxy how to update metadata?

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#32660]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

I read the code and found that when the proxy updates the metadata, it first creates a new version of the configuration, puts it into etcd, and then deletes the original configuration. I understand this logic. However, I would like to know how ShardingSphere updates the in-memory configuration when it watches for changes in the etcd configuration?

I found some event like this,
```
private Optional<GovernanceEvent> createStorageNodeChangedEvent(final String databaseName, final DataChangedEvent event) {
        Optional<String> dataSourceNodeName = DataSourceMetaDataNode.getDataSourceNameByDataSourceNodeActiveVersionNode(event.getKey());
        if (dataSourceNodeName.isPresent()) {
            if (Type.ADDED == event.getType()) {
                return Optional.of(new RegisterStorageNodeEvent(databaseName, dataSourceNodeName.get(), event.getKey(), event.getValue()));
            }
            if (Type.UPDATED == event.getType()) {
                return Optional.of(new AlterStorageNodeEvent(databaseName, dataSourceNodeName.get(), event.getKey(), event.getValue()));
            }
        }
        dataSourceNodeName = DataSourceMetaDataNode.getDataSourceNameByDataSourceNodeNode(event.getKey());
        return dataSourceNodeName.map(optional -> new UnregisterStorageNodeEvent(databaseName, optional));
    }
```

can you tell me shardingsphere-proxy watch how to change in-memory metadata? or query metadata when executor sql that ``` show databases; ```

**Comment by terrymanu** [comment]
Please read document with DistSQL part

**Comment by dobet** [comment]
> Please read document with DistSQL part

 I read document with DistSQL part, but I only found how to change config in config-center. but not found how to refresh the shardingsphere-proxy in-memory config, like metadataContext or ProxyContext

**Comment by terrymanu** [comment]
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata/

**Comment by dobet** [comment]
> https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/refresh-table-metadata/

tks，I found the watch use eventbus.
