### ISSUE TITLE
How to encrypt the sensitive properties in sharding.yml configuration

### ISSUE THREAD

**Issue by xuanwubing** [apache/shardingsphere#32679]
I don't find any information about encryption sharding configuration property。For example，the database password is sensitive，we can't config plaintext password int it. 
So, is there any way to work out this issue?
![微信图片_20240826164103](https://github.com/user-attachments/assets/acc78f38-e472-4141-8e03-49b8898de142)

**Comment by terrymanu** [comment]
The issue contains only images, which is not conducive to search or code copying by contributors. Could you please recreate an new issue and describe it again using text and code?

**Comment by xuanwubing** [comment]
The image has been removed.

My question is，how to encrypt the  property value  of  ShardingSphere-JDBC's yml configuration，such as database‘s password?
