### ISSUE TITLE
`shardingsphere-agent` should have a more convenient distribution method

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#32777]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
- No.
### Describe the feature you would like.
- Why is the `org.apache.shardingsphere:shardingsphere-agent:5.5.0` JAR not published to Maven Central? I looked at https://repo1.maven.org/maven2/org/apache/shardingsphere/shardingsphere-agent/5.5.0/ and found that there was only the definition file for the POM.
```bash
sdk install java 22.0.2-graalce
sdk install maven 3.9.9
mvn clean dependency:get -Dartifact=org.apache.shardingsphere:shardingsphere-agent:5.5.0
```
- I have the impression that this is not a normal limitation of the ASF. It is actually quite cumbersome to manually compile `org.apache.shardingsphere:shardingsphere-agent:5.5.0` as documented at https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/observability/ .
- In case I missed any issues, we actually also have JARs that publish binaries at https://apache.jfrog.io/ui/packages .
- Likewise, there is no restriction on publishing a Docker Image containing the shardingsphere agent to Docker Hub, like https://hub.docker.com/r/apache/skywalking-java-agent . Ideally, we should be able to download files directly from a Docker Image and insert similar statements into the downstream `Dockerfile`.
```dockerfile
COPY --from=apache/shardingsphere-agent:5.5.0 /apache-shardingsphere-5.5.0-shardingsphere-agent-bin ./apache-shardingsphere-agent/
```

**Comment by jiangML** [comment]
@linghengqian Hi, 
I think this is unnecessary, because shardingsphere-agent and shardingsphere-proxy are strongly related. And the shardingsphere-proxy artifact already contains the shardingsphere-agent.

Can download it from the official website address https://shardingsphere.apache.org/document/current/en/downloads/

**Comment by linghengqian** [comment]
> @linghengqian Hi, I think this is unnecessary, because `shardingsphere-agent` and `shardingsphere-proxy`are strongly related. And the `shardingsphere-proxy` artifact already contains the `shardingsphere-agent`.
> 
> Can download it from the official website address https://shardingsphere.apache.org/document/current/en/downloads/

- The problem is that https://shardingsphere.apache.org/document/current/en/downloads/ only provides the latest version. I think we should provide nightly builds of `ShardingSphere Agent` at https://github.com/orgs/apache/packages?repo_name=shardingsphere to provide for `ShardingSphere JDBC` testing, just like `ShardingSphere Proxy`. This can avoid checking in a lot of JAR binaries to git in recurring issues like https://github.com/apache/shardingsphere/issues/32793 and https://github.com/linghengqian/shardingsphere-agent-master-test .
- A possible `Dockerfile` might look like,
```dockerfile
FROM alpine AS prepare
# `APP_NAME` will be dynamically set to `apache-shardingsphere-5.5.1-SNAPSHOT-shardingsphere-agent-bin` from `distribution/agent/pom.xml`
ARG APP_NAME
ADD target/${APP_NAME}.tar.gz /opt
RUN mv /opt/${APP_NAME} /opt/shardingsphere-agent

FROM eclipse-temurin:22-jdk
MAINTAINER ShardingSphere "dev@shardingsphere.apache.org"
ENV LOCAL_PATH /opt/shardingsphere-agent
COPY --from=prepare /opt/shardingsphere-agent /opt/shardingsphere-agent
```

**Comment by jiangML** [comment]
> > @linghengqian Hi, I think this is unnecessary, because `shardingsphere-agent` and `shardingsphere-proxy`are strongly related. And the `shardingsphere-proxy` artifact already contains the `shardingsphere-agent`.
> > Can download it from the official website address https://shardingsphere.apache.org/document/current/en/downloads/
> 
> * The problem is that https://shardingsphere.apache.org/document/current/en/downloads/ only provides the latest version. I think we should provide nightly builds of `ShardingSphere Agent` at https://github.com/orgs/apache/packages?repo_name=shardingsphere to provide for `ShardingSphere JDBC` testing, just like `ShardingSphere Proxy`. This can avoid checking in a lot of JAR binaries to git in recurring issues like [Using the OpenTelemerty plugin with Agent will throw some undocumented exceptions #32793](https://github.com/apache/shardingsphere/issues/32793) and https://github.com/linghengqian/shardingsphere-agent-master-test .
> * A possible `Dockerfile` might look like,
> 
> ```dockerfile
> FROM alpine AS prepare
> # `APP_NAME` will be dynamically set to `apache-shardingsphere-5.5.1-SNAPSHOT-shardingsphere-agent-bin` from `distribution/agent/pom.xml`
> ARG APP_NAME
> ADD target/${APP_NAME}.tar.gz /opt
> RUN mv /opt/${APP_NAME} /opt/shardingsphere-agent
> 
> FROM eclipse-temurin:22-jdk
> MAINTAINER ShardingSphere "dev@shardingsphere.apache.org"
> ENV LOCAL_PATH /opt/shardingsphere-agent
> COPY --from=prepare /opt/shardingsphere-agent /opt/shardingsphere-agent
> ```

Can you try to implement it?

**Comment by linghengqian** [comment]
> Can you try to implement it?

- I will submit a PR in the near future to show a prototype Docker Image.

**Comment by linghengqian** [comment]
- @jiangML  I updated #32793 to use the Dockerfile, but the error persists.🫠
- I opened #32945 to support local build of Docker Images. But this is still a bit complicated, maybe we need to create a buildpacks to avoid understanding the Dockerfile?
