### ISSUE TITLE
Suggest adding an 'else if' to handle NoSuchTableException in PostgreSQLDialectExceptionMapper.

### ISSUE THREAD

**Issue by whoareyouandwhoami** [apache/shardingsphere#32795]
When PostgreSQLDialectExceptionMapper implements SQLDialectExceptionMapper override convert method,NoSuchTableException not processed,when the NoSuchTableException exception occurs, the cause of the exception cannot be determined through logs,suggest adding an 'else if' to handle NoSuchTableException.

**Comment by terrymanu** [comment]
Can you submit pull request for the idea?

**Comment by Yash-cor** [comment]
> Can you submit pull request for the idea?

Hello @terrymanu I have created a PR regarding this Issue
https://github.com/apache/shardingsphere/pull/33885

**Comment by Yash-cor** [comment]
> Can you submit pull request for the idea?

Hello I have submitted a PR regarding this could  you suggest the changes.
https://github.com/apache/shardingsphere/pull/33885
