### ISSUE TITLE
DATA_NODE_SUFFIX_PATTERN's changes from 5.21 to 5.4.1 

### ISSUE THREAD

**Issue by LeavesGirl** [apache/shardingsphere#32792]
## Bug Report

TableRule's prop  DATA_NODE_SUFFIX_PATTERN changed from 5.2.1【 (\d+[\-_]){0,}(\d+$) 】to 5.4.1 【\\d+$】,
our table used  name like【 t_order_2023_01,t_order_2024_01，t_order_item_2023_01,t_order_item_2024_01】，we used time to split ,when we changed the sharding-jdbc version to 5.4.1，the bindingtables  validator maked error,it parse the prefix with 't_order_2023_',I saw the issues about DATA_NODE_SUFFIX_PATTERN's changes, why delete the prop actualTablePrefix, if it still existed, I could point it ,but now ,this prop with private final modifiers，I cant change it, 

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues/29316).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
suport table names like t_order_2023_01,t_order_2024_01,t_order_item_2023_01,t_order_item_2024_01
### Actual behavior
when bindings t_order_2023_01,t_order_2024_01,t_order_item_2023_01,t_order_item_2024_01

Caused by: org.apache.shardingsphere.sharding.exception.metadata.InvalidBindingTablesException: Invalid binding table configuration in ShardingRuleConfiguration.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment]
What is TableRule?

**Comment by LeavesGirl** [comment]
> What is TableRule?

org.apache.shardingsphere.sharding.rule.TableRule#DATA_NODE_SUFFIX_PATTERN

**Comment by terrymanu** [comment]
This class is changed in the lasted version, can you try the new version?
