### ISSUE TITLE
using database encryption and decryption to fill in Oracle pagination SQL fields resulted in invalid 'ROWNUM' identifier

### ISSUE THREAD

**Issue by aillamsun** [apache/shardingsphere#32800]
## use version

```java
<dependency>
  <groupId>org.apache.shardingsphere</groupId>
  <artifactId>shardingsphere-jdbc-core</artifactId>
  <version>5.2.1</version>
</dependency>

<dependency>
    <groupId>com.oracle.database.jdbc</groupId>
    <artifactId>ojdbc8</artifactId>
    <version>12.2.0.1</version>
</dependency>
```

##  configuration
```JAVA
TB_VEHICLE_AUTH_REQUEST_LOGS: 
  columns:
    VIN:
      plainColumn: VIN
      cipherColumn: VIN_CIPHER
      assistedQueryColumn: VIN_QUERY_CIPHER 
      assistedQueryEncryptorName: assisted_query_encryptor 
      encryptorName: kms_encryptor
    PHONE: 
      plainColumn: PHONE
      cipherColumn: PHONE_CIPHER
      assistedQueryColumn: PHONE_QUERY_CIPHER 
      assistedQueryEncryptorName: assisted_query_encryptor 
      encryptorName: kms_encryptor
    VEHICLE_PLATE_NO: 
      plainColumn: VEHICLE_PLATE_NO
      cipherColumn: VEHICLE_PLATE_NO_CIPHER
      assistedQueryColumn: VEHICLE_PLATE_NO_QUERY_CIPHER 
      assistedQueryEncryptorName: assisted_query_encryptor 
      encryptorName: kms_encryptor
```

#### 1.Logic SQL
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/988c4462-06a2-433e-ba78-8e7b7a9f6d3a">

```SQL
SELECT *
FROM 
    (
    SELECT TMP.*,
         ROWNUM ROW_ID
    FROM 
        (SELECT ID,
        TYPE,
        USER_ID,
        PHONE,
        VEHICLE_PLATE_NO,
        VIN,
        CHANGE_LOG,
        CREATE_TIME
        FROM TB_VEHICLE_AUTH_REQUEST_LOGS
        ORDER BY  CREATE_TIME DESC ) TMP
        WHERE ROWNUM <=?)
    WHERE ROW_ID > ?
```

#### 2.Actual SQL
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/3432193f-170f-4767-81d6-c7d5aa005684">

```SQL

SELECT "ID",
         "TYPE",
         "USER_ID",
         "PHONE_CIPHER" AS "PHONE",
         "VEHICLE_PLATE_NO_CIPHER" AS "VEHICLE_PLATE_NO",
         "VIN_CIPHER" AS "VIN",
         "CHANGE_LOG",
         "CREATE_TIME",
         "ROWNUM" AS "ROW_ID"
FROM 
    (SELECT "ID",
         "TYPE",
         "USER_ID",
         "PHONE_CIPHER",
         "PHONE_QUERY_CIPHER",
         "PHONE",
         "VEHICLE_PLATE_NO_CIPHER",
         "VEHICLE_PLATE_NO_QUERY_CIPHER",
         "VEHICLE_PLATE_NO",
         "VIN_CIPHER",
         "VIN_QUERY_CIPHER",
         "VIN",
         "CHANGE_LOG",
         "CREATE_TIME",
         ROWNUM ROW_ID
    FROM 
        (SELECT ID,
        TYPE,
        USER_ID,
        PHONE_CIPHER,
         PHONE_QUERY_CIPHER,
         PHONE,
        VEHICLE_PLATE_NO_CIPHER,
         VEHICLE_PLATE_NO_QUERY_CIPHER,
         VEHICLE_PLATE_NO,
        VIN_CIPHER,
         VIN_QUERY_CIPHER,
         VIN,
        CHANGE_LOG,
        CREATE_TIME
        FROM TB_VEHICLE_AUTH_REQUEST_LOGS
        ORDER BY  CREATE_TIME DESC ) TMP
        WHERE ROWNUM <=?)
    WHERE ROW_ID > ?

```

##  result
<img width="1164" alt="image" src="https://github.com/user-attachments/assets/ccd2c6ac-7a80-4f5d-94e0-a307266b4be6">

as the boss encountered this problem?

**Comment by terrymanu** [comment]
Can you try to the lasted version?

**Comment by comecny** [comment]
It seems that the Oracle 5.21 version does not support ROWNUM parsing, but the latest version does

**Comment by aillamsun** [comment]
> Can you try to the lasted version?

use 5.4.1 error occurred

`java

SQL: SELECT * FROM ( SELECT TMP.*, ROWNUM ROW_ID FROM ( SELECT  ID,TYPE,USER_ID,PHONE,VEHICLE_PLATE_NO,VIN,CHANGE_LOG,CREATE_TIME  FROM TB_VEHICLE_AUTH_REQUEST_LOGS           ORDER BY CREATE_TIME DESC ) TMP WHERE ROWNUM <=?) WHERE ROW_ID > ?

### Cause: java.sql.SQLException: Unsupported SQL operation: Can not support encrypt shorthand expand with subquery statement.
`

**Comment by aillamsun** [comment]
> It seems that the Oracle 5.21 version does not support ROWNUM parsing, but the latest version does

I use 5.4.1 can't do it.

**Comment by aillamsun** [comment]
5.4.1 does it not support storing plaintext fields ? I need a data transition phase for my transformation. 

5.2.1  support plaintext

**Comment by terrymanu** [comment]
Could you follow the exception instruction: Do not use encrypt shorthand expand with subquery statement?

**Comment by thicv** [comment]
> 5.4.1 does it not support storing plaintext fields ? I need a data transition phase for my transformation.
> 
> 5.2.1 support plaintext

In the new version, data encryption function became pretty robust. plaintext is not necessary any more.

**Comment by aillamsun** [comment]
> > 5.4.1 does it not support storing plaintext fields ? I need a data transition phase for my transformation.
> > 5.2.1 support plaintext
> 
> In the new version, data encryption function became pretty robust. plaintext is not necessary any more.

the aggregation service is still synchronizing your old paragraph plaintext It's not easy to be compatible

**Comment by aillamsun** [comment]
> Could you follow the exception instruction: Do not use encrypt shorthand expand with subquery statement?

thx. this error has been resolved

**Comment by Y-sir** [comment]
> > Could you follow the exception instruction: Do not use encrypt shorthand expand with subquery statement?
> 
> thx. this error has been resolved

Hello, I have also encountered this problem now. How can I solve it
