### ISSUE TITLE
use navicat16 connect to shardingsphere proxy5.5, it shows "ERROR: Table or view 'pg tablespace' does not exist."

### ISSUE THREAD

**Issue by pastoralagriculture** [apache/shardingsphere#32815]
I try to use navicat16 to connect to shardingsphere proxy5.5, it shows "ERROR: Table or view 'pg tablespace' does not exist." 
database-sharding.yaml:
```databaseName: sharding_db

dataSources:
 ds_0:
   url: jdbc:postgresql://127.0.0.1:5432/postgres
   username: postgres
   password: postgres
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
rules:
- !SINGLE
 tables:
   - "ds_0.public.base_building"
- !SHARDING
 tables:
   base_household_population:
     actualDataNodes: ds_0.base_household_population_${1..14}

**Comment by zzyReal666** [comment]
Please provide more detailed information.

**Comment by puppysdevotion** [comment]
i counter the same problem , have you found out how to solve it?please teach me,thx in advance.

**Comment by zzyReal666** [comment]
Try Dbever, it has better connectivity support

**Comment by puppysdevotion** [comment]
> Try Dbever, it has better connectivity support

Many thanks for your advice, but it still cant work .error occurs:"ERROR: Unknown column 'db.oid' in 'field list'."in DBeaver.

**Comment by zzyReal666** [comment]
I have encountered similar problems, but it does not affect the execution of SQL, if you are using the proxy mode, you can try the `load single table *.*`;

> > Try Dbever, it has better connectivity support
> 
> Many thanks for your advice, but it still cant work .error occurs:"ERROR: Unknown column 'db.oid' in 'field list'."in DBeaver.
