### ISSUE TITLE
sql function cipherColumn not performed

### ISSUE THREAD

**Issue by yanwencheng** [apache/shardingsphere#32835]
shardingsphere-jdbc-core: 5.5.0
mysql：8.0.24

When I set cipherColumn as name,the select statement contains CONCAT_WS。The decryption method is not performed

the same issue is CASE statement within an SQL SELECT query to conditionally return different encrypted fields such as user_name or phone and aliasing the result, it's possible that the encryption/decryption does not work as expected.

**Comment by terrymanu** [comment]
Can you provide the SQL for example?

**Comment by yanwencheng** [comment]
> Can you provide the SQL for example?

1.the encrypt filed is phone ,user_name
concat_ws   sql  like  
```
SELECT
	CONCAT_WS( '-', user_name, phone ) 
FROM
	t_sys_user
```
case sql like
```
SELECT
CASE
		
	WHEN
		user_name THEN
			user_name ELSE phone 
			END AS result 
FROM
	t_sys_user
```

**Comment by terrymanu** [comment]
What is concat_ws

**Comment by terrymanu** [comment]
Can not support encrypt column in function expression.

**Comment by taojintianxia** [comment]
The commercial version can support these complex encrypted SQL queries through UDF, whereas the open-source version does not have this capability and therefore cannot support it.

You could have a try : https://www.sphere-ex.cn/

**Comment by taojintianxia** [comment]
@yanwencheng 

The encryption feature in ShardingSphere currently only supports simple column encryption and decryption, and does not support functions, expressions, or other complex SQL encryption or decryption. The SphereEx commercial edition has a database UDF (User-Defined Function) feature that can adapt to more complex SQL encryption and decryption based on UDFs.

Recommand you have a try https://www.sphere-ex.cn/

**Comment by thicv** [comment]
@yanwencheng The encryption feature in ShardingSphere currently only supports simple column encryption and decryption, and does not support functions, expressions, or other complex SQL encryption or decryption. The SphereEx commercial edition has a database UDF (User-Defined Function) feature that can adapt to more complex SQL encryption and decryption based on UDFs. Recommand your have a try : https://www.sphere-ex.cn/
