### ISSUE TITLE
encrypt error when sql has CONCAT_WS

### ISSUE THREAD

**Issue by yanwencheng** [apache/shardingsphere#32830]
shardingsphere-jdbc-core: 5.3.2
mysql：8.0.24

When I set cipherColumn as name,the select statement contains CONCAT_WS。The decryption method is not performed

**Comment by yanwencheng** [comment]
> Hi @yanwencheng, can you try the latest 5.5.0?

Doesn't look like it's in maven repository
![image](https://github.com/user-attachments/assets/884d4ef2-75d2-45b6-aee5-e6e3eb2f87c2)

**Comment by strongduanmu** [comment]
You can search `shardingsphere-jdnc`.

**Comment by yanwencheng** [comment]
> You can search .`shardingsphere-jdnc`

org.apache.shardingsphere:shardingsphere-test-util:jar:5.5.0 was not found

**Comment by yanwencheng** [comment]
> You can search `shardingsphere-jdnc`.

i have try the latest 5.5.0 ，the same issue

**Comment by yanwencheng** [comment]
> You can search `shardingsphere-jdnc

When using a CASE statement within an SQL SELECT query to conditionally return different encrypted fields such as user_name or phone and aliasing the result, it's possible that the encryption/decryption does not work as expected. This typically happens because encryption/decryption functions or procedures might be designed to work directly on the data fields before they are evaluated within the CASE expression.

```
        SELECT
       *,
        CASE
        WHEN user_name IS NOT NULL THEN user_name 
        WHEN phone IS NOT NULL THEN phone 
        END AS companyName
        FROM
        xxxx
```

**Comment by aillamsun** [comment]
> You can search `shardingsphere-jdnc`.

unable to find 5.5.0. do you have an address?

**Comment by strongduanmu** [comment]
> creator

Can you show your configuration? It looks like your plaintext column and ciphertext column are incorrectly configured with the same name.

**Comment by strongduanmu** [comment]
> > You can search `shardingsphere-jdnc`.
> 
> unable to find 5.5.0. do you have an address?

You can get latest version here——https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc/5.5.0

**Comment by strongduanmu** [comment]
> shardingsphere-jdbc-core: 5.3.2 mysql：8.0.24
> 
> When I set cipherColumn as name,the select statement contains CONCAT_WS。The decryption method is not performed

Currently ShardingSphere does not support the use of encrypted columns in functions, inluding `CONCAT_WS`. Let's see if there are community volunteers to improve this feature.

**Comment by strongduanmu** [comment]
Duplicate with #32835
