### ISSUE TITLE
The URLArgumentLine's PLACEHOLDER_PATTERN doesn't match whitespace after it

### ISSUE THREAD

**Issue by xuanwubing** [apache/shardingsphere#32831]
usually, we would comment  our xxx.yml config's key；
but，if we use placeholder with comment, then the placeholder value must has one whitespace after it at least.

This  " _**private static final Pattern PLACEHOLDER_PATTERN = Pattern.compile("\\$\\$\\{(.+::.*)}$");**_"  regular expression doesn't support any whitespace after placeholder.

**Comment by xuanwubing** [comment]
I cant agree this is intentional. cause the regular expression[ \$\$\{(.+::.*)\}$] is not right.
placeholder's regular expression should only match the placeholder itself, no matter what before or alter it（ps：the regular expression can match placeholder with head infos）.

Anyway,  as you said I can implement another for handle this problem！！！Thanks！！！

**Comment by xuanwubing** [comment]
I cant agree this is intentional. cause the regular expression[ \$\$\{(.+::.*)\}$] is not right.
placeholder's regular expression should only match the placeholder itself, no matter what before or alter it（ps：the regular expression can match placeholder with head infos）.

Anyway,  as you said I can implement another for handle this problem！！！Thanks！！！

**Comment by linghengqian** [comment]
Since I don't see any PR, I'll say I don't know what regular expressions you're referring to should look like. 

By the way, there have been changes to the regular expression in this part of the shardingsphere master branch.

**Comment by linghengqian** [comment]
The issue is closed due to no response.
