### ISSUE TITLE
Support for using AES in JCA to encrypt and decrypt YAML values ​​in JDBC Driver

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#32872]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- See #32695 .

### Describe the feature you would like.
- Support for using AES in JCA to encrypt and decrypt YAML values ​​in ShardingSphere JDBC Driver. This is certainly less secure, but sounds simple enough for downstream users to understand how to create custom implementations.
- Discuss potential solutions,
    - In contrast, neither `alibaba/druid` nor `dromara/hutool` provides English documentation, which may affect the translation of English documentation on the shardingsphere side, so I will not deal with it in the current issue. 
    - `jasypt/jasypt` has English documentation, but this project has not been maintained for more than 1 year. We should avoid using libraries like `apache/hive` that have not been updated for 17 years, such as `jpam`. 
    - Most of Spring Security Crypto's abstractions are designed for password encoding, not encryption and decryption. See `org.springframework.security.crypto.encrypt.BytesEncryptor`. It actually uses `org.bouncycastle:bcpkix-jdk15on`.
- JCA is more in line with my thinking. The API is not finalized yet. This requires additional exploration.

**Comment by linghengqian** [comment]
- I am working on the current issue.

**Comment by lazyboyl** [comment]
You can use the Nacos Configuration Center, which can help you implement encryption for configuration

**Comment by linghengqian** [comment]
> You can use the Nacos Configuration Center, which can help you implement encryption for configuration

- I actually don't want to introduce a discussion on support for non-local environment encryption and decryption in the current issue, maybe that needs another issue to directly introduce support for apache opendal. Because this kind of application involves integration testing using testcontainers-java.

- Also see https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/ .
