### ISSUE TITLE
shardingsphere集成达梦，使用分页插件 PageHelper.startPage(1,2);报错

### ISSUE THREAD

**Issue by wwding** [apache/shardingsphere#32946]
![image](https://github.com/user-attachments/assets/c98dfa82-df8c-496b-a219-477bdb02b0b1)

SELECT * FROM (  SELECT TMP_PAGE.*, ROWNUM PAGEHELPER_ROW_ID FROM ( 
SELECT  attendance_id,worker_Id,param,project_id,attendance_date,operation_type,update_Time AS createTime,update_Time  FROM tf_b_attendance_mirror      WHERE  (project_id = ?)
 ) TMP_PAGE) WHERE PAGEHELPER_ROW_ID <= ? AND PAGEHELPER_ROW_ID > ?

		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
			<version>5.2.1</version>
		</dependency>

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.sql.parser.exception.SQLParsingException

org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.sql.parser.exception.SQLParsingException

**Comment by linghengqian** [comment]
- You should try shardingsphere 5.5.0.
- You need to provide git with minimal reproducible unit tests, where your database should be created by testcontainers-java.
- By the way, dm8 never provided docker image or testcontainer module for developers, and I think it is impossible to solve this problem in a public environment.

**Comment by wwding** [comment]
shardingsphere 5.5.0. 和 <dependency>

<groupId>org.apache.shardingsphere</groupId>
<artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
<version>5.2.1</version>
</dependency>不兼容




| |
丁稳稳
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Ling ***@***.***> |
| 发送日期 | 2024年9月21日 12:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [apache/shardingsphere] shardingsphere集成达梦，使用分页插件 PageHelper.startPage(1,2);报错 (Issue #32946) |
You should try shardingsphere 5.5.0.
You need to provide git with minimal reproducible unit tests, where your database should be created by testcontainers-java.
By the way, dm8 never provided docker image or testcontainer module for developers, and I think it is impossible to solve this problem in a public environment.

**Comment by linghengqian** [comment]
- You no longer need ShardingSphere Spring Boot Starter, it has been removed due to incompatibility with Spring Boot 3.
- By the way, you exposed your private information when you replied via email.

**Comment by wwding** [comment]
好的，我尝试一下，感谢



| |
dingwenwen

|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Ling ***@***.***> |
| 发送日期 | 2024年9月21日 12:57 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [apache/shardingsphere] shardingsphere集成达梦，使用分页插件 PageHelper.startPage(1,2);报错 (Issue #32946) |
You no longer need ShardingSphere Spring Boot Starter, it has been removed due to incompatibility with Spring Boot 3.
By the way, you exposed your private information when you replied via email.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by fnwind** [comment]
Although this issue has already been closed, I’d like to leave my solution here for reference in case someone else encounters the same problem.

I am using `sharding-jdbc-spring-boot-starter:4.1.1`, `mybatis-plus-boot-starter:3.5.3`, and `DmJdbcDriver18:8.1.2.192`。

```xml
<dependency>
	<groupId>org.apache.shardingsphere</groupId>
	<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>4.1.1</version>
</dependency>
<dependency>
	<groupId>com.baomidou</groupId>
	<artifactId>mybatis-plus-boot-starter</artifactId>
	<version>3.5.3</version>
</dependency>
<dependency>
	<groupId>com.dameng</groupId>
	<artifactId>DmJdbcDriver18</artifactId>
	<version>8.1.2.192</version>
</dependency>
```

After reviewing other issues and the official extension implementations under [jdbc-dialect](https://github.com/apache/shardingsphere/tree/master/jdbc-dialect)
, I am **convinced that DM8 is not supported**.

In my experiments, I found that when `jdbc:dm://` cannot be matched, ShardingSphere falls back to parsing with the MySQL dialect. MySQL obviously cannot parse DM8’s pagination syntax, **but DM8 actually works fine with MySQL-style pagination syntax**.

So I added a custom configuration property `xxx.mybatis.page-interceptor-db-type=mysql` to force MyBatis-Plus’s `PageInterceptor` to generate pagination SQL using the MySQL dialect:

```java
@Data
@ConfigurationProperties(prefix = "xxx.mybatis")
public class MybatisProperties {
    private DbType pageInterceptorDbType;
}
```

```java
@Bean
public MybatisPlusInterceptor mybatisPlusInterceptor(MybatisProperties mybatisProperties) {
	MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
    // ...
	DbType customDbType = mybatisProperties.getPageInterceptorDbType();
	if (null != customDbType) {
		interceptor.addInnerInterceptor(new PaginationInnerInterceptor(customDbType));
	} else {
		interceptor.addInnerInterceptor(new PaginationInnerInterceptor());
	}

	return interceptor;
}
```

```yaml
spring:
  shardingsphere:
    datasource:
      names: dm8
      dm8:
        type: com.alibaba.druid.pool.DruidDataSource
        username: MY_APP
        password: PASSWORD
        driverClassName: dm.jdbc.driver.DmDriver
        url: jdbc:dm://localhost:5236
xxx:
  mybatis:
    page-interceptor-db-type: mysql
```

At least in my project, this setup works.

**Comment by linghengqian** [comment]
> At least in my project, this setup works.

- If Dameng refuses to provide a Docker image usable in unit tests, there's little that can be done about ShardingSphere's master branch. This is completely different from the situation with MS SQL Server, where Microsoft employees have addressed the availability of Docker images for MS SQL Server in open source projects. See https://github.com/testcontainers/testcontainers-java/issues/2496#issuecomment-610402944 .
- It is very strange that there is no reproducible unit test for the master branch of shardingsphere.
