### ISSUE TITLE
How to migrate sharding table for new sharding rule 

### ISSUE THREAD

**Issue by AaronFeng2014** [apache/shardingsphere#32941]
Shardingsphere proxy Data Migration 
version：5.5.0
original  single database multiple table： order_00, order_01,order_02
new table(multiple database multiple table): db1.order_00,db1.order_01,db1.order_02, db2order_00,db2.order_01,db2.order_02

I want to migrate this old data to new table  as above，but i dont konw how to do ,
because the official example is not sharding table

**Comment by terrymanu** [comment]
Have you read the user manual?

**Comment by AaronFeng2014** [comment]
> Have you read the user manual?

I cannot find  something usefull for this case（single database multiple table migrate into  multiple database multiple table） in user manual，，，
user manual show case olny for single database single table

can you help me?

**Comment by terrymanu** [comment]
Could you demonstrate which document you have read and explain why it cannot assist you?
