### ISSUE TITLE
Shadringsphere 5.5.0 Encryption of Existing Business Data

### ISSUE THREAD

**Issue by lchpersonal** [apache/shardingsphere#32980]
## Question

I am using ShardingSphere to encrypt the fields of existing business data. Some old MySQL table fields are in plaintext, and I want to add a new column for storing the ciphertext. According to the official documentation of version 5.5.0, I could not find instructions on how to configure it so that while writing to the plaintext field, the ciphertext can also be written into the newly added column. The official documentation only mentions the following configurations:
cipher, assistedQuery, likeQuery. These only ensure that new business can directly adopt encrypted storage methods for data. What should I do for existing business?

**Comment by thicv** [comment]
> ## Question
> I am using ShardingSphere to encrypt the fields of existing business data. Some old MySQL table fields are in plaintext, and I want to add a new column for storing the ciphertext. According to the official documentation of version 5.5.0, I could not find instructions on how to configure it so that while writing to the plaintext field, the ciphertext can also be written into the newly added column. The official documentation only mentions the following configurations: cipher, assistedQuery, likeQuery. These only ensure that new business can directly adopt encrypted storage methods for data. What should I do for existing business?

ShardingSphere only provides encryption functions. Regarding how to smoothly luanch old systems online, SphereEx's commercial products provide corresponding capabilities.
https://www.sphere-ex.cn/comparison/

ShardingShphere 只提供加密功能，关于如何将旧系统平滑上线，SphereEx的商业产品提供了相应能力
https://www.sphere-ex.cn/comparison/
