### ISSUE TITLE
Can ShardingSphere-JDBC support sending the specified slow SQL to the specified data source?

### ISSUE THREAD

**Issue by wwwwwwchun** [apache/shardingsphere#32996]
Detailed requirements:
We have a slow SQL statement and want to query it in the slave database, but other SQL statements are still queried in the master database.
Can you provide a relatively detailed description? We followed the documentation on the homepage and the operation did not seem to work.
Thank you.

**Comment by terrymanu** [comment]
There is currently no such feature.

**Comment by hza2022x** [comment]
@wwwwwwchun  which version are you using?

**Comment by wwwwwwchun** [comment]
> @wwwwwwchun which version are you using?

5.5.0

**Comment by hza2022x** [comment]
client mode or proxy mode?  For more detail you can add my wechat: bjo2008cn
