### ISSUE TITLE
快速入门文档有误

### ISSUE THREAD

**Issue by a4882567** [apache/shardingsphere#33023]
上门引入 非 springboo start 包，下面就开始用 spring boot start 配置

以下是快速入门文档内容
## Question
操作步骤
规则配置。
详情请参见[用户手册](https://github.com/apache/shardingsphere/blob/master/cn/user-manual/shardingsphere-jdbc)。

引入 maven 依赖。
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc</artifactId>
    <version>${latest.release.version}</version>
</dependency>
注意：请将 ${latest.release.version} 更改为实际的版本号。

创建 YAML 配置文件
# JDBC 逻辑库名称。在集群模式中，使用该参数来联通 ShardingSphere-JDBC 与 ShardingSphere-Proxy。
# 默认值：logic_db
databaseName (?):

mode:

dataSources:

rules:
- !FOO_XXX
    ...
- !BAR_XXX
    ...

props:
  key_1: value_1
  key_2: value_2
以 spring boot 为例，编辑 application.properties。
# 配置 DataSource Driver
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
# 指定 YAML 配置文件
spring.datasource.url=jdbc:shardingsphere:classpath:xxx.yaml
**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by strongduanmu** [comment]
For English only, other language will not accept.
