### ISSUE TITLE
Integration druid SQL parser

### ISSUE THREAD

**Issue by 15102552479** [apache/shardingsphere#33027]
## Question

how can I Integration druid SQL parser?sharding-sphere:4.1.1

**Comment by linghengqian** [comment]
- First of all, I don't believe that anyone knows how to extend SPI on the discontinued shardingsphere 4.1.1. You should start the discussion from shardingsphere 5.5.0.
- All you have to do is re-implement the work done in #8284. That sounds like just a few hundred PRs. I assume you plan to submit some PRs?

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by shardcn** [comment]
you can try new version. 
if you can't update to new version.  you may write issules here: https://github.com/shardcn/shardingsphere_4.1.1/issues or https://gitee.com/shardcn/shardingsphere_4.1.1/issues
