### ISSUE TITLE
How to replace sql parser with druid？

### ISSUE THREAD

**Issue by 15102552479** [apache/shardingsphere#33057]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

shardingsphere does not support some complex sql, will it be compatible to replace sql parser with druid? How should the substitution be done

**Comment by terrymanu** [comment]
There is currently no way to implement your request in the existing version; this is not related to functionality.
