### ISSUE TITLE
select count(1) with group by statement return one row when there is actual no data

### ISSUE THREAD

**Issue by peacefulprogram** [apache/shardingsphere#33209]
### Which version of ShardingSphere did you use?
5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
both ShardingSphere-JDBC and ShardingSphere-Proxy

### Reproduce

enviroment:
mysql 5.7
shardingsphere 5.5.0
table:
**t_user**

the following two sql,  **only the order by statement is differenet**, but have diffenrent result;
1. order by fields is same with group by fields, returns no data
![image](https://github.com/user-attachments/assets/e480f979-66d2-4b38-a428-2155fb5daf43)

2. order by fields is different from group by fields, returns one row
![image](https://github.com/user-attachments/assets/d30d6e60-26b8-4342-a1dd-c585f6cff02c)

**they both should returns no data;**

### Reason analyze
when order by fields is differenet from group by fields, GroupByMemoryMergedResult will be used.
in GroupByMemoryMergedResult, if there is no data, it will try to generate one row, when select fields have count(1), it will renturn 0

![image](https://github.com/user-attachments/assets/8ba21055-988e-4740-a952-06234394fd84)

![image](https://github.com/user-attachments/assets/4d84b90c-487c-4a57-a854-54960c93055c)

**Comment by terrymanu** [comment]
What is the configuration?

**Comment by peacefulprogram** [comment]
zookeeper cluster mode, and the sharding rules is in follow image
![image](https://github.com/user-attachments/assets/9f9db350-2b3e-490a-b775-9a17d98e9bfb)

**Comment by terrymanu** [comment]
The issue contains only images, which is not conducive to search or code copying by contributors. Could you please recreate an new issue and describe it again using text and code?

**Comment by peacefulprogram** [comment]
Sure. I'll create a new issue.
