### ISSUE TITLE
how to config default datasource on 5.5.0

### ISSUE THREAD

**Issue by geekerzhou** [apache/shardingsphere#33223]
## Question

a few table need sharding, how to make other table do not use shardingsphere datasource bug use default datasource

**Comment by terrymanu** [comment]
no default datasource on ShardingSphere 5.5.0

**Comment by geekerzhou** [comment]
> no default datasource on ShardingSphere 5.5.0

5.2.1 works fine, 5.5.0 do not support default database auto select. table do not config on rules will throw exception. change version to 5.2.1 everything works fine with same configuration. but 5.2.1 do't open some spi.

**Comment by geekerzhou** [comment]
5.2.1 works fine, 5.5.0 do not support default database auto select. table
do not config on rules will throw exception. change version to 5.2.1
everything works fine with same configuration. but 5.2.1 do't open some spi.

Liang Zhang ***@***.***> 于2024年10月12日周六 22:43写道：

**Comment by terrymanu** [comment]
The project is continuously being upgraded, and the configuration is being simplified. 
If you are interested in the reasons behind the changes, you can take a look at the release notes.
