### ISSUE TITLE
In version 5.3.2 of the proxy, there is a problem with the unknown system variable 'query_cache_size'.

### ISSUE THREAD

**Issue by shining-stars-lk** [apache/shardingsphere#33236]
## Question
In version 5.3.2 of the proxy, there is a problem with the unknown system variable 'query_cache_size'.
## Version
- ShardingSphere-Proxy:5.3.2
- The actual MySQL version being used in the connection:8.0.36

After adding the MySQL driver and modifying the version in the configuration file, what else needs to be modified?
![Dingtalk_20241014114155](https://github.com/user-attachments/assets/a2f8a686-49df-49f6-b18b-c13a153bbf0f)
![Dingtalk_20241014114237](https://github.com/user-attachments/assets/1014b530-2e5d-49aa-b958-058638dec4c7)
![Dingtalk_20241014115114](https://github.com/user-attachments/assets/ee6a06b4-884a-41b9-a5bc-075835a0fbaa)

**Comment by terrymanu** [comment]
Is it duplicated with https://github.com/search?q=repo%3Aapache%2Fshardingsphere+query_cache_size&type=issues ?

**Comment by shining-stars-lk** [comment]
I have modified proxy-mysql-default-version, but it still hasn't been solved
![Dingtalk_20241014114237](https://github.com/user-attachments/assets/39635a5c-bce7-44b8-8cbc-ba5dd0524180)

**Comment by terrymanu** [comment]
So which issue is duplicated?

**Comment by shining-stars-lk** [comment]
I didn't restart zookeeper. Thank you
