### ISSUE TITLE
ERROR 10103 (44000): Storage unit 'ds_2' still used by 'SingleRule'.

### ISSUE THREAD

**Issue by Horriber** [apache/shardingsphere#33252]
1.第一步 添加注册单元
 REGISTER STORAGE UNIT IF NOT EXISTS ds_2 (
    -> HOST="xxx",
    -> PORT=xxx,
    -> DB="xxx",
    -> USER="root",
    -> PASSWORD="xxx",
    -> PROPERTIES("maximumPoolSize"=10)
    -> );
2.使用sql hint进行查询
/* SHARDINGSPHERE_HINT: DATA_SOURCE_NAME = ds_2 */SELECT * from pay_order;
3.移除注册单元
UNREGISTER STORAGE UNIT ds_2;
ERROR 10103 (44000): Storage unit 'ds_2' still used by 'SingleRule'.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
