### ISSUE TITLE
获得错误结果当使用 "explain sql" 在 Sharding-Proxy 5.5.0

### ISSUE THREAD

**Issue by ShayneLee8** [apache/shardingsphere#33290]
Sharding-Proxy 5.5.0

Mysql 5.7

this is sharding config
![企业微信截图_17292218408415](https://github.com/user-attachments/assets/be50477e-d96c-4f28-8b3b-9a5990ff1253)

use explain 
![企业微信截图_17292216752707](https://github.com/user-attachments/assets/4ebffb96-3f5c-4433-8cc5-ffc653ed9a91)

no explain 
![企业微信截图_17292217062548](https://github.com/user-attachments/assets/cb3fc637-20b7-45ed-a85d-9f73f8b09e7c)

When I don't have "explain" I get the correct STORAGE UNIT,
When I add "explain" I get the wrong STORAGE UNIT, why is this happening,
I want to get the correct ds_2, how can I do it

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
