### ISSUE TITLE
How's the sidecar project going? 

### ISSUE THREAD

**Issue by JianZheng168** [apache/shardingsphere#33328]
How's the sidecar project going?  Is it still in the plan?

**Comment by terrymanu** [comment]
The graalvm is prepared for sidecar

**Comment by JianZheng168** [comment]
When is the expected release date for external use? Can you send some relevant documents for learning?

**Comment by JianZheng168** [comment]
@terrymanu This approach realizes containerized deployment through GraalVM. Is there a plan to deploy ShardingSphere proxy through a service mesh sidecar？

**Comment by JianZheng168** [comment]
I saw in the [doc](https://ost.51cto.com/posts/20839) that ShardingSphere-Sidecar is no longer under development. What is the future plan?

**Comment by terrymanu** [comment]
There is no specific plan. 
Are you interested in participating and further defining the roadmap?

**Comment by JianZheng168** [comment]
Thank you for the invitation.  I don't have much time to participate
