### ISSUE TITLE
The SQL statements that do not contain encrypted fields are passed through directly.

### ISSUE THREAD

**Issue by zzyReal666** [apache/shardingsphere#33383]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior

In the encryption feature, if the SQL does not involve encrypted fields, it is passed through directly.
### Actual behavior
Currently, SQL statements that do not involve encrypted fields are processed the same way as other functions, which causes many issues.

**Comment by terrymanu** [comment]
What is the issue details?

**Comment by zzyReal666** [comment]
> What is the issue details?

In the encryption function, the query that does not contain the encryption field must be transparently transmitted.But now, even if you don't include encrypted fields, SSP proxy still do things to SQL that cause a lot of problems, such as not being able to query across libraries or schemas.
Here is the SQL that went wrong :
`SELECT *
from (select a.*, SUBSTRING_INDEX(SUBSTRING_INDEX(a.rcareafks, ',', b.help_topic_id), ',', -1) rcareafk
      from rollcallrule a
               join mysql.help_topic b
      where a.`status` = 'P'
        and b.help_topic_id <= LENGTH(a.rcareafks) - LENGTH(REPLACE(a.rcareafks, ',', '')) + 1) t
where rcareafk is not null
  and rcareafk <> '';`
This sql does not contain encrypted fields, so the proxy simply forwards the request to the database and returns the result.But now I get an error like 'federated query not supported'

**Comment by terrymanu** [comment]
Could you show the details of exception?

**Comment by zzyReal666** [comment]
> 如果仅使用加密，则不应触发联合功能。
> 
> 云您显示您的配置和异常详细信息吗？

There is my config:
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/ddb80592-8491-43c1-9c6e-8d252796891b">
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/09fd4044-5b8b-41ff-8893-4dc8075629cb">


Mr. Zhang. Does the encryption function support cross-library queries, such as a concatenated table query using zzytest and mysql libraries

**Comment by terrymanu** [comment]
I don't think `cross-library` is the concept of ShardingSphere

**Comment by zzyReal666** [comment]
> I don't think `cross-library` is the concept of ShardingSphere

What I mean is `跨库查询`，But I don't know how to translate it. My business database is `zzytest`, but when querying, I jointly queried the system's own database `mysql`.

**Comment by terrymanu** [comment]
Can you update your content?
