### ISSUE TITLE
How can I configure multiple logic schemes, the offical docs provided is not enough to understand

### ISSUE THREAD

**Issue by qgao233** [apache/shardingsphere#33390]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by qgao233** [comment]
questioned in latest version 5.5.1, or older version could support?

**Comment by terrymanu** [comment]
No LTS version available for now.

**Comment by qgao233** [comment]
> No LTS version available for now.

which means I have to start multiple sharding-proxy apps if I still make it come true?

**Comment by terrymanu** [comment]
> > No LTS version available for now.
> 
> which means I have to start multiple sharding-proxy apps if I still make it come true?

I didn't understand, is the LTS version related to this?

**Comment by qgao233** [comment]
> > > No LTS version available for now.
> > 
> > 
> > which means I have to start multiple sharding-proxy apps if I still make it come true?
> 
> I didn't understand, is the LTS version related to this?

I don't want to implement it like I said due to our product's requirement, so seek solutions in sharding-proxy, but if no LTS version could support my requirement, that's okay, just felt tough upset

**Comment by terrymanu** [comment]
This is not a commercial project; the effort required for LTS version is unsustainable for the open source community. The current open source project only invests a lot of energy in development.
If you require support for older versions, perhaps commercial services are what you should consider.

**Comment by qgao233** [comment]
可能有些误解，我不是要说老版本的支持，我的问题是如果使用sharding-proxy，如何配置多个逻辑库，目前我没找到如何配置的操作，我只是想要应用程序连接该中间件，而该中间件有多个逻辑库，对应的逻辑库可有对应的配置分库分表啥的，如：
app->sharding-proxy(
  sharding_db_1[dataSources: ds_0,ds_1], 
  sharding_db_2[dataSources: ds_0,ds_1]
)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
