### ISSUE TITLE
Can not support multiple different database and  SQL federation does not support SQL

### ISSUE THREAD

**Issue by zzyReal666** [apache/shardingsphere#33401]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

### Expected behavior

sql ` select * from  ilp.rollcallrule a join mysql.help_topic b where a.status = 'P';`
The data should be presented correctly.

### Actual behavior
sql ` select * from  ilp.rollcallrule a join mysql.help_topic b where a.status = 'P';`
error : 
  `Unknown exception.
  More details: Can not support multiple different database.`

But when i execute sql ` select * from  rollcallrule a join mysql.help_topic b where a.status = 'P'`.The `rollcallrule` table is not prefixed with  database `ilp`,the error will become :
  `SQL federation does not support SQL '/* ApplicationName=DBeaver 24.1.1 - SQLEditor <Script-2.sql> */ select * from  rollcallrule a join mysql.help_topic b where a.status = 'P'`

ref:https://github.com/apache/shardingsphere/issues/33383

**Comment by terrymanu** [comment]
What is your configuration?
