### ISSUE TITLE
The base image specified in the Dockerfile is ubuntu:22.04, but the built image is 24.04

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#33461]
The base image specified in the Dockerfile is ubuntu:22.04, but the built image is 24.04

Dockerfile configuration file：
![image](https://github.com/user-attachments/assets/50f54162-ff3d-41aa-9ae7-0074cfb14570)

Final image：
![image](https://github.com/user-attachments/assets/756fcad1-0a1b-40f2-b9cb-f11a1dfee880)

**Comment by linghengqian** [comment]
- Ubuntu 22.04 is just a base image for this stage. Feel free to consult the documentation maintained by Docker. 

- According to https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md , the `17-jdk` corresponds to `17.0.13_11-jdk-noble`. Noble is the codename for Ubuntu 24.04.

**Comment by Y-sir** [comment]
@linghengqian ok thank you
