### ISSUE TITLE
Are there unit tests for metadata in shardingsphere?

### ISSUE THREAD

**Issue by makssent** [apache/shardingsphere#33477]
Are there tests for metadata in shardingsphere and where can I read about them? I couldn't find any information in the documentation.

**Comment by terrymanu** [comment]
Could you make the title more meaningful so that the content of the issue can be understood through the title?

**Comment by makssent** [comment]
better?

**Comment by terrymanu** [comment]
There are lots of unit test in metadata.
FYI: https://app.codecov.io/gh/apache/shardingsphere/tree/master/kernel%2Fmetadata

**Comment by makssent** [comment]
> There are lots of unit test in metadata.
> 
> FYI: https://app.codecov.io/gh/apache/shardingsphere/tree/master/kernel%2Fmetadata

Yes, that's exactly what I was looking for, thank you.
