### ISSUE TITLE
Make Sharding-Proxy control language like SQL grammar

### ISSUE THREAD

**Issue by yanickxia** [apache/shardingsphere#3349]
### Describe the feature you would like.

Sharding-Proxy control language not like SQL grammar, it's strange,  if make it like SQL grammar then better i think.

**Comment by yanickxia** [comment]
| NOW  | TO |  REF |
| ------------- | ------------- |  ------- |
| sctl:set transaction_type=XX  | set sctl:transaction_type XX   |      [Mysql-SET-transaction-Syntax](https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html)         |
| sctl:show transaction_type  | show sctl:transaction_type |               |
| sctl:show cached_connections	| show sctl:cached_connections | |
| sctl:explain SQL	| explain sctl:sql | |
| sctl:hint set MASTER_ONLY=true | set sctl:hint:MASTER_ONLY true ||
| sctl:hint set DatabaseShardingValue=yy | set sctl:hint:DatabaseShardingValue yy | |
| sctl:hint addDatabaseShardingValue xx=yy | set sctl:hint: addDatabaseShardingValue  yy| |
| sctl:hint addTableShardingValue xx=yy | set sctl:hint:addTableShardingValue  xx yy| |
| sctl:hint clear | set sctl:hint clear | |
| sctl:hint show status	 | show sctl:hint:status || 
| sctl:hint show table status	 | show sctl:hint:table:status ||


@terrymanu

**Comment by terrymanu** [comment]
Great. For new sctl sql, can we consider about remove sctl, just use it like a original DAL SQL?

For example, just `explain SQL`, beside original resultset, we can appned additional result set for route and merge info in it.
Any suggestions?

**Comment by cherrylzhao** [comment]
shall we parse SCTL SQL statement  instead of  regular expression?

**Comment by cherrylzhao** [comment]
I think we can replace it step by step, first just support` explain sctl:sql`

**Comment by yanickxia** [comment]
| NOW  | TO |  REF |
| ------------- | ------------- |  ------- |
| sctl:set transaction_type=XX  | set transaction_type XX   |      [Mysql-SET-transaction-Syntax](https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html)         |
| sctl:show transaction_type  | show transaction_type |               |
| sctl:show cached_connections	| show cached_connections | |
| sctl:explain SQL	| explain sql | should merge result with db `explain sql` |
| sctl:hint set MASTER_ONLY=true | set MASTER_ONLY [true \|false] ||
| sctl:hint set DatabaseShardingValue=yy | set DatabaseShardingValue yy | |
| sctl:hint addDatabaseShardingValue xx=yy | set addDatabaseShardingValue   yy| |
| sctl:hint addTableShardingValue xx=yy | set addTableShardingValue xx yy| |
| sctl:hint clear | set hint clear | |
| sctl:hint show status	 | show hint_status || 
| sctl:hint show table status	 | show hint_table_status ||

@terrymanu  update.  has any suggestions?

@cherrylzhao  yeah, wo can replace it step by step..

**Comment by terrymanu** [comment]
Sorry to reply late. It is all fine now.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more 1 year, we will close it. 
The most recent refactoring of SCTL: https://github.com/apache/shardingsphere/issues/11677
