### ISSUE TITLE
Table or view 'undo_log' does not exist

### ISSUE THREAD

**Issue by SilenceDevelopers** [apache/shardingsphere#33523]
shardingsphere-jdbc 5.5.0 org.apache.seata 2.2.0
my yaml:
```java
spring:
  application:
    name: cola-consumer
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url:  #jdbc:shardingsphere:classpath:sharding.yaml
``` 

my sharding.yaml:
```java
dataSources:
  ds_0:
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.78.201:3306/tb_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  ds_1:
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.78.201:3307/tb_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


rules:
  - !SHARDING
    tables:
      sharding_order:
        actualDataNodes: ds.sharding_order_${0..1}
        databaseStrategy: # 分库策略，缺省表示使用默认分库策略，以下的分片策略只能选其一
          none:
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: table_inline
    shardingAlgorithms:
      table_inline: # 分表策略
        type: INLINE
        props:
          # strategy: STANDARD
          algorithm-expression: sharding_order_$->{id % 2 + 1}
  - !READWRITE_SPLITTING
    dataSources:
      ds:
        writeDataSourceName: ds_0
        readDataSourceNames:
          - ds_1
        loadBalancerName: round-robin
    loadBalancers:
      round-robin:
        type: RANDOM

props:
  sql-show: true

transaction:
  defaultType: BASE
  providerType: Seata
```
my undo_logs:
![微信图片_20241104054328](https://github.com/user-attachments/assets/23e1ebc1-0418-44c3-a70c-a7c180281762)
![微信图片_20241104054336](https://github.com/user-attachments/assets/585d597d-51c5-45cd-9ca1-9656cd727e60)

when I start up,  the error is :Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Table or view 'undo_log' does not exist.

my datasource is com.alibaba.druid.pool.DruidDataSource

I don't know why

**Comment by linghengqian** [comment]
- Can you share a git containing unit tests for testcontainers-java ? The master branch has no problems with the seata integration tests for postgres .
- By the way, the docker image of seata server does not carry the mysql jdbc driver jar starting from v2.1.0.

**Comment by SilenceDevelopers** [comment]
ok  I will upload my project sooner.

**Comment by linghengqian** [comment]
@SilenceDevelopers I don't need all the relevant code, I just need a unit test execution process similar to https://github.com/linghengqian-scratches/code-repo/tree/re-test. The git you uploaded seems to contain multiple unit tests. Which unit test throws the error log you refer to? What are the steps to reproduce?

**Comment by SilenceDevelopers** [comment]
oh,sorry,I misunderstood. I didn't do a unit test.  just When I was integrating the project, I found that the whole project would not start.

**Comment by SilenceDevelopers** [comment]
I found out from the logs that shardingjdbc references Hikari and Druid, but the database driver I configured did not reference Hikari.

**Comment by linghengqian** [comment]
> I found out from the logs that shardingjdbc references Hikari and Druid, but the database driver I configured did not reference Hikari.

- I have explained a lot about alibaba druid in the Chinese article https://www.yuque.com/linghengqian/meve2v/zoy35sivtf6nzp90 mentioned in https://github.com/apache/shardingsphere/discussions/12258#discussioncomment-10427297 . 
- By default, the metadata of shardingsphere is stored in the `h2database in memory mode`, which will create an additional hikaricp database connection pool. 
- If you do not want to create a hikaricp database connection pool, consider the `Cluster Mode` provided by https://shardingsphere.apache.org/document/current/cn/user-manual/common-config/builtin-algorithm/metadata-repository/ , or create your own SPI implementation.
- Before https://github.com/alibaba/druid/pull/6143 is reviewed, I would not recommend using alibaba druid. According to https://github.com/apache/shardingsphere/issues/32765, druid has at least 4 bugs that existed 7 years ago that affect third-party application integration, although it does not affect simple use. This is why shardingsphere's master branch does not test druid at all.

**Comment by SilenceDevelopers** [comment]
OK,Thank you for your answer.

**Comment by linghengqian** [comment]
- By the way, if your seata server only uses file mode, you don't need to provide the mysql jdbc driver jar for the seata server's docker container. The seata server's docker container normally does not need to communicate with the mysql server unless you save the seata server's metadata in a mysql server and change the seata server's mode.
