### ISSUE TITLE
The following error message appears when executing an SQL statement with an ORDER BY clause in Oracle: "Order by value must implement Comparable."

### ISSUE THREAD

**Issue by NjuptMei** [apache/shardingsphere#33589]
### Which version of ShardingSphere did you use?
shardingsphere Ver. sharding-jdbc-spring-boot-starter, 4.1.1
oracle Ver. oracle12c
ojdbc Ver. ojdbc8

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
config：
actualDataNodes: ds0.dmg_kettle_conf, ds0.dmg_kettle_config_dmgtmp
logicTable: dmg_kettle_config
behavior：
when executing SQL "select * from dmg_kettle_config order by create_timstmp desc", except the ordered result, the dataTye of **create_timstmp is TimeStamp With Time Zone**, (doesn't support this dataType?)
### Actual behavior
when executing SQL "select * from dmg_kettle_config order by create_timstmp desc", the error message  "Order by value must implement Comparable." occurs

### Reason analyze (If you can)
When executing query, in `oracle.jdbc.driver.OracleResultSetMetaData.getColumnType`, the create_timstmp dataType is 181, and mappings to code -101
![image](https://github.com/user-attachments/assets/00a9ff80-d063-4d4c-aebf-40e9cbc7397d)
and in shardingJdbc, when merging resut, it only transfer the code 93 to java.sql.Timestamp, but the code -101 convert to Object:
`org.apache.shardingsphere.sharding.execute.sql.execute.result.MemoryQueryResult.getRows(ResultSet resultSet)`
![image](https://github.com/user-attachments/assets/7dc1eb01-76a8-4e61-b93f-440a8ee6eeea)
so, when code running the order executor: `org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValues()`, cause this error.
![image](https://github.com/user-attachments/assets/c3afe038-1eff-4425-b921-ed11053b42c5)
btw: Setting the following parameter: System.getProperties().setProperty("oracle.jdbc.J2EE13Compliant", "true") is ineffective.

[https://shardingsphere.apache.org/document/4.1.1/en/faq/#10-why-does-oracle-database-throw-order-by-value-must-implements-comparable-exception-when-using-timestamp-order-by](https://shardingsphere.apache.org/document/4.1.1/en/faq/#10-why-does-oracle-database-throw-order-by-value-must-implements-comparable-exception-when-using-timestamp-order-by)
  
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL "select * from dmg_kettle_config order by create_timstmp desc", **create_timstmp is TimeStamp With Time Zone**, (doesn't support this dataType?)

**Comment by terrymanu** [comment]
The version is out of service, please try new version.

**Comment by NjuptMei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by NjuptMei** [comment]
> The version is out of service, please try new version.

i have updated the version shardingsphere5.4.1, the question is also occur
