### ISSUE TITLE
Can shardingsphere support show slow sql?

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#33595]
Can shardingsphere support show slow sql? How to config?

version: 5.1.1

**Comment by linghengqian** [comment]
- As far as I can remember, ShardingSphere has never implemented this directly. But you can directly use OpenTelemetry Java agent to forward to a third-party APM platform to collect slow SQL. Elastic Kibana, Apache SkyWalking UI and Jaeger UI all have the function of analyzing the slow SQL in the data sent by OpenTelemetry SDK. 

- For 5.5.1, if you happen to be using MySQL, you can also use p6spy jdbc driver. Consider https://github.com/apache/shardingsphere/pull/31814 .

**Comment by penghuazhou** [comment]
thanks

**Comment by penghuazhou** [comment]
thanks
