### ISSUE TITLE
Could you update shardingsphere-jdbc-core-spring-boot-starter to the latest version?

### ISSUE THREAD

**Issue by Xiao-A-Zhai** [apache/shardingsphere#33608]
Due to work requirements, we have updated the Java version to 22. As some libraries also need to be upgraded, we found that ShardingSphere needs to be updated to 5.4.1. However, we could not find the corresponding version of shardingsphere-jdbc-core-spring-boot-starter, which has led to compatibility issues
![5af8acce106020b0d0e8286932dea19](https://github.com/user-attachments/assets/e2802862-d365-4725-a72a-8407f5841a26)
The above image shows compatibility errors between shardingsphere-jdbc-core 5.4.2 and shardingsphere-jdbc-core-spring-boot-starter 5.2.1. In fact, there are many compilation errors, and I have only captured a portion of the code.

**Comment by Xiao-A-Zhai** [comment]
shardingsphere-jdbc-core is 5.4.1, not 5.4.2. There was a typo in the input.

**Comment by linghengqian** [comment]
Spring boot starter has been removed. See #22469. We removed Spring boot starter to support Spring boot oss 2.x, Spring boot oss 3 and Graalvm native image.
