### ISSUE TITLE
Shardingshpere Connection is not available after stress test only restarted Shardingshpere can recover

### ISSUE THREAD

**Issue by penghuazhou** [apache/shardingsphere#33627]
shardingshpere version: 5.1.1

When I stress test Shardingshpere, it throws the following error. I will stop the stress test after 24 hours. When I execute the following SQL, it also throws this error. I restarted Shardingshpere and the SQL execution was normal.

`HikariPool-2 - Connection is not available, request timed out after 30000ms`

I will stop the stress test after 24 hours. When I execute the following SQL, it also throws this error.
![image](https://github.com/user-attachments/assets/959839e1-6f6d-447c-a75b-0113d78b8159)

I restarted Shardingshpere and the SQL execution was normal.
![image](https://github.com/user-attachments/assets/4c93d0fe-869f-45cd-96ec-23e652da0a1c)

![image](https://github.com/user-attachments/assets/a1816953-e28c-413f-b1ae-fa7dec580bc9)

only one slow sql, execute 20 times.
![image](https://github.com/user-attachments/assets/b1b10846-3ae7-499a-a841-72e3da8728ec)

**Comment by terrymanu** [comment]
The performance of  lasted version has been improved.
Can you try it?
