### ISSUE TITLE
Will shardingproxy support alibaba-cobar sharing-rule?

### ISSUE THREAD

**Issue by cocktail828** [apache/shardingsphere#33647]
### Is your feature request related to a problem?
No.

### Describe the feature you would like.
Due to various historical reasons, our company currently has a large number of old businesses using ALIBABA-COBAR database middleware. We expect to update the middlware to ShardingProxy but it is difficult to implement due the to incompatible sharding rules. 
We tried to implement a plugin ourselves, but the company think the custom plugin is unreliable, unmaintained, and difficult to upgrade.
Can sharddingproxy provide an official implementation of the plugin to support cobar's sharding rules?

**Comment by terrymanu** [comment]
No plan
