### ISSUE TITLE
Sharding  not support ZoneDateTime

### ISSUE THREAD

**Issue by fyeeme** [apache/shardingsphere#33660]
### Which version of ShardingSphere did you use?

5.5.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC 

### Expected behavior

zoneDateTime can be parsed correctly

### Actual behavior

The field was parsed as LocalDateTime, which subsequently caused a conversion exception.

```
Caused by: java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.time.ZonedDateTime (java.time.LocalDateTime and java.time.ZonedDateTime are in module java.base of loader 'bootstrap')
	at org.apache.ibatis.type.ZonedDateTimeTypeHandler.getNullableResult(ZonedDateTimeTypeHandler.java:39)
	at org.apache.ibatis.type.ZonedDateTimeTypeHandler.getNullableResult(ZonedDateTimeTypeHandler.java:29)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:86)
	... 157 more
```

### Reason analyze (If you can)
org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.type.stream.JDBCStreamQueryResult#getValue

<img width="875" alt="image" src="https://github.com/user-attachments/assets/047b5a4a-7a2c-4f1f-abec-6687029a6b42">
should be 

```java
 return resultSet.getObject(columnIndex, type);
```

<img width="1600" alt="image" src="https://github.com/user-attachments/assets/30749f30-af14-4e82-a7df-3d9f804fb43d">

The type-specified resultSet.getObject supports parsing ZonedDateTime. However, in  `org.apache.shardingsphere.infra.executor.sql.execute.result.query.impl.driver.jdbc.type.stream.JDBCStreamQueryResult#getValue`, the method’s last line calls return resultSet.getObject(columnIndex); without specifying a type, resulting in ZonedDateTime parsing not being applied.

As a result, this method defaults to parsing database fields with dateTime types as LocalDateTime.

**Comment by terrymanu** [comment]
The CI are all broken, can you fix it?

**Comment by fyeeme** [comment]
Ok, I wil fix it asap

**Comment by terrymanu** [comment]
Well done!
