### ISSUE TITLE
ShardingConditions to avoid same record in table 't_order' routing to multiple data nodes.

### ISSUE THREAD

**Issue by clay-f** [apache/shardingsphere#33688]
### Which version of ShardingSphere did you use?
5.5.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
I'm follow official website doc，copy [example config](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/) and get error
### Actual behavior

this is final error

![error](https://github.com/user-attachments/assets/b268baa2-db8d-442c-9d81-4e32cf4511da)

### Reason analyze (If you can)

I'm change

    actualDataNodes: ds_${0..1}.t_order_${0..1}

to

    actualDataNodes: ds_0.t_order_${0..1}

insert value succeed

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

database schema 
![sql_schema](https://github.com/user-attachments/assets/8f2bba0a-6d47-4af8-88d1-5f3c8afeb0df)

below is config file, will get **to avoid same record in table 't_order' routing to multiple data nodes**

    mode:
      type: Standalone
      repository:
        type: JDBC
    
    dataSources:
      ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/sharding_db0?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password:
      ds_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/sharding_db1?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password:
    
    rules:
      - !SHARDING
        tables:
          t_order:
            actualDataNodes: ds_${0..1}.t_order_${0..1}
            tableStrategy:
              standard:
                shardingColumn: order_id
                shardingAlgorithmName: t_order_inline
            keyGenerateStrategy:
              column: order_id
              keyGeneratorName: snowflake
            auditStrategy:
              auditorNames:
                - sharding_key_required_auditor
              allowHintDisable: true
        bindingTables:
          - t_order
        shardingAlgorithms:
          t_order_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_${order_id % 2}
        keyGenerators:
          snowflake:
            type: SNOWFLAKE
        auditors:
          sharding_key_required_auditor:
            type: DML_SHARDING_CONDITIONS
    
    props:
      sql-show: true
    

### Example codes for reproduce this issue (such as a github link).

test insert order code

![error_code](https://github.com/user-attachments/assets/387f7650-aa9d-4797-8b06-62112c71eab0)

entity order object
![image](https://github.com/user-attachments/assets/de3c2bee-a372-45a9-89ae-576e94fc6c86)

pom file and spring boot version is 3.3.1

![image](https://github.com/user-attachments/assets/13088ce3-1620-47e1-b9fb-05f21fac8981)

project structure
![image](https://github.com/user-attachments/assets/633bdfd3-e0d5-4942-9b29-8f66d5181d3e)

**Comment by Yash-cor** [comment]
`rules:
- !SHARDING
    tables:
      t:
        actualDataNodes : ds${0..1}.t${0..1}
        databaseStrategy:
          standard:
            shardingColumn: ID
            shardingAlgorithmName: mod_d
        tableStrategy :
          standard:
            shardingColumn: ID
            shardingAlgorithmName: mod
        keyGenerateStrategy:
          column: ID
          keyGeneratorName: snowflake
    shardingAlgorithms:
      mod:
        type: INLINE
        props:
          algorithm-expression : t${ID%2}
      mod_d:
        type: INLINE
        props:
          algorithm-expression: ds${ID%2}
    keyGenerators :
      snowflake :
        type : SNOWFLAKE`
        
        Using this configuration would solve your problem

**Comment by clay-f** [comment]
yeah!，I'm added database strategy config ，test insert data succeed

    mode:
      type: Standalone
      repository:
        type: JDBC
    
    dataSources:
      ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/sharding_db0?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password:
      ds_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/sharding_db1?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password:
    
    rules:
      - !SHARDING
        tables:
          t_order:
            actualDataNodes: ds_${0..1}.t_order_${0..1}
            databaseStrategy:
              standard:
                shardingColumn: id
                shardingAlgorithmName: mod_db
            tableStrategy:
              standard:
                shardingColumn: order_id
                shardingAlgorithmName: t_order_inline
            keyGenerateStrategy:
              column: order_id
              keyGeneratorName: snowflake
            auditStrategy:
              auditorNames:
                - sharding_key_required_auditor
              allowHintDisable: true
        bindingTables:
          - t_order
        shardingAlgorithms:
          t_order_inline:
            type: INLINE
            props:
              algorithm-expression: t_order_${order_id % 2}
          mod_db:
            type: INLINE
            props:
              algorithm-expression : ds_${id % 2}
        keyGenerators:
          snowflake:
            type: SNOWFLAKE
        auditors:
          sharding_key_required_auditor:
            type: DML_SHARDING_CONDITIONS
    
    props:
      sql-show: true
