### ISSUE TITLE
sharding-proxy link leak

### ISSUE THREAD

**Issue by YouSec995** [apache/shardingsphere#33718]
sharding version: 5.1.1
We found some problems here. We use gorm to link sharding and sharding to access mysql. Currently, we find that sharding has been growing CLOSE_WAIT links. At the same time, ss -s found that there are a large number of closed file handles in tcp (also growing, suspected of leaking). .

[root@]# netstat -an|grep CLOSE_WAIT
tcp6 1 0 1...95:23307 1...63:39174 CLOSE_WAIT
tcp6 1 0 1*..95:23307 1...114:4033 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...143:26496 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...37:61413 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...42:46421 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...22:56900 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...147:63209 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...14:17836 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...14:28253 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...143:42634 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...143:16788 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...22:34969 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...143:21811 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...22:17333 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...56:8017 CLOSE_WAIT
tcp6 147 0 1..95:23307 1...14:61618 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...63:7849 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...147:6705 CLOSE_WAIT
tcp6 1 0 1..95:23307 1...143:36122 CLOSE_WAIT
tcp6 1 0 1..95:23307 1..*.42:41520 CLOSE_WAIT[root@ conf]# ss -s
Total: 5959
TCP: 5753 (estab 33, closed 5694, orphaned 0, timewait 4)

Transport Total IP IPv6
RAW 1 0 1
UDP 4 3 1
TCP 59 7 52
INET 64 10 54
FRAG 0 0 0

**Comment by YouSec995** [comment]
We are sure that our business party initiated the FIN request and sharding is in CLOSE_WAIT

**Comment by terrymanu** [comment]
The version is pretty ancient, could you try the lasted version?
