### ISSUE TITLE
疑似sharding链接泄漏

### ISSUE THREAD

**Issue by YouSec995** [apache/shardingsphere#33713]
sharding版本：5.1.1
这边发现了要一些问题  我们使用gorm链接sharding，sharding来访问mysql，目前发现sharding一直在增长CLOSE_WAIT链接，同时ss -s发现tcp存在大量的closed状态的文件句柄（也是一直在增长，疑似泄漏）。

closed多的时候有好几万的，以下是我们重启sharding之后，慢慢增长的结果
23307是sharding启动的端口

[root@]# netstat -an|grep CLOSE_WAIT
  tcp6       1      0 1.*.*.95:23307       1.*.*.63:39174       CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.114:4033        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.143:26496      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.37:61413        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.42:46421        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.22:56900        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.147:63209      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.14:17836       CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.14:28253       CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.143:42634      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.143:16788      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307       1.*.*.22:34969        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.143:21811      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307       1.*.*.22:17333        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.56:8017        CLOSE_WAIT
  tcp6     147      0 1*.*.95:23307       1.*.*.14:61618       CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307       1.*.*.63:7849        CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.147:6705       CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.143:36122      CLOSE_WAIT
  tcp6       1      0 1*.*.95:23307        1.*.*.42:41520        CLOSE_WAIT[root@ conf]# ss -s
Total: 5959
TCP:   5753 (estab 33, closed 5694, orphaned 0, timewait 4)

Transport Total     IP        IPv6
RAW	  1         0         1
UDP	  4         3         1
TCP	  59        7         52
INET	  64        10        54
FRAG	  0         0         0

**Comment by kimmking** [comment]
You can use tcpdump to capture some tcp chains to determine which side interrupting the link.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
