### ISSUE TITLE
Failed to execute the SQL update statement

### ISSUE THREAD

**Issue by sidikaisi** [apache/shardingsphere#33728]
We're using ShardingSphere-Proxy, and when I just want to update the statement, the update fails. It is found that the updated field value contains English semicolons, so the update failed. For example, update user set user_name='ssss; A statement such as' where id=1 'will fail. May I ask why?
My configuration of global.yaml is as follows:
mode:
type: Standalone
repository:
type: JDBC
authority:
users:
- user: root@%
password: 121312414314
privilege:
type: ALL_PERMITTED
props:
system-log-level: INFO
sql-show: false
max-connections-size-per-query: 1
check-table-metadata-enabled: false
proxy-frontend-flush-threshold: 128
proxy-backend-query-fetch-size: -1
proxy-frontend-executor-size: 0
proxy-frontend-max-connections: 5000
proxy-default-port: 3307
proxy-netty-backlog: 1024
proxy-hint-enabled: true
proxy-backend-driver-type: JDBC

**Comment by terrymanu** [comment]
What is your version?

**Comment by sidikaisi** [comment]
> What is your version?

5.5.0

**Comment by terrymanu** [comment]
What is the exception?

**Comment by sidikaisi** [comment]
> What is the exception?

No exception is seen, that is, the number of rows returned is 0 and the data has not been updated

**Comment by terrymanu** [comment]
What is rule configuration, table metadata and desire updated data?

**Comment by sidikaisi** [comment]
> What is rule configuration, table metadata and desire updated data?

My problem is the same as this one. Is it OK to change to the lower version? Has this problem been solved?
https://github.com/apache/shardingsphere/issues/31609

**Comment by terrymanu** [comment]
The issue is still open

**Comment by terrymanu** [comment]
> > What is rule configuration, table metadata and desire updated data?
> 
> My problem is the same as this one. Is it OK to change to the lower version? Has this problem been solved? #31609

The issue is still open
