### ISSUE TITLE
 How shardingsphere is managed by DymaicDataSource？

### ISSUE THREAD

**Issue by zhuzhiquan** [apache/shardingsphere#33730]
## Question

 How shardingsphere is managed by DymaicDataSource？

The effect I want to achieve：By default, shardingsphere read-write separation takes effect, and special businesses use the library partitioning annotation of dynamicDataSource。。。

**Comment by linghengqian** [comment]
- This is what https://github.com/dynamic-datasource/dynamic-datasource-samples/tree/master/third-part-samples%2Fshardingsphere-sample%2Fshardingsphere-jdbc-5.x-core-sample does. You just need to set the primary datasource of `baomidou dynamic datasource spring boot starter` to `shardingsphere jdbc datasource`.

- Shardingsphere jdbc datasource can be multi-instance.

**Comment by linghengqian** [comment]
- By the way, https://github.com/dynamic-datasource/dynamic-datasource-samples does not belong to ASF or Baomidou. It's just that I ( Apache Shardingsphere Committer ) and several other Baomidou committers wrote examples in this git.
