### ISSUE TITLE
[SQLLogger] : Wanted to check if there is a way to handle to remove logs "Logic SQL:" and keep  "Actual SQL"

### ISSUE THREAD

**Issue by atul-singh-20230331** [apache/shardingsphere#33736]
Is is possible to remove the the log "Logic SQL:"  log from below class line no 46 ? 

I can see there is a config "ConfigurationPropertyKey.SQL_SHOW" to show the logic sql log is there  but that would remove "Actual SQL" log also . 

is there anyway to show "Actual SQL" log and remove "Logic SQL:"

Class for reference: 

https://github.com/apache/shardingsphere/blob/71b72a0b4563a8c3e4b42247692b237ac7b83944/infra/executor/src/main/java/org/apache/shardingsphere/infra/executor/sql/log/SQLLogger.java#L46

**Comment by terrymanu** [comment]
Logic SQL is the external SQL of ShardingSphere and should always be paid attention to.

**Comment by atul-singh-20230331** [comment]
Thanks Terry for the reply. 
Understood, is there any plan to decouple "Actual SQL"   and "Logic SQL:" logging from same method . Currently "Actual SQL" can only be enabled only if "Logic SQL:" is enabled .

**Comment by terrymanu** [comment]
For my understanding, Logic SQL is required which can be a key, Actual SQLs are optional which should be values.

**Comment by atul-singh-20230331** [comment]
Thanks @terrymanu   it's clear now and appreciate your quicker response.
