### ISSUE TITLE
Support GroupConcat sql for aggregating multiple shards

### ISSUE THREAD

**Issue by YaoFly** [apache/shardingsphere#33797]
## Feature Request

1. Shardingsphere currently only supports GROUP_CONCAT(parms SEPARATOR expr), not GROUP_CONCAT(parms)
2. Shardingsphere's GROUP_CONCAT currently does not support the aggregation of multiple shards

For example, table t_order has a field order_no, exists in databases A and B
database A:
1.aaa
2.bbb
database B:
1.ccc
2.ddd

execute select GROUP_CONCAT(order_no SEPARATOR ' ') from t_order;
The actual result is:
1.aaa bbb
2.ccc ddd
The expected result is:
1.aaa bbb ccc ddd

execute select GROUP_CONCAT(order_no) from t_order;
The actual result is:
[0A000][30001] Unsupported SQL operation: GROUP_CONCAT.
The expected result is:
1.aaa,bbb,ccc,ddd

if support is needed, I will contribute code.

**Comment by YaoFly** [comment]
@strongduanmu  PTAL

**Comment by strongduanmu** [comment]
@YaoFly Welcome to submit PR to support GROUP_CONCAT, which will help improve ShardingSphere's SQL support.
