### ISSUE TITLE
How to use sharding.yaml in nacos with spring.datasource.url ?

### ISSUE THREAD

**Issue by WangYehen** [apache/shardingsphere#33798]
Configuration in application.properties, spring. datasource.url=jdbc:shardingsphere:classpath:sharding.yaml. Will future versions support loading nacos configuration files, such as spring. datasource.url=jdbc:shardingsphere:nacos://server-addr:8848/sharding.yaml, I don't want to write it in the code because the sharding.yaml, beacuse configuration file contains sensitive data source information. Is there any way to transfer sharding.yaml to nacos and read the configuration now?

**Comment by terrymanu** [comment]
Can not support nacos

**Comment by WangYehen** [comment]
> Can not support nacos

ok，thank u

**Comment by linghengqian** [comment]
> spring.datasource.url=jdbc:shardingsphere:nacos://server-addr:8848/sharding.yaml

- As far as I know, Nacos is not a file system. If it were a file system, it should at least be able to integrate with https://github.com/apache/opendal . But this kind of thing did not happen.
- Allowing the shardingsphere jdbc driver to pull YAML configuration files from the dozens of file systems supported by opendal is indeed on my personal TODO, but this happens to be affected by an issue on the roadmap of OpenDAL's java bindings.

**Comment by 0xu8d75** [comment]
@WangYehen  try this : [https://0xu8d75.github.io/2024/10/08/springcloud%E9%9B%86%E6%88%90shardingsphere5-5-0%E4%BD%BF%E7%94%A8nacos%E4%BD%9C%E4%B8%BA%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83/](https://0xu8d75.github.io/2024/10/08/springcloud%E9%9B%86%E6%88%90shardingsphere5-5-0%E4%BD%BF%E7%94%A8nacos%E4%BD%9C%E4%B8%BA%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83/)
[https://github.com/0xu8d75/spring-cloud-parent/blob/master/spring-cloud-core/src/main/java/com/u8d75/core/shardingsphere/SpringNacosURLLoader.java](https://github.com/0xu8d75/spring-cloud-parent/blob/master/spring-cloud-core/src/main/java/com/u8d75/core/shardingsphere/SpringNacosURLLoader.java)
you can implement ShardingSphereURLLoader class integration shardingsphere config in nacos to spring
