### ISSUE TITLE
force to read data from zookeeper

### ISSUE THREAD

**Issue by motume** [apache/shardingsphere#33821]
shardingsphere proxy version:5.1.2
2 proxy node,1 zookeeper node
one of the two nodes add encrypt rule for table,but in other node the new rules can't be detected. 
could you pls tell me whether the following command can  force to read data from zookeeper?or other way?
curl -X POST http://<proxy_host>:proxy_port>/shardingsphere/refresh

## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
What's mean about curl?

**Comment by motume** [comment]
I tried to search from AI,it advise me force to read data from zookeeper by this  command(curl -X POST http://<proxy_host>:proxy_port>/shardingsphere/refresh)

> What's mean about curl?

**Comment by terrymanu** [comment]
I don't think it is a correct description.

**Comment by motume** [comment]
2 proxy node,1 zookeeper node
one of the two nodes add encrypt rule for table,but in other node the new rules can't be detected.how  to  solve the problem?
