### ISSUE TITLE
shardingsphere-proxy5.5 datasource is postgresql，when select keywaord an error is reported ，For example position keyword

### ISSUE THREAD

**Issue by lijuchuan** [apache/shardingsphere#33833]
problem：

select position  from test；

error：
dhri=> select position from org_staff;
ERROR:  You have an error in your SQL syntax: no viable alternative at input 'selectpositionfrom'

i changed to：
dhri=> select 'position' from org_staff;
 ?column?
----------
 position
 position
 position

**Comment by zzyReal666** [comment]
`position` is a keyword.
Can this SQL be executed directly in the database? 
 `select position from test；`

**Comment by zzyReal666** [comment]
I had a similar problem in distSQL.Because my field is name, but name is the distSQL keyword.

**Comment by zzyReal666** [comment]
> > I had a similar problem in distSQL.Because my field is `name`, but `name` is the distSQL keyword.
> 
> how do u solve it？

I changed `name` to `t_name`.Because it's the most direct and the fastest.I have an untested idea.If you have to use keywords as column names, I'll try later to see if my idea solves this problem.

**Comment by zzyReal666** [comment]
Which version do you use, I use the latest version test can run `select "position" from test`;

**real database** ,both `select position from test` and  `select "position" from test` success execute:
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/847852c8-afb6-45f9-b488-38b08cf06053">

**proxy database**,only `select "position" from test` success execute:
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/ee96206b-91df-49a3-803f-79a573d119b7">
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/ad0dd11e-1b0c-4c0f-a516-00f1cd53e2ee">

**Comment by zzyReal666** [comment]
Use double quotes instead of single quotes.
