### ISSUE TITLE
Operation error using cursor in postgresql database

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#33920]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
As shown below, you can get the data
![image](https://github.com/user-attachments/assets/af69c221-b1bd-4a15-8e1f-907cf1c10e9e)
### Actual behavior
When getting data by scrolling the cursor, this error is prompted; ERROR: Unknown exception.
More details: java.lang.IllegalArgumentException: Cursor cur_test does not exist.
![image](https://github.com/user-attachments/assets/4c2eeedc-c684-44f6-aa7b-d0bf78401fd6)
### Reason analyze (If you can)
The prepareCursorStatementContext method in DatabaseConnector, cursorContext.getCursorStatementContexts() map has no content
![image](https://github.com/user-attachments/assets/34159506-9a4b-45fb-a671-d80ca5e9a6de)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、Create a test table:
`CREATE TABLE "public"."test" (
  "id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "stu_pkey" PRIMARY KEY ("id")
)
;
`
2、Insert some data
`INSERT INTO "public"."test" ("id", "name") VALUES ('1', 'Yung Chieh Lun');
INSERT INTO "public"."test" ("id", "name") VALUES ('2', 'Kinoshita Ayato');
INSERT INTO "public"."test" ("id", "name") VALUES ('3', 'Chang Yunxi');
INSERT INTO "public"."test" ("id", "name") VALUES ('4', 'Long Jialun');
INSERT INTO "public"."test" ("id", "name") VALUES ('5', 'Yin Chi Ming');
INSERT INTO "public"."test" ("id", "name") VALUES ('6', 'Jiang Zhennan');
INSERT INTO "public"."test" ("id", "name") VALUES ('7', 'Yip Ming Sze');
INSERT INTO "public"."test" ("id", "name") VALUES ('8', 'Cheng Siu Wai');
INSERT INTO "public"."test" ("id", "name") VALUES ('9', 'Yam Lik Sun');
INSERT INTO "public"."test" ("id", "name") VALUES ('10', 'Yuan Jiehong');
INSERT INTO "public"."test" ("id", "name") VALUES ('11', 'Ren Xiuying');
INSERT INTO "public"."test" ("id", "name") VALUES ('12', 'Todd Castro');
INSERT INTO "public"."test" ("id", "name") VALUES ('13', 'Duan Jiehong');
INSERT INTO "public"."test" ("id", "name") VALUES ('14', 'Yan Zhiyuan');
INSERT INTO "public"."test" ("id", "name") VALUES ('15', 'Judith Thomas');
INSERT INTO "public"."test" ("id", "name") VALUES ('16', 'Shibata Itsuki');
INSERT INTO "public"."test" ("id", "name") VALUES ('17', 'Francis Kelly');
INSERT INTO "public"."test" ("id", "name") VALUES ('18', 'Fujita Ayano');
INSERT INTO "public"."test" ("id", "name") VALUES ('19', 'Yamaguchi Airi');
INSERT INTO "public"."test" ("id", "name") VALUES ('20', 'Lillian Martin');
INSERT INTO "public"."test" ("id", "name") VALUES ('21', 'Fujii Tsubasa');
INSERT INTO "public"."test" ("id", "name") VALUES ('22', 'Feng Anqi');
INSERT INTO "public"."test" ("id", "name") VALUES ('23', 'Jia Jiehong');
INSERT INTO "public"."test" ("id", "name") VALUES ('24', 'Yeow Yun Fat');
INSERT INTO "public"."test" ("id", "name") VALUES ('25', 'Hasegawa Sara');
INSERT INTO "public"."test" ("id", "name") VALUES ('26', 'Yao Zitao');
INSERT INTO "public"."test" ("id", "name") VALUES ('27', 'Ying Ka Ming');
INSERT INTO "public"."test" ("id", "name") VALUES ('28', 'Nomura Nanami');
INSERT INTO "public"."test" ("id", "name") VALUES ('29', 'Yu Zhiyuan');
INSERT INTO "public"."test" ("id", "name") VALUES ('30', 'Mok Ming Sze');
INSERT INTO "public"."test" ("id", "name") VALUES ('31', 'Kono Airi');
INSERT INTO "public"."test" ("id", "name") VALUES ('32', 'Siu Cho Yee');
INSERT INTO "public"."test" ("id", "name") VALUES ('33', 'Paula Henderson');
INSERT INTO "public"."test" ("id", "name") VALUES ('34', 'Cui Lu');
INSERT INTO "public"."test" ("id", "name") VALUES ('35', 'Yamamoto Hikari');
INSERT INTO "public"."test" ("id", "name") VALUES ('36', 'Ku Yun Fat');
INSERT INTO "public"."test" ("id", "name") VALUES ('37', 'Jack Olson');
INSERT INTO "public"."test" ("id", "name") VALUES ('38', 'Ishii Riku');
INSERT INTO "public"."test" ("id", "name") VALUES ('39', 'Jonathan Gonzales');
INSERT INTO "public"."test" ("id", "name") VALUES ('40', 'Ono Aoi');
INSERT INTO "public"."test" ("id", "name") VALUES ('41', 'Siu Sai Wing');
INSERT INTO "public"."test" ("id", "name") VALUES ('42', 'Jose Alvarez');
INSERT INTO "public"."test" ("id", "name") VALUES ('43', 'Sit Chieh Lun');
INSERT INTO "public"."test" ("id", "name") VALUES ('44', 'Micheal Woods');
INSERT INTO "public"."test" ("id", "name") VALUES ('45', 'Joanne Hamilton');
INSERT INTO "public"."test" ("id", "name") VALUES ('46', 'Choi Wing Kuen');
INSERT INTO "public"."test" ("id", "name") VALUES ('47', 'Nathan Mendoza');
INSERT INTO "public"."test" ("id", "name") VALUES ('48', 'Paul Marshall');
INSERT INTO "public"."test" ("id", "name") VALUES ('49', 'Arimura Yuto');
INSERT INTO "public"."test" ("id", "name") VALUES ('50', 'Zhu Xiuying');
`

**Comment by strongduanmu** [comment]
According to #18414, ShardingSphere currently only supports openGauss cursors, but not PostgreSQL. If you expect to complete this work, you are welcome to claim #18414.

**Comment by strongduanmu** [comment]
Duplicate with #18414
