### ISSUE TITLE
VERSION:5.4.1;Table or view %s does not exist

### ISSUE THREAD

**Issue by Luminary-12138** [apache/shardingsphere#33928]
VERSION：5.4.1
`rules:
  - !SHARDING
    defaultDatabaseStrategy:
      none: {}
    defaultTableStrategy:
      none: {}
    autoTables:
      t_system_point_log:
        actualDataSources: test
        shardingStrategy:
          standard:
            shardingColumn: school_code
            shardingAlgorithmName: auto_school_hash_mod
    tables:
      t_base_course_table_extra:
        actualDataNodes: test.t_base_course_table_extra_${0..9},test.t_base_course_table_extra_${['a','b','c','d','e','f']}
        tableStrategy:
          standard:
            shardingColumn: school_code
            shardingAlgorithmName: inline_school_code
    shardingAlgorithms:
      auto_school_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 3
      inline_school_code:
        type: INLINE
        props:
          algorithm-expression: t_base_course_table_extra_${school_code.substring(0,1).toLowerCase()}
props:
  sql-show: true`

Under version 5.4.1, when I configure it in this way, a prompt of "Table or view %s does not exist" will appear when querying a single table.
When using version 5.4.1, most of our tables are single tables that don't need to be partitioned. In order to avoid the problem of "Table or view %s does not exist", do we have to manually configure all the tables in the yml file? It's a bit cumbersome. Are there any other ways?

**Comment by zzyReal666** [comment]
ref:https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/single/
