### ISSUE TITLE
修改表结构后，select * 异常

### ISSUE THREAD

**Issue by wpinchine** [apache/shardingsphere#33983]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-jdbc:5.5.X

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

### Reason analyze (If you can)
select * 处理返回值的时候使用了进程启动时加载的表结构缓存，增删表结构之后，字段数量与类型无法对齐。通过数组下标获取缓存的表结构字段时候：在表结构中间添加字段时，表结构字段次序发生变更，可能会产生类型转换异常；在删除字段的时候，会产生数组越界异常。

**Comment by strongduanmu** [comment]
For English only, other language will not accept.
