### ISSUE TITLE
select * will be error after change table structure

### ISSUE THREAD

**Issue by wpinchine** [apache/shardingsphere#33988]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-jdbc:5.5.X

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

### Reason analyze (If you can)
select * 处理返回值的时候使用了进程启动时加载的表结构缓存，增删表结构之后，字段数量与类型无法对齐。通过数组下标获取缓存的表结构字段时候：在表结构中间添加字段时，表结构字段次序发生变更，可能会产生类型转换异常；在删除字段的时候，会产生数组越界异常。
The following is from Google Translation：
When Select * treats the return value, the surface structure cache loaded when the process starts. After the deletion and deletion of the table structure, the number of fields and types cannot be aligned.When the array is bidding, the table structure field is obtained: When adding fields in the middle of the table structure, the sequence of the surface structure field is changed, which may produce type conversion abnormalities; when deleting fields, array will cause cross -border abnormalities.

**Comment by terrymanu** [comment]
Can you show the details to reproduce it?

**Comment by wpinchine** [comment]
integrate with mybatis-spring-boot-starter:3.0.3,druid-spring-boot-3-starter:1.2.23,mysql8.0.X ,any table add columns to the table after first column on running will be error by select * ,or remove any one column from the table on running will be index out of bonud error by select * due to above

java code configuration:
` 
@Bean(name = "tempPreDatasource")
    @ConfigurationProperties(prefix = "spring.datasource.sharding")
    public DataSource tempPreDatasource() throws Exception {
        return DruidDataSourceBuilder.create().build();
    }

    @Bean(name = "shardingDataSource")
    public DataSource shardingDataSource(@Qualifier("tempPreDatasource") DataSource tempPreDatasource) throws Exception {
        Properties shardingRuleProperties = new Properties();
        shardingRuleProperties.put("algorithm-expression", "t_demo_key_$->{Math.abs(key.hashCode()) % 16}");
        AlgorithmConfiguration keyAlgo = new AlgorithmConfiguration("INLINE", shardingRuleProperties);
        ShardingRuleConfiguration sharingRuleConfig = new ShardingRuleConfiguration();
        sharingRuleConfig.getShardingAlgorithms().put("keyAlgo", keyAlgo);
        ShardingTableRuleConfiguration shardingTableRule = new ShardingTableRuleConfiguration("t_demo", "logic_db.t_demo_key_${0..15}");
        shardingTableRule.setTableShardingStrategy(new StandardShardingStrategyConfiguration("key", "keyAlgo"));
        sharingRuleConfig.getTables().add(shardingTableRule);
        Properties properties = new Properties();
        properties.put("sql-show", sqlShow);
        return ShardingSphereDataSourceFactory.createDataSource(tempPreDatasource,
                Lists.newArrayList(sharingRuleConfig),
                properties);
    }


    @Bean(name = "shardingSqlSessionFactory")
    public SqlSessionFactory shardingSqlSessionFactory(
            @Qualifier("shardingDataSource") DataSource shardingDataSource) throws Exception {
        SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
        bean.setDataSource(shardingDataSource);
        bean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath:mappers/sharding/*.xml"));
        bean.setTypeAliasesPackage("org.example.pojo");
        return bean.getObject();
    }
`

**Comment by wpinchine** [comment]
> Can you show the details to reproduce it?
> 
> 1. What is the DDL SQL?
> 2. What is the configuration?
> 3. What is the database type?

integrate with mybatis-spring-boot-starter:3.0.3,druid-spring-boot-3-starter:1.2.23,mysql8.0.X ,any table in sharding logic add columns to the table after first column on running will be error by select * ,or remove any one column from the table on running will be index out of bonud error by select * due to above

java code configuration:


```java
    @Bean(name = "tempPreDatasource")
    @ConfigurationProperties(prefix = "spring.datasource.sharding")
    public DataSource tempPreDatasource() throws Exception {
        return DruidDataSourceBuilder.create().build();
    }

    @Bean(name = "shardingDataSource")
    public DataSource shardingDataSource(@Qualifier("tempPreDatasource") DataSource tempPreDatasource) throws Exception {
        Properties shardingRuleProperties = new Properties();
        shardingRuleProperties.put("algorithm-expression", "t_demo_key_$->{Math.abs(key.hashCode()) % 16}");
        AlgorithmConfiguration keyAlgo = new AlgorithmConfiguration("INLINE", shardingRuleProperties);
        ShardingRuleConfiguration sharingRuleConfig = new ShardingRuleConfiguration();
        sharingRuleConfig.getShardingAlgorithms().put("keyAlgo", keyAlgo);
        ShardingTableRuleConfiguration shardingTableRule = new ShardingTableRuleConfiguration("t_demo", "logic_db.t_demo_key_${0..15}");
        shardingTableRule.setTableShardingStrategy(new StandardShardingStrategyConfiguration("key", "keyAlgo"));
        sharingRuleConfig.getTables().add(shardingTableRule);
        Properties properties = new Properties();
        properties.put("sql-show", sqlShow);
        return ShardingSphereDataSourceFactory.createDataSource(tempPreDatasource,
                Lists.newArrayList(sharingRuleConfig),
                properties);
    }


    @Bean(name = "shardingSqlSessionFactory")
    public SqlSessionFactory shardingSqlSessionFactory(
            @Qualifier("shardingDataSource") DataSource shardingDataSource) throws Exception {
        SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
        bean.setDataSource(shardingDataSource);
        bean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath:mappers/sharding/*.xml"));
        bean.setTypeAliasesPackage("org.example.pojo");
        return bean.getObject();
    }
```

**Comment by terrymanu** [comment]
The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.

**Comment by wpinchine** [comment]
> The issue involves other third-party dependencies, but our focus is solely on ShardingSphere itself. Since ShardingSphere implements the JDBC interface, standard applications should be functional. We wish to allocate more effort towards enhancing the current version, and therefore will no longer handle such issues. Please read the documentation or provide more effective information when submitting an issue.

I think this issue can not attributed to third-party dependencies, the select * query result is parsed by 
columnLabelAndIndexMap in ShardingSpherePreparedStatement ,and columnLabelAndIndexMap create use ProjectionsContext , and Projection is cached on server start. when table structure change , cached Projection list order can't correspond to database table column.

**Comment by terrymanu** [comment]
> > Can you show the details to reproduce it?
> > 
> > 1. What is the DDL SQL?
> > 2. What is the configuration?
> > 3. What is the database type?
> 
> integrate with mybatis-spring-boot-starter:3.0.3,druid-spring-boot-3-starter:1.2.23,mysql8.0.X ,any table in sharding logic add columns to the table after first column on running will be error by select * ,or remove any one column from the table on running will be index out of bonud error by select * due to above
> 
> java code configuration:
> 
> ```java
>     @Bean(name = "tempPreDatasource")
>     @ConfigurationProperties(prefix = "spring.datasource.sharding")
>     public DataSource tempPreDatasource() throws Exception {
>         return DruidDataSourceBuilder.create().build();
>     }
> 
>     @Bean(name = "shardingDataSource")
>     public DataSource shardingDataSource(@Qualifier("tempPreDatasource") DataSource tempPreDatasource) throws Exception {
>         Properties shardingRuleProperties = new Properties();
>         shardingRuleProperties.put("algorithm-expression", "t_demo_key_$->{Math.abs(key.hashCode()) % 16}");
>         AlgorithmConfiguration keyAlgo = new AlgorithmConfiguration("INLINE", shardingRuleProperties);
>         ShardingRuleConfiguration sharingRuleConfig = new ShardingRuleConfiguration();
>         sharingRuleConfig.getShardingAlgorithms().put("keyAlgo", keyAlgo);
>         ShardingTableRuleConfiguration shardingTableRule = new ShardingTableRuleConfiguration("t_demo", "logic_db.t_demo_key_${0..15}");
>         shardingTableRule.setTableShardingStrategy(new StandardShardingStrategyConfiguration("key", "keyAlgo"));
>         sharingRuleConfig.getTables().add(shardingTableRule);
>         Properties properties = new Properties();
>         properties.put("sql-show", sqlShow);
>         return ShardingSphereDataSourceFactory.createDataSource(tempPreDatasource,
>                 Lists.newArrayList(sharingRuleConfig),
>                 properties);
>     }
> 
> 
>     @Bean(name = "shardingSqlSessionFactory")
>     public SqlSessionFactory shardingSqlSessionFactory(
>             @Qualifier("shardingDataSource") DataSource shardingDataSource) throws Exception {
>         SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
>         bean.setDataSource(shardingDataSource);
>         bean.setMapperLocations(new PathMatchingResourcePatternResolver()
>                 .getResources("classpath:mappers/sharding/*.xml"));
>         bean.setTypeAliasesPackage("org.example.pojo");
>         return bean.getObject();
>     }
> ```

Can you use raw JDBC to describe and reproduce the issue?
