### ISSUE TITLE
How to import dependent jar packages as needed

### ISSUE THREAD

**Issue by penweizgx** [apache/shardingsphere#34008]
I am currently using shardingsphere-jdbc 5.5.1 + MySQL in my project. After importing Maven, many unnecessary jar packages are also imported. How can I minimize the import?

```
<dependency>
	<groupId>org.apache.shardingsphere</groupId>
	<artifactId>shardingsphere-jdbc</artifactId>
	<version>${shardingsphere.version}</version>
	<exclusions>
		<exclusion>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-test-util</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

<img width="617" alt="image" src="https://github.com/user-attachments/assets/3dc51920-6dd5-4b81-a792-81f836ae53f2">
<img width="622" alt="image" src="https://github.com/user-attachments/assets/0aa9b33e-d8bf-49f2-8a8b-3c4fda564c70">
<img width="672" alt="image" src="https://github.com/user-attachments/assets/b6874d32-4494-49cd-94bc-4b2c865f62ff">

**Comment by terrymanu** [comment]
Just like other regular projects, if you familiar the project, is there any special thing here?

**Comment by penweizgx** [comment]
There are too many jar packages. Are all these dependencies necessary?

**Comment by terrymanu** [comment]
You need to patiently handle them step by step.
