### ISSUE TITLE
[ShardingProxy 5.5.1] Unable to query existing table after registering a new storage unit

### ISSUE THREAD

**Issue by yuyongxing** [apache/shardingsphere#34002]
### **Title**  
`[ShardingProxy 5.5.1] Unable to query existing table after registering a new storage unit`

---

#### **ShardingSphere Version:**  
5.5.1  

#### **Problem Description:**  
When using ShardingProxy 5.5.1, after registering a new storage unit and attempting to query an existing table in the corresponding database, the following error occurs:  
[42S02][10002] Table or view 'a_table' does not exist.
However, the table `a_table` does exist in the `test` database.

#### **Steps to Reproduce:**  

1. Execute the following SQL statements:  
   ```sql
   create database `test` default charset utf8mb4 collate utf8mb4_general_ci;
   use test;
   REGISTER STORAGE UNIT test (
       URL="jdbc:mysql://xxxx:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true",
       USER="xxxx",
       PASSWORD="xxxx",
       PROPERTIES("maximumPoolSize"=10,"idleTimeout"=30000)
   );

However, the table `a_table` does exist in the `test` database.

2. Then execute the following query:
```sql
select * from a_table;
```
3. Error Message:

[42S02][10002] Table or view 'a_table' does not exist.

5. Expected Behavior:
The query should return data from the a_table table in the test database.

**Comment by terrymanu** [comment]
Have you been load single table?

**Comment by yuyongxing** [comment]
What do I need to do to load a single table

**Comment by yuyongxing** [comment]
I remember when using version 5.4.0, after registering the data source, the existing table data was automatically loaded

**Comment by yuyongxing** [comment]
run config file is  global.yaml 
```sql
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: zookeeper:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
#
authority:
  users:
    - user: test
      password: 123456
  privilege:
    type: ALL_PERMITTED

**Comment by yuyongxing** [comment]
The issue has been resolved through the following link：
```
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/single/
