### ISSUE TITLE
Questions about Logical Databases in ShardingProxy 5.5.1  

### ISSUE THREAD

**Issue by yuyongxing** [apache/shardingsphere#34017]
# Questions about Logical Databases in ShardingProxy 5.5.1  

Hello,  

Thank you for providing such an excellent open-source project! During my usage of ShardingProxy 5.5.1, I have encountered a few questions and would appreciate your assistance:

1. **Is it possible to create multiple logical databases?**  
   In real-world scenarios, we may need to create multiple logical databases for different business modules. Does ShardingProxy support this use case?

2. **Handling tables with the same name:**  
   If a logical database includes two data sources and both data sources contain tables with the same name, will there be any conflicts or issues when querying? How does ShardingProxy distinguish and handle these tables?

3. **Support for cross-database joins:**  
   If we need to perform cross-database join queries (e.g., JOIN operations) across different data sources within a logical database, does ShardingProxy support this? If supported, are there any additional configurations or considerations required?

Looking forward to your response. Thank you very much!  

Best regards

**Comment by terrymanu** [comment]
Hello, let me answer the questions.

1. Is it possible to create multiple logical databases?
Yes

2. Handling tables with the same name:
It depends on your rule configurations, sharding tables and broadcast tables can aggregate as same logic tables.

3. Support for cross-database joins:
Yes, it is federation query which is experimental function.
