### ISSUE TITLE
"insert into tab(f1,f2) values(?::int32,?::varchar)" doesn't work for encrypting

### ISSUE THREAD

**Issue by AlexNebula** [apache/shardingsphere#34020]
### Which version of ShardingSphere did you use?
5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Both of ShardingSphere-JDBC and ShardingSphere-Proxy

### Expected behavior
encrypting colums that already set encryptin rule. Shardingsphere works for "insert into tab(f1,f2) values(?,?)", but not for "insert into tab(f1,f2) values(?::int32,?::varchar)"

### Actual behavior
No encrypting algorithm involved, shardingsphere bypass the SQL to database

### Reason analyze (If you can)
shardingsphere doesn't support parsing of this kind of SQL

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
set encrypt rule for f1 or f2, send “insert into tab(f1,f2) values(?::int32,?::varchar)”

**Comment by terrymanu** [comment]
Is `?::int32,?::varchar` standard SQL parameters injection way?

**Comment by AlexNebula** [comment]
> Is `?::int32,?::varchar` standard SQL parameters injection way?

Yes, it is one of standard SQL instruction, although not often used. dataX uses it.

**Comment by terrymanu** [comment]
Can you provide the website link from any database official document to support your point?
