### ISSUE TITLE
when executing `ADD RESOURCE` command in ShardingProxy 5.5.1

### ISSUE THREAD

**Issue by yuyongxing** [apache/shardingsphere#34024]
# Error when executing `ADD RESOURCE` command in ShardingProxy 5.5.1

## Problem Description

After creating a logical database, I executed the following commands:

```sql
USE test;

ADD RESOURCE ds_0 (
    URL="jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false",
    USER=root,
    PASSWORD=root,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
);
```
However, I encountered the following error:
```sql
[42000][1064] You have an error in your SQL syntax: no viable alternative at input 'ADD' near '[@1,45:47='ADD',<88>,1:45]' at line 1

**Comment by terrymanu** [comment]
Where do you find the syntax?

**Comment by yuyongxing** [comment]
https://shardingsphere.apache.org/document/5.1.2/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/resource-definition/

**Comment by terrymanu** [comment]
Your version is 5.5.1, why do you see 5.1.2's document?

**Comment by yuyongxing** [comment]
I knowed
