### ISSUE TITLE
PaginationContext throws a ClassCastException when select with limit

### ISSUE THREAD

**Issue by strawberry1314** [apache/shardingsphere#34072]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
select success
### Actual behavior
because of ClassCastException,throws an NullPointerException when (CommandExecutorTask)commandExecutor.close()
### Reason analyze (If you can)
if the obj instanceof byte[],then class cast to int will throws exception
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/9024b955-8566-43e5-8fe0-1dbe8bc98c0a" />

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、The SQL statement is called using Go
![image](https://github.com/user-attachments/assets/d5daf4cf-cc5e-4a9a-bba3-26583fbd3134)
2、sql statement：
select id, content from test_table where version=? and create_time>? order by create_time desc limit ?, ?
### Proxy log
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/a6ffa2bf-ffb8-49c0-8fd3-bb4bafb332a6" />

**Comment by terrymanu** [comment]
SNAPSHOT version always changes, can you test a released version?

**Comment by strawberry1314** [comment]
Sorry，I used published 5.5.1 version，not SNAPSHOT version ，this problem still exists @terrymanu
