### ISSUE TITLE
MySQLComStmtPrepareExecutor throws an  IndexOutOfBoundsException when insert

### ISSUE THREAD

**Issue by strawberry1314** [apache/shardingsphere#34071]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
insert success
### Actual behavior
insert throw IndexOutOfBoundsException
### Reason analyze (If you can)
if the number of parameters in the inserted statement is greater than the number of fields to be inserted,List.get() will throw IndexOutOfBoundsException
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/92a82b4d-cb43-4dfb-8cc8-4f7da437bc5c" />

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、The SQL statement is called using Go
![image](https://github.com/user-attachments/assets/c590d1c3-4c07-41ad-857e-fb987143fc16)

2、sql statement：
insert into test_table (id, content, version, create_time) values (?, ?, ?, ?) ON DUPLICATE KEY UPDATE version = ?, update_time =?
### Proxy log
<img width="1618" alt="image" src="https://github.com/user-attachments/assets/f5f71011-7251-4add-ac46-725da10feef6" />

**Comment by terrymanu** [comment]
SNAPSHOT version always changes, can you test a released version?

**Comment by strawberry1314** [comment]
Sorry，I used published 5.5.1 version，not SNAPSHOT version ，this problem still exists

**Comment by strawberry1314** [comment]
Sorry，I used published 5.5.1 version，not SNAPSHOT version ，this problem still exists @terrymanu
