### ISSUE TITLE
Custom sharding only has one database

### ISSUE THREAD

**Issue by paulzhu8597** [apache/shardingsphere#34124]
ignore this  question

**Comment by terrymanu** [comment]
The markdown format in your issue is incorrect. To facilitate reading, could you please revise it?

**Comment by paulzhu8597** [comment]
![image](https://github.com/user-attachments/assets/30e6a4b2-7c8c-4b58-97f9-35cca470248d)

**Comment by wh-zxt-01** [comment]
ShardingSphereDataSourceFactory.createDataSource(databaseName, modeConfig, dataSourceMap, ruleConfigs, props);

private Map<String, DataSource> createDataSources() {
    Map<String, DataSource> dataSourceMap = new HashMap<>();
    // 配置第 1 个数据源
    HikariDataSource dataSource1 = new HikariDataSource();
    dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
    dataSource1.setJdbcUrl("jdbc:mysql://localhost:3306/ds_1");
    dataSource1.setUsername("root");
    dataSource1.setPassword("");
    dataSourceMap.put("ds_1", dataSource1);
    
    // 配置第 2 个数据源
    HikariDataSource dataSource2 = new HikariDataSource();
    dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
    dataSource2.setJdbcUrl("jdbc:mysql://localhost:3306/ds_2");
    dataSource2.setUsername("root");
    dataSource2.setPassword("");
    dataSourceMap.put("ds_2", dataSource2);
}

**Comment by paulzhu8597** [comment]
> You can take a look at this
> 
> ```
> ShardingSphereDataSourceFactory.createDataSource(databaseName, modeConfig, dataSourceMap, ruleConfigs, props);
> 
> private Map<String, DataSource> createDataSources() {
>     Map<String, DataSource> dataSourceMap = new HashMap<>();
>     // 配置第 1 个数据源
>     HikariDataSource dataSource1 = new HikariDataSource();
>     dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
>     dataSource1.setJdbcUrl("jdbc:mysql://localhost:3306/ds_1");
>     dataSource1.setUsername("root");
>     dataSource1.setPassword("");
>     dataSourceMap.put("ds_1", dataSource1);
>     
>     // 配置第 2 个数据源
>     HikariDataSource dataSource2 = new HikariDataSource();
>     dataSource2.setDriverClassName("com.mysql.jdbc.Driver");
>     dataSource2.setJdbcUrl("jdbc:mysql://localhost:3306/ds_2");
>     dataSource2.setUsername("root");
>     dataSource2.setPassword("");
>     dataSourceMap.put("ds_2", dataSource2);
> }
> ```
Creating  data source is normal

**Comment by paulzhu8597** [comment]
ignore  this question
