### ISSUE TITLE
Add lock timeout in DistSQL

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#34134]
Add lock timeout in DistSQL `LOCK CLUSTER WITH lockStrategy` and `UNLOCK CLUSTER`.

The new attribute `LOCK TIMEOUT` should be optional. The SQL should be:

`LOCK CLUSTER WITH lockStrategy (TIMEOUT int)?` and `UNLOCK CLUSTER (TIMEOUT int)?`.

The todolist should be:
1. Update G4 file
2. Update LockClusterExecutor and UnlockClusterExecutor with #34133's TODO
3. Update document
4. Add test cases

**Comment by lubochen** [comment]
Hi @terrymanu ，could you please assign this issue to me? Thank you.

**Comment by lubochen** [comment]
@terrymanu Hi,I'm  sorry. I've encountered some issues while working on this task. I'm not sure whether the timeout parameter should be added to the LOCK CLUSTER operation (TypedSPILoader.getService(ClusterLockStrategy.class, sqlStatement.getLockStrategy().getName()).lock();) or if the timeout in lockContext.tryLock(lockDefinition, 3000L) should be used as the parameter. Could you please clarify?

**Comment by terrymanu** [comment]
Great, welcome! @lubochen
