### ISSUE TITLE
Can not support DML operation with multiple tables

### ISSUE THREAD

**Issue by GuiwenChen** [apache/shardingsphere#34204]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
supported

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
When I run the following SQL:
`
UPDATE sync 
SET 
    is_deleted = 1
WHERE
    company_id = 2
        AND sync.id IN (SELECT 
            s.id
        FROM
            sync s
        WHERE
            s.is_deleted = 0 AND s.company_id = 2
                AND s.id != 2
                AND s.id NOT IN (SELECT 
                    synced_id
                FROM
                    device_info
                WHERE
                    company_id = 2)
                AND s.id NOT IN (SELECT 
                    synced_id
                FROM
                    company_info
                WHERE
                    company_id = 2)
        LIMIT 500)
`
I only updated one table, but the condition is to query the other tables. Why is this error reported?

**Comment by terrymanu** [comment]
The difficulty of supporting this feature in sharding is relatively high, and its necessity is not significant.
Therefore, there are currently no plans to support it.

**Comment by GuiwenChen** [comment]
Query other tables in the update operation is a very normal usage scenario, can you support it?
