### ISSUE TITLE
Are there any plans of supporting `isLast`

### ISSUE THREAD

**Issue by rimal** [apache/shardingsphere#3435]
## Question

Hello, I need to use `java.sql.ResultSet#isLast()` in my application. But am getting a `java.sql.SQLFeatureNotSupportedException: isLast` for this. On your [latest master](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-jdbc/sharding-jdbc-core/src/main/java/org/apache/shardingsphere/shardingjdbc/jdbc/unsupported/AbstractUnsupportedOperationResultSet.java#L57) as well, I could see that this function is still not supported. 

Are there any plans of supporting this function?

**Comment by terrymanu** [comment]
We can open this issue and let volunteer to consider about it.

**Comment by yanickxia** [comment]
i want try do it...

**Comment by terrymanu** [comment]
Great, assigned

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
