### ISSUE TITLE
plain column name failed to pasre to cipher column  in join clause

### ISSUE THREAD

**Issue by laoguanjie** [apache/shardingsphere#3571]
in my envrioment, plain column is 'value', cipher column is 'value_cipher', and 'sql.show' is set true in properties.

if sql is 

`
select user_id, value from user_mapping a where id = 100000100
`

it would be parsed to

`
select user_id, value_cipher from user_mapping a where id = 100000100
`

you can find 'value' is translated to 'value_cipher'.

but, 

if sql is 
`
select a.user_id, b.value value from user a join (select user_id, value from user_mapping a where id = 100000100) b on (a.user_id = b.user_id)
`

it would be parsed to 

`
select a.user_id, b.value value from iot_user a join (select user_id, value from user_mapping a where id = 100000100) b on (a.user_id = b.user_id)
`

'b.value' failed to be translated to 'b.value_cipher' !!

**Comment by terrymanu** [comment]
Can not support subquery now

**Comment by tristaZero** [comment]
Currently, the parsing for subquery is available, but we need more time to support `subquery` completely.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
