### ISSUE TITLE
Design for MySQL information_schema query

### ISSUE THREAD

**Issue by ssxlulu** [apache/shardingsphere#3572]
Query from information_schema is a common scene, some MySQL management client like Navicat will send such queries at the beginning of connection to ShardingSphere.

But ShardingSphere doesn't support information_schema query well for now.

For example, Navicat will send the following sql to SS:

`SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'sharding_db' UNION SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA
 = 'sharding_db' UNION SELECT COUNT(*) FROM information_schema.ROUTINES WHERE ROU
TINE_SCHEMA = 'sharding_db';`

But this sql will cause NPE exception for SS:

```
java.lang.NullPointerException: null
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:123)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionFromUnderlying(BackendConnection.java:198)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:181)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:150)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.callback.ProxyJDBCExecutePrepareCallback.getConnections(ProxyJDBCExecutePrepareCallback.java:56)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:89)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getSynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:67)
	at org.apache.shardingsphere.core.execute.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:59)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:80)
……
```

What's more, Navicat will not only send one sql, and not only Navicat but also other applications will query from information_schema, above is just an example.

**Comment by ssxlulu** [comment]
Here are my designs for the information_schema queries:
1. Fake the responses of queries about information_schema. We can intercept such sqls and fake the responses.
2. Use default datanode. Create the logic tables in the default datanode, and route these sqls to default datanode for querying.

**Comment by dongzl** [comment]
> @tristaZero Here are my designs for the information_schema queries:
> 
> **Design one:** Fake the responses of queries about information_schema. We can intercept such sqls and fake the responses.
> 
> **Design two:** Use default datanode. Create the logic tables in the default datanode, and route these sqls to default datanode for querying.
> For example, following is the logic table t_order structure:
> 
> ```
> t_order:
>           |____demo_ds_0:
>           |          |_____t_order_0
>           |          |_____t_order_1
>           |___demo_ds_1:
>                      |_____t_order_0
>                      |_____t_order_1
> ```
> 
> We can create empty table with the same name as t_order in the default datanode like demo_ds_0.t_order for information_schema query.Also, this table can be used for getting metadata.

I understand this design need user create a table `t_order`  only for query information_schema.

I don't think it is a good idea. User must maintain it's structure keep up with `t_order_0`.

Parse query sql and rewrite the sql is a good idea?

**Comment by ssxlulu** [comment]
@dongzl Hi, 
>  I understand this design need user create a table t_order only for query information_schema.
We can create the table automatically. 
> I don't think it is a good idea. User must maintain it's structure keep up with t_order_0.
The structure is same with each other.
>Parse query sql and rewrite the sql is a good idea?
Yes, it is a good idea, but I think it will be more complex to accomplish for some complex queries.

In conclusion, These designs are only in the discussion stage and more discussions are needed.

**Comment by dongzl** [comment]
yes, we need more discussions.

if we create the table automatically, if user change the source table's structure，how to make it synchronous?

**Comment by ssxlulu** [comment]
> yes, we need more discussions.
> 
> if we create the table automatically, if user change the source table's structure，how to make it synchronous?

Just also change the structure, I think.

**Comment by dongzl** [comment]
relation: #1176

**Comment by kimmking** [comment]
IMO, mock an our own infomation-schema & role-user layer out of datanode(physical mysql db) is a final solution here.

**Comment by cowcomic** [comment]
> IMO, mock an our own infomation-schema & role-user layer out of datanode(physical mysql db) is a final solution here.

I need it
metabase cannot work with wrong information-schema

**Comment by xbkaishui** [comment]
so navicat is not support now ? 
I also came up some error, below is the logs 

`[DEBUG] 20:05:25.073 [nioEventLoopGroup-3-3] o.a.s.d.protocol.codec.PacketCodec - Read from client e2b9bbea : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 9f 00 00 00 03 53 48 4f 57 20 56 41 52 49 41 42 |.....SHOW VARIAB|
|00000010| 4c 45 53 20 4c 49 4b 45 20 27 6c 6f 77 65 72 5f |LES LIKE 'lower_|
|00000020| 63 61 73 65 5f 25 27 3b 20 53 48 4f 57 20 56 41 |case_%'; SHOW VA|
|00000030| 52 49 41 42 4c 45 53 20 4c 49 4b 45 20 27 73 71 |RIABLES LIKE 'sq|
|00000040| 6c 5f 6d 6f 64 65 27 3b 20 53 45 4c 45 43 54 20 |l_mode'; SELECT |
|00000050| 43 4f 55 4e 54 28 2a 29 20 41 53 20 73 75 70 70 |COUNT(*) AS supp|
|00000060| 6f 72 74 5f 6e 64 62 20 46 52 4f 4d 20 69 6e 66 |ort_ndb FROM inf|
|00000070| 6f 72 6d 61 74 69 6f 6e 5f 73 63 68 65 6d 61 2e |ormation_schema.|
|00000080| 45 4e 47 49 4e 45 53 20 57 48 45 52 45 20 45 6e |ENGINES WHERE En|
|00000090| 67 69 6e 65 20 3d 20 27 6e 64 62 63 6c 75 73 74 |gine = 'ndbclust|
|000000a0| 65 72 27                                        |er'             |
+--------+-------------------------------------------------+----------------+
[DEBUG] 20:05:25.079 [ShardingSphere-Command-0] o.a.s.s.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=SHOW VARIABLES LIKE 'lower_case_%'; SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster')
[INFO ] 20:05:26.426 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: SHOW VARIABLES LIKE 'lower_case_%'; SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'
[INFO ] 20:05:26.426 [ShardingSphere-Command-0] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dal.dialect.mysql.ShowOtherStatement@19f232c4, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@18fbf1b2)
[INFO ] 20:05:26.427 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW VARIABLES LIKE 'lower_case_%'; SHOW VARIABLES LIKE 'sql_mode'; SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'
[DEBUG] 20:05:26.574 [nioEventLoopGroup-3-3] o.a.s.d.protocol.codec.PacketCodec - Write to client e2b9bbea : 
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| eb 00 00 01 ff 28 04 23 34 32 30 30 30 59 6f 75 |.....(.#42000You|
|00000010| 20 68 61 76 65 20 61 6e 20 65 72 72 6f 72 20 69 | have an error i|
|00000020| 6e 20 79 6f 75 72 20 53 51 4c 20 73 79 6e 74 61 |n your SQL synta|
|00000030| 78 3b 20 63 68 65 63 6b 20 74 68 65 20 6d 61 6e |x; check the man|
|00000040| 75 61 6c 20 74 68 61 74 20 63 6f 72 72 65 73 70 |ual that corresp|
|00000050| 6f 6e 64 73 20 74 6f 20 79 6f 75 72 20 4d 79 53 |onds to your MyS|
|00000060| 51 4c 20 73 65 72 76 65 72 20 76 65 72 73 69 6f |QL server versio|
|00000070| 6e 20 66 6f 72 20 74 68 65 20 72 69 67 68 74 20 |n for the right |
|00000080| 73 79 6e 74 61 78 20 74 6f 20 75 73 65 20 6e 65 |syntax to use ne|
|00000090| 61 72 20 27 53 48 4f 57 20 56 41 52 49 41 42 4c |ar 'SHOW VARIABL|
|000000a0| 45 53 20 4c 49 4b 45 20 27 73 71 6c 5f 6d 6f 64 |ES LIKE 'sql_mod|
|000000b0| 65 27 3b 20 53 45 4c 45 43 54 20 43 4f 55 4e 54 |e'; SELECT COUNT|
|000000c0| 28 2a 29 20 41 53 20 73 75 70 70 6f 72 74 5f 6e |(*) AS support_n|
|000000d0| 64 62 20 46 52 4f 4d 20 69 6e 66 6f 72 6d 61 74 |db FROM informat|
|000000e0| 69 6f 6e 5f 27 20 61 74 20 6c 69 6e 65 20 31    |ion_' at line 1 |
`

**Comment by sandynz** [comment]
It will be done in #11994, it's on progress now.
