### ISSUE TITLE
Suggestions about sql's statistics of ShardingProxy

### ISSUE THREAD

**Issue by ssxlulu** [apache/shardingsphere#3736]
In my opinion, I think here are some statistics about the sqls that users may pay attention when use ShardingProxy:
1. Detail execute time, like route time, execute time, users can know how long each step takes;
2. Slow sql, we may tell users which sqls are too slow, and need to optimize them;
3. Intercepted sql, if we have function of firewall to avoid some sqls to execute, we can audit such intercepted sql.

**Comment by terrymanu** [comment]
> 1. Detail execute time, like route time, execute time, users can know how long each step takes;

We can find them at sharding-opentracing module, ShardingSphere has already send those tracing information to OpenTracing protocol and user can show them on SkyWalking.

> 2. Slow sql, we may tell users which sqls are too slow, and need to optimize them;

I think those feature should be in druid or other connection pool, maybe ShardingSphere can add a new module for monitor sql status. We can discuss it further if you want to do it.

> 3. Intercepted sql, if we have function of firewall to avoid some sqls to execute, we can audit such intercepted sql.

This feature is for SQL audit, we create a new module do it just like encrypt or shadow table. We can discuss it further if you want to do it.

**Comment by terrymanu** [comment]
expired
