### ISSUE TITLE
Provide SPI interface for sharding adapter to user-defined function 

### ISSUE THREAD

**Issue by SteNicholas** [apache/shardingsphere#3799]
## Feature Request

In `RoutingEngine` sharding strategy, SQL including user-defined function doesn't support user-defined how to get sharding result. Therefore, it is necessary for user to provide SPI interface for sharding adapter to user-defined function.

### Is your feature request related to a problem?

Yes, related to #3749.

### Describe the feature you would like.

Define SPI interface for sharding adapter to user-defined function, and provide default implement of current functions.

**Comment by terrymanu** [comment]
Expired
