### ISSUE TITLE
SQLParseEngine support parse subquery statement

### ISSUE THREAD

**Issue by SteNicholas** [apache/shardingsphere#3841]
## Feature Request

Currently `SQLParseEngine` doesn't support parse subquery statement, but for many business scenario subquery is indeed significant. Therefore, it is necessary to support parse subquery statement based on Antlr4.

Please answer these questions before submitting your issue. Thanks!

No.

### Describe the feature you would like.

`SQLParseEngine` enable to support parse subquery statement based on Antlr4, and firstly implement on MySQL.

**Comment by phoema** [comment]
+1

**Comment by phoema** [comment]
Thank you for sharing

What the plan of this issue scheduled to be completed, fuzzy time?

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
