### ISSUE TITLE
Optimize model of  ColumnMetaData 

### ISSUE THREAD

**Issue by cherrylzhao** [apache/shardingsphere#3922]
currently our ColumnMetaData defined in this way
```
public class ColumnMetaData {
    
    private final String name;
    
    private final String dataType;
    
    private final boolean primaryKey;

    private final boolean notNull;

    private final boolean autoIncrement;
}
```

but `Sharding-Proxy` need entire meta to support database protocol, so we get others from underlying resultSetMetaData in this way
```
    columnLabel = resultSetMetaData.getColumnLabel(columnIndex);
    columnName = resultSetMetaData.getColumnName(columnIndex);
    columnLength = resultSetMetaData.getColumnDisplaySize(columnIndex);
    columnType = resultSetMetaData.getColumnType(columnIndex);
    decimals = resultSetMetaData.getScale(columnIndex);
    signed = resultSetMetaData.isSigned(columnIndex);
    notNull = resultSetMetaData.isNullable(columnIndex) == ResultSetMetaData.columnNoNulls;
    autoIncrement = resultSetMetaData.isAutoIncrement(columnIndex);
```

consider about  enhancing metadata like this
1. adding these missing meta field into `ColumnMetaData`, only maintain it in `TableMetaDataLoader` 
2. for `sharding-proxy` should provide a way to get logicTableName of ResultSetMetaData Column

**Comment by dongzl** [comment]
This has another question should be considered.

If only use `Master-Slave` mode, no sharding, ShardingSphere doesn't load table metadata, The `QueryHeader` how to get the metadata.

**Comment by SteNicholas** [comment]
@cherrylzhao In my opinion, `ColumnMetaData` should add these meta fields, because these meta fields are related to column metadata. And, about 'Master-Slave' mode, DDL operation should refresh the `ColumnMetaData`, which maybe store in Zookeeper.

**Comment by cherrylzhao** [comment]
agree with @SteNicholas metadata should be a infrastructure service for ShardingSphere, we should provide a uniform interface for initialization, read, refreshing instead of distinguish with whether sharding or not. it seems that it will be a big refactor for sharding-jdbc & sharding-proxy.
assume that task list is as below
- [ ] investigate the usage of current metadata, clarify the function list of metadata (SQLParse, Route,Rewrite etc)
- [ ] design a MetaData Model & MetaData Sevice, at first only consider about storing in memory
- [ ] then consider about migrating to zookeeper or other registration

@terrymanu is it ok for that

**Comment by dongzl** [comment]
If Database exists a lot of table, does put MetaData into Zookeeper is a good idea?

We can use Zookeeper as a listener, if one node change MetaData, the Zookeeper notice the other node to reload the MetaData, does this is a good idea?

**Comment by cherrylzhao** [comment]
I think we can discussing migrating to zookeeper in another issue, leverage the watcher of zookeeper is a better choice.

**Comment by SteNicholas** [comment]
> agree with @SteNicholas metadata should be a infrastructure service for ShardingSphere, we should provide a uniform interface for initialization, read, refreshing instead of distinguish with whether sharding or not. it seems that it will be a big refactor for sharding-jdbc & sharding-proxy.
> assume that task list is as below
> 
> * [ ]  investigate the usage of current metadata, clarify the function list of metadata (SQLParse, Route,Rewrite etc)
> * [ ]  design a MetaData Model & MetaData Sevice, at first only consider about storing in memory
> * [ ]  then consider about migrating to zookeeper or other registration
> 
> @terrymanu is it ok for that

@cherrylzhao Could u please send dev email group for discussion of this problem?

**Comment by cherrylzhao** [comment]
I have sent a mail to dev mailing list [
[DISCUSS] Optimize model of ColumnMetaData](https://lists.apache.org/thread.html/r17a6755569a787f34b917cd06a49895365d50c72f7c3ae6704044c76%40%3Cdev.shardingsphere.apache.org%3E)

**Comment by kimmking** [comment]
@dongzl @SteNicholas We already persist metadata to zk now.
And another question just like this first thread post by @cherrylzhao , add other fields to metadata center is neccesary or not?
