### ISSUE TITLE
XA transaction do not support oracle 

### ISSUE THREAD

**Issue by gxgmy521** [apache/shardingsphere#4297]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
In the documents, it said that the xa transction supports oracle datasource, can wrap the physical datasource connection to xa datasource connection . but i can not find the 
OracleXAConnectionWrapper
![image](https://user-images.githubusercontent.com/8359495/74495294-6c1bfa80-4f12-11ea-96ee-a1d95914f304.png)

### Actual behavior
here is the soucecode of the XAConnectionFactory class
```
 public static XAConnection createXAConnection(final DatabaseType databaseType, final XADataSource xaDataSource, final Connection connection) {
        switch (databaseType.getName()) {
            case "MySQL":
                return new MySQLXAConnectionWrapper().wrap(xaDataSource, connection);
            case "MariaDB":
                return new MariaDBXAConnectionWrapper().wrap(xaDataSource, connection);
            case "PostgreSQL":
                return new PostgreSQLXAConnectionWrapper().wrap(xaDataSource, connection);
            case "H2":
                return new H2XAConnectionWrapper().wrap(xaDataSource, connection);
            default:
                throw new UnsupportedOperationException(String.format("Cannot support database type: `%s`", databaseType));
        }
    }
```
it only support Mysql MariaDB PostgreSQL and H2,but no oracle, I have to use the AtomikosDataSourceBean ?

**Comment by cherrylzhao** [comment]
thanks for feedback, OracleXAConnectionWrapper should be add here, you can contribute a PR for it if possible.

**Comment by TaoZhiMLND** [comment]
I want have a try.
