### ISSUE TITLE
Different MySQLColumnDefinition41Packet values for parameters between MySQL Connector/J and MySQL C API

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#4358]
Parameter type of char in MySQLColumnDefinition41Packet handled differently between MySQL Connector/J and MySQL C API.
Connector/J accepts MYSQL_TYPE_VARCHAR, MYSQL_TYPE_VAR_STRING and MYSQL_TYPE_STRING.
While C API checks strictly and only accept MYSQL_TYPE_VAR_STRING and MYSQL_TYPE_STRING, because column type will be stored in struct MYSQL_STMT (fields.type) but MYSQL_TYPE_VARCHAR is not allowed to bind result.

For other filelds we follow MySQL Server's behavior:
```
- Database: ""
- Table: ""
- Original Table: ""
- Name: "?"
- Original Name: ""
- Length: 0
```

**Comment by terrymanu** [comment]
Close because of staled.
