### ISSUE TITLE
use of SPI to extend/modify statement executor (executeQuery)

### ISSUE THREAD

**Issue by ppourali** [apache/shardingsphere#4379]
Hi,

I was wondering if there is a good way to modify the implementation of the statement executor function (i.e., executeQuery function) like SPI. I can see that the encryption datasource and sharding datasource provide different implementations of the executeQuery function defined in EncryptStatment class and ShardingStatement class. So, should I provide SPI for each of these classes to modify their behavior?

Thanks,
Parsa

**Comment by terrymanu** [comment]
Thank you for provide the good idea. Actually, we have already to plan to a pluggable architecture, the discussion mail is https://lists.apache.org/thread.html/77afaffc7a9da81d2bb08a8f0bf6601530ecc751dbd732dc666c2eb6%40%3Cdev.shardingsphere.apache.org%3E

It maybe spend 2-3 month to finish it. The pluggable architecture use SPI to implement pluggable, it should include executor.

**Comment by ppourali** [comment]
Thanks for the reply, so, what do you suggest if we want to customize only one class in the sharding-proxy project? Let's say we want to extend/customize a small portion of ProxySQLExecuteCallback class.

Regards,
Parsa

**Comment by terrymanu** [comment]
Because they are still refactoring now, so I cannot guarantee how to use it now.
Maybe we can talk about this after 2 month.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
