### ISSUE TITLE
Completion of parse SET statement

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#4453]
We just parse SET statement simplify, it is not enough.

The SET statement is different with each database dialect.

Syntax of MySQL: 

```
SET variable = expr [, variable = expr] ...

variable: {
    user_var_name
  | param_name
  | local_var_name
  | {GLOBAL | @@GLOBAL.} system_var_name
  | {PERSIST | @@PERSIST.} system_var_name
  | {PERSIST_ONLY | @@PERSIST_ONLY.} system_var_name
  | [SESSION | @@SESSION. | @@] system_var_name
}
```

Syntax of PostgreSQL: 

```
SET [ SESSION | LOCAL ] configuration_parameter { TO | = } { value | 'value' | DEFAULT }
SET [ SESSION | LOCAL ] TIME ZONE { timezone | LOCAL | DEFAULT }
```

Even they are different totally, but we still can find the same abstraction of them.

The tasks of SET statement:

- [x] Parse variable name
- [ ] Parse variable value
- [ ] Parse scope
- [ ] Can support set multiple variables
- [ ] Consider about Oracle and SQLServer
- [ ] Consider about use sub-class to split different of SET dialect

**Comment by jingshanglu** [comment]
I'll support "Parse variable value" and "Can support set multiple variables"

**Comment by terrymanu** [comment]
@jingshanglu Great, I just assign issue to you.
Anybody inserting, I can continue  to assign them.

**Comment by beijing-penguin** [comment]
I want to do Parse variable value

**Comment by SteNicholas** [comment]
@terrymanu Please assign following two task to me:
- Consider about Oracle and SQLServer
- Consider about use sub-class to split different of SET dialect
