### ISSUE TITLE
Refer to DB doc to review the rule definition in each g4 file

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#4683]
Although the rule definitions for `MySQL`, `PostgreSQL`, `SQLServer`, `Oracle` and `SQL92` seem complete, it is also necessary to review those rule definitions to make true there are aligned to the definitions from different RDMS.

Note, the official documents of each RDMS are our guidelines.

**Comment by jingshanglu** [comment]
I'll support

**Comment by tristaZero** [comment]
Hello, community.
This issue needs more people to join and is a really important and long-term one.

### Who is wanted
If you understand `g4 file` of `ANTLR` and can look up the grammar definitions of anyone of `MySQL`, `PostgreSQL`, `SQLServer`, `Oracle` and `SQL92`, please be free to respond to this issue.

### What is the task of this issue
Compare grammar definitions between `ShardingSphere` and the official doc of each DB.

### Here are the sub-tasks you can claim
TODO

**Comment by strongduanmu** [comment]
Hello everyone, I want to participate in this task to check MySQL syntax. I am still a beginner in the field of ANTLR, I will try to keep up with everyone's rhythm.

**Comment by tristaZero** [comment]
@strongduanmu Welcome, please leave me some time to get you involved easily.

**Comment by strongduanmu** [comment]
> @strongduanmu Welcome, please leave me some time to get you involved easily.

@tristaZero Thanks a lot. 🙏👍👏

**Comment by tristaZero** [comment]
@strongduanmu Hi Would you mind my friend request on Wechat? If you like, an email with Wechat number is expected. Thx.

**Comment by strongduanmu** [comment]
> @strongduanmu Hi Would you mind my friend request on Wechat? If you like, an email with Wechat number is expected. Thx.

Hi, @tristaZero, my wechat number is s1069550670.

**Comment by jingshanglu** [comment]
@strongduanmu Hello, can you support check dal grammar of mysql? path: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql  ,mysql grammar official document address：https://dev.mysql.com/doc/refman/8.0/en/sql-server-administration-statements.html.

**Comment by strongduanmu** [comment]
> @strongduanmu Hello, can you support check dal grammar of mysql? path: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql ,mysql grammar official document address：https://dev.mysql.com/doc/refman/8.0/en/sql-server-administration-statements.html.

@jingshanglu Thank you for this assignment. I'll finish the job.

**Comment by jingshanglu** [comment]
> > @strongduanmu Hello, can you support check dal grammar of mysql? path: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql ,mysql grammar official document address：https://dev.mysql.com/doc/refman/8.0/en/sql-server-administration-statements.html.
> 
> @jingshanglu Thank you for this assignment. I'll finish the job.

Well,you can start from "Component, Plugin, and User-Defined Function Statements", the above is done.

**Comment by strongduanmu** [comment]
> > > @strongduanmu Hello, can you support check dal grammar of mysql? path: shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql ,mysql grammar official document address：https://dev.mysql.com/doc/refman/8.0/en/sql-server-administration-statements.html.
> > 
> > 
> > @jingshanglu Thank you for this assignment. I'll finish the job.
> 
> Well,you can start from "Component, Plugin, and User-Defined Function Statements", the above is done.

Thank you very much for reminding.

**Comment by jingshanglu** [comment]
Now, the g4 file of mysql has been reviewd. @tristaZero

**Comment by jingshanglu** [comment]
@strongduanmu Hello,are you interested in checking the dal of posgre.

**Comment by tristaZero** [comment]
Since other specific issues are threading the rule review work for different DBs, I closed this issue.
