### ISSUE TITLE
report error:Must have sharding column with subquery 

### ISSUE THREAD

**Issue by liweiboy** [apache/shardingsphere#4722]
The document say that: SQL 100% compatible if route to single data node.
sharding version: 4.0.0,database:mysql.
Original sql:
	select * from t_12_ws_wsdad_10049_s where id in (
		select a.id from t_12_ws_wsdad_10049_s a
		inner join t_12_ws_wsdad_10049_s b on a.title_proper = b.title_proper and b.is_delete =   0 AND b.STATUS IN ( 60, 80 )
		where 
		a.is_delete = 0 
		AND a.STATUS IN ( 60, 80 ) 
		AND a.fonds_code = 'mnxgb'
		and a.id != b.id
	)

**Comment by terrymanu** [comment]
What is your sharding rule?

**Comment by liweiboy** [comment]
![图片](https://user-images.githubusercontent.com/37232258/76506794-b4352b00-6486-11ea-86b0-b02993e23b72.png)
for example: table "t_user" is only one and in one database which is "db_0", so my actualDataNodes is "db_0.t_user".

**Comment by terrymanu** [comment]
I just set pending for subquery

**Comment by terrymanu** [comment]
ref #4696

**Comment by terrymanu** [comment]
The `5.0.0-beta` version supports federation engine which can process subquery, please try it, thank you.
