### ISSUE TITLE
 Optimize configuration structure of config&registry center 

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#4778]
For #4522
Based on the completed split of the config center and registry center, the related configuration structure will be adjusted as follows:

#### Current structure
```
/
├─orchestration-namespace
  ├─orchestration-name
  │  ├─config
  │  │  ├─authentication
  │  │  ├─props
  │  │  ├─schema
  │  │  │  ├─sharding-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
  │  │  │  ├─encrypt-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
  │  │  │  └─master_slave-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
  │  ├─state
  │  │  ├─datasources
  │  │  └─instances
```
##### config center
```
/
├─orchestration-namespace
  ├─orchestration-name
  │  ├─config
  │  │  ├─authentication
  │  │  ├─props
  │  │  ├─schema
  │  │  │  ├─sharding-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
  │  │  │  ├─encrypt-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
  │  │  │  └─master_slave-schema-name
  │  │  │  │  ├─datasource
  │  │  │  │  └─rule
```
##### registry center
```
/
├─orchestration-namespace
  ├─orchestration-name
  │  ├─registry
  │  │  ├─datasources
  │  │  └─instances
```
Note:

+ Split the registry and modify state node to registry node to match the registry
+ Modify the datasources node of registry center to states, currently used to record the status of slave database

Task lists:
 - [x] 1. Refactor persist and get configuration from registry center
 - [x] 2. Refactor unit tests
 - [x] 3. Refactor UI

Any suggestions， please reply directly to this issue.

**Comment by terrymanu** [comment]
It is better if change `states` to `status`

**Comment by terrymanu** [comment]
Add `rule` type maybe not good because the type can be extension by user via SPI. It is better do not add a static field here.

**Comment by menghaoranss** [comment]
> Add `type` maybe not good because the type can be extension by user via SPI. It is better do not add a static field here.

ok, I will reconsider the design of this part, thanks.

**Comment by menghaoranss** [comment]
> It is better if change `states` to `status`

@terrymanu I have changed the `state` node  to `registry` node,  I understand that `registry` node stores proxy and datasource runtime info(contains instance and status) which registered to the center . so , i consider whether it better to use `proxy`  instead of `instances`, just like:
```
/
├─orchestration-namespace
  ├─orchestration-name
  │  ├─registry
  │  │  ├─proxy
  │  │  └─datasources
``` 
Do you have any good suggestions about this?

**Comment by kimmking** [comment]
proxy -> proxies is better.
