### ISSUE TITLE
Does ShardingScaling still need to support the MySQL JSON and BIT data type?

### ISSUE THREAD

**Issue by KomachiSion** [apache/shardingsphere#4795]
When I handle #4594 , I found ShardingScaling support JSON data type. But I can't find any information about JSON type replication or binlog in [MySQL Internals Manual](https://dev.mysql.com/doc/internals/en/). I also search in [MariaDB document](https://mariadb.com/kb/en/clientserver-protocol/), but no information too.

There is only a [MySQL source code](https://github.com/mysql/mysql-server/blob/5.7/sql/json_binary.h) about JSON, but it seems be the decode and encode way between JSON and binary.

So should we still need to support the MySQL JSON data type in ShardingScaling?
Or Where we can get more reliable information about this data type?

**Comment by terrymanu** [comment]
Maybe low priority for json type

**Comment by KomachiSion** [comment]
Other type I find is similar to JSON type -- BIT. In mysql, BIT type can follow a length like `bit(n)` to set the storage way. And it will be different in binlog. But I do not find any description in mysql  and MariaDB document.

Currently, scaling will throw a log to warn users BIT type is unsupported.

**Comment by Lucas-307** [comment]
Currently, master version have been supported MySQL JSON and BIT data type, and I validate it. So this issue can be closed.
