### ISSUE TITLE
The diagram in English document contains Chinese characters.

### ISSUE THREAD

**Issue by minli04g** [apache/shardingsphere#4913]
## Bug Report

https://shardingsphere.apache.org/document/current/en/features/sharding/principle/rewrite/

![image](https://user-images.githubusercontent.com/18209024/77401605-2f340500-6de8-11ea-8887-336c4b1e44c0.png)

**Comment by minli04g** [comment]
https://shardingsphere.apache.org/document/current/en/manual/sharding-ui/usage/registry-center/

**Comment by tristaZero** [comment]
@minli04g Hi thanks for bringing them up. Would you like help ShardingSphere fix the second one?
It seems easy, but is the first step to join in community
@terrymanu The image needs updating as the first one said.

**Comment by tristaZero** [comment]
The doc was updated by #4934, and the remaining one is to update the image.

**Comment by xbkaishui** [comment]
let me try
