### ISSUE TITLE
Extended DDL for create table to simply the configuration

### ISSUE THREAD

**Issue by ssxlulu** [apache/shardingsphere#5044]
For now, the community has proposed the configuration is too complex #5030, and we have plan to optimize it #5017 .

After the optimization, we may further provide extended DDL for creata table syntax, which will auto generate configuration for the user.

The extended DDL may look like:
```
CREATE TABLE table_name (
     id int, 
     name varchar(20)
) DBPARTITION BY hash(id) DBPARTITIONS 2 TBPARTITION BY hash(name) TBPARTITIONS 2;
```
Such DDL will create a table with sharding rule for user.

**Comment by tristaZero** [comment]
> we have plan to optimize it #5017 .

Sorry, it means you want to do some contributions to this community?

**Comment by ssxlulu** [comment]
@tristaZero My privilege :)

**Comment by tristaZero** [comment]
@ssxlulu Welcome your joining!
Since it seems not an easy one, could you give more details about your idea? Like proposal, todo list, or schedule... Therefore we can basically know whether it can work well and receive more feedback from the community.

**Comment by tristaZero** [comment]
Thanks for [this reference](https://help.aliyun.com/document_detail/71300.html?spm=a2c4g.11186623.6.671.6f624af8unTHTg). As you said, after configuration optimization, this issue is likely to move into the discussion.

**Comment by Lucas-307** [comment]
Do it after api has been reconstructed, mark as pending now.

**Comment by kimmking** [comment]
RDL has been implemented.
