### ISSUE TITLE
Load unconfigured schema meta data concurrently

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#5073]
Use multiple thread to load unconfigured schema meta data for different data sources to improve performance of loading.

The code is in `RuleSchemaMetaDataLoader` line 80, please search `// TODO use multiple threads for different data sources`

**Comment by zjcnb** [comment]
Hi, i want to do it

**Comment by strongduanmu** [comment]
I want to solve this issue too!

**Comment by kimmking** [comment]
@zjcnb @strongduanmu  you can discuss about it here.

**Comment by strongduanmu** [comment]
> @zjcnb @strongduanmu you can discuss about it here.

@kimmking @zjcnb First come first served, next time I will claim issue earlier. 😂 I'm so sorry for everyone!

**Comment by terrymanu** [comment]
@zjcnb @strongduanmu It seems you have good negotiation.
I just assign this issue to you, thank you. @zjcnb

**Comment by zjcnb** [comment]
> @zjcnb @strongduanmu It seems you have good negotiation.
> I just assign this issue to you, thank you. @zjcnb

thx

**Comment by zjcnb** [comment]
> @zjcnb @strongduanmu you can discuss about it here.

i got it😁
