### ISSUE TITLE
How to start spring boot  shardingsphere with settings in a separate file config-sharding.yml?  

### ISSUE THREAD

**Issue by Leinariys** [apache/shardingsphere#5079]
Hello to all!
How to configure sharding for spring boot so that the settings are in a separate file (config-sharding.yml), since I need to specify 30+ databases?
I don’t want the settings to be in code.

Now I have a working code "[Rule Configuration Based on Java](https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/sharding/#rule-configuration-based-on-java)"

But he does not suit me.
I consider it is necessary to make Bean setup from ShardingDataSource  "[Use Native JDBC](https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/usage/sharding/#use-native-jdbc)"

But I get an error reading the settings file.  [LOG](https://pastebin.com/RMMfBZnt)

Please, help!!!

dependencies {
    compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.19'

    compile "org.springframework.boot:spring-boot-starter-jdbc:$springBootVersion"

    compile group: 'org.apache.shardingsphere', name: 'sharding-jdbc-core', version: '4.0.1'
}

[DbService](https://pastebin.com/DsdLpkeg)
[config-sharding.yml](https://pastebin.com/YnPTB0XQ)
[TestShard](https://pastebin.com/cafJEkLM)

**Comment by terrymanu** [comment]
Could you change the title for search friendly?

**Comment by kimmking** [comment]
sharding-jdbc hasn't ‘schemaName’ property, just remove it.

**Comment by Leinariys** [comment]
> sharding-jdbc hasn't ‘schemaName’ property, just remove it.

good, but it doesn’t help start with yml settings ((

**Comment by Leinariys** [comment]
> Could you change the title for search friendly?

Good name?
Any ideas how to start? and what should be the scheme?

**Comment by kimmking** [comment]
It's a spring boot config issue, not sharding issue.
And my suggestion is:
1. spilt your config whatever yml or properties to multi files with different profiles(such as p1/p2/p3/p4), you can search spring boot profiles.
2. set multi profiles active as the following.
> --spring.profiles.active=p1,p2,p3,p4

**Comment by Leinariys** [comment]
> It's a spring boot config issue, not sharding issue.
> And my suggestion is:
> 
> 1. spilt your config whatever yml or properties to multi files with different profiles(such as p1/p2/p3/p4), you can search spring boot profiles.
> 2. set multi profiles active as the following.
> 
> > --spring.profiles.active=p1,p2,p3,p4

Hi, it’s not clear where the profiles are here, I’m not a springing configuration, but YamlShardingDataSourceFactory.createDataSource(file), which allows you to turn the settings file into a data source.
Please help by showing an example with code

**Comment by kimmking** [comment]
It's always clear here.
You want to use a config-sharding.yml with spring-boot.

The anwser in a simpe way:
1. use application.yml
2. others like the above
3. xxx-sharding.yml may be modified a little for spring boot

**Comment by kimmking** [comment]
@Leinariys BTW, if you want use an original sharding.yaml just like sharding-proxy bootstrap config, you should:
1. remove sharding-jdbc-spring-boot-starter(it only recognize spring boot parameters)
2. add a config class implement spring boot config, or create an annotation bean, to invoke YamlShardingDataSourceFactory.createDataSource(file)

**Comment by Leinariys** [comment]
> @Leinariys BTW, if you want use an original sharding.yaml just like sharding-proxy bootstrap config, you should:
> 
> 1. remove sharding-jdbc-spring-boot-starter(it only recognize spring boot parameters)
> 2. add a config class implement spring boot config, or create an annotation bean, to invoke YamlShardingDataSourceFactory.createDataSource(file)

Ok, https://yadi.sk/i/e_TBWlQnUN6kvA 
as I understand it is not determined by DataSource - > MysqlDataSource 
please, help

**Comment by kimmking** [comment]
what's the MysqlDataSource?
DataSource is a standard jdbc interface, you can use it directly.
