### ISSUE TITLE
Simplify the `SelectStatement`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5135]
- [ ] Move `getSimpleTableSegments()` from `SelectStatement` to `SelectStatementContext`
- [ ] Consider the same operation for `TableReferenceSegment`, `JoinedTableSegment`, `JoinSpecificationSegment` and `TableFactorSegment`.

**Comment by tristaZero** [comment]
Could you consider this ISSUS? @jingshanglu

**Comment by jingshanglu** [comment]
> Could you consider this ISSUS? @jingshanglu

I'll support it.

**Comment by jingshanglu** [comment]
Some other modules directly call getSimpleTableSegment () of selectStatement, which cannot be directly moved to selectStatementContext. @tristaZero
