### ISSUE TITLE
Optimizate code about sharding-orchestration-center-etcd module.

### ISSUE THREAD

**Issue by dongzl** [apache/shardingsphere#5159]
I find some code about `sharding-orchestration-center-etcd` can be optimizated.

- [x] `jetcd.version` in this module's pom.xml can be moved to project root pom.xml.
- [x] upgrade `jetcd.version` to newest version.
- [x] In `EtcdCenterRepository` file, `config` is a global variable, but it is not used except the `init` method, I think we can define a local variable at `init` method.

**Comment by kimmking** [comment]
Awesome.

Accept 2/3/4.
The no.2: Guava version here is greater than root for jetcd. Removing is unneccessary.

**Comment by dongzl** [comment]
> unneccessary

Hi @kimmking , OK, I will fix this issue and test it to work well.
