### ISSUE TITLE
Simplify the configuration  API of ShardingKeyGenerator on spring namespace

### ISSUE THREAD

**Issue by TaoZhiMLND** [apache/shardingsphere#5168]
Hi community,

ShardingKeyGenerator configuration on spring namespace  is like this now,
```
<bean id="incrementAlgorithm" class="org.apache.shardingsphere.shardingjdbc.spring.namespace.factorybean.KeyGenerateAlgorithmFactoryBean">   
   <property name="type" value="INCREMENT" />   
</bean>   

<sharding:key-generator id="orderKeyGenerator" column="order_id" algorithm-ref="incrementAlgorithm" />
```
The following configuration will hide KeyGenerateAlgorithmFactoryBean may be more simplified,
```
<sharding:key-generate-algorithm id="incrementAlgorithm" type="INCREMENT"/>

<sharding:key-generator id="orderKeyGenerator" column="order_id" algorithm-ref="incrementAlgorithm" />
```
But element `<sharding:key-generate-algorithm>` has some strange for keyGenerateAlgorithm itself has nothing to do with Sharding. Besides, the elements `<key-generate-algorithm>` and `<key-generator>` has a duplicate word.

Do we need to make any changes to simplify this configuration? I will really appreciate any help on this. Thanks.

**Comment by kimmking** [comment]
IMO, if we need share a singleton bean, the first config style is simple enough:
```
<bean id="incrementAlgorithm" class="org.apache.shardingsphere.shardingjdbc.spring.namespace.factorybean.KeyGenerateAlgorithmFactoryBean">   
   <property name="type" value="INCREMENT" />   
</bean>   

<sharding:key-generator id="orderKeyGenerator" column="order_id" algorithm-ref="incrementAlgorithm" />
```

And if no need to share it, the simplest config style is:
``` 
<sharding:key-generator id="orderKeyGenerator" column="order_id"  type="INCREMENT" />
```

**Comment by tristaZero** [comment]
Hi I prefer the second one @kimmking mentioned, i.e,
> <sharding:key-generator id="orderKeyGenerator" column="order_id"  type="INCREMENT" />

Firstly, IMO, it is better to hide `org.apache.shardingsphere.shardingjdbc.spring.namespace.factorybean.KeyGenerateAlgorithmFactoryBean` which id internal class of ShardingSphere from user.
Secondly, like the picture below shows, the beans of `ShardingAlgorithm` and `KeyGenerateAlgorithm` have a similar format but with a different meaning, which is likely to confuse the user.

![image](https://user-images.githubusercontent.com/27757146/79177433-5f922080-7e35-11ea-99f5-dd4d42d63c35.png)

**Comment by cherrylzhao** [comment]
in fact, `<sharding:key-generator id="orderKeyGenerator" column="order_id" type="INCREMENT" />` is the old api before #1997, in this way keyGenerator was instanced by ServiceLoader which could been managed by spring-container. TaoZhiMLND and I have made many work in order to keep the old api but it is not possible to create 2 different beans in one spring tag, so we separate the KeyGeneratorAlgorithm from the <sharding:key-generator> using FactoryBean to wrap the serviceLoader as a spring bean

**Comment by cherrylzhao** [comment]
@TaoZhiMLND would you please investigate whether the FactoryBean api could simplify to this:

<spi:bean id="incrementAlgorithm" type="INCREMENT"/>
<sharding:key-generator id="orderKeyGenerator" column="order_id" algorithm-ref="incrementAlgorithm" />

**Comment by TaoZhiMLND** [comment]
> @TaoZhiMLND would you please investigate whether the FactoryBean api could simplify to this:
> 
> <spi:bean id="incrementAlgorithm" type="INCREMENT"/>
> <sharding:key-generator id="orderKeyGenerator" column="order_id" algorithm-ref="incrementAlgorithm" />

Thanks for all lot you, and I will do it soon!

**Comment by TaoZhiMLND** [comment]
It works well by leveraging a BeanDefinitionParser,
![image](https://user-images.githubusercontent.com/9602831/79213333-968b2500-7e7b-11ea-95e3-a99a43f4f66c.png)

and I will commit a pr soon.

**Comment by cherrylzhao** [comment]
the final api have changed to `<spi:key-generate-algorithm id="incrementAlgorithm" type="INCREMENT" props-ref="xxx"/>`, please don't forget revise the example and docs later

**Comment by cherrylzhao** [comment]
hi, @TaoZhiMLND please add a spi.xsd file in our [doc-repository](https://github.com/apache/shardingsphere-doc/tree/asf-site/schema/shardingsphere)

**Comment by TaoZhiMLND** [comment]
> hi, @TaoZhiMLND please add a spi.xsd file in our [doc-repository](https://github.com/apache/shardingsphere-doc/tree/asf-site/schema/shardingsphere)

done.

**Comment by TaoZhiMLND** [comment]
for everything is done, I will close this issue.
