### ISSUE TITLE
Provide SPI spring namespace configuration for all the Sharding algorithms

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5196]
Hi 
**Content:** This issue is to provide SPI spring namespace configuration for Sharding algorithms. 
**Difficulty rating:** ★★☆☆☆

**Comment by tristaZero** [comment]
### Background
All the sharding algorithms are loading by SPI currently, which you can refer to #5017 to learn more. Now, we need to provide SPI spring namespace configuration for all the sharding algorithms.

### What is wanted
Use the following configuration format
> <spi:sharding-algorithm id="standardModuloDatabaseShardingAlgorithm" type="STANDARD_TEST_DB" />

instead of
> <bean id="standardModuloDatabaseShardingAlgorithm" class="org.apache.shardingsphere.shardingjdbc.spring.algorithm.StandardModuloDatabaseShardingAlgorithm" />

### How
1.Refer to #5190 to learn how to use `beanFactory` to call `TypedSPIRegistry`
2.Provide `spi:sharding-algorithm` for users to configure.
3.Modify all the bean configurations of `shardingAlgorithm`.

**Comment by tristaZero** [comment]
@TaoZhiMLND Hi would like to tackle this one?

**Comment by strongduanmu** [comment]
I want to solve this issue. Can you assign it to me?

**Comment by tristaZero** [comment]
@strongduanmu Sure, guy. :)
Since @TaoZhiMLND  finished #5190 , it is easy for him. If you want to have a try, I will assign to you.

**Comment by tristaZero** [comment]
Actually, this issue is not much hard, since  #5190 gave a good example. 😃 
Besides, you can learn those branch new configuration APIs more, which I believe will simplify the tedious configuring work from our users. :-)

**Comment by strongduanmu** [comment]
> @strongduanmu Sure, guy. :)
> Since @TaoZhiMLND finished #5190 , it is easy for him. If you want to have a try, I will assign to you.

I want to try, please assign to me, thank you! 😀
Before starting work, I will first learn the contents of pr # 5190.

**Comment by tristaZero** [comment]
@strongduanmu Enjoy and learn more from it.😉

**Comment by tristaZero** [comment]
Sorry @TaoZhiMLND , but thanks for your contribution of #5190 . :-)
 Hope see your more interaction with this community.

**Comment by TaoZhiMLND** [comment]
> Sorry @TaoZhiMLND , but thanks for your contribution of #5190 . :-)
> Hope see your more interaction with this community.

It doesn't matter,  I will continue to focus on the community.   I believe @strongduanmu  will do a great job, and any question is welcome.

**Comment by strongduanmu** [comment]
> > Sorry @TaoZhiMLND , but thanks for your contribution of #5190 . :-)
> > Hope see your more interaction with this community.
> 
> It doesn't matter, I will continue to focus on the community. I believe @strongduanmu will do a great job, and any question is welcome.

@TaoZhiMLND Thank you very much, I will try my best to do it well. 🙏😊
