### ISSUE TITLE
Use new Inline algorithm for configurations of annotated tests

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5200]
Hi community, it is a good first issue. Welcome your attention. 😀 
Content: Modify YAML configurations with the new Inline algorithm
Difficulty rating: ★☆☆☆☆

**Comment by tristaZero** [comment]
### Backgroup
We are working on designing [new configuration API](#5017 ). As the inline sharding strategy has become one implement of the standard sharding strategy, we need to update all the YAML configuration with a new configuring format.

### How to do
1. Open project and full-text search with key work `inline:` in all of the `YAML` files.
2. Refer to #5199 to update those stale configuration
3. Comment those configurations out, for they will be tested in the future.

**Comment by JasonKing168** [comment]
Hi, could I have a try to fix this issue?

**Comment by tristaZero** [comment]
Good morning @JasonKing168 .
Thanks for your assistance to refactor the new API of ShardingSphere. 😀
