### ISSUE TITLE
Tackle with JDBC URL containing Multi-hosts

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5220]
MySQL Connector/J supports server failover and load balance by using a multi-hosts JDBC URL.
At present, users can not practice this MySQL feature since ShardingSphere can not analyze a multi-hosts JDBC URL.

However, a piece of good news is that we will provide this enhancement **in our incoming 4.1.0 release!**

Please follow this ISSUE to learn how it moves.

**Comment by tristaZero** [comment]
#### References
[1] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-config-failover.html
[2] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html
[3] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-multi-host-connections.html

**Comment by kimmking** [comment]
```
## failover url 
jdbc:mysql://[primary host][:port],[secondary host 1][:port][,[secondary host 2][:port]]...[/[database]]»
[?propertyName1=propertyValue1[&propertyName2=propertyValue2]...]

```

**Comment by cherrylzhao** [comment]
currently  hostname and port only referenced by scalling and open-tracing, just extract primary host and port using regex to compatible with it
