### ISSUE TITLE
sharding-jdbc-spring-boot-starter inject datasource through bean

### ISSUE THREAD

**Issue by yakamy** [apache/shardingsphere#5230]
when i use spring-boot-starter to config my sharding configuration, i found a trouble:
the datasource configuration is only can config from the yml, 

i want to config datasource through spring bean, and config sharding strategy through yml because our datasource config is encrypted that can't be config through the yml.

i read the source code found that the sharding config get datasource only from yml or jndi.

i suggest enhance the datasource config that user can defined through spring java bean,
add a way to inject user defined datasource in the following class.
`org.apache.shardingsphere.shardingjdbc.spring.boot.SpringBootConfiguration`

**Comment by kimmking** [comment]
sharding-jdbc-spring-boot-starter use spring boot style configurations.
if you want use sharding-jdbc yaml style to config rules, you should remove sharding-jdbc-spring-boot-starter, and launch config yaml file from a java config way.
