### ISSUE TITLE
Update the configuration of `inline` sharding algorithm for Sharding SpringNameSpace

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5234]
Hi everyone, thanks for your attention.  😉 

Content: Update the configuration of `inline` sharding algorithm for Sharding SpringNameSpace
Difficulty rating: ★☆☆☆☆

**Comment by tristaZero** [comment]
**Background**
 [New configuration API](#5017 ) is underway. As the inline sharding strategy has become one implement of the standard sharding strategy, it is necessary to modify the configuration of `inline` sharding algorithm for Sharding SpringNameSpace.

**How to do**
1. Open the project and full-text search with keyword `<sharding:inline-strategy` in all of the `xml` files.
2. Refer to #5233 to update those stale configuration.
3. Run those related string namespace `unit tests `.
4. Update the assertion to make `unit tests ` work well.

**Comment by tristaZero** [comment]
Hi This issue is open to the community to pick up. If anyone wants to try, please comment on this ISSUE and I will assign it to you. :)

**Comment by strongduanmu** [comment]
Hi, @tristaZero I want to solve this issue!

**Comment by tristaZero** [comment]
@strongduanmu This issue is the next step of your last one, welcome. :)
