### ISSUE TITLE
Any sharding rule demo for 5.0.0?

### ISSUE THREAD

**Issue by nevereverever** [apache/shardingsphere#5235]
I'm trying to use the new version, but the structural change is bigger than 4.0.1. I want to ask if there are any documents or examples？

**Comment by kimmking** [comment]
Rules structure in master is refactoring now.

**Comment by kimmking** [comment]
@nevereverever thanks for your attentions.
We will revise documents&examples after refactoring completely and 5.0.0 version is stable.
