### ISSUE TITLE
The Chinese document has a wrong word

### ISSUE THREAD

**Issue by mlw12345678** [apache/shardingsphere#5245]
https://shardingsphere.apache.org/document/legacy/3.x/document/cn/features/sharding/principle/execute/

![image](https://user-images.githubusercontent.com/40895047/79824971-460b4e80-83ca-11ea-859f-bac5c02ed129.png)

**Comment by mlw12345678** [comment]
I'm on fixing it.

**Comment by terrymanu** [comment]
Thank you， merged
