### ISSUE TITLE
sharding-data 4.0.1 & spring boot &mybaties  can not get datasource

### ISSUE THREAD

**Issue by taomingyaojing** [apache/shardingsphere#5271]
pom like this :
![image](https://user-images.githubusercontent.com/7371206/80051590-251e3700-854b-11ea-9b5c-411077a7f8ef.png)
druid 1.1.19
sharding-data 4.0.0.1 
get like error:
![image](https://user-images.githubusercontent.com/7371206/80051762-8f36dc00-854b-11ea-9623-971d674a150b.png)

**Comment by taomingyaojing** [comment]
I ’m not familiar with this one, so please ask the teachers to help?

**Comment by kimmking** [comment]
Learn from:https://github.com/apache/shardingsphere/tree/master/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example

**Comment by taomingyaojing** [comment]
ok  thinks,i will check.
