### ISSUE TITLE
[NEW API] 1-Update Sharding SpringBoot configuration with new API

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5287]
Hi everyone. Welcome your joining! 😉

Content: Update the configuration of the sharding algorithm for Sharding SpringBoot with the new API.

Difficulty rating: ★☆☆☆☆

Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. **Just follow the comment below to create your PR.** 😀

**Comment by tristaZero** [comment]
### How

#### orchestration-example
1. Refer to #5260 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/orchestration-example/orchestration-spring-boot-example/src/main/resources`.
```
application-local-nacos-sharding-databases-tables.properties
application-local-zookeeper-sharding-databases-tables.properties
```
2. Run `ExampleMain` to test your update.

### sharding-example
#### sharding-spring-boot-jpa-example
1.  Refer to #5260 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources`.
```
application-sharding-databases.properties
application-sharding-databases-tables.properties
application-sharding-tables.properties
```
3. Run `ExampleMain` to test your update.

#### sharding-spring-boot-mybatis-example
1.  Refer to #5260 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources`.
```
application-sharding-databases.properties
application-sharding-databases-tables.properties
application-sharding-tables.properties
```
3. Run `ExampleMain` to test your update.

**Comment by kekerzzZ** [comment]
I can do it.

**Comment by kekerzzZ** [comment]
5287

**Comment by tristaZero** [comment]
@kekerzzZ This is the first time to see you here, welcome. 😀
