### ISSUE TITLE
 [NEW API] 2-Update Sharding SpringBoot configuration with new API

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5288]
Hi everyone. Welcome your joining! 😉

Content: Update the configuration of the sharding algorithm for Sharding SpringBoot with the new API.

Difficulty rating: ★☆☆☆☆

Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. **Just follow the comment below to create your PR.** 😀

**Comment by tristaZero** [comment]
## How

### transaction-example
#### transaction-2pc-xa-spring-boot-example
1. Refer to #5260 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/transaction-example/transaction-2pc-xa-spring-boot-example/src/main/resources`.

> application-sharding-databases.properties
application-sharding-databases-tables.properties
application-sharding-tables.properties

2. Run `XAOrderServiceTest` to test your update.
-------
#### transaction-base-seata-spring-boot-example
1. Refer to #5260 to update the sharding configuration for the following properties in `/Users/trista/Documents/sharding-code-trista/incubator-shardingsphere/examples/sharding-jdbc-example/transaction-example/transaction-base-seata-spring-boot-example/src/main/resources`
> application-sharding-databases.properties
application-sharding-databases-tables.properties
application-sharding-tables.properties

2. Run `SeataATOrderServiceTest` to  test your update.

**Comment by DreamcatcherGo** [comment]
May I?

**Comment by wangzhengxi** [comment]
I want

**Comment by tristaZero** [comment]
@wangzhengxi, Hi It will be a great start for your open-source journey. 😉

**Comment by tristaZero** [comment]
@DreamcatcherGo Hi 
We are glad to see your hand up.
Since @wangzhengxi ping me earlier, I assign this one to him. But do not worry, a new one will be created for you, especially. Please wait for my news.  :)

**Comment by DreamcatcherGo** [comment]
@tristaZero Ok

**Comment by tristaZero** [comment]
@wangzhengxi 
Hi I do not see any progress of this issue, if you need any help, please tell us. :)

**Comment by wangzhengxi** [comment]
i am so sorry ,i forget this issue .i will finish it on this week(before 5.9)

**Comment by tristaZero** [comment]
@wangzhengxi That is not a big deal. Everyone is busy every day. Any questions, you can contact me. :)

**Comment by hitnewbee** [comment]
@wangzhengxi Are you keep working on this?If not plz let me know,I will work on this issue, thanks

**Comment by tristaZero** [comment]
> @wangzhengxi Are you keep working on this?If not plz let me know, I will work on this issue, thanks

@wangzhengxi Hi It is also my concern, could you give us an update here？

**Comment by wangzhengxi** [comment]
i will working on this . some time ago ，there's something wrong with me . so sorry @tristaZero @hitnewbee 

i will finish it these two days.

**Comment by wangzhengxi** [comment]
i am sorry .
Recently, I have been busy, and have no time to deal with the issues。
can you  deal with this issue？ thanks @hitnewbee

**Comment by tristaZero** [comment]
> i am sorry .
> Recently, I have been busy, and have no time to deal with the issues。
> can you deal with this issue？ thanks @hitnewbee

Hi @hitnewbee, are you still interested in this one? Looking forward to your response. :)

**Comment by hitnewbee** [comment]
Alright, but I am busy with somthing else in recent two week. After that, if no one interested in this, I'll finish it. @tristaZero

**Comment by tristaZero** [comment]
> Alright, but I am busy with somthing else in recent two week. After that, if no one interested in this, I'll finish it. @tristaZero

Hi @hitnewbee Thanks for your feedback. No problem and welcome you anytime! :-)

**Comment by jacksparrow414** [comment]
@tristaZero Hi,I've already done it.could you help me code review？:smiley:

**Comment by tristaZero** [comment]
@jacksparrow414 Hi I am glad to see your PR merged. Good job! :-)
Look forward to your more involvement in OS community!
