### ISSUE TITLE
[NEW API]  1-Update Sharding SpringNameSpace configuration with new API

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5289]
Hi everyone. Welcome your joining! 😉

Content: Update the configuration of the sharding algorithm for Sharding SpringNameSpace with the new API.

Difficulty rating: ★☆☆☆☆

Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. **Just follow the comment below to create your PR.** 😀

**Comment by tristaZero** [comment]
## How

### transaction-example
1. Refer to #5256 to update the sharding configuration for the following properties.
> ./incubator-shardingsphere/examples/sharding-jdbc-example/orchestration-example/orchestration-spring-namespace-example/src/main/resources/META-INF/nacos/local/application-sharding-databases-tables.xml
./incubator-shardingsphere/examples/sharding-jdbc-example/orchestration-example/orchestration-spring-namespace-example/src/main/resources/META-INF/zookeeper/local/application-sharding-databases-tables.xml

2. Run `ExampleMain` to test your update.
-------
### transaction-example
1. Refer to #5256 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/transaction-example/transaction-2pc-xa-spring-namespace-example/src/main/resources`
> application-sharding-databases.xml
application-sharding-databases-tables.xml
application-sharding-tables.xml

2. Run `XAOrderService` to test your update.

**Comment by edidada** [comment]
5289

**Comment by edidada** [comment]
> 5289

I will try to do this

**Comment by tristaZero** [comment]
@edidada 
Hi Nice to meet you, and welcome. 😉
