### ISSUE TITLE
[NEW API] 2-Update Sharding SpringNameSpace configuration with new API

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5290]
Hi everyone. Welcome your joining! 😉

Content: Update the configuration of the sharding algorithm for Sharding SpringNameSpace with the new API.

Difficulty rating: ★☆☆☆☆

Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. **Just follow the comment below to create your PR.** 😀

**Comment by tristaZero** [comment]
## How

### sharding-example
#### sharding-spring-namespace-jpa-example
1. Refer to #5256 to update the sharding configuration for the following properties in `/Users/trista/Documents/sharding-code-trista/incubator-shardingsphere/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources`.
>application-sharding-databases.properties
application-sharding-databases-tables.properties
application-sharding-tables.properties

2. Run `ExampleMain` to test your update.
-------
### sharding-example
#### sharding-spring-boot-mybatis-example
1. Refer to #5256 to update the sharding configuration for the following properties in `./incubator-shardingsphere/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources`
> application-sharding-databases.xml
application-sharding-databases-tables.xml
application-sharding-tables.xml

2. Run `ExampleMain` to test your update.

**Comment by meAsky** [comment]
I want to try it

**Comment by tristaZero** [comment]
@meAsky Hi Glad to see you here, and welcome!
