### ISSUE TITLE
[DISCUSS]About metrics feature

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5291]
Hi, community:
We know there are three important parts of observability with modern distributed system: logging, metric and tracing.
The tracing feature for observability in ShardingSphere components, logging feature is easy to gain via some tools such like ELK.And it's the time to design and implement metrics feature now. Finally we get a complete observability with UI console(integration with promethus/grafana). 
So we will launch this mission for the certain tasks about metrics. @yu199195 will be in charge of them.

Any ideas and questions are welcome here.

All incoming tasks will be shown project board: https://github.com/apache/shardingsphere/projects/11

**Comment by yu199195** [comment]
welcome friends from the community to discuss and finish.

**Comment by sunng87** [comment]
Data sources like [HikariCP](https://github.com/brettwooldridge/HikariCP) provides useful [metrics](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics) about its internal state. 

It would be nice if ShardingSphere follows this approach for its managed data sources.
