### ISSUE TITLE
use sharding-jdbc with oracle occur ORA-17059: Fail to convert to internal representation

### ISSUE THREAD

**Issue by shengzhai2015** [apache/shardingsphere#5296]
database :oracle 11g
jdbc driver: ojdbc6.jar
sharding-jdbc version: 4.0.0
  There is an Exception when I try to connect to oracle database with sharding-jdbc. According to the Exceptiontrace, I find the question.
  The Class org.apache.shardingsphere.core.execute.metadata.TableMetaDataLoader wil load All Table metadata in the getColumnMetaDataList method. When the method is executed, it will get a table property by jdbc resultset  in the 117 row.
Boolean isAutoIncrement = resultSet.getBoolean("IS_AUTOINCREMENT");
Then it will cause ORA-17059: Fail to convert to internal representation Exception .
I try to get the resultset then I know that the resultset will return String Value(Yes Or No) in my case. 
   Does anyone has the same question?

**Comment by kimmking** [comment]
Please try 4.0.1 or incoming 4.1.0 version, these codes was removed.
