### ISSUE TITLE
Enhance Bitronix and Narayana of sharding-transaction

### ISSUE THREAD

**Issue by cherrylzhao** [apache/shardingsphere#5302]
- [x] add unit test for sharding-transaction-xa-bitronix-mananger
- [ ] add unit test for sharding-transaction-xa-narayana-manager
- [x] add example for sharding-transaction-xa-bitronix-mananger
- [ ] add example for sharding-transaction-xa-narayana-manager

**Comment by TaoZhiMLND** [comment]
I want to solve this issue.
