### ISSUE TITLE
Call ComplexShardingStrategies even if no sharding conditions are present

### ISSUE THREAD

**Issue by KoxAlen** [apache/shardingsphere#5304]
## Feature Request
It would be good if ComplexShardingStrategies were able to decide the default behavior when no sharding conditions are present instead of defaulting to all shards.
Currently the ShardingStrategy is not called if there aren't any sharding condition in the query.

We had an use case where we needed a mix of InlineShardingStrategy and HintShardingStrategy.
We were able to emulate it easily with a ComplexShardingStrategy but we needed it to also apply to queries without sharding columns.
I also think it makes a lot of sense from a design perspective that the ComplexShardingStrategy can decide its default behavior.

The Feature request is about allowing (at least) ComplexShardingStrategy to influence queries without any sharding conditions.

**Comment by kimmking** [comment]
Hi, kox,
I guess you can put the default behavior into your custom ComplexShardingStrategy implementation.

**Comment by KoxAlen** [comment]
Sorry, maybe my message wasn't clear, I'll add an edit.
The problem is that currently the ComplexShardingStrategy is **not** called if there aren't any sharding condition in the query so I can't use it to decide the behavior of queries like "SELECT * FROM sharded". The Feature request is about allowing (at least) ComplexShardingStrategy to inflience those kind of queries

**Comment by kimmking** [comment]
It means that the current default strategy is to broadcast to all nodes, and you suggest users should config the defaut strategy instead of it?

**Comment by KoxAlen** [comment]
Yes, the feature request is about being able to decide which nodes a query should hit if it doesn't have  any sharding condition instead of always going to all nodes

**Comment by kimmking** [comment]
Can you make a pr for it?

**Comment by terrymanu** [comment]
Closed because of nobody interested about this issue
