### ISSUE TITLE
I want read-write separation and data desensitization can be supported at the same time

### ISSUE THREAD

**Issue by kuangyoubo** [apache/shardingsphere#5310]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.

### Describe the feature you would like.
I want read-write separation and data desensitization can be supported at the same time.

**Comment by yu199195** [comment]
please in English

**Comment by yu199195** [comment]
you can follow this doc https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/

**Comment by terrymanu** [comment]
We are doing this feature on #3691
