### ISSUE TITLE
Batch insert data is too slow when using sharding-jdbc

### ISSUE THREAD

**Issue by huweidada** [apache/shardingsphere#5313]
use PreparedStatement，batch insert，312 rows，insert into table (.....) values (...),(...),(...),(...),(...),(...),(...)
from origin sql to logic sql，it takes 5 seconds

ShardingSphere-sharding-jdbc,version:4.0.0

I found,something times,it takes too time,sometime very fast

I have log,do you need it to analysis？

how could I solve the problem？（Question aready asked，but no Solution）

**Comment by tuohai666** [comment]
Parse this SQL the first time will be slow. The parse result of the SQL will be cached after the first time, and will be very fast in future.

The parse engine will have an update in the version 4.1.0 which will be released soon. In the new release even the first time parsing will be very fast.

If you want to have a try right now, please compile the codes in the master branch or dev-4.x branch locally using version 5.1.0-SNAPSHOT.

**Comment by huweidada** [comment]
ths,we will wait for your optimizated version。
