### ISSUE TITLE
Archive Doc 4.x 

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5314]
Once 4.1.0 is released successfully, this issue starts.
- [x] Archive Doc 4.x
- [x] Create Doc 5.x as current doc directory
- [x] Merge doc5.x branch into master
- [x] Update links of doc on website

**Comment by kimmking** [comment]
roger

**Comment by kimmking** [comment]
https://github.com/apache/shardingsphere-doc/pull/472
