### ISSUE TITLE
Blog section is going to online

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5315]
The following items are needed to archive articles from different platforms and present some of them on the blog section,

- [x] Create a blog section by Hugo
- [x] 2 Update `build.sh`
- [x] 3 Collect all the articles published on different platforms to GitHub issue
- [x] 4 Add the drop-down list of the blog and GitHub issue on the homepage

**Comment by tristaZero** [comment]
Hi community,

Currently, we need more volunteers to take charge of the first and third ones. If you would like to translate some of our materials to English or organize blogs concerning ShardingSphere, please respond to this issue. 
Welcome! 😀

**Comment by wubingting** [comment]
join!join!join!

**Comment by tristaZero** [comment]
@wubingting Please append the article list [here](https://github.com/apache/shardingsphere/issues/5317).
