### ISSUE TITLE
ShardingSphere FAQ(常见问题与解决办法，有问题先看这里)

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5317]
## English version: https://shardingsphere.apache.org/document/current/en/faq
1. How to debug when SQL can not be executed rightly in ShardingSphere?
2. Why do some compiling errors appear?
3. Why is xsd unable to be found when Spring Namespace is used?
4. How to solve Cloud not resolve placeholder … in string value … error?
5. Why does float number appear in the return result of inline expression?
6. If sharding database is partial, should tables without sharding database & table be configured in sharding rules?
7. In addition to internal distributed primary key, does ShardingSphere support other native auto-increment keys?
8. When generic Long type SingleKeyTableShardingAlgorithm is used, why doesClassCastException: Integer can not cast to Long exception appear?
9. In SQLSever and PostgreSQL, why does the aggregation column without alias throw exception?
10. Why does Oracle database throw “Order by value must implements Comparable” exception when using Timestamp Order By?
11. Why is the database sharding result not correct when using Proxool?
12. Why are the default distributed auto-augment key strategy provided by ShardingSphere not continuous and most of them end with even numbers?
13. In Windows environment,when cloning ShardingSphere source code through Git, why prompt filename too long and how to solve it?
14. In Windows environment, could not find or load main class org.apache.shardingshpere.shardingproxy.Bootstrap, how to solve it?
15. How to solve Type is required error?
16. Why does my custom distributed primary key do not work after implementing ShardingKeyGenerator interface and configuring type property?
17. How to solve that DATA MASKING can’t work with JPA?
18. How to speed up the metadata loading when service starts up?
19. How to allow range query with using inline sharding strategy(BETWEEN AND, >, <, >=, <=)?
20. Why there may be an error when configure both sharding-jdbc-spring-boot-starter and a spring-boot-starter of certain datasource pool(such as druid)?
21. How to add a new logic schema dynamically when use sharing-proxy?
22. How to use a suitable database tools connecting sharding-proxy?

## Chinese version: https://shardingsphere.apache.org/document/current/cn/faq
1. 如果SQL在ShardingSphere中执行不正确，该如何调试？
2. 阅读源码时为什么会出现编译错误?
3. 使用Spring命名空间时找不到xsd?
4. Cloud not resolve placeholder … in string value …异常的解决方法?
5. inline表达式返回结果为何出现浮点数？
6. 如果只有部分数据库分库分表，是否需要将不分库分表的表也配置在分片规则中？
7. ShardingSphere除了支持自带的分布式自增主键之外，还能否支持原生的自增主键？
8. 指定了泛型为Long的SingleKeyTableShardingAlgorithm，遇到ClassCastException: Integer can not cast to Long?
9. 使用SQLSever和PostgreSQL时，聚合列不加别名会抛异常？
10. Oracle数据库使用Timestamp类型的Order By语句抛出异常提示“Order by value must implements Comparable”?
11. 使用Proxool时分库结果不正确？
12. ShardingSphere提供的默认分布式自增主键策略为什么是不连续的，且尾数大多为偶数？
13. Windows环境下，通过Git克隆ShardingSphere源码时为什么提示文件名过长，如何解决？
14. Windows环境下，运行Sharding-Proxy，找不到或无法加载主类 org.apache.shardingshpere.shardingproxy.Bootstrap，如何解决？
15. Type is required 异常的解决方法?
16. 为什么我实现了ShardingKeyGenerator接口，也配置了Type，但是自定义的分布式主键依然不生效？
17. JPA 和 数据脱敏无法一起使用，如何解决？
18. 服务启动时如何加快metadata加载速度？
19. 如何在inline分表策略时，允许执行范围查询操作（BETWEEN AND、>、<、>=、<=）？
20. 为什么配置了某个数据连接池的spring-boot-starter（比如druid）和sharding-jdbc-spring-boot-starter时，系统启动会报错？
21. 在使用sharing-proxy的时候，如何动态在sharding-ui上添加新的logic schema？
22. 在使用sharing-proxy时，怎么使用合适的工具连接到proxy？

**Comment by nongchangzhu** [comment]
sharding.jdbc.config.masterslave.name=ms #读写分离数据源名称 
 这句话咋理解呢？？？？

//---------------------------------------------------------------------------------------------
sharding.jdbc.datasource.names=master,slave0,slave1

sharding.jdbc.datasource.master.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.master.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.master.url=jdbc:mysql://localhost:3306/master
sharding.jdbc.datasource.master.username=root
sharding.jdbc.datasource.master.password=

sharding.jdbc.datasource.slave0.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.slave0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.slave0.url=jdbc:mysql://localhost:3306/slave0
sharding.jdbc.datasource.slave0.username=root
sharding.jdbc.datasource.slave0.password=

sharding.jdbc.datasource.slave1.type=org.apache.commons.dbcp.BasicDataSource
sharding.jdbc.datasource.slave1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.slave1.url=jdbc:mysql://localhost:3306/slave1
sharding.jdbc.datasource.slave1.username=root
sharding.jdbc.datasource.slave1.password=

sharding.jdbc.config.masterslave.load-balance-algorithm-type=round_robin
sharding.jdbc.config.masterslave.name=ms
sharding.jdbc.config.masterslave.master-data-source-name=master
sharding.jdbc.config.masterslave.slave-data-source-names=slave0,slave1

sharding.jdbc.config.props.sql.show=true



对于上面这样一个官方给的配置， sharding.jdbc.config.masterslave.name=ms   中的ms  是怎样来的，可以随意写吗？？？？
