### ISSUE TITLE
Do you have a demo integrated with springboot,mybatisplus and shardingsphere

### ISSUE THREAD

**Issue by yc825106632** [apache/shardingsphere#5328]
我在官网中看到 “在Spring中使用DataSource
直接通过注入的方式即可使用DataSource，或者将DataSource配置在JPA、Hibernate或MyBatis中使用。” 这样一句，但是却是找不到可用的案例，官方能提供下有springboot2,mybatisplus3.3.1与shardingsphere4.0.1集成的demo吗

**Comment by yc825106632** [comment]
要求比较奢侈，主要不熟悉如何使用官网中的这个，所以各种集成都不能用，因此来向官方求助了
@Resource
private DataSource dataSource;

**Comment by yc825106632** [comment]
我集成之后分页不能用了，localdatetime转换不能用了，fastjson的全局时间转换不能用了，mybatisplus的各种增强功能也都不能用了，官方有意向出这三大框架的集成demo吗？

**Comment by kimmking** [comment]
English only.

**Comment by yc825106632** [comment]
I saw "DataSource in Spring" on the website
You can use the DataSource directly through injection, or configure the DataSource to be used in JPA, Hibernate or MyBatis.This way, but can't find the available case, under the official offer springboot2, mybatisplus3.3.1 and shardingsphere4.0.1 integrated demo

**Comment by yc825106632** [comment]
Requirements are relatively luxurious, mainly not familiar with how to use this in the official website, so all kinds of integration can not be used, so to the official help
@ the resource
Private DataSource DataSource.

**Comment by yc825106632** [comment]
After my integration, paging could not be used, localdatetime conversion could not be used, global time conversion of fastjson could not be used, and various enhanced functions of mybatisplus could not be used. Is the official intention for the integration demo of these three frameworks? thanks thanks thanks

**Comment by kimmking** [comment]
Issue title also should be updated.

**Comment by yc825106632** [comment]
It has been updated

**Comment by terrymanu** [comment]
Example for spring boot and mybatis:
https://github.com/apache/shardingsphere/tree/master/examples/sharding-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example

No example for mybatis-plus, because Apache ShardingSphere is faced on international projects only.
