### ISSUE TITLE
batch  insert slow

### ISSUE THREAD

**Issue by believeyounger** [apache/shardingsphere#5332]
## Question
Version:4.0.1
I will batch insert 50W data.
Native jdbc execute sql , time: 25s.
Use sharding-jdbc execute sql, time: more than 3min.
Preliminary suspicion ：SQLRouteResult result = this.route(sql, clonedParameters); 

Please let us know the possible reasons，thinks

**Comment by kimmking** [comment]
duplicated with https://github.com/apache/shardingsphere/issues/5313 https://github.com/apache/shardingsphere/issues/5023 https://github.com/apache/shardingsphere/issues/4479 https://github.com/apache/shardingsphere/issues/3427

**Comment by kimmking** [comment]
b
