### ISSUE TITLE
shardingsphere 3.1 parse sql excpetion

### ISSUE THREAD

**Issue by ETUFO** [apache/shardingsphere#5337]
version ： shardingsphere 3.1
sharding-jdbc parse sql ：SELECT exam_id FROM exam_round WHERE (time LIKE ?) 
error message ：line 5:13 no viable alternative at input '(timeLIKE'
Cause io.shardingsphere.core.routing.SQLRouteResult is null，throw  java.lang.NullPointerException

**Comment by kimmking** [comment]
3.1 is a tooo oold version, you should try 4.0.1 or 4.1.0.
