### ISSUE TITLE
[DOC]Update the English document for encypt feature

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5338]
Hi everyone. Welcome your joining! 😉

Content: Update the English document [1] to sync with Chinese version[2] for encypt feature.

Difficulty rating: ☆☆☆☆☆

Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. Just follow the comment below to create your PR. 😀

1.https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/orchestration/encrypt.en.md
2.https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/orchestration/encrypt.cn.md

**Comment by kimmking** [comment]
> Hi everyone. Welcome your joining! 😉
> 
> Content: Update the English document [1] to sync with Chinese version[2] for encypt feature.
> 
> Difficulty rating: ☆☆☆☆☆
> 
> Note: To make each ISSUE simple, we split a bulky ISSUE into a few small ones. Just follow the comment below to create your PR. 😀
> 
> 1.https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/orchestration/encrypt.en.md
> 2.https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/orchestration/encrypt.cn.md

**Comment by taojintianxia** [comment]
May I ?

**Comment by kimmking** [comment]
You can.

**Comment by baiyongwei** [comment]
still have chance?

**Comment by taojintianxia** [comment]
> still have chance?

you wanna translate the picture into English ?
