### ISSUE TITLE
[performance test] proxy is too slow with sysbench

### ISSUE THREAD

**Issue by ChuckPerry** [apache/shardingsphere#5345]
## Question
I run sharding-proxy with no sharding mode. there's only 100+ qps , and with same parameters, there's 8000+ qps when I connect mysql directly.
![Snipaste_2020-04-27_17-28-10](https://user-images.githubusercontent.com/10229398/80356885-b3c4e800-88ac-11ea-9fec-fbe22d007124.jpg)
![Snipaste_2020-04-27_17-29-42](https://user-images.githubusercontent.com/10229398/80356903-b9bac900-88ac-11ea-8d22-ac4dcf66cbb3.jpg)
 
Environment:
- mysql 5.7.29
- sharding-proxy 4.0.1
- centos 7.4.18
- jdk 1.8+

Config files:
- server.yaml
`#orchestration:`
`#  name: orchestration_ds`
`#  overwrite: true`
`#  registry:`
`#    type: zookeeper`
`#    serverLists: localhost:2181`
`#    namespace: orchestration`
`#`
`authentication:`
`  users:`
`    root:`
`      password: root`
`      authorizedSchemas: test_db`
`    sharding:`
`      password: sharding`
`      authorizedSchemas: sharding_db`
`#`
`props:`
`  max.connections.size.per.query: 1`
`  acceptor.size: 16  # The default value is available processors count * 2.`
`  executor.size: 16  # Infinite by default.`
`  proxy.frontend.flush.threshold: 512  # The default value is 128.`
`#    # LOCAL: Proxy will run with LOCAL transaction.`
`#    # XA: Proxy will run with XA transaction.`
`#    # BASE: Proxy will run with B.A.S.E transaction.`
`  proxy.transaction.type: XA`
`  proxy.opentracing.enabled: false`
`  query.with.cipher.column: true`
`  sql.show: false`
- config-master_slave.yaml
`schemaName: test_db`
`dataSources:`
`  master_ds:`
`    url: jdbc:mysql://10.10.10.103:3306/test_db?serverTimezone=UTC&useSSL=false`
`    username: user`
`    password: xxxxxx`
`    connectionTimeoutMilliseconds: 30000`
`    idleTimeoutMilliseconds: 60000`
`    maxLifetimeMilliseconds: 1800000`
`    maxPoolSize: 100`
`  slave_ds_0:`
`    url: jdbc:mysql://10.10.10.102:3306/test_db?serverTimezone=UTC&useSSL=false`
`    username: user`
`    password: xxxxxx`
`    connectionTimeoutMilliseconds: 30000`
`    idleTimeoutMilliseconds: 60000`
`    maxLifetimeMilliseconds: 1800000`
`    maxPoolSize: 100`
`  slave_ds_1:`
`    url: jdbc:mysql://10.10.10.101:3306/test_db?serverTimezone=UTC&useSSL=false`
`    username: user`
`    password: xxxxxx`
`    connectionTimeoutMilliseconds: 30000`
`    idleTimeoutMilliseconds: 60000`
`    maxLifetimeMilliseconds: 1800000`
`    maxPoolSize: 100`
`#masterSlaveRule:`
`#  name: ms_ds`
`#  masterDataSourceName: master_ds`
`#  slaveDataSourceNames:`
`#    - slave_ds_0`
`#    - slave_ds_1`
Is there any place that I'm wrong?

**Comment by tuohai666** [comment]
Don't worry, you didn't do anything wrong.
The performance issue in 4.0.1 will be resolved in 4.1.0 which is in releasing process(under voting now).
The performance will be improved by two aspect:
1. New parser engine that will improve parse performance for long SQL by more than 10000%.
2. Fixed several C API related issues: #4358, #4355, #4255, #3968, #4501

You can compile the codes of 4.1.0 in https://github.com/apache/shardingsphere/releases/tag/4.1.0.
Or just wait the new release for about one week.

**Comment by rouxiaoxiao** [comment]
> Don't worry, you didn't do anything wrong.
> The performance issue in 4.0.1 will be resolved in 4.1.0 which is in releasing process(under voting now).
> The performance will be improved by two aspect:
> 
> 1. New parser engine that will improve parse performance for long SQL by more than 10000%.
> 2. Fixed several C API related issues: #4358, #4355, #4255, #3968, #4501
> 
> You can compile the codes of 4.1.0 in https://github.com/apache/shardingsphere/releases/tag/4.1.0.
> Or just wait the new release for about one week.

I have the same problem and the speed is not improved after upgrading to version 4.1.0.The following are my details:
sql cost：110ms
jdbc cost: 226ms
sharding jdbc 4.0.1: 2883ms
sharding jdbc 4.1.0:2930ms
