### ISSUE TITLE
count(DISTINCT xx)  has problem 

### ISSUE THREAD

**Issue by LikeBigCat** [apache/shardingsphere#5347]
version：4.0.1
Logic SQL: SELECT count(p.id) as pCount, count(DISTINCT p.store_id) as sCount FROM prescription p
Actual SQL ::: SELECT DISTINCT count(p.id) as pCount, p.store_id as sCount FROM prescription_0 p

The semantics here have changed

**Comment by tristaZero** [comment]
@LikeBigCat Hi Thanks for your feedback, but I am sorry this type of SQL is not supported currently. You can look up more in [Supported SQL](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/)
