### ISSUE TITLE
About spring.shardingsphere.masterslave.name = ms (read and write separation configuration)?

### ISSUE THREAD

**Issue by nongchangzhu** [apache/shardingsphere#5353]
What does the "ms" of "spring.shardingsphere.masterslave.name=ms" mean in the configuration of read-write separation? Can I write any mark?

**Comment by kimmking** [comment]
Yes, you can name it with any identifier string.
And if you configure master-slave with sharding rules, this identifier will be the table prefix.

1. https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/read-write-splitting/
