### ISSUE TITLE
batch insert route result is wrong

### ISSUE THREAD

**Issue by leego86** [apache/shardingsphere#5366]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
primary key produced by key generator 
Logic SQL:
insert into test_complex 	(`name`,age,create_time,modified_time,user_id,phone,address)
		values(?,?,?,?,?,	?,?) , (?,?,?,?,?,?,?) 
route result of sharding key(id)
  logicName=sharding_db, value=461910991453999105, hash=1101970151 , mod=1
  logicName=sharding_db, mod=1 ,route =sharding_db_1
  logicName=test_complex, value=461910991453999105, hash=1101970151 , mod=7
  logicName=test_complex, mod=7 ,route =test_complex_7

  logicName=sharding_db, value=461910991453999108, hash=1101970154 , mod=0
  logicName=sharding_db, mod=0 ,route =sharding_db_0
  logicName=test_complex, value=461910991453999108, hash=1101970154 , mod=2
  logicName=test_complex, mod=2 ,route =test_complex_2
### Actual behavior

Actual SQL: sharding_db_1 ::: insert into test_complex_3	(`name`,age,create_time,modified_time,user_id,phone,address,id) values
		(?, ?, ?, ?, ?, ?, ?, ?),(?, ?, ?, ?, ?, ?, ?, ?)
			::: [null, 1, 2020-04-28 15:09:21.415, 2020-04-28 15:09:21.415, 09c53d8e85934bbf8aeeec3d4711c0c95, 09c53d8e85934bbf8aeeec3d4711c0c95, 时代峰峻克鲁赛德, 461910991453999108, null, 1, 2020-04-28 15:09:21.415, 2020-04-28 15:09:21.415, 09c53d8e85934bbf8aeeec3d4711c0c98, 09c53d8e85934bbf8aeeec3d4711c0c98, 时代峰峻克鲁赛德, 461910991453999105]

### Reason analyze (If you can)
ShardingGeneratedKeyInsertValueParameterRewriter rewrite generateKey values had a descendingIterator
![image](https://user-images.githubusercontent.com/31645800/80464764-d9192b00-896c-11ea-8ee9-39ff979e871f.png)
the params had a descending order of route result, cause th actual sql is wrong
why use descendingIterator here ?  if use common iterator would cause some problems?

**Comment by kimmking** [comment]
duplicated with https://github.com/apache/shardingsphere/issues/4573

**Comment by kimmking** [comment]
===> case 1 multi values: insert into aa(name) values('tttt1'),('tttt2'),('tttt3'),('tttt4'),('tttt5')
ID: GeneratedKeys37
ID: GeneratedKeys38
ID: GeneratedKeys39
ID: GeneratedKeys40
ID: GeneratedKeys41
ID: 37, NAME: tttt1
ID: 38, NAME: tttt2
ID: 39, NAME: tttt3
ID: 40, NAME: tttt4
ID: 41, NAME: tttt5
 ===> case 2 prepare stmt: insert into aa(name) values(?),(?),(?),(?),(?)
ID: GeneratedKeys42
ID: GeneratedKeys43
ID: GeneratedKeys44
ID: GeneratedKeys45
ID: GeneratedKeys46
ID: 42, NAME: zzz1
ID: 43, NAME: zzz2
ID: 44, NAME: zzz3
ID: 45, NAME: zzz4
ID: 46, NAME: zzz5
 ===> case 3 batch prepare: insert into aa(name) values(?),(?),(?)
ID: GeneratedKeys47
ID: GeneratedKeys48
ID: GeneratedKeys49
ID: 47, NAME: yyy4
ID: 48, NAME: yyy5
ID: 49, NAME: yyy6

**Comment by kimmking** [comment]
If we execute above case by a logic table aa0,aa1 in today's master code, the result is error:
```
ID: 462298010773094402, NAME: tttt4
ID: 462298010773094404, NAME: tttt2
ID: 462298010773094401, NAME: tttt5
ID: 462298010773094403, NAME: tttt3
ID: 462298010773094405, NAME: tttt1
 ===> case 2 prepare stmt: insert into aa(name) values(?),(?),(?),(?),(?)
ID: 462298011511291904, NAME: zzz5
ID: 462298011511291906, NAME: zzz3
ID: 462298011511291908, NAME: zzz1
ID: 462298011511291905, NAME: zzz4
ID: 462298011511291907, NAME: zzz2
 ===> case 3 batch prepare: insert into aa(name) values(?),(?),(?)
ID: 462298012215934978, NAME: yyy2
ID: 462298012488564736, NAME: yyy6
ID: 462298012488564738, NAME: yyy4
ID: 462298012215934977, NAME: yyy3
ID: 462298012215934979, NAME: yyy1
ID: 462298012488564737, NAME: yyy5

```

**Comment by kimmking** [comment]
If we change as https://github.com/apache/shardingsphere/pull/4574 ,
the sharding is right, but generatedkeys is also empty.
```
 ===> case 1 multi values: insert into aa(name) values('tttt1'),('tttt2'),('tttt3'),('tttt4')
ID: 462301646538407936, NAME: tttt1
ID: 462301646542602242, NAME: tttt3
ID: 462301646542602241, NAME: tttt2
ID: 462301646542602243, NAME: tttt4
 ===> case 2 prepare stmt: insert into aa(name) values(?),(?),(?),(?)
ID: 462301648023191552, NAME: zzz1
ID: 462301648023191554, NAME: zzz3
ID: 462301648023191553, NAME: zzz2
ID: 462301648023191555, NAME: zzz4
 ===> case 3 batch prepare: insert into aa(name) values(?),(?),(?),(?)
ID: 462301648753000450, NAME: yyy2
ID: 462301648753000452, NAME: yyy4
ID: 462301649038213120, NAME: yyy5
ID: 462301649042407426, NAME: yyy7
ID: 462301648753000449, NAME: yyy1
ID: 462301648753000451, NAME: yyy3
ID: 462301649042407425, NAME: yyy6
ID: 462301649042407427, NAME: yyy8
```

**Comment by tristaZero** [comment]
Hi @leego86 Sorry for my late response.

Looking at your debugging, It seems you located the cause, didn't you?
Is there any progress for this issue. Besides, your issue is related to #6895. 

Considering the serious effect on the users, it is expected to figure them out entirely before the next release. Could you give us a hand?

Waiting for your reply.

Best,
Trista
