### ISSUE TITLE
Add a summary report for integrate-test

### ISSUE THREAD

**Issue by cherrylzhao** [apache/shardingsphere#5377]
our integrate test framework will initialize cases according to database type dimension, only execute it if database environment is available. it is better to add a summary report to tell the user the actual execute information, I will design it recently.

**Comment by cherrylzhao** [comment]
I want to add test plan log before actually execute the parameterized case:
```
[INFO] ======= Test Plan =======
[INFO] Total: xxx, Active: H2(xxx), Disabled: MySQL(xxx), PostgreSQL(xxx), SQLServer(xxx), Oracle(xxx)```

after we `mvn clean install` the summary report look like this:

```
[INFO] Running org.apache.shardingsphere.dbtest.engine.dcl.GeneralDCLIT
[INFO] ======= Test Plan =======
[INFO] Total: xxx, Active: H2(xxx), Disabled: MySQL(xxx), PostgreSQL(xxx), SQLServer(xxx), Oracle(xxx)
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shardingsphere.dbtest.engine.dcl.GeneralDCLIT
[INFO] Running org.apache.shardingsphere.dbtest.engine.dml.GeneralDMLIT
[INFO] ======= Test Plan =======
[INFO] Total: xxx, Active: H2(xxx), Disabled: MySQL(xxx), PostgreSQL(xxx), SQLServer(xxx), Oracle(xxx)
[INFO] Tests run: 336, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.3 s - in org.apache.shardingsphere.dbtest.engine.dml.GeneralDMLIT
```

**Comment by terrymanu** [comment]
If the test plan is not execute fully, should we use WARN instead of INFO?

**Comment by cherrylzhao** [comment]
agree with it, WARN is better for that
