### ISSUE TITLE
https://dist.apache.org/repos/dist/release/shardingsphere/,the link is error

### ISSUE THREAD

**Issue by huntunshule** [apache/shardingsphere#5380]
The wget link in the official dockerfile is incorrect and does not exist
![image](https://user-images.githubusercontent.com/52652738/80579314-65465380-8a3c-11ea-8cb1-4fc0bf55acae.png)

**Comment by kimmking** [comment]
which document?

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Will fix after 4.1.0 release finished

**Comment by huntunshule** [comment]
> Will fix after 4.1.0 release finished

ok
