### ISSUE TITLE
字符串类型分库，删除和更新不会生成undo_log，也不会正常回滚

### ISSUE THREAD

**Issue by zhangchuan1990** [apache/shardingsphere#5398]
采用shardingJDBC+seata，分库键如果是字符串类型的（自己写分库实现），插入会生成undo_log 回滚也没有问题，但是删除和更新不会生成undo_log，也不会正常回滚

**Comment by menghaoranss** [comment]
@zhangchuan1990 For English only here,  please translacte your issue title and content.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
