### ISSUE TITLE
update and delete no undo_log generated and cannot be rollback

### ISSUE THREAD

**Issue by zhangchuan1990** [apache/shardingsphere#5404]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-jdbc
### Actual behavior
Using sharding-jdbc and Seata, if the type of database-strategy.sharding-column is String , there is no problem with insert, but update and delete , no undo_log generated and cannot be rollback.
version:
sharding-jdbc 4.0.0
seata:1.2.0
spring-cloud-dependencies:Finchley.SR2
spring-boot-dependencies:2.0.6.RELEASE

**Comment by kimmking** [comment]
you should try 4.1.0

**Comment by cherrylzhao** [comment]
kimmking is right, you should have a try using 4.1.0 @zhangchuan1990

**Comment by zhangchuan1990** [comment]
think you ,Now it's no problem
