### ISSUE TITLE
@Transaction invalid

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#5411]
version:4.0.1
pom.xml:
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${shardingsphere.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-transaction-xa-core</artifactId>
            <version>${shardingsphere.version}</version>
        </dependency>
result:
    **@Transaction   invalid** 

If I exclude sharding-transaction-xa-core, transaction will be normal

**Comment by cherrylzhao** [comment]
@ShardingTransactionType annotation should be declared, please use 4.1.0, example is [here](https://github.com/apache/shardingsphere/tree/master/examples/sharding-jdbc-example/transaction-example/transaction-2pc-xa-spring-boot-example)

**Comment by romantictravel01** [comment]
I added @Import (TransactionConfiguration.class) in the startup class, using @Transaction is normal,
At this time, only DatasourceTransactionManager instance
        Add @Import (TransactionConfiguration.class) in the non-starting class, an error is reported when running expected single matching bean but found 2: transactionManager, txManager
jtaTransactionManager and DatasourceTransactionManager instances
       My code
      @Transactional (rollbackFor = Exception.class)
     @ShardingTransactionType (TransactionType.XA)
   public boolean change (xx) {
    }

**Comment by cherrylzhao** [comment]
@SpringBootApplication(exclude = JtaAutoConfiguration.class) is needed for your case

**Comment by kimmking** [comment]
@cherrylzhao should we add this case to faq?

**Comment by cherrylzhao** [comment]
yes, let me append it.
