### ISSUE TITLE
Cannot use LogicTableName in 'where clause'

### ISSUE THREAD

**Issue by 362475097** [apache/shardingsphere#5414]
I‘m using sqlalchemy + sharding-proxy.

The sql created by sqlalchemy like this:
  select * from order_info where CAST(order_info.create_time AS DATE) = '2020-05-03';

The real sql excuted by sharding-proxy like this:
  select * from order_info_2020_4 where CAST(order_info.create_time AS DATE) = '2020-05-03';

So the 'order_info' in 'where clause' is wrong. 
How to solve this problem?

**Comment by terrymanu** [comment]
What is your version?

**Comment by 362475097** [comment]
> What is your version?

My version is 4.1.0

**Comment by terrymanu** [comment]
You can use alias to instead of table name

**Comment by kimmking** [comment]
Or remove the table name in the prefix

**Comment by terrymanu** [comment]
Closed because of no response anymore
