### ISSUE TITLE
Does not support getObject with type yet?

### ISSUE THREAD

**Issue by liunancun** [apache/shardingsphere#5420]
Using MyBatis to return a LocalDateTime type field gives an error.

java.sql.SQLFeatureNotSupportedException: getObject with type
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getObject(AbstractUnsupportedOperationResultSet.java:221) ~[sharding-jdbc-core-4.1.0.jar:4.1.0]
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38) ~[mybatis-3.5.2.jar:3.5.2]

The sharding-jdbc version used is 4.1.0

Is there a way to solve this error?

**Comment by kimmking** [comment]
doesn't support yet.

**Comment by tuohai666** [comment]
Sharding-JDBC doesn't support getObject with type for now. You can try getTimestamp

**Comment by laingke** [comment]
In the release note, it says "Upgrade to Java 8", so I wonder what had been upgrade.

**Comment by tuohai666** [comment]
> In the release note, it says "Upgrade to Java 8", so I wonder what had been upgrade.

JDK, grammar, dependiencies... had been update to Java 8

**Comment by tuohai666** [comment]
Sharding-JDBC doesn't support doesn't support generic result now.

**Comment by alterhu2020** [comment]
Why not fixed, it's LocalDateTime support yet?
