### ISSUE TITLE
Avoid using JUnit on example

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#5425]
The current examples have lots of codes which include JUnit.
It is better to use main method instead of them, the benefits are:

1. Example should as simple as passible, user do not need to understand JUnit.
2. JUnit is not an unique unit test framework, some developers may prefer testNG.
3. The different versions of JUnit (3.x, 4.x, 5.x)'s APIs are different totally, it is difficult to decide which version we should use.

**Comment by TaoZhiMLND** [comment]
I want to support this issue. It is related on the issue #5302 which I focus on.

**Comment by terrymanu** [comment]
Welcome

**Comment by taojintianxia** [comment]
what's the original intention of **usding junit instead of main** ?

**Comment by cherrylzhao** [comment]
original intention is have a try to simplify the example structure, make every example independent from others, provide assert scenarios to let user know whether transaction works or not. If we just write a main, it is very confuse what have happened just through the print out logs.

**Comment by taojintianxia** [comment]
Understand. I also do agree with the idea of ​​**make every example independent from others**, Jun. But in my understanding, even in this case, junit is not the best assert scenarios way.if you wanna demonstrate the process , maybe BDD is better.
you could assert the scenarios by `GIVEN` `WHEN` `THEN` keyword even in your mother language or English as following :

```
Scenario: Account has sufficient funds
Given the account balance is $100
And the card is valid
And the machine contains enough money  
When the Account Holder requests $20
Then the ATM should dispense $20
And the account balance should be $80
And the card should be returned
```
But I personally prefer the example invoke by clear code structure through main method as the entrance.after all this example is for newbie, the more **stupid** the example is , the easier it can start with :smiley:

**Comment by cherrylzhao** [comment]
thanks a lot, BDD is a good idea
