### ISSUE TITLE
Use YAML file instead of inline string in test cases

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#5428]
Some cases include YAML inline string for testing orchestration persistent which are hard to read.
It is better to put the YAML inline string into YAML file.

Some test cases which need to be refactored:

- [ ] ConfigCenterTest
- [x] SchemaChangedListenerTest
- [ ] OrchestrationSpringBootRegistryShardingTest
- [ ] OrchestrationSpringBootRegistryEncryptTest
- [ ] OrchestrationSpringBootRegistryMasterSlaveTest
- [ ] HttpServerHandlerTest
- [ ] Still to be found...

**Comment by sukumaar** [comment]
Can I pick this issue? This is my first issue so is it ok if I work on ConfigCenterTest file first and raise PR ?

**Comment by menghaoranss** [comment]
@terrymanu We are optimizing the unit test coverage of the orchestration module now，I will optimize the above test classes at the same time.

**Comment by sukumaar** [comment]
@menghaoranss hey if you are busy with something and need some hand then please let me work on this , I also want to contribute to open source community :-)

**Comment by yu199195** [comment]
@sukumaar good ，you can pick a task to respond to.

**Comment by binxia5kpch** [comment]
what can i do for this case?

**Comment by binxia5kpch** [comment]
can i try the test `ConfigCenterTest`  ?

**Comment by menghaoranss** [comment]
> can i try the test `ConfigCenterTest` ?

of course，looking forward to your pull request.

**Comment by sukumaar** [comment]
> can i try the test `ConfigCenterTest` ?

hey is it possible for you to pick other test , because I have kinda started working on it.

**Comment by hitnewbee** [comment]
May I try `SchemaChangedListenerTest` this one？

**Comment by binxia5kpch** [comment]
> > can i try the test `ConfigCenterTest` ?
> 
> hey is it possible for you to pick other test ? , because I have kinda started working on it.
yeah, i can pick other

**Comment by binxia5kpch** [comment]
> > can i try the test `ConfigCenterTest` ?
> 
> hey is it possible for you to pick other test ? , because I have kinda started working on it.

yeah i can pick other

**Comment by binxia5kpch** [comment]
> > can i try the test `ConfigCenterTest` ?
> 
> hey is it possible for you to pick other test ? , because I have kinda started working on it.

yeah i can pick other @sukumaar

**Comment by terrymanu** [comment]
Please ref #5629, use 

```java
@SneakyThrows
    private String readYAML(final String yamlFile) {
        return Files.readAllLines(Paths.get(ClassLoader.getSystemResource(yamlFile).toURI())).stream().map(each -> each + System.lineSeparator()).collect(Collectors.joining());
    }
```

to load file content

**Comment by tomakemyself** [comment]
what can i do for this question?

**Comment by zengzhihong** [comment]
can i try the test:OrchestrationSpringBootRegistryEncryptTest

**Comment by terrymanu** [comment]
@tomakemyself @zengzhihong, welcome

**Comment by big-mountain-z** [comment]
Can I try the test: OrchestrationSpringBootRegistryMasterSlaveTest
