### ISSUE TITLE
master-slave mode doesn't read the meta data to obtain column definition

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#5433]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy

### Expected behavior
Use master-slave rule, execute SQL `select * from t_order` return correct result.

### Actual behavior
Can't return result and burst warnings.
```
mysql> use master_slave_db;
Database changed
mysql> select * from t_order_0;
Query OK, 0 rows affected, 25971 warnings (3 min 40.86 sec)
```

### Reason analyze (If you can)
The first packet Sharding-Proxy returned is an EOF packet, that means column definition packets lost. 
Debug in the codes, I found queryHeader size is 0. queryHeader  is obtained from meta data, master-slave mode doesn't read the meta data.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Config a master-rule and execute the SQL like `select * from`.

**Comment by kimmking** [comment]
I guess this is a design rather than a bug...
