### ISSUE TITLE
Add glossary in document

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#5434]
We need a glossary in our document because of some keywords maybe not universal name, for example: DCL, TCL.

I plan to collect the words in this issue and put them in the new glossary page. 
Please advice which words should include into glossary.

Thank you.

**Comment by taojintianxia** [comment]
jargon dictionary ? coool.

```
DDL, TCL, DAL, DCL, DML, DQL
redo log , undo log, bin log, wal, lsm, mvcc
```

**Comment by totalo** [comment]
such as : MMM 、MHA、MGR、read view、next-key、
