### ISSUE TITLE
通过yaml配置文件获取数据源失败

### ISSUE THREAD

**Issue by dostar** [apache/shardingsphere#5448]
## Question
1.项目添加的依赖shardingsphere jar包版本 4.1.0,springboot版本2.x
2.获取方式：
         File yamlFile = new File(DataSourceConfig.class.getResource("/application.yml").toURI());
        DataSource dataSource = YamlOrchestrationShardingDataSourceFactory.createDataSource(yamlFile);
3.yaml内容格式：
dataSources:
  ds0: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  ds1: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
        props:
          worker.id: 123

  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds${user_id % 2}
  defaultTableStrategy:
    none:

props:
  sql.show: false

4.异常信息：
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 4, column 20:
        driverClassName: com.mysql.cj.jdbc.Driver

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
