### ISSUE TITLE
Fetch DataSource by yaml file error

### ISSUE THREAD

**Issue by dostar** [apache/shardingsphere#5450]
## Question
1.Env info:   
    ShardingSphere jar version: 4.1.0
    springboot jar version:2.1.13.RELEASE
2. Key codes:
      File yamlFile = new File(DataSourceConfig.class.getResource("/application.yml").toURI());
        DataSource dataSource = YamlOrchestrationShardingDataSourceFactory.createDataSource(yamlFile);

3. yaml file is copy from   ShardingSphere example, file path is shardingsphere-4.1.0/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases-tables.yaml

4.error Info:
   Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 4, column 20:
        driverClassName: com.mysql.cj.jdbc.Driver

**Comment by yu199195** [comment]
What database connection pool ?  if  you ues  HikariDataSource ,this  driverClassName is  com.mysql.jdbc.Driver

**Comment by dostar** [comment]
HikariDataSource，but when I use com.mysql.jdbc.Driver ， is also the same error。
### aused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 4, column 20:
        driverClassName: com.mysql.jdbc.Driver

**Comment by terrymanu** [comment]
Can you use reference spring boot's example?
The raw jdbc yaml maybe not suitable with spring boot starter.

**Comment by dostar** [comment]
> Can you use reference spring boot's example?
> The raw jdbc yaml maybe not suitable with spring boot starter.

Can i  hava the other way to get  DataSource with springboot2 starter at bean confg？

**Comment by kimmking** [comment]
Can you show me your yaml file?

**Comment by dostar** [comment]
`
dataSources:
  ds0: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  ds1: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
        props:
          worker.id: 123

  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds${user_id % 2}
  defaultTableStrategy:
    none:

props:
  sql.show: false`

**Comment by dostar** [comment]
> Can you show me your yaml file?

I have send file to u by wechat。

**Comment by kimmking** [comment]
plz show all error stack here.

**Comment by dostar** [comment]
The problem has already been solved，thank u！
