### ISSUE TITLE
After source code changed in spring boot, hot reload  thow exception, sharding-sphere upgrade from 4.0.1 to 4.1.0 

### ISSUE THREAD

**Issue by King1031** [apache/shardingsphere#5453]
Caused by: org.hibernate.TransactionException: Already have an associated managed connection
![image](https://user-images.githubusercontent.com/32608606/81249815-2aeb4080-9052-11ea-8cba-d6da415dd95e.png)

**Comment by cherrylzhao** [comment]
please show the full stack trace, and what type of transaction you have used?

**Comment by King1031** [comment]
full stack here:
[stack.txt](https://github.com/apache/shardingsphere/files/4590660/stack.txt)

we used default type of transaction like this:
![企业微信截图_1588824591814](https://user-images.githubusercontent.com/32608606/81253715-c59c4d00-905b-11ea-8c6b-e6cee0800d5d.png)

**Comment by kimmking** [comment]
I guess we can't support hot-reload for hibernate now. Hibernate hold a connection by itself that sharding-jdbc can't control. So when sharding-jdbc reload and renew all connections with ds, those hold by hibernate is still the older ones.

**Comment by King1031** [comment]
if I switch to version 4.0.1 it works normally

**Comment by cherrylzhao** [comment]
I have tested `sharding-spring-boot-jpa-example`, it's ok.

**Comment by terrymanu** [comment]
Closed because no response anymore
