### ISSUE TITLE
scaling incrementalSyncTask is stuck

### ISSUE THREAD

**Issue by malaxiaolongxia** [apache/shardingsphere#5458]
Scaling incrementalSyncTask job is stucked in` MySQLClient.registerSlave() `and not work when i update source table

**Comment by avalon5666** [comment]
Pls provide steps to reproduce the behavior.

**Comment by malaxiaolongxia** [comment]
Here is my test code,when i run it , it never print ok and always wait expected response
```public class MysqlClientTest {
    public static void main(String[] args) {
        MySQLClient mySQLClient = new MySQLClient(2103316, "xxxx", 3306, "mall_test_m_rw", "mall_test_m_rw");
        mySQLClient.connect();
        mySQLClient.subscribe("mariadb-bin.000617", 790748916);
        System.out.println("ok");
    }
}
`show variables like '%server_id%';` then value is 2103316
`show master status;` then value is mariadb-bin.000617   790748916``

**Comment by avalon5666** [comment]
It seem you are using mariadb, scaling only test by mysql.

**Comment by KomachiSion** [comment]
Theoretically, the protocol between mysql and mariadb should be the same. 
The reason why it cannot be connected may be the error caused by the difference in the configuration of `abilities`. Need to be checked in detail.

**Comment by ssxlulu** [comment]
Can you provide TCP packet for further information?

**Comment by malaxiaolongxia** [comment]
Today I installed mysql in my test environment then the test code is work,

**Comment by malaxiaolongxia** [comment]
Today I installed mysql in my test environment and the test code worded,It's a little different than before
- I use mysql instead of mariadb
-  The data is less than before ,mysql has one database and one record while mariadb has about 100 database and 5E records.
Hope to resolve the issue

**Comment by avalon5666** [comment]
It can work normally in mariadb 10.1. Pls provide tcp dump or mariadb version.

**Comment by Lucas-307** [comment]
@malaxiaolongxia Maybe you can try any other server_id to new MySQLClient.
`show variables like '%server_id%';` is select master server_id, MySQLClient is a slave, we don't have to use the same id.

By the way, I tried the same server_id as my master, it still work. So I'm not sure my answer is correct, maybe it also effected by db version.

Just try.

**Comment by terrymanu** [comment]
Closed because of no response anymore
