### ISSUE TITLE
Generated order-by with alias bug

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5486]
In https://github.com/apache/shardingsphere/pull/5485, @EasonYi fix the rewriting bug for group-by alias. But now there is another bug:
> select distinct `a`.`id` from `aa` as `a`

This statement will be rewriting to:
>  select distinct `a`.`id` , `a`.`id` AS ORDER_BY_DERIVED_0 from `aa1` ORDER BY `a`.`id` ASC  as `a`

It occurs an error with a wrong insert position now:
> from `aa1` ORDER BY `a`.`id` ASC  as `a`

Order by clause should be after alias:
> from `aa1` as `a`  ORDER BY `a`.`id` ASC

**Comment by jingshanglu** [comment]
I'll track.
