### ISSUE TITLE
How default database sharding strategy work?

### ISSUE THREAD

**Issue by mawer111** [apache/shardingsphere#5487]
## Question
if not config table rule for tabe A , just set  default database sharding strategy, the default database strategy is work?

my situation： every table sharding in some db, but only some of them sharding in different tables,Is it possible to set a default database sharing strategy for all table？

at the last，Thanks for developer

**Comment by mawer111** [comment]
after read source code,I know DefaultDatasourceShardingStrategy wouldn't work without config table sharding rule
If table a isnt config with a sharding rule,
if config one defaultDatasource name,it will route by SharedingDefaultDatabaseRouting Engine
otherwires,will route by ShardingUnicastRoutingEngine
In ShardingRouteEngineFactory，will create ShardingDefaultDatabaseRoutingEngine ，that's will route to a random datasource in datasource names

**Comment by kimmking** [comment]
DefaultDatasourceShardingStrategy is remove in master now.
Under the design principles, each table that you need to control by shardingsphere,  should be configured in config files.

**Comment by mawer111** [comment]
get this.but in some situation, there are so many table here,maybe design some config to solve under the design principles.
and i think the annotation meta code is a good way to solve config problem.

**Comment by terrymanu** [comment]
@mawer111 Hi, could we close this issue?
