### ISSUE TITLE
Improve unit test coverage of sharding-orchestration

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5489]
The unit test coverage of sharding-orchestration is 77.86% now. We plan to upgrade to 90%+ in the end of May 2020. Here are the subproject less than 90% coverage:
sharding-orchestration 77.86->88.26
1.sharding-orchestration-center 66.49->82.26
- [x] sharding-orchestration-center-api 50.0->92.86 @kimmking 
- [x] sharding-orchestration-center-zookeeper-curator 72.59 @kimmking 
- [x] sharding-orchestration-center-apollo 50.98->96.94 @menghaoranss  
- [x] sharding-orchestration-center-etcd 53.33 @menghaoranss  
- [x] sharding-orchestration-center-nacos 78.0->92.0 @menghaoranss  

2.sharding-orchestration-core 88.07 -> 93.57
- [x] sharding-orchestration-core-common 42.86->85.71 @yu199195 
- [x] sharding-orchestration-core-configcenter 86.78->91.43 @yu199195 

Coverage: https://coveralls.io/github/apache/shardingsphere

**Comment by menghaoranss** [comment]
got it!
