### ISSUE TITLE
COUNT(DISTINCT x1) from table group by x2 return wrong result

### ISSUE THREAD

**Issue by marxy** [apache/shardingsphere#5492]
## Bug Report
SELECT col1, COUNT(DISTINCT col2) FROM tbl_name GROUP BY col1
I find it in document's [support list](https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/#supported-sql-2), but the result of this sql is wrong.
### Which version of ShardingSphere did you use?
4.0.1
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
Logic SQL: SELECT
            col1 AS name,
            COUNT(DISTINCT col2) as num
        from table_name
        group by col1 

### Actual behavior
Actual SQL: ds0 ::: SELECT
            DISTINCT col1 AS name,
            col2 as num
        from table_name_0
        group by col1 ORDER BY col1 ASC 

Actual SQL: ds0 ::: SELECT
            DISTINCT col1 AS name,
            col2 as num
        from table_name_1
        group by col1 ORDER BY col1 ASC 

### Reason analyze (If you can)
In mysql,  the sql "select DISTINCT col1,col2  group by col1" always return one row with each group by colunm, so the aggregated result of num is wrong.

**Comment by kimmking** [comment]
That doesn't support disctinct column is different with group by column.

**Comment by wosniuxx** [comment]
Same problem +1
Could has plan with it?

**Comment by strongduanmu** [comment]
@wosniuxx You can try the latest master branch, it has been supported now.

**Comment by williamXinCC** [comment]
@strongduanmu Hi, which version can be support?sharding-jdbc-4.1.1?

**Comment by strongduanmu** [comment]
@williamXinCC You can try ShardingSphere 5.1.2.
