### ISSUE TITLE
SqlServer IndexMetaData name is null

### ISSUE THREAD

**Issue by mawer111** [apache/shardingsphere#5497]
![20200509172405](https://user-images.githubusercontent.com/9105659/81469871-1659a480-921a-11ea-9db9-820ca1f2bae0.jpg)
code in TableMetaData constructor 
can't see this index in sqlserver console

**Comment by kimmking** [comment]
can you show your sql server ddl and all logs?

**Comment by TaoZhiMLND** [comment]
maybe duplicated with #5421

**Comment by mawer111** [comment]
@TaoZhiMLND 
so how to modify source code? I use maven to manage dependencies.

**Comment by TaoZhiMLND** [comment]
> @TaoZhiMLND
> so how to modify source code? I use maven to manage dependencies.

Which version did you use？

**Comment by mawer111** [comment]
@TaoZhiMLND 
jdbc-core 4.1.0

**Comment by TaoZhiMLND** [comment]
@mawer111  hi, could you please excute 
```call sp_statistics('tableName','schema','catlog','%','N','E')``` 
or ```call sp_statistics_100('tableName','schema','catlog','%','N','E')```
with the actual value of `tableName`, `schema`, `catlog` in your sqlserver console and show the result?
you can see more detail by making some breakpoints  at SQLServerDatabaseMetaData#getIndexInfo and SQLServerDatabaseMetaData.CallableHandles#prepare.
It is helpful to locate the issue, thanks.

**Comment by mawer111** [comment]
![image](https://user-images.githubusercontent.com/9105659/81500993-58f9aa80-9308-11ea-8bfe-21c8be8a894c.png)
every table has a null row...

**Comment by mawer111** [comment]
@TaoZhiMLND 
Just like #5421 , getIndexInfo would return statistics record on SqlServer.
But now question is how to fix it if I use 4.1.0 version import by maven? Any suggestions?

**Comment by terrymanu** [comment]
Please upgrade to 5.x or build form master
