### ISSUE TITLE
URGENT: Broken links on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/shardingsphere#5516]
There are two broken links on the download page:

https://www.apache.org/dyn/closer.cgi?path=shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.asc
https://www.apache.org/dyn/closer.cgi?path=shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.sha512

sigs and hashes must use 
https://downloads.apache.org/shardingsphere/...

**Comment by kimmking** [comment]
@sebbASF

https://downloads.apache.org/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.asc

https://downloads.apache.org/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.sha512

The two files exist. And how to fix the broken links, thx.

**Comment by terrymanu** [comment]
Thank you for reminder. I will fix it ASAP.

**Comment by terrymanu** [comment]
> @sebbASF
> 
> https://downloads.apache.org/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.asc
> 
> https://downloads.apache.org/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz.sha512
> 
> The two files exist. And how to fix the broken links, thx.
> Do you means these links should not with dyn pages?

The problem is the dyn mirror do not sync the sigs and sha, we need to put the original URL here.
