### ISSUE TITLE
Can't build sharding-proxy-backend without sharding-metrics-spi in pom.xml

### ISSUE THREAD

**Issue by hitnewbee** [apache/shardingsphere#5517]
in file:
sharding-proxy/sharding-proxy-backend/src/main/java/org/apache/shardingsphere/shardingproxy/backend/communication/jdbc/execute/JDBCExecuteEngine.java

line 22、23：
`import org.apache.shardingsphere.metrics.enums.MetricsLabelEnum;`
 `import org.apache.shardingsphere.metrics.facade.MetricsTrackerFacade;`
I can't build success until add 
`       <dependency>`
`            <groupId>org.apache.shardingsphere</groupId>`
`            <artifactId>sharding-metrics-spi</artifactId>`
`            <version>${project.version}</version>`
`        </dependency>`

into sharding-proxy/sharding-proxy-backend/pom.xml

**Comment by yu199195** [comment]
please install all

**Comment by kimmking** [comment]
You should mvn clean install in root directory.

**Comment by hitnewbee** [comment]
> You should mvn clean install in root directory.

Build success since run mvn clean, thanks.I will close it
