### ISSUE TITLE
Summary  Buried point information  in Sharding-Metrcis

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#5541]
All the community friends：
  
   We buried point  to Sharding-Proxy，to gather information that can be used。
   now，there are several types of information ：

name|  type | description| 
:-: | :-: | :-: 
request_total | Counter| Collect all request | 
sql_statement | Counter| Collect the types of SQL , example (SELECT,UPDATE,INSERT...)| 
channel_count| Gauge| Collect the number of connections | 
requests_latency| Histogram| Collect the request latency time(ms) | 
sharding_datasource| Counter |  Collect  the sql sharding datasource
sharding_table| Counter |  Collect  the sql sharding table
transaction| Counter |  Collect  the sql transaction
Anything else? You are welcome to join the discussion and contribute your good ideas.

**Comment by SanmuWangZJU** [comment]
Metrics of HikariDataSource may be useful

**Comment by yu199195** [comment]
@SanmuWangZJU   our metrics  Different from the HikariDataSource metrics

**Comment by yanyzy** [comment]
I think we can add some metrics according to different modules.
For example ，in shadow module

| name | type | description |
|  ----  | ----  |  ----  |
| shadow_hit_total | Counter | Collect the number of times hit the shadow database |
| shadow_route_latency | Histogram | Collect the route latency time for shadow (ms) |
| shadow_rewrite_latency | Histogram | Collect the rewrite latency time for shadow (ms) |

**Comment by yu199195** [comment]
@yanyzy good idea,you can contribute it
