### ISSUE TITLE
Use "no" as shardingColumn is expired when update

### ISSUE THREAD

**Issue by Mango-Hu** [apache/shardingsphere#5542]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
3.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
 Use "no" as shardingColumn can Hit  shard key  when update
### Actual behavior
The shard key is expired when update
### Reason analyze (If you can)
1. use "no" when select is Effective
2."no" is one of the DefaultKeyWord
3. when parseExpression 
column:"no"   
      lexer.getCurrentToken().getType() = "DefaultKeyWord"
      lexer.getCurrentToken().getLiterals() = "no"
another column: "process_status"
      lexer.getCurrentToken().getType() = "Literals"
      lexer.getCurrentToken().getLiterals() = "process_status"
4. after parseExpression
column:"no" 
      SQLExpression =  SQLIgnoreExpression
another column: "process_status"
      SQLExpression =  SQLIdentifierExpression
5.  route is expired when use "no" as shardingColumn to update
      
          

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL:  UPDATE t_adb_change_owner_order
         SET appended_quantity = appended_quantity + ?,
            
            
                gmt_modify = ? 
        WHERE no = ?
        AND process_status = 1
        AND is_deleted = 0

shardingRule:
   tables:
   t_adb_change_owner_order:
      actualDataNodes: ds$->{0..7}.t_adb_change_owner_order
      databaseStrategy:
        inline:
          shardingColumn: no
          algorithmExpression: ds$->{Math.abs(no.hashCode() % 8)}

**Comment by terrymanu** [comment]
Version 3.x is out of service, please try new version.
