### ISSUE TITLE
Documents about orchestration of 4.x should be updated

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#5568]
Since the orchestraion configuration structure has been restructured in the version 4.1.0，there are several documents about orchestration should be updated:

- [x] User Manual/Sharding-JDBC/Manual/Orchestration/Rule Configuration Based on Java
- [x] User Manual/Sharding-JDBC/Manual/Orchestration/Rule Configuration Based on Yaml
- [x] User Manual/Sharding-JDBC/Manual/Orchestration/Rule Configuration Based on Spring Boot
- [x] User Manual/Sharding-JDBC/Manual/Orchestration/Rule Configuration Based on Spring Name Space
- [x] User Manual/Sharding-JDBC/Configuration manual/Java Configuration/Orchestration
- [x] User Manual/Sharding-JDBC/Configuration manual/Yaml Configuration/Orchestration
- [x] User Manual/Sharding-JDBC/Configuration manual/Spring Boot Configuration/Orchestration
- [x] User Manual/Sharding-JDBC/Configuration manual/Spring Namespace/Orchestration
- [x] Concepts&Features/Orchestration/ConfigCenter/Data Structure in Configuration Center/ config/schema/schemeName/datasource

**Comment by kimmking** [comment]
Anyone could be pick your favorite task to submit pr to dev4.x
