### ISSUE TITLE
为什么sql要加上“;”啊，导致执行过错误。ORA-00933: SQL 命令未正确结束

### ISSUE THREAD

**Issue by 15168326318** [apache/shardingsphere#5581]
private static String generateEmptyResultSQL(String table, String databaseType) {
        String delimiterLeft;
        String delimiterRight;
        if (!"MySQL".equals(databaseType) && !"MariaDB".equals(databaseType)) {
            if (!"Oracle".equals(databaseType) && !"PostgreSQL".equals(databaseType) && !"H2".equals(databaseType) && !"SQL92".equals(databaseType)) {
                if ("SQLServer".equals(databaseType)) {
                    delimiterLeft = "[";
                    delimiterRight = "]";
                } else {
                    delimiterLeft = "";
                    delimiterRight = "";
                }
            } else {
                delimiterLeft = "\"";
                delimiterRight = "\"";
            }
        } else {
            delimiterLeft = "`";
            delimiterRight = "`";
        }

        return "SELECT * FROM " + delimiterLeft + table + delimiterRight + " WHERE 1 != 1;";

为什么sql要加上“;”啊，导致执行过错误。

异常信息：

Error : 933, Position : 47, Sql = SELECT * FROM "AUDIOLOGY_ITEM_REC" WHERE 1 != 1;, OriginalSql = SELECT * FROM "AUDIOLOGY_ITEM_REC" WHERE 1 != 1;, Error Msg = ORA-00933: SQL 命令未正确结束

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
