### ISSUE TITLE
Linux deployment, the proxy return unintelligible codes  when the database content is in Chinese or SQL has Chinese characters

### ISSUE THREAD

**Issue by psh882003** [apache/shardingsphere#5592]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by kimmking** [comment]
what do you means?

**Comment by psh882003** [comment]
sharing-proxy 中文乱码问题



psh882003@163.com 
13718105180
 
From: kimmking
Date: 2020-05-14 11:47
To: apache/shardingsphere
CC: psh882003; Author
Subject: Re: [apache/shardingsphere] Linux deployment, the proxy return when the database content is in Chinese or SQL has Chinese time code (#5592)
what do you means?

**Comment by psh882003** [comment]
Linux 部署， 当数据库内容为中文时 或者sql中带有中文时乱码



psh882003@163.com 
13718105180
 
From: kimmking
Date: 2020-05-14 11:47
To: apache/shardingsphere
CC: psh882003; Author
Subject: Re: [apache/shardingsphere] Linux deployment, the proxy return when the database content is in Chinese or SQL has Chinese time code (#5592)
what do you means?

**Comment by psh882003** [comment]
sharing-proxy 中文乱码问题




psh882003@163.com 
 
From: kimmking
Date: 2020-05-14 11:47
To: apache/shardingsphere
CC: psh882003; Author
Subject: Re: [apache/shardingsphere] Linux deployment, the proxy return when the database content is in Chinese or SQL has Chinese time code (#5592)
what do you means?

**Comment by psh882003** [comment]
sharing-proxy 中文乱码问题

**Comment by terrymanu** [comment]
Can you provide more details?

**Comment by terrymanu** [comment]
Closed because of no response anymore
