### ISSUE TITLE
[Refactoring] New architecture of runtime context for Sharding Proxy and JDBC

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5593]
Hi folks,

There is a significant change for release 5.x need to be public to our community. 
To get a consistent and straightforward orchestration function for both of Sharding Proxy and Sharding JDBC, we extracted the joint members from them, which will be passed down to `shardingsphere-underlying` module. Based on that, orchestration engine could function simply and uniformly.

A todo list is appended here.
- [x] Remove cache from Sharding Parser
- [x] Call the `clear()` of Sharding Parser when needed
- [x] Exact joint members from Sharding Proxy and JDBC to group into a new new `SchemaContext`
- [x] Pass a list of `SchemaContext` named `SchemaContexts` to `shardingsphere-underlying`
- [ ] Refactor the behaviors of `orchestration`

Here is the view of the new structure and relationships of related classes.
![image](https://user-images.githubusercontent.com/27757146/81891558-4c60a500-95db-11ea-8654-1c6a2a191cff.png)

**Comment by kimmking** [comment]
Based on this new architecture, shardingsphere will go further and evolve to a new epoch.
