### ISSUE TITLE
Can not update sharding key,

### ISSUE THREAD

**Issue by wei442** [apache/shardingsphere#5596]
## Bug Report
error
Cause: org.apache.shardingsphere.core.exception.ShardingException: Can not update sharding key, logic table: [user_account], column: [org.apache.shardingsphere.sql.parser.sql.segment.dml.assignment.AssignmentSegment@dc9eb6e].

config
spring.shardingsphere.sharding.tables.user_account.actual-data-nodes=master.user_account_$->{0..2}
spring.shardingsphere.sharding.tables.user_account.table-strategy.inline.sharding-column=user_id
spring.shardingsphere.sharding.tables.user_account.table-strategy.inline.algorithm-expression=user_account_$->{user_id % 3}

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by kimmking** [comment]
English only,
And need more details.

**Comment by wei442** [comment]
error
Cause: org.apache.shardingsphere.core.exception.ShardingException: Can not update sharding key, logic table: [user_account], column: [org.apache.shardingsphere.sql.parser.sql.segment.dml.assignment.AssignmentSegment@dc9eb6e].

config
spring.shardingsphere.sharding.tables.user_account.actual-data-nodes=master.user_account_$->{0..2}
spring.shardingsphere.sharding.tables.user_account.table-strategy.inline.sharding-column=user_id
spring.shardingsphere.sharding.tables.user_account.table-strategy.inline.algorithm-expression=user_account_$->{user_id % 3}

How to deal with it ？

**Comment by terrymanu** [comment]
Just like you said, we do not support update sharding key

**Comment by wanghaichao2195** [comment]
I have this issue today, but I'm 100 percent sure the sharding key is the same (in my case is "uid"), but in ShardingUpdateStatementValidator, 
the "shardingColumnSetAssignmentValue" is the correct value of uid,
but in 
```java
if (whereSegmentOptional.isPresent()) {
     shardingValue = getShardingValue(whereSegmentOptional.get(), parameters, shardingColumn);
} 
```
the getShardingValue will return empty because the identifier in it is "id" (which is the primary key, not shardingColumn in my table)
![Screen Shot 2020-10-01 at 9 32 09 PM](https://user-images.githubusercontent.com/24919562/94888326-92ed5980-042d-11eb-8a1d-55dd3e1dcf78.png)

**Comment by wanghaichao2195** [comment]
I use version 4.1.1 + springboot + hibernate

**Comment by wanghaichao2195** [comment]
yaml config:
rules:
      sharding:
        default-table-strategy:
          standard:
            sharding-column: uid
            precise-algorithm-class-name: xxxxxxxxxxxxx
        tables:
          user_info_A:
            actual-data-nodes: xxxx.user_info_A_$->{0..${db.sharding.table.maxnumber}}
          user_info_B:
            actual-data-nodes: xxxx.user_info_B_$->{0..${db.sharding.table.maxnumber}}

```java
@Table(name = "user_info_A")
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
public class UserInfo implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "uid", nullable = false)
    private String uid;

    @Column(name = "out_uid", nullable = false)
    private String outUid = "";
    
    xxxxxxxxxxxxxxx

```

I can save(insert) or query just fine, but I can't update. 
I just query out a row and change just one attribute, and save(update) will throw "Can not update sharding key" Exception

**Comment by 2602351188** [comment]
I have the same err

**Comment by pachuang** [comment]
反正就是不支持
