### ISSUE TITLE
proxy4.1.0 sql:"SHOW FULL TABLES FROM `sharding_db` LIKE 't_table'   " return null

### ISSUE THREAD

**Issue by wangjing112** [apache/shardingsphere#5608]
when exec sql:SHOW FULL TABLES FROM `sharding_db`
return:
t_table BASE TABLE

but exec sql:SHOW FULL TABLES FROM `sharding_db` LIKE 't_table' 
return null

**Comment by xbkaishui** [comment]
please assign to me. I want have try

**Comment by RaigorJiang** [comment]
I have tested the current master branch(ab45b9db on 12/24/20 at 12:26 AM) and there is no problem. 
This issue can be closed.
