### ISSUE TITLE
proxy4.1.0 create table not sharding.

### ISSUE THREAD

**Issue by wangjing112** [apache/shardingsphere#5609]
cfg:

```yaml
    t_role_shop: 
      actualDataNodes: r_game_sub${0..1}.t_role_shop${0..2}

  defaultDataSourceName: r_sub0
  defaultDatabaseStrategy:
    standard:
      shardingColumn: roleId
      preciseAlgorithmClassName: com.cg.raid.db.sharding.PreciseShardingDatabaseAlgorithm
      rangeAlgorithmClassName: com.cg.raid.db.sharding.RangeShardingDatabaseAlgorithm
  defaultTableStrategy:
    standard:
      shardingColumn: roleId
      preciseAlgorithmClassName: com.cg.raid.db.sharding.PreciseShardingTableAlgorithm
      rangeAlgorithmClassName: com.cg.raid.db.sharding.RangeShardingTableAlgorithm
```

log:

```
[INFO ] 18:47:32.889 [ShardingSphere-Command-11] ShardingSphere-SQL - Logic SQL: create table t_role_shop (roleId bigint not null, shopId integer not null, awakeEndTime bigint, awakeStatus integer, buyAmount int(11) default 0, buyTimes integer, goodsData varchar(20000), reflashTimes integer, resetTime bigint, status integer, type integer, primary key (roleId, shopId)) ENGINE=InnoDB
[INFO ] 18:47:32.889 [ShardingSphere-Command-11] ShardingSphere-SQL - SQLStatement: CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.ddl.CreateTableStatement@3353d4ea, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@61b88403)
[INFO ] 18:47:32.889 [ShardingSphere-Command-11] ShardingSphere-SQL - Actual SQL: r_sub0 ::: create table t_role_shop (roleId bigint not null, shopId integer not null, awakeEndTime bigint, awakeStatus integer, buyAmount int(11) default 0, buyTimes integer, goodsData varchar(20000), reflashTimes integer, resetTime bigint, status integer, type integer, primary key (roleId, shopId)) ENGINE=InnoDB
```

the same config is work fine in sharding-jdbc4.0.0

**Comment by wangjing112** [comment]
select not sharding too.
`
[INFO ] 20:07:49.051 [ShardingSphere-Command-5] ShardingSphere-SQL - Logic SQL: /* ApplicationName=DBeaver 7.0.0 - SQLEditor <Script-7.sql> */ select * from t_role_shop where roleId = 36030446286408251
LIMIT 0, 200
[INFO ] 20:07:49.051 [ShardingSphere-Command-5] ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@55477531, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@5ebefa40), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@5ebefa40, projectionsContext=ProjectionsContext(startIndex=70, stopIndex=70, distinctRow=false, projections=[ShorthandProjection(owner=Optional.empty, actualColumns=[])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@fccbed0, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@40ce5af8, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@2ece412d, containsSubquery=false)
[INFO ] 20:07:49.051 [ShardingSphere-Command-5] ShardingSphere-SQL - Actual SQL: r_game_sub0 ::: /* ApplicationName=DBeaver 7.0.0 - SQLEditor <Script-7.sql> */ select * from t_role_shop where roleId = 36030446286408251
`

**Comment by wangjing112** [comment]
the actualColumns=[] is empty?
in mysql table:
![image](https://user-images.githubusercontent.com/51982240/81935088-a5076080-9622-11ea-8119-e89fe0124f07.png)

**Comment by kimmking** [comment]
you can try "shardingColumn: roleId" instead of "shardingColumn: roleid" in lower case.

**Comment by wangjing112** [comment]
> you can try "shardingColumn: roleId" instead of "shardingColumn: roleid" in lower case.

use roleid same error.

but same config is run very good on sharding-jdbc4.0.0

i found on proxy4.1.0 same table is work good same not sharding,but i not find out what wrong with is.

**Comment by wangjing112** [comment]
what mean this log:
`
[INFO ] 14:12:17.543 [main] ShardingSphere-metadata - Loading 7 logic tables' meta data.
[INFO ] 14:12:17.693 [main] ShardingSphere-metadata - Loading 61 tables' meta data.
`

**Comment by tristaZero** [comment]
@wangjing112 Hi How about this issue now? How did you do to get out of this issue?

**Comment by tristaZero** [comment]
@wangjing112 I will close it tomorrow If there is still no any feedback. Thanksx

**Comment by tristaZero** [comment]
No feedback until now, so we have to close it.
