### ISSUE TITLE
how do you guys  improve performance of parsing SQL at first time  in the version 4.1.0 ?by upgrading the version of antlr4 to 4.7.2?

### ISSUE THREAD

**Issue by qhj348770376** [apache/shardingsphere#5611]
how do you guys  improve performance of parsing SQL at first time  in the version 4.1.0?by upgrading the version of antlr4 to 4.7.2?  

@tuohai666   #2793 #5313

**Comment by terrymanu** [comment]
We use two phase parse(LL and SLL) to improve performance.

**Comment by qhj348770376** [comment]
> We use two phase parse(LL and SLL) to improve performance.

Have you done performance testing? How much performance has been improved? Our production environment test is still very slow to parse SQL for the first time at version 4.1.0

**Comment by tuohai666** [comment]
> Have you done performance testing? How much performance has been improved? 

Yes. About 100 ~ 1000 times faster for long SQL.

How do you judge the slow part is parse? And what the SQL it is?

**Comment by qhj348770376** [comment]
> > Have you done performance testing? How much performance has been improved?
> 
> Yes. About 100 ~ 1000 times faster for long SQL.
> 
> How do you judge the slow part is parse? And what the SQL it is?

SQL：select * from group_strategy where id=？
first time cost 1210ms and second time 4ms
@tuohai666

**Comment by tuohai666** [comment]
You didn't answer my question: **How do you judge the slow part is parse?** 

You are using a sharding-proxy or sharding-jdbc?

**Comment by tuohai666** [comment]
Expired.

**Comment by qhj348770376** [comment]
> You didn't answer my question: **How do you judge the slow part is parse?**
> 
> You are using a sharding-proxy or sharding-jdbc?

![image](https://user-images.githubusercontent.com/15116585/82968329-a6139700-9fff-11ea-95ef-23837f924875.png)
1、As can be seen from the screenshot, most of the performance loss is in SQL parsing
2、sharding-jdbc 4.1.0

From the list of historical issues, it can be found that the service timeout or slow response caused by the first analysis of SQL performance problems is a very clear problem. Other companies have the same problem. I think the official should not avoid this problem. It should be taken seriously. Help us solve this problem.
If there are thousands of service QPS and hundreds of different SQL statements are parsed at the same time, this problem can be reproduced stably. And the official cache solution does not solve this kind of problem, the cache can only improve the resolution performance for the second time and later,not the first time . #2793 #5313
please!!!
@terrymanu @tuohai666

**Comment by tuohai666** [comment]
I thought you would provide the 1210ms log. Why 39ms this  time?
Please show me the trace from the entry of your code.
What's the hardware environment of your machine?

**Comment by qhj348770376** [comment]
OK，I let the business department sort out the relevant debugging information
