### ISSUE TITLE
The event notice-board of the community

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5659]
Hi fellows,

This is an event notice-board of Apache ShardingSphere community, where you could learn the latest news of activities or events, including the DateTime, participating way, guest speaker, and so on. Please be free to leave your comments! 😉 

**Welcome your attention and joining!** 😀

**Comment by tristaZero** [comment]
![WechatIMG151](https://user-images.githubusercontent.com/27757146/82143623-c57c2880-9877-11ea-895f-6db08ed36eb5.jpeg)

**Comment by kimmking** [comment]
Ten thousands applause and flowers for @tristaZero .

**Comment by menghaoranss** [comment]
Looking forward~~

**Comment by yu199195** [comment]
Looking forward

**Comment by tristaZero** [comment]
> Ten thousands applause and flowers for @tristaZero .

Thanks @kimmking 
I hear that there is another presentation presented by you. If we can take part in, a comment of its information is welcomed here!

**Comment by kimmking** [comment]
> > Ten thousands applause and flowers for @tristaZero .
> 
> Thanks @kimmking
> I hear that there is another presentation presented by you. If we can take part in, a comment of its information is welcomed here!

Roger

**Comment by tristaZero** [comment]
<img width="650" alt="WX20200522-104032@2x" src="https://user-images.githubusercontent.com/27757146/82625845-c961cf00-9c18-11ea-85ad-3932b9c36e95.png">

**Comment by tristaZero** [comment]
![WechatIMG38446](https://user-images.githubusercontent.com/27757146/82810017-04d1f700-9ec0-11ea-99ed-49e2e7b93eb2.jpeg)

**Comment by tristaZero** [comment]
![WechatIMG17](https://user-images.githubusercontent.com/27757146/86330345-2326d180-bc7a-11ea-8f69-aa492f0b790b.jpeg)

**Comment by wubingting** [comment]
![微信图片_20200720103830](https://user-images.githubusercontent.com/49680463/87896563-30fe9400-ca7b-11ea-8aeb-bd0e92b2ee62.png)

**Comment by wubingting** [comment]
![image](https://user-images.githubusercontent.com/49680463/89848802-a57bad00-dbb9-11ea-8739-e062c892498b.png)

**Comment by yang-7777** [comment]
![微信图片_20200914104214](https://user-images.githubusercontent.com/67564630/93038257-16116000-f677-11ea-9ee3-bedb46a044ee.jpg)

**Comment by yang-7777** [comment]
![achome_banner](https://user-images.githubusercontent.com/67564630/95551173-d0a93e00-0a3c-11eb-9e9e-403c9b3d6f86.png)
![liang](https://user-images.githubusercontent.com/67564630/95550459-85426000-0a3b-11eb-81cc-88f622ad664a.png)
![pan juan](https://user-images.githubusercontent.com/67564630/95550462-86738d00-0a3b-11eb-829e-c98fb8f721a1.png)
![track](https://user-images.githubusercontent.com/67564630/95550902-49f46100-0a3c-11eb-94b1-1af4dbb0ff23.png)

**Comment by yang-7777** [comment]
![coscon](https://user-images.githubusercontent.com/67564630/96440804-0d461800-123b-11eb-9e6c-93f2eabf3e2e.png)
[Pan Juan](https://www.bagevent.com/event/6840909?aId=1712948)
![juan](https://user-images.githubusercontent.com/67564630/96440810-0fa87200-123b-11eb-8282-2e0a05e36a24.png)
[Zhang Liang](https://www.bagevent.com/event/6840909?aId=1713014)
![liang](https://user-images.githubusercontent.com/67564630/96440813-10410880-123b-11eb-9d38-a091793cebdf.png)

**Comment by yang-7777** [comment]
![微信图片_20201109092321](https://user-images.githubusercontent.com/67564630/98497104-1ba5b380-227e-11eb-9505-a8b876bd35db.jpg)

**Comment by yang-7777** [comment]
[开源软件供应链 2020 峰会 2020年11月14日-15日](https://isrc.iscas.ac.cn/summer2020/#/summitmeeting)
![屏幕截图 2020-11-11 174108](https://user-images.githubusercontent.com/67564630/98795764-89500c00-2445-11eb-83c0-20cde83a93ab.png)

**Comment by yang-7777** [comment]
[直播链接:](https://live.csdn.net/room/ShardingSphere/mBTkAKhT)
![微信图片_20201118145459](https://user-images.githubusercontent.com/67564630/99495918-5a3e1b00-29ae-11eb-8d57-b0f74f81d98c.jpg)

**Comment by wgy8283335** [comment]
Hi @tristaZero, could you put the video links of these meetings or sharing sessions in this issue?
Because some videos are hard to be found.

**Comment by tristaZero** [comment]
@wgy8283335 ,

I will follow your suggestion for our later activities.

**Comment by tristaZero** [comment]
![WechatIMG48](https://user-images.githubusercontent.com/27757146/110890235-9402ab00-832a-11eb-8bbc-0e9a87a2776c.jpeg)

**Comment by taojintianxia** [comment]
![image](https://user-images.githubusercontent.com/4112856/131943309-def2cb53-4fb8-42c3-984c-0a7640377296.png)
