### ISSUE TITLE
Sharding-Proxy 'java.lang.ClassNotFoundException'

### ISSUE THREAD

**Issue by cws1981** [apache/shardingsphere#5667]
## Question
**Sharding-Proxy**
I Volume the directory  to /opt/sharding-proxy/ext-lib for user-defined sharding strategy, but even report 'java.lang.ClassNotFoundException' . below is the cmd
` docker run -d -v /opt/sharding-proxy/conf:/opt/sharding-proxy/conf -v /opt/sharding-proxy/lib:/opt/sharding-proxy/ext-lib -p13308:3308 apache/sharding-proxy:latest`

**Comment by menghaoranss** [comment]
@cws1981 Could you provide any more information?

**Comment by terrymanu** [comment]
Can you change the title for search friendly?

**Comment by terrymanu** [comment]
Closed by no response anymore
