### ISSUE TITLE
Daily community promotion

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5680]
### Introduction
It is necessary to summarize all the published articles and put them on all our columns or channels, which will help users or anyone interested in us learn more. Besides, to listen to users' voice is needed as well by questionnaire.
    
### Tasklist
- [x] 1 Translate and edit some of the articles in English, which are supposed to publish on [Blog section](https://github.com/apache/shardingsphere/tree/master/docs/blog/content/material) (Offer with a comment below).
- [x] 2 Synchronize other channels with articles from WeChat public account.
- [x] 3 User survey.

### Knowledge required
1. Markdown
2. Hugo
3. Engish skill
4. [Questionair](https://www.wjx.cn)
5. [Apache ShardingSphere Blog](https://github.com/apache/shardingsphere/tree/master/docs/blog/content/material)

**Comment by tristaZero** [comment]
[Graduation](https://shardingsphere.apache.org/blog/cn/material/graduate/) is the best one for our first translation.

**Comment by wubingting** [comment]
ok!
