### ISSUE TITLE
A complementary configuration for sharding-scaling

### ISSUE THREAD

**Issue by ssxlulu** [apache/shardingsphere#5681]
We will supply a complementary  configuration for sharding-scaling for first using to migrate data from  previous databases to shardingsphere.
The complementary configuration shows like:
```
{
  "ruleConfiguration": {
    "sourceDatasource": [
      {
        "password": "123456",
        "url": "jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=UTC&useSSL=false",
        "username": "root",
        "table": "test1"
      },
      {
        "password": "123456",
        "url": "jdbc:mysql://127.0.0.1:3306/db2?serverTimezone=UTC&useSSL=false",
        "username": "root",
        "table": "test2"
      }
    ],
    "destinationDataSources": 
      {
        "password": "123456",
        "url": "jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=false",
        "username": "root",
      }
  },
  "jobConfiguration": {
    "concurrency": 3
  }
}
```
I think it is more readable for the people who is first use sharding-scaling for data migration from  previous databases to shardingsphere.

**Comment by avalon5666** [comment]
Can we add field to distinguish source and destination component？
For source, there has jdbc and shardingsphere configuration, the destination is the same as.

**Comment by kimmking** [comment]
IMO，this config should be generated automatically.

**Comment by Lucas-307** [comment]
After use elastic-job, we will reconstructor this config.
