### ISSUE TITLE
ShardingSphere-Scaling Mysql datasource checker is incomplete

### ISSUE THREAD

**Issue by Lucas-307** [apache/shardingsphere#5688]
As a mysql slave, we should have `SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.*`  privileges.
Current code only check `SELECT` and `REPLICATION CLIENT` privileges, it's not enough.

And we also should check some database variables(such as if binlog is open).

**Comment by kimmking** [comment]
Can you make a pr to improve it.

**Comment by Lucas-307** [comment]
@kimmking sure.
