### ISSUE TITLE
InlineShardingAlgorithm add property LogicTableName

### ISSUE THREAD

**Issue by wangjing112** [apache/shardingsphere#5710]
in most time table's sharding rule is same like:

`
  defaultTableStrategy:
    standard:
      shardingColumn: id
      shardingAlgorithm: 
        type: INLINE
        props:
          algorithm.expression: ${LogicTableName}${id % 2}

`

so if algorithm.expression include LogicTableName ,most of table can use defaultTableStrategy 

just add code in InlineShardingAlgorithm like this:
`

    @Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Comparable<?>> shardingValue) {
        Preconditions.checkNotNull(properties.get(ALGORITHM_EXPRESSION), "Inline sharding algorithm expression cannot be null.");
        String algorithmExpression = InlineExpressionParser.handlePlaceHolder(properties.get(ALGORITHM_EXPRESSION).toString().trim());
        Closure<?> closure = new InlineExpressionParser(algorithmExpression).evaluateClosure();
        Closure<?> result = closure.rehydrate(new Expando(), null, null);
        result.setResolveStrategy(Closure.DELEGATE_ONLY);
        result.setProperty(shardingValue.getColumnName(), shardingValue.getValue());
        result.setProperty("LogicTableName", shardingValue.getLogicTableName());
        return result.call().toString();
    }
`

**Comment by kimmking** [comment]
Thanks for your suggestion, but IMO it's unneccessary now.
