### ISSUE TITLE
Are lower, trim and other methods and case... when... and other statements not supported in SQL?

### ISSUE THREAD

**Issue by hhj-cmd** [apache/shardingsphere#5714]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by kimmking** [comment]
English only.
