### ISSUE TITLE
The int(or bigint) value is null, but jpa with shardingsphere-jdbc returns zero.

### ISSUE THREAD

**Issue by shooray** [apache/shardingsphere#5727]
## Bug Report

We use springboot & jpa to read records from MySQL 5.6.x. 
There are several tables sharding by shardingsphere-jdbc with monthly strategy.
Some int(or bigint) fields is nullable, and its value is NULL as well. When the record is read by JPA methods such as findAll(), the Integer(or Long) fields with null returns zero.

I consider that is a bug, because other non-sharding tables can correctly return null value.
I reported this bug because zero and null value have different meanings. 

===
We found the cause of zero value. 
org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.java
It define some methods as below:
```java
    @Override
    public int getInt(final int columnIndex) throws SQLException {
        return (int) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, int.class), int.class);
    }
    
    @Override
    public int getInt(final String columnLabel) throws SQLException {
        int columnIndex = columnLabelAndIndexMap.get(columnLabel);
        return (int) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, int.class), int.class);
    }
    
    @Override
    public long getLong(final int columnIndex) throws SQLException {
        return (long) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, long.class), long.class);
    }
    
    @Override
    public long getLong(final String columnLabel) throws SQLException {
        int columnIndex = columnLabelAndIndexMap.get(columnLabel);
        return (long) ResultSetUtil.convertValue(mergeResultSet.getValue(columnIndex, long.class), long.class);
    }
```
every method returns basic variable type such as boolean, int, long ...
and in the org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ResultSetUtil.java
convertNullValue(convertType) convert null value to basic value.

```java
    private static Object convertNullValue(final Class<?> convertType) {
        switch (convertType.getName()) {
            case "boolean":
                return false;
            case "byte":
                return (byte) 0;
            case "short":
                return (short) 0;
            case "int":
                return 0;
            case "long":
                return 0L;
            case "float":
                return 0F;
            case "double":
                return 0D;
            default:
                return null;
        }
    }
```
I don't know why it should be handled in this way.
Could you please change its return value to an object such as Boolean, Integer, Long ...?

**Comment by kimmking** [comment]
Hi, @shooray 
We can't modify this method return type, case it defined by JDBC(java.sql.ResultSet):

```
/**
     * Retrieves the value of the designated column in the current row
     * of this <code>ResultSet</code> object as
     * an <code>int</code> in the Java programming language.
     *
     * @param columnIndex the first column is 1, the second is 2, ...
     * @return the column value; if the value is SQL <code>NULL</code>, the
     * value returned is <code>0</code>
     * @exception SQLException if the columnIndex is not valid;
     * if a database access error occurs or this method is
     *            called on a closed result set
     */
    int getInt(int columnIndex) throws SQLException;

    /**
     * Retrieves the value of the designated column in the current row
     * of this <code>ResultSet</code> object as
     * a <code>long</code> in the Java programming language.
     *
     * @param columnIndex the first column is 1, the second is 2, ...
     * @return the column value; if the value is SQL <code>NULL</code>, the
     * value returned is <code>0</code>
     * @exception SQLException if the columnIndex is not valid;
     * if a database access error occurs or this method is
     *            called on a closed result set
     */
    long getLong(int columnIndex) throws SQLException;
```

**Comment by shooray** [comment]
Hi kimmking. I don't quite agree with you.
First of all, the value of the field is NULL and 0 have different meanings. Secondly, defining the object type and basic type in the Entity class also has different meanings. JPA and some ORMs can correctly handle basic types and object types. As the underlying facilities of the sub-library and table, the original data should also be kept.
Yesterday I suggest you to modify
org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.java
public long getLong (final int columnIndex) throws SQLException;
The return value of Long is indeed wrong.

But can it be used first when processing data
java.sql.ResultSet
of
Object getObject (String paramString);
Method to receive data, if it is null, it returns null. If not null, then return the value of the basic type?

**Comment by kimmking** [comment]
Partiallly agree with you about that getObject can return null.
In another hand, you can't modify the method return type with long or int.

So, check an int field is null via getObject or rs.wasNull to be a better way.
And now, Can you try to fix it?

**Comment by tuohai666** [comment]
Closed because of no response anymore.

Actually, I don't think your description makes sense.

Of course, Null and 0 have diffenent meanings in database. But they have same meaning out of database. If you got a Null from JDBC, it is 0, vice versa. In other words, if you treat the result as a int , it is 0, while you treat it as an object, it is Null, it depends on you.

Besides, Iet's make sure we get the consensus on Null is not 'Null'.

**Comment by pengliu1tw** [comment]
> Hi @kimmking . I don't quite agree with you. First of all, the value of the field is NULL and 0 have different meanings. Secondly, defining the object type and basic type in the Entity class also has different meanings. JPA and some ORMs can correctly handle basic types and object types. As the underlying facilities of the sub-library and table, the original data should also be kept. Yesterday I suggest you to modify org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.java public long getLong (final int columnIndex) throws SQLException; The return value of Long is indeed wrong.
> 
> But can it be used first when processing data java.sql.ResultSet of Object getObject (String paramString); Method to receive data, if it is null, it returns null. If not null, then return the value of the basic type?

hi，do you fix the problem now? We are facing the same problem.

**Comment by pengliu1tw** [comment]
> tables

Hi, @tuohai666 . I think this problem is a bug or at least an underlying problem. I am now introducing shardingsphere into our company's projects and for historical reasons null and 0 has different processes. If shardingsphere don't fix this probleam, it will involve a lot of work to modify our business process logic, which is not acceptable and dangerous. So I hope ss will behave in accordance with other orm-frameworks like hibernate which can return the original value(Null).
