### ISSUE TITLE
Error message is ambiguous when insert with the Shardingvalue is null

### ISSUE THREAD

**Issue by DreamerBear** [apache/shardingsphere#5737]
### Which version of ShardingSphere did you use?
4.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
show appropriate Error message when insert with the Shardingvalue is null

### Actual behavior
Error updating database.  Cause: java.lang.IllegalArgumentException: Sharding value must implements Comparable.

### Reason analyze (If you can)
Source Code in org.apache.shardingsphere.core.route.router.sharding.condition.engine.InsertClauseShardingConditionEngine.java

`Preconditions.checkArgument(result instanceof Comparable, "Sharding value must implements Comparable.");`

=>

`Preconditions.checkNotNull(result, "Sharding value must not be null");`
`Preconditions.checkArgument(result instanceof Comparable, "Sharding value must implements Comparable.");`

**Comment by kimmking** [comment]
can you fix it and submit a pr?

**Comment by terrymanu** [comment]
Closed because nobody interest about this issue.
