### ISSUE TITLE
forced to use the master database when the transaction started in master-slave mode

### ISSUE THREAD

**Issue by mylava** [apache/shardingsphere#5738]
## Question
I want to force the commands in a transaction to be executed in the master database in sharding-proxy.

I see that there is no implementation in the source code (version number: 4.0.0-release)，so，I would like to ask if this feature is implemented in the newer version？

If the newer version doesn't have this feature, I'd like to implement it myself. Do you have any Suggestions?

If I were to expand myself, here's the idea,

If the command is "BeginTransactionStatement",the ” connectionId“ will be records into a cache，for the same connectionId after submission of SQL will be route to Master database to execute，utile the command  this connection committed is "CommitStatement", after this command executed, the ” connectionId“ will be remove from cache.  

That's the general idea,Please give advice or comments,thanks~

**Comment by nevereverever** [comment]
I have the same question.
Master-Slave mode cannot support transaction in proxy.

**Comment by mylava** [comment]
> I have the same question.
> Master-Slave mode cannot support transaction in proxy.

Is it not supported or not implemented？
Are there any problems implementing this functionality?

**Comment by terrymanu** [comment]
Master-Slave mode cannot support transaction
