### ISSUE TITLE
Will the follow-up support dynamically modify the single table's ShardingStrategy at runtime instead of refreshing the entire datasource?

### ISSUE THREAD

**Issue by LFstefan** [apache/shardingsphere#5744]
Will follow-up support dynamically modify ShardingStrategy at runtime?

Now if I want to modify the ShardingStrategy at runtime, I can only implement it in the following way(version: 4.1.0), which is also the way sharding-JDBC-Orchestration uses

`this.dataSource = new ShardingDataSource(this.getChangedDataSources(this.dataSource.getDataSourceMap(), dataSourceConfigurations), (ShardingRule)this.dataSource.getRuntimeContext().getRule(), this.dataSource.getRuntimeContext().getProperties().getProps());`

I think the update granularity in this way is a bit big

In the future, will you provide set methods for these variables at runtime?

`public class ShardingRule implements BaseRule {
     ...
    private final ShardingStrategy defaultDatabaseShardingStrategy;
    private final ShardingStrategy defaultTableShardingStrategy;
    ...
`

**Comment by kimmking** [comment]
You can use orchestration with zookeeper, when config is changed, and sharding-jdbc/proxy will be refresh in time.

**Comment by LFstefan** [comment]
> You can use orchestration with zookeeper, when config is changed, and sharding-jdbc/proxy will be refresh in time.

The implementation of orchestration is to refresh the entire datasource, but all I want is to refresh the ShardingStrategy of a certain modified table。So, will future versions support it

**Comment by kimmking** [comment]
keep ds config is unmodified, and update sharding strategy only via zk.

**Comment by LFstefan** [comment]
> keep ds config is unmodified, and update sharding strategy only via zk.
> there is any side effect for your case?

Because we have some special needs to do this, and we have considered the impact of doing so, just want to know if you can provide such support in the future

**Comment by kimmking** [comment]
there is no plan for it.
