### ISSUE TITLE
sharding-jdbc  slow start

### ISSUE THREAD

**Issue by cws1981** [apache/shardingsphere#5755]
**sharding-jdbc 4.0**
sharding-jdbc load all table metaData when start ,I have more then 600 table so spend too much time when start,can I assign table to load ?

**Comment by yu199195** [comment]
you can not check metadata。

**Comment by cws1981** [comment]
> you can not check metadata。
> 
> 
> 
> 

?

**Comment by yu199195** [comment]
you can config this  in you yaml.
```yml
spring.shardingsphere.check.table.metadata.enabled =false
```

**Comment by liuqiankun93** [comment]
> you can config this in you yaml.
> 
> ```yaml
> spring.shardingsphere.check.table.metadata.enabled =false
> ```
> 
> if not work,you can update version 4.1.0

i also have this problem.My version is 4.1.0.

`check.table.metadata.enabled (?) | boolean | 是否在启动时检查分表元数据一致性，默认值: false`

The config is default false.But there is no effective.

Then i write this code.it still no effective.

`        Properties properties = new Properties();
        properties.setProperty("check.table.metadata.enabled","false");`

The load methed cost many time because my database have more than 500 tables.

**Comment by yu199195** [comment]
@liuqiankun93 
now，we use executerService load table metadata，
you can config this：
```
spring.shardingsphere.max.connections.size.per.query =1  (default 1, changed by you)
```

**Comment by cws1981** [comment]
> @liuqiankun93
> now，we use executerService load table metadata，
> you can config this：
> 
> ```
> spring.shardingsphere.max.connections.size.per.query =1  (default 1, changed by you)
> ```

thanks! could I update to 4.1.0 version?

**Comment by liuqiankun93** [comment]
@yu199195 
`14:33:42.712 [main] INFO org.apache.shardingsphere.core.log.ConfigurationLogger - Properties:
max.connections.size.per.query: '1'
14:33:42.720 [main] INFO ShardingSphere-metadata - Loading 1 logic tables' meta data.
14:33:43.090 [main] INFO ShardingSphere-metadata - Loading 240 tables' meta data.
14:34:38.056 [main] INFO ShardingSphere-metadata - Meta data load finished, cost 55344 milliseconds.`

`14:36:27.783 [main] INFO org.apache.shardingsphere.core.log.ConfigurationLogger - Properties:
max.connections.size.per.query: '1000'
14:36:27.792 [main] INFO ShardingSphere-metadata - Loading 1 logic tables' meta data.
14:36:28.037 [main] INFO ShardingSphere-metadata - Loading 240 tables' meta data.
14:37:02.237 [main] INFO ShardingSphere-metadata - Meta data load finished, cost 34454 milliseconds.`

when i config the max.connections.size.per.query 1000

it still start slow

so i think it need to not check metadata.But there is no effective when i config the check.table.metadata.enabled

`14:41:08.735 [main] INFO org.apache.shardingsphere.core.log.ConfigurationLogger - Properties:
check.table.metadata.enabled: 'false'
14:41:08.744 [main] INFO ShardingSphere-metadata - Loading 1 logic tables' meta data.
14:41:09.005 [main] INFO ShardingSphere-metadata - Loading 240 tables' meta data.
14:42:05.546 [main] INFO ShardingSphere-metadata - Meta data load finished, cost 56810 milliseconds.`

**Comment by cws1981** [comment]
我想最好是 把要分表的表单独放一个scheme 减少表的数量

**Comment by cws1981** [comment]
It is best to have a configuration item that allows me to specify the table for loading metadata

**Comment by cws1981** [comment]
A microservice usually has a dozen tables, but the old monolithic system has hundreds of tables.

**Comment by yu199195** [comment]
@cws1981 
You can try this configuration, if not work,  You can provide us with your table structure data so that we can optimize it
```yaml
spring.shardingsphere.max.connections.size.per.query =50 (or 100)
```

**Comment by cws1981** [comment]
> @cws1981
> You can try this configuration, if not work, You can provide us with your table structure data so that we can optimize it
> 
> ```yaml
> spring.shardingsphere.max.connections.size.per.query =50 (or 100)
> ```

Thank you for your patience, I will try

**Comment by kimmking** [comment]
> > @cws1981
> > You can try this configuration, if not work, You can provide us with your table structure data so that we can optimize it
> > ```yaml
> > spring.shardingsphere.max.connections.size.per.query =50 (or 100)
> > ```
> 
> Thank you for your patience, I will try

I guess it take effect.
If not, you can send us your ddl and we will be profiling and tunning it's loading.

**Comment by cws1981** [comment]
It works, now it is two thirds less than before
`max.connections.size.per.query: '100'`

`20/05/26 11:03:36 INFO RMI TCP Connection(2)-127.0.0.1 ShardingSphere-metadata: Loading 2 logic tables' meta data.
20/05/26 11:03:36 INFO RMI TCP Connection(2)-127.0.0.1 ShardingSphere-metadata: Loading 647 tables' meta data.
20/05/26 11:04:02 INFO RMI TCP Connection(2)-127.0.0.1 ShardingSphere-metadata: Meta data load finished, cost 26610 milliseconds.`

The local test used to take more than 70 seconds, but now only 27 seconds

**Comment by kimmking** [comment]
this option can avoid sharding tables metadata loading:
> spring.shardingsphere.check.table.metadata.enabled =false

this option can parallelly load metadata for all tables:
> pring.shardingsphere.max.connections.size.per.query =50

**Comment by liuqiankun93** [comment]
> this option can avoid sharding tables metadata loading:
> 
> > spring.shardingsphere.check.table.metadata.enabled =false

my version is 4.1.0
I use jdbc config.The code is
`Properties properties = new Properties();
        properties.setProperty("check.table.metadata.enabled","false");
        DataSource dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig,properties);`

and the log is
`16:36:08.105 [main] INFO org.apache.shardingsphere.core.log.ConfigurationLogger - Properties:
check.table.metadata.enabled: 'false'

16:36:08.115 [main] INFO ShardingSphere-metadata - Loading 1 logic tables' meta data.
16:36:08.809 [main] INFO ShardingSphere-metadata - Loading 240 tables' meta data.`

the config It doesn't seem to be working

**Comment by hand515** [comment]
Although I updated the version to 4.1.1,it's still slow, and "check.table.metadata.enabled=false" doesn't work .

**Comment by liuqiankun93** [comment]
@kimmking 
my version is 4.1.0 and hand515‘s version is 4.1.1.
check.table.metadata.enabled=false" doesn't work .

**Comment by tristaZero** [comment]
Hi @cws1981 ,

I am sorry to give my comment late. The good news that the performance of starting ShardingProxy has been greatly improved already! Thanks for @xbkaishui, who took much effort in #6212.

Presently, welcome your any test for the `master branch` (Package it local firstly). Your feedback will be the best gift for the community.

Best,
Trista

**Comment by hermitcai** [comment]
> this option can avoid sharding tables metadata loading:
> 
> > spring.shardingsphere.check.table.metadata.enabled =false
> 
> this option can parallelly load metadata for all tables:
> 
> > spring.shardingsphere.max.connections.size.per.query =50

thanks, fix my problem.
but my config is:
spring.shardingsphere.props.check.table.metadata.enabled = false
spring.shardingsphere.props.max.connections.size.per.query = 5
version is 4.1.1

**Comment by linchuyao** [comment]
i copy TableMetaDataInitializer in project and annotation  result.putAll(loadShardingTables(shardingRule));  result.putAll(loadDefaultTables(shardingRule));
