### ISSUE TITLE
4.1.0 release suck. why can such version been released?

### ISSUE THREAD

**Issue by musarona** [apache/shardingsphere#5761]
another crash.
`Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaData.getIndexes(TableMetaData.java:72)
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaData.<init>(TableMetaData.java:53)
	at org.apache.shardingsphere.sql.parser.binder.metadata.schema.SchemaMetaDataLoader.load(SchemaMetaDataLoader.java:84)`

source code in 4.1.0
`public static Collection<IndexMetaData> load(final Connection connection, final String table) throws SQLException {
        Collection<IndexMetaData> result = new HashSet<>();
        try (ResultSet resultSet = connection.getMetaData().getIndexInfo(connection.getCatalog(), JdbcUtil.getSchema(connection), table, false, false)) {
            while (resultSet.next()) {
                String indexName = resultSet.getString(INDEX_NAME);
                result.add(new IndexMetaData(indexName));
            }
        }
        return result;
    }`

master trunk have fixed the problem。the version was released without any test.

**Comment by terrymanu** [comment]
Hi, it is impolite for the title, So I just close this one. Friendly communicate are always welcomed.

**Comment by kimmking** [comment]
we will fix in 4.1.1 soon.
