### ISSUE TITLE
sharding-orchestration-reg-zookeeper-curator 4.1.0版本是不是没有上传到maven中央库中？

### ISSUE THREAD

**Issue by wwy0201** [apache/shardingsphere#5772]
使用shardingsphere jdbc 准备测试配置中心的时候，发现这个依赖在maven库中最新的是4.0.1，其它的有4.1.0版本

**Comment by LFstefan** [comment]
你可以用 sharding-orchestration-center-zookeeper-curator这个依赖, 我试过可以的, 你说的那个我也没找着(官文上可能旧了还没更新),  后来看4.1.0的源码中没找到对应的模块, 可能他们改名了或者其他

**Comment by wwy0201** [comment]
> 你可以用sharding-orchestration-center-zookeeper-curator这个依赖，我试过可以的，你说的那个我也没找着（官文上可能旧了还没更新），后来看4.1.0的源码中没找到对应的模块，可能他们改名了或者其他
好的，谢谢，我试试看。
因为官网上依赖还是这么写的，所以问问

**Comment by kimmking** [comment]
![image](https://user-images.githubusercontent.com/807508/82779755-98d39c80-9e87-11ea-978f-1f6ab0054458.png)

It's in central repo.

**Comment by wwy0201** [comment]
> ![图片](https://user-images.githubusercontent.com/807508/82779755-98d39c80-9e87-11ea-978f-1f6ab0054458.png)
> 
> 在中央仓库中。
> 您可以从https://maven.aliyun.com/mvn/search搜索[](https://maven.aliyun.com/mvn/search)

看见这个依赖了，但是好像名字改了是吧？
因为之前我是按照官网配置加的pom依赖

**Comment by kimmking** [comment]
it's not renamed.

**Comment by wwy0201** [comment]
> it's not renamed.

thanks！
