### ISSUE TITLE
parse sql suggestion

### ISSUE THREAD

**Issue by prefect1005** [apache/shardingsphere#5773]
if query sql contains "user.id = order.userId" and specify "order.userId = xxx",
at this moment, sql parse by "order.userId = xxx" to confirm table "order" actual query, 
but table "user" don't filter by any condition, that cause full physical table "user" will be query 

whether or not we can parse sql automatic add "user.id = xxx" and the same parameters  in order to reduce the size of query table "user".

**Comment by kimmking** [comment]
If user.id is sharding key, you should explicitly set user.id=1234 to let sql parser know how to shard. A parser don't know a deep calculation such as a=b and b=1234.
