### ISSUE TITLE
Why ResultSet.getNString func is not supported

### ISSUE THREAD

**Issue by zhaolin81** [apache/shardingsphere#5778]
public final String getNString(final int columnIndex) throws SQLException {
    throw new SQLFeatureNotSupportedException("getNString");
}

**Comment by kimmking** [comment]
IMO, the scope of getString contains the getNString.

**Comment by zhaolin81** [comment]
> IMO, the scope of getString contains the getNString.

But i got SQLFeatureNotSupportedException("getNString") when i use mssqlserver to select a column whitch is nvarchar。

So i have to override EncryptResultSet manually like this：

    @Override
    public final String getNString(final int columnIndex) throws SQLException {
        //use getString to support getNString
        return getString(columnIndex);
    }

    @Override
    public final String getNString(final String columnLabel) throws SQLException {
        //use getString to support getNString
        return getString(columnLabel);
    }

**Comment by zhaolin81** [comment]
> IMO, the scope of getString contains the getNString.

I means for example，ibatis will automaticly choose ResultSet.getNString() instead of getString()

**Comment by zhaolin81** [comment]
> > IMO, the scope of getString contains the getNString.
> 
> I means for example，ibatis will automaticly choose ResultSet.getNString() instead of getString()

like this:

; getNString; nested exception is java.sql.SQLFeatureNotSupportedException: getNString] with root cause
java.sql.SQLFeatureNotSupportedException: getNString
	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getNString(AbstractUnsupportedOperationResultSet.java:165)
	at org.apache.ibatis.type.NStringTypeHandler.getNullableResult(NStringTypeHandler.java:37)
	at org.apache.ibatis.type.NStringTypeHandler.getNullableResult(NStringTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)

**Comment by kimmking** [comment]
ibatis make a redundant & unnecessary job here.

**Comment by kimmking** [comment]
Now we know getNString is unnecessary for Oracle&Sqlserver[1].
I found in MySQL-jdbc driver, getNString is wrapping a getString[2], 
In PGSQL-jdbc driver, getNString(int) is not supported, but getNString(String) is wrapping getString too[3].
```
 public String getNString(int columnIndex) throws SQLException {
    connection.getLogger().log(Level.FINEST, "  getNString columnIndex: {0}", columnIndex);
    throw org.postgresql.Driver.notImplemented(this.getClass(), "getNString(int)");
  }

  public String getNString(String columnName) throws SQLException {
    return getNString(findColumn(columnName));
  }
```

So it's the same for all of them(MySQL/PGSQL/SQLServer/Oracle). 
Further more, getNString is added since jdbc-4.0/jdk6, so every jdbc-driver keep it the same of getString to compatible with jdbc-3.0/jdk5.
And then, we can fix it now.

[1].https://kb.kutu66.com/java/post_1436975
[2].https://github.com/mysql/mysql-connector-j/blob/release%2F5.1/src/com/mysql/jdbc/JDBC4ResultSet.java
[3].https://github.com/pgjdbc/pgjdbc/blob/fda4299e1e3b76aa7e0c0031f3e11c61dd05c64b/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L3615

**Comment by zhaolin81** [comment]
> Now we know getNString is unnecessary for Oracle&Sqlserver[1].
> I found in MySQL-jdbc driver, getNString is wrapping a getString[2],
> In PGSQL-jdbc driver, getNString(int) is not supported, but getNString(String) is wrapping getString too[3].
> 
> ```
>  public String getNString(int columnIndex) throws SQLException {
>     connection.getLogger().log(Level.FINEST, "  getNString columnIndex: {0}", columnIndex);
>     throw org.postgresql.Driver.notImplemented(this.getClass(), "getNString(int)");
>   }
> 
>   public String getNString(String columnName) throws SQLException {
>     return getNString(findColumn(columnName));
>   }
> ```
> 
> So it's the same for all of them(MySQL/PGSQL/SQLServer/Oracle).
> Further more, getNString is added since jdbc-4.0/jdk6, so every jdbc-driver keep it the same of getString to compatible with jdbc-3.0/jdk5.
> And then, we can fix it now.
> 
> [1].https://kb.kutu66.com/java/post_1436975
> [2].https://github.com/mysql/mysql-connector-j/blob/release%2F5.1/src/com/mysql/jdbc/JDBC4ResultSet.java
> [3].https://github.com/pgjdbc/pgjdbc/blob/fda4299e1e3b76aa7e0c0031f3e11c61dd05c64b/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L3615

Yes, thanks for reply. 
I think  it's better for sharding-jdbc to supports jdbc4-api like getNString etc.
