### ISSUE TITLE
error in MySQLNullBitmap cause result wrong when more then one NULL fields.

### ISSUE THREAD

**Issue by wangjing112** [apache/shardingsphere#5803]
direct show the wrong code in class:org.apache.shardingsphere.db.protocol.mysql.packet.command.query.binary.execute.MySQLNullBitmap

`

    /**
     * Set null bit.
     *
     * @param index column index
     */
    public void setNullBit(final int index) {
        nullBitmap[getBytePosition(index)] = 1 << getBitPosition(index);
    }
`

in mysql protocal :https://dev.mysql.com/doc/internals/en/null-bitmap.html
`
nulls[byte_pos] |= 1 << bit_pos
`

so the right is:
`

    public void setNullBit(final int index) {
        nullBitmap[getBytePosition(index)] |= 1 << getBitPosition(index);
    }
`

this is reason issue #4707

**Comment by kimmking** [comment]
do you want to fix it?

**Comment by tuohai666** [comment]
@wangjing112  I believe you have spent much time to find the root cause. Thanks for your effort.
