### ISSUE TITLE
Is it functional to use apollo as ConfigCenter

### ISSUE THREAD

**Issue by chenyx7** [apache/shardingsphere#5814]
**release version 4.1.0**

**Is it ok to use apollo as configcenter without any registrycenter ? for the following code, it doesn't works**:

` public ShardingOrchestrationFacade(final OrchestrationConfiguration orchestrationConfig, final Collection<String> shardingSchemaNames) {
        Optional<String> registryCenterName = getInstanceNameByOrchestrationType(orchestrationConfig.getInstanceConfigurationMap(), CenterType.REGISTRY_CENTER.getValue());
        Preconditions.checkArgument(registryCenterName.isPresent(), "Can not find instance configuration with registry center orchestration type.");
       }
`

**Comment by dongzl** [comment]
Hi @chenyx7 , Apollo is only as a ConfigCenter, not for RegistryCenter,  you must use other framework as RegistryCenter, e.g  ZK or etcd.

**Comment by chenyx7** [comment]
> Hi @chenyx7 , Apollo is only as a ConfigCenter, not for RegistryCenter, you must use other framework as RegistryCenter, e.g ZK or etcd.

Thanks @dongzl . So it means , if I use apollo or nacos as ConfigCenter, it is necessary to use another framework as RegistryCenter. And RegistryCenter like zk or etcd, cannot just be replaced by apollo or nacos?

**Comment by dongzl** [comment]
> > Hi @chenyx7 , Apollo is only as a ConfigCenter, not for RegistryCenter, you must use other framework as RegistryCenter, e.g ZK or etcd.
> 
> Thanks @dongzl . So it means , if I use apollo or nacos as ConfigCenter, it is necessary to use another framework as RegistryCenter. And RegistryCenter like zk or etcd, cannot just be replaced by apollo or nacos?

Yes, Apollo or Nacos only use as `ConfigCenter`, they can't instead of ZK and etcd directly.

But ZK and etcd can be used as `ConfigCenter` and `RegistryCenter`.

**Comment by chenyx7** [comment]
> > > Hi @chenyx7 , Apollo is only as a ConfigCenter, not for RegistryCenter, you must use other framework as RegistryCenter, e.g ZK or etcd.
> > 
> > 
> > Thanks @dongzl . So it means , if I use apollo or nacos as ConfigCenter, it is necessary to use another framework as RegistryCenter. And RegistryCenter like zk or etcd, cannot just be replaced by apollo or nacos?
> 
> Yes, Apollo or Nacos only use as `ConfigCenter`, they can't instead of ZK and etcd directly.
> 
> But ZK and etcd can be used as `ConfigCenter` and `RegistryCenter`.

I get it , thanks
