### ISSUE TITLE
datasource route is random when  table config not exist

### ISSUE THREAD

**Issue by songkunming** [apache/shardingsphere#5818]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
 datasource route will Not sure when  table config not exist
pleace check this is reasonable，It is recommended that you either flow out of the extension or report an error directly

**Comment by kimmking** [comment]
what do you means?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
