### ISSUE TITLE
Multi-tenant dynamic processing scheme

### ISSUE THREAD

**Issue by lizhibo0914** [apache/shardingsphere#5823]
Hello, can we pay for the scheme of multi tenant dynamic database creation? How to operate? Is there any actual case?
I want to divide the database dynamically according to the tenants. The tenants are created dynamically through the project, not written in the configuration file. Thank you
中文解释: 
您好, 请问咱们可以支付多租户动态创建数据库的方案吗, 怎么操作, 有实际案例吗?
我是想按照租户去动态进行分库, 租户是通过项目动态创建, 不是写死在配置文件中的, 谢谢

**Comment by kimmking** [comment]
You can use user_id to sharding your tenant to different db/tables dynamically in runtime.

**Comment by lizhibo0914** [comment]
How do you do dynamic sharding? The new database I created was not loaded into the configured dataSource

**Comment by lizhibo0914** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IllegalStateException: Some routed data sources do not belong to configured data sources. routed data sources: `[ds_3]`, configured data sources: `[ds_0, ds_1, ds_2]`
### The error may exist in com/ikeep/account/dao/mapper/account/AccountDao.xml
### The error may involve com.ikeep.account.dao.mapper.account.AccountDao.selectAccountById-Inline
### The error occurred while setting parameters
### SQL: SELECT    subjects_level,    code_length,    cur_period,    start_period,    create_id,    bill_generate,    bill_assist_type_ids   FROM    c_account   WHERE    account_id = ?
### Cause: java.lang.IllegalStateException: Some routed data sources do not belong to configured data sources. routed data sources: `[ds_3]`, configured data sources: `[ds_0, ds_1, ds_2]`

**Comment by kimmking** [comment]
Add a new datasource for new tenants?

IMO, this is a different design. if you want to add a datasource, should reconfig ds&rules via sharding-ui.

**Comment by kimmking** [comment]
can you describe your design for tenants detailly?

**Comment by lizhibo0914** [comment]
The background can add a new tenant whose information is in the general configuration database. The corresponding user database can be created according to the new user information, such as: account_1. When I call the new tenant again, I will dynamically add a new database account_2,Now that I've created it dynamically, I can't load it into the data source

**Comment by lizhibo0914** [comment]
Because I'm created dynamically by a program, I can't do it manually in the UI

**Comment by lemondwm** [comment]
i wanna learn about  how to create database  dynamically and use by sharding-jdbc

**Comment by terrymanu** [comment]
I just label duplicate with #5973, maybe it is time to add a new module for Multi-tenant.

**Comment by lemondwm** [comment]
> I just label duplicate with #5973, maybe it is time to add a new module for Multi-tenant.

Multi-tenant just one situation,actually we need is how to add a data-source in run-time  and let sharding-jdbc can use it.that means add data-source  dynamically
