### ISSUE TITLE
rename module shardingsphere-kernal to shardingsphere-kernel

### ISSUE THREAD

**Issue by ningpp** [apache/shardingsphere#5837]
rename module shardingsphere-kernal to shardingsphere-kernel
rename module shardingsphere-kernal-context to shardingsphere-kernel-context
rename package org.apache.shardingsphere.kernal to org.apache.shardingsphere.kernel

**Comment by tristaZero** [comment]
Hi @ningpp 
Very appreciated your remainder, and welcome join the ShardingSphere community. :-)
