### ISSUE TITLE
make example cover all posibility

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#5841]
### Is your feature request related to a problem?
no

### Describe the feature you would like.
Refactor the example module to cover all usage combinations

Followings are the combinations

<details>
  <summary>sharding-jdbc</summary>

- [ ] sharding
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] master-slave
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] encryption
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] shadow
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] replica
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
</details>
<details>
  <summary>proxy</summary>

- [ ] sharding
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] master-slave
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] encryption
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] shadow
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
- [ ] replica
    - [ ] java
    - [ ] yaml
    - [ ] properties
    - [ ] springboot
    - [ ] spring-namespace
</details>

**Comment by taojintianxia** [comment]
I‘d like to contribute the corresponding code

**Comment by terrymanu** [comment]
expired
