### ISSUE TITLE
Sharding Proxy Registry Center Disable SlaveDB Doesn`t Work！

### ISSUE THREAD

**Issue by Randdon** [apache/shardingsphere#5851]
## registry center forbidden does not work

**environments:**

- mysql:5.7

- shardingproxy:4.1

- zk:3.6.1

I have disabled my **slave_ds_1** through shardingsphere-ui, like this:
![image](https://user-images.githubusercontent.com/52565931/83247105-a82f4e80-a1d5-11ea-9127-c159ee0be0ca.png)
and in zk, the value has been **DISABLED**, like this:
![image](https://user-images.githubusercontent.com/52565931/83247355-fe03f680-a1d5-11ea-98e4-7e4b47c0ec36.png)
but in my springboot project, I called my test interface several times, I found it still find data from the slave_ds_1 that has been forbidden. like this:
![image](https://user-images.githubusercontent.com/52565931/83248300-74edbf00-a1d7-11ea-9f70-370576378c9e.png)
This is ok , that the data find from the alive db, but after I call my test interface several times, the data changed from the db that has been disabled, 
![image](https://user-images.githubusercontent.com/52565931/83248651-fe9d8c80-a1d7-11ea-80fa-68b3f2474e1e.png)
I restart the shardingproxy but the problem still there.
I really dont know why my disable set didn`t work?

this is my server.yaml:
![image](https://user-images.githubusercontent.com/52565931/83249453-2c370580-a1d9-11ea-88bd-56fcb0e53533.png)

this is my confit-mater_slave.yaml:
![image](https://user-images.githubusercontent.com/52565931/83249419-1c1f2600-a1d9-11ea-8a7a-bcf1db50c256.png)

**Comment by dongzl** [comment]
I will test it.

**Comment by dongzl** [comment]
Hi @Randdon , I test your problem, I reproduce this problem on the `4.1.0` version.

But when I test this problem with the latest `master branch` code, It's OK.

Can you compile and try it with the latest code?

**Comment by Randdon** [comment]
> Hi @Randdon , I test your problem, I reproduce this problem on the `4.1.0` version.
> 
> But when I test this problem with the latest `master branch` code, It's OK.
> 
> Can you compile and try it with the latest code?

Thank you for your test and answer.

My sharding-proxy 4.1 and sharding-ui 4.1 are both downloaded from the apache like https://www.apache.org/dyn/closer.cgi/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz

Which molde should I build with the latest `master branch` ? proxy? or the ui ? or both of them?

**Comment by kimmking** [comment]
@dongzl hi, zonglei，we should carry this fix codes to dev4.x for 4.1.1

**Comment by dongzl** [comment]
> > Hi @Randdon , I test your problem, I reproduce this problem on the `4.1.0` version.
> > But when I test this problem with the latest `master branch` code, It's OK.
> > Can you compile and try it with the latest code?
> 
> Thank you for your test and answer.
> 
> My sharding-proxy 4.1 and sharding-ui 4.1 are both downloaded from the apache like https://www.apache.org/dyn/closer.cgi/shardingsphere/shardingsphere-ui-4.1.0/apache-shardingsphere-4.1.0-shardingsphere-ui-bin.tar.gz
> 
> Which molde should I build with the latest `master branch` ? proxy? or the ui ? or both of them?

Hi @Randdon , you can clone `ShardingSphere` repository and build proxy and ui with maven.

**Comment by menghaoranss** [comment]
@dongzl @kimmking @Randdon As our testing and discussion，this issue is same as #5899 , i have fixed in `dev-4.x` branch and will sync to `master` later.
