### ISSUE TITLE
no support sql contain schema

### ISSUE THREAD

**Issue by runbestfast** [apache/shardingsphere#5853]
## Question

sharding-proxy execute  error.
sql："SELECT `ghost_schema`, `ghost_table`, `ddls` FROM dm_meta.`task_tidb_onlineddl` WHERE `id`='7749'" 

######################################
中文：sharding-proxy中执行带scheme的语句报错，有没有什么方法能够执行带有scheme的语句。

**Comment by kimmking** [comment]
the schema must be the logic schema

**Comment by runbestfast** [comment]
I try to use the logic schema.  but client login no execute ‘use database;’,  the question still is existed.

**Comment by terrymanu** [comment]
Do not support SQL that contains schema, for the concept of ShardingSphere is to use multiple data source as one data source, so all the SQL visits are based on one logic schema.

FYI: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/#unsupported-sql
