### ISSUE TITLE
Mysql LengthEncodedInteger read error in class MySQLPacketPayload

### ISSUE THREAD

**Issue by wangjing112** [apache/shardingsphere#5868]
in mysql protocol:
https://dev.mysql.com/doc/internals/en/integer.html#packet-Protocol::LengthEncodedInteger

If it is < 0xfb, treat it as a 1-byte integer.
If it is 0xfc, it is followed by a 2-byte integer.
If it is 0xfd, it is followed by a 3-byte integer.
If it is 0xfe, it is followed by a 8-byte integer.

but in class org.apache.shardingsphere.db.protocol.mysql.payload.MySQLPacketPayload

read 2-byte integer use short ,in java short not Unsigned value in -32768 to 32767.
but  2-byte integer is 0 to 65535.

same as 3-byte integer.

code in MySQLPacketPayload:
'

    public long readIntLenenc() {
        int firstByte = readInt1();
        if (firstByte < 0xfb) {
            return firstByte;
        }
        if (0xfb == firstByte) {
            return 0;
        }
        if (0xfc == firstByte) {
            return byteBuf.readShortLE();
        }
        if (0xfd == firstByte) {
            return byteBuf.readMediumLE();
        }
        return byteBuf.readLongLE();
    }
'

need change to:
'

    public long readIntLenenc() {
        int firstByte = readInt1();
        if (firstByte < 0xfb) {
            return firstByte;
        }
        if (0xfb == firstByte) {
            return 0;
        }
        if (0xfc == firstByte) {
            return 0xFFFF & byteBuf.readShortLE();
        }
        if (0xfd == firstByte) {
            return 0xFFFFFF & byteBuf.readMediumLE();
        }
        return byteBuf.readLongLE();
    }
'

**Comment by tuohai666** [comment]
Why must thest two unsigned?
