### ISSUE TITLE
Sharding 4.1.0 and Spring-boot 2.3.0 incompatible? SQLFeatureNotSupportedException: isValid

### ISSUE THREAD

**Issue by baobeidaodao** [apache/shardingsphere#5882]
When I use sharding-jdbc-spring-boot-starter:4.1.0 and spring-boot:2.2.7 , it works well .
After upgrade spring-boot:2.3.0 , it throws an exception:

org.springframework.dao.InvalidDataAccessApiUsageException: ConnectionCallback; isValid; nested exception is java.sql.SQLFeatureNotSupportedException: isValid

Is this a bug or compatibility problem ?

**Comment by baobeidaodao** [comment]
My project dependencies list contains spring-boot-starter-actuator:2.3.0. It will check application health status. also it will check db connections use SQL such as "select 1". During that moment, the exception was thrown.
Maybe this is the problem.

**Comment by kimmking** [comment]
The root of ex cause: shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/unsupported/AbstractUnsupportedOperationConnection.java
```
@Override
    public final boolean isValid(final int timeout) throws SQLException {
        throw new SQLFeatureNotSupportedException("isValid");
    }@Override
    public final boolean isValid(final int timeout) throws SQLException {
        throw new SQLFeatureNotSupportedException("isValid");
    }
```

**Comment by kimmking** [comment]
This method for test connection is valid, and could be instead of "select 1" checking.
So we should discuss about supporting it or not.
@terrymanu @menghaoranss

**Comment by wuxingye** [comment]
how to solve in current version, thank you

**Comment by wuxingye** [comment]
https://blog.csdn.net/qq_33547169/article/details/106648132

**Comment by cy503328434** [comment]
because of health check, just close it.
`management.health.db.enabled=false`
or
```
management:
  health:
    db:
      enabled: false
```

**Comment by dbnex14** [comment]
> because of health check, just close it. `management.health.db.enabled=false` or
> 
> ```
> management:
>   health:
>     db:
>       enabled: false
> ```

how is disabling health check helpful??

**Comment by yluom** [comment]
If you are stuck with an old version of shardingsphere and have this issue, there is a fix to bypass this Connection#isValid() validation and use query validation instead: 
```
@Configuration
public class DataSourceHealthConfig extends DataSourceHealthContributorAutoConfiguration {

    @Value("${whatever.custom-db-validation-query:select 1}")
    private String defaultQuery;


    public DataSourceHealthConfig(Map<String, DataSource> dataSources, ObjectProvider<DataSourcePoolMetadataProvider> metadataProviders) {
        super(dataSources, metadataProviders);
    }

    @Override
    protected AbstractHealthIndicator createIndicator(DataSource source) {
        DataSourceHealthIndicator indicator = (DataSourceHealthIndicator) super.createIndicator(source);
        if (!StringUtils.hasText(indicator.getQuery())) {
            indicator.setQuery(defaultQuery);
        }
        return indicator;
    }
}
```
