### ISSUE TITLE
like condition in the statement discard

### ISSUE THREAD

**Issue by yoloz** [apache/shardingsphere#5901]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-sql-parser

### Expected behavior
AndPredicate length in WhereSegment  is zero

### Actual behavior
AndPredicate length is one

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT * FROM  book b where name LIKE '神%'

**Comment by terrymanu** [comment]
Did you meet some problem?  It seems which does not affect the correctness of the program.

**Comment by terrymanu** [comment]
Closed because of no response anymore

**Comment by yoloz** [comment]
regret, i need sql parser , like in sql replaced by equal so can get condition
