### ISSUE TITLE
psql couldn't connect to ShardingSphere Proxy 4.1.0

### ISSUE THREAD

**Issue by Ajkcki** [apache/shardingsphere#5912]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
psql -U postgres -h localhost -p 3307
will connect to the proxy
### Actual behavior
FATAL: database "postgres" does not exist
### Reason analyze (If you can)
Two conf files are activated: "server.yaml" and "config-sharding", All are defaults provided in "conf/".
Two databases "demo_ds_0" and "demo_ds_1" are created manually, run "bin/start.sh" to start the server without any error (zookeeper is running at localhost:2181). 

Couldn't figure out why. Please help !

**Comment by cherrylzhao** [comment]
you should use sharding_db like this:
psql -h127.0.0.1 -p 3307 -U root -d sharding_db

**Comment by Ajkcki** [comment]
Thank you, it works! Just noticed that 
psql -U whatevername -h localhost -p 3307 -d sharding_db 
works as well where option -U is supplied with any names.  So anyone can  access sharding_db with what ever names! I'm wondering why, or there is something wrong in my setttings. Again, the proxy started with default server.yaml and config-sharing.yaml.

**Comment by cherrylzhao** [comment]
yes, we have not implement the authentication logic, would you have a try for that?

**Comment by cherrylzhao** [comment]
associated code is `PostgreSQLAuthenticationEngine`.
```
public boolean auth(final ChannelHandlerContext context, final PacketPayload payload, final BackendConnection backendConnection) {
       .....
       // TODO send a md5 authentication request message
        context.write(new PostgreSQLAuthenticationOKPacket(true));
        context.write(new PostgreSQLParameterStatusPacket("server_version", "12.3"));
        context.write(new PostgreSQLParameterStatusPacket("client_encoding", "UTF8"));
        context.write(new PostgreSQLParameterStatusPacket("server_encoding", "UTF8"));
}
```

**Comment by cherrylzhao** [comment]
create another issue #5978 to record the authentication enhancement
