### ISSUE TITLE
How to get select, insert, update, delete in shardingalgorithm？

### ISSUE THREAD

**Issue by tutuerhao** [apache/shardingsphere#5913]
## Question
How to get select, insert, update, delete in shardingalgorithm？

**Comment by menghaoranss** [comment]
what do you mean？

**Comment by tutuerhao** [comment]
@menghaoranss 

MySelf ComplexKeysShardingAlgorithm

![image](https://user-images.githubusercontent.com/29938085/83729721-9db00180-a67a-11ea-9a3e-ac5573248a67.png)

**Comment by terrymanu** [comment]
No way, sharding algorithm can process sharding key only. It is not the process scope of SQL operate type in sharding algorithm
