### ISSUE TITLE
shardingsphere JDBC  not support  LocalDateTime 

### ISSUE THREAD

**Issue by moses-keqi** [apache/shardingsphere#5915]
version:
com.baomidou:org:mybatis: 3.5.3
mybatis-plus-boot-starter: 3.3.1.tm
com.microsoft.sqlserver:sqljdbc4: 4.0
com.alibaba:druid: 1.1.22
org.apache.shardingsphere:sharding-jdbc-spring-boot-starter: 4.0.0-RC2

org.springframework.jdbc.UncategorizedSQLException: Error attempting to get column 'update_time' from result set.  Cause: java.sql.SQLException: Error
; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error] with root cause

**Comment by dongzl** [comment]
@moses-keqi  For English only.

duplicate: #5445 .
