### ISSUE TITLE
4.1.0 not support subquery

### ISSUE THREAD

**Issue by jackyLqq** [apache/shardingsphere#5925]
subquery logic table name not be replaced physical table name ,it cause table not found error,When to support subquery？

**Comment by menghaoranss** [comment]
@jackyLqq Subquery support is in progress, refer to #4696

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.

Please refer to the document for the latest support status:
https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/
