### ISSUE TITLE
when 4.1.1  release in apache maven？

### ISSUE THREAD

**Issue by lorangej** [apache/shardingsphere#5928]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
@lorangej The 4.1.1 version is voting now, you can follow ShardingSphere Mailing-list.

**Comment by kimmking** [comment]
it's in apache maven now.
