### ISSUE TITLE
How's the sharding-sidecar going?

### ISSUE THREAD

**Issue by Fish-Potato** [apache/shardingsphere#5932]
## Question
How's the sharding-sidecar going?
**For English only**, other languages will not accept.
shading-sidecar现在的进展如何了，有什么进展能透露一下吗
Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
No plan ,need more volunteer to discuss it together.

**Comment by terrymanu** [comment]
I just set this issue as duplicate with #1480
