### ISSUE TITLE
In some cases ,cant get the right value  of the designated column

### ISSUE THREAD

**Issue by xdrreal** [apache/shardingsphere#5934]
### Which version of ShardingSphere did you use?
4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC 
### Expected behavior
````
SELECT *  FROM table
        WHERE 1 = 1
        AND (#{customerId} is null or `customerId` = #{customerId})
        AND  updatetime >= #{updatetime})
        ORDER BY updateTime DESC
```` 
we use 'customeid' as the sharding column

**Comment by kimmking** [comment]
why there have a ‘#{customerId} is null’ ？

**Comment by terrymanu** [comment]
If the customerId is null, what is your expected behavior about sharding?

**Comment by terrymanu** [comment]
Closed because of no response anymore
