### ISSUE TITLE
Does ShardingSphere support.NET CORE language and MSSQL database

### ISSUE THREAD

**Issue by xiaohuazi123** [apache/shardingsphere#5942]
## Question

Do you support .NET CORE language and Python language?   
Do you also support MSSQL database？

**Comment by kimmking** [comment]
- sharding-jdbc support only db via jdbc in java，not support C#/python
- sharding-proxy support all .net/python and other language, but only mysql/pgsql now, sqlserver will be supported .

**Comment by kimmking** [comment]
estio

**Comment by xiaohuazi123** [comment]
I have high expectations for Sharding-Proxy.
