### ISSUE TITLE
Metadata can not be stored to metadata center with the master branch code#Sharding-Proxy

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#5949]
I guess the code for persisting metadata is gone  after `metadata` refactoring,  the previous code is in the `LogicSchema` class, and now the code for creatding metadata is in the `SchemaContextsBuilder` class.

**Comment by kimmking** [comment]
I will check it.

**Comment by menghaoranss** [comment]
I tried sharding-jdbc with example, after fixing this problem #5955, metadata can be saved.

**Comment by menghaoranss** [comment]
According to the discussion just now, i will fix it. The metadata shuld be saved after `SchemaContexts` is initialized in proxy.
