### ISSUE TITLE
shardingsphere sqlserver not support page

### ISSUE THREAD

**Issue by moses-keqi** [apache/shardingsphere#5969]
shardingsphere sqlserver not support page
SELECT  id,batch_id,template_id,mobile,userid,policy_no,custom,content,sys_code,channel_code,send_type,send_time,sale_channel,channel_id,sms_status,case_name,channel_business_id,channel_return_id,create_time,update_time  FROM         zz_sms_send WHERE 1=1                        AND batch_id = ?                              order by create_time desc          offset 0 rows fetch next 10 rows only
### Cause: java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at org.apache.shardingsphere.core.parse.old.parser.context.limit.Limit.rewrite(Limit.java:99) ~[sharding-core-parse-common-4.0.0-RC1.jar:4.0.0-RC1]

LimitValue rowCount   rowCount is null

**Comment by terrymanu** [comment]
The SQL you provided are not use pagination, can you provide the pagination SQL?

**Comment by moses-keqi** [comment]
SELECT id,batch_id,template_id,mobile,userid,policy_no,custom,content,sys_code,channel_code,send_type,send_time,sale_channel,channel_id,sms_status,case_name,channel_business_id,channel_return_id,create_time,update_time FROM zz_sms_send WHERE 1=1 AND batch_id = ? order by create_time desc offset 0 rows fetch next 10 rows only

> The SQL you provided are not use pagination, can you provide the pagination SQL?

**Comment by moses-keqi** [comment]
> The SQL you provided are not use pagination, can you provide the pagination SQL?

4.0.0-RC1 sqlserver  Pagination fail 4.0.0-RC2 success
