### ISSUE TITLE
default-database-strategy:hint can't use

### ISSUE THREAD

**Issue by VitZhou** [apache/shardingsphere#5970]
ShardingSphere-JDBC 4.1.1  default-database-strategy:hint can't use

spring:
  shardingsphere:
    sharding:
      default-data-source-name: demo-1
      default-database-strategy:
        hint:
          algorithm-class-name: com.ai94.mysql.annotation.AnnotationHintShardingAlgorithm
    datasource:
      names: demo-1,demo-2
      # 配置第 1 个数据源
      demo-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/db_A?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
      # 配置第 2 个数据源
      demo-2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/db_B?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root

**Comment by terrymanu** [comment]
What is the current error and what is your expectation?

Can you provide more code to help the issue reproduce?

**Comment by terrymanu** [comment]
Closed because of no response anymore

**Comment by gongguoyu** [comment]
default-database-strategy:hint      It doesn't work anymore, however, it works well in 4.0.0-rc2

**Comment by cnlinjie** [comment]
@terrymanu  
发现你们只会关问题，他提的那么清楚了，
```
default-database-strategy:
hint:
algorithm-class-name: com.ai94.mysql.annotation.AnnotationHintShardingAlgorithm
```
这个不会生效，也就是不会调用到 AnnotationHintShardingAlgorithm 

只会回避问题而不是修复问题的话，那issues 拿来干嘛用呢？

**Comment by Roy-luoxiaosong** [comment]
@gongguoyu  have you resolved this issue , i was involved into this issue . but i can't downgrade to 4.0.0-RC1,  since the XA transaction of this version is not work .
