### ISSUE TITLE
ShardingSphere UI support etcd config center

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5972]
Hi, community,
We were planning to support more config center long ago[1].
As etcd/CNCF is more and more popular, it's time to launch the integration with etcd and ShardingSphere-UI, make our users could manage ShardingSphere via UI-Console with etcd.

And any contributor is welcome to join this task.
- [x] make investigation and design document
- [x] refactor ShardingSphere UI to support more center
- [x] implement integration with etcd config center 

[1] https://github.com/apache/shardingsphere/issues/3267

**Comment by renfufei** [comment]
Hi, Kimmking,
I want to join the develop work!

**Comment by kimmking** [comment]
plz submit pr to https://github.com/apache/shardingsphere-ui

**Comment by renfufei** [comment]
Hi, Kimmking,
I have created the pull request for this issue: 
[https://github.com/apache/shardingsphere-ui/pull/2](https://github.com/apache/shardingsphere-ui/pull/2)
