### ISSUE TITLE
liquibase  used setFetchSize,   Hope to support soon

### ISSUE THREAD

**Issue by HanKaiqiang** [apache/shardingsphere#5986]
## Feature Request

**For English only**, other languages will not accept.
Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Using liquibase and shardingsphere at the project  will be problematic because liquibase will used
setFetchSize

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

support setFetchSize

**Comment by tuohai666** [comment]
Thanks for your report. Can you provide more information?

1. Please provide the actual behavior originally, rawly and straightforwardly without any analysis. It means raw input/output data, or raw log, config...

2. You didn't fill in the bug report template, so I have to ask you here what's the release version? What's application(ShardingSphere-JDBC or ShardingSphere-Proxy)?

3. When you use setFetchSize, what's the value you set?

4. You mentioned you haven met problem when use setFetchSize, what is the exact problem?

5. At last, if you have some findings and want to analyze, please do it in a separate section.

**Comment by tuohai666** [comment]
Closed because of no response anymore.
