### ISSUE TITLE
Unsupported SQL

### ISSUE THREAD

**Issue by lorangej** [apache/shardingsphere#5997]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
execute sql:
( select  encrypt_column from tqdw.sharding_encrypt  where  is_deleted = 'N')    limit 1,2

report error:
no viable alternative at input '('
extraneous input '(' expecting {SELECT, INSERT,.....
Unsupported SQL

### Actual behavior
select failed

### Reason analyze (If you can)

In SqlPaser, SQL doesn't seem to start with '('

**Comment by jingshanglu** [comment]
@lorangej Is it mysql or pg?
