### ISSUE TITLE
shardingsphere 4.0.1 version project start so slow,take too long times

### ISSUE THREAD

**Issue by Spole0168** [apache/shardingsphere#5999]
Use shardingsphere 4.0.1 to configure the project, use the Oracle database, specifically 5 machines, one puts the basic table, two external connections are one master and one slave, and there are 10 tables in the database. After the project is started multiple times, the subsequent startup is special. slow. After analysis, it was found that "analyze table my_table compute statistics;" similarly scanned all the data of the sub-database tables, and the data of the sub-database tables was about 20 million. It currently takes more than 20 minutes to start to start the project. Did you encounter a similar situation again?

![image](https://user-images.githubusercontent.com/28697512/84361530-61424f80-abfe-11ea-8479-bb452a369e51.png)

analyze table my_table compute statistics;

**Comment by terrymanu** [comment]
Does this issue same with #5755?

**Comment by kimmking** [comment]
analyze table my_table compute statistics is not triggered by shardingsphere.

**Comment by hand515** [comment]
> `analyze table my_table compute statistics` is not triggered by shardingsphere.

This's triggered by oracle-jdbc : OracleDatabaseMetaData.getIndexInfo() (bytecode decompiled from com.oracle.database.jdbc:ojdbc10:19.6.0.0)
shardingsphere will call IndexMetaDataLoader.load on startup

**Comment by terrymanu** [comment]
ShardingSphere need database metadata. 
How long about `analyze table my_table compute statistics` spend? 
Is it related data count in table?

**Comment by hand515** [comment]
It's slow in mysql too.
There are 349 tables in my case , and it takes 105 seconds to load table meta.

In mysql jdbc driver [DataBaseMetaData](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java) , getIndexInfo and getColumns  executes one sql for each table to get metadata. More tables need more times to load metadata.

**Comment by terrymanu** [comment]
@hand515 is it the same version with @Spole0168 ?
MySQL and Oracle performance issue are diff one, can we discuss them separated?

**Comment by kimmking** [comment]
@hand515 https://shardingsphere.apache.org/document/current/cn/faq/#18-%E6%9C%8D%E5%8A%A1%E5%90%AF%E5%8A%A8%E6%97%B6%E5%A6%82%E4%BD%95%E5%8A%A0%E5%BF%ABmetadata%E5%8A%A0%E8%BD%BD%E9%80%9F%E5%BA%A6

**Comment by terrymanu** [comment]
Closed because of no response anymore

**Comment by hand515** [comment]
> @hand515 https://shardingsphere.apache.org/document/current/cn/faq/#18-%E6%9C%8D%E5%8A%A1%E5%90%AF%E5%8A%A8%E6%97%B6%E5%A6%82%E4%BD%95%E5%8A%A0%E5%BF%ABmetadata%E5%8A%A0%E8%BD%BD%E9%80%9F%E5%BA%A6

Although setting "max.connections.size.per.query" can make it initializing faster, but it's not helpful because of some reasons:
* The database has a limit on the maximum number of client connections.
* Time is related to the number of table. More tables will take more time.
* Afraid of unknown performance problems will trigger in production environment.

**Comment by tristaZero** [comment]
Hi @Spole0168 
Sorry for my delayed comment. The good news that the performance of starting ShardingProxy has been greatly improved already! Thanks for @xbkaishui, who took much effort in #6212.

Presently, welcome your any test for the `master branch` (Package it local firstly). Your feedback will be the best gift for the community.

Best,
Trista
