### ISSUE TITLE
The number of pages is mandatory to be less than 500

### ISSUE THREAD

**Issue by dudiao** [apache/shardingsphere#6009]
```xml
<dependency>
	<groupId>org.apache.shardingsphere</groupId>
	<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
	<version>4.1.0</version>
</dependency>
```

I use Mybatis plus, code show as below:
```java
// I write sql: select * from cust limit 0,1000
Page<Cust> page = custService.page(new Page<>(1, 1000));

// but Actual SQL: select * from cust limit 0, 500
```
This table(`cust`) is not configured with tableStrategy.

I want to find 1000 data per page, how should I configure it?

**Comment by terrymanu** [comment]
Is this issue related with ShardingSphere?
Maybe you should ask question for Mybatis plus

**Comment by dudiao** [comment]
o, thanks, get it.

![image](https://user-images.githubusercontent.com/38355949/84490565-eb111c00-acd5-11ea-9ba4-2179b74a9760.png)
