### ISSUE TITLE
@ljz0721cx ok，i know your data class now.

### ISSUE THREAD

**Issue by ljz0721cx** [apache/shardingsphere#6022]
@ljz0721cx ok，i know your data class now.
but i can't reproduce it...ah...
can you make a small demo for reproducing it for me?

_Originally posted by @kimmking in https://github.com/apache/shardingsphere/issues/5876#issuecomment-643194211_

Ok
you can pull demo code with url https://github.com/ruiqikeji/spring-nacos.git , branch is  sharding-db of  this project

run test class TestOrderShardingMapper

**Comment by terrymanu** [comment]
Can you change the title for search firendly?

**Comment by kimmking** [comment]
it's a private projec.

**Comment by kimmking** [comment]
we should discuss in the old issue.
