### ISSUE TITLE
sharding-proxy 4.1.1 insert sql contains emoji error

### ISSUE THREAD

**Issue by lonelythinker** [apache/shardingsphere#6028]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
execute sql:INSERT IGNORE INTO article(sharding_key, title, digest, link) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感😂', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865');

proxy log:
[INFO ] 12:25:49.242 [ShardingSphere-Command-2] ShardingSphere-SQL - Logic SQL: INSERT IGNORE INTO article(sharding_key, title, digest, link) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感😂', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865')
[INFO ] 12:25:49.242 [ShardingSphere-Command-2] ShardingSphere-SQL - Actual SQL: ds_2019 ::: INSERT IGNORE INTO article_09_6(sharding_key, title, digest, link, id) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感😂', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865', 478902062378123265)) ---- hint:There are two ')' here

report error:ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

But, when I execute the following sql, everything is ok.(no emoji)

execute sql:INSERT IGNORE INTO article(sharding_key, title, digest, link) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865');

proxy log:
[INFO ] 12:25:49.242 [ShardingSphere-Command-2] ShardingSphere-SQL - Logic SQL: INSERT IGNORE INTO article(sharding_key, title, digest, link) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865')
[INFO ] 12:25:49.242 [ShardingSphere-Command-2] ShardingSphere-SQL - Actual SQL: ds_2019 ::: INSERT IGNORE INTO article_09_6(sharding_key, title, digest, link, id) VALUES (1567930626785, '哈士奇看到“女神”后，结果忍不住舔屏了', '快进来接受二哈的“洗礼”配乐毫无违和感', 'https://mp.weixin.qq.com/s?__biz=MzI2MDA0NTY0MA==&mid=2651076369&idx=3&sn=c6efbfc6e685d75e2d6466d244cf7865', 478903797431664641) ---- hint:There are only one ')' here

### Actual behavior
insert failed

### Reason analyze (If you can)
Maybe the SqlPaser doesn't work well when the sql contains emoji.

**Comment by jingshanglu** [comment]
@lonelythinker Can you give complete stack information?

**Comment by jingshanglu** [comment]
@lonelythinker This error is reported by mysql server, shouldn't the emoji be a string?

**Comment by lonelythinker** [comment]
mysql error:ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

This error is reported by mysql server, because the sql has an extra character ')' at the end.

The error sql  is generated by ShardingSphere-SQL, when it contains emoji. So it can't be mysql that's causing this problem.(The character set for the mysql database is utf8mb4.)

**Comment by lonelythinker** [comment]
Maybe the key generator doesn't work well when the sql contains emoji. I used the key generator which the type is 'SNOWFLAKE' and the column is 'id'.

**Comment by lonelythinker** [comment]
I found the key generator doesn't work well  when the sql contains some  special character such as '𠈌’, not only emoji.

**Comment by BabyStrong** [comment]
@jingshanglu I also encountered the same problem，only insert sql contains emoji error，update works well，how to solve this problem?

**Comment by 171563857** [comment]
> @jingshanglu I also encountered the same problem，only insert sql contains emoji error，update works well，how to solve this problem?

@BabyStrong I also encountered the same problem，update works well, only insert sql contains emoji error，and update op also 
work error after insert op error, i use insert op at first but remove emoji and then use update op contains emoji, it's so contains

**Comment by 171563857** [comment]
update op also work error, some like this: 
𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪
徐学习🦄
![image](https://user-images.githubusercontent.com/22027896/87263262-35610500-c4ef-11ea-80d8-6b207a3b5878.png)

**Comment by xbkaishui** [comment]
there is a work version in my [branch ](https://github.com/xbkaishui/shardingsphere/tree/support-local-datetime-411), please have a try and let me know

**Comment by jingshanglu** [comment]
> @jingshanglu @171563857
> there is a work version in my [branch ](https://github.com/xbkaishui/shardingsphere/tree/support-local-datetime-411), please have a try and let me know

It maybe fix in parser, when sql contain emoji, the emoji has more than one byte.

**Comment by xbkaishui** [comment]
in version 4.1.1, it's no fixed. I will try in master branch

**Comment by xbkaishui** [comment]
@jingshanglu 
still have error in master branch. please check this log

[INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10+,'璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.');
[INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@ffa2a23, tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)])), tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)]), columnNames=[third_account_id, nickname], insertValueContexts=[InsertValueContext(parametersCount=0, valueExpressions=[LiteralExpressionSegment(startIndex=69, stopIndex=71, literals=10), LiteralExpressionSegment(startIndex=73, stopIndex=124, literals=璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.)], parameters=[])], onDuplicateKeyUpdateValueContext=null, generatedKeyContext=Optional.empty)
[INFO ] 20:11:50.579 [ShardingSphere-Command-4] ShardingSphere-SQL - Actual SQL: ds_0 ::: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10, '璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.')^123123d,.');

It seems parser issue.

**Comment by jingshanglu** [comment]
> @jingshanglu
> still have error in master branch. please check this log
> 
> `[INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10+,'璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.'); [INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@ffa2a23, tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)])), tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)]), columnNames=[third_account_id, nickname], insertValueContexts=[InsertValueContext(parametersCount=0, valueExpressions=[LiteralExpressionSegment(startIndex=69, stopIndex=71, literals=10), LiteralExpressionSegment(startIndex=73, stopIndex=124, literals=璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.)], parameters=[])], onDuplicateKeyUpdateValueContext=null, generatedKeyContext=Optional.empty) [INFO ] 20:11:50.579 [ShardingSphere-Command-4] ShardingSphere-SQL - Actual SQL: ds_0 ::: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10, '璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.')^123123d,.');`
> 
> It seems parser issue.

Now, it has not been fixed, i mean we should fix it in parser.

**Comment by 171563857** [comment]
> > @jingshanglu
> > still have error in master branch. please check this log
> > `[INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10+,'璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.'); [INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@ffa2a23, tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)])), tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)]), columnNames=[third_account_id, nickname], insertValueContexts=[InsertValueContext(parametersCount=0, valueExpressions=[LiteralExpressionSegment(startIndex=69, stopIndex=71, literals=10), LiteralExpressionSegment(startIndex=73, stopIndex=124, literals=璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.)], parameters=[])], onDuplicateKeyUpdateValueContext=null, generatedKeyContext=Optional.empty) [INFO ] 20:11:50.579 [ShardingSphere-Command-4] ShardingSphere-SQL - Actual SQL: ds_0 ::: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10, '璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.')^123123d,.');`
> > It seems parser issue.
> 
> Now, it has not been fixed, i mean we should fix it in parser.

how long will it fix ? i maybe choose other solution if it's too long, thx

**Comment by xbkaishui** [comment]
> > @jingshanglu
> > still have error in master branch. please check this log
> > `[INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10+,'璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.'); [INFO ] 20:11:50.578 [ShardingSphere-Command-4] ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@ffa2a23, tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)])), tablesContext=TablesContext(tables=[SimpleTableSegment(tableName=TableNameSegment(startIndex=12, stopIndex=31, identifier=IdentifierValue(value=t_user_third_account, quoteCharacter=NONE)), owner=Optional.empty, alias=Optional.empty)]), columnNames=[third_account_id, nickname], insertValueContexts=[InsertValueContext(parametersCount=0, valueExpressions=[LiteralExpressionSegment(startIndex=69, stopIndex=71, literals=10), LiteralExpressionSegment(startIndex=73, stopIndex=124, literals=璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.)], parameters=[])], onDuplicateKeyUpdateValueContext=null, generatedKeyContext=Optional.empty) [INFO ] 20:11:50.579 [ShardingSphere-Command-4] ShardingSphere-SQL - Actual SQL: ds_0 ::: INSERT INTO t_user_third_account ( third_account_id,nickname) values(10, '璐小果🍎我😀𪚥徐学习學習~🙋‍♀️𝓒𝓸𝓬𝓪𝓒𝓸𝓵𝓪asdfas!【】［］@#$%^123123d,.')^123123d,.');`
> > It seems parser issue.
> 
> Now, it has not been fixed, i mean we should fix it in parser.

I got your point. I will try to fix this, but I am not familiar with antlr parser, do you have any ideas ?

**Comment by xbkaishui** [comment]
@171563857, You can try my [branch](https://github.com/xbkaishui/shardingsphere/tree/support-local-datetime-411), it is ok now in version 4.1.1.

**Comment by 171563857** [comment]
it's sql parser err, i havn't any idea, sry
just to try another way QAQ

**Comment by xbkaishui** [comment]
Hi @jingshanglu , I find the root cause of this issue, please refer [this](https://github.com/antlr/antlr4/blob/master/doc/unicode.md#unicode-code-points-in-lexer-grammars),  let's discuss how to fix it.

**Comment by tristaZero** [comment]
Hi  @lonelythinker @171563857 

I am glad to tell you guys, this issue has been fixed perfectly with the help of @xbkaishui and @jingshanglu 
Thanks for your feedback!

Best,
Trista

**Comment by dsj017112** [comment]
@tristaZero Hello, could you please tell me in which version this bug was fixed?
