### ISSUE TITLE
How to configure the parameters of the data source?

### ISSUE THREAD

**Issue by cielswift** [apache/shardingsphere#6036]
shardingsphere:
    datasource:
      names: ds0,ds1 
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource  #How to configure?
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:1670/spring_alibaba?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ciel

Configure information such as the maximum number of connections

private static void callSetterMethod(final DataSource dataSource, final String methodName, final String setterValue) {
        for (Class<?> each : GENERAL_CLASS_TYPE) {
            try {
                Method method = dataSource.getClass().getMethod(methodName, each);
                if (boolean.class == each || Boolean.class == each) {
                    method.invoke(dataSource, Boolean.valueOf(setterValue));
                } else if (int.class == each || Integer.class == each) {
                    method.invoke(dataSource, Integer.parseInt(setterValue));
                } else if (long.class == each || Long.class == each) {
                    method.invoke(dataSource, Long.parseLong(setterValue));
                } else if (Collection.class == each) {
                    method.invoke(dataSource, Arrays.asList(setterValue.split(",")));
                } else {
                    method.invoke(dataSource, setterValue);
                }
                return;
            } catch (final ReflectiveOperationException ignored) {
            }
        }
    }

**Comment by kimmking** [comment]
`maximumPoolSize` or `maximum-pool-size` ?

**Comment by cielswift** [comment]
shardingsphere:
    datasource:
      names: ds0,ds1 #数据源名称，多数据源以逗号分隔
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 16
        min-idle: 16
        max-active: 32
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:1670/spring_alibaba?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: ciel

this ?

**Comment by xbkaishui** [comment]
yes for DruidDataSource the config is right.
