### ISSUE TITLE
Add metadata info shown in ShardingSphere-UI

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#6043]
- [x] Add metadata service interface in UI-backend
- [x] Add metadata details window in UI-frontend

**Comment by EasonFeng5870** [comment]
Hi @kimmking ，  I love to solve it.  By the way, when does this task need to be done?

**Comment by kimmking** [comment]
@EasonFeng5870  ASAP.

**Comment by EasonFeng5870** [comment]
Hello @kimmking ,  I tried to build ui project, the following error block me now :

General error is :

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run unit) on project shardingsphere-ui-frontend: Failed to run task: 'npm run unit' failed. `

Detail error is : 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\workspaces\\github\\EasonFeng5870\\shardingsphere-ui\\shardingsphere-ui-frontend\\node\\node.exe',
1 verbose cli   'C:\\workspaces\\github\\EasonFeng5870\\shardingsphere-ui\\shardingsphere-ui-frontend\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'unit' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'preunit', 'unit', 'postunit' ]
5 info lifecycle shardingsphere-ui-frontend@1.0.0~preunit: shardingsphere-ui-frontend@1.0.0
6 info lifecycle shardingsphere-ui-frontend@1.0.0~unit: shardingsphere-ui-frontend@1.0.0
7 verbose lifecycle shardingsphere-ui-frontend@1.0.0~unit: unsafe-perm in lifecycle true
8 verbose lifecycle shardingsphere-ui-frontend@1.0.0~unit: PATH: C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend\node_modules\.bin;C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend\node;C:\Users\eason\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\eason\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Java\jdk8\jdk1.8.0_102\bin;C:\Java\apache-maven-3.6.3\bin;C:\Java\jdk8\jdk1.8.0_102\jre\bin;C:\Program Files\Mercurial;C:\Java\gradle-6.2.2\bin;C:\Program Files (x86)\scala\bin;C:\Java\btrace-2.0.1-bin\bin\bin;C:\Users\eason\AppData\Local\Microsoft\WindowsApps;C:\Users\eason\AppData\Local\GitHubDesktop\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;
9 verbose lifecycle shardingsphere-ui-frontend@1.0.0~unit: CWD: C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend
10 silly lifecycle shardingsphere-ui-frontend@1.0.0~unit: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env BABEL_ENV=test karma start test/karma.conf.js --single-run' ]
11 silly lifecycle shardingsphere-ui-frontend@1.0.0~unit: Returned: code: 1  signal: null
12 info lifecycle shardingsphere-ui-frontend@1.0.0~unit: Failed to exec unit script
13 verbose stack Error: shardingsphere-ui-frontend@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/karma.conf.js --single-run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend\node\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid shardingsphere-ui-frontend@1.0.0
15 verbose cwd C:\workspaces\github\EasonFeng5870\shardingsphere-ui\shardingsphere-ui-frontend
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\workspaces\\github\\EasonFeng5870\\shardingsphere-ui\\shardingsphere-ui-frontend\\node\\node.exe" "C:\\workspaces\\github\\EasonFeng5870\\shardingsphere-ui\\shardingsphere-ui-frontend\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "unit"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error shardingsphere-ui-frontend@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/karma.conf.js --single-run`
22 error Exit status 1
23 error Failed at the shardingsphere-ui-frontend@1.0.0 unit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by EasonFeng5870** [comment]
@kimmking  thanks for your help on wechat, now I deploied successfully.  Now could you give me more details about metadata, thanks~~

**Comment by kimmking** [comment]
@EasonFeng5870 Expecting your forward.

**Comment by EasonFeng5870** [comment]
working on vue part now.
