### ISSUE TITLE
Add an unwatch method to CenterRepository interface

### ISSUE THREAD

**Issue by tswstarplanet** [apache/shardingsphere#6057]
CenterRepository has a watch method, but doesn't have an unwatch method. I think we can add a method like
```java
    /**
     * Unwatch key or path of the config server.
     *
     * @param key key of data
     */
    void unwatch(String key);
```
This method can cancel the watch of the specified key. I think it can be useful.

**Comment by terrymanu** [comment]
What is the usage of unwatch?

**Comment by tswstarplanet** [comment]
Use it to cancel the watch to key.

**Comment by terrymanu** [comment]
When the program need to cancel the watch to a key and release related resources?
If resources released, does the program run correctly?

**Comment by terrymanu** [comment]
Will close soon if no response anymore

**Comment by terrymanu** [comment]
Closed because of no response anymore
