### ISSUE TITLE
Whether HintShardingAlgorithm supports BETWEEN AND？

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#6066]
Whether HintShardingAlgorithm supports BETWEEN AND？

shardingsphere4.1.1 

The requirement is that I need to determine which database is based on a variable.It then determines which table is based on the fields and field values.
Can HintShardingAlgorithm be implemented?AND you need to support BETWEEN AND > < ...

addTableShardingValue(final String logicTable, final Comparable<?> value)

HintShardingAlgorithm can only add a table name and a sharding value.Column names and multiple sharding values cannot be added.

**Comment by kimmking** [comment]
Hint only support a certain key, such like `user_id = 10`
