### ISSUE TITLE
[Translation] Translate technical articles concerning Apache ShardingSphere

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6070]
Hi, community,

This issue is to call for volunteers to **translate some technical articles from Chinese into English**. Anyone who enjoys translation or wants to make some contributions to open source community is warmly welcomed! 👏 

### Competencies needed
1. English translation skill
2. Basically, know what ShardingSphere is doing

### Article list
- [x] 1. [Start ElasticJob off with new goal](https://mp.weixin.qq.com/s/XJFj_vOj3bR6HRQUzy1ikg) --> @rudy2steiner
- [x] 2. [How to construct the distributed database](https://mp.weixin.qq.com/s/YSoX0Apq6vQeu8TU_53EAw) --> @EasonFeng5870
- [x] 3. [Apache ShardingSphere is included in CNCF Landscape](https://mp.weixin.qq.com/s/hAxON1CMYvgFf6sFIHtDHA) --> @mlw12345678
- [x] 4. [The mixed open-source distributed transaction solution](https://mp.weixin.qq.com/s/fYESyuw7O4u7wB-tSWlhyg) --> @mlw12345678
- [x] 5. [Would you like to become an Apache committer](https://mp.weixin.qq.com/s/sFqOz10KTk23IhmmDTy67g) --> @mlw12345678
- [x] 6. [How automatic executor of ShardingSphere works](https://mp.weixin.qq.com/s/hIKZPJDfGfeduW4frwVN_w)
- [x] 7. [How to merge the child resultsets](https://mp.weixin.qq.com/s/5__SGXEdvGqkVhpnrW6zug)
- [ ] 8. [The quick explanation of ShardingSphere transaction module](https://mp.weixin.qq.com/s/0LtqRTL8HewUAdZCk8LRLg)
- [x] 9. [What is the ShardingProxy](https://mp.weixin.qq.com/s/bTX0n9tH4x8eue19b7rdGw) --> @wcsoft 

### How to submit your translation
1. Add your translation to `xxx.en.md` in [blog](https://github.com/apache/shardingsphere/tree/master/docs/blog/content/material).

2. Raise a PR for review.

### Notice
1. All the Chinese articles named `xxx.cn.md` could be found in the same directory of Your translation as well. 
2. If you want o find a partner to work together for these long articles, please be free to give `recruit comment` below. 😉 
3. You can give a brief translation for these author profiles in the articles. Like just translate their names and titles.

If you want to have a try, **please comment here with** `Article number and your estimated deadline`. 

Besides, **any feedback and comments are welcomed as well**! 😃

**Comment by kimmking** [comment]
Chinese articles list:

1. Start ElasticJob off with new goal:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/ElasticJob.cn.md
2. How to construct the distributed database:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/database.cn.md
3. Apache ShardingSphere is included in CNCF Landscape:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/CNCF.cn.md
4. The mixed open-source distributed transaction solution:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/solution.cn.md
5. Would you like to become an Apache committer:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/committer.cn.md
6. How automatic executor of ShardingSphere works:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/engine.cn.md
7. How to merge the child resultsets:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/result.cn.md
8. The quick explanation of ShardingSphere transaction module:https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/seata.cn.md
9. What is the ShardingProxy: https://github.com/apache/shardingsphere/blob/master/docs/blog/content/material/proxy.cn.md

**Comment by EasonFeng5870** [comment]
Hello all, I want to try with No. 2, and it will be done on 6.30, is that ok ?

**Comment by rudy2steiner** [comment]
No.1 i'd like to try!

**Comment by mlw12345678** [comment]
Hello all，i'd like to try No.3！

**Comment by tristaZero** [comment]
> Hello all, I want to try with No. 2, and it will be done on 6.30, is that ok ?

Hi @EasonFeng5870 Welcome, waiting for your good job!

**Comment by tristaZero** [comment]
@rudy2steiner Hi Welcome, now No.1 belongs to you, have a good time. :-)

**Comment by tristaZero** [comment]
@mlw12345678 Glad to see you! I will assign it to you. Good luck!

**Comment by mlw12345678** [comment]
I will translate No. 4 and 5 too ! I need to create a new PR or use the old one?

**Comment by tristaZero** [comment]
@mlw12345678 a new PR is preferable, welcome!

**Comment by wcsoft** [comment]
Take No.9, will commit it at 7.3.

**Comment by tristaZero** [comment]
> Take No.9, will commit it at 7.3.

Got it, thanks for coming.

**Comment by wcsoft** [comment]
https://github.com/apache/shardingsphere/pull/6261

**Comment by wcsoft** [comment]
Add proxy translaction in English https://github.com/apache/shardingsphere/pull/6261

pls review.

**Comment by tristaZero** [comment]
> Add proxy translaction in English #6261
> 
> pls review.

Thanks for your effort, actually the review is ongoing, please leave us a few of time.

Trista

**Comment by tristaZero** [comment]
Hi,
An update here. There are only one article to be translated. Does anyone want to take with it?
- [ ] 8. [The quick explanation of ShardingSphere transaction module]

**Comment by rudy2steiner** [comment]
> Hi,
> An update here. There are only one article to be translated. Does anyone want to take it?
> 
> * [ ]  8. [The quick explanation of ShardingSphere transaction module]

I'll work on it

**Comment by tristaZero** [comment]
Thanks @rudy2steiner, follow your schedule to translate it. :)

**Comment by tristaZero** [comment]
Hi @rudy2steiner How it is going now?

**Comment by rudy2steiner** [comment]
> Hi @rudy2steiner How it is going now?

will be ready on this weekend

**Comment by tristaZero** [comment]
@rudy2steiner  Great!
