### ISSUE TITLE
dateTimeUpper never used in AutoIntervalShardingAlgorithm

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6073]
The field `dateTimeUpper` never used in `AutoIntervalShardingAlgorithm`, please check the usage and document

**Comment by tristaZero** [comment]
@terrymanu Thanks for your issue.
I dug the commit history and found `private LocalDateTime dateTimeUpper;` is what you added. My commit record told me I did not need this member.
Please give it a look, thanks.

**Comment by terrymanu** [comment]
Ok, maybe wrong for copy, we can remove this field
