### ISSUE TITLE
可否增加对不带分片键的dml、dql进行限制的功能

### ISSUE THREAD

**Issue by DreamerBear** [apache/shardingsphere#6084]
业务方在使用sharding-jdbc操作分库分表数据源时，动态sql拼接后容易出现不带分片键的dml和dql

尤其是update语句，容易导致全部分表更新的问题，造成线上事故

因此想问下sharding-jdbc有没有 对不带分片键的dml、dql语句进行限制的功能，或者有没有一种插件机制去增加这种功能？

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
