### ISSUE TITLE
 Is there a configuration or function to restrict dml and dql without shard key?

### ISSUE THREAD

**Issue by DreamerBear** [apache/shardingsphere#6087]
When the business party uses sharding-jdbc to operate the sharding data source, after dynamic SQL splicing, dml and dql without the shard key are easy to appear

Especially the update statement can easily lead to the problem of updating all parts of the table, causing online accidents

Therefore, I would like to ask whether sharding-jdbc has the function of restricting the dml and dql statements without the shard key, or is there a plug-in mechanism to increase this function?

**Comment by terrymanu** [comment]
Can you give a example?

**Comment by terrymanu** [comment]
Closed because of no response anymore
