### ISSUE TITLE
Seata integrating sharding JDBC exception:  Failed to fetch schema of trend_chart（trend_chart table name）

### ISSUE THREAD

**Issue by yyjgit66** [apache/shardingsphere#6094]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
sharding jdbc 4.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere JDBC
### Expected behavior
Normal access to database
### Actual behavior
java.lang.String cannot be cast to java.lang.Integer
### Reason analyze (If you can)
The char type of PostgreSQL is 16 org.apache.shardingsphere . shardingjdbc.jdbc.core . resultset.DatabaseMetaDataResultSet#getInt Conversion of this row of (int) failed

(Integer) ResultSetUtil.convertValue ( this.currentDatabaseMetaDataObject .getObject(columnIndex), Integer.TYPE );
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
After using sharding JDBC and Seata integration. When inserting org.apache.shardingsphere . shardingjdbc.jdbc.core . resultset.DatabaseMetaDataResultSet#getInt (integer) of (int) ResultSetUtil.convertValue ( this.currentDatabaseMetaDataObject .getObject(columnIndex), Integer.TYPE ）; this line of code reports java.lang.String cannot be cast to java.lang.Integer

**Comment by kimmking** [comment]
you should try 4.1.1
