### ISSUE TITLE
Create the introduction document of Sharding-example module

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6113]
Since there is no document to introduce how to run the Sharding-example module, newcomers will feel confused.
It is necessary to create the introduction document of [Sharding-example module](https://github.com/apache/shardingsphere/tree/master/examples), and the following items can be considered to include.

### Content
- [ ] The preparations for examples, such as databases, user, IDE and so on
- [ ] The main entries for different examples
- [ ] The introduction of test scenarios
- [ ] How to run

### How
- [ ] Create a new directory [here](https://github.com/apache/shardingsphere/tree/master/docs/document/content). 
- [ ] Add `exmaples.cn.md` for Chinese content, and `exmaples.en.md` for English one
- [ ] Referring to other files to write documents
- [ ] Raise a PR

If you are interested in this one, **please comment below** (Then I will assign this one to you). Welcome your joining!

**Comment by xbkaishui** [comment]
let me try.  a coupe of questions?  
- what's is the best way to run the example module?  for now I just import only the example module as a new project  :blush: 
- the example module contains so much functions. I can't cover them all :cry:

**Comment by tristaZero** [comment]
> let me try. a coupe of questions?
> 
> * what's is the best way to run the example module?  for now I just import only the example module as a new project  😊
> * the example module contains so much functions. I can't cover them all 😢

Hi @xbkaishui 
For the first one, Yep maybe it seems a better way to run the example module, but someone wonders whether `mvn spring-boot run` could work well with the help of `spring-boot plugin` instead of import it as a project.
Back to the second one, I could not get your point. A lot of functions confused you very much, and so?

**Comment by JiekerTime** [comment]
I will do it latter. But before that, I need to get familiar with the structure of the framework.

**Comment by tristaZero** [comment]
Welcome, @JiekerTime take your time.

**Comment by tristaZero** [comment]
Hi @JiekerTime ,

I gave a look at the example module, and here is its [readme](https://github.com/apache/shardingsphere/blob/master/examples/README.md), which has a basic introduction of example. Thus, I  guess there is no necessity to provide another doc.

Still, thanks for your attention.
