### ISSUE TITLE
Update governance document 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6127]
- [x] user-manual/shardingsphere-jdbc/configuration/yaml/governance.cn.md
- [x] user-manual/shardingsphere-jdbc/configuration/yaml/governance.en.md
- [x] user-manual/shardingsphere-jdbc/configuration/java-api/governance.cn.md
- [x] user-manual/shardingsphere-jdbc/configuration/java-api/governance.en.md
- [x] user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/governance.cn.md
- [x] user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/governance.en.md
- [x] user-manual/shardingsphere-jdbc/configuration/spring-namespace/governance.cn.md
- [x] user-manual/shardingsphere-jdbc/configuration/spring-namespace/governance.en.md

**Comment by menghaoranss** [comment]
There are two more documents:

user-manual/shardingsphere-jdbc/configuration/java-api/governance.cn.md
user-manual/shardingsphere-jdbc/configuration/java-api/governance.en.md
