### ISSUE TITLE
Update common data source configuration

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6128]
- [x] user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/_index.en.md
- [x] user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/_index.cn.md
- [x] user-manual/shardingsphere-proxy/configuration/data-source.en.md
- [x] user-manual/shardingsphere-proxy/configuration/data-source.cn.md

**Comment by yu199195** [comment]
i will fix

**Comment by yu199195** [comment]
now，common data source configuration， also support springboot  and sharding-proxy yaml
