### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find JDBC type '2003' in PostgreSQL column type

### ISSUE THREAD

**Issue by rick2678** [apache/shardingsphere#6132]
Bug Report
Which version of ShardingSphere did you use?
4.1.1

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-proxy

Expected behavior
connection 
my yaml
![image](https://user-images.githubusercontent.com/67138442/85101000-fe6f3a80-b233-11ea-8c24-9b2b92896d49.png)

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/6232 .
