### ISSUE TITLE
jdbc loadbalace not support

### ISSUE THREAD

**Issue by chickFish** [apache/shardingsphere#6137]
## Question
i find 4.1.0 support failover url( #5247),i use durid set jdbc url=jdbc:mysql:loadbalance//ip:port,ip:port/db
but i find
![图片](https://user-images.githubusercontent.com/39667503/85116445-ec9b9080-b24f-11ea-8862-a75ac79b71fe.png)
throw Exception because connection url is jdbc://ip:port with no database
first i think it may be using druid cause,but i debug find that connection url(myUrl) will be set by  mysql-connector and when i use loadbalance/replication ,myUrl of connection  really not cotain database
so loadbalace or replication can be used really？or i use in wrong way
mysql-connector-java:5.1.34

**Comment by kimmking** [comment]
there is no plan for it.
