### ISSUE TITLE
Design and implementation of authority control model 

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#6140]
Improve authority control model of proxy, support more fine-grained permission control,  DCL operation /SQL verification, integration with config center for proxy clusters.

- [ ] 1. Design authority domain model
- [ ] 2. Design yaml configuration
- [ ] 3. Implement authority domain model
- [ ] 4. Intercept and verify SQL operation
- [ ] 5. Support config center
- [ ] 6. Sync all nodes via event notification
- [ ] 7. Support DCL statements

**Comment by dongzl** [comment]
Hi @kimmking , does this design include the MySQL's sql audit?

**Comment by menghaoranss** [comment]
looking foward.

**Comment by kimmking** [comment]
> Hi @kimmking , does this design include the MySQL's sql audit?

it's not so far.

**Comment by silverdarknight** [comment]
i'd like to try

**Comment by tristaZero** [comment]
This feature is undergoing, please refer to #9844
