### ISSUE TITLE
How to configure read-write separation? table level control

### ISSUE THREAD

**Issue by wanezu** [apache/shardingsphere#6142]

**Comment by wanezu** [comment]
How to configure read-write separation? Set some tables to go to master as long as they are associated with this table. In case of master-slave delay, complete read-write separation will cause data inconsistency.

**Comment by kimmking** [comment]
in the same tx/thread，read operation will be forced to master after write operation.

**Comment by wanezu** [comment]
![image](https://user-images.githubusercontent.com/7490236/85288147-db5cb900-b4c7-11ea-9dcf-47032acedaff.png)

**Comment by wanezu** [comment]
in the same thread, read and write operation default datasource
