### ISSUE TITLE
Please consider split table strategy support simple multi-tenancy implement (split by table one column and do not set actualDataNodes ,dynamic add splite table)

### ISSUE THREAD

**Issue by thinkwithlinc** [apache/shardingsphere#6146]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
https://github.com/apache/shardingsphere/issues/5632
https://github.com/apache/shardingsphere/issues/3680

### Describe the feature you would like.
In our toc (face to customer user) platform project，have some independent business provider( Merchant or tenant)，every tenant has it own table，for example：

**real shops**：
shop1
shop2
shop3

**three business table**(every table have column "tenant_id" indentify which shop)：
table_product
id ~ tenant_id ~ product_id ~ etc..

table_customer
id ~ tenant_id ~ customer_id ~ etc..

table_order
id ~ tenant_id ~ order_id ~ product_id ~ customer_id ~  etc..

**expect split table**：
shop1 have three table：
table_product_shop1 table_customer_shop1 table_order_shop1
shop2 have three table：
table_product_shop2 table_customer_shop2 table_order_shop2
shop3 have three table：
table_product_shop3 table_customer_shop3 table_order_shop3

**and most important** , the shop is dynamic increase
so the actualDataNodes we don't know , so need not check actualDataNodes , 
https://github.com/apache/shardingsphere/issues/3963#issue-549292357
because our  table_product_xxx is dymatic add

if expection case by our split table not create，it's my fault not sharding-jdbc

**Comment by kimmking** [comment]
It's a requirement for a specific case, so I think you should implement this case in your extends.
