### ISSUE TITLE
proxy auto-increment major key

### ISSUE THREAD

**Issue by nanyounanyounan** [apache/shardingsphere#6148]
`
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
`
I'm set proxy-keyGenerator-type=SNOWFLAKE,but it's no work,
I'm phper ,and I wan to use sharding-proxy in my project,
The JDBC not available in my project.
Can you get me some case,or tell my why it's no work in  auto-increment major key.
In  the proxy, databaseStrategy only use inline,other databaseStrategy not support?
If cant support ,can you get my some case.
thanks.

**Comment by nanyounanyounan** [comment]
I'm so sorry ,my major key is int,the snowflake need bigint.
Other databaseStrategy is supported proxy?
If they can,can you tell my how set?
thanks.

**Comment by tuohai666** [comment]
Please refer to the document:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/configuration/
