### ISSUE TITLE
4.1.1, for TableMetaDataLoader

### ISSUE THREAD

**Issue by assupg** [apache/shardingsphere#6161]
There is a question to ask, about 4.0.0-RC1 and 4.1.1, for TableMetaDataLoader
The project environment is: SpringBoot + Oracle 11g Release 2, there are about 600 tables in the database, there are 4 tables that need to be divided into tables, and there are too many indexes

4.0.0-RC1, it can be started normally during development, the loading time is a little long, but it is a bit unbearable; and when 4 upgrades to 1.1.1, the log output after startup, stays ShardingSphere-metadata :131: Loading 4 logic tables' meta data .

Read the source code IndexMetaDataLoader.load(final Connection connection, final String table, final String databaseType), connection.getMetaData().getIndexInfo(....)

**Comment by kimmking** [comment]
So,  @assupg what's your concrete problem?

**Comment by hand515** [comment]
same with  #5999

**Comment by kimmking** [comment]
> same with #5999

@hand515 in issue#5999, the behavior is not triggerred by sharding-jdbc. we can't controll it.

**Comment by hand515** [comment]
> .

The jdbc driver trigger it , and sharding-jdbc use the jdbc driver to load metadatas .
Not only Oracle, Mysql and PostgreSQL have the same problem .

**Comment by xbkaishui** [comment]
same with [#6212 ](https://github.com/apache/shardingsphere/issues/6212), I will fix in this issue

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/6212 .

**Comment by tristaZero** [comment]
Hi @assupg @hand515 

I am sorry to give my comment late. The good news that the performance of starting ShardingProxy has been greatly improved already! Thanks for @xbkaishui, who took much effort in #6212.

Presently, welcome your any test for the `master branch` (Package it local firstly). Your feedback will be the best gift for the community.

Best,
Trista
