### ISSUE TITLE
The UI of cluster state topology  optimization

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#6162]
We have completed `Cluster` feature which contains `heartbeat detection` and `cluster state topology`, and now  we can monitor the state of applications and databases in real time through `ShardingSphere-UI`. 

![微信图片_20200622164536](https://user-images.githubusercontent.com/60651792/85271879-fc181500-b4ad-11ea-8cf8-3dccaabebb47.png)

Howerver, there are still some  items of UI that need to be optimized. 

- [x] 1. Consider that add auto refresh switch button and refresh interval time selection box(60s, 120s, etc.)

Anyone who is interested or good at front-end development is welcome.

**Comment by renfufei** [comment]
Hi, @menghaoranss 
I want to join the develop work!

**Comment by kimmking** [comment]
@renfufei Expecting your forward.
