### ISSUE TITLE
Optimize proxy instance definition in registry center

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#6163]
According to the suggestions made by @dongzl and @kimmking  in the issue #5627 , use `ip+port` instead of `ip + threadId` to define proxy instance in registry center is better.

```
/
├─orchestration-namespace
├─orchestration-name
│ ├─registry
│ │ ├─instances
│ │ │ ├─127.0.0.1@3307@xxx
│ │ │ ├─127.0.0.1@3308@xxx
```

**Comment by swayamraina** [comment]
Hi!
I believe `OrchestrationInstance` holds this data of `ip + thread-id` which needs to be changed.
I am not sure how to get the port on which the instance is running.

**Comment by menghaoranss** [comment]
@swayamraina For proxy，the port can be passed to `ShardingOrchestrationFacade` when proxy starts, and for jdbc, thread id is better.

**Comment by swayamraina** [comment]
@menghaoranss can you please review yhe PR for any improvements.

**Comment by menghaoranss** [comment]
> @menghaoranss can you please review yhe PR for any improvements.

Of course, i will take the time to review, thanks for you contribution.

**Comment by kimmking** [comment]
@swayamraina Expecting your forward.

**Comment by menghaoranss** [comment]
@swayamraina any problems?

**Comment by swayamraina** [comment]
Will update the code as per review. Thanks!

**Comment by menghaoranss** [comment]
@swayamraina The pr #6187  you submitted has lasted too long, there may already be a lot of conflicts, can you please resubmit another pr based on our discussion?

**Comment by swayamraina** [comment]
sure @menghaoranss will sync the PR

**Comment by menghaoranss** [comment]
> sure @menghaoranss will sync the PR

merged! thansk for your contribution.

**Comment by swayamraina** [comment]
Thanks, will try to contribute more :)
