### ISSUE TITLE
about sharding-jdbc subquery quesetion

### ISSUE THREAD

**Issue by dxckey** [apache/shardingsphere#6164]
## about sharding-jdbc subquery quesetion

- i have a question about subquery, there is  the doc said（我有关于sharding-jdbc子查询的问题，文案上说下面的子查询框架是支持的）:
![20200622173436](https://user-images.githubusercontent.com/19223349/85273980-ea843c80-b4b0-11ea-8551-430f8f158fe6.png)

- this is my spring boot profile（spring boot sharding-jdbc 相关配置文件）:
![20200622172752](https://user-images.githubusercontent.com/19223349/85274121-1bfd0800-b4b1-11ea-8871-24a9f0ed2bf1.png)

- this is the log（执行控制台打印的语句）:
![20200622172947](https://user-images.githubusercontent.com/19223349/85274086-0f78af80-b4b1-11ea-9105-c0a68b50a353.png)
according to the doc it's should have 3 sql query like follow（根据文档的话，我的控制台应该打印以下的sql语句吧）:
``` sql
select count(a.id) from (select o.id as id from t_order_0 o) a;
select count(a.id) from (select o.id as id from t_order_1 o) a;
select count(a.id) from (select o.id as id from t_order_2 o) a;
```
- i use sharding-jdbc-spring-boot-starter:4.1.0+mybatis-spring-boot-starter:2.1.2,i want to is my profile has somewhere wrong or it doesn't support anymore
 我用的是sharding-jdbc-spring-boot-starter:4.1.0+mybatis-spring-boot-starter:2.1.2,我想知道这个功能是不支持了，还是我的配置出了问题

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
