### ISSUE TITLE
support LocalDateTime feature

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#6166]
Since current impl is not support java8 LocalDateTime, should we add the feature to support LocalDateTime?  I can try to fix this

**Comment by tuohai666** [comment]
Hi @xbkaishui,

@alterhu2020 mentioned **LocalDate, LocalTime, LocalDateTime** in https://github.com/apache/shardingsphere/issues/5203 .
Can you check whether it is the same problem in that issue?
I'am glad that you want to fix this, I can review the pr for you.

**Comment by xbkaishui** [comment]
yes, similar with @alterhu2020, wiil try to fixed and let you know.

**Comment by xbkaishui** [comment]
Hi guys, can't run the 5.0.0-RC1-SNAPSHOT with jdbc-spring-boot-starter

exception is 
`Caused by: java.lang.NullPointerException: Inline sharding algorithm expression cannot be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm.createClosure(InlineShardingAlgorithm.java:57)
	at org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm.init(InlineShardingAlgorithm.java:51)
`
I checked the master code, is this wrong or just need higher jdk ? 


public final class InlineShardingAlgorithm implements StandardShardingAlgorithm<Comparable<?>> {
    
    private static final String ALGORITHM_EXPRESSION_KEY = "algorithm.expression";
    

private Closure<?> createClosure() {
        String expression = props.getProperty(ALGORITHM_EXPRESSION_KEY);
//this is alwarys return null in jdk8 

BTW, do we have local wechat group for quickly comutations?

**Comment by jacksparrow414** [comment]
@xbkaishui you need config Inline sharding algorithm expression,like this:
![{0D66795B-37F0-4154-8057-32000A0667A5}_20200628152300](https://user-images.githubusercontent.com/33389378/85941100-5e13c700-b953-11ea-97cf-fc8c5ab7a6e2.jpg)

**Comment by xbkaishui** [comment]
@jacksparrow414  this is works for 4.x version ,  not work for 5.x version

**Comment by jacksparrow414** [comment]
> @jacksparrow414 this is works for 4.x version , not work for 5.x version

if it is 5.x version, you could try config like this:
```properties
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name=checking-transaction-detail-order-inline  
spring.shardingsphere.rules.sharding.sharding-algorithms.checking-transaction-detail-order-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.checking-transaction-detail-order-inline.props.algorithm.expression=ds_$->{user_id % 2}
```
I don't find something like first line in your config

**Comment by xbkaishui** [comment]
> > @jacksparrow414 this is works for 4.x version , not work for 5.x version
> 
> if it is 5.x version, you could try config like this:
> 
> ```ini
> spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name=checking-transaction-detail-order-inline  
> spring.shardingsphere.rules.sharding.sharding-algorithms.checking-transaction-detail-order-inline.type=INLINE
> spring.shardingsphere.rules.sharding.sharding-algorithms.checking-transaction-detail-order-inline.props.algorithm.expression=ds_$->{user_id % 2}
> ```
> 
> I don't find something like first line in your config

sorry just miss the spring root level, for now I just convert the properties file to yaml, it is same as your point.

**Comment by jacksparrow414** [comment]
@xbkaishui it should not version matters,it just config wrong.cause source code  
![1593395533(1)](https://user-images.githubusercontent.com/33389378/85965094-505f4f80-b9ee-11ea-9945-8c2451f9f946.jpg)

**Comment by xbkaishui** [comment]
<img width="1226" alt="屏幕快照 2020-06-28 下午10 50 21" src="https://user-images.githubusercontent.com/1477791/85967539-47be4780-b9f5-11ea-97a3-c07f94d8fa55.png">

this is debug view in myside.  in the props object,  algorithm and expression are separated
