### ISSUE TITLE
EncryptDataSource cannot be cast to ShardingDataSource

### ISSUE THREAD

**Issue by moses-keqi** [apache/shardingsphere#6175]
## Question
EncryptDataSource cannot be cast to ShardingDataSource
**For English only**, other languages will not accept.
 aes Encrypt   EncryptDataSource cannot be cast to ShardingDataSource
version: 4.0.0-RC2

Before asking a question, make sure you have:

spring:
  shardingsphere:
    props:
      proxy:
        transaction:
          type: xa
          enabled: true
      sql.show: true
    encrypt:
      encryptors:
        encryptor_aes:
          type: aes
          props:
            aes.key.value: Metlife202005030
      tables:
        zz_sms_send:
          columns:
            mobile:
              cipherColumn: mobile
              encryptor: encryptor_aes
        activity_record:
          columns:
            mobile:
              cipherColumn: reply_mobile
              encryptor: encryptor_aes
        blacklist:
          columns:
            mobile:
              cipherColumn: mobile
              encryptor: encryptor_aes

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

nested exception is java.lang.ClassCastException: org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.EncryptDataSource cannot be cast to org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource

**Comment by kimmking** [comment]
Could you try 4.1.1 ?

**Comment by moses-keqi** [comment]
> Could you try 4.1.1 ?

version: 4.0.0-RC2

**Comment by menghaoranss** [comment]
@moses-keqi you can upgrade to `4.1.1` version and try again.

**Comment by moses-keqi** [comment]
> @moses-keqi you can upgrade to `4.1.1` version and try again.

upgrade to 4.1.1 version sqlserver2012 use what version drives ,now drives not support

**Comment by tristaZero** [comment]
@moses-keqi Hi
> nested exception is java.lang.ClassCastException: org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.EncryptDataSource cannot be cast to org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource

These parts of the log can not give us some useful hints, so more detailed logs are needed.
Besides, At first glance, it looks like you mix up the `ShardingRule` and `EncryptRule.` My suggestion is you'd better review your configuration referring to our document.

Thanks,
Trista

**Comment by tristaZero** [comment]
Since there is no any feedback beyond 7 days, I have to close it.
