### ISSUE TITLE
Add unit test case for #4665

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6177]
Although #4680 was fixed by #4665, it is necessary to add a unit test to cover that special scenario. Besides, the check style of #4665 is needed to take care of as well. Please consider the items below.
- [x] Remove the redundant blank line in 146 Line of `GroupByMemoryMergedResult`
- [x] Instead of `tab`, lines beginning with 4 white spaces are preferable in `GroupByMemoryMergedResult `
- [x] Add a unit test

**Comment by kimmking** [comment]
FOLLOW IT.
