### ISSUE TITLE
max.connections.size.per.query affects database performance

### ISSUE THREAD

**Issue by 18511699755** [apache/shardingsphere#6179]
There are 7000 tables in the test target library, and the default value will start slowly, and the high setting value will lead to the soaring cpu and iops of the database

**Comment by tuohai666** [comment]
1. Have you closed check.table.metadata.enabled property?
2. How many databases and hosts hold that 7000 tables?
3. Please show the detail configurations of ShardingSphere.
4. Please fill in the template following.

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by 18511699755** [comment]
config：
spring.shardingsphere.datasource.names=db0

spring.shardingsphere.datasource.db0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.db0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.db0.url=jdbc:mysql://localhost:3306/ttt?useUnicode=true&characterEncoding=utf-8
spring.shardingsphere.datasource.db0.username=root
spring.shardingsphere.datasource.db0.password=root

spring.shardingsphere.props.sql.show=true
spring.shardingsphere.props.max.connections.size.per.query=1

spring.shardingsphere.sharding.tables.demo.actual-data-nodes=db0.demo_$->{0..1023}
spring.shardingsphere.sharding.tables.demo.database-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.demo.database-strategy.inline.algorithm-expression=db0
spring.shardingsphere.sharding.tables.demo.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.demo.table-strategy.inline.algorithm-expression=demo_$->{id % 1024}


The application needs more than 10 minutes to start

**Comment by 18511699755** [comment]
2020-06-24 11:37:38.592  INFO 61443 --- [           main] ShardingSphere-metadata                  : Loading 1 logic tables' meta data.
2020-06-24 11:37:39.538  INFO 61443 --- [           main] ShardingSphere-metadata                  : Loading 7169 tables' meta data.
2020-06-24 11:58:01.251  INFO 61443 --- [           main] ShardingSphere-metadata                  : Meta data load finished, cost 1222709 milliseconds.
2020-06-24 11:58:01.741  INFO 61443 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-06-24 11:58:02.004  INFO 61443 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8085 (http) with context path ''

**Comment by tuohai666** [comment]
OK. Yes, ShardingSphere will load all table names of actual datasources. The **7169 tables** in the log indicates that there are 7169 tables in ttt, although 6145 of them are not present in config file. 

I noticed that you use only one machine. If your hardware environment is not good, the meta data loading procedure will cost much time.

Can you create another database like **sss** contains only 1024 tables you really want to use and have a test?

**Comment by 18511699755** [comment]
Do you mean a machine where the application is located or a database machine?
There are 6 machines in our production environment, but there is only one database instance, and 7169 tables will be used in the production environment.

**Comment by tuohai666** [comment]
I mean database machine.

**Comment by 18511699755** [comment]
That is, if there are 7169 tables, do you need to use multiple instances (machines) in the database? If so, the cost may be higher. Is there any other solution?

**Comment by tuohai666** [comment]
Actually, we don't expect 1222709 milliseconds for meta data loading for 7169 tables.
Time cost for one query: 1222709/7169 = 170ms
IMO, this kind of query usually cost 1~2ms or even less.

There're two possibilities:
1. There's bug in ShardingSphere. I'll double check.
2. You machine is two slow. Please provide your hardware environment. And check is there any other service running on this machine.

**Comment by 18511699755** [comment]
okay, thank you

**Comment by tuohai666** [comment]
Hi @18511699755 
1. Please provide your hardware environment. 
2. And check is there any other service running on this machine.

Please don't just ignore my question, the answer is also important reference to me.

**Comment by 18511699755** [comment]
Type of database: MySQL 5.7
Cpu: 4 cores
Database memory: 16384MB

The application machine mac os 10.15.3

At present, debug found this exception, and the source code exception was ignore.
java.sql.SQLFeatureNotSupportedException
	at com.alibaba.druid.pool.DruidPooledConnection.getSchema(DruidPooledConnection.java:1191)
	at org.apache.shardingsphere.sql.parser.binder.metadata.util.JdbcUtil.getSchema(JdbcUtil.java:41)

Every time I load metadata, I log it, and the time is between 90ms and 400ms

**Comment by 18511699755** [comment]
There are also services that use this database, but monitoring has little impact on performance.

**Comment by tuohai666** [comment]
Is the mac your personal machine for working? What's the average load of it?

**Comment by tuohai666** [comment]
You said there's one machine in production environment, why you provide a mac hardware environment?
Is all data in this issue based on the mac?

**Comment by 18511699755** [comment]
Yes, the machine on which the program runs is mac, but the database is a database instance based on Alibaba Cloud.
The machine load is below 2.0.
mac os 6 core 16G.

**Comment by 18511699755** [comment]
At present, it is in the testing stage, and there are no machines produced on it

**Comment by 18511699755** [comment]
The performance of the machine where the program is located is no problem, and the configuration of the daily database may be lower.

**Comment by tuohai666** [comment]
What's the latency between the cloud service and your mac?

**Comment by 18511699755** [comment]
Are you referring to the cloud service database?

**Comment by tuohai666** [comment]
You can ping the cloud host from your mac.

**Comment by 18511699755** [comment]
The local delay is relatively high within 20ms, so I will apply for a daily machine and test it again.

**Comment by hand515** [comment]
```
[INFO ColumnMetaDataLoader:84] - load column metadata for table=t1 use 192.2264ms
[INFO IndexMetaDataLoader:62] - load index metadata for table=t1 use 38.0993ms
[INFO ColumnMetaDataLoader:84] - load column metadata for table=t2 use 392.8141ms
[INFO IndexMetaDataLoader:62] - load index metadata for table=t2 use 37.5664ms
[INFO ColumnMetaDataLoader:84] - load column metadata for table=t3 use 267.1177ms
[INFO IndexMetaDataLoader:62] - load index metadata for table=t3 use 38.5584ms
[INFO ColumnMetaDataLoader:84] - load column metadata for table=t4 use 500.384ms
[INFO IndexMetaDataLoader:62] - load index metadata for table=t4 use 38.3369ms
```

Using 5.0-RC1 -SNAPSHOT, add some metric code in ColumnMetaDataLoader.load and IndexMetaDataLoader.load.

The time is not related to the number of columns .

Properties:
```
max.connections.size.per.query: '10'
sql.show: 'true'
check.table.metadata.enabled: 'false'
```

Client pings to db server: 29ms

**Comment by tuohai666** [comment]
@hand515 I noticed that ColumnMetaDataLoader.load is more slower than IndexMetaDataLoader.load. I'll check.

**Comment by 18511699755** [comment]
load average: 1.27, 0.51, 0.22
ShardingSphere-metadata - rt : 34ms

**Comment by 18511699755** [comment]
load average: 1.27, 0.51, 0.22
The load of the machine where the application is located is about 35ms.
Machine and database delay is about 0.09ms

**Comment by 18511699755** [comment]
load average: 1.27, 0.51, 0.22
On average, it takes 35m's to load metadata every time.
Machine and database delay is about 0.09ms

**Comment by tuohai666** [comment]
What's the load average for? MySQL or ShardingSphere? Please record the load of servers for both MySQL and ShardingSphere.

**Comment by 18511699755** [comment]
The average server load in ShardingSphere is around 1.1

**Comment by tuohai666** [comment]
What's the total time this time?
Set the property spring.shardingsphere.props.max.connections.size.per.query to 1/2/4/8/16/32/64, record the log and show me the total time.

**Comment by tuohai666** [comment]
Compare to 
`2020-06-24 11:58:01.251 INFO 61443 --- [ main] ShardingSphere-metadata : Meta data load finished, cost 1222709 milliseconds.
`
What's the cost this time?

**Comment by 18511699755** [comment]
Set the property spring.shardingsphere.props.max.connections.size.per.query to 1, cost 258084 milliseconds

**Comment by 18511699755** [comment]
Set the property spring.shardingsphere.props.max.connections.size.per.query to 64,  database load is basically running at full load, and the cpu is full

**Comment by tuohai666** [comment]
Not only the 1 and 64. Please try 1/2/4/8/16/32/64.

**Comment by tuohai666** [comment]
I have captured some packets and studied the codes. There're 7 SQLs sent to MySQL every table for meta data purpose. In your case, there're 7 * 7169 = 50183 SQLs to be executed. The average response time is 258084 / 50183 = 5 ms. It's slow but acceptable if your server has only 4 cores.

The conclusion is that you can adjust spring.shardingsphere.props.max.connections.size.per.query to a suitable value to make the initialization faster without full load. Meanwhile, I will try to reduce the interaction times during meta data procedure.

**Comment by hand515** [comment]
According to mysql jdbc driver(mysql-connector-java:5.1.34) , load metadata will execute 4 sql (use wireshark to capture)
```
TableMetaDataLoader.isTableExists
1. show full tables from db_name like '%'   

ColumnMetaDataLoader
1. show full columns from table_name.
2. select * from table_name where 1!=1
IndexMetaDataLoader
1. show index from table_name

```

**Comment by tuohai666** [comment]
@hand515 There are 3 more:
![image](https://user-images.githubusercontent.com/24643893/86014328-c4cbda00-ba52-11ea-93ee-525db294400d.png)

**Comment by 18511699755** [comment]
Well, I'll try debugging. Will the optimization you mentioned be iterated in subsequent versions?

**Comment by tuohai666** [comment]
Yes, will exist in next release.

**Comment by tuohai666** [comment]
Duplicate with https://github.com/apache/shardingsphere/issues/6212 .

**Comment by tristaZero** [comment]
Hi @hand515 @18511699755 ,

I am sorry to give my comment late. The good news that the performance of starting ShardingProxy has been greatly improved already! Thanks for @xbkaishui, who took much effort in #6212.

Presently, welcome your any test for the `master branch` (Package it local firstly). Your feedback will be the best gift for the community.

Best,
Trista
