### ISSUE TITLE
mismatched input 'SOURCE' expecting {TRUNCATE, ..., IDENTIFIER_}

### ISSUE THREAD

**Issue by JOYS369** [apache/shardingsphere#6204]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.0.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-namespace</artifactId>
            <version>4.0.1</version>

        </dependency>
                <dependency>
                    <groupId>org.antlr</groupId>
                    <artifactId>antlr4-runtime</artifactId>
                    <version>4.7.1</version>
                </dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 4.0.1，antlr 4.7.1

### Expected behavior
1、the project can start  Running in MAC ，but can't start Running in window.（Multiple computers tests，It's all like this）
2、update statement  error
UPDATE  HMDM_MD_FIN001  
 SET REQUEST_ID = ?,PROGRAM_ID = ?,OBJECT_VERSION_NUMBER=?+1,LAST_UPDATED_BY=?,
 LAST_UPDATE_DATE=CURRENT_TIMESTAMP,LAST_UPDATE_LOGIN=?,MD_DESCRIPTION = ?,
 MD_TOP_CATE_CODE = ?,MD_CATE_CODE = ?,STATUS_CODE = ?,LAST_UPDATED_SOURCE_CODE = ?,
 START_DATE = ?,END_DATE = ?,REF_ORG_ID = ?,APPLY_ID = ?,APPLY_ITEM = ?,APPLIED_BY = ?,
 APPLIED_AT = ?,ENTITY_LAST_UPDATE_DATE = ?,LAST_DISTRIBUTE_DATE = ?,
 FLEX_VALUE_DISP= ?,STRUCTURED_HIERARCHY_NAME= ?,FLEX_VALUE_MEANING= ?,
 CHILD_FLEX_VALUE_HIGH_DISP= ?,SUB_ACC= ?,TAX_TARE= ?,RANGE_ATTRIBUTE= ?,
 THIRD_PARTY_CONTROL_ACCOUNT= ?,SEGMENT_TYPE= ?,ADJUST= ?,REV_ITEM= ?,REV_INFOR= ?,
 DESCRIPTION= ?,ENABLED_FLAG= ?,ACTIVITITY_INFOR= ?,CHILD_FLEX_VALUE_LOW_DISP= ?,
 VAT_AC_TYPE= ?,ALLOW_BUDGET= ?,HIERARCHY_LEVEL= ?,ALLOW_POSTING= ?,BUSINESS_TYPE= ?,
 SUMMARY_FLAG= ?,SOURCE= ?,CONTEXT= ?,PROCESS_NODE= ?,ACCOUNT_TYPE= ? 
 WHERE  ID = ?

error message：
mismatched input 'SOURCE' expecting {TRUNCATE, POSITION, VIEW, ANY, OFFSET, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, BOOLEAN, DATE, TIME, TIMESTAMP, YEAR, QUARTER, MONTH, WEEK, DAY, HOUR, MINUTE, SECOND, MICROSECOND, MAX, MIN, SUM, COUNT, AVG, CURRENT, ENABLE, DISABLE, INSTANCE, DO, DEFINER, CASCADED, LOCAL, CLOSE, OPEN, NEXT, NAME, TYPE, TABLES, TABLESPACE, COLUMNS, FIELDS, INDEXES, STATUS, MODIFY, VALUE, DUPLICATE, FIRST, LAST, AFTER, OJ, ACCOUNT, USER, ROLE, START, TRANSACTION, WITHOUT, ESCAPE, SUBPARTITION, STORAGE, SUPER, TEMPORARY, THAN, UNBOUNDED, UPGRADE, VALIDATION, ROLLUP, SOUNDS, UNKNOWN, OFF, ALWAYS, COMMITTED, LEVEL, NO, PASSWORD, PRIVILEGES, ACTION, ALGORITHM, AUTOCOMMIT, BTREE, CHAIN, CHARSET, CHECKSUM, CIPHER, CLIENT, COALESCE, COMMENT, COMPACT, COMPRESSED, COMPRESSION, CONNECTION, CONSISTENT, DATA, DISCARD, DISK, ENCRYPTION, END, ENGINE, EVENT, EXCHANGE, EXECUTE, FILE, FIXED, FOLLOWING, GLOBAL, HASH, IMPORT_, LESS, MEMORY, NONE, PARSER, PARTIAL, PARTITIONING, PERSIST, PRECEDING, PROCESS, PROXY, QUICK, REBUILD, REDUNDANT, RELOAD, REMOVE, REORGANIZE, REPAIR, REVERSE, SESSION, SHUTDOWN, SIMPLE, SLAVE, VISIBLE, INVISIBLE, ENFORCED, AGAINST, LANGUAGE, MODE, QUERY, EXTENDED, EXPANSION, VARIANCE, MAX_ROWS, MIN_ROWS, SQL_BIG_RESULT, SQL_BUFFER_RESULT, SQL_CACHE, SQL_NO_CACHE, STATS_AUTO_RECALC, STATS_PERSISTENT, STATS_SAMPLE_PAGES, ROW_FORMAT, WEIGHT_STRING, COLUMN_FORMAT, INSERT_METHOD, KEY_BLOCK_SIZE, PACK_KEYS, PERSIST_ONLY, BIT_AND, BIT_OR, BIT_XOR, GROUP_CONCAT, JSON_ARRAYAGG, JSON_OBJECTAGG, STD, STDDEV, STDDEV_POP, STDDEV_SAMP, VAR_POP, VAR_SAMP, AUTO_INCREMENT, AVG_ROW_LENGTH, DELAY_KEY_WRITE, ROTATE, MASTER, BINLOG, ERROR, SCHEDULE, COMPLETION, EVERY, HOST, SOCKET, PORT, SERVER, WRAPPER, OPTIONS, OWNER, RETURNS, CONTAINS, SECURITY, INVOKER, TEMPTABLE, MERGE, UNDEFINED, DATAFILE, FILE_BLOCK_SIZE, EXTENT_SIZE, INITIAL_SIZE, AUTOEXTEND_SIZE, MAX_SIZE, NODEGROUP, WAIT, LOGFILE, UNDOFILE, UNDO_BUFFER_SIZE, REDO_BUFFER_SIZE, HANDLER, PREV, ORGANIZATION, DEFINITION, DESCRIPTION, REFERENCE, FOLLOWS, PRECEDES, IMPORT, CONCURRENT, XML, DUMPFILE, SHARE, CODE, CONTEXT, CHANNEL, CLONE, AGGREGATE, INSTALL, UNINSTALL, RESOURCE, EXPIRE, NEVER, HISTORY, OPTIONAL, REUSE, MAX_QUERIES_PER_HOUR, MAX_UPDATES_PER_HOUR, MAX_CONNECTIONS_PER_HOUR, MAX_USER_CONNECTIONS, RETAIN, RANDOM, OLD, ISSUER, SUBJECT, CACHE, GENERAL, SLOW, USER_RESOURCES, EXPORT, RELAY, HOSTS, FLUSH, RESET, RESTART, UNIX_TIMESTAMP, LOWER, UPPER, IDENTIFIER_}

### Actual behavior
1、can't start Running in window
2、can't update data

### Reason analyze (If you can)
my table's attribute SOURCE,
the KEYWORD is conflicted？

**Comment by dongzl** [comment]
Hi @JOYS369   you can try the newest version `4.1.1`.

**Comment by kimmking** [comment]
Or try with a back quota:
> `source`

**Comment by JOYS369** [comment]
> Hi @JOYS369 you can try the newest version `4.1.1`.

Hi, I tried it，but can't start the project Running in window .
mismatched input 'text' expecting {TRUNCATE, ..., IDENTIFIER_}

**Comment by JOYS369** [comment]
> Or try with a back quota:
> 
> > `source`
error message：
mismatched input 'source' expecting {TRUNCATE, POSITION, VIEW, ANY, OFFSET, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, BOOLEAN, DATE, TIME, TIMESTAMP, YEAR, QUARTER, MONTH, WEEK, DAY, HOUR, MINUTE, SECOND, MICROSECOND, MAX, MIN, SUM, COUNT, AVG, CURRENT, ENABLE, DISABLE, INSTANCE, DO, DEFINER, CASCADED, LOCAL, CLOSE, OPEN, NEXT, NAME, TYPE, TABLES, TABLESPACE, COLUMNS, FIELDS, INDEXES, STATUS, MODIFY, VALUE, DUPLICATE, FIRST, LAST, AFTER, OJ, ACCOUNT, USER, ROLE, START, TRANSACTION, WITHOUT, ESCAPE, SUBPARTITION, STORAGE, SUPER, TEMPORARY, THAN, UNBOUNDED, UPGRADE, VALIDATION, ROLLUP, SOUNDS, UNKNOWN, OFF, ALWAYS, COMMITTED, LEVEL, NO, PASSWORD, PRIVILEGES, ACTION, ALGORITHM, AUTOCOMMIT, BTREE, CHAIN, CHARSET, CHECKSUM, CIPHER, CLIENT, COALESCE, COMMENT, COMPACT, COMPRESSED, COMPRESSION, CONNECTION, CONSISTENT, DATA, DISCARD, DISK, ENCRYPTION, END, ENGINE, EVENT, EXCHANGE, EXECUTE, FILE, FIXED, FOLLOWING, GLOBAL, HASH, IMPORT_, LESS, MEMORY, NONE, PARSER, PARTIAL, PARTITIONING, PERSIST, PRECEDING, PROCESS, PROXY, QUICK, REBUILD, REDUNDANT, RELOAD, REMOVE, REORGANIZE, REPAIR, REVERSE, SESSION, SHUTDOWN, SIMPLE, SLAVE, VISIBLE, INVISIBLE, ENFORCED, AGAINST, LANGUAGE, MODE, QUERY, EXTENDED, EXPANSION, VARIANCE, MAX_ROWS, MIN_ROWS, SQL_BIG_RESULT, SQL_BUFFER_RESULT, SQL_CACHE, SQL_NO_CACHE, STATS_AUTO_RECALC, STATS_PERSISTENT, STATS_SAMPLE_PAGES, ROW_FORMAT, WEIGHT_STRING, COLUMN_FORMAT, INSERT_METHOD, KEY_BLOCK_SIZE, PACK_KEYS, PERSIST_ONLY, BIT_AND, BIT_OR, BIT_XOR, GROUP_CONCAT, JSON_ARRAYAGG, JSON_OBJECTAGG, STD, STDDEV, STDDEV_POP, STDDEV_SAMP, VAR_POP, VAR_SAMP, AUTO_INCREMENT, AVG_ROW_LENGTH, DELAY_KEY_WRITE, ROTATE, MASTER, BINLOG, ERROR, SCHEDULE, COMPLETION, EVERY, HOST, SOCKET, PORT, SERVER, WRAPPER, OPTIONS, OWNER, RETURNS, CONTAINS, SECURITY, INVOKER, TEMPTABLE, MERGE, UNDEFINED, DATAFILE, FILE_BLOCK_SIZE, EXTENT_SIZE, INITIAL_SIZE, AUTOEXTEND_SIZE, MAX_SIZE, NODEGROUP, WAIT, LOGFILE, UNDOFILE, UNDO_BUFFER_SIZE, REDO_BUFFER_SIZE, HANDLER, PREV, ORGANIZATION, DEFINITION, DESCRIPTION, REFERENCE, FOLLOWS, PRECEDES, IMPORT, CONCURRENT, XML, DUMPFILE, SHARE, CODE, CONTEXT, CHANNEL, CLONE, AGGREGATE, INSTALL, UNINSTALL, RESOURCE, EXPIRE, NEVER, HISTORY, OPTIONAL, REUSE, MAX_QUERIES_PER_HOUR, MAX_UPDATES_PER_HOUR, MAX_CONNECTIONS_PER_HOUR, MAX_USER_CONNECTIONS, RETAIN, RANDOM, OLD, ISSUER, SUBJECT, CACHE, GENERAL, SLOW, USER_RESOURCES, EXPORT, RELAY, HOSTS, FLUSH, RESET, RESTART, UNIX_TIMESTAMP, LOWER, UPPER, IDENTIFIER_}

**Comment by tristaZero** [comment]
Hi  @JOYS369 
`source` did not work, did it?

**Comment by JOYS369** [comment]
> did not work, did it?

Hi,I tried it , change 'SOURCE' to 'source'。Still reporting errors。
analogous error message：
mismatched input 'source' expecting {TRUNCATE, ..., IDENTIFIER_}

**Comment by JOYS369** [comment]
> > did not work, did it?
> 
> Hi,I tried it , change 'SOURCE' to 'source'。Still reporting errors。
> analogous error message：
> mismatched input 'source' expecting {TRUNCATE, ..., IDENTIFIER_}

I tried use table's alias, update data sucess.
but, log also has error message,
line 1:136 no viable alternative at input 'CURRENT_TIMESTAMP,'
line 1:136 no viable alternative at input 'CURRENT_TIMESTAMP,'
line 1:828 mismatched input 'source' expecting  {TRUNCATE, ..., IDENTIFIER_}


Do you know how to slave first question?
1、the project can start Running in MAC ，but can't start Running in window.（Multiple computers tests，It's all like this）
It's very inconvenient，because I need to user other computer to test.

**Comment by tristaZero** [comment]
Everything works well on Mac, however, does not work well on win?

**Comment by tristaZero** [comment]
@jingshanglu Hi, could you give a look at his SQL, especially the keywords `source` and`CURRENT_TIMESTAMP `? Do you think there is something wrong with sharding parser?

**Comment by jingshanglu** [comment]
@JOYS369 @tristaZero  There is no wrong with sharding parser, i have tried it. Now everything works well on Mac, may be the problem with the windows environment.

**Comment by JOYS369** [comment]
> @JOYS369 @tristaZero There is no wrong with sharding parser, i have tried it. Now everything works well on Mac, may be the problem with the windows environment.

project can't start Running in window；
the second question is found Running in MAC.

**Comment by jingshanglu** [comment]
> > Hi @JOYS369 you can try the newest version `4.1.1`.
> 
> Hi, I tried it，but can't start the project .
> mismatched input 'text' expecting {TRUNCATE, ..., IDENTIFIER_}

@JOYS369 use version '4.1.1' ,will the second question occur? i have tried it on  '4.1.1' , it's ok. Can you show more detail info(eg:log stack).

**Comment by jingshanglu** [comment]
@JOYS369 You use pg?

**Comment by jingshanglu** [comment]
@JOYS369 @tristaZero Well , i reproduce it, the pr #6211 fix it.

**Comment by JOYS369** [comment]
> > > Hi @JOYS369 you can try the newest version `4.1.1`.
> > 
> > 
> > Hi, I tried it，but can't start the project .
> > mismatched input 'text' expecting {TRUNCATE, ..., IDENTIFIER_}
> 
> @JOYS369 use version '4.1.1' ,will the second question occur? i have tried it on mysql use '4.1.1' , it's ok. Can you show more detail info(eg:log stack).

 I tried it，but can't start the project use version 4.1.1 . 
It will throw an errormismatched input 'text' expecting {TRUNCATE, ..., IDENTIFIER_}

so I use version '4.0.1',my computer is window10，my partner computer is MAC

**Comment by tristaZero** [comment]
@JOYS369 Hi thanks for your feedback.
 #6211 made `test` parsed fine. Besides, `CURRENT_TIMESTAMP ` and `source ` could also work well on master branch.
