### ISSUE TITLE
Support more java types for  getObject with type method

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#6209]
the getObject with type of  AbstractUnsupportedOperationResultSet current impl  is throw SQLFeatureNotSupportedException,
```
public final Object getObject(final int columnIndex, final Map<String, Class<?>> map) throws SQLException {
        throw new SQLFeatureNotSupportedException("getObject with map");
    }
```

I have enhanced it to support local date and time,  It's should support more java types defines in  java.sql.Types

**Comment by tuohai666** [comment]
Add reference to https://github.com/apache/shardingsphere/issues/6166 .

**Comment by kimmking** [comment]
any update?
