### ISSUE TITLE
spring boot mybatis pageHelper query with a string date-time occur error

### ISSUE THREAD

**Issue by DongJigong** [apache/shardingsphere#6219]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
 <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>
```
### Actual behavior
```
.PersistenceException: 
### Error querying database.  Cause: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
### The error may exist in file [/Users/jonnyosborn/Workspace/petsuu-mall/petsuu-mall-admin/target/classes/dao/OmsOrderDao.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT         o.*,         orr.refund_time as refundTime,         orr.refund_money as refundMoney,         uc.user_id AS claimUserId,         uc.admin_id AS claimAdminId,         uc.admin_name AS claimAdminName,         uc.user_name AS claimUserName         FROM         oms_order AS o         LEFT JOIN oms_order_refund_record AS orr ON o.id = orr.order_id         LEFT JOIN oms_payment_transaction AS opt ON o.id = opt.order_id         LEFT JOIN ums_claim AS uc ON o.user_id = uc.user_id         WHERE         delete_status = 0                                                                                             AND DATE_FORMAT( o.create_time, '%Y-%m-%d' ) >= DATE_FORMAT( ?, '%Y-%m-%d' )                                       ORDER BY id desc LIMIT ?
### Cause: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer] with root cause

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```
### Reason analyze (If you can)
get page count result error
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/8855265/86102547-3ad14f00-baee-11ea-8c77-e0428555f76a.png)

**Comment by DongJigong** [comment]
![image](https://user-images.githubusercontent.com/8855265/86102922-b6330080-baee-11ea-9fe7-faa3245e999b.png)
If I change to this way below it works fine.
![image](https://user-images.githubusercontent.com/8855265/86103114-eda1ad00-baee-11ea-909d-611b314501a3.png)
# and $

**Comment by tristaZero** [comment]
@DongJigong Hi thanks for your feedback. :-)

Since I can not check your images well (Maybe due to my internet, not sure.), I can not settle the conclusion.
So 
Q1 Could ShardingSphere and page helper work together?
Q2 Do the users need to modify SQL? Such as `# and $`?

> ![image](https://user-images.githubusercontent.com/8855265/86102922-b6330080-baee-11ea-9fe7-faa3245e999b.png)
> If I change to this way below it works fine.
> ![image](https://user-images.githubusercontent.com/8855265/86103114-eda1ad00-baee-11ea-909d-611b314501a3.png)
> `# and $`

**Comment by DongJigong** [comment]
> @DongJigong Hi thanks for your feedback. :-)
> 
> Since I can not check your images well (Maybe due to my internet, not sure.), I can not settle the conclusion.
> So
> Q1 Could ShardingSphere and page helper work together?
> Q2 Do the users need to modify SQL? Such as `# and $`?
> 
> > ![image](https://user-images.githubusercontent.com/8855265/86102922-b6330080-baee-11ea-9fe7-faa3245e999b.png)
> > If I change to this way below it works fine.
> > ![image](https://user-images.githubusercontent.com/8855265/86103114-eda1ad00-baee-11ea-909d-611b314501a3.png)
> > `# and $`

Yes, if I change the symbol '#' to '$', it works fine. I guess maybe a sharding bug, but I am not sure.

**Comment by tristaZero** [comment]
Hi @DongJigong 
If it is possible, a detailed log is required. Could you set `sql.show` = `true` to get the logic SQL and actual SQLs?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
