### ISSUE TITLE
`fuck_finance`.`deleted_at`这种包含表名的字段不能正常解析？

### ISSUE THREAD

**Issue by qiuqiudyw** [apache/shardingsphere#6220]
**Logic SQL:** 
[INFO ] 17:37:51.911 [ShardingSphere-Command-10] ShardingSphere-SQL - Logic SQL: SELECT count(*) FROM `fuck_member`  WHERE `fuck_member`.`deleted_at` IS NULL

**Actual SQL**
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_1`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_2`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_3`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_4`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_5`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_6`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_7`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_8`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_9`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]
[INFO ] 17:37:51.917 [ShardingSphere-Command-12] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT SUM(amount) as allRecharge FROM `fuck_finance_10`  WHERE `fuck_finance`.`deleted_at` IS NULL AND ((`type` = ? AND `flag` = ?)) ::: [12, 1]

这种包含表名的字段不能正常解析？
`fuck_finance`.`deleted_at`

**Comment by kimmking** [comment]
It's a bug and fix in master branch now. https://github.com/apache/shardingsphere/issues/5857\
You can wait for 5.0.0-rc1 or modify it as:
> SELECT count(*) FROM  table1 WHERE  deleted_at IS NULL

or
> SELECT count(*) FROM  table1 as a1 WHERE  a1.deleted_at IS NULL
