### ISSUE TITLE
Sharding proxy can't identify schema from SQL if not explicity use schema.

### ISSUE THREAD

**Issue by chrissata** [apache/shardingsphere#6223]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
mysql> show databases;
+----------+
| Database |
+----------+
| db1          |
| db2          |
+----------+
mysql> use db1;
mysql> select * from db2.test_table;

SQL run well.

### Actual behavior
ERROR 1146 (42S02): Table 'db2.test_table' doesn't exist

### Reason analyze (If you can)

sql parser does not  extract schema from sql to modify sql statement context.
Only "use db2 " can change schema.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

shardingrule config: any config.

### Example codes for reproduce this issue (such as a github link).
use db1; 
do any sql on db2.table.

**Comment by tristaZero** [comment]
Hi Thanks for your feedback.
Cloud you try the following SQLs?
> user db2; select * from test_table;

That will work well, won't it?
If it is convenient, you can package master branch and give it a try. We have fixed it on the master branch already.

Bests,
Trista

**Comment by chrissata** [comment]
> Hi Thanks for your feedback.
> Cloud you try the following SQLs?
> 
> > user db2; select * from test_table;
> 
> That will work well, won't it?
> If it is convenient, you can package master branch and give it a try. We have fixed it on the master branch already.
> 
> Bests,
> Trista


Yes, of cource it will work inside the same schema without any schema switch.  But it's not the senario that I reported.  Sometimes we just use db.table to switch schema instead of using "use db".  Glad to hear it's fixed on master branch and It would be nice if you could attach the fix commit here.

Thanks,
Chrissta

**Comment by tristaZero** [comment]
@chrissata 
Hi [#6117](https://github.com/apache/shardingsphere/pull/6117/files) is what you want.
