### ISSUE TITLE
How to configure tables with the same table name in multiple data sources?

### ISSUE THREAD

**Issue by 18511699755** [apache/shardingsphere#6225]
Data source A and data source B, in which A has table_t and is divided into databases and tables, while B has table_t but does not. In application, it is necessary to add data to two tables of two libraries. How to configure it?

**Comment by kimmking** [comment]
I guess it doesn't support.

**Comment by ZhaoGuangYue1986** [comment]
将相同的数据插入到两个库的相同的表？
另外一个库是用做备份用吗？
