### ISSUE TITLE
Cannot find JDBC type '2003' in PostgreSQL column type

### ISSUE THREAD

**Issue by dingyf12593** [apache/shardingsphere#6232]
## Bug Report

ShardingSphere-Proxy  4.1.1  

pgsql  version  9.5.4 

jdbc config   jdbc:postgresql://172.17.0.4:5432/demo?serverTimezone=UTC&useSSL=false&allowEncodingChanges=true

navicat 15.0.11 connect show 
![image](https://user-images.githubusercontent.com/6504134/86307289-f9a18200-bc48-11ea-904e-9676e846909c.png)

logs error 
![image](https://user-images.githubusercontent.com/6504134/86307281-f3130a80-bc48-11ea-93c4-22303d0ab78e.png)

**Comment by dingyf12593** [comment]
demo datebase config

url: jdbc:postgresql://81.69.156.86:5432/postgres?serverTimezone=UTC&useSSL=false&allowEncodingChanges=true
    username: postgres
    password: a1b1c1d1
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

demo Proxy config

    129.211.76.191:5432

    authentication:
       users:
       root:
          password: root
          authorizedSchemas: demo

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/6408 .
