### ISSUE TITLE
Make the version of ShardingProxy and DB cluster consistent

### ISSUE THREAD

**Issue by 1006572352** [apache/shardingsphere#6239]
**usage:** sqoop-1.4.6-cdh5.16.2 +sharding-proxy-4.1.1 + mysql 5.6

**====
sqoop script：**
sqoop import \
--hive-drop-import-delims \
--connect "jdbc:mysql://xxx:3307/sharding_db?useSSL=false" \
--username root \
--password 'root' \
--split-by id \
--boundary-query "select min(id),max(id) from answer_report" \
--hive-import \
--hive-table tmp.test_sharding_proxy \
--query "select id,table_index,report_id,paper_id,paper_title from answer_report where "'$CONDITIONS' \
--fields-terminated-by '\001' \
--target-dir /tmp/sqoop_test_sharding_proxy_`date +%s` \
--hive-partition-key day \
--hive-partition-value ${bizdate}

**===
sqoop error info:**

ERROR manager.SqlManager: Error executing statement: java.sql.SQLException: Unknown system variable 'transaction_isolation'
java.sql.SQLException: Unknown system variable 'transaction_isolation'
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
......

**===
sharding-proxy log:**

[INFO ] 17:46:19.896 [ShardingSphere-Command-4] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, **@@transaction_isolation** AS transaction_isolation, @@wait_timeout AS wait_timeout

**=====
error analysis**
sharding-proxy are trying to find the variable ‘’transaction_isolation‘’，but mysql 5.6 don't have the variable 'transaction_isolation'  instead of 'tx_isolation'。

**then I test another version ：sharding-proxy-4.0.1。**

**====
sqoop error info：**
20/07/02 18:28:13 ERROR manager.SqlManager: Error executing statement: java.sql.SQLException: 2Unknown exception: [Failed to switch schema, please terminate current transaction.]
java.sql.SQLException: 2Unknown exception: [Failed to switch schema, please terminate current transaction.]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)

**===sharding-proxy info：**
[INFO ] 18:28:12.417 [ShardingSphere-Command-6] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, **@@tx_isolation** AS transaction_isolation, @@wait_timeout AS wait_timeout
......
[ERROR] 18:28:13.467 [ShardingSphere-Command-2] o.a.s.s.f.c.CommandExecutorTask - Exception occur:
org.apache.shardingsphere.core.exception.ShardingException: Failed to switch schema, please terminate current transaction.
        at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.connection.BackendConnection.setCurrentSchema(BackendConnection.java:116)
        at org.apache.shardingsphere.shardingproxy.backend.text.admin.BroadcastBackendHandler.execute(BroadcastBackendHandler.java:53)
        at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
        at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

===
the sharding-proxy-4.0.1  correctly identified parameter ‘tx_isolation’, but have the error  [Failed to switch schema, please terminate current transaction.] ;
the sharding-proxy-4.0.1  did not recognize parameter  ‘tx_isolation’,

**Comment by tristaZero** [comment]
@1006572352 Hi ShardingProxy would not try to find `transaction_isolation`. It just transfers the requests from users or APPs to the lower database cluster.

> sharding-proxy are trying to find the variable ‘’transaction_isolation‘’，but mysql 5.6 don't have the variable 'transaction_isolation' instead of 'tx_isolation'。

**Comment by 1006572352** [comment]
> @1006572352 Hi ShardingProxy would not try to find `transaction_isolation`. It just transfers the requests from users or APPs to the lower database cluster.
> 
> > sharding-proxy are trying to find the variable ‘’transaction_isolation‘’，but mysql 5.6 don't have the variable 'transaction_isolation' instead of 'tx_isolation'。

but when I test sharding-proxy-4.0.1, it correctly identified parameter ‘tx_isolation’.
===logg/stdout.log
[INFO ] 14:55:37.382 [ShardingSphere-Command-0] ShardingSphere-SQL - Rule Type: sharding
[INFO ] 14:55:37.382 [ShardingSphere-Command-0] ShardingSphere-SQL - Logic SQL: /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout

**Comment by kimmking** [comment]
MySQL8,  tx_isolation -> transaction_isolation.
And in recent version, proxy return the version with mysql 8.

**Comment by tristaZero** [comment]
@1006572352 @kimmking 
Thanks for your feedback.

It is sorted as a bug. Here is one of the recommended solutions, welcome everyone to try to fix it, and contribute to our community.

1. Get the version of MySQL servers deployed, like 5.7 by JDBC interface
2. Set the `SERVER_VERSION` in `MySQLServerInfo` class.
3. Therefore the versions of ShardingProxy and MySQL from the bottom are consistent.

**Comment by xbkaishui** [comment]
let me try,  @tuohai666  please re-assign to me

**Comment by xbkaishui** [comment]
I have a question, why we set the CHARSET to utf8_general_ci in  MySQLServerInfo ?  can we change it to  utf8mb4_unicode_ci to support like emoji ?

**Comment by tuohai666** [comment]
ok

**Comment by xbkaishui** [comment]
Hi anyone can help to review this bug fix. thanks

**Comment by tuohai666** [comment]
I'll review this pull request.

**Comment by xbkaishui** [comment]
thanks :blush:

**Comment by tuohai666** [comment]
@1006572352 The pr(https://github.com/apache/shardingsphere/pull/6270) that fix this problem is going to be merged. Would you like to have a test using master branch?

**Comment by tuohai666** [comment]
@1006572352 Since you use mysql 5.6.x, please change the connector/j version to 5.1.12 instead of 5.1.47

**Comment by tuohai666** [comment]
I have finished the test with MySQL server 5.6.47. It works well with connector/j 5.1.47.
