### ISSUE TITLE
The ID generated by snowflake algorithm would jumps and discontinuity. Serial ID is more suitable.

### ISSUE THREAD

**Issue by automvc** [apache/shardingsphere#6242]
The ID generated by snowflake algorithm strongly depends on clock. If Id is not generated at a certain time point, it will cause ID discontinuity; the longer the time is useless, the more serious the ID number jumps.

As the table primary key of DB, continuous ID is more suitable.
Reference for implementation of weak colck dependent and colck independent continuous ID algorithm:

https://github.com/automvc/honey/blob/master/src/main/java/org/teasoft/honey/distribution/SerialUniqueId.java
https://github.com/automvc/honey/blob/master/src/main/java/org/teasoft/honey/distribution/OneTimeSnowflakeId.java

**Comment by kimmking** [comment]
Can you make a pr to integrate this new ID generator? @automvc
