### ISSUE TITLE
How to use custom encryption rules

### ISSUE THREAD

**Issue by bruse1990** [apache/shardingsphere#6249]
Which class do I need to implement?
when i imlement after, what i should config in application.properties to distinguish like aes and md5?

**Comment by tristaZero** [comment]
Hi the interface `EncryptAlgorithm` is for you.

**Comment by bruse1990** [comment]
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.1.1</version>
		</dependency>

4.1.1can't find class EncryptAlgorithm
i should implement Encryptor.java?
how config custom encryption rules in application.yml after implement the encrytor class?
