### ISSUE TITLE
jdbc url not support p6spy driver

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#6266]
## Bug Report

jdbc url not support p6spy driver  examples like: jdbc:p6spy:mysql://credigo.ct2ud7p

**exceptions:** 
org.apache.shardingsphere.infra.exception.ShardingSphereException: Cannot resolve JDBC url `jdbc:p6spy:mysql:xxx`. Please implements `org.apache.shardingsphere.proxy.backend.communication.jdbc.recognizer.spi.JDBCDriverURLRecognizer` and add to SPI.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.x 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
  mysql 

### Actual behavior
org.apache.shardingsphere.infra.exception.ShardingSphereException: Cannot resolve JDBC url `jdbc:p6spy:mysql:xxx`. Please implements `org.apache.shardingsphere.proxy.backend.communication.jdbc.recognizer.spi.JDBCDriverURLRecognizer` and add to SPI.

### Reason analyze (If you can)
**current implement depends on JDBCDriverURLRecognizer , it just use url  prefix match to check which driver suitable, 
can't support such as  jdbc:p6spy:mysql:xxx**

### Example codes for reproduce this issue (such as a github link).

JDBCDriverURLRecognizerEngine.getJDBCDriverURLRecognizer("jdbc:p6spy:mysql:xxx");

**Comment by xbkaishui** [comment]
please assign to me

**Comment by dongzl** [comment]
Hi @xbkaishui , welcome!
