### ISSUE TITLE
document becomes partial under version 4.1.x in sharding-jdbc-orchestration

### ISSUE THREAD

**Issue by laingke** [apache/shardingsphere#6282]
### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-jdbc
### Expected behavior
Inject a dependency package with a same version as other shardingsphere package
### Actual behavior
In doc, It inject sharding-orchestration-reg-zookeeper-curator that verison is 4.0.x.
### Reason analyze (If you can)
The package renames to sharding-orchestration-center-zookeeper-curator under 4.1.x. It shall add description about this change.
### Example codes for reproduce this issue (such as a github link).
[ORCHESTRATION](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/usage/orchestration/#%E5%BC%95%E5%85%A5maven%E4%BE%9D%E8%B5%96-1)

**Comment by kimmking** [comment]
Solved.
