### ISSUE TITLE
Define a maven bom jar to uniform version

### ISSUE THREAD

**Issue by laingke** [apache/shardingsphere#6283]
### Is your feature request related to a problem?
#6282, It would be chaos when multiple shardingsphere jars have different version code in one project
### Describe the feature you would like.
Define a maven bom jar to uniform version, just like spring-boot-starter-parent or spring-boot-dependencies

**Comment by tristaZero** [comment]
@laingke 
Hi, since #6282 has been closed, I will close this one alike.

**Comment by laingke** [comment]
@tristaZero 
Before #6282 was solved, the document describe an example that may mislead developer to use sharding-orchestration-reg-zookeeper-curator(4.0.1) when using shardingphere(4.1.1).

So this has led me to ask such a question:
Is it exists a strong dependency relationship that all the shardingphere module are in one single same version? 

If not, in future, when the project becomes bigger and bigger, It is better to define a parent dependency version requirement.

**Comment by tristaZero** [comment]
@laingke 
All the modules are supposed to keep in the same release version. If not, maybe it is a mistake. Welcome your feedback. :)
