### ISSUE TITLE
how to use sharding-jdbc to shard table without mybatis?

### ISSUE THREAD

**Issue by syhasia** [apache/shardingsphere#6288]
i want to insert some data into shard tables in my project, but i do not use mybatis.
for example: insert into user(name,age) values (test,12); i want to insert this data into user0/user1, not user table.

how to implement it? does sharding-jdbc support it?

**Comment by menghaoranss** [comment]
@syhasia please refer to : https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/usage/sharding/

**Comment by menghaoranss** [comment]
If there is no problem, we will close this issue
