### ISSUE TITLE
insert into select is unsupport

### ISSUE THREAD

**Issue by ChuckPerry** [apache/shardingsphere#6289]
### versions:
shardingproxy version: 4.1.1
mysql: 5.7.21

### replay example:
`mysql>  create table test_t1(id int primary key auto_increment,name varchar(20));`
`mysql>  insert into test_t1 values(1,1);`
case 1:
`mysql> mysql> insert into test_t1(`name`) select t.`name` from test_t1 t;`
`ERROR 10002 (C1000): 2Unknown exception: [null]`
case 2:
`mysql> insert into test_t1(`name`) select '1' as name from test_t1;`
`ERROR 10002 (C1000): 2Unknown exception: [null]`
case 3:
`mysql> insert into test_t1 select 1,'1' ;`
`ERROR 10002 (C1000): 2Unknown exception: [null]`

**Comment by strongduanmu** [comment]
@ChuckPerry The insert select statement and replace select statement have not been implemented yet, and I will try to support it.

**Comment by ChuckPerry** [comment]
OK，thx for your reply
