### ISSUE TITLE
When use master slave mode, why exists not support sql?

### ISSUE THREAD

**Issue by ting570732** [apache/shardingsphere#6290]
![image](https://user-images.githubusercontent.com/8923410/86739064-2ea63e00-c068-11ea-89e4-46870f793dc3.png)
![image](https://user-images.githubusercontent.com/8923410/86739098-3534b580-c068-11ea-9369-405c205cfc21.png)
![image](https://user-images.githubusercontent.com/8923410/86739118-38c83c80-c068-11ea-961f-22528eb194e3.png)

**Comment by menghaoranss** [comment]
@ting570732  which version are you using?

**Comment by kimmking** [comment]
not support sql in a quote.

**Comment by tristaZero** [comment]
As I said before, SQL parsing is also required for Master-slave mode. But your log shows removing the outermost `()` will work well.
