### ISSUE TITLE
sorry to bother, how can i get  the shardingRule that i config in xml file?  i want to user the sharding rule in java class. thanks

### ISSUE THREAD

**Issue by smallericcc** [apache/shardingsphere#6292]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by menghaoranss** [comment]
@smallericcc you can refer to : https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-spring-namespace/

**Comment by xbkaishui** [comment]
you can convert the DataSource to ShardingSphereDataSource, in this class , it has rule configs,  this is a hack way

**Comment by kimmking** [comment]
I think we should close this issue.
