### ISSUE TITLE
shardingjdbc 4.1.1 mysql sql parse support "for update", but oracle not support 

### ISSUE THREAD

**Issue by zangyk** [apache/shardingsphere#6294]
shardingjdbc 4.1.1 mysql sql parse support "for update", but oracle not support

**Comment by tristaZero** [comment]
@zangyk Yep, right. But it is not so difficult to parse this SQL for Oracle. If you would like to take part in, here is a solution needing your contribution.

Add the grammar definition fo this SQL to `shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DMLStatement.g4` referring Oracle documment.

Look forward to your joining.

**Comment by zangyk** [comment]
I want to submit some code，how should I do？

**Comment by tristaZero** [comment]
Hi welcome @zangyk !
As I said before, 

Add the grammar definition fo this SQL to shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle/DMLStatement.g4 referring Oracle documment.

Do you have any ideas about that? Currently, I reopened this issue and assigned it to you. 
If you want to know the process of the contribution to this community, please refer to [Contribution guidence](https://shardingsphere.apache.org/community/en/contribute/contributor/)

**Comment by zangyk** [comment]
I solved this issues, but when I pushed a new branch to GitHub, I was prompted that I didn't have permission。

**Comment by tristaZero** [comment]
Hi @zangyk 
I appreciated your effort.
It is expected to raize a PR for your change, [Contriubtor](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will give you more detail.
Waiting for your joining!
