### ISSUE TITLE
Optimize the schema node of config center

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#6315]
## Question

Now  the config center use schema node content to maintain existing schemas, just like the picture below. 
When a schema is dynamically added or deleted, the content of the schema node needs to be updated at the same time, this way easily leads to inconsistent data, may be we should consider optimizing it.

![image](https://user-images.githubusercontent.com/60651792/87111741-ae1c5300-c29c-11ea-9414-8a123cc926d7.png)

**Comment by dongzl** [comment]
Hi @menghaoranss , This is indeed a problem, but what's the way do we optimize it? Do you have any good ideas?

**Comment by menghaoranss** [comment]
> Hi @menghaoranss , This is indeed a problem, but what's the way do we optimize it? Do you have any good ideas?

I understand that the reason for this is because some impl such as nacos cannot monitor the add and delete event of child code, so I think we can try to implement them.

**Comment by dongzl** [comment]
> > Hi @menghaoranss , This is indeed a problem, but what's the way do we optimize it? Do you have any good ideas?
> 
> I understand that the reason for this is because some impl such as nacos cannot monitor the add and delete event of child code, so I think we can try to implement them.

Yes, nacos and apollo don't have level relationship, your mean we construct this relationship?

**Comment by menghaoranss** [comment]
> > > Hi @menghaoranss , This is indeed a problem, but what's the way do we optimize it? Do you have any good ideas?
> > 
> > 
> > I understand that the reason for this is because some impl such as nacos cannot monitor the add and delete event of child code, so I think we can try to implement them.
> 
> Yes, nacos and apollo don't have level relationship, your mean we construct this relationship?

Need research first.

**Comment by menghaoranss** [comment]
fixed by #10555
