### ISSUE TITLE
how to modify sql_mode

### ISSUE THREAD

**Issue by leezhip** [apache/shardingsphere#6331]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

![image](https://user-images.githubusercontent.com/20160202/87266816-b7096080-c4f8-11ea-8b56-25eb63a6ec2a.png)

**Comment by kimmking** [comment]
What's your concrete error/question here?

**Comment by leezhip** [comment]
The new connection will be renewed "set session sql_mode"
Because of the database sql_mode are different, need to be consistent。
I tried to use it jdbcCompliantTruncation ,but it not work 
this my jdbcUrl
jdbcUrl: jdbc:mysql://127.0.0.1:3306/db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&jdbcCompliantTruncation=false

**Comment by tristaZero** [comment]
> I tried to use it jdbcCompliantTruncation ,but it not work

If you use regular JDBC, does it work? AFAIK, ShardingJDBC creates dataSource by means of `snakeyaml`. In general, it will not ignore any of the properties from user-defined `jdbcUrl`.
Do you think there is any JDBC interface, like `getAutoCommit()` can check whether this property and other properties take effect?

**Comment by leezhip** [comment]
Sorry, I found the problem. It's the mode initialized by the caller. thanks!
