### ISSUE TITLE
The hash table

### ISSUE THREAD

**Issue by yu258** [apache/shardingsphere#6333]
How do you hash tables using Sharding-Proxy?

**Comment by kimmking** [comment]
What do you mean?

**Comment by yu258** [comment]
> What do you mean?

What I mean by that is, can a sub-table be partitioned through hashing

**Comment by kimmking** [comment]
Of course, 
1. if your sharding key( for example, id) is int type, you can use `id % 16 `
2. if your sharding key( for example, code) is string type, you can use `Math.abs(code.hashCode()) % 16 `

**Comment by tristaZero** [comment]
> > What do you mean?
> 
> What I mean by that is, can a sub-table be partitioned through hashing （我的意思：分表能否通过Hash来进行分表）

Of course, please look at the official document about  `sharding strategy`.
