### ISSUE TITLE
how to get DataSource by DataSourceName

### ISSUE THREAD

**Issue by tony1991** [apache/shardingsphere#6336]
## Question

how to get DataSource by DataSourceName in my application？I want to get a specific DataSource from dataSourceMap, but there is no function to get dataSourceMap or DataSource. Looking forward for your reply

**Comment by kimmking** [comment]
There are many different ways for retrieving DataSource by its name, according to where your codes are weaving in ss.
For example, in spring/spring-boot env, you can inject bean by name. Sometimes we can get ds from SchemaContext-ShardingSphereSchema-dataSources Map.
So, where did you want to get dataSource?

**Comment by tony1991** [comment]
> There are many different ways for retrieving DataSource by its name, according to where your codes are weaving in ss.
> For example, in spring/spring-boot env, you can inject bean by name. Sometimes we can get ds from SchemaContext-ShardingSphereSchema-dataSources Map.
> So, where did you want to get dataSource?


my config like this pic
![微信图片_20200713193730](https://user-images.githubusercontent.com/11584767/87300391-50a83080-c540-11ea-8e53-33037144ff81.jpg)

I want get ds1 , can you give some examples?

**Comment by kimmking** [comment]
Autowired is injected by type, so there are many ds instances, an error occurs.
You should use `@Resource("ds1")`, injected by name.

**Comment by tony1991** [comment]
> `@Autowired` is injected by type, so there are many ds instances, an error occurs.
> You should use `@Resource("ds1")`, injected by name.

it's still not work.
![微信图片_20200714131018](https://user-images.githubusercontent.com/11584767/87386588-6f0b3c00-c5d3-11ea-9301-d9b53671425e.jpg)

**Comment by xbkaishui** [comment]
@tony1991 simple way 

`     ShardingSphereDataSource dataSource = (ShardingSphereDataSource)applicationContext.getBean(DataSource.class);
  Map<String, DataSource> dataSourceMap =  dataSource.getDataSourceMap();
`

or you can @autowire datasource

**Comment by kimmking** [comment]
> > `@Autowired` is injected by type, so there are many ds instances, an error occurs.
> > You should use `@Resource("ds1")`, injected by name.
> 
> it's still not work. My shardingjdbc version is 4.0.0-RC2.
> 
> ![微信图片_20200714131203](https://user-images.githubusercontent.com/11584767/87386730-bb567c00-c5d3-11ea-8467-77925ca6a9b1.jpg)

ds1 is the bean name in spring context, if your resource is null, something else is wrong.

**Comment by tony1991** [comment]
> dataSourceMap

dataSourceMap is final private and there is no method like `dataSource.getDataSourceMap();`

**Comment by tony1991** [comment]
> DataSource



> ds1 is the bean name in spring context, if your resource is null, something else is wrong.

I know and I can get ShardingDataSource by `@Autowire datasource`.  I have read the source code.
The ShardingDataSource cantains more dataSources in a dataSourceMap, but I can't get  these dataSources. you can try it.
I suggest you can change dataSourceMap to public or provide a public method to invoke

**Comment by tony1991** [comment]
> @tony1991 simple way
> 
> ` ShardingSphereDataSource dataSource = (ShardingSphereDataSource)applicationContext.getBean(DataSource.class); Map<String, DataSource> dataSourceMap = dataSource.getDataSourceMap();`
> 
> or you can @autowire datasource

Good! I have try before submit issues. But I have not convert DataSource to ShardingDataSource, so I can't get dataSourceMap. Your method works well! Thank you!

**Comment by xbkaishui** [comment]
no problem, you can close this issue if it is ok.
