### ISSUE TITLE
Why does HintManager's getInstance return a new HintManager instead of returning the one held by the current thread

### ISSUE THREAD

**Issue by SirMin** [apache/shardingsphere#6342]

**Comment by kimmking** [comment]
HintManager is designed to pass value from custom-hint codes to sharding engine, so in every query, it's a temp and once in user-side.

**Comment by tristaZero** [comment]
Hi @SirMin sorry, do you mean the following one? 

```
public final class HintManager implements AutoCloseable {
    
    private static final ThreadLocal<HintManager> HINT_MANAGER_HOLDER = new ThreadLocal<>();
    
    private final Multimap<String, Comparable<?>> databaseShardingValues = HashMultimap.create();
    
    private final Multimap<String, Comparable<?>> tableShardingValues = HashMultimap.create();
    
    private boolean databaseShardingOnly;
    
    private boolean masterRouteOnly;
```

**Comment by SirMin** [comment]
```
public static HintManager getInstance() {
        Preconditions.checkState(null == HINT_MANAGER_HOLDER.get(), "Hint has previous value, please clear first.");
        HintManager result = new HintManager();
        HINT_MANAGER_HOLDER.set(result);
        return result;
    }
```
I want to set masterRouteOnly in Custom annotation and  setDatabaseShardingValue in business code, But HintManager's getInstance return new everytime.
So i want to know why this is done.

**Comment by kimmking** [comment]
You should implement an HintShardingAlgorithm to wrap Hint process.

**Comment by SirMin** [comment]
I know this, but I must save the HimManager instance and transfer it to the callee. Because setMasterRouteOnly and setDatabaseShardingValue call are not in the same place.

**Comment by tristaZero** [comment]
Hi @SirMin Thanks for your feedback.

I got your point. Maybe a new PR is needed to meet your needs.
IMO, I think your requirement is sensible in some way. It is preferable to return the original one from `HINT_MANAGER_HOLDER` rather than `new HintManager()` when call `getInstance()`. Besides, `clear()` is also expected to be called by the user themselves.

```java
/**
     * Get a new instance for {@code HintManager}.
     *
     * @return  {@code HintManager} instance
     */
    public static HintManager getInstance() {
        Preconditions.checkState(null == HINT_MANAGER_HOLDER.get(), "Hint has previous value, please clear first.");
        HintManager result = new HintManager();
        HINT_MANAGER_HOLDER.set(result);
        return result;
    }
```

**BTW, do you want to have a try to fix this issue by yourself? If not, we will get volunteers involved in it.**

**Comment by SirMin** [comment]
Ok. I'ill try to new pr

**Comment by kimmking** [comment]
@SirMin Assigned
