### ISSUE TITLE
[ShardingSphere-Proxy] support absolute path for conf dir 

### ISSUE THREAD

**Issue by hongfuli** [apache/shardingsphere#6343]
## Feature Request
when we upgrade the version of ShardingSphere-Proxy, the most convenient way is to directly replace the entire installation directory. so it is best to separate the conf dir from base deploy dir.
if we use relative path, it is relative to base deploy dir, E.g:
```bash
./start.sh 3307 my_conf/   -->  the final conf dir is: /{base deploy dir}/my_conf/
```
but if we use absolute path, it has nothing to do with base deploy dir, E.g:
```bash
./start.sh 3307 /var/log/proxy/   -->  the final conf dir is: /var/log/proxy/
```

**Comment by tristaZero** [comment]
Hi @hongfuli 
I basically think your suggestion makes sense. Besides, it is better If we can support both absolute and relative conf dir.
Do you want to have a try to improve it? 
If not, we welcome any volunteer step forward!

Here is my draft solution, actually it is not hard.
Modifying its `start.sh` shell script is recommended.
Here it is,
`./incubator-shardingsphere/shardingsphere-distribution/shardingsphere-proxy-distribution/src/main/resources/bin/start.sh`

**Comment by hongfuli** [comment]
@tristaZero it's my pleasure, please assign it to me

**Comment by xbkaishui** [comment]
@hongfuli @tristaZero 
this is already fixed in master branch, please refer this [issue](https://github.com/apache/shardingsphere/issues/6274)

**Comment by tristaZero** [comment]
Thanks for your kind reminder. :-) @xbkaishui 
@hongfuli It seems other opportunities are expected to get you involved in ShardingSphere community in the future. What a pity! :-(

**Comment by hongfuli** [comment]
@xbkaishui @tristaZero 

According to the original design reflected in the code(org.apache.shardingsphere.proxy.config.ShardingConfigurationLoader) and the startup shell script(start.sh), it is best to keep the way using `class.getResource` to load resources. we only need to adjust the `classpath` setting in the `start.sh` scrip file.

In addition there is another problem, the logback.xml file in the conf dir directory has not been loaded successfully,
we must to add the `conf dir` and it's parent dir both to the `classpath`.

#6361  i reverted java code about loading resource and adjusted the start shell script.
