### ISSUE TITLE
Shardingsphere-proxy data sharding, How to deal with foreign keys？

### ISSUE THREAD

**Issue by lijintaotzx** [apache/shardingsphere#6353]
Newbies are just getting started with shadingsphere

I have several tables: user group, user, order, order details

Now the order table has a huge amount of data and needs to be split. I plan to use shardingsphere proxy to take orders and order details to other database and save them in many tables
However, there is a foreign key relationship between the order table and the user table. After configuring shardingsphere and created usertable , when creating the order table in the proxy, a foreign key error will always be reported. If only the table is not divided into the database, the error will not occur.
More doubts: Can't two tables with foreign key relationship be divided into two stocks?

**Comment by tristaZero** [comment]
If two tables are involved, you can consider shard them with the same sharding strategy, namely `bind-table`. Please consult our official doc. However, I am not sure if `bind-table` is suitable for your case.
