### ISSUE TITLE
How to get the result in MySQL JSON field

### ISSUE THREAD

**Issue by mazhaoshuo** [apache/shardingsphere#6354]
When I execute the following statement, I get two fields, but the result returns one field
`select content_json->>'$.nation' as nation,content_json->>'$.title' as title from  tb_content_json b where b.content_id=1`
![image](https://user-images.githubusercontent.com/39507157/87523098-09917b00-c6b9-11ea-8d74-49f3f3869842.png)

This table is not divided into tables. I want to ask if the tables that are not partitioned can directly put my SQL into MySQL for execution without parsing SQL through shardingsphere, or how to support the SQL above me

**Comment by menghaoranss** [comment]
@mazhaoshuo For English only.

**Comment by mazhaoshuo** [comment]
> @mazhaoshuo仅适用于英语。

I have translated the question

**Comment by mazhaoshuo** [comment]
@menghaoranss I have translated the question

**Comment by tristaZero** [comment]
@mazhaoshuo No matter It is a sharding table or not, `SQL Parsing` is required.

@jingshanglu Could you give this SQL a check? Parsed well nor not on our master branch and previous release?

Trista

**Comment by jingshanglu** [comment]
@tristaZero @mazhaoshuo The sql is not ok on master branch,i'll trance it.

**Comment by jingshanglu** [comment]
@mazhaoshuo Which version do you use? do you use mysql client to connect to shardingsphere proxy?

**Comment by mazhaoshuo** [comment]
> @mazhaoshuo Which version do you use? do you use mysql client to connect to shardingsphere proxy?

@jingshanglu apache-shardingsphere-4.1.1-sharding-proxy      I've changed it to the following
`select JSON_UNQUOTE(JSON_EXTRACT(content_json,'$.#(x.title')) as title from tb_content_json b where b.content_id=1`
Does not seem to support - > >

**Comment by jingshanglu** [comment]
@mazhaoshuo Can you give the error stack of proxy？

**Comment by tristaZero** [comment]
@mazhaoshuo The issue of parsing `->>` has been fixed at [#6423](https://github.com/apache/shardingsphere/pull/6423) by @jingshanglu . Our next release will include this one.

Thanks,
Trista

**Comment by tristaZero** [comment]
@mazhaoshuo BTW, could you provide the more detailed log of ShardingProxy? If so, we can make sure what @jingshanglu did is exactly for your issue.
