### ISSUE TITLE
Does ShardingSphere-Proxy support two-node cluster deployment?

### ISSUE THREAD

**Issue by cobstergo** [apache/shardingsphere#6355]
Does ShardingSphere-Proxy support two-node cluster deployment？
if ShardingSphere-Proxy support two-node cluster deployment, it will improve Reliability.
if not support, Is there any plan to support two-node cluster deployment?

**Comment by xbkaishui** [comment]
yes, you can deploy multi node as peers, each one are independent,  you can also use orchestration function to manage the multi nodes

**Comment by cobstergo** [comment]
@xbkaishui thanks for you reply,  cloud you please give me some clue or doc about the config or details.

**Comment by kimmking** [comment]
LVS+keepalived can wrap two proxies as a HA one.

**Comment by cobstergo** [comment]
@kimmking thanks a lot , it's means ShardingSphere-Proxy not support HA by itself, but we can use LVS + keepalived or other middleware to make ShardingSphere-Proxy as HA one?

**Comment by tristaZero** [comment]
> @kimmking thanks a lot , it's means ShardingSphere-Proxy not support HA by itself, but we can use LVS + keepalived or other middleware to make ShardingSphere-Proxy as HA one?

Exactly, you can treat ShardingProxy as a powerful single database.
