### ISSUE TITLE
Could Sharding-Proxy support load balance?

### ISSUE THREAD

**Issue by xtuer** [apache/shardingsphere#6357]
We can use keepalived to make high availability with Sharding-Proxy, one proxy is not enough when there are too many connections, is there anyway to load balance Sharding-Proxy?

Thank you!

**Comment by xbkaishui** [comment]
it that ok,  nginx  ->  multi proxy 
nginx for load balance with tcp connections.

**Comment by xtuer** [comment]
> nginx -> multi proxy , is that ok ?
> nginx for load balance with tcp connections.

Thank you for your reply, I will try it later.

**Comment by tristaZero** [comment]
@xbkaishui I like your response to many of the community issues. Good job, and keep on! :-)

**Comment by xtuer** [comment]
> hi, xuter.
> for HA，we suggest：
> LVS+KeepAlive -> multiple proxies.

Thank you, good suggestion!
