### ISSUE TITLE
Update Case When mode does not support encryption?

### ISSUE THREAD

**Issue by zhf122728281** [apache/shardingsphere#6358]
### Which version of ShardingSphere did you use?
    compile 'org.apache.shardingsphere:sharding-jdbc-spring-namespace:4.1.1'
    compile 'org.apache.shardingsphere:sharding-jdbc-core:4.1.1'

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
        ShardingSphere-JDBC

**Comment by zhf122728281** [comment]
What batch update method supports encryption?

**Comment by zhf122728281** [comment]
I need your help

**Comment by tristaZero** [comment]
Hi @zhf122728281 Your information is so insufficient. Please provide more, like SQL, log..

**Comment by zhf122728281** [comment]
![image](https://user-images.githubusercontent.com/20379651/87654636-cb17c100-c789-11ea-9b32-4d4363d4d5ff.png)


![image](https://user-images.githubusercontent.com/20379651/87654669-d834b000-c789-11ea-9477-b1f0fee46626.png)

Above, neither of the batch updates can be encrypted.

The field I want to encrypt is this one.   'visitor_phone_num'

**Comment by zhf122728281** [comment]
Multi-line update operation 、 The 'update case when' method doesn't work either.

**Comment by zhf122728281** [comment]
Is there any other solution?

**Comment by zhf122728281** [comment]
@tristaZero Is there any other solution?

**Comment by kimmking** [comment]
I think you should be foreach batch in you java code and let here only one update statement in one sql.

**Comment by zhf122728281** [comment]
> code

This puts a lot of pressure on the database and makes execution less efficient

**Comment by zhf122728281** [comment]
@tristaZero Is there any plan to support this later version?

**Comment by zhf122728281** [comment]
> I think you should be foreach batch in you java code and let here only one update statement in one sql.


This puts a lot of pressure on the database and makes execution less efficient

**Comment by tristaZero** [comment]
@zhf122728281 
Hi `batch update` you said means the SQL of `update case when`, doesn't it?

Could you set `sql.show` open and provide the `logic SQL` and `actual SQL` in the log?

It will make analysis easier if we could get the SQLs that ShardingJDBC received.

Trista
