### ISSUE TITLE
Bug for oracle when application starting

### ISSUE THREAD

**Issue by feiweihy** [apache/shardingsphere#6362]
We create many users in our oracle database ( 12C ), I use shardingsphere-jdbc in our project which is based on springcloud.  When I startup application, an error occurred: ORA-00942 table or view not exsist.
I read codes and found that function getSchema in class JdbcUtil has an problem:
     `if ("Oracle".equals(databaseType)) {
                return null;
            }`
This is ok when database just has one user, so I fixed it like this:
`if ("Oracle".equals(databaseType)) {
                return connection.getMetaData().getUserName().toUpperCase();
            }`
Problem is resolved.

**Comment by tristaZero** [comment]
@feiweihy Welcome!
