### ISSUE TITLE
How to configure MasterSlaveRuleConfiguration when a slave database is shut down

### ISSUE THREAD

**Issue by sevens66** [apache/shardingsphere#6364]
In the MasterSlave configuration, if any database in the slave configuration is closed, the failed database will not be automatically masked, resulting in the whole system completely unavailable during the database shutdown

how to  configure

读写分离配置时，如果slave配置内的任何一个数据库关闭，不会自动进行屏蔽失败的数据库，导致其中一个从库关闭期间整个系统完全不可用

**Comment by tristaZero** [comment]
@sevens66 If you want all the apps online to get the event that one of the slaves was closed, please consider `orchestration`, our official doc will tell you more.

Trista
