### ISSUE TITLE
Compatibility with MySQL's fullindex is not good, statements containing match are prone to errors

### ISSUE THREAD

**Issue by chentianming11** [apache/shardingsphere#6375]
### Which version of ShardingSphere did you use?
4.0.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Perfect support for fullindex

### Actual behavior
If the query statement contains the match keyword and the match query condition is in the first position of where, an error will be reported.The temporary solution is to ensure that the match clause is not the first position in the where query.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://user-images.githubusercontent.com/30620547/87775357-8b6bda80-c858-11ea-9a4a-c3bf24b9f032.png)

**Comment by kimmking** [comment]
it has been fixed in master branch.
https://github.com/apache/shardingsphere/issues/6299
