### ISSUE TITLE
Cannot find JDBC type '2003' in PostgreSQL column type

### ISSUE THREAD

**Issue by 1ssqq1lxr** [apache/shardingsphere#6396]
[ERROR] 09:41:15.943 [pool-16-thread-1] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalArgumentException: Cannot find JDBC type '2003' in PostgreSQL column type

**Comment by kimmking** [comment]
which version do you use now?

**Comment by 1ssqq1lxr** [comment]
> which version do you use now?

I use docker, the latest version of PostgreSQL, which is 11.8

**Comment by 1ssqq1lxr** [comment]
> which version do you use now?

docker:apache/sharding-proxy:latest
postgresql:11.8

**Comment by sandynz** [comment]
Hi, I'd like try to solve it

**Comment by tuohai666** [comment]
Duplicated with #6408 .
