### ISSUE TITLE
windows :  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project shardingsphere-ui-frontend: Failed to run task

### ISSUE THREAD

**Issue by 2222** [apache/shardingsphere#6402]
[ERROR] ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
[ERROR] { Error: read ECONNRESET
[ERROR]     at _errnoException (util.js:1022:11)
[ERROR]     at TLSWrap.onread (net.js:628:25)
[ERROR]   -- ASYNC --
[ERROR]     at BrowserFetcher.<anonymous> (D:\github\ss-ui\shardingsphere-ui\shardingsphere-ui-frontend\node_modules\puppeteer\lib\helper.js:111:15)
[ERROR]     at Object.<anonymous> (D:\github\ss-ui\shardingsphere-ui\shardingsphere-ui-frontend\node_modules\puppeteer\install.js:64:16)
[ERROR]     at Module._compile (module.js:652:30)
[ERROR]     at Object.Module._extensions..js (module.js:663:10)
[ERROR]     at Module.load (module.js:565:32)
[ERROR]     at tryModuleLoad (module.js:505:12)
[ERROR]     at Function.Module._load (module.js:497:3)
[ERROR]     at Function.Module.runMain (module.js:693:10)
[ERROR]     at startup (bootstrap_node.js:188:16)
[ERROR]     at bootstrap_node.js:609:3 code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! puppeteer@1.20.0 install: `node install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the puppeteer@1.20.0 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\yanhg\AppData\Roaming\npm-cache\_logs\2020-07-22T12_28_10_438Z-debug.log

**Comment by kimmking** [comment]
You should use VPN to across GFW.
or install node/npm locally and then use taobao mirror：
```
npm install -g cnpm
mvn clean install -Prelease,node-cn
```
