### ISSUE TITLE
Rename MetricsHandlerFacade.counterInc, gaugeInc and gaugeDec 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6406]
It is better to avoid use abbreviation with method name, please change the method name.

- [ ] Change MetricsHandlerFacade.counterInc to counterIncrement
- [ ] Change MetricsHandlerFacade.gaugeInc to gaugeIncrement
- [ ] Change MetricsHandlerFacade.gaugeDec to gaugeDecrement

**Comment by jiang2015** [comment]
please assigned to me
