### ISSUE TITLE
sharding-jdbc failover when master node is down

### ISSUE THREAD

**Issue by lishijun121910** [apache/shardingsphere#6412]
## Question
how sharding-jdbc support failover when master node is down when config a master-slave rule.

the situation is when master is down, the slave node upgrade to be a new master.

**Comment by tristaZero** [comment]
Hi @lishijun121910 

Please refer to [Orchestration](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/features/orchestration/)
All the relationships of data sources and sharding rules are stored in registry center.
You or your program need to update `the new master info` on the registry center, and it will push this event online.

**Comment by zhaopinglu** [comment]
I read the links in your answer above, but I still can't be sure if ShardingSphere-JDBC (or -Proxy) support Master-Slave failover or not. Could you please answer this question directly? Thanks.

**Comment by tristaZero** [comment]
@zhaopinglu Simply speaking, ShardingSphere can not handle the failover of MySQL, but it can push the info of new masters and slaves to all the proxy or JDBC clients online.
