### ISSUE TITLE
[SQL Definition Collation][PostgreSQL]Collate the g4 files of SQL definitions

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6417]
Hi community,

This issue is to collate the SQL definitions of PostgreSQL. **Therefore, we can support parsing more SQLs**. 
We need your interaction! If you 

> 1. Be familiar with `g4 file` of Antlr (The grammars are RegularExpression-like)
> 2. Understand the `PostgreSQL grammars`

then welcome!😃

### Background

**How is a SQL parsed?**
`SQL definition file` 
->(Parse to) 
`AST`
->(Visit it)  
`SQLStatment`  

### Process

1. Compare `SQL definitions` in [Oficial SQL Doc](https://www.postgresql.org/docs/12/index.html) (Or [Source code](https://github.com/postgres/postgres/tree/REL_12_STABLE)) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
3. Run `mvn install the current_file_module` 
4. Check whether there are any exceptions. If indeed, please fix them. (Especially `xxxVisitor.class`)
5. Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/supported) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/case)
6. Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/java/org/apache/shardingsphere/sql/parser/integrate/engine/SQLParserParameterizedTest.java) to make sure no exceptions.

### Notice
1.`Left recursion` can not work well in Antlr4, 
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```

2. [Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.

**Comment by strongduanmu** [comment]
I want to try this task, can you assigne it to me?

**Comment by tristaZero** [comment]
@strongduanmu Thanks for your comment, BTW are you interested in `Collating the g4 file for SQLServer or Oracle`? I am sorry to say this one is reserved for the students from [SUMMER2020](http://www.is.cas.cn/xshd2016/xshy2016/202004/t20200426_5563484.html) . 😿

**Comment by strongduanmu** [comment]
> @strongduanmu Thanks for your comment.
> I am sorry to say this one is reserved for the students from [SUMMER2020](http://www.is.cas.cn/xshd2016/xshy2016/202004/t20200426_5563484.html) . 😿
> 
> BTW are you interested in `Collating the g4 file for SQLServer or Oracle`?
> The following similar issues are coming online soon!
> 
> Trista

@tristaZero I'm so sorry 😂, and I will look for other unsolved issues.

**Comment by tristaZero** [comment]
#7243
