### ISSUE TITLE
data encrypt function ,  nominate schema in "spring.shardingsphere.datasource"  url params , select other schema sql will not execute correcttly

### ISSUE THREAD

**Issue by prefect1005** [apache/shardingsphere#6426]
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://1........:8888/ds_0?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true 
spring.shardingsphere.datasource.ds0.username=
spring.shardingsphere.datasource.ds0.password=

we nominate schema is ds_0
if we execute sql like "select * from ds_1.table_name where id = ?"
because in SchemaMetaData's private final Map<String, TableMetaData> tables; tables initialize value is  tables under ds_0 schema , there no ds_1.table_name in it. so sql  can execute  but in resultSet can't set value in javaBean. the conclusion is "all elements are null".

we use 4.1.1 has this problem
but in 4.0.1 version that not have this problem.

whether or not we can add all tables into SchemaMetaData's tables.

**Comment by tristaZero** [comment]
Currently, I suggest you first change to `db_1` and then execute SQL.
The feature of `ds_1.table_name` executed in `ds_0` has finished already and will online at our next release.

Thanks,
Tirsta

**Comment by prefect1005** [comment]
well, thank you, look forward  the next version
