### ISSUE TITLE
Hi Guys, is Sharding support the store procedure? 

### ISSUE THREAD

**Issue by manbo1987** [apache/shardingsphere#6430]
Hi Guys, is Sharding support the store procedure? 
   1) Can I create SP via sharding or i need create SPS on sub DB one by one?
   2) Could you show me demo ?
 thank you for your reply...

**Comment by tristaZero** [comment]
Hi @manbo1987

You mean the SQL of `the store procedure`?  Since the SQL of `store procedure` is diverse, I can not guarantee it. But ShardingSphere will change the table names of your SQL can send it to databases at the base. No matter what SQL it is.

**Comment by tristaZero** [comment]
Hi @manbo1987

You mean the SQL of `the store procedure`?  Since the SQL of `store procedure` is diverse, I can not guarantee it. But ShardingSphere will change the table names of your SQL can send it to databases at the base. No matter what SQL it is.

**Comment by tristaZero** [comment]
Hi @manbo1987

You mean the SQL of `the store procedure`?  Since the SQL of `store procedure` is diverse, I can not guarantee it. But ShardingSphere will change the table names of your SQL can send it to databases at the base. No matter what SQL it is.

**Comment by kimmking** [comment]
Hi, @manbo1987,
Generally says, procedures or custom functions are not supported now.
If you are interested in them, welcome to do some jobs to improve ss.

**Comment by tristaZero** [comment]
Hi @manbo1987 
 I create #6498 intending to solve your issue. I presume it is expected to finish a basic function, and a perfect result depends on its assignees.
