### ISSUE TITLE
Delete useless branches

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6447]
Make clear the usage of some branches, and delete them if the branches are useless.

- [x] dev-4.x
- [x] docs5.x

**Comment by tuohai666** [comment]
dev-4.x is for releasing of 4.x version. If we decide to publish a release, we can make it from the tag. So it's OK to delete this branch.

**Comment by kimmking** [comment]
docs5.x branch is unuseful, will be removed now.
