### ISSUE TITLE
shardingjdbc with mybatis compose use have some mistake

### ISSUE THREAD

**Issue by Yogurt-lei** [apache/shardingsphere#6448]
env:
mysql-connector-java: 8.0.20
mybatis-plus-boot-starter: 3.3.2
sharding-jdbc-spring-boot-starter: 4.1.1

when your entity is LocalDateTime ,so the MyBatis TypeHandler is LocalDateTimeTypeHandler#getNullableResult,

but this is a unsupport operation in ShardingJdbc AbstractUnsupportedOperationResultSet#getObject(columnIndex,type) throws SQLFeatureNotSupportedException

to resolve this question must override method in ShardingResultSet but the parent method is final tag

Is this under repair ？

**Comment by kimmking** [comment]
`getObject(columnIndex,type)` has supported in master branch now.

see:  shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/resultset/ShardingSphereResultSet.java

**Comment by tristaZero** [comment]
@Yogurt-lei Hi, thanks for the feedback. As @kimmking said, this issue had been fixed in our `master branch`. #6202 will give you more detail. Please be patient for our next release.

Trista
