### ISSUE TITLE
Wrong SQL parse with "DATE_ADD" function

### ISSUE THREAD

**Issue by johnny2002** [apache/shardingsphere#6451]
## Bug Report

I have an mysql SQL like：
INSERT INTO tab_user
 (id, name, sex, age, create_time, update_time, status)
VALUES(3, 'test', 'F', 30, DATE_ADD(now(),INTERVAL 2 DAY), DATE_ADD(now(),INTERVAL 2 DAY), '1');

After sharding-sphere parsor, it become:
INSERT INTO tab_user0
(id, name, sex, age, create_time, update_time, status)
VALUES(3, 'test', 'F', 30, DATE_ADD(now(),INTERVAL2DAY), DATE_ADD(now(),INTERVAL2DAY), '1');

Which removed spaces in "INTERVAL  2  DAY", caused the sql exception.

**Comment by kimmking** [comment]
which version did you use?

**Comment by tristaZero** [comment]
Hi @jingshanglu 
This SQL could work well on our master branch, couldn't it?

**Comment by jingshanglu** [comment]
@tristaZero @johnny2002 Now, this is a bug, new version will fix it.

**Comment by johnny2002** [comment]
> which version did you use?

4.1.1

**Comment by tristaZero** [comment]
Hi @johnny2002 
Thanks for your feedback, we will fix it before our next release!
