### ISSUE TITLE
How to skip sql parse and rewrite phase

### ISSUE THREAD

**Issue by johnny2002** [apache/shardingsphere#6458]
## Question

We have an ETL batch job, that the SQLs are very complex. We want to manually specify the datasource by HintManager and the real table name already fixed in SQLs,  while we cann't skip sql parser  which caused some exceptions. 

Although offical document says, the sql parse and rewrite phase will be skipped if we use hintManager.setDatabaseShardingValue, while we can't find a way to skip sql paring and rewritting.

**Comment by johnny2002** [comment]
my config file:


spring.shardingsphere.!SHARDING.tables.tab_user.actual-data-nodes=master${0..1}.tab_user
spring.shardingsphere.!SHARDING.tables.tab_user.database-strategy.hint.algorithmClassName=com.ibm.sharding.MyHintShardingAlgorithm

My java code:
            HintManager hintManager = HintManager.getInstance();
            hintManager.setDatabaseShardingValue("0"); // 

I want sharding-jdbc do not parse my sql, and get the right datasource from MyHintShardingAlgorithm directly. I think, you need to have somewhere to let me set the logic table name so that you know the configuration.

**Comment by kimmking** [comment]
sql parsing is a necessary phase.

**Comment by johnny2002** [comment]
> sql parsing is a necessary phase.

If you know the logicTableName, why do you need to parse SQL.

So suggestted solution:
HintManager hintManager = HintManager.getInstance();
hintManager.setDatabaseShardingValue("0"); 
hintManager.setLogicTableName("tab_user");

Then skip sql parsing

**Comment by kimmking** [comment]
see https://github.com/apache/shardingsphere/issues/4806
https://github.com/apache/shardingsphere/issues/4281

**Comment by tristaZero** [comment]
@johnny2002 The reason is that we can not know whether this `logicTableName` exists at your input SQL if there is no SQL parsing.

> > sql parsing is a necessary phase.
> 
> If you know the logicTableName, why do you need to parse SQL?
> 
> So suggestted solution:
> HintManager hintManager = HintManager.getInstance();
> hintManager.setDatabaseShardingValue("0");
> hintManager.setLogicTableName("tab_user");
> 
> Then skip sql parsing

**Comment by johnny2002** [comment]
> @johnny2002 The reason is that we can not know whether this `logicTableName` exists at your input SQL if there is no SQL parsing.
> 
> > > sql parsing is a necessary phase.
> > 
> > 
> > If you know the logicTableName, why do you need to parse SQL?
> > So suggestted solution:
> > HintManager hintManager = HintManager.getInstance();
> > hintManager.setDatabaseShardingValue("0");
> > hintManager.setLogicTableName("tab_user");
> > Then skip sql parsing

Dear,
Since I already told you the logicTableName, you should treat it as exists, even sometimes, the logicTableName not exists in SQL, but this is my intent. e.g. I want to use the sharding rule of table-a to shard table-b, this should be allowed.

Hope you can double check my suggestion. This feature should broadly promote the usage of Sharding-jdbc.

**Comment by tristaZero** [comment]
Hi @johnny2002 
You mean to add `logical table` and `sharding key`  to `hintManger` **just for** skipping the SQL parsing and rewriting?
If so, actually, sharding JDBC does need to parse SQL. Do you think there are any other scenarios needing this feature?

**Comment by johnny2002** [comment]
> Hi @johnny2002
> You mean to add `logical table` and `sharding key` to `hintManger` **just for** skipping the SQL parsing and rewriting?
[A] Exactly!
> If so, actually, sharding JDBC does need to parse SQL. Do you think there are any other scenarios needing this feature?
My case is, I have some very complex SQLs that involes many tables, while I already know whick database to use, and the real tablename already hardcode in the SQLs.

**Comment by tristaZero** [comment]
@johnny2002 Got it. Thanks for your further clarification.
Just to confirm, you have the `sharding tables` and these `hint tables` meanwhile, don't you?
Your particular case made me feel you only use shardingJDBC for routing the SQL to specific DB of the DB cluster. If so, why do not you use multiple independent MySQL instances instead?

I just wanna get other advantages of your suggestion for `hintManger` apart from skipping parsing and rewriting.

**Comment by johnny2002** [comment]
> @johnny2002 Got it. Thanks for your further clarification.
> Just to confirm, you have the `sharding tables` and these `hint tables` meanwhile, don't you?
> Your particular case made me feel you only use shardingJDBC for routing the SQL to specific DB of the DB cluster. If so, why do not you use multiple independent MySQL instances instead?
> 
> I just wanna get other advantages of your suggestion for `hintManger` apart from skipping parsing and rewriting.

other advantages has been stated on your official document already:
“Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.**After that, SQL parse and rewrite phase will be skipped and the _overall enforcement efficiency can be enhanced_**”

redarding "why do not you use multiple independent MySQL instances instead", in one application, since I have already configured one Shardingsphere datasource, I don't want to repeat configure for several datasources. Otherwise, I need to implement another datasource route routine.

**Comment by tristaZero** [comment]
@johnny2002 Catch your idea. I think it is reasonable, Please give the community some time to discuss this feature. I will give the feedback here ASAP.
Thanks for your feedback. :-)

**Comment by johnny2002** [comment]
> @johnny2002 Catch your idea. I think it is reasonable, Please give the community some time to discuss this feature. I will give the feedback here ASAP.
> Thanks for your feedback. :-)

Perfect!
Suggestted solution: 
hintManager.setDatabaseShardingValue(Comparable<?> value, String logicTable,). if the logicTable is present, then use it instead of parsing SQL.

**Comment by tristaZero** [comment]
@johnny2002 After a short discussion about this issue, others also give their thoughts about it. Here is a summary,

1. Actually, `Hint` is to inject `sharding key` which does not exist in your actual table, rather than to skip parsing and rewriting.
2. If there is no `parsing`, then `rewriting SQL` can not work either. Consequently, users have to write SQL with the actual table name instead of a logic table. That will confuse the user, right?
3. We would rather take more efforts on `SQL Parser` than provide users `non-standard API`.

Welcome to your opinion!

**Comment by tristaZero** [comment]
BTW, where is the following description?  I am sorry for the confusion. If possible, would you mind raizing a PR to change the following words to avoid confusing others?

> “Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced”,

**Comment by tristaZero** [comment]
Hi @johnny2002 

It is a friendly ping. 
Could you point the location of the statements below?
So we can fix them to avoid users' confusion like you. Plus, it will be a volunteer task for the community. If you like, then welcome your PR.

> "Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced",

**Comment by johnny2002** [comment]
> Hi @johnny2002
> 
> It is a friendly ping.
> Could you point the location of the statements below?
> So we can fix them to avoid users' confusion like you. Plus, it will be a volunteer task for the community. If you like, then welcome your PR.
> 
> > "Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced",

Sorry for reply late. what is PR?

**Comment by tristaZero** [comment]
@johnny2002 It is my honor to look at your comment in my lifetimes.
The PR is,

**To remove the relevant statements below to avoid users' confusion like you.**
> Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced

**Comment by unjie** [comment]
I think that org.apache.shardingsphere.underlying.route.DataNodeRouter#createRouteContext should be placed in the implementation of org.apache.shardingsphere.underlying.common.rule.BaseRule in order to satisfy everyone's way of parsing or expanding sql to facilitate implementation Cover funation

中文:
我认为 在org.apache.shardingsphere.underlying.route.DataNodeRouter#createRouteContext 应该放到org.apache.shardingsphere.underlying.common.rule.BaseRule 的实现中,以满足大家对sql 解析或者拓展的方式,以方便实现覆盖funation

**Comment by unjie** [comment]
org.apache.shardingsphere.underlying.route.decorator.RouteDecorator:
`
/**
 * Route decorator.
 *
 * @param <T> type of rule
 */
public interface RouteDecorator<T extends BaseRule> extends OrderAware<Class<T>> {

    /**
     * Decorate route context.
     *
     * @param routeContext route context
     * @param metaData     meta data of ShardingSphere
     * @param rule         rule
     * @param properties   configuration properties
     * @return decorated route context
     */
    RouteContext decorate(RouteContext routeContext, ShardingSphereMetaData metaData, T rule, ConfigurationProperties properties);


    /**
     * Decorate route context.
     *
     * @param operation  route sql
     * @param metaData   meta data of ShardingSphere
     * @param rule       rule
     * @param properties configuration properties
     * @return decorated route context
     */
    default RouteContext decorate(DataNodeRouter.RouteContextOperation operation, ShardingSphereMetaData metaData, T rule, ConfigurationProperties properties) {
        operation.parseSQL();
        return decorate(operation.get(), metaData, rule, properties);
    }
}
`
org.apache.shardingsphere.underlying.route.DataNodeRouter
`
package org.apache.shardingsphere.underlying.route;

import org.apache.shardingsphere.sql.parser.SQLParserEngine;
import org.apache.shardingsphere.sql.parser.binder.SQLStatementContextFactory;
import org.apache.shardingsphere.sql.parser.binder.statement.CommonSQLStatementContext;
import org.apache.shardingsphere.sql.parser.binder.statement.SQLStatementContext;
import org.apache.shardingsphere.sql.parser.sql.statement.SQLStatement;
import org.apache.shardingsphere.underlying.common.config.properties.ConfigurationProperties;
import org.apache.shardingsphere.underlying.common.metadata.ShardingSphereMetaData;
import org.apache.shardingsphere.underlying.common.rule.BaseRule;
import org.apache.shardingsphere.underlying.route.context.RouteContext;
import org.apache.shardingsphere.underlying.route.context.RouteResult;
import org.apache.shardingsphere.underlying.route.decorator.RouteDecorator;
import org.apache.shardingsphere.underlying.route.hook.SPIRoutingHook;

import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 * Data node router.
 *
 * @author unjie
 */
public final class DataNodeRouter {
    private final ShardingSphereMetaData metaData;
    private final ConfigurationProperties properties;
    private final SQLParserEngine parserEngine;
    private final Map<BaseRule, RouteDecorator> decorators = new LinkedHashMap();
    private SPIRoutingHook routingHook = new SPIRoutingHook();

    public DataNodeRouter(ShardingSphereMetaData metaData, ConfigurationProperties properties, SQLParserEngine parserEngine) {
        this.metaData = metaData;
        this.properties = properties;
        this.parserEngine = parserEngine;
    }

    public void registerDecorator(BaseRule rule, RouteDecorator decorator) {
        this.decorators.put(rule, decorator);
    }

    public RouteContext route(String sql, List<Object> parameters, boolean useCache) {
        this.routingHook.start(sql);

        try {
            RouteContext result = this.executeRoute(sql, parameters, useCache);
            this.routingHook.finishSuccess(result, this.metaData.getSchema());
            return result;
        } catch (Exception var5) {
            this.routingHook.finishFailure(var5);
            throw var5;
        }
    }

    private RouteContext executeRoute(String sql, List<Object> parameters, boolean useCache) {
        RouteContextOperation operation = new RouteContextOperation(this.metaData, sql, parameters, useCache, this.parserEngine);
        RouteContext result = null;
        Entry entry;
        for (Iterator var5 = this.decorators.entrySet().iterator(); var5.hasNext(); result = ((RouteDecorator) entry.getValue()).decorate(operation, this.metaData, (BaseRule) entry.getKey(), this.properties)) {
            entry = (Entry) var5.next();
        }

        return result;
    }

    public class RouteContextOperation {
        private SQLParserEngine parserEngine;
        private ShardingSphereMetaData metaData;
        private String sql;
        private RouteContext result = null;
        private List<Object> parameters;
        private boolean useCache;
        private SQLStatement sqlStatement;


        public RouteContextOperation(ShardingSphereMetaData metaData, String sql, List<Object> parameters, boolean useCache, SQLParserEngine parserEngine) {
            this.metaData = metaData;
            this.sql = sql;
            this.parameters = parameters;
            this.useCache = useCache;
            this.parserEngine = parserEngine;
        }

        public void parseSQL() {
            if (sqlStatement == null) {
                sqlStatement = parserEngine.parse(sql, useCache);
            }
        }

        public RouteContext get() {
            if (result == null) {
                createRouteContext();
            }
            return result;
        }

        public RouteContext createRouteContext() {
            try {
                SQLStatementContext sqlStatementContext = SQLStatementContextFactory.newInstance(this.metaData.getSchema(), sql, parameters, sqlStatement);
                return result = new RouteContext(sqlStatementContext, parameters, new RouteResult());
            } catch (IndexOutOfBoundsException var6) {
                return result = new RouteContext(new CommonSQLStatementContext(sqlStatement), parameters, new RouteResult());
            }
        }
    }

}
`

**Comment by unjie** [comment]
I have completed the test of the above code,RouteDecorator implements class is not open code
中文:
上述代码我已完成测试, RouteDecorator implements class 未开放代码

**Comment by tristaZero** [comment]
Hi @unjie 
Thanks for your comment. Although I want to catch your idea, the rough and unformatted code clips held me back.
Could you raize a PR to present your programming and thought?

Very appreciated that,
Trista

**Comment by kimmking** [comment]
This post is silent for 2 weeks and discussion out of the original topic, so I should close it now.
And anything forward and can help us move on NEED TO open a new issue to track it.
Thanks guys.

**Comment by gongguoyu** [comment]
same question:

https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/usage/hint/

Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables. After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced.

**Comment by tristaZero** [comment]
Hi @gongguoyu, It seems we will begin an `archeological` work.
First, @unjie thanks for your comments. If your idea is a general and universal solution, welcome your PR to make it merged into the master branch. :-) What's more, I suppose a simple explanation about your approach will make others catch your idea easily
Second, @gongguoyu Is your case only about database-sharding rather than table-sharding? As if users want to set table sharding value with hintManager, parsing work is needed to rewrite the logic SQLs to actual SQLs.

**Comment by gongguoyu** [comment]
thanks for your response.
in my situation,i just need database-sharding and no table-sharding. now batch insert 4000 rows will take 32s, and What can I do to improve the speed？

sql like this: insert into pressure(userid,orderid) values(?, ?),(?,?),...
sharding-jdbc 4.0.0-RC2,   MYSQL  5.7.12-log

_the following is some of my log while batch insert 4000 rows:
2020-10-28 13:19:37.759  INFO 9960 --- [nio-9002-exec-1] c.h.s.test.config.ShardingJDBCConfig     : HintShardingAlgorithm.doSharding
2020-10-28 13:19:37.759  INFO 9960 --- [nio-9002-exec-1] c.h.s.test.config.ShardingJDBCConfig     : 数据库路由完毕.
2020-10-28 13:19:38.553 DEBUG 9960 --- [nio-9002-exec-1] c.h.s.test.mapper.MapperTest.insertData  : <==    Updates: 4000
2020-10-28 13:19:38.562  INFO 9960 --- [nio-9002-exec-1] c.h.sharding.test.controller.controller  : sql: 30.554s_

**Comment by tristaZero** [comment]
@gongguoyu So a later version solved your issue, right?

**Comment by Jiugang** [comment]
@tristaZero The following statements still not removed，which mislead me for 2~3 days until I find this post.

> @johnny2002 It is my honor to look at your comment in my lifetimes. The PR is,
> 
> **To remove the relevant statements below to avoid users' confusion like you.**
> 
> > Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced

**Comment by tristaZero** [comment]
@Jiugang Sorry for my late response, Thanks. @RaigorJiang could you have a look here?

**Comment by RaigorJiang** [comment]
> @tristaZero The following statements still not removed，which mislead me for 2~3 days until I find this post.
> 
> > @johnny2002 It is my honor to look at your comment in my lifetimes. The PR is,
> > **To remove the relevant statements below to avoid users' confusion like you.**
> > > Users can use hintManager.setDatabaseShardingValue to add shardings in hint route to some certain sharding database without sharding tables.After that, SQL parse and rewrite phase will be skipped and the overall enforcement efficiency can be enhanced

Removed by https://github.com/apache/shardingsphere/pull/12190.

**Comment by Jiugang** [comment]
@tristaZero OK, thank you.
