### ISSUE TITLE
to support arbitrary SQL with HintShardingAlgorithm

### ISSUE THREAD

**Issue by johnny2002** [apache/shardingsphere#6463]
## Feature Request

Since we have an ETL Job need to use very complex SQL, we suggest sharding-jdbc can skip SQL parsing to support arbitrary SQL.
As I understand, with HintShardingAlgorithm, sharding-jdbc still need to parse SQL to get logicTableName so that it can get sharding configuration.
So, I suggest sharding-jdbc provide some method to let developer to set the logicTableName, so that it can skip SQL parsing. In this way,  sharding-jdbc can support any complex SQL.

**Comment by johnny2002** [comment]
For an example:

HintManager hintManager = HintManager.getInstance();
hintManager.setDatabaseShardingValue("0");
**hintManager.setLogicTableName("tab_user");** //add this method to set logic table name, so that parsing sql is not neccesary

boolean rst = statement.execute("insert into ... select ... from .... group by ... having...");

**Comment by kimmking** [comment]
duplicated with #6458
