### ISSUE TITLE
Support ShardingSphere-defined RDL SQL 

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6466]
Hi community,

We plan to provide **RDL(Rule Definition Language)** for `ShardingProxy` since the 5.x version. This feature simplifies the tedious workload for the Sharding configuration. 
The user can start ShardingProxy without `sharding rule` (However, the registry center is required for the rule durability), then the user can create a sharding rule or a sharding table through RDL SQL.

Presently, the execution part for `RDL` is basically done, and this issue is to parse RDL SQL out and provide the corresponding SQLParser.

**Comment by strongduanmu** [comment]
This feature sounds great!
