### ISSUE TITLE
Whether multiple shardingjdbc datasources can be created

### ISSUE THREAD

**Issue by peng-ran** [apache/shardingsphere#6473]
I don't want to define a lot of table rules, because most tables don't need sharding, so I want to define multiple Sharding-JDBC data sources, each of which is only responsible for table sharding by default database ，Is that all right？

**Comment by kimmking** [comment]
You have to config your sharding tables in config file.

**Comment by peng-ran** [comment]
My idea is to create multiple sharding - JDBC data sources, namely ShardingDataSourceFactory. CreateDataSource more, each data source is a sub-database and set himself to the default data source, in this way, the sub-tables will be configuration, but a lot of non-sub-tables without configuration can also be automatically routed to the current data source of the sub-database.

In my service invocation ShardingDataSourceFactory CreateDataSource many times, and according to the business logic to switch.I want to avoid sub-databse with a lot of tables that don't need to be sharded, and I don't want to maintain them in code or configuration files.

Ihave to config my sharding tables in config file，but, i have a lot of non-sharding-tables need routed. i dont want
define thems.

@kimmking

**Comment by tristaZero** [comment]
Hi @peng-ran Thanks for your issue.
If there are sharding tables and non-sharding tables in your project which you do not want to configure, you can consider `defaultDatasource`.
>  Default Datasource: All unconfigured tables will be routed here.
The documents will give you more detail.

**Comment by peng-ran** [comment]
@tristaZero  3q. but defaultDatasource only one datasource, a lot of non-sub-tables need route to sub-database. so i invoke ShardingDataSourceFactory. CreateDataSource more, each of  them defaultDatasource  is a  sub-database.

**Comment by peng-ran** [comment]
I wanted to know that ShardingJDBC can have multiple sharding-jdbc data source instances that are secure in the process, and a single sharding-jdbc data source would not satisfy my scenario

**Comment by kimmking** [comment]
Both raw-jdbc or spring configuration way, you can configure several sharding datasources with different names of their instances.

**Comment by tristaZero** [comment]
@peng-ran It is possible to create more than one ShardingDataSource in your project. Another way is to configure those non-sharding table with `NoneShardingStrategy` (Generally, one table without ShardingStrategy will be created as a non-sharding table.)

**Comment by peng-ran** [comment]
@tristaZero @kimmking Many thanks
