### ISSUE TITLE
 Commons - DBCP cannot be used in 4.1.1

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#6484]
Commons - DBCP 1.4  cannot be used in 4.1.1  but can be used in 4.0.1.

The same configuration is just a different version.

WARN 2020-07-28 13:41:08,235 [org.springframework.context.support.ClassPathXmlApplicationContext] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.mybatis.spring.mapper.MapperScannerConfigurer#0' defined in file [D:\workspacesharding\apache-shardingsphere-4.1.1-src-release\test-sharding\target\test-classes\app_config.xml]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in file [D:\workspacesharding\apache-shardingsphere-4.1.1-src-release\test-sharding\target\classes\app_config.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shardingsphere.shardingjdbc.spring.datasource.SpringShardingDataSource]: Constructor threw exception; nested exception is java.lang.AbstractMethodError: org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.getSchema()Ljava/lang/String;

why?Is there any requirement for DBCP version in 4.1.1?

**Comment by tristaZero** [comment]
Hi @65725738 
Thanks for your question.
IMO,  this is not about DBCP and more possibility is the sharding configuration. Could you compare your configuration with [4.1.1 examples](https://github.com/apache/shardingsphere/tree/4.1.1/examples/sharding-jdbc-example/sharding-example) ?

**Comment by kimmking** [comment]
You should use DBCP 2.x to adapter jdbc 4.1+ [1]: 
```
DBCP 2.7.0 compiles and runs under Java 8 only (JDBC 4.2)
DBCP 2.6.0 compiles and runs under Java 8 only (JDBC 4.2)
DBCP 2.5.0 compiles and runs under Java 8 only (JDBC 4.2)
DBCP 2.4.0 compiles and runs under Java 7 only (JDBC 4.1)
DBCP 1.4 compiles and runs under Java 6 only (JDBC 4)
DBCP 1.3 compiles and runs under Java 1.4-5.0 only (JDBC 3)
```

1. http://commons.apache.org/proper/commons-dbcp/
