### ISSUE TITLE
[Document]Revise the orchestration documents with the new API

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#6492]
After the #6445 (Redesign orchestration API) has been finished, it's time to sync the orchestration documents with the new well-defined API now.
We will show more sub-tasks soon.
---------

- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/governance.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/governance.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/yaml/governance.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/yaml/governance.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/governance.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/governance.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/governance.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/governance.en.md

- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/java-api.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/java-api.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/yaml.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/yaml.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/spring-namespace.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/spring-namespace.en.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/spring-boot-starter.cn.md
- [x] docs/document/content/user-manual/shardingsphere-jdbc/usage/governace/spring-boot-starter.en.md

- [x] docs/document/content/user-manual/shardingsphere-proxy/usage/governance.cn.md
- [x] docs/document/content/user-manual/shardingsphere-proxy/usage/governance.en.md

- [x] docs/document/content/dev-manual/governance.en.md
- [x] docs/document/content/dev-manual/governance.en.md

**Comment by yu199195** [comment]
i will check
