### ISSUE TITLE
Support createProcedure SQL query for MySQL

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6498]
This issue is related to #6430 .

### Background

Currently, `createProcedure` is difined in `DDLStatement.g4` of `<artifactId>shardingsphere-sql-parser-mysql</artifactId>`.
However, ShardingSphere does not visit it out as a `createProcedureStatment`. 

### Steps

Therefore, to solve #6430, we need to
1. Review the definition of `createProcedure`
1. Visit AST to get `createProcedureStatmen`
2. Add the SQL test.

### Bonus
1. If possible, we can consider reviewing all the definitions of `xxxStatement` for MySQL. My concern is that some of SQLs only have descriptions, but no `xxxStatement`. However, it is not an easy job, so we can consider `DDLStatemnt` as the start! (It is not **MUST** job, just an extra suggestion for its assignees).

### Notice

1. Actually, maybe this work can either not make `createProcedure` query work well; however, we can finish the first step in the parsing process at least. :)

**Comment by strongduanmu** [comment]
@tristaZero I will try to fix this issue, please assign it to me. 😀
