### ISSUE TITLE
shardingsphere 分库分表的数量限制是多少呢？

### ISSUE THREAD

**Issue by COMEONYAO** [apache/shardingsphere#6505]
我在官网没有找到分库分表数量说明，当库表数量各达到什么峰值，会影响数据库插入读取效率。
我曾经试过100库，每个库100表，使用shardingsphere 插入1000条记录要28s，当然这1000条记录平均分布到每个库每个表。

麻烦可以给出官方答复

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by COMEONYAO** [comment]
I didn't find the description of the Maximum of sub databases and sub tables on the shardingsphere official website. 

I have tried 100 databases. Each database has 100 tables. It takes 28s to insert 1000 records using shardingsphere. Of course, the 1000 records are evenly distributed to each database and table, 28s is too long.

too many databases or to many tables?

Please give an official reply
