### ISSUE TITLE
How to solve the problem of too many database connections

### ISSUE THREAD

**Issue by iamzxj** [apache/shardingsphere#6508]
How to solve the problem of too many database connections

**Comment by jingshanglu** [comment]
@iamzxj Plz show more detail info, such as:

- stack info
- background of use

**Comment by iamzxj** [comment]
The data source is divided into 30 databases. Every time the service is started, the number of connections to the mysql8 database reaches more than 5000

**Comment by iamzxj** [comment]
Error occured while trying to connect to the database
Error connecting to database: (using class org.gjt.mm.mysql.Driver)
Data source rejected establishment of connection, message from server: “Too many connections”

**Comment by tuohai666** [comment]
Suppose the connections reached 6000. 
maxPoolSize of HikariCp is 6000 / 30 = 200.
Reduce the maxPoolSize will solve this problem.
