### ISSUE TITLE
ComplexKeysShardingAlgorithm 复合分片算法，不支持多列不同类型的值。

### ISSUE THREAD

**Issue by liyiorg** [apache/shardingsphere#6526]
你好，复合分片算法接口   ComplexKeysShardingAlgorithm<T extends Comparable<?>> 泛型约定了不能使用Object 对象。

但实际使用中，如多个分片列的数据类型可能不一样。
例如，使用表列 transid 、 trade_time 同时作为分片key 时。 分别对应 String, java.sql.Timestamp 。
希望作者能修改泛型非强制继承Comparable 。或者如果设定泛型为 String 类型时，调用toString() 转换下。

```SQL
CREATE TABLE `bin_order` (
	`transid` VARCHAR(50) NOT NULL COMMENT '交易号',
	`trade_time` DATETIME NULL DEFAULT NULL COMMENT '交易时间',
	PRIMARY KEY (`transid`)
)
COMMENT='订单表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

```

**Comment by kimmking** [comment]
English only here.
Can you translate your post?

**Comment by kimmking** [comment]
java.sql.Timestamp -> java.util.Date -> Comparable

**Comment by yililiangbaikai** [comment]
所以怎么解决复合分片键值类型不一样的问题？
