### ISSUE TITLE
what is the Maximum of sub databases and sub tables on the shardingsphere

### ISSUE THREAD

**Issue by COMEONYAO** [apache/shardingsphere#6532]
I didn't find the description of the Maximum of sub databases and sub tables on the shardingsphere official website.

I have tried 100 databases. Each database has 100 tables. It takes 28s to insert 1000 records using shardingsphere. Of course, the 1000 records are evenly distributed to each database and table, 28s is too long.

too many databases or to many tables?

Please give an official reply

**Comment by kimmking** [comment]
Generally, there is no limit for sharding-db/tables here.
Full routing will be executed for a long term, so we should use precise sharding strategy to avoid it.
