### ISSUE TITLE
can't connect sharding-proxy 4.1.1 from navicat premium 15

### ISSUE THREAD

**Issue by cay914** [apache/shardingsphere#6533]
can't connect sharding-proxy 4.1.1 from navicat premium 15

I installed the sharding-proxy form https://shardingsphere.apache.org/ 's instruction。
The sharding-proxy server is up and running, **But I cant connect from navicat!**

and I alway get this erorr
![image](https://user-images.githubusercontent.com/6037435/88906290-dc80c300-d289-11ea-88c3-d84d66d9b304.png)

my config file:
[config-files.zip](https://github.com/apache/shardingsphere/files/5000317/config-files.zip)

and the log is ok:
sharding-proxy    | [INFO ] 17:20:52.412 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
sharding-proxy    | [INFO ] 17:20:52.659 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
sharding-proxy    | [INFO ] 17:20:52.660 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
sharding-proxy    | [INFO ] 17:20:52.666 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
sharding-proxy    | [INFO ] 17:20:52.708 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/opt/apache-shardingsphere-4.1.1-sharding-proxy-bin/lib/transactions-4.0.6.jar!/transactions-defaults.properties
sharding-proxy    | [INFO ] 17:20:52.709 [main] c.a.icatch.provider.imp.AssemblerImp - Loaded jar:file:/opt/apache-shardingsphere-4.1.1-sharding-proxy-bin/lib/sharding-transaction-xa-atomikos-manager-4.1.1.jar!/transactions.properties
sharding-proxy    | [WARN ] 17:20:52.768 [main] c.a.icatch.provider.imp.AssemblerImp - Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
sharding-proxy    | or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
sharding-proxy    | Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
sharding-proxy    | or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
sharding-proxy    | [INFO ] 17:20:52.776 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_max_wait_time_on_shutdown = 9223372036854775807
sharding-proxy    | [INFO ] 17:20:52.776 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.allow_subtransactions = true
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.recovery_delay = 300000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.automatic_resource_registration = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_max_retries = 5
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.client_demarcation = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.threaded_2pc = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.serial_jta_transactions = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_dir = ./logs
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.rmi_export_class = none
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_actives = 10000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.checkpoint_interval = 50000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.enable_logging = true
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.log_base_name = xa_tx
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.max_timeout = 300000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.trust_client_tm = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.factory.initial = com.sun.jndi.rmi.registry.RegistryContextFactory
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.tm_unique_name = 192.168.3.32.tm
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.forget_orphaned_log_entries_delay = 86400000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.oltp_retry_interval = 10000
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: java.naming.provider.url = rmi://localhost:1099
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.force_shutdown_on_vm_exit = false
sharding-proxy    | [INFO ] 17:20:52.777 [main] c.a.icatch.provider.imp.AssemblerImp - USING: com.atomikos.icatch.default_jta_timeout = 300000
sharding-proxy    | [INFO ] 17:20:52.778 [main] c.a.icatch.provider.imp.AssemblerImp - Using default (local) logging and recovery...
sharding-proxy    | [INFO ] 17:20:52.820 [main] c.a.d.xa.XATransactionalResource - resource-1-order_0: refreshed XAResource
sharding-proxy    | [INFO ] 17:20:52.846 [main] c.a.d.xa.XATransactionalResource - resource-2-order_1: refreshed XAResource
sharding-proxy    | [INFO ] 17:20:53.361 [main] ShardingSphere-metadata - Loading 1 logic tables' meta data.
sharding-proxy    | [INFO ] 17:20:53.675 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x23f87694] REGISTERED
sharding-proxy    | [INFO ] 17:20:53.676 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x23f87694] BIND: 0.0.0.0/0.0.0.0:3307
sharding-proxy    | [INFO ] 17:20:53.678 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x23f87694, L:/0.0.0.0:3307] ACTIVE
sharding-proxy    | [INFO ] 17:21:05.499 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x23f87694, L:/0.0.0.0:3307] READ: [id: 0x25356b28, L:/192.168.3.32:3307 - R:/192.168.3.15:7586]
sharding-proxy    | [INFO ] 17:21:05.503 [epollEventLoopGroup-2-1] i.n.handler.logging.LoggingHandler - [id: 0x23f87694, L:/0.0.0.0:3307] READ COMPLETE

**Comment by kimmking** [comment]
see https://shardingsphere.apache.org/document/current/cn/faq/#22-%E5%9C%A8%E4%BD%BF%E7%94%A8shardingsphere-proxy%E6%97%B6%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%E5%90%88%E9%80%82%E7%9A%84%E5%B7%A5%E5%85%B7%E8%BF%9E%E6%8E%A5%E5%88%B0shardingsphere-proxy

**Comment by cay914** [comment]
pleasse support navicat 15 prenium, man. it's a major tool for developer. 
The navicat 11 is too old, thanks.
