### ISSUE TITLE
[Performance Test] Provide a full-scale and multi-scenario benchmark test

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#6536]
Hi Community,

### Background
I know `performance test` is your concern when considering a new solution for your systems or projects. Recently we received many feedbacks and complaints about our benchmark graphs. 

After a rough discussion, we decide to commit more energy to the performance test of Apache ShardingSpehre and **provide a full-scale and multi-scenario benchmark test for the subsequent releases**.

### Content
1. The comparison among various releases.
2. The comparison among `ShardingJDBC`, `ShardingProxy`, and `MySQL`.
3. The comparison among `Sharding feature`, `Encrypt feature`, `MasterSlave feature.`
4. Different query SQLs for the above.
5. Benchmark UI

### Project
[shardingsphere-benchmark](https://github.com/apache/shardingsphere-benchmark)

**Comment by wcsoft** [comment]
Recently i have been investigating ShardingProxy and ShardingJDBC performance. 

Senarios i did
- Base Data 1000w vs Base Data 1000, observe tps of ShardingDBC & ShardingProxy;
- With base data 1000w, comparing ShardingJDBC&ShardingProxy to Mysql, observe tps of ShardingDBC & ShardingProxy and Mysql;

Result i got
- At senario 1 - base data 1000w vs base data 1000, ShardingDBC & ShardingProxy tps improves a lot with base data 1000w, refer to image 1 as detail data ;
- At senario 2 - with base data 1000w, comparing ShardingJDBC&ShardingProxy to Mysql, their tps is  much better for full routing select/full routing insert+update+delete/masterslave+encrpytinsert+update+delete than mysql. In addition their tps is lower than Mysql,  refer to image 2 as detail data ;

![image](https://user-images.githubusercontent.com/8036861/88928887-f03d2100-d2ab-11ea-9e4b-b0910e820527.png)

![image](https://user-images.githubusercontent.com/8036861/88928957-05b24b00-d2ac-11ea-903d-fa4f08d4088b.png)
