### ISSUE TITLE
Use SPI to introduce ClusterConfiguration in OrchestrationShardingSphereDataSource

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6547]
It is better to decouple ClusterConfiguration and OrchestrationShardingSphereDataSource.
Please use SPI to introduce ClusterConfiguration.
Just reference `MetricsConfiguration`

**Comment by kimmking** [comment]
It seems metrics is not loaded in jdbc-orchestration. @menghaoranss @yu199195

**Comment by kimmking** [comment]
ClusterConfiguration has been removed.
