### ISSUE TITLE
help sharingjdbc4.0.1  oracle page  

### ISSUE THREAD

**Issue by Spole0168** [apache/shardingsphere#6550]
I am using the 4.0.1 version of sharingjdbc to link to the oracle database and encounter problems with paging display data.
Currently sharingjdbc supports nesting of subqueries once, but Oracle paging can only be achieved by nesting twice with rownum. The recommendation on the official website is the same. When using it, it will report an error "Must have sharding column with subquery", just remove one level of nesting.
How to deal with Oracle paging?

Official suggestion link:
https://shardingsphere.apache.org/document/legacy/4.x/document/cn/features/sharding/use-norms/pagination/

![image](https://user-images.githubusercontent.com/28697512/89009228-ad785900-d33e-11ea-94a6-a5fb7131e6b6.png)
![image](https://user-images.githubusercontent.com/28697512/89009236-b23d0d00-d33e-11ea-9a40-25babcc11871.png)

**Comment by tristaZero** [comment]
Hi @Spole0168 Release has bad support for `subquery`. My suggestions are,
1. Make your SQL not contain `subquery`
2. Use our `master branch` for a test, since `master branch` has many improvements for `subquery.`

**Comment by Spole0168** [comment]
Thank you very much, 
currently shardingjdbc4.0.1 version cannot perform oracle paging.
 I try other versions.
