### ISSUE TITLE
Consider about redesign metrics configuration

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6577]
The current metrics configuration persist with port into config center, which is not adapter for cloud native design.
IP should not persist with orchestration module.
It is better to consider about redesign it.

**Comment by menghaoranss** [comment]
Refer #6546

- [ ] 1. Remove  `port`  from system environment
- [ ] 2. Persist global metrics configuration to  config center
- [ ] 3. Talk about whether to save the `port` of metrics
- [ ] 4. Refactor listeners and unit tests

**Comment by kimmking** [comment]
Cause the same reason with #7013, we close this issue now.
