### ISSUE TITLE
Add test cases for DatabaseType

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6590]
I just provide an example for `MySQLDatabaseType`, please ref it to finish remain test cases.

- [ ] H2DatabaseType
- [ ] MariaDBDatabaseType
- [ ] OracleDatabaseType
- [ ] PostgreSQLDatabaseType
- [ ] SQL92DatabaseType
- [ ] SQLServerDatabaseType

**Comment by taojintianxia** [comment]
assign to me .

**Comment by taojintianxia** [comment]
done
