### ISSUE TITLE
Finish test cases for infra.spi

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6594]
- [x] OrderedSPIRegistry
- [x] SingletonServiceLoader
- [x] TypedSPIRegistry
- [x] ShardingSphereServiceLoader for register twice
- [x] ShardingSphereServiceLoader for new instance error

**Comment by jacksparrow414** [comment]
could you assign me? :smile:

**Comment by jacksparrow414** [comment]
- [x] OrderedSPIRegistry
- [x] SingletonServiceLoader
- [ ] TypedSPIRegistry
- [ ] ShardingSphereServiceLoader for register twice
- [ ] ShardingSphereServiceLoader for new instance error

**Comment by jacksparrow414** [comment]
- [x] OrderedSPIRegistry
- [x] SingletonServiceLoader
- [x] TypedSPIRegistry
- [x] ShardingSphereServiceLoader for register twice
- [x] ShardingSphereServiceLoader for new instance error
