### ISSUE TITLE
adapting the ShenTong database

### ISSUE THREAD

**Issue by jameszhongsq** [apache/shardingsphere#6605]
Do you support domestic databases,For Examples ShenTong，dameng? I'm adapting the ShenTong database,
 ShenTong driver is : jdbc_mysql_driverUrl=jdbc:oscar://192.168.2.182:2003/OSRDB。The following error was encountered：
java.lang.UnsupportedOperationException: Can not support database type [OSCAR]

**Comment by yu199195** [comment]
we not support ShenTong database。。
