### ISSUE TITLE
Why not support the ‘point’ field？

### ISSUE THREAD

**Issue by yz-1130** [apache/shardingsphere#6625]
I have this question, I don't know how to solve it, because it is an old project, there is no way to change the field name. I have a ‘point’ field in the database table users, and it fails when I insert data or query data, and it’s no problem to change to other fields.
 Questions are as follows:

‘line 3:37 no viable alternative at input 'point,'
line 3:37 no viable alternative at input 'point,'
2020-08-05 11:00:12.886 ERROR 36606 --- [qtp940937618-39] .t.m.c.s.DefaultMemberPointUpReadService : Failed to find by id 1, cause org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
’
is this is a bug？Can anyone tell me how to solve this problem？

**Comment by yu199195** [comment]
`point `  maybe mysql keyword, please another field or use `point`.

**Comment by yu199195** [comment]
any question？ if not we will close

**Comment by yz-1130** [comment]
> not

no.   I. have done

**Comment by yz-1130** [comment]
> `point ` maybe mysql keyword, please another field or use `point`.

you are right ,I have solved

**Comment by jingshanglu** [comment]
@yz-1130 Now, mysql keywords have been checked, master branch is ok, new version will fix it.
