### ISSUE TITLE
the class "BindingTableRule" to get  the ActualTable's name been toLowerCase

### ISSUE THREAD

**Issue by karkaw** [apache/shardingsphere#6629]
When the logical table is uppercase, when bindrule is set, the BindingTableRule.getBindingActualTable Is converted to lowercase. The result is that the table cannot be found when two and more table to join 。

**Comment by menghaoranss** [comment]
Could you provide any configuration or log to describe your problem?

**Comment by karkaw** [comment]
1、the env is hibernate + spring +mysql (the mysql config ： lower_case_table_names = 0 大小写敏感 ) ，and the all logic lable 's name is uppercase 。
2、the sharding config as :
     <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="JC_ZONE,JC_ZONE_ORGANIZATION" />
     </sharding:binding-table-rules>
3、To execute the SQL as  "select * from JC_ZONE z join JC_ZONE_ORGANIZATION zo " , the exception as "the table's jc_zone_organization_1 not exist" 。 notice ：JC_ZONE and JC_ZONE_ORGANIZATION is a one to many relationship。

End

I've tracked the code  to lowercase  in the BindingTableRule.getBindingActualTable() ,
as " each.getActualDataNodes().get(index).getTableName().toLowerCase()" 。

Please confirm if there is the problem

**Comment by menghaoranss** [comment]
@karkaw refer to [#3635](https://github.com/apache/shardingsphere/issues/3635)
