### ISSUE TITLE
SELECT DISTINCT test cases error

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#6658]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Both

### Expected behavior

SELECT DISTINCT test cases pass.

### Actual behavior

When execute the integration test with MySQL, some of the SELECT DISTINCT cases failed.

### Reason analyze (If you can)

Maybe caused by https://github.com/apache/shardingsphere/pull/4597

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. env.properties:
databases=MySQL

2. hosts: (suppose your MySQL is on localhost)
add 127.0.0.1 db.mysql

3. mvn clean install

### Example codes for reproduce this issue (such as a github link).

Refer to #6603

**Comment by kimmking** [comment]
Case 1: shardingsphere-integration-test/shardingsphere-test-suite/src/test/resources/integrate/cases/dql/dataset/tbl/select_distinct_with_avg.xml

The original sql
```
SELECT AVG(DISTINCT order_id) FROM t_order WHERE order_id < 1100
```

convert to:
```
SELECT DISTINCT order_id AS AGGREGATION_DISTINCT_DERIVED_0 , order_id AS AVG_DERIVED_COUNT_0 , order_id AS AVG_DERIVED_SUM_0 FROM t_order_0 WHERE order_id < 1100
SELECT DISTINCT order_id AS AGGREGATION_DISTINCT_DERIVED_1 , order_id AS AVG_DERIVED_COUNT_0 , order_id AS AVG_DERIVED_SUM_0 FROM t_order_0 WHERE order_id < 1100
```

Rewriting result is wrong

**Comment by kimmking** [comment]
With debug, the GroupBy generated  return empty. 
```
    public GroupByContext createGroupByContext(final SelectStatement selectStatement) {
        if (!selectStatement.getGroupBy().isPresent()) {
            return new GroupByContext(new LinkedList<>(), 0);
        }
```

**Comment by tuohai666** [comment]
According to the docs https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/ , this is an unsupported SQL. I'll remove it from the integration test cases.
