### ISSUE TITLE
Statement setFetchDirection not supported

### ISSUE THREAD

**Issue by VincentChi** [apache/shardingsphere#6661]
## Feature Request
setFetchDirection is not supported and would throw exception
org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationStatement#setFetchDirection

### Is your feature request related to a problem?
We are using apache mahout which uses this method in db initialization, but would throw exception.
![image](https://user-images.githubusercontent.com/1518651/89497565-2e2bcf00-d7ef-11ea-8d9d-b0b164982893.png)

### Describe the feature you would like.
It's better to support this feature, or just make it not final which could be overridden in our codes.
**
![image](https://user-images.githubusercontent.com/1518651/89497684-6b905c80-d7ef-11ea-8fd4-3f4c39e41a65.png)
**

**Comment by yu199195** [comment]
we not support setFetchDirection，maybe cannot integrateion apache mahout， thanks！

**Comment by tristaZero** [comment]
Thanks for your debug. @VincentChi 
We welcome you or other guys to try to fix this issue, for it seems not difficult.
You can remove `final` from `setFetchDirection` and implement it in `AbstractPreparedStatementAdapter` and `ShardingSpherePreparedStatement`.

If you need any help, please feel free to ping us!

Best,
Trista

**Comment by wenweibin** [comment]
> Thanks for your debug. @VincentChi
> We welcome you or other guys to try to fix this issue, for it seems not difficult.
> You can remove `final` from `setFetchDirection` and implement it in `AbstractPreparedStatementAdapter` and `ShardingSpherePreparedStatement`.
> 
> If you need any help, please feel free to ping us!
> 
> Best,
> Trista

Can this be assgined to me?

**Comment by tristaZero** [comment]
My pleasure. @wenweibin

**Comment by terrymanu** [comment]
@wenweibin Hi, any update?

**Comment by kimmking** [comment]
@wenweibin any improvement or close this issue for a long time?
