### ISSUE TITLE
Can ShardingSphere cooperate with Orchestrator product to seamlessly feel the MySQL HA/Cluster status changes without any coding works

### ISSUE THREAD

**Issue by zhaopinglu** [apache/shardingsphere#6662]
This is a suggestion!
Orchestrator is a great MySQL cluster management tool. It supports to save the cluster status into zookeeper. 
ShardingSphere don't have such capability right now, but it's important for user. So, why not ShardingSphere leverage the status info in zookeeper to complete this missing part? If it works, then the users can get benefit from this integration without any coding works. This could be a triple WIN solutions. Do you agree?

Moreover, maybe you guys can make an agreement on a set of cluster status protocols, then develop some even more userful and complicate scenarios for end users. 

Hope it works.
Thanks.
Luke.

Ref Links:
https://github.com/openark/orchestrator
https://github.com/openark/orchestrator/blob/master/docs/configuration-kv.md

**Comment by tristaZero** [comment]
Hi @zhaopinglu 
Your issue inspired me with a lot of the possibility of an enhancement feature. Firstly, thanks for your great idea!
We need to give it a discussion and some studies.

Best,
Trista

**Comment by zhaopinglu** [comment]
Glad to be helpful. Hope to see the function come true ASAP.

**Comment by kimmking** [comment]
Orchestrator is awesome middlewire that focus on MySQL HA.
ShardingSphere now focus on sharding and scaling.
If you are interested in taking the HA like master-slave switch in-time, welcome to contribute this project here.

BTW: ShardingSphere in master branch have keep all nodes status in zk now.

**Comment by tristaZero** [comment]
@kimming
There is the nuance between `MySQL HA` and `keep all nodes status in zk `.
I am interested in this one and maybe we can give it research.

**Comment by tristaZero** [comment]
Hi @zhaopinglu 

Thanks for your proposal. 

Lately, I spent some time investigating this product and considered the feasibility of importing it into the ShardingSphere ecosystem. [Community Mail list](https://lists.apache.org/thread.html/r9d99ce07c77ff5ee781bbaad02b024c947d3340fdec9649305b4d0b8%40%3Cdev.shardingsphere.apache.org%3E) will show you more about my opinion and thinkings. 

We welcome anyone interested in this feature to participate in the discussion. :-)

Best wishes,
Trista
