### ISSUE TITLE
sharding-jdbc sharding performance

### ISSUE THREAD

**Issue by lishijun121910** [apache/shardingsphere#6676]
I am using sharding-jdbc , seperating one table(30,000,000 rows) to 64 tables(500,000 rows)
And I have done some tests, compare to mysql 

mysql config:
spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/shardingdb?useSSL=false
    username: xxxx
    password: xxxx
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      connection-timeout: 300000
      connection-test_query: SELECT 1
      max-lifetime: 0
      auto-commit: true
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000

QPS and ART
![image](https://user-images.githubusercontent.com/8045307/89533114-7d8cf200-d825-11ea-819c-0cd720493784.png)
![image](https://user-images.githubusercontent.com/8045307/89533152-8bdb0e00-d825-11ea-84e2-51cfcc1ae730.png)

sharding-jdbc config:
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://xx.xx.xxx.xx:3306/shardingdb?useSSL=false
        username: xxxx
        password: xxxx
        pool-name: HikariCP
        connection-timeout: 300000
        connection-test_query: SELECT 1
        max-lifetime: 0
        auto-commit: true
        maximum-pool-size: 100
        minimum-idle: 10
        idle-timeout: 600000

QPS and ART
![image](https://user-images.githubusercontent.com/8045307/89533252-ba58e900-d825-11ea-9a64-4931b1063a98.png)
![image](https://user-images.githubusercontent.com/8045307/89533348-de1c2f00-d825-11ea-9f9f-65ca33598363.png)

sharding-jdbc config:
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://xx.xx.xxx.xx:3306/shardingdb?useSSL=false
        username: xxxx
        password: xxxx
        pool-name: HikariCP
        connection-timeout: 300000
        connection-test_query: SELECT 1
        max-lifetime: 0
        auto-commit: true
        maximum-pool-size: 100
        minimum-idle: 10
        idle-timeout: 600000
    sharding:
      tables:
        T_MERCHANT:
          actual-data-nodes: ds0.T_MERCHANT${0..63}
          table-strategy:
            inline:
              sharding-column: MCC_ID
              algorithm-expression: T_MERCHANT${MCC_ID % 64}

QPS and ART:
![image](https://user-images.githubusercontent.com/8045307/89533529-24718e00-d826-11ea-8a81-3f1c5ce66345.png)
![image](https://user-images.githubusercontent.com/8045307/89533550-29ced880-d826-11ea-9888-39d4c79e5770.png)

It looks like that sharding-jdbc with table partition are not as good as just mysql with single table, whar can I do to improve performance?

**Comment by tristaZero** [comment]
@lishijun121910 Thanks for your test report.

1. Could you provide these test SQLs?
2. What's the difference between the second one and the third one?

**Comment by lishijun121910** [comment]
> @lishijun121910 Thanks for your test report. Let's give it a discussion.
> 
> 1. Could you provide these test SQLs?
> 2. What's the difference between the second one and the third one?
> 3. Which tool did you use for testing?

1. sql is 
    select
    <include refid="Base_Column_List" />
    from T_MERCHANT
    where INST_ID = #{inst_id,jdbcType=DECIMAL}
    and MCC_ID = #{mcc_id,jdbcType=DECIMAL}
    and MCHNT_ID = #{mchnt_id,jdbcType=VARCHAR}

2. the second is sharding-jdbc with 1 table(30000000rows), the third is sharding-jdbc with 64 table(1 into 64, 500000 rows).
 
3. I am using springboot+shardingjdbc+mybatis application for testing.


Our team discussed about the testing result today,  it is reasonable and as expected.

**Comment by tristaZero** [comment]
Hi @lishijun121910 
I like your understandable answers, thanks. :) Actually, we are working on the same tests. See #6536 

1. Why do not you try some other SQLs like `select count(*) from table where xxx` or `select xxx from table where id > xx and id < xx`?
2. Could you look at #6536 and write about your thoughts here?
3. Why do you think these tests are as expected? Do you mean your test method is appropriate?

**Comment by lishijun121910** [comment]
> 3\. Why do you think these tests are as expected? You mean your test method is reasonable?

1. Our bussiness is mostly like selecting one record in one sql. We will do some test like what you recommended  if we need.
2. We have done a group of testcases of sharding-proxy and sharding-jdbc(4.1.0) compare to mysql(5.7.31). Our hardware and software enviroument is  just simulation of our product enviroment , so I am afraid can not be a standard performance to consider.
4. We think this test result is as expected, without sharding any databases or tables, sharding-jdbc's natural performacne overhead is less than 10%, sharding-proxy's natural performance overhead is less than 30%. If the hardware environment including disk and memory configuration is unchanged, the single database  sharding-table can acctually not improve the performance, and the performance bottleneck of our test results eventually falls on the disk I/O. So sharding-databases will be our solution.

**Comment by kimmking** [comment]
@lishijun121910 is there something moving on and feedback the test results?

**Comment by tristaZero** [comment]
Hi @lishijun121910 

Sorry for coming late,
Thanks for the performance test on a single database scenario, which provided us a valuable reference. 
My suggestion is to create multiple shardings rather than one single database to lighten the load from applications. A single database has less value for internet apps with extensive data volume.

Welcome your updating. Whereas, please close this one.

Thanks,
Trista

**Comment by kimmking** [comment]
After a long time silence, we should close this issue now.
Anything further more NEED TO open a new issue to track it.

**Comment by tuohai666** [comment]
@lishijun121910 

I have improved the performance recently, please refer to #9616 and #9826 .

The TPS is proved to be increased by 12% and 15% respectively by sysbench test result of ShardingSphere-Proxy. The CPU load also decreased significantly.

It's expected that the ShardingSphere-JDBC can get the similiar result.

These two PRs will be included in the next release, may be 5.0.0-RC1.
