### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/shardingsphere#6680]
https://github.com/apache/shardingsphere/blob/acc64bdf0b9b994ca465c2a63a06e6db8221935c/shardingsphere-infra/shardingsphere-infra-merge/src/main/java/org/apache/shardingsphere/infra/merge/result/impl/stream/StreamMergedResult.java#L61

The program can potentially fail to release a system resource.

**Comment by tristaZero** [comment]
Hi @QiAnXinCodeSafe Thanks for your attention.

Could you give more explanation for this issue?
Since this result will return to users, could you confirm whether it will be closed after using?

**Comment by terrymanu** [comment]
Closed because of no response anymore
