### ISSUE TITLE
Merge result of DDL is not accurate

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#6684]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute the following SQL
```
drop table t_order
```
return **false** if one of the actual SQLs fails.

### Actual behavior

Execute the following SQL
```
drop table t_order
```
return **true** if one of the actual SQLs fails.

### Reason analyze (If you can)

Merge result is determined by one of the result of all actual SQLs.

**Comment by tuohai666** [comment]
The wrong result can not be reproduced by several test cases, more information is needed.

**Comment by lidonghai11** [comment]
Merge result of DDL is  accurate.  This issue does not exist
