### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/shardingsphere#6686]
https://github.com/apache/shardingsphere/blob/dc536c1fa19d5e4f98c50457d135254dd60d59eb/shardingsphere-scaling/shardingsphere-scaling-core/src/main/java/org/apache/shardingsphere/scaling/core/execute/executor/channel/MemoryChannel.java#L34

This field is never used

**Comment by Lucas-307** [comment]
Could you please help us fixed it.
