### ISSUE TITLE
chinese databases DM dameng 

### ISSUE THREAD

**Issue by gjf001** [apache/shardingsphere#6692]
shardingSphere is not compatible with Dameng database, the same configuration method, mysql can, but Dameng database is not, Dameng database is fully compatible with oracle, I use Springboot+mybatisplus, mybatisplus can configure the schema, the project can start normally, Queries are fine, but Data Sharding does not help

**Comment by kimmking** [comment]
ShardingSphere doesn't support Dameng now, and has no plan for it.
If you are insterested in this case, could you make a pr to achieve it?
