### ISSUE TITLE
Optimize test cases of DataSourceConfiguration.equals and hashCode

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6706]
The current test cases are mix equals and not equals, please split them.

- [ ] Split DataSourceConfigurationTest.assertEquals to assertEquals and assertNotEquals
- [ ] Split DataSourceConfigurationTest.assertHashCode to assertSameHashCode and assertDifferentHashCode
- [ ] Add more test case for Equals
  - [ ] assert for equals to null object
  - [ ] assert for equals to class not same

**Comment by jian365066744** [comment]
please assign to me

**Comment by GeniusQ** [comment]
让我来 ^_^

**Comment by terrymanu** [comment]
@jian365066744 Thank you, assigned, I add to more sub tasks, please have a look

**Comment by jian365066744** [comment]
thanks,I am outside, I will finish the task later.

**Comment by zhenpuwang** [comment]
Give me a chance

**Comment by jian365066744** [comment]
liang,I have finish the task.but I didn't find the issue #6706 is not exist,the DataSourceConfigurationTest is the issue #6718
![QQ截图20200810223903](https://user-images.githubusercontent.com/35258103/89795148-9fa2af00-db5a-11ea-87ae-81c3e3450b9e.png)

**Comment by terrymanu** [comment]
@ jian365066744 What's mean the issue #6706 is not exist?
You are in the issue #6706 now.

**Comment by taojintianxia** [comment]
> liang,I have finish the task.but I find the issue #6706 is not exist,the DataSourceConfigurationTest is the issue #6718,please tell me how to do.
> ![QQ截图20200810223903](https://user-images.githubusercontent.com/35258103/89795148-9fa2af00-db5a-11ea-87ae-81c3e3450b9e.png)

hi , there

**Comment by jian365066744** [comment]
thinks your reply and notice about how to commit the issues,I will do right in next time.thinks again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 中午1:37
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Optimize test cases of DataSourceConfiguration.equals and hashCode (#6706)





  
liang,I have finish the task.but I find the issue #6706 is not exist,the DataSourceConfigurationTest is the issue #6718,please tell me how to do.
 
  
hi , there
