### ISSUE TITLE
Optimize DataSourceMetasTest.getAllInstanceDataSourceNames

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6714]
- [x] Add more assertion details for `assertGetAllInstanceDataSourceNamesForShardingRule`, assertNotNull is not enough
- [ ] Add a new assertion for not MemorizedDataSourceMetaData branch

**Comment by harvies** [comment]
Can you explain the second article in detail.

**Comment by terrymanu** [comment]
![image](https://user-images.githubusercontent.com/5516298/89714803-faf66500-d9d3-11ea-871e-116fcf1ec459.png)
This branch is not test yet. We need to add the test case

**Comment by harvies** [comment]
> ![image](https://user-images.githubusercontent.com/5516298/89714803-faf66500-d9d3-11ea-871e-116fcf1ec459.png)
> This branch is not test yet. We need to add the test case
The first two methods of the class DataSourceMetasTest have verified this branch.
