### ISSUE TITLE
The idea configuration imported through the official website seems to be wrong.

### ISSUE THREAD

**Issue by harvies** [apache/shardingsphere#6741]
## Question

The idea configuration imported through the official website seems to be wrong. Many changes occurred after formatting. The IDEA version is mac 2020.1.1.

![image](https://user-images.githubusercontent.com/16585330/89735122-d7462400-da92-11ea-9947-b777ad273d7a.png)
![image](https://user-images.githubusercontent.com/16585330/89735147-0fe5fd80-da93-11ea-9823-dcdfcd4e90e5.png)

**Comment by terrymanu** [comment]
The changes is very strong, why merge 2 lines in same line?

**Comment by harvies** [comment]
> The changes is very strong, why merge 2 lines in same line?

![image](https://user-images.githubusercontent.com/16585330/89736125-ca78fe80-da99-11ea-9397-174e213cba13.png)
After importing the settings file (https://shardingsphere.apache.org/community/data/shardingsphere-settings.jar), the formatting is like this.

**Comment by tristaZero** [comment]
@harvies @terrymanu This issue has been fixed already?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
