### ISSUE TITLE
SS-Scaling integrate SS-ElasticJob and SS-JDBC

### ISSUE THREAD

**Issue by Lucas-307** [apache/shardingsphere#6743]
SS-Scaling connect SS-ElasticJob
- definition an OneOff type of ElasticJob
- monitoring Zk for execute config
- execute ElasticJob
	- start
	- update status
	- stop

SS-Scaling connect SS-JDBC
- definition a SPI
- write a ServiceLoader
- write an ScalingJob implement

SS-Scaling independent Main
- Main() function to start a job

**Comment by kimmking** [comment]
Hi, @Lucas-307 , I think we can't understand this issue... 😭
