### ISSUE TITLE
Add test cases for SQLRewriteContext

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6746]
- [x] Add test case for new SQLRewriteContext() with InsertStatementContext
- [x] Add test case for new SQLRewriteContext() with not InsertStatementContext
- [x] Add test case for SQLRewriteContext.generateSQLTokens()

**Comment by taojintianxia** [comment]
assign to me . but I need your tips

**Comment by taojintianxia** [comment]
@terrymanu may I use mock SchemaMetaData / SQLStatementContext for testing SQLRewriteContext ?
