### ISSUE TITLE
SHOW FULL COLUMNS get wrong

### ISSUE THREAD

**Issue by duanzonglong** [apache/shardingsphere#6759]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
config-wms.yaml:
shardingRule:
  defaultDatabaseStrategy:
    standard:
      shardingColumn: tenant_id
      preciseAlgorithmClassName: com.hrsoft.sharding.strategy.core.DatabaseStrategy
  tables:
    databasechangeloglock:
      actualDataNodes: wms_base.databasechangeloglock
      databaseStrategy:
        none:
      tableStrategy:
        none:
    databasechangelog:
      actualDataNodes: wms_base.databasechangelog
      databaseStrategy:
        none:
      tableStrategy:
        none:

### Actual behavior
Table 'wms_sd1.databasechangelog' doesn't exist
some times its ok,so i think the "DatabaseStrategy" got wrong

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
springliquibase:
SHOW FULL COLUMNS FROM `databasechangelog` FROM `sharding_wms` LIKE '%'

**Comment by tuohai666** [comment]
Is `SHOW FULL COLUMNS FROM sharding_wms LIKE '%'` works well?

**Comment by tuohai666** [comment]
I'd like to add this issue to `Usability test of ShardingSphere-Proxy` (#6690)

**Comment by duanzonglong** [comment]
the full sql is : SHOW FULL COLUMNS FROM `databasechangelog` FROM `sharding_wms` LIKE '%'

**Comment by duanzonglong** [comment]
some times its ok,but some times got wrong.

**Comment by kimmking** [comment]
the correct sql is:
> SHOW FULL COLUMNS FROM sharding_wms.databasechangelog LIKE '%'

**Comment by tuohai666** [comment]
I think we should not add 'wms_sd1.' into actual SQL. @tristaZero , can you have a look?

**Comment by tristaZero** [comment]
Hi @duanzonglong @tuohai666 

First, let me collect your thoughts,
 `sharding_wms` is a logic DB name, and `wms_sd1` is an actual one? We expected that this SQL is supposed to rewrite. However, we got an incorrect rewritten SQL, right?

**Comment by tuohai666** [comment]
@Lucas-307 subscribed.

**Comment by kimmking** [comment]
any update

**Comment by duanzonglong** [comment]
config-wms.yaml:

schemaName: sharding_wms

dataSources:
  wms_base:
  -----
  wms_sd0:
  -----
  wms_sd1:
  -----
  wms_sd2:

shardingRule:
  defaultDatabaseStrategy:
    standard:
      shardingColumn: tenant_id
      preciseAlgorithmClassName: com.hrsoft.sharding.strategy.core.DatabaseStrategy
  broadcastTables:
    - ds_changelog,ds_changelog_lock
  defaultDataSourceName: wms_base
  tables:
    ds_changelog:
      actualDataNodes: wms_base.ds_changelog
      databaseStrategy:
        none:
      tableStrategy:
        none:
    ds_changelog_lock:
      actualDataNodes: wms_base.ds_changelog_lock
      databaseStrategy:
        none:
      tableStrategy:
        none:
   more....
  bindingTables:
    - xxxxx
  defaultTableStrategy:
    none:  

the actual sql is:
SHOW FULL COLUMNS FROM databasechangelog FROM sharding_wms LIKE '%'
it's create bymysql-connector-java-5.1.46.jar
![image](https://user-images.githubusercontent.com/15925454/93954606-a12ddc80-fd80-11ea-8598-8c2a5320d4b6.png)

**Comment by kimmking** [comment]
what's wrong with  mysql-connector-java-5.1.46.jar ?

**Comment by duanzonglong** [comment]
> what's wrong with mysql-connector-java-5.1.46.jar ?

I only want ds_changelog route to wms_base,but sometimes it's wrong,please see image.

**Comment by kimmking** [comment]
As this issue have no more infomation for a long time, we close it now.

**Comment by duanzonglong** [comment]
Hi,this is the whole yaml.

`
schemaName: sharding_wms

dataSources:
  wms_base: 
    url: jdbc:mysql://172.172.172.213:3360/scms_wms?useUnicode=true&characterEncoding=UTF8
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65
  wms_sd0:
    url: jdbc:mysql://172.172.172.213:3360/wms_sd0?useUnicode=true&characterEncoding=UTF8
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65
  wms_sd1:
    url: jdbc:mysql://172.172.172.213:3360/wms_sd1?useUnicode=true&characterEncoding=UTF8
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65    

shardingRule:
  defaultDatabaseStrategy:
    standard:
      shardingColumn: tenant_id
      preciseAlgorithmClassName: com.hrsoft.sharding.strategy.core.DatabaseStrategy
  tables:
    ds_changelog_lock:
      actualDataNodes: wms_base.ds_changelog_lock
      databaseStrategy:
        none:
      tableStrategy:
        none:
    ds_changelog:
      actualDataNodes: wms_base.ds_changelog
      databaseStrategy:
        none:
      tableStrategy:
        none:      
  bindingTables:
    - ds_changelog_lock,ds_changelog
  defaultTableStrategy:
    none:
`

**Comment by duanzonglong** [comment]
Hi,I have solved this problem.
the config is:
defaultDataSourceName: wms_base
and 
liquibase.setLiquibaseSchema("wms_base");
