### ISSUE TITLE
Multiple routing policies can be configured for different operations in a single table支持单表不同操作配置多个路由策略

### ISSUE THREAD

**Issue by za1275952454** [apache/shardingsphere#6776]
sharding:
      default-database-strategy:
        hint:
          algorithm-class-name: com.cujia.logistics.task.algorithm.TaskHintShardingAlgorithm
      tables:
        order_track:
          actual-data-nodes: ds.order_track_$->{0..1}
          table-strategy:
#            hint:
#              algorithm-class-name: com.cujia.logistics.task.algorithm.TaskHintShardingAlgorithm
            inline:
              sharding-column: id
              algorithm-expression: order_track_$->{Math.abs(String.valueOf(id).hashCode()) % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              worker:
                id: 123
      binding-tables: order_track

I hope now that the_ In track query, the mandatory routing strategy is adopted, and the standard allocation strategy is added and modified according to the fragmentation rules. Thank you!

我现在希望对order_track查询时走强制路由策略，新增修改根据分片规则走标准分配策略。望解答谢谢！

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
