### ISSUE TITLE
Can multiple routing policies be configured for different operations in a single table？

### ISSUE THREAD

**Issue by za1275952454** [apache/shardingsphere#6778]
I want to tell order_ In track query, the mandatory routing strategy is adopted, and the standard allocation strategy is added and modified according to the fragmentation rules. Thank you!

**Comment by tristaZero** [comment]
@za1275952454 Sorry, one route strategy for one single table. You can consider implementing a user-defined sharding algorithm to cover all the routing cases by yourself.
