### ISSUE TITLE
Add test cases for SQLToken's impl of toString method

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6782]
- [ ] Add test case for RemoveToken.toString()
- [ ] Add test case for SubstitutableColumnNameToken.toString()
- [ ] Add test case for UseDefaultInsertColumnsToken.toString()

Please ref `InsertColumnsTokenTest`

**Comment by jian365066744** [comment]
please assign to me

**Comment by 804533125** [comment]
please assign to me,Thanks!

**Comment by wanglongzhen** [comment]
please assign to me

**Comment by 804533125** [comment]
Thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liang Zhang"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 下午2:35
收件人: "apache/shardingsphere"<shardingsphere@noreply.github.com&gt;; 
抄送: "郑建峰"<804533125@qq.com&gt;; "Assign"<assign@noreply.github.com&gt;; 
主题: Re: [apache/shardingsphere] Add test cases for SQLToken&#39;s impl of toString method (#6782)





 
Assigned #6782 to @804533125.

**Comment by jacksparrow414** [comment]
- [x] Add test case for RemoveToken.toString()
- [x] Add test case for SubstitutableColumnNameToken.toString()
- [x] Add test case for UseDefaultInsertColumnsToken.toString()
