### ISSUE TITLE
Load table meta data when it is used

### ISSUE THREAD

**Issue by Simbafa** [apache/shardingsphere#6803]
### Is your feature request related to a problem?
No
### Describe the feature you would like.
The current implementation is loading all table meta data at once.
If there are many tables in a database, time cost is high. (150 tables cost 25+ seconds)
But maybe only some of the tables will be accessed in the following operations.
Is it possible to load a table meta data only when it is used?

**Comment by hand515** [comment]
same with #6212

**Comment by tristaZero** [comment]
@hand515 Thanks for your answer. :)
@Simbafa Thanks for your attention, I will consider focusing on this enhancement after I finish #6466 .
We will include #6212 in our next release. 

Trista
