### ISSUE TITLE
Springboot integrates shardingjdbc only sub-library uses hint strategy configuration problem

### ISSUE THREAD

**Issue by zundaren** [apache/shardingsphere#6805]
I just want to sub-database and use hint strategy, but the configuration file needs to configure sub-table, which is not logical
---------------------------------------------------------------------------------------------------------

spring.shardingsphere.sharding.tables.item.actual-data-nodes=ds${0..1}.item
spring.shardingsphere.sharding.tables.item.table-strategy.hint.algorithm-class-name=com.shardingdemo.config.HintShardingKeyAlgorithm
spring.shardingsphere.sharding.tables.item.database-strategy.hint.algorithm-class-name=com.shardingdemo.config.HintShardingKeyAlgorithm
--------------------------------------------------------------------------------------------------------

For example, I use the item table to insert, and the hint strategy uses ShardingStandardRoutingEngine, but I want to use a table that is not configured in the configuration file, such as the user table, to route to ShardingUnicastRoutingEngine. That is to say, there are hundreds of tables in a database on my side, and I want to configure Only a few hundred tables configuration can use the hint mode, which is completely inappropriate

**Comment by Lucas-307** [comment]
Sorry, Your description is too difficult to understand and used some of your own vocabulary. Please revise it and reply again.

**Comment by tristaZero** [comment]
Hi @zundaren If the version you used is prior to `4.1.1` (including), can you consider `defaultDataSource` for non-sharding tables?
`Our master branch` has an improvement for your scenario. Please look forward to our next release.

Thanks,
Trista

**Comment by terrymanu** [comment]
Invalid description of `sub-library`.
Closed because of no response anymore.
