### ISSUE TITLE
Does sharding proxy support query add custom column?

### ISSUE THREAD

**Issue by cobstergo** [apache/shardingsphere#6814]
Does sharding proxy support query add custom column？
like this , for example
SELECT id,(SELECT count(0) FROM table_budev) as devCount FROM table_ticket ORDER BY id DESC limit 10;
in mysql:
![image](https://user-images.githubusercontent.com/11827280/90092452-8d439380-dd5b-11ea-8299-7c772aeed8fc.png)
in sharding proxy:
![image](https://user-images.githubusercontent.com/11827280/90092471-9df40980-dd5b-11ea-861b-51a52466c135.png)
sharding proxy version is 4.1.1

**Comment by tristaZero** [comment]
@cobstergo Hi
4.1.1 does not have better support for `subquery`, I suggest you try the `master branch`.
Besides, it is required that `table_budev ` and `table_ticket ` have the same sharding algorithm.

**Comment by cobstergo** [comment]
@tristaZero got it, thanks for you reply.
