### ISSUE TITLE
Add test cases for rule builder

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6825]
Add test cases for rule builder, please reference `EncryptRuleBuilder`:

- [x] Add test case for MasterSlaveRuleBuilder
- [x] Add test case for ReplicaRuleBuilder
- [x] Add test case for ShadowRuleBuilder
- [x] Add test case for ShardingRuleBuilder

Add test cases for algorithm provided rule builder, please reference `AlgorithmProvidedEncryptRuleBuilderTest`:

- [ ] Add test case for AlgorithmProvidedMasterSlaveRuleBuilder
- [ ] Add test case for AlgorithmProvidedShardingRuleBuilder

**Comment by gzdzss** [comment]
Assign it to me, thanks
