### ISSUE TITLE
shardingjdbc can close sharing? I only use write-read split

### ISSUE THREAD

**Issue by zhangzl0119** [apache/shardingsphere#6838]
shardingjdbc can close sharing? I only use write-read split. Because some sql not work well.

**Comment by Lucas-307** [comment]
@zhangzl0119 Yes, you can config master-slave only.
See: [application-local-zookeeper-master-slave.properties](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/orchestration-example/orchestration-spring-boot-example/src/main/resources/application-local-zookeeper-master-slave.properties)

**Comment by zhangzl0119** [comment]
No, I only config master-slave only. But has sharding function，lead to some sql not support, such as order by. So I not want to sharding, shardingjdbc has some config to close sharding?

**Comment by Lucas-307** [comment]
@zhangzl0119 Sorry, Current Version don't support . But we will consider what you suggest.

**Comment by Lucas-307** [comment]
@zhangzl0119 We discussed it internally, Sorry, we can't support that funciton. But we will enhance our sql parser function in the futrue to make sure all valid sql can execute.

**Comment by tristaZero** [comment]
@zhangzl0119 If there is no SQL parsing, how can shardingSphere know your SQL is to select or update?

**Comment by zhangzl0119** [comment]
@tristaZero You can parse SQL to know select or update. Howerver, some sql not support well, such as order by. I hope  when I only use write and read split，my sql can work well compare to original sql, I don't need to change SQL.

**Comment by zhangzl0119** [comment]
@Lucas-307 OK，SharindSphere will be better.

**Comment by terrymanu** [comment]
What's mean `close sharing`
Maybe we need to change the title more clear before discuss.

**Comment by tristaZero** [comment]
> @tristaZero You can parse SQL to know select or update. Howerver, some sql not support well, such as order by. I hope when I only use write and read split，my sql can work well compare to original sql, I don't need to change SQL.

I see, that is why we took a lot of effort on Sharding parser. BTW, the master branch has more satisfying support for many complex SQL parsing. Please be patient for our next release. 

Thanks,
Trista

**Comment by kimmking** [comment]
There will be some side-effects without parsing in read/write-split case.

**Comment by tristaZero** [comment]
@zhangzl0119 Hi so do you think this issue is possible to be closed?
