### ISSUE TITLE
how to run spirng-boot.2.3.2.RELEASE with sharding-jdbc-spring-boot-starter.4.1.1

### ISSUE THREAD

**Issue by sim-wangyan** [apache/shardingsphere#6840]
spring-boot.2.2.9.RELEASE no problem

**Comment by Lucas-307** [comment]
@sim-wangyan Hi, Please show us more detail. And what problem did you meet.

**Comment by sim-wangyan** [comment]
运行到JdbcTemplateConfiguration就卡死了，springboot 2.3.x都有这现象，应该是springboot 的坑


------------------ Original ------------------

**Comment by sim-wangyan** [comment]
springboot2.3.x, 现在整合了jdbcTemplate和shardingshpere的框架或应用，改成在监听里注入jdbcTemplate就OK



发自我的iPhone


------------------ Original ------------------

**Comment by Lucas-307** [comment]
@sim-wangyan **For English only**, Thank you.

**Comment by szlzhm** [comment]
可否分享下怎样使用的吗，我这里总是失败。我用alibaba spring cloud 2.2.3

**Comment by sim-wangyan** [comment]
maybe any db framework should set the&nbsp; datasource or jdbcTemplate&nbsp; at the child class of ApplicationListener<ApplicationStartedEvent&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 上午9:10
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"风之狼"<8966188@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] how to run spirng-boot.2.3.2.RELEASE with sharding-jdbc-spring-boot-starter.4.1.1 (#6840)





 
可否分享下怎样使用的吗，我这里总是失败。我用alibaba spring cloud 2.2.3
