### ISSUE TITLE
Does ShardingSphere not support REQUIRES_NEW？

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#6841]
Servicea.methoda has a transaction level of REQUIRED, and serviceb.methodB has a transaction level of REQUIRES_NEW.
Servicea.methoda calls serviceb.methodB .Serviceb.methodb throws an exception.
Servicea.methoda captures .
but  Methoda cannot execute correctly。
org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
why？
It should be if Serviceb.methodB fails to roll back,
If the exception he throws is caught by Servicea.methoda, the servicea.methoda transaction may still commit.

ShardingSphere  4.0.1  mysql5.6

**Comment by Lucas-307** [comment]
HI @65725738 , As you see, this Exception throw from springframework. So, I think it's springframework don't support.
`org.springframework.transaction.UnexpectedRollbackException`
