### ISSUE TITLE
.net core conection problem to SHARDINGSPHERE-PROXY when using MySqlConnector "1Unsupported command: [COM_RESET_CONNECTION]"

### ISSUE THREAD

**Issue by clayboby** [apache/shardingsphere#6861]
## Bug Report

**For Chinese Or English  only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-proxy
### Expected behavior
first and second connection opened successfully
### Actual behavior
When I User MySqlConnector(.net standart2.0) instead of Mysql.Data(From oracle)  and try to conect to proxy at second time. It happened as below.(first try was success, close and open again will throw the error)
I can only use MySqlConnector beacuse of Pomelo.Entityframework.Code，and it excute sql in real async mode(oracle's always in sync mode).
I check the source code, and find the error stacktrace was in ServerSession.cs 507th line.
### Reason analyze (If you can)
It work well when I use mysql 8.0.20 directly. I suppose that the proxy does not support this command. which use in MySqlConnector SDK to get better performance
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
VS2019
Create a Cosole project
Install MySqlConnector Nuget package
Create a Mysqlconnection. open once and close. then open again, you will get this error
### Example codes for reproduce this issue (such as a github link).
![image](https://user-images.githubusercontent.com/69718954/90312251-7b1d4d00-df35-11ea-88e9-96b534a6520f.png)
https://github.com/mysql-net/MySqlConnector ServerSession.cs 507 whent it try TryResetConnectionAsync
![image](https://user-images.githubusercontent.com/69718954/90312466-4dd19e80-df37-11ea-998a-b0fa45ffc3d9.png)
![image](https://user-images.githubusercontent.com/69718954/90312502-8c675900-df37-11ea-8d6d-fd9d4ab36f14.png)

Please, .net also need your help

**Comment by kimmking** [comment]
@clayboby 
Does the test case work well when directly connect to mysql?
> Create a Mysqlconnection. open once and close. then open again, you will get this error

**Comment by clayboby** [comment]
@kimmking<mailto:notifications@github.com>
Yes. It work well with mysql 8.0.20

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: kimmking<mailto:notifications@github.com>
发送时间: 2020年8月25日 11:41
收件人: apache/shardingsphere<mailto:shardingsphere@noreply.github.com>
抄送: clayboby<mailto:clayboby@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [apache/shardingsphere] .net core conection problem to SHARDINGSPHERE-PROXY when using MySqlConnector "1Unsupported command: [COM_RESET_CONNECTION]" (#6861)


@clayboby<https://github.com/clayboby>
Does the test case work well when directly connect to mysql?

Create a Mysqlconnection. open once and close. then open again, you will get this error

―

**Comment by tuohai666** [comment]
@clayboby Can you use wireshark to capture the process?

**Comment by TOP-LH** [comment]
> **只接受中文或英文**，不接受其他

现在解决了吗

**Comment by TOP-LH** [comment]
> @clayboby你能用wireshark来捕捉这个过程吗？

现在解决了吗

**Comment by TOP-LH** [comment]
> @clayboby你能用wireshark来捕捉这个过程吗？

我看MYSQL官方说是

**Comment by TeslaCN** [comment]
Maybe .net driver reuses the TCP connection.

**Comment by TOP-LH** [comment]
> Maybe .net driver reuses the TCP connection.

What can I do for you?

**Comment by TeslaCN** [comment]
MySqlConnector will use `COM_RESET_CONNECTON` (higher server version) or `COM_CHANGE_USER` (lower server version) to reset state of connection.

https://github.com/mysql-net/MySqlConnector/blob/c3a362e9f326c8b7773be389ec8496e221434641/src/MySqlConnector/Core/ServerSession.cs#L610-L669

**Comment by TeslaCN** [comment]
> > Maybe .net driver reuses the TCP connection.
> 
> What can I do for you?

I'd appreciate that if you could help us reproduce this in Linux. I haven't got a Windows environment.

**Comment by TOP-LH** [comment]
> > > Maybe .net driver reuses the TCP connection.
> > 
> > 
> > What can I do for you?
> 
> I'd appreciate that if you could help us reproduce this in Linux. I haven't got a Windows environment.

I'm sorry, I can't answer this question, this problem is .net core development colleagues to my feedback, according to him there is a paging interface need to query the total number of entries and the current page of data, the total number of entries can be queried successfully, the current page of SQL is not able to query
The master MySQL report is: 5.7.22-log
The slave MySQL report is: 5.7.40-log
-------------------------------------------------------------------------------------->>
不好意思, 这个我不太好回答, 这个问题是.net core的开发同事向我反馈的, 据他所说是有一个分页接口需要查询总条数和当前页的数据, 总条数是可以查询成功的, 当前页的SQL是无法查询的
主库MySQL报表是: 5.7.22-log
从库MySQL报表是: 5.7.40-log

**Comment by TOP-LH** [comment]
> > > > Maybe .net driver reuses the TCP connection.
> > > 
> > > 
> > > What can I do for you?
> > 
> > 
> > I'd appreciate that if you could help us reproduce this in Linux. I haven't got a Windows environment.
> 
> I'm sorry, I can't answer this question, this problem is .net core development colleagues to my feedback, according to him there is a paging interface need to query the total number of entries and the current page of data, the total number of entries can be queried successfully, the current page of SQL is not able to query The master MySQL report is: 5.7.22-log The slave MySQL report is: 5.7.40-log -------------------------------------------------------------------------------------->> 不好意思, 这个我不太好回答, 这个问题是.net core的开发同事向我反馈的, 据他所说是有一个分页接口需要查询总条数和当前页的数据, 总条数是可以查询成功的, 当前页的SQL是无法查询的 主库MySQL报表是: 5.7.22-log 从库MySQL报表是: 5.7.40-log

Java目前没碰到问题

**Comment by bgrainger** [comment]
The issue is that ShardingSphere claims to be MySQL 5.7 (or later) in the Initial Handshake packet, but doesn't support MySQL 5.7 protocol features such as COM_RESET_CONNECTION.

https://github.com/apache/shardingsphere/blob/f6a202bfde51b00dcfb02453e32697fc3c736324/proxy/frontend/mysql/src/test/java/org/apache/shardingsphere/proxy/frontend/mysql/command/MySQLCommandPacketFactoryTest.java#L227-L230

If ShardingSphere only supports the MySQL 5.6 protocol, it shouldn't present a MySQL 5.7 version number.

**Comment by TOP-LH** [comment]
@TeslaCN So do we need to wait for the next version? When will the next version be available?

**Comment by TeslaCN** [comment]
> @TeslaCN So do we need to wait for the next version? When will the next version be available?

We may release next version in 2 weeks. You may build ShardingSphere-Proxy from source codes or wait for next nightly build. https://github.com/apache/shardingsphere/pkgs/container/shardingsphere-proxy

**Comment by TOP-LH** [comment]
> > @TeslaCN So do we need to wait for the next version? When will the next version be available?
> 
> We may release next version in 2 weeks. You may build ShardingSphere-Proxy from source codes or wait for next nightly build. https://github.com/apache/shardingsphere/pkgs/container/shardingsphere-proxy

https://github.com/apache/shardingsphere/releases/tag/5.3.0 这个版本我可以使用吗?

**Comment by TeslaCN** [comment]
> > > @TeslaCN So do we need to wait for the next version? When will the next version be available?
> > 
> > 
> > We may release next version in 2 weeks. You may build ShardingSphere-Proxy from source codes or wait for next nightly build. https://github.com/apache/shardingsphere/pkgs/container/shardingsphere-proxy
> 
> https://github.com/apache/shardingsphere/releases/tag/5.3.0 这个版本我可以使用吗?

Of course. The release candidates could be found here: https://lists.apache.org/thread/94lgj7mwn2srnqbdwkn2p2phryfdq3fj
