### ISSUE TITLE
Force specifying hint when using hint sharding strategy configuration

### ISSUE THREAD

**Issue by satheesh-moorthy** [apache/shardingsphere#6898]
I am using sharding jdbc version 4.1.1

I have a table employee and it is sharded between 3 databases. It is represent by 3 datasources.

I am using HintShardingStrategyConfiguration as database sharding strategy. It is only database sharding.

Everything works fine when I set hint, but if hint is not set and a query is performed then all the 3 datasources are queried. I want to control this behaviour where if hint is not set then it should either throw exception or fallback to default datasource.

Is this already available or not supported.

Can you please help

My Java configuration Code below

@Bean
    public DataSource getDataSource() throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        
        shardingRuleConfig.setDefaultDataSourceName("ds_global");
        
        shardingRuleConfig.getTableRuleConfigs().add(getEmployeeeTableRuleConfiguration());
        
        shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new HintShardingStrategyConfiguration(new CustomHintShardingAlgo()));
        
        shardingRuleConfig.setMasterSlaveRuleConfigs(getMasterSlaveRuleConfigurations());
        
        Properties p = new Properties();
        p.setProperty("sql.show", "true");
        
        return ShardingDataSourceFactory.createDataSource(createDataSourceMap(), shardingRuleConfig, p);
    }
    
    //for sharded tables
    private static TableRuleConfiguration getEmployeeeTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration("employee");
        return result;
    }
    
    
 
    
    private static Map<String, DataSource> createDataSourceMap() {
        Map<String, DataSource> result = new HashMap<>();

        result.put("ds_global_master", DataSourceUtil.createDataSource("global_employee"));
        result.put("ds_global_slave_0", DataSourceUtil.createDataSource("global_employee"));
        result.put("ds_global_slave_1", DataSourceUtil.createDataSource("global_employee"));

        result.put("ds_shard_1_master", DataSourceUtil.createDataSource("employee_directory_1"));
        result.put("ds_shard_1_slave_1", DataSourceUtil.createDataSource("employee_directory_1"));
        result.put("ds_shard_1_slave_2", DataSourceUtil.createDataSource("employee_directory_1"));

        result.put("ds_shard_2_master", DataSourceUtil.createDataSource("employee_directory_2"));
        result.put("ds_shard_2_slave_1", DataSourceUtil.createDataSource("employee_directory_2"));
        result.put("ds_shard_2_slave_2", DataSourceUtil.createDataSource("employee_directory_2"));

        return result;
    }
    
    
    List<MasterSlaveRuleConfiguration> getMasterSlaveRuleConfigurations() {
        MasterSlaveRuleConfiguration masterSlaveRuleConfig1 = new MasterSlaveRuleConfiguration("ds_global", "ds_global_master", Arrays.asList("ds_global_slave_0", "ds_global_slave_1"));
        MasterSlaveRuleConfiguration masterSlaveRuleConfig2 = new MasterSlaveRuleConfiguration("ds_shard_1", "ds_shard_1_master", Arrays.asList("ds_shard_1_slave_1", "ds_shard_1_slave_2"));
        MasterSlaveRuleConfiguration masterSlaveRuleConfig3 = new MasterSlaveRuleConfiguration("ds_shard_2", "ds_shard_2_master", Arrays.asList("ds_shard_2_slave_1", "ds_shard_2_slave_2"));

        return Lists.newArrayList(masterSlaveRuleConfig1, masterSlaveRuleConfig2, masterSlaveRuleConfig3);
    }

**Comment by tristaZero** [comment]
Hi @satheesh-moorthy ,

Thanks for your issue. 

> if hint is not set and a query is performed then all the 3 datasources are queried.

Firstly, suppose you do not set any values to `hintManger`, we can not `filter the target databases or tables` using these values. Therefore what you mentioned will follow.
Secondly, just out of my curiosity, why do you consider using [other sharding strategies](https://shardingsphere.apache.org/document/legacy/4.x/document/en/features/sharding/concept/sharding/) like `Inline` or `Standard`? You do not need to set any values using them. 

Cheers,
Trista

**Comment by satheesh-moorthy** [comment]
Hi @tristaZero 

Thanks a lot for taking your time and clarifying.

Actually the application I am working on is more complex where the sharding column will not be present in SQL and we use separate lookup table to identify the shard based on metadata. 

So we can only use hint strategy and not inline or standard. Using the metadata in the request we will use a lookup table to find the shard and set it in hintmanager.

We have more than 20 shards, and by some programming error if shard is not set in hintmanager before some query is run then all the 20 shards will be queried, which will be not advisable.

So wanted to know if there is any setting to control this behaviour

**Comment by tristaZero** [comment]
Hi @satheesh-moorthy 

If so, I am sorry that currently there is no other better way than setting `hint manager` to route SQLs for this `logic table`. 
Please look at [Hint router](https://github.com/apache/shardingsphere/blob/f34ab740629545c530f26cc29eaf90ea64a8cf19/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-route/src/main/java/org/apache/shardingsphere/sharding/route/engine/type/standard/ShardingStandardRoutingEngine.java#L78)  for more detail.

Best,
Trista

**Comment by satheesh-moorthy** [comment]
Hi @tristaZero 

Thanks for clarifying. Appreciate your help
