### ISSUE TITLE
Unsupported subqueries

### ISSUE THREAD

**Issue by peng-ran** [apache/shardingsphere#6899]
SELECT COUNT(1)
FROM (
	SELECT *
	FROM t_demo o
) as a
I use Hint for table sharding, but this SQL statement is not sharding.
version：4.1.1

**Comment by strongduanmu** [comment]
@peng-ran The 4.x release version does not support `subquery ` very well, please wait for the 5.x release version. Currently, more subquery features are being implemented, please refer to #6497 .

**Comment by peng-ran** [comment]
@strongduanmu Thank you
