### ISSUE TITLE
Ignore the case of the logical table name when get sharding value from Hint

### ISSUE THREAD

**Issue by peng-ran** [apache/shardingsphere#6902]
![image](https://user-images.githubusercontent.com/35087778/90411152-e9047880-e0dd-11ea-9bb7-fc7ab73f112c.png)

Can ignore the case of the logical table name when get sharding value from Hint? Because table name in SQL has uppercase or lowercase.

**Comment by peng-ran** [comment]
![image](https://user-images.githubusercontent.com/35087778/90411925-0ab22f80-e0df-11ea-92ed-15e5751a9240.png)
I have to do it now, otherwise I can't execute it correctly，Which friend has a better way？

**Comment by tristaZero** [comment]
Hi @peng-ran 
I want to know that `HintManger` keeps the `logic table` as the same alphabet case as the user adds, right? Otherwise, does it capitalize or lower the character case?

**Comment by peng-ran** [comment]
The logical table name is derived from the SQL being executed, and the MYSQL table name can then be case-insensitive. Sharding-jdbc cannot execute correctly if the table name in the EXECUTED SQL is uppercase and the table name added in the HintManager is lowercase.
@tristaZero

**Comment by wcsoft** [comment]
@peng-ran

**Comment by wcsoft** [comment]
@peng-ran  could you provide version of Sharding-jdbc related the issue? 
thx a lot.

**Comment by wcsoft** [comment]
@peng-ran 
Logic table should be kept as the same HintManger using, ShardingJDBC does not provide ability to ingore case insensitive for the scenario.
we provide unified approaches as the purpose oriented many kinds of databases such as Orace, MYSQL, H2 etc.

**Comment by peng-ran** [comment]
@wcsoft thanks
