### ISSUE TITLE
Add more test cases for ShardingSpringNamespaceTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6909]
Please finished todo in ShardingSpringNamespaceTest

- [ ] assertModStrategy
- [ ] assertComplexStrategy
- [ ] assertHintStrategy
- [ ] assertIncrementAlgorithm
- [ ] assertDefaultKeyGenerator
- [ ] assertOrderKeyGenerator
- [ ] assertSimpleRule
- [ ] assertComplexRule
- [ ] assertBindingRule
- [ ] assertBroadcastRule
- [ ] assertAutoRule

**Comment by jian365066744** [comment]
please assign to me ,thanks

**Comment by jian365066744** [comment]
liang,when I start run test ,so many package and class  miss,are you sure ShardingSpringNamespaceTest can run ?
![image](https://user-images.githubusercontent.com/35258103/90605825-79070700-e231-11ea-8113-39f1522953ef.png)

**Comment by jacksparrow414** [comment]
@terrymanu @jian365066744 Can we work together to finish it？if we can,assign to me,please :smile:

**Comment by jian365066744** [comment]
@jacksparrow414  I am ok ,left half task to you ,but it seems lack of package and class ,so the ShardingSpringNamespaceTest'case can't run and get error ,you can try run firstly.

**Comment by jacksparrow414** [comment]
> @jacksparrow414 I am ok ,left half task to you ,but it seems lack of package and class ,so the ShardingSpringNamespaceTest'case can't run and get error ,you can try run firstly.

thanks,  I'll finish **the last five**.
 you could run **mvn install** if someclass can't find

**Comment by jacksparrow414** [comment]
- [x] assertSimpleRule
  - [x] assertComplexRule
  - [x] assertBindingRule
  - [x] assertBroadcastRule
  - [x] assertAutoRule
