### ISSUE TITLE
Add test case for shardingsphere-shadow-spring-boot-starter

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6920]
The module `shardingsphere-shadow-spring-boot-starter` is missing test cases.
Please add test case for spring boot starter.

FYI: 
Module: shardingsphere-master-slave-spring-boot-starter
Class: `MasterSlaveSpringBootAlgorithmProviderBeanTest` and `MasterSlaveSpringBootConditionTest`

**Comment by gzdzss** [comment]
assign to me , thanks
