### ISSUE TITLE
The same transaction, the data is inconsistent

### ISSUE THREAD

**Issue by yxb-git** [apache/shardingsphere#6924]
Hello, 
I use sharding-proxy to directly link proxy database. 
In the same transaction, query and update access different databases. 
Example: 
        tx := apiDB.Begin()
	var user TabUser
	tx.Where("id = ?", 1).First(&user)
	tx.Model(&user).Where("id = ?", 1).Updates(map[string]interface{}{"age": 0})
	tx.Commit()
Is there any problem with my approach, 
Thanks

**Comment by tristaZero** [comment]
Hi @yxb-git 
Your comment is insufficient. Please set `sql.show` = true to get the log and configuration.

Thanks,
Trista

**Comment by wcsoft** [comment]
@yxb-git 
We feel sorry that it's hardly to find any clue about ShardingSphere from the code you provide. Could you provide more details such as yaml configuraion, version of ShardingProxy etc.

It's pleasure you can type more information in format like this:

- What's the issue?
- How to reproduce it?
- What's the actural result?
- What's your expectation?
-  What's the version of ShardingSphere
-  Provide the configuration about ShardingSphere if you have.

**Comment by terrymanu** [comment]
Closed because of no response anymore
