### ISSUE TITLE
Add more assertions of MasterSlaveSpringBootStarterTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6926]
Please add more assertions of MasterSlave Rule Configuration

**Comment by jian365066744** [comment]
please assign to me

**Comment by terrymanu** [comment]
@jian365066744 Hi, any update on this issue?

**Comment by jian365066744** [comment]
I have finish it ,but the fork is error, I need fix it ,wait later




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 下午3:13
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Add more assertions of MasterSlaveSpringBootStarterTest (#6926)





 
@jian365066744 Hi, any update on this issue?
