### ISSUE TITLE
Question:Maven repository about shardingsphere-jdbc-core-spring-boot-starter

### ISSUE THREAD

**Issue by 291277058** [apache/shardingsphere#6931]
[shardingsphere4.1.1 doc about spring boot config](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/spring-boot-starter/)

![image](https://user-images.githubusercontent.com/33279488/90608401-2a5b6c00-e235-11ea-9d6e-1230ad14d0fc.png)

I can not find the maven info on the [repository](https://mvnrepository.com/)

Which repository should we use.

**Comment by menghaoranss** [comment]
Please refer to [document for 4.x](https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/usage/sharding/)

**Comment by menghaoranss** [comment]
There is no response, we will close it .
