### ISSUE TITLE
Add rules assertions for SpringBootStarterTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6933]
- [x] Add sharding rule assertion
- [x] Add encrypt rule assertion
- [x] Add master-slave rule configuration in `application-common.properties`
- [x] Add master-slave rule assertion
- [x] Add shadow rule configuration in `application-common.properties`
- [x] Add shadow rule assertion

**Comment by nikita-tyagi** [comment]
Can you please assign this issue to me? Thank you!

**Comment by gzdzss** [comment]
assign to me， thanks
