### ISSUE TITLE
ss-proxy 4.1.1 doesn't support "WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )))"

### ISSUE THREAD

**Issue by zhaopinglu** [apache/shardingsphere#6938]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ss-proxy-4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ss-proxy-4.1.1

### Expected behavior
The following sql runs to success.
SELECT USER, HOST   FROM PERFORMANCE_SCHEMA.accounts WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )));

### Actual behavior
SQL failed with the following error:
Error Code: 10002. 2Unknown exception: [null]

### Reason analyze (If you can)
ss-proxy 4.1.1 doesn't support "WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )))"

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Just run sql as below:
SELECT USER, HOST   FROM PERFORMANCE_SCHEMA.accounts WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )));

### Example codes for reproduce this issue (such as a github link).
Just run sql as below:
SELECT USER, HOST   FROM PERFORMANCE_SCHEMA.accounts WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )));

**Comment by tristaZero** [comment]
@zhaopinglu Hi You mean the SQL below runs well for MySQL but badly for ShardingProxy?

> SELECT USER, HOST FROM PERFORMANCE_SCHEMA.accounts WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )));

How about the following one? @jingshanglu Do you think it can work fine in our `master branch`?
> SELECT USER, HOST FROM PERFORMANCE_SCHEMA.accounts WHERE ( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' ));

**Comment by zhaopinglu** [comment]
> @zhaopinglu Hi You mean the SQL below runs well for MySQL but badly for ShardingProxy?
> 
> > SELECT USER, HOST FROM PERFORMANCE_SCHEMA.accounts WHERE (( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' )));
> 
> How about the following one? @jingshanglu Do you think it can work fine in our `master branch`?
> 
> > SELECT USER, HOST FROM PERFORMANCE_SCHEMA.accounts WHERE ( USER, HOST ) IN (( 'root', 'localhost' ),( '', '' ));

Yes. Exactly. 
Both 2 SQLs run well on MySQL (5.7.31) directly, but run to fail on ss-proxy 4.1.1

BTW, is there a guide described how to build ss-proxy from master branch? If yes, I'd like to test it.

**Comment by strongduanmu** [comment]
@zhaopinglu You can refer to this [document](https://github.com/apache/shardingsphere/blob/master/README_ZH.md#%E5%A6%82%E4%BD%95%E6%9E%84%E5%BB%BA).

**Comment by jingshanglu** [comment]
@zhaopinglu This involves the definition of statement, and  is being discussed.

**Comment by zhaopinglu** [comment]
@tristaZero @jingshanglu , Just built ss-proxy 5.0.0 RC1 from master branch and tested the sql. The result is same. The SQL is not supported.

**Comment by zhaopinglu** [comment]
Btw, Another issue in ss-proxy 5.0.0 RC1:
It doesn't support "select current_user();" . But I didn't see this issue in ss-proxy 4.1.1. 
So maybe ss-proxy 5.0.0 RC1 has a regression issue for supporting "select current_user();".

**Comment by zhaopinglu** [comment]
Hi, any progress?

**Comment by tristaZero** [comment]
@zhaopinglu 

First, this issue is in the process and not an easy one. Please be patient and watch this issue. If there is any fixed PR, you will see the updatings here.
Second, I suggest you raize another issue for [your new question](https://github.com/apache/shardingsphere/issues/6938#issuecomment-678054011).
One issue for one specific discussion.

Thanks,
Trista

**Comment by jingshanglu** [comment]
@zhaopinglu @tristaZero Now, the sql is support on parser by pr #7353, but maybe not have correct route.

**Comment by tristaZero** [comment]
> @zhaopinglu @tristaZero Now, the sql is support on parser by pr #7353, but maybe not have correct route.

Tha's a big step ahead!

**Comment by tristaZero** [comment]
@zhaopinglu You could give it a try keeping the following words in mind.

> This feature is supported only by the parser engine at present. We can not guarantee that the routing result is correct, which means we need more effort to work on this feature furthermore. As you know, it is not an easy one. Accordingly, I suggest you,

1. Change the relevant SQL to the ones without ` where (a, b) = ...`
2. Try your SQL using the master branch.

Best,
Trista

**Comment by kimmking** [comment]
@zhaopinglu keep move on.

**Comment by kimmking** [comment]
As this issue have no more infomation for a long time, we close it now.
