### ISSUE TITLE
sharding-proxy can't load metadata automatic

### ISSUE THREAD

**Issue by judakun** [apache/shardingsphere#6947]
## sharding-proxy can't load metadata automatic

**Description:** My project uses HA architecture, and custom registry to instead of zookeeper. I use one of the sharding-proxy to execute DDL statements, but another sharding-proxy can't synchronize data automatic. When I'm doing high-availability switching, must be to restart this sharding-proxy to load data. So i need help from technologist.

**Comment by wcsoft** [comment]
@judakun 

Thx to report the issue!
From the description of the issue, executing DDL statements from a sharding-proxy is not synchronized automatically to the onther one, right? could you provide more detail about it?

It's pleasure you can type more information in format like this:

- What's the issue?
- How to reproduce it?
- What's the actural result?
- What's your expectation?
- What's the version of ShardingSphere
- Provide the configuration about ShardingSphere if you have.
-  Code pieces.

**Comment by tristaZero** [comment]
@judakun Hi 
> custom registry to instead of the zookeeper. 
Could you clarify this statement? Does your custom registry implement `OrchestrationRepository` interface? Did you configure the `orchestration` in the YAML file?

**Comment by judakun** [comment]
@wcsoft ok

- What's the issue?
sharding-proxy can't load metadata automatic. Double sharding-proxy use one custom registry, and watch the same data. 
I changed the rules of the registry, and both of them can listen in and get the data. I use one of sharding-proxys to execute DDL, but another sharding-proxy can't operate these tables, sametimes can't load these tables.  when i restart it, it's ok.
![image](https://user-images.githubusercontent.com/59358145/90726802-e465dd00-e2f4-11ea-88d6-53be3feca2fd.png)

- What's your expectation?
What i want  sharding-proxy can synchronized automatically to another create tables and data.

- What's the version of ShardingSphere?
4.0.0

- Provide the configuration about ShardingSphere if you have.
My custom registry monitor the five interfaces
1./orchestration_ds/config/schema
2./orchestration_ds/config/props
3./orchestration_ds/config/schema/%s/rule
   `{'bindingTables':[],'broadcastTables':[],'defaultDataSourceName':'ds0','defaultDatabaseStrategy':{'none':{}},'defaultKeyGenerator':{'column':'id','props':{},'type':'SNOWFLAKE'},'defaultTableStrategy':{'none':{}},'encryptRule':{'encryptors':{},'tables':{}},'masterSlaveRules':{'ms_ds0':{'loadBalanceAlgorithmType':'ROUND_ROBIN','masterDataSourceName':'ds0','props':{},'slaveDataSourceNames':['ds0_slave']},'ms_ds1':{'loadBalanceAlgorithmType':'ROUND_ROBIN','masterDataSourceName':'ds1','props':{},'slaveDataSourceNames':['ds1_slave']}},'tables':{'t_order':{'actualDataNodes':'ms_ds${0..1}.t_order${0..1}','databaseStrategy':{'inline':{'algorithmExpression':'ms_ds${user_id % 2}','shardingColumn':'user_id'}},'logicTable':'t_order','tableStrategy':{'inline':{'algorithmExpression':'t_order${order_id % 2}','shardingColumn':'order_id'}}},'example_order':{'actualDataNodes':'ms_ds${0..1}.example_order${0..1}','databaseStrategy':{'inline':{'algorithmExpression':'ms_ds${user_id % 2}','shardingColumn':'user_id'}},'logicTable':'example_order','tableStrategy':{'inline':{'algorithmExpression':'example_order${order_id % 2}','shardingColumn':'order_id'}}}}}`
4./orchestration_ds/config/schema/%s/datasource
5./orchestration_ds/config/authentication

**Comment by judakun** [comment]
@tristaZero 
server.yaml
![image](https://user-images.githubusercontent.com/59358145/90729233-d6b25680-e2f8-11ea-8c3e-2f453ab55c45.png)
**OrchestrationRepository**shardingSphere 4.0.0 can't find this class

**My custom registry**
`public final class CuratorZookeeperCenterRepository implements ConfigCenterRepository, RegistryCenterRepository {}`

**Comment by wcsoft** [comment]
@tuohai666 

Please have a look at the issue.

**Comment by tristaZero** [comment]
Hi @judakun 
Thanks for your comments. 

ShardingSphere has `CuratorZookeeper` for `CenterRepository` already. Why do not you use the implement provided by   ShardingSphere?

**Comment by kimmking** [comment]
plz try 4.1.1 @judakun

**Comment by terrymanu** [comment]
Closed because of no response anymore
