### ISSUE TITLE
PreciseShardingAlgorithm does not work

### ISSUE THREAD

**Issue by RafaelGuo** [apache/shardingsphere#6948]
I implements PreciseShardingAlgorithm interface, but it does not work, who can give me a help?

**Comment by jacksparrow414** [comment]
@RafaelGuo could give more details ?

**Comment by RafaelGuo** [comment]
> @RafaelGuo could you show more details ?
now, I have three tables: sns_resource_basic, sns_resource_cache, sns_resource_essay. When i insert data to these tables, data should be inserted to a same database, sharding0 or sharding1, but In fact，data is insert to two deffierent databases. Please help me to check it.

1. my class
`public class CustomPreciseShardingAlgorithm implements PreciseShardingAlgorithm<String> {

    private static final Logger logger = LoggerFactory.getLogger(CustomPreciseShardingAlgorithm.class);

    public CustomPreciseShardingAlgorithm() {
        logger.info("CustomPreciseShardingAlgorithm 初始化");
    }

    @Override
    public String doSharding(Collection<String> collection, PreciseShardingValue<String> preciseShardingValue) {
        int hashedKey = Math.abs(preciseShardingValue.getValue().hashCode());

        for (Object dbName : collection) {
            String dbNameStr = (String) dbName;

            String dbRange = dbNameStr.substring(dbNameStr.indexOf("-") + 1);
            String[] dbRangeArr = dbRange.split("-");
            Integer begin = Integer.valueOf(dbRangeArr[0]);
            Integer end = Integer.valueOf(dbRangeArr[1]);

            if (hashedKey >= begin && hashedKey <= end) {
                return dbNameStr;
            }
        }
        return null;
    }
}`

2. my configuration
`spring.shardingsphere.datasource.names=sharding0,sharding1

spring.shardingsphere.datasource.sharding0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.sharding0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.sharding0.url=jdbc:mysql://127.0.0.1:3306/sharding0?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.sharding0.username=root
spring.shardingsphere.datasource.sharding0.password=123456

spring.shardingsphere.datasource.sharding1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.sharding1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.sharding1.url=jdbc:mysql://127.0.0.1:3306/sharding1?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.sharding1.username=root
spring.shardingsphere.datasource.sharding1.password=123456

spring.shardingsphere.rules.sharding.tables.sns_resource_basic.actual-data-nodes=sharding0.sns_resource_basic,sharding1.sns_resource_basic
spring.shardingsphere.rules.sharding.tables.sns_resource_essay.actual-data-nodes=sharding0.sns_resource_essay,sharding1.sns_resource_essay
spring.shardingsphere.rules.sharding.tables.sns_resource_cache.actual-data-nodes=sharding0.sns_resource_cache,sharding1.sns_resource_cache

spring.shardingsphere.rules.sharding.tables.sns_resource_basic.database-strategy.inline.sharding-column=res_id
spring.shardingsphere.rules.sharding.tables.sns_resource_basic.database-strategy.inline.algorithm-expression=sharding$->{Math.abs(res_id.hashCode())%2}

spring.shardingsphere.rules.sharding.tables.sns_resource_essay.database-strategy.inline.sharding-column=res_id
spring.shardingsphere.rules.sharding.tables.sns_resource_essay.database-strategy.inline.algorithm-expression=sharding$->{Math.abs(res_id.hashCode())%2}

spring.shardingsphere.rules.sharding.tables.sns_resource_cache.database-strategy.inline.sharding-column=res_id
spring.shardingsphere.rules.sharding.tables.sns_resource_cache.database-strategy.inline.algorithm-expression=sharding$->{Math.abs(res_id.hashCode())%2}`

**Comment by jacksparrow414** [comment]
@RafaelGuo hi, I use your config ,use you code, use the same res_id,data inserted to the same database.
![Xnip2020-08-20_20-23-33](https://user-images.githubusercontent.com/33389378/90769674-3160a800-e323-11ea-88bd-0b4708532e8d.jpg)

**Comment by RafaelGuo** [comment]
> @RafaelGuo hi, I use your config ,use you code, use the same res_id,data inserted to the same database.
> ![Xnip2020-08-20_20-23-33](https://user-images.githubusercontent.com/33389378/90769674-3160a800-e323-11ea-88bd-0b4708532e8d.jpg)
really? could you send your code to me? my email: 1412760381@qq.com

**Comment by RafaelGuo** [comment]
> @RafaelGuo hi, I use your config ,use you code, use the same res_id,data inserted to the same database.
> ![Xnip2020-08-20_20-23-33](https://user-images.githubusercontent.com/33389378/90769674-3160a800-e323-11ea-88bd-0b4708532e8d.jpg)

@jacksparrow414 really? could you send your code to me? my email: 1412760381@qq.com

**Comment by tristaZero** [comment]
@jacksparrow414 Very appreciated your time to answer questions, nice job. :-)
Your work will benefit `OUR` community. 

Thanks,
Trista

**Comment by jacksparrow414** [comment]
@tristaZero Grow with the community  :smile:

**Comment by RafaelGuo** [comment]
> @RafaelGuo hi, I use your config ,use you code, use the same res_id,data inserted to the same database.
> ![Xnip2020-08-20_20-23-33](https://user-images.githubusercontent.com/33389378/90769674-3160a800-e323-11ea-88bd-0b4708532e8d.jpg)

I find the reason why it is not work, because my configuration is wrong.
my config is: spring.shardingsphere.rules.sharding.tables.sns_resource_cache.database-strategy.standard.sharding-column=res_id.
It should be spring.shardingsphere.sharding.tables.sns_resource_essay.database-strategy.standard.sharding-column=res_id,
![image](https://user-images.githubusercontent.com/28351792/90867514-13994e80-e3c8-11ea-9a8d-3c78f713097d.png)

**Comment by RafaelGuo** [comment]
> @tristaZero Grow with the community 😄

@jacksparrow414 
I find the reason why it is not work, because my configuration is wrong.
my config is: spring.shardingsphere.rules.sharding.tables.sns_resource_cache.database-strategy.standard.sharding-column=res_id.
It should be spring.shardingsphere.sharding.tables.sns_resource_essay.database-strategy.standard.sharding-column=res_id,

**Comment by jacksparrow414** [comment]
@RafaelGuo :thumbsup:  as other configuartion,you could refer to official documents or the code I sent you
