### ISSUE TITLE
Packaging code will report this error

### ISSUE THREAD

**Issue by Hilary0511** [apache/shardingsphere#6949]
## Question

Packaging code will report this error

[INFO] shardingsphere-integration-test .................... SUCCESS [  0.086 s]
[INFO] shardingsphere-test-fixture ........................ SUCCESS [  0.086 s]
[INFO] shardingsphere-proxy-docker-build .................. FAILURE [  0.020 s]
[INFO] shardingsphere-test-suite .......................... SKIPPED
[INFO] shardingsphere-distribution ........................ SKIPPED
[INFO] shardingsphere-src-distribution .................... SKIPPED
[INFO] shardingsphere-jdbc-distribution ................... SKIPPED
[INFO] shardingsphere-proxy-distribution .................. SKIPPED
[INFO] shardingsphere-scaling-distribution ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.837 s
[INFO] Finished at: 2020-08-20T13:51:31+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shardingsphere-proxy-docker-build: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-proxy-docker-build:jar:5.0.0-RC1-SNAPSHOT: Failure to find org.apache.shardingsphere:shardingsphere-test-fixture:jar:tests:5.0.0-RC1-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shardingsphere-proxy-docker-build

**Comment by wcsoft** [comment]
@Hilary0511

**Comment by Hilary0511** [comment]
> @Hilary0511
> 
> It seems you get the issue when building ShardingSphere 5.0, is it? I dont have the issue and "org.apache.shardingsphere:shardingsphere-test-fixture:jar:tests:5.0.0-RC1-SNAPSHOT" stays in mvn working directory, look the screenshot as follow:
> ![image](https://user-images.githubusercontent.com/8036861/90736030-319b7c00-e300-11ea-860b-6945b5dd0090.png)
> 
> Could you provide details bellow:
> 
> * Which branch of ShardingSphere to build? Provide more infomation as much as you can.
> * How to build the project? Provide the command line or screenshot.

The branch is master；

**Comment by Hilary0511** [comment]
> @Hilary0511
> 
> It seems you get the issue when building ShardingSphere 5.0, is it? I dont have the issue and "org.apache.shardingsphere:shardingsphere-test-fixture:jar:tests:5.0.0-RC1-SNAPSHOT" stays in mvn working directory, look the screenshot as follow:
> ![image](https://user-images.githubusercontent.com/8036861/90736030-319b7c00-e300-11ea-860b-6945b5dd0090.png)
> 
> Could you provide details bellow:
> 
> * Which branch of ShardingSphere to build? Provide more infomation as much as you can.
> * How to build the project? Provide the command line or screenshot.

Can you send me a copy of your package to my email address? 465585935 @qq.com

**Comment by Hilary0511** [comment]
> @Hilary0511
> 
> It seems you get the issue when building ShardingSphere 5.0, is it? I dont have the issue and "org.apache.shardingsphere:shardingsphere-test-fixture:jar:tests:5.0.0-RC1-SNAPSHOT" stays in mvn working directory, look the screenshot as follow:
> ![image](https://user-images.githubusercontent.com/8036861/90736030-319b7c00-e300-11ea-860b-6945b5dd0090.png)
> 
> Could you provide details bellow:
> 
> * Which branch of ShardingSphere to build? Provide more infomation as much as you can.
> * How to build the project? Provide the command line or screenshot.

**Comment by wcsoft** [comment]
@Hilary0511 
Do you pull the latest code of master branch?
Could you try "mvn clean install" instead of running serveral mvn commands?

**Comment by Hilary0511** [comment]
> @Hilary0511
> Do you pull the latest code of master branch?
> Could you try "mvn clean install" instead of running serveral mvn commands?

Yes, I pulled the latest code of master branch.
Using the "mvn clean install" command reports the following error
![image](https://user-images.githubusercontent.com/33475609/90840206-f34b9e80-e38b-11ea-9fed-e26699bdda31.png)

**Comment by Hilary0511** [comment]
> @Hilary0511
> Do you pull the latest code of master branch?
> Could you try "mvn clean install" instead of running serveral mvn commands?

OK, it is packed.it may be that there is Chinese in the path as the package failed.
THX.

**Comment by Hilary0511** [comment]
> @Hilary0511
> Do you pull the latest code of master branch?
> Could you try "mvn clean install" instead of running serveral mvn commands?
Now I have packed the bags but I can't find these two bags as shown in the picture. Could you please help me check the positions of these two bags?
![image](https://user-images.githubusercontent.com/33475609/90843820-13cc2680-e395-11ea-8b05-cc06d539be98.png)
