### ISSUE TITLE
How to achieve the effect of mandatory routing for all tables when the database is forcibly routed

### ISSUE THREAD

**Issue by HanKaiqiang** [apache/shardingsphere#6964]
## Question

I want to use forced routing to use the database on another server, but the tables of the two databases are not much the same, what should I do to make all tables use forced routing instead of configuring logical tables.

At the same time, the main library is also equipped with read-write separation

**Comment by terrymanu** [comment]
> At the same time, the main library is also equipped with read-write separation

What is `main library`? Can you use correct words to describe your issue?

**Comment by HanKaiqiang** [comment]
> > At the same time, the main library is also equipped with read-write separation
> 
> What is `main library`? Can you use correct words to describe your issue?

I want to use forced routing to achieve the effect of dynamically selecting data sources, without setting the logical table

**Comment by kimmking** [comment]
do you mean Hint sharding strategy?

**Comment by HanKaiqiang** [comment]
> do you mean Hint sharding strategy?

yes, but I don't want to set logical table,  I hope all tables can be scanned automatically

**Comment by terrymanu** [comment]
I can't understand what is scanned automatically, can you give an example?

**Comment by HanKaiqiang** [comment]
> I can't understand what is scanned automatically, can you give an example?

yes,  This project can explain.

https://github.com/HanKaiqiang/shardingsphere-demo.git

**Comment by HanKaiqiang** [comment]
please， help me

**Comment by jacksparrow414** [comment]
@HanKaiqiang I'll use the example you provided to look at the problem

**Comment by HanKaiqiang** [comment]
> @HanKaiqiang I'll use the example you provided to look at the problem

 Ok, thanks

**Comment by HanKaiqiang** [comment]
> @HanKaiqiang I'll use the example you provided to look at the problem

ok， thanks

**Comment by jacksparrow414** [comment]
@HanKaiqiang
I try to reproduce problem by configuration you provided, and I found that there are no **tableRule** so that ShardingSphere use
unicast routing.
![{747621FA-F45B-432F-8210-EFE957E11EDC}_20200905114508](https://user-images.githubusercontent.com/33389378/92297014-4cf7bf80-ef6d-11ea-92b9-13d81f185fb1.jpg)

**Comment by HanKaiqiang** [comment]
@jacksparrow414   So, Direct Route also needs to be set sharding key ?  
![image](https://user-images.githubusercontent.com/48614052/92341431-3ded4a80-f0f0-11ea-8349-52adbfd925f0.png)

**Comment by HanKaiqiang** [comment]
@jacksparrow414  use default-database-strategy.hint,   must set tableRule ?    May I set default-table-strategy.hint ?

**Comment by kimmking** [comment]
In our issue board, any external file and project refered is not accepted, cause it can be removed or modified, so then our users can't see the entire records.
