### ISSUE TITLE
SQL evaluated expressions with double parentheses can not sharding

### ISSUE THREAD

**Issue by peng-ran** [apache/shardingsphere#6982]
SELECT ROUND(a.F_ID, 3)  / 1000 - ROUND(a.F_ID, 3)  / 1000 as F_ID,
               a.F_NAME
        FROM t_demo AS a

is ok 

        SELECT (ROUND(a.F_ID, 3) - ROUND(a.F_ID, 3))  / 1000 as F_ID,
               a.F_NAME
        FROM t_demo AS a
or

        SELECT (ROUND(a.F_ID, 3) - ROUND(a.F_ID, 3))  + 1000 as F_ID,
               a.F_NAME
        FROM t_demo AS a

or 

        SELECT (ROUND(a.F_ID, 3))  / 1000 as F_ID,
               a.F_NAME
        FROM t_demo AS a
is error ,can not sharding

**Comment by terrymanu** [comment]
What the version do you use? 
The problem has already fixed by version 4.x.

**Comment by peng-ran** [comment]
@terrymanu sharding-jdbc-core 4.1.1

**Comment by kimmking** [comment]
it's a bug.

> select (1+id) as iid from test;

is ok. 

> select (1+id)+2 as iid from test;

will be not sharding.

**Comment by jingshanglu** [comment]
@peng-ran @kimmking @terrymanu  Now, i test it on master branch, it is ok.
![image](https://user-images.githubusercontent.com/16559542/91792368-f5451580-ec47-11ea-9254-4c0518bce0b0.png)
![image](https://user-images.githubusercontent.com/16559542/91792419-09891280-ec48-11ea-96c1-43818b341afb.png)

**Comment by kimmking** [comment]
I check these cases work well now in master branch.
