### ISSUE TITLE
Finish OrchestrationBootstrapTest‘s assertion

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7000]
Please finish `assertProxyConfiguration` for two test cases

**Comment by jian365066744** [comment]
why didn't merge?can you give me tips?

**Comment by terrymanu** [comment]
@jian365066744 I post code review comment on your pull request, please check and fix them

**Comment by jian365066744** [comment]
I have add more assert,is all right?
![image](https://user-images.githubusercontent.com/35258103/91654561-6667ba00-eadc-11ea-8b6e-8ea19f1301d8.png)

**Comment by jian365066744** [comment]
if the #7000 is correct , please merge to  master,or you can tell the details reason as soon as possible.so I can fix and finish the #6926

**Comment by jian365066744** [comment]
Do you delete the OrchestrationBootstrapTest ? I can't find the class in latest version.

**Comment by menghaoranss** [comment]
The `OrchestrationBootstrap` has been removed in the master branch, we will close this issue soon, thanks all.
