### ISSUE TITLE
Add more test cases for DatabaseProtocolFrontendEngineFactory when newInstance success

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7012]

**Comment by terrymanu** [comment]
Cloud you consider about finish #7000 first？

**Comment by jian365066744** [comment]
sorry for&nbsp;so late ,I will finish&nbsp;both afternoon.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 中午12:13
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Add more test cases for DatabaseProtocolFrontendEngineFactory when newInstance success (#7012)





 
Cloud you consider about finish #7000 first？

**Comment by xbkaishui** [comment]
please assign to me

**Comment by xbkaishui** [comment]
@victorzhangchn , your pr is duplicate with mine :smile:
