### ISSUE TITLE
Should use SPI to introduce metrics in SingletonFacadeEngine.buildMetrics which calling on FrontendChannelInboundHandler

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7013]
For ShardingSphere's design way, proxy front module should not understand metrics and other governance concepts.
It is better to use SPI to introduce them.

Please see  `FrontendChannelInboundHandler`, line 62

**Comment by kimmking** [comment]
Since we remove and redesign metrics integrated with java agent [1], now we close this issue.

1. https://github.com/apache/shardingsphere/issues/6653  phase 4
