### ISSUE TITLE
Investigate why auth exception occur and process the exception correctly

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7014]
Please investigate why exception occur, and remove log if possible.
The `expected exception` should be return by error packet only.

**Comment by tuohai666** [comment]
It makes sense to remove the error log.

This issue if good for beginners:

`Remove the lines 84, 85 in FrontendChannelInboundHandler.java`

**Comment by guo156627977** [comment]
please assign to  me

**Comment by tuohai666** [comment]
Hi @guo156627977 , we decide to keep origin. Sorry for that.

**Comment by tuohai666** [comment]
The catched Exception is needed because PacketPayload's close() throws exceptions. This catch also handles the Netty exceptions when authentication.
