### ISSUE TITLE
[ShardingSphere-Proxy] Empty data packet

### ISSUE THREAD

**Issue by hongfuli** [apache/shardingsphere#7017]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

The data packet may be empty in some scenarios, for example, the login password is empty.

I'm not sure it is correct  as the follow modification(replace `>=` with `>`) 

```java
    @Override
    public boolean isValidHeader(final int readableBytes) {
        return readableBytes >= MySQLPacket.PAYLOAD_LENGTH + MySQLPacket.SEQUENCE_LENGTH;
    }
```

**Comment by tristaZero** [comment]
Hi, @hongfuli Thanks for your issue.
Besides, are you interested in raizing a PR to fix it?
If you worry about your modification, I think a unit test is expected in your PR as well. Moreover, our committers will also give it a review.

**Comment by tuohai666** [comment]
@hongfuli Can you show more examples? I had never met a single header transfer on the wire.

As to the empty password you mentioned, the username is not empty at the same time. There're also Client Capabilities/Charset/Client Auth Plugin information in the Login request packet.

**Comment by hongfuli** [comment]
If encounter `Authentication Method Mismatch` case, the server sends `Auth Switch Request` packet to client and then the client sends `Auth Switch Response` only contains header if the password is empty, because the username had been exchanged in the previous initial handshake. The following is capture data of complete auth phase:

<img width="1325" alt="Capturing_from_Loopback__lo0" src="https://user-images.githubusercontent.com/837054/91062173-93d4e380-e656-11ea-9e88-6d00b9f01362.png">

**Comment by tuohai666** [comment]
@hongfuli Yes, you are right. Would you like to submit a PR?

**Comment by hongfuli** [comment]
sure no problem.
