### ISSUE TITLE
Whether or not to support splitting tables in batches (wildcard method)？

### ISSUE THREAD

**Issue by lovehehehe** [apache/shardingsphere#7027]
**eg：**
 his_score,his_class,his_*** -> db0
 now_score,now_class,now_*** -> db1

Just divide the tables into different dbs with wildcard

**not like:**  
<sharding:table-rules>
               <sharding:table-rule logic-table="student_0" actual-data-nodes="m2.student_0"/>
               <sharding:table-rule logic-table="film" actual-data-nodes="m1.film"/>
               <sharding:table-rule logic-table="language" actual-data-nodes="m1.language"/>
               <sharding:table-rule logic-table="customer" actual-data-nodes="m1.customer"/>
           </sharding:table-rules>
Each table is configured with a node once

**Comment by terrymanu** [comment]
Not support yet

**Comment by lovehehehe** [comment]
ok  thanks!
