### ISSUE TITLE
Add test case for CommandExecutorTask

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7039]
There is do not need to use multiple threads, just assert run method is OK.

**Comment by jian365066744** [comment]
assign to me

**Comment by terrymanu** [comment]
@jian365066744  Hi, I notice the #7024 did not merge yet, could you finish previous pull request before you request a new task?

**Comment by jian365066744** [comment]
I will&nbsp; add more inaccurate assertions for rules in #7024,can you give me some tips?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午2:56
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Add test case for CommandExecutorTask (#7039)





 
@jian365066744  Hi, I notice the #7024 did not merge yet, could you finish previous pull request before you request a new task?
