### ISSUE TITLE
Shardingjdbc paging problems

### ISSUE THREAD

**Issue by 19950813** [apache/shardingsphere#7045]
### 一.  problem description

- In the process of using `ShardingJDBC`, `ORM`  framework used `Mybatis plus` , and found that using the native paging plug-in of `MyBatis Plus`  would fail. Later, I changed the commonly used `pageHelper` paging plug-in, and the paging result is still invalid...

**Comment by tristaZero** [comment]
Hi @19950813 
The issue about `pageHelper` came into my view a few times, I suggest you look up the issue list with the keyword like `pagination` or `limit`.
