### ISSUE TITLE
sharding in version 5.0.0

### ISSUE THREAD

**Issue by Hilary0511** [apache/shardingsphere#7046]
## Question

Do you still have this sharding in version 5.0.0? PreciseShardingAlgorithm and RangeShardingAlgorithm are not found on the latest master branch. If there are any, please help me to point out the location
![image](https://user-images.githubusercontent.com/33475609/91114880-7be37b00-e6bb-11ea-8c17-7f416d181459.png)

**Comment by tristaZero** [comment]
There is an adjustment for these API from 5.x. Maybe `StandardShardingAlgorithm` is what you want.

**Comment by terrymanu** [comment]
Can you summary the title for search friendly?

**Comment by terrymanu** [comment]
Closed because of no response anymore
