### ISSUE TITLE
up to 4.1.1 SQL result error

### ISSUE THREAD

**Issue by miniygq** [apache/shardingsphere#7047]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

```
SELECT
	dept_id,
	 ( SELECT count( * ) FROM s_sys_dept AS pDept WHERE pDept.parent_id = s_sys_dept.dept_id AND pDept.sys_delete = 0 ) AS children_count 
FROM
	s_sys_dept 
WHERE
	( sys_delete = 0 AND parent_id = '0' ) 
ORDER BY
	sys_index;
```

v4.1.1 `children_count` return 0 
v4.0.1 `children_count` return 1

**Comment by terrymanu** [comment]
@miniygq  Can you summary the title for search friendly?

**Comment by kimmking** [comment]
Can you show the actual sql in 4.1.1 and 4.0.1

**Comment by terrymanu** [comment]
Closed because of no response anymore
