### ISSUE TITLE
hi, @pengzhiming-sys , we need more info:

### ISSUE THREAD

**Issue by pengzhiming-sys** [apache/shardingsphere#7062]
hi, @pengzhiming-sys , we need more info:
1. which version
2. the logic sql and actual sql executed when throws exception
3. did you use a PG client or library to connect to proxy?

_Originally posted by @kimmking in https://github.com/apache/shardingsphere/issues/7056#issuecomment-679916924_

**Comment by pengzhiming-sys** [comment]
1.apache-shardingsphere-4.1.1
2.use a PG client or library to connect to proxy

**Comment by terrymanu** [comment]
@pengzhiming-sys Hi, I think this issue seems like wrong operation. I just close it, please report a new issue if you still have questions.
