### ISSUE TITLE
MYSQL command line can not access ShardingProxy after ShardingProxy starts up successfully.

### ISSUE THREAD

**Issue by wcsoft** [apache/shardingsphere#7065]
- What's the Issue

MYSQL command line can not access ShardingProxy after ShardingProxy starts successfully.

- Steps to reproduce the behavior

1. The issue occurs at ShardingSphere 5.0, the branch to test is master, build number is  "86b1dcb";
2. Build ShardingProxy based on the branch above; 
3. Start up ShardingProxy service; check its process to make sure it run successfully by cammond  "ps -ef | grep proxy";  check its log to make sure there is no any error(log path is <shardingsphere_proxy_base>/logs/stdout.log),  have a look at screenshots bellow:
![image](https://user-images.githubusercontent.com/8036861/91166380-de149e00-e704-11ea-9408-d3c5efce74e1.png)

![image](https://user-images.githubusercontent.com/8036861/91166439-f4225e80-e704-11ea-9fae-fe85b3c31f53.png)

4. Access ShardingProxy by mysql command  "mysql -u root -proot -P3307 -h ip" - sorry that i can not type the real ip here as confidential.

- Actual behavior

After triggering mysql command, the command hangs there all the time, see screenshow bellow. I test it on ShardingProxy 4.1.1, it works.
![image](https://user-images.githubusercontent.com/8036861/91167999-70b63c80-e707-11ea-9e76-5b73af5b64e9.png)

- Expected behavior

MYSQL command line can access ShardingProxy after ShardingProxy starts successfully.

- Which version of ShardingSphere did you use
1. ShardingSphere Version: 5.0
2. ShardingSphere branch: master
3.  ShardingSphere build number: 86b1dcb

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
The version 5.x is still in dev model, so we don't accept the report as a bug.
It will change rapidly.
User please use released version, 5.x for contributors only.
