### ISSUE TITLE
select 'count' column data, why return null?

### ISSUE THREAD

**Issue by leolv123** [apache/shardingsphere#7072]
sharding print the log as follows:
![image](https://user-images.githubusercontent.com/34678371/91247009-d9db9580-e783-11ea-966c-827c15757f38.png)

mysql output data as follows: 
![image](https://user-images.githubusercontent.com/34678371/91246803-5f127a80-e783-11ea-8d12-8216111028a5.png)

Final return result as follows: 
![image](https://user-images.githubusercontent.com/34678371/91246901-9ed96200-e783-11ea-93f8-3c58dde95faa.png)

why the column 'count' return null ???

**Comment by terrymanu** [comment]
What is the version do you use?

**Comment by tristaZero** [comment]
Hi @leolv123 
First, these actual SQLs are correct, aren't they?
Is there any `null` or other special values in `count` column?

**Comment by leolv123** [comment]
> What is the version do you use?

3.0.0.M3

**Comment by leolv123** [comment]
> Hi @leolv123
> First, these actual SQLs are correct, aren't they?
> Is there any `null` or other special values in `count` column?

I found the problem，It's caused by the mapping
![image](https://user-images.githubusercontent.com/34678371/91268534-1a4d0a80-e7a8-11ea-96e2-f3e4750178ad.png)

but there are other problems, why there a 'count' field in the query results, data merging will execute GroupByMemoryMergedResult
![image](https://user-images.githubusercontent.com/34678371/91268860-a3fcd800-e7a8-11ea-86fa-a4268b90ccc9.png)

**Comment by kimmking** [comment]
Can you try 4.1.1 ?

**Comment by leolv123** [comment]
> Can you try 4.1.1 ?

this version solve this problem？？

**Comment by tristaZero** [comment]
@leolv123 
Are you sure that `GroupByMemoryMergedResult` changes the result? If `count` is just a column name, I suppose it will not be handled by `GroupByMemoryMergedResult`.

>but there are other problems, why there a 'count' field in the query results, data merging will execute GroupByMemoryMergedResult

**Comment by leolv123** [comment]
> @leolv123
> Are you sure that `GroupByMemoryMergedResult` changes the result? If `count` is just a column name, I suppose it will not be handled by `GroupByMemoryMergedResult`.
> 
> > but there are other problems, why there a 'count' field in the query results, data merging will execute GroupByMemoryMergedResult


i am sure
![image](https://user-images.githubusercontent.com/34678371/91399405-81ce8d00-e870-11ea-911c-7af7c0f4809a.png)

**Comment by leolv123** [comment]
i know the reason, V3.0.0 use the **SelectListClauseParser.class** to parse the select statement
![image](https://user-images.githubusercontent.com/34678371/91810712-f3d41700-ec60-11ea-849d-28edd36b8d70.png)

V4.0.0 cann't find the class, Is the parse class changed??

**Comment by tristaZero** [comment]
Maybe `AggregationProjectionSegment` on the master branch is what you want?
From 4.x, we chose a new and more efficient Parser Engine to parse SQL. I suggest you can dig into the master branch to get your answer. :-)
