### ISSUE TITLE
sharding-jdbc automatically disable invalid slave datasource

### ISSUE THREAD

**Issue by lishijun121910** [apache/shardingsphere#7081]
version：
sharding-jdbc 4.1.0

situation:
springboot+mybatis+sharding-jdbc+mysql(master-slave).

For high availability, I use MHA to deal with master fail, switch and push event to zookeeper by script , to tell sharding-jdbc the new master . this works well.

But MHA only focus on fail of master, it does not care about fail of slave. When the slave is down , sharding-jdbc doesn't know and will still try to read from slave .

I wonder if sharding-jdbc can recognize unreachable datasource and block it ? Say I have two slavies, one is down , sharding-jdbc automatically block it and read the other one.

Or can you recommend some solutions to deal with fail of slave node ?

**Comment by tristaZero** [comment]
@lishijun121910 Hi 

Thanks for your feedback. 
For me, I like your idea.
We are considering MySQL `mgr` and `orchestrator` ([The detail](https://github.com/apache/shardingsphere/issues/6662)).
But it needs pretty much time and effort. If we just take care of the current functions of ShardingSphere. My rough thought is to **get the exception and execute this SQL in another slave afterward**

**Comment by lishijun121910** [comment]
> @lishijun121910 Hi
> 
> Thanks for your feedback.
> For me, I like your idea.
> We are considering MySQL `mgr` and `orchestrator` ([The detail](https://github.com/apache/shardingsphere/issues/6662)).
> But it needs pretty much time and effort. If we just take care of the current functions of ShardingSphere. My rough thought is to **get the exception and execute this SQL in another slave afterward**.

We are trying to use a HA to make a load balance to all slave nodes. By this way we don't worry about any single fail .

**Comment by tristaZero** [comment]
Hi @lishijun121910 Do you think it is possible to contribute what you did to the community? I think others will appreciate this significant feature as well. But I also suggest you'd better give the draft of your idea or critical code clip firstly here for a discussion. Maybe we will receive any better feedback from the community to make it excellent.

Best,
Trista

**Comment by kimmking** [comment]
This will be in our plan for 5.x.

**Comment by kimmking** [comment]
hi, @lishijun121910  you can refer and track this issue: https://github.com/apache/shardingsphere/issues/7318
