### ISSUE TITLE
if the feature on issue #6174 can be released in a new 4.x version？

### ISSUE THREAD

**Issue by dilboy** [apache/shardingsphere#7086]
## Question

 Excuse me ,if the feature on issue #6174 can be released in a new 4.x version？
#6101, support fetch size in DatabaseMetaDataResultSet #6174

**Comment by terrymanu** [comment]
Sorry, but we have no plan to maintain more version branches.

**Comment by dilboy** [comment]
Is it possible to open the 4.x branch, let's help release it together?
