### ISSUE TITLE
How to enable parameter printing in SQL

### ISSUE THREAD

**Issue by zhaokejin** [apache/shardingsphere#7087]
Shardingsphere supports me to open it sql.show However, it does not show the parameters in the SQL statement. How to configure the parameters that are passed in as placeholders in SQL
![image](https://user-images.githubusercontent.com/13448504/91299107-b3dde180-e7d3-11ea-9a33-5c85a31ee214.png)

open show.sql , only SQL, no parameters in SQL, how to open parameters

**Comment by tristaZero** [comment]
Hi @zhaokejin 
AFAIK, the SQLs, and parameters will show up together. Which version was used?

**Comment by terrymanu** [comment]
Closed because of no response anymore
