### ISSUE TITLE
Add UnitTest for OrchestrationShardingSphereDataSourceFactory

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#7099]
Location: 
shardingsphere-jdbc/shardingsphere-jdbc-orchestration/src/main/java/org/apache/shardingsphere/driver/orchestration/api/OrchestrationShardingSphereDataSourceFactory.java

**Comment by jian365066744** [comment]
please assign to me

**Comment by kimmking** [comment]
> please assign to me

as your will

**Comment by kimmking** [comment]
Is there anything foward or problem?

**Comment by terrymanu** [comment]
@kimmking @jian365066744 It is better to assign other contribute because jian365066744 has too issues assigned.

**Comment by sluk3r** [comment]
please assign to me

**Comment by terrymanu** [comment]
@sluk3r Hi, the pr #7155 is not finish this issue because we need to submit code into master branch.
The class is already changed to `GovernanceShardingSphereDataSourceFactory`, could you submit the test case again for master?

**Comment by sluk3r** [comment]
> @sluk3r Hi, the pr #7155 is not finish this issue because we need to submit code into master branch.
> The class is already changed to `GovernanceShardingSphereDataSourceFactory`, could you submit the test case again for master?

Ok, I'll try
