### ISSUE TITLE
Official example link error

### ISSUE THREAD

**Issue by zhangyang1995** [apache/shardingsphere#7113]
https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/usage/transaction/

The official link at the bottom of the page is wrong！

**Comment by terrymanu** [comment]
Can you submit a pull request to fix it?

**Comment by kimmking** [comment]
Since master branch became to 5.x, documents for 4.x had been archived. And the referred link should be https://github.com/apache/shardingsphere/tree/4.1.1/examples/sharding-jdbc-example/sharding-example

I will fix it today.

**Comment by kimmking** [comment]
It's fixed now.
