### ISSUE TITLE
update opentracing api version

### ISSUE THREAD

**Issue by eightroad** [apache/shardingsphere#7117]
## Feature Request

**For English only**, other languages will not accept.

I'm using opentracing, but sharding-opentrace depends version 0.30.0; and others(opentrace-springcloud) depends 0.32.0 or later version(0.33.0)
in 0.32.0 ,It move "io.opentracing.NoopSpanBuilderImpl" to "io.opentracing.noop.NoopSpanBuilderImpl",and remove some method

### Describe the feature you would like.
update opentracing api to 0.32.0 or latest

**Comment by kimmking** [comment]
There is no plan for it.
