### ISSUE TITLE
Sharding key in ON-Clause(Not Where-Clause) cause a error "No Sharding Key"

### ISSUE THREAD

**Issue by mark4z** [apache/shardingsphere#7129]
## Bug Report
when i want do like this:
select ... 
from A left join B on a.id = b.id and b.`key` = ?
where ...
B has been sharding and the key is `key`
A has more rows than B，so if i use left join, should put the predicates on `on` rather than `where`. but i got a error which said 
me have not Sharding Key. 

### Which version of ShardingSphere did you use?
4.0.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

**Comment by kimmking** [comment]
you can try:
```
select ...
from A left join B on a.id = b.id 
where b.key = ? ...
```

**Comment by mark4z** [comment]
> you can try:
> 
> ```
> select ...
> from A left join B on a.id = b.id 
> where b.key = ? ...
> ```

You know, left join  in ON-Clause equals inner join

**Comment by mark4z** [comment]
> you can try:
> 
> ```
> select ...
> from A left join B on a.id = b.id 
> where b.key = ? ...
> ```

So, sharding not supported this.

**Comment by jingshanglu** [comment]
@mark4z Can you show more stack info?

**Comment by mark4z** [comment]
> @mark4z Can you show more stack info?

Sorry, I can't resume it now. but actually it doesn't work.



like this:

Actual SQL: ds0 ::: select count(1) from forward left join back0 on back0.id = forward.id and back0.price = 100 where forward.id = 1
Actual SQL: ds0 ::: select count(1) from forward left join back1 on back1.id = forward.id and back1.price = 100 where forward.id = 1

‘back’ is a table which has been sharing and the key is 'price'.

**Comment by jingshanglu** [comment]
> > @mark4z Can you show more stack info?
> 
> Sorry, I can't resume it now. but actually it doesn't work.
> 
> like this:
> 
> Actual SQL: ds0 ::: select count(1) from forward left join back0 on back0.id = forward.id and back0.price = 100 where forward.id = 1
> Actual SQL: ds0 ::: select count(1) from forward left join back1 on back1.id = forward.id and back1.price = 100 where forward.id = 1
> 
> ‘back’ is a table which has been sharing and the key is 'price'.

@mark4z `forward` is a actualTable? can you give the correct rewrited sql for this sql?

**Comment by jingshanglu** [comment]
@mark4z You can try the master branch, the rewriting  has been greatly improved on master branch.

**Comment by mark4z** [comment]
> @mark4z You can try the master branch, the rewriting has been greatly improved on master branch.

Thks，if i have time, i'll dothing for this project.

**Comment by kimmking** [comment]
As this issue have no more infomation for a long time, we close it now.
