### ISSUE TITLE
Navicat or MySQL Workbench: No database selected

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7141]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Compat with Navicat or MySQL Workbench.

### Actual behavior

When use Navicat or MySQL Workbench connect ShardingSphere-Proxy, the client promp "No database selected".

### Reason analyze (If you can)

Maybe caused by https://github.com/apache/shardingsphere/pull/6281

**Comment by tuohai666** [comment]
@tristaZero I noticed you remove
`backendConnection.setCurrentSchema(ProxySchemaContexts.getInstance().getSchemaContexts().getSchemaContexts().keySet().iterator().next());`
from UnicastBackendHandler.java in https://github.com/apache/shardingsphere/pull/6281 which cause this problem. Can you have a look?

**Comment by lidonghai11** [comment]
Another error occurred，so  the navicat doesn't work with sharding-proxy.
![navicat](https://user-images.githubusercontent.com/66629133/92594531-7bf79380-f2d5-11ea-90ec-2ec3df5acb9f.png)
@tuohai666 @tristaZero

**Comment by tristaZero** [comment]
@lidonghai11 Thanks for your test. FYI The issue relating to this subject has been fixed already. If you have any other questions, a new issue is preferred, which will help others find their target issue ASAP.
