### ISSUE TITLE
Errors in parsing database function calls to facilitate the implementation of expanded sub-database queries

### ISSUE THREAD

**Issue by unjie** [apache/shardingsphere#7161]
## Feature Request
When using the custom function getRemindDays to execute "SELECT getRemindDays(${minCyc},${expirePrompt},#{user.uid})" SQL, db-sharding-autoconfiguration/4.1.1.RELEASE/db-sharding-autoconfiguration- 4.1.1.RELEASE.jar!/org/apache/shardingsphere/sql/parser/mysql/visitor/MySQLVisitor.class:321 conversion exception, cannot be converted to ColumnSegment object
中文:
在使用自定义函数getRemindDays 执行"  SELECT getRemindDays(${minCyc},${expirePrompt},#{user.uid}) " SQL 时提示db-sharding-autoconfiguration/4.1.1.RELEASE/db-sharding-autoconfiguration-4.1.1.RELEASE.jar!/org/apache/shardingsphere/sql/parser/mysql/visitor/MySQLVisitor.class:321 转换异常, 不能转换为ColumnSegment 对象
### Describe the feature you would like.
I want to process some unsupported parsing during the sql parsing process, or skip the SQL parsing and let the developer use other constraints. The database and tableName are routed to a RouteResult object.
I am trying to build these codes
中文:
我想在sql 解析过程中处理一些不支持的解析,或跳过SQL 解析由开发者使用其他约束.以路由database 与 tableName 以,相应一个RouteResult 对象.
我正在尝试构建这些代码

**Comment by tristaZero** [comment]
@unjie 
Hi Thanks for your feedback, English comment is required though.
This issue has been fixed on the master branch. If you want to learn more, please take a keyword search in `issues` or `PRs` list.

Best,
Trista
