### ISSUE TITLE
The refinement on categorizing all the SQL statements

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#7170]
Hi community,

I know this issue will be another considerable workload for the community. However, we have to start and boost it to move forward.

The reason is that **the overmuch and detailed segments overload the corresponding SQL statements at presently**. 

For instance, there is a `SetAssignmentSegment` in `InsertStatement`. Yet, the dialect SQL `INSERT SET` is an exclusive SQL for MySQL and not available for other databases. Hence, an `MySQLInsertStatement` with `SetAssignmentSegment` is needed. Moveover, it is better to split the original `InsertStatement` into `OracleInsertStatement`, `PostgreSQLInsertStatment`, `SQLServerInsertStatement`.

The case above is just a toy example, and there are many similar cases here. We have to polish all the SQL Statements. **Welcome you, who are interested in this issue, to join the community to push this issue to move ahead!**

Cheers,
Trista

**Comment by dongzl** [comment]
very great work!

**Comment by strongduanmu** [comment]
@tristaZero Hi, I want to participate in this task, can you assign some tasks to me? 😀
