### ISSUE TITLE
Support Oracle RAC

### ISSUE THREAD

**Issue by foreverzfg** [apache/shardingsphere#7195]
When the url type like this

 _jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.12)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.0.22)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = rac)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))

it throws UnrecognizedDatabaseURLException.

**Comment by tristaZero** [comment]
Hi @foreverzfg 

If so, I suppose it is not difficult to fix it. Would you like to work on it to help yourself and the community?

Here is a solution,

> Adjust the `pattern`(Just a regular expression)  in `OracleDataSourceMetaData` to cover your case.

Look forward to your reply.

Thanks,
Trista

**Comment by xbkaishui** [comment]
please assign to me

**Comment by tristaZero** [comment]
@xbkaishui Good luck.

**Comment by xbkaishui** [comment]
For the Oracle RAC case,  it has multi host info, is that ok we random choose one?

**Comment by xbkaishui** [comment]
@tristaZero  Hey, fixed this issue, please take time to have a look, Thanks
