### ISSUE TITLE
In multi-tenant mode database sharding invalid

### ISSUE THREAD

**Issue by zhaojitao** [apache/shardingsphere#7196]
## Question

![image](https://user-images.githubusercontent.com/17734542/91823534-eec89500-ec6b-11ea-85cf-793a3307301e.png)
In multi-tenant mode, all tables of each tenant have the same structure and are partitioned according to tenant ID. Since there are hundreds and thousands of tables in the business that need to be partitioned, can the program execute the default partitioning rule without specifying tables? After testing, if the tables that need to be partitioned are not specified, the default partitioning rule will be invalid

**Comment by zhaojitao** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.1.1</version>
        </dependency>

**Comment by tristaZero** [comment]
Hi @zhaojitao 
AFAIK, no one gave any feedback about this issue so far. Could you set `sql.show` right. So we can check whether the default strategy works or not.

**Comment by zhaojitao** [comment]
Hi @tristaZero 
![image](https://user-images.githubusercontent.com/17734542/91953765-d58b1b80-ed33-11ea-87e3-09fd6612e3fc.png)
![image](https://user-images.githubusercontent.com/17734542/91953839-dc199300-ed33-11ea-99d3-9f8df037bf46.png)

**Comment by zhaojitao** [comment]
Hi @TristaZero
![image](https://user-images.githubusercontent.com/17734542/91954163-fe131580-ed33-11ea-931d-8118c6b1c52a.png)
![image](https://user-images.githubusercontent.com/17734542/91954289-2f8be100-ed34-11ea-83bb-4398dad4ec8e.png)

**Comment by tristaZero** [comment]
@zhaojitao Do we have the same understanding of `defaultTableRule`? If there is `defaultTableRule`, you can ignore configuring the shardingStratergy, but `actualDataNodes: ds_${0..1}.t_order_${0..1}` is required yet, right?

**Comment by zhaojitao** [comment]
@tristaZero yes,The defaultDatabaseRulerule is not valid if actualDataNodes are not configured。I have 1000 table needed sharding database, do I need to configure actualDataNodes? Is that right?

**Comment by tristaZero** [comment]
Hi @zhaojitao 
I have to say that meet the expectation.  i.e., Even though users use `defaultDatabaseRulerule`, a simplified `tableRule` with `DatabaseRulerule` is still unavoidable. Otherwide, how does shardingSphere know this table is a sharding table or non-sharding table?

**Comment by zhaojitao** [comment]
@tristaZero Let's try a different idea here, which is to set whether all tables are default sharded or not, and then add a table that excloud doesn't go with the default rule (whether sharding or not), which helps us achieve that goal of simplifying configuration, which is of course a small recommendation. Here's a code snippet that helps clarify

**Comment by tristaZero** [comment]
@zhaojitao Sorry I can not get your idea clear. Do you mean to add one configuration item to set some of the tables using `defaultDatabaseRulerule`?
BTW, at present, you just need to configure a table name for those intending to use `defaultDatabaseRulerule`. It seems not taxing？

**Comment by zhaojitao** [comment]
@tristaZero ok,you are right! thanks!

**Comment by zhonghuali** [comment]
Striongly suggest to add new config for setting whether all tables are default sharded or not, then simplifying this kind of configuration
