### ISSUE TITLE
LockSegment absent of PostgreSQL parser 

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7200]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Under MasterSlave rule:

`SELECT * FROM t_order WHERE user_id = ? FOR UPDATE`

should be routed to Master node

### Actual behavior

The SQL is routed to Slave node

### Reason analyze (If you can)

LockSegment absent of PostgreSQL parser 

Please refer to the route logic in MasterSlaveDataSourceRouter:

 ```
    private boolean isMasterRoute(final SQLStatement sqlStatement) {
        return containsLockSegment(sqlStatement) || !(sqlStatement instanceof SelectStatement) || MasterVisitedManager.isMasterVisited() || HintManager.isMasterRouteOnly();
    }
    
    private boolean containsLockSegment(final SQLStatement sqlStatement) {
        return sqlStatement instanceof SelectStatement && ((SelectStatement) sqlStatement).getLock().isPresent();
    }
```

**Comment by kfwang90** [comment]
Hi, I have a similar problem when execute sql like this `select nextval('seq_name');`  The SQL is routed to Slave node.
Does this PR resolved the problem? @tuohai666
