### ISSUE TITLE
sharding jdbc, when insert config useGeneratedKeys , in one Transactional , the ID obtained by batch insertion is the first one

### ISSUE THREAD

**Issue by fantacy2001** [apache/shardingsphere#7227]
sharding jdbc 4.0.0
mybatis spring
sql mapper:
 <insert id="insertByStockMoveDetail" parameterType="com.jd.jcloud.wms.inventory.stockMove.domain.StockMoveDetail"
            useGeneratedKeys="true" keyProperty="id">
        insert into stock_move_detail  ........      values .....
sharding config ： only sharding db ,  Custom keyGenerator : UidGenerator
in one Transactional ,  Loop in the java code to call single insert Dao（insertByStockMoveDetail）,The insertion ID obtained each time in the loop is the first.
remove the transaction,  it's OK

**Comment by tristaZero** [comment]
Hi, do you think your issue is similar to the issues in [#6895](https://github.com/apache/shardingsphere/pull/6895)?

**Comment by fantacy2001** [comment]
> Hi, do you think your issue is similar to the issues in [#6895](https://github.com/apache/shardingsphere/pull/6895)?

It could be similar.  BatchInsert under the same transaction
#6895 is batchInsert in one sql ,like "insert into table values(),(),();"
my question is single insert ,like "insert into table values();"
but Loop in the java code to call the sql, the loop is managed by transactions  like 
for(A a : aList){
     singleInsert(a);
}

**Comment by tristaZero** [comment]
> It could be similar. BatchInsert under the same transaction

If so, it has been identified as a bug indeed. Please wait for it fixed. I believe the next release will include this bugfix certainly.

Hi, @terrymanu Ping here.

**Comment by jiuye9999** [comment]
> sharding jdbc 4.0.0 mybatis spring sql mapper: insert into stock_move_detail ........ values ..... sharding config ： only sharding db , Custom keyGenerator : UidGenerator in one Transactional , Loop in the java code to call single insert Dao（insertByStockMoveDetail）,The insertion ID obtained each time in the loop is the first. remove the transaction, it's OK
