### ISSUE TITLE
Refactor shadow API

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7276]
The current Shadow API's `shadowMappings` is not easy to understand.

It is better to create a new `ShadowDataSourceRuleConfiguration` object for collection.
There are `sourceDataSourceName` and `shadowDataSourceName` into the object.

Just ref for MasterSlave's configuration. Any suggestion?

We need to determine and complete the API changes before 5.0.0-alpha release.

**Comment by yanickxia** [comment]
i will refactor it.
