### ISSUE TITLE
Consider about remove shardingsphere-proxy-common module

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7281]
shardingsphere-proxy-common include ProxyConfiguration, DataSourceParameterConverter, YAML related, RDL converter

This module may remove and move the object to suitable modules.

My idea:

1. Move ProxyConfiguration into `shardingsphere-proxy-bootstrap` module
2. Move DataSourceParameterConverter into `shardingsphere-proxy-backend` module
3. Move RDL converter into `shardingsphere-proxy-backend` module

**Comment by RaigorJiang** [comment]
Hi @terrymanu, does this plan need to be retained?

**Comment by terrymanu** [comment]
Yes, it need to be discuss more, we can just keep it.

**Comment by RaigorJiang** [comment]
> Yes, it need to be discuss more, we can just keep it.

OK.
