### ISSUE TITLE
Add test cases for proxy's bootstrap.init package

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7285]
Please add test cases for proxy's bootstrap.init package, the tasks are:

- [x] StandardBootstrapInitializerTest
  - [x] Add test case for StandardBootstrapInitializer.getProxyConfiguration()
  - [x] Add test case for StandardBootstrapInitializer.decorateSchemaContexts()
  - [x] Add test case for StandardBootstrapInitializer.decorateTransactionContexts()
- [x] GovernanceBootstrapInitializerTest
  - [x] Finish assertProxyConfiguration in GovernanceBootstrapInitializerTest
  - [x] Add test case for GovernanceBootstrapInitializer.decorateSchemaContexts()
  - [x] Add test case for GovernanceBootstrapInitializer.decorateTransactionContexts()
- [ ] AbstractBootstrapInitializerTest
  - [ ] Add abstract class AbstractBootstrapInitializerTest which extended by StandardBootstrapInitializerTest and GovernanceBootstrapInitializerTest
  - [ ] Add test cases for init method

**Comment by sluk3r** [comment]
please assign it to me

**Comment by gzdzss** [comment]
I want to get involved

**Comment by taojintianxia** [comment]
finished StandardBootstrapInitializerTest
