### ISSUE TITLE
Proposal of add e2e test case

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#7303]
## Feature Request
Since we added more and more features (components) in SS.  The unit test and IT test may not enough to guarantee the whole quality, 
It's better to add end to end test case. 

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No, it's just enhance the test case related 
### Describe the feature you would like.
Add e2e test case for each major components (jdbc, proxy, shadow, encryption etc)

**Comment by xbkaishui** [comment]
Hi guys. anyone have some suggestions?

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 6 months, we will close it. 
If you still have related questions, please submit a new issue, thank you.
