### ISSUE TITLE
Rename MasterSlave module to ReadWriteSplit

### ISSUE THREAD

**Issue by flycoolman** [apache/shardingsphere#7307]
This is a proactive change to catch up with the movement of industry.
Primary and replica will be used as alternatives.

**Comment by flycoolman** [comment]
@terrymanu 
I will work on the change. Please assign it to me.

**Comment by tristaZero** [comment]
Hi @flycoolman Thanks for your attention for the issue from the dev ml.
Welcome!

This issue is likely to cause a massive effect on the modules. Please be careful about renaming work and potential conflicts caused by other contributors. :-)

@terrymanu Ping.

**Comment by terrymanu** [comment]
@flycoolman Great, thank you for take this task.

I paste the mail here.
FYI: https://lists.apache.org/thread.html/r95fb756ce67f52b1dac9ba103cf68e38d3df88f3356ff2f3bfaa0556%40%3Cdev.shardingsphere.apache.org%3E

**Comment by flycoolman** [comment]
@tristaZero Thanks for reminding me the difficulty of the task. I understand it will have a massive effect. So I expect stricter review before merge.

**Comment by flycoolman** [comment]
Hi @terrymanu @tristaZero ,
Please review the changes and let me know any further changes. This fix does not include the folder of 'examples'.
I have all the tests pass locally. I would like to keep this fix as small as possible, as long as all the tests can pass.
As expected, there are lots of conflicts.

Thanks for your patience.

**Comment by flycoolman** [comment]
To meet the release date, other people may open new issue and do it.
