### ISSUE TITLE
Add more test cases for ShardingSphere-Proxy

### ISSUE THREAD

**Issue by gzdzss** [apache/shardingsphere#7321]
Please add test cases for proxy, the tasks are:

**shardingsphere-proxy-backend**
-  ~~ProxySQLExecutorCallback~~

**shardingsphere-proxy-frontend-core**
- ~~ShardingSphereProxy **(jian365066744)~~
- ~~FrontendChannelInboundHandler~~
- ~~ServerHandlerInitializer **(jian365066744)~~

**shardingsphere-proxy-frontend-mysql**
- ~~MySQLFrontendEngine~~
- ~~MySQLCommandExecuteEngine~~
- ~~MySQLUnsupportedCommandExecutor~~

**shardingsphere-proxy-frontend-postgresql**
- [x] PostgreSQLFrontendEngine **(sandynz)**
- [x] PostgreSQLCommandExecutorFactory **(sandynz)**
- [x] PostgreSQLUnsupportedCommandExecutor **(sandynz)**
- [x] PostgreSQLComTerminationExecutor **(gzdzss)**
- [x] PostgreSQLComDescribeExecutor **(gzdzss)**
- [x] PostgreSQLComExecuteExecutor **(gzdzss)**
- [x] PostgreSQLComParseExecutor **(gzdzss)**
- [x] PostgreSQLComSyncExecutor **(gzdzss)**
- [x] PostgreSQLUnsupportedCommandExecutor **(gzdzss)**
- [x] PostgreSQLErrPacketFactory  **(gzdzss)**

**Comment by jian365066744** [comment]
assign to me

**Comment by cenyu00** [comment]
I want do this :

shardingsphere-proxy-frontend-mysql

 - MySQLProtocolFrontendEngine
- MySQLCommandExecuteEngine
- MySQLUnsupportedCommandExecutor

**Comment by tuohai666** [comment]
@jian365066744 Please pick up one or more test cases, thanks.

**Comment by gzdzss** [comment]
> I want do this :
> 
> shardingsphere-proxy-frontend-mysql
> 
> * MySQLProtocolFrontendEngine
> * MySQLCommandExecuteEngine
> * MySQLUnsupportedCommandExecutor

 @cenyu00  Got it.  

Please finish the tasks :
- ~~MySQLProtocolFrontendEngine~~ -> MySQLFrontendEngine
- MySQLCommandExecuteEngine
- MySQLUnsupportedCommandExecutor

**Comment by jian365066744** [comment]
I want do this


shardingsphere-proxy-frontend-core


&nbsp;ShardingSphereProxy
&nbsp;FrontendChannelInboundHandler
&nbsp;ServerHandlerInitializer


---Original---

**Comment by gzdzss** [comment]
> I want do this shardingsphere-proxy-frontend-core &nbsp;ShardingSphereProxy &nbsp;FrontendChannelInboundHandler &nbsp;ServerHandlerInitializer
> […](#)
> ---Original--- From: "Zhang Yonglun"<notifications@github.com&gt; Date: Tue, Sep 8, 2020 16:23 PM To: "apache/shardingsphere"<shardingsphere@noreply.github.com&gt;; Cc: "Mention"<mention@noreply.github.com&gt;;"zhang jian"<365066744@qq.com&gt;; Subject: Re: [apache/shardingsphere] Add more test cases for Sharding-Proxy (#7321) @jian365066744 Please pick up one or more test cases, thanks. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@jian365066744  Got it.

Please finish the tasks :
-  ShardingSphereProxy
-  FrontendChannelInboundHandler
-  ServerHandlerInitializer

**Comment by sandynz** [comment]
Hi, I'd like to try `shardingsphere-proxy-frontend-postgresql` module:
- PostgreSQLProtocolFrontendEngine
- PostgreSQLCommandExecutorFactory
- PostgreSQLUnsupportedCommandExecutor
- PostgreSQLComTerminationExecutor
- PostgreSQLComDescribeExecutor
- PostgreSQLComExecuteExecutor
- PostgreSQLComParseExecutor
- PostgreSQLComSyncExecutor

**Comment by gzdzss** [comment]
> Hi, I'd like to try `shardingsphere-proxy-frontend-postgresql` module:
> 
> * PostgreSQLProtocolFrontendEngine
> * PostgreSQLCommandExecutorFactory
> * PostgreSQLUnsupportedCommandExecutor

@sandynz  Got it.

Please finish the tasks :

- ~~PostgreSQLProtocolFrontendEngine~~  -> PostgreSQLFrontendEngine
- PostgreSQLCommandExecutorFactory
- PostgreSQLUnsupportedCommandExecutor

**Comment by gzdzss** [comment]
I didn't get the update for a long time, so I turned it off
