### ISSUE TITLE
can not find owner from table when select from a,b with where condition

### ISSUE THREAD

**Issue by chana71** [apache/shardingsphere#7326]
## Bug Report
This type SQL `select from (subquery)a, (subquery)b where a.id=b.aid` will report the error below. It should work as `join ... on`. Will this be fixed? Thx
![image](https://user-images.githubusercontent.com/31340809/92448162-ccde8d80-f1ea-11ea-8971-1736ba37c2e7.png)

### Which version of ShardingSphere did you use?
master 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy

**Comment by kimmking** [comment]
It's doesn't support now, and no plan for enhancement.
refer: https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/sql/#%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84sql

**Comment by chana71** [comment]
@kimmking sorry I don't figure out which one belongs to my case in your ref.
Besides how about this one `select from (subquery)a join (subquery)b on a.id = b.id where a.id=?`.  Report the same error. will this be fixed?
