### ISSUE TITLE
Add more test cases for ProxyContext

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7331]
Please add test cases for:

- [ ] ProxyContext.init()
- [ ] ProxyContext.schemaExists()
- [ ] ProxyContext.getSchema()
- [ ] ProxyContext.getAllSchemaNames()

**Comment by xiangtao** [comment]
hi, it cat assign it to me @terrymanu

**Comment by yu199195** [comment]
@xiangtao Welcome to join

**Comment by terrymanu** [comment]
I renamed `ProxySchemaContexts` to `ProxyContext` via #7335, so I just modify the issue title and content as well.

**Comment by terrymanu** [comment]
There is no feedback for the pull request, I'd like to reopen this issue for new contributor.

**Comment by sluk3r** [comment]
please assign it to me
