### ISSUE TITLE
Proxy show tables command can't show unConfigured table

### ISSUE THREAD

**Issue by xbkaishui** [apache/shardingsphere#7342]
## Bug Report
When use show tables command in ShardingSphere-Proxy (using sharding database feature)
It only show configured table, skiped the unconfigured table

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy using sharding feature
### Expected behavior
show all the tables in current sharding db
### Actual behavior
show only configuration table

## Reason analyze (If you can)
I found the bug maybe in 
LogicTablesMergedResult.java 
Line 56: 
```
 if (shardingRule.getTableRules().isEmpty() || schemaMetaData.containsTable(actualTableName) && tableNames.add(actualTableName)) {
   result.add(memoryResultSetRow);
  }
```

**Comment by tristaZero** [comment]
@xbkaishui Hi this bug has been fixed, which will help us test the metadata loading function.

Best,
Trista

**Comment by xbkaishui** [comment]
Yes， already checked. it is ok now, below is the example output 

```
| t_address            |
| t_order              |
| t_order_item         |
| t_user_third_account |
```

**Comment by tristaZero** [comment]
@xbkaishui Oh, your valuable feedback moves the 5x. release forward!

**Comment by xbkaishui** [comment]
:beers:
