### ISSUE TITLE
can't save null or not null in navcat 11 version, logical table null collumn is alway checked!!

### ISSUE THREAD

**Issue by cay914** [apache/shardingsphere#7358]
can't save null or not null in navcat 11 version
And the **null column** is not inconsistent between logical and actual table.
![image](https://user-images.githubusercontent.com/6037435/92584715-8f4f3280-f2c6-11ea-9932-3585a5109e23.png)

Env:
sharding-proxy 4.1.0
mysql 5.7
navcat 11

**Comment by kimmking** [comment]
Can you try 4.1.1 or master version?

**Comment by tuohai666** [comment]
Please set sql.show: true to see from the log what is the SQL when you click the box.

**Comment by kimmking** [comment]
@cay914 hi, anything for feedback?

**Comment by tuohai666** [comment]
Expired.
