### ISSUE TITLE
query with encrypt column , the result is incorrected

### ISSUE THREAD

**Issue by Keanhua** [apache/shardingsphere#7359]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 
### Expected behavior
when i query with encrypt column ,it can query the data
### Actual behavior
when i query with encrypt column ,it can query no data
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/31396902/92585879-2072d900-f2c8-11ea-95b0-41f6e0aacaa7.png)
when the table is instance of SubqueryTableSegment , it will not add to tables, it not parse the encrypt param
![image](https://user-images.githubusercontent.com/31396902/92586331-ad1d9700-f2c8-11ea-818c-4891275d769d.png)
when the table is instance of SimpleTableSegment , it will add to tables, it will parse the encrypt param

**Comment by kimmking** [comment]
plz show your config rules and logic sql/actual sql.

**Comment by Keanhua** [comment]
encryptors:
  encryptor_aes:
    props:
      aes.key.value: 123131313
    type: AES
tables:
  shangbao_idcard_verify:
    columns:
      idcard:
        cipherColumn: idcard
        encryptor: encryptor_aes

**Comment by Keanhua** [comment]
Logic SQL: SELECT COUNT(1) FROM ( SELECT  id,create_time,update_time,name,idcard,result,operate_time,operator_id,operator_name,valid  FROM shangbao_idcard_verify 
 
 WHERE (valid = ? AND (name = ? OR idcard = ?)) ORDER BY id DESC ) TOTAL


 Actual SQL: ds ::: SELECT COUNT(1) FROM ( SELECT  id,create_time,update_time,name,idcard,result,operate_time,operator_id,operator_name,valid  FROM shangbao_idcard_verify 
 
 WHERE (valid = ? AND (name = ? OR idcard = ?)) ORDER BY id DESC ) TOTAL ::: [1, 533022199607040734, 533022199607040734]

**Comment by kimmking** [comment]
encrypted query with subquery/join now is not supported.

**Comment by Keanhua** [comment]
@kimmking this is also a subquery but it can encrypt
![image](https://user-images.githubusercontent.com/31396902/92704620-a6088e80-f385-11ea-82c9-3678ca5d98df.png)

**Comment by Keanhua** [comment]
@kimmking but 4.0.1 is supported
