### ISSUE TITLE
SeataATShardingTransactionManager  can‘t read seata.conf

### ISSUE THREAD

**Issue by kpioneer123** [apache/shardingsphere#7360]
seata.conf exists in classpath ，but SeataATShardingTransactionManager  show please config application id within seata.conf file.

pom file ：
		<dependency>
			<groupId>io.seata</groupId>
			<artifactId>seata-spring-boot-starter</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-transaction-base-seata-at</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by cherrylzhao** [comment]
@kpioneer123 sorry for late response, please tell me your environment is sharding-proxy or sharding-jdbc? our jdbc-example is ok for that.

**Comment by kpioneer123** [comment]
sharding-jdbc   when seata-spring-boot-starter is 1.3.0   @kimmking @cherrylzhao

**Comment by kpioneer123** [comment]
Yes，can read seata.conf 。 
Need use SPI code in own project，not before so report an error 。
Thank you! @kimmking @cherrylzhao
