### ISSUE TITLE
shardingSphere orchestration question about logic_db

### ISSUE THREAD

**Issue by wencyGit** [apache/shardingsphere#7370]
![image](https://user-images.githubusercontent.com/21151964/92674545-290ef200-f350-11ea-868a-fac3d6d5b60d.png)
![image](https://user-images.githubusercontent.com/21151964/92675118-45f7f500-f351-11ea-861c-df9249640cfa.png)

```
I use Nacos client to register the service with Nacos in sahrdingsphere
Then I see sharding in the Nacos console configuration list_ test.config.schema .
When I look at documents and operations, I still don't understand sharding_test.config.schema What's the point,
sharding_ test.config.schema The configuration content is only logic_db
```

**Comment by menghaoranss** [comment]
`sharding_test.config.schema` node persist all logic schemas that configured in proxy, if use jdbc ,it's the default `logic_db`.

**Comment by wencyGit** [comment]
@menghaoranss 
I can understand it as sharding_ test.config.schema It only works on proxy,
If you only use sharding-jdbc, you can ignore sharding_test.config.schema Is this the configuration content of

**Comment by kimmking** [comment]
the application using sharding-jdbc with orchestration will be a logic schema named logic_db.
