### ISSUE TITLE
ShardingSphere-JDBC :  line 1:154 no viable alternative at input '->'

### ISSUE THREAD

**Issue by zhangboqing** [apache/shardingsphere#7372]
### Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.1.1</version>
        </dependency>

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
have not log this error

### Actual behavior
1、Only the error log was printed on the console
2、The SQL can execute correctly

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT count(0) FROM op_producer_hotting_task WHERE create_time BETWEEN ? AND ? AND app_id = ? AND source IN (?, ?, ?, ?) AND status IN (?) AND data_json->'$.crowdPackageId' IS NOT NULL

**Comment by tuohai666** [comment]
@zhangboqing 

> 1、Only the error log was printed on the console

what printed on the console in detail?

**Comment by zhangboqing** [comment]
> @zhangboqing
> 
> > 1、Only the error log was printed on the console
> 
> what printed on the console in detail?

**Comment by zhangboqing** [comment]
> @zhangboqing
> 
> > 1、Only the error log was printed on the console
> 
> what printed on the console in detail?

There is no other information；
I debug locally ，find the location of the log info：

`org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.bitExpr(MySQLStatementParser.java:11951)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.predicate(MySQLStatementParser.java:11869)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.booleanPrimary(MySQLStatementParser.java:11486)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.expr(MySQLStatementParser.java:11285)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.expr(MySQLStatementParser.java:11310)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.whereClause(MySQLStatementParser.java:6995)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.selectClause(MySQLStatementParser.java:4600)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.unionClause(MySQLStatementParser.java:4459)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.select(MySQLStatementParser.java:3121)
org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser.execute(MySQLStatementParser.java:769)
org.apache.shardingsphere.sql.parser.mysql.parser.MySQLParser.parse(MySQLParser.java:37)
org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.towPhaseParse(SQLParserExecutor.java:59)
org.apache.shardingsphere.sql.parser.core.parser.SQLParserExecutor.execute(SQLParserExecutor.java:47)
org.apache.shardingsphere.sql.parser.SQLParserEngine.parse0(SQLParserEngine.java:79)`

**Comment by tuohai666** [comment]
@zhangboqing After a serial of analysis, I found you fill reversely in Expected behavior and Actual behavior. Accordingly I guess you click reversely between the button Close and Comment.

**Comment by tuohai666** [comment]
![parseTree](https://user-images.githubusercontent.com/24643893/92693286-fed12a80-f377-11ea-9f9c-c3a225e29fa9.png)

@jingshanglu Can you help to check it?

**Comment by jingshanglu** [comment]
@tuohai666 Ok, new version will fix it.
