### ISSUE TITLE
 [  restartedMain] ShardingSphere-metadata                  : Loading 2048 tables' meta data.

### ISSUE THREAD

**Issue by xianyujava** [apache/shardingsphere#7373]
## Question
配置报错 ，java.sql.SQLException: ORA-00942: 表或视图不存在

MasterSlaveRuleConfiguration masterSlaveRuleConfig = new MasterSlaveRuleConfiguration("ds_master_slave", "ds_master", Arrays.asList("ds_slave"));
        try {
            return MasterSlaveDataSourceFactory.createDataSource(createDataSourceMap(), masterSlaveRuleConfig, new Properties());
        } catch (SQLException e) {
            e.printStackTrace();
        }

**Comment by tuohai666** [comment]
@xianyujava 
Please fill in the bug report:

```
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

```

**Comment by xianyujava** [comment]
照着官网配置读写分离， 为什么程序一启动报查不到表和视图的异常（java.sql.SQLException: ORA-00942: 表或视图不存在）。
定时在查atorg.apache.shardingsphere.sql.parser.binder.metadata.column.ColumnMetaDataLoader.load(ColumnMetaDataLoader.java:75)
什么意思？

**Comment by tuohai666** [comment]
@xianyujava Only English comments will be accepted.

Again, please fill in the bug report.
