### ISSUE TITLE
Make SQLParseResultCache maximum cached elements size customizable

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#7419]
### Is your feature request related to a problem?
No error, it might hurt performance.

### Describe the feature you would like.
Currently, `SQLParseResultCache` has maximum cached elements size `65535`.
In some scenario, routed sql will be parsed again. Since logical table has been rewritten as physical table, it need more cache.

**Comment by tristaZero** [comment]
> In some scenario, routed sql will be parsed again
Does `Some scenarios` mean `SQLParseResultCache` reach its capacity?

Do you have any suggestions or ideas?

**Comment by sandynz** [comment]
> 
> 
> > In some scenario, routed sql will be parsed again
> > Does `Some scenarios` mean `SQLParseResultCache` reach its capacity?

It might reach its capacity. For example, if t_order has 100 shardings, then one sql might be 100 different sqls after rewriting, t_order -> t_order_0, t_order_1, ..., t_order_99.

> 
> Do you have any suggestions or ideas?

Could we initialize `maximumSize` in `SQLParseResultCache` and `StandardSQLParserEngine` constructor?

**Comment by tristaZero** [comment]
> It might reach its capacity. For example, if t_order has 100 shardings, then one sql might be 100 different sqls after rewriting, t_order -> t_order_0, t_order_1, ..., t_order_99.

I am not sure whether we have the consensus that `SQLParseResultCache` will only cache the SQL with logic table name `t_order`, don't we?

**Comment by sandynz** [comment]
> 
> 
> > It might reach its capacity. For example, if t_order has 100 shardings, then one sql might be 100 different sqls after rewriting, t_order -> t_order_0, t_order_1, ..., t_order_99.
> 
> I am not sure whether we have the consensus that `SQLParseResultCache` will only cache the SQL with logic table name `t_order`, don't we?

That's true, it's better to cache sql with logic table name. I just find a new scenario.
If `maximumSize` is customizable, it might be better to use sql parser as individual library.

And that's ok to keep it unchanged, I have some workaround.

Thanks.

**Comment by tristaZero** [comment]
Got it, so do you think we should close this one?
