### ISSUE TITLE
Application start too slow because of scanning all tables's scheme!

### ISSUE THREAD

**Issue by Norshtein94** [apache/shardingsphere#7425]
when I start-up my spring-boot application, sharding-jdbc would scan all tables's scheme, and it took 7 minutes to load datasources. It is just like a attack on my database, for there are thousands of tables in one datasource, and there are nearly 10 datasources in my application! Is it necessary to do this strange operation? And how could I speed up start-up？

**Comment by tristaZero** [comment]
Hi @Norshtein94 thanks for your feedback. That's precisely what we are improving. Please pay attention to #7342. 
We will fix this issue in the incoming 5.x release. Please be patient.
