### ISSUE TITLE
How to configure non-separated tables without ShardingSphere for SQL parsing？

### ISSUE THREAD

**Issue by xfyang1988** [apache/shardingsphere#7430]
How to configure non-distributed tables without ShardingSphere for SQL analysis? But it must be ensured that it is in the same ShardingSphere transaction with the sub-table？

I know that ordinary data sources can be configured without sub-tables, but it is not the same transaction as ShardingSphere

**Comment by tristaZero** [comment]
@xfyang1988 If so, I suggest you configure the `non-sharding` table with `NoneShardingStratergy`. Plus, `defaultDataSource` is for the `non-sharding` table as well.

**Comment by xfyang1988** [comment]
> @xfyang1988 If so, I suggest you configure the `non-sharding` table with `NoneShardingStratergy`. Plus, `defaultDataSource` is for the `non-sharding` table as well.

Even if "defaultDataSource" or "NoneShardingStratergy" is configured, this kind of table that does not require sharding will need to be parsed by ShardingSphere. I have configured the defaultDataSource now, but the tables that do not need to be sharded will still be parsed by ShardingSphere, which results in slow first parsing

**Comment by kimmking** [comment]
Parsing-phase for ShardingSphere is MUST-BE now. No way to avoid it.

**Comment by tristaZero** [comment]
> > @xfyang1988 If so, I suggest you configure the `non-sharding` table with `NoneShardingStratergy`. Plus, `defaultDataSource` is for the `non-sharding` table as well.
> 
> Even if "defaultDataSource" or "NoneShardingStratergy" is configured, this kind of table that does not require sharding will need to be parsed by ShardingSphere. I have configured the defaultDataSource now, but the tables that do not need to be sharded will still be parsed by ShardingSphere, which results in slow first parsing

Hi @xfyang1988 
Only by parsing this SQL it is possible for ShardingSphere to know your table is a sharding table or not. Therefore, SQL parsing is necessary. Actually, parsed SQL will be cached for the next request, which will help weaken parsing's side effects.

Best,
Trista
