### ISSUE TITLE
分库分表、读写分离以及多数据源能否集成倒一起呢？

### ISSUE THREAD

**Issue by SuperIllidan** [apache/shardingsphere#7445]
业务中可能要连接多个不同的数据库，而每个数据库又需要配置读写分离，看了下目前的4.1.1版本，好像配置上不支持呢？

**Comment by kimmking** [comment]
Only english here.
And examples:

https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-databases-tables.yaml

https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-sharding-databases-tables.properties

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
