### ISSUE TITLE
java.sql.Timestamp cannot be cast to java.time.LocalDateTime

### ISSUE THREAD

**Issue by 191824852** [apache/shardingsphere#7447]
![image](https://user-images.githubusercontent.com/26399533/93092748-6bc72600-f6d2-11ea-9b2d-8c6f1b341633.png)
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.time.LocalDateTime

dependency:
              <dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.0.1</version>
		</dependency>

**Comment by kimmking** [comment]
Can you try 4.1.1?
