### ISSUE TITLE
Add more test cases for BackendConnection

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7454]
- [x] getConnections with getConnectionsWithoutTransaction
- [x] createStorageResource
- [x] setFetchSize
- [x] isSerialExecute
- [x] add
- [x] closeResultSets
- [x] closeStatements
- [x] closeConnections

**Comment by sluk3r** [comment]
please assign it to me

**Comment by sluk3r** [comment]
before adding test code, I do checkstyle, result is:

![image](https://user-images.githubusercontent.com/6405801/93218819-3afff300-f79d-11ea-9f69-7e5fc3b56b24.png)


So, should I solve this style problem as well?

**Comment by sluk3r** [comment]
And in ShardingSphere community, what is common solutions for ClassFanOutComplexity? need help.

**Comment by terrymanu** [comment]
May ignore for some checkstyle checks

**Comment by sluk3r** [comment]
> May ignore for some checkstyle checks

OK

**Comment by sluk3r** [comment]
@terrymanu   for task of setFetchSize and add, test cases are added also, the following is the details: 
1. test case for method of add are: assertAddStatementCorrectly, assertAddResultSetCorrectly
2. test case for method of setFetchSize is assertSetFetchSizeAsExpected

Please check the result
