### ISSUE TITLE
Help for issue of 7285

### ISSUE THREAD

**Issue by sluk3r** [apache/shardingsphere#7467]
Hi all, for issue of #7285, I try to add one test for org.apache.shardingsphere.proxy.init.impl.AbstractBootstrapInitializer#init. 

the following is Unit test code: 

![image](https://user-images.githubusercontent.com/6405801/93210838-ee171f00-f792-11ea-8d58-3f483e14da16.png)

(source code link is : https://github.com/sluk3r/shardingsphere/blob/dev-AbstractBootstrapInitializerTest-7285/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/test/java/org/apache/shardingsphere/proxy/init/impl/AbstractBootstrapInitializerTest.java)

Problems are:

1. Is it enough to just assert the specified port is ready?
2. How to stop ShardingSphereProxy server after execution of "new ShardingSphereProxy().start(port)"？ 
3. After execution of "org.apache.shardingsphere.proxy.init.impl.AbstractBootstrapInitializer#init" method, the org.apache.shardingsphere.proxy.init.impl.AbstractBootstrapInitializerTest#assertInit would hang, thereafter "assertTrue(isAvailable(port))" would not be executed. how to solve this problem?

**Comment by kimmking** [comment]
We need discuss to add a close-method for Proxy or not here.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 1 year, we will close it. 
If you still have related questions, please submit a new issue, thank you.
