### ISSUE TITLE
ShardingAlgorithmFactory.newInstance should use context classloader from Thread

### ISSUE THREAD

**Issue by carter-ya** [apache/shardingsphere#7475]
## Bug Report
The correct class loader is not used in the spring devtools environment.
### Which version of ShardingSphere did you use?
4.1.1 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
`Class.forName("class name", true, Thread.currentThread().getContextClassLoader())`
### Actual behavior
`Class.forName("class name")`

**Comment by menghaoranss** [comment]
@carter-ya The `ShardingAlgorithmFactory` has been refactored with SPI in master branch

**Comment by kimmking** [comment]
this API is out of date now.
