### ISSUE TITLE
Broadcast tables join a not broadcast one, how to route to default datasource?

### ISSUE THREAD

**Issue by z3sm** [apache/shardingsphere#7477]
I have a query sql like this:

`select * from table_a a left join table_b b on a.id=b.a_id where a.id = 'XX';
`

table_a:configure it by broadcast tables
table_b:not configure it by broadcast tables.
occured an error:
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ds.table_b' doesn't exist。
`
How to configure table_b's datasource on this case?

I hope this query from default datasource.

Looking forward to your reply 

Thanks

**Comment by kimmking** [comment]
what's your config rules?

**Comment by z3sm** [comment]
> what's your config rules?

spring.shardingsphere.sharding.broadcast-tables= table_a
spring.shardingsphere.sharding.tables.table_a.actual-data-nodes=ds.table_a

"ds" is the default datasource

**Comment by kimmking** [comment]
In your case, hint strategy or raw jdbc datasource maybe a better way.
Sharding rule can't support this case.

**Comment by tristaZero** [comment]
Where is `table_b`? 
Do you want to shard it? If not, how about putting it in default ds?
