### ISSUE TITLE
Add CircuitBreak function for PostgreSQL proxy

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7482]
Please FIY MySQL proxy's implementation on `MySQLComStmtExecuteExecutor` and `MySQLComQueryPacketExecutor`

**Comment by victorzhangchn** [comment]
Please assign to me.

**Comment by victorzhangchn** [comment]
> Please FIY MySQL proxy's implementation on `MySQLComStmtExecuteExecutor` and `MySQLComQueryPacketExecutor`

I'm confusing that the code about CircuitBreak in both `MySQLComStmtExecuteExecutor` and `MySQLComQueryPacketExecutor` is just throw CircuitBreakException, and then wrap it at the outer layer. What do you actually want me to do in this issue? Just throw  CircuitBreakException in `PostgreSQLComExecuteExecutor` and `PostgreSQLComQueryExecutor`? By the way, I find that the behaviour of `PostgreSQLComBindExecutor` does not match the command `BIND` of  protocol of PostgreSQL.

**Comment by terrymanu** [comment]
Yes, Just throw CircuitBreakException in PostgreSQLComExecuteExecutor and PostgreSQLComQueryExecutor `if in CircuitBreak model`

**Comment by SamuelJohnson01997** [comment]
Hi @terrymanu, this issue is still open? If so, I would be glad to help. Kindly assign the issue to me. Thank you.

**Comment by terrymanu** [comment]
@SamuelJohnson01997 
Hi Samuel, it still open, please have a look, thank you.

**Comment by SamuelJohnson01997** [comment]
Hi @terrymanu, after this https://github.com/apache/shardingsphere/commit/89cc0a08c824daf67c88e6cbabaaa05f79886d06 commit, I think the CircuitBreak is moved as state and thus the respective code in MySQLComStmtExecuteExecutor and MySQLComQueryPacketExecutor is removed in the same commit. Should we be still adding the throwing part in  PostgreSQLComExecuteExecutor and PostgreSQLComQueryExecutor or is this resolved already? Please guide me if I'm missing anything. Thank you.

**Comment by terrymanu** [comment]
@SamuelJohnson01997 You are correct, the feature is finished, I just close this issue.
