### ISSUE TITLE
Add more test cases for MySQLErrPacketFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7483]
- [ ] Assert for DBCreateExistsException
- [ ] Assert for DBDropExistsException
- [ ] Assert for TableExistsException
- [ ] Assert for CircuitBreakException
- [ ] Assert for ShardingSphereConfigurationException
- [ ] Assert for SQLParsingException

New exception assertions: 
- [ ] Assert for UnsupportedCommandException
- [ ] Assert for UnsupportedPreparedStatementException

**Comment by sluk3r** [comment]
please assign it to me
