### ISSUE TITLE
使用insert values时, 设置主键参数的index错误

### ISSUE THREAD

**Issue by zhaoyuehui** [apache/shardingsphere#7508]
## Bug Report
笔者使用的主键生成策略是SnowFlake算法, 在执行insert ....values语句时, 由于values中包含null值,  在设置主键id的参数index时, 参数错位. 
代码位置如下图所示
![image](https://user-images.githubusercontent.com/71489073/93571547-328b0080-f9c7-11ea-94f7-9cc9d6d9b268.png)

当参数中包含一个null值时, 主键id的index的位置会被前移一位

**Comment by menghaoranss** [comment]
For english only.
