### ISSUE TITLE
Use sql 'insert ....values()', the location of primary key's index is wrong

### ISSUE THREAD

**Issue by zhaoyuehui** [apache/shardingsphere#7509]
When add primary key's column parameter, if the parameter has a null value, the location of primary key's index is wrong.

Look at the picture

![image](https://user-images.githubusercontent.com/71489073/93574415-f78acc00-f9ca-11ea-9ded-a993ea7ef038.png)

**Comment by menghaoranss** [comment]
Which version of the code is ?

**Comment by zhaoyuehui** [comment]
> 哪个版本的代码是？

4.0.0-RC1

**Comment by zhaoyuehui** [comment]
> Which version of the code is ?

4.0.0-RC1

**Comment by menghaoranss** [comment]
The code has been removed in the later versions, thanks for your feedback.
