### ISSUE TITLE
Enhance test cases for TextProtocolBackendHandlerFactory

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7522]
The class TextProtocolBackendHandlerFactory has already split into multiple Factory classes. It is better to split test cases into suitable classes.

- [ ] Move TCL related test cases into `TransactionBackendHandlerFactoryTest`
- [ ] Keep one TCL SQL test case in `TextProtocolBackendHandlerFactoryTest` and assert return TransactionBackendHandler
- [ ] Move DAL related test cases into `DALBackendHandlerFactoryTest`
- [ ] Keep one DAL SQL test case in `TextProtocolBackendHandlerFactoryTest` and assert return UnicastBackendHandler
- [x] Add test cases for RDL (3 branches) in `TextProtocolBackendHandlerFactoryTest`
- [x] Add test case for MySQLShowTablesStatement in `DALBackendHandlerFactoryTest`
- [x] Add test case for CommitStatement in `TransactionBackendHandlerFactoryTest`
- [x] Add test case for RollbackStatement in `TransactionBackendHandlerFactoryTest`
- [x] Add test case for return BroadcastBackendHandler in `TransactionBackendHandlerFactoryTest`

**Comment by sluk3r** [comment]
please assign it to me

**Comment by menghaoranss** [comment]
@sluk3r Assigned.

**Comment by MingxingLAI** [comment]
can I take it please?

**Comment by terrymanu** [comment]
@MingxingLAI Go ahead please

**Comment by LingyaoLv** [comment]
Hi @MingxingLAI 
Are you working on this issue, or would you still like to contribute and resolve this issue?

**Comment by terrymanu** [comment]
@LingyaoLv Please go ahead if you want fix the issue

**Comment by terrymanu** [comment]
Hi @sluk3r @MingxingLAI @LingyaoLv There are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by tianhao960** [comment]
I would like to take this
