### ISSUE TITLE
are there some constraints on SQL schema  when using Read/Write split function?

### ISSUE THREAD

**Issue by lzqdename** [apache/shardingsphere#7533]
## Question

I am using the  Read/Write split function
I know that the principle inner  is to parse the sql ,and evaluate if it is a SelectStatement
sure, other factors will work , for example Hint and others.

My Question is , Generally,  are there some constraints on SQL schema  when using Read/Write split function?
will some sql  fail  to be parsed due to the complexity of the SQL when using  this function  ?

**Comment by kimmking** [comment]
see https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/sql/

**Comment by lzqdename** [comment]
直接上中文吧，我跟你聊读写分离，你让我看数据分片。。。。。。
