### ISSUE TITLE
sharding-proxy，Can I specify a driver？

### ISSUE THREAD

**Issue by zhanghq1314** [apache/shardingsphere#7552]
## Question
**Can I specify a driver**

![image](https://user-images.githubusercontent.com/69282348/93849884-996a2b80-fcdf-11ea-8546-998212067bff.png)

**Comment by yu199195** [comment]
if you use mysql, please add mysql driver in project lib....

**Comment by kimmking** [comment]
Hi， @zhanghq1314 ，
I guess sharding-proxy/jdbc cannot support sgi-nds.
