### ISSUE TITLE
Some strange issues about the 4.1.1 version？

### ISSUE THREAD

**Issue by ifzm** [apache/shardingsphere#7557]
JavaVersion：1.8.192
ShardingSphere-Proxy Version：4.1.1 release
OS：Windows Server 2016

I tried to download and use ShardingSphere-Proxy, but after downloading the release version, I found that it contains several strange problems

1. There are several dependencies in lib that are not .jar suffixes, which need to be modified manually to make the program run normally
2. The logback.xml configuration in conf is invalid. How to make the custom configuration overwrite the configuration in the jar dependency is not explained in the document, and there is no similar issue in issues.
3. The official document 5.x has updated some instructions in advance, but the git repository does not yet have a corresponding branch, which is misleading to developers who are new to it

**Comment by ifzm** [comment]
A proxy problem was also found during use. After the proxy has been running for a period of time, other clients will not be able to obtain connections, and there is no error message in the command-line. Without the log, it is almost difficult for me to troubleshoot the problem. where

**Comment by lwtdev** [comment]
@ifzm Hi~ 
1. You may try another unzip tool (for example  ` tar` command in git console)

**Comment by kimmking** [comment]
FAQ no 13&14
https://shardingsphere.apache.org/document/current/cn/faq/#13-windows%E7%8E%AF%E5%A2%83%E4%B8%8B%E9%80%9A%E8%BF%87git%E5%85%8B%E9%9A%86shardingsphere%E6%BA%90%E7%A0%81%E6%97%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E6%8F%90%E7%A4%BA%E6%96%87%E4%BB%B6%E5%90%8D%E8%BF%87%E9%95%BF%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
