### ISSUE TITLE
Single quote mark is not supported in LIKE clause

### ISSUE THREAD

**Issue by goool** [apache/shardingsphere#7562]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT, git commit hash: f601d558de

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
mysql> select id from admin where fullname like "%a";
Empty set (0.00 sec)
mysql> select id from admin where fullname like "%a";
Empty set (0.00 sec)
mysql> select id from admin where fullname like '%a';
Empty set (0.00 sec)
mysql> select id from admin where fullname like 'a%';
Empty set (0.00 sec)

### Actual behavior
mysql> select id from admin where fullname like "%a";
Empty set (0.00 sec)
mysql> select id from admin where fullname like "%a";
Empty set (0.00 sec)
mysql> select id from admin where fullname like '%a';
ERROR 10002 (C1000): 2Unknown exception: [Format specifier '%a']
mysql> select id from admin where fullname like 'a%';
ERROR 10002 (C1000): 2Unknown exception: [Conversion = ''']

### Reason analyze (If you can)
It seems like " (double quote mark) is supported in LIKE clause, but ' (single quote mark) is not supported.

**Comment by kimmking** [comment]
@jingshanglu will track it.
