### ISSUE TITLE
How to configure TableGroups use spring namespaces

### ISSUE THREAD

**Issue by pengboyin** [apache/shardingsphere#7577]
I want to ask how to use spring namespace to configure tablegroup. No relevant instructions are found in the document

**Comment by yu199195** [comment]
you can follow this document ： https://shardingsphere.apache.org/document/legacy/4.x/document/cn/overview/

**Comment by tristaZero** [comment]
Hi @pengboyin 
Please consult the link above. If no more questions, please close this one, thx.

**Comment by pengboyin** [comment]
> I want to ask how to use spring namespace to configure tablegroup. No relevant instructions are found in the document

thank you

**Comment by tristaZero** [comment]
If you give attention to the left column, you will get your answer.
 https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/usage/sharding/
