### ISSUE TITLE
Custom slicing rules

### ISSUE THREAD

**Issue by leblancvn** [apache/shardingsphere#7584]
When I customize the partition, I can't determine whether the parameter condition is delete or query. I need this condition because I need to operate different tables according to query or delete.

**Comment by kimmking** [comment]
Can you show an example?

**Comment by leblancvn** [comment]
I divide the database and table according to the time field, and then divide the table by day and month. The tables of the same order day and month are stored. When I query, I only query the database of days. But if I delete the data, I need to delete the data of day and month.

**Comment by leblancvn** [comment]
> Can you show an example?

I divide the database and table according to the time field, and then divide the table by day and month. The tables of the same order day and month are stored. When I query, I only query the database of days. But if I delete the data, I need to delete the data of day and month.

**Comment by leblancvn** [comment]
> Can you show an example?

My scenario is that the database tables returned during query are inconsistent with those returned during deletion.

**Comment by kimmking** [comment]
I don't know your case.

**Comment by leblancvn** [comment]
> I don't know your case.
I want the same query condition to delete and query to return different tables.
example：
DELETE
FROM
	order_info_201903,
	order_info_20190301
WHERE
	create_time BETWEEN '2019-03-01 00:00:00' and '2019-03-01 23:59:59';


select * from 
	order_info_20190301
WHERE
	create_time BETWEEN '2019-03-01 00:00:00' and '2019-03-01 23:59:59';

**Comment by leblancvn** [comment]
> I don't know your case.

I want the same query condition to delete and query to return different tables.
example
DELETE
FROM
	order_info_201903,
	order_info_20190301
WHERE
	create_time BETWEEN '2019-03-01 00:00:00' and '2019-03-01 23:59:59';

select * from 
	order_info_20190301
WHERE
	create_time BETWEEN '2019-03-01 00:00:00' and '2019-03-01 23:59:59';

**Comment by kimmking** [comment]
ShardingSphere can't support multi-tables-delete statement in one sql.
You can split to 2 sqls.

**Comment by leblancvn** [comment]
> ShardingSphere can't support multi-tables-delete statement in one sql.
> You can split to 2 sqls.

I only use pseudo code. I mean the same query condition. I want to return two tables for deletion statement, and only one table for query statement. In dosharding method, I want to judge whether the condition comes from deletion statement or query statement.

**Comment by leblancvn** [comment]
@kimmking In the dosharding method of the complexkeysshardingalgorithm class, can we judge whether the parameter in the where condition of the SQL statement comes from delete or select
