### ISSUE TITLE
Is the official website document written wrong？

### ISSUE THREAD

**Issue by YunJingJian** [apache/shardingsphere#7588]
![image](https://user-images.githubusercontent.com/37235197/94128536-dc1d3680-fe8c-11ea-9055-bf4f9ec7e350.png)
![image](https://user-images.githubusercontent.com/37235197/94128574-e63f3500-fe8c-11ea-9af4-816c37742d91.png)

**Comment by yu199195** [comment]
yes， you are right， the defaultDataSourceName is ds0

**Comment by kimmking** [comment]
fixed it now.
