### ISSUE TITLE
sharding-jdbc的springboot包从哪下载

### ISSUE THREAD

**Issue by xiandadaa** [apache/shardingsphere#7595]
`<dependency>
 <groupId>org.apache.shardingsphere</groupId>
<artifactId>shardingsphere-jdbc-spring-boot-starter</artifactId>
<version>4.1.0</version>
</dependency>`  

官网文档也没标版本号,我理解为跟shardingsphere同版本,但是在maven仓库或者阿里云仓库都没法下载下来，怎么解决，没有上传到maven仓库吗

**Comment by strongduanmu** [comment]
@xiandadaa For english only, other languages ​​will not be accepted.
By the way, the 4.x version of the jar is called `sharding-jdbc-spring-boot-starter`, you can refer to the [maven central repository](https://search.maven.org/artifact/org.apache.shardingsphere/sharding-jdbc-spring-boot-starter/4.1.1/jar).

**Comment by wang1023321231** [comment]
<dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
                <version>4.0.0</version>
            </dependency>
这个包引入项目失败，各个版本的都试了，直接就拉不下来，setting文件也修改过，这个怎么解决呢？

**Comment by sliqiao** [comment]
https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core-spring-boot-starter

这个最新版本只有 5.2.1 ，没有地方自动下载 5.4.1 ，能不能把5.4.1最新jar打到 mvnrepository.com上面？

**Comment by zhangchao778** [comment]
解决了吗

**Comment by zhangchao778** [comment]
> https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core-spring-boot-starter
> 
> ![image](https://github.com/apache/shardingsphere/assets/18230086/512740fd-c691-4883-bd39-a8595fd1fbde)
> 
> 这个最新版本只有 5.2.1 ，没有地方自动下载 5.4.1 ，能不能把5.4.1最新jar打到 mvnrepository.com上面？
> 
> 目前，卡在这里了

你好 解决了吗
