### ISSUE TITLE
connection rebalance issue while make shardingproxy ha on k8s

### ISSUE THREAD

**Issue by hisunwei** [apache/shardingsphere#7616]
Anyone deploy shardingproxy on k8s as a service ? I have a issue that client connections can transfer to new or restarted pod, the service is unbalance unless I restart all the client. Any one have Ideas to resolve this issue?

I have multi shardingproxy pod to make the service HA, But cannot balance connections while add a new shardingproxy instance.

**Comment by tristaZero** [comment]
Do you think there is any good ways to balance the connections for MySQL?

**Comment by johnny2002** [comment]
just simply add the following:
spring.datasource.hikari.max-lifetime=540000

then all connections will be released and reconnection after max-lifetime.

**Comment by tristaZero** [comment]
> spring.datasource.hikari.max-lifetime=540000

This is a setting item for SpringBoot? How is it connected to the k8s?

**Comment by hisunwei** [comment]
I think it will work if restart all the client connection to relance immediately  or set diffrent ttl to rebalance slowly, but it will make the application service more complexity. 

I prefer the proxy layer can auto detect the number of node changed, and disconnect part existing connections to force the client to reconnect.

**Comment by hisunwei** [comment]
BTW:  the app service connect the proxy on k8s via Service, which act like tcp loadbalance.

**Comment by tristaZero** [comment]
Hi @hisunwei 
> BTW: the app service connect the proxy on k8s via Service, which act like tcp loadbalance.

I prefer to balance requests in the service layer above the Proxy. 
Is there any reasonable reason for ShardingProxy to refuse connections, unless users tell it to do so by some settings or SQLs.
How do you think?

**Comment by hisunwei** [comment]
@tristaZero  I am trying to add ServiceMess into k8s to resolve this issue to keep the proxy and client simple.
I am not sure what will happen if the servicemess force broken the connection.

**Comment by tristaZero** [comment]
@hisunwei Maybe some of the tests could tell us the answer. :)
