### ISSUE TITLE
关于子查询的问题

### ISSUE THREAD

**Issue by asdxiaoqex** [apache/shardingsphere#7636]
select g.create_time as createTime, g.group_id as groupId, g.parent_id as parentId, g.title as title, g.remark as remark, g.status as status, (select (case when count(1) != 0 then true else false end)
 FROM tb_user_group ug
 WHERE ug.has_deleted = 'False' and ug.user_id = 'root' and ug.group_id = g.group_id ) as selected
 FROM tb_group g
 WHERE g.has_deleted = 'False';
![image](https://user-images.githubusercontent.com/50010140/94383378-7376d800-0172-11eb-9e89-102d551e80de.png)
但是用Navicat查询是有数据的 或者 不适用sharding jdbc也是 有数据的
如图
![image](https://user-images.githubusercontent.com/50010140/94383418-8d181f80-0172-11eb-9bb3-a57f2568f935.png)

**Comment by asdxiaoqex** [comment]
![image](https://user-images.githubusercontent.com/50010140/94383450-ab7e1b00-0172-11eb-81e6-d8745cf5e38e.png)
![image](https://user-images.githubusercontent.com/50010140/94383463-b5a01980-0172-11eb-8f7d-8d9e3686bf92.png)

**Comment by asdxiaoqex** [comment]
> select g.create_time as createTime, g.group_id as groupId, g.parent_id as parentId, g.title as title, g.remark as remark, g.status as status, (select (case when count(1) != 0 then true else false end)
> FROM tb_user_group ug
> WHERE ug.has_deleted = 'False' and ug.user_id = 'root' and ug.group_id = g.group_id ) as selected
> FROM tb_group g
> WHERE g.has_deleted = 'False';
> ![image](https://user-images.githubusercontent.com/50010140/94383378-7376d800-0172-11eb-9e89-102d551e80de.png)
> 但是用Navicat查询是有数据的 或者 不使用sharding jdbc也是 有数据的
> 如图
> ![image](https://user-images.githubusercontent.com/50010140/94383418-8d181f80-0172-11eb-9bb3-a57f2568f935.png)

**Comment by strongduanmu** [comment]
@asdxiaoqex For english only, other languages ​​will not be accepted.
