### ISSUE TITLE
The aggregate function is not correct:  SELECT SUM(file_size) right1, SUM(file_size/1000/1000) right2, SUM(file_size)/1000/1000 error2, CONCAT(IFNULL(FLOOR(SUM(file_size/1000/1000)),'0'),'MB') error2 FROM s_file_info  GROUP BY project_id

### ISSUE THREAD

**Issue by xlxomg** [apache/shardingsphere#7643]
## Bug Report

**When grouping queries, if the aggregate function is not the outermost, the result is wrong.And I didn't find the description in the document (translation software)**    
![图片](https://user-images.githubusercontent.com/26641605/94401137-b483e200-019c-11eb-8d1d-e4fc2d187bf5.png)

### Which version of ShardingSphere did you use?
       4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
      jdbc and proxy both have this problem
### Example codes for reproduce this issue (such as a github link).

The test SQL is as follows, where S File Info is a sharded table:
```
SELECT SUM(file_size) right1,
SUM(file_size/1000/1000) right2,
SUM(file_size)/1000/1000 error2,
CONCAT(IFNULL(FLOOR(SUM(file_size/1000/1000)),'0'),'MB') error2
FROM s_file_info  GROUP BY project_id

```

**Comment by kimmking** [comment]
"CONCAT(IFNULL(FLOOR(SUM(file_size/1000/1000)),'0'),'MB') error2"
is not supported now.

**Comment by xlxomg** [comment]
That "SUM (file_size) / 1000/1000"? Or if the aggregate function is not in the outermost layer

**Comment by kimmking** [comment]
what's your meanings?

**Comment by xlxomg** [comment]
Is "SUM (file_size) / 1000/1000" also not supported?
In addition, my tests found that in the case of grouped queries, if the sum function still had computations around it, the results would be wrong.

**Comment by xlxomg** [comment]
@kimmking Because My English is not very good, the use of translation software, the expression is not accurate, forgive me

**Comment by kimmking** [comment]
I test in master branch:
```
mysql> select sum(id)/10 from test;
ERROR 1235 (42000): This version of ShardingProxy doesn't yet support this SQL. 'Unsupported SQL of `select sum(id)/10 from test`'
```

**Comment by xlxomg** [comment]
ShardingProxy 4.1.1 There is no indication that it is not supported, but the data is incorrect.

![图片](https://user-images.githubusercontent.com/26641605/94413938-5233dd00-01ae-11eb-996d-60df8703d330.png)
![图片](https://user-images.githubusercontent.com/26641605/94414209-a474fe00-01ae-11eb-9662-1e9a0cc6b54d.png)
