### ISSUE TITLE
How to use complex algorithm in ShardingSphere-Scaling 

### ISSUE THREAD

**Issue by xiangtianyu** [apache/shardingsphere#7658]
I have read the documents on shardingsphere.apache.org, when i try to find some demos foe scaling, i can't find any demo for complex algorithm. 
ShardingSphere-Scaling not support complex algorithm?

**Comment by Lucas-307** [comment]
@xiangtianyu Sorry, what is `complex algorithm`?

**Comment by Lucas-307** [comment]
Did you meet any porblem in ShardingSphere-Scaling?

**Comment by kimmking** [comment]
@xiangtianyu IMO, complex algorithm and ShardingSphere-Scaling is not related.
