### ISSUE TITLE
sharding-proxy integration seata error

### ISSUE THREAD

**Issue by airship-lion** [apache/shardingsphere#7659]
Refer to How to integrate sharding-proxy with seata#4882 to configure, follow the pom to add the dependency, sharding-transaction-base-seata-at is also added to the lib, add seata.conf, file.conf, registry.conf I tried putting it in the conf directory and the lib directory. At first, the error was reported and the class KeyedPoolableObjectFactory could not be found. Later, I copied the jar package corresponding to the error and entered the lib and reported

[ERROR] 11:31:14.296 [timeoutChecker_2] i.s.c.r.n.NettyClientChannelManager-0101 can not connect to 127.0.0.1:8091 cause:can not register RM,err:can not connect to services-server.
io.seata.common.exception.FrameworkException: can not register RM,err: can not connect to services-server.

The sharding-proxy used is compiled with the source code of version 4.1.1, and the version used by the seata server is seata-server-1.3.0

**Comment by airship-lion** [comment]
It runs normally now. I forgot to open the seata server before, but I found that when the transaction is started, if the program reports an error in the transaction, the branch transaction can be rolled back normally, but the program does not report an error in the transaction. I manually close a data source instance , The transactions of other data sources that are not closed cannot be rolled back normally. I do not need
Shardingsphere, directly integrate seata with multiple data sources in the program. Under the same circumstances, the transactions of other data sources can be rolled back normally.
![sharding-proxy-test](https://user-images.githubusercontent.com/27192321/94668136-4416c580-0342-11eb-9d54-bd7e227898c1.png)
![sharding-proxy-service-1](https://user-images.githubusercontent.com/27192321/94668300-71637380-0342-11eb-860c-4db9c2672af9.png)
![sharding-proxy-service-2](https://user-images.githubusercontent.com/27192321/94668416-95bf5000-0342-11eb-8647-b24f852e8d9c.png)
The above is the code for testing the proxy. When I ran, I interrupted at the end of the transaction, and then closed one of the data source instances

The code for directly integrating seata is similar. It is also a single project with multiple data sources, and seata is configured in the direct project, but it can be rolled back normally.

**Comment by cherrylzhao** [comment]
sorry I don't understand what your test mean, please tell us the architecture of your demo and the configuration file of sharding-proxy.

**Comment by airship-lion** [comment]
Several entities in my demo are in different databases. When the sharding-proxy configuration file sets the transaction to BASE mode, put the seata related jar package into the lib, and the breakpoint is at the end when the test runs , And then when I shut down one of the database instances, the transactions of the other two instances cannot be rolled back normally. But when I don't use sharding-proxy and directly connect to seata with multiple data sources, the same test, the transactions of the other two instances can be rolled back.

My sharding-proxy configuration is as follows
![sharding-proxy-server-conf](https://user-images.githubusercontent.com/27192321/94840829-a6a7b880-044b-11eb-862b-6b3fbf3284d8.png)

![sharding-proxy-shardingrule-conf](https://user-images.githubusercontent.com/27192321/94840815-9f80aa80-044b-11eb-865d-cc1fab21884e.png)

**Comment by cherrylzhao** [comment]
what the configuration of `seata.conf`? you can put some breakpoint in `SeataATShardingTransactionManager` to confirm whether SEATA BASE transaction works or not.

**Comment by airship-lion** [comment]
seata.conf client is as follows
![seata-client conf](https://user-images.githubusercontent.com/27192321/95350084-5ec4dd80-08f2-11eb-84fa-f6657b380c79.png)

seata.conf server is as follows
![seata-server conf](https://user-images.githubusercontent.com/27192321/95350760-1bb73a00-08f3-11eb-9621-6b9c50378c6b.png)

The effect is effective. I saw that the seata log is connected to the database, there are transactions, and the xid is also consistent with the undo_log table of the database, indicating that it is effective

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.
