### ISSUE TITLE
Can anyone help to submit an IDEA version checkstyle.xml ? 

### ISSUE THREAD

**Issue by lovepoem** [apache/shardingsphere#7694]
Can anyone help to submit an IDEA version checkstyle.xml ?  It seems that the latest version of IDEA only supports importing idea format checkstyle

![image](https://user-images.githubusercontent.com/827112/95005421-e678c680-062a-11eb-986a-fa8320c84374.png)

You can just export it here

![image](https://user-images.githubusercontent.com/827112/95005426-07d9b280-062b-11eb-88de-d1717b4bde82.png)

**Comment by terrymanu** [comment]
I export my setting, please see.
[Uploading ShardingSphere_Code_Style.xml…]()

**Comment by lovepoem** [comment]
It works well, I will pr this file

**Comment by kimmking** [comment]
@lovepoem  that's great, but I still suggest  DON'T Format project codes anytime and anywhere.

**Comment by lovepoem** [comment]
Closed via https://github.com/apache/shardingsphere/pull/7711
