### ISSUE TITLE
分表数量在1937张，启动时应用卡在SchemaMetaDataLoader.load

### ISSUE THREAD

**Issue by xiaowan** [apache/shardingsphere#7702]
相信这个问题不止一个使用shardingsphere的同学遇到，开发阶段浪费掉大量时间，希望官方能有一个合理的解决办法

**Comment by strongduanmu** [comment]
@xiaowan For english only, other languages ​​will not be accepted. BTW, this problem has been optimized in the master branch, you can refer to the [issue 5755](https://github.com/apache/shardingsphere/issues/5755).
