### ISSUE TITLE
shardingsphere-governance-repository-zookeeper-curator not exist

### ISSUE THREAD

**Issue by yinlimin** [apache/shardingsphere#7705]
## Question

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-governance-repository-zookeeper-curator</artifactId>
    <version>${shardingsphere.version}</version>
</dependency>

 not exist

**Comment by tristaZero** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/27757146/95542547-aa79a300-0a28-11eb-9735-9cd59970e4f8.png">
On master branch.
