### ISSUE TITLE
Add test cases for sharding strategy

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7707]
- [ ] Add test case for ShardingStrategyFactory
- [X] Add test case for StandardShardingStrategy
- [X] Add test case for ComplexShardingStrategy
- [x] Add test case for HintShardingStrategy
- [x] Add test case for NoneShardingStrategy

**Comment by jacksparrow414** [comment]
- [x] Add test case for ShardingStrategyFactory

**Comment by jacksparrow414** [comment]
only finshed first ,reopen please

**Comment by tristaZero** [comment]
Please do not use `Fixes #7707 .` If this PR does not fix the relevant issue, `Ref #7704` or `#7704` are recommended. Otherwise, the related issue will be closed with this PR merged

**Comment by jacksparrow414** [comment]
ok

**Comment by jacksparrow414** [comment]
- [x] Add test case for StandardShardingStrategy
- [x] Add test case for ComplexShardingStrategy

**Comment by jacksparrow414** [comment]
- [x] Add test case for HintShardingStrategy
- [x] Add test case for NoneShardingStrategy

All test cases are finished

**Comment by tristaZero** [comment]
@jacksparrow414 Congrats! Do you think we can close this one?

**Comment by jacksparrow414** [comment]
> @jacksparrow414 Congrats! Do you think we can close this one?

yes
