### ISSUE TITLE
SQL Text contains 'like trim(upper(concat('%','c213', '%'))',did this case supported?

### ISSUE THREAD

**Issue by z3sm** [apache/shardingsphere#7722]
## Question

Are the following cases supported?
SQL Example:
```
select * from co t
where upper(t.co) like trim(upper(concat('%','c213', '%')).
```

I got an error like this:
### line 41:31 no viable alternative at input '(upper(T.CO)likeTRIM(UPPER'

My Shardingsphere version: '4.1.1'

I Changed SQL like this, and there has no error:
```
select * from co t
where (upper(T.CO) like concat('%', #{co}, '%'))
```

What are the suggestions for support of 'trim','concat', 'upper' function？

**Comment by z3sm** [comment]
I have another case, a same error occured:

```
	SELECT
		t.KEY,
		t.VALUE
FROM T_SYS_SYSTEM_CONFIG T 
```

**Comment by kimmking** [comment]
Those statements are not supported now.

**Comment by z3sm** [comment]
> Those statements are not supported now.

By the way，whether or not broadcast-tables can be excluded a datasource?
I don't want save data to a special datasource

**Comment by kimmking** [comment]
Another question NEED to open another issue.
