### ISSUE TITLE
opentracing support 0.33 version

### ISSUE THREAD

**Issue by pengliaoye** [apache/shardingsphere#7726]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by kimmking** [comment]
Since skywalking has not supported 0.33, and there is no plan for it.

**Comment by kimmking** [comment]
s
