### ISSUE TITLE
whether or not broadcast-tables can be excluded a datasource?

### ISSUE THREAD

**Issue by z3sm** [apache/shardingsphere#7730]
## Question
I don't want save data to a special datasource。
e.g:
There is ten datasource,but one table don't need save data to a special datasource.

How did I config my sharding configuration?

**Comment by Lucas-307** [comment]
@z3sm Not Supported.

**Comment by tristaZero** [comment]
@z3sm Sorry, but I can not get your point.
Do you think #7731 is your case?

**Comment by terrymanu** [comment]
Closed because of no response anymore
