### ISSUE TITLE
Add unit tests for DataSourceConnectionUrlUtil

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#7735]
## Introduction
`DataSourceConnectionUrlUtil` is to assemble configuration items, e.g., password, database name, to get a complete and correct JDBC URL for the connection pool.

## Task
1. Create unit test class for `DataSourceConnectionUrlUtil`
2. Add assertion for `getUrl()` with `PostgreSQL` database input
3. Add assertion for `getUrl()` with `MySQL` database input
4. Raise a PR

## Tips
1. `DataNodeUtilTest` is a good example for your information
2. [Contributor guidance](https://shardingsphere.apache.org/community/cn/contribute/contributor/) is for the newbie. :-)

**Comment by cenyu00** [comment]
please assign me

**Comment by strongduanmu** [comment]
@cenyu00 Assigned, welcome to join the SS community. 😁

**Comment by tristaZero** [comment]
@strongduanmu Nice. :)
@cenyu00 Welcome!
