### ISSUE TITLE
4.1.1 版本查询列中包含子查询什么时候能够支持？

### ISSUE THREAD

**Issue by coderJL** [apache/shardingsphere#7737]
![image](https://user-images.githubusercontent.com/16283748/95668620-2864b800-0ba9-11eb-99ec-7842e03f4f0a.png)，这个地方会忽略子查询的列，导致jdbc有返回这个子查询列，但是ShardingResultSetMetaData.getColumnCount 方法只会返回非子查询的列，导致程序中的结果集获取不到子查询列的值，期待sharding能早日支持这种查询语法。

另外再咨询一个问题：
ShardingResultSetMetaData.getColumnCount() 是否可以直接返回((ResultSetMetaData) resultSetMetaData).fields.length 来解决这个问题。
![image](https://user-images.githubusercontent.com/16283748/95668980-6d8ae900-0bad-11eb-983a-1fb4958abd20.png)

**Comment by coderJL** [comment]
![image](https://user-images.githubusercontent.com/16283748/95668879-2d773680-0bac-11eb-801c-ce3e2670a695.png)

**Comment by coderJL** [comment]
![image](https://user-images.githubusercontent.com/16283748/95668985-7aa7d800-0bad-11eb-8a43-4e64e330448c.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
