### ISSUE TITLE
When will the subquery included in the query column of version 4.1.1 be supported?

### ISSUE THREAD

**Issue by coderJL** [apache/shardingsphere#7738]
![image](https://user-images.githubusercontent.com/16283748/95668620-2864b800-0ba9-11eb-99ec-7842e03f4f0a.png)，
This place can ignore the subquery column, leading to the JDBC has returned to the query sequence, but ShardingResultSetMetaData. GetColumnCount method will only return a query sequence, has resulted in the result set in the program for less than the value of the query sequence, looking forward to sharding can support the query syntax as soon as possible.

One more question：
ShardingResultSetMetaData.getColumnCount() Can I return it directly ((ResultSetMetaData) resultSetMetaData).fields.length To solve this problem。thank you
![image](https://user-images.githubusercontent.com/16283748/95668980-6d8ae900-0bad-11eb-983a-1fb4958abd20.png)

**Comment by tristaZero** [comment]
@coderJL Hi, thanks for your issue. There is better improvement in the subquery on the master branch. Could you glance at it? Plus, #6497 is a test report about subquery by @lwtdev for your reference. :)

**Comment by coderJL** [comment]
@tristaZero Thanks to the guide, #6497 I found the answer I was looking for. The community is active and the development team very awesome makes us feel more confident in using it

**Comment by tristaZero** [comment]
Thanks for your attention @coderJL and welcome join in this community if you like. The issues with `good-first-issue` or `volunteer wanted` label will be a good start. :)
