### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: isValid

### ISSUE THREAD

**Issue by YXxy1002** [apache/shardingsphere#7780]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).
i cant start my project since update to springcloud
env: srpingcloud Hoxton.SR8    springboot 2.3.2.RELEASE  shardingsphere4.1.1
exception:
![image](https://user-images.githubusercontent.com/36941654/95868408-c1a7f000-0d9c-11eb-834d-3fbb02d26d78.png)

**Comment by jingshanglu** [comment]
@YXxy1002 Can you show logic sql and actual sql?

**Comment by YXxy1002** [comment]
@jingshanglu This is the startup exception, Not when querying

**Comment by tristaZero** [comment]
@YXxy1002 Hi Could you show us more log info? As I can not get some info about ShardingSphere.

**Comment by kimmking** [comment]
https://github.com/apache/shardingsphere/pull/6002

**Comment by Orange-apples** [comment]
are you  slove the issues

**Comment by yluom** [comment]
If you are stuck with an old version of shardingsphere and have this issue, there is a fix to bypass this Connection#isValid() validation and use query validation instead: 
`@Configuration
public class DataSourceHealthConfig extends DataSourceHealthContributorAutoConfiguration {

    @Value("${whatever.custom-db-validation-query:select 1}")
    private String defaultQuery;


    public DataSourceHealthConfig(Map<String, DataSource> dataSources, ObjectProvider<DataSourcePoolMetadataProvider> metadataProviders) {
        super(dataSources, metadataProviders);
    }

    @Override
    protected AbstractHealthIndicator createIndicator(DataSource source) {
        DataSourceHealthIndicator indicator = (DataSourceHealthIndicator) super.createIndicator(source);
        if (!StringUtils.hasText(indicator.getQuery())) {
            indicator.setQuery(defaultQuery);
        }
        return indicator;
    }
}`

**Comment by bert82503** [comment]
The solution is to temporarily disable the monitoring of DB by the HealthEndpoint of Actuator.

```properties
management.health.db.enabled=false
```

[SQLFeatureNotSupportedException-isValid.log](https://github.com/apache/shardingsphere/files/12675182/SQLFeatureNotSupportedException-isValid.log)
