### ISSUE TITLE
Did the shardingshpere support sql contains 'and find_in_set()' and 'and exists()'

### ISSUE THREAD

**Issue by z3sm** [apache/shardingsphere#7789]
## Question

I got  a sql ,there has function'find_in_set' and 'and exists':
Wether or not supported this case?

```
insert into table_insert(code, bno, is_confirm)
SELECT t.code,
       ?,
       '0'
FROM table_select t where
        t.columna = ?
        AND t.columnb = ?
        AND ( find_in_set(?, t.columnc) )
        AND EXISTS 
    (SELECT 1
    FROM table_exists ts
    WHERE ts.rule_id = t.rule_id
            AND ts.stage = ?
            AND ts.model = ? )
```

**Comment by z3sm** [comment]
the 'table_isnert' and 'table_select' is broadcast-tables table

**Comment by tristaZero** [comment]
Hi @z3sm 4.x is unsupported, but the master branch for 5.x release is likely to cover this case, I guess.
Hi @strongduanmu do you think this SQL is in our `insert...select` supported list?

**Comment by strongduanmu** [comment]
> Hi @z3sm 4.x is unsupported, but the master branch for 5.x release is likely to cover this case, I guess.
> Hi @strongduanmu do you think this SQL is in our `insert...select` supported list?

@z3sm Hi, the `insert ... select ...` statement is already supported in the master branch, you can use `sharding-proxy` for testing. 😀
