### ISSUE TITLE
Test case for database getTableNamePattern

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#7800]
Hi, alll the friends in the community.

Could you do me a little favor?  We need to test different database get schemas , ex (H2, MariaDB, PostgreSQL, SQLServer).

How to  contributer?

1. First,you can follow this : https://shardingsphere.apache.org/community/en/contribute/contributor/
2. Then, you can find `org.apache.shardingsphere.infra.metadata.model.physical.jdbc.handler.DatabaseMetaDataDialectHandlerTest.java`  in  shardingSphere project
3. Last,complete todo test in `assertGetTableNamePattern()`  

You don't have to worry at all , in `assertGetTableNamePattern()`,  we have finished the test of Oracle and mysql。
You can refer to them to complete the H2, MariaDB, PostgreSQL, SQLServer, SQL92。
 If you have any other questions, please feel free to reply here. We will help you with your questions

If you complete this task, you will become an official contributor， Thank you again for your contribute。

**Comment by wwj-go** [comment]
@yu199195 hi, I am very interested in this task, please assign it to me

**Comment by yu199195** [comment]
@wwj-go  good luck for you

**Comment by c913168497** [comment]
hi, I am very interested in this task, please assign it to me

**Comment by wwj-go** [comment]
> @wwj-go good luck for you

@yu199195 Thanks，I have finished it and commit a PR， Looking forward to your suggestions！
