### ISSUE TITLE
Sharding and master slave cannot be used at the same time

### ISSUE THREAD

**Issue by Gordonman** [apache/shardingsphere#7806]
## Question
 The project is currently using the sharding function, only the table is partitioned. And we want to use the master-slave function . 
 I configured the sharding and master-slave, but the sharding did not take effect. so DB throw table does not exist exception.
I saw they are two different data source. 
 
shardingsphere.version: 4.0.0-RC2

![image](https://user-images.githubusercontent.com/30857322/96225794-36a93e80-0fc4-11eb-9697-b618b7bf5c95.png)

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by kimmking** [comment]
the ms-datasources should be independent with sharding-datasources.

see:  https://github.com/apache/shardingsphere/blob/4.1.1/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-master-slave.yaml

**Comment by Gordonman** [comment]
> the ms-datasources should be independent with sharding-datasources.
> 
> see: https://github.com/apache/shardingsphere/blob/4.1.1/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-master-slave.yaml

My shardingsphere version is 4.0.0-RC2,  I didn't find 'masterSlaveRules' , only saw 'masterslave'

**Comment by Gordonman** [comment]
Can someone help me answer this question in detail

**Comment by yu199195** [comment]
@Gordonman  hi， you can follow this ： https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/configuration/config-yaml/#data-sharding--read-write-split    

any question？ and we'll close that later。

**Comment by Gordonman** [comment]
> @Gordonman hi， you can follow this ： https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/configuration/config-yaml/#data-sharding--read-write-split
> 
> any question？ and we'll close that later。

ok , I see. thanks
