### ISSUE TITLE
org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.simple.ParameterMarkerExpressionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment

### ISSUE THREAD

**Issue by hugohoo** [apache/shardingsphere#7823]
### The error occurred while setting parameters
SQL: SELECT    * FROM T_CODE   WHERE  ? BETWEEN CODE_START AND CODE_END
### Cause: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.expr.simple.ParameterMarkerExpressionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment

**Comment by strongduanmu** [comment]
@hugohoo Which version did you use? In addition, can you provide the sharding rule configuration and a case to reproduce this exception?

**Comment by kimmking** [comment]
How to reproduce this issue? @hugohoo

**Comment by terrymanu** [comment]
Closed because of no response anymore

**Comment by haidafus** [comment]
had the question been resolve d
