### ISSUE TITLE
Optimization scaling importer performance

### ISSUE THREAD

**Issue by avalon5666** [apache/shardingsphere#7836]
We can merge and batch execute the rows change to optimization performance.

## Merge

insert + insert -> insert(dumper back off)
insert + update -> insert 
insert + delete -> delete
update + insert -> insert(dumper back off)
update + update -> update
update + delete -> delete
delete + insert -> insert
delete + update -> update(dumper back off)
delete + delete -> delete

## Batch Execute

1. delete
2. insert
3. update

**Comment by Lucas-307** [comment]
Good job.

**Comment by Lucas-307** [comment]
Case 2: `insert + update -> insert`

If the program occur exception after a data inserted, and then this data updated.
By resume from break-point dumper back off, program received `insert + update`, which will merge to `insert`.
This data will **ignored** by `INSERT IGNORE` sql .

So maybe you should use `REPLACE INTO` sql or other plans.
