### ISSUE TITLE
Add MariaDBDatabaseMetaDataDialectHandlerTest

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#7840]
Hi, alll the friends in the community.

Could you do me a little favor?  We need to add test different database dialect handler , ex (H2, MariaDB, PostgreSQL, SQLServer).

How to  contributer?

1. First,you can follow this : https://shardingsphere.apache.org/community/en/contribute/contributor/
2. Then, you can new MariaDBDatabaseMetaDataDialectHandlerTest in shardingsphere-infra-common 
3. Then, Please extends AbstractDatabaseMetaDataDialectHandlerTest
4. Last,complete to add assertGetSchema(), assertFormatTableNamePattern() ,assertGetQuoteCharacter()  

You don't have to worry at all , You can refer to MySQLDatabaseMetaDataDialectHandlerTest 
 If you have any other questions, please feel free to reply here. We will help you with your questions

If you complete this task, you will become an official contributor， Thank you again for your contribute。

**Comment by zgat** [comment]
i want do it

**Comment by jinliang11** [comment]
i want it

**Comment by Ouyuone** [comment]
I want to add this , please assign me, thanks

**Comment by yu199195** [comment]
@zgat welcome to join us  !     @jinliang11 @Ouyuone  Yous  can stay focused on the next task

**Comment by Ouyuone** [comment]
how long time release the next task

**Comment by yu199195** [comment]
next week !

**Comment by Ouyuone** [comment]
ok wait for you

**Comment by zgat** [comment]
@yu199195 thanks you for the trust

**Comment by yu199195** [comment]
@zgat   its very easy。 pls complete as soon！

**Comment by zgat** [comment]
@yu199195 ok
