### ISSUE TITLE
Add SQL92DatabaseMetaDataDialectHandlerTest

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#7843]
Hi, alll the friends in the community.

Could you do me a little favor?  We need to add test different database dialect handler , ex (H2, MariaDB, PostgreSQL, SQLServer).

How to  contributer?

1. First,you can follow this : https://shardingsphere.apache.org/community/en/contribute/contributor/
2. Then, you can new SQL92DatabaseMetaDataDialectHandlerTest in shardingsphere-infra-common 
3.  Please extends AbstractDatabaseMetaDataDialectHandlerTest
4. complete to add assertGetSchema(), assertFormatTableNamePattern() ,assertGetQuoteCharacter()  

You don't have to worry at all , You can refer to MySQLDatabaseMetaDataDialectHandlerTest 
 If you have any other questions, please feel free to reply here. We will help you with your questions

If you complete this task, you will become an official contributor， Thank you again for your contribute。

**Comment by LikeElephantintheforest** [comment]
i want it,plz... That is something I SERIOUSLY need to do!

**Comment by yu199195** [comment]
@LikeElephantintheforest  welcome to join us！

**Comment by LikeElephantintheforest** [comment]
thanks ,It should be finished by next week at the latest.
