### ISSUE TITLE
Add  SQLServerDatabaseMetaDataDialectHandlerTest

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#7844]
Hi, alll the friends in the community.

Could you do me a little favor?  We need to add test different database dialect handler , ex (H2, MariaDB, PostgreSQL, SQLServer).

How to  contributer?

1. First,you can follow this : https://shardingsphere.apache.org/community/en/contribute/contributor/
2. Then, you can new SQLServerDatabaseMetaDataDialectHandlerTestin shardingsphere-infra-common 
3. Please extends AbstractDatabaseMetaDataDialectHandlerTest
4. Complete to add assertGetSchema(), assertFormatTableNamePattern() ,assertGetQuoteCharacter()  

You don't have to worry at all , You can refer to MySQLDatabaseMetaDataDialectHandlerTest 
 If you have any other questions, please feel free to reply here. We will help you with your questions

If you complete this task, you will become an official contributor， Thank you again for your contribute。

**Comment by liuyueve** [comment]
i want it

**Comment by zhengdegu** [comment]
I want it,too

**Comment by yu199195** [comment]
@zhengdegu  welcome to join us！
