### ISSUE TITLE
ShardingResultSet 怎么支持getNString方法

### ISSUE THREAD

**Issue by moyuguixiong** [apache/shardingsphere#7846]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by tristaZero** [comment]
Hi @moyuguixiong welcome.
Firstly, I suggest you'd better re-title this issue in English.
Secondly, this issue did not give us too much valuable info. Please elaborate on this issue. :)

**Comment by terrymanu** [comment]
For English only
