### ISSUE TITLE
Does sharding-jdbc support springAOP global transaction configuration

### ISSUE THREAD

**Issue by shenHaoRanDe** [apache/shardingsphere#7855]
Does sharding-jdbc support springAOP global transaction configuration? I read the official website document and GitHub case, and there is only one annotation

**Comment by yu199195** [comment]
sharding is Works on multiple  database， However spring aop only one database。If you want to use distributed transactions， pls integration XA and base transaction

**Comment by kimmking** [comment]
If you means "springAOP global transaction" as database local tx, the anwser is yes, shardingsphere support it.

**Comment by shenHaoRanDe** [comment]
<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="shardingDataSource"/>
    </bean>

    
    <tx:advice id="txAdvice" transaction-manager="transactionManager">
        <tx:attributes>
            <tx:method name="save*" propagation="REQUIRED" />
            <tx:method name="add*" propagation="REQUIRED"/>
            <tx:method name="delete*" propagation="REQUIRED"/>
            <tx:method name="update*" propagation="REQUIRED"/>
            <tx:method name="insert*" propagation="REQUIRED"/>
            <tx:method name="create*" propagation="REQUIRED"/>
            <tx:method name="deal*" propagation="REQUIRED"/>
            <tx:method name="do*" propagation="REQUIRED"/>
            <tx:method name="set*" propagation="REQUIRED"/>
            <tx:method name="change*" propagation="REQUIRED"/>
            <tx:method name="*" read-only="true"/>
        </tx:attributes>
    </tx:advice>

    
    <aop:config>
        <aop:pointcut id="allServiceMethod" expression="execution(* com.shen.service..*.*(..))"/>
        <aop:advisor advice-ref="txAdvice" pointcut-ref="allServiceMethod"/>
    </aop:config>

**This kind of global transaction configuration, how to integrate sharding-jdbc distributed transaction, is there an example?**

**Comment by shenHaoRanDe** [comment]
@kimmking How to configure global distributed transactions in XML files instead of adding annotations to methods
