### ISSUE TITLE
 SpringAOP global distributed transaction configuration

### ISSUE THREAD

**Issue by shenHaoRanDe** [apache/shardingsphere#7859]
....
<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
    <property name="dataSource" ref="shardingDataSource"/>
</bean>

<tx:advice id="txAdvice" transaction-manager="transactionManager">
    <tx:attributes>
        <tx:method name="save*" propagation="REQUIRED" />
        <tx:method name="add*" propagation="REQUIRED"/>
        <tx:method name="delete*" propagation="REQUIRED"/>
        <tx:method name="update*" propagation="REQUIRED"/>
        <tx:method name="insert*" propagation="REQUIRED"/>
        <tx:method name="create*" propagation="REQUIRED"/>
        <tx:method name="deal*" propagation="REQUIRED"/>
        <tx:method name="do*" propagation="REQUIRED"/>
        <tx:method name="set*" propagation="REQUIRED"/>
        <tx:method name="change*" propagation="REQUIRED"/>
        <tx:method name="*" read-only="true"/>
    </tx:attributes>
</tx:advice>

<aop:config>
    <aop:pointcut id="allServiceMethod" expression="execution(* com.shen.service..*.*(..))"/>
    <aop:advisor advice-ref="txAdvice" pointcut-ref="allServiceMethod"/>
</aop:config>
**This kind of global transaction configuration, how to integrate sharding-jdbc distributed transaction, is there an example?**

**Comment by yu199195** [comment]
@shenHaoRanDe  you can follow this ： https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/usage/transaction/

**Comment by shenHaoRanDe** [comment]
@yu199195 I have seen this, there is no configuration for global transactions, only one type of configuration is annotation

**Comment by shenHaoRanDe** [comment]
@yu199195 Is there any other configuration method besides adding annotations to the method?
