### ISSUE TITLE
sharding proxy can support zookeeper, sharding rule can dynamic modify ?

### ISSUE THREAD

**Issue by fafeidou** [apache/shardingsphere#7862]

**Comment by fafeidou** [comment]
i want to see blog help me , thanks!

**Comment by yu199195** [comment]
of course， you can

**Comment by fafeidou** [comment]
> of course， you can

i try it,but don't modify ,such as 【show tables】 command

**Comment by yu199195** [comment]
show tables ，How does it relate to shardingRule？

**Comment by fafeidou** [comment]
add bind tablas ,but mysql client [show tables] not shows

**Comment by kimmking** [comment]
> add bind tablas ,sharding rule can update, but mysql client [show tables] not shows,

I don't think so.
Can you give your steps and config to reproduce it？

**Comment by fafeidou** [comment]
10月 22, 2020 9:26:56 下午 com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
严重: Could not dispatch event: org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema@5cbb84b1 to public synchronized void org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema.renew(org.apache.shardingsphere.orchestration.core.common.event.ShardingRuleChangedEvent)
10月 22, 2020 9:26:56 下午 com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
严重: Could not dispatch event: org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema@5cbb84b1 to public synchronized void org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema.renew(org.apache.shardingsphere.orchestration.core.common.event.ShardingRuleChangedEvent)
10月 22, 2020 9:26:56 下午 com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
严重: Could not dispatch event: org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema@5cbb84b1 to public synchronized void org.apache.shardingsphere.shardingproxy.backend.schema.impl.ShardingSchema.renew(org.apache.shardingsphere.orchestration.core.common.event.ShardingRuleChangedEvent)

**Comment by fafeidou** [comment]
> > add bind tablas ,sharding rule can update, but mysql client [show tables] not shows,
> 
> I don't think so.
> Can you give your steps and config to reproduce it？

`select *` is not return,and `select id` can show , the code `org.apache.shardingsphere.shardingproxy.backend.response.query.QueryHeader` is empty ，i debug it

**Comment by kimmking** [comment]
Of course, it has been fixed in 5.0.0
