### ISSUE TITLE
Replace com.google.common.base.Charsets with java.nio.charset.StandardCharsets in CuratorZookeeperRepository.java

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#7883]
Because of the use of Guava’s Charsets class, which has been obsolete since JDK7, we should consider replacing it with 
`java.nio.charset.StandardCharsets`

- `org.apache.shardingsphere.governance.repository.zookeeper.CuratorZookeeperRepository`

**Comment by yangtaihsou** [comment]
I claim this issue.

**Comment by yangtaihsou** [comment]
I'm working on this issue. It will finished in oct 22.

**Comment by menghaoranss** [comment]
@yangtaihsou welcome
