### ISSUE TITLE
Replace com.google.common.base.Charsets with java.nio.charset.StandardCharsets in EtcdRepository.java

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#7884]
Same as #7883 

- `org.apache.shardingsphere.governance.repository.etcd.EtcdRepository`
- `org.apache.shardingsphere.governance.repository.etcd.EtcdRepositoryTest`

**Comment by zilongTong** [comment]
I claim this issue.I will fix it before October 28.
