### ISSUE TITLE
org.postgresql.util.PSQLException: Expected command status BEGIN, got null 0

### ISSUE THREAD

**Issue by zhuxiao-java** [apache/shardingsphere#7898]
- I encountered a problem when testing and using sharding-proxy, pgsql database, transaction type opened XA, configuration one master and one cluster, configuration copied from the official website, version 4.1.1, using native jdbc connection, once the connection is set .setAutoCommit(false); After executing an insert statement jdbc will report an error, the jdbc error message is as follows

- There is no problem with the query, and no problem without opening the transaction. The springboot transaction reports this error. I want to try with the native jdbc. I have tried both proxy.transaction.type configuration XA and LOCAL.

`org.postgresql.util.PSQLException: Expected command status BEGIN, got null 0.
	at: org.postgresql.core.v3.QueryExecutorImpl$1.handleCommandStatus(QueryExecutorImpl.java:536)
	at: org.postgresql.core.v3.QueryExecutorImpl.interpretCommandStatus(QueryExecutorImpl.java:2492)
	at: org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2127)
	at: org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at: org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at: org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at: org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at: org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at: com.geok.utils.db.DataBase.update(DataBase.java:379)
	at: com.geok.thirteen.test.TestApplication.main(TestApplication.java:23)
`

**Comment by yu199195** [comment]
if  you use XA tarnasaction,  Local transactions can no longer be used for nested purposes  ,   because  XA transaction is begin, not end..
