### ISSUE TITLE
SQL rewrite error, " SELECT COUNT(DISTINCT(order_serial)) counts ... " rewite  to " SELECT DISTINCT order_serial count ... "

### ISSUE THREAD

**Issue by blppz** [apache/shardingsphere#7906]
Hey my friends
I use sharding-jdbc for springboot 4.1.0
and i get this bug, logic sql is: 
`SELECT COUNT(DISTINCT(order_serial)) counts
FROM access_record
WHERE enter_time BETWEEN ? AND ?`
actual sql is:
`SELECT DISTINCT order_serial counts
FROM access_record_20201001
WHERE enter_time BETWEEN ? AND ?`
so, i got an wrong answer, I can avoid this problem, but I hope you can fix this bug, ths

**Comment by avalon5666** [comment]
The backend database is MySQL or PostgreSQL?

**Comment by tristaZero** [comment]
Hi @blppz 
Firstly, the actual SQL is expected, since ShardingSphere will calculate the `count()` by itself.
As @avalon5666 said, we did not know what the concrete problem or exception is.

**Comment by terrymanu** [comment]
Closed because of no response anymore

**Comment by williamXinCC** [comment]
I got the same problem

**Comment by strongduanmu** [comment]
@williamXinCC Can you submit a new issue to report this exception?
