### ISSUE TITLE
can sharding-jdbc-xxx support spring-frame 5.x?

### ISSUE THREAD

**Issue by MidnightFiend** [apache/shardingsphere#7917]
## Question
when i create new product with 
```
<!-- https://mvnrepository.com/artifact/org.apache.shardingsphere/sharding-jdbc-core -->
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-namespace</artifactId>
    <version>4.1.1</version>
</dependency>
```

at the same time, our company require to use openjdk11, so i should use spring version >5.1.x

i use dependency 
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>2.2.10-RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter</artifactId>
</dependency>
```

it dependency springframework version 5.2.9

when i mvn package the project, i found mvn dependency:tree 
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.2.10.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.2.10.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:4.3.16.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-aop:jar:4.3.16.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-beans:jar:4.3.16.RELEASE:compile

i had traced which one import 4.3.16 , then i found in shardingsphere-4.1.1-pom :
<springframework.version>[4.3.6.RELEASE,5.0.0.M1)</springframework.version>

it may control springframework version less than 5.x.

is there any way, i can skip it?

**Comment by avalon5666** [comment]
You can try to upgrade the version in the sharding-jdbc-namespace project, and test compatibility.

**Comment by MidnightFiend** [comment]
> You can try to upgrade the version in the sharding-jdbc-namespace project, and test compatibility.

is 4.1.1 the lastest version for sharding-jdbc ?

**Comment by avalon5666** [comment]
5.x coming soon

**Comment by MidnightFiend** [comment]
3Q! but because of deadline, i may build without springboot now.
