### ISSUE TITLE
single db transaction cant rollback

### ISSUE THREAD

**Issue by camelweiming** [apache/shardingsphere#7920]
## Bug Report
  TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
        transactionTemplate.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRED);
        transactionTemplate.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);
        ResultDTO<String> res = transactionTemplate.execute(transactionStatus -> {
            try {
                insert(xxx);
                insert(xxx);
                return xxxx;
            } catch (Throwable e) {
                transactionStatus.setRollbackOnly();
                return xxx
            }
        });

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by avalon5666** [comment]
Pls commit issue with bug report template, This can help us diagnose problems.

**Comment by terrymanu** [comment]
Closed because of no response anymore
