### ISSUE TITLE
How does Sharding-Proxy force routing to the master database?

### ISSUE THREAD

**Issue by daishicheng** [apache/shardingsphere#7921]

**Comment by tristaZero** [comment]
I guess [SCTL (Sharding-Proxy control language)](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-proxy/usage/) is the answer for this issue.

**Comment by daishicheng** [comment]
> I guess [SCTL (Sharding-Proxy control language)](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-proxy/usage/) is the answer for this issue.

Do I need to splice the SCTL prefix before the SQL statement? Is this unfriendly in business code?

**Comment by tristaZero** [comment]
@daishicheng Yep, the instruction will show you more details.
It is business-friendly to choose ShardingProxy for your business. Also we welcome your company appears in [the user list](https://github.com/apache/shardingsphere/issues/234) of ShardingSphere community.

**Comment by daishicheng** [comment]
> @daishicheng Yep, the instruction will show you more details.
> It is business-friendly to choose ShardingProxy for your business. Also we welcome your company appears in [the user list](https://github.com/apache/shardingsphere/issues/234) of ShardingSphere community.

@tristaZero Thanks for your answer.
