### ISSUE TITLE
Configuration error in test-engine/performance-test page

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7942]
There is still use old configuration in this page, we need to update them to new version

**Comment by SteNicholas** [comment]
@terrymanu Anyone focus on this issue?

**Comment by lemon6061** [comment]
Please assign to me

**Comment by strongduanmu** [comment]
> Please assign to me

@lemon6061 Welcome to the SS community! 😀

**Comment by lemon6061** [comment]
Sorry I don’t have time to complete this task, please assign it to someone else
