### ISSUE TITLE
Unsupported SQL of `RENAME TABLE`

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7967]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute SQL correctly:

`rename table t_order order;`

### Actual behavior

ERROR 1235 (42000): This version of ShardingProxy doesn't yet support this SQL. 'Unsupported SQL of `rename table t_order order`'

Errors in the log:

```
line 1:7 no viable alternative at input 'renametable'
line 1:7 no viable alternative at input 'renametable'
line 1:0 no viable alternative at input 'rename'
line 1:0 mismatched input 'rename' expecting CREATE
```

### Reason analyze (If you can)

Parse error.

**Comment by strongduanmu** [comment]
@tuohai666 Refer to the official [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/rename-table.html), `RENAME TABLE Statement` must contain the `TO` keyword.

```sql
RENAME TABLE
    tbl_name TO new_tbl_name
    [, tbl_name2 TO new_tbl_name2] ...
```
You can try the following SQL:

```sql
rename table t_order TO `order`;
```

**Comment by jingshanglu** [comment]
@tuohai666 `rename table t_order order;` the sql is illegal, and `To`  is necessary, plz use "rename table t_order TO `order`;", now master branch is ok.
