### ISSUE TITLE
Check whether throw SQLParsingException only in SQL parser engine

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#7969]
Please make sure catch accurate exception only in class `ShardingSphereSQLParserEngine`, search TODO to confirm the exception catch logic.

**Comment by SteNicholas** [comment]
@tristaZero @jingshanglu do you have any confirm update about this issue?

**Comment by tristaZero** [comment]
I guess @jingshanglu did some investigation. Let us wait for his summary.

**Comment by TeslaCN** [comment]
Any update here? Could we finish this in 5.1.1?
