### ISSUE TITLE
can not hit specific table by hash

### ISSUE THREAD

**Issue by wuxingye** [apache/shardingsphere#7980]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
i have two table topic_0, topic_1, when i search by id, it search the two table
### Actual behavior
just search specific table by hash which is hit

**Comment by avalon5666** [comment]
Pls reference sharding rule documents.

**Comment by wuxingye** [comment]
spring:
  shardingsphere:
    sharding:
      tables:
        topic:
          actual-data-nodes: live-content.topic_$->{0..1}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: topic_$->{user_id % 2}
        comment:
          actual-data-nodes: live-content.comment_$->{0..7}
          table-strategy:
            inline:
              sharding-column: topic_id
              algorithm-expression: comment_$->{topic_id % 8}
        game:
          actual-data-nodes: live-content.game
        game_ext:
          actual-data-nodes: live-content.game_ext
        live:
          actual-data-nodes: live-content.live
        slideshow:
          actual-data-nodes: live-content.slideshow
        star:
          actual-data-nodes: live-content.star
        tag:
          actual-data-nodes: live-content.tag
        team:
          actual-data-nodes: live-content.team

**Comment by avalon5666** [comment]
It will route to all table without sharding key in query sql.

**Comment by wuxingye** [comment]
An optimization method is to search attach the route key, such as user_id above
