### ISSUE TITLE
Navicat connect error: Unknown error

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7982]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Compat with Navicat.

### Actual behavior

When use Navicat connect ShardingSphere-Proxy, the client promp "10060 Unknown error".

![111](https://user-images.githubusercontent.com/24643893/97689258-43ef1e80-1ad6-11eb-8802-b91256cc6680.png)

**Comment by SteNicholas** [comment]
@tuohai666 , about this issue, do you recently have any pull request to fix the problem above mentioned?

**Comment by tuohai666** [comment]
Hi @SteNicholas , no plan yet. I can't reproduce this problem for I don't have a Navicat.

**Comment by tuohai666** [comment]
@lidonghai11 , can you provide the ShardingSphere log and tcpdump package for this error?

**Comment by lidonghai11** [comment]
Navicat Premium 15.0.17 @tuohai666

**Comment by tuohai666** [comment]
Thanks donghai.

Anyone can help to reproduce this problem via Navicat Premium 15.0.17?

**Comment by RaigorJiang** [comment]
The Navicat connection problem has been fixed in another issue, please refer to: https://github.com/apache/shardingsphere/issues/11994.
