### ISSUE TITLE
SQLParserConfiguration Unable to register，throw exception Cannot support database type Mysql

### ISSUE THREAD

**Issue by maxlange** [apache/shardingsphere#7990]
## Bug Report
as title,when i start with sharding-jdbc-spring-boot-starter4.1.0,cause the exception,but in my project the mysql parser jar is exits
enviroment: OS WIN10,jdk 1.8,druid 1.1.22

**Comment by SteNicholas** [comment]
@maxlange , could you provide exception stack information?

**Comment by terrymanu** [comment]
Closed because of no response.
