### ISSUE TITLE
Why 'rangeAlgorithmClassName' throw NullPointerException

### ISSUE THREAD

**Issue by XiaoleLee** [apache/shardingsphere#7997]
Sharding Proxy 4.1.0

My yaml config :

![image](https://user-images.githubusercontent.com/9973801/97781432-4630a600-1bc6-11eb-86c0-ecad4594db83.png)

Exception:

![image](https://user-images.githubusercontent.com/9973801/97781462-84c66080-1bc6-11eb-979e-26a20512e3d2.png)

Code:

![image](https://user-images.githubusercontent.com/9973801/97781543-2e0d5680-1bc7-11eb-9964-5d00c47ef7bf.png)

Is this mean 'rangeAlgorithmClassName' can not be use alone?

**Comment by SteNicholas** [comment]
@XiaoleLee , `rangeAlgorithmClassName` should be used with `preciseAlgorithmClassName`. You could add this config to yaml config.

**Comment by XiaoleLee** [comment]
> @XiaoleLee , `rangeAlgorithmClassName` should be used with `preciseAlgorithmClassName`. You could add this config to yaml config.

Many thanks for helping me，this case can be closed now.Thanks again~
