### ISSUE TITLE
Discuss Merge StatementSQLVisitor into same one or use lots of minor visitor to handle SQL segment

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8003]
Current situation:
The main DML logic is in origin StatementSQLVisitor because DDL use select statement too. 

There are tow way to enhance here:
1. Merge all visitors' logic into same one. 

The advantage is the generated visitor by ANTLR is all in one;
The disadvantage is the all in one class is too large (over 3000 lines).

2. Use lots of minor visitor to handle SQL segment, one visitor only handle related segment. The visitors can split by different levels, such DMLVisitor -> SelectVisitor -> WhereVisitor -> TableNameVisitor.

The advantage is better to reuse code fragment;
The disadvantage the parent visitor include all empty method, the minor visitor can implement part interest method only.

Which one is better, please advice me.

**Comment by SteNicholas** [comment]
@terrymanu IMO, the second way is better because from the interface level, the second way is more elegant and the code structure is more intuitive. In the first way, merging all visitors' logic into same one, the code is very unintuitive and its readability is also very bad.

**Comment by jingshanglu** [comment]
@terrymanu The first way does make the class larger, but it brings the advantages of simple structure and easy reuse the visitor function. For readability, I think only one class is easier to read,  and no need to transform class to see the code.

**Comment by strongduanmu** [comment]
@terrymanu I think the first way is more convenient to use, and there is no need to worry about calls between different statements. In the second way, we may design a reasonable structure at the beginning to facilitate the reuse of code blocks. But with the support of more statements, we will find that one statement block calls another statement block, which makes us have to repeatedly rewrite these codes.

**Comment by terrymanu** [comment]
Sorry, I forget to close this issue. The current codes just follow the first way, that's all right.
