### ISSUE TITLE
update the sharding key

### ISSUE THREAD

**Issue by daishicheng** [apache/shardingsphere#8006]
We are trying to use shardingsphere and encountered the problem of not being able to update the sharding key. I know this is the specification of shardingsphere, but I want to discuss whether it can support the function of updating the sharding key. Under normal circumstances, the solution to the inability to update the shard is to delete it and then add it again, but this method has a great impact on the transformation of the business, can you consider using the method of updating the partition key in mysql to support this function?

**Comment by tristaZero** [comment]
Hi @daishicheng 
I assume [#7703](https://github.com/apache/shardingsphere/issues/7703) is your concern, isn't it?

**Comment by daishicheng** [comment]
> 嗨@daishicheng
> 我认为[＃7703](https://github.com/apache/shardingsphere/issues/7703)是您的关注点，对吗？

@tristaZero Yes, just like mysql can support updating partition keys. Shardingsphere can provide greater flexibility.

**Comment by kimmking** [comment]
It has no plan for it.
