### ISSUE TITLE
I want to use the Shard-Proxy's read-write separation function, which has two schemas in a data source. Can I implement the same data source with two schemas?

### ISSUE THREAD

**Issue by 1iuyunpeng** [apache/shardingsphere#8028]
## Question
I want to use the Shard-Proxy's read-write separation function, which has two schemas in a data source. Can I implement the same data source with two schemas?

**Comment by cherrylzhao** [comment]
can you provide a demo configuration to explain your requirement?

**Comment by kimmking** [comment]
I don't understand.
