### ISSUE TITLE
Is it able to specify a special SQL to be executed in master node when using master-slave sharding?

### ISSUE THREAD

**Issue by Honglaisenburg** [apache/shardingsphere#8032]
The problem I got is as follow:
I have two databases, by use of shardingJdbc master-slave configuration, most part is working well.

The only issue is : There is one special SQL, defined to call a stored procedure which is actually doing some update command inside. Since the SQL format is written in "SELECT MY_PROCEDURE()" format, shardingJdbc routed the SQL to the slave database node and we got an error because the slave instance is read only and not able to execute any update command at all.

So I am thinking: how can I use configurations or some special format to bypass the default master-slave route mechanism, and make sure my special select-like SQL to send to master node instead ?

Thanks.

**Comment by tristaZero** [comment]
Hi @Honglaisenburg
If you use shardingJDBC, I supposed [hintManger](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/hint/) could give you some hints.
