### ISSUE TITLE
ClassCastException. parameter corresponding to the built-in function field

### ISSUE THREAD

**Issue by nnxiaod** [apache/shardingsphere#8034]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-jdbc

### Expected behavior
correct pagination

### Actual behavior
Exception：cannot cast String to Integer

### Example codes for reproduce this issue (such as a github link).

I found this when I was debugging

parameters(ArrayList):
```
0-"BBB"
1-"2020-10-28"
2-0
3-2
```

SQL-1 
```
select * from test_table where code = #{code} and join_time >= #{joinDate} limit #{startRow}, #{pageSize}
```
SelectStatement -> LimitStatement -> offset -> paramterIndex -> 2
SelectStatement -> LimitStatement -> rowCount -> paramterIndex -> 3

It goes well.

SQL-2
```
select * from test_table where code = #{code} and date(join_time) = #{joinDate} limit #{startRow}, #{pageSize}
```
SelectStatement -> LimitStatement -> offset -> paramterIndex -> 1
SelectStatement -> LimitStatement -> rowCount -> paramterIndex -> 2

Get into trouble.

The difference is that the second SQL uses the built-in function ```date```
It does not recognize the parameter corresponding to the built-in function field, which causes the parameter to not map correctly.
It tries to convert 2020-10-28 to an integer and then throws a ClassCastException

I don't know if built-in functions are supported.

**Comment by tristaZero** [comment]
Hi @nnxiaod I suppose we fixed in the coming release 5.0.0-alpha.
@jingshanglu Could you give it a double-check?

**Comment by jingshanglu** [comment]
@tristaZero @nnxiaod  I have checked it ,it is ok on  release `5.0.0-alpha`.

**Comment by tristaZero** [comment]
Nice :) @jingshanglu
