### ISSUE TITLE
存在addtime字段，解析sql会报空指针

### ISSUE THREAD

**Issue by chenrtoken** [apache/shardingsphere#8036]
![图片](https://user-images.githubusercontent.com/35092830/98205113-784d5980-1f72-11eb-9577-73086d405975.png)

**Comment by chenrtoken** [comment]
line 1:15 no viable alternative at input 'addtimefrom'
line 1:15 no viable alternative at input 'addtimefrom'
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException
### The error may exist in com/tnar/model/mapper/TParkInfoMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select addtime from t_park_info limit 1
### Cause: java.lang.NullPointerException

**Comment by tristaZero** [comment]
Hi @chenrtoken 
Please modify the title of this issue in English, thx.
@jingshanglu A test is needed here, thx.

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
