### ISSUE TITLE
数据库bit或者int值为null， shardingjdbc中的ResultSetUtil将其转换为false或0

### ISSUE THREAD

**Issue by white-yz** [apache/shardingsphere#8044]
您好，使用jpa findAll查询时户会将结果null值转换为默认值，应该怎么处理呢

使用版本：sharding-jdbc-spring-boot-starter 4.0.0-RC1 +  jpa

问题描述：使用findAll查询时会将结果布尔 `null值转换为false，整型null值转换为0，阅读源码后，发现大量使用boolean和int等基本数据类型，不甚求解，本人菜鸟一枚，虚心请教

![1604626866(1)](https://user-images.githubusercontent.com/44742616/98316233-f7936980-2014-11eb-8b8b-18212d408691.jpg)

![222](https://user-images.githubusercontent.com/44742616/98316399-4e993e80-2015-11eb-81f8-9dedd93ce9b0.png)

![333](https://user-images.githubusercontent.com/44742616/98316432-5a850080-2015-11eb-9985-2cbbef521fca.png)

**Comment by kimmking** [comment]
English only here.
Can you translate your title and content?

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
