### ISSUE TITLE
show variables / binlog / master can only get one of the databases

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#8053]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0 master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Get the correct result.

### Actual behavior

Only get the information from on of the databases

### Reason analyze (If you can)

Current implementation

**Comment by terrymanu** [comment]
Close because of staled.
