### ISSUE TITLE
information_schema cannot be used to query database tables in mysql

### ISSUE THREAD

**Issue by GisDeng** [apache/shardingsphere#8069]
here is my application.yml
![image](https://user-images.githubusercontent.com/30002851/98440130-c0ff4100-2131-11eb-8b33-a82d267a8545.png)

`shardingsphere:
    datasource:
      names: d1
      d1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://ip:3306/db?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
        username: username
        password: password
    sharding:
      tables:
        user:
          actual-data-nodes: d1.user_$->{0..9}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: user_$->{user_id % 10}
    props:
      sql:
        show: true`

When I use this sql to query the database for all table names:
`select table_name ,create_time , engine, table_collation, table_comment
from information_schema.tables
where table_schema = (select database()) order by create_time desc`

A bug appears that does not exist with table 'tables'

The prefix INFORMATION_SCHEMA appears to have been removed from SQL

**Comment by terrymanu** [comment]
Duplicate with #2235
