### ISSUE TITLE
Is sharding-proxy support R2DBC ?

### ISSUE THREAD

**Issue by Jiar** [apache/shardingsphere#8073]
Is sharding-proxy support R2DBC ?

**Comment by terrymanu** [comment]
I don't know. What is the different between R2DBC and common JDBC in database protocol?

**Comment by Jiar** [comment]
It's Reactive Relational Database Connectivity. But, I'm not clear what's the different in database protocol layer between them.

[Here is R2DBC's official website](https://r2dbc.io/)

**Comment by terrymanu** [comment]
Could you try to understand the different between R2DBC and raw JDBC by database protocol layer,
or maybe just try it to get the initial estimate result?

**Comment by kimmking** [comment]
@Jiar hi, Jiar,
You can use r2dbc in your application system and connecting to Proxy just as a mysql server.

**Comment by Jiar** [comment]
> maybe just try it to get the initial estimate result?

Sorry, I'm not understand the different between R2DBC and raw JDBC now. I'm just use R2DBC to connect the sharding-proxy, but not success.


> @Jiar hi, Jiar,
> You can use r2dbc in your application system and connecting to Proxy just as a mysql server.

I've tried, but I haven't succeeded. Maybe my Sharding-Proxy configuration is wrong, so I'll try again.

**Comment by Jiar** [comment]
Thank you very mush!

I made it(`spring-webflux + r2dbc + sharding-proxy`) !
