### ISSUE TITLE
Can the shardingColumn for InlineShardingStrategy in The shardingProxy be a string (it's not a numeric string)?

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8081]

**Comment by tristaZero** [comment]
There are many cases for `shardingColumn`, but generally my answer ti YES.
``
/**
 * Sharding value for precise.
 */
@RequiredArgsConstructor
@Getter
@ToString
public final class PreciseShardingValue<T extends Comparable<?>> implements ShardingValue {
    
    private final String logicTableName;
    
    private final String columnName;
    
    private final T value; // Here it is T
}
```

**Comment by duzhanfei** [comment]
thank you very much.



At 2020-11-09 10:38:13, "Juan Pan(Trista)" <notifications@github.com> wrote:

There are many cases for shardingColumn, but generally my answer ti YES.
``
/**

Sharding value for precise.
*/
@RequiredArgsConstructor
@getter
@tostring
public final class PreciseShardingValue<T extends Comparable<?>> implements ShardingValue {

private final String logicTableName;

private final String columnName;

private final T value; // Here it is T
}
