### ISSUE TITLE
Shardingproxy failed to insert Emoji expression, mysql5.7

### ISSUE THREAD

**Issue by zosimer** [apache/shardingsphere#8106]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')'

**Comment by strongduanmu** [comment]
@zosimer Which version are you using? I remember this problem has been fixed on the master branch, can you try the `5.0.0-alpha` version that will be released recently?

**Comment by zosimer** [comment]
> @zosimer Which version are you using? I remember this problem has been fixed on the master branch, can you try the `5.0.0-alpha` version that will be released recently?

4.1.1

**Comment by zosimer** [comment]
> > @zosimer Which version are you using? I remember this problem has been fixed on the master branch, can you try the `5.0.0-alpha` version that will be released recently?
> 
> 4.1.1

see this issue https://github.com/apache/shardingsphere/issues/7815

**Comment by strongduanmu** [comment]
@zosimer Good news, the latest `5.0.0-alpha` version has been released today, you can try it.

**Comment by zosimer** [comment]
thx,I'm compiling. I'll try it later

**Comment by zosimer** [comment]
> @zosimer Good news, the latest `5.0.0-alpha` version has been released today, you can try it.

thx,I'm compiling. I'll try it later

**Comment by zosimer** [comment]
> @zosimer Good news, the latest `5.0.0-alpha` version has been released today, you can try it.

java.lang.NullPointerException: Can not get connection from datasource pr_ds.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:987)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:80)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:62)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.BackendConnection.getConnectionsWithoutTransaction(BackendConnection.java:141)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:102)
        at org.apache.shardingsphere.infra.executor.sql.resourced.group.ResourceManagedExecuteGroupEngine.generateSQLExecuteGroups(ResourceManagedExecuteGroupEngine.java:66)
        at org.apache.shardingsphere.infra.executor.sql.group.AbstractExecuteGroupEngine.generate(AbstractExecuteGroupEngine.java:58)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.generateInputGroups(JDBCExecuteEngine.java:140)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.executeWithManagedResource(JDBCExecuteEngine.java:130)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.execute.engine.jdbc.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:123)

**Here is the configuration file：**
schemaName: jiajia
dataSourceCommon:
  username: root
  password: ********
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 151
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  primary_ds:
    url: jdbc:mysql://172.16.192.57:3306/jiajia?serverTimezone=GMT%2B8&useSSL=false
  replica_ds_0:
    url: jdbc:mysql://172.16.0.135:3306/jiajia?serverTimezone=GMT%2B8&useSSL=false

rules:
- !REPLICA_QUERY
  dataSources:
    pr_ds:
      name: pr_ds
      primaryDataSourceName: primary_ds
      replicaDataSourceNames:
        - replica_ds_0

**Comment by strongduanmu** [comment]
@zosimer I used the configuration you provided, and there was no abnormality in the 5.0.0-alpha version. Can you check your configuration again? In addition, can you provide the original error SQL?

**Comment by zosimer** [comment]
> @zosimer I used the configuration you provided, and there was no abnormality in the 5.0.0-alpha version. Can you check your configuration again? In addition, can you provide the original error SQL?

An error is reported when connecting to shardingproxy. No error is reported when starting

**Comment by zosimer** [comment]
> > @zosimer I used the configuration you provided, and there was no abnormality in the 5.0.0-alpha version. Can you check your configuration again? In addition, can you provide the original error SQL?
> 
> An error is reported when connecting to shardingproxy. No error is reported when starting

Is it possible that the problem is driven by MySQL? The driver I used is mysql-connector-java-8.0.20.jar

**Comment by zosimer** [comment]
> > > @zosimer I used the configuration you provided, and there was no abnormality in the 5.0.0-alpha version. Can you check your configuration again? In addition, can you provide the original error SQL?
> > 
> > 
> > An error is reported when connecting to shardingproxy. No error is reported when starting
> 
> Is it possible that the problem is driven by MySQL? The driver I used is mysql-connector-java-8.0.20.jar

What version of MySQL driver do you use? I'm going to try it out

**Comment by strongduanmu** [comment]
@zosimer You can refer to the [official document](https://shardingsphere.apache.org/document/current/cn/quick-start/shardingsphere-proxy-quick-start/) and download `mysql-connector-java-5.1.47.jar`.

**Comment by zosimer** [comment]
> @zosimer You can refer to the [official document](https://shardingsphere.apache.org/document/current/cn/quick-start/shardingsphere-proxy-quick-start/) and download `mysql-connector-java-5.1.47.jar`.

I changed the driver package version or not, I use the source code to compile, has compiled the binary package to download?

**Comment by strongduanmu** [comment]
@zosimer You can download `Sharding-Proxy` directly from [this link](https://shardingsphere.apache.org/document/current/cn/downloads/). For more information about `Sharding-Proxy`, please refer to the official documentation.
