### ISSUE TITLE
Is there any plan on oracle batch insert support?

### ISSUE THREAD

**Issue by piggytough** [apache/shardingsphere#8107]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
Oracle batch insert sql like:
```
insert into .. 
select ... from 
.. 
union all ..
```
**or** 
```
insert all
into ...
into ...
select 1 from dual
```

**Comment by strongduanmu** [comment]
@piggytough I am very sorry for that we do not have plans to support oracle batch insert recently. Are you interested in submitting a PR to support this feature?

**Comment by piggytough** [comment]
> @piggytough I am very sorry for that we do not have plans to support oracle batch insert recently. Are you interested in submitting a PR to support this feature?

sure, I'd be glad to.

**Comment by kimmking** [comment]
@piggytough  good news, let's move forward.

**Comment by kimmking** [comment]
@piggytough any update now?

**Comment by piggytough** [comment]
> @piggytough any update now?

nope. quite busy these days, sorry for that.

**Comment by terrymanu** [comment]
No plan to improve with oracle, I just set it as good amateur issue, does anyone want to fix it?

**Comment by terrymanu** [comment]
Close because of staled.
