### ISSUE TITLE
proxy 日期分表配制

### ISSUE THREAD

**Issue by isoleo** [apache/shardingsphere#8113]
能不能分享一个日期按月分表的配制文件呢？？文档上对于日期分表写的好少。不知道怎么配制？

**Comment by kimmking** [comment]
English here only.

**Comment by isoleo** [comment]
这个很有意思 。你人在北京，也是中国人，这个sharding 也是当年的当当出的。怎么就成了 only english ？？？这不是脱裤子放屁吗？？？？
