### ISSUE TITLE
When shardingjdbc integrates mybatis, how to realize the dynamic configuration of mapper.xml table name?

### ISSUE THREAD

**Issue by pendaba** [apache/shardingsphere#8121]
When shardingjdbc integrates mybatis, how to realize the dynamic configuration of mapper.xml table name?

**Comment by pendaba** [comment]
like I have two tables;t_use0,t_use1.
<insert id="save">
insert into t_user(name,age,create_date,create_time) values(#{item.name},#{item.age},#{item.createDate},#{item.createTime});
</insert>

**Comment by strongduanmu** [comment]
@pendaba You can refer to the [official documentation](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/java-api/). After the configuration is complete, you can use the logical table like a normal table in mybatis.

**Comment by kimmking** [comment]
Hi, @pendaba 
shardingsphere-jdbc doesn't need to know mapper xml details, it just parse sql and convert logic table name to actual name before sending to mysql server.
