### ISSUE TITLE
inventoryDataScaling Multiple threads migrating block

### ISSUE THREAD

**Issue by Zzshuo** [apache/shardingsphere#8122]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-scaling

### Expected behavior
Multiple threads migrating together

### Actual behavior
inventoryDataScaling Multiple threads migrating block

### Reason analyze (If you can)
  waitForResult(future) method blocked on the scalingTasks foreach start

![image](https://user-images.githubusercontent.com/12946820/98673572-7b8d7e80-2392-11eb-9fea-e46bc8263150.png)

![image](https://user-images.githubusercontent.com/12946820/98673570-7b8d7e80-2392-11eb-83a8-5b6ab18fd154.png)

![image](https://user-images.githubusercontent.com/12946820/98677037-6b2bd280-2397-11eb-9b11-b461a44fb4e9.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
use shardingsphere-ui scaling table. when conurrency>1 ,It will occur，next conurrency start after prev conurrency finished.

**Comment by avalon5666** [comment]
InventoryDataScalingTask serial execute in the InventoryDataScalingTaskGroup, and conurrency execute between InventoryDataScalingTaskGroup.

**Comment by Zzshuo** [comment]
> InventoryDataScalingTask serial execute in the InventoryDataScalingTaskGroup, and conurrency execute between InventoryDataScalingTaskGroup.

I think this is a bug. Because in 4.1.1 ScalingTask can  parallel execute in TaskGroup. We actually want to do it in parallel as well. Otherwise,InventoryDataScalingTaskGroup doesn't make any difference. just can remove  InventoryDataScalingTaskGroup only use InventoryDataScalingTask.

**Comment by avalon5666** [comment]
For easier thread management, we refactored.

**Comment by avalon5666** [comment]
We removed TaskGroup  #8368.
Thank you for your advice!
