### ISSUE TITLE
sharding jdbc cost too many times to checm meta data when i start a spring boot project

### ISSUE THREAD

**Issue by weikangqq** [apache/shardingsphere#8128]
my application.yml  
  props:
      sql:
        show: true
      check:## it looks like not effict
        table:
          metadata:
            enabled: false

my maven
           <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
                <version>4.1.1</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.3.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

that's my start log:
2020-11-11 13:23:27.090  INFO 7116 --- [  restartedMain] ShardingSphere-metadata                  : Loading 5 logic tables' meta data.
2020-11-11 13:23:27.522  INFO 7116 --- [  restartedMain] ShardingSphere-metadata                  : Loading 458 tables' meta data.
2020-11-11 13:25:25.592  INFO 7116 --- [  restartedMain] ShardingSphere-metadata                  : Meta data load finished, cost 118541 milliseconds.

it wait it too long;
please tell me how can i do to close meta check in spring boot project

**Comment by weikangqq** [comment]
![image](https://user-images.githubusercontent.com/20835251/98773438-e20ead00-2423-11eb-805e-748ea4394d56.png)

property 
      sql.show  ** take effect
      check:
        table:
          metadata:
            enabled: false  ***not take effect

**Comment by strongduanmu** [comment]
@weikangqq This problem is duplicated with #6212, and it has been solved in the latest `5.0.0-alpha` version. Welcome to try the new version. 😀
