### ISSUE TITLE
Does the latest version of Proxy (4.1.1) support Data Sharding + Read-Write Split   ?

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8139]

**Comment by kimmking** [comment]
Yes, as the same as jdbc.
you can refer https://github.com/apache/shardingsphere/blob/4.1.1/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-master-slave.yaml

**Comment by duzhanfei** [comment]
For the proxy, are these configurations all written in the file of config-master_slave.yaml ?



在 2020-11-11 22:10:34，"kimmking" <notifications@github.com> 写道：

Closed #8139.

**Comment by duzhanfei** [comment]
I see，Thank you.



At 2020-11-11 22:10:33, "kimmking" <notifications@github.com> wrote:

Yes, as the same as jdbc.
you can refer https://github.com/apache/shardingsphere/blob/4.1.1/examples/sharding-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-master-slave.yaml
