### ISSUE TITLE
Add scope for shardingsphere-test in all the pom files.

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8142]
### Background

`shardingsphere-test` is just for test. Therefore the `shardingsphere-test` dependency in other pom files is supposed to include `<scope>test</scope>`.
However, some of the cases are not as described above.

### Task
1. Find out all the `shardingsphere-test` dependencies without `<scope>test</scope>`.
2. Add `<scope>test</scope>` for these targets.
3. Raise a PR. ([Contributor guide](https://shardingsphere.apache.org/community/en/contribute/contributor/) for newbies)See you online that day, and best wishes for this wonderful PostgreSQL Asia conference.

Welcome on board. 😉

**Comment by wenweibin** [comment]
If nobody want to fix it，please assgin to me. 😉
