### ISSUE TITLE
Format input parameters for visitor functions

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8143]
### Background

Considering the check-style for functions, 
` public ASTNode visitQuerySpecification(final QuerySpecificationContext ctx) ` is expected rather than
 ` public ASTNode visitQuerySpecification(final MySQLStatementParser.QuerySpecificationContext ctx) `.

Hence, this issue aims to correct the nonstandard  `visit` function check-style.

### How?

1.  Enter into directory `~/shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect`.
2. All the target classes in `src/main/java/org/apache/shardingsphere/sql/parser/${database Name}/visitor/`.
 - As you can see, basically, most of the function names are in the form of `visitXXX()`.
3. If you find that the input parameter is in the style of `final MySQLStatementParser.QuerySpecificationContext ctx`, please modify it to `final QuerySpecificationContext ctx`.

This issue is simply understanding, though, it will take you some of the time. :) So All the changes in one PR or a few PRs with a part of changes are both ok. 

Waiting for your joining! 😃

**Comment by wenweibin** [comment]
This is really a good first  issue, and  if nobody want to fix it，please assgin to me. 😉

**Comment by strongduanmu** [comment]
@wenweibin Welcome!!!👏👏👏
