### ISSUE TITLE
sharding+seata commit error

### ISSUE THREAD

**Issue by niudadan** [apache/shardingsphere#8144]
error desc : https://github.com/seata/seata/issues/3253
![image](https://user-images.githubusercontent.com/11550882/98905311-2cf8f500-24f6-11eb-9ac2-6813e1f6de0d.png)
![image](https://user-images.githubusercontent.com/11550882/98905320-33876c80-24f6-11eb-9a12-76773e138c49.png)
![image](https://user-images.githubusercontent.com/11550882/98905340-3aae7a80-24f6-11eb-8d1b-a2ef8538223d.png)

**Comment by cherrylzhao** [comment]
you can add `sharding.transaction.seata.at.enable = false` in seata.conf
or just remove the sharding-transaction-base-seata dependency

**Comment by terrymanu** [comment]
No response anymore
