### ISSUE TITLE
INSERT INTO .... ON DUPLICATE KEY UPDATE can not support update for sharding column. 

### ISSUE THREAD

**Issue by AdancingCoder** [apache/shardingsphere#8145]
insert into ds0.yugong_example_mysql(`GMT_CREATE` , `SCORE` , `AMOUNT` , `DISPLAY_NAME` , `TEXT_B` , `TEXT_C` , `GMT_MODIFIED` , `GMT_MOVE` , `ID`) values (? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `GMT_CREATE`=values(`GMT_CREATE`) , `SCORE`=values(`SCORE`) , `AMOUNT`=values(`AMOUNT`) , `DISPLAY_NAME`=values(`DISPLAY_NAME`) , `TEXT_B`=values(`TEXT_B`) , `TEXT_C`=values(`TEXT_C`) , `GMT_MODIFIED`=values(`GMT_MODIFIED`) , `GMT_MOVE`=values(`GMT_MOVE`) , `ID`=values(`ID`)

how can i do it,please

**Comment by strongduanmu** [comment]
@AdancingCoder This issue is duplicated with #7703.
