### ISSUE TITLE
ShardingSphere XATransactionManager  with SPI

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#8151]
- [ ] 1. Tune the code with the SPI idea
- [ ] 2. update transation example
- [ ] 3. update transaction docment

**Comment by kimmking** [comment]
@yu199195 https://github.com/apache/shardingsphere/issues/8018

**Comment by kimmking** [comment]
@yu199195 https://github.com/apache/shardingsphere/issues/8018

**Comment by yu199195** [comment]
duplicate with #8018
