### ISSUE TITLE
Does  apache-shardingsphere-5.0.0-alpha-shardingsphere-scaling  support  Migrate the old system stock data to the   data  Sharding  new system  termly  ?

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8157]

**Comment by kimmking** [comment]
refered:
1. https://shardingsphere.apache.org/document/current/cn/features/scaling/principle/
2. https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-scaling/usage/

**Comment by terrymanu** [comment]
Yes, it support
