### ISSUE TITLE
MySQL date_ format and year error

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#8165]
### Which version of ShardingSphere did you use?
4.1.1 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

I used spring boot + mybatis plus. Issue recommends upgrading the latest version. I have already upgraded
**Mapper:**
![image](https://user-images.githubusercontent.com/59325449/99178114-f7991500-274a-11eb-9bd1-0f820a11f09c.png)
**SQL:**
![image](https://user-images.githubusercontent.com/59325449/99178073-b4d73d00-274a-11eb-9a5e-f1d22a373192.png)
**ERROR:**
![image](https://user-images.githubusercontent.com/59325449/99178154-71c99980-274b-11eb-8c5b-3ea0f904819e.png)

**Comment by tristaZero** [comment]
Hi @romantictravel01 Could you set `sql.show=true`? So we could get the `logic SQL` and `actual SQL`. Thx.

**Comment by terrymanu** [comment]
Closed because of no response anymore.

**Comment by romantictravel01** [comment]
It's too lazy. I've already given it very clearly
