### ISSUE TITLE
[ShardingSphere-Scaling ] JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8175]
### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-scaling

This error occurs when i start scaling job according to the sample 
（https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-scaling/usage/）, 

config：

curl -X POST \
  http://localhost:8888/scaling/job/start \
  -H 'content-type: application/json' \
  -d '{
        "ruleConfiguration": {
          "source": {
            "type": "shardingSphereJdbc",
            "parameter": {
              "dataSource":"
                dataSources:
                  ds_0:
                    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
                    props:
                      driverClassName: com.mysql.jdbc.Driver
                      jdbcUrl: jdbc:mysql://127.0.0.1:3306/cdsp?useSSL=false
                      username: root
                      password: root
                ",
              "rule":"
                rules:
                - !SHARDING
                  tables:
				    defaultDataSourceName: ds_0
				    defaultTableStrategy:
					  none:
                "
            }
          },
          "target": {
              "type": "jdbc",
              "parameter": {
                "username": "root",
                "password": "root",
                "jdbcUrl": "jdbc:mysql://127.0.0.1:3307/sharding_master_slave_db?serverTimezone=UTC&useSSL=false"
              }
          }
        },
        "jobConfiguration":{
          "concurrency":"3"
        }
      }'

log：

C:\Users\host>curl -X POST   http://localhost:8888/scaling/job/start   -H 'content-type: application/json'   -d '{ "ruleConfiguration": { "source": { "type": "shardingSphereJdbc", "parameter": { "dataSource":" dataSources: ds_0: dataSourceClassName: com.zaxxer.hikari.HikariDataSource props: driverClassName: com.mysql.jdbc.Driver jdbcUrl: jdbc:mysql://127.0.0.1:3306/cdsp?useSSL=false                      username: root                      password: root ", "rule":" rules: - !SHARDING tables: defaultDataSourceName: ds_0 defaultTableStrategy:  none:                "            }          },          "target": {              "type": "jdbc",              "parameter": { "username": "root", "password": "root", "jdbcUrl": "jdbc:mysql://127.0.0.1:3307/sharding_master_slave_db?serverTimezone=UTC&useSSL=false"}}},"jobConfiguration":{"concurrency":"3"}}'
{"success":false,"errorCode":500,"errorMsg":"com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $","model":null}curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: ruleConfiguration
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: source
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: type
curl: (6) Could not resolve host: shardingSphereJdbc,
curl: (6) Could not resolve host: parameter
curl: (3) [globbing] unmatched brace in column 1
curl: (3) Port number ended with ' '
curl: (3) Port number ended with ' '
curl: (3) [globbing] unmatched close brace/bracket in column 1
curl: (3) [globbing] unmatched close brace/bracket in column 1
curl: (6) Could not resolve host: target
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: type
curl: (6) Could not resolve host: jdbc,
curl: (6) Could not resolve host: parameter
curl: (3) [globbing] unmatched brace in column 1
curl: (6) Could not resolve host: username
curl: (6) Could not resolve host: root,
curl: (6) Could not resolve host: password
curl: (6) Could not resolve host: root,
curl: (6) Could not resolve host: jdbcUrl
curl: (3) [globbing] unmatched close brace/bracket in column 85

**Comment by dongzl** [comment]
@duzhanfei , Thank for your issue, @avalon5666 will help your.

**Comment by avalon5666** [comment]
cmd syntax error
