### ISSUE TITLE
Error message if circuit break mode has unnecessary test.

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8179]
When execute sql in circuit break mode, it display:

```
ERROR 10000 (C1000): 0Circuit break mode is ON.
```

In word `0Circuit`, `0` is unnecessary, please remove it.

![image](https://user-images.githubusercontent.com/5516298/99266106-636ba280-285d-11eb-83a2-2ea19a1c4586.png)

**Comment by cenyu00** [comment]
please assige me.

**Comment by dbhat6** [comment]
@cenyu00 are you still working on this?
Can I take it up if not?

**Comment by terrymanu** [comment]
Hi @dbhat6 
Please go ahead

**Comment by dbhat6** [comment]
@terrymanu I won't be able to take this up

**Comment by totalo** [comment]
Hi , plz assige me,I want to have a try,thx

**Comment by totalo** [comment]
Hello i want to know how to open circuit break mode， @terrymanu @strongduanmu

**Comment by totalo** [comment]
> Hello i want to know how to open circuit break mode， @terrymanu @strongduanmu

ohhh, I know， thx

**Comment by totalo** [comment]
I found that the `sqlState` length defined by mysql error packet is `5`, but we defined it as` 6`. This will happen to all `errorMsgs`. I would like to modify our defined length to` 5`. Take a look. If this design is unreasonable, I will Try another method.

**Comment by terrymanu** [comment]
@totalo  Thank you, the change is excellent, I will do a little research and merge it soon

**Comment by tuohai666** [comment]
LGTM. Please check one comment I left, then the PR can be merged.
