### ISSUE TITLE
[GSoC 2021] Apache ShardingSphere community prepares to attend GSoC 2021 as mentors

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8185]
Hi community,

We plan to attend [Google Summer of Code 2021](https://opensource.googleblog.com/2020/10/google-summer-of-code-2021-is-bringing.html).  Currently, we are **collecting ideas from our PMCs and committers of Apache ShardingSphere community**.

As GSoC 2021 is months away, the process of how to submit ideas is still vague and needs more investigation work. **I will give updates once I have any progress, so please watch this issue** If it draws your interests. **Still, you could prepare your ideas and share them here at present**.

---
# Procedure draft

## How to submit mentoring ideas
-  Prepare the description of your ideas in English
-  Submit them via your project JIRA (if your project does not use JIRA you can use [Comdev project](https://issues.apache.org/jira/browse/COMDEV)).
- Ensure you add the labels “gsoc2021” and “mentor”
- Ensure your title has “PROJECT_NAME:” at the start

### References
-  [Idea example]( https://issues.apache.org/jira/browse/COMDEV-385)
-  [Apache doc](https://community.apache.org/use-the-comdev-issue-tracker-for-gsoc-tasks.html)
- [Google Summer of Code 2021](https://opensource.googleblog.com/2020/10/google-summer-of-code-2021-is-bringing.html)

## How to be a mentor
- Subscribe [Mentors](mailto:mentors@community.apache.org) (Notice, the subscribe address is [Mentors-subscribe](mailto:mentors-subscribe@community.apache.org))
- Send your mentoring idea JIRA issue to [Mentors](mailto:mentors@community.apache.org) to ping `Maxim Solodovnik` to update the [GSoc 2021 ideas list](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2021+Ideas+list)
- Check your ideas in the [GSoc 2021 ideas list](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2021+Ideas+list)
- Watch [prospective-asf-mentors](https://community.apache.org/gsoc.html#prospective-asf-mentors-read-this) page to wait to register with the GSoC webapp

### References
- Email example (**TODO**)
- [Apache GSoC 2021 main page](https://community.apache.org/gsoc.html#prospective-asf-mentors-read-this)
- [Timeline](https://community.apache.org/gsoc.html#prospective-asf-mentors-read-this)
- [Ask for help](mailto:dev@community.apache.org) (Subscribe first)

**Comment by terrymanu** [comment]
Looks good, I want join it.

**Comment by terrymanu** [comment]
I have a task for add unit test for example to auto assert.
I will add it later.

**Comment by terrymanu** [comment]
I create the JIRA ticket: https://issues.apache.org/jira/projects/COMDEV/issues/COMDEV-392

**Comment by yu199195** [comment]
Looks good, I want join it.

**Comment by tristaZero** [comment]
Hi,
I created a new one [COMDEV-399](https://issues.apache.org/jira/browse/COMDEV-399)
