### ISSUE TITLE
bug, emoji cant save(insert), update is work

### ISSUE THREAD

**Issue by hhniao** [apache/shardingsphere#8194]
the docker-compose.yml file main content

    version: '3'
    services:
        mysql:
            image: "mysql:5.7.30"
        proxy:
            image: "apache/sharding-proxy:4.1.1"
    
insert sql, contain a emoji word, it is doesnt work

    INSERT INTO `sharding_db`.`t_order`(`id`, `title`, `user_id`, `order_id`, `amount`, `actual_amount`, `items_count`, `total_weight`, `order_status`, `status`, `remark`) VALUES (7, '😊', 1, 8, 1, 1, 1, 1, 1, 1, 'sdfdfs')
    // the error notice
    1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

insert sql, have no emoji word, it is work

     INSERT INTO `sharding_db`.`t_order`(`id`, `title`, `user_id`, `order_id`, `amount`, `actual_amount`, `items_count`, `total_weight`, `order_status`, `status`, `remark`) VALUES (7, 'dsfsfdfsd', 1, 8, 1, 1, 1, 1, 1, 1, 'sdfdfs')

update sql, have a emoji word, it is work
   
    UPDATE `sharding_db`.`t_order` SET `title` = 'dsfsfdfsd😊' WHERE `id` = 7

**Comment by strongduanmu** [comment]
Hi, @hhniao Only English will be accepted. Can you translate this issue into English?

**Comment by hhniao** [comment]
@strongduanmu why do you make it invalid?

**Comment by strongduanmu** [comment]
@hhniao Can you try the `5.0.0-alpha` version of sharding-proxy? This bug has been fixed in version 5.0.0-alpha.

**Comment by hhniao** [comment]
@strongduanmu thanks for you answer.
i will try it.
