### ISSUE TITLE
关于algorithm‐expression 配置问题

### ISSUE THREAD

**Issue by zhangle910522** [apache/shardingsphere#8196]
我现在有个需求，消息表的id 是根据uid(用户id)的分库基因 融合生成的，即id % m 和 uid % m 都会得到同一个数
sql语句 where uid = 或者 where id =  我都想获得对应数据库  algorithm‐expression 要怎么配置

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by ben905713861** [comment]
你把这几张表结构描述清楚一点，是对消息表分库吗？

**Comment by zhangle910522** [comment]
已经可以了 我自定义了 复合分片策略 谢谢
