### ISSUE TITLE
XA transaction in ShardingSphere-Proxy-5.0.0 is invalid

### ISSUE THREAD

**Issue by ben905713861** [apache/shardingsphere#8200]
### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
I use XA transaction configuation, but the sharding-proxy does not send XA SQL to the physics node, the XA transaction is invalid.
```
props:
#    # LOCAL: Proxy will run with LOCAL transaction.
#    # XA: Proxy will run with XA transaction.
#    # BASE: Proxy will run with B.A.S.E transaction.
  proxy-transaction-type: XA
```
I write the SQL in sharding-proxy mysql client,the SQL is:
```sql
start transaction;
update activity set startTime="2020-08-01 18:00:01" where activityId=30;
rollback;
```
The result is change, transaction does not rollback.
### Actual behavior
This is my Wireshark analysis chart:
```
           H   update activity set startTime="2020-08-01 18:00:01" where activityId=300       (Rows matched: 1  Changed: 0  Warnings: 0
```
I can't see any XA SQL in the analysis.So I think the XA configuration is invalid.

**Comment by kimmking** [comment]
duplicated with https://github.com/apache/shardingsphere/issues/8178

@yu199195 It has been fixed in master branch.
