### ISSUE TITLE
We will Develop ShardingSphere Agent！

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#8206]
Hi，Friends from all communities

We will Develop ShardingSphere Agent！ why？ 
1. agent  can decouple our project so that the master code is not disturbed。
2. use agent  we can do whatever we want。
3. and so on。。。

We technology select  is [byte-buddy](https://github.com/raphw/byte-buddy). It is a powerful and flexible framework based on ASM。

First of all, we need to set up the basic framework，and I'm going to list them here。

- [x]  1. Build the agent project structure @yu199195 
- [x]   2. load agent config @yu199195 
- [ ]   3. the custom classloader @yu199195
- [ ]   3. define plugin and load plugin @yu199195
- [ ]   4. integration byte-buddy and set up a variety of matches
- [ ]  5. develop a package release strategy

There may be more to come ，If you are familiar with it or interested in what we do, please join us in doing it。

**Comment by dmsolr** [comment]
Hi @yu199195 
I am very glad to join this.

**Comment by yu199195** [comment]
@dmsolr  you're very welcome

**Comment by dmsolr** [comment]
I used to work something on SkyWalking Agent, so I think I could be qualified.
