### ISSUE TITLE
Can  sharding key be varchar ?

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8211]

**Comment by duzhanfei** [comment]
<img width="796" alt="000" src="https://user-images.githubusercontent.com/46663706/99533037-31367e00-29e0-11eb-93b1-82cb25254174.png">

**Comment by dongzl** [comment]
Hi @duzhanfei , Can you provide more details, what's your ShardingSphere version, proxy or jdbc, and the config file?

and the screenshot is another issue? can you reference the issue id? Thanks.

**Comment by duzhanfei** [comment]
Thank you for your reply.

the issue id is 7940.



At 2020-11-19 09:13:58, "Zonglei Dong" <notifications@github.com> wrote:

Hi @duzhanfei , Can you provide more details, what's your ShardingSphere version, proxy or jdbc, and the config file?

and the screenshot is another issue? can you reference the issue id? Thanks.

**Comment by kimmking** [comment]
inline algorithmExpression is a groovy script, you can use any type such as int or string and whatever.

as your case `ds_${ecif_cust_no % 2}` ,   ` % 2 `  only for int or long.

you can use `Math.abs(ecif_cust_no.hashCode()) % 2` instead.

**Comment by duzhanfei** [comment]
Thank you very much. my idol .



At 2020-11-19 13:44:06, "kimmking" <notifications@github.com> wrote:

inline algorithmExpression is a groovy script, you can use any type such as int or string and whatever.

as your case ds_${ecif_cust_no % 2} , % 2 only for int or long.

you can use Math.abs(ecif_cust_no.hashCode()) % 2 instead.
