### ISSUE TITLE
proxy excute insert sql but insert into all physical table

### ISSUE THREAD

**Issue by xiaoliu10** [apache/shardingsphere#8217]
three database zookeeper_0, zookeeper_1, zookeeper_2.  shardingColumn  order_id, algorithm use hash_mod 
one database three physical  table t_order_0, t_order_1, t_order_2 , shardingColumn user_id, algorithm use hash_mode
now, execute `insert into `t_order` values('admin', now(), now())`, 
the expected result is to route to one of the nine tables, but all nine tables insert the same piece of data

**Comment by kimmking** [comment]
what is your config and logic/actual sql?

**Comment by xiaoliu10** [comment]
this is datasource config
dataSources:
  zookeeper_0:
    url: jdbc:mysql://xxxx:3306/zookeeper_0?useUnicode=true
  zookeeper_1:
    url: jdbc:mysql://xxxx:3306/zookeeper_1?useUnicode=true
  zookeeper_2:
    url: jdbc:mysql://xxxx:3306/zookeeper_2?useUnicode=true

**Comment by xiaoliu10** [comment]
this is rules config:
rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: zookeeper_${[0,1,2]}.t_order_${[0,1,2]}
      databaseStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: hash_mode
      tableStrategy:
        standard:
          shardingColumn: user_id
          shardingAlgorithmName: hash_mode
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: increment
    t_order_item:
      actualDataNodes: zookeeper_${0..2}.t_order_item_${0..2}
      databaseStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: hash_mode
      tableStrategy:
        standard:
          shardingColumn: user_id
          shardingAlgorithmName: hash_mode
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_config
  defaultTableStrategy:
    standard:
      shardingColumn: order_id
      shardingAlgorithmName: hash_mode
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: hash_mode
  
  shardingAlgorithms:
    hash_mod:
      type: HASH_MOD
      props:
        sharding-count: '3'

  keyGenerators:
    increment:
      type: SNOWFLAKE
      props:
        worker-id: 1

**Comment by terrymanu** [comment]
1. What is your ShardingSphere version?
2. Can you provide log of `sql.show`?

**Comment by xiaoliu10** [comment]
1. 5.0.0-alpha
2.  I use Navicat to connect to sharding proxy. How can I get SQL logs

**Comment by terrymanu** [comment]
Enable sql-show to log your actual SQL

**Comment by terrymanu** [comment]
Closed because of no response.
