### ISSUE TITLE
create table with key name bug.

### ISSUE THREAD

**Issue by hhniao** [apache/shardingsphere#8223]
docker-compose.yml
    
    version: '3'
    services:
        mysql:
            image: "mysql:5.7.30"
        proxy:
            // maybe 5.0.0? i dont know.
            image: "apache/sharding-proxy" 

failed sql( with key name):

    drop table if exists t_order;
    CREATE TABLE `t_order` (
        `id` bigint unsigned NOT NULL AUTO_INCREMENT,
        `order_id` int NULL COMMENT '订单号',
        PRIMARY KEY (`id`) USING BTREE,
        UNIQUE KEY `order_id_unique` (`order_id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    

10002 - 2Unknown exception: [org.apache.shardingsphere.sql.parser.sql.common.segment.ddl.index.IndexSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.value.identifier.IdentifierValue]

successed sql (without key name):

```
drop table if exists t_order;
CREATE TABLE `t_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int NULL COMMENT '订单号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY (`order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by tristaZero** [comment]
Hi @hhniao 
Which version of ShardingSphere for this test?

**Comment by hhniao** [comment]
@tristaZero i dont know. it is which version. maybe 5.0.0-beta
im use this command.

    docker pull apache/sharding-proxy

**Comment by kimmking** [comment]
docker pull apache/shardingsphere-proxy

**Comment by terrymanu** [comment]
First analyzation:
SQL parser visitor cast exception with index segment and IdentifierValue.
