### ISSUE TITLE
Will the new version support multi-tenant design; 5.0; Is there a concept of multi-tenancy in it

### ISSUE THREAD

**Issue by lizhibo0914** [apache/shardingsphere#8227]

**Comment by tristaZero** [comment]
Hi @lizhibo0914 
I guess `multi-tenant` is supported. From my perspective, `multi-tenant` is a kind of sharding databases essentially. Still, maybe we have a different concept about it. Thus an explanation or your concern is welcomed to be given.

**Comment by terrymanu** [comment]
No, but the Pluggable Architecture can let developers customize the feature by them self, please see: https://shardingsphere.apache.org/document/current/en/features/pluggable-architecture/

If any one plan to do this feature, please open a new issue to discuss how to design it.
