### ISSUE TITLE
Add test cases for SQL parser cache

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8238]
- [ ] Add test case for ParseTreeCacheBuilder
- [ ] Add test case for ParseTreeCacheLoader
- [x] Add test case for SQLStatementCacheBuilder
- [ ] Add test case for SQLStatementCacheLoader

**Comment by panda-luo** [comment]
Would like to claim this.

**Comment by laingke** [comment]
Please assgin to me

**Comment by terrymanu** [comment]
Welcome, I just assign the issue to you

**Comment by kimmking** [comment]
@panda-luo @laingke 
You two should be pick a half of these four tasks.

**Comment by laingke** [comment]
Got it, I will handle ParseTreeCacheBuilder and ParseTreeCacheLoader.

**Comment by panda-luo** [comment]
I'll handle the rest.

**Comment by terrymanu** [comment]
@laingke @panda-luo Hi, any update?

**Comment by laingke** [comment]
@terrymanu I encountered difficulties when coding `ParseTreeCacheLoaderTest`.

 `SQLParserFactory.newInstance` is calling `SQLParserFacade` to create a singleton, and this facade is implemented in module `shardingsphere-sql-parser-dialect`, which is dependce on `shardingsphere-sql-parser-engine`.

When initializing `SQLParserExecutor`, it will cacuse `UnsupportedOperationException: Cannot support database type`

I have no idea how to assert, and can you support any suggestion?

Thanks.

**Comment by terrymanu** [comment]
> @terrymanu I encountered difficulties when coding `ParseTreeCacheLoaderTest`.
> 
> `SQLParserFactory.newInstance` is calling `SQLParserFacade` to create a singleton, and this facade is implemented in module `shardingsphere-sql-parser-dialect`, which is dependce on `shardingsphere-sql-parser-engine`.
> 
> When initializing `SQLParserExecutor`, it will cacuse `UnsupportedOperationException: Cannot support database type`
> 
> I have no idea how to assert, and can you support any suggestion?
> 
> Thanks.

Please mock sqlParserExecutor after new ParseTreeCacheLoader, and use reflection to set your mock.
