### ISSUE TITLE
Update the sub classes of TextProtocolBackendHandler

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#8241]
As method getRowData in TextProtocolBackendHandler has been modified, return type from list to collection.
Before:
```
public List<Object> getRowData();
```
After:
```
public Collection<Object> getRowData();
```

But all sub classes have not updated to Collection type as follow:

- [x] 1.BroadcastBackendHandler
- [x] 2.QueryBackendHandler
- [x] 3.RDLBackendHandler
- [x] 4.ShardingCTLExplainBackendHandler
- [x] 5.ShardingCTLHintBackendHandler
- [x] 6.ShardingCTLSetBackendHandler
- [x] 7.ShardingCTLShowBackendHandler
- [x] 8.ShowDatabasesBackendHandler
- [x] 9.ShowTablesBackendHandler
- [x] 10.SkipBackendHandler
- [x] 11.TransactionBackendHandler
- [x] 12.UnicastBackendHandler
- [x] 13.UseDatabaseBackendHandler

You should pick up one and 
1. modify getRowData return type to Collection<Object>
2. remove useless imports
3. mvn clean package to ensure all test work well
4. submit a pr to this repo with a certain title: Update the sub class[your update class name here] of TextProtocolBackendHandler

buddies, good luck and move on.

It's the result:
```

1. @sydgeek           1
2. @Duelist-Fiora   2
3. @zenglinhui       3
4. @abysscat-yj     4
5. @guojia1698      5
6. @Jlif                     6
7. @sharpzhango   7
8. @plutokaito        8
9. @zhangwei1989 9
10. @lxl910128       10
11. @cutieagain       11
12. @sciatta              12
13. @Wincher           13

```

**Comment by zhangwei1989** [comment]
领取9号任务～

**Comment by Wincher** [comment]
get 13

**Comment by Duelist-Fiora** [comment]
领取2号

**Comment by Jlif** [comment]
领取6号

**Comment by plutokaito** [comment]
8

**Comment by zhangwei1989** [comment]
take mission 9

**Comment by sharpzhango** [comment]
get 7

**Comment by lxl910128** [comment]
get 10.SkipBackendHandler

**Comment by Duelist-Fiora** [comment]
get 2

**Comment by cutieagain** [comment]
get 11

**Comment by onlyonezhongjinhui** [comment]
take  13.UseDatabaseBackendHandler

**Comment by zenglinhui** [comment]
get 2

**Comment by 19java95** [comment]
get 8

**Comment by NohnJnow** [comment]
get 10

**Comment by sydgeek** [comment]
take 1.BroadcastBackendHandler

**Comment by dongguabai** [comment]
get 11

**Comment by sciatta** [comment]
get 12

**Comment by mcnultyboy** [comment]
get 6

**Comment by guojia1698** [comment]
get 5

**Comment by branchen** [comment]
get 1

**Comment by abysscat-yj** [comment]
get 4

**Comment by himalia6** [comment]
get 4

**Comment by himalia6** [comment]
get 5

**Comment by himalia6** [comment]
get 7

**Comment by NohnJnow** [comment]
get 1

**Comment by NohnJnow** [comment]
get 6

**Comment by Lin1nGithub** [comment]
get6

**Comment by wyc192273** [comment]
get 2

**Comment by dongguabai** [comment]
get 1

**Comment by mrly202016** [comment]
I want to choose 7th

**Comment by kimmking** [comment]
Other buddies may be waiting next time.
