### ISSUE TITLE
password cannot all be numbers (e.g. 123456) in zookeeper datasource config

### ISSUE THREAD

**Issue by iamif3000** [apache/shardingsphere#8248]
### Which version of ShardingSphere did you use?
tag 4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
sharding-proxy

### Expected behavior
The proxy server can start normally.

### Actual behavior
The proxy server cannot start.

### Reason analyze (If you can)
The password field of YamlDataSourceParameter is of type String. But when the password chars in setting are all number, the type of password in DataSourceConfiguration.properties is Integer.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Config
.../config/schema/master_slave_db/datasource
> master_ds: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration
>   dataSourceClassName: com.zaxxer.hikari.HikariDataSource
>   properties:
>     url: jdbc:mysql://127.0.0.1:3306/proxy?serverTimezone=UTC&useSSL=false
>     username: proxy
>     password: 123456
>     connectionTimeoutMilliseconds: 30000
>     idleTimeoutMilliseconds: 60000
>     maxLifetimeMilliseconds: 1800000
>     maxPoolSize: 50

then start the proxy server.

**Comment by kimmking** [comment]
It's a known bug.
you can use ‘123456’  instead this time.

**Comment by kimmking** [comment]
duplicated with https://github.com/apache/shardingsphere/issues/8204
