### ISSUE TITLE
databasename can not contain dot 

### ISSUE THREAD

**Issue by riyun1989** [apache/shardingsphere#8263]
databasename can not contain dot 。if contain， after dot string will be discard。 i found like pattern in SQLServerDataSourceMetaData class "jdbc:(microsoft:)?sqlserver://([\w\-\.]+):?([0-9]*);\S*(DatabaseName|database)=([\w\-]+);?" should be "jdbc:(microsoft:)?sqlserver://([\w\-\.]+):?([0-9]*);\S*(DatabaseName|database)=([\w\-\.]+);?"

**Comment by riyun1989** [comment]
> databasename can not contain dot 。if contain， after dot string will be discard。 i found like pattern in SQLServerDataSourceMetaData class "jdbc:(microsoft:)?sqlserver://([\w-.]+):?([0-9]_);\S_(DatabaseName|database)=([\w-]+);?" should be "jdbc:(microsoft:)?sqlserver://([\w-.]+):?([0-9]_);\S_(DatabaseName|database)=([\w-.]+);?"

version is 4.0.0-RC2

**Comment by dongzl** [comment]
Hi @riyun1989 , can you try the newest version, `5.0.0-alpha`?

**Comment by riyun1989** [comment]
> Hi @riyun1989 , can you try the newest version, `5.0.0-alpha`?

version is 4.0.0-RC2

**Comment by riyun1989** [comment]
@dongzl   version is 4.0.0-RC2

**Comment by dongzl** [comment]
Hi @riyun1989 , can you submit a PR and fix this bug?

**Comment by riyun1989** [comment]
@dongzl ok,I already submitted a PR .
