### ISSUE TITLE
shardingsphere-proxy 5.0 yaml file can not support configure PreciseAlgorithmClassName

### ISSUE THREAD

**Issue by luckleemon** [apache/shardingsphere#8270]
shardingsphere-proxy 4.0 support self define sharding  algorithm, and configure it like 'PreciseAlgorithmClassName' in yaml file, and it works,

but now we upgrade it to shardingsphere-proxy 5.0, and old configuration does not works, and it goes error, whether new framework has a new configure way to use self define sharding  algorithm.and how to configure?

hope your Reply

thank you very much.

**Comment by dongzl** [comment]
Hi @luckleemon , yes, the 5.0 version has new configurations.

you can reference: https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sharding/

**Comment by luckleemon** [comment]
I have read the guide documentation you supply，but i still have no idea with how to configurate it，when i  want
to use the self implement sharding algorithm.

for example:
type: INLINE
      props:
        algorithm-expression: t_user_${id % 2}
if i want use self implement sharding algorithm, how to configurate above.

thank you very much.

hope your reply.
