### ISSUE TITLE
How to use oracle sequence as primary key when inserting records？

### ISSUE THREAD

**Issue by tuchun** [apache/shardingsphere#8271]
## Question

**My development environment**
springboot 2.2.11
mybatis-spring-boot 2.1.3
shardingsphere-jdbc-core 5.0.0-alpha
 druid 1.1.23
oracle 11g
ojdbc8

1. 
**When I configure in this way：**
`<insert id="insert" parameterType="com.demo.shardj.entity.OdRecord">`
        `<selectKey keyProperty="id" order="BEFORE" resultType="java.lang.Long">`
            `select SEQUENCE_OD_RECORD_ID.nextval from dual`
        `</selectKey>`
        `insert into OD_RECORD (ID, USER_ID, LINE_CODE,STATION_CODE,DEVICE_CODE,DEVICE_SEQ_NO,OD_TIME,CREATE_TIME)
        values (#{id,jdbcType=DECIMAL},#{userId,jdbcType=DECIMAL}, #{lineCode,jdbcType=VARCHAR}, #{stationCode,jdbcType=VARCHAR},
        #{deviceCode,jdbcType=VARCHAR}, #{deviceSeqNo,jdbcType=VARCHAR}, #{odTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP})`
    `</insert>`

**The exception is**
 `org.apache.shardingsphere.infra.exception.ShardingSphereException: Can not route tables for `[dual, SEQUENCE_OD_RECORD_ID]`, please make sure the tables are in same schema.`

2. 
**When I configure in this way：**
`<insert id="insert" parameterType="com.shardj.entity.OdRecord">`
        `insert into OD_RECORD (ID, USER_ID, LINE_CODE,STATION_CODE,DEVICE_CODE,DEVICE_SEQ_NO,OD_TIME,CREATE_TIME)
        values (SEQUENCE_OD_RECORD_ID.nextval,#{userId,jdbcType=DECIMAL}, #{lineCode,jdbcType=VARCHAR}, #{stationCode,jdbcType=VARCHAR},
        #{deviceCode,jdbcType=VARCHAR}, #{deviceSeqNo,jdbcType=VARCHAR}, #{odTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP})`
    `</insert>`

**The exception is**
'### Cause: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.column.ColumnSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.complex.ComplexExpressionSegment] with root cause'
`### SQL: insert into OD_RECORD (ID, USER_ID, LINE_CODE,STATION_CODE,DEVICE_CODE,DEVICE_SEQ_NO,OD_TIME,CREATE_TIME)         values (SEQUENCE_OD_RECORD_ID.nextval,?, ?, ?,         ?, ?, ?, ?)`

**When I do not use sharding jdbc or do not use oracle sequence as the primary key, everything works fine**

**Comment by terrymanu** [comment]
It is no relationship with oracle sequence, you can use it as normal.
Please notice the error message: `please make sure the tables are in same schema.`

**Comment by tuchun** [comment]
Maybe I didn’t explain clearly what I mean, I’m pretty sure `the tables are in same schema`, when I don’t use shardingjdbc, it can be executed normally, here `SEQUENCE_OD_RECORD_ID ` is an oracle sequence not table

**Comment by tuchun** [comment]
> It is no relationship with oracle sequence, you can use it as normal.
> Please notice the error message: `please make sure the tables are in same schema.`

Thank you for your reply,Maybe I didn’t explain clearly what I mean, I’m pretty sure the tables are in same schema, when I don’t use shardingjdbc, it can be executed normally, here SEQUENCE_OD_RECORD_ID is an oracle sequence not table

**Comment by Kimisme** [comment]
Hello, I have the same problem, and I don't know how to solve it.
