### ISSUE TITLE
how to support database scheme  or user ?

### ISSUE THREAD

**Issue by wp0372176** [apache/shardingsphere#8286]
中文意思: oracle数据库，分库不分表。 查询时候必须指定schema 或者user 。 否则无法查询。请问如何支持?

oracle database . 
only sub database. not sub table.
exmaple:
select * from  schema1.tb_user 

config error 1:
spring.shardingsphere.sharding.tables.tb_user.logic-table=schema1.tb_user
 
config error 2:
spring.shardingsphere.sharding.tables.tb_user.actual-data-nodes=trade$->{0..1}.schema11.tb_user

question:
how to Config ?

**Comment by dongzl** [comment]
Hi @wp0372176 , which is the version for ShardingSphere?

**Comment by wp0372176** [comment]
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>

**Comment by wp0372176** [comment]
<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>19.8.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
            <version>19.8.0.0</version>
        </dependency>

**Comment by wp0372176** [comment]
hi @dongzl

shardingsphere  last version:

org.apache.shardingsphere sharding-jdbc-spring-boot-starter 4.1.1

oracle pom:

com.oracle.database.jdbc ojdbc8 19.8.0.0
    <dependency>
        <groupId>com.oracle.database.nls</groupId>
        <artifactId>orai18n</artifactId>
        <version>19.8.0.0</version>
    </dependency>

spring boot  pom：

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.3.6.RELEASE</version> 
</parent>

**Comment by kimmking** [comment]
Each physical schema should be configured as a datasource.
And then config datasource to logic schema.

**Comment by terrymanu** [comment]
It has already supported in ShardingSphere, please try it.
Code ref: `OracleDataSourceMetaData`

**Comment by terrymanu** [comment]
Cannot support, please read document: https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/#unsupported-sql

Do not support SQL that contains schema, for the concept of ShardingSphere is to use multiple data source as one data source, so all the SQL visits are based on one logic schema.
