### ISSUE TITLE
How to use custom encryption algorithm for sharding proxy, encryptor is in the configuration file config_encrypt.yml

### ISSUE THREAD

**Issue by wenjunlichao1231** [apache/shardingsphere#8294]

**Comment by kimmking** [comment]
what do you mean?

**Comment by wenjunlichao1231** [comment]
> what do you mean?

The sharding proxy can customize the encryption and decryption type. How do you customize it? Do you have relevant research? In the official document, the encryption and decryption type can be customized or the built-in type can be selected.

**Comment by terrymanu** [comment]
Duplicated with #8297
