### ISSUE TITLE
Hello everyone, can sharding proxy add a custom encryption algorithm, how to add it? Have you ever used it?

### ISSUE THREAD

**Issue by wenjunlichao1231** [apache/shardingsphere#8295]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
Yes, it is, please see https://shardingsphere.apache.org/document/current/en/dev-manual/data-encryption/ to get built-in encrypt algorithms.

And please ref the built-in encrypt algorithms to impl your custom encryption algorithm.

**Comment by wenjunlichao1231** [comment]
> to get built-in encrypt algorithms

Thank you for your reply, but I want to add my own algorithm for data desensitization. Use sharding proxy instead of the built-in algorithm
