### ISSUE TITLE
In yaml mode, is there a configuration file loaded according from the classpath?

### ISSUE THREAD

**Issue by elliotann** [apache/shardingsphere#8297]
## Question
In yaml mode, is there a configuration file loaded according from the classpath?
 **YamlShardingSphereDataSourceFactory.createDataSource(yaml)**
If not, because the yamlshardingsphere datasourcefactory is declared as final and cannot be extended. to provide a more convenient one directly?

**Comment by terrymanu** [comment]
You can use `public static DataSource createDataSource(final byte[] yamlBytes)` to load yaml from classpath and convert the content to yaml bytes.

**Comment by elliotann** [comment]
> You can use `public static DataSource createDataSource(final byte[] yamlBytes)` to load yaml from classpath and convert the content to yaml bytes.

Thanks very much.I have override this method in the project from classpath;
public static DataSource createDataSource(final String classpathYamlFile) throws SQLException, IOException
