### ISSUE TITLE
How can preciseShardingAlgorithm read the configuration in the configuration file? For example, in January 2019, a table is divided into three days in 2020. How to read such configuration in the configuration file

### ISSUE THREAD

**Issue by Zengweilu** [apache/shardingsphere#8298]
How can preciseShardingAlgorithm read the configuration in the configuration file? For example, in January 2019, a table is divided into three days in 2020. How to read such configuration in the configuration file

**Comment by terrymanu** [comment]
Please use governance module to handle your dynamic configuration

**Comment by Zengweilu** [comment]
My project is a spring boot project. After reading the source code, I found that the factory cannot be rewritten. I used radiation to load shardingalgorithm, and tried many methods to transfer configuration information to shardingalgorithm, but none of them succeeded. Could you tell me a simple demo
