### ISSUE TITLE
how to congurate self implement sharding algorithm？

### ISSUE THREAD

**Issue by luckleemon** [apache/shardingsphere#8309]
I have read the guide documentation you supply，but i still have no idea with how to configurate it，when i want
to use the self implement sharding algorithm.

for example:
type: INLINE
props:
algorithm-expression: t_user_${id % 2}
if i want use self implement sharding algorithm, how to configurate above.and i have put my jar into lib directory。

this is part of my sharding algorithm code

public class DatePreciseShardingAlgorithm implements PreciseShardingAlgorithm<String> {

	private static Logger logger = LoggerFactory.getLogger(DatePreciseShardingAlgorithm.class);

	private static DateTimeFormatter sdf = DateTimeFormatter.ofPattern("yyyyMM", Locale.CHINA);
	private static final String SEPERATOR = "_";
	private static Date  lowwerDate = null;

	@Override
	public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<String> shardingValue) {
		String loginTableName = shardingValue.getLogicTableName();
		logger.info("logicTableName===={}",loginTableName);
		String value = shardingValue.getValue();
		Date createTime = null;
		try {
			createTime = new SimpleDateFormat("yyyy-MM-dd").parse(value);
		} catch (ParseException e) {
		
		}

		if(createTime == null){
			return loginTableName;
		}
		String yyyyMM = "";
		try{
			yyyyMM =SEPERATOR+ createTime.toInstant().atZone(ZoneId.systemDefault()).toLocalDate().format(sdf);
			return loginTableName+yyyyMM;
		}catch(Exception e){
		}
		return loginTableName;
	}

and the code works well, in shardingsphere4.

thank you very much.

hope your reply.

**Comment by terrymanu** [comment]
Did you add it into SPI?

**Comment by kimmking** [comment]
@luckleemon  configure your class in META-INF/services

**Comment by luckleemon** [comment]
@kimmking  i have config my class in META-INF/services like this。
![image](https://user-images.githubusercontent.com/28569002/100173326-3bd3a480-2f05-11eb-8924-35e7d99a7309.png)
but when i start the sharding-proxy ， the system throw exception like this 
![image](https://user-images.githubusercontent.com/28569002/100173542-b13f7500-2f05-11eb-85fb-732f2c9266eb.png)
how to solve the problem。
thank you。
hope your reply。

**Comment by terrymanu** [comment]
Please according the error message to debug your code

**Comment by tristaZero** [comment]
Hi @luckleemon Thanks for your issue.

I guess a detailed instruction is needed to add to tell users how to use custom sharding algorithm and other algorithms using SPI.
If the instruction is a short one, we can append it to [Q&A](https://shardingsphere.apache.org/document/current/cn/faq/).
Otherwise, I suggest adding a section `5.11 custom algorithm usage` to [dev-manual](https://shardingsphere.apache.org/document/current/cn/dev-manual/).
Welcome our contributors to share their relevant experiences and add them to the user manual.

**Comment by haoqg** [comment]
5.0 是用的SPI机制，假如需要使用自定义分库或者分表策略的话，以官方的mod为例子，我们需要这么干，首先
在项目里的resources 目录下新建一个文件夹  META-INF/services，文件夹里新建一个文件org.apache.shardingsphere.sharding.spi.ShardingAlgorithm
![image](https://user-images.githubusercontent.com/9582571/100214534-fb971500-2f4a-11eb-9a29-64990c165bed.png)
在此文件里把自己的类加上
比如，我这里新建一个类，
public final class BatchIdShardingAlgorithm implements StandardShardingAlgorithm<Comparable<?>>, ShardingAutoTableAlgorithm {
    private static final String SHARDING_COUNT_KEY = "sharding-count";
    private Properties props = new Properties();
    private int shardingCount;

    public BatchIdShardingAlgorithm() {
    }

    @Override
    public void init() {
        this.shardingCount = this.getShardingCount();
    }

    private int getShardingCount() {
        return 0;
    }

    @Override
    public String doSharding(Collection<String> availableTargetNames, PreciseShardingValue<Comparable<?>> shardingValue) {


        return "usoa_detail_flow_0";
    }

    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, RangeShardingValue<Comparable<?>> shardingValue) {
        return this.isContainAllTargets(shardingValue) ? availableTargetNames : this.getAvailableTargetNames(availableTargetNames, shardingValue);
    }

    private boolean isContainAllTargets(RangeShardingValue<Comparable<?>> shardingValue) {
        return !shardingValue.getValueRange().hasUpperBound() || shardingValue.getValueRange().hasLowerBound() && this.getLongValue(shardingValue.getValueRange().upperEndpoint()) - this.getLongValue(shardingValue.getValueRange().lowerEndpoint()) >= (long)(this.shardingCount - 1);
    }

    private Collection<String> getAvailableTargetNames(Collection<String> availableTargetNames, RangeShardingValue<Comparable<?>> shardingValue) {
        Collection<String> result = new LinkedHashSet(availableTargetNames.size());

        for(long i = this.getLongValue(shardingValue.getValueRange().lowerEndpoint()); i <= this.getLongValue(shardingValue.getValueRange().upperEndpoint()); ++i) {
            Iterator var6 = availableTargetNames.iterator();

            while(var6.hasNext()) {
                String each = (String)var6.next();
                if (each.endsWith(String.valueOf(i % (long)this.shardingCount))) {
                    result.add(each);
                }
            }
        }

        return result;
    }

    private long getLongValue(Comparable<?> value) {
        return Long.parseLong(value.toString());
    }

    @Override
    public int getAutoTablesAmount() {
        return this.shardingCount;
    }

    @Override
    public String getType() {
        return "BATCH-ID";
    }

    @Override
    public Collection<String> getAllPropertyKeys() {
        return Collections.singletonList("sharding-count");
    }

    @Override
    @Generated
    public Properties getProps() {
        return this.props;
    }

    @Override
    @Generated
    public void setProps(Properties props) {
        this.props = props;
    }

    @Generated
    public void setShardingCount(int shardingCount) {
        this.shardingCount = shardingCount;
    }
}

然后就可以使用自定义的策略了

Properties tableShardingAlgorithmrProps = new Properties();
        shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("BATCH-ID", tableShardingAlgorithmrProps));

大概就是这么个机制，
其实源码里就是这么干的，有图为证
![image](https://user-images.githubusercontent.com/9582571/100214851-516bbd00-2f4b-11eb-9389-c25b770b6a15.png)

**Comment by terrymanu** [comment]
For english only, I think the issue has already explain clearly. I just close the issue.
