### ISSUE TITLE
How to configure SQL statement printing in shardingsphere JDBC core spring boot starter

### ISSUE THREAD

**Issue by lazyboyl** [apache/shardingsphere#8321]
## Question
How to configure SQL statement printing in shardingsphere JDBC core spring boot starter
## 1、shardingsphere-jdbc-core-spring-boot-starter version
` <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>
        </dependency>`
## 2、spring-boot-starter version
`<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> 
    </parent>`
## 3、application.yml
How to configure SQL statement printing in application.yml，In this [configure](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/props/), only SQL show is found, but there is no specific configuration

**Comment by terrymanu** [comment]
Yaml‘s format is same with prop file

**Comment by lazyboyl** [comment]
application.properties I know how to configure it. However, the official spring boot document is not detailed enough. I found it through debugging the source code. I hope it can be supplemented in the spring boot document.
`spring.shardingsphere.props.sql-show: true`
