### ISSUE TITLE
Create a built-in sharding algorithm SPI in 5.x, which allows users to directly configure the class name as in 4.x

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#8330]
According to the suggestion of Liang Zhang
Create a built-in spi called class based sharding algorithm. As long as the user uses this built-in type, he can directly configure the class name, which is equivalent to the use of 4.x

**Comment by RaigorJiang** [comment]
Here is reference:
https://shardingsphere.apache.org/document/current/cn/dev-manual/sharding/

I'm trying to do this right now.

**Comment by RaigorJiang** [comment]
Hi, everyone~(especially @terrymanu )
I want to discuss the solution of this feature.

There are 3 types of ShardingAlgorithm which users can expand:
StandardShardingAlgorithm, ComplexKeysShardingAlgorithm and HintShardingAlgorithm.

I hava two plans:

1. If we provide only ONE SPI implementation, the class should  implement these three interfaces, and the configuration may like this :
`# 分片算法配置
  shardingAlgorithms:
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED   # 分片算法类型
      props: # 分片算法属性配置
        strategy: standard
        preciseAlgorithmClassName: org.xxx.example.PreciseShardingAlgorithm
        rangeAlgorithmClassName: org.xxx.example.RangeShardingAlgorithm
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED   # 分片算法类型
      props: # 分片算法属性配置
        strategy: complex
        algorithmClassName: org.xxx.example.ComplexKeysShardingAlgorithm
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED   # 分片算法类型
      props: # 分片算法属性配置
        strategy: hint
        algorithmClassName: org.xxx.example.HintShardingAlgorithm
      # ...`

2. We provide THREE SPI implementations, so their types can be different, and the configuration may like this : 
`# 分片算法配置
  shardingAlgorithms:
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED_STANDARD   # 分片算法类型
      props: # 分片算法属性配置
        preciseAlgorithmClassName: org.xxx.example.PreciseShardingAlgorithm
        rangeAlgorithmClassName: org.xxx.example.RangeShardingAlgorithm
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED_COMPLEX   # 分片算法类型
      props: # 分片算法属性配置
        algorithmClassName: org.xxx.example.ComplexKeysShardingAlgorithm
    <sharding-algorithm-name> (+): # 分片算法名称
      type: CLASS_BASED_HINT   # 分片算法类型
      props: # 分片算法属性配置
        algorithmClassName: org.xxx.example.HintShardingAlgorithm
      # ...`


I prefer to the second one, can you give some suggestions？
Thanks!

**Comment by terrymanu** [comment]
The 1st one is simple and clear, I like it.

**Comment by RaigorJiang** [comment]
Hi all:   
Because the precise sharding method and range sharding method are both in standard sharding algorithm interface now,
I remove the 'preciseAlgorithmClassName' and  'rangeAlgorithmClassName' variables, and unified as "algorithmClassName". So finally the configuration format is :
> # 
     shardingAlgorithms:
      <sharding-algorithm-name>:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: org.xxx.example.StandardShardingAlgorithm
      <sharding-algorithm-name>:
        type: CLASS_BASED
        props:
          strategy: complex
          algorithmClassName: org.xxx.example.ComplexKeysShardingAlgorithm
      <sharding-algorithm-name>:
        type: CLASS_BASED
        props:
          strategy: hint
          algorithmClassName: org.xxx.example.HintShardingAlgorithm
      # ...
