### ISSUE TITLE
What is the compatible mysql jdbc version of 5.0.0 ?

### ISSUE THREAD

**Issue by iamif3000** [apache/shardingsphere#8332]
Hi,

I made a performance test on sharding-proxy(4.1.1). And I found out that mysql-jdbc-5.1.48 is not compatible with sharding-proxy while 5.1.12 works OK.
So I'd like to know the compatible jdbc version of sharding-proxy 5.0.0.

**Comment by terrymanu** [comment]
I am not testing for all MySQL versions, but I think they are similar.
Could you provide the error message or use wireshark to catch the packet?

**Comment by iamif3000** [comment]
@terrymanu 

The error message
------------------------
java.sql.SQLException: Cannot create PoolableConnectionFactory (Unknown system variable 'transaction_isolation')
------------------------

**Comment by kimmking** [comment]
transaction_isolation  means mysql server is 8.0.

You should ensure your jdbc version compatible with your mysql server version, not ShardingSphere-proxy.
