### ISSUE TITLE
jdk8  LocalDateTime java.sql.SQLFeatureNotSupportedException: with mybatis 3.5.x

### ISSUE THREAD

**Issue by jxw1989** [apache/shardingsphere#8345]
private LocalDateTime createDate;
		
result column="CREATE_DATE" property="createDate" jdbcType="TIMESTAMP"

	at org.apache.shardingsphere.shardingjdbc.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getObject(AbstractUnsupportedOperationResultSet.java:221)

**Comment by terrymanu** [comment]
What the ShardingSphere version do you use?

**Comment by jxw1989** [comment]
> ShardingSphere

<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by jxw1989** [comment]
> What the ShardingSphere version do you use?

org.apache.shardingsphere sharding-jdbc-spring-boot-starter 4.1.1
spring-boot 2.3.4

**Comment by tuohai666** [comment]
Duplicated with #6166 
@jxw1989 You can try with 5.0.0-alpha
