### ISSUE TITLE
Redesign SchemaBuilderTest 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8351]
The test case SchemaBuilderTest is not make sense. It is better to redesign it for testing.

**Comment by yinyanghuafa** [comment]
please assign to me.

**Comment by JohnZhaozy** [comment]
Please assign it to me.

**Comment by arthasking123** [comment]
would you please give some hints？：）

**Comment by JohnZhaozy** [comment]
Is there any updates of this issue? Could you please assign it to me and tell some details if any?

**Comment by ruiyang00** [comment]
Hi @terrymanu , 
I am wondering that if this issue still open?
