### ISSUE TITLE
Can I use the like statement to query in shardingsphere JDBC 4? For example: like% XXX%

### ISSUE THREAD

**Issue by zhangleidaniejian** [apache/shardingsphere#8376]
**Can I use the like statement to query in shardingsphere-JDBC 4? For example: like% XXX%**
mysql:5.7
shardingsphere-JDBC 4.1.1

spring.shardingsphere.sharding.tables.writeoff_sales_order.actual-data-nodes = ds0.writeoff_sales_order_$->{0..4}
spring.shardingsphere.sharding.tables.writeoff_sales_order.table-strategy.inline.sharding-column = order_no
spring.shardingsphere.sharding.tables.writeoff_sales_order.table-strategy.inline.algorithm-expression = writeoff_sales_order_$->{order_no.toBigInteger() % 5}

spring.shardingsphere.sharding.tables.writeoff_sales_order_detail.actual-data-nodes = ds0.writeoff_sales_order_detail_$->{0..4}
spring.shardingsphere.sharding.tables.writeoff_sales_order_detail.table-strategy.inline.sharding-column = order_no
spring.shardingsphere.sharding.tables.writeoff_sales_order_detail.table-strategy.inline.algorithm-expression = writeoff_sales_order_detail_$->{order_no.toBigInteger() % 5}

spring.shardingsphere.sharding.binding-tables = writeoff_sales_order,writeoff_sales_order_detail
spring.shardingsphere.props.sql.show = true

**Comment by kimmking** [comment]
what's the type of order_no ?

**Comment by zhangleidaniejian** [comment]
bigint

**Comment by terrymanu** [comment]
Can not support
