### ISSUE TITLE
Cause: java.sql.SQLException: 2Unknown exception: [Can not route tables for `[bcpur_pscst_deptp_stats]`, please make sure the tables are in same schema.]\r\n### The error may exist in file

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8377]
#7816 # Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

I configured the default routing datesouce   when configuring read/write separation

I want to route  table   bcpur_pscst_deptp_stats  to the default database, but I am prompted that I do not have a routing policy configured

part  config   of config-replica-query.yaml 

  defaultDatabaseStrategy:
    standard:
      shardingColumn: ECIF_CUST_NO
      shardingAlgorithmName: database_default_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_default_inline:
      type: INLINE
      props:
        algorithm-expression: ms_ds
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ms_ds
    
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
        
- !REPLICA_QUERY
  dataSources:
    ms_ds:
      name: ms_ds
      primaryDataSourceName: primary_ds
      replicaDataSourceNames:
        - replica_ds_0
        - replica_ds_1

**Comment by duzhanfei** [comment]
"returnMsg": "\r\n### Error querying database.  Cause: java.sql.SQLException: 2Unknown exception: [Can not route tables for `[ORG_INFO]`, please make sure the tables are in same schema.]\r\n### The error may exist in file [D:\\sn_20201020\\customer1120\\cdsp-customer\\cdsp-customer-impl\\target\\classes\\mapper\\AdmdvTbMapper.xml]\r\n### The error may involve com.sxxh.cdsp.customer.dao.AdmdvTbMapper.queryOrgInfoTreeList-Inline\r\n### The error occurred while setting parameters\r\n### SQL: SELECT ORG_ECD, ORG_APLTN, SPR_ORG_ECD, 'orgInfo' NODE_TYPE, PRTCL_ADDR, ORG_LVL_CD FROM ORG_INFO WHERE VLD_FLG = 1 AND ORG_TYP_CD = '00' ORDER BY ORG_LVL_CD\r\n### Cause: java.sql.SQLException: 2Unknown exception: [Can not route tables for `[ORG_INFO]`, please make sure the tables are in same schema.]\n; uncategorized SQLException; SQL state [C1000]; error code [10002]; 2Unknown exception: [Can not route tables for `[ORG_INFO]`, please make sure the tables are in same schema.]; nested exception is java.sql.SQLException: 2Unknown exception: [Can not route tables for `[ORG_INFO]`, please make sure the tables are in same schema.]",

**Comment by terrymanu** [comment]
There is no version for 5.0.0, please provide the correct version number

**Comment by duzhanfei** [comment]
5.0.0-alpha ( Release Date: Nov 10, 2020 )



At 2020-11-29 16:14:22, "Liang Zhang" <notifications@github.com> wrote:

There is no version for 5.0.0, please provide the correct version number

**Comment by tuohai666** [comment]
@duzhanfei Can you provide the entire config of config-replica-query.yaml? So that I can reproduce and debug.

**Comment by terrymanu** [comment]
Closed because of no response.
