### ISSUE TITLE
how to update data in sharding-spring-boot-jpa

### ISSUE THREAD

**Issue by lly835** [apache/shardingsphere#8395]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

#### 'Update' method is very popular, hope to give an example
https://github.com/apache/shardingsphere/blob/master/examples/example-core/example-spring-jpa/src/main/java/org/apache/shardingsphere/example/core/jpa/repository/OrderRepositoryImpl.java

**Comment by terrymanu** [comment]
What is your version?

**Comment by lly835** [comment]
https://github.com/apache/shardingsphere/issues/8392
