### ISSUE TITLE
Add more test case for JDBCQueryResultMetaData

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8404]
- [ ] getTableName
- [ ] getColumnType
- [ ] getColumnLength
- [ ] getDecimals
- [ ] isSigned
- [ ] isNotNull
- [ ] isAutoIncrement

**Comment by yifanzzz** [comment]
what is the timeline?

**Comment by wenweibin** [comment]
Please assgin to me

**Comment by yifanzzz** [comment]
if it exist, please assign to me

**Comment by terrymanu** [comment]
Thank you, there are lots of method need to be test, you may share them.
