### ISSUE TITLE
How can I config the server-version of sharding-proxy?

### ISSUE THREAD

**Issue by wangleigithub** [apache/shardingsphere#8419]
When I  connect Mysql 8.0 with sharding-proxy 4.1.0,  the proxy always retrun server_version like '5.6.4-Sharding-Proxy 4.1.0', it will cause a problem, in cj.jdbc.drive will compare the drive version and proxy version , if min than 8.0.3 it will add "query_cache_size" property , but in Mysql 8.0 it removed.

**Comment by tuohai666** [comment]
This problem had been resolved in 5.0.0-alpha.
Please refer to https://github.com/apache/shardingsphere/issues/6239 .
