### ISSUE TITLE
dont support oracle RAC  in db.url?

### ISSUE THREAD

**Issue by hanjinxing** [apache/shardingsphere#8424]
## Question

 when i use the jdbc.url=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = host_ip1)(PORT = 1521)) (ADDRESS = (PROTOCOL = TCP)(HOST = host_ip2)(PORT = 1521)) (LOAD_BALANCE = yes)(failover=on)(connect_data= (service_name = orattt))), the class of OracleDataSourceMetaData is error, 

public final class OracleDataSourceMetaData implements DataSourceMetaData {
    
    private static final int DEFAULT_PORT = 1521;
    
    private final String hostName;
    
    private final int port;
    
    private final String catalog;
    
    private final String schema;
    
    private final Pattern pattern = Pattern.compile("jdbc:oracle:(thin|oci|kprb):@(//)?([\\w\\-\\.]+):?([0-9]*)[:/]([\\w\\-]+)", Pattern.CASE_INSENSITIVE);
    
    public OracleDataSourceMetaData(final String url, final String username) {
        Matcher matcher = pattern.matcher(url);
        if (!matcher.find()) {
            throw new UnrecognizedDatabaseURLException(url, pattern.pattern());
        }
        hostName = matcher.group(3);
        port = Strings.isNullOrEmpty(matcher.group(4)) ? DEFAULT_PORT : Integer.valueOf(matcher.group(4));
        catalog = matcher.group(5);
        schema = username;
    }
}

throw UnrecognizedDatabaseURLException, 

please help me , the shardingsphere dont support oracle RAC???

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/7195 .
