### ISSUE TITLE
The SQL tool can still see the original MySQL database name

### ISSUE THREAD

**Issue by xhrg** [apache/shardingsphere#8430]
test conditions：：：
*  sharding-proxy-4.1.1
*  mysql 5.7.30
*  create the database name ssdb in MySQL for test

---

testing procedure：：：
**config sharding-proxy**
`schemaName: sharding_db
dataSources:
  ds0: 
    url: jdbc:mysql://127.0.0.1:3306/ssdb?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds0.t_order_${0..1}
      databaseStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: ds0
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
  bindingTables:
    - t_order
  defaultTableStrategy:
    none:`

Abnormal situation：：：：
case 1：The database name must be configured to use Navicat，if not，will error。(使用Navicat必须设置数据库名称，否则会失败)
case 2：use mysql -u root -p，Log in MySQL，if you “show tables”，Incorrect display

> use sharding_db
> database changed
> show tables;
+----------------------+
|   Tables_in_ssdb           |
+----------------------+
|  t_order                         |
+----------------------+         Why is it shown here “Tables_in_ssdb”  is not  “Tables_in_sharding_db”

case 3：when i use DataGrip，All configuration methods will not succeed(使用DataGrip，怎么配置都不会成功)

**Comment by tristaZero** [comment]
Hi @xhrg 
Thanks for your feedback. I looked back the PRs, and found this bug has been fixed in [my PR](https://github.com/apache/shardingsphere/pull/6916/). I suggest you try it with the latest release 5.0.0-alpha.

**Comment by terrymanu** [comment]
Closed because of no response
