### ISSUE TITLE
Translate issue conduct to English

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8441]
Please translate issue conduct to English.

The Chinese version to be referenced:
https://github.com/apache/shardingsphere/tree/master/docs/community/content/contribute/issue-conduct.cn.md

English doc address:
https://github.com/apache/shardingsphere/tree/master/docs/community/content/contribute/issue-conduct.en.md

**Comment by wenweibin** [comment]
Please assgin to me
