### ISSUE TITLE
why sql parse useCache default value is false?

### ISSUE THREAD

**Issue by liuchaoheliang** [apache/shardingsphere#8457]
## Question

public final class SQLStatementParserEngine {
    
    private final SQLStatementParserExecutor sqlStatementParserExecutor;
    
    private final LoadingCache<String, SQLStatement> sqlStatementCache;
    
    public SQLStatementParserEngine(final String databaseType) {
        sqlStatementParserExecutor = new SQLStatementParserExecutor(databaseType);
        // TODO use props to configure cache option
        sqlStatementCache = SQLStatementCacheBuilder.build(new CacheOption(2000, 65535L, 4), databaseType);
    }
    
    /**
     * Parse to SQL statement.
     *
     * @param sql SQL to be parsed
     * @param useCache whether use cache
     * @return SQL statement
     */
    public SQLStatement parse(final String sql, final boolean useCache) {
        return useCache ? sqlStatementCache.getUnchecked(sql) : sqlStatementParserExecutor.parse(sql);
    }
}
hello, from this class ,i found useCache is not any effect, because the default value is false, is there needn't Cache?
why ? when most of the same sqls need parse ,how to guaranatee performance?

**Comment by tuohai666** [comment]
Statement will not be cached while PreparedStatement will be cached.

Why Statement will not be cached?
Imagine I insert rows whose id is from 1~1000000, all the 1000000 SQLs are different and the cache will not work.

Why PreparedStatement cache works?
Imagine I insert rows whose id is from 1~1000000, **id = ?** will be cached and is the only SQL to be cached. All the 1000000 SQLs share one parse result.

**Comment by liuchaoheliang** [comment]
OK, i understand ,thank you very much !
