### ISSUE TITLE
add support for checksumTable

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#8462]
## Feature Request

Now, when use `checksumtable`, there is a exception reported, we need it is ok to run `checksumtable`.

## subtask

- [x] add support parser of `checksumTable`

- [x] make it run ok on proxy.

**Comment by TeslaCN** [comment]
This statement worked.
![image](https://user-images.githubusercontent.com/20503072/209630170-06fb0dbc-ba9d-41da-b079-15844e63400a.png)
