### ISSUE TITLE
datetime format

### ISSUE THREAD

**Issue by chenjipdc** [apache/shardingsphere#8469]
## Bug Report

位置 -> org.apache.shardingsphere.sharding.algorithm.sharding.datetime.AutoIntervalShardingAlgorithm#parseDate

这个方法的参数类型可能是java.sql.Timestamp,直接调用.toString方法会得到毫秒(2020-12-01 01:01:55.601)，LocalDateTime使用的是yyyy-MM-dd HH:mm:ss，此时会抛异常。

**Comment by tuohai666** [comment]
Please translate the report to English and create a new issue.
