### ISSUE TITLE
5.0.0  change param 

### ISSUE THREAD

**Issue by taigam** [apache/shardingsphere#8480]
` <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>
        </dependency>`
`Actual SQL: magic-image2 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info1 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]`
`-Actual SQL: magic-image0 ::: select
    	app_code,
    	group_id,
    	matrix_pwd
, count(matrix_pwd) AS ORDER_BY_DERIVED_0     	
		from 
		matrix_info0 
      
    group by
		matrix_pwd
	 
        having count(matrix_pwd) >= ?
     
	order by
		count(matrix_pwd) desc LIMIT ?  ::: [2147483647, 20]`
when i add order by count()   then  param  have been changed

**Comment by tuohai666** [comment]
@taigam Please fill in the template:

```

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

```

**Comment by taigam** [comment]
5.0.0
ShardingSphere-JDBC
the param  i give in  is 6  
but  actual  change it to 2147483647  
something was wrong with it    
the log :
`2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image0 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info0 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image0 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info1 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image1 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info0 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image1 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info1 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image2 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info0 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.309 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image2 ::: SELECT count(0) FROM (SELECT app_code, group_id, matrix_pwd FROM matrix_info1 GROUP BY matrix_pwd HAVING count(matrix_pwd) >= ?) table_count ::: [6]
2020-12-03 11:13:15.318 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Logic SQL: select
    	app_code,
    	group_id,
    	matrix_pwd
    	
		from 
		matrix_info 
      
    group by
		matrix_pwd
	 
        having count(matrix_pwd) >= ?
     
	order by
		count(matrix_pwd) desc LIMIT ? 
2020-12-03 11:13:15.319 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -SQLStatement: MySQLSelectStatement(limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@64ba7b61], lock=Optional.empty)
2020-12-03 11:13:15.319 INFO [http-nio-8443-exec-10]ShardingSphere-SQL.log:74 -Actual SQL: magic-image0 ::: select
    	app_code,
    	group_id,
    	matrix_pwd
, count(matrix_pwd) AS ORDER_BY_DERIVED_0     	
		from 
		matrix_info0 
      
    group by
		matrix_pwd
	 
        having count(matrix_pwd) >= ?
     
	order by
		count(matrix_pwd) desc LIMIT ?  ::: [2147483647, 20]`

**Comment by tuohai666** [comment]
@taigam Get it, the param is changed. Can you show the final SQL result from ShardingSphere-JDBC and the result from raw JDBC?

**Comment by tuohai666** [comment]
I found that the parameter is rewritten to Integer.MAX_VALUE intentionally for some reason. So we need to compare the SQL results to determine whether there's a bug.

**Comment by taigam** [comment]
the  mapper  
`<select id="selectRepeatedMatrixInfoList" resultMap="ResultMapRepetitionExtension">
    select
    	app_code,
    	group_id,
    	matrix_pwd,
    	count(matrix_pwd)  as repeatedCount 
		from 
		matrix_info 
    <where>
        <if test="groupId != null and groupId != 0" >
          group_id = #{groupId,jdbcType=INTEGER}
        </if>
        <if test="appCode != null and appCode != ''" >
          app_code = #{appCode,jdbcType=VARCHAR}
        </if>
       
         
    </where>
    group by
		matrix_pwd
	<if test="minCount != null and minCount != 0" >
        having count(matrix_pwd) >= #{minCount,jdbcType=INTEGER}
    </if>
	order by
		count(matrix_pwd) desc
  </select>`
it's  with  PageHelper    
the final SQL result  from jdbc    is not the  log show ?   how to get it  ?

**Comment by taigam** [comment]
and   i found 
if  i delete   order by    
sharing  will  add it  behind the group by   
the sql changed for  :
SELECT
	app_code,
	group_id,
	matrix_pwd,
	count(matrix_pwd) AS repeatedCount
FROM
	matrix_info1
GROUP BY
	matrix_pwd
ORDER BY
	matrix_pwd ASC
HAVING
	count(matrix_pwd) >= ?
LIMIT ? ::: [ 6,
 20 ]


it can't be used

**Comment by tuohai666** [comment]
I mean SQL execute result

**Comment by taigam** [comment]
![微信图片_20201203142147](https://user-images.githubusercontent.com/31159699/100972061-1254f180-3573-11eb-8f8f-d178d7f332ab.png)

**Comment by taigam** [comment]
it can run  with the changed param    
just no data

**Comment by tuohai666** [comment]
What's data when you execute SQL use raw JDBC?

**Comment by taigam** [comment]
![111111111](https://user-images.githubusercontent.com/31159699/100973789-2a7a4000-3576-11eb-92dd-de4ef3af8edd.png)

**Comment by tuohai666** [comment]
@taigam (Let's stop focusing on param change or not) It seems like raw JDBC also just no data, I am not sure, am I right?

**Comment by tuohai666** [comment]
@taigam 
If ShardingSphere-JDBC returns no data, at the same time, raw-JDBC returns no data, I think at least there's no bug at this moment.
If you wonder why parameter changed, I can label this issue question, and we should read the code to find out why the parameter is rewritten like this.

**Comment by taigam** [comment]
the problem  is pagehelper    i changed the version of pagehelper  then  solved
