### ISSUE TITLE
Add test case for DatabaseBackendHandler impl

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8488]
- [ ] Add test case for SchemaAssignedDatabaseBackendHandler
- [ ] Add test case for UnicastDatabaseBackendHandler
- [ ] Add test case for DatabaseBackendHandlerFactory

**Comment by arthasking123** [comment]
please assign to me

**Comment by terrymanu** [comment]
@arthasking123  Assigned.
I just changed the class name from QueryBackendHandler to DatabaseBackendHandler.
The title is updated, please have a look.

**Comment by arthasking123** [comment]
got it

**Comment by terrymanu** [comment]
Sorry, the module is still in refactor, I split them to 2 classes. It is stable now. I will update title and content again

**Comment by arthasking123** [comment]
OK
