### ISSUE TITLE
In my project, the query time for tables without separate tables is 10 times that of ordinary jdbc

### ISSUE THREAD

**Issue by rouxiaoxiao** [apache/shardingsphere#8502]
In my project, the query time for tables without separate tables is 10 times that of ordinary jdbc. 
version:4.0.1

**Comment by tristaZero** [comment]
Hi @rouxiaoxiao,
The description of this issue is too short to deal with. I suggest you give more detail if you want the community's suggestion.

**Comment by terrymanu** [comment]
Please provide more details, we can not get any point of this issue.

**Comment by terrymanu** [comment]
Closed because of no response
