### ISSUE TITLE
How do You support the Grails framework 4

### ISSUE THREAD

**Issue by zhangjiayu139** [apache/shardingsphere#8507]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
I never used Grails, can you provide more details about it?
Is there any problem with Grails and ShardingSphere now?

**Comment by zhangjiayu139** [comment]
Grails: A powerful Groovy-based web application framework for the JVM built on top of Spring Boot
[Grails](https://grails.org/)
GORM: The Grails framework seamlessly integrates with GORM, a data access toolkit that provides a rich set of APIs for accessing relational and non-relational data. GORM also includes implementations for Hibernate (SQL), MongoDB, Cassandra, and Neo4j.
[Gorm](http://gorm.grails.org/)

I'm using GORM FOR HIBERNATE，In theory, Hibernate should be supported, but it doesn't work

I don't know how to configure it. I refer to the Spring Boot starter configuration and it doesn't work

step :
![image](https://user-images.githubusercontent.com/30860538/101149432-e5c7d500-3659-11eb-87bb-c551e95806e5.png)
![image](https://user-images.githubusercontent.com/30860538/101149464-f0826a00-3659-11eb-8bb6-46d75b7b5d71.png)

It started successfully, but it didn't work


please help me, Thank you very much

**Comment by terrymanu** [comment]
> It started successfully, but it didn't work

How to know it didn't work?

**Comment by zhangjiayu139** [comment]
我是用的是：sharding-jdbc-spring-boot-starter:4.1.1 这个包，我是用的框架底层是Spring boot2.1的，我理解应该是可以自动配置的，而且启动没有任何异常（也有可能没有自动配置），，，我用的orm框架是hibernate 高度封装的Gorm ，我理解应该也是支持的，，，我写的测试demo，数据并没有按照我预测的进入对应的表中，我猜测是不是需要替换底层的DataSource?

**Comment by terrymanu** [comment]
For english only. Can you translate?

**Comment by zhangjiayu139** [comment]
sorry
I used: sharding-jdbc-spring-boot-starter:4.1.1 this package, I am using the underlying framework is the spring boot2.1, I understand should be can automatically configure, and start without any abnormal (possibly with no automatic configuration),,, I am using orm framework hibernate is highly encapsulation Gorm, I understand should also support,,, I write test demo, data is not according to my forecast into the corresponding table, I wonder if we need to replace the underlying DataSource?

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 6 months, we will close it. 
If you still have related questions, please submit a new issue, thank you. 

In addition, the new version has been optimized a lot, welcome to experience.
