### ISSUE TITLE
Version 5.0 governance functions maven coordinate is less than

### ISSUE THREAD

**Issue by laiweiNo2** [apache/shardingsphere#8515]
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
			<version>5.0.0-alpha</version>
		</dependency>
		<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>shardingsphere-governance-repository-zookeeper-curator</artifactId>
			<version>5.0.0-alpha</version>
		</dependency>

**Comment by laiweiNo2** [comment]
Missing artifact org.apache.shardingsphere:shardingsphere-test:jar:5.0.0-alpha

**Comment by tristaZero** [comment]
Hi @laiweiNo2 
which operation caused the exception above? Could you provide more details?

**Comment by laiweiNo2** [comment]
> Hi @laiweiNo2
> which operation caused the exception above? Could you provide more details?

I just joined the coordinates in the pom file, will report the error

**Comment by tristaZero** [comment]
@laiweiNo2 It's not supposed to happen.
Hi @menghaoranss , could you give it a look?

**Comment by laiweiNo2** [comment]
> @laiweiNo2 It's not supposed to happen.
> Hi @menghaoranss , could you give it a look?

I changed to 4 x version, thank you

**Comment by tristaZero** [comment]
@laiweiNo2 So your issue was solved by using a later version? Which one?

**Comment by menghaoranss** [comment]
Shardingsphere-governance relies on `shardingsphere-test`  in 5.0.0-alpha，this issue has been fixed in the master branch, and if you want to use 5.0.0-alpha, please try with  the configuration below：

```
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.shardingsphere</groupId>
                    <artifactId>shardingsphere-test</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-governance-repository-zookeeper-curator</artifactId>
            <version>5.0.0-alpha</version>
        </dependency>
```

**Comment by laiweiNo2** [comment]
> @laiweiNo2 So your issue was solved by using a later version? Which one?

 I use another version

**Comment by laiweiNo2** [comment]
> Shardingsphere-governance relies on `shardingsphere-test` in 5.0.0-alpha，this issue has been fixed in the master branch, and if you want to use 5.0.0-alpha, please try with the configuration below：
> 
> ```
> <dependency>
>             <groupId>org.apache.shardingsphere</groupId>
>             <artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
>             <version>5.0.0-alpha</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>org.apache.shardingsphere</groupId>
>                     <artifactId>shardingsphere-test</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.shardingsphere</groupId>
>             <artifactId>shardingsphere-governance-repository-zookeeper-curator</artifactId>
>             <version>5.0.0-alpha</version>
>         </dependency>
> ```

Ok, thank you
