### ISSUE TITLE
After the introduction of ShardingJDBC, system startup slowed down

### ISSUE THREAD

**Issue by chentianming11** [apache/shardingsphere#8518]
![image](https://user-images.githubusercontent.com/30620547/101317059-b6eb7200-3898-11eb-94e2-629177ce4fc0.png)
For our system, only a few tables need to be divided into tables. But when starting, shardingJDBC initialized all table information, which caused the system to start too slowly!

version: sharding-jdbc-spring-boot-starter:4.0.3

**Comment by YX-GitH** [comment]
I used version: sharding-jdbc-core-4.1.1, which is the same problem

**Comment by tristaZero** [comment]
Hi could you try the latest release, i.e., 5.0.0-alpha which gives an improvement on this issue?
BTW, `check-table-metadata-enabled` is false in your example, doesn't it?

**Comment by terrymanu** [comment]
Closed because of no response
