### ISSUE TITLE
ShardingProxy Loss Transactional

### ISSUE THREAD

**Issue by duanzonglong** [apache/shardingsphere#8522]
## Question
version: shardingproxy 4.1.0    proxy.transaction.type: LOCAL
We loss java Transactional some times.
the code is like:
update oms_order set status=1 where id = 'xxxx'; // this sql is in oms database
orderApi.addOrder(orderDto);  // insert into wms_order values ();  this sql is in wms database and this is another micro service with springcloud feign interface.
Now the first sql is success,the second sql sometimes is false and no errors were obtained.
Sseing as they had some involvement with that "proxy.transaction.type: LOCAL".

**Comment by tristaZero** [comment]
> update oms_order set status=1 where id = 'xxxx'; 

Is `oms_order` a sharding table? 
[Transaction Intro](https://shardingsphere.apache.org/document/current/cn/features/transaction/use-norms/) will give you more details.

**Comment by duanzonglong** [comment]
yes,oms_order is a sharding table in oms schema,wms_order is a sharding table in wms schema. 
I have see the document.but  no errors were obtained.

**Comment by tristaZero** [comment]
Hi @duanzonglong 
You mean `Insert into wms_order values ()`  failed after the first update SQL? Have you ever tried to run this `INSERT` SQL singly？

**Comment by duanzonglong** [comment]
No
I mean the second sql is successed.but we can't find this order in database.

**Comment by tristaZero** [comment]
Hi @duanzonglong ,

So your question is about why the second SQL ran successfully but no any changes in the databases?

Could you set `sql.show` = `true` so that we can know what happened in detail.

**Comment by duanzonglong** [comment]
yes
ok,I'll do it.

**Comment by terrymanu** [comment]
Any update for this issue?

**Comment by terrymanu** [comment]
Closed because of no response.
