### ISSUE TITLE
“in” query slow

### ISSUE THREAD

**Issue by qwaszx92717** [apache/shardingsphere#8528]
When using “in” query, and the parameters have thousands of “ID”, the query speed will be very slow. Use "_+partitioned "  query speed  is normal. Here are some configuration data and troubleshooting data.

config
![image](https://user-images.githubusercontent.com/24630042/101450401-773e8c00-3965-11eb-996d-e9f6c58176cf.png)

query sharding log
![image](https://user-images.githubusercontent.com/24630042/101449975-b4564e80-3964-11eb-884b-40bedcb09ab0.png)

testing environment
1.using sharding、50w data、sql:select * from table where column in (...)、condition have index, not shardingid. query time 15s
2.not used sharding，ditto. query time  less 0.2s

**Comment by tristaZero** [comment]
Hi @qwaszx92717 ,

Thanks for your info.
ShardingSphere helps user handle SQLs queried in a database cluster though, the consuming time your provided is longer than expected.
The actual SQL is executed in MySQL using the index, isn't it?
Have you ever counted how many seconds one actual SQL takes? I am curious where that `15s` is used.

**Comment by qwaszx92717** [comment]
> Hi @qwaszx92717 ,
> 
> Thanks for your info.
> ShardingSphere helps user handle SQLs queried in a database cluster though, the consuming time your provided is longer than expected.
> The actual SQL is executed in MySQL using the index, isn't it?
> Have you ever counted how many seconds one actual SQL takes? I am curious where that `15s` is used.

This column have index.
At that time，I connect some shading database and try to execute SQL in some sharding table. 
example：select * from **table_1** where column in (...); this query speed is very fast.
after troubleshooting ，I print the stack information ，found that most of the time it was pointing to sharding.
sharding log as above,but no useful information was found.

**Comment by qwaszx92717** [comment]
sharding version ：4.0.1

**Comment by tristaZero** [comment]
I guess you can get the execution time, like 
```
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - Logic SQL: select * from t_order where order_id in (1,2)
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_0 ::: select * from t_order_0 where order_id in (1,2)
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_0 ::: select * from t_order_1 where order_id in (1,2)
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_1 ::: select * from t_order_0 where order_id in (1,2)
[INFO ] 14:05:43.837 [ShardingSphere-Command-8] ShardingSphere-SQL - Actual SQL: ds_1 ::: select * from t_order_1 where order_id in (1,2)
---- New one
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - Logic SQL: select * from t_order_item
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_0 ::: select * from t_order_item_0
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_0 ::: select * from t_order_item_1
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_1 ::: select * from t_order_item_0
[INFO ] 14:06:07.247 [ShardingSphere-Command-9] ShardingSphere-SQL - Actual SQL: ds_1 ::: select * from t_order_item_1
```

**Comment by terrymanu** [comment]
Closed because of no response

**Comment by rouxiaoxiao** [comment]
I have the same problem, is there a solution? sharding version ：4.0.1
