### ISSUE TITLE
still not work, cant compile, wtf? 

### ISSUE THREAD

**Issue by gravin** [apache/shardingsphere#8531]
[INFO] Finished at: 2020-12-08T17:33:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shardingsphere-proxy-docker-build: Could not resolve dependencies for project org.apache.sha
rdingsphere:shardingsphere-proxy-docker-build:jar:5.0.0-alpha: Failure to find org.apache.shardingsphere:shardingsphere-test-fixture:j
ar:tests:5.0.0-alpha in https://maven.aliyun.com/repository/public was cached in the local repository, resolution will not be reattemp
ted until the update interval of aliyunmaven has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shardingsphere-proxy-docker-build

**Comment by gravin** [comment]
no matter brach 5 ,branch 4, or master ,all cant compile
for master, it gives issue

Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-proxy-docker-build:jar:5.0.0-RC1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-test-fixture:jar:tests:5.0.0-RC1-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots)

**Comment by terrymanu** [comment]
@gravin 
Please keep grace. 
I just report abuse for your impolite words to GitHub, please pay attention next time.
