### ISSUE TITLE
WHERE (user_id, order_id) IN  ( (?,?) ,  (?,?) ) has ClassCastException:

### ISSUE THREAD

**Issue by fourier416** [apache/shardingsphere#8542]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
sql:SELECT * FROM pay_info WHERE (user_id, order_id) IN  ( (?,?) ,  (?,?) )

### Actual behavior
Caused by: java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment cannot be cast to org.apache.shardingsphere.sql.parser.sql.segment.dml.column.ColumnSegment
	
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
order_info:
          actual-data-nodes: ds0.pay_info
          table-strategy:
            inline:
              algorithm-expression: pay_info
              sharding-column: order_id

**Comment by tristaZero** [comment]
Hi @fourier416 
If you have to query with `WHERE (user_id, order_id) IN`, 5.0.0-alpha has better support than 4.x release. But my suggestion is to replace it with another equivalently semantic one.
