### ISSUE TITLE
shardingsphere-jdbc-core-spring-boot-starter not installed in maven central repository

### ISSUE THREAD

**Issue by gravin** [apache/shardingsphere#8547]
why not install all of them in maven central?
it will take one hour to build and install from source code, and always have build issues because of change.

**Comment by gravin** [comment]
this also make it impossible to deploy,  need everyone to install from source code

**Comment by menghaoranss** [comment]
```
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0-alpha</version>
</dependency>
```
