### ISSUE TITLE
read and write separation problem

### ISSUE THREAD

**Issue by shenHaoRanDe** [apache/shardingsphere#8553]
sharding_jdbc:4.1.1

Does shardingjdbc support separation of read and write for some tables, while other tables are directly routed to the main database

**Comment by tristaZero** [comment]
Hi @shenHaoRanDe ,
Please give a look to [HINT](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/hint/).

**Comment by terrymanu** [comment]
Closed because of no response
