### ISSUE TITLE
wrong of examples of shardingsphere official documents 

### ISSUE THREAD

**Issue by CrazyFz** [apache/shardingsphere#8556]
[error_url](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/java-api/) 

### error 1
A left parenthesis here is redundant
![error1](https://user-images.githubusercontent.com/22133156/101721787-b98dd780-3ae3-11eb-861f-e21da353dd40.png)

document example error code 
**
// 创建 ShardingSphereDataSource
DataSource dataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton((shardingRuleConfig), new Properties());
**

### error 2
Variable name error
![image](https://user-images.githubusercontent.com/22133156/101722112-7aac5180-3ae4-11eb-9d1d-1705475aa0ed.png)

Code block of try  
the  variable PreparedStatement  is ps  not preparedStatement

document example error code 
**
    PreparedStatement ps = conn.prepareStatement(sql)) {
    ps.setInt(1, 10);
    ps.setInt(2, 1000);
    try (ResultSet rs = preparedStatement.executeQuery()) {
        while(rs.next()) {
            // ...
        }
    }
**

**Comment by menghaoranss** [comment]
@CrazyFz Thanks for your feedback, could you please submit a PR to fix it?

**Comment by fyuan1030** [comment]
> @CrazyFz Thanks for your feedback, could you please submit a PR to fix it?
I think [this page](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/governance/) has a error too;
there are just Zookeeper and Etcd implement RegistryRepository；Apollo and Nacos didn't implement RegistryRepository
![image](https://user-images.githubusercontent.com/38123832/101738124-ab9a7f80-3b00-11eb-981a-eac68ce0d65f.png)

**Comment by CrazyFz** [comment]
> @CrazyFz感谢您的反馈，能否请您提交PR进行修复？

ok，I try
