### ISSUE TITLE
beanClassName may be null

### ISSUE THREAD

**Issue by hegw** [apache/shardingsphere#8561]
https://github.com/apache/shardingsphere/blob/c05b58b1610b18503f436a61db1d24dba72c7e33/shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-spring-infra/shardingsphere-jdbc-spring-namespace-infra/src/main/java/org/apache/shardingsphere/spring/namespace/registry/ShardingSphereAlgorithmBeanRegistry.java#L48

here `parserContext.getRegistry().getBeanDefinition(each).getBeanClassName()` may got a **null** value，check null value first may be a good choice。

**Comment by menghaoranss** [comment]
@hegw What configuration will causes NPE  here, could you provide a configuration demo?

**Comment by hegw** [comment]
The project already use [redissson ](https://github.com/redisson/redisson/)framework
```
    <redisson:client id="redissonClient" netty-threads="20" threads="20" name="redissonClinet">
        <redisson:cluster-servers
                idle-connection-timeout="${redisson.idleConnectionTime}"
                connect-timeout="${redisson.connectTimeout}"
                timeout="${redisson.timeout}"
                retry-attempts="${redisson.retryAttempts}"
                retry-interval="${redisson.retryInterval}"
                scan-interval="${redisson.scanInterval}"
                client-name="cleitName">
            <redisson:node-address value="${redisson.hostAndPort1}" />
            <redisson:node-address value="${redisson.hostAndPort2}" />
            <redisson:node-address value="${redisson.hostAndPort3}" />
            <redisson:node-address value="${redisson.hostAndPort4}" />
            <redisson:node-address value="${redisson.hostAndPort5}" />
            <redisson:node-address value="${redisson.hostAndPort6}" />
        </redisson:cluster-servers>
    </redisson:client>
```
and when I use **shardingsphere-jdbc-5.0.0-alpha** version in project，in the proccess of application startup, [ShardingSphereAlgorithmBeanRegistry ](https://github.com/apache/shardingsphere/blob/c05b58b1610b18503f436a61db1d24dba72c7e33/shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-spring-infra/shardingsphere-jdbc-spring-namespace-infra/src/main/java/org/apache/shardingsphere/spring/namespace/registry/ShardingSphereAlgorithmBeanRegistry.java#L48) class iterate all beanDefinitions by **beanDefinitionNames**，but there was a beanDefination‘s '**beanClassName**' attribute was null，and then when it **equals** with _**algorithmFactoryBeanClassName**_,  it causes **NPE** 

![图片1](https://user-images.githubusercontent.com/982953/101888907-ba089a00-3bd9-11eb-9b33-2e65cbf581ac.png)
![图片2](https://user-images.githubusercontent.com/982953/101889005-defd0d00-3bd9-11eb-80fe-224e34f35d06.png)

**Comment by smallericcc** [comment]
I have missed this bug too. could you Provide a solution for this thanks.

**Comment by smallericcc** [comment]
@terrymanu

**Comment by terrymanu** [comment]
There are lots of dependencies to reproduce this issue.
Does anyone can help to analyze the issue and make the reproduce condition easy?

**Comment by TeslaCN** [comment]
Spring modules have been deprecated and removed since 5.3.0. Please use the new way to integrate ShardingSphere with Spring Boot.
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/
