### ISSUE TITLE
Cannot invoke method mod() on null object] with root cause

### ISSUE THREAD

**Issue by 50133142** [apache/shardingsphere#8568]
Use version ：5.0.0-RC1-SNAPSHOT
Two kudos, 16 tables

![image](https://user-images.githubusercontent.com/42038247/101794037-69ddf900-3b41-11eb-9051-2b7f3faa8a9a.png)

分片建传了一个null，但是如下图有数据呀
![image](https://user-images.githubusercontent.com/42038247/101794064-719d9d80-3b41-11eb-8cb0-0878f72943bc.png)

**Comment by 50133142** [comment]
图片显示不全

**Comment by Jearys** [comment]
请问这个问题是怎么解决的呢，我也遇到了相同的问题

**Comment by DengQin** [comment]
请问怎么解决的呢
