### ISSUE TITLE
Amazing problem，my broadcast table disappear suddenly。

### ISSUE THREAD

**Issue by luckleemon** [apache/shardingsphere#8573]
two weeks ago，i config the broadcast table in yaml file， and insert the broadcast table data into the sharding database，then i use it to test， and it works well。

but yesterday，i found the broadcast table disappear， but my config is still here， i do not know what happens。

ps：no one delete them，my linux system has enough disk space，enough ram。

hope your reply。

thank you very much。

**Comment by menghaoranss** [comment]
You should check the log first
