### ISSUE TITLE
sharding-sphere3.0.0+mybatisplus2.1.4+mysql, batchInsert  error, help me !!!

### ISSUE THREAD

**Issue by guid-git** [apache/shardingsphere#8577]
### Cause: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:255)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:131)
	... 37 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.accumulate(BatchPreparedStatementExecutor.java:176)
	at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.executeBatch(BatchPreparedStatementExecutor.java:168)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeBatch(ShardingPreparedStatement.java:236)

**Comment by guid-git** [comment]
private int[] accumulate(final List<int[]> results) {
        int[] result = new int[batchCount];
        int count = 0;
        for (BatchRouteUnit each : routeUnits) {
            for (Entry<Integer, Integer> entry : each.getJdbcAndActualAddBatchCallTimesMap().entrySet()) {
              ###   **int value = null == results.get(count) ? 0 : results.get(count)[entry.getValue()];**
                if (DatabaseType.Oracle == getDatabaseType()) {
                    result[entry.getKey()] = value;
                } else {
                    result[entry.getKey()] += value;
                }
            }
            count++;
        }
        return result;
    }

**Comment by terrymanu** [comment]
I don't know what is mybatis-plus do, could you get the actual SQL and jdbc method?

**Comment by qixiaobo** [comment]
> I don't know what is mybatis-plus, could you get the actual SQL and jdbc method?

It's a framework based on mybatis https://github.com/baomidou/mybatis-plus (MyBatis-Plus is an powerful enhanced toolkit of MyBatis for simplify development. This toolkit provides some efficient, useful, out-of-the-box features for MyBatis, use it can effectively save your development time.).
Maybe @guid-git should provide more info

**Comment by guid-git** [comment]
for example, i call mybatis-plus's method ExampleService.insertBatch(list). when list's size is 10, sharding-sphere will put the same table data in one sql. such like '' insert into table values(),()"".   then look the method i said above "accumulate", each.getJdbcAndActualAddBatchCallTimesMap().entrySet() ’s size is 2。but when i debug the param "final List<int[]> results" of the method "accumulate" , i get the param int[] 'size is 1, so throw java.lang.ArrayIndexOutOfBoundsException:1

**Comment by RaigorJiang** [comment]
It is recommended that you first check whether the SQL is correct, so please provide your actual SQL, not the Java code.

**Comment by terrymanu** [comment]
Closed because of no response
