### ISSUE TITLE
Confusing about the method `equals` in DataSourceConfiguration

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#8593]
## Question

I wonder why 2 instances of `DataSourceConfiguration` having different properties are considered to be equivalent.

https://github.com/apache/shardingsphere/blob/e3c6e9df48f88af9e49232f51fe54f7139a16121/shardingsphere-infra/shardingsphere-infra-common/src/test/java/org/apache/shardingsphere/infra/config/DataSourceConfigurationTest.java#L95-L106

![image](https://user-images.githubusercontent.com/20503072/101976925-ee856000-3c84-11eb-965e-38ba22d36da9.png)

`org.apache.shardingsphere.infra.config.datasource.DataSourceConfiguration#equalsByProperties`

https://github.com/apache/shardingsphere/blob/e3c6e9df48f88af9e49232f51fe54f7139a16121/shardingsphere-infra/shardingsphere-infra-common/src/main/java/org/apache/shardingsphere/infra/config/datasource/DataSourceConfiguration.java#L164-L166

**Comment by terrymanu** [comment]
I check the commit log, it shows `Fix issue for data source cannot renew`

Can you check it if you are interesting?

**Comment by TeslaCN** [comment]
I have checked it, but I still don't know why. Why `DataSourceConfiguration` with property `username=sa` equals to `username=sa,password=sth`?

**Comment by terrymanu** [comment]
DataSourceConfiguration is refactored by 5.0.0, this issue is staled.
