### ISSUE TITLE
table for unconfigured "SELECT t.*, t2.col FROM t LEFT JOIN t2" not work

### ISSUE THREAD

**Issue by iblilife** [apache/shardingsphere#8605]
### Which version of ShardingSphere did you use?

`mysql 8.0.20`
`spring boot 2.2.5.RELEASE`

```xml
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core</artifactId>
    <version>5.0.0-alpha</version>
</dependency>
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
```ShardingSphere-JDBC```

### Table
```sql
CREATE TABLE `card_type` (
  `id` bigint NOT NULL,
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '',
  `code_no` varchar(20) NOT NULL DEFAULT '' COMMENT '',
  `shop_id` bigint NOT NULL COMMENT '',
  `create_date_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `create_employee_id` bigint NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE `shop_employee` (
  `id` bigint NOT NULL COMMENT '',
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE
)
```
### sharding yaml config
`card_type`  `shop_employee` don't need  sharding。unconfigured in yaml file。

### Mybatis mapper.xml
```xml
<select id="fetchCardTypeList" resultType="java.util.Map">
    SELECT 
        ct.* ,
        se.name as empName
    FROM card_type ct 
    LEFT JOIN shop_employee se ON (se.id = ct.create_employee_id)
</select>
```

### Results 
return resultset columns is empty。

**Comment by iblilife** [comment]
add code 
```yml
rules:
- !SHARDING
  tables:
    card_type:
      actualDataNodes: princess.card_type
    shop_employee:
      actualDataNodes: princess.shop_employee
```
working normal

**Comment by huanghao495430759** [comment]
Try recafctor their configuration to broadcast-tables ?

rules:
  sharding:
	broadcast-tables: card_type,shop_employee

**Comment by huanghao495430759** [comment]
Try reconfigure their configuration to broadcast-tables ?

rules:
sharding:
broadcast-tables: card_type,shop_employee

**Comment by tristaZero** [comment]
> broadcast-tables: card_type,shop_employee

That's one great solution If two of these tables do not have a large volume of rows. Besides, does a simple SQL queried on `unconfigured table` run well?

**Comment by iblilife** [comment]
> > broadcast-tables: card_type,shop_employee
> 
> That's one great solution If two of these tables do not have a large volume of rows. Besides, does a simple SQL queried on `unconfigured table` run well?

Simple SQL works well。

`SELECT t1.* FROM t1` // run ok
`SELECT t2.* FROM t2` // run ok
`SELECT t1.*, t2.id FROM t1 LEFT JOIN t2` // failed，data column does not have。

**Comment by strongduanmu** [comment]
@iblilife Hi, I have used the native JDBC api to test the SQL you provided, and the `left join` is OK. Can you provide more information that you encountered?

**Comment by iblilife** [comment]
@strongduanmu 
# case 1, FAILED
> `card_type` `shop_employee` don't need sharding。unconfigured in yaml file。

mybatis mapper.xml
```xml
  <select id="fetchCardTypeList" resultType="java.util.Map">
    SELECT
      ct.*,
      cemp.name as createEmpName
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = #{shopId}

    <!--
     // RUN FAILED
     SELECT
      ct.id,
      cemp.*
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = #{shopId}
     -->
  </select>
```
console log
```text
[13:28:49:830] [INFO] - org.apache.shardingsphere.infra.executor.sql.log.SQLLogger.log(SQLLogger.java:74) - Logic SQL: SELECT
      ct.*,
      cemp.name as createEmpName
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = ? LIMIT ? 
[13:28:49:830] [INFO] - org.apache.shardingsphere.infra.executor.sql.log.SQLLogger.log(SQLLogger.java:74) - SQLStatement: MySQLSelectStatement(limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@5e8f0b00], lock=Optional.empty)
[13:28:49:830] [INFO] - org.apache.shardingsphere.infra.executor.sql.log.SQLLogger.log(SQLLogger.java:74) - Actual SQL: princess ::: SELECT
      ct.*,
      cemp.name as createEmpName
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = ? LIMIT ?  ::: [498914881295097857, 10]
[13:28:49:832] [DEBUG] - org.apache.ibatis.logging.jdbc.BaseJdbcLogger.debug(BaseJdbcLogger.java:143) - <==      Total: 7
```
debug
![debug_img_1](https://jzray.oss-cn-shenzhen.aliyuncs.com/temp/debug_img_1.png)

# case 2, OK
mybatis mapper.xml
```xml
<select id="fetchCardTypeList" resultType="java.util.Map">
    SELECT
      ct.*
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = #{shopId}
</select>
```
![debug_img_2](https://jzray.oss-cn-shenzhen.aliyuncs.com/temp/debug_img_2.png)

# case 3, OK
mybatis mapper.xml
```xml
  <select id="fetchCardTypeList" resultType="java.util.Map">
    SELECT
      cemp.*
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = #{shopId}
   </select>
```
![debug_img_5](https://jzray.oss-cn-shenzhen.aliyuncs.com/temp/debug_img_5.png)

# case 4, OK
mybatis mapper.xml
```xml
  <select id="fetchCardTypeList" resultType="java.util.Map">
    SELECT
      ct.*,
      cemp.*
    FROM card_type ct
    left join shop_employee cemp on (cemp.id = ct.create_employee_id)
    where ct.shop_id = #{shopId}
   </select>
```

**Comment by iblilife** [comment]
@tristaZero @huanghao495430759 

My English Very Poor！Help me fixed this bug，thx！Orz...

I found the cause of the bug。

java: org.apache.shardingsphere.infra.metadata.model.logic.LogicSchemaMetaDataLoader

`org.apache.shardingsphere.infra.metadata.model.logic.LogicSchemaMetaDataLoader#load(org.apache.shardingsphere.infra.database.type.DatabaseType, java.util.Map<java.lang.String,javax.sql.DataSource>, org.apache.shardingsphere.infra.config.properties.ConfigurationProperties)
` 
Not init unconfigured tables `SchemaMetaData`

Cause `org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData#getColumnCount` to get wrong data

```java
    public LogicSchemaMetaData load(final DatabaseType databaseType, final Map<String, DataSource> dataSourceMap,
                                    final ConfigurationProperties props) throws SQLException {
        Collection<String> excludedTableNames = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
        PhysicalSchemaMetaData configuredSchemaMetaData = new PhysicalSchemaMetaData();
        for (Entry<ShardingSphereRule, LogicMetaDataLoader> entry : OrderedSPIRegistry.getRegisteredServices(rules, LogicMetaDataLoader.class).entrySet()) {
            PhysicalSchemaMetaData schemaMetaData = entry.getValue().load(databaseType, dataSourceMap, new DataNodes(rules), entry.getKey(), props, excludedTableNames);
            excludedTableNames.addAll(schemaMetaData.getAllTableNames());
            if (entry.getKey() instanceof DataNodeRoutedRule) {
                excludedTableNames.addAll(((DataNodeRoutedRule) entry.getKey()).getAllActualTables());
            }
            configuredSchemaMetaData.merge(schemaMetaData);
        }
        decorate(configuredSchemaMetaData);
        Map<String, Collection<String>> unConfiguredSchemaMetaDataMap = loadUnConfiguredSchemaMetaData(databaseType, dataSourceMap, excludedTableNames);
        /**********************************************************************
        //
        // Here should be initialized unconfigured tables SchemaMetaData
        //
        **/
        return new LogicSchemaMetaData(configuredSchemaMetaData, unConfiguredSchemaMetaDataMap);
    }
```

**Comment by tristaZero** [comment]
@iblilife Thanks for your detailed info. Which SQL were you running for debugging?
@strongduanmu Could you give it a check?

**Comment by gavenpeng** [comment]
we have the same problem,the fllower sql is can.t run :
```
select ta.*,tb.track_count from (select ID,activity_id,name,begin_time,end_time,first_shelf_time,last_shelf_time,description,operate_surface_url,big_surface_url,sort,status,show_status,created_by,updated_by,create_time,update_time 
from dub_read_activity) ta left join (
select activity_id,count(*) as track_count
from dub_read_track
where is_deleted = 0 and status = 1 group by activity_id ) tb on ta.activity_id = tb.activity_id
limit
  1, 10 
```
the result is only contain id clumn if the sql constain * 



but not write * is ok,example:
```
select ta.ID,ta.name,ta.last_shelf_time,ta.create_time,tb.track_count from (select ID,activity_id,name,begin_time,end_time,first_shelf_time,last_shelf_time,description,operate_surface_url,big_surface_url,sort,status,show_status,created_by,updated_by,create_time,update_time 
from dub_read_activity) ta left join (
select activity_id,count(*) as track_count
from dub_read_track
where is_deleted = 0 and status = 1 group by activity_id ) tb on ta.activity_id = tb.activity_id
order by
  track_count desc,
  last_shelf_time desc,
  create_time desc
limit
  1, 10 

```

**Comment by iblilife** [comment]
> @iblilife Thanks for your detailed info. Which SQL were you running for debugging?
> @strongduanmu Could you give it a check?

table
```sql
CREATE TABLE `card_type` (
  `id` bigint NOT NULL,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '',
  `create_employee_id` bigint NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE `shop_employee` (
  `id` bigint NOT NULL COMMENT '',
  `name` varchar(50)  NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE
)
```

sql of debuging
```sql
select
  ct.*,
  emp.name
from card_type ct
left join shop_employee emp on (emp.id = ct.create_employee_id)
```

**Comment by strongduanmu** [comment]
@iblilife I noticed that you use the `PageHelper` framework. Can you submit a demo program to help me reproduce the problem? 😊

**Comment by iblilife** [comment]
> @iblilife I noticed that you use the `PageHelper` framework. Can you submit a demo program to help me reproduce the problem? 😊

Demo Github: https://github.com/iblilife/shardingjdbc-demo

look at the code for 'com.example.shardingjdbc.demo.DemoApplication#run'

**Comment by strongduanmu** [comment]
> > @iblilife I noticed that you use the `PageHelper` framework. Can you submit a demo program to help me reproduce the problem? 😊
> 
> Demo Github: https://github.com/iblilife/shardingjdbc-demo
> 
> look at the code for 'com.example.shardingjdbc.demo.DemoApplication#run'

@iblilife Thank you very much for the detailed demo, I will test it. 👍

**Comment by huanghao495430759** [comment]
when I used @iblilife's sql:
`SELECT a.*, b.id FROM table_a a LEFT JOIN table_b b ON (a.id = b.id)`;
and shardingsphere-5.0.0-RC1-SNAPSHOT have the same proplem.

when shardingsphere create ShardingSpherePreparedStatement
I think the bug may be at SchemaBuilder.java line 70:
![image](https://user-images.githubusercontent.com/34728144/104438647-2b69ad00-55cb-11eb-9750-964239b63f6e.png)

 when load unconfig tables MeataData,it only init TableMetaData(), but doesn't load table columns,
so when doQuery in :
`
->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute
->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#createExecutionContext
->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#createLogicSQL
->org.apache.shardingsphere.infra.binder.SQLStatementContextFactory#newInstance
->new SelectStatementContext
->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionsContextEngine#createProjectionsContext
->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionsContextEngine#getProjections
->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionEngine#createProjection(final Collection<SimpleTableSegment> tableSegments, final ShorthandProjectionSegment projectionSegment)
->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionEngine#getShorthandColumns
`
when get ShorthandColumns, table columns is empty
![image](https://user-images.githubusercontent.com/34728144/104438411-efcee300-55ca-11eb-9433-925d656fc4b5.png)
so after  ShardingSpherePreparedStatement#execute, 
and handle resultSet
![image](https://user-images.githubusercontent.com/34728144/104438860-7257a280-55cb-11eb-9e63-938cc9d59004.png)
`
->org.apache.ibatis.executor.resultset.DefaultResultSetHandler#handleResultSets
->org.apache.ibatis.executor.resultset.DefaultResultSetHandler#getFirstResultSet
->org.apache.ibatis.executor.resultset.ResultSetWrapper#ResultSetWrapper()
->org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData#getColumnCount
->org.apache.shardingsphere.infra.binder.segment.select.projection.ProjectionsContext#getExpandProjections
`
![image](https://user-images.githubusercontent.com/34728144/104439228-d9755700-55cb-11eb-985e-20642a7e5a6c.png)
![image](https://user-images.githubusercontent.com/34728144/104439686-5a345300-55cc-11eb-872c-43856b826311.png)

in this code, ShorthandProjection actual columns is empty,so after getExpandProjections(), columnCount is only 1
![image](https://user-images.githubusercontent.com/34728144/104439787-7c2dd580-55cc-11eb-99c9-ca2a7525045d.png)

![image](https://user-images.githubusercontent.com/34728144/104440276-1b52cd00-55cd-11eb-96d7-6951241b3559.png)
and ResultSet only get one column。

so  I think bug maybe at 
`
->org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder#appendRemainTables line 70
`
![image](https://user-images.githubusercontent.com/34728144/104441089-32de8580-55ce-11eb-82d2-7e73196a7dbd.png)
shardingsphere must be load remain table MetaData when System start.

**Comment by huanghao495430759** [comment]
> when I used @iblilife's sql:
> `SELECT a.*, b.id FROM table_a a LEFT JOIN table_b b ON (a.id = b.id)`;
> and shardingsphere-5.0.0-RC1-SNAPSHOT have the same proplem.
> 
> when shardingsphere create ShardingSpherePreparedStatement
> I think the bug may be at SchemaBuilder.java line 70:
> ![image](https://user-images.githubusercontent.com/34728144/104438647-2b69ad00-55cb-11eb-9750-964239b63f6e.png)
> 
> when load unconfig tables MeataData,it only init TableMetaData(), but doesn't load table columns,
> so when doQuery in :
> `->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#execute ->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#createExecutionContext ->org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement#createLogicSQL ->org.apache.shardingsphere.infra.binder.SQLStatementContextFactory#newInstance ->new SelectStatementContext ->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionsContextEngine#createProjectionsContext ->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionsContextEngine#getProjections ->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionEngine#createProjection(final Collection<SimpleTableSegment> tableSegments, final ShorthandProjectionSegment projectionSegment) ->org.apache.shardingsphere.infra.binder.segment.select.projection.engine.ProjectionEngine#getShorthandColumns`
> when get ShorthandColumns, table columns is empty
> ![image](https://user-images.githubusercontent.com/34728144/104438411-efcee300-55ca-11eb-9433-925d656fc4b5.png)
> so after ShardingSpherePreparedStatement#execute,
> and handle resultSet
> ![image](https://user-images.githubusercontent.com/34728144/104438860-7257a280-55cb-11eb-9e63-938cc9d59004.png)
> `->org.apache.ibatis.executor.resultset.DefaultResultSetHandler#handleResultSets ->org.apache.ibatis.executor.resultset.DefaultResultSetHandler#getFirstResultSet ->org.apache.ibatis.executor.resultset.ResultSetWrapper#ResultSetWrapper() ->org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData#getColumnCount ->org.apache.shardingsphere.infra.binder.segment.select.projection.ProjectionsContext#getExpandProjections`
> ![image](https://user-images.githubusercontent.com/34728144/104439228-d9755700-55cb-11eb-985e-20642a7e5a6c.png)
> ![image](https://user-images.githubusercontent.com/34728144/104439686-5a345300-55cc-11eb-872c-43856b826311.png)
> 
> in this code, ShorthandProjection actual columns is empty,so after getExpandProjections(), columnCount is only 1
> ![image](https://user-images.githubusercontent.com/34728144/104439787-7c2dd580-55cc-11eb-99c9-ca2a7525045d.png)
> 
> ![image](https://user-images.githubusercontent.com/34728144/104440276-1b52cd00-55cd-11eb-96d7-6951241b3559.png)
> and ResultSet only get one column。
> 
> so I think bug maybe at
> `->org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder#appendRemainTables line 70`
> ![image](https://user-images.githubusercontent.com/34728144/104441089-32de8580-55ce-11eb-82d2-7e73196a7dbd.png)
> shardingsphere must be load remain table MetaData when System start.

@strongduanmu
@tristaZero

**Comment by huanghao495430759** [comment]
I see Liang Zhang had fix this issue at 2021-01-18.
`org.apache.shardingsphere.driver.jdbc.core.resultset.ShardingSphereResultSetMetaData#getColumnCount line 52.`
![image](https://user-images.githubusercontent.com/34728144/105297113-fb3a9380-5bf4-11eb-925a-d77162aac642.png)

@tristaZero @iblilife @strongduanmu

**Comment by tristaZero** [comment]
@huanghao495430759 ,

Yep, our IT engines found this bug and we fixed it. If this change is relevant to yours, do you think it is time to close this one?
