### ISSUE TITLE
Consider about quote character with CREATE SHARDING RULE

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8618]
Support quote character with names of sharding table and sharding column.

**Comment by zhujunxxxxx** [comment]
@terrymanu can you give some test case for this issues, I want to try.

**Comment by terrymanu** [comment]
@zhujunxxxxx Thank you for interest the issue, @menghaoranss will give some new idea on this.

**Comment by RaigorJiang** [comment]
Hi  @menghaoranss 
Can you provide more information about this issue?

**Comment by menghaoranss** [comment]
> Hi @menghaoranss
> Can you provide more information about this issue?

We need to sort out which fields need to be supported just like :

```
CREATE SHARDING TABLE RULE `t_order`(...)
```

**Comment by RaigorJiang** [comment]
Got it!

**Comment by RaigorJiang** [comment]
I think these statements should be considered:
```sql
- CREATE SHARDING TABLE RULE
- ALTER SHARDING TABLE RULE
- DROP SHARDING TABLE RULE

- CREATE SHARDING BROADCAST TABLE RULES
- ALTER SHARDING BINDING TABLE RULES
- DROP SHARDING BINDING TABLE RULES

- CREATE SHARDING BROADCAST TABLE RULES
- ALTER SHARDING BROADCAST TABLE RULES 
- DROP SHARDING BROADCAST TABLE RULES

- CREATE ENCRYPT RULE
- ALTER ENCRYPT RULE
- DROP ENCRYPT RULE
```
We can discuss about them.

Hi @zhujunxxxxx 
Are you interested in handling this issue？

**Comment by lanchengx** [comment]
@RaigorJiang  I can try to investigate.

**Comment by RaigorJiang** [comment]
> @RaigorJiang I can try to investigate.

@lanchengx  Thank you~
