### ISSUE TITLE
【shardingproxy-5.0.0-alpha】Can not route tables for `[PSNL_POTN_CUST_CNTWY]`, please make sure the tables are in same schema

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8621]
I have config default route rule for table  PSNL_POTN_CUST_CNTWY， but it doesn‘t work.

config:

config-sharding.yaml

schemaName: sharding_db5

dataSourceCommon:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  ds_0:
    url: jdbc:mysql://190.11.1.4:3306/test_db_0?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  ds_1:
    url: jdbc:mysql://190.11.1.5:3306/test_db_1?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  ds_2:
    url: jdbc:mysql://190.11.1.6:3306/test_db_2?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  ds_3:
    url: jdbc:mysql://190.11.1.7:3306/test_db_3?serverTimezone=UTC&useSSL=false
    username: root
    password: root

rules:
- !SHARDING
  tables:
    PBCST_QRY_INFO:
      actualDataNodes: ds_${0..3}.PBCST_QRY_INFO_${0..15}
      tableStrategy:
        standard:
          shardingColumn: ECIF_CUST_NO
          shardingAlgorithmName: PBCST_QRY_INFO_inline
      databaseStrategy:
        standard:
          shardingColumn: ECIF_CUST_NO
          shardingAlgorithmName: database_inline          
      keyGenerateStrategy:
        column: ECIF_CUST_NO
        keyGeneratorName: snowflake
        
  defaultDatabaseStrategy:
    standard:
      shardingColumn: ECIF_CUST_NO
      shardingAlgorithmName: database_default	    
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_default:
      type: INLINE
      props:
        algorithm-expression: ds_0
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${Math.abs(ECIF_CUST_NO.hashCode() % 4)}		
    PBCST_QRY_INFO_inline:
      type: INLINE
      props:
        algorithm-expression: PBCST_QRY_INFO_${Math.abs(ECIF_CUST_NO.hashCode() % 16)}
		
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
<img width="751" alt="图片1" src="https://user-images.githubusercontent.com/46663706/102168661-968c6a80-3ecb-11eb-9d10-a94c72be04fe.png">

**Comment by menghaoranss** [comment]
@duzhanfei Please confirm whether the table name is PSNL_POTN_CUST_CNTWY or psnl_potn_cust_cntwy

**Comment by duzhanfei** [comment]
①  when the talbe name is PSNL_POTN_CUST_CNTWY  ,   
tips in navicat showed as below  
0002 - 2Unknown exception: [Can not route tables for `[PSNL_POTN_CUST_CNTWY]`, please make sure the tables are in same schema.

②when the talbe name is psnl_potn_cust_cntwy  , 
The above error message will not appear in navicat ,
but we can know that the route for the  table is incorrect: the default database is ds_0 , but   the routed database  for psnl_potn_cust_cntwy   is  ds_3
<img width="761" alt="图片3" src="https://user-images.githubusercontent.com/46663706/102190549-2691da80-3ef3-11eb-8d8f-c2a2cb97ada9.png">


by the way, 
Are there any requirements for case in SQL statements when using proxy?
Is the default database configured correctly?

**Comment by duzhanfei** [comment]
@menghaoranss

**Comment by as882301** [comment]
我也是遇到 这种问题 请问你解决了吗

**Comment by duzhanfei** [comment]
单独指定一下路由试试



在 2021-04-08 09:15:56，"QJ" ***@***.***> 写道：

我也是遇到 这种问题 请问你解决了吗

**Comment by uestcwsy** [comment]
Do you define a table in the entity class or mybatis mapper? Remember to remove the complete definition and make a mapping

**Comment by terrymanu** [comment]
I just close this issue because of no feedback for long time.
