### ISSUE TITLE
run shardingsphere5.0.0-alpha error

### ISSUE THREAD

**Issue by xuup** [apache/shardingsphere#8631]
## Question

downloading src from https://www.apache.org/dyn/closer.cgi/shardingsphere/5.0.0-alpha/apache-shardingsphere-5.0.0-alpha-src.zip , run class ShardingSphereConnectionTest has error.

Error:(26, 52) java: org.apache.shardingsphere.sql.parser.autogen not exist
Error:(27, 77) java: org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParser not exist
Error:(28, 77) java: org.apache.shardingsphere.sql.parser.autogen.SQLServerStatementParserexist
...
## Error
![image](https://user-images.githubusercontent.com/33018640/102223002-1c85d100-3f1f-11eb-8171-aa2babf6de0c.png)
![image](https://user-images.githubusercontent.com/33018640/102223120-417a4400-3f1f-11eb-81d7-4ae2b0b2aa28.png)

I don't change any code , just want to run test, what should I do? thx!

**Comment by terrymanu** [comment]
Please run `mvn install` first, altlr need to generate the code
