### ISSUE TITLE
只有单个字段的表会出问题，改不改都可以，我加个字段就好

### ISSUE THREAD

**Issue by cnlinjie** [apache/shardingsphere#8633]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

只有主键，且主键字段为自增的表会出问题。
提示：java.lang.StringIndexOutOfBoundsException: start -1, end 1, length 1
```
DROP TABLE IF EXISTS shortcode;
CREATE TABLE shortcode
(
    id            bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8mb4 COMMENT ='shortcode';
```
改不改都可以，我加个字段就可以了。

### Which version of ShardingSphere did you use?

4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

insert success 

### Actual behavior

error 
java.lang.StringIndexOutOfBoundsException: start -1, end 1, length 1

**Comment by terrymanu** [comment]
For English only, other languages will not accept.

**Comment by cnlinjie** [comment]
我知道，改不改无所谓，问题我提了就是。
