### ISSUE TITLE
Bug for USE JAVA API to to configure two tables

### ISSUE THREAD

**Issue by CrazyFz** [apache/shardingsphere#8638]
## Bug Report

When  my just have one table,  all database CRUD is right
but when i configure two tables(ssuser,gateway), it just can select ,but not insert 

then debug i find error, but do not how to fix it 

My DataSourceTestConfig code
`
public class BeetlSqlDataSourceTestConfig {

    @Autowired
    private Environment e;

    /**
     * postgrepsql db 配置
     * @return
     */
    @Bean(destroyMethod = "close",value = "sstest")
    DataSource getDataSource() {
        HikariDataSource hs = new HikariDataSource();
        hs.setUsername(e.getProperty("spring.datasource.hikari.sstest.username"));
        hs.setJdbcUrl(e.getProperty("spring.datasource.hikari.sstest.url"));
        hs.setPassword(e.getProperty("spring.datasource.hikari.sstest.password"));
        hs.setDriverClassName(e.getProperty("spring.datasource.hikari.sstest.driver-class-name"));
        

        Map<String, DataSource> dataSourceMap = new HashMap<>();
        dataSourceMap.put("ds0", hs);
        
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTables().add(getSsuserTableRuleConfiguration());
        shardingRuleConfig.getTables().add(getGatewayTableRuleConfiguration());

        Properties tableShardingAlgorithmrProps = new Properties();
        tableShardingAlgorithmrProps.setProperty(
        		"algorithm-expression", "ssuser_${user_id}");
        shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
        		new ShardingSphereAlgorithmConfiguration("INLINE",
        				tableShardingAlgorithmrProps));
        
		
		Properties tableShardingAlgorithmrProps2 = new Properties();
		tableShardingAlgorithmrProps2.setProperty(
				"algorithm-expression", "gateway_${user_id}");
		
		shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
				new ShardingSphereAlgorithmConfiguration("INLINE", 
						tableShardingAlgorithmrProps2));
        

        DataSource dataSource = null;
        try {
        	Properties dataSourceProperties =  new Properties();
        	dataSourceProperties.put("sql-show", true);
        	dataSource = ShardingSphereDataSourceFactory.createDataSource(dataSourceMap, Collections.singleton(shardingRuleConfig), dataSourceProperties);
		} catch (SQLException e1) {
			e1.printStackTrace();
		}  
        return dataSource;
    }
    
    private static ShardingTableRuleConfiguration getSsuserTableRuleConfiguration() {
        ShardingTableRuleConfiguration orderTableRuleConfig = 
        		new ShardingTableRuleConfiguration("ssuser", 
        				"ds0.ssuser_${0..1}");
        orderTableRuleConfig.setTableShardingStrategy(
        		new StandardShardingStrategyConfiguration(
        				"user_id", "tableShardingAlgorithm"));
        return orderTableRuleConfig;
    }
    
    private static ShardingTableRuleConfiguration getGatewayTableRuleConfiguration() {
        ShardingTableRuleConfiguration orderTableRuleConfig = 
        		new ShardingTableRuleConfiguration("gateway",
        				"ds0.gateway_${0..1}");
        orderTableRuleConfig.setTableShardingStrategy(
        		new StandardShardingStrategyConfiguration(
        				"user_id", "tableShardingAlgorithm"));
        return orderTableRuleConfig;
    }
`

![image](https://user-images.githubusercontent.com/22133156/102292669-9c905300-3f80-11eb-9e61-6e92ba64c540.png)
![image](https://user-images.githubusercontent.com/22133156/102292710-b16ce680-3f80-11eb-9db4-25a5df536ced.png)

 my sql
`
CREATE TABLE `gateway_1` (
  `user_id` int(11) NOT NULL,
  `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
)
CREATE TABLE `gateway_0` (
  `user_id` int(11) NOT NULL,
  `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
)
CREATE TABLE `ssuser_0` (
  `user_id` int(11) NOT NULL,
  `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
)
CREATE TABLE `ssuser_1` (
  `user_id` int(11) NOT NULL,
  `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
)
`

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? 
ShardingSphere-JDBC

**Comment by menghaoranss** [comment]
Please show the actual sql.

**Comment by huanghao495430759** [comment]
it is your configurations error. 

`Properties tableShardingAlgorithmrProps = new Properties();
    tableShardingAlgorithmrProps.setProperty(
    		"algorithm-expression", "ssuser_${user_id}");
    **shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
    		new ShardingSphereAlgorithmConfiguration("INLINE",
    				tableShardingAlgorithmrProps));**
    
	
	Properties tableShardingAlgorithmrProps2 = new Properties();
	tableShardingAlgorithmrProps2.setProperty(
			"algorithm-expression", "gateway_${user_id}");
	
	**shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
			new ShardingSphereAlgorithmConfiguration("INLINE", 
					tableShardingAlgorithmrProps2));`**

when you exetuted shardingRuleConfig.getShardingAlgorithms(), you put the same key 'tableShardingAlgorithm' into map, it was replace of new value  'new ShardingSphereAlgorithmConfiguration("INLINE", tableShardingAlgorithmrProps2)';

**Comment by huanghao495430759** [comment]
it is your configurations error.

`Properties tableShardingAlgorithmrProps = new Properties();
tableShardingAlgorithmrProps.setProperty(
"algorithm-expression", "ssuser_${user_id}");
shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
new ShardingSphereAlgorithmConfiguration("INLINE",
tableShardingAlgorithmrProps));

Properties tableShardingAlgorithmrProps2 = new Properties();
tableShardingAlgorithmrProps2.setProperty(
		"algorithm-expression", "gateway_${user_id}");

shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
		new ShardingSphereAlgorithmConfiguration("INLINE", 
				tableShardingAlgorithmrProps2));`
when you exetuted shardingRuleConfig.getShardingAlgorithms(), you put the same key 'tableShardingAlgorithm' into map, it was replace of new value 'new ShardingSphereAlgorithmConfiguration("INLINE", tableShardingAlgorithmrProps2)';

**Comment by CrazyFz** [comment]
> 请显示实际的sql。

![image](https://user-images.githubusercontent.com/22133156/102297735-bdf63c80-3f8a-11eb-8779-2c4c92aeabd3.png)

**Comment by CrazyFz** [comment]
> it is your configurations error.
> 
> `Properties tableShardingAlgorithmrProps = new Properties();
> tableShardingAlgorithmrProps.setProperty(
> "algorithm-expression", "ssuser_${user_id}");
> shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
> new ShardingSphereAlgorithmConfiguration("INLINE",
> tableShardingAlgorithmrProps));
> 
> Properties tableShardingAlgorithmrProps2 = new Properties();
> tableShardingAlgorithmrProps2.setProperty(
> "algorithm-expression", "gateway_${user_id}");
> 
> shardingRuleConfig.getShardingAlgorithms().put("tableShardingAlgorithm",
> new ShardingSphereAlgorithmConfiguration("INLINE",
> tableShardingAlgorithmrProps2));`
> when you exetuted shardingRuleConfig.getShardingAlgorithms(), you put the same key 'tableShardingAlgorithm' into map, it was replace of new value 'new ShardingSphereAlgorithmConfiguration("INLINE", tableShardingAlgorithmrProps2)';

Thanks , you are right

**Comment by CheerwayRen** [comment]
Hello, I also encounter this problem now. When I use one table to divide the table, it can work normally. When I add another table, the rule of dividing the table will become invalid. The version I use is  5.0.0-beta
Here is my java configuration

`@Bean
    public DynamicDataSourceProvider dynamicDataSourceProvider() {
        Map<String, DataSourceProperty> datasourceMap = properties.getDatasource();
        return new AbstractDataSourceProvider() {
            @SneakyThrows
            @Override
            public Map<String, DataSource> loadDataSources() {
                Map<String, DataSource> dataSourceMap = createDataSourceMap(datasourceMap);
                // 拿到两个数据源,对sharding进行改造
                DataSource sharding = dataSourceMap.get(SHARDING_DATA_SOURCE_NAME);
                Map<String, DataSource> targetDataSources = new HashMap<>(1);
                // 这里的key一定要保持和ShardingTableRuleConfiguration中actualDataNodes中前缀一致
                targetDataSources.put(SHARDING_DATA_SOURCE_NAME, sharding);
                // 考虑到备份表的机制 每次扫描备份表还有最近五年的分表
                Date now = new Date();
                String shardingStart = DateUtils.format(DateUtils.beginOfYear(DateUtils.offsetYear(now, 0 - SalesPropertiesConstant.SALE_MODE_DEFALUT_TABLE_BACKUP_YEAR)), SalesPropertiesConstant.SALE_YM_FORMAT);
                String shardingEnd = DateUtils.format(DateUtils.endOfYear(DateUtils.offsetYear(now, 1)), SalesPropertiesConstant.SALE_YM_FORMAT);
                System.setProperty("backupEnd", shardingStart);
                // 配置 day_report 表规则 实际表为过去五年加未来一年 + 备份表
                ShardingRuleConfiguration shardingRuleConfiguration = new ShardingRuleConfiguration();
                //day table sharding rule
                String dayReportActualDataNodes = "sharding.mng_sale_amount_day_$->{" + shardingStart.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + ".." + shardingEnd.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + "}0$->{1..9},sharding.mng_sale_amount_day_$->{" + shardingStart.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + ".." + shardingEnd.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + "}1$->{0..2},sharding.mng_sale_amount_day_backup";
                ShardingTableRuleConfiguration dayReportRuleConfiguration = new ShardingTableRuleConfiguration(SalesPropertiesConstant.SALE_DAY_REPORT_TABLE_NAME, dayReportActualDataNodes);
                StandardShardingStrategyConfiguration standardShardingStrategyConfiguration=  new StandardShardingStrategyConfiguration("SALE_YMD", "dayReportTableShardingAlgorithm");
                dayReportRuleConfiguration.setTableShardingStrategy(standardShardingStrategyConfiguration);
                shardingRuleConfiguration.getTables().add(dayReportRuleConfiguration);
                shardingRuleConfiguration.getShardingAlgorithms().put("dayReportTableShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("dayReportRule", new Properties()));

                //brand table sharding rule
                String brandDailyActualDataNodes = "sharding.mng_sale_brand_daily_data_$->{" + shardingStart.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + ".." + shardingEnd.substring(SpecialCharConstants.FINAL_INT_ZERO, SpecialCharConstants.FINAL_INT_FOUR) + "},sharding.mng_sale_brand_daily_data_backup";
                ShardingTableRuleConfiguration brandDailyRuleConfiguration = new ShardingTableRuleConfiguration(SalesPropertiesConstant.SALE_BRAND_DAILY_TABLE_NAME, brandDailyActualDataNodes);
                brandDailyRuleConfiguration.setTableShardingStrategy(new StandardShardingStrategyConfiguration("SALE_YMD", "brandDailyPreciseShardingAlgorithm"));
                shardingRuleConfiguration.getTables().add(brandDailyRuleConfiguration);
                shardingRuleConfiguration.getShardingAlgorithms().put("brandDailyPreciseShardingAlgorithm", new ShardingSphereAlgorithmConfiguration("brandDailyRule", new Properties()));
                shardingRuleConfiguration.setDefaultTableShardingStrategy(standardShardingStrategyConfiguration);
                Properties prop=  new Properties();
                prop.setProperty("sql-show","true");


                DataSource dataSource = ShardingSphereDataSourceFactory.createDataSource(targetDataSources, Collections.singleton(shardingRuleConfiguration), prop);
                dataSourceMap.put(SHARDING_DATA_SOURCE_NAME, dataSource);
                return dataSourceMap;
            }
        };
    }`

brand table sharding rule  is my new addition then is do，Then the rules didn't take effect. Please see what's wrong with my configuration

@huanghao495430759 @menghaoranss
