### ISSUE TITLE
Support allocating dataSource to autoTable generator

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8651]
### Intro

This is an enhancement feature to allocate some of the data sources configured to autoTable generator. In that way, the generator will create tables using allocated resources.

### Tasks

- [ ] Parse RDL in 96th Line of `DistSQLVisitor.class`
- [ ] Create table rule using allocated data sources or all data sources in 158th Line of `ShardingRule.class`

**Comment by jingshanglu** [comment]
#9112 #9119 has fixed it.
