### ISSUE TITLE
The Chinese characters is converted to ?? in db which default charset is utf8 (keywords: 中文乱码,gbk,utf8)

### ISSUE THREAD

**Issue by dafanzhi** [apache/shardingsphere#8656]
### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The Chinese chars should be stored normally into a utf8 database after doing an UPDATE sql.

### Actual behavior
The Chinese chars is converted to ??

### Reason analyze (If you can)
By default, the characterEncoding param in the url is set to GBK.
When i specified the  characterEncoding is utf8 in the url like follows, the issue is resovled:
```
url: jdbc:mysql://47.99.192.24:3306/enhancer_project_1?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
```

So, it is strongly recommended to set the value of utf8 for the characterEncoding by default and provide more explicit  configuration document for each props in config-xxx.yaml.

You know, I have done a lot of works to figure out the prop name should be characterEncoding rather than charset or encoding or some others :  )

Thanks in advance.

**Comment by menghaoranss** [comment]
The above url is the standard JDBC URL, not shardingsphere defined，you should make sure that the character encoding of the database and the client are consistent.

**Comment by dafanzhi** [comment]
> the database and the client are consistent

i'm sure that the database and the client are consistent.
plz see the Reason analyze above, thanks!

**Comment by duzhanfei** [comment]
what's you mysql  version?

**Comment by dafanzhi** [comment]
> what's you mysql version?

mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.5.62-0ubuntu0.14.04.1 |
+-------------------------+
1 row in set (0.01 sec)

**Comment by duzhanfei** [comment]
I think the database version is too low, you can try 5.7.25-log,it's ok.



At 2020-12-17 19:51:44, "dafanzhi" <notifications@github.com> wrote:

what's you mysql version?

mysql> select version();
+-------------------------+
| version() |
+-------------------------+
| 5.5.62-0ubuntu0.14.04.1 |
+-------------------------+
1 row in set (0.01 sec)
