### ISSUE TITLE
how to combine no sharding database with sharding database？

### ISSUE THREAD

**Issue by verify31** [apache/shardingsphere#8662]
### Which version of ShardingSphere did you use?
verison 4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC
### Expected behavior
support no sharding database combine with sharding databse
### Actual behavior
not work ,and got error ,
"Some routed data sources do not belong to configured data sources. routed data sources: `%s`, configured data sources: `%s`"
### Reason analyze (If you can)
i don't know

**Comment by tristaZero** [comment]
I suggest you try 5.0.0-alpha, which has better support for your scenario. For 4.1.0, could you try configuring `defaultDataSource` for non-sharding tables?

**Comment by verify31** [comment]
ok,thanks!

**Comment by verify31** [comment]
> I suggest you try 5.0.0-alpha, which has better support for your scenario. For 4.1.0, could you try configuring `defaultDataSource` for non-sharding tables?
ask more，what can I use in this version，can you show me the details。
and  4.1.0, could you try configuring `defaultDataSource` for non-sharding tables not work。
