### ISSUE TITLE
Tk.Mybatis “updateByPrimaryKeySelective ” Case " Can not update sharding key"

### ISSUE THREAD

**Issue by lazyboyl** [apache/shardingsphere#8677]
### Which version of ShardingSphere did you use?
ShardingSphere 5.x
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Use Tk,Mybatis.updateByPrimaryKeySelective methods 
### Actual behavior
case "Can not update sharding key, logic table: [t_user], column: [user_id]."
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/49420893/102482300-f33f7f00-409d-11eb-8899-84a5d06ade93.png)
The judgment is made here, but I suggest adding a judgment before the pre judgment. If the value of the updated partition key is the same as the value after the update, it will be released.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SQL: UPDATE t_user  SET user_id = user_id,user_name = ?,pwd = ? WHERE  user_id = ?
 sharding rule: user_id % 4

**Comment by lazyboyl** [comment]
@menghaoranss

**Comment by huanghao495430759** [comment]
SET user_id = user_id ？

**Comment by lazyboyl** [comment]
@huanghao495430759 Here are tk.mybatis Source code, you can use tk.mybatis The updatebyprimarykeyselective method, you will see the scenario I mentioned above。
`package tk.mybatis.mapper.common.base.update;

import org.apache.ibatis.annotations.UpdateProvider;
import tk.mybatis.mapper.annotation.RegisterMapper;
import tk.mybatis.mapper.provider.base.BaseUpdateProvider;

@RegisterMapper
public interface UpdateByPrimaryKeySelectiveMapper<T> {
    @UpdateProvider(
        type = BaseUpdateProvider.class,
        method = "dynamicSQL"
    )
    int updateByPrimaryKeySelective(T var1);
}`

**Comment by terrymanu** [comment]
Can not update sharding key for now. There are document describe the unsupported operation.
