### ISSUE TITLE
shardingsphere-jdbc-core-spring-boot-starter Database encryption starter fail

### ISSUE THREAD

**Issue by lazyboyl** [apache/shardingsphere#8678]
### Which version of ShardingSphere did you use?
       <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>
        </dependency>
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Start successfully
### Actual behavior
Failed to start
### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/49420893/102482816-c50e6f00-409e-11eb-8d72-8a45fedfcb24.png)
I have to add any configuration under props to start successfully. I hope you can fix this bug

**Comment by lazyboyl** [comment]
@menghaoranss

**Comment by menghaoranss** [comment]
@lazyboyl if you use springboot 2.x, you have to configure it as above, and it has been fixed in the master branch.
