### ISSUE TITLE
【shardingproxy4.1.1】Can i config both broadcastTables and defaultDataSourceName?

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8679]
I config  broadcastTables for data_dic,but when i insert data for this table  by proxy , the data was inserted only in ds_0,  i want insert data  into all datasource. 
Is there something wrong with my configuration?
 

config:

schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://13.1.16.54:3306/db_test_0?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://13.1.16.55:3306/db_test_1?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_2:
    url: jdbc:mysql://13.1.16.56:3306/db_test_2?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_3:
    url: jdbc:mysql://13.1.16.57:3306/db_test_3?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    PBCST_QRY_INFO:
      actualDataNodes: ds_${0..3}.PBCST_QRY_INFO_${0..15}
      tableStrategy:
        inline:
          shardingColumn: ECIF_CUST_NO
          algorithmExpression: PBCST_QRY_INFO_${Math.abs(ECIF_CUST_NO.hashCode() % 16)}
      databaseStrategy:
        inline:
          shardingColumn: ECIF_CUST_NO
          algorithmExpression: ds_${Math.abs(ECIF_CUST_NO.hashCode() % 4)}
      keyGenerator:
        type: SNOWFLAKE
        column: ECIF_CUST_NO
  
  broadcastTables:
    - STF_INFO,ORG_INFO,ORG_SUM,data_dic
  
  defaultDataSourceName: ds_0
  defaultTableStrategy:
    none:

**Comment by tristaZero** [comment]
Hi,

Could you set `sql.show` = `true` to get the detail info? Besides, I guess[Examples](https://github.com/apache/shardingsphere/tree/shardingsphere-ui-4.1.1/examples/sharding-proxy-example) will give you some points.

**Comment by terrymanu** [comment]
Closed because of no response
