### ISSUE TITLE
Shardingsphere is very slow to parse SQL for the first time after the service is started

### ISSUE THREAD

**Issue by wh1024k** [apache/shardingsphere#8684]
## Feature Request

![image](https://user-images.githubusercontent.com/36752386/102588293-322a0f00-4148-11eb-82f2-9643bf7e99c8.png)
Shardingsphere is very slow to parse SQL for the first time after the service is started or restarted. The version is 3.1.0

**Comment by yu199195** [comment]
can you up the shardingsphere version？  3.1.0  is too old

**Comment by terrymanu** [comment]
No response anymore, I just close the issue
