### ISSUE TITLE
shardingsphere-test not found in maven center repository

### ISSUE THREAD

**Issue by alvinqq** [apache/shardingsphere#8685]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

> `<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-test</artifactId>
            <version>5.0.0-alpha</version>
</dependency>`
in the maven center repository

### Actual behavior
not found in the maven center repository

### Reason analyze (If you can)
not deploy to maven center repository

### Example codes for reproduce this issue (such as a github link).
pom.xml include dependency：
>`<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
            <version>5.0.0-alpha</version>
</dependency>`
but, tip "Missing artifact org.apache.shardingsphere:shardingsphere-test:jar:5.0.0-alpha"

**Comment by alvinqq** [comment]
Temporary solution：
pom exclusion shardingsphere-test dependency

> `<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-governance-spring-boot-starter</artifactId>
            <version>${org.apache.shardingsphere.version}</version>
            <exclusions>
            	<exclusion>
            		<groupId>org.apache.shardingsphere</groupId>
            		<artifactId>shardingsphere-test</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>`

**Comment by yu199195** [comment]
shardingsphere-test not be released in maven center ,  Why do you need this project?

**Comment by terrymanu** [comment]
The test module is unnecessary to release
