### ISSUE TITLE
Why does the analysis take more time for the first time?

### ISSUE THREAD

**Issue by liuchaoheliang** [apache/shardingsphere#8686]
version 5.x
when I was testing and parsing a large sql,  use the same engine , new SQLStatementParserEngine("MySQL"), do 50 times parse. watch the cost time,
i found The first few times are much more time-consuming than the subsequent analysis.  why ? 
 my java code like this:
    @Test
    public void test() {
        String sql = "select ........";
        SQLStatementParserEngine engine = new SQLStatementParserEngine("MySQL");
        int i = 0;
        while (i < 50){
            Long now = System.currentTimeMillis();
            engine.parse(sql, false);
            Long cost = System.currentTimeMillis() - now;
            System.out.println("cost:" + cost);
            i++;
        }
    }

RESULT:
times: 0,cost(ms):1097
times: 1,cost(ms):11
times: 2,cost(ms):13
times: 3,cost(ms):8
times: 4,cost(ms):9
times: 5,cost(ms):4
times: 6,cost(ms):3
times: 7,cost(ms):3
times: 8,cost(ms):3
times: 9,cost(ms):4
times: 10,cost(ms):9
times: 11,cost(ms):4
times: 12,cost(ms):3
times: 13,cost(ms):2
times: 14,cost(ms):2
times: 15,cost(ms):5
times: 16,cost(ms):3
times: 17,cost(ms):3
times: 18,cost(ms):2
times: 19,cost(ms):1
times: 20,cost(ms):3
.......

**Comment by yu199195** [comment]
@jingshanglu  Can you answer that?

**Comment by jingshanglu** [comment]
@liuchaoheliang @yu199195 Parser engine has a cache, only the first time it is parsed, and from the second time it gets the result from the cache.

**Comment by liuchaoheliang** [comment]
i know the cache, but when i test it ,i use “engine.parse(sql, false);” ，this means parser engine des't use cache. right ?

**Comment by jingshanglu** [comment]
> i know the cache, but when i test it ,i use “engine.parse(sql, false);” ，this means parser engine des't use cache. right ?

Yes.

**Comment by Beyondeclipse** [comment]
@liuchaoheliang Parser engine need to create/load many objects in the first time, and it takes time.

**Comment by RaigorJiang** [comment]
Since this issue has been inactive for more than 30 days, we will close it. 
If you still have related questions, please submit a new issue, thank you.
