### ISSUE TITLE
use ShardingSphere-Proxy occur  "ERROR 2006 (HY000): MySQL server has gone away"

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere#8703]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Which version of ShardingSphere did you use?**
4.1.1

**Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?**
ShardingSphere-Proxy (i see proxy use mysql connector is 5.1.47)

**Expected behavior**
execute right 

**Actual behavior**
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    61

**Reason analyze (If you can)**
i cannot find any reason 

**Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.**
tools：mysql official client (version 5.7.30-log)
step：
  1.do not use proxy ：direct connect db is ok ,then execute sql is ok;
  2.use proxy  ： can connect a few seconds  , then execute sql will return  "ERROR 2006 (HY000): MySQL server has gone away" (sql eg：show tables)

but there is no error log ,i see log is normal execute , and i use Archery(another db client ) is ok ,so i cannot find the reason 

**Example codes for reproduce this issue (such as a github link).**

@tuohai666 @tristaZero

**Comment by yu199195** [comment]
Issue must be follow the template!

**Comment by xue2lang** [comment]
> Issue must be follow the template!

now use template

**Comment by yu199195** [comment]
@tristaZero  Can you take a look at it

**Comment by jingshanglu** [comment]
@xue2lang  It has been fixed on master branch by #8610, new version will be ok, you can use the master branch.

**Comment by xue2lang** [comment]
> @xue2lang It has been fixed on master branch by #8610, new version will be ok, you can use the master branch.

3Q，i will review the code and merge it to our branch of 4.1.1

**Comment by tristaZero** [comment]
> 3Q，i will review the code and merge it to our branch of 4.1.1

Hi, That's not an easy one. If it is needed, running master branch is another option for you. :)

**Comment by xue2lang** [comment]
> > 3Q，i will review the code and merge it to our branch of 4.1.1
> 
> Hi, That's not an easy one. If it is needed, running master branch is another option for you. :)

you are right ,i have saw the master code ,shardingshpere 5.x too much changed for 4.1.x ,i have given up my idea  💔

**Comment by z-n** [comment]
Isn't this a basic requirement？ show me what's wrong ok? the server is just gone ,no logs no errors
