### ISSUE TITLE
Proxy with governance can't work if there's no config file

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#8711]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Proxy with governance can run if there's only server.yaml file

### Actual behavior

Proxy with governance can't work if there's no config file

### Reason analyze (If you can)

**FrontDatabaseProtocolTypeFactory.getDatabaseType()** depends on the config file.

```
    private void initServerBootstrap(final ServerBootstrap bootstrap) {
        bootstrap.group(bossGroup, workerGroup)
                .channel(Epoll.isAvailable() ? EpollServerSocketChannel.class : NioServerSocketChannel.class)
                .option(ChannelOption.SO_BACKLOG, 128)
                .option(ChannelOption.WRITE_BUFFER_WATER_MARK, new WriteBufferWaterMark(8 * 1024 * 1024, 16 * 1024 * 1024))
                .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .handler(new LoggingHandler(LogLevel.INFO))
                .childHandler(new ServerHandlerInitializer(FrontDatabaseProtocolTypeFactory.getDatabaseType()));
    }
```

**Comment by tristaZero** [comment]
Hi @tuohai666 @terrymanu ,

I gave it a try, and indeed there was an exception like below,
```
Exception in thread "main" org.apache.shardingsphere.infra.config.exception.ShardingSphereConfigurationException: Can not find any configured data sources and database frontend protocol type.
	at org.apache.shardingsphere.proxy.frontend.protocol.FrontDatabaseProtocolTypeFactory.getDatabaseType(FrontDatabaseProtocolTypeFactory.java:47)
	at org.apache.shardingsphere.proxy.frontend.ShardingSphereProxy.initServerBootstrap(ShardingSphereProxy.java:84)
	at org.apache.shardingsphere.proxy.frontend.ShardingSphereProxy.start(ShardingSphereProxy.java:59)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:66)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)

```

I also tried to locate the cause and found @terrymanu did some changes recently. So could you look at `FrontDatabaseProtocolTypeFactory.java:47`?

**Comment by terrymanu** [comment]
This issue is not for released version, I just put the label as enhancement.
