### ISSUE TITLE
Oracle  paginations not work in version 4.1.1.

### ISSUE THREAD

**Issue by lvfuyou** [apache/shardingsphere#8727]
Oracle  paginations can not work in version 4.1.1.

The paginations sql like this:
  SELECT * FROM (SELECT row_.*, rownum rownum_ FROM (SELECT o.order_id as order_id FROM t_order_item where order_id = ?) row_ WHERE rownum <= ?) WHERE rownum > ?

**Comment by tkzhu818** [comment]
It might recognize the alias name as a table or view, try to upgrade to another version?

**Comment by terrymanu** [comment]
Duplicate with #8841
