### ISSUE TITLE
事务中读第一库非常慢，耗时近500ms左右

### ISSUE THREAD

**Issue by lhcxj576** [apache/shardingsphere#8728]
![1](https://user-images.githubusercontent.com/73157467/102963751-e353ef00-4524-11eb-9b9c-648e7cfbf444.png)
![2](https://user-images.githubusercontent.com/73157467/102963754-e64edf80-4524-11eb-9b93-dac2611116bd.png)
![image](https://user-images.githubusercontent.com/73157467/102963875-329a1f80-4525-11eb-97f6-16a1962806fa.png)

**Comment by yu199195** [comment]
please in english
