### ISSUE TITLE
about broadcast table  type

### ISSUE THREAD

**Issue by verify31** [apache/shardingsphere#8734]
## Question

what kinds of table can be config as broadcast table ? and how does  broadcast table work? 
for example,some opetate log table can be config as broadcast table?

**Comment by verify31** [comment]
version:4.1.0

**Comment by tristaZero** [comment]
[DOC](https://shardingsphere.apache.org/document/current/en/features/sharding/) will give you a hand.

**Comment by verify31** [comment]
> [DOC](https://shardingsphere.apache.org/document/current/en/features/sharding/) will give you a hand.

I have read this docoument,and not ge the right answer。

**Comment by tristaZero** [comment]
I guess the following description in [1] is what you are looking for.

```
Broadcast Table

It refers to tables that exist in all sharding database sources. Their structures and data are the same in each database. It can be applied to the small data volume scenario that needs to correlate with big data volume tables to query, dictionary table for example.
```

[1]https://shardingsphere.apache.org/document/current/en/features/sharding/concept/sql/

**Comment by verify31** [comment]
yes ,but I am still confused，eg，I hava one operate log table ,first I need to insert one row in this table,and then I need to insert the data in the second table,if I have db0,db1,db2,db3 4 databases,and in this scenario ,how does sharding handle it,if I hava one insert failed ,what about other theres?

**Comment by tristaZero** [comment]
Hi, ShardingSphere will send the `insert` SQL to all the actual tables of this broadcast table in different databases. In most cases, it will succeed. However, if you worry about its atomicity, please use the distributed transaction (Please consult the doc).

**Comment by verify31** [comment]
All right，tks
