### ISSUE TITLE
Is there an invalid names list?

### ISSUE THREAD

**Issue by Simbafa** [apache/shardingsphere#8739]
## Question

(For ShardingSphere-Proxy 4.1.1 version)
Some names are invalid for ShardingSphere.
For example, 
"names" is not a valid field name. 
"events" is not a valid table name.
If they are used, a parsing error will be thrown.

So could you please provide a list of these invalid names?
Thank you very much.

**Comment by yu199195** [comment]
You can refer to the database for official advice on this issue

**Comment by tristaZero** [comment]
Hi @Simbafa ,

Sorry to confuse you. Actually, 5.0.0-alpha has an accurate unreserved keyword list. Therefore my suggestion is to try this release.
Supposing 4.x release, you can find the answer in [Unreserved word list] (https://github.com/apache/shardingsphere/blob/96375f420074a8a4cba5307f1a308f3a87b3c7bf/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-mysql/src/main/antlr4/imports/mysql/BaseRule.g4#L77).

**Comment by Simbafa** [comment]
Thank you very much.
