### ISSUE TITLE
does shardingspere-ui 5 work with sharding-jdbc 4.X ?

### ISSUE THREAD

**Issue by Roronoa-Zoro** [apache/shardingsphere#8747]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Obviously no
