### ISSUE TITLE
shardingsphere-UI 4.1.0, after login, it pop up error, it does not work

### ISSUE THREAD

**Issue by Roronoa-Zoro** [apache/shardingsphere#8749]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Example codes for reproduce this issue (such as a github link).
click registry server, it pop up 2 error tips;
first:
Cannot create property=centerConfigs for JavaBean=org.apache.shardingsphere.ui.common.domain.CenterConfigs@2db70cea in 'reader', line 1, column 1: centerConfigs: ^ Cannot create property=additionalConfigCenterServerList for JavaBean=org.apache.shardingsphere.ui.common.domain.CenterConfig@1e53c87c in 'reader', line 2, column 3: - activated: true ^ Unable to find property 'additionalConfigCenterServerList' on class: org.apache.shardingsphere.ui.common.domain.CenterConfig in 'reader', line 3, column 37: additionalConfigCenterServerList: null ^ in 'reader', line 2, column 1: - activated: true ^ 

second:
Cannot create property=centerConfigs for JavaBean=org.apache.shardingsphere.ui.common.domain.CenterConfigs@6bf147b7 in 'reader', line 1, column 1: centerConfigs: ^ Cannot create property=additionalConfigCenterServerList for JavaBean=org.apache.shardingsphere.ui.common.domain.CenterConfig@27b3c4b6 in 'reader', line 2, column 3: - activated: true ^ Unable to find property 'additionalConfigCenterServerList' on class: org.apache.shardingsphere.ui.common.domain.CenterConfig in 'reader', line 3, column 37: additionalConfigCenterServerList: null ^ in 'reader', line 2, column 1: - activated: true ^

**Comment by menghaoranss** [comment]
Thanks for your feedback, please delete `shardingsphere-ui-configs.yaml` in your user home and refresh page again.

**Comment by daiyunqing** [comment]
I also have this problem, how to solve it

**Comment by xjrmail** [comment]
I also!!!
