### ISSUE TITLE
Oracle sql like【select * from table】  not work in version 4.1.1.

### ISSUE THREAD

**Issue by chaojunzi** [apache/shardingsphere#8753]
## sql
```
SELECT  * FROM t_invoice_create
``` 
##mysql
![image](https://user-images.githubusercontent.com/31429166/103080335-92b9c000-4610-11eb-872f-7901a597a78b.png)
![image](https://user-images.githubusercontent.com/31429166/103080352-99e0ce00-4610-11eb-8006-a79e1dfa24da.png)
##oracle
![image](https://user-images.githubusercontent.com/31429166/103080383-ae24cb00-4610-11eb-803d-0efa7ab779d6.png)
![image](https://user-images.githubusercontent.com/31429166/103080391-b250e880-4610-11eb-9248-7927ecb8035f.png)

## result
mysql is ok， oracle  is  error.
Please check this class 【org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement】
Thanks.
![image](https://user-images.githubusercontent.com/31429166/103080552-0956bd80-4611-11eb-8c89-a6b3663a415b.png)

**Comment by chaojunzi** [comment]
oracle  driver is ojdbc6-11.2.0.1.0.jar

**Comment by tristaZero** [comment]
Hi @chaojunzi ,
Could you try 5.0.0-alpha for a test?

**Comment by terrymanu** [comment]
No response
