### ISSUE TITLE
sql can't parse ":="

### ISSUE THREAD

**Issue by HoltYin** [apache/shardingsphere#8754]
**version:**
5.0.0-alpha
**project:**
shardingsphere-jdbc-core-spring-boot-starter
**sql:**
INSERT INTO test ( id, test, count )
VALUES
	( 13, 1, 2 ) 
	ON DUPLICATE KEY UPDATE 
	id =
IF
	( @update_condition := ( count < VALUES ( count ) ), VALUES ( id ), id ),
	test =
IF
	( @update_condition, VALUES ( test ), test ),
	count =
IF
	( @update_condition, VALUES ( count ), count )

**exception:**
line 1:106 no viable alternative at input 'IF(@update_condition:'
![image](https://user-images.githubusercontent.com/25241944/103080281-79b10f00-4610-11eb-86b5-736ea4d5f5ac.png)
**Reason analyze:**
maybe can't parse ":=",i try it without":" like  @update_condition = ( count < VALUES ( count ) ),it worked

**Comment by jingshanglu** [comment]
@HoltYin It is a bug, i'll check it.

**Comment by tristaZero** [comment]
@HoltYin Thanks for the feedback.
@jingshanglu Is they any progress?

**Comment by tuichenchuxin** [comment]
I found this sql already supported on branch master.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it. Thank you.
