### ISSUE TITLE
Improve the definition of projection.

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#8767]
## Bug Report

```
select 1+1;
```
parse the sql to get the statement, the projection in the statement is a string . 
### Which version of ShardingSphere did you use?
5.0.0-alpha

### Expected behavior
the projection in the statement is a `BinaryExpression` or others to get the detail of `1+1`.
### Actual behavior
the projection in the statement is a string "1+1" .

**Comment by tuichenchuxin** [comment]
I found we already supported parsing this to `BinaryExpression` on master branch.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it. Thank you.
