### ISSUE TITLE
Improve the definition about 'having' 

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#8768]
## Bug Report
```
SELECT region, SUM(population), SUM(area) FROM bbc GROUP BY region HAVING SUM(area)>1000000.

```
Parse the sql to get  statement, there is not info about `having`.

### Which version of ShardingSphere did you use?
5.0.0-alpha

### Expected behavior
we can get info about `having` in the statement.

### Actual behavior
there is no info about `having` in the statement.

**Comment by strongduanmu** [comment]
Duplicate with issue #10618.
