### ISSUE TITLE
How to config sharding sphere ?

### ISSUE THREAD

**Issue by Nononoa-Zoro** [apache/shardingsphere#8770]
**The scene is , I have tab_user,tab_role two tables , and ds0,ds1 two database.
The follow is DDL  of tab_user and tab_role:**

DROP TABLE IF EXISTS `tab_user`;
CREATE TABLE `tab_user`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
  `age` int(11) NULL DEFAULT NULL COMMENT ,
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT ,
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT ,
  `status` tinyint(1) NULL DEFAULT NULL COMMENT ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS `tab_role`;
CREATE TABLE `tab_role`  (
  `id` int(11) NOT NULL COMMENT ,
  `role_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `age` int(11) NULL DEFAULT NULL COMMENT ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

My sharding strategy of database is based of column age, and both tab_user and tab_role have the column age , but the two tables is accosiated by column `id`.
when i execute sql as follows:

Logic SQL: select *
    from tab_user u,tab_role r
    where u.id = r.id and u.id = ?

Actual SQL: ds0 ::: select *
    from tab_user u,tab_role r
    where u.id = r.id and u.id = ? ::: [2]

in application.properties if i didn't config like follows :
spring.shardingsphere.sharding.default-data-source-name=ds0
the application will not start successfully

My question is that is there any solution can help execute such accosiation sql in all actual db instead of default db ?

**Comment by yu199195** [comment]
what version used by?   can you show sharding config?

**Comment by terrymanu** [comment]
The title is too generic, can you change it for search friendly?

**Comment by terrymanu** [comment]
Closed because of no response.
