### ISSUE TITLE
关于用户手册

### ISSUE THREAD

**Issue by wplus3** [apache/shardingsphere#8795]
1、用户手册手几个 maven 依赖都是 alpha版本的，生产可以使用吗？
2、目前使用了 springboot的配置方式并没有跑通，各种报错，对应的 springboot和 Mybatis/MybatisPlus 版本是有要求吗
比如
spring.shardingsphere.rules.sharding.tables.t_order.database-strategy.standard.sharding-algorithm-name=database_inline
database_inline中的 _下划线在 springboot2.0x中不能使用，即使不使用 _ 也会有其它问题 
3、用户手册中的
spring.shardingsphere.datasource.ds1.url=jdbc:mysql://localhost:3306/ds1
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://localhost:3306/ds0
下面的配置是不是应该去掉 ds 后面的_
spring.shardingsphere.rules.sharding.sharding-algorithms.database_inline.props.algorithm-expression=ds_${user_id % 2}

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
