### ISSUE TITLE
【shardingproxy5.0.0.】What should be configured for 8C16G machines acceptor-Size and Executor-size in server.yaml

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8796]
Here is my configuration. Is this reasonable?

props:
  max-connections-size-per-query: 1
  acceptor-size: 32  # The default value is available processors count * 2.
  executor-size: 32  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy-transaction-type: LOCAL
  proxy-opentracing-enabled: false
  proxy-hint-enabled: false
  query-with-cipher-column: true
  sql-show: true
  check-table-metadata-enabled: false

**Comment by terrymanu** [comment]
It is better to get the best practice on configuration during performance test.
