### ISSUE TITLE
Support REMOVE REPLICA_QUERY RULE

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#8801]
CREATE REPLICA_QUERY RULE (
logic_ds_a (primary=primary_new_ds_a, repilca=repilca_ds_a_0) RANDOM(xxx=xxx),
logic_ds_b (primary=primary_new_ds_b, repilca=repilca_ds_b_0 ROUNDROBIN(xxx=xxx)
);

REMOVE REPLICA_QUERY RULE (logic_ds_a, logic_ds_b)

**Comment by jingshanglu** [comment]
@tuohai666 @terrymanu It is suggested to change to `DROP REPLICA_QUERY RULE (logic_ds_a, logic_ds_b)`.
