### ISSUE TITLE
Support REMOVE RESOURCE

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#8802]
ADD RESOURCE (
primary_ds=127.0.0.1:3306:demo_ds_0:root,
replica_ds_0=127.0.0.1:3306:demo_ds_0:root,
replica_ds_1=127.0.0.1:3306:demo_ds_0:root
)

REMOVE RESOURCE (primary_ds, replica_ds_0)

**Comment by jingshanglu** [comment]
It is suggested to change to `DROP RESOURCE (primary_ds, replica_ds_0)`, @terrymanu  @tuohai666
