### ISSUE TITLE
The "Read-write Split" is working，but  the "Data Masking" is not working.

### ISSUE THREAD

**Issue by zhf122728281** [apache/shardingsphere#8804]
compile 'org.apache.shardingsphere:sharding-jdbc-core:4.1.1'
compile 'org.apache.shardingsphere:sharding-jdbc-spring-namespace:4.1.1'

spring-datasource.xml 配置

    <bean id="kjySqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="masterSlaveKjyDataSource"></property>
        <property name="mapperLocations" value="classpath*:mybatis/kjy/**/*.xml"></property>
        <property name="configLocation" value="classpath:mybatis/sqlMapConfig.xml"/>
        <property name="failFast" value="true"/>
    </bean>

    
    <bean id=" kjyMapperScannerConfigurer" class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="cn.com.duiba.kjy.livecenter.dao.master"></property>
        <property name="sqlSessionFactoryBeanName" value="kjySqlSessionFactory"></property>
    </bean>

    
    <bean id="kjyTransactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="encryptKjyliveDataSource" />
        <qualifier value="kjy-live"/>
    </bean>

    <bean:properties id="props">
        <prop key="aes.key.value">${aes.key.value}</prop>
    </bean:properties>
    <encrypt:data-source id="encryptKjyliveDataSource" data-source-name="kjyDataSource" >
        <encrypt:encrypt-rule>
            <encrypt:tables>
                <encrypt:table name="tb_live_user">
                    <encrypt:column logic-column="phone" cipher-column="phone_num" encryptor-ref="custom_encryptor_aes" />
                    <encrypt:column logic-column="auth_phone" cipher-column="auth_phone_num" encryptor-ref="custom_encryptor_aes" />
                </encrypt:table>
            </encrypt:tables>
            <encrypt:encryptors>
                <encrypt:encryptor id="custom_encryptor_aes" type="CustomAes" props-ref="props"/>
            </encrypt:encryptors>
        </encrypt:encrypt-rule>
        <encrypt:props>
            <prop key="sql.show">false</prop>
            <prop key="query.with.cipher.column">true</prop>
            <prop key="max.connections.size.per.query">5</prop>
        </encrypt:props>
    </encrypt:data-source>

    <master-slave:load-balance-algorithm id="randomStrategy" type="RANDOM" />

    <master-slave:data-source id="masterSlaveKjyDataSource" master-data-source-name="encryptKjyliveDataSource" slave-data-source-names="readKeJiJiLiveDataSource" strategy-ref="randomStrategy">
        <master-slave:props>
            <prop key="sql.show">true</prop>
            <prop key="executor.size">10</prop>
            <prop key="check.table.metadata.enabled">false</prop>
            <prop key="foo">bar</prop>
        </master-slave:props>
    </master-slave:data-source>

    <bean id="liveReadOnlySqlSessionTemplate" class="org.mybatis.spring.SqlSessionTemplate">
        <constructor-arg name="sqlSessionFactory" ref="kjyReadOnlySqlSessionFactory" />
    </bean>

    
    <bean id="kjyReadOnlySqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="readKeJiJiLiveDataSource"></property>
        <property name="mapperLocations" value="classpath*:mybatis/readonly/**/*.xml"></property>
        <property name="configLocation" value="classpath:mybatis/sqlMapConfig.xml"/>
        <property name="failFast" value="true"/>
    </bean>

    
    <bean id=" kjyReadOnlyMapperScannerConfigurer" class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="cn.com.duiba.kjy.livecenter.dao.readonly"></property>
        <property name="sqlSessionFactoryBeanName" value="kjyReadOnlySqlSessionFactory"></property>
    </bean>
------------------------------

The "Read-write Split" is working，but  the "Data Masking" is not working.

**Comment by avalon5666** [comment]
Both read and write not working?

**Comment by tristaZero** [comment]
Hi @zhf122728281 Could you set `sql.show` = `true` and execute some SQLs to get the detailed log?

**Comment by terrymanu** [comment]
Closed because of no response.
