### ISSUE TITLE
Some question about newer to this community

### ISSUE THREAD

**Issue by lmhmhl** [apache/shardingsphere#8814]
I am very interested in this project and want to join in this community, but I don't know where and how to start it, I would be very glad if someone offer me some advices? thx.

**Comment by avalon5666** [comment]
Code pr, docs pr, resolve issue and so.
This is the [document contributor guide](https://shardingsphere.apache.org/community/en/contribute/document-contributor/), hope to help you.

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

Have my welcome. : )
You can go through the issue list and try some issues with the volunteer label. Plus, I am just going to post some tasks these days.  If you'd like, I will ping you here once posted.

**Comment by lmhmhl** [comment]
> Hi @lmhmhl ,
> 
> Have my welcome. : )
> You can go through the issue list and try some issues with the volunteer label. Plus, I am just going to post some tasks these days. If you'd like, I will ping you here once posted.

Appreciate it.

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

I have no idea about your interest or technique, but would like to try [#8883](https://github.com/apache/shardingsphere/issues/8883)?
For the newbie, [Instruction](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will tell you how to raise a good PR.

**Comment by lmhmhl** [comment]
> Hi @lmhmhl ,
> 
> I have no idea about your interest or technique, but would like to try [#8883](https://github.com/apache/shardingsphere/issues/8883)?
> For the new comer, [Instruction](https://shardingsphere.apache.org/community/cn/contribute/contributor/) will tell you how to raise a good PR. If you like, please comment on that issue, and I will assign to you there.

Thank u, I wanna have a try, and try my best finishing it ASAP!

**Comment by tristaZero** [comment]
@lmhmhl Then #8883 is assigned to u.
