### ISSUE TITLE
ShardingSphere JDBC整合Spring Boot的BUG

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#8816]
我在整合Spring Boot和ShardingSphere JDBC 5.0.0alpha使用读写分离算法ROUND_ROBIN的时候，在加载配置文件的时候会出现一些问题。
首先明确官网中对于ROUND_ROBIN的参数并没有要求：
![image](https://user-images.githubusercontent.com/76552510/103326006-590e0c80-4a89-11eb-9b45-16fd6816ac63.png)
其次进行问题描述：
我的配置文件：
`spring.shardingsphere.datasource.names=master,slave

spring.shardingsphere.datasource.master.jdbc-url=jdbc:mysql://localhost:3306/master?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.master.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.master.username=root
spring.shardingsphere.datasource.master.password=123456
spring.shardingsphere.datasource.slave.jdbc-url=jdbc:mysql://localhost:3306/slave?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.slave.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.slave.username=root
spring.shardingsphere.datasource.slave.password=123456
spring.shardingsphere.props.sql-show=true
spring.shardingsphere.rules.replica-query.load-balancers.round-robin.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.data-sources.masterandslave.primary-data-source-name=tb_user
spring.shardingsphere.rules.replica-query.data-sources.masterandslave.load-balancer-name=round-robin
`
这样运行会报错：

![image](https://user-images.githubusercontent.com/76552510/103326037-835fca00-4a89-11eb-81fc-ea99eadf5144.png)
尝试加上.props：
`spring.shardingsphere.rules.replica-query.load-balancers.props=a:b`
仍会出现问题：
![image](https://user-images.githubusercontent.com/76552510/103326094-ca4dbf80-4a89-11eb-8a10-4f43ee5437b4.png)
debug过程：
![image](https://user-images.githubusercontent.com/76552510/103326040-8e1a5f00-4a89-11eb-82c0-dd9de8b8665c.png)
![image](https://user-images.githubusercontent.com/76552510/103326042-91ade600-4a89-11eb-92da-98e6b407f3fe.png)
个人认为是因为
spring.shardingsphere.props与spring.shardingsphere.rules.replica-query.load-balancers.round-robin.props读写出现混乱导致的。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
