### ISSUE TITLE
Some problems occured when using boot combined with ShardingSphere JDBC 5.0.0alpha

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#8818]
When I was integrating Springboot and ShardingSphere JDBC 5.0.0 alpha to use the read-write separation by ROUND_ROBIN, there will be some problems when loading the configuration file. 
First, there is no requirement for the ROUND_ROBIN parameter in the official website：
![image](https://user-images.githubusercontent.com/76552510/103326846-282fd680-4a8d-11eb-96f8-998454079186.png)

Then, describe my problem：
My configuration file：
`spring.shardingsphere.datasource.names=master,slave

spring.shardingsphere.datasource.master.jdbc-url=jdbc:mysql://localhost:3306/master?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.master.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.master.username=root
spring.shardingsphere.datasource.master.password=123456
spring.shardingsphere.datasource.slave.jdbc-url=jdbc:mysql://localhost:3306/slave?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.slave.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.slave.username=root
spring.shardingsphere.datasource.slave.password=123456
spring.shardingsphere.props.sql-show=true
spring.shardingsphere.rules.replica-query.load-balancers.round-robin.type=ROUND_ROBIN
spring.shardingsphere.rules.replica-query.data-sources.masterandslave.primary-data-source-name=tb_user
spring.shardingsphere.rules.replica-query.data-sources.masterandslave.load-balancer-name=round-robin
`
Some error occured：

![image](https://user-images.githubusercontent.com/76552510/103326037-835fca00-4a89-11eb-81fc-ea99eadf5144.png)
Try to add some props：
`spring.shardingsphere.rules.replica-query.load-balancers.props=a:b`
Problems still occured：
![image](https://user-images.githubusercontent.com/76552510/103326094-ca4dbf80-4a89-11eb-8a10-4f43ee5437b4.png)
debuging：
![image](https://user-images.githubusercontent.com/76552510/103326040-8e1a5f00-4a89-11eb-82c0-dd9de8b8665c.png)
![image](https://user-images.githubusercontent.com/76552510/103326042-91ade600-4a89-11eb-92da-98e6b407f3fe.png)
Personally think it is caused by
spring.shardingsphere.props&spring.shardingsphere.rules.replica-query.load-balancers.round-robin.props's confusion in reading and writing.

**Comment by yu199195** [comment]
you can see #8300

**Comment by JiekerTime** [comment]
> you can see #8300
Doesn't seem to be the same problem.I am not using the sharding. It's just a read-write separation algorithm.
Here is my project：
https://github.com/JiekerTime/ShardingSphere-StudyNodes/tree/master/shardingjdbc_p1
