### ISSUE TITLE
SQL parsing error

### ISSUE THREAD

**Issue by lostnana** [apache/shardingsphere#8819]
## Bug Report
When I execute this SQL
`
select
    <include refid="Base_Column_List"/>
      from t_refund_apply_log
      where id in (
      select MAX(id) from t_refund_apply_log where
      refund_item_id IN (
         <foreach collection="refundItemIds" separator="," item="refundItemId">#{refundItemId}</foreach>
      )
      group by refund_id,`operate_type`,refund_item_id
    )
    order by `id` desc
`
throw Exception
`Caused by: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'MAX', literals is 'MAX'.
`

**Comment by jingshanglu** [comment]
@lostnana  Which version you use? can you show the sql that can run in mysql or others?

**Comment by lostnana** [comment]
then version is 3.0.0 ,it can be executed normally in mysql

**Comment by jingshanglu** [comment]
@lostnana Can you use `5.0.0-alpha`?   it is ok.

**Comment by lostnana** [comment]
Ok, I'll try it，thanks!

**Comment by terrymanu** [comment]
Closed because of no response.
