### ISSUE TITLE
does shardingsphere support several sharding strategies for one table ?

### ISSUE THREAD

**Issue by NOLouser** [apache/shardingsphere#8820]
for example:
&ensp;&ensp; I have several tables
&emsp; &emsp;logic table:&nbsp;t_order(order_id, order_msg, create_time)
&emsp; &emsp;sharding tables:&nbsp;t_order_202001、t_order_202002、t_order_202003 ....
&ensp;&ensp; I want to set PreciseShardingAlgorithm for sharding key: order_id (sql like: query by order_id), and in some cases, I want to force sql to the table that I specify( by using HintShardingAlgorithm, sql like: specify query table t_order_202001 ).

<br/>I tried to set my PreciseShardingAlgorithm and HintShardingAlgorithm to the shrading rule config, however, only one sharding algorithm would work. Does this mean not support several sharding strategies for the same table?<br/>

**Comment by tristaZero** [comment]
Hi, @NOLouser ,

You can not configure two sharding algorithms for one logic table in a direct way. However, creating two different logic tables sharding the same actual tables (i.e., two different sharding algorithm for the same actual data nodes) is possible to meet your needs. Be careful with this usage, It is not a regular one.

**Comment by NOLouser** [comment]
I get it! 

Thanks a lot!
