### ISSUE TITLE
Under the scenario of sub-table, does sharding-proxy support flyway for management?

### ISSUE THREAD

**Issue by li-sen** [apache/shardingsphere#8825]
As mentioned in the title,

Under the scenario of sub-table, does sharding-proxy support flyway for management?

**Comment by avalon5666** [comment]
You can test it, and submit issue when there are incompatible sql.

**Comment by tristaZero** [comment]
Hi @li-sen 

What's the meaning of `flyway`?

**Comment by terrymanu** [comment]
Closed because of no response.
