### ISSUE TITLE
ShardingSphereConfigurationException: Invalid datetime-lower, datetime pattern should be `yyyy-MM-dd`, value is `2018-06-01`

### ISSUE THREAD

**Issue by lwh-0739** [apache/shardingsphere#8827]
version：
    spring boot 2.x
    shardingsphere-jdbc-core-spring-boot-starter   5.0.0-alpha

IntervalShardingAlgorithm configuration：

spring.shardingsphere.rules.sharding.sharding-algorithms.test.type=INTERVAL
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-pattern=yyyy-MM-dd
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.sharding-suffix-pattern=yyyyMM
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-lower=2018-06-01
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-upper=2021-12-31
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-interval-amount=6
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-interval-unit=MONTHS

Error in running times：
![image](https://user-images.githubusercontent.com/53554356/103338186-8c1bc480-4ab8-11eb-885e-be180bab468f.png)

Specific location of the error：
![image](https://user-images.githubusercontent.com/53554356/103339196-b58a1f80-4abb-11eb-9902-5cfe84e8e11f.png)

![image](https://user-images.githubusercontent.com/53554356/103339350-216c8800-4abc-11eb-91bd-da1ed6d85da9.png)

**Comment by strongduanmu** [comment]
@lwh-0739 Hello, thank you very much for your feedback. 😊 Just like the code you showed, the interval sharding algorithm is implemented based on `LocalDateTime`, which requires us to define parameters in the datatime format. You can adjust the configuration to avoid this error:

```properties
spring.shardingsphere.rules.sharding.sharding-algorithms.test.type=INTERVAL
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-pattern=yyyy-MM-dd HH:mm:ss
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.sharding-suffix-pattern=yyyyMM
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-lower=2018-06-01 00:00:00
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-upper=2021-12-31 00:00:00
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-interval-amount=6
spring.shardingsphere.rules.sharding.sharding-algorithms.test.props.datetime-interval-unit=MONTHS
```
In addition, you can also implement custom algorithms through SPI to meet your needs.

**Comment by lwh-0739** [comment]
thank you!
