### ISSUE TITLE
mvn install error: 'parent.relativePath' of POM shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT

### ISSUE THREAD

**Issue by jiangtao69039** [apache/shardingsphere#8832]
when i execute "mvn install" bug get follow error message:
 
 'parent.relativePath' of POM org.apache.shardingsphere:shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT...

so i change shardingsphere-ha-mgr/pom.xml(line 25)  from " <artifactId>shardingsphere-ha</artifactId> "  to " <artifactId>shardingsphere-ha-provider</artifactId> "  then mvn install sucess

is this a bug?

**Comment by tristaZero** [comment]
Hi @jiangtao69039 ,

I an able to succeed in installing, could you clean and reinstall it?

**Comment by yangzhongj** [comment]
yes , it always:    FATAL] Non-resolvable parent POM for org.apache.shardingsphere:shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-ha:pom:5.0.0-RC1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 23, column 13

**Comment by tristaZero** [comment]
@yangzhongj ,
Thanks for your feedback, @tuohai666 is working on this one. Please wait for his PR fixing it.

**Comment by tuohai666** [comment]
Fixed via https://github.com/apache/shardingsphere/pull/8906
