### ISSUE TITLE
Can not update sharding key, error using JPA 

### ISSUE THREAD

**Issue by huoleihu** [apache/shardingsphere#8845]
### Which version of ShardingSphere did you use?

Sharding-JDBC 4.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere JDBC

### Expected behavior

Normal update

### Actual behavior

Can not update sharding key error in update

### Reason analyze (If you can)

JPA SQL :update tb_hd_task set .... where id = ?
I guess the correct SQL should be-->update tb_hd_task set .... where id = ? and share_key = ?

Does shardingjdbc support adding table keys automatically?

**Comment by huoleihu** [comment]
<img width="2128" alt="WX20201231-154833@2x" src="https://user-images.githubusercontent.com/47547437/103401063-770b6800-4b82-11eb-82a0-8495182f37bb.png">

**Comment by kimmking** [comment]
Users should add sharding-key to sql, shardingsphere can't know the value.
