### ISSUE TITLE
Some newer question

### ISSUE THREAD

**Issue by lmhmhl** [apache/shardingsphere#8861]
I am a newer to this community,  I want to read the source code to know more  details, which part should I read first?

**Comment by terrymanu** [comment]
Sorry, I can't answer the question.
ShardingSphere has dozens of modules, please choose your interested and familiar modules to read them.
I don't know what is your familiar technical.

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

Welcome here.
Like @terrymanu said, ShardingSphere is a large-scale project. Thus it is not a good start to read source code at the beginning. Plus, I am afraid you will lose interest in this project later, so my suggestion is to learn about this project by fixing some issues little by little. That way, you will have the interaction with the community and deep learning of it gradually.
