### ISSUE TITLE
Support different Database types for Query optimization 

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8880]
Hi,

This is an enhancement function for query optimization. It is not a difficult one, welcome your contribution.

### Target
Add corresponding SqlConformanceEnum and Lex to the properties of Calcite by `ShardingSphereMetaData` in `CalciteContextFactory`.

### Items
- Get `DatabaseType` from `ShardingSphereResource` of `ShardingSphereMetaData`
- Get the corresponding type value from `SqlConformanceEnum` (If there is no correct value, please use `default` type.)
- Get the corresponding type value from `Lex`  (If there is no correct value, please use `default` type.)
- Put the two values above into `Properties` in `createProperties()` of `CalciteContextFactory`
- Add a unit test for `CalciteContextFactory` (Please consider mocking a ShardingSphereMetaData, which will make it easy.)

**Comment by JiekerTime** [comment]
I will implement it as soon as possible~

**Comment by wgy8283335** [comment]
Does this issue still need contributors? @tristaZero

**Comment by tristaZero** [comment]
Hi @wgy8283335 

Sorry for no updating here. This one was  fixed by #8918.
