### ISSUE TITLE
JSON function in SQL

### ISSUE THREAD

**Issue by ittoyxk** [apache/shardingsphere#8908]
When there is a JSON function in SQL, the logical table name cannot be resolved, resulting in the failure to hit the real table name. Please see how to solve this problem?

**Comment by tristaZero** [comment]
Which version is running in your environment?

**Comment by ittoyxk** [comment]
Version 4.0.0-rc1 used;
When parsing JSON with "->" in SQL, The table name cannot be resolved,
But it's OK to change to the "JSON_EXTRACT" function;

**Comment by tristaZero** [comment]
Hi Could you try an upgraded version? I suggest 5.0.0-alpha if you like.

**Comment by terrymanu** [comment]
Closed because of no response.
