### ISSUE TITLE
ProjectionEngine subquery support

### ISSUE THREAD

**Issue by Allkoman** [apache/shardingsphere#8914]
### Is your feature request related to a problem?
no

### Describe the feature you would like.
ProjectionEngine.class 
//TODO subquery
Can you support subquery?

**Comment by Allkoman** [comment]
sharding version 4.1.0 & 4.1.1

**Comment by tristaZero** [comment]
Please try 5.0.0-alpha, since we have better support for it. Welcome your feedback later.
