### ISSUE TITLE
mvn complie err

### ISSUE THREAD

**Issue by yangzhongj** [apache/shardingsphere#8933]
## Question

git clone shardingsphere, execute  ./mvnw clean install -Prelease ， error 

detail info:
node@nodedeMacBook-Pro shardingsphere % ./mvnw clean install -Prelease
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.shardingsphere:shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-ha:pom:5.0.0-RC1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 23, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.apache.shardingsphere:shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT (/Users/node/project/shardingsphere/shardingsphere-features/shardingsphere-ha/shardingsphere-ha-provider/shardingsphere-ha-mgr/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.apache.shardingsphere:shardingsphere-ha-mgr:5.0.0-RC1-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-ha:pom:5.0.0-RC1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 23, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by SteNicholas** [comment]
@yangzhongj You could run `mvn clean install -DskipTests -Dfast`.
