### ISSUE TITLE
shardingsphere-jdbc-governance incompatible with druid-spring-boot-starter

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#8940]
## Feature Request

The `DataSourceConfiguration` requires public no-args constructor on `DataSource`. But the `druid-spring-boot-starter` create a class named `DruidDataSourceWrapper` extends DruidDataSource, but without public no-args constructor.

https://github.com/alibaba/druid/blob/5761dccf904c1fe8120767f86d67ccf0be171726/druid-spring-boot-starter/src/main/java/com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceWrapper.java#L32

If we used the druid starter, an exception 
```java.lang.NoSuchMethodException: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper.<init>()```
will occurred when invoking `org.apache.shardingsphere.infra.config.datasource.DataSourceConfiguration#createDataSource`.

**Comment by yu199195** [comment]
hi, you will see this : https://github.com/apache/shardingsphere/issues/1900

**Comment by TeslaCN** [comment]
Hi @yu199195 
I think this issue is different with #1900. This issue is failed to instantiate a DataSource without no-args constructor.

**Comment by linghengqian** [comment]
Caused by the situation mentioned in https://github.com/alibaba/druid/issues/4673?

**Comment by TeslaCN** [comment]
Fixed since Druid 1.2.8.
