### ISSUE TITLE
Sharding JDBC don't work with Postgres jsonb type

### ISSUE THREAD

**Issue by LeasyZhang** [apache/shardingsphere#8946]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Data should be inserted into table successfully.

### Actual behavior
Insert failed and throw the following error message: 
"column "content" is of type jsonb but expression is of type character varying"

### Reason analyze (If you can)
ShardingSphere remove the jsonb function before it's processed by PgPreparedStatement. But it works on version 3.0.0.M1.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

- Prepare raw sql "insert into news(title, author, content) values (?, ?, ?::jsonb)"
- Do insert with PreparedStatement.executeUpdate method

### Example codes for reproduce this issue (such as a github link).
`Session session = entityManager.unwrap(Session.class);

        return session.doReturningWork(connection -> {
            String sql = "insert into news(title, author, content) values (?, ?, ?::jsonb)";
            PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            int paramIndex = 1;
            ps.setString(paramIndex++, news.getTitle());
            ps.setString(paramIndex++, news.getAuthor());
            ps.setString(paramIndex, news.getContent());
            ps.executeUpdate();
            ResultSet result = ps.getGeneratedKeys();
            while (result.next()) {
                news.setId(result.getLong(1));
            }
            ps.close();
            return news;
        });`

**Comment by LeasyZhang** [comment]
It works in ShardingSphere-3.0.0.M1 but failed in later versions.

**Comment by susongyan** [comment]
is pg's    jsonb and  ::     supported in  5.x version  now?

**Comment by zxz-github** [comment]
`cast(? as json)` is supported

**Comment by jpaterso** [comment]
Hi, this issue still appears to exist in ShardingSphere 5.3.1 where inserting into a table with a JSONB column generates an incorrect number of parameters to the insert statement. Is there any workaround for this? Thanks

**Comment by susongyan** [comment]
need support  ::   to cast jsonb?

i'd like to have a try

**Comment by terrymanu** [comment]
Close because of staled.
