### ISSUE TITLE
Throw NPE when table name include '-'

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8947]
### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute SQL `SELECT * FROM t-order;`

### Actual behavior

Report error message table not exist, or syntax error,  or parse exception at last.

**Comment by jingshanglu** [comment]
@terrymanu The table name is wrong.
![image](https://user-images.githubusercontent.com/16559542/103999852-66896c00-51d8-11eb-8e9e-ba9f0f772cb6.png)
