### ISSUE TITLE
Failed to generate using spring data jpa id

### ISSUE THREAD

**Issue by wxq851685279** [apache/shardingsphere#8964]
version: 
springboot 2.3.7.RELEASE
sharding-jdbc-spring-boot-starter:4.1.1
exception:
`org.springframework.orm.jpa.JpaSystemException: ids for this class must be manually assigned before calling save(): com.example.demo.entity.Course; nested exception is org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): com.example.demo.entity.Course`

![image](https://user-images.githubusercontent.com/29041799/104111957-76619700-5323-11eb-8121-86c4676ddd31.png)

**Comment by wxq851685279** [comment]
@rfscholte @WillemJiang @ke4qqq @gmcdonald

**Comment by terrymanu** [comment]
The exception is throw from hibernate and your own class, can you make clear the problem first?

**Comment by wxq851685279** [comment]
Need to manually set the primary key

**Comment by terrymanu** [comment]
Do you resolve the issue?

**Comment by wxq851685279** [comment]
> Do you resolve the issue?

Manually set the primary key effective

**Comment by hesixian123** [comment]
What is the use of this ID sequence generation algorithm after configuration? Or do you need to generate it manually
