### ISSUE TITLE
Create unit test for `CalciteLogicSchemaFactory`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#8965]
Hi, guys,

Thanks for your attention, this issue to create unit test for `CalciteLogicSchemaFactory`.

### Steps
- Create a `CalciteLogicSchemaFactoryTest` class
- Create a `ShardingSphereDataSource` to get `Map<String, ShardingSphereMetaData>` from `MetaDataContexts`(`AbstractShardingSphereDataSourceForShardingTest` will give you some points, I guess)
- Create `CalciteContextFactory` by Map<String, ShardingSphereMetaData> acquired by the last step to get `CalciteContext`
- Assert `CalciteContext`

### Tips
- Since this issue is associated with #8883, where I guess you can get some useful hints.

**Comment by lmhmhl** [comment]
I wanna have a try. Thx.

**Comment by tristaZero** [comment]
Hi  @lmhmhl ,

Your name came to my mind when I created this issue  though, glad to see you stand out.
