### ISSUE TITLE
SeataAT transaction in ShardingSphere-Proxy block abnormally

### ISSUE THREAD

**Issue by ben905713861** [apache/shardingsphere#8978]
### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When I use Seata-AT transaction in ShardingSphere-Proxy,I have start transaction and send a `select for update` SQL,the mysql-client is blocking forever.
（使用Seata-AT事务，执行select for update语句，客户端会永久阻塞）

```sql
BEGIN;
SELECT * FROM user WHERE id=1 FOR UPDATE;
(blocking......)
```
After sending this SQL,ShardingSphere-Proxy is blocking.
In this test, I use wireshark to analysis, I can see the SQL send to ShardingSphere-Proxy and MySQL-Server successfuly, and  MySQL-Server echo the result successfuly.
（抓包分析，mysql服务收到了分片语句并成功返回）
![image](https://user-images.githubusercontent.com/37857367/104157987-5a471e00-5427-11eb-90b3-78171f31f4b5.png)

### Another behavior
Using `insert`, `update` or `delete` SQL is successful, only the `select for update` is failed (Blocking forever)
（使用增删改是正常的，只有select for update语句是永久阻塞）

**Comment by yu199195** [comment]
1. you add  shardingsphere-transaction-base-seata-at.jar in proxy?
2. can you show server.yml ?
3. can you show seata.conf  and register.conf?

**Comment by ben905713861** [comment]
@yu199195 1.yes, I add shardingsphere-transaction-base-seata-at.jar in proxy,the version is 4.1.1

2.the server.yml is:
```
authentication:
  users:
    root:
      password: 12345678
props:
  proxy.transaction.type: BASE
  sql.show: true
```

3.1 register.conf is:
```
registry {
  type = "nacos"
  nacos {
    serverAddr = "127.0.0.1:8848"
    namespace = ""
    cluster = "default"
    group = "SEATA_GROUP"
    application = "seata-server"
  }
}
config {
  type = "nacos"
  nacos {
    serverAddr = "127.0.0.1:8848"
    namespace = ""
    cluster = "default"
    group = "SEATA_GROUP"
  }
}
```

3.2 seata.conf is:
```
sharding.transaction.seata.at.enable = true
client {
    application.id = test
    transaction.service.group = my_test_tx_group
}
```

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.
