### ISSUE TITLE
Only Sharing-JDBC can use seata?

### ISSUE THREAD

**Issue by guoxianwei-ying** [apache/shardingsphere#8981]
According to the user manual on the official website, using the Sharding-proxy mode does not currently support seata distributed transactions. Only Sharing-JDBC can use seata?

**Comment by strongduanmu** [comment]
@guoxianwei-ying You can refer to issue #4882, which provides some ideas for `sharding-proxy` to integrate `seata`.

**Comment by guoxianwei-ying** [comment]
> @ guoxianwei-ying您可以参考问题[＃4882](https://github.com/apache/shardingsphere/issues/4882)，其中提供了一些`sharding-proxy`集成的想法`seata`。

Thank you.I will try
