### ISSUE TITLE
jpa+proxy Data not found        HELP!!!!!!

### ISSUE THREAD

**Issue by Han-Tang** [apache/shardingsphere#8995]
i have a project.used sharding proxy.
![图片](https://user-images.githubusercontent.com/33918398/104290344-33571d80-54f5-11eb-93aa-55b7268d4942.png)
![图片](https://user-images.githubusercontent.com/33918398/104290365-3a7e2b80-54f5-11eb-99bd-1daebab03116.png)
hibernate  sql:
![图片](https://user-images.githubusercontent.com/33918398/104290585-7dd89a00-54f5-11eb-93aa-d4ae9aee5f9f.png)
proxy sql:
![图片](https://user-images.githubusercontent.com/33918398/104290929-e6c01200-54f5-11eb-8798-3281976dc145.png)

**Comment by tristaZero** [comment]
Hi, 

What you mentioned is that to-execute SQLs are correct, but no result return, right?

**Comment by Han-Tang** [comment]
yes.the sql is correct

**Comment by Han-Tang** [comment]
yes, the sql is correct. in my project,hibernate count() can get return ,but select  sql no result return

**Comment by tristaZero** [comment]
`SELECT count(*)` returns `0` ? How about `SELECT * FROM`? Is there any rows coming back?

**Comment by Han-Tang** [comment]
thanks！i know reason now. Error in field type.entity field type is "LocalDate" in my ,but mysql field  type is "date'.
then i change "date" to "datetime" ,is ok.
