### ISSUE TITLE
PSQLException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_NUMERIC' in column type when process binary protocol value

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#9000]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Support POSTGRESQL_TYPE_NUMERIC column type.

### Actual behavior

Cause: org.postgresql.util.PSQLException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_NUMERIC' in column type when process binary protocol value
; uncategorized SQLException; SQL state [null]; error code [0]; Cannot find PostgreSQL type 'POSTGRESQL_TYPE_NUMERIC' in column type when process binary protocol value; nested exception is org.postgresql.util.PSQLException: Cannot find PostgreSQL type 'POSTGRESQL_TYPE_NUMERIC' in column type when process binary protocol value

### Reason analyze (If you can)

There's no POSTGRESQL_TYPE_NUMERIC type in PostgreSQLBinaryProtocolValueFactory

Need to add the missing types and their read()/write() method according to the PostgreSQL wire protocol.

**Comment by sandynz** [comment]
Hi @tuohai666 , I'll try to fix it
