### ISSUE TITLE
5.0.0-alpha did not delete the datasource.common prop

### ISSUE THREAD

**Issue by aBoyNicholas** [apache/shardingsphere#9003]
## Bug Report

**For English only**, other languages will not accept.

I can't understand that the documentation and everything in the instructions don't mention this, the 5.0.0-alpha in the Maven repository doesn't remove datasource.common props, which caused me to have to carry datasource.common in application.yml.

However, when I use the Hikari pool, this still does not allow me to omit the jdbc url attribute in the common as in the original version, which causes Hikari to not find the url

**Comment by aBoyNicholas** [comment]
I think the problem has been found, the **url** must be modified to **jdbc-url**, is it considered to modify this one?

**Comment by tristaZero** [comment]
> I think the problem has been found, the url must be modified to jdbc-url, is it considered to modify this one?

Hi, the document gives users wrong configuration?

**Comment by JiekerTime** [comment]
@aBoyNicholas In 5.0.0 apha, if your springboot version is 2.x, you really need to configure datasourse.common. However, under 2.x, you do not need to configure at all.
The datasourse.common will be removed in the future.

**Comment by yu199195** [comment]
>In 5.0.0 apha, if your springboot version is 2.x, you really need to configure datasourse.common. However, under 2.x, you do not need to configure at all.
The datasourse.common will be removed in the future.

this is right..

**Comment by tristaZero** [comment]
Hi @aBoyNicholas 
This issue has been open for 14 days. If you got the answer, please close it.
Thanks.
