### ISSUE TITLE
Why we use “try catch” to implement the condition logic in the ShardingSphereSQLParserEngine.parse0() method?

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#9005]
## Why we use try-catch to implement the condition judgment logic in the ShardingSphereSQLParserEngine.parse0() method?
 
```
    private SQLStatement parse0(final String sql, final boolean useCache) {
        try {
            return sqlStatementParserEngine.parse(sql, useCache);
        } catch (final SQLParsingException | ParseCancellationException originalEx) {
            try {
                return distSQLStatementParserEngine.parse(sql);
            } catch (final SQLParsingException ignored) {
                throw originalEx;
            }
        }
    }
```

**Comment by tristaZero** [comment]
Hi, 
`distSQLStatementParserEngine` and `sqlStatementParserEngine` have similar function though, server as different queries. Therefore, we have to firstly use  `sqlStatementParserEngine` and return the correct parsed result or continue use `distSQLStatementParserEngine` next if there is an exception from  `sqlStatementParserEngine`
