### ISSUE TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of ROLLBACK

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9018]
### Target
- Collate SQL definition of `ROLLBACK` to make SQL definition of `Apache ShardingSphere` the same with Oracle's.
- Add a test case

### How

1. Compare `ROLLBACK` definition in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ROLLBACK.html#GUID-94551F0C-A47F-43DE-BC68-9B1C1ED38C93) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc (**g4 file of ANTLR**)
3. Run `mvn install shardingsphere-sql-parser-oracle` 
4. Check whether there are any exceptions. If exists, please fix them. (Please pay attention to `xxxVisitor.class`)
5. Add new corresponding SQL case in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/sql` and expected parsed result in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case`
6. Run SQLParserParameterizedTest (`shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java`).

### Tips
- Since this issue is a child one of #6480, I guess the PRs relevant to #6480 will give you some examples or hints.

**Comment by ThanoshanMV** [comment]
Hi, I would like to work on this issue

**Comment by tristaZero** [comment]
Hi @ThanoshanMV Welcome. :)

**Comment by ThanoshanMV** [comment]
![sharding-error](https://user-images.githubusercontent.com/48581379/104716854-795aee00-574e-11eb-8a78-0ba4ed3add6f.png)
@tristaZero I've gone through [contributor guide](https://shardingsphere.apache.org/community/en/contribute/contributor/) and set up the project. In `shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle`, I ran `mvn install` and got this error message. Issue is `Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-sql-parser-oracle:jar:5.0.0-RC1-SNAPSHOT`
