### ISSUE TITLE
support explain

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#9030]
## Feature Request

support explain

### Describe the feature you would like.
I expect to use explain to verify whether SQL can be executed.

**Comment by mengJackye** [comment]
It is not supported

**Comment by footmanFF** [comment]
this feature is useful  :)

**Comment by footmanFF** [comment]
have a look at this page:

https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-proxy/usage/

sctl:explain is explain

**Comment by tuichenchuxin** [comment]
I found explain had supported on master branch.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it. Thank you.
