### ISSUE TITLE
Service start stuck without exception after table locking

### ISSUE THREAD

**Issue by tony1991** [apache/shardingsphere#9057]
My shardingsphere version is 4.0.0-RC2
Service start stuck and no exception after table locking.
Also, if I locked table when service running , the service will not response and no exception throw.
I want to catch exception when table is locked, how to do it?

**Comment by terrymanu** [comment]
RC version is not for use, could you try to stable version?

**Comment by tony1991** [comment]
> RC version is not for use, could you try to stable version?
The software version is under the control of the company.

Could you give me some other solutions?  Thank you very much!

**Comment by terrymanu** [comment]
Just tell your company that community response.
`RC` means release candidate, not for stable version.
