### ISSUE TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of DROP TABLE

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#9059]
Target
- Collate SQL definition of DROP TABLE to make SQL definition of Apache ShardingSphere the same with Oracle's.
- Add a test case

HOW
1 Compare DROP TABLE definition in Oficial SQL Doc and ShardingSphere SQL Doc
2 If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc (g4 file of ANTLR)
3 Run mvn install shardingsphere-sql-parser-oracle
4 Check whether there are any exceptions. If exists, please fix them. (Please pay attention to xxxVisitor.class)
5 Add new corresponding SQL case in shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/sql and expected parsed result in shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case
6 Run SQLParserParameterizedTest (shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java).

Tips
- Since this issue is a child one of #6480, I guess the PRs relevant to #6480 will give you some examples or hints.

**Comment by tristaZero** [comment]
Hi @wgy8283335 

> Compare DROP TABLE definition in Oficial SQL Doc and ShardingSphere SQL Doc

Could you point the specific links for `DROP TABLE definition` and `ShardingSphere SQL Doc`?

**Comment by ThanoshanMV** [comment]
Hi, I would like to work on this issue.
