### ISSUE TITLE
Cannot resolve symbol autogen

### ISSUE THREAD

**Issue by ThanoshanMV** [apache/shardingsphere#9069]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Actual behavior
Cannot resolve symbol `autogen` in the import statements. Thus I could not able to use those imported classes.
![import-error](https://user-images.githubusercontent.com/48581379/104849356-3bf18e80-590f-11eb-9765-3901ecf9b5b7.png)
`

**Comment by terrymanu** [comment]
autogen means auto generated. Please run `./mvnw install` first.

**Comment by ThanoshanMV** [comment]
![whole-pic](https://user-images.githubusercontent.com/48581379/104851476-30a46000-591b-11eb-8319-2dfa62355204.png)
When I faced this issue initially, I ran `mvn clean install` and it did not work. Now, I've run `./mvnw install` and the issue stays the same. I restarted the application but it didn't work too. I've attached the screenshot after I ran `./mvnw install` inside the `shardingsphere` directory.

**Comment by ThanoshanMV** [comment]
![solved](https://user-images.githubusercontent.com/48581379/104853160-fe97fb80-5924-11eb-8428-a914f6897503.png)
Hi, I think I solved the issue. Now, it works. Thank you.

**Comment by ThanoshanMV** [comment]
Hi, I think now the issue is resolved. Thank you.

**Comment by xianshun163** [comment]
I  have  do  ./mvnw install  ，but the  issue stays。 Is  that   other   thing  to do ?
