### ISSUE TITLE
ERROR execute sql （select COUNT(*) ckey, COUNT(*) pv, COUNT(DISTINCT user_id) uv,COUNT(DISTINCT ip) ip from tb_record）  

### ISSUE THREAD

**Issue by sunnyshen1991** [apache/shardingsphere#9078]
execute sql （select COUNT(*) ckey, COUNT(*) pv, COUNT(DISTINCT user_id) uv,COUNT(DISTINCT ip) ip from tb_record）

**Comment by sunnyshen1991** [comment]
version：3.1.0.M1    jdbc   @dongzl

**Comment by dongzl** [comment]
> version：3.1.0.M1 jdbc @dongzl 

@sunnyshen1991  `3.1.0.M1` is a out of service version and not an apache version, can you test the newest version?
