### ISSUE TITLE
error of SchemaBuilder append remain tables,it doesn't load table columns

### ISSUE THREAD

**Issue by huanghao495430759** [apache/shardingsphere#9086]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc

### Reason analyze (If you can)
https://github.com/apache/shardingsphere/issues/8605#issuecomment-759364099

I think bug maybe at
->org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder#appendRemainTables line 70
![image](https://user-images.githubusercontent.com/34728144/104995275-fba22580-5a60-11eb-96fe-d7f5c8226d9a.png)

shardingsphere must be load remain table MetaData when System start.

**Comment by dongzl** [comment]
Hi @huanghao495430759 , can you submit a PR and fix this bug?

**Comment by tristaZero** [comment]
Is there any exception relevant to what you pointed?

**Comment by huanghao495430759** [comment]
> Is there any exception relevant to what you pointed?

maybe it is the problem of https://github.com/apache/shardingsphere/issues/8605;
https://github.com/apache/shardingsphere/issues/8605#issuecomment-759364099

**Comment by huanghao495430759** [comment]
Hi @tristaZero ,maybe it is the problem of https://github.com/apache/shardingsphere/issues/8605;
when i run sql of  [SELECT a.*, b.id FROM table_a a LEFT JOIN table_b b ON (a.id = b.id)]
https://github.com/apache/shardingsphere/issues/8605#issuecomment-759364099

**Comment by tristaZero** [comment]
Hi @huanghao495430759 ,

Thanks for your comment. If this issue is duplicate to #8605, maybe we can move our discussion to that one. Still, I will ping @strongduanmu to give it a look since it looks like he is working at your scenario.
