### ISSUE TITLE
A mistake in document.

### ISSUE THREAD

**Issue by lmhmhl** [apache/shardingsphere#9096]
The ` t_score_0` should be ` t_score_1`

https://shardingsphere.apache.org/document/current/cn/features/sharding/principle/rewrite/

<img width="1053" alt="Screen Shot 2021-01-19 at 8 46 19 PM" src="https://user-images.githubusercontent.com/24718258/105038604-805d6580-5a9a-11eb-985d-cc88dd0784a4.png">

**Comment by dongzl** [comment]
Hi @lmhmhl , can you submit a PR and fix it?
