### ISSUE TITLE
create  a  ShardingProxy  *.yaml  ,How to not restart the service  and take effect

### ISSUE THREAD

**Issue by Han-Tang** [apache/shardingsphere#9101]
i have a question:  how to create a *.yaml file and take effect when not restart the service.

**Comment by dongzl** [comment]
Hi @Han-Tang , which version do you use?

I understant if you want to add a new yaml config file, you must restart the proxy.

But you can add config by ShardingSphere-UI, and doesn't need restart proxy.

**Comment by Han-Tang** [comment]
i used  sharding proxy 4.x
