### ISSUE TITLE
masterRouteOnly changed to primaryRouteOnly ?

### ISSUE THREAD

**Issue by jarvisqi** [apache/shardingsphere#9102]
`java
public final class HintManager implements AutoCloseable {
    
    private static final ThreadLocal<HintManager> HINT_MANAGER_HOLDER = new ThreadLocal<>();
    
    private final Multimap<String, Comparable<?>> databaseShardingValues = HashMultimap.create();
    
    private final Multimap<String, Comparable<?>> tableShardingValues = HashMultimap.create();
    
    private boolean databaseShardingOnly;
    
    private boolean primaryRouteOnly;

    /**
     * Set database operation force route to primary database only.
     */
    public void setPrimaryRouteOnly() {
        primaryRouteOnly = true;
    }
`
May I ask which version was changed ？

**Comment by dongzl** [comment]
Hi @jarvisqi , which version do you use?

ShardingSphere-jdbc or ShardingSphere-proxy?

**Comment by jarvisqi** [comment]
> Hi @jarvisqi , which version do you use?
> 
> ShardingSphere-jdbc or ShardingSphere-proxy?

The latest version

**Comment by terrymanu** [comment]
5.0.0-alpha
