### ISSUE TITLE
More test cases for integration test engine.

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9104]
More test cases are needed to ensure  integration test engine covers all the scenarios as many as it can.

Here is a todo list to add cases,

1 For tables (Q1)
- [x] Broadcast table
- [ ] Single table
- [ ] DAL

2 For configuration  (Q1)
- [x] Encryption
- [x] Sharding + Encryption
- [x] Encryption + ReplicaQuery
- [x] Sharding + Encryption + ReplicaQuery

3 For governance
- [ ] Zookeeper
  - [ ] DDL+DML   (Q1)
    - [ ] CREATE TABLE
    - [ ] ALTER TABLE
    - [ ] DROP TABLE
    - [ ] CREATE INDEX
    - [ ] DROP INDEX
    - [ ] CREATE VIEW
    - [ ] DROP VIEW
    - [ ] INSERT
    - [ ] DELETE
    - [ ] UPDATE
    - [ ] CREATE USER
    - [ ] DROP USER
    - [ ] GRANT
    - [ ] REVOKE
  - [ ] RDL(#9964 )
- [ ] ETCD (Later)

4 For databases
- [ ] PostgreSQL JDBC
- [ ] PostgreSQL Proxy
- [ ] Oracle JDBC
- [ ] SQLServer JDBC

5 For Shadow
- [ ] Shadow
- [ ] Sharding + Encryption + ReplicaQuery + Shadow (Later)

6 Data agent
- [ ] Frontend: MySQL  Backend: PostgreSQL
- [ ] Frontend: MySQL  Backend: Oracle/Server
- [ ] Frontend: PostgreSQL  Backend: MySQL
- [ ] Frontend: PostgreSQL  Backend: Oracle/Server

### Tips
- Here is [DOC](https://shardingsphere.apache.org/document/current/cn/features/test-engine/integration-test/) presenting more details
- [Concepts](https://shardingsphere.apache.org/document/current/cn/features/)

**Comment by lmhmhl** [comment]
I wanna have a try

**Comment by JiekerTime** [comment]
I will do it!

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

Currently, @JiekerTime is taking this one. Do you want to try #9117? 
Plus, if you like, I can give more intro about this issue to get you in.

**Comment by lmhmhl** [comment]
> Hi @lmhmhl ,
> 
> Currently, @JiekerTime is taking this one. Do you want to try #9117?
> Plus, if you like, I can give more intro about this issue to get you in.

Hi @tristaZero .
Thanks for your comment. You are so nice, may be I am better for another issue9117.

**Comment by terrymanu** [comment]
Close because of staled.
