### ISSUE TITLE
MySQL InnoDB back-end ShardingSphere-Proxy query result of sql without order by clause is not sorted by primary key ascending

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#9109]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy with MySQL 5.7.29

### Expected behavior
Sort order is the same as MySQL

### Actual behavior
Result not sorted

### Reason analyze (If you can)
Query sql is not rewritten as `ORDER BY`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
config-sharding.yaml snippet:
```
rules:
- !SHARDING
 tables:
   t_order:
     actualDataNodes: ds_${0..1}.t_order_${0..1}
```
table schema:
```
CREATE TABLE `t_order_0 / 1` (
  `order_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB;
```
example query result:
```
mysql> SELECT * FROM t_order WHERE order_id>=1 AND order_id<=10;
+----------+---------+---------------------------+
| order_id | user_id | status                    |
+----------+---------+---------------------------+
|        2 |      94 | inited 2 at 16:47:44.588  |
|        4 |      34 | inited 4 at 16:47:44.607  |
|        6 |      66 | inited 6 at 16:47:44.628  |
|       10 |      80 | inited 10 at 16:47:44.668 |
|        1 |      20 | inited 1 at 16:47:44.571  |
|        5 |      36 | inited 5 at 16:47:44.619  |
|        7 |      50 | inited 7 at 16:47:44.636  |
|        8 |     101 | inited 8 at 16:47:44.645  |
|        3 |      73 | inited 3 at 16:47:44.598  |
|        9 |      23 | inited 9 at 16:47:44.656  |
+----------+---------+---------------------------+
```

**Comment by dongzl** [comment]
Hi @sandynz , I understant that the SQL doesn't have `order by`.

`SELECT * FROM t_order WHERE order_id>=1 AND order_id<=10;`  will get data from `t_order_0` and `t_order_0` and merge the result.

If you want to sort the result, should specify the sort column.

**Comment by sandynz** [comment]
> 
> 
> Hi @sandynz , I understant that the SQL doesn't have `order by`.
> 
> `SELECT * FROM t_order WHERE order_id>=1 AND order_id<=10;` will get data from `t_order_0` and `t_order_0` and merge the result.
> 
> If you want to sort the result, should specify the sort column.

Hi @dongzl , that's true, result ordering is not guaranteed if sql without `order by` clause. But it could be a trival enhancement when backend is MySQL InnoDB, respond similar result as MySQL might be a little better.
