### ISSUE TITLE
Proofread the SQL definition `MERGE` of Oracle database

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9129]
### Introduction
[MERGE](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/MERGE.html#GUID-5692CCB7-24D9-4C0E-81A7-A22436DC968F) SQL is made up of many [basic elements](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Expressions.html#GUID-E7A5363C-AEE9-4809-99C1-1A9C6E3AE017) or [keywords](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-SQL-Reserved-Words-and-Keywords.html#GUID-6A07BB21-AD82-4B47-80FA-9B1141CC23C2).
Hence it is a good thread to help us fix the vague definitions of these basic elements which will compose other complex SQL definition.

### Task
- Work out the vague definition of basic elements
- Proofread `MERGE` definition
- Add test for `MERGE`

### Target files
shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'll try this one.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'm quite unsure about where (in which target files) to add SQL case and expected parsed result for `MERGE`. I couldn't able to find similar test cases for `MERGE` inside `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources`

**Comment by tristaZero** [comment]
Hi @ThanoshanMV ,

Sorry for missing your msg.
Since `MERGE` is a new SQL type, I suggest we create a `merge.xml` in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources`

**Comment by ThanoshanMV** [comment]
Hi @tristaZero,

The count of SQL cases and SQL parser cases are mismatched when I try to run `OracleParserParameterizedTest`. I tried to write a basic one to ensure all okay but it's not considering my new case which is written inside `merge.xml`. Are there any configurations we need to do here?

I've attached the error for your consideration. 
![merge-error](https://user-images.githubusercontent.com/48581379/105805755-b766d600-5fc8-11eb-8aec-e95ab1413f38.png)

**Comment by ThanoshanMV** [comment]
Here are the basic codes inside sql and in case files: 

![merge-sql](https://user-images.githubusercontent.com/48581379/105806277-a9658500-5fc9-11eb-9d3e-15a0fb3a10e1.png)
![merge-case](https://user-images.githubusercontent.com/48581379/105806317-c0a47280-5fc9-11eb-9da3-d5d14ba7f9a5.png)

**Comment by tristaZero** [comment]
Hi @ThanoshanMV ,

Since `merge` is a new SQL type, we plan to create a `merge.xml`, right? Correspondingly we still need to define which parts of this SQL need assertion, like `tableName`, `columnType` etc.

Therefore, after creating `merge.xml`, it is necessary to define `@XmlElement(name = "merge")` in `SQLParserTestCases` to tell `SQLParserTestCasesRegistry` to load your new `sql-parser-test-cases`.

The main work above is to operate `javax.xml` (A common file type for developers). I am not sure whether you ever tried it, but we can start with `imitation`.  :-)

Here are some steps for your consideration,
- Add `@XmlElement(name = "merge")` to `SQLParserTestCases`
- Create `MergeStatementTestCase` referring to other `xxxStatementTestCase` in that file (`SelectStatementTestCase` is a good one)
- No need to fill all the elements in `MergeStatementTestCase` once. Just enrich it little by little to cover your SQL cases. (Don't discourage ourselves at first sight, :-) )

**Comment by ThanoshanMV** [comment]
Okay @tristaZero, I'll try to do it.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, 

Now, I'll try to add further test cases for `MERGE`.

**Comment by tristaZero** [comment]
@ThanoshanMV Please go ahead.
