### ISSUE TITLE
Add test case for SingleTableRuleLoader

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#9135]

**Comment by liveonsky** [comment]
I want to try it

**Comment by arthasking123** [comment]
please assign to me

**Comment by huanghao495430759** [comment]
Is there any updates of this issue?

**Comment by liveonsky** [comment]
There is currently no update.It takes a long time to download master.zip.
I'm looking at the singleTableRuleLoader.java class.
I have no application development foundation. Is there any other test reference for me.
thank you!

**Comment by liveonsky** [comment]
I understand that I need to create a "single" directory  in the "/shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/test/java/org/apache/shardingsphere/sharding/rule"
”, and then create the “SingleTableRuleLoaderTEST.java” Class.

**Comment by huanghao495430759** [comment]
> There is currently no update.It takes a long time to download master.zip.

@liveonsky 
does you have gitee[https://gitee.com/] account ?
you can try faster way to download ss  repositories : 
`
1.fork apache/shardingsphere to your github repositories, 
2.use your gitee account and sync your shardingsphere project,
3.clone shardingsphere from gitee repositories to your local development env.
`

**Comment by huanghao495430759** [comment]
> I understand that I need to create a "single" directory in the "/shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/test/java/org/apache/shardingsphere/sharding/rule"
> ”, and then create the “SingleTableRuleLoaderTEST.java” Class.

@liuyueve 
I have no any idea to U. but I think U must be understond SingleTableRuleLoader what it do first.
and maybe you can read 

`
org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderTest
org.apache.shardingsphere.infra.metadata.schema.builder.loader.SchemaMetaDataLoaderTest
`
learn how to mock DataSource to load table metadatas.

**Comment by liveonsky** [comment]
> > There is currently no update.It takes a long time to download master.zip.
> 
> @liveonsky
> does you have gitee[https://gitee.com/] account ?
> you can try faster way to download ss repositories :
> `1.fork apache/shardingsphere to your github repositories, 2.use your gitee account and sync your shardingsphere project, 3.clone shardingsphere from gitee repositories to your local development env.`

thanks!

**Comment by liveonsky** [comment]
> 3.clone shardingsphere from gitee repositories to your local development env.



> > There is currently no update.It takes a long time to download master.zip.
> 
> @liveonsky
> does you have gitee[https://gitee.com/] account ?
> you can try faster way to download ss repositories :
> `1.fork apache/shardingsphere to your github repositories, 2.use your gitee account and sync your shardingsphere project, 3.clone shardingsphere from gitee repositories to your local development env.`



> > There is currently no update.It takes a long time to download master.zip.
> 
> @liveonsky
> does you have gitee[https://gitee.com/] account ?
> you can try faster way to download ss repositories :
> `1.fork apache/shardingsphere to your github repositories, 2.use your gitee account and sync your shardingsphere project, 3.clone shardingsphere from gitee repositories to your local development env.`


Thanks！Steps 1 and 2 have been completed, and 3 always fails. My source code has been downloaded successfully, now I am reading and trying to add the test.

**Comment by liveonsky** [comment]
> > I understand that I need to create a "single" directory in the "/shardingsphere/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-common/src/test/java/org/apache/shardingsphere/sharding/rule"
> > ”, and then create the “SingleTableRuleLoaderTEST.java” Class.
> 
> @liuyueve
> I have no any idea to U. but I think U must be understond SingleTableRuleLoader what it do first.
> and maybe you can read
> 
> `org.apache.shardingsphere.infra.metadata.schema.builder.loader.TableMetaDataLoaderTest org.apache.shardingsphere.infra.metadata.schema.builder.loader.SchemaMetaDataLoaderTest`
> learn how to mock DataSource to load table metadatas.


Thank you for your advice！

**Comment by GLBB** [comment]
@liveonsky  Are you still in work for the issue? I want to complete issue to familiar project
