### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by ThanoshanMV** [apache/shardingsphere#9143]
### Which version of ShardingSphere did you use?
`5.0.0-RC1-SNAPSHOT`

### Actual behavior
Build fails in `shardingsphere-jdbc-core`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I executed `./mvnw install` in `shardingsphere`, it failed in `shardingsphere-jdbc-core`. 
![sharding](https://user-images.githubusercontent.com/48581379/105610154-3810b100-5dd4-11eb-9325-263e1bfad6a2.png)

**Comment by ThanoshanMV** [comment]
![jdbc-core](https://user-images.githubusercontent.com/48581379/105610381-6c38a180-5dd5-11eb-8386-02f1190321e3.png)
The following error occurred inside `shardingsphere-jdbc-core`

**Comment by terrymanu** [comment]
Thank you for reporting, some test cases are error, I will try to investigate it.
