### ISSUE TITLE
db connection in sharding-jdbc still does not support array  type

### ISSUE THREAD

**Issue by hebing0625** [apache/shardingsphere#9164]
hi,

There still has a issue when I try to create array with connection as below:

`Connection conn = shardingDataSource.getConnection();`
`conn.createArrayOf("int8", new Long[]{1L, 2L, 3L});`

A SQLFeatureNotSupportedException will be thrown.

I trace the codes and find such snippets in SQLFeatureNotSupportedException.java:

`@Override public final Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {`
`throw new SQLFeatureNotSupportedException("createArrayOf"); }`

**Comment by tristaZero** [comment]
Hi @hebing0625 ,

You're right. ShardingSphere does not implement this interface of JDBC currently.
BTW, have you tried this interface with other database driver, like MySQL or Postgre?

**Comment by hebing0625** [comment]
Do you have plan to support it in future?

**Comment by tristaZero** [comment]
Hi,

I am unsure now. We definitely want to have excellent support for JDBC Driver. However, there are so many features to do currently. Also,  there are many contributors willing to have a try to fix it. That's why I ask your interest. Benefit yourself and others.

**Comment by sandynz** [comment]
Hi @hebing0625 , you could use `java.sql.PreparedStatement.setObject` for now, e.g. `statement.setObject(1, new long[]{1, 2, 3})`.

I'll try to support `java.sql.Connection.createArrayOf`.
