### ISSUE TITLE
[RDL] Support create/alter multiple bindTable groups

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9168]
`CREATE/ALTER SHARDING RULE` supports multiple bindTable groups by the following RDLs.

```sql
CREATE SHARDING RULE (
binding_tables((t_order, t_item), (t1, t2, t3))
) 

ALTER SHARDING RULE (
binding_tables((t_order, t_item))
)
```

**Comment by jingshanglu** [comment]
Now, `CREATE/ALTER SHARDING RULE` has supported multiple bindTable groups, like this:
```
CREATE SHARDING RULE (
...
binding_tables(t_order t_item, t1  t2  t3)
) 

ALTER SHARDING RULE (
...
binding_tables(t_order t_item)
)
```

**Comment by terrymanu** [comment]
How about 

```sql
CREATE SHARDING RULE (
...
binding_table(t_order t_item)
binding_table(t1  t2  t3)
) 

ALTER SHARDING RULE (
...
binding_table(t_order t_item)
)
```

**Comment by jingshanglu** [comment]
@terrymanu @tristaZero When create sharding rule, you can use multiple `binding_table`. When alter sharding rule, what is the meaning of using multiple `binding_table`?

**Comment by jingshanglu** [comment]
@terrymanu @tristaZero It is recommended to keep the status. when create or alter, the bindingTableGroup will be created or modified.

**Comment by tristaZero** [comment]
Hi, @jingshanglu ,
Thank for feedback.

here are two ways to figure out this issue,
```sql
// Add rule id for each bind rule

CREATE SHARDING RULE (
...
binding_table bt1 (t_order t_item)
binding_table bt2 (t1  t2  t3)
) 

ALTER SHARDING RULE (
...
binding_table bt1 (t_order t_item)
)

// Keep current handling
CREATE SHARDING RULE (
...
binding_tables(t_order t_item, t1  t2  t3)
) 

ALTER SHARDING RULE (
...
binding_tables(t_order t_item)
)
```

What do you think?

**Comment by terrymanu** [comment]
I prefer add rule id for each bind rule, it is similar with original SQL
By the way, the SQL ALTER should add operation type, such as `ADD, MODIFY, DROP`. For example:

```sql
ALTER SHARDING RULE (
...
MODIFY binding_table bt1 (t_order t_item)
)
```

**Comment by tristaZero** [comment]
After a brief discussion, here is the final conclusion,
```sql
CREATE SHARDING RULE (
...
binding_table (t_order t_item),
binding_table (t1  t2  t3)
) 

ALTER SHARDING RULE (
...
add binding_table (t_order t_item t_new),
drop binding_table (t_order t_item)
)
```

**Comment by terrymanu** [comment]
Cool, it is better, we do not need to change our SQLStatemtnt domain.
