### ISSUE TITLE
An error of pagination

### ISSUE THREAD

**Issue by nrg1982lixi** [apache/shardingsphere#9177]
When I was using pagination, sharding-jdbc throw an exception, didn't sharding-jdbc support sub-query?
database: Oracle
sharding-jdbc version: 4.0.1

### Cause: java.lang.IllegalStateException: Must have sharding column with subquery.

**Comment by tristaZero** [comment]
Hi @nrg1982lixi 
4.0.1 does not support subquery well, I suggest  you try a updated release.

**Comment by terrymanu** [comment]
No response
