### ISSUE TITLE
COUNT may have an out-of-bounds exception

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9185]
The logic of COUNT() seems to be in GroupByMemoryMergedResult.setAggregationValueToMemoryRow, and the way to get the result here seems to be to call the getResult method：
![716041eea1ef12661c24bab527c70d4](https://user-images.githubusercontent.com/76552510/105947026-338b0900-601d-11eb-890c-c0ad3ae5e1c6.jpg)
The logic of size is based on HashSet, and its return type is int type.：
![image](https://user-images.githubusercontent.com/76552510/105945651-88795000-601a-11eb-8b30-2bc36a66988a.png)

If the future size exceeds the range of int, unexpected errors may occur.

Then since HashMap is used, is it possible that it will cause some concurrency problems in the future?

**Comment by terrymanu** [comment]
What is the version?

**Comment by JiekerTime** [comment]
> What is the version?

In the 5.0.0 branch, which is also valid in the current version

**Comment by terrymanu** [comment]
Close because of staled.
