### ISSUE TITLE
sharding-proxy 5.0 Configuration preciseAlgorithmClassName error

### ISSUE THREAD

**Issue by Leovoc** [apache/shardingsphere#9198]
Hi,In sharding - proxy configuration in 5.0 the custom rules of depots, look at the journal quoted: "Unable to find the property 'preciseAlgorithmClassName on class: org. Apache. Shardingsphere. Sharding. Yaml. Config. The strategy. The sharding. YamlStandardShardingStrategyConfiguration".Same configuration I can be in the sharding - proxy4.1 version, whether preciseAlgorithmClassName configuration position did change in the version 5.0?It is the place where I in version 5.0 preciseAlgorithmClassName configuration.
![image](https://user-images.githubusercontent.com/18509916/106099435-a0b1b200-6175-11eb-9b8d-1a18a3868763.png)

**Comment by terrymanu** [comment]
Can you follow example for the correct version?

**Comment by terrymanu** [comment]
No response
