### ISSUE TITLE
no viable alternative at input 'offline'

### ISSUE THREAD

**Issue by LHRH** [apache/shardingsphere#9201]
## Bug Report

add mysql keyword offline to unreservedWord

**Comment by JiekerTime** [comment]
Hi~ @LHRH!
 If possible, please give more detailed information, such as your configuration information and business logic. This will help us find the problem quickly. thank!

**Comment by terrymanu** [comment]
What is your version?

**Comment by LHRH** [comment]
4.1.1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 上午9:19
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"LH"<995549467@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] no viable alternative at input 'offline' (#9201)





 
What is your version?

**Comment by LHRH** [comment]
mysql-version:8.0
shardingsphere:4.1.1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 上午9:19
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"LH"<995549467@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] no viable alternative at input 'offline' (#9201)





 
What is your version?

**Comment by jingshanglu** [comment]
@LHRH Plz use 5.0.0.

**Comment by jingshanglu** [comment]
It has been fixed by 5.0.0-alpha ..
