### ISSUE TITLE
The integration test framework needs to add the initialization function of H2's single table

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9216]
First, it is clear that the single table needs to create a unique table in databases.

The logic of H2 loading init.sql is located in DatabaseEnvironmentManager.executeInitSQLForSchemaNotSupportedDatabase.

The execution logic here is to load init.sql once with each data source.
![image](https://user-images.githubusercontent.com/76552510/106235689-06229480-61b0-11eb-8ff4-e991f4efea41.png)
If you simply put the logic of creating a single table into init.sql, it may cause "Single table conflict, there are multiple tables `t_single_table` existed."

Therefore, I think we need to rewrite H2's init.sql loading method or create a single table creation method for H2 to help us initialize the single table.

**Comment by terrymanu** [comment]
H2 will remove soon, we can close this issue
