### ISSUE TITLE
10002 _ 2Unknown exception [Can not route tables for '[ENGINES]', please make sure the tables are in same schema

### ISSUE THREAD

**Issue by fengchao-GitHub** [apache/shardingsphere#9218]
version: sharding proxy 5.0.0

yml: 

schemaName: sharding_db

dataSourceCommon:
  username: root
  password: 123456
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  ds1:
    url: jdbc:mysql://192.168.255.115/testdb1?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
  ds1_slave:
    url: jdbc:mysql://192.168.255.116/testdb1?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
  ds2:
    url: jdbc:mysql://192.168.255.115/testdb2?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
  ds2_slave:
    url: jdbc:mysql://192.168.255.116/testdb2?serverTimezone=UTC&useSSL=false&characterEncoding=utf8

rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ms_ds${1..2}.t_order${1..2}
        databaseStrategy:
          standard:
            shardingColumn: uid
            shardingAlgorithmName: database_inline
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    bindingTables:
      - t_order
    broadcastTables:
      - t_user
      - t_org
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ms_ds${uid % 2+1}
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order${order_id % 2+1}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

  - !REPLICA_QUERY
    dataSources:
      ms_ds1:
        primaryDataSourceName: ds1
        replicaDataSourceNames:
          - ds1_slave
        loadBalancerName: ROUND_ROBIN
      ms_ds2:
        primaryDataSourceName: ds2
        replicaDataSourceNames:
          - ds2_slave
        loadBalancerName: ROUND_ROBIN

##############################################
*** when I try to connect the proxy db it misreport:
10002 _ 2Unknown exception [Can not route tables for '[ENGINES]', please make sure the tables are in same schema.]

![image](https://user-images.githubusercontent.com/64132316/106251017-6ae0fc00-624f-11eb-8acc-32972478eae0.png)

**Comment by tristaZero** [comment]
Hi `ENGINES` is a table?

**Comment by fengchao-GitHub** [comment]
yes it is a table in database 'information_schema' 
![image](https://user-images.githubusercontent.com/64132316/106423304-25187380-649b-11eb-985f-3d5441f35428.png)

**Comment by tristaZero** [comment]
Hi @fengchao-GitHub ,

Could you see `information_schema` in this client? It looks like SS do not load the metadata of `information_schema` and its tables.

Hi @tuohai666 , could you give it a look? I met some of the similar issues, but I am unsure it is easy to handle.

**Comment by tuohai666** [comment]
@fengchao-GitHub 
Please set sql.show: true in server.yaml when reproduce this problem, and provide the log with SQLs.
BTW, what's the MySQL client?

**Comment by tuohai666** [comment]
Duplicated with https://github.com/apache/shardingsphere/issues/6693
