### ISSUE TITLE
sharding-jdbc 4.1.1性能压测不理想，单表单库TPS为集成sharding-jdbc的10倍以上

### ISSUE THREAD

**Issue by wangzhuangwei** [apache/shardingsphere#9243]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by tuohai666** [comment]
**For English only**, other languages will not accept.
