### ISSUE TITLE
encrypt-rule does not support "not in" conditional column

### ISSUE THREAD

**Issue by 414135289** [apache/shardingsphere#9255]
version 4.0.0

When I used encrypt-rule for data encryption, I found a problem.When I use the "not in" condition to query the encrypted column, the component will not automatically encrypt the query field. From the source code,I found that there is no "not in" query condition in the SQLStatement object returned by the parse method of the SQLParserEngine class.

For example：

    @Test
    public void notInTest(){
        String sql = "select * from a where a.a not in ('1','2') and a.b in ('11','22')";
        SQLParserEngine result = new SQLParserEngine("MySQL");
        SQLStatement statement = result.parse(sql,false);
    }

![image](https://user-images.githubusercontent.com/16203942/106443038-0031f980-64b7-11eb-817b-51d4b89a1526.png)

So I want to know if this is a bug?

**Comment by tristaZero** [comment]
Hi @414135289 ，

> I found that there is no "not in" query condition in the SQLStatement object 

You're right, Ver 4.0.0 does not support the query with `not in` condition. 

Hi @jingshanglu Do we parse `not in` condition into `SQLstatement` in our 5.0.0-alpha Version?

**Comment by jingshanglu** [comment]
@414135289 @tristaZero It's already supported in version 5.0.0-alpha.

**Comment by 414135289** [comment]
thanks
