### ISSUE TITLE
Add document of mix rule configuration description

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#9286]
- [x] Summary
  - [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/_index.en.md
  - [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/_index.cn.md
- [ ] Java config
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/mix.en.md
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/mix.cn.md
- [ ] YAML config
  - [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/yaml/mix.en.md
  - [x] docs/document/content/user-manual/shardingsphere-jdbc/configuration/yaml/mix.cn.md
- [ ] spring-boot-starter config
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/mix.en.md
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/mix.cn.md
- [ ] spring-namespace config
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/mix.en.md
  - [ ] docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/mix.cn.md

**Comment by huanghao495430759** [comment]
please assign to me
