### ISSUE TITLE
insert sql  include keyword column, insert fail ?

### ISSUE THREAD

**Issue by wuzhiwei18** [apache/shardingsphere#9292]
when my tables has keyword column, before insert, The symbol ' will be added, but sharding auto remove the symbol, Cause insert to fail.
the code ：
class SQLUtil : 
method:  getExactlyValue

`public static String getExactlyValue(final String value) {
        return null == value ? null : CharMatcher.anyOf("[]`'\"").removeFrom(value);
    }`

**Comment by wuzhiwei18** [comment]
this keyword column is  show.   original sql is 
`insert into album( app_id,`name`,cover_path,content,
`show`,hot,`free` ) values ( ?,?,?,?,?,?,? )`
after rewrite ;
`insert into album  (app_id, name, cover_path, content, show, hot, free) VALUES (?, ?, ?, ?, ?, ?, ?) `
this show column lost symbol ` 
error msg :
`{
    "code": 500,
    "data": null,
    "message": "\r\n### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show, hot, free) VALUES ('3001', '图集2', '132545w34', '[{\"order\":1,\"picPath\":' at line 2\r\n### The error may exist in file [D:\\development\\rockyplay-games\\rockyplay-game-admin\\target\\classes\\mapper\\AlbumDao.xml]\r\n### The error may involve com.rockyplay.game.admin.dao.album.AlbumDao.insertSelective-Inline\r\n### The error occurred while setting parameters\r\n### SQL: insert into album          ( app_id,                                           `name`,                                           cover_path,                                           content,                                                        `show`,                                           hot,                                           `free` )           values ( ?,                                           ?,                                           ?,                                           ?,                                                        ?,                                           ?,                                           ? )\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show, hot, free) VALUES ('3001', '图集2', '132545w34', '[{\"order\":1,\"picPath\":' at line 2\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show, hot, free) VALUES ('3001', '图集2', '132545w34', '[{\"order\":1,\"picPath\":' at line 2"
}`

**Comment by tristaZero** [comment]
@wuzhiwei18 
Which version do you use?
What's DBMS running in your env?

**Comment by terrymanu** [comment]
Closed because of no feedback
