### ISSUE TITLE
select ...left join ... ,the select cloumn not be rewrite except the frist table encrypt cloumns .

### ISSUE THREAD

**Issue by liuchaoheliang** [apache/shardingsphere#9298]
version: 5.0.0-alpha

my config 
spring.shardingsphere.props.query-with-cipher-column=true
spring.shardingsphere.rules.encrypt.tables.user_info.columns.name.cipherColumn=name_enc
spring.shardingsphere.rules.encrypt.tables.user_info.columns.name.encryptorName=name_encryptor
spring.shardingsphere.rules.encrypt.tables.user_info.columns.mobile.cipherColumn=mobile_enc
spring.shardingsphere.rules.encrypt.tables.user_info.columns.mobile.encryptorName=mobile_encryptor
spring.shardingsphere.rules.encrypt.tables.user_info.columns.ident.cipherColumn=ident_enc
spring.shardingsphere.rules.encrypt.tables.user_info.columns.ident.encryptorName=idcard_encryptor
spring.shardingsphere.rules.encrypt.tables.test_name.columns.phone.cipherColumn=phone_enc
spring.shardingsphere.rules.encrypt.tables.test_name.columns.phone.encryptorName=name_encryptor
spring.shardingsphere.rules.encrypt.tables.users.columns.test_value.cipherColumn=test_value_enc
spring.shardingsphere.rules.encrypt.tables.users.columns.test_value.encryptorName=name_encryptor

Logic SQL: select ui.name,ui.mobile,u.test_value,tn.phone from user_info ui left join  users u on u.id = ui.id left join test_name tn on tn.id = u.id where ui.name ='test' group by ui.name

Actual SQL: ds0 ::: select ui.name_enc AS name,ui.mobile_enc AS mobile,**u.test_value,tn.phone** from user_info_0 ui left join  users u on u.id = ui.id left join test_name tn on tn.id = u.id where ui.name_enc ='*nGdJAcXN2T+XkR1YXQ+lbYw==' group by **ui.name** ORDER BY ui.name ASC 

there u.test_value , tn.phone should be rewrite  u.test_value_enc as test_value, tn.phone_enc as phone 
and group by ui.name also should be rewrite ui.name_enc , right ?

**Comment by tristaZero** [comment]
@JiekerTime 

Please give this SQL with encryption feature a try. It is very likely a point to improve.

**Comment by terrymanu** [comment]
Duplicate with #9334
