### ISSUE TITLE
line 1:78 no viable alternative at input 'full'

### ISSUE THREAD

**Issue by LHRH** [apache/shardingsphere#9315]
line 1:78 no viable alternative at input 'full'
line 1:78 mismatched input 'full' expecting {'!', '~', '+', '-', '.', '(', '{', '?', '@', TRUNCATE, POSITION, VIEW, VALUES, CASE, CAST, TRIM, SUBSTRING, LEFT

shardingsphere version:4.1.1

**Comment by jingshanglu** [comment]
@LHRH Can you show the sql?

**Comment by LHRH** [comment]
SELECT guid,is_system,status,version,creator,create_time,modifier,modify_time,full,got,post,del,patch,put FROM sys_routes_ignore WHERE status = ?

**Comment by jingshanglu** [comment]
@LHRH It has been fixed in version 5.0.0-alpha.

**Comment by LHRH** [comment]
5.0.0-release   Release time？

**Comment by jingshanglu** [comment]
It is under test. It can only be released after passing the test.
