### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by zht0209** [apache/shardingsphere#9325]
public synchronized long getEndIndex(final long fromIndex, final int size) {
        if (size == 0) {
            return fromIndex;
        }
        int correctIndex = (int) (fromIndex - startIndex);
        int listIndex = correctIndex / BIT_SET_SIZE;
        int count = size;
  
        for (int i = listIndex; i < bitSets.size(); i++) {
            int begin = i == listIndex ? correctIndex % BIT_SET_SIZE : 0;
            for (int j = begin; j < BIT_SET_SIZE; j++) {
                if (bitSets.get(i).get(j) && --count == 0) {
                    return startIndex + i * BIT_SET_SIZE + j + 1;
                }
            }
        }
        throw new IndexOutOfBoundsException(String.format("BitSets(%s) do not have enough data from %d count %d", bitSets, correctIndex, size));
    }

当fronIndex< startIndex，listIndex会小于0

**Comment by menghaoranss** [comment]
@zht0209 For English only

**Comment by Lucas-307** [comment]
let me see

**Comment by Lucas-307** [comment]
@zht0209 Could you pleace give me more detail to reproduce it.
I don't why this case happen.

**Comment by zht0209** [comment]
> @zht0209 Could you pleace give me more detail to reproduce it.
> I don't know why this case happen.

增量迁移的时候，当Placeholder Record 大于1024时,此时进来一个DataRecord,startIndex将改变成1024,fetchRecords的fromIndex是0,所以correctIndex将会变成负数

**Comment by Lucas-307** [comment]
I got it. 
when fromIndex < startIndex, may be correctIndex = 0 is better.
```
int correctIndex = fromIndex < startIndex ? 0 : (int) (fromIndex - startIndex);
```
