### ISSUE TITLE
[API] New yaml configuration for authentication of ShardingProxy

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9326]
Hi community,

ShardingProxy will support `create/drop user` and `grant/revoke` SQL in the future, which means ShardingProxy is going to have the privileges checking capability (#8966). The basic function is similar to [Privileges Provided by MySQL](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html).

This issue is to do API change for `authentication` in `server.yaml` to **remain the simple user configuration**.

### Comparison for current and intending authentication configuration
```sql
// Current one
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding 

// Intending one
users:
  - username@hostname:password
  - root@127.0.0.1:root_pwd
```
Each line with `username`, `hostname` and `password` items will be viewed as a user record, where key parts are split by `@` and `:`

### How

There are two main phases for this work, i.e., the change for`local configuraion` and `registry configuration`.

####Local configuration change
- Replace `authentication` in `YamlProxyServerConfiguration.java` with a collection<String>
- A new util class is expected to transform user records (collection<String>) to a collection<YamlUserConfiguration>
- `UserYamlSwapper` is still needed to transform `YamlUserConfiguration` and `ShardingSphereUser`
- Delete `UserRuleYamlSwapper` and `YamlUserRuleConfiguration`
- Fix relevant issue in this project caused by your previous changes

#### Registry configuration change
- Modify `AUTHENTICATION_NODE` to `USERS_NODE` in `ConfigCenterNode`
- `convertUsers()` is expected to replace `convertAuthentication()`
- Fix relevant issue in this project caused by your changes above

### Notices
- It is not an easy one, so I suggest anyone who wants to have a try to firstly read [Privileges](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/configuration/authentication/) and [Governance](https://shardingsphere.apache.org/document/current/cn/features/governance/management/config-center/)
- If you have any question, please be free to comment here.

**Comment by lmhmhl** [comment]
I want to do it

**Comment by tristaZero** [comment]
@lmhmhl Welcome.

**Comment by lmhmhl** [comment]
@tristaZero I have make some try, but I don't know whether I am right or not, due to I am not familiar with the source code, so I may spend some time doing deep learning of the source code. When I read the source code, I felt confused and don't know what's the meaning of some detail. I think I am lost in the desert, can you recommend me some learning material of the source code.

**Comment by lmhmhl** [comment]
Hi @tristaZero ,I am sorry that  It is a really long time I have been doing this issue. Due to Chinese NewYear holiday, I haven't seen this issue a few days, when I did this issue, I do encountered some troubles and made me upset, but I don't want to give up, should I do another issue 9416 first?

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

Undoubtedly you can set the priority for these issues. 
Take it easy and just follow your schedule. :)
Have a nice day.

**Comment by huanghao495430759** [comment]
Hi, can I try it ?

**Comment by tristaZero** [comment]
Hi @huanghao495430759  Thanks for your comment, and please have my welcome. 

Since @lmhmhl firstly shows his interest in this one, but it looks he has no enough time recently, let us listen to his thought.
How do you think @lmhmhl ?

**Comment by lmhmhl** [comment]
@tristaZero, Thank you for understanding me, please assign to @huanghao495430759. Thx.

**Comment by tristaZero** [comment]
@huanghao495430759 
If any confusions, please ping me here.

**Comment by tristaZero** [comment]
Hi @huanghao495430759  are you working on this one?

**Comment by huanghao495430759** [comment]
> Hi @huanghao495430759 are you working on this one?

Hi @tristaZero , yes, I am working on this issue, and I have a question, 
if delete  `YamlUserRuleConfiguration`,  and `YamlUserConfiguration` must be add  a property to save the `username`  right ?

**Comment by tristaZero** [comment]
@huanghao495430759 ,

> YamlUserConfiguration must be add a property to save the username

I think so. This file will contain the user information.

**Comment by huanghao495430759** [comment]
Hi @tristaZero , I have another question, now the register center save the authentication data is :

`
users:
  root:
    hostname: '%'
    password: root
  sharding:
    hostname: '%'
    password: sharding

`

does it also change to 
`
users:
  - root@%:root
  - sharding@%:sharding
`

?

**Comment by huanghao495430759** [comment]
> @huanghao495430759 ,
> 
> > YamlUserConfiguration must be add a property to save the username
> 
> I think so. This file will contain the user information.

Hi @tristaZero , I have another question, now the register center save the authentication data is :

`
users:
root:
hostname: '%'
password: root
sharding:
hostname: '%'
password: sharding

`

does it also change to
`
root@%:root
sharding@%:sharding
`
?

**Comment by huanghao495430759** [comment]
> @huanghao495430759 ,
> 
> > YamlUserConfiguration must be add a property to save the username
> 
> I think so. This file will contain the user information.

Hi @tristaZero  , I have another question, now the register center save the authentication data is :

zk node is : authentication
and data is
`
users:
  root:
    hostname: '%'
    password: root
  sharding:
    hostname: '%'
    password: sharding

`

does it also change to 
zk node is: users
`
users:
  - root@%:root
  - sharding@%:sharding
`

or
`
!!map
- !!org.apache.shardingsphere.infra.metadata.auth.builtin.yaml.config.YamlUserConfiguration
  hostname: '%'
  password: root
  username: root
- !!org.apache.shardingsphere.infra.metadata.auth.builtin.yaml.config.YamlUserConfiguration
  hostname: ''
  password: root1
  username: root1

 `

**Comment by huanghao495430759** [comment]
Hi @tristaZero  ,I had resolve my confusions, the new zk node path is
`\users`
and node data will save the list of users, like  :

`
users:
  - hostname: '%'
    password: root
    username: root
  - hostname: ''
    password: sharding
    username: sharding

`
am I rigth ?

**Comment by huanghao495430759** [comment]
Oh, I got it, the users authentication of register center should keep pace with local config in ` server.yaml` , so the new zk node path is `/users`,
and node data is 
`
users:
    - username@:password
    - root@127.0.0.1:root
    
`
am i right ? @tristaZero

**Comment by tristaZero** [comment]
Hi,

I assume the original `authentication` node at zk has its father nodes, isn't it?
The content of new node, i.e, `users` is supposed to be a collection of user info without `users:`

**Comment by huanghao495430759** [comment]
> Hi,
> 
> I assume the original `authentication` node at zk has its father nodes, isn't it?
> The content of new node, i.e, `users` is supposed to be a collection of user info without `users:`

look like 
![image](https://user-images.githubusercontent.com/34728144/113106307-3250a500-9235-11eb-8889-59b840fded3b.png)
?  @tristaZero

**Comment by tristaZero** [comment]
``` java
@Getter
@Setter
public final class YamlProxyServerConfiguration implements YamlConfiguration {
    
    // To be deleted
    private YamlUserRuleConfiguration authentication;
    
    // To be added
    private Collection<String> users;
    
    private YamlGovernanceConfiguration governance;
    
    private YamlScalingConfiguration scaling;
    
    private Properties props = new Properties();
}
```

`users` will be transformed into `Collection<ShardingSphereUser> users` of `ProxyConfiguration` by `YamlUserConfigurationSwapper` (Or probably `UserRuleYamlSwapper`).
