### ISSUE TITLE
Failed to parse sensitive field under encryption scenario

### ISSUE THREAD

**Issue by giggs131400** [apache/shardingsphere#9334]
### Which version of ShardingSphere did you use?
5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. we have two tables, one is student, the other is score. And table student have column "stuname" we need to encryt
2. we have sql:
```sql
select student.id, uid, stuname 
from score 
left join student on student.id = score.id
where stuname = ?
```
3.  after shardingsphere rewrite it, we expected: 
```sql
select student.id, uid, stuname_enc 
from score 
left join student on student.id = score.id
where stuname_enc = ?
```
but actually it parsed:
```sql
select student.id, uid, **stuname**
from score 
left join student on student.id = score.id
where stuname_enc = ?
```

4. another scenario, we have sql:
```sql
select AA.id, AA.uid, AA.stuname 
from (select * from student whre stuname = ?) as AA
```
after rewrite it, we expect
```sql
select AA.id, AA.uid, AA.stuname_enc AS stuname 
from (select * from student whre stuname_enc = ?) as AA
```
but actually it parsed:
```sql
select AA.id, AA.uid, AA.stuname_enc AS stuname 
from (select * from student whre stuname = ?) as AA
```

**Comment by terrymanu** [comment]
There are 2 problems in this issue.

The first problem is for SELECT JOIN , I just add the test case about it, please see #9346. 
It is OK, so could you try the master branch?

The second problem is for sub-query which is not in the current scope, we cannot process sub-query as well.
There is no plan for now.

**Comment by terrymanu** [comment]
ref #9349

**Comment by giggs131400** [comment]
I still encounter the first problem, and I add the steps how to reproduce it under the #9346

**Comment by terrymanu** [comment]
It has been supported in version `5.0.0-beta`
