### ISSUE TITLE
Exception occured when loading metadata

### ISSUE THREAD

**Issue by rtj599** [apache/shardingsphere#9336]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

project works

### Actual behavior

SQLException:S0022 Unknown Column Id xxx 

### Reason analyze (If you can)

error occurs in com.mysql.cj.jdbc.result.ResultSetImpl#findColumn(String) which is called by org.apache.shardingsphere.sql.parser.binder.metadata.column.TableMetaDataLoader#load(java.sql.Connection,String,String)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

There are two tables in the same db, we assume that db name(schema name)was 'shard',one table name was 'table_1', another table name was 'shard.table_1',  table 'table_1' had column 'table_1_column' while table 'shard.table_1' didn't have .
testing DDL statements are as follow:
```

create database `shard`;
create table `table_1`(
    `id` int not null auto_increment primary key,
    `table_1_column` varchar(32) default null,
    `another_column` varchar(32) default null
)engine =innodb;

create table `shard.table_1`(
    `id` int not null auto_increment primary key,
    `another_column` varchar(32) default null
)engine =innodb;`
```

when table 'shard.table_1' was being scanned, after executing generated empty sql ```SELECT * FROM `shard.table_1` WHERE 1<>1'``` but colum name 'table_1_column' was in the result set of colums metadata, then this exception occured.

**Comment by terrymanu** [comment]
Cloud you try to version 5.0.0-alpha?

**Comment by rtj599** [comment]
> Cloud you try to version 5.0.0-alpha?

ok,but we prefer a stable version to an alpha version. Could you please give me an  approximate time that a stable version of shardingsphere release?I think so many devs are waiting for it :)

**Comment by terrymanu** [comment]
It seems fix the problem in 5.0.0-alpha.
I have no idea to both keep old version and new feature.

**Comment by rtj599** [comment]
it seems that my bad English led to your misunderstanding about what I have asked,I just care about when we can use a newer stable version than 5.0.0-alpha which have lower risk to be used in some important business situations.

**Comment by terrymanu** [comment]
The version 5.x is still develop rapidly.
I am not sure when can we release the stable version.
