### ISSUE TITLE
does support fulltext search

### ISSUE THREAD

**Issue by jackjoesh** [apache/shardingsphere#9337]
does shardingjdbc support fulltext search?

**Comment by terrymanu** [comment]
What is the SQL about fulltext search?

**Comment by jackjoesh** [comment]
> What is the SQL about fulltext search?

is this sql:

select * from table where MATCH(trade_user_white_list) AGAINST(CAST('#{userId,jdbcType=BIGINT}' AS CHAR) IN BOOLEAN MODE)

thank you for help

**Comment by terrymanu** [comment]
What feature do you use, sharding or other?

**Comment by jackjoesh** [comment]
> Which feature do you use, sharding or other?

i use sharding

**Comment by hongshunanhai** [comment]
does shardingsphere jdbc 4.1.1 support match() against('' in boolean mode) query in mysql?

**Comment by number68** [comment]
Could shardingsphere jdbc 4.1.1 support match() against('' in boolean mode) parse recently?
Upgrading to 5.0-beata is a big change and needs too much work to be done.

**Comment by tuichenchuxin** [comment]
I found master branch has already supported match() against() query.

**Comment by strongduanmu** [comment]
This sql has been supported in the master branch, you can try it. Thank you.
