### ISSUE TITLE
batch insert exception

### ISSUE THREAD

**Issue by rtj599** [apache/shardingsphere#9345]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

batch insert statements execute successfully or throw SQLFeatureNotSupportException

### Actual behavior

SQLException throws : bad SQL grammar []; nested exception is java.sql.SQLException: No value specified for parameter xx

### Reason analyze (If you can)

something wrong with sql parser

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
<insert id="xxx">
    <foreach item="item" index="index" collection="list" separator=";">
        insert into xxxxx....

    </foreach>
</insert>
```

**Comment by jingshanglu** [comment]
@rtj599 Can you try `5.0.0-alpha`?  `5.0.0-alpha` improves the support of SQL.

**Comment by rtj599** [comment]
> @rtj599 Can you try `5.0.0-alpha`? `5.0.0-alpha` improves the support of SQL.

OK, I'll try it,thx
