### ISSUE TITLE
sharding-scaling calling POST /shardingscaling/job/start  report an error 

### ISSUE THREAD

**Issue by daiyunqing** [apache/shardingsphere#9352]
**URL**
http://****:8888/shardingscaling/job/start

**parameter:**
{"ruleConfiguration":{"sourceDatasource":"slave0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  properties:\n    jdbcUrl: jdbc:mysql://*****:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC\n    username: java\n    password: 123456\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 50\n    minPoolSize: 1\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\nmaster: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  properties:\n    jdbcUrl: jdbc:mysql://****:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC\n    username: java\n    password: 123456\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 50\n    minPoolSize: 1\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n","sourceRule":"masterDataSourceName: master\nname: global_market\nslaveDataSourceNames:\n- slave0\n","destinationDataSources":{"username":"root","password":"root","url":"jdbc:mysql://***:3307/global_market_master0"}},"jobConfiguration":{"concurrency":"3"}}

**response:**

{"success":false,"errorCode":500,"errorMsg":"Cannot create property=masterDataSourceName for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration@5926db5f\n in 'string', line 1, column 1:\n    masterDataSourceName: master\n    ^\nUnable to find property 'masterDataSourceName' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration\n in 'string', line 1, column 23:\n    masterDataSourceName: master\n                          ^\n","model":null}

Migrated from a read-write separated Proxy to a read-write separated sharded Proxy

version: sharding-proxy 4.1.0 + sharding-scaling 4.1.0 +sharding-ui 4.1.0

error message :
Unable to find property 'masterDataSourceName' on class: org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration
 in 'string', line 1, column 23:
    masterDataSourceName: master

**Comment by Lucas-307** [comment]
@daiyunqing you parameter is wrong. 
refer to:  https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-scaling/usage/

**Comment by daiyunqing** [comment]
> @daiyunqing您的参数错误。
> 请参阅：[https](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-scaling/usage/) : [//shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-scaling/usage/](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-scaling/usage/)

The parameter initiated by the  Sharding-Ui 4.1.0 data scaling menu,

**Comment by Lucas-307** [comment]
@daiyunqing You can try to update your rule config.

**Comment by daiyunqing** [comment]
@Lucas-307 The source  rule config only read-write separation. new rule config is  read-write separation and  table sharding 。
**Configuration is as follows：**


**source rule config:**

schemaName: global_market
dataSources:
  master0:
    url: jdbc:mysql://**:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave0:
    url: jdbc:mysql://**:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

masterSlaveRule:
  name: global_market
  masterDataSourceName: master0
  slaveDataSourceNames: 
    - slave0 

**new dataBase rule config:**

schemaName: global_market_master0

dataSources:
  master0:
    url: jdbc:mysql://**:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  slave0:
    url: jdbc:mysql://**:3306/global_market?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

masterSlaveRule:
  name: global_market_master0
  masterDataSourceName: master0
  slaveDataSourceNames:
      - slave0
shardingRule:
  tables:
    t_coupon:
      actualDataNodes: global_market_master0.t_coupon_${0..1}
      tableStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: t_coupon_${user_id % 2}

**Comment by Lucas-307** [comment]
@daiyunqing You can try to use `curl`  command to create a http request. Just like document's example.

**Comment by daiyunqing** [comment]
@Lucas-307 all right thank u happy Chinese New Year.

**Comment by Lucas-307** [comment]
@daiyunqing You are welcome.

**Comment by daiyunqing** [comment]
@Lucas-307 Still not resolved,error message :{"success":false,"errorCode":500,"errorMsg":"Cannot create property=masterDataSourceName for JavaBean=org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration@3282b36f\n in 'string', line 1, column 1:\n    masterDataSourceName: ds0\n    ^\nUnable to find property 'masterDataSourceName' on class: **org.apache.shardingsphere.core.yaml.config.sharding.YamlShardingRuleConfiguration\n in 'string', line 1, column 23:\n    masterDataSourceName: ds0\n**                          ^\n","model":null}
