### ISSUE TITLE
SpringBoot integrated Sharding-Jdbc How to get the Distributed Primary Key after inserted

### ISSUE THREAD

**Issue by kindess** [apache/shardingsphere#9363]
When i insert a new row，but can not get id from the instance，the primary key return the value "null"。such as, noticeMapper.insert(notice)，the 'notice.getId()' can not get id. How get to the new row primary key ?

**Comment by tristaZero** [comment]
Hi, 

What you said is `getGeneratedKeys()` from `preparedStatement`?
Which version is running in your env?

**Comment by kindess** [comment]
@tristaZero springboot 2.3.4 + sharding-jdbc-spring-boot-starter 4.1.1。But, how to use or how to configure ? I have not find  way for returning to the primary key

**Comment by tristaZero** [comment]
Hi, 

Could you do some search on `getGeneratedKeys()` by Springboot?
Springboot just helps users manage the data sources, and I guess there is some interface calling `getGeneratedKeys()` of `preparedStatement` to return all the generated keys. 
Suppose you want to try the original `getGeneratedKeys()` of `preparedStatement`, you can write a demo to call this function from `ShardingSphereDataSource`. 

That way will help us figure out whether SS has a bug on this function or just a usage issue.
