### ISSUE TITLE
sharding-jdbc-spring-boot-starter auto-configuration class better to rename

### ISSUE THREAD

**Issue by maxh4** [apache/shardingsphere#9381]
Hi,

I am using sharding-jdbc-spring-boot-starter as a common sub-module in my project so that I can use some common customized classes in other sub-modules.

After writing unit tests, spring throws an error as following:

```log
Failed to instantiate [javax.sql.DataSource]: Factory method 'shardingDataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Data sources cannot be empty.
```

However, I have added ignore "DataSourceAutoConfiguration.class" annotations in spring-boot start class. This confused me for a while.

```java
@SpringBootApplication(exclude = {
        DruidDataSourceAutoConfigure.class,
        DataSourceAutoConfiguration.class,
        RabbitAutoConfiguration.class
}
```

After looking into the source code here [SpringBootConfiguration.java](https://github.com/apache/shardingsphere/blob/master/shardingsphere-jdbc/shardingsphere-jdbc-spring/shardingsphere-jdbc-core-spring/shardingsphere-jdbc-core-spring-boot-starter/src/main/java/org/apache/shardingsphere/spring/boot/SpringBootConfiguration.java)
I have updated as below, then my tests got passed.

```java
@SpringBootApplication(exclude = {
        DruidDataSourceAutoConfigure.class,
        DataSourceAutoConfiguration.class,
        SpringBootConfiguration.class, // ShardingSphereDataSourceAutoConfiguration
        RabbitAutoConfiguration.class
}
```

So I suggest renaming the class name from "SpringBootConfiguration" to "ShardingSphereDataSourceAutoConfiguration" or other similar to avoid confusion.

**Comment by tristaZero** [comment]
Hi @maxh4 ,

Do you mean `SpringBootConfiguration` of ShardingSphere has conflicts with Spring framework or others?

**Comment by maxh4** [comment]
Hi @tristaZero ,

I didn't mean any conflicts. Just a naming strategy suggestion.

My project is in this structure:
|-RootProject
  \-CommonModule
  \-ServiceModule1
  \-ServiceModule2

ServiceModules are all referencing the CommonModule, so that I can extract some common configurations to avoid redundant code.
Then I also need to write some tests in each module, so I have excluded the auto-configuration classes for features in Common, then import back in ServiceModules. This can start spring and run tests without configuration properties declared in the yaml file.

For other AutoConfiguration classes from the features I used, they are naming like:
SecurityAutoConfiguration.class,
DruidDataSourceAutoConfigure.class,
DataSourceAutoConfiguration.class,
RabbitAutoConfiguration.class

So here I suggest renaming the sharding sphere data source auto-configuration boot class to avoid confusions.

**Comment by terrymanu** [comment]
Sure, good suggestion, we are consider about change the class name for more make sense

**Comment by yu199195** [comment]
I think, ShardingSphereDataSourceAutoConfiguration is  comply with Spring-Boot specification

**Comment by yu199195** [comment]
@maxh4  thanks  good suggestion,   SpringBootConfiguration (old ) need init other bean to spring-boot, so  I think  named ShardingSphereAutoConfiguration  is reasonable. What do you think?
