### ISSUE TITLE
line 1:119 no viable alternative at input 'point,'

### ISSUE THREAD

**Issue by Suny95** [apache/shardingsphere#9413]
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
    <version>4.1.1</version>
</dependency>

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.3.2</version>
</dependency>

**Comment by Suny95** [comment]
@TableField(value = "`point`")
private Integer point;

format point to `point` , I'm fixed this problem

**Comment by terrymanu** [comment]
What is the SQL?

**Comment by jingshanglu** [comment]
It has been fix in 5.0.0-alpha version.
