### ISSUE TITLE
Can @ShardingTransactionType(TransactionType.XA) and @GlobalTransactional be used together? Will it conflict?

### ISSUE THREAD

**Issue by cielswift** [apache/shardingsphere#9419]
Can @ShardingTransactionType(TransactionType.XA) and @GlobalTransactional be used together? Will it conflict?

**Comment by tristaZero** [comment]
@yu199195  Do we have any doc to clarify such type of issue?

**Comment by yu199195** [comment]
@cielswift   hi , @GlobalTransactional  where are from?

**Comment by cielswift** [comment]
> @cielswift嗨，@GlobalTransactional从哪里来的？

seata project

**Comment by terrymanu** [comment]
ShardingSphere will manage all transaction managers.
So it is better do not use them mixed.
I don't know what happen if using @ShardingTransactionType and other annotation of other projects.
