### ISSUE TITLE
how can I find sharding-jdbc-spring-boot-starter of the version 5.0?

### ISSUE THREAD

**Issue by YeDongaidiiqu** [apache/shardingsphere#9421]
![image](https://user-images.githubusercontent.com/25131877/108302447-f4e10c80-71de-11eb-91a8-3fb27791572b.png)

**Comment by tristaZero** [comment]
Hi `hardingsphere-jdbc-core-spring-boot-starter` is the new package name. 
FYI., https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/sharding/spring-boot-starter/

**Comment by Ambitie** [comment]
I can't find shardingsphere-jdbc-core-spring-boot-starter on http://mvnrepository.com.I think shardingsphere 5 is a semi-finshed product.

**Comment by 5661954** [comment]
@Ambitie i cant get the pom from official maven repository?which repository should i setting in my maven settings.xml ?
