### ISSUE TITLE
sharding rule config 

### ISSUE THREAD

**Issue by wavelet123** [apache/shardingsphere#9454]
Hi Team,
This is not a bug.
As we want to sharding 1000 tables with table name as t_accountfriend_000, t_accountfriend_001, t_accountfriend_999 etc,while with the following rule,I can only get t_accountfriend_0,t_accountfriend_1.
Coud you please advise, how to config this sharding rule?

shardingRule:
  tables:
    t_accountfriend:
      actualDataNodes: ds_${0}.t_accountfriend_${000..999}
      tableStrategy:
        inline:
          shardingColumn: FAccountId
          algorithmExpression: t_accountfriend_${FAccountId % 1000}

Thanks

**Comment by huanghao495430759** [comment]
Hi ！ U can defind sharding algorithms  by yourself and format 0 to 000;
or only use complex groovy expressions.

**Comment by terrymanu** [comment]
The actualDataNodes  can be `ds_${0}.t_accountfriend_00${0..9},ds_${0}.t_accountfriend_0${10..99},ds_${0}.t_accountfriend_${100..999}`

More details please ref https://shardingsphere.apache.org/document/current/en/features/sharding/concept/inline-expression/
