### ISSUE TITLE
Add UT for grantStatement and revokeStatement

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#9471]
## Background
Now, `grant` and `revoke` in statement  are improved, so origin UT for it is not suitable. We need to add UT for `grant` and `revoke`.
parser UT entry:`shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java->assertSupportedSQL()`

## Solutions
1. Think about design of xxxAssert.java.
2. change expected result.(path:`shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case`)
3. The test class runs successfully(`shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java).

### eg
* #7880 

## Note
We can discuss the reasonableness of the design and then implement it.

### subtasks

- [ ]  add UT for `grant`
- [ ]  add UT for `revoke`

**Comment by HoldDie** [comment]
1

**Comment by HoldDie** [comment]
pls assign me.

**Comment by yu199195** [comment]
@HoldDie  welcome.

**Comment by terrymanu** [comment]
@Asxing There are no progress for long time, I just cancel assign to you and make the issue open to pick up.

**Comment by SalvadorRomo** [comment]
Hi Can work in  this one?? I  was going to start working on the past you already assigned but somene else already did it, so can i try this one ??

**Comment by TeslaCN** [comment]
Closes #9471 via #12037.
