### ISSUE TITLE
When I try to create a sharding rule  or datasource, I encountered this........ the corresponding version is 5.0 alpha

### ISSUE THREAD

**Issue by bestksl** [apache/shardingsphere#9494]
![image](https://user-images.githubusercontent.com/43023538/108981577-d0e26700-76c7-11eb-9256-1023d10606cb.png)
Why the exception info is null?
Why I can't execute commands like create datasources, or sharding rules? , the whole env like zookeeper, mysql , I believe they were well prepared....

**Comment by menghaoranss** [comment]
Please provide the complete stack logs.

**Comment by bestksl** [comment]
> Please provide the complete stack logs.

![image](https://user-images.githubusercontent.com/43023538/109089719-a686bd00-774c-11eb-8438-c888179b7058.png)

and matadata stored in the zookeeper...
![image](https://user-images.githubusercontent.com/43023538/109089872-f36a9380-774c-11eb-84df-61e5304b4352.png)

**Comment by terrymanu** [comment]
Hi bestksl,

Thank you for try to using the dev features. 

`create sharding rule` must before related table created.
However, NullPointException is not good enough, I will improve the error message reporting.

**Comment by tristaZero** [comment]
Hi @bestksl ,

Thanks for the feedback. 
Two of the images you provided have any sequences?
I mean, suppose you only run `create databases`, is there any exception?

**Comment by bestksl** [comment]
> Hi @bestksl ,
> 
> Thanks for the feedback.
> Two of the images you provided have any sequences?
> I mean, suppose you only run `create databases`, is there any exception?
![image](https://user-images.githubusercontent.com/43023538/109095331-75ab8580-7756-11eb-8efb-a2aab5377240.png)
emmmm.. . I can create the database normally.

**Comment by tristaZero** [comment]
@bestksl ,Thanks.

@jingshanglu  Please look at his first image. Suppose a table is created before its `table rule`, it seems an exception will happen.

**Comment by bestksl** [comment]
When I created a datasource... 
![image](https://user-images.githubusercontent.com/43023538/109459242-63ed1980-7a99-11eb-9c71-63b56fce0955.png)
Blow is the exception in backend.,
![image](https://user-images.githubusercontent.com/43023538/109459143-2ee0c700-7a99-11eb-8d60-151ebc7f60cb.png)
When I create a datasource....
![image](https://user-images.githubusercontent.com/43023538/109459306-82531500-7a99-11eb-82ab-c7a891268b53.png)

**Comment by jingshanglu** [comment]
@bestksl plz refer 
```
CREATE SHARDING RULE (
t_order [resource(ds0, ds1)] [order_id HASH_MOD("sharding-count"=4)] [generated_key another_id snowflake("worker-id"=123)],
t_item item_id mod("sharding-count"=2)
[binding_table(t_order t_item) ...]
[default_table_strategy HASH_MOD("sharding-count"=4)]
[broadcast_tables(t_order, t_item)]
)
```

**Comment by jingshanglu** [comment]
@bestksl `[]`:optional

**Comment by menghaoranss** [comment]
RDL has been refactored，please refer #9964
