### ISSUE TITLE
ShardingSphereResultSet 可以支持 last()和beforeFirst()等方法吗

### ISSUE THREAD

**Issue by yangzhongj** [apache/shardingsphere#9496]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
