### ISSUE TITLE
Add more test cases with `single` table for integration test engine

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9499]
### What' the `single table`?

Single table (单表): A table with one sharding. It can be regarded as a logic table with one actual table. Generally, it is a regular table in a database.

### Tasks
- Add the concept above to [SQL](https://shardingsphere.apache.org/document/current/cn/features/sharding/concept/sql/) in English and Mandarin
- Create `single table` in all the `init_sql`s of `shardingsphere-integration-test` (Notice: since `db.tb` SQL segment is unsupported by `H2` and `Postgre`, please add `db-types` for your test SQLs on `single table`)
- Add some of the SQL cases on `single table`

**Comment by JiekerTime** [comment]
I will try it!
