### ISSUE TITLE
HashModShardingAlgorithm can not working!

### ISSUE THREAD

**Issue by valleyG** [apache/shardingsphere#9504]
my yml setting：
          hash-mode-algorithm:
            type: HASH_MOD
            props:
              sharding-count: 10
Why is it by zero when doing routing?
![image](https://user-images.githubusercontent.com/37858395/109119395-95a36f00-777f-11eb-8341-a2a32c1c1434.png)
why this prop is 0：
no call init method?
How to solve the problem;
thinks!

**Comment by tristaZero** [comment]
Hi, 

I guess it is simple for you to work out why the `shardingCount` = 0. Just set a breakpoint at `getShardingCount()`

**Comment by valleyG** [comment]
@tristaZero 
thanks!
i have set a breakpoint at getShardingCount() and init().
but no one calls these two methods.

**Comment by tristaZero** [comment]
Hi which version is running?
If ` init()` does not execute, it is definitely you got the exception. But, ` init()` is supposed to run.

**Comment by terrymanu** [comment]
Closed because of no feedback
