### ISSUE TITLE
sharding-proxy can support mulitple schemas in one config yaml?

### ISSUE THREAD

**Issue by zealinux** [apache/shardingsphere#9515]
## Question

- multiple mysql databases in one instance (named instance-master).
- I had created instance ( instance-slave-1) for master-slave copy.
- I want to ask: 1 sharding-proxy only support 1 schema?
  - if yes, I must run multiple sharding-proxy servers for my need.☹️
  - if not, How should I configure it (config-replica-query.yaml)?

*sharding-proxy 5.0*

**Comment by terrymanu** [comment]
No, please use different config files
