### ISSUE TITLE
Add more test cases for ShardingSphereRulesBuilder if implements ResourceAware

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#9521]

**Comment by songyuequan** [comment]
can I  take it please?

**Comment by yu199195** [comment]
@songyuequan welcome join us

**Comment by songyuequan** [comment]
@terrymanu hi~  ShardingSphereRulesBuilder  is  not the implements of  ResourceAware .  should I add test cases In  ShardingSphereRulesBuilder  to   test if  all of "ShardingSphereRulesBuilder"  implement ResourceAware?   I feel confused.

**Comment by terrymanu** [comment]
Sorry, the class `ShardingSphereRulesBuilder` is refactored and pass the necessary parameter in the method signature.
I just close this issue for expired reason.
