### ISSUE TITLE
How to configure default datasource for the version of 5.0.0-alpha

### ISSUE THREAD

**Issue by VanPersies** [apache/shardingsphere#9524]
As the version of 5.0.0-alpha has removed DefaultDataSourceName setting item, how can i configure the default datasource which not uses the shardingsphere datasource?

**Comment by tristaZero** [comment]
Hi @VanPersies ,

There is no need for users to configure `default datasources` from 5.0.x, since SS will load these `default datasources` by itself.

**Comment by xhkyyy** [comment]
> Hi @VanPersies ,
> 
> There is no need for users to configure `default datasources` from 5.0.x, since SS will load these `default datasources` by itself.

if there are 3 Datasources, how does SS know which one is the default?
can you explain it in details?

**Comment by tristaZero** [comment]
SS has no needs to know which one is default ds, since it will put a single table randomly. All datasources are the `storage`s for SS.

**Comment by coolbeevip** [comment]
I only have a part of the tables that need to sharding-database and still support this scenario?

**Comment by tristaZero** [comment]
Sure @coolbeevip , please try the 5.x release.

**Comment by magicodex** [comment]
> SS has no needs to know which one is default ds, since it will put a single table randomly. All datasources are the `storage`s for SS.

hi, i use ShardingSphere v5.1 and liquibase v4.5.  it randomly select a datasource to create table?
i don't know why to remove defaultDataSourceName, but some scenarios are not satisfied now. i hope most table default create in the specified database.
`
// SingleTableRouteEngine.route0
RouteUnit routeUnit = rule.getDefaultDataSource().isPresent() // defaultDataSource is null
  ? getDefaultRouteUnit(rule.getDefaultDataSource().get()) 
  : getRandomRouteUnit(rule);
  routeContext.getRouteUnits().add(routeUnit);
`

**Comment by StackRui** [comment]
我也是不理解为什么要去掉defaultDataSourceName次配置

**Comment by StackRui** [comment]
I also don't understand why the defaultdatasourcename configuration is removed

**Comment by StackRui** [comment]
I also don't understand why the defaultdatasourcename configuration is removed

**Comment by slyang520** [comment]
Is there any conclusion to this question?

**Comment by magicodex** [comment]
> Is there any conclusion to this question?

Code Examples:

import cn.hutool.core.util.ReflectUtil;
import org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource;
import org.apache.shardingsphere.infra.metadata.ShardingSphereMetaData;
import org.apache.shardingsphere.infra.metadata.rule.ShardingSphereRuleMetaData;
import org.apache.shardingsphere.infra.rule.ShardingSphereRule;
import org.apache.shardingsphere.mode.manager.ContextManager;
import org.apache.shardingsphere.mode.metadata.MetaDataContexts;
import org.apache.shardingsphere.singletable.rule.SingleTableRule;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.Collection;
import java.util.Map;

@Component
@ConfigurationProperties(prefix = "spring.shardingsphere.custom", ignoreUnknownFields = true)
public class ShardingSphereDataSourcePostProcessor implements BeanPostProcessor {
    private String defaultDataSourceName;

    public void setDefaultDataSourceName(String defaultDataSourceName) {
        this.defaultDataSourceName = defaultDataSourceName;
    }

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof ShardingSphereDataSource) {
            ShardingSphereDataSource dataSource = (ShardingSphereDataSource) bean;
            setDefaultDataSourceName(dataSource, defaultDataSourceName);
        }

        return bean;
    }

    private void setDefaultDataSourceName(ShardingSphereDataSource dataSource, String defaultDataSourceName) {
        ContextManager contextManager = dataSource.getContextManager();
        MetaDataContexts metaDataContexts = contextManager.getMetaDataContexts();
        Map<String, ShardingSphereMetaData> metaDataMap = metaDataContexts.getMetaDataMap();
        Collection<ShardingSphereMetaData> metaDataCollection = metaDataMap.values();

        for (ShardingSphereMetaData metaData : metaDataCollection) {
            ShardingSphereRuleMetaData ruleMetaData = metaData.getRuleMetaData();
            Collection<ShardingSphereRule> rules = ruleMetaData.getRules();

            for (ShardingSphereRule rule : rules) {
                if (rule instanceof SingleTableRule) {
                    SingleTableRule singleTableRule = (SingleTableRule) rule;
                    ReflectUtil.setFieldValue(singleTableRule, "defaultDataSource", defaultDataSourceName);
                }
            }
        }
    }

}
