### ISSUE TITLE
Transaction issues

### ISSUE THREAD

**Issue by 50133142** [apache/shardingsphere#9526]
## Solved the problem of unable to find the sub-table, need to switch the data source, but the current data source is what I need, why need to switch again to find the sub-table

<img width="663" alt="51dd1db9a7b846f5417a366c5762956" src="https://user-images.githubusercontent.com/42038247/109403439-a844c080-7998-11eb-90f9-a87c1e087193.png">

**Comment by 50133142** [comment]
![image](https://user-images.githubusercontent.com/42038247/109403544-d1655100-7998-11eb-8e9c-8bb0d72ee98f.png)

**Comment by yu199195** [comment]
@50133142  You can follow the template and provide more details

**Comment by dpengjianjun** [comment]
seata版本更新太慢了，官方强烈推荐1.4版本了

**Comment by terrymanu** [comment]
Is there any one want to try it?

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.
