### ISSUE TITLE
sharding-proxy timestamp format error by using NOW() function

### ISSUE THREAD

**Issue by zealinux** [apache/shardingsphere#9544]
## Bug Report

`SELECT NOW();` then return `2021-03-01T16:26:53`

but in ORIGINAL mysql return `2021-03-01 16:24:04`

so. In application always execption:

```
Caused by: com.mysql.cj.exceptions.DataReadException: Invalid format for type 2020-12-08T09:50:01. Value 'TIMESTAMP'
```

## Version

sharding-proxy docker 5.0-alpha

**Comment by tuohai666** [comment]
I have executed this SQL on 5.0.0-RC1-SNAPSHOT version, and it works. Can you try the new version?

![image](https://user-images.githubusercontent.com/24643893/109481035-3b741800-7ab7-11eb-8a17-8dd25a71f4af.png)

**Comment by beichengjjh** [comment]
**I tried it in Navicat and the results are as follows**
![image](https://user-images.githubusercontent.com/50292345/112616094-4758bd00-8e5e-11eb-9b90-ad2527b2e771.png)

**Comment by beichengjjh** [comment]
I tried it in Navicat and the results are as follows @tuohai666 
![image](https://user-images.githubusercontent.com/50292345/112616820-247ad880-8e5f-11eb-87c3-f3e71c3094a7.png)

and  I download the new version from shardingSphere :
![image](https://user-images.githubusercontent.com/50292345/112616746-0e6d1800-8e5f-11eb-9c21-f6c9445ff3c5.png)

**Comment by tuohai666** [comment]
@beichengjjh Please clone the head codes on master branch and compile.

**Comment by tuohai666** [comment]
Please double check the version I mentioned:

![image](https://user-images.githubusercontent.com/24643893/112777508-038bd080-9075-11eb-8833-dbf95093074f.png)
![image](https://user-images.githubusercontent.com/24643893/112777520-0c7ca200-9075-11eb-94ed-b4f7cf679ae8.png)
![image](https://user-images.githubusercontent.com/24643893/112777530-143c4680-9075-11eb-8774-72045bed0426.png)

**Comment by metayx** [comment]
@

> I tried it in Navicat and the results are as follows @tuohai666
> ![image](https://user-images.githubusercontent.com/50292345/112616820-247ad880-8e5f-11eb-87c3-f3e71c3094a7.png)
> 
> and I download the new version from shardingSphere :
> ![image](https://user-images.githubusercontent.com/50292345/112616746-0e6d1800-8e5f-11eb-9c21-f6c9445ff3c5.png)

Same question, please, did you solve it?

**Comment by metayx** [comment]
@beichengjjh Same question, please, did you solve it?

**Comment by ccMoriarty** [comment]
![image](https://user-images.githubusercontent.com/35559210/128873148-e22e7a3e-4409-4c0e-8de8-a935059f80bd.png)
same question ,i can't get values
![image](https://user-images.githubusercontent.com/35559210/128873236-a2ba146e-e4d1-49b3-9e5e-9ba7fb2b42cf.png)
