### ISSUE TITLE
如何配置才能避免shardingjdbc的全局解析，A表不分库分表，但是A表执行语句会被解析，最终导致报错

### ISSUE THREAD

**Issue by 805950337** [apache/shardingsphere#9559]
1.报错信息
![image](https://user-images.githubusercontent.com/47844125/109593097-542e0d80-7b4b-11eb-8a58-826c6a1ef63c.png)

2.执行语句
insert into t_order (USER_ID,CREATE_TIME)values(#{userId},now())
3.数据库结构
DROP TABLE IF EXISTS `t_order`;
CREATE TABLE `t_order`  (
  `ID` bigint(0) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` bigint(0) NULL DEFAULT NULL COMMENT '用户ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`) USING BTREE
)
4.yml配置
![image](https://user-images.githubusercontent.com/47844125/109593442-f1894180-7b4b-11eb-82ee-39e31bf1b203.png)

5.额外说明：用传参数方式把时间传进来可以插入，当前demo是为了体现其中一个因为shardingjdbc解析未分库分表的数据表的执行语句导致执行报错，项目改造过程中有太多地方用了shardingjdbc不支持的语法或者不支持的函数，可大部分表都不进行分库分表但是都报错，比如有数据迁移用了INSERT INTO SELECT FROM #

**Comment by yu199195** [comment]
pls in english
