### ISSUE TITLE
Encrypt does not support DDL operation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9570]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Expected behavior
After I configured the encrypt rules for t_user_details, if I use logical column name to perform some DDL operations, for example:
`CREATE TABLE t_user_details (user_id INT NOT NULL, pwd VARCHAR(45))`
It will execute DDL according to the configuration rules to generate the table as follows:
![image](https://user-images.githubusercontent.com/76552510/109746421-51e1b700-7c10-11eb-838d-3755ea0e4c96.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/109746427-560dd480-7c10-11eb-8bd2-e5d3ea45eaa7.png)

### Reason analyze (If you can)
Not support this feature

Some other sql please refer to https://github.com/apache/shardingsphere/pull/9563
about issue ： https://github.com/apache/shardingsphere/issues/9497

**Comment by yu199195** [comment]
can you fix it？

**Comment by JiekerTime** [comment]
https://github.com/apache/shardingsphere/issues/9579 is more detailed and that is the same as the current issue, so close the current issue

**Comment by JiekerTime** [comment]
> can you fix it？

I will try it.

**Comment by terrymanu** [comment]
Duplicate with #9610
