### ISSUE TITLE
SQL rewrites abnormally in Encrypt

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9576]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

Assertion fails when I try to execute  `SELECT * FROM t_user u INNER JOIN t_user_item m ON u.user_id=m.user_id`.
According to the log, the SQL was rewritten as follows and throwed some exception：
![image](https://user-images.githubusercontent.com/76552510/109769710-89168f00-7c35-11eb-8327-ba1672c16f7c.png)

Obviously, this is not the expected result

You can review this by https://github.com/apache/shardingsphere/pull/9563

Try to analyze the reason:
If we don’t configure sharding rules：
![image](https://user-images.githubusercontent.com/76552510/109918456-ed972400-7cf1-11eb-844b-da44bd75ea94.png)

We will not be able to get routers and therefore cannot get RouteContext：
![image](https://user-images.githubusercontent.com/76552510/109918579-2c2cde80-7cf2-11eb-9813-ce8fd222b664.png)

When we start to rewrite, we skip the rewrite because RouteContext is empty.

It is worth noting that this type of problem can also be triggered in the case of a single table.

**Comment by tristaZero** [comment]
Please look at the case in `shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/dql/dql-integration-test-cases.xml` (`<!--TODO fix me! about issue #9570-->`).
