### ISSUE TITLE
insert into table(xx,xx) select xx,xx from dual 。Error preparing statement.  Cause: org.antlr.v4.runtime.misc.ParseCancellationException

### ISSUE THREAD

**Issue by yj951** [apache/shardingsphere#9578]
use version：5.0.0
database：mysql
question：insert into table(xx,xx) select xx,xx from dual 。 insert error
error info：no viable alternative at input 'select?,?,?fromdual'
nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.antlr.v4.runtime.misc.ParseCancellationException

**Comment by yu199195** [comment]
can you show full sql？

**Comment by jingshanglu** [comment]
@yj951 It has been fixed, new version will be ok;

**Comment by yj951** [comment]
@jingshanglu  thanks
