### ISSUE TITLE
5.X auto-generate prime key

### ISSUE THREAD

**Issue by yj951** [apache/shardingsphere#9582]
for 4.x spring.shardingsphere.datasource.sharding.tables.tablename.key-generator.type=
           spring.shardingsphere.datasource.sharding.tables.tablename.key-generator.column=

for 5.x  How should I do it

**Comment by devfat** [comment]
See the details on [User Manual](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/spring-boot-starter/sharding/)
