### ISSUE TITLE
Twice event post when refresh schema metadata

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9587]
### Problem

If users execute DDL queries, in some cases, there is the possibility that ShardingProxy may post two `refresh` events.
One is a more specific event, like `DropTableEvent`, and another one is `SchemaAlterEvent`.

I am unsure whether it is necessary to post two events together. Besides, there is only a single event is posted in other cases like `AlterTableStatementSchemaRefresher`.

### Files
- DatabaseCommunicationEngine (`refreshMetadata(executionContext)`)
- AlterTableStatementSchemaRefresher
- CreateTableStatementSchemaRefresher
- Other implements of `SchemaRefresher`

**Comment by terrymanu** [comment]
Sure, the `SchemaAlterEvent` is general event which for persist schema meta data only.
The `DropTableEvent` is for additional operation with delete single table rule from sharding rule.
The both events are necessary.
