### ISSUE TITLE
Refactor the features of shardingsphere-replica-query and shardingsphere-ha

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#9590]
The concept **Source to Replica Replication** (called Primary Secondaries or Master Slave previously) and MGR (MySQL Group Replication) relate to the function **Replication**.

The **shardingsphere-replica-query** module mainly splits read and write queries and routes to different data sources. There's no replication function in this module. So the name shardingsphere-replica-query or shardingsphere-master-slave (previous) is not appropriate for further use. It's suggested to rename the module to **shardingsphere-read-write-splitting**.

For the **shardingsphere-ha** module, it's function is check and interoperate with the database replication process.  So it's better to rename this module to **shardingsphere-db-discovery**.

- [x] Rename the module **shardingsphere-replica-query** to **shardingsphere-read-write-splitting**
- [x] Modify examples  to ReadWriteSplitting
- [x] Modify doc  to ReadWriteSplitting
- [x] Modify IT to ReadWriteSplitting
- [x] Modify RDL ReplicaQuery to ReadWriteSplitting
- [x] Modify ShardingSphere-UI to ReadWriteSplitting
- [x] Rename the module **shardingsphere-ha** to **shardingsphere-db-discovery**

Now, the concept and names are clear. We know we can combine the sharding rule and read-write-splitting rule to enable both features. Similarly, the way and the only way to enable shardingsphere-db-discovery and shardingsphere-read-write-splitting should be the combination of replication rule and read-write-splitting rule. So it's suggested to remove the logic of read write split in shardingsphere-db-discovery.

![image](https://user-images.githubusercontent.com/24643893/109959912-12f05600-7d23-11eb-9a5b-89e7d91423a4.png)

- [x] Remove the read write split logic in shardingsphere-db-discovery
- [x] Make the rule order of shardingsphere-db-discovery before shardingsphere-read-write-splitting

To enable both the features shardingsphere-db-discovery and shardingsphere-read-write-splitting by combining rules, there's more work to do. It's not as easy as the combination of shardingsphere-sharding and shardingsphere-read-write-splitting. It's because the 
topology of former is dynamic while the topology of latter is static . 

There's only one replication approach (MGR) in the shardingsphere-db-discovery module for now. MGR determines which instance is primary itself, and the result may change automatically. That's why the topology is dynamic and we could not use the routing ability of shardingsphere-read-write-splitting which topology is static.

![image](https://user-images.githubusercontent.com/24643893/109949175-06b1cc00-7d16-11eb-93c3-a7dcad70648b.png)

So we need to introduce a dynamic data source like **autoDetectedDataSourceName** which can transfer the information from shardingsphere-db-discovery by APIs like getPrimaryDataSource() and getReplicaDataSources(). The dynamic rule something like this:

![image](https://user-images.githubusercontent.com/24643893/109950072-18e03a00-7d17-11eb-9608-7ea3a7f27312.png)

The dynamic and static rules are mutually exclusive, the can not appear together.

- [x] Design the APIs of ReplicationDataSourceAware(temporary name), at least include getPrimaryDataSource()(temporary name) and getReplicaDataSources()(temporary name)
- [x] Add new rule format for autoDetectedDataSourceName in shardingsphere-read-write-splitting
- [x] Update the route logic in shardingsphere-read-write-splitting to compatible with dynamic topology

**Comment by tristaZero** [comment]
Hi, here is another solution for consideration

```sql
rules:
  - !HA # Need new name, todo
    dataSources:
      pr_ds:
        name: pr_ds # removed
        dataSourceNames:
          - ds_0
          - ds_1
          - ds_2
        replicaQuery: false # removed
        haTypeName: mgr
    haTypes:
      mgr:
        type: MGR
        props:
          groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
          zkServerLists: 'localhost:2181'
          keepAliveCron: '0/5 * * * * ?'

  - !REPLICA_QUERY # Need new name, todo
    dataSources:
      ds_0:
        primaryDataSourceName: primary_ds_0
        replicaDataSourceNames:
          - primary_ds_0_replica_0
          - primary_ds_0_replica_1
        loadBalancerName: roundRobin
      ds_1: # new
        autoAwareDataSourceName: pr_ds
        loadBalancerName: random
    loadBalancers:
      roundRobin:
        type: ROUND_ROBIN
      random:
        type: RANDOM
```

Notes,
- `HA` and `REPLICA_QUERY` need new names
- `ds_1` is an example for using `HA` and `REPLICA_QUERY` togather
- Remove `name` and `replicaQuery` of `HA` rule
