### ISSUE TITLE
Why are the keywords treated as  the identifier?

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#9604]
## Why are the keywords treated as the identifier?

Since the rule identifier is specified as IDENTIFIER_, why add unreservedWord in the identifier?
The unreserved words are the subset of the IDENTIFIER.
```
identifier
    : IDENTIFIER_ | unreservedWord
    ;
```
![image](https://user-images.githubusercontent.com/22066046/110227845-45729c80-7f37-11eb-9ed4-391c1fb8fbdf.png)

**Comment by jingshanglu** [comment]
@wgy8283335 Unreserved words can be used as variable name.

**Comment by wgy8283335** [comment]
So, should all of the keyWords be put in the 'unreservedWord' rule?

**Comment by wgy8283335** [comment]
> > So, should all of the keyWords be put in the 'unreservedWord' rule? @jingshanglu
> 
> Only a part of keywords are unreserved words. @wgy8283335

Thank you. And what kind of keywords should be unreserved words?

**Comment by jingshanglu** [comment]
> > > So, should all of the keyWords be put in the 'unreservedWord' rule? @jingshanglu
> > 
> > 
> > Only a part of keywords are unreserved words. @wgy8283335
> 
> Thank you. And what kind of keywords should be unreserved words? @jingshanglu

@wgy8283335 Each DB has its own list of reserved words, such as [MySQL](https://dev.mysql.com/doc/refman/8.0/en/keywords.html)

**Comment by Liangda-w** [comment]
Hi @jingshanglu, @wgy8283335 

I'm a also a little bit confused by `unreservedWord`. [Here ](https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm)I've found the list of reserved words in Oracle, however some of them appear in our `unreservedWord` (for example `ROLE`, `UNUSED`.... which are also defined in OracleKeyword.g4). Should we actually delete those words to keep in line with others?

**Comment by jingshanglu** [comment]
> Hi @jingshanglu, @wgy8283335
> 
> I'm a also a little bit confused by `unreservedWord`. [Here ](https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm)I've found the list of reserved words in Oracle, however some of them appear in our `unreservedWord` (for example `ROLE`, `UNUSED`.... which are also defined in OracleKeyword.g4). Should we actually delete those words to keep in line with others?

I think we should correct `unreservedword` according to the official list. @Liangda-w @wgy8283335

**Comment by wgy8283335** [comment]
@jingshanglu
To add words into unreservedWord, shall we follow this link "https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-SQL-Reserved-Words.html#GUID-55C49D1E-BE08-4C50-A9DD-8593EB925612"? 

> > Hi @jingshanglu, @wgy8283335
> > I'm a also a little bit confused by `unreservedWord`. [Here ](https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm)I've found the list of reserved words in Oracle, however some of them appear in our `unreservedWord` (for example `ROLE`, `UNUSED`.... which are also defined in OracleKeyword.g4). Should we actually delete those words to keep in line with others?
> 
> I think we should correct `unreservedword` according to the official list. @Liangda-w @wgy8283335

**Comment by Liangda-w** [comment]
> @jingshanglu
> To add words into unreservedWord, shall we follow this link "https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-SQL-Reserved-Words.html#GUID-55C49D1E-BE08-4C50-A9DD-8593EB925612"?

@wgy8283335 oh yes! I'm sorry that I looked at an older release before.
