### ISSUE TITLE
The name of the column in the encrypt scene is confused

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9608]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Expected behavior
According to the current code logic, columnName and columnLabel should be consistent：
![image](https://user-images.githubusercontent.com/76552510/110307843-5952f700-803a-11eb-94b1-3c89d8bb72c1.png)
The relevant logic is located at QueryHeaderBuilder.build

### Actual behavior
They are deferent.
![image](https://user-images.githubusercontent.com/76552510/110307620-185ae280-803a-11eb-8982-9ebdf2fcb322.png)

### Reason analyze (If you can)
There is a problem with the logic at DatabaseCommunicationEngine.containAllTablesWithColumnMetaData.
Single table has no configuration,so it has no metaData's information.
This leads to a difference between sqlStatementContext and metaData's , and the judgment is invalid.
![image](https://user-images.githubusercontent.com/76552510/110440527-b8c10d80-80f3-11eb-8d85-4ad0d6083ce1.png)

Excute SQL：'SELECT * FROM t_user u INNER JOIN t_user_item m ON u.user_id=m.user_id' to review this problem. 

# Addition
I think columnName  and columnLabel  cannot be consistent
Because columnLabel is the alias of columnName .
columnName  is actual column name.

**Comment by LeeGuoPing** [comment]
@JiekerTime Now,there is no `containAllTablesWithColumnMetaData` method in `DatabaseCommunicationEngine`, can you retry it with the latest version?

**Comment by TeslaCN** [comment]
Close due to no response.
