### ISSUE TITLE
Support DDL for encrypt

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#9610]
Support DDL for encrypt, 

We need to rewrite DDL with encrypt columns, just add new TokenGenerators which in package `org.apache.shardingsphere.encrypt.rewrite.token.generator.impl`. 

Please add new TokenGenerators with:

- [x] CREATE TABLE
- [x] ALTER TABLE

Ref #9579 and #9570

**Comment by zjcnb** [comment]
hello, i want to try it

**Comment by arthasking123** [comment]
hello, i want to try it

**Comment by terrymanu** [comment]
Welcome, I just assigned the issue, we can discuss here.
