### ISSUE TITLE
mismatched input 'WITH' expecting {SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, GRANT, REVOKE, SET, BEGIN, COMMIT, ROLLBACK, SAVEPOINT, CALL, START, RESET, SHOW}

### ISSUE THREAD

**Issue by qwy1289500966** [apache/shardingsphere#9622]
sharding-jdbc-spring-boot-starter version is  '4.0.0', log show : 
Unsupported SQL of  `WITH  RECURSIVE  r  AS (
    SELECT * FROM district WHERE "id" = ?
    UNION ALL
    SELECT district.* FROM district, r WHERE district."id" = r.parent_id
    )
    SELECT * FROM r`

how to recursive query?

**Comment by avalon5666** [comment]
Can you try the latest version?

**Comment by terrymanu** [comment]
Closed because of no feedback
