### ISSUE TITLE
Persistent configurations to local file after configuration changes in the registry center

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#9623]
We can use [RDL](https://shardingsphere.apache.org/document/current/en/features/dist-sql/rdl/) in proxy to define data source resources and rules now,  and these configurations will be persisted in the registry center. 
We consider persisting the configuration to the local file when the configuration changes to prevent configuration 
loss when the registry center fails.

The task can be divided into the following parts:

- [ ] 1. Add a switch and  configuration file path in `server.yaml` （If there is no configured file path, we need to provide a default）

- [ ] 2. Persisted to the configured or default path after the configuration in the registry center changes

**Comment by menghaoranss** [comment]
refer #9613

**Comment by JooKS-me** [comment]
Hello, I’m Kunshuai Zhu, a sophomore at Northeastern University at Qinhuangdao. My programming language is Java.  I really want to participate in summer 2021 and contribute to the ShardingSphere community(*^ω^*).  I am currently reading the  document of ShardingSphere. Could you tell me what knowledge is required to complete this task?
