### ISSUE TITLE
SqlToken Error occured in a mixed scenario of Encrypt and Sharding

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9625]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Expected behavior
Complete query normally

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/110587337-80cad080-81ae-11eb-9d5b-cd37373f9cee.png)

### Reason analyze (If you can)
SqlToken did not do sharding：
![image](https://user-images.githubusercontent.com/76552510/110590764-313ad380-81b3-11eb-862b-ad5de29fdab8.png)
This is because SqlToken  is obtained by the actual column name in Projection：
EncryptProjectionTokenGenerator.generateSQLTokens：
![image](https://user-images.githubusercontent.com/76552510/110596878-d3aa8500-81ba-11eb-8c4f-04143b28a532.png)
But the actual name of Projection is actually a logical name:
![image](https://user-images.githubusercontent.com/76552510/110597005-005e9c80-81bb-11eb-97e4-c5fabeee93d4.png)
This leads to the following situations:
![image](https://user-images.githubusercontent.com/76552510/110597119-1cfad480-81bb-11eb-8464-707dc1d2bf20.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
By PR：https://github.com/apache/shardingsphere/pull/9626

This may be similar to https://github.com/apache/shardingsphere/issues/9608

**Comment by arthasking123** [comment]
I'll try to fix it
