### ISSUE TITLE
Sharding-proxy：a slew of 'config-' files cause proxy start takes a long time 

### ISSUE THREAD

**Issue by Emitswang** [apache/shardingsphere#9628]
## Feature Request

Request to optimize the startup speed for a slew of  'config-'  files

### Is your feature request related to a problem?

In my case, there are 2000 schema config files, it's the same configuration and just have diffrent schemaName and jdbcUrl.

For each schema config file load, it need about 500ms, so the proxy will spent about 20min to start.

It's necessary to optimize the loading speed.

case show:
![image](https://user-images.githubusercontent.com/80370684/110620378-e8dfdd80-81d3-11eb-8613-50d1adcb020a.png)

### Describe the feature you would like.

A. Provide new configuration to reduce schema files number ,  like "schemaNames". We can set a list of schemaName use the same config contents.
B. Concurrent execute 'SchemaBuilder.build'.
C. Other ways which can optimize the loading speed.

**On the other hand, will the  2000 schema config cause some performance problems in run time?**

 
### Shells 

these shells to build 2000 config files

**File1:template.yaml**

```yaml
schemaName: V_SCHEMA_NAME
dataSources:
  master:
    url: jdbc:mysql://V_MASTER_IP_PORT/V_SCHEMA_NAME?serverTimezone=UTC&useSSL=false
    username: V_MASTER_NAME
    password: V_MASTER_PASSW
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 30000
    maxPoolSize: V_MASTER_POOL_SIZE
    minPoolSize: V_MASTER_POOL_SIZE
  slave:
    url: jdbc:mysql://V_SLAVE_IP_PORT/V_SCHEMA_NAME?serverTimezone=UTC&useSSL=false
    username: V_SLAVE_NAME
    password: V_SLAVE_PASSW
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 30000
    maxPoolSize: V_SLAVE_POOL_SIZE
    minPoolSize: V_SLAVE_POOL_SIZE

rules:
- !REPLICA_QUERY
  dataSources:
    db:
      name: db
      primaryDataSourceName: master
      replicaDataSourceNames:
        - slave
      loadBalancerName: random

  loadBalancers:
    round:
      type: ROUND_ROBIN
    random:
      type: RANDOM
```

**File2: create.sh**

```shell
for i in {0..19}
do

        cat proxy.create | while read schemaName master masterName masterPassw masterPool slave slaveName slavePassw slavePool
        do
                echo ${schemaName}
                rm -f config-t${i}-${schemaName}.yaml
                # copy template file
                cp template.yaml config-t${i}-${schemaName}.yaml
                # sed modify fields
                sed -i "s/schemaName: V_SCHEMA_NAME/schemaName: test${i}_${schemaName}/g;s/V_SCHEMA_NAME/${schemaName}/g;s/V_MASTER_IP_PORT/${master}/g;s/V_MASTER_NAME/${masterName}/g;s/V_MASTER_PASSW/${masterPassw}/g;s/V_MASTER_POOL_SIZE/${masterPool}/g;s/V_SLAVE_IP_PORT/${slave}/g;s/V_SLAVE_NAME/${slaveName}/g;s/V_SLAVE_PASSW/${slavePassw}/g;s/V_SLAVE_POOL_SIZE/${slavePool}/g;"  config-t${i}-${schemaName}.yaml
        done
done
```

**File3: proxy.create**

```text
sharding_test_00_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_01_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_02_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_03_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_04_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_05_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_06_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_07_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_08_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_09_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_10_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_11_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_12_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_13_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_14_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_15_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_16_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_17_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_18_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_19_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_20_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_21_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_22_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_23_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_24_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_25_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_26_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_27_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_28_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_29_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_30_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_31_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_32_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_33_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_34_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_35_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_36_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_37_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_38_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_39_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_40_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_41_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_42_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_43_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_44_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_45_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_46_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_47_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_48_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_49_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_50_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_51_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_52_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_53_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_54_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_55_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_56_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_57_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_58_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_59_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_60_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_61_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_62_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_63_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_64_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_65_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_66_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_67_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_68_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_69_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_70_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_71_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_72_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_73_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_74_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_75_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_76_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_77_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_78_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_79_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_80_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_81_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_82_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_83_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_84_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_85_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_86_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_87_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_88_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_89_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_90_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_91_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_92_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_93_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_94_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_95_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_96_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_97_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_98_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
sharding_test_99_db 127.0.0.1:3306 root root 4 127.0.0.1:3306 root root 4
```

**Comment by tristaZero** [comment]
Hi @Emitswang ,

Thanks for your feedback. Let us discuss more to work out whether we can accelerate the startup.

There are two concerns from your description, I suppose.
1. Lessen the configuration files
2. Improve the startup speed

I will keep my opinion about the first one since we always need to balance configurations' simplification and independence.
Next, let us look at the second one. I agree to parallelize `build()` of `ShardingSphereRulesBuilder`. Would you like to try to implement this improvement? Please tell me your preference so that I can figure out whether we need other contributors.

Besides, what does make you just want to leverage Proxy with read-write-spliting feature? Many of the cases are about Proxy with the sharding feature or mixed ones.

**Comment by Emitswang** [comment]
Hi @tristaZero 

I'm glad that my suggestion has been accepted. For the first point, let me briefly explain the background.

Previously, we have implemented the rule of sharding through mybatis interceptor at the business application level. That is to say, the SQL currently applied to the proxy layer is in the form of `select * from sharding_13_25_db.t_sharding_table_1 where uid =13000251`.

Current stage, we want to take over all SQL requests by using sharding-proxy. Then, without changing the business, I need to create all the DB corresponding config files so that sharding-proxy can take over all the SQL requests smoothly.

For example, if I only configure a sharding rule config file corresponding to `schemaName: sharding_db`. Business application send sql request: `select * from sharding_13_25_db.t_sharding_table_1 where uid = 13000251 `, an exception will occur:` error 1049 (42000): unknown database`.

Therefore, we need a large number of configuration files to enable the proxy to normally accept all SQL requests. In this way, we will have 2000 dataSources need to configure, although in fact, we only want to split them into 20 data source instances, so we don't use the sharding function provided by proxy, we just do read-write separation.

You may ask why business applications don't modify the SQL to `select * from sharding_db.t_sharding where uid = 13000251`.  This is mainly considered from the cost of business implement, which mainly involves the following changes:

    1. At present, there are some SQL scenarios in the business, which can't obtain the sharding rule according to SQL itself. It needs to carry out some association queries, query from the dictionary mapping table, and then rewrite the sharding rule to SQL.
    2. The business has table scanning logic traversing by table name, starting from `00_db.t_0` to `99_db.t_9` scan data one by one.

Another risk I am worried about is that 2000 table configurations will produce some large objects. Will this cause runtime exception, such as fullgc frequently or oom, even affect proxy performance.

In theory, parallelization can speed up the `build` process, and I'm preparing to make relevant modifications to verify it. If I can, I'd like to be a contributor to the project. However, as I am a novice in the project, the whole process of submitting PR is not very clear, so I need to learn it first, such as:

    1. Is the scope of change to be evaluated by myself or to be implemented after your evaluation and confirmation?
    2. If the code I submit does not meet the requirements of the project, will it wait until I finish the modification?
    3. Is it necessary to add new test cases or run the original test cases for parallelization?
    4. Is there a deadline requirement?

**Comment by tristaZero** [comment]
Hi @Emitswang ,

Thanks for your detailed explanation, which helps me get an all-sided view of your case.
I guess ShardingSphere can solve your sharding need by like `HINT` or extra configuration, but that will also bring a burden to your business code. That's fine to pick up whatever solutions you like.

Here are the response to your questions,
1. I guess we already reach a conclusion on `build()` of `ShardingSphereRulesBuilder`. Just do it.
2. Yes.
3. If the existing UT can cover your modification, a new one is unnecessary. Whereas you need a new one.
4. No exact deadline, but... maybe it is better to leave it within one or two months?

FYI. [Contributor guidance](https://shardingsphere.apache.org/community/cn/contribute/contributor/)

**Comment by tristaZero** [comment]
Hi,

If Sharding feature has no meaning to you, why do you still need read-write-splitting feature? You can still directly configure with that in business code, right?

**Comment by Emitswang** [comment]
Hi, @tristaZero 

1. We need to use Sharding feature, we need to divid the data into 10 different DB instance have different  jdbcUrl.
2. We have tried JDBC mode, but there are too many connects , there is a waste of resources, and the overall architecture is relatively complex.
3. We will eventually refine the configuration to a standard configuration file with sharding feature, but it will take a period of time, involving more business modify.

**Comment by TeslaCN** [comment]
We have done some performance enhancement after this issue, such as https://github.com/apache/shardingsphere/issues/11718. Please try the latest ShardingSphere.
