### ISSUE TITLE
Add  JAVA-API each versions of the document

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#9653]
Hi，all communities

Could you do me a small favor? We need to do a summary of the historical version of the document，So I created this task.

you  can see this : 

 [chang-history-cn](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/change-history.cn.md)

[chang-history-en](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/change-history.cn.md)

now, i will add 5.0.0-alpha version , you will add other version to this file

- [ ] 4.x document  
- [ ] 3.x document
- [ ] 2.x document
- [ ] 3.x document

Format is as follows : 

```
## 4.xxx （this is version）

### feture (like sharding, replica-query)

#### API config

```

Won't the PR be submitted yet?  you can see this : [how to contributor](https://shardingsphere.apache.org/community/en/contribute/contributor/)

**Comment by xiaoshen11** [comment]
get it
