### ISSUE TITLE
Add spring namespace each versions of the document

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#9655]
Hi，all communities

Could you do me a small favor? We need to do a summary of the historical version of the document，So I created this task.

you  can see this : 

 [chang-history-cn](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/change-history.cn.md)

[chang-history-en](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/spring-namespace/change-history.en.md)

now, i will add 5.0.0-alpha version , you will add other version to this file

- [x] 4.x document  
- [x] 3.x document
- [x] 2.x document
- [x] 1.x document

Format is as follows : 

```
## 4.xxx （this is version）

### feture (like sharding, replica-query)

#### spring  namespace config

```

Won't the PR be submitted yet?  you can see this : [how to contributor](https://shardingsphere.apache.org/community/en/contribute/contributor/)

**Comment by cwangtf** [comment]
get it
