### ISSUE TITLE
Recommend ShardingProxy Use G1 Garbage Collector

### ISSUE THREAD

**Issue by GLBB** [apache/shardingsphere#9663]
In JDK9 or higher, CMS was removed, I think g1/zgc better than cms.

**Comment by terrymanu** [comment]
Could provide performance test report of change garbage collector?

**Comment by tuohai666** [comment]
@GLBB Can you show the parameters for the G1 Garbage Collector you recommand?

**Comment by SteNicholas** [comment]
@terrymanu , @tuohai666 , IMO, the garbage collector recommend should be based on the performance of benchmark, and provide the JVM parameters benchmark involved.
@GLBB , could you help to provide corresponding benchmark report here?
