### ISSUE TITLE
ShardingSphere-Agent  Add OpenTelemetry plugin（Open Source Promotion Plan - Summer 2021）

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#9675]
Hi ，good guys

Welcome to the Shardingsphere community， in this  Task，As a mentor, I will guide you to complete the development of SharingSphere-Agent plugin。You must worry, this is a very simple task, if you would like to talk with me。Before that, you should know ByteBuddy, SPI, Java Agent, etc。

Task List

- [ ] add OpenTelemetry plugin
- [ ] add test unit
- [ ] add integration test for docker

**Comment by totalo** [comment]
Hello, can I give it a try?

**Comment by CatYangWei** [comment]
how or where  **PluginBootServiceManager** startup?

**Comment by terrymanu** [comment]
expired
