### ISSUE TITLE
best practices for sharding-proxy using Apollo

### ISSUE THREAD

**Issue by xhkyyy** [apache/shardingsphere#9682]
#### Which version of "sharding-proxy" did you use?

`sharding-proxy` ：4.1.1

#### Question

When using Apollo as a Configuration Center, what is the best solution if the configuration of the Datasource or Sharding-Rule is complex and exceeds the maximum length of the Value?

------------------------

| key  | value
| ------------- | ------------- |
| {OrchestrationName}.config.schema  | mysql-1,mysql-2,mysql-3  |
| {OrchestrationName}.config.authentication  | ... |
| {OrchestrationName}.config.props  | ...  |
| {OrchestrationName}.config.schema.{SchemeName_AAAA}.rule | `error: configuration is to long` | 
| {OrchestrationName}.config.schema.{SchemeName_AAAA}.datasource | `error: configuration is to long` | 
| {OrchestrationName}.config.schema.{SchemeName_BBBB}.rule | ...| 
| {OrchestrationName}.config.schema.{SchemeName_BBBB}.datasource | ...| 

![gh-apollo-2](https://user-images.githubusercontent.com/2297302/111253137-97a97100-864d-11eb-80b5-375b1912d86e.png)

**Comment by terrymanu** [comment]
ShardingSphere-Proxy is a production which like a database, it has own config center.
