### ISSUE TITLE
Data was inserted into inccorect table

### ISSUE THREAD

**Issue by zhkj0001** [apache/shardingsphere#9683]
Dear team,
I'm sorry to report a problem here, To be honest , i have not searched all issues here, Our team met a problem when we are using shardingSphere to insert data into a logical table.
The problem is that we have 23 physical table and one logical table. We try to insert data through logical table and every data has proper shardingColumn, but finally there were few data inserted into another physical table.
Eg. we had data with sharding column ky, then insertted into table with sharding column Joker.
by the way, we insert these data in batch manner .
Would you like to figure out what's problem is ?

**Comment by zhkj0001** [comment]
The following is the configuration: 
tpg_record:  
          actualDataNodes: master.tpg_record_$->{['KY','Joker']}
          tableStrategy:
            inline:   
              shardingColumn: thirdparty_platform
              algorithmExpression: tpg_record_$->{thirdparty_platform}

**Comment by RaigorJiang** [comment]
Hi @zhkj0001 

which version do you use? sharding-jdbc or sharding-proxy?

would you please give mere details, thank you.

**Comment by terrymanu** [comment]
No response anymore, I just close the issue.
