### ISSUE TITLE
oracle no viable alternative at input 'DROPPARTITION'

### ISSUE THREAD

**Issue by hanjinxing** [apache/shardingsphere#9694]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
5.0.0-alpha
Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
when i excute the sql, ALTER TABLE tablename DROP PARTITION partitionname, some wrong message like this:
no viable alternative at input 'DROPPARTITION'
but i exute the sql, ALTER TABLE tablename ADD PARTITION partitionname, that is ok.

before , when i used 4.1.0, this sql can run ok ,ALTER TABLE tablename DROP PARTITION partitionname

### Actual behavior
wrong message:
no viable alternative at input 'DROPPARTITION'

org.antlr.v4.runtime.misc.ParseCancellationException: null

**Comment by Liangda-w** [comment]
Hi @hanjinxing 

I think the reason behind the error `no viable alternative at input 'DROPPARTITION'` is that `alter_table_partitioning` ([document](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-TABLE.html#GUID-552E7373-BF93-477D-9DA3-B2C9386F2877)) is not supported yet (onging Oracle SQL Definition Collation #6480)

And `ALTER TABLE tablename ADD PARTITION partitionname` is identified here incorrectly

![image](https://user-images.githubusercontent.com/66914151/111853612-07ed1680-891c-11eb-8982-1a96a55e841b.png)

The error is cause by `LP_?` and `RP_?` in `oracle/DDLStatement.g4`
```
addColumnSpecification
    : ADD columnOrVirtualDefinitions columnProperties?
    ;

columnOrVirtualDefinitions
    : LP_? columnOrVirtualDefinition (COMMA_ columnOrVirtualDefinition)* RP_? | columnOrVirtualDefinition
    ;
```

it should be something like:
```
addColumnSpecification
    : ADD LP_ columnOrVirtualDefinitions RP_ columnProperties?
    ;

columnOrVirtualDefinitions
    : columnOrVirtualDefinition (COMMA_ columnOrVirtualDefinition)*
    ;
```

according to 

![image](https://user-images.githubusercontent.com/66914151/111853899-0f60ef80-891d-11eb-8bb3-50dd0258472c.png)

Hi @wgy8283335 is it right:) Can I try to help with this issue?

**Comment by wgy8283335** [comment]
@Liangda-w  ADD PARTITION or DROP PARTITION？

**Comment by Liangda-w** [comment]
> @Liangda-w ADD PARTITION or DROP PARTITION？

DROP PARTITION :)
