### ISSUE TITLE
Realizing automatic standard process through github actions.

### ISSUE THREAD

**Issue by avalon5666** [apache/shardingsphere#9697]
- [ ] Automatically publish docs to [shardingsphere-doc](https://github.com/apache/shardingsphere-doc) repository when released.
- [ ] Automate the issue standard handling process.
- [ ] Automatically publish image to docker registry when released.

**Comment by HollowMan6** [comment]
Hi! I'm a student from [Summer 2021](https://summer.iscas.ac.cn/#/org/orgdetail/apacheshardingsphere). I would like to do this project as the Summer 2021 Project. 

For automatically publish docs to shardingsphere-doc repository when released, I have a workflow which helps me automaticly sync repos from GitHub to Gitee: https://github.com/HollowMan6/LZU-Auto-COVID-Health-Report/blob/main/.github/workflows/repo-sync.yml , the mechanism behind this is such code: https://github.com/wearerequired/git-mirror-action/blob/master/git-mirror.sh . So I think such a logic can be used for realizing this feature, too. Just generate those docs then auto push commits to shardingsphere-doc repository.

For automating the issue standard handling process, I guess a workflow may not be the best way? Why not try some bots in GitHub Apps for this, such as https://github.com/marketplace/issue-label-bot . If such kind of bot can't be found, I can also help to make one. I'm the author of the LZU COVID Health Report: https://github.com/marketplace/lzu-covid-health-report , which now ranks first in GitHub MarketPlace Trending.

![image](https://user-images.githubusercontent.com/43995067/118655695-5f283e00-b81c-11eb-83a5-47a5bed73be5.png)

For automatically publish image to docker registry when released, I actually have a project that has realized this feature to push image to docker hub and also GitHub Container Registry with multiple architecture support realized by docker buildx: every time when I push a new commit, the workflow will automatically push the image with tag `latest`, and when I release a version, the released version's image will be automatically pushed to the registry tagged correctly. The workflow also supports a manual dispatch specifying the tag.
![image](https://user-images.githubusercontent.com/43995067/118653706-62bac580-b81a-11eb-9392-7dff707484ac.png)

Here's the link of my workflow file for automatically publish image to docker registry : https://github.com/HollowMan6/LZU-Auto-COVID-Health-Report/blob/main/.github/workflows/docker-publish.yml

Please tell me if I got something wrong or there's a better idea. Thanks!

**Comment by avalon5666** [comment]
@HollowMan6 I'm glad you want to participate in this project, but there are other students already involved. I'll let you know if there's any new developments.

**Comment by QiliangFan** [comment]
> 🔨 Task one: Automatically publish docs to shardingsphere-doc repository when released.

- PR1 from  `ShardingSphere-doc`: [552](https://github.com/apache/shardingsphere-doc/pull/552/files)
   - When someone commits to `master` branch, changes will exist in `preview` directory.
   - Add a workflow `Update Document`: When triggered, move files in `preview` directory to `current` directory with some necessary operations( eg. sed, rm)
- PR2: [11121](https://github.com/apache/shardingsphere/pull/11121)
   - keep the newest contents in `preview` directory
   - When release published, trigger the workflow `Update Document` in the `shardingsphere-doc` repo (need a `secret`)

- [ ] The token `PERSONAL_TOKEN` is supposed to be configured in the `shardingsphere` repo.

**Comment by tristaZero** [comment]
I just wanna confirm, that the final result of the issue-1 is,
Each release ([tag](https://github.com/apache/shardingsphere/tags)) will own its doc site built from its doc source code, right? For instance, 5.0.0-beta will be presented in the dropdown of the `Document` [header](https://shardingsphere.apache.org/).

@avalon5666 @QiliangFan

**Comment by QiliangFan** [comment]
> I just wanna confirm, that the final result of the issue-1 is,
> Each release ([tag](https://github.com/apache/shardingsphere/tags)) will own its doc site built from its doc source code, right? For instance, 5.0.0-beta will be presented in the dropdown of the `Document` [header](https://shardingsphere.apache.org/).
> 
> @avalon5666 @QiliangFan

> I just wanna confirm, that the final result of the issue-1 is,
> Each release ([tag](https://github.com/apache/shardingsphere/tags)) will own its doc site built from its doc source code, right? For instance, 5.0.0-beta will be presented in the dropdown of the `Document` [header](https://shardingsphere.apache.org/).
> 
> @avalon5666 @QiliangFan

![demo](https://z3.ax1x.com/2021/07/04/RfniGD.png)

Each release version with pattern '5.x.x' will share the directory named `5.x(current)`. While the directory named `preview` will hold on all untaged commits since last release created.

It will look like this.... [Demo site](https://shardingsphere-doc.torch-fan.site/)  🤔 

![demo1](https://z3.ax1x.com/2021/07/04/RfuiT0.png)

**Comment by avalon5666** [comment]
@tristaZero @QiliangFan 
Document header will keep current struct, and add a master version in the dropdown for master branch.
so, 5.0.0-beta will be presented in the 5.x(Current).

**Comment by tristaZero** [comment]
Got it, could we have a 5.x (Dev) only for `master branch`, as we may do some modifications according to the master (dev) programming update? Plus, we still need 5.0.0-beta (Current) for the released version. How do you think?
