### ISSUE TITLE
about actual_data_node

### ISSUE THREAD

**Issue by lwz666666** [apache/shardingsphere#9711]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

version：4.1.1
use ShardingSphere-JDBC

First question:
       Is there a problem if the real table calculated using the sharding algorithm does not exist in the actual_data_node?
In the process of using myself, I found that it can be used normally.
For example：
application.properties
```
spring.shardingsphere.sharding.tables.user.actual-data-nodes=ds.user_$->{0..1}
spring.shardingsphere.sharding.tables.user.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.user.table-strategy.inline.algorithm-expression=user_$->{id % 3}
```
Note: user_0,user_1,user_2 are tables that exist in the database
Second question：
      In the case of the first question, do I need to dynamically refresh the value of the real data node?
Looking forward to your reply，Thanks

**Comment by terrymanu** [comment]
The version 4.x is too old, please try 5.x
