### ISSUE TITLE
sharding-proxy HikariPool-1 - Failed to validate connection Possibly consider using a shorter maxLifetime value

### ISSUE THREAD

**Issue by dinofei** [apache/shardingsphere#9712]
我怎么感觉数据源的连接池配置不生效呢，已经配置maxLifetimeMilliseconds: 10000了，日志还是报HikariPool-1 - Failed to validate connection Possibly consider using a shorter maxLifetime value  这个错误. sharding-proxy一段时间后进程会挂掉，不知道和这个有没有关系。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by wzzqy** [comment]
sharding-proxy HikariPool-1 - Failed to validate connection Possibly consider using a shorter maxLifetime value
This error occurs every once in a while

  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
settings are useless
