### ISSUE TITLE
There two problems occured in single table

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9719]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy and ShardingSphere-JDBC

### Expected behavior
![image](https://user-images.githubusercontent.com/76552510/111575055-98c2d580-87e8-11eb-8d9b-d8b2a1a98a31.png)

### Actual behavior
First problem:
![image](https://user-images.githubusercontent.com/76552510/111575091-a5dfc480-87e8-11eb-87a7-7603636e45ab.png)
![image](https://user-images.githubusercontent.com/76552510/111575104-ad06d280-87e8-11eb-8f34-09e414727148.png)
![image](https://user-images.githubusercontent.com/76552510/111575110-b09a5980-87e8-11eb-9c54-77e4dc7522eb.png)

Second problem:
If you add parameter?useServerPrepStmts=true：
![image](https://user-images.githubusercontent.com/76552510/111575260-f35c3180-87e8-11eb-992b-e76cb3f207e2.png)

### Reason analyze (If you can)
First Problem：
It seems to be caused by rowType's problem.
![image](https://user-images.githubusercontent.com/76552510/111577180-c7db4600-87ec-11eb-96f1-34def854977b.png)

# You can review this problem by PR：
https://github.com/apache/shardingsphere/pull/9729

**Comment by SteNicholas** [comment]
@JiekerTime , thanks for the fixing of the problem mentioned above. I would like to review this pull request.

**Comment by JiekerTime** [comment]
> @JiekerTime , thanks for the fixing of the problem mentioned above. I would like to review this pull request.
thank! If you need help, you can contact me at any time.

**Comment by RaigorJiang** [comment]
Hello @JiekerTime 
terrymanu reopend this issue, but did not describe the reason. Can you help verify it? Does the problem still exist?
