### ISSUE TITLE
sharding-proxy can't update metadata

### ISSUE THREAD

**Issue by xhkyyy** [apache/shardingsphere#9728]
### Which version of ShardingSphere did you use?

4.1.1

### Which project did you use? 

ShardingSphere-Proxy

### Expected behavior

The metadata can be updated automatically when a DDL statement is executed.

### Actual behavior

I created a new table using sharding-proxy (DDL statements), but when I execute query statements with this table, sharding-proxy reports an error. 

![bug](https://user-images.githubusercontent.com/2297302/111592433-bc474980-8803-11eb-8af0-98ff2f751361.png)

### Reason analyze (If you can)

My guess is that sharding-proxy does not automatically update the metadata when DDL is executed.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

`create table X (id  int(3) primary key )`

`select * from X`

### Example codes for reproduce this issue (such as a github link).

none

**Comment by strongduanmu** [comment]
@xhkyyy You can upgrade to the latest version of `sharding-proxy`, which already has good support for metadata updates.

**Comment by xhkyyy** [comment]
> @xhkyyy You can upgrade to the latest version of `sharding-proxy`, which already has good support for metadata updates.

I'm using the latest version of 4.x. Do you mean to use 5.x, but this is not yet GA. 😊

**Comment by strongduanmu** [comment]
@xhkyyy Please be patient and wait for the good news. 😀 In addition, you are welcome to join the community.
