### ISSUE TITLE
GitHub action has a concurrent exception

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9751]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Expected behavior
git action's tests all pass:
![image](https://user-images.githubusercontent.com/76552510/111814178-21d72b00-8915-11eb-840d-68427457ea56.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/111814458-72e71f00-8915-11eb-9d78-93bbb7dfb658.png)
![image](https://user-images.githubusercontent.com/76552510/111814986-19332480-8916-11eb-8c00-91ea5e030fcb.png)

### Reason analyze (If you can)
Data abnormalities caused by multithreading.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
https://github.com/apache/shardingsphere/pull/9742/checks?check_run_id=2146074371

**Comment by terrymanu** [comment]
Expired issue, the Github action works fine now.
