### ISSUE TITLE
any documents error of replica-query when replica-query module refactor to read-write-splitting

### ISSUE THREAD

**Issue by huanghao495430759** [apache/shardingsphere#9758]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC and ShardingSphere-Proxy
### Expected behavior
performance-test.md 
![image](https://user-images.githubusercontent.com/34728144/111898921-00d12000-8a64-11eb-847c-cf4f7216c301.png)

### Actual behavior
refactor to 
`- !READ_WRITE_SPLITTING`

**Comment by strongduanmu** [comment]
@huanghao495430759 Are you interested in submitting a PR to improve this document?

**Comment by huanghao495430759** [comment]
> @huanghao495430759 Are you interested in submitting a PR to improve this document?

Hi @strongduanmu ,It is my pleasure, I had commited at [https://github.com/apache/shardingsphere/pull/9759](url)

**Comment by strongduanmu** [comment]
Closed by #9759
