### ISSUE TITLE
Routing problem in the single table mix read-write scenario

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9769]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC and ShardingSphere-Proxy

### Expected behavior
Datas insert into master datatsource.

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/111979394-fdab6200-8b3f-11eb-8832-6be416d0ebd0.png)
Or:
![image](https://user-images.githubusercontent.com/76552510/111979417-056b0680-8b40-11eb-8f49-a6d515c7225e.png)

### Reason analyze (If you can)
The singleTableRules has problem:
![image](https://user-images.githubusercontent.com/76552510/111979463-10259b80-8b40-11eb-8bff-e050d2c8233c.png)
In SingleTableRuleLoader.load:
![image](https://user-images.githubusercontent.com/76552510/111979641-45ca8480-8b40-11eb-860d-b2b251147e69.png)
The master-slave dataSource was overwritten, so that only one dataSource  remained.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
By PR: https://github.com/apache/shardingsphere/pull/9770

**Comment by terrymanu** [comment]
Close because of staled.
