### ISSUE TITLE
When will shardingsphere-scaling support migrating jdbc data to shardingSphereJdbc cluster?

### ISSUE THREAD

**Issue by lintingjie** [apache/shardingsphere#9772]
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-scaling/usage/
From the document, currently source type must shardingSphereJdbc.
So, when will support Jdbc to shardingSphereJdbc? Cause we don't want to use shardingSphereJdbc from the beginning of our project.

**Comment by sandynz** [comment]
Hi @lintingjie , It will be improved later. Should be in 5.0 which may be released after 1 month.
