### ISSUE TITLE
Single table not support DDL

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9782]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC and ShardingSphere-Proxy

### Expected behavior
Create a table or execute some other DDL operations.

### Actual behavior
![image](https://user-images.githubusercontent.com/76552510/112129325-4592bd80-8c02-11eb-81a9-a0bd2de14eaf.png)

### Reason analyze (If you can)
The logic in UnicastDatabaseBackendHandler.execute（） is as follows:
![image](https://user-images.githubusercontent.com/76552510/112129431-5fcc9b80-8c02-11eb-9387-2fe6d8c76fa4.png)
isComplete()：
![image](https://user-images.githubusercontent.com/76552510/112129493-6eb34e00-8c02-11eb-882a-8fea6a0a464f.png)
Single table has no configuration rules, so the execution fails.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Try to execute a ddl sql.

**Comment by jiang-wei** [comment]
I guess the newly created table is not picked up by SS to save into "unconfiguredSchemaMetaDataMap"

**Comment by jiang-wei** [comment]
In 5.0.0, the default sharding datasource is removed.
SS loads all tables at startup and configure the sharding policy on them.

For newly created tables there's no way to tell SS to load them.

**Comment by RaigorJiang** [comment]
After verification, DDL has been supported, the following is the test record:
```sql
mysql> CREATE TABLE `t_single` (
    ->   `order_id` bigint(20) NOT NULL AUTO_INCREMENT,
    ->   `user_id` int(11) NOT NULL,
    ->   `status` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
    ->   PRIMARY KEY (`order_id`)
    -> ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected (0.10 sec)

mysql> show tables;
+-----------------------+
| Tables_in_sharding_db |
+-----------------------+
| t_order_item          |
| t_order               |
| t_single              |
+-----------------------+
3 rows in set (0.00 sec)

mysql> ALTER TABLE t_single ADD remark varchar(20) DEFAULT NULL;
Query OK, 0 rows affected (0.13 sec)

mysql> TRUNCATE table t_single;
Query OK, 0 rows affected (0.04 sec)

mysql> DROP table t_single;
Query OK, 0 rows affected (0.04 sec)

```

**Comment by RaigorJiang** [comment]
The problem no longer exists, close this issue.
