### ISSUE TITLE
sql解析出错

### ISSUE THREAD

**Issue by larrychen8276** [apache/shardingsphere#9785]
无法解析下面的sql语句
` (select t.id, t.category_id, t.category_name  from ppt_p_contents t where t.type = 1 and t.show_in_home = 3 order by t.create_time desc limit 8 )  
union all  (select t.id, t.category_id, t.category_name  from ppt_p_contents t where t.type = 1 and t.show_in_home = 4 order by t.create_time desc limit 8 )  
union all  (select t.id, t.category_id, t.category_name  from ppt_p_contents t where t.type = 1 and t.show_in_home = 5 order by t.create_time desc limit 8 )  
`

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
