### ISSUE TITLE
Add test cases for OrderedSPIRegistry and OrderedServicesCache

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#9789]
- [x] Add test cases for OrderedServicesCache
- [ ] Add more test cases for OrderedSPIRegistry.getRegisteredServices(final Collection<K> types, final Class<V> orderedSPIClass) when cache hit
- [ ] Clean cache after OrderedSPIRegistry's test cases run (use reflection to clean cache map in @After method)

**Comment by totalo** [comment]
I want do it too
