### ISSUE TITLE
SS cannot configure default non-sharding policy for newly created tables from outside SS

### ISSUE THREAD

**Issue by jiang-wei** [apache/shardingsphere#9792]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
SS-jdbc
### Expected behavior
apply default non-sharding policy for newly created tables
### Actual behavior
"Cannot route table for xxx, please make sure the tables are in the same schema"

### Reason analyze (If you can)
configured two datasources in spring boot.
one for liquibase & the other for hibernate & SS

they are both created and liquibase needs some time to create the tables.

Once tables created, SS complains "cannot route" for the newly created table

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. create a table directly in the database, not through SS
2. query that table with SS
### Example codes for reproduce this issue (such as a github link).

link: #9782

**Comment by jiang-wei** [comment]
I run liquibase scripts with another datasource because #9774

**Comment by jiang-wei** [comment]
Log:

```
2021-03-23 14:48:46.199  INFO 93803 --- [           main] ShardingSphere-metadata                  : Loading 0 tables' meta data for unconfigured tables.
```

**Comment by tristaZero** [comment]
You can run `create table`  with ShardingSphere. So the question is about `create sequence`, isn't it?

**Comment by RaigorJiang** [comment]
When the system is running, the single table created outside of SS will not be perceived. 
This is not supported and does not conform to the design.
