### ISSUE TITLE
Is there any schedule for 5.0.0 release?

### ISSUE THREAD

**Issue by IcebergXTY** [apache/shardingsphere#9794]
## Question

Hi, we plan to use shardingsphere in our project. Now the latest release is 4.1.1 but we found some useful enhancement in the version 5.0.0-alpha.  As there is a big digital gap between 4.1.1 and 5.0.0(4->5) which sometimes means lots of modifications, so we can't change the version arbitrary after we determine it.

Could you tell me is there any schedule for 5.0.0 release? After all, there has bean a long time since the last release(2020.6). 

A immature advice, maybe we can release more frequent? Upgrade from 5.0.0 to 5.0.1 is easier than upgrade 4.1.1 to 5.0.0.

**Comment by strongduanmu** [comment]
@IcebergXTY I am very sorry to tell you that there is no definite release time now. Please be patient and wait for the good news. 😀 In addition, you are welcome to join the community.
