### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by peng-my** [apache/shardingsphere#9795]
![7DEA190C-3CB0-484d-9415-B63A07CA3DD3](https://user-images.githubusercontent.com/66413490/112244361-2475af80-8c8a-11eb-8d77-8faa6876d8b0.png)
Building database by shardingsphere proxy Chinese garbled

**Comment by peng-my** [comment]
vesion: 5.0.0-alpha

**Comment by terrymanu** [comment]
No enough information, I just close the issue.
