### ISSUE TITLE
Proposals on service governance and Proxy availability

### ISSUE THREAD

**Issue by juaby** [apache/shardingsphere#9797]
**Enhance service governance**

- [ ] Configuration (including parameter configuration and rule configuration)

    - [ ] Version control
    
    - [ ] integrity
    
    - [ ] Local backup

- [ ] DistSQL instruction

  - [ ] Enhanced check mechanism
  
  - [ ] Add feedback mechanisms

**Enhance Proxy availability**

- [ ] Schema isolation. Problems with individual Schema do not affect others

- [ ] Proxy loads only valid configuration rules

**Comment by menghaoranss** [comment]
I will split this issue into more tasks in the next version, I just close it now.
