### ISSUE TITLE
RMClient and TMClient  are initialized twice

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#9807]
## Question

sharding jdbc 4.1.1+seata 1.4.1

In GlobalTransactionScanner ,the method initClient is executed,
 RMClient and TMClient are initialized

In SeataATShardingTransactionManager, the method  initSeataRPCClient is executed, and RMClient and TMClient are also initialized. Someone told me that @ GlobalTransaction annotation is invalid at this time ,must rewrite GlobalTransactionScanner and remove initClient. It's strange. What's the right way

**Comment by strongduanmu** [comment]
@romantictravel01 You can refer to this article——https://www.jianshu.com/p/41ebdaf403c8.

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.
