### ISSUE TITLE
When to upgrade the Seata version? I feel like you all live in the mountains

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#9812]
## Question

The current version of Seata is 1.4.1

**Comment by strongduanmu** [comment]
@romantictravel01 At present, the main work of the SS community is focused on the development and improvement of new features of the 5.x version. There is no plan for the upgrade of the seata version. If you are interested, you are welcome to submit a PR to complete this work. 😀

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.

**Comment by terrymanu** [comment]
@romantictravel01 
It is better to participate in open source than ask for it.
If you think ShardingSphere need to be upgraded the new version of seata , just submit pull request.
It is better to re-recognize open source for you, welcome to get out of the mountains.
