### ISSUE TITLE
Concurrency Issue in TransactionalSQLExecutionHook

### ISSUE THREAD

**Issue by ymwangzq** [apache/shardingsphere#9817]
https://github.com/apache/shardingsphere/blob/2f3a4d28a64b36de3577163b22eaa63cc2ee8199/shardingsphere-transaction/shardingsphere-transaction-base/shardingsphere-transaction-base-seata-at/src/main/java/org/apache/shardingsphere/transaction/base/seata/at/TransactionalSQLExecutionHook.java#L40

When using seata AT mode, ShardingConnection.transactionType is TransactionType.BASE, so ShardingConnection.isHoldTransaction is false, too. Which let ExecutorEngine execute in parallel mode.

In ExecutorEngine.parallelExecute, there is no promise that syncExecute happens before then asyncExecute, so there is a chance that asyncExecute task run without current global transaction context.

**Comment by yu199195** [comment]
Transaction It can only be executed serially

**Comment by ymwangzq** [comment]
https://github.com/apache/shardingsphere/blob/fc05c4dbfed64edbc93287b303c6d9cd5358e6b5/shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/org/apache/shardingsphere/driver/jdbc/core/connection/ShardingSphereConnection.java#L158

**Comment by userkdg** [comment]
@ymwangzq    How is this problem?

**Comment by terrymanu** [comment]
Close because of staled.
