### ISSUE TITLE
sharding-sphere-proxy 5.x dosen't own the property of "defaultDataSourceName"

### ISSUE THREAD

**Issue by 814196912** [apache/shardingsphere#9837]
Hey.I meet with difficulties. In sharding-sphere-proxy 4.x ，YAML file can set the value of "defaultDataSourceName".However, in sharding-sphere-proxy 5.x ,  the "defaultDataSourceName" disappears.How can  I assign the fixed datasoure to store the data of the table without  sharding.

 sharding-sphere-proxy 4.x  **official document** 
![image](https://user-images.githubusercontent.com/38856046/112611439-c814ba80-8e58-11eb-8706-53bd0c3a9668.png)

sharding-sphere-proxy 5.x **official document** 
![image](https://user-images.githubusercontent.com/38856046/112611492-dbc02100-8e58-11eb-845f-9d56414564d4.png)

If I set the value of the "defaultDataSourceName" in Yaml file , the sgharding-sphere-proxy will occur in error.
![image](https://user-images.githubusercontent.com/38856046/112612357-cbf50c80-8e59-11eb-8399-7e5f7a18f6de.png)

**Comment by menghaoranss** [comment]
@814196912  refer #9524
