### ISSUE TITLE
Distributed transaction with seata AT throw a NullPoint Exceptoin

### ISSUE THREAD

**Issue by medoer** [apache/shardingsphere#9841]
### dependencies

spring-cloud-alibaba-seata for web interceptor

sharding-transaction-base-seata-at

seata-spring-boot-starter

sharding-jdbc-spring-boot-starter

###   

use   @Transactional and @ShardingTransactionType(TransactionType.BASE) 

2021-03-26 20:23:42.260 [http-nio-19010-exec-1] ERROR o.s.jdbc.datasource.DataSourceTransactionManager - [doRollbackOnCommitException : 905] - Commit exception overridden by rollback exception
java.lang.NullPointerException: null
	at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingTransactionManager.commit(SeataATShardingTransactionManager.java:110)

##

get seata GlobalTransaction instance return NULL when commit

### Service A

@Transactional
@ShardingTransactionType(TransactionType.BASE)
public void test() {
   bFeginClient.test();
  a.insert();
  throw a exception();
}

### Service B

@Transactional
@ShardingTransactionType(TransactionType.BASE)
public void test() {
  b.insert();
}

// and service b will throw the NullPoint Exception

### interceptor

import com.alibaba.cloud.seata.web.SeataHandlerInterceptor;

@Configuration
public class WebAuthConfig extends WebMvcConfigurationSupport {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SeataHandlerInterceptor()).addPathPatterns("/**");
    }
}

**Comment by medoer** [comment]
And use seata @GlobalTransactional can rollback success, but must add 

`TransactionTypeHolder.set(TransactionType.BASE)` before every persistent SQL. AND `TransactionTypeHolder.get()` return 'LOCAL'

**Comment by medoer** [comment]
add web mvc interceptor SeataHandlerInterceptor to pass the seata xid, Is there another way？

**Comment by medoer** [comment]
![image](https://user-images.githubusercontent.com/20471718/112637664-5c8f1500-8e79-11eb-89c2-de86875f7f70.png)
How can i pass the seata xid AND GlobalTransaction

**Comment by medoer** [comment]
```java
Service A
@Transactional
@ShardingTransactionType(TransactionType.BASE)
public void test() {
bFeginClient.test();
a.insert();
throw a exception();
}

Service B
// @Transactional // producer service no @Transactional annotation 
@ShardingTransactionType(TransactionType.BASE)
public void test() {
b.insert();
}

```
code like this the transactional is working, both service transaction is rollback.
 but service b get transaction type is 'LOCAL'

**Comment by medoer** [comment]
It's working when using the seata with the 1.3.0 version.

**Comment by terrymanu** [comment]
The seata version of ShardingSphere is 1.0.0, it is better to upgrade the version, please see #12739.

**Comment by a5302091** [comment]
I have the same problem with you. Have you solved it

**Comment by duanqiaoyanyu** [comment]
I have the same problem with you. how to solve it

**Comment by zhang-zhipeng** [comment]
// @Transactional // producer service no @Transactional annotation  这行代码太重要了。。。
