### ISSUE TITLE
 Is sharding-transaction-base-seata-at necessary when using @GlobalTransaction

### ISSUE THREAD

**Issue by romantictravel01** [apache/shardingsphere#9842]
Shardingjdbc  4.1.1
Shardingjdbc integrates the proxy data source of Seata, which means that shardingjdbc has the ability of Seata. Many people are used to using @Globaltransaction. This uses Seata itself. Do we still need to use shardingjdbc to integrate Seata? Can't we use Seata alone

**Comment by terrymanu** [comment]
Is the `@Globaltransaction` seata concept, please ask the seata community, thank you.
