### ISSUE TITLE
Format the loading SQL for `MySQLPrivilegeLoader`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9851]
Hi,

This issue is to format the loading SQL for `MySQLPrivilegeLoader`.

### Intro
MySQLPrivilegeLoader loads the privileges from MySQL using some of SQLs. But these SQLs do not have better definitions. 

### Task
- Add statice final variable `SELECT * FROM mysql.user WHERE (user, host) in (%s)` in `MySQLPrivilegeLoader` to replace the line 124 and refactor the function `getGlobalPrivilegeSQL()`.
- Same handling with the above for `getSchemaPrivilegeSQL()`
- Same handling with the above for `getTablePrivilegeSQL()`

### Tip
`MySQLTableMetaDataLoader` class is good example FYI.

**Comment by totalo** [comment]
hi i want to have a try ,thx

**Comment by tristaZero** [comment]
Welcome @totalo

**Comment by zhujunxxxxx** [comment]
@totalo sorry, I didn't see you want to do this, I have finished the repair. ^_^

**Comment by totalo** [comment]
> @totalo sorry, I didn't see you want to do this, I have finished the repair. ^_^

it's ok , i will try another.
