### ISSUE TITLE
Add unit test for `MySQLPrivilegeLoader`

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9852]
Hi,

### Intro
`MySQLPrivilegeLoader` is to load privileges from MySQL databases using specific SQLs. Please add a test class to test this `MySQLPrivilegeLoader` function. I assume `MySQLTableMetaDataLoaderTest` will give you some hints.

Any questions, please contact me here. :)

**Comment by zhujunxxxxx** [comment]
i'd like try
