### ISSUE TITLE
Load users and privileges from PostgreSQL

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9853]
Hi,

This issue is part of #8966  and to load the privileges from PostgreSQL. You can refer to `MySQLPrivilegeLoader` to finish this one. BTW, please give a look at #9851 for a better implement.

### Task
- Implement `PostgreSQLPrivilegeLoader `
- Add a test class for it (#9852 will give some hints).

Have a good day. :)

**Comment by herozeng** [comment]
I want have a try

**Comment by tristaZero** [comment]
Hi @herozeng ,

It's yours now.
