### ISSUE TITLE
Load users and privileges from Oracle

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9854]
Hi,

This issue is part of #8966  and to load the privileges from Oracle. You can refer to `MySQLPrivilegeLoader` to finish this one. BTW, please give a look at #9851 for a better implement.

### Task
- Implement `OraclePrivilegeLoader `
- Add a test class for it (#9852 will give some hints).

Have a good day. :)

**Comment by zhujunxxxxx** [comment]
I want to try. thanks

**Comment by strongduanmu** [comment]
@zhujunxxxxx Welcome, it has been assigned to you. 👏

**Comment by zhujunxxxxx** [comment]
@strongduanmu I'm sorry that I clicked cancel by accident. Please assign it to me again ^_^
