### ISSUE TITLE
Cuongnam13217@gmail.com 

### ISSUE THREAD

**Issue by Baoanh217** [apache/shardingsphere#9862]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

**Comment by strongduanmu** [comment]
@Baoanh217 Hi, can you describe your problem in detail?

**Comment by terrymanu** [comment]
@Baoanh217 Please do not report spammy issues again.
