### ISSUE TITLE
读写分离的负载均衡问题

### ISSUE THREAD

**Issue by mybug99** [apache/shardingsphere#9866]
数据源：3个
读写分离中：1主2从
负载均衡：ROUND_ROBIN

问题：当从属节有一个挂了，死了，还会负载均衡到挂了的从节点，导致请求的时候，一个从节点的时候会卡着直到timout因为这个挂了，1个从可以用是好的正常使用，为想请问是我需要额外配置吗？还是说没有支持这种功能？

**Comment by strongduanmu** [comment]
@mybug99 For english only, other language will not be accept.
