### ISSUE TITLE
Load balancing problem of read-write separation

### ISSUE THREAD

**Issue by mybug99** [apache/shardingsphere#9870]
Data source: 3
Read and write separation: 1 master and 2 slaves
Load balancing: ROUND_ROBIN

Problem: When one of the slave nodes hangs and dies, it will load balance to the failed slave node. When a request is made, one slave node will be stuck until the timout hangs due to this, and the load balances the other one. Usable is good for normal use. Two slave nodes are always like this, one is normal and the other is dead. I would like to ask how to shut down the dead slave node, do I need additional configuration? Or is there no support for this feature?

**Comment by dongzl** [comment]
Hi @mybug99 , you can reference  https://shardingsphere.apache.org/document/current/en/features/governance/management/registry-center/

`Disable Replica Database`

**Comment by mybug99** [comment]
> 嗨@ mybug99，您可以参考 https://shardingsphere.apache.org/document/current/en/features/governance/management/registry-center/
> 
> `Disable Replica Database`

Thanks
