### ISSUE TITLE
使用使用 SPRING 命名空间方式配置分片找不到data-source标签

### ISSUE THREAD

**Issue by SpinSi** [apache/shardingsphere#9875]
根据文档配置 
  ShardingSphere > 用户手册 > ShardingSphere-JDBC > 使用手册 > 数据分片
使用 SPRING 命名空间
maven 依赖 
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-namespace</artifactId>
            <version>5.0.0-alpha</version>
        </dependency>
**找不到下面标签**
**shardingsphere:data-source**

**Comment by menghaoranss** [comment]
@SpinSi For english only
