### ISSUE TITLE
whe shardingsphere gets wrong when mvn install 

### ISSUE THREAD

**Issue by SpriderMan** [apache/shardingsphere#9877]
git clone https://github.com/apache/shardingsphere.git；
cd shardingsphere;
mvn clean install -Prelease;

![image](https://user-images.githubusercontent.com/18304842/112961275-cceaae80-9177-11eb-8b2e-fccc1bac4656.png)

**Comment by tristaZero** [comment]
Hi, please open that `rat.txt` file and check these files mentioned in `rat.txt`. You can remove them if they are unnecessary.

**Comment by SpriderMan** [comment]
*****************************************************
Summary
-------
Generated at: 2021-03-30T16:48:04+08:00

Notes: 2
Binaries: 2
Archives: 260
Standards: 1902

Apache Licensed: 350
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

1550 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  c:/Repository/commons-codec/commons-codec/1.6/commons-codec-1.6.pom.sha1
  c:/Repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar.sha1
  c:/Repository/commons-codec/commons-codec/1.6/_remote.repositories

**Comment by SpriderMan** [comment]
> Hi, please open that `rat.txt` file and check these files mentioned in `rat.txt`. You can remove them if they are unnecessary.

*****************************************************
Summary
-------
Generated at: 2021-03-30T16:48:04+08:00

Notes: 2
Binaries: 2
Archives: 260
Standards: 1902

Apache Licensed: 350
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

1550 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  c:/Repository/commons-codec/commons-codec/1.6/commons-codec-1.6.pom.sha1
  c:/Repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar.sha1
  c:/Repository/commons-codec/commons-codec/1.6/_remote.repositories

**Comment by terrymanu** [comment]
The CI is running for every commit, please check.
