### ISSUE TITLE
Distributed Transaction dose not work with spring-data-jpa

### ISSUE THREAD

**Issue by hongroumeng** [apache/shardingsphere#9878]
- ShardingSphere-JDBC
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0-alpha</version>
</dependency>

- JPA
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
    <version>2.4.3</version>
</dependency>

- YAML
server: 
  port: 8080

spring:  
  shardingsphere:  
    props: 
      sql-show: true
    datasource:  
      common: 
        driverClassName: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
      names: db0,db1
      db0: 
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/test0
        username: postgres
        password: postgres
      db1: 
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/test1
        username: postgres
        password: postgres
    rules: 
      sharding: 
        defaultDataSourceName: db0
        defaultTableStrategy: 
          none: 
        key-generators:  
          snowflake: 
            type: SNOWFLAKE
            props: 
              worker-id: 1
        sharding-algorithms: 
          table-inline: 
            type: INLINE
            props: 
              algorithm-expression: sys_user$->{dept_id % 2}
          database-inline: 
            type: INLINE
            props: 
              algorithm-expression: db$->{channel_id % 2}
        tables: 
          sys_user: 
            keyGenerateStrategy: 
              column: id
              keyGeneratorName: snowflake
            actual-data-nodes: db$->{0..1}.sys_user$->{0..1}
            table-strategy: 
              standard: 
                sharding-column: dept_id
                sharding-algorithm-name: table-inline
            database-strategy: 
              standard: 
                sharding-column: channel_id
                sharding-algorithm-name: database-inline
          sys_dept: 
            keyGenerateStrategy: 
              column: id
              keyGeneratorName: snowflake
            actual-data-nodes: db$->{0..1}.sys_dept$->{0..1}
            table-strategy:
              inline:
                shardingColumn: id
                algorithmExpression: sys_dept$->{id % 2}
            database-strategy: 
              standard:
                sharding-column: channel_id
                sharding-algorithm-name: database-inline
        bindingTables:
            - sys_user,sys_dept
    enabled: true

- Test

1. used @GeneratedValue
![image](https://user-images.githubusercontent.com/65977610/112969876-3ec6f600-9180-11eb-86f0-91eebe2de405.png)
![image](https://user-images.githubusercontent.com/65977610/112969932-4ab2b800-9180-11eb-9da8-63a08d0d191e.png)
![image](https://user-images.githubusercontent.com/65977610/112969987-54d4b680-9180-11eb-9611-e6dcc863f97b.png)

2. no  @GeneratedValue,throw Exception
Caused by: org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save()

3. use jdbc
![image](https://user-images.githubusercontent.com/65977610/112970345-ac732200-9180-11eb-9396-b7f86d13432c.png)
![image](https://user-images.githubusercontent.com/65977610/112970387-b7c64d80-9180-11eb-87a4-efb6f9d1875d.png)

**Comment by terrymanu** [comment]
The exception does not throw from ShardingSphere, I just close it
