### ISSUE TITLE
Optimize startup time: to mach tables in DB, control same logic table only load once  

### ISSUE THREAD

**Issue by viclemon** [apache/shardingsphere#9879]
I find the startup time is too slow due to the database full tables metadata scan,
for our case. the database has 5133 tables, we are using micro service,  about 80 apps.
when we deploying the app. This cause two problems

1. Each app will load all tables metadata, in our project, many tables is same, but all table need to be load, so it's slow to start up.
2. So many app load tables in the same time makes the Database high load and CPU utilization

I debug the code find 
```java
// SchemaMetaDataLoader:84  version:4.1.1
    private static Map<String, TableMetaData> load(final Connection connection, final Collection<String> tables, final String databaseType) throws SQLException {
        try (Connection con = connection) {
            Map<String, TableMetaData> result = new LinkedHashMap<>();
            for (String each : tables) {
                result.put(each, new TableMetaData(ColumnMetaDataLoader.load(con, each, databaseType), IndexMetaDataLoader.load(con, each, databaseType)));
            }
            return result;
        }
    }

```
The for loop load all table.  Every logic table like test `(test_${0..1023})`  which need load 1024 times in all.
Sharding table have the same metadata, why not use memory to load only once for logic table
I tried like this
```java
          for (String each : tables) {
                String logicTable= StrUtils.getLogicTableName(each);
                if(!resultMeta.containsKey(logicTable)){
                    resultMeta.put(logicTable,new TableMetaData(ColumnMetaDataLoader.load(con, each, databaseType), IndexMetaDataLoader.load(con, each, databaseType)));
                }
                result.put(each, resultMeta.get(logicTable));
            }
            return result;
```
```java
public static final String SEPARATOR="_";
public static String getLogicTableName(String tableName){
        if(StringUtils.isNumeric(getSuffix(tableName))){
            return tableName.substring(0,tableName.lastIndexOf(SEPARATOR));
        }
        return tableName;

    }

public static String getSuffix(String tableName){
        return tableName.substring(tableName.lastIndexOf(SEPARATOR)+1);
    }
```
### logs
*before:*
>[INFO] -[main] ShardingMetaDataLoader.loadShardingSchemaMetaData(131) - Loading 5 logic tables' meta data.
>[INFO] -[main] SchemaMetaDataLoader.load(70) - Loading 5133 tables' meta data.
>[INFO] -[main] MultipleDataSourcesRuntimeContext.createMetaData(59) - Meta data load finished, cost 184055 milliseconds.

*after:*
>[INFO] -[main] ShardingMetaDataLoader.loadShardingSchemaMetaData(131) - Loading 5 logic tables' meta data.
>[INFO] -[main] SchemaMetaDataLoader.load(79) - MyLoading 5133 tables' meta data.
>[INFO] -[main] MultipleDataSourcesRuntimeContext.createMetaData(59) - Meta data load finished, cost 827 milliseconds.

Only use single thread, the load  time reduce almost 200 times.
So, why not use memory when loading the metadata?

**Comment by zhujunxxxxx** [comment]
Hi, I am very aware of this problem in 4.1.1, this problem appears to have been fixed in the latest version.

**Comment by viclemon** [comment]
Grate!  I'll try it

**Comment by viclemon** [comment]
Unfortunately, the latest version is not stable version
The two versions are quite different, and upgrade cost is relatively high.
I'll use my own code

**Comment by terrymanu** [comment]
The problem has resolved on 5.x
