### ISSUE TITLE
inline expression user${age<50?0:1} invalid？

### ISSUE THREAD

**Issue by cloudgyb** [apache/shardingsphere#9880]
## inline expression user${age<50?0:1} invalid？
The value of expression is always 1！Why？ 

my project configuration(Spring Boot + sharding jdbc)：

spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.60.128:13306/test?useUnicode=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.60.128:13316/test?userUnicode=true&serverTimezone=GMT%2b8
        username: root
        password: 123456
    props:
      sql:
        show: true
    sharding:
      tables:
        user:
          actual-data-nodes: db0.user${0..1},db1.user${0..1}
          database-strategy: #分库策略
            inline:
              sharding-column: age
              algorithm-expression: db${age%2}
          table-strategy:  #分表策略
            inline:
              sharding-column: age
              algorithm-expression: user${age<50?0:1}
          key-generator:
            column: id
            type: SNOWFLAKE
            worker.id: 123

**Comment by zhujunxxxxx** [comment]
please use bug report template.

**Comment by dongzl** [comment]
@cloudgyb Hi, which version do you use?

**Comment by cloudgyb** [comment]
> @cloudgyb Hi, which version do you use?

4.1.1

**Comment by terrymanu** [comment]
No response anymore, I just close the issue.
