### ISSUE TITLE
when I use "not in" and "gruop by",It merges all the groups into one group;

### ISSUE THREAD

**Issue by littttttttlePig** [apache/shardingsphere#9886]

**Comment by littttttttlePig** [comment]
**Elaboration:
  I am making a function.
Filter out the number of people recharged and the number of people who did not recharge in stage, so I used two SQL:
Filter out the number of people recharged in stage(It is normal):**

>         SELECT COUNT(DISTINCT t.role_id) `number`,t.stage_id stageId FROM t_log_stage t
>          WHERE t.role_id IN (select a.role_id FROM t_log_recharge a GROUP BY a.role_id) 
>          and t.log_date > '2021-03-16' and t.log_date < '2021-03-31' group by stage_id;

**execut result:**
![图片](https://user-images.githubusercontent.com/44159804/113114149-a42cec80-923d-11eb-908c-dd4fec7a329c.png)

**But I added a "NOT" keyword**

>         SELECT COUNT(DISTINCT t.role_id) `number`,t.stage_id stageId FROM t_log_stage t
>         WHERE t.role_id not IN (select a.role_id FROM t_log_recharge a GROUP BY a.role_id) 
>         and t.log_date > '2021-03-16' and t.log_date < '2021-03-31' group by stage_id;

**execut result:**
![图片](https://user-images.githubusercontent.com/44159804/113114276-c0c92480-923d-11eb-861f-09099b68d477.png)
### So i have a question,why I did not trigger its merge engine??

**Comment by dongzl** [comment]
Hi @littttttttlePig , I'm sorry, the `sharding-jdbc:2.0.3` is very old version, and it is not an apache version, we don't maintain it, I suggest you upgrade the new version.

**Comment by littttttttlePig** [comment]
thanks @dongzl ,I got it when I upgrade to the apache version.

**Comment by dongzl** [comment]
> thanks @dongzl ,I got it when I upgrade to the apache version.And solved a lot of strange problems.

You are welcome!
