### ISSUE TITLE
if there is a script to create a table in the code, will it randomly select a sharding-base to create?

### ISSUE THREAD

**Issue by RelaxBin** [apache/shardingsphere#9895]
When I do sharding in code that integrates with ealstic-job, when logging the runtime log of elastic-job, It create log tables in a different sharding-base each time.As shown in the figure below:
![001](https://user-images.githubusercontent.com/17397623/113235427-96c34100-92d5-11eb-81fd-6d1baafd5611.png)
![002](https://user-images.githubusercontent.com/17397623/113235436-99be3180-92d5-11eb-872b-eeb76e451533.png)

Then, for monitoring, the query will be ambiguous, which sharding-base is the correct one to query.
I don't know if I understand it correctly, please enlighten me, Thank you very much

**Comment by dongzl** [comment]
Hi @RelaxBin , which version do you use? sharding-jdbc or sharding-proxy?

I'm sorry, I don't understand for the meaning of `sharding-base`?

**Comment by RelaxBin** [comment]
> Hi @RelaxBin , which version do you use? sharding-jdbc or sharding-proxy?
> 
> I'm sorry, I don't understand for the meaning of `sharding-base`?

Sorry, that's my fault. I am expressing a sharded database.
The version is Sharding-jdbc 5.x

**Comment by dongzl** [comment]
> > Hi @RelaxBin , which version do you use? sharding-jdbc or sharding-proxy?
> > I'm sorry, I don't understand for the meaning of `sharding-base`?
> 
> Sorry, that's my fault. I am expressing a sharded database.
> The version is Sharding-jdbc 5.x

Hi @RelaxBin , can you provide the configuration of your project? or provide a demo project on the github for reproduce this problem.

**Comment by terrymanu** [comment]
This is the feature of `single-table`, we will complete the doc soon.

**Comment by TeslaCN** [comment]
The single table is already supported.
