### ISSUE TITLE
custom ShardingUpdateStatementValidator and invailld default ShardingUpdateStatementValidator 

### ISSUE THREAD

**Issue by wangkang09** [apache/shardingsphere#9911]
version:4.1.1
sharing strategy: complex sharding strategy
sharing column: memberId、referenceNum

my sharding column are memberId and billno，but the real sharding column is memberId。if in the where condition only have referenceNum，We will calculate memberId by referenceNum，and sharding by the calculated memberId。

but，the default ShardingUpdateStatementValidator  will throw excption : Can not update sharding key!
with the follow sql:
update order set referenceNum= xx where memberId = xx

i want custom ShardingUpdateStatementValidator and invailld default ShardingUpdateStatementValidator。but i cannot find a good way。i can custom a ShardingRouteDecorator，but the default ShardingRouteDecorator will also vaild

**Comment by wangkang09** [comment]
if the ShardingStatementValidatorFactory can use SPI，it will be nice

**Comment by dongzl** [comment]
`my sharding column are memberId and billno，but the real sharding column is memberId。`

Hi @wangkang09 , what's the meaning of it?  why the configuration include two sharding column, but actually only one？

can you provide the configuration of your project?

**Comment by wangkang09** [comment]
Thank you for your reply。this is my sharding algorithm
```java
@Slf4j
public class DbComplexAlgorithm implements ComplexKeysShardingAlgorithm<Comparable<?>> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Comparable<?>> shardingValue) {
        Map<String, Collection<Comparable<?>>> shardingMap = shardingValue.getColumnNameAndShardingValuesMap();
        Collection<Comparable<?>> memberIdList = shardingMap.get("member_id");
        //For historical reasons, the where conditions may not have member_id column
        if (CollectionUtils.isNotEmpty(memberIdList)) {
            return getDbs(memberIdList);
        }

        //so,we add a additional sharding key : billno
        Collection<Comparable<?>> billnoList = shardingMap.get("billno");
        //to get memberIds
        List<Long> memberId = getMemberIdFromEs(billnoList);
        return getDbs(memberId);
    }
```

**Comment by wangkang09** [comment]
> Thank you for your reply。this is my sharding algorithm
> 
> ```java
> @Slf4j
> public class DbComplexAlgorithm implements ComplexKeysShardingAlgorithm<Comparable<?>> {
>     @Override
>     public Collection<String> doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Comparable<?>> shardingValue) {
>         Map<String, Collection<Comparable<?>>> shardingMap = shardingValue.getColumnNameAndShardingValuesMap();
>         Collection<Comparable<?>> memberIdList = shardingMap.get("member_id");
>         //For historical reasons, the where conditions may not have member_id column
>         if (CollectionUtils.isNotEmpty(memberIdList)) {
>             return getDbs(memberIdList);
>         }
> 
>         //so,we add a additional sharding key : billno
>         Collection<Comparable<?>> billnoList = shardingMap.get("billno");
>         //to get memberIds
>         List<Long> memberId = getMemberIdFromEs(billnoList);
>         return getDbs(memberId);
>     }
> ```



> Thank you for your reply。this is my sharding algorithm
> 
> ```java
> @Slf4j
> public class DbComplexAlgorithm implements ComplexKeysShardingAlgorithm<Comparable<?>> {
>     @Override
>     public Collection<String> doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Comparable<?>> shardingValue) {
>         Map<String, Collection<Comparable<?>>> shardingMap = shardingValue.getColumnNameAndShardingValuesMap();
>         Collection<Comparable<?>> memberIdList = shardingMap.get("member_id");
>         //For historical reasons, the where conditions may not have member_id column
>         if (CollectionUtils.isNotEmpty(memberIdList)) {
>             return getDbs(memberIdList);
>         }
> 
>         //so,we add a additional sharding key : billno
>         Collection<Comparable<?>> billnoList = shardingMap.get("billno");
>         //to get memberIds
>         List<Long> memberId = getMemberIdFromEs(billnoList);
>         return getDbs(memberId);
>     }
> ```

@dongzl

**Comment by terrymanu** [comment]
The version 4.x is out of service, I just close this issue.
