### ISSUE TITLE
Custom algorithm bug

### ISSUE THREAD

**Issue by zhoubonet** [apache/shardingsphere#9916]
## Bug Report
![image](https://user-images.githubusercontent.com/4209701/113399590-0b2fda00-93d3-11eb-822b-8cb2fe261c94.png)

**Comment by zhoubonet** [comment]
![image](https://user-images.githubusercontent.com/4209701/113399799-64980900-93d3-11eb-8b55-5d9d7b21d4c5.png)

**Comment by dongzl** [comment]
Hi @zhoubonet , can you provide more details?

the configuration of you project? which version do you use? sharding-jdbc or sharding-proxy?

can you provide a demo project on the github to reproduce this problem, thanks?

**Comment by dongzl** [comment]
Hi @zhoubonet , can you provide more details?

the configuration of you project? which version do you use? sharding-jdbc or sharding-proxy?

can you provide a demo project on the github to reproduce this problem, thanks?

**Comment by zhoubonet** [comment]
setting Custom algorithm code debugger result
![image](https://user-images.githubusercontent.com/4209701/113645725-006a9300-96ba-11eb-903e-b1cb564b3135.png)

**Comment by RaigorJiang** [comment]
@zhoubonet 
Thanks for your report, let me have a chek.

**Comment by RaigorJiang** [comment]
Hi @zhoubonet 
because ClassBasedShardingAlgorithm implemented three interfaces, so there's a real problem here.  I'll fix it, thank you.
