### ISSUE TITLE
can not use map get result while join table query 

### ISSUE THREAD

**Issue by fox-he** [apache/shardingsphere#9922]
today i use sharding-jdbc(4.1.1) to get data from database, but when use join table query and get result fill in map ,i  only can get first table data, can not get the  secend table data. when use low wersion(4.0.1) is ok. how is work?

**Comment by dongzl** [comment]
Hi @fox-he ,can you provide the configuration of your project, or provide a demo project on github for reproduce this project?

also include the SQL of reproduce this problem.

**Comment by fox-he** [comment]
Hi Dong,  i have push a demo in my github, please find the follow link: https://github.com/fox-he/shardingsphere-demo.git . 
i use junit to test the demo. any question please send mail to me. thanks.

**Comment by fox-he** [comment]
Hi Dong,  i have push a demo in my github, please find the follow link: https://github.com/fox-he/shardingsphere-demo.git . 
i use junit to test the demo. any question please send mail to me. thanks.

**Comment by terrymanu** [comment]
Closed because of no response anymore.
