### ISSUE TITLE
How to dynamically create and modify sharding policy at runtime?

### ISSUE THREAD

**Issue by GaoFeiGit** [apache/shardingsphere#9938]
Create and modify sharding policy at runtime.

**Comment by GaoFeiGit** [comment]
Maybe i could invoke the method `ShardingSphereDataSourceFactory.createDataSource` once again,and replace the ShardingSphereDataSource bean in Spring context . is it right?

**Comment by GaoFeiGit** [comment]
I think the solution above is a way to solve the problem.But I need to close the original DataSource，so it is not safe while some operations are processing.

**Comment by terrymanu** [comment]
Please see https://shardingsphere.apache.org/document/current/en/features/governance/management/
