### ISSUE TITLE
Does the shardingsphere-scaling support mysql 8?

### ISSUE THREAD

**Issue by 206227087** [apache/shardingsphere#9962]
## Question
I'm trying to scaling the cluster for mysql8.0.17, and it has succeed with inventory data but failed with incremental data. Does the shardingsphere project support mysql 8 now? 

BTW, I tried to refactor the code in shardingsphere-scaling about mysql packet protocol, but there are still some problems.
Has anyone succeed?

**Comment by tristaZero** [comment]
Hi @Lucas-307 please look at  this one.

**Comment by Lucas-307** [comment]
@avalon5666 Hi avalon, I remember you tested with mysql-8 before, would you help @206227087 for this issue.

**Comment by avalon5666** [comment]
Pls provider exception stack, not support 8.0 default pluggable authentication caching_sha2_password yet.
