### ISSUE TITLE
Hello, do shardingsphere scaling support disaster recovery (such as master-slave switching)? How to write the code without my own implementation? For example, modify: org.apache.shardingsphere . proxy.frontend.netty.frontendchannelinboundhandler#backendconnection?

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#9965]
Hello, do shardingsphere scaling support disaster recovery (such as master-slave switching)? How to write the code without my own implementation? For example, modify: org.apache.shardingsphere . proxy.frontend.netty.frontendchannelinboundhandler#backendconnection?

**Comment by terrymanu** [comment]
scaling is for data migrate, for example, change 2 sharded databases to 4 databases

**Comment by sandynz** [comment]
Hi @wl4g , scaling is not for data synchronization currently.
