### ISSUE TITLE
Build from master,but some jars in  shardingsphere-proxy-5.0.0alpha.tar  can not find in the build target folder 

### ISSUE THREAD

**Issue by djession** [apache/shardingsphere#9966]
## Question
build the shardingsphere-proxy from master branch, the build result is different from apache-shardingsphere-5.0.0-alpha-shardingsphere-proxy-bin.tar.gz.
eg:
sphere-tracing-opentracing-5.0.0-alpha.jar
can not found the sphere-tracing-opentracing in my build result.
how can i make shardingsphere-proxy work with master branch like used apache-shardingsphere-5.0.0-alpha-shardingsphere-proxy-bin.tar.gz ?

**Comment by menghaoranss** [comment]
Please refer to `README.md` in the ROOT path of ShardingSphere master branch.

**Comment by terrymanu** [comment]
What is your expectation? 
Build `master` or `5.0.0-alpha` version?

**Comment by djession** [comment]
@terrymanu 
> What is your expectation?
> Build `master` or `5.0.0-alpha` version?

yesterday，building master and run it，via mysql-client-8 cli connect the shardingsphere-proxy，got exception：
`Thanks for using Atomikos! Evaluate http://www.atomikos.com/Main/ExtremeTransactions for advanced features and professional support
or register at http://www.atomikos.com/Main/RegisterYourDownload to disable this message and receive FREE tips & advice
[INFO ] 2021-04-07 20:25:56.468 [main] o.a.s.p.i.i.AbstractBootstrapInitializer - Database name is `MySQL`, version is `8.0.23-0ubuntu0.20.04.1`
[INFO ] 2021-04-07 20:25:56.780 [main] o.a.s.p.frontend.ShardingSphereProxy - ShardingSphere-Proxy start success.
[DEBUG] 2021-04-07 20:34:17.120 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Write to client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 7b 00 00 00 0a 38 2e 30 2e 32 33 2d 30 75 62 75 |{....8.0.23-0ubu|
|00000010| 6e 74 75 30 2e 32 30 2e 30 34 2e 31 2d 53 68 61 |ntu0.20.04.1-Sha|
|00000020| 72 64 69 6e 67 53 70 68 65 72 65 2d 50 72 6f 78 |rdingSphere-Prox|
|00000030| 79 20 35 2e 30 2e 30 2d 62 65 74 61 00 01 00 00 |y 5.0.0-beta....|
|00000040| 00 77 66 35 70 66 58 56 6a 00 4f b7 21 02 00 08 |.wf5pfXVj.O.!...|
|00000050| 00 15 00 00 00 00 00 00 00 00 00 00 6f 57 77 77 |............oWww|
|00000060| 55 51 78 65 4c 4f 6b 79 00 6d 79 73 71 6c 5f 6e |UQxeLOky.mysql_n|
|00000070| 61 74 69 76 65 5f 70 61 73 73 77 6f 72 64 00    |ative_password. |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.127 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Read from client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 3c 00 00 01 85 a6 ff 09 00 00 00 01 ff 00 00 00 |<...............|
|00000010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
|00000020| 00 00 00 00 72 6f 6f 74 00 00 63 61 63 68 69 6e |....root..cachin|
|00000030| 67 5f 73 68 61 32 5f 70 61 73 73 77 6f 72 64 00 |g_sha2_password.|
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.130 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Write to client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 2c 00 00 02 fe 6d 79 73 71 6c 5f 6e 61 74 69 76 |,....mysql_nativ|
|00000010| 65 5f 70 61 73 73 77 6f 72 64 00 77 66 35 70 66 |e_password.wf5pf|
|00000020| 58 56 6a 6f 57 77 77 55 51 78 65 4c 4f 6b 79 00 |XVjoWwwUQxeLOky.|
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.132 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Read from client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 14 00 00 03 ae 85 7e d6 fa 3b 20 a0 bc dc b6 d8 |......~..; .....|
|00000010| 8a 28 5b d4 d5 6f 74 af                         |.([..ot.        |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.137 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Write to client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 07 00 00 04 00 00 00 02 00 00 00                |...........     |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.137 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Read from client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 21 00 00 00 03 73 65 6c 65 63 74 20 40 40 76 65 |!....select @@ve|
|00000010| 72 73 69 6f 6e 5f 63 6f 6d 6d 65 6e 74 20 6c 69 |rsion_comment li|
|00000020| 6d 69 74 20 31                                  |mit 1           |
+--------+-------------------------------------------------+----------------+
[DEBUG] 2021-04-07 20:34:17.144 [ShardingSphere-Command-0] o.a.s.p.f.m.c.MySQLCommandExecutorFactory - Execute packet type: COM_QUERY, value: MySQLComQueryPacket(sql=select @@version_comment limit 1)
[DEBUG] 2021-04-07 20:34:19.032 [epollEventLoopGroup-3-1] o.a.s.db.protocol.codec.PacketCodec - Write to client 78e0025e :
          +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 22 00 00 01 ff cf 07 23 43 31 39 39 39 55 6e 6b |"......#C1999Unk|
|00000010| 6e 6f 77 6e 20 65 78 63 65 70 74 69 6f 6e 3a 20 |nown exception: |
|00000020| 5b 6e 75 6c 6c 5d                               |[null]          |
+--------+-------------------------------------------------+----------------+
[ERROR] 2021-04-07 20:34:19.042 [ShardingSphere-Command-0] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.infra.check.SQLCheckEngine.check(SQLCheckEngine.java:49)
        at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.sqlCheck(TextProtocolBackendHandlerFactory.java:92)
        at org.apache.shardingsphere.proxy.backend.text.TextProtocolBackendHandlerFactory.newInstance(TextProtocolBackendHandlerFactory.java:78)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.<init>(MySQLComQueryPacketExecutor.java:52)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecutorFactory.newInstance(MySQLCommandExecutorFactory.java:73)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.getCommandExecutor(MySQLCommandExecuteEngine.java:60)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:92)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by djession** [comment]
> What is your expectation?
> Build `master` or `5.0.0-alpha` version?

question resloved.

btw: 
when i use master branch found new requirements, that is cli connect shardingsphere-proxy must specify the schema as a direct result of the navicat can not use.
can modify this?
