### ISSUE TITLE
关于shardingscaling全量同步

### ISSUE THREAD

**Issue by aa310958153** [apache/shardingsphere#9970]
## Question
实在搞不定了 源码也下下来调试了 5.0版本
{
  "ruleConfiguration": {
    "source": {
      "type": "shardingSphereJdbc",
      "parameter": {
        "dataSource": "dataSources:\n canal2:\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  props:\n    jdbcUrl: jdbc:mysql://127.0.0.1:3306/canal2?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true\n    username: root\n    password: '868978'\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 50\n    minPoolSize: 1\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n",
        "rule": "rules:\n- !SHARDING\n  tables:\n    student:\n      actualDataNodes: canal2.student_$->{0..1}\n      logicTable: student\n      tableStrategy:\n        standard:\n          shardingColumn: id\n          shardingAlgorithmName: t_order_tbl_algorith\n  shardingAlgorithms:\n    t_order_tbl_algorith:\n      type: INLINE\n      props:\n        algorithm-expression: student_$->{id % 2}\n"
      }
    },
    "target": {
      "type": "jdbc",
      "parameter": {
        "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/canal2?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true",
        "username": "root",
        "password": "868978"
      }
    }
  },
  "jobConfiguration": {
    "concurrency": 1,
    "shardingIndex": 0
  }
}

只会生成3个Task 但是是做增量的 ，就没有看到全量的555 我的初衷是student表->迁移成3个表 student_表

**Comment by menghaoranss** [comment]
For English only. @aa310958153
