### ISSUE TITLE
2Unknown exception: [Can not route tables for `[role_relation, ssmember]`, please make sure the tables are in same schema.]

### ISSUE THREAD

**Issue by as882301** [apache/shardingsphere#9986]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Get the right result
### Actual behavior
2Unknown exception: [Can not route tables for `[role_relation, ssmember]`, please make sure the tables are in same schema.]
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
SELECT `M`.`role`,`M`.`member_id`,`M`.`member_name`,`M`.`member_avatar`,`M`.`member_mobile` FROM `role_relation` `R` LEFT JOIN `ssmember` `M` ON `M`.`member_id`=`R`.`member_id` WHERE ( R.bind_id=7 );
### Example codes for reproduce this issue (such as a github link).
SELECT `M`.`role`,`M`.`member_id`,`M`.`member_name`,`M`.`member_avatar`,`M`.`member_mobile` FROM `role_relation` `R` LEFT JOIN `ssmember` `M` ON `M`.`member_id`=`R`.`member_id` WHERE ( R.bind_id=7 );

**Comment by wangjing112** [comment]
i get other exception:

**Comment by RaigorJiang** [comment]
Hi @as882301  @wangjing112 
Could you provide your sharding configuration , and the logic SQL & actual SQL?

**Comment by as882301** [comment]
> 您好@ as882301 @ wangjing112
> 您能否提供分片配置以及逻辑SQL和实际SQL？
schemaName: sharding_db
#
dataSourceCommon:
#  username: root
#  password:
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 50
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000
#
dataSources:
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useSSL=false
   username: shop
   password: Zjw228478
 ds_2:
   url: jdbc:mysql://127.0.0.1:3306/hotel?serverTimezone=UTC&useSSL=false
   username: hotel
   password: 228478
#
rules:
- !SHARDING
 tables:
   test:
     actualDataNodes: ds_${1}.test${1}
     tableStrategy:
       standard:
         shardingColumn: id
         shardingAlgorithmName: test_inline
     keyGenerateStrategy:
       column: id
       keyGeneratorName: snowflake
 


SQL  SELECT M.role,M.member_id,M.member_name,M.member_avatar,M.member_mobile FROM role_relation R LEFT JOIN ssmember M ON M.member_id=R.member_id WHERE ( R.bind_id=7 );


ssmember  table in shop database
role_relation table in hotel database

**Comment by RaigorJiang** [comment]
OK, table `ssmember` and `role_relation` are in different databases, so it can not work.

Please see 
https://shardingsphere.apache.org/document/current/en/features/sharding/use-norms/sql/  (English)
https://shardingsphere.apache.org/document/current/cn/features/sharding/use-norms/sql/  (Chinese)

Sharding does not support cross-database relevance.

**Comment by RaigorJiang** [comment]
@as882301  
Suggestion:   make the relevance business logic in your application layer, but not in the databases.

**Comment by as882301** [comment]
> @as882301
> Suggestion: make the relevance business logic in your application layer, but not in the databases.

OK, thank you very much
