### ISSUE TITLE
Shardjing JDBC 4.x how to pull data configuration center

### ISSUE THREAD

**Issue by laiweiNo2** [apache/shardingsphere#9997]
Shardjing JDBC using zookeeper unified management configuration can realize dynamic refresh data source, but the service restart configuration information on how to take the initiative to pull configuration center

**Comment by terrymanu** [comment]
Please set `overwrite` to `true`

**Comment by laiweiNo2** [comment]
> 请设定`overwrite`为`true`

Overwrite is set to true, the local configuration overrides the configuration on the zookeeper, I hope that is a service restart is local uncovers a zookeeper, but will be subject to the configuration on the zookeeper

**Comment by terrymanu** [comment]
How to understand about "but will be subject to the configuration on the zookeeper"?

**Comment by terrymanu** [comment]
Closed because of no response anymore.
