### ISSUE TITLE
Is version 5.0.0 recommended for production?

### ISSUE THREAD

**Issue by xianshun163** [apache/shardingsphere#9999]
## Question
Is version 5.0.0 recommended for production?
we mainly use the sharding  feature   in the near future.

Is that  any suggestions?

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment]
Not for now, please test and feedback us until version 5.0.0 release

**Comment by xianshun163** [comment]
ok    ， thanks。
